### ISSUE TITLE
Model jumps when dragging to new position

### ISSUE THREAD

**Issue by Mitrasmit** [Ultimaker/Cura#100]
When clicking and holding a model, its position changes immediately to a few centimeters below the mouse pointer. This means you always have to reposition when you want to drag the model, and minute changes are therefore not possible. It does this in fee drag as well as with the x/y arrows.

It also seems to happen when you deselect the model, then select it and immediately drag it. It wants to reposition the camera view with the product centered, but when you are holding the mouse button, the whole position of the model on the platform changes.

**Comment by irrenhaus** [comment]
+1 here

**Comment by TMHogenhout** [comment]
<h3>User feedback: </h3>
It seems that the model jumps to a position relative to the pointer where it should be relative to the build-plate centre. When you load two models, the model the farest from the centre, gets the biggest displacement in the opposite direction of the build-plate centre. De model goes back to the right position after the user has clicked one of the arrows, after that the displacement starts building up again.

**Comment by nallath** [comment]
This was caused by another fix, we're working on fixing it.

**Comment by fieldOfView** [comment]
This seems to fix it for me: https://github.com/Ultimaker/Uranium/pull/65
