### ISSUE TITLE
Post-processing - Modify G-Code - TempFanTower - Updated params not applied

### ISSUE THREAD

**Issue by ingscarrero** [Ultimaker/Cura#10004]
### Application Version

4.9.1

### Platform

Mac OS Big Sur 11.3.1

### Printer

CR6 SE

### Reproduction steps

Set Change layer to an arbitrary value N, different than the original; and slicing the model.

### Actual results

Updating Change layer doesn't change the layer in which the temperature increment is applied on the generated G-Code. It seems to be using the original ( Layer 72) regardless the value that is set.  

### Expected results

Temperature increment is set every N change layers.  

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional files attached since the issue can be reproduced by following the steps

**Comment by fvrmr** [comment]
Hi @ingscarrero thank you for your report.
I assume you are using this processing script: https://github.com/5axes/Cura-Postprocessing-Scripts
If so please report your bug there.
