### ISSUE TITLE
16 extruders makes model transformation controls inaccessible

### ISSUE THREAD

**Issue by jenniferlee1818** [Ultimaker/Cura#10019]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

custom

### Reproduction steps

1. added custom printer with 16 extruders
2. activate custom printer
3. load stl

### Actual results

the extruders on the left side of GUI cover/push up some of the model transformation controls, making them inaccessible

![extruders-cover-controls](https://user-images.githubusercontent.com/44507767/122939106-91075580-d330-11eb-89e3-37d42cff9a9d.png)

### Expected results

should have access to all transformation controls

![accessible-controls](https://user-images.githubusercontent.com/44507767/122938438-fc9cf300-d32f-11eb-99aa-239cb49d60ef.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[custom3MF.zip](https://github.com/Ultimaker/Cura/files/6694951/custom3MF.zip)

**Comment by fieldOfView** [comment]
As a workaround, the Sidebar GUI plugin aligns the toolbar to the top of the window, so the transform toolbuttons will stay accessible. You will still loose a couple of the extruder buttons towards the bottom, but hey, workaround.

**Comment by jenniferlee1818** [comment]
OK I will try that.  thanks
