### ISSUE TITLE
Slicing process never ends with tree support and cross pattern

### ISSUE THREAD

**Issue by Ari-SSO** [Ultimaker/Cura#10039]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Custom Printer

### Reproduction steps

1. select tre support in a complex figure, and never end

### Actual results

never end the process.

### Expected results

end the slicing process with tree support

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_1.zip](https://github.com/Ultimaker/Cura/files/6720770/CFFFP_1.zip)

I upload the project file.

**Comment by fvrmr** [comment]
Hi @Ari-SSO thank you for your report.
I can reproduce your issue with your model. When I changed the support pattern to lines or zigzag it slices perfectly.
When the support pattern is set to cross and changed the support line distance to 1 mm is also slices.

I will discuss this issue with the team. Keep you posted!

**Comment by fvrmr** [comment]
I have created a ticket on our backlog for this issue. Devs see CURA-8361

**Comment by ThomasRahm** [comment]
I think this is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/1412
If the support density is set to something above 0% it will work.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by ThomasRahm** [comment]
Can be closed. Was fixed with https://github.com/Ultimaker/CuraEngine/commit/a0b20d8fbe29913b93b4410212471b2847af8ea3

**Comment by GregValiant** [comment]
Thanks.
