### ISSUE TITLE
missing layer parts

### ISSUE THREAD

**Issue by Reksterlord** [Ultimaker/Cura#10032]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 5 pro

### Reproduction steps

I opend a STL file and looked at it and scaled the model size to 35%, the model was OK. 
Then I sliced the model.
![file 1](https://user-images.githubusercontent.com/86447370/123346276-32242500-d558-11eb-8ed1-bb9a8cdaa4a8.png)

### Actual results

When I sliced the model and saw the 'PREVIEW' I noticed some gaps in the model after I sliced it.
After printing the model, I saw the same gaps on the print.
![file 2](https://user-images.githubusercontent.com/86447370/123346291-39e3c980-d558-11eb-99c8-37d34a603e80.png)

### Expected results

These should't be any gaps 

### Checklist of files to include

- [ ] Log file
- [x] #10033

### Additional information & file uploads

.

**Comment by fvrmr** [comment]
Hi @Reksterlord thank you for your report.
Could you share your project file (file - save project)?

**Comment by Reksterlord** [comment]
[VB4.MD](https://github.com/Ultimaker/Cura/files/6714971/VB4.MD)

**Comment by fieldOfView** [comment]
That is an STL, not a project fille. The STL file has just the geometry, but a project file would include both the geometry _and_ the settings you currently use. With a project file we can see what is going wrong. With the STL we can only admire the model.

**Comment by Anon0ne** [comment]
Having this issue also... When I rotate the part it will place gaps in different location. Just updated to 4.10 today.
![Screenshot (2)](https://user-images.githubusercontent.com/41264521/123871348-a4528c00-d901-11eb-84e1-3e429c708b31.png)
[CE5_watchstand_newV.zip](https://github.com/Ultimaker/Cura/files/6736709/CE5_watchstand_newV.zip)

**Comment by fieldOfView** [comment]
@Anon0ne in your case it looks like your problem is that Coasting is turned on. Turn it off and you gaps will go away.

**Comment by Ghostkeeper** [comment]
To create a project file, you'd go to File -> Save Project in Cura. The result is a .3mf file with extra information on how to slice the object.
