### ISSUE TITLE
Cura is unable to generate normal Bridges

### ISSUE THREAD

**Issue by s777s** [Ultimaker/Cura#10040]
### Application Version

4.9.1

### Platform

Linux

### Printer

Anet A8

### Reproduction steps

1. Enable Experimental -> Enable Bridge Settings
2. Use the default Settings
3. Load the model  (like a box. about 200mm long; 20mm width inside and 24mm outside)
4. Slice it

### Actual results

The result is definitely unprintable model with too long 200mm bridges in full length of long model.

### Expected results

It must be fine printable model with perpendicular short 20mm bridges.

### Additional information & file uploads

There is no setting to "shorten bridges (if possible)" or better the default behavior to slice model with optimal bridges length.
(I use 1mm noozle and PETG. Octopi+Klipper as control software. Extended 240x240 hot bed)

![Screenshot1-ModelInCura](https://user-images.githubusercontent.com/12828134/123535936-107d9600-d730-11eb-9cd4-30151a11040c.png)

**Comment by smartavionics** [comment]
Hi, could you please provide that model file? You'll probably need to zip it to get github to allow it to be attached. Thanks.

**Comment by GregValiant** [comment]
You might try changing your Top/Bottom Line Directions to [135,45].  Because your model is at 45° you may need to rotate the line pattern.

**Comment by fvrmr** [comment]
A project file (file - save project) would be very help full like @smartavionics mentioned please attach it as a .zip here.
