### ISSUE TITLE
Inital Layer options for coasting and adaptive layers

### ISSUE THREAD

**Issue by FountainGoat** [Ultimaker/Cura#10043]
### Is your feature request related to a problem?

When using coasting or adaptive layers for printing thin objects the initial layer adhesion fails more frequently due to less material being extruded.

### Describe the solution you'd like

Adding an option to disable adaptive layers and coasting for the initial layer. This will allow the initial layer to have the best chance of adhesion while the rest of the print can have the quality benefits of coasting and adaptive layers.

### Describe alternatives you've considered

Seperate options for initial layer for adaptive/coating but since this is only 1 layer high its necessary.

### Affected users and/or printers

Everyone using experimental features

**Comment by fvrmr** [comment]
Hi @FountainGoat thank you for your feature request.
I will bring this up for discussion with the team. Keep you posted!

**Comment by Ghostkeeper** [comment]
Adaptive layers is already disabled for the first layer. The first layer should always be printed at the Initial Layer Height.

Are you seeing that differently? Do you have a project file where the first layer is not printed at the initial layer height?

**Comment by FountainGoat** [comment]
I did have a project that printed the initial layer too thin while adaptive layers was enabled, but i am not able to reproduce it now unfortunately.

**Comment by Ghostkeeper** [comment]
Hmm, okay well that would still be a bug, if we can find a way to reproduce it...

**Comment by FountainGoat** [comment]
I have encountered the bug again and have attached my project file and screenshot. I think it only happens when the model is moved below the bed plane and sliced.
[coastingbug.zip](https://github.com/Ultimaker/Cura/files/6974081/coastingbug.zip)
![coastingbug](https://user-images.githubusercontent.com/19329003/129168488-6cb09bef-1bc9-4b6f-8ccd-849328207e6f.png)
