### ISSUE TITLE
4.10.0 tag missing in libSavitar repository

### ISSUE THREAD

**Issue by karl-nilsson** [Ultimaker/Cura#10052]
### Application Version

4.10.0

### Platform

Linux

### Printer

N/A

### Reproduction steps

N/A

### Actual results

N/A

### Expected results

N/A

### Additional information & file uploads

The most recent release in the libSavitar repo is 4.10-beta. I suspect someone forgot to tag 4.10
https://github.com/Ultimaker/libSavitar/releases

**Comment by Ghostkeeper** [comment]
Indeed, this was missing. I added the tag on the commit that was built!
