### ISSUE TITLE
supports in new version - only TREE type?

### ISSUE THREAD

**Issue by jabbermacy** [Ultimaker/Cura#10064]
### Application Version

4.10

### Platform

win 10

### Printer

mega S

### Reproduction steps

generate ANY supports gives only TREES, I don't want them

### Actual results

generate ANY supports gives only TREES, I don't want them

### Expected results

normal supports

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

generate ANY supports gives only TREES, I don't want them

**Comment by Asterchades** [comment]
Change the Support Type, then. They would ordinarily default to "Normal" but you've got them set to "Tree".

**Comment by jabbermacy** [comment]
YEP! My bad, I forgot to enable ALL settings on reinstall, thanks!
