### ISSUE TITLE
Loading issue

### ISSUE THREAD

**Issue by SSAA308** [Ultimaker/Cura#10060]
### Application Version

4.10

### Platform

windows 10

### Printer

ender 6

### Reproduction steps

Loading new version have to download every time l restart my computer

### Actual results

reload opens ultimaker 4.10

### Expected results

should open without downloading on start up pervious version started every time

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no upload
![Capture](https://user-images.githubusercontent.com/86766683/124080823-22dc3480-da8e-11eb-94d6-0e1f451386ca.JPG)

**Comment by fvrmr** [comment]
Hi @SSAA308 thank you for your bug report.
Can you share your log file? You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
