### ISSUE TITLE
Cannot restore backup / cannot save current backup

### ISSUE THREAD

**Issue by BirefringenceEffects** [Ultimaker/Cura#10068]
### Application Version

4.9.1 & 4.10

### Platform

Windows 10

### Printer

Prusa i3 Mk3/Mk3s

### Reproduction steps

Hi guys, 
I'm in a bit of a pickle here.

I tried to uninstall the "Calibration shapes" Plugin from Cura via the GUI's marketplace (I was running 4.10 at the time), then I tried to reinstall it and it just keeps saying that the plugin fails to download. 
This has extended to all plugins as it would seem. 
I also cannot restore from existing backups or save a current backup. 
It almost seems like all connectivity to the Ultimaker server is restricted somehow....
 
After this I tried to roll back to version 4.9.1 as everything was working for me in that release. which installed fine, but the issues are consistent.
Not too sure what the problem is but it's pretty much broken Cura for me....

Kind regards, 
Jack.

### Actual results

![1](https://user-images.githubusercontent.com/62273832/124237992-7c5e6500-db5b-11eb-977c-221ee7485846.png)
![2](https://user-images.githubusercontent.com/62273832/124238000-7d8f9200-db5b-11eb-8bea-3a0b2d98f211.png)
![3](https://user-images.githubusercontent.com/62273832/124238002-7e282880-db5b-11eb-8e08-9e768abe7a79.png)
![4](https://user-images.githubusercontent.com/62273832/124238005-7e282880-db5b-11eb-8d17-273774eccc74.png)
![5](https://user-images.githubusercontent.com/62273832/124238007-7ec0bf00-db5b-11eb-9184-319576163872.png)
![6](https://user-images.githubusercontent.com/62273832/124238008-7f595580-db5b-11eb-92a6-c18c355340ec.png)
![7](https://user-images.githubusercontent.com/62273832/124238011-7f595580-db5b-11eb-96c3-042bdee46401.png)
![8](https://user-images.githubusercontent.com/62273832/124238012-7ff1ec00-db5b-11eb-9125-90ce8f8f49a1.png)
![9](https://user-images.githubusercontent.com/62273832/124238014-808a8280-db5b-11eb-9614-aaaa8fff7e26.png)
![10](https://user-images.githubusercontent.com/62273832/124238017-808a8280-db5b-11eb-9d07-2d9d7a9aa064.png)

### Expected results

I should communicate with the cloud properly and let me download plugins as well as upload backups etc...

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

logfile
[cura.log](https://github.com/Ultimaker/Cura/files/6752894/cura.log)

**Comment by fvrmr** [comment]
Hi @BirefringenceEffects it looks like there is something wrong with the connection. Do you maybe have a firewall? I couldn't reproduce your issue.

**Comment by BirefringenceEffects** [comment]
Hi @fvrmr, 

Nothing out of the ordinary just windows firewall I think

**Comment by BirefringenceEffects** [comment]
I've just had a look at windows defender and it has been allowed through the firewall. 
So it shouldn't be an issue...
![11](https://user-images.githubusercontent.com/62273832/124261295-f69ae380-db73-11eb-9e1a-667d4cc76747.png)

**Comment by BirefringenceEffects** [comment]
current log file
[cura.log](https://github.com/Ultimaker/Cura/files/6753991/cura.log)

**Comment by BirefringenceEffects** [comment]
current appdata folder zipped up with .cfg file removed for privacy.
[Uploading appdata_CURA.zip…]()

**Comment by BirefringenceEffects** [comment]
[appdata_CURA.zip](https://github.com/Ultimaker/Cura/files/6754032/appdata_CURA.zip)

**Comment by BirefringenceEffects** [comment]
Okie dokie, 

I've resolved this bug/issue; it turned out to be an out of date .NET framework for windows. 
After I updated to ".NET Framework 3.5 and 4.8 for Windows 10 Version 20H2 for x64", Cura was able to communicate with the server again and I've since been able to download plugins and backup profiles as well.

I'm making this bug as closed.

Thanks, 
Jack.

**Comment by fvrmr** [comment]
Hi @BirefringenceEffects thanks for the update!
