### ISSUE TITLE
Language package problem

### ISSUE THREAD

**Issue by twosilly-2B** [Ultimaker/Cura#1006]
I try to change the language package, because my English is not very good, but I have found that the language package is not identified! "Fdmprinter.json.mo" is only the file is not identified!

![shezhi](https://cloud.githubusercontent.com/assets/21135628/18621083/e3a0aa06-7e50-11e6-9c0c-77fa7a55b31f.png)
![qq 20160919100102](https://cloud.githubusercontent.com/assets/21135628/18621085/e4d7175c-7e50-11e6-8753-54f7d89f4e0d.png)

I've also found that this is not recognized as a package of all languages.
![qq 20160919100615](https://cloud.githubusercontent.com/assets/21135628/18621087/e7f86198-7e50-11e6-8829-db82d224df5a.png)

**Comment by Ghostkeeper** [comment]
Yes, we haven't yet translated the new texts for 2.3. They are currently being translated.

Some old texts are broken too, because we renamed the FDMPrinter file that had all the setting names and descriptions. That'll be repaired once we have new translations.

**Comment by twosilly-2B** [comment]
OK! Thank you for your answers! 
@Ghostkeeper
