### ISSUE TITLE
FLYING BEAR GHOST 5 WiFi

### ISSUE THREAD

**Issue by fortan25** [Ultimaker/Cura#10070]
### Application Version

4.10.0

### Platform

Windows 10 64

### Printer

FLYING BEAR GHOST 5

### Reproduction steps

Установил плагин MKS WiFi. Плагин установился.

### Actual results

В настройках принтера не отображается кнопка настройки WiFi. Пробовал устанавливать-удалять. Ничего не помогает. В предыдущей версии всё работало без проблем.

### Expected results

Хотелось бы нормальной работы по WiFi

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2021-07-02_14-30-03](https://user-images.githubusercontent.com/55958870/124268560-56789680-db42-11eb-981b-65c106493dde.png)
![2021-07-02_14-30-03](https://user-images.githubusercontent.com/55958870/124268840-c1c26880-db42-11eb-8155-a8cd0e89ab91.png)

**Comment by fvrmr** [comment]
Hi @fortan25 thank you for your report.
Could you share this in English. I assume that your wifi plugin is not working.

**Comment by fortan25** [comment]
Good afternoon.1. Wi-fi is working on the printer-it sees the router and gets the address.2. What does the printer have to do with it, if after installing the plugin,   the Wi-fi settings button does not appear in the printer settings ?Everything worked fine on the previous version of Cura.Thanks 02.07.2021, 15:44, "Fenne" ***@***.***>: Hi @fortan25 thank you for your report.Could you share this in English. I assume that your wifi plugin is not working.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.  Сергей Бондаренкотел.  +7 928 126 43 05WhatsApp 7 928 126 43 05

**Comment by Sladerix** [comment]
I've problems too.
Cura is at version 4.10.0, MKS is at version 1.2.2 but in the Printer Preferences i don't see anymore the button "MKS Wifi"
![Schermata 2021-07-06 alle 11 08 25](https://user-images.githubusercontent.com/6717214/124574279-9a251600-de4a-11eb-8187-6414ba26ba86.png)

**Comment by fvrmr** [comment]
It is not an issue with Cura but with the plugin. The plugin is only supported till 4.9 See: https://github.com/Jeredian/mks-wifi-plugin/issues/171

I will close this issue since this is not something we will fix.

**Comment by SupersADF** [comment]
if the plugin doesn't work follow these steps:
1) open plugin.json in folder C:\Users\$USERNAME\AppData\Roaming\cura\4.10\plugins\MKSWifiPlugin\MKSWifiPlugin, where $USERNAME - you user name
2) edit "maximum_cura_version": "4.9" to "maximum_cura_version": "4.10"
3) add "7.6.0" in "supported_sdk_versions" like this
 "supported_sdk_versions": [
        "7.1.0",
        "7.2.0",
        "7.3.0",
        "7.4.0",
        "7.5.0",
        "7.6.0"
    ],
4) run Cura and config your printer!
