### ISSUE TITLE
(4.10.0) Cannot turn off Prime Blob

### ISSUE THREAD

**Issue by mothnox** [Ultimaker/Cura#10074]
### Application Version

4.10.0

### Platform

Manjaro Linux

### Printer

Creality Ender 5 Plus

### Reproduction steps

1. Import and slice a model.
2. Print model. 

### Actual results

A prime blob is printed first, before the model. 

### Expected results

Cura would not default to having prime blob enabled, or would allow the setting to be shown so that it can be disabled. 

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

The setting for "Enable Prime Blob" cannot be shown, with it displaying the message "This setting has been hidden by the active machine and will not be visible". 
[CE5P_supports_test.3mf.zip](https://github.com/Ultimaker/Cura/files/6757674/CE5P_supports_test.3mf.zip)

**Comment by Ghostkeeper** [comment]
The setting is not visible because the prime blob command itself, G280, is not supported by Creality Ender 5 Plus. They implemented something that behaves similarly in the start g-code. You'd have to adjust the start g-code to remove it.
