### ISSUE TITLE
Unable to Slice with current settings. Zhop speed

### ISSUE THREAD

**Issue by jamesblen** [Ultimaker/Cura#10083]
### Application Version

4.10.0

### Platform

Windows 10 Pro 

### Printer

Monoprice mini V2

### Reproduction steps

1. Downloaded and uninstalled 4.9 completely and installed 4.10.0
2. Added the Monoprice mini V2
3. Now Cura won't slice

### Actual results

Cura does not work

### Expected results

Expected it to work as well as 4.9 but it doesn't
[Bathroom Mucket V5 L v2.zip](https://github.com/Ultimaker/Cura/files/6759884/Bathroom.Mucket.V5.L.v2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

The file I sent you worked with 4.9

**Comment by GregValiant** [comment]
Try going to Speed | Z Hop Speed and set it to 1.5.  If it isn't visible then use the drop down list next to the search box and set visibility to "All".
The Max Z Speed for your printer is 1.5 and the default for the Z Hop speed is higher than that.  That could be the reason it won't slice.

**Comment by fvrmr** [comment]
I will discuss this with the team, keep you posted!

**Comment by GregValiant** [comment]
@fvrmr I left a post on #10085 .  It appears that the problem rests in the definition file.

**Comment by jamesblen** [comment]
Thank you for your response. Agreed.

**Comment by fvrmr** [comment]
Closing since it should be fixed for next release.
