### ISSUE TITLE
Cura crashes at end of slicing under Macos 11.3.1 (Big Sur)

### ISSUE THREAD

**Issue by gcusick** [Ultimaker/Cura#10088]
### Application Version

4.10.0

### Platform

Macos 11.3.1 (Big Sur)

### Printer

Monoprice Mini 

### Reproduction steps

Created model in Fusion 360;
Used Fusion 360 Tools>Make>3D Print to send mesh to Cura
Rotated model on build plate
Sliced in Cura (took 3 button presses to start slicing)
Slicing ran
Cura crashed, showing Macos crash report

### Actual results

Cura crashed 

### Expected results

Sliced model ready for printing (Save to File, Print with Octoprint)

This is the behaviour under Cura 4.8.0

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6763265/cura.log)

**Comment by nallath** [comment]
Thanks for reporting it! It should be fixed for the next release!
