### ISSUE TITLE
Camera fliped

### ISSUE THREAD

**Issue by fredlamour** [Ultimaker/Cura#10089]
### Application Version

4.10.0

### Platform

WIndows 10

### Printer

Ender 3 V2

### Reproduction steps

1. Connect Cura to octoprint
2. Open supervise tab 

### Actual results

the camera is flipped.
the option is available in octoprint to rotate the camera but in Cura the original image is sent

### Expected results

add option to rotate camera

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing to add

**Comment by nallath** [comment]
Please report issues about the octoprint plugin with repository of the plugin: https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
