### ISSUE TITLE
Support roof ignoring z-distance for thin structures

### ISSUE THREAD

**Issue by avogra** [Ultimaker/Cura#1009]
Version is Cura 2.3.0 win64 from 2016-09-08

Look at the following screeshots. Layer height is 0.1mm, min. z-distance 0.1mm too.

This is the first layer of the part, that is to be supported:

![cura thinsupport layer0](https://cloud.githubusercontent.com/assets/12623449/18650892/234a032e-7ec8-11e6-907b-c599576511ee.png)

This is 2 layers before the supported structure, which looks fine:

![cura thinsupport layer-2](https://cloud.githubusercontent.com/assets/12623449/18650766/25d3bbea-7ec7-11e6-94e8-3570ba92fdbc.png)

And this is the layer just below the part:

![cura thinsupport layer-1](https://cloud.githubusercontent.com/assets/12623449/18650782/3bac2ace-7ec7-11e6-9a32-705586245215.png)

In the large area, there is no material as expected, but the thin structures have support layers here. The support roof will be bonded tightly. In the enlarged view of the same layer, there is a bit of support lines around the edge of the large area too. Is this intended?

![cura thinsupportb layer-1](https://cloud.githubusercontent.com/assets/12623449/18651275/8f3f16d0-7eca-11e6-8363-06c25e04d779.png)

**Comment by Vandrasc** [comment]
Is this still an issue in the current version 3.2 or 3.3? If so, could you please attach a project file to the ticket so we can easily reproduce as well? Thanks

**Comment by avogra** [comment]
No, the issue is gone in 3.2.1 :-)
