### ISSUE TITLE
Print One At a Time - functionality disappeared?

### ISSUE THREAD

**Issue by Mitrasmit** [Ultimaker/Cura#101]
Is it true that the option to print several models after each other, instead of at the same time, has been removed from the newest version? Or can I just not find it?

**Comment by daid** [comment]
It's one of the features which has not been implemented in the new GUI yet, but is planned for the future release.

Until then, if you need this feature, you'll have to use the previous release:
http://software.ultimaker.com/current/

**Comment by BagelOrb** [comment]
Does that mean it is now implemented in the GUI already, or that it's not going to be done?

**Comment by nallath** [comment]
Its not implemented, which we communicated. It will be implemented in the future.

**Comment by daid** [comment]
(closed because it's already on the internal feature development list for future planned features, also multi material printing will depend on the details of the implementation of this feature, so that's why it will be done for sure)
