### ISSUE TITLE
Support fails to be generated correctly at (0;0;0) coordinates of the model

### ISSUE THREAD

**Issue by HidalgoS2207** [Ultimaker/Cura#10114]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3 PRO

### Reproduction steps

1 - Slice Model with certains supports at coordinates (0;0)

### Actual results

The support its void in Z axis until some layer in coordinates of the model placed in (0;0) 

if i move the model to lets say (5;5) the support is generated OK 

### Expected results

Support consistent and equal in any position of the plate

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![001](https://user-images.githubusercontent.com/22479738/125164753-2cd6f500-e16a-11eb-97aa-550b3004fbef.png)
![002](https://user-images.githubusercontent.com/22479738/125164755-2e082200-e16a-11eb-86c7-59c513d0b5ae.png)

**Comment by fvrmr** [comment]
Hi @HidalgoS2207 could you share your project file (file - save project)?

**Comment by Ghostkeeper** [comment]
From the picture, it looks like the same problem as https://github.com/Ultimaker/Cura/issues/10035.
