### ISSUE TITLE
Crash when saving slices to media when using Bigtree3DPluginSuit

### ISSUE THREAD

**Issue by Hitamku** [Ultimaker/Cura#10148]
### Application Version

4.10

### Platform

Windows  10

### Printer

Biqu B1

### Reproduction steps

Just do the install steps like the previous Cura

### Actual results

The result is the same, crash when saving the slacing result

### Expected results

On Cura 4.9 or earlier versions there is no problem. Only occurs on 4.10

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/6835512/DxDiag.txt)
[cura.log](https://github.com/Ultimaker/Cura/files/6835513/cura.log)

**Comment by Hitamku** [comment]
![crash](https://user-images.githubusercontent.com/13373210/126052912-1f4f0c01-8a14-4fb7-b6b0-1816f25fb8c6.jpg)

**Comment by konskarm** [comment]
Hi @Hitamku. We do not maintain this plugin, so please report this issue in the plugin's repository https://github.com/bigtreetech/Bigtree3DPluginSuit.

**Comment by Hitamku** [comment]
Ok thank you
