### ISSUE TITLE
 mksplugin no aparece

### ISSUE THREAD

**Issue by leofaure** [Ultimaker/Cura#10144]
### Application Version

4.10

### Platform

windows 10 

### Printer

custom

### Reproduction steps

acabo de actualizar, y mksplugin no aparece en administrar de impresoras, esta descargado e instalado pero no aparece donde deveria estar.

### Actual results

no aparece mks wifi

### Expected results

deberia aparecer mks wifi en preferencias/printers

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![prueba 1](https://user-images.githubusercontent.com/4386884/125834986-03c7c0b8-7725-4e80-bdf0-31e6218d0b7f.png)
![prueba 2](https://user-images.githubusercontent.com/4386884/125834998-e217b5a7-d42c-4fd4-b249-1d0408779dc9.png)

**Comment by fvrmr** [comment]
Hi @leofaure this is because the plugin is not supported with 4.10 yet. See https://github.com/Ultimaker/Cura/issues/10070

I will close this issue since it is a duplicate.
