### ISSUE TITLE
run cura on ipad os

### ISSUE THREAD

**Issue by lm339-gj** [Ultimaker/Cura#10159]
### Is your feature request related to a problem?

It's very convenient to design 3D with apple pencil and shapr3d on iPad pro. When 3D printing is needed, other devices are needed to run Cura, which is very troublesome.

### Describe the solution you'd like

port of Cura to iPad OS

### Describe alternatives you've considered

3D design on iPad OS and Cura running on PC。

### Affected users and/or printers

Users of 3D design using iPad OS

**Comment by fvrmr** [comment]
Hi @lm339-gj thank you for your feature request.
Unfortunately there are no plans to develop Cura for iPad OS. Since it would take a lot of time to create a IOS version of Cura. I hope you understand.
