### ISSUE TITLE
line of fillament

### ISSUE THREAD

**Issue by jonilma** [Ultimaker/Cura#10168]
### Application Version

4.10

### Platform

windows 10

### Printer

FLSUN Q5

### Reproduction steps

Slicing cutters

### Actual results

When printer is hot and starts to print, its start printing a line in the hot bed then it starts printing. This is happening since last version update cause I have print things save with other version and it does not print the line. 
![Uploading filament error 2.jpg…]()
![Uploading filament error.jpg…]()

### Expected results

No filament lines

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no
![Uploading filament error 2.jpg…]()

**Comment by Asterchades** [comment]
Sounds like a purge line was added to the printer profile in 4.10. There's definitely some customised start code there, some of which draws an arc - and a lot of which is poorly notated. You should be able to manually alter the start GCode in the Printer Configuration to remove or comment out the line starting with G3 and stop it from happening.

Ultimaker doesn't maintain 3rd party printer profiles. They rely on community submissions, and evidently someone in the community decided to add this. The profile author is listed as Daniel Kreuzhofer.

**Comment by fvrmr** [comment]
Hi @jonilma your images didn't upload correctly. But it looks like this is indeed a purge line like @Asterchades mentioned which seems to be in your printer profile. 
And this is something we don't maintain, so I will close this issue. Hope you understand. 

But the work around @Asterchades suggested should work for you.

**Comment by jonilma** [comment]
Hello:

Just open my settings and I don't see any G3 code, please see picture. What can I do?![Uploading fillament error 2.jpg…]()
<img width="537" alt="machine settings FLSUN" src="https://user-images.githubusercontent.com/87790416/126729770-a2e78547-015a-4ff3-a79c-91204ff2d56c.PNG">

<img width="537" alt="machine settings FLSUN" src="https://user-images.githubusercontent.com/87790416/126729678-c1031a5e-4968-4cb8-ac32-8b61481aa9cf.PNG">
![fillament error 2](https://user-images.githubusercontent.com/87790416/126729688-1bcd9ff8-1247-4a55-b1cd-b09c6865188b.jpg)

**Comment by Asterchades** [comment]
It's down further in the Start G-code section. Cura doesn't visibly add a scroll bar to indicate that there's more text there (though it will crop the end of longer lines if they're present where such a bar should be), but there should be a fair few more lines under the G92 which you can access by selecting anything in there and using the cursor keys, or just hovering over it and using the scroll wheel. The line that actually draws the arc (G3) should be three lines further down, following an M106 and a G1.

**Comment by jonilma** [comment]
@Asterchades thank you very much! I just did it I hope this works, I deleted the line completely. Im new to this so thanks again for your time.
