### ISSUE TITLE
[FR] Add bed adhesion settings to material profiles

### ISSUE THREAD

**Issue by whyme12** [Ultimaker/Cura#10186]
### Is your feature request related to a problem?

Some materials require more bed adhesion than other. A possibility to enable for example a brim on a material basis would ease a material swap.

### Describe the solution you'd like

Make it possible to change all printer settings or at least the bed adhesion settings to the material profile.
All these settings should be able to be set optional and if changed should override the settings of the printer profile.

### Describe alternatives you've considered

Another possibility could be to have different print profiles with different bed adhesion settings set, but then, if jerk or acceleration settings are changed, they have to be changed in every profile.

While writing this, I think that the print settings should be split into 3 parts:
1. dependent by printer (jerk, acceleration, some additional settings like mm steps for layer height to counter ringing)
2. dependent by material (temperature, cooling, adhesion, maybe even limit print speed)
3. dependent by print quality/speed (layer thickness, wall thickness, etc. a majority of the current settings)

### Affected users and/or printers

Probably everyone changing filament types

**Comment by nallath** [comment]
There is a plugin in the marketplace that allows you to do just that! https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MaterialSettingsPlugin
