### ISSUE TITLE
Z coordinate value always reset to zero after saving the project to a .3mf file.

### ISSUE THREAD

**Issue by twinclouds** [Ultimaker/Cura#10184]
### Application Version

4.6.1, 4.9.1, 4.10.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Change the z-coordinate to a non zero (nagative) value.
save the project to a .3mf file.
Close Cura and restart.
Check the new z-coordinate value.

### Actual results

The z-coordinate value always becomes to 0.

### Expected results

The z-coordinate value should be the same before saving.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

That's it.
![Untitled-1](https://user-images.githubusercontent.com/5117656/126912312-4889c6c8-9670-42a6-8138-17aee8a06f4b.jpg)

**Comment by fvrmr** [comment]
Hi @twinclouds thank you for your report. I can't reproduce your issue, tried it with grouped models and support blockers. Does it happen with every model? Could you share your project file?

**Comment by twinclouds** [comment]
Hi, Fanny:I checked a couple of models.  For 3DBench, the z-coordinate change saved fine.  However, the problem happens to most of my models and every version of Cura since 4.6.1. I am not sure it has anything to do with grouped or not.  I have attached link to a 3MF.zip file containing the original bull-s.3MF file and the CE3PRO_Bull-s.3MF file saved after shifting z-axis by -0.5mm.  The results are the same, i.e., the shift of -0.5mm got lost.  Could you take a look?Link: 3mf.zip

| 
| 
|  | 
3mf.zip


 |

 |

 |



Thank you very much!Fuyun 
    On Monday, July 26, 2021, 05:32:14 AM PDT, Fenne ***@***.***> wrote:  
 
 


Hi @twinclouds thank you for your report. I can't reproduce your issue, tried it with grouped models and support blockers. Does it happen with every model? Could you share your project file?

**Comment by fvrmr** [comment]
Hi @twinclouds I can't see your attachment since you replied via email. Could you post it as a zip here on Github?

**Comment by twinclouds** [comment]
Actually, I attached a link and you can see from there.  Here is the link again: (Link: 3mf.zip).  I will try to upload on github but I haven't do that before.Fuyun
    On Tuesday, July 27, 2021, 02:14:38 AM PDT, Fenne ***@***.***> wrote:  
 
 


Hi @twinclouds I can't see your attachment since you replied via email. Could you post it as a zip here on Github?

**Comment by twinclouds** [comment]
Here is the same link.  Hopefully you have no problem to open it.
[https://drive.google.com/file/d/1B75A1Jh3T-1_nlTyRBlLWkvUx0txy3pH/view?usp=sharing](url)
Thank you!

**Comment by twinclouds** [comment]
Here are two files.  The file with "shift" is the one saved after shifting z by 0.5 mm.  The shift was not saved.
[Bull-s.zip](https://github.com/Ultimaker/Cura/files/6887691/Bull-s.zip)
[Bull-s-shift.zip](https://github.com/Ultimaker/Cura/files/6887698/Bull-s-shift.zip)

**Comment by twinclouds** [comment]
Hi,Hope you have received my files this time.  Thank you for your help!Fuyun
    On Tuesday, July 27, 2021, 02:14:38 AM PDT, Fenne ***@***.***> wrote:  
 
 


Hi @twinclouds I can't see your attachment since you replied via email. Could you post it as a zip here on Github?

**Comment by GregValiant** [comment]
Here is how bull-s-shift.3mf it came in for me (Z = -0.5).   Bull-s came in at Z = 0.
![Untitled](https://user-images.githubusercontent.com/64202104/127380168-1afc998f-26d8-4f6f-bfb6-325b4e31e738.png)

**Comment by twinclouds** [comment]
Hi, Thank you for getting back to me.  This is what I got from Cura v4.10.0 and W10.  Which version of Cura and platform (OS) are you using?  

Could you tell me you think what happened?Thanks.Fuyun
    On Wednesday, July 28, 2021, 12:01:20 PM PDT, GregValiant ***@***.***> wrote:  
 
 


Here is how bull-s-shift.3mf it came in for me (Z = -0.5). Bull-s came in at Z = 0.

**Comment by twinclouds** [comment]
Is there anything I did wrong?Fuyun
    On Wednesday, July 28, 2021, 01:47:27 PM PDT, twinclouds ***@***.***> wrote:  
 
  Hi, Thank you for getting back to me.  This is what I got from Cura v4.10.0 and W10.  Which version of Cura and platform (OS) are you using?  

Could you tell me you think what happened?Thanks.Fuyun
    On Wednesday, July 28, 2021, 12:01:20 PM PDT, GregValiant ***@***.***> wrote:  
 
 


Here is how bull-s-shift.3mf it came in for me (Z = -0.5). Bull-s came in at Z = 0.

**Comment by GregValiant** [comment]
Win 10 and Cura 4.10 and an Ender 3 Pro.
There have been some complaints lately about things moving in the Z when a 3mf file is opened.  I think that so far they have been tough to duplicate.  It's like trying to chase down an intermittent automobile electrical problem.  It drives you crazy so you take it in to the repair shop and it refuses to act up for the mechanic.

**Comment by twinclouds** [comment]
No.  It's not only for Cura 4.10.  I have tried 4.6, 4.8 they all have the same problem.  In addition, it has nothing to do with what 3D printer that I am using.  Could you please tell me which version on which platform the saving works?  I will be happy to try it if convenient.  Actually, the x and y coordinates that I saved are both zero but what you had shown are not.  So even your version did something incorrect.  I don't this is an unrepeatable case as you discussed.  Hopefully you guys can figure out a way to determine what this problem is.
Fuyun
    On Thursday, July 29, 2021, 05:33:57 PM PDT, GregValiant ***@***.***> wrote:  
 
 


Win 10 and Cura 4.10 and an Ender 3 Pro.
There have been some complaints lately about things moving in the Z when a 3mf file is opened. I think that so far they have been tough to duplicate. It's like trying to chase down an intermittent automobile electrical problem. It drives you crazy so you take it in to the repair shop and it refuses to act up for the mechanic.

**Comment by fvrmr** [comment]
Hi @twinclouds do you write it down manually? Because it could be a duplicate of https://github.com/Ultimaker/Cura/issues/10100
For me if I use a `,` it doesn't save the value.
Could that be that be the case for you?

**Comment by twinclouds** [comment]
Hi, Fanne:  Not sure what do you mean by "write it down manually".  In any case, I was taking about the coordinate changes.  Not about scaling changes.  Fuyun
    On Friday, July 30, 2021, 06:25:41 AM PDT, Fenne ***@***.***> wrote:  
 
 


Hi @twinclouds do you write it down manually? Because it could be a duplicate of #10100
For me if I use a , it doesn't save the value.
Could that be that be the case for you?

**Comment by twinclouds** [comment]
I tried to use "," instead of ".".  It didn't take "-0,5" as a valid input for "-0.5", so no shift was performed in the first place.

**Comment by fvrmr** [comment]
>  Not sure what do you mean by "write it down manually". 

Typing the coordinates in the input box in the move tool, instead of dragging it with the arrow. 

Did you see that your model was moved before you saved your project?
And does it happen with other models.

**Comment by twinclouds** [comment]
Hi, Fenne:Yes, the coordinates are typed in, not by drawing, and I checked them every time before I save the project.It happen to most of my models.  I did find that the 3Dbench saved correctly.Do you find my model of bull saved correctly in your setting?  If you do please let me know the conditions that I can try to repeat.Thank you!Fuyun
    On Tuesday, August 3, 2021, 02:32:22 AM PDT, Fenne ***@***.***> wrote:  
 
 



Not sure what do you mean by "write it down manually". 


Typing the coordinates in the input box in the move tool, instead of dragging it with the arrow.

Did you see that your model was moved before you saved your project?
And does it happen with other models.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ghostkeeper** [comment]
In the bull-s-shift file, it stored it as moved 0.5mm down. That part is working fine.

The issue at hand here is the "Automatically drop models to the build plate" preference. If enabled, Twinclouds' symptoms reproduce. If not, the model loads in 0.5mm lowered into the build plate.

I'll confirm that this is a bug. Although you could interpret it both ways... It's aligning the bottom of the model to the build plate properly here, but that's clearly not what the user wanted. If the file would have models floating up in the air, it's fair to say that most likely the user wants to drop them down. But if it is lowered underneath the build plate, the user most likely intended it to be lowered in order to cut off the bottom side.

As a workaround, temporarily disable the "Automatically drop models to the build plate" preference when loading in this model.

**Comment by twinclouds** [comment]
Thanks for finding out the root cause of the problem.  I disabled "Automatically drop models to the build plate" and it works fine.  I am satisfied with this solution, even though I hope that a permanent fix as you suggested can be implemented in the future revisions.Fuyun
    On Thursday, August 5, 2021, 07:55:59 AM PDT, Ghostkeeper ***@***.***> wrote:  
 
 


In the bull-s-shift file, it stored it as moved 0.5mm down. That part is working fine.

The issue at hand here is the "Automatically drop models to the build plate" preference. If enabled, Twinclouds' symptoms reproduce. If not, the model loads in 0.5mm lowered into the build plate.

I'll confirm that this is a bug. Although you could interpret it both ways... It's aligning the bottom of the model to the build plate properly here, but that's clearly not what the user wanted. If the file would have models floating up in the air, it's fair to say that most likely the user wants to drop them down. But if it is lowered underneath the build plate, the user most likely intended it to be lowered in order to cut off the bottom side.

As a workaround, temporarily disable the "Automatically drop models to the build plate" preference when loading in this model.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fvrmr** [comment]
I have created a ticket on our backlog for this bug. 
Devs see CURA-8479

**Comment by twinclouds** [comment]
Thank you!
    On Thursday, August 12, 2021, 07:39:16 AM PDT, Fenne ***@***.***> wrote:  
 
 


I have created a ticket on our backlog for this bug.
Devs see CURA-8479

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
