### ISSUE TITLE
Material settings build plate temperature does not update print settings

### ISSUE THREAD

**Issue by whyme12** [Ultimaker/Cura#10185]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Modded Anycubic i3 Mega

### Reproduction steps

Change material from PLA to ABS and compare the buld plate temperature with the temperature in the material profile.

### Actual results

As seen in the attached picture, the buildplate temperature was not changed when selecting a new material.

I have checked the gcode, it is not a visual bug, the parameter is not updating.

### Expected results

All settings of the the material profile should changed when selecting a new material.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Example](https://user-images.githubusercontent.com/3646082/126912160-1ab26b17-a89f-4358-bcd0-d344d412e9b8.PNG)

**Comment by fvrmr** [comment]
Hi @whyme12 I can't reproduce your issue.
![Screenshot (217)](https://user-images.githubusercontent.com/77000924/127003325-c79a8055-ba9f-4a93-ae8e-a4d57e8eb1f0.png)

Could you share your definition file of your printer? It is possible that it is defined there. You can find your definition here: `C:\Program Files\Ultimaker Cura 4.10.0\resources\definitions`

**Comment by whyme12** [comment]
Found the problem, bed temperature was stored inside the quality settings ("...AppData\Roaming\cura\4.10\quality_changes").

But not sure when and why I should have changed it.
