### ISSUE TITLE
Poor seam alignment

### ISSUE THREAD

**Issue by Wasser97** [Ultimaker/Cura#10181]
### Application Version

Arachne

### Platform

Win 10, gtx 1550ti

### Printer

Custom, flying bear ghost 5

### Reproduction steps

Upgrade to version 4.10, then upgrade to arachne. The problem appeared already on version 4.10. Completely deleting profiles, cleaning the registry and reinstalling did not help
![Снимок](https://user-images.githubusercontent.com/70451717/126872360-a6dc36c5-0ab2-40bf-82e4-7aa59fd7d19d.PNG)
[proba100.zip](https://github.com/Ultimaker/Cura/files/6872662/proba100.zip)

### Actual results

The seam is lost in the slicer and when printing

### Expected results

Align the seam in a line

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The files are attached above

**Comment by smartavionics** [comment]
For a Cura variant that will align that seam as you desire, see https://github.com/smartavionics/Cura/releases. To get that benefit, you need to set the z-seam alignment to user specified and the seam corner preference to none. Hope this helps...

![Screenshot_2019-10-22_10-25-30](https://user-images.githubusercontent.com/585618/126877407-66fe4a98-bac3-4208-9817-1551d309d6c5.png)

**Comment by fvrmr** [comment]
Hi @Wasser97 We have a ticket on our backlog related to the seam in Arachne. 
Devs see CURA-8053

For more info about how Cura is place the z seam can you read here: https://github.com/Ultimaker/Cura/issues/8010#issuecomment-654193325

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?
