### ISSUE TITLE
Bug: Multiple objects slice

### ISSUE THREAD

**Issue by andmuniz** [Ultimaker/Cura#10201]
### Application Version

Cura Arachne_engine_beta

### Platform

Windows 10

### Printer

Anycubic mega S

### Reproduction steps

When slicing process **many objects** the process stop. 

### Actual results

Slicing process stop. 

### Expected results

Slicing many objects.

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6889227/cura.log)
![stopprocess](https://user-images.githubusercontent.com/21102504/127240216-8149089c-fe68-4201-87f1-8e1cfeb902d4.png)

**Comment by fvrmr** [comment]
Hi @andmuniz can you also share your project file? I can't reproduce this issue myself.

**Comment by andmuniz** [comment]
> 
> 
> Hi @andmuniz can you also share your project file? I can't reproduce this issue myself.

[AI3M_teste.zip](https://github.com/Ultimaker/Cura/files/6913705/AI3M_teste.zip)

**Comment by fvrmr** [comment]
Hi @andmuniz thank you for your project file. I can reproduce your issue and it seems like this is caused by some changed settings because if I change to the default profile, I can slice your project. 
![Screenshot (220)](https://user-images.githubusercontent.com/77000924/128019895-e9ad90a5-6d92-4e8c-ad75-d58ce17642b9.png)

I will bring this up with the team. Keep you posted.

**Comment by andmuniz** [comment]
> I will bring this up with the team. Keep you posted.

Okay, thank you... and i appreciate that I can contribute in any way.

**Comment by Ghostkeeper** [comment]
Specifically, it seems that the infill density of 15% instead of 25% seems to be causing this error. Looks like an edge case.

**Comment by konskarm** [comment]
Hi @andmuniz. My apologies for the late response. This issue seems to be happening somewhere in the InsetOrderOptimizer. We already have an internal ticket for that. Devs, see CURA-8106.

**Comment by Piezoid** [comment]
Hopefully this bug should be solved with [PR #1487 (CuraEngine)](https://github.com/Ultimaker/CuraEngine/pull/1487)

**Comment by Ghostkeeper** [comment]
Can confirm! This bug is indeed fixed now. Thanks for your help, Piezoid!

**Comment by andmuniz** [comment]
> 
> 
> Hopefully this bug should be solved with [PR #1487 (CuraEngine)](https://github.com/Ultimaker/CuraEngine/pull/1487)

Hello, But I didn't undesrstand how apply this solution in my software.

**Comment by fvrmr** [comment]
You can run Arachne from source, read here how: https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source
Other than that you need to wait till we release a other beta of Arachne.
