### ISSUE TITLE
Crashes when browsing a folder that contains subfolder with 3D files

### ISSUE THREAD

**Issue by mbmcnicol** [Ultimaker/Cura#10207]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Open Cura
2. Browse to a folder either directly contains OR has a SUBFOLDER that directly contains a 3D object file (tested with both OBJ and STL files).
3. Cura will crash IF the view is set to "Large Icons" (or any other size, as long as it will attempt to show a preview on the icon).  If in "List" or "Detail" view the issue does not happen.

### Actual results

Cura crashes without an error message

### Expected results

Cura displays files and continues to work properly.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

This appears to be an issue relating directly to rendering an icon that will display a preview.  This goes for the icon of the file itself, or a subfolder containing the file (because Windows will render subfolders to show a preview of a couple of files that are inside that folder).  In "List" and "Detail" views however, these icons are only rendered using the associated program's designated icon, and Cura has no issue whatsoever then.

This problem *seemed* to have started after I installed Chitubox Basic for my resin printer (version 1.9.0).  Reinstalling Cura over top of my current installation did not fix the issue.  Reassigning Cura as the default app for STL and OBJ files did not correct the issue either.  Uninstalling Chitubox, however, DID fix the issue, so it seems that Chitubox instigates the problem in Cura.  I do not know whose software has the faulty code in it, but reinstalling Chitubox reinstates the crash, so it's likely something that their software is doing that Cura doesn't like.

I have attached a fresh log file, though it doesn't seem to log anything after the program finishes loading, so I don't know how useful it'll actually be.  :/

[cura.log](https://github.com/Ultimaker/Cura/files/6903664/cura.log)

**Comment by fvrmr** [comment]
Hi @mbmcnicol this is indeed a problem with Chitubox. You can see here the duplicate: https://github.com/Ultimaker/Cura/issues/9668
Here you can find a workaround: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file

I will close this issue, since it is a duplicate.
