### ISSUE TITLE
The possability to place the menu on a second screen.

### ISSUE THREAD

**Issue by fnelen** [Ultimaker/Cura#10212]
### Is your feature request related to a problem?

it's not a problem but it shoud be an nice feature for me.

### Describe the solution you'd like

Just the menu on the second screen.

### Describe alternatives you've considered

the alternative is what it is now.

### Affected users and/or printers

no

**Comment by fieldOfView** [comment]
The sidebargui plugin available in the Marketplace has this functionality.
