### ISSUE TITLE
Crash when saving project (SOLVED!!, .obj files too large, not enough computer memory)

### ISSUE THREAD

**Issue by christianpatrickgalles** [Ultimaker/Cura#10229]
### Application Version

4.10

### Platform

windows 10

### Printer

creality mini 

### Reproduction steps

these are my steps:
1 Save project as 
2 select any folder
3 loading wheel 
4 black screen
5 cura ends itselfi

I have allowed windows defender to make exemptions to this app
I have saved it as a new profile
I have imported just the objects
I have grouped and ungrouped the objects
I have updated to cura 4.10

### Actual results

program crashes, file size is 0

### Expected results

the file should save completely intact

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6928114/cura.log)

https://drive.google.com/file/d/1ql18EC9TlQoe5biPeOd4ucZQF4qMf7Ut/view?usp=sharing

**Comment by fvrmr** [comment]
Hi @christianpatrickgalles I noticed you've changed your title to solved, so I will close this issue.
