### ISSUE TITLE
Fix the sequence when the Utlimaker S5 when you get: "ER38 - Active leveling correction failed"

### ISSUE THREAD

**Issue by TRLBY** [Ultimaker/Cura#10224]
### Is your feature request related to a problem?

This is the dumbest of the dumb errors: ER38 - Active leveling correction failed since 99.9% of the time it's due to a little residue on the tip of the Nozzles.

### Describe the solution you'd like

Instead of shutting down the print completely how about give it a "Pause" instead. This way you can wipe the nozzle's nose and carry on.

But NO the programmers would prefer they waste 10 more minutes of your time shutting the print down instead.

You need a pause option... then you could try again before the Core need to cool down, then abort the print. It doesn't even hold the job, it just goes cold.

### Describe alternatives you've considered

Selling my S5 Bundle and looking for a company that understands what Business users expect from there equipment.

I thought Ultimaker had made a commitment to business users by introducing the S5 Bundle, but it appears their Software development is stuck in the hobbyist market. I don't understand your new Business Management system, that let's you manage all your printers when your printers are not even close to being refined enough. If I was using it and got these kinds of stupid errors due to poor programming, I'd be furious... especially given the cost at $600 yearly! 

### Affected users and/or printers

ME and my S5 Bundle

### Additional information & file uploads

Ultimaker needs to use a proprietary version of CURA.  I see too many dropped balls and hate the fact that I have to deal with 2 separate companies.

**Comment by fvrmr** [comment]
Hi @TRLBY thank you for reaching out. On Github we keep track of bugs and feature requests related to Cura and it seems like your issue is not related to Cura. The best way to report this is by contacting [our support](https://support.ultimaker.com/hc/en-us/requests/new), they will help you with finding a proper solution. 
I will close this issue, since this is not something we can help you with.
