### ISSUE TITLE
Print temperature +10°C after gcode export

### ISSUE THREAD

**Issue by mvsoldier** [Ultimaker/Cura#10228]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Anycubic Mega X

### Reproduction steps

Set the Print Temperature to 200°C 
and exported it as a gcode

### Actual results

the Temperature in the Exported gcode is set to 210 °C

### Expected results

the print Temperature should be 200 °C

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

I Tried a different Anycubic printer and the same export bug happend
[185.zip](https://github.com/Ultimaker/Cura/files/6925964/185.zip)

The attached file was exported with 185 °C and when you look at the gcode it says 195°C

found out that it will only print like this for the first layer

**Comment by fieldOfView** [comment]
Without a project file, we cannot see where Cura gets it temperature from in your case, so we cannot help you.

**Comment by Ghostkeeper** [comment]
Most likely the difference between the normal printing temperature and the initial layer printing temperature.
