### ISSUE TITLE
Cura 4.10 support pattern no changing. Keep sticking to zigzag

### ISSUE THREAD

**Issue by SkylinerXwiz** [Ultimaker/Cura#10237]
### Application Version

4.10

### Platform

Windows 10

### Printer

Prusa i3

### Reproduction steps

Change the support pattern from zigzag to line, or any other type. (I tried with line, grid, Gyroid)
Click on slice.
then preview

### Actual results

preview keep seeing zigzag pattern

### Expected results

should be line support or any other type of support pattern that i select
[Desktop.zip](https://github.com/Ultimaker/Cura/files/6942805/Desktop.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Nil

**Comment by fvrmr** [comment]
Hi @SkylinerXwiz on your screenshot I can't really see what support pattern is used in the support it self. 
The project file you shared had support pattern triangles and I could see that was used. 
![Screenshot (225)](https://user-images.githubusercontent.com/77000924/128473455-bbf5406c-5efa-4b9b-b010-abd06b51bf04.png)
The reason why you can't see it that well is probably of the support density and the gradual support infill steps. 

If I change it to lines and set gradual support infill steps to 0, this is what I get: 
![Screenshot (226)](https://user-images.githubusercontent.com/77000924/128474587-be656aaa-6fa4-4bb3-9c3d-1b2fb5f59cd0.png)
The lines may look like zig zag because of the connect support lines.

**Comment by cliffordvandyk** [comment]
![image](https://user-images.githubusercontent.com/17923003/129256937-42da91dd-03d2-4e8e-8835-c7c9438db00b.png)
I am seeing the same issue - Support structures seem to remain at the zig-zag default, and default 20% density, and the support interface flag appears to be ignored.

**Comment by fvrmr** [comment]
@cliffordvandyk can you share your project file (file - save project)?

**Comment by cliffordvandyk** [comment]
Hi fvrmr

Changing the support pattern, support density and "Enable support interface" seems to have no influence over the support pattern/density/interface - it remains per my screen grab above.
[CCR10SPRO_display_holder_scaled.zip](https://github.com/Ultimaker/Cura/files/6982252/CCR10SPRO_display_holder_scaled.zip)
 To confirm, using CURA 4.10 on Windows 10.

**Comment by fvrmr** [comment]
Thank you, it seems like you want to change the `support interface pattern`.  To see these settings you can select all in the setting visibility. And then you will also some other settings related to the support interface.

**Comment by cliffordvandyk** [comment]
Thanks for your reply. I indeed tried to activate support interface as the
default support grid was not dense enough, and Cura did not seem to respond
to me increasing the density.

I activated the support interface in settings. After selecting it and
ticking the checkbox, I again saw no change in slicer output. I also tried
changing the support pattern (and support density mentioned above), but
none of my changes showed up in the sliced view.

Kind regards,
Clifford

**Comment by cliffordvandyk** [comment]
Further follow-up:
After "fiddling" a bit with enabling extra settings on the menu, Cura does now seem to be responding to support pattern, density and request for a support interface. I am not sure what caused the change in behaviour, but it is now working.

**Comment by Ghostkeeper** [comment]
@SkylinerXwiz probably wants to disable the Connect Support Lines setting. Using that in combination with the lines pattern looks a lot like zigzag. But other than that, it seems to change fine in layer view, starting from their project file.
