### ISSUE TITLE
Filament Cost

### ISSUE THREAD

**Issue by nissenhj** [Ultimaker/Cura#10235]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Sovol-SV01

### Reproduction steps

When you enter a price under "Filament Cost", the price changes for all filaments that are in that group!
This can not be r
![Skärmbild 2021-08-05 074744](https://user-images.githubusercontent.com/45319576/128297864-8c42e416-9271-4385-9830-cfbbc780d69b.jpg)
ight as it does not correspond to reality. 

### Actual results

The price changes for all filaments in the group
![Skärmbild 2021-08-05 074745](https://user-images.githubusercontent.com/45319576/128298064-b4e899f1-d2d5-42ed-b39e-108361b7385c.jpg)

### Expected results

The price should only be changed for the filament I am in and change

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

has no more files 
![Skärmbild 2021-08-05 074745](https://user-images.githubusercontent.com/45319576/128298367-5284aa86-56ad-4d21-98a9-9d32d559f695.jpg)
![Skärmbild 2021-08-05 074744](https://user-images.githubusercontent.com/45319576/128298422-ed88021a-95ee-4021-aa77-c8e563af13c5.jpg)

**Comment by fvrmr** [comment]
Hi @nissenhj you can unlink your materials if you duplicate a material from another material. 
![Screenshot (229)](https://user-images.githubusercontent.com/77000924/128514439-a7680e24-cfb4-409b-9a7c-52756b1c1fdf.png)

Let me know if that works for you!

**Comment by nissenhj** [comment]
> Hi @nissenhj you can unlink your materials if you duplicate a material from another material.
> ![Screenshot (229)](https://user-images.githubusercontent.com/77000924/128514439-a7680e24-cfb4-409b-9a7c-52756b1c1fdf.png)
> 
> Let me know if that works for you!
Hi

I have not such a button?

![Skärmbild 2021-08-06 211642](https://user-images.githubusercontent.com/45319576/128560928-4e6d665e-fe5c-4414-a8ce-31b4560a76c8.jpg)

**Comment by fvrmr** [comment]
Could you try to duplicate one and see if the button is there after you clicked duplicate?

**Comment by nissenhj** [comment]
Hi
I have tried to duplicate one but no button appeared 
I am running Cura 4.10.0

**Comment by fvrmr** [comment]
Can you share your material files with me? You can find them here: `C:\Users\<your username>\AppData\Roaming\cura\4.10\materials`

**Comment by nissenhj** [comment]
Yes I will  share this files with you. But I don´t know how to do in here?

**Comment by nissenhj** [comment]
[Cura_4_10_0_materials.zip](https://github.com/Ultimaker/Cura/files/6988746/Cura_4_10_0_materials.zip)
So! I made a zip file of it

**Comment by Ghostkeeper** [comment]
The materials in question all have the same GUID so they are indeed linked and it is correct that they share their cost. They are meant to denote different profiles for the same spool of material.

However it is then incorrect that it doesn't display the button to unlink them.

It's not displaying the button due to this error, which shows up in the log:

    MaterialsView.qml:34:5: Unable to assign QStringList to QString

I've fixed that error now. The unlink button should properly show up again.

**Comment by nissenhj** [comment]
Thanks for any help!
