### ISSUE TITLE
Cura won't open (Fatal error)

### ISSUE THREAD

**Issue by MPGundling** [Ultimaker/Cura#10248]
### Application Version

4.9.1

### Platform

Windows-10-10.0.19041

### Printer

Creality Ender 3 pro

### Reproduction steps

Tried to open an .stl and cura popped up with this error and said I needed to backup and restore

### Actual results

[Logs_20210807.txt](https://github.com/Ultimaker/Cura/files/6949015/Logs_20210807.txt)
[traceback_20210807.txt](https://github.com/Ultimaker/Cura/files/6949017/traceback_20210807.txt)

### Expected results

STL opens in Cura

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[traceback_20210807.txt](https://github.com/Ultimaker/Cura/files/6949018/traceback_20210807.txt)
[Logs_20210807.txt](https://github.com/Ultimaker/Cura/files/6949019/Logs_20210807.txt)

**Comment by nallath** [comment]
Please update Cura. This issue has been fixed in 4.10
