### ISSUE TITLE
Add base $ amount to pricing.

### ISSUE THREAD

**Issue by GeekStreetSolutions** [Ultimaker/Cura#10283]
### Is your feature request related to a problem?

In my pricing method for pricing my prints, I have a base dollar amount I charge and I charge what the calculator shows on top of that base price. This is mostly for those times when I have a very small order that wont cost much.

### Describe the solution you'd like

I would like to have the ability to enter a number on the price settings for a material and have that number added onto the price calculated by Cura. Say I enter base amount of $10. Cura calculates a print will cost $25. It will then add $10 onto $25 for a total of $35.

An additional feature that would be nice is if I can have the option to charge this base price per individual STL file on the bed. So lets say I use the previous $25 print, but I have two copies of the model on the bed and slice it using the print "all at once" feature. Cura would know to charge the $25 per part plus another $10 per part for a total of $70 even though they are printed all at once. This should be able be to toggled on/off though.

Hopefully that was not too confusing to understand.

### Describe alternatives you've considered

Currently I use the pricing calculator feature, but then manually add on the base price. It would be nice to have Cura do this for me and update the price accordingly.

### Affected users and/or printers

This will mostly benefit users who use the price calculator for pricing print services.

**Comment by fvrmr** [comment]
Hi @GeekStreetSolutions thank you for your feature request. 
I think this issue is related to this one: https://github.com/Ultimaker/Cura/issues/9261 which started about electricity cost, but there is also discussed about tracking more costs. Feel free to continue the thread there. 

I will close this issue, since it is a duplicate.
