### ISSUE TITLE
Layer hight setting is ignored

### ISSUE THREAD

**Issue by adamtoczek** [Ultimaker/Cura#10296]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3 

### Reproduction steps

1. Select Dynamic Quality - 0.16mm
2. Change layer hight to 0.2mm
3. Slice
4. Save to disk
5. Open G Code and see that each layer is 0.16

### Actual results

Layer hight is ignored. Z is incremented by 0.16 with each layer

### Expected results

Generated G Code should have layer hight corresponding to the setting

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Can't attach project file .3mf file here :(
![2021-08-17 17_02_00-CE3PRO_b1b4ea83-01c0-43bf-8310-f309c1611c6a - Ultimaker Cura](https://user-images.githubusercontent.com/17167889/129750728-62116a62-0053-46fd-b909-100b4bac754c.png)
![2021-08-17 17_06_36-C__Users_Adam_Downloads_CE3PRO_b1b4ea83-01c0-43bf-8310-f309c1611c6a gcode - Note](https://user-images.githubusercontent.com/17167889/129751548-e5876ccc-6730-43d1-ae89-47103e19632e.png)

**Comment by nallath** [comment]
Dynamic quality enables the "Use Adaptive layers" strategy. That will vary the layer height depending on the features in your model. 

Check the description of that setting for more information.
