### ISSUE TITLE
Arachne beta: Support layers missing

### ISSUE THREAD

**Issue by mcer12** [Ultimaker/Cura#10293]
### Application Version

arachne beta

### Platform

Windows 10

### Printer

Creality CR10

### Reproduction steps

There is a similar issue regarding gaps in supports (but it focuses on tree support):
https://github.com/Ultimaker/Cura/issues/8218
To me this happends with normal zig-zag support. It seemingly happends randomly. Moving the model and re-slicing doesn't help.

### Actual results

Gaps in supports in arachne

### Expected results

Cura 4.9.1 doesn't have this issue using the same profile.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

Arachne:
![arachne](https://user-images.githubusercontent.com/33605121/129589951-92c62396-5fc4-469b-8eb6-be7c2a94f068.png)

4.9.1:
![4 9 1](https://user-images.githubusercontent.com/33605121/129589964-38aaa149-b5eb-45ca-94ad-e2bbda610d0c.png)

Project file (saved in arachne):
[rails.zip](https://github.com/Ultimaker/Cura/files/6993617/rails.zip)

**Comment by fvrmr** [comment]
Hi @mcer12 thank you. I can reproduce your issue. 
I will bring this up with the team. Keep you posted!

**Comment by fvrmr** [comment]
I have discussed this with the team. And I have created a ticket on our backlog. 
Devs see CURA-8492

**Comment by mcer12** [comment]
@fvrmr thank you, I only use arachne beta unless I need supports. It's much better than the normal version.

**Comment by nallath** [comment]
This has been fixed for the 5.0 release!
