### ISSUE TITLE
Cura 4.10.0 Crashes when opening file prompt

### ISSUE THREAD

**Issue by Meagleson88** [Ultimaker/Cura#10295]
### Application Version

4.10.0

### Platform

Windows 10 64

### Printer

Creality CR-10S Pro V2

### Reproduction steps

Click Open File. Crashes.

### Actual results

Cura locks up and crashes immediately.

### Expected results

Should open prompt window and let me select file.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![CuraCrash](https://user-images.githubusercontent.com/89082077/129727287-96ab083e-1e80-45fd-83f9-f5b0f17aecef.jpg)

**Comment by Meagleson88** [comment]
Well I did some more reading and found out that Chitubox was infecting it. Uninstalled Chitubox and now it works as should. But now I don't have a software for my Elegoo....

**Comment by nallath** [comment]
You don't have to uninstall it. Check: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
