### ISSUE TITLE
Create Profile From Current Settings

### ISSUE THREAD

**Issue by sleemanj** [Ultimaker/Cura#1030]
Cura 2.3, accept my apologies if this is already fixed, I couldn't see anything like it in the tracker.

When you adjust some settings, at least of a custom profile on-the-fly, and then select "Create profile from current settings..." option from the Profile drop down, it appears that only the currently uncommitted (not yet saved to profile) changed settings of the current profile are added to the new profile, instead of all the settings from the current profile plus the uncommitted ones.

The result is that various settings in the profile get reset to defaults, and thus the profile you created is not the same as the settings you were looking at.

This image shows a custom profile, there are no uncommitted changes, notice the Wall Thickness is set to 1.2mm in this profile
![1](https://cloud.githubusercontent.com/assets/207209/19149658/862def00-8c1f-11e6-939f-dab58a279499.jpg)

I make a change to the layer height (we see it is uncommitted because of the circular arrow)
![2](https://cloud.githubusercontent.com/assets/207209/19149679/a02a3a9e-8c1f-11e6-9236-31f0308ce42b.jpg)

I select Create profile from current settings...
![3](https://cloud.githubusercontent.com/assets/207209/19149704/c34c5fca-8c1f-11e6-9e9f-6674843825f4.jpg)

(off-camera I call the new profile Normal Quality 5 and click the button)

The profile which gets created is different to the settings it was created from, notice the Wall Thickness has reverted to a default 0.8mm, instead of the 1.2mm it should have been, the layer height change however has been recorded.

![4](https://cloud.githubusercontent.com/assets/207209/19149735/e092dc4e-8c1f-11e6-9fb8-9b66ec00cdfd.jpg)

**Comment by fieldOfView** [comment]
Thanks for the report. I will log an issue in our internal tracker, and I will try to get it fixed before the 2.3 release.

The issue seems to be that when creating a new profile, Cura disregards the currently selected custom profile ("quality_changes container" in our code) and instead looks at the protected profile ("quality container" in our code) it was based on.

**Comment by nickthetait** [comment]
Really great and detailed bug report :+1:

**Comment by fieldOfView** [comment]
And it's been fixed, reviewed and tested. How's that for a turnaround? The fix will be part of the Cura 2.3 final release. 

Again, thanks for reporting.
