### ISSUE TITLE
cura slicer bug reports

### ISSUE THREAD

**Issue by ben3dprints** [Ultimaker/Cura#10313]
### Application Version

4.10.0

### Platform

windows 10

### Printer

ender 5 pro

### Reproduction steps

step 1. enable ironing and use a file where you iron multiple layers 
step 2 print 

### Actual results

It will iron the layers then switching to normal printing it will kinda skip a layer causing the rest of the print to fail on that one point. 

### Expected results

The print should iron the layers successfully and print the rest of the layers properly. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I've only had this problem on the newest update of cura also if the print doesn't turn to goop after that layer it leaves a big scar around the print 

Also, what you see in this image is (top) a tank track where it ironed the wheels inside and all that mess is the layers after it ironed them.
![IMG_6680](https://user-images.githubusercontent.com/89233950/130171141-5d8219f2-d47f-459e-9c14-f7f701145af3.JPG)

**Comment by fvrmr** [comment]
Hi @ben3dprints can you share your project file (file - save project)?
