### ISSUE TITLE
Add support layer height feature like infill layer height

### ISSUE THREAD

**Issue by raimondi1337** [Ultimaker/Cura#10317]
### Is your feature request related to a problem?

Some prints have a lot of support that needs to exist but doesn't need to be high quality, this takes a lot of time to print

### Describe the solution you'd like

There is already a separate 'infill layer height' option to allow printing of thicker infill layers, it should exist for support too.

Also, as these settings are required to be multiples of print layer height, they should be the multiplier not the layer height (ie '2' rather than '0.24mm')

### Describe alternatives you've considered

There are other ways to reduce support printing time but as this is very close the the infill layer feature it seems like a valid request

### Affected users and/or printers

All

### Additional information & file uploads

This has been thought of at least once before
https://community.ultimaker.com/topic/27971-support-layer-height/

**Comment by johnkray** [comment]
I believe "Support infill layer thickness" is what you are talking about and this setting is already present.
