### ISSUE TITLE
Monotonic ordering for Arachne

### ISSUE THREAD

**Issue by unkn0wndude** [Ultimaker/Cura#10322]
### Is your feature request related to a problem?

Top and bottoms just does not look good without monotonic ordering.

### Describe the solution you'd like

Please add monotonic ordering for tops and bottoms as it was added in Ultimaker Cura 4.11.0-BETA. 

### Describe alternatives you've considered

I don't think there are any alternatives.

### Affected users and/or printers

All users/all printers.

### Additional information & file uploads

Thank you so much :)

**Comment by jellespijker** [comment]
The master branch with the monotonic ordering has already been merged to the libArachne branch. In other words the next Arachne release will have monotonic ordering and more ;-)

Will close this issue as it already implemented, just be patient a little while longer.
