### ISSUE TITLE
file explorer cash

### ISSUE THREAD

**Issue by JaysonEBishop** [Ultimaker/Cura#10324]
### Application Version

4.10.0

### Platform

windows 10

### Printer

creality CR10s

### Reproduction steps

click on open folder
click on sub folder in file explorer
tried to move file explorer, crash, or tried another subfolder , crash

### Actual results

Cura closes (crashes)

### Expected results

open a file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7028038/cura.log)
no project was loaded

**Comment by fieldOfView** [comment]
If you have Chitubox installed on the same computer, see https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
