### ISSUE TITLE
Cura unable to boot in new version

### ISSUE THREAD

**Issue by kerk93** [Ultimaker/Cura#10337]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality Ender 5 Plus

### Reproduction steps

The software process is generate and will auto end after a few second. Will found is a faulting module name ntdll.dll. Exception code 0xC0000005

### Actual results

Faulting application name: Cura.exe, version: 4.10.0.0, time stamp: 0x60ad43a2
Faulting module name: ntdll.dll, version: 10.0.19041.1110, time stamp: 0xe7a22463
Exception code: 0xc0000005
Fault offset: 0x000000000002d30e
Faulting process id: 0x2090
Faulting application start time: 0x01d79661723e4398
Faulting application path: C:\Program Files\Ultimaker Cura 4.10.0\Cura.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: ba5957a6-77f5-40fc-9763-008d17f30a5d
Faulting package full name: 
Faulting package-relative application ID: 

### Expected results

Cura can load correctly.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/89528488/130801511-1b533c0e-acd0-4047-a451-3bfe45dca6b8.png)

**Comment by Ghostkeeper** [comment]
Could be the same issue as https://github.com/Ultimaker/Cura/issues/9489. Do you happen to have an application called "BetterHash" installed?
