### ISSUE TITLE
Slicing does not complete if tis model is upside down

### ISSUE THREAD

**Issue by YoshinaKuraka** [Ultimaker/Cura#10334]
### Application Version

4.10

### Platform

Windows 10

### Printer

Crealit Ender3

### Reproduction steps

[LensCapSlim.zip](https://github.com/Ultimaker/Cura/files/7042116/LensCapSlim.zip)

if this model is flipped upside down
[OpenTaclightSLimParts.zip](https://github.com/Ultimaker/Cura/files/7042130/OpenTaclightSLimParts.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7042134/cura.log)

### Actual results

slicing does not seem to finish:
![grafik](https://user-images.githubusercontent.com/89487491/130690085-8687aac9-18a2-4f83-8cf3-096e2d33b992.png)

### Expected results

slicing finishes

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

If the model is turned even slightly, the slicer finishes as expected:

![grafik](https://user-images.githubusercontent.com/89487491/130690235-e0320e47-6441-4739-b652-154a4afd89dc.png)

**Comment by fvrmr** [comment]
Hi @YoshinaKuraka thank you for your bug report.
I can reproduce your issue, I will bring this up with the team. Keep you posted!
