### ISSUE TITLE
Extra material added to edge of supports in random spots

### ISSUE THREAD

**Issue by Gamepimp** [Ultimaker/Cura#10341]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality CR10S Pro

### Reproduction steps

When printing a box with some holes/openings on the back, Cura randomly adds extra material to the edges of the supports within those cavities which then partially fuses them to the box itself. In the settings I selected zig zag supports with a 4mm line distance. I have also set a X/Y distance of 1.5mm so that the supports won't touch the edges of the openings in order to make them easier to remove. I'm using a 0.6mm nozzle and set the supports to print with a 0.4mm line width. I used support blockers on the round holes as supports aren't necessary in those. However, Cura did actually fill one of the holes up with material for some reason. When previewing the print, the supports appear to be exactly as desired. The actual print is very different though.

### Actual results

Extra material is printed on the edge of supports in random spots causing them to fuse with the actual print even though a 1.5mm X/Y distance is set. This makes them harder to remove. One hole that had supports blocked filled with material.

![Box](https://user-images.githubusercontent.com/80081591/130878404-bb5e1ac5-13c7-4ca7-b838-f5d6f03b18ab.jpg)

### Expected results

Supports should have printed in all the openings that were not blocked and a 1.5mm gap should have been left between the edge of the support and the opening as per the print preview

![Box (Cura)](https://user-images.githubusercontent.com/80081591/130878864-02e08bae-facd-48a6-9553-b13fc3ce5be1.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by Gamepimp** [comment]
Hi @fvrmr. I tried disabling the limited support retraction option and printing the rear portion of the box again (it's a slightly different box than the one I originally posted a picture of, but the openings in the rear are the same). I still ended up with some extra material inside one of the holes that had been blocked and on the edge of one of the supports. I've attached a photo and the project so that you can take a look. Please let me know if there is any other setting that might be contributing to this. Thanks!

![InkedIMG_3451 - Copy_LI](https://user-images.githubusercontent.com/80081591/131198978-684473c6-9f50-4b50-a2e9-c329735ce1a1.jpg)

[Box Project.zip](https://github.com/Ultimaker/Cura/files/7069815/Box.Project.zip)

**Comment by fvrmr** [comment]
Thank you for your project file. You need to change the `retraction minimum travel` to 1.5mm instead of 10mm. Because it was set to 10 mm it didn't have an effect on the small holes. 
I will close this issue, since this will fix your problem. But please let me know if you have more questions.
