### ISSUE TITLE
Always crashing

### ISSUE THREAD

**Issue by ST5311** [Ultimaker/Cura#10346]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3 pro

### Reproduction steps

1. start cura
2. press "open" (to open an STL file)

### Actual results

Cura will crash

### Expected results

you should be able to open any STL file you have either downloaded or created

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i cannot upload a file i am having an issue with if the program cant even load the folder

**Comment by nallath** [comment]
The solution to this (and more inf) can be found here: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
