### ISSUE TITLE
Stuck halfway during the slicing process, CURA using all the RAM memory

### ISSUE THREAD

**Issue by sbk1198** [Ultimaker/Cura#10367]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Sometimes when I slice a bigger more complex model, CURA gets stuck halfway during the slicing process. Looking at the PC performance, it's using almost 100% of the RAM memory (32 gb) and nothing happens. I've waited over half an hour to see if it would solve, but still doesn't. Normally when this model works, it takes only about a minute to solve.

### Actual results

See problem description above

### Expected results

See problem description above

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_COY12_RevA_modified.zip](https://github.com/Ultimaker/Cura/files/7077084/UMS5_COY12_RevA_modified.zip)

**Comment by fvrmr** [comment]
Hi @sbk1198 thank you for your report.
I couldn't slice in 4.10, but in 4.11 beta I could slice it. You can download the beta here: https://github.com/Ultimaker/Cura/releases/tag/4.11-beta

Let me know if that works for you!
