### ISSUE TITLE
Missed Creality CR-200B profiles

### ISSUE THREAD

**Issue by mcecchi** [Ultimaker/Cura#10368]
### Is your feature request related to a problem?

Cannot found Creality CR-200B in Cura.

### Describe the solution you'd like

Support for Creality CR-200B fully enclosed 3d printer in future Cura release.

### Describe alternatives you've considered

Creality Slicer, a Cura derivative. Not updated, bugged and clpsed source.

### Affected users and/or printers

All owners of CR-200B that want to use Ultimaker Cura in place of rarely updated Creality Slicer.

**Comment by fvrmr** [comment]
Hi @mcecchi thank you for your request. 
We don't maintain these profiles and are depended on our community to add these to Cura.
You could also add a custom printer in Cura with the settings of your printer. 
I will close this issue since this is something we won't do. I hope you understand.
