### ISSUE TITLE
Strange preview issues with knurled container

### ISSUE THREAD

**Issue by achampion** [Ultimaker/Cura#10379]
### Application Version

4.10.0

### Platform

Mac Big Sure

### Printer

Snapmaker 2

### Reproduction steps

1. Load a model, e.g. simple calibration cube does the same from the Calibration plugin.
2. Slice with default settings
3. Preview model

### Actual results

This is the Preview image: 
![image](https://user-images.githubusercontent.com/4431181/131782129-c1f08f6e-b25f-4e6a-b085-3f8d90f6a655.png)

### Expected results

A Preview without all the artifacts.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional info.

**Comment by achampion** [comment]
A reboot seems to have fixed the issue, please ignore.

**Comment by Ghostkeeper** [comment]
We've seen this before. The current going theory is that with Cura using a geometry shader, we're touching something that not a lot of applications do, and there seem to be bugs in some graphics drivers there as a result.
Looks cool though.
