### ISSUE TITLE
Profile Ultimaker 2 on cura is missing material customisation

### ISSUE THREAD

**Issue by leo33700** [Ultimaker/Cura#10380]
### Application Version

4.10

### Platform

Windows 10

### Printer

Ultimaker 2

### Reproduction steps

There is no material and there is no possibility to modify or create any material with the preset ultimaker 2 profile.
![um2](https://user-images.githubusercontent.com/89973469/131824428-6887e892-58ae-4001-8336-fa9206e3d05b.jpg)

And when I switch to other preset profile like ultimaker original it is possible
![umoriginal](https://user-images.githubusercontent.com/89973469/131824467-b881c3e9-5b61-43c7-8316-db091de5c538.jpg)

### Actual results

Nothing happened

### Expected results

There should be materials

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none
![um2](https://user-images.githubusercontent.com/89973469/131825169-d5f8d6d3-fc51-41b5-b010-c790d61fbe24.jpg)
![umoriginal](https://user-images.githubusercontent.com/89973469/131825175-19eab3b2-6be9-4efa-bd53-fc491d6c3448.jpg)

**Comment by nallath** [comment]
That is by design; Materials are handled on the printer by the Ultimaker 2. 

We thought back then that that was a better way of doing it, but we realized that we were wrong, so future machines did have a combination of both.

**Comment by leo33700** [comment]
> 
> 
> That is by design; Materials are handled on the printer by the Ultimaker 2.
> 
> We thought back then that that was a better way of doing it, but we realized that we were wrong, so future machines did have a combination of both.

There was a time when i had this function on cura (i don't remember the version). And the ultimaker original is older than the um2 and it has the function on cura. It's just i like to see an approximation of the cost for an impression...

**Comment by nallath** [comment]
> There was a time when i had this function on cura (i don't remember the version). 

It didn't. It could be that you set the g-code flavor to something different. The UM2 not having material profiles is because of the specific flavor of g-code that it requires. 

> And the ultimaker original is older than the um2 and it has the function on cura. It's just i like to see an approximation of the cost for an impression...

That is true. Like i explained, we changed the way it worked for the UM2, but we realised that this was not the best way forward (and thus switched back again for the UM3). Unfortunately, it has to do with the way that firmware handles these things, so it's not up to Cura to do this.

**Comment by leo33700** [comment]
> 
> 
> > There was a time when i had this function on cura (i don't remember the version).
> 
> It didn't. It could be that you set the g-code flavor to something different. The UM2 not having material profiles is because of the specific flavor of g-code that it requires.
> 
> > And the ultimaker original is older than the um2 and it has the function on cura. It's just i like to see an approximation of the cost for an impression...
> 
> That is true. Like i explained, we changed the way it worked for the UM2, but we realised that this was not the best way forward (and thus switched back again for the UM3). Unfortunately, it has to do with the way that firmware handles these things, so it's not up to Cura to do this.

Ok and there won't be any update of the firmware of the UM2?

**Comment by nallath** [comment]
> > > There was a time when i had this function on cura (i don't remember the version).
> > 
> > 
> > It didn't. It could be that you set the g-code flavor to something different. The UM2 not having material profiles is because of the specific flavor of g-code that it requires.
> > > And the ultimaker original is older than the um2 and it has the function on cura. It's just i like to see an approximation of the cost for an impression...
> > 
> > 
> > That is true. Like i explained, we changed the way it worked for the UM2, but we realised that this was not the best way forward (and thus switched back again for the UM3). Unfortunately, it has to do with the way that firmware handles these things, so it's not up to Cura to do this.
> 
> Ok and there won't be any update of the firmware of the UM2?

No. We did change this behavior for the UM2+ though (so for the UM2+ you can select materials in Cura)

**Comment by fieldOfView** [comment]
What you can do is go into the Machine Settings in Cura, and change the gcode flavor to "Marlin" (instead of "Ultimaker 2"). This will let you set all material properties in Cura, but your printer will "complain" that the gcode will override any material properties selected on the printer.

**Comment by leo33700** [comment]
> 
> 
> What you can do is go into the Machine Settings in Cura, and change the gcode flavor to "Marlin" (instead of "Ultimaker 2"). This will let you set all material properties in Cura, but your printer will "complain" that the gcode will override any material properties selected on the printer.

Thanks a lot this work like you said !
