### ISSUE TITLE
Sign in issue

### ISSUE THREAD

**Issue by madigracesmith** [Ultimaker/Cura#10383]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

N/A

### Reproduction steps

When I tried to sign in on Cura, it took me to the website and asked me to allow it access and I clicked allow.

### Actual results

It said there was an error and that I needed to sign in again and click allow. But every time I click to sign in, it gives me that same screen that says I need to sign in again and click allow.

### Expected results

It's supposed to sign me in

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/90060038/132041920-b83f084e-e170-4b93-b88f-096200d5733b.png)

**Comment by nallath** [comment]
We've added more logging in 4.11 BETA. Could you use that and provide us the logs?
