### ISSUE TITLE
Cura won't slice the model

### ISSUE THREAD

**Issue by Enderdragon2236** [Ultimaker/Cura#10398]
### Application Version

4.9.1

### Platform

Mac OS 11.5.2

### Printer

Ender 3

### Reproduction steps

1. I made a model in Tinkercad that was 210x210 millimeters (Ender 3 build volume is 220X220)
2. I exported it to Cura
3. I tried to slice it and it said the model was too big for the build volume. What?!?

### Actual results

It said the model was too big and wouldn't slice

### Expected results

The model was just fine and Cura sliced it just fine

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

there is no additional info

**Comment by Enderdragon2236** [comment]
Please help!!

**Comment by nallath** [comment]
Please upload the model, preferably in a project file.

**Comment by Ghostkeeper** [comment]
Perhaps you will need to reduce the width of the brim around your 210mm wide object? You only have 2.35mm of space around it, so your brim will need to be quite small.

**Comment by Enderdragon2236** [comment]
Never mind it was because I left the bed adhesion on. Dumb noob error.

**Comment by jellespijker** [comment]
Good to know it is fixed and don't worry we have all been dumb noobs at one point in our lives 😉
