### ISSUE TITLE
Cura crashes on startup on OS X 10.10.4

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#104]
Cura 15.06 crashed directly after startup

This happened on 10.10.4 (14E46) on a Mid 2012  mac book pro retina.

System log:
20150704 00:04:44,073 Cura[4293]: Cura Error
20150704 00:04:44,073 Cura[4293]: 2015-07-04 00:04:44.072 Cura[4293:56327] Cura Error
20150704 00:04:46,060 Cura[4293]: Traceback (most recent call last):
20150704 00:04:46,060 Cura[4293]:   File "/Users/cmueller/Desktop/Cura.app/Contents/Resources/__boot__.py", line 77, in <module>
20150704 00:04:46,060 Cura[4293]:     _run()
20150704 00:04:46,061 Cura[4293]:   File "/Users/cmueller/Desktop/Cura.app/Contents/Resources/__boot__.py", line 62, in _run
20150704 00:04:46,061 Cura[4293]:     exec(compile(source, path, 'exec'), globals(), globals())
20150704 00:04:46,061 Cura[4293]:   File "/Users/cmueller/Desktop/Cura.app/Contents/Resources/cura_app.py", line 8, in <module>
20150704 00:04:46,061 Cura[4293]:     app = cura.CuraApplication.CuraApplication.getInstance()
20150704 00:04:46,061 Cura[4293]:   File "UM/Application.pyc", line 326, in getInstance
20150704 00:04:46,061 Cura[4293]:   File "cura/CuraApplication.pyc", line 64, in __init__
20150704 00:04:46,061 Cura[4293]:   File "configparser.pyc", line 937, in __getitem__
20150704 00:04:46,061 Cura[4293]: KeyError: 'general'

**Comment by awhiemstra** [comment]
This should be fixed in 15.06.01, that is available from the ultimaker site.
