### ISSUE TITLE
Monotonic ironing causes fanspeed jump to 255 for ironing pass

### ISSUE THREAD

**Issue by ferociousdiablo** [Ultimaker/Cura#10407]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Add model
2. Enable monotonic ironing
3. Slice
4. Check gcode file for extra M106 commands. Found M106 S255 on layers 25,96 and 99 in attached project.

### Actual results

Fanspeed jumps to max when it should not on layers 25, 96 and 99, fanspeed returns to specified speed on the next layer after each apart from the last.

[CFFFP_Cura fanspeed bug reproduction.zip](https://github.com/Ultimaker/Cura/files/7124552/CFFFP_Cura.fanspeed.bug.reproduction.zip)

### Expected results

Leave fanspeed as user has set it and do not interfere.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

First noticed this on a custom model which I cannot upload project for as it is an item I sell. Seems to happen on layer before ironing layer. I also noticed that there is an erroneous / extra travel move in layer 26 which I had previously reported back in 4.6 or so and was apparently 'fixed'.

![Screenshot 2021-09-07 224637](https://user-images.githubusercontent.com/42818303/132416520-3ba9ba66-e80a-4f6b-af96-9e74c9121a41.png)

**Comment by ferociousdiablo** [comment]
Also noticed that if you disable "Iron only highest layer" there is an additional M106 S255 on layer 25 which returns to specified speed on layer 26, and an erroneous / extra travel move on layer 26 (picture attached) which has been a long standing bug in Cura which I previously reported back in 4.6 or so. There is also an extra M106 S255 on layer 94 which returns to specified speed on layer 95 with only highest layer only disabled.

![image](https://user-images.githubusercontent.com/42818303/132414568-7520c14f-f947-41bd-aef2-ade08e1c7f99.png)

**Comment by fvrmr** [comment]
Hi @ferociousdiablo thank you for your report. 
I will bring this up with the team. Keep you posted.

**Comment by nallath** [comment]
I've found the issue. Fix is pending testing  & review.

**Comment by ferociousdiablo** [comment]
Thanks for the quick fix on this! Was driving me mad until I noticed what was going on with my ABS prints lol
