### ISSUE TITLE
Hole not being sliced

### ISSUE THREAD

**Issue by reza0310** [Ultimaker/Cura#10400]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality CR 10S pro

### Reproduction steps

1. I made the model using blender
2. I exported it as an STL file
3. I imported it in Cura
4. I scaled it down since the auto-scale was too much but I don't have to do this step with the creality slicer even if i have the same problem since the file is technically scaled properly
5. I sliced it and went to the layers view to check
PS: "Remove all holes" parameter is off and "Union overlapping volumes" parameter doesn't change anything but is currently off too
PS2: I thought it could be too precise for the printer but i already printed the same model with the hole even smaller and it worked. I didn't change any parameters so it might be my model or I just got lucky I don't know I'm a begginner.

### Actual results

The middle hole isn't sliced at all

### Expected results

I expected the layer view to have the hole that all the other views show

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[project.zip](https://github.com/Ultimaker/Cura/files/7117126/project.zip)
![1](https://user-images.githubusercontent.com/70545529/132244556-7676e0cf-c882-41cd-86eb-bb29350c30d4.PNG)
![2](https://user-images.githubusercontent.com/70545529/132244593-d2068c48-a35b-49f5-a19e-da4c9d47f715.PNG)
![3](https://user-images.githubusercontent.com/70545529/132244609-db67bb12-540b-4a50-bfcf-8b18f61d36a8.PNG)

**Comment by GregValiant** [comment]
When I turn off "Union Over-lapping Volumes" it's fine.
![Untitled](https://user-images.githubusercontent.com/64202104/132379344-49df2f30-88d9-44f9-b453-62ae1944b0fa.png)
[GVproject.zip](https://github.com/Ultimaker/Cura/files/7123040/GVproject.zip)

**Comment by reza0310** [comment]
The parameter is on each time I open Cura but deactivating it just before slicing work as you said. I might have deactivated it too late or thought it will still be deactivated whenever I reopen Cura and that's what blocked me probably. Thanks a lot I'm closing this issue.

**Comment by GregValiant** [comment]
When you start Cura and that "Profile" loads make sure of all settings and then click on the Profile name.  Near the bottom of the list of profiles will be a command "Update profile with current settings".  That should keep the setting from loading "turned on".
