### ISSUE TITLE
Error with support blockers

### ISSUE THREAD

**Issue by LonyWM** [Ultimaker/Cura#10408]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Voron v0.1

### Reproduction steps

1. Put something on the bed
2. Add a support blocker
3. Per model settings
4. Add infill density
5. Change the infil density
6. Try to slice 

### Actual results

Slicing failed

### Expected results

Slicing failed

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Cura_Project.zip](https://github.com/Ultimaker/Cura/files/7124917/Cura_Project.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7124908/cura.log)
![image](https://user-images.githubusercontent.com/90291787/132426348-3e8debdc-bb96-4bc8-bda0-5ea713c1010a.png)

**Comment by fvrmr** [comment]
Hi @LonyWM I can't open your project file, since I don't have your machine settings. Could you share the def.json of your machine and extruder with me?
