### ISSUE TITLE
Cannot change theme Cura 4.11

### ISSUE THREAD

**Issue by adalta87** [Ultimaker/Cura#10413]
### Application Version

4.11

### Platform

Windows 10

### Printer

CR6-SE

### Reproduction steps

Tried changing the theme to dark and blind dark modes and restarted on both but the theme will not change in cura. only have added 4 printers cr6-se, snapmaker a350, cr10 and a tevo tornado. I also added 3 custom print profiles for the cr6-se

### Actual results

nothing

### Expected results

theme change but did not actually change

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by fvrmr** [comment]
Hi @adalta87 could your share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by Ghostkeeper** [comment]
Still works okay as far as I can tell.

![image](https://user-images.githubusercontent.com/2448634/133777012-1f2a3f15-c1f9-4d95-9461-4ede9c0a0ba8.png)

**Comment by adalta87** [comment]
Sorry I have been away for awhile. Mine is now working as well odd that it didn't take after a cpl restarts but oh well its all good sorry for the delay!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ghostkeeper** [comment]
Okay! With a log file we could've maybe seen what went wrong. But if you can't reproduce it any more either, we'll have to chalk it up as a mystery.
