### ISSUE TITLE
Symlink check for plugins

### ISSUE THREAD

**Issue by thomaskilian** [Ultimaker/Cura#10416]
### Is your feature request related to a problem?

I do have a symlink for my own plugin that refers to some folder on my disk. When a new Cura version is loaded it does not recognize the symlink and issues a plain copy of the folder. 

### Describe the solution you'd like

A new version should check the folder for being a symlink and create another one in plugins.

### Describe alternatives you've considered

Well, I do that manually once I found out why my plugin changes did not take effect.

### Affected users and/or printers

Any

**Comment by konskarm** [comment]
Hi @thomaskilian. We understand that this is a bit annoying, but after we discussed, we decided that it is not going to be prioritized any time soon if we put it in our already long backlog. However, we would be happy to review and test a PR with a solution if you feel like contributing to our codebase.

**Comment by thomaskilian** [comment]
Fair enough. I haven't looked into Cura's code itself, but I'll see what time will give :-)

**Comment by Ghostkeeper** [comment]
I'd suggest starting with this function, which does the copying: https://github.com/Ultimaker/Uranium/blob/2db3496f941f008bee053b3f4275a76ef8550e5f/UM/Resources.py#L485

**Comment by thomaskilian** [comment]
Thanks! I already cloned the Cura sources and had a short look. Without that pointer it would have been hard to find. Especially when it's located in a totally different repo :-)
