### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by raymwe** [Ultimaker/Cura#10414]
### Is your feature request related to a problem?

when changing filament a window pops up, with a couple of columns - one says 'standard quality', the other 'current changes'. The selection is either 'keep changes', or 'discard changes'. I think this is misleading wording as to the changes that you are keeping or discarding. I have noticed that it is not apparent on the main page as to the filament type or printer that is selected, and that is not even mentioned on the window when a change is being made. It could be made a lot more obvious. I can see nothing on the screen to show me the filament, nor printer that I am using.- 

### Describe the solution you'd like

you could use bolder text/colour, etc to emphasise differences. use colors that do not obliterate the text. Don't hide away important information under two or three menu items.

### Describe alternatives you've considered

Writing my own gui

### Affected users and/or printers

everyone, in particular those not embedded in the way cura presents information.

**Comment by fvrmr** [comment]
Hi @raymwe thank you for your feature request. 
We had multiple request relating to the updated settings box. 
See https://github.com/Ultimaker/Cura/issues/9581 and https://github.com/Ultimaker/Cura/issues/7592 I will close this one as a duplicate.
