### ISSUE TITLE
Preparing to slice...

### ISSUE THREAD

**Issue by joostmarkerink** [Ultimaker/Cura#1041]
Sometimes when I am changing Print Job settings it stays at status "Preparing to slice". It seems that this happens when I change settings while it is still slicing. When it hangs in "Preparing to slice" the CPU is not busy. So it looks like it is waiting for current changes to be made, while there aren't any. Something with update changes queue maybe?
(running on Mac OSX Sierra).
I restart Cura to be able to generate the G-Code again.

**Comment by fieldOfView** [comment]
Which version of Cura is this? 2.1.3, or the 2.3 beta?

**Comment by red-green** [comment]
I'm having this error as well on Cura 2.1.3, downloaded from the official website, running on Mac OS 10.11. I was able to slice one model successfully, but now I can't seem to slice a second model (same settings as the first but with supports enabled).

**Comment by fieldOfView** [comment]
Try the Cura 2.3 beta, or wait a couple of days and try the Cura 2.3 final.

**Comment by red-green** [comment]
Update: On mac, manually killing CuraEngine and restarting the whole app seems to fix it for me.

**Comment by joostmarkerink** [comment]
Ah yes sorry. I forgot to mention. the version is 2.1.3

**Comment by nallath** [comment]
This should no longer be an issue. Haven't seen this in a long time.
