### ISSUE TITLE
Crashed GUI after new update

### ISSUE THREAD

**Issue by azorek777** [Ultimaker/Cura#10426]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

I installed a new version 4.11 then uninstalled the previous 4.10. 

### Actual results

The first run was fine, everything worked fine. After launching the computer a day later Cura GUI crashed and looks like this
![image](https://user-images.githubusercontent.com/57835812/132755257-147caa7d-7c01-459b-a333-41b35417291e.png)
Changing the theme doesn't help (for example Ultimaker Dark)
![image](https://user-images.githubusercontent.com/57835812/132755377-d8e21970-3bd0-470d-be04-18807d9a781b.png)

### Expected results

Cura should works like at first launch (it means fine)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7139483/cura.log)

**Comment by fvrmr** [comment]
Hi @azorek777 do you have problems with other programs that are using OpenGL?

**Comment by azorek777** [comment]
No, I uninstalled and installed it again. Then it started to work

**Comment by Ghostkeeper** [comment]
Maybe the installation failed then for some reason, the first time? It didn't install all of the files or something? Or maybe it was installed on top of a previous installation?
