### ISSUE TITLE
cura 4.11.0 will not let me save

### ISSUE THREAD

**Issue by Daemonforce** [Ultimaker/Cura#10427]
### Application Version

4.11.0

### Platform

windows 10

### Printer

creality 10 v2

### Reproduction steps

everytime i try to save to disk on desktop after slicing cura crashes 

### Actual results

cura crashes and i have to relaunch

### Expected results

i have to restart cura

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it doesnt matter what file im using it does it with every file it happend with cura 4.9 also

**Comment by fvrmr** [comment]
Hi @Daemonforce could you share your log file?
You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
