### ISSUE TITLE
Ultimaker printer said "Job was encoded by older CURA program, please use Cura4.4 or newer...  blablabla"

### ISSUE THREAD

**Issue by behpaja** [Ultimaker/Cura#10420]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ultimaker S5 with Bot image sides

### Reproduction steps

1. create cut on Cura 4.11
2. Load job on the USB Key
3. activate job on printer
4. push Ignore on the printer panel

### Actual results

Since Cura 4.10 I have this window message
I push Ignore and I can print my job

### Expected results

No need to push Ignore with Cura 4.11

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Type: Ultimaker S5
firmware of the printer: 5.5.12-20200226-ultibot
Id Type material: 9051-0

**Comment by fieldOfView** [comment]
This has been fixed in a newer version of the printer firmware. Please update your printer(s) to the latest firmware.

**Comment by behpaja** [comment]
Hello,
Have you got an link for the firmware?

Thanks
Pascal.

Pascal JANSSEN
RST Coordinator
Wet wipes
ESSITY BELGIUM SA-NV
Phone +32 87 306 729
Mobile +32 496 127 603
***@***.******@***.***>

**Comment by behpaja** [comment]
Hello,
I found them
Thanks
Pascal.

Pascal JANSSEN
RST Coordinator
Wet wipes
ESSITY BELGIUM SA-NV
Phone +32 87 306 729
Mobile +32 496 127 603
***@***.******@***.***>



Essity Internal
From: JANSSEN Pascal
Sent: 9 septembre 2021 12:02
To: Ultimaker/Cura ***@***.***>; Ultimaker/Cura ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Ultimaker/Cura] Ultimaker printer said "Job was encoded by older CURA program, please use Cura4.4 or newer... blablabla" (#10420)

Hello,
Have you got an link for the firmware?

Thanks
Pascal.

Pascal JANSSEN
RST Coordinator
Wet wipes
ESSITY BELGIUM SA-NV
Phone +32 87 306 729
Mobile +32 496 127 603
***@***.******@***.***>

**Comment by fvrmr** [comment]
Hi @behpaja  I will close this issue since it is solved with a firmware update. 
Thank you @fieldOfView
