### ISSUE TITLE
Support Blockers are not selectable when reloading a Cura project file.

### ISSUE THREAD

**Issue by DLLarson** [Ultimaker/Cura#10433]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender-3 V2

### Reproduction steps

I created several support blockers and saved the file as a Cura project file. When I reloaded the file I could see that the support blockers show up as part of the model but can't be selected:

![image](https://user-images.githubusercontent.com/175455/132958117-4e472ae9-1eb1-45bb-831d-00d50f09af5a.png)

### Actual results

When I run the slice operation the areas with the blocks are preventing supports but I can't select or adjust them at all.

### Expected results

I expect that I can modify, add  or delete support blockers between Cura project file load sessions.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file for bug.

[CE3_swoopingnight.zip](https://github.com/Ultimaker/Cura/files/7148358/CE3_swoopingnight.zip)

-Dale

**Comment by GregValiant** [comment]
Either ungroup the model and select the blocker or you can use CNTRL+Lt Click to select just the blocker in the group.

**Comment by DLLarson** [comment]
If I ungroup the model the support blockers lose their position and fall onto the bed. However the Ctrl-Lbutton click works so that will enable me to proceed. I do get lost in the UI at times. Weirdly. I can't seem to locate a comprehensive manual for such a popular program.

When I try to add an additional blocker which should be 1cm x 1cm it creates a cube that is over 15cm square-ish and is not exactly cube shaped:

![image](https://user-images.githubusercontent.com/175455/133107369-11b372c5-055a-4db7-a3e1-95aa11ad257b.png)

The model was scaled up 1500% right after import. The rescaling didn't give me issues when I added prior support blocker blocks. Something seem out of whack.

**Comment by nallath** [comment]
I think this might be related to https://github.com/Ultimaker/Cura/issues/9973

**Comment by DLLarson** [comment]
>I think this might be related to #9973

Yep. That's exactly what happens. I'm running on Windows 10 although someone in that issue said it was working on Win10 for him.
