### ISSUE TITLE
Infill

### ISSUE THREAD

**Issue by AndyCap777** [Ultimaker/Cura#10438]
### Application Version

4.11

### Platform

Windows 10

### Printer

Creality Ender 3v2

### Reproduction steps

1. I loaded my model into Cura 4.11 
2. I hit preview and rolled through the layers

### Actual results

I don't want to print because of the fear of it coming out like it looks in the slicer
![Capture1](https://user-images.githubusercontent.com/90554372/132984574-371e5dc5-2d58-49a4-902b-ae5117b622b5.JPG)

### Expected results

Like in version 4.10
![Capture2](https://user-images.githubusercontent.com/90554372/132984581-d5537057-1cb9-4f21-9ab9-af77600ad447.JPG)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture1](https://user-images.githubusercontent.com/90554372/132984559-401be592-6256-45e0-a71c-66d39468497a.JPG)
![Capture2](https://user-images.githubusercontent.com/90554372/132984567-86913b87-d604-4fff-b3a0-9cea78e1e769.JPG)

**Comment by AndyCap777** [comment]
Infill seems to be corrupt

**Comment by Ghostkeeper** [comment]
Maybe you had the Infill Support setting enabled?
