### ISSUE TITLE
cura 4.11.0 slicing failed using monotonic

### ISSUE THREAD

**Issue by coloso1967** [Ultimaker/Cura#10439]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. changed top surface skin layers to 3
2. top/bottom pattern to Zig Zag
3. enabled monotonic top/bottom order
![Screenshot 2021-09-12 093009](https://user-images.githubusercontent.com/56937294/132990517-143bffc4-cbf4-45fe-852d-fad8159226c2.png)

### Actual results

failed to slice

### Expected results

sliced to print

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7149681/cura.log)

**Comment by smartavionics** [comment]
See https://github.com/Ultimaker/Cura/issues/10418.
