### ISSUE TITLE
Cura 4.11 not seeing my 20 x20 bed leveling test 

### ISSUE THREAD

**Issue by Boomerang1224** [Ultimaker/Cura#10432]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Elegoo Neptune 2

### Reproduction steps

Loaded stl file into Cura not slicing but shows on screen 20 x 20 pattern.
load into Cura 4.10.0 works fine 
![2021-09-11 (2)](https://user-images.githubusercontent.com/90290865/132947050-ff8abf2f-7ceb-41ce-996e-9523f54d7ff8.png)

### Actual results

Nothing happens

### Expected results

Should slice like 4.10.0
![2021-09-11 (1)](https://user-images.githubusercontent.com/90290865/132946984-ea01c408-043f-4843-b8ac-4d8e2352e401.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Cura file.zip](https://github.com/Ultimaker/Cura/files/7147800/Cura.file.zip)

**Comment by smartavionics** [comment]
See https://github.com/Ultimaker/Cura/issues/10425.
