### ISSUE TITLE
support blockers

### ISSUE THREAD

**Issue by puchodog** [Ultimaker/Cura#10443]
### Application Version

4.11.0

### Platform

windows 11

### Printer

cr10v3

### Reproduction steps

`tried to use support blockers. the print would turn transparent and would not slice. 

### Actual results

couldnt slice

### Expected results

should have added the support block and allowed slicing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing more to say

**Comment by nallath** [comment]
Could you also add a project file? I've tried adding support blockers and it sliced for me.
