### ISSUE TITLE
OctoPrint Printing Time

### ISSUE THREAD

**Issue by Louisvilleboy81** [Ultimaker/Cura#10445]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality Ender-3

### Reproduction steps

After loading up a model to print. I slice the model, then I have the option to Print with OctoPrint. I click on this option, it takes me to the monitor tab of Cura. Here is listed all sorts of information about the current print job. Under the Active Print section, you have the Job Name, Printing Time, and Estimated Time Remaining. The Printing Time listed here is incorrect. I believe it is calculating the Printing Time + the Time Remaining. 

### Actual results

The Printing time is displaying the elapsed print time + the estimated time remaining.

### Expected results

The printing time to display the elapsed printing time. If the printing time is supposed to be the elapsed print time + the estimated time remaining, I would recommend adding a new line to this section, saying total print time. Then have Printing Time being the elapsed print time. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture](https://user-images.githubusercontent.com/11465756/133142672-dd2922c1-0018-4136-8ec8-0bad5844bf0a.PNG)

**Comment by nallath** [comment]
Please report issues with the octoprint plugin here: https://github.com/fieldOfView/Cura-OctoPrintPlugin/
