### ISSUE TITLE
Strange characters in Preferences

### ISSUE THREAD

**Issue by ajvdmeij** [Ultimaker/Cura#10446]
### Application Version

4.11

### Platform

macos Big Sur

### Printer

Creality Ender 3 V2

### Reproduction steps

I just opened Prefernces

### Actual results

The dropdown menus show strange characters. 
<img width="772" alt="Schermafbeelding 2021-09-13 om 23 37 28" src="https://user-images.githubusercontent.com/14240955/133159886-a4da0475-f222-4168-8e77-e7872bbee2ba.png">

### Expected results

I expected readable choices. I can not recognise the items in the menu.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no extra information

**Comment by nallath** [comment]
We don't fully support M1 yet: https://support.ultimaker.com/hc/en-us/articles/360018141480-Ultimaker-Cura-is-not-fully-compatible-with-the-Apple-M1-chip
