### ISSUE TITLE
Pint Settings Box not expanding

### ISSUE THREAD

**Issue by alevalle06** [Ultimaker/Cura#10448]
### Application Version

4.11

### Platform

Windows 10

### Printer

Artillery Sidewinder

### Reproduction steps

I adjusted to reduce size of print settings box to move it elsewhere

### Actual results

When I click to expand the print settings box, it does not expand anymore

### Expected results

The attached image is the only size I can search within the print settings box, which makes it difficult to find items. I used to be able to expand it all the way to the bottom of the screen. 
![Screenshot 2021-09-13 231015](https://user-images.githubusercontent.com/90674824/133204281-975bf1cf-67a9-4514-9990-e55edd608028.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This started with 4.10. I was hoping it would be fixed if I downloaded 4.11 but it did not fix it.

**Comment by Ghostkeeper** [comment]
Did you figure out what the issue was, or did you accidentally close this?
