### ISSUE TITLE
2.3 complete mix up of version naming

### ISSUE THREAD

**Issue by claus1009** [Ultimaker/Cura#1045]
I downloaded a file called:  Cura-2.3.0-BETA-win64.exe

But after installation "help-> about" tells me that I'm using a version 2.1.99
Also during the whole installation process the GUIs report about a verion 2.1.

Which version am I using now

This is really inconsistent and confusing?

**Comment by fieldOfView** [comment]
It's a known issue caused by an internal build accidentally being uploaded to the public server. The issue will be solved in a couple of days.

**Comment by ChrisRiddell** [comment]
@fieldOfView This issue is still half there in the stable release, in windows 10.

![capture2](https://cloud.githubusercontent.com/assets/2055566/19588105/03881ac0-97ab-11e6-9c91-0fe4d32441a7.png)

**Comment by CCS86** [comment]
On a slightly related question, is the new "stable" 2.3.0 an actual update to the "beta" 2.3.0?

**Comment by nallath** [comment]
@CCS86 A bit of both. There is one notable new feature in the stable release that was not in the beta; the network printing.
