### ISSUE TITLE
Wrong upload path sent to octoprint, fails when using moonraker

### ISSUE THREAD

**Issue by njoyard** [Ultimaker/Cura#10453]
### Application Version

4.10.0

### Platform

Linux

### Printer

Ender-3 Pro

### Reproduction steps

1. Setup klipper and moonraker for the printer
2. Configure printer and octoprint connection correctly
3. Prepare and slice a print
4. Send to octoprint

### Actual results

An error happens during upload. Moonraker responds with HTTP 400.

### Expected results

Gcode is uploaded.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Cura sends an errorneous `path` parameter value of `//` to Octoprint API when uploading a file.

We can get away with this behaviour when using octoprint because it happens to magically fix the path when saving the file.
However, when using moonraker which implements a compatible API this fails because `//` is not a valid value for the path parameter.

An empty path should be sent instead.

**Comment by nallath** [comment]
Please report issues with the octoprint plugin at it's own repo. You can find it here: https://github.com/fieldOfView/Cura-OctoPrintPlugin/
