### ISSUE TITLE
MKS WIFI plugin

### ISSUE THREAD

**Issue by paul88Flla** [Ultimaker/Cura#10469]
### Application Version

4.11.0

### Platform

windows 10

### Printer

wanhao d12/230

### Reproduction steps

I have problem, mks plugin wifi didn't run on my cura, on the last version ( 4.10.0) the plugin work well so i can't use my printer. please i need help <3
<img width="960" alt="cura" src="https://user-images.githubusercontent.com/90678559/133736927-258d75ab-745b-4afc-92ef-fa9e78d657ca.png">

### Actual results

The plugin dont work good,the icon does not appear 

### Expected results

nothing the bug is already here 
<img width="960" alt="cura" src="https://user-images.githubusercontent.com/90678559/133737314-3bae749f-59ce-46cc-aa9a-32e6fbc6616b.png">

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

helpp, paul.flageollet@gmail.com for any contact 
<img width="960" alt="cura" src="https://user-images.githubusercontent.com/90678559/133737218-143f2fda-23e3-4901-b1d8-a3d45ed4dc46.png">

**Comment by nallath** [comment]
We don't develop that plugin. Please contact the author of that plugin. The listed website for the plugin is: https://github.com/Jeredian/mks-wifi-plugin
