### ISSUE TITLE
Install failed Cura 4.11.0 - CX_Freeze: Python error in main script - Windows 7  

### ISSUE THREAD

**Issue by Snowpex24** [Ultimaker/Cura#10465]
### Application Version

4.11

### Platform

Window 7

### Printer

None 

### Reproduction steps

1.- Download cure 4.11 from the official website.
2.- Run as administrator.
3.- Finish installation.
4.- Launch cure
5.- Error panel for Cx_Freeze

### Actual results

A error panel is displayed 

CX_Freeze: Python error in main script  

### Expected results

start cura 4.11

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![242075546_3084754475088362_7522116972221532367_n](https://user-images.githubusercontent.com/90872649/133690109-eb6b2b79-e9fd-4ce4-9ea5-0669a39091c7.jpg)

**Comment by nallath** [comment]
From the changelog: _From version 4.11 onwards - Ultimaker Cura is only supported on operating systems actively maintained by their software manufacturer or community. This means Windows 7 and MacOS 10.13 will no longer be supported. Technically this means Ultimaker will stop testing and developing for such operating systems. However, even though it is no longer supported, there is still a high likelihood the application keeps functioning._

I would strongly recommend you to upgrade to windows 10. Windows 7 is end of life and no longer supported by windows.
