### ISSUE TITLE
3MF FIle fails to open

### ISSUE THREAD

**Issue by mscherotter** [Ultimaker/Cura#1046]
The attached file fails to open in Cura 2.1.3 downloaded from the Windows Store:
[Rocket_Camera_Mount.zip](https://github.com/Ultimaker/Cura/files/529888/Rocket_Camera_Mount.zip)

**Comment by Ghostkeeper** [comment]
Has been fixed since. This file opens fine in Cura 2.3. It looks like a pencil sharpener.
