### ISSUE TITLE
UM S5 Pro Active Levelling problem

### ISSUE THREAD

**Issue by TheDesignerDan** [Ultimaker/Cura#10461]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ultimaker S5 Pro Bundle

### Reproduction steps

1. Print a part using PLA in nozzle 1 and Breakaway in Nozzle 2.
2. Set up a new print using PLA in nozzle 1 and Breakaway in Nozzle 2.

### Actual results

1. When active levelling, the printer first probes the glass with nozzle 1 and nozzle 2. Both nozzles are heated. Left-over breakaway from inside nozzle 2 oozes out of nozzle 2.
2. Then, the printer probes most of the glass with nozzle 1.
3. During this time, nozzle 2 is cooling down.
4. When the printer then probes the rest of the glass with nozzle 2, a blob Breakaway material has hardened under nozzle 2.
5. The printer either levels nozzle 2 too high relative to nozzle 1 - meaning the print will fail -  or the print fails immediately.
![20210916_160137](https://user-images.githubusercontent.com/83696953/133627860-f13f6163-bc1f-4db9-a32b-c67089fbb48b.jpg)

### Expected results

Both nozzles should remain hot while active levelling, to ensure that any extra oozed material is liquid and does not interfere with levelling.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All information provided above.

**Comment by nallath** [comment]
This is unfortunately not something we can help you with. The leveling procedure isn't something that is controlled by Cura, but by the machine itself. 

You can get into contact with the hardware support via this link: https://support.ultimaker.com/hc/en-us/requests/new
