### ISSUE TITLE
Slicing non-closed meshes - Single extrusion at faces, no volume

### ISSUE THREAD

**Issue by TheRooster13** [Ultimaker/Cura#10476]
### Is your feature request related to a problem?

I am trying to design lightweight/fast printing/cosmetic models. I want the models to print with a single extrusion, but each layer isn't an enclosed space.

For example, a topographical map model, printing on edge. It has height and width, but no depth. I want to use as little plastic as possible, and to print as quickly as possible.

### Describe the solution you'd like

Ideally, I could create a non-closed stl file with just the surface. Slicing this stl file would create gcode that extrudes a single bead of plastic that goes back and forth, following that surface up the model.

### Describe alternatives you've considered

I've tried hollowing/extruding/thickening models and enabling thin wall detection. This causes problems when the surface is close to horizontal. With a constant part thickness, the purely horizontal thickness gets pretty big when surfaces are close to horizontal.

I've tried enclosing the model and then cutting the part I don't want away. This wastes a lot of plastic and time printing features that get cut away and discarded.

### Affected users and/or printers

I can see this feature being useful for people who want to design/print lightweight models (like RC airplanes) or 3D "paintings" like topographical maps or fast-printing models where only the surface is important, not the part thickness.

**Comment by Ghostkeeper** [comment]
Surface mode may do what you need.
