### ISSUE TITLE
Seperate line width for top and bottom layers

### ISSUE THREAD

**Issue by DragonFlyer007** [Ultimaker/Cura#10489]
### Is your feature request related to a problem?

Often only one side of the printed model needs a fine finish, and a smaller line width on that layer can absolutly help with that. It will give that layer a higher "resolution".

Cura can only set both top and bottom the same.

### Describe the solution you'd like

Individual line width settings for top and bottom layers.

### Describe alternatives you've considered

None

### Affected users and/or printers

This will benefit everyone much!

**Comment by Ghostkeeper** [comment]
Currently the top and bottom skin areas are joined together into one area. This prevents getting a separation between those areas like what Top Surface Skin does:
![image](https://user-images.githubusercontent.com/2448634/134912766-c5a278f6-15e3-4b75-8711-0898256227f7.png)

Introducing different pattern settings for the top vs. bottom skin will add that border. This will be visible in the print.

**Comment by DragonFlyer007** [comment]
> Currently the top and bottom skin areas are joined together into one area. This prevents getting a separation between those areas like what Top Surface Skin does: ![image](https://user-images.githubusercontent.com/2448634/134912766-c5a278f6-15e3-4b75-8711-0898256227f7.png)
> 
> Introducing different pattern settings for the top vs. bottom skin will add that border. This will be visible in the print.

But how can you change pattern for bottom skin?  The line direction setting? SEt to "[0,90]" now, But how could you change the bottom skin layer here?


Thanks
