### ISSUE TITLE
Settings Ender 3 V2

### ISSUE THREAD

**Issue by anmalo1** [Ultimaker/Cura#10526]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Add new Printer Ender 3 oder Ender 3 Pro for the Ender 3 V2?
Ender 3 V2 is not Listed.

Or can i not use this Software with Ender 3 V2 ?
(Creality Software not Work 4.8.2-177, missing Nozzles and Default Profiles)

Regards
Andrew

### Actual results

New installed...

### Expected results

Updated

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by GregValiant** [comment]
Creality is responsible for the Printer Definitions for their machines.  You should be able to use the Ender3 definition with no problems.
