### ISSUE TITLE
After rotation the percentages of the scaling-tool are not set 100% 

### ISSUE THREAD

**Issue by 3DAmsterdam** [Ultimaker/Cura#1053]
After rotating an object the percentages are referring to the not rotated measurements
![rotatiebug01](https://cloud.githubusercontent.com/assets/9759412/19471483/baa64da6-9523-11e6-828f-ff1fedbcda94.JPG)
![rotatiebug02](https://cloud.githubusercontent.com/assets/9759412/19471496/caedbaa0-9523-11e6-90a8-853cbfacce4e.JPG)

.

**Comment by nallath** [comment]
This has been fixed in 2.3
