### ISSUE TITLE
Profile import ignores 'infill_pattern'

### ISSUE THREAD

**Issue by turekwet** [Ultimaker/Cura#1054]
To reproduce:
1. Choose "Profile -> Manage Profiles..." from menu
2. Click any profile that doesn't have "infill_pattern" specified (it will be visible on right side).
3. click "import" and choose profile file that specifies "infill_pattern", for example 
   [LinearBearingBrick.curaprofile.txt](https://github.com/Ultimaker/Cura/files/535958/LinearBearingBrick.curaprofile.txt)
4. Click just imported profile so its settings are shown on the right. "infill_patter" should be present there but it isn't.

This can be workaround by changing step 2. above and clicking a profile that has "infill_patter" specified.

reproduced on
cura version: 2.1.3
OS: Linux Mint 17.3 Rosa

I haven't investigated whether this bug concerns only "infill_pattern" or it happens to other fields as well.

**Comment by Ghostkeeper** [comment]
I can't reproduce this in version 2.3. We rewrote our entire setting architecture since then.

We also had some display issues in the profile manager more recently, but I think those weren't in 2.1 yet.
