### ISSUE TITLE
Cura Settings Guide

### ISSUE THREAD

**Issue by AKCirc** [Ultimaker/Cura#10549]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ultimaker

### Reproduction steps

Clicked on Infill - connect infill lines. Requested help information.

### Actual results

 In Cura Settings Guide 2.7.1  the images for Connect Infil Lines are identical. The description states that these should be very different.

### Expected results

The images should be different.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All projects have this result.
![Connect](https://user-images.githubusercontent.com/91735149/135617365-5f1ba17c-5f11-4c95-b457-3ebe9efdb817.png)
)

**Comment by nallath** [comment]
Please report issues with a plugin with the repository of the plugin. In this case that would be: https://github.com/ghostkeeper/settingsguide

**Comment by Ghostkeeper** [comment]
You can see in your own screenshot that in the left picture, the lines have open ends, while in the right picture the endpoints of the lines are connected via the side ;) Just needs a more careful eye, is all.

Maybe reducing the scale of that model could make it more clear to see.
