### ISSUE TITLE
Print too many Walls

### ISSUE THREAD

**Issue by marco-117** [Ultimaker/Cura#10555]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

- Load Modell with a wall thiknes of 1.2 mm. 
- The printer uses a 0.4mm nozzle
- Wall Line count is 2

### Actual results

I had issues with missing materail in the outer wall. I tried many things, nothing works.
Then i looked even closser in the preview and i recognized that cura prints the one inner wall (1,2mm model thicknes = 2 outer walls + 1 inner wall) two times! But in the preview you can see just one inner wall. The second inner wall is printed with 0-10% flow over the existing wall.
I must aktivate wall overlaps compensation and set it to 10% minimum flow to prevent cura from printing the second wall.
Therefore i assume that ist musst print with 0-10% flow.

I also tried to deaktivate thin wall printing. But this wall is super thin. Why does cura want to print it without this option?

### Expected results

I think there should be only one wall, when there is no space for two. Even if  the wall line count is >1

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[2nd-Wall_Issue.zip](https://github.com/Ultimaker/Cura/files/7273206/2nd-Wall_Issue.zip)

**Comment by fvrmr** [comment]
Hi @marco-117 thank you for your report. 
This how the engine works and it is solved in our Arachne build. Read here more about our Arachne build: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta

Let me know if that works for you!
