### ISSUE TITLE
Error slicing

### ISSUE THREAD

**Issue by inqusi** [Ultimaker/Cura#10550]
### Application Version

4.11.0

### Platform

WINDOWS 10

### Printer

Creality Ender 3

### Reproduction steps

Opened the model STL, slicing
[23.zip](https://github.com/Ultimaker/Cura/files/7269451/23.zip)

### Actual results

error
![1](https://user-images.githubusercontent.com/81592238/135671013-b6ecd9b6-962e-44f9-807c-e4d3bab8e9de.png)

### Expected results

slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3_23.zip](https://github.com/Ultimaker/Cura/files/7269460/CE3_23.zip
[cura.log](https://github.com/Ultimaker/Cura/files/7269473/cura.log)
)

**UP.** If you move the model, you can find the position at which the slicing will work. But if you throw off the position of the model, then again the error

VIDEO:
[video.zip](https://github.com/Ultimaker/Cura/files/7269551/video.zip)

**Comment by TheHawk25** [comment]
Check #10418, many people seem to have this problem if you use zigzag patterns with the new mono-direction slicing.

**Comment by Festivejelly** [comment]
I've noticed I get this if I do "arrange all models" but only on my Tronxy X5SA profile, works fine on CR10. If I manually place them on my tronxy it seems to work fine.
