### ISSUE TITLE
Custom Machine Prefix

### ISSUE THREAD

**Issue by JohnnyWobble** [Ultimaker/Cura#10560]
### Is your feature request related to a problem?

I was using an MP10 for a while, and I had to create a custom profile for it (based on the custom FFF printer), well the machine prefix for it was CFFFP, which was pretty unhelpful. If I had to make another custom profile for a different printer, there would have been some mild confusion. Also, I have been using a Creality CR6 SE recently, and the machine prefix is CCR6SE, which I would like to be able to change to CR6 or CR6SE.

### Describe the solution you'd like

I think at the very least, allow custom machine prefixes for custom printer profiles, but might as well allow all of them, right? 

### Describe alternatives you've considered

The only alternative is turning them all off completely, but I do like them, they allow me to easily different gcode files.

### Affected users and/or printers

It will affect custom printer profiles, if not all printer profiles. I've seen a bit of grumbling online about this, but nothing too much, but at the very least, it can't hurt right?

**Comment by fieldOfView** [comment]
See the Printjob Naming plugin in the Marketplace. It will let you do this and more.
