### ISSUE TITLE
Cura OAuth redirection failure when login and return to localhost

### ISSUE THREAD

**Issue by Sergioloid** [Ultimaker/Cura#10591]
### Application Version

4.11.0 (installed via SNAP)

### Platform

Manjaro KDE (Arch linux)

### Printer

Ender 3 V2

### Reproduction steps

Hello guys, here's the repro-steps.

1. I click on the Sign-in button
2. Chrome (or any browser) open and ask me to log in
3. login was successful and I was redirected to localhost in order to finish the OAuth flow
4. localhost refuses to connect as if the 'webserver' doesn't exist or is not running up
The localhost address in which I was redirected is: http://localhost:32118/callback?code=gI6aOEaQN49vn5mdv-KfGL7RwnoLM45V&state=F0C545C2F4FA6EEDA617B454E0D34BF5

I've tried also to stop any running webserver like httpd or npm instance but without luck. Tried to run CURA with sudo permissions without luck.

It seems like cura has an internal web server or something similar that uses to authenticate requests, but it's actually not working.
No cura.log found in suggested path or with Show settings folder.

### Actual results

I can't login to CURA application.

### Expected results

To login to CURA.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing

**Comment by fvrmr** [comment]
Hi @Sergioloid thank you for your report.
Could you try if this also happens with the AppImage? https://ultimaker.com/software/ultimaker-cura
We don't maintain the packages via snap.
