### ISSUE TITLE
[4.11] Artifacts on top surface

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#10598]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Cr10S

### Reproduction steps

1. Load an STL
2. Default CR10S profile
3. Slice

### Actual results

There are artifacts on the top layers, which disappear going up.

### Expected results

Filled top layers

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![l8](https://user-images.githubusercontent.com/20385116/136773078-8402f473-784d-446e-93f1-2788f0920d2d.png)
![l9](https://user-images.githubusercontent.com/20385116/136773082-69770b25-fd3e-4c3d-81f7-dac2b7cf3f19.png)
![l10](https://user-images.githubusercontent.com/20385116/136773084-c4653bca-4278-4703-98a8-6f053031722a.png)

[CCR10S_top artifact.zip](https://github.com/Ultimaker/Cura/files/7321606/CCR10S_top.artifact.zip)

**Comment by Liger0** [comment]
There's no geometry there, so it shouldn't exist to begin with.

**Comment by TheSkittle** [comment]
Try turning on ironing. Also, how did u turn on dark mode?

**Comment by Liger0** [comment]
> 
> 
> Hi @Liger0 thank you for your report. The explanation of @smartavionics is correct. I will close this issue since this is not something we want to fix.

Hi, I don't understand why it isn't something that's worth to fix. 

There are printed lines where there are no features in the models, which cause gaps in a totally full surface, and the next layer won't grip into something solid becoming weak.

If you print a full cube you don't want random empty shapes in it, right?

**Comment by Liger0** [comment]
> 
> ![image](https://user-images.githubusercontent.com/2448634/137728929-4f48fb48-0d74-4fa6-b19b-daac93de5f88.png)
> 
> You want the skin to have a hole there underneath the bump, in several of the layers. If not, it's filling an unnecessarily thick skin there.

I thought the top layers were to have full layers for the next parts to grip on.
What is the advantage of having small gaps following the future geometries and then another full one in between the two?
