### ISSUE TITLE
Skin edge support causes infill pattern redo

### ISSUE THREAD

**Issue by sanblangar** [Ultimaker/Cura#10592]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Seckit SK-GO 2

### Reproduction steps

Activate connect infill lines
use X layers of skin edge support layers
slice
print
[Cura_bug.zip](https://github.com/Ultimaker/Cura/files/7315889/Cura_bug.zip)

### Actual results

the preview shows the printhead printing over the already printed infill, and the actual printer does accordingly causing extruder skipped steps and overextruded infill lines
[CFFFP_Spur Gear (20 teeth)(Mirror) - Ultimaker Cura 2021-10-09 09-34-09.zip](https://github.com/Ultimaker/Cura/files/7315877/CFFFP_Spur.Gear.20.teeth.Mirror.-.Ultimaker.Cura.2021-10-09.09-34-09.zip)

### Expected results

A normal infill

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Cura_bug.zip](https://github.com/Ultimaker/Cura/files/7315874/Cura_bug.zip)

**Comment by smartavionics** [comment]
See https://github.com/Ultimaker/CuraEngine/issues/1490.
