### ISSUE TITLE
Menus don't follow mouse on Wayland in HiDPI

### ISSUE THREAD

**Issue by njoyard** [Ultimaker/Cura#10608]
### Application Version

4.11.0

### Platform

Linux (arch)

### Printer

Ender-3 Pro

### Reproduction steps

1. Click on a menu
2. Move the mouse to select a menu entry

### Actual results

Menus don't follow mouse. The tiniest mouse movement moves focus to the previous menu to the left. Keep moving and eventually the "File" menu is opened.

### Expected results

Menus work correctly

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

All packages up to date as of this writing. Using sway v1.6.1, qt5-base v5.15.2. Display is HiDPI with scale 2. 

`QT_QPA_PLATFORM` is set to `wayland`. Issue disappears when using `QT_QPA_PLATFORM=xcb` (but then I lose HiDPI scaling of course).

The issue has been present for as long as I've been using Cura (since 4.7 I think).

I could not reproduce the issue with other qt5 apps (tried pcmanfm-qt).

Here is a video recording showing the issue:
https://user-images.githubusercontent.com/127842/137002767-6d611a33-7039-47e9-bba4-39593baf2506.mp4

The following log file was saved while the above video was recorded (and with `WAYLAND_DEBUG=1`):
[cura-menu-issue.log](https://github.com/Ultimaker/Cura/files/7332057/cura-menu-issue.log)

**Comment by stef-ladefense** [comment]
> Hi @njoyard thank you for your report. Do you have this issue also with the AppImage of Cura? You can download the AppImage here: https://github.com/Ultimaker/Cura/releases/tag/4.11.0

it's ok with appimage of cura last 4.11 in wayland and x11
but not with fedora paquet 4.11.0-1.fc35
