### ISSUE TITLE
Strange message

### ISSUE THREAD

**Issue by rolanddemeester** [Ultimaker/Cura#10606]
### Application Version

4.11

### Platform

windows 10

### Printer

Ultimaker S5

### Reproduction steps

When sending a print file to the printer, a message on the printers' screen is displayed:

"This file is made with an older version of Ultimaker Cura. For optimal performance prepare your print job with Ultimaker Cura 4.4 or higher."
buttons available : Ignore Abort

I pressed "Ignore"

### Actual results

Normal behavior

### Expected results

I don't want that message, because I have to walk to the printer to remove the message, something not always possible (remote printing)
Moreover, the printer status in Cura is "preparing...", so you are not noticed that that printer is waiting for some input.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no files uploaded

**Comment by fvrmr** [comment]
Hi @rolanddemeester thank you for your report. 
You need to update your firmware of the Ultimaker S5.
See https://github.com/Ultimaker/Cura/issues/10062 I will close this issue, since this is a duplicate.
