### ISSUE TITLE
Export not complete

### ISSUE THREAD

**Issue by Lucacido** [Ultimaker/Cura#10601]
### Application Version

4.10.0

### Platform

windows 10

### Printer

Creality Ender 3 PRO

### Reproduction steps

Create Custom Material with many settings, including price and weight
Exporting Material to file

### Actual results

edit Exported file using a notepad : price and weight are not included 
when you import this material price and weight are 0 !

### Expected results

price and weight need to be exported as well

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

expecting a new release...I can receive a TEST version to participate to tests if you need some help !

**Comment by Liger0** [comment]
I reported this years ago.

**Comment by Lucacido** [comment]
there are many posts, difficult to read them all.
sorry for the duplicate topic.

so DEV TEAMS ! UP ! when can you fix it ?
this should be consider as a bug, and not as a new feature  !

**Comment by Ghostkeeper** [comment]
This is indeed a duplicate of #5948.
