### ISSUE TITLE
НЕ возможен предварительный просмотр.

### ISSUE THREAD

**Issue by Pavel1610** [Ultimaker/Cura#10619]
### Application Version

4.11

### Platform

windows 7 x64

### Printer

ender 3

### Reproduction steps

#
![Безымянный](https://user-images.githubusercontent.com/85416286/137379205-50911e8b-bf40-41ee-83aa-1f00b643e49c.png)

### Actual results

# #
![Безымянный](https://user-images.githubusercontent.com/85416286/137379163-e4ddba47-d5a3-42b7-a896-99f2b5363c0c.png)

### Expected results

Как открыть предварительный просмотр?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Как открыть предварительный просмотр проекта

**Comment by fvrmr** [comment]
Hi @Pavel1610 thank you for your report. 
I think you need to update one of your plugins. If that is not the case could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

Also for next time please fill in the form in English.
