### ISSUE TITLE
Start G Code screwed up!!

### ISSUE THREAD

**Issue by Cooly1911** [Ultimaker/Cura#10621]
### Application Version

4.11.0

### Platform

Win 7

### Printer

Ender 3 V2

### Reproduction steps

I want to send G28, preheat my bed and hotend, then G29 prior to printing from Cura settings start G-code.  But it goes to the print temp, then cools down as it G28 and G29's, then stops because the temp is now wrong!  What the hell did 4.11.0 screw up?????

### Actual results

It locks up my printer and kicks out an error.

### Expected results

Start G-code is supposed to "START" from there? YES?  The Start-code first, then print!

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I saved and started the print from my octopi, and tried starting from Ultimaker.  Same bad results

**Comment by fieldOfView** [comment]
Please calm down a little, there is no need to scream.

Cura checks if the start gcode snippet contains a heatup sequence. If it doesn't, Cura adds a heatup sequence before your start gcode. This is to prevent "cold extrusion", ie to protect your printer.

The way Cura checks to see of there is a heatup sequence in your start gcode is by checking for certain replacement patterns. If you add something like the following sequence in your start gcode snippet, Cura will not add a heatup sequence of its own in front of the start gcode.

```
M140 S{material_bed_temperature_layer_0} ; set bed temp
M190 S{material_bed_temperature_layer_0} ; wait for bed temp
M104 S{material_print_temperature_layer_0} ; set extruder temp
M109 S{material_print_temperature_layer_0} ; wait for extruder temp
```

It is important NOT to fill in the text between the {}; do NOT fill in temperatures there, Cura will do that for you.

**Comment by Cooly1911** [comment]
No one here is screaming.  I added that Code to preheat my nozzle to 150
and my bed to 60 prior to g28 followed by g29.  Please reread my message as
I clearly stated that and the fact that it went to the print temperatures
and then dropped. And then locked up my printer.  Do you have some
questions about what I'm explaining?

**Comment by GregValiant** [comment]
Maybe there is an issue between Octoprint and the printer?  If your start Gcode is similar to above then it shouldn't be a Cura or Creality problem.  If you can print the file from the SD card OK (bypassing Octoprint) then you will know.
