### ISSUE TITLE
build platform

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#1062]
Cura 2.3
Windows 10

As you see from the screenshot on the right side has a large gap.

![capture](https://cloud.githubusercontent.com/assets/2055566/19587995/359a2b76-97aa-11e6-876e-4abe9341f34a.PNG)

**Comment by Ghostkeeper** [comment]
This is correct. The right side has a larger gap than the left side because the nozzle is on the left side of the print head. So it can reach further towards the left than towards the right, without hitting the side of the printer with the head.
