### ISSUE TITLE
Printing time difference of >1d 4h between Cura 4.11.0 and Cura 15.04.6 on same STL

### ISSUE THREAD

**Issue by reibuehl** [Ultimaker/Cura#10629]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ultimaker 2

### Reproduction steps

1. Download Temperature Tower STL from https://www.thingiverse.com/thing:3064519
2. Slice with Cura 15.04.6 with 0.2 layer height, 0% infill, 2 outer layers - print time is 1h 25m
3. Slice with Cura 4.11.0 with same settings - print time is 1d 5h 42m

### Actual results

The calculated printing time from Cura 4.11.0 is >1d 4h longer than the one from Cura 15.04.6 on the same STL with the same settings. 

### Expected results

Printing time should not differ that much. A difference of a few minutes would be okay but differences of >1d seem to point to a bug somewhere. Since the printing time calculated by Cura 15.04.6 is much more realistic for the same STL, I think that it is not an issue in the STL itself. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Temperature_Tower.zip](https://github.com/Ultimaker/Cura/files/7359939/Temperature_Tower.zip)

**Comment by Ghostkeeper** [comment]
So we'll consider this issue fixed for 5.0 then. Thanks for the report!
