### ISSUE TITLE
I can not switch the printer profile

### ISSUE THREAD

**Issue by landway** [Ultimaker/Cura#1063]
Hello,

I have a fundamental problem with CURA 2.3.0. I can not switch the printer profile. Neither the menu nor the preferences window I can not switch the printer profile. In preferences window I use button activate, but It does nothing...

PS: in attachment [screenshot cura um3 to um2go buildplate] it can be seen changing build platform, but not build envelope...

Love new CURA, please help....

![screenshot cura um3 to um2go buildplate](https://cloud.githubusercontent.com/assets/10966030/19600025/798885f0-97a3-11e6-9254-6602335bed39.jpg)
![screenshot cura um3 to um2go s rozevrenym menu](https://cloud.githubusercontent.com/assets/10966030/19599502/519ec286-97a1-11e6-8491-a1b0d786f31f.jpg)
![screenshot cura um3 to um2go v menu printers aktivace](https://cloud.githubusercontent.com/assets/10966030/19599503/51a06dca-97a1-11e6-9753-0bdf5bca6a76.jpg)
![screenshot cura um3 to um2go](https://cloud.githubusercontent.com/assets/10966030/19599504/51a8d906-97a1-11e6-8991-adf8670aefc2.jpg)

[cura.log.txt](https://github.com/Ultimaker/Cura/files/544387/cura.log.txt)

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/544365/DxDiag.txt)

**Comment by nallath** [comment]
Oh wow. That's a new one. I'll have a look at your logs.

**Comment by nallath** [comment]
I think this is caused by an issue that was in cura 2.1 which created profiles that shouldn't be there. We can't identify those profiles correctly, so they get converted to 2.3 automatically (but cause issues).

Could you try clearing your local data (make a backup first)?

**Comment by landway** [comment]
Yes I can... Can you tell me how, please? Btw, this problem I have from 2.3.0.rc1 so I uninstall it and install 2.3.0. and I have same problem. You are right with profiles.... i have old profiles in new instalation of CURA.

**Comment by nallath** [comment]
Go to help->show configuration folder

That is the folder that you need to backup (and then delete & reboot Cura)

**Comment by landway** [comment]
OK, I delete all files from c.f. and now it is ok. You are greate **nallath**! Everywhere I will praise you. Thank you.
