### ISSUE TITLE
Two Bugs

### ISSUE THREAD

**Issue by jonwienke** [Ultimaker/Cura#10638]
### Application Version

4.11

### Platform

Windows 10

### Printer

Creality Ender 5 Plus

### Reproduction steps

I'm having issues loading files and slicing.

The first and most common is a conflict with serial ports. If I have any standard serial devices connected, Cura hangs, sometimes for hours, before opening files or slicing. With serial devices plugged in, file loads hang, but as soon as I unplug the serial device, files load immediately as normal.

In addition, When Cura is running, it also conflicts with other devices that use serial ports. For example, I have issues running ProScan, which communicates with scanners via COM ports, or the U-Blox GPS test/diagnostic utility, when Cura i s running because it's accessing and locking serial ports, and I can't get it to stop.

On top of that, I'm getting this error intermittently when slicing:
![Screenshot 2021-10-18 231641](https://user-images.githubusercontent.com/73071393/137838168-05eeffc5-3c1f-40f2-a90f-8726a7adc77e.png)

### Actual results

The file doesn't load until I disconnect all serial devices, or Cura doesn't slice. Here's my log file:
[cura.log](https://github.com/Ultimaker/Cura/files/7369917/cura.log)

### Expected results

The file should load and slice regardless of whether I have serial devices connected to the computer.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I think I covered everything already.

**Comment by jonwienke** [comment]
A project file is attached.

 

Turning off the USB printing plugin seems to have resolved the other issues.

**Comment by fieldOfView** [comment]
Email attachments are filtered out by github. Please attach the log via https://github.com/Ultimaker/Cura/issues/10638 instead.
