### ISSUE TITLE
CTRL+Z history doesn't properly restore support blockers

### ISSUE THREAD

**Issue by cos-boop** [Ultimaker/Cura#10648]
### Application Version

4.10.0

### Platform

Linux Mint

### Printer

Anet A8

### Reproduction steps

1. Open a test cube STL. 
2. Select it
3. Press E and add support blockers randomly on one face
4. CTRL+Z #N times
5. CTRL+SHIFT+Z  #N times

### Actual results

Support Blockers appear randomly shifted in space

### Expected results

Support Blockers should reapper exactly where they were before being canceled by CTRL+Z

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This works with any STL I have tried.

**Comment by nallath** [comment]
I've also ran into this, so a PR that fixes it pending review / testing.
