### ISSUE TITLE
Tronxy X5SA Pro 2E Printer Controls/Jog Position

### ISSUE THREAD

**Issue by JoeCorder** [Ultimaker/Cura#10646]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Tronxy

### Reproduction steps

1. USB connected to Tronxy X5SA/X5ST/Pro default profile
2. Jog the Z axes  down (which moves the plate up) Click on 10 then click onto Z axes down button.
3. It will reboot the printer each time 
4. Once rebooted it moves the requested distant 

### Actual results

Reboot printer and then moves

### Expected results

Just move the z axes

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7383322/cura.log)

**Comment by 64bittuning** [comment]
> ### Reproduction steps
> 1. USB connected to Tronxy X5SA/X5ST/Pro default profile
> 2. Jog the Z axes  down (which moves the plate up) Click on 10 then click onto Z axes down button.
> 3. It will reboot the printer each time
> 4. Once rebooted it moves the requested distant

This is a firmware problem. Your only solution is to modify the maximum Z speed in the machine and slow it down. a Z max of 6-8 seems to work well.
