### ISSUE TITLE
Sliced layers contain holes if build plate contains several object

### ISSUE THREAD

**Issue by prizrak** [Ultimaker/Cura#10644]
### Application Version

4.11.0

### Platform

Mac OS X

### Printer

Custom

### Reproduction steps

1. Open and slice STL object
2. Observe resulted layers (layer 77) - no holes
<img width="1280" alt="Screen Shot 2021-10-20 at 15 20 23" src="https://user-images.githubusercontent.com/642534/138092540-99216715-b453-4b3b-98ef-5fbe203e1fa2.png">
<img width="698" alt="Screen Shot 2021-10-20 at 15 21 05" src="https://user-images.githubusercontent.com/642534/138093177-93d86aa7-cf4f-468e-8267-d3205a788866.png">
3. Apply multiplication modifier to existing object (or add another object) and slice again
4. Observe resulted layers (layer 77) - object contains holes every through one layer
<img width="1374" alt="Screen Shot 2021-10-20 at 15 20 02" src="https://user-images.githubusercontent.com/642534/138093483-06b95e9d-1380-4d6a-82b1-b0f68cc4013e.png">
<img width="1385" alt="Screen Shot 2021-10-20 at 15 19 50" src="https://user-images.githubusercontent.com/642534/138093747-45d314de-af9b-4ba3-ab07-faa2f5963a69.png">
<img width="1373" alt="Screen Shot 2021-10-20 at 15 19 29" src="https://user-images.githubusercontent.com/642534/138093769-6eaa9dd5-59fe-46be-8f18-a457e0648930.png">
<img width="930" alt="Screen Shot 2021-10-20 at 15 21 39" src="https://user-images.githubusercontent.com/642534/138093780-1cc97f6e-8287-47eb-a593-95c8176ce1ec.png">

### Actual results

If objects were multiplied (or added few) in sliced layers formed holes.

### Expected results

Holes must not be formed independently from count of objects on build plate.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Log file: [cura.log](https://github.com/Ultimaker/Cura/files/7381972/cura.log)
STL file: [Tail 05.STL.zip](https://github.com/Ultimaker/Cura/files/7381975/Tail.05.STL.zip) 
Project file: [CFFFP_Tail 05.3mf.zip](https://github.com/Ultimaker/Cura/files/7381978/CFFFP_Tail.05.3mf.zip)

**Comment by fvrmr** [comment]
Hi @prizrak thank you for your report. 
This is related to your model, looking at your model in x-ray view. You can see that there are meshes overlapping. 

![Screenshot (271)](https://user-images.githubusercontent.com/77000924/138265593-f570ebd7-370f-4188-ba48-2e5f31f29fa9.png)

As a work around you can disable `remove mesh intersection` under mesh fixes or move your models further away. 
![Screenshot (272)](https://user-images.githubusercontent.com/77000924/138266336-184692d0-72fa-479a-ba97-a3fbb7d5bd46.png)

Also see: https://github.com/Ultimaker/Cura/issues/10600, there you can read why this is happening in this comment: https://github.com/Ultimaker/Cura/issues/10600#issuecomment-945798124

I will close this as a duplicate.
