### ISSUE TITLE
Downscaled objects are not included in the skirt

### ISSUE THREAD

**Issue by PikaPenetrator** [Ultimaker/Cura#10645]
### Application Version

4.11

### Platform

Windows 11

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. Placed several object on the buildplate
2. Resized one of the objects to 99%
3. Slicing

### Actual results

The object I resized to 99% gets not included in the skirt

![Screw not included](https://user-images.githubusercontent.com/23237580/138116631-55c8c544-4321-46e4-af82-7e037abd346b.png)

Resizing back to 100% (or resizing it to a bigger version) works perfectly fine

### Expected results

I expect that all my objects are surrounded by the skirt

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Rotating_Clip-Joystick.zip](https://github.com/Ultimaker/Cura/files/7382188/CE3PRO_Rotating_Clip-Joystick.zip)

**Comment by Asterchades** [comment]
Check its location of your reduced object. It's probably no longer sitting on the bed, but slightly off it instead (Z > 0.0).

Bed adhesion only extends to objects actually on the bed.
