### ISSUE TITLE
Inappropriate "Can't Find Location" Warning.

### ISSUE THREAD

**Issue by Wheatron** [Ultimaker/Cura#10658]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Creality Ender 3 (modified for Creality Ender 3 V2)

### Reproduction steps

1. Click _File_.
2. Hover mouse over _Open Recent_.
3. Selected random, previously used stl object sized X=121.3379mm, Y=53.5404mm, and Z=91.2mm.
4. Repeat steps 2 and 3 to have two of the exact same stl objects within build volume boundaries.
![Cura Before Arrange](https://user-images.githubusercontent.com/93009535/138520589-a1afc915-6472-4c8d-a486-4cb19258da00.jpg)
5. Press key combination ctrl+r to arrange all models. Or right mouse click on either object or right mouse click on empty space then select _Arrange All Models_.

### Actual results

Cura prompts a "Can't Find Location" warning message stating, "Unable to find a location within the build volume for all objects" even though the models get rearranged properly and the build volume is set to X=220, Y=220, and Z=250.
![Cura After Arrange](https://user-images.githubusercontent.com/93009535/138520649-15591ec3-d580-486f-ad8d-32ea4f1e5cbe.jpg)

### Expected results

Models should get rearranged properly as it already does, but there shouldn't be a warning message about the objects not being able to both fit within the build volume.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Project file and stl file used.](https://github.com/Wheatron/Part_Cooling_Duct_-_263.5015.ZX_r2_v3-1-.stl.git)

**Comment by mennucc** [comment]
this warning reappeared in Cura-5.7.0-beta.1

**Comment by gyrex** [comment]
Same issue persists in 5.12.1

<img width="2316" height="1437" alt="Image" src="https://github.com/user-attachments/assets/89bda258-0009-4719-aa68-646d3ade1c72" />
