### ISSUE TITLE
Opening 3MF with support blockers, only open with one object

### ISSUE THREAD

**Issue by DragonFlyer007** [Ultimaker/Cura#10656]
### Application Version

4.11.0

### Platform

Win 10

### Printer

Cr10S

### Reproduction steps

Re-slice and save

### Actual results

If i open a model saved as 3mf, with support blockers, it will only show one object, so you cant edit the blockers anymore. Have to start from scratch.

Man Cura 4.11 is buggier than a forrest :/ 

### Expected results

Opening with all objects.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CCR10S_Fan case V3_Ender5_Hus.zip](https://github.com/Ultimaker/Cura/files/7393193/CCR10S_Fan.case.V3_Ender5_Hus.zip)

![5465654654](https://user-images.githubusercontent.com/90724902/138365530-a13b789a-b315-43fd-9089-9f0377dc3306.JPG)

**Comment by GregValiant** [comment]
In Windows _Control+Left Click_ on the object you want that is in a group.
