### ISSUE TITLE
Popup to new beta 4.12 send users to wrong page.

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#10661]
### Application Version

4.11

### Platform

Windows 10

### Printer

-

### Reproduction steps

Link popup sends me to:

https://ultimaker.com/learn/smooth-sailing-with-ultimaker-cura-4-11?**utm_source=cura&utm_medium=software&utm_campaign=cura-update-features**

### Actual results

-

### Expected results

I would like you to send me to the Github changelog and download the beta.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

a

**Comment by fvrmr** [comment]
Fixed in: https://github.com/Ultimaker/Cura/pull/10724 and https://github.com/Ultimaker/Uranium/pull/747
