### ISSUE TITLE
The market store must be alien language

### ISSUE THREAD

**Issue by oliverryanwong** [Ultimaker/Cura#10663]
### Application Version

4.12.0 -beta

### Platform

MAC Big Sur 11.6

### Printer

Creality Ender 3

### Reproduction steps

<img width="414" alt="Screen Shot 2021-10-23 at 11 36 56 AM" src="https://user-images.githubusercontent.com/44273025/138562757-feed78fc-63d5-4f2d-be50-702d5aeb9415.png">
<img width="885" alt="Screen Shot 2021-10-23 at 11 33 54 AM" src="https://user-images.githubusercontent.com/44273025/138562758-a278207b-2055-4d82-a7b5-3e1994b7fc39.png">

### Actual results

.

### Expected results

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by fvrmr** [comment]
Hi @oliverryanwong just to check, do you have a M1?

**Comment by Ghostkeeper** [comment]
We tend to see this sort of thing specifically when the text is not pixel-aligned.
