### ISSUE TITLE
Cura will not launch except from Applications folder (Mac)

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#10688]
### Application Version

All

### Platform

Mac OS 10.15.7 (Catalina)

### Printer

N/A

### Reproduction steps

Move Cura out of Applications folder
Launch Cura

This is a long standing issue I just finally decided to mention.  I have my apps in folders relating to their function, for organizational purposes (well, most of them, as some act like Cura and refuse to run properly when moved).  I.e., I have all my 3D related apps in one, my Productivity apps in another, my Utility apps in another, Graphics, Audio, etc., all in grouped folders, within the Application Folder itself.  With literally hundreds of apps on my system, I _have_ to organize things more cleanly.

### Actual results

Refuses to run.

If it is placed in the actual OS recognized "Applications" folder, it runs fine. 

### Expected results

Apps should run from wherever the user chooses to place them.  They are, after all supposedly self-contained (i.e., "containers"), with preferences and application support files stored in the user's Library folder hierarchy.  Where the app itself is located _should_ make no difference, this should be the users' choice.  Most of my apps don't care where they are, so it's not an inherent thing.

Running it from an Alias in the sub-folder pointing to the original in the Applications Folder works, but this is not my ideal solution.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by fvrmr** [comment]
Hmm strange. I tried it myself also on Catalina 10.15.7 and I could drag Cura to my desktop from the dmg with no issues. I created a folder in my application folder and that also works, both Cura launches perfectly.

**Comment by KenLucke** [comment]
I made a screencast, where I copied it directly from the .dmg to the sub-folder I keep my 3D apps.  You can see it copy, and when I launch it, it goes through some initial verification, but then does not run (if it were running, you'd see a little black tick mark next to its icon in the dock.

I then deleted that one, and copied directly to my applications folder.  Running that one goes through the standard steps, gets my clearance from my network monitor (which was never requested by the one above, so it never got that far) and actually runs and opens its interface.

https://www.dropbox.com/s/szhvkrgsm7sl543/%20Cura%20Not%20Launching.mp4

**Comment by Ghostkeeper** [comment]
What I see in that recording, is that MacOS pops up with a question that "This is an application downloaded from the internet. Are you sure you want to run this?", but that pop-up disappears immediately, seemingly without interaction. Maybe something is up with MacOS before it even starts Cura.

Do you have a log file of when it didn't open?

**Comment by KenLucke** [comment]
It disappears because I hit [Return] (which activates the default button) instead of moving the mouse to the button and clicking, because I was using the mouse to hold the dock open visually.  It does the same if I actually mouse the button.   I'll look for logs.

**Comment by KenLucke** [comment]
OK, it never gets as far as even creating the folder ~/Library/Application Support/Cura/<version number>.  Therefore, no log files, which I what I suspected would be the case.

To test, I zipped my current v4.12 beta preferences folder, moved it out of the ~/Library/Application Support/Cura folder just to be sure, and ran a freshly copied Cura from the non-application folder, while watching the ~/Library/Application Support/Cura folder.  The 4.12 folder was never created.  Running it from the Applications folder, that preferences folder was created and populated just a split second before the first splash screen for Cura showed (factoring in the time it takes for it to show up in a Finder window).

I also tried leaving the older 4.12 log file in place and ran the new app from the non-Applications folder to see if it would find it and modify it.  It didn't.  The log file was byte-for-byte identical to the one from prior to running the rogue folder app.

**Comment by KenLucke** [comment]
I'm finally being forced into upgrading from Catalina.  Photoshop's latest version refuses to use my graphics processor and continually tells me I'm an idiot for not upgrading.  It's been a long resistance, as there are some programs I use that simply will not run beyond Catalina, but now it's down to programs I use sometimes that won't work past Catalina, and those I *must* use (I am a photographer) requiring it.

So, I will no linger be able to test this on Catalina, unless one of the other accounts on this computer will stay on that OS after my main account upgrades.  I will let you know if the issue persists after the upgrade, as a data point.

**Comment by KenLucke** [comment]
OK, upgraded, issue still remains.

**Comment by Ghostkeeper** [comment]
> OK, it never gets as far as even creating the folder ~/Library/Application Support/Cura/. Therefore, no log files, which was I what I suspected would be the case.

Since it's happening before the configuration folder gets created, that means it stops before `Application.initialize()`, most likely even during the imports. If it is a Python error, it occurs even before the early-crash dialogue has been loaded, or you'd see a crash dialogue. The imports are likely because it's the very first thing that happens, and it expects to find Python libraries. But it could also just be that Python itself doesn't start when it's not in the Applications folder. It has libraries too.

Running from a terminal might garner a bit more information, but this is something we can expect from a developer rather than a user. I'm sharing this issue with the team to see what they think about it.

**Comment by KenLucke** [comment]
> Running from a terminal might garner a bit more information, but this is something we can expect from a developer rather than a user. I'm sharing this issue with the team to see what they think about it.

I can give that a try.  I'm not a typical user.  I've been using computers since the late '70s, and I'm fairly comfortable "on the metal," and have beta tested for literally decades.  Let me see what I can do.

**Comment by KenLucke** [comment]
Same results.  

```
{493} KensMacBookPro2018LAN: open -a "/Applications/3D Printer : CD/Ultimaker Cura.app" ; ps -e | grep "(Ultimaker|cura)"
69927 ttys000    0:00.00 grep (Ultimaker|cura)
{494} KensMacBookPro2018LAN: 
```

"Verification" dialog comes up, then the "Downloaded from internet, do you really want to run it?" dialog, then nothing.  No logs, no support folder, no active processes with "ultimaker" or "cura" in their name (with the exception of the grep process itself).  It creates the icon in the Dock when it tries to run, just as it does double clicking from the Finder, but it's not an active app (just the residual showing of one of the last three apps "run."  Clicking on that icon shows an instantaneous "running app" tick mark, but it disappears within a quarter of a second.  Not sure how to trace what's happening during that split second.  All the same as originally reported.

I also tried running the executable within the package directly, with the same results.

**Comment by zuul47** [comment]
Won't even launch on my Mac. It's a MacPro 2010 w/ High Sierra.

**Comment by GregValiant** [comment]
Is this still a problem in current versions of Cura (5.8.0 and up)?  Can this be closed?
