### ISSUE TITLE
Wrong code generation with "Pause at height"

### ISSUE THREAD

**Issue by VijitCoder** [Ultimaker/Cura#10680]
### Application Version

4.11.0

### Platform

KUbuntu 19.01

### Printer

Ender 3

### Reproduction steps

Take the model from the attachment.

Setup 4 Pauses at heights (in mm): 18, 19, 21, 22. Method: Marlin (M0)

Check generated gcode. Search `M0` commands. And there will be definitely wrong instructions, like this quote:

```
...
G0 X96.452 Y101.151
G0 X92.488 Y103.187
G0 X91.248 Y103.937
G0 X86.163 Y107.255
;TIME_ELAPSED:8860.767160
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current z: 19
;current height: 19.0
M83 ; switch to relative E values for any needed retraction
G1 F300 Z20 ; move up a millimeter to get out of the way
G1 F9000 X190 Y190
M104 S240 ; standby temperature
M0 ; Do the actual pause
M109 S240 ; resume temperature
G1 F9000 X86.163 Y107.255
G1 F300 Z19 ; move back down to resume height
G1 F1500 ; restore extrusion feedrate
M82 ; switch back to absolute E values
G92 E2406.42271
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current z: 18
;current height: 18.0
M83 ; switch to relative E values for any needed retraction
G1 F300 Z19 ; move up a millimeter to get out of the way
G1 F9000 X190 Y190
M104 S240 ; standby temperature
M0 ; Do the actual pause
M109 S240 ; resume temperature
G1 F9000 X86.163 Y107.255
G1 F300 Z18 ; move back down to resume height
G1 F1500 ; restore extrusion feedrate
M82 ; switch back to absolute E values
G92 E2406.42271
;LAYER:88
;TYPE:WALL-INNER
;MESH:holder eye.stl
G1 F1500 E2408.42271
G1 F2400 X85.255 Y108.016 E2408.45935
G1 X84.483 Y108.646 E2408.49017
G1 X83.373 Y109.645 E2408.53637
...
```

Here you can see two pauses one after the other, without any real printing. Also, heights are switched (19mm before 18mm). The same problem with a pair of 21/22 pauses. And the worse: Z height is changed. Eventually, impossible to print the model by this gcode.

### Actual results

Mess in the gcode. Failed printing.

### Expected results

Correct pauses and printing instructions.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I checked my instructions several times. All set up correctly. See screenshot as example:
![2021-10-26_16-08](https://user-images.githubusercontent.com/8523131/138847690-8d1f07d7-9067-45a0-bc98-b42ce420cb39.png)

Model and Project file [holder eye.zip](https://github.com/Ultimaker/Cura/files/7416727/holder.eye.zip)

**Comment by fvrmr** [comment]
Thank you for your picture! It looks really cool!

Yes you could indeed use Filament Change (but you can't set it to mm) or use pause at height but instead of height use layer.
Or my work around I mentioned above with changing the order. 

Based on that I will defer this bug, since it is a bit of an edge case. I hope you understand.

**Comment by VijitCoder** [comment]
> Based on that I will defer this bug, since it is a bit of an edge case. I hope you understand.

Yeap, no problem )

**Comment by kevin-aus72** [comment]
Hello VijitCoder
For some reason the pause at height when mm used is not working when using the height .. When you use the layer_number it works as what you are wanting to do.

**Comment by kevin-aus72** [comment]
Seems that the fault is with how the pause at height in mm mode is when it is searching for  a z height mm.
Also when the new gcode is added, it is inserted on the correct layer but not in the correct position. 

When the layer height equals the desired height would be the correct position.. to insert the gcode

**Comment by kevin-aus72** [comment]
Best solution would be to use Pause_at_height using layers 
layer count  = 18mm x .2  = 90 z height layer steps 

Pause at height falls over when you run it multiple post-process
