### ISSUE TITLE
XML Sidecar files

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#10687]
### Is your feature request related to a problem?

When I save a gcode file, it might be months before I go back and revisit it for some reason, maybe a minor tweak or size change.  By that time, if I even saved one, the project file containing all the settings may be gone for some reason.  Then I have to try to recreate the settings it used, which cannot be done from the gcode file.

### Describe the solution you'd like

The option to automatically save an XML "sidecar" file alongside (or, optionally, in a separate designatable directory) the .gcode file (same name, but with ".xml" suffix).  This would contain a plist or other listing of every single non-default parameter used to create that file, including the path to the original .stl/.obj file.  It would be like automatically saving a project file, but without the actual object embedded, as it is with a project.

The .xml could be loaded just as is a project file, and override the current settings, but would not replace the current object(s) on the build plate, as does a project file.   It would also be much smaller (saving disk space) than a project file.

In this way, you could even save favorite settings and reload them for _any_ model, not just the original.  I know that profiles can be saved within Cura, but when there are lots of different settings adjusted, and a huge number of different models and projects being produced, that list of profiles gets incredibly long and hard to filter through (not to mention trying to accurately name them all).

### Describe alternatives you've considered

Living with it the way it is :)

### Affected users and/or printers

Lots of people.

**Comment by fvrmr** [comment]
Hi @KenLucke thank you for your feature request. 
I have discussed this issue with a colleague and we decided to defer this issue. When you use the Digital Factory it saves a UFP and project file.

I hope you understand.

**Comment by KenLucke** [comment]
Surprise, surprise, not everyone uses the Digital Factory.

**Comment by Ghostkeeper** [comment]
But loading a project file back in would also create new profiles, unless you'd want to revert your existing profiles to that old version from the project file, right?

**Comment by KenLucke** [comment]
No, it would only affect the current project (and subsequent ones until the parameters changed, just as changing a single parameter does now), unless you then manually saved it as a profile.  It would be, essentially,m a quick way to change a bunch of parameters without cluttering up the Profiles list with dozens of sets of changes to name, scroll through, and remember off-hand what they were.
