### ISSUE TITLE
Add "Internal Brim Around Holes" settings for better attaching bottom layer holes to build plate

### ISSUE THREAD

**Issue by mathiasm74** [Ultimaker/Cura#10684]
### Is your feature request related to a problem?

To get a nicer top layer when printing something with thick walls, it's better to increase the "Extra Infill Wall Count" rather than the normal "Wall Line Count". However this means any holes in the bottom layer will have thin walls and not stick to the build plate.

I.e. this is nicer...
![image](https://user-images.githubusercontent.com/917776/138941440-5fe387d9-4ff0-4818-b394-be364f522f5c.png)

...than this...
![image](https://user-images.githubusercontent.com/917776/138941691-84c99598-2637-45ce-b381-ca72498cb657.png)

...but results in poorly attached bottom-layer hole walls, that results in failed prints.
![image](https://user-images.githubusercontent.com/917776/138942056-4d95066f-5686-4160-a19f-affe2936ed81.png)

### Describe the solution you'd like

Some setting that results in more bottom layer walls seems to be required. Maybe a brim setting that allow the brim to be drawn outwards around (small) holes, or allowing the brim to fill in smaller holes entirely.

### Describe alternatives you've considered

I've tried to turn off the "Brim Only on Outside" settings, but this only works on larger holes. There appears to be some limit on the inner radius of the brim that I've not find any way to change.
![image](https://user-images.githubusercontent.com/917776/138942983-f252721d-c7e4-4637-9c63-eb45e378cb99.png)

### Affected users and/or printers

Anyone printing a part with thin top/bottom walls and holes in a material that stick poorly to the build plate.

### Additional information & file uploads

This was an issue while printing this Voron part in eSun ABS+ on an Ender 5 Pro
[b_drive_frame_lower.stl.zip](https://github.com/Ultimaker/Cura/files/7420839/b_drive_frame_lower.stl.zip)

**Comment by fvrmr** [comment]
Hi @mathiasm74 thank you for your feature request. 
The brim in small holes will not be printed because small holes can cause over extrusion which is not very useful for bed adhesion. 
As a work around you could add a disk inside that you print with a concentric pattern. 

Let me know what you think!

**Comment by Ghostkeeper** [comment]
The brim is currently omitted in holes with an area of less than 100 square line widths (like, the area of a square of 10x10 line widths). Or partially omitted if only the furthest brim lines are below this area.

This limit is hard-coded in CuraEngine: https://github.com/Ultimaker/CuraEngine/blob/9042a0a4e2f31aef5c96d789c01b2ac10d676140/src/SkirtBrim.cpp#L105
