### ISSUE TITLE
"Machine center is zero" + "Z seam Allighment: BACK" cause curaengine.exe to crash

### ISSUE THREAD

**Issue by davidwyl** [Ultimaker/Cura#1070]
if i tick **"Machine center is zero"** in custom fdm printer and set "**Z seam Allighment**" to **BACK** , this will cause curaengine.exe to crash and stopped. This Message will pop up **"CuraEngine.exe has stopped working".**.
the problem disappear if i untick the **Machine center is zero**.

_How to reproduce the issue:_ Tick **"Machine center is zero"**, open 3DBenchy stl file,  and  set "**Z seam Allighment**" to **BACK**. Now Curaengine.exe will crash . 
i managed to reproduce this issue in 2 different wondows 10 pc.

**Comment by Ghostkeeper** [comment]
I could reproduce this also. I also tried on other meshes though (a half-sphere and a tetrahedron), but couldn't reproduce this on those. Perhaps it only happens with meshes that are not convex?

**Comment by davidwyl** [comment]
Working fine on square cube too but doesn't work on most of the stl files... Definitely some bug here.

**Comment by smartavionics** [comment]
Bug confirmation - same behaviour with cura 2.3.1 on Linux.

**Comment by smartavionics** [comment]
BTW - I made a discovery, moving the object away from the centre of the build plate (possibly so that none of the object overlaps the centre?) appears to avoid the crash.

**Comment by BagelOrb** [comment]
In Cura 2.4 Z Seam Alignment Back will be replaced by User Specified, so that you can choose yourself close to which point you want the z-seam to be.

With that feature the bug also disappeared :)
