### ISSUE TITLE
Make Overhang Printable makes vertical walls oscillate

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#10708]
### Application Version

4.11, 4.12 beta, more?

### Platform

Windows 10

### Printer

Ultimaker S5, probably any

### Reproduction steps

1. Load a model which has vertical walls
2. enable make overhangs printable
3. set angle to 70*

### Actual results

![image](https://user-images.githubusercontent.com/8895761/139533760-547ad86d-f175-446d-867d-8f304217cb24.png)

 Walls alternate in position. Odd layers have a small inset inward.

### Expected results

Straight walls
![image](https://user-images.githubusercontent.com/8895761/139533786-cff781bb-b11b-4e35-8a94-74f02b091e03.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[UMS5_proto.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/7446586/UMS5_proto.3mf.renamed.zip)

**Comment by BagelOrb** [comment]
If I leave the overhang angle at 50* then the odd layers aren't generated at all:
![image](https://user-images.githubusercontent.com/8895761/139533834-b6763431-1a11-44a7-8b51-459ae1f6293e.png)

**Comment by fvrmr** [comment]
Hi @BagelOrb thank you for your report. 
Your model displays at the top that it needs overhang. When you fix your model with mesh tool, it doesn't happen anymore. 
Can you check if that is also your case?

**Comment by BagelOrb** [comment]
Yeah. That's super weird. I never imagined that something like that could influence this feature, because after it's sliced all geometry should be the same regardless of normals.

Closing this issue because it's caused by a 'bad' model.
