### ISSUE TITLE
MacOS Monterey: Cura is not able to make multiple copys of one object

### ISSUE THREAD

**Issue by WolfgangDomroese** [Ultimaker/Cura#10706]
### Application Version

4.11.0

### Platform

MacOS 12.0.1

### Printer

Ender 3V2

### Reproduction steps

Put one Object to Cura by Fusion360. Select the object and select "Ausgewählte vervielfachen 3".

### Actual results

Cura stops showing a message:
![image](https://user-images.githubusercontent.com/15429256/139528437-13cd6733-78d8-4abd-8647-a730055fcd54.png)

The message does not disappear. And no

### Expected results

Cura should place 3 additional objects. Id did so before I upgraded to Monterey.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No further comment.

**Comment by liquiduk** [comment]
Same exact issue for me on Monterey

**Comment by Imerch** [comment]
Аналогичная проблема!

**Comment by fvrmr** [comment]
Hi @WolfgangDomroese thank you for your bug report.
This is a duplicate of #10249
I will close this issue since it is a duplicate.
