### ISSUE TITLE
Rotation Tool not working

### ISSUE THREAD

**Issue by ericmtg** [Ultimaker/Cura#10702]
### Application Version

4.11.0

### Platform

MAC OS Big Sur 11.2

### Printer

Creality Ender-3

### Reproduction steps

First I imported my OBJ file, Next I tried to select the model by using the left click button on the mouse and it wouldn't select it, After that I was able to select the model from the "Object list" but when I tried to Rotate the model it wouldn't move no matter what I tried. Aside from the fact that I've reinstalled multiple times and also tried installing older versions the problem still persists- I'm not able to Rotate the models. I hope that you are albe to address this issue in the next update. I also have a request; Can you add X,Y,Z input for the Rotation tool like you have for the Scaling???? This would make the Rotation tool easier to user to use - and it is a common feature in other slicer Apps. Just saying!... Peace! 

### Actual results

Like I stated above - The rotation tool in Cura doesn't work at all. 

### Expected results

I would expect that when I have selected the model and the Rotation tool I would be able to rotate the model, but the Rotation tool would allow you to manipulate it instead it dissappears when you click on the manipulators.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

This problems has caused me to seek out other Slicer Apps to use. I hope you can fix this issue sometime... I will try again at a later time.

**Comment by fieldOfView** [comment]
Do you have multiple displays, with different "retina-ness"? If so you might try unchecking the "restore window position on start" option in the General preferences of Cura.

**Comment by ericmtg** [comment]
Thank you for this information - I worked... Hopefully it will continue to work. I do have and extra monitor that I use with my laptop - that must have been what cause Cura to error. I appreciate the help. All the best!

**Comment by fieldOfView** [comment]
Can you close the issue please?
