### ISSUE TITLE
Configuración Kingroon KP3S

### ISSUE THREAD

**Issue by Joaquin1963** [Ultimaker/Cura#10710]
### Application Version

4.12.0

### Platform

Windows 11 pro

### Printer

Kingroon Kp3s

### Reproduction steps

Desinstalar la impresora y volverla a  #instalar.

### Actual results

![image](https://user-images.githubusercontent.com/52271470/139584063-4db0d601-b439-45a0-a5c6-3109fe53895c.png)

### Expected results

Ninguno.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/52271470/139584098-f661cdc2-92e8-4adb-8653-12a4f17ef6be.png)

**Comment by fvrmr** [comment]
Hi @Joaquin1963 thank you for your report.
You can delete your configuration folder: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>`
This will delete all your settings and profiles. 
Or you can only delete the extruder configs 
`C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\extruders\<your extruder files.cfg>`

Let me know if that works.

**Comment by Ghostkeeper** [comment]
Deleting a printer shouldn't cause corrupt configurations though. Perhaps Joaquin had multiple instances of Cura open at the time of removal? That could cause it.

I'm unable to reproduce this bug otherwise, so far.
