### ISSUE TITLE
German translation for estimated time

### ISSUE THREAD

**Issue by fralut** [Ultimaker/Cura#10718]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ultimaker S3

### Reproduction steps

When i select the "monitoring" tab, the estimated time with german language is a mixture of german an englisch

### Actual results

Finishes morgen at 11:08

### Expected results

Fertiggestellt morgen um 11:08

Therefore the word "Finishes" needs to be replaced with "Fertigestellt" and "at" with "um"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![grafik](https://user-images.githubusercontent.com/18448723/139729900-f68e33d9-0235-4d0c-beb1-419430ace00a.png)

**Comment by fvrmr** [comment]
Hi @fralut thank you for your report. 
I will bring this up with the team!

**Comment by Ghostkeeper** [comment]
Good find! This was a small oversight. Fixed now.

**Comment by fralut** [comment]
Unfortunately, the change was not implemented as i recommended. The new translation "auf" instead of "um" is a bad german translation and better would be really my recommendation.

![grafik](https://user-images.githubusercontent.com/18448723/141001635-fa765a62-4b55-4442-9d57-ed8c616fa405.png)

**Comment by fralut** [comment]
Thanks
