### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by UxuginPython** [Ultimaker/Cura#10720]
### Application Version

4.11.0

### Platform

macOS Monterey 12.0.1, iMac (Retina 5K, 27-inch, 2019), 3.6 GHz 8-Core Intel Core i9, 32 GB 2667 MHz DDR4, Radeon Pro 580X 8 GB

### Printer

Ultimaker S5

### Reproduction steps

1. I added 3 STL files to be printed at once
2. I clicked Slice
3. I waited 7 minutes

### Actual results

I got an error message linking me to the bug report page.

### Expected results

It would have completed successfully and taken me to the Preview section.

[cura.log](https://github.com/Ultimaker/Cura/files/7456985/cura.log)
<img width="2560" alt="Screen Shot 2021-11-01 at 7 02 48 PM copy" src="https://user-images.githubusercontent.com/84234447/139770788-84d6f2c7-c655-469f-8268-c11ea966526f.png">
The project file was greyed out when I tried to upload it.

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

Oops, I uploaded the files in the textbox above. I hope that's OK.

**Comment by fvrmr** [comment]
Hi @UxuginPython thank you for your report. 
Could you share your project file as a .zip?
