### ISSUE TITLE
i have a set of .stl which cant be arranged by cura. also the selective settings wont work. i cant have brim activated on some objects and deactivated on others on the same plate.

### ISSUE THREAD

**Issue by yzorgone** [Ultimaker/Cura#10741]
### Application Version

4.12 Beta and version before.

### Platform

Mac OS Monterey

### Printer

UM S5

### Reproduction steps

i have this set of .stl which cant be auto arranged by cura. also the selective print settings wont work. i cant have brim activated on some objects and deactivated on others on the same plate.

all i do is import.. orient and then arrange.. 

[Archiv.zip](https://github.com/Ultimaker/Cura/files/7475502/Archiv.zip)
.

### Actual results

when i try merging the objects after arranging them manualy they snap to a weird state losing all placement and orientation..

### Expected results

objects be grouped/ merged to a single entity so i can apply seperate print settings to small parts of an assembly.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_all.3mf.zip](https://github.com/Ultimaker/Cura/files/7475530/UMS5_all.3mf.zip)

**Comment by Ghostkeeper** [comment]
Seems to be the same as https://github.com/Ultimaker/Cura/issues/10133 ?
