### ISSUE TITLE
Duplicate parts does not work

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10758]
### Application Version

4.11

### Platform

macOS m1

### Printer

CR10/Ender3

### Reproduction steps

Select object, select "Multiply Selected" change the number in the dialog, press ok, and the progress bar shows but does nothing more

### Actual results

Stuck progress bar and no multiplication

### Expected results

Multiplication of items

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

does not need files

**Comment by fieldOfView** [comment]
Duplicate of #10249
