### ISSUE TITLE
Copying components is not possible

### ISSUE THREAD

**Issue by acki138** [Ultimaker/Cura#10755]
### Application Version

4.11.0

### Platform

MacBook Air M1, Monterey 12.0.1

### Printer

Anycubic i3 Mega S

### Reproduction steps

press command+m

### Actual results

There is a requester with the info: "Place objects - duplicate and place objects" and that's it. The objects are not copied and placed

### Expected results

It is not possible to clone (duplicate) components as usual. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Bildschirmfoto 2021-11-06 um 15 41 10](https://user-images.githubusercontent.com/93829225/140613580-484c3afd-dd59-421a-886c-fc1ada1d6908.png)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/10249.
