### ISSUE TITLE
Slicing a lithophane

### ISSUE THREAD

**Issue by AlaskainFlight** [Ultimaker/Cura#10757]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality 5 pro

### Reproduction steps

Loaded a jpg photo and sliced it.

![Loading a JPG photo](https://user-images.githubusercontent.com/93848204/140636338-c487c7b9-3ad7-45fd-aed1-c866809bd3cf.JPG)
![Sent to slicer](https://user-images.githubusercontent.com/93848204/140636411-b29cf3aa-23bb-4c49-985e-b6311d6e1f45.JPG)

### Actual results

The preview shows that Cura omitted the base.

![Preview, missing base layers](https://user-images.githubusercontent.com/93848204/140636422-07b56d7a-b1f2-4c64-b834-fe44832e291d.JPG)

### Expected results

The base, the air gap under the printed photo should have been filled in with multiple layers of filament
![Preview, missing base layers](https://user-images.githubusercontent.com/93848204/140636445-f8112983-0358-4096-91e3-80a384fd81ad.JPG)
.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Buddy 000](https://user-images.githubusercontent.com/93848204/140636471-647c8e18-c736-4881-8fec-2ee29430d320.jpg)
[Buddy 000.zip](https://github.com/Ultimaker/Cura/files/7491892/Buddy.000.zip)

**Comment by AlaskainFlight** [comment]
Resolved. Delayed Intelligence
![Culprit](https://user-images.githubusercontent.com/93848204/140638005-ede9aa36-31c5-45f7-9086-b65152a82588.JPG)
!

**Comment by Ghostkeeper** [comment]
The problem was, as far as I can see, rather with Surface Mode. Setting that to Normal works.
