### ISSUE TITLE
App icon on macOS is too large

### ISSUE THREAD

**Issue by CraigSiemens** [Ultimaker/Cura#10762]
### Application Version

4.11.0

### Platform

macOS

### Printer

n/a

### Reproduction steps

Launch the app on macOS.

### Actual results

The icon size is large than the other icons on macOS.

<img width="423" alt="Screen Shot 2021-11-07 at 2 56 11 PM" src="https://user-images.githubusercontent.com/680442/140663347-683ace60-fbcd-428a-9a1d-62749557dd25.png">

### Expected results

The icon should have similar sizing to the other icons. There are [templates](https://developer.apple.com/design/resources/#macos-apps) available to get the correct sizing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Apple - Human Interface Guidelines - macOS - App Icons](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

**Comment by neofuture** [comment]
Second this is goes against apples ecosystem and human interface guidelines

**Comment by fvrmr** [comment]
Hi @CraigSiemens thank you for your report.
I have discussed it with our UX designer and we have created a ticket on our backlog.
Devs see CURA-8681

**Comment by fvrmr** [comment]
With the new Cura 5.0 release the Cura icon has had an update and is now better aligned on MacOS. So I will close this issue!
