### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by Heagr** [Ultimaker/Cura#10768]
### Application Version

4.11.0

### Platform

windows 10

### Printer

anet a6

### Reproduction steps

trying to print a miniatur
set top layer to 9999999999
Bottom layer to 0
speed 25
100% infille
0.1 profile fine

### Actual results

nothing

### Expected results

get the slicing failed error

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by fvrmr** [comment]
Hi @Heagr thank you for your report.
Could you share a project file? (file - save project)

**Comment by Ghostkeeper** [comment]
Possibly this is a problem because 9999999999 is more than the maximum integer (2^31). Could be looking at an integer overflow here.
