### ISSUE TITLE
Slicer preview is unresponsive and crashes

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10766]
### Application Version

4.11.0

### Platform

macOS M1

### Printer

CR10/Ender3

### Reproduction steps

When clicking to see a prepare on any slice the preview becomes unresponsive and sometimes crashes Cura I have resorted to using ideaMaker as that opens the slices's without issue 

### Actual results

Locks Mac and causes a quit in application

### Expected results

See the slices preview in full sliced glory

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

as always load a model and slice It then see the bug

**Comment by fvrmr** [comment]
Hi @neofuture thank your for your bug report. 
This is a known issue, see https://github.com/Ultimaker/Cura/issues/9542
I will close this issue and mark it as a duplicate.
