### ISSUE TITLE
Moving from Retina to none retina screen results in a half viewer interface

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10764]
### Application Version

4.11.0

### Platform

macOS M1

### Printer

CV10

### Reproduction steps

Move Cura from retina screen to a second monitor

### Actual results

Cant see print bed representation anymore

### Expected results

To see the print bed representation

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

No files needed try on supported hardware to replicate

**Comment by fvrmr** [comment]
Hi @neofuture thank you for your report. 
This is a know issue, see https://github.com/Ultimaker/Cura/issues/9912 
I will close this issue since it is a duplicate.
