### ISSUE TITLE
Printer Settings - "Maximum Feedrate"

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#10767]
### Application Version

4.12beta

### Platform

Win 10

### Printer

Creality E3Pro

### Reproduction steps

N/A

### Actual results

N/A

### Expected results

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Within the Printer Settings are:
Maximum Speed X
Maximum Speed Y
Maximum Speed Z
Maximum Feedrate

Within fdmprinter.def.json is:
"machine_max_feedrate_e":
                {
                    "label": "Maximum Feedrate",
                    "description": "The maximum speed of the filament.",

This can cause some confusion as "Maximum Feedrate" would seem to imply an overall speed limit for everything.  I would suggest a change to "Maximum Speed E" for consistency and to match the tooltip.

**Comment by fvrmr** [comment]
Hi @GregValiant thank you for your report.
I will discuss this with the team. Keep you posted!
