### ISSUE TITLE
Closes when updating account

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10775]
### Application Version

4.12.0

### Platform

Mac

### Printer

Biqu b1 /Tarantola Pro

### Reproduction steps

When I try to synchronize the account to update pulgins and other data, the program closes.

### Actual results

Already uninstalled and re-installed and the problem continues. Appeared since I installed the beta version of 4.12. It is therefore impossible to work with the program without some plugins

### Expected results

I await a resolution as soon as possible

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7506755/cura.log)

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your report. 
I could not find anything in the logs that shows why this is happening. 
What version OS are you using?

**Comment by Z122-JPL** [comment]
@NunoFilipePereira 
Here is the solution to fix this known 'Sign In" problem under Mac OS:
https://github.com/Ultimaker/Cura/issues/10789#issuecomment-968054449

**Comment by NunoFilipePereira** [comment]
> Hi @NunoFilipePereira thank you for your report.
> I could not find anything in the logs that shows why this is happening.
> What version OS are you using?

MacOs Catalina Versão 10.15.7

**Comment by fvrmr** [comment]
@NunoFilipePereira thank you
Could you check the comment @Z122-JPL mentioned if that works for you: https://github.com/Ultimaker/Cura/issues/10789#issuecomment-968054449
