### ISSUE TITLE
Unable to Open File

### ISSUE THREAD

**Issue by Iain-Intracar** [Ultimaker/Cura#10778]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

TronXY X5SA-400

### Reproduction steps

Attempting to open Solidworks files in Cura both via the macro and opening from inside Cura gives an "unable to open file" error message. Files open ok if converted to STL. The error occurs with all SWx files, it's not isolated to one individual file

### Actual results

![image](https://user-images.githubusercontent.com/94019908/141015074-59f0aff3-c269-4268-812b-786a4c110d5a.png)

### Expected results

Model opens in Cura

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7508347/cura.log)

**Comment by nallath** [comment]
Please report issues with plugins with the author of the plugin. You can find more information about the author here: https://marketplace.ultimaker.com/app/cura/plugins/thopiekar/CuraSolidWorksPlugin
