### ISSUE TITLE
Multiplying and Placing Objects

### ISSUE THREAD

**Issue by Strobeump** [Ultimaker/Cura#10783]
### Application Version

4.12.0

### Platform

Mac

### Printer

Ender 3

### Reproduction steps

Opened a file.
Selected the object.
Right clicked Multiply Selected

### Actual results

The "Placing Objects" box appears at the bottom of the screen, but nothing happens, nor will it go away without quitting Cura and re-launching.

### Expected results

It should have multiplied the selected object.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It happens regardless of the STL file I open.

**Comment by nallath** [comment]
Duplicate of #10249
