### ISSUE TITLE
file Close out

### ISSUE THREAD

**Issue by johnbeteta** [Ultimaker/Cura#10781]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Opened Cura, selected file, open file, selected file location like the downloads folder.  It did this in Cura 4.11 as well, I was hoping it would go away with 4.12

### Actual results

The folder opens for about 10 seconds then all of Cura closes.

### Expected results

I should be able to select a file or multiple files and they open in the Cura program running.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None at this time

**Comment by nallath** [comment]
Do you have chitubox installed? If so, check https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file for a solution.
