### ISSUE TITLE
[Improvement] Change UI text size

### ISSUE THREAD

**Issue by luisonoff** [Ultimaker/Cura#108]
In my screen (1920*1080, 23 inches), some of the text displayed is too small, like text displayed inside progress bar.

I would love an option in settings, for example, to scale UI text size, to make it bigger and more easy to read in my case.

**Comment by awhiemstra** [comment]
We currently scale the UI text based on system font size. However, if certain bits of text are too small, we probably need to set a minimum font size. Can you provide screenshots of the things you consider too small?

**Comment by luisonoff** [comment]
Menu text and settings text is small but OK, but look at the progress bar, the save button and top text where you have to choose mode and machine.

![ui_text](https://cloud.githubusercontent.com/assets/10898530/8544353/f0434784-24a4-11e5-8de2-eba81f4a0235.png)

**Comment by TMHogenhout** [comment]
Duplicate. See: https://github.com/Ultimaker/Cura/issues/194#issuecomment-128656307

**Comment by bear454** [comment]
The font size comes from the Qt libraries... you can override by setting an environment variable: `QT_SCALE_FACTOR`

For example, on Linux, I run Cura with the command `QT_SCALE_FACTOR=2 Cura-2.4.0.AppImage`

**Comment by tfischer4765** [comment]
QT_SCALE_FACTOR=2 may be a wee bit much, I'd recommend 1.1 or 1.2
