### ISSUE TITLE
Slide to synchronize account

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10807]
### Application Version

4.12.0

### Platform

Mac

### Printer

Biqu b1 /Tarantola Pro

### Reproduction steps

Hi, can you help me? ultimakercura is always shutting down as soon as you try to sync your account or install pulgins. Without some pulgins it is impossible to work, Can you hel
[cura.log](https://github.com/Ultimaker/Cura/files/7523528/cura.log)
p?

### Actual results

I open the program again, it warns me that I have plugins to install, I load it and everything happens again... turn it off if

### Expected results

I open the program again, it warns me that I have plugins to install, I load it and everything happens again... turn it off if

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7523548/cura.log)

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your report.
This is the same report you've posted 3 days ago.
https://github.com/Ultimaker/Cura/issues/10775

There I asked what version of MacOS you are using? I will close this issue. Since this is a duplicate. But please continue the thread there.
