### ISSUE TITLE
Create Text Area bigger for sending GCode to the Printer

### ISSUE THREAD

**Issue by marius-lu** [Ultimaker/Cura#10802]
### Is your feature request related to a problem?

It would be nice to have a bigger text-area when sending GCode.
So, when you want to send a few lines of GCode or test a few lines of command, it would be nice to have the area bigger. 
This helps you better testing a few lines of code.

### Describe the solution you'd like

In "Monitor" Tab create the text area of "Send G Code" bigger.

### Describe alternatives you've considered

N/A

### Affected users and/or printers

N/A

**Comment by fvrmr** [comment]
Hi @marius-lu thank you for your feature request. 
We don't maintain and update USB printing anymore, since our printers are not using USB. So there is no priority for us to make this bigger. I hope you understand! 
That's why I will close this issue and mark it as won't do.
