### ISSUE TITLE
4.12 Crashes on Model Open

### ISSUE THREAD

**Issue by kpdcompany** [Ultimaker/Cura#10821]
### Application Version

4.12

### Platform

Win10

### Printer

Voron

### Reproduction steps

I can not load a model, just crashes

### Actual results

Crash on model load

### Expected results

Load a model and work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I can not even use it.  Can't even select a file, as soon as you say open and click a folder it crashes

**Comment by nallath** [comment]
Please check https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
