### ISSUE TITLE
Save as 3MF project file doesn't save project with "Modify Settings with Overlap" settings.

### ISSUE THREAD

**Issue by Roboman69** [Ultimaker/Cura#10823]
### Application Version

4.12

### Platform

Windows 10 v21H1

### Printer

Creality CR-10S

### Reproduction steps

![image](https://user-images.githubusercontent.com/94209018/141603593-f64e3935-5344-4b4f-ae62-8fb78105551d.png)

1. Load STL
2. Add support blockers and then select "Per Model Settings" and a bunch of "Modify Settings with Overlap" settings.
3. Save the whole setup as a project file .3mf.
4. Close Cura.
5. Load .3mf file. 
6. Looks ok until you try and select model or support blocker.
7. The "Per Model Settings" is greyed out and the model and support blocker has Black lines boxing everything in.
8. HELP!!!
![image](https://user-images.githubusercontent.com/94209018/141603607-aebb962e-67b2-40c1-8372-b2d1c049c3ca.png)

### Actual results

![image](https://user-images.githubusercontent.com/94209018/141603574-929d5a4c-f307-47d7-8aa2-9ffc7902f35f.png)

### Expected results

I should be able to change settings in the "Per Model Settings" after reloading the .3MF project. But CANNOT!
[CCR1_Mug Test2.zip](https://github.com/Ultimaker/Cura/files/7531307/CCR1_Mug.Test2.zip)
!

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CCR1_Mug Test2.zip](https://github.com/Ultimaker/Cura/files/7531309/CCR1_Mug.Test2.zip)

**Comment by fvrmr** [comment]
Hi @Roboman69 thank you for your report. 
This is fixed in 4.13! 

See also: https://github.com/Ultimaker/Cura/issues/9973

For now if you want to select the model you can press CTRL and then click the object you want to edit. 
I will close this issue since it is a duplicate. But please let me know if you have more questions!
