### ISSUE TITLE
Crashes on LG Gram Laptop

### ISSUE THREAD

**Issue by whirlingsterling** [Ultimaker/Cura#10822]
### Application Version

4.12

### Platform

Windows 10

### Printer

Creality Ender3Max

### Reproduction steps

Launch 4.12 app
Select open folder icom
Select .stl file to open

### Actual results

App crashes

### Expected results

File should load to prepare and slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[2829176_A.zip](https://github.com/Ultimaker/Cura/files/7531253/2829176_A.zip)

**Comment by nallath** [comment]
Please check https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
