### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10833]
### Application Version

4.12.0

### Platform

Mac

### Printer

Tarantula/ Biqu

### Reproduction steps

The latest version cures a lot of problems and it seems they aren't solving any of them. Pulgins terminates the program. Many problems with the generated gcode causes the machine to shut down due to heating. The program is unstable, even adding some manual elements the program takes a long time to generate the gcode and exits. Several tests and then I go back to the old man Simply 3d and everything works although few current resources which makes the curate to be in the main list. But with so many problems, you can't trust…

### Actual results

I test in different ways and the result is always the same

### Expected results

It was interesting to create stability in the program.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Errors and temperature issues are extremely complicated and in this version it happens a lot.

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your request.
Could you share a project file (file - save project)?
