### ISSUE TITLE
Downloads are broken - 404 Not Found for Windows and Linux versions

### ISSUE THREAD

**Issue by gheja** [Ultimaker/Cura#10848]
### Application Version

website

### Platform

website

### Printer

website

### Reproduction steps

The links for Linux and Windows versions lead to a 404 Not Found error on the download page:

https://ultimaker.com/software/ultimaker-cura

### Actual results

404 Not Found

### Expected results

200 OK

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by fvrmr** [comment]
Hi @gheja thank you for your report. 
It is working for me. Does it still shows a 404?

**Comment by gheja** [comment]
All three of them are working now, thank you for the quick fix!
