### ISSUE TITLE
details missing

### ISSUE THREAD

**Issue by RudiCor** [Ultimaker/Cura#10852]
### Application Version

4.12.0

### Platform

mint-linux

### Printer

Creality CR-6 MAX

### Reproduction steps

Loaded model shows fine in prepare mode. However, in preview and also printed model there are some elements missing.

![preview](https://user-images.githubusercontent.com/94514428/142147145-a0b873ed-a645-4c70-a260-86917def9162.png)
![prepare](https://user-images.githubusercontent.com/94514428/142147147-5d2ef70b-8e2e-4317-8917-dfb6a6216342.png)

### Actual results

Letters are not there

### Expected results

see letters

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CCR6MAX-Problem.3mf.zip](https://github.com/Ultimaker/Cura/files/7552356/CCR6MAX-Problem.3mf.zip)

**Comment by fieldOfView** [comment]
You have the setting "Remove all holes" enabled (under Mesh Fixes), which... removes all holes.
