### ISSUE TITLE
VersionUpgrade does not ensure unique container names

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#1085]
In Cura 2.1 it was possible to have a profile with the same name as a printer. Eg if the user names his UM2 "Ultimaker 2" (the default choice), he can create a quality profile named "Ultimaker 2" as well.

When upgrading Cura to 2.3, the VersionUpgrade plugin blindly creates a ContainerStack with the id "Ultimaker 2" and a InstanceContainer with the id "Ultimaker 2". This leads to an error where either the InstanceContainer is found as a ContainerStack, or in a more positive case an error that a container with the id "Ultimaker 2" already exists. In either case, Cura does not start.

Note that when trying to create a profile named "Ultimaker 2"  in Cura 2.3, it is correctly renamed "Ultimaker 2 #2".

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by Ghostkeeper** [comment]
Yes, and this causes Cura to brick itself. The version upgrade system upgrades file-by-file without looking at whether a file already exists.

**Comment by Vandrasc** [comment]
I think we fixed this, @Ghostkeeper can you confirm (again) that it's still an issue? ^^

**Comment by Ghostkeeper** [comment]
Yes, it's still an issue. Renames occurred in the upgrade from 2.7 to 3.0. Also, if we ever want to rename a file again in a future version upgrade then this will again occur.
