### ISSUE TITLE
Bridge layer is taken as a layer 1 and it turns off fans

### ISSUE THREAD

**Issue by canadank0** [Ultimaker/Cura#10862]
### Application Version

4.12

### Platform

Windows 11

### Printer

Voron 2.4

### Reproduction steps

I have print object with hole in the center, so the layer 85 is closing the hole, but this layer that is as a first layer covering the empty area is taken as a first layer and it turns off the cooling filament fan, which i don't need for the bridge areas. i think that is bug.

![image](https://user-images.githubusercontent.com/30533921/142233907-67b1d138-2edc-4893-93dd-5f10a0059c86.png)

### Actual results

the result is melted filament that is doing uneven surface

### Expected results

clean straight bridge

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

...

**Comment by fvrmr** [comment]
Hi @canadank0 thank you for your report.
Could you share also your project file (file - save project)
Then I can check what is going on.
