### ISSUE TITLE
Cura drops Z-offset 0.1mm with each sequential print in "one at a time" mode

### ISSUE THREAD

**Issue by Patrick5693** [Ultimaker/Cura#10866]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Ender 3 (4.2.7 silent board)

### Reproduction steps

Every time I try to print multiple prints in the "one at a time" mode in cura my printer will drop the height by 0.1mm. 

### Actual results

The first print always turns out flawless but the second print will be 0.1mm lower than the 1st, and then the 3rd will be 0.2mm lower than the 1st and usually results in the nozzle scrapping the bed.

### Expected results

The prints should be replicated in the exact same quality as the previous model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don't have a picture of the issue due to have to scrap the PEI sheet after the nozzle ate off the finish. But the 1st print looks flawless, the 2nd looks almost the same except the skirt and 1st layer are almost transparent from the nozzle being closer to the bed, the 3rd print is when the nozzle will actually dig into the bed and eat off the finish

**Comment by GregValiant** [comment]
Zip one of your gcode files and post it.  When you print "one at a time" there is a "layer:0" for each part and the starting Z should be the same for all of them.
