### ISSUE TITLE
Cura does not see material installed

### ISSUE THREAD

**Issue by YvesChalifour** [Ultimaker/Cura#10867]
### Application Version

4.12

### Platform

Windos 10

### Printer

UMS3

### Reproduction steps

Printer UMS3
UMS3 did not recognize Ultrafuse PAHT CF15 material

Details in attached document

### Actual results

Details in attached document

### Expected results

Details in attached document

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Ultrafuse PAHT CF15 Bug Report.pdf](https://github.com/Ultimaker/Cura/files/7559082/Ultrafuse.PAHT.CF15.Bug.Report.pdf)

**Comment by fvrmr** [comment]
Hi @YvesChalifour thank you for your report. 
Sometimes the synchronization with materials doesn't work indeed correctly.
Good to know you've found the way to do this manually. But here you can find more information about how to troubleshoot these kind of issues: https://support.ultimaker.com/hc/en-us/articles/360016857859-How-to-troubleshoot-issues-with-material-printer-synchronization- 

I will close this issue, but let me know if you have more questions.
