### ISSUE TITLE
ULTIMAKER CURA 12 NO FUNCIONA

### ISSUE THREAD

**Issue by cinthialm95** [Ultimaker/Cura#10868]
### Is your feature request related to a problem?

Hola estoy utilizando ultimaker cura y de repente dejó de funcionar... cuando le doy a segmentar se queda bloqueado y no responde.

### Describe the solution you'd like

Me podéis ayudar?

### Describe alternatives you've considered

A alguien le paso lo mismo que a mi? Como puedo solucionarlo?

### Affected users and/or printers

Creo que este problema afecta a más gente.

**Comment by fieldOfView** [comment]
Please use english here. If you cannot use english, please go to the spanish subforum of the Ultimaker community forum instead. Perhaps someone there will be able to help you:
https://community.ultimaker.com/forum/125-espa%C3%B1ol/

**Comment by fvrmr** [comment]
Hi @cinthialm95 thank you for your report.
Google translate tells me Cura stopped working. So if that is the case this is not a feature request. 
Please let us know in English what your problem is and share your log file: https://github.com/Ultimaker/Cura#logging-issues
