### ISSUE TITLE
Top surface using issues

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10873]
### Application Version

4.12.99 - Monterey Fix

### Platform

macOS M1 Montery beta 12 

### Printer

Ender 3 v2

### Reproduction steps

Printing any thing results in a poor top layer

### Actual results

Top layer seems to use concentric only, no matter what settings I change the quality of the top is no different

### Expected results

Better surface performance

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

<img width="669" alt="Screenshot 2021-11-18 at 13 17 59" src="https://user-images.githubusercontent.com/11268634/142422724-23e5785f-847d-4fff-9e67-98560230c4bc.png">
[CE3_V1.01_Chassis_Plate(RPi).3mf.zip](https://github.com/Ultimaker/Cura/files/7563040/CE3_V1.01_Chassis_Plate.RPi.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7563043/cura.log)

**Comment by fvrmr** [comment]
Hi @neofuture thank you for your report. 
We don't maintain the quality profiles for your printer. Since we can't test these, we only test Ultimaker printers. 
These profiles were contributed to us by the community. 

If you use the default Super quality for an Ender you will get lines as Top/Bottom pattern. 
Looking from the preview I can't really see if there is a bug in here.

**Comment by neofuture** [comment]
OK previous to this version on version 4.11 the top/bottom surface was much better than this, I will roll back to that version and test again after this print is finished, I have not changed the profile, but the top surface seems to change if you remove the raft

**Comment by neofuture** [comment]
<img width="1792" alt="Screenshot 2021-11-18 at 17 03 18" src="https://user-images.githubusercontent.com/11268634/142462168-21113b80-c8d5-4f56-be3f-2bfc6da94d9c.png">

The above is with 4.12

<img width="1792" alt="Screenshot 2021-11-18 at 17 04 02" src="https://user-images.githubusercontent.com/11268634/142462275-f87d236c-ea0a-4032-8a93-7c84e99f636e.png">

Above is 4.11 

Both using exactly the same profile

**Comment by neofuture** [comment]
<img width="1792" alt="Screenshot 2021-11-18 at 17 13 07" src="https://user-images.githubusercontent.com/11268634/142463788-bbc70678-ba4d-4db1-8a52-f605b45498c6.png">

And this is 4.11 with the raft off and skirt on

**Comment by neofuture** [comment]
Ok some how the profile had got something wrong with it I have removed the ender 3 profile and re added it and now its working, please feel free to close this if you think its just an issue on my end

**Comment by fvrmr** [comment]
Thank you for your update! I will close this issue now since it is solved for you :)
