### ISSUE TITLE
Multiply objects does not work

### ISSUE THREAD

**Issue by Callewaert3D** [Ultimaker/Cura#10875]
### Application Version

4.12.0

### Platform

macOS Monterey

### Printer

UltimakerS5

### Reproduction steps

I choose an object on the build plate

### Actual results

"Placing objects" window opens with progress barr "multiplying an placenta objects"

### Expected results

Object should be multiplied on the build plate

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="955" alt="Schermafbeelding 2021-11-18 om 16 00 00" src="https://user-images.githubusercontent.com/94625194/142440220-05cb2e28-27d7-4300-95fd-2af9e14d8eb8.png">

**Comment by fieldOfView** [comment]
Especially for you, Cura 4.12.1 was released 10 minutes before you posted your issue:
https://github.com/Ultimaker/Cura/releases/tag/4.12.1

**Comment by Callewaert3D** [comment]
Works perfect now! 

Thanks,

P

**Comment by fvrmr** [comment]
Closing this issue since it is solved!
See also https://github.com/Ultimaker/Cura/issues/10249
