### ISSUE TITLE
1.st layer support omission

### ISSUE THREAD

**Issue by RudiCor** [Ultimaker/Cura#10874]
### Application Version

4.12.0

### Platform

mint-linux

### Printer

creality CR6-MAX

### Reproduction steps

Loaded and sliced model as usual

### Actual results

region of 1.st layer without support (cross lines)

### Expected results

all support areas of 1.st layer with cross-li
![1st_layer](https://user-images.githubusercontent.com/94514428/142423672-6f55a100-a750-4537-afc9-76bae94f8ca5.png)
ne

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CCR6MAX_1st_layer.3mf.zip](https://github.com/Ultimaker/Cura/files/7563102/CCR6MAX_1st_layer.3mf.zip)

**Comment by fvrmr** [comment]
Hi @RudiCor thank you for your report.
Did you use the official AppImage of Cura?
For me the support is showing up correctly. But you project file is not sharing your settings and printer. So I could not reproduce it the right way.

**Comment by Ghostkeeper** [comment]
That's not a project file. That's a plain 3MF file. A project file can be created by going to File -> Save Project...

**Comment by RudiCor** [comment]
Hello,

I changed some parameters and can not reproduce the setup that produced 
the issue any more. Now it works fine.
Sorry for disturbing you!

Corneliu

Am 2021-11-25 15:12, schrieb Ghostkeeper:
