### ISSUE TITLE
Raft not lifting model

### ISSUE THREAD

**Issue by RedDirt3D** [Ultimaker/Cura#10887]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

Ender 5 Plus

### Reproduction steps

I imported a model, selected raft for adhesion layer, and sliced the model.

### Actual results

The model wasn't lifted onto the raft. Instead, the sliced file shows the model losing the bottom 4 layers to the raft.
![Screenshot 2021-11-17 061904](https://user-images.githubusercontent.com/61371617/142714150-c3ddb876-2f4f-4ef3-9599-4eac66a44f45.png)

### Expected results

The model should lift up the 4 layers of the raft and sit on top of the raft.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional information.

**Comment by fvrmr** [comment]
Hi @RedDirt3D thank you for your report.
The model is lifted on the raft. Only it does not move the shadow of the model. 
This cube has 100 layers:
![Screenshot (302)](https://user-images.githubusercontent.com/77000924/142841108-41701965-db08-45c6-860b-5d32b7fcacdb.png)

And with raft it shows 104 layers:
![Screenshot (303)](https://user-images.githubusercontent.com/77000924/142841235-5be06279-fdae-45fb-b9c9-8e1e52fd5393.png)

Let me know if that is also the case for you!
