### ISSUE TITLE
crash saving gcode after slicing

### ISSUE THREAD

**Issue by tyeth** [Ultimaker/Cura#10896]
### Application Version

4.12.0 - Released 09-11-21

### Platform

Windows 11

### Printer

Custom FFF Printer (10year old mendel)

### Reproduction steps

Load project, slice, save gcode.

### Actual results

Saving gcode causes crash related to Y-max or something

### Expected results

saves already safely generated gcode

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[stderr_and_cura_logs.zip](https://github.com/Ultimaker/Cura/files/7576645/stderr_and_cura_logs.zip)
[CFFFP_front_wheel.zip](https://github.com/Ultimaker/Cura/files/7576647/CFFFP_front_wheel.zip)

**Comment by nallath** [comment]
This is an issue caused by the snapmaker plugin. Please contact the author of the plugin. If you don't want / need it, you can always disable or uninstall it.
