### ISSUE TITLE
Temperature set by the initial g-code

### ISSUE THREAD

**Issue by WCrozera** [Ultimaker/Cura#10890]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

JGAurora Magic

### Reproduction steps

I entered the temperatures to heat the table and the nozzle directly into the g-code, below. But after slicing the curate puts his dice first, duplicating the dice. Would it be possible to disable the data generated by the cura? Thanks

### Actual results

But after slicing the curate puts his dice first, duplicating the dice

### Expected results

I entered the temperatures to heat the table and the nozzle directly into the g-code, below. But after slicing the curate puts his dice first, duplicating the dice. Would it be possible to disable the data generated by the cura? Thanks

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

; -- START GCODE --
G21                     ;set units to millimetres
G90                     ;set to absolute positioning
M106 S0                 ;set fan speed to zero (turned off)
G28                     ;home all axis
M420 S1                 ;turn on mesh bed levelling if enabled in firmware
G92 E0                  ;zero the extruded length
G1 Z1 F1000             ;move up slightly
G1 X60.0 Z0 E9.0 F1000.0;intro line
G1 X70.0 E21.5 F1000.0 ;continue line
M140 S{print_bed_temperature}
M104 S{print_temperature} TO
M190 S{print_bed_temperature}
M109 S{print_temperature} TO
M105
G92 E0                  ;zero the extruded length again
; -- end of START GCODE --

**Comment by GregValiant** [comment]
Wrong keywords.  Cura doesn't understand them and so puts it's own temperature lines in just in case.
material_print_temperature_layer_0
material_bed_temperature_layer_0
All the keywords are [HERE](http://files.fieldofview.com/cura/Replacement_Patterns.html).
