### ISSUE TITLE
Cura not slicing model properly

### ISSUE THREAD

**Issue by kayleb27** [Ultimaker/Cura#10897]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

creality ender 3

### Reproduction steps

I used Cura to slice a wing I was making for an airplane it already had support in it so i only put support on to make sure any over hangs would be okay bit it made it completely hollow without anything on the inside even though in the prep section it showed everything like it should but the software seemed to just say it was only going to print certain parts that it chose and I'm not sure why it wont even attempt to print certain parts or details 

### Actual results

i use 3d builder to view so i tried skipping that step incase it modified it did not work so then i put 0 infill tried different orientations didnt work but the files are good it comes with just gcode as well but it tells my printer to go very fast when it needs to be slow precise on the inside supports so im not sure why it is covering up all of the holes i tried with support and without same thing on both

### Expected results

so as you may be able to see in the pictures i provided that when its preparing it shows the hole through the middle for wires as well as some of the internal support but when sliced it puts a top and bottom on and makes it hollow on the inside and doesn't put a hole trough it![Screenshot (4)](https://user-images.githubusercontent.com/94799336/142772896-3d1e8c11-8ac4-48a9-ab76-a4cbe5026eb7.png)
![Screenshot (5)](https://user-images.githubusercontent.com/94799336/142772897-0fedb6ec-13ff-499d-9562-25a49a371a6d.png)
![Screenshot (6)](https://user-images.githubusercontent.com/94799336/142772898-2724316a-4bfd-43af-a555-2c1c4f2170ce.png)
![Screenshot (7)](https://user-images.githubusercontent.com/94799336/142772899-c17046d9-31d8-4713-a94a-fef2f18fdccf.png)
![Screenshot (8)](https://user-images.githubusercontent.com/94799336/142773130-9e71622b-2092-449a-ac35-e2ad1149507c.png)
![Screenshot (9)](https://user-images.githubusercontent.com/94799336/142773132-793f5613-5e2b-4305-a731-5e0cad9f049a.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

if anymore info is needed please email me at kaylebbeam27@gmail.com

**Comment by TheSkittle** [comment]
Can you please upload the project file? I can take a look at it and see why its not working. To be clear, that giant hole going up and down being covered up is the issue right?

**Comment by fvrmr** [comment]
Hi @kayleb27 thank you for your report.
Like @TheSkittle mentioned a project file (file - save project) would be very helpful.
Also it could be the case that the missing pieces are to thin to print. You can check our Arachne release: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta here we use variable line widths.

**Comment by TheSkittle** [comment]
@fvrmr I've been hearing a lot about that thing. What is it? And what new features it have?

**Comment by fvrmr** [comment]
@TheSkittle Arachne is a new engine that to fill available space better with walls, preventing gaps and improve paths by implementing variable line widths. This could help with printing thin walls like this model. 
You can download the beta here: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta and we are currently working on improving this beta and will release a new build soon!

**Comment by TheSkittle** [comment]
@fvrmr sounds cool. Also, when I print certain models, when the overhang becomes greater and greater gradually, it prints fine, but when the walls go inward gradually, the walls look like theres underextrusian , which is wierd because it only happens when the walls go inward,  not outwards, and I already have the flow rate on 150 percent
