### ISSUE TITLE
Cura Failed to slice model

### ISSUE THREAD

**Issue by Joel2243** [Ultimaker/Cura#10895]
### Application Version

4.11

### Platform

WIndows 10

### Printer

Fokoos Odin odin-5 F3

### Reproduction steps

I am trying to slice "Grabtoy" from thingiverse.
https://www.thingiverse.com/thing:2768626

### Actual results

Cura gives an error saying "Slicing failed due to an unexpected error"

### Expected results

the model should properly slice and be ready to send to my 3d printer

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![Screenshot (4)](https://user-images.githubusercontent.com/94795174/142770844-cac71a1f-679d-4c0d-87f9-edd1356fad04.png)
[log files.zip](https://github.com/Ultimaker/Cura/files/7576644/log.files.zip)

**Comment by fvrmr** [comment]
Hi @Joel2243 thank you for your report.
Could you also share your project file? (file - save project)
Thank you!
