### ISSUE TITLE
No retraction / z hop during solid infill printing

### ISSUE THREAD

**Issue by Matszwe02** [Ultimaker/Cura#10906]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Import any model
the travel lines inside solid infill aren't retracted neither z-hopped, which harms the external surface look

### Actual results

[![1.png](https://i.postimg.cc/x1f3Tp9T/1.png)](https://postimg.cc/PP7wS4LB)

### Expected results

Cura should avoid scrubbing the solid infill with a nozzle, because it leaves clearly visible lines

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by fvrmr** [comment]
Hi @Matszwe02 thank you for your report. 
The z hop is not visible in the preview mode. If you export your gcode and then import that gcode in Cura it should show the z hops in the preview animation.
Let me know if that works for you and if not could you share a project file?

**Comment by Matszwe02** [comment]
> Hi @Matszwe02 thank you for your report. The z hop is not visible in the preview mode. If you export your gcode and then import that gcode in Cura it should show the z hops in the preview animation. Let me know if that works for you and if not could you share a project file?

[![image.png](https://i.postimg.cc/prNnvfjQ/image.png)](https://postimg.cc/MMDGbjdX)
[![20211123-165415.jpg](https://i.postimg.cc/q7SNcs1f/20211123-165415.jpg)](https://postimg.cc/hJ84cdFM)
[![20211123-165509.jpg](https://i.postimg.cc/QdNKjxFz/20211123-165509.jpg)](https://postimg.cc/xc71RQyG)

As you can see, when I view the gcode, some travel moves are with retraction and z raise, but these aren't.
I posted the print images, which have lines visible both on top and bottom. That means that it wasn't raised neither retracted.
It happens on every model, for example: https://www.thingiverse.com/thing:2332471

**Comment by Matszwe02** [comment]
During the print I can even see that between printing perimeters it moves over the print bed leaving a line, so it is underextruding for the first mm of printing the next perimeter or infill (due to lack of nozzle pressure)

**Comment by smartavionics** [comment]
Looks like you don't have combing enabled with the "no skin" combing setting?

**Comment by Matszwe02** [comment]
> Looks like you don't have combing enabled with the "no skin" combing setting?

I tester with all combing modes

**Comment by Ghostkeeper** [comment]
If the combing mode is set to "Not in skin", then it's expected to move through the walls. If it's not necessary to cross any walls it can comb, and stay within the model. It doesn't feel the need to retract for those moves because oozing is not visible from the outside.

Of course, oozing indeed still does reduce the pressure in the nozzle chamber. If retractions/z hops are preferred, I suggest you disable combing. It should then decide to retract. Alternatively, you could set a Max Comb Distance With No Retract to retract only for longer moves and still make the combing movements. Make sure that the maximum retraction count is high enough, though, either way.

Let us know if this helps. If not, please provide a project file using File -> Save Project. This file also contains the configuration you're using in your printer, your current settings and profiles. That way we can reproduce the print exactly.

**Comment by Matszwe02** [comment]
> If the combing mode is set to "Not in skin", then it's expected to move through the walls. If it's not necessary to cross any walls it can comb, and stay within the model. It doesn't feel the need to retract for those moves because oozing is not visible from the outside.
> 
> Of course, oozing indeed still does reduce the pressure in the nozzle chamber. If retractions/z hops are preferred, I suggest you disable combing. It should then decide to retract. Alternatively, you could set a Max Comb Distance With No Retract to retract only for longer moves and still make the combing movements. Make sure that the maximum retraction count is high enough, though, either way.
> 
> Let us know if this helps. If not, please provide a project file using File -> Save Project. This file also contains the configuration you're using in your printer, your current settings and profiles. That way we can reproduce the print exactly.

Oozing is still visible in the bottom surface (see pictures), but the lack of z hop also affects the top layer, so the nozzle remelts its path through the print. I'll check if your suggested solution works. Thanks for help for now.

**Comment by Matszwe02** [comment]
I tested it and without combing it doesn't show any artifacts. But anyway you can consider making the setting that the first and the last layers are without combing (+ retraction) so the surface looks as good as possible. The issue is very visible when I need to print many small holes, but everytime printer jumps from one to another, it loses a bit of filament and doesn't print the entire hole due to lack of pressure.

**Comment by Ghostkeeper** [comment]
> But anyway you can consider making the setting that the first and the last layers are without combing (+ retraction) so the surface looks as good as possible.

Indeed, in Cura 4.12 we added the "Not in outer skin" option for combing that does precisely that.
