### ISSUE TITLE
Add thumbnail to 3MF output format

### ISSUE THREAD

**Issue by pedrolamas** [Ultimaker/Cura#10913]
### Is your feature request related to a problem?

3MF format supports including a thumbnail, so it would be great if the files created by Cura would include that thumbnail that can be easily read in Windows file explorer (and possibly other OS) 

### Describe the solution you'd like

Add a thumbnail of the model to the 3MF output file

### Describe alternatives you've considered

Adding the GCode postprocessing script to add thumbnails, however those are not visible in Windows file explorer, only on specific files.

### Affected users and/or printers

Every Windows user will benefit from this (and possibly other users too)

**Comment by fvrmr** [comment]
Hi @pedrolamas thank you for your feature request.
I have discussed it with the team and we decided to create a ticket for this on our backlog.
Devs see CURA-8723

**Comment by pedrolamas** [comment]
Hi @fvrmr, Sorry if that is not the correct process but I just went ahead and created this as a Feature Request (FR) type of ticket without discussing it with anyone before.

**Comment by fvrmr** [comment]
It is the right way to request a new feature for Cura. I brought it up with the Cura team and based on your request we have now a ticket on our backlog for this :)

**Comment by nallath** [comment]
I'm personally a big fan of this feature! It shouldn't be too hard to implement since we already have a system that can create these thumbnails.

**Comment by fieldOfView** [comment]
See #10971.
