### ISSUE TITLE
Errors and more errors

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10912]
### Application Version

4.12.1

### Platform

Mac

### Printer

Bíqu b1/ tarantola

### Reproduction steps

Errors and more errors
![Captura de ecrã 2021-11-23, às 15 57 50](https://user-images.githubusercontent.com/23368014/143058829-36fe5736-20b1-4238-aba5-5480283e9845.png)

### Actual results

Errors and more errors

### Expected results

Errors and more errors
[cura.log](https://github.com/Ultimaker/Cura/files/7589390/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7589395/cura.log
![Captura de ecrã 2021-11-23, às 15 57 50](https://user-images.githubusercontent.com/23368014/143059137-c8ea698e-ac28-41aa-8bdf-b34bdb2d3275.png)
![Foto_Cura](https://user-images.githubusercontent.com/23368014/143059487-78badf69-43b1-405b-990e-69ecd30e1e47.jpg)
[cura.log](https://github.com/Ultimaker/Cura/files/7589421/cura.log)
)

**Comment by GregValiant** [comment]
867 errors by Washington Nationals in 1886 (in 122 games).
1. Herman Long with 122 in 1889
1. Billy Shindle with122 in 1890

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your report.
In your object list you have custom support added. Could you delete those? 
Also could you share your project file (file - save project)?
