### ISSUE TITLE
Slicing fails depending on quantity of parts.

### ISSUE THREAD

**Issue by cbletcher** [Ultimaker/Cura#10919]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Changing the quantity of parts causes the slicer to hang.
1) Position one instance of each part on the build plate. Try slicing. It works.
2) Add one more instance of each part.  Try slicing. The box in the bottom corner says "Slicing..." but it hangs forever and the progress bar never appears.

### Actual results

Changing the quantity of parts causes the slicer to hang. There are other combinations of quantities that will or won't slice.

### Expected results

Slicer would be expected to complete the slicing process. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![slices successfully](https://user-images.githubusercontent.com/72990891/143278856-1da56908-8a49-4fb0-b3e0-96db606165ee.png)
![will not slice](https://user-images.githubusercontent.com/72990891/143278862-267e2827-9cf6-4b39-922f-f8a9fcd296a8.png
I can't upload the STL's or the 3mf's if they're needed, I can provide them. They're big.

**Comment by GregValiant** [comment]
You need to zip the files to upload them.  A project file and your Cura.log file would be good.
