### ISSUE TITLE
Bub

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10911]
### Application Version

4.12.1

### Platform

Mac

### Printer

Biqu b1 / Tarantola 

### Reproduction steps

When I try to sync the account to update the program it shuts down. already checked the log on mac and nothing strange. I have the Mac updated as well as the latest version of cura. This started to happen since I updated the beta version of cura 11. I never had stability of the program on the mac computer again.

### Actual results

When I try to sync the account to update the program it shuts down. already checked the log on mac and nothing strange. I have the Mac updated as well as the latest version of cura. This started to happen since I updated the beta version of cura 11. I never had stability of the program on the mac computer again.

### Expected results

When I try to sync the account to update the program it shuts down. already checked the log on mac and nothing strange. I have the Mac updated as well as the latest version of cura. This started to happen since I updated the beta version of cura 11. I never had stability of the program on the mac computer agai
[cura.log](https://github.com/Ultimaker/Cura/files/7589185/cura.log)
n.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

When I try to sync the account to update the program it shuts down. already checked the log on mac and nothing strange. I have the Mac updated as well as the latest version of cura. This started to happen since I updated the beta version of cura 11. I never had stability of the program on the mac computer again.

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your report.
This is the same report as https://github.com/Ultimaker/Cura/issues/10775 I asked you there to check if this: https://github.com/Ultimaker/Cura/issues/10789#issuecomment-968054449 fixes the problem. Could you give me an update in the other issue?
I will close this issue since it is a duplicate.
