### ISSUE TITLE
Preview mode- no Speed color scheme, only Line type

### ISSUE THREAD

**Issue by djordjedr** [Ultimaker/Cura#10926]
### Application Version

4.11.10

### Platform

Linux Ubuntu

### Printer

Creality Ender 3

### Reproduction steps

1. Slice your model
2. Go to preview 
3. Select Color Scheme-layer lines
 

### Actual results

Note that user cant switch from Color scheme-line type

### Expected results

Multiple options should be possible for Color scheme 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot from 2021-11-25 20-34-35](https://user-images.githubusercontent.com/68948897/143493432-7d348f24-4680-4410-bda2-d85b9d1de7e0.png)

**Comment by fieldOfView** [comment]
Your preview is in "compatibility mode" because either your GPU or the driver you use does not support OpenGL 4.1, which is required for the full featured layer view.

**Comment by fvrmr** [comment]
Hi @djordjedr thank you for your report.
Like @fieldOfView mentioned this is because you are in compatibility mode. 
I will close this issue, since this is something we won't fix.

**Comment by fvrmr** [comment]
Also if in the preferences the `Force layer view compatibility mode` is enabled you could also disable this. But if it is disabled and you still have compatibility mode this is related to your GPU or driver not supporting OpenGL 4.1

**Comment by djordjedr** [comment]
Thank you for clearing up this misunderstanding in such a short notice and
sorry for taking up your time

уто, 30. нов 2021. 11.09 Fenne ***@***.***> је написао/ла:
