### ISSUE TITLE
Prioritize outside over inside wall thickness

### ISSUE THREAD

**Issue by kb-elmo** [Ultimaker/Cura#10923]
### Is your feature request related to a problem?

When printing parts that have thin outside walls (~2mm thickness) with a wall thickness setting of 1.2mm (3 lines at 0.4mm nozzle diameter) the first extrusion of the inside and outside walls will overlap. Right now Cura prioritizes the inside wall thickness, sacrificing one of the extrusions for the outside wall.

Unfortunately this leads to the outside wall often being "squished" out due to not having enough room for expansion to the inside.
Since the outside walls are far more important for dimensional accuracy than the inside it would be better to prioritize the wall line count of the outside walls and instead sacrifice one of the extrusions of the inside wall.

The Slic3r engine already does it like this and creates far better looking results with it.

Example of the issue being visible in prints

Part sliced with Cura:
[![cura_image](https://i.imgur.com/DROQDIYl.jpg)](https://i.imgur.com/DROQDIY.jpg)
The visible line is a layer that got squished out. It's the first layer of a 2mm thick wall, below that the part had infill on the inside.

Same part sliced with SuperSlicer (Slic3r engine):
[![superslicer_image](https://i.imgur.com/Ck8tG2bl.jpg)](https://i.imgur.com/Ck8tG2b.jpg)
Same part, same settings (1.2mm outside wall thickness) but no squished layer visible.

### Describe the solution you'd like

Prioritize the wall thickness of the outside wall to allow for internal expansion of the wall extrusions
Sacrifice internal wall thickness if necessary (reduce the line count dynamically for only the inside wall).

This would prevent the outside wall from being pushed out by the inside wall, increasing outside dimensional accuracy of the part and improving the surface finish.

A solution similar to the way how the Slic3r engine (PrusaSlicer/SuperSlicer) solves this would be ideal.

Cura:
[![cura_image](https://i.imgur.com/RjUB1nql.png)](https://i.imgur.com/RjUB1nq.png)
The inside wall is already printed with three extrusion lines when the outside wall printing starts, leaving zero room for internal expansion.

SuperSlicer (Slic3r engine):
[![superslicer_image](https://i.imgur.com/0wUmBkzl.png)](https://i.imgur.com/0wUmBkz.png)
The inside wall is only printed with two extrusion lines, then the outside wall is printed. The sacrificed third inside wall extrusion is replaced with a gap fill.

### Describe alternatives you've considered

Decreasing the wall line count would work but it would weaken the entire rest of the part which is not an ideal solution at all, especially for larger parts that have solid sections printed with infill.

### Affected users and/or printers

Not machine specific, slicer related issue.

### Additional information & file uploads

Example Gcodes of both SuperSlicer and Cura
[wall_test.zip](https://github.com/Ultimaker/Cura/files/7602019/wall_test.zip)

**Comment by fvrmr** [comment]
Hi @kb-elmo thank you for your request.
We have a setting `Outer before inner walls` also our new Arachne engine would help since it is using variable line width. 
Read here more about the Arachne release: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta_2

Let me know what you think!
