### ISSUE TITLE
Brim preview doesn't work

### ISSUE THREAD

**Issue by Wilbarose** [Ultimaker/Cura#10938]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

Adding a brim to model doesn't change the preview, the brim doesn't show, but it does get added to the G-Code

### Actual results

no brim

### Expected results

a brim should be visible in the layer preview

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no need

**Comment by fvrmr** [comment]
Hi @Wilbarose thank you for your report.
Probably in the preview the helpers are disabled.

![Screenshot (309)](https://user-images.githubusercontent.com/77000924/143849159-98aa7eb3-2f42-403a-a5b1-5452bea847db.png)

Let me know if that is the case for you!
