### ISSUE TITLE
Using tab to cycle to next text box in Per Model Settings not functional

### ISSUE THREAD

**Issue by Festivejelly** [Ultimaker/Cura#10967]
### Application Version

4.11

### Platform

Windows 10

### Printer

CR10

### Reproduction steps

Add a model to Cura,

Then click per model settings
Select parameters to change (such as walls)
Press tab to cycle to next text box

### Actual results

When pressing tab in a text box it does not cycle to the next text box

### Expected results

When pressing tab it should cycle to the next text box for you to enter a value. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is an accessibility issue as a lot of people prefer to navigate applications using a keyboard instead of having to click with the mouse. Ive noticed this issue in several versions of Cura.

**Comment by fvrmr** [comment]
Hi @Festivejelly thank you for your report.
I discussed it with my colleagues and we decided to create a ticket for this. I marked it as a new feature so I will change this in to a feature request.
Developers see CURA-8728

**Comment by nallath** [comment]
This has been added to the next release. Should be in Cura 5.5
