### ISSUE TITLE
Minimized Custom Print Settings

### ISSUE THREAD

**Issue by luke-higgins** [Ultimaker/Cura#10961]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Sovol SV01

### Reproduction steps

1. Minimized the custom print settings menu
2. It will not allow me to make it larger again 

### Actual results

The print menu stay minimized even when trying to enlarge. 

### Expected results

Menu should expand downward. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by fvrmr** [comment]
Hi @luke-higgins thank you for your report.
Do you have an external monitor? And does this happen every time in Cura?
