### ISSUE TITLE
when printing the wipe line is reversing the filament

### ISSUE THREAD

**Issue by crispinchurch** [Ultimaker/Cura#10975]
### Application Version

4.12.1

### Platform

win 10

### Printer

geetech a10t

### Reproduction steps

open stl file and sliced 
save on card

### Actual results

when printing the wipe line is reversing the filament

### Expected results

extrude filament wipe line

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[GA_1coffee machine drip tray 1.zip](https://github.com/Ultimaker/Cura/files/7628186/GA_1coffee.machine.drip.tray.1.zip)

**Comment by GregValiant** [comment]
Are you referring to a retraction?
I sliced the file you provided with no changes and there is only 1 retraction in the gcode file and it was at the end of the skirt.
