### ISSUE TITLE
Cura Arachne Beta not slicing with VORON machine profiles

### ISSUE THREAD

**Issue by exec79** [Ultimaker/Cura#10983]
### Application Version

arachne_beta

### Platform

Windows 10

### Printer

VORON300

### Reproduction steps

offline printer setup, chosing VORON 300 machine profile, other voron profiles results same.
Default slicing settings, nothing changed. 

### Actual results

stuck at slicing
![image](https://user-images.githubusercontent.com/20884744/144325879-5ec77792-313a-4b1d-941a-93767ba8453b.png)

### Expected results

sliced model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

by making a Custom FFF profile, slicing works!
[V300_spool_holder.zip](https://github.com/Ultimaker/Cura/files/7637584/V300_spool_holder.zip)

**Comment by GregValiant** [comment]
I was able to slice it with Arachne beta 2 and 4.12.1.  There doesn't seem to be a problem with the model itself.  Below is the Arachne slice.
If it isn't slicing at all then you may need to post the cura.log file so one of the team members can take a look.
![image](https://user-images.githubusercontent.com/64202104/144342858-18c5d5b8-d359-41fe-9083-d54f0493e8b3.png)
