### ISSUE TITLE
MKS Plugin Connection

### ISSUE THREAD

**Issue by Jeeank** [Ultimaker/Cura#10984]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Two Trees Bluer

### Reproduction steps

1. I Installed MKS Plugin
2. I restarted the Cure 4.12.1
3. I opened the STL file and I sliced.
4. When trying to save the GCODE, it doesn't show the option to record TFT .

### Actual results

It does not show the option to generate the GCODE in the TFT in the button to write the GCODE.

### Expected results

I uninstalled CURA 4.12.1, reinstalled again, installed the MKS WiFi Plugin, but the same thing happened, the plugin didn't work.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura4 12 1](https://user-images.githubusercontent.com/64566682/144349841-5669dc85-1901-41c2-bf39-ce0e29431fa6.png)

**Comment by fieldOfView** [comment]
For issues with the MKS plugin, see https://github.com/Jeredian/mks-wifi-plugin/
