### ISSUE TITLE
lack of printing time stamp

### ISSUE THREAD

**Issue by SidneiCandrade** [Ultimaker/Cura#10981]
### Application Version

4.12

### Platform

mac catalina 10.15.7

### Printer

tarantula pro

### Reproduction steps

after slicing, the printing time is no longer displayed,

### Actual results

I would like the printing time to be displayed again

### Expected results

I would like the printing time to be displayed again

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

![Captura de Tela 2021-12-01 às 11 27 48](https://user-images.githubusercontent.com/54152474/144252268-5441fd1f-0995-4d05-9bc4-4513d9744ba5.png)

**Comment by fvrmr** [comment]
Hi @SidneiCandrade thank you for your report.
Could you share a project file (file - save project) and share it here on Github in a .zip

**Comment by SidneiCandrade** [comment]
hello, I can, no problem, it turns out that it's not a file, it's all the files that I put to slice that the printing time no longer appears. 

 

 

Sidnei

 

De: Fenne ***@***.***>
Responder para: Ultimaker/Cura ***@***.***>
Data: quinta-feira, 2 de dezembro de 2021 06:23
Para: Ultimaker/Cura ***@***.***>
Cc: Sidnei Andrade ***@***.***>, Mention ***@***.***>
Assunto: Re: [Ultimaker/Cura] lack of printing time stamp (Issue #10981)

 

Hi @SidneiCandrade thank you for your report.
Could you share a project file (file - save project) and share it here on Github in a .zip

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SidneiCandrade** [comment]
hello, here are the 3 files which i put in the curative for printing and all without the time data.

**Comment by SidneiCandrade** [comment]
I can't attach files

**Comment by GregValiant** [comment]
Zip them together and post the zip file.
