### ISSUE TITLE
Biqu B1 error

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10993]
### Application Version

4.12.1

### Platform

Mac

### Printer

Bibu b1

### Reproduction steps

Sadder and sadder with the Ultimaker Cura. Only mistakes. This time it won't let me add a 2 nozzle to the printer. Amazing how many errors are possible in a version and they are not corrected.

### Actual results

Sadder and sadder with the Ultimaker Cura. Only mistakes. This time it won't let me add a 2 nozzle to the printer. Amazing how many errors are possible in a version and they are not corrected.

### Expected results

Sadder and sadder with the Ultimaker Cura. Only mistakes. This time it won't let me add a 2 nozzle to the printer. Amazing how many errors are possible in a version and they are not corrected.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

*
![Captura de ecrã 2021-12-02, às 22 27 53](https://user-images.githubusercontent.com/23368014/144514084-0c6c1433-e0fd-416f-aa35-777575edd28b.png)

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your bug report. 
We don't maintain these printer profiles, the printer profiles are contributed by the community. 
You could add a custom FFF printer with more extruders. 

I will close this issue since this is something we won't do. I hope you understand.
