### ISSUE TITLE
Highly excessive ironing speed

### ISSUE THREAD

**Issue by MichaelObermeier** [Ultimaker/Cura#10997]
### Application Version

Arachne_engine_beta_2

### Platform

Windows 10

### Printer

Size modified Anycubic i3 Mega/ Happens on others too

### Reproduction steps

1. Import 40mm cube from .3mf
2. Select Normal profile
3. Enable Ironing

### Actual results

The default ironing speed is exceeded 10x resulting in 133 mm/s speed instead of 13.33 mm/s.

![TenFoldIroning](https://user-images.githubusercontent.com/53817086/144574985-df201492-25b0-411f-b4c5-2aadad6bed26.PNG)

Decreasing flow to 1% multiplies the speed another 10x resulting in 1333 mm/s.

![HundredFoldIron](https://user-images.githubusercontent.com/53817086/144574980-27bb5f74-6683-4d69-a6d4-a41dafb24408.PNG)

### Expected results

The set ironing speed should be respected.
Print speed should not exceed reasonable levels.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

It seems like this might be an issue with Arachne not recognizing ironing as a separate action and trying to increase speed for backpressure compensation.

[IronSpeed.zip](https://github.com/Ultimaker/Cura/files/7648138/IronSpeed.zip)

**Comment by fvrmr** [comment]
Hi @MichaelObermeier thank you for your bug report.
I created a ticket on our backlog for this.
Developers see CURA-8737

**Comment by Ghostkeeper** [comment]
This is considered a blocker for the stable release.

**Comment by fvrmr** [comment]
This is fixed for 5.0. The beta of 5.0 is already out, see here: https://github.com/Ultimaker/Cura/releases/tag/5.0-beta
I will close this issue, since it is fixed.
