### ISSUE TITLE
Cannot slice

### ISSUE THREAD

**Issue by iterator-de** [Ultimaker/Cura#10998]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Artillery Sidewinder X1

### Reproduction steps

1. Dropped STL on empty build plate
2. Sliced it with my standard settings
3. Previewed slice
4. Realised model was wrong one
5. Dropped new STL on build plate in the slice preview mode which automatically took me back to build plate
6. Deleted wrong model
7. Couldn't slice. Save to disk was the only option
8. Restart to fix problem

### Actual results

![Screenshot 2021-12-03 103824](https://user-images.githubusercontent.com/69585425/144580443-d45ef7bb-9304-4211-8f91-0b728d98dcdc.jpg)

### Expected results

Option to reslice should become available.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Would share project file if it was supported here on Github!

**Comment by fvrmr** [comment]
Hi @iterator-de thank you for your report.
You can share your project file in a zip here on Github. But I also need your log file. You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
