### ISSUE TITLE
Error Profile Import

### ISSUE THREAD

**Issue by NunoFilipePereira** [Ultimaker/Cura#10999]
### Application Version

4.12.1

### Platform

Mac

### Printer

Biqu B2

### Reproduction steps

Importing the profile gives an error as it always automatically has the others selected

### Actual results

gives error

### Expected results

let import profile

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Captura de ecrã 2021-12-03, às 11 01 37](https://user-images.githubusercontent.com/23368014/144592324-7d2ec2a7-3168-4dc7-bdd1-a813fa22d4d2.png)

**Comment by fvrmr** [comment]
Hi @NunoFilipePereira thank you for your report.
Could you share your profile you want to import?
