### ISSUE TITLE
Program sometimes shuts down when ejecting SD card

### ISSUE THREAD

**Issue by BurnData** [Ultimaker/Cura#10991]
### Application Version

Arachane_engine_beta 

### Platform

Windows 10 Home, Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz, 16gb ram, geeforce rtx 2060

### Printer

Ender 5

### Reproduction steps

1: sliced file
2: saved to SD card
3:ejected SD card
4;program closes on its own. (doesn't happen every time)

### Actual results

4;program closes on its own. (doesn't happen every time)

### Expected results

Program should not close when ejecting SD card

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by fvrmr** [comment]
Hi @BurnData thank you for your report.
Could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
