### ISSUE TITLE
I can't change layer height

### ISSUE THREAD

**Issue by MiguelAngelLV** [Ultimaker/Cura#11]
The layer height is always of 0.095. When I try change I can't type a dot and I write a comma the field is become in red.

If I only delete 095 and wite 2 (0.2) not change anything, the gcode is for 0.095. If I change the .cfg file, set 0.2 for height_layer and open Cura, the value is change to 0.095.

I use the code from today and branchs 15.06

Note: I use GNU/Linux, Debian Testing

**Comment by MiguelAngelLV** [comment]
I've noticed that when I change the quality "simple mode" the height of layer changes. It seems that not overwrite option

**Comment by MiguelAngelLV** [comment]
The bug is still in last version. The values of profiles override the manual value.

**Comment by awhiemstra** [comment]
Oh, seems I misread the original issue, since I thought it was about the dot-versus-comma we have has issues with before.

In regards to simple mode overwriting the set layer value, I will need some more comments from people since I have heard from other people that they actually expect that to happen.

**Comment by MiguelAngelLV** [comment]
Um... a checkbox to "force" a user manual configuration?

2015-06-25 10:19 GMT+02:00 awhiemstra <notifications@github.com>:

> Reopened #11 <https://github.com/Ultimaker/Cura/issues/11>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ultimaker/Cura/issues/11#event-339787911>.
>



-- 
Miguel Ángel López

**Comment by awhiemstra** [comment]
So there was a bug that I fixed where the simple mode settings would override the set layer height even if we open in Advanced mode. This is now fixed, though values will still be overridden when switching to simple mode and back. That however, will probably not be fixed any time soon.

**Comment by MiguelAngelLV** [comment]
So, If I use advance mode the layer height will not overrride, not? Ok for
me

2015-06-25 14:27 GMT+02:00 awhiemstra <notifications@github.com>:

> So there was a bug that I fixed where the simple mode settings would
> override the set layer height even if we open in Advanced mode. This is now
> fixed, though values will still be overridden when switching to simple mode
> and back. That however, will probably not be fixed any time soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ultimaker/Cura/issues/11#issuecomment-115234063>.
>



-- 
Miguel Ángel López

**Comment by awhiemstra** [comment]
Yeah, if you switch to advanced and do not switch back, it will remember the layer height properly.

**Comment by nallath** [comment]
@MiguelAngelLV Is this still an issue in the latest version?

**Comment by MiguelAngelLV** [comment]
@nallath the issue is solved, thanks.
