### ISSUE TITLE
adding same part again or multiply 1x causes an off build area issue

### ISSUE THREAD

**Issue by 95gtspeedemon** [Ultimaker/Cura#11009]
### Application Version

4.11.0

### Platform

win 10

### Printer

cr10 v3

### Reproduction steps

add sword to plate, use tool to lay flat side down (90*). multiply sword 1x, it goes from a 30min print to a 7 day print and showing a line off screen/build area that i cant see the extent of.
![Capture](https://user-images.githubusercontent.com/29670205/144730304-38d1c62e-5878-42dc-8280-c161510033ee.PNG
[sword large.zip](https://github.com/Ultimaker/Cura/files/7655053/sword.large.zip)
)

### Actual results

it becomes a 6 day print and 736g of filament (its a 10g print)

### Expected results

off build area issue to go away

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[sword large.zip](https://github.com/Ultimaker/Cura/files/7655054/sword.large.zip)

**Comment by 95gtspeedemon** [comment]
its a profile issue (which its fine with one sword and every other print thus far). use the fine profile and the issue stopped
![below build plate](https://user-images.githubusercontent.com/29670205/144730498-18eaa67d-f092-4d5b-ac99-017793f496bd.PNG)
![std dynamic profile](https://user-images.githubusercontent.com/29670205/144730501-c19649f5-b6b3-458c-b507-208128e36548.PNG)
![on build plate](https://user-images.githubusercontent.com/29670205/144730502-a0df672f-0f69-4326-8732-c760876f03bc.PNG)
.

**Comment by 95gtspeedemon** [comment]
my profile, instead of using the lay flat tool, i turned the model 90* manually. then multiplied by 1, ok this time...

**Comment by fvrmr** [comment]
Hi @95gtspeedemon thank you for your report.
Could you share a project file (file - save project)? Your 3mf does not contain the Cura settings.
