### ISSUE TITLE
Terrible performance in some dropdowns

### ISSUE THREAD

**Issue by sneakythr0ws** [Ultimaker/Cura#11003]
### Application Version

4.12.1 and previous

### Platform

Linux(Ubuntu 21.10 and previous)

### Printer

Flyingbear ghost 5

### Reproduction steps

Open `Material` or `Nozzle Size` choice dropdown. 

### Actual results

Performance in this dropdown is very very bad. 

### Expected results

Same performance in all part of system. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This drop down works fine:
![image](https://user-images.githubusercontent.com/1594945/144650519-5337081a-ee48-404c-9fe2-eb66db37b56e.png)
but `Material` and `Nozzle Size` have very very bad performance. This dropdowns have different color scheme(white.).Sorry for quality. I can't screenshot it and made a photo with smartphone
![image](https://user-images.githubusercontent.com/1594945/144653482-d9819a4c-9c7e-4164-9dab-362ec6a088c2.png)

In preferences dialog performance is good.

**Comment by fvrmr** [comment]
Hi @sneakythr0ws thank you for your report.
Could you share your log file? You can find your log file here: `$HOME/.local/share/cura/<Cura version>/cura.log`

**Comment by sneakythr0ws** [comment]
> Hi @sneakythr0ws thank you for your report. Could you share your log file? You can find your log file here: `$HOME/.local/share/cura/<Cura version>/cura.log`

Sure. But I don't see changes when I use dropdown(I used tail -f)
[cura.log](https://github.com/Ultimaker/Cura/files/7668379/cura.log)

**Comment by fvrmr** [comment]
Hi @sneakythr0ws I can't see anything happening in that log. Could you do your reproductions steps: open material and or open nozzle size dropdowns. And after you did that close Cura and again share your log file here.

**Comment by sneakythr0ws** [comment]
> Hi @sneakythr0ws I can't see anything happening in that log. Could you do your reproductions steps: open material and or open nozzle size dropdowns. And after you did that close Cura and again share your log file here.

As I said I tried `tail -f cura.log` and monitored log when I clicked dropdown. Nothing happened in log. 
I think it may be hardware acceleration problem. Is it possible to switch to software api?

**Comment by sneakythr0ws** [comment]
@fvrmr do you need any extra info?

**Comment by fieldOfView** [comment]
Recently some users have reported sluggish UI performance in Cura that seems to be caused by a 3rd party component that monitors the network for Ultimaker printers. If you don't have any Ultimaker printers, you could try disabling that module.

Go to the "Installed" tab of the Marketplace, and scroll down to "UM3 Network Printing" and uncheck the checkmark in front of it. Restart Cura and check if the terrible performance is still there.

**Comment by sneakythr0ws** [comment]
> Recently some users have reported sluggish UI performance in Cura that seems to be caused by a 3rd party component that monitors the network for Ultimaker printers. If you don't have any Ultimaker printers, you could try disabling that module.
> 
> Go to the "Installed" tab of the Marketplace, and scroll down to "UM3 Network Printing" and uncheck the checkmark in front of it. Restart Cura and check if the terrible performance is still there.

I tried. But unfortunately no effect. Dropdown controls still have bad performance(

I have problem only in two dropdowns. Look at my screenshots. With dropdowns have different color scheme than main controls and panels. May be this dropdowns use another styles, components, libraries ?

**Comment by sneakythr0ws** [comment]
This window has terrible performance too. It takes 5 seconds to enter one character 
![image](https://user-images.githubusercontent.com/1594945/145803223-848a26bf-a1ca-455a-8373-b5d569a6dd0c.png)

**Comment by sneakythr0ws** [comment]
> Could you install and use this plugin to generate some profiling information for us: https://marketplace.ultimaker.com/app/cura/plugins/UltimakerPackages/ExtensiveSupportLogging

[log.zip](https://github.com/Ultimaker/Cura/files/7718203/log.zip)

**Comment by nallath** [comment]
Hmm. I don't really see anything that would explain a slowdown. The rendering update itself seems to take only 2ms, so that's well within the range that one would expect

Could you also run the plugin from startup? It might provide a bit more information.

**Comment by sneakythr0ws** [comment]
> Hmm. I don't really see anything that would explain a slowdown. The rendering update itself seems to take only 2ms, so that's well within the range that one would expect
> 
> Could you also run the plugin from startup? It might provide a bit more information.

I made some extra tests. The problem appears only on external display with fractional scaling
![image](https://user-images.githubusercontent.com/1594945/146214729-6d856527-c3f0-4022-88f7-66c5867e8a0c.png)

**Comment by Ghostkeeper** [comment]
That's a good hint. Unfortunately on my current computer, my work laptop, using fractional scaling at 125% still causes it to go to 200%. Seems to be a bug in Ubuntu (20.04) there for me.

At home I have a more modern version of Ubuntu (21.10) so maybe I could try it again there.

**Comment by sneakythr0ws** [comment]
> That's a good hint. Unfortunately on my current computer, my work laptop, using fractional scaling at 125% still causes it to go to 200%. Seems to be a bug in Ubuntu (20.04) there for me.
> 
> At home I have a more modern version of Ubuntu (21.10) so maybe I could try it again there.
> 
> I suspect that Qt 6.2 will fix this issue by removing use of Controls 1, which seems to be the places where this issue occurs.

FYI 4.13 beta affected too

**Comment by Ghostkeeper** [comment]
Indeed at home the 125% fractional scaling works properly. But the performance of Cura feels normal, even in the drop-downs and pop-ups. I'm not able to reproduce this issue yet.

**Comment by sneakythr0ws** [comment]
> Indeed at home the 125% fractional scaling works properly. But the performance of Cura feels normal, even in the drop-downs and pop-ups. I'm not able to reproduce this issue yet.
For me problem appears only on **external** 4k monitor. On build-in laptop 4k display even with factional scaling it works properly. Other software works fine.

**Comment by Ghostkeeper** [comment]
Yes, I have a desktop computer so every monitor is an external monitor. I also have a second "monitor", a 4k projector, which doesn't show the problem either.

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?

**Comment by sneakythr0ws** [comment]
> Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?

Sure. It works fine
