### ISSUE TITLE
Infill can't be defined

### ISSUE THREAD

**Issue by AndrezinhoCosta** [Ultimaker/Cura#11007]
### Application Version

4.12.1

### Platform

MacOS

### Printer

RatRig V-Core 3

### Reproduction steps

I was creating a temperature tower and I use only the walls. The INFILL was in 0%, but in preview I have 20%. 
And the INFILL now is blocked to modifications, unselectable.

### Actual results

![PHOTO-2021-12-04-14-57-17](https://user-images.githubusercontent.com/53056892/144720003-b224290a-0cd1-4426-80bd-4110c8eb0e85.jpg)

### Expected results

It should be free to use the infill...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don't know if it's something wrong in my computer... But I think no.

**Comment by Asterchades** [comment]
You've manually set an Infill Line Distance (Distância da Linha de Preenchimento), which overrides the density (Densidade) percentage value. Click the "fx" indicator on the line distance setting to return it to being calculated by the percentage you've entered instead.

This is no different to the value for the number of walls overriding the wall width setting, or other similar indented values.
