### ISSUE TITLE
Hole Horizontal expansion  delete the print area from the files. 

### ISSUE THREAD

**Issue by Talha909** [Ultimaker/Cura#11000]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

CR 10

### Reproduction steps

I turn on the Hole Horizontal expansion. 

### Actual results

Print area disappear
![without horizental](https://user-images.githubusercontent.com/29024390/144601712-7741b1eb-bc5e-4be7-a1fe-bee434115bba.JPG)
![horizental hole](https://user-images.githubusercontent.com/29024390/144601720-a7bdccb6-36d6-4b92-8b84-0dd95d9f2438.JPG)
 from the print. 

### Expected results

It suppose only effect the hole on thr print. But it delete the printed areas from the some sides. 
![horizental hole](https://user-images.githubusercontent.com/29024390/144602240-5a484c6a-94ae-4f5d-bbf5-ce67967cd8db.JPG)
![without horizental](https://user-images.githubusercontent.com/29024390/144602247-dfb8f05d-85a4-4947-81ad-cb42dacc6740.JPG)
[CCR10SPRO_New bltouch after update.zip](https://github.com/Ultimaker/Cura/files/7649559/CCR10SPRO_New.bltouch.after.update.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I have upload the both files. 
[CCR10SPRO_New bltouch after update.zip](https://github.com/Ultimaker/Cura/files/7649567/CCR10SPRO_New.bltouch.after.update.zip)
Can you please check

**Comment by Talha909** [comment]
![123Untitled](https://user-images.githubusercontent.com/29024390/144605374-00d74396-28f5-4dfd-9655-8840b599a4a5.png)

**Comment by GregValiant** [comment]
Cura cannot tell the difference between a round feature and a square feature.  A hole is a hole whether it is comprised of 3 sides, 8 sides, or 3000 very short sides.  There are no circles - just approximations.
So Hole Horizontal Expansion acts on any enclosed internal vertical feature whether it's square, an octagon, a trischilioi-gon or whatever.
If you want to adjust the printed diameter of the three vertical holes on that shelf then it is probably easier to do that in CAD.  You could try using a Support Blocker as a Mesh Modifier.
Hole Horizontal Expansion works in the X and Y and so has no effect on horizontal holes, just vertical ones.
Set the Hole Horizontal Expansion to 5 and look at the preview.

**Comment by Talha909** [comment]
![horizental hole4](https://user-images.githubusercontent.com/29024390/145209940-e3011070-2b56-43a5-94df-c9d9d32a1ecf.JPG)
This is the view when I add 5 in horizontal expansion.

**Comment by Ghostkeeper** [comment]
This is indeed expected behaviour.

You have some (rectangular) holes between the panels in that lower section. It's making them bigger. The bigger hole erases some part of the structure around it, which is those panels, in this case.

Hole Horizontal Expansion works with limited scope: It will only expand holes in the layers, i.e. vertical holes.

There is no way that I know of that can neatly achieve what you want to achieve in Cura. You'd have to edit the model to be able to make those horizontal holes bigger.
