### ISSUE TITLE
Top layer added where is none

### ISSUE THREAD

**Issue by thomaskilian** [Ultimaker/Cura#11012]
### Application Version

4.12.1

### Platform

OS X (M1)

### Printer

Custom

### Reproduction steps

I have a simple model which is sort of a cup-formed cover. When rendering Cura adds a top layer where none should be. Turning it to the side it does not add support at all.

<img width="454" alt="Bildschirmfoto 2021-12-05 um 16 52 42" src="https://user-images.githubusercontent.com/69296/144753734-f1cde740-cfc2-49a5-b408-f59b4ba31d22.png">

Slice with slight tilt:
<img width="223" alt="Bildschirmfoto 2021-12-05 um 16 53 16" src="https://user-images.githubusercontent.com/69296/144753775-56e0a63f-8bf0-4c23-ae2b-7b17debb81de.png">

Slices bottom down:
<img width="342" alt="Bildschirmfoto 2021-12-05 um 16 54 14" src="https://user-images.githubusercontent.com/69296/144753798-c19813fd-c97d-48e9-a909-1e3e4d9fbf29.png">

### Actual results

Single "ghost" top layer added

### Expected results

Well, no "ghost" top...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CFFFP_temp.3mf.zip](https://github.com/Ultimaker/Cura/files/7656305/CFFFP_temp.3mf.zip)

**Comment by thomaskilian** [comment]
I just tried that with 4.9 and it slices correctly there.

**Comment by GregValiant** [comment]
Under "Mesh Fixes" de-select "Remove All Holes".  The inside of your box constitutes a rectangular hole and so it is being removed.

**Comment by thomaskilian** [comment]
Will test that in an hour or so. Anyhow, that option should rather be an opt-in than an opt-out. Makes me wonder that nobody else fell in that trap already.

**Comment by thomaskilian** [comment]
There is no such option:
<img width="112" alt="Bildschirmfoto 2021-12-05 um 21 27 12" src="https://user-images.githubusercontent.com/69296/144762769-ecdb4a77-8fa3-4ca1-a60f-a93c41b8fb4d.png">

**Comment by thomaskilian** [comment]
Noticed only now that this has been closed. The above is no solution.

**Comment by fvrmr** [comment]
Hi @thomaskilian thank you for your report.
Like @GregValiant is mentioned you need to disable `Remove All Holes`

In 4.9.1 it is also showing the ghost layer. Because this is set in your project file. 
![Screenshot (312)](https://user-images.githubusercontent.com/77000924/144822082-d278eda3-371a-4d3f-ba38-a87051937b56.png)

**Comment by thomaskilian** [comment]
Well, I just don't see that option :-/ And I rendered the stl file from source in the former versions, not from a project file. Before/including V10 it worked and starting from V11 it fails. Here what V11 shows (working on another machine currently):
<img width="448" alt="pic20211206103934" src="https://user-images.githubusercontent.com/69296/144823435-0f2da57c-d509-4c44-90d3-07d07d5d186c.png">

**Comment by GregValiant** [comment]
Check the setting visibility.  If you hover the mouse over Mesh Fixes an icon will appear on the right.  Click it and see if Remove All Holes appears in the dialog.
An alternative is to select the Setting Visibility control to the right of the Setting Search box and set the visibility to "All".

![Untitled](https://user-images.githubusercontent.com/64202104/144826145-3547f04d-eb5f-47e2-92ac-097db7e96bc4.png)

This is with it un-checked.

![Untitled1](https://user-images.githubusercontent.com/64202104/144826447-686d1ae4-4f0e-4f9a-bb13-31dcfc2e7a73.png)

**Comment by thomaskilian** [comment]
Uhm, interesting. Now on this machine I see the option. I was sure to have looked at the complete list yesterday on the other machine and not seeing it. Well, I'll check that when I switch over later the day...

**Comment by thomaskilian** [comment]
Well, in any case: I never touched that option (as you can see I was not even aware of it's existance). So it must have been set during migration. Either on purpose (bad idea) or accidentally (not better either). In any case this option needs to be turned off except for people wanting it to be set (for whatever case).

**Comment by thomaskilian** [comment]
So I'm at my machine now and now I see the option (no idea what was on yesterday). However, it's not set:
<img width="117" alt="Bildschirmfoto 2021-12-06 um 12 32 18" src="https://user-images.githubusercontent.com/69296/144839081-994130e6-a05f-4211-8dc1-c07b518fff0a.png">
And toggling it does not seem to tangent the slicer. It won't re-enable Start Slicing. Also it will not appear in the menu.

<img width="598" alt="Bildschirmfoto 2021-12-06 um 12 36 11" src="https://user-images.githubusercontent.com/69296/144839403-54af5cbe-ee39-4712-889a-b5bf2e6a45d8.png">

And maybe you have not noticed, but if you see the very first picture above you notice that there was no support generated. There's something very strange here.

**Comment by GregValiant** [comment]
Here is a 3mf with your printer.  I've altered some settings but left the retraction distance alone.  When you open it in Cura you will see how I've set it up.  
[GV_temp.zip](https://github.com/Ultimaker/Cura/files/7660991/GV_temp.zip)

**Comment by thomaskilian** [comment]
Can you tell me how to open that with Cura??? Cmd-O does not recognize the format (only Prusa Slicer would).

**Comment by GregValiant** [comment]
FIle | Open

**Comment by thomaskilian** [comment]
I did say that this is not possible. Greyed out:
<img width="91" alt="Bildschirmfoto 2021-12-06 um 19 59 07" src="https://user-images.githubusercontent.com/69296/144905886-97e43947-5e6c-4d1d-a712-5ec8671e23f5.png">

**Comment by fvrmr** [comment]
You can drag the 3mf also onto the build plate.

**Comment by thomaskilian** [comment]
Not really:
<img width="191" alt="Bildschirmfoto 2021-12-07 um 12 52 58" src="https://user-images.githubusercontent.com/69296/145024487-da33e2a6-8070-4b99-9c25-2db6322795b4.png">

**Comment by thomaskilian** [comment]
Interestlingly though, I now see the Hole option:

<img width="218" alt="Bildschirmfoto 2021-12-07 um 13 17 19" src="https://user-images.githubusercontent.com/69296/145027665-66623fe1-126e-45ab-994b-c583b8be802c.png">

**Comment by fvrmr** [comment]
Strange... Did disabling this setting solve the issue for you?

**Comment by thomaskilian** [comment]
Well, now it slices correctly. Don't ask me, but I'd tell you there'se something terribly fowl and you should keep an eye on this.

**Comment by Ghostkeeper** [comment]
> Will test that in an hour or so. Anyhow, that option should rather be an opt-in than an opt-out. Makes me wonder that nobody else fell in that trap already.

It is by default disabled. I don't think any profile in Cura's distribution ever enables Remove All Holes by default. Nor do I think they should. It's a mesh fixing setting, so not really relevant to profiles.
It could be that you loaded a profile or project file from someone else at some point that enabled this setting.

> Interestlingly though, I now see the Hole option:
> 
> <img alt="Bildschirmfoto 2021-12-07 um 13 17 19" width="218" src="https://user-images.githubusercontent.com/69296/145027665-66623fe1-126e-45ab-994b-c583b8be802c.png">

This happens if you disable the 3MF reading plug-in. Some people disable that to improve performance, though it really only saves a miniscule amount of time. I'd suggest the Start-up Optimizer plug-in instead which is much more clever with what it disables.

**Comment by thomaskilian** [comment]
I disabled quite some plugins which did tell me nothing. That might have been one of them. Interestingly though dropping the file seemed to have made changes. I can't tell for sure under which circumstance the Mesh option did appear. But since it appeared my issue was gone. Definitely I smeel a bug hiding there somewhere.
