### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by johnco1126** [Ultimaker/Cura#11030]
### Application Version

Arachne_Engine_beta_2

### Platform

Windows 11

### Printer

FLSUN SR

### Reproduction steps

Add objects to play. Add custom support.

### Actual results

Slice fails.   Slicing engine stops.

### Expected results

Slicing succeeds

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Works fine with other objects

**Comment by fvrmr** [comment]
Hi @johnco1126 thank you for your report. 
Does this happen with every file you want to slice? Could you share a project file (file - save project) and your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
