### ISSUE TITLE
2.3: Can't add printer

### ISSUE THREAD

**Issue by victor9999** [Ultimaker/Cura#1103]
When running cura from 2.3 branch it won't add the new printer.
[cura.log.txt](https://github.com/Ultimaker/Cura/files/568616/cura.log.txt)

**Comment by nallath** [comment]
This is an issue that has been fixed for 2.3.1

**Comment by nickthetait** [comment]
It is possible to add a new printer using a build of 2.3. But it does not work by running from the source code using 2.3 branches? Is there some other branch we should we be using?

**Comment by fieldOfView** [comment]
Have you populated the materials folder?

**Comment by nickthetait** [comment]
@victor9999 is one of our contractors. I have talked with him a little bit about this problem. I'm not certain, so will leave it to him to provide more details.
