### ISSUE TITLE
I would like to rotate using middle mouse button

### ISSUE THREAD

**Issue by capuadaniel** [Ultimaker/Cura#11033]
### Is your feature request related to a problem?

I use a wacom tablet (the simplest, "one by wacom") and I can't rotate around the print bed using the pen. I tried to change how the pen works, and it didn't work, and even if it was solved the problem... I should change my sculpt configurations each time I access cura again.
I tried to use shift and ctrl... it simply dont work too.

### Describe the solution you'd like

Please, make the shortcuts changeable.
OR the rotate shortcut editable. 

### Describe alternatives you've considered

If create a configurable rotate control is not a solution, you can fix the shift or ctrl to the wacom pen. Shift+click makes translation moves Ctrl+click could make rotate moves.

### Affected users and/or printers

All people that uses wacom devices to sculpt and print.

**Comment by fvrmr** [comment]
Hi @capuadaniel thank you for your feature request.
We already have an issue open to make shortcuts and key combinations customisable. See https://github.com/Ultimaker/Cura/issues/10609 and this is also on our backlog.
I will close this issue since it is a duplicate.
