### ISSUE TITLE
Cannot slice models taller than ~550mm

### ISSUE THREAD

**Issue by colin-donar** [Ultimaker/Cura#11046]
### Application Version

4.12

### Platform

Windows 10

### Printer

Custom pellet printer

### Reproduction steps

1. Create printer profile with Large Z height
2. import large model
3. slice

### Actual results

4. If model is larger than ~550mm then cura wont slice anything and the preview will be blank. see image full.png

![full](https://user-images.githubusercontent.com/77845904/145468577-9c862f96-4e54-4b75-8557-f86497a59186.png)

### Expected results

Sinking the model into the bed to shorten the sliced model will result in cura correctly displaying the gcode preview. see image short.png

![short](https://user-images.githubusercontent.com/77845904/145468751-8917be8f-5a30-4eb7-8823-6cd53fd21cab.png)

both images are taken after clicking "slice"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have replicated the issue on multiple machines (including machine with activated windows)
I have found Version 4.9 does not have this issue...

I can provide log/project files eventually if requested. Currently away from that computer...

**Comment by fvrmr** [comment]
Hi @colin-donar thank you for your report. 
I need indeed your log and project file to see what is causing this. You can share this in a .zip here on Github.

**Comment by colin-donar** [comment]
[cura issue.zip](https://github.com/Ultimaker/Cura/files/7693772/cura.issue.zip)
Log and Project file

**Comment by colin-donar** [comment]
Any update @fvrmr?

**Comment by Ghostkeeper** [comment]
It's currently working on master and 4.13. I believe this is fixed by https://github.com/Ultimaker/CuraEngine/commit/75d826437aaa18a27c65a18f5620ae960e6511ba, after a similar report on Reddit. This fix is included in 4.13. Could you try with the beta?

**Comment by colin-donar** [comment]
Just tested the beta and the bug is gone! Thanks!
