### ISSUE TITLE
Build Plate Adhesion

### ISSUE THREAD

**Issue by Pedrx** [Ultimaker/Cura#11050]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Ender 5 +

### Reproduction steps

Attempted to add a Brim

### Actual results

![Build Plate Adhesion](https://user-images.githubusercontent.com/46064440/145588188-e7ee0563-c222-468c-b8d1-022ae5faf8a6.png)

### Expected results

Not the above.

![Build Plate Adhesion](https://user-images.githubusercontent.com/46064440/145588984-5a4101d5-469a-4177-938a-70e88cc9eba9.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

None

**Comment by GregValiant** [comment]
Check your Brim Line Count.  At 2000 and a .4 line width that's 800mm wide all around the model.  Your build plate would need to be 1700 x 1700 to fit that.
If you click on the icon next to the number it will re-set back to "Brim Width / Line Width" which (dependent on line width) should be around 20.

**Comment by Pedrx** [comment]
Thank you for prompt reply but no, I didn't insert a brim line count of 2000! 
It appears of its own volition and refuses to go away.
Not with the CE3 though. In fact I'm getting a successful print, so far, by using Cura to prepare the file for the CE3 then shoving the SD card in the CE5. 
    On Friday, 10 December 2021, 17:13:44 GMT, GregValiant ***@***.***> wrote:  
 
 


Check your Brim Line Count. At 2000 and a .4 line width that's 800mm wide all around the model. Your build plate would need to be 1700 x 1700 to fit that.
If you click on the icon next to the number it will re-set back to "Brim Width / Line Width" which (dependent on line width) should be around 20.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GregValiant** [comment]
"support_brim_line_count" has a maximum of 50 before the warning shows up and the default appears to be 20.  Those should have loaded when you installed the Ender 5 in Cura.
The Cura folks are going to need a project file (File | Save Project) and probably a log file (Help | Show Configuration Folder and "Cura.log") so they can figure out where the 2000 came from.  Zip them up and post them here.
Did you try switching to "Skirt" or "Raft"?
