### ISSUE TITLE
Décalage entre la pièce et le Raft 

### ISSUE THREAD

**Issue by sebr6** [Ultimaker/Cura#11055]
### Application Version

4.12.1

### Platform

windows 10

### Printer

Snapmaker A350

### Reproduction steps

Lors du tranchage avec un raft il y a un décalage entre la pièce et le raft . 
![raft](https://user-images.githubusercontent.com/38330726/145675070-a4fff58d-e52b-4d8f-9eda-d941ef450a5d.PNG)

### Actual results

Décalage

### Expected results

Enlever le décalage , imprimer sur le raft

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Uploading S2A_Groot_hole_fixed.zip…]()
[Uploading cura.log…]()

**Comment by sebr6** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/7696924/cura.log)
[Uploading S2A_Groot_hole_fixed.zip…]()

**Comment by fvrmr** [comment]
Hi @sebr6 thank you for your report.
I can't open your project file, since it was not done with uploading. But you could check the `Raft Air Gap` setting. 
Also for next time please fill in the form in English.

**Comment by sebr6** [comment]
> Hi @sebr6 thank you for your report. I can't open your project file, since it was not done with uploading. But you could check the `Raft Air Gap` setting. Also for next time please fill in the form in English.

After adding and modifying the raft air gap it's ok.
thank you very much 👍

**Comment by Ghostkeeper** [comment]
This is the intended behaviour of the Raft Air Gap setting.
