### ISSUE TITLE
Unable to drop file

### ISSUE THREAD

**Issue by VASAPOL** [Ultimaker/Cura#11063]
### Application Version

4.11.0

### Platform

MacOS

### Printer

Biqu B1 ABL

### Reproduction steps

Upload using fusion directly to Cura and model not appear.and I tried to download model directly from Fusion 360 and drop directly to Cura and program not show anything and I tried to click "Slice" and program show "Unable to slice"

### Actual results

reopen application

### Expected results

no issue was found again and couple hour after and issue found again

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

https://user-images.githubusercontent.com/43716227/145761936-9f4b0a91-11b5-439c-8cca-622100a8d4f7.mov
[BB1ABL_Component6.3mf.zip](https://github.com/Ultimaker/Cura/files/7701402/BB1ABL_Component6.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7701409/cura.log)
[cura.log.1.zip](https://github.com/Ultimaker/Cura/files/7701410/cura.log.1.zip)

**Comment by Ghostkeeper** [comment]
Note that 3MF files retain their model coordinates on the build plate (as required by the 3MF spec). Possibly you may need to look around with the camera to find it.
