### ISSUE TITLE
Same material - dual extrusion For parts over 1kg

### ISSUE THREAD

**Issue by TheMagicPig** [Ultimaker/Cura#11065]
### Is your feature request related to a problem?

The issue is that we have parts that require more than 1kg of material (one color). Currently we have to manually change the spool to a new spool mid print or slice the model as if it was 2 coloured parts and use the 2 extruders. 

### Describe the solution you'd like

My request is to have an option where when the ultimaker printer detects that one material has ran out, it switches to the second extruder. Both material would have to have the same nozzle and material set up but that would allowe prints up to 2kg material (with the standard 1kg spool).

### Describe alternatives you've considered

When the printer detects the material has ran out or the print exceeds 1kg (or 900g) it switches to the second extruder. The spool on the first extruder would have to be new.

### Affected users and/or printers

Anyone with an ultimaker 5S or anyone with printers that have large print volume.

**Comment by fvrmr** [comment]
Hi @TheMagicPig thank you for your feature request. 
When using a material station for your S5 it will switch materials on the same nozzle when one material is empty it will automatically switch to the other same material in your material station. 
Read here more about the material station: https://support.ultimaker.com/hc/en-us/articles/360011547780-Printing-with-the-Material-Station
But your request is not something we can do in Cura but needs to be changed in the firmware. 
So I will close this issue. But let me know what you think!
