### ISSUE TITLE
Font Kerning in End Gcode Text Box

### ISSUE THREAD

**Issue by ChristopherBonner** [Ultimaker/Cura#1106]
The font kerning in the End Gcode text box is off. Letters are overlapping. Looks like it's mainly the letter "L" (lowercase) that is problematic.
![cura_font_kerning](https://cloud.githubusercontent.com/assets/5431359/19991468/cfe216f6-a1f2-11e6-9611-cf41aea8ba2d.PNG)

**Comment by Ghostkeeper** [comment]
Doesn't reproduce here on Ubuntu. What operating system are you using, Christopher?

**Comment by ChristopherBonner** [comment]
Windows 10 Professional.
Cleartype is on (Windows has this on by default)

Interesting note: this issue seems to be tied very specifically to window size. If I resize the window by one or so pixels in width, the font kerning issue disappears. Will reappear if I resize to another size. Could be an even/odd scaling problem?

**Comment by awhiemstra** [comment]
This is most likely an upstream bug. We do not touch the font rendering, this is all handled by Qt. It may very well be related to https://bugreports.qt.io/browse/QTBUG-46030 . If you have some time and a text editor it may be possible to play around with Qt's text rendering hints to get improved rendering.

**Comment by nallath** [comment]
Closing this as it's upstream.

**Comment by fieldOfView** [comment]
Not only is it upstream, it was fixed by rounding the pixel boundaries, and by switching to another font (non proportional).
