### ISSUE TITLE
Can't import SLDPRT if solidworks is running

### ISSUE THREAD

**Issue by JiMcNulty** [Ultimaker/Cura#11079]
### Application Version

4.12.1

### Platform

windows

### Printer

Cr-10

### Reproduction steps

1. Open a part in solidworks
2. Try to import it to Cura
3. Fail

### Actual results

Error msg - fail to open corrupted or inaccessible 

### Expected results

Open it, like versions before that
Its worked on 4.11

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

solidworks plugin

**Comment by fvrmr** [comment]
Hi @JiMcNulty thank you for your report.
This is probably related to the Solidworks plugin. We don't maintain this plugin. Please report it to the maintainer https://thopiekar.eu/cura/cad/solidworks/
So I will close this issue, since this is not something we will fix. I hope you understand.
