### ISSUE TITLE
Changing infill density in "Modify Settings For Overlap", no longer working in Cura 4.12.1

### ISSUE THREAD

**Issue by Dgilla** [Ultimaker/Cura#11070]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

S5

### Reproduction steps

1. support blocker
2. Scale and a surround an area on my object
3. Per Model Settings/ Modify settings for Overlap
4. Change infill density to 80%
5. Change Infill pattern to grid
6. Slice
7. Warning pops up, unable to slice
8. Have done this many times before, now not working in the new Cura

### Actual results

Wont slice

### Expected results

Will slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[S5-CUIRA-No-Slice.zip](https://github.com/Ultimaker/Cura/files/7707335/S5-CUIRA-No-Slice.zip)

**Comment by fvrmr** [comment]
Hi @Dgilla thank you for your report. 
Your model is set to don't support overlaps in the per model settings, so there is nothing to slice. 
Change your model to per model settings - normal model. And then you can slice your model.
![Capture-permodel](https://user-images.githubusercontent.com/77000924/145969653-93684607-7911-4a1a-bcfd-320b3c54b36f.PNG)

**Comment by GregValiant** [comment]
![image](https://user-images.githubusercontent.com/64202104/146174508-c23a737a-f16b-41f7-b3a4-5507edfe6aa3.png)

**Comment by Dgilla** [comment]
Great thanks for your help,
It was just that I selected the model and blocks, instead of just the blocks when changing the infill density
