### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by dmitrygribenchuk** [Ultimaker/Cura#11073]
### Application Version

4.13~202112141335 PPA

### Platform

Linux Mint

### Printer

Creality Ender 3 v2

### Reproduction steps

1) Open STL model
2) Slice it

It's working fine at the previous version (for example at 4.13~202112131335). Now it's broken on every model.

### Actual results

Get error: Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.

### Expected results

Slicing completed

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log.gz](https://github.com/Ultimaker/Cura/files/7718845/cura.log.gz)
![Selection_1585](https://user-images.githubusercontent.com/15670247/146177092-2426945f-d61b-414e-94b2-864c71de6701.png)

**Comment by dmitrygribenchuk** [comment]
Also reproduced on 4.13~202112151335

**Comment by fvrmr** [comment]
Hi @dmitrygribenchuk thank you for your report.
Could you also share your project file?

**Comment by kiss81** [comment]
I can confirm this issue on the latest ppa builds. It's also complaining that it can't load the following plugins:
Sentrylogger, AMFReader, TrimeshReader

[concolelogcura.txt](https://github.com/Ultimaker/Cura/files/7733503/concolelogcura.txt)
[CCR10_3DBenchy.3mf.txt](https://github.com/Ultimaker/Cura/files/7733506/CCR10_3DBenchy.3mf.txt)

**Comment by kiss81** [comment]
I can confirm the slicing issue is solved. I still get the missing plugin errors on
Sentrylogger, AMFReader, TrimeshReader

**Comment by Ghostkeeper** [comment]
So this probably was a temporary problem in the version they built nightly. The only change we made to CuraEngine between 2021-12-14 and 2021-12-18 was a fix for tree support which is disabled in Kiss' project file, so I don't know what made it tick there. Could be that those builds are a bit behind and it was https://github.com/Ultimaker/CuraEngine/commit/75d826437aaa18a27c65a18f5620ae960e6511ba.

**Comment by dmitrygribenchuk** [comment]
Hello. have the same problem with 4.13~202202021404
[cura.log.zip](https://github.com/Ultimaker/Cura/files/8060445/cura.log.zip)

**Comment by fvrmr** [comment]
@dmitrygribenchuk could you share a project file? (file - save project)
Your logs don't show what is causing this.

**Comment by dmitrygribenchuk** [comment]
Sure
[CE3_GoPro_Monitor_Mount_Laptop.3mf.zip](https://github.com/Ultimaker/Cura/files/8061830/CE3_GoPro_Monitor_Mount_Laptop.3mf.zip)

**Comment by fvrmr** [comment]
Hi @dmitrygribenchuk, thank you it is working for me on master.
Please keep in mind that you are using a nightly we don't maintain. So they are maybe a bit behind with our master branch.

**Comment by dmitrygribenchuk** [comment]
Fixed on 4.13~202202271238
