### ISSUE TITLE
Abnormal slice

### ISSUE THREAD

**Issue by whoseyoung** [Ultimaker/Cura#11082]
### Application Version

4.12.1

### Platform

windows10

### Printer

Geeetech A10

### Reproduction steps

Use the attached slice parameter to preview the slice, the printing effect is very poor

### Actual results

Severe striations appear

### Expected results

Solve the layer pattern problem

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Abnormal slice.zip](https://github.com/Ultimaker/Cura/files/7731571/Abnormal.slice.zip)

**Comment by GregValiant** [comment]
I get a "compressed file is invalid" message when I try to extract from that zip file.

**Comment by fvrmr** [comment]
Hi @whoseyoung thank you for your report.
Can you share a project file (file - save project) instead of your profile. Also can you show a screenshot what is happening.

**Comment by whoseyoung** [comment]
Hi all，
Thank you for your reply. Maybe I made a mistake, and I have solved it just now


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Ultimaker/Cura"                                                                                    ***@***.***&gt;;
Date:&nbsp;Wed, Dec 22, 2021 08:10 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Ultimaker/Cura] Abnormal slice (Issue #11082)





 
Hi @whoseyoung thank you for your report.
 Can you share a project file (file - save project) instead of your profile. Also can you show a screenshot what is happening.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fvrmr** [comment]
Good to know it has been solved. I will close this issue. Feel free to reach out if you have more questions!
