### ISSUE TITLE
Unable to slice a thin shell correctly

### ISSUE THREAD

**Issue by ilko-k** [Ultimaker/Cura#11090]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Load the provided .stl file and try to get a decent slice.
[Caliset-Flow_1_perimeter.zip](https://github.com/Ultimaker/Cura/files/7740020/Caliset-Flow_1_perimeter.zip)

### Actual results

![Snipaste_2021-12-18_23-06-32](https://user-images.githubusercontent.com/5411848/146656768-dee17cce-7a10-4131-a0f2-e0de9bdf40b6.jpg)

### Expected results

![Snipaste_2021-12-18_23-01-25](https://user-images.githubusercontent.com/5411848/146656777-a20ce03a-559a-4ae1-be9c-720017bc1b90.jpg)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Even in vase mode, the behavior is bad and the nozzle does a lot of unecessary moves and retractions, leaving gaps and holes. The shell of this object is of 0.4 mm width. I also tried to reduce the line width parameter in Cura with no luck. It seems to occur only when there is a thin wall that is smaller than 0.8 mm
[Caliset-Flow_1_perimeter_project.zip](https://github.com/Ultimaker/Cura/files/7740773/Caliset-Flow_1_perimeter_project.zip)
.

**Comment by GregValiant** [comment]
Line Width .399
Enable Compensate Outer Wall Overlaps.
Vase mode can only be used effectively with models that are solid throughout so that model doesn't qualify.

**Comment by ilko-k** [comment]
@GregValiant thanks for the reply but I already tried your suggests and every possible things but no, that is not good at all. SuperSlicer is doing well where Cura fails at this point. Maybe it's not purely a bug but there is definitely something wrong in the algorithm

**Comment by GregValiant** [comment]
This is what I get with 4.12.1 with my Ender active.  The .399 line width trick is not something mast new users would think to do.
![Untitled](https://user-images.githubusercontent.com/64202104/146673540-3514926f-a9a0-468b-8807-4623fb480a76.png)

This is what I get from Arachne at .4 line width.
![AUntitled](https://user-images.githubusercontent.com/64202104/146673626-ccdbc78f-a243-4edc-be0f-93ce8fdecdd0.png)

In neither case do they look very much like that first slice you showed.  (This old laptop doesn't support OpenGL 4.1 and so my display is in Compatibility Mode).
If you could do a "File | Save Project" and zip and post the 3mf file it would provide more info.

**Comment by ilko-k** [comment]
Just so you know, I'm printing / modeling since years so I'm a little bit experienced. I'm maybe missing something. This is the best I can get but still not good.
![image](https://user-images.githubusercontent.com/5411848/146674450-b98303c6-edb4-4fdc-9848-7f07719a0a83.png)

I attached the project file. Thanks in advance for the help.
[Caliset-Flow_1_perimeter.zip](https://github.com/Ultimaker/Cura/files/7740765/Caliset-Flow_1_perimeter.zip)
.

**Comment by GregValiant** [comment]
Try changing your Outer Wall Inset to 0 and re-slice.
The model on the left has Outer Wall Inset at 0 and the one on the right is set to .005 in the per model settings.
![image](https://user-images.githubusercontent.com/64202104/146675169-c8f0cb48-3f4f-42e8-9f32-ed719f6dc0ca.png)

**Comment by ilko-k** [comment]
oh well, I had never took attention at this particular setting. Now this is what I get :
![image](https://user-images.githubusercontent.com/5411848/146677442-b3020b00-cddc-47b7-932c-c2c4fa0c313a.png)

It seems fine. Thank you very much for your time.

**Comment by GregValiant** [comment]
I'm not sure but it seems that like "Remove All Holes" and "Make Overhangs Printable" the Outer Wall Inset appears to be for very specific cases and combinations of settings.  This is the first time I've noticed what it actually does.

**Comment by ilko-k** [comment]
hmm interesting, I've never played with these settings before since I did not need any of them. Combining "Remove holes" with regular 0.4 mm line width also gives a good slice result. It adds a few extra internal lines on the uppermost layer of the ground though.
![image](https://user-images.githubusercontent.com/5411848/146684281-ee780380-0461-4130-abe9-7303d7a7f4a9.png)

**Comment by Ghostkeeper** [comment]
The printing of small walls was not ideal, but I consider this fixed in Cura 5.0.
