### ISSUE TITLE
Multiply Frozen. 

### ISSUE THREAD

**Issue by CaudillHotshot** [Ultimaker/Cura#11099]
### Application Version

4.12.0

### Platform

MACos12.0.1

### Printer

ender 3 pro

### Reproduction steps

imported design, right click, multiply item selected. item will not load. will have to reload manually using file import to multiply 

### Actual results

shows placing and multiplying, yet never actually multiplies items in Cura. 

### Expected results

items should multiply on build plate. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

seems as though any stl file will have this happen to it.

**Comment by nallath** [comment]
This is fixed for 4.12.1
