### ISSUE TITLE
[FR] Better handling of print height when printing in sequence

### ISSUE THREAD

**Issue by BloodyRain2k** [Ultimaker/Cura#11091]
### Is your feature request related to a problem?

Currently, printing in sequence is only possible with Cura, if ALL parts to be printed are below the gantry clearance.

This is of course the easiest way to ensure that the printer won't navigate into the prints.

However, there's 3 changes I'd like to request to improve on this, each with a more difficult amount of work implied, so I'll start with the easiest:

### Describe the solution you'd like

1) Manual override: there are the shadow outlines on the virtual print bed, which I assume outline the predicted clearing needed for the part.
This allows it to move parts to opposite corners of the print area and have them mostlikely be fine if printed.
The only 2 things missing for that would be a manual override to still generate the GCode, and on top of that have the head move to a height at the end of the print so that XY movement won't risk knocking the head into the prints.

2) Allow one "too high" part be printed by printing it last.
Depending on how the slicing logic is built, this might be actually the easiest one, but I have no insight on that.
But if there are 5 parts to be printed and only the 5th of these is higher than the clearance, then there should be no problem printing all 5 in one run by just printing the too high part last.
All previous parts should still be below the clearance and therefore fine.

3) Advanced gantry clearance checks: this would be the end goal: by extending the measurements that can be defined for printers, Cura could estimate the clearing left on the print area with the whole gantry.
Meaning not just the size and height of the head but also the width and clearance of the gantry it runs on.
This could then be used to have prints be allowed to be "stacked" behind each other.
Similar to the 1st, but here Cura would know the space free below and on the sides, where as the first just blocks the whole X space for the used up Y length.

### Affected users and/or printers

Aside of the 1st option, would this mainly focus on Core XY and bed slinger printers.

Simply because I assume that Delta clearance is either more difficult to estimate or just much more limited in where "free space" remains.

**Comment by fvrmr** [comment]
Hi @BloodyRain2k thank you for your feature request. 
Al your 3 solutions are duplicates of existing issues.
Solution 1: https://github.com/Ultimaker/Cura/issues/4835
Solution 2: https://github.com/Ultimaker/Cura/issues/6627
Solution 3: https://github.com/Ultimaker/Cura/issues/7403

So I will close this issue and mark it as a duplicate.
