### ISSUE TITLE
Setting retractions... (possibly incorrect length retraction)

### ISSUE THREAD

**Issue by landway** [Ultimaker/Cura#1109]
When i updated FW on UM2+ from CURA 2.3. I can reed on display lenght retraction 6,5 mm. Is it correct? Because in past it was 4,5 mm...

**Comment by thopiekar** [comment]
@Ghostkeeper ping

**Comment by Ghostkeeper** [comment]
No, it should be 6.5: https://github.com/Ultimaker/UM2.1-Firmware/blob/UM2.1_JarJar/Marlin/ConfigurationStore.cpp#L296

This seems to have changed in April. Perhaps the Cura2.1 firmware was made just before that. That would've been bad planning on our part.

**Comment by landway** [comment]
So, which value is right? 4,5 mm? 6,5 mm?

**Comment by Ghostkeeper** [comment]
6.5mm is correct. It was tested extensively with 6.5mm.
