### ISSUE TITLE
Setting Panel

### ISSUE THREAD

**Issue by Vaibhavkhakkar** [Ultimaker/Cura#11103]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

Setting box not expanding. 

### Actual results

Setting box not expanding. 

### Expected results

Setting box not expanding. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Setting box not expanding.

**Comment by fvrmr** [comment]
Hi @Vaibhavkhakkar thank you for your report.
Could you maybe share a screenshot/video of what is happening? 
And could you also share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5527.
