### ISSUE TITLE
"Duplicate object" option should allow "multiply object" like previous Cura

### ISSUE THREAD

**Issue by partsoven** [Ultimaker/Cura#1111]
I noticed in this version 2.3.0 of Cura that the "Multiply object" has been changed to "Duplicate object". If I am making 50 of the same part on the same build this becomes very time consuming to click this over and over. I liked the old version where you could type in exactly how many duplicates you wanted and it would populate them automatically.

**Comment by nallath** [comment]
This is not a change in 2.3, this is a change in cura 2.x (2.1 also had a duplicate).

The issue is on our internal tracker, but we have no release assigned yet.

**Comment by Ghostkeeper** [comment]
Duplicate (or multiplication?) of https://github.com/Ultimaker/Cura/issues/282

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/1116

**Comment by fieldOfView** [comment]
This one can be closed
