### ISSUE TITLE
program not slicing to gcode.

### ISSUE THREAD

**Issue by mrplasticcup** [Ultimaker/Cura#11129]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Creality ender 3

### Reproduction steps

Tried to save.stl file and slive to g code.  program stated there was an error.

### Actual results

Nothing happened and there seemes to be something wrong with the file.

### Expected results

File should have been saved to gcode.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/96636909/147373946-66326328-8273-46c6-b72a-50fcdf16b11f.png)

**Comment by Vandresc** [comment]
Hi @mrplasticcup, could you please share a project file so we can try to reproduce it? Thank you!
File>Save project (you will probably need to zip the file first)

**Comment by mrplasticcup** [comment]
Small file.  Saved project from Cura.
    On Monday, December 27, 2021, 07:29:39 AM PST, Vandresc ***@***.***> wrote:  
 
 


Hi @mrplasticcup, could you please share a project file so we can try to reproduce it? Thank you!
File>Save project (you will probably need to zip the file first)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rburema** [comment]
Hello @mrplasticcup 
Attaching via email doesn't work (sadly) you need to attach the file via the github website itself.
