### ISSUE TITLE
Printer profiles do not show up if there is another printer with the same manufacturer but different letters are capitalized

### ISSUE THREAD

**Issue by MicobyteMichael** [Ultimaker/Cura#11125]
### Application Version

4.11

### Platform

Windows 10

### Printer

N/A

### Reproduction steps

When adding a custom machine definition to the `resources/definitions folder`, if there is another machine definition that has the same manufacturer, if the two printers use different capitalizations of the manufacturer's name (i.e. FlashForge vs Flashforge), then the printers that have the manufacturer's name capitalized differently do not show up in the "add non-networked printers" UI.
I was trying to use [Eugr's FlashForge Creator Pro profile](https://github.com/eugr/Flashforge-for-Cura) to set up this printer. I installed it according to the steps on that GitHub page (copy-pasting the files into the Cura configurations folder, installing the plugin, and restarting Cura), but the printer wasn't showing up. After about half an hour of pulling my hair out, I realized that, in the list of printers, there was a Flashforge Dreamer printer. Upon looking more closely, I noticed that it spelled FlashForge with the second F lower-case. On a whim, I figured "why not, I might as well try to see if that would fix it", and lo and behold, I edited the config file to spell FlashForge with the second F lower-case, and *boom*, my Creator Pro suddenly appeared.

### Actual results

If the printer's manufacturer's name is capitalized differently from another printer with the same manufacturer, then it doesn't show up in the "Add non-networked printer" UI. When the capitalization is edited in the definition file to match the other printer, the printer appears.

Original definition file:
![capital-f](https://user-images.githubusercontent.com/10109958/147299087-2922edbf-46cd-442e-89ee-8c428fc55db2.PNG)

Printer does not show up:
![missing-creator-pro](https://user-images.githubusercontent.com/10109958/147299095-960320ee-0ab9-4cdd-9217-2e92e85c9020.PNG)

Made the F lowercase:
![made-f-lowercase](https://user-images.githubusercontent.com/10109958/147299106-c08dc140-59e0-454d-bd77-2a2979a83af9.PNG)

Printer shows up in the list now:
![it-shows-up-now](https://user-images.githubusercontent.com/10109958/147299128-e1370608-27b8-47a4-b983-90cbd0c975fa.PNG)

### Expected results

The printer should have showed up in the "Add non-networked printers" UI regardless of the capitalization differences of the manufacturer's name.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Log file, in case it helps in any way: (I already `grep`'d it for anything that might be relevant, such as "FlashForge", "Creator", "Pro", etc. and found nothing, but just in case it helps somehow.)
[cura.log](https://github.com/Ultimaker/Cura/files/7771780/cura.log)

**Comment by rburema** [comment]
I'll put it on the list to discuss with colleagues. We'll keep you informed.

**Comment by MicobyteMichael** [comment]
Thank you, please feel free to let me know if there is anything else I can do to help, or any other details I can provide.
