### ISSUE TITLE
Cura don´t connect USB pen drive

### ISSUE THREAD

**Issue by Javier7619** [Ultimaker/Cura#11131]
### Application Version

4.12.1

### Platform

Ubuntu

### Printer

Ultimaker 5

### Reproduction steps

1. Import file
2. Slice it
3. Can´t save in usb pen drive. Cura don´t autodetect it.

### Actual results

I can´t print file

### Expected results

I want print it

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don´t know how I can solve it.

**Comment by rburema** [comment]
If it is really a problem with detection, you can work around it by doing 'save to file', then navigating to the USB drive.

If it doesn't show up there, it's likely to be a problem with your OS or USB drive.

Even if it does 'save to file' by default, there should be an arrow next to/on top of the action-button. Is that showing for you? Can you show a screenshot?
