### ISSUE TITLE
will not eject sd card after upgrading to Windows 11

### ISSUE THREAD

**Issue by jstinnett** [Ultimaker/Cura#11135]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

Teveo Tornado

### Reproduction steps

saved file(s) just fine but when I hit eject it gives me an error. 
"Failed to eject 3D Printer another program maybe using this device"
I have nothing else running but cura. Not sure if this is a Cura problem or windows 11. I just updated both.

### Actual results

Not ejecting via cura

### Expected results

sd card should be ejected

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by fvrmr** [comment]
Hi @jstinnett thank you for your report.
Could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
