### ISSUE TITLE
Tree support - doesn't honor support bottom distance

### ISSUE THREAD

**Issue by mslucass** [Ultimaker/Cura#11136]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Ender 3 v2 - BTT MKS-2 motherboard - Marlin firmware

### Reproduction steps

slice with different settings

project: with normal support does have an empty line at print line 10
The project with tree support doesn''t have this =>  result melted support against the main print

### Actual results

Print line 10 should have a empty line but with thee support does print something. result difficult to remove

### Expected results

an empty print line

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Cura 4.12.0.zip](https://github.com/Ultimaker/Cura/files/7779372/Cura.4.12.0.zip)

**Comment by Ghostkeeper** [comment]
Indeed, I can reproduce this again. We [fixed this at some point](https://github.com/Ultimaker/CuraEngine/pull/1288/files), but it seems to have regressed.

**Comment by fvrmr** [comment]
We have created a ticket on our backlog for this.
Devs see CURA-8874

**Comment by mslucass** [comment]
You can close this issue

Maurice

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MariMakes** [comment]
Thanks for the update 😊
I'll close the issue
