### ISSUE TITLE
Cura 2.3.0 Appimage does not react on any Keyboard Input

### ISSUE THREAD

**Issue by argo2445** [Ultimaker/Cura#1113]
I use the AppImage version of Cura because of [https://github.com/Ultimaker/Cura/issues/1094](url) on Ubuntu 16.10. 
I used it with my older config files. Now I want to change some printing settings but it is not possible. Cura does not react on any keyboard input. I just tried a virtual keyboard application. It does not help either.

**Comment by awhiemstra** [comment]
If you start the AppImage with `QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb ./Cura-2.3.0.AppImage` keyboard input should work again. This is a known issue that has been fixed for the 2.3.1 AppImage which will be released soon.
