### ISSUE TITLE
Error Clould not load : File Profilespage.qml / SettingVisibilltypage.qml 

### ISSUE THREAD

**Issue by Golf3gti1** [Ultimaker/Cura#11134]
### Application Version

4.12.1

### Platform

Win10 

### Printer

Genius, Sovol 

### Reproduction steps

I only wanted to save a profile of a created material. 

### Actual results

this error message appeared 

### Expected results

Save a profile from the material [](url)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7776966/cura.log)
![Cura](https://user-images.githubusercontent.com/96671197/147408003-8cee8414-4c37-427c-b57c-941cde915bc3.png)
![Cura12](https://user-images.githubusercontent.com/96671197/147408020-32f1bf28-24ec-46dc-9248-740b8d3ad870.png)

**Comment by rburema** [comment]
If you go to that file in explorer (or at least the parent folder), is that file indeed still there?

If so, how are the permissions set? Was Cura installed as 'administrator'?
