### ISSUE TITLE
Slicing failed with unexpected error.

### ISSUE THREAD

**Issue by PernelSned** [Ultimaker/Cura#11132]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

Custom FFF

### Reproduction steps

1. Import .STL
2. Slice Model

### Actual results

Slicing failed with unexpected error.

### Expected results

Gcode.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7776348/cura.log)
[Project.zip](https://github.com/Ultimaker/Cura/files/7776366/Project.zip)
![Untitled](https://user-images.githubusercontent.com/6433867/147395425-6fc5128c-8271-4b95-b9b5-abb1a84483af.png)

**Comment by rburema** [comment]
Thanks for the report, I can confirm this happens in 4.12.x, 4.13-BETA. and even an early preview of 5.0/Arachne (beta 2).

The model itself is proper (not broken and has correct normals), so it can't be that.

I'll add it to the list of things to discuss with colleagues.

**Comment by fvrmr** [comment]
We have discussed it and created a ticket on our backlog for this bug.
Devs see CURA-8861

**Comment by nallath** [comment]
The odd thing is, I can't reproduce this on the beta or on the latest 4.13 on Linux...

**Comment by nallath** [comment]
I've managed to reproduce this on windows. It turned out that you had set the max retraction count to a value that caused the crash. If you change it to something lower (eg: 999999999) it will work. 

In the next release, the interface should also prevent one from entering too large numbers. Thanks for reporting it!
