### ISSUE TITLE
Custom PLA setting not updated

### ISSUE THREAD

**Issue by StuartP34** [Ultimaker/Cura#11148]
### Application Version

4.13

### Platform

windows 10 64bit

### Printer

Anycubic Vyper

### Reproduction steps

Created Custom PLA with material temp 195
Changed to existing eSun Purple PLA
Changed back to custom PLA

### Actual results

Created Custom Silver PLA with material temp 195
Changed to existing eSun Purple PLA - temperature changed to 200 automatically (profile temp)
Changed back to custom Silver PLA temp did not change to 195, instead remained at 200.

### Expected results

Temps did not change but retraction speed did change to the speed used in custom silver Pla profile.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no files to add

**Comment by fvrmr** [comment]
Hi @StuartP34 thank you for your report. 
I could not reproduce your issue. Could you share your material profile?
