### ISSUE TITLE
"Alternate Extra Wall" and "Ironing" interfers 

### ISSUE THREAD

**Issue by nicklsss** [Ultimaker/Cura#11144]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Custom FFF

### Reproduction steps

I turned on "Ironing" and "Alternate Extra Wall"

### Actual results

I was printing an object with 300 layers, but when I went into the preview, I noticed that it was ironing at every layer (look at the linked picture). This means that it will iron about 150-170 times instead of just on top of the print. 
I do know that there is an option to "Iron only at highest layer", but I need it to iron all of the top surfaces, so I cant use this option.

Also, the part usually takes 3 hours, but with ironing enabled it took 4.5 hours.

![CURA BUG](https://user-images.githubusercontent.com/55872512/147577808-57c702a7-3967-4569-a518-547a45d51617.png)

### Expected results

I expected it to only iron the top layers and top surfaces and NOT iron in the middle of the part.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![CURA BUG](https://user-images.githubusercontent.com/55872512/147578323-5e7e6d1c-364e-4217-9ad9-093985fc1895.png)

**Comment by fvrmr** [comment]
Hi @nicklsss thank you for your report. 
Could you share your project file (file - save project) in a .zip here on Github?
I can't reproduce this with your reproduction steps.
