### ISSUE TITLE
Surface mode gaps (4.13 beta regression)

### ISSUE THREAD

**Issue by galvanized** [Ultimaker/Cura#11147]
### Application Version

4.13.0 BETA

### Platform

Windows 10

### Printer

Creality Ender-3 Pro

### Reproduction steps

- Using Planeprint test print (["Wingtest PLA"](https://www.planeprint.com/print))
- Use default profile "Standard Quality - 0.2 mm" but with Surface Mode set to Surface

### Actual results

Intermittent missing layers on internal features when using surface mode on 1.13.0 BETA.
![image](https://user-images.githubusercontent.com/1581628/147596489-905bbd9a-1ce0-43b1-8c34-82adcae6e35a.png)
1.12.1 shown on left, 1.13.0 BETA shown on right

### Expected results

Behavior in 1.12.1 and earlier is as expected. Problem appears in 1.13.0 BETA.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project files: [Wingtest Comparison.zip](https://github.com/Ultimaker/Cura/files/7785979/Wingtest.Comparison.zip)

**Comment by prometheanprints** [comment]
I am having same issues and even reverting to previous version of cuts causers other problems like connection over wifi to printer and sub extrusion on outer walls.

**Comment by Vandresc** [comment]
Hi @galvanized thank you for your feedback, we will look into it.
Devs, see CURA-8860 for our internal reference.

**Comment by Vandresc** [comment]
@prometheanprints , we are not aware of any connection issues, could you please create a ticket and fill in the bug template? Many thanks!

**Comment by rburema** [comment]
Cherry-picked the fix commit for this to 4.13.0-final

Cause as determined and fixed by @casperlamboo was an extra call to simplification of open polylines introduced after 4.12.x
