### ISSUE TITLE
Skirt  Line Count (1 = 2 )

### ISSUE THREAD

**Issue by Sekisback** [Ultimaker/Cura#11146]
### Application Version

4.13.b

### Platform

Linux

### Printer

Ender 3

### Reproduction steps

decreased the number of skirt lines to 1, will produce 2 skirt line
![Bildschirmfoto_2021-12-28_17-00-19](https://user-images.githubusercontent.com/24872777/147589560-ebdcce08-297b-44e8-b643-eb2dc2bb0cd4.png)
s

### Actual results

the skirt line will be 2

### Expected results

skirt line = 1

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[fussleiste_gerade_PLA_NZ-04_LH-02.zip](https://github.com/Ultimaker/Cura/files/7785691/fussleiste_gerade_PLA_NZ-04_LH-02.zip)

**Comment by WhiteRabbit56** [comment]
If you enable the option "Skirt/Brim Minimum Length" and lower that from 250 mm does it still produce two skirt lines for you?

**Comment by Sekisback** [comment]
you are right, the bug was in front of the screen
