### ISSUE TITLE
Modifier mesh should allow 0 perims setting

### ISSUE THREAD

**Issue by jaggzh** [Ultimaker/Cura#11155]
### Is your feature request related to a problem?

With modifier meshes, while we can adjust perimeters count/thickness, we can't set them to 0.

### Describe the solution you'd like

Allowing a modifier mesh to set perims to 0 will allow us to "remove" surfaces of a model.
The goal of this, in the present use-case, is to allow the Lightning infill to be used for hollow shells, until Lightning supports are available.

![image](https://user-images.githubusercontent.com/20318973/147684428-a0aec2ab-3f59-4a22-85d5-2a56f238c85d.png)
Here's a mouse cover I have to print in parts (or it's an impossibly large amount of support structure, and quite a mess to clean up).

![Screenshot_20211229_084045](https://user-images.githubusercontent.com/20318973/147684525-52a5bba9-5cac-461f-85e1-1a14b995184d.png)
Here's part of it, with a test modifier mesh to remove the perimeters off part of it, so lightning supports can handle the top overhangs of the lilac-colored part.

![Screenshot_20211229_084154](https://user-images.githubusercontent.com/20318973/147684619-d4972a5d-6eac-45dc-a8c5-f14d79b0cfe5.png)
Here you can see Cura considers the 0.0 settings invalid.
(The 50% infill was just to visualize the area to ensure it was being affected by the modifier mesh).

### Describe alternatives you've considered

I don't know an alternative to this -- not until we get Lightning supports.

### Affected users and/or printers

(This is not directly related to a specific printer.)

**Comment by jaggzh** [comment]
The idea would be to have removed the perimeters of the object, so Lightning infill could support just the top:
![Screenshot_20211229_085644](https://user-images.githubusercontent.com/20318973/147685895-beb30a48-8a7e-4196-9dc7-0d8ed5e5bbd8.png)

**Comment by fvrmr** [comment]
Hi @jaggzh thank you for another feature request.
When using the infill mesh only in modify settings for overlap it will only affect the infill. You can select cutting mesh and set wall thickness to 0 it will not print your wall where the modifier mesh overlaps with your model. 
For the lightning infill you can change the lighting infill support angle to a higher value to just support the top. 

Let me know if that could work for you.

**Comment by Ghostkeeper** [comment]
> Here you can see Cura considers the 0.0 settings invalid.

This is not true. It colours it orange, indicating that it expects that it will not print well. But it does allow you to slice and print it.

And that seems to work correctly with your use case:
![image](https://user-images.githubusercontent.com/2448634/148230349-cc82a225-2a5d-4dcb-afab-c21bbdfad174.png)

It does, of course, suffer a the problem I outlined [here](https://github.com/Ultimaker/Cura/issues/11151#issuecomment-1005592738). The lightning infill lines will hang in mid-air since they try to attach to the side of the infill area.
