### ISSUE TITLE
Cura unusable on macos m1 max

### ISSUE THREAD

**Issue by mac190** [Ultimaker/Cura#11154]
### Application Version

4.12.1, 4.13.0 beta

### Platform

macOS 12.0.1

### Printer

none

### Reproduction steps

import big model
or
scale a big model
or
move a big model
or
rotate a big model
or
slice a big model

* by big I am saying 70mb+ (or two models on plate)

### Actual results

I get rainbow spinner of death with posibility to force quit application. It just freezes while performing a simple operation on model.

### Expected results

It actually do every single thing that i tried in reproduction steps as it was doing on intel macs.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Guys, in some short time m1 will be gaining popularity, such reports will come out more and more frequently. :) cheers

**Comment by fvrmr** [comment]
Hi @mac190 thank you for your report.
We officially don't support M1 yet, see this article: https://support.ultimaker.com/hc/en-us/articles/360018141480-Ultimaker-Cura-is-not-fully-compatible-with-the-Apple-M1-chip
To know what is happening with your issue a log file could be really helpful. 
You can find your log file here: `$HOME/Library/Application Support/cura/<Cura version>/cura.log`
