### ISSUE TITLE
Top Surface Skin Layer not working in arachne beta 2 99.10.0

### ISSUE THREAD

**Issue by TwomD** [Ultimaker/Cura#11157]
### Application Version

arachne beta 2 99.10.0

### Platform

win 10

### Printer

ender 3 pro

### Reproduction steps

i cant get the top surface skin layer to work in the Arachne beta. it ignores all settings for the top surface skin layer and just uses the "normal" top layer settings.

if i save the project as a *.3mf and open it in cura v 4.12.0 it works and it uses the right settings ( 1 top surface skin layer, slower speed, different line with )

is this a known bug ? ( couldn't find anything about it )

### Actual results

arachne: 
![Top Surface Skin Layer_cura arachne](https://user-images.githubusercontent.com/81984193/147703693-126acee6-6f50-4f41-b782-c743e6e3413c.jpg)

### Expected results

cura 4.12.0:
![Top Surface Skin Layer_cura 4_12_0](https://user-images.githubusercontent.com/81984193/147703715-cea3f3c7-ead7-4f10-9a73-befd99b02682.jpg)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

the project file:
[CE3PRO_Lüftungsschlauch Durchführung _ teil1.zip](https://github.com/Ultimaker/Cura/files/7790641/CE3PRO_Luftungsschlauch.Durchfuhrung._.teil1.zip)

**Comment by fvrmr** [comment]
Hi @TwomD thank you for your bug report. 
We discovered this as well and have ticket on our backlog related to this. 
I will link this to our ticket.
Devs see CURA-8839

**Comment by TwomD** [comment]
Good to know :)

**Comment by fvrmr** [comment]
This should be fixed in the 5.0 release: https://github.com/Ultimaker/Cura/releases/tag/5.0.0
So closing this issue!
