### ISSUE TITLE
Uneven Z seam and stuttering with simple model in Arachne beta

### ISSUE THREAD

**Issue by daniels220** [Ultimaker/Cura#11150]
### Application Version

Arachne engine beta 2

### Platform

MacOS Big Sur

### Printer

Creality CR-10s

### Reproduction steps

Okay, so first off, searching around it looks like there is already an issue in your backlog for some of this, but, I think this submission contains greater detail that may be helpful. Similar issues I'm aware of include #8010, #9555, #10181.

I sliced a very simple model—just a thin-walled tapered cylinder (a test piece for a vacuum-hose adapter)—with the Arachne engine beta, and found when I printed it that the printer was making a lot of extraneous travel moves between the two wall lines.

### Actual results

Looking more closely at the preview, the first problem at least is obvious—the start locations of each line jitter significantly between layers and between the two concentric lines:

<img width="541" alt="Arachne-UserZSeam" src="https://user-images.githubusercontent.com/1410866/147632193-6c44026e-1fd7-404b-b5c1-13087f6ec585.png">

That layer is one of the most extreme, with the two concentric lines starting almost a centimeter apart, but all of them have _some_ separation. Frustratingly, nothing I do to the Z seam settings helps, and in fact selecting "Shortest" makes the problem _dramatically_ worse:

<img width="512" alt="Arachne-ShortestZSeam" src="https://user-images.githubusercontent.com/1410866/147632263-2ae25508-c504-4ab8-a1f4-81c54765d717.png">

The worst part—and one I've not seen mentioned elsewhere—is that this applies to the skirt/brim lines as well: each successive line starts in a different place, resulting in the printer making sudden travel moves each time around rather than transitioning smoothly from one line to the next, which can easily knock the brim loose from the bed if adhesion is at all questionable. Not only that, but Arachne will sometimes print skirt/brim lines out of order—that is, numbering the lines with 1 being the innermost and counting upward, I've seen it print 1, 3, 5, 4, 2, leaving gaps and then filling them back in, rather than 1, 2, 3, 4, 5 or 5, 4, 3, 2, 1. This also dramatically increases the chances of knocking the brim loose before it can fully adhere. Changing the adhesion type on this very model to Brim produces that behavior, in fact:

<img width="1012" alt="Arachne-BrimWTF" src="https://user-images.githubusercontent.com/1410866/147632122-973990bd-f99a-4544-bb25-515bde0dfddf.png">

### Expected results

Cura 4.12.1 handles the situation perfectly well:

<img width="583" alt="Cura 4.12 with 'Shortest' Z Seam" src="https://user-images.githubusercontent.com/1410866/147629399-3fc56e81-dba1-4624-8a33-f051c1af05f5.png">

This is with "Shortest" Z seam, and interestingly "User Specified" produces _some_ of the same jitter, depending on the chosen location—front-left produces the exact same result as shortest, and most of the other options are basically fine, but back-right is less than ideal, though still far better than what Arachne produces:

<img width="696" alt="Cura 4.12 with User-Specified Back Right Z Seam" src="https://user-images.githubusercontent.com/1410866/147629643-081fff00-daa0-4156-bb2d-dcc7857cc820.png">

I've experienced having the "layer start position" influence this Z seam jitter in the past, as well—if that becomes relevant I can try to chase down the exact behavior further. Though it seems this is likely explainable by the comments on #8010...

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

All of this was with completely stock settings (I did a full reset of Cura by renaming ~/Library/Application Support/cura), except changes to Z seam settings as indicated.

Raw model: [TaperedHollowCylinder.3mf.zip](https://github.com/Ultimaker/Cura/files/7787419/TaperedHollowCylinder.3mf.zip)

Project as saved by Cura 4.12: 
[Cura412Project.3mf.zip](https://github.com/Ultimaker/Cura/files/7787441/Cura412Project.3mf.zip)

Project as saved by the Arachne beta: 
[ArachneProject.3mf.zip](https://github.com/Ultimaker/Cura/files/7787442/ArachneProject.3mf.zip)

Might as well include the gcode files, though I imagine you can reproduce them: [GCode.zip](https://github.com/Ultimaker/Cura/files/7787497/GCode.zip)

**Comment by fvrmr** [comment]
Hi @daniels220 thank you for your detailed bug report. 
I can reproduce your issue with the seam. I will bring this up with the team.

About the brim see this issue: https://github.com/Ultimaker/Cura/discussions/8965#discussioncomment-237369 and this is indeed still in the second Beta. We have a ticket related to this on our backlog.

The visual lines are also a know issue see: https://github.com/Ultimaker/Cura/discussions/10931#discussioncomment-1748963

**Comment by daniels220** [comment]
Great, thank you.

I realize now that the second issue I mention here, the flow/stuttering issues, should really be, well, a second issue, so I'll edit it out of here and submit it that way.

**Comment by fvrmr** [comment]
I have created a ticket on our backlog for this.
Devs see CURA-8875

**Comment by fvrmr** [comment]
The seam should be better in 5.0 now! So closing this issue. 
Here you can find the builds: https://github.com/Ultimaker/Cura/releases/tag/5.0.0
