### ISSUE TITLE
High CPU consumption even if nothing happens

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#11158]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

Anycubic I3 Mega S

### Reproduction steps

1. After some prints the CPU usage become higher and higher even if Cura is in the background.

### Actual results

![qf4JZGISL9](https://user-images.githubusercontent.com/51311453/147704449-5768e265-a3d3-47ac-85e1-8756d1a4199e.png)

### Expected results

If Cura does nothing it should not consume CPU ressources.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[stdout.log](https://github.com/Ultimaker/Cura/files/7790679/stdout.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/7790681/stderr.log)
[cura.log](https://github.com/Ultimaker/Cura/files/7790683/cura.log)

**Comment by nallath** [comment]
Could you run the special profiling plugin that we made for a while? It will help us figuring out what is causing this. See https://marketplace.ultimaker.com/app/cura/plugins/UltimakerPackages/ExtensiveSupportLogging
