### ISSUE TITLE
Cura 4.2.1 Cannot connect to cura package database through marketplace

### ISSUE THREAD

**Issue by dhoule1102** [Ultimaker/Cura#11168]
### Application Version

4.2.1

### Platform

Windows 10

### Printer

AnyCube Mega Pro

### Reproduction steps

Click on Marketplace Button

![Capture cura 1](https://user-images.githubusercontent.com/96885276/147778076-6afe738c-11e9-426c-9bea-86575c159900.PNG)

### Actual results

Continuously getting popup of Error connecting to cloud

### Expected results

I should be able to access new plugins and materials

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don't do coding, I don't get what ya'll are asking for, Im just trying to access my plugins and materials so I can adjust my settings to continue learning how to use my 3d printer.

**Comment by fvrmr** [comment]
Hi @dhoule1102 thank you for your report. 
Could you try using the Marketplace in Cura 4.12.1? You are using an older version of Cura. 
When installing 4.12.1 you don't have to uninstall 4.2.1

If the problem still persist in 4.12.1 could you then share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
