### ISSUE TITLE
Running Cura from Source on Windows contains dead link

### ISSUE THREAD

**Issue by Penrif** [Ultimaker/Cura#11173]
### Application Version

NA

### Platform

NA

### Printer

NA

### Reproduction steps

On this page:
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Windows
The instructions for getting SIP include a dead link - "Download SIP 4.19.24 from here." pointing to https://www.riverbankcomputing.com/static/Downloads/sip/4.19.24/sip-4.19.24.tar.gz

I clicked it.

### Actual results

404, 'cause it's dead ;)

### Expected results

It appears Riverbank Computing is only hosting 4.19.25 from it's 4.X line.  If that is an acceptable version, the link should be updated to "https://www.riverbankcomputing.com/static/Downloads/sip/4.19.25/sip-4.19.25.tar.gz"

Otherwise, alternative hosting for a 4.19.24 artifact should be found.  I managed to scrounge one up but I cannot vouge for the site so can't recommend linking to them.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Required field is required but not useful in this case.

**Comment by fvrmr** [comment]
Hi @Penrif thank you for your report.
I checked with a colleague and we can indeed use 4.19.25. I updated the link in the Wiki! 
I will close this issue since it is changed!
