### ISSUE TITLE
model toolbar

### ISSUE THREAD

**Issue by jason10012** [Ultimaker/Cura#11176]
### Application Version

4.12.1

### Platform

windows 10

### Printer

cr10s

### Reproduction steps

installed the newest version of cura and I no longer have the side toolbar that allows me to scale, rotate etc and nothing I can find shows it or shows how to make it appear

### Actual results

nothing

### Expected results

have access to the side toolbar

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by nallath** [comment]
Please add the log file.

**Comment by fieldOfView** [comment]
The toolbar only appears when there is a model on the buildplate.
