### ISSUE TITLE
Cura Slicing Error

### ISSUE THREAD

**Issue by ctucker1** [Ultimaker/Cura#11191]
### Application Version

I'm not sure. On the loading screen it says "master"

### Platform

Linux (Raspberry Pi 4b)

### Printer

Ender 5

### Reproduction steps

I designed a new spool holder in Tinkercad and imported it to Cura (as an .stl).

### Actual results

After slicing it (with my normal settings), I got an error saying "Slicing failed with an unexpected error...". 

### Expected results

Instead of getting error, I expected an estimated print time and a button that allows me to save to a disk or removable device.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Here is the project as a .zip file:
[CE5_Spool Holder.zip](https://github.com/Ultimaker/Cura/files/7800652/CE5_Spool.Holder.zip)

Here is a screenshot of the error:
![error_pic](https://user-images.githubusercontent.com/90222874/147904798-0657ecf7-5b02-4794-ad01-4e18b9835e30.jpg)

**Comment by GregValiant** [comment]
The "Master" version is a branch of Cura maintained by @smartavionics.  He may see your report here.  He has his own github site [HERE](https://github.com/smartavionics/Cura/issues).

**Comment by smartavionics** [comment]
Hi, yes, it's my Cura build. Perhaps you are using an old build and a more recent build would be OK. I have just sliced your project on a Pi 4 and it completed OK.

![Screenshot_2022-01-04_07-15-45](https://user-images.githubusercontent.com/585618/148022949-a05a761d-69aa-477f-83ac-89da7a60a5b1.png)

If you continue to have problems, please open an issue on my repo and close this issue so to avoid spamming the UM folks.

**Comment by smartavionics** [comment]
BTW, I see the project is using the Schwarz P infill pattern. That's a bad choice for this print, gyroid would yield a much stronger part and is quicker to print.

**Comment by fvrmr** [comment]
Closing this issue since it is not related to our version!

**Comment by ctucker1** [comment]
Thanks

**Comment by ctucker1** [comment]
I’m sorry for the trouble
