### ISSUE TITLE
Z-hop height is hidden

### ISSUE THREAD

**Issue by reapingminer** [Ultimaker/Cura#1119]
Z-hop height does not show under advanced print settings, even if the checkbox is ticked in the cura settings menu.

**Comment by reapingminer** [comment]
Strange, it just appeared after changing some other settings. (Not related to Z-hop)

**Comment by Ghostkeeper** [comment]
The `Z Hop Height` setting should only be visible if `Z Hop when Retracted` is on and `Enable Retraction` is on. Also, `Z Hop when Retracted` is visible only if `Enable Retraction` is on.

If any of that is not the case, that's a bug.

**Comment by reapingminer** [comment]
I am fairly sure Z-hop when retracted was ticked. I ticked/unticked it a couple of times to see if i could get the Z hop height to show but i couldnt. I just noticed the option was there after i finished setting all other settings as my final check of the settings about 2 minutes later.

**Comment by Ghostkeeper** [comment]
I can't reproduce it. Do you remember what machine/material/quality you were using?

**Comment by uwe999** [comment]
I ran into the same issue today (cura 2.4).
I enabled "z hop only over printed parts" and "z hop height" but it wouldn't show up.
I had to enable "z hop when retracted" before those options would show.
The "Settings visibility" box should indent those 2 options to make it obvious that they are only available when the main "z hop when retracted" has been checked.
