### ISSUE TITLE
Problem When slicing

### ISSUE THREAD

**Issue by JakeMSteers** [Ultimaker/Cura#11200]
### Application Version

4.11.0

### Platform

Mac

### Printer

Creality Ender 3 Pro

### Reproduction steps

-loaded .STL file
-repositioned to where I wanted it to print on the bed
-hit slice
- gets to around 50% then stops

### Actual results

unable to slice file

### Expected results

the file should completely slice giving me a file to save and send to my printer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

STL file can not be added but a screenshot of the error has been attached
<img width="1440" alt="Screen Shot 2022-01-04 at 9 44 49 PM" src="https://user-images.githubusercontent.com/97147600/148166634-ba9152db-c887-4cc7-b730-ff5e176b59f6.png">

**Comment by nallath** [comment]
Please add the log files. Project files can be added if you zip them (as explained in the template).

Could you also try if the issue is also present in Cura 4.12 or (even better) check Cura 4.13-Beta?
