### ISSUE TITLE
Not saving changes in extruder settings

### ISSUE THREAD

**Issue by JediRAMA** [Ultimaker/Cura#11214]
### Application Version

arachne beta 2

### Platform

win10

### Printer

Kosher

### Reproduction steps

im changing number of cooliong fan from 0 to 3 and 5

### Actual results

It works well, but after restart cura changes reset to 0

### Expected results

in cura 4.13 that changes saving after restart cura

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Скриншот 07-01-2022 212116](https://user-images.githubusercontent.com/61805782/148589625-b50709ce-f0b7-4cca-bf59-e8860feb3595.jpg)

**Comment by JediRAMA** [comment]
I added this printer from list in cura. Not custom printer

**Comment by fvrmr** [comment]
I tried it again with your printer, but I still couldn't reproduce your issue. Maybe your log file could help. 
You can find your log file here: C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
