### ISSUE TITLE
Arachne: No infill generated in small cross sections when using extra infill walls

### ISSUE THREAD

**Issue by neutebach** [Ultimaker/Cura#11210]
### Application Version

Arachne Beta 2

### Platform

Windows 11

### Printer

CFFFP

### Reproduction steps

To receive strong parts, more than the standard 2 wall lines may be chosen to increase the wall thickness. The print speed can only be chosen for outer and inner walls, but stays the same no matter how many inner walls there are, adding print time with every further inner wall. I chose to instead add extra infill walls that are then printed at the speed of the infill, allowing for the best compromise between strong parts and print time.

--> instead of a _Wall Line Count_ of 4, only 2 Walls but also 2 _Extra Infill Walls_ are selected.

![arachne-3](https://user-images.githubusercontent.com/95223671/148449354-bbbc1e91-532b-4c81-b369-6fc192f2e727.png)

### Actual results

For some small areas, presumably where the infill area is too small to accomodate all perimeters and **extra infill wall**s, there is **no infill generated** at all, when the above mentioned settings are in place (2 perimeters/walls, 2 extra infill walls).

![arachne-4](https://user-images.githubusercontent.com/95223671/148449448-23e49529-1896-486c-8ca5-9b620773710a.png)

![arachne-6](https://user-images.githubusercontent.com/95223671/148449482-04cc5a32-a8bb-4098-b100-5b11f35202b4.png)

Infill is however generated in these areas when **no extra infill walls** are selected:

![arachne-8](https://user-images.githubusercontent.com/95223671/148449750-c59f623a-e299-4ab1-bc86-049c3bdaea6a.png)

### Expected results

Similar to what is output when **4 walls, but no extra infill walls** are selected (see images below), I would expect the extra infill walls to be placed inside the perimeters so that the area is filled. When the area cannot accomodate all extra infill walls, only the necessary amount of walls should be drawn, instead of the infill being omitted completely.

![arachne-5](https://user-images.githubusercontent.com/95223671/148450120-f8ea263b-e5a4-4417-afc1-479b2a30f8f8.png)

![arachne-7](https://user-images.githubusercontent.com/95223671/148450135-6f951520-4de9-4d31-a12e-fbb9fbabf461.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[arachne-demo-project.zip](https://github.com/Ultimaker/Cura/files/7824644/arachne-demo-project.zip)

**Comment by fvrmr** [comment]
Hi @neutebach thank you for your bug report.
I will bring this up with the team for discussion. Keep you posted!

**Comment by neutebach** [comment]
thank you @fvrmr 

I've just found that in some cases, infill with extra walls might be created after all when there is at least one connected area where all infill walls and the infill structure can be created - however this might just be coincidental. Nevertheless I tought I'd share it.

![arachne-9](https://user-images.githubusercontent.com/95223671/148581835-129b6796-7280-4e45-b6ca-f6db206740b9.png)

**Comment by neutebach** [comment]
FWIW after looking at these screenshots again, this encapsules the whole beauty of how arachne is working, it's really amazing when you think back to how the old engine would handle these cross sections. I'm really excited for Cura 5, keep up the great work!

**Comment by fvrmr** [comment]
I have discussed it with the team and turns out we already got a ticket related to this. I will link this issue to the ticket on our backlog. 
Devs see CURA-8067
