### ISSUE TITLE
Multiplying Objets

### ISSUE THREAD

**Issue by MiguelEro** [Ultimaker/Cura#11211]
### Application Version

4.11.0

### Platform

mac

### Printer

Ender 3 Pro

### Reproduction steps

Try to multiply an object several times

### Actual results

Nothing happend, but a label on the screen keepts always saying :
"Multiplying and Placing Objects"
![image](https://user-images.githubusercontent.com/97259760/148458353-3a5c4037-955a-4b8d-bc28-5d78cf4ab750.png)

### Expected results

Multiplyed objets appears on working area

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[icableguards-read-description-by-3dmx.zip](https://github.com/Ultimaker/Cura/files/7824976/icableguards-read-description-by-3dmx.zip)

**Comment by MiguelEro** [comment]
I Update to 4.12.1 Version and Works fine.

**Comment by Ghostkeeper** [comment]
Indeed, this was one of the reasons we put out version 4.12.1 (over 4.12.0).
