### ISSUE TITLE
Cura 4.13.0-BETA recommending me to update to 4.13.0-BETA

### ISSUE THREAD

**Issue by hapklaar** [Ultimaker/Cura#11229]
### Application Version

4.13.0

### Platform

WIndows 10

### Printer

Biqu B1

### Reproduction steps

Start Cura 4.13

### Actual results

Observe popup below" Ultimaker Cura 4.13.0-BETA is available!"

![image](https://user-images.githubusercontent.com/7703320/148695803-e74e342d-6309-4a2e-8ac5-4a8af40301f0.png)

![image](https://user-images.githubusercontent.com/7703320/148695793-c9ebf5bd-e1a6-4386-968b-268c08c9fec3.png)

### Expected results

Don't recommend upgrading to version 4.13.0-BETA when that version is already being used.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7835670/cura.log)

**Comment by fvrmr** [comment]
Hi @hapklaar thank you for your report. 
We discovered this as well and have ticket on our backlog for this. 
Devs see CURA-8856

**Comment by Jarren141** [comment]
I'm also seeing this on 5.0.0-beta+1

**Comment by fvrmr** [comment]
Closing this issue, since it is fixed for next beta releases!
