### ISSUE TITLE
cannot open "help/show configuration folder"

### ISSUE THREAD

**Issue by amills1982** [Ultimaker/Cura#11226]
### Application Version

4.12.1

### Platform

ubuntu 20

### Printer

ender 3

### Reproduction steps

click help
click " show configuration folder"
nothing happens
trying to install "createJPEGthumbnail.py" script

### Actual results

nothing happens
trying to install "createJPEGthumbnail.py" script

### Expected results

config folder should open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

works fine on 4.4.1

**Comment by fvrmr** [comment]
Hi @amills1982 thank you for your report.
Are you using the AppImage?

**Comment by amills1982** [comment]
It’s the snap installer, I’m going to pause this (for me) for the moment as I’m going to install mint tonight and try cura on that os

Sent from my iPhone

On Jan 10, 2022, at 8:27 AM, Allen Mills ***@***.***> wrote:

﻿ Snap

Sent from my iPhone

On Jan 10, 2022, at 5:54 AM, Fenne ***@***.***> wrote:

﻿

Hi @amills1982<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famills1982&data=04%7C01%7C%7C93868d45245540fb153608d9d4279515%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774088733642287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=giMldQHZ34Jgzpcxfs%2FIlCyEp1K6dFqkWdqY%2B%2FSuKpY%3D&reserved=0> thank you for your report.
Are you using the AppImage?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11226%23issuecomment-1008753246&data=04%7C01%7C%7C93868d45245540fb153608d9d4279515%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774088733652262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ip4DxTJpzHf%2BAuREGbZSPsafangwWywsIjcKwBO1yto%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALDLQ2ELS6MCJF2DQQZGKC3UVK3GPANCNFSM5LRRN6SA&data=04%7C01%7C%7C93868d45245540fb153608d9d4279515%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774088733652262%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=glQWV4MxI9lFKTS4SF8hrMAW7XYJeTP%2F1qUyHgPGdy8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C93868d45245540fb153608d9d4279515%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774088733662195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m%2Fp%2FXbr8E9Tsl76ElP1KZAvE3L7Q%2BQrkkWBQOGdGaxM%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C93868d45245540fb153608d9d4279515%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774088733662195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HI%2FhYFMkhwnSaVRNgYw74%2BxlpnjCdo05Be%2BRiMjESas%3D&reserved=0>.

**Comment by fvrmr** [comment]
Thank you for your reply. I will close this issue since it is not an issue with our AppImage. Please report your issue to the maintainer of this package.

**Comment by amills1982** [comment]
Installed mint last night. Cura config folder is accessible. Ty for your responses

Sent from my iPhone

On Jan 11, 2022, at 5:33 AM, Fenne ***@***.***> wrote:

﻿

Closed #11226<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11226&data=04%7C01%7C%7C6a00992e57334e29283508d9d4eddb34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774940323226521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h34r9tbcQZw92yZMxEv6wPCG0iEHOfk5XUcD47QCh08%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11226%23event-5872059821&data=04%7C01%7C%7C6a00992e57334e29283508d9d4eddb34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774940323236478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pymTc8JUQB98JwtApd23Spn8OeYV55B9%2BX4lyHrHYKM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALDLQ2HXJJIOQMQUF7FJUQLUVQBQZANCNFSM5LRRN6SA&data=04%7C01%7C%7C6a00992e57334e29283508d9d4eddb34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774940323236478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uBRXLwc12DzCS0Ovm4s6XQ40Q8J6cOF%2FlOUATtmWZAI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6a00992e57334e29283508d9d4eddb34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774940323246434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LrO%2Bs9K7jX3Z7a5nrMWzQd8fqzriS3Mh7p%2BQ39Fpubk%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6a00992e57334e29283508d9d4eddb34%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774940323246434%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y6QIemGJtLDJzvES%2FANymDwa%2FhMwHVMjfR7zepoPshU%3D&reserved=0>.
