### ISSUE TITLE
Cura 4.12.1 says there is an error when I try to load a file.   It worked last week, but happened occaisionly.  I have reloaded Cura and it it not working??

### ISSUE THREAD

**Issue by SOUTHMTNPHIL** [Ultimaker/Cura#11224]
### Application Version

4.12.1

### Platform

windows 10

### Printer

Ender3v2

### Reproduction steps

Tried to open file.   Never even get to select file to open.   Immediately says - error.

### Actual results

Cura 4.12.1 says there is an error when I try to load a file.   It worked last week, but happened occasionally.  I have reloaded Cura and it it not working??

### Expected results

open file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by fvrmr** [comment]
Hi @SOUTHMTNPHIL thank you for your report.
Does this happen with every file you want to import? Could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
