### ISSUE TITLE
Fill pattern

### ISSUE THREAD

**Issue by hanheik** [Ultimaker/Cura#11233]
### Is your feature request related to a problem?

no problem

### Describe the solution you'd like

![3d-haus-3d-druck](https://user-images.githubusercontent.com/94489999/148760368-0c008a3f-11c5-4b2a-96ef-8661c2515bbf.jpg)
Hi, i think a pattern like they use for 3D-printing houses would be helpful for cylindrical objects. Just a line connecting the inner and and outer wall.
ys
HHK

### Describe alternatives you've considered

no alternatives

### Affected users and/or printers

all users

**Comment by fvrmr** [comment]
Hi @hanheik thank you for your feature request.
You can do this with the zig zag infill pattern.
![Capture-infill](https://user-images.githubusercontent.com/77000924/149367278-60415778-33c5-45de-a799-03220a38f784.PNG)
Select zigzag as infill pattern and change the infill direction with one value so all the lines will go in the same direction.
Let me know if that works for you!

**Comment by fieldOfView** [comment]
Though that somewhat works in the top and right of that model, it does not work in the left.

**Comment by fieldOfView** [comment]
The requested infill would entail finding the centerline (medial axis or topological skeleton) of the area needing infill, and having a sine or sawtooth modulate over that path by the local feature size.

**Comment by Ghostkeeper** [comment]
While it's easy to think of shapes where this infill pattern would be simple, it's hard to think of a way to generate this infill pattern for all shapes. Especially if the model contains splits and a big difference between inner and outer radii this is problematic.

Essentially, this suggestion suffers from the same design problems as https://github.com/Ultimaker/Cura/issues/8811.
