### ISSUE TITLE
希望垂悬部位可以单独调控风扇速度

### ISSUE THREAD

**Issue by v4806** [Ultimaker/Cura#11243]
### Is your feature request related to a problem?

打印ABS的时候，如果不开启或者冷却风扇速度不够大，那么小于45°的垂悬壁部位会很烂，但如果冷却风扇速度太高，又会翘边

### Describe the solution you'd like

如连桥打印的设置一样，可以自定义打印垂悬壁部位的冷却风扇速度，例如：打印abs时，默认是关闭冷却风扇的，当打印到垂悬壁部位时，风扇速度开启到100%，当垂悬壁打印完成之后，再次将风扇关闭，就像连桥设置里单独自定义风扇速度一样。
![20220111181608](https://user-images.githubusercontent.com/97516076/148924342-2136cce4-5e58-43a0-90c7-d7d697d50d09.jpg)

### Describe alternatives you've considered

考虑过全程将冷却风扇速度设置为35%左右，以此来优化垂悬壁打印质量，但这也做，会一定程度导致abs的层间粘合变差

### Affected users and/or printers

使用像abs这类易翘边、收缩率高的材料的每个人

**Comment by fieldOfView** [comment]
Please use english in this issue queue. If we cannot read what you are saying, we cannot help you.

For many of the people helping others in this issue queue, english is not their native language either.  We use english as a common ground. Many of us put in our own time to help you. Please do not also ask us to use a translator to help you.
