### ISSUE TITLE
Pause - Post Processing Plugin caused error

### ISSUE THREAD

**Issue by doncrush** [Ultimaker/Cura#1124]
I got a message that the print head tried to move outside of acceptable range or something to that effect.

I suspect it has to do with the 190 mm default entry for Park Print Head X and Y?

**Comment by thopiekar** [comment]
Can you tell us something about your printer? Cura version? Operating system?

Thanks!

**Comment by Ghostkeeper** [comment]
Perhaps we can park the print head by default on coordinate 0,0 or else just `machine_width - 10` or something.

**Comment by doncrush** [comment]
UM2Go, latest Cura 2.3.1 on Win10.

**Comment by fieldOfView** [comment]
machine_width-10 would be better than hitting the endstops at 0,0. Say the axes have slipped a fraction of a mm; homing the head halfway through the print would then leave a visible line in the print.

**Comment by Ghostkeeper** [comment]
Or `10,10` then.

**Comment by ianpaschal** [comment]
Very old, never got required reproducibility info.
