### ISSUE TITLE
Garbled G code

### ISSUE THREAD

**Issue by Pathoman** [Ultimaker/Cura#11244]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

ANET A8

### Reproduction steps

1. I sliced an object, and stored the g-code on disk.
2. When I attempted to view the code in Cura, it
![kjhgfdsc](https://user-images.githubusercontent.com/97530643/148957363-7612e1bf-357b-4b13-b4b7-2e2f251a8e19.JPG)
![dfghjkl](https://user-images.githubusercontent.com/97530643/148957373-86b0e009-a01d-489b-b1b8-6da406a340dc.JPG)
 

### Actual results

Garbled display.

### Expected results

I should be able to previev my print process

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Hello,

I was Happy with the previous version of Cura, and only experienced this problem after updating to 4.12.
![kjhgfdsc](https://user-images.githubusercontent.com/97530643/148958584-81e36839-f004-45ae-a3f9-d0f369f53d98.JPG)
![dfghjkl](https://user-images.githubusercontent.com/97530643/148958593-e9a6dea7-4173-418b-8f28-76b0156b4f1b.JPG)
1

**Comment by fieldOfView** [comment]
Do you perhaps have the ArcWelder plugin installed and enabled? If so, Cura can not display the arc movements that are now in your gcode.

**Comment by Pathoman** [comment]
Hello,

 

Thank you, that was the problem.

 

Thank you for the help.

 

Regards

 

Patrick Homan

078 712 7534

**Comment by fvrmr** [comment]
Closing this issue, since it is solved!
