### ISSUE TITLE
Tree Support collides with Object

### ISSUE THREAD

**Issue by slewantoski** [Ultimaker/Cura#11258]
### Application Version

4.13.0

### Platform

Windows 11

### Printer

Creality CR-10S Pro

### Reproduction steps

1. import STL
2. enable Tree Support
3. Preview

### Actual results

Until Version 4.12.1 Tree Support worked fine.
Since 4.13.0 the Tree Support collides with the object and can not be removed after printing

I've attached an example file where the problem occurs.

### Expected results

Tree Support should not be printed in the object.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura-log.zip](https://github.com/Ultimaker/Cura/files/7862572/cura-log.zip)
[Project.zip](https://github.com/Ultimaker/Cura/files/7862573/Project.zip)
![Cura 4-12-1 first Layer Preview](https://user-images.githubusercontent.com/50290847/149327860-bbbfee93-ea35-472a-a709-89f9f0b1e6c1.png)
![Cura 4-13-0 first Layer Preview](https://user-images.githubusercontent.com/50290847/149327863-9a3b8da3-9344-4571-940b-13a7f354f84a.png)

**Comment by fvrmr** [comment]
Hi @slewantoski thank you for your report.
We have a ticket on our backlog for this issue. I will link your issue to our ticket!
Devs see CURA-8852

**Comment by ajalberd** [comment]
I can confirm this is an issue with hollow models printed at an angle - the tree supports cut through and merge with the walls making them impossible to remove.

This is not an issue in the 4.13 beta, at least for me.

**Comment by partlyhuman** [comment]
I have some more repro cases for this issue. Attaching a test project.
![image](https://user-images.githubusercontent.com/327136/149428710-f2b01028-6cfc-4b01-ae59-229b1720cb56.png)
[issue-test-project.zip](https://github.com/Ultimaker/Cura/files/7866734/issue-test-project.zip)

**Comment by chipmunk1977** [comment]
Is it possible that this is somehow a Windows issue?  I've tried several models and various settings within tree supports and can't reproduce this at all on a Linux machine.

**Comment by Ghostkeeper** [comment]
I wouldn't think this sort of issue is Windows-specific (but indeed so far all reports for this issue are on Windows). Operating-system-specific issues do exist in CuraEngine, but are pretty rare. In this case it should at the very least remove the intersection of support interface with the model.

**Comment by GregValiant** [comment]
Here is one from the Ultimaker Forum.  Windows 11 and Cura 4.13.
[Issues with Tree Supports](https://community.ultimaker.com/topic/39277-issues-with-tree-supports-on-ender-6-cura-413/#comment-301810)

**Comment by mjquinlan2000** [comment]
I can confirm that tree supports are colliding with the model on macOS 12.1

**Comment by nallath** [comment]
This has been fixed. We will release a 4.13.1 ASAP. Thanks for reporting it :)
