### ISSUE TITLE
Extra Plane when Slicing Parts

### ISSUE THREAD

**Issue by zacharyneveu** [Ultimaker/Cura#11259]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

1. Open the attached project
[bugged_cura_slice.zip](https://github.com/Ultimaker/Cura/files/7863576/bugged_cura_slice.zip)

2. Slice in default orientation (see photo below) without supports (bug also appears with supports)
![basic_part](https://user-images.githubusercontent.com/23347363/149349704-ccbf4203-8a67-4e47-8766-3e4333606623.PNG)

### Actual results

Slice shows 2 extra planes being printed in places where the STL had no material (see photo below)
![bugged_slice](https://user-images.githubusercontent.com/23347363/149350045-a0b564ef-2064-4cc8-9f5c-75ca2103ad99.PNG)

If the part is rotated by a small amount the planes do not appear. If the part is rotated 180 degrees (upside down), the planes appear again.
![rotated_slice_no_bug](https://user-images.githubusercontent.com/23347363/149350133-9f2941ef-3ad9-4a19-8a6e-e807b0605def.PNG)

### Expected results

No extra planes should appear. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[bugged_cura_slice.zip](https://github.com/Ultimaker/Cura/files/7863610/bugged_cura_slice.zip)
[cura_bugged_slice.log](https://github.com/Ultimaker/Cura/files/7863611/cura_bugged_slice.log)

**Comment by fvrmr** [comment]
Hi @zacharyneveu thank you for your report. 
Looking at your model, your model is not correct. You can red on top, which means that area need support. So the normals of that model are reversed. If you install the [mesh tools plugin](https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools) you can fix your model normals. 

![Capture(239)](https://user-images.githubusercontent.com/77000924/149537021-7af6fb01-8762-467a-8f5a-fbdacec78866.PNG)
![Capture(240)](https://user-images.githubusercontent.com/77000924/149537024-776bcb25-03a1-408e-b8c2-f134481bf8c4.PNG)

I will close this issue, but reach out if you have more questions.

**Comment by zacharyneveu** [comment]
Sorry for the spam and appreciate the helpful advice, that solved it!
