### ISSUE TITLE
Repeated Slicing Errors

### ISSUE THREAD

**Issue by Dude-Industries** [Ultimaker/Cura#11253]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Artillery Sidewinder X1

### Reproduction steps

I've been having problems getting a workable first layer with this one component, so started amending first layer height and line width; in desperation, I attempted a 0.15mm first layer; since then, the majority of attempts to slice have failed (even after resetting first layer to 0.2mm) 
![image](https://user-images.githubusercontent.com/97627266/149201137-d3c5f428-5973-433b-88d4-87a66087a72c.png)

### Actual results

repeated failure to slice :(

Have rebooted PC in hope of overcoming the gremlins, but they're clinging on with surprising tenacity

### Expected results

A wonderful and trouble free life enhancing experience?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I hope you can Cura my symptoms...

**Comment by Dude-Industries** [comment]
Hold up, all sorted now... I also adjusted line width; instead of using percentage, I entered a value of 0.48 thinking it was in mm.

Reset to 100% and all is well; as a bonus, print speed is hugely improved!

**Comment by Ghostkeeper** [comment]
It shouldn't crash the slicing engine regardless. If a certain combination of settings causes this error we'd love to hear about it, because it could result in similar settings crashing for other people where they are useful.
