### ISSUE TITLE
Notifactions and warnings don't disappear

### ISSUE THREAD

**Issue by BSOD76** [Ultimaker/Cura#11269]
### Application Version

4.9.8 ->

### Platform

Windows 10

### Printer

ender3 pro

### Reproduction steps

1. save file, upload to printer or anything that evokes a pop-up

### Actual results

![CURA](https://user-images.githubusercontent.com/64681446/149623279-abbca798-16a4-4cf6-8ed1-06e53bf53043.jpg)

### Expected results

pop-up should disappear after 30 sec.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

An option would be nice to disable pop-ups altogether.

**Comment by fvrmr** [comment]
Hi @BSOD76 thank you for your report.
Does this only happen with these notifications when sending to the printer? 
I assume you are using a plugin to send your print jobs to the printer right?

**Comment by fvrmr** [comment]
Closing this issue since it is indeed related to the Creality Cloud Integration plugin, thanks @fieldOfView!
We can't fix this since we don't maintain this plugin. Please report it to the maintainers of this plugin.
