### ISSUE TITLE
Wire Print - WP Strategy

### ISSUE THREAD

**Issue by verne64** [Ultimaker/Cura#1126]
I've been having some moderate succes in using the Wire Printing feature and would really like to do more with it. When tweaking the settings I noticed some of my changes didn't seem to have an effect (most importantly the Top delay, which I found in the forums, should only be active when using Knot strategy). 

To see what was happening I made some gcodes with the three delays set to 0.4, 0,2 and 0,1 and looked for the resulting pauses in the Gcodes. I did not find a single "G4 P400" in any of the Gcodes and as I looked further, I noticed there actualy weren't any differences whatsoever. No knots being extruded, no compensations not being made and no retractions (except for end of each layer) in any of them.

So I think the WP - strategy setting is not working. I'm on Cura 2.3.1 (win10), but had the same problem on the previous build. Can some other setting prevent WP strategy from taking effect?

Printing on UMO and UM2 with 0.4 and 0.8 nozzles btw.

![cura wireprint gcodes](https://cloud.githubusercontent.com/assets/23369617/20162406/2398b97e-a6f5-11e6-8fd0-50e49d438bd2.jpg)

**Comment by Ghostkeeper** [comment]
Our product owner just shot this down because it had been inactive for too long.
