### ISSUE TITLE
Textposition in Project Save Windows (GERMAN lang.) 

### ISSUE THREAD

**Issue by soundserie** [Ultimaker/Cura#11270]
### Application Version

4.13.0

### Platform

MACOS 12.1 

### Printer

not relevant

### Reproduction steps

Project after slice process save.

### Actual results

German text ist in down layer ant buttons cover this text.
![image](https://user-images.githubusercontent.com/96784053/149628734-ff841794-2378-4780-a156-bd38e6e99ecd.jpeg)

### Expected results

Text is complet readable.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

not relevant

**Comment by fvrmr** [comment]
Hi @soundserie thank you for your report.
I will bring it up with the team. Keep you posted.

**Comment by fvrmr** [comment]
I have discussed it with the team and it turns out that this is a known issue. It turns out you can resize your window to show the text. And we decided to defer this, since this will change with some updates we have planned. I hope you understand.
