### ISSUE TITLE
Changing profiles bug

### ISSUE THREAD

**Issue by theflyingbean** [Ultimaker/Cura#1127]
When changing profiles from the main print screen, The first time you select the new profile, it loads, but you have to click on the profile a second time before the correct profile name shows in the "Profile" box.

Windows 10
Cura 2.3.0
Custom printer

**Comment by Ghostkeeper** [comment]
I suspect this was fixed in version 2.3.1. Could you try with the latest version from https://ultimaker.com/en/products/cura-software ?

I can't reproduce it in the development version 2.4 in any case.

**Comment by theflyingbean** [comment]
It is fixed in 2.3.1.
