### ISSUE TITLE
huge problem with sliser

### ISSUE THREAD

**Issue by RadoBGMTB** [Ultimaker/Cura#11277]
### Application Version

the latest one 4.13.0

### Platform

windows 10

### Printer

Ender 3 v2

### Reproduction steps

It have problem with sliceing singel leyer prints/walls. Its mest up.

### Actual results

?

### Expected results

?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

?

**Comment by GregValiant** [comment]
I see.

**Comment by fvrmr** [comment]
Hi @RadoBGMTB please share more information about what is failing. What are the steps and what is the result you are having. 
Include a project file (file - save project) as a .zip so we can help you better.
