### ISSUE TITLE
Flsun QQ wifi communication problem with Cura

### ISSUE THREAD

**Issue by michelconf** [Ultimaker/Cura#11283]
### Application Version

4.13.0

### Platform

Windows 8.1 Pro

### Printer

Flsun QQ

### Reproduction steps

1. Connect my printer to the network - IP 192.168.1.104
2. Open Cura
3. Printer connection in first step
4. Loosing the connection to the printer after one or two second
5. Note that I succeed one time to be connected and print. Since that I am not able to stay connected for one or two second.

### Actual results

Printer not connecte
![FLsun QQ wifi connection problem](https://user-images.githubusercontent.com/97902426/149802482-8db1d4ff-df42-42cd-9449-257554d00ed2.JPG)
d

### Expected results

Printer connected and operating.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing more to say or to add.

**Comment by michelconf** [comment]
![IMG_6157](https://user-images.githubusercontent.com/97902426/149804239-44497c57-4429-4207-af2b-ebd83ccd78a4.jpg)

**Comment by michelconf** [comment]
Printer always ready and connected to my network

**Comment by Ghostkeeper** [comment]
Please report this with whichever plug-in maintains the connection with your firmware! It's not in the default installation of Ultimaker Cura, so we can't fix this.
