### ISSUE TITLE
Cura 4.13.0 crashes immediately on boot, no log file

### ISSUE THREAD

**Issue by pownall-thomas** [Ultimaker/Cura#11288]
### Application Version

4.13.0

### Platform

Windows 7

### Printer

N/A

### Reproduction steps

I performed a fresh install of Ultimaker Cura 4.13.0 on a machine that had never seen Cura.  I run Windows 7 SP1.

Installation appeared to complete successfully.  When I tried to boot Cura, I saw the attached error message:

![cura_startup_error2](https://user-images.githubusercontent.com/97979474/149993189-b9378d19-53f7-4f92-a3c2-a5de4931978b.png)

As per other bug reports, I went looking for the Cura log file so I could delete it and retry the program -- however under C:\Users\<user>\AppData\Roaming there was no Cura directory.  This is also why I have no log file to share with this bug report.

Since I had an installer for 4.5 lying around from a prior workstation, I tried installing it and it seems to work fine.

Here are the things I tried in the sequence I tried them:

1. Installing 4.13.0
1. Rebooting
2. Uninstalling and reinstalling 4.13.0
3. Uninstalling 4.13.0 and installing 4.12.1 (which I had successfully run on another station)
4. Uninstalling 4.12.1 and installing 4.11.0 (which I had successfully run on another station)
5. Installing Python 3.7 just in case the 4.13 installer failed to include it
6. Uninstalling 4.11.0 and reinstalling 4.13.0
7. Installing 4.5.0 while leaving 4.13.0 intact

Here you can see 4.5 running in the background, while I continue to get the same error message from 4.13.0:

![cura_startup_error](https://user-images.githubusercontent.com/97979474/149993999-7fd7cabf-2a65-47d5-b696-c58e805b6064.png)

I can't figure out why the directory structure for the log file isn't being created by the 4.13.0 installer (it DID create that structure for 4.5).

### Actual results

![cura_startup_error](https://user-images.githubusercontent.com/97979474/149995704-78012e6c-3987-4678-96dd-b137ce1a65d7.png)

### Expected results

Successful installation of 4.13.0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No log file to upload

**Comment by nallath** [comment]
From version 4.11 onwards - Ultimaker Cura is only supported on operating systems actively maintained by their software manufacturer or community. This means Windows 7 and MacOS 10.13 will no longer be supported. Technically this means Ultimaker will stop testing and developing for such operating systems. 

Windows 7 has been end of life for a little over 2 years now. I strongly recommend you to upgrade to at least windows 10.
