### ISSUE TITLE
Disallowed Areas?

### ISSUE THREAD

**Issue by HRjunior** [Ultimaker/Cura#11291]
### Is your feature request related to a problem?

Since 4.13, i can't disable the disallowed areas

### Describe the solution you'd like

Option in the settings to reduce the disallowed areas

### Describe alternatives you've considered

adding disallowed_areas in machine definition

### Affected users and/or printers

ender 3 pro, but mainly all users

**Comment by Ghostkeeper** [comment]
Disabling disallowed areas allows you to print outside of the build volume, which can damage your printer.

If your printer is actually capable of reaching a bigger area than the build volume indicates, feel free to increase the size of the printer in the machine settings. It is more of an explicit action then. I think that is a better way to communicate that between the user, Cura and their printer.
