### ISSUE TITLE
TEVO BLACK WINDOW в CURA не отображаются материалы 

### ISSUE THREAD

**Issue by inrudjt** [Ultimaker/Cura#11296]
### Application Version

4.11.0

### Platform

Windows 10

### Printer

Tevo Black Widow

### Reproduction steps

Добрый день при добавлении других принтеров в них можно выбрать материал и увидеть затраты пластика при печати, На данной модели принтера нет возможности выбора материала, а также добавление нового. Прошу решить проблему скрины приложил 
Good afternoon, when adding other printers, you can select a material in them and see the cost of plastic when printing. This printer model does not have the ability to select a material, as well as adding a new one. Please solve the problem screenshots attached
![44444](https://user-images.githubusercontent.com/98033606/150148231-b6d16337-d17f-4155-94ea-d9a825f883d2.png)
 

### Actual results

не нашел что возможно сделать в данной ситуации
did not find what can be done in this situation

### Expected results

Вот как выглядит на других моделях принтера 
Here is what it looks like on other printer models

![44444](https://user-images.githubusercontent.com/98033606/150148904-79f204f3-f263-4a21-be5c-8e1bfd8aab18.png)
![5555](https://user-images.githubusercontent.com/98033606/150148913-63285f7a-5474-45ac-8aa4-82ee4bacbe51.png)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

прошу подсказать решение проблемы
please help me to solve the error

**Comment by fieldOfView** [comment]
Please use english in this issue queue. If we cannot read what you are saying, we cannot help you.

For many of the people helping others in this issue queue, english is not their native language either. We use english as a common ground. Many of us put in our own time to help you. Please do not also ask us to use a translator to help you.

**Comment by inrudjt** [comment]
> Кто бы ни составлял файл определения вашего принтера («Тобби»), он не хотел, чтобы в нем были материалы. "metadata": { "visible": true, "author": "TheTobby", "manufacturer": "Tevo", "file_formats": "text/x-gcode", **"has_materials": false** , поскольку установлено значение False, вам также не разрешено импортировать материалы. Может быть, Tevo может подсказать, почему они это сделали и как это обойти.

Это только в данной модели принтера от TEVO в других от компании TEVO все впорядке

**Comment by fvrmr** [comment]
Closing this issue, since we don't maintain the printer definition of third party printers. 
Please contact your printer manufacturer for this.
