### ISSUE TITLE
longer

### ISSUE THREAD

**Issue by emanuel1979** [Ultimaker/Cura#11297]
### Application Version

4.9

### Platform

windows

### Printer

longer

### Reproduction steps

Cura doesn't have longer with the .6 and .8 nozzles. I think its not even listed this time. Please help me.

### Actual results

Cura doesn't have longer with the .6 and .8 nozzles. I think its not even listed this time.

### Expected results

Please add the longer printer with all the nozzles. Me EMAIL is emanuel.calderon@pettorino.com

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Cura doesn't have longer with the .6 and .8 nozzles. I think its not even listed this time.

**Comment by emanuel1979** [comment]
Cura doesn't have longer with the .6 and .8 nozzles. I think its not even listed this time.

**Comment by GregValiant** [comment]
That was up to whoever wrote the definition file (it looks like Longer wrote it).  I think you need to go back to Longer and ask them to add more nozzles or you can add your own.

**Comment by fvrmr** [comment]
Hi @emanuel1979 thank you for your report.
We don't maintain these profiles, so we can't change this.
Like @GregValiant mentioned please contact the manufacturer or contributor to add this.  

I will close this issue.

**Comment by emanuel1979** [comment]
Thanks. I which I could change it my self. Its simple. Thanks for the advice . have a nice one.--- ***@***.*** wrote:From: Fenne ***@***.***>To: Ultimaker/Cura ***@***.***>Cc: emanuel1979 ***@***.***>,  Mention ***@***.***>Subject: Re: [Ultimaker/Cura] longer (Issue #11297)Date: Fri, 21 Jan 2022 05:34:10 -0800
Hi @emanuel1979 thank you for your report.
We don't maintain these profiles, so we can't change this.
Like @GregValiant mentioned please contact the manufacturer or contributor to add this.
I will close this issue.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>
 Sign up for FREE email from Everyone.net email at http://www.everyone.net
