### ISSUE TITLE
Custom Support Not working

### ISSUE THREAD

**Issue by PrabakPk** [Ultimaker/Cura#11307]
### Application Version

4.13.0

### Platform

windows11

### Printer

Creality ender 3 pro

### Reproduction steps

I added a custom support to my design and change support setting to 'touching buildplate'. When i slice it and loot at the preview, it doesn't show the support.
while exporting and printing also, it prints without support

### Actual results

Design was not previewed with support

### Expected results

Design should have support

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Pls solve this

**Comment by fvrmr** [comment]
Hi @PrabakPk thank you for your report.
Could you please attach a project file (file - save project) and share it here in a .zip on Github?
