### ISSUE TITLE
Support roof doesn't cover all support top

### ISSUE THREAD

**Issue by maaboo** [Ultimaker/Cura#11306]
### Application Version

4.12.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

1. Put model required supports into slicer
2. Enable tree support and slice

### Actual results

Roof only partially covers support top

### Expected results

Roof covers all support top

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

![roofbug](https://user-images.githubusercontent.com/912261/150490245-cd63cf9b-7693-4eb8-9c17-ba2dcb349879.png)
[roofbug.zip](https://github.com/Ultimaker/Cura/files/7911417/roofbug.zip)

**Comment by fvrmr** [comment]
Hi @maaboo thank you for your report.
I could reproduce your issue in 4.12, but not in 4.13. 
However in 4.13 there is a known bug with tree support you might run into when using it. See: https://github.com/Ultimaker/Cura/issues/11258

**Comment by maaboo** [comment]
I confirm that this particular bug is no longer reproducible in 4.13 and I also have [#11258](https://github.com/Ultimaker/Cura/issues/11258). Also I noticed that top of the support roof looks "dirty" like it's density significantly decreased. Is this a bug or just configuration? I thought interface should be consistent on all the layers.

**Comment by fvrmr** [comment]
Could you show me with a screenshot what you mean?

**Comment by maaboo** [comment]
![roofbug2](https://user-images.githubusercontent.com/912261/151122972-b9cad417-cf1a-491c-a71a-973dbd42f010.png)
Looks more like rice

**Comment by fvrmr** [comment]
@maaboo thank you, could you share a project file of this? Because with your other project file I could not reproduce this.

**Comment by maaboo** [comment]
This is strange, but here you are:
[roofbug2.zip](https://github.com/Ultimaker/Cura/files/7950610/roofbug2.zip)

**Comment by fvrmr** [comment]
I have discussed it with the team and this is expected behaviour because of the support branch diameter. If you change this to 0.6mm it will show the interface on every layer the same!

**Comment by maaboo** [comment]
Well, not branch diameter but branch distance. I changed it as you suggested and it works as expected.
I think there is nothing left and issue could be closed.
Thanks.
