### ISSUE TITLE
"Multiply" Doesn't work, Also "arrange all models" doesn't work

### ISSUE THREAD

**Issue by LasseRb03** [Ultimaker/Cura#11303]
### Application Version

4.11.0

### Platform

macOS Monterey 12.1

### Printer

Anycubic Kossel linear plus

### Reproduction steps

I wanted to print circle of one layer hight.
I imported the model in Cura and scaled it to the right hight with uniform scaling because the whole circle was too big in total.
My goal was to print three circles in different z Offset positions to get the right hight for my first layer.
When I clicked multiply and entered the number two it showed it is processing the act but didn't finish it o even start to Show a processing bar.

<img width="375" alt="Bildschirmfoto 2022-01-20 um 16 33 27" src="https://user-images.githubusercontent.com/98107860/150370085-d44180c0-d88e-4715-a56c-6d45db0f061c.png">
<img width="496" alt="Bildschirmfoto 2022-01-20 um 16 33 16" src="https://user-images.githubusercontent.com/98107860/150370080-b5ebafa6-ef07-4620-91f0-c7f25c1372fa.png">

The circle I was trying to duplicate was this one scaled to 12.5%:
[Circle 0,25 height.stl.zip](https://github.com/Ultimaker/Cura/files/7906499/Circle.0.25.height.stl.zip)

In another project I wanted to separate two parts like I have been already doing for multiple prints and the parts just didn't separate

### Actual results

the app doesn't multiply or arrange the models at all!

### Expected results

The objects should get duplicated two times and they should get arranged to be able to print them.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7906511/cura.log)

**Comment by nallath** [comment]
This was fixed in Cura 4.12.1 and up.
