### ISSUE TITLE
Support blocker has no effect

### ISSUE THREAD

**Issue by ReaperKeeper** [Ultimaker/Cura#11311]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Creality CR-10S

### Reproduction steps

1. Loaded a helmet file
2. Added support blocker to bottom dome of helmet
3. Scaled to size
4. Sliced
5. Noticed print was over 1700G of filament and questioned why
6. Went to preview, noticed in the line view that it printed supports anyway.

### Actual results

Cura does not recognize the support blockers and is creating supports where asked not to.

### Expected results

Should block supports

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Great Ape Studios Mandalorian helmet - can't share file due to copyright.
![Screenshot 2022-01-21 092628](https://user-images.githubusercontent.com/98179376/150572518-48137cb4-4720-4743-844a-b7d6a29e6e81.png)
![Screenshot 2022-01-21 092124](https://user-images.githubusercontent.com/98179376/150572539-60cdac7b-5ef6-4bc5-a9b3-fd22633797f8.png)

**Comment by fvrmr** [comment]
Hi @ReaperKeeper thank you for your report.
What are exactly the steps you are doing? You add one support blocker and then resize this? 
Or do you want to duplicate your support blockers?

Does this also happen on another model?

**Comment by ReaperKeeper** [comment]
One support blocker scaled up. I went back to 4.11 and it worked.

It did the same for other models. Adding individuals didn't help either.

**Comment by fvrmr** [comment]
Could you share a project file (with another model) where it is also happens?
