### ISSUE TITLE
Stl files will not load

### ISSUE THREAD

**Issue by lotta3dprinters** [Ultimaker/Cura#11321]
### Application Version

4.13.0

### Platform

Windows 10 OS build 19044.1466

### Printer

Traffic cone

### Reproduction steps

Program closes when you type to load any files.

### Actual results

Cura closes.

### Expected results

Thw files should load.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by fieldOfView** [comment]
Hard to diagnose without any logs, but if you have Chitubox installed on the same computer, read this:
https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
