### ISSUE TITLE
Number ob Skirt Lines are shown wrong

### ISSUE THREAD

**Issue by tgindia** [Ultimaker/Cura#11324]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

1. Set Skirt Lines to 1
2. In the Model are seen 2 Lines

### Actual results

-

### Expected results

Also show 1 Line for the Skirt in the Model preview

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Skirt](https://user-images.githubusercontent.com/98311682/150752113-9830b052-1fdb-4598-9a11-068efc5366b7.jpg)

**Comment by nallath** [comment]
Try changing the "Skirt/brim Minimum Length" setting (or "Mindestlange fur Skirt/Brim" in your case)
