### ISSUE TITLE
The length of the material to be pulled back last when machine_extruders_share_heater is true.

### ISSUE THREAD

**Issue by furuiie** [Ultimaker/Cura#11327]
### Is your feature request related to a problem?

The length that is pulled in last is the length of retraction_amount, so the material remains in the common part of the nozzle.

### Describe the solution you'd like

If machine_extruders_share_nozzle is true, please pull back to the value of machine_extruders_shared_nozzle_initial_retraction.

### Describe alternatives you've considered

I set machine_end_gcode to ";End G-code \nM140 S0 \nG91 \nG0 F300 Z3 \nG90 \nG92 E-{retraction_amount} \nG1 F1800 E-{machine_extruders_shared_nozzle_initial_retraction} \nG28 XY \nG0 F300 Z{machine_height} \n;End of End G-code \n ".

If the value of retraction_amount is different, the value of retraction_amount will return the value of extruder 0, even if the last extruder is 1.

### Affected users and/or printers

Those who have a machine where the extruder shares a single nozzle.

**Comment by Ghostkeeper** [comment]
Set the Extruder Switch Retraction Distance equal to the initial retraction amount then. This is up to you or whoever created your profiles.
