### ISSUE TITLE
ogni volta che seziono un oggetto si chiude il programma

### ISSUE THREAD

**Issue by ninogtr** [Ultimaker/Cura#11339]
### Application Version

4.13

### Platform

windows 10

### Printer

flsunq5-ender 3

### Reproduction steps

ho caricato il file da stampare,avvio sezionamento,e si chude il programma

### Actual results

si chiude il programma

### Expected results

che si risolve il problema

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

bho

**Comment by fvrmr** [comment]
Hi @ninogtr please fill in you report in English. 
Also attach a project file and log file, with that information we can help you further.
