### ISSUE TITLE
Add {material_weight} replacement pattern

### ISSUE THREAD

**Issue by pedrolamas** [Ultimaker/Cura#11343]
### Is your feature request related to a problem?

Cura already calculates and shows the material weight, but as far as I can see, this is not output on the gcode files and there is no pattern available for it.

![image](https://user-images.githubusercontent.com/85504/151205133-e0325a89-b63e-4c8a-8b07-d6caa95d74a1.png)

This is useful information for Klipper users as it will allow to show this information in the web interface (via Moonraker)

### Describe the solution you'd like

For a new `{material_weight}` replacement pattern to be available.

### Describe alternatives you've considered

None available AFAIK...

### Affected users and/or printers

All?

**Comment by fieldOfView** [comment]
Unfortunately this can't work in Cura. The replacement patterns are processed by Cura before slicing, and the material weight is only available _after_ slicing.

**Comment by pedrolamas** [comment]
Oh, that's a pitty... 😕

**Comment by tispokes** [comment]
@pedrolamas 
I have this in my start G code and it works fine.
`;Filament weight = {filament_weight}`

**Comment by pedrolamas** [comment]
Oh, that DOES work!! 😁

![image](https://user-images.githubusercontent.com/85504/151343866-baab47fb-f3f7-4dd0-bcb8-6dd2b68d0948.png)

And it matches the Cura interface, so it seems all good!

@fieldOfView guess this is already available?

**Comment by tispokes** [comment]
> Unfortunately this can't work in Cura. The replacement patterns are processed by Cura before slicing, and the material weight is only available _after_ slicing.

Why it works then?

**Comment by fieldOfView** [comment]
I don't know. There must be something (a plugin) that runs after Cura is done slicing.

**Comment by pedrolamas** [comment]
I just confirmed on a brand new install (via Windows Sandbox) with no extra plugins added, seems to work fine even there!

![image](https://user-images.githubusercontent.com/85504/151354392-fb933517-9a66-444a-88a5-b9a0d1510227.png)

No idea how or why this works, but seems to extra plugin is required! 😁

**Comment by pedrolamas** [comment]
Closing the issue as this is already available right now via `{filament_weight}`

Thanks for the help @tispokes and @fieldOfView!

**Comment by fieldOfView** [comment]
I have added the additional replacement patterns I found to http://files.fieldofview.com/cura/Replacement_Patterns.html

**Comment by pedrolamas** [comment]
Awesome stuff @fieldOfView , that is exactly where I go when I want to see what replacement patterns Cura has to offer! 😁
