### ISSUE TITLE
CURA 4.13 - Creality Ender3 - nozzle size option 

### ISSUE THREAD

**Issue by TinMaan** [Ultimaker/Cura#11348]
### Application Version

4.13.0

### Platform

MacOSX 10.15.7

### Printer

Creality Ender 3

### Reproduction steps

- Add printer
- Creality 
- Creality Ender-3
- Enter

### Actual results

In the Printer setup steps the extruder window missing the option for entering the nozzle size
![Screen Shot 2022-01-26 at 8 22 11 PM](https://user-images.githubusercontent.com/83846199/151275125-9f0b93fa-eadd-4198-a4f5-9b324b6a2f66.png)

### Expected results

I should be able to enter the nozzle size for the printer extruder in that window

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is not an Apple Silicon case. 
I have deleted and re-installed CURA 4.13 twice with the same issue

**Comment by GregValiant** [comment]
Try "Settings | Extruder | Extruder 1 | Nozzle Size".  It's also available somewhere else but I'm using FieldOfView's GUI and it's different.
