### ISSUE TITLE
Crash on opening files 

### ISSUE THREAD

**Issue by madcap23** [Ultimaker/Cura#11351]
### Application Version

4.13.0

### Platform

Windows 11 Pro

### Printer

Custom 

### Reproduction steps

Select File open, the open dialog starts but never populates, Cura crashes 
Dragging and dropping a file into Cura causes Cura to crash

Only success is double clicking on an STL file, that will open Cura and display the file. 

### Actual results

Crash

### Expected results

Cura opens file 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7947532/cura.log)

**Comment by fvrmr** [comment]
Hi @madcap23 thank you for your report.
Do have Chitubox installed? If so see https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
