### ISSUE TITLE
Cura 4.13.0 crashes when I want to open file using "Open File(s)" 

### ISSUE THREAD

**Issue by huzargarden** [Ultimaker/Cura#11356]
### Application Version

4.13.0

### Platform

WIndows 10

### Printer

BLV MGN

### Reproduction steps

Slight problem here with Cura 4.13.0. If I want to load the file using the Cura "open file" feature then CURA will crash. The same happens when I will use File -> Open File(s) from the menu. 
However, I can still load the files by dragging them into cure from the folder. 

My folder settings are as large icons. 

### Actual results

Cura will open the file selection window then freezes and it will crash. 

### Expected results

Program crashing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/12796202/151424399-a4e99194-450a-4a14-89ac-567330e39e62.png)

**Comment by fvrmr** [comment]
Hi @huzargarden thank you for your report.
Do you have Chitubox installed? If so please check: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
If this is not the case could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
