### ISSUE TITLE
Cura Very Slow on S5 Ultimaker

### ISSUE THREAD

**Issue by RogueWaves** [Ultimaker/Cura#11368]
### Application Version

4.13

### Platform

win 10

### Printer

Ultimaker S5

### Reproduction steps

Cura very slow on selection of menu, input data, and rotate model. After about 20 minutes in Cura drops to a crawl. Close/Start Cura usually solve the problem, but have to reboot at times....
Computer AMD Thread Ripper
128 GB memory
when other program running or Cura solo issue still alive
 sometimes CPU goes to 40% when solo
No crashes

### Actual results

n/a

### Expected results

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by nallath** [comment]
Please run Cura again with the data collected by our profiling plugin. You can find it here: https://marketplace.ultimaker.com/app/cura/plugins/UltimakerPackages/ExtensiveSupportLogging
