### ISSUE TITLE
윈도우11 에서 실행시  프리징현상을 보입니다

### ISSUE THREAD

**Issue by bushse** [Ultimaker/Cura#11376]
### Application Version

4.13.1

### Platform

windows11

### Printer

clone s-290

### Reproduction steps

정상적인큐라 설치 후 셋팅

### Actual results

큐라 실행시 프리징현상(응답없음)이 보임
특히 구성의 재료설정 에서 증상이 많이 나타남
버전을 바꾸어 설치 해봐도 동일함 
4.10 이전 버전설치시 응답없음 시간이 약간 줄어듬

### Expected results

[cura.log](https://github.com/Ultimaker/Cura/files/7964868/cura.log)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![화면 캡처 2022-01-30 072506](https://user-images.githubusercontent.com/62738966/151679535-c3f6f4f7-4eec-483f-a821-607d2be7f3c7.png)

**Comment by fvrmr** [comment]
Hi @bushse thank you for your report.
Please fill in the form in English.

**Comment by Ghostkeeper** [comment]
Looks like a duplicate of https://github.com/Ultimaker/Cura/issues/11381 then. Please continue the conversation there!
