### ISSUE TITLE
"Pause at height" Does not display tool head move

### ISSUE THREAD

**Issue by theflyingbean** [Ultimaker/Cura#1137]
Cura 2.3.1
Windows 10
Custom printer (Lulzbot Mini)

When Using the "Pause at height" plugin, the tool head moving away from the part and parking is not displayed when in layer view mode. This is a feature that is in Cura 15.xx and is helpful to visualize where your print pause will occur. I am wondering if it could be added to Cura 2. 

Cheers

**Comment by thopiekar** [comment]
@nickthetait, @kakaroto Ping

As far as I know this feature is included in the PostProcessing plugin.

**Comment by BerndJM** [comment]
Can confirm this for Linux also, so it seems to be OS independent ...
I think to remember that this worked as expected in versions before 2.3.1 - but cannot say exactly when it is gone :-(

**Comment by thopiekar** [comment]
@BerndJM So missing in PostProcessingPlugin too?

**Comment by BerndJM** [comment]
it seems so

**Comment by fieldOfView** [comment]
Anything added or changed by the postprocessing plugin has never shown in the layerview since the 2.x rewrite.

The postprocessing plugin is invoked when saving or sending gcode, not before. So what you see in layerview has not yet been postprocessed

**Comment by Ghostkeeper** [comment]
I'm marking this as a bug (it technically is), but for the reason that fieldOfView says, it is probably not getting fixed any time soon.

For version 2.4 we are planning to upgrade the layer view a bit to allow for loading g-code from a file. Perhaps we could consider performing the post-processing a bit earlier then and see what we can do to display the result in the layer view (or whatever view is made for displaying g-code).

**Comment by fieldOfView** [comment]
> For version 2.4 we are planning to upgrade the layer view a bit to allow for loading g-code from a file

Have you seen the work by lulzbot here: https://code.alephobjects.com/T466 ?

**Comment by Ghostkeeper** [comment]
I hadn't! I'll be sure to link that to our Jira issue too... Nice work over there, guys.

**Comment by nickthetait** [comment]
Yeah, bulk of the work for GCodeReader is done. :smile:  It will be going through a code review, then I'll make a PR.
I've not yet tried this plugin in Cura 2.x, so don't have anything else to add.

**Comment by kakaroto** [comment]
That makes sense, if the post processing works on the gcode and cura2 doesn't parse the resulting gcode, it can't show it in the layer view. So I assume that once we finish the work on the gcode loader (which would also fix #577), then the layer view would parse the result gcode and show that instead of whatever it is showing currently. That would fix the current issue.

**Comment by jackha** [comment]
Marked as deferred because of inactivity

**Comment by Ghostkeeper** [comment]
A problem with this is that parsing the g-code takes an order of magnitude longer than displaying the pre-generated polygons that CuraEngine sends to the front-end. We don't want to have the user wait for an additional minute after each slice to display layer view.
