### ISSUE TITLE
Unable to open configuration folder from Help->Show Configuration folder

### ISSUE THREAD

**Issue by TDS07** [Ultimaker/Cura#11372]
### Application Version

4.13.0

### Platform

ubuntu 20.04

### Printer

/

### Reproduction steps

Unable to open configuration folder from Help->Show Configuration folder

### Actual results

nothing

### Expected results

Window with configuration file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Cura installed with snap on Ubuntu 20.04

**Comment by fvrmr** [comment]
Hi @TDS07 thank you for your report.
We don't maintain the snap packages, so please report your issue to the maintainer of the package.
We only maintain the AppImage. I will close this issue, but let us know if you have the same issue with our AppImage.
