### ISSUE TITLE
Print Dialog 15.06.4

### ISSUE THREAD

**Issue by BNNorman** [Ultimaker/Cura#1138]
Running on Debian (Jessie). Now realised that if the printer is not up to temperature BEFORE the print to USB button is used then the print dialog may or may not display the full buttons. I find if I close the dialog and re-open when the printer is at the required temperature then the Print/cancel buttons are fully visible.

**Comment by thopiekar** [comment]
As you are using an older version of Cura, please ask for support at: https://github.com/daid/LegacyCura/issues

Thanks

**Comment by BNNorman** [comment]
Thank you. I am new to this. I had presumed 15.x was newer than 2.x (dates on the website seemed similar – very confusing to me)– I will download 2.31 and install it.
