### ISSUE TITLE
loading files

### ISSUE THREAD

**Issue by dwatson03** [Ultimaker/Cura#11386]
### Application Version

4131

### Platform

windows11

### Printer

ender 3 pro

### Reproduction steps

after starting cura every file i try to load closes cura

### Actual results

he only way i can get a file to load is if i double click on the file from its folder

### Expected results

to load the file i want to load

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i have been having this problem since 4.11

**Comment by fvrmr** [comment]
Hi @dwatson03 thank you for your report.
Do you have Chitubox installed? See https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
If not a log file would be really helpful! You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
