### ISSUE TITLE
Change open File window

### ISSUE THREAD

**Issue by Turiok** [Ultimaker/Cura#11394]
### Is your feature request related to a problem?

It's not really a problem but a feature.
The windows when we want to open file is minimalist.
I think, it'll be nice to have a windows with favorite folder in place. I'm not sure it's Cura and not the OS.
But other tool (ex : VSCode) has a different windows for open a file and the favorites work.
Check the images to understand.
On Cura we can see what it seems to be favorites. But we can't modify the existing list.

### Describe the solution you'd like

Change the type of windows with favorites integrated. 

### Describe alternatives you've considered

I don't know.

### Affected users and/or printers

I'm not sure it is not depending of the OS.

### Additional information & file uploads

Cura : 4.12.0
Os : Manjaro 21.2.1
Folder manager : nemo 5.0.5
Cura window :
![cura_window](https://user-images.githubusercontent.com/6814217/151865675-535ac215-32ea-4a01-9810-f634d8b2fc4a.png)
vscode window :
![vscode_window](https://user-images.githubusercontent.com/6814217/151865684-aa708000-b0b1-453a-912e-fc25e855c579.png)

**Comment by fvrmr** [comment]
Hi @Turiok thank you for your request.
This is handled by Qt and we use one version for all operating systems. The option where favourites are shown will not work properly on MacOS. So that's why will not change this, I hope you understand.
