### ISSUE TITLE
macOS Grey Empty Window on Launch

### ISSUE THREAD

**Issue by lilithebowman** [Ultimaker/Cura#11405]
### Application Version

latest

### Platform

macOS

### Printer

N/A

### Reproduction steps

Download a fresh copy of the latest Cura and install on macOS 11.6.2

### Actual results

![image](https://user-images.githubusercontent.com/1637212/152222308-04620404-0432-4859-bc3d-0e20270a9675.png)

### Expected results

Anything more than this! Hopefully the 3D view and allowing me to load and slice files!

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This happens on the latest version available. It's been broken for a while now on macOS.

**Comment by fvrmr** [comment]
Hi @lilithebowman thank you for your report.
Could you share your log file. You can find your log file here: `$HOME/Library/Application Support/cura/<Cura version>/cura.log`
