### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tlyates08** [Ultimaker/Cura#11414]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Ender 5 Plus

### Reproduction steps

Slice Object
Click Preview

### Actual results

Software Crash, no error

### Expected results

Preview and edit 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[170517_h500_medieval_wooden_shield_v2.zip](https://github.com/Ultimaker/Cura/files/7999336/170517_h500_medieval_wooden_shield_v2.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/7999344/cura.log)

**Comment by fvrmr** [comment]
Hi @tlyates08 thank you for your report. 
Your log file doesn't show me why Cura is crashing. Does this happen with every file? Or just this one file?
