### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pgocon** [Ultimaker/Cura#11418]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Creality Ender 3D Pro

### Reproduction steps

1. Opened Cura
2. selected the folder icon upper left
3. window opened for windows explorer
4. freezes for a moment, then closes and Cura closes..

### Actual results

Cura closes, i have to restart Cura, and get the same results, every time.  I cannot select any files to print.  

### Expected results

should work?

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8005019/cura.log)

**Comment by fvrmr** [comment]
Hi @pgocon thank you for your report.
Do you have Chitubox installed? If so check: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
