### ISSUE TITLE
Gcode preview showing lines everywhere

### ISSUE THREAD

**Issue by davkvi** [Ultimaker/Cura#11416]
### Application Version

4.13.1

### Platform

Macos

### Printer

Ender 3 v2

### Reproduction steps

Add stl file. Slice and click preview

https://imgur.com/a/RMDnXUV

### Actual results

https://imgur.com/a/RMDnXUV

### Expected results

Normal gcode viewer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://imgur.com/a/RMDnXUV

**Comment by fvrmr** [comment]
Hi @davkvi thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/10387
Because this is a duplicate I will close your issue, you can read there that a reboot fixed it for some people.
Please continue the thread there, so we keep everything in one place.
