### ISSUE TITLE
feature suggestion: always show parent category when searching for an advanced setting

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1143]
This is what the advanced settings look like when scrolling through: 
![image](https://cloud.githubusercontent.com/assets/16858474/20247570/73700bb4-a99d-11e6-9f9d-a48735d6f028.png)

But when one searches for a specific setting, the parent categories are hidden. 
This makes it useless for figuring out where specific setting lives!
It means I can enable any setting easily, but then have to still manually go through the UI settings to see where it actually is... 
![image](https://cloud.githubusercontent.com/assets/16858474/20247577/b08e37d2-a99d-11e6-8760-bcba890c634d.png)

**Solution: always display parent category in search.**

**Comment by fieldOfView** [comment]
Yes, very much agreed. I'll see what I can do about this, unless team Cura or team Lulzbot beat me to it.

**Comment by nallath** [comment]
This is already implemented for 2.4 :)

**Comment by fieldOfView** [comment]
By golly, you're right!
