### ISSUE TITLE
Cura not work

### ISSUE THREAD

**Issue by hanzprague** [Ultimaker/Cura#11441]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Creality CR-10 Smart

### Reproduction steps

When I want to upload or save a stl file and Cura offers Windows Explorer, the program shuts down. The older version did not. I have Windows 10 in perfect condition. The problem is in the Cura program.

### Actual results

When I want to upload or save a stl file and Cura offers Windows Explorer, the program shuts down. The older version did not. I have Windows 10 in perfect condition. The problem is in the Cura program.

### Expected results

When I want to upload or save a stl file and Cura offers Windows Explorer, the program shuts down. The older version did not. I have Windows 10 in perfect condition. The problem is in the Cura program.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

When I want to upload or save a stl file and Cura offers Windows Explorer, the program shuts down. The older version did not. I have Windows 10 in perfect condition. The problem is in the Cura program.

**Comment by nallath** [comment]
Have you checked this link: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file?
