### ISSUE TITLE
4.13.1 AppImage doesn't start on linux

### ISSUE THREAD

**Issue by wileu** [Ultimaker/Cura#11440]
### Application Version

4.13.1

### Platform

Mint 19

### Printer

TwoTrees Sapphire Pro

### Reproduction steps

Double click on the file

### Actual results

Nothing - no errors, etc.

### Expected results

To run the program.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Something.

**Comment by fvrmr** [comment]
Hi @wileu thank you for your report.
What file are your trying to open a stl or you want to open Cura?
Could you share your log file? You can find your log file here: `$HOME/.local/share/cura/<Cura version>/cura.log`

**Comment by wileu** [comment]
I want to open Cura. I only have a folder for other Cura like 4.12 and 4.13.0. Cura 4.13.1 does not create any folder, file. Cura 4.13.0 opens without a problem.

**Comment by wileu** [comment]
Yes, I know. I write that Cura 4.13.0 create folder 4.13, but 4.13.1 doesn't create any folder like 4.13.

**Comment by wileu** [comment]
I already know what's wrong. The problem is the GLIBC. Cura 4.13.1 needs GLIBC 2.78  but I have version 2.27.Regards.

**Comment by lucastcox** [comment]
Still an issue. Says it needs glibc 2.28 and I have 2.27

**Comment by Ghostkeeper** [comment]
I wonder what component says that then. We didn't implement that message ourselves. Qt mentions it needs GLib 2.8.3. Perhaps it's Sip? Or Python?

**Comment by GWRon** [comment]
Doesnt the glibc requirement come simply from the building OS ? 
In other words: building on an older distribution will lead to a lower glibc required.

Maybe cura should not try to run on the latest versions of its dependencies.

**Comment by Ghostkeeper** [comment]
Ah, that sounds plausible indeed. If it's linking to the system version of that library it might not be binary compatible with older versions. We used to build on CentOS6, but changed that to Debian-buster with 4.13. It was apparently necessary for the upgrade to Python 3.10 in the upcoming release, which we were already preparing for back then.
