### ISSUE TITLE
2.3.1 Maximum Z Speed, and M203

### ISSUE THREAD

**Issue by darrelhunt** [Ultimaker/Cura#1144]
Hi, new to Cura so pardon me if I'm doing something wrong.

I'm finding that when Cura creates the gcode, it's doing some math and it's placing M203 Z<Max Speed*60> into the gcode.
Which is logical it's converting to mm/min

Except all the RepRap firmwares are expecting it in mm/sec
M203 is expected in mm/sec

My issue for example,
I like my Z speed to be 0.5 mm/sec (30 mm/min)

I put in 0.5 into the interface and it does the math, creating the mm/min:
M203 Z30
But Marlin expects that as the mm/sec and now it's running insanely fast and binds

In this case, entering 0.5 should just be passed straight through and M203 should be:
M203 Z0.5

Also Cura seems to place an M203 Z300 at the end of the gcode, right before the end gcode
Where is it told to do that?  And can it be stopped?

Also, first thing Cura does after the start gcode is retract, again where is it told to do that?  And can it be stopped?

**Comment by Ghostkeeper** [comment]
Nice catch. We should be able to get this fixed.

I think the `M203 Z300` is to reset the maximum speed to the default, so that any subsequent print that does not specify the maximum speed will have the proper default maximum speed (unless you abort the print). I don't think there is an option to prevent it at the moment.

**Comment by darrelhunt** [comment]
Glad I'm not going crazy.

About the Z Max Speed option in the GUI

After researching implementations of M203 in all of the RepRap firmwares.  Excluding Repetier as it doesn't use M203 for max feedrate, and I'm not including Ultimaker hardware in the RepRap classification.

It looks like all of them do M203 in mm/sec.  It seems that Cura shouldn't be multiplying it at all, rather than just passing the value through.  And I'd like to ask that it allows more granular in the GUI, say down to .01

**Comment by Ghostkeeper** [comment]
You should be able to specify the speed down to 0.0001mm/s. It's a floating point field, and these accept values down to 4 digits after the radix.

**Comment by darrelhunt** [comment]
True, the interface does allow.  But the resulting gcode gets rounded.  Looking at the code for Cura Engine, it looks like it's an integer.  Everything appears to get rounded there.  So the ability for it to output something like M203 Z0.5 doesn't exist.

**Comment by darrelhunt** [comment]
Also a question.
Say a default install, Max Z Speed was never unhidden from advanced options, value never set.  M203 doesn't appear in gcode.

But if you unhide it and set a value, M203 appears in gcode

It wasn't performing the way I wanted so I though hiding it again would turn it of and M203 would no longer appear in gcode.

M203 remains, it seems like hiding it doesn't disable it.  And there's no option to disable it once you have enabled it.

**Comment by Ghostkeeper** [comment]
I'd expect that iff the Max Z Speed setting is equal to the default, it wouldn't put the M203 commands in the g-code.

**Comment by BagelOrb** [comment]
The M203 command is left out if it's set to zero...

**Comment by BagelOrb** [comment]
M203 now always uses mm/s.
I've checked the firmware of Sprinter, Marlin and Repetier and all used mm/s.
I haven't checked any other firmware we support (BFB, MACH, MaketBot).

Other firmware types are not selectable in Cura.
