### ISSUE TITLE
Support arborescent

### ISSUE THREAD

**Issue by seb449** [Ultimaker/Cura#11442]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Toutes

### Reproduction steps

Support arborescent mal conçu, pas de soucis sur la 4.12

### Actual results

Support arborescent non ou très difficilement détachable

### Expected results

Support arborescent détachable

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Support arborescent non ou très difficilement détachable

**Comment by fvrmr** [comment]
Hi @seb449 thank you for your report.
Please fill in the form in English. Also a project file (file - save project) would help to see if I can reproduce your issue.
Screenshots of the problem will also help. Thank you in advance.
