### ISSUE TITLE
Crash on start | Plugin could not be loaded

### ISSUE THREAD

**Issue by harmo** [Ultimaker/Cura#11453]
### Application Version

4.13.1

### Platform

Archlinux

### Printer

Ender 3

### Reproduction steps

just start Cura

### Actual results

i have this 3 popup at start, most of the time when I close them Cura crashes, sometimes I can use the soft, but the popup are always there.

![image](https://user-images.githubusercontent.com/667592/153291586-db928175-5731-4fe6-8c6e-5409ad06c97b.png)

I already completely removing any trace of Cura (including profiles & local config)  and reinstalling it, same behavior.

When I click on `Remove Plugin` Cura crashes.

### Expected results

Those popups are really annoying, the worst is that i really don't use those plugins !

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8036324/cura.log)

**Comment by fieldOfView** [comment]
Use the AppImage instead of the Arch package. The package you currently use misses dependencies.
