### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by MrReijii** [Ultimaker/Cura#11465]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Flsun Super Racer

### Reproduction steps

When slicing the model, the upper face is not generated in narrow places (about 1-3 mm). This happens when choosing my printer Flsun Super Racer and also Anet A8. If you specify a printer of any Ultimaker, then there is no such problem with slicing.
This model is just an example, this happens on all models where there are such bottlenecks.
Sorry for my english
![1](https://user-images.githubusercontent.com/37585988/153605740-a0d5a764-d886-4a9f-84f7-244a794220a7.png)
![2](https://user-images.githubusercontent.com/37585988/153605742-7b5d9ef1-b20c-428b-86ef-bf6173982c60.png)
.

### Actual results

When printing such a model, there are holes on it, since there is simply no plane that needs to be printed there. In the attached files, the wall thickness is indicated in one layer specifically in order to better see the problem. Such a problem on any number of wall layers.
This problem was on previous versions of Сura, the update did not fix it. I removed the program completely. I deleted all profiles and printers. Installed the program on another PC and there is the same problem.
![IMG_1318](https://user-images.githubusercontent.com/37585988/153605843-2b1cefd5-849b-48fa-96cc-ccd6a389bff7.JPEG)
![IMG_1319](https://user-images.githubusercontent.com/37585988/153605849-578cfced-0a19-4ea0-bde3-34c70f6c4e18.JPEG)
.

### Expected results

Same model but with
![3](https://user-images.githubusercontent.com/37585988/153606615-331107df-0440-4aa9-81bd-42e050fa7a5a.png)
![4](https://user-images.githubusercontent.com/37585988/153606622-ad92d52c-36ae-4d4e-896a-91583f928415.png)
 selected printer Ultimaker S5

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[FSR_Korobka Litii B.zip](https://github.com/Ultimaker/Cura/files/8049205/FSR_Korobka.Litii.B.zip)

**Comment by fvrmr** [comment]
Hi @MrReijii thank you for your report. 
You need to change the `Maximum Skin Angle for Expansion` to for example 90 °
![Capture(275)](https://user-images.githubusercontent.com/77000924/153618146-f1d4407f-d327-4193-942a-f0703d5308a3.PNG)
This is probably set as default in your profile, you can change this setting and create your own profile, so you don't have this issue in the future. 
I will close this issue, but let me know if you have more questions.

**Comment by pixie-wrangler-irl** [comment]
Why did this value get changed in the default profile of only the Super Racer? What does it take to change the default back to 90 to save folks from this insanely niche issue.

**Comment by Ghostkeeper** [comment]
See https://github.com/Ultimaker/Cura/issues/11553 for a fix to the FLSUN Super Racer profiles.
