### ISSUE TITLE
Alternating Wall Line Counts

### ISSUE THREAD

**Issue by HMarxen** [Ultimaker/Cura#11468]
### Is your feature request related to a problem?

The adhesion between an infill line meeting a wall line is often waeker than two paralel lines.

### Describe the solution you'd like

Having alternating wall line counts. E. g. every odd number of layers has a wall line count of 3, every even number of layers has a wall line count of 2. This would better squish in the ends of infill lines between two wall lines on top and bottom.

### Describe alternatives you've considered

none

### Affected users and/or printers

Everyone who needs strong parts.

### Additional information & file uploads

![layers](https://user-images.githubusercontent.com/6662401/153705153-597ba612-c95b-4c34-b68e-d7f29d60ab67.png)

**Comment by Asterchades** [comment]
Does the **Alternate Extra Wall** option (in the Walls section) no longer do this...?

**Comment by HMarxen** [comment]
Oh damn. You are right. Sorry this is redundant then.
