### ISSUE TITLE
Menu bar button has no functionality and cannot be disabled on macOS

### ISSUE THREAD

**Issue by KizzyCode** [Ultimaker/Cura#11476]
### Application Version

4.13.1

### Platform

macOS Monterey 12.2.1 (21D62)

### Printer

Ender 3 Pro

### Reproduction steps

1. Minimize Cura

### Actual results

If I minimize Cura, a big bright blue menu bar button appears (see screenshot). However this icon has no functionality and cannot be disabled either.

<img width="1512" alt="Screen Shot 2022-02-14 at 03 02 58" src="https://user-images.githubusercontent.com/13999009/153787618-dd57ebd1-0cdd-4e33-9fd3-7ba7f3dd0528.png">
 

### Expected results

The menu bar button should do something if I interact with it. Furthermore it should always be possible to disable the button entirely (e.g. via settings).

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by fvrmr** [comment]
Hi @KizzyCode thank you for your report.
I checked it on macOS Monetery 12.1 and there it also shows up and does nothing.
I will bring it up with the team. Keep you posted!

**Comment by fvrmr** [comment]
I have discussed it with the team. And we decided to defer this issue, since it will not get a high priority for us to fix right now. 
I hope you understand.

**Comment by KizzyCode** [comment]
Yeah of course; I mean this is just a minor UI inconvenience 😊

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/2687?

**Comment by KizzyCode** [comment]
This could indeed be related, however what puzzles me is that this bug exists since 2017 whereas the macOS-variant happened just recently for the first time?

**Comment by Ghostkeeper** [comment]
We didn't change anything here recently. But of course, MacOS also changes all the time.
