### ISSUE TITLE
Wall type changes depending on orientation (rotation angle z) of the part.

### ISSUE THREAD

**Issue by dtex91** [Ultimaker/Cura#11472]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Voron 2.4

### Reproduction steps

For easyness i am using cura normal profile for this. Nothing modded.

I have loaded the .stl and wondered about hilarious walls. These walls are 0.4mm thick (approved it in fusion). 
Then i tried turning the whole stl by 45 degree on the z axis and the walls changed to nice ones. 
You can also see, that the walls line type changes...this seems to be a bug i guess. Maybe this behaviour creates problems somewhere else too.

![normal_rotation0deg](https://user-images.githubusercontent.com/77171585/153734138-d7b1ee35-d871-48da-ac97-997effe7f53f.png)
![rotation45deg](https://user-images.githubusercontent.com/77171585/153734140-1afcb5dc-8f43-4e6d-be38-bbdaf042a6b3.png)

### Actual results

Single walls at 0 deg rotation are ugly and not outer perimeter ones.
At 45 deg rotation the walls appear good and are treated like outer perimeter ones.

### Expected results

Indepentand of the rotation of the part, the walls should always be treated like outer perimeter ones.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Cura_Wall_problem.zip](https://github.com/Ultimaker/Cura/files/8054789/Cura_Wall_problem.zip)

**Comment by GregValiant** [comment]
I had to drop down to .39mm Line Width to get it to slice.  I was able to turn off Print Thin walls.
![image](https://user-images.githubusercontent.com/64202104/153777598-667f25f3-64bc-4b92-b7b1-e17519692446.png)

**Comment by fvrmr** [comment]
Hi @dtex91 thank you for your report. 
In Arachne this is not a problem anymore, since Arachne uses variable line width. See https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta_2
![Capture(277)](https://user-images.githubusercontent.com/77000924/153863697-f05b377c-3cf2-4d02-987e-e4123deac968.PNG)

And since that will be the engine in our next Cura release, I will close this issue.
