### ISSUE TITLE
changing view

### ISSUE THREAD

**Issue by ruettenc** [Ultimaker/Cura#11480]
### Application Version

4.13.0

### Platform

win 10

### Printer

ender 3 V2

### Reproduction steps

open file browser from inside cura
go to folder for .stl files
change view to large icons, extra large icons

### Actual results

cura crashes and force closes

### Expected results

change view to see preview of file to choose the right one

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fvrmr** [comment]
Hi @ruettenc thank you for your report.
Does this happen when you want change the large icons? I can't reproduce this myself. 
Could you also share a log file? 
Maybe it is related to having Chitubox installed? See https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
