### ISSUE TITLE
I put a tick on "generation of supports" and nothing is generated. only manually.

### ISSUE THREAD

**Issue by LEXUS9** [Ultimaker/Cura#11489]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

anycubic vyper

### Reproduction steps

I put a tick on "generation of supports" and nothing is generated. only manually.

### Actual results

I put a tick on "generation of supports" and nothing is generated. only manually.

### Expected results

I put a tick on "generation of supports" and nothing is generated. only manually.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I put a tick on "generation of supports" and nothing is generated. only manually
![1](https://user-images.githubusercontent.com/35878957/154145457-a4fecd4d-8efc-494a-8e5f-a7f214b1b297.PNG)
.

**Comment by GregValiant** [comment]
With the model loaded use the "File | Save Project" command to save a 3mf file.  Then zip it up and post it here.

**Comment by Asterchades** [comment]
Automatically generated supports don't show on the Prepare tab (the one pictured) - only the preview (middle tab). You have to slice the model after telling it to generate them, then switch to the preview of said slice, before you can see where they're going to be.

**Comment by LEXUS9** [comment]
[AV_cat_rogue.zip](https://github.com/Ultimaker/Cura/files/8101988/AV_cat_rogue.zip)




> With the model loaded use the "File | Save Project" command to save a 3mf file. Then zip it up and post it here.

**Comment by GregValiant** [comment]
This is with no changes to the 3mf file.  (It's a different model.)
Did you switch to the "Preview" window as @Asterchades suggested?
![image](https://user-images.githubusercontent.com/64202104/154799561-30d6dbf2-15e0-41cc-a40f-5d9dcb4a7283.png)

**Comment by LEXUS9** [comment]
> Automatically generated supports don't show on the Prepare tab (the one pictured) - only the preview (middle tab). You have to slice the model after telling it to generate them, then switch to the preview of said slice, before you can see where they're going to be.

thank you very much. i'm a dumb newbie

**Comment by Asterchades** [comment]
We were all beginners at some point. Some of us learn by experimenting, others by asking questions - both are perfectly valid ways to improve.
