### ISSUE TITLE
Gaps in Walls Using Lightening Infill

### ISSUE THREAD

**Issue by bill-orange** [Ultimaker/Cura#11490]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Anet AM8

### Reproduction steps

1. Create an STL of a cylinder.
2. Slice with Cura using your favorite settings with Lightening infill and Z-seam  NOT random.
3. Print and observe large gap in horizontal wall.
4. Try a reprint with Combing off.  the result is better but not good.

### Actual results

Large gap in cylinder wall at Z-seam.

### Expected results

Observable Z-seam but no gap.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AM8_height gage_1.zip](https://github.com/Ultimaker/Cura/files/8074794/AM8_height.gage_1.zip)
![IMG_0618](https://user-images.githubusercontent.com/18121312/154150221-ca6d7ac8-1055-4a76-b406-3dd2c4e945c6.jpg)

**Comment by fvrmr** [comment]
Hi @bill-orange thank you for your report.
This is not an issue with Lightning Infill but you have coasting enabled. When disabling this settings it will not show these gaps.
![Capture(283)](https://user-images.githubusercontent.com/77000924/154438448-c9c4574d-4a65-4a52-8f0a-9f36fa5b93e7.PNG)

I will close this issue, but feel free to reach out if you have questions.
