### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by sdbruder** [Ultimaker/Cura#11514]
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Creality Ender 3 S1

### Reproduction steps

trying to print a thin and big wing with 99999999 top layers

### Actual results

slice failed.

### Expected results

successful slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[not_slicing.zip](https://github.com/Ultimaker/Cura/files/8103054/not_slicing.zip)

**Comment by GregValiant** [comment]
When a setting box turns orange Cura is giving a warning.  You kind of mis-stated the number.  The 3mf file shows you asking for 9,999,999,999 top layers.  That may be too many digits for a variable in the program.  The model slices with 1087 layers.  Try using a number that is closer to reality.
999,999,999 slices.  9,999,999,999 does not.  That extra 9 billion layers seems to be the issue.

**Comment by fvrmr** [comment]
Hi @sdbruder thank you for your report.
@GregValiant is correct that the top layers are causing this. 
I will bring this up with the team. Keep you posted.

**Comment by sdbruder** [comment]
thanks for the fix, that will not allow stupid values like the one I used.

Thanks!

**Comment by nallath** [comment]
Well, in your defense, it also doesn't break on all operating systems.
