### ISSUE TITLE
Crash on file open.

### ISSUE THREAD

**Issue by NDeepDesigns** [Ultimaker/Cura#11528]
### Application Version

4.13.0 and 4.13.1

### Platform

Win 10

### Printer

Ender 5 plsu

### Reproduction steps

Tried to open a file

### Actual results

Appl freezes and xloses

### Expected results

Should be able to open a file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This was working then just started all of a sudden. Uninstalled and installed new version and same issue.

**Comment by fvrmr** [comment]
Hi @NDeepDesigns thank you for your report.
Do you have Chitubox installed?
If so see: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file for a work around.
