### ISSUE TITLE
compatibility mode

### ISSUE THREAD

**Issue by cruising254** [Ultimaker/Cura#11520]
### Application Version

Arachne_engine_beta_2

### Platform

windows 10

### Printer

Artillery Sitewinder X2

### Reproduction steps

at some point the program switched to compatibility mode.
How to change it and restore it to normal?

### Actual results

  the preview of the object is very difficult to read.

### Expected results

n.a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![compatibilitat-mode](https://user-images.githubusercontent.com/44414810/154930829-52044c6f-bc4f-4512-a5eb-b502f1398b3a.png)

**Comment by GregValiant** [comment]
Welcome to my view of the world.  There are a couple of things to check (I'm on Windows but I think this applies to other Operating Systems):
In Cura under "Preferences/Configure Cura/General" is a section for Viewport Behavior.  One of the settings is "Force Layer View Compatibility Mode".  If it is checked then de-select it.  Re-start Cura and see how it goes.

Cura requires that your video sub-system supports OpenGL 4.1.  If it doesn't, or if you have both an onboard video system and a dedicated video card, then maybe Cura is working off the onboard system and it isn't as capable as the dedicated system.  That would drop Cura into Compatibility Mode by default (this is the case with my laptop that doesn't support OpenGL 4.1).  You would need to change something in the Operating System/Video System to get Cura working with the more capable dedicated video sub-system.
