### ISSUE TITLE
raft loses smooth top layers

### ISSUE THREAD

**Issue by Duf571** [Ultimaker/Cura#11543]
### Application Version

14.3.1

### Platform

windows 10

### Printer

flsun qqs

### Reproduction steps

using the fl sun qq to print and cura seems to lose the top smooth layers of the raft when printing . no issue with the ender 3. 

### Actual results

print doesnt stick to raft and is ruinned

### Expected results

i expect it to work properly 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

if i reload cura it works for a few prints then it disappears again

**Comment by fvrmr** [comment]
Hi @Duf571 thank you for your report.
Could you share both project files (file - save project) as a zip here?

**Comment by Duf571** [comment]
Nothing I do will make this layer stick .  this pla produced a beautiful mask not 2 days ago on this flsun.   Now I get this.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by fvrmr** [comment]
Hi @Duf571 could you post that on Github, I don't see your attachments since you've replied via e-mail.

**Comment by Duf571** [comment]
Give it a shot. Not sure



Sent from my Galaxy



-------- Original message --------
From: Fenne ***@***.***>
Date: 2022-02-25 10:34 (GMT-05:00)
To: Ultimaker/Cura ***@***.***>
Cc: Duf571 ***@***.***>, Mention ***@***.***>
Subject: Re: [Ultimaker/Cura] raft loses smooth top layers (Issue #11543)


Hi @Duf571<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDuf571&data=04%7C01%7C%7Cc7dcc34f530f48ed57b808d9f87455e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637814000820098891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1Xr78jx3GakXL9rqwjbY%2B%2FYqC2SI%2BJ7VIungBTsUhvw%3D&reserved=0> could you post that on Github, I don't see your attachments since you've replied via e-mail.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11543%23issuecomment-1050957682&data=04%7C01%7C%7Cc7dcc34f530f48ed57b808d9f87455e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637814000820098891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nDzlO3WP49DFyB1DNFlsUfE4SBC4QZc0Lh5Z5YKCF4I%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX55SDCTUJ6Y6DBYBGKA6YLU46OQ5ANCNFSM5PI54BQQ&data=04%7C01%7C%7Cc7dcc34f530f48ed57b808d9f87455e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637814000820098891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=i5kd2BQNJmcLcDfZ%2BlHotQko2J1udfA6s8OHh%2FI1snI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc7dcc34f530f48ed57b808d9f87455e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637814000820098891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2UQKNSrTRcL5r6J0uz6pYIFpm4%2FK%2FTJoxxE7c2rtrwY%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc7dcc34f530f48ed57b808d9f87455e9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637814000820098891%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u6Osuvm6a2Mm9oQ269huqWFdKAYnuPwuI5sPxx3pw2Q%3D&reserved=0>.

**Comment by Duf571** [comment]
Ive tried to attach files and its not working.
Ive tried all settings I can think of ... really ired of your software dropping settings on me. It worked fine for weeks. Now its garbage. Is this your ploy to make be my the full version ?
It wont adhere to the bed. It rips out its own infill. Truly junk

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Ghostkeeper** [comment]
Github removes e-mail attachments. To send attachments, you'd have to go back to [your issue on the Github website](https://github.com/Ultimaker/Cura/issues/11543) to post them there.

There is no "full version" (or non-full version) of Cura. Just the one you're using.

Have to keep in mind that we don't have your printer. We can't see if the print sticks to the raft or not, because on other printers this will be totally different. We can only see if the g-code output is correct. So we can only help out if it can be pointed out what's wrong in the g-code output.

**Comment by Duf571** [comment]
I will try again once I'm home




Sent from my Galaxy



-------- Original message --------
From: Ghostkeeper ***@***.***>
Date: 2022-03-12 14:40 (GMT-04:00)
To: Ultimaker/Cura ***@***.***>
Cc: Duf571 ***@***.***>, Mention ***@***.***>
Subject: Re: [Ultimaker/Cura] raft loses smooth top layers (Issue #11543)


Github removes e-mail attachments. To send attachments, you'd have to go back to your issue on the Github website<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11543&data=04%7C01%7C%7C37ce071c0102449b013f08da0457d7d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827072569901508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VYyB6Djd%2B8ZSBH%2BkVomA%2FyoXgtytUrwOG2AyCxg8q0A%3D&reserved=0> to post them there.

There is no "full version" (or non-full version) of Cura. Just the one you're using.

Have to keep in mind that we don't have your printer. We can't see if the print sticks to the raft or not, because on other printers this will be totally different. We can only see if the g-code output is correct. So we can only help out if it can be pointed out what's wrong in the g-code output.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11543%23issuecomment-1065939294&data=04%7C01%7C%7C37ce071c0102449b013f08da0457d7d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827072569901508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pjLY6i58WS3k2KwKl664X8U1nkjMNE%2FpTvZ6zuPPfnk%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAX55SDAPPSXESP4PYM7PWPLU7TQLPANCNFSM5PI54BQQ&data=04%7C01%7C%7C37ce071c0102449b013f08da0457d7d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827072569901508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T%2B9LAjYFuFitGSD840UcfMVulIJo%2F1CZ0DqwPnlCo1I%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C37ce071c0102449b013f08da0457d7d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827072569901508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6rQQnXQfJKk9LsriDUko14zy5DRVFfOLwY28iU%2FvN%2Bw%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C37ce071c0102449b013f08da0457d7d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637827072570057735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=a5F4X6oqn36kVBfE%2FqPXlHyrWT3F3gvPIlUY9XidUnM%3D&reserved=0>.
