### ISSUE TITLE
Build volume decreased to unusable size

### ISSUE THREAD

**Issue by Bryandewet** [Ultimaker/Cura#11554]
### Application Version

4.13.1

### Platform

windows 11

### Printer

ender 2

### Reproduction steps

Opened Cura and attempted to slice a part. the usable build volume decreased substantially from 150 mm by 150 mm to about 30x30mm
![image](https://user-images.githubusercontent.com/61828483/155838450-9a23b19c-dd04-46d7-b006-548453e45dba.png)
![image](https://user-images.githubusercontent.com/61828483/155838461-ac5da693-50d9-4bae-9020-825fbd038244.png)

### Actual results

build surface is reduced

### Expected results

Build surface should remain what is entered or set in machine configuration

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

let me know if the file is required

**Comment by pixie-wrangler-irl** [comment]
They pulled this crap on the Ender 3 profile too. This looks very similar.  Someone decided to disable 20% of build volume for no reason.  Here is a YouTube guide on how to fix this, https://www.youtube.com/watch?v=Il1sierB4Yk

**Comment by GregValiant** [comment]
The Ender 3 has the "disallowed areas" whereas the Ender 2 (and many other Creality printers) does not.  Why Creality decided the E3 needed them but the E3Pro did not, I have no idea.
@Bryandewet did you check your "Build Plate Adhesion" settings"  If you have a really wide brim or a large gap between the skirt and the model then you can get a necked down build surface as a lot of room has to be set aside for something like a 50mm wide brim.

**Comment by nallath** [comment]
> They pulled this crap on the Ender 3 profile too. This looks very similar. Someone decided to disable 20% of build volume for no reason. Here is a YouTube guide on how to fix this, https://www.youtube.com/watch?v=Il1sierB4Yk

We don't pull "crap" on profiles. They are as they are contributed to us. If you feel that they are incorrect, please make a pull request to fix them. We can't test third party profiles so we have to rely on contributions.

As for the original issue, I've added a creality ender-2 myself and I don't get the same result, so it's probably as @GregValiant mentiones: One or more settings are changed that cause this. You can find more info on https://support.ultimaker.com/hc/en-us/articles/360013799339-How-to-print-the-maximum-build-volume-in-Ultimaker-Cura
