### ISSUE TITLE
A Simple Ability To Export Print Settings For Sharing (This would be useful for uploading to Thingiverse, etc)

### ISSUE THREAD

**Issue by jackharvest** [Ultimaker/Cura#11556]
### Is your feature request related to a problem?

- Issue: We cannot quickly share our print-job settings with others that have different printers. This would help to ensure print jobs are consistent when having someone else print it on their printer.

### Describe the solution you'd like

The exported settings could be text. It could be a small picture. Whatever the case may be, it would be nice to have it export all the print settings so that explaining what you may have done to get the results you did become easier to collect and share on sites like Thingiverse, Reddit, etc.

### Describe alternatives you've considered

Right now the workaround is to take multiple screenshots of important non-default settings, or typing it all out by hand after reviewing it all manually. It takes forever, and most people simply don't share their print settings as a result.

### Affected users and/or printers

Everyone that uploads print settings would benefit greatly.

**Comment by fieldOfView** [comment]
1. Save a project with File -> Save project... 
2. Share the project.

You can even share a project of an empty buildplate.

**Comment by jackharvest** [comment]
Doesn’t this include details like the build-plate size, and other unwanted-because-it-isn’t-the-same-for-everyone kinds of stuff?  Jack ***@***.*** | https://jackharvest.com  From: Aldo HoebenSent: Saturday, February 26, 2022 10:27 AMTo: Ultimaker/CuraCc: Jackharvest; AuthorSubject: Re: [Ultimaker/Cura] A Simple Ability To Export Print Settings For Sharing (This would be useful for uploading to Thingiverse, etc) (Issue #11556) Save a project with File -> Save project...Share the project.You can even share a project of an empty buildplate.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by yet-another-average-joe** [comment]
Did you try these plugins :
Import/Export CSV Profiles : save / restore / merge profiles ; readable /editable as a spreadsheet
Export HTML Cura Settings : writes settings to a HTML file from  the "File/Save Project..." menu item

(I always save my projects with these two files)

**Comment by fvrmr** [comment]
Hi @jackharvest thank you for your request. 
@yet-another-average-joe is correct that these plugins will do what you would like. 

I will close this issue, but reach out if you have questions.
