### ISSUE TITLE
Add deb files in packages when compiling

### ISSUE THREAD

**Issue by TheRealOne78** [Ultimaker/Cura#11555]
### Is your feature request related to a problem?

Most debian based linux distros just like the popular ubuntu and mint have in their repositories the version 4.4.3 as latest cura. The AppImage `github packages` provides is good as a portable program, but for fixed(personal) computers just like most people it would be more wise to install cura directly in the computer than keeping the AppImage somewhere you know, or moving/replacing the AppImage everytime there is a new update.

To move to the AppImage to /bin, you would need to download the file somewhere with write permision, open a terminal to the location of the file, making the AppImage executable and move it to /bin. This is a 4-5 steps approach. 
In case you want to open cura with just `cura` command instead of cura_verxx_.AppImage, you would need to make inside /bin an executable shell file named "cura" that executes cura's AppImage or make an alias inside your shell rc, which is gross for not-experienced users and in case you want to open cura from the menu, you would need to create a .desktop file with cura's AppImage and import the .desktop file to the menu. Most un-experienced users don't even know that this can be approached by users.

However downloading a deb file from github packages, opening a terminal to specific location and entering `sudo apt install ./cura_verxx_.deb` is a 3-4 step process where you don't need to make yourself an alias/sh file in /bin and make yourself a start menu entry, the deb file makes it automatically.

### Describe the solution you'd like

Make .deb files that places `cura` in executable path and imports a .desktop file of cura to the menu when compiling and put then in the packages list.

### Describe alternatives you've considered

The other alternative would be to ask the maintainers of the deb repositories to update this by themselves. However it would be more wise to both put the deb files in the packages and update the repositories. There may be as well the risk of the maintainers not cooperating, but the attempt is not dead.

### Affected users and/or printers

Only debian based distro users will benefit from this, but other distros like arch or gentoo already have maintained repositories.

### Additional information & file uploads

Here is a link providing a series of links showing how to make a .deb file
https://duckduckgo.com/?q=how+to+make+deb+files&t=newext&atb=v298-1&ia=web

**Comment by fvrmr** [comment]
Hi @TheRealOne78 thank you for your request.
I checked with a developer and we switched from Deb packages to AppImage because Deb packages caused a lot of issues. 
Here you can see when we made that switch: https://github.com/Ultimaker/Cura/issues/718#issuecomment-266382730
See also: https://github.com/Ultimaker/Cura/issues/2634

I will close this issue, I hope you understand.
