### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by GameKyuubi** [Ultimaker/Cura#11580]
### Application Version

4.13.1

### Platform

Archlinux 5.16.11-arch1-1 Nvidia 510.54

### Printer

Monoprice MP10

### Reproduction steps

- Load model
- Try to slice

### Actual results

"Slicing failed with an unexpected error."

### Expected results

Slicing should complete successfully.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_chain01.3mf.zip](https://github.com/Ultimaker/Cura/files/8163751/CFFFP_chain01.3mf.zip)

[cura.log](https://github.com/Ultimaker/Cura/files/8163769/cura.log)

**Comment by Toddi3D** [comment]
Same Problem here

**Comment by fvrmr** [comment]
Hi @GameKyuubi thank you for your report.
I could slice your project file with no issues.
![Capture(293)](https://user-images.githubusercontent.com/77000924/157018427-2a96f5c5-235c-465f-b68e-1d3d4e1eb1c4.PNG)


Are you using the AppImage?

**Comment by Toddi3D** [comment]
Its not my fiie
-------- Ursprüngliche Nachricht --------Von: Fenne ***@***.***> Datum: 07.03.22  11:57  (GMT+01:00) An: Ultimaker/Cura ***@***.***> Cc: Toddi3D ***@***.***>, Comment ***@***.***> Betreff: Re: [Ultimaker/Cura] Slicing failed with an unexpected error (Issue #11580) 
Hi @GameKyuubi thank you for your report.
I could slice your project file with no issues.

Are you using the AppImage?

**Comment by fvrmr** [comment]
@Toddi3D could you share your file in the other thread you created: https://github.com/Ultimaker/Cura/issues/11598?

**Comment by GameKyuubi** [comment]
> Hi @GameKyuubi thank you for your report. I could slice your project file with no issues. 
> Are you using the AppImage?

I installed from AUR, version 4.13.1-1

**Comment by fvrmr** [comment]
@GameKyuubi we don't support that version, only the AppImage you can find here: https://github.com/Ultimaker/Cura/releases/tag/4.13.1
Please report your issue to the maintainer of that version. If you run into issue with the AppImage let us know.

I will close this issue.
