### ISSUE TITLE
Cura ppa UM3 connect missing

### ISSUE THREAD

**Issue by peteruithoven** [Ultimaker/Cura#1158]
I'm not sure whether this is the right place for this issue, but I'm having an issue with the Cura version on the ppa. For some reason the Ultimaker 3 connect buttons are missing. @thopiekar is this something you can help with? 

Cura 2.3.1 AppImage:
![cura 2 3 1 appimage](https://cloud.githubusercontent.com/assets/523210/20429037/82d24ebc-ad8c-11e6-96db-8a05aa4a97fe.png)

Cura 2.3.1 PPA:
![cura 2 3 1 ppa](https://cloud.githubusercontent.com/assets/523210/20429050/8ea5991a-ad8c-11e6-91c7-7248ad2dd8b5.png)

Let me know if there is something I can check.

**Comment by thopiekar** [comment]
Hey @peteruithoven ,

yes, this is the right place. Also my own repository called "Cura-packaging" would be fine, but as long as you mention me here, I get directly notified.

You probably missed to add needed plugin for the UM3
Here is the list of extra plugins, which are available in my stable PPA:
```
cura-extra-plugin-octoprint Cura plugin - OctoPrint
cura-extra-plugin-postprocessing Cura plugin - PostProcessing
cura-extra-plugin-um3networkprinting Cura plugin - UM3NetworkPrinting
cura-extra-plugins-all Cura plugin meta-package
```
Make sure you've installed `cura-extra-plugins-all` or `cura-extra-plugin-um3networkprinting`.

Finally, have you used any instruction to install Cura via PPA?
I guess I should mention the extra plugins in the thread in the Ultimaker forums :thinking:

**Comment by peteruithoven** [comment]
Awesome. After installing those the connect button appeared right away. 

Ah, sorry never found those instructions. Only read the instructions on:
https://launchpad.net/~thopiekar/+archive/ubuntu/cura

**Comment by thopiekar** [comment]
No problem. Wish you a lot of fun!

Ah, these are outdated. Thank you for the hint.
I'm at the moment working on the PPA. So as it seems to work for you at the moment, please don't do any updates to Cura at the moment.
Will give you feedback (or simply close the issue here) when everything is save again :wink:

**Comment by thopiekar** [comment]
Stable PPA is now back again and completely built on 2.3.1, as Ultimaker does.
