### ISSUE TITLE
'Minimum Bridge Wall Length' not coinciding with 'Infill Line Distance' 

### ISSUE THREAD

**Issue by Calibr8tion** [Ultimaker/Cura#11582]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1.Set cubic infill line distance to 8mm
2. Set Bridging 'minimum wall length' 10000mm

### Actual results

Treats first top layer as a slower bridging layer.

### Expected results

Expected to treat first top layer as a normal layer without using bridging settings.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Stand for external case.zip](https://github.com/Ultimaker/Cura/files/8167134/CE3PRO_Stand.for.external.case.zip)

**Comment by smartavionics** [comment]
The clue is in the name, the "minimum bridge WALL length" affects how WALLS are printed, not skins. And, yes, as you have discovered the "bridge sparse infill max density" affects how skins are printed over sparse infill.

**Comment by Calibr8tion** [comment]
> The clue is in the name, the "minimum bridge WALL length" affects how WALLS are printed, not skins. And, yes, as you have discovered the "bridge sparse infill max density" affects how skins are printed over sparse infill.

Ahh yes, thanks for pointing that out. So I guess I accidentally found that the 'bridge sparse infill max density' isn't jiving with my infill density that I have currently active? Infill density is 15% and sparse density at only 6% triggers the bridging feature. I do believe that feature should be active until 15% in this instance? I could be misinterpreting that as well?

**Comment by smartavionics** [comment]
The "bridge sparse infill max density" sets a threshold value, when the infill density for the part is less than that threshold, the infill is considered to be sparse and not capable of properly supporting the skin above, so the skin may be printed using the bridge settings. So an infill density of 15% should not be considered sparse and I wouldn't expect the skin above to be printed using the bridging settings. I'll take a look at your project tonight.

**Comment by fvrmr** [comment]
Hi @Calibr8tion thank you for your report.
I will bring it up for discussion, keep you posted.
