### ISSUE TITLE
multiple files transfer from fusion 360 bug

### ISSUE THREAD

**Issue by jorjito89** [Ultimaker/Cura#11585]
### Application Version

4.13.1

### Platform

Mac 

### Printer

N/A

### Reproduction steps

transfer multiple files from Fusion 360 to Cure.

### Actual results

it will ask to reload and erase the first file and copy the last files transfer. is not the file I try different designs and stl binary,
stl ascII, 3MF. it does the same thing for all of them. 

### Expected results

Just transfer without erase the first file and make a copy of the last file transfer. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

N/A

**Comment by DivingDuck** [comment]
This is not a bug. It depends on how you export bodies from your design with Fusion360. You choose the wrong way of export.

For your particular situation you need to make first all wanted bodies / components of your design visible and hide all components/bodies you don't want to export. Then select the uppermost structure of your design with [right mouse click] and export this via [Save as Mesh] like shown below:

![Fusion360CuraExpMultBodies1](https://user-images.githubusercontent.com/8143022/156896590-69cf9f84-2c82-456f-9828-cfb1f6d6320c.PNG)

Take attention to the entry [Structure]. This should be in your case [One File] and Output is [Send to 3D Print Utility] selected like Cura. Now Fusion360 will export all visible bodies included as one file to Cura. Cura will place them at 0,0 position as shown below.

![Fusion360CuraExpMultBodies2](https://user-images.githubusercontent.com/8143022/156897031-a2bccd5f-0865-4a35-8b3b-855caf2e99ab.PNG)

You will notice that there are now multible bodies listed (as selected in Fusion in step one). Arrange the bodies on your build plate and you are ready for printing.

![Fusion360CuraExpMultBodies3](https://user-images.githubusercontent.com/8143022/156897131-eb94ad82-35ad-4e64-855d-8552022a7ffd.PNG)

Be careful on how you export something with Fusion360. Eg. exporting via menu -->Utilities -->Make have a different result. It will export the visible bodies as one mesh.

**Comment by fvrmr** [comment]
Hi @jorjito89 thank you for your report.
Could you let us know if @DivingDuck suggestion is correct?
