### ISSUE TITLE
cant slice my models ... nothing

### ISSUE THREAD

**Issue by Toddi3D** [Ultimaker/Cura#11598]
### Application Version

Arachne 2 beta

### Platform

Windows 10 64

### Printer

Anycubic Vyper

### Reproduction steps

loading model but cant slice it, nothing

### Actual results

see above

### Expected results

nothing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8178779/cura.log)
![Screenshot (38)](https://user-images.githubusercontent.com/95543715/156591031-7fa5495c-0ca8-400e-8bbb-c347a46b9cc4.png)

**Comment by GameKyuubi** [comment]
Maybe the same problem here #11580?

**Comment by fvrmr** [comment]
Hi @Toddi3D thank you for your report.
Could you share your project file? (file - save project) You can share it in a .zip here on Github.
