### ISSUE TITLE
G code View/Edit

### ISSUE THREAD

**Issue by brushmake** [Ultimaker/Cura#11603]
### Is your feature request related to a problem?

Cura does not have a way to view/edit the G code after slicing. 

### Describe the solution you'd like

I would like to see a text editor in Cura for viewing, searching, replacing, and editing the G code after slicing. Cura is my Goto slicer.  

### Describe alternatives you've considered

I have had to open the G code in a text editor to check the G code.

### Affected users and/or printers

All users could use this feature.

**Comment by Ghostkeeper** [comment]
See also https://github.com/Ultimaker/Cura/issues/7621, which is a similar feature request (almost duplicate?). Some of the difficulties in implementing this have been explained there.
