### ISSUE TITLE
Installer asks if I want to delete all my profiles when just upgrading to a newer version

### ISSUE THREAD

**Issue by Christanoid** [Ultimaker/Cura#11614]
### Is your feature request related to a problem?

Whenever I update cura the uninstaller of the old version will ask if I want to remove my old Profiles

### Describe the solution you'd like

The remove everything question is good when actually uninstalling, but the installer of the new version should tell the old version via an launch argument to not ask for that.
I and multiple friends of mine have at least once nuked out profiles due to a missclick on that pop-up. 

### Describe alternatives you've considered

None.

### Affected users and/or printers

People updating are affected

**Comment by fvrmr** [comment]
Hi @Christanoid thank you for your request.
We are aware of this and we have multiple reports about this. We have a ticket on our backlog to change the message during the installation process.
See also: https://github.com/Ultimaker/Cura/issues/8233

I will close this issue, since it is a duplicate.
