### ISSUE TITLE
Update profile with current settings/overrides. Greyed out and won't work

### ISSUE THREAD

**Issue by oscarmemo** [Ultimaker/Cura#11618]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

CR-10

### Reproduction steps

Quitting Cura and trying again.
Restarting computer
swap to ender 3 pro profile and back (CR-10 can update profile)
checked all plugins were enabled
Updated Cura to 4.13
changed between profiles while keeping settings and not keeping
![SETTING](https://user-images.githubusercontent.com/101086379/156978294-de28bf06-f9a8-470c-a104-04d407e96c16.png)

### Actual results

No change button is still greyed out and won't perform action

### Expected results

Current settings should be saved to profile

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![SETTING](https://user-images.githubusercontent.com/101086379/156978477-509d49e1-716a-4879-b51c-f6c84dc6e4a3.png)

**Comment by 64bittuning** [comment]
Have you tried actually changing any settings before trying to save them? I build profiles like this all the time.

**Comment by nallath** [comment]
Well, I don't see a star in the dropdown, so I'm guessing that no settings have been adjusted and as such, all options are greyed out.
