### ISSUE TITLE
Requesting Customization Interface

### ISSUE THREAD

**Issue by sunheat** [Ultimaker/Cura#11615]
### Is your feature request related to a problem?

Is there currently a way to customize Cura so the icons and background images can be changed?

### Describe the solution you'd like

I would like the ability to replace the default image resources which are included in the standard Cura build.

### Describe alternatives you've considered

N/A

### Affected users and/or printers

N/A

**Comment by nallath** [comment]
Yeah. Have a look at the /resources/themes folder. You will see 4 folders there, each representing a theme that is currently supported by Cura. "Cura-light" is the default theme.
