### ISSUE TITLE
Cura 4.13.1 fails to print vertical holes and strangely prints a halfway wedge in horizontal holes

### ISSUE THREAD

**Issue by paulbauwens** [Ultimaker/Cura#11612]
### Application Version

Cura 4.13.1

### Platform

Windows 10

### Printer

Ender 3 + Marlin Bugfix may 2021 on  Ender 3 32bit 4.2.7 motherboard wiht 

### Reproduction steps

I am using Marlin Bugfix mat 2021 on an Ender3 4.2.7  32-bit motherboard with BLtouch no such issues before
I checked the STL files with Tinkercad, they look completely OK

Slicing and Printing STL files form this public source:

https://www.prusaprinters.org/prints/123038-table-clamp-for-miniature-vice-30-100-printed

file:  Table protector for clamp V3.0.stl  fails to print the hole in the bottom for the screw after Cura slicing
file:  Table clamp for miniature vice V3.0.stl   prints strange wedges halfway through the horizontal holes in all 4 holes
prints are otherwise completely smooth , 0.2 mm layer height
Using Grid infill pattern and 40% infill

![cura13bug](https://user-images.githubusercontent.com/90704674/156884626-fe269e45-9ea2-4730-a3f3-2720ca7ffd19.jpg)

P.S.  I re-sliced these files with Cure 4.12.1 and the problem does not appear, perfect usable prints

### Actual results

You can reproduce the wedge in de big hole of file  Table clamp for miniature vice V3.0.stl   This makes the print unusable.

The other three smaller holes in this object will also have a wedge halfway in the hole

### Expected results

The expected result was a hole without the wedge with a smooth thread for the accompanying printed screw.

The small nick in the photo was a result from my attempt to remove the wedge

Slicing and printing the Table protector for clamp V3.0.stl  shows a massive print without the hole in the bottom

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8190747/cura.log)
[cura_cfg.txt](https://github.com/Ultimaker/Cura/files/8190754/cura_cfg.txt)

**Comment by GregValiant** [comment]
In Mesh Fixes -turn off "Make overhangs printable" and "Remove all holes".

**Comment by paulbauwens** [comment]
Thanks, I will try this.  I can’t remember ever touching this setting, coukd it come from the defaults?
Regards, PaulBauwens

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: GregValiant ***@***.***>
Verzonden: Saturday, March 5, 2022 4:30:31 PM
Aan: Ultimaker/Cura ***@***.***>
CC: Paul Bauwens ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Ultimaker/Cura] Cura 4.13.1 fails to print vertical holes and strangely prints a halfway wedge in horizontal holes (Issue #11612)


In Mesh Fixes -turn off "Make overhangs printable" and "Remove all holes".

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11612%23issuecomment-1059783500&data=04%7C01%7C%7C643f8034b21e485ce0ec08d9febd1618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820910332820340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rEQSC357qV33P2wHvBbxojhKz0%2BrpN7lCLzowg0QmVU%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVUAWIU2ST4ZQRKERWES5C3U6N4ZPANCNFSM5P7XIIQQ&data=04%7C01%7C%7C643f8034b21e485ce0ec08d9febd1618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820910332820340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IJjVTlxVxDEy3xAD%2F4pYfgpjlRv5X0o%2FY%2BaknDmaPV4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C643f8034b21e485ce0ec08d9febd1618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820910332820340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iwYqI6SYdhZsCJb0WJ0Jg90tutgUk5elxIBXHyv0mjg%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C643f8034b21e485ce0ec08d9febd1618%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637820910332820340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HWsmeNhz%2FAK4fYJN4zU6ggehUqcd4wsU%2FbyAj%2BVRzNM%3D&reserved=0>.

**Comment by GregValiant** [comment]
They should have been turned off by default.  I have had a couple of occasions to use Remove all Holes.  The Make Overhangs Printable setting I have never used.  I do tell lot of people to turn it off though.  Without a better look see I'm guessing it's what caused a chamfer within your horizontal holes.

**Comment by fvrmr** [comment]
Hi @paulbauwens thank you for your report.
Can you let us know if the suggestion of @GregValiant worked for you?

**Comment by paulbauwens** [comment]
I will check and teport didnt have time yet

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Fenne ***@***.***>
Verzonden: Monday, March 7, 2022 11:40:45 AM
Aan: Ultimaker/Cura ***@***.***>
CC: Paul Bauwens ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Ultimaker/Cura] Cura 4.13.1 fails to print vertical holes and strangely prints a halfway wedge in horizontal holes (Issue #11612)


Hi @paulbauwens<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaulbauwens&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480263869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v64X4UCKqcDyDLZxriAg%2Bz0gph0oh1Yd%2B1GN0T2Wmm0%3D&reserved=0> thank you for your report.
Can you let us know if the suggestion of @GregValiant<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGregValiant&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480263869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eGeS2szI0i3YIQHZQ5yDfX6nopA1EsRGTlf52lhrqtM%3D&reserved=0> worked for you?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F11612%23issuecomment-1060479046&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480420094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T%2B6EF4hZa6ueBYKc%2FDrSWzlMm0dpW%2FcFtAHuG4yRyK4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVUAWISM4CWG7YTFAHVER7LU6XMK3ANCNFSM5P7XIIQQ&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480420094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cic2cmcjZfJe0ISxs18cXGMau%2F03gva4qasMDwUul%2Fg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480420094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iHOEYGaoecDR9vHNd%2FwftYCEHdzx72JvumF3DHtEi74%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cf9a78ebe92f14ce9114008da0026f03e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637822464480420094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LFTvUGeZoRqHNOiwE%2BCsRhLYM6DlluqHiC%2BdiA2haY8%3D&reserved=0>.
