### ISSUE TITLE
Export Model with changes CURA has done to it.

### ISSUE THREAD

**Issue by eGit** [Ultimaker/Cura#11621]
### Is your feature request related to a problem?

Cura can do some modifications to a model. For example the feature "make overhangs printable". It alters the mesh of the model before slicing. When I "Export" such a model it exports the original model and not the model mesh after Cura's changes - which is what I want.

### Describe the solution you'd like

Export should export the original model in the "Prepare" workspace and the modified model in the "Preview" workspace.

### Describe alternatives you've considered

There are none to my knowledge. Cura can do so many modifications to a model and there is no way to access that modified internal model.

### Affected users and/or printers

People who want to look or use the modified internal mesh from Cura.

**Comment by fvrmr** [comment]
Hi @eGit thank you for your feature request. 
I will bring it up for discussion with the team, keep you posted.

**Comment by fieldOfView** [comment]
> For example the feature "make overhangs printable". It alters the mesh of the model before slicing.

Not quite. It alters the mesh of the model _while_ slicing. These changes are performed layer by layer, not on the model. At no point in time is there a polygonal model in memory that has "printable overhangs". The same is true for support structures or infill. These are not first created as a 3d model and then sliced; they are all created from sliced cross-sections of the 3d model.

**Comment by eGit** [comment]
> > For example the feature "make overhangs printable". It alters the mesh of the model before slicing.
> 
> Not quite. It alters the mesh of the model _while_ slicing. These changes are performed layer by layer, not on the model. At no point in time is there a polygonal model in memory that has "printable overhangs". The same is true for support structures or infill. These are not first created as a 3d model and then sliced; they are all created from sliced cross-sections of the 3d model.

I was afraid this to be the case. I was hoping at least things like "make overhangs printable" would be performed on the model and not during slicing. Well, I guess then it is impossible.

**Comment by fvrmr** [comment]
I have discussed it with the team and indeed @fieldOfView is correct. So we decided to reject this request since it is not possible to do this. I hope you understand.

**Comment by eGit** [comment]
> I have discussed it with the team and indeed @fieldOfView is correct. So we decided to reject this request since it is not possible to do this. I hope you understand.

No problem. Thanks for clearing this up.

**Comment by tekmouse** [comment]
@eGit ; I had this same request and found a way to do it.
Slice the object. Export as a G-Code. Download and Import to Volexir.
Once imported, select the 'Voxelize' button which is an arrow going counter-clockwise around a box, Click 'Voxelize'. I selected 0.1mm at this point.  That's as far as I have gotten but I am excited. Hope this helps you!

**Comment by eGit** [comment]
Thanks. Interesting approach. Sadly small things such as holes are completely fused shut for me in the exportet STL. I think I could increase resolution, but that has its own problems. Still, interesting approach. Thanks!
