### ISSUE TITLE
Cura 2.3.1 Wrong number of Layers 

### ISSUE THREAD

**Issue by pelikan39** [Ultimaker/Cura#1163]
The attached file  showes 4 layers  instead of 10  (hight  0.4 / layer hight 0.04 =10) Cura 15.04.4 works fine.
Is this a err
![layers](https://cloud.githubusercontent.com/assets/23613680/20462992/13781dc2-af2a-11e6-9d4e-eedfc9298e2f.JPG)
or or did  I made a configuration mistake?

**Comment by fieldOfView** [comment]
There's a setting called "Initial Layer Height" that is currently not visible in your sidebar. It's default value is 0.3.  ```0.3 + 3 * 0.04 = 0.42```, so you get 4 layers.

Click the cog-wheel next to Quality to make the Initial Layer Height setting visible. Note that you may get first layer issues with an initial layer height this small.

**Comment by pelikan39** [comment]
Thank you very much for your awnser, I followed your advise, now it works fine.
Yes initial layer hight this small is difficult, but if the bed leveling is ok it works. 
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 20/11/2016 - 14:39 (GMT)
An : Cura@noreply.github.com
Cc : pelikan39@bluewin.ch, author@noreply.github.com
Betreff : Re: [Ultimaker/Cura] Cura 2.3.1 Wrong number of Layers (#1163)
There's a setting called "Initial Layer Height" that is currently not visible in your sidebar. It's default value is 0.3.  0.3 + 3 * 0.04 = 0.42, so you get 4 layers.
Click the cog-wheel next to Quality to make the Initial Layer Height setting visible. Note that you may get first layer issues with an initial layer height this small.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ultimaker/Cura","title":"Ultimaker/Cura","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ultimaker/Cura"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fieldOfView in #1163: There's a setting called \"Initial Layer Height\" that is currently not visible in your sidebar. It's default value is 0.3.  ```0.3 + 3 * 0.04 = 0.42```, so you get 4 layers.\r\n\r\nClick the cog-wheel next to Quality to make the Initial Layer Height setting visible. Note that you may get first layer issues with an initial layer height this small."}],"action":{"name":"View Issue","url":"https://github.com/Ultimaker/Cura/issues/1163#issuecomment-261778929"}}}
