### ISSUE TITLE
default End-Gcode for Snapmaker needs to reference machine_height for Z instead of machine_width

### ISSUE THREAD

**Issue by Rolzad73** [Ultimaker/Cura#11666]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Snapmaker 2 A350

### Reproduction steps

looking at default Printer End G-code for Snapmaker A350

Preferences->Printers->Machine Settings for Snapmaker A350

```
G1 Z{machine_width} E-1 F3000 ;move Z up a bit and retract filament even more
```

should read:

```
G1 Z{machine_height} E-1 F3000 ;move Z up a bit and retract filament even more
```

https://github.com/Ultimaker/Cura/blob/c6326eff64323b5a4ab6da6532840042f78b3884/resources/definitions/snapmaker2.def.json#L32

### Actual results

default config issue

### Expected results

default config issue

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

default config issue

**Comment by fvrmr** [comment]
Hi @Rolzad73 thank you for your report.
You can change this yourself via a pull request. We don't maintain these profiles. That's why I will close this issue, but if you need help with creating a PR let me know.
