### ISSUE TITLE
(4.12.1) Adaptive Layer Max Height Unclear

### ISSUE THREAD

**Issue by not-crazyramen** [Ultimaker/Cura#11679]
### Is your feature request related to a problem?

The adaptive layer height setting does not make it clear if the selected layer height is the maximum or the median. Upon manual measurement, I found that it is the maximum.

### Describe the solution you'd like

Add "This will not exceed the layer height selected in 'Quality>Layer Height.'" to the description of Adaptive Layers.

### Describe alternatives you've considered

Clarify the same in Quality>Layer Height

### Affected users and/or printers

All users

**Comment by fvrmr** [comment]
Hi @not-crazyramen thank you for your report.
In the settings guide you can find a more detailed description of this setting. See here: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/experimental/adaptive_layer_height_enabled.md
Let me know if this description makes it clear to you how this setting works. 
You can install this plugin from the marketplace. I will check if we want to change this description.
