### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by JmSpace123** [Ultimaker/Cura#11680]
### Application Version

Ultimaker Cura 4.10.0

### Platform

Windows 7

### Printer

Didn't open the software yet

### Reproduction steps

Hello, The following error occurs after installing and running the Cura on my conputer. Seems to be an error with cx_Freeze.
I'm using Cura version 4.10.0 because looks like is the latest one compatible with Windows 7.

### Actual results

cx_freeze error

### Expected results

--

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura_error](https://user-images.githubusercontent.com/101850523/158926707-3fb02f40-b914-4543-aaf6-a208496bde0b.JPG)

**Comment by fvrmr** [comment]
Hi @JmSpace123 thank you for your report.
Could you check if you have this folder C:\\Program Files\\Ultimaker Cura 4.10.0 on your computer?
