### ISSUE TITLE
Wall Thickness {wall_thickness} is looking like a float in GCode 

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#11685]
### Application Version

4.13.0

### Platform

Windows 11

### Printer

Anycubic Mega S

### Reproduction steps

Add {wall_thickness} in GCode

### Actual results

Showing 1.2000000000000002
![notepad++_nFqOT3pSA4](https://user-images.githubusercontent.com/51311453/159134769-3747c3bb-7650-46a6-a5e0-1dbea2d2ef8b.png)

### Expected results

Should add 1.2 in GCode

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Tageslichtlampe.zip](https://github.com/Ultimaker/Cura/files/8309901/Tageslichtlampe.zip)

**Comment by GregValiant** [comment]
What software actually generated that gcode file?  Was it post-processed?  I've never seen all those ";Slicer Info" lines before.

**Comment by NilsRo** [comment]
That's included in Printer Startcode to transfer this information to OctoPrint. My plug-in Slicer Estimator shows all metadata there. So no Post-Processing.

**Comment by fvrmr** [comment]
Hi @NilsRo thank you for your report.
I can reproduce this also on a Ultimaker S5 when using a 0.3mm profile. 
I will bring it up for discussion, keep you posted.

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
