### ISSUE TITLE
Cura leave out holes and or tooth in my gears.

### ISSUE THREAD

**Issue by DennyNem** [Ultimaker/Cura#11683]
### Application Version

15.04 and 3.2.1

### Platform

Windows 10

### Printer

EcubeMaker Fantasy Pro II

### Reproduction steps

Cura leave out holes and or tooth in my gears.
![image](https://user-images.githubusercontent.com/25213972/159051419-38db7b67-d63b-42ba-91eb-9ee8f916c370.png)
![image](https://user-images.githubusercontent.com/25213972/159051519-9c935b0b-e096-47f2-816c-a1aec0c4ccb6.png)

### Actual results

the hole in the gear is not there.

### Expected results

there should be a thru hole in the gear
[Gear5.zip](https://github.com/Ultimaker/Cura/files/8306483/Gear5.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8306530/cura.log)

**Comment by fieldOfView** [comment]
Neither of those versions is supported anymore. Please try a more recent version of Cura.

Having said that, the model has inconsistent normals, and needs to be "repaired". You can use the Mesh Tools plugin, available from the Marketplace (in Cura 3.5 and newer), to fix the normals, and it will slice correctly after that.

**Comment by fvrmr** [comment]
Hi @DennyNem thank you for your report.
@fieldOfView is correct you need to use a newer version of Cura: https://ultimaker.com/software/ultimaker-cura
In 4.13.1 I fixed the model with using the Mesh Tools plugin and then it sliced correctly.
![Capture(314)](https://user-images.githubusercontent.com/77000924/159915137-468b988d-b4f9-4cef-ba38-c84652fc2412.PNG)

I will close this issue. But let me know if you have questions.

**Comment by DennyNem** [comment]
Thank you I will try it.
