### ISSUE TITLE
Marketplace materials not appearing in available materials list

### ISSUE THREAD

**Issue by AndrewLindsay** [Ultimaker/Cura#11687]
### Application Version

4.13.1

### Platform

Mac OS Monterey

### Printer

Creality Ender 5

### Reproduction steps

1. I added the Duport Hytrel material to my list of materials.
2. I rebooted Cura, and tried to select Hytrel, but it was not in the list of available materials.  I searched under all the different materials headings, in case it had been miscatagorized. 

### Actual results

I can not locate the Dupont Hytrel material as a material option in Cura, even though it appears in the material folder for the application.

### Expected results

I should be able to select the hytrel as the material for slicing my model.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screen Shot 2022-03-20 at 10 20 40 am](https://user-images.githubusercontent.com/4137215/159145172-48814f45-94f6-432e-93b7-61d4d1720cca.png)
![Screen Shot 2022-03-20 at 10 18 53 am](https://user-images.githubusercontent.com/4137215/159145175-7acb6719-0d21-42ce-99e8-82050bdb6900.png)
![Screen Shot 2022-03-20 at 10 18 47 am](https://user-images.githubusercontent.com/4137215/159145176-f43623e6-156d-4fa7-986a-b7887bd09ce0.png)
![Screen Shot 2022-03-20 at 10 18 15 am](https://user-images.githubusercontent.com/4137215/159145177-18348da4-6177-441f-9508-798ffae3fdb1.png)

**Comment by fieldOfView** [comment]
The Marketplace only contains material profiles compatible with Ultimaker printers, and Ultimaker printers use 2.85 mm filament. Your printer does not support 2.85 mm filament. I know that all those materials are also available in 1.75 mm varaints, but the profiles on the Marketplace don't include this informaiton, let alone print settings for other printers than Ultimaker printers.

**Comment by fvrmr** [comment]
Hi @AndrewLindsay thank you for your report. 
@fieldOfView is correct, see also: https://github.com/Ultimaker/Cura/issues/6236

I will close this issue, since it is a duplicate.
