### ISSUE TITLE
Al cargar stl se cierra programa.

### ISSUE THREAD

**Issue by guevaragus** [Ultimaker/Cura#11693]
### Application Version

4.12.0 beta

### Platform

win 10

### Printer

Geeetech A10M

### Reproduction steps

Tenia tiempo que no usaba mi impresora, hoy decidi usarla y ahora nada que puedo imprimir

### Actual results

Al cargar un stl, se cierra el programa, cualquier stl hace que se cierre.

### Expected results

deberia subir el stl a cura y luego imprimir.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[creality-ld-002r-ld-002h-better-drip-mount20200918-25133-15u85pe.zip](https://github.com/Ultimaker/Cura/files/8312195/creality-ld-002r-ld-002h-better-drip-mount20200918-25133-15u85pe.zip)

**Comment by fvrmr** [comment]
Hi @guevaragus thank you for your report.
Could you please fill in the form in English? Do you maybe have Chitubox installed, if so see here more information: https://support.ultimaker.com/hc/en-us/articles/4402996140946-Ultimaker-Cura-crashes-when-opening-any-file
