### ISSUE TITLE
UI Zoomed outside of screen, no icons, no model view

### ISSUE THREAD

**Issue by dcormieb** [Ultimaker/Cura#11697]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Anet A8

### Reproduction steps

On opening Cura, UI has large text, buttons have no text, there is no model view etc etc here's a screenshot https://i.imgur.com/HZj7Lk2.png

### Actual results

On opening, no steps to follow.

### Expected results

Should open the model view and populate the menus with icons etc.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Opened properly on reinstall, but when opening after the first initialization or when opening a file, UI breaks again. Even have a bugged window and OK window open at once https://i.imgur.com/QS2OiPZ.png
Turns out that the only condition which causes it to open properly is to launch from the install window. If I don't launch off install and open it afterwards, the UI prevents me from even initializing.
Saw this issue posted by someone else, did not appear to have same cause as it was to do with their username's non-latin characters. I tried creating an account for this reason but this did nothing.
Hope this can be helped.

**Comment by fieldOfView** [comment]
It seems you have two displays. In the General preferences inside Cura, try unchecking the option to "Restore window position on start".
