### ISSUE TITLE
Bring back layer count

### ISSUE THREAD

**Issue by Fass-ohne-Hoden** [Ultimaker/Cura#117]
In layer view mode, older Cura versions would indicate at which layer you're looking right now.
15.06 doesn't have that. It's useful, please bring it back.

**Comment by awhiemstra** [comment]
It is being worked on and should be available with 15.06.02 once that is released.

**Comment by nallath** [comment]
Stupid github issue tracker. It's not yet fixed, we will reaaaly close it when it is.

**Comment by TMHogenhout** [comment]
![layer_slider_proposal](https://cloud.githubusercontent.com/assets/12695732/8568364/501a441e-256d-11e5-94c3-529413f7a2e7.png)

layer slider proposal by Menno

**Comment by nickthetait** [comment]
Looks nice :smile:
