### ISSUE TITLE
Release the nozzle temperature limit

### ISSUE THREAD

**Issue by magicmaker3** [Ultimaker/Cura#11700]
### Is your feature request related to a problem?

I need to print PEEK material at 420 ℃，But it reports an error, saying the setting is wrong。

### Describe the solution you'd like

Release the nozzle temperature limit

### Describe alternatives you've considered

Release the nozzle temperature limit

### Affected users and/or printers

Users who will make more breakthroughs

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/66371323/159656953-3d9021f0-b219-4bdb-9972-6339122f1cea.png)

**Comment by fieldOfView** [comment]
In the `"overrides"` section of the printer-definition for your printer (.def.json file), you need to specify a new (higher) `"maximum_value"` for `"default_material_print_temperature"`, `"material_print_temperature"`, `"material_print_temperature_layer_0"`, `"material_initial_print_temperature"` and `"material_final_print_temperature"`.

**Comment by fvrmr** [comment]
Hi @magicmaker3 thank you for your report.
Could you let us know if you can make it work with the solution from @fieldOfView?
