### ISSUE TITLE
Line width preview incorrect for double thickness layers

### ISSUE THREAD

**Issue by gestalth** [Ultimaker/Cura#11710]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

S3

### Reproduction steps

1. Adjust line width to 0.9
2. Adjust support line width to 0.6
3. Adjust infill line width to 0.6
4. Adjust layer height to 0.3
5. Adjust support layer thickness to 0.6 (2x layer height)
6. Adjust infill layer thickness to 0.6 (2x layer height)
7. Slice a model with supports and/or infill

### Actual results

The preview shows very thick lines (and colored to match) for lines that are 2 layers thick. The thickness and coloring seem to be appropriate for 1.2mm lines not 0.6.

### Expected results

I would think it would show 0.6mm lines there.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I also tested this on the Arachne Beta 2 with the same results.

**Comment by GregValiant** [comment]
Yes, Cura works by single layers so a double layer will show as a double wide line rather than a double thick like.  It is expected behavior.
I'll go ahead and close this.  The behavior is the same in current versions.
