### ISSUE TITLE
Bouwvolume Ultimaker 3 is length 215,  width  215,  height 200

### ISSUE THREAD

**Issue by Leonav** [Ultimaker/Cura#1171]
In Cura 3.1.2 the height = maximale 150

**Comment by nallath** [comment]
There is no cura 3.1.2

**Comment by Leonav** [comment]
Sorry 1, there is no cura 3.1.2. I mean 2.3.1,
Sorry 2, the height in Cura 2.3.1 is for Ultimaker 200 mm

**Comment by nallath** [comment]
So what is exactly the issue you are reporting?

**Comment by Ghostkeeper** [comment]
As far as we know the build height is correct for all Ultimaker printers. The actual build volume may be a few millimetres higher, depending on how high you adjusted your bed. But for safety we only allow the current heights for all of Ultimaker's printers.
