### ISSUE TITLE
No support for CR-5 Pro H

### ISSUE THREAD

**Issue by bridgettegraham** [Ultimaker/Cura#11726]
### Application Version

4.13

### Platform

Windows 10

### Printer

CR-6

### Reproduction steps

Please can you add support for CR-5 Pro H

### Actual results

there is currently no support for CR-5 Pro H

### Expected results

Please can you add support for CR-5 Pro H

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional info

**Comment by GregValiant** [comment]
The definition files come from the manufacturer (Creality in your case) or a community member.  They aren't updated between Cura versions.  Is there another Creality printer that is close?

**Comment by GregValiant** [comment]
No one as added a pull request for this printer.  I'll go ahead and close this.
