### ISSUE TITLE
Import File causes program to close

### ISSUE THREAD

**Issue by noellengod** [Ultimaker/Cura#11732]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

AnyCubic Mega Pro

### Reproduction steps

1. Click Profile
2. Click Import

### Actual results

It freezes then Cura Crashes. No, I do not have Chitubox installed. =)

### Expected results

Ability to open "Import Profile" and finish setting up Cura. or ability to open anything, tried to look in other areas, crashes. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (46)](https://user-images.githubusercontent.com/102624013/160712157-c25ce172-5ed0-4328-a2a1-391ac396a135.png)

I literally can't find the log file. I looked for 30 minutes.

**Comment by fvrmr** [comment]
Hi @noellengod thank you for your report.
You can find your log here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
Without a log it is a bit hard to guess what is causing this.
