### ISSUE TITLE
The ";LAYER_COUNT:" in a gcode file is off because of a support blocker

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#11730]
### Application Version

4.13.1

### Platform

Windows 10 Home (onboard video OpenGL 4.0 in compatibility mode)

### Printer

Creality E3Pro

### Reproduction steps

Sliced a file and checked the Cura Preview - 392 layers.  I used a skirt.
Saved the gcode file.

### Actual results

Open the file in NotePad and see
;LAYER_COUNT:411
;LAYER:0
I was going to drop the temperature at layer 400, but there wasn't a layer 400.
The last layer in the file is LAYER:391 as the preview indicated it would be.

### Expected results

The layer count should be 392.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I have noticed this before.  I am not sure it happens all the time.
The gcode, project and log are included in the zip.
[LayerNumberIssue.zip](https://github.com/Ultimaker/Cura/files/8374512/LayerNumberIssue.zip)

EDIT:  Playing around some more...when a support blocker is taller than the model it adds to the LAYER_COUNT even when configured only to block supports.

**Comment by smartavionics** [comment]
It's including the top support-blocker in the layer count, when I moved that below the top of the model, the LAYER_COUNT value became 392.

**Comment by fvrmr** [comment]
Hi @GregValiant thank you for your report.
I will bring it up with the team. Keep you posted.

**Comment by GregValiant** [comment]
I checked and 5.8.0 does not have the problem.  I'll go ahead and close this.
