### ISSUE TITLE
0.1 nozzle option

### ISSUE THREAD

**Issue by DuckersMcQuack** [Ultimaker/Cura#11747]
### Is your feature request related to a problem?

I use a 0.1 nozzle for my miniature prints, but when i wanted to print at 0.1 again now, i can't see lower than 0.2 nozzle, is that a bug? As i can't remember if it was there or not last time. (i have a terrible memory)

So i want to request a 0.1 nozzle option in cura.

### Describe the solution you'd like

0.1 nozzle option for miniature prints

### Describe alternatives you've considered

using 0.2 option, but set wall thickness to 0.102 which i used to use.

### Affected users and/or printers

ender 3 pro

### Additional information & file uploads

https://cdn.discordapp.com/attachments/807157014236495882/948066575787909140/20220224_044143.jpg

One of my few 0.1 nozzle prints.

**Comment by GregValiant** [comment]
Creality provides the nozzle definitions as "variants" for their printers.  If they don't provide it you will have to do it yourself.
In Windows the Creality nozzle definition files are in the "...Cura 4.x.x\resources\variants" folder.  You can go back to your previous version and find the .1 nozzle file (something like "creality_ender3pro_0.1.inst.cfg" and copy and paste it into the "variants" folder of the new version of Cura you are using.  You could also open a "creality_ender3pro***.inst.cfg" nozzle file in NotePad and make a couple of changes and then do a save-as using the proper format for the file name.  The next time you open Cura it should show up.
