### ISSUE TITLE
[Cura 4.13.1] Tree Support does not generate Support Brim on slicing

### ISSUE THREAD

**Issue by GJSchaller** [Ultimaker/Cura#11749]
### Application Version

4.13.1

### Platform

macOS 12

### Printer

Ender 3 Pro

### Reproduction steps

- Enable Support Brim in profile
- Set support type to Tree
- Slice
- Preview output

### Actual results

The Tree support is generated, but there is no Support Brim, resulting in adhesion issues with smaller trees.

### Expected results

A support brim is generated for the tree support.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Image of output, with option selected:
![Screen Shot 2022-04-01 at 10 15 45 AM](https://user-images.githubusercontent.com/2761607/161282481-108b768e-6eef-482a-a2ca-35d7172e7471.png)

**Comment by GregValiant** [comment]
It's there.  I can see it inside the the tree trunk in your photo.  You can select "Brim" as the build plate adhesion and set the Brim Distance to 1.0 so it doesn't connect to the model but it will surround the tree.  It should give a broader base around the tree support.  The is with the brim distance at 2.0.
![image](https://user-images.githubusercontent.com/64202104/161352471-173e3556-4ad3-422c-a6f1-4943fa503977.png)
