### ISSUE TITLE
Cura slices walls, depending on model orientation

### ISSUE THREAD

**Issue by CustomGenerated** [Ultimaker/Cura#11750]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

I tried slicing my file using a "fake" vase mode (0.4 width walls, no infill). Profile is called "Wing Settings". The object was located at X=0, Y=0.
Cura was not slicing a wall correctly.

![notWorking](https://user-images.githubusercontent.com/15821951/161289067-6b5c244c-479f-43ed-9b18-15dd31e82919.PNG)

I changed both X and Y coordinates to random values. The file was then slicing correctly.

![working](https://user-images.githubusercontent.com/15821951/161289071-d6e404ff-783f-4e69-91f1-5a924bdd8b1b.PNG)

### Actual results

one wall was incorrectly sliced.

![notWorking](https://user-images.githubusercontent.com/15821951/161289067-6b5c244c-479f-43ed-9b18-15dd31e82919.PNG)

### Expected results

the wall should have been present

![working](https://user-images.githubusercontent.com/15821951/161289071-d6e404ff-783f-4e69-91f1-5a924bdd8b1b.PNG)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Project File: [CE3PRO_Fuselage.zip](https://github.com/Ultimaker/Cura/files/8398795/CE3PRO_Fuselage.zip)

**Comment by GregValiant** [comment]
When the orientation effects the slicing - that is an excellent indicator that there is a problem within the model.  Try repairing the model with MS 3D Builder or Blender or some other utility.
This report is from [https://formware.co/OnlineStlRepair](https://formware.co/OnlineStlRepair)
-> Analysed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 1 Non-manifold edges (?)
--> 1 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 2 Duplicate faces (?)
--> 0 Disjoint shells (?)
There isn't much wrong, but in certain orientations the errors confuse Cura.
