### ISSUE TITLE
Settings are sometimes not saved

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#11768]
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Anycubic Mega S

### Reproduction steps

1. Start Cura
2. Add a model
3. Changing setting like printer nozzle size, material settings or print profile or the material
4. Slice
5. Switch to monitor
6. Close Cura
7. Restart Cura, everything lost

### Actual results

**Everything** changed is lost. I thought it was just switching to an old material first but after switching to a different nozzle I see that **everything** is lost changed in this session.

### Expected results

Changed settings should be saved.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Extensive Logging Plugin was installed...

Sounds similar to https://github.com/Ultimaker/Cura/issues/11358

[4.13.zip](https://github.com/Ultimaker/Cura/files/8412077/4.13.zip)
[stderr.zip](https://github.com/Ultimaker/Cura/files/8412074/stderr.zip)

Video to reproduce:
[Ultimaker Cura 2022-04-04 20-00-24.zip](https://github.com/Ultimaker/Cura/files/8412062/Ultimaker.Cura.2022-04-04.20-00-24.zip)
Result after restart: ![Cura_uFnrH4PIpB](https://user-images.githubusercontent.com/51311453/161604224-63326cbe-2237-4ee8-88fb-adf77f23811b.png)

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
