### ISSUE TITLE
[BUG] Slicing supports in diagonal way are too close to object

### ISSUE THREAD

**Issue by tispokes** [Ultimaker/Cura#11775]
### Application Version

4.13.1

### Platform

W11

### Printer

SWX1

### Reproduction steps

Layer height: 0.12 mm
Support X/Y distance: 0.8 mm
Support Z distance: 0.24 mm
Generate supports in Zig Zag from buildplatform

### Actual results

Supports are too close in diagonal

### Expected results

More distance

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

project zip: https://www.dropbox.com/s/mb8pa8pu2yetvwp/ohmeiEgg.zip?dl=0
![image](https://user-images.githubusercontent.com/45465820/161951481-e87f2758-ccfa-46dc-9b72-26d9ba0bcb7d.png)
![image](https://user-images.githubusercontent.com/45465820/161951519-1be0abd2-4e0f-4719-9d6c-d6d72332e5a2.png)

**Comment by tispokes** [comment]
Thanks for the fast reply. I tried X/Y over Z and vis a versa. "Minimum Support X/Y distance" was the last factor I testet before addind the project file. Was 0.4 mm initial.

Chainging "Minimum Support Floor Area" (or all) to 2.0 mm² indeed to something positive, but the diagonal issue still exists. Both Z over X/Y and X/Y over Z tested.
See pictures.
![image](https://user-images.githubusercontent.com/45465820/161977941-438fb02c-f2d6-4120-aad2-82a516874fa9.png)

![image](https://user-images.githubusercontent.com/45465820/161978013-6c722568-fd17-4a25-8c24-a6426e99e2ed.png)

**Comment by GregValiant** [comment]
I don't get that area when I slice it.  I wonder if it's a video display thing.  (My laptop doesn't support OpenGL 4.1 and so I am in compatible mode).
Have you tried slicing, clearing the build plate, and then opening the Gcode file in Cura?  The gcode reader is separate from the slicer and sometimes things will appear differently.

**Comment by tispokes** [comment]
Same on the opened gcode. 
![image](https://user-images.githubusercontent.com/45465820/161980644-8abea9fb-76b8-4eaf-b314-6ac863e9364e.png)

**Comment by tispokes** [comment]
Changed only the initial. Same problem. 
Used now the standard profile "Super Quality" same effect/problem.
Same as Dynamic and Standard.

![image](https://user-images.githubusercontent.com/45465820/161995316-a034ddcf-68c2-419d-8e07-f13bc9b25b04.png)

**Comment by GregValiant** [comment]
Instead of altering the Initial Layer Height I've moved the model down to 1.92 above the build plate and made the other changes I talked about.
[GVohmeiEgg.zip](https://github.com/Ultimaker/Cura/files/8427659/GVohmeiEgg.zip)

**Comment by tispokes** [comment]
I did also set the model also to a height which has 0 remainder to the layer height. All my pictures from the second post on are with 0.84 z.
But will try later thanks

**Comment by tispokes** [comment]
Opened your 3mf, imported as model with new profile for the settings. remains the same. 
![image](https://user-images.githubusercontent.com/45465820/162437725-db418e60-6517-43a3-b528-a4f4c7bafa56.png)

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
