### ISSUE TITLE
"Cura quit unexpectedly" when clicking quit on Mac

### ISSUE THREAD

**Issue by nbaddorf** [Ultimaker/Cura#11780]
### Application Version

4.12.1

### Platform

macOS Monterey 20.0.1

### Printer

Ender 3 Pro

### Reproduction steps

Right click on Cura in the Mac dock, and hit quit. 

### Actual results

The "Cura unexpectedly quit" error pops up.

### Expected results

Cura should quit cleanly
[cura.log](https://github.com/Ultimaker/Cura/files/8443816/cura.log)
<img width="1005" alt="Screen Shot 2022-04-07 at 10 21 57 AM" src="https://user-images.githubusercontent.com/42445164/162222500-0cbe5a35-c846-4ecc-8269-ff9fc4d2163c.png">
.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Cura still works fine and all, it is just a bit anoying that it 'crashes' whenever I hit quit

**Comment by callmefresh** [comment]
I am having a similar issue on **10.15.7 CATALINA** . But I can be in the program for as little as 5 minutes and get booted. and there are times where it isn't even booting up. I have re-installed many times and it seems to get worse and worse. Now i can not even get on for 2 seconds, PLEASE HELP!
