### ISSUE TITLE
Bridge : wrong behaviour

### ISSUE THREAD

**Issue by zifnab0** [Ultimaker/Cura#11788]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Longer LK4 Pro

### Reproduction steps

Enable bridge setting and slice.

### Actual results

See attached image.
The model is symetric and the bridges are short on one side (red in the image) and way too long on the other side (blue in the image)

### Expected results

Bridges are always built as short as possible like on the "red" side (see image)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/50694607/162728946-6e001b1a-f7e7-40eb-b5ec-b1a2f17e8bec.png)

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
