### ISSUE TITLE
When Multiplying an object, nothing happens and the progress bar remains on screen (empty)

### ISSUE THREAD

**Issue by jasoben** [Ultimaker/Cura#11781]
### Application Version

4.11

### Platform

OS X

### Printer

S5

### Reproduction steps

1. Edit > Multiply Objects

### Actual results

The multiply window doesn't do anything and continues to block the view even if you open another project

### Expected results

Objects should multiply

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="1272" alt="Screen Shot 2022-04-08 at 1 12 48 PM" src="https://user-images.githubusercontent.com/7291792/162490474-df0e1664-1775-44a1-b799-5543ed2be126.png">

I'd include the project file but it won't let me upload the 3MF format

**Comment by fieldOfView** [comment]
This has been fixed in later versions of Cura. Time to update!

**Comment by jasoben** [comment]
Gotcha thanks!
