### ISSUE TITLE
feature request: add support for Printrbot Play in 2.3.x

### ISSUE THREAD

**Issue by FlorinAndrei** [Ultimaker/Cura#1178]
What the title says. Version 2 does not seem to support the Printrbot Play. Please add support for it. Thanks!

**Comment by Ghostkeeper** [comment]
Was already added. It will be in version 2.4: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/printrbot_play.def.json

Thanks to @themaninthesuitcase
