### ISSUE TITLE
HELP ME!! CURA KEEPS QUITTING!! *MAC OS 10.15.7 CATALINA*

### ISSUE THREAD

**Issue by callmefresh** [Ultimaker/Cura#11785]
### Application Version

4.13

### Platform

MACOS 10.15.7 CATALINA

### Printer

Creality 3D Ender 3 Pro

### Reproduction steps

1. I have re-installed many times and all that keeps happening is it quits unexpectedly.
2. I have tried many ways to open the program too. right clicks, control button etc. still no luck.
I may get in for 1 minute if i reboot my mac and re-install from fresh but I cant do this every minute. Also did'nt work twice in a row.

### Actual results

Cure still will not open. And if ti does, it is for 2 seconds then I get an error message
![Screenshot 2022-04-10 at 00 44 39](https://user-images.githubusercontent.com/89579132/162595223-a7f61981-04e2-410d-9be3-2288d3c04acf.png)

### Expected results

Cura should open and allow me to use it. at least for 5-10 minutes to get some files converted at least. that i the bare minimum I ask for. But I wish to be able to use it without these bugs.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I wish to be able to install an older version of cura or for there to be an update/patch to stop this issue on MACOS.

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
