### ISSUE TITLE
incorrect speed of the first layer

### ISSUE THREAD

**Issue by dziabi3** [Ultimaker/Cura#11784]
### Application Version

4.13.1

### Platform

Windows10

### Printer

Ender 3

### Reproduction steps

I configured "Initial Layer Print Speed" to 50mm / s and got F3600 in gcod.
Instead of taking into account the value of "Initial Layer Print Speed", Cura takes into account the inactive value of "Initial Layer Speed"

### Actual results

the printer prints at F3600 instead of F3000

### Expected results

I should get the speed of F3600

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_Złożenie1 - C-1 (3).zip](https://github.com/Ultimaker/Cura/files/8457937/CE3_Zlozenie1.-.C-1.3.zip)
[CE3_Złożenie1 - C-1.zip](https://github.com/Ultimaker/Cura/files/8457938/CE3_Zlozenie1.-.C-1.zip)
[Bez tytułu.zip](https://github.com/Ultimaker/Cura/files/8457940/Bez.tytulu.zip)

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
