### ISSUE TITLE
Tree support merged with model

### ISSUE THREAD

**Issue by zifnab0** [Ultimaker/Cura#11799]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Longer LK4 Pro

### Reproduction steps

Use tree support on this model : https://www.thingiverse.com/download:9752565

### Actual results

Tree support merged with model :
![image](https://user-images.githubusercontent.com/50694607/163382755-dc3785d1-f4e7-42ca-909d-cc70ad79fbab.png)

### Expected results

Tree support separated from model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by Asterchades** [comment]
This was already fixed by 4.13.1 back at the end of January. It's the first of only two listed bug fixes that version is for.

Updating to the latest version should be a matter of course before reporting bugs; or at least reading the change logs.

**Comment by zifnab0** [comment]
Thank you for your answer. I apologize for posting this issue.
