### ISSUE TITLE
text alignment

### ISSUE THREAD

**Issue by ririfonfon** [Ultimaker/Cura#11795]
### Application Version

4.13.1

### Platform

windows 10 64

### Printer

ender 3 pro

### Reproduction steps

none

### Actual results

![cura](https://user-images.githubusercontent.com/25557362/163041606-20a5f095-85e6-4d43-81c1-01e8af07f609.png)

### Expected results

none

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
