### ISSUE TITLE
NZXT Cam and Power Toys (Sometimes) Freeze Cura and make it Unusable

### ISSUE THREAD

**Issue by inf1n1tyPa1n** [Ultimaker/Cura#11800]
### Application Version

20220310

### Platform

Windows11

### Printer

CR-10s

### Reproduction steps

it only happens after my pc is ON for at least 3 hours, when it happens i have to restart my pc.
when i restart my pc i can have open both programs and Cura without any problem. 
is happening since at least half a year (also with windows 10) it does not happen every day but recently it happens more often. (video of it happening is in file uploads)

Install Power Toys and/or NZXT Cam.
Wait some Hours
Open Cura

### Actual results

Cura Freezes and is unresponsive when trying to move or slice an imported (any) stl File

### Expected results

Shouldn't Freeze 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8489204/cura.log)

https://user-images.githubusercontent.com/57602604/163392759-ea36c73d-7ae5-450d-9fc6-c0a0a42fb04c.mp4

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
