### ISSUE TITLE
stl文件不能显示cura图标

### ISSUE THREAD

**Issue by CrazyFreshBoy** [Ultimaker/Cura#11808]
### Application Version

4.8.0

### Platform

win10

### Printer

自定义

### Reproduction steps

安装新版本，然后闪退，退回了4.8版本

### Actual results

打印机使用软件切片文件会重启

### Expected results

正常使用

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

无

**Comment by GregValiant** [comment]
Is this still an issue with recent versions (5.8.0 and up)?  Can I close this?
