### ISSUE TITLE
Problem creating letters with inner spaces

### ISSUE THREAD

**Issue by Pebels2626** [Ultimaker/Cura#11814]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Artillery Sidewinder X1

### Reproduction steps

I've created a text with Blender and exported it as STL, I've done it 1000 times so I don't think I made any mistakes in the design.

### Actual results

A hole that the laminate fills is not processed.

### Expected results

The central space of the letter "e" should appear without padding.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

Attached two images about the problem.
![image](https://user-images.githubusercontent.com/103932414/163794399-5f01112c-8742-4f71-9a40-95a8e514c678.png)
![image](https://user-images.githubusercontent.com/103932414/163794423-da55b47a-116c-46f1-afeb-6e446b951ed9.png
[ASX1_Vera.zip](https://github.com/Ultimaker/Cura/files/8505053/ASX1_Vera.zip)
)

**Comment by GregValiant** [comment]
If you would use the "File | Save Project" command in Cura and then zip the 3mf project file and post it here it may give clues to what is happening.

**Comment by Pebels2626** [comment]
i did it. The file is ant the end of the post, it is called "ASX1_Vera.zip"

**Comment by GregValiant** [comment]
The "r" and the center of the "e" are the problems.  I was able to repair the STL in MS 3D Builder.
Prior to repairing the STL It sliced kind of as expected after I used the Mesh Tools to split the model into parts and then play with the Mesh Fixes settings in Cura.
This is the repaired model.  Zooming in I can still see a bit of funkiness between the E and R and between the R and the A.

![image](https://user-images.githubusercontent.com/64202104/163883033-9716e995-9f91-4ef7-9578-c5a1b10c504d.png)

**Comment by Pebels2626** [comment]
can you share the model fixed please?

**Comment by GregValiant** [comment]
You can fix it in several different free softwares.
[ASX1_fixed_Vera.zip](https://github.com/Ultimaker/Cura/files/8597466/ASX1_fixed_Vera.zip)

**Comment by Pebels2626** [comment]
I finally download MS 3D builder and fixed myself, thank you so much anyway!! :3
