### ISSUE TITLE
Filament change with ender 6 does not work

### ISSUE THREAD

**Issue by Magic2226** [Ultimaker/Cura#11815]
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Creality Ender 6

### Reproduction steps

1. Extensions, post processing, modify G Code
2. Added 3 scripts to pause and place nozzle at x20 y20 on each of them.
3. Passed the 1st one and second one paused and moved to x20 y20
4. I replaced filament and it then tried to restart print from beginning.
5. NEXT
6. I tried Filament change scripts. 
7. Added 3 scripts.
8. did not stop at any layer height
9. at each script I set to move Z to 100mm
10. Did not stop once so I had to cancel

### Actual results

With PAUSE, it skipped 1st one and on second script it moved to where I told it but would not have any option to do anything but restart then tore into the 1st part of print.

### Expected results

Expected it to stop at layer 18 and move to y20 x20 so I could change filament. Did not happen.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Have tried 4 times and did not work.

**Comment by GregValiant** [comment]
Slice a calibration cube and pick a layer for a Pause at Height and another for a Filament Change.  Slice and save the gcode.
Put the gcode into a zip folder and post it here.

When Creality moved to the 4.2.x mainboards there was poor integration with the TFT type LCD displays.  Commands that send a message to the LCD (M0, M1, M117, M600, etc.) no longer worked.  That may not be your problem, but it's the most likely cause.  The commands you are talking about work fine on my older Ender 3 Pro with the 1.1.5 mainboard.

**Comment by Magic2226** [comment]
Will do this when I get off work. I did get a red message something about m0 being a bad command.Sent via the Samsung Galaxy Note20 5G, an AT&T 5G smartphone
-------- Original message --------From: GregValiant ***@***.***> Date: 4/19/22  6:57 AM  (GMT-06:00) To: Ultimaker/Cura ***@***.***> Cc: Magic2226 ***@***.***>, Author ***@***.***> Subject: Re: [Ultimaker/Cura] Filament change with ender 6 does not work
  (Issue #11815) 
Slice a calibration cube and pick a layer for a Pause at Height and another for a Filament Change.  Slice and save the gcode.
Put the gcode into a zip folder and post it here.
When Creality moved to the 4.2.x mainboards there was poor integration with the TFT type LCD displays.  Commands that send a message to the LCD (M0, M1, M117, M600, etc.) no longer worked.  That may not be your problem, but it's the most likely cause.  The commands you are talking about work fine on my older Ender 3 Pro with the 1.1.5 mainboard.

**Comment by Magic2226** [comment]
I have picked three.  

Pause at height layer 20Filament change at layer 40Filament change using printer firmware at layer 80

    On Tuesday, April 19, 2022, 06:57:16 AM CDT, GregValiant ***@***.***> wrote:  
 
 


Slice a calibration cube and pick a layer for a Pause at Height and another for a Filament Change. Slice and save the gcode.
Put the gcode into a zip folder and post it here.

When Creality moved to the 4.2.x mainboards there was poor integration with the TFT type LCD displays. Commands that send a message to the LCD (M0, M1, M117, M600, etc.) no longer worked. That may not be your problem, but it's the most likely cause. The commands you are talking about work fine on my older Ender 3 Pro with the 1.1.5 mainboard.

**Comment by GregValiant** [comment]
I'll go ahead and close this.  It is likely that M600 was not enable in your firmware.  I hope you understand.

**Comment by Magic2226** [comment]
I had a problem like this too. does not seem to work running through the pi but from thumb drive mine works.Sent via the Samsung Galaxy S24 Ultra, an AT&T 5G smartphone
-------- Original message --------From: GregValiant ***@***.***> Date: 11/15/24  1:37 PM  (GMT-06:00) To: Ultimaker/Cura ***@***.***> Cc: Magic2226 ***@***.***>, Author ***@***.***> Subject: Re: [Ultimaker/Cura] Filament change with ender 6 does not work
  (Issue #11815) 
I'll go ahead and close this.  It is likely that M600 was not enable in your firmware.  I hope you understand.
