### ISSUE TITLE
Manage Printers / Add Printer ScrollView problem

### ISSUE THREAD

**Issue by cederom** [Ultimaker/Cura#1182]
When adding New Printer in Manage Printers, the "Other" machine configuration  list is truncated as the ScrollView does not seem to work correctly and the window cannot be resized. I had to put my machine into "Custom" to select it, otherwise it was not visible.
<img width="642" alt="screen shot 2016-11-26 at 21 13 21" src="https://cloud.githubusercontent.com/assets/3051832/20644107/14608a6c-b42a-11e6-9837-18263641c246.png">

**Comment by Ghostkeeper** [comment]
Indeed a bug.

You should be able to resize the window, though. At least it is possible on Ubuntu.

**Comment by cederom** [comment]
cannot resize on osx.. :-(

**Comment by fieldOfView** [comment]
This has been fixed a good while back, issue can be closed
