### ISSUE TITLE
Lags, stutters, pauses, freezes, borderline crashing when doing anything

### ISSUE THREAD

**Issue by crystalanims** [Ultimaker/Cura#11820]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Doing literally anything
- Starting the software
- Interacting with the GUI
- loading a small model
- loading a larger model

A fresh reinstall of the software, with and without the plugins only cures it for a while

### Actual results

Being able to use the software without hiccups

### Expected results

As stated

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8513670/cura.log)
i want to send the project file but it says that i cant upload it here

**Comment by fieldOfView** [comment]
Could you try disabling the SidebarGUIPlugin?

There's an issue with that plugin which I have not yet been able to reproduce: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/29. I hope the work I am doing to update the plugin for compatibility with Qt6 and Cura 5 will fix the issue.
