### ISSUE TITLE
Error Segmentación

### ISSUE THREAD

**Issue by Blankita1999** [Ultimaker/Cura#11851]
### Application Version

5.0.0 beta

### Platform

win 10

### Printer

Geeetech A10

### Reproduction steps

Metí un STL de una luna, y al querer segmentarlame da error, no porque tenga puesto nada mal, simplemente me pone "Se produjo un error, haga click aqui para informar de este error" o algo así.
Luego también está dando problemas con las letras de las descripciones, que se juntan unas con otras.
Y a la hora de meter un archivo STL 90MB tarda muchisimo, en la versión de 4.13.0 (si no me equivoco de version) nada de esto pasa con ese mismo stl.
Envío esto para ayudaros a corregir problemas.
Un saludo.
Gracias

### Actual results

![image](https://user-images.githubusercontent.com/104166899/164538315-3215f9c1-b85a-4f79-b158-c98460978fb0.png)

### Expected results

nada avanza

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nome deja poneros archivos stl

**Comment by jellespijker** [comment]
Please upload log file and project 3mf. Otherwise it is impossible for us to analyze the issue.

**Comment by fvrmr** [comment]
You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
Please share your files in a .zip here on GitHub.
