### ISSUE TITLE
After triple clicking the number under "move" to highlight all numbers, typing a number doesn't replace the current number, you have to highlight the numbers manually or backspace in order to replace them.

### ISSUE THREAD

**Issue by CadetPrewitt** [Ultimaker/Cura#11854]
### Application Version

5 Beta

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Title

### Actual results

Title

### Expected results

Title

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by Vandresc** [comment]
@CadetPrewitt , did you try using Tab? The entire value should be highlighted then. 
Will bring this up with the rest of the team, thank you for your feedback.

**Comment by fvrmr** [comment]
We have discussed this with the team and decided to defer this issue, since it is not a high priority for us to fix. I hope you understand.
