### ISSUE TITLE
[Cura 5.0 beta] Freeze when switching profile with active changes

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#11869]
### Application Version

[Cura 5.0 beta]

### Platform

win10

### Printer

custom fff

### Reproduction steps

Cura 5 imported all my profiles as expected and included the current changes to the active profile.
When I click another profile, the question to keep or discard changes opens blank and Cura immediately freezes.

However, if I choose discard changes BEFORE selecting a different profile there is no issue.

### Actual results

Cura freezes and needs to be restarted.

### Expected results

no freeze

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![freeze](https://user-images.githubusercontent.com/32172100/164648734-88d5efd6-36d2-4cc2-872e-426a8914ee62.jpg)
[cura.log (2).zip](https://github.com/Ultimaker/Cura/files/8538622/cura.log.2.zip)

**Comment by fvrmr** [comment]
Hi @printingotb thank you for reporting.
Could you try to disable the USB printing plugin and see if that helps?

**Comment by printingotb** [comment]
I have don't have that plugin.

**Comment by Zazou49** [comment]
I have the same issue. I have dual monitor, can it be the issue ?

**Comment by printingotb** [comment]
> I have the same issue. I have dual monitor, can it be the issue ?
It was for me:
https://github.com/Ultimaker/Cura/issues/11929

**Comment by Zazou49** [comment]
I confirm, if I disable the second screen, everything works
