### ISSUE TITLE
Unmet dependencies when trying to remove for update

### ISSUE THREAD

**Issue by Jax3DTrains** [Ultimaker/Cura#11887]
### Application Version

4.13

### Platform

Ubuntu

### Printer

Snapmaker A350T

### Reproduction steps

I download the 5.0 beta to try the new version. So I went to remove the version I have been using, and Linux would not remove the software because of "unmet dependencies."

### Actual results

I was not able to update to newer version of Cura.

### Expected results

I was hoping to remove the version I have been using to try the features on the newest version 5.0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I hope to have an opportunity to try out the new software.

**Comment by fvrmr** [comment]
Hi @Jax3DTrains thank you for your report.
You don't have to delete the older version of Cura to update Cura. You can have multiple versions of Cura at the same time. 
Let me know if it works for you!
