### ISSUE TITLE
[5.0 beta] Camera Button does not have a icon

### ISSUE THREAD

**Issue by RDols** [Ultimaker/Cura#11884]
### Application Version

5.00 beta+1

### Platform

Windows 11

### Printer

Ultimaker 3

### Reproduction steps

Go to monitor tab. It looks like the camera button is not present, but actually it is, just no icon. Clicking on it also gives the expected camera window.

![image](https://user-images.githubusercontent.com/57181702/164714472-4139619b-6a3f-440e-ab73-711ba9c049f2.png)

When mouse hoovering:
![image](https://user-images.githubusercontent.com/57181702/164714483-65f72624-f079-4e83-bc7c-44c3f02f9aef.png)

### Actual results

Button is invisible

### Expected results

I see the camera button

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Tiny visualisation bug: The camera button in the Monitor tab doesn't have an visible icon, so it appears the camera button isn't there.

**Comment by nallath** [comment]
Thanks for taking the time to test the beta!

It's on our backlog. Developers see CURA-9117

**Comment by fieldOfView** [comment]
Fixed in https://github.com/Ultimaker/Cura/pull/11893

**Comment by RDols** [comment]
Although i can't test the fix and CI build failed, i will close this issue. Will reopen if the it's not fixed in the next beta.....
