### ISSUE TITLE
No GUI in Zorin OS Linux

### ISSUE THREAD

**Issue by jaymcd** [Ultimaker/Cura#11886]
### Application Version

5.0 Beta 1

### Platform

Linux

### Printer

FLSUN QQS

### Reproduction steps

Never opens GUI

### Actual results

No GUI

### Expected results

Visible GUI

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No GUI available in Zorin OS Linux (Current Version)

**Comment by fvrmr** [comment]
Hi @jaymcd thank you for your report.
Could you share your log file? You can find your log file here: `$HOME/.local/share/cura/<Cura version>/cura.log`

**Comment by jaymcd** [comment]
here you go;

**Comment by fieldOfView** [comment]
Unfortunately, github strips out attachments from email replies. Please use the github web interface to attach your logs (or post a link instead of an attachment).

**Comment by jaymcd** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/8564177/cura.log)
Here is my log from Zorin OS

**Comment by nallath** [comment]
Sorry! The bot was broken for a bit and it's having some hickups starting up again.

**Comment by MariMakes** [comment]
Quick update from our side 👋

We are cleaning up our open issues, so we can focus on the most requested and needed features and bug fixes from our community and from UltiMaker, I stumbled upon your issue about your Linux GUI not working. 

Could you try if it's resolved in the 5.5 Beta release 🎉 , you can download the Cura version here: [https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)

Thank you 🙏

**Comment by jaymcd** [comment]
It has been working in Linu xnow for a bit - all good. Thanks 

Jay
