### ISSUE TITLE
Use Adaptive Layers

### ISSUE THREAD

**Issue by chippymiller** [Ultimaker/Cura#11891]
### Application Version

5.0

### Platform

macOS Monterey

### Printer

Custom

### Reproduction steps

Clicked "Use Adaptive Layers" and it said that it had a issue slicing and asked me to report this bug.

### Actual results

I am now reporting the bug

### Expected results

be able to use the Adaptive Layers function.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://www.thingiverse.com/thing:3008571/makes
It wouldn't let me load the STL so here is the link to it.

**Comment by fvrmr** [comment]
Hi @chippymiller thank you for your report.
Could you share your project file (file - save project) and share it here as a .zip. I can't reproduce your issue with only an STL.
