### ISSUE TITLE
"Pick a screen color" missing

### ISSUE THREAD

**Issue by guate6** [Ultimaker/Cura#11899]
### Application Version

5.0.0

### Platform

Windows 10/11

### Printer

Ultimaker S5

### Reproduction steps

Opened the material settings in Cura to add a filament and color. 

### Actual results

It has pre-set colors and hex only, no option to pick screen color

### Expected results

That the "pick screen color" option would be there, but it's missing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Please re-add this as it's a useful feature. Thanks.

**Comment by fvrmr** [comment]
Hi @guate6 thank you for your report.
I know that this menu is updated because of the Qt6 upgrade, I will check with the team if this is expected. Keep you posted.

**Comment by guate6** [comment]
Hello. Yes, this problem has not been fixed in any of the version 5
releases. It's a picture that was available in the older versions.

**Comment by MariMakes** [comment]
Hey @guate6,

👋 I'm a fresh set of eyes reporting for duty 💪 
I don't make new materials very often 🤔 

Can you help me understand why this feature is important for you?
What are things you cannot do now that the feature is missing? 
What is something that the old feature used to do, that you cannot do with the hex code field?

**Comment by guate6** [comment]
Precision of color for client previews is one thing (yes, my monitor is
color calibrated). Rather than having to manually input the hex code for
color.
When any software is released, once you get accustomed to a feature, when
it's missing from any newer versions, it's disappointing that the whole
thing seems to have gone a step backwards.
This became increasingly necessary, because the backup system is broken,
and sometimes I have to reset my profiles. So this taught me to have a
backup xls file with profile information, including colors. I was able to
go in and click the screen color on each cell to get each color done
correctly, but now that the "pick screen color" option is missing, I have
many extra steps to program a color for each material I add or restore to
Cura.

Raúl E. Fernández
Office (call/text): 352-573-6114
Mobile (call/text): 352-234-6161

**Comment by guate6** [comment]
I understand, and appreciate the positive attitude on this.
Personally I prefer "we will get to it eventually," rather than "we don't
care about this" that seemed to be the subtext of responses I received last
year. Thank you :)

Raúl E. Fernández
Office (call/text): 352-573-6114
Mobile (call/text): 352-234-6161

**Comment by MariMakes** [comment]
Hey @guate6,

It seems like the feature you were looking for was not available in the library we are using at the time you reported this. But since then it has been updated and we can now implement https://doc.qt.io/qt-6.2/qcolordialog.html#details. 

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10687

Thanks for the report! 👍

**Comment by guate6** [comment]
Great, thanks. I suspect in an upcoming update we might see this again?

Raúl E. Fernández
Office (call/text): 352-573-6114
Mobile (call/text): 352-234-6161

**Comment by MariMakes** [comment]
Hey @guate6,

The upcoming release is super duper soon, so I expect it not to show up in that release.
But hopefully a later one, I cannot make any promises 😅

**Comment by MariMakes** [comment]
👋 Quick update on our side. 

This is resolved in the 5.5 Beta release 🎉 , you can download the Cura version with the fix here: [https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)
I'll close this issue since it's resolved. 

Thanks again, and please let us know if you run into any other issues 💪
