### ISSUE TITLE
Wish I could save my builds in Cura

### ISSUE THREAD

**Issue by partsoven** [Ultimaker/Cura#1191]
Feature request: Saving a build would be helpful (not in G-code) but my actual Cura layout etc... that way if you want to pull up a past build but tweak a setting or material you can do so.

**Comment by nickthetait** [comment]
You are not the first to request a feature like this :smile: 
Take a look at https://github.com/Ultimaker/Cura/issues/1086
Elaborate on any data/ideas that you do not see mentioned in that ticket

**Comment by fieldOfView** [comment]
You're in luck. This is exactly what is coming in 2.4.

**Comment by partsoven** [comment]
Awesome!
