### ISSUE TITLE
 Fusion 360 opens 4.13 but will not open 5.0 beta

### ISSUE THREAD

**Issue by TedDavis** [Ultimaker/Cura#11923]
### Application Version

5.0.0-beta+1

### Platform

Windows 11

### Printer

Creality Ender

### Reproduction steps

1. I set the preference for Fusion 360 to open Ultimaker-Cura.exe(5.0) instead of Cura.exe(4.13). 
2. I clicked the 3D Print command in the File dropdown and selected a Body 3MF and Cura.
3. I clicked OK.

### Actual results

No matter what I did, Fusion insisted on opening Cura 4.13.

### Expected results

Fusion should send my .3mf to Ultimaker-Cura (5.0).

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I understand that this maybe a problem with Fusion and not with Cura... but I'd be grateful for advice.
Thanks.

**Comment by fvrmr** [comment]
Hi @TedDavis thank you for reaching out.
I would say this is an issue with Fusion, so please reach out to them.
I will close this issue but feel free to reach out again!
