### ISSUE TITLE
Cura 5.0 Deutsch

### ISSUE THREAD

**Issue by daddyschlumpf** [Ultimaker/Cura#11939]
### Application Version

5.0  beta

### Platform

Windows 10, 21H1, ntel(R) Core(TM) i3-3220 CPU @ 3.30GHz   3.30 GHz

### Printer

Creality Ender-3 pro

### Reproduction steps

Bei den Druckeinstellungen ist es nicht mehr möglich (wie in Version 4.1.) die Hinweise (alle) der funktionserklärenden Popups komplett zu lesen. Die Texte müssten gescrollt werden, was aber nicht möglich ist, weil beim Verlassen des entsprechenden Items in den Druckeinstellungen nach links, das Popup verschwindet.
 
Schritte:  
- Öffnen der Druckeinstellungen.
[Beta 5.0 von Curo - popup Problem.pdf](https://github.com/Ultimaker/Cura/files/8549700/Beta.5.0.von.Curo.-.popup.Problem.pdf)
[Beta 5.0 von Curo - popup Problem.pdf](https://github.com/Ultimaker/Cura/files/8549701/Beta.5.0.von.Curo.-.popup.Problem.pdf)

- Mouseover z.B. Fülldichte (oder jedes anderes Item mit längerem Erklärungstext) 
- Popup öffnet sich wird aber durch zu kleine Fenstergröße nicht vollständig angezeigt und hat einen Scrollbalken
- Maus zum Popup um zu scrollen
- Popup verschwindet, wenn die Fläche der Druckeinstellung verlassen wird

### Actual results

Popup verschwindet und kann nicht vollständig gelesen werden

### Expected results

Popup bleibt vorhanden und kann gescrollt werden, mit einem X oben rechts zum Ausschalten-
oder die Popup Fenster sind so groß (wie in 4.1.) dass der gesamte Text gelesen werden  kann

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Sorry for not writing in English-I am not sure, if I could describe the fault correctly.

**Comment by fvrmr** [comment]
Hi @daddyschlumpf thank you for your report.
Looking at your pdf file, this is a duplicate of https://github.com/Ultimaker/Cura/issues/11834
I will close this issue, since it is a duplicate.
