### ISSUE TITLE
Plugins missing

### ISSUE THREAD

**Issue by ManCavePrinting** [Ultimaker/Cura#11932]
### Application Version

5.0 Beta

### Platform

Windows 10

### Printer

Ender 5

### Reproduction steps

Plugins not available

Started Cura
Plugins not found
Marketplace does not show Plugins

### Actual results

can´t connect to octoprint
can´t use other plugins

### Expected results

Find Plugins in Marketplace

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no more inforamtion
![image](https://user-images.githubusercontent.com/104298769/164968721-bfc683c5-bfa8-40e3-9e52-11c4ba24bc24.png)
![image](https://user-images.githubusercontent.com/104298769/164968734-a4ff8f37-07c5-4301-a40d-b9c7d7ca296f.png)

**Comment by fieldOfView** [comment]
See https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50 for info and links to prereleases of some of the plugins you are looking for.
