### ISSUE TITLE
Cura 5.0+1 Beta Randomly crashes in the middle of working on projects

### ISSUE THREAD

**Issue by AngiHa6845** [Ultimaker/Cura#11948]
### Application Version

5.0.0+1

### Platform

windows 10

### Printer

Creality Ender 3 Max

### Reproduction steps

 Several times cura beta just randomly crashes while I am in the middle of working on items. When it crashes it closes out. I have to reopen and then start all over again. It does not do this all of the time. Only every  other time I am working on a new part..

### Actual results

dont know how to as it happens randomly at different times. restarting the app It will usually let me then start all over and slice/save. This crash happens about every other time while using it. 

### Expected results

beta is crashing back to desktop

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

will try to see if i can capture anything when it does it. As it gives no error message other then crashing back to desktop/

**Comment by nallath** [comment]
Could you also share your log files? They might contain something that can tell us more about what is going on.
