### ISSUE TITLE
5.0.0-beta+1 Wall Printing Issue

### ISSUE THREAD

**Issue by fefifofums** [Ultimaker/Cura#11947]
### Application Version

Ultimaker-Cura-5.0.0-beta+1-win64

### Platform

Windows 10

### Printer

Ender-3  Pro v2

### Reproduction steps

**Using 5.0.0-beta+1 Ceality Ender-3 Pro ~~all~~ most default settings  except 70mm print speed**
1. Slice [object](https://cdn.thingiverse.com/assets/76/ec/16/21/8a/Adaptapod_Neck_v1.stl)
2. Print
![5 0 0-beta+1](https://user-images.githubusercontent.com/11931705/164997692-c7e09d98-67fd-470d-83c8-edb385d9a6a8.PNG)
3. See result

Note - Same result multiple times with different filament temperatures. I have not tried slowing down the print speed yet but I will update this section with the results.

**Using 4.13.0 Ceality Ender-3 Pro ~~all~~ most default settings  except 70mm print speed**
1. Slice [object](https://cdn.thingiverse.com/assets/76/ec/16/21/8a/Adaptapod_Neck_v1.stl)
2. Print
![4 12 0](https://user-images.githubusercontent.com/11931705/164997697-454f289a-eee9-4884-b5ee-a04d3bce48f8.PNG)
3. See result

### Actual results

Results from printing on 5.0.0-beta+1 
![5 0 0-beta+1Result](https://user-images.githubusercontent.com/11931705/164997703-e44c6345-7568-4824-9cbd-195191d4281c.jpg)

### Expected results

Result of print on 4.13.0
![4 12 0Result](https://user-images.githubusercontent.com/11931705/164997717-4caac409-62aa-480c-89e0-ebf85e31363f.jpg)

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

I'm happy to include any additional information such as the project file.  However, I will not that the previews look identical (i.e. totally normal) between both versions.   Please let me know if I can provide any other useful information.
[badProjectAndGcode.zip](https://github.com/Ultimaker/Cura/files/8551308/badProjectAndGcode.zip)
[goodProjectAndGcode-4.13.0.zip](https://github.com/Ultimaker/Cura/files/8551336/goodProjectAndGcode-4.13.0.zip)

**Comment by GregValiant** [comment]
Post a project file and post that "bad" gcode file also.  I've got the same printer and we'll see if I get the same result.
Did you look at the preview with the Travel Moves turned on?  Settings like "Max comb distance with no retract", "Retraction Minimum Travel" and the "Combing" mode are the same in both Cura versions?

**Comment by fefifofums** [comment]
I added the bad project file and gcode above.  While three settings you asked about match in both 5.0.0 and 4.13.0, it appears I did change the default values.  

**5.0.0 Preview** 
![5 0 0-beta+1Preview](https://user-images.githubusercontent.com/11931705/165013937-8a3bddd2-6c74-4683-b550-c01b0465d57f.PNG)

**4.13.0 Preview**
![4 13 0Preview](https://user-images.githubusercontent.com/11931705/165014000-9171853b-3865-4f82-b2be-31c68a935869.PNG)

**Comment by GregValiant** [comment]
Changing the combing mode to "All" seems to be the ticket.  Changing "Max comb distance with no retract" to 3.0 may help.  It's a small part.
Telling it to "Avoid Printed Parts" can have odd effects when there is only one part on the build plate.  It can make for travel moves outside the part and that can cause stringing.
I'm not a fan of "Retract before outer wall" as it can leave a blob when it primes at the start of the outer wall extrusion.  That can make the Z seam more noticeable.

**Comment by fefifofums** [comment]
Interesting, I'll try change that and report back with my results.  

I'm still curious why I don't see this issue with the same settings on 4.13.0 though.  Any thought's on that?

**Comment by fefifofums** [comment]
I figured out what the problem is.  In Cura 4.13.0, there is a setting in Walls called "Outer Before Inner Walls", in Cura 5.0.0-beta+1 this got changed to a setting called "Wall Ordering".  The problem is that in Cura 5.0.0-beta+1 the default value changed from "Inside to Outside" to "Outside to Inside" so when it was printing that first outer wall of the overhand, it had nothing to bond to, resulting in the drooping.  

### Solution - Set "Wall Ordining" to "Inside to Outside".

**Comment by GregValiant** [comment]
Well that makes sense.  I learned something as well.

**Comment by fefifofums** [comment]
All good! It was helpful to have someone to talk to about it.  Thank you!
