### ISSUE TITLE
Unable to open files like in Cura 4.0

### ISSUE THREAD

**Issue by fhbrev** [Ultimaker/Cura#11945]
### Is your feature request related to a problem?

Familiar with Cura 4.x, I just installed Cura 5.0 without uninstalling 4.x, expecting every parameters and plugins would be included into 5.x during its installation. Unfortunately, this was not the case.
Using Freecad application,  Cura 5.0 was not recognizing FCStd files meaning the plugin I have in Cura 4.x was not installed in Cura 5.x.
Unfortunately, I was not able to find it .

### Describe the solution you'd like

Ensure user parameters implemented in a current application are transferred when installing a new release, whatever is the release level. In case a parameter needs adjustment, an information to the user. if a plugin was in place, it should be installed too. If a plugin is no more necessary or no more valid, alternatives should be offered to the user .

### Describe alternatives you've considered

Not being able to deal with FCStd files, I am continuing to use Cura 4.x

### Affected users and/or printers

No waste of time for reinstalling capabilities of previous release

**Comment by fieldOfView** [comment]
Opening freecad files directly in Cura relies on a plugin. In order to be compatible with Cura 5, all plugins need to be updated by their maintainers and re-approved for inclusion in the Marketplace. This will take some time.
