### ISSUE TITLE
Networked drive and multiply object

### ISSUE THREAD

**Issue by Chad541121** [Ultimaker/Cura#11965]
### Application Version

5.0

### Platform

windows 10

### Printer

ender 5 plus

### Reproduction steps

Right click on object and select multiply.  Leave quantity at 1 and select ok.  Nothing happens.  You have to physically retype the 1 as a quantitiy before clicking ok.
Also when opening a file, networked drives that have been assigned a drive letter are not available, you have to use the UNC path to access files on a networked drive.

### Actual results

object is not multiplied.
mapped network drive cannot be accessed.

### Expected results

should not have to change the 1 to a 1 to make this work
mapped drive should be able to be clicked on and viewed.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Happens with any file

**Comment by fieldOfView** [comment]
Please report only one problem per issue. If one of the problems gets solved, it is going to be unclear what's the status of the issue.

The multiply issue has been reported before and a fix is ready:
https://github.com/Ultimaker/Cura/pull/11906

**Comment by fvrmr** [comment]
Hi @Chad541121 thank you for your report.
Could you share your log file? You can find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
