### ISSUE TITLE
problème d'etirage

### ISSUE THREAD

**Issue by ena91** [Ultimaker/Cura#11967]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

Wanhao D12 230 dual

### Reproduction steps

En activant l'étirage uniquement sur la dernière couche de la pièce

### Actual results

l'étirage se fait sur certaine couche aléatoirement ce qui ruine mes impressions

### Expected results

l'étirage devrait se faire uniquement sur la dernière couche de la pièce.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

......

**Comment by GregValiant** [comment]
I think something is lost going to English.  What setting is "Stretching"?
