### ISSUE TITLE
fermeture de la fenêtre Ultimaker Cura 5.0 beta

### ISSUE THREAD

**Issue by jessy2027** [Ultimaker/Cura#11976]
### Application Version

5.0

### Platform

Windows 11

### Printer

ANYCUBIC VYPER

### Reproduction steps

Quand je lance une impression 3D via USB (en filaire ), tout se passe bien mais arrivé environ à la 10ème couche la fenêtre de Ultimaker Cura 5.0 beta se ferme et l'impression 3D s'arrête.

### Actual results

Ultimaker Cura 5.0 beta se ferme et l'impression 3D s'arrête.

### Expected results

l'impression devrait continuer jusqu'à son terme

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8561670/cura.log)

**Comment by fieldOfView** [comment]
Duplicate of #11896
