### ISSUE TITLE
v5b1 open 3mf file leads to inaccessible window

### ISSUE THREAD

**Issue by tispokes** [Ultimaker/Cura#11973]
### Application Version

5

### Platform

W11

### Printer

-

### Reproduction steps

Ctrl+O, open a 3mf File. Now I can't see the primary/secondary button. 

### Actual results

![image](https://user-images.githubusercontent.com/45465820/165238305-89bf6142-d78a-4d65-9867-88765550833b.png)

After some switching between secondary and primary screen, I now see all options but can't click it.
This happens **only** when swithcing windows with shortcut Win+Shift+(Left | Right) as I use this very often.

### Expected results

![image](https://user-images.githubusercontent.com/45465820/165238652-966ee901-5161-4a95-b111-2051fc5832da.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

not needed

**Comment by fvrmr** [comment]
Hi @tispokes thank you for your report.
This is a known issue, we have a ticket on our backlog for this. Devs see CURA-9165
If you move the menu it will show the buttons.

**Comment by tispokes** [comment]
> Hi @tispokes thank you for your report. This is a known issue, we have a ticket on our backlog for this. Devs see CURA-9165 If you move the menu it will show the buttons.

Yes i see the print-menu but cannot resize the settings menu. But as is it known bug, thanks for the information.
