### ISSUE TITLE
Can't view drop down info

### ISSUE THREAD

**Issue by Lazy13b** [Ultimaker/Cura#11987]
### Application Version

5.0

### Platform

Win 10

### Printer

Ender 3v2

### Reproduction steps

hovered mouse over a setting. 

### Actual results

Drop Down info appears. but Can't scroll down to see all the info

### Expected results

scroll through the info.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Absolutely LOVEING version 5.0!!!! THANK YOU!!

**Comment by fvrmr** [comment]
Hi @Lazy13b thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11834, so I will close this issue!
