### ISSUE TITLE
Dual Extruder crash

### ISSUE THREAD

**Issue by soleyar** [Ultimaker/Cura#11986]
### Application Version

4.13.1

### Platform

Windows 11

### Printer

Weed X40

### Reproduction steps

When printing in duplication on the weedo x40 with the version 4.13.1 the left extruder goes all the way to the right extruder and continues to try and push it and won't actually stop unless you quit the print job.

Tried slicing the program again with just the recommended setting. Not changing anything other than the filament temp. The left extruder still crashes into the right extruder.

I have a friend in another state having the exact same issue. 

### Actual results

same issue, nothing changed

### Expected results

hoping the left extruder would not crash into the right extruder

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by nallath** [comment]
Cura doesn't support duplication mode. There are cura forks that do, but they are quite behind what we ship.
