### ISSUE TITLE
Switching machines adds extra Extruders to Settings menu, then crashes when the mouse-hovers over them.

### ISSUE THREAD

**Issue by pufferfish-tech** [Ultimaker/Cura#11988]
### Application Version

5.0 beta

### Platform

Windows 10

### Printer

Any (Ender, FLSUN, Artillery)

### Reproduction steps

1. Change printer using the combo box below the menu (not the menu). 
2. You can do this as many times as you want (each time will add another instance in the menu in step 4)
3. click Settings
4. Observe the extra menu items labeled "Extruder 1"
5. If you press escape or the menu top level here, cura wont crash, but hovering any of these extruder menu items causes instant disappear of cura UI. 

### Actual results

Cura disappears. 

### Expected results

Cura should not disappear. More specifically those menu items should not be present. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

There does not appear to be an entry at all in the log file, however I believe this is easy enough to reproduce on any setup with more than one printer.
Image should show just one "Extruder 1"
![bug1](https://user-images.githubusercontent.com/58510167/165381137-31359664-5d3e-480e-8370-a6b442017321.PNG)
 
Additional trivia, if selecting a dual extrusion printer, you get a bonus "extruder 2". So it looks like it's just adding the new ones, but keeping the old ones.
![bug2](https://user-images.githubusercontent.com/58510167/165381637-4adc8b6e-9eca-42fd-a333-2747e27d0848.PNG)

**Comment by pufferfish-tech** [comment]
I should add that the workaround is to use the button pictured and avoid the menu entirely, then it does not appear to crash.
![bug3](https://user-images.githubusercontent.com/58510167/165382171-4cd754c8-3fc9-4f50-b07a-da9530c67101.PNG)

**Comment by jellespijker** [comment]
Thank you for reporting this.
Keep up the nice videos we really enjoy them.

**Comment by Sonicboom247** [comment]
Happening to me as well, seems that continuing to switch between machines keeps adding extruders 
![extruder](https://user-images.githubusercontent.com/84334417/165535452-245b9f6b-0e81-4f65-ad7f-93a0cfd3b133.jpg)

**Comment by Hun73rdk** [comment]
Can confirm happens to me also had 8 extruders last time

**Comment by fvrmr** [comment]
Hi @pufferfish-tech thank you for your report.
I can reproduce your issue, will bring it up with the team. Keep you posted!

**Comment by MariskaMaas** [comment]
Thanks for reporting this! 
For internal reference, this is CURA-9222

**Comment by nallath** [comment]
Fixed for the final 5.0 release. Thanks for reporting it!
