### ISSUE TITLE
Does not allow screen print

### ISSUE THREAD

**Issue by Emersongte** [Ultimaker/Cura#11982]
### Application Version

5.0 Beta

### Platform

Windows 10

### Printer

GT max Pro A3

### Reproduction steps

keyboard key fn+PrintScm
does not work

### Actual results

keyboard key fn+PrintScm does not work, can't print screen

### Expected results

Does not allow screen print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Does not allow screen print

**Comment by fieldOfView** [comment]
I can't reproduce this; I can use the Print Screen functionality and then paste the image into applications just fine on Windows 10.

**Comment by nallath** [comment]
Is it even possible for an application to prevent printscreen?

**Comment by fvrmr** [comment]
Hi @Emersongte thank you for your report.
I can also not reproduce this on Windows 10. Can you use the print screen function in other applications?
