### ISSUE TITLE
Starting point for next layer is same as the last point of the next layer

### ISSUE THREAD

**Issue by Driver2007** [Ultimaker/Cura#11999]
### Is your feature request related to a problem?

Hello,

Could you please consider adding a feature allowing to set the starting point for the following layer to be as close as possible to the last point of the previous one? In some certain cases, it could considerably reduce traveling time (printing time) and the quality of the print.

Thank you

Best regards,
Sergey

### Describe the solution you'd like

it could considerably reduce traveling time (printing time) and the quality of the print.

### Describe alternatives you've considered

To my knowledge there is no this feature in Cura. I was googling and found that previous versions of Cura allowed to activate it. But late it was removed because of too long compilation process. Which  do not sound convincing because users could decide for themselves if they want to wait for compilation or not.

### Affected users and/or printers

It will affect all users

**Comment by nallath** [comment]
It was never removed. You can use "shortest" in z-seam alignment
