### ISSUE TITLE
Cura5 Beta 300% Slice

### ISSUE THREAD

**Issue by Plattmach** [Ultimaker/Cura#11997]
### Application Version

5.0.0-Beta+1

### Platform

W11

### Printer

AnyCubic

### Reproduction steps

Scale up to 300% in Cura 4.13.0  it works

### Actual results

Slicing failed with an unexpected Error

### Expected results

no Error

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

[cura5.zip](https://github.com/Ultimaker/Cura/files/8573261/cura5.zip)

**Comment by fvrmr** [comment]
Hi @Plattmach thank you for your report.
Could you also share your project file (file - save project) and share it here in a .zip?

**Comment by GregValiant** [comment]
You will need to put the project file in a zip folder and post the zip folder.

**Comment by Plattmach** [comment]
Sorry, as .zip of course, but that's the problem.
See Screenshot.
![error](https://user-images.githubusercontent.com/104514192/165909930-c542b091-3a37-4788-8d10-b463d42c8dca.jpg)

Thanks

**Comment by GregValiant** [comment]
The "log" file posted OK.  I'm a user and not real good at reading log files but I was able to download and open it.

**Comment by Plattmach** [comment]
@GregValiant : No problem :-)
But now i know, what´s wrong.
The File is to big (84.747KB), therefore i´m not able to upload it. 
I tried a smaller Project and it works.
