### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by glennwad** [Ultimaker/Cura#11995]
### Application Version

5

### Platform

windows 8.1

### Printer

ender3v2

### Reproduction steps

after i select stl it puts it on the build plate and as soon as i click on part it crashes if i slice it with out doing anything to the stl its fine

### Actual results

program shuts down

### Expected results

i should be able to resize or move stl

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by glennwad** [comment]
i couldnt locate the log
ill try again

**Comment by glennwad** [comment]
is this the log you need

**Comment by fieldOfView** [comment]
Unfortunately, github strips out attachments from email replies. Can you please use the github web interface to add the logs?

**Comment by glennwad** [comment]
no i just uninstalled 5 ill wait till its final is out
