### ISSUE TITLE
Cura 5 Object move dialog is unusable when there are many extruders defined.

### ISSUE THREAD

**Issue by Anathema-Device** [Ultimaker/Cura#11990]
### Application Version

5.0.0.beta-1

### Platform

Windows 10

### Printer

Custom Geeetech A10M

### Reproduction steps

Create a printer definition with 8 extruders
Open any .stl file
Select the object on the platter
Select the move icon (top left)
Try and enter coordinates < the entry fields for the coordinates are behind the top icon bar that shows the folder, printer name and extruders
This issue also exists in Cura 4.13.1 and earlier.

![Cura5-move_dlg](https://user-images.githubusercontent.com/36930217/165403842-42687f84-81c8-4b65-95da-bbcc8669b6cb.PNG)

### Actual results

It is not possible to accurately adjust the position of objects on the build plate when this happens.

### Expected results

The dialog should be positioned lower so that the values can be edited.  

One simple solution would be to put the column of extruders to the left of the column of icons with the move, rotate, etc icons when they get too long?  This would also solve the issue of not being able to get to all the extruder icons when the window is too small.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional info, I believe the steps above will show the problem clearly - also see the picture attached

**Comment by fvrmr** [comment]
Hi @Anathema-Device thank you for your report.
I will bring this up with the team, keep you posted.

**Comment by fvrmr** [comment]
We have discussed it with the team and decided to defer this issue, this is not an issue for Ultimaker printers and that's why it will not get a high priority for us to fix. 
Anyone is welcome to fix this and create a pull request for this.

**Comment by fieldOfView** [comment]
A quick workaround is installing the prerelease of the SidebarGUI plugin, which does not have this issue.
https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/

I will see if I can create a fix for the standard GUI as well.

**Comment by fieldOfView** [comment]
See my fix in #12054
