### ISSUE TITLE
Unexpected travels in Vase mode causing unnecessary seam

### ISSUE THREAD

**Issue by Ferrograph** [Ultimaker/Cura#12006]
### Application Version

5.0.0-beta

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Slice the attached project with included profiles. Look at the travels on the bottom layer
[cura.log](https://github.com/Ultimaker/Cura/files/8581760/cura.log)
.

### Actual results

Slicing produces weird unnecessary travels as shown in the screen shot resulting in ugly seams. 

![image](https://user-images.githubusercontent.com/6049510/165727955-b9533653-e579-460d-8945-5dbc613d1316.png)
![image](https://user-images.githubusercontent.com/6049510/165728013-e7b0a63e-0ece-4665-b0de-693185fd3f99.png)

### Expected results

Slicing in 4.13.1 does not have unnecessary travels and expected single seam.
[Cura Belt Project.zip](https://github.com/Ultimaker/Cura/files/8581630/Cura.Belt.Project.zip)
.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Im trying to print belts with minimal seam and uniform cross section.

**Comment by fvrmr** [comment]
Hi @Ferrograph thank you for your report.
I will discuss this with the team. Keep you posted.

**Comment by fvrmr** [comment]
I have discussed it with the team and we decided to defer this issue for now. It will not get a high priority to fix for us now. I hope you understand.

**Comment by Ferrograph** [comment]
Wondering if this will ever be fixed? Because of this issue I cant use Cura for my prints
