### ISSUE TITLE
Help/About

### ISSUE THREAD

**Issue by TJF0700** [Ultimaker/Cura#12008]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

None Selected yet

### Reproduction steps

Installed Ultimaker-Cura-5.0.0-beta+1-win64.exe removed the plugins it stated I needed to, then restarted.   Noticed when it started it had a notification that the new 5.0 beta was out and I should download it. (Although it *is* the beta).

Went to help about - nothing shows up, but Cura no longer responds... as if the modal dialog box is hidden, yet there somehow.  Pressing escape gives me back control of Cura.

### Actual results

Cura won't respond, windows beeps as thought here is a modal dialog box stopping behavior

### Expected results

I should see a help screen and Cura should respond

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing else

**Comment by fieldOfView** [comment]
Could you please attach the Cura.log file to this issue (via the webinterface; github strips attachments from email replies)?

%APPDATA%\cura\<Cura version>\cura.log (Windows), or usually C:\Users\<your username>\AppData\Roaming\cura\5.0\cura.log
