### ISSUE TITLE
Missing support if "Use Adaptive Layer" is enabled

### ISSUE THREAD

**Issue by Skybeat** [Ultimaker/Cura#12016]
### Application Version

5.0 beta

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Slice a object what needs support with "Use Adaptive Layer" disabled and support enabled
![Adaptive_Layer_Disabled](https://user-images.githubusercontent.com/9727699/165909758-90c2fb34-1fe5-4e14-8d21-3b23ebc89c78.png)

Slice the same object  with "Use Adaptive Layer" enabled and support enabled
![Adaptive_Layer_Enabled](https://user-images.githubusercontent.com/9727699/165909856-78c28ad7-4d82-46b4-9848-4c5a71939cd8.png)

As you can see there is support missing as soon as "Use Adaptive Layer" is enabled and the object is sliced. 
In the case of the images, you can see that with "Use Adaptive Layers" enabled, Cura try to print a part of the object in the air.

### Actual results

print will fail because of missing support

### Expected results

that the same support is available no matter if "Use Adaptive Layer" is enabled or disabled.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

After checking Cura 4.13.1, I can tell thet there is the same issue.

**Comment by Skybeat** [comment]
since I have seen that other bug reports have already been responded to, I wanted to ask if you have already seen my bug.

**Comment by fvrmr** [comment]
Hi @Skybeat thank you for your report.
Could you share your project file (file - save project) and share it here as a .zip on GitHub.

**Comment by Skybeat** [comment]
> Hi @Skybeat thank you for your report. Could you share your project file (file - save project) and share it here as a .zip on GitHub.
I tried but i get all the time the message "is not included in the list" after I add the zip to my comment in github.

**Comment by Skybeat** [comment]
Attached my project as ZIP

**Comment by Skybeat** [comment]
sorry I clicked the wrong button and closed the ticket. 
I can't add the zip even if I trie in differend browsers, I get all the time the message  "is not included in the list"

**Comment by Skybeat** [comment]
since I'm not able to add the zip directly in GITHUB I have added it to my onedrive. You can dowloaded the zip from this link
[https://1drv.ms/u/s!AnayxfPV8dxsivkeG3DfCPWvINAH9Q?e=ap7E2C](url)

**Comment by Skybeat** [comment]
@nallath thank you ;-)

**Comment by nallath** [comment]
Sorry that it took so long! I've been able to reproduce your issue and I will discuss it with the rest of the team.

**Comment by Skybeat** [comment]
> Sorry that it took so long! I've been able to reproduce your issue and I will discuss it with the rest of the team.

you are welcome and thank you for the update.

**Comment by nallath** [comment]
We already had a ticket that mentions this issue on our backlog. It turns out that it happens for skin as well (which is the original thing it was reported on!). That also explains why I wasn't able to find it in the first place.

For future reference: CURA-5104
