### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by moliisi** [Ultimaker/Cura#12013]
### Application Version

Ultimaker-Cura-5.0.0-beta+1-win64

### Platform

windows10

### Printer

Creality3

### Reproduction steps

I opened file to slice
cura show model errors, 

### Actual results

slicing failed

### Expected results

slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/104609569/165881268-cd173105-80b8-4150-97b6-535545fec082.png)
[cura.log](https://github.com/Ultimaker/Cura/files/8587945/cura.log)

![image](https://user-images.githubusercontent.com/104609569/165882289-f923d7a1-cad4-4e6a-9dc2-36aec16fbe09.png)

**Comment by fvrmr** [comment]
Hi @moliisi thank you for your report.
Could you share your project file (file - save project) and share it here as a .zip on GitHub?
