### ISSUE TITLE
Random under extrusion near z-seam

### ISSUE THREAD

**Issue by LasagnaSam** [Ultimaker/Cura#12026]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

I tried printing a few things in Cura 5.0 beta out of curiosity. I am printing with petg at 240 degrees Celsius on an ender 3 pro. I used my normal Cura profile for petg from cura 4.13.1 which usually gives me good prints. 

### Actual results

When I print something in Cura 5.0 beta I get a rough surface near the z-seam. It seems that there is under extrusion near this region.

### Expected results

Extrusion should be consistent and surface should be fairly smooth even near the seam. When I slice the exact same model with the exact same slicer profile in Cura 4.13.1 I get a normal looking surface.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

![Screenshot (70)](https://user-images.githubusercontent.com/104661565/166085999-861cbaa6-5c5f-4055-a8d2-25d2590b684c.png)
21a721e5ad3e.jpg)
![20220429_213157](https://user-images.githubusercontent.com/104661565/166085953-a9b780c5-991d-4ca2-b64a-6b81e572984d.jpg)
![20220429_203421](https://user-images.githubusercontent.com/104661565/166086034-dbfea55e-2701-4b9d-8c59-02014e9125e4.jpg)
[CE3PRO_calicat.zip](https://github.com/Ultimaker/Cura/files/8606131/CE3PRO_calicat.zip)

**Comment by fvrmr** [comment]
Hi @LasagnaSam thank you for your report.
Could you share your project file (file - save project) and share it here as a .zip on GitHub.

**Comment by LasagnaSam** [comment]
I just added the project file for the model I sliced in Cura 5.0

**Comment by skl111** [comment]
Any feedback, I am experiencing this as well. various brands of petg around 240/245. I see a model was uploaded, did it show anything?

**Comment by nallath** [comment]
Bad bot!

**Comment by nallath** [comment]
Sorry that this got closed! The bot was broken for a while and it never removed the label. I fixed the bot yesterday, so it closed it

**Comment by Arne-W** [comment]
I have the same issue on an Anycubic Vyper. Since I changed to 5.0.0 I have problems with under extrusion near z-seam. I did a lot of experimenting but was not able to fix it.
For now I will switch back to 4.13 an check if that fixes the issue fro me.

**Comment by skl111** [comment]
If you try wall order setting and change it from "outside to inside" to
"inside to outside" that should make it work like 4.x
