### ISSUE TITLE
model is not cutting

### ISSUE THREAD

**Issue by MembI4** [Ultimaker/Cura#12022]
### Application Version

5.0.0-beta+1

### Platform

win10

### Printer

custom

### Reproduction steps

I was change profile to another material, and I was push the bottom for slice

### Actual results

I have notification about unknow trouble

### Expected results

generate g-code for printing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8592546/cura.log)

**Comment by fvrmr** [comment]
Hi @MembI4 thank you for your report. 
Could you also share your project file (file - save project) and share it here in a .zip on GitHub?
