### ISSUE TITLE
infill-walls connection problem

### ISSUE THREAD

**Issue by soleshoe** [Ultimaker/Cura#12030]
### Application Version

5 beta 1

### Platform

macOS 10.15.7

### Printer

X5SA Pro (Klipper)

### Reproduction steps

Random effect seems to appear on large surfaces only.
The problem is not seen using Cura 4.13

### Actual results

infill doesn't connect well to walls from time to time when printing...

![IMG_1145](https://user-images.githubusercontent.com/940041/166096177-1035f9f7-0ae4-4e4f-874a-fc03ee973189.jpg)

![TXXPRO2ED01P_exhaust middle cover 10mm Hepa filter](https://user-images.githubusercontent.com/940041/166096313-c1931465-76af-4fd5-8ecd-b8a7422c1cd7.jpg)

### Expected results

smooth connection between infill and walls

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[tronxy_x5sa_vzbot_-_non_moving_parts.inst.cfg.zip](https://github.com/Ultimaker/Cura/files/8596354/tronxy_x5sa_vzbot_-_non_moving_parts.inst.cfg.zip)

**Comment by fvrmr** [comment]
Hi @soleshoe thank you for your report.
Could you share your project file (file - save project) and share it here on GitHub as a .zip file.
