### ISSUE TITLE
Initial Layer: Brim only

### ISSUE THREAD

**Issue by DoganM95** [Ultimaker/Cura#12032]
### Is your feature request related to a problem?

First layers can have tiny circles/lines etc. These are very hard to stick to the bad becuase of their size and most of the times get loose and ruin the print.

### Describe the solution you'd like

Cura should offer filling the complete initial layer with brim only, meaning no tiny inner objects like lines, circles, etc. instead it should create the complete first layer from the most outer wall to the center in one go, without stopping, without any gaps in between. This would create a 100% infill first layer to make the first layer stick perfectly and giving the chance to add tiny parts to the bottom of the object.

### Describe alternatives you've considered

- Gluestick for first layer (mess)
- Increasing temps (mess)

### Affected users and/or printers

everyone, who has small parts in their print will benefit. Afrer print, it will only require a quick post-processsing (by hand), cutting the excessive brim off the first layer.

### Additional information & file uploads

This is the current situation, brim (turquoise) is only used on the outside. Small rings (green) will easily lift and mess up the whole print.
![bad](https://user-images.githubusercontent.com/38842553/166105476-e2ecab9c-4d77-45c0-afd7-a7dcee603959.PNG)

This is at least in color what i mean. The whole layer should be printed in one go, in this case in circular motions from the outside to the inside. It should only take the most outer wall of the part to print as a reference, crete an outer brim and fill the inside of the first layer completely.
![gud](https://user-images.githubusercontent.com/38842553/166106000-8c5f35f0-b3fa-4c98-a47b-8a2e5faf9083.PNG)

**Comment by nallath** [comment]
So like a raft?

**Comment by DoganM95** [comment]
Yes, seems like the Raft was exactly what i was looking for. Thanks alot!
