### ISSUE TITLE
Slicing bug report

### ISSUE THREAD

**Issue by Grisoulefifou** [Ultimaker/Cura#12035]
### Application Version

5.0

### Platform

Windows10

### Printer

ender 5 plus

### Reproduction steps

I opened a sent profile but when I want to slice, there is a message error that says slicing failed

### Actual results

I can't slice

### Expected results

Still can't slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture d’écran 2022-04-30 175912](https://user-images.githubusercontent.com/96694660/166113083-18539422-74cf-4941-8b88-81e4afd0c20f.jpg)

**Comment by fvrmr** [comment]
Hi @Grisoulefifou thank you for your report. 
Could you share your project file (file - save project) and share it here as a .zip on GitHub?
