### ISSUE TITLE
Cura 5.0 Beta Marketplace scrollbar is not working correctly

### ISSUE THREAD

**Issue by KimmoHop** [Ultimaker/Cura#12043]
### Application Version

5.0.0-beta+1

### Platform

Windows 10 Home 21H2, AMD Ryzen 5 4500U with Radeon Graphics

### Printer

based on Ender 3 Pro

### Reproduction steps

1. Open Marketplace
2. Try to scroll down using scrollbar (grab it with mouse and pull)

### Actual results

Pulling scrollbar does nothing. If scrolled with e.g. mouse wheel, scrollbar is not within range

### Expected results

Pulling scrollbar should work and reveal more plugins (when they are there, currently there is like 8 plugins)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Log file from today, using Marketplace:
[kt-marketplace-cura.log](https://github.com/Ultimaker/Cura/files/8598578/kt-marketplace-cura.log)

Looks like that's all:
![image](https://user-images.githubusercontent.com/4123150/166139085-e7939256-cec7-447a-8202-97dca9366fd6.png)

But there's more and scrollbar is out of range:
![image](https://user-images.githubusercontent.com/4123150/166139111-bf7ccac2-7dbd-4540-8798-681fcbb887a4.png)

**Comment by fvrmr** [comment]
Hi @KimmoHop thank you for your report.
This is a known issue and is fixed for the stable release! I just checked an internal build and there it is working as expected. 
So I will close this issue!
