### ISSUE TITLE
Two extruder menu appears

### ISSUE THREAD

**Issue by yhira1023** [Ultimaker/Cura#12050]
### Application Version

5.0.0 β

### Platform

Windows 11

### Printer

Tronxy X5SA or Ender3

### Reproduction steps

1. Resist two printers
2. Switch another printer
3. Two Extruder menu appears in Settings menu
4. select 2nd extruder menu ,then Cura will hang up.

### Actual results

Cura will hang up.

### Expected results

run without hang up

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[stderr.log](https://github.com/Ultimaker/Cura/files/8599975/stderr.log)

**Comment by nallath** [comment]
I've already fixed this for the 5.0 release. Thanks for reporting it!
