### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by Meanmachine69** [Ultimaker/Cura#12053]
### Application Version

5.0.0-beta+1

### Platform

Window 10

### Printer

Ultimaker 3

### Reproduction steps

1.opening model (.3mf 1.913 kB)
2. centering model (just by clicking on "center selected")
2.Settings extra fine was already selected
3.click on slice

### Actual results

message "slicing failed" appeared after 50% of slicing

### Expected results

a slicing model should have been made ;)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8601007/cura.log)

**Comment by fvrmr** [comment]
Hi @Meanmachine69 thank you for your report.
Could you share your project file (file - save project) and share it here as a .zip on GitHub?
