### ISSUE TITLE
no extruye material

### ISSUE THREAD

**Issue by Omher21** [Ultimaker/Cura#12069]
### Application Version

5.0.0 beta

### Platform

windows 10

### Printer

Creality Ender 3 Max

### Reproduction steps

preparo el objeto en Cura y mando a imprimir

### Actual results

despues de algunas capas deja de extruir material, ya cambie el motor del extrusor pensando que podria ser ese el tema, pero extactamente a la misma altura vuelve a dejar de extruir

### Expected results

deberia imprimir bien, ya hice la prueba en 4.12.1 y la impresión sale correcta con ambos motores.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

mi impresora es una ender 3 max con motor pancake y un bmg, nunca tengo problemas de extrusión, llevo tiempo imprimiendo pero con esta version de cura siempre se traba

**Comment by fvrmr** [comment]
Hi @Omher21 thank you for your report.
Did you use the same project file for 4.12.1 and 5.0 beta? 

For next time please report your issues in English!
