### ISSUE TITLE
Invisible Camera Button

### ISSUE THREAD

**Issue by jonklopp1** [Ultimaker/Cura#12067]
### Application Version

5.0.0

### Platform

Windows 20

### Printer

Ultimaker 3

### Reproduction steps

The camera button is invisible on the monitor tab.

### Actual results

Cannot see the camera button, but you can use it.

### Expected results

The camera button should be visible

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![nocam](https://user-images.githubusercontent.com/43683378/166345599-94921437-e3b8-4314-b56b-4df1b6b8ff64.JPG)

**Comment by fieldOfView** [comment]
Thanks for reporting. This has already been fixed for the release version.
