### ISSUE TITLE
Falha ao fatiar

### ISSUE THREAD

**Issue by oc-leite** [Ultimaker/Cura#12061]
### Application Version

ultimaker cura 5 beta

### Platform

Windows 10

### Printer

Creality ender3

### Reproduction steps

1. Importei e  dimensionei o objeto na mesa de impressão
2. Escolhi as configurações

### Actual results

erro de fatiamento após alguns minutos

### Expected results

o resultado esperado seria o fatiamento do modelo

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/104722144/166228480-d8eea26f-cd8f-421a-8683-6dbbe49d3f26.png)
[cura.log](https://github.com/Ultimaker/Cura/files/8602590/cura.log)

**Comment by fvrmr** [comment]
Hi @oc-leite thank you for your report.
Could you share your project file (file - save project) here as a .zip on Github?

**Comment by oc-leite** [comment]
[base under hulk.zip](https://github.com/Ultimaker/Cura/files/8603059/base.under.hulk.zip)

**Comment by fvrmr** [comment]
Thank you, unfortunately I can't reproduce your issue with an stl file. Could you share a project file (file - save project)?
