### ISSUE TITLE
Too small Birm

### ISSUE THREAD

**Issue by J0h4nP** [Ultimaker/Cura#1206]
I do not know if this is a handling error or a bug?
I flipped it and the problem was solved for me.
![skarmavbild 2016-12-03 kl 10 32 14](https://cloud.githubusercontent.com/assets/22328138/20858346/35949132-b944-11e6-8702-3976ddc0b998.png)
![skarmavbild 2016-12-03 kl 10 20 20](https://cloud.githubusercontent.com/assets/22328138/20858349/3cd1672c-b944-11e6-86d9-47490fc9dd30.png)
![skarmavbild 2016-12-03 kl 10 19 49](https://cloud.githubusercontent.com/assets/22328138/20858350/40426dfc-b944-11e6-92e4-08e84acdfd54.png)

**Comment by Ghostkeeper** [comment]
We have no error handling that does that sort of thing. It looks like a bug to me.

**Comment by Ghostkeeper** [comment]
Is the component you're slicing available somewhere?
This bug doesn't reproduce on other models I've tried.

**Comment by J0h4nP** [comment]
https://www.dropbox.com/s/otwbo53buwjk8b5/Landskap.stl?dl=0

**Comment by thopiekar** [comment]
I tried to reproduce here with my BH2 and get something different on master.
Instead it doesn't center the model and says that the model doesn't fit on the plate.
Centering it manually work and the model becomes yellow (so it fits) and slices.

**Comment by thopiekar** [comment]
Apart from that, everything works here. I also had a similar effect like @J0h4nP , but that's why the model is not completely flat at the bottom. Enabling support creates the brim correctly of course.

PS: About the centering problem: I'll add a JIRA ticket plus video I made here.

**Comment by Ghostkeeper** [comment]
The model is indeed a bit crooked. It only creates a brim around the part that is touching the bed.

Lay Flat seems to work to put the entire bottom against the bed.

**Comment by thopiekar** [comment]
Added the centering issue to JIRA: CURA-3091

**Comment by J0h4nP** [comment]
In summary: the error was somewhere between the keyboard and backrest :)

**Comment by thopiekar** [comment]
Correct :sweat_smile:
