### ISSUE TITLE
Bottom Progress Bar in Preview screen

### ISSUE THREAD

**Issue by ItsJohnKelly** [Ultimaker/Cura#12077]
### Application Version

5.0.0 Beta+1

### Platform

Win10

### Printer

Ender 5

### Reproduction steps

I loaded a model I had previously sliced in 4.13.1 with success.
I sliced it in 5 Beta
I went to preview screen and saw the vertical progress bar (Layers) on the right but there was none on the bottom edge or, the start icon. So could not run the preview in the usual way
![image_2022-05-03_210006667](https://user-images.githubusercontent.com/104865733/166556256-53ae691d-d7d2-447d-aa79-263f5cb42ae3.png)

### Actual results

cant watch preview in usual manner

### Expected results

Should have seen bottom progress bar

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8613957/cura.log)

[5.0_20220503_193657.zip](https://github.com/Ultimaker/Cura/files/8613982/5.0_20220503_193657.zip)

**Comment by fvrmr** [comment]
Hi @ItsJohnKelly thank you for your report.
Is it possible that you have enabled Force layer view compatibility mode in preferences?

**Comment by ItsJohnKelly** [comment]
Oh good grief,  I have never knowingly used that option but you are correct, it WAS turned on.  Strange though that such an option should hide the horizontal progress bar.

Thanks for your help, John
