### ISSUE TITLE
Vase mode does not respect, wall count etc.

### ISSUE THREAD

**Issue by PhilBaz** [Ultimaker/Cura#12075]
### Application Version

5

### Platform

win 10

### Printer

Voron 2.4

### Reproduction steps

 Vase mode does not respect, wall count, bottom pattern, extra skin wall for initial layer, for initial skin layer. 

### Actual results

concentric

### Expected results

respect wall , etc. for initial skin layer.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

nothing

**Comment by fvrmr** [comment]
Hi @PhilBaz thank you for your report.
This is expected behaviour with using Spiralize Outer Contour. This feature will print a solid bottom and only a single wall. 
Read here more about Spiralize Outer Contour: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/blackmagic/magic_spiralize.md

Let me know if this makes sense to you!

**Comment by PhilBaz** [comment]
Im only talking about the **initial layer**. The bottom skin. The setting for, wall count, bottom pattern, extra skin wall **for initial layer**, should all have an impact. They did previously.

At the very least choice of skin pattern.

**Comment by PhilBaz** [comment]
@nallath  does this need something? does the explanation of the problem make sense?

**Comment by PhilBaz** [comment]
@fvrmr @nallath encountered the issue again in the new 5.0

I've added both an image and project file....

![khgkjhk](https://user-images.githubusercontent.com/21558241/170531486-206919e0-64f6-4046-b42d-d855736dcfb4.jpg)
[bottom layer pattern.zip](https://github.com/Ultimaker/Cura/files/8780502/bottom.layer.pattern.zip)

**Comment by PhilBaz** [comment]
There is now a duplicate report.

https://github.com/Ultimaker/Cura/issues/12391

**Comment by gitlui** [comment]
As the duplicate got closed I'm commenting here to get notifications. I print a lot of boxes in vase mode and the bottom is unusable for me like this. Still using 4.13 for the time being. Hope you can fix this soon :-)

**Comment by Vandresc** [comment]
Devs see CURA-7296 for our internal reference.

**Comment by hapklaar** [comment]
Hi, Is this still on the radar to get fixed?

**Comment by Vandresc** [comment]
This is now fixed in 5.2.

**Comment by PhilBaz** [comment]
@Vandresc 

I found new errors related to this in the 5.2 beta. You want them posted here?

**Comment by PhilBaz** [comment]
@Vandresc @nallath 

here...

https://github.com/Ultimaker/Cura/issues/13420
