### ISSUE TITLE
Profile doesn't exports

### ISSUE THREAD

**Issue by HukpoFuJl** [Ultimaker/Cura#12071]
### Application Version

5.0.0-beta+1

### Platform

Windows 10 LTSC 1809

### Printer

FlyingBear Ghost 5

### Reproduction steps

Create new profile. Try to export. 

### Actual results

Nothing happend.

### Expected results

File with profile must be created :)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Permissions is ok, trying save to root directory of many disks.

**Comment by PhilBaz** [comment]
Me too! Cant export profiles. Can save them but not export.

**Comment by fvrmr** [comment]
Hi @HukpoFuJl thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11971, so I will close this issue.
