### ISSUE TITLE
Extruding on Pause at Height when using retraction

### ISSUE THREAD

**Issue by DigitalSketch** [Ultimaker/Cura#12074]
### Application Version

5.0.0-beta+1

### Platform

Win 10

### Printer

Ender 3 V2

### Reproduction steps

Using the "Pause at height" Post Processing plugin, I set the Retraction to 500 to pull the filament out of my extruder. When I added the new filament and resumed the print, the extruder ran for a long time and pushed out a lot of filament right over the print. The nozzle moved to the position to start printing again and pushed out the extra filament.  

This happened on a production print, so I created a print test. The extrusion happened as described with the test as well. When I removed the Retraction number on the second test, no extrusion occurred. 

Attached are the gcode files used and a screenshot of the Pause at height settings for the "CE3_Me_Test.gcode" file.
 

### Actual results

After changing the filament, the nozzle moves to the position to start printing again and then extrudes a lot of filament. I'm guessing it's the same amount of filament that was retracted. 

### Expected results

After the filament is replaced and the print is resumed, I expected it to simply start printing where it left off. Or to extrude the filament at the Park Print Head X and Y,  not over the position where it should resume printing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Screenshot of the Pause at height settings used in the CE3_Me_Test.gcode file:
![Ultimaker-Cura_kNiTpqxnOs](https://user-images.githubusercontent.com/15157975/166516293-f8d29197-c1e2-4e79-bf1b-8f88ebcb43d9.png)

gcode test files I created. CE3_Me_Test.gcode file has the 500 retraction setting and the CE3_Me_Test_NoRetract.gcode has the 0 retraction setting and had no extrusion. 
[Pause_at_height_Print_Tests.zip](https://github.com/Ultimaker/Cura/files/8612721/Pause_at_height_Print_Tests.zip)

**Comment by fvrmr** [comment]
Hi @DigitalSketch thank you for your report.
Could you also share your project file (file - save project) and share it here as a .zip on GitHub.

**Comment by DigitalSketch** [comment]
[CE3_Me_Test.zip](https://github.com/Ultimaker/Cura/files/8631656/CE3_Me_Test.zip)

**Comment by nallath** [comment]
Bad bot! This shouldn't be closed...

**Comment by GregValiant** [comment]
I'm going through and cleaning up these old reports.  I'll close this.  Pause at Height has been rewritten (for 5.13.0) and these issues should be resolved.  The new version has "unloads" and retractions are handled in the code so the user doesn't have to fool with them.
