### ISSUE TITLE
Проблема со швом

### ISSUE THREAD

**Issue by usergey1961** [Ultimaker/Cura#12070]
### Application Version

5.0.0-beta+1

### Platform

Windows10

### Printer

Ender-3 pro

### Reproduction steps

Пытаюсь установить шов в режим "Острейший угол"

### Actual results

Шов где попало
[Экструдер.zip](https://github.com/Ultimaker/Cura/files/8609650/default.zip)

### Expected results

Все швы должны быть на одном остром угле
[Экструдер.zip](https://github.com/Ultimaker/Cura/files/8609625/default.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

qqqqqqqqqqqq

**Comment by fvrmr** [comment]
Hi @usergey1961 thank you for your report. 
Could you share a project file (file - save project) instead of a stl? 
And please report your bugs in English so everybody can understand your issue!
