### ISSUE TITLE
[5.0 beta] Red/invalid "wall transistion length" does not disable slicing.

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#12082]
### Application Version

5.0 beta

### Platform

win10

### Printer

custom fff

### Reproduction steps

Accidentally entered 5mm line width instead of 0.5, see project.

### Actual results

Wall transition length turns red but slicing is still allowed.

### Expected results

Slicing should be disabled or setting should not turn red.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![opticooler](https://user-images.githubusercontent.com/32172100/166636622-b5ebb2a7-2478-4ec9-a364-7d589a8f89d4.jpg)
[Uploading OpticoolerFunels.3mf.zip…]()

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your report.
Your project file is not correctly uploaded. Could you upload it again?

**Comment by printingotb** [comment]
Try now.
[OpticoolerFunels.3mf.zip](https://github.com/Ultimaker/Cura/files/8621051/OpticoolerFunels.3mf.zip)

**Comment by fieldOfView** [comment]
There's a difference between orange and red. Red means: error, can't slice with this value. Orange means: are you sure? I don't think that's a good idea, but if you say so I'll slice with this value.

**Comment by fieldOfView** [comment]
To elaborate: red is normally limited to values that are physically impossible, such as a speed that is faster than the speed of light, or a layer height of 0. Orange means the value seems to exceed a normal, usable range.

**Comment by nallath** [comment]
I think @printingotb is correct. Any setting in error state currently does not prevent slicing (and it should!)

**Comment by fvrmr** [comment]
We have a ticket on our backlog for this!
Devs see CURA-9249
