### ISSUE TITLE
Destek

### ISSUE THREAD

**Issue by tuka50** [Ultimaker/Cura#12080]
### Application Version

5.0

### Platform

Windows 10

### Printer

custom

### Reproduction steps

bazı yerlerde destek atması gerekirken atmıyor

![image](https://user-images.githubusercontent.com/61657248/166586691-d509a82a-1910-478b-875b-d5b1566a1d29.png)
![Ekran Alıntısı](https://user-images.githubusercontent.com/61657248/166586736-5bc1344d-fb0c-4b71-a15a-8833235315aa.PNG)
![Ekran Alıntısı 2PNG](https://user-images.githubusercontent.com/61657248/166586738-caa10a63-43b2-4501-b534-b1abdd523951.PNG)

### Actual results

desteği tamamına atması gerekiyor

### Expected results

düzeltilmesini talep ediyorum

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

ilk defa cura kullanıyorum

**Comment by GregValiant** [comment]
Did you manage to determine the problem?
