### ISSUE TITLE
Doesnt save to USB

### ISSUE THREAD

**Issue by Dvddylucid** [Ultimaker/Cura#12097]
### Application Version

5.0

### Platform

chromebook

### Printer

Ender 3 v2 

### Reproduction steps

got my ender 3 v2 set it all up downloaded cura thru linux but when i try to open a file nothing happens i have to open my download folder and drag the file to cura and it shows cool i hit splice it does its thing when it shows save to USB i click i and nothing happens just stays on cura i have done everything posted the problem on communities no answer plz help im giving up

### Actual results

i uninstalled cura and redownloaded it got a diffrent slicer but they dont even open !!

### Expected results

i just want to print something man even a damn line

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

im giving up n praying the 3D gods help me

**Comment by fieldOfView** [comment]
I don't know about the gods, but the rest of us need to see your log file to know what is going on. Cura.log can be found via Help -> Show configuration folder.
