### ISSUE TITLE
no permite la segmentacion

### ISSUE THREAD

**Issue by jessiygus** [Ultimaker/Cura#12093]
### Application Version

4.13.1

### Platform

linux

### Printer

anet et4

### Reproduction steps

intento segmentar cualquier archivo y no puedo, dice que ocurre un error inesperado antes de finalizar el proceso de corte.

### Actual results

no segmenta

### Expected results

el archivo segmentado

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fieldOfView** [comment]
Can you please report issues in english? It is not my native language either, but using the english language here vastly increases the number of people that can help you. If you would rather post in spanish, please use the spanish Ultimaker forum instead: https://community.ultimaker.com/forum/125-espa%C3%B1ol/
