### ISSUE TITLE
difference in generated gcode between Windows and Ubuntu versions of Cura 4.13.1

### ISSUE THREAD

**Issue by BenchmarkCreative** [Ultimaker/Cura#12095]
### Application Version

4.13.1

### Platform

Win 7 and ubuntu 20.04

### Printer

Voron V300

### Reproduction steps

Slice the exact same STL, with the exact same profile and printer settings within each Operating system using CURA 4.13.1.  Open the generated gcode and compare.   

### Actual results

There is a visual difference in the top layer of the print, noticeable due to gaps between the top lines
![curaissue](https://user-images.githubusercontent.com/100858983/166854026-cc7763da-aedb-4499-a00f-8a583d589399.png)

The g-code is not the same?  Should it be?

### Expected results

I expected that the files would be identical, or off only by a very small differences that are consistent.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

Added the 2 gcode files in a zip, wouldn't let me upload them and didn't think anyone would want that copied into here :-)

[PrintQueue.zip](https://github.com/Ultimaker/Cura/files/8628330/PrintQueue.zip)

![Untitled picture](https://user-images.githubusercontent.com/100858983/166853441-7a90e0f8-d905-432d-9c1a-2ed66be086da.png)

**Comment by BenchmarkCreative** [comment]
Let me know what additional files you want from each machine?

**Comment by fvrmr** [comment]
Hi @BenchmarkCreative thank you for your report.
Did you use the same project file on Windows and Ubuntu?

**Comment by BenchmarkCreative** [comment]
I used the same STL... I will use duplicate project file tonight when I return home... would you like it done both ways... i.e. create project on Ubuntu and then use on both machines and then vice versa?
Thanks

**Comment by BenchmarkCreative** [comment]
Slicing with same project file yields same gcode... I will need to figure out where the differences were.  Thanks!!!
