### ISSUE TITLE
Switching printers creates multiple extruders in settings menu, the additional ones cause a crash to the desktop.

### ISSUE THREAD

**Issue by glx-seven** [Ultimaker/Cura#12106]
### Application Version

5.0.0-beta+1

### Platform

MacOS 12.3.1

### Printer

Ultimaker S5 and Ultimaker 2 Go

### Reproduction steps

Switching printers in the "Prepare"-tab creates more and more extruders in the "Settings" menu in the menu-bar.

It also happens on my Windows 10 machine.

### Actual results

When hovering on one of these additional Extruder-entries that isn't associated with the current printer, Cura immediately crashes to the desktop. I also attached a MacOS-crashlog below.

### Expected results

It shouldn't create menu-entries, especially when it leads to a crash. 

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

**cura.log:**

[cura.log](https://github.com/Ultimaker/Cura/files/8636435/cura.log)

-------------------------------------
**MacOS error-log:**
[cura-crash_macos.txt](https://github.com/Ultimaker/Cura/files/8636453/cura-crash_macos.txt)

**Comment by MariskaMaas** [comment]
Hi Theo. Thank you for your report.
The behavior you are describing seems similar to https://github.com/Ultimaker/Cura/issues/11988
This has been resolved in Cura 5.0 Stable. Can you check again in the latest version of Cura 5.0?
