### ISSUE TITLE
Ugly seams in 5.0 beta standard print settings. Not smart-hiding?

### ISSUE THREAD

**Issue by Zanderama** [Ultimaker/Cura#12100]
### Application Version

5.0 beta

### Platform

Windows 11

### Printer

Creality Ender 3 V2

### Reproduction steps

Congrats on the 5.0 beta.

However, I found printing the attached simple quarter-sphere results in quite ugly seams in 5.0 beta compared to 4.13.1.  Using the "Standard" print settings on both.  It seems (pun not intended ;) ) that 4.13.1 does its "smart hiding" much better than 5.0 beta, and possibly 5.0 beta is not really trying to hide the seam at all.  

I've not tried printing with "hide seams" rather than the default "smart hiding" yet, in case that helps

[Seam Tester.zip](https://github.com/Ultimaker/Cura/files/8631085/Seam.Tester.zip)

### Actual results

In the images below, Cura 4 is on the left, and Cura 5 is on the right.  You can see Cura 5's lumpy seam on the edge, whereas Cura 4 has tried to hide the seam inside the rear of the object.

![Photo 5-05-22, 10 36 55](https://user-images.githubusercontent.com/630157/166919436-44d275ff-2ac7-4c7f-8123-d4a3761afb9d.jpg)
![Photo 5-05-22, 10 37 24](https://user-images.githubusercontent.com/630157/166919447-b7ae2473-61a5-41ea-bdbf-a2f49eeb26f3.jpg)

### Expected results

I'd expect the seams to be more hidden like Cura 4.13.1.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This may relate to the issue #11877 and CURA-8600 I believe mentioned.

**Comment by sovtek** [comment]
I also found similar results. If it's helpful, i've attached a comparison of the seams in both versions of cura.

Settings of note:
zseam relative (true)
corner preference (none)
z y seam (110)
z x seam (0)
z seam position (back)
z seam alignment (user specified)
<img width="449" alt="cura 4" src="https://user-images.githubusercontent.com/4308409/167663431-21796340-e118-41a7-b8ca-2a3feac7e124.png">
<img width="429" alt="cura 5 beta" src="https://user-images.githubusercontent.com/4308409/167663447-09be6119-7221-4672-a71a-4d3b061c8c81.png">

**Comment by Arashrk82** [comment]
I have the same problem with Cura 5. The Z seam relative is not working like before, the seam line it is not in a straight line anymore.

**Comment by MariskaMaas** [comment]
Hey Zanderama, 
Thanks for reporting this issue and the thorough analysis + pictures. 
We are aware of some zseam issue in 5.0. It seems to be related to the new engine in 5.0.
It was also reported in https://github.com/Ultimaker/Cura/issues/11877.
I'm closing this issue as a duplicate, but you can follow the process there.
