### ISSUE TITLE
Files do not load into Cura 5 beta

### ISSUE THREAD

**Issue by TeleFragger** [Ultimaker/Cura#12103]
### Application Version

5.0.0 beta 1

### Platform

Windows 10

### Printer

Ender 5+

### Reproduction steps

Opened cura, clicked open and chose either file and it just sat there trying to bring the stl in. Worked fine in Cura 4.13

### Actual results

just sat there trying

### Expected results

show stl file
[teschio.zip](https://github.com/Ultimaker/Cura/files/8634553/teschio.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[teschio.zip](https://github.com/Ultimaker/Cura/files/8634555/teschio.zip)

**Comment by MariskaMaas** [comment]
Hey @TeleFragger, thanks for reporting this issue.
I've succesfully been able to open the included STL files. 
Can you please retry please in Cura 5.0 stable? 
If you still run into any trouble, can you share your .log files so we can have a closer look at what is happening? 
Thank you!
