### ISSUE TITLE
Trouble when multiply models

### ISSUE THREAD

**Issue by FranzBalleis** [Ultimaker/Cura#12118]
### Application Version

5.0 beta+

### Platform

windows 10

### Printer

Anycubic Viper

### Reproduction steps

Use of Crtl M copy Model
when make the option to Copy a Model one Time this do not run.
when I use the + Button to chsnge to 2 Copies and the go Back to One Copie thge Programm run as expected.

### Actual results

Nothing happens

### Expected results

No 2 Models should be there.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I suspect that the variable containing the value of the number of copies is not set to 1, although the display field shows this.

**Comment by fieldOfView** [comment]
Thanks for reporting this issue. It has been reported before, and is fixed for the final release of Cura 5.
You may close this issue.
