### ISSUE TITLE
Printing Issue: Speed up feature Causing Printing Issues ??

### ISSUE THREAD

**Issue by dagnall53** [Ultimaker/Cura#12117]
### Application Version

5.0 Beta 1

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Summary:  Using Cura 5 I believe I have come across a print issue related to the print Speed up feature.

After I switched to 5.0 beta.  Noticed that all prints now seemed to have small print distortions at near identical heights. At first, I thought this was a printer issue, but later I needed a very simple cone with a hole and so made quick G code to print three parts (using 5.0 beta1)
ALL three cones exhibited similar large distortions at similar heights when printed.  (see photo)  Most broke at the distortion when removed from build plate.   I printed the same file three times with near identical results.  (G code attached at end) . Unfortunately I had not saved the cone STL, as this was just a "quick" project. 

I checked the printer for height movement issues, and then conducted some slice tests to explore this issue. 
Looking at the G code, I suspected the result was due to the new speed up capability in Cura 5? 
The G code of the problem file seems to show significant speed variations at the heights that are problematic.  

To try and lock down the cause and give you a replicatable problem,  I re-drew the cone (and saved it !) and sliced a test file with the cone and a thin walled box using both 4.13 and 5.0.0.  Unfortunately .. this seemed to print fine. So I repeated the slicing, but this time with just the three cones, as in the original G code.  (Post note- I have discovered that this new cone is not exactly the same size as the original, the new one has 5.9 mm hole, I think the old one had 6mm) 

Although the print issue seems to be reduced, (possibly due the smaller hole diameter ?) the new Cura5 slice prints do demonstrate some issues at about 3mm that are not present when sliced with Cura 4.13 

My suspicion is that the new engine is attempting speed changes that the printer is not capable of. 
The fact that the new slices seem to print better than the original slice is concerning, as this makes the issue harder to pin down. 

.. I did later try a single Cura 5 print with one cone with 5.9 hole and one cone with 6mm hole in the cone, but this did not show any noticeable differences.

### Actual results

Photo of one of the better versions of the original cone after print. It appears that the  "bad" print areas are at what is probably one of the transition layers for speed changes?   
![image](https://user-images.githubusercontent.com/6950560/167113319-251eb99d-e9ad-4667-9bc1-d1b6b2fe74ec.png)

Re-slicing in Cura 5 (and saving the project file) I got this result.:-   This print is now better than the earlier slice, but there is still a distinct issue at about 3mm.  The middle cone in particular has a weakness at 3mm, and broke at this layer on removal. 
Note that there are small but definite issues with the other two cones at the same height. 
~ the effect is much smaller than with my original G- code, but is still noticeable.  

NOTE:  I noted afterwards and while writing this up that the "new" cone has a 5.9mm hole, whereas the original cone had (I think) a 6mm hole. 
This change may have exacerbated the differences in the way that Cura 5 treated the slices? 
![image](https://user-images.githubusercontent.com/6950560/167128050-15d32d05-6916-4ccc-9108-caa0361b0a58.png)

### Expected results

This is a photo of the result using Cura 4.13 : same stl files.
I realise that the differences are visually small, but these prints are all physically strong and removed well from the print bed..
![image](https://user-images.githubusercontent.com/6950560/167128738-0ec7d3cf-72e1-4eb9-bcd7-4e9cba1ec27f.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

The original G code.  NOTE that unfortunately I did not save the .3mf for this one at the time. 
[Original problematic G code.zip](https://github.com/Ultimaker/Cura/files/8639858/Original.problematic.G.code.zip)

Files used for repeat  tests.   (These printed much better than the G code above, BUT the cura 5 file still demonstrated some strange behaviour at circa 3mm ) 

[CE3_Cura5-3Cone Only.zip](https://github.com/Ultimaker/Cura/files/8639869/CE3_Cura5-3Cone.Only.zip)
[CE3_Cura3-3Cone Only.zip](https://github.com/Ultimaker/Cura/files/8639870/CE3_Cura3-3Cone.Only.zip)

**Comment by GregValiant** [comment]
This is your "original problematic G code" file "CE3Body4.gcode" printed on my Ender 3 Pro.  Looks good to me.  I noticed that within the file it says it was sliced with 4.13.1.  Is this really the problem file?
![DSCN2868](https://user-images.githubusercontent.com/64202104/167318638-b31fd98a-ade7-4b1b-913d-ad8cbcefe7c4.JPG)
![DSCN2869](https://user-images.githubusercontent.com/64202104/167318639-8fc34210-8140-4fe1-b186-0548ee9963dd.JPG)

These are from your Cura5-3Cone Only.3mf file.  Your Ender 3 was the active printer and I didn't make any changes to the settings.
![DSCN2872](https://user-images.githubusercontent.com/64202104/167319508-3df42e36-5f36-4eee-9459-1a0a8c661ca7.JPG)
![DSCN2873](https://user-images.githubusercontent.com/64202104/167319509-5d907278-10a2-418c-8c9b-0f05c3e01b21.JPG)

Have you taken a close look at your Z system lately?  I know it seems like a problem between Cura 4.13 and 5.0 but I've been printing a lot with 5.0 and I haven't seen the problem you describe and I don't think I see the problem with these prints.  There was some stringing, but as I say, I made no changes to your settings and my normal retraction distance is 5.5 at 35mm/sec.

**Comment by dagnall53** [comment]
Huge thanks for testing this.. I

I certainly believed that that was the "problematic" file, but it was a
quick and dirty print, so i only saved it with the "body4 name. I looked it
out on theSD cards later,
My later prints on 5 were better. (the ones where I saved the Printing
format etc!) and I did spend a lot of time checking and cleaning the Z
axis.

For full disclosure, My 5V line fuze blew almost on arrival a year or so
ago,  so I replaced the smd fuse with a wired PTC, which managed to
disconnect a week ago..   I did some runs on external 5V (via usb). Then I
had to upend the machine to get at the  PCB and properly resolder the PTC.
I was very careful to try and not misalign the Z axis  during this, but
anything is possible.  I did not record when the "bad prints were done".
but I thought it was after resoldering the PTC, but it might have before.

I also later extensively cleaned the lead screw and put a LITTLE oil on the
bearings.

I have had some excellent prints after this .. no signs of any layer
related issues.. So you could well be correct. - BUT I did use the older
Cura.. just to be sure. ;-)

I will try future prints with 5 and let you know if anything crops up.

Many thanks

Dagnall
