### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by danilopmaciel** [Ultimaker/Cura#12115]
### Is your feature request related to a problem?

Whithout drang and drop i spend more time to load a new arqchive.

### Describe the solution you'd like

Bring back drag and drop =D

### Describe alternatives you've considered

Drag and drop is a solution to load more fast.

### Affected users and/or printers

users pro.

### Additional information & file uploads

When i try drag a object the sginal ou mouse is denny.

**Comment by fieldOfView** [comment]
This has already been reported. It only happens the first time you start Cura (from the setup wizard), or when you launch Cura "As Administrator", which you should not do.

**Comment by danilopmaciel** [comment]
Sorry about that. Thanks for answore. Drag and drop work before a close and open again.

**Comment by fieldOfView** [comment]
You may close this issue...
