### ISSUE TITLE
A translation error in Chinese version

### ISSUE THREAD

**Issue by wumucun** [Ultimaker/Cura#12129]
### Application Version

4.13.1

### Platform

Win 10

### Printer

Ender 3

### Reproduction steps

1.click Maket
2.and then choose plugin
3.enter ThingiBrower plugin

at the top left，is Back（in Chinese is “返回”， return to the last step）

### Actual results

背部,

### Expected results

返回

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

null

**Comment by Joeydelarago** [comment]
Hi, thanks for bringing this to our attention. The 5.0 release will have the corrected text.
