### ISSUE TITLE
Tools swapping

### ISSUE THREAD

**Issue by samfvr** [Ultimaker/Cura#12121]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Tenlog 3D Pro

### Reproduction steps

Slicing for Tenlog3D (IDEX) using the two extruders.

Plate is up before new tool gone the right position.

Thanks for your reply

PS:
When swapping tool, printer parks the unused tool

### Actual results

When swapping tools:
-  plate is down by 1 mm
- tool swap occur
- plate is up by 1mm
- tool move to the rigth place
 Except for the first swapping

Following g-code while swapping tool (with my comment after double slash):

G1 X148.847 Y156.936
G1 F1200 E84.96829
**G1 F600 Z1.6**                                         // Plate down by 1mm
G92 E0
**T1**                                                          // Swap Tool
G92 E0
M105
M109 S200
M104 T0 S190
M106 S255 P2
**G1 F600 Z0.6**                                        // Plate up by 1mm
;MESH:hilbert_cube1_support.stl
**G0 F9000 X154.498 Y154.498**               // Tool move to the right place
;TYPE:WALL-OUTER
G1 F1200 E3
G1 F1500 X154.498 Y167.28 E3.46764

### Expected results

I think, plate should be up after tool is in the right place.
Following the g-code that I except:

G1 X148.847 Y156.936
G1 F1200 E84.96829
**G1 F600 Z1.6**                                         // Plate down by 1mm
G92 E0
**T1**                                                          // Swap Tool
G92 E0
M105
M109 S200
M104 T0 S190
M106 S255 P2
;MESH:hilbert_cube1_support.stl
**G0 F9000 X154.498 Y154.498**               // Tool move to the right place
**G1 F600 Z0.6**                                        // Plate up by 1mm
;TYPE:WALL-OUTER
G1 F1200 E3
G1 F1500 X154.498 Y167.28 E3.46764

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[SwapToolIssue.zip](https://github.com/Ultimaker/Cura/files/8642240/SwapToolIssue.zip)

**Comment by MariskaMaas** [comment]
Hey @samfvr 

Thanks for reporting this issue you are encountering.
This seems really printer settings specific and also something that you might be able to resolve yourself. 
There are Extruder Start and End Gcodes where you can specify these settings 
![image](https://user-images.githubusercontent.com/40423138/170082657-16ee7870-d56b-41da-bc4d-de24ab789a73.png)

I'll be deferring this issue. Ultimaker will not create a profile for this printer, but if someone contributes a profile, Ultimaker will add it to Cura just like they did with all the other 3rd party profiles.
