### ISSUE TITLE
Plugin tries to re-install after removal

### ISSUE THREAD

**Issue by Doorman352** [Ultimaker/Cura#12135]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Longer LK1

### Reproduction steps

1. Uninstalled Octoprint plugin
2. Shutdown computer
3. Next day on opening Cura get a message to sync materials and plugins and Octoprint re-installs.
4. Removed, backed up settings.

### Actual results

The plugin deletes from the list but upon starting Cura it wants to sync and re-install it

### Expected results

Plugin should have been removed and not re-installed 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8645738/cura.log)

**Comment by Doorman352** [comment]
Hello,

                After I posted the issue; I loaded the Beta 5.0 and it also tried to sync everything from my account, unsuccessfully. This weekend, I loaded the 5.0 final release and after the first sync my issues resolved and now Octoprint is showing available to install but is not trying to re-install itself after each start of Cura. 

 

                I agree it was probably something in the account, but it would not resolve until after I installed 5.0 final release and then after the initial sync, my account issues have resolved themselves and it did not try to re-install the Octoprint plugin.

 

                Thank you for your time investigating this issue, and I apologize for not posting any update. I was actually really busy using Cura 5.0 and enjoying all the great updates, I haven’t found anything yet that it doesn’t do better. My only problem was that my custom materials did not automatically import, but I was able to get them manually.

 

Thank You

 

 

Sean Parsons (AKA Doorman352)

**Comment by Ghostkeeper** [comment]
We'll consider this issue to be resolved then, but it's a good reminder that we need to look at the workflow of syncing plug-ins with the client for cases such as this.
