### ISSUE TITLE
5.0 Opens Some 4.13 Project Files Incorrectly

### ISSUE THREAD

**Issue by rachael7** [Ultimaker/Cura#12139]
### Application Version

5.0 Beta

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Slice a part in Cura 4.13 using a standard profile that has 0.0mm values for horizontal expansion and initial layer horizontal expansion.
2. Observe that the values for horizontal expansion and initial layer horizontal expansion, are both 0.0mm.
3. Save the 3mf project file.
4. Close Cura 4.13 and open Cura 5.0 Beta.
5. Open the 3mf project file saved in step 3.
6. Observe the values for horizontal expansion and initial layer horizontal expansion are non-zero.

### Actual results

Both horizontal expansion and initial layer horizontal expansion showed a value of -0.02mm when I opened the 3mf project file. That value does not correspond to the default value in the profile , nor does it correspond to the values saved with the project file.

### Expected results

Both horizontal expansion and initial layer horizontal expansion should have shown a value of 0.0mm, as they were saved in Cura 4.13.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

For some reason, my ZIP file of the project will not upload directly to Github, despite being only 76kB, so I put it on my DropBox. It can be downloaded [here](https://www.dropbox.com/s/r0e8h81z6yqtd87/Test.zip?dl=0).

![Test-Cura-4 13](https://user-images.githubusercontent.com/47545009/167277714-a49f4860-637b-4fd1-997e-afe64f49c100.jpg)
![Test-Cura-5 0](https://user-images.githubusercontent.com/47545009/167277713-919f5878-7c4a-4b51-a876-ea2df77d9b04.jpg)

**Comment by nallath** [comment]
This is intentional. We found out that the default horizontal expansion needed to be set to this for better results with the new slicing engine.
