### ISSUE TITLE
Combing Mode no longer changes behaviour of travel moves

### ISSUE THREAD

**Issue by coreyfaure** [Ultimaker/Cura#12133]
### Application Version

5.0 Beta

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. I loaded a model that would benefit from keeping the combing mode within the print to avoid stringing.
2. I changed the combing mode to "not on outer surface"

### Actual results

Travel moves do not change to be within printed parts.

### Expected results

Travel moves should be moving within printed parts, as it happened in 4.13.1

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/4889057/167264045-fa9313fe-7a2f-4f65-b326-d4b75c5637db.png)
A side by side comparison of 4.13.1 (right) and 5.0 Beta (left) versions with same settings, different results.

**Comment by MariskaMaas** [comment]
Hey @coreyfaure.

We have some known issues in combing that we are trying to resolve.
Can you share your cura project so we can see if it's related?

To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files.

Thank you!
