### ISSUE TITLE
Print quality issue 

### ISSUE THREAD

**Issue by JerryCih** [Ultimaker/Cura#12138]
### Application Version

5.0.0 Beta

### Platform

Windows 10

### Printer

Creality Ender 4 V2

### Reproduction steps

Done twice, same STL file in Cura 5 and twice the same result.
[spacer_plate_1_-_5mm_v4.zip](https://github.com/Ultimaker/Cura/files/8646119/spacer_plate_1_-_5mm_v4.zip)

### Actual results

STL file sliced in Cura 5.0.0 Beta and printed via Octoprint on Ender 3 V2:
 
![20220507_233905](https://user-images.githubusercontent.com/53308206/167275865-6c0f0412-7918-4172-b7c7-c353fce01e83.jpg)
![20220507_233911](https://user-images.githubusercontent.com/53308206/167275867-501f9bc0-fd29-40a6-a4e1-800d8e126fef.jpg)
![20220507_233920](https://user-images.githubusercontent.com/53308206/167275873-eb5a0c63-c2f6-45df-89b8-805211a24f9a.jpg)

### Expected results

Same file sliced in Cura 4.13.1 

![20220507_225606](https://user-images.githubusercontent.com/53308206/167275953-362a7576-32f4-47d7-8e34-f2f86174de5a.jpg)
![20220507_225616](https://user-images.githubusercontent.com/53308206/167275958-4faa5fe6-2569-4514-aee3-c0cd4b797839.jpg)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Cura 5-CE3PRO_spacer_plate_5mm_v4.zip](https://github.com/Ultimaker/Cura/files/8646110/Cura.5-CE3PRO_spacer_plate_5mm_v4.zip)

[Cura 4 CESPRO_spacer_plate_5mm_v4.zip](https://github.com/Ultimaker/Cura/files/8646111/Cura.4.CESPRO_spacer_plate_5mm_v4.zip)

**Comment by GregValiant** [comment]
With "Generate Support" turned off there was nothing for the first extrusions of the overhang to squish against and so they just followed the nozzle around.  About the max overhang angle you can get by with without support is 63° and that overhang is 70°.  Whether sliced with 4.13 or 5.0 I think you were fortunate to get it to print correctly at all.

**Comment by JerryCih** [comment]
This isnt the first time I'm printing this, never had problems with 4.13 ( 10+ times )

**Comment by GregValiant** [comment]
In 5.0, what do you have as the "Wall Ordering" setting?  "Inside to Outside" has some chance of success.  "Outside to Inside" doesn't really as the outside wall would definitely be air-printed in that overhang.
(I've customized my installation and changed the default  to "Inside to Outside" and so I maybe can't tell what your setting is?)

**Comment by JerryCih** [comment]
I have "outside to inside". I will try to change and print again

**Comment by JerryCih** [comment]
Sorry didnt have time to try to print it again earlier. Changing it to "inside to outside" did the trick. No issue with the orint
![20220517_190935](https://user-images.githubusercontent.com/53308206/168776401-e88da860-9d61-43ee-bfb5-79823a55e991.jpg)
.
