### ISSUE TITLE
Could not probe OpenGL

### ISSUE THREAD

**Issue by dsvi** [Ultimaker/Cura#12146]
### Application Version

5

### Platform

Linux (Ubuntu 22.04)

### Reproduction steps

Cura 5 does not start with the error message:

`Could not probe OpenGL. This program requires OpenGL 2.0 or higher. Please check your video card drivers.`

While Cura 4.x works fine on the same machine. I was using the official Appimage. `cura.log` isn't even created.

**Comment by nallath** [comment]
Duplicate of #11856
