### ISSUE TITLE
Can't export profiles

### ISSUE THREAD

**Issue by TacII** [Ultimaker/Cura#12142]
### Application Version

5.0.0-Beta+1

### Platform

Windows11

### Printer

Ender 3

### Reproduction steps

1) Opened  "Manage Profiles"
2) Selected a custom profile
3) Pressed the "hamburger"-menu, selected export
4) Saved the file 

### Actual results

No file is created on the harddisk. Tried multiple filenames and directories.

### Expected results

A .curaprofile file should be available.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8646705/cura.log)

**Comment by nallath** [comment]
I could reproduce this with the beta, but not with the nightly build for 5.0.0 stable. Seems to have already been fixed.
