### ISSUE TITLE
Changing layer height slider does not affect sliced file

### ISSUE THREAD

**Issue by jrutlen** [Ultimaker/Cura#12150]
### Application Version

5.0b1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Sliced file at 0.2mm height
2. Viewed file preview
3. Changed "Profiles" height slider to 0.28mm
4. Cura does NOT prompt to reslice
5. Cleared build plate and re-loaded model
6. Verified 0.28mm height was still selected
7. Sliced and saved file
8. Opened file in text editor

### Actual results

The layer height in the G code file is still 0.2mm despite the slider being changed and the model re-loaded / re-sliced
![2022-05-09 16_43_05-](https://user-images.githubusercontent.com/47150744/167495550-6877429d-5e16-4805-a4fd-62181ee47edf.png)
.

### Expected results

Cura should prompt to re-slice when a settings change is made and the layer height in the G-code file should respect the setting.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I am unable to save the project file. Nothing happens after selecting "Save Project..." from the 'File' menu.
[cura.log](https://github.com/Ultimaker/Cura/files/8655345/cura.log)

After completely exiting and re-loading Cura 5.0, the 'Profiles' slider does work correctly and adjusts the layer height correctly.

**Comment by Vandresc** [comment]
Hi @jrutlen, thank you for your feedback! 
Question, I see that you are still using the beta version, and not the stable one, is that correct? We had some update issues that we resolved in the 5.0 stable release. https://github.com/Ultimaker/Cura/releases/tag/5.0.0
Could you see if your issue is also resolved? Many thanks!
