### ISSUE TITLE
File Open

### ISSUE THREAD

**Issue by RaminShalom** [Ultimaker/Cura#12151]
### Application Version

 5

### Platform

 Windows 11

### Printer

 Artist-D

### Reproduction steps

 File Open

### Actual results

File open very very slow

### Expected results

File should open fast

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

SAmhain-NoCloak.stl

**Comment by RaminShalom** [comment]
Samhain-NoCloak.stl

**Comment by Vandresc** [comment]
Hi @RaminShalom, thank you for your feedback. 
We were hoping you could provide us with a bit more information, like the logs and maybe you can zip and upload the file again? Is the loading of the file in Cura slow? 
Thank you
