### ISSUE TITLE
Some Simplified Chinese translation errors

### ISSUE THREAD

**Issue by iBral** [Ultimaker/Cura#12169]
### Application Version

5.0

### Platform

Win10

### Printer

Voron 2.4

### Reproduction steps

Some Simplified Chinese translation errors, I fixed them. see zip files.
[zh_CN.zip](https://github.com/Ultimaker/Cura/files/8669201/zh_CN.zip)
 

### Actual results

Some Simplified Chinese translation errors, I fixed them. 

### Expected results

Some Simplified Chinese translation errors, I fixed them. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Some Simplified Chinese translation errors, I fixed them.

**Comment by fvrmr** [comment]
Hi @iBral thank you for your report.
I will link this to a ticket we have on our backlog!

**Comment by fvrmr** [comment]
Thank you for your changes, we updated it and will be included in 5.0!
