### ISSUE TITLE
will not slice

### ISSUE THREAD

**Issue by BigxCountryx88** [Ultimaker/Cura#12179]
### Application Version

5.0

### Platform

windows

### Printer

creality ender 5 plus

### Reproduction steps

loaded model, adjusted scale, selected slice

### Actual results

slice failed

### Expected results

complete slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fvrmr** [comment]
Hi @BigxCountryx88 thank you for your report.
Could you share your project file (file - save project) and share it as a zip here on GitHub. Without a project file it is hard to reproduce this issue.
