### ISSUE TITLE
Cura Bug, Slicing Failed

### ISSUE THREAD

**Issue by BirdHunter007** [Ultimaker/Cura#12176]
### Application Version

5.0

### Platform

Windows 10 Enterprise Version 20H2

### Printer

Ender 5

### Reproduction steps

1. Attempted to slice parts created in SolidWorks 2016.

### Actual results

Slice fails.

![Untitled](https://user-images.githubusercontent.com/101292000/167903661-2e6ccd51-f34c-4e50-8501-41d4705a3972.png)

### Expected results

Should be able to create printer file for Ender 5 Pro printer.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Cannot upload zip file as github text boxes state "is not included in the list".

[cura.log](https://github.com/Ultimaker/Cura/files/8671940/cura.log)

**Comment by fvrmr** [comment]
Hi @BirdHunter007 thank you for report. 
Could you also share your project file (file - save project) and sharing it as a .zip should be possible!
