### ISSUE TITLE
Navigation arrows on main screen lost

### ISSUE THREAD

**Issue by baerbar** [Ultimaker/Cura#12173]
### Application Version

5.0.0-beta+1

### Platform

Windows 10 Pro

### Printer

Ultimaker 2+

### Reproduction steps

Nothing unusual! Only select the preferred object.

### Actual results

The Navigation arrows on main screen aren't visible when select a tool like 'move' or 'scale'

### Expected results

E.g. selected object can be move with the arrows on the buildplate

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing

**Comment by fieldOfView** [comment]
Thanks for reporting. The issue only affects systems where Cura is running in "compatibility mode" (opengl 2). It has already been fixed for the full release of Cura 5.0.

**Comment by fvrmr** [comment]
Hi @baerbar thank you for your bug report.
This is indeed a duplicate, see https://github.com/Ultimaker/Cura/issues/11882. So I will close this issue.
