### ISSUE TITLE
The very useful inbuilt help pop up boxes

### ISSUE THREAD

**Issue by zipitupuk** [Ultimaker/Cura#12189]
### Application Version

5.0 beta

### Platform

widows 11

### Printer

Artillery Sidewinder X1

### Reproduction steps

Im new to 3D printing(2 days old lol) and I find the mouse over pop up boxes that explain the slicer setting absoloutly brilliant...BUT
they often have more text information that can be seen in the box, and there is no way to scroll(?) the box and see the rest of the useful text, because as soon as you move the mouse the help box disapears 

### Actual results

mouse over text box help/info appears (brillant for newbies)

### Expected results

the text info in the box as more lines than are visable and no way(?) to keep the box open and scroll down

although I am a newbie to printig, I fully apreciate the work you are putting in to a brilliant piece of soft ware

thank you

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

no log file needed - not that sort of problem and does not relate to any .stl file. its a user interface coding problem

**Comment by GregValiant** [comment]
Me too.

**Comment by nallath** [comment]
This has been fixed for the stable release. Thanks for reporting it :)
