### ISSUE TITLE
Ultimaker 3 Extended - Profile Manger not showing any profiles Cura 2.3.1

### ISSUE THREAD

**Issue by ianlpowell** [Ultimaker/Cura#1218]
Initially Profile Manger show no profiles. Also after creating a new one no profiles is shown in the manger.

**Comment by ianlpowell** [comment]
Here is the log file
[cura.zip](https://github.com/Ultimaker/Cura/files/631753/cura.zip)

**Comment by nickthetait** [comment]
Might help to add a screenshot of this problem

**Comment by ianlpowell** [comment]
Sequence - Creating new profile and result. 

![create](https://cloud.githubusercontent.com/assets/8142448/20898080/de52c878-bb1c-11e6-87d4-d94139114021.png)
![name](https://cloud.githubusercontent.com/assets/8142448/20898087/e8456ff2-bb1c-11e6-93da-936c1d0c46af.png)
![result](https://cloud.githubusercontent.com/assets/8142448/20898096/f4d66546-bb1c-11e6-848f-5c39b75d1dc9.png)

**Comment by fieldOfView** [comment]
So you added a custom material. That is useful information to reproduce your bugreport. Care to share your material file(s)?

**Comment by ianlpowell** [comment]
Do need all of them or just the added ones.
BTW I did not see any profiles just after I installed Cura but at this time I did not know what to expect.
I am running Cura in Windows 10 ver 1607.

**Comment by Ghostkeeper** [comment]
It filters the known profiles based on the "Material Type" field in the material editor. If you changed this to something unknown, Cura won't find any quality profiles to display.

We changed this in 2.4 to display the default profiles (changing only the layer height) if this happens.
