### ISSUE TITLE
Spiral Mode

### ISSUE THREAD

**Issue by Basti10785** [Ultimaker/Cura#12185]
### Application Version

5.0.0-BETA+1

### Platform

MacOS

### Printer

FLSun SR

### Reproduction steps

add part
want to use spiralmode

### Actual results

cura doesn't use spiral mode

### Expected results

no Z seam

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1690" alt="Bildschirmfoto 2022-05-13 um 09 18 24" src="https://user-images.githubusercontent.com/105481995/168232012-7e7dc3de-62f7-46dc-8c6c-9883aa8eab75.png">

**Comment by GregValiant** [comment]
To use spiral mode the part must be solid through-and-through.  That one has a hole in it.  The hole creates a second outside surface and there will be travel moves between the inside surface that faces air, and the outside surface that faces air.
A cylinder would work.  A tube will not.
