### ISSUE TITLE
Hundreds of error windows

### ISSUE THREAD

**Issue by josewmc** [Ultimaker/Cura#12180]
### Application Version

5.0.0-Beta+1

### Platform

Windows 11

### Printer

Delta Kossel Mini - Marlin 2.0

### Reproduction steps

After a few minutes of printing, hundreds of error windows appear and I can't see, they crash my pc. In version 4.13.1 I can print without problems.

### Actual results

I didn't receive any suggestions.

### Expected results

I didn't receive any suggestions.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8674105/cura.log)

**Comment by fvrmr** [comment]
Closing because this is a duplicate.
