### ISSUE TITLE
Cura 5.0 Beta - support blocker added on viewpoint instead of object

### ISSUE THREAD

**Issue by KimmoHop** [Ultimaker/Cura#12187]
### Application Version

5.0.0-beta+1

### Platform

Windows 10 Home 21H2, AMD Ryzen 5 4500U with Radeon Graphics

### Printer

based on Ender 3 Pro

### Reproduction steps

1. Add part on platform
2. Select part
3. Add support blocker on part

### Actual results

Support blocker is added to point of view

### Expected results

Support blocker is added to the part

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/4123150/168278122-ffe54199-1639-435b-aa32-39d0370cc9ac.png)
![image](https://user-images.githubusercontent.com/4123150/168278155-941a5ab3-c244-488c-abd6-70c7d6c9cd24.png)

I'll add project file (and possibly log file) when I get to the other PC ;)

**Comment by fvrmr** [comment]
Hi @KimmoHop thank you for your report.
I couldn't reproduce this with the 5.0 stable, could you try that as well?
If this is still happening, please add you log file.

**Comment by KimmoHop** [comment]
@fvrmr  Works correctly in 5.0 stable :)

![image](https://user-images.githubusercontent.com/4123150/169553940-4fb74d68-f07b-4690-a445-c6495ae4b649.png)
