### ISSUE TITLE
Need to run in administrator mode to have the (5.0.0-Beta+1) run in Windows 11

### ISSUE THREAD

**Issue by ariasfelipe2070** [Ultimaker/Cura#12193]
### Application Version

5.0.0-Beta+1

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Installed the Beta version
The shortcuts were not found in windows menus, even using the windows search
Restarted the laptop
Now the shortcuts are seen in the menu
Cura does not stars, either using the shortcut or launching directly from the executable, it stay as in the picture:
![Screenshot 2022-05-12 175312](https://user-images.githubusercontent.com/61257993/168399194-6ac6145f-0679-43e8-97f8-a9d33b0b607c.png)
If I click the 'splash', it is abprted:
![image](https://user-images.githubusercontent.com/61257993/168399277-fa71c055-cd46-4cbd-b407-32bbe9482166.png)
If  I run with the administrator option, it launches and works fine
![image](https://user-images.githubusercontent.com/61257993/168399368-77fc690a-d09f-40bf-94ae-8ea8e9c2152f.png)

This is my system information:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DELL-FELIPE
System Manufacturer	Dell Inc.
System Model	Precision 7740
System Type	x64-based PC
System SKU	0927
Processor	Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.17.0, 12/8/2021
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0K5KK9
BaseBoard Version	A00
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	Spain
Hardware Abstraction Layer	Version = "10.0.22000.527"
User Name	DELL-FELIPE\arias
Time Zone	Mountain Daylight Time
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.8 GB
Available Physical Memory	50.2 GB
Total Virtual Memory	73.3 GB
Available Virtual Memory	57.0 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

 

### Actual results

Cura runs only if I launch it in administrator mode

### Expected results

I expect cura to launch without requiring Administrator mode

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[stderr.log](https://github.com/Ultimaker/Cura/files/8691688/stderr.log)
[cura.log](https://github.com/Ultimaker/Cura/files/8691690/cura.log)

**Comment by Vandresc** [comment]
Hi @ariasfelipe2070 , this should be now fixed in the stable release. Let us know if it is also fixed for you Thank you!
