### ISSUE TITLE
Beta 5 - Font looks blurry/smeared  

### ISSUE THREAD

**Issue by jwhite** [Ultimaker/Cura#12195]
### Application Version

5.0 B1

### Platform

Windows 11

### Printer

Voron

### Reproduction steps

Loading Cura and viewing on a 4k monitor shows smeared/blurry fonts.

### Actual results

<img width="342" alt="image" src="https://user-images.githubusercontent.com/473577/168408131-42077980-9a73-4dfd-8582-5008f2cd254d.png">

<img width="85" alt="image" src="https://user-images.githubusercontent.com/473577/168408147-8fcd8ffc-eef5-478d-a421-84fb80bf4889.png">

### Expected results

Clear fonts.

Cura 4 example :

<img width="80" alt="image" src="https://user-images.githubusercontent.com/473577/168408204-0cfdd443-fae5-4cab-8da1-5d55e6554fb1.png">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fieldOfView** [comment]
It looks like the texts are not aligned on whole pixels. It may be tricky to hunt for the spot where the fractional offset is introduced.

**Comment by fvrmr** [comment]
Hi @jwhite thank you for your report. 
This is a known issue, see https://github.com/Ultimaker/Cura/issues/11957. So I will close this issue.
