### ISSUE TITLE
Dialog crash on Profile change

### ISSUE THREAD

**Issue by usernametakenaaaa** [Ultimaker/Cura#12194]
### Application Version

5.0

### Platform

10

### Printer

S3

### Reproduction steps

Create a new profile ("Super Fine" in my case) 
1st bug: You can only create ONE additional profile, then the option to create one is gone
Now change Layer height to something else
Now change to the prev profile (Fine).

Cura 5 will display an empty dialog window and become unresponsive

### Actual results

Cura 5 will display an empty dialog window and become unresponsive
It's the dialog that asks you to confirm the changes.

### Expected results

Cura 5 will display an proper dialog window and not crash

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

not required

**Comment by Vandresc** [comment]
hi @usernametakenaaaa , the Create new option appears only when there are user changes in the profile, so it is correct that you saw the button only once. if you again make changes to the profile the Create profile will appear again. 
The second issue, Cura becoming unresponsive is new to me and cannot be reproduced, would it be possible to share your logs with us?
