### ISSUE TITLE
STL File Drag and Drop

### ISSUE THREAD

**Issue by BlueHawk77** [Ultimaker/Cura#12206]
### Is your feature request related to a problem?

Please add drag and drop stl files support.

### Describe the solution you'd like

Drag and drop functionality for opening STL files.

### Describe alternatives you've considered

...

### Affected users and/or printers

...

**Comment by fieldOfView** [comment]
If you are using Cura 5.0 Beta 1, then just restart Cura. Drag and drop does not work when you launch Cura "As Administrator". The installer for Cura 5.0 Beta 1 inadvertently launches Cura "As Administrator". Just closing Cura and starting it again after that initial launch by the installer should give you drag and drop back.
