### ISSUE TITLE
Unexpected error during slicing 

### ISSUE THREAD

**Issue by DrKayzed** [Ultimaker/Cura#12205]
### Application Version

5.0.0-beta+1

### Platform

OS Name	Microsoft Windows 10 Home Version	10.0.19043 Build 19043 Other OS Description 	Not Available OS Manufacturer	Microsoft Corporation System Name	DESKTOP-1O15LR5 System Manufacturer	IT Channel Pty Ltd System Model	P9XXEN_EF_ED System Type	x64-based PC System SKU	Not Applicable Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2208 Mhz, 6 Core(s), 12 Logical Processor(s) BIOS Version/Date	INSYDE Corp. 1.07.02TMB, 22/12/2018 SMBIOS Version	3.0 Embedded Controller Version	7.02 BIOS Mode	UEFI BaseBoard Manufacturer	IT Channel Pty Ltd BaseBoard Product	P9XXEN_EF_ED BaseBoard Version	Not Applicable Platform Role	Mobile Secure Boot State	Off PCR7 Configuration	Elevation Required to View Windows Directory	C:\WINDOWS System Directory	C:\WINDOWS\system32 Boot Device	\Device\HarddiskVolume7 Locale	United States Hardware Abstraction Layer	Version = "10.0.19041.1566" User Name	DESKTOP-1O15LR5\61416 Time Zone	W. Australia Standard Time Installed Physical Memory (RAM)	16.0 GB Total Physical Memory	15.8 GB Available Physical Memory	7.55 GB Total Virtual Memory	40.8 GB Available Virtual Memory	26.0 GB Page File Space	25.0 GB Page File	C:\pagefile.sys Kernel DMA Protection	Off Virtualization-based security	Not enabled Device Encryption Support	Elevation Required to View Hyper-V - VM Monitor Mode Extensions	Yes Hyper-V - Second Level Address Translation Extensions	Yes Hyper-V - Virtualization Enabled in Firmware	Yes Hyper-V - Data Execution Protection	Yes

### Printer

Ender 3

### Reproduction steps

Bug during slicing model
changed outter wall from 0.4 to 0.3
maybe related to using bridge settings at the same time, with 100% skin threshold

### Actual results

Failed with unexpected error

### Expected results

Sliced model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3_New cogs.zip](https://github.com/Ultimaker/Cura/files/8694621/CE3_New.cogs.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/8694624/cura.log)

**Comment by fvrmr** [comment]
Hi @DrKayzed thank you for your report.
I checked internal build and this issue seems to be fixed for 5.0 stable which will be released soon! 
![Capture(363)](https://user-images.githubusercontent.com/77000924/168606117-63840fdd-3ead-4f01-a30c-89f1620c69e2.PNG)
So I will close this issue since it is fixed.
