### ISSUE TITLE
Duplication of objects does not work

### ISSUE THREAD

**Issue by johnReeferVermont** [Ultimaker/Cura#12212]
### Application Version

5

### Platform

Windows 10

### Printer

Ender 5 and Ender 6

### Reproduction steps

Add an object to the plate then select it and duplicate it.  If you select the number of duplications of 1, it does not create one.  It works if you tell it to do two or more.

### Actual results

Does not duplicate the object

### Expected results

I should be able to duplicate an object once.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing more
![2022-05-15_16-25-45](https://user-images.githubusercontent.com/100879478/168492537-951df0d1-188b-4614-be84-ec10005daed9.jpg)

**Comment by GregValiant** [comment]
This has been fixed for the next release.  In the mean time, if you make it "2" and then drop it back to "1" it works as expected.
