### ISSUE TITLE
Unable to locate package cura-extra-plugins

### ISSUE THREAD

**Issue by hulkco** [Ultimaker/Cura#1221]
I try to instal de Cura plugins but i have this error

Unable to locate package cura-extra-plugins

**Comment by thopiekar** [comment]
Ah this is obviously related to my PPA.

Let me see.. Yes, you are right. The package is now called `cura-extra-plugins-all`.
I think I've forgot to update the package name in my instructions after splitting it up into different packages.

**Comment by hulkco** [comment]
Thanks!!!
