### ISSUE TITLE
Ultimaker S5 Pro won't connect via network

### ISSUE THREAD

**Issue by jmccurley-lumco** [Ultimaker/Cura#12217]
### Application Version

5.0 beta +1

### Platform

Windows 10

### Printer

Ultimaker S5 Pro

### Reproduction steps

1. Starting up Cura 5, making sure that previous versions are not open. Also verified that printer was on and not in the middle of a print, if that matters.
2. Import models as normal and select settings
3. Slice
4. Select options for print method

### Actual results

Print via Network is not available.
Manage Printers -> Connect via Network does not find any printers
Closing project and Cura 5.0 and opening Cura 4.13.1 connects to printer via network and can send programs
Closing Cura 4.13.1 and re-opening Cura 5.0, printer is still unavailable for connection

### Expected results

Printer is physically connected and powered on, Print via Network has been the preferred method previously since we save all of our programs and projects locally on our server.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Printer is Ultimaker S5 Pro with material station and air manager; Firmware is version 7.0.3.  Cloud printing works as intended through Cura 5.0

**Comment by fvrmr** [comment]
Hi @jmccurley-lumco thank you for your report.
Do you maybe have a firewall enabled for Cura 5.0?
