### ISSUE TITLE
I can't open file 

### ISSUE THREAD

**Issue by dedmaximded** [Ultimaker/Cura#12239]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1 I tried open file, and have a message that file bad 
2 Then i try open that file with help PerForm slicer , and it open clear
3 I was instal previous version (4.13.1) and open that file clear

### Actual results

Previous version open file, new none 

### Expected results

Open file i new version

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Test.zip](https://github.com/Ultimaker/Cura/files/8716676/Test.zip)

**Comment by fvrmr** [comment]
I created a ticket for this on our backlog, for internal reference see CURA-9321

**Comment by Vandresc** [comment]
This is now fixed for 5.1. If the issue still persists please reopen the ticket.
