### ISSUE TITLE
Preferences Window issues

### ISSUE THREAD

**Issue by idmadj** [Ultimaker/Cura#12233]
### Application Version

5.0.0 beta+1

### Platform

Windows 11

### Printer

-

### Reproduction steps

1. Open **Preferences** > **Configure Cura...**;
2. Click **Settings**;
3. Hover above **Layer Height**.

### Actual results

The blue hovered checkbox is smaller than un-hovered checkboxes.
No help tooltip is displayed as was the case in Cura 4.x

### Expected results

The blue hovered checkbox is the same size as un-hovered checkboxes.
A help tooltip is displayed.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Incorrectly sized hovered checkboxes and missing tooltips in Cura 5:
![cura5](https://user-images.githubusercontent.com/4053575/168890864-44c2edae-55c4-47ca-b014-919b00b269b9.png)

Tooltips in Cura 4:
![cura4](https://user-images.githubusercontent.com/4053575/168889836-a7f875ce-10ce-433a-a23b-defc6d64a9cd.png)

cura.log is also full of these:
```
WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [431]: file:///C:/Program Files/Ultimaker Cura 5.0.0/PyQt6/Qt6/qml/UM/TooltipArea.qml:0: ReferenceError: Tooltip is not defined
```

**Comment by fieldOfView** [comment]
Both the weird checkbox styling and the missing tooltip have been fixed in the final Cura 5.0 release which was published today.

You may close this issue.
