### ISSUE TITLE
Info.plist has incorrect CFBundleShortVersionString value for Macintosh version 5.0

### ISSUE THREAD

**Issue by stevemaser** [Ultimaker/Cura#12246]
### Application Version

5.0

### Platform

macOS 12.4

### Printer

doesn't matter

### Reproduction steps

We downloaded the application and were looking at the info.plist in order to be able to deploy via munki based on the version number, but the Info.plist is showing this;

	<key>CFBundleShortVersionString</key>
	<string>0.0.0</string>

and there is also no <key>CFBundleVersion</key> either.

and the BundleIndentifier string has a .dmg in it, too:

<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura.dmg</string>

### Actual results

we can not do version comparisons with the version of "0.0.0" being reported instead of 5.0.0

### Expected results

ShortVersion String should be 5.0.0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Full Info. plist for 5 looks like this:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDisplayName</key>
<string>Ultimaker-Cura</string>
<key>CFBundleExecutable</key>
<string>Ultimaker-Cura</string>
<key>CFBundleIconFile</key>
<string>cura.icns</string>
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura.dmg</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundleName</key>
<string>Ultimaker-Cura</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleShortVersionString</key>
<string>0.0.0</string>
<key>NSHighResolutionCapable</key>
<true/>
</dict>
</plist>

For 4.13 (what we currently deploy), it looks like this:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleDevelopmentRegion</key>
<string>English</string>
<key>CFBundleDisplayName</key>
<string>Ultimaker Cura</string>
<key>CFBundleDocumentTypes</key>
<array>
<dict>
<key>CFBundleTypeExtensions</key>
<array>
<string>*</string>
</array>
<key>CFBundleTypeName</key>
<string>Model Files</string>
<key>CFBundleTypeRole</key>
<string>Viewer</string>
</dict>
</array>
<key>CFBundleExecutable</key>
<string>cura</string>
<key>CFBundleIconFile</key>
<string>icon.icns</string>
<key>CFBundleIdentifier</key>
<string>nl.ultimaker.cura</string>
<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>
<key>CFBundleName</key>
<string>Ultimaker Cura</string>
<key>CFBundlePackageType</key>
<string>APPL</string>
<key>CFBundleShortVersionString</key>
<string>4.13</string>
<key>CFBundleSignature</key>
<string>????</string>
<key>CFBundleVersion</key>
<string>4.13.1</string>
<key>NSPrincipalClass</key>
<string>NSApplication</string>
</dict>
</plist>

**Comment by Ghostkeeper** [comment]
Fixed for Cura 5.1, by this commit: https://github.com/Ultimaker/Cura/commit/c100f68f58d0c39b9f6b70df32edb2a4b3ca40c6
