### ISSUE TITLE
Support Generation Error on Initial Layer Height

### ISSUE THREAD

**Issue by rvanemon** [Ultimaker/Cura#12245]
### Application Version

5.0

### Platform

Windows 11

### Printer

Craftbot Flow IDEX

### Reproduction steps

1. Used Darft 0.2mm Profile
2. Enable Supports
3. Changed Initial Layer Height from 0.3mm to 0.2mm. (see Actual Results)
4.  If I change the Initial Layer Height back to 0.3mm the supports go back to normal. (see Expected Results)

### Actual results

![image](https://user-images.githubusercontent.com/105809534/169097157-7b711002-5aa5-49b3-becb-94f89206b57b.png)

### Expected results

![image](https://user-images.githubusercontent.com/105809534/169096878-720728cf-ab58-447c-b382-f539408a4df9.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CFFFP_hinge_main 0.2mm Support NOK.zip](https://github.com/Ultimaker/Cura/files/8718594/CFFFP_hinge_main.0.2mm.Support.NOK.zip)
[CFFFP_hinge_main 0.3mm Support OK.zip](https://github.com/Ultimaker/Cura/files/8718596/CFFFP_hinge_main.0.3mm.Support.OK.zip)

**Comment by fvrmr** [comment]
Hi @rvanemon thank you for your report.
If you disable `Use towers` it will also show your expected result:
![Capture(365)](https://user-images.githubusercontent.com/77000924/169287799-178cad01-c952-419d-bc58-665a11652f95.PNG)
I will close this issue, but feel free to reach out.
