### ISSUE TITLE
Mr Ian Davys

### ISSUE THREAD

**Issue by iandavys** [Ultimaker/Cura#12247]
### Application Version

5.0.0

### Platform

windows 11

### Printer

Flsun Q5

### Reproduction steps

I
![Screenshot 2022-05-18 205316](https://user-images.githubusercontent.com/105819713/169144796-8d4a2e78-3c5d-4b80-94f5-776cee6d929a.jpg)
[Cura failed project.zip](https://github.com/Ultimaker/Cura/files/8720469/Cura.failed.project.zip)

### Actual results

I gave up and i loaded my Cura from flsun 1.4.15 (that came with the Q5) yep it worked and now all is good.
it would be very intresting to find out why the new Cura never worked.
Hope you can help.

thanks from Ian

iandavys@vivaldi.net

### Expected results

It working and slicing my small project for someone.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Sorry think the photo should of gone in this space!

Thanks.

from Ian
![Screenshot 2022-05-18 205316](https://user-images.githubusercontent.com/105819713/169146907-44a9d5b0-9a95-4bb5-92d4-a599042187d6.jpg)

**Comment by GregValiant** [comment]
I'm not sure what happened.  I changed to the "Draft" profile, discarded all the changes, and then switched back to the "Extra Fast" profile and it sliced.
This problem with 5.0 has been noted before.

**Comment by Vandresc** [comment]
Thank you, @iandavys. I will bring this up with the team. We indeed have some cases where the slicing still fails.

**Comment by Vandresc** [comment]
Devs see CURA-9345 for our internal reference.
