### ISSUE TITLE
Barra horizontal en vista previa (NO SALE )

### ISSUE THREAD

**Issue by juanmomos** [Ultimaker/Cura#12250]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

artillery

### Reproduction steps

![image](https://user-images.githubusercontent.com/48109404/169202216-5a05e7ca-5465-4484-b15e-4f9ecf5431cd.png)
la barra horizontal no me apare, ya reinstale y actualice y nada.

### Actual results

no aparece la barra 

### Expected results

deberia de aparecer la barra 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/48109404/169202461-19868ca8-d0f9-45d3-80a4-d96e795b8ef2.png)

**Comment by fvrmr** [comment]
Hi @juanmomos thank you for your report.
This is happening because you are in compatibility mode, this could be enabled in the configurations or your GPU doesn't support OpenGL 4.1
See also https://github.com/Ultimaker/Cura/issues/11510, I will close this issue since it is a duplicate.
