### ISSUE TITLE
takes forever to slice or doesnt slice at all.

### ISSUE THREAD

**Issue by MrMalarkey** [Ultimaker/Cura#12252]
### Application Version

5.0

### Platform

windows 11 home

### Printer

flsun SR

### Reproduction steps

unable to process slice when multiple pieces are on bed. beta ran flawlessly. 5.0 launch is literally useless for me now since i dont ever print 1 at a time. 

### Actual results

nothing.

### Expected results

functional slicing capabilities....

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

no

**Comment by fvrmr** [comment]
Hi @MrMalarkey thank you for your report.
Could you add your project file (file - save project) and log file and share this here as a .zip on GitHub?
You could find your log file here: `C:\Users\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
