### ISSUE TITLE
Cura 5.0.0 does not show Raft Print Acceleration and Jerk settings after they are enabled

### ISSUE THREAD

**Issue by JasonFIN** [Ultimaker/Cura#12259]
### Application Version

5.0.0

### Platform

Windows 19

### Printer

Creality Ender 3 V2

### Reproduction steps

1. Open model in Cura
2. Select hamburger menu from Print settings and select "All" for Settings visibility.
3. Scroll down to "Build Plate Adhesion" section in Print settings and notice that Raft Print Acceleration or Jerk settings are not shown.
4. Click the Sliders icon to the right from "Build Plate Adhesion" title and check that the "Raft Print Acceleration" and "Raft Print Jerk" settings are selected.
5. Notice that even toggling the "Raft Print Acceleration" and "Raft Print Jerk" setting on and off does not make these settings visible in the Print settings.

![image](https://user-images.githubusercontent.com/26737409/169359255-18877ff9-d521-4601-b6d2-076d47065590.png)

### Actual results

Raft Print Acceleration and Jerk settings are not shown in the Print settings.

### Expected results

Raft Print Acceleration and Jerk settings would be shown in the Print settings.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

That's all folks!

**Comment by Vandresc** [comment]
Thank you, @JasonFIN. I will bring this up with the rest of the team.

**Comment by Vandresc** [comment]
Hi @JasonFIN , though I could indeed reproduce it in 5.0 it is not an issue anymore in the master build., meaning this is fixed already for the next release. Thank you for bringing this up!
