### ISSUE TITLE
Configuration Errors 

### ISSUE THREAD

**Issue by Jarren141** [Ultimaker/Cura#12261]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Start Cura 5.0.0
See configuration error popup
Hit blue reset button
Confirmation popup appears
Select yes on confirmation popup
Confirmation popup closes
Nothing happens
Close and reopen Cura and repeat above steps

### Actual results

Cura stays open
Corrupt configs are not reset

### Expected results

Cura closes
Corrupt configs are reset/removed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/69659296/169360690-f5e54557-b833-46eb-9f26-14a4a664bbc2.png)

**Comment by AceTanner** [comment]
I have the same bug and posted it 12hours ago and the printer time is adding 4+ hours to the prints

**Comment by Vandresc** [comment]
Thank you, @Jarren141, I saw we already have a ticket and planned to be fixed for the next release. Devs see CURA-9334 for our internal reference.

**Comment by Vandresc** [comment]
This is now fixed for the next release.
