### ISSUE TITLE
cannot change object position using 'Move' UI

### ISSUE THREAD

**Issue by mikosik** [Ultimaker/Cura#1227]
It is not possible to change object position using Move UI ...

![move_object_ui](https://cloud.githubusercontent.com/assets/4783806/21001916/586b208a-bd23-11e6-899e-9ebf7fe23d3a.png)

.. if object position has been changed by dragging object using mouse/touchpad.
Move UI works correctly when object has been just loaded from stl file and have been only clicked once to bring 'Move' UI.

Reproduced in cura 2.3.1 on Linux Mint 18.

**Comment by Ghostkeeper** [comment]
Can't reproduce this in version 2.4 (master).

Note that you have to press enter or remove the focus from the text box before the move gets applied. Otherwise we'd have to update the position while typing, which gets annoying with large models.

**Comment by mikosik** [comment]
@Ghostkeeper I confirm that it works correctly with cura 2.4.0 for linux official release.
