### ISSUE TITLE
Application crash and print stops

### ISSUE THREAD

**Issue by Lord-ET** [Ultimaker/Cura#12277]
### Application Version

5.0.0-beta+1

### Platform

Windows10x64

### Printer

Creality Ender3Pro

### Reproduction steps

Any time I try to print via USB.

### Actual results

The print will start, but after 5 minutes or so the application generates a full taskbar worth of application icons, the print stops, and I get an application has crashed message.

### Expected results

The file should print and the monitor tab should show the progress
[cura.log](https://github.com/Ultimaker/Cura/files/8740658/cura.log)
[self_siphon.zip](https://github.com/Ultimaker/Cura/files/8740663/self_siphon.zip)
.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

If I slice and then save to removable disk the print works and the part is made.

**Comment by nallath** [comment]
This is fixed for the 5.0.0 release
