### ISSUE TITLE
"No profiles matching configuration of this extruder"

### ISSUE THREAD

**Issue by uenz** [Ultimaker/Cura#12271]
### Application Version

5.0.0

### Platform

MacOs Monterey 12.3.1

### Printer

Ultimaker 2+

### Reproduction steps

Installed Extruder PETG definitions from Marketplace:
https://marketplace.ultimaker.com/app/cura/materials/extrudr/Extrudr_PETG
Selected as material from material dropdown in CURA.

### Actual results

There's now a yellow triangle by the material dropdown. Hovering over it shows "There are no profiles matching the configuration of this extruder". 
Under Manage Materials als seems to be ok, no way to get rid of the warning there.

### Expected results

Materials should be completely independent of the extruder except for maybe the Diameter. Of course, the filament has to fit the nozzle.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing else to add. Thanks for checking into this.

**Comment by nallath** [comment]
This profile only contains settings for the Ultimaker S5, which you can see on the marketplace page.
