### ISSUE TITLE
Multiply Selected in Cura 5.0.0 Beta + 1

### ISSUE THREAD

**Issue by glsolomon** [Ultimaker/Cura#12288]
### Application Version

5.0.0 Beta + 1

### Platform

Windows 11

### Printer

FLSUN SR

### Reproduction steps

1. Highlighted a model on the bed
2. Right Clicked the model
3. Chose "Multiply Selected"
4. Left the default at "1"
5. Left Clicked the "OK"
6. Then right clicked model again
7. Chose "Multiply Selected"
8. Selected "2"
9. Left Clicked "OK"
10. 

### Actual results

When selected Multiply Selected "1"
Nothing happens.
When selected Multiply Selected "2"
You get three models on the bed

### Expected results

I expected that when I choose "Multiply Selected" and then choose "1" that I would end up with two models on the bed as  this is what happens in Cura 4.x
I expected that when I choose "Multiply Selected" and then choose "2" that there would now be three models on the bed which is indeed what happened.

Mind you I find this confusing. I would have said that in "Multiply Selected" "0 & 1" would not be an option.
When you selected "2" then the number of models on the bed would double the selected model(s).
When you selected "3" then the number of models on the bed would be three times the selected model(s)
etc

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This is a Screen capture video of the behaviour of the "Multiply Selected"
https://user-images.githubusercontent.com/81938585/169634933-d6a6f466-99b3-4bf9-a55c-8ddca472ffe1.mp4

**Comment by Asterchades** [comment]
Multiply when using the default 1 not producing results has already been fixed in the 5.0 release. You should update to that from the beta anyway as there were a lot of other fixes added at the same time - not just this one.
