### ISSUE TITLE
Cura 5 keeps crashing

### ISSUE THREAD

**Issue by rich-jamison** [Ultimaker/Cura#12298]
### Application Version

5.0.0-beta+1

### Platform

Windows 10

### Printer

Anycubic Mega Pro

### Reproduction steps

Started a print and it went fine for about 5 to 8 minutes.  Then all of a sudden, a bunch of crash report windows popup, one after the other in rapid succession.  The print head stops, the popups stay for a few seconds (with blank, white backgrounds) then the program and all windows close. 

I have tried this several times on the same print and a different one with the same results.  I re-booted the program and my computer in between prints each time and still get the same result.

### Actual results

program crashes and my printer locks up

### Expected results

I expected the print to complete without stopping 5-8 minutes in.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

don't know where to get any logs from

**Comment by Vandresc** [comment]
Hi @rich-jamison , thank you for your feedback? Is the issue still present in the 5.0 stable version? And if so could you please share your logs with us? Thank you!
