### ISSUE TITLE
Cura 15.06.01: Layer view missing visualisation of top layers if concentric pattern is selected

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#123]
Steps to Reproduce
1. have a simple cube in cura
2. enable top/bottom pattern in the machine settings.
3. set the top/bottom pattern to concentric
4. enable layers view
Result:
![screen shot 2015-07-08 at 15 58 40](https://cloud.githubusercontent.com/assets/759145/8572113/d672d6c6-258a-11e5-964e-4dde0c340053.png)
 expected result:
something like 
![screen shot 2015-07-08 at 15 58 57](https://cloud.githubusercontent.com/assets/759145/8572125/e317975e-258a-11e5-846d-ce41ee09e579.png)

**Comment by nickthetait** [comment]
I may be wrong, but concentric might deliberately disable the top surface. So it would be expected that you would not see/print that part.

**Comment by Spirou42** [comment]
I have exported the GCode and rendered it with Repetier-Host. The top and bottom layers are complete, including a nice concentric pattern.
![screen shot 2015-07-08 at 17 18 04](https://cloud.githubusercontent.com/assets/759145/8574161/8fbe4d18-2595-11e5-9d53-3ee39fb44bed.png)
![screen shot 2015-07-08 at 17 11 02](https://cloud.githubusercontent.com/assets/759145/8574164/9712981c-2595-11e5-8a47-06fc5d41fed1.png)

**Comment by nickthetait** [comment]
I was definitely wrong! That's what I get for trying to help :disappointed:

**Comment by nallath** [comment]
I didn't even knew we had a concentric pattern :$

**Comment by luisonoff** [comment]
I confirm this is also happening to me. With concentric pattern chosen, no top layers show up on layer view.

**Comment by nallath** [comment]
Is this still an issue with 15.06.02?

**Comment by Xisle** [comment]
Yes.

![screen shot 2015-07-22 at 11 05 36 pm](https://cloud.githubusercontent.com/assets/12257213/8844925/ccc56b38-30c6-11e5-927b-142f5759aa12.png)

**Comment by Xisle** [comment]
No top or bottom.

![screen shot 2015-07-22 at 11 14 23 pm](https://cloud.githubusercontent.com/assets/12257213/8844997/6b932584-30c7-11e5-88e2-b2195b20edb7.png)

**Comment by BagelOrb** [comment]
Visualizing the concentric pattern should be fairly easy.

However, visualizing ZigZag infill will probably be harder.

**Comment by nallath** [comment]
Currently no skin is rendered, it seems like it's not correctly sent by the engine.

**Comment by BagelOrb** [comment]
This should be fixed for the next release.
I now do get skin visualization for any pattern.
