### ISSUE TITLE
Filament usage per layer. 

### ISSUE THREAD

**Issue by Mightywiz** [Ultimaker/Cura#12301]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

On the preview screen I’d like to see a running total of filament used per layer.   Example:  I have a 30 layer project and I want to perform a color swap at layer 11 & 21.  It would be nice to have a tally on the preview screen when I’m using the height slider to see how much filament I’ve used to build the first 10 layer.   And again at layer 21.  I could do the math and minus the amount from the first 10 layers.    So I can verify I have enough filament on some of my almost empty rolls.  And I could create some pre sliced rolls for some projects.   

### Describe alternatives you've considered

Buying a mosaic palette 3 to do it for me.  Too much money.   I could just pause the project and perform the swap.  Too time consuming to babysit the project to do a color swap.  And who wants to try to wake up a 3am to do a swap when I could pre build a roll.   

### Affected users and/or printers

All users wanting to play with color swapping.

**Comment by nallath** [comment]
Unfortunately we have too many feature requests for us to work on. As this is not a feature that we feel is valuable enough, it's not something that we will work on.

If someone would develop this feature, we would obviously welcome any pull request.
