### ISSUE TITLE
Random change of print direction

### ISSUE THREAD

**Issue by danoveb** [Ultimaker/Cura#12304]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Formbot Raptor (Custom)

### Reproduction steps

1. Sliced a simple cube to test variable line width. Different thickness on the walls

 

### Actual results

Was looking at the actual print and saw that it suddenly changed print direction on some random layers. This produced some unwanted artifacts (not on all layers though), and I cannot see whats the meaning of it. This happened on layer 9,23,24,26,27 and some more. Tried to find in the settings something about it but with no success. Is this a bug or a feature?

### Expected results

Slice the attached files and you can also see the changed direction in the preview.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_Wallthickness.zip](https://github.com/Ultimaker/Cura/files/8749009/CFFFP_Wallthickness.zip)

**Comment by Vandresc** [comment]
Hi @danoveb , unfortunately, the project file you shared is just a plain 3mf file, could you please re-attached a project file again?  Thank you!
