### ISSUE TITLE
Cut / Paste text in the Machine Settings dialogue box

### ISSUE THREAD

**Issue by reynol3232** [Ultimaker/Cura#12305]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Artilery X1

### Reproduction steps

Tried to select text then cut and paste the Machine Settings Start Up GCode from another printer using Cura 5.0.0.  Previous version of Cura allowed this.  I only tried the Machine Setting dialogue box but I would guess all of the dialogue boxes have this same issue

### Actual results

Not allowed to highlight text then cut and paste.

### Expected results

Previous version allow cut and paste function

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot 2022-05-22 080826](https://user-images.githubusercontent.com/71512626/169694459-2ddd3fa9-fc1d-451d-806f-d7abf8fbc8e5.jpg)

**Comment by nallath** [comment]
This is fixed for the 5.1 release.
