### ISSUE TITLE
camera view does not take window size into account

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#12310]
### Application Version

5.0.0

### Platform

macOS Monterey

### Printer

Ultimaker 3

### Reproduction steps

open the camera view in the monitor section 
resize the window

### Actual results

the camera view is not integrated into the windows layout.

### Expected results

the camera view stays in the relative layout of the window.

https://user-images.githubusercontent.com/759145/169699349-4e1a47a7-d064-4d58-aa6c-152a06a82819.mov

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://user-images.githubusercontent.com/759145/169699400-184315d4-db87-4ab5-82f3-396d5690d3cc.mov

**Comment by Vandresc** [comment]
Hi @Spirou42 , thank you for your feedback! The resizing never actually worked, was not implemented. If you wish to resize it, you can visit the api in the browser http://[IPadress]:8080/?action=stream and resize it from there, but indeed the camera view doesn't take the window size into account. 
Of course, you can always create a feature request, or being an open source, PR's are also very welcome.
