### ISSUE TITLE
Not able to slice if .gcode file is view then clear build plate

### ISSUE THREAD

**Issue by Schmitty4311** [Ultimaker/Cura#12311]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

CR10v3

### Reproduction steps

1. Opened Cura 5.0.0 official release
2. Imported (drag & drop) .gcode file to preview time, material consumption, and model preview. FYI The file was previously sliced on Cura 4.13.0.
![image](https://user-images.githubusercontent.com/81663036/169701349-4b51dcd7-d524-4dec-a058-9b96a2e9923c.png)
![image](https://user-images.githubusercontent.com/81663036/169701358-89f379ab-3456-4309-88c4-299192e91d0e.png)
![image](https://user-images.githubusercontent.com/81663036/169701374-39942d1d-e848-475a-8d81-6578fc083f08.png)
3. Cleared build plate
4. Imported .stl file for print setting and slicing and ran into the issue of not being able to adjust settings and slice.
![image](https://user-images.githubusercontent.com/81663036/169701446-c807443d-cb6c-4ea1-b257-99f9eb109aa4.png)
5. In order for it to work properly again to slice. Must exit/shutdown Cura 5.0.0 and restart to be able to adjust settings and slice any .stl files.

### Actual results

Not able to slice if .gcode file is imported to slicer prior to .stl file. Must exit Cura and restart to be able to adjust settings, modify, or slice any .stl files.

**Note** This does not happen if any .stl file is imported prior to .gcode file, then the sequence of events is followed. It only happens when the Cura is opened then first action is to import .gcode file.

### Expected results

After build plate cleared when the .gcode file was viewed, then imported .stl file, It should have let the program adjust settings, modify model, and slice fir printing. This could not occur until after the program had been shutdown and restarted, then import the .stl file.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additonal information at this time.

**Comment by Vandresc** [comment]
Hi @Schmitty4311 , first of all, I want to thank you for the detailed and very clear filled-in bug template! 
Unfortunately, I cannot reproduce the issue described by you, after importing the stl after the gcode I can adjust all settings and slice. 
Could you please share your logs with us as well? Thank you!
