### ISSUE TITLE
Crash due to Randomize Infill Start without infill lines

### ISSUE THREAD

**Issue by hendriksen-mark** [Ultimaker/Cura#12312]
### Application Version

5.0.0

### Platform

MacOs Monterey 12.3.1

### Printer

cr-x pro

### Reproduction steps

1. add a stl
2. rotate
3. multiply selected
4. mirror 1
5. arrange all models
6. press slice

### Actual results

error:
Slicing failed with an unexpected error.

### Expected results

cura should finish slicing with no error.
cura 4.13.1 works fine

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8749666/cura.log)
<img width="1792" alt="Schermafbeelding 2022-05-22 om 16 53 11" src="https://user-images.githubusercontent.com/16277488/169701815-251c5089-7046-470a-b90d-f627cc65ff72.png">
[test.zip](https://github.com/Ultimaker/Cura/files/8749682/test.zip)

cura log and file that make the error

**Comment by GT-Geo** [comment]
I'm using MacOs Monterey 12.3 and the latest Cura V5.0.0 and it sliced without errors for me.
<img width="1783" alt="Screen Shot 2022-05-22 at 7 03 58 PM" src="https://user-images.githubusercontent.com/104281051/169719910-280567f5-cdca-4c3a-88bf-bd26fc17ad80.png">
.

**Comment by nallath** [comment]
It does reproduce for me on Ubuntu 21 with 5.0.0.

Thanks for reporting this. I will discuss this with the other developers!

**Comment by Ghostkeeper** [comment]
This occurs when Randomize Infill Start is enabled, but when there are layers without any infill lines (e.g. concentric, or just small infill parts).
