### ISSUE TITLE
Cura 5.0 Dual Extruder Settings Crash

### ISSUE THREAD

**Issue by sjbaird** [Ultimaker/Cura#12316]
### Application Version

5.0

### Platform

Windows 10

### Printer

Tevo Trantula

### Reproduction steps

Have two extruders defined and make a change like nozzle diameter. Close Machine settings and Preferences windows and allow auto slicing to occur. Then click settings menu option.

### Actual results

Duplicated extruder options, the first time was about 4 duplicates.
Once the mouse hovers above a selection the program crashes and all work is lost.

![image](https://user-images.githubusercontent.com/28546600/169708991-298d3416-3c20-4366-8d0b-d7fba9d48a9d.png)

### Expected results

Not to crash

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/28546600/169709128-a4150891-b922-4c85-b26d-d09633b1e244.png)

**Comment by nallath** [comment]
Are you very sure that you're using 5.0.0 and not the 5.0 beta? This was an issue with the Beta, but has been fixed for the final 5.0 release. 

I've just re-tested this in the final 5.0.0 release and the issue doesn't happen there.

**Comment by sjbaird** [comment]
Yep was beta, I hadn't realized 5 was released yet.
