### ISSUE TITLE
Tower position when center=0,0 (bug?) Cura 2.3.1 and 2.4beta

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#1232]
I set center as 0,0
1 Shadow of tower does not know about it at all  and displayed as if center at  0,0 = false
2 Cura accepts only positive values as tower position. So I can place the tower only right far corner of the bed.

**Comment by Ghostkeeper** [comment]
Probably the prime locations as well, then.

**Comment by karabas** [comment]
The same in 2.4 beta. Tower placement  for delta is very limited due to this bug.
![2017-01-11_18-01-49](https://cloud.githubusercontent.com/assets/67457/21853613/e9290c16-d828-11e6-911c-e2c0ce234377.png)

**Comment by fieldOfView** [comment]
As it says in the 2.4 release notes, delta support is largely untested, because none of the Cura regulars have any deltas around. So we rely on reports like this to get things fixed. Thanks @karabas!
