### ISSUE TITLE
Cura 5.0 z not increasing if scale object

### ISSUE THREAD

**Issue by andreac** [Ultimaker/Cura#12328]
### Application Version

5

### Platform

ubuntu

### Printer

qidi xplus

### Reproduction steps

1. import object
2. scale 80%
3. slice
4. print
5. after feaw layer z not increase and print fail

### Actual results

printer stop increasing z if object scaled

### Expected results

z should be increased

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[arch_scale80.zip](https://github.com/Ultimaker/Cura/files/8755991/arch_scale80.zip)

**Comment by nallath** [comment]
Cura doesn't add any different g-code due to scale. This isn't a bug with Cura but with your printer.
