### ISSUE TITLE
Octoprint error message not closable

### ISSUE THREAD

**Issue by kylane** [Ultimaker/Cura#12325]
### Application Version

5.0.0-beta1

### Platform

Win11

### Printer

Ender 3

### Reproduction steps

Opening Cura without turning on my octoprint first shows an error on load that I cant close until I start octoprint.

![image](https://user-images.githubusercontent.com/8296041/169783650-d102fc0b-a660-47b4-9fc8-a481cd3093b1.png)

### Actual results

Cura error opens offscreen making it impossible to dismiss.

### Expected results

Popover panel should still be closable - perhaps scroll the contents within?

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

NO need - easily reproducable.

**Comment by fieldOfView** [comment]
Issues with the OctoPrint Connection plugin should go here:
https://github.com/fieldofview/Cura-OctoPrintPlugin/issues

One could argue that Cura should handle messages that are too long in a better way.

**Comment by fieldOfView** [comment]
Note that you are using a beta version of Cura 5, and the full release has been out for a while now. Please update.

**Comment by nallath** [comment]
> One could argue that Cura should handle messages that are too long in a better way.

I figured that was also what this bug was about.

**Comment by MariMakes** [comment]
Quick update, 
We discussed it with the team and see value in making long messages scrollable so they can be closed, but we totally forgot to update this issue. 

For internal reference CURA-9374

Thanks for the report! 👍

**Comment by MariMakes** [comment]
Hey @kylane,

Quick update from our side 👋

Our new developer @wawanbreton was able to resolve your issue here: https://github.com/Ultimaker/Cura/pull/16509
Long messages now have a scroll bar. ![image](https://github.com/Ultimaker/Cura/assets/40423138/3be61b11-7bff-4429-99f1-73b72ceff8fc)

I'll be closing this issue and you will see the fix in the upcoming release.

**Comment by kylane** [comment]
> Hey @kylane,
> 
> Quick update from our side 👋
> 
> Our new developer @wawanbreton was able to resolve your issue here: #16509 Long messages now have a scroll bar. ![image](https://user-images.githubusercontent.com/40423138/263287681-3be61b11-7bff-4429-99f1-73b72ceff8fc.png)
> 
> I'll be closing this issue and you will see the fix in the upcoming release.

Awesome work!
