### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by cpu012** [Ultimaker/Cura#12352]
### Application Version

4.13.1

### Platform

Arch Linux

### Printer

Creality Ender 3 Pro

### Reproduction steps

I imported a stl file.

quality: dynamic quality
infill density: 20%
infill pattern: cross
speed: 80 mm/s
generate support: true
build plate adhesion: raft
everything else: default

### Actual results

cura failed to slice

### Expected results

cura should have sliced succesfully

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8774137/cura.log)
[project.zip](https://github.com/Ultimaker/Cura/files/8774155/project.zip)

**Comment by Ghostkeeper** [comment]
Seems to slice correctly in Cura 5.0.

![image](https://user-images.githubusercontent.com/2448634/171401472-d9b02453-43d1-4bc6-8341-8c23b9fe7dc9.png)

Could you update Cura and try again?

You didn't provide a project file so I reconstructed the print from your instructions. Providing a project file (File -> Save...) would make it easier to ensure that we're actually using identical settings and model placement and everything.
