### ISSUE TITLE
Automatische Objekt skalierung auf 10000%

### ISSUE THREAD

**Issue by powerlotus** [Ultimaker/Cura#12357]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Eder 3 V2

### Reproduction steps

Beim Einfügen der Dateien wird eine automatische skalierung des Objektes auf 10000% vorgenommen (das auf jeden Fall besagt das Hinweisfenster das aufgeht, siehe Anhang). Diese Datei kann ich so oft ich will einfügen, es wird immer auf 10000% skaliert. 
Wenn ich auf : Scale ("S"), Button drücke, zeigt es mir bei diesem Beispiel 2540% an.  

Ich kann die gleiche Datei in Cura 4.2.1 einfügen und es wird 1:1 eingefügt.

Es kommt auch öfter vor, dass die Datei zB auf Z: -500mm eingefügt wird

Es passiert nicht bei allen Dateien. Bisher habe ich noch kein Muster herausgefunden, was an den Dateien die grösser skaliert werden anders ist. 

![10000%](https://user-images.githubusercontent.com/23580292/170450276-cc07b3cd-bfcb-479c-8b68-2c1f4b22af0e.jpg)

### Actual results

Die Datei ist so nicht zu gebrauchen. Auch wenn ich beim Scale Button 100% eingebe, entspricht das noch lange nicht der Grösse die das Objekt haben sollte. Es ist immer noch zu gross. Es sieht so aus, dass manchmal auch nicht alle Elemente des Objektes betroffen sind und einige nicht mit dem gleichen Faktor multipliziert werden. 
![nach 100% Skalierung](https://user-images.githubusercontent.com/23580292/170455816-ad841d92-de16-4946-8a8b-c0f401c8ecb5.jpg)

### Expected results

Die Datei ist nicht zu gebrauchen

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Keine weiteren Angaben

**Comment by nallath** [comment]
My German is rusty at best, so I can't really help you here. 

In order to debug this, I do at the very least need a model that reproduces the issue.
