### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by iambatkam** [Ultimaker/Cura#12354]
### Application Version

5.0

### Platform

Windows 11

### Printer

Anycubic i3 Mega

### Reproduction steps

1. I loaded the model
2. Clicked "Slice"

### Actual results

Get an error:

> Slicing failed
>> Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker

![sliceError](https://user-images.githubusercontent.com/102985687/170377889-4c63cd18-fd2b-40b9-afa4-e4dd826b541d.jpg)
.

### Expected results

A sliced .gcode file

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Uploading AI3M_Giant_bird_skele_cauldron_Project_File.zip…]()

**Comment by nallath** [comment]
Something went wrong with uploading the file. Could you try again?
