### ISSUE TITLE
Cura 5 Error Slicing Model

### ISSUE THREAD

**Issue by rczook** [Ultimaker/Cura#12350]
### Application Version

5.0.0

### Platform

Windows 10 Pro

### Printer

Ender 3 Pro

### Reproduction steps

1.  Loaded model
2.  Changed Z scale to 500%
3.  Moved model down 13mm in the Z direction
4. Clicked "Slice"

### Actual results

Get an error stating "Slicing failed:  Slicing failed with an unexpected error.  Please consider reporting a bug on our issue tracker."  Model works fine in Cura 4.13.1.

![Cura5SlicingError](https://user-images.githubusercontent.com/106252628/170273251-36731ae9-db42-42cb-a1a5-ea43f0967a33.png)

### Expected results

Model should slice and let me print.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This model slices fine in Cura 4.13.1.  Cura 5.0.0 seems to take quite a bit longer to open than Cura 4.13.1 does and takes longer to slice as well

[cura.log](https://github.com/Ultimaker/Cura/files/8771573/cura.log)
[Uploading SouthDakota_Z500_Z-13mm.zip…]()
.

**Comment by GregValiant** [comment]
Can you re-try zipping and posting a Project File?

**Comment by rczook** [comment]
[SouthDakota_Z500_Z-13mm.zip](https://github.com/Ultimaker/Cura/files/8786881/SouthDakota_Z500_Z-13mm.zip)

**Comment by GregValiant** [comment]
It looks like there is something wrong with that "Dynamic" quality setting.

If you change to "Standard" quality and make the layer height .16 (like the Dynamic quality) then it slices.

**Comment by Ghostkeeper** [comment]
The model slices correctly for me in the Cura 5.0 release as well as in the current main branch.

![image](https://user-images.githubusercontent.com/2448634/171404555-876fe5d1-0517-4313-be26-411df884da66.png)
