### ISSUE TITLE
Error of slicing

### ISSUE THREAD

**Issue by Carlitoos95** [Ultimaker/Cura#12364]
### Application Version

4.13.1

### Platform

windows 10

### Printer

creality ender 3

### Reproduction steps

hello 
i want to make some pieces and i import some stl o similar formats and all okey but when i click the segmentation button 
![Captura de pantalla (1)](https://user-images.githubusercontent.com/106347852/170564016-052094d5-2f7c-4d0e-9d6f-eb221dcc5eb8.png)
.

### Actual results

after that i go see preview to check everything is all right and there is some missing parts of the piece
![Captura de pantalla (2)](https://user-images.githubusercontent.com/106347852/170564075-32a8c05e-33f6-43ac-a6fa-ff266a2d66d0.png)
 

### Expected results

i wanted to finalise the process because with this issue i cant make my pieces , if you wanna know i use SketchUp and i export it in STL formats but i tried in other formats and i can´t reach what i want. 

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

if it is my own error because im new please write me an email to kranoox@gmail.com showing me the option to fix this .
im gonna try with 5.0 too i write here later::: 
in 5.0 doesn´t work well too

**Comment by GregValiant** [comment]
It looks to be a problem with the model, or that flange is too thin to slice.
You can try using MS 3D Builder to repair the model.  SketchUp often has reversed surfaces and open seams that won't allow parts to slice or that slice in error.

**Comment by Carlitoos95** [comment]
i tried with that my guy 
but no result i´ll try with other CADs...
