### ISSUE TITLE
4.13.1 Profile With Internal Threads Result In Excess Striging When Sliced With 5.0.0 

### ISSUE THREAD

**Issue by reynol3232** [Ultimaker/Cura#12367]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Artillery X1

### Reproduction steps

I've made several hundred prints from a profile originally sliced in 4.13.1. The print has large internal ACME threads.  When I slice the same print in Cura 5.0.0 using the profile from from 4.13.1 the threads show a lot of stringing.  Photo #1 is the printed model sliced in Cura 5.0.0 and Photo #2 is the same printed model using 4.13.1.  All of the setting were identical between 5.0.0 and 4.13.1.  

### Actual results

Threads will fail to print when sliced in 5.0.0

### Expected results

A profile from 4.13.1 should print when sliced in 5.0.0.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Attached photos of prints that were sliced with identical settings in 4.13.1 and 5.0.0.  Cura 5.0.0 is having trouble printing overhangs
![Photo #2 Success](https://user-images.githubusercontent.com/71512626/170616725-d0f7f692-af58-414e-8603-6658209dc679.jpg)
![Photo #1 Failure](https://user-images.githubusercontent.com/71512626/170616727-e5ac69bf-2195-4abf-8fd0-b8f0dbbc313f.jpg)
.

**Comment by GregValiant** [comment]
There are new settings in 5.0 that had no equivalents in 4.13.  They need to be adjusted.
One that may apply here is "Wall Order".  The default is "Outside to Inside" which on overhangs isn't good.  Try changing it to "Inside to Outside" and do a test.

**Comment by reynol3232** [comment]
You are correct!  The default setting in Cura 5.0.0 is opposite of what the setting is in Cura 4.13.1.  That is really bad.  When installing 5.0.0 it should have looked for the setting "Outer Before Inner Walls" from 4.13.1 and copied that setting to the new named "Wall Order" in 5.0.0.  This will indeed frustrate a few people.   I will try another print and see if that corrects the issue.
