### ISSUE TITLE
support wall prints at double speed

### ISSUE THREAD

**Issue by exec79** [Ultimaker/Cura#12369]
### Application Version

5 beta

### Platform

Windows 10

### Printer

voron 2.2

### Reproduction steps

setup support to 140mms.

### Actual results

it prints support at 280mms.  (feedrate at 100%, checked)

### Expected results

support prints at 140mms

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![support1](https://user-images.githubusercontent.com/20884744/170684937-b6397d9a-1600-4f75-a859-ee17c9757947.png)
[CFFFP_Fach_mittelarmlehne_Focus3.zip](https://github.com/Ultimaker/Cura/files/8786071/CFFFP_Fach_mittelarmlehne_Focus3.zip)

**Comment by GregValiant** [comment]
In the Speed section set the "Flow Equalization Ratio" to 0%.
It looks like it's being affected by "Gradual Support Infill Steps".  With the Flow Equalization at 100% and Gradual Steps at 3 then yes, it wants to print the support infill at 2X speed.  With either setting at "0" it doesn't happen.

I don't know what the intent was behind the Flow Equalization setting, but there may be issues with the implementation.

**Comment by exec79** [comment]
> In the Speed section set the "Flow Equalization Ratio" to 0%. It looks like it's being affected by "Gradual Support Infill Steps". With the Flow Equalization at 100% and Gradual Steps at 3 then yes, it wants to print the support infill at 2X speed. With either setting at "0" it doesn't happen.
> 
> I don't know what the intent was behind the Flow Equalization setting, but there may be issues with the implementation.

thank you, thats it.
