### ISSUE TITLE
Print setting information window scroll is inaccessible

### ISSUE THREAD

**Issue by Teddy-1024** [Ultimaker/Cura#12377]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

The information windows that appear when I hover over the print setting labels in the print settings window sometimes contain too much text to fit and have scroll bars, but when moving the mouse over to the information window, it disappears. Using the mouse scroll-wheel scrolls the print settings window and the arrow keys have no effect.

### Actual results

The information window disappears.

### Expected results

It would be helpful if the text in the information window could be viewed.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2022-05-28 (6)](https://user-images.githubusercontent.com/39016164/170832130-fa39fc0e-69ec-41e6-a82a-3111a8a66bf6.png)
![2022-05-28 (7)](https://user-images.githubusercontent.com/39016164/170832131-182cc66c-248a-47bf-9d9a-2a304085b3b1.png)

**Comment by nallath** [comment]
This has been fixed in the final release of Cura 5.0. You are still using the Beta.

**Comment by Teddy-1024** [comment]
Awesome. Thank you very much for your help!
