### ISSUE TITLE
BSOD AMD Ryzen paired with ASUS MoBo 

### ISSUE THREAD

**Issue by BulletDropplay** [Ultimaker/Cura#12375]
### Application Version

5,0

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

just leave cura running for more than 15 min
have an asus motherboard and a ryzen cpu

### Actual results

Black Screen Of Death PC restarts 

### Expected results

Id expect after having this issue on 2 separate machines with 2 different generation's of hardware to be fixe
[cura.log](https://github.com/Ultimaker/Cura/files/8791211/cura.log)
d

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![system](https://user-images.githubusercontent.com/106437172/170827953-dece0021-cfe3-4c41-94eb-8c14343d17bf.jpg)

**Comment by nallath** [comment]
It's unfortunately an issue that we can't fix or influence, as it's entirely caused by bugs with Ryzen.
