### ISSUE TITLE
5.0.0 Slicing error: 1 of 4 copies of a model has no bottom pattern after slicing

### ISSUE THREAD

**Issue by ManfredAdler** [Ultimaker/Cura#12374]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Voron 0.1

### Reproduction steps

1. Loaded my model
2. Multiplied the selected model 3 times to have 4 pieces printed
3. Arranged all models
4. Set Wall Thickness to 2.0mm (other values don't show the error)
5. Sliced
6. Previewed

### Actual results

On one of the 4 parts (the one on the left), the bottom pattern on the first layer is missing:
![grafik](https://user-images.githubusercontent.com/60928199/170825330-e9c34aea-61b7-4b6a-8f61-3ac519e65b6b.png)
From layer 2 on, the models are all sliced the same. 

### Expected results

All 4 copies of the same modelshould be sliced in the same maner without missing parts.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[SlicingBugReportAdler.zip](https://github.com/Ultimaker/Cura/files/8791127/SlicingBugReportAdler.zip)

(Project File)

**Comment by nallath** [comment]
I can't reproduce this with the latest version of the engine. It seems that we have already fixed this in the mean time. 

I'd suggest trying it again with Cura 5.1 once it's out. If it's still not working, feel free to re-open (or create a new ticket!)
