### ISSUE TITLE
Cura 5 does not set temperatures

### ISSUE THREAD

**Issue by lorroi** [Ultimaker/Cura#12376]
### Application Version

5.0

### Platform

Windows 10

### Printer

Prusa i3 Mk3/Mk3s

### Reproduction steps

I altered the starting-gcode from the i3 Mk3/Mk3s preset to work with my DIY i3-like machine.
Slice any file with cura 5.0 and the temperatures will not be set as defined, but the start G-Code is taken literally. 
This results in the printer starting to move without any heaters turned on... :/
In cura 4.13, the same start G-code in "machine settings" produces the desired results.
Similarly, when I use the unaltered start G-code from the preset for the Prusa i3 Mk3/Mk3s everything works as inteded. However, since I am not running PrusaFW, but vanilla Marlin instead, I cannot use the preset.

### Actual results

The start G-Code contains:
[...]
M104 **S{material_print_temperature_layer_0}** ; set extruder temp
M140 **S{material_bed_temperature_layer_0}** ; set bed temp
M190 **S{material_bed_temperature_layer_0}** ; wait for bed temp
M109 **S{material_print_temperature_layer_0}** ; wait for extruder temp
[...]

### Expected results

Instead I want the start G-Code to contain (e.g.)
[...]
M104 **S210**; set extruder temp
M140 **S60**; set bed temp
M190 **S60**; wait for bed temp
M109 **S210**; wait for extruder temp
[...]

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I uploaded the Log-file and the project-file as well as the G-code generated for a simple XYZ-calibration cub
[Log-files.zip](https://github.com/Ultimaker/Cura/files/8791345/Log-files.zip)
e

**Comment by nallath** [comment]
You have if statements in your g-code. Cura does not support these. If you remove them everything will work as normal again.

The offending line is 
`M221 S{if layer_height<0.075}100{else}95{endif}`
