### ISSUE TITLE
Cura 2.3.1 & 2.4.0 can't save profile

### ISSUE THREAD

**Issue by johannesritzer** [Ultimaker/Cura#1238]
Cura dont let ne save the profile.
![unbenannt](https://cloud.githubusercontent.com/assets/24533881/21120696/eceb10fa-c0c8-11e6-8c40-c89bee92933e.JPG)

and for sure you will see my log:
![grafik](https://cloud.githubusercontent.com/assets/24533881/21120768/40fefb48-c0c9-11e6-9ddf-2e3243a3109d.png)

plz help.
cheers!

**Comment by Ghostkeeper** [comment]
This happened sometimes when you had custom materials. We fixed that with 2.4. Did you make a custom material, @johannesritzer?

**Comment by Spirou42** [comment]
The old profiles for the UM2 for my custom materials are working, but i'm not able to create new ones for my brand new UM3. I have a bunch of custom material settings for nGen, XT, t-glaze and NinjaFlex.

**Comment by Spirou42** [comment]
It seams not to be fixed in 2.4b-darwin. Downloaded it and tried to create a profile form the current settings.
I was asked for a profile name and than a couple of files appear in the file system (~/Library/Application Support/Cura/quality) but the user interface is still unaware of the existence of the profiles.
Restarting the application does not help. The profiles are still not visible.

**Comment by Spirou42** [comment]
This will not help i presume: In 2.4.0, after adding a couple of more materials (ColorFabb HT and some color variations of nGen) suddenly all my saved profiles appeared.  After this magical appearance all the profiles are working as expected.

**Comment by RedbullVienna** [comment]
I'm using facing the same issue with version 2.4.0 :-(
When I create a new material (duplicate and modify) it is still visible in the settings menu (drop down) "material:" but when you click on "manage material" it is gone.
Any fix available yet?

**Comment by Ghostkeeper** [comment]
This doesn't reproduce any more, in master at least. If you still see this issue, let us know :)
