### ISSUE TITLE
Bug about add print and profile

### ISSUE THREAD

**Issue by uyminhtri2702** [Ultimaker/Cura#12384]
### Application Version

5.0

### Platform

window 10

### Printer

mega Zero

### Reproduction steps

import profile and add printer new

### Actual results

erro
![image](https://user-images.githubusercontent.com/101711902/170876306-126813b8-01c6-4922-9e04-bfa3f27b0c56.png)

### Expected results

fix bug! help me

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/101711902/170876343-9b5b2c04-6841-4cfc-8d68-25f78a0977b1.png)

**Comment by GregValiant** [comment]
Are you trying to install that with the stock Mega Zero definition in Cura, or did you get a custom definition file from someone?  It might be trying to load a couple of files that don't exist on your computer.
I don't have a problem installing a Mega Zero using the stock Cura definition (also Windows 10).

**Comment by nallath** [comment]
Not only would I like an answer on the questions posted by greg, I'd also need your configuration folder and log files in order to debug the issue.
