### ISSUE TITLE
Sidebar GUI

### ISSUE THREAD

**Issue by fnelen** [Ultimaker/Cura#12388]
### Is your feature request related to a problem?

Geachte,
In Cura4.x.x kon ik de extentie Sidebar GUI installeren, waardoor ik het printer settings scherm op een apart scherm kon zetten, dat was bijzonder handig voor mij. Deze functie bestaat niet meer in Cura5. Komt daar nog verandering in? of is er een andere extension die dat ook kan?
Vriendelijke groeten
Fons Nelen
fons.nelen@belgacom.net

### Describe the solution you'd like

Extentie die het printersettings scherm op een aparte monitor kan weergeven.

### Describe alternatives you've considered

Terug naar Cura 4.13.x

### Affected users and/or printers

Iedereen met dual monitor.

### Additional information & file uploads

Geen.

**Comment by fieldOfView** [comment]
Hoewel een aantal Cura devs Nederlands spreekt is de voertaal hier engels. If you prefer dutch, you can use the dutch section of the community forum: https://community.ultimaker.com/forum/123-nederlands/

I'm the creator of the Sidebar GUI plugin. Please read this forum post, which explains why the plugin is not yet available in the Marketplace for Cura 5.0, and contains a link and instructions for a prerelease of the plugin:
https://community.ultimaker.com/topic/40313-fieldofview-plugins-for-cura-50/
I am finishing up a new release for inclusion in the Marketplace now.

Generally speaking, questions about specific plugins should go to the issue-queues of their respective repositories. For the sidebar gui plugin, that is https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues
