### ISSUE TITLE
No paste in the Post Processing textfield

### ISSUE THREAD

**Issue by aixxo2** [Ultimaker/Cura#12381]
### Application Version

5.0.0

### Platform

macOS

### Printer

Anycubic Mega X

### Reproduction steps

1. copy a text to your clipboard with shortcut "Command-C"
2. open Post Processing Plugin in Cura
3. add Script "Insert at layer Change"
4. click into textfield "G-code to insert"
5. try paste with shortcut "Command-V"

### Actual results

Nothing, the textfield remains empty.

### Expected results

The textfield should have been filled with the content of my clipboard.
(The textfield should have resized due to the content for better reading and editing.)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I found no other bug report for this issue, but if I oversaw one, I'm sorry

**Comment by nallath** [comment]
This is fixed for 5.1!
