### ISSUE TITLE
Brim, Skirt and Raft don't display in preview

### ISSUE THREAD

**Issue by EM-III** [Ultimaker/Cura#12380]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

All Printers

### Reproduction steps

I sliced my model with with Brim, Skirt and Raft. None of the previews showed the Brim, Skirt or Raft. 

### Actual results

When I printed the part with Brim chosen, the brim did print.

### Expected results

The brim should show up in the preview.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Yes, I did check to make sure I was viewing the first layer.

**Comment by nallath** [comment]
Did you also enable the "helpers" in the visibility screen of the preview?

![image](https://user-images.githubusercontent.com/3922611/170985042-65d09aff-36b6-48cc-a3f0-5b4d88e3498c.png)

**Comment by EM-III** [comment]
Helpers is checked but still the supports are not displayed.

**Comment by EM-III** [comment]
![image](https://user-images.githubusercontent.com/105289514/171012092-87e1cfe8-0f8f-4e8e-9f64-deeeac23bc15.png)

**Comment by nallath** [comment]
I can't reproduce this on any of the models that I slice with. Could you provide a project file that reproduces the issue?

**Comment by EM-III** [comment]
Without changing anything, When I now slice the exact same model file, the supports and brim/skirt now appear correctly. Before I submitted the original bug complaint, I did reboot, so I am at a loss why it now works and didn't before. 
![image](https://user-images.githubusercontent.com/105289514/173064574-b77ed036-7999-4e3d-b58d-29f9d09dc2c2.png)
