### ISSUE TITLE
Objects with holes are having the holes removed after slicin

### ISSUE THREAD

**Issue by gubbas8900** [Ultimaker/Cura#12390]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 5 Plus

### Reproduction steps

Objects with holes are having the holes removed after slicing.  
1) Load object
2) Place face to bed (face with holes)
3) Slice
4) Holes gone

![Capture](https://user-images.githubusercontent.com/17454545/170895387-d5b6c541-d954-4a43-9fb1-6f583d281fd0.PNG)
![Capture1](https://user-images.githubusercontent.com/17454545/170895389-54b560f9-34ab-4cb7-b7b3-25fc71635aa3.PNG)
.

### Actual results

Preview shows no holes.  Printed object has holes deleted.

### Expected results

Object should appear as created.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE5P_Base.zip](https://github.com/Ultimaker/Cura/files/8794501/CE5P_Base.zip)

**Comment by Asterchades** [comment]
If you don't want it to do it, don't tell it to do it. Uncheck "Remove All Holes" in Mesh Fixes and it will leave them in place.

**Comment by gubbas8900** [comment]
What is interesting, is I never set that setting, nor have I ever needed to bother with the mesh fixes settings.  Now that you pointed it out, I unchecked and all is normal again.  Curious how it got checked.

**Comment by Asterchades** [comment]
Have you downloaded a print or printer profile at some point? I'd be very curious to find out where and how this happened as well - it crops up far too regularly over on Reddit for it to be something that people have accidentally done.

**Comment by gubbas8900** [comment]
Previously using Cura 4.13.1.  When I loaded 5 it copied over everything so I have not directly loaded anything into 5.

The only profile I had loaded into 4 was for my SeemeCNC Rostock Max.  Attached are the profiles given by them.
[SE300.zip](https://github.com/Ultimaker/Cura/files/8798623/SE300.zip)

**Comment by nallath** [comment]
Since this was a case of misconfiguration, I'm going to close this.
