### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by edwardsryan** [Ultimaker/Cura#12392]
### Application Version

5.0

### Platform

Mac OS

### Printer

Longer LK5 Pro

### Reproduction steps

adjusted view

### Actual results

error for slicing

### Expected results

no clue

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

no data was provided

**Comment by nallath** [comment]
Please provide the project file. We can't help you without it.
