### ISSUE TITLE
Top/Bottom pattern ignored when using spiralize outer contour

### ISSUE THREAD

**Issue by dalovering** [Ultimaker/Cura#12391]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. Add part to be printed with vase mode (i.e. spiralize outer contour)
2. Set "Bottom layers" to 3
3. Set "Top/Bottom pattern" to "Lines" or "Zig zag"
4. Set "Spiralize outer contour" setting to enabled
5. Slice

### Actual results

Bottom layers are filled with "Concentric" solid fill pattern
![image](https://user-images.githubusercontent.com/59812162/170901965-f6b5c07e-13e6-4fc2-b959-423c99d6676c.png)

### Expected results

Bottom layers should have shells according to "Wall line count" and "Lines" or "Zig Zag" solid fill, depending on "Top/Bottom pattern" setting, as in previous versions of Cura (4.12.1 shown)
![image](https://user-images.githubusercontent.com/59812162/170902047-c3ee7b47-03ea-4c6b-941f-addb5ebdf4e1.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[20mm cube project file.zip](https://github.com/Ultimaker/Cura/files/8794790/20mm.cube.project.file.zip)

**Comment by gitlui** [comment]
I can second this behaviour. Here are two screenshots of the same model and same profile between cura 4.13 and 5.
In the screenshot left ist cura5 and right ist cura 4.13
![grafik](https://user-images.githubusercontent.com/23734544/172070130-463a1845-bd5f-4d78-b95d-110b5b2a86d3.png)

**Comment by PhilBaz** [comment]
See

https://github.com/Ultimaker/Cura/issues/12075
