### ISSUE TITLE
splash screen problem

### ISSUE THREAD

**Issue by xueyebai** [Ultimaker/Cura#12407]
### Application Version

5.0

### Platform

win10

### Printer

FF

### Reproduction steps

启动画面

### Actual results

Under the dual screen, the startup screen runs to the secondary screen to start, which feels very uncoordinated

### Expected results

Under the dual screen, the startup screen runs to the secondary screen to start, which feels very uncoordinated

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by usernametakenaaaa** [comment]
Try click on "Marketplace" or "Multiply model" or make changes to a profile and switch profile (fine -> medium)
Cura will crash in addition to the wrong monitor.

There are tons of such errors reports since the Beta was released
