### ISSUE TITLE
Layer failure

### ISSUE THREAD

**Issue by celioaa** [Ultimaker/Cura#12429]
### Application Version

5.0.0

### Platform

MacOS Monterrey

### Printer

Ender 3 S1

### Reproduction steps

After installing Cure version 5.0, printed some xyz cube tests and get this result! Same profile used on Cura 4.13
![XYZ Cube](https://user-images.githubusercontent.com/106775720/171730510-49b4f645-41ba-409a-b7e8-6a6c13a7ae9e.jpeg)
.

### Actual results

Picture posted

### Expected results

Picture posted

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![XYZ Cube](https://user-images.githubusercontent.com/106775720/171730712-c919ff16-135f-4148-986d-db4e15e1123c.jpeg)

**Comment by GregValiant** [comment]
There are additional settings in 5.0 that can't carry over from 4.13.1 because they weren't in it.
A project file (File | Save Project) would likely point them out.  Off the top of my head make sure the Wall Order is "Inside to Outside".
