### ISSUE TITLE
marketplace crashing cura

### ISSUE THREAD

**Issue by GUS1999SWAG** [Ultimaker/Cura#12421]
### Application Version

5.0.0

### Platform

Windows 1

### Printer

creality cr-10

### Reproduction steps

1. clicked on marketplace icon on top right

### Actual results

 it opened marketplace blank window and crashed.

### Expected results

expected to open marketplace so i can install plugins

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8814936/cura.log)

**Comment by usernametakenaaaa** [comment]
You have more than one screen or a docking station ? Cura 5 is currently not compatible with that and will crash.
If you completely disable the 2nd screen it will work
