### ISSUE TITLE
Missing Print Setting

### ISSUE THREAD

**Issue by Firedogs2x** [Ultimaker/Cura#12436]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Modix Big-60

### Reproduction steps

Hello, I was watching a video about supports, and following along with my CURA program open. When the video talked about the setting for the “Support Z Distance”, specifically setting the “Support Bottom Distance” I was not able to find that setting under “Printer Settings”.

So, I opened Preferences, Settings, and Settings Visibility. When I scroll down to the Support section, I see that option is checked.

So, I wanted to contact you and let you know what I found.

Thank you.
Dirk
![CURA Print Settings 2022-06-03](https://user-images.githubusercontent.com/5606057/171953136-b7cbf1d1-ef2c-4676-bb62-be0379fca8ec.jpg)
![CURA Settings Visability Options 2022-06-03](https://user-images.githubusercontent.com/5606057/171953140-524514e6-641e-42e7-9e2d-19a187b1f02f.jpg)
![CURA Version 2022-06-03](https://user-images.githubusercontent.com/5606057/171953142-d57e4756-1699-4740-a4d7-6bdaa56f5b37.jpg)

### Actual results

I am unable to see "Support Bottom Distance".

### Expected results

I should see "Support Bottom Distance".

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

There is no more information beyond what I stated above.

**Comment by Asterchades** [comment]
Support Bottom Distance is only available if you're using Everywhere for Support Placement. It's a completely irrelevant setting otherwise.

**Comment by Firedogs2x** [comment]
Yes, I see that now. I did not have support everywhere.

Sorry for the mistake.

Thank you for your help and support.
