### ISSUE TITLE
sections of model not being sliced

### ISSUE THREAD

**Issue by RenchesAndSords** [Ultimaker/Cura#12437]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Tronxy x5sa 400 pro

### Reproduction steps

![Screenshot 2022-06-03 173138](https://user-images.githubusercontent.com/40300986/171956096-ebbb837e-3d7a-4e25-9121-acc9238eb66d.png)
![Screenshot 2022-06-03 173151](https://user-images.githubusercontent.com/40300986/171956097-920b7ef8-ade3-4c42-accd-2b3291cfdfb8.png)
![Screenshot 2022-06-03 173154](https://user-images.githubusercontent.com/40300986/171956098-0016d4f0-110b-4570-9705-3108018fb860.png)
![Screenshot 2022-06-03 173159](https://user-images.githubusercontent.com/40300986/171956099-750dbaca-5481-4cfa-9c86-93894f56d403.png)

### Actual results

files show models in preview and layer view, slicer is ignoring part of the bottom of the model

### Expected results

bottom of the rectangular piece should be smooth with no need to generate support
[CFFFP_laptop kickstand_slim_pair.zip](https://github.com/Ultimaker/Cura/files/8835827/CFFFP_laptop.kickstand_slim_pair.zip)
s

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_laptop kickstand_slim_pair.zip](https://github.com/Ultimaker/Cura/files/8835829/CFFFP_laptop.kickstand_slim_pair.zip)
![Screenshot 2022-06-03 173138](https://user-images.githubusercontent.com/40300986/171956845-f339fb19-f2ce-4de8-a8d9-373e3f645188.png)
![Screenshot 2022-06-03 173151](https://user-images.githubusercontent.com/40300986/171956853-452ce004-0075-48ad-ba3f-75047f3ceee0.png)
![Screenshot 2022-06-03 173154](https://user-images.githubusercontent.com/40300986/171956855-28e44abc-b103-434e-9c3e-61619429e8dc.png)
![Screenshot 2022-06-03 173159](https://user-images.githubusercontent.com/40300986/171956858-29053545-5e7f-43e3-9cbf-18081e8b8397.png)

**Comment by GregValiant** [comment]
Did the Not Watertight warning come up?  The model has errors.
From [Formview.co](https://formware.co/OnlineStlRepair)
-> Analysed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 2 Non-manifold edges (?)
--> 2 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 110648ms ------
-> Vertex count changed from 107480 to 104187 (-3293)
-> Triangle count changed from 215004 to 208438 (-6566)

One of these has been repaired.
![image](https://user-images.githubusercontent.com/64202104/171978636-be5a5c8c-de40-41fd-9998-43d698fd15c2.png)
