### ISSUE TITLE
Allow bridge skin density > 100%

### ISSUE THREAD

**Issue by traviselam** [Ultimaker/Cura#12455]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Attempt to set the bridge skin density > 100%

### Actual results

Unable to slice

### Expected results

Slice and allow the bridge skin density > 100% like Bridge second and third skin density.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is technically a duplicate issue of a previously closed issue: 
- https://github.com/Ultimaker/Cura/issues/10736

And this was supposedly resolved in this commit:
- https://github.com/Ultimaker/Cura/commit/346640478227cb4e868d85ff37c4f5835cc5cc2f

However, in the latest CURA 5.0.0 this is not an allowed option. Was this a merge issue?

**Comment by nallath** [comment]
Whoops! That was a mistake on our side. Should be fixed for 5.1 now!

**Comment by traviselam** [comment]
Awesome! I was doing some substantial bridge testing and I was hoping to get lower skin/wall flow with an increased density so I could cool less plastic over many passes to get a nicer-looking bridge first layer. Thank you!
