### ISSUE TITLE
PrintrBot keeps "connecting"

### ISSUE THREAD

**Issue by Oceanic217v2** [Ultimaker/Cura#12456]
### Application Version

15.04.2

### Platform

Windows 11

### Printer

PrintrBot simple maker revf5

### Reproduction steps

Hi all! Ive recently got this Printrbot simple maker model 1405. Its taken forever to find drivers, old versions of Cura and how to understand everything since I'm new to this. Ive flashed it and everything but Ive ran into two issues, Cura 15.04.2 Recognizes it and the COMS ports but it just is stuck on a "connecting" screen while trying to print. It has already verified the COM Ports and Baurdrarte. It has been sitting like this for a better most of a hour and nothing. Ive also tried printing via SD Cards and it doesn't even move. If anyone could tell me a good direction to follow that would be super helpful! Thank you!!

### Actual results

Connecting isues.

### Expected results

Nothing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot 2022-06-05 191857](https://user-images.githubusercontent.com/106935117/172074712-fbabe7ae-1fa9-4511-ba05-363b1ced913c.png)

**Comment by GregValiant** [comment]
If there are USB problems AND the SD doesn't work then it would seem to be a mainboard problem.  Either some component has malfunctioned, or the firmware installation isn't correct.  I searched for the printer and some of the support articles have been removed and the information on the printer is sketchy.
The drivers and such that Adafruit recommended are listed on [This Support Documment](https://cdn-shop.adafruit.com/datasheets/CID2444_Datasheet.pdf).  It looks like there was a Windows 8 configuration using Repetier?  You could experiment with different port drivers but that wouldn't account for the problem printing via the SD card.  Have you tried contacting Adafrruit?  Maybe someone there has more information.  It may be that the Win8 drivers just don't want to work with your Win11 computer.  A generic CH340 port driver might be something to check out (but there is that SD card thing). 
 Good Luck
