### ISSUE TITLE
A bug that acually improve the print quality???

### ISSUE THREAD

**Issue by AstroZYX** [Ultimaker/Cura#12459]
![Detour](https://user-images.githubusercontent.com/99131153/172155154-4925f7dd-c700-446d-8eca-4d3703c372e6.png)

### Application Version

5.0.0

### Platform

Windows 10

### Printer

Voron 2.4 254mm

### Reproduction steps

Using 0.8mm nozzle print some small object

### Actual results

At 1st layer, The nozzle take a comb detour between each bottom line and print the line in same direction

### Expected results

This hugely improve the the print quality, normally it will just smush a lot of plastic in a small area because of oozing so I normally remove some skin to pervent this but that create other problems

I wish we can have this as a function/option to print small skin areas or at start/end of the top/botton that the length of the line became too short and oozing override any control.

Something like "If a top/bottom line shorter than ***, take a detour"

Also please do think about wall line width on the highest top layer, only skin line width is not enough

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[V250_Cura 5 Bug Report.zip](https://github.com/Ultimaker/Cura/files/8844258/V250_Cura.5.Bug.Report.zip)

**Comment by MariMakes** [comment]
Hey @AstroZYX thanks for the report.
I took a look and I am still seeing the same cumbersome travel Cura 5.1.

But... I suspect it has something to do with your combing behavior. 
If you change it to Within Infill I believe it is displaying the behavior you are looking for.
[You can learn more about it in the settings guide. ](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/travel/retraction_combing.md)

Can you let us know if this is the behavior you are looking for? 👼
