### ISSUE TITLE
Stop Z-seam in overhang

### ISSUE THREAD

**Issue by Rubenzzz** [Ultimaker/Cura#12458]
### Is your feature request related to a problem?

When slicing a model I frequently have to play around with the Z-seam position. It might start in an overhang and is not (completely) supported by the previous layer. For instance, the top of the doorways in a benchy. If it starts in the overhang, the plastic will have nothing to attach to and droop down.
<img width="1033" alt="Benchy Z-seam in overhang" src="https://user-images.githubusercontent.com/106967575/172153406-95319c08-94f4-44c6-bd05-1323623a794c.PNG">

### Describe the solution you'd like

A feature to place the z-seam away from the overhangs whenever possible.
If it starts far enough from an overhang, there will be enough plastic supported to build the overhang. 
Alternatively, it may start closer to the overhang, if the nozzle starts the layer in the opposite direction of the overhang, thus ending the layer with the overhang. 

### Describe alternatives you've considered

Playing around with the z-seam position settings. However they do not always end up where I'd like them to be.

### Affected users and/or printers

Those users who's printers can do moderate to steap overhangs.

**Comment by smartavionics** [comment]
See #12220
