### ISSUE TITLE
Feedrate setting not updating like bed and extruder temp when dropping file into repetier host

### ISSUE THREAD

**Issue by mo7abdo** [Ultimaker/Cura#12467]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Graber i3/pursa i3

### Reproduction steps

updating cura and repetier host

### Actual results

nothing

### Expected results

probably fix the issue

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8856922/cura.log)
e

**Comment by GregValiant** [comment]
I don't get it.  Could you explain further?  What kind of file are you talking about?  How is this a problem with Cura?
