### ISSUE TITLE
Configuration error when application loads. Option to reset does nothing.  

### ISSUE THREAD

**Issue by thedaviator** [Ultimaker/Cura#12461]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3 v.2

### Reproduction steps

Launch the application
Notice that the attached error appears 
Clicking "Reset" and restarting the application has no affect. 

### Actual results

Cannot get past error so the application is useless. 

### Expected results

At the very least, have reset button do what the error claims it will do. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![5 0 ender 3 v2](https://user-images.githubusercontent.com/1562261/172194832-e98714b3-9117-44ca-9280-2ebba2076bc0.JPG)

**Comment by nallath** [comment]
The reset button has been fixed for the 5.1 release. 

Without your configuration folders and log files, I can't find out what caused the error to show in the first place.
