### ISSUE TITLE
Retraction stops on 16th layer 

### ISSUE THREAD

**Issue by JerryNew99** [Ultimaker/Cura#12466]
### Application Version

5.0.0

### Platform

windows 10

### Printer

Ender 3v2

### Reproduction steps

Loaded the 'retraction test' from 'part from calibration'. 
Set retract distance to .8mm and retraction speed to 50mm/s. I'm using a direct drive

       
![IMG_0778](https://user-images.githubusercontent.com/107061096/172424094-4dce0289-a524-4585-a5ea-995178bd5eef.JPG)
 

### Actual results

The first 15 layers print fine, the retraction is occurring, no stringing. 
On the 16th layer the retraction just isn't occurring and there is string. 

### Expected results

Retraction should be occurring for the whole print 

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8854708/cura.log)

**Comment by GregValiant** [comment]
That's a plugin written by 5axes.  The [GitHub page is HERE](https://github.com/5axes/Calibration-Shapes).

**Comment by JerryNew99** [comment]
I should add, I tried with another similar model from an external source.

**Comment by GregValiant** [comment]
Did you use the post-processing plugin "retract tower"?

**Comment by nallath** [comment]
> I should add, I tried with another similar model from an external source.

Okay, which one? 

It's very likely that this is caused by the "minimum extrusion distance window" setting.

**Comment by JerryNew99** [comment]
I think you're right, thanks.
