### ISSUE TITLE
Slice Failed

### ISSUE THREAD

**Issue by hhagquist** [Ultimaker/Cura#12479]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

Opened the Sugar Skull from Hex3D
Went to slice using the Standard 0.2mm layer profile

### Actual results

Got a slice failed error
![Screenshot 2022-06-08 214224](https://user-images.githubusercontent.com/97145776/172746315-49aae5c0-9338-43d3-9245-6bda85e466d7.png)

### Expected results

Should have sliced properly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Could not upload project file. Find it on my Dropbox at https://www.dropbox.com/s/oi1iib4gcgt6wlf/Deluxe_SugarSkull%20R.zip?dl=0

**Comment by GregValiant** [comment]
The model is watertight but there are errors.  After repairing it in MS 3D Builder it sliced.  The zip file won't upload because it's 47mb and is over the 25mb limit.
![image](https://user-images.githubusercontent.com/64202104/172930876-b5285908-aaed-407e-be23-cdfe5a1a122c.png)

**Comment by GregValiant** [comment]
@hhagquist I'm going to close this as it appears to be a model issue.  If you feel that it should remain open let me know.
