### ISSUE TITLE
No full screen mode at Ubuntu

### ISSUE THREAD

**Issue by grenki** [Ultimaker/Cura#12471]
### Application Version

5.0.0

### Platform

Ubuntu 

### Printer

Custum FFF

### Reproduction steps

After run AppImage no full screen mode availabe

### Actual results

no full screen mode at right top corner of window
![image](https://user-images.githubusercontent.com/6865824/172539787-d7ac9987-a762-48e8-994e-a8b11b009918.png)

### Expected results

Full screen mode at right top corner of window at cura 4.13.1
![image](https://user-images.githubusercontent.com/6865824/172539273-1a4b980d-b85f-4b1c-a37a-ad46adfcec13.png)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8858559/cura.log)

**Comment by nallath** [comment]
What version of Ubuntu? I've tried it on 21.04 and it works for me.
