### ISSUE TITLE
Slow to slice.

### ISSUE THREAD

**Issue by chibastos** [Ultimaker/Cura#12506]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Creality Ender-3 MAX

### Reproduction steps

Slow to slice, takes longer than 30 minutes

### Actual results

Slow to slice, takes longer than 30 minutes

### Expected results

Slow to slice, takes longer than 30 minutes

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

Slow to slice, takes longer than 30 minutes

**Comment by fieldOfView** [comment]
Without a project file there is nothing we can do about this issue.

**Comment by chibastos** [comment]
https://www.myminifactory.com/object/3d-print-deadpool-bust-rem
![CURA_5 0 0](https://user-images.githubusercontent.com/107352581/173234107-bf675416-8ece-4cf2-b28b-f3a6c6a133c5.jpg)
astered-supportless-edition-81435#google_vignette

**Comment by chibastos** [comment]
I attached an image and the file path.

https://www.myminifactory.com/object/3d-print-deadpool-bust-remastered-supportless-edition-81435#google_vignette
[https://cdn.myminifactory.com/assets/object-assets/5c145d5a14bbc/images/720X720-deadpool-bust-v2-01.jpg]<https://www.myminifactory.com/object/3d-print-deadpool-bust-remastered-supportless-edition-81435#google_vignette>
3D Printable Deadpool Bust (Remastered Supportless Edition) by Eastman - MyMiniFactory<https://www.myminifactory.com/object/3d-print-deadpool-bust-remastered-supportless-edition-81435#google_vignette>
| Download free and paid 3D printable STL files
www.myminifactory.com

________________________________
De: Aldo Hoeben ***@***.***>
Enviado: domingo, 12 de junho de 2022 09:43
Para: Ultimaker/Cura ***@***.***>
Cc: chibastos ***@***.***>; Author ***@***.***>
Assunto: Re: [Ultimaker/Cura] Slow to slice. (Issue #12506)


Without a project file there is nothing we can do about this issue.

**Comment by fieldOfView** [comment]
None of the links you posted work. From the image, it looks like a fairly detailed model, and there are certain settings that are computationally intensive to slice. You could try slicing with regular supports instead of tree supports.

To get a definitive answer, we really need a project file, because that includes all your settings. A project file can be created with File -> Save project...

**Comment by chibastos** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]deadpool-bust-v2-supportless.stl<https://1drv.ms/u/s!AjAsASc_dmRZmHWFf3a-EHLghhhF>[https://res.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]deadpool-bust-v2-supportless.3mf<https://1drv.ms/u/s!AjAsASc_dmRZmHS4MV085Noh5Gt5>


in cura 4.13.1 I'm getting it faster


________________________________
De: Aldo Hoeben ***@***.***>
Enviado: domingo, 12 de junho de 2022 15:46
Para: Ultimaker/Cura ***@***.***>
Cc: chibastos ***@***.***>; Author ***@***.***>
Assunto: Re: [Ultimaker/Cura] Slow to slice. (Issue #12506)


None of the links you posted work. From the image, it looks like a fairly detailed model, and there are certain settings that are computationally intensive to slice. You could try slicing with regular supports instead of tree supports.

To get a definitive answer, we really need a project file, because that includes all your settings. A project file can be created with File -> Save project...
