### ISSUE TITLE
Bottom pattern same for Lines and Zig Zag

### ISSUE THREAD

**Issue by floridajohn** [Ultimaker/Cura#12509]
### Application Version

5.0.0

### Platform

Windows 10 Pro - Xeon E5 2690 - HP Z620 

### Printer

Creality Ender 3

### Reproduction steps

Large print (~80mm x 230mm) that I actually had to rotate it on the plate (~45 degrees to get it to fit - had to turn off snap to get it exactly in the orientation that would print.

Lines was producing a rough looking bottom surface.  Switched to Zig Zag but the physical output was still Lines.  Preview for both is the same.  Concentric preview is as expected as is the print.

I've only been doing 3D printing for 5 months so please have some patience with me - and this is my first CURA ticket.

[C6 coffee V2.zip](https://github.com/Ultimaker/Cura/files/8886007/C6.coffee.V2.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/8886009/cura.log)

### Actual results

Lines not Zig Zag for bottom layers

### Expected results

Zig Zag not lines for bottom layers

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Low end video card - NVIDIA GeForce 9800 GTX/GTX+

**Comment by Asterchades** [comment]
Are you able to provide screenshots of the (mis)behaviour? I'm unable to reproduce what you're describing using the project file you've given.

Zig Zag:
![image](https://user-images.githubusercontent.com/29810435/173287221-8658d818-273c-487b-9768-e2b319661891.png)

Lines:
![image](https://user-images.githubusercontent.com/29810435/173287252-1e643340-c4c0-405d-9e5b-7baeea50b3a4.png)

Both are similar as expected, but you can clearly see the links between the lines around the circle and along the edges when the Zig Zag pattern is in use.

**Comment by floridajohn** [comment]
I actually physically printed them part way.  Went out to get them from the
trash but they got an early start and they are gone.  Attached are 3 pics.

**Comment by Asterchades** [comment]
Your images haven't attached. You might need to upload them directly via GitHub rather than replying to the email notification with attachments.

I did double check just in case the preview is showing the links and the GCode isn't actually being generated and Cura, PursaSlicer , and IdeaMaker's GCode viewers are showing the joining lines present. I can't actually run a test print as my printer is physically too small but something very odd would need to be happening at the printer level for the GCode to be present but not executed.

**Comment by floridajohn** [comment]
It's my first GitHub.  I just attached them to a reply email.  Here you go:

![gammel-lines](https://user-images.githubusercontent.com/42040111/173428928-e0f34833-ac7b-42ee-94bf-3162f0f4c77d.jpg)
![gammel-concentric](https://user-images.githubusercontent.com/42040111/173428931-52d66aef-880a-4ed6-bd65-4bc0ea4dbf3d.jpg)
![gammel-zigzag](https://user-images.githubusercontent.com/42040111/173428932-de34fd25-1506-46c3-b88b-52727437da02.jpg)
.

**Comment by floridajohn** [comment]
Ok, thanks for the clarification.  Let's let this go.
