### ISSUE TITLE
Hover over Combing options the pop up window dialouge seems not right

### ISSUE THREAD

**Issue by tmanstls** [Ultimaker/Cura#1251]
When you hover ove the combing option, the last 2 sentences say the same thing. They are supposed to explain each selection, but somehow were duplicated?
![curacomb](https://cloud.githubusercontent.com/assets/24613260/21276964/8c51bbee-c399-11e6-98bd-93d32d25fad7.PNG)

**Comment by Ghostkeeper** [comment]
They were duplicated.

This has been fixed since then though: https://github.com/Ultimaker/Cura/commit/707b38431bc927203d4729bc27b8f1cd599c103b

It'll be better in 2.4.
