### ISSUE TITLE
Heating Bed

### ISSUE THREAD

**Issue by Gheim2** [Ultimaker/Cura#12522]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

I sliced an object with a build plate temperature different by the Build Plate Temperature Initial Layer from the printing settings.

### Actual results

When i started printing the build plate temperature automatically sets to 0 degrees.

### Expected results

The build plate temperature for the initial layer should has set to 108 degrees and next to 105, but it didn't happen

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I cannot upload the .3mf file. It says "We don't support that file type
![Giunto a - Ultimaker Cura 14_06_2022 22_29_01](https://user-images.githubusercontent.com/87243317/173682715-c562f668-cd1b-4b03-a6bc-4fe5a3bc9ef9.png)
"

**Comment by nallath** [comment]
I've not been able to reproduce this. I've set the initial build plate temperature to 21 degrees and the normal one at 50. After inspecting the g-code, i can see that the correct commands are given.

Github doesn't like certain file types. You can get around that by zipping the 3mf file (as is also instructed by the template)
