### ISSUE TITLE
Add Virtual Extruders to Dual Printers like the A20M

### ISSUE THREAD

**Issue by muckypaws** [Ultimaker/Cura#12529]
### Is your feature request related to a problem?

I have a couple of Geeetech A20Ms which are configured in Cura using the default A20M profile.  However, if I want to add Virtual Extruders to the printer profile, I'm unable to, since the default profile limits the number to two.

The virtual extruders would contain percentages of mix from each physical extruder.  Currently I edit the Start G-Code to set these percentages which is great until I kick off a print forgetting I did this 🤦🏼‍♂️

![Screenshot 2022-06-15 at 11 40 34](https://user-images.githubusercontent.com/7505779/173808367-ae0143e1-4e56-4e03-ad69-98fe73d4307c.png)
 

### Describe the solution you'd like

I would like a way to automatically override the default printer profile to add virtual extruders up to the maximum of 8 please.

### Describe alternatives you've considered

I've looked at manually editing the config files, but don't know enough as I usually get a message saying the profile is corrupt when trying to add extruders by editing and copying config file.

A tutorial how to do this manually would be appreciated in the interim

### Affected users and/or printers

Anyone with a default Cura profile for multi-extrusion but isn't configured to allow virtual extruders.

I appreciate this might be an "Advanced Option" for new new users unfamiliar with printing.

### Additional information & file uploads

Thank you for considering my request :)

**Comment by nallath** [comment]
If you want more extruders, the easiest option is to add a custom printer. There you can go up to eight.

As for modifying other printers configurations, it's not something we (can) do. All the printer profiles that we have are contributed to us by the company that produced them or someone from the community. 

Adding the virtual (mixing) extruder is not something that we will implement in the future, as ultimaker printers don't have this feature. So not only wouldn't it benefit us, we would also not be able to test it in any way.
