### ISSUE TITLE
"slicing failed"

### ISSUE THREAD

**Issue by FjolnirsBath** [Ultimaker/Cura#12543]
### Application Version

5.0.0

### Platform

windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. loaded file from stemfie rubber band car kit: SPS-000001 - Rubber-band-driven car - Beams Braces (stemfie.org) both by double clicking file in file explorer, and then by trying to open file from Cura file menu.
2. attempt to slice

### Actual results

receive unspecified "slicing failed" message, then forced to create this report

### Expected results

expected slicing to complete and file to export

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

inside text

**Comment by nallath** [comment]
Please provide the model that fails for you. You can add them via the web interface if you zip them.

**Comment by cht685** [comment]
Seems like this is becoming a popular error :( I just posted yet another one of these today. :(
