### ISSUE TITLE
cant save files

### ISSUE THREAD

**Issue by joshwa0991** [Ultimaker/Cura#12547]
### Application Version

5.0.0

### Platform

Acer chromebook

### Printer

Anycubic i3 Mega

### Reproduction steps

Tried to save a print to a usb stick

it doesnt work

none of the save buttons work

### Actual results

nothing.

### Expected results

For it to actually save

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

.

**Comment by nallath** [comment]
You didn't add the requested log files. We can't help you without that.
