### ISSUE TITLE
Unexpected Slicing Error (5.0.0)

### ISSUE THREAD

**Issue by GreetingsGQ** [Ultimaker/Cura#12563]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Prusa i3 Mk3/Mk3s

### Reproduction steps

Press slice

### Actual results

Error message:
Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.

### Expected results

gcode created

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![cura slicing error](https://user-images.githubusercontent.com/12089530/174514548-b91fd79d-a83a-49fd-b028-1bd2e8a0024e.png)
[cura.log](https://github.com/Ultimaker/Cura/files/8937079/cura.log)
[PI3MK3M_FDG_Giant_Rack_Nolock_Fixed.zip](https://github.com/Ultimaker/Cura/files/8937092/PI3MK3M_FDG_Giant_Rack_Nolock_Fixed.zip)

**Comment by Asterchades** [comment]
The project file name suggests that it has been "fixed' but a quick check suggests there's more than a few issues remaining - PrusaSlicer reports over one million issues, or one per vertex, the Solid Inspector² plugin SketchUp shows thousands (plural) of disconnected surfaces and stray edges, and I've given up waiting for MeshMixer's report as it's been scanning for over 30 minutes on my 3900x without finishing. In other words, the model is, at least for 3D printing purposes, a right mess.

Repairing the model with 3D Builder (a free tool under Windows 10 or 11) allows it to slice without issue (though it doesn't stop the pillars from being separate pieces at the top). It also cuts out a few tens of thousands of superfluous triangles, reduces the vertex count by over 80% (making it under half the triangle count, which is more expected), and knocks about a quarter off the file size (which is nice).

[PI3MK3M_FDG_Giant_Rack_Nolock_Fixed-Repaired.zip](https://github.com/Ultimaker/Cura/files/8938160/PI3MK3M_FDG_Giant_Rack_Nolock_Fixed-Repaired.zip)

Cura is a slicer, not a modelling program. It has some ability with regards to correcting models but this was simply beyond what it is capable of addressing. None of the in-built Mesh Fixes, nor the Mesh Tools plugin could salvage this one - an external modelling tool was required to fix it.
