### ISSUE TITLE
Low Camera FPS

### ISSUE THREAD

**Issue by SQuicke** [Ultimaker/Cura#1256]
When monitoring my ultimaker 3 prints on the LAN the camera FPS is down to around 1-2fps.  This is using my Laptop using a wired connection.  I've recently downloaded the ultimaker 3 app and monitoring the camera on my phone over wifi is much smoother.  Is there any known issue with the camera or could it be a problem with the LAN?  Everything else seems to run fine over the network.

**Comment by daid** [comment]
Known issue, there where problems in getting the same feed working in Cura as the App is using. So it falls back to using slow snapshots. I think the next update will fix this problem. (I'm sure someone will drop in here to confirm this)

**Comment by SQuicke** [comment]
Thank you David.  Any ideas when the update will be released?  It's not a major issue, more frustrating than anything!

**Comment by daid** [comment]
I hope before new year.

**Comment by fieldOfView** [comment]
Cura 2.4 does indeed use the video stream instead of snapshots. It also stops requesting frames when you're not looking at the monitor (Cura 2.3 is a bit wastefull there)

**Comment by daid** [comment]
How does Cura know I'm not looking at the monitor? Cura spying on me?!? ;-)

**Comment by nallath** [comment]
Yes

**Comment by Ghostkeeper** [comment]
Fixed in firmware.

**Comment by fieldOfView** [comment]
No, fixed in Cura
