### ISSUE TITLE
2.4 - Project saved with no file extension

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1257]
Just trying out 2.4 on a 64 bit Ubuntu system and when I saved a project it didn't give the file the .curaproject.3mf extension. I would have thought it should have done as the file save dialog has that file type filter.

**Comment by nallath** [comment]
This sometimes happens. I've not been able to figure out where this comes from. I get the impression that this has to do with the file dialog in Ubuntu.

**Comment by BerndJM** [comment]
Additional:
after saving a project (without extension) the regular "Save to File"  switches from .gcode to .3mf as default ending.
When you now again save the project, the filename is correctly appended with .curaproject.3mf
...
spooky ;-))

**Comment by Ghostkeeper** [comment]
Was that also on Ubuntu, @BerndJM? Or on OSX? Because on OSX we save simply as .3mf due to OS constraints.

**Comment by BerndJM** [comment]
It's on Ubuntu ...

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by smartavionics** [comment]
Don't know, let's close this issue and if I have any more problems I will create a new issue.

**Comment by Ghostkeeper** [comment]
We had some fixes for this around the release of Cura 2.6.
