### ISSUE TITLE
'zoom toward mouse direction' not working properly on high resolution machine (3840 x 2160)

### ISSUE THREAD

**Issue by discip** [Ultimaker/Cura#12577]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

not relevant

### Reproduction steps

I am experiencing a strange behavior of the 'zoom towards mouse' feature.
It does not work as it did before Cura 5.0.0.
Although zooming works, the corresponding panning does not keep up.

This issue is not related to a specific printer.

Since I am using Cura on 2 different machines and the bug occurs only on the machine with the higher resolution (3840 x 2160), I assume the higher resolution to be the cause.

### Actual results

No proper zooming towards mouse.

### Expected results

Panning  should keep up with zoom.

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8950299/cura.log)

**Comment by nallath** [comment]
Fixed by: https://github.com/Ultimaker/Uranium/pull/817

**Comment by discip** [comment]
@nallath
Thanks! 👍

**Comment by discip** [comment]
@nallath
In the beta 5.1.0 this is still not working!

**Comment by nallath** [comment]
Well, yes, because it wasn't merged yet ;)

**Comment by discip** [comment]
Ah, I see.
Thanks.

**Comment by discip** [comment]
@nallath
Still not fixed for latest stable release (Cura 5.1.0).

**Comment by MariMakes** [comment]
Hey @discip
It seems like the fix was not merged in time for release. 😢 
I'll go ask the team what happened and if we can have it for the next release instead. 
Fingers crossed 🤞

**Comment by discip** [comment]
@MariMakes
### Thank you. 😃

**Comment by discip** [comment]
Seems to be fixed in 5.2.0-beta!

**Comment by MariMakes** [comment]
![giphy (8)](https://user-images.githubusercontent.com/40423138/193788176-9717cca5-6570-46d2-861f-88b44170673e.gif)
