### ISSUE TITLE
Ultima Cura won't open on MacOS

### ISSUE THREAD

**Issue by dylanReinsma** [Ultimaker/Cura#12571]
### Application Version

5.0.0

### Platform

Mojave MacOS

### Printer

Anycubic Vyper

### Reproduction steps

I was on 4.13, was prompted for an update, installed update, and it installed a separate application. I uninstalled 4.13, deleted the cura folder, and 5.0.0 still will not open.

### Actual results

I uninstalled 5.0.0, made sure cura folder was still deleted, attempted to start, and cura bounces a few times on the dock and does not open.

### Expected results

I expect the cura 5.0.0 to open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have no files to upload because the app simply will not open

**Comment by nallath** [comment]
Mojave isn't supported for Cura 5.0 https://support.ultimaker.com/hc/en-us/articles/360011889579-On-what-operating-systems-is-Ultimaker-Cura-available-
