### ISSUE TITLE
Slicing issue

### ISSUE THREAD

**Issue by GabrielStevenson** [Ultimaker/Cura#12579]
### Application Version

5.0.0

### Platform

10

### Printer

Enderv2

### Reproduction steps

1. I slice a model
2. Extract the model
3. print the model

### Actual results

1. couldnt slice the model

### Expected results

that I could slice the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by GabrielStevenson** [comment]
number 10 means windows 10

**Comment by GabrielStevenson** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/107952403/174913585-3977759e-3a5a-401c-9a1a-45188022e519.png)

**Comment by GregValiant** [comment]
1. You use Windows 10.
2. You are using Cura 5.0.0.
3. A model didn't slice.
With the model loaded in Cura use the "File | Save Project" command.  That will create a 3mf project file.  Zip the file and post it here.  There is a reason the form you filled out asks for a Project File and the Cura.log file.

**Comment by GabrielStevenson** [comment]
[New folder (2).zip](https://github.com/Ultimaker/Cura/files/8958151/New.folder.2.zip)

**Comment by GregValiant** [comment]
And after all of that it sliced fine for me.
![image](https://user-images.githubusercontent.com/64202104/175078332-cfbf9978-3cf9-4930-a309-54ed44fd2118.png)

The next step is:  In Cura - under the Help menu the top command is "Show Configuration Folder" click on it.  In that folder is the Cura.log file.  Zip that file up and post it here.  The model doesn't appear to have any errors.  Hopefully whatever happened got logged in that file.

**Comment by GabrielStevenson** [comment]
[Log.zip](https://github.com/Ultimaker/Cura/files/8966920/Log.zip)

**Comment by cht685** [comment]
Did you ever get this to work? This just started happening to me this morning. I can load the files up in 4.13.1 and slice it just fine. But if I try to slice them in 5.0.0, I get this same error...I just opened another ticket for the same issue.

**Comment by GabrielStevenson** [comment]
Hello I actually did the creator of the model your looking at sent it to me again and I dont know what kind of magic he did but its works now but I left this ticket open to see what happens

**Comment by Joeydelarago** [comment]
> Hello I actually did the creator of the model your looking at sent it to me again and I dont know what kind of magic he did but its works now but I left this ticket open to see what happens

Hello, I've had a look at the logs. It seems that the original model you were using had both overlapping and disconnected faces which causes the slicing to fail. The creator probably loaded the mesh up in blender and cleaned these up. 

I'll close ticket since it is resolved.
