### ISSUE TITLE
Creality belt program Crashes when saving files

### ISSUE THREAD

**Issue by GarySmith405** [Ultimaker/Cura#12580]
### Application Version

3.6.0

### Platform

Windows 10

### Printer

Creality CR-30

### Reproduction steps

1. slice file
2. select save sliced file and enter
3. watch wheel spin 3 seconds.
4. watch program vanish from screen.
5. verify that file is written... file is there, but only a partial file. not usable.

### Actual results

same thing happens when I try to save an STL file that has been modified.

### Expected results

Expect to have the file written and the program still running when write completes.'

Can't save a project file. Program crashes when I try to save any file of any type.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura 3 6 0 log file.pdf](https://github.com/Ultimaker/Cura/files/8952085/cura.3.6.0.log.file.pdf)

**Comment by fieldOfView** [comment]
The "Creality belt program" is not supported here. Please ask Creality for support for their programs.
