### ISSUE TITLE
Feature request: Quickly duplicate/make multiple items

### ISSUE THREAD

**Issue by sp847242** [Ultimaker/Cura#1258]
Hello,
Feature request: I've got a small part that I want to make about 20 of. The only way I've found to do that, other than opening the file 20 times, is to right-click and select Duplicate, and redo that 20 times.

I was thinking to have something in the toolbar with Move, Scale, Rotate, Mirror, and Per Model Settings with a Quantity entry, possibly withing the Per Model Settings slide-out: Just enter in a number, and the software quickly arrays the part.

Thank you.

**Comment by fieldOfView** [comment]
Good news, this is already part of what will very soon be Cura 2.4

**Comment by Ghostkeeper** [comment]
Already implemented! Thanks to @fieldOfView right here.
