### ISSUE TITLE
slicing issue

### ISSUE THREAD

**Issue by MrEj89** [Ultimaker/Cura#12595]
### Application Version

5.0.0

### Platform

windows 11

### Printer

creality cr10s pro

### Reproduction steps

added a file I've slice before an clicked slice

### Actual results

fails to slice and says there's a error

### Expected results

It should slice and give me a Gcode

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![failed slice](https://user-images.githubusercontent.com/108098602/175406361-c38deae5-37b4-406e-a449-346cbf7e7260.jpg)

**Comment by GregValiant** [comment]
If you could either post the model file, or better, a project file then I can take a look.  There have been several issues similar to this and if this is different then it will stay open but if it is the same sort of problem that has already been reported then I'll link this to the others and close this one.
