### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by nickisghosty** [Ultimaker/Cura#12596]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Opened a file from explorer by double clicking it
2. Left it open over night
3. Switched from a profile I have saved to dynamic quality
4. Clicked keep changes
5. Slicing failed, and asked me to report a bug.

### Actual results

slicing failed

### Expected results

should have sliced? 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I probably just need to restart cura
[cura.log](https://github.com/Ultimaker/Cura/files/8971208/cura.log)

**Comment by Asterchades** [comment]
Without a project file this is going to be almost impossible to accurately diagnose.

Best guess in the absence of a project is that the model is in need of repair. Cura 5 is currently far more dependant on having a well-made model than its predecessors.
