### ISSUE TITLE
Wire Print Crashes shortly after being selected from options

### ISSUE THREAD

**Issue by Tom-Lauerman** [Ultimaker/Cura#126]
I'm excited about the wire print function. However, at present it seems to cause Cura to crash almost immediately after selecting wire print. Several people on the UM forum have found this same problem.

**Comment by nallath** [comment]
@BagelOrb Could you have a look at this?

**Comment by BagelOrb** [comment]
Thanks for communicating this to us. I will dig into it.

**Comment by BagelOrb** [comment]
When I slice using the engine directly I don't encounter any problem.

Supposing that the defaults correspond to the inherited values enough, this is most probably a frontend issue.

Perhaps it has something to do with the fact that the layer height communicated to the frontend is around 1 cm..

@awhiemstra can you take a look at it?

**Comment by BagelOrb** [comment]
Fixed!

**Comment by BagelOrb** [comment]
Can you provide a link to the forum post?

**Comment by Tom-Lauerman** [comment]
Sure, here you go:
https://ultimaker.com/en/community/view/16675-has-anyone-had-any-luck-with-wireprint

Thanks!

**Comment by BagelOrb** [comment]
Thanks
