### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Bocian82** [Ultimaker/Cura#12606]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

U 5S

### Reproduction steps

sliceing model
error

### Actual results

error

### Expected results

g-code

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

dont know what

**Comment by GregValiant** [comment]
Without a project file there is no way to know what is going on.  In Cura, load the model.  Set up to slice.  Use the "File | Save Project" command.  Zip the 3mf file.  Post the Zip file here.
