### ISSUE TITLE
Tradução para o português

### ISSUE THREAD

**Issue by Henryking39** [Ultimaker/Cura#12605]
### Application Version

5.0.0

### Platform

windows 10

### Printer

Tycoon Slim

### Reproduction steps

Ao abrir o Cura, algumas etapas ficam em português outras em inglês.

### Actual results

Quando abro a aba de edição de recursos como por exemplo, ajuste de parede, velocidade, etc.. ao passar o mouse aprece uma descrição de cada item. esses comentários aparecem em inglês mas o Cura está em português no meu computador.

### Expected results

Todos o cura fique em português.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Só preciso que o cura fique por completo em portugês
![Cura](https://user-images.githubusercontent.com/105471847/175776583-c9a77abf-a03f-46c6-92e8-5e248a9f3f25.png)

.

**Comment by fieldOfView** [comment]
It looks like you have the "Settings Guide" plugin installed. It replaces the short tooltip texts that Cura includes with more elaborate texts. Cura itsalef has a translation to portuguese, but the texts for the Settings Guide plugin do not have a portuguese translation, so the plugin falls back to english texts.

This is not an issue with Cura, but with the Settings Guide plugin. It should be reported here:
https://github.com/Ghostkeeper/SettingsGuide/issues
