### ISSUE TITLE
Disable coasting for Ironing

### ISSUE THREAD

**Issue by bbbwex** [Ultimaker/Cura#12610]
### Is your feature request related to a problem?

I use a combination of retraction and coasting on my builds to minimize stringing.

When ironing the top layer, coasting will stop the flow for coasting completely and leave the last part of the surface not ironed out.

### Describe the solution you'd like

I'd like to see a disable coasting option with the settings for Ironing.

### Describe alternatives you've considered

None

### Affected users and/or printers

All printers

**Comment by Joeydelarago** [comment]
Hey we will discuss this. Could you attach a project file where the coasting messes up the end of the ironing? Thank you
