### ISSUE TITLE
wrong extruder temp

### ISSUE THREAD

**Issue by hexxter** [Ultimaker/Cura#1261]
Hi,

cura 2.4.0 set wrong temperatures.
i set 210 in cura it was 215 in the generated gcode. standby temp is always 5 ?

**Comment by BerndJM** [comment]
Have a look at the new parameter "Printing Temperature Initial Layer" that could be the reason for the 215° ...

**Comment by hexxter** [comment]
No this is the result of:
printing temperature 240
initial temperature 240
finale temperature 240
stand by temperature 210

(the second extruder is set to 0 in each field)

`;Generated with Cura_SteamEngine master
M190 S60
M104 S245
M104 T1 S5
M109 S245
M109 T1 S5`

**Comment by hexxter** [comment]
thank you this was the solution.
