### ISSUE TITLE
Marketplace update pausing print intermittently 

### ISSUE THREAD

**Issue by MardellK** [Ultimaker/Cura#12618]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Metal Anet A8

### Reproduction steps

1. Started my print.
2. 10 min into print.
3. Saw that Cura needed some marketplace features updated.
4. Pressed update.
5. Print acted like a install bar percentage pausing and going.
6. pause - print 5 sec. - pause 2 sec. - print 2 sec. - pause 6 sec.  
7. stop update.
8. print operated normal. 
9. Lesson - don't update during a print.

### Actual results

Updating my features in marketplace during a print is not recomended.

### Expected results

I expected my updates to have no affect on the print until I restarted Cura. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Marlin-2.0.x

**Comment by GregValiant** [comment]
@MardellK Thanks for the report.
Were you using USB printing when this happened?

**Comment by Joeydelarago** [comment]
Hello, could you also attach a log file. This will help us understanding the cause of your issue. Thanks
