### ISSUE TITLE
error en el corte

### ISSUE THREAD

**Issue by francum** [Ultimaker/Cura#12613]
### Application Version

5.0.0

### Platform

windows 10 i5 11400f

### Printer

creality ender 3

### Reproduction steps

con cualquier configuración al segmentar sale error de corte.

### Actual results

siempre sale error de corte.

### Expected results

que pueda guardar el proyecto para imprimir.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

no tengo información adicional, tendría que funcionar

**Comment by GregValiant** [comment]
Thank you for the report.  We need a project file to troubleshoot this.
In Cura, bring in the model and get the settings the way you want them, and then use the "File | Save Project" command to create a 3mf project file.  Zip the file and post the zip file here.

There has been a lot of these "can't slice" errors and the more project files and different models we have the better the chance of chasing this down.
