### ISSUE TITLE
Reuse Build Plate Adhesion

### ISSUE THREAD

**Issue by M-ABCDEFG** [Ultimaker/Cura#12616]
### Is your feature request related to a problem?

Greetings

Build Plate Adhesion layer(s) help in increasing parts stability, take time printing, and stuck to build plate unless intentionally removed.

They become useless after printing, unless recycled.
They use a considerable time and plastic.

### Describe the solution you'd like

In case of **planning** to do a number of consecutive prints, only 1 build plate is printed, expanded enough to encompass all the planned prints.

This would add new "Print Sequence" type(s); other than the two "One at a time" or "All at once" options.

"Planning" **sometimes** saves resources.

### Describe alternatives you've considered

While designing, I trying to add a suitable thin base to the model (that I want to print).
That would help in 2 things
1. make Cura expand the brim or raft (or skirt)
2. and would add an additional thin and easy-to-remove elevating soft support base, to remove the print without affecting the rest of the build plate adhesion layer(s).
This way it would be possible to position another model to print over the same build plate adhesion layer(s) that has been already printed (for example a raft).
A print **pause** shall be considered between the models to remove the finished models, to avoid collisions.
Pauses can be for a specified period or absolute till the user resume printing.
An axis offset (usually z axis) is be considered too.

### Affected users and/or printers

Someone who has lots of models to print quickly.
Someone who usually need to print brims or rafts.

Cura shall slice each model in a separate entity, while in fact all prints are on the same g-code file.

If it is somehow considered, printers shall ignore colliding previous printed models before the mentioned pause.

### Additional information & file uploads

Where to add the suggested option?
Adding a new "build plate adhesion" to be skirt/brim/raft/expandable, or a checkbox for and expandable build plate? 
Or better adding a new "Print Sequence" type, for  example called "Planned"?

The first one would  be so appealing, having a new build plate adhesion option!
However, the second one is functionally more suitable.

Have a good time.

**Comment by Joeydelarago** [comment]
Hi, this is a cool idea but this feature is quite complex. I think it is unlikely to make it to the top of our backlog. 

There are a few workarounds you could try. 

1. Print a thin buildplate out of the material you are using and level the bed from that. 
2. Printing your rafts as one model, and then slice your models floating above this and repeat prints.

Good luck!
