### ISSUE TITLE
Adaptive line width incapable of bridging. Need minimum line width clamp option in bridge mode.

### ISSUE THREAD

**Issue by tastyratz** [Ultimaker/Cura#12620]
### Is your feature request related to a problem?

Adaptive line width is amazing and allows for significant line width variances on some nozzle types. Unfortunately, this destroys bridging capabilities. Printing 1.1mm on a 0.6mm e3d nozzle is just fine but can't happen on models with bridging due to the greater line width. The print completely falls apart at bridges.

### Describe the solution you'd like

Adaptive line width has a minimum and a maximum line width setting. I would like to see an option for bridge mode to clamp to minimum configured line width when bridging. This will make for significantly more success with overhangs and bridging without having to disable this incredibly handy new capability.

### Describe alternatives you've considered

You cannot take advantage of wider line widths for faster stronger prints if you need successful overhangs and bridges. I have to run a small width on my part.

### Affected users and/or printers

All users with cura 5.

**Comment by Joeydelarago** [comment]
Hi, have you tried out the "Experimental" Bridge Settings? Increasing the fan speed/reducing the line speed could help with your issue. 

Have you used the same nozzle with successful bridging on earlier version of Cura as well?
