### ISSUE TITLE
Settings Guide Plugin Slowing Cura Significantly 

### ISSUE THREAD

**Issue by molotovgod** [Ultimaker/Cura#12621]
### Application Version

5.0.0

### Platform

Windows 11 Pro

### Printer

Ender 3 V2

### Reproduction steps

1. Install Settings Guide from Marketplace.
2. Run Cura
3. Load model
4. Configure settings
5. Slice
6. Uninstall Plugin
7. Repeat steps for testing

### Actual results

Steps 1-5 make Cura unstable

### Expected results

Uninstalling plugin brings Cura back to normal with no lag, freeze or crash.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is something which was bothering me after the new release and I couldn't figure out why my instance of Cura was extremely slow and not usable until I noticed that by collapsing settings brough back my navigation and slicing to normal without overworking my CPU.
I then uninstalled the plugin which allowed me to continue using Cura as normal.

**Comment by Asterchades** [comment]
While the Settings Guide plugin is made by one of the Cura devs it is maintained separately to Cura. Any issues need to be reported directly to its dedicated repository.

https://github.com/Ghostkeeper/SettingsGuide
