### ISSUE TITLE
Not One Piece

### ISSUE THREAD

**Issue by SolidWorksMagi** [Ultimaker/Cura#1262]
I have a design printing but the components do not connect into one large part in the print ???

![img_6063-20161220-notonepiece-in-cura-e](https://cloud.githubusercontent.com/assets/24598434/21358033/4b65b766-c68c-11e6-8fb6-a1d8557135d3.JPG)

**Comment by nallath** [comment]
Could you view the model in the x-ray view? I think your model is broken. If there are red areas in the x-ray view, it means that this is the case.

**Comment by SolidWorksMagi** [comment]
Hi, 

 

The model .STL file is from SolidWorks … 

 

I actually noticed this problem with other things where components cross each other so CURA makes spaces in those areas rather than seeing them as a solid.  

 

This is from making separate parts in SolidWorks, then assembling them and saving the assembly as a solid part, then saving the solid part as a .STL file.  

 

I've been creating a new crisscross all from one 3D SolidWorks part to see if the mesh becomes one better that way than assembly conversions.  

 

This is weird because I've never had this problem with other GCode generators.  

 

 

 

==============================================================================================
C U L8r,  °|°  Walt Perko  °|°        "Kids ... teach them the good stuff, and they still learn the bad stuff on their own."

http://www.R2Pv1.com/  RoboGuts™

                         "The World Needs a New Economic Model"
==============================================================================================

BillyBotAvatar-2centsStamp-c

            Sent from the Cyber7

**Comment by Ghostkeeper** [comment]
Is there any way in which we can reproduce this?

I don't have SolidWorks, but when I create a piece in OpenSCAD that crosses its own components it doesn't have this problem.

All bets are off when there are internal walls, because it's difficult to determine then what the inside of the component is. In this case, the even-odd rule would make the inside hollow.

**Comment by SolidWorksMagi** [comment]
Hi, 

 

What comes from SolidWorks is a solid.  The slicer turns components hollow.  What it looks like is that the slicer is seeing the individual meshes and turning them into its own separate component again.  

 

 

 

==============================================================================================
C U L8r,  °|°  Walt Perko  °|°        "Kids ... teach them the good stuff, and they still learn the bad stuff on their own."

http://www.R2Pv1.com/  RoboGuts™

                         "The World Needs a New Economic Model"
==============================================================================================

BillyBotAvatar-2centsStamp-c

            Sent from the Cyber7

**Comment by Ghostkeeper** [comment]
How could it see the individual meshes if it is a single solid?

Is there a way I can reproduce this? Perhaps you have a file that we can test with?

**Comment by SolidWorksMagi** [comment]
Hi, 

 

Here's one of the files I was using and getting those odd results;  

http://www.brainless.org/OtherStuff/HelicalVase10.STL 

 

 

 

==============================================================================================
C U L8r,  °|°  Walt Perko  °|°        "Kids ... teach them the good stuff, and they still learn the bad stuff on their own."

http://www.R2Pv1.com/  RoboGuts™

                         "The World Needs a New Economic Model"
==============================================================================================

BillyBotAvatar-2centsStamp-c

            Sent from the Cyber7

**Comment by Ando120** [comment]
There object crosses its own components.

I get that result only when I turn off option: Mesh Fixes > Union Overlaping Volumes.
By default its on.

**Comment by SolidWorksMagi** [comment]
Hi, 

 

So I should have a checkmark on:  "Mesh Fixes > Union Overlaping Volumes"? 

 

 

 

==============================================================================================
C U L8r,  °|°  Walt Perko  °|°        "Kids ... teach them the good stuff, and they still learn the bad stuff on their own."

http://www.R2Pv1.com/  RoboGuts™

                         "The World Needs a New Economic Model"
==============================================================================================

BillyBotAvatar-2centsStamp-c

            Sent from the Cyber7

**Comment by Ando120** [comment]
Yes, then it looks fine in layers view.

**Comment by Ghostkeeper** [comment]
Looking at the file in X-Ray View, as Nallath said, shows that the mesh is not closed:
![helicalvase](https://cloud.githubusercontent.com/assets/2448634/21450932/5b35b80a-c8fb-11e6-9398-a13f21691813.png)

X-Ray View colours everything red where there are an odd number of surfaces behind each other. This means that SolidWorks must've produced meshes that are not water tight or have additional non-water-tight shapes inside the outer shell.

Apart from the Union Overlapping Volumes option, you could also try "Extensive Stitching" under Mesh Fixes.

**Comment by Ghostkeeper** [comment]
It seems to slice fine with default settings in 2.4, by the way. No subtracting from itself.
