### ISSUE TITLE
Incorrect skirt placement - Cura 5.0.0

### ISSUE THREAD

**Issue by Fabbro03** [Ultimaker/Cura#12625]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Anycubic Mega Zero

### Reproduction steps

1. duplicated two objects and separated them
2. sliced

### Actual results

The skirt goes through the objects.

![image](https://user-images.githubusercontent.com/68427968/176185921-a6005d73-0575-4fe9-a298-ea669a34a7bc.png)

### Expected results

A correct skirt placement.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file: [AMZ_supp_tubo-telaio.zip](https://github.com/Ultimaker/Cura/files/9001316/AMZ_supp_tubo-telaio.zip)

**Comment by smartavionics** [comment]
The objects need to be placed flat on the buildplate. As you have it, they are at an angle and so the skirt goes underneath.

After adjusting their orientation...

![Screenshot_2022-06-28_14-32-59](https://user-images.githubusercontent.com/585618/176192009-bd30e0fa-9142-4d23-a44b-fb7dc40be7ce.png)

**Comment by Fabbro03** [comment]
I apologize infinitely, you are right. I tried it and it worked. But there is one thing I don't understand in the rotation without snap.
The piece has the face at a 95-degree angle. So after importing it, I rotate it without snap by 95 degrees. Now to make it flat, I have to either press "lay flat" or I have to re-rotate it, without leaving the left button, at any angle and bring it back to 0°, then it lays it flat. So why doesn't it lay it flat right away, since the second rotation rotate it by 0°?

**Comment by Fabbro03** [comment]
I've just added the pull request (https://github.com/Ultimaker/Uranium/pull/835) to show the decimals of rotation angle, so it can prevent the incorrect rotation of the object that can occur with only the integer display of the angle.

Can it be integrated within the next version of Cura?

**Comment by GregValiant** [comment]
@Fabbro03 I'm going to close the bug report since it appears to have been resolved.  If you feel that is in error let me know here.
As to whether your PR can be implemented for the next version - that would be a question for the Cura Team and the place to ask that would be on the PR page.
