### ISSUE TITLE
Cura 5 Crashing

### ISSUE THREAD

**Issue by cverbrugge** [Ultimaker/Cura#12646]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Loaded a high resolution STL file and was adding support blockers when it crashed

### Actual results

Screens went black, when they came back cura was closed and no error message was shown

### Expected results

Support blockers are added to the model

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

[5.0.zip](https://github.com/Ultimaker/Cura/files/9020977/5.0.zip)

**Comment by JAZ-013** [comment]
I'm having a similar issue.  I think it's something to do with the 3D object rendering.  I get it almost every time I use Cura now and it's **always** when I'm trying to move or rotate a model.  I've stopped using the model modifier slider and use the parameters now as it doesn't seem to cause this issue.

Easiest way I know to consistently cause it to crash is to move one object _through_ another object using the single axis sliders.  When it crashes, my whole screen goes blank.  Sometimes it crashes the graphics so hard that my screen will flicker (even without Cura running) until I reboot! 

If it matters, I'm on a 2022 Dell XPS 15 which has both a Intel UHD Graphics and an Nvidia GeFore GTX 3050 Ti.
