### ISSUE TITLE
Can no longer change SD card while Cura 5 is open. The program becomes very unstable and does not function.

### ISSUE THREAD

**Issue by wizdish** [Ultimaker/Cura#12644]
### Application Version

5.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

In previous versions you could find your slicing settings and then change the SD card to save it.

### Actual results

Cura 5 crashes (disappears and cannot be run without a reboot) or stops functioning

### Expected results

Seamless changes to SD card or save location

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9019404/cura.log)

**Comment by Joeydelarago** [comment]
Hi, I tried this out and I wasn't able to reproduce. Are you properly ejecting your SD cards before removing them?
