### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by antandpets** [Ultimaker/Cura#12657]
### Application Version

the latest version

### Platform

macbook air

### Printer

ender3v2

### Reproduction steps

I put in the file
I resize the object
i generate suports
it crashed

### Actual results

nothing

### Expected results

it should have created the g-code file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

IT JUST WONT WORK

**Comment by nallath** [comment]
Please provide us with logs and the model that caused the issue. We can't help you without it.
