### ISSUE TITLE
when i try to merge 2 objects in some mods (scale, translation, rotation etc) they are merged without these transformations.

### ISSUE THREAD

**Issue by harellevy** [Ultimaker/Cura#12652]
### Application Version

5.0.0beta+1

### Platform

mac

### Printer

ender 3

### Reproduction steps

import 2 objects, move them around, and rotate one of them, then right-click and merge the object when both selected

### Actual results

both object was merged but not in the desired place.

### Expected results

both objects merged in the position i left them.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'll be glad to help if I can deliver more info. tag me.

**Comment by nallath** [comment]
You need to use "group" not merge. Merging ensures that the models have the same origin (eg; the same 0,0,0 coordinates) that they were saved in the file with.
