### ISSUE TITLE
Bug cura bouton

### ISSUE THREAD

**Issue by EliotOnFire** [Ultimaker/Cura#12666]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

J'ai installé la nouvelle version
Ensuite j'ai voulu me connecter
Et aucun bouton lié à Internet ne marcher
Quand je cliquez dessus rien ne se passer
Les bouton sont : 
Se connecter
Crée gratuitement un compte ultimaker 
Ultimaker marketplace 
Ultimaker academy 
Assistante ultimaker 
Poser une question 
Notifier un bug 
Ultimaker.com

### Actual results

Je ne peux pas me connecter

### Expected results

Que je puisse me connecter je puisse utiliser ces boutons

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Je ne peux malheureusement pas mettre de vidéo
Mais la chose qui se passe
C'est juste que quand j'appuie sur les boutons il ne se passe absolument rien

**Comment by Joeydelarago** [comment]
Hello, to help you we need more information. Could you attach your log files?

They can be found here, the file name is "cura.log"
<img width="770" alt="Screenshot 2022-07-06 at 16 44 00" src="https://user-images.githubusercontent.com/23387864/177577866-6d65b493-c0fd-4d44-83e0-a9ecfd07ee05.png">

Merci 🙂
