### ISSUE TITLE
Kallibrierung X-Y versatzt

### ISSUE THREAD

**Issue by MiCroft87** [Ultimaker/Cura#12680]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Starten der Kalibrierung x-y Versatz
2. Korrektur um den Wert der Verschiebung (7)
3. Starten der Kalibrierung x-y Versatz
4. Korrektur um den Wert der Verschiebung (7)
5. Starten der Kalibrierung x-y Versatz
6. Korrektur um den Wert der Verschiebung (7)
7. Feststellen das die Software den versatz einfach nicht korrigiert!!!!!

### Actual results

Frustration

### Expected results

Der Korrekturwert sollte den Versatz ausgleichen. Da der Korrekturwert nicht übernommen wird sind die Ergebnisse ensprechen schlecht auf der jeweiligen Seite an der der Abstand zu gering ist. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Firmware
Version
7.0.3.0
Letzte
7.0.3.0

Ultimaker-221549
Seriennummer: BPP-028508-088696

**Comment by MariMakes** [comment]
Hey @MiCroft87 

Welcome to the Ultimaker Cura Github. 
I'm so sorry to hear that you are struggling with your XY calibration on your S5.
But unfortunately, I cannot help you here 😢 
I'm here to help with Cura bugs and this is a firmware bug. 

Perhaps you can check our support pages?
https://support.ultimaker.com/hc/en-us/articles/360011544899-How-to-do-a-XY-calibration-on-the-Ultimaker-S5

Or if you submit a ticket in our system there is someone happy to help you there.
(Probably also in German) [Click here to submit a ticket.](https://support.ultimaker.com/hc/en-us) 

Good luck with your Dual Extrusion Printjob 💪
