### ISSUE TITLE
minimize window 

### ISSUE THREAD

**Issue by goldjunge91** [Ultimaker/Cura#12687]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Anycubic i3 mega

### Reproduction steps

Start cura (you can try it in sliced view in every view you get it )
Press ESC button

### Actual results

the cura window resize to the last size

### Expected results

nothing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9057414/cura.log)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7499.
