### ISSUE TITLE
New Project dialog box doesn't accept keyboard response

### ISSUE THREAD

**Issue by pmastren** [Ultimaker/Cura#12694]
### Application Version

5.0.0

### Platform

Ubuntu 22.04

### Printer

Ender 3

### Reproduction steps

1. keypress <ctrl-N> to start new project
2. keypress <Y> to respond yes

### Actual results

Does not respond to keypress <Y> - must click <Yes> dialog box with mouse

### Expected results

Accept keypress <Y> as valid response - All prior versions accepted keyboard response

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by Ghostkeeper** [comment]
Tested this on Ubuntu 22.04 in Cura 5.1 and Cura 5.0. Both seem to work fine.

If I've loaded in any model, I can press Ctrl+N to start a new project, at which point the dialogue pops up. Then I can press Enter to accept it (erasing the build plate) or Esc to cancel.

So I'm currently unable to reproduce this issue. Which keys are you pressing in your reproduction steps?
