### ISSUE TITLE
Thingibrowser plugin could not be loaded at startup

### ISSUE THREAD

**Issue by advisorgee** [Ultimaker/Cura#12696]
### Application Version

5.1.0-beta+327

### Platform

macOS Catalina 10.15.7

### Printer

Ender 3 Pro

### Reproduction steps

downloaded and installed latest beta for osx
replaced existing beta
started.
Uninstalled the plugin, restarted Cura
re-installed the plugin from the marketplace, restarted Cura
same error

### Actual results

On startup Cura has a pop up that says:

the plugin Thingibrowser could not be loaded. 

### Expected results

Plugin would load correctly

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![cura-5 1-thingibrowser](https://user-images.githubusercontent.com/5341449/177794088-ee9b9866-14bb-4bb0-b21b-2c49b8c752c1.png)
[cura.log](https://github.com/Ultimaker/Cura/files/9064460/cura.log)

**Comment by ChrisTerBeke** [comment]
Author of the plugin here. Got the same result, it seems to be caused by the `requests` package missing from the 5.1 Beta build. Not sure if this was intentional (maybe all network calls in Cura are now executed using the PyQt network manager?), but I guess this would impact a bunch of other plugins as well.

**Comment by nallath** [comment]
Yeaah, that's our bad. We switched over to a different packaging tool for python that handles imports differently. It's now more automatic, but that also means that we accidentally dropped requests.

**Comment by Ghostkeeper** [comment]
This is fixed for 5.1 stable. Thanks for the report! Lots of plug-ins are still using Requests so it'd be pretty bad if it were missing.

**Comment by ChrisTerBeke** [comment]
Thanks! Only using for one HTTP call still, will probably remove it as dependency soon.
