### ISSUE TITLE
[5.1.0] Impossible to add a custom printer (macOS build)

### ISSUE THREAD

**Issue by Guilouz** [Ultimaker/Cura#12698]
### Application Version

5.1

### Platform

macOS

### Printer

Custom

### Reproduction steps

I want to add a new printer that is not present in Cura 5.1 for an existing manufacturer. I have created all needed files (definitions, extruder, meshe, quality)

I copy my files to:

- "definitions\my_printer.def.json" file to "Contents\Resources\share\cura\resources\definitions" folder.

- "extruders\my_printer_extruder_0.def.json" file to "Contents\Resources\share\cura\resources\extruders" folder.

- "meshes\my_printer.stl" file to "Contents\Resources\share\cura\resources\meshes" folder.

- "quality\my_printer" folder to "Contents\Resources\share\cura\resources\quality" folder.

### Actual results

Printer does not appear in the list of printers from the manufacturer. It's working fine with Cura 5.0.

When I compare my files with others existing files, they looks good. I don't see any changes in the files from 5.0 to 5.1.

### Expected results

Printer appear in the list of printers.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Working fine with Cura 5.0 but not with 5.1. 

EDIT : My files working on Cura 5.1 with Windows build but not on macOS build.

**Comment by Ghostkeeper** [comment]
It also works fine for me. However, you may have added them in a different way.

I added them to Cura's resources directory. In your case on MacOS, that would be `~/Library/Application Support/cura/5.1/`. Not as you say `Contents/Resources/share/cura/resources/`. So I'm suspecting that you may be adding these files inside of the .dmg?

Cura's releases are signed and notarized by Ultimaker. MacOS should check those signatures and then prevent reading unsigned files. If you edit the DMG file, I'd expect that you have to sign the new files, and notarize everything again. That's not really anything we can help you with... Unless you submit these profiles as a PR for us to merge into the next release. You can test them in Cura by adding them to the directory I listed to above (also found by going in Cura to Help -> Show configuration folder).
