### ISSUE TITLE
Slicing a model getting error

### ISSUE THREAD

**Issue by JohnWJ69** [Ultimaker/Cura#12703]
### Application Version

5.0

### Platform

Windows 11

### Printer

Creality 3 PRO

### Reproduction steps

Using Standard Quality 
Loaded Waratah Bowl
Hit Slice

### Actual results

Received message saying
Slicing failed
slicing failed with an unexpected error

### Expected results

Should have slice the model 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by Asterchades** [comment]
Without a project file any diagnostics is impossible. Best guess at this point is that the model isn't manifold or otherwise requires repairs, which you can easily do using the free 3D Builder tool in Windows.
