### ISSUE TITLE
weird start g-code

### ISSUE THREAD

**Issue by goldjunge91** [Ultimaker/Cura#12701]
### Application Version

5.0.0

### Platform

win10

### Printer

Anycubic i3 mega / custom fff printer

### Reproduction steps

i get this problem with marlin as well with reprap flavour.

the redline is end of my start gcode -->G92 E0.0 !

and cura add 2xg92 e0 and g1 e-7 
![image](https://user-images.githubusercontent.com/30201929/177860578-003f104c-ace0-4ab6-84a7-128a9eb56d2c.png)

### Actual results

remove with hand 

### Expected results

dont put it in :D

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

i add a project for recreating this problem
[AI3MSPRO_30_retraction_test.zip](https://github.com/Ultimaker/Cura/files/9066946/AI3MSPRO_30_retraction_test.zip)
t

**Comment by goldjunge91** [comment]
Yes i know its my retraction Length the question is why will the printer start with empty nozzle ? why i can not change this to want i want ? 
> The "G1F2400 E-7" is it retracting before it moves over to start the first extrusion move of the print (the "7" will correspond with your retraction distance setting", once the nozzle is in position, it will then unretract the 7mm and begin printing.
> 
on the right side you see an explanation a little bit of retraction after purging. 
> I am not sure what you are trying to achieve, but I suspect by removing "G1 E-3 F500' from your start gcode, the printer should behave as intended. Currently it is starting the print with the filament physically 3mm further back than it is expecting.
and no after my -3mm retraction i tell the extruder he is on G92 E0 its 0 in in my eyes its have to travel to start position an start to print and not extruded 7mm and then come first filament out so this behavior is in my is total wrong

**Comment by goldjunge91** [comment]
generated gcode without a start code from me 
`;FLAVOR:Marlin
;TIME:1806
;Filament used: 1.62095m
;Layer height: 0.2
;MINX:86.45
;MINY:86.45
;MINZ:0.2
;MAXX:123.55
;MAXY:123.55
;MAXZ:20
;Generated with Cura_SteamEngine 5.0.0
M140 S60
M105
M190 S60
M104 S235
M105
M109 S235
M82 ;absolute extrusion mode

G92 E0  **again why ???**
G92 E0  **again why ???**
G1 F2400 E-7 **again why ???**
;LAYER_COUNT:100
;LAYER:0
M106 S38.2
G1 F600 Z0.475
G0 F3600 X88.977 Y88.979 Z0.475
G1 F600 Z0.475
G0 F3600 X86.451 Y95.608
;TYPE:SKIRT
G1 F600 Z0.2
G1 F2400 E0 
G1 F1350 X86.46 Y94.943 E0.02212`

from posting this lines i the its make sense we pushing back to zero G1 F2400 E0   and my G1 E-3 is the problem.

**Comment by 3Duke3** [comment]
What is the actual issue you are experiencing? From what I can tell, after the printer has done its purge sequence, it moves into position to print the model, but filament does not start extruding immediately as it begins to print, and that's what you want to fix?

Cura cannot read your start gcode and then adjust what it generates to suit. It simple inserts your start gcode before its own gcode. Cura gcode will always start with G92 E0, so you must ensure your start gcode script finishes with filament at the tip of the nozzle, and not further back. I believe Curas "G1 F2400 E-7" is already doing what your trying to achieve with your "G1 E-3 F500"

![image](https://user-images.githubusercontent.com/78054669/177885614-e7f3c22f-1974-4d0a-a632-b7db7c797506.png)

**Comment by goldjunge91** [comment]
> I believe Curas "G1 F2400 E-7" is already doing what your trying to achieve with your "G1 E-3 F500"

Yes you are total right when I slice it without start code and poste my last comment I have understand that’s my fault 😅
