### ISSUE TITLE
Hollow wall (2.3.1)

### ISSUE THREAD

**Issue by Ando120** [Ultimaker/Cura#1270]
Designed wall (>2*nozzle and <3*nozzle ) will be hollow.

Example:
nozzle 0.4 mm and designed wall 1.0 mm 
result is hollow wall with any "wall thickness" value
Also when "wall thickness" value  is bigger than 1.5*nozzle then top and bottom of wall is open too.

Is it bossible to fix or just to know in the future that must design wall thickness >=3 * nozzle or <=2 * nozzle.

***EDIT:  downloaded 2.4 and its fixed there. :)***

**Comment by thopiekar** [comment]
@Ando120 Good news 👍
