### ISSUE TITLE
Support could have a thin, wider base

### ISSUE THREAD

**Issue by d3x0r** [Ultimaker/Cura#12706]
### Is your feature request related to a problem?

I have this model that has a like 1cm overhang, and it ends up needing support; but this one is pretty narrow and small, so it is very easy to knock over. If I lay out several models to print at a time, the move doesn't seem to care what it goes over, and if the filament is hanging just a little from the nozzle it can catch one of these small supports and knock it over.

When the model starts, it paints a flat wider line around the model, it would be nice if a similar patch could be added to the base of supports, I would think this would give it a better chance of not getting knocked over.

I do have a heated bed, so parts do generally stay fairly stuck to the print bed.

### Describe the solution you'd like

An additional thin layer printed under supports for extra 'support' especially if the support is straight and small - a curved support doesn't seem to have as much issue either.

### Describe alternatives you've considered

Only an initial thought.

### Affected users and/or printers

I would think everyone with any printer would be affected.

### Additional information & file uploads

![failure example](https://user-images.githubusercontent.com/1909610/177905622-7d154344-8004-4268-9894-572228cb3c88.jpg)

This is an example, in this case, the right-most support fell off, I paused the printer, and put a peice of plastic to replace the missing 3mm... it's resumed OK.... but the right one should be a regular thin support like the other three to the left.

**Comment by Ghostkeeper** [comment]
Did you try using Conical Support? When using a negative Conical Support Angle, it becomes wider near the base. For most prints I'd say that -3% to -5% is reliable. But for a shallow object such as this you could even consider -20% or something. It's meant to be a solution to this problem, of having tall, thin pieces of support.
