### ISSUE TITLE
"Slicing failed with an unexpected error."

### ISSUE THREAD

**Issue by Yakibb** [Ultimaker/Cura#12705]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Anet A8 Plus

### Reproduction steps

Created a lithophane "pillow" style image, exported .STL

Imported .STL file, adjusted settings, and hit slice. Unexpected error, couldn't slice 3D model for printing.

### Actual results

Nothing. Error persists after reopening file and software.

### Expected results

Program should've sliced the 3D model, then allow me to export to a file for my printer.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by Asterchades** [comment]
Without a project file any diagnostics is impossible. Best guess at this point is that the model isn't manifold or otherwise requires repairs, which you can easily do using the free 3D Builder tool in Windows.
