### ISSUE TITLE
Missing driver (2.3.1 and 2.4 beta)

### ISSUE THREAD

**Issue by Ando120** [Ultimaker/Cura#1271]
I was unable to connect my UM2+ printer with USB untill I installed 15.04.6
Then it installed some "Arduino... " driver. 
After that 2.3.1 and 2.4 is working too.

**Comment by sedwards2009** [comment]
Which operating system and version are you using?

**Comment by Ando120** [comment]
Windows 8.1 pro 64 bit

**Comment by thopiekar** [comment]
Sounds like https://github.com/Ultimaker/cura-build/pull/96 is needed 😃

**Comment by Ghostkeeper** [comment]
Nope, the drivers have not yet been updated.

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.

**Comment by Ghostkeeper** [comment]
The drivers have been updated for 3.1. See https://github.com/Ultimaker/cura-build/pull/140
