### ISSUE TITLE
Measuring Tool not working for me in Preview Mode

### ISSUE THREAD

**Issue by Ergonomicmike** [Ultimaker/Cura#12719]
### Application Version

5.0.1 Beta 304

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

I was trying to measure the distance between two points on a sliced model in Preview Mode.

### Actual results

I can see one dot. But I cannot add another dot, as I can when in Prepare View. (I can link to a video if it would help show the problem.)

### Expected results

The Measuring Tool works in the Preview Mode.  IIRC, it used to work in Cura 5.0 in Preview Mode. But not working for me now with the Beta. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have a fancy GPU card and I can see the Print Head animation thing. So I think that my video system is adequate for Cura.

**Comment by Asterchades** [comment]
While a member of the Cura team developed and maintains the Measuring Tool plug-in, it is maintained separate to Cura. You'll need to address any issues to its repository instead.

https://github.com/fieldOfView/Cura-MeasureTool
