### ISSUE TITLE
5.1.0 beta installs by default over 5.0.0 Windows 10

### ISSUE THREAD

**Issue by KimmoHop** [Ultimaker/Cura#12723]
### Application Version

5.1.0-beta+304

### Platform

Windows 10 Home 21H2, AMD Ryzen 5 4500U with Radeon Graphics

### Printer

based on Ender 3 Pro

### Reproduction steps

1. start 5.1.0 beta installer
2. blindly click OK

### Actual results

5.1.0 beta is installed over existing 5.0.0

### Expected results

5.1.0 would be installed to e.g. 5.1.0 directory by default

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Yes, it shows it's going to install to 5.0.0 directory but if it is not about uninstalling (seems to be history in 5.x?), who reads these ;)
Configuration is in 5.1.0 directory so profiles are not overwritten.

installer with default location
![image](https://user-images.githubusercontent.com/4123150/178133875-964a9073-fc6d-4d99-aad0-9be326141195.png)

install location
![image](https://user-images.githubusercontent.com/4123150/178133746-6cd2ad79-8aee-4fa7-80a6-b547e839837c.png)

app started
![image](https://user-images.githubusercontent.com/4123150/178133772-e30d4ad8-da89-4687-aac0-c6c5f9cdef3e.png)

**Comment by jellespijker** [comment]
Thank you for reporting this, we have this on our backlog in Jira as well.
Devs see: CURA-9459

**Comment by Ghostkeeper** [comment]
Fixed in 5.1 stable!
