### ISSUE TITLE
Add the new Ender printers,  S1, S1 Pro and S1 Plus

### ISSUE THREAD

**Issue by Jim99Bass** [Ultimaker/Cura#12720]
### Is your feature request related to a problem?

No, Love Cura software

### Describe the solution you'd like

Would it be possible to add the new Ender printers,  S1, S1 Pro and S1 Plus under the Creality list of printers.      Thanks, Jim Bass

### Describe alternatives you've considered

The Ender S1 Plus has a 300mm bed, I selected the Ender Max, as it also has a 300 mm bed.   Will see how that works out.

### Affected users and/or printers

 New Ender printers,  S1, S1 Pro and S1 Plus

**Comment by nallath** [comment]
The Ultimaker team doesn't add any printers except for the ones that we develop. For third party printers we entirely rely on contributions from others. More information on how to create these files can be found here https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
