### ISSUE TITLE
2.3.1 - Reports "Printer Not Connected" when printing - but does prints model.

### ISSUE THREAD

**Issue by AlanJonesTriumph** [Ultimaker/Cura#1272]
Mac OS 10.11.1

**Comment by Ghostkeeper** [comment]
Did you happen to be switching wifi networks at the time?

**Comment by AlanJonesTriumph** [comment]
Printer is Prusa I3 - No change to networks -  if the printeris already connected to the Mac via usb port then then when I hit the USB print button it reports printer not connected -but continues and prints the model.

**Comment by Ghostkeeper** [comment]
We've created an internal issue for this one to take a look at this issue for v2.5 or so.

**Comment by Ghostkeeper** [comment]
This was just rejected by our change control board for the reason that it is a third-party printer of which we don't have any way to debug this problem because we don't have the printer model ourselves to test with.
