### ISSUE TITLE
not slicing

### ISSUE THREAD

**Issue by Super0soup** [Ultimaker/Cura#12734]
### Application Version

5.0.0

### Platform

windows 11

### Printer

cr 10 s4

### Reproduction steps

1. All I did was add a couple of files of an iron man helmet
2. I hit slice

### Actual results

 1. it stops and says "slicing failed"

### Expected results

  it should say slicing failed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

  and its with any file i put in cura and click slice it says slicing failed

**Comment by Asterchades** [comment]
Without a project file there's very little that can be done to diagnose this issue.

Typically with 5.0 this is the result of a broken model. Repairing it with an external tool or sourcing a corrected version of the file should allow it to slice successfully. A project file will be required for more specific recommendations.
