### ISSUE TITLE
Se ha producido un error al cortar o laminar el archivo

### ISSUE THREAD

**Issue by P3LUAAAJ82** [Ultimaker/Cura#12759]
### Application Version

5.1 beta

### Platform

Windows 10

### Printer

Creality ender 3 (perfil modificado por mi para la V2)

### Reproduction steps

Al laminar el archivo tarda mas de lo habitual y cuando llega a la mitad de la barra, aparece el error antes mencionado.

### Actual results

no pude laminar el archivo

### Expected results

el laminado del archivo
![err](https://user-images.githubusercontent.com/109251832/178851682-9e31279c-aee2-41fc-8b29-b327fa5d5b80.jpg)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Uploading err.jpg…]()

**Comment by GregValiant** [comment]
Thank you for the report.
Load the model into Cura and set up the profile as you like.  Then use the "File | Save Project" command to create a 3mf file.  You will need to zip the 3mf file in order to post it here.  Without the project file there is no way to troubleshoot this.

**Comment by drakann1** [comment]
[CE3_portalapicero.zip](https://github.com/Ultimaker/Cura/files/9117963/CE3_portalapicero.zip)
tengo el mismo problema al laminar cualquier archivo esto sucedió después de probar la versión beta del 5.1 y regresar a la versión 5.0 de cura.

**Comment by Ghostkeeper** [comment]
Please report issues in English only, since not all developers know Portuguese.

**Comment by drakann1** [comment]
i have the same problem when slicing any file this happened after trying the beta version of 5.1 and going back to version 5.0 of cura.

**Comment by drakann1** [comment]
i have the same problem when slicing any file this happened after trying the beta version of 5.1 and going back to version 5.0 of cura.

**Comment by Ghostkeeper** [comment]
That project file seems to slice correctly for me. Both in the current state for 5.1 (approaching stable) and in the 5.1 beta.
![image](https://user-images.githubusercontent.com/2448634/179531645-cc3f0e32-d2be-4513-990c-14c78a1b0df2.png)
It's a different file than what you produced the original issue with though.
