### ISSUE TITLE
Cura 5.0.0 crashes with multiple monitor

### ISSUE THREAD

**Issue by ftsabrov** [Ultimaker/Cura#12754]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Sliced a model
2. Entered preview mode
3. Used the layer view slider
4. While holding LMB down, slid mouse pointer onto other monitor

### Actual results

Cura crashes, forces the screen to flash black. No error code given.

### Expected results

The slider should continue to scroll through layers as in prior versions of Cura.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9103261/cura.log)

**Comment by nallath** [comment]
Duplicate of #11907
