### ISSUE TITLE
Failed to Slice

### ISSUE THREAD

**Issue by Luv2disc** [Ultimaker/Cura#12756]
### Application Version

5.1 Beta

### Platform

Window 10

### Printer

Creality CR-10

### Reproduction steps

changed some settings under the default "dynamic .16" profile, hit slice and it stated that it failed.

### Actual results

failed to slice

### Expected results

should have sliced the models

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by Asterchades** [comment]
You need to include at least a project file for any diagnostics to be done. As it stands "changed some settings" is meaningless without knowing which settings were changed and what they were changed to.

It's also worth mentioning that simply hitting the checkbox next to the "Log file" option does nothing. You must manually provide your own log and/or project file - the checkboxes are simply a quick way of indicating that they've been included.
