### ISSUE TITLE
Error when slicing

### ISSUE THREAD

**Issue by jwhite** [Ultimaker/Cura#12763]
### Application Version

5.0 B1

### Platform

Windows 11

### Printer

Voron

### Reproduction steps

Loaded this file from the ERCF repository to print

### Actual results

Fails with error.

### Expected results

Should have sliced!

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file is here: https://filetransfer.io/data-package/XqQjidfu#link

Nothing in log related.

**Comment by jwhite** [comment]
Full Release works fine.

**Comment by Ghostkeeper** [comment]
Thanks! Fixed for 5.0 then.
