### ISSUE TITLE
Cura 5.1 beta | Initial Layer Horizontal Expnasion

### ISSUE THREAD

**Issue by hawkeyexp** [Ultimaker/Cura#12775]
### Application Version

5.1.0-beta+304

### Platform

Windows 11

### Printer

Voron 2.4

### Reproduction steps

Slice a object with horizontal expansion of -0.15 for example - is not object dependent

### Actual results

Object expands on negative values which should shrink it and shrinks on positive values

### Expected results

Object should shrink on negative values and expand on positive

Seems to be inverted behavior since beta 1.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Expand on negative value:

![expand](https://user-images.githubusercontent.com/761728/179363460-cd1d6572-77d7-4f39-87fa-9cced135cfa7.png)

Shrink on positive value:
![shrink](https://user-images.githubusercontent.com/761728/179363481-00a33d75-516e-4d31-94a1-8b602518d468.png)

**Comment by GregValiant** [comment]
Thanks for the report.
This will be fixed in the next release.
I'll mark this as a duplicate report and close it.
FYI I believe a couple of variables were inadvertently swapped and that's what caused the problem.
