### ISSUE TITLE
Drop file onto Cura app in MacOS

### ISSUE THREAD

**Issue by bradmcnally** [Ultimaker/Cura#12779]
### Application Version

5.0.0

### Platform

MacOS 12.4

### Printer

Sovol SV01

### Reproduction steps

Drag stl or 3mf file onto Cura in the dock.

### Actual results

Nothing happens

### Expected results

In previous version of Cura, this opened the file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This began happening after I upgraded to 5.0.0

**Comment by Ghostkeeper** [comment]
We could reproduce this in Cura 5.0, but it seems to be fixed in 5.1. We didn't explicitly fix it, but we made fixes for a related issue on Windows that might also have fixed this issue.

Thanks for the report though! We're lucky in this case.
