### ISSUE TITLE
Problem while slicing.

### ISSUE THREAD

**Issue by Wargrog** [Ultimaker/Cura#12787]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Anycubic Kobra Max

### Reproduction steps

Tried to slice model

### Actual results

Model got to ~10% slice, then failed.

### Expected results

Should have sliced just fine.  Supports are enabled, too.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Project File:  https://we.tl/t-HNKWneJp3t

**Comment by Ghostkeeper** [comment]
This has already been fixed for 5.1. We've encountered other models that had the same issue.
Thanks for the report nonetheless though!

Takes a long time to print!
![image](https://user-images.githubusercontent.com/2448634/179505177-04ae31af-d505-4ffc-9ce6-47faf94405eb.png)
