### ISSUE TITLE
Cura 2.3.1 fail to set initial layer speed

### ISSUE THREAD

**Issue by mypeopoly** [Ultimaker/Cura#1278]
Hi guys,

I notice Cura 2.3.1 fails to set initial speed correctly and I found this by observing how my printer moves.

For example, if I set my initial layer to be 5mm/s (as an example)  and print speed at 50mm/s  travel speed at 300mm/s. I found that
first G0 code sets F3000
The G1 starts to print, without set to F300.  thus leaving first layer printing at F3000 (50mm/s)
attached is unedited gcode.
[P_calibrationtarget_solid_fixed-no-initial.zip](https://github.com/Ultimaker/Cura/files/676985/P_calibrationtarget_solid_fixed-no-initial.zip)

**Comment by Ghostkeeper** [comment]
Did you intend to close your own issue? Was it resolved?
