### ISSUE TITLE
extruder offset changeble in GUI

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1279]
Every time you physically change your extruder you will have to set the offset for the 2nd one.
At present you will have to fiddle with the .def.json file.
Can this be done in the GUI?

**Comment by fieldOfView** [comment]
It's on my personal todo list for 2.5

**Comment by maukcc** [comment]
Also: this needs to be set per printer.
So if I have 5 exactly the same printers, the offsets will probably differ per printer

**Comment by maukcc** [comment]
@fieldOfView Any progress on this? source files to test?
it is driving me insane to manually change this every time :)

**Comment by fieldOfView** [comment]
I have no progress on this to report.

**Comment by fieldOfView** [comment]
Progress is here: #1521

**Comment by maukcc** [comment]
this can be closed
