### ISSUE TITLE
Several functions do not reset when the model is deleted

### ISSUE THREAD

**Issue by TMHogenhout** [Ultimaker/Cura#128]
Application Version: 15.05.94
Platform: Ubuntu 15.04 64-bit
Qt: 5.4.1
PyQt: 5.4.1
Display Driver: xserver-xorg-video-intel 2.99.917

Steps to Reproduce:
- Delete a model or clear the build platvorm.

Actual Results:
- The save-button still displays estimated print-time, you can save the old model and the number of layers of the deleted model is displayed. 

Expected results:
- The save-button and layer view go back to their idle-state 
![screenshot from 2015-07-09 16 46 00](https://cloud.githubusercontent.com/assets/12695732/8598534/7518c67a-265b-11e5-839f-ed710086be12.png)

**Comment by nickthetait** [comment]
Just FYI it is spelled "platform" not "platvorm" :grin:
