### ISSUE TITLE
slicing error report

### ISSUE THREAD

**Issue by miragemig** [Ultimaker/Cura#12809]
### Application Version

5.1.0-beta+304

### Platform

W10

### Printer

artillary sw x2

### Reproduction steps

nor slicing error report

### Actual results

slicing

### Expected results

preview slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[ASX1_completo candeeiro1 (1).zip](https://github.com/Ultimaker/Cura/files/9150953/ASX1_completo.candeeiro1.1.zip)

**Comment by GregValiant** [comment]
Using Cura's Mesh Tools Plugin and checking the mesh this window pops up.
![Untitled](https://user-images.githubusercontent.com/64202104/180065534-e5fd5052-0a49-43fd-83c0-9394d16ed655.png)

Along with not being watertight, the model consists of 894 separate meshes.  That being said, it did slice in 5.0.0 and in 5.1.0 with no problem.  I would suggest you move from 5.1beta to 5.1.0.

I don't think it's printable as all those islands will make a mess, and the upper portion is at a severe angle to the build plate and would typically require support.  It sliced but I don't think it is a suitable model for FDM.

![image](https://user-images.githubusercontent.com/64202104/180066343-aa19f9ab-7a07-474c-808d-a21859de33ed.png)

All those islands result in 8810 retractions in the gcode file.  This is layer 271.  The red dashes are what prints on this layer.

![image](https://user-images.githubusercontent.com/64202104/180067315-8d908230-4ae4-4b5c-80df-d84587c1ba23.png)

I'll leave the bug label for now so you can respond.  I can't duplicate your problem, the model has issues, and the model is not really suitable for the FDM process.
