### ISSUE TITLE
Slicing Error at 0.12 layer height

### ISSUE THREAD

**Issue by skoomaeater** [Ultimaker/Cura#12812]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Load Model
Select Super Quality (or any 0.12 layer profile)
Slice

### Actual results

Error
![Screenshot 2022-07-20 133841](https://user-images.githubusercontent.com/21180730/180047085-c250e46f-f66d-4ad9-8de7-8a3b3f9d66aa.png)

### Expected results

Gcode file generation

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9152492/cura.log)
[CrystalDragon_NewLegs_Curled_2.zip](https://github.com/Ultimaker/Cura/files/9152497/CrystalDragon_NewLegs_Curled_2.zip)

This file slices on cura versions < 5 with these settings perfectly.

**Comment by GregValiant** [comment]
Thanks for the report.
I've seen this model before.  It has a lot of errors.
-> Analyzed your file:
--> 12 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 125 Non-manifold edges (?)
--> 183 Inverted faces (?)
--> 59 Degenerate faces (?)
--> 4 Duplicate faces (?)
--> 0 Disjoint shells (?)
After repairing the model in Mesh Mixer or MS 3D Builder it sliced.  This is in 5.1.0.
![image](https://user-images.githubusercontent.com/64202104/180088974-56d83e17-4561-4da7-b341-b67bf23916f5.png)

I'll close this as it is an obvious model error that was preventing Cura from slicing.  If you think that is premature you can still respond here.
