### ISSUE TITLE
Slicing Failed With Unexpected Error

### ISSUE THREAD

**Issue by DirtFarmerIndustries** [Ultimaker/Cura#12810]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

Open file.
Edit parameters.
Slice. 
"Slicing Failed With Unexpected Error"
Reboot PC, Uninstall Cura 5.0.0.
Open file.
Edit parameters.
Slice. 
"Slicing Failed With Unexpected Error"

### Actual results

Slicing fails

### Expected results

Slicing successful, write to drive

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Ottoman.zip](https://github.com/Ultimaker/Cura/files/9151492/CE3PRO_Ottoman.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The model has errors in it.  It would not slice in 5.1.0.
After repairing the model using MS 3D Builder it sliced fine.
I'll close this now as it was a model error.  If you feel that is premature leave a message here.

![image](https://user-images.githubusercontent.com/64202104/180071154-e7bef22a-5840-4063-a3bf-64edce1a03c3.png)
