### ISSUE TITLE
Cura not uploading  print files to moonraker

### ISSUE THREAD

**Issue by cwlksn** [Ultimaker/Cura#12811]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anycubic Mega S

### Reproduction steps

Tried to upload a file to moonraker via cura (works on 4.9.1) but when trying to upload i get dozens of crash report screens and can not click the send report as cura crashes out. This also happens on all recent versions from 4.9.1 onwards, so for me to upload any files i have to go back to Cura 4.9.1

### Actual results

when trying to upload i get dozens of crash report screens and can not click the send report as cura crashes out.

### Expected results

file should upload as per cura 4.9.1 to my raspberry pi klipper using mainsail and moonraker plugin for cura ( all plugins and klipper firmware up to date)
[cura.log](https://github.com/Ultimaker/Cura/files/9151617/cura.log)
[Clockspring3D_Torture_Toaster_v24.zip](https://github.com/Ultimaker/Cura/files/9151633/Clockspring3D_Torture_Toaster_v24.zip)
.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I am curious as to why cura 4.9.1 can upload even after i try on more recent versions.

**Comment by fieldOfView** [comment]
This functionality is not provided by Cura, but by a plugin. Therefore, Cura developers cannot fix this, or answer your question.

You are going to have to take this up with the creators of the Moonraker connection plugin, which I think is this one:
https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/issues
