### ISSUE TITLE
Does not start up on Windows 11 using dual monitor.

### ISSUE THREAD

**Issue by user897943** [Ultimaker/Cura#12823]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anycubic Vyper

### Reproduction steps

Dual monitor on Windows 11 - Nvidia GTX1080

1. Open Cura
2. Cura does not appear, but icon on taskbar says it's running
3. Click icon to bring window to foreground
4. Window flashes, it appears that two windows are stuck outside the monitor area, they briefly appear then disappear

### Actual results

See above

### Expected results

Cura launches and displays as normal. I already disabled "remember window position", makes no difference.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No further info, please request specific stuff

**Comment by jellespijker** [comment]
We can only help you if you provide us with the log and/or project files.

The log file, located at:
- Windows: `%APPDATA%\cura\<Cura version>\cura.log` or usually `C:\Users\<your_username>\AppData\Roaming\cura\<Cura version>\cura.log`
- MacOS: `$HOME/Library/Application Support/cura/<Cura version>/cura.log` (OSX)
- Linux: `$HOME/.local/share/cura/<Cura version>/cura.log`
