### ISSUE TITLE
Cura not responding

### ISSUE THREAD

**Issue by Drzet** [Ultimaker/Cura#12822]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Cura stops responding following loading any model. Multiple formats tested, 3mf, stl ascii and binary
Any action within Cura window results in application freezing for anywhere between few seconds to minutes

### Actual results

Restarting Cura does not solve issue

### Expected results

Normal function

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9162363/cura.log)

**Comment by MariMakes** [comment]
Hey @Drzet,

Sorry that it took us a while to get back to you.
Are you still stuck?

We had a bug in 5.0 that would load STLs slower than you are used to us that has been resolved in Cura 5.1. 
That bug + Autoslice + Arcwelder is pushing your computing power and might cause your freeze.

Can you try to upgrade to Cura 5.1 and disable either AutoSlice or Arc Welder for big models? 
Can you let us know if this helps with your problem? 👼
