### ISSUE TITLE
Font Color in Dark Mode

### ISSUE THREAD

**Issue by MarioM1998** [Ultimaker/Cura#12834]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Sidewinder X2

### Reproduction steps

I switched to Dark Mode

### Actual results

The font remained light gray mainly for Projectnaming and object list
![Screenshot_9](https://user-images.githubusercontent.com/109826181/180542719-ae164111-ff14-482d-b392-ca481370d2b6.png)

### Expected results

The font color for dark mode should be a complementary color to the grayish background. Maybe blue

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It isnt extremely urgen

**Comment by Toddi3D** [comment]
it would be good if you could choose from four or five colors. I would like to take orange

**Comment by Vandresc** [comment]
Hi @Toddi3D , thank you for your report!
Devs, see CURA-9315 for our internal reference.

**Comment by nallath** [comment]
This has already been fixed
