### ISSUE TITLE
Slicing failed.

### ISSUE THREAD

**Issue by lococnc** [Ultimaker/Cura#12847]
### Application Version

5.1.0 beta 304

### Platform

Windows 10

### Printer

Voron 2.4

### Reproduction steps

Open 3mf file. Slice. Slice failed.

### Actual results

Slicing failed

### Expected results

Slicing succeded

.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Files uploaded
[cura.log](https://github.com/Ultimaker/Cura/files/9175140/cura.log)
[CW2_SW1.zip](https://github.com/Ultimaker/Cura/files/9175141/CW2_SW1.zip)

.

**Comment by Vandresc** [comment]
Hi @lococnc , I could successfully complete the slice by using your project file in stable 5.1. 
Please download the 5.1 stable and let me know if the issue still persists for you, if that is the case you can always reopen the ticket. Thank you!
