### ISSUE TITLE
Cura Configuration error bug

### ISSUE THREAD

**Issue by 3nterausername** [Ultimaker/Cura#12848]
### Application Version

4.11.0

### Platform

Windows10, RTX2060 GPU

### Printer

Doesn't matter, AnetA8 or CoreXY diy build

### Reproduction steps

On startup I get a persistent error about a corrupt profile ..titled configuration errors. The problematic profiles have long since been removed but it is still complaining about it ...and wants to reset the entire configuration - removing all printers and profiles ...even the good ones.
![Configuration_Error](https://user-images.githubusercontent.com/102857279/180637827-7ea57b78-94b7-48e3-8a6c-9c09141df737.JPG)
 

### Actual results

The error pops up on each startup - bothers me - but I can just ignore it. 

### Expected results

The error should not be there - since the profiles no longer are. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The jpeg I added should be sufficient.

**Comment by Vandresc** [comment]
Hi @3nterausername, could you perhaps share your configuration folder with us?
