### ISSUE TITLE
(5.1.0) Size of text boxes insufficient for some numbers

### ISSUE THREAD

**Issue by bellzw** [Ultimaker/Cura#12859]
### Application Version

5.1.0

### Platform

64-bit Windows 10 on a Lenovo Yoga

### Printer

BIBO dual

### Reproduction steps

1. Run Cura with Printer Settings plug-in so settings are visible
2. Scroll down to Maximum Speed X, Y, Z, E
3. Change any visible digit
4. Restore the changed digit to its original value by typing

### Actual results

Text boxes show 2997924580, whereas actual values are 299792458000 (default values from fdmprinter), 2 more digits than can be displayed.  If a visible digit is changed and then changed back by typing, rather than using undo, Cura thinks the last 2 digits were removed and thinks there's been a change.  Undo does to work correctly.

Fields as displayed:
![speed of light](https://user-images.githubusercontent.com/51066449/180680064-d3d6b0d6-5bd2-4f45-81b1-b899e384a6c3.png)

Message after changing a digit and then retyping the same digit:
![textbox digits](https://user-images.githubusercontent.com/51066449/180680077-59c0c42e-2595-4c44-9627-c144b4d29849.png)

### Expected results

Text box would show 299792458000, and restoring the number by typing would be equivalent to undo.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Admittedly, there are probably very few, if any, times that a number is legitimately as large as even 10 digits.  However, inadvertent typos do occur.  In this case, it seems likely that Cura is writing the full 12-digit speed of light to the text box, which only is 10 characters wide, then reading the text box and comparing what's read to what is actually stored in memory as a 12-digit number.  It looks like there's more than enough room to show all 12 digits.

**Comment by Ghostkeeper** [comment]
I increased the limit to 12 characters. Thanks for the report!

The numbers are stored as Python integers in memory which don't really have a limit. I think the limit was there to prevent people from causing integer overflows as they are converted to C++ ints for slicing. But we tend to use 64-bit integers anyway (either `size_t` or Cura's own `coord_t` which is `int64_t`).
