### ISSUE TITLE
The program has closed.

### ISSUE THREAD

**Issue by 19vlad86** [Ultimaker/Cura#12853]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anet A8

### Reproduction steps

Launched the program, chose the stl-file. The program has closed.
Launched the program, chose the gcode file. The program has closed.

### Actual results

The program has closed.

### Expected results

Correct work of the slicer

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9175889/cura.log)

**Comment by jellespijker** [comment]
Hi I noticed that the files are located in path with Bulgarian characters in the path, can you check if you can open the file if there are in an location like: `C:\tmp\Level Bed.gcode` ?
