### ISSUE TITLE
Ultimaker Cura 5.1

### ISSUE THREAD

**Issue by Erox77** [Ultimaker/Cura#12879]
### Application Version

5.1

### Platform

win 10

### Printer

biqu b1

### Reproduction steps

Im trying to download some plugins but it keeps loading the word installing forever and at the end dont download the plugin, i've already reinstall the program and restarted my computer but i keel cant download any plugin

### Actual results

n/a

### Expected results

i want to download the plugins

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i'm trying to download cylinder custom support

**Comment by jellespijker** [comment]
We can only help you if you provide us with the log and/or project files.

The log file, located at:
- Windows: `%APPDATA%\cura\<Cura version>\cura.log` or usually `C:\Users\<your_username>\AppData\Roaming\cura\<Cura version>\cura.log`
- MacOS: `$HOME/Library/Application Support/cura/<Cura version>/cura.log` (OSX)
- Linux: `$HOME/.local/share/cura/<Cura version>/cura.log`

**Comment by Erox77** [comment]
Ok, im sorry for that... here it goes
[cura.log](https://github.com/Ultimaker/Cura/files/9223293/cura.log)
.

**Comment by MariMakes** [comment]
Hey @Erox77 , I recognize you and your request from https://github.com/Ultimaker/Cura/issues/13023

Since this is a duplicate, I'm closing this in favor for the other issue. 
You can follow your the progress here: https://github.com/Ultimaker/Cura/issues/13023
