### ISSUE TITLE
Cura bug when slicing

### ISSUE THREAD

**Issue by Corallus-Caninus** [Ultimaker/Cura#12873]
### Application Version

5.1

### Platform

Windows 11

### Printer

Flsun q5

### Reproduction steps

slice

### Actual results

bug reported but didnt slice

### Expected results

slicing as usual (this has never happened till now)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Please let me know how I can help further I am active on github.

**Comment by GregValiant** [comment]
We need something to investigate this.
Load the model in Cura.  Set Cura up to slice.  From the "File" menu select "Save Project".  Zip the 3mf file and post the zip file here.  The model will be inside along with your printer and all your settings.
