### ISSUE TITLE
Plugin Side Bar

### ISSUE THREAD

**Issue by Jaroslav99** [Ultimaker/Cura#12888]
### Application Version

5.1.0

### Platform

windows10

### Printer

CR10S-PRO V2

### Reproduction steps

Plugin Sidebar GUI 4.3.0 not work

### Actual results

![Screenshot_3](https://user-images.githubusercontent.com/63043593/181505738-c99d427a-389f-49bf-bdf4-93361dbcf6d4.png)

### Expected results

Fix plugin

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

not

**Comment by fieldOfView** [comment]
Normally, issues for plugins should go to the issue queues of the respective plugin, not to the issue queue of Cura. The creators of Cura don't maintain the plugins,

In this case, that issue queue is here: 
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues
More specifically, you will find this pinned issue on the subject which also contains a note about Cura 5.1:
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/31

Having said all that, I have pushed a new version of the plugin to the Marketplace early last week, but it is awaiting approval. This new version adds support for Cura 5.1. I'll leave this issue open for Ultimaker devs to find, as a subtle reminder that my plugin needs a review.

**Comment by jellespijker** [comment]
Hahaha 🤣 I love subtle reminders, it was on my todo list for yesterday, but I got distracted (oeh a 🐿️). I will pick this up first thing today 😉

**Comment by jellespijker** [comment]
Plugin is reviewed and Approved. I will close this issue as a subtle reminder for @fieldOfView to now publish the plugin on our marketkplace

**Comment by fieldOfView** [comment]
The new version is available in the Marketplace now. Get it while it's hot.
Thanks for the review @jellespijker !

**Comment by Jaroslav99** [comment]
Hello Aldo,

Friday, July 29, 2022, 10:22:24 AM, you wrote:

> The new version is available in the Marketplace now. Get it while it's hot.
> Thanks for the review @jellespijker !
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
Thanks for help. Have a nice day.

-- 
Best regards,
 Modelkit                           ***@***.***
