### ISSUE TITLE
Crash when slicing; Binding loop detected for property "width"

### ISSUE THREAD

**Issue by aioren** [Ultimaker/Cura#12880]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Anycubic Kobra Max (Chiron profile, updated)

### Reproduction steps

Attempted to slice a [specific file](https://media.printables.com/media/prints/228125/stls/2078803_92ea0bd0-e99f-46d9-b3e6-d83c8ef659a4/apple_planter_3_2.stl), the slicer starts to process but then errors out and asks me to submit a bug report

### Actual results

![error](https://user-images.githubusercontent.com/25991882/181263759-59e6d437-a399-4299-ad6b-41585c56cebd.png)

### Expected results

It should have sliced the model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[AKMAX_apple_planter_3_2.zip](https://github.com/Ultimaker/Cura/files/9199531/AKMAX_apple_planter_3_2.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9199532/cura.log)

**Comment by Vandresc** [comment]
Hi @aioren, I  could successfully slice the model from the project file, so I would advise downloading the 5.1 build, where we fixed some issues related to the slicing errors. Thank you!
