### ISSUE TITLE
slicing bug

### ISSUE THREAD

**Issue by miragemig** [Ultimaker/Cura#12893]
### Application Version

5.1.0-beta+304

### Platform

W10

### Printer

artillary sw x2

### Reproduction steps

slicing with tree support

### Actual results

error slicing stop unuexpeted

### Expected results

tree support preview slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

i´ve printed earlier with normal suppor
[cura.log](https://github.com/Ultimaker/Cura/files/9218455/cura.log)
[ezyzip.zip](https://github.com/Ultimaker/Cura/files/9218483/ezyzip.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I opened your project file in 5.1beta and didn't make any changes.  It sliced fine (took a while though).  It also sliced in 5.1.0.
So I am unable to duplicate the problem.
The model is showing as "Not Watertight" s errors within the model might be a problem on your system.  You could repair the model and try again.  (1 non-watertight edge and 1 inverted face).  You could also try rotating the model on the Cura build plate.  Sometimes with models that have errors that can make a difference.
I'll close this as it doesn't appear to be a Cura problem.  If you think that is premature let me know here and I'll revisit it.
