### ISSUE TITLE
Failed to slice

### ISSUE THREAD

**Issue by Irghen** [Ultimaker/Cura#12895]
### Application Version

5.1.0-beta+304

### Platform

Windows 10

### Printer

Creality Ender-3

### Reproduction steps

1. Opened the program to load previous working print settings.
2. Drag and dropped my file ( `2020CommercialDistrict.stl` ) from windows file explorer.
3. Press slice.

### Actual results

Error dialog appears:
`"Slicing Failed. `
`Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."`

### Expected results

Piece should have been sliced to save the produced g-code.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Model loaded: `2020CommercialDistrict.stl
[BugReport_290722.zip](https://github.com/Ultimaker/Cura/files/9220656/BugReport_290722.zip)
`

**Comment by GregValiant** [comment]
Thanks for the report.
You have to post the project file here so the problem can be investigated.  Load the model and use the "File | Save Project" command and then Zip the 3mf file and post it here.  Without it we don't have anything to work with.
