### ISSUE TITLE
In version 5.0 and 5.1 in the section Materials, the setting temperature for the nozzle disappeared. Now you have to set the temperature in the printer settings.

### ISSUE THREAD

**Issue by balabykov** [Ultimaker/Cura#12903]
### Application Version

5.0  5.1

### Platform

windows 10

### Printer

kingroon kp3s

### Reproduction steps

I set the last Cura and found that there was no heating temperature of the nozzle. There is no "Setting Visibility", but there is no "materials"

### Actual results

nothing

### Expected results

I want it to wor
![Untitled-2](https://user-images.githubusercontent.com/64344514/181872289-5e36efc8-91f3-453d-98b6-02afc2068b0d.jpg)
k

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Untitled-2](https://user-images.githubusercontent.com/64344514/181872632-9cf59ebc-d7ee-40c3-ad3b-acf87116a799.jpg)

**Comment by fieldOfView** [comment]
Please include a link to your log file _and_ a project file. Even with an empty buildplate you can create a project with File -> Save project...

NB: sending in the requested files as an email attachment will NOT work. Please use the github web interface instead:
[github.com/Ultimaker/Cura/issues/12903](https://github.com/Ultimaker/Cura/issues/12903)
