### ISSUE TITLE
overscaling

### ISSUE THREAD

**Issue by sanctum012** [Ultimaker/Cura#12904]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3 S1

### Reproduction steps

Hello,
when inserting a newly created SLT file from Fusion360, the component is displayed in the correct size in Cura 5.0 for about 1 second, but it is then immediately scaled to a huge size. 

### Actual results

However, when I open the same file in Cura 4.8.2, the component is displayed correctly from the start and is also correctly saved in the file as G-code. The 3D print is true to size.
What could be the reason for this behavior of Cura 5.0 and how can this be stopped?

### Expected results

True to scale mapping as in Cura 4.8.2

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Abdeckung Schalter_V2_seitlich.zip](https://github.com/Ultimaker/Cura/files/9225605/Abdeckung.Schalter_V2_seitlich.zip)

**Comment by fieldOfView** [comment]
A log would have been useful to know what is going on, but I think what is happening is that you have set the Mesh Tools option  "Unit for files that don't specify a unit" to something that is not the default `mm`. Setting that to a non-mm value scales all STLs after loading.

Extensions -> Mesh Tools -> Mesh Tools settings... -> Unit for files that don't specify a unit
Also see https://github.com/fieldOfView/Cura-MeshTools/issues/26

Does this ring a bell? Or should we look elsewhere for the issue?
