### ISSUE TITLE
Retraction distance keeps increasing over the course of the print, until it reaches 1,500%

### ISSUE THREAD

**Issue by Tylersuard** [Ultimaker/Cura#12902]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Ratrig V-Core

### Reproduction steps

I just sliced a print using Cura and printed it.  I set the retraction distance to be 5mm, but it keeps getting longer as the print goes on.  By the end of the print the retraction distance is 75mm!

### Actual results

Lots of popping because the retraction distance is many times what it needs to be.

### Expected results

The extrusion distance should be 5mm throughout the entire print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

G1 F3600 E-5

G1 F3600 E-53.00000

**Comment by Asterchades** [comment]
Sounds like you have a post processing script enabled for a stringing test. Look for an icon next to the slice/print/save button with a numbered indicator in the upper right corner (it will be in a red circle).

A project file would go a long way towards helping diagnostics in the event you don't have such scripts enabled.
