### ISSUE TITLE
unable to slice

### ISSUE THREAD

**Issue by vlSharkylv** [Ultimaker/Cura#12912]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

i input a file and it failed to slice. done it with a few different files still the same result, reset my pc no no avail 
![2022-07-31](https://user-images.githubusercontent.com/110333820/182022714-bdecaf97-0aa9-45e2-b92a-ec9375cb5928.png)

### Actual results

still fails

### Expected results

it should slice so i can print the file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by GregValiant** [comment]
We need a project and log file to be able to look into this.
In the Help menu select "Show Configuration Folder".  The Cura.log file will be in there.
Load one of those models, set Cura up to slice and select the "File | Save Project" command to create a 3mf project file.
Zip the log file and project file and post the zip file here.
(There are a lot of models out there with errors in them that keep Cura from being able to slice.)
