### ISSUE TITLE
Custom wall ordering

### ISSUE THREAD

**Issue by fkiliver** [Ultimaker/Cura#12928]
### Is your feature request related to a problem?

Now Cura's choice of wall order is only from inside to outside and from outside to inside.However, in some cases, taking the 3-layer wall as an example, better surface quality can be obtained by using the order of inside-outside-middle.
Like this
|    |    |
|    |    |
|    |    |
2  3  1   (wall ordering)
outside-middle-inside

### Describe the solution you'd like

In the wall ordering option, add a custom printing order for each wall or add a ordering that two sides first and then the middle.
|    |    |
|    |    |
|    |    |
3  2   1   (wall ordering)
outside-middle-inside

Due to the poor extrusion quality at the beginning of extrusion, the extrusion should be started from the inside of the model in advance before extruding the outer wall
### Describe alternatives you've considered

Add an extra lead line inside the model to the outside wall

### Affected users and/or printers

Anyone

**Comment by Vandresc** [comment]
Hi @fkiliver, to me your feature request looks similar to the behavior described in https://github.com/Ultimaker/Cura/issues/11934.  If that is the case then the "center line" green line will always be printed last as it is not the inner wall, so Outside to Inside and Inside to Outside may look indeed confusing.

**Comment by MariMakes** [comment]
We changed the description so hopefully it's clearer what to expect from the wall ordering. 🤞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/11934
