### ISSUE TITLE
Benchy Polypropelene

### ISSUE THREAD

**Issue by cverbrugge** [Ultimaker/Cura#12925]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Attempted to slice a benchy with PP filament

### Actual results

Slice failed with an unexpected error

### Expected results

Slice completes

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="1911" alt="Benchy" src="https://user-images.githubusercontent.com/108478072/182189800-d6722fba-56a0-44ab-b2d1-2f4a94eaf0f7.PNG">
[New Compressed (zipped) Folder.zip](https://github.com/Ultimaker/Cura/files/9235304/New.Compressed.zipped.Folder.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I opened your project file and it sliced as it should.  That particular Benchy is "not watertight" (I think I have the same one).  You can attempt to repair it with Windows MS 3D Builder.  See if that works for you.
I can't duplicate the problem with the project file.  If you could post the cura.log file (in "Help | Show Configuration Folder") that may help a team member figure out what's going on.

**Comment by cverbrugge** [comment]
It is slicing fine now with the same model/settings. Not sure what changed but the issue is no longer happening. Thank you

**Comment by GregValiant** [comment]
No problem.  I will close this now.
