### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by bojangles86** [Ultimaker/Cura#12939]
### Application Version

5.1.0

### Platform

Linux Garuda

### Printer

Ender 5

### Reproduction steps

Tried slicing .stl 
recieved error "slicing failed"
Turned off extensive stitching and tried again.
recieved same error.
most other settings are defaulted besides temps. 
![Screenshot_1](https://user-images.githubusercontent.com/84755778/182644482-fe096de8-3fe7-4074-9735-dda94a9995a8.png)

### Actual results

tried changing settings to default and tried slicing again

### Expected results

expected .stl to slice but get error instead

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9252806/cura.log)

**Comment by jellespijker** [comment]
We really need the 3mf project file as well,l. It will be nearly impossible to debug and reproduce this issue otherwise

**Comment by bojangles86** [comment]
[CE5_Laser_Cat_-_Voronoi_fine.zip](https://github.com/Ultimaker/Cura/files/9255260/CE5_Laser_Cat_-_Voronoi_fine.zip)

sorry i thought i had uploaded this.

**Comment by GregValiant** [comment]
Win10 Cura 5.1.  I opened it and it sliced.
(I would have lost a bet with myself on that as I was sure there would be model errors.)
Will it print?  Now that is a cat of a different color.
![image](https://user-images.githubusercontent.com/64202104/182723739-018f2241-642a-46d0-af92-c1ac2bf6b8af.png)

**Comment by MariMakes** [comment]
I can also slice your project file in Cura 5.1
![image](https://user-images.githubusercontent.com/40423138/186862765-88aeb992-d6b9-4862-8754-4e90e6c41b79.png)

If it's not an issue anymore, can we close the issue?

**Comment by bojangles86** [comment]
Sure. I think it's safe to close now.
