### ISSUE TITLE
Opening project file from browser NOT the same as opening a project file from Cura (tested on OSX)

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1294]
Maybe this is desired behavior, but it feels confusing: 

## Expected, good
When opening a .curaproject.3mf file from Cura (File > Open Project)
- .stl configuration on the build plate loaded
- build plate cleared
- print settings loaded
- open project dialog tells user what will happen

## Unexpected, bad?
When opening a .curaproject.3mf file from a file browser, 
(effectively adding stls, but doing nothing else)
- .stl configuration on the build plate loaded
- build plate NOT cleared 
- print settings NOT loaded
- NO open project dialog

**Comment by Ghostkeeper** [comment]
Ah, hmm, I think it then interprets the file as if it were a normal .3MF file, by the looks of things.

**Comment by filipgoc** [comment]
Makes sense.

**Comment by nallath** [comment]
This has been fixed.
