### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by PRASS1** [Ultimaker/Cura#12945]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anycubic I3 mega

### Reproduction steps

Camera movement.
Using right click to reposition camera.

### Actual results

The camera is now fixed pointing in a direction that is useless.

### Expected results

In older versions you could slide the camera left, right, up & down freely to get up close to any components or far awy to view everything.
In the newest version V5 onwards the camera seems to be fixed pointing to the centre both horizontally & vertically completely without free movement.
This truely sucks as you can no longer look at tiny pieces that are low down or on the edges of the build plate.

Every time you try to zoom in or out it automatically starts zooming to the fixed position & not to the centre point of the image you are looking at.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

In older versions you could slide the camera left, right, up & down freely to get up close to any components or far awy to view everything.
In the newest version V5 onwards the camera seems to be fixed pointing to the centre both horizontally & vertically completely without free movement.
This truely sucks as you can no longer look at tiny pieces that are low down or on the edges of the build plate.

Every time you try to zoom in or out it automatically starts zooming to the fixed position & not to the centre point of the image you are looking at.

**Comment by GregValiant** [comment]
Thanks for the report.
In Cura under the Preferences Menu is Configure Cura.  In the "Viewport Behavior" box are some settings that control the way the zoom control works.  "Zoom towards Mouse Direction" is the main one.
Under "Camera Rendering" are two options.  If Perspective is selected then "Zoom Toward Mouse Direction" should work as you expected.  If Orthographic is selected then the zoom is towards a point in space.  In the Cura main window, if you are set to Orthographic then zooming can send the model out of the frame.  If you click your mouse wheel and hold it down then you can drag the model back to the center.
Let us know if making adjustments in the Viewport Behavior  works for you.
