### ISSUE TITLE
English translations: Which flavor do we prefer? British or US?

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#1295]
I was going through https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fdmprinter.def.json.pot and noticed that we are using "traveling" except of "travelling", which is used in British English.

According to http://writingexplained.org/travelling-or-traveling-difference "traveling" is preferred in American English.

It that correct?

**Comment by Ghostkeeper** [comment]
That's correct. British doubles these kinds of consonants. American uses only one.

We hold with American English though. It has been decided very early in the development of Cura 2 (then called 15.6).
