### ISSUE TITLE
Slice Failed

### ISSUE THREAD

**Issue by jlg0682** [Ultimaker/Cura#12960]
### Application Version

5.0.1

### Platform

Windows 11

### Printer

BIQU B1

### Reproduction steps

Loaded build plate. Selected slice. Slicing failed with an unexpected error. Closed Cura re opened and tried again same result.

### Actual results

Failed to slice

### Expected results

File should slice for printing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

None

**Comment by GregValiant** [comment]
Thanks for the report.
To investigate bugs we need a project file and the Cura log.  
In Cura go to Help/Show Configuration Folder.  The "Cura.log" file will be in there.
With the model loaded and Cura ready to slice use the "File | Save Project" command to create a 3mf project file.
Put those two files into a Zip folder and post the Zip folder here.  (It's a GitHub rule regarding file types.)
