### ISSUE TITLE
Prompted to Update / Create New Profile when opening project; current profile settings are identical

### ISSUE THREAD

**Issue by sityware** [Ultimaker/Cura#12987]
### Application Version

5.1

### Platform

Windows 10

### Printer

CR10

### Reproduction steps

Saved a project
Went through slicing, saved Gcode.
Closed Cura.
Reopened Cura and project.

Prompted to Update or Create New Profile.
I selected Create New Profile.
Switched to previously saved profile.
Prompted to Discard or Keep Changes

### Actual results

Below screenshot showing the changes which are identical between profiles.
![Cura_profile](https://user-images.githubusercontent.com/31103915/183595620-4f4fbc63-8581-43bd-a9b3-f1c088a6f4a4.png)

### Expected results

No prompt should display if profile settings are identical.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All details are above.

**Comment by Vandresc** [comment]
Hi @sityware, unfortunately, I am not able to reproduce the given steps to reproduce. For me, after the [Reopened Cura and project] step, Cura prompts the Open project window and no Discard or Keep window. I assume something went wrong in your configuration folder, could you please share the project file you encounter the issue with and a log file? Thank you!
