### ISSUE TITLE
Custom Seam 

### ISSUE THREAD

**Issue by daviddallaqua** [Ultimaker/Cura#12997]
### Is your feature request related to a problem?

Put a tool where you can manually draw the seam path.

### Describe the solution you'd like

make this 

### Describe alternatives you've considered

no

### Affected users and/or printers

yes

### Additional information & file uploads

no

**Comment by casperlamboo** [comment]
Hi @daviddallaqua, thank you for the feature request. We do have various tickets open on the backlog regarding the seam. We recognise that the generated seams are somewhat inconsistent and we would like to improve this. We expect (hope) that once these backlog tickets are resolved the need for a "drawn-on" seam will be mitigated. But for now we have decided to defer this feature request.

I did think of a work around for drawing on seams; If you can add a small ridge in the model where you want the seam to be, and set you seam settings to "sharpest corner" then the seam will be located in this ridge.
