### ISSUE TITLE
seam random Z problem

### ISSUE THREAD

**Issue by daviddallaqua** [Ultimaker/Cura#12996]
### Application Version

5.1.0

### Platform

Mac

### Printer

All

### Reproduction steps

In CURA 5.1.0. when choosing random Z seam alignment. it does not leave the seam z random.

### Actual results

![Captura de Tela 2022-08-10 às 06 02 56](https://user-images.githubusercontent.com/11407390/183861326-cc170da6-5704-471c-ba48-8de306060ceb.png)

### Expected results

make random seam

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

no

**Comment by Asterchades** [comment]
Fuzzy Skin seems to be interfering with the Z seam at the moment (#12525). With this disabled the Random option should work, but with it enabled the seam location settings appear to do absolutely nothing at all.

Between this and the known seam issues it's reasonably safe to assume that someone is looking into it already.
