### ISSUE TITLE
Cura cannot be uninstalled completely.

### ISSUE THREAD

**Issue by eelcor** [Ultimaker/Cura#130]
Issue affects both Mac and Windows. My windows machine gives an error when starting Cura. This error is the result of a previous crash and is somehow not reset when uninstalling and reïnstalling Cura.

For the Mac I've added a Prusa i3 settings file and somehow it is not found. After reinstalling and trying without the settings file, Cura remembers the earlier settings and throws an error.

This is a pity, because the print I was able to make was really nice!

**Comment by eelcor** [comment]
Okay the Mac issue has been solved by removing the .Cura file from my home dir.

**Comment by awhiemstra** [comment]
We should probably add an option to the windows uninstaller to remove existing settings. Unfortunately this is going to be hard for the OSX installer since I do not know if it has uninstall hooks.

**Comment by eelcor** [comment]
For OSX it suffices to say that you can remove the .Cura directory. For Windows the settings are less transparent. Where can I find these?

**Comment by awhiemstra** [comment]
~/AppData/Local/Cura

**Comment by quillford** [comment]
Mac was an issue for me as well, but you just need to make another json file with the same one as you were using before.

**Comment by BagelOrb** [comment]
It would still be nice to have an option in the deinstaller to delete all configuration files.

**Comment by Ghostkeeper** [comment]
Our project manager just removed this from our planner because it's older than 12 weeks.

**Comment by ianpaschal** [comment]
@Vandrasc Can you put this ticket number in JIRA and add the JIRA number here?

**Comment by Vandrasc** [comment]
Yep, sure can! See CURA-5154.

**Comment by diegopradogesto** [comment]
This is now implemented in the master branch.
