### ISSUE TITLE
fehler beim sclicen

### ISSUE THREAD

**Issue by onkeltrucker** [Ultimaker/Cura#13005]
### Application Version

5.1.0

### Platform

windos 11

### Printer

Anycubic chiron

### Reproduction steps

zeigt beim sclicen immer fehler an 

### Actual results

????
kann kein englisch 

### Expected results

fffff

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

fehler beim Sclicen

**Comment by GregValiant** [comment]
If you would like us to investigate then we need something to investigate.
If you could zip a project file from Cura ("File | Save Project") and post the zip file here it can be investigated.
