### ISSUE TITLE
not posible add material 

### ISSUE THREAD

**Issue by Zedral1** [Ultimaker/Cura#13000]
### Application Version

5.1.0

### Platform

Windovs10

### Printer

Ender3

### Reproduction steps

If i add new material, it is no posible 
Iwould like add PLA, ASA, ABS and PETG it is no posible 

### Actual results

If i start cura software i dont  add material 
it is still freze on ultimaker Red Translucent PET
![Snímek obrazovky (16)](https://user-images.githubusercontent.com/111002148/183966708-15383b56-7cdc-4c97-81c3-a0fe12b6a311.png)
G

### Expected results

how to add material

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9302275/cura.log)

**Comment by Vandresc** [comment]
Hi @Zedral1, could you please provide a project file as well? I need your configuration in order to reproduce the issue. Thank you!

**Comment by MariMakes** [comment]
Hey @Zedral1,

How did you add your 3D printer?
I believe if you add a Creality Ender 3 from the Add Printer list, instead as a custom FFF printer you get a bunch of community-contributed materials. It already has the profiles for PLA, ASA, ABS, and PETG. 
![image](https://user-images.githubusercontent.com/40423138/186891688-51ca597d-352e-4f00-bcf1-aa8bffe2d13c.png)|
![image](https://user-images.githubusercontent.com/40423138/186892196-f49d8162-3fe7-43bc-bbd0-916c19b36ab1.png)

We also have a support page about custom materials 
https://support.ultimaker.com/hc/en-us/articles/360012565000-How-to-add-a-custom-material-in-Ultimaker-Cura-

Can you let us know if this solves your problem? 👼
