### ISSUE TITLE
Prime tower and brim still generate despite 2nd extruder being disabled

### ISSUE THREAD

**Issue by thekojent** [Ultimaker/Cura#13008]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Disable Extruder 2
2. Import models
3. Slice models

### Actual results

Prime tower brim generates, even in areas where the model will intersect it.
![image](https://user-images.githubusercontent.com/75548272/184209514-05ac0c2e-03d2-4121-9fee-960ded5e2d95.png)

Disabling prime tower brim (setting hidden while Extruder 2 is disabled) still generates skirt surrounding area where prime tower would be.
![image](https://user-images.githubusercontent.com/75548272/184209638-5f261b14-daec-4043-b231-07c116ba76ca.png)

### Expected results

Disabling extruder 2 should also disable generation of prime tower related geometry (brim and skirt path)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_Buggy prime tower.zip](https://github.com/Ultimaker/Cura/files/9311104/UMS5_Buggy.prime.tower.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
If you enable Extruder 2 that will make the setting "Enable Prime Tower" visible.  Then you can disable the prime tower and then once again disable Extruder 2.
Let us know if that works for you.
I'll leave this as a bug report.  I should think the Dual Extrusion settings should update when an extruder is disabled.  The developers may have a reason for it to behave the way it does.
