### ISSUE TITLE
Slicing failed with an unexpected error when slicing

### ISSUE THREAD

**Issue by ejblaser** [Ultimaker/Cura#13016]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anycubic Mega X

### Reproduction steps

Imported .stl file
scaled the model
tried to slice

### Actual results

I receive the "Slicing failed with an unexpected error when slicing" error.

### Expected results

Should have been sliced and ready for export.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Thank you.

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and/or log file we can't chase things down.
Load your model, set Cura up to slice, and use the "File | Save Project" command to create a 3mf project file.
In the Cura Help menu is "Show Configuration Folder".  Click on it and it will take you to the folder where "Cura.log" resides.
Zip your project file and the Cura.log file and post the zip file here.
