### ISSUE TITLE
Slincing Fail 

### ISSUE THREAD

**Issue by Queneri** [Ultimaker/Cura#13010]
### Application Version

5.1.0

### Platform

Monterey 12.5

### Printer

Ultimaker 3 Extended

### Reproduction steps

Slicing a heavy mesh density OBJ. (Over 660mb) 

Slicing sometimes fails, close and reopen cura to resolve the issue. 

### Actual results

occasionally the slice fails

### Expected results

Slicing the model with no problem

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1624" alt="Screen Shot 2022-08-11 at 23 35 52" src="https://user-images.githubusercontent.com/54904776/184274690-f4da594f-f25f-466c-a366-55242d5c4cd9.png">

**Comment by GregValiant** [comment]
Thanks for the report.
This cannot be investigated without a Project File.  Load the model in Cura, set up to slice, use the "File | Save Project" command to create a 3mf file.  Zip the 3mf file and post the zip file here.
I will leave this as a bug report but it's quite possible that there are errors in the model.  If you can find a repair utility that can handle a file that large it would be worth a try to repair it.  Sometimes Cura can work around errors in models if the model is rotated on the Cura build plate.
