### ISSUE TITLE
Multicolor 3D Printing Preparation Failures

### ISSUE THREAD

**Issue by alex-samra** [Ultimaker/Cura#13014]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

I am trying to merge two parts in Cura to print in two colors on my Ultimaker S5. I have followed all of Ultimaker's recommended steps seen [here](https://www.youtube.com/watch?v=dxifYhs9Ugg), preparing the files in Solidworks to align on the same coordinate frame and making sure to select this coordinate frame in the options tab on the file export window. 
I bring the files into Cura, highlight them both, and select the merge models option.

First, when I exported in STL, I had parts that were centered on the build plate but dropped down, and merging them resulted in a random alignment with the logo text sticking out of the middle of the cylinder. When I tried 3mf and other file types, the origin reads correctly and places both files in the correct place spatially, but when I merge them it puts a massive gap between them and tilts them to the side for some reason. I have had several coworkers try this export and merging process with different design softwares and filetypes and origin setups, and we all have the exact same issues in Cura no matter what, so it seems to be a Cura-related bug. This is an important capability for my job shop so we need to get this figured out quickly.

### Actual results

First, when I exported in STL, I had parts that were centered on the build plate but dropped down, and merging them resulted in a random alignment with the logo text sticking out of the middle of the cylinder. When I tried 3mf and other file types, the origin reads correctly and places both files in the correct place spatially, but when I merge them it puts a massive gap between them and tilts them to the side for some reason. I have had several coworkers try this export and merging process with different design softwares, filetypes, and origin setups, and we all have the exact same issues in Cura no matter what, so it seems to be a Cura-related bug. This is an important capability for my job shop so we need to get this figured out quickly.

### Expected results

The models should merge in such a way that their origins overlap so that I can print a single model in multiple colors/materials. Yet no matter how I export and ensure the same origin between files to merge correctly, cura seems to spit out a random result with the models being nowhere close to merged properly.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Align4 jpg c9324623fa39297d7fa7cc7d44ac183e](https://user-images.githubusercontent.com/110542679/184404335-faac71a3-f4e6-4f10-9dfc-f125d2c8ba03.jpg)
![Align5 jpg 90e7f1e9bf0915fd9c8d5b3c5338dc98](https://user-images.githubusercontent.com/110542679/184404338-88eaafed-e4e3-4b3c-bbb4-fcff9863b2ca.jpg)
![Align3 jpg baa6e17dba0a3853f75f4d68ced6c2bc](https://user-images.githubusercontent.com/110542679/184404340-8138b0a9-f63e-497c-b28e-77ab00d422bf.jpg)
![Align2 jpg 97bc6d042ba5d487dea1e939dc52872c](https://user-images.githubusercontent.com/110542679/184404343-bce9283d-24ec-4c10-a086-fc9e8e540ba2.jpg)
![Align1 thumb jpg 7e5458adb68a1a4a0c6c2625ab304a8f](https://user-images.githubusercontent.com/110542679/184404344-bb3e6dd4-549c-4bd9-9f7c-2ca3f387a13b.jpg)

**Comment by MariMakes** [comment]
Hey @alex-samra,

Welcome to Github 🎉 
Thank you for opening your first issue with us. 

It's a bit tricky for me to troubleshoot without the actual .stls or .3mfs but I'm going to try! 💪 

First of all, you don't actually need to merge your models to print, it just makes the steps easier so if you load your .3mfs and they end up in the correct position you should be able to slice and print them, the result should be the same. 

Did you design the parts yourself? Which program did you use? Some CAD software will let you export the origin by default others won't. If you designed it as an assembly, did you consider exporting the whole assembly as a .3mf? I've exported whole assemblies in the past from Fusion 360 and once I've loaded them in Cura, they had the correct position and I could still individually address the different solids. 

Can you let me know if this helps? Thank you! 👼
