### ISSUE TITLE
move, scale, rotate blocked when click space(2.4 beta)

### ISSUE THREAD

**Issue by Ando120** [Ultimaker/Cura#1301]
move, scale, rotate,...  command buttons blocked and mixed highlight when click space.
Windows 8.1 pro 64 bit

**Comment by Ghostkeeper** [comment]
Seems like the tool buttons behave like a radio selection and pressing space causes them to select or deselect, which messes up the interface.

**Comment by Ghostkeeper** [comment]
This was just rejected by our change control board for being too minor.
