### ISSUE TITLE
Separate speed for first layer above infill

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#13018]
### Is your feature request related to a problem?

I'm currently optimizing a profile for speed and I noticed that bottom layers and generally layers on top of a flat surface can be printed much faster than layers above infill.
The infill rips the printed line apart when the nozzle moves over it and the material curls up and creates bumps which ruin everything printed on top of this layer.

### Describe the solution you'd like

To mitigate this I would like to print the first top layer above infill at slower speed than the rest of the top layers.

### Describe alternatives you've considered

I could lower the Top/Bottom speed value but this costs a lot of time in large objects and is not necessary for all other layers except the one above the infill.

### Affected users and/or printers

Me and probably lots of others.

### Additional information & file uploads

_No response
![20220813_135504](https://user-images.githubusercontent.com/43012099/184494799-05562ebf-2102-41ba-855e-f1eaedb3bd95.jpg)
_

**Comment by smartavionics** [comment]
See https://github.com/smartavionics/Cura/releases for a Cura variant that kinda provides this feature. It has a setting called Bridge Sparse Infill Max Density that lets you print skin over sparse infill using the bridge skin settings rather than the normal skin settings....

![Screenshot_2022-08-13_14-44-26](https://user-images.githubusercontent.com/585618/184496939-4f9c3d98-5b2d-4788-907e-a6afa6c45011.png)

**Comment by Triangulix** [comment]
> See https://github.com/smartavionics/Cura/releases for a Cura variant that kinda provides this feature. It has a setting called Bridge Sparse Infill Max Density that lets you print skin over sparse infill using the bridge skin settings rather than the normal skin settings....
> 
> ![Screenshot_2022-08-13_14-44-26](https://user-images.githubusercontent.com/585618/184496939-4f9c3d98-5b2d-4788-907e-a6afa6c45011.png)

That looks like a solution. Do you plan to continue maintaining this fork so that it keeps up with Cura's development?

**Comment by Vandresc** [comment]
Wouldn't Top Surface Skin Speed cover your request? Or there is only the layer on top of the infill that you want to decrease the speed for? Will bring it up for discussion with the rest of the team.

**Comment by Triangulix** [comment]
Hi @Vandresc, I could archieve half of the desired result using "Top Surface Skin Layers" with a "Top Surface Skin Speed" greater than the "Top/Bottom Speed" but on one hand I had to manually determine the number of Top Surface Skin Layers, depending on the desired "Top Thinkness" and the resulting number of layers and on the other hand I still had to set the bottom layers to an unnecessarily low speed.

**Comment by MariMakes** [comment]
Hey @Triangulix 

I brought it up to the team and they mentioned that the setting Bridge Skin Support Threshold.
https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/experimental/bridge_skin_support_threshold.md

**Comment by Triangulix** [comment]
Hi @MariMakes 
I didn't know that this feature was alread available in Cura 5.1.

The option "Bridge Skin Support Threshold" seems to have no effect on skin that is printed over infill-filled areas but the option "Bridge Sparse Infill Max Density" does.

This could be a solution for my problem but I have to test that. It is important that the skin layers still fuse to the infill and do not become a bridge that just happens to be over the infill.

**Comment by Triangulix** [comment]
The bridging feature solves the problem.

**Comment by MariMakes** [comment]
Awesome! 🎉 
That's great to hear, thanks for updating us. 
I'll close the issue.
