### ISSUE TITLE
Flow at 25% requested on Anycubic I3 Mega S

### ISSUE THREAD

**Issue by Troudouillet** [Ultimaker/Cura#13025]
### Application Version

5.1

### Platform

windows 10

### Printer

Anycubic I3 mega S

### Reproduction steps

On 5.1, printing not working, very low extrusion flow
Same object, i use 4.13, and printing is OK, same parameters.

### Actual results

Get extrusion flow at 25% requested. So can't print.
I change the buse before thinking about new cura version.

### Expected results

Like on 4.13
It's currently printing the parts, flow is correct.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Flow bug.zip](https://github.com/Ultimaker/Cura/files/9331535/Flow.bug.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
In "Manage Printers" and "Machine Settings" take a look at the Filament Diameter.  I believe yours should be 1.75mm.
Another thing to look at is the "Gcode Flavor".  If it is set to "Marlin Volumetric" then the printer must also be set to Volumetric.  The reverse is true as well...If the printer is set to volumetric and the slicer is NOT set to volumetric then there will be flow problems.
Let us know what you find out.  You could also post a project file and it should tell the story.
