### ISSUE TITLE
cura wont load 

### ISSUE THREAD

**Issue by RioHarding** [Ultimaker/Cura#13024]
### Application Version

5.1.0

### Platform

windows 10

### Printer

creality tempro

### Reproduction steps

stated loading Cura
Loads up to a white screen which stops responding 
software has been uninstalled and reinstalled. and fully deleted
pc restarted 

### Actual results

cura software dosent load and shut dowwn

### Expected results

cura software to load 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads
![image](https://user-images.githubusercontent.com/111185524/184496486-fcb6a044-3edb-44a1-8139-c434983e2445.png)

**Comment by MariMakes** [comment]
HI @RioHarding,

Welcome to Github 🎉 
I'm sorry you can't load your Cura. 

It's going to be a tricky issue to troubleshoot but I'm going to try my best. 💪 
Here are a bunch of questions that might help:
A. Is Cura the only software that isn't loading for you?
B.  Are you running [a compatible operating system for Cura](https://support.ultimaker.com/hc/en-us/articles/360011889579-On-what-operating-systems-is-Ultimaker-Cura-available-)?
C. Did you manage to get other versions of Cura to run on your device in the past? 
D. Do you have any unconventional devices connected to your USB ports while loading?  
E. How long do you have to wait for this screen to show up? 
F. Where did you download your Cura version from?
G. Are you working with multiple monitors? 
H. Did you attempt a complete reset according [to these instructions?](https://support.ultimaker.com/hc/en-us/articles/360013007080-How-can-I-completely-reset-my-Ultimaker-Cura-installation-) 

If your issue has been magically resolved in the meantime can you please let us know?
