### ISSUE TITLE
Cant select any roof settings in Cura 

### ISSUE THREAD

**Issue by ArtSosa** [Ultimaker/Cura#1302]
My problem is basically the title its self i cant select any roof settings in Cura i do not know what i'm doing wrong please help if possible. I'm sure its a silly mistake of user error. Sorry for the inconvenience 

Best regards,
 Sosa

 
<img width="960" alt="cura" src="https://cloud.githubusercontent.com/assets/24923416/21657635/35628258-d291-11e6-8821-e6a39f81aa6b.PNG">

**Comment by fieldOfView** [comment]
You see those "i" icons? Try hovering your mouse over them

**Comment by ArtSosa** [comment]
It say "this setting has been hidden by the values of enable support interface, enable support, support interface extruder, Change the values of those settings to make this setting visable." i have tried but it still does not activate or remove the "i" icon from this setting.

**Comment by fieldOfView** [comment]
Realise that the setting visibilty dialog makes settings visible in the sidebar, it does not change those setting values. "Support Interface" is not visible in your sidebar. If you do make it visible, you will see that its value *in the sidebar* is unchecked. Tick the checkbox in the sidebar, and the roof settings will become visible.

**Comment by ArtSosa** [comment]
Hey it worked thank you so much. =)

**Comment by nickthetait** [comment]
Here's an idea on how we can improve the labeling for this message:
"This setting cannot be displayed until the following settings are visible and enabled: {setting names}."

**Comment by ArtSosa** [comment]
For real @nickthetait  i dont like how that is

**Comment by Ghostkeeper** [comment]
That wouldn't work well for settings that are disabled because other settings are below/above some numeric threshold or because of an enumerated setting, such as settings that are only for multi-extrusion, or on infill density being greater than 0, or dependent on bed adhesion being set to "Raft".
