### ISSUE TITLE
Agregar funciones

### ISSUE THREAD

**Issue by JorgeNadeR1** [Ultimaker/Cura#13031]
### Is your feature request related to a problem?

Al hacer zoom siempre se aumenta o reduce en un mismo punto de coordenada.

### Describe the solution you'd like

Poner la función de zoom en el cursor para que al ampliar o reducir se realice donde este el mismo. 

### Describe alternatives you've considered

Activar o desactivar está opción.

### Affected users and/or printers

Se beneficiaran todos los usuarios.

**Comment by GregValiant** [comment]
@JorgeNadeR1 I'll close this request as it is a duplicate of your #13032 .  Let me know if you are good with that.
