### ISSUE TITLE
Tree Supports not generating for overhang

### ISSUE THREAD

**Issue by jpirok** [Ultimaker/Cura#13033]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Ender 3 V2

### Reproduction steps

When slicing the attached stl with tree supports and the large porting of the object touching the build plate, there is an overhang that does not get a support generated for it during slicing. Slicer is set to generate tree supports touching the build plate. The project file with settings is attached.

### Actual results

![Frame Pre-Slice](https://user-images.githubusercontent.com/2065543/184553601-59bad9c0-e1ae-43b2-9c91-e5fe1f90f880.png)
![Frame Sliced](https://user-images.githubusercontent.com/2065543/184553607-0f5bd453-cde7-46df-bb32-913d6615b109.png)

Notice the unsupported overhang at the top in the second picture.

### Expected results

The overhang at the top of the of the object should have a support generated by the slicer.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Frame.zip](https://github.com/Ultimaker/Cura/files/9334054/Frame.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9334059/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
There are over 70 settings for supports with 5 settings specific to tree supports.
Changing the "Tree Support Branch Angle" to 25° makes a big difference but it isn't the only change you need to make.

I don't see a bug here.  You need to make changes to some of your settings to get tree supports to work with this model.
![Tree](https://user-images.githubusercontent.com/64202104/184558685-22ba091e-ca7d-4400-ba97-9c3d104ca79d.png)

For that model I think Normal Supports do a better job.  If you make the floor distance 2X layer height the bottom will come off pretty easy.  Using tree supports isn't always the best way to print a model.
![Treeless](https://user-images.githubusercontent.com/64202104/184558726-137d5ce9-f2f6-4ad0-9410-655aafd546c7.png)

I'll leave this open so you can comment and remove the Bug label as it appears to be a settings issue.

**Comment by jpirok** [comment]
Got it. Thank you!
