### ISSUE TITLE
(5.1) Crashes when loading files

### ISSUE THREAD

**Issue by sebastlamon16** [Ultimaker/Cura#13049]
### Application Version

5.1

### Platform

Windows 10

### Printer

Creality CR-10s

### Reproduction steps

1. Tried to open any slt or gcode files using various methods (drag, right click/open with, open file from within cura)
2. Tried restarting computer
3. Tried reinstalling cura

### Actual results

Starts to load the files then promptly crashes

### Expected results

Showing me a pretty little 3d model in the middle when loading a file would be a good start and "not crashing" would also be in expected results range.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

This is following a update from 4.7 to 5.1 which was also it's own little pain to deal with. In the end uninstalling every versions then deleting anything remotely affiliated with cura and finally reinstalling it did the trick.

I do not have either chitubox or octoprint on my PC which looking online seems to be the only cause for my problem people have found
[cura.log](https://github.com/Ultimaker/Cura/files/9354604/cura.log)
.

**Comment by Vandresc** [comment]
Hi @sebastlamon16, could you also share a project file? Logs don't really show anything weird explaining your issue. Thank you!

**Comment by sebastlamon16** [comment]
Well here's a project file of nothing, since loading anything else makes it crashe it's all i can give really

[project file.zip](https://github.com/Ultimaker/Cura/files/9382724/project.file.zip)

**Comment by sebastlamon16** [comment]
Ok, im just not 100% sure which file exactly you want is it this one?

[cura.zip](https://github.com/Ultimaker/Cura/files/9384276/cura.zip)

**Comment by Vandresc** [comment]
Ah sorry, I was thinking more of the 5.1 folder found in C:\Users\name\AppData\Roaming\cura, where you store all your user changes, machine definitions, custom profiles, and everything related to top user changes. I hope that replacing my config with yours will bring Cura to a state where I can reproduce the issue.

**Comment by sebastlamon16** [comment]
Aaah I see, there you go then.
[5.1.zip](https://github.com/Ultimaker/Cura/files/9399469/5.1.zip)

**Comment by MariMakes** [comment]
Hey @sebastlamon16,

I took a look at your configuration folder and your logs and I don't see anything odd.
When I load your configuration and a model I don't get a crash. 😞 
![image](https://user-images.githubusercontent.com/40423138/187486623-5dbd134d-456b-4d9d-b78e-0822aca95da8.png)

It's a shot in the dark, but could it be related to a Nahimic Audio Driver as described here?
https://www.youtube.com/watch?v=XW-E1P6Ms4s

**Comment by sebastlamon16** [comment]
I looked at the video but sadly it doesn't seems like i have Nahimic audio on my pc, nor do i use a second monitor for the that matter. I think i will just have to revert to Cura 4 for the time being. Thanks for the help.

**Comment by MariMakes** [comment]
Thanks for the update. 
I wish we could help you better 😞 
But I'm glad that you can still use Cura 4.x
