### ISSUE TITLE
"Slicing failed" error

### ISSUE THREAD

**Issue by Triffen** [Ultimaker/Cura#13048]
### Application Version

5.1.0 appimage

### Platform

Linux Manjaro, KDE Plasma

### Printer

Ender 3 v2

### Reproduction steps

Added models, changed some settings, covered some models with a support blocker, tried to slice.

### Actual results

Got an error on the screenshot.
Tried to reverse all the steps but still won't slice.

### Expected results

Should have sliced.

There is no way to save a project in Cura 5+ appimage, no dialogues for saving or opening are working so can't add the project and it has proprietary models anyway.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![SlicingError_2022-08-16_12-59](https://user-images.githubusercontent.com/4696816/184854996-3a4a7f57-0fa0-4702-978f-154a8e475cd3.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We can't do anything without a Project file ("File | Save Project") and the cura.log file ("Help | Show Configuration Folder").
Zip those files and post them here and someone will take a look.
