### ISSUE TITLE
Spiralize outer contour does not appear to use wall speed correctly

### ISSUE THREAD

**Issue by pufferfish-tech** [Ultimaker/Cura#13054]
### Application Version

5.1.0-beta+304

### Platform

Windows 10

### Printer

FLSUN V400

### Reproduction steps

If you crank the speed up to 300 (yes, this is a real speed! :) ) then the wall speed still seems to be around 40-50. I'm not sure where this is coming from since I've increased all speeds to test. 

### Actual results

You get a much lower speed. It seems like maybe there is a speed limit around 50-60mm/s
[FV_001_60mm_solid.zip](https://github.com/Ultimaker/Cura/files/9359627/FV_001_60mm_solid.zip)
 

### Expected results

I would expect the vase mode wall speed to be = the outer wall speed. 

![image](https://user-images.githubusercontent.com/58510167/185131150-b0d79ed4-daca-4707-8e58-378c4e80c2ab.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

see attached images. 
With spiralize off, the wall speed is correctly set: 
![image](https://user-images.githubusercontent.com/58510167/185140437-888cb096-9aeb-4b1e-bee6-f738f2fc50aa.png)

Can also reproduce on 5.0.0

**Comment by smartavionics** [comment]
Perhaps you have too large a value for Minum Layer Time?

**Comment by pufferfish-tech** [comment]
> Perhaps you have too large a value for Minimum Layer Time?

spot on! Thank you! 
![image](https://user-images.githubusercontent.com/58510167/185162772-bae31c3f-dab4-4595-a50f-aa82181f758d.png)
