### ISSUE TITLE
Cura does not migrate settings between versions

### ISSUE THREAD

**Issue by skorokithakis** [Ultimaker/Cura#1305]
I just installed Cura 2.4.0 beta, and it seems that none of my settings were preserved. Given that I had already set up materials, printers and presets, this is a major inconvenience. Cura should have a migration function that will change my settings to the new format, if necessary.

**Comment by Ghostkeeper** [comment]
We have a migration function. It seems to be somewhat broken though. It's on our list of blocking issues for the actual release of 2.4.

**Comment by skorokithakis** [comment]
Ah, thank you, if there's a "migration option is broken" ticket, please close this one.

**Comment by Ghostkeeper** [comment]
Well, it is the cause of #1289 and #1283, but those don't have exactly the same symptoms as you.

**Comment by skorokithakis** [comment]
Hmm, right. Yes, mine was slightly different, although I can't tell if the settings weren't preserved because of a crash...

**Comment by nallath** [comment]
I think this has been fixed (as it was a blokcing issue). So this can be closed.
