### ISSUE TITLE
error al cargar segmentar archivo convinado para impresion en 2 colores

### ISSUE THREAD

**Issue by elsama** [Ultimaker/Cura#13053]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

hellbot magna 2 230

### Reproduction steps

1

2

### Actual results

1

### Expected results

1

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

captus

**Comment by MariMakes** [comment]
Hey @elsama ,

We don't have enough information to troubleshoot your bug. 
Could you please fill in the form correctly and include the file that is crashing for you?

Thank you!
