### ISSUE TITLE
Support blocker > overlap > infill mesh only  > infill density dont work at version 5 and up.

### ISSUE THREAD

**Issue by widyahong** [Ultimaker/Cura#13059]
### Application Version

5.0.0 and 5.1.0

### Platform

Windows 11

### Printer

Creality Ender 3 Pro and V2

### Reproduction steps

1. Add Support blocker to 1 model.
2. Config the per model setting to mesh type overlap infill mesh only.
3. Add infill density, example i add to 100% infill density.

### Actual results

Nothing happen.

### Expected results

Normally the infill will 100% solid box at support blocker size, and the skin will not affected.
**At cura 4.x.x its work fine.**

For now i using cutting mesh for alternative but the skin will show up the solid box support blocker.

Its not a big deal i know.
But this feature good for hardening some section like hinge i made.

And i have 1 more bug, Move function doesn't work when directly entering the desired location number, even though 1 click is enough to block existing numbers but it doesn't work, so I have slide mouse to block all manually first and enter the numbers after that it will work.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

1  add blocker and setup overlaps infill mesh only to infill density 100
![1  add blocker and setup overlaps infill mesh only to infill density 100](https://user-images.githubusercontent.com/95664559/185246640-4c9a6bd9-e356-42b9-b495-6fbca7c40b2c.png)
2  after slicing nohing happen
![2  after slicing nohing happen](https://user-images.githubusercontent.com/95664559/185246651-1e915a7d-98df-462f-ad92-80bdc620808e.png)
3  the result in middle layer if i using cutting mesh
![3  the result in middle layer if i using cutting mesh](https://user-images.githubusercontent.com/95664559/185246658-87add47f-f4d4-4843-97ab-d2a9a59a00da.png)
4  the result if i using cutting mesh but the support blocker show up on skin
![4  the result if i using cutting mesh the support blocker show up on skin](https://user-images.githubusercontent.com/95664559/185246671-3ce3c6cb-0c60-422a-99d3-ff792fcb3200.png)
additional: the move tool selection number block bug
![the move tool selection number block bug](https://user-images.githubusercontent.com/95664559/185246683-38c7ba4f-2e91-4b08-befe-b2f11071f4de.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We will need a project file.
With your model loaded in Cura and Cura set up ready to slice use the "File | Save Project" command.  You will need to Zip the 3mf project file and post it here.  Without knowing how you are set up and without the model these things can't be investigated.
