### ISSUE TITLE
Cannot slice

### ISSUE THREAD

**Issue by Tyrell63** [Ultimaker/Cura#13065]
### Application Version

5.1

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

loading stl
auto orientation
slicing (with support)

### Actual results

slicing failed

### Expected results

store the file on sd card and print

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

![cura-error](https://user-images.githubusercontent.com/37303017/185546938-9b1e3886-04e6-4c73-aec6-8bef428db036.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file we can't investigate.
Load the model and set Cura up to slice and then use the "File | Save Project" command to save a 3mf project file.
Zip the file and post the zip file here and someone will take a look.
Have you checked the model for errors?  You can use MS 3D Builder for that and to repair it if necessary.
