### ISSUE TITLE
Failed to slice

### ISSUE THREAD

**Issue by BoogerX** [Ultimaker/Cura#13086]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Creality Ender 5Pro

### Reproduction steps

Cura will not slice model.

### Actual results

Still will not slice

### Expected results

??

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE5_Baby_Groot_Planter.zip](https://github.com/Ultimaker/Cura/files/9389247/CE5_Baby_Groot_Planter.zip)

**Comment by MariMakes** [comment]
Hey @BoogerX,

Welcome to Github and for thank you for your report 🎉 
I'm also having a failed slice with your .3mf but I can successfully slice it with the default settings. 
So it might have to do with the combination of a few settings. 

![image](https://user-images.githubusercontent.com/40423138/186920781-8a5843a0-967d-486e-9ef3-09fe502e8b2c.png)
![image](https://user-images.githubusercontent.com/40423138/186921097-2e55b494-6fc6-4a15-9ff5-506c65c29d29.png)

We'll have to do some closer investigation. I'll keep you up to date 💪

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/ed67b68d-41f1-4d31-bd50-015343351631)
