### ISSUE TITLE
MJK

### ISSUE THREAD

**Issue by ZTPack** [Ultimaker/Cura#13085]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

but my project what i wanted to print 
then press slice it 
then it said it has a bug 

### Actual results

i been trying to slice my project it aint working 

### Expected results

its been rejecting it saying there is a bug

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

cant do that

**Comment by Asterchades** [comment]
Without a project file, or at the very least a log, no diagnostics can be done on this. Hitting the checkbox is to indicate that you _have_ included one file or the other but doesn't actually attach anything - it must be attached manually, following the instructions which were present when posting your report.

Note that attachments only work via the web interface. They cannot be uploaded via an email reply.
