### ISSUE TITLE
Slicing failed with an unexpected error. Please consider reporting a bug.

### ISSUE THREAD

**Issue by eteojedi** [Ultimaker/Cura#13099]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

S3

### Reproduction steps

Clicked slice

### Actual results

Gave error

### Expected results

Slice, preview, print

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9402282/cura.log)
I was unable to upload my project file...

**Comment by MariMakes** [comment]
Hey @eteojedi,

Welcome to the Ultimaker Github! 🚀 

I can see the crash in your logs, but unfortunetly I cannot help you without your .3mf file. 😢 

The easiest way to share your .3mf is by changing the .3mf to .zip.
Like this:
https://user-images.githubusercontent.com/40423138/187241039-2a9f0685-958f-4152-84ff-3fed24bed3d8.mp4
If it's too big for even that, you can also share a link from WeTransfer. 

Just be mindfull that you open Github in your browser to share your file, just replying to the email is not enough.

Thank you! 👼
