### ISSUE TITLE
stops responding

### ISSUE THREAD

**Issue by middlechamber** [Ultimaker/Cura#13092]
### Application Version

5.1

### Platform

wndows 10 or 11

### Printer

Creality Ender 3 Pro

### Reproduction steps

I print through MY PC as I also work with Laser Engravers usually at the same time, and have been for over 4yrs. When I use ver 4.4.1 I can setup a print hit print and the printer activates & prints with no problem. While that is printing I usually set up another print file to do when the first is done. Again with no problem.
When I use 5.1 opening takes longer, I can load a file & make adjustments & many times it STOPS REPONDING and a prompt shows up on the top bar "Not Responding", screen goes white & I have to shut down.so I revert back to 4.4.1. to make my print.
OR if it does start printing if I try opening another file to print, it will Stop Responding I can let the print finish and it may comeback but by then I usually will revert back to 4.4.1 after that file is finished.
If I went to the marketplace while it was printing it will Stop Responding. 
If I try to load another file to print with the first it usually Stops Responding.

### Actual results

I revert back to 4.4.1

### Expected results

I want it to work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have been using Cura starting with Ver 3.6 and have downloaded new versions as they are released. Any version after 4.8  I get the prompt. "Not Responding"

**Comment by MariMakes** [comment]
Hey @middlechamber,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

Are you still running into this issue with Cura 5.2.1?

The next time you encounter this, could you share your log files with us? 
That would help us with troubleshooting. You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
