### ISSUE TITLE
Modify G-Code - Filament Change - Z Position not working

### ISSUE THREAD

**Issue by cutmoney** [Ultimaker/Cura#13109]
### Application Version

5.1.0

### Platform

macOS 12

### Printer

Ender 3 Pro

### Reproduction steps

I'm using the Modify G-Code - Filament Change - Z Position (with firmware settings). The firmware filament change works, but the Z Position has no effect whatsoever. Printer parks at the same Z position as where it stopped, which obviously causes an issue if it's close to the bed.

### Actual results

See above. Z position has no effect.

### Expected results

Z position should move prior to filament change.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing additional.

**Comment by MariMakes** [comment]
Hey @cutmoney,

Welcome to the Ultimaker Cura community! 🎉 

In my experience is the pause at height way more effective for the filament change purpose. 
![image](https://user-images.githubusercontent.com/40423138/187437517-4d85423d-4a77-4467-98f1-eb6f26e911ac.png)

Can you try it out and let me know if it works for you?
Thank you! 😄
