### ISSUE TITLE
crash 5.1 cura

### ISSUE THREAD

**Issue by Daman877** [Ultimaker/Cura#13107]
### Application Version

5.1

### Platform

windows 11

### Printer

creality cr 10 v3

### Reproduction steps

slicing a figure

### Actual results

same issue

### Expected results

successful slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment]
Hey @Daman877 

Welcome to Github! 🚀 

To help you troubleshoot I need at least your .3mf file, but preferably also your logs. 

To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files.

A cura.log file can be found  from the application menu in Help -> Show settings folder

Be sure to not just reply to this email but open Github in your browser. 

Thank you 😄
