### ISSUE TITLE
Cloud Sync

### ISSUE THREAD

**Issue by claell** [Ultimaker/Cura#1310]
Since Ultimaker already uses accounts it would be cool to sync profiles etc. to the Cloud so one could use them on different machines.

**Comment by claell** [comment]
Could you add an explanation why?

**Comment by ianpaschal** [comment]
Sorry, I should have explained.

Because we don't plan on adding this sort of feature for the foreseeable future. Also, if it does, there will be another repository where this sort of thing should be. But it's not going in Cura.

**Comment by claell** [comment]
Ok, originally I was looking for having the reason for why you are not planning this explained :smiley: 

Probably it is too much effort to set up a cloud endpoint for this compared to the possible benefits from it?

**Comment by ianpaschal** [comment]
Essentially yes. Even now most of our users only have 1 or 2 machines and Cura Connect does a fairly good job at letting a user manage them from one place. I realize that's not the same as managing the settings from multiple computers but we've been working on that in other directions than a cloud service for settings.

**Comment by Ghostkeeper** [comment]
If you want a workaround, setting up a symlink to Cura's configuration folder from a network drive or Dropbox or something seems to work all right if all computers have the same operating system. If they don't, you need multiple symlinks and a reasonable knowledge of where Cura's settings are stored.

**Comment by claell** [comment]
Yes, that would do the trick. Just wanted to have an easy and convenient way for this.
