### ISSUE TITLE
Slicing failed on changing infill overlap percentage

### ISSUE THREAD

**Issue by the-real-loondawg** [Ultimaker/Cura#13114]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

With attached project file, changed infill overlap percentage to 10.0%. 

[CE3PRO_tidy_cat_funnel.zip](https://github.com/Ultimaker/Cura/files/9424839/CE3PRO_tidy_cat_funnel.zip)
.

### Actual results

Received an unexpected error slicing. Cura asked me to report a bug. Same file with infill overlap percentage set to 0.0% slices without error

### Expected results

Slicing with out unexpected error.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

NA

**Comment by MariMakes** [comment]
Hey @the-real-loondawg,

Welcome to Github! 🚀 

I took a look at your file and I'm having the same slicing error. 
![image](https://user-images.githubusercontent.com/40423138/187442556-104e86c6-52e5-42f8-8b43-369b7f389c49.png)
Thanks for sharing! 

I'll bring it up to the team for further investigation 🔍

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/f363b2db-bc68-4403-9863-e463fbec512c)
