### ISSUE TITLE
can not run cura from source

### ISSUE THREAD

**Issue by KrIsChUnn** [Ultimaker/Cura#13125]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Ultimaker S5

### Reproduction steps

I download all necessary requirements as the file asked. but when I operating as the website(https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source) says, Error appeared.

### Actual results

the error message was:
ERROR: Conan v2 incompatible: Use 'self.cpp_info.build_modules["<generator>"] = ['lib\\cmake\\protobuf\\protobuf-generate.cmake', 'lib\\cmake\\protobuf\\protobuf-module.cmake', 'lib\\cmake\\protobuf\\protobuf-options.cmake']' instead

### Expected results

there should be no errors.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

please help me about it.

**Comment by jellespijker** [comment]
Please pass the complete output of the `conan install` command. This is to little information for us to help you with.

**Comment by KrIsChUnn** [comment]
thank you for your reply, here is the output of the conan install below.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/94164027/186846428-925e53e4-b386-4228-8f7d-b13e86fcc80b.png">
![image](https://user-images.githubusercontent.com/94164027/186846519-46e19d1f-cf49-4452-8199-d7fdf09bf57a.png)
![image](https://user-images.githubusercontent.com/94164027/186846572-f727b9a9-e5fa-43ed-9311-3cef1829cadd.png)
![image](https://user-images.githubusercontent.com/94164027/186846639-19560376-ecd3-48ef-b849-3d0cb2faf6db.png)
that's all outputs.

**Comment by MariMakes** [comment]
Hey @KrIsChUnn,

Just wanted to say Welcome to the Elite Running from Source Club 👑 
I can't say that I reached that tier yet 😉 

I just know that we recently updated our wiki regarding running from source.
https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source
Maybe it holds the answers you need. 

@jellespijker can you take a look at the output, please?

**Comment by jellespijker** [comment]
Hi @KrIsChUnn did you set the `CONAN_V2_MODE` variable in your environment by any chance? If that is the case can you check what happens if you remove that variable from the Environment?
https://docs.conan.io/en/latest/reference/conan_v2_mode.html

Alternatively you can also remove the protobuf package from the local conan cache and try for it to download the latest recipe.
```powershell
conan remove protobuf -f
```

**Comment by KrIsChUnn** [comment]
Hi @jellespijker ,I reinstalled  Win11 in my pc and do as the Running from Source says, it happend to be successful. However the error with PyQt6 comes after. I'm gonna to deal with it according to Issues commited by others. Thanks a lot for helping me !

**Comment by jellespijker** [comment]
Hi @KrIsChUnn thanks for letting me know. Good to know that your issue has been resolved. Sad to know that you run into #12773 . But keep following that thread, we're working on that
