### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by ekos2001** [Ultimaker/Cura#13137]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender-3 Pro

### Reproduction steps

I tried to slice a file generated in the OpenSCAD. It can be sliced in the 4.12.1, but not in the 5.0.1
 

### Actual results

Slicing failed message appears

### Expected results

Successful slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_orchid_pot_base_large.zip](https://github.com/Ultimaker/Cura/files/9438329/CE3PRO_orchid_pot_base_large.zip)
[cura.zip](https://github.com/Ultimaker/Cura/files/9438364/cura.zip)
![7wtL7CdJfy](https://user-images.githubusercontent.com/12628077/187040724-7ca3ea5f-aa2f-4f60-9231-67176dfcf3de.png)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
