### ISSUE TITLE
Slicing Failed - Unexpected Error

### ISSUE THREAD

**Issue by LordBlam** [Ultimaker/Cura#13133]
### Application Version

5.1.0

### Platform

Apple Mac 12.4

### Printer

Reality CR-10S

### Reproduction steps

I loaded the commercially-produced STL file "Mimic House-Base-v1.1.stl" which is produced by Printable Scenery (https://www.printablescenery.com/product/mimic-house/).  Using my normal settings, I get an Unexpected Error and failure around 15% of the way through the slicing process.  

Cura 4.13 can slice the file without error using slicer settings which, given the software revision, are as close as can be arranged.

Project file exceeds Github upload limit.

[cura.log](https://github.com/Ultimaker/Cura/files/9435022/cura.log)
 

### Actual results

Unexpected error dialog, slicing stops.

### Expected results

A toolpath file for my 3D printer should have been created.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by MariMakes** [comment]
Hey @LordBlam,

Welcome to the Ultimaker Github 🚀 
We cannot troubleshoot your issue without your project file. 😞 
It contains your printer and profile settings.

Can you share your project file with us? 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites. Please remember, G-code files are not project files!

Also keep in mind to open Github in your browser and not simply reply to this email if you want to attach files.

Thank you 😇
