### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AlgenGruetze** [Ultimaker/Cura#13139]
### Application Version

5.1.0

### Platform

Windows 8.1

### Printer

Ai3 Mega X

### Reproduction steps

start "Slice"
messed up after 10%
msg: Application failed , must be closed...

### Actual results

messed up

### Expected results

sliceing should finish

im not been payed by yas to do your work

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9438415/cura.log)
[cura-1.log](https://github.com/Ultimaker/Cura/files/9438418/cura-1.log)
![Cura-crash-27082022_1941](https://user-images.githubusercontent.com/112272071/187041737-bec3fd00-6754-4b35-80a2-36ee2ae7a5ef.JPG)
![Cura-crash-27082022_1937](https://user-images.githubusercontent.com/112272071/187041739-b6bef9c9-0ccc-456a-9e4f-17449445504d.JPG)
![Cura-crash-27082022_1939](https://user-images.githubusercontent.com/112272071/187041740-fb82e4de-10f3-4564-84eb-e9e1a65f46c6.JPG)
![Cura-crash-27082022_1940](https://user-images.githubusercontent.com/112272071/187041742-66f20cec-7cf9-494f-8084-84e74f6fd9eb.JPG)

**Comment by jellespijker** [comment]
Please provide a 3mf with the project that is failing.

I would also want to remind you that Cura is a free product, provided by Ultimaker to the public. I think people will respond better on a request for help if it has a little less demanding tone about delivering a fix for a product which is free for a third-party printer.

**Comment by MariMakes** [comment]
Hey @AlgenGruetze,

@jellespijker is right, I need a project file to start troubleshooting your issue. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files you may need to use WeTransfer or similar file sharing sites. Rememer, G-code files are not project files.

Can you share your project file with us?
