### ISSUE TITLE
Slicing failure

### ISSUE THREAD

**Issue by Romaniux** [Ultimaker/Cura#13146]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Crealitu Ender 3 v2

### Reproduction steps

1.- Opened the file in cura
2.- Set the model with the preset settings
3.- sliced The piece

### Actual results

It indicated upper zones as hightlighted areas 

### Expected results

Slice my model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing else

**Comment by GregValiant** [comment]
Well thanks for the report but without the supporting Cura.log file and a project file an investigation can't be done.
Under the Help menu is "Show Configuration Folder".  That will take you to the location of the Cura.log file.
Load the model and set Cura up to slice and use the "File | Save Project" command to save a 3mf file with you printer and settings.
Zip those two files and post the Zip file here.
