### ISSUE TITLE
Not slicing

### ISSUE THREAD

**Issue by ALFROROROR** [Ultimaker/Cura#13169]
### Application Version

4.16

### Platform

Mac

### Printer

Ender 3 pro

### Reproduction steps

Usual settings

### Actual results

NOT SLICING

### Expected results

Be able to cep slicing like normal

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screen Shot 2022-08-30 at 6 28 04 PM](https://user-images.githubusercontent.com/112341950/187554667-ceb05f1e-2a01-4c47-b3b7-080d50be70c8.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file in order to investigate.
Load your model, set Cura up ready to slice, and then select the "File | Save Project" command.  Zip the3mf file and post the zip file here.
