### ISSUE TITLE
Infill Editor

### ISSUE THREAD

**Issue by dromanovich** [Ultimaker/Cura#13164]
### Is your feature request related to a problem?

Similar to game level editors, I'd like to be able to develop unique infill patterns.  Unique infill geometry can be used for altering mechanical part properties or simply for cosmetic purposes when top or bottom layers are switched off.

### Describe the solution you'd like

One possible way to generate custom infill geometry is to load a DXF file.  Allowing the pattern to rotate with consecutive layers would be an added bonus.

### Describe alternatives you've considered

Currently I use SolidWorks to model desired infill geometry.
![test infill pattern](https://user-images.githubusercontent.com/7397184/187464229-a1d7c4cd-6588-469e-bbad-d3536c2a8079.png)

### Affected users and/or printers

Engineers and industrial designers can benefit from this added customization to create unique designs.

### Additional information & file uploads

[test-infill.zip](https://github.com/Ultimaker/Cura/files/9453715/test-infill.zip)

**Comment by MariMakes** [comment]
Hey @dromanovich,

Welcome to the Ultimaker Cura Github 🚀 
There actually is a way to make custom infill if yo have your infill in a surface. 

I wrote a short instruction in this thread: https://github.com/Ultimaker/Cura/issues/13020#issuecomment-1222684283
Will this help you out? 

![184891806-7fdc4d54-5f03-4230-9695-f9ecbc9f6727](https://user-images.githubusercontent.com/40423138/187485875-5f6ad306-ba43-4cc6-acac-ee424c3058a1.png)
