### ISSUE TITLE
Cura

### ISSUE THREAD

**Issue by Jacinta05** [Ultimaker/Cura#13161]
### Application Version

5.1.0

### Platform

Mac

### Printer

CR6-SE

### Reproduction steps

tried slicing my model

### Actual results

"Slicing failed with unexpected error." please consider reporting to our issues thing

### Expected results

To slice the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by GregValiant** [comment]
Without a project file and the Cura.log file we can't investigate.
The log file can be found by using the "Help/Show Configuration Folder".  You create a project file by loading your model, setting Cura up to slice, and using the "File | Save Project" command.
Zip them up and post them here.
