### ISSUE TITLE
wont slice

### ISSUE THREAD

**Issue by bunbun06** [Ultimaker/Cura#13170]
### Application Version

5.1.0

### Platform

windows 10

### Printer

anycubic mega x

### Reproduction steps

went to slice the file and it said error

### Actual results

nothing

### Expected results

fix it

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

wont sllice

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file in order to investigate.
Load your model, set Cura up ready to slice, and then select the "File | Save Project" command. Zip the3mf file and post the zip file here.
