### ISSUE TITLE
"Unexpected error" using tree supports

### ISSUE THREAD

**Issue by rtuite** [Ultimaker/Cura#13193]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anet A8

### Reproduction steps

Generating tree supports fails on some models. It could be the model because my design skills are weak and there could be artifacts in my model that cause the issue. The slicing was successful with regular supports, and only fails with tree supports. 

1. Import model
2. Select "Generate Support"
3. Select "Tree" from the "Support structure" dropdown
4. Click "Slice"

Issue occurs with both "everywhere" and "Touching build plate" for placement. I have not adjusted the overhang, pattern, etc. 

### Actual results

When clicking "slice," the progress bar makes it about half way and I get this error:
Slicing failed
Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.

### Expected results

I would expect it to generate the gcode to send to my printer. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I'm attaching a log file and the project file including the model in question. I'm also including a screenshot of the error and the support settings that cause the issue. 

https://1drv.ms/u/s!AkL7oloQo8z0onxGl1Due8IEatHt?e=3x3SFh

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
