### ISSUE TITLE
slicer error

### ISSUE THREAD

**Issue by ospanacar** [Ultimaker/Cura#1320]
Hi,
I have this problem, the holes of the piece appear filled, in the end result.
This is de part. 
![pieza](https://cloud.githubusercontent.com/assets/24992724/21752632/672187f0-d5dc-11e6-8472-d0bb985cf4fd.jpg)

and this es the result.
![slicer](https://cloud.githubusercontent.com/assets/24992724/21752638/7a08e886-d5dc-11e6-8fc1-317e57115750.jpg)

Thanks.

**Comment by nallath** [comment]
How does it look in x-ray view?

**Comment by ospanacar** [comment]
Thanks, I have solved the problem, the red line that appears in the first photo, was an error in the mesh file, once corrected the error, all is correct
