### ISSUE TITLE
Rotation of view

### ISSUE THREAD

**Issue by porzioev** [Ultimaker/Cura#13217]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

a bunch

### Reproduction steps

1. at any time
2. trying to rotate the view

### Actual results

3. since the pivot point is too far from the center of the scene, the objects and the printing plate splash out of the frame.

### Expected results

solution:
Set the pivot point in the center of the depth of field or object or simply in the center of the build plate. Maybe making the center of rotation selectable from the settings. Or rather by making the center of rotation visible and selectable as in photoshop or cad software.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

xxx

**Comment by GregValiant** [comment]
Thanks for the report.
Under _Preferences_ and _Configure Cura_ and then on the _General_ tab are some settings that apply to the view and rotation.
_Zoom to Mouse Direction_ works when the "Camera Rendering" is set to _Perspective_ but not when in _Orthographic_.
_Center Camera When Item is Selected_ will bring the model to the center point of the workspace and the model "Center of Geometry" should be the rotation pivot point.  If the model is off-screen and you use "Select all Models" from the right click menu it doesn't work.  You have to physically click on a model to select it and the scene should jump to the center of the screen.
I'll leave this as a bug report.  Let us know if you can find a solution in those settings.
