### ISSUE TITLE
The filling does not connect to the walls

### ISSUE THREAD

**Issue by boris098765** [Ultimaker/Cura#13212]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

FlyingBear Ghost 5 + Direct by SibMaker

### Reproduction steps

I checked the G CODE, the preview did not reveal the problem, however, when printing, I saw that the filling does not connect to the walls of the model, and there is a distance of about 1 mm between them.

### Actual results

The filling does not connect to the walls

### Expected results

The filling must be connected to the walls

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[4JUIbRP8YU4.zip](https://github.com/Ultimaker/Cura/files/9489653/4JUIbRP8YU4.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I get the same preview you did and I printed a couple of layers and it was fine.
When I first looked at your image of the print I thought it looked like a filament/shrinkage issue.
You can try adjusting the "Infill / Infill Overlap" setting to a higher percentage to see if it will help.  You can also zip that gcode file and post it here.  I can read the toolpath into AutoCad and see if that gap showed up in the gcode but this really looks like more of a printer/filament problem to me
