### ISSUE TITLE
support patterns not responding

### ISSUE THREAD

**Issue by shamrocksfit** [Ultimaker/Cura#13232]
### Application Version

5.05

### Platform

Windows 10

### Printer

Creality Ender Pro4

### Reproduction steps

1. Bring in STL. file
2. Checked "Generate Support" box
3. Selected "Tree" Support Structure
4. Selected "Everywhere" for placement
5. Selected "Zig Zag" for support pattern
6. Sliced
7. clicked preview and toggled through layer view

### Actual results

only showed tree support at layers 1 and 2, then switched to grid pattern for rest of support layers
![Capture1](https://user-images.githubusercontent.com/112992834/188764760-17b75a49-8059-4123-8e96-ce99f04394cc.JPG)
![Capture2](https://user-images.githubusercontent.com/112992834/188764762-9f2d4094-52ac-4517-bacd-57dd1635ad3a.JPG)

### Expected results

Tree support should have generated all through support 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file we can't investigate.  Load your model and set Cura up to slice.  Use the "File | Save Project" command to create a 3mf Project File.  Put the 3mf in a Zip folder and post the Zip file here.

Supports are Cyan colored and Support Interface is a light purple.  It appears that the support is within a shallow hole feature and you have Support Interface Pattern set to "Grid".  A Project File would tell.

The button to the right of the Settings Search box is the "Settings Visibility" tool.  Click on it and set the visibility to "All" and the support interface pattern setting will show up.
