### ISSUE TITLE
Grouping Support Blocker Shapes

### ISSUE THREAD

**Issue by rjsimon** [Ultimaker/Cura#13235]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality CR-10s

### Reproduction steps

1) I imported a model to print.
2) I created two new Support Blocker objects.
3) I  grouped them using Control-G.

### Actual results

4) The Objects Group but translate immediately below the deck of the working planer.
5) On selecting the group of support blocks and attempting to move them back above the deck they snap back into their previous positions and cannot be translated until ungrouped and even then will snap back to a position above the build plane with it's bottom most face flush with the build deck.

### Expected results

Support objects should group like normal objects; keeping all positions and transformations when grouped.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/779821/188830507-2e0c18f7-aef2-4457-96ef-3693ce0df16c.png)

![image](https://user-images.githubusercontent.com/779821/188830576-fb18782c-f54a-4743-b3df-80e6f486b8b3.png)

**Comment by GregValiant** [comment]
Thanks for the report.
I am not able to duplicate this on my computer.
Load the model, get it and Cura ready to slice, and use the "File | Save Project" command to create a 3mf Project File.  Zip the project file and post the Zip file here.
