### ISSUE TITLE
Cura 5.1.0 not slicing past 1/3 or 1/2 progress bar

### ISSUE THREAD

**Issue by camdavbax** [Ultimaker/Cura#13233]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anycubic Kobra Max

### Reproduction steps

Imported files, selected standard settings I have used before. Slice. Failed to complete. Tried 6 more times with same result, adjusted settings along the way.

### Actual results

Failed to slice file. Unknown error.

### Expected results

It should slice the file and allow me to preview and save it.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[KobraMax Profile.txt](https://github.com/Ultimaker/Cura/files/9502459/KobraMax.Profile.txt)
![Screenshot 2022-09-07 112347](https://user-images.githubusercontent.com/112999726/188781967-a4c2cfb1-0d07-4166-a376-89889c1924bd.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file to investigate this.  Set Cura up to slice your models and select the "File | Save Project" command.  Add the 3mf file to a zip folder and post the zip folder here.
