### ISSUE TITLE
No walls showing in preview

### ISSUE THREAD

**Issue by Champ1800** [Ultimaker/Cura#13234]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Open any .stl file & slice it with my standard profiles.

### Actual results

In the preview window none of the walls or outer layers are showing, only the infill.
The attached project file is one I have used before without any issue.

### Expected results

Normal preview to examine the sliced item layer by layer

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_GizoSpider.zip](https://github.com/Ultimaker/Cura/files/9504130/CE3_GizoSpider.zip)
![Prepare Screenshot](https://user-images.githubusercontent.com/110258497/188827681-394e4f91-e00d-4b69-b9b2-b3da3d9e84d2.jpg)
![Preview screenshot1](https://user-images.githubusercontent.com/110258497/188827705-2f9f37fd-38a6-453a-82bd-5b11e5933113.jpg)
![Preview screenshot2](https://user-images.githubusercontent.com/110258497/188827722-0738c675-78a9-4698-9d0d-28dd70b81197.jpg)

**Comment by GregValiant** [comment]
Thanks for the report.
In the preview screen you can see a DropDown list for "Line Type".  Click on it and make sure you have Shell and Helpers turned on.
Let us know if turning them on makes the outer and inner walls visible.  When I slice it I get this...
![image](https://user-images.githubusercontent.com/64202104/188951687-59cecc5d-f835-4751-bcf5-9a44f0521f5e.png)

**Comment by Champ1800** [comment]
That fixed it, thank you. Sorry it was a stupid issue on my side. I must have accidently unchecked it.
