### ISSUE TITLE
Cura Crash

### ISSUE THREAD

**Issue by ElPedro99** [Ultimaker/Cura#13246]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

FlyingBear Ghost 5

### Reproduction steps

Open cura

### Actual results

Crash

### Expected results

Keep Working

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9528560/cura.log)

**Comment by MariMakes** [comment]
Hey @ElPedro99 

Can you share more precisely what you were doing when Cura crashed?
If you cannot open Cura anymore can you tell us more about your set-up?
What kind of graphics card do you have? Do you have a dual monitor set-up? 

If you were slicing a file. Can you share a project file for us?
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 👼
