### ISSUE TITLE
Cura closes on its own, no error message

### ISSUE THREAD

**Issue by Alkerion** [Ultimaker/Cura#13260]
### Application Version

4 and 5

### Platform

W10

### Printer

Anycubic Mega S

### Reproduction steps

Not reproducible as the close happens unexpectedly, most of the time when I don't use the program.

### Actual results

Cura closes

### Expected results

Cura to stay open, or at least rise an error

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment]
Hey @Alkerion ,

Welcome to the Ultimaker Cura Github! 

I'll need a little bit more information about what happens to help troubleshoot or resovle.
If we don't have steps to reproduce we cannot check if we made a fix that it resolves your issue. 

There are two things that jump to mind. 
1. Could it be that you lost your connection to the internet?
2. Could it be that you have your Cura open in the background for a long time being idle? 

The next time that it happens could you please share the logs? 
You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
MacOS: $USER/Library/Application Support/cura/<Cura version>/cura.log
Ubuntu/Linux: $USER/.local/share/cura/<Cura version>/cura.logs

Thanks 😇
