### ISSUE TITLE
cura is deleting my sd card when i slice and save to disk

### ISSUE THREAD

**Issue by wtaylor2877** [Ultimaker/Cura#13269]
### Application Version

5.1

### Platform

mac

### Printer

creality

### Reproduction steps

so after i updated the slicer to 5.1 i tried to slice a file and i saved to removable disk.
then i pulled sd card and installed in my printer and tried to pull up the file and nothing would load. so i thought it was the printer at first so i put a sd card that had some old files on it and all files would load. so i took that sd card out and tried to save the recent sliced file and saved to the sd card i knew was working. so i pulled that out of the computer and installed the working sd and tried to pull up the files and nothing loaded. so after 4 sd cards tried. i put each one back in the computer and opened each one and when the sd folder opens there was no files. all my files i had save on 4 sepreat sd cards were gone like the sd card had been formatted and i lost all my sliced files from the older versions. What the hell is going on i tried to look through the settings but i don't see anything that has really changed.

### Actual results

...

### Expected results

...

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

...

**Comment by GregValiant** [comment]
Thanks for the report.
Cura doesn't deal with the SD card directly.  It makes calls to the Operating System and the OpSys deals with the SD card, hard drive, etc..
Try saving a gcode to your hard drive and then copy the file from the hard drive to your SD card.  Then try to bring it up in the printer.  Let us know if you can find out some more.
There is a firmware command for deleting files from the SD in the printer.  The printer is also capable of writing to the SD card.
