### ISSUE TITLE
Material temperature are not applied in "Custom Profiles"

### ISSUE THREAD

**Issue by mawitmer** [Ultimaker/Cura#13272]
### Application Version

5.1.1

### Platform

MacOX

### Printer

Ender S1 Pro

### Reproduction steps

1. Create a custom profile
2. Select a material A with Temp A ➝ Material temperature unchanged
3. Select a different Material B ➝  ➝ Material temperature unchanged
4. Select a predefined profile
5. Select a material A with Temp A ➝ Material temperature A applied
6. Select a different Material B ➝  ➝ Material temperature B applied

### Actual results

Material temperature are unchanged in "Custom Profiles"

### Expected results

Material temperature should be applied according material settings

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_Gummiauflage v2.11.gcode.zip](https://github.com/Ultimaker/Cura/files/9545056/CFFFP_Gummiauflage.v2.11.gcode.zip)

**Comment by nallath** [comment]
Could you also share a project file? I think this is caused by a configuration mistake.
