### ISSUE TITLE
Gap in circle lines for Biqu ABL printer

### ISSUE THREAD

**Issue by vovodroid** [Ultimaker/Cura#13276]
### Application Version

5.1.0

### Platform

Windows 10x64

### Printer

Biqu B1 ABL

### Reproduction steps

Set printer Biqu B1 ABL (or B1), PLA generic (doesn't matter) and slice attached STL with Standard quality profile.

### Actual results

See screenshot.

![image](https://user-images.githubusercontent.com/8691781/189705219-f02944f3-2377-4aa9-8cdf-6ba82ac9876e.png)

### Expected results

No gaps in lines.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Biqu MX works fine.

Attached project and source STL.

[gaps.zip](https://github.com/Ultimaker/Cura/files/9549931/gaps.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Do you have "Coasting" turned on?  The preview only shows extrusions and there is no extrusion during a Coast.

**Comment by vovodroid** [comment]
> Do you have "Coasting" turned on?

Indeed. It's enabled by default, with turned off looking good:

![image](https://user-images.githubusercontent.com/8691781/189744832-23c4d022-c7a2-492c-a062-8af25eebbbfe.png)

So it's actually visualization issue.

**Comment by GregValiant** [comment]
It's expected behavior as the preview shows where the extrusions are.  The gaps actually are the indicator that coasting is turned on.
I'm going to remove the bug label.  I'll leave this open for a while in case you would like to respond.
