### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by 3DEnthusiast** [Ultimaker/Cura#13285]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Creality CR-10S Pro

### Reproduction steps

Added model using existing slicing profiles. 
Clicked Slice.

### Actual results

Received this error message. 
![image](https://user-images.githubusercontent.com/35167054/190032444-ebfd9640-83ca-4505-be13-bbee3c83d7ee.png)

### Expected results

The file is sliced and ready for export. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9561623/cura.log)

Project file too large.

**Comment by GregValiant** [comment]
Thanks for the report.
I've seen this one before:
_Backend exited abnormally with return code 3221225477!_
I'll mark this as a duplicate and someone from the Cura team will check it.
If you could post a project file on Google Drive or some other storage site and provide a download link here that would be good.  A project file will contain the model and that could be a key to figuring this out.
