### ISSUE TITLE
Failed to slice model with tree supports enabled

### ISSUE THREAD

**Issue by bryanduxbury** [Ultimaker/Cura#13289]
### Application Version

5.1

### Platform

OSX

### Printer

Voron 2.4 350

### Reproduction steps

Tried to slice a relatively large model with tree supports enabled. After a long slice wait, it failed with an error. cura.log has "Reversing even wall line causes it to be printed CCW instead of CW!" as the last message.

### Actual results

Slicing failed

### Expected results

Slicing succeeded

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9565876/cura.log)
[back.3mf.zip](https://github.com/Ultimaker/Cura/files/9565879/back.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a persistent bug in 5.1 that keeps certain Hi-Res models from slicing i the model is at the midpoint of the build plate in Cura.  As a workaround, try moving the model on the build plate.  You might have to rotate it as well.
I'll mark this as a duplicate.
Here is your model after I moved and rotated it.
![image](https://user-images.githubusercontent.com/64202104/190171480-e62ae751-21fe-4573-8516-837488ce7268.png)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/fd85f24a-b742-42be-829a-ff536a2ae2a9)
