### ISSUE TITLE
Tree Support

### ISSUE THREAD

**Issue by Narumyiko** [Ultimaker/Cura#13297]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Two Trees SAPPHIRE pRO

### Reproduction steps

Model Tree Support generate it not without infill( Line with for Support) 0,0mm.
by changing to 2,0 mm it generate tree support

### Actual results

no tree support by a line with for support of 0,0 mm

### Expected results

a generated tree support without infill

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura bug tree support](https://user-images.githubusercontent.com/103070260/190536008-ba7144ac-ea08-4baa-8366-b843dd2731c6.jpg)

**Comment by GregValiant** [comment]
Thank you for the report.
Without a Project File and Cura.log file there can be no investigation.
If you have 0% density, 0.00 Support Infill Line Distance, and 0 Support Wall Count then yes, you have 0 support structure.  At least one of them must be a non-zero number.
To the right of the Settings Search box is the Setting Visibility tool.  Set the visibility to "All".  There are 73 settings in the support section.
