### ISSUE TITLE
Cura crashes when used by the tablet

### ISSUE THREAD

**Issue by VanessaSantiago** [Ultimaker/Cura#13299]
### Application Version

5.0.0

### Platform

MacOS Monterrey - version 12.4

### Printer

Ultimaker S5

### Reproduction steps

I'm a designer and I use tablet to work, but every time I open Cura using my tablet it works for maybe a couple of clicks and then it stops working completely. 

I see the hover states of buttons and icons but when I click them, they simply don't work. Whereas when I go back to the trackpad everything works fine for a while and then eventually Cura just crashes and quit by itself.

That didn't happen in the previous versions.

### Actual results

.

### Expected results

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by MariMakes** [comment]
Hey @VanessaSantiago,

Welcome to the Ultimaker Cura Github 🚀 

Am I understanding correctly that you have a MacOS Monterrey and you have a touch sceen that is not working as expected?
From https://github.com/Ultimaker/Cura/issues/5288 I learned, that rotating is not available on touch screens, but you mention that there is more not working? 
Also, can you check for me if the behavior has improved with the 5.2 Beta? 

Thank you 😄
