### ISSUE TITLE
Plugin errors

### ISSUE THREAD

**Issue by xeorx** [Ultimaker/Cura#13294]
### Application Version

5.1

### Platform

Ubuntu 22.04.1 LTS ( 64-bit)

### Printer

Labists ET4

### Reproduction steps

![Bildschirmfoto vom 2022-09-15 04-21-54](https://user-images.githubusercontent.com/55350450/190298563-f58f967a-c416-4e6c-90a5-e3c586fbcd7f.png)
This plugin errors are allways after start Cura. To remove or new installations doesn't help.

### Actual results

Cura restart.

### Expected results

The same errors.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9571205/cura.log)

**Comment by fieldOfView** [comment]
Ultimaker only supports the AppImage they provide for Linux. It seems you are using a different distribution of Cura, which omits one or more dependecies; the trimesh python package is required for both plugins that fail to load.

Can you check the AppImage instead?

**Comment by xeorx** [comment]
Ok, with the AppImage works fine. Thx for help.
