### ISSUE TITLE
Still having issues slicing certain files since updating CURA

### ISSUE THREAD

**Issue by wmerritt72** [Ultimaker/Cura#13292]
### Application Version

5.1

### Platform

MacOS 12.6

### Printer

Creality CR-10 Smart

### Reproduction steps

1. import Model and try to print

### Actual results

![Screen Shot 2022-09-14 at 3 39 16 PM](https://user-images.githubusercontent.com/40249783/190246936-21d1280a-5b89-4f32-b6b7-bd9e9f0eeca2.png)
![Screen Shot 2022-09-14 at 3 38 31 PM](https://user-images.githubusercontent.com/40249783/190246939-76bef081-7cec-4af0-9df5-81f7354d8de1.png)

### Expected results

[cura.log](https://github.com/Ultimaker/Cura/files/9569421/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

non

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project File ("File | Save Project") we can't check the model.  Have you checked the failed models for errors?  Are they watertight?

**Comment by handyrandyrc** [comment]
I am getting the same error.  Attaching a copy of the project I was working with.
[CE3PRO_Earth_Golem_FINAL.zip](https://github.com/Ultimaker/Cura/files/9584495/CE3PRO_Earth_Golem_FINAL.zip)

**Comment by handyrandyrc** [comment]
All good now!  @wmerritt72 - I will bet there is an issue with your model that needs to be repaired.  I opened it up with Microsoft 3D builder, which reported errors with my model.  It was able to repair the errors and I saved it.  I then imported into Cura, and was able to slice without any errors.  There are online tools for doing automated model repair, or you can find an application for your Mac that will do the same.

**Comment by GregValiant** [comment]
Thanks @handyrandyrc .
@wmerritt72 This is the MeshMixer view of handyrandy's model.  When a model has this many errors Cura can't figure out how to slice it.  When the "Model is not watertight and may not print correctly" warning comes up you need to take heed.  It doesn't matter how the model was made or who made it or where you got it from, some models have critical errors.
![image](https://user-images.githubusercontent.com/64202104/190661817-d8f5704e-e148-4f9f-aa8f-dbb8e88037d7.png)

Here it is repaired.
![image](https://user-images.githubusercontent.com/64202104/190662397-63b61d75-bb95-45ce-bc11-9a93323a718a.png)

And here is the repaired model sliced.
![image](https://user-images.githubusercontent.com/64202104/190663508-d293d59f-16ed-4c4d-bd37-89afea6f39fa.png)
