### ISSUE TITLE
Line width bug with third party print core with 0.6mm nozzle

### ISSUE THREAD

**Issue by Hateyaall** [Ultimaker/Cura#13300]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Loading a standard profile Engineering normal at 0.15mm layer hight. I changed the layer hight to 0.2 and line width to 0.6 because there is no option for 0.6mm nozzle in the firmware. I get a slicing bug error when I try to change from 0.4 to 0.6 it worked until now but I switched to Extrudr BioFusion fillament. If I change back to 0.4mm it works otherwise it won't.

![Screenshot 2022-09-16 120248](https://user-images.githubusercontent.com/67191565/190600384-21ae7cd2-6727-405c-980a-b3831da47fc7.png)

### Actual results

Bug report window pops up and it wont slice.

### Expected results

It should work and slice the model like it did before I changed to this fillament. I have also updated the materials list so I select a material directly when I load it from the 3D printer mini screen.

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_Voron_Design_Cube_v7.zip](https://github.com/Ultimaker/Cura/files/9582557/UMS5_Voron_Design_Cube_v7.zip)

**Comment by MariMakes** [comment]
Hey @Hateyaall,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for including the project file, I think I know what is going wrong!

The material profile you are using is defined by Extrudr and not by Ultimaker.
They have a hardcoded Wall Thickness of 1, usually this is a formula based on the linewidth. 

If you change that value to 0.6 your file slices!
![image](https://user-images.githubusercontent.com/40423138/193839880-c95981cf-1366-4924-acae-102d53e5e354.png)

Can you let us know if this is what you are looking for? 😄 
Than we can close the issue.
