### ISSUE TITLE
unknown cura crash

### ISSUE THREAD

**Issue by metricpiano** [Ultimaker/Cura#13314]
### Application Version

5.1.0

### Platform

windows 10

### Printer

monoprice mini delta

### Reproduction steps

1. import models with mesh error
2. arrange and scale
3. save as 3mf
4. open in 3d viewer (windows)
5. repair
6. save as 3mf
7. cura new project
8. open 3mf
9. ctrl A ctrl G
10. scale group
11. multiply group x12
12. slice == crash

### Actual results

crash

### Expected results

slicing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

unsupported

**Comment by MariMakes** [comment]
Hey @metricpiano.,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you  😞 

Thanks for your report, but we need a little more information to help you. 

Do you have a project file for us?
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
