### ISSUE TITLE
Menu items in window instead of menu bar on Mac OS

### ISSUE THREAD

**Issue by OutcastZeroOne** [Ultimaker/Cura#13318]
### Application Version

5.1.1

### Platform

Mac

### Printer

all

### Reproduction steps

launch program.

### Actual results

menu shows on window, not on menu bar like every other Mac OS program.

### Expected results

a program that conforms to Mac OS standard.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Uploading Screen Shot 2022-09-17 at 11.51.19 PM.png…]()

**Comment by fieldOfView** [comment]
This has been reported before, see https://github.com/Ultimaker/Cura/issues/12307. Therefore I will close this issue as a duplicate.

**Comment by OutcastZeroOne** [comment]
well, it has been months and no fix on it yet. not using the new CURA till it works correctly.
