### ISSUE TITLE
Random seam not actually random at all

### ISSUE THREAD

**Issue by nirurin** [Ultimaker/Cura#13326]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Ender5+

### Reproduction steps

https://github.com/smartavionics/Cura/issues/186#issue-1376924951

This has a log of the issue, reported to the smartavionics fork (which had the same issue). He has now fixed the problem with a bugfix. You may want to go crib his notes and implement the fix, as your 'random' seams are hilarously linear. 

### Actual results

Vertical seams, even though they are meant to be random. 

### Expected results

Random seams. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CE5P_cross-blade-sansCylinder_001.zip](https://github.com/Ultimaker/Cura/files/9595032/CE5P_cross-blade-sansCylinder_001.zip)

PRoject file and screenshot showing issue.

**Comment by nallath** [comment]
![image](https://user-images.githubusercontent.com/3922611/191013832-b5784a79-1853-4800-8df2-b7a5fe8da961.png)

This was already fixed for the 5.2 release (which should be out soon :))
