### ISSUE TITLE
Top Surface Skin Pattern not showing up

### ISSUE THREAD

**Issue by JParr91** [Ultimaker/Cura#13335]
### Application Version

5.1.1

### Platform

macOS Monterey 12.3.1

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. click setting icon 
2. search for experimental settings
3. check top skin surface pattern in preferences

### Actual results

top skin surface pattern options did not show up in print settings

### Expected results

top skin surface pattern options should show up in print settings so I can change settings

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screen Shot 2022-09-19 at 8 52 04 PM](https://user-images.githubusercontent.com/113953273/191143861-ae2de529-0532-4dd8-96de-f6e995e9709a.png)

**Comment by GregValiant** [comment]
Thanks for the report.
The visibility of the setting is dependent on the setting in Top/Bottom "Top Surface Skin Layers".  If that is set to 0 then the pattern is irrelevant.  If you have that set to 1 or more then please provide a Project File so there can be an investigation.  Right now I don't see a bug here so I will remove the tag but I'll leave this open so you can respond.
