### ISSUE TITLE
Echec de la découpe avec erreur inattendue

### ISSUE THREAD

**Issue by Golay65** [Ultimaker/Cura#13338]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker S3

### Reproduction steps

Découper

### Actual results

[Doc1.docx](https://github.com/Ultimaker/Cura/files/9605430/Doc1.docx)

### Expected results

?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

?

**Comment by GregValiant** [comment]
Thanks for the report.
Like a slice, it is very thin.

**Comment by Golay65** [comment]
[exemple.docx](https://github.com/Ultimaker/Cura/files/9607207/exemple.docx)

**Comment by GregValiant** [comment]
With the model loaded in Cura, and with Cura set up and ready to slice, use the "File  | Save Project" command.  Put the 3mf file in a zip folder and post the Zip file here.

**Comment by Golay65** [comment]
[ImageToStl.com_ums3_mark4 (1) entonnoir.zip](https://github.com/Ultimaker/Cura/files/9613152/ImageToStl.com_ums3_mark4.1.entonnoir.zip)
Info: sur CURA 4.13.1 j'arrive à découper!!?

**Comment by GregValiant** [comment]
Without a Cura "Project File" I can not investigate this.  I don't know what a "*.blend" file is but Cura will not open it.
