### ISSUE TITLE
3d printer

### ISSUE THREAD

**Issue by BRIANGREEN1113** [Ultimaker/Cura#13334]
### Application Version

the new one

### Platform

10

### Printer

xyz printing inc

### Reproduction steps

when i try to print it like to print to the top right corner of my 3d printer

### Actual results

i dont know what to do

### Expected results

it should print it the middle

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

when i try to print it like to print to the top right corner of my 3d printer

**Comment by GregValiant** [comment]
Thanks for the report.
It's possible that whatever "xyz" model printer you have that the printer is an "Origin at Center" machine and the box is not checked in the Cura Machine Settings.  I think you need to find out from the manufacturer if the box needs to be checked or not.  The setting should have been in the printer definition file supplied by the manufacturer of the printer.
It is unlikely that this is a Cura problem and I'll remove the bug label.  I'll leave this open so you can respond.
