### ISSUE TITLE
Saved profiles lost when switching nozzle size.

### ISSUE THREAD

**Issue by BigManBuck** [Ultimaker/Cura#13357]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

1, I switched the nozzle size to 0.2mm and pretty much had to make a new profile from there.

2. I switched back to a 0.4mm nozzle, and now all of the saved profiles I had are gone.

### Actual results

Now it says : There are no profiles matching this extruder. 

### Expected results

I'm not sure this applies ti this situation.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by MariMakes** [comment]
Hey @BigManBuck,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you. 😞 

I need a little bit more information to help you here. 
A. Can you explain in more detail how you changed your nozzle size?
B. Can you share your configuration folder? 

You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
	
You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 👼
