### ISSUE TITLE
Tick box for CONICAL SUPPORT, but it not showing in printer setting list.

### ISSUE THREAD

**Issue by mickiete** [Ultimaker/Cura#13373]
### Application Version

5.1.0

### Platform

windows 10

### Printer

Ender 3 pro

### Reproduction steps

1. opened prefs,
2. went to experimental
3. found conical support
4. Placed tick in box.
5. back to main screen
6. looked in printer settings list
7. NO CONICAL SUPPORT listed.
8. closed and restarted cura
9. still not listed.

### Actual results

nothing, it never shows.

### Expected results

to see it in the list to use.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it happen with all.

**Comment by GregValiant** [comment]
Thanks for the report.
In order to have the setting available you must have "Generate Support" checked and you must use "Normal" supports.  "Conical" is hidden and disabled if you use Tree supports.
See if that is true with your setup and let us know how it turns out.
