### ISSUE TITLE
Exporting as text file 

### ISSUE THREAD

**Issue by TheLaw23** [Ultimaker/Cura#13388]
### Application Version

5.1.1

### Platform

chrome os

### Printer

ender 3

### Reproduction steps

Re-downloaded Cura via website
Set up profiles
Sliced 

### Actual results

Exports files as usual to linux but as text file not Gcode

### Expected results

Gcode configuration  

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Unable

**Comment by MariMakes** [comment]
Hey @TheLaw23,

Sorry, it took us a while to get back to you 😞 
I'm having some trouble understanding your problem. 🤔 

If I export a gcode with Cura 5.2 Beta, it becomes a text file.
![image](https://user-images.githubusercontent.com/40423138/195084023-60d33fdf-f61e-4292-ba75-7a51778c6f2a.png)

What program are you trying to open your file with?
Do you have an example of the file that you are trying to open as a text file?

Thank you 🙏
