### ISSUE TITLE
Shape position not saved/loaded correctly when using 3MF file

### ISSUE THREAD

**Issue by rondlh** [Ultimaker/Cura#13387]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Anycubic i3 Mega

### Reproduction steps

1. Import a model
2. Add some parts (cube/cylinder) from the "Parts for calibration" plugin
3. Place the added parts at specific locations
4. Save the project as a 3MF file
5. Close Cura
6. Load the 3MF file (Open as project)

### Actual results

All shapes (cubes/cylinders) except the main shape have moved (Y position is reduced by 10 mm).

### Expected results

Reload the shapes in the original position.

![Car Before Saving](https://user-images.githubusercontent.com/77279634/192482680-36dedc3e-56bc-4bf6-84b5-e8fd942ef3fe.png)
![Car Reloaded](https://user-images.githubusercontent.com/77279634/192482696-f6ba5452-3455-4073-8e3e-0a5d568762ad.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

A picture of a cube before and after reloading the project.
The car position stayed the same, but the cube and cylinders Y position was reduced by 10 mm

**Comment by MariMakes** [comment]
Hey @rondlh,

Thanks for your report 👍 
Sorry, it took us a while to get back to you 😞 

Can you check for me in your preferences if you have these settings checked? 
They influence the position of the meshes that you load from a project file.

If this is not the cause, can you share your project file with us? 
It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by rondlh** [comment]
> Hey @rondlh,
> 
> Thanks for your report 👍 Sorry, it took us a while to get back to you 😞
> 
> Can you check for me in your preferences if you have these settings checked? They influence the position of the meshes that you load from a project file.
> 
> ![image](https://user-images.githubusercontent.com/40423138/195082370-ff3c6bcb-1268-41df-9a9a-35e52e800a84.png)
> 
> If this is not the cause, can you share your project file with us? It contains the printer and settings we need for troubleshooting. To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.
> 
> You'll need to open Github in your browser to attach any files to your ticket You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

Thanks, I have both options switched off. The problem is in the Y-direction, so dropping to the build plate should not cause this issue. I'm happy to share the project. Currently when I load the project, I add 10mm to the Y-position of the Cube and 2 cylinders to correct the issues I have. (Cube: Y=14.745mm, Cylinder: Y=22mm, Cylinder(1): Y=22mm). These parts are from the "Part for calibration" extension.
[Suzuki_Jimny-Print_in_Place3.zip](https://github.com/Ultimaker/Cura/files/9791355/Suzuki_Jimny-Print_in_Place3.zip)

**Comment by MariMakes** [comment]
Hey @rondlh,

Thanks for sharing your project file. 
I can reproduce it on my side and it's indeed super odd 😮 

I've discussed it to the team and we've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-9755

Thanks for the report! 👍 

I also think it might be connected to https://github.com/Ultimaker/Cura/issues/13523

**Comment by rondlh** [comment]
> Hey @rondlh,
> 
> Thanks for sharing your project file. I can reproduce it on my side and it's indeed super odd 😮
> 
> I've discussed it to the team and we've added a ticket to the backlog with the intent to improve this. For internal reference [CURA-9755](https://ultimaker.atlassian.net/browse/CURA-9755)
> 
> Thanks for the report! 👍
> 
> I also think it might be connected to #13523

Thanks, it's good to hear that the issue can be reproduced. I just tried it on Cura 5.2.1, and the issue still remains.

**Comment by rogerw-gh** [comment]
Same problem observed on Ubuntu LTS 20.04.05, however unchecking Keep Models Apart leaves the models where they were positioned when the 3MF was created by Cura 4.12.1

**Comment by saumyaj3** [comment]
hey @rondlh 

I was analysing the issue: 
It seems like the parts (cube/cylinder) from the "Parts for calibration" plugin are to be used in a group. Is it possible if you can guide me to that plugin?

**Comment by rondlh** [comment]
OK, that's good to know, thanks a lot for the efforts!
