### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by pamilyyyyy** [Ultimaker/Cura#13381]
### Application Version

5

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Slicing 3D model 

### Actual results

Slicing Error

### Expected results

Sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Please fix

**Comment by GregValiant** [comment]
You haven't described the problem or provided a model or included your Cura settings.  Without a Project File and Cura log file no investigation can take place.
Please provide all pertinent information and we will be glad to look into it for you.  You can ZIP the relevant files and post them here.
