### ISSUE TITLE
slicing issue

### ISSUE THREAD

**Issue by agentnightswan** [Ultimaker/Cura#13380]
### Application Version

5.0

### Platform

windows 10

### Printer

anycubic mega - s

### Reproduction steps

selected slice

### Actual results

error bug pop up

### Expected results

model to slice and prep for printing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

need support

**Comment by GregValiant** [comment]
@agentnightswan you haven't provided any information about the model you are trying to slice or your Cura settings.  Without a Project File and Cura log file nothing can be done.  Please provide the information as described in the form instructions.
