### ISSUE TITLE
Não consigo conectar

### ISSUE THREAD

**Issue by Rdsnts** [Ultimaker/Cura#13398]
### Application Version

5.1.1

### Platform

windows 10

### Printer

Ender3 Pro

### Reproduction steps

Não consigo conectar a minha conta e nem ter acesso ao marketplace e plugins

### Actual results

Não conecta.

### Expected results

Que possa me conectar a minha conta e ter acesso aos plugins.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![erro](https://user-images.githubusercontent.com/89394116/192936983-9c969f47-e600-46fb-a80e-b168cb320972.png)

**Comment by fieldOfView** [comment]
Please use english in this issue queue. We cannot help you otherwise.
