### ISSUE TITLE
Unknown  error 

### ISSUE THREAD

**Issue by Create6250** [Ultimaker/Cura#13401]
### Application Version

5.0.0

### Platform

windows 11

### Printer

Ender 3

### Reproduction steps

Slice come back unknown error 

### Actual results

Wouldn't slice even after adjustment

### Expected results

Sliced

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Non giving

**Comment by MariMakes** [comment]
Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Thank you for your report.

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
