### ISSUE TITLE
Cura 2.3.1 unable to import .ini from 15.04.6

### ISSUE THREAD

**Issue by juggleberry** [Ultimaker/Cura#1341]
Unable to import .ini config files exported from 15.04.6 there just greyed out on macOS Sierra 10.12.2 and cant be selected
<img width="411" alt="screen shot 2017-01-12 at 22 13 22" src="https://cloud.githubusercontent.com/assets/7253657/21910582/92bb491a-d914-11e6-8444-3868dda24ea2.png">

**Comment by fieldOfView** [comment]
This is fixed kn 2.4. 

In 2.3, make sure to select "All supported filetypes (...)" in the filedialog.

**Comment by juggleberry** [comment]
Thanks it was hidden on osx you have to select option in the dialog to see the options.
<img width="507" alt="screen shot 2017-01-13 at 19 31 13" src="https://cloud.githubusercontent.com/assets/7253657/21942957/126d2d6a-d9c7-11e6-9d2f-63e1bb3823a1.png">
