### ISSUE TITLE
Allow sequencing of parts printed one-at-a-time

### ISSUE THREAD

**Issue by Burtfaceman** [Ultimaker/Cura#13413]
### Is your feature request related to a problem?

I often use the "one at a time" print sequence when printing multiple copies of a part because it reduces the risk that the entire print job will fail, reduces stringing, and in some cases helps control warping and improve build plate adhesion. In order to fit more parts on the build plate, I need to be able to arrange the parts to print in a left-to-right and front-to-back sequence to prevent the print head from clashing with already-printed parts. Cura 4.X would allow me to do this with some difficulty: the print order of objects placed on the build plate was practically random, but I could rearrange them to print in the desired spatial sequence. But with Cura 5 the sequence is changed every time I move objects in the project.

### Describe the solution you'd like

I have two ideas for a solution:
- When the "one at a time" print sequence is chosen, include a drop down box that provides options for the order in which objects are printed, e.g. left-to-right, right-to-left, back-to-front, or front-to-back
- Allow the user to assign a print sequence number to each object on the build plate. The objects will be printed in ascending order of assigned numbers.

### Describe alternatives you've considered

Go back to Cura 4.X

### Affected users and/or printers

All users who use the "one at a time" print sequence feature will be affected by this, especially when printed objects are tall enough to clash with the lowered gantry. This print sequence option is not very useful if the user cannot control the sequene in which objects on the build plate are printed.

**Comment by passkal** [comment]
I support the author of the topic, this is a useful function: Choosing the printing sequence.I also use it often, I have to drag the parts around the table guessing in what order the cutting will take place.

**Comment by Turbine1991** [comment]
This should be considered a core must have feature. Currently you have to figure out which order CURA has chosen, and reposition all models accordingly.

**Comment by GregValiant** [comment]
This feature has been added to 5.7beta.
When you enable "One at a Time" print sequence a new setting "Set Print Sequence Manually" is added below Print Sequence.
When you select a model from the object list (in the lower left of the Cura workspace) and right-click on it there are two new settings at the bottom of the right-click menu.  They will move the selected object up or down in the sequence.

You can get the 5.7beta version [HERE](https://github.com/Ultimaker/Cura/releases).  Install it and see if the new feature is satisfactory.
