### ISSUE TITLE
Raft generation problem in 5.2.0-beta

### ISSUE THREAD

**Issue by hoblin** [Ultimaker/Cura#13428]
### Application Version

5.2.0-beta

### Platform

Mac (M1)

### Printer

Creality Ender 3 Max

### Reproduction steps

1. Enable raft
2. Slice model
3. Check the result

### Actual results

Raft generates under full square under the model

### Expected results

Raft follows the model shape

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Two project files were uploaded. 
1. [Cura-5.1.0_CE3MAX_iPhone_AppleWatch_Stand.3mf.zip](https://github.com/Ultimaker/Cura/files/9692086/Cura-5.1.0_CE3MAX_iPhone_AppleWatch_Stand.3mf.zip) version with proper raft generation
2. [Cura-5.2.0-beta_CE3MAX_iPhone_AppleWatch_Stand.3mf.zip](https://github.com/Ultimaker/Cura/files/9692087/Cura-5.2.0-beta_CE3MAX_iPhone_AppleWatch_Stand.3mf.zip) version with a too big raft

Cura 5.1.0:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/28090/193446201-cac52c73-a5c6-4f55-8620-22572d8739af.png">
Cura 5.2.0-beta:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/28090/193446209-4b80063a-20e6-42a9-a59e-6766fe8285ff.png">

**Comment by MariMakes** [comment]
Hey @hoblin,

Welcome to the Ultimaker Cura Github 🚀 

This behavior looks like the Remove Raft Inside Corners setting.
![image](https://user-images.githubusercontent.com/40423138/193521083-5cdfbdde-39b7-4a0c-a1a8-c84ba5f4daf1.png)
If you uncheck it you see the original behavior.

The fact that it's turned on by default seems to be faulty behavior. 
I'll let the team know.


Good find! 👍

**Comment by MariMakes** [comment]
I discussed it with the team.
It was a mistake on our side. 

We resolved it in https://github.com/Ultimaker/Cura/commit/b33cff33f5f18f7be23e6c0a86a302ea887a517c and it should be resolved in the stable version of 5.2 so I'll close this issue. 

Thanks again for the report ❤️
