### ISSUE TITLE
Slicing fails on AppImages

### ISSUE THREAD

**Issue by olsfors** [Ultimaker/Cura#13422]
### Application Version

5.2.0 beta

### Platform

Linux Mint 21

### Printer

Ultimaker S5

### Reproduction steps

Slicing with Engineering Fine 0.1 mm, 20% fill, Tough PLA

### Actual results

Got message: Unable to slice.

### Expected results

Slicing finished

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9690222/cura.log)
[top-baro.zip](https://github.com/Ultimaker/Cura/files/9690226/top-baro.zip)

**Comment by MariMakes** [comment]
Thanks for the report @olsfors 👍 
And thanks for reporting the duplicates @Piezoid ❤️ 

I'll bring them up to the team. 🤞

**Comment by MariMakes** [comment]
We're working on a solution to make it work again. 💪
For internal reference CURA-9711

Thanks for the reports ❤️

**Comment by nallath** [comment]
I've uploaded a new version of the beta. Enjoy!
