### ISSUE TITLE
CHYBA V ZOBRAZENÍ

### ISSUE THREAD

**Issue by wadware** [Ultimaker/Cura#13421]
### Application Version

5.1.0

### Platform

WINDOWS 10

### Printer

OWN DESIGN ALUMINUM COREXY

### Reproduction steps

I JUST HAPPENED TO NOTICE THIS

### Actual results

THE RED CUBE AROUND THE BLUE ARROW FOR Z AXIS DISPLACEMENT APPEARS BELOW THE 3D MODEL, BUT IT APPARENTLY SHOULD NOT BE THERE.

### Expected results

THE RED CUBE SHOULD NOT BE VISIBLE

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Ultimaker-Cura](https://user-images.githubusercontent.com/80482058/193400350-da2e3a10-1145-463e-8ee0-25484820a3a5.png)

**Comment by GregValiant** [comment]
Thanks for the report.
That almost looks like a support blocker but it's not shown in the Object List.  Can it be selected and deleted?
If not then use the "File | Save Project" command and then zip the 3mf file and post the zip folder here.
