### ISSUE TITLE
Cura is using 100% CPU when it should be idle

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1343]
I am currently using the Linux PPA of the Cura/CuraEngine master branches and Cura (the UI not the engine) is constantly using 100% CPU. I'm sure it has only just started doing this in the last 24 hours or so. It otherwise appears to function OK, you can load models and slice them, change settings, etc.

How can I determine what the problem is?

**Comment by sedwards2009** [comment]
If you are on master then I think I know what you mean. We saw that Cura was eating a whole CPU core while idle at the office yesterday. A fix has been committed to master in the meantime.
