### ISSUE TITLE
no restart of print after computer "crash"

### ISSUE THREAD

**Issue by ajmorin369** [Ultimaker/Cura#13462]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Anycubic Kobra

### Reproduction steps

1. Opened the .stl file that I wanted to print
2. configured the print to be done the way I wanted it to.
3. Sliced the model that I was trying to print, which was a 3d printer all in one test
4. started the print, was supposed to take about 4 1/2 hours to 5 1/2 hours. 
5. the computer that I used for printing, I also used to do other things like play games.
6. I loaded up Halo infinite
7. I got a green screen "crash" 
8. the print stopped
9. the computer restarted
10. I opened up the Cura to resume printing but it's not available to do.
11. report the bug, since this printer and cura should have been able to restart the print where it left off as soon as I reopened Cura in Windows 11 after it restarted.

### Actual results

There is nothing.....the printer just stopped and now it won't finish the final layers it has left, just as it should.

### Expected results

The printer through cura should have restarted the printer after I opened up cura again.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

I don't have much else.

**Comment by GregValiant** [comment]
Thanks for the report.
How were you printing (via the SD card, over the USB port, using Octoprint, etc.)?
