### ISSUE TITLE
Slicing a part, Cura 5.1.0 misses to slice a hole 

### ISSUE THREAD

**Issue by JesConsuegra** [Ultimaker/Cura#13478]
### Application Version

5.1.0

### Platform

Linux 64

### Printer

Hyoercube Evolution

### Reproduction steps

1. Load the part into Cura 5.1.0
2. Slice it
3. In preview mode, a hole has disappeared.

### Actual results

Printed the part, the hole is missing in the part.

### Expected results

That hole should have been made at slicing time. On other slicers (Prusaslicer, Superslicer, Ideamaker) that part slices properly
[missing-hole.zip](https://github.com/Ultimaker/Cura/files/9712750/missing-hole.zip)
![Screenshot-bug12_2022-10-05_06-48-37](https://user-images.githubusercontent.com/11779140/193984014-9d60975d-73be-4f58-bbb3-9b305ee687ed.png)
![Screenshot-bug1_2022-10-05_06-48-37](https://user-images.githubusercontent.com/11779140/193984017-ba7ab6ca-0b0f-4999-888a-0ff38e3fcc96.png)
[cura.log](https://github.com/Ultimaker/Cura/files/9712800/cura.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Easy to reproduce, just open the part and try to slice it.

**Comment by Piezoid** [comment]
You have "Mesh Fixes" -> "Remove All Holes" enabled. This setting is meant to do exactly that: removes all holes in each slice. 
The horizontal slots and vertical holes are not affected because they split some slices in multiple parts rather than producing polygons/parts with vertical holes in them.

**Comment by JesConsuegra** [comment]
Thanks!. But I can't see that "Remove All Holes" entry in "Mex Fixes", even if I set to see all controls, so I could not had set it.... And I cannot reset it.
![cura_Screenshot_2022-10-06_06-48-27](https://user-images.githubusercontent.com/11779140/194216937-6223c3c2-1803-4051-aa30-89bd84a17fba.png)
![Cura_Screenshot_2022-10-06_06-47-29](https://user-images.githubusercontent.com/11779140/194216949-ce33afe0-dcb3-4a41-b323-45a9dc06b13b.png)

**Comment by JesConsuegra** [comment]
Thanks, This control  was somewhat hidden to me, so I could'nt have set it. Anyway I got to show all the mesh controls and there it is, solved!. Thanks again.
