### ISSUE TITLE
When slicing a Dog Whistle "window," Cura calls for a floating inner wall.

### ISSUE THREAD

**Issue by Ergonomicmike** [Ultimaker/Cura#13479]
### Application Version

5.2.0 beta

### Platform

Win 10 65-bit

### Printer

Ender 3 V2

### Reproduction steps

I am printing an (ultrasonic) Dog Whistle. I found an .stl here: https://www.thingiverse.com/thing:4970265.
I am using the Standard Quality profile (0.20 layer height) for the Ender 3 V2 with a 0.6 mm nozzle.

The Whistle is composed of three parts. Here's what the finished product looks like.

![Dog Whistle](https://user-images.githubusercontent.com/15025888/193988371-2d14518a-8cdb-469a-890e-4749b73c50ac.jpg)

For this report, focus on the middle part with the curved/arched whistle "window,' Part B. (Download from the thingiverse link, above.)

Here's what Part B looks like from a distance in Cura:

![Dog Whistle Part B](https://user-images.githubusercontent.com/15025888/193988891-b42437fc-3d8a-4841-ad7c-44afe183675b.jpg)

Here's a zoomed in image of the window part after importing the slt into Blender. 

![Dog Whistle window in Blender](https://user-images.githubusercontent.com/15025888/193989131-671c2057-0845-4f42-8d72-b993021748c2.jpg)

As you can see, the window is smooth with no strange irregularities. (TinkerCAD shows the same smooth arch.)

### Actual results

And now here is a zoom in of the window in Cura. Note the green inner wall hanging in mid-air.

![Dog Whistle window with floating inner wall ](https://user-images.githubusercontent.com/15025888/193989626-e01a4543-6a73-41f5-a518-5abf550ddb49.jpg)

### Expected results

Naturally, I didn't expect a wall to be floating in mid-air. 

I tried lower layer heights (e.g. 0.16, 0.12 mm). The problem becomes worse.

I suppose there might be some value in Cura that I can tweak to fix this. But I tried tweaking for a half hour without success.

I don't know - maybe it's a poorly designed model and Cura is doing what it's supposed to do and this arch HAS to have a support? (The inner part of the window slopes downward, and it appears that Cura is trying to make that part of the arch.)

(As a workaround , I printed this part reversed in Z and it printed the window better, even with the resultant bridge.)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Ultrasonic_Whistle_B for github.zip](https://github.com/Ultimaker/Cura/files/9713085/Ultrasonic_Whistle_B.for.github.zip)

**Comment by MariMakes** [comment]
Hey @Ergonomicmike,

Thanks for the report 👍 

I see that the your flute contains a lot of what I would call wedges.
It's one of the shapes that the Variable Linewidth struggles with the most.

But there are settings that can help print these wedges better. 
[You can learn more about them here.](https://support.ultimaker.com/hc/en-us/articles/4792077687068-What-new-print-settings-are-introduced-to-Cura-5-) 

With just 2 profile changes I've been able to get this result.
Is this what you are looking for? 

![image](https://user-images.githubusercontent.com/40423138/194049384-0aa7f4c3-04ea-4d1b-9a3c-95b691d73926.png)

If it is, do you agree it's not a cura issue and we can close the ticket?  👼

**Comment by Ergonomicmike** [comment]
Perfect! I thought it might be a setting. Thanks!

Am closing now.

**Comment by MariMakes** [comment]
![giphy (10)](https://user-images.githubusercontent.com/40423138/194083200-6c9bd66d-3ec4-4041-a1ec-e28513b7c53e.gif)

**Comment by Ergonomicmike** [comment]
BTW, the Dog Whistle works! I blew on it last night and the dog across the street woke up and looked at me to see what the "noise" was all about.
