### ISSUE TITLE
Add the OpenSSF Scorecard GitHub Action

### ISSUE THREAD

**Issue by gabibguti** [Ultimaker/Cura#13474]
### Is your feature request related to a problem?

This feature request is related to improving the project's security posture. There are some best practices that could be raised and encouraged in Cura, such as ensure all releases are signed and follow lest privilege rule for GitHub Workflows.

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[sc-checks]: https://github.com/ossf/scorecard/blob/main/docs/checks.md
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

### Describe the solution you'd like

I would like to suggest using [Scorecards][sc] tool to perform automated security [checks][sc-checks] and help maintainers better understand where in the supply-chain the repository could be compromised. The tool is developed by the [Open Source Security Foundation][ossf], [in partnership with GitHub][sc-blog].

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[sc-checks]: https://github.com/ossf/scorecard/blob/main/docs/checks.md
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

### Describe alternatives you've considered

.

### Affected users and/or printers

Cura maintainers, Cura users and the Open Source community. We all could benefit from viewing that the repository is concerned about security, that the repository is acting to improve the supply-chain security, and raising awareness to help us all build and consume more secure software.

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[sc-checks]: https://github.com/ossf/scorecard/blob/main/docs/checks.md
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

#### Additional context about me:
I currently work on behalf of Google and the [Open Source Security Foundation](https://openssf.org/) helping open-source projects to improve their supply-chain security.

#### Additional context about Scorecards:
The [Scorecard GitHub Action](https://github.com/ossf/scorecard-action) is very lightweight and runs on each change to the repository's main branch. The results of its checks are available on to the project's [security dashboard](https://github.com/Ultimaker/Cura/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. Over 1600 projects have added the action already.

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[sc-checks]: https://github.com/ossf/scorecard/blob/main/docs/checks.md
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

**Comment by MariMakes** [comment]
Hey @gabibguti 

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I'm not very knowledgeable if it comes to the build environment but this looks like a really good suggestion. 
Thank you 😄 

I'll bring it up with the team to see if this is something we can implement.
Fingers Crossed 🤞

**Comment by rburema** [comment]
Hi! I just added the badge. Thanks for the suggestion. Sorry this took a while, it got stuck on the side-tasks board.
