### ISSUE TITLE
Error while slicing the model 

### ISSUE THREAD

**Issue by Jayang21** [Ultimaker/Cura#13485]
### Application Version

5.2.0 - beta 

### Platform

Windows 10 

### Printer

Ultimaker 2 extended +

### Reproduction steps

I am getting errors while slicing a 3d model of a tesla cyber truck 
i tried different prints but it still gives me the error 

### Actual results

It wont slice the model 

### Expected results

it should be slicing the model since i just used it an hour ago 

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[4022339_Tesla_Cybertruck.zip](https://github.com/Ultimaker/Cura/files/9724809/4022339_Tesla_Cybertruck.zip)

**Comment by GregValiant** [comment]
Well, I get the confetti page when I try to find that model.  Without a project file and Cura log file there really can't be an investigation.

**Comment by MariMakes** [comment]
Hey @Jayang21,

Welcome to the Ultimaker Cura Github 🚀 

Do you have a project file for us?
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 😄

**Comment by MariMakes** [comment]
Hey @Jayang21,

Thanks for getting back to us. 
What you shared is the .zip file that you downloaded from Thingiverse.

I'm looking for a project file. The file contains the settings that you use for slicing in Cura and ends with .3mf. 
If I just slice your STL I get a successful result. 

![image](https://user-images.githubusercontent.com/40423138/194322466-1a9d8d1a-b8ad-4d3a-b89f-9a26f4df24a0.png)

[UM2E_Tesla_Cybertruck.zip](https://github.com/Ultimaker/Cura/files/9725115/UM2E_Tesla_Cybertruck.zip)

Do you have a project file for us?
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
