### ISSUE TITLE
supports and blockers

### ISSUE THREAD

**Issue by Jacobwindsor1** [Ultimaker/Cura#13484]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

creality ender 3 pro

### Reproduction steps

put a figure in slicer
tried adding my own supports
supports or support blockers did not add

half the time when i try typing in numbers for scaling they dont register or it lags for a good 2 minutes

### Actual results

supports or blockers didnt add

lagging on numbers typed or just didnt go in at all

### Expected results

for the stuff i want to happen to actually happen

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

everything needed to know is in previous areas

**Comment by GregValiant** [comment]
Thanks for the report.
My printer is also a Creality Ender 3 Pro and I don't have any of those issues with it.  We need a project file in order to do an investigation.
