### ISSUE TITLE
Mouse Ears feature

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#1349]
It would be a welcome addition if there was an option in Cura to automatically switch on [Mouse Ears](https://community.ultimaker.com/topic/11151-issues-with-detaching-brim-general-print-suggestions/?do=findComment&comment=121518) for corners.

![Mouse Ears](https://content.invisioncic.com/ultimake/monthly_2015_09/20150906_214635.jpg.768755cd463ba5acced440be5825a25c.jpg)

**Comment by smartavionics** [comment]
One problem with DIY mouse ears is that the outer wall of the model goes around the mouse ear and so when the ear is removed the edge of the model where the ear joined is poor quality. What needs to happen is that it gets implemented the same as brim, i.e. the mouse ears butt against the perimeters which are not modified in any way and the ears can be removed with less damage to the printed part. So another way of thinking of mouse ears is "wide brim in selected locations".

**Comment by Mearman** [comment]
Was this ever implemented?

**Comment by fieldOfView** [comment]
Not as far as I know.

**Comment by smartavionics** [comment]
But now we have the brim gap setting which can help make removing brim easier. Try a small gap, e.g. 0.1 or 0.2, works well for me.

**Comment by nallath** [comment]
There are two plugins that can do this available on the marketplace:
https://marketplace.ultimaker.com/app/cura/plugins/5axes/TabPlus
https://marketplace.ultimaker.com/app/cura/plugins/5axes/TabAntiWarping

**Comment by MKlimuszka** [comment]
@nallath , neither of those plugins exist anymore. Can this be reopened?

**Comment by gh13** [comment]
> @nallath , neither of those plugins exist anymore. Can this be reopened?

You could try downloading the curapackage directly from the dev's github [https://github.com/5axes?language=&page=1&q=&sort=name&tab=repositories](url) & install them manually

**Comment by nicolasbuch** [comment]
This would be quite amazing to have as an alternative to the brim that goes all the way around. 

+1

**Comment by pkubat** [comment]
+1
