### ISSUE TITLE
print setting scrolling does not folow mose wheel movement

### ISSUE THREAD

**Issue by 1technick** [Ultimaker/Cura#13501]
### Application Version

5,1,0

### Platform

windows 10 64b nvidia gtx

### Printer

any

### Reproduction steps

Hi, it is simple. Use mouse wheel to to move in the printer settling list up/down and se the reaction.

### Actual results

resulting movement does not correspond to moue wheel movement it continues long after the wheel is stopped. It make it difficult to read and impossible to select anything from the list because it is still moving. 

### Expected results

Expected behavior is move the list by number of wheel iteration and stop. If there is a movement smoothing it could extend the movement by  ~50ms, but no more. 
When dragging the slider it behaves correctly. Even model zooming (more computations) with the same mouse has no perceivable delay. Nether any other windows apps. So I assume it is a bug in movement smoothing of the setting panel. Ether fix it or have an option to turn it off completely until it is fixed. It is either a new bug in v5 or at least much worse than it used to be in older version.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by MariMakes** [comment]
Hey @1technick,

Thanks for your report. 👍 

We are aware of changes in scrolling behavior introduced in Cura 5.0.
I also encounter it from time to time 😕 

It's quite tricky to resolve for Windows, Mac and Linux at the same time. 
But we have a ticket on our backlog with the intent to improve this behavior.

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12870
