### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by Marksman702** [Ultimaker/Cura#13506]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anycubic Vyper

### Reproduction steps

Scaled a model to 200%.
During the slicing after halfway its stops with a error warning.

### Actual results

Get the same error after restarting.

### Expected results

To finishing slicing my model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Never had a problem before

**Comment by MariMakes** [comment]
Hey @Marksman702,

Welcome to the Ultimaker Cura Github 🚀 

Do you have a project file for us? 
It contains the printer and settings I need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
