### ISSUE TITLE
Slicing  ven i open files six objektEnder 5 +

### ISSUE THREAD

**Issue by MrSilverfox1** [Ultimaker/Cura#13511]
### Application Version

5.2.0 beta

### Platform

Windows 10

### Printer

Ender 5+

### Reproduction steps

open files
slicing
printing

### Actual results

stop vith slicing

### Expected results

slicing all files

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

open stl files

**Comment by GregValiant** [comment]
Thanks.

**Comment by MariMakes** [comment]
Hey @MrSilverfox1,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report but we don't have enough information to troubleshoot.

Do you have a project file for us? It contains the printer and settings I need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 👼
