### ISSUE TITLE
Cura slicer

### ISSUE THREAD

**Issue by Pinguino08** [Ultimaker/Cura#13513]
### Application Version

5.1.1

### Platform

windows

### Printer

creality ender 5

### Reproduction steps

When I change the settings from standard to dynamic quality, I get an error and it will not slice.

### Actual results

error came up

### Expected results

Slice my project

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file there can't be an investigation as we have nothing to go by, or look at.
When I go from Standard to Dynamic I don't get that problem and so I can't reproduce it on my own.
Create a project file by using the "File | Save Project" command and then Zip the 3mf file and post the Zip file here.
