### ISSUE TITLE
Error en el corte

### ISSUE THREAD

**Issue by lobsanchez** [Ultimaker/Cura#13539]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Ender 3 S1 Pro

### Reproduction steps

1. Cargo archivo .stl
2. Habilito opción "Generar soporte"
3. Aparece "Error de corte".
![Captura de pantalla 2022-10-12 084219](https://user-images.githubusercontent.com/115613805/195268913-7af0c8b3-e619-45b6-bbf0-8271b1d7ef99.png)

### Actual results

![Captura de pantalla 2022-10-12 084219](https://user-images.githubusercontent.com/115613805/195269056-e0af9ef0-cead-4727-bc13-ce0076a7db88.png)

### Expected results

Cura finalice el proceso de laminado y genere el archivo .gcode .

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Si desactivo la opción "Generar soporte" la aplicación funciona correctamente.

**Comment by GregValiant** [comment]
Thanks for the report.
Please post a project file so there can be an investigation.
Load the model, set Cura up to slice with supports, select "File | Save Project".  Zip the 3mf file and post the zip folder here.
