### ISSUE TITLE
(5.1.1) Crash when using layer preview slider

### ISSUE THREAD

**Issue by kylebjorn** [Ultimaker/Cura#13532]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Creality CR10 S5

### Reproduction steps

1. Open file, slice part
2. Go to preview tab
3. Slide the layer preview slider on the right

### Actual results

Cura crashes when I get to about 1/4 down the slider bar.

It will also crash SolidWorks or any other open application.

### Expected results

Normally I can quickly slide to the bottom layer and be able to preview it

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9759493/cura.log)
[Transition, Supply, Split Wall Mount.zip](https://github.com/Ultimaker/Cura/files/9759502/Transition.Supply.Split.Wall.Mount.zip)

**Comment by MariMakes** [comment]
Hey @kylebjorn,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I've been trying to recreate your issue in Cura 5.2.1 but I'm able to get the crash that you mention.
![image](https://user-images.githubusercontent.com/40423138/197778302-4592f07d-371d-4e1d-a001-ad7d1cdd2b05.png)

I've also had someone look at your logs and they could not find anything indicating your crash. 

Is your layerview in compatibility mode? 
Are you seeing it with other models? Or only this one?
Are you also getting a crash in Cura 5.2.1?
Are you still stuck or is the issue resolved and we can close this issue?
