### ISSUE TITLE
Prime tower preview is in the wrong place when build plate has 0,0 at center

### ISSUE THREAD

**Issue by pouncingiguana** [Ultimaker/Cura#1354]
When using Cura 2.3.1 or 2.4 beta (Linux and Windows) with a dual extrusion printer that has 0,0 at the center of the bed, the shadow image (reserved space) for the prime tower is shown as if 0,0 is in the front left of the bed, not the center. In the layer preview, the tower is built in the correct spot, but you can't place your model where the wrongly positioned preview is because of this and it will let you park your model right on top of the real tower.

**Comment by fieldOfView** [comment]
This was fixed recently (see https://github.com/Ultimaker/Cura/pull/1336)
