### ISSUE TITLE
Printhead settings not applying

### ISSUE THREAD

**Issue by Drmalkav** [Ultimaker/Cura#13549]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

xyz Vinci mini w

### Reproduction steps

Changed printhead settings x min to -10

### Actual results

it changes it to -20 as soon as i leave the input number box

### Expected results

it should stay at -10

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Before leaving the text box.
![curabefore](https://user-images.githubusercontent.com/41089048/195463527-21b4b5ec-b4f5-41c0-8294-a3ce64357c0b.png)
As soon as i click out of the text box
![curaafter](https://user-images.githubusercontent.com/41089048/195463530-40eb7465-c594-40d8-a1cd-51b49c191663.png)

**Comment by GregValiant** [comment]
Thanks for the report.
I installed a DaVinci Jr Wifi Pro in Cura.  I changed the X min to -10.  It flashed back to -20 for a moment and then returned to -10 so I'm unable to duplicate the problem.  (The same behavior occurs when I change the numbers for my Ender.)

The -20 is called out in the printer definition file (provided by XYZ Printing) but I don't see a maximum so you should be able to set it to "0".  I know the box will not accept a positive number.
I'll leave this open as a bug report but a project file would be helpful ("File | Save Project").  You will need to zip the 3mf file and post the zip file here.
