### ISSUE TITLE
Cura is closing unexpectedly

### ISSUE THREAD

**Issue by GiseyE** [Ultimaker/Cura#13554]
### Application Version

5.1.1

### Platform

Windows 10 Business

### Printer

New defined printer or any existing printer

### Reproduction steps

-Uninstall older versions and install 5.1.1
-Load any stl
-Start working on the printing settings
-Cura is crashing

### Actual results

-Cura is closing unexpectedly 

### Expected results

-Cura is working

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9790421/cura.log)

**Comment by rburema** [comment]
What do you mean exactly by 'working on the printing settings'?

Is this an operation within Cura itself, or are you editing the print-setting files life?

**Comment by GiseyE** [comment]
Hello,

Thank you for the follow up. All is working now; I had to uninstall everything and delete some files manually, that were not being uninstall/deleted automatically. Also update some visualization stuff in my computer.
Then install again. Now is working

Thank you,
IGEW

**Comment by rburema** [comment]
Thanks for getting back to us!

Could you tell us which files where the problem?

**Comment by rburema** [comment]
Since all seems to be working now on your end, I'm closing this issue. If unexpected files (so not the user data for example, but things in program files) stay after deinstalling again, please feel free to open a new issue.
