### ISSUE TITLE
Slicing error when using "Spiralize"

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#13560]
### Application Version

5.2beta

### Platform

Windows 10 Home 64bit

### Printer

Ender 3 Pro

### Reproduction steps

This report started with a thread on the UM Forum [HERE](https://community.ultimaker.com/topic/41786-vase-mode-seam-and-artefacts/#comment-313726)

Loaded a suitable model into Cura.
Set up to spiralize with .8 nozzle and .2 layer height at .8 line width.
Natural PLA.
There are localized bulges in the print.  They were not apparent in a print when using opaque filament.

### Actual results

The print has a couple of areas with localized bulges.
![DSCN3018](https://user-images.githubusercontent.com/64202104/195989553-35fb883b-e9e1-4fa4-8c2c-265e9257473d.png)

Here you can see that they are in the gcode.  The max offset is 0.1478mm.
![Wiggles](https://user-images.githubusercontent.com/64202104/195989385-4525ec8b-f390-45ed-bf23-e71c7ea87c97.png)

This is a screenshot of a second gcode file as I was setting the Project File to upload here.  The "waves" in the lines show up in the print.
![Waves](https://user-images.githubusercontent.com/64202104/195991267-460623d4-1ed2-4f46-9ed7-a8f78e2cd774.png)

### Expected results

A flawless print with a finish like 12 coats of hand rubbed lacquer.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[GV_Spiralize_Report.zip](https://github.com/Ultimaker/Cura/files/9792281/GV_Spiralize_Report.zip)
I did not include a log file.

**Comment by smartavionics** [comment]
Changing the Maximum Deviation to 0.1 (was 0.025) made a big difference to the output, you may find doing that yields better results...

Using 0.025 we get lots of segments on some layers (including the region that makes you unhappy)

![Screenshot_2022-10-15_18-45-10](https://user-images.githubusercontent.com/585618/196000941-457d1380-02da-432a-ac7c-9cfeca7f6cbc.png)

![Screenshot_2022-10-15_18-46-48](https://user-images.githubusercontent.com/585618/196000939-7dfa69da-da24-4263-9be9-c624c0165833.png)

Using 0.1 reduces the segment count and may print nicer (not tested :)

![Screenshot_2022-10-15_18-45-36](https://user-images.githubusercontent.com/585618/196001055-11d2619f-69b0-4d77-8a1c-3050679a5a9f.png)

![Screenshot_2022-10-15_18-47-58](https://user-images.githubusercontent.com/585618/196001140-ead2f311-6b1d-4d03-92a8-999f3f59abb5.png)

**Comment by GregValiant** [comment]
Thanks @smartavionics.  That worked and the test print turned out excellent.
