### ISSUE TITLE
Does Cura 2.4.0 support dual extruders for custom printers?

### ISSUE THREAD

**Issue by JBKingdon** [Ultimaker/Cura#1357]
Hi,
I was going to try the 2.4.0-BETA2 release but I can't seem to find any way of configuring for dual extruders. Am I missing something or is this not supported yet? 

Regards,
James

**Comment by markwal** [comment]
2.3.1 has experimental dual support, but only for Ultimaker original dual.  It's actually possible to make it work with other printers, but not through the UI. You have to add some custom definition files in json format to the app files directly and since its a bit if a hack, guaranteed to break on upgrade.

Anyhow, you entered this issue on the OctoPrint upload plugin. Maybe you meant to enter it on the http://github.com/Ultimaker/Cura issue tracker?

**Comment by JBKingdon** [comment]
That sounds interesting. The 2.4.0-Beta comes in some sort of launchable wrapper and I can't see where it's put the json files. Is there some way of unpacking it or should I just grab the current master from github (and go down the build dependencies rabbit hole...)

**Comment by markwal** [comment]
What platform?

**Comment by JBKingdon** [comment]
This is on Linux.

**Comment by pouncingiguana** [comment]
If you're running ubuntu you can add the PPA to install a pretty current build of the beta (instructions below), then add you custom json files to /usr/share/cura/resources

sudo add-apt-repository ppa:thopiekar/cura
sudo apt update
sudo apt install cura

**Comment by Ghostkeeper** [comment]
Also, the AppImage wrapper will unpack to a mounted image upon launching Cura. You can inspect the contents of the image while Cura is open if you can find where it lists the mounted images on your Linux distribution.

**Comment by BagelOrb** [comment]
I think this question is answered.

**Comment by probonopd** [comment]
> Also, the AppImage wrapper will unpack to a mounted image upon launching Cura. You can inspect the contents of the image while Cura is open if you can find where it lists the mounted images on your Linux distribution.

`/tmp/.mount_*` -- or you can just loop-mount it, since it is (also) an ISO file.

**Comment by Patola** [comment]
I have been successfully using Cura with dual extrusion since 2.3, I even wrote a chapter in a book in my national language teaching how to do it. But you really have to edit the .def.json files... I used the ultimaker dual as a template
