### ISSUE TITLE
Slicing Failed with an Unexpected Error

### ISSUE THREAD

**Issue by bluecollardm** [Ultimaker/Cura#13577]
### Application Version

5.2.0

### Platform

Windows 10

### Printer

Voxelab Aquila C2 (Custom input printer)

### Reproduction steps

1. 2 Instances of Cura 5.2 Open at the same time
2. Autoslicer extension on
3. Failed to slice
4. Retry slice by pausing and unpausing autoslicer
5. Failed to slice
6. Turned off autoslice and manually click slice
7. Failed to slice

### Actual results

Warning of Slicing error

### Expected results

Should have sliced the stls for printing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by MariMakes** [comment]
Hey @bluecollardm,

Welcome to the Ultimaker Cura Github 🚀 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
