### ISSUE TITLE
Slicings stops with unknown error

### ISSUE THREAD

**Issue by UdoMeessen** [Ultimaker/Cura#13589]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Anycubic Mega X

### Reproduction steps

Independently of the structure of the model Cura stops sclicing whenever I scale up the models in height. There seems no rule to aply, because I've printed models 260mm heigh without issues and the next model can only be sliced as long as if keep it below 230mm or something else. Thus it appears as if Cura gets problems with slicing whenever a not clearly defined height is reached.
![grafik](https://user-images.githubusercontent.com/94394850/196374232-a1b0cedf-1972-4937-9c9a-4c2f6dab08af.png)

Teher seems to be no definded rule why Cura stops slicing with an UNKNOWN Error.

### Actual results

Scaling down models does help but is not desireable, because the rule behind ist not understandeable.

### Expected results

Cura should slice any model, independently of its complexity as long as it fits into the printing volume of the machine.
[cura.log](https://github.com/Ultimaker/Cura/files/9808376/cura.log)
[Kameri-Errect.zip](https://github.com/Ultimaker/Cura/files/9808393/Kameri-Errect.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Need help, please.

**Comment by MariMakes** [comment]
Hey @UdoMeessen,

Thanks for your report and this 🌶️ project file.
I had some raised eyebrows in the office today. 😉 

I'm able to recreate your crash when I change the size of your model. 
But I also noticed that I'm getting an error that the mesh is faulty. 
![image](https://user-images.githubusercontent.com/40423138/196435645-19029d17-0034-4135-8905-bd4b5e605dac.png)

Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/ or the Make Solid feature of MeshMixer.
