### ISSUE TITLE
Ultimaker 3 Print Area

### ISSUE THREAD

**Issue by jeffcolabs1** [Ultimaker/Cura#13588]
### Application Version

4.13.1

### Platform

Mac

### Printer

Ultimaker 3

### Reproduction steps

When printing the maximum print area is too large.  The print head hits the two rear glass clips.

### Actual results

When printing the maximum print area is too large.  The print head hits the two rear glass clips.

### Expected results

When printing the maximum print area is too large.  The print head hits the two rear glass clips.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

When printing the maximum print area is too large.  The print head hits the two rear glass clips.

**Comment by MariMakes** [comment]
Hey @jeffcolabs1,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for you report, but I don't have enough information to start troubleshooting. 

Do you have a picture of what you are encountering?

I have an Ulitmaker 3 here where I can test your issue on. 
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
