### ISSUE TITLE
In-Line heater

### ISSUE THREAD

**Issue by tzutsi** [Ultimaker/Cura#13595]
### Is your feature request related to a problem?

yes, print quality, due to wet filament

### Describe the solution you'd like

I live in Seattle are, routinely 90% humidity. Constantly battle print quality issues, due to wet filament, especially PETG and Nylon. I store my spools with LOTs of silica beads, put them in dehydrator prior to use. Also have a dryer keeping the spools heated while printing. All of this Helped, But as an experiment, I added an in-line dryer and bowden tubing, such that the filament is exposed to room air only when going through the extruder gears. This solved my print quality issues. The heater is controlled by a 2nd extruder. My dryer IS a couple of heat breaks and heat sinks run in series, with heat block in the middle, and a extruder heat cartridge and thermistor). What would be nice, is a profile setting that stored the desired temperature for each filament. I currently edit  printer settings to set the desired temperature, prior to generating Gcode. 

### Describe alternatives you've considered

manual controlling the heater. I'd like software control, so it can be turned on and off with the printer. 

### Affected users and/or printers

Anybody that lives in a humid location

**Comment by MariMakes** [comment]
Hey @tzutsi,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I'm aware that it's necessary to dry your materials before printing to ensure good printed part quality.
Most printers have ways to adjust their temperatures in the firmware. 
We suggest defining the build plate temperature if you want to dry your filament from the printer itself. 
https://support.ultimaker.com/hc/en-us/articles/360017464340-How-to-dry-Ultimaker-materials-

We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided to defer this issue. We believe we will not work on this anytime soon and will therefore defer this issue.

I hope you understand 🙏
