### ISSUE TITLE
Manitore STL I paid for and downloaded, just attempting to slice using Cura 5.1.1

### ISSUE THREAD

**Issue by GuindonDesigns** [Ultimaker/Cura#13606]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Just clicked Slice, Support checked, infill% 20, Layer Height/(resolution)  0.2mm

### Actual results

it sliced ok

### Expected results

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
Well, thanks for that.
So this is a bug report?
