### ISSUE TITLE
Windows Installer does not remove previous version when installing new release

### ISSUE THREAD

**Issue by pessimism** [Ultimaker/Cura#13619]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Install Cura 5.1
Install Cura 5.2.1

### Actual results

Installing 5.2.1 leaves 5.1 installed also.

### Expected results

Installing 5.2.1 removes 5.1 as is standard for most Windows application installations.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is not new with 5.2.1, the problem has existed for some time.

**Comment by lugui1998** [comment]
Pretty sure this is a feature, not a bug
