### ISSUE TITLE
not slicing

### ISSUE THREAD

**Issue by DocYoung21** [Ultimaker/Cura#13612]
### Application Version

5.2.1

### Platform

windows 11

### Printer

voxlab aquila

### Reproduction steps

I added the print in so i could slice it

It started to slice and then stoped. 

### Actual results

box shows up and say report bug.

### Expected results

This.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

N/a

**Comment by MariMakes** [comment]
Hey @DocYoung21,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
