### ISSUE TITLE
Very old bug with (not) displaying file name and parameters.

### ISSUE THREAD

**Issue by Vipcioo** [Ultimaker/Cura#13615]
### Application Version

4.0 or less up

### Platform

Windows 10

### Printer

Not relevant

### Reproduction steps

I changed the display to a dark theme.

### Actual results

I can't see the name or parameters of the file when zoomed in.
Only when you move away from the table to darker background does all the print data correctly appear.

### Expected results

Change the colours just like a light theme where the fonts are shown against a light and dark background. 
It's impossible now.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

![#1](https://user-images.githubusercontent.com/19477134/197069328-f68801bb-2800-4c8e-9ae5-2c88a21f0d89.png)
![#2](https://user-images.githubusercontent.com/19477134/197069356-8cfffbe9-7d4a-4243-a2f3-c5172cd0827d.png)

**Comment by MariMakes** [comment]
Hey @Vipcioo,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I recognize your issue. We've received some internal reports on the issue. 
I asked around and we seem to have resolved it for mac users but not for Windows. 
I'll bring it up again to see if we can resolve it for widows as well. 🤞 

<img width="546" alt="Screenshot 2022-10-31 at 16 16 16" src="https://user-images.githubusercontent.com/40423138/199045018-3c690131-5962-4a39-851e-9532a372202c.png">

**Comment by MariMakes** [comment]
Hey @Vipcioo 

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-9840

Thanks for the report! 👍

**Comment by Vandresc** [comment]
Fixed for the next release!
