### ISSUE TITLE
2.4.0b keyboard view rotation fails

### ISSUE THREAD

**Issue by wkearney99** [Ultimaker/Cura#1362]
At some point when moving items around on the bed the arrow keys fail to perform their rotating functions.

Might it be possible to either support mouse-based movement (using control, alt, shift modifiers perhaps) or provide quick view change resets?  Like top, front, side, etc.

It's hard to duplicate this bug, but if you decide to rename the output file that seems to be the simplest way to trigger the loss of rotation changes.  It's the up/down arrow keys that get lost the most.  Eventually the right/left will respond.

That or are there some other keys that'll provide view rotation?

**Comment by Ghostkeeper** [comment]
> Might it be possible to either support mouse-based movement (using control, alt, shift modifiers perhaps)

You can rotate the view by dragging the right mouse button.

It seems that only left/right works from here. Up/down causes the application menu to open, starting with File.
