### ISSUE TITLE
Unexpected error when trying to slice model

### ISSUE THREAD

**Issue by kekshibe** [Ultimaker/Cura#13621]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 3

### Reproduction steps

I imported the model, tried to slice it with the same od settings i did for everything else, it starts to slice but immediatelly after it tells me that it has been an unexpected error. I'm doing a model of Artorias that i had bought on Etsy and this is the file
(It wont even let me upload the files)

### Actual results

Won't let me slice it

### Expected results

that it slices

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

help

**Comment by GregValiant** [comment]
Thanks for the report.
We would need a project file to debug this.
A lot of models have internal errors that keep any slicer from finishing a slice.  Something you could try would be to open the model in MS 3D Builder (included with Windows) and then select the "Insert" command on the menu bar.  An automatic Model Checking utility will run and if it finds errors there will be a popup message box.  Click on the box to make repairs to the model (the repair utility is pretty good).  Do a Save-As and change the file name then load the repaired model into Cura and try again.

If that doesn't work then:
With the model loaded in Cura and Cura set up to slice - use the "File | Save Project" command to create a 3mf project file.  Zip the file (right-click on the file in Explorer and use the Send-To command).  Post the zip folder here.
