### ISSUE TITLE
update or use marketplace without crashing 

### ISSUE THREAD

**Issue by AlexFaber18** [Ultimaker/Cura#13633]
### Application Version

5.2.1

### Platform

windows 10

### Printer

ender 3 

### Reproduction steps

1. downloaded the newest update like version 5.2.0 advised 
2. try the new version out but it wouldn't let me update after I used the marketplace from the main website to add the cutter feature 
3. tried to redownload the previous version and now it has the same problem 
4. both versions crash after I try to update my profile 

### Actual results

i exit the application and think about downloading a different application cause I shouldn't have something like this happening 

### Expected results

my profile should have been updated without the whole application failing 

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by MariMakes** [comment]
Hey @AlexFaber18,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report, I'm sorry to hear you are stuck 😖 

In this case, we need your configuration folder and your logs for troubleshooting. 

You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
	
You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏

**Comment by AlexFaber18** [comment]
[5.2.zip](https://github.com/Ultimaker/Cura/files/9859638/5.2.zip)
Thank you for getting back to me so quickly attached above I believe is what you have asked for. Thank you again.

**Comment by MariMakes** [comment]
Hey @AlexFaber18,

Thanks for the files.
Unfortunetly, I'm still having trouble recreating your issue, even with your configuration folder. 😖 

I'll have someone look at your included log files. 

Can you share what kind of cutter feature you wanted to add? 
Is it a plugin on the marketplace?

**Comment by AlexFaber18** [comment]
So the additional item I want to add is the mesh tool that is able to cut up a stl file that is to big to fit in my ender 3s parameters.

Sent from my iPhone

On Oct 25, 2022, at 9:48 AM, MariMakes ***@***.***> wrote:

﻿

Hey @AlexFaber18<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAlexFaber18&data=05%7C01%7C%7C4088365395524fcd6fb508dab68f8985%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638023024852624769%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dixouXDvngnityIObqy3SVqZv9nYGdTAOSX5NijMuuA%3D&reserved=0>,

Thanks for the files.
Unfortunetly, I'm still having trouble recreating your issue, even with your configuration folder. 😖

I'll have someone look at your included log files.

Can you share what kind of cutter feature you wanted to add?
Is it a plugin on the marketplace?

**Comment by MariMakes** [comment]
Do you remember what the tool is called? 
Is it something I could install aswell?

**Comment by AlexFaber18** [comment]
Yes it is the mesh tool in the marketplace.

Sent from my iPhone

On Oct 26, 2022, at 4:36 AM, MariMakes ***@***.***> wrote:

﻿

Do you remember what the tool is called?
Is it something I could install aswell?

**Comment by MariMakes** [comment]
![image](https://user-images.githubusercontent.com/40423138/198017916-814cdcf3-f579-4f5f-a80a-372549df145f.png)

I installed the plug-in but it only has a split model into parts setting. 

But that only works for STLs that consist out of multiple small submeshes like this model: 
![image](https://user-images.githubusercontent.com/40423138/198018143-f11bf8b0-155e-40ad-8d3b-db16495b44b3.png)

Is that what you want to do?

**Comment by AlexFaber18** [comment]
Yes it is that is what I was trying to accomplish

Sent from my iPhone

On Oct 26, 2022, at 7:47 AM, MariMakes ***@***.***> wrote:

﻿

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40423138%2F198017916-814cdcf3-f579-4f5f-a80a-372549df145f.png&data=05%7C01%7C%7Cf6825d27641a4812d6bc08dab747e187%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638023816591319626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lZr%2BUqIOy9htKRkbBz6EKCPoDIJcpBztTGxSg5eNt3E%3D&reserved=0>

I installed the plug-in but it only has a split model into parts setting.

But that only works for STLs that consist out of multiple small submeshes like this model:
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F40423138%2F198018143-f11bf8b0-155e-40ad-8d3b-db16495b44b3.png&data=05%7C01%7C%7Cf6825d27641a4812d6bc08dab747e187%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638023816591319626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QQ6sAifl4honBrKDLnOeOhYqeZZe7vGwNlYje3Se7%2Bc%3D&reserved=0>

Is that what you want to do?

**Comment by AlexFaber18** [comment]
Hello thank you again so much I was able to get to work the way I wanted to. So I really appreciate it. Have a wonderful weekend.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by MariMakes** [comment]
Yay! I'm happy to hear this update. 😊 
I'll close the issue as resolved.

**Comment by AlexFaber18** [comment]
Thank you again for all your work it was much appreciated

Sent from my iPhone

On Oct 31, 2022, at 5:32 AM, MariMakes ***@***.***> wrote:

﻿

Closed #13633<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUltimaker%2FCura%2Fissues%2F13633&data=05%7C01%7C%7Ce5596b1480e34e9b100608dabb22d61b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638028055544438264%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8B24TQD96PNyq9ieHW5Q4m3hxltD%2FlXZt9usdIw%2FfcY%3D&reserved=0> as completed.
