### ISSUE TITLE
Overheating

### ISSUE THREAD

**Issue by Gphantom650** [Ultimaker/Cura#13637]
### Application Version

4.2.0

### Platform

Windows 10 Pro

### Printer

FLSUN QQ-S Pro

### Reproduction steps

Preset on printer, Hot end set to 210 to feed new spool.
After new spool was fed, went to cura to PRINT using Wifi.
As project was being sent, I noticed that the heater was cooking the PTFE tube.
I looked at the MONITOR on Cura and it reported a temperature of 430 degrees celcius.
This happens regularly if the Hot end is pre-heated and a file is sent via Wifi.
If the file is short, the temperature eventually settles before it gets too hot but, when a LONG file is sent, the heater keeps getting hotter till the bed is heated.
I replicated this using a short file and the cura Monitor showed the hot end temperature increasing.

### Actual results

The hot end temperature keeps rising until the bed is hot

### Expected results

Temperature should not be set until the bed temperature is set.  I haven't tested to see if pre heating the bed would cause a temperature rise if a large time consuming file is sent via wifi.  I might do this to see.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None required.  Any file will do this.
Also, I'm using the standard FLSUN program.

**Comment by GregValiant** [comment]
Thanks for the report.
Ultimaker Cura has it's own internal limit on temperature.  It is not possible to write an M104 or M109 command to gcode for a temperature over 365° without doing some hacking.
_"I'm using the standard FLSUN program."_   Is that a fork of Cura provided by FLSUN?  If it is then you would need to go to them for support.  The current Cura version is 5.2.1 so your version is out-of-date by 13 or 14 releases.

This sounds like a problem within the firmware of the printer.  Somehow it is ignoring the Set Point that you gave it during your pre-heat sequence.
You say you are sending the file via WiFi.  What plugins are you using in Cura to accomplish that?

If you are using UltiMaker Cura then please post a gcode file that has been a problem for you.
