### ISSUE TITLE
(Feature) Add Renderer colors to theme.json

### ISSUE THREAD

**Issue by rudowinger** [Ultimaker/Cura#1364]
As a friend of "dark" 3D software, it would be great if the theme.json is extended by _renderer_ color options like background-color

![render](https://cloud.githubusercontent.com/assets/14955635/22172036/984c1da2-df9d-11e6-8e1d-6d6b18aff464.jpg)

**Comment by fieldOfView** [comment]
I looked into this a little while ago. The tricky part is that the theme layer is used in the part of the UI that is specified in QML, but the viewport is handled by the underlying python layer. Python currently has no access to the theme singleton.

**Comment by rudowinger** [comment]
Maybe a Python level "dark_mode" setting then, that inverts the colors?

**Comment by fieldOfView** [comment]
I have found a way to access the theme from the Python side of things, and I am working on a set of Pull Requests to make the viewport colors themable.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/1370 and https://github.com/Ultimaker/Uranium/pull/215
