### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by PUTONAHAPPYFACE2022** [Ultimaker/Cura#13649]
### Application Version

5.2.1

### Platform

WINDOWS 10

### Printer

ENDER 3 

### Reproduction steps

LOADED MODEL 
sized the model 
went to slice then it keeps saying unable to slice with any model at any size very frustrating 

### Actual results

nothing as cura not working 

### Expected results

it should slice any model at any size with no problem 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

nothing left to say

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and a log file there is nothing for us to look at or work with to debug your problem.
_"Cura is not working"_. 
If this was a widespread problem then no one would use the software.  Cura works fine on my Windows 10 computer and with my Ender 3 Pro.
