### ISSUE TITLE
Cura slice failure

### ISSUE THREAD

**Issue by Trodai205** [Ultimaker/Cura#13640]
### Application Version

5.2.1

### Platform

windows 11

### Printer

ender 5 plus

### Reproduction steps

loaded file into slicer and changed scale to 200% and then clicked slice and failed to slice, tried again and still failed to slice

I rescaled file to 199.99% and was successfully sliced I then tried 200.1% this also worked. attempted 200% again and failed

### Actual results

failure to slice at 200% scale

### Expected results

file would slice at 200%

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[owl.zip](https://github.com/Ultimaker/Cura/files/9852904/owl.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing it so I can't reproduce the problem.
If you post a Project File ("File | Save Project") it might give a clue.
