### ISSUE TITLE
(5.2.1) Raft Top Layer Defaulting to Extruder 2

### ISSUE THREAD

**Issue by wcj97** [Ultimaker/Cura#13678]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

- Disabled Extruder 2
- Varied extruder 2 material
- Varied extruder 2 print core
- Set Raft Top Layers to "0"

### Actual results

Regardless of "enabled" status of extruder 2, and regardless of print core and material type selected, raft top layers default to being printed by extruder 2.

Only setting raft top layers to 0 prevented extruder 2 from being used during print.

### Expected results

Disabling Extruder 2 should force all gcode to be generated for extruder 1. Raft top layers should be printed using extruder 1 material by default unless otherwise specified.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/39246786/198402585-c9ba43f5-8eba-4383-9240-c2f27e04ab31.png)

![image](https://user-images.githubusercontent.com/39246786/198402684-eaf018e1-fdc0-413e-a655-493635420aff.png)

**Comment by MariMakes** [comment]
Hey @wcj97,

Thanks for your report 👍
This seems like super weird behavior 😮 
At first glance, this seems like one of the BASF 17-4 PH or 316L materials. 
They have particular settings enabled by default to ensure a successful print.
Are you trying to print with these materials? 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
