### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by DKiefer770** [Ultimaker/Cura#13674]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Anycubic MegaX

### Reproduction steps

Attempted to slice.  

### Actual results

Slicing proceeds all the way to end the sometimes, but then resets.  Now I am getting "Slicing Failed" dialog box.

### Expected results

Slicing should complete normally.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AI3MX_Stubby Cubical 6.zip](https://github.com/Ultimaker/Cura/files/9881277/AI3MX_Stubby.Cubical.6.zip)

**Comment by DKiefer770** [comment]
Thanks for response.  I thought I was pushing the envelope here.  I really don’t want to remove the supports.  This is a lamp design that I print in clear PLA, PETG, ABS, etc. where I want to show some interesting internal structures.

In other designs I have (that do not have the internal structures, but just the outer shell), I use Gradual Support Infill Steps (see attached) but I wanted something more consistent.

I will try modifying my design (these are randomly/parametrically generated in OpenSCAD) to gut out more of the inside.  Clearly the slicer is confused as to what is inside/outside, and what needs supports.

This is probably related to my other Issue: 5.2.1 hangs when opening dialogs (Issue #13653).  I only see the hangs after I attempt a slicing operation.

You can close both these issues if you like.

Thanks for your help!

David Kiefer
***@***.******@***.***>

sine pendulositate nulla significatio

**Comment by GregValiant** [comment]
I'll go ahead an close this then.  It was an interesting exercise.
