### ISSUE TITLE
won't slice on MAC

### ISSUE THREAD

**Issue by cman346** [Ultimaker/Cura#13689]
### Application Version

Mac version

### Platform

Mac OS Montery

### Printer

GEEEtech A30T

### Reproduction steps

1. won't slice stl downloads from Tinkercad

### Actual results

stops working won't print

### Expected results

it should print; right?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

so far so good finally but this is another step that gets stuck!!!

**Comment by GregValiant** [comment]
Thanks for the report.
Models created with TinkerCad need to be carefully checked.  They often have "flipped normals" and slicers can't figure out what is "inside" and what is "outside".
If you load the "Mesh Tools" plugin from the Cura MarketPlace you can select a model, right click, and the Mesh Tools menu is at the top.  One of the tools is "Check Mesh".  Mesh Tools is not a replacement for a dedicated repair utility but it does have some basic ability to repair models.

![MeshTools Menu](https://user-images.githubusercontent.com/64202104/198828089-ead27ea6-aa41-4f90-b63a-a4b905b92878.png)

If you Zip one of your model files that doesn't slice and post the zip folder here we can take a look.
