### ISSUE TITLE
Cura Crashing and program resetting

### ISSUE THREAD

**Issue by JParr91** [Ultimaker/Cura#13684]
### Application Version

5.2.1

### Platform

macOS Monterey 12.3.1

### Printer

Creality Ender 3 V2

### Reproduction steps

Loading a new file into Cura this time, but sometimes I'm doing nothing at all and the program still crashes. I literally am not even in the window and it crashes randomly.

### Actual results

Cura crashes and I need to reopen the program. Sometimes when I open it, it acts like I'm a new user, even though I have an account. It makes me select a printer as if I've never used the program. Then as I click on sign in, it randomly remembers me and I don't have to sign in. So I still have to add a new printer to get in, but then all of my custom setting selection boxes are unchecked, so I have to start from a blank slate on all my printer again, and its extremely irritating. 

### Expected results

I would expect Cura to not crash while doing nothing, and especially not make me re-sign and and uncheck ALL my settings. This has happened 3 times now.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

There is nothing to submit since it crashed.

**Comment by MariMakes** [comment]
Hey @JParr91,

Thanks for your report 👍
It's a bit tricky to troubleshoot. 

Are you trying to load the same exact file? 
Could you share that file with us?
Are you adding and deleting printers and materials?
Do you have any plugins installed?

Maybe you can share your configuration folder. 
You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
