### ISSUE TITLE
[regression 15.06.02] Est. print-time & material use not showing

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#137]
After slicing a model, the "SaveButton" text still shows "Please load a 3D model" instead of the estimated print-time and material usage.

This is a regression from 15.06.01, where this functionality worked.

**Comment by awhiemstra** [comment]
Can you provide the model you used? It seems to work here.

**Comment by fieldOfView** [comment]
This may be caused by my hacking the theme; a clean copy does not exhibit this bug. Will investigate and reopen if I can reproduce it with a clean copy.
