### ISSUE TITLE
When I try to slice my models it freezes and doesn't slice it and comes up with a possible bug error message.

### ISSUE THREAD

**Issue by msabourin16** [Ultimaker/Cura#13712]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

1. Attempted to slice it again
2. Quit the software
3. Reopened the software
4. Sliced again

### Actual results

Nothing. It still didn't work.

### Expected results

It should slice the models. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[harry scott hall.zip](https://github.com/Ultimaker/Cura/files/9920144/harry.scott.hall.zip)
![image](https://user-images.githubusercontent.com/117279437/199485605-78907a6c-6cca-4208-a427-ad2d8d95968c.png)

**Comment by GregValiant** [comment]
Thanks for the report.
I can duplicate the problem.
I started swapping pieces in and out.  The problem appears to be the model I've marked below with the red arrow.  Rotating that one model 90° seems to fool the bug.
I'll mark this as a duplicate as this behavior has been reported previously.  Someone from the Cura team will take a look at this.  In the meantime, see if that workaround makes a difference for you.
![Untitled](https://user-images.githubusercontent.com/64202104/199679772-ee6b7a11-a17c-4935-a392-eda2d66edb29.png)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/9dde5080-481f-4f0a-98f4-91835d7e76b2)
