### ISSUE TITLE
Vase mode doesnt slice properly in Arachne beta 2

### ISSUE THREAD

**Issue by mariovsky** [Ultimaker/Cura#13721]
### Application Version

arachne_engine_beta_2

### Platform

windows 7

### Printer

creality 5 pro

### Reproduction steps

Set spiral mode 
sliced 

### Actual results

After slicing i check the preview and the print has lines inside instead of having a consistent wall.

### Expected results

A consistant wall

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![cura](https://user-images.githubusercontent.com/117349420/199684932-52f5ccdc-dad0-4d05-97a0-ea76b5aa6dc1.jpg)
[CE5_staple100.zip](https://github.com/Ultimaker/Cura/files/9927020/CE5_staple100.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model isn't suitable for spiralize as it has a big hole in the middle and the low sill on one side.  Sorry.
This isn't a bug but normal behavior.  Vase mode is for solid vase-like objects that have no overhangs and no "U" shaped sections develop when sliced.
I'll remove the bug label and close this.  You can still respond here.
