### ISSUE TITLE
not slicing

### ISSUE THREAD

**Issue by Raiders199001** [Ultimaker/Cura#13723]
### Application Version

5.2.1

### Platform

windows 10

### Printer

anycubic vyper

### Reproduction steps

tried to slice a file
said couldnt slice

### Actual results

says a bug has happened report

### Expected results

sliced the object 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

need fixed

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file to troubleshoot this.  Import the model to Cura, set up your slice and then use the "File | Save Project" command to create a 3mf file.  Zip the 3mf file and post the zip folder here.
