### ISSUE TITLE
Small part not displayed in Monitor

### ISSUE THREAD

**Issue by ProtomakerSprint** [Ultimaker/Cura#13738]
### Application Version

5.2.1

### Platform

Windows 11 64 bit

### Printer

Crealitit Ender 5 Plus

### Reproduction steps

Use as normal

### Actual results

Monitor  never displayed small part, displays in other tabs, preview, etc

about 6.5 x 4,5mm

### Expected results

Hope it was displayed;

3D Prints without issue

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Try This first Pinion Gear.zip](https://github.com/Ultimaker/Cura/files/9944453/Try.This.first.Pinion.Gear.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The Monitor stage has some controls for USB printing and that's about it.  There is a lot of open real estate.  If you want to view the model you can switch back to the Preview or Prepare stage.
I'll remove the bug label and close this since this is how the program works.
