### ISSUE TITLE
Error When Slicing an STL Scaled to 800%

### ISSUE THREAD

**Issue by will-maxim** [Ultimaker/Cura#13736]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic Kobra Plus

### Reproduction steps

Opened STL file
Scaled up to 800% without incident
Started slicing. WIthin approximately 10 seconds of slicing, error message appears.

### Actual results

"Slicing failed with unexpected error. Please consider reporting a bug on our issue tracker."

### Expected results

Model should slice normally.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9943073/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
This has been coming up a lot.

"Backend exited abnormally with return code 3221225477!"

This is the 20th report of this behavior.  I'll mark this as a duplicate and close it as plenty of models have been submitted that show the problem and the Cura Team has plenty to work with.  I hope you understand.

**Comment by will-maxim** [comment]
I completely understand. Was hoping I wasn't the only one. Thanks for the quick reply.
-- Jim C.

    On Saturday, November 5, 2022 at 06:32:46 AM EDT, GregValiant ***@***.***> wrote:  
 
 


Thanks for the report.
This has been coming up a lot.

"Backend exited abnormally with return code 3221225477!"

This is the 20th report of this behavior. I'll mark this as a duplicate and close it as plenty of models have been submitted that show the problem and the Cura Team has plenty to work with. I hope you understand.

**Comment by MariMakes** [comment]
Hey @will-maxim,

Thanks for your report 👍

Return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅 
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors. 
Can you download the Beta and retry your slice? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, we'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
