### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by Antrioch** [Ultimaker/Cura#13735]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Anycubic Mega X

### Reproduction steps

Closed and reopened slicer multiple times.
redownloaded the files multiple times.

### Actual results

Always gives the same error

### Expected results

slice the file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
Thanks for the report.
Without the Cura.log file and a Project File we have nothing to investigate.  If you would zip those files and upload the zip folder here then someone will take a look.
"Help | Show Configuration Folder" will take you to the cura.log file location.
"File | Save Project" will create a project file with your printer, the model, and all your current settings.
