### ISSUE TITLE
Expert Mode in Cura 2.3.1?

### ISSUE THREAD

**Issue by kjgipp** [Ultimaker/Cura#1373]
Does Cura 2.3.1 still have an "Expert Mode" in it?  If so how to I access this mode?

**Comment by kjgipp** [comment]
Never mind, just found that that the "Expert Mode" is called "Custom", and not Expert

**Comment by Ghostkeeper** [comment]
When we re-designed the front-end we moved a couple of things around. What was originally Basic Mode is now called "Recommended". What was originally Advanced Mode is now called "Custom". What was originally Expert Mode is now in the form of the setting visibility screen. We consider the settings that are not visible by default to be expert settings.
