### ISSUE TITLE
Scaling error after opening a .3MF file from 3D-Builder

### ISSUE THREAD

**Issue by Speedy-McCat** [Ultimaker/Cura#13748]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

The following steps produced the "error":

1. Open the original STL file in Cura
2. Scaling to e.g. 89%
3. save as project file
4. open this project file in 3D Builder
5. the message appears: the object has an error
6. started the auto repair from the 3D builder
7. the file is saved as a .3MF file
8. now opened in CURA, the message appears that the scaling is set to 10000
[Original_fixed-headlight-repaired.zip](https://github.com/Ultimaker/Cura/files/9946637/Original_fixed-headlight-repaired.zip)
[after saving to 89% in CURA_headlight-repaired.zip](https://github.com/Ultimaker/Cura/files/9946638/after.saving.to.89.in.CURA_headlight-repaired.zip)
[File after saving from 3D-Builder_headlight-repaired.zip](https://github.com/Ultimaker/Cura/files/9946639/File.after.saving.from.3D-Builder_headlight-repaired.zip)

### Actual results

After loading the .3MF file, a scaling of 10000 is displayed

### Expected results

The file should appear as a Printable Object in the previously scaled size.
[cura.log.zip](https://github.com/Ultimaker/Cura/files/9946661/cura.log.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

The files are already uploaded.

**Comment by GregValiant** [comment]
Thanks for the report.
I have seen this behavior from 3D Builder myself and I think it's a 3D Builder problem.  If you save the file in 3D Builder as an STL the problem will go away.
Let me know if that works for you.  I believe Cura is simply opening the file the way 3D Builder saved it so the bug would be in the Microsoft program.
