### ISSUE TITLE
Support is disrupted by a brim

### ISSUE THREAD

**Issue by 3DAmsterdam** [Ultimaker/Cura#13742]
### Application Version

5.2.1

### Platform

Ubuntu 22.04.1 LTS

### Printer

Ultimaker 2+/E3D hotend

### Reproduction steps

I try to slice a ring for NGen-flex wit a brim. The support did not appear very well and after I activated the brim it becomes even worse. She support should  rest on the brim bud it disappears 
![Schermafdruk van 2022-11-06 12-55-20](https://user-images.githubusercontent.com/9759412/200169259-76ff09b8-5b6a-4c80-ab36-d7d185d6570f.png)

### Actual results

Result is a support-roof flying in the air. 

### Expected results

The support should rest on the brim. Cura 5.1.1 has no problem with it.
[CuraGcodeFail.TXT](https://github.com/Ultimaker/Cura/files/9945799/CuraGcodeFail.TXT)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don´t know additional files you need.

**Comment by MariMakes** [comment]
Hey @3DAmsterdam 

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

We have a known issue with support for smaller parts.
You can read more about how to avoid it here:
https://support.ultimaker.com/hc/en-us/articles/6103470096028

If  that doesn't help.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
