### ISSUE TITLE
layers turned floating after rotated 90 degrees

### ISSUE THREAD

**Issue by kitopitodave** [Ultimaker/Cura#1374]
I'm having an issue with parts of my model becoming empty layers when rotated 90 degrees to its side. The issue goes away if I removed the pole from the model or have the pole pointing up instead of on the side (but will need to print supporting structures, which adds another 2hrs). 

I've attached the stl files.  Is this a cura issue or sketchup issue? 

Cura 2.3.1 for Mac
The model is drawn using sketchup 2017 mac version.

thanks for the help

![original](https://cloud.githubusercontent.com/assets/25318052/22239476/af109d54-e251-11e6-9f0d-c34541169c86.png)
Model sitting in the orientation as designed. No issue near pole area

![turned90](https://cloud.githubusercontent.com/assets/25318052/22240069/5265458e-e254-11e6-9252-726bf1676ac2.png)
model turned onto its side for faster printing without supporting structure. However, parts of the model turned empty near the pole area. 

![rendered-fine-no-pole](https://cloud.githubusercontent.com/assets/25318052/22239856/45ff8d28-e253-11e6-95f7-452d247d04fc.png)
No issue if the pole is removed. 

[Archive.zip](https://github.com/Ultimaker/Cura/files/726044/Archive.zip)

**Comment by fieldOfView** [comment]
If you change the view mode to "XRay", you will see red areas in your model with poles. This means there is an error in your model, making the slicing result unpredictable. You *might* have luck turning on/off some of the "Mesh Fixes" in Cura.

Sketchup is not the best modeler to create models for 3d printing; it just was not designed with 3d printing in mind. I'm not saying it cannot be done, but you will run into issues like this.

**Comment by kitopitodave** [comment]
Great, thanks for the reply Aldo. I'll check on that, and maybe consider
other design software.
best.

Dave
