### ISSUE TITLE
Cura 5.2.1 fail to slice model

### ISSUE THREAD

**Issue by philbowers** [Ultimaker/Cura#13749]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality CR-10 V2

### Reproduction steps

1. Load .stl
2. Press slice
3. Failed report a bug

### Actual results

Failed to slice

### Expected results

Model to slice and generate gcode

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Fresh install of Cura 5.2.1

[cura.log](https://github.com/Ultimaker/Cura/files/9947476/cura.log)
[Buddy.zip](https://github.com/Ultimaker/Cura/files/9947483/Buddy.zip)

**Comment by MariMakes** [comment]
Hey @philbowers,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I can slice your STL just fine on my Ultimaker S5, so it's not an issue with the model.
![image](https://user-images.githubusercontent.com/40423138/200307811-7bdd58ac-c22f-4815-ab6f-216b9745592b.png)

But in your logs I can read CuraEngineBackend.CuraEngineBackend._terminate [369]: Engine process is killed. Received return code 3221225477

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏

**Comment by philbowers** [comment]
It sliced when I switched to my ender 3 it sliced just fine. Besides the obvious differences, the main difference between the two are.
Ender 3 - .4mm nozzle, upgraded 32bit mks board with 2209 drivers and, controlled with Octoprint 
CR10 - .6mm nozzle, stock creality board and, is controlled with Klipper (Fluidd)

[CCR10_Buddy_3mf.zip](https://github.com/Ultimaker/Cura/files/9963493/CCR10_Buddy_3mf.zip)

**Comment by MariMakes** [comment]
Hey @philbowers,

Thanks for sharing your files 👍

When I change your Adaptive Layers Maximum Variation from a negative to a positive number I'm able to slice your printjob.
![image](https://user-images.githubusercontent.com/40423138/200790887-d2113c99-4fcb-40cc-9978-925e8d0a7227.png)

Why do you wnat this value to be negative? 

I checked the setting defition and I don't see any maximum or minimum values for this setting. 
Probably since it's experimental.

 I'll bring it up to our print profile experts to take a look to apply proper warning values here. 👍 
 
To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by philbowers** [comment]
I see what you are saying but, I do not know where that value is stored/ changed at. And oddly it only appears in that profile.
![additive1](https://user-images.githubusercontent.com/8340735/201098056-af08ce0d-efad-4606-9569-1867a084a85d.PNG)
![additive2](https://user-images.githubusercontent.com/8340735/201098072-1ed635a0-c162-4c2e-882f-da013003cec5.PNG)
![additive3](https://user-images.githubusercontent.com/8340735/201098086-b465369b-07e0-4a78-a868-672e701bd1fb.PNG)
![Layer Height](https://user-images.githubusercontent.com/8340735/201096194-e7a48cc4-2fa8-439e-bddf-c8f718f170d0.PNG)
![Z offset](https://user-images.githubusercontent.com/8340735/201096206-4704908b-3a54-42e5-89ab-28c2870bfbcb.PNG)

**Comment by philbowers** [comment]
I do not know how that fetcher was enabled, as it wasn't selected as enable when I found it. I have set it to zero and left it disabled which, fixed the problem. I give you My Sincerest Thank You for helping solve this issue and, will be closing this issue out.
