### ISSUE TITLE
End g-code ultimaker s3

### ISSUE THREAD

**Issue by DodoSam** [Ultimaker/Cura#13755]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Ultimaker S3

### Reproduction steps

When printing there seems to be no end g-code. when the print is done the nozzle just stands still for some time and then goes away. this affects the top layer... 
In the cura software I don't see a end g-code for the printer in the settings. 

### Actual results

print head stands still on top layer and doesnt go away

### Expected results

A better end g-code...

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![IMG_3797](https://user-images.githubusercontent.com/83286973/200323696-0c258802-f56a-4aa7-a0ed-60a3b0add3ad.jpg)
[UMS3_pop.zip](https://github.com/Ultimaker/Cura/files/9952049/UMS3_pop.zip)

**Comment by MariMakes** [comment]
Hey @DodoSam,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This actually reminds me of a bug we had in the Printer Firmware a long while ago.
Are you on the latest version of the firmware?
It should be 7.1.3 for the latest or 7.0.3 for stable. 
[You can download it here:](https://support.ultimaker.com/hc/en-us/articles/360012103559-Update-the-Ultimaker-S3-firmware) 

If I have a pointy model I ususally turn on the Lift Head setting.
Can you try if this works for you? Be sure to enable it in both extruders!
![image](https://user-images.githubusercontent.com/40423138/200366205-031bcf1d-5234-4b99-ad2e-daba6c946c2d.png)

Hope this helps 👼
