### ISSUE TITLE
Нарезка на слои не выполнена

### ISSUE THREAD

**Issue by Timur78** [Ultimaker/Cura#13754]
### Application Version

5.1.0

### Platform

Windows 11 Pro 21H2 - CPU intel i5-9400F

### Printer

Anycubic  Mega X

### Reproduction steps

1.Import model
2.Setting up parameters
3.Slicing. Started automatically

### Actual results

1.Error Message
2.Eternal slicing

### Expected results

Successful slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![AI3MX](https://user-images.githubusercontent.com/80568319/200260791-d7bf8163-81f0-4664-9f81-bd4397f5e42a.png)
[3mf fille.zip](https://github.com/Ultimaker/Cura/files/9949437/3mf.fille.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9949445/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report and the supporting files.
I can reproduce this in Windows 10 and Cura 5.2.1.  This behavior has been reported previously so I'll mark this as a duplicate and close it.  I hope you understand.

A possible workaround is to rotate the model on the Cura Build plate.  That has been known to fool this bug into allowing the model to slice.  It did in my case.  It came out as about a 29 hour print.
![image](https://user-images.githubusercontent.com/64202104/200308167-d764117b-d7a8-466f-bf97-ac8d17bd645e.png)
