### ISSUE TITLE
Error slicing a simple dice set

### ISSUE THREAD

**Issue by aprat-ctrl** [Ultimaker/Cura#13760]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

lodaded up a D&D dice set STL file
Then pressed slice and the error ocurred

### Actual results

a message saying an error ocurred 
![image](https://user-images.githubusercontent.com/96742817/200464731-f9dfd886-9917-412b-9a3b-1a1e699b3dd3.png)

### Expected results

An slice shoud happen

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9957264/cura.log)
[CE3_CompleteDiceSet.zip](https://github.com/Ultimaker/Cura/files/9957271/CE3_CompleteDiceSet.zip)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/684b0cd3-8dc1-4dc8-abc4-acf201f6a837)
