### ISSUE TITLE
Preview - Color Scheme - Line Type

### ISSUE THREAD

**Issue by the-moog** [Ultimaker/Cura#13767]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

n/a

### Reproduction steps

Print settings - enable support interface
Preview - Color Scheme - Line type

### Actual results

The interface lines are drawn in purple, but missing from the above dialog so you can't hide/unhide it.

### Expected results

It should be possible to enable/disable the interface line type

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by MariMakes** [comment]
Hey @the-moog,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This is the first I've heard of this.
Do you have a screenshot for us of how what it looks like?

The first things that come to mind when I read this are Compatibility Mode and the Colorblind Theme.
Is what you are seeing similar to this? 
![image](https://user-images.githubusercontent.com/40423138/200795885-b266acf0-d170-4749-97fe-0fcdb0d8cd02.png)
