### ISSUE TITLE
model disappears

### ISSUE THREAD

**Issue by carlosrrazo** [Ultimaker/Cura#13788]
### Application Version

5.2.1

### Platform

iOS

### Printer

any cubic cobra max

### Reproduction steps

downloaded model to software as usual. opened custom support tool. attempted to select support options (print as support, support blocker, support shape, etc..)

### Actual results

model disappears

### Expected results

custom supports should be applicable after these steps

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

deleted and reinstalled all software. tried with different model files. problem still exists.

**Comment by MariMakes** [comment]
Hey @carlosrrazo,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

It's a bit difficult to troubleshoot your issue with this little information.
Are you sure you have selected the correct meshtype
![image](https://user-images.githubusercontent.com/40423138/201302957-729cc510-8523-46eb-92c5-8ea625f6d8d6.png)

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
