### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by 3dprintrecycling** [Ultimaker/Cura#13783]
### Application Version

5

### Platform

windows 10

### Printer

creality ender 5 pro

### Reproduction steps

adjusted retraction settings
rotated model 180 degrees
attempted to slice

### Actual results

slicing failed due to an unexpected error

### Expected results

model should have been sliced

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[project.zip](https://github.com/Ultimaker/Cura/files/9977196/project.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm unable to duplicate this on my Win10 laptop and using your project file.

There is an oft-reported bug that seems to be triggered by the orientation of the model on the build plate.  You can try rotating the model again and see if there is a rotation angle that will fool the bug.

I wouldn't think the retraction distance has anything to do with this but seemingly unrelated settings can cause problems.
I'll mark this as a duplicate and the Cura team will take a look.

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/5ae163de-af5e-461b-abe6-142bbad2465f)
