### ISSUE TITLE
Intelligent Combing/Moving or Specify Move Path Feature

### ISSUE THREAD

**Issue by dhingos** [Ultimaker/Cura#13794]
### Is your feature request related to a problem?

When printing parts where I am combing (combing infill only) I still wind up with stringing in empty space between areas of the model because the slicer has no problem travelling across any empty space. However I cannot clean up the part within that empty space because it is small, narrow, or has lots of angles and makes it difficult to get any sort of tool inside these spaces to clean up stringing, which is what I am trying to avoid by using combing.

### Describe the solution you'd like

I would like combing or travelling options that treat empty space inside a model or between parts of a model as if it were a printed part of the model. Alternately, I would like the option to force all combing/travelling to occur within infill areas. Either that or I would like the ability to draw/shade an area that is off limits for combing/travelling moves.

This is different than just clicking "infill only" as a combing mode or "avoid printed parts when travelling" as an option, because the slicer will still allow travel across empty space between walls even if they are within the overall perimeter of a model. 

### Describe alternatives you've considered

Combing mode, z hop, avoid printed parts when travelling, heat gun to clean up stringing in inconvenient areas

### Affected users and/or printers

all printers

### Additional information & file uploads

Here is an example of a use case - you have a model of a hairpin shaped object. You comb within infill only, and avoid printed parts when travelling. You are printing in PETG. You get stringing between the inside walls of the hairpin because of moves from one side of the hairpin to the other, when the move could be within the shape of the hairpin rather than across the gap. When the model is done it is tough to clean up stringing inside the hairpin. Yes it may take a bit more time to print with such long moves, but in some cases this is preferable to doing post processing.

**Comment by MariMakes** [comment]
Hey @dhingos,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

When you are worried about stringing between outer walls you can adjust these settings:
![image](https://user-images.githubusercontent.com/40423138/205943187-cae33003-8bc8-45a4-9ac7-8676a9c3f109.png)

Do you have an example where these settings do not help to avoid stringing?
