### ISSUE TITLE
slicing 

### ISSUE THREAD

**Issue by Janitortimm420** [Ultimaker/Cura#13796]
### Application Version

5.2.1

### Platform

windows 11

### Printer

Creality CR6-SE

### Reproduction steps

just hit slice 

### Actual results

file should be sliced

### Expected results

the product should be sliced 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

>

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project file ("File | Save Project") or Cura.Log file ("Help | Show Configuration Folder") we have nothing to base an investigation on.  You will need to zip those files and post the zip folder here.
