### ISSUE TITLE
[regression 15.06.02] Machine settings do not "take"

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#138]
Setting options in the Machine settings does not change the available options in the Print Setup panel. Even after restarting the app, new settings are not available.

Changing the same settings in 15.06.01 works, and changes carry over to 15.06.02 when it is restarted.

**Comment by awhiemstra** [comment]
That one slipped through, thank you for reporting.

**Comment by fieldOfView** [comment]
Confirmed fix

**Comment by nallath** [comment]
Thanks for confirming it.
