### ISSUE TITLE
Slicing failed with tree support on mask - Sovol SV06

### ISSUE THREAD

**Issue by BigRigCookin** [Ultimaker/Cura#13807]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Sovol SV06

### Reproduction steps

tried to put tree support on a mask im printing

### Actual results

Wouldnt slice

### Expected results

slice iwth tree supports

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/113308869/201508460-4ee98e46-4588-4476-aa31-a6c173bbdd4c.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Cura.log file ("Help | Show Configuration Folder") and Project File ("File | Save Project") there can be no investigation.
Github requires that the files be zipped and the zip folder can be posted here.

**Comment by GregValiant** [comment]
@FlyingWolf11 I sliced your file and didn't have any trouble so I am unable to reproduce the problem.  I'm on Win10.
![image](https://user-images.githubusercontent.com/64202104/201738444-e64ed208-b1e5-45a0-8954-0bed88988c16.png)

This appears 6 times in your log file:
"Backend exited abnormally with return code -11!"
Someone from the Cura team will take a look.

@BigRigCookin We could use a file from you to see if this is the same sort of error.

**Comment by FlyingWolf11** [comment]
@GregValiant I've tested something out and it seems like the slice with tree supports only fails if the model is rotated specifically. In my case the file I gave you yesterday still doesn't work but it does when it is rotated by -90 degrees on the x axis.

**Comment by GregValiant** [comment]
If the model slices when rotated then that is an often reported bug.
When it gets fixed there will be a lot of reports cleared up.

**Comment by FlyingWolf11** [comment]
That is good to know. I was thinking the tree supports could be the fault since the slicing worked with rotation and normal supports but not with rotation and tree supports.

**Comment by GregValiant** [comment]
No, it's a slicing bug as far as I know.  Mac and Linux don't seem to be affected, just Windows systems.
