### ISSUE TITLE
FORD 34 COUPE LEGENDS

### ISSUE THREAD

**Issue by lwwwhitworth** [Ultimaker/Cura#13804]
### Application Version

5.2.1

### Platform

Window 10

### Printer

Creality CR-10S Pro

### Reproduction steps

slicer show bug

### Actual results

SLICER PROBLEM

### Expected results

bug 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![Ford 34 Coupe Legends - Cristales Separados-1](https://user-images.githubusercontent.com/25962771/201491549-33274d03-d886-4c95-beaf-37582facb46f.jpg)

**Comment by Asterchades** [comment]
You have included neither a log nor a project file, despite checking the boxes. Without either of these - preferably both - no  diagnostics can be done and your issue cannot be addressed by anything more than a happy accident. Please provide one or both of these files (preferably a project).

At present the only assumption that can be made is that the model is in need of repairs before it can be properly sliced, which isn't at all uncommon for these more complicated ones.
