### ISSUE TITLE
Multimonitor usage

### ISSUE THREAD

**Issue by martin2705** [Ultimaker/Cura#13816]
### Application Version

5.2.1

### Platform

Win 10

### Printer

CR-10 v3

### Reproduction steps

I have 3 monnitors
left NM notebook 1920x1080 (normally bottom aligned)
middle LG 27" 2560x1440
right LG 27" 2560x1440

rmb click in on the bed area in cura - rmb menue pops up 10cm on the right side of the monior
all ack menues opens on another monitor, for example. the owerwrite acknolage. 
It opens on the left nb monitor in the top right are, which is not accessable/viewable cause the viewarea is alinied to the bottom.
If you align the monitor with the smaler resolution to the top of the niddle monitor, than you are able to see the ack menue.

### Actual results

rmb click in on the bed area in cura - rmb menue pops up 10cm on the right side of the monior

all ack menues opens on another monitor, for example. the owerwrite acknolage. 
It opens on the left notebook monitor in the top right are, which is not accessable/viewable cause the viewarea is alinied to the bottom.

### Expected results

rmb click in on the bed area in cura - rmb menue pops up direct unter the mousebutton

all ack menues should open on the same monitor. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![ack_menue_bottom_align](https://user-images.githubusercontent.com/102171719/201628194-7cc96754-1552-4d3a-9f4d-fb07d615feed.JPG)
![ack_menue_top_align](https://user-images.githubusercontent.com/102171719/201628200-564402ed-8f1c-4c57-abc6-acfe11f814dc.JPG)
[cura.log](https://github.com/Ultimaker/Cura/files/10001683/cura.log)
![rmb_click_bedarea](https://user-images.githubusercontent.com/102171719/201628213-bf28125e-0c12-4aa0-b5b8-9aef49aab285.JPG)

**Comment by MariMakes** [comment]
Hey @martin2705,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Curious 🤔 . This is the first time I've seen this report. 
Can you try if this workaround works for you? 
https://community.ultimaker.com/topic/41458-ultimaker-cura-510-window-scaling-problem

If that doesn't help I have two more things you can try: 
1.  Do you have GPU Tweak OSD overlay enabled? Does Cura act as expected if you disable that software?
2.. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627

If you are still stuck, let me know. 
I'll have someone from the team take a look at your issue. 
Good luck 💪
