### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Papabear77714** [Ultimaker/Cura#13811]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 5 Plus

### Reproduction steps

Opened file titled CE5P_CubeGears2-3 from https://www.thingiverse.com/thing:213946
Selected Adhesion - Skirt
Selected Slice
Error popped open

### Actual results

Error pops up thatslicing failed
Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker

### Expected results

It should complete the slice to save

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Unable to upload file

**Comment by GregValiant** [comment]
Thanks for the report.
I must have forgotten to hit the "comment" button last night.
All three of the gear files sliced for me with no issues.  We'll need a Project File ("File | Save Project") and Cura.log file ("Help | Show Configuration Folder") to debug this.  The files will need to be zipped and then the zip folder posted here (Github rules).
