### ISSUE TITLE
Slicing fail

### ISSUE THREAD

**Issue by SilverbackGamez** [Ultimaker/Cura#13814]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Ender 3

### Reproduction steps

Placed to g codes and tried to slice it.

### Actual results

slice failed with un expected error.

### Expected results

It would slice so i could print

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by MariMakes** [comment]
Hey @SilverbackGamez,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
