### ISSUE TITLE
5.2.1 freezes the application when i try to open preferences

### ISSUE THREAD

**Issue by Krominicon** [Ultimaker/Cura#13819]
### Application Version

5.2.1

### Platform

windows 11

### Printer

anycubic kobra max

### Reproduction steps

i tried to open preferences on the top menu bar.

### Actual results

cura freezes and becomes unresponsive and i have to restart it.

### Expected results

it should open the preferences menu so i can change some settings.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10005428/cura.log)

**Comment by Krominicon** [comment]
you can probably close it, it's just a bit different because it's just happening with the preferences menu.

**Comment by MariMakes** [comment]
I'll be closing this issue as a duplicate but you can follow the progress here in a single ticket: https://github.com/Ultimaker/Cura/issues/13820

I was thinking, it might also be related to https://github.com/Ultimaker/Cura/issues/13789
