### ISSUE TITLE
Cura 2.4.0 Mac (Ultimaten 2 Extended+) Custom Nozzle Size

### ISSUE THREAD

**Issue by bulior** [Ultimaker/Cura#1381]
Hey there, 

i try since days to get a variable Noozle Size within the Dropdown Menue ob the Um2 Extended plus Profile by edit the .json-files. Has someone done this before or is the solution to configure a custom FDM-Profile?

Best Regards

**Comment by nallath** [comment]
What do you mean? There already is a dropdown menu with multiple nozzle sizes.

**Comment by fieldOfView** [comment]
I think he's trying to make a custom nozzle size, eg 0.15 or 1.0.

**Comment by nallath** [comment]
Ooh. Yeah, that takes a bit more work. You need to add a variant for this to work.

**Comment by bulior** [comment]
Yeah I try it with the current Ultimaker variants but it would not be work.  Has some one done this before

**Comment by Ghostkeeper** [comment]
Well, we created them so it was done before. I'd advise to start with copying `resources/variants/ultimaker2_extended_plus_0.25.inst.cfg` and copying all the 0.25mm profiles in `resources/quality/ultimaker2_plus`. Then modify the names, IDs and nozzle sizes of those files. See how far that gets you.

**Comment by bulior** [comment]
Thanks for all comments!
I got it with the solution of Ghostkeeper. Thanks!

[http://imgur.com/a/3HqGj](`http://imgur.com/a/3HqGj`)

**Comment by nallath** [comment]
This has now also been properly fixed.
