### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by R-B-Riddick** [Ultimaker/Cura#13813]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Opened a file (Head of son goku dragonball)
2. Changed Tree Support from touching buildplate to everywhere

If i change back to touching its working again. 
the slicing takes a relatively long time and the printing time also seems longer than normal to me. 

### Actual results

slicing had an error

### Expected results

that the slice should work

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![notworking](https://user-images.githubusercontent.com/66056927/201601988-76c031b0-c626-4cc3-a6d3-7bdefc4b1ace.JPG)
![Working](https://user-images.githubusercontent.com/66056927/201601990-ce8ca43d-b3ed-4e68-9501-fbd4c6715224.JPG)
[cura.log](https://github.com/Ultimaker/Cura/files/10000621/cura.log)

[CE3PRO_Cabeza 01.zip](https://github.com/Ultimaker/Cura/files/10000604/CE3PRO_Cabeza.01.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Your project sliced fine for me so I am unable to duplicate the problem.

There have been several reports about a slicing bug that can sometimes be fooled by rotating the model on the build plate.  Give that a try and let us know if it works.
I'll leave this open and as a bug report for now.
![image](https://user-images.githubusercontent.com/64202104/202073973-9fb2b9f1-797b-4394-8ae2-053ace2cb730.png)

**Comment by R-B-Riddick** [comment]
You are right. I just opened it again and sliced it without moving and it worked. Guess there was something else in my profile. I'm sorry that you had to do more work unnecessarily
