### ISSUE TITLE
program freezes when navigating folders

### ISSUE THREAD

**Issue by Jimrost** [Ultimaker/Cura#13828]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. opened program
2. tried navigating the open file menu
3. when I try to switch folders, the program freezes and does not recover.
4. I have to close the program by forcing it to shut down.

### Actual results

Nothing, If I try to open the program again, it does the same thing.  
I uninstalled the program and reinstalled to the latest version, and it does the same thing.

### Expected results

I expect the program to navigate through folders so I can open up a project or file.
It does not.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

can't find log file

**Comment by MariMakes** [comment]
Hey @Jimrost ,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Your issue reminds me of: https://support.makerbot.com/s/article/1667412729970
But that should be resolved in 5.0 and up.

You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

But I think in this case it would be more valuable for us to have your configuration file.
You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 😇
