### ISSUE TITLE
Mirrored STL file make slicing fails

### ISSUE THREAD

**Issue by lucviala** [Ultimaker/Cura#13821]
### Application Version

5.2..1

### Platform

Windows 10

### Printer

Creality Ender-3 Pro

### Reproduction steps

1. Load STL file into Cura downloaded from thingiverse.
2. Slicing with 0.6mm nozzle, 0.28mm layer height, 20% infill, tree support, no adhesion.
3. Slicing completes successfully.
4. Save generated gcode file.
5. Mirroring loaded STL file using Cura
6. Slicing with 0.6mm nozzle, 0.28mm layer height, 20% infill, tree support, no adhesion.
7. Slicing crashes.

I also tried to load the already mirrored STL file:
1. Mirror the STL file.
2. Load mirrored STL file into Cura.
3. Slicing with 0.6mm nozzle, 0.28mm layer height, 20% infill, tree support, no adhesion.
4. Slicing crashes.

### Actual results

Got 'Slicing failed' error pop-up with the following message:
'Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.'

### Expected results

Slicing is not supposed to fail. So I expect Slicing to be successful.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Files available [here](https://filetransfer.io/data-package/4BSj6t09#link).

**Comment by GregValiant** [comment]
Thanks for the report and the files.
I was able to slice the model as received.  I checked it with Mesh Tools and it reported that it wasn't "watertight".
Then I mirrored the model in Cura and once again it sliced fine.
So I can't duplicate the problem.

You might try repairing the model in MS 3D Builder and see if it makes a difference.  It only took a couple of seconds to make the repairs so I'm assuming the errors are minor.
![image](https://user-images.githubusercontent.com/64202104/201742231-9b84e9b7-3783-47a7-9b7f-547437198a98.png)

There were several reports of a slicing bug that could be fooled by moving and/or rotating the model on the build plate.

Let me know if either of those have an effect and I'll update this thread for the Cura team.

Here is the repair report from OnLineSTLRepair.  It's not as minor as I thought.
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 44 Non-manifold edges (?)
--> 62 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 45 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 2978ms ------
-> Vertex count changed from 7150 to 7212 (+62)
-> Triangle count changed from 14464 to 14660 (+196)
