### ISSUE TITLE
Part of the model is visible in the prepare mode, but does not come in preview

### ISSUE THREAD

**Issue by stemsin** [Ultimaker/Cura#13831]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Anycubic Viper

### Reproduction steps

1. Prepared a model in Blender
2. Exported it to STL
3. Created a new project in cure
4. Imported the STL
6. Sliced the model and created gcode file
7. Printed the gcode file

### Actual results

7. while printing part of the model did not come in plastic
8. also, found out that part is not coming in the preview mode also

### Expected results

7. the printed model is matching the one in prepare mode
8. the preview is matching the prepare mode also

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![prepare](https://user-images.githubusercontent.com/19945914/201975517-d18b4ee6-8619-4274-ba06-20cc799c3f77.png)
![preview-1](https://user-images.githubusercontent.com/19945914/201975546-56bec9b0-252d-418c-91e4-be8488744a6c.png)
![preview-2](https://user-images.githubusercontent.com/19945914/201975570-095d9254-b6d9-40c2-a44a-4c3ef051aa16.png)
[project.zip](https://github.com/Ultimaker/Cura/files/10014537/project.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You need to check models after bringing them in to Cura.  If there are errors they can fool the slicer and you can end up with missing features or other errors.
The model you uploaded is on the right and Cura called it "not watertight".  You can see the red area on your model indicating an error where the boss is supposed to be connected.  The model on the left was repaired in MS 3D Builder.

![image](https://user-images.githubusercontent.com/64202104/202006037-adc20f53-9aba-4da9-bb33-931fc1131fd9.png)

Here is the slice.  The boss made it through the process.
![image](https://user-images.githubusercontent.com/64202104/202005863-791f95f9-3991-4fd3-ae41-49efb39630c6.png)

Repair the model and try again.  This doesn't appear to be a Cura bug but rather a problem with your model.

**Comment by GregValiant** [comment]
I'll go ahead and close this.  If you feel that is premature let us know.
