### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by Arbuzek** [Ultimaker/Cura#13832]
### Application Version

5.2.0

### Platform

Win 11

### Printer

Ender 3v2

### Reproduction steps

I sliced a model

### Actual results

it cannot slice
[cura.log](https://github.com/Ultimaker/Cura/files/10015668/cura.log)

### Expected results

It would slice

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10015686/cura.log)

**Comment by MariMakes** [comment]
Hey @Arbuzek,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

There is not enough information for me to help you troubleshoot.
In your logs I can see you had a crash:
```
CuraEngineBackend.CuraEngineBackend._onBackendQuit [959]: Backend exited abnormally with return code 3221225477!
CuraEngineBackend.CuraEngineBackend._terminate [359]: Attempting to kill the engine process
CuraEngineBackend.CuraEngineBackend._terminate [365]: Killing engine process
CuraEngineBackend.CuraEngineBackend._terminate [368]: Engine process is killed. Received return code 3221225477

```
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by MariMakes** [comment]
Hey @Arbuzek ,

In the mean time we learned that return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅 
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors. 
Can you download the Beta and retry your slice? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, we'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
