### ISSUE TITLE
cura bug  decoupe

### ISSUE THREAD

**Issue by dussaultj** [Ultimaker/Cura#13845]
### Application Version

5.2.1

### Platform

win 10

### Printer

cura 5.2.1

### Reproduction steps

bug decoupe avant impression

### Actual results

nothing

### Expected results

nothing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

nothing

**Comment by MariMakes** [comment]
Hey @dussaultj,

Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Your report is missing the information we need to troubleshoot. 😞 
We need at least a screenshot or a project file to troubleshoot. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Merci 😇
