### ISSUE TITLE
Slicing promblem

### ISSUE THREAD

**Issue by Maximiliano3D-printer** [Ultimaker/Cura#13849]
### Application Version

5.2.1

### Platform

Window 11

### Printer

Kobra max

### Reproduction steps

He says it works with slicing

### Actual results

nothing 

### Expected results

nothing 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

nothing

**Comment by GregValiant** [comment]
Thanks for the report.
Since your "expected results" are "nothing" and your "actual results" are "nothing" then I don't see a bug here.
I'll remove the bug label and go ahead and close this as my investigation shows nothing which appears to be what you expected.
