### ISSUE TITLE
Support orientation

### ISSUE THREAD

**Issue by gwiethaus** [Ultimaker/Cura#13846]
### Is your feature request related to a problem?

One idea is to improve the placement of supports according to the selected plane X or Y. It is necessary that the support not only be angled for all orientations (as it already exists), but also be able to place the support in an arrangement of 90 or 0 degrees according to the X or Y orientation of the part.

### Describe the solution you'd like

none

### Describe alternatives you've considered

none

### Affected users and/or printers

users e printing quality

**Comment by GregValiant** [comment]
Are you talking about the "Support Infill Line Directions"?
This is at the default (empty square brackets as "[ ]") for both the (Lines) Support Infill and the (Grid) Infill.
![image](https://user-images.githubusercontent.com/64202104/202475539-e28577f4-0a2e-4fbf-8407-d18ee11f560b.png)

This is with the "Support Infill Line Directions" at 45° ([45]) and the Infill at [45,90].
![image](https://user-images.githubusercontent.com/64202104/202475062-e18ffe6f-9783-4788-ab7e-038dc3fd6781.png)

I didn't know this but unlike the "Infill Line Directions" the "Support Infill Line Directions" doesn't support multiple angles.

**Comment by Asterchades** [comment]
> I didn't know this but unlike the "Infill Line Directions" the "Support Infill Line Directions" doesn't support multiple angles.
That's curious. I've been using multiple angles for support infill (specifically [0, 90]) since they added the feature without issue. I even checked again just now and it's working fine as of 5.2.1 - all of the line-based patterns (ie Not Cross, Gyroid, or Concentric) at whatever angles I throw at it (going past ten different ones felt superfluous).

**Comment by GregValiant** [comment]
@Asterchades it is curious.  I just tried again at [45,135] with Lines and with ZigZag and it doesn't work on my install (5.2.1).  With it set to something like [135,90] it will only use the first parameter and the second is ignored.
In 4.13.1 it works as expected.

Curiouser and curiouser...
I looked closer at the 5.2.1 preview.  This is the layer immediately prior to the first layer of Support Interface.
I get the 45° support infill on the left side only, and only on this single layer.  (This is with Win10.)
![image](https://user-images.githubusercontent.com/64202104/202693905-c7d47d0b-7b9c-4df7-bee5-a86811eeebc4.png)

**Comment by MariMakes** [comment]
Hey @gwiethaus,

Can you let us know if  "Support Infill Line Directions" is the solution you are looking for? 
To me, it seems to solve your problem. 🤔 
If it's not, can you let us know how your solutions should be different? 

Thank you 🙏
