### ISSUE TITLE
i dont know 

### ISSUE THREAD

**Issue by Vojtas77** [Ultimaker/Cura#13855]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Anycubic Kobra / Viper

### Reproduction steps

not any reaction for start sliceding 

### Actual results

restarting proccesing for start again

### Expected results

shudle start normally

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

set up for exta fine and nothing happened

**Comment by GregValiant** [comment]
Thanks for the report.
Unfortunately I don't know either and unless you provide a project file ("File | Save Project") and the cura.log file ("Help | Show Configuration Folder") we'll probably never know.  The two files need to be zipped and the zip folder posted here.
