### ISSUE TITLE
Camera view in cura frozen

### ISSUE THREAD

**Issue by KarelTenkink** [Ultimaker/Cura#1385]
Data and camera are frozen and is no longer counting.
I've send the STL via wifi.

ABS black +Innofill PVA print 26h to go
Ultimaker 3 extended
Cura 2.3.1
MacOS Sierra 10.12.2

Can I close Cura during printing and restart?

**Comment by fieldOfView** [comment]
It is safe to close Cura when printing over Wifi. You don't even have to have Cura open while printing over Wifi; once the print is sent, the UM3 prints by itself.

**Comment by KarelTenkink** [comment]
Awesome, thank you for your quick response.
