### ISSUE TITLE
Infill speed definition in materials is beeing ignored

### ISSUE THREAD

**Issue by dgrat** [Ultimaker/Cura#13864]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Custom Build

### Reproduction steps

This problem happens with 2/3 of my printer profiles

I use the material settings plugin
![grafik](https://user-images.githubusercontent.com/4668178/202915522-2b064b9e-c6b7-46f8-bbd0-07894b987a05.png)

I define a speed
![grafik](https://user-images.githubusercontent.com/4668178/202915596-e2b0d19e-ccca-4a47-9494-d337a1c55cf4.png)

I see the setting is ignored
![grafik](https://user-images.githubusercontent.com/4668178/202915611-e361c434-b90f-41de-ba3d-c5c963954340.png)

### Actual results

The print speed of the infill is much bigger 167 mm/s instead of 100 mm/s.
I find no hint in the cfg files why this happens with 2/3 printers. 

### Expected results

Setting in material definition should be used.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Downloads.zip](https://github.com/Ultimaker/Cura/files/10050266/Downloads.zip)

**Comment by Asterchades** [comment]
This is an issue with the plug-in, not the base Cura. You'll want to discuss this with fieldOfView on the appropriate repository: https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/

Note also that if you right-click on a value with the plugin installed there's also an option to "Use value from material", which may correct what you're seeing.
