### ISSUE TITLE
Cura 5.2.1 slow and freeze when play with parametres menu

### ISSUE THREAD

**Issue by Alama32** [Ultimaker/Cura#13861]
### Application Version

5.2.1

### Platform

windows11

### Printer

custom new for Tenlog 3D pro Idex

### Reproduction steps

i'm under Win11, When I go to the settings for my printer or to add one, when I go to the extruders to add a new material or in Profil, Cura, at best starts to slow down seriously, and at worst, I I have this: 

My config:
CPU XEON 3,5gh
32 G RAM ECC
HD 250 GB Corsair M2
GPU Nvidia GTX 1060 6 Gram

### Actual results

![316206407_10229086302046366_6713296813362425094_n](https://user-images.githubusercontent.com/1370864/202911668-5971e8f2-44d3-4a66-be59-9502d62fe019.jpg)

### Expected results

work without slowness or freezing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

He seems, i haven't log file .. i scanned all C: (with windows) and nothing found.

**Comment by j-snijder** [comment]
Same here

**Comment by MariMakes** [comment]
Hey @Alama32,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Thanks for your report 👍
We are seeing more reports about slow-running Cura's on Windows 11.

We are investigating how we can resolve this. 
I'll be closing this issue as a duplicate but you can follow the progress here:  https://github.com/Ultimaker/Cura/issues/13820
