### ISSUE TITLE
City of Tarok Road Side Inn: tower_room_top.stl

### ISSUE THREAD

**Issue by salvatoretramuto** [Ultimaker/Cura#13879]
### Application Version

5.2

### Platform

macOSMonterey 12.6

### Printer

ANYCUBIC S

### Reproduction steps

1. updated download file model
2. sliced file model

### Actual results

Slicing Failure: Slicing failed with an unexpected error. Report bug.

### Expected results

file to slice like remainder of model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![upper rooms](https://user-images.githubusercontent.com/117738931/203415938-322e7246-efe8-45c7-8734-0c767c86e6d7.jpg)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project File ("File | Save Project") and a cura.log file (@ "Help | Show Configuration Folder") there can be no investigation.  Zip those files and post the zip folder here.

**Comment by salvatoretramuto** [comment]
[tower_room_top.zip](https://github.com/Ultimaker/Cura/files/10075635/tower_room_top.zip)

**Comment by salvatoretramuto** [comment]
Please find Zip of file. Thank you and Happy Thanksgiving!

**Comment by GregValiant** [comment]
![image](https://user-images.githubusercontent.com/64202104/203560650-9847e563-8fd7-4aa0-a332-7cfad9dd7d9f.png)

The model doesn't appear to have any errors and sliced for me.
This is why we ask for a "Project File".  With nothing to check but the model I find it to be OK and I can't duplicate the problem.  It may be your printer, or your settings, or a Cura bug.
