### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by pocketscience** [Ultimaker/Cura#13880]
### Application Version

5.2.1

### Platform

Mac OS

### Printer

Ender 3

### Reproduction steps

Download this STL. Immediately fails to slice.

https://www.thingiverse.com/thing:5591649/files

### Actual results

Fails to slice. Suggests filing bug. Here we are..

### Expected results

expected it to actually slice the STL...

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3E3V2_Rib_Knit_Round_Bowl.3mf.zip](https://github.com/Ultimaker/Cura/files/10071238/CE3E3V2_Rib_Knit_Round_Bowl.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10071250/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the file so I can't reproduce this.  One thing you might try is to rotate the model on the Cura build plate.  Let us know if that works for you.  That bug has been reported a few times and can be fooled by rotating and/or moving the model.
![image](https://user-images.githubusercontent.com/64202104/203559764-c210bd28-eeb0-4faa-94ce-1644dd90ba1c.png)
