### ISSUE TITLE
Loosing models material setting, if PC idle for some time

### ISSUE THREAD

**Issue by structab** [Ultimaker/Cura#1388]
If I leave the PC (win10) for a while (hours?) and the screen has gone black, and CURA (2.3.1) has lost the connection to the printer (Ultimaker3) then CURA reslices models with material 1. Ultimaker3 normal have PVA in PrintCore1, and that's normally not what I want to print with.

**Comment by Ghostkeeper** [comment]
Oh, boy. This is going to be fun to test! 🤣

**Comment by Ghostkeeper** [comment]
Turns out we already knew about this from an internal report. For reference of our developers: CURA-3059. It's scheduled for release 2.6 at the moment.

**Comment by structab** [comment]
Thanks !
Any estimations om how long a "while" is ?

**Comment by Ghostkeeper** [comment]
We try to release a release every 2 months, so it would be like for May or June. In practice it's a bit slower though.

**Comment by Ghostkeeper** [comment]
This was just kicked off of our planning because it's been inactive for too long... I protested this because people hate having to re-authenticate, but it didn't make it nonetheless.

**Comment by nallath** [comment]
The re authenticate issue should already be solved because of another issue report.
