### ISSUE TITLE
cura2.0被修改了输出文件格式

### ISSUE THREAD

**Issue by a5421306** [Ultimaker/Cura#13893]
### Is your feature request related to a problem?

Unable to save as G-coode

### Describe the solution you'd like

Save as G-coode

### Describe alternatives you've considered

The software has been modified

### Affected users and/or printers

Special industry users

### Additional information & file uploads

![QQ截图20221125122859](https://user-images.githubusercontent.com/43923937/203903610-88e13521-9e91-434f-9960-54dc0832792a.png)
![QQ截图20221125122935](https://user-images.githubusercontent.com/43923937/203903615-025c72ff-b2e4-4c3f-adbf-114479c1ca86.png)
![QQ截图20221124122038](https://user-images.githubusercontent.com/43923937/203903619-e36a3c4d-056f-4b7a-8112-1308a669bad9.png)
![QQ截图20221124122112](https://user-images.githubusercontent.com/43923937/203903625-de193715-a2ef-4d97-add9-5e7c28ccb0b5.png)

![QQ截图20221124122051](https://user-images.githubusercontent.com/43923937/203903620-5a2079fc-ec4d-4f3f-a1a2-00c686974176.png)

**Comment by fieldOfView** [comment]
This seems to be a heavily modified version of Cura. We don't know what they changed, nor even what version of Ultimaker Cura it is based on. Please ask whoever made this version of Cura for support.
