### ISSUE TITLE
Duplicate model causes slicing error after copy is moved

### ISSUE THREAD

**Issue by bbum** [Ultimaker/Cura#1389]
Starting with the STL from here:

http://www.thingiverse.com/thing:1863728

Drag the STL onto Cura.

Either drag a second time or duplicate.

Drag the second copy so it is aligned on the X axis with the first.

If you look closely, the X part of the vertical structure is no longer filled in on the copy.   The resulting print is unusable.

Cura 2.1.99-master.2016.09.30

![1 drag one on](https://cloud.githubusercontent.com/assets/2791/22407760/849c5a30-e621-11e6-92ed-a883b614935e.png)

![2 make a copy](https://cloud.githubusercontent.com/assets/2791/22407761/849ce04a-e621-11e6-8050-6a2d35341e04.png)

![3 drag original to side](https://cloud.githubusercontent.com/assets/2791/22407759/849c3c80-e621-11e6-92c3-5daed5c39204.png)

![4 drag copy in line with orig](https://cloud.githubusercontent.com/assets/2791/22407758/8481cbd4-e621-11e6-99a4-58512e982369.png)

**Comment by bbum** [comment]
Realized I was running an ancient version.   Checked against current production release (2.3).   Bug still occurs.

**Comment by fieldOfView** [comment]
I think this can be fixed by turning off one of the meshfixes that is turned on by default.

**Comment by Ghostkeeper** [comment]
I don't really see the problem when I try this. It's got infill. It looks like it would print properly.

![image](https://cloud.githubusercontent.com/assets/2448634/22463748/9df73fde-e7b3-11e6-8857-090a55047eca.png)

It's not really clear from the original screenshots either. Perhaps I'm misunderstanding what this is about. Is it about infill missing?

**Comment by bbum** [comment]
@Ghostkeeper wrote:
> It's not really clear from the original screenshots either. Perhaps I'm misunderstanding what this is about. Is it about infill missing?

Look closely at the left hand tower in the last screenshot in my original post.

It isn't an infill issue, there are parts of the model flat out missing where the upright bits form the X.

Yours looks like it is correct.   What version of Cura are you using?   It may also be because of the mesh fix issue @fieldOfView mentioned.

**Comment by Ghostkeeper** [comment]
I was using master, which is currently more or less the same as the 2.4 beta that you can find on the Ultimaker website. Perhaps it has been fixed since then. We did tweak some bits with wall outlines since 2.3.

**Comment by bbum** [comment]
Thank you, @Ghostkeeper.

I'll give it a shot soon and will update this bug with the results.
