### ISSUE TITLE
Bug when Slicing

### ISSUE THREAD

**Issue by Jcoulter24** [Ultimaker/Cura#13902]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

FLsun Super Racer

### Reproduction steps

Open Cura, Open STL, Click Slice

### Actual results

Slicing... appears, blue bar goes all the way to the end and disappears, Slicing... stays. Cancel button does not work. Hit X button to close program. Ultimaker-Cura.exe pops up and says its not responding. Close the program clicked, program closed. 

### Expected results

It should slice the file as normal, instead I have to close and open the program at least 10 times to get each file to slice.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Cant attach a file because it wont slice at all

**Comment by GregValiant** [comment]
Thanks for the report.
You don't need to slice the model.  Load the model, set Cura up to slice, then use the "File | Save Project" command to create a 3mf project file.  Zip the file and post the zip folder here.
If you include the Cura.log file ("Help | Show Configuration Folder" will take you to it) in the zip folder that would be good.  More information is better and right now we have none.
You can try rotating the model on the Cura build plate and see if that allows it to slice.  That is a bug that has been reported numerous times.
Let me know if rotating the model works for you.
