### ISSUE TITLE
SLICING FAILED WITH AN UNEXPECTED ERROR

### ISSUE THREAD

**Issue by BABYRC** [Ultimaker/Cura#13904]
### Application Version

5.2.1

### Platform

windows 10

### Printer

ENDER 3 MAX

### Reproduction steps

just did some minor adjustments on layer height and speeds

### Actual results

the error occured i did restart cura but still failed slicing i restart pc and the same error happens now i cant slice anything

### Expected results

it should have sliced

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![2022-11-26 (1)](https://user-images.githubusercontent.com/119114946/204090427-8b51f46d-fa13-4389-a456-caf9db60d20a.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We can't do an investigation without a Project File ("File | Save Project") and Cura log file ("Help | Show Configuration Folder").  If you could zip those up and post the zip folder here then someone will be able to take a look.
