### ISSUE TITLE
lower movement slider not showing and wierd lines showing

### ISSUE THREAD

**Issue by pratyushganguly** [Ultimaker/Cura#13905]
### Application Version

5.2.1

### Platform

windows 11

### Printer

custom

### Reproduction steps

1. I uninstalled some plugins

### Actual results

1. Not showing the slider which shows the nozzle movement.
2. showing weird thin lines in the layer lines instead of proper layers (screenshots attached)

![CFFFP_thecorner - Ultimaker Cura 26-11-2022 19_23_28](https://user-images.githubusercontent.com/97211696/204092564-208e7844-c170-4e89-988c-fe3fd3e29bd6.png)
![CFFFP_thecorner - Ultimaker Cura 26-11-2022 19_31_29](https://user-images.githubusercontent.com/97211696/204092615-de034976-6a3f-4b2a-9c28-2c70f0294035.png)

### Expected results

Show lower slider and properly color coded layers

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

kindly help with any settings (if aplicable).
my cura screen is not showing the layers as it used to show, crisp and clean. (probably in previous versions)
tried 3mf as well as stl

**Comment by GregValiant** [comment]
Thanks for the report.
Try going to Preferences / Configure Cura and in the Viewport settings make sure "Force Layer View Compatibility Mode" is not checked.
Your computer must have OpenGL 4.0 or later drivers.  If the computer has two video subsystems you may have to get it to use the more capable one with Cura.
This is probably not a Cura bug.  I'll leave the label on so you can respond here and let us know if you found the problem.

**Comment by pratyushganguly** [comment]
![CFFFP_thecorner - Ultimaker Cura 29-11-2022 19_09_53](https://user-images.githubusercontent.com/97211696/204544002-d5c58379-2074-48e6-991d-1f65ba96c50d.png)


Thanks @GregValiant for your help, both of my problems are resolved by unchecking "Force Layer View Compatibility Mode".
I have not yet checked OpenGL 4.0.

Thanks again.

**Comment by GregValiant** [comment]
If your preview is showing "sausages" instead of flat lines then you must have OpenGL 4.1 or higher.  If you didn't then Cura would default back to Combability mode without any user input.
