### ISSUE TITLE
Bed Temperature Setting not removable from Profile

### ISSUE THREAD

**Issue by r-schmidtke** [Ultimaker/Cura#13912]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Custom Printer

### Reproduction steps

1. Create custom Profile
2. Set a bed temperature
3. Update custom Profile with current settings

### Actual results

Bed temperature set in Material does no longer affect Bed Temperature setting.
There is no way to remove the Bed Temperature Setting from the current Profile. 

### Expected results

There should be a way to remove the Bed Temperature setting from the profile, so that the temperature set in the material profile can be used.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

There is no f(x) button to revert it and no other way to remove the set value like there is for the print temperature.

**Comment by MariMakes** [comment]
Hey @r-schmidtke,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Removing settings from a profile is indeed harder than adding them.

If you want to remove the setting, here are the instructions you can find your profiles here: 
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Quality_Changes folder
	4. For every profile in Cura, you have at least 2 files representing your setting. 
	5. Select the file without the extruder in the file name
	6. Remove the line that says "material_bed_temperature =" 
	
Then your Cura will not listen to the profile but will take the default setting. 

Is this the information you are looking for?
