### ISSUE TITLE
Raft doesnt slice correctly

### ISSUE THREAD

**Issue by Corallus-Caninus** [Ultimaker/Cura#13922]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

FLsun Q5

### Reproduction steps

sliced a model with raft settings

![Uploading image.png…]()

### Actual results

raft skipped a significant section of the second raft layer

### Expected results

a complete raft should have been rendered.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[FQ5_extender_30deg.zip](https://github.com/Ultimaker/Cura/files/10110216/FQ5_extender_30deg.zip)

there wasnt an error so I didnt upload log files. I can follow up with this later if necessary but the bug should be reproducible unless I am being hacked.

**Comment by GregValiant** [comment]
Thanks for the report.
I don't see a difference between the base raft layer and the upper layers.  They all look to be the same shape.  I have to say though that when I opened the gcode in Cura it was a really poor visual representation of the gcode.  I haven't seen that before.

I read the gcode into AutoCad and everything was there as it should be.  All the raft layers were the same shape as I expected to see.  The three layers are present throughout.  (I could have colorized better).
There are about 1.2 million line segments to display and that could be taking a toll.
![Untitled](https://user-images.githubusercontent.com/64202104/204704849-189113ef-05a5-4ec5-b399-f58fa403ca8a.png)

I'll leave the bug label on this for now but I'm inclined to remove it as the raft was fine but there might be something to check with the display of the preview.  If you could load the Cura.log file it could be helpful with this.

BTW The model has a flipped normal on the top surface.  MS 3D Builder was able to repair it but it doesn't look correct to me and those two top holes didn't get covered.  You would need to address that in CAD.
![image](https://user-images.githubusercontent.com/64202104/204703896-225d00fe-dd3e-4d9c-b3ef-c49a132df928.png)

More images.  I dropped the infill to 7% to get rid of a bunch of lines and this looks as it should.  I think this points to either Cura or the video systems being overwhelmed by the number of really short line segments.
Bottom Raft Layer.
![image](https://user-images.githubusercontent.com/64202104/204706068-396b2e46-b0cc-4366-b451-15836130bae5.png)

Next layer up
![image](https://user-images.githubusercontent.com/64202104/204706192-5a28a041-0324-450a-aa0c-da3199e6485c.png)
