### ISSUE TITLE
Request: Some way to identify which model is which after loading?

### ISSUE THREAD

**Issue by ntoff** [Ultimaker/Cura#1392]
I tried hovering, right clicking, looking all about the UI but can't see anywhere that indicates which model is which or which model is currently selected. I have several which are very similar in appearance, some need duplicates others don't but once they're all imported it's hard to tell which one is which since they all look the same and there's no name list. Is my only option seriously to use another program to duplicate them, plate them, then import that into cura?

Using 2.4 beta on windows 10.

**Comment by Ghostkeeper** [comment]
Eh, good one. Perhaps we could solve this by adding a non-clickable header to the context menu when you right-click a model or something?

There's a plug-in that does allow this among other things: https://github.com/sedwards2009/cura-god-mode-plugin

**Comment by fieldOfView** [comment]
Or we could use the new legend area to show the names of loaded objects when in solid mode, indicating which models are selected by making them bold.

**Comment by Ghostkeeper** [comment]
That would be more discoverable, but also takes some real estate though.

**Comment by Ghostkeeper** [comment]
Our product manager just closed this for being inactive for 3 months.

**Comment by nickthetait** [comment]
A little justification for this under-appreciated issue. :wink:  All from from my own personal experience.
* At least 8 different people have asked me for this feature (verbally, indirectly or otherwise)
* This feature would provide significant benefit to usability
* The level of effort is quite low. I suggest simply displaying a text label above the field for the project name

**Comment by Ghostkeeper** [comment]
Relatedly, one of the designs for a future version of Cura featured a model tree, which shows all models on the build plate and would be clickable to select the model in question.

**Comment by Ghostkeeper** [comment]
I think the model tree idea has been shot down by now. Haven't heard of it recently and they've been going in another direction with their designs.

**Comment by alekseisasin** [comment]
Hi @ntoff , Cura has feature "Use multi build plate functionality". To enable it please open Preferences and you will find it in Experimental section. This feature allows to arrange models on the different build plates and identify models after loading.

**Comment by ntoff** [comment]
Thanks, but unfortunately I moved away from Cura. Hopefully it'll help someone else though.

**Comment by ianpaschal** [comment]
Closed in favor of discussion of #3535.
