### ISSUE TITLE
No Slice

### ISSUE THREAD

**Issue by Nesty39** [Ultimaker/Cura#13929]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

1. No slice

### Actual results

No slice

### Expected results

slice for print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Uploading chimuelo-mica_listo20200725-717-1uvo4e4.zip…]()

**Comment by GregValiant** [comment]
Thanks for the report.
Could you try posting that zip file again?  What is there is just a link to this page.
