### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by ninjajoejohn** [Ultimaker/Cura#13933]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Anycubic Vyper

### Reproduction steps

1. Loaded STL
2. Sliced
3. Sliced failed

### Actual results

Slicer failed

### Expected results

Sliced my image so i could print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/119460511/204668241-24327c3e-5739-477d-adfd-67ea28292671.png)

![image](https://user-images.githubusercontent.com/119460511/204668309-c1b341d9-8100-4036-9edf-cafd69fcbef7.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and log file there can't be an investigation.  Nothing to check you see.
Try rotating the model on the build plate.  This is a known bug and sometimes rotating or moving the model will fool it.  You will want to check the model for errors as well.
This appears to be a duplicate report of this behavior.  I'll mark this as a "Slicing Error" and close this as it is one report of many.  I hope you understand.  It should be fixed for 5.3
