### ISSUE TITLE
Extruder 2 for Support (Slicing)

### ISSUE THREAD

**Issue by GallowayJJ** [Ultimaker/Cura#13958]
### Application Version

5.1.0

### Platform

MacOS Ventura 13.1

### Printer

GeeeTech A10M

### Reproduction steps

(Not connected via USB during)
1. Have set extruder 2 to be used for supports
2. Close program 
3. Re-open
4. Load new model
5. Attempt Slicing

### Actual results

Error messages says Cannot Slice.

### Expected results

It should slice. 

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

🫡

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file we have nothing to investigate.  Load the model, set Cura up to slice, use the "File | Save Project" command.
Zip the 3mf file and post the zip folder here.
