### ISSUE TITLE
Raft not slicing correctly

### ISSUE THREAD

**Issue by oldblackcrow** [Ultimaker/Cura#13955]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 3

### Reproduction steps

Import model, add a raft, and slice. I've tried rotating it in both Cura and SketchUp but nothing seems to fix it. I cannot increase the size of the raft, as it grows beyond the build plate. 

### Actual results

Print fails because the bottom of model is not fully supported.

### Expected results

A large flat model should have a complete build plate. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Raft-Error](https://user-images.githubusercontent.com/45359956/205320579-f06c94e6-8a3f-44b0-b7d4-80fe7df4f259.png)

**Comment by MariMakes** [comment]
Hey @oldblackcrow,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

That's an odd raft. 🤔 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
