### ISSUE TITLE
NO SEGMENTA CON HIDRA PLUS

### ISSUE THREAD

**Issue by brenda2016** [Ultimaker/Cura#13978]
### Application Version

5.2.1

### Platform

windows 11

### Printer

HELLBOT HIDRA PLUS

### Reproduction steps

COLOQUE ARCHIVOS STL en cura, los configure y cuando los quise segmentar me dice error con la hidra plus, cosa que antes no pasaba.. pero seleccionando la ender s1 si funciona bien. El problema esta solo con la hidra plus
![2022-12-05 (2)](https://user-images.githubusercontent.com/119898813/205754677-28a2ccba-0ab7-4617-9161-5f7a662b5b0c.png)
![2022-12-05](https://user-images.githubusercontent.com/119898813/205754681-98c1cfeb-58b7-42cb-9804-67d91b8b094d.png)

### Actual results

...

### Expected results

...

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

...

**Comment by GregValiant** [comment]
Thanks for the report.
There are two files needed to look into this.
With your models loaded and Cura ready to slice, use the "File | Save Project" command to create a 3mf file.  Use the "Help | Show Configuration Folder" command to locate the Cura.log file.  Zip the log file and the 3mf file and post the zip folder here.
