### ISSUE TITLE
Estimated time left stops counting down

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#1397]
After an half an hour or so, the estimated time left counter on MACos CURA 2.4 beta surrounding stops counting down.

When CURA 2.4 is restarted it is solved

**Comment by nallath** [comment]
What count down timer? The one that you see when connected with the UM3?

**Comment by fieldOfView** [comment]
When it stops, could you check if the monitor icon in the top right of the window has a cyan "..." or grey "?" (or other color) overlay?

**Comment by Ghostkeeper** [comment]
I suspect it might just be a lost connection. Cura should try to restore the connection on its own though, but perhaps it takes a while before it tries the connection again.

**Comment by KarelTenkink** [comment]
The camera is still streaming, so in my opinion its not a lost connection.
![schermafbeelding 2017-02-02 om 15 45 21](https://cloud.githubusercontent.com/assets/25366548/22553981/d965c002-e95e-11e6-8b82-48eacbd76dc6.png)

**Comment by KarelTenkink** [comment]
It has been running for more than 6 hours now. Estimated time left stopped at 3 hours into printing.

**Comment by fieldOfView** [comment]
It is perfectly possible to have a working camera stream but no connection from Cura to the part of the firmware that supplies the printer status; they are two separate systems, and they can "break" independently. If the screenshot you posted is of the situation you describe (estimated time left stops going down), then Cura has not noticed it (yet).

**Comment by KarelTenkink** [comment]
Ok thanks for replying.

**Comment by fieldOfView** [comment]
Please keep the issue open; it needs to be investigated and fixed.

**Comment by Ghostkeeper** [comment]
Apparently not. Our product manager just closed this because it was inactive for 3 months.

**Comment by ianpaschal** [comment]
This is no longer an issue in Cura 3.2.1.
