### ISSUE TITLE
Slicer changes shape when slicing 

### ISSUE THREAD

**Issue by RichardL0ngFl0p** [Ultimaker/Cura#13981]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 5 Pro

### Reproduction steps

I imported a stl file and tried to have it be 98% infill with supports and print it.

### Actual results

I went to slice it and saw that the hole I made in the file has been removed, almost as if it wasn't added in the first place.
![Screenshot (68)](https://user-images.githubusercontent.com/119920970/205841782-80e6807c-a398-4cec-b837-b2abcdbdfe92.png)
![Uploading Screenshot (69).png…]()

### Expected results

The file's hole should not have been filled.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[bug problem.zip](https://github.com/Ultimaker/Cura/files/10163527/bug.problem.zip)

**Comment by fieldOfView** [comment]
You have the "Remove all holes" setting turned on, which... removes all holes.
