### ISSUE TITLE
1ST REPORT

### ISSUE THREAD

**Issue by Charlieborg** [Ultimaker/Cura#13985]
### Application Version

5.2.1

### Platform

windows 11

### Printer

ender s 1 pro

### Reproduction steps

UPSCALED THE PRINT
SLICED

### Actual results

WOULD NOT SLICE PRINT

### Expected results

Identify what was wrong with print.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

File was downloaded

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura log file we have nothing to check to do an investigation.
Load the model and use the "File | Save Project" command to save as a 3mf project file.  Use the Help | Show Configuration Folder" to go to the location of the Cura.log file.  Zip the project file and the log file and post the Zip folder here.
