### ISSUE TITLE
Error Slicing

### ISSUE THREAD

**Issue by WWGG12** [Ultimaker/Cura#13986]
### Application Version

5.2.1

### Platform

OSX

### Printer

Creality CR X

### Reproduction steps

1. Opened STL
2. Slice
3. 
[HomepodMini.3mf.zip](https://github.com/Ultimaker/Cura/files/10176865/HomepodMini.3mf.zip)

### Actual results

Error

I reported this error before for 5.0.0
in 4.17 it does slice perfectly

### Expected results

Sliced file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

cannot find log files

**Comment by GregValiant** [comment]
Thanks for the report and the project file.
I can duplicate this with your project file.  The model has some errors but even after repairing it I couldn't get it to slice.  PrusaSlicer took a long time but finished the slice. 

Just for curiosity sake - this image shows the errors in Mesh Mixer.
![image](https://user-images.githubusercontent.com/64202104/206216828-b6a08a02-0911-4383-9363-e29cba869a7f.png)

Someone from the Cura team will take a look.

**Comment by GregValiant** [comment]
@MariMakes I added a 0.4 x 3 x 80 cutting mesh to the model and this project will slice.  
[GV HomepodMini with Cutting Mesh.zip](https://github.com/Ultimaker/Cura/files/10178075/GV.HomepodMini.with.Cutting.Mesh.zip)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/91a261dc-8a1b-44b1-a342-d1b9f03366aa)
