### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by Arkirianne** [Ultimaker/Cura#13988]
[CE3PRO_Bruccius.zip](https://github.com/Ultimaker/Cura/files/10178766/CE3PRO_Bruccius.zip)
### Application Version

5.2.1

### Platform

windows 10

### Printer

ender 3 pro

### Reproduction steps

1. Drag & drop 3D model
2. Click Slice
3. Cura tell slicing failed

### Actual results

I can't print this model

### Expected results

Print the model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

no

**Comment by Arkirianne** [comment]
Hi,
I turn around the model and i was able to slice it.
Thanks a lot for your time!

Cassandra Lépine

Le mer. 7 déc. 2022 à 17:29, GregValiant ***@***.***> a
écrit :

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/741f948c-9f02-40df-bd12-f953f48322c0)
