### ISSUE TITLE
Strange support structures

### ISSUE THREAD

**Issue by structab** [Ultimaker/Cura#1399]
The backside are flat at 50°. Some strange supports appear on this model (STL attached) on "High Quality - 0.06mm".  
![bild](https://cloud.githubusercontent.com/assets/25148707/22551380/e43db336-e954-11e6-8279-8ff4c5f1152b.png)
![bild](https://cloud.githubusercontent.com/assets/25148707/22551472/3d874cf4-e955-11e6-98aa-0de31e062bf8.png)

[Mtme400 Demo fäste2.zip](https://github.com/Ultimaker/Cura/files/747860/Mtme400.Demo.faste2.zip)
CURA(2.3.1) Win10

**Comment by BagelOrb** [comment]
This should be solved in cura 2.4

Op 3 feb. 2017 11:55 schreef "Jaime van Kessel" <notifications@github.com>:
