### ISSUE TITLE
Wont sclise

### ISSUE THREAD

**Issue by spyingcreeper09** [Ultimaker/Cura#13999]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

I downloaded a marble run and tried to sclice with tree support on

### Actual results

Wont sclice

### Expected results

to sclise with tree support

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

big print?

**Comment by MariMakes** [comment]
Hey @spyingcreeper09,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
