### ISSUE TITLE
Second/ Third skin Flow setting not respected

### ISSUE THREAD

**Issue by PhilBaz** [Ultimaker/Cura#13996]
### Application Version

5.2

### Platform

win 10

### Printer

Voron 2.4

### Reproduction steps

Change second/third skin flow setting 

![skin 1](https://user-images.githubusercontent.com/21558241/206559537-f5e044bc-4a30-4b4a-b966-142f976cadd0.jpg)
![skin2](https://user-images.githubusercontent.com/21558241/206559539-55bd1332-b203-481e-b54c-d76e949f1e1e.jpg)

### Actual results

Nothing

### Expected results

Flow change

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Second-Third skin flow issue.zip](https://github.com/Ultimaker/Cura/files/10189199/Second-Third.skin.flow.issue.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I looked at the flows for the first, second and third skin.  The first skin responds to the setting but the second and third did not.  I wasn't able to change other options and get them to work.

The Cura team will take a look at this.

**Comment by PhilBaz** [comment]
@GregValiant Yes, that's my experience too.

**Comment by PhilBaz** [comment]
@GregValiant Greg I was wrong @smartavionics helped me understand why.   In the cube above the second and third skin  should not work because it is an internal rather than proper bridge. So he says that's by design.

Beyond that the model I was using had walls filling the space in question, so there was no proper skin to control there. Second and third skin only allow control of skin flow and speed, not wall speed and flow, like the first layer...

I hope my explanation is clear.

**Comment by GregValiant** [comment]
I built this model to check and in this case, all the flows worked as they should:
![image](https://user-images.githubusercontent.com/64202104/206701901-0cda9897-83fb-4e00-b60a-50e8738d1117.png)

I set the "Bridge Skin Flow" to 50%, the "Second Skin Flow" to 150% and the "Third Skin Flow" to 200% and the numbers were dead on.
So there would appear to be a lot more going on in the background than is apparent at first glance and the specific model features do have a bearing on how Cura attacks and solves the problem.

Based on that, I'm inclined to remove the bug label and close this.  Let me know what you think.
I'm attaching a project file in case you want to play with it.
[GV Bridge.zip](https://github.com/Ultimaker/Cura/files/10194775/GV.Bridge.zip)

**Comment by PhilBaz** [comment]
@GregValiant 

Hi Greg, 

Yeah I think case close.  But while I have you here I just want to make an appeal to expose the 'skin wall' flow parameters for bridge 'skin layer' 2 & 3.

This  would be very helpful for TPU bridging, and other flexibles that are seeing increased use.

An all wall bridge might be desirable for TPU in narrow sections to get the heat of the nozzle away from the bridge as quickly as possible. 

I'm thinking real skin will keep concentrated heat in a given area for longer, going back and forth across the shorter length rather than quickly across the longest side in a straight line. I think more heat = more drooping. TPU is so finicky that bridging wall flow might make all the difference. Especially for narrow all wall bridges.

**Comment by GregValiant** [comment]
I think I'll close this.  (I have permissions here to change this to a "feature request" but I can't change the name so it would be misleading.)

If you could write up a feature request that would be the best way to go.
I'll go ahead and close this one out.

**Comment by PhilBaz** [comment]
@GregValiant Will do!
