### ISSUE TITLE
Failed Printjob - MacOS Ventura vs  Cura 5.2.1

### ISSUE THREAD

**Issue by wfyoungers** [Ultimaker/Cura#13991]
### Application Version

5.2.1

### Platform

MacOS Ventura

### Printer

Creality CR10S Pro

### Reproduction steps

Just any stl.  

The out may or may not look correct in Preview.

When printing, just a mess

Doesn't matter which printer

### Actual results

Wasted Time and Filament

### Expected results

The output should have been normal as in the past.   Ventura seems to have broke Cura 5.2.1

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_Kokeswirlskull.3mf.zip](https://github.com/Ultimaker/Cura/files/10181569/CFFFP_Kokeswirlskull.3mf.zip)

**Comment by MariMakes** [comment]
Hey @wfyoungers,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍
I'm sorry to hear your print job failed, but I'm not sure if it is related to macOS. 

When looking at your changed settings I noticed that you have Make Overhang Printable enabled. 
This drastically changes how your model looks, If you disable this setting your skull becomes hollow as the file intended. 
If you disable this setting, don't forget to enable support and build plate adhesion. 
![image](https://user-images.githubusercontent.com/40423138/206450268-7cb7c77c-ca69-43de-a420-03f5829f3861.png)

If this doesn't help, can you share a picture of your failed printjob?
That makes troubleshooting easier 😅

**Comment by wfyoungers** [comment]
Thanks for the reply and I noticed I had not unchecked “Make overhangs printable” after I sent off the report. Yes it fixed the problem and so far, it seems to have solved the issue. Thanks again Bill Youngers. Sent from my iPhoneOn Dec 8, 2022, at 6:50 AM, MariMakes ***@***.***> wrote:﻿
Hey @wfyoungers,
Welcome to the Ultimaker Cura Github 🚀
Thanks for your report 👍
I'm sorry to hear your print job failed, but I'm not sure if it is related to macOS.
When looking at your changed settings I noticed that you have Make Overhang Printable enabled.
This drastically changes how your model looks, If you disable this setting your skull becomes hollow as the file intended.
If you disable this setting, don't forget to enable support and build plate adhesion.

If this doesn't help, can you share a picture of your failed printjob?
That makes troubleshooting easier 😅

**Comment by MariMakes** [comment]
I'm very happy to hear that!
Good luck 🥳
