### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by gcortez681** [Ultimaker/Cura#14006]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

Open thingiverse file. Apply custom quality preset. Increase size of model to 121.46%. Slice.

### Actual results

 Upon slicing the program produced an error:
"Slicing failed with an unexpected error. Please consider reporting a bug."

### Expected results

Fully sliced object. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The work around for now is to use whole numbers. 120% fixed the slicing error.

**Comment by MariMakes** [comment]
Hey @gcortez681,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
