### ISSUE TITLE
Fills in extruded cut inappropriately aligned to Z-axis

### ISSUE THREAD

**Issue by user17625** [Ultimaker/Cura#14008]
### Application Version

4.8.0

### Platform

Windows 10, i7 processor

### Printer

INFI-20

### Reproduction steps

Created a tray in Solidworks v2014 x64.  
Did an extruded cut from top of box down. 

### Actual results

Tray was created with a piece of the floor starting at a 45 degree angle from outside bottom of box.  Extra floor material added which was not part of CAD layout followed extruder path as the INFI-20 prints at a 45 degree angle.  This added feature shows accurately in the "Preview" menu what is created in g-code incorrectly, which is different from both the Solidworks CAD layout, and the Cura "Prepare" menu which show the original, intended design. 

### Expected results

Tray should have 1/4" thickness on all sides except top which should be open.  See prepare view for what was expected.  

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[Tray.zip](https://github.com/Ultimaker/Cura/files/10199527/Tray.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
UltiMaker Cura 4.8 was at least a dozen releases ago and I don't recall it supporting belt printers.  
In your version of Cura - at the top left of the screen above the menu bar, what does the title bar say?
If it is the "SainSmart Slicer" then this report should be made on their site.

I'll leave this open, but I don't think this is a UM Cura problem so I'll remove the bug label.

(See if you have "Make Overhangs Printable" checked and if you do then disable it.)
