### ISSUE TITLE
fichier ne ce decoupe pas car erreur de decoupe 

### ISSUE THREAD

**Issue by hvs3d** [Ultimaker/Cura#14004]
### Application Version

5.1

### Platform

windows 10

### Printer

sidewinderx1

### Reproduction steps

decoupe du fichier 

### Actual results

erreur de decoupe 

### Expected results

decoupe 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

le fichier est telecharger mais ne contien pas de probleme

**Comment by MariMakes** [comment]
Hey @hvs3d,

Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Merci 🙏
