### ISSUE TITLE
Support density not changing

### ISSUE THREAD

**Issue by MRBmedic1** [Ultimaker/Cura#14005]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Anycubic Chiron

### Reproduction steps

Changed the support density from 100% to 10%.
When I checked in the preview mode it was still at 100%. Even though on the print settings field the number did change. It just didn't have any affect on the model. 
After printing the support was fused to the print.
![Screenshot 2022-12-08 080916](https://user-images.githubusercontent.com/120232439/206825813-a631ccc8-c02a-4966-98d5-fa2204b0bd23.jpg)
![Screenshot 2022-12-08 081043](https://user-images.githubusercontent.com/120232439/206825816-474f4fee-62ef-4e0e-ae00-11de97bb60e2.jpg)
![Screenshot 2022-12-08 081211](https://user-images.githubusercontent.com/120232439/206825824-ac2fd53a-3f48-41b8-8cfe-8406a4a833b9.jpg)

### Actual results

The density remained at 100% causing support to fuse to model.

### Expected results

Density should have change when settings were changed.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Unable to attach Cura project file.
Find attached screen shots of issue.
![Screenshot 2022-12-08 080916](https://user-images.githubusercontent.com/120232439/206825988-09c0bf77-a4cc-4bcd-a6ad-cedd2e3d0bb5.jpg)
![Screenshot 2022-12-08 081043](https://user-images.githubusercontent.com/120232439/206825997-4dfbca0f-41ac-4b9d-b9b8-69c0e47ec5c0.jpg)
![Screenshot 2022-12-08 081211](https://user-images.githubusercontent.com/120232439/206825999-d5c92228-7907-46b2-92cd-90fa8d25978b.jpg)

**Comment by Asterchades** [comment]
Pastel blue is the Support Interface - not the regular Supports. Supports are coloured the same teal as the skirt (the "Helpers" colour). Adjusting the Support Density has zero effect on the Support Interface. You'll want to either disable the Support Interface (or at least the Support Roof, which is the top Interface) or adjust the Support Interface Density.

The Support Interface is primarily to allow for changing materials on only the very last few layers of the Support structure, such as for changing to a more expensive, soluble material for only the part that will come into contact with the model. Though I've personally found a 100% density Interface useful even without changing materials when using PLA and PETG, provided enough part cooling is present.

**Comment by MRBmedic1** [comment]
Sorry, I meant to say Support Interface and take screen shots of that, my
bad!!

**Comment by Asterchades** [comment]
You've overridden the Density by specifying a Line Distance. The global Support Interface Density gets inherited by the Support Roof and Floor Density settings, but each of those in turn gets overridden by their respective Line Distance settings - which you've got set to a fixed 0.55mm. This is why the two sub-settings are greyed out, indicating that they're not being used.

You'll either have to change your Line Distance settings to something more appropriate or hit the ƒx indicator next to Density settings to allow them to work again.
