### ISSUE TITLE
Can't fetch PGP Key used to verify AppImage / Add Documentation in Wiki

### ISSUE THREAD

**Issue by decipher-random** [Ultimaker/Cura#14025]
### Application Version

5.2.1

### Platform

Linux

### Printer

none

### Reproduction steps

**Follwed what was said in** #6225
`gpg --keyserver pgp.mit.edu --recv-keys C1A1B91069C4AF59`

### Actual results

`gpg --keyserver pgp.mit.edu --recv-keys C1A1B91069C4AF59`
`gpg: error searching keyserver: No keyserver available`
`gpg: keyserver search failed: No keyserver available`
**Then tried searching for  key** 
`gpg --keyserver pgp.mit.edu --search-keys C1A1B91069C4AF59`
`gpg: error searching keyserver: No keyserver available`
`gpg: keyserver search failed: No keyserver available`
**Then tried the same output above but with full key name:** `1889EAED2DB93BF7DFFB3CA6C1A1B91069C4AF59`

### Expected results

`gpg --keyserver pgp.mit.edu --recv-keys C1A1B91069C4AF59`
`gpg: key 0xC1A1B91069C4AF59: public key "Ultimaker Build Server <monolith@ultimaker.com>" imported`
`gpg: Total number processed: 1`
`gpg:               imported: 1`

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

There is no dI'm not sure if this is an issue with *pgp.mit.edu* keyserver or not. Suggestion would be to also add the key on the git repo so people can fetch it if the server is down or having problems with wget. Maybe also add on another backup keyserver.

There is no documentation that I could find about verifing the signature of each release or where the key is even located besideds looking in issues. Verifing software is very important for all users(Windows/MacOS/Linux). That being said SHA256sums of each release should be added aswell. 
# Please add documenation to Wiki
## - Add Signing Key to Github repo as backup

**Comment by MariMakes** [comment]
Hey @decipher-random,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This is very much outside my field of expertise 🙈 
I'll bring it up to the team to see what they can do to help.
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @decipher-random,

Quick update on our side. 
We clearly need to fix this keyserver. 

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10460

Thanks for the report! 👍

**Comment by jellespijker** [comment]
Closing this issue since it was an issue with the pgp.mit.edu server, running these commands now provide the expected results.

```bash
$ gpg --keyserver pgp.mit.edu --recv-keys C1A1B91069C4AF59
gpg: key C1A1B91069C4AF59: public key "Ultimaker Build Server <monolith@ultimaker.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by CoeJoder** [comment]
@jellespijker's [comment](https://github.com/Ultimaker/Cura/issues/14025#issuecomment-1745039673) in this thread is the closest thing I can find to official documentation as to what the public GPG key is for this project.

Really should have better documentation here!
