### ISSUE TITLE
Overwriting a file on a stick > error

### ISSUE THREAD

**Issue by Keno55** [Ultimaker/Cura#14029]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Artillery Sidewinder X1

### Reproduction steps

Whenever I want to overwrite a file on my USB stick, the first thing that appears is: "File already exists, do you really want to overwrite it?"
After confirmation with "yes" an error message appears: "type object 'QMessagebox' has no attribute 'No' "
This has only happened since version 5.21
I then have to delete the file before I can save the new version

### Actual results

See above

### Expected results

I want to overwrite the file after confirming "Yes"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura1](https://user-images.githubusercontent.com/120403559/207101572-f268502c-d32d-4c62-b3b3-e08719b2cad3.jpg)
![Cura2](https://user-images.githubusercontent.com/120403559/207101618-430f01a9-ca00-45c3-b696-2df6ceb3a9e6.jpg)

**Comment by fieldOfView** [comment]
Thanks for the report. Please include a link to your Cura.log. That makes it much easier to fix this (as it will tell us which piece of code is responsible).

**Comment by MariMakes** [comment]
Hey @Keno55,

Welcome to the Ultimaker Cura Github 🚀 

What an interesting report! I don't think I've seen this before. 
It might be related to the german translations in your buttons. 
Mine look like this:
![image](https://user-images.githubusercontent.com/40423138/207317373-6981b616-1433-4f6b-b0cb-1f76a3189b24.png)


@fieldOfView is right, we need your log file to troubleshoot. 

You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
