### ISSUE TITLE
Unable to launch on a monitor that isn't windows primary display

### ISSUE THREAD

**Issue by jSydorowicz21** [Ultimaker/Cura#14030]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender 5 plus

### Reproduction steps

On first open drag Cura window to a monitor that isn't the windows primary display
Close Cura
Reopen Cura

### Actual results

Window launches unresponsive and entirely white.

### Expected results

Cura should launch, the only way to fix this issue once encountered is to change the primary display in windows to the one that cura is attempting to launch on. Once done Cura launches fine, this issue can be resolved by defaulting the save window position option to false as a temporary workaround.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10211531/cura.log)

**Comment by MariMakes** [comment]
Hey @jSydorowicz21,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

We have some known issues with Cura on multiple monitors. 

I have a couple of questions to narrow it down.
	1. Do you have multiple monitors? Does Cura start if you disable one of the monitors?
	2. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
	3. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
	4. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665
