### ISSUE TITLE
slicing fails

### ISSUE THREAD

**Issue by amills1982** [Ultimaker/Cura#14042]
### Application Version

5.0.0

### Platform

windows 11

### Printer

flsun v400

### Reproduction steps

loaded stl

### Actual results

slicing fails at 100% but works at 95%
[retromaker_ornament_globe3.zip](https://github.com/Ultimaker/Cura/files/10222454/retromaker_ornament_globe3.zip)

### Expected results

should slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

cant find cura.log

**Comment by MariMakes** [comment]
Hey @amills1982,

Thanks for your report 👍

I believe that your slice fails, but for me it seems to slice just fine:
![image](https://user-images.githubusercontent.com/40423138/207613020-2757c7b4-263b-41cf-9d19-930406577dbb.png)

Do you think it could be related to this issue: https://github.com/Ultimaker/Cura/issues/13643, where we see that models fail if they are in the complete center of the buildplate ?
