### ISSUE TITLE
Program crash when move objets on windows 11

### ISSUE THREAD

**Issue by danilopmaciel** [Ultimaker/Cura#14045]
### Application Version

5.2.1

### Platform

windows 11

### Printer

ender 3

### Reproduction steps

Import objetc
Move objetc
freeze cura

### Actual results

Cura don't respond.

### Expected results

Dont't freeze ^^

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/30030866/207588696-202c8553-b092-464b-bdd6-6dad13cb50e4.png)

**Comment by MariMakes** [comment]
Hey @danilopmaciel,

Thanks for your report 👍
We've seen a number of reports of Cura being slower or freezing on Windows 11. We've been collecting them here: https://github.com/Ultimaker/Cura/issues/13820

I personally upgraded my device to Windows 11 to help with troubleshooting but I'm not experiencing the slowness or freezing. 

[We found this report in the community ](https://community.ultimaker.com/topic/42105-cura-521-work-slowly-and-freeze-when-i-go-to-the-printer-settings-menus-profiles-etc/#comment-315788)that it might be related to overlay software like Reverso or Punto Switcher that use global hotkeys.

Can you check if you are having a similar program running in the background? I had Reverso enabled all day in the background yesterday and my Cura was noticeably slower, today I uninstalled the program and it seems to be running fine.
