### ISSUE TITLE
Slicing issue with supports

### ISSUE THREAD

**Issue by Fusion-Tech-05** [Ultimaker/Cura#14052]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. Load up your model.
2. Add supports
3. Set infill to 20%
4. Make sure the model is going to take about 14 hours without supports
5. Press slice

### Actual results

It doesn't slice and gives me an error and says to report a bug.

### Expected results

It should slice with supports added

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am not legally allowed to share the file due to it being a paid for product.

**Comment by GregValiant** [comment]
Thanks for the report.  We understand about the model.
Try moving and /or rotating the model on the build plate.  There is a bug that can be fooled by doing that.
Also, open the model in MS 3D Builder and the error checker will run.  It has decent repair ability if the model requires it.
Let us know if that workaround does the trick or not.
