### ISSUE TITLE
Gradual Infill Steps unavailable

### ISSUE THREAD

**Issue by andersonee85** [Ultimaker/Cura#14069]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Elegoo Neptune 2

### Reproduction steps

1. Manage Visibility Settings
2. Under Infill Category, check box for "Gradual Infill Steps"

### Actual results

Gradual Infill steps setting should appear in the Print Settings Menu for adjustment.

### Expected results

Gradual Infill Steps setting does not show up in the Print Settings Menu.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by GregValiant** [comment]
Thanks for the report.
Gradual Infill Steps isn't available for all infill patterns.
Without a project file there is no way to tell if that is the problem.
