### ISSUE TITLE
will not slice file 

### ISSUE THREAD

**Issue by Cthulhu1512** [Ultimaker/Cura#14067]
### Application Version

5.21

### Platform

win 11

### Printer

ce3v2

### Reproduction steps

imort and slice than fails slice 

### Actual results

gives me option to report bug 

### Expected results

my model should of sliced so it was ready for a print 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

im not to shore how to take screen shots and i cant uplaod the folder it doesnt show anny of my 3d files

**Comment by GregValiant** [comment]
Thaks for the report.
To troubleshoot we need the project file and cura.log file.  Github requires that they be zipped and has a 25mb limit on the size of the zip folder.
To create a project file - load the model and set Cura up to slice and then use the "File | Save Project" command.
To locate the Cura.log file use the "Help | Show Configuration Folder" command.

In Windows if you right click on a file and select "Send To..." and then "Compressed (zipped) folder" the zip folder will be created and your file added to it.  You can add other files by dragging them into the zip folder.
Post the zip folder here.
