### ISSUE TITLE
G2/G3 requires IJ, IK or JK parameters

### ISSUE THREAD

**Issue by PaintOnBrush** [Ultimaker/Cura#14074]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 pro Klipper

### Reproduction steps

arc welder generated this line:

G3 X68.406 Y115.000 I-0.000 J2.203 E0.04874 

### Actual results

running it through the print fails with:

G2/G3 requires IJ, IK or JK parameters

failed to run on my Klipper firmware / cancels print.

### Expected results

command should work.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it works if I change I-0.000 to  I-0.001

**Comment by Asterchades** [comment]
Arc Welder isn't part of the base Cura, even if it is maintained by one of the Cura contributors. You'll need to bring this up on its specific Git repository instead.

https://github.com/fieldOfView/Cura-ArcWelderPlugin
