### ISSUE TITLE
moonracker

### ISSUE THREAD

**Issue by ward1975** [Ultimaker/Cura#14070]
### Application Version

5.2.1

### Platform

window 10

### Printer

ender 3 s1 pro

### Reproduction steps

i was on mark place in cura 

### Actual results

hi there i had this problem before with moonracker its not uploading to my sonic pad i tried and tried but it still dose not work. I slist the xyz cube and i tried 4 times its coming up with the same error and come up with a report page 
![IMG_1821](https://user-images.githubusercontent.com/120813274/208253369-67549e08-87b9-4573-a4ac-8cab29a3ccca.jpg)
 
![IMG_1821](https://user-images.githubusercontent.com/120813274/208253398-33d771fa-8c09-4ea3-8148-a7b2045cc17d.jpg)

### Expected results

can this be sorted out because i love klipper  

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![IMG_1821](https://user-images.githubusercontent.com/120813274/208253421-a34fac14-c8d2-43b8-a624-22a719cec378.jpg)

**Comment by GregValiant** [comment]
Thanks for the report.
If it is a slicing error the report comes here.  If it is a Moonraker error then the slice goes to the developers who created the plugin. If you go to the Marketplace and to the Moonraker icon there is a link to the emtrax people.

**Comment by ward1975** [comment]
Ok thank you I do that sorry for your time

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GregValiant** [comment]
Not a problem.  It's the nature of open source software that there can be many contributors and it isn't always clear who is responsible for a particular part.  

I'll go ahead and close this then.  If Emtrax comes back and says that it's a problem on the Cura end then this can be re-opened.
