### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by Pantyhouse** [Ultimaker/Cura#14075]
### Application Version

5.2.1

### Platform

w10

### Printer

ender 3v2

### Reproduction steps

slicing and object it happends an unexpected error

### Actual results

cant continue

### Expected results

slice object

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/48135452/208282331-c510ecba-ffde-4350-924d-c543555efeeb.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project File and Cura.log file there can be no investigation.
Load the model and set Cura up to slice then use the "File | Save Project" command.
Use the "Help | Show Configuration Folder" to go to the location of the Cura.log file.
Put those two files into a Zip folder and post the zip folder here.

For doing that you get my Weber DCOE model.  You'll need to build your own manifold.
[40 DCOE.zip](https://github.com/Ultimaker/Cura/files/10253953/40.DCOE.zip)
