### ISSUE TITLE
Having issue to slice with custom support

### ISSUE THREAD

**Issue by Raian111** [Ultimaker/Cura#14086]
### Application Version

5.2.1

### Platform

windows 11

### Printer

anycubic kobra max

### Reproduction steps

1.
![image](https://user-images.githubusercontent.com/86621827/208342238-169f4da4-a92d-4b84-9813-f6f63e897304.png)
2.
![image](https://user-images.githubusercontent.com/86621827/208342269-3a7be21d-31b1-4237-9c85-94d757f82bab.png)

### Actual results

Slicing error

### Expected results

Need to slice it perfect

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nope

**Comment by MariMakes** [comment]
Hey @Raian111,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
