### ISSUE TITLE
BUG MESSAGE BEFORE PRINTING AND OBJECT DOES NOT PRINT.

### ISSUE THREAD

**Issue by Mkanton** [Ultimaker/Cura#14087]
### Application Version

Cura 5.2.1

### Platform

Windows 10

### Printer

Ultimaker S3

### Reproduction steps

I'm trying to print the hand (Thing of Addams Family), see the link below, but it always pops up a bug message. 

I place the model on the table, the program displays normally, adjust the parameters and try to slice. 

What could be happening? Is it a problem with the model or with the Cura app?

### Actual results

Nothing happens except the bug message.

### Expected results

I expected to be able to print the model.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

http://bit.ly/3BNmQUm

**Comment by GregValiant** [comment]
Thanks for the report.
We can't do an investigation without a project file and the cura.log file.
Use the "File | Save Project" command to make a project file.
Use the "Help | Show Configuration Folder" to locate the cura.log file.
Zip those two files up and post the zip folder here.
