### ISSUE TITLE
Part cooling fan

### ISSUE THREAD

**Issue by giaco-leopardi** [Ultimaker/Cura#14091]
### Application Version

5.2.1

### Platform

MacOs Monterey

### Printer

Ender 3 V2

### Reproduction steps

One day I installed the add-in of printer settings and selected the option of scaling the fan speed from 0-1.

### Actual results

The part cooling fan never worked again, even if I disabled the option in the menu

### Expected results

The part cooling fan must work as normal

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Tray_slicer.3mf.zip](https://github.com/Ultimaker/Cura/files/10262677/Tray_slicer.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The setting "Scale fan speed to 0-1" is a specialty setting for certain printers.  Your printer definition file would have checked if you needed it.

That isn't the problem.  Go to "Manage Printers" then "Machine Settings" and select the "Extruder Tab".  You have one fan and it is numbered as Fan0.  Set the "Cooling Fan Number to "0".
The setting is "Cooling Fan Number" and NOT the "Number of Cooling Fans".

This is a settings issue so I'll close this.  Let us know if you think that was premature.
