### ISSUE TITLE
Missing option

### ISSUE THREAD

**Issue by Tandouji** [Ultimaker/Cura#14094]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. tick "conecct lines fill" option 
2. Doesn't show option 

### Actual results

nothing

### Expected results

that appears the option it's missing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i tick the option "Connect Lines Fill" to show me in "Fill" options but it doesn't appear anymore as an option
![Captura](https://user-images.githubusercontent.com/121078359/208587664-4eb92361-4772-4855-af53-18774cf24d90.PNG)

**Comment by Asterchades** [comment]
Connect Infill Lines is not available for the Zigzag infill pattern. Zigzag is already connected - the connections are basically what separate it from Lines in the first place. It also isn't available for Concentric or Lightning.

Many settings are automatically hidden when they will have no effect, regardless of visibility settings. This includes many (though curiously not all) Infill settings when the Infill Density is set to 0%, Support settings when Supports are disabled (and no models are set to Print as Support), Z Hop Height when Z Hop is disabled, and so forth.
