### ISSUE TITLE
Retract Continue when using Relative Extrusion

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#14100]
### Application Version

5.2.1

### Platform

Win10

### Printer

Ender 3 Pro

### Reproduction steps

Enable relative extrusion for a print.
Enable retract continue.
Slice and save the gcode file.

### Actual results

This happens throughout the file.  I hadn't noticed and the extruder was beating itself to death.

G1 F3000 X165.281 Y123.421 E0.18226        ;last extrusion
G1 F2100 **E-6.5**                                             ;normal retraction
;MESH:X-Y Ref Block.stl(1)
G1 F9000 X162.983 Y104.5 Z0.35 **E-7.45300** ;retract continue
G1 X160.123 Y104.5 Z0.35 **E-7.59600** ;retract continue
G1 X69.697 Y104.5 Z0.35 **E-12.11730** ;retract continue
G1 X66.837 Y104.5 Z0.35 **E-12.26030** ;retract continue
G1 X44.657 Y104.5 Z0.35 **E-13.36930** ;retract continue
;TYPE:WALL-INNER
G1 F2100 **E6.5**   ;normal prime - this should be 59.2959 so E6.5 leaves the filament just a tad short of the nozzle.
G1 F3000 X44.657 Y125.5 E2.82354   ;first extrusion

### Expected results

The deltas of the travel moves need to be calculated correctly.
The prime at the end must account for all the delta changes in the E.
G1 F3000 X7.359 Y97.869 E7.89636           ;Last extrusion
G1 F2100 E-6.5                                          ;retract filament -6.5
G1 F9000 X7.36 Y132.129 Z1.4 E-1.21300 ;"retract continue" with a proper additional retraction distance
G1 F2100 E7.713                                      ;prime to make up for all retractions to get the filament back to the nozzle.
G1 F3000 X41.899 Y97.589 E5.97052        ;first extrusion

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

This issue was mentioned in #7396 and #7458.  It looks like @rburema had a hand in making some fixes a couple of years ago.

This snippet is with Absolute Extrusion and appears to be fine.  There are incremental retractions through the travel moves and then the final prime accounts for all the delta changes.
G1 F3000 X222.739 Y154.857 E891.5317 ;Last Extrusion
G1 F2100 E885.0317                   ;retract 6.5
;MESH:NONMESH
G1 F600 X222.5 Y154.857 Z1.75 E885.01420    ;additional retraction retract continue
G1 F9000 X175.714 Y159.617 Z1.75 E882.66282 ;additional retraction retract continue
G1 X172.86 Y159.617 Z1.75 E882.52012        ;additional retraction retract continue
G1 X36.156 Y165.971 Z1.75 E875.67754        ;additional retraction retract continue
G1 X34.161 Y166.4 Z1.75 E875.57551          ;additional retraction retract continue
G1 F2100 E891.5317                   ;prime back to the location of the last extrusion

I had enabled "Retract Continue" as I was printing with a 0.8 nozzle and it needed the help.  It is a large print and with "Relative Extrusion" turned on it's easier to do a restart if something bad happens mid-print.

Here is a project file.  I didn't think the log would be helpful.
[Retract Continue Problem.zip](https://github.com/Ultimaker/Cura/files/10271986/Retract.Continue.Problem.zip)

**Comment by MariMakes** [comment]
Hey @GregValiant ~!

Thanks for the comprehensive report 😍 
As usual, this is far outside my field of expertise.
But, I'll bring it up to the team to see what they can do to improve it. 
Fingers crossed 🤞 

And.... Happy Holidays 🎄🎅🎆

**Comment by rburema** [comment]
Seems all the actual commits where made by ghostkeeper*, from what I can track back, I didn't even review, I was merely the messenger in that case, based on what I remember the team discussing. (Hence ghostkeeper correcting me later in that same thread about the details.)

So I don't have any piercing insights here unfortunately; let's just follow the normal process.

*) Not @ -ing, they don't work for UM at the moment and are probably still taking a well deserved break from Cura.

**Comment by GregValiant** [comment]
Yeah, I had figured that he left.

This is something that I would imagine doesn't come up much.  It was kind of a fluke that I found it.  "Deferring" this or putting it on the "Won't fix/do" list is fine by me.

It was necessary for me to abort the first print and re-slice in Absolute Extrusion mode.  As it turned out I ran out of filament about 14 hours into the print and did have to do a quick pause and restart.  That went well with Absolute Extrusion as it is something I've practiced.

**Comment by MariMakes** [comment]
Hey @GregValiant,

I brought your issue up to the team. 
They agree it's a booboo and needs to be fixed just don't know how soon yet. 

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10092

Thanks for the report! 👍
