### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by Redwolfh613** [Ultimaker/Cura#14101]
### Application Version

5.2.1

### Platform

windows 11

### Printer

anycubic kobra max

### Reproduction steps

imported file
rotated 180
increased size to 130%

### Actual results

starts slicing
gets about half way
error message saying "unexpected error"

### Expected results

a printable file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

here is the link to the file im using since you dont support stl files. https://www.thingiverse.com/thing:5448692/files

**Comment by GregValiant** [comment]
Thanks for the report.
Github requires that anything other than text files be zipped.  A project file and the Cura.log file are necessary to do an investigation.  The instructions are on the page you filled in for the report.
