### ISSUE TITLE
won't slice

### ISSUE THREAD

**Issue by deadlyhuman139** [Ultimaker/Cura#14102]
### Application Version

5.2.1

### Platform

mac

### Printer

ender3

### Reproduction steps

rotated model to slice on side.

### Actual results

won't slice

### Expected results

help resolving.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

new to this.

**Comment by GregValiant** [comment]
Thanks for the report.
We can't do anything about it without a project file and a cura.log file.  The instructions are on that first page you filled out.  The files need to be zipped and the zip folders posted here.
