### ISSUE TITLE
[Cura 2.4-beta][OSX] Filaments disappear, cannot duplicate custom ones

### ISSUE THREAD

**Issue by zanmoskotevc** [Ultimaker/Cura#1410]
Hello!

I am having issues with filaments - I can only duplicate the existing ones and not the custom ones.
The custom ones disappear after closing the app. Has anyone else had this problem?

**Duplication problem** - [video](https://v.usetapes.com/JTU2uxlVaC)

**Filaments disappearing** - [video](https://v.usetapes.com/BCOLbldGfh)

**System info**
![screenshot 2017-02-07 20 42 34](https://cloud.githubusercontent.com/assets/630728/22708309/1584d9a4-ed76-11e6-84d8-f23a1d2c92c9.png)

EDIT: also noticed, importing doesn't work. This feels like a read/write permission issue, but I don't know how to fix it..

**Comment by Ghostkeeper** [comment]
Other people indeed had this problem too. See https://github.com/Ultimaker/Cura/issues/1104 and https://github.com/Ultimaker/Cura/issues/1286.
