### ISSUE TITLE
Could not slice Thingiverse Soul Skull

### ISSUE THREAD

**Issue by kpavey** [Ultimaker/Cura#14115]
### Application Version

5.2.1

### Platform

iMac

### Printer

Ender 3 S1 Pro (modified from other Ender profile I believe)

### Reproduction steps

1. Downloaded soul skulls from https://www.thingiverse.com/thing:2834901/comments
2. verified print settings 5% infill, 2 perimeters and supports with top/bottom skins
3. Tried to slice - software failed

### Actual results

Cora doesn't complete slice successfully

### Expected results

Should slice successfully and be able to review layers.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No further info

**Comment by MariMakes** [comment]
Hey @kpavey,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍
I tried to slice your STL but with my settings, it slices just fine.
![image](https://user-images.githubusercontent.com/40423138/209333169-e45274c3-e040-43b3-adb8-3b830f519bac.png)


Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
