### ISSUE TITLE
Extra start gcode being added to prints

### ISSUE THREAD

**Issue by Colin-Whelan** [Ultimaker/Cura#14110]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality CR-10S

### Reproduction steps

1. Added custom start gcode to machine settings 
![1](https://user-images.githubusercontent.com/38737123/209038677-360ec481-c865-4bc4-9de7-e9c07f39a3fe.PNG)
2. Slice model
3. Checked gcode output in a code editor 

### Actual results

Extra start gcode is being added to the file which is setting the bed and hotend temp
![2](https://user-images.githubusercontent.com/38737123/209038647-73d7738b-f527-42ca-b49d-e020d6c5ea3d.PNG)

### Expected results

I expected only my custom gcode to be there, without the other code.
I also checked the config files and cant find the extra code anywhere.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

heres the config file with the start gcode saved, looks good here: 
![3](https://user-images.githubusercontent.com/38737123/209039341-f90d0b44-8d75-4abd-a1fd-097c799d2939.PNG)

**Comment by GregValiant** [comment]
Thanks for the report.
If there are no [_Cura keywords_ ](http://files.fieldofview.com/cura/Replacement_Patterns.html)within your StartUp Gcode then Cura adds the temperature lines before the Startup as a safety to insure there will be no "cold extrusions".  That was likely fine for a stock printer without ABL.
You need to make a couple of changes in your Startup Gcode.
Go to Manage Printers and then Machine Settings.
In the "Startup G-Code" pane make these changes:

M104 S165 ;this line is OK as it sets the the hot end to below the oozing temperature for the ABL moves.  If you like you could change it to 
M104 S{material_standby_temperature} which might be a bit warm though as most materials have the standby at 175°.

M190 S60 ; ; right now you have the bed temperature hard coded at 60.  If you were to print with PETG and needed the bed at 80 then this line would interfere with it.  Change that line to:
**M190 S{material_bed_temperature_layer_0}** ; Cura will replace the keyword with the actual "Bed Temperature Initial Layer" as set in Cura.  The curly brackets are required.

after the M420 line is
M109 S215 ; this line has the same problem as the bed line.  The 215 is hard coded into the startup and if you change the temperature in Cura this line will keep your change from taking effect.
change that line to:
**M109 S{material_print_temperature_layer_0}** ;that will set the hot end to "Print Temperature Initial Layer" and wait for the hot end to hit the set point.  Once again the curly brackets are required.

The StartUp Gcode comes from the Creality CR-10S printer definition file and was fine for a printer without ABL.  When you customized it to account for the ABL you needed to have inserted the keywords.
BTW that definition was submitted by a contributor (or by Creality through trouch.com) to be included in Cura.  So this isn't a Cura bug at all.  I'll leave this open so you can respond here.

I'll remove the bug label and change this to a "question" as the StartUp Gcode is provided either by the printer manufacturer or a contributor, _or_ what sounds like happened in this case, it was customized by a User.  Ultimaker has no idea what the startup gcode for a Creality printer should be.

**Comment by Colin-Whelan** [comment]
Thank you! this solved m,y issues!
