### ISSUE TITLE
CURA 5.2.1 Fehler beim Slicing

### ISSUE THREAD

**Issue by jkilian1963** [Ultimaker/Cura#14119]
### Application Version

5.2.1

### Platform

W 11

### Printer

Elegoo Neptune 3

### Reproduction steps

STL geladen
Dann Slice

### Actual results

Fehler: Slicing fehlgeschlagen

### Expected results

Mit Cura 5.0.0 funktioniert alles einwandfrei.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

1
[cura.log](https://github.com/Ultimaker/Cura/files/10294948/cura.log)
[EN3_Heizrohrabdeckung.zip](https://github.com/Ultimaker/Cura/files/10294949/EN3_Heizrohrabdeckung.zip)

**Comment by MariMakes** [comment]
Hey @jkilian1963,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I tried to load your project file, but was missing your Elegoo printer in my configuration.
After I loaded these files: https://github.com/Ultimaker/Cura/pull/13706
Is that the same place where you got the printer definitions? 

I was able to load and slice your print job successfully. 
![image](https://user-images.githubusercontent.com/40423138/209351224-08ccf8e8-37af-4b59-9fad-e2701b44ecca.png)

In your logs, I can see that your slicing failed.
ERROR - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [964]: Backend exited abnormally with return code 2!
DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [360]: Attempting to kill the engine process
DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [366]: Killing engine process
DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [369]: Engine process is killed. Received return code 2

Could it be related to something else happening in the background that could cause it to fail?
If you would try again now, does your slice still fail?
