### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by rishi807** [Ultimaker/Cura#14117]
### Application Version

5.1.0

### Platform

Mac

### Printer

Ender 3 pro

### Reproduction steps

i have started slicing a model i have downloaded online it was a 3mf file 

### Actual results

it showed me an unknown error saying it was unable to slice

### Expected results

i think it should slice the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment]
Hey @rishi807,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We'll need a little bit more information from you before we can start troubleshooting. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
