### ISSUE TITLE
Time left bug while printing via USB

### ISSUE THREAD

**Issue by Panostop** [Ultimaker/Cura#14122]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Biqu B1

### Reproduction steps

I launched a print via USB
I went to the monitoring section of the application
I checked the time left until the print is finished

### Actual results

![image](https://user-images.githubusercontent.com/94406359/209416098-0e756c24-5d42-4246-b6eb-b7d411c4bfe3.png)
This happens

### Expected results

i should have seen a normal printing time and time left

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it does this every single time...

**Comment by GregValiant** [comment]
Thanks for the report.
There have been a lot of reports about USB printing (Ultimaker printers don't use it anymore and consequently UM doesn't support it) but I haven't heard of this one.
Do you have any post-processors active?  I'm not sure but I think the time comment lines are read and they are in seconds.  If that gets altered in some way then USB Printing plugin won't understand them.
At the beginning of a gcode should be ";TIME:13733" where the number is in seconds.  Throughout the file are additional lines like: ";TIME_ELAPSED:169.071466".  It should be just some simple math and formatting to get the display correct, but if the numbers are wrong then everything falls apart.
