### ISSUE TITLE
model inserting issue

### ISSUE THREAD

**Issue by ojibs11** [Ultimaker/Cura#14128]
### Application Version

5.2.1

### Platform

macOS monterey

### Printer

ender 3 pro

### Reproduction steps

wont insert model.
redownloaded model and still wont insert

### Actual results

file name changes to what the model is but nothing inserted on build plate
<img width="1438" alt="Screen Shot 2022-12-24 at 11 56 31 AM" src="https://user-images.githubusercontent.com/121355658/209446788-ab4b13e8-25bd-444d-b828-326bb2f8a305.png">

### Expected results

model should be seen

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="227" alt="Screen Shot 2022-12-24 at 12 00 53 PM" src="https://user-images.githubusercontent.com/121355658/209446876-90b3c343-8fef-4a2a-b959-25adae72c93c.png">

**Comment by GregValiant** [comment]
Thanks for the report.
The model might be in there but so far off screen it doesn't show.  Try this:
Right click and select "Select all Models".
On the left toolbar select the Move tool and if the numbers are big then the model is there.  Set all the numbers to "0".

If that isn't the case then something else is wrong and someone from the Cura team may be able to help.

**Comment by ojibs11** [comment]
thanks this fixed the issue with this new update it made the model so small that you couldn't actually see it when it was inserted

**Comment by GregValiant** [comment]
One of the tools you get with Mesh Tools is an option for default scaling when models are brought in.  It's a really good set of tools to have.  It's in the Cura Marketplace.  After installing you will have to quit Cura and restart it.
After the restart go to "Extensions" and "Mesh Tools" and down at the bottom is Mesh Tools Settings.  One box is "Units for models that don't specify units".  If models are drawn in inches then you would select Inches and Cura will auto scale small models by 2540% to convert them to millimeters.
