### ISSUE TITLE
Unexpected Slicing Error

### ISSUE THREAD

**Issue by Lord-Memester** [Ultimaker/Cura#14124]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

1. Import [this file](url)
2. Attempt to slice it

### Actual results

Unexpected Slicing Error

### Expected results

Sliced Successfully

### Checklist of files to include

- [1] Log file
- [1] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10297987/cura.log)
[day17_strainerfunnel_error.zip](https://github.com/Ultimaker/Cura/files/10297988/day17_strainerfunnel_error.zip)
![image](https://user-images.githubusercontent.com/71044282/209421117-b8981459-08f0-4c83-b31f-e8ae5c0c5118.png)

**Comment by GregValiant** [comment]
Thanks for the report.
5.0 had problems both with slicing and with the dialog boxes and controls.  Much of that has been worked out (although there is still a slicing bug in Windows installations).  I suggest you upgrade to 5.2.1.
I didn't have any trouble slicing this in 5.2.1.  In 5.0 you might trying moving and/or rotating the model on the build plate to see if that makes a difference.

This is one of those models that looks easy, but it isn't.
Regarding this particular model:
With the Wall Order of the model set to "Inside to Outside" there are a lot of little spots that go down on the first layer and the chances of every one sticking correctly to the bed is not good.  I think if the Outer Walls go down first on the Initial Layer that the chances of a failure are much lower.
I would suggest that you put a Support Blocker in and scale it to 125 x 125 x 0.25 thick (1 layer height) and move it to 0,0,0.
Choose Per Model settings.  Set the blocker as a Cutting Mesh.  Use Select Settings and Wall Ordering and set it to "Outside to Inside".  That will change just the Initial Layer wall order and it has a much higher chance of success.
You have "Hole Horizontal Expansion" set to 0.3 and that is causing some separation between the outer part of the model and the strainer holes in the bottom.  I would suggest you set it to "0" and if there are issues with the model then the model should be altered.

Let us know if upgrading to 5.2.1 allows this to slice for you.
