### ISSUE TITLE
Add Support for Qt Wayland

### ISSUE THREAD

**Issue by decipher-random** [Ultimaker/Cura#14136]
### Is your feature request related to a problem?

AppImages don't load/open on linux using Wayland. AppImages have to be launched via commandline by setting the environment variable `QT_QPA_PLATFORM=xcb ./cura-version.AppImage`.

### Describe alternatives you've considered

`QT_QPA_PLATFORM=wayland;xcb` allows static Qt apps without QtWayland to start with the xcb backend. Apps that support Wayland will use the Wayland backend.

### Affected users and/or printers

Linux users using wayland and not X11. Alos considering many Linux systems will be replacing X11 for Wayland in the future.

**Comment by piontec** [comment]
I checked both (setting env variable and the alpha build) and nothing helped. Still, I made an experiment: I moved my cura dirs like this
```
mv ~/.local/share/cura ~/.local/share/cura.old
mv ~/.config/cura ~/.config/cura.old
```

and then 5.3.0 started (at least showed me the 'add printer' wizard, I didn't continue from there), and the workbench loaded.
So it seems it's something about my config and/or plugins. Still, 5.2.1 works perfectly fine :| Let me know how can I help and provide more debug data.
