### ISSUE TITLE
Crash when slicing model

### ISSUE THREAD

**Issue by quad341** [Ultimaker/Cura#14148]
### Application Version

5.2.1

### Platform

Windows 11 with NVidia GTX 1050

### Printer

Anycubic i3 Mega X

### Reproduction steps

1. Open attachec project
2. Slice

### Actual results

Slicing engine crashes :(

### Expected results

It slices!

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura-20221227-gladosCrash.zip](https://github.com/Ultimaker/Cura/files/10312759/cura-20221227-gladosCrash.zip)
[AI3MX_GlaDOS Head V1.1.zip](https://github.com/Ultimaker/Cura/files/10312761/AI3MX_GlaDOS.Head.V1.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm a fan of Portal.
The model sliced fine for me so I can't duplicate the problem.  There is a bug in Cura that can keep good models from slicing.  A workaround is to rotate the model on the Cura build plate.  That will often fool the bug.
Let us know if rotating the model works for you as that would indicate we're talking about the same bug as has been noted.

You will notice that with your current settings this is a 6 1/2 day print.
![image](https://user-images.githubusercontent.com/64202104/209825326-1ffaf092-f34b-49b7-97a5-4f33889a09df.png)
