### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lway40** [Ultimaker/Cura#14147]
### Application Version

5.1.1 and 5.2.1

### Platform

windows 10

### Printer

creality CR-10 v3

### Reproduction steps

as soon as i hit 143 scale it stops working and when i hit 153 scale it starts working again 

![Screenshot (685)](https://user-images.githubusercontent.com/121535584/209766770-1410a730-20e3-4794-b405-012cc5d61891.png)
![Screenshot (686)](https://user-images.githubusercontent.com/121535584/209766804-94f15b0f-fe4d-4a6f-8d29-e7ab1214b456.png)
![Screenshot (687)](https://user-images.githubusercontent.com/121535584/209766808-0535cf50-c938-48d4-b1bd-1d2c67ba3f5c.png)
![Screenshot (688)](https://user-images.githubusercontent.com/121535584/209766810-bd54bf0d-3c12-4e8e-a28c-fa40b375104a.png)
![Screenshot (689)](https://user-images.githubusercontent.com/121535584/209766811-0250fa32-0001-4504-a4b7-c9a1e1677d87.png)
![Screenshot (690)](https://user-images.githubusercontent.com/121535584/209766812-09e7ac3e-8783-4fe4-a36a-bd034ad81a28.png)
![Screenshot (691)](https://user-images.githubusercontent.com/121535584/209766813-73b8632e-5742-4d79-b147-81d070ef2e6b.png)
![Screenshot (692)](https://user-images.githubusercontent.com/121535584/209766814-4b669610-0a47-43ec-8f92-1aad7a235219.png)
![Screenshot (693)](https://user-images.githubusercontent.com/121535584/209766816-ea24f73b-6e69-4638-963a-a65b72e66727.png)
![Screenshot (694)](https://user-images.githubusercontent.com/121535584/209766817-7f3588ec-a14b-4bed-89a3-602ea96bfd67.png)
![Screenshot (695)](https://user-images.githubusercontent.com/121535584/209766818-445aa90b-e41d-46b4-b01e-e9ce7ce84ae5.png)
![Screenshot (696)](https://user-images.githubusercontent.com/121535584/209766819-3038e5fd-5e57-43d7-a08b-a8d86f14e474.png)

### Actual results

when i hit a scale the program stops working and when i scale 1 point up until i hit 153 scale then it starts working again 

### Expected results

there is not mush more that i can say but there is a bug in the program or the 3-D print file so I'm sending a report to you and to the one that made the file as well

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10312415/cura.log)
[cura.log](https://github.com/Ultimaker/Cura/files/10312421/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
If you can share the file then a Project File would be the best for debugging.
There is a bug in Cura that will keep a model from slicing when the model is in certain orientations, or in the center of the build plate.  Moving and/or rotating the model can often fool the bug.
I'll mark this as a duplicate and someone from the Cura team will take a look.
