### ISSUE TITLE
Any news on a more consistent Z-seam?

### ISSUE THREAD

**Issue by meltiseugen** [Ultimaker/Cura#14140]
### Application Version

5.2.1

### Platform

All

### Printer

All

### Reproduction steps

Add a sphere, slice it with z-seam set as: user specified, seam corner preference as None

added project file

[sphere.3mf.zip](https://github.com/Ultimaker/Cura/files/10306731/sphere.3mf.zip)

### Actual results

zig-zag seam positioning

<img width="575" alt="image" src="https://user-images.githubusercontent.com/18147746/209630430-c630a4c1-700d-4502-a75c-eebe55dd3464.png">

### Expected results

straight seam positioning

<img width="516" alt="image" src="https://user-images.githubusercontent.com/18147746/209630575-1f8db00a-c861-4eb2-97a1-65981f0aab9d.png">

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

N/A

**Comment by MariMakes** [comment]
Hey @meltiseugen,

Thanks for your report 👍

I already spoiled it a little in this comment https://github.com/Ultimaker/Cura/issues/11877#issuecomment-1367219842 but we expect improvements in the zseam in Cura 5.3 stable.

I expect your model to look like this in the new version of Cura. 
![image](https://user-images.githubusercontent.com/40423138/210085722-fabb3e6a-cd90-48cd-be54-ff31660a55c1.png)
It's not completely resolved, but we are getting closer to a solution.

Would you still like to keep this issue open or do you agree that we can close it?

**Comment by meltiseugen** [comment]
> Hey @meltiseugen,
> 
> Thanks for your report 👍
> 
> I already spoiled it a little in this comment [#11877 (comment)](https://github.com/Ultimaker/Cura/issues/11877#issuecomment-1367219842) but we expect improvements in the zseam in Cura 5.3 stable.
> 
> I expect your model to look like this in the new version of Cura. ![image](https://user-images.githubusercontent.com/40423138/210085722-fabb3e6a-cd90-48cd-be54-ff31660a55c1.png) It's not completely resolved, but we are getting closer to a solution.
> 
> Would you still like to keep this issue open or do you agree that we can close it?

Well, you did provide news on the seam problem haha. So let's meet in the middle and I can close it. 

Honestly, I can't wait for the issue to be completely fixed (5.4?). But I really like the iterations :)

Thank you!
