### ISSUE TITLE
Crash while slicing with 2 support blockers

### ISSUE THREAD

**Issue by Ananiaskye** [Ultimaker/Cura#14154]
### Application Version

5.2.1

### Platform

Windows 10 Home

### Printer

Geeetech Mizar_S

### Reproduction steps

Added 2 support blockers to a design.
Created the first one, 
Duplicated Eraser
Adjust size and location
Click "slice" - crash. 
Attempted to slice twice - crash both times. 

I saved and attached the project in case you want to review <-- please note that the **model is a paid one and not free, do not distribute**

![Screenshot 2022-12-28 124425](https://user-images.githubusercontent.com/104271546/209864489-faa7f9f9-734f-4ed8-b298-82b8a3702502.png)
[0g_Hex3D_DozenEggs_Pack1_Egg5_0h00m.zip](https://github.com/Ultimaker/Cura/files/10316121/0g_Hex3D_DozenEggs_Pack1_Egg5_0h00m.zip)

### Actual results

Crash - app quit and invitation to log a defect

### Expected results

Slice the model.

The same model was sliced without support blockers - no crash. 
[cura.log](https://github.com/Ultimaker/Cura/files/10316134/cura.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Log and project files are attached to the previous fields.

Happy debugging!

**Processor:** Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz   3.50 GHz
**Memory:** 32 GB DDR3
**GPU :** NVIDIA GeForce GTX 980 Ti   <-- I wish Cura would use our GPUs

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug that has been reported numerous times that keeps a good model from slicing when it's in certain orientations on the Cura build plate.  The project file wouldn't slice for me either.  When I rotated the model and blockers 90° it did slice.
So far as I know this actually doesn't have anything to do with the blockers, it's a regular old slicing bug.
I'll mark this as a duplicate and close it as the Cura team has a lot of reports on this.

Here it is sliced in 5.2.1 on Windows 11.
![image](https://user-images.githubusercontent.com/64202104/209895189-4ba1cfbb-6f3c-40d2-9d1e-3cdf39200e47.png)
