### ISSUE TITLE
5.3.0-alpha One-at-a-time order now unpredictable

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#14157]
### Application Version

5.3.0-Alpha

### Platform

Windows10x64, 21H2

### Printer

All - Not printer specific

### Reproduction steps

One at a time sequence.
Add multiple items.

### Actual results

It used to be that print order was "first in, last out".
You could lay out the job for safe sequential printing by placing objects back of bed to front, knowing they would print front to back and not collide.
Now... I don't know what its doing.  
Prints 1, 3, 2, 6, 5, 4
Move a couple things around
Now its 5, 3,2,1,4, 5

Maybe its trying to do some kind of smart ordering?  From the closest to enter outward?  Largest Y first?  Or just random print order.
But this makes doing platforms of several objects one-at-a-time early impossible.

### Expected results

It used to be that print order was "first in, last out".
You could lay out the job for safe sequential printing by placing objects back of bed to front, knowing they would print front to back and not collide.
Now... I don't know what its doing.  
Prints 1, 3, 2, 6, 5, 4
Move a couple things around
Now its 5, 3,2,1,4, 5

Maybe its trying to do some kind of smart ordering?  From the closest to enter outward?  Largest Y first?  Or just random print order.
But this makes doing platforms of several objects one-at-a-time early impossible.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It used to be that print order was "first in, last out".
You could lay out the job for safe sequential printing by placing objects back of bed to front, knowing they would print front to back and not collide.
Now... I don't know what its doing.  
Prints 1, 3, 2, 6, 5, 4
Move a couple things around
Now its 5, 3,2,1,4, 5

Maybe its trying to do some kind of smart ordering?  From the closest to enter outward?  Largest Y first?  Or just random print order.
But this makes doing platforms of several objects one-at-a-time early impossible.

**Comment by MariMakes** [comment]
Hey @tlhintoq,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

One at a time is not something I use often. 
I just tried and for me, the behavior for Cura 5.1 is the same as 5.2 Alpha. 

I can bring it up to the team if I can show them the behavior before and after. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
