### ISSUE TITLE
line skin gcode fail 

### ISSUE THREAD

**Issue by SamRlaput** [Ultimaker/Cura#14172]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Alfawise u20

### Reproduction steps

Up down top/bottom patern set in line
Gcode is on line on G0 the other in G1 and E=0
Then i set top/bottom in zig-zag 
Gcode stay on G1 but E got issues
In line patern :
![image](https://user-images.githubusercontent.com/121681966/210086841-2be6ad2a-f679-4960-942c-79ff3a5614d6.png)
Gcode : 
![image](https://user-images.githubusercontent.com/121681966/210086979-bac89881-251f-4bfb-a150-a5c4740d1ae4.png)
Zig-zag patern : 
![image](https://user-images.githubusercontent.com/121681966/210087035-c0a25740-0033-40b2-8258-39f7cac5e14c.png)
Gcode : 
![image](https://user-images.githubusercontent.com/121681966/210087101-4972705a-096e-4ec1-b994-6e2901fa6735.png)

![20221230_163658](https://user-images.githubusercontent.com/121681966/210087514-8c0e78f2-7664-4a6f-bb13-9242a74d76dc.jpg)

### Actual results

No matter what type of patern (line or zig-zag) the skin are always the same result.

I try it in cura vers. 4.13.1, 5.2.1

### Expected results

Skin full....

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by GregValiant** [comment]
Thanks for the report.
A project file ("File | Save Project") is necessary for trouble-shooting.  If you would create a project file and zip it together with those two gcode files and post the zip folder here it would be very helpful.

Without the files I have to make some assumptions.
When you use the "Lines" pattern then each extrusion is on a G1 line and they are connected by travel moves that are on G0 lines.  If you have "Coasting" turned on then the extrusion stops and the following G1 line is the "Coast" move that continues the previous line but has no extrusion (no "E" value).

When you use the "Zig Zag" pattern then the extrusion never really ends and so there are no "G0" lines in the gcode.

What I see in the image you posted looks a lot like a problem with intermittent extrusion through the hot end.  Are you confident that the extruder is maintaining pressure on the filament and that there is no partial blockage in the hot end?
