### ISSUE TITLE
Error when slicing

### ISSUE THREAD

**Issue by AnakinAbel2** [Ultimaker/Cura#14175]
### Application Version

5.2.1

### Platform

windows 11

### Printer

Creality CR-10S Pro V2

### Reproduction steps

I just attempted to slice by hitting the "Slice" button.

### Actual results

Takes about 5 minutes and then gives me an error code stating "Slicing Failed Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

### Expected results

What should happen is the program should slice a gcode.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![20221230_180511](https://user-images.githubusercontent.com/121699591/210119780-9b84ae75-b61e-4f22-beca-5da5add51f68.jpg)
![20221230_180515](https://user-images.githubusercontent.com/121699591/210119783-bd44df1b-819f-40ae-95c5-db0d2d604ad3.jpg)
[CCR10SPRO_MAIN DEADPOOL TEXTURED from Do3D17.zip](https://github.com/Ultimaker/Cura/files/10326611/CCR10SPRO_MAIN.DEADPOOL.TEXTURED.from.Do3D17.zip)

**Comment by GregValiant** [comment]
Hello @AnakinAbel2 ,
I get a "Unable to open" error when I attempt to load that project file in any app (not just Cura).
Could you create a new project file (File | Save Project") and try zipping and uploading again?
