### ISSUE TITLE
Error in function multiply

### ISSUE THREAD

**Issue by Zorba40** [Ultimaker/Cura#14182]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Alfawize U20

### Reproduction steps

As soon as I use the multiply function, the software freezes and stops responding

### Actual results

the software freezes and stops responding

### Expected results

I have to close the software

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It's the same with any other STL files

**Comment by MariMakes** [comment]
Hey @Zorba40,

Welcome to the Ultimaker Cura Github 🚀 
Sorry to hear you are stuck, I'm also running on Windows 11 and haven't encountered this yet. 

I think your issue might be related to https://github.com/Ultimaker/Cura/issues/13820
We've added a ticket to the backlog with the intent to improve this. 

To learn better about what's slowing your software down, could you install a plug-in that performs more extensive logging? 
You can download it here: https://marketplace.ultimaker.com/app/cura/plugins/UltimakerPackages/ExtensiveSupportLogging
After it's installed can you.... 
	1. Select Extensions
	2. Select Remote Support
	3. Start CPU profiler
	4. Repeat your steps to reproduce. 
	5. Stop CPU profiler
	6. Save Remote Support Archive
	7. Go to the Marketplace
	8. Select the Gear icon 
	9. Uninstall Startup Optimiser
	10. Share the Remote Support Archive Zip file here on Github

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
