### ISSUE TITLE
Custom Printer Printhead Settings ignored

### ISSUE THREAD

**Issue by StefanKi** [Ultimaker/Cura#1420]
I have a custom printer.

The 0,0 point is at the front left.
The maximum (200,220) is at the back right.
There is no print bed in the first 20mm in Y.
So I can only print 0-200 in X and 20-220 in Y.
![1](https://cloud.githubusercontent.com/assets/23430325/22820233/2217e042-ef76-11e6-9e3d-841f7f1846ea.png)

My Machine Settings are following:

Printer Settings:
X (Width): 200
Y (Depth): 200

Printhead Settings:
X min: 0
Y min: 20
X max: 200
Y max 220

If I put a part at the front left, the print starts at 0,0. But there is no build plate. The build plate starts at 0,20.
If I put a part at the back right, the print don't fits the back, but is 20mm apart from the back.

I think this is a bug - or did I make a mistake?

**Comment by nallath** [comment]
The um2go has a smilar issue. In that case we solved this by changing it in the firmware. The home position is set to be (0,-20), so (0,0) is actually the first part of the plate where a print can be done.

**Comment by Ghostkeeper** [comment]
You could also solve this by adding a disallowed area. This is only possible with an actual machine definition file though (`.def.json`). Not with the "Custom FDM Printer" option in the Cura GUI.

The disallowed area is rendered as a shadow in Cura. It prevents people from placing items on it.

**Comment by StefanKi** [comment]
So my interpretation and solution of the custom printer configuration is correct?

Both "workarounds" aren't very satisfying. I think I will try both versions to find out which one is best for me. (Of course not simultaneously...)
