### ISSUE TITLE
cannot connect to digital factory

### ISSUE THREAD

**Issue by CalebThibodeaux** [Ultimaker/Cura#14209]
### Application Version

5.3.0

### Platform

windows 10

### Printer

ultimaker S5

### Reproduction steps

1. installed 5.3.0
2. open cura

### Actual results

3. the printers which are connected to the digital factory appear to be offline, and I cannot add them via the cloud or IP
4. tried restarting cura, relogging into cura, restarting PC, and re-adding the printers to the digital factory with no success. 
5. Cura 5.2.1 can connect with my printers

### Expected results

printers should be available to print via cloud in 5.3.0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![5 2 1](https://user-images.githubusercontent.com/119626214/210664331-3d695967-5801-4230-adae-5eb3c57edf4d.jpg)
![5 3 0](https://user-images.githubusercontent.com/119626214/210664335-b8d0a96e-288f-4032-98e0-12e75d5b79f3.jpg)

**Comment by MariMakes** [comment]
Hey @CalebThibodeaux,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

That's odd, I have been able to send print jobs over the cloud in the Alpha build. 
Are you sure you are signed in? That's a mistake I make myself quite often 🙈 

Do you have the log files for us so we can see what might be going on? 
You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
