### ISSUE TITLE
Cannot print stl only in Ultimaker 3 extended

### ISSUE THREAD

**Issue by labF212** [Ultimaker/Cura#14201]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Ultimaker 3 extended

### Reproduction steps

1. Try to print the stl in Ultimaker 3 make the error
2. In Blocks one is OK

### Actual results

In Ultimaker 3 makes a error

### Expected results

Print the piece

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Download the file, and try to print it in Ultimaker 3:
https://github.com/labF212/FreeCad/blob/master/assobio_WhistleV2.stl
![Screenshot 2023-01-04 090219](https://user-images.githubusercontent.com/43177468/210520428-347dabe4-3387-4797-9b46-4cbcf5cf9856.png)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the model so I cannot duplicate the problem.  There has been a bug reported on Windows installations that can be fooled by rotating and/or moving the model on the Cura build plate.  See if doing that fixes the problem and let us know.  I'll mark this as a duplicate slicing error.  The Cura team may close this as there have been several reports of good models that would not slice unless moved or rotated.

This is sliced with Cura 5.2.1 on a Windows 11 laptop.
![image](https://user-images.githubusercontent.com/64202104/210544827-b9843915-7421-4027-adcd-cb6a2316086f.png)
