### ISSUE TITLE
Cura slices with support from extruder one, but yields an error when trying to use extruder 2 for the support.

### ISSUE THREAD

**Issue by Ogatyr** [Ultimaker/Cura#14214]
### Application Version

5.2.1

### Platform

MacOS Ventura 13.0.1

### Printer

Ultimaker S5

### Reproduction steps

1. Open the file
2. Chose material for Extruder 1 (PLA)
3. Select Support
4. Select extruder 2 for the support (PVA)
5. Slice
6. Unknown error occurs
7. When selecting Extruder 1 for the support Cora slices with no issue

### Actual results

Unknown error and the slicing stops.

### Expected results

A slice with support
[cura.log](https://github.com/Ultimaker/Cura/files/10354251/cura.log)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Project file too big even when zipped

**Comment by MariMakes** [comment]
Hey @Ogatyr,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I'm afaid we don't have so much info to go on...
In your logs I can see:
`Failing to discretize parabola! Must add an apex or one of the endpoints.
CuraEngineBackend.CuraEngineBackend._onBackendQuit [964]: Backend exited abnormally with return code -11!
CuraEngineBackend.CuraEngineBackend._terminate [360]: Attempting to kill the engine process`

That is usually an indication that there is something wrong with the mesh.
Were you able to slice it in other versions of Cura?
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.

If you are trying to print with PVA are you sure you have the correct exruders selected?
If you have the wrong selected they would show up as non supported like this:
![image](https://user-images.githubusercontent.com/40423138/211309398-ba21b9ca-e160-4a44-8124-1c97acd0b377.png)

If this doesn't solve your issue, we do need a project file or at least a screenshot. 
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

Thank you 🙏
