### ISSUE TITLE
Possible Input Validation Error

### ISSUE THREAD

**Issue by fatofthelan** [Ultimaker/Cura#14211]
### Application Version

5.2.1

### Platform

Mac OS

### Printer

Ender 3 S1

### Reproduction steps

If I enter "PLA+" in the Material Type for my filament, I can no longer see my printing profiles. If I remove the "+" from the Material Type, my printing profiles reappear. 

### Actual results

Printing profile vanish when a Plus sign is in the Material Type field.

### Expected results

Input should be constrained/sanitized and not affect visibility of printing profiles.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by MariMakes** [comment]
Hey @fatofthelan,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This has been a known issue for a while most interactions around it can be found here https://github.com/Ultimaker/Cura/issues/8229

You can read more about it in the linked ticket but it's actually intended. 
The Material Type Field needs to match EXACTLY the known materials in Cura. 

But the behavior has been so confusing that we have a ticket on our backlog with the intent to improve this.
We've been getting a lot of reports on this, so I hope we can resolve this soon 🤞 

I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/8229
