### ISSUE TITLE
Pc with good config crash cura

### ISSUE THREAD

**Issue by Rip01nt** [Ultimaker/Cura#14239]
### Application Version

any version biger than 4.13.1

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. install cura
2. open cura
3. close cura
4. open cura

### Actual results

cura crashed at start

### Expected results

cura working proprely, and opening up the interface

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

there's just a blank window with at the top "cura {version} (vot responding)"

**Comment by MariMakes** [comment]
Hey @Rip01nt,

Welcome to the Ultimaker Cura Github 🚀 
Sorry to hear you are stuck 😖 

I have a couple of questions to narrow it down.
	1. Do you have multiple monitors? Does Cura start if you disable one of the monitors?
	2. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
	3. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
	4. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665
	5. If your problem is related to scaling, can you try this workaround from the community? https://community.ultimaker.com/topic/41458-ultimaker-cura-510-window-scaling-problem/#comment-311838

If this doesn't work for you, let us know.
We'll see what we can doe.
