### ISSUE TITLE
Cant Slice the Cinderwing 3D Nighwing Curled.

### ISSUE THREAD

**Issue by karcaw** [Ultimaker/Cura#14240]
### Application Version

5.3.0-alpha+xmas

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. loaded STL.
2. Tried to slice it.

### Actual results

Says slicing failed with unexpected error

### Expected results

its slices
[cura.log](https://github.com/Ultimaker/Cura/files/10367544/cura.log)
![slice fail dragon](https://user-images.githubusercontent.com/663031/211177131-bb792648-dc92-41f9-92d2-4e74e6d1447e.png)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

no project as it would contain the dragon stl which i dont have license to share

**Comment by karcaw** [comment]
Slices Fine in Cura 5.2.1

**Comment by karcaw** [comment]
So..  as luck would have it I loaded the same model up to try moving and scaling it, and I slices just fine today, at the origin, and off the origin.  so I'm not sure what I changed, as its just my standard Print Profile.  Probably can close the ticket until I see the issue again.

**Comment by MariMakes** [comment]
Hey @karcaw,

Thanks for getting back to us.
Good luck with printing your amazing dragon 🐉 

I'll close the ticket.
