### ISSUE TITLE
Cura 2.4 interface layer issues

### ISSUE THREAD

**Issue by jaibooot** [Ultimaker/Cura#1424]
Hello,

I have noticed that cura 2.4 prints the interface layer on the bottom of the support fine, but skips the interface layer closest to the part, and replaces it with a gap.

So, If I am printing with .2mm layer height and specify .6mm of interface, I will get 3 layers on the bottom of the support and only 2 layers on the top of the support.

Thanks - Jay

**Comment by Ghostkeeper** [comment]
This was remarked by other beta testers as well. We've fixed this since then in more recent versions of 2.4.
