### ISSUE TITLE
Problema no Segmenta

### ISSUE THREAD

**Issue by sergiocassini** [Ultimaker/Cura#14266]
### Application Version

5.1.0

### Platform

windows 10

### Printer

Hellbot Magna 2 230

### Reproduction steps

Puse a cortar una figura con dos estrusores en cura para una impresora hellbot Magna 2 230, la misma consta de cuatro capas a diferente altura, al segmentarla se cuelga.

### Actual results

![image](https://user-images.githubusercontent.com/50642021/211678252-015f6c64-8115-4d76-a6e7-b14fa2d7cac6.png)

### Expected results

Se termine de segmentar

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/50642021/211678663-5fc22275-dd2e-48b9-a393-466340c7ac20.png)

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file to troubleshoot what is going on.  Use the "File | Save Project" command to create a 3mf project file.  Zip the file and post the zip folder here.

**Comment by MariMakes** [comment]
Hey @sergiocassini,

Lo siento, no puedo hablar español, pero creo que puedo ayudarte.

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
