### ISSUE TITLE
Unable to use Cura prepare upon opening

### ISSUE THREAD

**Issue by markdid** [Ultimaker/Cura#14275]
### Application Version

5.2.1

### Platform

Linux (Zorin OS based on Ubuntu)

### Printer

Anycubic Vyper

### Reproduction steps

Open Cura

### Actual results

Prepare preview opens with build area preview as normal until quickly snapping to a smaller (about 1/4) area in bottom left hand corner.
![image](https://user-images.githubusercontent.com/14829066/211947042-1ff5980d-0e60-4669-93d5-2524c5abc714.png)

When I import a model, the only way I can select it is by selecting it in the object list
This shows the move/rotate controls but if I try to interact with the object it de-selects it and I can't do anything

Only way I've been able to fix it so far is by restarting my computer. Restarting the program yeilds same results.yields

### Expected results

Regular operation - preview full screen, objects interactable.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

NA

**Comment by MariMakes** [comment]
Hey @markdid,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I showed your issue to the team and our Mac and Linux Developers instantly recognized your issue. 
They mentioned that your prepare window should respond again if you slightly resize your window with Maximize/Resize button. You don't need to reboot your computer. 

Can you let us know if that works for you? 😇
