### ISSUE TITLE
failed print slice error

### ISSUE THREAD

**Issue by sailor1118** [Ultimaker/Cura#14274]
### Application Version

5.21

### Platform

windows 10

### Printer

anycube koba

### Reproduction steps

have been slicing with no problems till yesterday now get an "slicing failed with unexplected error please consider reporting.
Yesterday uninstalled and reinstalled cura which fixed and was able to slide the file.  But same problem again today,  A first thought may been my file but get same thing on all my stl  files.

### Actual results

still unable to slice

### Expected results

cura slices my projects
[AK_pizza bracket 1.1.zip](https://github.com/Ultimaker/Cura/files/10396805/AK_pizza.bracket.1.1.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AK_pizza bracket 1.1.zip](https://github.com/Ultimaker/Cura/files/10396809/AK_pizza.bracket.1.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The models don't show any errors and sliced for me on the first try.
There has been a persistent bug reported that keeps good models from slicing when they are in certain positions on the build plate.  Try rotating and or simply moving the models around on the build plate.

I'll mark this as a Slicing Error and a Duplicate.  We'd like to know if the workaround allowed you to slice.
