### ISSUE TITLE
Typo in the mouse-over/hover pop-up in Cura Settings

### ISSUE THREAD

**Issue by CriticaI13** [Ultimaker/Cura#14276]
### Application Version

5.1.1

### Platform

WIndows 10

### Printer

Tronxy X5SA Pro

### Reproduction steps

I have poured through Github to find the relevant .md file and create a pull, but I have been unable to find the correct file - sorry, I'm not very Github literate.

```Settings``` > ```Configure setting visibility``` (open ```Preferences```). Under ```Special Modes```, hover ```Relative Extrusion``` and the 23rd ish word is '_the_', which should be '_then_'.

Can someone please explain how I could have just done this myself? I feel a bit stoopid for not being able to accomplish adding a single letter!

### Actual results

```Settings``` > ```Configure setting visibility``` (open ```Preferences```). Under ```Special Modes```, hover ```Relative Extrusion``` and the 23rd ish word is '_the_', which should be '_then_'.

### Expected results

```Settings``` > ```Configure setting visibility``` (open ```Preferences```). Under ```Special Modes```, hover ```Relative Extrusion``` and the 23rd ish word is '_the_', which should be '_then_'.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No files added.

**Comment by MariMakes** [comment]
Hey @CriticaI13,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report. It's super clear! 👍 

I found the place where the tooltip description is given.  [It seems to be here ](https://github.com/Ultimaker/Cura/blob/5c38f62d39b2ede50a5dc3c71a826c3dcb938e02/resources/i18n/fdmprinter.def.json.pot#L6468) 

The Cura default tooltip looks like this
![image](https://user-images.githubusercontent.com/40423138/212723520-80d34b50-75a3-494c-9c19-4c005fa6456d.png)

Could it be, that you found the typo in the settings guide plug-in?
That replaces your Cura default tooltip [and can be found here.](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/blackmagic/relative_extrusion.md) 
`... These instructions move the print head to certain positions and the engages the feeder. ...` 

That description seems to have a typo, is that the typo you were referring to?

**Comment by MariMakes** [comment]
Hey @CriticaI13,

Thanks for getting back to us. 
If I understand [our Translation Cura wiki ](https://github.com/Ultimaker/Cura/wiki/Translating-Cura) correctly there are four places where string definitions live. 
If you want to create a PR it probably lives in one of these four places. 
1. https://github.com/Ultimaker/Cura/blob/master/resources/i18n/cura.pot
2. https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fdmextruder.def.json.pot
3. https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fdmprinter.def.json.pot (This one is the largest)
4. https://github.com/Ultimaker/Uranium/blob/master/resources/i18n/uranium.pot

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
You can submit a Pull Request for the settings guide plugin here: 
https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/blackmagic/relative_extrusion.md

Thanks for the report, I'll close the issue.
