### ISSUE TITLE
One of the Japanese menus is not appropriate

### ISSUE THREAD

**Issue by tamorikawa** [Ultimaker/Cura#14290]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

not filled in

### Reproduction steps

In Japanese, "Extensions" in the menu becomes "拡張子", but I think "拡張" is correct.

### Actual results

not filled in

### Expected results

not filled in

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

not filled in

**Comment by MariMakes** [comment]
Hey @tamorikawa,

Welcome to the Ultimaker Cura Github 🚀 
We are always super happy if our community helps to improve Cura. 

I've changed two mentions of 拡張子 to 拡張.
You can check the pull request here: https://github.com/Ultimaker/Cura/pull/14339
Once it passes review, you can expect it in the next Cura Release. 

🙇 Thank you so much for helping us out by pointing out ways to improve.
