### ISSUE TITLE
Tree support through part

### ISSUE THREAD

**Issue by mslucass** [Ultimaker/Cura#14307]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender3 with BTT SKR

### Reproduction steps

slice the part and the support will go through the part instead of around it

### Actual results

![cura](https://user-images.githubusercontent.com/20923229/212747708-2ff02cad-a929-485f-9b7f-cefe86fd24f9.PNG)

support through part

### Expected results

only support on the build plate next to the hole

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3E3V2_051 - 24v cover.zip](https://github.com/Ultimaker/Cura/files/10428621/CE3E3V2_051.-.24v.cover.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the project file.
I can duplicate this with your project.  The Cura team will take a look.

For this model I wouldn't bother to support those holes.  They are small and should bridge with no issues.  That would allow you to use normal supports and "touching buildplate" which will eliminate the "Going Through The Model Problem".

**Comment by DerGenaue** [comment]
Please try the new [Tree Support XMas Alpha](https://github.com/Ultimaker/Cura/discussions/14111).
It should solve this problem
