### ISSUE TITLE
Image Reader doesn't remember width and depth

### ISSUE THREAD

**Issue by peteruithoven** [Ultimaker/Cura#1430]
When an image is loaded in Cura a *Convert Image* popup is shown. All these settings are maintained when another image is loaded, which makes it much easier to play with them. But the width and depth settings aren't stored. 
Maybe because there is some logic to keep the aspect ratio which prevents this? 
![screenshot from 2017-02-14 17 06 17](https://cloud.githubusercontent.com/assets/523210/22937222/3b23a21e-f2d8-11e6-822e-b5ebc5e69813.png)

**Comment by Ghostkeeper** [comment]
The width is indeed kept to honour the aspect ratio.

The depth though, I don't know why it would reset for each image.
