### ISSUE TITLE
5.3.0-alpha+xmas unneeded supports

### ISSUE THREAD

**Issue by pantala** [Ultimaker/Cura#14302]
### Application Version

5.3.0-alpha+xmas

### Platform

MacOS M1

### Printer

Prusa i3 MK3S+

### Reproduction steps

1. Load STL (attached project file)
2. Slice using new xmas tree supports

### Actual results

Unneeded supports generated in the middle of the model where there is no overhang.

### Expected results

Supports generated only on the outer rim where there is an overhang. (This doesn't happen with normal supports.)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[PI3MK3M_Wheels_frontrim.3mf.zip](https://github.com/Ultimaker/Cura/files/10421205/PI3MK3M_Wheels_frontrim.3mf.zip)
<img width="614" alt="Screenshot 2023-01-15 at 1 02 05 PM" src="https://user-images.githubusercontent.com/8108119/212567115-231b9f8a-98fd-4e8c-8c7e-99f66a7a2a1b.png">
<img width="606" alt="Screenshot 2023-01-15 at 1 02 12 PM" src="https://user-images.githubusercontent.com/8108119/212567118-4ad0a6da-a148-48fa-ac37-6f9fd5730658.png">

**Comment by DerGenaue** [comment]
This is probably the same as has been reported in this discussion: https://github.com/Ultimaker/Cura/discussions/14111?sort=top#discussioncomment-4585873
Te bug has already been fixed for the next version

**Comment by DerGenaue** [comment]
If you want to, you can try out this fix by the original contributor of the new tree support algorithm:
Be aware that this is not an official Ultimaker build though and that you need to be on Windows to test it
https://github.com/ThomasRahm/CuraEngine/releases/tag/5.3.0-alpha%2Bxmas%2Bfixes

**Comment by MariMakes** [comment]
Hey @pantala,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for the analysis @DerGenaue 🤩 

We've also received a report on this on our Community Forum.
And have already added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10179

Thanks for the report! 👍

**Comment by DerGenaue** [comment]
Should be solved in 5.4

**Comment by MariMakes** [comment]
True 😊 
I'm closing this issue.
