### ISSUE TITLE
Druckerauswahl

### ISSUE THREAD

**Issue by Andreas02994** [Ultimaker/Cura#14308]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Monoprice MP10

### Reproduction steps

Mein Drucker ist nicht in der Auswahl in CURA vertreten

### Actual results

ich kann Cura deshalb nicht nutzen

### Expected results

Ich brauche eine Lösung, da Cura 4... nicht ordnungsgemäß slikt

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Ich bitte um Antwort

**Comment by GregValiant** [comment]
The printer definition files are submitted to Ultimaker by members of the community or by the printer manufacturer.  Ultimaker simply has no way to provide a definition for a printer produced by someone else.
There is a link on the Monoprice site for downloading their version of Cura 4.0.  It would appear to have a definition for your printer.  There also appears to be people out there using the Creality CR-10 definition with success.  You will need to figure it out for yourself.
Maybe the Reddit site has some information on how people have coped with this problem.  

I'll remove the bug label from this as it appears to be a Monoprice decision to not supply a definition for their printers..

**Comment by Andreas02994** [comment]
Danke für die Auskunft. Mit der Version Cura 4…. Ist es nicht möglich eine entsprechende Datei zu erzeugen. Bei einem geschätzten Volumen von ca. 6MB hat die Datei eine Größe von 696kB bis 2500 kB., obwohl der Körper in Cura angezeigt wird. Ich werde es mit Creality CR 10 versuchen und mich an Monoprice wenden.

Danke für die Nachricht und alles Gute

 

Von: GregValiant ***@***.***> 
Gesendet: Dienstag, 17. Januar 2023 00:37
An: Ultimaker/Cura ***@***.***>
Cc: Andreas02994 ***@***.***>; Author ***@***.***>
Betreff: Re: [Ultimaker/Cura] Druckerauswahl (Issue #14308)

 

The printer definition files are submitted to Ultimaker by members of the community or by the printer manufacturer. Ultimaker simply has no way to provide a definition for a printer produced by someone else.
There is a link on the Monoprice site for downloading their version of Cura 4.0. It would appear to have a definition for your printer. There also appears to be people out there using the Creality CR-10 definition with success. You will need to figure it out for yourself.
Maybe the Reddit site has some information on how people have coped with this problem.

I'll remove the bug label from this as it appears to be a Monoprice decision to not supply a definition for their printers..

**Comment by GregValiant** [comment]
@Andreas02994 
A definition can consist of several files.  If you have loaded the 4.0 version from Monoprice then you may have all that is required to copy them to 5.2.1.
You can open a definition file in a text editor like Windows Notepad.  The first several lines of the file will indicate what other files you need.  If the definition "inherits" another definition, has an "extruder", has a "platform", has "variants", has "quality", then those other files will be required.  In 5.x Cura the folders are moved down a level to the "...\share\" folder.  Platforms are in the "Meshes" folder.
If there is an "inherits" then you would also need to open the Inherited file and see what it requires.

I'll go ahead and close this.  I hope you understand.
