### ISSUE TITLE
Starts slice put won't slice

### ISSUE THREAD

**Issue by rlebkuecher** [Ultimaker/Cura#14311]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 5 Plus

### Reproduction steps

Tried to slice a new object and it failed. I resaved the object from Tinkercad as a stl again with the same results.
![Phone Holder](https://user-images.githubusercontent.com/81172090/212908715-41963427-fadd-4f33-9899-5eda97e00ee5.jpg)

### Actual results

The Error message popped up saying Slicing Failed with an unexpected error.

### Expected results

I expected the item to slice.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10435413/cura.log)
[Phone Holder v6.zip](https://github.com/Ultimaker/Cura/files/10435440/Phone.Holder.v6.zip)

**Comment by rlebkuecher** [comment]
In Tinkercad I undid the last grouping of the part then regrouped it without any changes to the design. After that I exported the object again as an stl and it sliced just fine.

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't find anything wrong with the model you posted and it sliced fine for me.
It seems to have been a model error rather than a Cura bug.  Can we close this then?
