### ISSUE TITLE
FILL-IN ERRORS IN GCODES

### ISSUE THREAD

**Issue by DalSheron** [Ultimaker/Cura#14345]
### Application Version

5.1.0

### Platform

Windows 10 Pro

### Printer

TwoTrees SP-5

### Reproduction steps

I write these mugs from DEEP ROCK GALACTIC so I can print them, Rotate them by 90 degrees so bottoms meet print bed, then scale them to 500%, write to GCODE and then the tops are filled in where they shouldnt be.
![Screenshot 2023-01-20 12 15 21](https://user-images.githubusercontent.com/18010883/213780315-c2cd76f8-760a-4a92-87f7-506b2671f184.png)
![Screenshot 2023-01-20 12 15 26](https://user-images.githubusercontent.com/18010883/213780339-590c1015-fc6d-48a2-9777-cc4765a6df07.png)
![Screenshot 2023-01-20 12 20 20](https://user-images.githubusercontent.com/18010883/213780406-2a7e832a-5b62-4ea0-ba3f-fc745a449b02.png)
![Screenshot 2023-01-20 12 20 24](https://user-images.githubusercontent.com/18010883/213780428-4bb76c8d-e791-4e2b-b079-ae754d9cc286.png)
![Screenshot 2023-01-20 12 21 58](https://user-images.githubusercontent.com/18010883/213780443-01772af8-b72b-4025-9a52-9c4b971777b9.png)
![Screenshot 2023-01-20 12 22 01](https://user-images.githubusercontent.com/18010883/213780462-bc723a82-c14b-4071-9300-627ddd6983f8.png)
![Screenshot 2023-01-20 12 22 35](https://user-images.githubusercontent.com/18010883/213780474-3ed862bf-75db-4c87-8823-a44647562f6f.png)
![Screenshot 2023-01-20 12 22 37](https://user-images.githubusercontent.com/18010883/213780488-a861da01-a9c8-4c1e-828a-053e9079a115.png)
![Screenshot 2023-01-20 12 24 17](https://user-images.githubusercontent.com/18010883/213780498-89747008-c9bb-4d7d-9d93-2ff0b637de18.png)
![Screenshot 2023-01-20 12 24 20](https://user-images.githubusercontent.com/18010883/213780514-4927059d-5f7d-4f73-9a89-199f1e5f013c.png)
![Screenshot 2023-01-20 12 24 56](https://user-images.githubusercontent.com/18010883/213780533-cded6d4a-b5e1-4100-9f9a-e999a6ea8f23.png)
![Screenshot 2023-01-20 12 24 57](https://user-images.githubusercontent.com/18010883/213780560-bc3df440-934d-4dd4-b929-c36501efc270.png)
![Screenshot 2023-01-20 12 16 45](https://user-images.githubusercontent.com/18010883/213780376-438f0a8c-bfa9-4abf-91ea-9d355d9fa88a.png)
![Screenshot 2023-01-20 12 16 59](https://user-images.githubusercontent.com/18010883/213780389-6c82f768-1130-419f-ae51-c87b7336aaec.png)

### Actual results

Mug internal surfaces are joined by layers of material that should not be there, rendering mugs useless from an appearance perspective

### Expected results

The mug internals should be voided as they are in the preview models.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

these are the files I used
[DRG-Beer-mugs.zip](https://github.com/Ultimaker/Cura/files/10469223/DRG-Beer-mugs.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10469229/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I thought for sure I'd be telling you to turn off "Remove All Holes".  I still might but here is a view of the first model I opened...
![image](https://user-images.githubusercontent.com/64202104/213811495-111a7e06-8cda-446d-8420-80f31755dbc3.png)

All of those red areas are problems within the model.  I tried to repair that one in MS 3D Builder but it didn't work.  Mesh Mixer couldn't fix them either  This is the "deep" side.
![image](https://user-images.githubusercontent.com/64202104/213815182-9efc7619-d9b9-4d41-8961-8464d524c303.png)

I opened a couple of others and they also show errors.  When Cura paints something in polka-dots it indicates problems in the model.  I wouldn't expect these models to slice correctly.
I'll remove the bug label from this but I'll leave it open so you can respond.  Those are some bad models.  Even the ones that looked like they sliced OK have gaps and holes.

**Comment by Asterchades** [comment]
Videogame models are very rarely, if ever going to be 3D printable without modification. They're only really made to look good on a screen - due to things like Z-buffering and backface culling there are a lot of modelling shortcuts which can, and often are, used to both reduce the artist's work and to reduce the GPU load (clipping is less expensive than additional geometry). And that's before considering geometry which is only used to apply effects (glows, liquids, etc).

These in particular appear to be riddled with internal geometry - to the point where it's going to require largely manual correction, given Greg's experiences with automated tools.

**Comment by DalSheron** [comment]
too bad I have zero experience with modeling outside of Autodesk Inventor, otherwise 3d modeling is largely alien to me.

**Comment by GregValiant** [comment]
@DalSheron  if you really want those models you could use a utility like [THIS ONE](https://www.cadforum.cz/catalog_en/stl2dwg.asp) and use their STLtoDWG tool.  It's time consuming to do it that way as you are basically starting from scratch.  You will end up with a good model though.
I'm going to go ahead and close this as it isn't a Cura problem.  I hope you understand.
