### ISSUE TITLE
Mixed layer height for time saving

### ISSUE THREAD

**Issue by anders661228** [Ultimaker/Cura#14366]
### Is your feature request related to a problem?

I am always irritated when the printer print the infill and support with the same layer height as the wall. 

### Describe the solution you'd like

Wouldnt it be possible to first print the wall with say 0.1mm layer height in 3 layers, and then the infill or support with one 0.3mm layer height.
This will save a lot of time. 🙂

### Describe alternatives you've considered

I dont have any alternative. 

### Affected users and/or printers

Time saving with the same quality.

**Comment by Asterchades** [comment]
You can already do this. There's an Infill Layer Thickness setting and a corresponding Support Infill Layer Thickness setting already built in, and they've been there for quite some time now (I want to say at least as far back as 4.0.0 but can't confirm that). Like most layer-based settings these will automatically round up to the next full layer height, and it will automatically fall back to shorter lines should the full height simply not fit.

Do be aware that if you use the Line Direction option for each of these that this setting operates on a per-model-layer cadence. So if you're running infill that's two layers thick you need to treat it as two layers (it will take the first of these). eg [0, 90] to alternate a 90° offset would be best changed to [0, 90, 90, 0] so it keeps alternating the thicker layers _and_ the thinner ones.
