### ISSUE TITLE
Reverse support blocker

### ISSUE THREAD

**Issue by mirakct** [Ultimaker/Cura#14361]
### Is your feature request related to a problem?

When only needing support in specific areas of big and complex meshes it is tedious to unselect many areas with support blockers.

### Describe the solution you'd like

A support blocker, that overwrites globally disabled support to produce support only within its volume.

### Describe alternatives you've considered

print as support from per model settings can work, but is still not suited for complex areas.

### Affected users and/or printers

Anyone, who prints complex parts

**Comment by fieldOfView** [comment]
There's a custom supports plugin in the Marketplace that you may like. It has many options for creating supports in user-specified places.

I'm closing this, since it can be solved with a plugin. Feel free to ask further questions on the subject here.
