### ISSUE TITLE
Slicing failed with an unexpected error.

### ISSUE THREAD

**Issue by astead** [Ultimaker/Cura#14378]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender-3 Pro

### Reproduction steps

1. Load STL
2. Hit Slice
Also tried moving model off the center.

### Actual results

Get error message.

### Expected results

Finish slicing.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_B7.zip](https://github.com/Ultimaker/Cura/files/10495469/CE3PRO_B7.zip)
[cura_log.zip](https://github.com/Ultimaker/Cura/files/10495501/cura_log.zip)

I've been trying to build Cura from source to be able to help debug, but get stuck when it says it doesn't recognize sip-build, even though I've done pip install sip...

**Comment by astead** [comment]
I've also checked the model with the mesh tools and confirmed the model is watertight.

**Comment by astead** [comment]
![cura_error](https://user-images.githubusercontent.com/4774723/214464540-ab9400fd-688f-4a5c-be3c-b453b50ebbac.png)

**Comment by MariMakes** [comment]
Hey @astead,

Thanks for your report 👍
I'm getting a similar error in Cura 5.2.2.

I did notice that the file can be sliced in Cura 4.13.1, perhaps it's related to the variable line width Engine in Cura 5.x
I hope at least it helps you get unstuck. 
![image](https://user-images.githubusercontent.com/40423138/216616191-11b34d84-ce87-4ed4-95b2-1573b1e17f7f.png)

I'll have someone from the team take a look.

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/bd0a73d2-99da-46f1-9bcc-dfd89ed864ff)
