### ISSUE TITLE
Slicing failed with unexpected result... 

### ISSUE THREAD

**Issue by bachmarc** [Ultimaker/Cura#14385]
### Application Version

5.3 xmas 

### Platform

Windows 10

### Printer

SOVOL SV6 

### Reproduction steps

I tried to slice a STL exported from FreeCad

### Actual results

It sliced a looooong time and than aborded 

### Expected results

A slice with tree supports

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[SS_deckel.zip](https://github.com/Ultimaker/Cura/files/10507687/SS_deckel.zip)
[deckel.zip](https://github.com/Ultimaker/Cura/files/10507693/deckel.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10507698/cura.log)

**Comment by Janitortimm420** [comment]
having this same issue right now as well

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/83dc03d8-bc37-47f7-9ac4-2c7390e2c817)
