### ISSUE TITLE
slice

### ISSUE THREAD

**Issue by Isaacawesome11** [Ultimaker/Cura#14384]
### Application Version

5

### Platform

windows 10

### Printer

Ender 3

### Reproduction steps

I edited a design in Inventor then moved it to meshmixer then moved it to cura and there was a problem slicing.

### Actual results

There was a problem slicing 

### Expected results

It should have sliced the model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
Without a project file and log file there can be no investigation as we have no information to work with.  The instructions are on the opening page you filled in for the bug report.
