### ISSUE TITLE
Dark Gray Border (Printhead Settings) Changing with Variants?

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1439]
This is probably super obvious, but

The Printhead Settings available through machine settings manifest as a dark grey border. 

Trouble: This border seems to change with machine variants, even though I put nothing in the variant other than “nozzle size”

Where does this limit come from? Any ideas? 
Thanks!

PS: the following is from the machine def.json file, and that’s the only size I ever define.

```
…
"machine_width": { "default_value": 170 },
"machine_depth": { "default_value": 160 },
…
```

Basic 0.4mm variant, 0 for all printhead limits. 
![image](https://cloud.githubusercontent.com/assets/16858474/23082875/8bd69222-f55b-11e6-8502-a0b87ca36bd0.png)

0.6mm variant. Why does it make the border bigger (and print area smaller?)
![image](https://cloud.githubusercontent.com/assets/16858474/23082866/850aaee2-f55b-11e6-9d57-328851270c58.png)

**Comment by fieldOfView** [comment]
The dark border shows the area reserved for build plate adhesion such as brim, raft & skirt. These increase the footprint of your models, so you cannot print as wide as your buildplate. If you want to print at the full size of your builtplate, you would have to print eg with a 0mm wide brim.

Cura 2.4 will add a setting to not print a brim, raft or skirt, making it easier to print at the full size.

**Comment by filipgoc** [comment]
You're Absolutely right. 

For some reason, the 0.6mm variant has adhesion ON by default, even though it's empty... 
There probably is some adhesion cura default deep deep down (fdmprinter maybe). 

Thanks!

PS: I'm on Cura 2.4 Beta.

**Comment by Ghostkeeper** [comment]
The grey border (and build volume) is dependent on Adhesion Type, Skirt Gap, Skirt Line Count, Skirt/Brim Line Width, Brim Width, Brim Line Count, Raft Margin, Draft Shield Enabled, Draft Shield Distance, Raft Base Thickness, Raft Interface Thickness, Raft Surface Layers, Raft Surface Thickness, Raft Airgap, Extruder Prime Position X (disabled in GUI), Extruder Prime Position Y (disabled in GUI), Extruder Prime Position Z, Prime Tower Enabled, Prime Tower Size, Prime Tower Position X, Prime Tower Position Y, Ooze Shield Enabled, Ooze Shield Distance, Infill Wipe Distance, Travel Avoid Distance, Support Offset, Support Enabled, Avoid Other Parts, Support Interface Enabled, Support Extruder, Initial Layer Support Extruder, Support Interface Extruder and Platform Adhesion Extruder.
