### ISSUE TITLE
when setting infill it requires extra keystrokes

### ISSUE THREAD

**Issue by N6REJ** [Ultimaker/Cura#14391]
### Application Version

5.3.0-alpha-xmas

### Platform

windows 10

### Printer

Aquila S2

### Reproduction steps

click on infill density
remove a number
number will be removed and field deselected
click in box
remove or change number
change will again occur and again field will be deselected

### Actual results

deselects field with each change

### Expected results

entering field you remain in field while manipulating values until "enter" is hit or you click off.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This happens in all version 5 versions

**Comment by MariMakes** [comment]
Hey @N6REJ,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/12949
We have a ticket on our backlog with the intent to improve this behavior.
I'll be closing this issue as a duplicate but you can follow the progress here: https://github.com/Ultimaker/Cura/issues/12949
