### ISSUE TITLE
wont slice

### ISSUE THREAD

**Issue by stlprettyboy** [Ultimaker/Cura#14405]
### Application Version

5.2.1

### Platform

windows 11

### Printer

Ender 3 s1

### Reproduction steps

nothing

### Actual results

nothing

### Expected results

nothing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by GregValiant** [comment]
Thanks for the report.
It's very comprehensive and I see you spent a lot of time on it.  It pretty much says it all so I have nothing to add.
