### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by marek96681** [Ultimaker/Cura#14406]
![Snímek obrazovky 2023-01-28 180613](https://user-images.githubusercontent.com/95543523/215279447-e45d5807-f3e6-4997-892f-ddd62e64d578.jpg)
[UMS5_[a]_Idler_Cam_Lock_x2.zip](https://github.com/Ultimaker/Cura/files/10527275/UMS5_.a._Idler_Cam_Lock_x2.zip)
### Application Version

5.2.2

### Platform

Windows 11 pro

### Printer

Ultimaker S5

### Reproduction steps

1. clear build plate in Cura
2. add new parts for print
3. Change new spool in printer (Ultimaker ABS Grey)

### Actual results

Error message
![slicing_failed](https://user-images.githubusercontent.com/95543523/215266583-8c5d5850-59f1-4d0a-a65b-8acdd4b8208b.jpg)
[cura.log](https://github.com/Ultimaker/Cura/files/10527244/cura.log)

### Expected results

Get slicing Preview.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

I do not use NFC reader.

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing it.  Someone from the UM Cura team will take a look.
![image](https://user-images.githubusercontent.com/64202104/215278986-952fbad0-0af2-4675-92aa-5fb588d4befe.png)

**Comment by MariMakes** [comment]
Hey @marek96681,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

The file also slices for me. 
![image](https://user-images.githubusercontent.com/40423138/216641908-0bee334c-0a5e-4861-ba3d-2bcb0337a62f.png)

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
Perhaps you changed more settings than just the wall line count. 

To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
