### ISSUE TITLE
Slicing 

### ISSUE THREAD

**Issue by SINEZIO30** [Ultimaker/Cura#14409]
### Application Version

5.0.0

### Platform

O WINDOWS 10

### Printer

Anycubic Kobra Max

### Reproduction steps

Coloquei para Fatiar o arquivo STL... Ele carrega até a metade e da um erro "slicing engine for Cura"

![Capturar](https://user-images.githubusercontent.com/57670927/215291496-d42daa97-1de0-4470-ad9c-7c8263a408f5.JPG)

### Actual results

Não acontece nada 

### Expected results

Não acontece nada 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capturar](https://user-images.githubusercontent.com/57670927/215291736-c54a2f84-72c8-43ac-9cf5-2a20397b20e9.JPG)

**Comment by MariMakes** [comment]
Hey @SINEZIO30,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This error can have a lot of causes, were you slicing in the background? 
Did you lose connection to the internet?

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
