### ISSUE TITLE
"um" namespace question

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1440]
In the XmlMaterialProfile.py, there is 

```
# Map of recognised namespaces with a proper prefix.
    __namespaces = {
        "um": "http://www.ultimaker.com/material"
   }
```

I noticed that if a material (even the ‘generic’ ones) only loads correctly if it contains xmlns="http://www.ultimaker.com/material”.

What does this do? And Why? It seems later this is use for serialization of profiles..
(Pardon my ignorance.)

**Comment by nallath** [comment]
It's a namespace. You can use it to have extentions on a specification. 

See for more info: https://www.w3schools.com/xml/xml_namespaces.asp

**Comment by filipgoc** [comment]
Thank you for kindly supporting the XML noob in me @nallath !
