### ISSUE TITLE
cant slice

### ISSUE THREAD

**Issue by Zeezee073** [Ultimaker/Cura#14410]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creatily Ender 3

### Reproduction steps

I tried to slice the stl file but it doesn't seem to work all the other stls associated with it are perfectly fine just this. I have updated cura and my pc to see if anything was wrong but its still an issue

### Actual results

its says slicing failed

### Expected results

should've worked and told me how long it's going to be and what'll look like

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

there is nothing else to add

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura log file we have nothing to work with or look at to do an investigation.  The instructions regarding the files are on the first page you filled out for the bug report.
