### ISSUE TITLE
Проблемы с масштабированием (Zoom Issues)

### ISSUE THREAD

**Issue by sanlexandro** [Ultimaker/Cura#14414]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Flying Bear Ghost 5

### Reproduction steps

1) загрудил модель в формате stl 1) sued the model in stl format
2)отмасштабировал на 50%           2)scaled by 50%

### Actual results

Программа не отвечает и либо вылетает либо очень долго загружается
(The program does not respond and either leaves or loads for a very long time)

### Expected results

Модель должна уменьшится не 50% без вылетов
(Model should not decrease 50% without departures)
### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10529650/cura.log)
![Снимок экрана 2023-01-29 144008](https://user-images.githubusercontent.com/114338016/215323639-af349ec4-0f93-4dd9-910e-38d91a67ea6d.png)

**Comment by MariMakes** [comment]
hey @sanlexandro,

Welcome to the Ultimaker Cura Github 🚀 

I checked your logs and they seemed to be flooded by the [MKSWiFiPlugin](https://marketplace.ultimaker.com/app/cura/plugins/Jeredian/MKSWifiPlugin) .

Does your functionality return if you disable the plugin? 
Are you using the plug-in correctly?
