### ISSUE TITLE
slicer gives unknown error

### ISSUE THREAD

**Issue by co-labor-3d** [Ultimaker/Cura#14411]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic i3mega

### Reproduction steps

1. Download https://www.thingiverse.com/thing:2368726
2. import in cura
3. change  Z size to 40 mm
4. Slicing gives an error and message, that I should inform you

### Actual results

error and message, that I should inform you

### Expected results

no error message...

interesting: if I go to 39.5 mm instead of 40.0 mm then it does not crash....
exactly 40.0 mm crashes

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10528451/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report and the log.
I'm not good at reading the logs but I know this one "Backend exited abnormally with return code 3221225477!"
Someone from the Cura team will take a look.

**Comment by MariMakes** [comment]
Hey @co-labor-3d,

Thanks for your report 👍

Return code 3221225477, is actually a super generic error, even though it doesn't sound generic 😅 
In the Cura 5.3 Beta, we made a fix that should solve a number of these errors. 
Can you download the Beta and retry your slice? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

If that's it still doesn't work, we'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
