### ISSUE TITLE
model slicing keeps failing

### ISSUE THREAD

**Issue by Zuko22222222** [Ultimaker/Cura#14418]
### Application Version

5.0.0

### Platform

mac 

### Printer

ender 3 v2

### Reproduction steps

drag and drop 

### Actual results

model sling fails 

### Expected results

model slicing works

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

j

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project and Log to look at there is no way to do an investigation.  The instructions for creating a project file and finding the cura.log file are on the bug report page.  They need to be zipped and the zip folder posted here.
