### ISSUE TITLE
Recent commit features new typo

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1442]
It's funny how one's eye gets drawn to these things. Honestly, I do not go looking for mistakes!

![screenshot_2017-02-18_08-25-25](https://cloud.githubusercontent.com/assets/585618/23091697/dd892dc0-f5b3-11e6-9546-5535188572f6.png)

**Comment by fieldOfView** [comment]
Whoops, how did that happen? I could have sworn I used a find/replace to refactor this.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/1446

**Comment by nallath** [comment]
I also missed that :( Nice find.

**Comment by BagelOrb** [comment]
This seems to have been fixed
