### ISSUE TITLE
slicing fails - Cura 5.3.0-alpha+cura_9879_19

### ISSUE THREAD

**Issue by mslucass** [Ultimaker/Cura#14424]
### Application Version

UltiMaker Cura 5.3.0-alpha+cura_9879_19

### Platform

win 10

### Printer

custom ender 3v2

### Reproduction steps

just slice it

### Actual results

slicing fails

It does work in cura 5.2.1

### Expected results

success

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CE3E3V2_051 - encoder steun.zip](https://github.com/Ultimaker/Cura/files/10539250/CE3E3V2_051.-.encoder.steun.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This sliced for me on the first try so I'm unable to duplicate the problem.
There are a lot of reports here on a bug that will keep models from slicing when the model is at the mid-point of the Cura build plate.  Try moving and maybe rotating the model.  You may find a position where it will slice.
This bug has been worked on and a proposed fix has been rolled into Cura.  It will be in place in Cura 5.3.
I'll mark this as a duplicate slicing error and go ahead and close it.  The team has a LOT of examples of this behavior.
