### ISSUE TITLE
Error running cura from source

### ISSUE THREAD

**Issue by gconcha1** [Ultimaker/Cura#14438]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

3D Blocks One MkII

### Reproduction steps

I was following the guide below, and in step 3, when I tried running "conan install . --build=missing --update -o cura:devtools=True -g VirtualPythonEnv" the following error was presented. How can I solve this issue? 

https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source

PS: Sorry if this was asked before, but I couldn't find anything

### Actual results

![image](https://user-images.githubusercontent.com/124080065/215841833-1bc613d0-5fef-45ab-8332-dae08584cc13.png)

### Expected results

The initialization of the Virtual Python Development Environment.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://github.com/Ultimaker/Cura

**Comment by MariMakes** [comment]
Hey @gconcha1,

Can you confirm if this is the same issue as https://github.com/Ultimaker/Cura/issues/14337#issuecomment-1413579618?
Or do you need one of our developers to take a look?

**Comment by gconcha1** [comment]
Hi! 

Yeah it is, I was desperade at the time xD.

I'll close it.

Thanks again.
