### ISSUE TITLE
Range Slider in LayerView

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#1444]
I looked into unifying the two sliders in the new layerview. First I checked out the QML RangeSlider, but that does not *quite* do what I want, and it required PyQt5.8 due to an unfortunate packaging error. Instead I created one myself:
https://gist.github.com/fieldOfView/b4565ab77dbff625408bd926760ee3bf

![draggablerangeslider](https://cloud.githubusercontent.com/assets/143551/23093871/81934c0e-f5ee-11e6-9f22-dc999a0122e1.gif)

@jackha, are you working on this or shall I continue and prepare a PR to use this in LayerView?

**Comment by gabfv** [comment]
That's a great feature!

**Comment by nallath** [comment]
I like it!

**Comment by awhiemstra** [comment]
Nice work. As far as I know, @jackha is not currently working on any UI changes for the layer view, so feel free to make a PR.

**Comment by fieldOfView** [comment]
Work in progress here:
https://github.com/Ultimaker/Cura/compare/master...fieldOfView:feature_draggable_range_slider

**Comment by jackha** [comment]
Looks good! Currently I'm not working on any UI changes. Still fine-tuning the layer view itself and working on other issues.

**Comment by Ghostkeeper** [comment]
Processing this and coordinating this with our UX guys and fieldOfView was just planned to be done in the sprint for the following two weeks.

**Comment by fieldOfView** [comment]
I have an implementation that is mostly working, except for keyboard input. It still needs work, but that should be doable in two weeks.

**Comment by fieldOfView** [comment]
Closing this issue in favor of the PR
