### ISSUE TITLE
adaptative layer height

### ISSUE THREAD

**Issue by Malibu948975** [Ultimaker/Cura#14440]
### Application Version

5.2.2

### Platform

win10 64bits

### Printer

Geeetech I3 pro x

### Reproduction steps

3 model like a 4.1 lego brick home made, adaptive layer, and

### Actual results

 index of middle variance offset with the first layer not the the "all layer height" setting. To have the result i should put 1rst layer height as tall that all layers not wanted.

### Expected results

the middle of variance between thiner and taller layer must index on general layer height settings not the height of first layer, it would be great to put on option on seize of layer view to dont care size of first layer to see ion great color dispertion the variance of significative layers except the first that is set fix.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture](https://user-images.githubusercontent.com/96630336/215863932-24bc822a-98b1-4d14-908c-6971905468f7.JPG)
![Capture2](https://user-images.githubusercontent.com/96630336/215863967-a20a59bf-962e-4175-b0a1-b9d906e17113.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.
Look closely at the Settings Box in your screen shot.  You see you have the top setting "Layer Height" set to 0.29 and the "Initial Layer Height" set to .145.  I think you have them backwards and Cura was doing what it was told.
I don't see a bug here but rather a settings issue.  I'll leave this open so you can respond but I will remove the bug label.  Let me know if you feel that is premature.

**Comment by GregValiant** [comment]
I'll go ahead and close this then.
