### ISSUE TITLE
Cannot re-open profile manager

### ISSUE THREAD

**Issue by GregDarcy0** [Ultimaker/Cura#14447]
### Application Version

5.2.2

### Platform

Mac O/S 11.7.2

### Printer

Cocoon Create Touch

### Reproduction steps

1. Opened profile manager
2. made changes and closed profile manager
3. attempted to re-open profile manager

### Actual results

Cura ignores request to open profile manager It does not matter whether it is from the menu bar, double clicking the profile, or using the settings manager for a specific section

### Expected results

The profile manager should open to allow further changes.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10552917/cura.log)

**Comment by MariMakes** [comment]
Hey @GregDarcy0,

Thanks for your report 👍

What an odd request. This might sound dumb, but have you checked if the window is hidden under other windows? Or perhaps on another screen? We've had some reports that pop-ups like this appear in a different window. 

I'll bring it up to the team to see what they can do to improve it or see what's in you logs. Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @GregDarcy0,

I've brought your issue up to the team. We are convinced that your window might be hidden on a different screen or behind other windows. 

To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided to remove this defer this issue. 

I hope you understand.
