### ISSUE TITLE
Bug Report Cura

### ISSUE THREAD

**Issue by TGTechnic** [Ultimaker/Cura#14458]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 5 Pro

### Reproduction steps

[uploads_files_918895_Kiki-01-MAX.zip](https://github.com/Ultimaker/Cura/files/10574155/uploads_files_918895_Kiki-01-MAX.zip)
File just gives me a bug not sure why

### Actual results

not sure why the is happening

### Expected results

not sure why the is happening

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

not sure why the is happening

**Comment by GregValiant** [comment]
Thanks for the report.
Load the model and set Cura up to slice.  Use the "File | Save Project" command to create a 3mf project file.
Use the "Help | Show Configuration Folder" command to locate the Cura.log file.
Zip the Cura.log and 3mf files and post the zip folder here.
