### ISSUE TITLE
Help with UltiMaker Cura 5.2.2

### ISSUE THREAD

**Issue by SergoMArtys** [Ultimaker/Cura#14457]
### Application Version

5.2.2

### Platform

Windows 8.1

### Printer

flyingbear ghost 5

### Reproduction steps

Good afternoon. Help with UltiMaker Cura 5.2.2
The program was downloaded from the official site. The program has been installed. When starting the program, it immediately gives an error.
I am attaching a photo of the error.
operating system Windows 8.1 64-bit
![Снимок экрана (24)](https://user-images.githubusercontent.com/124299144/216433857-fb461fa8-4fda-44e1-879a-afe79b9a655b.png)

### Actual results

When starting the program, it immediately gives an error.

### Expected results

program launch

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Снимок экрана (24)](https://user-images.githubusercontent.com/124299144/216434115-c8f1b7e8-05b0-452f-ab2c-f1e2292b8d9f.png)

**Comment by fieldOfView** [comment]
What does it say after "DLL load failed while importing QTWidgets? Can you translate that back to english?

**Comment by kliment** [comment]
It's the equivalent of "ImportError: DLL load failed: The specified module could not be found"

**Comment by fieldOfView** [comment]
Thanks @kliment. 

I am afraid Ultimaker Cura no longer supports Windows 8.1:
https://support.makerbot.com/s/article/1667337917781
The biggest reason for that is the the Qt GUI framework Cura uses no longer supports Windows 8.1:
https://doc.qt.io/qt-6/windows.html

**Comment by fieldOfView** [comment]
I'm closing this issue, because though it is regrettable that Cura no longer works on Windows 8.1, it is (apparently) a known issue and a deliberate choice.
