### ISSUE TITLE
zoom roll mouse

### ISSUE THREAD

**Issue by Ipermax2000** [Ultimaker/Cura#1447]
WHEN you act on the mouse wheel to zoom Subject, The 3d space becomes smaller and not ê can maximize it.

**Comment by nallath** [comment]
I don't quite understand what you mean.

**Comment by Ghostkeeper** [comment]
Rolling the mouse wheel down should zoom back out, making the viewport larger again. Isn't that happening for you?

**Comment by BagelOrb** [comment]
Unclear
