### ISSUE TITLE
5.3.-alpha doesn't slice file properly.

### ISSUE THREAD

**Issue by N6REJ** [Ultimaker/Cura#14476]
### Application Version

5.3.0

### Platform

win 10x64 pro

### Printer

Aquila S2

### Reproduction steps

Load file
examine to see that holes and other parts are showing
slice
observe most parts are now missing.

### Actual results

doesn't include many parts

### Expected results

slices all parts properly.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Holder SocketS.zip](https://github.com/Ultimaker/Cura/files/10608503/Holder.SocketS.zip)

Works fine in cura 4 and 5.2.1

"Finished" print from 5.3.0.-alpha
![327339403_930131571493290_5712381925207785678_n](https://user-images.githubusercontent.com/1850089/216765094-b4c27e39-2a0c-499e-b679-83247b05c1c3.jpg)
walls are stringly and not fused.
I've done days and days worth of printing from 5.3.0-alpha without issues so its not a config issue as far as I know.

**Comment by GregValiant** [comment]
Thanks for the report.
Load the model and use the "File | Save Project" command to create a 3mf project file.  Zip the file together with one of those "bad" gcode files.  Post the zip folder here.

Have you tried printing one of the older gcodes that you are confident print correctly?
When I load the STL the slice looks good and I'm confident it would print properly on my Ender.

Looking at the image you posted - the skirt looks very odd.  It should not have that scalloped inside edge.  That has me thinking you may have developed a problem within the printer.
Additionally, the image doesn't really look like the STL you posted.  We always need to talk "apples and apples" here.
![image](https://user-images.githubusercontent.com/64202104/216771280-55705874-599e-4d26-8769-7aeee59ce515.png)

**Comment by N6REJ** [comment]
The image I posted is exactly my point.  It doesn't create all the g-code needed to do it properly.
This what the finished product looks like when sliced with 5.2.1
![327302544_1178602063021313_4103319380501842749_n](https://user-images.githubusercontent.com/1850089/216793234-50f7a08b-446f-4cd7-8d24-04db2f7cedd7.jpg)

This is as shown in 5.2.1-alpha
![image](https://user-images.githubusercontent.com/1850089/216793253-f513fa64-4a39-49c5-a857-7b140246fbec.png)
[HolderSocketS.zip](https://github.com/Ultimaker/Cura/files/10609848/HolderSocketS.zip)
[HolderSocketS_2.zip](https://github.com/Ultimaker/Cura/files/10609849/HolderSocketS_2.zip)
Had to use 2 zips cause its too big for git otherwise.

**Comment by GregValiant** [comment]
Turn "Spiralize" off and make sure that "remove all holes" gets turned off as well.  They are linked in 5.2.1.

**Comment by N6REJ** [comment]
spiralize did it... ty.
