### ISSUE TITLE
Setting visibility

### ISSUE THREAD

**Issue by shoxzz** [Ultimaker/Cura#14482]
### Application Version

5.2.2

### Platform

w10

### Printer

cr10s

### Reproduction steps

checked setting that i want to show like accelleration etc but they dont show up in the setting task
![image](https://user-images.githubusercontent.com/74992044/216810320-c9a12ba5-7a4b-44d4-aefc-53c5a6cec870.png)

### Actual results

setting dont show 

### Expected results

setting should appear

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by GregValiant** [comment]
Thanks for the report.
Many settings are dependent on other settings.  If you want to see "Print Acceleration" you need to check "Enable Acceleration Control".  That is normal behavior.  If a "parent" setting is disabled then it's "child" settings are removed as there is no need for them.
Is that what you meant?
