### ISSUE TITLE
Add a profile for the Ender-3 V2 Neo

### ISSUE THREAD

**Issue by MrBrain295** [Ultimaker/Cura#14487]
### Is your feature request related to a problem?

Kind of, I have an [Ender-3 V2 Neo](https://www.creality.com/products/ender-3-v2-neo-3d-printer) and there is no official profile for it I followed a tutorial for a profile and it has worked fine but it would be nice to have one built in.

### Describe the solution you'd like

A profile for the Ender-3 V2 Neo.

### Describe alternatives you've considered

Making my own custom profile. It has worked but it would be easier to start out with the printer if Cura had a profile for it.

### Affected users and/or printers

Ender-3 V2 Neo users.

### Additional information & file uploads

None.

**Comment by MrBrain295** [comment]
I didn't see this when I made the issue but this is fixed by #13580.

**Comment by GregValiant** [comment]
It may or may not make it into the next release of Cura.  You can keep an eye on that thread and see when the definition is added.  You could then copy the file and paste it into the definitions folder on your computer.
Can I close this then? (it does seem to be getting attention in #13580 ).

**Comment by MrBrain295** [comment]
Yeah
