### ISSUE TITLE
Rates of Process

### ISSUE THREAD

**Issue by Ipermax2000** [Ultimaker/Cura#1448]
in cura to right,  when mold usb does not flow the printing time and the remaining time

**Comment by Ghostkeeper** [comment]
If I understood you correctly, this issue is about showing the printed time and remaining time in the GUI while printing via USB and wifi.

**Comment by Ipermax2000** [comment]
Yes good. do not work


----- Messaggio originale -----
Da: "Ghostkeeper" <notifications@github.com>
Inviato: ‎23/‎02/‎2017 15:18
A: "Ultimaker/Cura" <Cura@noreply.github.com>
Cc: "Ipermax2000" <massimiliano.conti.68@gmail.com>; "Author" <author@noreply.github.com>
Oggetto: Re: [Ultimaker/Cura] Rates of Process (#1448)

If I understood you correctly, this issue is about showing the printed time and remaining time in the GUI while printing via USB and wifi.

**Comment by Ghostkeeper** [comment]
Our product manager just closed this for being inactive for too long.
