### ISSUE TITLE
Enum settings values not loaded properly from config

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#145]
Steps to reproduce:
1) in home/.config/cura/cura.cfg 
have a line that says:
platform_adhesion = Brim
2) open Cura
3) change platform adhesion type to Raft
4) close Cura

Expected result:
1) when opening Cura, platform adhesion type is set to Brim
2) the config file now contains
platform_adhesion = Raft

Actual result:
1) when opening Cura, platform adhesion type is set to None
2) the config file now contains
platform_adhesion = Brim

Note that before after closing Cura the config file contains
raft_airgap_all = 0.0
raft_surface_linewidth = 0.4
etc.

**Comment by nallath** [comment]
We've reimplemented settings & saving it, so closing this.
