### ISSUE TITLE
"Lift head" causes head to move outside build envelope

### ISSUE THREAD

**Issue by berthrsd** [Ultimaker/Cura#1450]
When using "Lift head" in 2.4.0 beta, the toolhead can move outside the build envelope. I found this out the hard way... :)

![skarmklipp](https://cloud.githubusercontent.com/assets/25897043/23117938/6204f21a-f752-11e6-84df-91f97339cb21.PNG)

[Desktop.zip](https://github.com/Ultimaker/Cura/files/786946/Desktop.zip)

**Comment by nallath** [comment]
I've tagged the people that did most of the work on the disallowed areas.

**Comment by BagelOrb** [comment]
Ah yes. I guess someone finally found out :$

We could move toward the middle of the build plate, that shouldn't be too hard..

Note that this problem i not so much to do with disallowed areas.

Iĺl make a ticket in JIRA for it.

**Comment by BagelOrb** [comment]
fixed
