### ISSUE TITLE
UNKNOW ERROR SLICING

### ISSUE THREAD

**Issue by Kayserdeath** [Ultimaker/Cura#14519]
### Application Version

5.2.1

### Platform

WINDOWS 10

### Printer

ARTILLERY GENIUS

### Reproduction steps

1. CARGAR MODELO
2. AJUSTAR TAMAÑO A 55% (X,Y &Z)
3. GIRAR 45° EL MODELO SOBRE LA PLACA
4. CONFIGURAR PARÁMETROS DE SLICING
5. SLICE

### Actual results

SLICING ERROR, CERRAR PROGRAMA

### Expected results

SLICING 100% DONE

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10690078/cura.log)
![Captura de pantalla 2023-02-08 183102](https://user-images.githubusercontent.com/124837256/217655930-9f662b6e-55f7-4b07-b87a-2d48cc1b62ee.png)
[AG_MPP_Articulated_vaporeon.zip](https://github.com/Ultimaker/Cura/files/10690090/AG_MPP_Articulated_vaporeon.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
That model has a large error in the interior.  After repairing the model in Mesh Mixer it sliced fine.  MS 3D Builder was also able to repair the model but that version wouldn't slice until I moved it around on the build plate.  That part is a known Cura bug that has been addressed and should be fixed it 5.3 stable.
![image](https://user-images.githubusercontent.com/64202104/217677131-80e5e7cd-b456-402c-92e5-fb265961c166.png)

So the model has problems but is repairable and will slice.  If it is a Cura bug it's one that has been squashed.
I'll mark this as a duplicate and go ahead and close it.  I hope you understand.
