### ISSUE TITLE
Cura 2.3.1 does not recognize connected Ultimaker Original+ 3D Printer

### ISSUE THREAD

**Issue by kirschnw** [Ultimaker/Cura#1451]
When have the printer connected to my PC and start Cura 2.3.1 the printer status remains "not connected". It makes no difference, if the printer was recently connected before Cura was started or stayed connected over a restart of the system.
Looking at the Windows device list shows, that the printer is connected properly.

When I disconnect the printer and reconnect it while Cura is running, the printer will be recognozed properly. I cannot find a method to make Cura find the printer except the above described workaround

**Comment by kirschnw** [comment]
The parameters of my system:
CURA version: 2.3.1
Win10 professional
USB 2.0 port

**Comment by Ghostkeeper** [comment]
Does this happen in Cura 2.4 as well?

**Comment by BagelOrb** [comment]
outdated

**Comment by BagelOrb** [comment]
Try Cura 2.6
