### ISSUE TITLE
Top/Bottom -> "Line Directions" function doesn't work V5.5.2 

### ISSUE THREAD

**Issue by SRAsolution** [Ultimaker/Cura#14534]
### Application Version

5.5.2 

### Platform

Window 11

### Printer

Own build

### Reproduction steps

1, Import STL
2, rotation 90° (for biggest surface touch plate)
3, Select default profile then "slice"
4, view 1st layer (check line orientation)
5, Change "Top/Bottom Line Direction" value "90" or "60" or "45" or [90] or [60]......
6. press slice and check 1st layer
7. Issue: no change on the layer orientation

### Actual results

New setting has no impact on the build

### Expected results

The lines orientations should change based on the input 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/105916690/218085355-63f7a2d5-10a6-482e-a609-681ccca0a38b.png)

**Comment by SRAsolution** [comment]
Dear Greg,

I attached the files and took the photos.
Note that the 1st appear was on v5.2.1 and I update to 5.2.2 to solve the
problem, but it didn't solve the issue
[image: 0.png]
[image: 90.png]
Kind regards/Üdvötlettel,

*Renato* *Sanchez*
Mobile: +36 20 201 6816
E-mail: ***@***.***

**Comment by GregValiant** [comment]
@SRAsolution attachments here don't work via e-mail.  If you could please direct post it here on the website that would work.
(FYI my screenshots were with 5.2.1.)

**Comment by SRAsolution** [comment]
![0](https://user-images.githubusercontent.com/105916690/218247973-934373cd-473a-44ff-a099-1886c2047446.png)
![90](https://user-images.githubusercontent.com/105916690/218247974-b3b32cea-4079-43df-a0fe-a7c783040ca4.png)

Re-attached

Since yesterdays I have shut-down my computer and restarted. Now I can't reproduce the issue. (look like it work)
note: before restarting the computer I try to re-lunch  the software, but it didn't solve the issue
