### ISSUE TITLE
A bunch of issues related to adhesion and 'allowed/maximum' Print Size 

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1453]
There are several issues I observe when slicing objects close to the max size of the build area. 

I am not sure what the underlying issue connecting all this is.

So I'll just sum up the observations with no hypothesis and see what you guys think. 

## The system set up
(Without which the observations make no sense.)
- 160x150x145
- Cura 2.4 Beta on Mac, El Capitan
- Custom Marlin based printer (IMADE3D JellyBOX)
![image](https://cloud.githubusercontent.com/assets/16858474/23131309/cc3bd4a0-f789-11e6-8ff2-cc32fa1157b0.png)

## Interaction between X and Y
- x=150, y=150, slices fine
- X=160, y=100, slices fine
- X=160, y=150, **error**
- same pattern works in the other direction:
- y=160, x=100, slices fine
- y=160, x=150, **error**
![image](https://cloud.githubusercontent.com/assets/16858474/23131361/020c244a-f78a-11e6-91c2-5bd683c620b7.png)
![image](https://cloud.githubusercontent.com/assets/16858474/23131369/08f6240e-f78a-11e6-8cb4-7aa6bb520237.png)

## Can't reach 'full size' no matter what
- Adhesion is set to 'none'
- maximum sizes in x and y are 12mm and 9mm smaller than the printer print area
![image](https://cloud.githubusercontent.com/assets/16858474/23131979/6193f788-f78c-11e6-8d3a-01b1a542568e.png)

## Print area reduced even if adhesion not enabled
- adhesion not enabled
- yet, as clear from the dark grey border, there is some ares taken away from maximum XY size
- when we enable adhesion, it adds a 2nd grey border
- it therefore seems the first one is _not_ for adhesion... so what is it? 
![image](https://cloud.githubusercontent.com/assets/16858474/23132169/057ab97c-f78d-11e6-896c-970ecc97ba3f.png)
![image](https://cloud.githubusercontent.com/assets/16858474/23132149/f8416b3e-f78c-11e6-99fa-98d071cac0b3.png)

**Comment by nallath** [comment]
We add a very small area to the shadow an object "drops" to prevent rounding errors in the model. If I remember correctly it's a 0.5 mm offset, which can contribute to a few of the issues you observe. 

Adhesion is not the only setting that has influence on the build size. A number of travel & avoid settings also influence it (infill_wipe_dist, travel_avoid_distance, travel_avoid_other_parts)

**Comment by awhiemstra** [comment]
Note also that the recommended mode "build plate adhesion" toggle toggles between brim and skirt, not between brim and none.

**Comment by filipgoc** [comment]
Not all sure the tiny buffer you mention (0.5mm) would result in 
> x and y are 12mm and 9mm smaller than the printer print area

I'll explore the infill_wipe_dist, travel_avoid_distance, travel_avoid_other_parts and see what happens.

**Comment by Ghostkeeper** [comment]
The full list of settings that influence the disallowed areas are here: https://github.com/Ultimaker/Cura/blob/b0c8a4df7a995520665e701f2f829a69ebbfba14/cura/BuildVolume.py#L891

The `_extruder_settings` only affect which extruders are used (for multi-extrusion machines) and the `_extra_z_settings` only affect the height of the build volume.

To use the full build volume, you typically need to disable platform adhesion and disable Avoid Objects While Printing. Other things that affect the build volume (Draft Shield, Ooze Shield and Infill Wipe Distance) are typically already disabled by default, unless you're using some machine definition I don't typically test with.

**Comment by filipgoc** [comment]
thanks for this @Ghostkeeper . 
i'll report back after another round of test :-)

**Comment by ianpaschal** [comment]
This came up again in [#3365](https://github.com/Ultimaker/Cura/issues/3365) including some discussion of possible fixes/improvements, so I'm closing this. Discussion can be continued in the up-to-date thread.
