### ISSUE TITLE
when adhesion set to 'none', it is automatically 'enabled' in recommended tab

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1454]
This is either confusing UI, or cofusing functionality. Not sure which one.
- i'd guess that when adhesion is set to 'none' under custom tab, it should be equivalent to 'not-enabling' adhesion under recommended tab. 

## Instead, this is what happens:

action  | reaction  |
--|---
1: select adhesion:none in custom tab  | ahesion: _enabled automatically in recommended tab (even if disabled before; weird)_
2: de-enable adhesion in recommended tab  | adhesion under custom tab set to 'skirt' (even though is was 'none')

**Comment by nallath** [comment]
It's such a small issue that I fixed it right away. It was a visualisation issue. 

Originally we didn't have a "None" option for platform adhesion and only "skirt" was seen as not having platform adhesion. When we added the None option, we failed to also include the None for the recommended view.
