### ISSUE TITLE
won't slice

### ISSUE THREAD

**Issue by wftiny555** [Ultimaker/Cura#14545]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Longer LK5 Pro

### Reproduction steps

I set up what I needed to slice, starts, then after a couple min it pops up not able to slice. Slicing failed is what it says

### Actual results

nothing, it won't slice

### Expected results

it should slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'm not sure how to get these files....I'm not that good with computers

**Comment by GregValiant** [comment]
Thanks for the report.
Without the documentation files there is no way to investigate this.  The instructions are on the first page that you filled out to make this report.
Use the "File | Save Project" command to save your model and settings.  You will need to zip the 3mf file (in Windows right click on the file in Explorer and use the "Send To... | Compressed (Zipped) Folder" command).  Post the zip folder here.
