### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by muthafnmutt** [Ultimaker/Cura#14544]
### Application Version

5.2.2

### Platform

window11

### Printer

ender3s1pro

### Reproduction steps

uninstall and reinstall 

### Actual results

same

### Expected results

not to crash

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

what and how do i send u reports when it is crashing

**Comment by MariMakes** [comment]
Hey @muthafnmutt,

Welcome to the Ultimaker Cura Github 🚀 
Your crash sounds super frustrating 😞 

I have a couple of questions to narrow it down.
	1. Do you have multiple monitors? Does Cura start if you disable one of the monitors?
	2. Do you have two monitors placed above each other? Can you try this workaround from the community? https://community.ultimaker.com/topic/42633-cura-522-stopped-working/#comment-318105
	3. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
	4. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
	5. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665
	6. If your problem is related to scaling, can you try this workaround from the community? https://community.ultimaker.com/topic/41458-ultimaker-cura-510-window-scaling-problem/#comment-311838
