### ISSUE TITLE
ERROR ON CUTTING MESH

### ISSUE THREAD

**Issue by DM9628** [Ultimaker/Cura#14546]
### Application Version

5.3.0

### Platform

WIN 11

### Printer

E32

### Reproduction steps

![image](https://user-images.githubusercontent.com/125153770/218276858-66f46be0-ab12-45ba-aceb-910f58303b32.png)
 Im trying to cut a model using a cutting mesh, but it does not slice. 
I've done that before with other models.

### Actual results

Nothing

### Expected results

Sliced model with a hole in it

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10714546/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm unable to duplicate this problem.  A project file would be good.

Here you can see how I've set up the Cutting Mesh cylinder.  When you set yours up like that does it work?
![image](https://user-images.githubusercontent.com/64202104/218530795-7d140451-9df5-42de-ac3e-119e69554bc5.png)
