### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by KITZKRIEG** [Ultimaker/Cura#14552]
### Application Version

5.3.0 alpha xmas

### Platform

Windows 10

### Printer

Anycubic Kobra Plus

### Reproduction steps

tried to slice

### Actual results

it fails

### Expected results

should be sliced

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![cure xmas](https://user-images.githubusercontent.com/125224353/218343314-7e1cf93a-2daf-4b12-b10c-00be55e45afa.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura.log file there isn't much we can do.
Load the model and use the "File } Save Project" command to create a 3mf file.  Use the "Help | Show Configuration Folder" command to find the Cura.log file.
Put the files into a zip folder and post the zip folder here.
