### ISSUE TITLE
Project saving issues (multiplying extensions, no keyboard support)

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1455]
Mac El Capitan, Cura 2.4 Beta

## no keyboard
When saving a project (summary showing), pressing `enter` simply closes the window instead of confirming the `save` button. One has to either use the mouse (oh the pain) or press tab a bunch of times and then use the spacebar. 
![image](https://cloud.githubusercontent.com/assets/16858474/23133716/5b1184b0-f792-11e6-80ff-824883c3c182.png)

## .curaproject.3fm not generated properly; cyclical error
Even though the (automatically generated!) filename `3Dbenchy.curaproject.3mf` looks ok, cura screams:
![image](https://cloud.githubusercontent.com/assets/16858474/23133856/e5e2863e-f792-11e6-97eb-eae9488c0fb9.png)

Consequently, if I select `Use .curaproject.3mf` file is saved as `3DBenchy.curaproject.curaproject.3mf`

Moreover, if I then go and save the project again (save as), the automatically generated filename is `3DBenchy.curaproject.3mf.curaproject.3mf` and cura still screams
![image](https://cloud.githubusercontent.com/assets/16858474/23133990/6a04ec18-f793-11e6-92c7-414ec8e6cd90.png)

Weird?

**Comment by nallath** [comment]
It's not Cura that screams, it's OSX that screams. It works fine on Linux & Windows. Unfortunately it's one of those issues that is out of our hands :(

**Comment by filipgoc** [comment]
Ha. That's good to know. 

In that case I post here: 

## Mac OS : Saving .curaproject.3mf Workaround/ Deal with It
- As long as you're saving a file with no visible extension, it will be A-OK. 
- When you're saving a project, the filename is automatically highlighted, including the extension. 
- Therefore, if you simply rename the file by starting to type with no mouse input, and then save the project, all will be well. And it's not that much work. 

![image](https://cloud.githubusercontent.com/assets/16858474/23156664/39c44e10-f818-11e6-9c1c-9f64be259977.png)
![image](https://cloud.githubusercontent.com/assets/16858474/23156673/40f43538-f818-11e6-99f7-a39c9676866a.png)

**Comment by filipgoc** [comment]
@nallath and the issue of not saving on 'enter' ?
Is that out of hands as well?

**Comment by nallath** [comment]
Uh, I'm not sure about that one.

**Comment by DDDirk** [comment]
More in general, Cura could be a lot more keyboard-friendly. That would not only speed up work, but also help prevent RSI.

**Comment by filipgoc** [comment]
Oh I dare not even to mention that @DDDirk 
I cry salty tears every time I don't use a keyboard shortcut!

I have defined many shortcuts myself (export to file, open project, save project... ), but not all can be easily defined. 

And even the ones I have (mac has a native way to do it), but honestly even these shortcuts don't work every time, they are finicky in cura (even though for other programs I use this approach with no issues). 

Another thread on shortcuts?!
I am happy to make a the first draft of the desired ones.

**Comment by nallath** [comment]
Adding short cuts should not be that hard for most of them. A number of actions (save file, etc) we use default shortcuts.

**Comment by fieldOfView** [comment]
There's a JIRA issue for improved keyboard navigation (and another one for improved touch support btw), but I am guessing that has been postponed to kingdom come.

**Comment by filipgoc** [comment]
I've never implemented keyboard shortcuts into a project from developer's side, but if there's some helper type work (give me a schema and I'll can prepare the bindings map for example), happy to help.

**Comment by nallath** [comment]
We use the QT shortcuts. For the moment being it means that the key sequences defined in http://doc.qt.io/qt-5/qkeysequence.html#StandardKey-enum would work. It's also possible to add your own, but thats a bit more work.

**Comment by Ghostkeeper** [comment]
I think this particular dialogue is not a problem of introducing keyboard shortcuts, but a problem of setting the focus on the correct button initially.

**Comment by DDDirk** [comment]
Related is using the keyboard for navigation through the menus. The names have underscores for Alt-key-combinations (visible without pressing Alt first, which I like). But (in Cura 2.4) these don't work for View and Settings. I can acces them through Alt-E (edit) and then the right arrow. But when I do that 3 times I should get into the printer submenu, which doesn't happen (although it becomes visible, but not selected (highlighted)). If I use the right arrow a fourth time, the menus disappear. This also happens when the submenu is visible, eg File > Open recent. Or nothing happens, as with the submenus under Extensions (meaning I can't move on to Preferences that way).

It really disrupts my workflow if things don't work as expected. I have to momentarily think about something that should be automatic and then I have to grab the mouse, which also slows me down. And it's bad for my RSI.

**Comment by jackha** [comment]
Pressing enter will now open the file dialog to save: c036912
