### ISSUE TITLE
Autosave Current Workspace as Current-Project on Cura Quit (Feature Idea)

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1456]
Now that Cura supports Projects, I propose that when Cura quits, the “workspace”* get automatically saved as a Current-Project in the user’s folder, and gets loaded next time Cura starts instead of “blank slate.”

- By workspace I mean models with their transformations and slicing settings.
- May be beneficial to have this as a turn off/on option in preferences.

**Comment by nallath** [comment]
Right now, workspace saving can be a bit on the expensive side. Especially if you have a build plate filled with models, it can take ~10 seconds to save it. I do like the idea, but im not so sure about the user impact.

**Comment by Ghostkeeper** [comment]
Our product manager just closed this for being inactive for 3 months.

**Comment by nickthetait** [comment]
Has any work been done to the performance of saving a workspace? This may be less of a hurdle nowadays...

**Comment by awhiemstra** [comment]
Some work has been done, we introduced https://github.com/ultimaker/libSavitar to speed up the 3MF reading/writing. Parts of workspace are still being done in Python though, so there are still performance bottlenecks. We might be able to do project save on window close though, but we definitely would not want to do project auto saves while the user is using the application.

**Comment by nallath** [comment]
The ~10 sec is the current time for larger workspaces. Autosaving is not that good of an idea at the moment (unless we put a whole lot of work in it).
