### ISSUE TITLE
Supprt is printed in the air

### ISSUE THREAD

**Issue by anno0** [Ultimaker/Cura#14569]
### Application Version

5.2.2

### Platform

Ubuntu 20.04

### Printer

Anycubic Mega X

### Reproduction steps

1. Insert stl file https://www.thingiverse.com/thing:5620612
2. Activate normal support and layer height 0.16 mm

### Actual results

Support is printed in the air. 

### Expected results

A support that there is a working support without printed parts in the air.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![support](https://user-images.githubusercontent.com/2607705/219058074-7715563c-196c-4c32-a885-04bfc2e52ee5.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file it's impossible to tell how you had it set up to slice.
Threads are tough.  The "XY" distance changes in a helix and so the support structure has to chase it around the centerline of the thread.  There are 73 support settings and you can find a combination that will work.
In the screenshot below I've used a cylindrical support blocker to keep support from growing for the threads themselves.  That allows it go grow only to support the underside of the hex feature.
Part of the problem may be your Support Density setting.  That model may need the internal walls to grown correctly.
I'm inclined to remove the bug label as this seems to be a setting issue.  I'll leave it on for now so you can respond here.![image](https://user-images.githubusercontent.com/64202104/219165091-72cce5b4-25b9-425c-9d30-44cefcadc54a.png)
