### ISSUE TITLE
Camera not working properly

### ISSUE THREAD

**Issue by action3dprint** [Ultimaker/Cura#14560]
### Application Version

5.2.1

### Platform

Windows 10 and 11

### Printer

Ultimaker 3

### Reproduction steps

Note: the camera works fine on my Android phone app but not on Windows 10 or 11
Click on the camera icon

### Actual results

In Windows the camera is extremely slow and once up only shows a single snapshot

### Expected results

Full video as I get on my phone

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Used to work fine.

**Comment by MariMakes** [comment]
Hey @action3dprint,

Welcome to the Ultimaker Cura Github 🚀 
This is not really a Cura issue unless you are referring to the monitor page in Cura. 

If you have trouble seeing the camera feed from the monitor you can check the support page. 
https://support.makerbot.com/s/article/1667412693301

I'll close the issue, Good luck! 👍
