### ISSUE TITLE
No minimize, expand or close buttons. Also cannot move window 

### ISSUE THREAD

**Issue by d-portero** [Ultimaker/Cura#14575]
### Application Version

5.2.2

### Platform

Windows 10 

### Printer

Ultimaker S5

### Reproduction steps

Opened cura and cannot maniuplate the window. 

have uninstalled and reinstalled the program. 

### Actual results

No buttons

### Expected results

Have buttons and be able to move the window 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/50592002/219239252-7ee2a2ac-ddfe-42fb-9e9d-f3fb2a574cf4.png)

**Comment by MariMakes** [comment]
Hey @d-portero,

Thanks for your report 👍
Sorry, to hear reinstall our software😞 

I've never seen this before. 😮 
![image](https://user-images.githubusercontent.com/40423138/220312371-f7f66403-495a-46a6-bb29-6e20f84cce4b.png)

It looks like the necessary buttons are just hidden out of view. 
Like they disappear from the top of the screen.

You can use the following buttons to move your window:
Windows Key + Arrow Up
Windows Key + Arrow Right/Left

If you use these hotkeys, do your buttons come back?
