### ISSUE TITLE
UI Post Processing Extension Window too Big (Bug?) on Mac

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#1457]
Incorrect sizing of Modify G-code post processing extension. 
- mac el capitan cura 2.4 beta
- The presumed `OK` button is out of display and invisible. 
- There is no visual way to interact, or close the window. One just has to try “enter” and hope for the best. 
![image](https://cloud.githubusercontent.com/assets/16858474/23136426/fa9747ea-f79c-11e6-8f06-77927acb7e15.png)

**Comment by fieldOfView** [comment]
Hmm, weird. Is this just with the post processing window? Or are windows such as the About dialog and Preference window also affected?

**Comment by filipgoc** [comment]
-- | --
-- | --
preferences    | ok
About dialog   | oversized
changelog       | ok

**Comment by nallath** [comment]
Ugh. Stupid DPI densitity issues again. I thought we squashed all of them :(

**Comment by nallath** [comment]
This should be fixed by the pull request!
