### ISSUE TITLE
No slicing with tree supports

### ISSUE THREAD

**Issue by YATTAMilano** [Ultimaker/Cura#14578]
### Application Version

5.2.2

### Platform

Win10 home

### Printer

Ender5

### Reproduction steps

slicing with Tree support. 

### Actual results

a pop-up window appeared reporting a bug

### Expected results

slicing with supports

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura bug report](https://user-images.githubusercontent.com/20341483/219319134-e2b0b0f9-bf38-4a14-9dd9-201863ec1899.jpg)

**Comment by Asterchades** [comment]
Without a project file, or at least the STL in question, little if any diagnostics can be done.

Note that files cannot be attached via the e-mail response system. They must be uploaded through the website. Changing the file extension of the project from .3MF to .ZIP will allow it to be uploaded.
