### ISSUE TITLE
The slicer will not slice a specific model

### ISSUE THREAD

**Issue by J-BAD** [Ultimaker/Cura#14573]
### Application Version

5.2.1

### Platform

Windows 10 Pro

### Printer

Ultimaker 2+

### Reproduction steps

Slicing an STL model using custom supports.

### Actual results

The supports look like they are placed well. The slicer goes through the motions and then gives the message 
Slicer failed with unexpected error.

### Expected results

It should give me a useable g-code to use in the printer.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[uploads_files_3724018_Gokuss4_Corte3_SubTool1_(4).zip](https://github.com/Ultimaker/Cura/files/10747150/uploads_files_3724018_Gokuss4_Corte3_SubTool1_.4.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Cura has a persistent bug that can keep good models from slicing when they are in certain orientations and at the build plate mid-point.  I rotated and moved the model and it sliced.
I'll mark this as a duplicate slicing error.  I'll close it though as the team is currently working on this bug and they have lots of examples to work with.  I hope you understand.
Here it is sliced in 5.2.1
![image](https://user-images.githubusercontent.com/64202104/219147217-a682160b-a317-4d29-9db7-9c5dfbb27ed4.png)
