### ISSUE TITLE
Special Modes does not show Print Sequence option 

### ISSUE THREAD

**Issue by servant74** [Ultimaker/Cura#14587]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Ultiaker 3

### Reproduction steps

1. I went to change the visible options on the Special Options submenu, and selected Print Sequence
2. Opton does not appear back under various options under Special Options (like ArcWelder did nicely)
3. Does not allow to select 'Print Sequential' due to lack of Print Sequence dropdown.

### Actual results

Cannot print multiple objects in sequence.

### Expected results

The Print Sequence drop down is not abailable in the Special Options section after being selected in the appropriate sub menu.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No additional files are required.

**Comment by GregValiant** [comment]
This is from "fdmprinter.def.json":
"print_sequence":
                {
                    "label": "Print Sequence",
                    "description": "Whether to print all models one layer at a time or to wait for one model to finish, before moving on to the next. One at a time mode is possible if **a) only one extruder is enabled** and b) all models are separated in such a way that the whole print head can move in between and all models are lower than the distance between the nozzle and the X/Y axes.",
                    "type": "enum",
                    "options":
                    {
                        "all_at_once": "All at Once",
                        "one_at_a_time": "One at a Time"
                    },
                    "default_value": "all_at_once",
                    **"enabled": "extruders_enabled_count == 1",**
So if you have a multi-extruder printer Print Sequence isn't available unless you disable all extruders except one.
Let us know if that is the situation.  I'm thinking that this is "expected behavior".

**Comment by servant74** [comment]
Thanks...
