### ISSUE TITLE
Slicing Failed - Unexpected Error

### ISSUE THREAD

**Issue by stuart264** [Ultimaker/Cura#14586]
### Application Version

5.2.2

### Platform

Linux Mint

### Printer

Sunlu S9+

### Reproduction steps

Loaded file as normal, ran auto orientation, slicing failed about 1/2 way through.

### Actual results

Error repeats, no way round it.around

### Expected results

[error.3mf_FILES.zip](https://github.com/Ultimaker/Cura/files/10759702/error.3mf_FILES.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[error.3mf_FILES.zip](https://github.com/Ultimaker/Cura/files/10759705/error.3mf_FILES.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm not sure what type of files you uploaded by I can't do anything with them.
Use the "File | Save Project" command, add the 3mf to a zip folder, and post the zip folder here.
