### ISSUE TITLE
Ultimaker Cura 5.2.2 fails to slice .3MF object

### ISSUE THREAD

**Issue by agtrandicosta24** [Ultimaker/Cura#14596]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

AnyCubic Mega Zero 2.0

### Reproduction steps

Launch Ultimaker Cura.

Load file from local drive.

Click slice.

### Actual results

Error Message populate after slicer begins.

![image](https://user-images.githubusercontent.com/35247848/219812840-abe6324c-c2c7-4c52-bc97-af39d9f383d6.png)

### Expected results

File should have sliced and allowed for save to thumb drive.

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

https://drive.google.com/file/d/1vCSnzCGL4w9TujCd52Xgeacp2H1OBAuV/view?usp=share_link
[cura.log](https://github.com/Ultimaker/Cura/files/10772222/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I don't have permission to download that file and there isn't much I can do without it.

**Comment by GregValiant** [comment]
Ta-Daaa
![image](https://user-images.githubusercontent.com/64202104/219984160-495fd9d6-ace7-456c-b2e6-c0d0fada8ef2.png)

I didn't find any errors in the model.  After moving it and rotating it sliced.
This is a well known bug in Cura 5.x.  It's being worked on.  I'll mark this as a duplicate and close it as the Cura Team has a lot of examples of this bug.  I hope you understand.
