### ISSUE TITLE
Model failed to slice at dyamic quality

### ISSUE THREAD

**Issue by DrBarney** [Ultimaker/Cura#14595]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Creality CR-10S

### Reproduction steps

Attempted to slice attached file at scale 50mm x 50mm x 50.4332 using resolution 0.16mm.
[impossible_box.zip](https://github.com/Ultimaker/Cura/files/10771892/impossible_box.zip)

### Actual results

Seems to be resolution dependent as model will slice at standard quality.

### Expected results

Model should have generated gcode.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

No additional comments.

**Comment by GregValiant** [comment]
Thanks for the report.
A project file would be preferred as it would have your Cura settings and printer as well as the model.

I didn't have any trouble slicing this.  You can try moving it and rotating it on the Cura build plate.  There is a bug that can keep models from slicing when they are in the center of the build surface.
Let us know if that works for you.  I'll mark this as a duplicate and close this as the Cura team is working on this bug and they have a lot of examples to look at.  If you think that is premature let us know.

I thought it looked a lot better with a 0.3 nozzle.
![image](https://user-images.githubusercontent.com/64202104/219826424-73f04023-1563-422b-a2e3-7883a2db1577.png)
