### ISSUE TITLE
file wont slice

### ISSUE THREAD

**Issue by grdianangel** [Ultimaker/Cura#14603]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Mega X

### Reproduction steps

tried to slice an stl file and it is saying slicing failed

### Actual results

wont slice

### Expected results

file should slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

stl file says it is not a supported file to send. not sure what to do to send file that wont work

**Comment by GregValiant** [comment]
You have to Zip files and post the zip folder here (Github rules).  The instructions are on the first page you filled out here.
Without a 3mf Project File and the Cura.log file there really can't be an investigation.
