### ISSUE TITLE
Issue with Multi-Filament Extrusion purge tower.

### ISSUE THREAD

**Issue by Tobiah10** [Ultimaker/Cura#14606]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Custom Ender 3 

### Reproduction steps

I set up a custom printer with 2 separate nozzles for multi-filament printing, and enabled and set up the purge tower.

### Actual results

the first layer of the purge tower is laid down nicely but every other layer the Inner purge ring for the secondary nozzle, set for support material, does not get printed. this leads to a messy and often failure causing rings of purged filament. this happens on every single multi-filament print done. the outside rings, purged from the primary nozzle, happen every single layer with no issue, except for when the inside rings get dragged over them due to a non-existent layer beneath them.

### Expected results

a purge tower with messy inside rings for a secondary nozzle purge and normal outside rings for the primary nozzle.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

if anyone has any tips on how to fix this, please let me know.

**Comment by MariMakes** [comment]
Hey @Tobiah10,

Welcome to the Ultimaker Cura Github 🚀 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

The prime tower is supposed to only prime the second extruder if it's used that layer. For Ultimaker Dual Extrusion printers that is usually enough, and reduces the material waste. I've seen more reports like this, some people have a workaround where they print a tiny Cube that is present in all the layers. Something like this:
![image](https://user-images.githubusercontent.com/40423138/220315509-fbf9517f-b3bf-4054-9606-da07ba281311.png)

Would that work for you?
