### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by dymbox** [Ultimaker/Cura#14612]
### Application Version

5.3.0a

### Platform

macOS

### Printer

Kingroon KP5L

### Reproduction steps

Sliced a model, only added 102% shrikage

### Actual results

Sliced

### Expected results

Did not

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[KK_MK8 Nozzle Sanding Fixture.3mf.zip](https://github.com/Ultimaker/Cura/files/10777367/KK_MK8.Nozzle.Sanding.Fixture.3mf.zip)

**Comment by MariMakes** [comment]
Hey @dymbox,

Welcome to the Ultimaker Community 🎉
Thanks for your report 👍

I just tested your file and it slices in our internal build.
This seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643

This issue has already been resolved, you should keep an eye out for a new release. 👍
