### ISSUE TITLE
Infill not working properly

### ISSUE THREAD

**Issue by Scottz1000** [Ultimaker/Cura#14615]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 

### Reproduction steps

I tried different infill patterns.

This happened on 5.2.1, 5.2.2, and 5.3.0

### Actual results

It printed just like the screen shot I added below. Infill did not go all the way out to the outer walls
![Screenshot_20230219_032106](https://user-images.githubusercontent.com/97261755/219973460-7b4c79f2-612d-423b-b908-8a9f7b8663b1.png)

### Expected results

To correct the problem, I can't be the only one who noticed it

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot_20230219_032106](https://user-images.githubusercontent.com/97261755/219973380-365ad18e-173d-466b-ab48-dddcfaa6f499.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Actually, as far as I know you are the first to have this problem.  I can't duplicate it.
With that model loaded and Cura set up to slice use the "File | Save Project" command.  Zip the 3mf file and post the zip folder here.  It could be a bug.  The project file will tell.

**Comment by Scottz1000** [comment]
[Egg_arrowhead Custom PLA lw 0.4mm lh 0.2mm if 10% ext1 210C bed 55C.zip](https://github.com/Ultimaker/Cura/files/10778562/Egg_arrowhead.Custom.PLA.lw.0.4mm.lh.0.2mm.if.10.ext1.210C.bed.55C.zip)

**Comment by GregValiant** [comment]
Uncheck "Infill as Support".  When it's checked the infill acts like support and only builds a tower to support the overhang of the roof.
I'll go ahead and close this as a settings issue.  I hope you understand.
