### ISSUE TITLE
error during slicing

### ISSUE THREAD

**Issue by abrahamvsaldana** [Ultimaker/Cura#14616]
### Application Version

5.2.1

### Platform

Mac OS 13.2.1 (22D68)

### Printer

Creality Ender 3 S1 PRO

### Reproduction steps

https://user-images.githubusercontent.com/125833808/219977664-4f44f6b6-9591-4e8f-a653-2f33bd2a756e.mov

[CFFFP CFFFP Perspective Creality3D PETG lw 0.4mm lh 0.16mm if 15.0% ext1 225.0C bed 75C Creality3D PETG lw 0.4mm lh 0.16mm if 15.0% ext1 225.0C bed 75C.3mf.zip](https://github.com/Ultimaker/Cura/files/10778079/CFFFP.CFFFP.Perspective.Creality3D.PETG.lw.0.4mm.lh.0.16mm.if.15.0.ext1.225.0C.bed.75C.Creality3D.PETG.lw.0.4mm.lh.0.16mm.if.15.0.ext1.225.0C.bed.75C.3mf.zip)

### Actual results

Actually it´s no slicing models

### Expected results

I expect to SLICE MODELS normally

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP CFFFP Perspective Creality3D PETG lw 0.4mm lh 0.16mm if 15.0% ext1 225.0C bed 75C Creality3D PETG lw 0.4mm lh 0.16mm if 15.0% ext1 225.0C bed 75C.3mf.zip](https://github.com/Ultimaker/Cura/files/10778095/CFFFP.CFFFP.Perspective.Creality3D.PETG.lw.0.4mm.lh.0.16mm.if.15.0.ext1.225.0C.bed.75C.Creality3D.PETG.lw.0.4mm.lh.0.16mm.if.15.0.ext1.225.0C.bed.75C.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10778099/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I moved the model in Cura and rotated it and it sliced.
This is a well known bug and it's being worked on.  I'll mark this as a duplicate slicing error and go ahead and close this.  The Cura team has a lot of examples of this behavior.  I hope you understand.
