### ISSUE TITLE
Cura 2.4 - add 1.0mm nozzle option to UM2+

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#1461]
I can not create an Ultimaker II with Olsson Block.
Using the Ultimaker II+ profile instead, I am limited to only 0.25, 0.4, 0.6 and 0.8mm nozzles.
However I do all structural parts with a 1.0mm nozzle that can not be selected.
(very strong parts in a short time where details don't matter)

**Comment by ChrisTerBeke** [comment]
As a work-around you can edit the line width instead of the nozzle size.

**Comment by Ghostkeeper** [comment]
We may not have specific profiles for those nozzle sizes, but you can still modify the line width yourself if you modified the hardware of the printer.

**Comment by ChrisTerBeke** [comment]
Closing due to old Cura version and the fact that we won't support custom nozzle sizes on Ultimaker printers (not testable for us).
