### ISSUE TITLE
How to use cura to save png images? Is there an api interface

### ISSUE THREAD

**Issue by yess1987** [Ultimaker/Cura#14619]
### Is your feature request related to a problem?

How to use cura to save png images? Is there an api interface
I want to use stl file to directly convert to a png image

### Describe the solution you'd like

How to use cura to save png images? Is there an api interface
I want to use stl file to directly convert to a png image

### Describe alternatives you've considered

How to use cura to save png images? Is there an api interface
I want to use stl file to directly convert to a png image

### Affected users and/or printers

How to use cura to save png images? Is there an api interface
I want to use stl file to directly convert to a png image

**Comment by MariMakes** [comment]
Hey @yess1987,

Thanks for your report 👍
I don't believe that is something you can do in Cura. 

Can you please use the template to help us understand what problem you are trying to solve? 
What problem are you solving by saving pngs?

There is a way to extract the render you see in your .3mf and .ufp files. 
Is that what you are after? 

![image](https://user-images.githubusercontent.com/40423138/220374717-b54cb338-eab5-4b68-8c90-a65b00171283.png)
