### ISSUE TITLE
double shadows are too dark

### ISSUE THREAD

**Issue by norbertom8** [Ultimaker/Cura#14621]
### Application Version

5.3.0

### Platform

windows 10

### Printer

Artillery Sidewimder x2

### Reproduction steps

doubled shadows overlapping from two different parts are too dark making it hard to see the grid

### Actual results

double shadows are too dark making it hard to see the grid

### Expected results

double shadows are too dark making it hard to see the grid

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Just that

**Comment by MariMakes** [comment]
Hey @norbertom8,

Welcome to the Ultimaker Cura Github 🚀 

A screenshot would really help to understand your problem. 😅 
How is this bug affecting you in using Cura? 
What is something you cannot do now that you cannot see the grid?
