### ISSUE TITLE
Cura crashes upon startup

### ISSUE THREAD

**Issue by fender-bender** [Ultimaker/Cura#14623]
### Application Version

>5.1.0

### Platform

Windows 10

### Printer

None

### Reproduction steps

Install any version of cura >5.1.0
Run

### Actual results

Cura gives this screen 
![image](https://user-images.githubusercontent.com/80074481/220248765-8c6a94fe-ff99-4528-8f76-97975bb9ab75.png)

### Expected results

Cura should launch and let me slice as it did with version 5.1

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10789614/cura.log)

**Comment by MariMakes** [comment]
Hey @fender-bender,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, to hear your Cura is crashing😞 

Your logs are spamming that something is wrong with the containers and metadata. 
Could you try resetting your Cura? If there is anything you would like to keep, first create a back-up, or zip the files you are about to delete first. 

[You can find the instructions to do so here.](https://support.makerbot.com/s/article/1667337567843)
