### ISSUE TITLE
Cura is not able to slice Skull

### ISSUE THREAD

**Issue by reite24** [Ultimaker/Cura#14626]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

I designed a dartholder at Tinkercad, by using a skull as base and adding 12 Holes. Then i sliced it and printed it. Because the holes were to small, i modified the diameter of the holes with Tinkercad. After that I tried to slice the Skull v2, but I got an error massage.

### Actual results

Slicing the Skull with Cura is not possible.

### Expected results

The Skull shoud be sliced.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

STL Data of Skull v2:
https://cloud.sturm-gruppe.com/index.php/s/SdPrbcyPtFWJ8dH

Error massage:
![Error](https://user-images.githubusercontent.com/125960673/220293054-34c645cb-ad43-4394-bd2b-eb04e1140546.PNG)

**Comment by MariMakes** [comment]
Hey @reite24,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

![image](https://user-images.githubusercontent.com/40423138/220322919-767bfaa8-fda2-4ad7-87fa-6fa91c3a4431.png)

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

**Comment by reite24** [comment]
Thank's for the quick reply. Meanwhile i could slice the Skull. I just moved it a bit in x and y direction and then it worked.
-------- Ursprüngliche Nachricht --------Von: MariMakes ***@***.***> Datum: 21.02.23  11:41  (GMT+01:00) An: Ultimaker/Cura ***@***.***> Cc: reite24 ***@***.***>, Mention ***@***.***> Betreff: Re: [Ultimaker/Cura] Cura is not able to slice Skull (Issue #14626) 

Hey @reite24,

Welcome to the Ultimaker Cura Github 🚀

Thanks for your report 👍



This mesh seems faulty

Have you tried doing a quick mesh fix with the Meshtools Plugin?

You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.

Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

**Comment by MariMakes** [comment]
Yay! Good to know, I'll close this ticket.
