### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by jk101290** [Ultimaker/Cura#14633]
### Application Version

5.2.1

### Platform

Linux Mint 20.3

### Printer

Ender Extender 400XL (Modded E3Pro)

### Reproduction steps

Tried slicing a 3D model

### Actual results

Message: Slicing failed with an unexpected error

### Expected results

Cura slices the model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This does not occur if I rotate the model so that it is along the y axis. It also does not occur in 5.1.0. Including project and log.

[xtender400XL_profilebug.zip](https://github.com/Ultimaker/Cura/files/10797800/xtender400XL_profilebug.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10797863/cura.log)

**Comment by MariMakes** [comment]
Hey @jk101290,

Thanks for your report 👍

It seems to be a duplicate of https://github.com/Ultimaker/Cura/issues/13643
I was able to slice it with the 5.3 Beta, can you try aswell? 
![image](https://user-images.githubusercontent.com/40423138/220911740-c261901e-ba90-4863-8499-c6890a25165a.png)

You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0-beta.1

**Comment by jk101290** [comment]
@MariMakes I was able to slice it in 5.3, thanks!
