### ISSUE TITLE
Infill Values not working

### ISSUE THREAD

**Issue by KacieHultgren** [Ultimaker/Cura#1465]
Changing infill values in Cura 2.4 on mac is not working.  Have tried changing via the recommended tab - see attached images - as well as custom tab.  Changes in infill pattern also not working.

![light](https://cloud.githubusercontent.com/assets/25957939/23216764/27db8f74-f8e5-11e6-9377-b5a0d15c542a.jpg)
![hollow](https://cloud.githubusercontent.com/assets/25957939/23216766/27e7e670-f8e5-11e6-8101-3343567c8c0b.jpg)
![dense](https://cloud.githubusercontent.com/assets/25957939/23216765/27e32e64-f8e5-11e6-8960-f614447fd637.jpg)

**Comment by awhiemstra** [comment]
It is immediately obvious here but you are changing the infill density of the second extruder, while your object is probably being printed with the first extruder. If you switch to the first extruder (click on the "Print Core 1" tab thingy) you should see the infill density properly change.

**Comment by KacieHultgren** [comment]
Ah, thank you.  I haven't used the extruder often enough to get the tab switching into my workflow.  Thanks for catching.
