### ISSUE TITLE
Cura won't slice .stl file

### ISSUE THREAD

**Issue by zepher38** [Ultimaker/Cura#14655]
### Application Version

5.0

### Platform

Windows 10

### Printer

Prusa Mk3

### Reproduction steps

Loaded a Planeprint pre-made .stl file
[V-tail3-right LW_profile3_rise.zip](https://github.com/Ultimaker/Cura/files/10816717/V-tail3-right.LW_profile3_rise.zip)

All the other files for this project print fine.

Planeprint sent a replacement .stl file and it failed to slice as well.

### Actual results

1. Selected "New" project
2. Selected the .stl file in question
3. Clicked on "Slice"
![Slicer_Error](https://user-images.githubusercontent.com/126193128/220991320-b9460d19-d983-49c8-8a7e-63e96ba41442.PNG)

### Expected results

I expected Cura to slice the provided .stl file so it can be printed

[PI3MK3M_V-tail3-right LW_profile3_rise.zip](https://github.com/Ultimaker/Cura/files/10816903/PI3MK3M_V-tail3-right.LW_profile3_rise.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log.zip](https://github.com/Ultimaker/Cura/files/10816834/cura.log.zip)

**Comment by MariMakes** [comment]
Hey @zepher38,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

![image](https://user-images.githubusercontent.com/40423138/221213327-9bd559e0-a193-4f55-b779-d76bd554595a.png)
This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

**Comment by WOWElectronics** [comment]
latest appimage of 5.3.0-beta-2 for linux, on debian bullseye won't slice, does not even give menu to start slice. Forced me to back up to 5.2.1-beta which has it own problems with retraction, as in does not retract when moving to another copy when doing 2 or more up, so excess stringing that takes half an hour to trim off with a constantly steel sharpened box knife. I'd paste the .stl but its just short of 23 megs made into 50 megs made into gcode by 5.2,1-beta.  Its a half nut for a 2" diameter hard maple screw, buttress thread. Takes around 12 hours to print 2 up.
