### ISSUE TITLE
Normal supports not being generated

### ISSUE THREAD

**Issue by tangcla** [Ultimaker/Cura#14658]
### Application Version

5.3.0-beta1

### Platform

Windows 11

### Printer

Creality CR-6 SE

### Reproduction steps

Used a different model - still no supports
Set support overhang angle to 10 degrees - still no supports
Toggled between normal and tree supports - tree supports are fine

### Actual results

No supports are generated in the preview

### Expected results

Normal supports should be created in the model as there are some serious overhangs (especially at 10 degree overhang angle).
Tree supports are created as expected, but normal supports are absent.
![Screenshot 2023-02-24 131309](https://user-images.githubusercontent.com/8278114/221075089-240347aa-53b9-477b-b194-94af0f9f46d0.png)
[bottom.zip](https://github.com/Ultimaker/Cura/files/10820037/bottom.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10820033/cura.log)

**Comment by MariMakes** [comment]
Hey @tangcla,

Thanks for your report 👍
That doesn't look like it's going to print well 😮 

![image](https://user-images.githubusercontent.com/40423138/221164896-877d0532-4759-467e-a8c7-0ea322b502b5.png)

I'll bring it up to the team to see what they can do to improve before the stable.
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @tangcla ,

Thanks again for bringing it up. 
We are super grateful for the report. 

We've added a ticket to with the intent to fix this as soon as possible. 
For internal reference CURA-10340

Thanks for the report, and apologies for the inconvenience.

**Comment by MariMakes** [comment]
![image](https://user-images.githubusercontent.com/40423138/221214867-e94326bd-35d1-41d4-b6a1-e0231623d7e9.png)

Update! It seems to be related to the experimental Conical Support. 
We'll be working on a solution, but at least you get unstuck.

**Comment by teafusion** [comment]
I opened another ticket before finding this one, but have more notions on the issue aka using conical supports brim creation also breaks in conjunction when you disable prime tower while dual extrusion enabled, resulting the brim to become very narrow, possibly including only the second extruder two lines. My ticket https://github.com/Ultimaker/Cura/issues/14666

**Comment by MariMakes** [comment]
Hey @teafusion,

Thanks to your report we were able to resolve the issue here: https://github.com/Ultimaker/CuraEngine/commit/34e126879add53fd15796d19a3e4e0a90740d38c

I can successfully slice your model in Cura 5.3 Stable, [you can download the stable here to try for yourself. ](https://github.com/Ultimaker/Cura/releases/tag/5.3.0)

![image](https://user-images.githubusercontent.com/40423138/226412156-521411e7-9cc0-4d0c-8607-1fde3b9c8af8.png)

Thanks again, thanks to your report we were able to narrow down what the problem was. 
I'll close this issue since there is a solution in place. 💪
