### ISSUE TITLE
Infill setting not changing

### ISSUE THREAD

**Issue by Dmills541** [Ultimaker/Cura#14668]
### Application Version

5.3

### Platform

windows 10

### Printer

multiple

### Reproduction steps

Trying to adjust infill density settings to slice in cure and the infill will not change from default setting. i have tried this on cura 5.2.2 and cura 5.3.0, and on profiles i have being Creality Cr10, Creality ender 3 pro, and Sovol SV02. this is a new issue that just started this evening. my original solution was to restart version 5.2.2, then reboot my PC, then, update to the 5.3.0 beta version and the issue continues.

### Actual results

there has been no change after any of the steps listed above

### Expected results

I would hope the steps would allow the infill setting to be adjusted

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

no screenshot or crash log to show the infill density setting just doesn't change it would just be a screenshot of a default setting

**Comment by MariMakes** [comment]
Hey @Dmills541,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Infill seems to work for me. I'll need a little bit more information from you. 
Are you able to make a video sharing your screen to show what is going wrong? 
Or do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
