### ISSUE TITLE
Beta notification leads to old beta news post

### ISSUE THREAD

**Issue by jwigum** [Ultimaker/Cura#14685]
### Application Version

5.2.1

### Platform

macOS 11.6.7

### Printer

Generic

### Reproduction steps

1. Launch Cura
2. Note 5.3.1 beta notification
3. Click button to learn more (can't remember exact text)
4. Browser opens to news page

### Actual results

4. Browser opens to news post from September talking about 5.2 beta, which is an older version than I'm running

### Expected results

4. Browser opens to news post talking about the new hotness from the notification, not an older version

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I get this is probably a website issue, but it's the report method I had on hand.

**Comment by MariMakes** [comment]
Hey @jwigum,

Thanks for flagging this!
Sorry, it took us a while to get back to you.

The link should now redirect to the correct page. 
I'll close this issue, thanks for your report 👍

And good luck trying the beta!
