### ISSUE TITLE
unable to slice

### ISSUE THREAD

**Issue by sirdirk22** [Ultimaker/Cura#14688]
### Application Version

5.3.0-alpha+cura_9879_19

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

loaded stl from thingiverse
attempted to slice
recieved error
restarted cura
![unable to slice](https://user-images.githubusercontent.com/126370943/221391561-9bf93efb-5e7b-4b6f-88c9-48d49ca1f004.png)

tried again with same result
stl can be found here https://www.thingiverse.com/thing:5159220

### Actual results

error. unable to slice

### Expected results

the file should be sliced and produce a gcode

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10832920/cura.log)
[Unable to Slice.zip](https://github.com/Ultimaker/Cura/files/10832927/Unable.to.Slice.zip)

**Comment by sirdirk22** [comment]
oh man... how did i miss that? it was weird because it would slice just
fine in cura 5.2... please close this ticket :)  and thank you for your
time and attention 👍

**Comment by MariMakes** [comment]
Glad to hear. 
Good luck with your door lock shim 🙂
