### ISSUE TITLE
5.3.0 upgrade from 5.2.1 - Crashing after installation - Not able to run

### ISSUE THREAD

**Issue by PilotManForever** [Ultimaker/Cura#14683]
### Application Version

5.3.0

### Platform

Mac

### Printer

NA

### Reproduction steps

I got a notification to upgrade the city to try beta 530. 

After downloading and dragging into the applications folder I was not able to launch the new version. 

After multiple trials decided to download the 5.2.2 version and reinstall. 

Absolutely nothing appears to happen and there is nothing to force quit. 

### Actual results

None.   Nothing working. 

### Expected results

To Run

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Only log files that show up are from installations of 4.11 through 4.13.

**Comment by MariMakes** [comment]
Hey @PilotManForever,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

What a super frustrating way to get stuck. 
Are you still stuck? 

If that's the case, can you help me understand what `downloading and dragging into the applications folder` means? 
Do you install the program in a different place than the installer suggests?
