### ISSUE TITLE
Files will not slice due to unknown error

### ISSUE THREAD

**Issue by OverlordRylin** [Ultimaker/Cura#14713]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Crealit Ender-3 Pro

### Reproduction steps

I downloaded my STL from tinkercad as I normally do and tried to slice the file. 

### Actual results

Cura gives me this error message:  Slicing failed with an unexpected error. 

### Expected results

I expectred Cura to slice the file as usual but this just started happening. I tried other files and they work fine. I even re-downloaded the file from Tinker cad and the same thing happens. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file there really can't be an investigation.  The instructions for creating on are on the first page you filled out for this report.
There are a couple of things you can check.
In the Cura "Prepare" screen are any of the upper surfaces red?  Are there any "Polka-Dot" surfaces?  Cura uses those to indicate errors in the model.
You can open your model in MS 3D Builder (available from the Microsoft App Store) and it will tell you if there are errors in the model.  It also has a pretty good repair function.
