### ISSUE TITLE
Supports not showing up.

### ISSUE THREAD

**Issue by Loonatix** [Ultimaker/Cura#14715]
### Application Version

5.3.0-beta 2

### Platform

Windows 10 PRO

### Printer

Anycubic Kobra

### Reproduction steps

Uploaded model, checked off support for model. No supports showing on model. No kind of support showing on screen. It was working just fine. 

### Actual results

Can't print models without supports. Models will sag.

### Expected results

Get supports for models.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

xxxxx

**Comment by MariMakes** [comment]
Hey @Loonatix,

We made some fixes for this in the 5.3 stable, which you can expect soon. 
You can download it here: https://github.com/Ultimaker/Cura/releases

Can you test if this resolves your issues? 

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
