### ISSUE TITLE
Zonestar Z8 mit 3 Extruder

### ISSUE THREAD

**Issue by Thorstenb1987** [Ultimaker/Cura#14740]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Zonestar z8

### Reproduction steps

Ich habe mi ein Zonestar Z8 gekauft. 
Bei dem Cura 4 konnte ich den Drucker installieren leider nur mit 2 Extruder. 
Nach dem Udate 5.2 ist in den Drucker hinzufügen nicht mal mehr Zonestar aufgeführt.
Jetzt hab ich einen Drucker mit 3Extruder und kann ihn nicht verwenden. 

### Actual results

Drucker ist nicht aufgeliestet

### Expected results

Hoffe es isst möglich meinen Zonestar Z8 Mit 3 Extruder zu Installieren

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Keine DAtei

**Comment by GregValiant** [comment]
Cura is open source and anyone may add a printer definition file.  UltiMaker maintains Cura but is not responsible for 3rd party definition files.  In addition, some manufacturers have taken Cura and made it their own slicer and added their machines to it.  Your printer may never have had a defintion in UM Cura but did in Zonestar Cura (if there is such a thing).

If you know your printers physical size and what flavor of gcode it requires you can try installing a Geeetech A30T which is a 3-in-1-out printer.  It may be close enough to get you going.  If you go back to your previous version of Cura and check your "Machine Settings" you can note those settings and set the Geeetech printer up the same way.  The actual name of the printer can be changed (although the definition file it uses will remain the Geeetech file).

I'll go ahead and close this as UltiMaker cannot be responsible for printers built by other companies.  It would be impossible.  I hope you understand.
