### ISSUE TITLE
Z seam start from middle no matter what

### ISSUE THREAD

**Issue by CalinN96** [Ultimaker/Cura#14743]
### Application Version

5.2 and 5.0

### Platform

Windows 11

### Printer

Flsun V400

### Reproduction steps

I changed Z Seam Alignment on literally everything. Random, corner, everything possible, and no matter what, on ALL layers it always starts from the middle for some reason.

I tried with 4 different infill types, it is not that.
I tried 2 different models, is not that.

### Actual results

It ignores the Z Seam I set

### Expected results

To start it from a corner or even random, just not always from the middle because it finishes the left side and then jumps to the right side

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/66618606/222538602-fec859f7-3aa0-4e59-bd31-4fc7af6d2ddf.png)
![image](https://user-images.githubusercontent.com/66618606/222538807-c2189fcb-c262-4c85-975d-af0ebc688ba2.png)

**Comment by GregValiant** [comment]
Thanks for the report.  Without a project file it's impossible to do an investigation.  The instructions are on the page you filled out for this report.
I have a question though.
The Z-seam is the point on the outer wall that the outer wall extrusion starts and stops.  Infill is not involved at all.
There are separate settings in the Travel section regarding the Layer Start X and Layer Start Y.  The only setting for Infill is "Randomize Infill Start".
So is it possible there is some confusion here regarding the Z seam?  Are we talking apples and apples?
Here you can see that Cura has marked the Z seam with small white blocks.  The seam is set to "right".
![image](https://user-images.githubusercontent.com/64202104/222574839-820d6b22-7d22-48b5-b366-2bc1ea35fab0.png)

The only change I made here was to move the Z seam to "Left" and it did.  I have no idea where my infill starts and stops, only where the Z-seam scar is going to be.
![image](https://user-images.githubusercontent.com/64202104/222575112-907a947e-84a2-495c-af39-95be3f646f42.png)

**Comment by CalinN96** [comment]
If only you would know how much this explanation saved me... would be surprised.

I searched all over the internet and everyone was talking about the z seam in order to fix my infill issue...

Thank you a lot for your answer!

Have a great day!
