### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by defalkner** [Ultimaker/Cura#14744]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

custom

### Reproduction steps

slicing complex stl

### Actual results

about 15% of the file slices then fails

### Expected results

slicing should have completed.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

stl may be too complex for engine to slice

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura log file we can't do an investigation.  The instructions are on the page you filled out for this report.
_"...stl may be too complex for engine to slice"_
I haven't seen that yet.  It may take a while, but an error free model should slice regardless of the complexity.
