### ISSUE TITLE
5.3.0-beta.2 Infill and walls change order of printing when permodel settings are activated

### ISSUE THREAD

**Issue by Ugly101** [Ultimaker/Cura#14762]
### Application Version

5.3.0-beta.2

### Platform

Windows 10

### Printer

Creality CR10s

### Reproduction steps

1) Selected support blocker 
2) Then per model settings.
3) Then changed the infill from 10% to 30%

### Actual results

The infill started to print before the walls instead of the walls printing first.

### Expected results

The order of infill should be printed AFTER the walls unless infill before walls is selected in the per model settings. This can result in dimensional inaccuracy's at the infill change layer height.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Image 1](https://user-images.githubusercontent.com/95768951/222916726-57a0d395-9de8-4345-9b6c-0dcd2d0f1712.jpg)

![Image 2](https://user-images.githubusercontent.com/95768951/222916735-bd04fbfd-b82d-4ffe-91cf-219e6f1a3c0c.jpg)

![Image 3](https://user-images.githubusercontent.com/95768951/222916753-dbbb9a65-db1f-440b-962c-9f980d9d8046.jpg)

https://user-images.githubusercontent.com/95768951/222918080-f2fe8f2f-f8e4-4815-b6dd-9d2f1dd626b0.mp4

**Comment by GregValiant** [comment]
Thanks for the report.
We'll need a project file to investigate this.  Load the model in Cura, set up to slice, use the "File | Save Project" command to create a 3mf project file.  Zip the project file and post the zip folder here.
