### ISSUE TITLE
Lose Profile settings when changing Filament

### ISSUE THREAD

**Issue by NO1DLR** [Ultimaker/Cura#14767]
### Application Version

4.13.2

### Platform

lsb_release -a

### Printer

Custom

### Reproduction steps

1. Every time I change filament type Cura loses my profile settings. 
2. Every time I change filament I have to completely reset all my slicer settings by manually entering them. The feature to save settings is completely broken.

### Actual results

It works until I have to change filament. 

### Expected results

The software should do what it says and save the slicer settings I have selected.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by MariMakes** [comment]
Hey @NO1DLR,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for the report. 

I'm not sure if it's a bug in Cura. 
When you change filament a lot of settings change with it, like temperature and print speed. 

You should get a pop-up asking if you want to keep your settings. 
Do you have Always Ask Me This enabled in your Preferences | Configure Cura? 
![image](https://user-images.githubusercontent.com/40423138/223186935-a56e454f-caa8-4dee-9985-19970aca1864.png)

If that's not it. 
Can you help me understand, what settings do you expect to stay that are not staying?
