### ISSUE TITLE
PauseBackendPlugin missing

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#1477]
Has it been kicked out of Cura again? 🤔 

```
dh_install: cura-plugin-pausebackend missing files: /usr/lib/cura/plugins/PauseBackendPlugin
dh_install: missing files, aborting
debian/rules:16: recipe for target 'override_dh_install' failed
```

**Comment by awhiemstra** [comment]
The functionality was integrated properly instead of being in a plugin. So yeah, the plugin has gone the way of the dodo, but the feature is still there.

**Comment by thopiekar** [comment]
Thank you for the info, @awhiemstra 👍
