### ISSUE TITLE
Ultimaker Cura 5.3.0 Beta 2 Adhesion Bug

### ISSUE THREAD

**Issue by tahayusab** [Ultimaker/Cura#14775]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic i3 Mega S/P/X

### Reproduction steps

1. I added text cube
2. added brim adhesion 
3. sliced
4. no brim was shown in the preview

### Actual results

no brim was shown in the preview

### Expected results

seeing the brims or any types of adhesion in the preview section

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Ekran Görüntüsü (78)](https://user-images.githubusercontent.com/83808941/222958453-4b897b55-41c4-43f4-ae4b-9d510fd172c1.png)

**Comment by GregValiant** [comment]
Thanks for the report.
I know I can't duplicate this as the print I have running now has a brim.  That's why we ask for Project Files.
Check your preview "Color Scheme" and see if you have "Helpers" disabled.

**Comment by tahayusab** [comment]
yeah you were right in the old version because i didn't changed it i didn't think about it. thanx for your help
