### ISSUE TITLE
Wont let me slice this file

### ISSUE THREAD

**Issue by bsj56888** [Ultimaker/Cura#14777]
### Application Version

5.1

### Platform

Windows 10

### Printer

Sovol 03

### Reproduction steps

Just tried to slice it  and keeps giving an error

### Actual results

says error

### Expected results

says error

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

says error

**Comment by GregValiant** [comment]
Thanks for the report.
Let me go over what I know of the problem.
"says error".
This is why a project file is necessary.  Sometimes it's a bug, sometimes it's the model, sometimes it's the user, sometimes it's the printer, sometimes it's the computer.
