### ISSUE TITLE
Don't restart Cura (2.4) when USB is connected!!

### ISSUE THREAD

**Issue by foreachthing** [Ultimaker/Cura#1478]
- Updated Firmware on UM2
- Started Job from SD
- Closed Cura 2.4
- ... Job's almost done! Just one more hour.
- started Cura 2.4 (left USB cable attached) ..... ***BAM*** Printer stopped!
Thank you, Cura 2.4!

**Comment by fieldOfView** [comment]
Sorry about your print!

Better rule of thumb: don't keep the usb cable connected when you don't use it.

**Comment by foreachthing** [comment]
Yeah, me too! Just thought this should be documented somewhere or possibly caught in Cura, when the printer is printing, don't try to connect.

**Comment by nallath** [comment]
We don't know that the printer is printing, untill we connect. It's actually a bit of a weird arduino issue that trying to connect to it causes a reboot.

**Comment by fieldOfView** [comment]
So the only reasonable course of action is not to connect on startup, but only when a connection is required:
* when starting a print and/or switching to the print monitor
* when uploading firmware

From a UX perspective, it could be interesting to have an option to have Cura warn you before it tries to open the USB connection.

**Comment by fieldOfView** [comment]
Also see this discussion/proposal:
https://github.com/Ultimaker/Cura/issues/1049

**Comment by foreachthing** [comment]
I like that one: "without thinking"! :-)
Well, **now** I know!

**Comment by ianpaschal** [comment]
Since this issue is almost a year old and hasn't had any activity in 11 months, I'm going to go ahead and close it. See fieldOfView's discussion which is open.

**Comment by Ghostkeeper** [comment]
This is still an issue with the most recent version. If you start Cura with the USB cable connected to your printer, it ruins your print because Cura causes the printer to restart.

**Comment by LipuFei** [comment]
@ChrisTerBeke That sounds like a nice feature, but a lot more work than expected... I will reopen this and make a new JIRA ticket.

**Comment by fieldOfView** [comment]
@LipuFei, see #1049 for a proposal of the UI. I once got half implementing it in #1688 but other things (and the release schedule) got in the way. I could pick it up again around the end of june.

**Comment by goscicki** [comment]
PLEASE make Cura stop connecting on startup. It still does this in 4.0. Why can't it just connect you click print? I keep opening a new window to tweak what I'm going to print next and lose hours of work/materials!

**Comment by MollyUrs** [comment]
I can't believe this is still an issue, it also causes issues with loads of programs as it hogs all of the COM ports so I can't use my Arduino while printing :/
