### ISSUE TITLE
Slicing Failed, Unexpected Error

### ISSUE THREAD

**Issue by rke211** [Ultimaker/Cura#14804]
### Application Version

5.0.0

### Platform

Windows 10 Prro, GeForce GT 730

### Printer

Creality Ender-3 V2

### Reproduction steps

1. Opened Pre Sliced Helmet section STL file
2. Hit Slice 
3. Slicing Failed, slicing failed with an unexpected error

### Actual results

Slicing Failed

![image](https://user-images.githubusercontent.com/67314686/223431694-441e68d6-cc51-4405-900c-d0a3a3e1b120.png)

### Expected results

Slicer Fails
Works if scaled to 99.9%

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3_HELMET_5.zip](https://github.com/Ultimaker/Cura/files/10909691/CE3_HELMET_5.zip)
[cura_log.txt](https://github.com/Ultimaker/Cura/files/10909721/cura_log.txt)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing this.  There is a bug (being worked on) that can keep a model from slicing when it is at the mid-point of the Cura build plate.  Try moving and/or rotating the model.  That can often fool this bug.
I'll mark this as a duplicate and a slicing error.  I'll close this as well as it is a known issue in 5.0 through 5.3.1beta and should be fixed for 5.3 stable.
