### ISSUE TITLE
Slicing fails

### ISSUE THREAD

**Issue by reuschi** [Ultimaker/Cura#14809]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

1. Inserted a .STL file
2. Started slicing
3. Slicing interrupts immediately with an unexpected error (no error code or something like this available)

### Actual results

Nothing happens. I can't slice anymore. With Version 5.2.2 everything was working normal. But no STL file do work anymore in 5.3.0

### Expected results

It should just slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura_slice_error](https://user-images.githubusercontent.com/35533281/223531137-108b83c9-4670-4ff7-988a-6f13bb51d472.png)

**Comment by reuschi** [comment]
With installation of the MSI file the slicing fails. After reinstallation by the EXE installation file, slicing is working again.

**Comment by MariMakes** [comment]
Hey @reuschi,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Are you still stuck? 
Or do you still need some troubleshooting help?

**Comment by reuschi** [comment]
Hi @MariMakes,

Thanks for asking. Don't know what was the problem, but currently Cura is working as expected, after I reinstalled it.
So, everything seems to be fine now and I just wanted to let you know, that they _could_ possibly be a problem with the MSI file.
