### ISSUE TITLE
Printer bed size

### ISSUE THREAD

**Issue by hekistner** [Ultimaker/Cura#14808]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Tronxy X5SA Pro 2E

### Reproduction steps

I was using Cura 4.13.1 working great. Moved to Version 5.0.0 and the printer settings did not move with the 5.0.0 setup. So I went to manage the printer and set up printer 1 and printer 2 bed size to 330mm x 330mm x 400mm which is the proper bed size for my printer. Which works with version 4.13.1 entered the rest of the settings. When I opened Cura the bed size for X & Y was correct at 330mm square. But the print height was less than 1/2 of the 400mm. The maximum height I can print is approx. 149.2mm. I have tried changing the height to double to 800mm but the height does not change. Changed to less than 100mm and it does not change. So my printer has a limited printing height of 149,2mm with Cura version 5.0.0 and above and yes I have tried the latest released version. So to print models that extend above 149.2mm I have to go to version 4.13.1 to print them

### Actual results

Have not been able to slice anything that is taller in the Z direction than 149.2mm

### Expected results

Should be able to set the bed height to 400mm. then slice the model and print.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'm unable to send a copy of the screen while Cura is loaded.

**Comment by 64bittuning** [comment]
Tronxy Profile creator here. Something is wrong with your install. Remove all versions of Cura from your machine, including all Cura files buried deep in your C drive. (C:\Users\(UserName)\AppData\Local\cura)

I have 5.3.0 freshly downloaded and was able to slice a 340mm tall print with no issues.
