### ISSUE TITLE
won't slice

### ISSUE THREAD

**Issue by Georgia94** [Ultimaker/Cura#14814]
### Application Version

5.3.0

### Platform

MacBook air

### Printer

creality CR-10S

### Reproduction steps

When I try to slice the 3d model it does this.
![A689ADAD-E052-402C-BB74-53420D657BA1](https://user-images.githubusercontent.com/127271093/223603984-66da218b-986a-4340-88cc-579b7c19cfdf.jpeg)

### Actual results

![A689ADAD-E052-402C-BB74-53420D657BA1](https://user-images.githubusercontent.com/127271093/223604262-e055dc09-49e6-42e2-a763-9ebad5d474f6.jpeg)

### Expected results

save it so I can 3d print it.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![A689ADAD-E052-402C-BB74-53420D657BA1](https://user-images.githubusercontent.com/127271093/223604070-1f96b989-e4c0-4640-93d3-f71f893758af.jpeg)

**Comment by MariMakes** [comment]
Hey @Georgia94,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
