### ISSUE TITLE
Skirt/Brim outside of build plate boundaries

### ISSUE THREAD

**Issue by ThatOneKidLiam** [Ultimaker/Cura#14815]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 S1 Pro

### Reproduction steps

1. Skirt or brim enabled
2. Object is moved to where skirt or brim is now outside of build plate boundaries 

### Actual results

Skirt or brim is sliced correctly (along with object), though the part of the brim or skirt that is outside of build plate boundaries is now cut off

![Screenshot 2023-03-07 224700](https://user-images.githubusercontent.com/127281814/223629773-d5862cfe-5f82-498a-928f-790ed9d729bd.png)

### Expected results

Cura should give a warning saying that it will not slice correctly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'm not sure if this is an intended feature or not, I just wanted to report this just in case its a bug that needs to be fixed. I have not tested to see if this will damage the printer or cause issues (have not saved gcode and printed file).

I'm new to github and am not sure how this platform works, so I'm hoping this works.

**Comment by GregValiant** [comment]
Thanks for the report.
I can duplicate this bug.
This is in 5.2.2.  The model is too close to the edge and the "reserved for brim" gray area is present.
![image](https://user-images.githubusercontent.com/64202104/223715343-1fae8164-25c2-408c-a54c-e7fe0a4dc85d.png)

This is in 5.3.s-beta and you can see that the brim reserved area is ignored and the model was allowed to slice.
![image](https://user-images.githubusercontent.com/64202104/223715624-13c7d92a-08fb-43d6-9027-17ae6c286494.png)

I'll mark this as a Slicing Error (it should not have sliced) and @MariMakes of the Cura team will take a look.

**Comment by MariMakes** [comment]
Hey @ThatOneKidLiam,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This seems to be one of the new features introduced in Cura 5.3
You can read more about it here: https://github.com/Ultimaker/CuraEngine/pull/1613
It's done on purpose to allow more print jobs on your buildplate/

If you print it, does your printjob fail? And if it does, can you show a picture?
Then we can take another look at the implementation.

But to me, it doesn't seem like a bug in Ultimaker Cura. 
Would you still like to keep this issue open or do you agree that we can close it?
