### ISSUE TITLE
Slicing Failure

### ISSUE THREAD

**Issue by RodislavR** [Ultimaker/Cura#14819]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. Loaded multiple objects on the built plate with my previous configurations and pressed Slice.
2. Repeated a few times. Still the same result.
3. Changed placement of the objects. Still same result.
4. Deleted objects. Still same result.
5. Loaded 3 small objects. Still Failure.

### Actual results

1. Slicing failed multiple times.
2. Changed to Cura 5.2.1 and Sliced my models. Worked out fine.

### Expected results

Cura should generate a G-code file. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2023-03-08 (1)](https://user-images.githubusercontent.com/127315254/223725101-b50d9b5b-ecc1-43b2-91f9-b61571fa2b97.png)
![2023-03-08](https://user-images.githubusercontent.com/127315254/223725109-bec602be-beaa-4200-982d-1053c2f7c77c.png)

**Comment by MariMakes** [comment]
Hey @RodislavR,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

 I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by RodislavR** [comment]
[Slicing Failed.zip](https://github.com/Ultimaker/Cura/files/10922727/Slicing.Failed.zip)

Thank you for the fast reaction! 

I have attached the zipped Project file. 

Kind regards,
Rodislav

**Comment by MariMakes** [comment]
Hey @RodislavR,

Thanks for the file! I figured out what is going wrong. 👍 
Your Minimum Feature Size is too small. 
If you increase it to 0.1 your models slices again.
![image](https://user-images.githubusercontent.com/40423138/224004933-973087b6-cc21-4f07-acb7-7e7563332681.png)

To me, it doesn't seem like a bug in Ultimaker Cura anymore, since it's related to your settings. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by MariMakes** [comment]
Awesome! Good luck printing these cutters 🎉
