### ISSUE TITLE
Skirt line count dont match

### ISSUE THREAD

**Issue by PeterSoenberg** [Ultimaker/Cura#14831]
### Application Version

5.3.0 alpha xmas

### Platform

Windows 11

### Printer

ender 2

### Reproduction steps

just picture

### Actual results

just picture

### Expected results

just picture

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

<img width="906" alt="Screenshot 2023-03-09 194530" src="https://user-images.githubusercontent.com/46631344/224125746-5798fa93-7555-43ce-aae8-d133d5a93127.png">

**Comment by PeterSoenberg** [comment]
Skirt line count dont match the picture

**Comment by MariMakes** [comment]
Hey @PeterSoenberg,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I think I know what might be happening. 
Your _Skirt/Brim Minimum Length_ might be too high to have a single skirt layer. 
That setting ensures that at least a certain amount of material is extruded when a skirt is printed.
In smaller models that will result in thicker skirts like this: 
![image](https://user-images.githubusercontent.com/40423138/225925607-fa0a1f3f-d414-4a6b-88a7-f47219e9535f.png)

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
