### ISSUE TITLE
memory usage on macOS 10.12

### ISSUE THREAD

**Issue by waspinator** [Ultimaker/Cura#1483]
After running for a few hours, Activity Monitor reports Cura 2.4 using more than 60GB of memory.

**Comment by Ghostkeeper** [comment]
It typically stays around 2GB here on Ubuntu. Seems this is a memory leak specifically in MacOS then.

**Comment by Ghostkeeper** [comment]
Could it be happening only after connecting to a UM3 printer and then seeing the camera image in the print monitor?

**Comment by Ghostkeeper** [comment]
Our product manager just closed this for being inactive for 3 months.

**Comment by waspinator** [comment]
http://i.imgur.com/4AFkCBzl.jpg

**Comment by ianpaschal** [comment]
I'm not experiencing this (I typically have at least 2 instances of Cura open all day), and there's no more recent reports of it, so I'm closing this. It was likely fixed in later versions.

**Comment by Ghostkeeper** [comment]
We've whack-a-moled a bug that was causing this during versions 2.7 and 3.0 if you've accessed the print monitor. The camera image wasn't properly closing when the tab was closed, and a bug in Qt causes the camera data to accumulate for frames that it misses due to a glitchy network connection.
