### ISSUE TITLE
Slicing Failure

### ISSUE THREAD

**Issue by RustyOldStuff** [Ultimaker/Cura#14848]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Sliced and object, got a failure.

### Actual results

Get an error/failure.

### Expected results

Object should have been sliced.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

File is 48 mb compressed, can't upload project.
[cura.log](https://github.com/Ultimaker/Cura/files/10949196/cura.log)

**Comment by MariMakes** [comment]
Hey @RustyOldStuff,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I can see in your logs that you have an Engine process is killed. Received return code 3221225477
That's a generic rounding error, quite a number of them can be solved with slightly resizing or rotating the error with 90 degrees. 

If that's not it, I'll need a little bit more information from you
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
I know you mentioned it's too big to upload,  you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by RustyOldStuff** [comment]
I appreciate the response, and appreciate the interest in weeding-out bugs
in general.  The only new piece of information I'd like to contribute is
that I spend another hour trying to do mesh fixes, reslicing using somewhat
different parameters, etc.  In each case, I got the same failure to slice.

Then, I opened-up an older Creality-branded Cura slicer (I believe it was a
version 4.2, but I don't recall from memory - it's installed on a different
computer that I don't have access to right now).  It sliced absolutely
fine, and printed correctly after 43 hours.  So I have a solution for the
time being.  I'll go back and try re-slicing this object after a 90 degree
x axis rotation and see if it makes any difference.

**Comment by MariMakes** [comment]
Hey @RustyOldStuff,

Thanks for the update. 👍 
Sorry you ran into so much trouble resolving your issue. 😞 

Cura 5.0 introduced a new Variable Linewidth slicing engine, and with it new rounding errors. 
Returning to 4.x version of Cura can indeed also resolve a number of these crashes. 
Cura 4.2 has been released in August 2019 and is missing quite a number of improvements. 

If it's more useful for you to stay on Ultimaker Cura 4.x I suggest to download 4.13.1, [you can download it here. ](https://github.com/Ultimaker/Cura/releases/tag/4.13.1) That version is from October 2021.

Good luck!
