### ISSUE TITLE
slicing not possible under 220°C

### ISSUE THREAD

**Issue by dr5n0w** [Ultimaker/Cura#14840]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

FLSun SR

### Reproduction steps

Printing temp needs min. 220°C... Why? (PLA)
Speed 120-160mm
layer high: 0,2mm
nozzle: 0,4mm

### Actual results

slicing is not possible

### Expected results

slicing is not possible

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Printing temp needs min. 220°C... Why? (PLA)
slicing is not possible under 220°C

Speed 120-160mm
layer high: 0,2mm
nozzle: 0,4mm

**Comment by Asterchades** [comment]
Why is it not possible? You've not specified whether an error is presented (I'm sure there would be) nor provided a project file to reproduce the issue locally, so it's going to be impossible to even figure out _what_ is happening, much less _why_.

Hitting the check next to "Project file" doesn't upload anything. You need to do that manually, following the provided instructions when creating a new issue post. The check is simply to indicate that you've done so.
