### ISSUE TITLE
Crash while slicing

### ISSUE THREAD

**Issue by iduarte1966** [Ultimaker/Cura#14843]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Slice a STL

### Actual results

Can't slice, error.
![BUG](https://user-images.githubusercontent.com/110292099/224429543-3dfc715e-d773-4cd6-a81f-d0fee6c69776.jpg)

### Expected results

No errors
[SpiceGlassHolder_6er.zip](https://github.com/Ultimaker/Cura/files/10946159/SpiceGlassHolder_6er.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10946178/cura.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Not just with this file, many others

**Comment by MariMakes** [comment]
Hey @iduarte1966,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 


![image](https://user-images.githubusercontent.com/40423138/225967100-941c86da-3cc4-40d9-9843-a23046573c84.png)

I was able to slice your file correctly but I see
_Backend exited abnormally with return code 2!_
So I'll have one of the developers take a look to see what that means. 
Fingers crossed 🤞

**Comment by iduarte1966** [comment]
Hi
I've reinstalled Cura and is solved. Thank you
