### ISSUE TITLE
Shift - Middle Mouse Button does not zoom anymore

### ISSUE THREAD

**Issue by Mrts00** [Ultimaker/Cura#1486]
Shift-Middle Mouse Button does not zoom anymore, just like it used to do in the old Cura (15.04.6 and lower). This helps to have a quick workflow, especially when using a Wacom tablet and CAD Software.

**Comment by Ghostkeeper** [comment]
Holding space while moving the mouse works. This was not designed with a drawing pad / pen in mind though. In fact it works quite unintuitively.
