### ISSUE TITLE
"arc welder" causes "pockmarks" in outer wall 

### ISSUE THREAD

**Issue by jahnj0584** [Ultimaker/Cura#14864]
### Application Version

5.3 beta 2 

### Platform

windows 10

### Printer

ender 3 

### Reproduction steps

Used arc welder on model to reduce gcode size. Got weird pockmarks/zits all along my outer walls 

disabled arc welder, they are gone and part prints properly again. 

IT IS NOT A (OVER)RETRACTION ISSUE AT THE SEAM 
IT IS NOT UNDER EXTRUSION 

### Actual results

a print with dented walls that look bad and a part I cannot sell 

### Expected results

a good print but in a smaller gcode file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://ibb.co/pr82fRn

**Comment by fieldOfView** [comment]
Issues with the ArcWelder plugin should be reported on the issue queue of that plugin:
https://github.com/fieldOfView/Cura-ArcWelderPlugin/issues

The maintainers of Cura cannot do much to help you.
