### ISSUE TITLE
Plz insert FLSUN v400

### ISSUE THREAD

**Issue by Looker1981** [Ultimaker/Cura#14865]
### Is your feature request related to a problem?

Plz insert printer FLSUN v400

### Describe the solution you'd like

Plz insert printer FLSUN v400

### Describe alternatives you've considered

Plz insert printer FLSUN v400

### Affected users and/or printers

Plz insert printer FLSUN v400

### Additional information & file uploads

Plz insert printer FLSUN v400

**Comment by Asterchades** [comment]
Non-Ultimaker printers are only added based on community submissions. They're not added nor maintained by the Ultimaker team, thus feature requests as such are pointless.

With that said, the v400 was already added with the 5.3.0 release five (5) days ago.
