### ISSUE TITLE
Skirt is printed after support and model

### ISSUE THREAD

**Issue by domis4** [Ultimaker/Cura#14868]
### Application Version

5.3.0

### Platform

macOS 13.2.1

### Printer

Flashforge Adventurer 3

### Reproduction steps

1. i modified the cura profiles in order to print a very good benchy
2. now i wanted to print a supported structure

### Actual results

when using supports (either auto, or via plugin manually) cura prints the supports and the model before the skirt
As i dont have a purge line for my adventurer 3 yet, this leads to clogging and an unsucessfull print

### Expected results

the skirt should always be printed before either support or model

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[cura-skirt-after-support.zip](https://github.com/Ultimaker/Cura/files/10956888/cura-skirt-after-support.zip)

**Comment by ItsMeAubey** [comment]
I also have this issue.
