### ISSUE TITLE
Misplaced Tooltip

### ISSUE THREAD

**Issue by didierma34** [Ultimaker/Cura#14870]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

TL D3Pro

### Reproduction steps

1. Il s'agit des bulles d'informations qui sont toujours mal placées et empêchent le clic de la souris.

### Actual results

1. Il s'agit des bulles d'informations qui sont toujours mal placées et empêchent le clic de la souris.

### Expected results

1. Il s'agit des bulles d'informations qui sont toujours mal placées et empêchent le clic de la souris.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Pas de fichier

**Comment by MariMakes** [comment]
Hey @didierma34,

Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.
Welcome to the Ultimaker Cura Github 🚀 

We could troubleshoot your problem better if you would have followed the template and added a picture to illustrate your problem. 

Could it be related to the Settings Guide Plug-in? 
Do you have a tooltip that covers your window like this? 
![image](https://user-images.githubusercontent.com/40423138/225075868-35ef96df-a3c3-44c5-97d5-6cfdc6458ed7.png)
Then you can temporarily disable the plug-in if you click on the gear in the Marketplace. 

If that's not the case showing a video or a screenshot would really help with troubleshooting.
