### ISSUE TITLE
Missing part of skirt

### ISSUE THREAD

**Issue by Vipcioo** [Ultimaker/Cura#14876]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Kossel Delta Plus

### Reproduction steps

1. Just sliced model.
2. I checked the same model with the same settings in an older version for confirmation of the error.
The skirt fragment disappears with a random amount of models on the bed, similar to the brim I reported today.

### Actual results

Random fragment missing skirt.

### Expected results

Full skirt around models.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Skirt #1](https://user-images.githubusercontent.com/19477134/224847352-3ac7f65a-a950-4005-a5eb-710edcd1a4dd.png)
![Skirt #2](https://user-images.githubusercontent.com/19477134/224847731-fe4a3849-4863-4c35-aed6-06a393558d75.png)
![Skirt #3](https://user-images.githubusercontent.com/19477134/224847475-21410f29-6057-4e40-bca9-b3eee7d12789.png)

**Comment by MariMakes** [comment]
Hey @Vipcioo,

Thanks for your report 👍
Could it be that you have the following experimental settings enabled:
Enable Coasting + Wipe Nozzle Between Layers
![image](https://user-images.githubusercontent.com/40423138/225031098-79b20044-c898-4ceb-bfde-08f49d0fa369.png)

To me, it doesn't seem like a bug in Ultimaker Cura, just the result of a setting combination. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by grbd** [comment]
Just to add I've been seeing the same thing myself with parts such as the endplate from the M4 extruder
Note, I have no experimental settings set
https://github.com/VoronDesign/Mobius-Extruder/releases/tag/M4

I'm going to have a try of 5.4.0 beta to see if it's fixed there

![image](https://github.com/Ultimaker/Cura/assets/8965579/e1ce5d86-7eb6-4288-a2fd-4bcdd39ca087)
