### ISSUE TITLE
multiply model option places models off build plate

### ISSUE THREAD

**Issue by TheOneTruePhradd** [Ultimaker/Cura#1488]
Placing a model in the center of the plate, right clicking and selecting Multiply Model... will propagate models to the right off the build plate.  Other versions of Cura (Type A) correctly place the models into a grid so all are on the plate.

Ultimaker Version (adding 4 models)
![image](https://cloud.githubusercontent.com/assets/13709876/23563497/bb2ee47a-fffb-11e6-9367-a578e56e0c8e.png)

Type A Version (adding 4 models)

![image](https://cloud.githubusercontent.com/assets/13709876/23563533/e67efcd2-fffb-11e6-8da3-aac25b6e85c8.png)

**Comment by nallath** [comment]
Cura 2 is a re-write of legacy cura (the one model A is based on). We haven't gotten to implementing this fully how it should be.

We've spent some time on checking if we could use a physics engine to handle this, which has had some promising results.  It won't be in the next (2.5) release though.

**Comment by nallath** [comment]
This is in the 2.6 release.
