### ISSUE TITLE
Cura not connecting to octopi. 

### ISSUE THREAD

**Issue by BiggsAH** [Ultimaker/Cura#14895]
### Application Version

Cura 5.3.0

### Platform

Mac OS 13.3

### Printer

Creality Ender 3 V2

### Reproduction steps

Reloaded both Octoprint and Cura latest updates and restarted computer, Pi and printer, but still the same. Unable to load from Cura to printer.

### Actual results

Even though camera is active and temps are shown correctly, when trying to send file to printer I get the message that printer is not connected. This only became an issue with latest update of both Cura and octoprint. Have true reinstalling both but still get same response. With file loaded from SD card I can monitor what is happening but am unable to make ant changes in Octoprint and must make changes at printer.

### Expected results

Everything worked fine until updates.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot 2023-03-15 at 20 12 00](https://user-images.githubusercontent.com/128003359/225475938-1b3bc09d-8ea1-4a82-8616-41b0bbfd7440.png)

**Comment by Asterchades** [comment]
Cura has no native OctoPrint integration - it's handled via the OctoPrint Connection plugin. As such any issues would need to be brought up on its repository as it is not maintained by the Cura team (even if fieldOfView is a contributor to Cura).

https://github.com/fieldOfView/Cura-OctoPrintPlugin
