### ISSUE TITLE
5.3.0 wont run with dagoma errors

### ISSUE THREAD

**Issue by Thydurdan** [Ultimaker/Cura#14916]
### Application Version

5.3.0

### Platform

windows 11

### Printer

creality ender pro 3

### Reproduction steps

installed new update and keep getting 
Dagoma_discoultimate_bicolor
Dagoma_neva
Dagoma_magis 
config errors
had been working great till new update

### Actual results

if i reset it, the whole cura goes to (not responding)

### Expected results

not sure 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura errors](https://user-images.githubusercontent.com/128090806/225735248-7629575f-4fb4-49d8-b2fa-0d5f0c93ba96.jpg)

**Comment by MariMakes** [comment]
Hey @Thydurdan,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

It seems like Cura 5.3 ships with updated Dagoma printers to make them available for everyone.
If you've added them in Cura before, these files are now conflicting.

If you want to get rid of the configuration error without losing your settings. 
I suggest installing the Start-up Optimizer plug-in. 
You can find it here:https://github.com/fieldOfView/Cura-StartOptimiser

Good luck!

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
