### ISSUE TITLE
vista previa 5.2.2

### ISSUE THREAD

**Issue by Markpichu** [Ultimaker/Cura#14917]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Artillery x2

### Reproduction steps

1. diseñe un objeto y lo exporte en stl para imprimirlo.
2. abrí UltiMarker Cura y el objeto en "preparado" se veía bien pero cuando le di a vista previa el objeto se veía raro
3. aquí le dejo el objeto porque no se explicar bien
[sin_nombre.zip](https://github.com/Ultimaker/Cura/files/10995212/sin_nombre.zip)
![image](https://user-images.githubusercontent.com/128089752/225736313-28f71c15-3981-46c6-b682-403df590ca7e.png)
![image](https://user-images.githubusercontent.com/128089752/225736383-180b4998-1470-410c-ade8-ad6eebf6def2.png)

### Actual results

el objeto tendra fallos

### Expected results

el objeto abría salido bien y podría imprimirlo sin ningún problema

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Gracias por gastar su preciado tiempo para ayudarme

**Comment by MariMakes** [comment]
Hey @Markpichu,

Lo siento, no puedo hablar español, pero creo que puedo ayudarte.

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I don't see anything that's strange. 😅  

The dark and light blue lines will not be printed.
Those are the travels that the nozzles will make, you can use these lines to troubleshoot potential stringing. 
If you don't want to see them, you can uncheck this checkmark in the color scheme preview. 
![image](https://user-images.githubusercontent.com/40423138/226688062-80db59a3-f8ec-4a3f-aad9-f0559f773ce8.png)

Does that solve your problem?
