### ISSUE TITLE
Layer height top/bottom/infill settings not changing layer height

### ISSUE THREAD

**Issue by cutmoney** [Ultimaker/Cura#14934]
### Application Version

5.3.0

### Platform

Mac

### Printer

Ender 3 Max Neo

### Reproduction steps

1. Tried adjusting the top/bottom/infill layer thickness and layer number to a value which should have changed the layer thickness for the corresponding layers.
2. Tried enabling and disabling Adaptive Layers

### Actual results

The layer thickness remains constant based only on the Quality settings of Layer height and Initial Layer Height.

### Expected results

Layers thickness should adjust according to the calculation in top/bottom/infill thickness. For example, If I set the top thickness to 1.0 and set 10 layers, the top 10 layers should be a .1mm thickness, but they remain at the same thickness as the main "Layer Height" settings.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/4040591/226001323-ae44f4ae-89a1-43c2-819c-257e57d843a5.png)

![](https://content.invisioncic.com/ultimake/monthly_2023_03/Screenshot2023-03-17at10_39_10AM.png.e3ce62a649f022d793359ec773df1ad6.png)

**Comment by Asterchades** [comment]
The Top/Bottom Thickness settings (including child settings) don't adjust the layer height of the features, nor are they meant to. They adjust the total height of the feature in question - it's the value used to calculate the number of layers involved, which you've mostly overridden anyway.

Only Infill and Supports have a separate Layer Thickness setting, both of which include reference to the layer thickness in their name. These allow you to make those features a number of standard layers thick, automatically rounding up to the next whole layer.
