### ISSUE TITLE
Fuzzy Skin failing to "fuzz" on one face

### ISSUE THREAD

**Issue by plantar9998372** [Ultimaker/Cura#14933]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Loaded a simple pot.  Added fuzzy skin, but the right hand side is not fully applying "fuzzy".  About 2/3 of it is fuzzing, the rest is smooth.
I have closed the app and reloaded the model, but it's repeatable.
[Plant_Pot_Square_2in.zip](https://github.com/Ultimaker/Cura/files/11004607/Plant_Pot_Square_2in.zip)

### Actual results

Skin on one side is not fuzzy

### Expected results

All outside skin should be fuzzy

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

None

**Comment by Amador1999** [comment]
when fix this problem???
