### ISSUE TITLE
"Limit Support Retractions" option is missing in Cura 5.3

### ISSUE THREAD

**Issue by anthacdc** [Ultimaker/Cura#14940]
### Application Version

5.3

### Platform

Windows 10

### Printer

S1 Pro

### Reproduction steps

I was getting some stringing between supports so i went to disable the "limit support retractions" but noticed it was missing from Cura 5.3 even with all items selected from a menu visibility point of view.

### Actual results

limit support retractions option does not appear

### Expected results

limit support retractions should appear as a option (tickbox)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/128193562/226067837-c874b6bb-f53a-481f-a6da-d0592b503229.png)

**Comment by GregValiant** [comment]
I had read that "Limit Support Retractions" would be removed from Cura.  I don't recall the reasoning but maybe it was interfering with other code.
So this isn't a bug and I'll remove the label and close this ticket.  You could change this to a feature request if you want it back.
