### ISSUE TITLE
wont let me change material AT ALL

### ISSUE THREAD

**Issue by arbuckletabatha** [Ultimaker/Cura#14959]
### Application Version

5.3.0

### Platform

WINDOWS 10

### Printer

ENDER 3 NEO

### Reproduction steps

i CHANGED THE NOZZLE SIZE & IT CHANGED THE MATERIAL. when EVER I DO THAT IT NEVER LETS MER CHANGE THE MATERIAL NO MATTER WHAT I DO IT WON'T ALLOW ME TO CHANGE IT!!!

### Actual results

NOTHING HAPPENS!!!!

### Expected results

I should be able to change it no matter what.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NOTHING WORKS EVEN ADDINA MATERIALS DOESN'T WORK!!!!

**Comment by MariMakes** [comment]
Hey @arbuckletabatha,

Welcome to the UltiMaker Cura Github 🚀 
Sorry to hear you are stuck 😞 
What were you trying to print? 

A common error we see in people encountering this is that they changed the Gcode flavor of their printer to something like Ultimaker-2. Can you check for us if you have the correct gcode flavor? 
You can check this by clicking Manage Printers | Machine Settings | G-code Flavor. 

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
