### ISSUE TITLE
Cura 5.3.0 - Maschine settings notice box at "Start G-code" & "End G-code" covers input & not scrollable

### ISSUE THREAD

**Issue by Gerhard-59** [Ultimaker/Cura#14963]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic Kobra

### Reproduction steps

1.) When you hover with the mouse over the input fields of "Start G-code" & "End G-code" the notice box covers the whole window as long as you move the mouse outside. The notice box disappears when the mouse is outside this input fields.

2.) The notice box of  "Start G-code" & "End G-code" are not scrollable.

### Actual results

1.) There's no possibility to push the notice box away to have a reference for the possible input.

2.) They contain more information as what can be displayed in the box.

### Expected results

1.) Please make the notice box movable.

2.) Please make them scrollable.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

see also https://community.ultimaker.com/topic/43071-ultimaker-cura-53-stable-released/?do=findComment&comment=320441

![2023-03-19_20h26_33](https://user-images.githubusercontent.com/91338720/226205165-24166fc9-5630-45af-a80d-383a6b7a5120.png)

**Comment by 5axes** [comment]
It's a not a issue from Cura but from the plugin  **Cura Settings Guide** : 

https://github.com/Ghostkeeper/SettingsGuide/issues/89
https://github.com/Ghostkeeper/SettingsGuide/issues/108
https://github.com/Ghostkeeper/SettingsGuide/issues/105
https://github.com/Ghostkeeper/SettingsGuide/issues/103
https://github.com/Ghostkeeper/SettingsGuide/issues/95

To temporarily (or permanently) solve the problem, do not use  : **Show articles in setting Tooltips**  In the plugin Preferences

![image](https://user-images.githubusercontent.com/11015345/226330392-8639ef7a-2a89-413e-a133-b9f606148857.png)

**Comment by MariMakes** [comment]
Hey @Gerhard-59,

Welcome to the Ultimaker Cura Github 🚀 

This is related to the Settings Guide Plug-in.
People who don't have that plug-in installed, like me, just see this as tooltip:
![image png 3b035a438239486e10cf0668a60e32e2](https://user-images.githubusercontent.com/40423138/226335635-26d425f1-e629-4113-be9b-d1797fe02ada.png)


You can temporarily disable your plug-in in the marketplace by clicking the gear in the top right corner and then disable.
If you are done editing your gcode you can enable it again. 
![image png b18c43bd0ef1817ab6f0bd2d48fe61d5](https://user-images.githubusercontent.com/40423138/226335695-d9882a06-39be-4ff6-9702-734d9244c2ec.png)

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by Gerhard-59** [comment]
Hello MariMakes,

Thank you for your fast reply.

As I don't want to modify this G-code before and after every day I can live with your suggestion to temporarily disable the plugin as a workaround.

But, in general the issue is not solved, because when someone wants to use this guide, it should work so that one can read and also copy the examples.

I would agree to shift this issue to the thread of the plugin.

sent from my Huawei P30 Pro with MailDroid

Gerhard Eckert
Oberweihersbucher Str. 5
90522 Oberasbach
Tel: +49 911 697886
mob: +49 173/8288 661
email: ***@***.***

-----Original Message-----

**Comment by MariMakes** [comment]
Thanks for getting back to us @Gerhard-59.
Good luck with editing the start/end gcode! 💪 
I'll close this issue.
