### ISSUE TITLE
Cura 5.3 cannot launch UI

### ISSUE THREAD

**Issue by chsjm** [Ultimaker/Cura#14968]
### Application Version

5.3.0

### Platform

windows11

### Printer

None

### Reproduction steps

I installed Cura 5.3, and try to launch it, it just showed the splash screen, but  no  UI, just a Cura icon in the windows taskbar 

### Actual results

the Cura cannot launch, only a splash screen, no UI, just a Cura icon in the windows taskbar
![image](https://user-images.githubusercontent.com/58614506/226264088-eaa0bf61-e358-4239-a3d3-7fd2d997608c.png)

### Expected results

launches normally.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[stderr.log](https://github.com/Ultimaker/Cura/files/11014751/stderr.log)
[cura.log](https://github.com/Ultimaker/Cura/files/11014753/cura.log)

**Comment by MariMakes** [comment]
Hey @chsjm,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I'm sorry to see you are stuck.

I have a couple of questions to narrow it down.
	1. Do you have multiple monitors? Does Cura start if you disable one of the monitors? 
	2. Can you try our nightly build? It has some fixes for multiple monitors: https://github.com/Ultimaker/Cura/discussions/15098?
	3. Do you have two monitors placed above each other? Can you try this workaround from the community? https://community.ultimaker.com/topic/42633-cura-522-stopped-working/#comment-318105
	4. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
	5. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
	6. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665

If you are still stuck, please let me know, I'll take another look. 
Good luck!
