### ISSUE TITLE
Print parameters  why lost？

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#1497]
Print parameters set up after the restart the print software found before all the settings are lost, each need to re-set, cura2.3 and cura2.4, win7 64-bit。

**Comment by nallath** [comment]
Do you have some log files? or a project file?

**Comment by Ghostkeeper** [comment]
Could be a bug in the upgrade plug-in for 2.4.

**Comment by ianpaschal** [comment]
No info was provided.
