### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#1498]
The Cura repository currently has 46 branches, many of which have already been merged or will never be merged. This includes a couple of mine, but I am no longer allowed to remove these branches.
* fix_unsupported_materials_warning
* fix_um2p_profilenames
* feature_black

Other branches that have already been merged: smartavionics-mb-anchor-skin-in-infill, feature_auto_slice, feature_temp_disable, python_type_hinting, feature_preheat_bed, single_instance, layer_view3. And those are just the "active" branches.

Time for some spring cleaning?

**Comment by nallath** [comment]
I've killed all the branches you mentioned. It's a good start at least. I also noticed that i have a ton of local branches that need purging. Better get started with that as well.

**Comment by nickthetait** [comment]
I agree, quite a kerfuffle at the moment :stuck_out_tongue:  Might add a step to the end of your release process to prune the old ones.

**Comment by BagelOrb** [comment]
I agree.
My usual cycle is 
```
git log some_branch ^master  --pretty=oneline
#if result is no commits then:
git push origin :some_branch
git branch -D some_branch
```

I think it's better not to automate this, because you might want to keep some branches a bit longer sometimes, even when they are already merged.

**Comment by BagelOrb** [comment]
Also: there's too many open issues which can be closed. Keeping github clean means that contributors have clear information and we have clear information on what the community wants or the bugs they ahave found which haven't been solved yet.

**Comment by fieldOfView** [comment]
These branches are from PRs that have been merged:
```
python_type_hinting
recommended_sidebar
```

The following branches have no commits ahead of master (so they were also merged):
```
feature_omp_writeGcode
feature_z_seam_location
feature_recursive_cubic
feature_alternate_carving
feature_bed_adhesion_none
feature_precool
feature_fan_speed_0
feature_extruder_temp_layer_0
feature_wall_wipe
feature_anti_support
feature_infill_support
feature_retract_at_layer_change
feature_bed_temp_layer_0
feature_concentric_3d_infill
feature_better_warning_formulas
feature_resolvement_functions
bugfix_global_inherits_stack
```
Note they are (allmost?) all @BagelOrb's branches, so somewhere there's a workflow merging his stuff that is not working out.

Finally, these branches are from PRs that have been retracted:
```
robo_c2
thopiekar-unity-workaround
bugfix_legacy_importer
```

Together that's 22 unnecessary branches.

**Comment by nallath** [comment]
@BagelOrb usually doesn't make pull requests, so then there is no reminder to remove old branches. I think we should indeed have a workflow change (eg; always use a pull request)

**Comment by awhiemstra** [comment]
I have gone through the branches and deleted a bunch of them. Branch count is now down to 17 with most of these being active, release, or PR related branches.

**Comment by BagelOrb** [comment]
@fieldOfView You still got privileges?! O_O

Uhmmm @Ghostkeeper .....?

**Comment by BagelOrb** [comment]
oh wait nvm. Everybody can open tickets of course! :P

**Comment by fieldOfView** [comment]
It is that time again... The following branches have no commits ahead of master:

feature_try_line_widths
CURA-5135_fancy_fix 
feature_gzgcode_writer
CURA-4800_test_opengl
CURA-4916_infill_sidebar_update
CURA-4968_support_eraser_on_platform

**Comment by Ghostkeeper** [comment]
I cleaned those up again.
