### ISSUE TITLE
Support breaks the brim in dual extrusion setup

### ISSUE THREAD

**Issue by teafusion** [Ultimaker/Cura#14982]
### Application Version

5.3.0 stable

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

1. New project, fast 0.2mm preset, dual extrusion, 0.4mm nozzle for the 1st extruder, 0.8mm nozzle for the 2nd extruder.
2. Load an .stl and **assign it for the 2nd, 0.8mm nozzle**, slice without support, brim turns out like set, 7.0mm and 9 lines.
3. The object needs support though, so enable it and slice again, brim gets narrower than in the settings, lines missing.

### Actual results

Brim gets very narrow when enabling support in some cases, not in every setup or with all supported objects. It seems to vary with the same object too, hard to detect which factor makes the difference, but enabling support makes it anyway in some cases.

### Expected results

Brim should be the width that's in the settings.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[UM3_Support_Brim_Issue.zip](https://github.com/Ultimaker/Cura/files/11026933/UM3_Support_Brim_Issue.zip)
![BrimYesSupport](https://user-images.githubusercontent.com/28002449/226572802-7de25ecf-1bec-4ed4-b2cd-89b004a75d4b.jpg)
![BrimNoSupport](https://user-images.githubusercontent.com/28002449/226572805-243759a1-415e-4f4b-890b-516bdb8ca4e0.jpg)

**Comment by MariMakes** [comment]
Hey @teafusion,

Sorry, it took us a while to get back to you 😞 
I recognize your report! 👍 

It seemed to be resolved with this comment: https://github.com/Ultimaker/Cura/issues/14666#issuecomment-1477909456
In 5.3 we introduced brims that can be printed in multiple materials.
Some people encounter small brims if they have not defined the Build Plate Adhesion Extruder.

I'll close this issue.
