### ISSUE TITLE
No Support Brim if Buildplate Adhesion is set to None. 

### ISSUE THREAD

**Issue by Chad541121** [Ultimaker/Cura#14983]
### Application Version

5.3.0

### Platform

Window 10

### Printer

Ender 5 Plus

### Reproduction steps

My ticket was closed without being resolved.
There is a setting that breaks the conical support brim.
No support brim is generated when the value is greater than zero.
I have figured out that when Build Plate Adhesion Type is set to NONE, then support brim does not work.
[Speaker Cover no support brim when build plate adhesion set to NONE.zip](https://github.com/Ultimaker/Cura/files/11028155/Speaker.Cover.no.support.brim.when.build.plate.adhesion.set.to.NONE.zip)

### Actual results

No support brim is generated.
![Build Plate Adhesion Type NONE](https://user-images.githubusercontent.com/48022180/226603899-afddecd2-b37c-4c11-ad3c-1b33e880a1d4.jpg)

### Expected results

Build Plate Adhesion Type set to none should not remove support brim.
I may be wrong, but I would think one should be able to have support brim without model brim. 
![Build Plate Adhesion Type anything other than NONE](https://user-images.githubusercontent.com/48022180/226603938-c1d38c2b-7fe6-4f89-9227-471409cd0480.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This issue is in reference to a recently closed issue #14789 
Claiming the issue was fixed.  Please see above documentation showing the problem still exists.
If I set the Build Plate Adhesion to brim and then set Brim line count to zero, It still adds a single brim to my model, however all of my support brim is now generated.

**Comment by MariMakes** [comment]
Hey @Chad541121,

Thanks for your report 👍
I apologize for closing your other bug,  I can clearly see what is wrong here. 
If buildplate adhesion is set to none, than there is no support brim. 

![image](https://user-images.githubusercontent.com/40423138/229515170-4af462c5-08ca-44a8-85b9-3455dbd5f1e9.png)

It seems that an easy workaround here is setting your adhesion to skirt.
Can you share why it's important that you adhesion is set to none? 

I'll bring it up to the team to see what they can do to improve it. 
But I expect that if it's not a quick fix that it will not get a high priority to implement. 
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @Chad541121,

I brought your issue up with the team. 👍 
We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10502

Good Find! 👍

**Comment by ZedOud** [comment]
I'm not sure if this was the case in 5.3.0 but in 5.4.0, Instead of "None" you can also trigger the bug by doing this:
1. Select "Skirt" for Build Plate Adhesion.
2. Set Skirt Line Count to 0
3. Set Skirt/Brim Minimum Length to 0

**Comment by jxer** [comment]
wow this is a terrible response, why should i was filament using skirt if I don't need it? this worked in 5.1.1 without issue

**Comment by MariMakes** [comment]
Quick update from our side.
We were able to resolve the issue here: https://github.com/Ultimaker/CuraEngine/pull/1917

That means that we can have a fix for this problem in the upcoming release.
Thanks for all the reports, apologies for the inconvenience 🙏
