### ISSUE TITLE
[OS X] 3D view only uses part of available space

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#15]
As a user I'd like to see my platform and 3D models in all of their glory :)
The 3D view only uses a part of the space that is available.

Where: Main interface

Actions: Using [the 15.05.92 Darwin](http://software.ultimaker.com/Cura_closed_beta/15.06/Cura-15.05.92-Darwin.dmg) release.

Behavior: Just upon opening. When resizing the window there are changes, but it always cuts off the view which uses a part of the available screen real estate.

Expected behavior: The window should have  the 3D view using the max of the size available.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/191236/7858984/218122bc-053d-11e5-96f6-bc8588d90f6b.png)

Specs: OS X 10.10.3

**Comment by ErikDeBruijn** [comment]
It's present on this Macbook with Retina, indeed. I saw it worked fine on an older Mac without retina.

I can test for you if you have a release that should work with Retina screens.

**Comment by awhiemstra** [comment]
This should be fixed with the new 15.05.93 build

**Comment by oliv3r** [comment]
So this might be a hidpi issue. Ill check under linux with hidpi to see of it happend there aswell

On June 3, 2015 8:19:12 PM CEST, Erik de Bruijn <notifications@github.com> wrote:
>It's present on this Macbook with Retina, indeed. I saw it worked fine
>on an older Mac without retina.
>
>I can test for you if you have a release that should work with Retina
>screens.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Ultimaker/Cura/issues/15#issuecomment-108556226

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ErikDeBruijn** [comment]
@awhiemstra the .93 version fixes it! Great job!
