### ISSUE TITLE
The model is reduced after slicing

### ISSUE THREAD

**Issue by passkal** [Ultimaker/Cura#15000]
### Application Version

5.3.0

### Platform

windows 10

### Printer

KingRoon KP3S

### Reproduction steps

I loaded the model, made the scale 101%, and the model after slicing was reduced by about half.
After that, I rebooted CURA and rebooted the models, but the problem persisted
![Prepare1](https://user-images.githubusercontent.com/51381842/226999407-f40448ab-0d48-46d7-a5b1-ca0443c12e36.jpg)
![Preview1](https://user-images.githubusercontent.com/51381842/226999415-d848a332-caf1-4748-b2c7-cfe80040db30.jpg)

### Actual results

Printing also takes place at a reduced scale

### Expected results

I expected that after slicing, the size of the model should not have decreased

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[KK_rezinka.zip](https://github.com/Ultimaker/Cura/files/11043476/KK_rezinka.zip)

**Comment by fieldOfView** [comment]
The "Scaling Factor Shrinkage Compensation" is set to 60% in your "PLEX" profile. Reset that back to 100%.
