### ISSUE TITLE
Slicing failure on a bunny

### ISSUE THREAD

**Issue by carchietaz** [Ultimaker/Cura#15023]
### Application Version

5.3.0

### Platform

Apple

### Printer

Dremel 3D45

### Reproduction steps

1. Loaded .stl file
2. Turned off supports and adhesion
3. Scaled model down to 60%
4. Pressed "SLICE"

### Actual results

Slicing Failed error message appears when the slider is close to finishing
<img width="539" alt="Screenshot 2023-03-24 at 10 41 34 AM" src="https://user-images.githubusercontent.com/128822872/227556771-aa72c2a0-7eea-405a-a3e3-e7cc2a4f45e4.png">

### Expected results

The file to be sliced and it asks me to print / save to disk

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11063427/cura.log)

**Comment by MariMakes** [comment]
Hey @carchietaz,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
