### ISSUE TITLE
cura lost my profile, says file is corrupt

### ISSUE THREAD

**Issue by Salteedogg** [Ultimaker/Cura#15030]
### Application Version

5.3.1

### Platform

windows 10

### Printer

kobra vyper

### Reproduction steps

I just updated my profile, I exited out of cura. I reopened cura about 10 minutes later, it was like everything was wiped, says my profile is corrupt. Is there anyway to recover this?
![Screenshot (5)](https://user-images.githubusercontent.com/98138273/227732740-cae6d9cf-6a60-42cd-87e6-c009323eade6.png)

### Actual results

Nothing is working.

### Expected results

I want my profiles back, many of hours spent in them.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

n/a

**Comment by MariMakes** [comment]
Hey @Salteedogg,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

Are you still stuck? Then I'll need some more information. 
I'll need your configuration folder for troubleshooting.

You can share your configuration folder by:
	1. Go to Help at the top bar of Cura
	2. Select Show Configuration Folder
	3. Select all the folders in there and create a zip OR go up a folder in your folder structure and zip your folder with the correct Cura version
You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
