### ISSUE TITLE
Slice button only appears if recommended print settings selected

### ISSUE THREAD

**Issue by golflands** [Ultimaker/Cura#15050]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Creality Ender 3 S1 Pro

### Reproduction steps

Loaded an STL file and could not slice it when Custom Settings selected. Only the 'RECOMMENDED' button was visible. 'SLICE' would only become visible if the 'RECOMMENDED' button was selected.

### Actual results

Could not slice using custom print settings.

### Expected results

The 'SLICE' button should be visible when custom print settings are selected.
![Missing Slice Button](https://user-images.githubusercontent.com/37853571/227810095-560eb3e3-192e-4f9f-a5f7-c0f3c5e7b704.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Windows 11, Ryzen 9 5900HX CPU (Integrated Graphics), 1 external monitor, Ender 3 S1 Pro, Creality Sonic Pad. . Cura works fine with 5.2.2.

**Comment by MariMakes** [comment]
Hey @golflands,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

You can resize your setting window with a resize handle. 
Could it be that your slice button is hidden behind the window?
![ezgif-2-9d4ac6d2fb](https://user-images.githubusercontent.com/40423138/230087931-fe4a5d89-111f-46f4-8332-49bb13e978fb.gif)

If the handle is stuck you can consider resetting your Cura. (like it was before I made this gif)
Caution: Resetting Ultimaker Cura removes all configurations, including machines, profiles, and preferences. Ensure any important information is backed up before continuing.

This is how you reset your Cura: 
- Quit the application
- In a file explorer window, navigate to:
- My Computer/users/[user_name]/AppData/Local/cura
- My computer/Users/<your username>/AppData/Roaming/cura
- Delete the entire 'cura' folder of your current version. Note: Cura folders of previous versions will be imported if not deleted!
- Open Ultimaker Cura. If it has been reset correctly, you will be greeted with the onboarding flow

Can you let us know if this get's you unstuck?
