### ISSUE TITLE
slicing bug

### ISSUE THREAD

**Issue by 3deed** [Ultimaker/Cura#15063]
### Application Version

5.2.1

### Platform

windows 10

### Printer

ultimate maker cura

### Reproduction steps

slicing

### Actual results

did not slice

### Expected results

slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

report
![slice](https://user-images.githubusercontent.com/129133320/228108306-8ecefd2f-4381-4d93-a284-6c61ecfedccc.jpg)

**Comment by discip** [comment]
@3deed
> * [x]  Log file
> * [x]  Project file

Despite checking both boxes, you did neither!

Please attach the corresponding log file and project file.
