### ISSUE TITLE
Printed model with Cura 5.3 has lines in z-direction

### ISSUE THREAD

**Issue by InScene** [Ultimaker/Cura#15062]
### Application Version

5.3

### Platform

Windows 10

### Printer

Ender 3 S1 Pro with Sonic Pad

### Reproduction steps

I have sliced and printed the following model in Cura 5.3 [Thingiverse Egg](https://www.thingiverse.com/thing:4812640?fbclid=IwAR3HP7bMX7UPPCIjnLl7YwNSOzucalk7VCRIJFZ-PiQb_PUy5_TNl7uZCJM)
Everything looked good in the sliced preview.

### Actual results

It was printed with two lines in each of the four directions.
I printed a cylinder with the same dimensions and the same settings in Cura 5.3 and it was fine and had no lines.
The problem only occurs with this Thingiverse model in Cura 5.3.

### Expected results

A print without lines in each of the four directions. (Of course, there is a line for the Z seam).
I switched back to version 5.2.2 and printed the same model with the same printer profile and settings. And this print was good and has no lines.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads
**Print error in Cura 5.3**
![Error_print_bottom_Cura-5-3](https://user-images.githubusercontent.com/13087847/228066865-2789ec90-0ae9-4f66-ba4a-c5a0bf83ac1e.jpeg)
![Error_print_top_half_Cura-5-3](https://user-images.githubusercontent.com/13087847/228066871-71eb21ad-b55e-4df9-ae1b-29692bfd6e3b.jpeg)
![Error_print_top_Cura-5-3](https://user-images.githubusercontent.com/13087847/228066866-d891f602-882a-47f1-b4d1-55df0a72e0ac.jpeg)
**Sliced model in Cura 5.3**
![IMG_5428](https://user-images.githubusercontent.com/13087847/228440063-e69e018b-6881-47e5-a88c-c21240841c05.JPG)
![Sliced_model_Cura-5-3](https://user-images.githubusercontent.com/13087847/228067223-5df20fd4-a1b6-4fca-a99f-8d8365da7d89.JPG)
**Error-free test print of a cylinder in Cura 5.3 with the same settings as the model**
![Zylinder_print_with_same_settings_Cura-5-3](https://user-images.githubusercontent.com/13087847/228067254-29361b6f-1ce6-4c19-805c-2cdc3c5b5729.jpeg)

**Good printing of the model in Cura 5.2.2 with the same settings as in Cura 5.3**
![Good_print_Cura-5-2-2](https://user-images.githubusercontent.com/13087847/228066862-4d5eec3b-488f-4f00-beac-0d64cf7716d0.jpeg)

[Cura_project.zip](https://github.com/Ultimaker/Cura/files/11083045/Cura_project.zip)

**Comment by Fritzo81** [comment]
Have the same issue!

**Comment by discip** [comment]
Duplicate of #14811!

**Comment by discip** [comment]
Seems to be a duplicate of #14811!

**Comment by InScene** [comment]
@discip I do not believe that this is a duplicate of #14811. It may be the same cause, but the error behaves slightly differently. I did not see any errors in the slicer as is the case in #14811. The errors were only present in the print.

**Comment by discip** [comment]
@InScene
These artifacts are barely noticeable in Cura.
In order to be able to perceive the "deformations" in Cura, you have to zoom in and look very closely.

Please refer to this comment [jagged paths](https://github.com/Ultimaker/Cura/issues/14811#issuecomment-1462937823).

Were you able to spot the _**'cuts'**_ in the marked areas?

**Comment by InScene** [comment]
@discip Okay, then I guess you are right. Then I'll close this topic and refer to the other topic. 

**Closed due to duplicate of #14811**
