### ISSUE TITLE
Tetrahedral infill dense

### ISSUE THREAD

**Issue by Dilbert1** [Ultimaker/Cura#1506]
Hi,
Tetrahedral infill is not the same density like the other infills.
I think it's round about the half of them.
20% Infil terahedral is ~ 10% cubic pattern.

**Comment by BagelOrb** [comment]
Good catch!

**Comment by BagelOrb** [comment]
Verified.

**Comment by BagelOrb** [comment]
Internal ticketing system: CURA-3474

**Comment by BagelOrb** [comment]
fixed
