### ISSUE TITLE
fan redefinition does not work with cover/bottom template concentric

### ISSUE THREAD

**Issue by gumileeev** [Ultimaker/Cura#15079]
### Application Version

5.2.1 5.3.0

### Platform

win10,64

### Printer

FBG5

### Reproduction steps

1. I activate support
2. activate the option "override fan speed"
3. template for cover/bottom choose "concentric"

### Actual results

The fan does not turn on when laying the first layer, which lies on the support

### Expected results

I expect the fan to turn on, on the layer that comes after the support, as it does if you set the pattern to cover/bottom "lines". But if you set the cover / bottom template concentric - the fan does not turn on

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am printing a model with supports, select the "override fan speed" option - if the cover/bottom template is set to "concentric" - the fan will not be activated for the first layer after the support. If you set the "line" cover/bottom template, the fan will turn on.
**I see a big problem in the fact that the preview is not available for the fan. Please add fan operation to the "preview" menu. Without this, it is impossible to check the correctness of the cooling settings of the model in the right places. Before the model starts printing :(**

**Comment by MariMakes** [comment]
Hey @gumileeev,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I believe this might just be a setting issue. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
