### ISSUE TITLE
Cura doesnt start properly

### ISSUE THREAD

**Issue by Embells** [Ultimaker/Cura#15077]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Ender 3 S1

### Reproduction steps

1. I searched cura in search bar
2. I clicked open button

### Actual results

3. cura loading screen popped out
4. loading screen stopped working
5.  cura doesnt open

### Expected results

cura must start

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/114401127/228554365-b6fe75a4-b649-468a-81da-9d00dc48a696.png)
loading screen stops on that

**Comment by MariMakes** [comment]
Hey @Embells,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, to hear you are stuck 😞, is that still the case? 

If you are still stuck, can you please try this Nightly Build? 
We believe it resolves a number of things, including your booting problem.
You can download it here: https://github.com/Ultimaker/Cura/discussions/15098

Can you let us know if this resolves your issue?
If that's not the case please also let us know so we can take another look.
