### ISSUE TITLE
Skirt is printed AFTER support on first layer

### ISSUE THREAD

**Issue by Edocecrous** [Ultimaker/Cura#15088]
### Application Version

5.3.0

### Platform

Linux 64

### Printer

Anycubic Predator

### Reproduction steps

Load model
Hit slice

### Actual results

The model is sliced, but the order is not correct, first the support is printed, then the skirt, then the model on the first layer.
![image](https://user-images.githubusercontent.com/80519926/228771528-59ee4bdd-5adb-44e1-ada9-f3af6dbfbb7d.png)

### Expected results

In Cura 5.2.1 it works correctly,
Does the skirt first,
then the support (tree support)
then the model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[NanoSD15fdmE.3mf.zip](https://github.com/Ultimaker/Cura/files/11109318/NanoSD15fdmE.3mf.zip)

**Comment by MariMakes** [comment]
Hey @Edocecrous,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Thanks for your report 👍
That definitely looks like a bug on our side. 
It might be related to whatever introduced https://github.com/Ultimaker/Cura/issues/14983 in Cura 5.3

I'll bring it up to the team to see what they can do to improve it.  
Fingers crossed 🤞

**Comment by TommySchwartz** [comment]
I have the same problem in Cura 5.4.0, Windows 10.
Support prints before skirt.

**Comment by MariMakes** [comment]
Hey @Edocecrous,

I discussed your issue with the team, it's serious enough that we want to try to resolve it. 
We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10872

Thanks for the report! 👍

**Comment by Edocecrous** [comment]
[Plug_funnel.zip](https://github.com/Ultimaker/Cura/files/12238791/Plug_funnel.zip)
Just rotated it so supports are needed, and even on preview the support is printed first.
Cura 5.4.0, Linux

**Comment by saumyaj3** [comment]
> [Plug_funnel.zip](https://github.com/Ultimaker/Cura/files/12238791/Plug_funnel.zip) Just rotated it so supports are needed, and even on preview the support is printed first. Cura 5.4.0, Linux
> 
> btw, The windows user who reported same problam was not me, i"m the original reporter. ![image](https://user-images.githubusercontent.com/80519926/257776836-892b679b-48d9-4934-adba-539297c79d66.png)

Hey! Thanks for another test case. I was asking to another user, so that I can have the issue recreated for another machine too. Anyway, this issue should be fixed in the later release. Thanks for your report :) 👍
