### ISSUE TITLE
Mini Countryman X Ride front

### ISSUE THREAD

**Issue by Grueschnuez** [Ultimaker/Cura#15089]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 6

### Reproduction steps

Hello
i tried to slice the Mini Front and then it marks me " The highlitet Aereas
indicate eighter missing or extraneus Surfaces.
Fix your Model and open it again into Cura "

### Actual results

on some Friends Slicer it works.

### Expected results

.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

.

**Comment by GregValiant** [comment]
That model is broken.  You can try fixing it with Blender or MS 3D Builder.  Errors in the model fool Cura and so the slicing stops (as it should).
I'll go ahead and close this as it is a model problem rather than a Cura problem.  I hope you understand.
