### ISSUE TITLE
Crashing out

### ISSUE THREAD

**Issue by Gtrshop** [Ultimaker/Cura#15096]
### Application Version

5.3

### Platform

WIN10

### Printer

Ender 5

### Reproduction steps

SLICE. Thats it I jsut sliced

### Actual results

It stops slicing and tells me to submit a bug

### Expected results

I dont know. I guess it should slice the file and then let me save.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/95543140/229007274-975f06bc-4f50-41e5-8732-41f92f5fba34.png)
[CE5_AAA_to_AA_V3.zip](https://github.com/Ultimaker/Cura/files/11117600/CE5_AAA_to_AA_V3.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This sliced for me on the first try so I cannot duplicate the behavior.  You may have a faulty installation.  Use the "Help | Show Configuration Folder" command and you will find the Cura.log file.  Zip that file and post the zip folder here.  Hopefully something in the log will point to the problem.
