### ISSUE TITLE
how create my plugin for cura ?

### ISSUE THREAD

**Issue by d1ms** [Ultimaker/Cura#1509]
Hello, i have files .py from my plugin, how i can getting files .pyc ?

I read https://github.com/Ultimaker/cura-build , but i don't understand.

What's the simple way compile file ?

**Comment by LipuFei** [comment]
Hi @d1ms , when you import a python module, compiling `.py` to `.pyc` will be done automatically, so there is no need to do this manually.

It should just work if you put your plugin into the `plugins` directory. Make sure your `__init__.py` contains the correct information.

**Comment by d1ms** [comment]
Good evening @LipuFei, i take standart plugin `LocalFileOutputDevice ` and edit only `LocalFileOutputDevicePlugin.py`. Plugin will be automatically refresh folder `__pycache__` ?

**Comment by LipuFei** [comment]
Hi @d1ms, you don't need to worry about `__pycache__`. It just makes compiling python code a bit faster.

In your case, suppose you want to duplicate the `LocalFileOutputDevice` plugin and create a new one called `LocalFileOutputDeviceTest`, you can use the following steps:

1. Duplicate the `LocalFileOutputDevice` directory in the `plugins` directory
2. Edit `__init__.py` at least to rename plugin name (I named it `Local File Output Device (Test)`)
3. Save and start Cura
4. Go to menu `Preferences -> Configure Cura -> Plugins`.
5. You should be able to see the new plugin `Local File Output Device (Test)` in the list

<img width="683" alt="custom-plugin" src="https://cloud.githubusercontent.com/assets/2630468/23739940/80746d64-04a1-11e7-81cf-71c427b92bf2.png">
<img width="541" alt="new-plugin-demo" src="https://cloud.githubusercontent.com/assets/2630468/23740199/d3eeeeb4-04a2-11e7-8710-5398a20ee000.png">

**Comment by Ghostkeeper** [comment]
If you change the .py file, Python will automatically update the version in `__pycache__` the first time you run or import the file.

**Comment by d1ms** [comment]
All thanks!
