### ISSUE TITLE
"CuraEngine.exe has stopped working" on loading STL (Cura 15.06.02)

### ISSUE THREAD

**Issue by Fuzionist1** [Ultimaker/Cura#151]
1. Opened a basic STL file in Cura 15.06.02 (Shared on my Dropbox - https://www.dropbox.com/s/k1giwgx0szb3caw/Fan_Baseplate.stl?dl=0)

2. Error pop-up "CuraEngine.exe has stopped working" (see attached Capture.png)
![capture](https://cloud.githubusercontent.com/assets/13238025/8749786/cc0806a0-2c71-11e5-80b7-0f478dfdc096.PNG)

Notes:
- No error when opening in Cura 15.06.01
- STL was created in Fusion 360

**Comment by awhiemstra** [comment]
This is a bug in the engine as far as I can tell. I get this backtrace:

#0  0x00000000004f8856 in std::vector<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> >, std::allocator<std::vector<ClipperLib::IntPoint, std::allocator<ClipperLib::IntPoint> > > >::size() const ()
#1  0x00000000004f7b94 in cura::Polygons::size() const ()
#2  0x0000000000501ecf in cura::CommandSocket::sendPolygons(cura::PolygonType, int, cura::Polygons&) ()
#3  0x0000000000523055 in cura::FffPolygonGenerator::sendPolygons(cura::PolygonType, int, cura::Polygons&) ()
#4  0x000000000051f568 in cura::FffPolygonGenerator::slices2polygons(cura::SliceDataStorage&, TimeKeeper&) ()
#5  0x000000000051e43a in cura::FffPolygonGenerator::generateAreas(cura::SliceDataStorage&, PrintObject*, TimeKeeper&) ()
#6  0x0000000000504313 in cura::fffProcessor::processModel(PrintObject*) ()
#7  0x000000000050157a in cura::CommandSocket::connect(std::string const&, int) ()
#8  0x00000000005368af in main ()

**Comment by awhiemstra** [comment]
Actually, that was with the master version from the engine. That version has known issues unrelated to this. Testing with the released version of 15.06.02 on Windows 8.1 I get no crashes. Any chance you can list settings that are not set to their default values?

**Comment by Fuzionist1** [comment]
The error was consistent and reproducible before, but not it is not.  You are probably right - it was probably a setting - or combination of settings, and I don't know what they were anymore.  Thanks for your help.
