### ISSUE TITLE
Can't import/export printer files in Cura 2.4 (and 2.3.1) 

### ISSUE THREAD

**Issue by jtzemp** [Ultimaker/Cura#1510]
I wanted pull in a profile for a Lulzbot Taz 4 and I couldn't see any obvious way to do it. I googled around and found these links that all either talk about or show screenshots of import/export functionality:
* https://ultimaker.com/en/resources/20441-manage-profiles
* https://ultimaker.com/en/resources/21351-machines-and-profile-settings-cura-2-1-0
* https://ultimaker.com/en/community/23453-cura-230-release-bug-profiles-are-not-importing

When I pull up the manage printers page, I'm missing the import/export buttons:
<img width="775" alt="preferences_and_cura" src="https://cloud.githubusercontent.com/assets/12219/23730074/5e40abae-041a-11e7-8b90-f4f60278c20b.png">

I'm running MacOS 10.12.3. I had the problem first in Cura 2.3.1 and upgraded to 2.4 hoping it was just an issue with that version. The issue is exhibited in both versions.

Also, I tried quitting the app and deleting the `~/Library/Application Support/cura` folder and then starting the app up again to try to rebuild preference/settings like a new install and the problem was there after nuking app prefs as well.

I'm happy to attach the cura.log, but I looked at it and nothing stood out to me as an issue.

Thanks!

P.S.:

I've got the `Cura Profile Reader` and `Cura Profile Writer` plugins:

<img width="784" alt="about_cura_profile_reader_and_preferences_and_cura" src="https://cloud.githubusercontent.com/assets/12219/23730605/2f184c80-041d-11e7-8296-e38c54eda21b.png">

<img width="779" alt="about_cura_profile_writer_and_preferences_and_cura" src="https://cloud.githubusercontent.com/assets/12219/23730617/4095ac82-041d-11e7-9d34-b9857d379723.png">

**Comment by nallath** [comment]
Profiles are quality profiles. These might be tied to a machine, but simply define what "normal" means with regards to settings. 

If you want a machine that's not already in Cura, you will need to make a *.def.json file that describes the properties of that machine.

**Comment by fieldOfView** [comment]
> If you want a machine that's not already in Cura, you will need to make a *.def.json file that describes the properties of that machine.

... or use the "Custom FDM printer" and edit the values in Cura to match your printer.

Note that Lulzbot have (alpha-quality) builds out which include support for their printers:
http://devel.lulzbot.com/software/Cura2/

**Comment by BagelOrb** [comment]
The misunderstanding has been solved.
