### ISSUE TITLE
Seperate monitor causes cura to crash

### ISSUE THREAD

**Issue by TateNeague** [Ultimaker/Cura#15107]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 pro

### Reproduction steps

1. Clicked the cura marketplace button or tried to open the multiply object menu
2. It tried to open on my second monitor

### Actual results

Cura crashes every time that it opens on a separate monitor

### Expected results

Cura marketplace/the multiply menu should open

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (26)](https://user-images.githubusercontent.com/129557420/229239652-2ff09340-da3f-4a00-ba50-c05f79f35100.png)

**Comment by MariMakes** [comment]
Hey @TateNeague,

Welcome to the UltiMaker Cura Github 🚀 
Ah, that shouldn't crash. 😞 

We have an internal version of Cura available that might resolve this issue. 
Can you download it and let us know if it resolves your issue? 

We also have these three workarounds that might help you: 
Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665

Also feel free to let us know if none of these work, and then we'll have another look.
