### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by samuelhood428** [Ultimaker/Cura#15100]
### Application Version

5.3.0

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

loaded stl file
clicked slice 
got error

### Actual results

got error

### Expected results

expected gcode file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11122218/cura.log)

**Comment by MariMakes** [comment]
Hey @samuelhood428,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
