### ISSUE TITLE
project wont slice

### ISSUE THREAD

**Issue by karahump** [Ultimaker/Cura#15116]
### Application Version

5.3.0

### Platform

windows 11

### Printer

ender 3

### Reproduction steps

I uploaded my project into cura and clicked slice and it loads for 5min then fails and says to report bug.

### Actual results

 I am reporting the bug rn

### Expected results

I would like to find out how to slice or covert my stl file into gcode to print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (9)](https://user-images.githubusercontent.com/129624203/229311760-93516801-33bf-40d0-b122-f3c4fd70e628.png)

**Comment by MariMakes** [comment]
Hey @karahump,

Welcome to the UltiMaker Cura Github 🚀 
That looks like a lovely printjob!

Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
