### ISSUE TITLE
Outer border not visible in Cura 5.3.0

### ISSUE THREAD

**Issue by anno0** [Ultimaker/Cura#15117]
### Is your feature request related to a problem?

In Cura 5.2.x there was a gray border displayed in the width of the skirt distance to the part on the build plate.
I marked the border in blue at the attachment.

Is this functionality not available anymore in Cura 5.3.0?

### Describe the solution you'd like

A option to display the border again

### Describe alternatives you've considered

Nothing

### Affected users and/or printers

Anycubic MEGA X

### Additional information & file uploads

![outer skirt](https://user-images.githubusercontent.com/2607705/229314318-b68f46fd-e8ce-4ff2-86ee-0c1eed61e235.png)

**Comment by nallath** [comment]
That is intentional, as the brim will now be cut off if it doesn't fit:
![image](https://user-images.githubusercontent.com/3922611/231164318-0e367032-8a7f-47ff-af5e-770d8cadaf2b.png)
