### ISSUE TITLE
5,3 support problem

### ISSUE THREAD

**Issue by skamlam** [Ultimaker/Cura#15111]
### Application Version

5,3

### Platform

windows 11

### Printer

any printer

### Reproduction steps

try making a support test with the calibration parts plugin using normal supports everywhere
supports will trap the model inside making it impossible to remove even if they can be broken off

### Actual results

supports will trap the model inside making it impossible to remove even if they can be broken off which did not happen with the same settings in any previous cura

### Expected results

the supports should not trap the model inside

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![supports 5,3](https://user-images.githubusercontent.com/129601852/229291519-59b5d5fc-e96d-45b8-9c30-4299bb9a081a.jpg)

**Comment by skamlam** [comment]
Thank you very much ! I totally missed that setting
Fixed the problem.

Dňa st 5. 4. 2023 o 6:22 PM MariMakes ***@***.***>
napísala(a):

**Comment by MariMakes** [comment]
Great! Good to hear your issue has been resolved.
I'll close the issue. Happy printing! 💪
