### ISSUE TITLE
UM version?

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/Cura#1512]
Hi, When I look into cura.qml file 
the tenth line
import UM 1.3 as UM

where did you define the UM version? is that matter?

**Comment by Ghostkeeper** [comment]
I honestly don't know where the 1.3 comes from now, though I've heard it before.

It doesn't really matter, but using 1.3 is always correct. If you use 1.1 or 1.2 then some of the models may not be available in the QML.

**Comment by nallath** [comment]
This is probably already fixed. I can't reproduce this.

**Comment by Ghostkeeper** [comment]
It's basically not a problem but a question where the QML object version numbers come from. They originate from how the object was registered to Qt (usually in CuraApplication or QtApplication).
