### ISSUE TITLE
file names

### ISSUE THREAD

**Issue by XandertheV** [Ultimaker/Cura#15122]
### Is your feature request related to a problem?

File is always saved as the first-loaded model name when saving to removable drive. If there is a "save as" prompt i haven't found how to turn it on. I've overwritten too many files this way

### Describe the solution you'd like

In settings, there could be a check box that enables the "save as" or whatever to wnere i can manually input the file name i would like to be saved to a removable drive. I understand it speeds up workflow to just save it as whatever but I'd like an easier way around it, as it often disrupts my workflow.

### Describe alternatives you've considered

going back and making sure my sd card doesn't have any files of the same name and changing it if there is

### Affected users and/or printers

I think it could potentially affect a lot of people if they had the option the not just automatically save the file to the sd using the first-loaded model name.

**Comment by MariMakes** [comment]
Hey @XandertheV,

Did you get a chance to take a look at the suggestions from @rburema?
I believe that the Printjob Naming is the solution you are looking for. 

Would you still like to keep this issue open or do you agree that we can close it?
