### ISSUE TITLE
Translation (to French)

### ISSUE THREAD

**Issue by AgimaFR** [Ultimaker/Cura#15125]
### Application Version

5.3.0-alpha+xmas

### Platform

MacOS Ventura 13.3

### Printer

Creality CR10-S

### Reproduction steps

1. I went to the Advanced settings
2. I searched for the word "temperature"
3. I changed the temperature of the plate and the printing for the first layer
4. I validated my modification

### Actual results

⚠️ Alcune impostazioni sono state modificate.

Warning message in Italian (French expected) after the temperature change for the first layer.
This is perhaps normal for the Alpha version of Cura.

### Expected results

"⚠️ Some settings have been changed." in English 🇬🇧
"⚠️ Certains paramètres ont été modifiés." in French 🇫🇷

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Just a problem with a warning message that appears in Italian instead of French.

**Comment by MariMakes** [comment]
Hey @AgimaFR,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report, these are super helpful for us! 👍

We are working on improving the translations as we speak and I believe this has been reported before. 
[I believe this is where you can find the translation](https://github.com/Ultimaker/Cura/blob/main/resources/i18n/fr_FR/cura.po#L6214)

Can you confirm if this translation is correct?
msgid "Recommended settings (for <b>%1</b>) were altered."
msgstr "Les paramètres recommandés (pour <b>%1</b>) ont été modifiés."
