### ISSUE TITLE
Poor layouts on modal screens

### ISSUE THREAD

**Issue by N6REJ** [Ultimaker/Cura#15136]
### Application Version

5.3.0

### Platform

win 10x64 pro

### Printer

Voxelab Aquila S2

### Reproduction steps

open a modal window in non full-screen mode.
you'll get a partial layout or poorly laid out window.
change to full screen reopen modal and it will be fine.
THIS IS NOT TRUE for colors.  They are always messed up.

### Actual results

window at roughly 50% 
![image](https://user-images.githubusercontent.com/1850089/229617434-88492485-a722-4f7e-b6d2-04b36b5f38d1.png)
after going full screen
![image](https://user-images.githubusercontent.com/1850089/229617497-f5e6d1e8-80e0-4b3c-90d7-881ce11d7612.png)
![image](https://user-images.githubusercontent.com/1850089/229617577-391c9767-692a-41b3-a697-4a9832927505.png)

### Expected results

![image](https://user-images.githubusercontent.com/1850089/229617505-c1ebede6-0584-44cf-b136-500246149c49.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

sometimes the color modal is so messed up you can't even select all the colors

**Comment by rburema** [comment]
We suspect several issues may be solved with our update of Qt to 6.4 (the library we use to make the GUI). If you whish, you could try if this alpha build solves your issues (warning for bugs, please keep your older Cura around when installing): https://github.com/Ultimaker/Cura/discussions/15098

**Comment by N6REJ** [comment]
@rburema yes it does solve the windows issues.
