### ISSUE TITLE
Slicing not dome

### ISSUE THREAD

**Issue by thingsmart** [Ultimaker/Cura#15159]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Creality CR6 SE

### Reproduction steps

1. Just dropped the .stl as ever
2. Selected parameter
3. The slicing it's not done.

![image](https://user-images.githubusercontent.com/9590781/230441355-0f8ac909-f216-417b-b369-cc8a6867c7e5.png)

### Actual results

![image](https://user-images.githubusercontent.com/9590781/230441433-1a478347-878b-47e2-b8c8-a879766304b6.png)

### Expected results

The slicing done.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11172702/cura.log)
[CCR6SE_Il bro la rana.zip](https://github.com/Ultimaker/Cura/files/11172707/CCR6SE_Il.bro.la.rana.zip)

**Comment by nallath** [comment]
I've not been able to reproduce this with Cura 5.3.0, but I am slicing it on another operating system. Could you try again with Cura 5.3 and let us know if it still fails for you?
