### ISSUE TITLE
Insert stl file into open project

### ISSUE THREAD

**Issue by fastStevie80** [Ultimaker/Cura#15167]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic Kobra Neo

### Reproduction steps

1. I opened a stl file with Ultimaker Cura 5.3.0
2. I imported another stl file
3. 

### Actual results

the two different stl objects were kinda "morphed" into one
![grafik](https://user-images.githubusercontent.com/130143654/230585470-f03aa46a-e413-4f36-82f2-86e83f001d86.png)

### Expected results

The two stl objects should be placed next to another
![grafik](https://user-images.githubusercontent.com/130143654/230585584-6ba2907c-7ee9-40f4-9cee-b3e4090ec4b2.png)

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_OttoDIY_feet_V11.zip](https://github.com/Ultimaker/Cura/files/11177862/CFFFP_OttoDIY_feet_V11.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11177866/cura.log)

**Comment by fieldOfView** [comment]
In the Cura preferences, do you have the "Ensure models are kept apart" setting checked or unchecked?

**Comment by fastStevie80** [comment]
Hello,

thank you very much for this quick response on a holiday...
I didn´t have set this. I never had changed this setting. It worked fine
till the update from Cura 5.2.2 to Cura 5.3.
Maybe it got changed automatically...

Again: Thank you very much and have a good time.

Many greetings!

Am Fr., 7. Apr. 2023 um 13:40 Uhr schrieb Aldo Hoeben <
***@***.***>:
