### ISSUE TITLE
Unable to slice due to unknown error.

### ISSUE THREAD

**Issue by tdshimo** [Ultimaker/Cura#15172]
### Application Version

5.3.0

### Platform

macOS Big Sur 11.7.4 (20G1120)

### Printer

Sovol SV01PRO

### Reproduction steps

1) Imported .stl from Fusion 360 into Cura. Model's refinement set to "High." 2.8MB file size.
2) In Cura, rotated model on two axes to get the proper orientation. 
3) Multiplied the model, then mirrored the multiple. 
4) Attempted to slice; Cura returned error message "Unable to slice due to unknown error." The error occurred on the second attempt. 
5) Error was resolved after closing and restarting Cura.

### Actual results

Cura was unable to slice due to an "unknown error."

### Expected results

Expected a successful slice operation.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11180872/cura.log)
The issue did not replicate upon restarting.

**Comment by MariMakes** [comment]
Hey @tdshimo,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser. 

If your error was resolved after closing and restarting Cura, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
