### ISSUE TITLE
Wire Printing Failed to Slice

### ISSUE THREAD

**Issue by Drommotech** [Ultimaker/Cura#15177]
### Application Version

5.3.0

### Platform

MAC OS

### Printer

Ender 5

### Reproduction steps

Enabled Wire Printing on a bunny model for easter. 

Then got the message "Failed to Slice, unknown error"

### Actual results

Get an error message and Cura wouldn't slice. 

### Expected results

It slices like normal with Wire Printing and I can print =)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Bunny-LowPoly.3mf.zip](https://github.com/Ultimaker/Cura/files/11183444/CE3PRO_Bunny-LowPoly.3mf.zip)

**Comment by nallath** [comment]
We've recently decided to remove the wire-printing altogether. You can see https://github.com/Ultimaker/Cura/commit/5b209161aca23d55a377032182315a5dfe872c58 for a bit more information about this.
