### ISSUE TITLE
Cura 5.2.2 Infill pattern Concentric doesn't work

### ISSUE THREAD

**Issue by Queldaras** [Ultimaker/Cura#15181]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Anet A6

### Reproduction steps

Enabled supports
Selected infill pattern Concentric
Selected support density 100%
Sliced the model
![problem](https://user-images.githubusercontent.com/121657796/230733931-7d19aaaa-b6c3-46ce-b511-82f165eb9300.jpg)

### Actual results

The supports are hollow and are never actually generated.
It only creates the outer walls (2 walls in my case)
Everything else is blank
![problem](https://user-images.githubusercontent.com/121657796/230734511-c9f6bbdc-a4c9-4d7a-8a21-b5cf8797151f.jpg)

https://we.tl/t-we5P60W3nN

### Expected results

Should create the concentric infill pattern and fill the empty space
according to the selected infill density (100% in my case)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://we.tl/t-we5P60W3nN
![problem](https://user-images.githubusercontent.com/121657796/230734539-d4ca5fdb-c760-4cf7-8f1e-87525fd9b96b.jpg)

**Comment by MariMakes** [comment]
Hey @Queldaras,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 
Your WeTransfer link has expired but I can already see some things in your screenshot.

Can you help me understand why you want to use Concentric Infill at 100%?
I can imagine that it will cost a lot of material, and printing time and I can imagine it's hard to remove. 
https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/support/support_pattern.md

Can you check for me what the Gradual Support Infill Steps value is? 
Chances are if the setting is too high, it will not generate the supports you expect. 
![image](https://user-images.githubusercontent.com/40423138/236443794-f2b518dc-69c0-4cc7-90ab-48eb56483f18.png)

Can you let us know if that solves your issue? If not, can you share the project file again?
I'll promise to respond quick enough to download it this time.
Thank you 😊
