### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by thezakfiles** [Ultimaker/Cura#15183]
### Application Version

5.3.0

### Platform

windows 10

### Printer

cr10s using it for anycubic chiron

### Reproduction steps

I have uninstalled the old verison of cura and updated to the lastest software. No matter how many times I reinstall it, the application crashes when I open a file, slice a model or sometimes even when I save to the sd card. 

### Actual results

nothing has been a fix. I don't have Chitubox installed. 

### Expected results

I need it to stop crashing. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

no other uploads

**Comment by MariMakes** [comment]
Hey @thezakfiles,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We'll need a little bit more context to help you troubleshoot.
Do you see a crash window?
The next time you experience a crash, can you do the following things for us:
1. Can you share your log file with us? 
You can find your log file here:Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log
2. If you see a crash window, can you scroll all the way down in the scrollable fields and share a screenshot? 

That would really help us with troubleshooting. Thank you 🙏
