### ISSUE TITLE
Generate Interlocking Structure fails to slice after model rotation

### ISSUE THREAD

**Issue by TCandee** [Ultimaker/Cura#15187]
### Application Version

5.3

### Platform

Windows 10

### Printer

Ultmaker S5 Pro Bundle

### Reproduction steps

I imported 6 STL files, assigned an extruder to each, merged the files.  After the merge completed the model rotated to an odd position, but printable.  The slice engine completes if you do not move it.  

### Actual results

When I move the model the slice engine fails.

I tried to upload the project but the file is too big and the uploader won't accept .3mf files

### Expected results

It should slice even after moving the model

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Capture](https://user-images.githubusercontent.com/49054556/230751499-7a71c19b-fc2f-4a99-9b8f-feb6a03d6e4c.JPG)
![Capture1](https://user-images.githubusercontent.com/49054556/230751501-69635200-708a-4d1b-a287-2feb0532497c.JPG)

**Comment by Vandresc** [comment]
Hi @TCandee, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file_. For big files, you may need to use WeTransfer or similar file-sharing sites._

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

Thank you!
