### ISSUE TITLE
Cura error when slicing

### ISSUE THREAD

**Issue by norbertom8** [Ultimaker/Cura#15194]
### Application Version

5.3.0

### Platform

windows 10

### Printer

Artillery Sidewimder x2

### Reproduction steps

Made it slice this file (change extension to .obj to drop into CURA).
![Brake 3 caliper piston cover 57mm to paint - change to obj](https://user-images.githubusercontent.com/57204038/230790821-b9f8efc1-6b8f-479a-82fb-8395d26b8c8f.png)

Tried to print it with settings STD QLTY #2 (change extension to .curaprofile to import the setting in CURA)
And error ocurred
![Standard Quality #2 - Change to curaprofile](https://user-images.githubusercontent.com/57204038/230790977-3be10eca-b539-4368-b206-b3f03a80d7b0.png)

Thank you

### Actual results

Error occurs

### Expected results

Should print

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Thank you

**Comment by GregValiant** [comment]
I'm unable to download using the links in your post.  Zip the file(s) and post the zip folder here.
