### ISSUE TITLE
Monitor Tab not showing anything

### ISSUE THREAD

**Issue by Arketsu** [Ultimaker/Cura#15193]
### Application Version

5.3.0 

### Platform

Windows 11

### Printer

Creality Ender 3 S1

### Reproduction steps

1. updated to version 5.3.0 monitor tab not showing any buttons, progress or webcam only shows message that says. in order to monitor your print with cura please connect printer.
2. Opened version 5.2.2 no issues at all monitor tab works flawlessly.

More info:
Using octoprint plugin every past version worked fine until 5.3.0

### Actual results

new version wont work only on old version.

### Expected results

monitor tab should work on 5.3.0 but it doesn't.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Edit: after uninstalling Moonraker plugin I was able to fix the problem.... but I use both moonraker for my ender 3 v2 and octoprint for my ender 3 S1. Not sure how to make both work.

Edit: Found a work around. click manage printer,(on the S1 that is the one using octoprint) connect to moonraker  add the ip for the moonraker instance and add the webcam url. Would be nice to find a way to stop both plugins from conflicting.

**Comment by fieldOfView** [comment]
Logs would help diagnose what is going on, but since this is an issue with 3rd party plugins, you are probably going to have to open an issue at the respective plugin issue queues:
https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
https://github.com/emtrax-ltd/Cura2MoonrakerPlugin/issues

**Comment by Arketsu** [comment]
@fieldOfView Just did, thank you.

**Comment by fieldOfView** [comment]
Thanks! I'll put on my other hat and look in to it from the OctoPrint plugin side of things.
Because - for now - this looks like an issue with 3rd party plugins, I will close this issue on the Cura repository.
