### ISSUE TITLE
no funciona bien en la flsun v400

### ISSUE THREAD

**Issue by Curuchi** [Ultimaker/Cura#15204]
### Application Version

5.3

### Platform

Windows 10

### Printer

Flsun v400

### Reproduction steps

No funciona

### Actual results

no funciona

### Expected results

demora el slice y deja de funcionar

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

bad

**Comment by MariMakes** [comment]
Hey @Curuchi,
Lo siento, no puedo hablar español, pero creo que puedo ayudarte.

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
