### ISSUE TITLE
Tap+ AntiWarping- Tabs misplaced or missing

### ISSUE THREAD

**Issue by Gerhard-59** [Ultimaker/Cura#15209]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic Kobra

### Reproduction steps

I've used Tab+ V1.1.0 to prevent warping on some objects.

1.) A soap-box  with bottom and top part, need to be printed together because of the integrated hinges.
I used Tab+ because the first print failed due to warping.

2.) For a fan duct for the Anycubic Kobra I also wanted to use Tab+.

### Actual results

to 1.) When trying to use Tab+, I found, that there are tabs missing, where they should be. See enclosed screenshot

to 2.) I found that same of the generated tabs didn't have contact to the object. 
Tabs where placed at the shadow outline of the object, which is far from the base outline. see enclosed screenshot
Therefore I waved using Tab+ for this object. see

### Expected results

to 1.) there should be additional tabs at the inner corners of the combined object and not only at the outer corners.
![2023-04-10_17h34_43](https://user-images.githubusercontent.com/91338720/231153043-8e4ac8e9-ba91-42a0-a6e7-49b67b5e48c6.png)

to 2.) The tabs should be placed near the base outline of the object.
![2023-03-31_15h55_55](https://user-images.githubusercontent.com/91338720/231153167-41bddc1a-7693-4bac-8525-2f2cc7b3f60a.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project files included.

[Soap_box-GE-Hair_90x65x32.zip](https://github.com/Ultimaker/Cura/files/11200005/Soap_box-GE-Hair_90x65x32.zip)

[AK_kobra_fan_duct_final.zip](https://github.com/Ultimaker/Cura/files/11200009/AK_kobra_fan_duct_final.zip)

**Comment by nallath** [comment]
Issues with Plugins should be reported with their respective authors. In this case you can do that in this project: https://github.com/5axes/TabPlus
