### ISSUE TITLE
Cura 5.3.0 Layer height different in gcode than profile

### ISSUE THREAD

**Issue by LilSpeedDemon87** [Ultimaker/Cura#15206]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Anet A8

### Reproduction steps

I updated Cura from 5.2(I think) to the latest 5.3. I have calibrated my printer to print at layer height .12mm (I have been printing this way since I started). In the gcode that is sliced with my profile of using .12mm layer height, it shows that it is actually producing .16mm layer height looking through the code (even though it says .12mm at top of gcode). I checked several of my old gcodes that I sliced with 5.2 version and verified that they were indeed .12mm layer height. For whatever reason, version 5.3 is producing a different layer height within the code itself of the gcode, after slicing. 

### Actual results

I started having layer issues and the initial first layer wasn't laying down a good "squish" starting with the very first print after updating to 5.3. Releveled bed several times which I don't ever really have any issues with bed leveling or problems with prints sticking.

### Expected results

I should be able to check the gcode and it corresponds to my profile I have created, and should print without issues.
[cura.log](https://github.com/Ultimaker/Cura/files/11196892/cura.log)
[AA8_X_Belt_Holder.zip](https://github.com/Ultimaker/Cura/files/11196894/AA8_X_Belt_Holder.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

The gcodes I have that used Cura 5.2, shows the z starting at .3 and then going to .42 at the next layer, which is .12mm layer height. The gcodes I just produced with Cura 5.3 shows the z starting at .3 and the going to .46 at the next layer, which is .16mm layer height.
![Layer at Z0 46 with Cura 5 3](https://user-images.githubusercontent.com/130431013/231069196-33ff8bc0-cac4-4ff3-9093-74c1162a0fb3.png)
![Layer at Z0 3 with Cura 5 3](https://user-images.githubusercontent.com/130431013/231069199-ee1f8b6b-4c87-45f9-ada9-e0e9e890876b.png)
![Layer at Z0 42mm with Cura 5 2](https://user-images.githubusercontent.com/130431013/231069200-7fe443d4-6e43-4e7e-8b30-649ed153d494.png)
![Layer at Z0 3 with Cura 5 2](https://user-images.githubusercontent.com/130431013/231069204-187fdf40-6fd1-47ea-ae47-7eae486f6477.png)

**Comment by nallath** [comment]
You have the setting "adaptive layer height" enabled, which automatically changes the layer height based on the curvature of your model. If you want a fixed layer height, disable that setting.

**Comment by LilSpeedDemon87** [comment]
Wow, something so simple to make someone feel like an idiot... Thank you so much!

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 11, 2023 at 7:27 AM, Jaime van ***@***.***> wrote:   


You have the setting "adaptive layer height" enabled, which automatically changes the layer height based on the curvature of your model. If you want a fixed layer height, disable that setting.
