### ISSUE TITLE
Slicng Failed

### ISSUE THREAD

**Issue by N0MAD-7567** [Ultimaker/Cura#15208]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

1. loaded in a file that has sliced before but this time i wanted to change the scale slightly.
2. let the system slice automatically as i always do.
3. it failed to slice.
4. i changed my settings so it would not slice automatically.
5. closed cura.
6. opened cura.
7. loaded in my file, scaled it.
8. hit slice.
9. it failed to slice.

### Actual results

![image](https://user-images.githubusercontent.com/69372155/231142467-595692fe-016f-4ba4-9573-bc792d562f5a.png)

### Expected results

it should slice.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am unable to share the files as i dont own the rights to distribute them.

**Comment by MariMakes** [comment]
Hey @N0MAD-7567,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, we'll need the project file for troubleshooting.
Without it, we cannot test if a fix works. 

Can you let us know if these workarounds work for you?
