### ISSUE TITLE
Not slicing manual supports to full height

### ISSUE THREAD

**Issue by Poporacer** [Ultimaker/Cura#15203]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Created cylindrical object with a 90-degree overhang
2. Added manual supports around the circumference.
3. Sliced the file

### Actual results

The supports are only sliced for 4 or 5 layers and then stop. I have printed a few of these that were almost identical and they sliced correctly.

### Expected results

The supports should print up to the overhang they are supposed to support.
[CE3PRO_Jack Cap v2.zip](https://github.com/Ultimaker/Cura/files/11191447/CE3PRO_Jack.Cap.v2.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

File Preview
![image](https://user-images.githubusercontent.com/46263877/230931319-09998cf0-0511-4975-826a-4d947426d73b.png)

Layer 4
![image](https://user-images.githubusercontent.com/46263877/230931603-6f8f0be2-794a-4c58-91cc-3fdb789a9137.png)

Layer 20
![image](https://user-images.githubusercontent.com/46263877/230931718-439ad03a-d121-4a1e-88bc-bec175422b40.png)

**Comment by nallath** [comment]
This is caused by the "Minimum Support Area", which is set to 2mm. At the bottom, it does print them, as the tapered edge makes them go slightly above the 2mm^2 that is the default.

If you change the setting to 1mm^2, it will print the manual supports that you added.

**Comment by Poporacer** [comment]
Thank you, that make sense. I slightly decreased one dimension that probably put it within that minimum...Thanks a million!
