### ISSUE TITLE
Cura not slicing

### ISSUE THREAD

**Issue by APerson43** [Ultimaker/Cura#15214]
### Application Version

5.3.0

### Platform

windows 10

### Printer

anycubic vyper

### Reproduction steps

this error is only occurring for two specific 3d models.
when i hit slice it loads like normal then comes up with an error message saying : "slicing failed with an unexpected error. please consider reporting a bug on our issue tracker
[New Compressed (zipped) Folder.zip](https://github.com/Ultimaker/Cura/files/11202251/New.Compressed.zipped.Folder.zip)

### Actual results

.

### Expected results

.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by Vandresc** [comment]
Hi @APerson43, thank you for your report. I could indeed reproduce the slicing error in 5.3 and it is already fixed for the 5.4 release. I will close this ticket but feel free to reopen it if the issue still occurs with 5.4 (future release).
