### ISSUE TITLE
Island Detection

### ISSUE THREAD

**Issue by tlyates08** [Ultimaker/Cura#15218]
### Is your feature request related to a problem?

Slicing fails to auto detect islands

### Describe the solution you'd like

Island Warning, Overhead angle warning

### Describe alternatives you've considered

None

### Affected users and/or printers

Any printer

**Comment by GregValiant** [comment]
I guess I don't understand.
In the image below the islands are obvious so I know there will be islands because I can see them.
I don't know what an "Overhead Angle Warning" would be.
![image](https://user-images.githubusercontent.com/64202104/231322459-607fb0a1-22b8-4108-be82-0c4c8a0b2714.png)

**Comment by nallath** [comment]
I have the same issue, I also don't really understand what this feature request is about.
