### ISSUE TITLE
multiple files not sliceing

### ISSUE THREAD

**Issue by rprodger** [Ultimaker/Cura#15226]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Ender 5 pro

### Reproduction steps

i have been trying to slice files but they keep comeing up with a un expected error. have tried resetting the slicer but nothing happens

### Actual results

nothing it keeps refusing to slice the file 

### Expected results

the file should be sliced and able to print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

m

**Comment by nallath** [comment]
Thanks for reporting this. We're aware of a number of slicing issues. To figure out if we're talking about the same problem, could you share some of the models that caused this issue for you?
