### ISSUE TITLE
Pause at height

### ISSUE THREAD

**Issue by FabienBoissel** [Ultimaker/Cura#15223]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Je suis habitué à utilise la fonction "Pause at height" (insertion d'écrou métallique) depuis quelques années, j'ai une mise à jour de Cura et du firmware de l'imprimante.

### Actual results

La fonction "pause at height " ne fonctionne plus, l'imprimante ne s'arrête pas. Les impressions que je réalise sont alors non conforme et rebuté

### Expected results

L'imprimante doit s'arrêter au layer number programmer.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Pause](https://user-images.githubusercontent.com/130543256/231684704-d4edf075-38ea-4e4b-a6e8-827cf0f06739.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.
If it is the same printer as you used before, and the pause command worked before, then it really should work now.  Was there a recent firmware update?
Maybe @nallath has some information on this?

**Comment by nallath** [comment]
This was fixed for 5.3.1
