### ISSUE TITLE
Tree support fusing to model

### ISSUE THREAD

**Issue by eldadry** [Ultimaker/Cura#15239]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

Sliced a model with auto tree supports

### Actual results

the tree support fused with the model. I checked the gcode and could see the point where it fused and it shows that the support is too close but only in that one place

### Expected results

You see the fusing in the gcode and real life

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![problem 2](https://user-images.githubusercontent.com/33181626/232034140-fd00e58b-ce37-4678-a2e6-5efad690bcc2.PNG)
how it should be

![problem](https://user-images.githubusercontent.com/33181626/232034145-26739d1d-1330-49a4-8ed2-30df703c1a1e.PNG)
how it is

![IMG_20230414_143735](https://user-images.githubusercontent.com/33181626/232034324-f8ea1050-a9b0-4a19-b212-6ada2123fc3c.jpg)
printed

**Comment by rburema** [comment]
We're doing a big overhaul of the Tree Support feature, which is not yet present in 5.3 -- We'll hopefully have it in 5.4 (fingers crosses), and as such, are no longer updating the to-be-removed older code.

You can check an early preview of the new tree supports here: https://github.com/Ultimaker/Cura/discussions/14111
