### ISSUE TITLE
Buildplate adhesion is not generated properly

### ISSUE THREAD

**Issue by andreikovari** [Ultimaker/Cura#15249]
### Application Version

5.3.0

### Platform

Win10

### Printer

Anycubic Kossel Linear Plus

### Reproduction steps

When slicing a file, when selecting brim or skirt, the contours for both has a missing gap. 
The file was sliced in a previous version of cura and worked fine.
The gap in the buidplate adhesion seems to be dependent on the location of the piece in reference to the origin.
1. Add file to slicer.
2. Slice with buildplate adhesion enabled. 

### Actual results

Brim line consistency dependent on position of object on the buidplate
![image](https://user-images.githubusercontent.com/53494213/232226145-919186d6-1620-4e60-8fed-ac63d6ff34ed.png)
![image](https://user-images.githubusercontent.com/53494213/232226158-e5cb07c2-3290-457f-85ee-ee6d248d808d.png)
![image](https://user-images.githubusercontent.com/53494213/232226169-a2922321-a050-4095-9c08-ed0f3d9f7214.png)
![image](https://user-images.githubusercontent.com/53494213/232226182-a02f4a64-b742-47d1-a4a3-aa73a6faab4c.png)
![image](https://user-images.githubusercontent.com/53494213/232226205-7370fafc-f54a-48d3-b1c3-a1a64a48e752.png)

Same behavior with skirt
![image](https://user-images.githubusercontent.com/53494213/232226420-34b4fcfc-5e85-4e66-b368-f8bacf32a9ad.png)
![image](https://user-images.githubusercontent.com/53494213/232226429-c723322b-4124-4fde-825c-5e09d74611bc.png)

### Expected results

Continous line for brim or skirt

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Here is the project file.
[AKLP_Body2.zip](https://github.com/Ultimaker/Cura/files/11239579/AKLP_Body2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the Project File.
I can duplicate the problem with your printer and that the problem occurs with both "Brim" and "Skirt".  Changing the Bed Adhesion settings didn't help.
When I switch to my Ender 3 Pro the problem went away and I could not duplicate it with my printer.  The only real difference I see is the shape of the bed.
Someone from the Cura team will take a look.

**Comment by andreikovari** [comment]
Awesome! Thanks! Let me know if I can assist you with anything else.

**Comment by PerlBoy79** [comment]
Hi, I am having the same issue. I simply created a 500 brim line count (similarly skirt with 300 lines), and the missing shape is consistently there. So far happens to any objects placed. 

Current workaround is to move object away from that location or place big enough an object's 1st layer to cover that zone.

Other posts:
[https://github.com/Ultimaker/Cura/issues/14873](url)
[https://github.com/Ultimaker/Cura/issues/14876](url)
Also Anycubic Kossel Linear Plus models

**Application Version**
5.3.0 / 5.3.1 
(issues present in both versions)

**Platform**
Win11

**Printer**
Anycubic Kossel Linear Plus

![image](https://user-images.githubusercontent.com/132211356/235359574-b1598af7-e23e-48d9-82bb-3b55c8024445.png)

**Comment by yzheka** [comment]
same for me for kossel. looks like issue is only for delta printer. i have no issue for voron 0.1

**Comment by fieldOfView** [comment]
Probably related to the 'Origin at center" setting and how CurEngine recently started clipping the skirt and brim to the buildplate extents.

**Comment by GregValiant** [comment]
This was addressed with [PR #15847](https://github.com/Ultimaker/Cura/pull/15847/commits/8cfa59eabf7c140e99e9babe26eb5e8a80038a05) .  It has been merged and the problem should be fixed in the next release.

Yes, it did look like the brim/skirt "clipping" was the issue but it was the way the "disallowed areas" were defined in the printer definition files that was causing the problem.  

I'll go ahead and close this as it has been addressed.
