### ISSUE TITLE
Ask user before resizing

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#1524]
Currently the Cura default behavior is to resize objects without asking the user. It is easy to overlook the message and waste filament. It would be better to explicitly ask the user for confirmation with yes/no before resizing.

**Comment by nallath** [comment]
The default behavior has been set to disabled for 2.5, so part of this is already fixed. 

I've added the feature to our Internal tracker (CURA-3513)

**Comment by probonopd** [comment]
With the default being disabled, that's sufficient as a solution for me, hence closing. Thanks.
