### ISSUE TITLE
CURA Does NOT produce gcode file that matches the stl or obj file.

### ISSUE THREAD

**Issue by bricomp** [Ultimaker/Cura#15247]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Elegoo Neptune 3 Plus

### Reproduction steps

Sliced stl (and obj) file which produced a gcode file which does not resemble the stl (or obj) file.

![zz](https://user-images.githubusercontent.com/3074955/232208150-21242bde-cd48-42f2-8be4-6cabb55e6f84.png)

### Actual results

![zz1](https://user-images.githubusercontent.com/3074955/232208139-c005ca1e-24b5-4d44-b734-8f73fc2b0042.png)

### Expected results

![zz2](https://user-images.githubusercontent.com/3074955/232208280-2c7dcf10-83ab-4ef1-bc2c-9af17216580c.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[EN3P_Thermostat Enclosure.zip](https://github.com/Ultimaker/Cura/files/11239115/EN3P_Thermostat.Enclosure.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11239121/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
If you turn off "Spiralize" I think you'll find it to be OK.
This appears to be a setting issue so I'll remove the bug label.  I'll leave this open for a bit so you can respond if you feel that is premature.
![image](https://user-images.githubusercontent.com/64202104/232228591-a2536c0a-bf1d-418d-bd1d-1e0777e2bb32.png)
