### ISSUE TITLE
Cura got a bug during slicing

### ISSUE THREAD

**Issue by servant74** [Ultimaker/Cura#15255]
### Application Version

5.3.0

### Platform

Windows 33

### Printer

Ultimaker 3

### Reproduction steps

1. brought in models
2. arranged on bead
3. sliced using tree supports
4. it reported a bug 

### Actual results

Slicer displayed a problem happened and suggested reporting bug

### Expected results

should have shown results of slicing on display

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UM3_Spool_Holder.3mf.zip](https://github.com/Ultimaker/Cura/files/11240786/UM3_Spool_Holder.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This sliced for me on the first try so I can't duplicate the problem.  If you could post a Cura.log file ("Help | Show Configuration Folder") it may give a clue as to what is happening.
