### ISSUE TITLE
Falha no Fatiamento

### ISSUE THREAD

**Issue by marygisele** [Ultimaker/Cura#15252]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Tycoon Slim

### Reproduction steps

Fatiou o arquivo mas depois que mudei a posição, mando fatiar e não fatia aparece a seguinte mensagem fatiamento falhado e isso vem acontecendo várias vezes.

### Actual results

Fatiou o arquivo mas depois que mudei a posição, mando fatiar e não fatia aparece a seguinte mensagem fatiamento falhado e isso vem acontecendo várias vezes.

### Expected results

Fatiou o arquivo mas depois que mudei a posição, mando fatiar e não fatia aparece a seguinte mensagem fatiamento falhado e isso vem acontecendo várias vezes.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Erro cura](https://user-images.githubusercontent.com/130853799/232235060-44f0ec14-050f-4e9e-929e-6a632bdf3c69.png)

**Comment by MariMakes** [comment]
Hey @marygisele,

Desculpe, não falo português, mas acho que posso ajudá-lo.

That's a pretty cool model 🤩, but it doesn't seem to be made for 3D printing. 
Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
