### ISSUE TITLE
Errore di Cura 5.3.0

### ISSUE THREAD

**Issue by Itanium2k** [Ultimaker/Cura#15253]
### Application Version

5.3.0

### Platform

Windows 11 Pro

### Printer

Artillery Sidewinder x1

### Reproduction steps

Salve. Segnalo che cura 5.3.0 si blocca quando moltiplico gli oggetti sul bed.

### Actual results

CTRL+M dovrebbe creare più oggetti invece il programma con questa operazione si blocca

### Expected results

Mi aspetto che crei come le versioni precedenti più copie dell'oggetto sul bed

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Non ho altro da aggiungere.

**Comment by GregValiant** [comment]
Thanks for the report.
If you could post a Cura.log file it would help to show what is going on.  I can't duplicate the problem as it works fine for me.  Use the "Help | Show Configuration Folder" command and the Cura.log file will be in it.  I think you will need to zip it and post the zip folder here.
