### ISSUE TITLE
unable to view files

### ISSUE THREAD

**Issue by stephdu68** [Ultimaker/Cura#15261]
### Application Version

5.3.0

### Platform

Mac 64 bit

### Printer

Creality ender 3 s1 pro

### Reproduction steps

1.open files

### Actual results

unable to view files on cura 5.3.0, but it's ok with cura 5.2.2

### Expected results

display of my file in order to be able to slice it

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

?

**Comment by nallath** [comment]
I'm not entirely sure what your issue is. What files were you unable to view? Any file? Does the open file window not show? Is nothing shown or is something incorrect shown? 

Could you provide some screenshots and or log files?
