### ISSUE TITLE
error Could not save data:text/

### ISSUE THREAD

**Issue by imactony** [Ultimaker/Cura#15267]
### Application Version

5.3.0

### Platform

windows 11

### Printer

Creality CR-10S

### Reproduction steps

1. Uninstall program.
2. Reboot computer.
3. Reinstall program.
4. Attempt to save project file.

### Actual results

Could not save to data:text/
plain;base64,QzpcVXNlcnNcY3Jhd2ZcRGVza3RvcFxSb2JlcnQgQmFyYXRoZW9uXFdlYXBvbnNcNjA1MzdkMmY2YTRlNl9yb2JlcnQtcy13YXJoYW1tZXI

### Expected results

I should have a savable file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no files to add

**Comment by nallath** [comment]
Could you provide us with a bit more information? We will need the log file at the very least in order to attempt to figure out what is going wrong.
