### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by weruhgfderfg** [Ultimaker/Cura#15265]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Ender 3 V2 Neo (Klipper)

### Reproduction steps

1. droped in a modle

### Actual results

1. didnt slice

### Expected results

1. should have sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by nallath** [comment]
Without a model, there isn't a lot we can do to debug the issue. Could you please provide us with the model that caused the issue? Preferably we would like to have the project file.
