### ISSUE TITLE
new profiles

### ISSUE THREAD

**Issue by Gadget74** [Ultimaker/Cura#15275]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

tried to save a new profile and the option is gone

### Actual results

no option to save a new profile

### Expected results

older versions have an option to save a new profile from current settings
![Untitled](https://user-images.githubusercontent.com/131071062/232623474-81933db1-8027-4018-a988-f4c31a7efd99.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Untitled](https://user-images.githubusercontent.com/131071062/232623744-691e2857-6442-483e-b09b-0e91c5e98f36.png)

**Comment by nallath** [comment]
By the looks of it, you simply don't have any changes to save to a new profile. Once you make a change, you should see the following:

![image](https://user-images.githubusercontent.com/3922611/232756831-893cd19f-8239-4b62-98c0-1e0e284b74a0.png)

The save icon to the right of the profile menu allows you to create a new profile. Also note the star in the profile selector, which indicates that there are unsaved changes. 

Could you check if you indeed have any settings changed and if that isn't working for you?
