### ISSUE TITLE
Printer nanes

### ISSUE THREAD

**Issue by jerry1935** [Ultimaker/Cura#15282]
### Is your feature request related to a problem?

Have two differing Creality Ender S1(s)

### Describe the solution you'd like

Is there a way to change the printer names in the profile?  I run both a 300 and 225 mm bed Ender and have to keep the slicer inputs separate and the files too.  All I have now is Ender 3 S1#1 and Ender 3 s1#2  which I have to keep remembering.  The #1 is a S1+ if I remember correctly.

Thanks for your consideration,
Jerry Jensen, C-My3DPrints.com

### Describe alternatives you've considered

can't seem to find any.

### Affected users and/or printers

any one using more than one different Ender 3

**Comment by GregValiant** [comment]
Go to "Manage Printers" and there is a  "hamburger" icon (three horizontal lines) on the right.  One of the options is to rename a printer.  
![image](https://user-images.githubusercontent.com/64202104/232906046-cea8c947-eea8-466b-970d-4fc1e9dcb050.png)
