### ISSUE TITLE
Slices to gcode no longer include nozzle temp settings

### ISSUE THREAD

**Issue by TheDarwking** [Ultimaker/Cura#15281]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Ender 3 S1 Pro

### Reproduction steps

I have the same profile I have been using, but I have noticed since switch to 5.3.0, that new slices have not included the nozzle temp settings, so when I go to print the printer starts pre-heating the bed but the nozzle is still at zero.  If I manually preheat, it works fine, so its definitely not getting overridden, just missing.

### Actual results

See above

### Expected results

I expect after I slice, the gcode to include the filament profiles nozzle temp settings.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3S1PRO_Bent_Tree_3canopy.zip](https://github.com/Ultimaker/Cura/files/11263084/CE3S1PRO_Bent_Tree_3canopy.zip)
[CE3S1PRO_Bent_Tree_3canopy_gcode.zip](https://github.com/Ultimaker/Cura/files/11263117/CE3S1PRO_Bent_Tree_3canopy_gcode.zip)

**Comment by fieldOfView** [comment]
The gcode file you upload starts as followis, and does contain extruder heating commands:
```
;FLAVOR:Marlin
;TIME:35724
;Filament used: 22.5096m
;Layer height: 0.2
;MINX:68.668
;MINY:68.329
;MINZ:0.2
;MAXX:147.458
;MAXY:144.151
;MAXZ:86
;Generated with Cura_SteamEngine 5.3.0
M140 S60
M105
M190 S60
M104 S200
M105
M109 S200
M82 ;absolute extrusion mode...
```
As far as the gcode is concerned, there is no reason why the extruder temperature would stay at 0.

**Comment by TheDarwking** [comment]
Based on the profile I had in Cura, I have the setting set to 200C, so
shouldn't it be making it into the gcode?  That's why I included both the
project and the gcode for comparison.

Thanks for the help

**Comment by fieldOfView** [comment]
> I have the setting set to 200C, so shouldn't it be making it into the gcode? 

That _is_ what's in the gcode. 200C for the nozzle.

**Comment by TheDarwking** [comment]
Oh sorry.  Well for whatever reason when I put it in my ender 3 s1 pro, I
have not had it pick it up.  I tried with Prusa or old slices from Cura and
those still work fine.

**Comment by nallath** [comment]
That doesn't seems to be a Cura issue. The g-code clearly has the command to instruct the printer to heat to 200 degrees.
