### ISSUE TITLE
Failed to Slice

### ISSUE THREAD

**Issue by jchihak-stlcc** [Ultimaker/Cura#15286]
### Application Version

5.3.0

### Platform

Apple macOS 12.6.1

### Printer

Ultimaker 2+ and Ultimaker 3 Extended

### Reproduction steps

1. Imported 3MF file into Cura
2. Applied desired print settings 
3. clicked Slice button

### Actual results

Slicing begins and before reaching ~10% fails with error Slicing failed
Slicing failed with an unexpected error. Please consider reporting a big on our issue tracker.

### Expected results

Model slices successfully and then saved to disk or removable media.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11265012/cura.log)
<img width="439" alt="Screen Shot 2023-04-18 at 1 16 54 PM" src="https://user-images.githubusercontent.com/60162583/232867998-067f85db-1e0e-4b00-afe8-f1cb70d37345.png">
[UM3E_3-D printing.3mf.zip](https://github.com/Ultimaker/Cura/files/11265018/UM3E_3-D.printing.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
From you log file:
"Backend exited abnormally with return code -11!"
Someone from the Cura Team will know what that means.  I'll mark this as a duplicate report and a slicing error.

I moved the model and then rotated it 90° CCW and it sliced.  This bug showed up in 5.2 and it has been worked on but it obviously isn't gone yet.
![image](https://user-images.githubusercontent.com/64202104/232904401-d7ad73d9-a8b7-44e1-9552-6e9bfa6f8b90.png)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
