### ISSUE TITLE
Missing images in the wiki

### ISSUE THREAD

**Issue by MarcBresson** [Ultimaker/Cura#15294]
### Application Version

on the GitHub wiki

### Platform

on the GitHub wiki

### Printer

on the GitHub wiki

### Reproduction steps

Go to https://github.com/Ultimaker/Cura/wiki/Container-Stacks and see that it is missing an image for "three container stacks".

### Actual results

We cannot see the images in the wiki

### Expected results

I suspect that when the doc has been migrated to the wiki pages, the image links has not correctly been adapted. In GitHub, the wiki behaves as a different repo than the code repo, with all the pages of the wiki being at the root of the wiki repo.

The correct link to the images should not include `../` and should have an upper case `R` for `Resources`. Instead of `../resources/machine_instance.svg`, the correct link is then `Resources/machine_instance.svg` (I tested it by modifying the HTML locally)

I could fix this issue but I don't have the rights to push to the wiki repo in a `fix-...` branch.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

None

**Comment by nallath** [comment]
Thanks for reporting this! I've fixed it.

There is one weird thing about it though (might be a github bug). In order for it to work in the preview, you do need to use "../Resources/machine_instance.svg"
