### ISSUE TITLE
 error when cutting or slicing

### ISSUE THREAD

**Issue by i5ma91** [Ultimaker/Cura#15308]
### Application Version

5.2.2

### Platform

10

### Printer

Creality Ender-3 Pro

### Reproduction steps

1. enter the stl file, i raised the layer height to 0.2mm
2. I gave it to segment

### Actual results

i print other stl files just fine

### Expected results

the save to external drive button will appear

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

It is a print of 195.7 x 195.8 x 196.9 mm

**Comment by GregValiant** [comment]
Thanks for the report.
In order to investigate - a Project File and the Cura.log is required.
