### ISSUE TITLE
bug, unable to slice

### ISSUE THREAD

**Issue by skvjlm** [Ultimaker/Cura#15309]
### Application Version

5.3.0

### Platform

MacOs Ventura

### Printer

Ender 3 PRO

### Reproduction steps

loaded a moon, tried to slice, got error, unable to slice

### Actual results

no slicing

### Expected results

slicing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nope

**Comment by skvjlm** [comment]
![Captură de ecran din 2023-04-21 la 09 16 23](https://user-images.githubusercontent.com/105647965/233555592-d12af3dc-4a22-43bf-9e9a-db4736b89028.png)

**Comment by casperlamboo** [comment]
Hello @skvjlm, 

Thank you for opening the issue.

Without a project file we are unable to help you. You can share a project file by saving the project (ctrl+s) and creating a zip of the exported 3mf file. The zip can then be uploaded to this issue on github.

The error looks a bit like a known issue where certain orientations of the model result in a slicing error. We are actively working on resolving this issue but there is a workaround. By slightly rotation and/or moving the model Cura can often still slice the model.

Hope this helps!

- @casperlamboo

**Comment by skvjlm** [comment]
Well Thanks for the response!It’s just a very low priority project and I assumed it’s because of the really difficult mesh with lots of surfaces.Pe 24 apr. 2023, la 16:02, Casper Lamboo ***@***.***> a scris:﻿
Hello @skvjlm,
Thank you for opening the issue.
Without a project file we are unable to help you. You can share a project file by saving the project (ctrl+s) and creating a zip of the exported 3mf file. The zip can then be uploaded to this issue on github.
The error looks a bit like a known issue where certain orientations of the model result in a slicing error. We are actively working on resolving this issue but there is a workaround. By slightly rotation and/or moving the model Cura can often still slice the model.
Hope this helps!

@casperlamboo

**Comment by MariMakes** [comment]
Hey @skvjlm,

This mesh indeed looks difficult, but not impossible. I've seen people print it before. Where did you get the model? 

If you want us to help you troubleshoot. I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.
