### ISSUE TITLE
slicer stopped working

### ISSUE THREAD

**Issue by abohannon98** [Ultimaker/Cura#15303]
### Application Version

5.3.0

### Platform

windows 10

### Printer

anycubic mega pro

### Reproduction steps

pressed slice to slice and print.

### Actual results

slice stopped working

### Expected results

file should have sliced and been able to print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

slicer stopped working

**Comment by Vandresc** [comment]
Hi @abohannon98, thank you for your feedback! In order to reproduce the issue we will need a project file, could you please upload it to the ticket? Thank you!
