### ISSUE TITLE
Incredible error when print a object (and only thtat)

### ISSUE THREAD

**Issue by MarcelloMazza** [Ultimaker/Cura#15317]
### Application Version

5.3.0

### Platform

Window 10

### Printer

FLSUN V400

### Reproduction steps

I launch a print of the same large but not very complex object, but at the second layer there is a trouble.

### Actual results

At the second layer, when the head reaches about halfway, an overextrusion occurs and the head descends until it removes the material from the first layer and I have to stop printing. All this does not depend on the orientation of the piece.
Layer heght first and second 0.2 mm.
![20230421_093531_HDR](https://user-images.githubusercontent.com/131460765/233723485-0f43a198-4a62-4f5a-90a0-869105d6fdf3.jpg)

### Expected results

Stop printing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

In the gcode file there are not problem and the trouble is only for that piece

**Comment by nallath** [comment]
From the information that you have provided here, this doesn't seem to be an issue with Cura. It looks much more like the bed isn't leveled correctly. Could you try leveling the bed and try again?

**Comment by MariMakes** [comment]
Hey @MarcelloMazza,

I'm tending to agree with @nallath, this seems to be a leveling issue. 
I'm seeing SnailTracks, which often means that the nozzle is too close. 

![image](https://user-images.githubusercontent.com/40423138/236507296-da99a5bd-7164-41ee-97d4-7f35fa8c3582.png)

To me, it doesn't seem like a bug in Ultimaker Cura but one with your printer. 
You can reach out on Reddit or facebook to other FLSUN users or even start a discussion on our [UltiMaker community forum which you can find here.](https://community.ultimaker.com/). 

I'll be closing this issue. I hope you understand. 
Good luck!
