### ISSUE TITLE
Support not generating.

### ISSUE THREAD

**Issue by BurritoKitten** [Ultimaker/Cura#15320]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Wanhao D6

### Reproduction steps

Import "slide_v2.stl"
Select generation settings (Support on, bed adhesion on, PLA)
Slice.

### Actual results

The object is sliced, without supports. Bed adhesion generates sometimes.

### Expected results

Object slices with supports and bed adhesion (brim).

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/125295362/233760398-cc20981f-fab8-46dc-ace9-c2346e8625d6.png)
[Troubleshoot.zip](https://github.com/Ultimaker/Cura/files/11300196/Troubleshoot.zip)

**Comment by fieldOfView** [comment]
If you click the "Color scheme" part of the top bar, you should get a legend for the colors. Make sure that in that legend, the "Helpers" items is not unticked.
