### ISSUE TITLE
COULD NOT SLICE FILE

### ISSUE THREAD

**Issue by db9jc** [Ultimaker/Cura#15321]
### Application Version

5.3.0

### Platform

WINDOWS 11

### Printer

FLSUN SUPER RACER

### Reproduction steps

1. UPLOAD THE FILE TO CURA
2. INCREASE THE SIZE FROM 100% UP TO 150%, SELECT TREE SUPPORT AND RUN THE SLICER
3. IT TOOK FOREVER TO SLICE AND THEN IT SAID IT COULDN'T SLICE THE FILE

### Actual results

NOTHING HAPPEND AS IF I NEVER RUN THE SLICER

### Expected results

SLICE THE FILE AND GET IT ON WITH IT..

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11300281/cura.log)

**Comment by Vandresc** [comment]
Hi @db9jc, could you please share a project file with us where the error can be reproduced? Thank you!
