### ISSUE TITLE
Se detiene proceso de corte y emite un error

### ISSUE THREAD

**Issue by carlosgds1** [Ultimaker/Cura#15325]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Kimgroon KP3S

### Reproduction steps

Estoy realizando la segmentacion de un diseño, y se detiene a la mitad

### Actual results

Hace una recomendacion de realizar el reprote y no termina la segmentacion

### Expected results

tener el Gcode para imprimir

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/131537644/233790162-87708277-487b-4047-918b-edc0baa02434.png)

**Comment by casperlamboo** [comment]
Hello @carlosgds1,

Thank you for opening the issue. My Spanish is not that great, so pardon me for replying in English.

Without a project file we are unable to help you. You can share a project file by saving the project (ctrl+s) and creating a zip of the exported 3mf file. The zip can then be uploaded to this issue on github.

The error looks a bit like a known issue where certain orientations of the model result in a slicing error. We are actively working on resolving this issue but there is a workaround. By slightly rotation and/or moving the model Cura can often still slice the model.

Hope this helps!
