### ISSUE TITLE
Segmentation Error

### ISSUE THREAD

**Issue by dariobarroeta** [Ultimaker/Cura#15335]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Artillery Hornet

### Reproduction steps

1.- Press star segmentation Bottom
2.- Initiate segmentation.

### Actual results

The screen shows a message of an "Unexpected Error when trying to slice"
![image](https://user-images.githubusercontent.com/106969433/233863799-554377e4-636f-4f64-90a3-c087b1fa0e03.png)

### Expected results

Slice of the file.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

....

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project File and Cura log there can't be an investigation as we have nothing to view/refer to.
