### ISSUE TITLE
cura slicing fail

### ISSUE THREAD

**Issue by PAXMASTER2000** [Ultimaker/Cura#15349]
### Application Version

5.3.0

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

put stl in and tried to slice.
came back with an error
![Screenshot 2023-04-24 200111](https://user-images.githubusercontent.com/131724986/234140428-3f96e72e-2c9e-4a2e-89a3-6aa1e87dca45.png)

### Actual results

nothing will not slice

### Expected results

it to slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11315394/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
From the log file: "_Backend exited abnormally with return code 2!_"
Someone from the Cura team will take a look.  They may need a project file as well.
