### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by rbohlken** [Ultimaker/Cura#15345]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Creality Ender 3 Pro

### Reproduction steps

Opened stl file that successfully sliced in Cura 5.2 Now fails everytime
![image](https://user-images.githubusercontent.com/55544078/234064710-0d5b97ee-5922-4553-8f57-b78a6514a27f.png)

### Actual results

Keeps Failing

### Expected results

Keeps failing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/55544078/234064911-e574a406-74fd-41ef-b938-2c166587cdeb.png)

**Comment by MariMakes** [comment]
Hey @rbohlken,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
