### ISSUE TITLE
Custom Printers use RepRap not Marlin.  Why will this setting not register?

### ISSUE THREAD

**Issue by TH-AC** [Ultimaker/Cura#15343]
### Application Version

5.3.0

### Platform

Win 11

### Printer

Ender 3 custom Duet 3d and other custom Duet driven printer

### Reproduction steps

1 Select "Manage Printers"
2.  Select "Machine Settings" for any of my 2 printers
3. Change "G-code-flavor" to "RepRap
4.  Close the Machine settings page/Dialogue
5. Reopen Machine settings to confirm change of Flavor.  Flavor not changed still has Marlin as flavor.

### Actual results

Cannot change flavor to correct flavour

### Expected results

Change Flavor to RepRap.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Should there be a save button on the Machine settings page, for storing changes?

**Comment by GregValiant** [comment]
In Explorer - right click on the "Cura 5.3" installation folder.  Select Properties.
On the Security tab "Edit" the permissions and make sure everything/everybody has access.
On the Sharing tab share the folder.
It's a Windows thing.  This is my computer, I'm the only one who uses it, and I have to share things with myself.  Dumb.
Anyway, those two things should allow you access and over-write ability.

**Comment by GregValiant** [comment]
This bug has been addressed in current versions of Cura.  I'll go ahead and close this.
