### ISSUE TITLE
Bug no processamento

### ISSUE THREAD

**Issue by LuisVasconcelos1987** [Ultimaker/Cura#15344]
### Application Version

5.3

### Platform

Windows 10

### Printer

Elegoo Neptune 2S

### Reproduction steps

Quando o software vai fatiar ele buga. Nas outras versões não acontecia, mas está se tornando comum esse problema.

### Actual results

Trava e não gera o modelo fatiado

### Expected results

Ocorresse o fatiamento normalmente

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nada mais a contribuir

**Comment by MariMakes** [comment]
Hey @LuisVasconcelos1987,

Desculpe, não falo português, mas acho que posso ajudá-lo.

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
