### ISSUE TITLE
slicing fails

### ISSUE THREAD

**Issue by 00slice** [Ultimaker/Cura#15358]
### Application Version

5.3.0

### Platform

windows 11, amd ryzen 9 5900x

### Printer

anycubic kobra max

### Reproduction steps

selected file and hit slice to prepare for print and fails to slice.. tried slicing on my longer LK5 and slices perfectly fine

### Actual results

slicing fails

### Expected results

slicing should not fail

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

only having slicing issue with the anycubic kobra max my longer lk5 has no issues tried 3 other files as well with same results.

**Comment by MariMakes** [comment]
Hey @00slice,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
