### ISSUE TITLE
Raft selection causing increased accel on Initial travel after prime

### ISSUE THREAD

**Issue by Jcoulter24** [Ultimaker/Cura#15359]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

FLsun Super Racer

### Reproduction steps

When slicing file with raft, the head would jerk after prime and start digging into build plate. This would not happen when using brim. After checking both Gcodes, I noticed that after the prime line my accel which is always F3000 was changed to F10800. Changing the Gcode fixed the jerk and drag

### Actual results

Nozzle jerking and dragging into bed

### Expected results

Changes to accel and speeds should not change when using raft vs brim or skirt

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Uploaded is screenshot of the gcode files side by side. Left Raft and Right Brim 

<img width="1920" alt="Screenshot 2023-04-26 014741" src="https://user-images.githubusercontent.com/119092880/234481397-d0d680c1-5601-4714-92e0-17a265b79967.png">

**Comment by GregValiant** [comment]
Thanks for the report.
**G0 F10800 X92.4 Y132.804 Z0.35 ;adjusted by z offset
G92 Z0.2 ;consider this the original z before offset**
You can see that the comment states "adjusted by Z-Offset" so it is the plugin that adds that line.  The author of the plugin (@fieldOfView ) will need a Project File to check your other settings (number of slower layers, initial layer travel speed, travel speed) and make sure his plugin is working as designed.
Use the "File | Save Project" command and zip the 3mf file it creates.  Post the zip folder here.
