### ISSUE TITLE
g code sürüm hatası

### ISSUE THREAD

**Issue by mertoo78** [Ultimaker/Cura#15355]
### Application Version

5.3.0

### Platform

windows 11

### Printer

ender 3

### Reproduction steps

thingiverse den dosyayı indiriyorum cura da açtığımda herşey düzgün ama dilimleyip kaydet dediğim zaman %10 gcode oluşturuyor

### Actual results

.

### Expected results

.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by nallath** [comment]
I'm sorry, but I don't understand what your issue is. Could you share a project file that reproduces the issue and post reproduction steps in English?
