### ISSUE TITLE
5.3.0. Unable to slice fully closed and good mesh print

### ISSUE THREAD

**Issue by owoodykent** [Ultimaker/Cura#15351]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

1. I imported the file and set the settings
2. I attempted multiple times to slice the object but with no success
3. I went back into the rhino file to make sure it was a good mesh with no non-manifold edges and naked edges
4. Reimported the file and attempted to re-slice it

### Actual results

I got an error message saying unable to slice and I should report the bug

### Expected results

Its supposed to slice the object and show how long the file will take to print, as well as give the option to save the print file to a removable disk to insert into the printer 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AV_W3P2.zip](https://github.com/Ultimaker/Cura/files/11319154/AV_W3P2.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
