### ISSUE TITLE
cura 5.3.0 crashes when slicing

### ISSUE THREAD

**Issue by rockinjon49** [Ultimaker/Cura#15363]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Creality Ender 3 

### Reproduction steps

1. fill build plate with 4 or 5 cookie cutter models
2. click slice the bar quickly fills and goes blank

### Actual results

Software hangs and then stops responding then i have to close and restart program

### Expected results

the models should slice and i should be able to export the gcode

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This is an intermittant issue but the frequency has jumped considerably recently. previous versions of cura i would have to cancel the slice when the bar would go blank but with 5.3.0 I cant as the program freezes. My machine has a ryzen 7 3700x processor 48GB ram with a nvidia geforce gtx1650 graphics card. I have uninstalled and reinstalled software and it happens when running as admin also

**Comment by MariMakes** [comment]
Hey @rockinjon49,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
