### ISSUE TITLE
Bug. Support blockers?

### ISSUE THREAD

**Issue by nitram6272** [Ultimaker/Cura#15360]
### Application Version

5.3.0-alpha+xmas

### Platform

Windows 10

### Printer

Artillery Sidewinder X1

### Reproduction steps

Used cubed support blockers on 2 of 3 models for the first time.

### Actual results

Failed to slice approx 60% into slicing.
![CURA bug report](https://user-images.githubusercontent.com/109218985/234497605-04bec103-104a-482e-8943-2b1f38a9fe23.jpg)

### Expected results

Sliciing should complete.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11330083/cura.log)

**Comment by nitram6272** [comment]
Although I created a project file it would not upload sorry.

**Comment by GregValiant** [comment]
Thanks for the report.
Github site rules are that files other than text files must be zipped in order to upload.  Right-click on the 3mf file and select "Send To..." and then "compressed (zip) folder".  Post the zip folder here.
