### ISSUE TITLE
units overlap text 

### ISSUE THREAD

**Issue by AMI3** [Ultimaker/Cura#15361]
### Application Version

5.3.1

### Platform

windows 11

### Printer

creality ender3

### Reproduction steps

  I am using windows in hebrew, and it seems the Right to Left indentation messes up the units position, and overlaps the input text in the configuration menu
![Cura_screenshot2](https://user-images.githubusercontent.com/56076966/234503599-477fc905-5b93-49c7-96f9-b21e0e776a06.png)

![Cura_screenshot](https://user-images.githubusercontent.com/56076966/234502913-5f9e1e08-771e-4e82-b7e2-58a7f2fc18a7.png)

### Actual results

The units position, and overlaps the Data text.
![Cura_screenshot](https://user-images.githubusercontent.com/56076966/234503924-6b321b57-c9a5-4c8c-b74c-4a437576c10a.png)

### Expected results

No overlap of the text

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I added 2 screensots
![Cura_screenshot](https://user-images.githubusercontent.com/56076966/234504078-b1e59110-e434-4be8-893e-a1167deb8512.png)
![Cura_screenshot2](https://user-images.githubusercontent.com/56076966/234504088-d6d81ee9-8ee0-4ba0-aebf-dbb604562145.png)

**Comment by MariMakes** [comment]
Hey @AMI3,

Sorry, it took us a while to get back to you 😞 

Thanks for your report 👍 This is the first time I've seen this. 😅 

I'll bring it up to the team to see what they can do to improve it. 
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @AMI3,

Quick update from our side 👋

One of our developers was able to resolve it, so it should be fixed in the next release 😊
You can read more about the fix here https://github.com/Ultimaker/Cura/pull/16270

Thanks again for your report 👍
