### ISSUE TITLE
Slicing error due to bug

### ISSUE THREAD

**Issue by Bilal-Shirwani** [Ultimaker/Cura#15375]
### Application Version

5.1.1

### Platform

Mac OS

### Printer

xx's Aquila

### Reproduction steps

Inserted the .stl file, rearranged the x,y and z axis and tried to slice.

### Actual results

Notification popped up that unable to slice due to bug.

### Expected results

proper slicing and g code.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All stated above.

**Comment by GregValiant** [comment]
Thanks for the report.
5.1.1 is four versions behind.  Could you update to 5.3.1 and see if the problem still exists?  Have you checked the model for possible errors?
