### ISSUE TITLE
Tempeture Bad 

### ISSUE THREAD

**Issue by PureevilCZ** [Ultimaker/Cura#15380]
### Application Version

5,2,1

### Platform

W 10

### Printer

Ender 3

### Reproduction steps

After the first layer, the temperature of the bed cannot be set to zero

### Actual results

fdgdfg

### Expected results

fdgdfg

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

dfgd

**Comment by GregValiant** [comment]
A little more information would be good.  What exactly do you mean?  You want the bed shut off after the first layer?  That's the sort of thing that ChangeAtZ is for.  You could also use Search and Replace.  You could also set the regular Bed Temperature to 15 and the Intial Layer Bed Temperature to something like 60.
I don't see a bug here but you didn't really give any information.
