### ISSUE TITLE
report

### ISSUE THREAD

**Issue by Trayan86** [Ultimaker/Cura#15385]
### Application Version

5.3.1

### Platform

windows 11

### Printer

wanhao duplikator 9

### Reproduction steps

I ran to "slice" and it gave me an error

### Actual results

error

### Expected results

to make me a file for the printer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nol

**Comment by GregValiant** [comment]
Thanks.
