### ISSUE TITLE
slicing issue

### ISSUE THREAD

**Issue by emmav28** [Ultimaker/Cura#15395]
### Application Version

5.3.1

### Platform

windows 11

### Printer

cr10 s5

### Reproduction steps

put file into cura
postioned file in cura 
clicked slice 
waited for it to slice 
slicer got to about 80% and then the bug report came up 

### Actual results

the program will not slice

### Expected results

the program would slice 

### Checklist of files to include

- [x] Log file
- [ ] [general]
visible_settings = support;bottom_layers;infill_line_width;cool_fan_speed;cool_fan_enabled;support_interface_extruder_nr;support_structure;machine_settings;cool_fan_speed_max;wall_thickness;material_final_print_temperature;interlocking_enable;line_width;top_thickness;ironing_enabled;cool_fan_full_layer;support_interface_enable;support_offset;top_bottom_thickness;travel;support_infill_sparse_thickness;prime_tower_brim_enable;infill_sparse_density;infill_extruder_nr;material_initial_print_temperature;blackmagic;dual;wall_extruder_nr;retraction_speed;speed_infill;prime_tower_position_x;speed_print;material_print_temperature;brim_outside_only;cool_fan_speed_0;infill_overlap;gradual_support_infill_steps;material;retraction_hop;optimize_wall_printing_order;adhesion_extruder_nr;material_standby_temperature;adhesion_type;speed_layer_0;support_extruder_nr;travel_avoid_distance;skin_line_width;wall_0_extruder_nr;retraction_combing;skin_monotonic;support_type;travel_avoid_supports;infill;resolution;prime_blob_enable;meshfix;skirt_brim_speed;support_angle;material_bed_temperature_layer_0;retraction_hop_after_extruder_switch;support_infill_rate;speed_support;speed_travel;support_conical_enabled;jerk_enabled;speed_wall;speed_topbottom;wall_line_width;top_layers;wall_line_count;infill_line_distance;infill_multiplier;retraction_hop_only_when_collides;cool_fan_speed_min;infill_sparse_thickness;cooling;support_pattern;speed_wall_0;brim_line_count;material_print_temperature_layer_0;retraction_enable;top_bottom_extruder_nr;support_enable;retraction_amount;infill_pattern;initial_layer_line_width_factor;support_infill_extruder_nr;cool_min_layer_time;skirt_line_count;adaptive_layer_height_enabled;prime_tower_position_y;smooth_spiralized_contours;speed_prime_tower;cool_fan_full_at_height;gradual_support_infill_step_height;travel_avoid_other_parts;platform_adhesion;top_bottom;print_sequence;shell;cool_min_layer_time_fan_speed_max;retraction_hop_enabled;support_roof_enable;speed_wall_x;magic_mesh_surface_mode;bottom_thickness;support_bottom_enable;layer_height;gradual_infill_steps;conical_overhang_enabled;speed;brim_width;retract_at_layer_change;cool_lift_head;support_extruder_nr_layer_0;cool_min_speed;wall_x_extruder_nr;layer_height_0;xy_offset;material_bed_temperature;prime_tower_enable;magic_spiralize;wall_line_width_x;acceleration_enabled;experimental;wall_line_width_0
last_run_version = 5.3.1
accepted_user_agreement = True
ultimaker_auth_data = {"success": true, "token_type": "Bearer", "expires_in": 600, "scope": "account.user.read connect.cluster.read connect.cluster.write connect.material.write cura.printjob.read cura.printjob.write drive.backup.read drive.backup.write library.project.read library.project.write packages.download", "received_at": "2023-04-30 18:55:02", "access_token": null, "refresh_token": null}
window_left = 665
window_top = 30
window_width = 1040
window_height = 881
window_state = 2
version = 7

[view]
settings_ypos = 60.0

[cura]
recent_files = E:/Boba fett/boba fresh/Fett Armor/Abs.stl;E:/Boba fett/boba fresh/Fett Armor/Hand Plate Left.stl;E:/Boba fett/boba fresh/Fett Armor/HandPlateRight.stl;E:/Boba fett/boba fresh/Fett Armor/SHoulder left.stl;E:/Boba fett/boba fresh/Fett Armor/Shoulder right.stl;E:/Boba fett/boba fresh/Fett Armor/Circuit.stl;E:/Boba fett/boba fresh/Fett Armor/Chest Centre.stl;E:/Boba fett/boba fresh/Fett Armor/Chest Right.stl;E:/Boba fett/boba fresh/Fett Armor/Chest Left.stl;
active_mode = 1
categories_expanded = ;adhesion_extruder_nr;adhesion_type;anti_overhang_mesh;blackmagic;brim_gap;brim_inside_margin;brim_line_count;brim_outside_only;brim_replaces_support;brim_width;cutting_mesh;extruder_prime_pos_x;extruder_prime_pos_y;gradual_support_infill_step_height;gradual_support_infill_steps;infill_mesh;infill_mesh_order;layer_0_z_overlap;magic_mesh_surface_mode;magic_spiralize;minimum_bottom_area;minimum_interface_area;minimum_roof_area;minimum_support_area;mold_angle;mold_enabled;mold_roof_height;mold_width;platform_adhesion;prime_blob_enable;print_sequence;raft_acceleration;raft_airgap;raft_base_acceleration;raft_base_extruder_nr;raft_base_fan_speed;raft_base_jerk;raft_base_line_spacing;raft_base_line_width;raft_base_speed;raft_base_thickness;raft_fan_speed;raft_interface_acceleration;raft_interface_extruder_nr;raft_interface_fan_speed;raft_interface_jerk;raft_interface_layers;raft_interface_line_spacing;raft_interface_line_width;raft_interface_speed;raft_interface_thickness;raft_jerk;raft_margin;raft_smoothing;raft_speed;raft_surface_acceleration;raft_surface_extruder_nr;raft_surface_fan_speed;raft_surface_jerk;raft_surface_layers;raft_surface_line_spacing;raft_surface_line_width;raft_surface_speed;raft_surface_thickness;relative_extrusion;skirt_brim_extruder_nr;skirt_brim_minimal_length;skirt_gap;skirt_line_count;smooth_spiralized_contours;support;support_angle;support_bottom_angles;support_bottom_density;support_bottom_distance;support_bottom_enable;support_bottom_extruder_nr;support_bottom_height;support_bottom_line_distance;support_bottom_offset;support_bottom_pattern;support_bottom_stair_step_height;support_bottom_stair_step_min_slope;support_bottom_stair_step_width;support_bottom_wall_count;support_brim_enable;support_brim_line_count;support_brim_width;support_connect_zigzags;support_enable;support_extruder_nr;support_extruder_nr_layer_0;support_fan_enable;support_infill_angles;support_infill_extruder_nr;support_infill_rate;support_infill_sparse_thickness;support_initial_layer_line_distance;support_interface_angles;support_interface_density;support_interface_enable;support_interface_extruder_nr;support_interface_height;support_interface_offset;support_interface_pattern;support_interface_skip_height;support_interface_wall_count;support_join_distance;support_line_distance;support_mesh;support_mesh_drop_down;support_meshes_present;support_offset;support_pattern;support_roof_angles;support_roof_density;support_roof_enable;support_roof_extruder_nr;support_roof_height;support_roof_line_distance;support_roof_offset;support_roof_pattern;support_roof_wall_count;support_structure;support_supported_skin_fan_speed;support_top_distance;support_tower_diameter;support_tower_maximum_supported_diameter;support_tower_roof_angle;support_tree_angle;support_tree_branch_diameter;support_tree_branch_diameter_angle;support_tree_branch_distance;support_tree_collision_resolution;support_tree_max_diameter;support_type;support_use_towers;support_wall_count;support_xy_distance;support_xy_distance_overhang;support_xy_overrides_z;support_z_distance;zig_zaggify_support
active_machine = Creality CR-10S5
active_setting_visibility_preset = advanced
custom_visible_settings = support;bottom_layers;cool_fan_speed;cool_fan_enabled;machine_settings;top_layers;wall_thickness;wall_line_count;top_thickness;support_offset;cooling;top_bottom_thickness;retraction_enable;travel;support_tree_branch_diameter;support_enable;infill_sparse_density;support_tree_max_diameter;infill_pattern;blackmagic;dual;prime_tower_position_y;support_tree_branch_distance;prime_tower_position_x;speed_print;top_bottom;material_print_temperature;platform_adhesion;support_tree_angle;shell;retraction_hop_enabled;material;support_tree_branch_diameter_angle;bottom_thickness;layer_height;adhesion_extruder_nr;speed;support_extruder_nr;adhesion_type;xy_offset;material_bed_temperature;support_type;prime_tower_enable;infill;resolution;prime_blob_enable;meshfix;experimental;support_tree_collision_resolution;support_angle

[local_file]

[info]

[cura_drive]

[backend]

[gcodereader]

[layerview]

[metadata]
setting_version = 21

[mesh]

[um3networkprinting]

[physics]

[output_devices]
- [ ] Project file

### Additional information & file uploads

nothing else to report

**Comment by MariMakes** [comment]
Hey @emmav28,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
