### ISSUE TITLE
[Window Title] Slicing engine for Cura  [Main Instruction] Slicing engine for Cura 已停止工作  [Content] 出现了一个问题，导致程序停止正常工作。如果有可用的解决方案，Windows 将关闭程序并通知你。  [关闭程序(C)]

### ISSUE THREAD

**Issue by cyh924417122** [Ultimaker/Cura#15399]
### Application Version

5.1.0

### Platform

 Microsoft Windows 10 企业版 2016 长期服务版

### Printer

Prusa i3

### Reproduction steps

1.open the file （download from https://www.printables.com/model/285368-v29-whistle/files）
2.auto slice

### Actual results

[Window Title]
Slicing engine for Cura

[Main Instruction]
Slicing engine for Cura stoped work

### Expected results

slice done，and start printing on usb

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11364028/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
From your log file:  "Backend exited abnormally with return code 3221225477!"
My understanding is that is a memory fault generated by the Cura engine.  Someone from the Cura team will take a look.
That link to Printables just brings up a Prusa page.  If you would load the model in Cura and then use the "File | Save Project" command and then zip the file and post the zip folder here someone will take a look.  It would be good to have the Cura set up, the model and your printer to trouble shoot this.
