### ISSUE TITLE
Ubuntu Connection by IP Not Working

### ISSUE THREAD

**Issue by nicholas1513** [Ultimaker/Cura#15393]
### Application Version

5.3.1

### Platform

GNU/Linux

### Printer

Snapmaker 2.0 a350

### Reproduction steps

1. Install cura software using linux-modern 5.3.1 package
2. Assure that both printer and computer are connected to the same wifi network connection
3. Get ip address from printer details, and confirm against devices listed from wifi router login
4. Attempt to add printer to cura by ip address (since it is not showing up as detected on network automatically)

### Actual results

The printer does not connect.  Cura software reads, "Could not connect to device."

### Expected results

Printer is registered with cura software as a usable machine

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have assured that I can connect via the same IP address, on the same computer, using other slicing software (snapmaker's provided Luban software).  I am unable to replicate a successful connection through Cura 5.3.1

**Comment by fieldOfView** [comment]
Without installing plugins, Cura can only connect to Ultimaker printers on the network.

There is not one 3d printer network protocol; just about every 3d printer manufacturer comes up with their own. There are some common network hosts, such as OctoPrint and Mainsail (Klipper). There are plugins in the Marketplace to interface Cura with those hosts. I don't know what host/protocol Snapmaker uses, and if there is a plugin for Cura to interface with it. This is something for you to ask Snapmaker.
