### ISSUE TITLE
Replacement patterns don't appear to work

### ISSUE THREAD

**Issue by gbarbehenn** [Ultimaker/Cura#15403]
### Application Version

5.3.0

### Platform

Windows 10 Pro 64b

### Printer

Wanhao Duplictor I3

### Reproduction steps

End Gcode includes:
G1 Z+5 F{speed_travel/5}		; Move carriage up 5mm
G90							; Need absolute positioning to park the carriage
G1 X0 Y200 F{speed_travel}		; Bring thing to the front

### Actual results

Travel speed set 120mm/s, but Both G1 moves execute very, very slowly.

### Expected results

Z move to execute at 24mm/s, and second move to execute at 120mm/s

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I would upload a file how?

**Comment by GregValiant** [comment]
@gbarbehenn The math and logic is now supported in 5.7.1.  I'll go ahead and close this.
