### ISSUE TITLE
Cura 2.4 "heating failed" in 3rd layer of raft

### ISSUE THREAD

**Issue by bond4u** [Ultimaker/Cura#1540]
3 prints in a row Marlin 1.1.0-rc8 told "heating failed print halted".
Thought it's intial layer temp problem, but setting it to 0 didn't make a difference.
Switched back to Cura 2.3.1 and it's printing fine.
[files.zip](https://github.com/Ultimaker/Cura/files/842226/files.zip)

**Comment by kr15uk** [comment]
Had the same issue. Apparently will be fixed in v2.5.

Let me guess you don't have heated bed?!
If so then go to printer settings, enable heated bed, in temp settings set bed to 0 and you should be all good (you can disable bed back in settings if you like).

**Comment by bond4u** [comment]
Thanks! That did the trick.
Tried Marlin RCBugFix branch, but it didn't make a difference.
Set all four temp settings to same value and that didn't work either.

**Comment by BagelOrb** [comment]
fixed
