### ISSUE TITLE
wire printing slicing failes

### ISSUE THREAD

**Issue by gilr128** [Ultimaker/Cura#15400]
### Application Version

5.3.0

### Platform

windows 10

### Printer

ender3 v2

### Reproduction steps

1) sliced a model with a standard slicing profile
2)tried to slice using wire printiing, slicing failed.

### Actual results

slicing failiure

### Expected results

sucsessful slicing 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

nothing to add
![image](https://user-images.githubusercontent.com/132254453/235422881-0b721d14-5bef-44a6-8276-11c4594dd804.png)

**Comment by fieldOfView** [comment]
Thanks for the report.

Unfortunately this will not be fixed. Wireprinting will be removed entirely in the next version of Cura.
If you want to use Wireprinting, you will have to keep an older version of Cura around.
