### ISSUE TITLE
freezes during first layer on brim

### ISSUE THREAD

**Issue by chuckie1975** [Ultimaker/Cura#15405]
### Application Version

5.2.1

### Platform

windows 10

### Printer

ender 3 pro v2

### Reproduction steps

started print and it failed on brim
re sliced and it did the same

### Actual results

tried it a few times gave up went to prusa wich worked

### Expected results

done with prusa

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3E3V2_CUP INSERT(.210).zip](https://github.com/Ultimaker/Cura/files/11367469/CE3E3V2_CUP.INSERT.210.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I don't see anything in the gcode that would cause a stoppage.  They are small models and it's a small gcode file.  
I have a utility that takes all the extrusions out of a file.  I "air printed" the file on my Ender 3 Pro and there weren't any issues.  It made it to the end.
So I am unable to duplicate this problem.  I just don't see anything in the gcode that would cause the printer to stop (until the ending gcode).
If you are printing via the SD card- try re-formatting the card.  If a file get written to a bad memory sector then it can randomly stop when the printer tries to read the instructions in the bad memory area.  The Prusa file could have been in a good sector and the Cura file after the skirt was in a bad sector.
