### ISSUE TITLE
Problem with infill pattern

### ISSUE THREAD

**Issue by FedeFlour** [Ultimaker/Cura#15412]
### Application Version

5.3.1

### Platform

MacOS Monterey

### Printer

Custom FFF

### Reproduction steps

I set the infill pattern as both with lines and grid with an array of infill line direction [0,90]

### Actual results

the slicing shows a diagonal infill pattern

### Expected results

the infill pattern should be a non-diagonal grid 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1185" alt="Schermata 2023-05-02 alle 12 01 40" src="https://user-images.githubusercontent.com/132348708/235637854-02a97e08-a907-4c4d-8417-f894c166ff1c.png">

**Comment by GregValiant** [comment]
Thanks for the report.
I'm not familiar with an infill setting for "both".  With my installation of Cura I have a dropdown box and I can select one type of infill.
Your image appears to show Top/Bottom Lines over your Grid infill.  The Infill appears to be at [0,90].  There is a separate setting for Top/Bottom Line Directions and your current setting appears to be the default [45, 135].
I don't see a bug here so I'll remove the label for now.  If you provide something else for us to look at then that can be re-visited.
This is with the infill line directions at [0, 90] and the top/bottom line directions set to [0,90]
![image](https://user-images.githubusercontent.com/64202104/235730102-e2df2f16-6feb-4740-b1cf-321221852eb3.png)

**Comment by GregValiant** [comment]
I'll close this today.
