### ISSUE TITLE
Incorrect Preview

### ISSUE THREAD

**Issue by TheMickael** [Ultimaker/Cura#15426]
### Application Version

5.3.1

### Platform

MacOS Version 13.3.1 (a) (22E772610a)

### Printer

Biqu B1 ABL

### Reproduction steps

1. In Fusion 360: Select the Component (single body) and "Save As Mesh"
2. In dialog box: Format STL, Unit Type Millimetre, Structure One File, Refinement High, Print Utility Custom and Cura as application
3. Cura opens and centre the model on the print bed
4. Slice and then Preview 

### Actual results

Once in a blue moon It shows the component to print with lines going out from the model (see attached pics)
If moving around in the view, the lines change direction
No error message or crash
The file print well on the 3D printer, so seems to be a render issue in the Preview

Had the same issue with previous versions as well
Restarting Cura does not help
Restarting Fusion 360 and try again does not help
Changing Component to print does not work either 
Only way to get it to work again is to restart the Mac

<img width="801" alt="Screenshot 2023-05-03 at 09 25 53" src="https://user-images.githubusercontent.com/132414552/235860662-a4044558-050e-4b42-abc0-9f81c304f35f.png">
<img width="798" alt="Screenshot 2023-05-03 at 08 45 34" src="https://user-images.githubusercontent.com/132414552/235860678-fd9bb194-9a3a-4f03-a520-106ab6dd12de.png">

### Expected results

Normal view of the preview with proper layers

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It happens very seldom and have not been able to find any specific circumstances that triggers it.
Its input independent, but once it happens it happens with all loaded models.
The saved gcode file opens OK in other applications as well as on printer.

**Comment by MariMakes** [comment]
Hey @TheMickael,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

That doesn't look good 😨 

It reminds me of two issues that we are investigating. 
One that seems to be specifically for Biqu printers: https://github.com/Ultimaker/Cura/issues/14080
Another that seems to be related to One At A Time Mode https://github.com/Ultimaker/Cura/issues/11057

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
