### ISSUE TITLE
Cura 5.x.x doesnt work for lot of models ... usualy when you use support 

### ISSUE THREAD

**Issue by Juraj-MJ** [Ultimaker/Cura#15429]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. put the model 
2. Use custom profile PolyWood_Ultimaker_S5_Cura 

### Actual results

doesnt slice 

### Expected results

normal slice 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

https://www.thingiverse.com/thing:4640403

**Comment by GregValiant** [comment]
Thanks for the report.
The bears "are not watertight and may not print correctly".  That makes a problem for Cura BUT I was able to slice your project without repairing the models.
Here is the slice with an S5 active but I don't have your custom profile.  If you would create a project file and zip it and post the zip folder here it may provide more information.
![image](https://user-images.githubusercontent.com/64202104/236211205-06988e53-54e8-4a3f-a383-ddbbdb6ff3dc.png)
