### ISSUE TITLE
Layer cutting problem

### ISSUE THREAD

**Issue by rybianets** [Ultimaker/Cura#15433]
### Application Version

5.3.1

### Platform

Windows 10

### Printer

Anet A8 plus

### Reproduction steps

About slicing the model in the middle of the model, support layers are generated.
Loaded the model and performed cutting.
Supports included, 60% infill.

### Actual results

![Error](https://user-images.githubusercontent.com/17320803/236007545-c1efacf9-b571-42e5-bfd5-2e1cca8fe9ed.PNG)
[3D Objects.zip](https://github.com/Ultimaker/Cura/files/11389652/3D.Objects.zip)

### Expected results

Cura 4.6
![WoError](https://user-images.githubusercontent.com/17320803/236010762-2e18d4af-ec4d-4f1c-9a1a-337ebfcac4a6.PNG)
.0

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Attached is project and model.

**Comment by GregValiant** [comment]
Thanks for the report and the files.
Looking at the preview with supports turned off you can see that there are gaps in the preview where there shouldn't be any.  That indicates errors in the model (usually flipped normals).
Here is your model on the left and a model I repaired using MS 3D Builder is on the right.  You would need to check to make sure but it would appear that the problems have gone away on the repaired model.
![image](https://user-images.githubusercontent.com/64202104/236205911-f9f24631-2fd6-4fcc-8a07-d6b62202207c.png)

I'm going to remove the bug label from this as it appears to be a model problem.  I hope you understand.
If you feel that is premature let us know.  I'll leave this open so you can respond here.

**Comment by GregValiant** [comment]
I'll close this today.
