### ISSUE TITLE
Cura uninstalls self

### ISSUE THREAD

**Issue by BurritoKitten** [Ultimaker/Cura#15440]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Wanhao D6

### Reproduction steps

I have no idea; but my computer seems to do this recovering from a deeper state of sleep than normal.
The applications that I left open when I turned off my computer do not restore themselves, and this is unusual, even after a restart.
After this, when I boot my computer, The shortcut on my desktop says that the file isn't found.
A large quantity of the Cura files are missing, but it skips a fair number of them in reinstallation. My profiles still exist, and all personalization is present after reinstallation, but this has happened twice now and is quite annoying.

### Actual results

N/A

### Expected results

N/A

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11396991/cura.log)

**Comment by MariMakes** [comment]
Hey @BurritoKitten,

Thanks for your report 👍
It sounds super annoying 😞 

Are you switching a lot between Cura versions?
Are you connected to your printers over the internet?
I've seen some reports where after uninstalling an older version the shortcuts would not be removed properly. There is a workaround available if that is what you are encountering. 


To help resolve this issue we would like to have a better understanding of what is happening. 
Do you perhaps have some screenshots of what you are encountering? 
Do you have some more solid steps to reproduce?
For example, how do you open your cura version?
We would need these steps to test any solutions that we are looking at.
