### ISSUE TITLE
Cura 2.3.1 generate Up-side-down GCode

### ISSUE THREAD

**Issue by vadimostanin** [Ultimaker/Cura#1544]
I tried to print this http://www.thingiverse.com/thing:2178442
I generated gcode by Cura 2.3.1 with default "Solid" settings Prusai3 PLA, with changed layer height and speed
But when printer prints several layer, I saw that printed layers was not layers from bottom of model, but It is layers from top of model.

**Comment by nallath** [comment]
I can't reproduce this.

**Comment by Ghostkeeper** [comment]
This report slipped through the cracks in March...

Is the g-code actually upside down in the file as well or is it a firmware issue?
