### ISSUE TITLE
Stone age

### ISSUE THREAD

**Issue by RICKYBOBBY1979** [Ultimaker/Cura#15443]
### Application Version

5.3.1

### Platform

Windows 10

### Printer

Magician Pro

### Reproduction steps

Tried slicing a file and this program is taking days to preform a simple task. My other slicers have it done in a few minutes. I have to ask if you are using Windows 98 to run this program.

### Actual results

Nothing I can't use my printers. I run a fast paced shop and these latest versions have been nothing but trash

### Expected results

Please get it together and create something that is useful.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Nothing to show here cause I can't get it to slice

**Comment by fieldOfView** [comment]
Hey, I'm a community contributor to the Cura project.

I am sorry you are having issues running Cura. Unfortunately you did not share any logs, nor did you tell anything about your system configuration,  so there is nothing we can do to help you.

I will close this issue, but we can reopen it if you have anything constructive to add, leaving your thinly veiled attempts at insults at bay. Then we can see if we can help you get going.
