### ISSUE TITLE
Failure to slice

### ISSUE THREAD

**Issue by gilahacker** [Ultimaker/Cura#15455]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Snapmaker 2 A350

### Reproduction steps

Imported model, tweaked print settings, hit "Slice".

### Actual results

Generic "Unexpected error has occurred" message w/ recommendation to report it here.

### Expected results

It should slice the file.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11413204/cura.log)
[S2A_skull-bowl-paradigm.zip](https://github.com/Ultimaker/Cura/files/11413207/S2A_skull-bowl-paradigm.zip)

**Comment by MariMakes** [comment]
Hey @gilahacker,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for the Project File 👍

I took a look at it in Cura 5.3.1 but I seem to be able to slice it correctly in Cura. 
![image](https://user-images.githubusercontent.com/40423138/236864816-4a0d0c24-fc86-4285-b920-69d06e699dbf.png)

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
