### ISSUE TITLE
Error trying to slice in the "Wire Printing" mode

### ISSUE THREAD

**Issue by abrahamvsaldana** [Ultimaker/Cura#15450]
### Application Version

5.3.1

### Platform

macOS 13.3.1 (a) (22E772610a)

### Printer

Creality Ender-33 S1 PRO

### Reproduction steps

1- I Open the Cura Slicer
2- Open a model (.stl)
3- Put it to be printed on "Wire printing"
4- An Error Message that couldn´t let the file to slice" saying to please inform of this error message
<img width="1440" alt="Captura de pantalla 2023-05-05 a la(s) 3 22 21 p m" src="https://user-images.githubusercontent.com/125833808/236571046-24440f54-8412-4d14-aa7b-9ddbd4369636.png">
[CFFFP Pineapple_box_-_Bottom Creality3D PETG lw 0.4mm lh 0.24mm if 25% ext1 245C bed 80.0C.3mf.zip](https://github.com/Ultimaker/Cura/files/11410197/CFFFP.Pineapple_box_-_Bottom.Creality3D.PETG.lw.0.4mm.lh.0.24mm.if.25.ext1.245C.bed.80.0C.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11410207/cura.log)

### Actual results

An Error Message that couldn´t let the file to slice" saying to please inform of this error message

### Expected results

Be able to slice it in the "wire printing" mode

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11410213/cura.log)
[CFFFP Pineapple_box_-_Bottom Creality3D PETG lw 0.4mm lh 0.24mm if 25% ext1 245C bed 80.0C.3mf.zip](https://github.com/Ultimaker/Cura/files/11410215/CFFFP.Pineapple_box_-_Bottom.Creality3D.PETG.lw.0.4mm.lh.0.24mm.if.25.ext1.245C.bed.80.0C.3mf.zip)

**Comment by MariMakes** [comment]
Hey @abrahamvsaldana,

Thanks for your report 👍

As mentioned in the release notes, it's broken in 5.3 and we are removing it because we see it's rarely used. So if you want to use it you'll have to go back to Cura 5.2 or older. You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.2.2

Can you help me understand why you wanted to use wire printing?
