### ISSUE TITLE
Wont slice

### ISSUE THREAD

**Issue by dorkshork** [Ultimaker/Cura#15464]
### Application Version

5.3.1

### Platform

windows 10

### Printer

Ender 3

### Reproduction steps

I uploaded a file from thingiverse which will not slice

### Actual results

It tells me it cannot slice and to report the bug

### Expected results

it should slice and print my project

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

will not let me upload the files in question

**Comment by GregValiant** [comment]
Github only accepts zipped files.
Load the model into Cura and set Cura up to slice.
Use the "File | Save Project" command to make a 3mf project file.
In Explorer, right click on the file and select "Send To..." and then "Condensed (Zip) Folder".  Post the zip folder here.
