### ISSUE TITLE
填充时打印头速度失控

### ISSUE THREAD

**Issue by xxzhang0119** [Ultimaker/Cura#15462]
### Application Version

5.2.1

### Platform

WIN11

### Printer

CCR6SE

### Reproduction steps

设定填充速度50mm/s或者其他，打印填充尤其是弯道时速度会比设定快，挤出机频繁打滑，如果需要可以提供视频

### Actual results

设定填充速度50mm/s或者其他，打印填充尤其是弯道时速度会比设定快，挤出机频繁打滑

### Expected results

查遍全网没有找到相关解决办法，是不是我没有注意到某些参数

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

无

**Comment by GregValiant** [comment]
Load a model that is a problem and set Cura up to slice.
Use the "File | Save Project" command to create a 3mf project file.
Right click on the new 3mf file and select "Send To..." and then select "Compressed (zip) folder".
Post the zip folder here and some one will take a look.
