### ISSUE TITLE
cura slicer engine crashed

### ISSUE THREAD

**Issue by AlgenGruetze** [Ultimaker/Cura#15460]
### Application Version

5.3.1

### Platform

Windows 10 HE

### Printer

Anycubic i3 Mega S/Pro

### Reproduction steps

same procedure as always....

### Actual results

crash again

### Expected results

should work fine

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![photo_2023-05-06_16-15-11](https://user-images.githubusercontent.com/112272071/236678321-f9cd5b93-f1a7-4d07-b57b-fece052209b1.jpg)

**Comment by GregValiant** [comment]
Thank you Thing for the report.
The Cura team will want a log file to review.  A project file would help as well.
Use the "Help | Show Configuration" folder to find the "cura.log" file.
Load a model, set Cura up to slice, use the "File | Save Project" command to create a 3mf project file.
In File Explorer, right-click on the 3mf file and select "Send To.." and "Compressed (zipped) folder"  You can add the log file to the zip folder and post the zip folder here.
