### ISSUE TITLE
slicing does not work on a MacBook Pro M1

### ISSUE THREAD

**Issue by glaudahn** [Ultimaker/Cura#15478]
### Application Version

all

### Platform

slicing does not work on a MacBook Pro M1 2022

### Printer

Anycubic i3 Mega S

### Reproduction steps

Problem:
Ultimaker Cura 5.3.1 can slice on a MacBook Pro Silicon 2021, MacOS Ventura 13.2
slicing does not work on a MacBook Pro M1, MacOS Ventura 13.2.
Is there a workaround?

### Actual results

Cura screen stays always empty on MacBook Pro M1 
on a MacBook Pro Silicon 2021 everything works fine

### Expected results

Cura should slice on MacBook Pro M1 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1037" alt="Bildschirmfoto 2023-05-08 um 20 33 25" src="https://user-images.githubusercontent.com/5211315/236903383-c913bf1b-f5b7-4063-9413-124c38f50245.png">
screen is empty

**Comment by MariMakes** [comment]
Hey @glaudahn,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

We have users that have M1 MacBooks, even in the team. 
So I believe it might be related to something else. 

Do you have more solid steps to reproduce for us? 
Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
