### ISSUE TITLE
Printersettings Window

### ISSUE THREAD

**Issue by VirusMercutio** [Ultimaker/Cura#15488]
### Application Version

5.3.1

### Platform

windows 10

### Printer

Anycubic Viper

### Reproduction steps

I try to make the Printersettings window bigger, but if i push the left butten on my mouse on the 3 points down at the window, the window change to a small window, and  now i cant make it bigger.

I try to delete Cura and install again and this 3 times but nothing changes.

### Actual results

nothing

### Expected results

...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

....

**Comment by MariMakes** [comment]
Hey @VirusMercutio,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

I think I recognize your report. 
Are you talking about these buttons at the bottom of the settings?
![image](https://github.com/Ultimaker/Cura/assets/40423138/e97b6c8e-3cc7-4628-bc14-537aa2d91666)

Do I understand correctly that it's stuck in a small position that makes it hard to see all the settings?
I believe I've seen it once or twice, what resolved it for me was a reset.
This is how to perform it:
1. Quit the application
2. In a file explorer window, navigate to:
- My Computer/users/[user_name]/AppData/Local/cura
- My computer/Users/<your username>/AppData/Roaming/cura
4. Delete the entire 'cura' folder of your current version. Note: Cura folders of previous versions will be imported if not deleted!
5. Open Ultimaker Cura. If it has been reset correctly, you will be greeted with the onboarding flow

If you do this you will use any custom profiles. If you want to keep these make sure to make a back-up. 
You can read more about them here: https://support.makerbot.com/s/article/1667412704080

Can you try the reset and let us know if this works for you?  Thanks 🙏
