### ISSUE TITLE
Navigation cube

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#1550]
It would be nice if Cura would have a navigation cube known from many other 3D applications.

![screenshot at 2017-03-18 11 38 27](https://cloud.githubusercontent.com/assets/2480569/24071335/8d654662-0bcf-11e7-9fa6-7203afaaa407.png)

**Comment by foreachthing** [comment]
Nice one, @probonopd!
And if you're at it, add a possibility to enable/disable perspective (orthographic) view. This would make layer-view much easier to over view.

**Comment by fieldOfView** [comment]
Unfortunately Autodesk has a patent on the navigation cube.

**Comment by probonopd** [comment]
I'd be surprised if the general idea could be patented (might be wrong though, ianal). Do you have a link? Maybe we'd need to make it a bit different then, but still something similar.

**Comment by foreachthing** [comment]
Use arrows and planes...

**Comment by probonopd** [comment]
Actually if we could have this existing UI element interact with the mouse like a navigation cube, then that'd do the job:

![screenshot from 2017-03-19 13-39-58](https://cloud.githubusercontent.com/assets/2480569/24080962/a5df92d0-0ca9-11e7-92b7-e63b1aa1eb42.png)

**Comment by nallath** [comment]
@probonopd Software patents. Which would mean we can't distribute to america anymore. 

Even if a court would deem it invalid, it would still cost a whole lot of money, so I'd rather not take the risk.

**Comment by BagelOrb** [comment]
Let's consider the OP's last idea to circumvent the patent.

**Comment by fieldOfView** [comment]
Caveat: for some printers, this is in the center of the buildplate.

**Comment by Ghostkeeper** [comment]
It'd also be a bit weird for elliptical build plates to click on the sides.

**Comment by Ghostkeeper** [comment]
This has been implemented with several buttons at the top of the screen in 3.1.
