### ISSUE TITLE
Block rotating pieces when arrange/mutiply

### ISSUE THREAD

**Issue by alfrenovsky** [Ultimaker/Cura#15517]
### Is your feature request related to a problem?

Sometimes you need to orient the parts so the last layer lines is aligned with the object. paralel, perpendicular or any angle you want.
When I Multiply, the clones appears oriented to optimize the print space usuarlly rotating them in 90º mutiples . The same with Arrange all models (I suspect the multiply action ends calling arrange)

### Describe the solution you'd like

I like an option to force keeping the piece orientation.

### Describe alternatives you've considered

It could be another action like "arrange without rotating" or a checkbox in multiply

### Affected users and/or printers

Everybody

**Comment by MariMakes** [comment]
Hey @alfrenovsky,

Thanks for your request👍
I see the benefit of a way to lock rotation. You are not the first with this request. 😉 

It looks like this proposal will make it into the next Cura release: https://github.com/Ultimaker/Cura/pull/15496
Is that the kind of solution you are looking for?
