### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Kimbleta** [Ultimaker/Cura#15513]
### Application Version

5.3.1

### Platform

Windows 10 Pro

### Printer

Anycubic Kobra Max

### Reproduction steps

Added objects to bed. 
During slicing I get an error.

Slicing engine for Cura has stopped working.
Restarted, checked for updates. reloaded objects.
I have slied and printed the same files/object before.

### Actual results

Slicing engine for Cura has stopped working.

### Expected results

Slice object results

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2023-05-13_02h27_47](https://github.com/Ultimaker/Cura/assets/107646786/bd4526a9-5c75-4f4a-867e-83240ce10cd1)
![2023-05-13_02h29_39](https://github.com/Ultimaker/Cura/assets/107646786/98c85f90-c9ef-4afe-8672-7249b3e710c1)

**Comment by MariMakes** [comment]
Hey @Kimbleta,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
