### ISSUE TITLE
not slicing

### ISSUE THREAD

**Issue by Timothy-21-c7** [Ultimaker/Cura#15529]
### Application Version

5.3.1

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

i put my file in to the slicer then imputed my settings and it says there was a error and now im here

### Actual results

an error message was shown

### Expected results

to get it sent to my sd card

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
_"...it says there was a error and now im here"_
Yes.  But it seems that you forgot to bring a project file and log file so we have nothing to look at, and so we can't investigate what might be going on.
