### ISSUE TITLE
slicer crashing instanly

### ISSUE THREAD

**Issue by AlgenGruetze** [Ultimaker/Cura#15537]
### Application Version

5.3.1

### Platform

Windows 10 HE

### Printer

Anycubic i3 Mega S/Pro

### Reproduction steps

slice groot leg

### Actual results

slice engine crashed

### Expected results

generate g-code

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![16052023_2130](https://github.com/Ultimaker/Cura/assets/112272071/66459683-18c2-4bd9-acc2-34d9d341b4e6)

**Comment by MariMakes** [comment]
Hey @AlgenGruetze,

Thanks for sharing these crashes. 😊 
I can see this is not your first thanks for your dedication. 👍 
We add them to the list so when we work on solving them we can use them as a test case to analyze what is going wrong. 
But for that we need the project file to be included in your report. 

Without the project file, we cannot see if it's an error on the Cura side, like wrong support generation or incorrect simplification of complex shapes. Or if it's an error that we cannot resolve like a wrong model or an unreasonable combination of settings. 

Can you share the project file so we can troubleshoot what is going wrong? 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
