### ISSUE TITLE
wating for user input error 

### ISSUE THREAD

**Issue by KGR33** [Ultimaker/Cura#15533]
### Application Version

5.3.1

### Platform

windows 11

### Printer

cr10s4

### Reproduction steps

wating for user input error mid print < it happened recently and i tried to uninstall it but that did not work .

### Actual results

wating for user input error mid print < it happened recently and i tried to uninstall it but that did not work .

### Expected results

wating for user input error mid print < it happened recently and i tried to uninstall it but that did not work .

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log1.txt](https://github.com/Ultimaker/Cura/files/11484126/cura.log1.txt)

**Comment by MariMakes** [comment]
Hey @KGR33,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This seems like a firmware error that is specific for your printer.

Can you share more about what you are seeing? 
Do you have a picture of the error? 
Did it occur on the printer or in your monitor?
Do you have the gcode that caused the error? 
Could it be that it had a post processing script that paused the printer? 

I understand that it's frustrating if your printer doesn't work, but it's hard for us to help you if you don't provide the correct information. Looking forward to your reply 😊
