### ISSUE TITLE
Keeps crashing while trying to slice

### ISSUE THREAD

**Issue by ghpetrina** [Ultimaker/Cura#15539]
### Application Version

5.3.1

### Platform

windows 10

### Printer

Creality ender -5 plus

### Reproduction steps

trying to place numerous parts on the platform, it kept trying to slice every time i moved something. started coming up with slicer error and finally became non-responsive.
Like it became overloaded with slicing too many parts.

### Actual results

program crashed

### Expected results

it should have been able to keep up with the added parts
![bug1](https://github.com/Ultimaker/Cura/assets/47299590/672e194b-e45a-4386-9da9-cf1ac11cb347)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
Thanks for the report but without a project file there can be no investigation.
Are you sure all those models are error free?
