### ISSUE TITLE
Slice fails and requests to report a bug

### ISSUE THREAD

**Issue by Johann1** [Ultimaker/Cura#15548]
### Application Version

5.3.1

### Platform

Windows 10 Home

### Printer

Ultimaker S5

### Reproduction steps

1. Open Download Page [https://www.thingiverse.com/thing:4063612/files](https://www.thingiverse.com/thing:4063612/files) and  download Code2_Ulvheim_Tavern_A_Columns_Update.stl or unzip attached project zip file (contains .3mf)
2. Open downloaded STL in fresh installed Ultimaker Cura 5.3.1 or open .3mf project file
3. Start slicing

### Actual results

**Slicing failed with unexpected error and Cura requests to report a bug.** 

[MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [964]: Backend exited abnormally with return code 3221225477!

Screenshot:
<img width="1807" alt="screenshot" src="https://github.com/Ultimaker/Cura/assets/6651945/907a9111-4f7a-4fde-a94c-83e43263ff03">

Logs:
[cura.log](https://github.com/Ultimaker/Cura/files/11502142/cura.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/11501775/stderr.log)

Project file in ZIP
[UMS5_Code2_Ulvheim_Tavern_A_Columns_Update.zip](https://github.com/Ultimaker/Cura/files/11501998/UMS5_Code2_Ulvheim_Tavern_A_Columns_Update.zip)

### Expected results

**Slicing works.**

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11502389/cura.log)
[UMS5_Code2_Ulvheim_Tavern_A_Columns_Update.zip](https://github.com/Ultimaker/Cura/files/11502413/UMS5_Code2_Ulvheim_Tavern_A_Columns_Update.zip)
[stderr.log](https://github.com/Ultimaker/Cura/files/11502415/stderr.log)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
**Backend exited abnormally with return code 3221225477!** I believe that is a memory error.
I'll mark this as a duplicate and close it as there are a lot of reports on this behavior and that error code.  I hope you understand.
For myself (Windows10 home), I've never been able to duplicate that error.
With your settings this is a 44 hour print.  I didn't find any errors in the model.
![image](https://github.com/Ultimaker/Cura/assets/64202104/0e1896d8-c418-4106-af81-957bd317e414)

**Comment by Johann1** [comment]
Thank you for the quick answer. It would make sense to assume a memory issue.
I will try again on a Ti5 Aegis, because i know it has 128GB.

**Comment by Johann1** [comment]
@GregValiant - i tried with 128 GB machine but same issue occured after i imported the project and started the slicing:
![2023-05-19 21_03_19-Greenshot](https://github.com/Ultimaker/Cura/assets/6651945/861b745a-d65d-4431-aad6-51ea19722384)

@GregValiant - Does it have to do with Ultimaker printer? I have the same error for S3 and S5
> 2023-05-17 22:04:58,846 - DEBUG - [EngineOutputThread] UM.Backend.Backend._backendLog [115]: [Backend] [2023-05-17 22:04:58.845] [warning] Failing to discretize parabola! Must add an apex or one of the endpoints.
2023-05-17 22:05:02,994 - ERROR - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [964]: Backend exited abnormally with return code 3221225477!
2023-05-17 22:05:02,997 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [360]: Attempting to kill the engine process
2023-05-17 22:05:02,998 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [366]: Killing engine process
2023-05-17 22:05:02,999 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._terminate [369]: Engine process is killed. Received return code 3221225477

I will continue to try other settings next.

**Comment by Johann1** [comment]
@GregValiant - It works with 0.15mm  but not with 0.2mm fast print 😒
<img width="1807" alt="slice" src="https://github.com/Ultimaker/Cura/assets/6651945/ea9be55a-fecc-4c7b-a660-73e041181143">

**Comment by GregValiant** [comment]
An alternative may be to change the Initial Layer Height by just a bit.  For example if it is 0.20 make it 0.21.  Sometimes that can be enough to full the bug and you still get the quicker print time from the higher layer height.  That's a long print and anything to make it quicker will help.
Another thing you could do would be to make the "Infill Layer Thickness" 2X layer height.  It will go down every other layer and (depending on the geometry of the model) make for a faster print.

**Comment by Johann1** [comment]
@GregValiant actually it works with 0.201mm (but not 0.21mm). Thank you very much! This solution is fine 🙂
