### ISSUE TITLE
NO PRINTER ANYCUBIC PHOTON ULTRA

### ISSUE THREAD

**Issue by mxDOCTOR** [Ultimaker/Cura#15545]
### Application Version

5.3.1

### Platform

Windows 10 1080 Ti

### Printer

NO MY PRINTER!

### Reproduction steps

NO PRINTER ANYCUBIC PHOTON ULTRA

### Actual results

NO PRINTER ANYCUBIC PHOTON ULTRA

### Expected results

NO PRINTER ANYCUBIC PHOTON ULTRA

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NO PRINTER ANYCUBIC PHOTON ULTRA

**Comment by GregValiant** [comment]
Thanks for the report.
All non-Ultimaker printer definition files come from members of the community or from the individual printer manufacturer.  You should check with AnyCubic and see if they have definition files for your printer.  Maybe someone over on Reddit has a suggestion.
I'll close this as it is not an Ultimaker Cura bug.  I hope you understand.
