### ISSUE TITLE
Cura unexpected error

### ISSUE THREAD

**Issue by JPVenson** [Ultimaker/Cura#15546]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Ender 3V2 Neo

### Reproduction steps

1. Imported STL
2. Set To Low Quallity
3. Set infill to 20%
4. Set Support to Tree
5. Set Placement to Everywhere
6. Enabled Adhesion
7. Sliced
8. Set To Low Quallity

### Actual results

9. Slice throws error

### Expected results

Should not throw error and slice the file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3E3V2_Funky Tumelo (1).zip](https://github.com/Ultimaker/Cura/files/11502068/CE3E3V2_Funky.Tumelo.1.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11502072/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
From your log file "Backend exited abnormally with return code 3221225477!"
My understanding is that is a memory error.
I'll mark this as a duplicate and someone from the Cura team will look.

I didn't find any errors in the model and it sliced for me.
![image](https://github.com/Ultimaker/Cura/assets/64202104/1171f4b4-db5a-4b92-9351-5fa467e1ec23)

**Comment by JPVenson** [comment]
Maybe try the following:
Slice it with Tree Support & Adhesion enabled and change the qualltiy a few times ( i maybe tried it 8 times with only slightly different layer heights before that) maybe its a memory leak.

**Comment by JPVenson** [comment]
Tree support was just a bit faster and more efficient if i remember

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
