### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by lacierh** [Ultimaker/Cura#15554]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Ender 3 S1

### Reproduction steps

Fatiar

### Actual results

Não está fatiando

### Expected results

Fatiar 

### Checklist of files to include

- [X] Project file
- [ ] Log file

### Additional information & file uploads

Aumentei o projeto para 100mm

**Comment by MariMakes** [comment]
Hey @lacierh,

Desculpe, não falo português, mas acho que posso ajudá-lo.

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
