### ISSUE TITLE
slicing error?

### ISSUE THREAD

**Issue by CarrieSimba72** [Ultimaker/Cura#15551]
### Application Version

5.3.0

### Platform

Windows 11 I think?

### Printer

Anycubic Kobra Neo

### Reproduction steps

its been slow when trying to do commands like scale, move. I tried to slice something & it said slicing error. i am new to cura & the 3d world.

### Actual results

not sure

### Expected results

not sure

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![IMG_7456](https://github.com/Ultimaker/Cura/assets/133933785/d4dc1304-47ed-499e-af2e-e93941ef69a9)

**Comment by GregValiant** [comment]
Thanks for the report.
It could be a slicing bug, it could be the models, or it could be some conflict in your Cura settings or the printer definition.  This is why we ask for a project file.
Load the models and set Cura up to slice.  Use the "File | Save Project" command to create a 3mf project file.  In Widnows Explorer right-click on the 3mf file and select "Send To..." | Compressed (zipped) Folder".  Post the zip folder here.
