### ISSUE TITLE
Fehler bei Cura 5.2.1 entdeckt

### ISSUE THREAD

**Issue by Tommygmx** [Ultimaker/Cura#15568]
### Application Version

5.2.1

### Platform

Windows10

### Printer

Neptune2

### Reproduction steps

1. ein Objekt mit Thinkercad erstellt.
2. heruntergeladen
3. Mit Cura 5,2.1 gesliced
4. anschließen mit dem Elegoo Neptune 2 gedruckt
5. Müll erhalten

### Actual results

Ich habe einen Fehler bei Cura 5.2.1 festgestellt. Dabei verschwindet eine komplette Bohrung nach dem Slicen.
Vielleicht kennt jemand die Ursache.

### Expected results

wie kann dieser Fehler behoben werden?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://www.youtube.com/watch?v=3BUNXjMtpaA

**Comment by GregValiant** [comment]
Thanks for the report.
In the Mesh Fixes settings turn off "Remove all Holes".  Also make sure "Make Overhangs Printable" is turned off.  Those are specialty settings that aren't often used.
I will leave the bug label for now.  Let us know if that fixed the problem.
