### ISSUE TITLE
Wont Slice or Preview

### ISSUE THREAD

**Issue by BlahBlahBlah2323** [Ultimaker/Cura#15565]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Creatillity - Ender pro 3 V2

### Reproduction steps

loaded file, added support, clicked Slice, Bug (slicing fail with unexpecting error). Please help fix!

### Actual results

I get a big to report

https://github.com/Ultimaker/Cura/assets/134078831/4455988e-5a39-4fbb-a698-693ed6021c9a

### Expected results

Nothing, program sits there. Checked for updates, there are none.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Please help fix this issue.

https://github.com/Ultimaker/Cura/assets/134078831/050bfdcc-5885-4a3a-9869-543ad84ff5ee

**Comment by MariMakes** [comment]
Hey @BlahBlahBlah2323,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, to hear you are stuck 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
