### ISSUE TITLE
i have no idea what's happening 

### ISSUE THREAD

**Issue by toxictae** [Ultimaker/Cura#15562]
### Application Version

5.3.1

### Platform

windows 10 

### Printer

elegoo Neptune pro 

### Reproduction steps

i tryed to slice a spiderman shell but it just keeps saying slice failed 

### Actual results

i trued it again still nothing 

### Expected results

im at my wits end and need help

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

i m not sure

**Comment by GregValiant** [comment]
Thanks for the report.
You might have a faulty model, or it could be a slicing bug.

- Load the model and set Cura up to slice.
- Use the "File | Save Project" command to create a 3mf file.
- In File Explorer right-click on the 3mf file and select "Send Too | Compressed (Zipped) Folder".
- Post the zip folder here.
