### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by Last-rebel** [Ultimaker/Cura#15573]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

1 - Conflicts with Nvidia RTX graphics card.
Makes the screen flicker or frizz.
2 - Conflict also with the Arduino program.
Occasionally prevents the program from opening.

### Actual results

Non-permanent conflict.

### Expected results

Close Cura is the solution.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing

**Comment by GregValiant** [comment]
Thanks for the report.
5.0.0 had other issues as well.  I would suggest updating to 5.2.x.  (There have been complaints about 5.3.1 not handling curves very well.)
I would expect the Cura team to close this unless the problem has continued into the new versions.  They won't go back and update 5.0.0.  I hope you understand.
