### ISSUE TITLE
Bad slicing procces

### ISSUE THREAD

**Issue by FoxMulderX77** [Ultimaker/Cura#15578]
### Application Version

5.3.1

### Platform

Windows 10 PRO

### Printer

Ender 3 MAX

### Reproduction steps

I modeled a piece in Autodesk Maya and some other programs and saved it as an STL file

![image](https://github.com/Ultimaker/Cura/assets/114688444/8497e2d5-5b1c-4e36-8758-695266785523)
![image](https://github.com/Ultimaker/Cura/assets/114688444/a5a8e4d9-716f-4c57-9a59-bb8296e2fc45)

### Actual results

Sometimes the model looks fine in the _PREPARE_ tab, but once the program ends its slicing process the _PREVIEW_ tab shows a bad result in some areas and the model is too different and blocky in some areas making the piece unuseful
PREPARE TAB
![image](https://github.com/Ultimaker/Cura/assets/114688444/956f14dc-d37f-452d-bbc3-e21f5d19b8a6)
![image](https://github.com/Ultimaker/Cura/assets/114688444/ab5d7540-7541-4829-b35e-b3cc61e153d6)
PREVIEW tab
![image](https://github.com/Ultimaker/Cura/assets/114688444/d63c6a0b-4ce0-4fbc-bb9c-826d3e55ea2b)
![image](https://github.com/Ultimaker/Cura/assets/114688444/986a2f3a-ed3f-48f8-a34a-3a7be0585a81)
![image](https://github.com/Ultimaker/Cura/assets/114688444/e99732db-54bf-4df1-a30e-d6f5b6172366)

### Expected results

I was waiting for no errors at all

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://mega.nz/file/zMRgEDjD#Pu244FJ7ViON2M-ehJdoF2Rtp7bBN_AQ-O2JrxpPrBQ

**Comment by FoxMulderX77** [comment]
Sorry if this issue is already in the forums but I didn't find anything

**Comment by MariMakes** [comment]
Hey @FoxMulderX77,

Thanks for your report 👍
I believe I've spotted what is going wrong. 
You have the setting _Make Overhang Printable_ enabled.
This setting _changeS the geometry of the printed model such that minimal support is required._
![image](https://github.com/Ultimaker/Cura/assets/40423138/8557298c-eebe-4d2e-adb3-618cad717147)
I believe your model should look as expected if you disable the setting. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/b5554ffd-c74b-4e10-891c-01e46c467563)

To me, it doesn't seem like a bug in Ultimaker Cura anymore, but an issue with setting choices. 
Would you still like to keep this issue open or do you agree that we can close it?
