### ISSUE TITLE
Support issue

### ISSUE THREAD

**Issue by slyht3rin** [Ultimaker/Cura#15588]
### Application Version

5.3.1

### Platform

windows 10 64bit

### Printer

Custom that I always use

### Reproduction steps

I'm trying to slice my model and with tree supports on it will not slice and gives an error everytime

### Actual results

nothing it doesn't slice unless I turn on different supports or no supports

### Expected results

it should allow tree supports

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://github.com/Ultimaker/Cura/assets/134340446/0407fe81-029d-4d6c-9b17-819c9bf06047)

**Comment by GregValiant** [comment]
Thanks for the report.
There is no way to tell what might be going on without a Project File.  Use the File/Save Project command and then zip the file and post the zip folder here.
