### ISSUE TITLE
Incorrect model size

### ISSUE THREAD

**Issue by martin66789** [Ultimaker/Cura#15585]
### Application Version

5.3.1

### Platform

Windows 10

### Printer

Creality Ender 3 V2

### Reproduction steps

I ran into a problem where I drew a cylindrical part in Solid Edge 2023 Community Edition that is Ø50x7mm. I saved this file as a *.stl file and opened it in UltiMaker Cura. In the UltiMaker Cura, the shape appears as a very small model 2.0x2.0x0,3mm.
What could cause this? Maybe a misconfiguration?

### Actual results

In the UltiMaker Cura, the shape appears as a very small model 2.0x2.0x0,3mm.

### Expected results

What could cause this? Maybe a misconfiguration?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Solid Edge 2023 Community Edition:
https://i.imgur.com/6dhmG2X.jpg

UltimakerCura:
https://i.imgur.com/jQksEaJ.jpg

**Comment by Asterchades** [comment]
Make sure that Solid Edge is exporting with the correct base unit. Cura will import any and all STL files as if the base unit is the millimetre (not at all unreasonable for 3D printing purposes), but with a 25.4:1 reduction occurring I suspect you're model is being exported in Inches instead. While STL does have unofficial extensions which allow the base unit to be recorded these are not recognised by most programs - including Cura.

If you need to preserve the base unit for any reason you'll need to use the 3MF format instead. This newer format includes facilities to store and recall units for every model contained there-in.
