### ISSUE TITLE
Bridges everywhere

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#15602]
### Application Version

5.3.1

### Platform

Windows 10

### Printer

UM 3

### Reproduction steps

Slice (and print) attached file with and without Enable Bridge Settings enabled.

### Actual results

Layers create a set of vertical walls instead of a solid part.

Each layer has the same less than fully dense infill in the same direction rather than alternating.

Bridges are generated on each layer on the same locations, which build up walls.

![image](https://github.com/Ultimaker/Cura/assets/8895761/6c297826-6e00-4c98-b863-5921586ed58d)

### Expected results

Bridges shouldn't be triggered for these objects. They are lithophanes without any overhangs.

Every layer should be fully dense with top skin at 90* wrt the prev layer.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UM3_separators_and_tops.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/11552179/UM3_separators_and_tops.3mf.renamed.zip)

Perhaps a relevant factor is the cutting mesh used in this project.

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I can't duplicate the problem using your project file.  I get the normal 45°, 135° cross hatch of the top and bottom lines.
![image](https://github.com/Ultimaker/Cura/assets/64202104/94581706-228a-4937-af79-d3f48f7f1b2c)

You have that cutting mesh in there but it doesn't have any settings.  Am I missing something?
If you look at my screenshot you will see that the tab for extruder 1 is missing.  Within the machine settings the printer is configured with two extruders.  That looks like some sort of glitch.  When I tried to enable extruder 1 the whole build plate went to "can't slice" mode and the extruder 2 tab disappeared as well.
I've been working with a dual extruder printer today and I haven't had any trouble.  I think that there might be something wonky in the project file.
I agree that something isn't right but I think the "bridges everywhere" is a symptom of something deeper.
The Cura team will take a look.  Could you prepare another project file and post it?  Maybe it will help chase this down.
