### ISSUE TITLE
Slice Failure

### ISSUE THREAD

**Issue by daveh0805** [Ultimaker/Cura#15604]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

1. Added 2 files to print using pre selected profile.
2. Clicked on "Slice"

### Actual results

Slicing Failed with an unexpected error

### Expected results

Files sliced and ready to export to folder

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://github.com/Ultimaker/Cura/assets/134565890/9a2d0967-6904-4b65-97b1-2e1c2a115285)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura log there isn't much we can do.
