### ISSUE TITLE
How to set Z-offset of second nozzle?

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#1560]
Prusa like 3d printer with dual  independent extruders. 
I need to set Z-offset when I switch to second extruder.
But there are only X and Y offsets in config files.
How to set?

**Comment by Ghostkeeper** [comment]
There's no feature like that yet. I'll have it added to our tracker.

**Comment by fieldOfView** [comment]
How does the UM3 handle it then? Purely in the firmware?

**Comment by fieldOfView** [comment]
I hope to finish support for Machine Settings for multiextrusion printers, which will let you edit extruder switch gcode snippets. I think those snippets could include the Z offset too?

**Comment by karabas** [comment]
Its impossible via firmware. Even if you remove nozzle and put it back there is a possibility of its height changing...

**Comment by karabas** [comment]
As a workaround I use M218 command in Marlin RC-bugfixed. After some code hacks it works. But currently does not save via M500

**Comment by Ghostkeeper** [comment]
Our product manager just rejected this issue because it had been inactive for three months.
