### ISSUE TITLE
 bug add stl

### ISSUE THREAD

**Issue by fab7294** [Ultimaker/Cura#15614]
### Application Version

5.3.1

### Operating System

ventura 13.2

### Printer

ender 3

### Reproduction steps

opening of CURA.
press the tab to insert an stl file.
select the file, press open

nothing happens on cura, no display of the stl

### Actual results

nothing on the bed after 5 minutes.

### Expected results

the stl should appear and I should be able to cut it.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by GregValiant** [comment]
Thanks for the report.
Sometimes, if there is location data in the model file, the model will come in way out of bounds.  It's there but you can't see it.
Just for a check, open the STL and then right-click on the build plate and "Select all Models".  Select the Move Tool on top of the left toolbar and see if there are X,Y,Z locations.  If there are then set them to 0,0,0 and the model should be on the build plate.  If not, then we can continue with this as a bug report.
