### ISSUE TITLE
Slicing fails with layer height of 0.1

### ISSUE THREAD

**Issue by treaves** [Ultimaker/Cura#15636]
### Cura Version

5.3.1

### Operating System

MacOS Ventura

### Printer

Creality Ender 3 S1 Pro

### Name abnormal settings

Slices fine with layer height of 0.08 and 0.12; just not 0.1

### Describe model location

No change if rotated

### Describe your model

It's a pack mule DnD miniature

### Add your .zip here ⬇️

I can't attach the zip file, as it's 56 MB.  I can email it if someone wants.

**Comment by treaves** [comment]
Ah. Moving it out of the center, then rotating 30 degrees allowed it to slice. 

Thanks.

**Comment by SFireblood** [comment]
go to rotation and click on the button that says lay flat. that's what helped me
