### ISSUE TITLE
Supports/bed adhesion not generated in CURA

### ISSUE THREAD

**Issue by Causeimbored** [Ultimaker/Cura#15631]
### Application Version

5.3.0

### Operating System

windows 11

### Printer

Creality Ender 3 pro

### Reproduction steps

I recently changed the nozzle on my printer from a .5mm to a .4mm. I changed the setting in Cura to reflect this.  However, when I went to print this, I noticed that it wasn't generating any supports or bed adhesion in the software. When I tried to print a benchy with generated support (support angle 0.0 degrees just to see if they would print) and raft the printer failed to print.

 

### Actual results

The Benchy printed without raft or supports

### Expected results

The benchy should have printed with a raft and supports generated

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_3DBenchy.zip](https://github.com/Ultimaker/Cura/files/11601530/CE3PRO_3DBenchy.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I can't duplicate this with your project file.
Here is the slice
![image](https://github.com/Ultimaker/Cura/assets/64202104/50f7916f-7565-4991-a777-91d0300189ab)

Here is a snippet from the Gcode.
;TYPE:SUPPORT
G1 F1500 E204.07183
G1 F2243 X117.953 Y121.937 E204.10368
and another
;TYPE:SUPPORT-INTERFACE
G1 F1500 E208.78035
G1 F3000 X118.08 Y103.07 E208.79254

The Cura gcode reader is separate from the slicer.  If you open the Gcode file in Cura you will get an accurate view of the generated gcode.
I read the gcode into AutoCad to take Cura totally out of the loop and the gcode is fine.

Post a "bad" gcode file and I'll look.
