### ISSUE TITLE
Incorrect path from prime tower.

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#1563]
In dual nozzle mode and offset on first extruder. Prime tower is on.
After printing prime tower head goes firstly not directly to model(as expected) but to the point of the tower BUT with no offset applying and then  immediatly to model. The same with both extruders.

**Comment by Ghostkeeper** [comment]
After printing a prime tower, it'll still be in the prime tower. You say it's then going to the corner of the prime tower, but it should already be in the corner of the prime tower because it just printed the prime tower. Or am I visualising this wrongly? Perhaps a picture or some example g-code could illustrate what's going wrong?

**Comment by karabas** [comment]
It seems as  prime tower last printing coordinate looses offsets (coordinates of prime tower). So head goes far beyond the prime tower, as if prime tower located in another place, and after  to model Situation is similar to delta bug of prime tower shadow. Or maybe "extruder_prime_pos_CCCC" settings suddenly turn on.

**Comment by Ghostkeeper** [comment]
I'm not reproducing this. I've sliced a dual-colour print with a printer where the first extruder had 7mm y-offset and the second extruder had 18mm x-offset. No strange travel moves. Goes directly to the model after the prime tower of the layer is completed.

**Comment by karabas** [comment]
![cura2 5b_1_2017-03-28_10-19-01](https://cloud.githubusercontent.com/assets/67457/24393351/13f127f8-1398-11e7-9c7e-682957de4930.png)
![cura2 5b_2_2017-03-28_10-19-01](https://cloud.githubusercontent.com/assets/67457/24393378/33057464-1398-11e7-80fb-34ee9cf79846.png)

You can see that additional side pathes appears. Marked with red arrows.
The only difference is Prime Tower on/off. If I change pos of prime tower red pathes are moves correspondently.

**Comment by Ghostkeeper** [comment]
I agree that this definitely looks like a bug. I've tracked this in our internal issue tracker (CURA-3612).

**Comment by karabas** [comment]
My  distance between nozzles is very big - ~87mm along the X axis.  You may see on the pics that it is exactly the same distance to left and right wrong movement points.

**Comment by Ghostkeeper** [comment]
Our product manager just rejected this because it was inactive for 3 months.

**Comment by ianpaschal** [comment]
CURA-3612 is marked as fixed as of August 2017.

**Comment by Ghostkeeper** [comment]
No, it's not. It's put in the category for deferred issues.
