### ISSUE TITLE
 Slicing Failed

### ISSUE THREAD

**Issue by jhi2** [Ultimaker/Cura#15643]
### Cura Version

5.3.0

### Operating System

windows 11

### Printer

anycubic korbra neo

### Name abnormal settings

I changed support to tree

### Describe model location

it works if I change support to normal 

### Describe your model

yes I hive sliced my model secesfully before

### Add your .zip here ⬇️

[CFFFP_alein.zip](https://github.com/Ultimaker/Cura/files/11618112/CFFFP_alein.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
About that project...is this what it is supposed to look like?  I didn't have any trouble slicing it but I have no idea what I'm looking at.  Why are all those pieces up in the air?
![image](https://github.com/Ultimaker/Cura/assets/64202104/91c0c37d-a299-4164-abee-282a89e120c7)
