### ISSUE TITLE
Updated an STL, now slicing fails.

### ISSUE THREAD

**Issue by DragonDon** [Ultimaker/Cura#15644]
### Cura Version

5.3.1

### Operating System

Windows 11 Pro

### Printer

Ender 5 Plus

### Describe your model

A open box on one end with a cylinder attached and an internal 'funnel' to guide airflow.

### Add your .zip here ⬇️

[CE5PLUS_Toaster_Part-v2.zip](https://github.com/Ultimaker/Cura/files/11618495/CE5PLUS_Toaster_Part-v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing it.  There is a bug that has been reported numerous times.  It keeps a model from slicing if it is at the midpoint of the Cura build plate.  There are a couple of workarounds.

- Move the model to a different place on the build plate.
- Rotate the model.
- Change the Initial Layer Height by a little bit.
- Switch to Normal Supports (tree supports aren't indicated for that model anyway).

I'll mark this as a duplicate.  Let us know of any of the workarounds were effective.

**Comment by DragonDon** [comment]
> Thanks for the report and the file. I didn't have any trouble slicing it. There is a bug that has been reported numerous times. It keeps a model from slicing if it is at the midpoint of the Cura build plate. There are a couple of workarounds.
> 
> * Move the model to a different place on the build plate.
> * Rotate the model.
> * Change the Initial Layer Height by a little bit.
> * Switch to Normal Supports (tree supports aren't indicated for that model anyway).
> 
> I'll mark this as a duplicate. Let us know of any of the workarounds were effective.

Hi Greg,

Not sure what it was but I simply tried again and it sliced.  Tree Supports were selected.

Thanks any ways.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
