### ISSUE TITLE
added STL and got eerror Canot slice due to error

### ISSUE THREAD

**Issue by numpty9989** [Ultimaker/Cura#15652]
### Application Version

5.3.1

### Operating System

Windows 11

### Printer

Voxlab Aquila

### Reproduction steps

add stl
click slice as settings are fine
gets small way into then stops and gives the error "failed to slice due to unexpected error. please consider reporting a bug on our bug tracker"

### Actual results

nothing didn't slice model

### Expected results

sliced model ready to print

[We Transfer Log File](https://we.tl/t-STyL7EJdsz)
[We Transfer Project File](https://we.tl/t-GwXolcfs80)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[We Transfer Log File](https://we.tl/t-STyL7EJdsz)
[We Transfer Project File](https://we.tl/t-GwXolcfs80)

**Comment by GregValiant** [comment]
Thanks for the report.
I see the gcode file there in the "We Transfer Project" file, but no actual model file or Cura Project file.  It looks like you got it to slice.  Here is the gcode file opened in Cura.
![image](https://github.com/Ultimaker/Cura/assets/64202104/84d44dbf-7058-48b7-b090-e5ce4fb2c595)

So I don't see a problem.  Can you explain more??
(If you load the model and use the File | Save Project command, then zip the 3mf project file you can post the zip folder here.)
