### ISSUE TITLE
Crashes on 5X scale, works on 3X scale

### ISSUE THREAD

**Issue by budnik** [Ultimaker/Cura#15666]
### Cura Version

5.3.1

### Operating System

macOS 13.0.1 (22A400)

### Printer

Sovol SV06 plus 

### Name abnormal settings

-

### Describe model location

Moving and rotating would not help

### Describe your model

Worked well at 300% scale of orignal Fails on 500%

### Add your .zip here ⬇️

[SSP_toothless.3mf.zip](https://github.com/Ultimaker/Cura/files/11638829/SSP_toothless.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It wouldn't slice for me either.  I kept moving it around and then rotated it.  It finally sliced.
This bug has been reported numerous times and the Cura team is well aware of this.  I'll mark this as a duplicate and go ahead and close this report.  I hope you unnderstand.

This slice is at your 5X scale.
![image](https://github.com/Ultimaker/Cura/assets/64202104/3a311c18-e3eb-4770-99c5-2ddb2ffd8f12)
