### ISSUE TITLE
Filament cost limitations for certain currencies

### ISSUE THREAD

**Issue by w00kie** [Ultimaker/Cura#1567]
I just installed Cura 2.5 Beta and tried loading up my material costs but ran into an issue: I live in Japan so I set the currency to JPY and a spool of Ultimaker PLA costs 9,000 JPY but the `filament cost` field will not accept values over 999.99.

This will be a problem for users in Korea too where the spool cost would be 90,000 KRW

**Comment by fieldOfView** [comment]
Thanks for reporting. I failed to take that into account.

**Comment by nallath** [comment]
Closing this issue so we can continue with the pull request.
