### ISSUE TITLE
no nozzle size for flsun v400

### ISSUE THREAD

**Issue by Zacrye** [Ultimaker/Cura#15679]
### Application Version

5.3.1

### Operating System

windows 10

### Printer

flsunv400

### Reproduction steps

reinstalled cura

### Actual results

no nozzle size options, go to machine settings, non there as well

### Expected results

I want to adjust nozzle size to basic 0.4mm

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by GregValiant** [comment]
I'll close this today.
