### ISSUE TITLE
could not slice

### ISSUE THREAD

**Issue by ajscrit** [Ultimaker/Cura#15678]
### Cura Version

5.3.1

### Operating System

Mac os Ventura

### Printer

AnkerMake 5

### Name abnormal settings

did a 45% infill

### Describe model location

enter

### Describe your model

sleeping cat with wings

### Add your .zip here ⬇️

[angel_cat_final.stl.zip](https://github.com/Ultimaker/Cura/files/11646363/angel_cat_final.stl.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the file.
Have you tried moving the model around on the build plate?  Rotating it?  Changing the Initial Layer Height?
If any of those work then this bug has been reported.  Let us know so we know how to categorize this report.
