### ISSUE TITLE
Tree Support generating outside of build area

### ISSUE THREAD

**Issue by Kethiannne** [Ultimaker/Cura#15696]
### Application Version

4.12.0

### Operating System

Windows 10

### Printer

Custom FFF Printer: Anycubic Kobra Neo

### Reproduction steps

I attempted to fit two large models on my build plate, with them being fairly close to the edge of the plate at the corners.
Here are my support settings:
![image](https://github.com/Ultimaker/Cura/assets/75802954/2e6b35cd-994c-4410-a843-23b9988df7b8)
and my build plate adhesion settings:
![image](https://github.com/Ultimaker/Cura/assets/75802954/d060b8fb-f992-4271-8867-2113c87474cc)

### Actual results

It drew the supports outside the build plate area:
![image](https://github.com/Ultimaker/Cura/assets/75802954/ad42072c-51aa-4552-a36a-09c6f2469e75)

### Expected results

I expected it to make some funky tree supports that weave into the hard to reach places of my models and let them build properly. Which they do, I suppose, but my printer can't actually move the extruder where it would need to

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[CFFFP_frame-holder.zip](https://github.com/Ultimaker/Cura/files/11682281/CFFFP_frame-holder.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That was a known bug up to about Cura 5.1.  You would need to upgrade Cura to eliminate the behavior.  Starting with Cuura 5.3 the behavior was changed to cut the brim off at the edge of the build area.
I had to export your model and repair it with MS 3D Builder.  The image below shows repaired models and you can see that Cura has pushed the brim to the edge, but it is cutoff there.
I'm going to go ahead and close this as the problem has been addressed.  You can still respond in this thread.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7ca5a7b3-1d3e-4498-8399-941e3895f4ac)
