### ISSUE TITLE
Cura set always own gcode

### ISSUE THREAD

**Issue by ManuelW77** [Ultimaker/Cura#1569]
if i set my own gcode for temps with variables {material_print_temperature_layer_0}, Cura set this temps but place its own temp code in the beginning of the gcode also. In 2.4 Cura set no own temps when the variables for this was set in the gcode already.

**Comment by Ghostkeeper** [comment]
It still doesn't set the temperature at the start when `{material_print_temperature}` is in the start g-code. It doesn't pay attention to `{material_print_temperature_layer_0}` though. I'd say that is a bug.

**Comment by Ghostkeeper** [comment]
The `material_print_temperature_layer_0` not being detected should be fixed in version 2.6.
