### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by DrPerry97** [Ultimaker/Cura#15693]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Neptune 2s

### Describe model location

In the middle of the plate

### Describe your model

chainlink for a kobra max

### Add your .zip here ⬇️

[CE3E3V2_widened_platform_chain_mount_V2.2_Stronger.3mf.zip](https://github.com/Ultimaker/Cura/files/11680317/CE3E3V2_widened_platform_chain_mount_V2.2_Stronger.3mf.zip)

close cura and start it again and it works. 
I sliced the same model for my kobra max then I changed the printer to neptune 2s and tried it again. It fails. 
After changing the support from tree to normal it works

**Comment by GregValiant** [comment]
Thanks for the report and the file..
I didn't have any trouble slicing this.  You can try moving the model on the Cura build plate.  Sometimes rotating the model can fool this bug as can changing the Initial Layer Height by a little (like from .20 to .22).

This bug has been reported numerous times and the Cura team is aware of it.  I'll mark this as a duplicate slicing error and go ahead and close this.  I hope you understand.
