### ISSUE TITLE
models not resliced after Clear build platform

### ISSUE THREAD

**Issue by mvangils** [Ultimaker/Cura#157]
Version: 15.06.02
Platform: Windows 7 64Bit
Qt: ???
PyQt: ????

Error:
i put 2 models on the build platform and generated the gcode for it to the sdcard (safe removed after). then used right mouse button and clear build platform to clear the models. dragged two new models into the open cura window. inserted another sdcard and pressed safed to sdcard. it saved under the correct name, however the models printed where not the new ones i put on the buildplate. it printed the first 2 models. Layerview also didn't work for the new models.

altering one of the speed settings made the layerview gcode appear and when resaved it printed the correct models. 

My laptop:
i5 2,5ghz
8GB DDR
Intel HD Graphics 3000 512 MB

**Comment by awhiemstra** [comment]
As far as I can tell this works. Any chance you can share the models with which this happens?
