### ISSUE TITLE
This is a serious bug regarding slicing algorithms.

### ISSUE THREAD

**Issue by SuperDeron** [Ultimaker/Cura#15714]
### Application Version

5.3.1

### Operating System

windows10-intel11700K-NV3070Ti

### Printer

Voron2.4-R2-350mm

### Reproduction steps

![1](https://github.com/Ultimaker/Cura/assets/133164701/2691d6fe-bfcd-4692-a990-52f23c250cf5)
![2](https://github.com/Ultimaker/Cura/assets/133164701/9106b1ba-8f9b-4b55-a3f8-e02b51c0bb3f)
![3](https://github.com/Ultimaker/Cura/assets/133164701/6d31c433-4809-44c3-9aa7-da778ceba357)
![4](https://github.com/Ultimaker/Cura/assets/133164701/171a91a8-0ab4-406f-8bfc-c003e975cd4c)
![5](https://github.com/Ultimaker/Cura/assets/133164701/86be2d9b-8076-4331-a1b9-7d08af07094b)
![6](https://github.com/Ultimaker/Cura/assets/133164701/18a64322-5ee0-4b65-982d-8e7c953894a2)
I found this bug when printing this pipeline model, and only returned a query to find that it was caused by cura slicing. The same parameters were not found to be problematic in prusaSlicer, but the problem was that curved pipeline models like this would experience layering issues when reaching a certain height, some appearing externally and some internally, which is related to the volume of the model. The location is approximately 10% of the total height, I only discovered this issue on the surface of the model after printing, which is a serious bug. I hope Cura can take it seriously. Thank you.

### Actual results

A circular step or staggered layer appears in the printed product.

### Expected results

I hope Cura can solve this serious bug as soon as possible.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![1](https://github.com/Ultimaker/Cura/assets/133164701/9ab5aabe-dbe3-4608-92cd-408ef0258527)
![2](https://github.com/Ultimaker/Cura/assets/133164701/b36c78dc-d399-4414-979c-1188b43e22b9)
![3](https://github.com/Ultimaker/Cura/assets/133164701/98fd1cb8-8738-4b1c-911b-b3692e1813c1)
![4](https://github.com/Ultimaker/Cura/assets/133164701/01ae1721-d6cd-4103-bd31-0ab9ab7abe6f)
![5](https://github.com/Ultimaker/Cura/assets/133164701/3971366f-5c1d-4cfe-a6cc-642ca00c03ae)
![6](https://github.com/Ultimaker/Cura/assets/133164701/30132f71-395f-4514-9f5f-b0dd84755129)

**Comment by smartavionics** [comment]
Set hole horizontal expansion to zero?

**Comment by GregValiant** [comment]
That's what it looks like to me.
@SuperDeron this looks like a settings issue.  See if Hole Horizontal Expansion is set to "0" and re-slice.  See if that ledge goes away.
I'll leave this open for new but it looks like expected behavior.  If you would post a project file it would be helpful.

**Comment by SuperDeron** [comment]
It is indeed a problem with the holes, but I was negligent. Thank you for your help.
