### ISSUE TITLE
Gyro from Ultimaker PVA video

### ISSUE THREAD

**Issue by Chichnillasrcute** [Ultimaker/Cura#15717]
### Cura Version

5.3.1

### Operating System

Windows server 2019

### Printer

Ultimaker S5

### Name abnormal settings

Supports should work, as the were in the video, the only changes were in making wall thickness equal and sizing it up

### Describe model location

No

### Describe your model

I have but it was a black ABS. i need it as green PLA

### Add your .zip here ⬇️

https://we.tl/t-QSOZcp5Kya
(project file)

**Comment by fieldOfView** [comment]
I think you may have forgotten to say what your problem is. We need way more information to help you.

**Comment by rozmansi** [comment]
This is a duplicate of #15715. Reported twice due to bad family communication, sorry.

**Comment by Chichnillasrcute** [comment]
Still maybe try slicing and posting a .ufp, maybe

**Comment by Chichnillasrcute** [comment]
never mind this issue.  post to #15715
