### ISSUE TITLE
Cura connection problem

### ISSUE THREAD

**Issue by GabyChab** [Ultimaker/Cura#15734]
### Application Version

5.3.1 / 5.3.0 / 5.0.0

### Operating System

W11 

### Printer

ultimaker S5

### Reproduction steps

1. I did nothing 
2. Cura loose the connection with my printer.
3. I switch it off and it says connected and 3 min after not anymore.
4. I tried to change the Cura version, but it doesn't shows any differences
5. My collegue tried, he got the same result as me.

### Actual results

Hello, 
I've got a connection problem between Cura and my S5 printer.
Everthing was working well and suddendly, I didn't touch anything, Cura was not anymore connected to the printer.
Then I reboot everything it says connected and 3 min after not anymore.
I tried to switch all off again, but it don't work. 
Cura says that my printed is non reachable. 
After that my collegue tried too, and he got the same problem.
Can you help me ? 
Thanks by advance ! 

### Expected results

How I can fixed this problem ? 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don't have any file.

**Comment by MariMakes** [comment]
Hey @GabyChab,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried the troubleshooting steps mentioned in this support article? https://support.makerbot.com/s/article/1667417632472

Other than that, we don't have enough information to troubleshoot your issue. 

Can you also show some screenshots of what you are seeing before and after you lose your connection? 
Your CuraLogs would really help here. You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log 

Thank you 🙏
