### ISSUE TITLE
Feature Request: Horizontal Expansion on Initial layer

### ISSUE THREAD

**Issue by Labern2** [Ultimaker/Cura#1573]
The squish factor that helps make prints stick to the glass also leaves the print with a sharp edge on the bottom.
If you could adjust the horizontal expansion and enter a - amount (eg -0.3) then this will remove the sharp edge and make the print square on the bottom. I have done tests with this by adding 2 stl's. One was the height of the Initial layer which I used per object settings to enter the -0.3 horizontal expansion. merged the 2 stl's and got a print with a square edge on the base.
This would allow a more aggressive initial layer and not distort the prints base to get strong adhesion.

**Comment by Ghostkeeper** [comment]
That's basically what Brim does, isn't it?

**Comment by Labern2** [comment]
No. It's kinda the opposite of brim. 
the initial layer is designed to squash onto the glass. The more squash the stronger it sticks to the glass.
the squashing action makes the line width wider and it ends up wider than the actual parts dimensions. If you print a part with skirt selected, you end up with a tiny brim from the squashed initial layer.
This can effect parts that need dimensional accuracy like an internal threaded hole and it makes the part sharp on the bottom.
But if you use horizontal expansion more as horizontal contraction on the initial layer you can remove the tiny brim or sharp edge.
Pictures shown are print placed upside down. One showing the sharp edge the other was with my modified horizontal expansion settings set to -0.3. Not perfect examples but illustrates my point.
![img_20170313_052712](https://cloud.githubusercontent.com/assets/17557978/24291734/14f93eac-10ef-11e7-9fb9-695961ea890f.jpg)
![img_20170313_052633](https://cloud.githubusercontent.com/assets/17557978/24291740/17277108-10ef-11e7-960e-63a794e443c6.jpg)

**Comment by Ghostkeeper** [comment]
Ah, I see. It's to compensate elephant feet. Well, that could help. I'm making a feature ticket and we'll see what the planning allows.

**Comment by Ghostkeeper** [comment]
Apparently the planning didn't allow it. Our product manager just said we aren't going to do this.

**Comment by Dim3nsioneer** [comment]
But you would accept a proper pull request if someone from the community does it, right?

**Comment by fieldOfView** [comment]
That is generally the case.

**Comment by fieldOfView** [comment]
> But you would accept a proper pull request if someone from the community does it, right?

Let's test that theory.
It was fairly trivial to implement.

**Comment by fieldOfView** [comment]
Feature has been implemented for Cura 2.7. This issue can be closed

**Comment by Dim3nsioneer** [comment]
Thanks to all who made this happening. Great.

**Comment by Labern2** [comment]
This is awesome. Thanks.
