### ISSUE TITLE
Support : Tree, Support wall line count : 1 and Support Density : 0% does not slice

### ISSUE THREAD

**Issue by nbourre** [Ultimaker/Cura#15738]
### Cura Version

5.3.0

### Operating System

Windows 11

### Printer

Modified Ender 3

### Name abnormal settings

Support structure : Tree, Support wall line count : 1, Support Density : 0

### Describe model location

Normal local

### Describe your model

I've already sliced this model before with different settings

### Add your .zip here ⬇️

[CCR20_Feeder with glass insert.zip](https://github.com/Ultimaker/Cura/files/11734884/CCR20_Feeder.with.glass.insert.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
When I first sliced it the Support Walls and Support Density were both set to "0".  That won't work.
I set the Support Walls to "1" and it still sliced so I'm unable to duplicate the problem.
This isn't the first one where that has happened.  Have you tried moving the model around on the Cura build plate, or rotating the model?  Those and changing the Initial Layer Height by a little bit will often fool this bug.  You could also use normal supports as tree supports aren't really indicated for this model.
I'll mark this as a duplicate and go ahead and close it as the Cura team has a lot of examples of  this behavior.  The report is appreciated and we hope you understand.
