### ISSUE TITLE
Slicing failed after selecting wire printing.

### ISSUE THREAD

**Issue by moadster** [Ultimaker/Cura#15754]
### Cura Version

5.3.1

### Operating System

Windows 10 64 bit

### Printer

FLSun V400

### Name abnormal settings

Wire Printing

### Describe model location

No

### Describe your model

Sliced many times.

### Add your .zip here ⬇️

[6in Vice Soft Jaws 1.1.zip](https://github.com/Ultimaker/Cura/files/11750914/6in.Vice.Soft.Jaws.1.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Wire printing is broken in 5.3.1 and I've read that it is slated to be removed from Cura.
This isn't the first report of this and I'll mark this as a duplicate and go ahead and close it.  I hope you understand.
