### ISSUE TITLE
[5.3.1] Slicing Error

### ISSUE THREAD

**Issue by clems77750** [Ultimaker/Cura#15753]
### Application Version

5.3.1

### Operating System

win 11

### Printer

geeetech misar s

### Reproduction steps

j'ai effectue mes réglages et quand je veut découpe cela me dit : échec de la découpe avec une erreur inattendue

### Actual results

rien . impossible de creer mon fichier .ni meme generer un apercu

### Expected results

faire ma decoupe et generer mon g code

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

aucun

**Comment by MariMakes** [comment]
Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.

Hey @clems77750,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
