### ISSUE TITLE
print slicer failed

### ISSUE THREAD

**Issue by Pangalang** [Ultimaker/Cura#15760]
### Cura Version

5.3.1

### Operating System

macbook air 2015

### Printer

Neptune 2s

### Name abnormal settings

no

### Describe model location

yes

### Describe your model

no and its an aligator

### Add your .zip here ⬇️

80026

**Comment by MariMakes** [comment]
hey @Pangalang,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
