### ISSUE TITLE
Slicing fails when tree supports selected

### ISSUE THREAD

**Issue by chrisschnabel** [Ultimaker/Cura#15767]
### Cura Version

5.3.1

### Operating System

Ubuntu 22.04.2 LTS

### Printer

Monoprice Maker Select Plus

### Name abnormal settings

Support Type = Tree (works for normal)

### Describe model location

Yes, when rotated to side, slicing does not fail.

### Describe your model

The slicing works unless support type = tree, in the configuration as loaded from stl.

### Add your .zip here ⬇️

The attached design does not slice when support type = tree. If it is rotated with support type = tree, it will slice. If it is support type normal, it will slice.

[Delta Dust Chute 900025 V1.1.zip](https://github.com/Ultimaker/Cura/files/11775817/Delta.Dust.Chute.900025.V1.1.zip)

**Comment by chrisschnabel** [comment]
Original step file available here: https://cad.onshape.com/documents/f50737f67745fbc14bddb27c/w/fcff1aa7f56bb194fb5486f6/e/246072fe9c26f68a52c3ee36?renderMode=0&uiState=648ccc43e4a27c25f992bcdc

**Comment by chrisschnabel** [comment]
This works now with the new version! Thank you!

**Comment by MariMakes** [comment]
Great! I'll close this issue.
