### ISSUE TITLE
The nesting in cura doesn't work well

### ISSUE THREAD

**Issue by Kreyren** [Ultimaker/Cura#15778]
### Application Version

5.3.1

### Operating System

GNU Guix (297ba5c15a32845ab8514aeb6f405ebd4290142d)

### Printer

Prusa i3 MK3S (Modded version of FabLab Brno to include FabLab Management)

### Issue

I am trying to make an optimized build of the [InputLabs's Alpakka controller](https://inputlabs.io/alpakka), but Cura is unable to nest the parts for me to optimize the printing for it:

![image](https://github.com/Ultimaker/Cura/assets/11302521/2a4907ec-933f-4f79-b902-983b71d9a027)

requiring me to manually reorient all the parts which is very painful and wasting a lot of time:

![image](https://github.com/Ultimaker/Cura/assets/11302521/d18e83da-b1ac-4043-a5ef-254cae18d577)

Proposing to implement a better nesting solution.

### Steps to reproduce

The printable parts can be downloaded from https://github.com/inputlabs/alpakka_case/releases/tag/0.88.0

Import the 3mf file variation of parts with the exception of `Print_E.3mf` (as that is a technical part requiring a conductive material) in cure, try to automatically arrange it for printing and expect a failure

### Blockers

Contribution to the InputLabs that automatically creates a sliced project files to make the complicated and exhausting process of printing the parts into just drag and drop on the printer.

### Relevants

* Fabrication tracker for the controller https://git.dotya.ml/kreyren/kreyren/issues/61

**Comment by GregValiant** [comment]
Thanks for the report.
Cura does not work with the parts as such, but rather the "bounding box" that contains the shape of the part.  A bounding box only has Length, Width, and Height.  It simply isn't possible to inter-leave the parts as you show.

I'll remove the bug label from this and close it.  I hope you understand.
