### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by ryee-dev** [Ultimaker/Cura#15773]
### Cura Version

5.4.0

### Operating System

macOS  Ventura 13.4

### Printer

flsun super racer

### Describe your model

lots of cute animal figures

### Add your .zip here ⬇️

[all-the-animals.3mf.zip](https://github.com/Ultimaker/Cura/files/11778449/all-the-animals.3mf.zip)

**Comment by GregValiant** [comment]
I can't open that file.
Use the File | Save Project command to create a 3mf project file.  Zip the file and post the zip folder here.
