### ISSUE TITLE
Parts of support are missing

### ISSUE THREAD

**Issue by Anwah** [Ultimaker/Cura#15782]
### Application Version

5.3.1

### Operating System

windows

### Printer

Elegoo Neptune 3

### Reproduction steps

Tried slicing a mask on Cura but for some reason the support just hangs in the middle of the air and does not connect to the mask and on some parts does not connect to the bed.

### Actual results

Ive tried it many times and still the same result for this specific mask.

### Expected results

Same thing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (2)](https://github.com/Ultimaker/Cura/assets/136919395/0a922b69-3081-45be-89fd-d7ff9f849287)

**Comment by MariMakes** [comment]
Hey @Anwah,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

That's odd 🤔, I would love to take a closer look at what is happening.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
