### ISSUE TITLE
Standard profiles not available in 5.4.0 beta 1

### ISSUE THREAD

**Issue by JanLie19** [Ultimaker/Cura#15812]
### Application Version

5.4.0 beta 1

### Operating System

windows  11 

### Printer

ender 3 S1

### Reproduction steps

open a stl file
try to select a slicing profile

standard profiles not available

### Actual results

standard profiles not avalable

### Expected results

stan dard profile not available 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Schermafbeelding 2023-06-19 174728](https://github.com/Ultimaker/Cura/assets/137032457/749541f2-001f-4077-bcbd-abf9b1130666)

**Comment by GregValiant** [comment]
Thanks for the report.
I installed an S1 and all the built-in profiles showed up including "Standard" so I'm unable to duplicate this.
Someone from the Cura team will take a look and hopefully have a suggestion for you on what to look at.
