### ISSUE TITLE
Cura 5.4.0 beta1; An extra skirt line on layer 1 and layer 2 (using layer 0 as bottom layer)

### ISSUE THREAD

**Issue by csterlin** [Ultimaker/Cura#15818]
### Application Version

5.4.0 beta1

### Operating System

Windows 11 Home, 22H2, 22621.1778, Intel(R) Iris(R) Xe Graphics

### Printer

Creality Ende 3

### Reproduction steps

Sliced model. Exported to sd-card. Inserted card into printer. Selected pre-heat PLA. Printed model.
![2023-06-19_18-12-47](https://github.com/Ultimaker/Cura/assets/46879843/c1fd31b0-59ae-4956-a29e-40e35c02b5f3)
![2023-06-19_18-15-14](https://github.com/Ultimaker/Cura/assets/46879843/978b8a26-1ee1-4d08-ac29-602c2de3b733)
![2023-06-19_18-17-32](https://github.com/Ultimaker/Cura/assets/46879843/cab0c246-63bd-4e65-9fb0-14b918e3450c)

### Actual results

The print runs normally until the start of layer one (layer 2 in the jpeg) in which it adds a skirt line to the existing skirt. This happens again at the start of layer two (layer 3 in the jpeg), but runs normally after starting layer 3 (layer 4 in the jpeg).

### Expected results

There should be no additional skirt lines after layer 0 completes.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[HoseHolder_4.zip](https://github.com/Ultimaker/Cura/files/11794087/HoseHolder_4.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11794095/cura.log)

**Comment by csterlin** [comment]
[HoseHolder_4.zip](https://github.com/Ultimaker/Cura/files/11794156/HoseHolder_4.zip)
Added gcode and stl files to zip archive

**Comment by opjose** [comment]
I see the same issue with 5.4.0 non-beta

**Comment by csterlin** [comment]
Turns out that there's a new feature, skirt height, which also affects the
corner tab+ plugin, and which has a workaround by setting skirt height to
one.

**Comment by opjose** [comment]
Thanks!

Found it. Strangely it did not appear in the list until I searched for it even though I have all options enabled.
Even then it shows up slightly greyed out as if the setting is not applicable, yet it still works.

**Comment by ThomasCura** [comment]
Hello! I also have the problem that the skirt is printed over several layers, even though I don't want to. Where is the switch that can be used to reduce skirt to 1? I haven't found anything.

**Comment by ThomasCura** [comment]
Now I've also found him with the search. Greyed out. Setting it to 1 gives the desired result. Set to 3 again (default), the setting no longer works. It stays with one layer. Somehow the function is not implemented correctly. It works for me if only one skirt layer should be printed.
