### ISSUE TITLE
Raise3D N2 Profiles Wrong E-Steps

### ISSUE THREAD

**Issue by Jared-Nees** [Ultimaker/Cura#15825]
### Application Version

5.3.1

### Operating System

Windows 10

### Printer

Raise3D N2 Plus Dual

### Reproduction steps

The base Cura profile for any of the Raised3D N-Series printers has E-Steps set to **140**. That number should be 4479 or 6640 to avoid serious under extrusion. The number differences are based on serial number/production age of the printer. 4479 is the number of E-Steps Raised3D recommends for any of the N-Series Printers as well as the value that was applied to our printers out of the box. When using Cura this value overwrites the printer's default.

### Actual results

Sever under extrusion (Barely any filament extrusion at all.)

### Expected results

Nominal extrusion.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://github.com/Ultimaker/Cura/assets/70307798/2d596ea7-fa4b-467c-a8e3-e926818bd630)
Example image from an old support post from Raised using an early-model N-Series printer.

**Comment by GregValiant** [comment]
Thanks for the report.
This is from the Raise3D N definition file:
        **"author": "Raise3D",**
        "manufacturer": "Raise3D",
It does indeed state in the default StartUp Gcode
**; set extruder steps per mm
M92 E140**
The definition files come from either a member of the community, or from the manufacturer.  It isn't possible to buy one of every printer to check the accuracy of the definition files.
I'll remove the bug label and close this as it is a Raise3D issue.  You need to get with the on this.  I hope you understand.
