### ISSUE TITLE
Slicing failed when rotated 90 degrees

### ISSUE THREAD

**Issue by RarePossum** [Ultimaker/Cura#15823]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 3 v2

### Describe model location

Yes

### Describe your model

5015 Fan ducts as part of the Hydra cooling system

### Add your .zip here ⬇️

[5015_ducts.zip](https://github.com/Ultimaker/Cura/files/11798696/5015_ducts.zip)

Reslicing was successful

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
