### ISSUE TITLE
5.3.1 / 5.4.0-beta1 - Missing brim / skirt

### ISSUE THREAD

**Issue by grbd** [Ultimaker/Cura#15824]
### Application Version

5.3.1 / 5.4.0-beta1

### Operating System

Windows 10

### Printer

Anycubic Kossel Linear Plus

### Reproduction steps

I figured I'd open a new issue since the original one was closed down
and this seems to affect both 5.3.1 and 5.4.0-beta1
https://github.com/Ultimaker/Cura/issues/14876

Basically in certain circumstances part of the brim or skirt will be missing on a print
I've put an example 3mf project file here:
https://github.com/Hecatron-Cad/Tools.3DPrinter.Anycubic.Kossel/blob/master/Schematics/Upgrades/Voron-M4/AKLP_end_plate.3mf

You can work around it by dragging the part to a different area such as to the left or right
Maybe it's related to the fact I'm using a delta? I'm not sure

### Actual results

Missing brim / skirt

### Expected results

brim / skirt

### Checklist of files to include

- [ X] Log file
- [X ] Project file (linked above)

### Additional information & file uploads

Github doesn't support 3mf files in issues, linked above
[cura.log](https://github.com/Ultimaker/Cura/files/11800367/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report and the link.
You can Zip a 3mf file and post the zip folder here.  I think there is a 25mb limit on the zip folder size.

This looks like a bug to me.  I'll guess and say that the brim is being cut off in a response to the way Cura now allows models to be closer to the edge of the build plate by trimming the skirt/brim.  This one just looks weird as the part extends beyond the trim line.

@MariMakes may want to take a look at this one.

**Comment by grbd** [comment]
[AKLP_end_plate.zip](https://github.com/Ultimaker/Cura/files/11801067/AKLP_end_plate.zip)
Ok now zipped and uploaded
I've noticed it does impact the g-code so isn't just a visual artifact, also it affects both brim and skirt.

**Comment by MariMakes** [comment]
Hey @grbd,

We discussed https://github.com/Ultimaker/Cura/issues/14876 with the team already, but I probably haven't updated the ticket correctly. We can see in our data that the combination of these two settings Enable Coasting + Wipe Nozzle Between Layers are quite rare, and that the issue disappears if one of them is disabled. 
Is disabling one of the two settings an option for you? 

We believe we will not work on this anytime soon and will therefore defer this issue.
Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
I'll close this issue, I hope you understand.

**Comment by GregValiant** [comment]
I see the model has some errors as well.
Here you can see that the project model has the funky brim.  The model at the bottom was repaired with MS 3D Builder and the brim is what we would expect.
![image](https://github.com/Ultimaker/Cura/assets/64202104/9def2ed6-4903-4b07-a669-4eef093eea31)

**Comment by grbd** [comment]
As far as Coasting + Wipe Nozzle Between Layers those features are already disabled
I don't have anything Experimental enabled

I tried importing the stl into MS 3D Builder but it's saying everything is ok

![image](https://github.com/Ultimaker/Cura/assets/8965579/cf893845-51dc-438d-988f-8bc626ebde2a)

**Comment by grbd** [comment]
[end_plate.zip](https://github.com/Ultimaker/Cura/files/11805445/end_plate.zip)
This is the stl file for info

**Comment by grbd** [comment]
Also had a quick go with meshlab just in case it was something that 3D Builder wasn't seeing
But the results were the same
https://www.youtube.com/watch?v=IreaoCfQ8mE&t=83s

I should mention though that moving to a different area of the build plate will give you different results as far as what part of the brim / skirt is masked off

This is fine:
![image](https://github.com/Ultimaker/Cura/assets/8965579/50cc8bf4-5dde-4ea1-99e0-c17301de491e)

over here it gets weird
![image](https://github.com/Ultimaker/Cura/assets/8965579/2f8b0b82-3da5-4fb1-b822-04c87d94d63f)

**Comment by GregValiant** [comment]
This is with the AnyCubic Kossel active.
![image](https://github.com/Ultimaker/Cura/assets/64202104/bd36fb59-cdb6-4452-bfff-124a2fdd3821)

And this is with an Ender 5 active.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8f768f71-f356-40d8-97cf-cc2594f5fe10)

This is an FLSUN 400
![image](https://github.com/Ultimaker/Cura/assets/64202104/d9717ce5-b737-40c4-9bbc-85e8f4f96fba)

Every time I switch back to the Kossel the effect reappears.
I noted that in the original project file neither "Enable Coasting" nor "Wipe Nozzle Between Layers" were enabled.
I installed a Vyper and it didn't have the effect either.
This is what I get in MS 3D Builder.
![image](https://github.com/Ultimaker/Cura/assets/64202104/51f08d70-e287-413c-ab74-04c5da9ae246)

@MariMakes this only seems to occur with the AnyCubic Kossel, but those other two settings weren't involved.

**Comment by GregValiant** [comment]
With a 110mm brim it gets weirder.
![image](https://github.com/Ultimaker/Cura/assets/64202104/0f8df23d-e3da-4b23-844c-00c4bf1c61b0)

[Brim problem.zip](https://github.com/Ultimaker/Cura/files/11806000/Brim.problem.zip)

**Comment by GregValiant** [comment]
Alright, here is the deal.
The Kossel Linear Pro inherits the regular Kossel definition.
Both definition files have "Disallowed Areas" defined.  Those disallowed areas are causing Cura to act like it would if the brim was falling off the edge of the build plate.
I think the disallowed areas are simply written incorrectly in the definition files.
I have to guess here, but it seems like the intent was to disallow all of the circular build plate except for a 230 x 230 square in the center of the build plate.

This is back to square one, with the original project file BUT with the "Disallowed Areas" deleted from the definition files.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a657b657-9098-4b1a-9c5b-87ac6640051e)

And that Ladies and Gentleman deserves a beer.
