### ISSUE TITLE
Scaling issue Ultimaker S5 Cura - will not work at 90% scaled

### ISSUE THREAD

**Issue by LDHUGS2406** [Ultimaker/Cura#15822]
### Cura Version

5.3.1

### Operating System

Windows10

### Printer

Ultimaker S5

### Name abnormal settings

Scaling down the model to 90%

### Describe model location

No after moving the model to the back of the build plate the error still occurs

### Describe your model

The model slices fine when at 95% scaled or 80%

### Add your .zip here ⬇️

[Slicing error.zip](https://github.com/Ultimaker/Cura/files/11798228/Slicing.error.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
