### ISSUE TITLE
[5.4.0-beta.1] Slicing failed

### ISSUE THREAD

**Issue by agibson2** [Ultimaker/Cura#15835]
### Cura Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

Wanhao D9

### Name abnormal settings

It was slicing correctly before I added manual supports to help support it during printing

### Describe your model

Canopy for RC helicopter

### Add your .zip here ⬇️

[WD9_Canopy.zip](https://github.com/Ultimaker/Cura/files/11811832/WD9_Canopy.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
