### ISSUE TITLE
issue with auto orientation

### ISSUE THREAD

**Issue by Mkeel1451** [Ultimaker/Cura#15830]
### Application Version

5.4.0 Beta

### Operating System

windows 11

### Printer

creality cr10 s pro v2

### Reproduction steps

loaded two files into cura a lid and a container 
after selecting auto orientation it oriented them correctly but the items are overlapped.

### Actual results

items are oriented correctly but they overlap

### Expected results

items are oriented correctly and they do not overlap.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by MariMakes** [comment]
Hey @Mkeel1451,

Thanks for trying our Beta and reporting your issue 👍
In this release we did try to resolve [this issue](https://github.com/Ultimaker/Cura/issues/14838) with overlapping models when loading. 

It would show up like this:

https://github.com/Ultimaker/Cura/assets/40423138/832eec14-1838-4230-8023-4a0e596551d7

Is this the issue you are encountering? 
Do you mind sharing a video of what you are seeing?
