### ISSUE TITLE
missing volumes

### ISSUE THREAD

**Issue by iguvendikler** [Ultimaker/Cura#15852]
### Application Version

5.4.0-beta

### Operating System

windows11

### Printer

ender3 pro

### Reproduction steps

![20230622_132830](https://github.com/Ultimaker/Cura/assets/137399149/32c31b65-db74-48e2-af61-d72fa8154668)
I sliced my datas on cura for ender 3 pro and 3 v2. While on cure, every thing looking good and normal.

### Actual results

Ass you see the attached image.  Printer make this. some volumes are remove or axis are wrong after a while. 
![20230622_132830](https://github.com/Ultimaker/Cura/assets/137399149/57e44bac-f69c-400f-bbf3-373d6bb7e897)

### Expected results

![20230622_132830](https://github.com/Ultimaker/Cura/assets/137399149/2f8978ee-e687-46e4-8c31-d794c7084795)
I expected left one on picture.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

first time I have experience this issues for over 3 years.

**Comment by GregValiant** [comment]
Thanks for the report.
Please provide a project file by loading the model (just the bad one) and setting Cura up, and then use the "File | Save Project" command.  Zip the 3mf file and post the zip folder here.
Without a project file I have to guess and I'd say that looks like a bad model file to me.  It might have a duplicate surface or two.  I've seen that happen before.

**Comment by MariMakes** [comment]
Hey @iguvendikler,

Thanks for the update.
Your pictures scared me a bit, but I'm glad to hear your issue has been resolved.
I'll close the issue, feel free to let us know if you find anything new 😊
