### ISSUE TITLE
Slicing failed with Extension Cylindric custom support applied

### ISSUE THREAD

**Issue by Gerhard-59** [Ultimaker/Cura#15855]
### Cura Version

5.4.0-beta.1

### Operating System

Windows 10 64 bit

### Printer

Anycubic Kobra

### Name abnormal settings

Modell gets sliced without Custom Cylindric Support applied, but failes if one CCS is applied.

### Describe your model

Model of an old transistor radio

### Add your .zip here ⬇️

[AK_Radio Philips Original N250522.zip](https://github.com/Ultimaker/Cura/files/11833306/AK_Radio.Philips.Original.N250522.zip)

The slicer crashes when a Custom Cylindric Support is applied to the model. See alos enclosed screenshot

![2023-06-22_13h12_18](https://github.com/Ultimaker/Cura/assets/91338720/a67d83c8-e10a-445f-8996-034bc278813a)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
The highlighted "polka dot" areas are added by Cura when there are errors in the model.  That model needs repair.
Here is a view in Mesh Mixer.  All those colored balls indicate errors.
I'll leave the bug label on this for a bit, but that model needs help.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c8a8314f-4da2-47bc-a2df-c330fa123c75)

**Comment by Gerhard-59** [comment]
Issue can be closed from my side, with the fix planed for the stable release.
