### ISSUE TITLE
Save printer.def.json file on Mac OSX (Sierra) using Cura 2.4

### ISSUE THREAD

**Issue by prodigerati** [Ultimaker/Cura#1587]
I can't find the resources/definitions folder to save my printer.def.json file as stated in the documentation?

I tried `$user/user/.cura` and `/Users/user/.cura` but the directory does not exist.

Any assistance would be appreciated.

Thanks,

**Comment by fieldOfView** [comment]
Start Cura. In the "Help" menu there should be an option to "Show configuration folder".
