### ISSUE TITLE
Not slicing 

### ISSUE THREAD

**Issue by Mello527** [Ultimaker/Cura#15890]
### Application Version

5.4.0 Beta

### Operating System

Windows 10

### Printer

Ender 3 pro

### Reproduction steps

1 load in file 
2 make it bigger
3 slice the print
4 slicing fail

### Actual results

turn computer off and on and still not slicing 

### Expected results

it would slice so I could print           

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

please fix, i just wanna print

**Comment by MariMakes** [comment]
Hey @Mello527,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Are you still stuck? 
I want to help Fix, but I would need more information to help you. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
