### ISSUE TITLE
CE3E3V2_02 - Top Back Right

### ISSUE THREAD

**Issue by whtwlf** [Ultimaker/Cura#15908]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Ender 3 v2

### Name abnormal settings

Tree Supports?

### Describe model location

It will slice when moved away from the center of the build plate.

### Describe your model

I have sliced it successfully at other angles. It is not water tight.

### Add your .zip here ⬇️

[CE3E3V2_02 - Top Back Right.zip](https://github.com/Ultimaker/Cura/files/11859756/CE3E3V2_02.-.Top.Back.Right.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This is your file as received:
![image](https://github.com/Ultimaker/Cura/assets/64202104/88427781-3bdf-43f0-a6e0-81468fd86083)

I repaired the model with MS 3D Builder.  This is sliced in 5.4beta
![image](https://github.com/Ultimaker/Cura/assets/64202104/16be81c2-f81b-4d36-aefc-bb35c6d33376)

I'm unable to duplicate the problem.   In the meantime have you tried moving the model on the Cura build plate?  Sometimes rotating the model or changing the Initial Layer Height be just a little can help fool the bug.

I'll mark this as a duplicate and the Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
