### ISSUE TITLE
Attempt made on slicing 

### ISSUE THREAD

**Issue by Mello527** [Ultimaker/Cura#15901]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Ender 3 pro

### Name abnormal settings

nope

### Describe model location

nope

### Describe your model

I have sliced it before. 

### Add your .zip here ⬇️

I downloaded the 5.4.1 beta and after that i cant seem to get 5.3.1 or 5.4.1 to slice. I did the save project thing and uninstalled and reinstalled and there just seem to be no helping the slicing. Sometime is starts and fails about 90% of the way, other times it wont start the slicing at all. Please let me know! Thank you!

**Comment by MariMakes** [comment]
Hey @Mello527,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

To help you, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
