### ISSUE TITLE
Unable to add/modify post-processing script in 2.4 under Linux

### ISSUE THREAD

**Issue by buteomont** [Ultimaker/Cura#1590]
I have downloaded the 2.4 Cura appimage file and it runs fine. However, I need to add my post-processing script to it, but Ubuntu won't let me modify the appimage file. 

How can I add my post-processing script to 2.4 running in Ubuntu Linux?

(P.S., I tried to look in the documentation for the answer but when I click Help -> Show Online Documentation nothing happens.  But that's a separate issue.)

**Comment by nallath** [comment]
Currently that's the only place that the plugin can check for new scripts. 

I've created an issue on our tracker (CURA-3593)

**Comment by randyxxl** [comment]
Issue is listed as CURA-3597

**Comment by Ghostkeeper** [comment]
About the "Show online documentation", a few users reported that too but then it turned out that it added a tab to some Firefox window in the background or something, without them noticing.

**Comment by ChrisTerBeke** [comment]
You can now place a custom post processing script in the user_data/scripts folder.
