### ISSUE TITLE
Cura beta 5.4 app freezing and crashing when trying to open

### ISSUE THREAD

**Issue by masterfenix87x** [Ultimaker/Cura#15914]
### Application Version

5.4

### Operating System

windows 10

### Printer

elegoo neptune 3 pro

### Reproduction steps

App will not open if i have more than 1 monitor. how is this a thing? the original beta 5.3 never had this issue then some update you guys did caused this issue.

### Actual results

literally nothing

### Expected results

actually fix this issue. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by MariMakes** [comment]
Hey @masterfenix87x,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I have a couple of questions to narrow it down.
	1. From which version did you try to upgrade? From 5.3 beta? Or did you also have a 5.4 nightly installed? 
	2. Do you have two monitors placed above each other? Can you try this workaround from the community? https://community.ultimaker.com/topic/42633-cura-522-stopped-working/#comment-318105
	3. Do you have GPU Tweak OSD overlay enabled? Does Cura start if you disable that software?
	4. Do you have a Ryzen Graphics card? Can you try this workaround? https://support.makerbot.com/s/article/1667412437627
	5. Do you have the Nahimic audio enhancement service enabled? Can you try this workaround? https://github.com/Ultimaker/Cura/issues/12102#issuecomment-1157907665
