### ISSUE TITLE
unable to slice project

### ISSUE THREAD

**Issue by Russianbreadguy** [Ultimaker/Cura#15923]
### Cura Version

5.4.0 beta 1

### Operating System

macOS ventura 13.4.1

### Printer

anycubic kobra

### Name abnormal settings

standard settings

### Describe model location

all placed as per normal

### Describe your model

the models are from gambody and have been through QC 

### Add your .zip here ⬇️

[AK_1038-53-55_turbine_connector_L_FDM (repaired).3mf.zip](https://github.com/Ultimaker/Cura/files/11870908/AK_1038-53-55_turbine_connector_L_FDM.repaired.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It wouldn't slice form me either.  I moved the models and rotated them and they sliced.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7ffd3e54-a2e0-49e3-8a3b-0fef91f72aed)
I'll leave this one open for the Cura team and mark this as a duplicate.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0

**Comment by Russianbreadguy** [comment]
Hi,Will do as soon as possible RegardsCalebSent from my iPadOn 3 Apr 2024, at 12:32, HellAholic ***@***.***> wrote:﻿
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
