### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by DadIsPlayingNow** [Ultimaker/Cura#15929]
### Cura Version

5.3.1

### Operating System

Windows 11 Pro 22H2 Build 22621.1848

### Printer

Ender 3 Pro

### Name abnormal settings

Nothing abnormal, project only fails with Tree supports touching everywhere

### Describe model location

Model fails when facing right.  Successful in all other directions

### Describe your model

First time with this model.

### Add your .zip here ⬇️

[MC-_Parrot.zip](https://github.com/Ultimaker/Cura/files/11877236/MC-_Parrot.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
It sliced fine for me so I can't duplicate the problem.
Load the model, set Cura up to slice, and then use the "File | Save Project" command to create a 3mf project file.  In File Explorer - right click on the 3mf file and select "Send To | Compressed (Zip) Folder".  Post the Zip folder here.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5e273cfa-fb48-45e3-b8c6-f34afdffef6d)
