### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by wwchrism** [Ultimaker/Cura#15933]
### Cura Version

5.3

### Operating System

MacOS Ventura 13.4.1

### Printer

Ender Pro 3

### Name abnormal settings

Does not print with default

### Describe model location

Center build plate not rotated

### Describe your model

Roof building

### Add your .zip here ⬇️

https://we.tl/t-9vpEC6tqPb

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It sliced for me (using 5.3.0 and 5.3.1 on Windows) so I'm unable to duplicate this problem.
You can try moving the model away from the midpoint on the Cura build plate or maybe rotating the model.  Sometimes adjusting the Initial Layer Height by a little bit (like from 0.20 to 0.23).  All of those have been able to fool the bug for certain models.
I'll mark this as a duplicate and go ahead and close it.  The Cura team has lots of examples of the behavior.  I hope you understand.
