### ISSUE TITLE
Cura 5.4.0-beta.1 appimage not launching

### ISSUE THREAD

**Issue by Crylia** [Ultimaker/Cura#15948]
### Application Version

5.4.0-beta.1

### Operating System

Linux

### Printer

-

### Reproduction steps

Try to start application

### Actual results

Not starting

### Expected results

Starting

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

When trying to launch the appimage I get this error.

PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

**Comment by N6REJ** [comment]
i just get a hard crash.

**Comment by jellespijker** [comment]
- Is this with the modern AppImage or legacy?
- Are you using Ubuntu 23.04?
  - What is the outcome of: `uname -a`
- What do the logs say? They can be found at: `~/.local/share/cura/5.4/cura.log`

**Comment by N6REJ** [comment]
in my case its windows 10 x64 pro

**Comment by jellespijker** [comment]
`linux.AppImage` are for Linux operating systems. Use either the `win64.exe` or `win64.msi` installers.

**Comment by N6REJ** [comment]
no, I used the win64.mis and the win64.exe with same results

**Comment by N6REJ** [comment]
![image](https://github.com/Ultimaker/Cura/assets/1850089/ec63ba4e-034d-4077-87ea-93ac0d971a5f)
I assume its sent numerous crash reports during my attempts

**Comment by jellespijker** [comment]
please open up a new issue for this and make sure you add the logs.

**Comment by jellespijker** [comment]
@Crylia 

Is this with the modern AppImage or legacy?

Are you using Ubuntu 23.04?

What is the outcome of: uname -a

What do the logs say? They can be found at: ~/.local/share/cura/5.4/cura.log

**Comment by Crylia** [comment]
`Pop!_OS 22.04 LTS`
`Linux chunchumaru 6.2.6-76060206-generic #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux`
There are no logs

**Comment by jellespijker** [comment]
@Crylia 

Also not the error output, which can be found at: ~/.local/share/cura/

**Comment by Crylia** [comment]
Uh I redownloaded the appimage as I deleted it, and now it works just fine?

**Comment by jellespijker** [comment]
good to know will close this issue
