### ISSUE TITLE
Custom supports won't slice

### ISSUE THREAD

**Issue by kabaltah** [Ultimaker/Cura#15952]
### Cura Version

5.4 beta

### Operating System

Windows 11

### Printer

Creality ender 3 s1 pro

### Name abnormal settings

No

### Describe model location

No

### Describe your model

Model is watertigh checked and repaired by windows 3d builder

### Add your .zip here ⬇️

When I add custom supports via custom support add-on while using new tree supports the model simply don't slice. Same model with same settings and same custom supports slices without any problems on version 5.3 xmas special edition.

**Comment by GregValiant** [comment]
Thanks for the report.
This is a popular problem with the beta release and hopefully it is fixed for the stable release.  #15956 appears to be another example of this behavior.
I'll mark this as a duplicate and the Cura team will take a look.
