### ISSUE TITLE
"Benchtop apparatus."

### ISSUE THREAD

**Issue by AlexJusten** [Ultimaker/Cura#15960]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Sethi3D

### Name abnormal settings

Custom Supports Cylinder

### Describe model location

"I rotated the piece 90 degrees and placed the support in the center of the piece."

### Describe your model

"My model is a kind of platform to support a dynamometer for use in series."

### Add your .zip here ⬇️

[PeçaAparatoDeBancadaSuporteDinamometro.zip](https://github.com/Ultimaker/Cura/files/11918241/PecaAparatoDeBancadaSuporteDinamometro.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I don't see any "custom supports" in the project file.  The model sliced for me as received, and inverted.
I'm not sure if this is what you had expected...
![image](https://github.com/Ultimaker/Cura/assets/64202104/ccbf91dd-8ef6-44b1-9e04-ce5216f66e5e)

I can't duplicate the problem with that project file but as I say - there aren't any custom supports in it.  I used both normal supports and tree supports.
