### ISSUE TITLE
randomize infill start causing slicing to fail with cubic based infill types 

### ISSUE THREAD

**Issue by rockape01** [Ultimaker/Cura#15964]
### Cura Version

5.0.0 

### Operating System

windows 10

### Printer

oddjob

### Name abnormal settings

print slices if randomize infill start is not checked, only effects cubic and derivative infil patterns

### Describe model location

approximate bed centre  

### Describe your model

model, watertight change of slicer settings allows slicing

### Add your .zip here ⬇️

[bug report, issue with randomize infill start.zip](https://github.com/Ultimaker/Cura/files/11923169/bug.report.issue.with.randomize.infill.start.zip)

used cura update checker and only got 5.4 beta did not know about 5.3.1 release may 

Only seems to affect cubic, cubic subdivision and quarter cubic wen trying to use randomize infill start. and not all models fail.

print settings for fast printing structural ABS parts, useable quality but not overly pretty. profile meh 0.2mm in use 

printer type, Voron 2.4 ( early build,quite old ) with Duet control board running Klipper  on Rasberry Pie 4.

**Comment by GregValiant** [comment]
Thanks for the report.
I believe this problem did exist in 5.0 but it has since been fixed.  I don't see that behavior in 5.3.1 or 5.4beta.  Upgrading to a more recent version should fix the problem.
I'll go ahead and close this as the problem appears to have been fixed.  I hope you understand.
