### ISSUE TITLE
Build height reduced behaviour  2.5 BETA

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#1598]
Hello,

Cura 2.5 BETA
OS: MacOS 10.12.4

When you select "Print Sequence: One at a Time" the build volume height has been reduced message does not come up until you go into Layer View mode. I would expect the message to show and the blue frame to be reduced when it sliced on that change on any view mode.

**Comment by nallath** [comment]
The issue is that the message is actually incorrectly displayed. It should only be displayed if there is more than 1 model on the buildplate.
I've logged the issue in our own tracker; CURA-3608
