### ISSUE TITLE
Cura does not report its installed size within the Apps control panel on Windows 10 or 11

### ISSUE THREAD

**Issue by meyersjd** [Ultimaker/Cura#15996]
### Application Version

5.21 and 5.31

### Operating System

Windows 11 and Windows 10

### Printer

CR6SE

### Reproduction steps

1. Install the program
2. Look in the Apps control panel, formerly called Add/Remove Programs
3. The installed size is not listed next to either version.
![Screenshot 2023-07-04 062754](https://github.com/Ultimaker/Cura/assets/80523069/7f4c5e01-6235-40ff-842c-51aa81d1297b)

### Actual results

No installed size is shown.
![Screenshot 2023-07-04 062754](https://github.com/Ultimaker/Cura/assets/80523069/6bb7f4f1-f28d-4688-9e4c-482fdc504e96)

### Expected results

Apps panel should show installed size.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
I don't see it in Win10.  The Cura installation folder and the configuration folder add up to about 1.9gb.
I have MS Visual Studio installed and it doesn't report the installation size either.

**Comment by jellespijker** [comment]
dis you use the exe installer or the msi? I believe it is a known issue for the exe installer but the msi should report it correctly

**Comment by meyersjd** [comment]
It was an exe installer. That is the one on the ultimaker website

**Comment by MariMakes** [comment]
Hey @meyersjd,

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place with the MSI. 
Apologies for any inconvenience caused by our delayed response. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by MariMakes** [comment]
Oh, in case you missed it, you can download the MSI here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

**Comment by meyersjd** [comment]
Yes, the MSI works. Thanks! You can close it.
