### ISSUE TITLE
Cura crashed when opening up a file

### ISSUE THREAD

**Issue by benclewett** [Ultimaker/Cura#15998]
### Application Version

5.2.1

### Operating System

MacOS  13.4

### Printer

Ender-3 V2

### Reproduction steps

1. Download from https://www.thingiverse.com/thing:3227965/files 
2. Open Body_Front.stl

### Actual results

App will freeze until killed.

This was not the case on earlier version.  Sorry I can't remember what that was.

### Expected results

App working.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

No extra details required

**Comment by MariMakes** [comment]
Hey @benclewett,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We might have a fix for this issue by updating the PyQT Library. 🎉
It's shipped with our most recent Stable Cura version 5.4.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

If you still run into the issue, please share your log files
You can find your log file here:
MacOS: $USER/Library/Application Support/cura/<Cura version>/cura.log

I'll take another look at what is going wrong. 👍
