### ISSUE TITLE
Not able to slice at Super Quality 

### ISSUE THREAD

**Issue by arpitm91** [Ultimaker/Cura#16004]
### Cura Version

5.3.1

### Operating System

MacOs Montrey 12.6.7

### Printer

Ender 3 V2 Neo

### Name abnormal settings

It slices at the default 0.28 layer height profile

### Describe model location

Nope

### Describe your model

Harry potter sign

### Add your .zip here ⬇️

[HP_Top_Enlarged.3mf.zip](https://github.com/Ultimaker/Cura/files/11952037/HP_Top_Enlarged.3mf.zip) 
I got this file from thingiverse (https://www.thingiverse.com/thing:4652144) all credits to them.

The slicer slices successfully in the default 0.28 profile but in 0.12 and 0.16 settings it fails. Even in 0.28 if I change the `Experimental Mode` > `Slicing Tolerance` to `Inclusive` it fails in the 0.28 setting.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
