### ISSUE TITLE
Failed Slicing

### ISSUE THREAD

**Issue by lucassmerica** [Ultimaker/Cura#16015]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Creality Edner 3 S1 Pro

### Name abnormal settings

Z hop when retracted, Z hop distance = 0.4mm

### Describe model location

eh

### Describe your model

It is half of a boat hull. I easily sliced the other half, which was more complex geometry

### Add your .zip here ⬇️

[Hull Front.zip](https://github.com/Ultimaker/Cura/files/11959812/Hull.Front.zip)
[CE3S1PRO_Hull Front.zip](https://github.com/Ultimaker/Cura/files/11959844/CE3S1PRO_Hull.Front.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
