### ISSUE TITLE
Not all layers shown when raft is used 2.5 BETA

### ISSUE THREAD

**Issue by PascalMa** [Ultimaker/Cura#1601]
When using a raft, the model is not shown to the top in layer view.

In my case the layer height is 0.04mm.
Seems like the "Raft Air Gap" contributes to this, as it shifts the model up, but doesn't increase the index of the topmost selectable layer.
But even with Raft Air Gap = 0, there are still some layers missing and I haven't figured out yet wich parameter is not considered in the max. layer index calculation.

**Comment by Ghostkeeper** [comment]
Indeed, this reproduces. Quite a serious bug! Thanks.

It seems to create a model of the same height regardless of raft height, including air gap and such.

**Comment by Ghostkeeper** [comment]
For our reference: CURA-3615.

**Comment by jackha** [comment]
Fixed
