### ISSUE TITLE
Slicing issue

### ISSUE THREAD

**Issue by Gaetan36** [Ultimaker/Cura#16028]
### Cura Version

5.4.0-beta.1

### Operating System

Windows 11

### Printer

custom printer

### Name abnormal settings

None

### Describe model location

No

### Describe your model

It's the first time i try, so never

### Add your .zip here ⬇️

[Cheval Low Poly.zip](https://github.com/Ultimaker/Cura/files/11966420/Cheval.Low.Poly.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
