### ISSUE TITLE
Slice Fail with file (worked fine with different material profile)

### ISSUE THREAD

**Issue by Tuknir** [Ultimaker/Cura#16020]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Neo

### Name abnormal settings

Only change I made was swapping from one custom PLA material profile (Sunlu glow-in-the-dark) to another (Anycubic Silk PLA)

### Describe your model

Top cover for a turtle shaped container. Threaded around outside to screw into base (separate model)

### Add your .zip here ⬇️

[CFFFP_turtle-top_SliceFail.zip](https://github.com/Ultimaker/Cura/files/11961511/CFFFP_turtle-top_SliceFail.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
