### ISSUE TITLE
Slicing failed , under Cura 5.3 it worked fine

### ISSUE THREAD

**Issue by JesConsuegra** [Ultimaker/Cura#16044]
### Cura Version

5.4.0

### Operating System

MX Linux

### Printer

Hypercube Evolution

### Name abnormal settings

none, it worked fine so far

### Describe model location

centered in the platform

### Describe your model

a picture frame

### Add your .zip here ⬇️

[frame.zip](https://github.com/Ultimaker/Cura/files/11980465/frame.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Here is a report on your model from formware.co/onlineSTLrepair
-> Reading file and indexing vertices
-> Analysed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
**--> 26324 Non-manifold edges (?)
--> 90295 Inverted faces (?)
--> 1260 Degenerate faces (?)
--> 1731 Duplicate faces (?)**
--> 0 Disjoint shells (?)

Here is the view in Mesh Mixer.  The errors seem to relate to those fancy fleur-de-lis in the corners and their adjacent radii.
![image](https://github.com/Ultimaker/Cura/assets/64202104/73d06eaf-4ac7-4481-95ff-c6d808bcb8d4)

Here is the model after being repaired in MS 3D Builder (the formware site timed-out) as sliced in 5.4.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/6b028a4f-2d5f-4c70-9d25-9e44525510a9)

I'm going to remove the bug label and close this.  The model needs help and after repairing the model the behavior went away.  I hope you understand.

**Comment by JesConsuegra** [comment]
Thanks, anyway Cura 5.3 was able to process it....
