### ISSUE TITLE
Expansiones Horizontales y de Orificios 

### ISSUE THREAD

**Issue by juanbalca** [Ultimaker/Cura#16046]
### Cura Version

5.4.0

### Operating System

Windows 10 

### Printer

magna 2 230 dual

### Reproduction steps

Hice un cuadrado de 5cm x 5cm con un redondo en el medio hueco que mide 4cm de circunferencia y aunque cambie los valores no corrige la medida.
Otra cosa que cuando guarda el archivo gcode en la microsd. el nombre son los parametros del gcode a imprimir pone temp 210º cam 60º relleno 30% , y pone todo bien menos el relleno que yo pongo ejemplo a 25% y en el nombre pone 30% 

### Actual results

imprime siempre con las mismas medidas

### Expected results

imprime

### Add your .zip and screenshots here ⬇️

+543773447610

**Comment by GregValiant** [comment]
Thanks for the report.
I think I am having translation errors.  Please load the model, set Cura to slice, use the "File | Save Project" command, zip the 3mf file and post the zip folder here.  Thanks.
