### ISSUE TITLE
tyrell building slice error

### ISSUE THREAD

**Issue by jedgarpark** [Ultimaker/Cura#16040]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.4.1

### Printer

Ultimaker 2+

### Name abnormal settings

does not slice w normal - 0.15mm settings

### Describe model location

weirdly, it slices if I move it a bit away from center of buildplate

### Describe your model

yes

### Add your .zip here ⬇️

[Tyrell_Desk_Synth_v0.7.3mf.zip](https://github.com/Ultimaker/Cura/files/11973765/Tyrell_Desk_Synth_v0.7.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
