### ISSUE TITLE
Unable to load multiple files

### ISSUE THREAD

**Issue by justinroyboulanger** [Ultimaker/Cura#16052]
### Cura Version

5.4.0

### Operating System

Windows 10 

### Printer

CR-10 pro

### Reproduction steps

Open file previously could open multiple different files at once and arrange them on the build plate. 

With the new 5.4 I need to open file for each different model i'll be placing on the build plate.

Steps :
 File > Open file(s) (ctrl+O)
 Try to select more than 1 .stl file 

### Actual results

Only one file can be selected. Manually entering the Path of multiple files like "file.stl" + "file.stl" still works.

### Expected results

Multiple files should be selected

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/138899208/13221627-d1bb-4c02-9a44-8a1f0c38020e)
![image](https://github.com/Ultimaker/Cura/assets/138899208/951a05e6-a02c-4b2d-beae-f2bd9ddc81ea)

**Comment by GregValiant** [comment]
Thanks for the report.
This bug has been reported previously ( #15879 and #16003 ) so I'll mark this as a duplicate and go ahead and close this.  I hope you understand.
You can still drag and drop multiple files but the "Open File" dialog doesn't allow for multiple files.

**Comment by MikeOxawopper** [comment]
having the exact same issue, reported in beta, still present in release version
cant control click more than one part
Cant box select more than 1 part
cant control a to select all

plus slicing is slower
and the same test print the pen holder in 5.4 comes in at 7 hour longer
![5 3 1](https://github.com/Ultimaker/Cura/assets/65547160/f63b1cc1-0934-44cf-848a-d271354a8b49)
![5 4](https://github.com/Ultimaker/Cura/assets/65547160/5b56d3b7-c0ba-43e0-89ee-6b98071b3129)
![531 support density](https://github.com/Ultimaker/Cura/assets/65547160/abc7f8ba-bddd-4be9-96fb-c1ff0fa6e01e)
![random zero values](https://github.com/Ultimaker/Cura/assets/65547160/cbdbd4bc-5098-4db2-959c-e9da7850bde9)
