### ISSUE TITLE
Open file dialog not working in kubuntu 23.04

### ISSUE THREAD

**Issue by jouky2** [Ultimaker/Cura#16065]
### Cura Version

5.4.3

### Operating System

Kubuntu 23.04

### Printer

Not relevant

### Reproduction steps

1. press open file button

### Actual results

cura just abandons me and only dragging files on there works; however, i can not save it to disk, will also crash cura

### Expected results

allow me to open files

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/11990459/cura.log)

**Comment by MariMakes** [comment]
Hey @jouky2,

I recognize your Ubuntu version 🤔
Ubuntu does not ship FUSE 2 anymore on 23.04. This is required to run our appimages.
We have reports that Cura 5.4 runs if you install FUSE 2 with sudo apt install libfuse2

Can you let us know if installing this library works for you?
