### ISSUE TITLE
something

### ISSUE THREAD

**Issue by boki221231** [Ultimaker/Cura#16068]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 Pro

### Describe your model

first time slicing its not waterlight 

### Add your .zip here ⬇️

https://we.tl/t-z7Id6EmI6G

**Comment by GregValiant** [comment]
Thanks for the report.
There are so many errors in that model that I don't think it's repairable.  You may get it to slice, but I wouldn't trust it.
When models are this bad there isn't any way to tell if it's a bug in Cura or the model just has so many open seams and flipped surfaces that it's impossible to slice.  All upward facing red surfaces are wrong.  Any areas painted polka-dot by Cura are wrong.
![image](https://github.com/Ultimaker/Cura/assets/64202104/08910c15-7e83-4674-84ff-cbd98dec4881)

I'll leave the bug label on, but I'm going to close this.  That's a really bad model and isn't really proper for FDM.  I don't see any way to get the support out.
