### ISSUE TITLE
slincing error in 5.4 but not in 5.3.1

### ISSUE THREAD

**Issue by marcu0111** [Ultimaker/Cura#16066]
### Cura Version

5.4.0

### Operating System

window11

### Printer

wanhao i3

### Describe your model

yes in 5.3.1

### Add your .zip here ⬇️

[WDI3_bug.zip](https://github.com/Ultimaker/Cura/files/11991461/WDI3_bug.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
