### ISSUE TITLE
Top layers not right thickness and expose infill

### ISSUE THREAD

**Issue by gbarbehenn** [Ultimaker/Cura#16080]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Monoprice Maker Select v2

### Reproduction steps

Print the attached project file

### Actual results

See picture.  Top layers not printing correctly, and not 8 layers (0.8mm) thick. 
![20230709_062850](https://github.com/Ultimaker/Cura/assets/109034829/a43cb561-cfe2-402b-ba1d-d5535e6f7c1c)

### Expected results

Smooth top layer, like bottom layer.  "Top" layer is on two different Z coordinates.  There are two different Bottom Layer counts, depending on Z = 0, or not ("Initial" vs regular bottom layers).  There doesn't appear to be such a difference for top layers.
In any event, both top layers have finish problem.

### Add your .zip and screenshots here ⬇️

[Top layer problem.zip](https://github.com/Ultimaker/Cura/files/11995585/Top.layer.problem.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That sure looks like a wet filament problem.  The water in the filament turns to steam and blows out the covering layers.

I looked at a gcode file from your project and I don't see any problems with it.  I get 8 bottom layers, and 8 top layers on both the levels.  A flow analysis shows that you are right at 100% flow and all line widths on the skins are 0.40.

I don't see a bug here.  I'll leave the label on for a while and you can respond, but I'm inclined to remove the label and close this.  I had that problem once and it was with a brand new roll of filament.   I tried drying it out but it never did print right.  I was glad when it was gone.
