### ISSUE TITLE
Iron man helmet

### ISSUE THREAD

**Issue by b3nny90** [Ultimaker/Cura#16083]
### Cura Version

5.4

### Operating System

windows 11 and windows 10

### Printer

Voron v2.4 350mm

### Describe your model

iron man helmet

### Add your .zip here ⬇️

NIL

**Comment by Asterchades** [comment]
When reporting a bug it's vital to actually mention what the bug is. Since you've not provided a project file as requested when filling out the form we can't even begin to guess what problem you're having, and as such no steps can be taken to attempt to correct it.
