### ISSUE TITLE
Remove Mesh Intersection is not working

### ISSUE THREAD

**Issue by JuanOvalle** [Ultimaker/Cura#16086]
### Cura Version

5.4.0

### Operating System

ALL

### Printer

ALL

### Reproduction steps

I overlap 2 identical models and saw that the layers are getting printed twice, so, the final result is overextrusion, but as well as I understand, this "issue" should be fixed by enabling this option callled "Remove Mesh Intersection".

If I understan wrong this option, please let me know.
Thanks a lot for your attention and good work.

Have a nice day.

### Actual results

The overlap of 2 models result in overextrusion, even when the option "Remove Mesh Intersection" is enable.

### Expected results

Only one layer should be printed when multiple models intersect.

### Add your .zip and screenshots here ⬇️

![imagen](https://github.com/Ultimaker/Cura/assets/51271804/981f63c1-0d95-4dbf-ac5a-67da0cc06b47)
![imagen](https://github.com/Ultimaker/Cura/assets/51271804/1cfd3448-fc13-4ad6-a920-6e17fed7a849)

**Comment by MariMakes** [comment]
Hey @JuanOvalle,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

What an interesting issue, it's a bit hard to reproduce for me based on your screenshots.
I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
