### ISSUE TITLE
problème machine non répertorier  creality k1

### ISSUE THREAD

**Issue by cbdlegalfrance** [Ultimaker/Cura#16089]
### Cura Version

5..4.0

### Operating System

windows 10 64bits

### Printer

creality k1

### Name abnormal settings

la vitesse

### Describe your model

creality k1 et manquante dans vos donner 

### Add your .zip here ⬇️

je ne peux pas paramètre la creality k1 car elle ne fais pas partie de votre catalogue machine merci a vous en l attente d une réponse ou mise a jour de votre équipe car je serai obliger de prendre un notre logiciel merci a vous je suis satisfait de votre produit pourtant merci a vous *

**Comment by GregValiant** [comment]
Thanks for the report.
The definition files and their associated files come from the community or the manufacturer of the printer.  UltiMaker has no control over who submits a definition, or when it might be submitted, or what is in it.
Maybe you can find someone on Reddit or at Creality tech support who can help you.
You might be able to add a printer as a Custom FFF and set up the Machine Settings to what you require.

I'll remove the bug label and close this as it is not an UltiMaker Cura problem.  I hope you understand.
