### ISSUE TITLE
a 3D model with a cone underneath caused the slicer to fail

### ISSUE THREAD

**Issue by SP4CEBARsystems** [Ultimaker/Cura#16109]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender-3/Ender-3Pro/Ender-3-3S

### Describe model location

it will successfully slice it if it is rotated by 90 degrees in any direction

### Describe your model

it has a cone on one side which, if it's on the bottom, causes the slicer to fail

### Add your .zip here ⬇️

[CE3E3V2_pot - axle.zip](https://github.com/Ultimaker/Cura/files/12014621/CE3E3V2_pot.-.axle.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I can confirm the behavior.  There continues to be reports about this happening with good models.
I'll mark it as a duplicate and the Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0

**Comment by SP4CEBARsystems** [comment]
It worked perfectly and I had no issues with slicing the file. Thanks for your support in resolving the problem.
