### ISSUE TITLE
bridge test

### ISSUE THREAD

**Issue by RelayRS** [Ultimaker/Cura#16116]
### Cura Version

5.3.1 

### Operating System

Windows 10

### Printer

Hornet

### Describe your model

bridge for test

### Add your .zip here ⬇️

[bridge-test.zip](https://github.com/Ultimaker/Cura/files/12022723/bridge-test.zip)

**Comment by GregValiant** [comment]
I'm not sure what you want here.  Do you feel that something is broken in Cura?
It sliced fine for me.  I'll re-label and close this as I don't see any problems.
That really isn't a valid model for a bridge test because there are no bridges.
