### ISSUE TITLE
can't sign in cura 

### ISSUE THREAD

**Issue by qqwert33** [Ultimaker/Cura#16111]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

creailty cr-6 se

### Reproduction steps

just need log in i did't do any thing 

### Actual results

no thing 

### Expected results

nothing 

### Add your .zip and screenshots here ⬇️

l

**Comment by MariMakes** [comment]
Hey @qqwert33,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Were you trying to log in to [account.ultimaker.com](https://account.ultimaker.com/app/profile)?
Do you have a screen recording of what is happening? 
Do you think it might be related to your default browser?

To help you better troubleshoot it would help to have a log file. 
You can find your log file here:
Windows: %APPDATA%\cura\<Cura version>\cura.log or usually C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
