### ISSUE TITLE
CrealityBelt crashes and fails slice when saving to file or removable devise

### ISSUE THREAD

**Issue by Tphelps1** [Ultimaker/Cura#16122]
### Cura Version

CrealityBelt 3.6.0

### Operating System

Windows 11

### Printer

3DPrintMill

### Name abnormal settings

Tried default settings, promblem persists

### Describe model location

Middle of build plate

### Describe your model

Yes, it's a cylinder with two cutouts in the middle

### Add your .zip here ⬇️

[45_04_PETG_BRAKE GRAB.zip](https://github.com/Ultimaker/Cura/files/12030931/45_04_PETG_BRAKE.GRAB.zip)

Whenever I try to save to a file or removable device, the application crashes and the .gcode created is often incomplete, empty, or very rarely works. The attached .zip likely won't load, but maybe it can still be of help

**Comment by GregValiant** [comment]
Thanks for the report.
This is the Ultimaker Cura site.  Black Belt Cura is a Creality app?  You need to go back to your printer manufacturer (or whoever supplied Black Belt) for support.
Sorry.
I'll go ahead and close this.  I hope you understand.
