### ISSUE TITLE
Enable Support Brim causes problems if "None" is selected for Build Plate Adhesion

### ISSUE THREAD

**Issue by ZedOud** [Ultimaker/Cura#16139]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.4.1

### Printer

AnkerMake M5, Flsun V400

### Reproduction steps

Reproduction steps:
1. With either Tree or Normal support, select Enable Support Brim.
2. Select "None" for Build Plate Adhesion.
3. Now, the first layer of the support will not be generated (the 2nd layer will print in mid-air).

Alternative step 2:
2a. Select "Skirt" for Build Plate Adhesion.
2b. Set Skirt Line Count to 0
2c. Set Skirt/Brim Minimum Length to 0

### Actual results

It remove the entirety of the first layer of support. (Or all but a tiny bit, see below about Example A)

Most importantly, these results are rather inconsistent and occur on most default profiles if Support is enabled and Build Plate Adhesion is set to None, because most profiles have Support Brim enabled.

Sometimes, it does generate a quirky miniature support that has upwards of 25-50% the footprint of the actual support on Normal support. This may depend on the Support Brim Width value. It consistently occurs if no part of the model is touching the build plate. (Example A project file.)
If no part of the model is touching the build plate, then with Tree support you will get a normal first layer without a support brim. 
If at least some part of the model is touching the build plate, then this bug should occur. (Example B project file.)

### Expected results

This pattern should either refuse to generate a Support Brim, or ignore the Build Plate Adhesion settings category and print a Support Brim.

### Add your .zip and screenshots here ⬇️

[Examples.zip](https://github.com/Ultimaker/Cura/files/12046279/Examples.zip)
Example A - Full Preview:
<img width="347" alt="Example A - Full Preview" src="https://github.com/Ultimaker/Cura/assets/7321904/aeecc9ba-653c-4664-a0ab-c3baba00cf8f">
Example A - 1st Layer Preview:
<img width="347" alt="Example A - First Layer" src="https://github.com/Ultimaker/Cura/assets/7321904/0251f290-0ee5-41b8-8289-e3ec194194c0">

Example B - Full Preview:
<img width="496" alt="Example B - Full Preview" src="https://github.com/Ultimaker/Cura/assets/7321904/016c6bd0-3cd6-4db2-9b64-6f53cb5553e2">
Example B - 1st Layer Preview:
<img width="496" alt="Example B - First Layer" src="https://github.com/Ultimaker/Cura/assets/7321904/61e587b8-6356-4edf-98f4-e6fa715350f3">

**Comment by Asterchades** [comment]
This is a known issue, per the release notes for 5.4.0.

> Support Brim is missing if the Buildplate Adhesion is set to None. [We are tracking reports here](https://github.com/Ultimaker/Cura/issues/14983).

Duplicate #14983.

**Comment by ZedOud** [comment]
> This is a known issue, per the release notes for 5.4.0.
> 
> > Support Brim is missing if the Buildplate Adhesion is set to None. [We are tracking reports here](https://github.com/Ultimaker/Cura/issues/14983).
> 
> Duplicate #14983.

It may be a duplicate, but as far as I can see, no one has found out the 2nd method of producing the bug:
Alternative step 2:
2a. Select "Skirt" for Build Plate Adhesion.
2b. Set Skirt Line Count to 0
2c. Set Skirt/Brim Minimum Length to 0
