### ISSUE TITLE
My delta printer can not normally use  cura2.4 or 2.5 or 2.3

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#1613]
My delta printer （255×255×270mm）using kossel pro settings, export gcode file printer can not print normally - the symptoms are not heated to start printing, please help？thank you very much.

**Comment by nallath** [comment]
Contact the person who sold you the printer. We can't and won't provide help with setting up or using your printer.

**Comment by Ghostkeeper** [comment]
Make sure that the exported .gcode file contains an M104 or M109 line around the beginning setting the temperature to somewhere around 200. If this line exists, it's a problem with your printer.
