### ISSUE TITLE
Slicing Crash 

### ISSUE THREAD

**Issue by German3Planes** [Ultimaker/Cura#16138]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Magma 1

### Reproduction steps

i pick a stl from thingiverse, next i open it, next i try to slicing it, but it fail

### Actual results

after, it open this web

### Expected results

i need to print it in 3D

### Add your .zip and screenshots here ⬇️

<img width="960" alt="Captura de pantalla (399)" src="https://github.com/Ultimaker/Cura/assets/139520072/1aade302-a645-4fc0-a88a-aa024158e361">

**Comment by MariMakes** [comment]
Hey @German3Planes,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
