### ISSUE TITLE
Shift/Control Select doesnt work

### ISSUE THREAD

**Issue by jmlflara** [Ultimaker/Cura#16147]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

Ender 3

### Reproduction steps

Open file
While selecting files can't select with shift key or control key

### Actual results

have to select every file manually

### Expected results

select all files i want 

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/20761242/54b1d83a-244e-4be9-af13-787233a1f69b)

**Comment by GregValiant** [comment]
Thanks for the report.
This is a duplicate report of #15879 .  Drag and drop still works so you can select multiple files in Explorer and drag them to the Cura workspace as a workaround.
The Cura team is looking at this.  I'm going to close this report as the team is aware of it.  You can follow any progress in that original report.  I hope you understand.
