### ISSUE TITLE
CFFFP_skull03-sup_fixed

### ISSUE THREAD

**Issue by FredericJULIEN** [Ultimaker/Cura#16142]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Neo

### Describe your model

No

### Add your .zip here ⬇️

[CFFFP_skull03-sup_fixed.zip](https://github.com/Ultimaker/Cura/files/12048294/CFFFP_skull03-sup_fixed.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't find any errors in the model.  It simply won't slice in Cura 5.4.0.  I was able to slice it in 4.13.1 and PrusaSlicer.
Even after simplifying the model in 3D Builder it still would not slice.
The Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
