### ISSUE TITLE
can't select different extruders for support, sovol sv4 dual printer

### ISSUE THREAD

**Issue by Jeroen1328** [Ultimaker/Cura#16145]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Sovol SV04 Dual

### Reproduction steps

1. import 2 structures (1 for left extruder, 1 for right extruder)
2. position 1 structure on te left of build plate, the other to the right.
3. set support structure of left structure to left extruder
4. set support structure of right structure to right extruder (so both structures can be printed at once)
5. check extruder selection for support of left structure

### Actual results

extruder for left structure is set to richt extruder

### Expected results

extruder for left structure should be left to left extruder
this way left structure is printed with left head, while right structure is printed with right head (saving time)

is there anything that prevents left and right heads crashing into each other ?

### Add your .zip and screenshots here ⬇️

[SSDM_kung_r2_bot2.zip](https://github.com/Ultimaker/Cura/files/12050435/SSDM_kung_r2_bot2.zip)
[kung_r2_top2.zip](https://github.com/Ultimaker/Cura/files/12050443/kung_r2_top2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
There are a couple of things going on here.
You can get some IDEX printers to work with Cura, but Cura doesn't directly support IDEX printers.  There is a single gcode being generated.  Some printers (Ex:  Raise3D) can split that single gcode to Mirror or Duplicate but that is done by the firmware.

It sounds like what you are trying to do is print two different gcode files at the same time.  Effectively, you are trying to split one printer into two.  Unless your printer is wildly different than most others (like it has two mainboards and one controls each print head) I'll take a guess and say that isn't possible.

I'll remove the bug label and close this as what you want to do goes beyond Cura's capabilities (and likely the printers).  I hope you understand.
