### ISSUE TITLE
STL Files don't load after opening

### ISSUE THREAD

**Issue by icebear1981** [Ultimaker/Cura#16143]
### Cura Version

5.3.0

### Operating System

Fedora 38 with Cinnamon

### Printer

Anycubic Mega Pro

### Reproduction steps

trying other stl files
trining o ununstall any cuda verson and install again from rpmfusion

### Actual results

1. Installed first out of snap store, but this couldnt do firmware and direct printing
2. installed the rpm version. firmware update is working but if i open an stl file it wont be loaded
3. tried many other STL files but problem is still there
4. uninstalled anything of cuda and installed cuda out of rpmfusion repo but also same problem, dont opens stl file

### Expected results

Should load and display the opended file 

### Add your .zip and screenshots here ⬇️

[vokoscreen-2023-07-14_11-18-25.mkv.zip](https://github.com/Ultimaker/Cura/files/12048372/vokoscreen-2023-07-14_11-18-25.mkv.zip)

**Comment by MariMakes** [comment]
Hey @icebear1981,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Can you check something for me? 
Do you have the STL reader installed? 
If you go to the Marketplace, Click the Gear, and scroll down to the STL Reader plug-in. 
If you see this, you should click enabled.
![image](https://github.com/Ultimaker/Cura/assets/40423138/0301b0db-1356-45d4-a14e-69da8d7855c7)

If that's not it. Please let me know and I'll take another look at what is going wrong. 👍
