### ISSUE TITLE
merged model fails to slice

### ISSUE THREAD

**Issue by Dweinbach** [Ultimaker/Cura#16148]
### Cura Version

5.4.20 Beta 1

### Operating System

Windows 11

### Printer

Sovol SV04 - Dual mode

### Name abnormal settings

merged mode

### Describe your model

each part (STL) slices individually, but after merge slicing fails

### Add your .zip here ⬇️

[PandaDualExtrude.zip](https://github.com/Ultimaker/Cura/files/12052676/PandaDualExtrude.zip)

the 3mf in the file fails to slice, but the 2 stl's it is made of slice successfully. as soon as I merge models, slicing no longer succeeds.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
