### ISSUE TITLE
Incomplete first layer

### ISSUE THREAD

**Issue by kdale2006** [Ultimaker/Cura#16158]
### Cura Version

5.4.0

### Operating System

Windows11

### Printer

Creality CR-10 Smart Pro

### Reproduction steps

Open STL file
Slice
Save file
Save project 
Print
![2023-07-15_11-41-57](https://github.com/Ultimaker/Cura/assets/99414545/8fe531af-2425-444a-b6f5-bb04e0cea4de)

### Actual results

I have a part (Bottle Opener) that has a bunch of small fingers around a radius.
Everything prints on the first layer except the fingers.
The fingers do print on the second layer but won't stick to the bed because of the first layer space

### Expected results

I expect the complete first layer to print
![Layer 1](https://github.com/Ultimaker/Cura/assets/99414545/7dbdc848-870d-4886-a177-64b939b11aa4)
![Layer 2](https://github.com/Ultimaker/Cura/assets/99414545/161501d5-d308-479b-b998-4e699c98d966)

### Add your .zip and screenshots here ⬇️

[CR10-29_0-V6-New Bottle Open.zip](https://github.com/Ultimaker/Cura/files/12062040/CR10-29_0-V6-New.Bottle.Open.zip)
![2023-07-15_11-41-57](https://github.com/Ultimaker/Cura/assets/99414545/02fdb0b2-adca-4801-93a8-a2d6cc7d1fee)
![Layer 1](https://github.com/Ultimaker/Cura/assets/99414545/c7c8ad2b-13c7-4093-948b-458a9cfde60f)
![Layer 2](https://github.com/Ultimaker/Cura/assets/99414545/13a8d841-40fc-4b47-8e3b-19528e663dda)

**Comment by kdale2006** [comment]
I did not have this issue with the previous version of Cura.
I am using the same STL file

**Comment by GregValiant** [comment]
Thanks for the report.
This looks to be a settings problem.
Make sure "Initial Layer Horizontal Expansion" and "Hole Horizontal Expansion" are set to 0.0.
You could also enable "Remove all holes" and see if it gets rid of the lettering.

**Comment by kdale2006** [comment]
Thanks for the reply and things to try.
Making the "Initial Layer Horizontal Expansion" 0.0 solves the problem.  It
looks like even -0.1 causes some issues and -0.2 makes the fingers
disappear.  I was using -0.3 to take care of some "Elephant Foot" issues.
Has something new been added to take care of the "Elephant Foot '' problem
that pops its ugly head up.
Ken
