### ISSUE TITLE
A *slightly* Overengineered Olpe Vase

### ISSUE THREAD

**Issue by Babble69** [Ultimaker/Cura#16166]
### Cura Version

5.3.1

### Operating System

windows 11

### Printer

artilary sidewinder x1

### Name abnormal settings

none

### Describe model location

no

### Describe your model

slices in prusa with same settings

### Add your .zip here ⬇️

[[shelled]An-Over-Engineered-Vase (2).zip](https://github.com/Ultimaker/Cura/files/12063304/shelled.An-Over-Engineered-Vase.2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
That vase is the same model as in report #16082 .  I'll mark this as a duplicate and close it.  You can follow along or comment in the other thread.  I hope you understand.
