### ISSUE TITLE
Ender 3 S1 start g-code issue

### ISSUE THREAD

**Issue by rblackmore712** [Ultimaker/Cura#16170]
### Cura Version

5.4.0

### Operating System

MacOS Ventura

### Printer

Creality Ender 3 S1

### Reproduction steps

1. auto home printer
2. print something
3. move print bed with hand to remove print
4. start new print immediately after

### Actual results

y-axis does not home which causes the print bed to move all the way forward and causes the belt to jump, then the test line is printed off the back of the print bed

### Expected results

all axis's should home before each print. 

It seems that in the default start g-code for the S1 the home command is "G28 0" when it should just be G28

### Add your .zip and screenshots here ⬇️

n/a

**Comment by GregValiant** [comment]
Thanks for the report.
The printer definition files come from either the printer manufacturer, or a member of the community.  In your case, I think the startup gcode was changed in a pull request.
Go to Manage Printers / Machine Settings.  In the lower left text box there is this line in your startup:
**G28 O ; Home all untrusted axes**
I don't like that as it only applies to newer versions of Marlin and Creality runs it's own version.
Change that line to:
**G28 ;Home all axes**
That should work.
I've put in a Pull Request #16173 to revert all three Ender3s1 startup gcodes back to a plain "G28".
I'll remove the bug label and close this as it's a definition problem.  UltiMaker has no way to check the suitability of definition file for other manufacturers printers.  I hope you understand.
