### ISSUE TITLE
Error al procesar  el  objeto en cura 

### ISSUE THREAD

**Issue by Romano3123** [Ultimaker/Cura#16180]
### Cura Version

5.4.0

### Operating System

Windows 11 

### Printer

Wanhao D12 

### Describe your model

Its a 3d Plane 

### Add your .zip here ⬇️

[Eclipson Panthera.zip](https://github.com/Ultimaker/Cura/files/12066182/Eclipson.Panthera.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
