### ISSUE TITLE
hannya mask part 2

### ISSUE THREAD

**Issue by Dagon1138** [Ultimaker/Cura#16187]
### Cura Version

5.4

### Operating System

windows 11

### Printer

Kobra Max

### Describe your model

I have tried everything in cura nothing works

### Add your .zip here ⬇️

[hannya mask part 2.zip](https://github.com/Ultimaker/Cura/files/12070085/hannya.mask.part.2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This is another good model that Cura can't slice.  I'll add it to the list and the Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
