### ISSUE TITLE
Cura 2.5beta How to change language? Question

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#1619]
Languige setting does not affect anything.
How to change?

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/1568
There's a bug in the 2.5 beta, which I think has been fixed for the final version.

**Comment by nallath** [comment]
It has been fixed. Also note that the beta usually has poor translation due to changes in the strings that have not yet passed the translators.
