### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by BigBooh** [Ultimaker/Cura#16195]
### Cura Version

5.4

### Operating System

windows 11

### Printer

Anycubic Kobra Max

### Name abnormal settings

no and no

### Describe model location

no and yes

### Describe your model

Iron man forearm

### Add your .zip here ⬇️

[AKMAX_forearm right fused.zip](https://github.com/Ultimaker/Cura/files/12074702/AKMAX_forearm.right.fused.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
