### ISSUE TITLE
Save model does not honor scale changes 15.06.02

### ISSUE THREAD

**Issue by CountMurphy** [Ultimaker/Cura#162]
I have tested this with both the Windows and Linux clients. I have a model which I accidentally scaled incorrectly when I created it. The model in question is 76.4 mm on the x axis. My typical workflow is to load the model into cura to position, rotate and scale it 76.7 mm, save the stl and then send it to replicatorg to export to my makerbot. With the new release of cura, any model I save as an stl retains the models original dimensions. For example I can import my model, scale to 76.7 mm (on the x axis), save the model to stl and open that newly saved model with cura. The loaded model will still have the dimensions of 76.4.

this was tested with cura 15.06.02

**Comment by nallath** [comment]
Cura also re-centers an object when it loads it in the current implementation. Would it be a problem if that is also saved?

**Comment by CountMurphy** [comment]
I wouldn't think that would be an issue.

**Comment by awhiemstra** [comment]
This is being overhauled for the next feature release. Unfortunately, that work cannot be backported to 15.06. I will try and see if I can implement a quick fix for 15.06, but otherwise I am afraid you will need to wait until the next feature release.

**Comment by nallath** [comment]
Saving the transformed mesh would work as a quick fix right?

**Comment by awhiemstra** [comment]
Yes, that is what needs to be done for 15.06.

**Comment by CountMurphy** [comment]
Awesome. Thanks for looking into this. Much appreciated.
