### ISSUE TITLE
error slice

### ISSUE THREAD

**Issue by valeriosouza** [Ultimaker/Cura#16202]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 v2

### Describe your model

BLANK ELEPHANT

### Add your .zip here ⬇️

[CE3E3V2_BE-tail.zip](https://github.com/Ultimaker/Cura/files/12079715/CE3E3V2_BE-tail.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
