### ISSUE TITLE
sending files to octoprint

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1620]
Since the play/pause button is introduced, I can not seem to send the files to octoprint.
I do have a connection, I can change the bed temp, and have video feed, I just cant sent the file.
I am using 2.4.99 on Ubuntu.

**Comment by nallath** [comment]
@fieldOfView

**Comment by fieldOfView** [comment]
My bad. See https://github.com/fieldOfView/OctoPrintPlugin/issues/31

**Comment by fieldOfView** [comment]
@maukcc could you try the fixed version? 
https://github.com/fieldOfView/OctoPrintPlugin/tree/2.5

**Comment by maukcc** [comment]
Yep, it works. I didn't even have to download it, it was already in the update.
Thanks!

**Comment by fieldOfView** [comment]
Thanks for reporting, this issue can be closed.
