### ISSUE TITLE
Diplicate crashes slicing

### ISSUE THREAD

**Issue by lbennett49** [Ultimaker/Cura#16217]
### Cura Version

5.4.0

### Operating System

window 10

### Printer

Vyper

### Name abnormal settings

none

### Describe model location

flat

### Describe your model

Support

### Add your .zip here ⬇️

[AV_Loop Spacer middle tapped v1.zip](https://github.com/Ultimaker/Cura/files/12100866/AV_Loop.Spacer.middle.tapped.v1.zip)
Work with the model on the plate but when I multiply to one even more slicer crashes.
Yes restarted 
![Loop Spacer Middle Tapped](https://github.com/Ultimaker/Cura/assets/21987758/272818a5-b166-4593-9a81-2675fa3710df)
![Loop Spacer Middle Tapped](https://github.com/Ultimaker/Cura/assets/21987758/40848985-7fc5-4767-9252-22569fb9fde4)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
