### ISSUE TITLE
Slicing error on frog model

### ISSUE THREAD

**Issue by enewbold** [Ultimaker/Cura#16227]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Flsun V400

### Reproduction steps

Loaded the BoredFrog_belly.stl.
Sliced it (with tree supports).

### Actual results

Slicing failed.
![slice_Screenshot 2023-07-20 140221](https://github.com/Ultimaker/Cura/assets/5244831/10b2af14-e0d0-464b-b682-3d1f874f95a3)

### Expected results

It should have sliced.

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12112856/cura.log)
[cura.log.txt](https://github.com/Ultimaker/Cura/files/12112861/cura.log.txt)
[FV_BoredFrog_belly.zip](https://github.com/Ultimaker/Cura/files/12112876/FV_BoredFrog_belly.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
It wouldn't slice for me either.  I changed the Initial Layer Height to .27 and moved the model away from the center of the bed and it sliced.
I'll mark this as a duplicate and the Cura team will take a look.
![image](https://github.com/Ultimaker/Cura/assets/64202104/43a1da82-3b13-444d-be1c-c9e9de6a6bec)

**Comment by enewbold** [comment]
I actually got Orca 1.6.3 to slice it with no problems, but the Orca slicer
output is not as good as Cura.

Thanks much,
Ed Newbold

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
