### ISSUE TITLE
Slice Fails

### ISSUE THREAD

**Issue by DavrosFPV** [Ultimaker/Cura#16224]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Sovol SV06 Plus

### Describe model location

Dropped on plate

### Describe your model

Downloaded from Thingiverse. Slices if I change scale

### Add your .zip here ⬇️

[baby1.zip](https://github.com/Ultimaker/Cura/files/12105438/baby1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
