### ISSUE TITLE
Cura adds weird temp settings before my start-code.

### ISSUE THREAD

**Issue by TheNecronomica** [Ultimaker/Cura#16223]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 S1 Pro

### Reproduction steps

1. Add model to Cura
2. Change "printing temperature initial layer" to 10°c higher than "Printing temperature".
3. Add "M140 S{first_layer_bed_temperature}" and "M104 S{first_layer_print_temperature}" to start G-code in printer settings before G28; Home.
4. Add "M190 S{first_layer_bed_temperature}" and "M109 S{first_layer_print_temperature}" to Start G-code after G28; Home.
5. Slice.

### Actual results

![Screenshot 2023-07-20 093141](https://github.com/Ultimaker/Cura/assets/140058991/75a7bfc7-7a64-4489-a994-3eaf340e74b6)

Cura adds this part before the start G-code. 

### Expected results

I expect the marked G-code not to be there.

### Add your .zip and screenshots here ⬇️

[cura.log.zip](https://github.com/Ultimaker/Cura/files/12104051/cura.log.zip)

**Comment by fieldOfView** [comment]
Instead of `{first_layer_bed_temperature}`, use `{material_bed_temperature_layer_0}`
Instead of `{first_layer_print_temperature}`, user `{material_print_temperature_layer_0}`

For a neat list of all replacement patterns for Cura settings, see this page:
http://files.fieldofview.com/cura/Replacement_Patterns.html

**Comment by TheNecronomica** [comment]
> Instead of `{first_layer_bed_temperature}`, use `{material_bed_temperature_layer_0}` Instead of `{first_layer_print_temperature}`, user `{material_print_temperature_layer_0}`
> 
> For a neat list of all replacement patterns for Cura settings, see this page: http://files.fieldofview.com/cura/Replacement_Patterns.html

This worked!
