### ISSUE TITLE
barbie key chain with supports

### ISSUE THREAD

**Issue by tbaccus04** [Ultimaker/Cura#16232]
### Cura Version

5.4.0

### Operating System

Windows 10 pro

### Printer

AnyCubic I3 MegaS Pro

### Name abnormal settings

I turned on supports

### Describe model location

Center and flat, but has a lip that needs supprots

### Describe your model

with out supports it sliced fine

### Add your .zip here ⬇️

[barbie_keychainFail.zip](https://github.com/Ultimaker/Cura/files/12116174/barbie_keychainFail.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It wouldn't slice so I grouped the two models and rotated them 90° and then it sliced.  This is a known bug so I'll mark this as a duplicate and go ahead and close this as they have a lot of examples of this behavior.
