### ISSUE TITLE
Vent Mount

### ISSUE THREAD

**Issue by TheToxicant** [Ultimaker/Cura#16247]
### Cura Version

5.2.1

### Operating System

Windows 10

### Printer

Artist D

### Describe model location

center of bed 90 degree rotation 

### Describe your model

sliced and printed several times

### Add your .zip here ⬇️

[Artist-D_JGMaker_Firebird_Vent_Mount.zip](https://github.com/Ultimaker/Cura/files/12136463/Artist-D_JGMaker_Firebird_Vent_Mount.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This is an odd one in that I haven't been able to get it to NOT slice.
There is a bug that can sometimes be fooled by moving the model on the Cura build plate, rotating the model, or sometimes changing the Initial Layer Height by a little bit (like from 0.20 to 0.23).
I'll mark this as a duplicate and go ahead and close this as the Cura team has a lot of examples of this behavior.  I hope you understand.
