### ISSUE TITLE
Cura is slow when moving the camera on MacOS Ventura 13.4.1 (c) (2017 Macbook Pro 13in. 4 Thunderbolt 3 ports 16gb RAM)

### ISSUE THREAD

**Issue by plyght** [Ultimaker/Cura#16259]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.4.1 (c)

### Printer

Anycubic Kobra GO

### Reproduction steps

move the camera in any way. (can have a file on the buildplate or not, it doesn't matter)

### Actual results

the camera is super slow/laggy, around 1 sec response time.

### Expected results

the camera should have smoothly moved around, and i know this for a fact, because on the exact same laptop, i ran bootcamp and used cura there and it was perfectly fine. everything was smooth and crisp. now, grant you, I was on an older version of cura. (not sure which one)

### Add your .zip and screenshots here ⬇️

screenshots wouldnt work so here's a screen recording of whats happening: https://youtu.be/G3Yfe7P3h8g (lmk if the link doesn't work)

**Comment by plyght** [comment]
hey, appreciate the response! no worries about the timing, i’m just glad
you could respond. if you could bring it to the ultimaker team that would
be great.

Thanks!

**Comment by MariMakes** [comment]
The team reminded me that we can learn what's slowing your software down, could you install a plug-in that performs more extensive logging? 

You can download it here: https://marketplace.ultimaker.com/app/cura/plugins/UltimakerPackages/ExtensiveSupportLogging

After it's installed can you.... 
	1. Select Extensions
	2. Select Remote Support
	3. Start CPU profiler
	4. Move the camera and your model around. 
	5. Stop CPU profiler
	6. Select Save Remote Support Archive
	7. Go to the Marketplace
	8. Select the gear icon 
	9. Uninstall Startup Optimiser
	10. Share the Remote Support Archive Zip file here on Github

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
