### ISSUE TITLE
Add iNSTONE profiles

### ISSUE THREAD

**Issue by ITProggeruz** [Ultimaker/Cura#16255]
### Main

- [ ] _**halp**_

`Hi` everyone i want iNSTONE profiles

—

<details><summary>Because</summary>
<p>

I got a `NEW` 3D printer
And it’s iNSTONE Inventor pro
The support site is down which it has drivers for connecting
You can give me tips to profile settings until the presets will adds

</p>
</details> 

Thanks, please don’t make me sad by not responding

### Describe the solution you'd like

I can solve it by asking from you guys and set up
But it it is a suggestion and issue

### Describe alternatives you've considered

Any people who can help me

### Affected users and/or printers

Maybe all of instone printers

### Additional information & file uploads

I don’t have any resources to download drivers, control app, e.t.c..

`Or you can give me link to download and it’s OPTIONAL`

**Comment by ITProggeruz** [comment]
The operation system and other stuff is:
/

**Comment by ITProggeruz** [comment]
And it somehow closed this issue

**Comment by ITProggeruz** [comment]
Hoping this issue will complete in a short time

**Comment by GregValiant** [comment]
Are they still in production?  All I found was a small printer that is no longer available (and I've never heard of them prior to this).

**Comment by ITProggeruz** [comment]
no, its out of stock (i brought it not from online)

**Comment by ITProggeruz** [comment]
also the websit is closed (idk owned or hacked)

**Comment by ITProggeruz** [comment]
socials are facebook and twitter
and if you look up from wayback machine the download files don't exist anymore

**Comment by ITProggeruz** [comment]
wait also i changed places of some details

**Comment by ITProggeruz** [comment]
> Are they still in production? All I found was a small printer that is no longer available (and I've never heard of them prior to this).

its not on popular marketing sites

**Comment by ITProggeruz** [comment]
oh wait also someone used this product before me

**Comment by GregValiant** [comment]
The UltiMaker Company will not be putting money into developing Cura support for an obsolete printer built by another manufacturer.  This is something you will have to do for yourself.
You can try installing a similar printer (look at the Weefun Tina2 printer).  Then you can go to the Machine Settings and adjust for your printer.  You could also install it as a Custom FFF printer.
I'll go ahead and close this.  I hope you understand.

**Comment by ITProggeruz** [comment]
how i can create FDM printers then???

**Comment by ITProggeruz** [comment]
let me check in issues about fdm printer

**Comment by ITProggeruz** [comment]
it gave me 56% chance of help
