### ISSUE TITLE
Dragon slicing failed

### ISSUE THREAD

**Issue by enewbold** [Ultimaker/Cura#16250]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Flsun V400

### Name abnormal settings

None

### Describe model location

Yes, but print time almost doubles to 16 hours.

### Describe your model

Slices OK in Prusa and Orca slicers.

### Add your .zip here ⬇️

[FV_dragon_nice_1.zip](https://github.com/Ultimaker/Cura/files/12137585/FV_dragon_nice_1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
