### ISSUE TITLE
When I slice my object it cura doesn't respond

### ISSUE THREAD

**Issue by karatekidnic** [Ultimaker/Cura#16267]
### Cura Version

5.4

### Operating System

windows 10

### Printer

Creality ender 3 pro

### Reproduction steps

1. I loaded my model into the cura
2. then I tried slicing it

### Actual results

When I slice it cura stops responding for me completely I  even left it for like an hour and it was still slicing it and then I have to go to task manager and close it that way it virtually makes cura unusable for me. 

### Expected results

I should get a time for my model after slicing and a save to disk 

### Add your .zip and screenshots here ⬇️

[cura.log.zip](https://github.com/Ultimaker/Cura/files/12155838/cura.log.zip)

**Comment by MariMakes** [comment]
Hey @karatekidnic,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Do I understand correctly that slicing the part took a long time for you and Cura stopped responding when you were interacting with it? 
Did it slice other models correctly or did it just happen with a certain model? 
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
Would you be able to share the model?
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
