### ISSUE TITLE
Infill bug when "infill wipe distance" number is high

### ISSUE THREAD

**Issue by Ciber101** [Ultimaker/Cura#16262]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender 3 Pro

### Reproduction steps

Set "infill wipe distance" to 5mm and choose "grid" for "infill pattern" and slice and then go to "preview" and you will see infill lines extending out past the outer wall. ALL infill pattern options have these extended lines when wipe distance is set to a high number like 5mm.
![image](https://github.com/Ultimaker/Cura/assets/130101183/9d9456fa-3033-4de0-a6e6-d40d6836db0f)

### Actual results

You will see infill lines extending out past the outer wall making the entire print look very spiky. ALL infill pattern options have these extended lines when wipe distance is set to a high number like 5mm. These extended infill lines actually print like that also. "zig-zag" infill pattern has a small amount of these extended lines, but it is still very annoying.
![image](https://github.com/Ultimaker/Cura/assets/130101183/0545fc1d-63b0-438b-8d32-feeea7378a9a)

### Expected results

There should be NO infill lines extending out beyond the outer walls.

### Add your .zip and screenshots here ⬇️

[CE3PRO_Body211.zip](https://github.com/Ultimaker/Cura/files/12148640/CE3PRO_Body211.zip)
![image](https://github.com/Ultimaker/Cura/assets/130101183/0b47fe0e-c742-4f5f-aedd-3bacb308a585)
![image](https://github.com/Ultimaker/Cura/assets/130101183/e71f7430-d4d1-410b-a41b-a8f5ad0aac43)

**Comment by GregValiant** [comment]
Thanks for the report.
What you see is the reason that the setting box turns orange when you enter a number that is greater than your nozzle size.  Some people use 5.0 nozzles so an absolute upper limit would be inadvisable.
I'll remove the bug label from this and close it as the warning is in place.  I hope you understand.
