### ISSUE TITLE
Clockspring Toaster Slicing Failed

### ISSUE THREAD

**Issue by enewbold** [Ultimaker/Cura#16276]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Flsun V400

### Name abnormal settings

none

### Describe model location

Won't slice in any position

### Describe your model

Sliced OK in Orca 1.6.3.  It's a sample file for testing.

### Add your .zip here ⬇️

[FV_Clockspring3D Torture Toaster v24.zip](https://github.com/Ultimaker/Cura/files/12166850/FV_Clockspring3D.Torture.Toaster.v24.zip)
[curalog.zip](https://github.com/Ultimaker/Cura/files/12166855/curalog.zip)

**Comment by enewbold** [comment]
Cura 5.4 pretty much is crashing regularly and not slicing much now.  Not a very good situation.

**Comment by GregValiant** [comment]
Thanks for the report.
Your right.  I can pretty much copy and paste this response.

There is a persistent bug that keeps good models from slicing.  Sometimes moving the model away from the midpoint of the plate, or rotating the model, or changing the Initial Layer Height but a little bit can fool the bug.
In this case I moved it and rotated it and it sliced.
![image](https://github.com/Ultimaker/Cura/assets/64202104/249100db-41b7-4fe3-81bc-396747ae998b)

I'll mark this as a duplicate and leave it open for the Cura team.  They have a lot of examples, but no toaster that I'm aware of.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
