### ISSUE TITLE
Fatal Exception "QVector3D"

### ISSUE THREAD

**Issue by freesurfer75** [Ultimaker/Cura#1627]
Version: 2.5.0-BETA
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1

Exception:
TypeError: unable to convert a C++ 'QVector3D' instance to a Python object

**Comment by fieldOfView** [comment]
Thanks for the report. Before submitting please check if this issue has not been reported before.
See https://github.com/Ultimaker/Cura/issues/1566, #1591, #1594 and #1607
