### ISSUE TITLE
Crash to slicing process

### ISSUE THREAD

**Issue by JohnBoyleAT** [Ultimaker/Cura#16275]
### Cura Version

5.4.0

### Operating System

Win 10 Pro

### Printer

Ender 3 via Raspberry Pi

### Reproduction steps

Seems like anything I slice it will crash as soon as slicing starts. 

### Actual results

[-](https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage&projects=&template=bugreport.yaml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage&projects=&template=bugreport.yaml#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2023-07-25T23:38:22.2001046Z" /> 
  <EventRecordID>147452</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>DADDY07172019.HOME.local</Computer> 
  <Security /> 
  </System>
[-](https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+Bug%2CStatus%3A+Triage&projects=&template=bugreport.yaml#) <EventData>
  <Data>CuraEngine.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>64a40e02</Data> 
  <Data>CuraEngine.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>64a40e02</Data> 
  <Data>c0000005</Data> 
  <Data>00000000001a5330</Data> 
  <Data>b884</Data> 
  <Data>01d9bf50de88a275</Data> 
  <Data>C:\Program Files\UltiMaker Cura 5.4.0\CuraEngine.exe</Data> 
  <Data>C:\Program Files\UltiMaker Cura 5.4.0\CuraEngine.exe</Data> 
  <Data>ce10686b-4051-4ca4-8785-e89b00a95989</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

### Expected results

I just slices like it always has

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12166389/cura.log)

**Comment by MariMakes** [comment]
Hey @JohnBoyleAT,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
