### ISSUE TITLE
Slicing Adapters

### ISSUE THREAD

**Issue by djxs2000** [Ultimaker/Cura#16287]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 3

### Describe your model

Garden Hose Adapters

### Add your .zip here ⬇️

[CE3E3V2_Adapter.zip](https://github.com/Ultimaker/Cura/files/12176440/CE3E3V2_Adapter.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It's the nut.  It simply won't slice at .20 Initial Layer Height.  I did get all three to slice at 0.23 Initial Layer Height.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e612315d-e2f9-4f02-ae5c-1b7186ec2530)

I'll mark this as a duplicate and the Cura team will take a look.

I print a lot of threaded parts.  You will need to block the support from the threads as it is a real pain trying to clean them out.

**Comment by djxs2000** [comment]
Awesome advice, and fast as lightning, thank you so much!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
