### ISSUE TITLE
"uniform scaling" checkbox sometimes doesn't get remembered 

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1628]
Cura 15 remembered the selection for "uniform scaling".
Cura 2.4 does it sometimes but then drops.

**Comment by Ghostkeeper** [comment]
Good one. I think that just nobody ever thought of that when we ported the functionality to Cura 2.

**Comment by Ghostkeeper** [comment]
Our product manager just rejected this ticket because it has been inactive for 3 months.

**Comment by GregValiant** [comment]
@uwe999 Can this be closed?  Did the rework of the controls in Cura 5.0 take care of this?
