### ISSUE TITLE
Ultimaker CURA, Only Front View Available, NO Top, Left, Right or 3D

### ISSUE THREAD

**Issue by MykelCrafter** [Ultimaker/Cura#16289]
### Cura Version

5.4.0

### Operating System

Windows 10 Pro Version	22H2 - AMD Radeon HD 8600/8700M & Intel(R) HD Graphics 4600

### Printer

Ender 3 Neo, NO Mods & Sovol SV06, No Mods

### Reproduction steps

Reboot, same problem has been happening with the last two versions
have attempted to use controls at the bottom left corner of the screen as well as selecting from the "VIEW" selection in the menu. This happens (or doesn't happen) regardless of if the camera view is Perspective or Orthographic .

### Actual results

No Change

### Expected results

expect to be able to view from all perspectives 

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12176782/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
You are the first to report this so the problem may well be local.
If you have a Dashboard for the Radeon card can you make sure that your system is set so Cura uses the more capable video system?  It should still work with the onboard Intel video though.  There may be some conflict between the two video systems and Cura is somehow stuck in the middle.
