### ISSUE TITLE
Specialty funnel

### ISSUE THREAD

**Issue by Timothy-Alexander-ECMS** [Ultimaker/Cura#16298]
### Cura Version

5.3.1

### Operating System

windows 10 enterprise

### Printer

ultimaker s5

### Name abnormal settings

default setting with support turned on, using second nozzle for pva support

### Describe model location

have tried multiple locations, none slice

### Describe your model

This model did successfully slice yesterday, but I forgot to turn on the pva support.

### Add your .zip here ⬇️

[UMS5_Funnel 1 v3.zip](https://github.com/Ultimaker/Cura/files/12183877/UMS5_Funnel.1.v3.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
