### ISSUE TITLE
Multiple Part Positioning

### ISSUE THREAD

**Issue by marcus2tts** [Ultimaker/Cura#163]
Trying to place multiple objects on the build platform in 15.06 is just a nightmare. I'm using Win8.1. First of all, please don't automatically place every new object in the middle of the plate and then forcing what's already there out of the way. Let me put it where I want it.

When duplicating an object, duplicate it in the same orientation as it's currently positioned in. Right now it duplicates and places in the original orientation in the center of the platform; pushing anything that already occupies that space out of the way.

I've purposely had to move things off the platform to still have some control over them. But when i go to move them back onto the platform, as i click on it, it flies out of the window; refocuses the window, and then there is no way to move the object back onto the platform as the pick center of the object is nowhere near the center of the part anymore. 

There has to be a way to remove all the history of the part's transformations while keeping them where they are. Barring that, there should be a numerical transformation display of each object, with the ability to punch in the numbers you want.

**Comment by luisonoff** [comment]
I just wanted to say that I experienced this same thing today of having multiple parts, clicking one to move it and then window moves, changes pick center but you only realize when you move it a bit because it goes crazy further than waht you expected...

**Comment by FuzzySadist** [comment]
Ditto here, I was getting ready to write this up.  
![image](https://cloud.githubusercontent.com/assets/8291885/8921814/d4767cec-348f-11e5-8730-d738b34004c1.png)

**Comment by nallath** [comment]
This is a known issue. We're working on it. It was caused by another fix.

**Comment by mdklapwijk** [comment]
And on the note of the duplicate option, please bring back the "how many duplicates" dialog.

**Comment by nallath** [comment]
Please make a seperate issue for every request. We cant keep track otherwise.

**Comment by nallath** [comment]
Part of this is fixed for the next release; You can disable the automatic push free.

**Comment by BagelOrb** [comment]
Fixed
