### ISSUE TITLE
Error de instalacion impresora creality k1 max

### ISSUE THREAD

**Issue by ozc2023** [Ultimaker/Cura#16306]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

creality k1 max

### Reproduction steps

No puedo instalarla, porque no aparece en el listado y tampoco reconoce la ip 

Espero sus comentarios

Un saludo

### Actual results

Nada porque no aparece la impresora

### Expected results

ver la impresora y poder instalarla

### Add your .zip and screenshots here ⬇️

![primera](https://github.com/Ultimaker/Cura/assets/140840254/1f7f1a64-c636-485b-a483-60cb122e8dfd)

**Comment by GregValiant** [comment]
If no one has submitted a definition file for that printer then there is nothing you can do.  You may find some support from Creality (use their slicer) or on Reddit.  This is not a Cura problem.
I'll remove the bug label and close this as it is not an UltiMaker Cura problem.  Sorry.
