### ISSUE TITLE
Slicer turns hollow model into solid model

### ISSUE THREAD

**Issue by 170050051624** [Ultimaker/Cura#16301]
### Cura Version

5.4.0

### Operating System

win11

### Printer

voron 2.4

### Reproduction steps

just slice

### Actual results

However, the Slicer software assumes that this item is solid.

### Expected results

My expectation is to produce an hollow item.

### Add your .zip and screenshots here ⬇️

[1.zip](https://github.com/Ultimaker/Cura/files/12186237/1.zip)
![before](https://github.com/Ultimaker/Cura/assets/48182406/c4a39d83-cc60-470a-b95d-70404da15a20)
![after](https://github.com/Ultimaker/Cura/assets/48182406/b27c4259-2768-49de-9d3b-f63d433c4718)

**Comment by GregValiant** [comment]
Thanks for the report.
The Mesh Fix setting "Remove all holes" and the Experimental setting "Make overhangs printable" are specialty settings to be used for specific conditions.  In this case you have "Make overhangs printable" enabled.  One of the things it does is to put chamfers on overhangs so they don't need support.
Turn off "Make overhangs printable" and it should print as you expect.

I'll remove the bug label but I'll leave this open so you can respond and let us know if that was it.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a32a472a-aaf8-4d18-8f90-4e425deca709)

**Comment by 170050051624** [comment]
thank you
