### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by SWO12345** [Ultimaker/Cura#16319]
### Cura Version

5.4.0

### Operating System

windows 10 pro

### Printer

elegoo neptune 3pro

### Reproduction steps

I made the 3d print bigger and fit it on the printing bed then tried slicing it 

### Actual results

it said the slicing failed and there was a bug

### Expected results

it should slice and I should be able to print it

### Add your .zip and screenshots here ⬇️

fix it

**Comment by MariMakes** [comment]
Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
