### ISSUE TITLE
Bug in Mac cura 5.3.1

### ISSUE THREAD

**Issue by 1Junglist** [Ultimaker/Cura#16315]
### Cura Version

5.3.1

### Operating System

MacOS

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

1. Slice file
2. Go to preview Sliced item
3. Cura Crashes, unable to select anything have to turn off the macbook pro m1 by power button to restart computer, but works fine on windows system was able to slice and view on windows 10
![361290562_270764848933751_2068132264469035193_n](https://github.com/Ultimaker/Cura/assets/140885327/0d366939-c6d9-41a6-a34a-c2ae9ae114ca)
![361317227_270764882267081_6281983062102838023_n](https://github.com/Ultimaker/Cura/assets/140885327/97a24ab7-1f9e-4201-a45a-ea3ffe6494af)
![361328952_270764925600410_7468080019732544091_n](https://github.com/Ultimaker/Cura/assets/140885327/088901a0-419b-4461-a558-1f1c2a65d988)

### Actual results

cura crashes

### Expected results

Should be able to preview sliced file

### Add your .zip and screenshots here ⬇️

![361290562_270764848933751_2068132264469035193_n](https://github.com/Ultimaker/Cura/assets/140885327/5742511b-48c8-43c4-b667-dfc7733766ad)
![361317227_270764882267081_6281983062102838023_n](https://github.com/Ultimaker/Cura/assets/140885327/3209959e-a5f7-4aea-b7a4-e42aeab5c82d)
![361328952_270764925600410_7468080019732544091_n](https://github.com/Ultimaker/Cura/assets/140885327/1a9691e7-a46c-4e07-9a48-29fef758fe36)

**Comment by MariMakes** [comment]
Hey @1Junglist,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I've never seen a crash like this 😨 
It seems like the preview is not working correctly. 
Are you only seeing this in this model, or also in other models? 

As a Windoows user this issue is outside my field of expertise 😖, so I'll bring it up to the team to see what they can do to improve it. But I expect that if it's not a quick fix that it will not get a high priority to implement. 
Fingers crossed 🤞

**Comment by 1Junglist** [comment]
Hi ya mate,

It only happens on my Macbook pro m1, I have seen it a couple times on the
3D printing Facebook groups.
I think it's software based doesn't show in prints as I can't save the
g.code, the glitch just locks up my whole Macbook and I have to do a hard
reset on the laptop.

Thank you

Ben

**Comment by MariMakes** [comment]
Hey @1Junglist,

I showed your issue to the team and they mentioned that it might be related to your hardware. 
Unfortunately, that is not something that we can fix in Cura 😞 

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
