### ISSUE TITLE
weird printing on a spot

### ISSUE THREAD

**Issue by bdag46** [Ultimaker/Cura#16318]
### Cura Version

5.4.0

### Operating System

Mac OSX 12.6.8

### Printer

Creality Ender3 pro

### Reproduction steps

Made small changes to a model
Created the Gcode using Cura
transfered the gcode file to the printer
started the print

### Actual results

The printer attempted to print the model at the home position only.
i.e there was no x or y movement from the home position

### Expected results

would have expected the model to be be printed centered on the middle of the build plate

### Add your .zip and screenshots here ⬇️

[BEST TRY YET v17.3mf.zip](https://github.com/Ultimaker/Cura/files/12207559/BEST.TRY.YET.v17.3mf.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/12207568/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
You can see in the image below that the "Origin" is at the middle of your build plate.  Other than Delta printers there are very few printers that have the origin at the midpoint (center) of the build plate.
![image](https://github.com/Ultimaker/Cura/assets/64202104/d8ee94df-81e4-47a8-a480-85b53b7945e1)

It's supposed to look like this with the origin at the left front corner.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4d6784a7-f8f5-4c55-9a45-21efcd4e5737)

Go to the Manage Printers and then Machine Settings and **de-select** "Origin at Center".
Let us know if that works for you.
I'll remove the bug label and close this but you can still respond here.
BTW that setting is explicitly set to "False" in the main printer definition file.  Somebody changed yours.
