### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by Godzilla556** [Ultimaker/Cura#16311]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

anycubic vyper

### Reproduction steps

tried to slice 2 models i would like to print

### Actual results

error message appears and states:
  Slicing Failed
     "slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker"
     

### Expected results

a regular slice

### Add your .zip and screenshots here ⬇️

![Screenshot (3)](https://github.com/Ultimaker/Cura/assets/140864866/e8144dc8-41c6-401d-85be-656f5af68aa9)

**Comment by MariMakes** [comment]
Hey @Godzilla556,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
