### ISSUE TITLE
falla del cortador por usar una maquina que tiene 2 extrusores 

### ISSUE THREAD

**Issue by ZDABEO** [Ultimaker/Cura#16314]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

solvo v2 dual extruder 

### Name abnormal settings

cambie de 2 extrusores a 1 y eso provoca la falla

### Describe model location

no solo falla

### Describe your model

si

### Add your .zip here ⬇️

cambie de dual boden  struder a direct extruder de creality sprite extruder pro kit y cuando CAMBIO LA COMFIGURACION DE LA IMPRESORA EN CURA ME FALLA DE INMEDIATO la regreso a 2 extrusores y se quita la falla
[Sizzling Amberis-Wolt.zip](https://github.com/Ultimaker/Cura/files/12206089/Sizzling.Amberis-Wolt.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You have a 3rd party printer that you customized (a 4th party).  In addition, the Sovol SV02 printer definition file was submitted to Ultimaker by Sovol.  UltiMaker has no way to check if the definitions are suitable for the printer they were written for.
So I will remove the bug label and close this.  I hope you understand.

The SV02 definition file was written for a dual extruder printer.  There are a couple of things you can do.  The simplest is to:

- Change the printer back to a dual extruder in Cura
- Set the Bed Adhesion Extruder to either "Left" or "Not overridden" (this is why it won't slice as a "single" extruder)
- Change the printer so a single extruder

Once you have done that it should slice.
