### ISSUE TITLE
Multaka Cura - Bad slicing

### ISSUE THREAD

**Issue by Beki024** [Ultimaker/Cura#16338]
### Cura Version

Multaka Cura

### Operating System

Windows 10

### Printer

Wanhao Infinity 200

### Reproduction steps

Slicing in Multaka Cura is bad for every part I import in it, only time it is good is when I configure nozzle diameter to 0.25mm which is not true in my case it is 0.4mm.

### Actual results

I get bad slice with unfilled gaps in it!

### Expected results

It should be sliced good!

### Add your .zip and screenshots here ⬇️

![Bad slicing - 0 4mm nozzle diameter](https://github.com/Ultimaker/Cura/assets/141043514/db88c37d-a479-45cd-b321-42943835b63a)
![Good slicing - 0 25 nozzle diameter](https://github.com/Ultimaker/Cura/assets/141043514/c26e4489-c5ee-4bec-ac3c-8c5a39f9a3cd)

**Comment by fieldOfView** [comment]
I don't know what Multaka Cura is, so I will assume you meant Ultimaker Cura.

It is hard to see exactly what you mean from just these two images, especially without any description with the images. I can only take a guess that the first image shows the problem, but I don't know what the geometry looks like. If you save and share a project (File -> Save project...), we get both your object and the settings you use, and as a result we can help you much better.

Having said all that, is the "Coasting" setting enabled? If so, disable it.

**Comment by Beki024** [comment]
Yes, I got this software with Wanhao Infinity 200 printer to slice with it. On internet I havent found anything about this software so I thought maybe there is someone who can help me here... I will post picture of software how it looks like.
![Multaka cura exe](https://github.com/Ultimaker/Cura/assets/141043514/4d482066-fba0-4d8e-a8ad-089766852976)
![Multaka Cura](https://github.com/Ultimaker/Cura/assets/141043514/69e35cf5-f224-4c98-906b-7135c8b3b097)

**Comment by Beki024** [comment]
Ok. Thank you very much, I unchecked Coasting and now it works!

**Comment by fieldOfView** [comment]
Glad I could help.
