### ISSUE TITLE
Slicing misses all detail and internal geometry - Bad Slicing

### ISSUE THREAD

**Issue by PhilBaz** [Ultimaker/Cura#16346]
### Cura Version

5.4

### Operating System

win 10

### Printer

Voron 2.4

### Reproduction steps

Slice file.

Slicing misses all detail and internal geometry. Smartavionics branch produces expected/correct result. Ill include images for comparison.

Cura 5.4
![Screenshot 2023-08-01 104425](https://github.com/Ultimaker/Cura/assets/21558241/36896cd7-21ad-4225-9943-8373529c7d73)
&
![nbmnbmnb](https://github.com/Ultimaker/Cura/assets/21558241/68abcfad-c0eb-467f-b0c8-458ab6d98287)

Smartavionics
![bvnbvbnv](https://github.com/Ultimaker/Cura/assets/21558241/ff88b059-49f8-47d9-adf8-3f7e7bb925aa)

### Actual results

![nbmnbmnb](https://github.com/Ultimaker/Cura/assets/21558241/b7f8da9d-c089-4f2e-b7ed-d1412c1b407d)

### Expected results

![bvnbvbnv](https://github.com/Ultimaker/Cura/assets/21558241/4d9f049a-5412-48c2-956a-0021f15b1d78)

### Add your .zip and screenshots here ⬇️

[bad slice detail lost.zip](https://github.com/Ultimaker/Cura/files/12232107/bad.slice.detail.lost.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This is in 5.4.0 with the Line Width at 0.40 and "Print Thin Walls" turned on.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8d246e4b-ea18-481f-b391-852da426cc4b)

5.X UM Cura is different and the Arachne Engine means some settings have to change.  SmartAvionics fork doesn't have the Arachne Engine.
Is that what you are looking for?
I don't see a bug here.  UM Cura 5.X needs to be set up slightly differently.

**Comment by PhilBaz** [comment]
@GregValiant 

Ahh, sorry, I thought I had tried that...

**Comment by PhilBaz** [comment]
@GregValiant 

Still the slice with .5 and thin walls off is bad...lots of nonsense in there.

**Comment by GregValiant** [comment]
With the Arachne Engine there is no "upper limit" on line width, just a lower limit.  You need to drop the "suggested" line width to at .40.  The Engineering line width of .37 (for a .4 nozzle) might be better suited to this model.  Leonardo didn't paint the Mona Lisa with a house brush.

This is what I'm getting for layer 1
![image](https://github.com/Ultimaker/Cura/assets/64202104/f6441d0b-d24b-4579-a6a8-f65cdde7dfce)

Layer 2
![image](https://github.com/Ultimaker/Cura/assets/64202104/b00ba469-24d0-4631-acff-3fca9eece283)

Those are wrong?  It's really hard to make out what you have going on within the part.

**Comment by PhilBaz** [comment]
@GregValiant 

Thanks Greg, i didn't realize how line width worked under Arachne. Engineering line width, ill have to look into that. 

Its not my part, but yes they are trying some clever tricks. The second layer you just posted isn't quite right, I think. But the one you posted above is, with veins going down the length of the center. 

But, thanks this definitely solves the problem in terms of getting this thing printed as intended. Ill keep this aspect of the workflow in mind going forward.

**Comment by GregValiant** [comment]
This is not about your post but it seems like people want all sorts of options to do this that way and that this way.  The program ends up complicated with a lot of settings that can interact in unexpected fashions.
In addition, Cura is highly customizable which adds another layer of complexity.  There is no "Easy" button or built-in "AI" to make the decisions and figure everything out for a user.  It's a complicated app with a long learning curve.  The documentation on how to use some of the settings seems spread out and hard to find. 
I still use 4.13.1 for some stuff and I use SmartAvionics version as it is better on sprialize.  Gotta use the right tool for the job.

Good luck with that piece.  I did slice it with a 0.25 nozzle.  The 0.4 should work fine with the lower line width.

I'll leave this open and the bug label in place.  That model presents a unique printing problem.  Let me know how the print turns out.

**Comment by PhilBaz** [comment]
@GregValiant 

Hey Greg, yeah, totally.  The model represents a complex problem and I get there is no easy way to evaluate what the user is trying to achieve in these types of situations.

In the end the program was capable of producing the desired output. So, then user knowledge was the limiting factor. 

Its true, these are highly complex problems and complex sophisticated software. 

I was able to achieve the desired result, in the end essential was 0.4 line width and a first layer height under 0.28. 

Thanks for your help.

**Comment by GregValiant** [comment]
Ta-Daa.  Another head scratcher figured out.  I'll go ahead and close this out as a "settings issue" then.
