### ISSUE TITLE
Confirmation dialog for overrides cut off on high-dpi displays on Windows

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#1634]
As you can see from this screenshot, the confirmation dialog for profile overrides is cut off on high-dpi displays on Windows. This is a regression from previous builds.

![image](https://cloud.githubusercontent.com/assets/606923/24582501/c3bd2630-16f6-11e7-9546-9b67e0471c79.png)

**Comment by fieldOfView** [comment]
Since this dialog is new for Cura 2.5, it is hardly a regression. But it does need to be fixed, thanks for the report.

**Comment by mqudsi** [comment]
Sorry, I meant regression as in "the previous dialog didn't exhibit this problem."
