### ISSUE TITLE
Profile override confirmation dialog does not reflect correct values

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#1635]
![image](https://cloud.githubusercontent.com/assets/606923/24582503/d8ee02ea-16f6-11e7-870b-fbfa99a6bc16.png)

In the image above, the first column is incorrect as the saved value in the profile is actually 0.97 but in 2.5 beta it says that values differ though it shows them to be the same.

**Comment by fieldOfView** [comment]
I think the default is a "calculated" value, the customized value is an "absolute" value. Ideally this difference would be visible.

**Comment by mqudsi** [comment]
I'm not positive what you mean, but I'm pretty sure that 0.36 is neither the saved profile value nor what would have been calculated by the saved profile?

**Comment by fieldOfView** [comment]
Ah, I thought you had manually entered 0.36, and were wondering why Cura was showing that it was a changed value. But it turns out I am having trouble reading today.

**Comment by Ghostkeeper** [comment]
I filled in 0.97 and it showed both as 0.97 for me, even the default.

**Comment by ianpaschal** [comment]
This is fixed in 3.2.1.
