### ISSUE TITLE
Ultimaker Cura 5.4 is not displaying materials when selected in settings

### ISSUE THREAD

**Issue by GoguyT3D** [Ultimaker/Cura#16350]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Ultimaker S3

### Reproduction steps

Immediately after installing 5.4 from 5.4alpha nightly version I opened cura to see if my personal custom profiles, materials and settings were still in tact. When clicking the dropdown menu from the top of the window and selecting manage materials, the window pops up although the window is not displayed correctly nor is the materials page at all. When clicking on something like profiles the page displays but the title does not show correct text, like two words are on top of each other, also the buttons on the top right of the page dont seem to "mind their own space" and overlap even when maximising the profiles window.
![Screenshot_20230801_051635](https://github.com/Ultimaker/Cura/assets/67012956/e570b7e1-88aa-4d70-9ab6-11b3e37e7bda)
[New folder.zip](https://github.com/Ultimaker/Cura/files/12234090/New.folder.zip)
Config folder in zip

### Actual results

the correct screen (materials) is not displayed and the profiles screen is displayed with a skewed title and buttons that arent separated.

### Expected results

The material page with my standard and custom materials should show, the title should say "Materials" and the buttons on the top right should be separated with a small margin.
![Screenshot_20230801_051050](https://github.com/Ultimaker/Cura/assets/67012956/946a21c4-1754-4d15-b491-37a5ecc4049c)
![Screenshot_20230801_051015](https://github.com/Ultimaker/Cura/assets/67012956/8eea9b41-3f65-47b2-ab9c-c05a6ffb6cd2)

### Add your .zip and screenshots here ⬇️

[New folder.zip](https://github.com/Ultimaker/Cura/files/12234115/New.folder.zip)

**Comment by GoguyT3D** [comment]
UPDATE!
First, I created a backup with the Ultimaker Cura 5.4, then I shut down my computer, Reopened Cura and the problem persisted. Next I went into Marketplace and downloaded the first random material and installed it(to try to wake up my materials and jog curas memory so to speak), shut down cura (Picture 1) and restarted Cura. Now the Materials screen displays fine and I can switch between printers and Profiles, and materials and see them all with no distorted words at the top. It seems like the graphic of flashing between "Profiles" and "Materials" was staying fixed so two words were printed onto each other, and before the materials screen was not even loading. 
![Screenshot_20230801_065521](https://github.com/Ultimaker/Cura/assets/67012956/6501417d-92bc-4f63-99bc-1ebe742cb67a)
Cura seems to be performing normally now. (Picture 2)
![Screenshot_20230801_065714](https://github.com/Ultimaker/Cura/assets/67012956/ff54d580-a31b-48f7-b8ba-90628bf4e62e)

**Comment by MikeOxawopper** [comment]
Having the same issue in windows 10 pro with the materials panel and preference panel.

![Bact to materials](https://github.com/Ultimaker/Cura/assets/65547160/12d2c712-72e0-459b-8bd7-d85923a96837)
![Jumble](https://github.com/Ultimaker/Cura/assets/65547160/e9998660-5978-4827-94ec-7f206ebedd84)
![Manage](https://github.com/Ultimaker/Cura/assets/65547160/45e212d7-279d-4f65-8180-370bf233d8f5)

**Comment by GoguyT3D** [comment]
@MikeOxawopper try my August 1st comment it solved it for me
