### ISSUE TITLE
No Slice facility no blue slice link Cura 5.4

### ISSUE THREAD

**Issue by einsvonzehn** [Ultimaker/Cura#16351]
### Cura Version

5.4.0

### Operating System

Win 10 64bit

### Printer

Anycubic Kobra

### Reproduction steps

I want to slice but no blue slice link

### Actual results

![Capture Cura 5 4](https://github.com/Ultimaker/Cura/assets/68445535/dd3097aa-8745-4f98-9023-cf14ae5ec985)

### Expected results

I would expect a slice if there was a blue link

### Add your .zip and screenshots here ⬇️

![Capture Cura 5 4](https://github.com/Ultimaker/Cura/assets/68445535/154c9fc6-3936-4f26-be4b-5f587c6ab697)

**Comment by GregValiant** [comment]
Thanks for the report.
This is the first report I've seen about that behavior.
@MariMakes of the Cura team might have some information about what is going on.

**Comment by MariMakes** [comment]
Hey @einsvonzehn,

Thanks for your report 👍
That indeed looks off 🤔 

It seems like parts of your screen have been cut off, like the bottom of your screen where the slice button lives.
What happens if you press the windows key and the arrow up a couple of times? 
It should resize your window, hopefully making the slice button appear. 🤞 

Can you let us know if this works for you?
If not just let us know and we'll take another look.

**Comment by einsvonzehn** [comment]
Hallo und Danke für Ihre schnell Nachricht.

Ich habe das Taskleite auto ausblenden und Ja ich siehe das Slice button.

Mfg.

Colin Finch.

 
 

Gesendet: Mittwoch, 02. August 2023 um 10:55 Uhr
Von: "Mariska" ***@***.***>
An: "Ultimaker/Cura" ***@***.***>
Cc: "Colin Finch" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [Ultimaker/Cura] No Slice facility no blue slice link Cura 5.4 (Issue #16351)


 

Hey @einsvonzehn,

Thanks for your report 👍
That indeed looks off 🤔

It seems like parts of your screen have been cut off, like the bottom of your screen where the slice button lives.
What happens if you press the windows key and the arrow up a couple of times?
It should resize your window, hopefully making the slice button appear. 🤞

Can you let us know if this works for you?
If not just let us know and we'll take another look.

**Comment by MariMakes** [comment]
Hey @einsvonzehn,

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
I'll be closing this issue. I hope you understand.
