### ISSUE TITLE
slicing fail for 3d file

### ISSUE THREAD

**Issue by henryhyh-hyphen** [Ultimaker/Cura#16360]
### Cura Version

5.4.0

### Operating System

win10

### Printer

dwmaker

### Describe your model

123

### Add your .zip here ⬇️

![图片](https://github.com/Ultimaker/Cura/assets/140830234/808458a9-9f87-4cde-9d4e-893e2f2fec19)

**Comment by GregValiant** [comment]
Without a project file there can be no investigation as we have nothing to check.
