### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by dusanfpwn97** [Ultimaker/Cura#16368]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 S1 Pro

### Describe your model

Slicing fails when slicing with 100% scale. With 95% it works fine

### Add your .zip here ⬇️

[handring.zip](https://github.com/Ultimaker/Cura/files/12244464/handring.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Note that the model has errors.  That always makes it tough to figure out if Cura has a bug or if the model is the problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/451fffa5-b14b-4fef-b8a2-b62a9ad5b632)

This is a report on the model errors.  The "Non-manifold" edges are a particular problem as they confuse the slicer regarding where the exterior of the model ends and the interior starts.
--> 40 Naked edges (?)
--> 2 Planar holes (?)
--> 0 Non-planar holes (?)
--> **768 Non-manifold edges (?)**
--> 775 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 15118ms ------
-> Vertex count changed from 75000 to 76312 (+1312)
-> Triangle count changed from 151450 to 154478 (+3028)

After repairing the model it sliced.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a0ff59bf-57c5-44a8-848a-9d5503bae545)

Cura 5.4 does have a bug that can keep models from slicing, but in this case it looks like the model is the problem.
I'm going to remove the bug label from this report and close it.  I hope you understand.

**Comment by dusanfpwn97** [comment]
Of course. I was just confused why it worked with <= 95% scale and below, but not with 100%. Cheers!

**Comment by GregValiant** [comment]
Scaling down can "close" open seams while scaling up can cause seams that seemed closed to open up.  I know it was only a 5% difference, but computers are working to 12 or more decimal places.  That 5% may have pushed it within some slicing tolerance.
