### ISSUE TITLE
Slicing issue

### ISSUE THREAD

**Issue by alfonsvh** [Ultimaker/Cura#16373]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ultimaker S5

### Name abnormal settings

See project file

### Describe your model

Sliced before without issue

### Add your .zip here ⬇️

[UMS5_Disso-Cup_LID-withprintedseptum.zip](https://github.com/Ultimaker/Cura/files/12249257/UMS5_Disso-Cup_LID-withprintedseptum.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I moved the parts away from the midpoint and it sliced.  This is a known bug so I'll mark this as a duplicate.

On the small inner part - every other layer has this going on.
![image](https://github.com/Ultimaker/Cura/assets/64202104/97dcedd9-8f55-406e-b7ad-98f175d2a41c)

After using the "Lay Flat" tool every other layer looks like this with a small concentric circle inside.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e73516a6-27a4-419a-95b5-efd84de5b709)

Did you intend for the small part to be skewed?

**Comment by alfonsvh** [comment]
No, that isn't supposed to happen...

Op do 3 aug 2023 om 13:22 schreef GregValiant ***@***.***>:

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
