### ISSUE TITLE
Failed to slice

### ISSUE THREAD

**Issue by Hoelzle24** [Ultimaker/Cura#16378]
### Cura Version

5.4

### Operating System

Windows 11 5950x 3070ti

### Printer

Anycubic Kobra Max

### Name abnormal settings

Does not slice even with default.

### Describe your model

mesh fix shows water tight

### Add your .zip here ⬇️

[AKMAX_dice_tower_small_tower_middle_plain_v10.zip](https://github.com/Ultimaker/Cura/files/12256141/AKMAX_dice_tower_small_tower_middle_plain_v10.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I changed the "Initial Layer Height" to 0.23 and it sliced.
That's a known bug so I'll mark this as a duplicate and close this as the Cura team has a lot of examples of this behavior.
Two other workarounds are to move and/or rotate the model in Cura.
