### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by zaubaerer** [Ultimaker/Cura#16387]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Anycubic i3 Mega X

### Describe your model

THe same model with the same settings sliced sucessful with Cura 4.13.1

### Add your .zip here ⬇️

[crash.zip](https://github.com/Ultimaker/Cura/files/12262301/crash.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Your "Max Speed Z" is 20mm/sec but you have your ZHop speed set to 30mm/sec.  That is one reason it wouldn't slice.
Your "Initial Layer Height" is 0.10 at 130% Line Width, and your Layer Height is 0.26...that isn't a problem, but its an odd combination.

The other reason it wouldn't slice is a bug that has been reported numerous times.  I rotated  the model 90° and it sliced for me.
![image](https://github.com/Ultimaker/Cura/assets/64202104/19bfb866-2799-4f89-9bf5-01a451f836de)

I'll mark this as a duplicate and go ahead and close it as this is a well documented bug.  I hope you understand.
