### ISSUE TITLE
failed slicing

### ISSUE THREAD

**Issue by MPSmith5000** [Ultimaker/Cura#16382]
### Cura Version

5.4.0

### Operating System

windows 10 Pro

### Printer

anycubic kobra max

### Name abnormal settings

none

### Describe model location

model is long so i have to go across the build plate at an angle. But I have tried every available orientation and all failed 

### Describe your model

this is my first attempt to slice this file. It is watertight

### Add your .zip here ⬇️

I can not include the file it is 45MB and your system wont allow it.

**Comment by GregValiant** [comment]
Thanks for the report.
Github imposes a limit on file size.  Sorry.
If you have tried re-orienting the model and made small changes to the Initial Layer Height and it still won't slice then you will have to use a different slicer.  I use 4.13.1 as my alternate Cura slicer.  It is much more forgiving about model errors as well.

I'll mark this as a duplicate.  There have been many reports of error-free models that 5.4.0 simply will not slice.  I'll go ahead and close this as well as the Cura team has many examples of this behavior to work with.  I hope you understand.
