### ISSUE TITLE
Slicing Failed-Merged Models

### ISSUE THREAD

**Issue by Lobo-Mostla** [Ultimaker/Cura#16391]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.5

### Printer

Ultimaker S5

### Describe your model

a model for dual printing

### Add your .zip here ⬇️

[UMS5_octopus_part2_origin.3mf.zip](https://github.com/Ultimaker/Cura/files/12263688/UMS5_octopus_part2_origin.3mf.zip)
<img width="1434" alt="Screenshot 2023-08-04 at 12 35 10 p m" src="https://github.com/Ultimaker/Cura/assets/141448444/33bcf219-e548-4254-9c5c-5dfaeeaa8fde">

**Comment by GregValiant** [comment]
Thanks for the report and the file.
It wouldn't slice for me either.  I changed the Initial Layer Height to 0.27 and it sliced.

I'll mark this as a duplicate report and the Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
