### ISSUE TITLE
unable to slice

### ISSUE THREAD

**Issue by sotsot2** [Ultimaker/Cura#16397]
### Cura Version

5:3:1

### Operating System

window 11

### Printer

ender 3 v2

### Name abnormal settings

unable to slice

### Describe model location

center

### Describe your model

watertight model

### Add your .zip here ⬇️

<img width="831" alt="Screenshot 2023-08-05 211252" src="https://github.com/Ultimaker/Cura/assets/141351806/a48dda28-d608-47fe-bac1-4dbe0d400de4">

**Comment by GregValiant** [comment]
Thanks for the report but without a Project File there cannot be an investigation.
