### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by DCLAW** [Ultimaker/Cura#16390]
### Cura Version

5.4.0

### Operating System

MacOS Sonoma Beta 4

### Printer

Custom FFF Printer

### Name abnormal settings

This model slices fine on the exact same machine/system but on Cura 5.3.1.  When I downgrade, I can slice, when I upgrade to 5.4.0, it fails.

### Describe model location

I did try to move it away from the center of the build plate.  There is plenty of room on all sides of the model.

### Describe your model

Yes, this model slices just fine on my older laptop with 5.3.1.  Then I downgraded from 5.4.0 to 5.3.1 and it slices fine.  When I upgrade back to 5.4.0, it fails again.  Seems to be directly related to that version of Cura.

### Add your .zip here ⬇️

[Test export.3mf.zip](https://github.com/Ultimaker/Cura/files/12263465/Test.export.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Yes, 5.4.0 is not doing well.  I cannot get it to slice that model.
At this time I would suggest going back to 5.2.2 as it had less issues than 5.3.1.

I'll mark this as a duplicate and go ahead and close it.  There are a lot of reports of slicing problems with 5.4.0 and I'm sure the Cura team has enough examples for them to work on.  I hope you understand.
