### ISSUE TITLE
where can i get help with developing a plugin for Cura 2.5 beta?

### ISSUE THREAD

**Issue by zoff99** [Ultimaker/Cura#1639]
https://github.com/zoff99/ElectricPrintCostCalculator

the plugin already works, but i want to access a few values in the plugin.
* printing time
* printing cost (only PLA cost now in 2.5)
* material weight

so i can use those in calculating the realistic cost (electricity and more ...)

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/blob/master/resources/qml/JobSpecs.qml#L202 about how to get the lengths, weights and costs based on what is entered into the Materials pane of the preferences.

**Comment by zoff99** [comment]
i would need the calculated data. not the static data,

these 2 values:

![values001](https://cloud.githubusercontent.com/assets/6833516/24602214/271b9c50-185c-11e7-8a1b-cbed4cfeb3d7.png)


so i do NOT need to enter them manually in the input fields here:

![values002](https://cloud.githubusercontent.com/assets/6833516/24602223/2c26cfa8-185c-11e7-907d-a88dd2e61fd8.png)

**Comment by fieldOfView** [comment]
You can get them from PrintInformation.currentPrintTime and PrintInformation.materialCosts respectively. Note that both of these return an array as they can include information from multiple extruders (which you will have to add up for this plugin).

**Comment by zoff99** [comment]
any chance of putting a feature like this into Cura itself?

**Comment by fieldOfView** [comment]
That's not up to me to decide, but I don't think the Ultimaker devs will get much time to spend on this so it would have to come from a community member like you and I. 

It should work fairly well as a plugin downloadable, right?

**Comment by fieldOfView** [comment]
That's not up to me to decide, but I don't think the Ultimaker devs will get much time to spend on this so it would have to come from a community member like you and I. 

It should work fairly well as a plugin downloadable, right?

**Comment by zoff99** [comment]
is there a central plugin list or registry where i can link mine to?

**Comment by nallath** [comment]
We're probably not going to build it, but by all means develop it! At the moment we are actively looking into making some sort of plugin repository so it will be easier to discover & share plugins.

Also note that it doesn't have to be a plugin. If it makes way more sense to put it in the "main" code, that's acceptable as well. Do note that we will review & test changes outside of plugins a whole lot better, so it could lead to a delayed acceptance.

**Comment by zoff99** [comment]
wow thanks a lot. this is already working now.
only thing i need is to know when slicing/printtime changes? what signal do i need there? how do i catch it?

**Comment by zoff99** [comment]
and also how can i get the currency symbol ($,€) that is set in the settings?

**Comment by fieldOfView** [comment]
The values from PrintInformation.currentPrintTime and PrintInformation.materialCosts should automagically update. The currency symbol can be accessed with UM.Preferences.getValue("cura/currency")

**Comment by zoff99** [comment]
yes they do, but my plugin does not update :-)
not sure where i can just say do it again ...

**Comment by fieldOfView** [comment]
The best/easiest way is to get the values in QML instead of in python. You can remove most of the logic in the python part of your plugin (because it is already made available to QML from another part of Cura).

**Comment by zoff99** [comment]
can't get the values to update. it works only on the first call.
don't know what i am doing wrong :-(

**Comment by fieldOfView** [comment]
You can't get the values to update _because you are trying to do this in Python_, instead of in QML. You have based your plugin on a rather old plugin by @nallath, and by now there are better ways of doing what you want to do.

It is possible to make it work in Python (ofcourse), but it can be done much more elegantly in QML now. Look how JobSpecs.qml handles the values.

**Comment by zoff99** [comment]
https://github.com/zoff99/ElectricPrintCostCalculator

so the latest version now works pretty nice.
can you guys link it to

https://github.com/Ultimaker/Cura#third-party-plugins

please?

**Comment by nallath** [comment]
71bb3c3a22b9b21d761af15f0c3f72a4aed553dd There ya go.

For the next time, you can also make a pull request on our readme right away.

**Comment by Ghostkeeper** [comment]
Without testing it myself, I wonder. How significant are the electricity costs compared to the filament, typically?

**Comment by BagelOrb** [comment]
I suppose this question is answered.
