### ISSUE TITLE
Tree support is missing in Cure 5.4

### ISSUE THREAD

**Issue by KoronGIT** [Ultimaker/Cura#16398]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Elegoo Neptun 3 Pro

### Reproduction steps

Slicing a model in Cure 5.4 with tree support. 

### Actual results

Tree support is missing in required places

### Expected results

The tree support is created correctly as in 5.3.

### Add your .zip and screenshots here ⬇️

I did the whole thing once with the exact same settings in Cure 5.3 and Cura 5.4. Also reset to default settings and also move, rotate and change the layer height of the model.

The problem persists.

In Cura 5.3 it is correct: ![cura5_3](https://github.com/Ultimaker/Cura/assets/16877169/e6663b5e-ea0c-44cd-9c6e-727e5c32f4ba)

At Cura 5.4. is it wrong. I once marked it with green circles.
![cura5_4](https://github.com/Ultimaker/Cura/assets/16877169/043497f4-b05a-4be5-acf5-432d23fa1952)

**Comment by ThomasRahm** [comment]
Set `minimum support area` to 0 and it should work.

**Comment by KoronGIT** [comment]
> Set `minimum support area` to 0 and it should work.

This change worked and the support is now generated correctly.
![cura_5 4_fix](https://github.com/Ultimaker/Cura/assets/16877169/ba7e57c7-60a6-43bb-b1ab-887c6016495c)

**Comment by GregValiant** [comment]
Thank you @ThomasRahm .
I'll go ahead and close this.
