### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by SWO12345** [Ultimaker/Cura#16401]
### Cura Version

5.4.0

### Operating System

windows 10 pro

### Printer

elegoo neptune 3pro

### Name abnormal settings

no

### Describe model location

no

### Describe your model

yes

### Add your .zip here ⬇️

fix it

**Comment by GregValiant** [comment]
I'm sorry but I don't see in your report where anything is broken.
I'll go ahead and close this.  I hope you understand.
