### ISSUE TITLE
err

### ISSUE THREAD

**Issue by stwillocks** [Ultimaker/Cura#16404]
### Cura Version

5.4.0

### Operating System

w11

### Printer

two trees sapphire plus

### Name abnormal settings

default/

### Describe model location

all build plate more than 1 model

### Describe your model

electronic box 

### Add your .zip here ⬇️

![ss](https://github.com/Ultimaker/Cura/assets/45604983/2a40ec1f-2b3b-4390-b057-1f4db20c0f41)
[boxbox.zip](https://github.com/Ultimaker/Cura/files/12269298/boxbox.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is why we ask for a Project File ("File | Save Project" and zip it).  It slices for me by I don't have any of your settings so I'm unable to duplicate any problem you might be having.
