### ISSUE TITLE
Digital Factory Crashes when trying to delete a print

### ISSUE THREAD

**Issue by redmagejr** [Ultimaker/Cura#16415]
### Cura Version

5.4.0

### Operating System

Windows 10/ Chrome 115.0.5790.171

### Printer

Ultimaker S5/S3

### Reproduction steps

Logged into Digital Factory
Select Print Jobs for Printer
Select Print Job and Click Delete from menu
System "locks up" then shows printer as "disconnected" and print still remains in queue

### Actual results

Printer becomes disconnected and printer/cura/browser all need to be restarted. Deleted print still remains in queue/ 

### Expected results

Print should be removed from queue and printer should not disconnect.

### Add your .zip and screenshots here ⬇️

![DigitalFactory_DeleteCrash](https://github.com/Ultimaker/Cura/assets/4010440/8dc7a3ae-82ef-428a-8b58-085d9464126f)

**Comment by MariMakes** [comment]
Hey @redmagejr,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

This doesn't seem like a bug we can fix with the Cura team. 
Are you still stuck? Then it's better to contact our actual support team. 
You can reach them here: https://support.ultimaker.com/s/contactsupport

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
