### ISSUE TITLE
continuous failure slicing helmets

### ISSUE THREAD

**Issue by trmacd** [Ultimaker/Cura#16418]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

anymaker chiron

### Describe your model

mando helmet

### Add your .zip here ⬇️

[AC_mandalorian-helmet.zip](https://github.com/Ultimaker/Cura/files/12283943/AC_mandalorian-helmet.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug that has been reported numerous times that keeps models from slicing.  There are 3 possible workarounds.  Rotate the model in Cura, move the model in Cura, make a slight change to the "Initial Layer Height".  In this casee I did all three and it sliced.  It's nearly a 60 hour print and 1100 gms of filament (more than a roll).
![image](https://github.com/Ultimaker/Cura/assets/64202104/57d92dcb-4dbf-4567-a1a2-71c7becf3ddc)

I'll mark this as a duplicate and go ahead and close this as the Cura team has a lot of examples of this behavior.  I hope you understand.
