### ISSUE TITLE
5.4.0 Slicing failed -- with "Print thin walls" checked

### ISSUE THREAD

**Issue by csterlin** [Ultimaker/Cura#16417]
### Cura Version

5.4.0

### Operating System

Windows 11 Home, 22H2, 22621.1778, Intel(R) Iris(R) Xe Graphics

### Printer

Ender 3

### Name abnormal settings

"Print thin walls" being checked caused the slicing failure in this case

### Describe model location

no

### Describe your model

Yes, with "Print thin walls" unchecked, yes, watertight, via 3dBuilder and Prusa Slicer, but not with meshtools which could not fix it.

### Add your .zip here ⬇️

The example is with the file scaled to 600% larger than the original.
[MChouse.zip](https://github.com/Ultimaker/Cura/files/12283744/MChouse.zip)
[5.4.zip](https://github.com/Ultimaker/Cura/files/12283752/5.4.zip)

**Comment by Kiefels2** [comment]
I have recently ran into this problem AGAIN. Went away for a while but now it's back again, even on models it sliced the day previous. 
Tried the new beta 2 version and it does it in that also.
I have not added any new hardware or sofware, so at a loss on why this came back

**Comment by HellAholic** [comment]
Small update,
Issue is resolved in CURA-11570 and will be part of the next Cura release.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
