### ISSUE TITLE
PLANTAGE

### ISSUE THREAD

**Issue by MOCO51** [Ultimaker/Cura#16426]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

flsun v400

### Reproduction steps

mise en place de deux fichier sur le plateau 
interaction sur le deplacement et plantage obliger de redemaré 1 fois sur 5
idem des que je modifie dans les reglage la temperature d impression

### Actual results

tout se fige au début ca charge mais même en attendant cela ne reviens pas

### Expected results

que cela ne plante plus ^^

### Add your .zip and screenshots here ⬇️

![Capture d'écran 2023-08-08 152932](https://github.com/Ultimaker/Cura/assets/141742503/441cd16c-1802-43c6-9d96-4ae753ef1274)
![Capture d'écran 2023-08-08 152938](https://github.com/Ultimaker/Cura/assets/141742503/72440442-55e2-48c3-b250-a06179651b43)
![Capture d'écran 2023-08-08 152942](https://github.com/Ultimaker/Cura/assets/141742503/95994ea6-813c-4038-805f-5728a2246c21)
![Capture d'écran 2023-08-08 152944](https://github.com/Ultimaker/Cura/assets/141742503/ad0b29f3-415f-4e96-a0fd-56c0dc0d2139)
![Capture d'écran 2023-08-08 152947](https://github.com/Ultimaker/Cura/assets/141742503/57e5a2ac-4e1e-49d4-9068-20bc30c96519)
![Capture d'écran 2023-08-08 152948](https://github.com/Ultimaker/Cura/assets/141742503/09f82be4-828d-4f24-8ac9-e4016e647e01)
![Capture d'écran 2023-08-08 152951](https://github.com/Ultimaker/Cura/assets/141742503/493e31d5-7878-4021-827d-d8cb8addcf9f)
![Capture d'écran 2023-08-08 152954](https://github.com/Ultimaker/Cura/assets/141742503/79dfc693-fe3d-49cd-8840-ad105ab26d8c)
![Capture d'écran 2023-08-08 152957](https://github.com/Ultimaker/Cura/assets/141742503/b57820f3-773b-4140-97f0-41336f6cf76b)

**Comment by GregValiant** [comment]
Thanks for the report.
All those screenshots are nice but without a Project file and your Cura.log file there can be no investigation.
