### ISSUE TITLE
Tree support = cold build plate

### ISSUE THREAD

**Issue by templecorran** [Ultimaker/Cura#16422]
### Cura Version

5.4.0

### Operating System

macOS 11.7.8

### Printer

any cubic kobra Neo

### Reproduction steps

Using PLA
Opened a stl model, selected tree support. touching build plate, all other as default.
The M140 S60, M105, M190 S60 code sequence is missing.

If I open the same model but select Normal support the M140 / M190 code is present.

### Actual results

?
I edit the g-code to include the M140 S60 / M105 / M190 S60. to get bed to heat

### Expected results

n/a

### Add your .zip and screenshots here ⬇️

n/a

**Comment by GregValiant** [comment]
Thanks for the report.
The definition file for the Neo defines the StartUp Gcode and contains this line.
M190 S{**material_bed_temperature_layer_0**}
When Cura sees a "replacement pattern" in the Startup it knows it doesn't have to put the command in itself, just make the replacement (in this case 60° for "material_bed_temperature_layer_0").  It sets the bed temperature and waits for the bed to heat up.  The M140 line is not required.
So it has nothing to do with Supports.  I sliced a model every which way and cannot duplicate this behavior.
Use the "File | Save Project" command and zip the 3mf file and post the zip folder here.  UltiMaker is not responsible for 3rd party printer definition files and the StartUp Gcode is subject to customization by the end user.
