### ISSUE TITLE
Angry Hulk Body wont slice

### ISSUE THREAD

**Issue by Jamelb** [Ultimaker/Cura#16438]
### Cura Version

5.4

### Operating System

MacOS Sonoma

### Printer

Anycubic Kobra+

### Reproduction steps

Load STL file, slice and receive error 

### Actual results

File fails to slice

### Expected results

File slices, I print and dance for joy. 

### Add your .zip and screenshots here ⬇️

<img width="1538" alt="Corpo" src="https://github.com/Ultimaker/Cura/assets/343432/6d8ecd00-1a87-46ec-9134-35cdd800ac12">

**Comment by MariMakes** [comment]
Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
