### ISSUE TITLE
Learn More link points to salesforce 

### ISSUE THREAD

**Issue by oohookoo** [Ultimaker/Cura#16458]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

ender 3 v2 neo

### Reproduction steps

Marketplace-> manage packages link -> top of window has a notification about making sure to keep plugins up to date.
'Learn More' directs to a salesforce login page 

#unexpectedbehavior.

### Actual results

directs to salesforce page

### Expected results

doesn't go to salesforce login.

### Add your .zip and screenshots here ⬇️

![Screenshot 2023-08-10 182507](https://github.com/Ultimaker/Cura/assets/3816351/d6f1f933-b930-4cdb-9ea3-50c6e69da6fa)
![Screenshot 2023-08-10 182552](https://github.com/Ultimaker/Cura/assets/3816351/9c2b251f-295b-4abd-9499-2dc443e42867)

**Comment by MariMakes** [comment]
Hey @oohookoo,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

We are migrating our support pages, so some of our redirects are broken. I encountered exactly the same issue earlier this week and reported it. I was told it was resolved but seeing your report, it might not be the case. 

I'll bring it up to the team to see what they can do to fix it. Thanks for keeping us sharp 😊 
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Quick update, there was a typo we overlooked https://github.com/Ultimaker/Cura/blob/298f00ebdeb545ea93d56001c962b5eb8a26f1ab/plugins/Marketplace/resources/qml/ManagedPackages.qml#L17

So we are double-checking the work done. 
Hopefully it's resolved soon. Thanks again 👍

**Comment by MariMakes** [comment]
Hey 👋 
Because of your report a number of Learn More Links have been fixed now, 👍 
I'll close this issue, thanks again 😊
