### ISSUE TITLE
вентилятор

### ISSUE THREAD

**Issue by SergeyHSV76** [Ultimaker/Cura#16471]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

Ender 3 pro

### Describe your model

В другой версии Cura работает

### Add your .zip here ⬇️

`[](url)`
[CE3PRO_turbine_small.zip](https://github.com/Ultimaker/Cura/files/12328777/CE3PRO_turbine_small.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
