### ISSUE TITLE
Issue slicing

### ISSUE THREAD

**Issue by one4nukes** [Ultimaker/Cura#16486]
### Cura Version

5.4.0

### Operating System

Window 11

### Printer

AnyCubic Viper

### Name abnormal settings

No

### Describe model location

No

### Describe your model

No, Yes, Yes, No,No ,no

### Add your .zip here ⬇️

[New Compressed (zipped) Folder.zip](https://github.com/Ultimaker/Cura/files/12345359/New.Compressed.zipped.Folder.zip)

Both Models are having, issue, Still new to 3d printing, so not sure what to do fully do.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
