### ISSUE TITLE
Problem slicing dragon mini for DND in Cura 5.4

### ISSUE THREAD

**Issue by Hendarkii** [Ultimaker/Cura#16482]
### Cura Version

5.4

### Operating System

windows 10

### Printer

Anycubic Kobra Max

### Name abnormal settings

no still crash

### Describe model location

no still crash

### Describe your model

IT does say it is not watertight, when i run the meshtools to fix, cura frezzes for a minute or so, and then return. No promp if it fixed any thing. But will still not slice

### Add your .zip here ⬇️

The file is origanally for Resin printers, but this is not the first file for resin printer i print on pla printer. All other there have been no problem.
did not know if you need both files so used wetransfer for it, but it would not let me submit without a file, so the profile file is there 2 times

Link to files
https://we.tl/t-3YyLMNzHGk

[AKMAX_Adult Gold Dragon Updated (2).zip](https://github.com/Ultimaker/Cura/files/12343085/AKMAX_Adult.Gold.Dragon.Updated.2.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
