### ISSUE TITLE
Slicing fails in default position, ok with vertical object

### ISSUE THREAD

**Issue by arhuaco** [Ultimaker/Cura#16493]
### Cura Version

5.4.0

### Operating System

Ubuntu Linux 22.04

### Printer

KP3S 3.0

### Name abnormal settings

0.5 nozzle, 0.4 retraction, supports at half speed, for Klipper

### Describe model location

Center, if I rotate 90ddegrees it slices and prints

### Describe your model

I did slice it upright, and I printed it

### Add your .zip here ⬇️

[project.zip](https://github.com/Ultimaker/Cura/files/12354627/project.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
