### ISSUE TITLE
Slicing Failed on 5.4.0 but worked on an earlier version

### ISSUE THREAD

**Issue by Jason-BCIT** [Ultimaker/Cura#16492]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender 5

### Name abnormal settings

changed wall thickness, and top/bottom heights but pretty standard settings.

### Describe model location

It sliced at a 90 rotation from the file included in the zip, but failed when I rotated it back to the build plate.

### Describe your model

It sliced fine on a slightly earlier (5.3.1?? can't recall at the moment) version of Cura.

### Add your .zip here ⬇️

[CE5_RPi slicing failure on 540.zip](https://github.com/Ultimaker/Cura/files/12354093/CE5_RPi.slicing.failure.on.540.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
