### ISSUE TITLE
Lion Wall light

### ISSUE THREAD

**Issue by LuisDevLipe** [Ultimaker/Cura#16505]
### Cura Version

5.4

### Operating System

win 11

### Printer

ender 3

### Name abnormal settings

all default chep profile

### Describe model location

centered

### Describe your model

wall light from stlflix

### Add your .zip here ⬇️

[CE3E3V2_Lion Wall Light.zip](https://github.com/Ultimaker/Cura/files/12374381/CE3E3V2_Lion.Wall.Light.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This model is getting more popular but it isn't getting any better.  See bug report #16366 and #16497 for more info.
I'll mark this as a duplicate and go ahead and close this.  I hope you understand.
