### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by gabrieldeampli** [Ultimaker/Cura#16500]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender3

### Describe your model

I have sliced OK at 100% scale. It fails on 150%

### Add your .zip here ⬇️

[CE3E3V2_VARITECH-3.zip](https://github.com/Ultimaker/Cura/files/12369757/CE3E3V2_VARITECH-3.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing this either with or without supports.
There is a known bug in 5.4.0 that can keep a model from slicing.  There are three workarounds that can sometimes fool the bug.

- Move the model on the Cura build plate.
- Rotate the model in Cura.
- Change the initial layer height by a little bit (like from 0.12 to 0.15).

Let us know if any of those work to free up the slice.
