### ISSUE TITLE
Unerwarteter Fehler

### ISSUE THREAD

**Issue by A-Apache** [Ultimaker/Cura#16502]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Geeetech Mizar M

### Name abnormal settings

unerwarteter Fehler

### Describe model location

no

### Describe your model

no

### Add your .zip here ⬇️

[Projekt.zip](https://github.com/Ultimaker/Cura/files/12371592/Projekt.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
