### ISSUE TITLE
Unable to slice large model

### ISSUE THREAD

**Issue by link1021l** [Ultimaker/Cura#16504]
### Cura Version

5.4.0

### Operating System

Windows 11, Ryzen 7 5700X, NVIDIA 4070TI 

### Printer

Anycubic Vyper

### Name abnormal settings

Model scaled up to 145% and 175%, default profiles fail to slice both. Still cannot slice at 100% scale

### Describe model location

Tested model in different positions and rotated it as well, Cura would still not slice. Tested model at default size and it can still not slice

### Describe your model

I have sliced this model at 175% scale in Prusa Slicer without issue. Mesh Fix shows model as watertight

### Add your .zip here ⬇️

[AV_Four_Corner_Coiled_Rope_Bowl project.zip](https://github.com/Ultimaker/Cura/files/12372858/AV_Four_Corner_Coiled_Rope_Bowl.project.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
