### ISSUE TITLE
slice failed after switching to PLA from PETG

### ISSUE THREAD

**Issue by jigsawhc** [Ultimaker/Cura#16528]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 2 Max

### Name abnormal settings

none

### Describe model location

center

### Describe your model

printed it fine before

### Add your .zip here ⬇️

[Bolt Action Fidget Body threaded v7.zip](https://github.com/Ultimaker/Cura/files/12391674/Bolt.Action.Fidget.Body.threaded.v7.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
