### ISSUE TITLE
Unexpected Error when Slicing

### ISSUE THREAD

**Issue by Aqueousfun** [Ultimaker/Cura#16527]
### Cura Version

5.4

### Operating System

Windows 10 Pro

### Printer

Ender 3 S1 Pro

### Describe model location

I have moved the model all around the plate, and rotated it tons of times. 

### Describe your model

Model is watertight, have not been able to get it to slice. 

### Add your .zip here ⬇️

[CFFFP_Ground Floor.zip](https://github.com/Ultimaker/Cura/files/12391248/CFFFP_Ground.Floor.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
