### ISSUE TITLE
Upload and Export Does Not Function

### ISSUE THREAD

**Issue by bellertm1** [Ultimaker/Cura#16538]
### Cura Version

5.2.1

### Operating System

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. Uploaded .stl 
2. Sliced .stl and Gcode created
3. Attempt to use export/upload Btn next to "Preview" Btn to export the completed slice

### Actual results

Button to export to a file location or upload to Creality site does not react when pressed and drop down portion of Btn does not react

### Expected results

Option to upload to Gcode to Creality cloud or select location to export it to a location or upload it to Creality cloud

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/49034870/737c854e-1a18-490f-940c-9f2957c596dd)

**Comment by MariMakes** [comment]
Hey @bellertm1,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

To me, it doesn't seem like a bug in UltiMaker Cura, but more like one for the makers of the Creality Plugin. 🤔 
You can check if it's related to the plug-in by temporarily disabling it. 

This is how you can check:
1. Open the marketplace
2. Click on the Gear
3. Find the Plug-in
4. Click on Disble
5. Reboot Cura
6. Attempt to export the completed slice

![image](https://github.com/Ultimaker/Cura/assets/40423138/0299be9b-fabd-4c1f-8fd0-3e613753245d)

Would you still like to keep this issue open or do you agree that we can close it?
