### ISSUE TITLE
Slicing Bug

### ISSUE THREAD

**Issue by ares2885** [Ultimaker/Cura#16537]
### Cura Version

5.4.0

### Operating System

WINDOWS 11

### Printer

ANYCUBIK KOBRA NEO

### Reproduction steps

SI BLOCCA DURANTE IL SEZIONAMENTO 

### Actual results

CONTINUI BUG

### Expected results

NON DOVREBBE PIU BLOCCARSI

### Add your .zip and screenshots here ⬇️

CONTINUI BUG SU SEZIONAMENTO

**Comment by MariMakes** [comment]
Hi @ares2885,

Mi dispiace, non parlo italiano ma penso di poterti aiutare.
Welcome to the UltiMaker Cura Github 🚀 

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
