### ISSUE TITLE
Bolt CCS Support Wedge

### ISSUE THREAD

**Issue by dogunter** [Ultimaker/Cura#16541]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.4

### Printer

Creality Ender 3 v2

### Name abnormal settings

No

### Describe model location

It will not slice in any location or any rotation

### Describe your model

I have never printed/sliced this before, many people have.

### Add your .zip here ⬇️

[Bolt_CCS_Support_v5.5_Wide.3mf.zip](https://github.com/Ultimaker/Cura/files/12414307/Bolt_CCS_Support_v5.5_Wide.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
