### ISSUE TITLE
slice fail

### ISSUE THREAD

**Issue by marzx0** [Ultimaker/Cura#16557]
### Cura Version

5.4.0

### Operating System

MacOS Ventura

### Printer

Creality CR-10 Smart PRo

### Name abnormal settings

none

### Describe model location

rotated 90 degrees

### Describe your model

Sculpt, sliced before perfectly

### Add your .zip here ⬇️

[CCR10SPRO_FathersDaySculpture.3mf.zip](https://github.com/Ultimaker/Cura/files/12438136/CCR10SPRO_FathersDaySculpture.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
