### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by Nostang3** [Ultimaker/Cura#16554]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender V3 S1

### Name abnormal settings

None

### Describe model location

sliced as loaded

### Describe your model

Just a mount. Simple L bracket

### Add your .zip here ⬇️

[CE3S1_BIGTREETECH-PI-TFT-5inch_V1.0_2020_Extrusion_Mount.zip](https://github.com/Ultimaker/Cura/files/12434013/CE3S1_BIGTREETECH-PI-TFT-5inch_V1.0_2020_Extrusion_Mount.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
