### ISSUE TITLE
Slicing Failed when centered

### ISSUE THREAD

**Issue by SQL-enwiki** [Ultimaker/Cura#16553]
### Cura Version

5.4.0

### Operating System

Garuda Linux (Arch-like)

### Printer

FLSun Super Racer

### Describe model location

Model slices if I move it to the side of the build plate

### Describe your model

Model 3d engine. Model slices w/o issue in other slicers.

### Add your .zip here ⬇️

[FSR_AllPiecesBig.zip](https://github.com/Ultimaker/Cura/files/12433822/FSR_AllPiecesBig.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
