### ISSUE TITLE
disallowed area by extruder offset

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1655]
Is there a way to disable the disallowed area that is being generated by the extruder offsets ?

**Comment by nallath** [comment]
Not without changing the code. Why do you ask?

**Comment by maukcc** [comment]
I wanted to make the prime tower in the disallowed area.
This issue can be closed then.

**Comment by Ghostkeeper** [comment]
The prime tower needs to be printable by all nozzles that are used in the print, because it sometimes needs to prime those nozzles.
