### ISSUE TITLE
Vyper - Cura 5.4.0 - Error to Slice

### ISSUE THREAD

**Issue by josepauloalmeida** [Ultimaker/Cura#16558]
### Cura Version

5.4.0

### Operating System

Windows 11 Pro

### Printer

Anycube Vyper

### Describe your model

It is the first time I try to slice this model.

### Add your .zip here ⬇️

[terminator.zip](https://github.com/Ultimaker/Cura/files/12438324/terminator.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
