### ISSUE TITLE
Worked fine before on this same build.

### ISSUE THREAD

**Issue by jahorgos** [Ultimaker/Cura#16568]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ultimaker S5

### Name abnormal settings

same as I've used previously

### Describe model location

default, center

### Describe your model

Yes

### Add your .zip here ⬇️

[UMS5_Chinese Puzzle Ball Plain Loose.zip](https://github.com/Ultimaker/Cura/files/12446669/UMS5_Chinese.Puzzle.Ball.Plain.Loose.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
