### ISSUE TITLE
Articulated Octopus slicing fail

### ISSUE THREAD

**Issue by rbenites** [Ultimaker/Cura#16569]
### Cura Version

5.4.0

### Operating System

Windows 11 home

### Printer

Creality Ender -3 S1 Pro

### Name abnormal settings

default settings

### Describe model location

Yes, if i rotate it around about 90deg horizontal the slice works.

### Describe your model

This was a first time slice. I have not used anyother plugin yet

### Add your .zip here ⬇️

[CE3S1PRO_Octopus Plush by BODY3D ( Fix ).zip](https://github.com/Ultimaker/Cura/files/12446670/CE3S1PRO_Octopus.Plush.by.BODY3D.Fix.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
