### ISSUE TITLE
Skirt issue

### ISSUE THREAD

**Issue by Almazick** [Ultimaker/Cura#16572]
### Cura Version

5.4

### Operating System

Window 10

### Printer

Ender 3 Pro

### Reproduction steps

Skirt enabled

### Actual results

skirts print 3 layers instead of just 1 layer.

### Expected results

skirt 1 layer

### Add your .zip and screenshots here ⬇️

skirt issue

**Comment by Asterchades** [comment]
Correct.

This is a new - documented - feature of 5.4, called `Skirt Height`, and it does exactly what it sounds like it should. The intent is to make the Skirt easier to remove without using fingernails or tools, risking damage to your printer or your person. By default it has a value of 3 when the `Skirt Distance` is above 0 (which it pretty much always will be) and to my knowledge no profiles currently change this.

Note that by default it is hidden until the Expert level settings are in use or its visibility has been manually toggled by the user. You can also search for it by name.

ref: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
> - Introduced Skirt Height setting to make a skirt easier to remove
