### ISSUE TITLE
Random Slicing crash

### ISSUE THREAD

**Issue by planecrazy29** [Ultimaker/Cura#16578]
### Cura Version

5..4.0

### Operating System

Windows 11

### Printer

Creality Ender 3

### Name abnormal settings

Only changed temp and infill from previous model

### Describe model location

upside down, flat on plate.  Right side up slices

### Describe your model

Simple fuel cap.  First slicing attempt.

### Add your .zip here ⬇️

[CE3E3DD_JD 3038 Fuel Cap.zip](https://github.com/Ultimaker/Cura/files/12448052/CE3E3DD_JD.3038.Fuel.Cap.zip)

Very simple file.  Never had issues slicing before.  No supports, flat portion of part on plate doesn't slice.  No supports open portion of part on plate, slices.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
