### ISSUE TITLE
Initial print temperature always starts at 240°C

### ISSUE THREAD

**Issue by magnum61** [Ultimaker/Cura#16573]
### Cura Version

5.4.0

### Operating System

Linux (same behavior on any flavor)

### Printer

Creality K1 Max

### Reproduction steps

I have created a new printer based on the settings of Creality Print.
That includes the following start code:

```
M140 S0
M104 S0
START_PRINT EXTRUDER_TEMP=[material_print_temperature_layer_0] BED_TEMP=[material_bed_temperature_layer_0]

```
i also created different profiles for my used filament (only PLA in different flavors so far).
All goes fine, but once i upload the GCODE to the printer and start printing, the initial print temperature of the hotend always jumps up to 240°C and remain there until i change it manually on the printer.

Once i change it back to the value i selected in the profile it works perfect.
What causes that temperature jump? The default profiles of Cura also do not indicate that high temperature. They are all set to 200°C

The screenshot below shows the beginning of the GCODE. Looks the same on all of my prints

### Actual results

Print temperature of Nozzle is set to 240°C

### Expected results

Print temperature need to be set to the given temperature in profile

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/59759323/71b8165a-ddab-438a-80d7-8e96d314734d)

**Comment by Asterchades** [comment]
Those are not valid Cura placeholder names and as such they're simply being passed through verbatim. You'll want to replace the square brackets with curled ones - eg `{material_print_temperature_layer_0}`. The actual placeholder names themselves still appear to be the same, so I'm not sure why Creality went through the effort in making sure the brackets were different, but their design choices are beyond the scope of the main repository.

This is also why it's adding additional temperature commands prior to your Klipper macro, setting the temperatures to 210/60 in this instance before your start code disables the heaters and calls the macro (which I assume has default values that include 240°c for the tool). Cura has a failsafe to ensure the printer is heated in the event valid placeholders are not found to do the job.
