### ISSUE TITLE
Slice problem with Eiffel Tower file

### ISSUE THREAD

**Issue by thiagovictorino** [Ultimaker/Cura#16584]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender-3 S1

### Describe your model

My model is The Eiffel Tower. Sometimes I can slice it, but most of the time it crashes or freezes my Windows and I have to restart my PC. I did all the Mesh fixes.

### Add your .zip here ⬇️

[CE3S1_EiffelTower_fixed.zip](https://github.com/Ultimaker/Cura/files/12448835/CE3S1_EiffelTower_fixed.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
