### ISSUE TITLE
Error Slicing groot, normal.

### ISSUE THREAD

**Issue by josht000** [Ultimaker/Cura#16594]
### Cura Version

5.4.0

### Operating System

Windows

### Printer

Anycubic Vyper

### Name abnormal settings

default - normal

### Describe model location

center

### Describe your model

groot

### Add your .zip here ⬇️

Draft quality slices, but 'Normal does not. 
[Groot.zip](https://github.com/Ultimaker/Cura/files/12454101/Groot.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model has been here before in at least one other bug report.  I've never been able to get it to slice in 5.4.0 but 4.13.1 doesn't have a problem with it.
I'll mark this as a duplicate and go ahead and close this as the Cura team has a lot of reports on this behavior. I hope you understand.
