### ISSUE TITLE
New tree supports huge bed sticking issue

### ISSUE THREAD

**Issue by ramsestom** [Ultimaker/Cura#16599]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Artillery sidewinder X2

### Reproduction steps

I recently update from cura 5.2.x to cura 5.4.0 and I have a big problem with the way new tree supports are made (I think there is a bug in the way these supports bases (contact interface with the printer bed) are made).
The tree supports from the previous cura version where designed by cura with a plane and plain contact interface with the printer bed. So there was no risk of them detaching from the printer bed during the print. But in cura 5.4.0 the tree suports are directly printed on the bed with no base. It's just the wall of the trunk (a single line) that is in contact with the printer bed (there is also a second internal line, that is attached to nothing (see screenshot) at every support's trunk base. So I guess there is some bug here as I would have think that the trunk wall first layer line would at least be attached to this internal line with some other lines, else this internal 1 layer tall line really makes no sense). As a consequence when printing the second or third layer, these supports tend to come off the bed (even with a heating bed) and get caught by the printer nozzle, completely ruinning the print. Actually, I have not succeed to have a correct print with the new tree supports without using a raft (wich is a nonsense as I have a heating bed so it's just wasting material because of the baddly designed/non existing base of new tree supports).
Would it be possible to restore the plain contact base of tree supports with the bed, or at least have an option in the interface to force them without having to get a raft for the full print?    

### Actual results

tree supports first layer detaching from the printer bed during the print of next layers, completely running the print

### Expected results

tree supports sticking to the printer bed (by intreassing the contact interface)

### Add your .zip and screenshots here ⬇️

![cura_tree_supports_bed_interface](https://github.com/Ultimaker/Cura/assets/636758/e5c0884a-7a16-46a5-aec7-051d7c1920a3)

**Comment by GregValiant** [comment]
Thanks for the report.
Yes, there is a bug that affects the "Support Brim" and the "Prime Tower Brim".
The workaround is to enable "Skirt" or "Brim".  If you enable the skirt you can set the "Skirt Line Count" to "0" and there won't be a skirt but it will fool the bug that affects the Support and Prime Tower Brims.

I'll mark this as a duplicate and go ahead and close this.  The Cura team is aware of this bug and it has been worked on and should be fixed in the next release.  I hope you understand.

**Comment by ramsestom** [comment]
Thanks for the quick reply. 
The trick of the Skirt with a 0 line count (tested it today on a print and it works fine) would do the job for now until this bug is properly solved in the next release
