### ISSUE TITLE
Slice failed, after rotation to address infinite runtime during slice

### ISSUE THREAD

**Issue by sanslos** [Ultimaker/Cura#16601]
### Cura Version

5.4.0

### Operating System

Windows 10 Pro

### Printer

RadZ 0.4

### Name abnormal settings

Failed using Normal (0.15mm).  Support everywhere enabled

### Describe model location

Rotated 90 degrees from original

### Describe your model

Simple display piece with complex image at top

### Add your .zip here ⬇️

[CFFFP_Snaggy Meow Wolf.zip](https://github.com/Ultimaker/Cura/files/12458455/CFFFP_Snaggy.Meow.Wolf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
