### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by REDTRUK** [Ultimaker/Cura#16603]
### Cura Version

5.3.0

### Operating System

Windows 11

### Printer

TENLOG

### Reproduction steps

Executed slice command

### Actual results

Slice failed notification

### Expected results

STL file creation

### Add your .zip and screenshots here ⬇️

[LAV_25_1960505.zip](https://github.com/Ultimaker/Cura/files/12458791/LAV_25_1960505.zip)

**Comment by VoxelTek** [comment]
After running a quick online repair tool on one of the files, it now imports and slices perfectly, with no issues.

I'd recommend running all the broken files you have through some sort of STL repair tool, such as [the one I used.](https://www.formware.co/OnlineStlRepair)

[LAV25_fixed.zip](https://github.com/Ultimaker/Cura/files/12458891/LAV25_fixed.zip)

**Comment by VoxelTek** [comment]
If this is now solved, please mark this issue as closed.

**Comment by REDTRUK** [comment]
ClosedOn Aug 29, 2023, at 10:52 PM, VoxelTek ***@***.***> wrote:﻿
If this is now solved, please mark this issue as closed.

**Comment by GregValiant** [comment]
Thanks for getting back.  I'm glad it is working.
