### ISSUE TITLE
Feature request: Add "save as" option for Octoprint

### ISSUE THREAD

**Issue by Revxel** [Ultimaker/Cura#16611]
### Is your feature request related to a problem?

This is a QoL improvement for Octoprint and maybe another remote printer software. When trying to “Print with Octoprint” i would like to change the name of the output file without having to “save to disk” and later upload that file.

 Other inconveniences come from items from extension from “parts for calibration” will be uploaded as “untitled”. 

![image](https://github.com/Ultimaker/Cura/assets/118232935/7a768e55-3e02-4df8-90fc-b3dbc5b3820c)

![image](https://github.com/Ultimaker/Cura/assets/118232935/ca103300-34eb-48c9-aa18-cd563febd3f6)

### Describe the solution you'd like

Add an option that to allows me to save that file with a custom name to Octoprint. "Print with Octoprint As..." would be a nice to have.

Desire option:
![image](https://github.com/Ultimaker/Cura/assets/118232935/9191534f-f495-4b0a-addf-74befab4f04e)

### Describe alternatives you've considered

Saving to disk and later manual upload to Octoprint.
Saving the project, but most of the time there is no use for that.

### Affected users and/or printers

Octoprint users and perhaps others remote users.

### Additional information & file uploads

Thanks for the amazing software :)

**Comment by Asterchades** [comment]
This sounds like something better suited to be addressed by the author of the [OctoPrint Connection plugin on its Git repository](https://github.com/fieldOfView/Cura-OctoPrintPlugin). There's no native support for OctoPrint in Cura, so any features related to it are going to be added externally.

Note that you can already rename the current project without any additional coding being done. If you select the name in the lower-left corner of the screen, just above the overall print bounding dimensions and just right of the "pen on pad" icon, you can change the name here. This will in turn change the default filename should you choose to save the project, slice the project and save to GCode, or send it to OctoPrint.
