### ISSUE TITLE
Slicing Orig-Ballerina Failed

### ISSUE THREAD

**Issue by txyankee2** [Ultimaker/Cura#16613]
### Cura Version

Ultimaker Cura 5.4.0 - see attachment

### Operating System

Windows 11, Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 2001 Mhz, 4 Core(s), 8 Logical Processor(s)

### Printer

Mingda Magician X2

### Name abnormal settings

See attached files. No.

### Describe model location

See attached screenshot

### Describe your model

First time to us it. See attched screenshot

### Add your .zip here ⬇️

I will attach the zip file and two screen shots of the model and the printer settings.
[CFFFP_OrigBallerina.zip](https://github.com/Ultimaker/Cura/files/12469297/CFFFP_OrigBallerina.zip)
![Magician X2 Printer Settings on Crash2](https://github.com/Ultimaker/Cura/assets/143553221/036553d2-69f2-4601-aa3f-59597b72846d)
![Magician X2 Printer Settings on Crash](https://github.com/Ultimaker/Cura/assets/143553221/9ef75ecf-c562-4117-a220-4e1d2ebb63b5)
![Using Default seetings crash](https://github.com/Ultimaker/Cura/assets/143553221/fb8ceffa-0cfd-4783-9cd1-576be63f4f15)
![CuraVersion](https://github.com/Ultimaker/Cura/assets/143553221/f001306d-9556-4557-897d-ba572efc6e63)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
