### ISSUE TITLE
MATV print job 

### ISSUE THREAD

**Issue by Boostjuncky** [Ultimaker/Cura#16617]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

ultimaker s5

### Name abnormal settings

No

### Describe model location

center 

### Describe your model

it is a sand table model of a military vehicle 

### Add your .zip here ⬇️

[chasis.zip](https://github.com/Ultimaker/Cura/files/12471287/chasis.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
That model is in serious need of repair.  When Cura adds a polka-dot pattern to surfaces it means the surfaces are in error.
That model is almost all polka-dot.
![image](https://github.com/Ultimaker/Cura/assets/64202104/64578e47-5bd9-41f3-be5e-780c3071173f)

Here is a report on the model from formware.co/OnLineSTLRepair
--> 9759 Naked edges (?)
--> 271 Planar holes (?)
--> 849 Non-planar holes (?)
--> 904 Non-manifold edges (?)
--> 2141 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 979 Duplicate faces (?)
--> 0 Disjoint shells (?)

My normal repair tools couldn't fix it.  Even if it sliced I wouldn't trust it to print correctly.

I'm going to remove the bug label from this as the model has serious issues.  Even if it didn't need repair it really isn't a candidate for FDM printing.  Things like the sideview mirrors and the running board chains simply aren't printable.  I hope you understand.
