### ISSUE TITLE
UM3_GBHS_LOGO 

### ISSUE THREAD

**Issue by MeatyToby** [Ultimaker/Cura#16627]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Ultimaker 3

### Name abnormal settings

Default profile with Raft Bed adhesion checked on

### Describe model location

It does not

### Describe your model

I have sliced it successfully before. The only difference with this time is that I scaled it up from 100% to 125%, and the edges aren't anywhere close to the edges of the buildplate

### Add your .zip here ⬇️

[ImageToStl.com_gbhs+logo.zip](https://github.com/Ultimaker/Cura/files/12478179/ImageToStl.com_gbhs%2Blogo.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The model has some errors.  This is a report from Formware.co/OnLineSTLRepair.
-> Analyzed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> **94 Non-manifold edges (?)**
--> **150 Inverted faces (?)**
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 42270ms ------
-> Vertex count changed from 23127 to 23854 (+727)
-> Triangle count changed from 46580 to 48780 (+2200)

I was able to slice the original model (in 5.4) but it looked bizarre so I had that site repair it and it still looks bizarre.  There are a lot of islands and a lot of stalagmites.
Is this how it's supposed to look?
![image](https://github.com/Ultimaker/Cura/assets/64202104/7baec864-7d94-4377-b649-9bd7dd1d8a1b)

Both 5.3.1 and 5.4 have a bug that can keep models from slicing.  There are three workarounds that can often fool the bug.

- Move the model away from the midpoint of the Cura build plate.
- Rotate the model in Cura.
- Change the Initial Layer Height by just a bit (for example from 0.20 to 0.23)
I'll mark this as a duplicate.  See if any of those, or a combination of them, allows you to slice.
