### ISSUE TITLE
[5.4.0] Sovol SV06 Plus default profile creates unprintable overhangs

### ISSUE THREAD

**Issue by Toastywf** [Ultimaker/Cura#16635]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Sovol SV06 Plus

### Reproduction steps

1. Load model with large [90 degree overhang](https://cdn.discordapp.com/attachments/483268571196162049/1147025819227656262/image.png) 
2. Configure temperatures and supports as normal NOT tree supports
3. Slice using other settings at default

### Actual results

Print fails as the supports are unprintable with these settings

### Expected results

Print should print as previewed
![image](https://github.com/Ultimaker/Cura/assets/66246375/66fbff80-c433-4f49-a096-f930816b3912)

Conical supports with default profile are unprintable and should either be changed to like 25% or be disabled alltogether,
![image](https://github.com/Ultimaker/Cura/assets/66246375/b598ff2a-13cb-467f-8b14-6394514bca79)

### Add your .zip and screenshots here ⬇️

[Conical bug CURA 5.4.0.zip](https://github.com/Ultimaker/Cura/files/12494309/Conical.bug.CURA.5.4.0.zip)

**Comment by Asterchades** [comment]
All third party printer definitions (any which do not list "Ultimaker" as the author) are maintained by the community, as the Cura team lacks the appropriate hardware (and time) to properly test them. As such it's extremely rare that the Cura team will step in to make changes to them.

This particular definition sets the Conical Support Angle to the same 70° it sets the Support Overhang Angle, which suggests whoever made it feels confident this printer (at least as they have it configured) is capable of doing such overhangs without relevant complications. If you disagree with this, and feel the community at large would benefit from having a different default value you are welcome - and indeed encouraged - to submit a pull request altering the default.

The definition in question can be found here: https://github.com/Ultimaker/Cura/blob/main/resources/definitions/sovol_sv06_plus.def.json

**Comment by fieldOfView** [comment]
Note that the "Setting  Visibility" dialog in the preferences just manages whether a setting is shown or not. It does not affect the value of settings at all. A setting that is not shown to the user still has a value and still affects slicing.
