### ISSUE TITLE
Can't send new slice to Ultimaker 3 over Ethernet

### ISSUE THREAD

**Issue by mcguirems** [Ultimaker/Cura#1663]
Cura 2.4

Error message at bottom:
"Unable to start a new print job because the printer is busy.  Please check the printer"

Detail:
- print completed succesfully
- print removed from bed; verified PRINT REMOVED at machine
- deleted part from Cura bed
- loaded new part files
- no changes to settings
- can't send as per above message

**Comment by mqudsi** [comment]
Does powering down and then powering up the printer make a difference?

**Comment by Ghostkeeper** [comment]
Or closing and restarting Cura?

**Comment by mcguirems** [comment]
Yes, both solutions work.
However you lose the settings upon reopen.

M

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by mcguirems** [comment]
Sold the unit.

M.
