### ISSUE TITLE
Slicing failure

### ISSUE THREAD

**Issue by c713s** [Ultimaker/Cura#16647]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.4.1

### Printer

Ender 3 S1

### Describe model location

Rotating to have lower edge flat on build plate

### Describe your model

apple shaped watch and phone holder

### Add your .zip here ⬇️

[Cura Crash.3mf.zip](https://github.com/Ultimaker/Cura/files/12504697/Cura.Crash.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
