### ISSUE TITLE
can't undo scaling 

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1664]
Cura 2.4:
this happens frequently when I have a model loaded and the scale option is still selected. 
I'm trying to move the object with the mouse (not realizing scale is selected - the arrows on the object looks similar enough) - instead the object resizes. However, I can't undo this operation and always have to clear the build plate and reload the model.

**Comment by BagelOrb** [comment]
This is probably because of Drop on Builplate.

I really hate this bug.

**Comment by nallath** [comment]
You hate it so much that you didn't notice that this was fixed about a release ago? ;)
