### ISSUE TITLE
Default directory

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1665]
when I open an STL and then save the gcode I would expect the same directory is being used. Instead, cura seems to select the last directory a file has been saved to. I can see how that is beneficial for users that save all their gcode to a single directory. Maybe have an option in the settings to control the behavior?

**Comment by Ghostkeeper** [comment]
We now save the most recent load directory and the most recent save directory separately, so this shouldn't be an issue any more.

It's not in the preferences dialogue, but I think that wouldn't make much sense anyway.
