### ISSUE TITLE
Cura Crash

### ISSUE THREAD

**Issue by ringocat123** [Ultimaker/Cura#16663]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Go

### Describe model location

Yes

### Describe your model

Never sliced before

### Add your .zip here ⬇️

[Cura Model.zip](https://github.com/Ultimaker/Cura/files/12515264/Cura.Model.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
