### ISSUE TITLE
DEM Model

### ISSUE THREAD

**Issue by mastro-vtg** [Ultimaker/Cura#16668]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender-3 Neo

### Describe your model

It's the first time I'm slicing this model. it's watertight and I try to fix the mash with the Meshtools Plugin

### Add your .zip here ⬇️

[CE3PRO_Merged_model_290.zip](https://github.com/Ultimaker/Cura/files/12526948/CE3PRO_Merged_model_290.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
