### ISSUE TITLE
cura 2.4.0

### ISSUE THREAD

**Issue by jamesjfc123** [Ultimaker/Cura#1666]
I have designed a file in sketchup. When I brought it into Cura everything looked the same. I then checked the layers and it changed my model filling in holes that I did not want to be filled in.

**Comment by fieldOfView** [comment]
> I have designed a file in sketchup.

There's your problem. Sketchup lets you create meshes that are horrible for 3d printing, because Sketchup was not designed for 3d printing.

You can try to turn on/off some of the mesh fixes in Cura, but your best path towards succesfull 3d printing is learning a different modeling application.

**Comment by jamesjfc123** [comment]
Thank you. What software would you suggest I use in place of sketchup.

**Comment by fieldOfView** [comment]
I hear good things about TinkerCAD and Fusion360. Both are free for non-commercial work.

**Comment by jamesjfc123** [comment]
Thank you.

**Comment by fieldOfView** [comment]
If you feel your question has been sufficiently answered, feel free to close the issue (both of them)
