### ISSUE TITLE
wrong treatment when we use the sequence one at a time in special mode

### ISSUE THREAD

**Issue by Robert-AUL** [Ultimaker/Cura#16660]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Alfawise U20

### Reproduction steps

Two parts (STL) on the bed
Using Zoffset plugin with a value of -0,06mm
In special mode settings: sequence once at a time

The problem is that the correction it’s applied for the first STL and not for the second one

See the detailed problem description in the attached pdf  (Plugin Zoffset.pdf)
You will find also the 3mf file (Plugin Zoffset.3mf in the zip file) of this project like this you will have all configuration including the problems reported
[Plugin Zoffset.pdf](https://github.com/Ultimaker/Cura/files/12513819/Plugin.Zoffset.pdf)
[Plugin Zoffset.zip](https://github.com/Ultimaker/Cura/files/12513823/Plugin.Zoffset.zip)

### Actual results

The plugin action it's apply only on the first STL

### Expected results

Each STL file or we can say all first layers of each STL files should be affected by the plugin action as requested by the user 

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/128434597/d5434921-eada-41b5-927a-45cf00daf0b2)
[Plugin Zoffset.zip](https://github.com/Ultimaker/Cura/files/12513868/Plugin.Zoffset.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
With the nozzle at Z0.14 the "G92 Z0.2" line tells the printer to consider the current location as Z0.2.  Every Z location after that G92 is affected and will be adjusted in the printer by -0.06.  There is no need to have any other gcode commands inserted nor is it necessary to change any Z numbers in the file as that one G92 command will stay in effect until the steppers disarm at the end of the print, or a G28 is encountered.
The same is true for the ChangeAtZ plugin in regards to the setting the location of any axis.
In both cases what you see is exactly how it is supposed to work.  When that second ";LAYER:0" is encountered and the gcode tells the nozzle to move to Z0.2 it's going to actually be at Z0.14.  That's what the G92 does.  If the Gcode says to go to Z2.40 it will really be at Z2.34.

@fieldOfView is the author of the plugin and he may wish to address this.  For now I'll remove the bug label.  I hope you understand.
