### ISSUE TITLE
Crash during slicing

### ISSUE THREAD

**Issue by pinkyrelli** [Ultimaker/Cura#16674]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

Anycubic Kobra Neo

### Name abnormal settings

Slice was completed successfully without enabling supports, when I enabled supports it crashed while slicing.

### Describe model location

model is centered on plane. did not try multiple locations or angles

### Describe your model

It sliced successfully the first time using default printing profile from 3d printer manufacturer, then I realized I needed to enable supports, so I enabled supports (Tree, all default options) and then slicing failed.

### Add your .zip here ⬇️

[sonic_onepiece_manifold_crash_save.zip](https://github.com/Ultimaker/Cura/files/12532609/sonic_onepiece_manifold_crash_save.zip)

This is the first time slicing has crashed. I've only been 3d printing for 3 months so I'm not super experienced but I have printed various projects from various sources and Cura has not crashed before.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
