### ISSUE TITLE
Slice failed

### ISSUE THREAD

**Issue by JoshIsEpic** [Ultimaker/Cura#16687]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Ender 3 V2

### Name abnormal settings

M420 S1

### Describe model location

90 degrees

### Describe your model

Ninja trophy for CodeNinjas

### Add your .zip here ⬇️

[CE3E3V2_NinjaTrophyFixedV2.zip](https://github.com/Ultimaker/Cura/files/12553234/CE3E3V2_NinjaTrophyFixedV2.zip)

**Comment by 5axes** [comment]
Windows 10 Cannot reproduce
![image](https://github.com/Ultimaker/Cura/assets/11015345/b35e280d-a057-43b3-ae82-a12c4cc09faf)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
