### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by mikemsd** [Ultimaker/Cura#16688]
### Cura Version

5.4.0

### Operating System

MacOS Ventura on M1 MacBook

### Printer

Ankermake M5 CE

### Describe your model

Slices successfully in AnkerMake Slicer. Yes tried fix with Meshtools with no success

### Add your .zip here ⬇️

[AM5CE_AtlantaLion.3mf.zip](https://github.com/Ultimaker/Cura/files/12554029/AM5CE_AtlantaLion.3mf.zip)

**Comment by 5axes** [comment]
ankermake_m5_ce  printer is not in the standart list of the Cura Printer. Cannot reproduce the issue without this element.  Works fine with a standard printer. 

![image](https://github.com/Ultimaker/Cura/assets/11015345/717957e0-b93b-44f1-846d-665daa68e905)

**Comment by 5axes** [comment]
An other origin ... This model is made with Three mesh 
![image](https://github.com/Ultimaker/Cura/assets/11015345/ccb94151-2434-4bf4-913e-27669d03ba14)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
