### ISSUE TITLE
Slicing Failed - please submit

### ISSUE THREAD

**Issue by inspectionsbybob** [Ultimaker/Cura#16685]
### Cura Version

5.4

### Operating System

Win11

### Printer

JGMaker Artist

### Describe your model

Crown, first attempt after trying to reduce supports

### Add your .zip here ⬇️

[CFFFP_Dragons_Crown.zip](https://github.com/Ultimaker/Cura/files/12549514/CFFFP_Dragons_Crown.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
