### ISSUE TITLE
CE3PRO_2D_Dragon_girl

### ISSUE THREAD

**Issue by TankTak** [Ultimaker/Cura#16696]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Creality Ender 3-Pro

### Name abnormal settings

Raft

### Describe model location

Center

### Describe your model

Dragon with lady

### Add your .zip here ⬇️

[CE3PRO_2D_Dragon_girl.zip](https://github.com/Ultimaker/Cura/files/12559764/CE3PRO_2D_Dragon_girl.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I checked the file using formware.co/OnLineSTLRepair and this is the report.
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> **9 Non-manifold edges (?)**
--> **10 Inverted faces (?)**
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 58623ms ------
-> Vertex count changed from 45153 to 45162 (+9)
-> Triangle count changed from 91294 to 91316 (+22)

So  the model isn't watertight and has some inverted surfaces.  Those errors could be affecting the slice.
I was able to slice the repaired model so I'm going to remove the bug label from this and close it as it appears to be a model problem.

I have a couple of comments regarding your settings.
This would print a lot better with a 0.3 nozzle.  Some of the facial parts are very thin and a 0.4 line width won't allow them to slice.  That brings up my second point.
If you were to print this on a base (like 1mm thick) you could print the main part in a second color and all those little pieces that are barely attached would not break off when you pull this from the build plate.  It's a delicate model and will not bear up under any rough handling.  That means your brim is going to be a permanent part of the print, or you can plan ahead and put it on a plate.

The area around the nose is particularly difficult.  This is with a .4 nozzle at .37 line width.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ec39dc9f-1daa-4d01-b50e-5ea77e863880)
