### ISSUE TITLE
Wire Print does not wait for head to heat up

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#167]
Wireprint gcode seems to use M104 (Set Extruder Temperature), instead of M109 (Set Extruder Temperature and Wait), and so the printer tries to start printing immediately without waiting for the head to heat up.

Note that non-wireprint output from new-Cura contains both M104 and M109 (with the same value). The M104 seems superfluous.

**Comment by fieldOfView** [comment]
Wire Print could also benefit from printing a skirt. Reporting that here because it is both in the startup of the print. Let me know if you prefer a separate issue.

**Comment by BagelOrb** [comment]
Both fixed ^^
Also the end gcode wasn't used.
