### ISSUE TITLE
Speicherung zum Drucken

### ISSUE THREAD

**Issue by effjott** [Ultimaker/Cura#16700]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 2

### Reproduction steps

Hallo,
Keine Endung "gcode" zum speichern z.B. auf Festplatte, nur "stl und obj"
MfG FJHomberg

### Actual results

Hallo,
Keine Endung "gcode" zum speichern z.B. auf Festplatte, nur "stl und obj"
MfG FJHomberg

### Expected results

Hallo,
Keine Endung "gcode" zum speichern z.B. auf Festplatte, nur "stl und obj"
MfG FJHomberg

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/98834861/d25d3172-21c4-45cf-a187-c07b3049febb)

**Comment by GregValiant** [comment]
That looks like the "Export" dialog.  After slicing a model the slice button will change to two buttons "Preview" and "Save to Disk". 
 Use that "Save to Disk" button (far lower right) to save your gcode.
If that worked for you let me know (let me know if it didn't work as well).  Right now it doesn't look like a bug.
![image](https://github.com/Ultimaker/Cura/assets/64202104/41ccfdb6-b17a-4f8d-bac8-9008d2459292)

**Comment by GregValiant** [comment]
Images do not come through via email.  They must be inserted here on the website.

When you go to "Save to Disk" there is no option for " ***.gcode**" and there should be.

@MariMakes of the Cura team will take a look at this.  Whether you use the "Save to Disk" button or the "Export" command there should be an option for "**G-code File (*.gcode)**" but there may be situations where it is not an option, or it could be a bug.

**Comment by effjott** [comment]
Ok, I'll check it out.

Am Di., 19. Sept. 2023 um 16:35 Uhr schrieb GregValiant <
***@***.***>:

**Comment by fieldOfView** [comment]
@effjott posted this elsewhere:

> Dear Greg Valiant
> What I mean is the ending .gcode, which is not intended for file storage, only .stl and .obj if I want to save to hard drive, for example.
> Regards FJHomberg

![269000506-90365ae0-a754-4ae5-b970-e1176e3b84e6](https://github.com/Ultimaker/Cura/assets/143551/bbcce81a-7c39-47c6-bcd0-ff4b624c3cca)
