### ISSUE TITLE
feeder lid v2.3mf

### ISSUE THREAD

**Issue by gr3333** [Ultimaker/Cura#16703]
### Cura Version

5.4.0

### Operating System

Mac OS 13.5 Apple M1 16GB

### Printer

Creality Ender 3 S1 Plus 

### Name abnormal settings

changed to tree supports

### Describe model location

centered - moving off centre slices

### Describe your model

worked recently

### Add your .zip here ⬇️

[feeder lid v2.3mf.zip](https://github.com/Ultimaker/Cura/files/12564624/feeder.lid.v2.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing your file in 5.4.0 and Windows 10.  There are a couple of things you can try.
Move the model around in Cura
Change the initial layer height by a little bit.
Rotate the model in Cura.
I'll mark this as a duplicate bug report as this behavior has been reported many times.  I'm going to go ahead and close this as the Cura team has a lot of examples of this behavior.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/1d889418-4109-4029-beb1-55a1a389b1e6)

With your settings this is about a 31 hour print.  I would suggest you go to normal supports with grid infill at 10%.  You should be able to cut that print time way down.  With my normal settings on my Ender 3 Pro it's a 15 hour print.
