### ISSUE TITLE
Main Body

### ISSUE THREAD

**Issue by roberthay3** [Ultimaker/Cura#16717]
### Cura Version

5.4

### Operating System

Windows 10

### Printer

Ender 2

### Name abnormal settings

no

### Describe model location

model is corner to corner

### Describe your model

yes

### Add your .zip here ⬇️

not sure what you want me to add

**Comment by GregValiant** [comment]
So, what is the problem?
You didn't give is a clue.  No project file, no screenshots, no information at all.
I'm going to close this as it is incomplete and uninformative.
