### ISSUE TITLE
thingverse1

### ISSUE THREAD

**Issue by jkmhb** [Ultimaker/Cura#16720]
### Cura Version

5.4

### Operating System

MX linux

### Printer

ender 5

### Describe model location

centered

### Describe your model

not water tight

### Add your .zip here ⬇️

[cura.zip](https://github.com/Ultimaker/Cura/files/12592180/cura.zip)
![Screenshot 2023-09-12 6 19 12 PM](https://github.com/Ultimaker/Cura/assets/50624053/040fcf47-cd97-4126-96f3-275c9f42e3b3)
[CE5_ender5_bed_calibration_v2.zip](https://github.com/Ultimaker/Cura/files/12592213/CE5_ender5_bed_calibration_v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That's just a bad model.  The "spokes" are only 0.15 wide where they intersect with the center round feature so there is a good portion of each of them that just won't slice.
You would be better off bringing in a cube, scaling it down to 1mm in the Z and putting copies in each corner and at the midpoint of the bed.

Even after repairing it, I couldn't get that model to slice.  I'll mark this as a duplicate and go ahead and close this as that behavior is a well known bug in 5.4.0.  I hope you understand.
