### ISSUE TITLE
tree slicing failed

### ISSUE THREAD

**Issue by ocie** [Ultimaker/Cura#16721]
### Cura Version

5.4.0

### Operating System

Mac OS 13.5.2

### Printer

Creality ender-3 pro

### Name abnormal settings

tree support, scaled model to 1200%

### Describe your model

statue of libert torch downloaded from thingiverse

### Add your .zip here ⬇️

[CE3PRO_torch_3.3mf.zip](https://github.com/Ultimaker/Cura/files/12592704/CE3PRO_torch_3.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This sliced for me so I can't duplicate the problem.

There is a bug in 5.4.0 that can keep models from slicing.  You can try these workarounds.  Maybe one or a combination will allow it to slice.

- Move the model away from the midpoint of the Cura build plate.
- Adjust the Initial Layer Height by a little bit.
- Rotate the model in Cura.

I'll mark this as a duplicate and go ahead and close it as the bug has been reported numerous times.  I hope you understand.
