### ISSUE TITLE
E3_SNW_Enterprise_v1.16-export_(1)

### ISSUE THREAD

**Issue by RetArsonFD** [Ultimaker/Cura#16737]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

unk

### Describe model location

no

### Describe your model

new project..no previous slice, mesh fix does not change anything

### Add your .zip here ⬇️

[E3_SNW_Enterprise_v1.16-export_(1).zip](https://github.com/Ultimaker/Cura/files/12618515/E3_SNW_Enterprise_v1.16-export_.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You have a material "generic_PLA_175" in that project that causes Cura to crash on me, but I can import the model.
I didn't have any trouble slicing it so I'm unable to duplicate the problem.
There is a slicing bug in 5.4.0 that can cause slicing to fail.  The usual workarounds are:

- Move the model on the Cura build plate.
- Rotate the model in Cura
- Change the Initial Layer Height by a little bit ((like from .20 to .23)

Changing the orientation and/or the starting Z height of the slice seems to make a difference.

I'll go ahead and mark this as a duplicate and close this as the Cura team has numerous examples of this behavior.  I hope you understand.

BTW I'm retired out of the Detroit Arson Squad.  Hobbies are better than wandering around burned out crack houses on midnights.

Here is your model sliced in the vertical orientation.  If it was me I'd make it an assembly using something like MS 3D Builder to turn it into 3 or 4 parts and glue them together.  There is very little chance of this actually traveling through outer space so super glue would be fine.
![image](https://github.com/Ultimaker/Cura/assets/64202104/55ccd620-3659-4cc6-b245-06bf12f7e15a)
