### ISSUE TITLE
sliccing fail

### ISSUE THREAD

**Issue by TheGodSkill** [Ultimaker/Cura#16731]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Artillery Sidewinder x1

### Name abnormal settings

does not slice with normal

### Describe model location

no it doesnt slice

### Describe your model

its an jaw for an helmet

### Add your .zip here ⬇️

[HelmetJaw.zip](https://github.com/Ultimaker/Cura/files/12610873/HelmetJaw.zip)

**Comment by GregValiant** [comment]
There doesn't appear to be a model in the 3mf file.  Could you try again?
