### ISSUE TITLE
Slicing Failed on a big model Creality CR-10

### ISSUE THREAD

**Issue by feliS317** [Ultimaker/Cura#16744]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality CR-10

### Name abnormal settings

Tree supports, 8mm retraction distance, 60mm/s retraction retract speed

### Describe your model

It managed to slice with the Y size at 150mm and 250mm, but not at the current 200

### Add your .zip here ⬇️

https://drive.google.com/file/d/1b0p3YDs6Xya8cEUSOclfhRd4hvVJdFHU/view?usp=drive_link

**Comment by GregValiant** [comment]
I don't have "permission" to download the file.  Have you set it up to share?
https://drive.google.com/uc?export=download&id=1b0p3YDs6Xya8cEUSOclfhRd4hvVJdFHU
