### ISSUE TITLE
Bottom layer thickness not affected on extruder 2

### ISSUE THREAD

**Issue by fmgrotepass** [Ultimaker/Cura#16749]
### Cura Version

5.4.0

### Operating System

Linux

### Printer

Ultimaker UM3

### Reproduction steps

Choose a model with hollow core and open top and bottom
Choose extruder 2
Enable Spiralize outer contour
Choose bottom thickness 0
[BearingCovers.stl.zip](https://github.com/Ultimaker/Cura/files/12642338/BearingCovers.stl.zip)
![CorrectBehaviourExtruder1](https://github.com/Ultimaker/Cura/assets/1943221/f11f2fa0-fd6c-4420-a441-c2fdcdf3128a)
![IncorrectBehaviourExtruder2](https://github.com/Ultimaker/Cura/assets/1943221/8555302e-af5d-479f-ad8e-6c5486b951db)

### Actual results

In the preview it is clear that the first layers has the bottom printed. 

### Expected results

The way it behaves with extruder 1 is what is expected. 

### Add your .zip and screenshots here ⬇️

[BearingCovers.stl.zip](https://github.com/Ultimaker/Cura/files/12642354/BearingCovers.stl.zip)
![CorrectBehaviourExtruder1](https://github.com/Ultimaker/Cura/assets/1943221/8951eb37-7519-4607-bdaf-f2975fc958ed)
![IncorrectBehaviourExtruder2](https://github.com/Ultimaker/Cura/assets/1943221/41557d48-7fdd-484b-be3a-0f7d76c81506)

**Comment by GregValiant** [comment]
Thanks for the report.
I can make it have a floor but the floor goes away when I have Ext2 set to all zeros in the Top/Bottom Settings.
The Cura team will take a look.

Here is your model set to Extruder#2 and Spiralize is on.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ec561c44-13ad-4f01-af1f-0eb604ad6527)

**Comment by GregValiant** [comment]
Did you get this to work?

**Comment by GregValiant** [comment]
I'll go ahead and remove the bug label and close this as it appears to be a settings issue.  Let me know if you feel that is premature.
