### ISSUE TITLE
Anycubic Kobra 2 FFF printer support

### ISSUE THREAD

**Issue by motorsep** [Ultimaker/Cura#16740]
### Is your feature request related to a problem?

It seems that using Anycubic Kobra printer setup in Cura 5.4 for Anycubic Kobra 2 doesn't allow to utilize high speed printing capability of Kobra 2 printer.

### Describe the solution you'd like

Please add Anycubic Kobra 2 FFF printer profile to Cura, so that it can be selected during printer setup in Cura and thus provide high speed printing support for Kobra 2 

### Describe alternatives you've considered

There is no solution, except using Anycubic Slicer which is very limited, comparing to Cura.

### Affected users and/or printers

Anycubic Kobra 2 FFF printer

**Comment by GregValiant** [comment]
The printer definition files come from the community or from the manufacturer.  There is no way that Ultimaker can buy one of every printer on the planet and test it and come up with a definition file that works.  That is something that owners and manufacturers need to do.
"ThatGuyZim" has submitted a pull request  #16090  for the Kobra 2 definition.

I'll go ahead and close this as there appears to be a definition in the system and it may be included in the next release of Cura.  I hope you understand.
