### ISSUE TITLE
Slicing this file failed and caused CURA to shut down

### ISSUE THREAD

**Issue by Pridanc** [Ultimaker/Cura#16754]
### Cura Version

5.4.0

### Operating System

Win 10

### Printer

Ender 3 V2

### Name abnormal settings

None that I consider odd.

### Describe model location

Part is square and fills most of the build plate. If I try to slice another similar grid but 5x4 instead of 5x5 it slices fine oriented in any direction

### Describe your model

Slightly smaller model of the same thing slices fine as noted above

### Add your .zip here ⬇️

[GridLite 5x5.zip](https://github.com/Ultimaker/Cura/files/12649314/GridLite.5x5.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing it and the model seems to be error free so I think this involves the slicing bug in 5.4.0.
There are a couple of things that sometimes work to fool the bug.

- Rotate the model in Cura
- Change the Initial Layer Height by a little bit (maybe try it at .35)
- Move the model on the Cura build plate.

I'll mark this as a duplicate (of many previous reports).  I'll close this as well because the Cura team has numerous reports of this behavior.  I hope you understand.

**Comment by GregValiant** [comment]
It just occurred to me that those previous reports didn't include a hard crash so I'll leave this open.

**Comment by Pridanc** [comment]
Thanks Greg.  I'll make the changes you suggest and will report back.
As these are wants and not needs, won't affect my life at all. Talk soon,
PDC

**Comment by Pridanc** [comment]
Greg,
Changing the first layer height to .35 did nothing. Changing it to .22 (random arsed number based on half the normal height of this course print) did nothing.

However, moving the print to **-2mm in the X axis worked.** But not with .35 first layer height.  I Still had to have the .22 first layer height as well.  (I have not run through all heights. Just the two.) 

Moving the print -1mm in the  X  axis did nothing
Moving the print 1, and then 2mm in the X axis did nothing
Moving the print -1, or -2mm in the Y axis did nothing
Moving the print 1, or 2mm in the  Y axis did nothing.

Rotating the print 90deg did nothing.  As there is little room, I did not try to turn it some small amount. Sorry.

Let me know if you want more info as I'm happy to run any iterations.  Remember, I'm retired and only have Bonneville on my plate. 

So to speak....  PDC

**Comment by GregValiant** [comment]
I heard they cancelled it again this year do to the weather?

This slicing bug is a pain.  It rarely happens to me and half the time I can't even duplicate what is happening to other people.  This has to be a tough one to chase down.  There have been some good models that have come through here that 5.4.0 simply refuses slice.

**Comment by Pridanc** [comment]
Greg, even if this is never fixed it doesn't affect me since I have options. Particularly as I'm just having fun in the twilight of my life. 
Bonneville ran but limited time and on shortened tracks.  

Stay well, PDC

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
