### ISSUE TITLE
When you go to "Save to Disk" there is no option for " *.gcode" and there should be.

### ISSUE THREAD

**Issue by effjott** [Ultimaker/Cura#16764]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 2

### Reproduction steps

Dear Greg Valiant
What I mean is the ending .gcode, which is not intended for file storage, only .stl and .obj if I want to save to hard drive, for example.
Regards FJHomberg

### Actual results

Dear Greg Valiant
What I mean is the ending .gcode, which is not intended for file storage, only .stl and .obj if I want to save to hard drive, for example.
Regards FJHomberg

### Expected results

Dear Greg Valiant
What I mean is the ending .gcode, which is not intended for file storage, only .stl and .obj if I want to save to hard drive, for example.
Regards FJHomberg

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/98834861/90365ae0-a754-4ae5-b970-e1176e3b84e6)

**Comment by fieldOfView** [comment]
I will repost this into the issue you meant to post to.
