### ISSUE TITLE
Selecting Build Plate Adhesion Extruder visibility does not add it to the print settings

### ISSUE THREAD

**Issue by GADify** [Ultimaker/Cura#16777]
### Cura Version

5.4.0

### Operating System

MacOS Monteret 12.6.1 AMD Radeon Pro W5700X 16GB

### Printer

Ultimaker S5 Pro

### Reproduction steps

In Print Settings, under Build Plate Adhesion, click the three lines to pull up the preferences visibility window. 
Select Build Plate Adhesion Extruder

### Actual results

Nothing happens

Note that if I deselect Build Plate Adhesion Type then that is immediately removed from Print Settings and I can add it back, but Build Plate Adhesion Extruder will not show. 

### Expected results

Build Plate Adhesion Extruder should show up in Print Settings

### Add your .zip and screenshots here ⬇️

<img width="1856" alt="Screen Shot 2023-09-20 at 1 44 06 PM" src="https://github.com/Ultimaker/Cura/assets/7839569/debd4c91-fa73-457c-a30c-25f9a7d99def">

**Comment by GregValiant** [comment]
Thanks for the report.
Extruder#2 looks to be grayed out as if it was disabled.  That would cause Cura to consider your S5 as a single extruder printer and there won't be options for a second extruder under any of the categories.
With both extruders enabled I can't duplicate this problem.

**Comment by GADify** [comment]
Sorry - totally my fault. Thanks for the quick reply. Spelling errors courtesy of iPhoneOn Sep 20, 2023, at 3:42 PM, GregValiant ***@***.***> wrote:﻿
Thanks for the report.
Extruder#2 looks to be grayed out as if it was disabled.  That would cause Cura to consider your S5 as a single extruder printer and there won't be options for a second extruder under any of the categories.
With both extruders enabled I can't duplicate this problem.

**Comment by GregValiant** [comment]
Not a problem.
I'll go ahead and close this then.
