### ISSUE TITLE
Slicing gets stuck, CPU pegged at 100%; never completes

### ISSUE THREAD

**Issue by john94501** [Ultimaker/Cura#16771]
### Cura Version

5.4.0

### Operating System

Mac OS Ventura 13.3.1

### Printer

Creality Ender 5

### Reproduction steps

1. Import STL file
2. Return settings to defaults
3. Click slice button

### Actual results

Slicing progresses initially and then freezes.

<img width="1029" alt="Screenshot 2023-09-19 at 4 46 25 PM" src="https://github.com/Ultimaker/Cura/assets/76087873/ffef9ec4-35c1-4c63-960c-89150746d233">

### Expected results

Was expecting slicing to complete the way it normally does :)

### Add your .zip and screenshots here ⬇️

[Slicer_Freezes.zip](https://github.com/Ultimaker/Cura/files/12667324/Slicer_Freezes.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Yes, this takes a while to slice in 5.4.0.  Maybe you just didn't wait long enough?

Slicing times for comparison:
- 00:02:30 in 5.4.0
- 00:00:15 in PrusaSlicer
- 00:00:03 in Cura 4.13.1

So it took 50X longer to slice in 5.4.0 than it does in 4.13.1.  This has been noted before in regards to 5.4.0.  Hopefully something will be done about this in the next release.  The Cura team will take a look.

**Comment by john94501** [comment]
Hello Greg,

I waited longer than that, but perhaps my laptop is not as fast as yours.
It was pegged at 100% with fans running full speed for several minutes. In
the end, I played with the number of holes in the mesh until it sliced
faster (a few seconds again once I dropped it to 10 x 7 and removed the
side triangles & diamonds).

Thanks for the quick response,
John...

**Comment by GregValiant** [comment]
When I stood it on one edge it sliced right away.  I do that with some models to see if slicing from a different angle makes any difference.  In this case it was a huge difference.

**Comment by john94501** [comment]
Hello Greg,

I wondered about that but didn't try it because this mesh is actually part
of a larger model (I isolated it as the cause of the slow slicing by
breaking it into pieces) and printing the whole model on one edge might
have been a challenge. I had also considered whether I could make sure the
holes were perfect squares and then rotate by 45 degrees to align them on
the XY axes. The generator for that mesh doesn't have good controls for
ensuring they were perfect squares, so would probably have meant me
manually creating them in the model.  Interesting how the same model at a
different angle can make such a big difference though. Worth remembering if
I have future models that do similar things.

Rgds,
John...

**Comment by GregValiant** [comment]
I don't know the inner workings of Cura, but the three main workarounds for the 5.4.0 slicing bug all have one thing in common, they change the angle that the slicer views the model.  So it appears that Cura's "view" of the model has some relevance to the bug.
That is a good model with no discernable errors and it should slice with no problem.

**Comment by GregValiant** [comment]
@MariMakes and @fieldOfView this is the model with the high slicing time in 5.4.0.

**Comment by GregValiant** [comment]
"Optimize Wall Printing Order" enabled 2:30, disabled 0:15.
