### ISSUE TITLE
Gecko keychain slicing fail

### ISSUE THREAD

**Issue by JustToby22** [Ultimaker/Cura#16783]
### Cura Version

5.4.0 (Flatpak)

### Operating System

Manjaro Linux (CPU:CPU: 11th Gen Intel i5-1135G7 (8) @ 4.200GHz / GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics])

### Printer

Creality Ender-3 v2

### Name abnormal settings

Slicing without supports enabled works. I changed many things, but this one broke it. Tree supports, 59° Overhang angle, touching buildplate.

### Describe model location

Model slices when rotated even 15°, but doesn't when i move it around the buildplate.

### Describe your model

Didn't print yet, but sliced successfully (even while touching buildplate) before I enabled the "generate supports" setting.

### Add your .zip here ⬇️

Attempted to extract my changed settings (based on Super Quality). Hope this helps.
[CE3E3V2_Gecko_Keychain.zip](https://github.com/Ultimaker/Cura/files/12685216/CE3E3V2_Gecko_Keychain.zip)
[settings_gecko.zip](https://github.com/Ultimaker/Cura/files/12685227/settings_gecko.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
You've run into the slicing bug in 5.4.0 and you found one workaround.  Moving it is another and the third is changing the Initial Layer Height by a little bit.  In this case changing the Initial Layer Height to 0.23 allowed the model to slice.

I'll mark this as a duplicate report and go ahead and close this one as the Cura team has a lot of examples of this behavior.
