### ISSUE TITLE
Need dark mode to ease eye strain.

### ISSUE THREAD

**Issue by Chuckling** [Ultimaker/Cura#16792]
### Is your feature request related to a problem?

Related to user discomfort.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Affected users and/or printers

Large bright white screen are had for user to sit in front  of for any period of time.

### Additional information & file uploads

N/A

**Comment by 5axes** [comment]
We already have a dark mode in Cura. **Preferences -> Configure Cura -> Theme** :  
## Ultimaker Dark

![image](https://github.com/Ultimaker/Cura/assets/11015345/df37bf4d-aa33-4a1c-bee5-65bf2fd0b239)


## Ultimaker Darkish 

![image](https://github.com/Ultimaker/Cura/assets/11015345/1a0c604d-1cbd-4297-9ac8-3a8e3a468b24)


##or 
![image](https://github.com/Ultimaker/Cura/assets/11015345/98ad33f9-4f0d-43eb-a121-bec06abd0f13)

**Comment by GregValiant** [comment]
@Chuckling  - Did you find the setting?
