### ISSUE TITLE
Ender-3 v3 SE Profile missing

### ISSUE THREAD

**Issue by ProTechEx** [Ultimaker/Cura#16795]
### Is your feature request related to a problem?

Unfortunately cannot work with Cura because Ender-3 v3 SE Profile is missing

### Describe the solution you'd like

Adding Ender-3 v3 SE Profile

### Describe alternatives you've considered

I've try to a add Ender-3 v2 Profile, but I notice that the Printer Setting are different in comparison.

### Affected users and/or printers

Creality Ender-3 v3 SE

**Comment by andytimofeev** [comment]
Thank you for adding this feature request - also looking how to solve the problem with printing settings for Ender 3 V3 SE

**Comment by eborchardt** [comment]
I'd also like to see a profile for the Ender 3 v3 SE.

**Comment by evanlloydjohns** [comment]
I also hoping to see an Ender 3 V3 SE profile in Cura

**Comment by marcvandecoevering** [comment]
yes, please!! :)

**Comment by Murat0773** [comment]
please..

**Comment by saumyaj3** [comment]
Hi! These changes will be available in the CURA version after 5.5. 
If you still wish to use the machine please follow the comment: https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700

**Comment by WilliamSC65** [comment]
> Hi! These changes will be available in the CURA version after 5.5. If you still wish to use the machine please follow the comment: [#16796 (comment)](https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700)

Vraiment dommage que la dernière version (5.5) de Cura n'ai pas intégré le profil Ender 3 V3 SE 👎

**Comment by joostvhts** [comment]
> > Hi! These changes will be available in the CURA version after 5.5. If you still wish to use the machine please follow the comment: [#16796 (comment)](https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700)
> 
> Vraiment dommage que la dernière version (5.5) de Cura n'ai pas intégré le profil Ender 3 V3 SE 👎 
> 
> 

Zoals je hier kunt lezen is er een manier om de profielen alsnog nu al te gebruiken 🙃

**Comment by WilliamSC65** [comment]
> > > Hi! These changes will be available in the CURA version after 5.5. If you still wish to use the machine please follow the comment: [#16796 (comment)](https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700)
> > 
> > 
> > Vraiment dommage que la dernière version (5.5) de Cura n'ai pas intégré le profil Ender 3 V3 SE 👎
> 
> Zoals je hier kunt lezen is er een manier om de profielen alsnog nu al te gebruiken 🙃

Oui je l'ai installé dans Cura 5.4.0 et cela fonctionne parfaitement 👍

**Comment by joostvhts** [comment]
> > > > Hi! These changes will be available in the CURA version after 5.5. If you still wish to use the machine please follow the comment: [#16796 (comment)](https://github.com/Ultimaker/Cura/pull/16796#issuecomment-1748634700)
> > > 
> > > 
> > > Vraiment dommage que la dernière version (5.5) de Cura n'ai pas intégré le profil Ender 3 V3 SE 👎
> > 
> > 
> > Zoals je hier kunt lezen is er een manier om de profielen alsnog nu al te gebruiken 🙃
> 
> Oui je l'ai installé dans Cura 5.4.0 et cela fonctionne parfaitement 👍

Lekker gewerkt pikkestein en wat fijn dat we elkaars taal spreken dan hebben we die ene niet nodig die iederéén kan 🙃

**Comment by jsleroy** [comment]
Had a try at the profile for my V3 SE.
This works well but there's stringing I can't get rid off.
I'm using a V2 Neo with no issues at all.
So probably this profile needs some refinement (working on it but no success yet).
In case, find attached the profile extracted from Cura slicer.

[v3se.cxprinter.txt](https://github.com/Ultimaker/Cura/files/13195501/v3se.cxprinter.txt)
