### ISSUE TITLE
Slicing Failed on stl import via drag and drop

### ISSUE THREAD

**Issue by anarchopossum** [Ultimaker/Cura#16803]
### Cura Version

5.4.0

### Operating System

Mac OS Ventura 13.2.1

### Printer

Ender 3 Pro

### Name abnormal settings

Standard Quality (No modifications)

### Describe model location

Center

### Describe your model

grinder Wheel

### Add your .zip here ⬇️

Here is the link to the item in question via the [printable site](https://www.printables.com/model/287425-grinder)
I placed `Grinding wheel finer.stl` into Cura by dragging and dropping it. 

Also Here is the STL just remove the .txt label
[Grinding wheel finer.stl.txt](https://github.com/Ultimaker/Cura/files/12707996/Grinding.wheel.finer.stl.txt)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the model.
Try:

- Move the model away from the midpoint of the Cura build plate.
- Try rotating the model in Cura.
- Change the "Initial Layer Height" by a little bit.

Let us know if any of those work for you.
I'll mark this as a duplicate as this behavior has been reported many times.   I'll go ahead and close it as the team has numerous examples of this behavior.  I hope you understand.
