### ISSUE TITLE
bug pour l'ajout de nouvelle imprimante 3D

### ISSUE THREAD

**Issue by ggillian** [Ultimaker/Cura#16818]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3pro

### Reproduction steps

j ai ajouté un profil custom fff en plus de mon Ender 3 pro

### Actual results

je ne peut plus ajouter d autres imprimantes que les précédentes 

### Expected results

impossibilité de rajouter de nouvelle imprimantes 

### Add your .zip and screenshots here ⬇️

<img width="406" alt="image" src="https://github.com/Ultimaker/Cura/assets/90850404/55ec414e-409f-4bf4-812f-0aed31796264">

**Comment by GregValiant** [comment]
Thanks for the report.
Go to the MarketPlace and see if you have the "StartUp Optimizer" plugin installed.  One of it's tricks to speeding up Cura loading is to keep a lot of printers from loading which makes them inaccessible.
Let us know if that was it.
