### ISSUE TITLE
failed STL slicing cura 5.4

### ISSUE THREAD

**Issue by Neo-bud** [Ultimaker/Cura#16827]
### Cura Version

5.4

### Operating System

Windows 10

### Printer

Monoprice Ultimate 2

### Name abnormal settings

changed to extra fine

### Describe model location

center

### Describe your model

just a flat panel

### Add your .zip here ⬇️

[MU_Toppanel1.zip](https://github.com/Ultimaker/Cura/files/12731259/MU_Toppanel1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There doesn't appear to be anything wrong with the model.
Cura 5.4.0 has a bug that can keep models from slicing.  There are three workarounds.

- Move the model in Cura.
- Rotate the model.
- Change the Initial Layer Height by a little but.

I'll mark this as a duplicate and go ahead and close this.  This bug has been reported numerous times.  I hop you understand.

That's a lot of brim.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7fb1d5ad-9693-425b-8925-8344d6bdeee0)
