### ISSUE TITLE
Ender 3D pro freeze

### ISSUE THREAD

**Issue by 111VooDoo** [Ultimaker/Cura#16849]
### Cura Version

5.4.0

### Operating System

Windows 10 Pro

### Printer

Creality Ender 3D Pro

### Reproduction steps

I have started the printed and connected to my PC
Opened cura and imported 3d model
Before printing, i checked x,y,z axis to see if they work properly, and they all did
Preheated bed and nozzle and pressed print to usb

### Actual results

When nozzle reached the bed, it FREEZES in place, in the corner
No movement whatsoever
I tried new models from the start but got the same result, it freezes and wont move

### Expected results

I expected to see as usual, when the nozzle reaches the bed, it goes x axis in one and another direction for test print before going to print the actual model

### Add your .zip and screenshots here ⬇️

I do know what happened and i cannot find anything similar on the internet
Please help i freaked out

**Comment by GregValiant** [comment]
Use the "File | Save Project" command in Cura.  Then zip the 3mf file and post the zip folder here.  There is no way to tell without seeing what the printer is reading.

This sounds like a problem with either the printer or the StartUp Gcode.  Both of those are provided by Creality.
