### ISSUE TITLE
Rose

### ISSUE THREAD

**Issue by JaneBelousova** [Ultimaker/Cura#16854]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Flying bear ghost 6

### Describe your model

Can't slice because of unexpected error

### Add your .zip here ⬇️

[CFFFP_rose.zip](https://github.com/Ultimaker/Cura/files/12775373/CFFFP_rose.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I had to rotate it 90° CCW and then it sliced.

I'll mark this as a duplicate as this bug has been reported numerous times.  I'll go ahead and close it as the Cura team has plenty of examples of this behavior.  I hope you understand.

**Comment by JaneBelousova** [comment]
Slice become successfull after rotating around Z axis. But it depends on the angle: in some cases the model couldn't be sliced.

**Comment by JaneBelousova** [comment]
> Thanks for the report. I had to rotate it 90° CCW and then it sliced.
> 
> I'll mark this as a duplicate as this bug has been reported numerous times. I'll go ahead and close it as the Cura team has plenty of examples of this behavior. I hope you understand. ![image](https://user-images.githubusercontent.com/64202104/271797990-f2ed0d7f-44e6-45f9-ac97-8192ccb72bb5.png)

Thanks for reply and help!
