### ISSUE TITLE
Slicing error when scaling down

### ISSUE THREAD

**Issue by Mandalorian23** [Ultimaker/Cura#16874]
### Cura Version

5.4.0

### Operating System

macOS Ventura 13.5.1

### Printer

Sidewinder X1 (using Sidewinder X2)

### Describe your model

Slicing is possible at 100% Scale. I'm scaling down to 96% and getting the error

### Add your .zip here ⬇️

[ASX2_Rose_Bear.3mf.zip](https://github.com/Ultimaker/Cura/files/12793549/ASX2_Rose_Bear.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I moved it, and then I rotated it, but it didn't slice until I changed the Initial Layer Height to 0.23.
I'll mark this as a duplicate and go ahead and close it as it appears to be the slicing bug that has been reported numerous times.  I hope you understand.
