### ISSUE TITLE
Slicing fail

### ISSUE THREAD

**Issue by l-dunbar** [Ultimaker/Cura#16878]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Ender 3

### Describe model location

its slices when on 90 increments or any angle when not scaled up to 170%

### Describe your model

works on smaller scale, once scaled up and angled at a 45degree it looses its mind

### Add your .zip here ⬇️

[Ducati Panigale V4S 2019.zip](https://github.com/Ultimaker/Cura/files/12795965/Ducati.Panigale.V4S.2019.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Go to the Cura Marketplace and load the "Mesh Tools" plugin.  It checks models for errors when you load them.
You would see this:
![image](https://github.com/Ultimaker/Cura/assets/64202104/bd882d06-403b-4519-baf8-2e5574543e73)

The polka-dot surfaces are errors in the model.  That's the reason why this won't slice.
I'm going to remove the bug label from this and close it.  I hope you understand.

After repairing the model it sliced with no problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a5142356-2af7-44fc-a7d8-ec581a0f8c35)
