### ISSUE TITLE
File Open Dialog no longer allows you to multi-select files for opening.

### ISSUE THREAD

**Issue by thantik** [Ultimaker/Cura#16875]
### Cura Version

5.4.1

### Operating System

Windows 10

### Printer

All of them.

### Reproduction steps

1. Click the file open dialog in Cura.
2. Browse to a directory with multiple STL files
3. Click a file, hold shift/ctrl, click on another STL file.

### Actual results

Ctrl/Shift do not allow selecting multiple files.  Only 1 file is allowed to be selected at a time.

### Expected results

Multiple files should be allowed to be opened at once.  If you use the Click+Drag with multiple files selected from the Explorer window, multiple STLs will open at once using this as a workaround.  Versions 5.3 and below allow multiple-file selection, so this seems to be a regression.

### Add your .zip and screenshots here ⬇️

Screenshots are unable to 'show' the issue at hand.  Not needed.

**Comment by GregValiant** [comment]
Thanks for the report.
This is easy to duplicate and it has been reported several times.
As a workaround you can drag multiple files from File Explorer (but not from the File Open dialog box).

I'll tag this as a duplicate report and go ahead and close it as the Cura team is aware of this one.  I hope you understand.
