### ISSUE TITLE
Kettenhemd

### ISSUE THREAD

**Issue by qugu57** [Ultimaker/Cura#16885]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Any Cubic i3 Mega

### Describe model location

No

### Describe your model

I created some interlocking rings with tinkerCAD

### Add your .zip here ⬇️

[Downloads.zip](https://github.com/Ultimaker/Cura/files/12804120/Downloads.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This appears to be a duplicate of hte standard slicing bug in 5.4.0.  After rotating and moving the model in Cura it sliced.  Sometimes altering the Initial Layer Height by a little bit will fool the bug as well.
I'll mark this as a duplicate and go ahead and close this report.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5b26df85-5934-43f6-964e-d2dbdf900d74)
