### ISSUE TITLE
Mjolnir Mk6 Helmet single print.

### ISSUE THREAD

**Issue by ProximalAlpha** [Ultimaker/Cura#16881]
### Cura Version

5.4.0

### Operating System

Win11

### Printer

Anycubic Chiron 0.6mm

### Name abnormal settings

Using Trees support instead of standard pillars

### Describe model location

Sliced when I used 0.6mm layers with a 0.4mm nozzle

### Describe your model

yes, 2 years ago with the same file just older Cura Version

### Add your .zip here ⬇️

[AC_1.17 triangles at 50percent.3mf.zip](https://github.com/Ultimaker/Cura/files/12798904/AC_1.17.triangles.at.50percent.3mf.zip)

This model was sized to be 182.+ mm between the ears at the neck.  It is tipped at approximately 68 degrees to fit in the build area.
The model is currently oriented at 45 degrees off-center and won't slice.  I got the file to slice at 0 degrees off-center with trees at 0.6mm layers with a 0.4mm nozzle.  [post processing won't be pretty... model thinks it is watertight, but reality says differently]

'why not just cut it into smaller pieces?'
"Because I know it will print in one solid piece on a Chiron, I've done it before. That's one of the only reasons I bought a Chiron."

**Comment by Roasas** [comment]
the models too big for the plate my g

**Comment by ProximalAlpha** [comment]
> the models too big for the plate my g

I don't know why it sliced this then. These photos are from a 0.4 nozzle at 0.6 layers (I forgot to change nozzle size in printer profile) this was taken at approx 7:10pm central (-5gmt)

![PXL_20231005_000657669](https://github.com/Ultimaker/Cura/assets/146906855/e304f2fa-655d-417f-8390-4e71a9a53563)
![PXL_20231005_000707531](https://github.com/Ultimaker/Cura/assets/146906855/83d090a0-9038-45e2-9763-02b45d4516bd)

This is the same model with 1.5mil+ tris.
