### ISSUE TITLE
I can't slice any models i try to slice

### ISSUE THREAD

**Issue by Oneill67** [Ultimaker/Cura#16905]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

Ender3 V2

### Name abnormal settings

No change since the last time

### Describe model location

I have the issue with all models i tried to slice

### Describe your model

Yes, It's a models i've downloaded from Thingiverse

### Add your .zip here ⬇️

[CE3E3V2_Stand_v2.zip](https://github.com/Ultimaker/Cura/files/12837437/CE3E3V2_Stand_v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the project.
Are you sure you provided the project file with the settings you want to use and the model in the orientation you want to print it in?
It will fail with your current setup.
![image](https://github.com/Ultimaker/Cura/assets/64202104/992d1ff5-3cc9-4e92-9935-5b7cc2f97291)

**Comment by Oneill67** [comment]
I've found the solution, it's the Antivirus software Avast. I stoped the protection and I can slice the project.
To resolve the problem, add an exception Files/Directory in to Avast on the "C:\Program Files\UltiMaker Cura 5.4.0\*".
![image](https://github.com/Ultimaker/Cura/assets/68613444/11dc9249-548c-4bce-9af3-2c2abe98d842)

**Comment by GregValiant** [comment]
It appears that it wasn't a Cura problem.  Can we go ahead and close this?

**Comment by Oneill67** [comment]
Yes you can close the issue

**Comment by Oneill67** [comment]
Yes, it can be closed
