### ISSUE TITLE
Trouble with custom filament profiles

### ISSUE THREAD

**Issue by Matej111** [Ultimaker/Cura#1690]
I created a filament profile. (1.75 mm, abs, 255/100 degrees,green colour, custom manufacturer)
THe profile was not shown in the material list, and disappeared upon reload. I created it again and exported it. Disappeared on reload, the exported file does nothig but says"succesfully imported". Also, it is not posible to set filament cost, weight, length and cost per meter.

**Comment by fieldOfView** [comment]
Please try again with the 2nd beta of Cura 2.5.0

**Comment by Matej111** [comment]
Thank you, it worked.
