### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by Nutschi** [Ultimaker/Cura#16918]
### Cura Version

5.4.0

### Operating System

W11

### Printer

Sidewinder X1

### Name abnormal settings

Size 150%

### Describe your model

Size 100% is O.K

### Add your .zip here ⬇️

[error.ZIP](https://github.com/Ultimaker/Cura/files/12846263/error.ZIP)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug in 5.4 that can keep models from slicing.  I rotated that model and it still wouldn't slice.  Changing the Initial Layer Height fooled the bug and it sliced.  Sometimes just moving the model to a different place in Cura will allow it to slice.
I'll mark this as a duplicate and go ahead and close this as it is a well known bug.

That's a tough print with no support.
![image](https://github.com/Ultimaker/Cura/assets/64202104/05d8590e-213a-434b-9260-553ccea4d6c4)
