### ISSUE TITLE
Cura merges meshes when slicing

### ISSUE THREAD

**Issue by astramateria** [Ultimaker/Cura#16915]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Prusa i3 MK3S+ w/ .4mm nozzle

### Name abnormal settings

Horizontal Expanion (All)

### Describe model location

Center

### Describe your model

Simple tolerance test

### Add your .zip here ⬇️

[tolerance test crash.zip](https://github.com/Ultimaker/Cura/files/12842541/tolerance.test.crash.zip)

Issue: When I slice this tolerance test with the default "Draft .2mm" profile, the STL is sliced perfectly; there are gaps between the tolerance test parts. However, when I slice it with my custom profile (based off the aforementioned default file), Cura merges the mesh so that it prints as one whole piece instead of 2 pieces for the tolerance test. 

Cura crashes when I use my custom profile and remove any horizontal expansion settings. I tried replicating this issue in 5.3.1 and it does not crash.

**Comment by GregValiant** [comment]
Thanks for the report.
When I open your project file it won't slice.  I changed the "Initial Layer Height" to 0.23 and it sliced.

This sounds like the standard 5.4.0 slicing bug.  Moving the model and/or rotating the model in Cura are also known workarounds.
I'll mark this as a duplicate and go ahead and close this report as the Cura team is aware of this problem.  I hope you understand.
BTW all horizontal expansion is turned off in the project file and the preview looks good.  This should print as you would expect.
![image](https://github.com/Ultimaker/Cura/assets/64202104/174078f5-f9c5-45ba-9fb2-b06b040206b2)
