### ISSUE TITLE
AE10_zen_soap_1 FAIL SILICING

### ISSUE THREAD

**Issue by Mike7Gtz** [Ultimaker/Cura#16924]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anet E10

### Describe your model

its a mold to do soap

### Add your .zip here ⬇️

[AE10_zen_soap_1.zip](https://github.com/Ultimaker/Cura/files/12850881/AE10_zen_soap_1.zip)
![image](https://github.com/Ultimaker/Cura/assets/95316094/02a61755-66c4-4590-8639-3cf7c4742dad)

**Comment by GregValiant** [comment]
Thanks for the report.
It wouldn't slice for me until I rotated the model and then changed the Initial Layer Height to 0.23.

I'll mark this as a duplicate and close this report as this has been reported numerous times.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/47deffbe-ea22-4ef5-a66c-cdcefd829bd4)
