### ISSUE TITLE
Slicing Fehlgeschlagen 

### ISSUE THREAD

**Issue by WhyNotYet1** [Ultimaker/Cura#16939]
### Cura Version

5.4

### Operating System

10

### Printer

Ender 3 Pro

### Describe your model

Unicon

### Add your .zip here ⬇️

[test.zip](https://github.com/Ultimaker/Cura/files/12868451/test.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
