### ISSUE TITLE
House that just won't slice it

### ISSUE THREAD

**Issue by Puciek** [Ultimaker/Cura#16930]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Neptune 3 pro

### Describe your model

A ruined house

### Add your .zip here ⬇️

[EN4_RuinedChateau-Lv1-v1.1.zip](https://github.com/Ultimaker/Cura/files/12860218/EN4_RuinedChateau-Lv1-v1.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug in 5.4.0 that can keep models from slicing.  I don't have a Elegoo 4 definition so I used a Elegoo 3.  When I changed the Initial Layer Height to 0.23 the model sliced.  You can also try moving and/or rotating the model in Cura.
It seems like models of buildings with either stone or warped wood floors really bring out this bug.  
I'll mark this as a duplicate report and go ahead and close it as there have been many reports of this happening and the Cura team is working on it.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/9d6b9bd8-f51f-4a99-830d-c81a21087e11)
