### ISSUE TITLE
Size of Appimage in Beta 5.5

### ISSUE THREAD

**Issue by chipmunk1977** [Ultimaker/Cura#16931]
### Cura Version

Beta 5.5

### Operating System

Linux Ubuntu

### Printer

N/A

### Reproduction steps

On downloading the Beta release, I noticed that the size of the file has jumped by over 100 megabytes. Even for combining the the two Linux versions, this seems excessive.

### Actual results

The file is extremely large.

### Expected results

A file size closer to the previous versions.

### Add your .zip and screenshots here ⬇️

N/A

**Comment by MariMakes** [comment]
Hey @chipmunk1977,

Thanks for your report 👍

I brought your issue up with the developers, and they mentioned that they might know what caused it and they proposed a fix. 
https://github.com/Ultimaker/Cura/pull/16943

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-11146
