### ISSUE TITLE
5.5 Beta Crash - AttributeError - Nonetype Object has no atribute in 'extruderList'

### ISSUE THREAD

**Issue by MikeOxawopper** [Ultimaker/Cura#16941]
### Cura Version

5.5

### Operating System

windows 10

### Printer

ender 3 v2

### Reproduction steps

1. install software
2. open software

### Actual results

CRASH
![5 5 beta 1st run](https://github.com/Ultimaker/Cura/assets/65547160/159a0024-bc3f-41c1-8986-af346151e958)

### Expected results

Be nice if it at least opened

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12869219/cura.log)

**Comment by lonlonranchdressing** [comment]
Just chiming in, Same issue. Any workarounds?

**Comment by MikeOxawopper** [comment]
I bodged my way around it.
i hit the regenerate and backup button at the bottom

then opened 5.4 and 5.5 folders side by side by using the show folder option within 5.4 help menu.

i then opened each folder in turn in 5.4 copied the data within the folders to the matching folder in 5.5

you have to create a new printer but once in i just deleted that

**Comment by MariMakes** [comment]
@5axes, I believe this is the issue [you've reported in the UltiMaker Community](https://community.ultimaker.com/topic/44294-ultimaker-cura-55-beta-released/?do=findComment&comment=326232).

Do you agree?

**Comment by 5axes** [comment]
> @5axes, I believe this is the issue [you've reported in the UltiMaker Community](https://community.ultimaker.com/topic/44294-ultimaker-cura-55-beta-released/?do=findComment&comment=326232).
> 
> Do you agree?

Yes exactly. Temporary workaround : delete the gradualflow Plugin ( un the folder share/cura/plugins)

**Comment by jellespijker** [comment]
Instead of deleting thebplugin you could also replace this file https://github.com/Ultimaker/CuraEngine_plugin_gradual_flow/blob/main/CuraEngineGradualFlow/GradualFlowPlugin.py 

It contains a fix such that Cura doesn't crash

**Comment by 5axes** [comment]
Ok issue solved with the [GradualFlowPlugin.py](https://github.com/Ultimaker/CuraEngine_plugin_gradual_flow/blob/main/CuraEngineGradualFlow/GradualFlowPlugin.py) modification.

**Comment by MariMakes** [comment]
To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. I'll be closing this issue.
Rhanks again, and please let us know if you run into any other issues 💪
