### ISSUE TITLE
Slicing Failed while attempting to slice Pumpkin

### ISSUE THREAD

**Issue by llamboladd** [Ultimaker/Cura#16948]
### Cura Version

5.4.0

### Operating System

Windows 10, RTX 2080 Ti, i9 9900k

### Printer

Tenlog TL-D3 Pro (Custom FFF Printer)

### Name abnormal settings

0.3mm layer height.

### Describe model location

Seems to be an issue with the model; changing orientation doesn't help.

### Describe your model

A pumpkin split in half.  Downloaded form here: https://www.thingiverse.com/thing:6238747

### Add your .zip here ⬇️

[CFFFP_Pumpkin_Front.zip](https://github.com/Ultimaker/Cura/files/12873394/CFFFP_Pumpkin_Front.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
