### ISSUE TITLE
Slicing Error with Skull Pot

### ISSUE THREAD

**Issue by rattenbo** [Ultimaker/Cura#16946]
### Cura Version

5.4.0

### Operating System

Windows 10 V22H2

### Printer

Ender 3 v2

### Name abnormal settings

Chuck Hellybrucks FFV5.3 Extra Fast Profile

### Describe model location

Location was default. When I rotated 45 deg it sliced properly

### Describe your model

I have sliced it before, but it was on an angle. 

### Add your .zip here ⬇️

[CE2_Scull_geant_pot_-_Copy.zip](https://github.com/Ultimaker/Cura/files/12871497/CE2_Scull_geant_pot_-_Copy.zip)

Sliced previously. Reloaded from start to re-locate supports to better locations. STL Loaded facing front. I added supports and went to slice. It failed twice. Based on this form, I rotated by 45 Degrees and re-sliced and that worked.  Rotated back, re-sliced and it failed again.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
