### ISSUE TITLE
5.5.0 Beta won't slice model

### ISSUE THREAD

**Issue by alavabeer** [Ultimaker/Cura#16951]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Artillery Genius

### Reproduction steps

1. Downloaded model - https://www.thingiverse.com/thing:3251366
2. Sliced it in Cura 5.0.0, worked perfectly
3. Opened Cura 5.5.0, failed to slice

### Actual results

Error message - Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.

### Expected results

Model should have sliced ready for print.

### Add your .zip and screenshots here ⬇️

[AG_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/12874480/AG_Christmas_Village.zip)
![christmas village pre slice](https://github.com/Ultimaker/Cura/assets/10846897/f4b9c17d-8366-4a82-9c21-905d507d3263)
![christmas village post slice](https://github.com/Ultimaker/Cura/assets/10846897/7785b2c8-287d-474c-af82-004b8e62d4d2)

**Comment by GregValiant** [comment]
Thanks for the report.
That model has shown up here in a previous bug report.
It would not slice for me "as recevied".  I rotated the model 90° CCW and it sliced.
@MariMakes of the Cura team will take a look.

Your line width and layer height are keeping a lot of fine details (and a couple of roofs) from printing.
It would be a shame to get this far and have one of the last things fail.
This really needs to be printed with a 0.3 nozzle and line width.
This is at 0.20 layer height and a 0.35 line width.  That's about as far down as you can go with a 0.4 nozzle.  As you can see the roof of the topmost building won't slice and the spire would fail.
![image](https://github.com/Ultimaker/Cura/assets/64202104/40537d39-9969-4475-acd1-53640bf6392f)

This is with a 0.3 nozzle and line width.  The print time is up to 35 hours though.
![image](https://github.com/Ultimaker/Cura/assets/64202104/85cbf487-e87f-4f07-99ef-9f4f9d2b4af7)

**Comment by KarinaLaursen** [comment]
I just want to add, i have been trying to slice this file also, no luck, i tried the same settings as on the photo and tried to rotate 90 degrees :(

**Comment by GregValiant** [comment]
@KarinaLaursen if you install 4.13.1 it will slice this.  The page is [HERE](https://github.com/Ultimaker/Cura/releases?page=2).  Scroll down to 4.13.1 and click on the "Assets" link.
If you want to stick with the Arachne versions of Cura then 5.2.2 will slice this.
You don't have to un-install a version to install another version.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
