### ISSUE TITLE
Support Blocker Overlap Infill - Starting <100% works, but trying to reduce from 100% does not

### ISSUE THREAD

**Issue by gannon145** [Ultimaker/Cura#16964]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender-3

### Reproduction steps

**For main part with infil set at 100%**

1. Add print part
2. Set infill to 100%
3. Add support blocker and move to area of change
4. Change support blocker to "Modify settings for Overlap"
5. Add "Infill Density" and change to a desired value lets say 50%

**For main part set at less than 100%**

1. Add print part
2. Set infill to anything except 100% --- 75% in this case
3. Add support blocker and move to area of change
4. Change support blocker to "Modify settings for Overlap"
5. Add "Infill Density" and change to a desired value lets say 50%

### Actual results

**For main part with infil set at 100%**
Whole part stays at 100% infill including the overlap which should be 50%

**For main part set at less than 100%**
Main part is 75% infill and overlap is 50% infill -- as expected

### Expected results

**For main part with infil set at 100%**
Main part stays at 100% infill except overlap which should be at 50%

**For main part set at less than 100%**
Main part is 75% infill and overlap is 50% infill

### Add your .zip and screenshots here ⬇️

[Cura Overlap Bug.zip](https://github.com/Ultimaker/Cura/files/12884792/Cura.Overlap.Bug.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Screenshots are helpful to visualize, but to investigate we need a project file ("File | Save Project").
This looks to be working correctly for me.  The model is at 100% zigzag at 0° and the Infill Mesh block is 7% grid with a 3 infill line multiplier at 45°.
![image](https://github.com/Ultimaker/Cura/assets/64202104/86b6aff1-0f90-41b5-947a-7bafa6d95551)

**Comment by gannon145** [comment]
[CE3E3V2_8se mini vixen accessory plate.zip](https://github.com/Ultimaker/Cura/files/12889020/CE3E3V2_8se.mini.vixen.accessory.plate.zip)

Priject file added

**Comment by GregValiant** [comment]
@MariMakes,
This isn't the first time but I can't open this 3mf file without Cura 5.4 or 5.5 crashing.  It seems to be related to the material "generic_PLA_175".

**Comment by GregValiant** [comment]
I can duplicate this behavior from 5.5 back into 4.13.1.
The Cura team will take a look.
At some point "100%" infill was changed so the pattern would switch to "lines" to avoid path conflicts that would occur with some other patterns at that density.  With the density set to 99.9% the problem goes away.

**Comment by MariMakes** [comment]
Hi! 👋 

I see indeed that the mesh seems to be ignored, unless the infill density is something different than 100%
![image](https://github.com/Ultimaker/Cura/assets/40423138/7c4faada-0592-4311-9217-42f262997264)

I'll bring it up to the team to see what they can do to improve it. 
But I expect that if it's not a quick fix that it will not get a high priority to implement. 
Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hi!

I showed your issue to the team, and they were able to show me why your issue isn't the case for UltiMaker printers.
In most printers 100% infill often means 0 toplayers and 99999 bottom ones. 
That is why the lines look yellow for the skin instead of orange for the infill.

If you bring these values to a more reasonable 2 layers, you can see that the bug is gone:
![ezgif-4-8e38165c20](https://github.com/Ultimaker/Cura/assets/40423138/6c9a63da-426b-43eb-bd13-fcd4231f1f87)

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
