### ISSUE TITLE
Crash1

### ISSUE THREAD

**Issue by zerquetch** [Ultimaker/Cura#16967]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

K1Max

### Describe model location

center

### Describe your model

Holder for measuring tape. NOT watertight...ever

### Add your .zip here ⬇️

[CFFFP_TapeHolder_V2_FailedSlice.zip](https://github.com/Ultimaker/Cura/files/12887280/CFFFP_TapeHolder_V2_FailedSlice.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
