### ISSUE TITLE
Multiple articulating parts on the build plate failed. 

### ISSUE THREAD

**Issue by 801Wighty** [Ultimaker/Cura#16970]
### Cura Version

5.5.0-beta.1-macos-X64

### Operating System

MacOS Ventura 13.4

### Printer

SOVOL SV06Plus

### Name abnormal settings

NA

### Describe model location

No

### Describe your model

3 each, Articulating Dragon

### Add your .zip here ⬇️

[3-Small-Dragons.3mf.zip](https://github.com/Ultimaker/Cura/files/12887827/3-Small-Dragons.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
