### ISSUE TITLE
Unable to open File, The File could be corrupt, inaccessible or it did not contain any models

### ISSUE THREAD

**Issue by ZigeunerBro** [Ultimaker/Cura#16987]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Kobra Plus / Ender 3 S1 Pro

### Reproduction steps

I tried to print a STL file at the following site: https://wiki.openastrotech.com/OpenAstroTracker/Addons/AutoPA

The files are available on github: https://github.com/OpenAstroTech/OpenAstroTracker-Addons/tree/master/AutoPA/STL/V2.0

Every time I try to open one of these files, nothing happened. only an error msg occur an says "Unable to open File, The File could be corrupt, inaccessible or it did not contain any models"

I tried different versions of cura and in version 4.4 (i believe), i could open one of the files. After that I was able to open this STL in 5.4.0 without issues.
But the rest are still gives me that error msg

### Actual results

Error Msg:
"Unable to open File, The File could be corrupt, inaccessible or it did not contain any models"

### Expected results

just open the file

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/12908174/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I downloaded the "13_rear_AltAz_mount_6801.stl" file and didn't have any trouble.  I have had that error message come up when I try to load a 3mf Project File and the model is missing.  I've never seen it with an STL file.
Is it possible that your anti-virus or firewall is having an effect on the download?
![image](https://github.com/Ultimaker/Cura/assets/64202104/b2a4d82f-ed79-4bfa-980d-404f6fbdacaf)

**Comment by ZigeunerBro** [comment]
Thx for your help.

![Screenshot 2023-10-15 10 10 08](https://github.com/Ultimaker/Cura/assets/147935391/5d681b01-751a-4f65-9911-10b74b968702)
![Screenshot 2023-10-15 10 10 16](https://github.com/Ultimaker/Cura/assets/147935391/88d1b39b-9d8f-4bde-a285-8f45acb6e54f)

I found the issue.

I downloaded the files via right click/save as... in the file overview section. And that seems to be the problem.


If i click on the file and use the download button, everything is fine.

**Comment by GregValiant** [comment]
I'll go ahead and close this as solved.
