### ISSUE TITLE
Slicing dual color print using Mizar M profile

### ISSUE THREAD

**Issue by buddybu** [Ultimaker/Cura#16982]
### Cura Version

5.5.0 Beta 1

### Operating System

Windows 10

### Printer

Geeetech Mizar M Seperated Color Module

### Reproduction steps

1. Open attached project
2. Attempt to slice it

### Actual results

Slicing crashes with a message that I should generate a bug report. 

### Expected results

Slicing completes and I am able to print my object. 
[GM_poison_dragon-clean.zip](https://github.com/Ultimaker/Cura/files/12902743/GM_poison_dragon-clean.zip)

### Add your .zip and screenshots here ⬇️

Before pressing slice
![image](https://github.com/Ultimaker/Cura/assets/6501723/a0b5c323-65b4-45e1-9356-653612a2be38)

After pressing slice and getting about 1/3 the way complete
![image](https://github.com/Ultimaker/Cura/assets/6501723/194f7a20-b1df-48a0-be93-68e501722d70)

Cura log file
[cura.log](https://github.com/Ultimaker/Cura/files/12902748/cura.log)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
