### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nor899** [Ultimaker/Cura#16985]
### Cura Version

5.4.0

### Operating System

Win 10

### Printer

Sidewinder X2 usw.

### Name abnormal settings

no

### Describe model location

no

### Describe your model

no

### Add your .zip here ⬇️

Please try to slice this: Pumpkin_Front.stl.
https://www.thingiverse.com/thing:6238747
I have received an error message on several printers.
Error during slicing.
Best wishes
N. Goder

**Comment by GregValiant** [comment]
Thanks for the report.
I received an error message from the Mesh Tools plugin that the model isn't watertight.  The model sliced right away for me.  You might be using different settings and that is why we ask for a project file and not just the model.
You can try moving the model in Cura, or rotating it, or changing the Initial Layer Height by a little bit.
I'll mark this as a duplicate report and go ahead and close it.  If this is a bug, then it is a known bug in 5.4.0.  I hope you understand.
