### ISSUE TITLE
Slicing failed on simple shapes

### ISSUE THREAD

**Issue by hmoazed** [Ultimaker/Cura#16994]
### Cura Version

5.4.0

### Operating System

MacOS Ventura 13.5.2

### Printer

Snapmaker J1

### Name abnormal settings

None

### Describe your model

6 button shafts

### Add your .zip here ⬇️

[failed_slicing.3mf.zip](https://github.com/Ultimaker/Cura/files/12909878/failed_slicing.3mf.zip)

I exported a single rectangular button, then a single round button, from Fusion 360 to Cure, then rotated and multiplied them to what you see.
Deleting the round button that is laying on its side in the middle gets rid of the failure.

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing this so I can't reproduce the problem.  (Windows 10)
Have you tried moving the models around in Cura?  Sometimes moving, rotating, or changing the Initial Layer Height can fool this bug.
I'll leave this open for a now so you can respond.  Let us know if any of those workarounds helped.
