### ISSUE TITLE
Failed Slicing

### ISSUE THREAD

**Issue by 3DStreetFurniture** [Ultimaker/Cura#16998]
### Cura Version

5.4.0

### Operating System

Windows 11 Pro

### Printer

Kobra Max

### Name abnormal settings

Tree Supports

### Describe model location

centre and flat

### Describe your model

Prototype of a stool base

### Add your .zip here ⬇️

[AKMAX Piatto_Base Casting_Stool_Base Weld_350mm eSUN PETG lw 0.4mm lh 0.2mm if 25.0% ext1 230.0C bed 80.0C.zip](https://github.com/Ultimaker/Cura/files/12911640/AKMAX.Piatto_Base.Casting_Stool_Base.Weld_350mm.eSUN.PETG.lw.0.4mm.lh.0.2mm.if.25.0.ext1.230.0C.bed.80.0C.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug in 5.4.0 that keeps models from slicing when they are in certain orientations.  I rotated the model 90°CCW in Cura and it sliced.  You can also try moving the model and changing the Initial Layer Height by a little bit.

I'll mark this as a duplicate and go ahead and close it.  I hope you understand.
Here it is sliced.  It's an 89 hour print with your settings.  Part of the time problem is the 19hrs printing the tree supports.  This is an excellent model for normal supports.  The way I set up the slice it's a 47hr print with only 4hrs spent printing the supports.  I didn't adjust the speeds, just the support.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4e708328-08a8-4e86-ae38-70747c2ffa9a)
