### ISSUE TITLE
need tl-d3 pro settings. 

### ISSUE THREAD

**Issue by djwest9999** [Ultimaker/Cura#17017]
### Cura Version

5.4.0

### Operating System

win. 11

### Printer

none need tl-d3 pro settings

### Reproduction steps

cant find info on my TL-D3 pro

### Actual results

none

### Expected results

have the info i need

### Add your .zip and screenshots here ⬇️

none due to no settings

**Comment by Asterchades** [comment]
All non-Ultimaker definitions are submissions from the community. The Cura team simply doesn't have the time nor hardware to test and maintain anything beyond that scope.

You're more than welcome to create a pull request for an appropriate definition to suit, per the instructions provided [here](https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura) in the Wiki. In the meantime there's almost certain to be an existing definition which functions just fine, and the `Custom FFF Printer` definition is almost completely universal as a "bare bones" definition once the dimensions have been corrected.
