### ISSUE TITLE
Zooming in and out unexpectedly

### ISSUE THREAD

**Issue by srcarter2012** [Ultimaker/Cura#17027]
### Cura Version

5.5.0 Beta 1

### Operating System

Windows 10

### Printer

Ender 3 Max Neo

### Reproduction steps

1. Open Cura
2. Move mouse around without clicking

### Actual results

This causes the view to zoom in and out without pressing any buttons unexpectedly.

### Expected results

Nothing

### Add your .zip and screenshots here ⬇️

[Issue.zip](https://github.com/Ultimaker/Cura/files/13038065/Issue.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I am also running Win10 and my printer is an Ender, and I don't think this is a Cura problem.  Maybe you have a stuck button on the mouse?  
Cura defers to the operating system for the mouse movement, saving files, screen resolution, etc.
This certainly doesn't have anything to do with the that project file.
I'm going to remove the bug label from this and go ahead and close it.  I hope you understand.
