### ISSUE TITLE
Failed to Slice in 5.5.0-Beta.1 

### ISSUE THREAD

**Issue by jburchard23** [Ultimaker/Cura#17026]
### Cura Version

5.5.0-Beta.1

### Operating System

Windows 10

### Printer

Neptune 3 set up for a Neptune 4

### Name abnormal settings

Speeds are set to 250. even if speed is at 55 still fails 

### Describe model location

Yes 90 degrees, if placed like normal then moved no

### Describe your model

Yes sliced fine before, it does not say it isnt, No

### Add your .zip here ⬇️

[EN3_deadpool-bust-v2-supportless-by-eastman.zip](https://github.com/Ultimaker/Cura/files/13035188/EN3_deadpool-bust-v2-supportless-by-eastman.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This wouldn't slice for me either.  I rotated the model 90°CCW and it sliced.  Sometimes just moving the model will fool this bug and changing the Initial Layer Height by a little bit can fool it as well.
I'll mark this as a duplicate report and go ahead and close it as the Cura team is aware of this behavior.  I hope you understand.

![image](https://github.com/Ultimaker/Cura/assets/64202104/86d7e7b2-0aae-4c28-a56c-7ac7e81a1ea9)
