### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baz657** [Ultimaker/Cura#17028]
### Cura Version

5.4.0

### Operating System

Widnows 11

### Printer

ender 3 pro

### Describe your model

new model

### Add your .zip here ⬇️

[CE3S1PRO_yggdrasil_in_a_circle_v1.zip](https://github.com/Ultimaker/Cura/files/13039857/CE3S1PRO_yggdrasil_in_a_circle_v1.zip)

**Comment by DanWSDev** [comment]
Hi, @baz657 I looked at your file I would suggest printing one at a time and lie it down on it side to make it less likely to cause stringing between them and to fall over. 
![Screenshot from 2023-10-19 13-37-05](https://github.com/Ultimaker/Cura/assets/148011207/060b36f5-d557-4947-856f-25e5bef78ae0)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
