### ISSUE TITLE
Foldable Jack O Lantern - Top

### ISSUE THREAD

**Issue by satflo** [Ultimaker/Cura#17047]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Geetech A20M

### Name abnormal settings

My model slice without problems on other slicers. I didin't succeed to slice it on Cura, even without supports or raft

### Describe model location

It slices when i rotate it, not when I'm moving it from the center of the buildplate

### Describe your model

I've never sliced it successfully before. There is no mesh problem with the model

### Add your .zip here ⬇️

[GA_Fab365_Foldable_Jack-O_Lantern_Carved_Face_Ver2.0_Top.zip](https://github.com/Ultimaker/Cura/files/13058765/GA_Fab365_Foldable_Jack-O_Lantern_Carved_Face_Ver2.0_Top.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
It sliced after I rotated it.  This is a well known bug in 5.4.0 and the Cura team is aware of it.  It appears to be much better in 5.5beta but there are still reports from Windows 11 users about this problem.
I'll mark this as a duplicate and go ahead and close it.
![image](https://github.com/Ultimaker/Cura/assets/64202104/1429f6da-98c5-43d8-948e-fa37fb2c0701)
