### ISSUE TITLE
wireframe skull slice issues

### ISSUE THREAD

**Issue by racerty1** [Ultimaker/Cura#17061]
### Cura Version

5.2.2

### Operating System

Windows 11 64bit

### Printer

Biqu BX

### Describe model location

center of build plate, cannot rotate file for reasons of co-extrusion material

### Describe your model

Wireframe skull, the model slices fine on other printers without rearranging the layout on the buildplate and similar profiles

### Add your .zip here ⬇️

[BIQUBX_wireframe_skull_fixed_error.zip](https://github.com/Ultimaker/Cura/files/13062457/BIQUBX_wireframe_skull_fixed_error.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
