### ISSUE TITLE
Standard profiles are gone

### ISSUE THREAD

**Issue by S-teffi** [Ultimaker/Cura#1707]
After the "update" from 2.4 to 2.5 the standard profiles were gone.
I have opened the version 2.4 version again,  the standard profiles are gone also.

I have uninstalled everything and installed only 2.5 again. Standard profiles are still deleted.

When installing 2.5 I took another installation path. Can it be because of this?
Where can I find the default profiles, so I can import them again?

Thanks and best regards, Steffi

**Comment by S-teffi** [comment]
Hi@all..

I think all my profiles are invisible.
If I try to import some profiles, I get the message "successfully imported". But I can't see any / any new profile.

What can I do to fix that error?

Thanks and best regards, Steffi

**Comment by fieldOfView** [comment]
Can you zip up your configuration folder and post it somewhere so we can have a look at what happened?

**Comment by S-teffi** [comment]
Problem solved by deleting the configuration folder before installation cura 2.5 again

**Comment by S-teffi** [comment]
okay.. now I know that the profiles are only not displayed, if I take a self-applied profile. Is this a bug?

**Comment by fieldOfView** [comment]
> Is this a bug?

Probably. Could you zip up the configuration folder and post a link to it?

**Comment by S-teffi** [comment]
Unfortunately, I will be back on Thursday and can upload it.
Perhaps you could create a new material (I have duplicated PLA and changed name, density, price, etc.)

As soon as you select the new material in the main menu, no more profiles are visible.

**Comment by Ghostkeeper** [comment]
Did you also change the "Material Type" field?

**Comment by S-teffi** [comment]
Yes, I also changed it.
If I duplicate an original Cura Material, I will get this error.
If I duplicate an ultimaker material, profiles work. But another problem: the duplicated material is only a reference. So if I change properties (for example density) of new material, it will also change properties of material which I had copied.

**Comment by Ghostkeeper** [comment]
The quality profiles filter on the material type. They are meant to be specific to a certain type of material, such as PLA. So if you modify the material type, all the quality profiles should disappear: They are profiles for PLA, not for your material type.

With material type we mean the molecule, the principal component of the filament in the printer.

**Comment by S-teffi** [comment]
So I can't create a new material for Green-TEC?

**Comment by fieldOfView** [comment]
Sure, but you have to create your own quality profiles for it.
