### ISSUE TITLE
Crash when slicing at specific orientation at center of build plate

### ISSUE THREAD

**Issue by 4angrybadgers** [Ultimaker/Cura#17082]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Creality Ender 3 V2

### Name abnormal settings

None

### Describe model location

Model sliced OK when rotated, or moved as little as 0.6mm from center of build plate.

### Describe your model

Model has been sliced successfully before and appears to be watertight.

### Add your .zip here ⬇️

[Stiffened stock extruder mount.zip](https://github.com/Ultimaker/Cura/files/13073998/Stiffened.stock.extruder.mount.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is a known bug in 5.4.0 and has been reported numerous times.  Another workaround is to change the Initial Layer Height by just a little bit.
I'll mark this as a duplicate and go ahead and close it.  The problem continues to be worked on but it is still an issue with some installations of 5.5beta.  I hope you understand.

I used 5.5beta to slice this.  Looks good to me.
This is the project "as received".
![image](https://github.com/Ultimaker/Cura/assets/64202104/bd6fa247-b3b8-4e91-855b-cae701959b12)
