### ISSUE TITLE
V5.5.0 beta 1 Text and box rapping 

### ISSUE THREAD

**Issue by mwmumma** [Ultimaker/Cura#17098]
### Cura Version

5.5.0 beta

### Operating System

Windows 11

### Printer

Tevo Tornado

### Reproduction steps

The text at the top right is rapping and the Import, Create New, and Default boxes overlay each other when the preferences window is minimized.

### Actual results

If the window is maximized the boxes are visible, but the text remains overlayed.

### Expected results

The text should be visible and the boxes spaced to allow selection when the window is in the default minimized size.

### Add your .zip and screenshots here ⬇️

![Ultimaker 5 5 0 beta 1 Text Rap](https://github.com/Ultimaker/Cura/assets/57846135/793b34ae-378f-4d8e-8dac-28ec9eb67400)

**Comment by GregValiant** [comment]
Thanks for the report.
Do you happen to have any of the plugins from the MarketPlace loaded?  If you do then listing them could be helpful.

"Material Settings" in particular has an effect on that dialog box.  A quick fix has been made to it and it's available [HERE](https://github.com/fieldOfView/Cura-MaterialSettingsPlugin/releases/tag/v3.6.1-DEV) as "...5.0 to current".  Download it and drop it onto the Cura build plate.
