### ISSUE TITLE
Issue Slicing File

### ISSUE THREAD

**Issue by PalmKraft** [Ultimaker/Cura#17095]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Max

### Name abnormal settings

I have my own settings profile I use that I have tweaked to my filament.

### Describe your model

It's a table top mini

### Add your .zip here ⬇️

[PortWinterdale-Bastion-L-Top-v1.0.zip](https://github.com/Ultimaker/Cura/files/13121799/PortWinterdale-Bastion-L-Top-v1.0.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
