### ISSUE TITLE
excessive slice time/ not slicing

### ISSUE THREAD

**Issue by TFDGMel** [Ultimaker/Cura#17105]
### Cura Version

5.5.0

### Operating System

MacOS Big Sur

### Printer

Elegoo

### Name abnormal settings

none. happened with multiple files using default settings

### Describe model location

didn't move

### Describe your model

previously sliced files and new slice files affected

### Add your .zip here ⬇️

File slicing is taking excessive amount of time. A file that previously only took a couple minutes, took over 30min to slice a few days ago. Tried slicing same file on Monday and it sat at less than half processed for over 30 min. I gave up and canceled request.  Today, 10/25, I updated software to 5.5.0. Currently trying to slice a file and it has been sitting in same position 11:15am-12:14pm, less than half processed.
[EN2S_Crate stacker.3mf.zip](https://github.com/Ultimaker/Cura/files/13168258/EN2S_Crate.stacker.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This type of model that has a lot of geometric shapes on the build plate seems to really give Cura trouble.  
Try turning off "Optimize Wall Printing Order" and see if it helps.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
