### ISSUE TITLE
Long Slicing Time if "Optimize Wall Printing Order" is enabled

### ISSUE THREAD

**Issue by leCandas** [Ultimaker/Cura#17104]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

not relevant

### Reproduction steps

trying to slice the file using standard settings and slicing never ends. its a simple stl from tinkercad

### Actual results

slicing does not end

### Expected results

slicing ends.

### Add your .zip and screenshots here ⬇️

[Glorious Crift-Leelo(5).zip](https://github.com/Ultimaker/Cura/files/13167512/Glorious.Crift-Leelo.5.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Models with a lot of geometric shapes on the build plate seem to give Cura heartburn.  Turning off "Optimize Wall Printing Order" can speed up the slicing.
This took two minutes with "Optimize..." turned off.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b3cd585a-7240-4f93-a6d9-674412a4b7cb)

I've marked this as a duplicate and the Cura team will take a look.

**Comment by MariMakes** [comment]
Hey @leCandas,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We are aware of the issue and are collecting test cases to help resolve this. 
Your model is a great example. Thanks for that!

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-11352

Thanks for the report! 👍

**Comment by MariMakes** [comment]
Quick update from our side 👋
Our developers put quite some effort into this one, and it should be resolved in the upcoming release.
The fix can be found here: https://github.com/Ultimaker/CuraEngine/pull/2001

Thanks for your report. Together we can make Cura better 😊
