### ISSUE TITLE
Mandalorian helmet error 

### ISSUE THREAD

**Issue by xPelambrex** [Ultimaker/Cura#17117]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

-

### Describe your model

It's two pieces of a helmet. The right part is working fine, but the left part show the error of slicing

### Add your .zip here ⬇️

[CE3E3V2_Mandalorian_Helmet_Left_Full_Chin.zip](https://github.com/Ultimaker/Cura/files/13180827/CE3E3V2_Mandalorian_Helmet_Left_Full_Chin.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
