### ISSUE TITLE
holes like window are filled in Cura 5.5.0

### ISSUE THREAD

**Issue by RolandHartl** [Ultimaker/Cura#17127]
### Cura Version

5.5.0

### Operating System

Windows 10/Intel5

### Printer

Anycubic Kobra Max

### Reproduction steps

1. files for a "tardis" phone station from movie "Dr. Who" do have open windows and open roof.
2. these files are attached.
3. after slicing in Cura and starting prints these windows and the open roof are completely filed with filament.
4. I tried the same file in the anycubic slicer and hereby get open windows and open roof, all ok.
5. I will attach the stl files and the files getting from the cura slicer as gcode

### Actual results

used another slicer to solve problem

### Expected results

windows and holes must be free

### Add your .zip and screenshots here ⬇️

[stl-files.zip](https://github.com/Ultimaker/Cura/files/13188483/stl-files.zip)
[cgode_files_error.zip](https://github.com/Ultimaker/Cura/files/13188514/cgode_files_error.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is likely a setting issue.  I'll remove the bug label for now.
This is in 5.5.0 with my printer and settings and with "Remove all Holes" turned off.
![image](https://github.com/Ultimaker/Cura/assets/64202104/3de3dd09-198b-448c-be0f-ec4127c21aed)

**Comment by RolandHartl** [comment]
Ok, I understand, but the preview of gcode shows object correct with the holes whereas the print shows closed windows and holes.....There must be a correct previewVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: GregValiant ***@***.***> Datum: 27.10.23  14:35  (GMT+01:00) An: Ultimaker/Cura ***@***.***> Cc: RolandHartl ***@***.***>, Author ***@***.***> Betreff: Re: [Ultimaker/Cura] holes like window are filled in Cura 5.5.0
  (Issue #17127) 
Thanks for the report.
This is likely a setting issue.  I'll remove the bug label for now.
This is in 5.5.0 with my printer and settings and with "Remove all Holes" turned off.

**Comment by GregValiant** [comment]
_"...the preview of gcode shows object correct with the holes whereas the print shows closed windows and holes..."_
Cura users slice somewhere in the range of 2,000,000 per day on a good day.  If this was a problem with Cura someone would have noticed.
You were asked for a Project File when you opened this report.  It is the main debugging tool and you haven't provided one and I've seen no screenshots showing the problem on your system.  Use the "File | Save Project") command to create a project file, then zip it and post the zip folder here.  Is it possible that you are you confusing the "Prepare" screen with the "Preview" screen?
Here is the prepare screen.  This is with "Remove All Holes" enabled.  It looks like this before and after slicing.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4d4a9fc8-9966-4d54-bd73-fd6d8d826b45)
This is the preview screen after slicing and with Remove All Holes enabled.  This is what your gcode files look like.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b22742b3-f1c7-48e8-9f5f-ad7fee2a4ab0)

**Comment by RolandHartl** [comment]
Ok. Thank you.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: GregValiant ***@***.***> Datum: 27.10.23  20:08  (GMT+01:00) An: Ultimaker/Cura ***@***.***> Cc: RolandHartl ***@***.***>, Author ***@***.***> Betreff: Re: [Ultimaker/Cura] holes like window are filled in Cura 5.5.0
  (Issue #17127) 
"...the preview of gcode shows object correct with the holes whereas the print shows closed windows and holes..."
Cura users slice somewhere in the range of 2,000,000 per day on a good day.  If this was a problem with Cura someone would have noticed.
You were asked for a Project File when you opened this report.  It is the main debugging tool and you haven't provided one and I've seen no screenshots showing the problem on your system.  Use the "File | Save Project") command to create a project file, then zip it and post the zip folder here.  Is it possible that you are you confusing the "Prepare" screen with the "Preview" screen?
Here is the prepare screen.  This is with "Remove All Holes" enabled.  It looks like this before and after slicing.

This is the preview screen after slicing and with Remove All Holes enabled.  This is what your gcode files look like.

**Comment by GregValiant** [comment]
This is finished?  Can we close this?

**Comment by RolandHartl** [comment]
Yes, thanks.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: GregValiant ***@***.***> Datum: 27.10.23  23:57  (GMT+01:00) An: Ultimaker/Cura ***@***.***> Cc: RolandHartl ***@***.***>, Author ***@***.***> Betreff: Re: [Ultimaker/Cura] holes like window are filled in Cura 5.5.0
  (Issue #17127) 
This is finished?  Can we close this?
