### ISSUE TITLE
Error when slicing a model with "tree" support

### ISSUE THREAD

**Issue by dddVolodyabbb** [Ultimaker/Cura#17125]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Klipper

### Reproduction steps

cura throws an error when building support "tree". With normal support, no error occurs.

### Actual results

Cura must cut the model and send it to print.

### Expected results

Cura freezes in the middle of the model cutting process and produces a critical error.

### Add your .zip and screenshots here ⬇️

I will leave an archive with the rest of the print settings and a log and printable model file.
[cura.log](https://github.com/Ultimaker/Cura/files/13188041/cura.log)
[settings and file.zip](https://github.com/Ultimaker/Cura/files/13188043/settings.and.file.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for a project file ("File | Save Project") because it will contain all your settings, the model, and your printer.
This is in 5.4.0 with my printer and settings.  I'm unable to duplicate the problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/9750ada0-e4d4-4baa-aa49-ecffb03a344a)

**Comment by dddVolodyabbb** [comment]
> Спасибо за отчет. Мы запрашиваем файл проекта ("Файл | Сохранить проект"), поскольку он будет содержать все ваши настройки, модель и ваш принтер. Это в версии 5.4.0 с моим принтером и настройками. Я не могу воспроизвести проблему. ![изображение](https://user-images.githubusercontent.com/64202104/278640235-9750ada0-e4d4-4baa-aa49-ecffb03a344a.png)

project:
[vtxAntenna gps 1.2.zip](https://github.com/Ultimaker/Cura/files/13189017/vtxAntenna.gps.1.2.zip)

**Comment by GregValiant** [comment]
There should not have been an error with support set to "Touching Build Plate" and I do not get an error like that (I have the same printer) so I am unable to duplicate the problem.
Do you want to leave this report open?

**Comment by dddVolodyabbb** [comment]
> Не должно было возникнуть ошибки при настройке поддержки на "Касание пластины сборки", и я не получаю подобную ошибку (у меня тот же принтер), поэтому я не могу воспроизвести проблему. Вы хотите оставить этот отчет открытым?

well... maybe one of the plugins is causing the error. No, I'll close the report.
