### ISSUE TITLE
problem with cutting

### ISSUE THREAD

**Issue by Ulito22** [Ultimaker/Cura#17130]
### Cura Version

5.4

### Operating System

Windows 11

### Printer

Crealty Ender 3 S1

### Name abnormal settings

No

### Describe your model

Yes, before I was able to cut it normally

### Add your .zip here ⬇️

[CE3S1_LLAVERO FINAL CERRO TENIS.zip](https://github.com/Ultimaker/Cura/files/13191398/CE3S1_LLAVERO.FINAL.CERRO.TENIS.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
There is a slicing bug in 5.4.0 that can keep models from slicing.  Moving and rotating the model is the usual workaround but you are limited with the number you have on the plate.  You can try "Select all models" and rotate the entire group 90°.  Changing the Initial Layer Height is another workaround that can fool the bug.
The racket also has a couple of errors in it and when you multiply the racket you multiply the errors.  That might be having an effect.
I'll mark this as a duplicate and go ahead and close it as this is a well known bug.  It was worked on for 5.5.0 but still shows up occasionally.
