### ISSUE TITLE
multiply not separating builds on plate  

### ISSUE THREAD

**Issue by dsc52359** [Ultimaker/Cura#17156]
### Cura Version

5.5.0

### Operating System

windows 11

### Printer

ender 5 pro

### Reproduction steps

Place item to build on plate then attempt to multiply it.

### Actual results

Doesn't spread the builds apart correctly.

### Expected results

separation 

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/149433628/1f12004a-ac31-488e-851d-56a1bc561f16)

**Comment by GregValiant** [comment]
In the Cura Preferences do you have "Ensure models are kept apart" checked?

**Comment by dsc52359** [comment]
It is now thank you. I never had to do that before but thanks once again.

**Comment by GregValiant** [comment]
I'll go ahead and close this then as it appears it was a setting issue.

**Comment by dsc52359** [comment]
Yes, please!
