### ISSUE TITLE
bug when opening cura

### ISSUE THREAD

**Issue by sd95100** [Ultimaker/Cura#17153]
### Cura Version

4.13.0

### Operating System

rasperry os

### Printer

crealty ender 5

### Reproduction steps

i head successfully installed cura butt when i wanteed to install it on another system, it display "the plugin TrimesReader could not be loaded. Re-instaling the plugi might solve the issue" and "the plugin AMRReader could not be loaded. Re-instaling the plugi might solve the issue" I clicked on it but it did nothing, i restarted and i reintalled but that didn't do anything. on the old system it worked corerectly. and since then i can't import the file. 

### Actual results

it display "the plugin TrimesReader could not be loaded. Re-instaling the plugi might solve the issue" and "the plugin AMRReader could not be loaded. Re-instaling the plugi might solve the issue"

### Expected results

i hope it works

### Add your .zip and screenshots here ⬇️

![20231030_16h01m04s_grim](https://github.com/Ultimaker/Cura/assets/67218839/ebe0bd84-35a2-4b56-9e78-e34fd298ac1b)

![20231030_16h02m11s_grim](https://github.com/Ultimaker/Cura/assets/67218839/bb1f47a3-d772-4665-bffa-ea6c27a73414)

**Comment by sd95100** [comment]
I'm using a raspberry pi 400 and had to replace the sd card because it crashed. cura worked correctly but when i wanted to reinstall cura it caused this bug

**Comment by fieldOfView** [comment]
You are likely missing a dependency: trimesh.

Ultimaker does not make a distribution of Cura that is compatible with Raspberry Pi OS. You are going to have to ask whoever packaged Cura for Raspberry Pi OS to fix the dependencies in their package.
