### ISSUE TITLE
materials disapear until scrolling

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#1716]
In Cura 2.4 and 2.5 some custom materials are missing from the list in "manage materials" until you scroll down and scroll back up again.

**Comment by Ghostkeeper** [comment]
Whoa, weird.

What operating system are you using?

Does it appear as a blank line in the material manager or is it just not listed until you scroll? If it's the first, we might be looking at a Qt bug. If it's the second, perhaps it's an update bug resulting from us asynchronously filling the list or something...?

**Comment by MarcusWolschon** [comment]
Windows
They are just not listed until I scroll.
Since it's only custom materials that are affected, my guess is some update bug too. That the materials are added later but after adding them the model does not inform the view that there is an update.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/1757/commits/a727e4ffd09d365dfaa3f532c912a952f30e7089
