### ISSUE TITLE
discard or keep settings dialog unusable

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#1717]
Cura 2.5
Windows 10 on a 4K display

when switching profiles the "discard or keep settings" dialog can not be used.
I assume there are some buttons off-screen that I am supposed to press.
Resizing the dialog is possible but doesn't reveal additional ui elements
nor does it completely reveal the half cut off dropdown-list.

![untitled](https://cloud.githubusercontent.com/assets/604692/25280914/dcda2a54-26ab-11e7-880b-8e6f3e5f3e9b.png)

**Comment by fieldOfView** [comment]
This was fixed in master 20 days ago, but unfortunately the fix was not applied to the 2.5 branch. See https://github.com/Ultimaker/Cura/pull/1636

**Comment by MarcusWolschon** [comment]
Then let's set the Milestone to 2.5.1 or 2.6

**Comment by fieldOfView** [comment]
I have not seen the Milestone feature being used in the Cura project.
