### ISSUE TITLE
"unsupported operand type(s) for /: 'NoneType' and 'int'"

### ISSUE THREAD

**Issue by sumone-lol** [Ultimaker/Cura#17171]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality Ender 3 Pro

### Name abnormal settings

N/A

### Describe model location

Location and rotation doesn't matter

### Describe your model

Haven't sliced it before but I think it should still be fine, it's a pretty simple model

### Add your .zip here ⬇️

Model I tried slicing (I'm not very experienced don't judge me) [USB Case.zip](https://github.com/Ultimaker/Cura/files/13222129/USB.Case.zip)

Error message I received:
![Screenshot 2023-10-31 200044](https://github.com/Ultimaker/Cura/assets/88620982/e172c7df-e6d4-4bc6-a183-fefdf1937445)

This only started happening after I updated to 5.5.0, it was fine in 5.4.0

**Comment by GregValiant** [comment]
With the model loaded use the "Help | Show Configuration Folder" command.
Within the Configuration Folder will be a file "Cura.log".  Right click on it and select "Send To... Compressed (ziped) folder" and post the zip folder here.

![Untitled](https://github.com/Ultimaker/Cura/assets/64202104/fadd25af-f4cf-410e-86be-c97bc2aaecfc)

**Comment by sumone-lol** [comment]
[cura.zip](https://github.com/Ultimaker/Cura/files/13222376/cura.zip)

**Comment by GregValiant** [comment]
Thanks.
@MariMakes or another member of the Cura team will take a look.

**Comment by yzheka** [comment]
I have noticed that Arc_Welder plugin causing this issue. Disabling it solves the problem

**Comment by GregValiant** [comment]
@fieldOfView can you look at this one?

**Comment by sumone-lol** [comment]
Huh, strange. I went to test it and turn off arc welder which worked. But then after I re-enabled it, it still worked. Not sure what went on there :L  I'll probably reopen this if it happens again in the future.
