### ISSUE TITLE
cura will not slice

### ISSUE THREAD

**Issue by Aarenwain** [Ultimaker/Cura#17182]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

anycubic kobra go

### Name abnormal settings

No

### Describe model location

no

### Describe your model

no

### Add your .zip here ⬇️

[AKGO_TORSO.zip](https://github.com/Ultimaker/Cura/files/13239124/AKGO_TORSO.zip)

**Comment by GregValiant** [comment]
This is the same model and same report as #17183 so I'll close this one as a duplicate.
