### ISSUE TITLE
Missing Temperature Control UM2+

### ISSUE THREAD

**Issue by UltimateSports** [Ultimaker/Cura#1718]
Using Ultimker 2+ and cura 2. ... all temperature control is missing.

**Comment by fieldOfView** [comment]
This is on purpose, because for the Ultimaker 2(+), materials are handled on the printer.

If you want to have full control over the material settings inside Cura, go to Machine Settings and switch GCode Flavor to "Reprap (Marlin/Sprinter)"

**Comment by nallath** [comment]
This is by design.
