### ISSUE TITLE
Lithophane slicing failed on Cura 5.5.0

### ISSUE THREAD

**Issue by Harrybroha** [Ultimaker/Cura#17207]
### Cura Version

5.5.0

### Operating System

Windows11

### Printer

Custom FFF Printer

### Name abnormal settings

rotated 

### Describe your model

Mesh tested, is 100% waterproof , sliced it with anycubic slicer

### Add your .zip here ⬇️

[CFFFP_New_Litho_Opa1.zip](https://github.com/Ultimaker/Cura/files/13253312/CFFFP_New_Litho_Opa1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
