### ISSUE TITLE
Fine tuning Support Overhang Angle with Tree Supports

### ISSUE THREAD

**Issue by bazrd** [Ultimaker/Cura#17219]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 V2

### Name abnormal settings

Support Overhang Angle

### Describe model location

It barely fits as is

### Describe your model

half body piece of a P90

### Add your .zip here ⬇️

[CE3E3V2_polybius right grips.zip](https://github.com/Ultimaker/Cura/files/13257019/CE3E3V2_polybius.right.grips.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
