### ISSUE TITLE
Slicing failed testing out different support types

### ISSUE THREAD

**Issue by AryaOfDruids** [Ultimaker/Cura#17213]
### Cura Version

5.2.1

### Operating System

Windows 10

### Printer

Anycubic Kobra Neo

### Name abnormal settings

changed speed and support settings (tree touching buildplate) infill- gyroid. Was testing different support types to see what would use the least amount of filament and effort to cleanup

### Describe model location

sliced previously in the same spot. testing different supports and went back to one already tested and it wouldn't slice

### Describe your model

successful slice yes, watertight no but no error pops up for the watertight issue

### Add your .zip here ⬇️

[AK_lid_leaner.zip](https://github.com/Ultimaker/Cura/files/13255695/AK_lid_leaner.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
