### ISSUE TITLE
feature request: auto reload on file change

### ISSUE THREAD

**Issue by Ognian** [Ultimaker/Cura#1721]
Hello,
an option (check box) in the view to autoreload when checked  would be great e.g. when  the underlying .stl file changes then the view is refreshed (at the moment it has to be triggered manually with F5). This will improve a lot the overall workflow...
Thanks a lot
Ognian

**Comment by nallath** [comment]
Thanks for the feature request! I've created a ticket for it (CURA-3716). We will let you know if it's going to be implemented (which is up to our product owner).

**Comment by Ghostkeeper** [comment]
Does Python have functionality to monitor the file system or do we need an external library for that?

**Comment by awhiemstra** [comment]
I don't know if Python has it, but I do know that Qt has it. So we won't need an extra dependency in any case.

**Comment by jackha** [comment]
Deferred because it ended up too low of our backlog.

**Comment by Ghostkeeper** [comment]
This has been implemented now.

**Comment by bo0tzz** [comment]
Hi! I've been looking for this feature but can't find it anywhere. Is it still present?

**Comment by fieldOfView** [comment]
It is, but it is disabled for Windows because the feature caused a crash on Windows.

**Comment by bo0tzz** [comment]
I'm running on linux, but I can't find it. Any pointers?

**Comment by Ghostkeeper** [comment]
Once a file on the build plate changed, you should see a message pop up on the bottom side of the screen, asking you whether you want to reload your mesh.

It currently doesn't work for meshes that contain multiple submeshes (like AMF and 3MF) but that's something that we're improving in Cura 4.6.

**Comment by wohltat** [comment]
There is a manual reload but no "auto reload" in linux. Or am i missing something?
Would love to see that feature in cura.

**Comment by Ghostkeeper** [comment]
It's not 100% automatic. That would be inadvisable because people would normally expect the data loaded in Cura to not change once it's loaded.
It's implemented with this pop-up:
![image](https://user-images.githubusercontent.com/2448634/109818840-ba8e5b00-7c33-11eb-8a94-7f81ca9784bb.png)
So you still have to press the button to reload it.
