### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by Gilgamesh82** [Ultimaker/Cura#17214]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Peopoly Moai

### Name abnormal settings

0.1 layer thickness

### Describe model location

Center build plate.  Rotation doesn't help.

### Describe your model

Slices fine in Asura3D

### Add your .zip here ⬇️

https://go.wetransfer.com/t-GbrqsRXVlw
[PleaseSeeLink.zip](https://github.com/Ultimaker/Cura/files/13255956/PleaseSeeLink.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model is chock full of errors.  You will need to repair it before Cura can slice it.  I tried to repair it but the file is so big and the surfaces so dense that it wouldn't repair.
The polka-dot areas have errors.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5be542fa-e077-49cc-815f-18632c45c84e)

There is a bug in 5.5.0 that can keep a model from slicing and the Cura team is aware of it.  I'm going to close this as nothing can be done with that model and it is not a good example for debuging.  I hope you understand.
