### ISSUE TITLE
Unable to slice (tried 5.4 and 5.5)

### ISSUE THREAD

**Issue by Sniper-1818** [Ultimaker/Cura#17216]
### Cura Version

5.5.0 and 5.4.0

### Operating System

Windows 11

### Printer

Aroura A5

### Describe your model

At first it would slice upright, but not rotated. But now it wont slice at all

### Add your .zip here ⬇️

[JA5A5S_Ghost_Mask.zip](https://github.com/Ultimaker/Cura/files/13256169/JA5A5S_Ghost_Mask.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is a known bug.  It's been worked on but is still there.  You can move the model, rotate the model, or try changing the initial layer height.  I moved it and with the Initial Layer Height at 0.15 it sliced.
I'll mark this as a duplicate and go ahead and close it.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/0df276f7-a27a-470b-9c60-78ed1fa3036c)
