### ISSUE TITLE
rc boat

### ISSUE THREAD

**Issue by Bezzo1979** [Ultimaker/Cura#17226]
### Cura Version

5.5.0

### Operating System

windows 10/64

### Printer

Ender 3v2 Neo

### Describe model location

https://www.printables.com/model/322399-zryw-1-an-hydrofoil-rc-boat/files

### Describe your model

n/a

### Add your .zip here ⬇️

[hydrofoil-rc-boat-model_files.zip](https://github.com/Ultimaker/Cura/files/13257942/hydrofoil-rc-boat-model_files.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Yes, those parts do appear to belong to a boat.
Without a project file, screenshots, or description of what might be going on I can't tell anything else about it.
I'll close this as it contains no pertinent information.
