### ISSUE TITLE
Slicing Failed Unexpected Error when tyring to splice

### ISSUE THREAD

**Issue by Droidslayer** [Ultimaker/Cura#17228]
### Cura Version

5.3.0 Beta

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 Plus

### Name abnormal settings

Using Recommned settings

### Describe model location

Two pieces near the center one infront of the tother

### Describe your model

a chest amor pice cut in half 

### Add your .zip here ⬇️

[EN3P_Chect Pice 1_1 Bot.zip](https://github.com/Ultimaker/Cura/files/13258581/EN3P_Chect.Pice.1_1.Bot.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
