### ISSUE TITLE
Mexico

### ISSUE THREAD

**Issue by eplotner1** [Ultimaker/Cura#17222]
### Cura Version

5.5.0

### Operating System

Win 11

### Printer

Ender 3 v2 Klipper

### Describe your model

I have never been able to slice

### Add your .zip here ⬇️

[CE3E3V2_llavero_escudo_mexico.zip](https://github.com/Ultimaker/Cura/files/13257170/CE3E3V2_llavero_escudo_mexico.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There is a persistent bug that can keep models from slicing.
Try moving, rotating the model and sometimes changing the Initial Layer Height by a little bit can fool the bug.
I didn't have any trouble slicing this.
I'll mark this as a duplicated and close it as the Cura team is aware of this bug.
![image](https://github.com/Ultimaker/Cura/assets/64202104/98c77d14-412d-4d83-abea-b183f6d708fe)
