### ISSUE TITLE
Neil Armstrong not slicing. Error.

### ISSUE THREAD

**Issue by anthonyzeh** [Ultimaker/Cura#17236]
### Cura Version

5.5

### Operating System

Windows 10

### Printer

Anycubic Kobra Plus

### Name abnormal settings

nope

### Describe model location

yes

### Describe your model

no first time print of this model

### Add your .zip here ⬇️

[AK_armstrong_suit_9in_statue.zip](https://github.com/Ultimaker/Cura/files/13260868/AK_armstrong_suit_9in_statue.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
