### ISSUE TITLE
Slicing error with trees

### ISSUE THREAD

**Issue by burkes13** [Ultimaker/Cura#17253]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Custom Printer

### Name abnormal settings

No unusual or advanced settings. Does slice when normal support selected, but when trees selected it fails

### Describe your model

Model is of horns, the model can be slices when normal support is selected, not with trees.

### Add your .zip here ⬇️

[CFFFP_JesterHorns1.zip](https://github.com/Ultimaker/Cura/files/13284812/CFFFP_JesterHorns1.zip)

**Comment by doubletrouble023** [comment]
I also get this a lot of the time.
Sometimes it works as usual if I uncheck "Create support" and/or "Tree" a few times.

**Comment by 5axes** [comment]
No issue on my Windows 10 laptop ...  
![image](https://github.com/Ultimaker/Cura/assets/11015345/19ac58a0-418c-4546-a853-383c326a5d61)

The Windows 11 issue ? https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
