### ISSUE TITLE
Can't open two models simultaneously

### ISSUE THREAD

**Issue by josecalvario** [Ultimaker/Cura#17251]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Divide my complete model into 2 STL files, perfectly aligned with each other.
2. File/open inside CURA doesn't allow me to select both files. If I open one and then the other, the second will be imported with a translation and mirroring transformation, which will completely invalidate the model.
3. If I try to drag and drop both files, the same thing happens: one of the mode half get's mirrored by CURA.

How can I import 2 STL files in order to do a print with  2 colors?

### Actual results

The imported model get's mirrored on the second half.

### Expected results

I would expect the model to completely import without any transformation.

### Add your .zip and screenshots here ⬇️

[model_for_3dprint.zip](https://github.com/Ultimaker/Cura/files/13281809/model_for_3dprint.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This was a known bug in 5.4.0 and was fixed in 5.5.0.
I'll go ahead and close this.
