### ISSUE TITLE
both cura 5.4 and 5.5 wont slice.

### ISSUE THREAD

**Issue by Duncantoys85** [Ultimaker/Cura#17255]
### Cura Version

5.4 and 5.5

### Operating System

10

### Printer

ender 3 v2/custom fff printer

### Name abnormal settings

no

### Describe model location

no

### Describe your model

does it on mutple models

### Add your .zip here ⬇️

[CFFFP_Crystal_Pen_Holder.zip](https://github.com/Ultimaker/Cura/files/13290658/CFFFP_Crystal_Pen_Holder.zip)

both cura 5.4 and 5.5 wont slice. it starts to slice then says it has reached a unexpected error and then closes program.

*Slicing engine for cura has stopped working
A problem caused the program to stop working correctly.
Windows will close the program and notify you if a solution is available.

Close program

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I had to move the model, rotate it 90° CCW and set the Initial Layer Height to 0.27 but it finally sliced.

This is a known bug in 5.4 and 5.5.  I'll mark this as a duplicate and close it as the Cura team is aware of this one.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/1d45c9e2-632b-4089-93e0-0908370850b8)
