### ISSUE TITLE
cant drag and drop stl files into cura 2.5

### ISSUE THREAD

**Issue by xile6** [Ultimaker/Cura#1725]
cant drag and drop stl files into cura 2.5

**Comment by fieldOfView** [comment]
Try restarting Cura. This only happens the first time you run Cura, directly from the installer.

**Comment by Ghostkeeper** [comment]
And if that doesn't work: What operating system? Do you have logs?

**Comment by xile6** [comment]
After fully uninstalling 2.4 and 2.5  and a fee reboots its started working
