### ISSUE TITLE
Sacrarium Mosaic Fail

### ISSUE THREAD

**Issue by PeteBoo** [Ultimaker/Cura#17263]
### Cura Version

5.5.0 beta 1

### Operating System

Windows 11

### Printer

Artillery Sidewinder X1

### Name abnormal settings

Slices at 0.16 layer height, but not at 0.12

### Describe model location

Slices at 0.12 if turned 90 degrees

### Describe your model

Mesh fixed in Blender, watertight. First time slicing it.

### Add your .zip here ⬇️

[Sacrarium Mosaic Floor 1.zip](https://github.com/Ultimaker/Cura/files/13298005/Sacrarium.Mosaic.Floor.1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
