### ISSUE TITLE
Slicing failure

### ISSUE THREAD

**Issue by Kid-Garrett** [Ultimaker/Cura#17262]
### Cura Version

5.5.0

### Operating System

macOS Big Sur

### Printer

Ender 3 s1 pro with sonic pad (custom FFF set up as per creality instructions)

### Name abnormal settings

has happened before, couldnt report as already exited cura and didnt have save project to send. when retried with same settings, it worked.

### Describe model location

sliced successfully when tried again, no change.

### Describe your model

new model

### Add your .zip here ⬇️

[CFFFP_HexSideLeft.3mf.zip](https://github.com/Ultimaker/Cura/files/13297627/CFFFP_HexSideLeft.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
