### ISSUE TITLE
[5.5.0] Typo in warning

### ISSUE THREAD

**Issue by RedstoneGuy9248** [Ultimaker/Cura#17267]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Ender 3

### Reproduction steps

1.) Import a (.3mf) file with no models

### Actual results

A warning appears which says "There where no models in "file.3mf""
There is a typo, it says where instead of were

### Expected results

A warning appears which says "There were no models in "[PATH].3mf""

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/66919162/a472d9c4-d393-40b7-bca1-9eb77756a979)

**Comment by GregValiant** [comment]
Thanks for the report.
It looks like it showed up in 5.4.0.
I'll mark this as a duplicate of #16810 and go ahead and close this one.  I hope you understand.
