### ISSUE TITLE
SLicing Fail 

### ISSUE THREAD

**Issue by Diserian** [Ultimaker/Cura#17269]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Anycubic Vyper

### Name abnormal settings

it slices with the normal profile but i use the recommended one for Anycubic Vyper

### Describe model location

No

### Describe your model

The model only slices right wenn i use the recommendes setting. that does not work with my pla and printer

### Add your .zip here ⬇️

[AI3M_BonyBasilisk_ExtraLong_Medium.zip](https://github.com/Ultimaker/Cura/files/13305415/AI3M_BonyBasilisk_ExtraLong_Medium.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
