### ISSUE TITLE
WCF_Top

### ISSUE THREAD

**Issue by EstebanClaro** [Ultimaker/Cura#17270]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

artillery genius

### Describe your model

Trophy World Cup Female (top part)

### Add your .zip here ⬇️

[AG_WCF_TOP.zip](https://github.com/Ultimaker/Cura/files/13307957/AG_WCF_TOP.zip)

**Comment by EstebanClaro** [comment]
Bottom part of this model (brokendown into two pieces by means of MeshMixer) was sliced properly

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
