### ISSUE TITLE
Manually Configure IP Address for Printer in Cura.

### ISSUE THREAD

**Issue by DevonDorrity** [Ultimaker/Cura#17274]
### Is your feature request related to a problem?

When I installed my Snapmaker Printer using the Snapmaker plugin, it worked great, until my router's DHCP reset and the printer received a new IP address. There is no way to change the IP address of an existing printer to match its new IP so I have to use a USB drive to send files to the printer.

### Describe the solution you'd like

I would like the IP address to be exposed in the Machine Settings dialogue box so that if the printer's IP address changes, I can quickly update it and restore network printing.

### Describe alternatives you've considered

I have tried to add a new printer by IP, but it says it can't find it. I am using a Starling Network and I can't find any way to statically assign the IP addresses.

### Affected users and/or printers

I would think this would allow all users that have a printer IP address change an easy way to update it. I am using the Snapmaker Artisan.

### Additional information & file uploads

I'm using Cura 5.5.0 on a M1 Ultra Mac.

**Comment by Asterchades** [comment]
This sounds like something better dealt with by the author of the Snapmaker plugin, as the functionality you're requesting to be altered isn't part of the base Cura package.

https://github.com/Snapmaker/SnapmakerCuraPlugin
