### ISSUE TITLE
Insane amount of material added to sliced model

### ISSUE THREAD

**Issue by ValerioMalara** [Ultimaker/Cura#17271]
### Cura Version

5.4.0 - 5.5.0

### Operating System

Windows 10

### Printer

FLSUN SR

### Reproduction steps

Tried to print a model with hollow parts.
<img width="468" alt="Immagine 2023-11-09 133614" src="https://github.com/Ultimaker/Cura/assets/26430835/af62988d-0b93-488c-85be-e59540b1a8c6">

### Actual results

Material was added to the sliced model, certain orientation seens to aggravate the issue
<img width="553" alt="Immagine 2023-11-09 133634" src="https://github.com/Ultimaker/Cura/assets/26430835/c224834e-6ba2-484a-91a2-afd2e8f83f1a">

### Expected results

Correct slice of the model with no added geometry

### Add your .zip and screenshots here ⬇️

[FSR_Frame-Katana.zip](https://github.com/Ultimaker/Cura/files/13308142/FSR_Frame-Katana.zip)

**Comment by chipmunk1977** [comment]
This looks like you might have got the parameter "make overhangs printable" selected. If so, I'd try slicing it with that unchecked.

**Comment by GregValiant** [comment]
That's what it looks like to me as well.
@ValerioMalara was that the problem and can we close this?
