### ISSUE TITLE
Merged part when multiplying 

### ISSUE THREAD

**Issue by Brumcm** [Ultimaker/Cura#17286]
### Cura Version

5.5.0

### Operating System

macOS Ventura 13.6

### Printer

Ceality Ender 3 Pro

### Reproduction steps

- Download file from https://www.printables.com/model/132643-aqara-temperature-sensor-wall-mount
- Import .STL file
- Select item, multiple for 9 copies
- Select Top View
- Note that piece in the center is a mutant combination of two units

<img width="775" alt="Screenshot 2023-11-10 at 6 40 49 PM" src="https://github.com/Ultimaker/Cura/assets/68305621/01562c08-b492-43e3-8d7a-e9fd2d3a9315">

### Actual results

mutant double piece created

<img width="775" alt="Screenshot 2023-11-10 at 6 40 49 PM" src="https://github.com/Ultimaker/Cura/assets/68305621/c76ac455-6468-4ce6-acd3-07c99eaf3fc7">

### Expected results

Should have printed 10 units, not 8 and 1 mutant double piece

[CE3PRO_Aqara_Sensor_Mount.3mf.zip](https://github.com/Ultimaker/Cura/files/13323766/CE3PRO_Aqara_Sensor_Mount.3mf.zip)

### Add your .zip and screenshots here ⬇️

Cura log file...

[cura.log.zip](https://github.com/Ultimaker/Cura/files/13323799/cura.log.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Under "Preferences / Configure Cura" on the General tab you will find "Ensure models are kept apart".  Make sure that is ticked and try it again.
![KeepModelsApart](https://github.com/Ultimaker/Cura/assets/64202104/073b4433-cb98-4e15-845a-15d25b1b2923)

![image](https://github.com/Ultimaker/Cura/assets/64202104/3efa9c1e-f7ca-45f8-8005-115870704158)

I'll remove the bug label.  Let us know if that works for you and if it doesn't I'll put the bug label back on.

**Comment by Brumcm** [comment]
Greg,

Thanks for the quick reply!  That did resolve the issue, but I had to clear the build plate, re-add the object and then re-multiply.  Shouldn't that option be checked by default?

thanks!
Bruce

**Comment by GregValiant** [comment]
If it is enabled by default then the user can never overlap models as they always jump away from each other.  I have a feeling that a lot of users would complain about that (including me).

If you want to add an override to your definition file you can try.  The setting is named "physics/automatic_push_free".
It is defined in PlatformPhysics.py on line 40.

I'll go ahead and close this as it is "expected behavior" given the setting that you had.  I hope you understand.

**Comment by Brumcm** [comment]
Understood, thanks for letting me know
