### ISSUE TITLE
Supports generated as a loop so cannot be taken off

### ISSUE THREAD

**Issue by radical-ale** [Ultimaker/Cura#17281]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Creality Ender 3 S1

### Reproduction steps

1. Import file
2. Generate supports for file
3. Print file
4. Support cannot be taken off as it has been generated as a loop
![Support_Issue_1](https://github.com/Ultimaker/Cura/assets/94841352/daf226e2-b1da-47ce-8370-c81ca40f350a)
![Support_Issue_2](https://github.com/Ultimaker/Cura/assets/94841352/cd593614-a641-49cd-9aeb-d92aae17a025)

### Actual results

File was printed but I could to take off all the supports.

### Expected results

Whenever I generate automatically supports, I expect to be able to take them off. I expect the software to be able to generate supports that I will be able to remove, e.g. with branches small enough to be removed from a hole or not connected through the bottom and top so they cannot be removed from a closed structure.

### Add your .zip and screenshots here ⬇️

![Support_Issue_1](https://github.com/Ultimaker/Cura/assets/94841352/9b45aa32-5d9a-4729-b3e6-a8b31332597f)
![Support_Issue_2](https://github.com/Ultimaker/Cura/assets/94841352/0de0d656-a840-4e43-a9fb-dfb5ea3edb2d)
[CE3S1_keyScull_fixed.zip](https://github.com/Ultimaker/Cura/files/13321833/CE3S1_keyScull_fixed.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There are settings you can adjust to keep the branches from growing together.  I don't see a bug here so I'll go ahead and remove the bug label and close this.  I hope you understand.

These are my support removal tools.  From left to right:
Micro-files, Picks, Hobby knife, Razor blade, Forceps, Chisel, Filament nippers, and Needle-nose pliers.
![DSCN3202](https://github.com/Ultimaker/Cura/assets/64202104/408fcaf0-8405-4625-858e-f45c45775903)
