### ISSUE TITLE
cura slicing failing

### ISSUE THREAD

**Issue by arad20051** [Ultimaker/Cura#17289]
### Cura Version

5.5

### Operating System

windows 11

### Printer

Snapmaker A350 Dual Extruder

### Name abnormal settings

no. all the settings that I have used work

### Describe model location

the model is in the center

### Describe your model

nope. I did try to fix it with the meshtools plugin but it didnt work

### Add your .zip here ⬇️

[S2ADE_freddy.zip](https://github.com/Ultimaker/Cura/files/13325504/S2ADE_freddy.zip)
this is a 3mf file of freddy and i am trying to print in multiple colors but everytime i try to slice, it does not work. with every setting it does not work.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
