### ISSUE TITLE
Nadeln 50mm Slice fehlgeschlagen

### ISSUE THREAD

**Issue by VkCura** [Ultimaker/Cura#17282]
### Cura Version

5.5.0

### Operating System

Windows 10 Pro

### Printer

Ultimaker-0082ca

### Describe your model

ja, mit Cura 4.13.1

### Add your .zip here ⬇️

[UMS5_Nadeln_50mm_0.1_AA0.25_v5.9.zip](https://github.com/Ultimaker/Cura/files/13321793/UMS5_Nadeln_50mm_0.1_AA0.25_v5.9.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
