### ISSUE TITLE
Building Roof

### ISSUE THREAD

**Issue by Down2GoblinTown** [Ultimaker/Cura#17307]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

neptune pro 3

### Describe your model

building roof

### Add your .zip here ⬇️

[EN3PRO_Ulvheim_Cottage_02.zip](https://github.com/Ultimaker/Cura/files/13336371/EN3PRO_Ulvheim_Cottage_02.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
The project would not slice as received.  I moved the model on the Cura build plate and it sliced.  You might also try rotating the model or changing the Initial Layer Height by a little bit.
This is a known bug so I'll mark this as a duplicate report and go ahead and close this.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5bcfbf38-7ebb-4def-b51f-98ac85aae713)
