### ISSUE TITLE
Silcing failed

### ISSUE THREAD

**Issue by hknorst** [Ultimaker/Cura#17305]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender 3S1

### Name abnormal settings

No

### Describe model location

Rotate 90º at center

### Describe your model

It's watertight and never sliced before.

### Add your .zip here ⬇️

[CE3S1_cover_rev_2.zip](https://github.com/Ultimaker/Cura/files/13335800/CE3S1_cover_rev_2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing this and the model doesn't seem to have any errors.
Try moving, rotating the model or channging the Initial Layer Height by a little bit.  That can sometimes fool this slicing bug.

I'll mark this as a duplicate and go ahead and close it as this bug has been previously reported.  I hope you understand.

That's a tough print.
![image](https://github.com/Ultimaker/Cura/assets/64202104/f1b2b2d8-cb9b-47b7-8c26-19777d68455f)
