### ISSUE TITLE
failed slicing

### ISSUE THREAD

**Issue by mksbrasil** [Ultimaker/Cura#17310]
### Cura Version

5.5

### Operating System

windows 11

### Printer

K1

### Describe model location

center

### Describe your model

Lions head lamp from Bright art collections

### Add your .zip here ⬇️

[0.00_N_100_10_ESUNWOOD_PLA_Lion_wall_lighting).zip](https://github.com/Ultimaker/Cura/files/13341563/0.00_N_100_10_ESUNWOOD_PLA_Lion_wall_lighting.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
