### ISSUE TITLE
Support Layer Thickness/Height feature request.

### ISSUE THREAD

**Issue by ioannisnousias** [Ultimaker/Cura#1731]
Hello devs,

I was wondering if you could add an option for changing the layer height/thickness for support structures, akin to the 'infill layer thickness' option. I find support structures to be too hard to remove at times, so I often set the 'support line width' to 0.2 or 0.1 on a 0.4 nozzle, and I think being able to, say, double the layer height might also help making it easier to break apart. That's of course in addition to helping speed up the prints a bit.

cheers,
Ioannis

**Comment by maukcc** [comment]
We were discussing this in #1292 also.
