### ISSUE TITLE
Face crash

### ISSUE THREAD

**Issue by grish57** [Ultimaker/Cura#17327]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Snapmaker 2 A350

### Name abnormal settings

fails with defaults also

### Describe model location

no

### Describe your model

First time using

### Add your .zip here ⬇️

[Face planter - 4462209.zip](https://github.com/Ultimaker/Cura/files/13366514/Face.planter.-.4462209.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is an often reported bug in 5.4.0.  It is a little better in 5.5.0.  There are three possible workarounds that can fool this bug.
Sometimes a combination of them is required.
- Move the model on the Cura build plate.
- Rotate the model in Cura.
- Change the initial layer height by a little bit (like from .20 to .23).

I'll mark this as a duplicate and go ahead and close this as the team is aware of this bug.  I hope you understand.
