### ISSUE TITLE
The image in cure does not correspond to the one supplied as stl.

### ISSUE THREAD

**Issue by Matorra** [Ultimaker/Cura#17328]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

Artllery Genius

### Reproduction steps

I try to laminate an stl file and it does not correspond to the original. I try to do it in Prusa_slicer and it does it correctly. This has happened to me several times with other files and sometimes it has been corrected but I don't know why.
![image](https://github.com/Ultimaker/Cura/assets/59731721/12ce3707-3257-4772-9b35-d3c4d94da6a3)
![image](https://github.com/Ultimaker/Cura/assets/59731721/c8f43ee5-e20d-433b-8bba-293414510c00)

### Actual results

I have NOT been able to get it to generate correctly.

### Expected results

![image](https://github.com/Ultimaker/Cura/assets/59731721/6ff92575-c9ee-4488-b870-742b2d2b37ec)

### Add your .zip and screenshots here ⬇️

[AG_remates Vinco-servo.zip](https://github.com/Ultimaker/Cura/files/13367540/AG_remates.Vinco-servo.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Go to the Mesh Fixes settings and turn off "Remove all Holes".

I'll go ahead and close this as it is a settings issue.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a598e684-c602-4aad-8620-45fd95af4957)

**Comment by Matorra** [comment]
Thank you very much, I will try it as soon as I can.Enviado desde mi Galaxy
-------- Mensaje original --------De: GregValiant ***@***.***> Fecha: 15/11/23  19:39  (GMT+01:00) Para: Ultimaker/Cura ***@***.***> Cc: Matorra ***@***.***>, Author ***@***.***> Asunto: Re: [Ultimaker/Cura] The image in cure does not correspond to the one supplied as stl. (Issue #17328) 
Thanks for the report.
Go to the Mesh Fixes settings and turn off "Remove all Holes".
I'll go ahead and close this as it is a settings issue.
