### ISSUE TITLE
Strange slicing problem @ X0, Y0

### ISSUE THREAD

**Issue by Smarti0101** [Ultimaker/Cura#17320]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 3 Pro

### Name abnormal settings

Model @ X:0 Y:0

### Describe model location

Model @ X:0 Y:0

### Describe your model

Some kind of Pokemon

### Add your .zip here ⬇️

[CE3PRO_psyduck_issue.zip](https://github.com/Ultimaker/Cura/files/13360745/CE3PRO_psyduck_issue.zip)

When I move the model on X-coordinates, I can print it. This happens just at X:0

**Comment by GregValiant** [comment]
Thanks for the report.
This is a known bug in 5.4.0 and it has continued into 5.5.0.  There are three workarounds that can often fool the bug.  You found one of them.
Move the model away from the Cura build plate midpoint.
Rotate the model
Change the Initial Layer Height by a little bit.

I'll mark this as a duplicate report and go ahead and close it as this behavior is well documented.  I hope you understand.
