### ISSUE TITLE
Slicing crash

### ISSUE THREAD

**Issue by Steff28** [Ultimaker/Cura#17333]
### Cura Version

5.5

### Operating System

Windows 11

### Printer

FLSUN V400

### Name abnormal settings

No abnormal settings

### Describe model location

Slicing fails in any direction

### Describe your model

Slicing is succesfull when using Simplify 3D or Prusaslicer

### Add your .zip here ⬇️

[FV_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13369919/FV_Christmas_Village.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model has been here numerous times.  I can get it to slice when I rotate it 90° CCW and make the Initial Layer Height 0.23.
I'll mark this as a duplicate report and go ahead an close it as it has been reported many times (see #16951 ).  I hope you understand.
I've played with this model a bit and I would suggest dropping your line width to 0.38 as some of the features are very fine.  A 0.3 nozzle would be advisable.
