### ISSUE TITLE
file failed to slice

### ISSUE THREAD

**Issue by jsilvius** [Ultimaker/Cura#17335]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality CR-10 S5

### Describe model location

no

### Describe your model

no

### Add your .zip here ⬇️

[CCR1_R5D4 Dome Single Print MKIII (with details) v2.zip](https://github.com/Ultimaker/Cura/files/13372073/CCR1_R5D4.Dome.Single.Print.MKIII.with.details.v2.zip)

**Comment by jsilvius** [comment]
Thank you Greg.
I've tried it on three different computers now, so I'm not sure what I'm
doing incorrectly.
I've been using the Cura software since v3, and have never had this issue
before.
I've never seen the " Make Overhangs Printable" setting. When I turned it
on, it asked for a maximum setting, do you have a suggestion?

Thank you again,
James


------
James Silvius

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
