### ISSUE TITLE
Cant slice a rosebear in cura

### ISSUE THREAD

**Issue by notfirsttimecoding** [Ultimaker/Cura#17343]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Anycubic Kobra

### Name abnormal settings

Not really, it never slices

### Describe model location

No it doesnt

### Describe your model

No its first time from internet

### Add your .zip here ⬇️

(
[AK_meda_V4_cura.zip](https://github.com/Ultimaker/Cura/files/13383142/AK_meda_V4_cura.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm not sure what to make of this.  I checked the model and it doesn't show any errors but I could not get your project to slice.
I tried my usual bag of tricks and Cura keeps throwing a slicing error.
I made my Ender 3 Pro the active printer, kept all your settings the way they were, and it sliced.
The Cura team will take a look.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e2cb4f1a-37d8-4d0e-8460-bdf6e3ba636f)

**Comment by notfirsttimecoding** [comment]
Dear Greg, you are welcome and thank you for your very fast reply and that you took a look at it. That is even more confusing! 

Patiently and curious waiting for a feedback. Cheers guys

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
