### ISSUE TITLE
Feature request: add layer view colour scheme to show speed

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1734]
S3D gives you the option of colouring the layer view based on the hot-end movement speed. It would be nice to have that capability in Cura.

**Comment by Ghostkeeper** [comment]
What colour scheme would be appropriate for Cura? Brighter is faster?

We already use brightness to indicate the active extruder though.

**Comment by fieldOfView** [comment]
I think @smartavionics suggests a third layerview mode: Line type, Material Color and Printing Speed. 

> We already use brightness to indicate the active extruder though.

That seems to be MIA since the new layerview work.

**Comment by smartavionics** [comment]
Hi Guys. Yes, I am suggesting a new layer view mode.  S3D uses a rainbow from blue (slow), green, orange, yellow to red (fast). I don't like that personally and would go for a much simpler two colour scheme such as dark blue for slow and light yellow or orange or even white for fast. Although, thinking about that, half way between blue and yellow would be greenish but even so, I am advocating a simple colour scheme. Tastes vary so unless you give the user the option to select the colours at the limits, someone is always going to moan about the colour choice!

**Comment by Ghostkeeper** [comment]
This was just rejected by our project manager because it was inactive for 3 months.

**Comment by smartavionics** [comment]
OK, I'm not going to do it myself and if nobody else is likely to then let's close this issue.

**Comment by smartavionics** [comment]
That sounds good. Even though the current layer view is quite pretty, it's still lacking a lot of functionality compared to other slicers. When I am working on cura  gcode issues, I currently view the gcode using the craftware slicer as a viewer. It's a little buggy but is so much better than cura for looking at gcode. Some useful stuff in there that could possibly be incorporated into cura. One of the very best features in craftware is the popup that displays all the info you need about the current line being printed (speed, extrusion rate, z, etc.) so you can scroll through the lines in the layer and see exactly what the gcode is doing at each line.

**Comment by ChrisTerBeke** [comment]
He's building line-by-line simulation support including nozzle position, colors per flow rate (and/or print speed), colors by layer height (handy for my adaptive layer height feature).

**Comment by diegopradogesto** [comment]
Yes, I started doing just the line by line view (#2713), but I had time enough for creating two new options for coloring the lines: Feedrate (aka. Speed) and Layer thickness. I will put some pictures and video.

**Comment by smartavionics** [comment]
Hi, that sounds good. If you haven't played with it yet, I really recommend using the craftware slicer to view some gcode as it has some nice features you may want to look into. They also have an option to colour by extrusion rate and, as I mention above, their pop-up that includes all the info about the current line is very good. I am looking forward to seeing what you have done. Cheers.

**Comment by diegopradogesto** [comment]
I was using CraftWare as an inspiration because I saw that you took some screenshots from that software. I didn't add the GCode information aside but it could be interesting.

**Comment by smartavionics** [comment]
The scrolling gcode display is useful for me as a developer but I doubt if most people would need it. The little popup that shows the info for the current line is definitely worth recreating if possible (or something equivalent).

**Comment by diegopradogesto** [comment]
This feature is implemented now in version 3.1
