### ISSUE TITLE
Cura not slicing

### ISSUE THREAD

**Issue by lukeslayers** [Ultimaker/Cura#17368]
### Cura Version

5.6 and 5.5

### Operating System

Windows 11 home

### Printer

FLSUN V400

### Describe your model

Chirstmas PLA village no supports needed but supports might accidently be turened on. 

### Add your .zip here ⬇️

Will not slice. I tired different profiles I had saved too. No luck. Thanks!
[FV_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13402056/FV_Christmas_Village.zip)
[FV_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13402064/FV_Christmas_Village.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That's a popular model and has showed up here in numerous reports.  I can get it to slice in 5.5 and 5.6 by playing with some settings and rotating the model.  I'll mark this report as another duplicate and close it as the team has that model.

The default Line Width for the FLSun Normal profile is .44 and that is too wide for this model.  A Line Width of .38 works without leaving gaps in the slice.  The best would be to print it with a 0.3 nozzle.  There are a lot of fine features on this that would benefit from a 0.3 line width.
![image](https://github.com/Ultimaker/Cura/assets/64202104/abcaad98-fd59-49b7-86d4-01164dca7dde)
