### ISSUE TITLE
Field next to "save to drive/removable" for saving as a specific name

### ISSUE THREAD

**Issue by PistolShrimpPimp** [Ultimaker/Cura#17376]
### Is your feature request related to a problem?

When working with models and when trying multiple print settings, it's a bit much to have to change the body name in fusion, export to file, or save to disk just to rename it when it saves to the removable drive.

### Describe the solution you'd like

A  simple text field in the box for "save to removable" that you can toggle to show or hide at all times within the box.
![image](https://github.com/Ultimaker/Cura/assets/86175850/f62de6e3-79e1-4639-8e43-985f121eeea7)
![image](https://github.com/Ultimaker/Cura/assets/86175850/ac70d53a-c6a2-4db5-8efa-071c7b417ff1)

### Describe alternatives you've considered

Other easier ways to change the name of the file without going through multiple steps.

### Affected users and/or printers

Users who will save multiple versions of the file with different names but may not save/export each one to their main disk.

**Comment by fieldOfView** [comment]
The file name is based on the "job name" which is already editable in the lower left of the UI:
![image](https://github.com/Ultimaker/Cura/assets/143551/eae5b76b-dadc-4053-914f-ffe331462b5c)
You can either click in the name there and edit it, or press the little pencil icon to select the text.
