### ISSUE TITLE
Deathstar Ikea Fado Fail

### ISSUE THREAD

**Issue by DerRetroBro** [Ultimaker/Cura#17371]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 V2

### Describe model location

roate makes it sliceable

### Describe your model

Deathstar Lamp

### Add your .zip here ⬇️

[DeathStar_IkeaFado17cm.zip](https://github.com/Ultimaker/Cura/files/13402992/DeathStar_IkeaFado17cm.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
