### ISSUE TITLE
boo

### ISSUE THREAD

**Issue by JMcski** [Ultimaker/Cura#17387]
### Cura Version

5.50

### Operating System

windows

### Printer

creality

### Reproduction steps

try to slic

### Actual results

fix

### Expected results

fix

### Add your .zip and screenshots here ⬇️

wft why is this my job

**Comment by Asterchades** [comment]
Without any information to go on, absolutely nothing can be done about... whatever it is you're experiencing. You haven't even mentioned what - if anything - has actually gone wrong.

As near as I can figure you're reporting that things are working. If your expected results are "fix" and your actual results are "fix" then it's doing exactly what you feel like it should.
