### ISSUE TITLE
Method XL

### ISSUE THREAD

**Issue by KellyERasmussen** [Ultimaker/Cura#17386]
### Cura Version

5.6.0-beta-1

### Operating System

Windows 10

### Printer

Method XL

### Reproduction steps

Can't add a Method XL Printer, even though beta-1 is supposed to be able to.

(Method XL uses numbers and letters for a local printer code.  Cura will only accept numbers.)

No options are availible to add via: "UltiMaker" or "Non".

Also, a Method XL can't be added via "Digital Factory".

### Actual results

Failure to add.

### Expected results

Blissful addition of a Method XL to Cura!

### Add your .zip and screenshots here ⬇️

![Capture, 1](https://github.com/Ultimaker/Cura/assets/151592518/f8f0fff7-0528-403d-92f7-825c4a3a4014)
![Capture, 2](https://github.com/Ultimaker/Cura/assets/151592518/42b5580a-ca43-484b-b6f7-8e05e9696c56)
![Capture, 3](https://github.com/Ultimaker/Cura/assets/151592518/b0ea9b50-019e-4251-a36c-9c3e6d3465dc)
![Capture, 4](https://github.com/Ultimaker/Cura/assets/151592518/fe583091-7bc0-42db-af52-438d90def312)

**Comment by MariMakes** [comment]
Hey @KellyERasmussen,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The Method printers can be found in the Local/Non-Networked printers
![image](https://github.com/Ultimaker/Cura/assets/40423138/e1374761-aefa-4e0f-bc56-7dc6dd9cfcf8)

For now, only USB printing is available, we hope to include Networked printing in later releases.
I'll make sure to let the team know to update the documentation to make the printers easier to find. 

Can you try to let us know if you were able to find the printer and start a printjob?
Thank you 🙏
