### ISSUE TITLE
Unable to enter values when moving by small amounts

### ISSUE THREAD

**Issue by jcosmo** [Ultimaker/Cura#1738]
This appears to be a new problem in 2.5, it worked fine in 2.4.

When entering an absolute value for moving an object on the build plate, for example entering -0.1, Cura is resetting the value to 0.  It seems to round it in some fashion.  Entering -1 works.  Dragging the model using the mouse controls allows me to get -0.1xxx

**Comment by nallath** [comment]
That's odd. As far as I know nothing in that bit of code was changed. 
It seems that entering any value below 0 is broken.
