### ISSUE TITLE
[5.6.0-beta.1] Support Z-distance feedback: Normal support and Interface support is being placed incorrectly

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#17392]
### Cura Version

5.6.0-beta.1

### Operating System

win10

### Printer

Custom fff

### Reproduction steps

See project.

Please also see my other reports submitted at the same time, some are related.

### Actual results

Normal support is being placed around and on top of support interface. This also happens with support floor turned off and support brim turned off. Bed adhesion set to none.

### Expected results

Normal support and interface to be placed correctly

### Add your .zip and screenshots here ⬇️

[Normal vs interface glitch.3mf.zip](https://github.com/Ultimaker/Cura/files/13424500/Normal.vs.interface.glitch.3mf.zip)
![Normal vs interface glitch2](https://github.com/Ultimaker/Cura/assets/32172100/2b68d524-5611-4661-a35f-7f90c2214d31)
![Normal vs interface glitch](https://github.com/Ultimaker/Cura/assets/32172100/394115ff-6685-4e2f-b6b1-16d58d3c9b21)
(Reducing Support horizontal expansion removes the extra normal support lines on layer 0 but not the ones resting on top of the interface. I had set it high to make test-prints easier to separate)

**Comment by Vandresc** [comment]
Hmm, I cannot seem to reproduce the support on the interface when the Z distance is 0.21. We will have a release soon, could you please re-check this in the stable? Thank you

**Comment by printingotb** [comment]
Yeah it still happens in 5.6.0. (you have to change the Z-distance in the project from 0.2 to anything between 0.21 and 0.39)

**Comment by Vandresc** [comment]
I made a ticket for the backlog, Devs see CURA-11423 for our internal reference.

**Comment by casperlamboo** [comment]
issue should be solved here https://github.com/Ultimaker/CuraEngine/pull/2049, the fix will be in our next release, 5.7, scheduled to be released in a few weeks.

**Comment by casperlamboo** [comment]
solves https://github.com/Ultimaker/Cura/issues/17392
