### ISSUE TITLE
Project fails to slice

### ISSUE THREAD

**Issue by johntdyer** [Ultimaker/Cura#17398]
### Cura Version

5.5.1

### Operating System

OSX Sonoma

### Printer

cr-10s v2

### Describe your model

one wheel stand

### Add your .zip here ⬇️

[CCR10SPRO_FFV5.0-ExtraFast-028(1).3mf.zip](https://github.com/Ultimaker/Cura/files/13429860/CCR10SPRO_FFV5.0-ExtraFast-028.1.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
After repairing the model with MS 3D Builder it sliced.
I'll remove the bug label and close this since it is a model problem.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7dd256b9-1872-4fca-b0da-8d65a7543168)
