### ISSUE TITLE
curaEngine support should have a  Sealing surface

### ISSUE THREAD

**Issue by zifengtayu** [Ultimaker/Cura#174]
the support should have a  Sealing surface Contact with the print object surface
![img_20150723_150115](https://cloud.githubusercontent.com/assets/7849639/8844846/461b3d2a-314c-11e5-8efd-840959cc73f7.jpg)
![img_20150723_150128](https://cloud.githubusercontent.com/assets/7849639/8844850/4648995a-314c-11e5-8f92-81b44006ccc6.jpg)
![img_20150723_150136](https://cloud.githubusercontent.com/assets/7849639/8844847/4620c9d4-314c-11e5-9a22-fb33179fd288.jpg)
![img_20150723_150151](https://cloud.githubusercontent.com/assets/7849639/8844848/462591c6-314c-11e5-9b1f-e95c09985aed.jpg)
![img_20150723_145956](https://cloud.githubusercontent.com/assets/7849639/8844849/46443b3a-314c-11e5-8b10-1b75afce8869.jpg)
![img_20150723_150016](https://cloud.githubusercontent.com/assets/7849639/8844851/46684ec6-314c-11e5-9e33-f7c2fe35d4b5.jpg)
![Uploading IMG_20150723_150047.jpg…]

**Comment by BagelOrb** [comment]
It is unclear what these pictures are pictures of. You should give them a name, description or say why you uploaded each picture the next time.

However, this feature has already been implemented. Will be in the release of October.
