### ISSUE TITLE
Échec de découpe

### ISSUE THREAD

**Issue by LaurentN1305** [Ultimaker/Cura#17400]
### Cura Version

5.5.5

### Operating System

Windows 11

### Printer

Artillery Genius

### Describe your model

1ere decoupe du modele

### Add your .zip here ⬇️

[RavenLeft.zip](https://github.com/Ultimaker/Cura/files/13431639/RavenLeft.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The model has errors in it that is keeping it from slicing.  After repairing the model with MS 3D Builder it did slice.

I'll remove the bug label and go ahead and close this as it is a model problem.  L hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b53cc739-e4be-48c2-af8a-a99932196f54)
