### ISSUE TITLE
K1 Max profile please!

### ISSUE THREAD

**Issue by dandontknow1** [Ultimaker/Cura#17417]
### Is your feature request related to a problem?

There's no Cura profile for Creality's latest and greatest?! i mean, what's going on with that?!

### Describe the solution you'd like

A cura profile for the K1 max which can utilise all its features.

### Describe alternatives you've considered

Creality Print. This made me sad.

### Affected users and/or printers

I should imagine many people would benefit from this!

**Comment by Changowen** [comment]
see this: https://www.youtube.com/watch?v=Vua0OfaRg2g

**Comment by dandontknow1** [comment]
I think most of us would like a proper native profile in Cura like with other printers.

**Comment by itay-grudev** [comment]
Could one of you please take a look at #17871 and verify independently that the provided printer definition works as expected.

Also please note that Cura won't enable the side-fan by default.

**Comment by dandontknow1** [comment]
Nice one. If I knew how to try test code, I would but I'm not too clever with GitHub and coding. Sorry.

**Comment by cadbob** [comment]
i used to love using cura but since i got the k1max , i have had to use orca, orca is good but was so used to cura and would like to use again.
