### ISSUE TITLE
Brim not generated when Supports used...

### ISSUE THREAD

**Issue by Happydace** [Ultimaker/Cura#1742]
When supports are used, the brim is only generated around the base of the support, not the whole model...

**Comment by nallath** [comment]
Could you provide us with a project file?

**Comment by Happydace** [comment]
Sorry for delay nallath...
I went back to this and checked a few things and it turned out to be an issue with the stl file...  It was sectioned in Meshmixer using a Plane Cut and appeared to have a perfectly flat bottom. It looks like there was something sticking down from the bottom, even though it was invisible...

Re-worked it in Meshmixer and it was fine the second time around...

Sorry for wasting your time..

H.D.
