### ISSUE TITLE
Calibration cube labels X/Y are swapped.

### ISSUE THREAD

**Issue by maXe72** [Ultimaker/Cura#17433]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Creality Ender S1 Pro / Clipper

### Reproduction steps

1. Menü Settings -> Part for Calibration -> Add a calibration Cube

### Actual results

The sliced result is a 20mm calibration cube, but the model is rotated by 90 degree. 
So the X and Y axis letters on the sliced and printed cube are swaped against each other.
If you measure the X-Axis labed side of the cube printed you are actually measuring the Y-Axis printed and vice versa.

### Expected results

The X labeled side should represent the X-Axis printed.
The Y labeled side should represent the Y-Axis printed.

### Add your .zip and screenshots here ⬇️

![grafik](https://github.com/Ultimaker/Cura/assets/121335605/7522b8f8-609d-405a-9100-1689e31282cb)

**Comment by 5axes** [comment]
We could also consider that the  X represent the length of the Axis we want to calibrate.
![image](https://github.com/Ultimaker/Cura/assets/11015345/5b7900e8-5b3c-439b-a8f0-39d5c501aff0)

**Comment by maXe72** [comment]
Yes, but it is counterintuitve and oposide way of measurement  in comparision to the z-axis

**Comment by 5axes** [comment]
Yes, but when you measure the Z-Axis You don't see the Z mark and you don't care as you know that it's the Z direction.  Anyway it's not a bug it's a feature and it will not change.
