### ISSUE TITLE
Slicing Failed on FLSun Super Racer

### ISSUE THREAD

**Issue by EduCueto** [Ultimaker/Cura#17447]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

FLSun Super Racer

### Describe your model

Part of a Tower from PrintableScenery

### Add your .zip here ⬇️

[FSR_Tower-of-Insanity-Lv1-Bottom-v1.1.zip](https://github.com/Ultimaker/Cura/files/13473180/FSR_Tower-of-Insanity-Lv1-Bottom-v1.1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
