### ISSUE TITLE
Slicing Failure no reason why given

### ISSUE THREAD

**Issue by Mike-Greany** [Ultimaker/Cura#17443]
### Cura Version

5.3.1

### Operating System

Windows 11 Home 22H2

### Printer

Ender 3 Max Neo

### Name abnormal settings

no

### Describe model location

Center of build place rotation does not change

### Describe your model

Have not been able to slice in Cura, was able to slice in Creality Slicer 4.8.2

### Add your .zip here ⬇️

[CE3MAX_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13469472/CE3MAX_Christmas_Village.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
