### ISSUE TITLE
Failed to Slice

### ISSUE THREAD

**Issue by MartinMade** [Ultimaker/Cura#17440]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality Ender 3

### Name abnormal settings

n/a

### Describe model location

No

### Describe your model

Recent download

### Add your .zip here ⬇️

Tried Mesh Fix, no longer getting the error message, but still won't finish slicing. 
[CE3E3V2_Christmas_Village.zip](https://github.com/Ultimaker/Cura/files/13468332/CE3E3V2_Christmas_Village.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That's a popular model and has showed up here several times and all with the same slicing problem.
I've gotten good at this one.  It will slice if I use Cura 5.2.2 or 4.13.1.  The "Petulant Child" bug in Cura 5.4 to 5.6beta will not allow those versions to slice this model.

I'll  mark this as a duplicate report and go ahead and close this ticket as this model is well known to cause heartburn in the newer Cura versions.

If I were to print this I'd go with a 0.3 nozzle.  There are features that a 0.4 is just too wide for.  A downside is that at .12 layer height and .24 infill layer height the print time goes from 18 hours to 23 hours.

This is in 5.2.2 which you can get [HERE](https://github.com/Ultimaker/Cura/releases).  Scroll down the page and click on the "Assets" button.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c3654777-02b3-4e1d-9c74-c9495ce33f9f)
