### ISSUE TITLE
Slicing Failed (printing a d12 die)

### ISSUE THREAD

**Issue by Tynnin** [Ultimaker/Cura#17464]
### Cura Version

5.4.0-beta 1

### Operating System

Windows 11

### Printer

Magician Max

### Name abnormal settings

No settings have been changed

### Describe model location

center of buildplate (tried other locations and rotating, did not help)

### Describe your model

a specialty d12 die

### Add your .zip here ⬇️

[Uploading CFFFP_d12_solid.zip…]()

**Comment by GregValiant** [comment]
Thanks for the report.
That's a bad download link.  All it does is bounce back to this page.
