### ISSUE TITLE
slicing failed on certain orientations

### ISSUE THREAD

**Issue by giocomputerer** [Ultimaker/Cura#17479]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Tronxy xy2 yes it was selected

### Describe model location

any location on the bad but only in one orientation

### Describe your model

its a part of darth vader helmet

### Add your .zip here ⬇️

[file.zip](https://github.com/Ultimaker/Cura/files/13504388/file.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
