### ISSUE TITLE
Why does my Slicer Fail

### ISSUE THREAD

**Issue by JustAMando** [Ultimaker/Cura#17485]
### Cura Version

5.6.0

### Operating System

Windows 10/with updates

### Printer

Anycubic kobra max

### Name abnormal settings

only enable support and wall count is 3

### Describe model location

No

### Describe your model

Jango fett helmet/Boba fett helmet/Mandalorian Helmet

### Add your .zip here ⬇️

[Helm.zip](https://github.com/Ultimaker/Cura/files/13517051/Helm.zip)

when I slice it does not allow it to slice. it has an unexpecting error

**Comment by GregValiant** [comment]
Thanks for the report.
There is a bug in Cura that keeps some models from slicing.  It's been worked on but it is still present in 5.6.0.
There are a couple of things you can try.

- Move the model in Cura.
- Rotate the model in Cura.
- Change the Initial Layer Height by a little bit.
- Turn off "Print Thin Walls"
- Turn off "Optimize Wall Printing Order".

I'll mark this as a duplicate and go ahead and close this as the Cura team has a lot of examples of this behavior.  I hope you understand.

Your Initial Layer Print Temperature is "0" and it won't print at all like that.
Here is your 5 day 17 hour print in Cura 5.6.  I didn't make any changes to you settings and it took a good while to slice.
If I was going to print this I'd go with a .6 nozzle at .3 layer height and up the outer wall speed to 70.  You could also set the Support Infill Layer Height to 2X layer height and it would only print support every other layer.  It's still a 29 hour print with my settings, but that's a heck of a lot quicker than 137 hours.
![image](https://github.com/Ultimaker/Cura/assets/64202104/3fdafd51-eab7-4027-b0b0-0674d0781bde)
