### ISSUE TITLE
Unknown slicing failed

### ISSUE THREAD

**Issue by Tom-Neverwinter** [Ultimaker/Cura#17481]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Ender 3 S1 Pro

### Describe model location

auto arrange center

### Describe your model

Deck box

### Add your .zip here ⬇️

[CE3S1PRO_Zig_Lid.zip](https://github.com/Ultimaker/Cura/files/13509914/CE3S1PRO_Zig_Lid.zip)

**Comment by 5axes** [comment]
Don't need Support. 
![image](https://github.com/Ultimaker/Cura/assets/11015345/63fdf044-529d-44e5-bd9e-1e7397c12a56)
