### ISSUE TITLE
bug by slice. 5.6.0

### ISSUE THREAD

**Issue by tris-pax** [Ultimaker/Cura#17490]
### Cura Version

5.6.2

### Operating System

Win 11

### Printer

creality ender 3 s1 pro

### Describe your model

a 3 part of a dragon 

### Add your .zip here ⬇️

[CE3S1PRO_part2 map.zip](https://github.com/Ultimaker/Cura/files/13531746/CE3S1PRO_part2.map.zip)

**Comment by 5axes** [comment]
An other Windows 11 Issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
