### ISSUE TITLE
Name of file is lost when save gcode

### ISSUE THREAD

**Issue by jltrma** [Ultimaker/Cura#1749]

**Comment by fieldOfView** [comment]
Please provide more details.
I think this is a duplicate of https://github.com/Ultimaker/Cura/issues/1703, but without details I can not be sure.

**Comment by jltrma** [comment]
Yes is the same

Sorry

 

 

De: Aldo Hoeben [mailto:notifications@github.com] 
Enviado el: jueves, 27 de abril de 2017 8:23
Para: Ultimaker/Cura <Cura@noreply.github.com>
CC: jltrma <jlmtellado@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Ultimaker/Cura] Name of file is lost when save gcode (#1749)

 

Please provide more details.
I think this is a duplicate of #1703 <https://github.com/Ultimaker/Cura/issues/1703> , but without details I can not be sure.
