### ISSUE TITLE
Couldn't start EnginePlugin: CuraEngineTiledInfill Operating system is blocking it (antivirus?)

### ISSUE THREAD

**Issue by Sherman-c** [Ultimaker/Cura#17515]
### Cura Version

5.6.0

### Operating System

Window 10

### Printer

Creality Ender 3 V2

### Name abnormal settings

NA

### Describe model location

NA

### Describe your model

Yes, works well on 5.4.0

### Add your .zip here ⬇️

[CE3E3V2_star_base.zip](https://github.com/Ultimaker/Cura/files/13543629/CE3E3V2_star_base.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
