### ISSUE TITLE
First layer too fast for some shapes

### ISSUE THREAD

**Issue by vtechev** [Ultimaker/Cura#17513]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Snapmaker Artisan

### Reproduction steps

Apologies if this is a duplicate. I'm not sure what the right terminology is for this, so I may have missed another report.

Print `topper_bow_flat.stl` from [this puzzle box](https://www.thingiverse.com/thing:5177963)

### Actual results

Travel speed for the initial layer is way faster than other shapes using the same settings. Bed adhesion is poor and the part frequently fails.

### Expected results

Travel speed and bed adhesion consistent with other parts.

### Add your .zip and screenshots here ⬇️

[too_fast.zip](https://github.com/Ultimaker/Cura/files/13538559/too_fast.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I don't have the definition files for your printer so the only thing I get from the project file are the model.
Try setting the "Flow Equalization Ration" to 0.  I've been seeing some ridiculous speeds being generated when that is at 100%.  I think it is the cause of high speeds as it adjusts the speed to keep the flow at a constant rate.  If Cura wants a narrow line width extrusion the speed goes up and if a line is wide then the speed goes down.

I'll mark this as a duplicate report for the Cura team.

**Comment by vtechev** [comment]
Thanks for the suggestion and the compelling explanation.  I've just tried it out and speeds seem to be much more reasonable now, the initial layer looks much better too.
