### ISSUE TITLE
Slicing fails with tree supports enabled

### ISSUE THREAD

**Issue by meismyusername** [Ultimaker/Cura#17526]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

VZBot VZ330

### Name abnormal settings

Slicing breaks when enabling tree supports

### Describe model location

2 of model, middle of build plate, position does not seem to change result

### Describe your model

VZBot frame corner brace

### Add your .zip here ⬇️

Hey, not sure what's going on with this one. I'm using pretty much default settings in this profile, and while I can slice with normal supports, tree supports is causing the slicer to error out with "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

[V330_Frame_Brace.zip](https://github.com/Ultimaker/Cura/files/13557048/V330_Frame_Brace.zip)

**Comment by 5axes** [comment]
No issue 

![image](https://github.com/Ultimaker/Cura/assets/11015345/0e97374c-c83a-4a46-841c-586975eda28b)

**Comment by deBugger-** [comment]
Avoid this combination. Tree support and vertical round hole in your Model.
Use normal support instead.
As shown switch from normal to tree support will lead to a cura issue.
![cura5 6 x](https://github.com/Ultimaker/Cura/assets/7442971/60117f50-3a07-4015-951c-8b67c5a409f2)
![curaBug](https://github.com/Ultimaker/Cura/assets/7442971/5dac30e6-1d73-4c5c-8c81-da1943b5561c)

**Comment by speedyrudolf** [comment]
same issue with Cura 5.6.0
no matter what I do, tree supports fail, normal supports work. I have this issue with all models I tried.
