### ISSUE TITLE
cura 2.5, profile seems to save incomplete

### ISSUE THREAD

**Issue by UltiArjan** [Ultimaker/Cura#1753]
![profilesavecura](https://cloud.githubusercontent.com/assets/9219556/25526168/afd49fc8-2c12-11e7-872e-6de69cb874af.png)
I've seen it before, but just tried to save a profile again, and after I save I still get a "star" behind the profile name, indicating there's been a change..... which is not posible as I just saved it....

enclosed the project file...
[MFU_LEGOwheel-v02.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/964163/MFU_LEGOwheel-v02.curaproject.3mf.zip)

**Comment by Ghostkeeper** [comment]
Can't test this in master, since loading project files just broke yesterday :(
I'm not able to reproduce this by reproducing the settings as can be seen in the 3MF file with a text editor. I must be missing something. I guess we'll re-test once loading project files is repaired.

**Comment by BagelOrb** [comment]
@Ghostkeeper please retest

**Comment by Ghostkeeper** [comment]
We won't consider this a bug then because the definition file contains syntax errors. Please correct that definition before using it in Cura!
