### ISSUE TITLE
error al cambiar a mayor tamaño

### ISSUE THREAD

**Issue by JOANMIDAF** [Ultimaker/Cura#17540]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

elegoo neptune 2s

### Name abnormal settings

configuraciones correctas,todos los demas modelos se cortan sin error

### Describe model location

se corta si lo giro 90 grados

### Describe your model

si

### Add your .zip here ⬇️

[EN2S_Bottom.zip](https://github.com/Ultimaker/Cura/files/13589665/EN2S_Bottom.zip)

**Comment by 5axes** [comment]
Strange .. anyway don't need support to print this part .

![image](https://github.com/Ultimaker/Cura/assets/11015345/4dac891b-b8ce-416d-b8a3-e70547ee6969)

**Comment by 5axes** [comment]
And it's very strange to use a Flow at 75%  ??? you should calibrate the E Step of your printer.
![image](https://github.com/Ultimaker/Cura/assets/11015345/049827fe-13d7-4afc-8099-24fb0bc94a25)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
