### ISSUE TITLE
File crashed while slicing

### ISSUE THREAD

**Issue by CIPuyleart** [Ultimaker/Cura#17543]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ultimaker S3

### Describe your model

STL exported from Shapr3D

### Add your .zip here ⬇️

[UMS3_Console No Top Holes.zip](https://github.com/Ultimaker/Cura/files/13591827/UMS3_Console.No.Top.Holes.zip)
this is slicing and printing fine in Cura 5.4.0

**Comment by 5axes** [comment]
No issue on Windows 10

![image](https://github.com/Ultimaker/Cura/assets/11015345/f62e4c9c-797f-48e1-9778-479540eeb143)

Certainly  the same issue as every report concerning Cura 5.6 and Windows 11

**Comment by CIPuyleart** [comment]
the only extra step done on this file was rotating it 180 degrees about Y axis prior to slicing. Just tested with it in original orientation and still crashes.

**Comment by 5axes** [comment]
ok same issue not related to windows 11

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
