### ISSUE TITLE
Slising Failed

### ISSUE THREAD

**Issue by Sei7RaiRyu** [Ultimaker/Cura#17561]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Creality Ender 3

### Describe your model

The character Shogun Raiden from the game Genshin Impact

### Add your .zip here ⬇️

[CE3E3V2_Raiden Ei.zip](https://github.com/Ultimaker/Cura/files/13617569/CE3E3V2_Raiden.Ei.zip)

**Comment by 5axes** [comment]
Invalid Model.
![image](https://github.com/Ultimaker/Cura/assets/11015345/588fe9a9-9fc8-4353-8efd-c1f3a529cad5)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
