### ISSUE TITLE
slicing error with Cura v 5.6.0 

### ISSUE THREAD

**Issue by dbyy** [Ultimaker/Cura#17572]
### Cura Version

5.6.0

### Operating System

Linux Mint v20.3

### Printer

Ender 3

### Name abnormal settings

no

### Describe model location

center of build plate

### Describe your model

no, yes, yes

### Add your .zip here ⬇️

[AirTagHolder_BugReport.zip](https://github.com/Ultimaker/Cura/files/13624226/AirTagHolder_BugReport.zip)
[AirTagHolder_BugReport.zip](https://github.com/Ultimaker/Cura/files/13624232/AirTagHolder_BugReport.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0

**Comment by dbyy** [comment]
Hello, 
as you suggested (HellAholic), I downloaded Cura 5.7 and sliced the model again.
Unfortunately its still reporting "Slicing failed".
I'm wondering whether it has something to do with my settings of Cura?
Regards
