### ISSUE TITLE
Failed slicing with tree support - success after changing model orientation - Tree supports

### ISSUE THREAD

**Issue by otede** [Ultimaker/Cura#17575]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Custom FFF

### Name abnormal settings

The model slices with default DRAFT profile. Changes - compare yourself. Tree support is most probable culprit - the model slices with Regular.

### Describe model location

Yes, one location slices, the other doesn't. See the attached project files.

### Describe your model

Yes, one location slices, the other doesn't. See the attached project files.

### Add your .zip here ⬇️

High CPU usage around the middle of the process, then error after few seconds.
[LumePlus vs C5_6 slicing error.zip](https://github.com/Ultimaker/Cura/files/13624567/LumePlus.vs.C5_6.slicing.error.zip)
![irfan_20231209_163809](https://github.com/Ultimaker/Cura/assets/5107909/5e306942-0770-4602-bb48-2a2b1fe35c85)
![irfan_20231209_163805](https://github.com/Ultimaker/Cura/assets/5107909/b59b1c0d-3c31-4101-b713-169021bf881a)
![irfan_20231209_163748](https://github.com/Ultimaker/Cura/assets/5107909/bdd70f0e-4df8-4e34-9eb1-e953aa1c1a4f)

Prior to slicing the model has been scaled up proportionally by entering 120 mm for the Z size.

**Comment by otede** [comment]
A non-standard printer
https://lumeplus.wixsite.com/lume

**Comment by 5axes** [comment]
An other Tree Support issue.. Duplicate https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

Slices, if the model is at the "right" place and we have enought distance to create the support.
![image](https://github.com/Ultimaker/Cura/assets/11015345/c58a0cf7-37ba-4507-8e01-de2189773156)

**Comment by Vandresc** [comment]
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm!
(https://github.com/Ultimaker/CuraEngine/pull/2002)
 

I'll close this issue since it's resolved, a fix should be available with the upcoming release. 

Thanks again, and please let us know if you run into any other issues 💪

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0

**Comment by otede** [comment]
I have re-opened the mech Delta_40mm_Autorifle_1 N04 projekt slicing error - DOESNT SLICE.3mf project and it indeed does slice. Well done, Cura Team!
![irfan_20240616_195129](https://github.com/Ultimaker/Cura/assets/5107909/757e0c20-bcad-472b-9f8f-a2a5cbe5ee5d)
