### ISSUE TITLE
Skirt ran not expected

### ISSUE THREAD

**Issue by npk98** [Ultimaker/Cura#17586]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

ender 3 v2  with Sonic pad

### Reproduction steps

Skirt ran few rounds, then started to print main object, before first layer completed, it went to continue with skirt.

Skirt is supposed to complete printing skirt BEFORE printing main object...sliced two object, same behavior

Using Ender 3 v2 with Sonic pad 

### Actual results

main items well printed

### Expected results

that Skirt is completed before printing main object

### Add your .zip and screenshots here ⬇️

nil

**Comment by Asterchades** [comment]
Without a project file I can only guess what's happening, but it sounds like you've just discovered a new feature from 5.4. Specifically, 5.4 introduced a `Skirt Height` setting - this defaults to three (3) and is intended to make the skirt easier to remove. As Cura will avoid backtracking layers (too much risk of the nozzle colliding with anything) these extra layers are simply printed at the start of their respective model layers.

Note that fixes were made to this feature with Cura 5.5 to prevent it from attempting to occupy the same space as the model you're printing, though this should only affect a small minority of models.

Setting this to one (1) will restore the old functionality.
