### ISSUE TITLE
Cura Slicer crashes while attempting to slice

### ISSUE THREAD

**Issue by zumaster20** [Ultimaker/Cura#17585]
### Cura Version

5.6.0, 5.4.0

### Operating System

windows 10

### Printer

Ender 3

### Name abnormal settings

no, model doesn't slice anyway

### Describe model location

model placed at the center of buildplate

### Describe your model

any model does not slice

### Add your .zip here ⬇️

weird part is the fact, that previously models were slicing normally with like 30% chance of failure (crash like now), then every second attempt to slice began to cause crash, now I can not slice it at all. I checked logs, and error is  

[35m2023-12-10 14:31:15,834[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.834] [info] Progress: support accomplished in 0.013s[0m
[35m2023-12-10 14:31:15,834[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.834] [info] Starting export...[0m
[35m2023-12-10 14:31:15,850[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Progress: export accomplished in 0.016s[0m
[35m2023-12-10 14:31:15,851[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Sending 21 layers.[0m
[35m2023-12-10 14:31:15,851[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Total time elapsed 0.033s[0m
[35m2023-12-10 14:31:15,851[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [0m
[35m2023-12-10 14:31:15,852[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Print time (s): 321[0m
[35m2023-12-10 14:31:15,852[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Print time (hr|min|s): 0h 5m 21s[0m
[35m2023-12-10 14:31:15,852[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:15.851] [info] Filament (mm^3): 198[0m

**_"[35m2023-12-10 14:31:16,114[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:16.115] [info] Closing connection.[0m
 [35m2023-12-10 14:31:16,326[0m - [33mWARNING[0m - [37m[MainThread] UM.Backend.Backend._onSocketError [267]: Unhandled socket error ErrorCode.ReceiveFailedError[0m"_**
 
[35m2023-12-10 14:31:16,327[0m - [36mDEBUG[0m - [37m[MainThread] UM.Backend.Backend._createSocket [294]: Previous socket existed. Closing that first.[0m
[35m2023-12-10 14:31:16,327[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [0m
[35m2023-12-10 14:31:16,328[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] Cura_SteamEngine version 5.6.0[0m
[35m2023-12-10 14:31:16,328[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] Copyright (C) 2023 Ultimaker[0m
[35m2023-12-10 14:31:16,329[0m - [36mDEBUG[0m - [37m[MainThread] CuraEngineBackend.CuraEngineBackend._terminate [410]: Attempting to kill the engine process[0m
[35m2023-12-10 14:31:16,329[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [0m
[35m2023-12-10 14:31:16,330[0m - [36mDEBUG[0m - [37m[MainThread] CuraEngineBackend.CuraEngineBackend._terminate [416]: Killing engine process[0m
[35m2023-12-10 14:31:16,330[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] This program is free software: you can redistribute it and/or modify[0m
[35m2023-12-10 14:31:16,331[0m - [36mDEBUG[0m - [37m[MainThread] CuraEngineBackend.CuraEngineBackend._terminate [419]: Engine process is killed. Received return code 0[0m
[35m2023-12-10 14:31:16,331[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] it under the terms of the GNU Affero General Public License as published by[0m
[35m2023-12-10 14:31:16,331[0m - [36mDEBUG[0m - [37m[MainThread] UM.Backend.Backend._createSocket [294]: Previous socket existed. Closing that first.[0m
[35m2023-12-10 14:31:16,332[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] the Free Software Foundation, either version 3 of the License, or[0m
[35m2023-12-10 14:31:16,332[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] (at your option) any later version.[0m
[35m2023-12-10 14:31:16,333[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [0m
[35m2023-12-10 14:31:16,333[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] This program is distributed in the hope that it will be useful,[0m
[35m2023-12-10 14:31:16,334[0m - [33mWARNING[0m - [37m[MainThread] CuraEngineBackend.CuraEngineBackend._onSocketError [689]: A socket error caused the connection to be reset[0m
[35m2023-12-10 14:31:16,334[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of[0m
[35m2023-12-10 14:31:16,335[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the[0m
[35m2023-12-10 14:31:16,335[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] GNU Affero General Public License for more details.[0m
[35m2023-12-10 14:31:16,336[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [0m
[35m2023-12-10 14:31:16,337[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] You should have received a copy of the GNU Affero General Public License[0m
[35m2023-12-10 14:31:16,337[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.[0m
[35m2023-12-10 14:31:16,338[0m - [36mDEBUG[0m - [37m[MainThread] UM.Backend.Backend._logSocketState [232]: Socket state changed to Listening[0m
[35m2023-12-10 14:31:16,341[0m - [32mINFO[0m - [37m[MainThread] UM.Backend.Backend.startEngine [96]: Started engine process: C:\Program Files\UltiMaker Cura 5.6.0\CuraEngine.exe[0m
[35m2023-12-10 14:31:16,342[0m - [36mDEBUG[0m - [37m[MainThread] UM.Backend.Backend._backendLog [140]: [Backend] Calling engine with: ['C:\\Program Files\\UltiMaker Cura 5.6.0\\CuraEngine.exe', 'connect', '127.0.0.1:49674', ''][0m
[35m2023-12-10 14:31:16,371[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:16.371] [info] Connecting to 127.0.0.1:49674[0m
[35m2023-12-10 14:31:16,474[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [140]: [Backend] [2023-12-10 14:31:16.474] [info] Connected to 127.0.0.1:49674[0m

 
 
i think its 4 lines i made bold
 everything before seems pretty right to me, Im getting print time, mass of printed model and all this stuff, and then this error occurs, and cura just stop responding
 
 
[selector_project_issue.zip](https://github.com/Ultimaker/Cura/files/13627536/selector_project_issue.zip)

**Comment by zumaster20** [comment]
also everything works fine if Im doing it not on my pc, but in my laptop
pc:
gpu AMD Radeon RX5700XT
cpu AMD Ryzen 7 3600
mb ASRock SteelLegend B450M
16gb ddr4 RAM
os Win10

laptop: 
cpu Intel I5-4200
os Win10

**Comment by 5axes** [comment]
No issue for me 
![image](https://github.com/Ultimaker/Cura/assets/11015345/5e8350c4-fd4d-4f7c-973a-aa2234d4b3aa)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
