### ISSUE TITLE
include ALYA 3D printer in source code

### ISSUE THREAD

**Issue by nbennett1978** [Ultimaker/Cura#1759]
Hi,
we are manufacturer of ALYA, a FFF printer for kids and youngsters. I'd like to ask to include the printer definitions into the source code. I tried to do that myself, but couldn't due to user permissions.
[alya3dp.def.json.txt](https://github.com/Ultimaker/Cura/files/966412/alya3dp.def.json.txt)

**Comment by nbennett1978** [comment]
We used legacy cura (15.04) up until recently. The printer definition file i sent you was created with the generator link on cura's github repo- what exactly did you mean with your recommendation to update?

**Comment by fieldOfView** [comment]
This is fixed now that #1761 has been merged. The Alya 3d printer will show up in the list of printers when adding a new printer in version 2.6 and up.
