### ISSUE TITLE
Slicing failed on mirror image of a piece I just printed.

### ISSUE THREAD

**Issue by DowntownTrainer** [Ultimaker/Cura#17598]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Custom CR10 profile

### Name abnormal settings

First time getting a slice fail, using same settings as I normally use

### Describe model location

Still won't slice

### Describe your model

Just downloaded it from Thingiverse.com thing:6306571 part 2 of 2 file

### Add your .zip here ⬇️

The other side printed fine, this is a mirror image of an angel wing christmas ornament.  First time getting a slicer failure
[Wing_Ornament_-_Part_2_of_2a.zip](https://github.com/Ultimaker/Cura/files/13629347/Wing_Ornament_-_Part_2_of_2a.zip)

**Comment by 5axes** [comment]
Rotation of the part of 90° should temporary solved your issue.
![image](https://github.com/Ultimaker/Cura/assets/11015345/966136da-fc8e-4abd-8d51-35b434d7f6a7)

**Comment by DowntownTrainer** [comment]
I'm thinking we can close this issue, the actual file, part 2 of 2 seems to have incongruity issues.  I just mirror imaged part 1 of 2 and it sliced fine.
