### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by Bernardino-Home** [Ultimaker/Cura#17600]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender 3

### Name abnormal settings

Didn't changed setting

### Describe model location

Doesn't slice in any rotation

### Describe your model

First time slicing this model

### Add your .zip here ⬇️

[upper-body.zip](https://github.com/Ultimaker/Cura/files/13629537/upper-body.zip)

**Comment by 5axes** [comment]
Doesn't have any issue with this model.
![image](https://github.com/Ultimaker/Cura/assets/11015345/ac80be32-be35-4fc6-a174-ec95711e9701)

Don't share an STL file it's absolutly useless, share your project file for analyse.

**Comment by Bernardino-Home** [comment]
![image](https://github.com/Ultimaker/Cura/assets/55561766/69517ab2-a68c-4e7a-8c0c-be2abd014888)

Close bug.
Today it started to work.

The only difference from today and yesterday was that today, i had the pen inserted on the slot.

**Comment by Bernardino-Home** [comment]
Today's working fine. the only difference was me having the pen inserted. As you can see, yesterday I had this problem:
![image](https://github.com/Ultimaker/Cura/assets/55561766/9d597bae-06d9-4ec4-bd6b-f2df491c434f)

But not anymore, don't know why.

**Comment by Bernardino-Home** [comment]
Thank you and i'm sorry for the trouble:

![image](https://github.com/Ultimaker/Cura/assets/55561766/1800bb09-ffaa-43aa-9a39-99b222d3f1da)
