### ISSUE TITLE
Project fails to slice on after layer height change

### ISSUE THREAD

**Issue by hgs25** [Ultimaker/Cura#17609]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender-3 / Ender-3 v2

### Name abnormal settings

Layer Height

### Describe model location

No

### Describe your model

successful on certain layer heights

### Add your .zip here ⬇️

[CE3E3V2_Door Modular(DM) Piece_4 QTY.zip](https://github.com/Ultimaker/Cura/files/13638183/CE3E3V2_Door.Modular.DM.Piece_4.QTY.zip)

**Comment by hgs25** [comment]
I would also like to add that the failure is inconsistent. sometimes it will work, often it will fail.

**Comment by 36grad** [comment]
Exactly the same here.

I just installed Cura 5.6.0 and wondered why the print time just doubled compared to 5.3.1.
Saw that the layer height per default was 0.1 in Cura 5.6.0 and changed to 0.2.
Does not slice 3 out of 4 times but every now and then it works.

Printer: Elegoo Neptune 3 Pro
OS: Windows 10 x64

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
