### ISSUE TITLE
Error while slicing

### ISSUE THREAD

**Issue by RLG21275** [Ultimaker/Cura#17612]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Kobra 2 Neo

### Name abnormal settings

It can be sliced with default settings. Sus, setting is "Infill layer thickness"

### Describe model location

Model in the center. Rotation or displacement changes nothing.

### Describe your model

Sliced and printed with different profile. Meshtools used but stiil slicing error.

### Add your .zip here ⬇️

[cuteDragon_PLA_0h0m.zip](https://github.com/Ultimaker/Cura/files/13639318/cuteDragon_PLA_0h0m.zip)

**Comment by 5axes** [comment]
No issue on Windows 10 .
![image](https://github.com/Ultimaker/Cura/assets/11015345/ece1c1e2-38da-4203-b7ab-3b6833a1e916)

An other Windows 11 issue :https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
