### ISSUE TITLE
Bag Holder

### ISSUE THREAD

**Issue by verge66** [Ultimaker/Cura#17610]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3 v2

### Describe model location

centered on plate

### Describe your model

simple bag holder

### Add your .zip here ⬇️

[CE3E3V2_BagHolder_Part_1_v8j_Nozzle-06_Infill-20_Speed-1000_Flow-100_CFN6N2LWITHS_Generic_Nylon.zip](https://github.com/Ultimaker/Cura/files/13638669/CE3E3V2_BagHolder_Part_1_v8j_Nozzle-06_Infill-20_Speed-1000_Flow-100_CFN6N2LWITHS_Generic_Nylon.zip)

**Comment by 5axes** [comment]
AN other Tree Support Issue or Part Orientation issue
https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
![image](https://github.com/Ultimaker/Cura/assets/11015345/264f0e07-4084-4d01-8200-8fdf0bd4edd9)
