### ISSUE TITLE
at the start of the slice it imediately failed to slice

### ISSUE THREAD

**Issue by Elliehanna** [Ultimaker/Cura#17618]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

ender 3 pro

### Name abnormal settings

I enabled Z op when retracted, z hop only over printed parts, 

### Describe model location

entire build plate, centered

### Describe your model

Articulated dragon

### Add your .zip here ⬇️

[failed slice.zip](https://github.com/Ultimaker/Cura/files/13649284/failed.slice.zip)

**Comment by 5axes** [comment]
Interesting bug. Works if Layer height is different.
