### ISSUE TITLE
[5.6.0] Minor typo.

### ISSUE THREAD

**Issue by Asterchades** [Ultimaker/Cura#17623]
### Cura Version

5.6.0

### Operating System

Windows 11 (23H2)

### Printer

Custom FFF Printer (default config)

### Reproduction steps

1. Download the file "Part_Studio_1_-_Hide.3mf from [this Thingiverse object](https://www.thingiverse.com/thing:6225612),
2. Attempt to open the file in Cura

Please note that this issue is not regarding the model itself. It appears to be a deliberately non-conformant 3MF exported by Bambu Studio.

*I'd put in a pull request to fix it myself but I cannot find what file it's part of. It appears to be part of Uranium.

### Actual results

A warning is presented stating that "There _where_ no models in" the file (emphasis mine).

### Expected results

"Were" is the appropriate spelling in this situation, being the past tense of "are" (which would also be acceptable).

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/29810435/a9931150-dd2f-4aa3-ba47-53e23a430d3b)

**Comment by 5axes** [comment]
Duplicate : https://github.com/Ultimaker/Cura/issues/16810

**Comment by Asterchades** [comment]
My bad. Not quite sure how I missed those - they're recent.
