### ISSUE TITLE
slicing failed, dont know why

### ISSUE THREAD

**Issue by Krasha-S** [Ultimaker/Cura#17621]
### Cura Version

5.6.0

### Operating System

Windows 10, GTX 1060, intel I7, 32 GB ram

### Printer

Anycubic i3 mega S

### Name abnormal settings

nothing abnormal

### Describe model location

in center

### Describe your model

didnt slice it succesfully before, it is water tight, tried do a mesh fix.

### Add your .zip here ⬇️

part 3 of 3. went well to slice other two parts but not this one.
mesh tools says it is watertight.
[AI3M_baby1.zip](https://github.com/Ultimaker/Cura/files/13650790/AI3M_baby1.zip)

**Comment by Krasha-S** [comment]
i solved this issue. failed to print with support structure: tree, if i use normal structure it works fine.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
