### ISSUE TITLE
support not added in first layer without skirt

### ISSUE THREAD

**Issue by netanelt93** [Ultimaker/Cura#17626]
### Cura Version

5.4.0

### Operating System

windows 10

### Printer

Genius Pro

### Reproduction steps

1. set slicer with supports, but no adhesion (no skirt aswell)
2. sliced

3. set slicer with skirt aswell
4. sliced

### Actual results

![image](https://github.com/Ultimaker/Cura/assets/153680576/012ad4db-e80d-4eec-a96d-c7ab629a40bd)

### Expected results

![image](https://github.com/Ultimaker/Cura/assets/153680576/15829f39-44c2-4ae3-969a-560a3edf26ed)

### Add your .zip and screenshots here ⬇️

[Curabug.zip](https://github.com/Ultimaker/Cura/files/13653138/Curabug.zip)

**Comment by GregValiant** [comment]
This was fixed in 5.6.
I'll go ahead and close this report.
