### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by rhntr64** [Ultimaker/Cura#17638]
### Cura Version

5.4

### Operating System

windows 11

### Printer

Flsun Super Racer

### Name abnormal settings

Exclusive

### Describe model location

no

### Describe your model

Tail part for airplane

### Add your .zip here ⬇️

[FSR_horizontal stabilizer left.zip](https://github.com/Ultimaker/Cura/files/13668003/FSR_horizontal.stabilizer.left.zip)

**Comment by 5axes** [comment]
Could be due to the invalid Model :  
![image](https://github.com/Ultimaker/Cura/assets/11015345/9ad6a0b4-fbbc-4da0-9c61-d512c321fd6d)

**Comment by rhntr64** [comment]
Wow. That is strange.  That is not on the model when sliced with another slicer.  The part is from the Pond Racer 1200mm on Cults3d. He has internal structure requiring the use of the exclusive setting to have it populate. This model has been extensively downloaded and printed with limited isssues.Sent from my iPhoneOn Dec 14, 2023, at 1:54 AM, 5axes ***@***.***> wrote:﻿
Could be due to the invalid Model :
image.png (view on web)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
