### ISSUE TITLE
Large model slicing failed

### ISSUE THREAD

**Issue by mortensenal** [Ultimaker/Cura#17647]
### Cura Version

5.6.0

### Operating System

Win 11

### Printer

Ender 3 s1 Plus

### Name abnormal settings

slice failed when i added support keep out blocks to model

### Describe model location

it does slice if rotated long model axis to y axis

### Describe your model

Model has been sliced fine before. 

### Add your .zip here ⬇️

[FFV5.0-ExtraFast-028.zip](https://github.com/Ultimaker/Cura/files/13677873/FFV5.0-ExtraFast-028.zip)

**Comment by 5axes** [comment]
Large Model ?
![image](https://github.com/Ultimaker/Cura/assets/11015345/7d62d86a-8b14-48cd-9e24-f413ca2845d0)

Looks like an other Windows 11 issue

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
