### ISSUE TITLE
GMC Truck Slice Failing

### ISSUE THREAD

**Issue by Tyman108** [Ultimaker/Cura#17648]
### Cura Version

5.6

### Operating System

windows 11

### Printer

Anycubic Kobra

### Describe model location

center at 45deg -1.5mm

### Describe your model

gmc truckk

### Add your .zip here ⬇️

[AK_trruck v1_fixed.zip](https://github.com/Ultimaker/Cura/files/13679081/AK_trruck.v1_fixed.zip)

**Comment by 5axes** [comment]
An other Print Thin Walls issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
![image](https://github.com/Ultimaker/Cura/assets/11015345/ddd68da3-1e67-420b-8c4d-870695f771d3)

**Comment by Tyman108** [comment]
> An other Print Thin Walls issue : [#16440 (comment)](https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452) ? ![image](https://private-user-images.githubusercontent.com/11015345/290685365-ddd68da3-1e67-420b-8c4d-870695f771d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2ODkyMjksIm5iZiI6MTcwMzY4ODkyOSwicGF0aCI6Ii8xMTAxNTM0NS8yOTA2ODUzNjUtZGRkNjhkYTMtMWU2Ny00MjBiLThjNGQtODcwNjk1Zjc3MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDE0NTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZWUxZjEwYmRlOTM4OTU5OTJjZWE3ZWRhYTM3YTU5Mzk4YmQ1YjE5MjlkNjcxOWVkYjI0MTRkYTYwMjVlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ua4wv5TAcGYVRhK81EHAByyFmha4lkI4VnhpEpwvaNo)

how where you able to get this to slice?

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
