### ISSUE TITLE
failed slice of simple plate with an embossed character

### ISSUE THREAD

**Issue by altconcepts** [Ultimaker/Cura#17652]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender 5 Plus

### Name abnormal settings

no

### Describe model location

no

### Describe your model

rectangular plate with an embossed zodiac character

### Add your .zip here ⬇️

[sample_slice_failure.zip](https://github.com/Ultimaker/Cura/files/13682246/sample_slice_failure.zip)

**Comment by 5axes** [comment]
If you don't need some supports , don't activate the support creation you will save processing time and get a result.
![image](https://github.com/Ultimaker/Cura/assets/11015345/939fdba8-1ed1-4093-ad7a-bc01b63dc101)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
