### ISSUE TITLE
unsupported operand type(s) for +: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by bigbm2019** [Ultimaker/Cura#17663]
### Cura Version

5.5.0

### Operating System

macOS 14.2 (23C64)

### Printer

ender 3 with klipper

### Reproduction steps

I am trying to save the file 

### Actual results

it says unsupported operand type(s) for +: 'float' and 'NoneType'

### Expected results

it should save as gcode 

### Add your .zip and screenshots here ⬇️

<img width="1401" alt="Skærmbillede 2023-12-15 kl  22 42 49" src="https://github.com/Ultimaker/Cura/assets/48869744/0e9e92b7-cdba-4fd7-9c07-42af31ce1b01">

**Comment by GregValiant** [comment]
Thanks for the report.
Do you happen to have the "Z-Offset" plugin from the MarketPlace loaded?

**Comment by GregValiant** [comment]
Thanks for the report.
This might be related to #17650 .  We need a project file to trouble shoot.  Use the "File | Save Project" command then zip the file and post the zip folder here.
