### ISSUE TITLE
Failed Slicing

### ISSUE THREAD

**Issue by calif94577** [Ultimaker/Cura#17667]
### Cura Version

5.4.0

### Operating System

Mac OS 14.0

### Printer

SV-01

### Describe your model

Just this model

### Add your .zip here ⬇️

[SSL_Tabaxi Female Hexblade.3mf.zip](https://github.com/Ultimaker/Cura/files/13690981/SSL_Tabaxi.Female.Hexblade.3mf.zip)

**Comment by 5axes** [comment]
An other Print Thin Walls Issue ... https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

![image](https://github.com/Ultimaker/Cura/assets/11015345/efe93a6a-a876-4155-a9c9-07e1288bd9c0)

Model muste be print with support and at least a 0.2 Nozzle

**Comment by calif94577** [comment]
I've definitely tried with support with no luck. However I need a nozzle smaller than or equal to 0.2 you're saying?

**Comment by calif94577** [comment]
Just tried to slice it with supports and 0.2, 0.1, and even tried 0.05 nozzle without success. Same error.
