### ISSUE TITLE
Slicing Failed on Car print

### ISSUE THREAD

**Issue by GundamSonic** [Ultimaker/Cura#17664]
### Cura Version

5.6.0

### Operating System

Windows 

### Printer

Anycubic Vyper

### Name abnormal settings

slicing failed

### Describe model location

center

### Describe your model

Its A Car

### Add your .zip here ⬇️

[AV_VW_Transporter_1958FX.zip](https://github.com/Ultimaker/Cura/files/13690118/AV_VW_Transporter_1958FX.zip)

**Comment by GundamSonic** [comment]
it keep failing no matter how I oriented the model

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
