### ISSUE TITLE
Warehouse building

### ISSUE THREAD

**Issue by pbechard** [Ultimaker/Cura#17682]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender3 S1 Plus

### Name abnormal settings

Standard Profile:  Super Quality 0.12mm.   Minor changes:  "Print Thin Walls" is enabled.     The model WILL slice if I use Dynamic Quality 0.16mm

### Describe model location

Centered on build plate, default location

### Describe your model

It will slice on Ender3v2 printers, no issue

### Add your .zip here ⬇️

[Warehouse - Flat Roof version.zip](https://github.com/Ultimaker/Cura/files/13696289/Warehouse.-.Flat.Roof.version.zip)

Standard Profile:  Super Quality 0.12mm.   Minor changes:  "Print Thin Walls" is enabled.     

The model WILL slice if I use Dynamic Quality 0.16mm

**Comment by 5axes** [comment]
AN other "Print Thin Walls" Issue: https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

 .. on extruder 1 

![image](https://github.com/Ultimaker/Cura/assets/11015345/b1133e48-2e0d-46f3-9368-26cedd7bafa5)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
