### ISSUE TITLE
Cura

### ISSUE THREAD

**Issue by PkzKingz** [Ultimaker/Cura#17684]
### Cura Version

5.6.

### Operating System

Win 10

### Printer

Elegoo Neptune 4 plus

### Name abnormal settings

Yeah, I need support and it seems like that when I enable it, Slicing fail(default normal 0.15mm profile will slice until I check generate support)

### Describe model location

center build plate, 90­degree(so that the inner of the joystick face the buildplace)

### Describe your model

It's an half of a not so pretty joystick

### Add your .zip here ⬇️

I did try to change support density, structure, pattern. But It was still failing to slice
I tried slice both model(left and right part of my joystick) with same result
I was able to get to slice with both models on the build plate once but now I get slicing failure
(I still use Cura 5.2.1 to slice for my ender3max and I have no problem slicing the same files)
[Files.zip](https://github.com/Ultimaker/Cura/files/13696613/Files.zip)

**Comment by 5axes** [comment]
An other Tree Support Issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
