### ISSUE TITLE
slicing failed astronaut

### ISSUE THREAD

**Issue by cyberjunkiefr** [Ultimaker/Cura#17697]
### Cura Version

5.6.0

### Operating System

Windows 11 pro

### Printer

ender-3

### Describe model location

it can be sliced when turne 270°

### Describe your model

astronaut sitting on moon

### Add your .zip here ⬇️

[CE3PRO_astronaut.zip](https://github.com/Ultimaker/Cura/files/13707678/CE3PRO_astronaut.zip)

**Comment by 5axes** [comment]
An other Part Model / position , orientation issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452
![image](https://github.com/Ultimaker/Cura/assets/11015345/0fb26abf-0907-41da-b32a-8b1990a4b8b5)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
