### ISSUE TITLE
Slicing error, additional surfaces

### ISSUE THREAD

**Issue by reimannsum** [Ultimaker/Cura#17699]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Kingroon KP3S

### Describe model location

center of bed

### Describe your model

Model is watertight, 

### Add your .zip here ⬇️

[KK_Bead board v3.zip](https://github.com/Ultimaker/Cura/files/13709491/KK_Bead.board.v3.zip)
When the model is rotated 90 degrees it slices correctly, but in the default orientation it will generate at least one layer only seen in the preview window. 
![image](https://github.com/Ultimaker/Cura/assets/15264176/76e54a66-daf0-4fec-b88d-a42d584f737f)

**Comment by reimannsum** [comment]
if it slices Ok the first time you may have to slice it with supports to get it to generate but then when you disable supports again it still shows the middle slot having that cover

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
