### ISSUE TITLE
Issue #17702: re

### ISSUE THREAD

**Issue by oscargg** [Ultimaker/Cura#17703]
### Cura Version

5.6 & 5.4

### Operating System

w10

### Printer

anycubic chiron from library or diy setting

### Describe your model

slicing error 

### Add your .zip here ⬇️

[bass drum claw.zip](https://github.com/Ultimaker/Cura/files/13714262/bass.drum.claw.zip)
i've added a screenshot of error msg, and a material setting profile that creates the error
if you can't recreate the issue, i will try to deinstall all cura version (actually 15.04, 5.3, 5.4, 5.6 installed) and reinstall only last ver.
tks

**Comment by 5axes** [comment]
Sorry No issue : Windows 10 like you  Cura 5.6.0 . But As every release are independant  I don't think it's a good idea to unstall all cura release. 

![image](https://github.com/Ultimaker/Cura/assets/11015345/ed2d750d-5a74-4902-a72f-a0c228dd7895)

**Comment by 5axes** [comment]
@GregValiant Do you have any issue on your side ?

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
