### ISSUE TITLE
Error slicing

### ISSUE THREAD

**Issue by Oyagum** [Ultimaker/Cura#17704]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Artillery X2

### Describe your model

One door that opens

### Add your .zip here ⬇️

[Freestanding-Metal-Door.zip](https://github.com/Ultimaker/Cura/files/13718687/Freestanding-Metal-Door.zip)

**Comment by 5axes** [comment]
Well normaly I would say "**Print Thin Walls**" issue. But as the model are not very valid for a FDM process it's much more an issue with the Model.  Your model sould be a "real" manifold geometry.

![image](https://github.com/Ultimaker/Cura/assets/11015345/2b7f8a9a-9248-4ff6-963a-1b18574ef525)

On the right the "exploded" model.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
