### ISSUE TITLE
crash in wall count = 4, and/or infill density =20

### ISSUE THREAD

**Issue by oscargg** [Ultimaker/Cura#17702]
### Cura Version

5.6 & 5.4
no slicing issue with cura 5.3

### Operating System

w10

### Printer

anycubic chiron from library or diy setting

### Describe your model

sliced one year ago whitout problems

### Add your .zip here ⬇️

[bass drum claw.zip](https://github.com/Ultimaker/Cura/files/13713808/bass.drum.claw.zip)

**Comment by 5axes** [comment]
Sorry cannot reproduce your issue . **Wall count = 4 and  infill density =20%**

![image](https://github.com/Ultimaker/Cura/assets/11015345/6347cf77-7927-41a2-97dd-b435a2c588c8)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
