### ISSUE TITLE
Missing Profiles

### ISSUE THREAD

**Issue by BobFre** [Ultimaker/Cura#1771]
The only preloaded profile I get is Fast Print.  I have loaded Cura on two separate computers and get the same result.  Is there a way to download/import the protected profiles?

**Comment by fieldOfView** [comment]
Are you using an UM2+ with a .8mm nozzle? If so, that's all you are going to get. There is no High Quality profile for a .8mm nozzle

**Comment by BobFre** [comment]
Yes, I am using .8mm nozzle.

Thanks
