### ISSUE TITLE
center camera grey out cura2.5

### ISSUE THREAD

**Issue by xile6** [Ultimaker/Cura#1772]
I am unable to click the center camera. It is grey out. I have uninstall and reinstall and deleted all my settings and i just can not get it to work.
cura 2.5

**Comment by nallath** [comment]
This is because of a bug in a library we use for windows. I hope it will be fixed in the next release.

**Comment by fieldOfView** [comment]
To clarify: the option was disabled (on Windows) because enabling it would cause Cura to crash.

**Comment by dalgibbard** [comment]
Is there a link to an associated bug or library that I can follow to keep track of progress?

**Comment by Ghostkeeper** [comment]
This is the issue: https://github.com/Ultimaker/Cura/issues/1566

**Comment by dalgibbard** [comment]
Thanks
