### ISSUE TITLE
Slicing Failed After Long Processing Time

### ISSUE THREAD

**Issue by Wachobc** [Ultimaker/Cura#17729]
### Cura Version

5.3.0

### Operating System

Windows 11

### Printer

Monoprice Select Mini V2 (E3D)

### Name abnormal settings

Support changes 

### Describe model location

No alternate locations were tested.

### Describe your model

Model was sliced with normal support but the error seemed to occur when  changed to Tree.  Attempting to reduce print time

### Add your .zip here ⬇️

Changed support from normal to Tree in an attempt to reduce build time.  Slice took much longer than usual then failed with the option to report.  Reporting in hopes that it will help improve the tool.
[MSMV2E3D_Round_Base_1.zip](https://github.com/Ultimaker/Cura/files/13749400/MSMV2E3D_Round_Base_1.zip)
[MSMV2E3D_Round_Base_1.zip](https://github.com/Ultimaker/Cura/files/13749407/MSMV2E3D_Round_Base_1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
