### ISSUE TITLE
Cura fails with every model

### ISSUE THREAD

**Issue by hd42** [Ultimaker/Cura#17739]
### Cura Version

5.6.0

### Operating System

Ubuntu Linux

### Printer

Elegoo Neptune 4 plus

### Describe model location

default

### Describe your model

simple pyramid

### Add your .zip here ⬇️

[EN3P_Pyramide.zip](https://github.com/Ultimaker/Cura/files/13754513/EN3P_Pyramide.zip)

**Comment by 5axes** [comment]
Sory no issue for me : 
![image](https://github.com/Ultimaker/Cura/assets/11015345/e12bc55c-4a00-466d-8bd7-d9ed80d71dd4)

but in your project the printer is detected as **Anycubic Kobra Youtube** ????
![image](https://github.com/Ultimaker/Cura/assets/11015345/d172dcbe-3b69-4b32-92b8-810bbf85ab20)

**Comment by hd42** [comment]
[CFFFP_TOP2.zip](https://github.com/Ultimaker/Cura/files/13829282/CFFFP_TOP2.zip)
I tried creating a new printer profile, but still get the same error.

**Comment by 5axes** [comment]
Still no problem for me :  
![image](https://github.com/Ultimaker/Cura/assets/11015345/d6196216-d7fc-46d6-ba43-9e4e86bb0d5c)

**Comment by hd42** [comment]
I disabled all plugins and now it works. I'll try to enable them one after the other to find out which one caused the problem.

**Comment by 5axes** [comment]
similar to https://github.com/Ultimaker/Cura/issues/17551 ?

**Comment by hd42** [comment]
The culprit appears to be the CuraEngineTiledInfill 0.2.0 plugin.

**Comment by hd42** [comment]
Thank you for your help, @5axes.
