### ISSUE TITLE
Slicing Fails with Tree Supports Enabled

### ISSUE THREAD

**Issue by MedicBot2319** [Ultimaker/Cura#17736]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 Pro

### Name abnormal settings

No changes to default profile (Balanced - Fast)

### Describe model location

No changes to default location when model is loaded.

### Describe your model

It slices successfully with "Normal" supports or no supports but when "Tree" supports are selected the model will not slice.

### Add your .zip here ⬇️

[DoryHooks3-ghook.zip](https://github.com/Ultimaker/Cura/files/13753922/DoryHooks3-ghook.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
