### ISSUE TITLE
ENDER3  V3SE - M109 Error code in Sonic pad

### ISSUE THREAD

**Issue by Dine79** [Ultimaker/Cura#17735]
### Cura Version

5.6.0

### Operating System

Win 10 Pro

### Printer

Creality Ender 3 V3SE

### Reproduction steps

this error appears right before the start of the print.  The line is in the start code.  I took it out and it works, but... what does that line do?

### Actual results

I took it out and it works, but... what does that line do?

### Expected results

Start printing normally

### Add your .zip and screenshots here ⬇️

no zip

**Comment by GregValiant** [comment]
It sets the hot end temperature and waits for the hot end to reach the temperature before continuing with the print.
The line in the startup may contain "replacement patterns".  If Cura understands them then it takes out the word (like "material_print_temperature_layer_0") and replaces it with the actual number from the settings.
If there is a typo in the replacement pattern then the number doesn't get put in and your pad thingy would see
"M109 S{material_print_tempera  ure_layer_0" and might not know what to do with it.

This isn't a Cura problem though.  The startup gcode is from the definition file for your printer which comes either from a user or from Creality.  I'll go ahead and close this.  I hope you understand.
