### ISSUE TITLE
using a cutting mesh anywhere will bug

### ISSUE THREAD

**Issue by chazzy25011** [Ultimaker/Cura#17749]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

kingroon kp3s

### Name abnormal settings

using a cutting mesh

### Describe model location

centre

### Describe your model

complex statue and simple disc for cutting mesh

### Add your .zip here ⬇️

[KK_astronaut on the moon crash.zip](https://github.com/Ultimaker/Cura/files/13759451/KK_astronaut.on.the.moon.crash.zip)

adding a cutting mesh of any complexity with any settings in any position (even not on build plate) will stop slicing.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
