### ISSUE TITLE
Scaled up model with tree support in center of build plate does not slice

### ISSUE THREAD

**Issue by ChrisZehr** [Ultimaker/Cura#17751]
### Cura Version

5.5.0

### Operating System

Windows 10, RTX 3080

### Printer

Anycubic Vyper

### Name abnormal settings

Scaled up 500%

### Describe model location

Moving the model to the front of the build plate allows it to slice without error

### Describe your model

M1A1 Abrams body

### Add your .zip here ⬇️

[AV_M1A1_Abrams_w Tree Support.zip](https://github.com/Ultimaker/Cura/files/13759629/AV_M1A1_Abrams_w.Tree.Support.zip)

**Comment by 5axes** [comment]
Don't know if we have to classify in Another "Part Position issue" or "Tree Support Issue". Anyway rotate the model solved the issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-6793499

![image](https://github.com/Ultimaker/Cura/assets/11015345/b7445a99-6c97-4494-a6ca-29635cb3c9b0)

**Comment by ChrisZehr** [comment]
Did you try moving it around the build plate as well? It seemed to have an
issue in random locations when I tried to slice. It would either hang at
50% or give me the error message or work. I couldn't get it to be
consistent. Maybe it's fixed in 5.6.0?

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
