### ISSUE TITLE
grille 15

### ISSUE THREAD

**Issue by Golddwing1983** [Ultimaker/Cura#17758]
### Cura Version

5.5.0

### Operating System

Windows 10 pro

### Printer

Ender 3 Si Pro

### Describe model location

yes 90 cw

### Describe your model

wot tank

### Add your .zip here ⬇️

[CE3S1PRO_Grill_15_Complete.zip](https://github.com/Ultimaker/Cura/files/13760890/CE3S1PRO_Grill_15_Complete.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
