### ISSUE TITLE
Vase failed to slice

### ISSUE THREAD

**Issue by Jac-SV** [Ultimaker/Cura#17768]
### Cura Version

5.5.0

### Operating System

Mac OS Sonoma 14.1.1 (23B81)

### Printer

Anycubik Kobra Mega

### Describe model location

default

### Describe your model

first time slicing, to see difference between spiraled and infilled

### Add your .zip here ⬇️

[AKMAX_Czechia.3mf.zip](https://github.com/Ultimaker/Cura/files/13762838/AKMAX_Czechia.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
