### ISSUE TITLE
2 Color Benchy Slicing Issue

### ISSUE THREAD

**Issue by wdhensley** [Ultimaker/Cura#17762]
### Cura Version

5.6.0

### Operating System

Mac OS Sonoma

### Printer

Elegoo Neptune 2D

### Name abnormal settings

default setings used

### Describe model location

center of plate

### Describe your model

Have not been able to slice

### Add your .zip here ⬇️

[N2D_Ghostship_Benchy 2 Color.3mf.zip](https://github.com/Ultimaker/Cura/files/13761729/N2D_Ghostship_Benchy.2.Color.3mf.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
