### ISSUE TITLE
USB printing - Not working for Smoothieware firmware

### ISSUE THREAD

**Issue by Shaische** [Ultimaker/Cura#1777]
There is an issue with printing via USB when attempting to print with a smoothieware firmware based printer. This issue didn't exist in Cura 1, so it would be good to compare the code to see what changed that is causing this as it has to do with how Cura 2 is communicating with the printer (what it is sending) based on the discussions I had with the smoothieware developers.

The original problem with Cura 2 was not being able to communicate with the printer at all and that was due to it sending empty command lines to the printer. Clicking "Print via USB" did not do anything at all. Jaime had been able to fix this, but not sure if it was merged into 2.5.0. 

After testing a nightly build that had the fix of not sending empty command lines, we were able to start the print. But, it would only get to the point where the hotend heated up, moved down to the bed to start to print and would only deposit maybe about 2mm worth of plastic before the printer froze in place and wouldn't continue further.

If anyone can fix this, we would be very grateful! We can test it for you.

**Comment by nallath** [comment]
I've made a few changes outside of working hours, but as I only have a board without a full printer attached, it's hard to see what's going wrong. 

The code difference between Cura 1 and Cura 2 are pretty big. Also considering that cura 1 used python 2, whereas cura 2 used Python 3. The USB code of cura2 is based on that of the old one, but it's impossible to completely duplicate it.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by Shaische** [comment]
Yes, for smoothieware it is still an issue.

**Comment by nallath** [comment]
As Ultimaker doesn't use smoothieware, i don't think its likely that anyone from Ultimaker is going to spend time on fixing it. If someone from the comunity fixes it, we're more than happy to merge the pull request.
