### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by PeterDarley** [Ultimaker/Cura#17774]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Voron 2.4

### Name abnormal settings

Fails with tree supports, succeeds with no supports.

### Describe model location

Center of bed.  Doesn't change if I rotate or move it.

### Describe your model

Mostly flat. Sliced correctly in 5.5.  Fails after fixing with meshtools.

### Add your .zip here ⬇️

[V350_Brown Cover (A) 2x.zip](https://github.com/Ultimaker/Cura/files/13764103/V350_Brown.Cover.A.2x.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
