### ISSUE TITLE
Slicing Error when supports are enabled

### ISSUE THREAD

**Issue by Chidwi-commits** [Ultimaker/Cura#17779]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3 V3 SE

### Name abnormal settings

Enable Supports

### Describe model location

Doesn't matter

### Describe your model

Yes, the model is sliced sometimes. Mesh Fix doesn't help. 

### Add your .zip here ⬇️

Quite often, when I print models with supports (even small ones and 1 piece in the center of the plate), this problem occurs. Usually it helps to lift the model over the plate and let it go so that it sticks by itself. With the supports off, everything cuts fine. Today I placed the models on the table, turned on the support, got an error, tried several more times to no avail. I left the computer for a while, and when I came back, I clicked on the slice again and everything went fine.
![зображення_2023-12-25_233210398](https://github.com/Ultimaker/Cura/assets/55891821/9f3bb138-d159-4535-a11a-b4cb7b0d223b)
![зображення_2023-12-25_233318397](https://github.com/Ultimaker/Cura/assets/55891821/573d5f2a-ef51-4afa-b0d8-e3a492fff9e3)
[CE3V3SE_hanger.zip](https://github.com/Ultimaker/Cura/files/13767291/CE3V3SE_hanger.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
