### ISSUE TITLE
Cannot Slice Model in latest Cura Version

### ISSUE THREAD

**Issue by maxifox79** [Ultimaker/Cura#17782]
### Cura Version

5.6.0

### Operating System

Windows 11 Home

### Printer

Trimaker Cosmos II

### Name abnormal settings

None

### Describe model location

Does not slice in any way, after increasing size 250%

### Describe your model

It slices in original model, but does not slide while increasing size 250% (both files attached)

### Add your .zip here ⬇️

[CFFFP_C21.zip](https://github.com/Ultimaker/Cura/files/13771847/CFFFP_C21.zip)

**Comment by maxifox79** [comment]
I find it out that I can slice in original model, the one that I attached was scaled to 250%. I need to print using this scale.

**Comment by maxifox79** [comment]
Attached the original file which can be sliced, but I need to scale this up to 250% which is not slicing.

**Comment by maxifox79** [comment]
[CFFFP_C21_Original.zip](https://github.com/Ultimaker/Cura/files/13771869/CFFFP_C21_Original.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
