### ISSUE TITLE
Every time i try to slice the Bowser fails on slicing

### ISSUE THREAD

**Issue by Alpdog14** [Ultimaker/Cura#17799]
### Cura Version

5.6.0

### Operating System

Windows 10 Pro

### Printer

Ender Pro V3 SE

### Name abnormal settings

keeps throwing errors

### Describe model location

Center and I made it smaller

### Describe your model

Bowser figure

### Add your .zip here ⬇️

Here is the original file from Thingiverse: 
[Bowser from Super Mario 3d World.zip](https://github.com/Ultimaker/Cura/files/13780245/Bowser.from.Super.Mario.3d.World.zip)

here is my scaled down version:
[CE3V3SE_Bowser.zip](https://github.com/Ultimaker/Cura/files/13780274/CE3V3SE_Bowser.zip)

still throws error when slicing

**Comment by 5axes** [comment]
Model Issue : 
![image](https://github.com/Ultimaker/Cura/assets/11015345/b25376d7-be5b-443b-b981-321617d69352)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
