### ISSUE TITLE
Eiffel Tower slice fail

### ISSUE THREAD

**Issue by ibyte01** [Ultimaker/Cura#17790]
### Cura Version

5.5.0

### Operating System

windows 11

### Printer

ender 3 s1 pro

### Name abnormal settings

no abnominal settings.

### Describe model location

no

### Describe your model

No

### Add your .zip here ⬇️

[CE3S1PRO_EiffelTower_fixed.zip](https://github.com/Ultimaker/Cura/files/13773834/CE3S1PRO_EiffelTower_fixed.zip)

**Comment by 5axes** [comment]
An other Windows 11 issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
