### ISSUE TITLE
Slice Failed Again

### ISSUE THREAD

**Issue by justjay1986** [Ultimaker/Cura#17802]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3 V2

### Describe model location

Center of bed, flat to bed

### Describe your model

Raspberry Pi 3+ case

### Add your .zip here ⬇️

[CE3E3V2_upperpart_V2_fail.zip](https://github.com/Ultimaker/Cura/files/13780752/CE3E3V2_upperpart_V2_fail.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
