### ISSUE TITLE
Upgraded to 5.6.0, slicing of model that was working now fails

### ISSUE THREAD

**Issue by ernwa** [Ultimaker/Cura#17803]
### Cura Version

5.6.0

### Operating System

MacOS Big Sur

### Printer

prusa i3 mk3s

### Name abnormal settings

don't know, tried different generic materials. Rotation doesn't change error

### Describe model location

tried various, immediate failure regardless

### Describe your model

yes, then I updated to 5.6.0. It is watertight

### Add your .zip here ⬇️

[cover try 2.3mf.zip](https://github.com/Ultimaker/Cura/files/13781569/cover.try.2.3mf.zip)

**Comment by 5axes** [comment]
No issue on Windows 10.  
![image](https://github.com/Ultimaker/Cura/assets/11015345/c12e5e88-4ebe-4616-9771-690aeb6a76eb)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
