### ISSUE TITLE
Simple L Bracket Part that angles up off the build plate at the one end. Using tree suport.

### ISSUE THREAD

**Issue by allgoodtw** [Ultimaker/Cura#17815]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

CR-10 Max

### Name abnormal settings

Tree Support with Recommended settings.

### Describe model location

Slices on a second attempt

### Describe your model

L Shaped Bracket That rises up off the built plaate at the far end which needs support.

### Add your .zip here ⬇️

[Zip for debug.zip](https://github.com/Ultimaker/Cura/files/13792423/Zip.for.debug.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
