### ISSUE TITLE
Cura Doesn't slice at all on my new computer

### ISSUE THREAD

**Issue by red-age** [Ultimaker/Cura#17813]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

custom fff

### Name abnormal settings

no, i tried different printers and profiles. all the same error

### Describe model location

i tried different models placed in different locations 

### Describe your model

no, new computer

### Add your .zip here ⬇️

[File Cura.zip](https://github.com/Ultimaker/Cura/files/13790893/File.Cura.zip)

**Comment by red-age** [comment]
HI, I installed Cura on my ner computer. it doesnt slice at all. I have a asus prime z790m plus with i7 14700kf, rtx 4070ti 64 giga of ram ddr5

**Comment by red-age** [comment]
I solved by reinstalling cura, no need help anymore thankyou

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
