### ISSUE TITLE
Slicing failed using Tree Structure

### ISSUE THREAD

**Issue by Astaro2sa** [Ultimaker/Cura#17814]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

creality ender 3 s1

### Name abnormal settings

Support Structure -> Tree

### Describe model location

no

### Describe your model

It can be sliced with normal Support Structure

### Add your .zip here ⬇️

[CE3S1_akali_up.zip](https://github.com/Ultimaker/Cura/files/13791684/CE3S1_akali_up.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
