### ISSUE TITLE
Slicing Failed bug report

### ISSUE THREAD

**Issue by douvine** [Ultimaker/Cura#17823]
### Cura Version

5.60

### Operating System

windows 11

### Printer

ender 3 v2 neo

### Describe your model

theres a part of the object thats not water tight, i have checked with the meshtool but it cant fix it its too complex, i tried editing with mesh mixer autodesk, but all the mesh is pink if i checked with the inspect tool. help i need to print this file ASAP

### Add your .zip here ⬇️

https://we.tl/t-u1TOKOQr0W

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
