### ISSUE TITLE
slicing failing with support blocker / modifiy settings for overlaps / cutting mesh

### ISSUE THREAD

**Issue by V1an** [Ultimaker/Cura#17826]
### Cura Version

5.5.0

### Operating System

Windows 10 AMD RX 5700 XT

### Printer

Ender 3

### Name abnormal settings

support blocker / modifiy settings for overlaps / cutting mesh

### Describe your model

yes i can slice before, it's the cutting mesh that makes slicing impossible

### Add your .zip here ⬇️

[player-1.zip](https://github.com/Ultimaker/Cura/files/13798410/player-1.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
