### ISSUE TITLE
Small flat item slicing fail

### ISSUE THREAD

**Issue by LDDSurfer** [Ultimaker/Cura#17822]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

ELEGOO Neptune 3 Pro

### Name abnormal settings

Tree supports

### Describe model location

rotated 90*

### Describe your model

No to all

### Add your .zip here ⬇️

[Ebony Dagger (Skyrim) - 3353876.zip](https://github.com/Ultimaker/Cura/files/13797499/Ebony.Dagger.Skyrim.-.3353876.zip)

**Comment by LDDSurfer** [comment]
Only works with Fine settings for some reason

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
