### ISSUE TITLE
Laufverbinder

### ISSUE THREAD

**Issue by ThorWallhall** [Ultimaker/Cura#17825]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality Ender 3

### Describe your model

runde Scheibe mit Profilen, die in ein PVC Rohr eingeführt wird

### Add your .zip here ⬇️

[Laufverbinder.zip](https://github.com/Ultimaker/Cura/files/13798099/Laufverbinder.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
