### ISSUE TITLE
Ouverture fichier STL

### ISSUE THREAD

**Issue by dgburbjdhfb** [Ultimaker/Cura#17824]
### Cura Version

5.6.0

### Operating System

Windows11

### Printer

Anycubic Kobra

### Reproduction steps

J'ai converti plusieurs fichiers SLDPRT en fichier STL. Puis j'ai essayé de les ouvrir l'un après l'autre sur Cura.

### Actual results

Lorsque j'essaye de les ouvrir, soit ils n'arrivent pas à s'ouvrir alors que le fichier n'est pas corrompu et qu'il contient bien un modèle, ou soit il s'ouvre et les dimensions sont automatiquement mises à 10000% et lorsque que je les remet à 100% il ne s'affiche pas.

### Expected results

J'aimerais pouvoir ouvrir mes fichiers normalement pour pouvoir les imprimer. 

### Add your .zip and screenshots here ⬇️

![Capture d'écran 2023-12-30 105719](https://github.com/Ultimaker/Cura/assets/155228320/2dcde4cb-ac56-4929-9c28-3da67d99b933)
![Pièce à l'origine](https://github.com/Ultimaker/Cura/assets/155228320/ba94767c-c75e-4d76-a1a8-65ea3e0a15ea)
![Capture d'écran 2023-12-30 110705](https://github.com/Ultimaker/Cura/assets/155228320/8ce29dca-f932-4dc0-b27c-f879e5959c9e)
[entretoise 2.zip](https://github.com/Ultimaker/Cura/files/13797726/entretoise.2.zip)

**Comment by 5axes** [comment]
Le problème n'est pas avec Cura. Ceci n'est pas un fichier STL. le problème est au niveau de la conversion depuis SolidWorks.

**Comment by dgburbjdhfb** [comment]
Oui, c'était bien sa. Merci

**Comment by dgburbjdhfb** [comment]
Erreur au niveau de l'enregistrement de mes fichiers.
