### ISSUE TITLE
Cura keeps crashing

### ISSUE THREAD

**Issue by Splainit** [Ultimaker/Cura#17835]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Sovol sv 01

### Name abnormal settings

none that I know of.

### Describe model location

It only fails when it is centered and flat on the plate

### Describe your model

No

### Add your .zip here ⬇️

[Train.zip](https://github.com/Ultimaker/Cura/files/13799329/Train.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
