### ISSUE TITLE
Slicing process is getting stuck

### ISSUE THREAD

**Issue by EngVinalay** [Ultimaker/Cura#17830]
### Cura Version

5.6.0

### Operating System

window 10

### Printer

Ender 3 V2

### Name abnormal settings

I am using the default settings

### Describe model location

wherever position it stucks

### Describe your model

yes I have sliced other ones prior, and used meshTool plugin as well

### Add your .zip here ⬇️

[CE3E3V2_2.-Dice_tower_Small_Tower_door_v1.0.zip](https://github.com/Ultimaker/Cura/files/13798641/CE3E3V2_2.-Dice_tower_Small_Tower_door_v1.0.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
