### ISSUE TITLE
Tree supports causing failure to slice

### ISSUE THREAD

**Issue by Penrif** [Ultimaker/Cura#17836]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Voron2 300

### Name abnormal settings

Slices fine with normal supports - likely something's up with tree

### Describe model location

Issue is invariant to rotation and translation

### Describe your model

Slices fine with normal supports. Is watertight ect, fresh export from F360.

### Add your .zip here ⬇️

[V300_BottomLeftMonitorPegboard.zip](https://github.com/Ultimaker/Cura/files/13800014/V300_BottomLeftMonitorPegboard.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
