### ISSUE TITLE
crash slicer

### ISSUE THREAD

**Issue by Riothamus87** [Ultimaker/Cura#17846]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

Anycubic kossel linel plus

### Name abnormal settings

put on supports

### Describe model location

rotate it 180º

### Describe your model

yes

### Add your .zip here ⬇️

[D_CaseTS35_TopMeshed.zip](https://github.com/Ultimaker/Cura/files/13801843/D_CaseTS35_TopMeshed.zip)

**Comment by 5axes** [comment]
Not a Cura Project . Just a 3mf format. No issue for me.
![image](https://github.com/Ultimaker/Cura/assets/11015345/203620bc-d373-4de2-ad83-e8689d5b96d3)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
