### ISSUE TITLE
Model will not slice the first few times, but will slice after clicking "Slice" a few more times.

### ISSUE THREAD

**Issue by HutchMD** [Ultimaker/Cura#17845]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3 Pro

### Describe your model

Housing, Will slice if I press "Slice" a few more times.

### Add your .zip here ⬇️

[CE3PRO_Pico Case.zip](https://github.com/Ultimaker/Cura/files/13801743/CE3PRO_Pico.Case.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
