### ISSUE TITLE
dice failed

### ISSUE THREAD

**Issue by AGenericDuck** [Ultimaker/Cura#17866]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

flsun superracer

### Name abnormal settings

brim was on thats the only change but have been using for weeks

### Describe model location

center with the 2 completely flat on the bed

### Describe your model

yes but not this large

### Add your .zip here ⬇️

[FSR_D20 test (1).zip](https://github.com/Ultimaker/Cura/files/13810088/FSR_D20.test.1.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
