### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by amathis58** [Ultimaker/Cura#17879]
### Cura Version

5.6.0

### Operating System

Macbook Pro 2015 Montery 12.7.2

### Printer

Creality Ender 3 max neo

### Name abnormal settings

no

### Describe model location

don't know

### Describe your model

Yes

### Add your .zip here ⬇️

[CE3MAX_BabyGrootStanding_Galaxy.zip](https://github.com/Ultimaker/Cura/files/13819744/CE3MAX_BabyGrootStanding_Galaxy.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
