### ISSUE TITLE
Solo quiero hacer una caja para mis cartas :,)

### ISSUE THREAD

**Issue by UnoYMedio11** [Ultimaker/Cura#17883]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality Ender-3 Pro #2

### Name abnormal settings

los cambios que he hecho son tener una balsa debajo y tener soportes de árbol, cosa que sí había funcionado con el mismo objeto anteriormente

### Describe model location

todo funciona bien si lo giro los 90°, y no le he cambiado ninguna configuración

### Describe your model

sí, he logrado cortarlo antes, pero no en la misma posición, la pieza está en vertical, pero cuando lo coloco en horizontal sí logra cortarlo, no sé usar bien Mesh así que uso Tinkercad no sé si ahí también hay alguna opción de corrección para mi objeto 

### Add your .zip here ⬇️

[CE3PRO_Caja Cartas P ext. 2.1.zip](https://github.com/Ultimaker/Cura/files/13822297/CE3PRO_Caja.Cartas.P.ext.2.1.zip)

esta es la primera vez que me sucede, la verdad no me complica que no poder hacer la pieza en esa posición, porque en la forma horizontal todo funciona bien, aunque me gustaría saber si la razón de la falla es por mi culpa y así no tener que molestarlos otra vez. La versión de UltiMaker Cura no estoy segura, pero en la aplicación sale 5.4.0., no sé qué otra información sería relevante, si pueden contactarme por dudas adelante, yo responderé lo antes posible. Que tengan lindo día.

**Comment by UnoYMedio11** [comment]
Hola, he podido que no haya error de las capas girando en el eje azul, teniendo el objeto verticalmente. No sé si es de ayuda pero igual dejo el dato. Saludos.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
