### ISSUE TITLE
Slicing works then a bug

### ISSUE THREAD

**Issue by Rav3n007** [Ultimaker/Cura#17895]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Vyper

### Describe your model

Yes

### Add your .zip here ⬇️

[AV_spool_rack_pvc_4_fixed.zip](https://github.com/Ultimaker/Cura/files/13826872/AV_spool_rack_pvc_4_fixed.zip)
Slicing works then a bug

**Comment by 5axes** [comment]
Basic part, No issue, Looks like an other "Windows 11 issue" : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

![image](https://github.com/Ultimaker/Cura/assets/11015345/6ce3f04c-5cb3-4af3-a4ff-ab3e91383995)

Duplicate : Slice Failed on **Windows 11**

https://github.com/Ultimaker/Cura/issues/17818
https://github.com/Ultimaker/Cura/issues/17798
https://github.com/Ultimaker/Cura/issues/17790
https://github.com/Ultimaker/Cura/issues/17787
https://github.com/Ultimaker/Cura/issues/17775
https://github.com/Ultimaker/Cura/issues/17675
https://github.com/Ultimaker/Cura/issues/17659
https://github.com/Ultimaker/Cura/issues/17645
https://github.com/Ultimaker/Cura/issues/17636
https://github.com/Ultimaker/Cura/issues/17635
https://github.com/Ultimaker/Cura/issues/17617
https://github.com/Ultimaker/Cura/issues/17613
https://github.com/Ultimaker/Cura/issues/17612
https://github.com/Ultimaker/Cura/issues/17595
https://github.com/Ultimaker/Cura/issues/17571
https://github.com/Ultimaker/Cura/issues/17567
https://github.com/Ultimaker/Cura/issues/17566
https://github.com/Ultimaker/Cura/issues/17552
https://github.com/Ultimaker/Cura/issues/17546
https://github.com/Ultimaker/Cura/issues/17538
https://github.com/Ultimaker/Cura/issues/17530
https://github.com/Ultimaker/Cura/issues/17526
https://github.com/Ultimaker/Cura/issues/17523
https://github.com/Ultimaker/Cura/issues/17509
https://github.com/Ultimaker/Cura/issues/17491
https://github.com/Ultimaker/Cura/issues/17490
https://github.com/Ultimaker/Cura/issues/17461  ??
https://github.com/Ultimaker/Cura/issues/17380
https://github.com/Ultimaker/Cura/issues/17343
https://github.com/Ultimaker/Cura/issues/17335
https://github.com/Ultimaker/Cura/issues/17253

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
