### ISSUE TITLE
Problems with last digits in Cura for OSX

### ISSUE THREAD

**Issue by eelcor** [Ultimaker/Cura#179]
I am not sure whether this applies to other platforms as well, but I have noticed several times that the last digit, when it is a zero gets omitted in the Gcode. 

This has been happening to both temperature (nozzle), speed (shell) and infill percentage. It results in really slow prints due to very low speeds (instead of 50mm/s the nozzle moves 5mm/s) or not printing at all (heating to 19 celsius instead of 190 celsius).

Kind regards,

Eelco Rouw

**Comment by nickthetait** [comment]
This one is related: https://github.com/Ultimaker/Cura/issues/168

Good find @eelcor !
