### ISSUE TITLE
5.4 will not slice file but does in 5.2. same file

### ISSUE THREAD

**Issue by Scage75** [Ultimaker/Cura#17909]
### Cura Version

5.4

### Operating System

windows 10

### Printer

ender 3

### Name abnormal settings

no setting change

### Describe model location

nope

### Describe your model

it is water tight. first time slicing it in 5.4 it will slice in 5.2 though

### Add your .zip here ⬇️

[Gaston_left_boot.zip](https://github.com/Ultimaker/Cura/files/13845316/Gaston_left_boot.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
