### ISSUE TITLE
Failed to slice this

### ISSUE THREAD

**Issue by jdeslaur68** [Ultimaker/Cura#17907]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

S5

### Name abnormal settings

nope

### Describe model location

Sliced at 50% it's size, but failed at 100%, and 90%

### Describe your model

Customer has, now trying to reproduce issue they encountered.

### Add your .zip here ⬇️

[UMS5_cinderwing3d-nightmare-tower2.zip](https://github.com/Ultimaker/Cura/files/13842377/UMS5_cinderwing3d-nightmare-tower2.zip)

We fixed printhead from a flood, but customer had a failure on first print.  Failed within 4-5 hours (4 day print).  Already did a simple 7 hour print, no issue.  So now slicing their STL but fails to slice, tried 90% size failed, 50% worked.  Seems to be a memory hog, and slows down my whole computer.  If this is because there's lacking available memory, or anything like that.  Error should be more descriptive.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
