### ISSUE TITLE
Cannot slice any STL with 5.6.0

### ISSUE THREAD

**Issue by Lwrs10** [Ultimaker/Cura#17906]
### Cura Version

5.6.0

### Operating System

Windows 10, Windows 11

### Printer

Ender 5 Plus, Ender 5 Pro, Robo3DR1+

### Name abnormal settings

No

### Describe model location

No

### Describe your model

Yes I have. Files are watertight. Works perfectly fine on 5.4.0

### Add your .zip here ⬇️

After updating to Cura 5.6.0, no STL files will slice. No matter what profile or printer I select, and even using a preloaded printer setup and no changes to the machine or profile settings. 

I also tried installing Cura 5.6.0 on a fresh installation of Windows 10. The only program I loaded is Cura 5.6.0. No change

Cura just says "slicing" and never actually finishes. Sometimes it will show a settings error, but does not show what settings need to be corrected. 
![errors](https://github.com/Ultimaker/Cura/assets/155734224/a2859ee6-ca85-4e46-969d-c10cd23fce1a)

Reinstalling Cura 5.4.0 on both instances works fine. No errors, and can slice files as normal. 

[CE5P_Stand.zip](https://github.com/Ultimaker/Cura/files/13841425/CE5P_Stand.zip)
[cura.zip](https://github.com/Ultimaker/Cura/files/13841428/cura.zip)

**Comment by 5axes** [comment]
No issue on Windows 10 .. an other Windows 11 issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

![image](https://github.com/Ultimaker/Cura/assets/11015345/83c90878-6c10-4c3b-b9b3-2374112a0bc8)

Duplicate  Slice Failed on **Windows 11**

https://github.com/Ultimaker/Cura/issues/17895
https://github.com/Ultimaker/Cura/issues/17818
https://github.com/Ultimaker/Cura/issues/17801
https://github.com/Ultimaker/Cura/issues/17798
https://github.com/Ultimaker/Cura/issues/17790
https://github.com/Ultimaker/Cura/issues/17787
https://github.com/Ultimaker/Cura/issues/17775
https://github.com/Ultimaker/Cura/issues/17675
https://github.com/Ultimaker/Cura/issues/17659
https://github.com/Ultimaker/Cura/issues/17645
https://github.com/Ultimaker/Cura/issues/17636
https://github.com/Ultimaker/Cura/issues/17635
https://github.com/Ultimaker/Cura/issues/17617
https://github.com/Ultimaker/Cura/issues/17613
https://github.com/Ultimaker/Cura/issues/17612
https://github.com/Ultimaker/Cura/issues/17595
https://github.com/Ultimaker/Cura/issues/17571
https://github.com/Ultimaker/Cura/issues/17567
https://github.com/Ultimaker/Cura/issues/17566
https://github.com/Ultimaker/Cura/issues/17552
https://github.com/Ultimaker/Cura/issues/17546
https://github.com/Ultimaker/Cura/issues/17538
https://github.com/Ultimaker/Cura/issues/17530
https://github.com/Ultimaker/Cura/issues/17526
https://github.com/Ultimaker/Cura/issues/17523
https://github.com/Ultimaker/Cura/issues/17509
https://github.com/Ultimaker/Cura/issues/17491
https://github.com/Ultimaker/Cura/issues/17490
https://github.com/Ultimaker/Cura/issues/17461  ??
https://github.com/Ultimaker/Cura/issues/17380
https://github.com/Ultimaker/Cura/issues/17343
https://github.com/Ultimaker/Cura/issues/17335
https://github.com/Ultimaker/Cura/issues/17253

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
