### ISSUE TITLE
Problems with this model when addiding supports

### ISSUE THREAD

**Issue by hamboy75** [Ultimaker/Cura#17901]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Anycubic Kobra 2 PRO

### Describe your model

It sliced before but when adding supports it fails

### Add your .zip here ⬇️

[CFFFP_Spoolholder-triangle_female.zip](https://github.com/Ultimaker/Cura/files/13834409/CFFFP_Spoolholder-triangle_female.zip)

**Comment by 5axes** [comment]
No issue for me with the project provided :
![image](https://github.com/Ultimaker/Cura/assets/11015345/7db569d5-c4e1-4b6f-b716-03a89d71b0e7)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
