### ISSUE TITLE
Naruto Mountains

### ISSUE THREAD

**Issue by Gonzor666** [Ultimaker/Cura#17904]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Artillery Sidewinder X1

### Describe your model

A mountain model reduced to 86%

### Add your .zip here ⬇️

[ASX1_montaña.zip](https://github.com/Ultimaker/Cura/files/13836160/ASX1_montana.zip)

**Comment by 5axes** [comment]
An other  Part position issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

![image](https://github.com/Ultimaker/Cura/assets/11015345/8aed61cf-239f-4942-bcd2-454f7c0d9ea4)

Duplicate Slicing success can be Part position dependant 

https://github.com/Ultimaker/Cura/issues/17853
https://github.com/Ultimaker/Cura/issues/17697
https://github.com/Ultimaker/Cura/issues/17682
https://github.com/Ultimaker/Cura/issues/17670
https://github.com/Ultimaker/Cura/issues/17610
https://github.com/Ultimaker/Cura/issues/17598
https://github.com/Ultimaker/Cura/issues/17494
https://github.com/Ultimaker/Cura/issues/17473
https://github.com/Ultimaker/Cura/issues/17466

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
