### ISSUE TITLE
Slicing Issue

### ISSUE THREAD

**Issue by darkmoonx1** [Ultimaker/Cura#17914]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality CR10S-Pro

### Describe your model

It has been sliced before. 

### Add your .zip here ⬇️

[CCR10SPRO_Cover.zip](https://github.com/Ultimaker/Cura/files/13848588/CCR10SPRO_Cover.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
