### ISSUE TITLE
Slicing with Tree type support doesn't always work

### ISSUE THREAD

**Issue by WhatNot911** [Ultimaker/Cura#17916]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Elegoo Neptune 3 Pro

### Name abnormal settings

Support Type

### Describe model location

It does slice if I rotate it 90 degrees. It doesn't slice if I move it away.

### Describe your model

It's a M-Lok picatinny rail

### Add your .zip here ⬇️

[EN3PRO_m-lok-picatinny-rail.zip](https://github.com/Ultimaker/Cura/files/13849746/EN3PRO_m-lok-picatinny-rail.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
