### ISSUE TITLE
CrealityBelt don't start on macOS 13.5.2

### ISSUE THREAD

**Issue by RubbaCippi** [Ultimaker/Cura#17919]
### Cura Version

3.6

### Operating System

macOS Ventura 13.5.2

### Printer

Creality CR-30

### Reproduction steps

1) Download CrealityBelt from the Creality page;
2) mount the CrealityBelt.dmg;
3) drag CrealityBelt into the Application folder;
4) goto Application folder, double click onto CrealityBelt;
5) Observe that noting happen;
6) Open Activity Monitor;
7) in the search box type "Creality";
8) a blank page will open;
9) launch CrealityBelt;
10) observe that the icon of CrealityBelt show up for a few seconds, then disappear.

No log is created, neither the folder "cura" inside Application Support.
I don't have any chance to test on previous mac OS

Observe that Creality Slicer and Creality Printer run as expected; indeed they don't support CR-30 belt printer

### Actual results

Nothing

### Expected results

That the application start and show me the application windows, as do the Windows version I am able to run under Parallels

### Add your .zip and screenshots here ⬇️

[Screenshot 2024-01-06 alle 17.28.55.zip](https://github.com/Ultimaker/Cura/files/13850361/Screenshot.2024-01-06.alle.17.28.55.zip)

**Comment by fieldOfView** [comment]
There is nothing Ultimaker or the devs here can do to fix CrealityBelt. That's a different application, by a different manufacturer.
