### ISSUE TITLE
Slicing Failed with Unexpected Error

### ISSUE THREAD

**Issue by bricomp** [Ultimaker/Cura#17928]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Elegoo Neptune 4 Pro #2

### Name abnormal settings

Tree Supports - Touching Buildplate

### Describe model location

Fails independant of location

### Describe your model

Model is Watertight

### Add your .zip here ⬇️

[EN4PRO_M.0001.0006.004 - MainsDetectBoardSupport.zip](https://github.com/Ultimaker/Cura/files/13853430/EN4PRO_M.0001.0006.004.-.MainsDetectBoardSupport.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
