### ISSUE TITLE
Cannot slice when choosing restored profile.

### ISSUE THREAD

**Issue by tomasz-darlowski** [Ultimaker/Cura#17925]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 6

### Name abnormal settings

I restore profile from other computer (Same version of Cura). It works on default profiles.

### Describe model location

Doesn't matter

### Describe your model

In default profile it's ok

### Add your .zip here ⬇️

[CE6_new_front_mount_.zip](https://github.com/Ultimaker/Cura/files/13853032/CE6_new_front_mount_.zip)

**Comment by tomasz-darlowski** [comment]
I figure it out that issue was on tree support with minimum branch angle set to 65 degree. On 45 degree it passed

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
