### ISSUE TITLE
Slicing Fails on some STLs with Tree Supports enabled. 

### ISSUE THREAD

**Issue by boogieman2048** [Ultimaker/Cura#17932]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Kobra 2 Max

### Name abnormal settings

None that I know of

### Describe model location

No

### Describe your model

Support Test Object

### Add your .zip here ⬇️

[Support_test.zip](https://github.com/Ultimaker/Cura/files/13854377/Support_test.zip)
![UltiMaker-Cura_esXRZROAOy](https://github.com/Ultimaker/Cura/assets/77519525/212504ae-0f5a-4016-9c79-52fa16a57620)

Slicing fails when tree supports on some models. Happen on random STLs. Some I can change size or angel and it is ok. 
[Support_test_STL.zip](https://github.com/Ultimaker/Cura/files/13854387/Support_test_STL.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
