### ISSUE TITLE
Unable to Slice any Model. Even Models that sliced before 

### ISSUE THREAD

**Issue by cartman-sp69** [Ultimaker/Cura#17933]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Kossel Linear Plus

### Name abnormal settings

none Tried diggerant profiles same error

### Describe model location

Centre and Tried Rotating 

### Describe your model

Same error with multiple models Basic Models

### Add your .zip here ⬇️

[AKLP_Mitre Adapter.zip](https://github.com/Ultimaker/Cura/files/13854909/AKLP_Mitre.Adapter.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
