### ISSUE TITLE
Slicing failed with unexpected error. 

### ISSUE THREAD

**Issue by orsty3001** [Ultimaker/Cura#17935]
### Cura Version

5.6.0

### Operating System

Linux Mint 21.2

### Printer

Ender Pro 3

### Name abnormal settings

It's when I rotate the peice. 

### Describe model location

Rotated on the Y plane 90 degrees. 

### Describe your model

It randomly throws this error. 

### Add your .zip here ⬇️

[CE3PRO_Cyber Deck Bezel v9.3.zip](https://github.com/Ultimaker/Cura/files/13855220/CE3PRO_Cyber.Deck.Bezel.v9.3.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
