### ISSUE TITLE
[5.5.0] Multiple layer shifts on two printers

### ISSUE THREAD

**Issue by eholley** [Ultimaker/Cura#17957]
### Cura Version

5.5.0

### Operating System

macOS Sonoma 14.2.1 Apple Silicon

### Printer

Ender 3 + Custom CoreXY

### Reproduction steps

I'm running two printers that are normally reliable. One is an Ender 3 with an upgraded hot end. The other is a custom built CoreXY.

In the photos, the Ender 3 uses white filament and the CoreXY uses blue.

![ender-photo](https://github.com/Ultimaker/Cura/assets/946105/a093ab47-76db-4978-94ec-52ca31ac6e7a)

![corexy-photo](https://github.com/Ultimaker/Cura/assets/946105/a33095d6-73f8-4486-b7b3-f6fc75bf5042)

The part (an arm for a control pad) was imported as a mesh into Cura from Fusion 360; which is my normal workflow.

Slicing was performed for each printer using almost identical profiles.

I tested both printers three times and both failed three times, both experiencing multiple layer shifts per print run.

Printing at 50mm/s.

Observing the CoreXY prints (blue filament), the shift seemed to occur around a certain location. The same may have occurred on the Ender prints. The print head seemed to pause for a moment, jitter, then move to a nearby location at breakneck speed, which caused the steppers to dramatically skip--on both printers.

Looking at the G-code, the skips seem to occur at the same location in each layer for at least 8mm of layers. The first occurrence is in lines 13556-13558 of `arm-ender.gcode`:

```
13556: G1 X110.494 Y152.01 E355.44121
13557: G0 F9000 X110.51 Y152.308
13558: G0 X108.382 Y159.098
``` 

<img width="779" alt="13556" src="https://github.com/Ultimaker/Cura/assets/946105/b2e61273-f432-4671-9eef-b65920f2c70c">

<img width="777" alt="13557" src="https://github.com/Ultimaker/Cura/assets/946105/51006ba8-8089-4090-bd73-f8b892186d45">

<img width="776" alt="13558" src="https://github.com/Ultimaker/Cura/assets/946105/a301dc20-832b-4bea-98fb-313ee5a153f2">

The small but fast (F9000) jump from X110.494 Y152.01 to X110.51 Y152.308, then immediately jumping to X108.382 Y159.098, caused both machines to layer shift. Which is interesting because the machines are different kinematics, yet both performed the same way.

I've attached 3MF, G-code, and photos.

### Actual results

Layer shifts

### Expected results

No layer shifts ;)

### Add your .zip and screenshots here ⬇️

[Archive.zip](https://github.com/Ultimaker/Cura/files/13878234/Archive.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Just so we are clear here - speeds in a gcode file are expressed in millimeters / minute.
G0 lines are travel lines and G1 lines are extrusion lines.  The lines you highlighted "G0 F9000..." are travel moves at 150mm/sec.
Your Cura settings are:
Initial Layer ~ Print Speed 30mm/sec (1800mm/min) and Travel Speed 150mm/sec (9000mm/min)
Other Layers ~ Print Speed 25mm/sec (1500mm/min) with Infill Speed at 50mm/sec (3000mm/min) and the Travel Speed is 120mm/sec (7200mm/min)
I checked the speeds in the gcode.  Your initial layer speeds are right there with your settings.  The same is true for the higher layers in that they match your settings.
I sliced the project file with the Ender active and got this with my post processor.
;  The speed ranges for this print are
;  Initial Layer Speeds
;      Max Travel Speed: 120 mm/sec
;      Min Travel Speed: 120 mm/sec
;    Max Printing Speed: 30.0 mm/sec
;    Min Printing Speed: 25.0 mm/sec
;  The Speeds for the remainder of the file
;      Max Travel Speed: 120 mm/sec
;      Min Travel Speed: 120 mm/sec
;    Max Printing Speed: 50.0 mm/sec
;    Min Printing Speed: 11.9 mm/sec

Your Acceleration setting of 1000mm/sec² and Jerk setting of 8mm/sec are reasonable and both printers should handle that with no problem.  Those are about what I use with my Ender 3 Pro.

So I just don't see a problem with the Cura generated gcode.  The speeds are as you have set them.
I agree that it is problematic that this is happening with two printers, but it does not appear to be anything in the gcode.  I'm sure I could print that file with no problem on my Ender.

Here is a graph of the extrusion speeds in your "arm-ender.gcode" file:
![1 Speed](https://github.com/Ultimaker/Cura/assets/64202104/e07a5135-48ad-4e29-97c0-8b10eec2ada3)

Here is a graph of the "arm-corexy.gcode" file.  There is very little difference between this one and the Ender.
![2 core Speed](https://github.com/Ultimaker/Cura/assets/64202104/931988e8-1903-498f-86d9-5dd98e2b0297)

Here is a screenshot of my slice of the project file.  The infill shows at 50mm/sec and all other extrusions at 25mm/sec.
![image](https://github.com/Ultimaker/Cura/assets/64202104/d104d892-b0d1-44fe-bc48-49f22c650cb3)

This is a screenshot of your "arm-ender.gcode" file.  Looks the same to me.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a9625509-25ed-4af0-a196-a77d27d0dd78)

I'm inclined to remove the bug label and close this as neither of your gcode files, nor the one I generated, are showing any variations from your settings.
