### ISSUE TITLE
Hand Slicing Failed

### ISSUE THREAD

**Issue by tristan-cox** [Ultimaker/Cura#17950]
### Cura Version

5.5.0

### Operating System

Ubuntu 20.04.6 Intel Graphics 620

### Printer

Ultimaker S3

### Name abnormal settings

Using the balanced profile

### Describe your model

Hand from thingiverse

### Add your .zip here ⬇️

[UMS3_indice_02.zip](https://github.com/Ultimaker/Cura/files/13865807/UMS3_indice_02.zip)

**Comment by jellespijker** [comment]
Thank you for reporting this, I can indeed confirm that the model crashes in Cura 5.5.0. Slicing it on our development version 5.7.0-alpha.0+30708a seems to slice as expected. I will close this is issue as fixed for the upcoming released version.
