### ISSUE TITLE
slicing fails when scaling model to 150%

### ISSUE THREAD

**Issue by Yossi** [Ultimaker/Cura#17951]
### Cura Version

5.6.0

### Operating System

ubuntu 22.04

### Printer

ender 3 s1 pro

### Describe your model

slices fine when scaled to 146% or less. fails at any greater scale.

### Add your .zip here ⬇️

[CE3S1PRO_Blade.zip](https://github.com/Ultimaker/Cura/files/13866148/CE3S1PRO_Blade.zip)

**Comment by jellespijker** [comment]
Thank you for reporting, I can indeed confirm that the engine crashes in 5.6.0. However testing it on our working development version 5.7.0-alpha.0+30708a seems to slice the model correctly. I will close this issue as fixed for our upcoming 5.7.0 release.

![image](https://github.com/Ultimaker/Cura/assets/8535734/4b4dbb9c-8cd1-4a49-a2b4-d7afa5795fe4)

@MariMakes fyi
