### ISSUE TITLE
erreur de découpe

### ISSUE THREAD

**Issue by Max70100** [Ultimaker/Cura#17956]
### Cura Version

5.5.0-beta1

### Operating System

Windows 11

### Printer

CUSTOM FFF Printer

### Describe your model

Oui j ai essayé de le découper avec cura elegoo et cela fonctionne

### Add your .zip here ⬇️

[CFFFP_Lion_wall_lighting_plug_.zip](https://github.com/Ultimaker/Cura/files/13877701/CFFFP_Lion_wall_lighting_plug_.zip)

**Comment by 5axes** [comment]
Pas mal juste le 6eme avec la même pièce : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7795637 
on va vraiment pouvoir établir un record. 
![image](https://github.com/Ultimaker/Cura/assets/11015345/aa02bf79-f232-469f-9239-f2a07d85f3e6)

Duplicate : 
https://github.com/Ultimaker/Cura/issues/17530
https://github.com/Ultimaker/Cura/issues/17310
https://github.com/Ultimaker/Cura/issues/16505
https://github.com/Ultimaker/Cura/issues/16497
https://github.com/Ultimaker/Cura/issues/16366
