### ISSUE TITLE
Error when  try to generate tree support

### ISSUE THREAD

**Issue by fogddragon** [Ultimaker/Cura#17972]
### Cura Version

5,6,0

### Operating System

Windows 10 Pro

### Printer

Elegoo Neptune 3 Pro

### Name abnormal settings

tree support

### Describe model location

it happens in any model location

### Describe your model

if i use  "normal" support it works

### Add your .zip here ⬇️

[EN3PRO_D20_Lid.zip](https://github.com/Ultimaker/Cura/files/13890728/EN3PRO_D20_Lid.zip)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
