### ISSUE TITLE
Slicing Flexi Dinosaur

### ISSUE THREAD

**Issue by axoibc** [Ultimaker/Cura#17979]
### Cura Version

5.6.0

### Operating System

MacOS Sonoma

### Printer

Ender 5

### Describe your model

No

### Add your .zip here ⬇️

[CE5__Flexi_Dino.3mf.zip](https://github.com/Ultimaker/Cura/files/13896507/CE5__Flexi_Dino.3mf.zip)

**Comment by jellespijker** [comment]
Thank you for reporting this issue, I can confirm that the project file still crashes with our latest internal build 5.7.0-alpha.0+3abb55 The crash is logged crash under Sentry issue [CURAENGINE-1W](https://ultimaker-o7.sentry.io/issues/4859878959/) for internal reference

A work around for this model is to uncheck Support, which isn't need

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
