### ISSUE TITLE
cube

### ISSUE THREAD

**Issue by Jimmybick** [Ultimaker/Cura#17976]
### Cura Version

5.6.0

### Operating System

Linux

### Printer

ender 3 v2

### Name abnormal settings

none

### Describe model location

no

### Describe your model

Calibration cube from Mesh tools

### Add your .zip here ⬇️

[calibration cube.zip](https://github.com/Ultimaker/Cura/files/13895575/calibration.cube.zip)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.

![image](https://github.com/Ultimaker/Cura/assets/8535734/e8d88a7a-7fe7-4e3f-9cfb-45614c94144c)

I'm closing this issue as fixed for the 5.7.0 release
