### ISSUE TITLE
i keep having failed slices

### ISSUE THREAD

**Issue by CommanderLeo14** [Ultimaker/Cura#17975]
### Cura Version

5.6.0

### Operating System

Mac OS Ventura

### Printer

Elegoo Neptune 3 pro

### Describe your model

its a spiderman 2099 helmet cut in half

### Add your .zip here ⬇️

[EN3PRO_Main(1).3mf.zip](https://github.com/Ultimaker/Cura/files/13895525/EN3PRO_Main.1.3mf.zip)
[EN3PRO_Main(2).3mf.zip](https://github.com/Ultimaker/Cura/files/13895527/EN3PRO_Main.2.3mf.zip)
i tried to do the helmet together but the slicing feature took forever (nearly 3 days) and it crashed and i had to start over and then when i cut the helmets in half, it kept crashing and showing an error in the file

**Comment by jellespijker** [comment]
It seems that your 3mf files are corrupt and beyond saving. Your best bet is to use the stl and start from scratch. If the problem still occurs. Please share the newly created 3mf file.

I'm closing this issue, but feel free to reopen it if it still is an issue with the new project file?
