### ISSUE TITLE
Tank Hull Printing, expected error 

### ISSUE THREAD

**Issue by DanielD03** [Ultimaker/Cura#17989]
### Cura Version

5.6.0

### Operating System

MacOS Catalina

### Printer

ender 3 pro

### Name abnormal settings

changed scale to 63.95%

### Describe model location

It did but not anymore 

### Describe your model

yes, printed upright by itself it did and tried to add multiple of the file in same manner and doesnt want to work

### Add your .zip here ⬇️

[Leopard AS1  - 5539793 (1).zip](https://github.com/Ultimaker/Cura/files/13911266/Leopard.AS1.-.5539793.1.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
