### ISSUE TITLE
Pro-1

### ISSUE THREAD

**Issue by PrakashLogan** [Ultimaker/Cura#17981]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3V2

### Describe your model

Big model.

### Add your .zip here ⬇️

[full-210mm-thicker-columns-fixedsepflag.zip](https://github.com/Ultimaker/Cura/files/13901619/full-210mm-thicker-columns-fixedsepflag.zip)

**Comment by jellespijker** [comment]
It seems the project file is one saved by PrusaSlicer. Can you Save the project file in Cura, and share that such that we have all the relevant settings and can check if it crashes on our latest internal build

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
