### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by reinvantveer** [Ultimaker/Cura#17992]
### Cura Version

5.6.0

### Operating System

Ubuntu 20.04.6 LTS

### Printer

UM S3

### Name abnormal settings

Using a custom profile, but the model does not slice anymore using any of the standard settings

### Describe model location

No orientation works anymore, even more thant 20 other orientations and build plate positions

### Describe your model

I have sliced successfully before, in Cura 5.2.2 (I still can) but it doesn't slice anymore in 5.3+. I have tried the Mesh Tools plugin, to no avail.

### Add your .zip here ⬇️

Please note that this model is not open data. It is © Antfield Creations, NL, all rights reserved.
Please contact me if you want to use this model, or you want a printed copy.

[Hij-boven-30k.zip](https://github.com/Ultimaker/Cura/files/13917796/Hij-boven-30k.zip)

Note 2: this model _used to slice_ using older versions of Cura.

Thank you for looking into this!

**Comment by jellespijker** [comment]
Thank you for reporting this issue, I can confirm that the project file still crashes with our latest internal build 5.7.0-alpha.0+3abb55 The crash is logged crash under Sentry issue [CURAENGINE-1V](https://ultimaker-o7.sentry.io/issues/4859823116/) for internal reference

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
