### ISSUE TITLE
1963 body

### ISSUE THREAD

**Issue by wmharbert** [Ultimaker/Cura#17995]
### Cura Version

Cura 5.6.1

### Operating System

Windows 10

### Printer

AnyCubic Vyper

### Name abnormal settings

no

### Describe model location

no

### Describe your model

yes in Cura 4.2.1

### Add your .zip here ⬇️

[body.zip](https://github.com/Ultimaker/Cura/files/13920969/body.zip)
[AV_body.zip](https://github.com/Ultimaker/Cura/files/13921080/AV_body.zip)

**Comment by jellespijker** [comment]
Thank you for reporting this issue, I can confirm that the project file still crashes with our latest internal build 5.7.0-alpha.0+3abb55 The crash is logged crash under Sentry issue [CURAENGINE-1T](https://ultimaker-o7.sentry.io/issues/4859810080/) for internal reference.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
