### ISSUE TITLE
slicing engine failed

### ISSUE THREAD

**Issue by schoubert** [Ultimaker/Cura#17991]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 4 Max

### Name abnormal settings

no and no

### Describe model location

no

### Describe your model

yes with a previous cura version

### Add your .zip here ⬇️

i have message " slicing engine stop to process" during slicing
[Uploading Buste ok 2024.zip…]()

**Comment by schoubert** [comment]
![Capture d'écran 2024-01-12 112938](https://github.com/Ultimaker/Cura/assets/59742743/8432e741-f8f5-4187-8773-aced5462264b)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
