### ISSUE TITLE
Cat hook fail slice

### ISSUE THREAD

**Issue by Iyakimaru** [Ultimaker/Cura#17998]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3-s1

### Name abnormal settings

Super Quality 0.12mm

### Describe model location

Center

### Describe your model

It is a model created by me, really quite simple.

### Add your .zip here ⬇️

[Gancho michi.zip](https://github.com/Ultimaker/Cura/files/13924790/Gancho.michi.zip)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.

![image](https://github.com/Ultimaker/Cura/assets/8535734/e0465c66-f297-42f3-948c-ebca290816d3)

I'm closing this issue as fixed for the 5.7.0 release

FYI @MariMakes
