### ISSUE TITLE
Slicing fails in 5.6.0 but fine in 5.3.1

### ISSUE THREAD

**Issue by daverave999** [Ultimaker/Cura#17994]
### Cura Version

5.6.0

### Operating System

Linux Mint; have uploaded system info file too.

### Printer

Ender 3 v2

### Name abnormal settings

N/A

### Describe model location

Will not slice in any orientation or position. Have tried scaling too.

### Describe your model

No mesh problems reported by Meshtools. Slices fine in 5.3.1

### Add your .zip here ⬇️

File is from https://www.printables.com/model/75759-cat-litter-scoop
Slices fine in Cura 5.3.1 with exactly same settings.

[Cat litter scoop with longer handle Generic PETG lw 0.6mm lh 0.4mm if 100% ext1 240C bed 90C.zip](https://github.com/Ultimaker/Cura/files/13920345/Cat.litter.scoop.with.longer.handle.Generic.PETG.lw.0.6mm.lh.0.4mm.if.100.ext1.240C.bed.90C.zip)

[systemInfo.txt](https://github.com/Ultimaker/Cura/files/13920383/systemInfo.txt)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.

![image](https://github.com/Ultimaker/Cura/assets/8535734/eedf1d01-22f6-4062-85bd-ec3d07eaf585)

I'm closing this issue as fixed for the 5.7.0 release

FYI @MariMakes
