### ISSUE TITLE
cura 2.5 no shortcut or files on Windows 10 64bit

### ISSUE THREAD

**Issue by Wirelessmikey** [Ultimaker/Cura#1800]
After installing cura 2.5 on win 10, there is no 
Cura shortcut, look in program files there is no cura folder. No cura app in control panel, there was a windows critical update on May 1st. Now restoring windows to April 23rd two checkpoints ago. If anyone knows of any win 10 issues with cura 2.5 please share!!.

**Comment by Ghostkeeper** [comment]
Haven't seen this on our side. We cannot reproduce :(

**Comment by Wirelessmikey** [comment]
Restored my pc, 2.5 & 2.4 start up, than when loading an stl, cura states not responding where I have to close cura in task manager.

**Comment by Ghostkeeper** [comment]
Don't know how to debug this for you... Is there a log file?

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.
