### ISSUE TITLE
crash while slicing

### ISSUE THREAD

**Issue by B-mxm** [Ultimaker/Cura#18004]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3 s1 pro

### Describe your model

slicing won't work. not even after mesh repair.

### Add your .zip here ⬇️

[CFFFP_gsfr-rearexit-bottom-ruinB-part1.zip](https://github.com/Ultimaker/Cura/files/13927816/CFFFP_gsfr-rearexit-bottom-ruinB-part1.zip)

**Comment by jellespijker** [comment]
Thank you for reporting this issue, I can confirm that the project file still crashes with our latest internal build `5.7.0-alpha.0+3abb55` The crash is logged crash under Sentry issue [CURAENGINE-1R](https://ultimaker-o7.sentry.io/issues/4855843759/) for internal reference

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
