### ISSUE TITLE
Error with support interface

### ISSUE THREAD

**Issue by suelenbraga2006** [Ultimaker/Cura#18007]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Hypercube

### Name abnormal settings

support interface > support roof

### Describe model location

Yes, if I move it away from the center of the buildplate

### Describe your model

It's a part of a slip ring for my ffb steering wheel

### Add your .zip here ⬇️

[CFFFP_parte sobrepor.zip](https://github.com/Ultimaker/Cura/files/13928752/CFFFP_parte.sobrepor.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
