### ISSUE TITLE
I have a bug.

### ISSUE THREAD

**Issue by samat35** [Ultimaker/Cura#18006]
### Cura Version

5.2.1

### Operating System

windows 10

### Printer

Creality Ender-3 v2 

### Name abnormal settings

Yes I changed supports setting. No.

### Describe model location

Yes

### Describe your model

No, yes, no

### Add your .zip here ⬇️

[CE3E3V2_resheto1.zip](https://github.com/Ultimaker/Cura/files/13928533/CE3E3V2_resheto1.zip)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased `5.7.0-alpha.0+3abb5` which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.

![image](https://github.com/Ultimaker/Cura/assets/8535734/e73b13ca-0a0c-428d-9ce4-27c81ad31977)

You indicated that you're using version 5.2.1 maybe you could try to slice it in our latest release 5.6.0 

I'm closing this issue as fixed for the 5.7.0 release

FYI @MariMakes
