### ISSUE TITLE
Slicing failed when switching to tree supports

### ISSUE THREAD

**Issue by dorkn1nja** [Ultimaker/Cura#18009]
### Cura Version

5.6.0

### Operating System

Microsoft Windows 10 Home (x64) Build 19045.3930 (22H2)

### Printer

Elegoo Neptune 4 Pro

### Name abnormal settings

switched from normal to tree support

### Describe model location

tried 15, 45, and 90° z-axis rotation, all failed

### Describe your model

hopper insert for Timemore Sculptor 078s coffee grinder

### Add your .zip here ⬇️

The STL that is failing is "Timemore_Sculptor_Hopper_Insert_V2_[TABS.stl" in the attached. 
[Timemore_Sculptor_078_S__Hopper_Insert_6395248.zip](https://github.com/Ultimaker/Cura/files/13928924/Timemore_Sculptor_078_S__Hopper_Insert_6395248.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
