### ISSUE TITLE
Error slicing model

### ISSUE THREAD

**Issue by asafyos** [Ultimaker/Cura#18017]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Custom printer - Kywoo Tycoon slim

### Name abnormal settings

using tree supports for the model

### Describe your model

The model sliced succesfully before, with some different settings 

### Add your .zip here ⬇️

[Octopus_spiral_error.zip](https://github.com/Ultimaker/Cura/files/13932160/Octopus_spiral_error.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
