### ISSUE TITLE
Failed to slice right after slicing a different file

### ISSUE THREAD

**Issue by trinitybat** [Ultimaker/Cura#18012]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Neptune 4 Pro customer profile

### Describe your model

bottom case for a raspberry pi 3 B+

### Add your .zip here ⬇️

[CFFFP_bottom_hex_mm2_color1.zip](https://github.com/Ultimaker/Cura/files/13929309/CFFFP_bottom_hex_mm2_color1.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
