### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by adoeller** [Ultimaker/Cura#18011]
[TT_mic halter.zip](https://github.com/Ultimaker/Cura/files/13929034/TT_mic.halter.zip)
### Cura Version

5.6.0

### Operating System

Windows

### Printer

Tevo Tornado

### Describe your model

sucessfully sliced before.

### Add your .zip here ⬇️

[TT_Clip Lichterkette v2.zip](https://github.com/Ultimaker/Cura/files/13929027/TT_Clip.Lichterkette.v2.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by adoeller** [comment]
I switched to orca slicer (and an other printer)
