### ISSUE TITLE
Slincing failed on 5.6, while everything works on 5.4

### ISSUE THREAD

**Issue by mroelandts** [Ultimaker/Cura#18016]
### Cura Version

5.6.0

### Operating System

Ubuntu 22.04.3 LTS

### Printer

Creality Enter-3 Pro

### Name abnormal settings

No, same settings as with the 5.4 release

### Describe model location

center

### Describe your model

Nothing special

### Add your .zip here ⬇️

[CE3PRO_jan_2_battery.zip](https://github.com/Ultimaker/Cura/files/13931675/CE3PRO_jan_2_battery.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by mroelandts** [comment]
Issues are still present in 5.7.0
