### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by zIlgar** [Ultimaker/Cura#18015]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Creality Ender 3v2

### Describe your model

mini snowman maker

### Add your .zip here ⬇️

[snowman_maker_right_side.zip](https://github.com/Ultimaker/Cura/files/13930709/snowman_maker_right_side.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
