### ISSUE TITLE
Different Stls give same error, on m1 Mac Pro with latest Cura ver. Error msg asked "bug" be reported

### ISSUE THREAD

**Issue by scififan42** [Ultimaker/Cura#18014]
### Cura Version

Cura 5.6.0

### Operating System

Sonoma 14.2.1

### Printer

Anycubic vyper

### Name abnormal settings

d/l cura 5.6.0, so had latest version

### Describe model location

no

### Describe your model

No, Yes, have not tried mesh fix.

### Add your .zip here ⬇️

Got this free file from 3dcults, d/l latest Cura version as running on a Mac Pro m1.. tried opening / loading several stls and all are generating same error msg and refusing to slice. Had no probs on Intel Mac with earlier Cura version, and I am using the latest version in same way. When not slicing got msg asking me to report this, so did so and hope it's not wasting your time? thanks.

[AV_Dalek 2005 Version In Basic Setting.3mf.zip](https://github.com/Ultimaker/Cura/files/13929800/AV_Dalek.2005.Version.In.Basic.Setting.3mf.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
