### ISSUE TITLE
Large Build Volume Slicing Failed

### ISSUE THREAD

**Issue by educatedengineer** [Ultimaker/Cura#18022]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 4 Plus 

### Name abnormal settings

NA

### Describe model location

Slices without supports

### Describe your model

Slices without supports

### Add your .zip here ⬇️

[helmet_crash.zip](https://github.com/Ultimaker/Cura/files/13933015/helmet_crash.zip)

Anytime there is a model with a large volume the slicer fails when adding supports. Works fine without supports.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
