### ISSUE TITLE
Show height next to layer count

### ISSUE THREAD

**Issue by Shaische** [Ultimaker/Cura#1805]
Since velocity printing just came out and is gaining traction... See the following links:

https://www.velocitypainting.xyz/blog/
https://www.velocitypainting.xyz/gui/download.html

It would be nice if Cura showed the height in mm next to the layer count when viewing the model in layer mode. This would allow someone who does Velocity printing to easily figure out how high they should position their image on the print when defining Z offset.

**Comment by BagelOrb** [comment]
We're not going to implement this.
IT's not that difficult if you want to give it a try, though.
You might want to create a pull request in github/com/Ultimaker/CuraEngine
