### ISSUE TITLE
Tree Support causes crash

### ISSUE THREAD

**Issue by BlueSteel04** [Ultimaker/Cura#18075]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3

### Name abnormal settings

Tree support

### Describe model location

Middle of plate

### Describe your model

Yes, not with Tree

### Add your .zip here ⬇️

[CE3E3V2_Solar Panel ARM v1.zip](https://github.com/Ultimaker/Cura/files/13986093/CE3E3V2_Solar.Panel.ARM.v1.zip)
It's not only with this model. Sometimes I can change the tree slightly to make it work, but I have not been successful this time.

**Comment by 5axes** [comment]
Classic tree support error on versions 5.5 & 5.6 test on 5.7 Alpha  : https://github.com/Ultimaker/Cura/discussions/18080

![image](https://github.com/Ultimaker/Cura/assets/11015345/5500a0ac-8e69-405b-a985-3bdf1a91df9d)

**Comment by BlueSteel04** [comment]
> Classic tree support error on versions 5.5 & 5.6 test on 5.7 Alpha : #18080
> 
> ![image](https://private-user-images.githubusercontent.com/11015345/298398273-5500a0ac-8e69-405b-a985-3bdf1a91df9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NjU2ODAsIm5iZiI6MTcwNTk2NTM4MCwicGF0aCI6Ii8xMTAxNTM0NS8yOTgzOTgyNzMtNTUwMGEwYWMtOGU2OS00MDViLWE5ODUtM2JkZjFhOTFkZjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDIzMTYyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMWFmYTRlODkwMzhkNDc1NjM1NmFhZmVmMDZlNzk5MDIyNzc0OTEwNzhmNWI5ZGI4N2Q3MDQ2MDZiOGRjYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ML5KaSCF7id1v7QNV_JN9qK0mxeuGPD5LxEqe6vyZ20)

Thank you!
