### ISSUE TITLE
5.6.0 and 5.5.0 AppImages Ui Error.

### ISSUE THREAD

**Issue by richardwolfe4991** [Ultimaker/Cura#18084]
### Cura Version

5.5.0 && 5.6.0

### Operating System

Artix Linux

### Printer

N/A

### Reproduction steps

1. Download `UltiMaker-Cura-5.6.0-linux-X64.AppImage`
2. Set `UltiMaker-Cura-5.6.0-linux-X64.AppImage` executable permissions.
3. Launch `UltiMaker-Cura-5.6.0-linux-X64.AppImage` using terminal.

### Actual results

Cura 5.6.0 Splash Screen shows up, but disappears after "loading UI..."

The cura app seems to be "running" as the process for it doesn't terminate and continues to run despite the UI for the application never launching.

The same issue occurs with `UltiMaker-Cura-5.5.0-linux-X64.AppImage`.

Oddly, `UltiMaker-Cura-5.4.0-linux-modern.AppImage` works fine.

### Expected results

Cura 5.6.0 and Cura 5.5.0 launch properly and are usable.

## Additional Details

Oddly, Cura 5.4.0-linux-modern seems to work fine on my system. Wondering what changed between 5.4.0-linux-modern and 5.5.0/5.6.0 that could have broken the UI for me? Terminal doesn't seem to give much info other than:
```
Gtk-Message: Failed to load module "xapp-gtk3-module"
Gtk-Message: Failed to load module "xapp-gtk3-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
```
But those seem to show on even the working 5.4.0.

The other notable errors that only show up on 5.5.0 and 5.6.0 are:
```
QQmlApplicationEngine failed to load component
QQmlComponent: Component is not ready
```
### Add your .zip and screenshots here ⬇️

![cura_troubleshooting_5 4](https://github.com/Ultimaker/Cura/assets/11876053/743ae1b4-b337-4f35-8298-1c9a68f654d6)
![cura_troubleshooting_5 5](https://github.com/Ultimaker/Cura/assets/11876053/04c3c8c9-39c1-4b3c-8503-0357c19bc70d)
![cura_troubleshooting_5 6](https://github.com/Ultimaker/Cura/assets/11876053/29fe506d-0179-47b4-9b8b-89098449fb0d)

**Comment by fieldOfView** [comment]
Please add your logs:

https://github.com/Ultimaker/Cura/wiki/Reporting#cura-log
