### ISSUE TITLE
Official Support for Elegoo Neptune 4, 4 pro, 4 max

### ISSUE THREAD

**Issue by liluzibird** [Ultimaker/Cura#18093]
### Is your feature request related to a problem?

No current support for Elegoo Neptune 4, 4 pro, and 4 max.

### Describe the solution you'd like

Official support for Elegoo Neptune 4, 4 pro, and 4 max when adding printer in Cura.

### Describe alternatives you've considered

Change bed size, speed, and other configs listed in [Elegoo Cura](https://github.com/maltejur/elegoo-cura).

### Affected users and/or printers

Users who use Elegoo Neptune 4, 4 pro, 4 max.

### Additional information & file uploads

https://github.com/maltejur/elegoo-cura

**Comment by GregValiant** [comment]
The definitions come from members of the community or from the printer manufacturer.
There is a pull request to add the Neptune 4 and 4 Pro to Cura.  It's [HERE](https://github.com/search?q=repo%3AUltimaker%2FCura%20neptune%204&type=code).  It looks like those two models will be included in Cura 5.7.

I'll go ahead and close this as it appears it has been taken care of.
