### ISSUE TITLE
Error cura slicer

### ISSUE THREAD

**Issue by Feleec** [Ultimaker/Cura#18091]
### Cura Version

5.6.0

### Operating System

windows 10 pro

### Printer

Ender 3 v3 se

### Describe your model

wolverine claws

### Add your .zip here ⬇️

[wolverine-claws-with-grip-model_files.zip](https://github.com/Ultimaker/Cura/files/14002417/wolverine-claws-with-grip-model_files.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for project files because sometimes it's a setting issue and a project file contains all your Cura settings.
I didn't have any trouble slicing either STL in 5.6.0.
