### ISSUE TITLE
Printables Voronoi Useless Mug - macOS - Cura 5.6 - slicing failed

### ISSUE THREAD

**Issue by fspiper-home** [Ultimaker/Cura#18092]
### Cura Version

5.6.0

### Operating System

MacOS Ventura 13.6.3 on M1 Mac Mini

### Printer

Flsun Q5

### Name abnormal settings

n/a

### Describe model location

no

### Describe your model

no, no, tried mesh fix and slicing still failed

### Add your .zip here ⬇️

[Useless_Mug.3mf.zip](https://github.com/Ultimaker/Cura/files/14002522/Useless_Mug.3mf.zip)
[Useless_Mug.3mf.zip](https://github.com/Ultimaker/Cura/files/14002540/Useless_Mug.3mf.zip)

**Comment by saumyaj3** [comment]
e
