### ISSUE TITLE
Slicing Failed error after upgrading to v5.6.0

### ISSUE THREAD

**Issue by aordorica** [Ultimaker/Cura#18102]
### Cura Version

5.6.0

### Operating System

MacOS Sonoma 14.2.1

### Printer

Creality Ender-3 Pro

### Describe your model

Simple Calibration Cube

### Add your .zip here ⬇️

<img width="1796" alt="Screenshot 2024-01-22 at 4 26 44 PM" src="https://github.com/Ultimaker/Cura/assets/41565814/20a48651-3050-4b93-b53e-15f54c38b475">

**Comment by Asterchades** [comment]
Even if it may seem like a simple model, a project file with the exact model you've used is always going to be beneficial when it comes to diagnosing issues like this.

That said, try it again in the [just-released Cura 5.7 alpha](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-alpha.0). This build incorporates some fixes with regards to engine crashes like this, but it also incorporates additional logging facilities specifically to track down where these crashes are occurring. Note that this should not replace your existing installation as it hasn't been fully vetted by the Cura team, so keep your current install for more general usage and use this one only for diagnostic purposes.
