### ISSUE TITLE
Elegoo profile issues with M420 command in starting G-code

### ISSUE THREAD

**Issue by colin91473** [Ultimaker/Cura#18103]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 Max

### Reproduction steps

Myself as well as a large part of the Elegoo printer community with the Neptune series have had a lot of issues with corners of the prints warping and curling.. but it has been found in most cases its has to do with the M420 line of the starting G-Code being commented out by your Elegoo Printer profile author. We do not know why this was done. After removing the semicolon for the comment, the printers are no longer ignoring the printer bed leveling state. Your profile by default turns off bed leveling.. why? There is speculation that the bed leveling is firmware based. Which makes a lot of sense.. but if that is the case, then why are we seeing improvements with no other changes other than uncommenting out that command? If I'm not mistaken, whether or not the bed leveling command is woven in the firmware or not, it doesn't matter if it's in the g-code. If its in the firmware, good so be it.. if its not, then this will fix the issue.

### Actual results

Lifting corners and lack of using auto bed leveling. 

### Expected results

Bed leveling should be used preventing uneven first layers etc.. 

### Add your .zip and screenshots here ⬇️

I have nothing to add here.

**Comment by Asterchades** [comment]
The Cura team does not maintain any of the third party definitions - they simply lack the time and appropriate hardware to do so. Such definitions are entirely provided by the community through pull requests here on GitHub, so ultimately the Cura team can't really tell you why this was done either as they weren't responsible. There are minimum standards imposed but ultimately it's up to the community to both create and refine these definitions.

As such if you've found that adding (or not-commenting in this case) that particular command makes a noticeable improvement to both quality and reliability, and would be better suited to being the default behaviour, I would strongly encourage you to make a pull request with an appropriate change. The definition file for your particular printer can be found [here](https://github.com/Ultimaker/Cura/blob/main/resources/definitions/elegoo_neptune_3max.def.json).
