### ISSUE TITLE
slicing fails Cura 5.6 Kingroon KLP1 Cache

### ISSUE THREAD

**Issue by paulgiordano** [Ultimaker/Cura#18127]
### Cura Version

5.6

### Operating System

Linux

### Printer

Kingroon KLP1 Klipper

### Reproduction steps

selected printer, add an STL, slice, and get the error

### Actual results

Error message as on screen shot

### Expected results

A normal slice

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/14049353/cura.log)
[HMG7.4 Creality Spider 3 Pro Mount V6.zip](https://github.com/Ultimaker/Cura/files/14049376/HMG7.4.Creality.Spider.3.Pro.Mount.V6.zip)
![UltiMaker-Cura_gzFkjnfwci](https://github.com/Ultimaker/Cura/assets/19802449/e343f646-7bb4-45a5-8e49-17c0007c98f4)

**Comment by paulgiordano** [comment]
Tie this to Tree supports, everywhere, overhang 50, zigzag, 0.0 density. Actually it looks like tree support is broken in this instance, no matter what the other parameters are.

**Comment by nallath** [comment]
Could you try to use this build: https://github.com/Ultimaker/Cura/discussions/18080? 

If that doesn't fix it, we at least get more information about what is going wrong.

**Comment by paulgiordano** [comment]
That fixes it for me. Thanks for being so quick!
