### ISSUE TITLE
The anycubic kobra 2 neo aint on your printers?

### ISSUE THREAD

**Issue by EvilBilll** [Ultimaker/Cura#18136]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic kobra 2 neo

### Reproduction steps

The Anycubic kobra 2 neo ain't on your printers tab so I cant use my printer :(

### Actual results

The Anycubic kobra 2 neo ain't on your printers tab so I cant use my printer :(

### Expected results

The Anycubic kobra 2 neo ain't on your printers tab so I cant use my printer :(

### Add your .zip and screenshots here ⬇️

The Anycubic kobra 2 neo ain't on your printers tab so I cant use my printer :(

**Comment by GregValiant** [comment]
Thanks for the report.
UltiMaker can't can't be responsible for other manufacturers printers.  The definition files need to come from the manufacturer or a member of the community.  No one has submitted definition files for that printer.
I'll remove the bug label and close this.  I hope you understand.
