### ISSUE TITLE
Initial Layer Speed Partially Incorrect

### ISSUE THREAD

**Issue by wulfhednar02** [Ultimaker/Cura#18146]
### Cura Version

5.6.0

### Operating System

Kubuntu Linux

### Printer

Geeetech Mizar Pro 0.4mm nozzle

### Reproduction steps

1. Set all print speeds to 40mm/s
2. Set Initial Layer Speed to 10mm/s
3. Slice

### Actual results

Outer wall of the initial layer is 40mm/s.

Note: The model is not watertight and is dropped below the build plate level by -0.1mm

### Expected results

Expected all of the initial layer to be 10mm/s

### Add your .zip and screenshots here ⬇️

[dragon.zip](https://github.com/Ultimaker/Cura/files/14070414/dragon.zip)
![flow_equalization](https://github.com/Ultimaker/Cura/assets/47700032/f17519b1-0a61-4d1f-ae92-5f5cc1144499)
![no_flow_equalization](https://github.com/Ultimaker/Cura/assets/47700032/3a9e57e4-a08a-4c6b-8b7f-e591237e05f1)

**Comment by wulfhednar02** [comment]
I have also been experiencing issues with retraction being set but not being implemented in the gcode. The original and retraction problems go away when ever I make the values permanent values. The issue stated and the retraction become wrong whenever I set the settings to "Use material setting".

**Comment by GregValiant** [comment]
Thanks for the report.
The Initial layer speed problem has been reported previously (#17602 ).
That model has a lot of errors.  I would not trust it to slice correctly.
![image](https://github.com/Ultimaker/Cura/assets/64202104/6c2c9b81-9cfa-4ac3-9415-39ec97106aad)

In regards to the "Retraction" settings, I can't duplicate that.  When I click on "Use value from material" the current setting is correctly over-ridden by the setting of the current material "Transparent PETG" with a retraction speed of 80.

**Comment by wulfhednar02** [comment]
`I would not trust it to slice correctly.`
For sure.

The retraction settings always look correct. It was not until I actually printed the model that the I "see" the retraction is missing. Could be this model, but once I put the numbers back to manually entered, the retraction came back for this model.

**Comment by GregValiant** [comment]
When I slice the project (after repairing the model) there are 3475 retractions in the gcode (and a corresponding 3475 primes).
With the retraction distance of 1mm the extruder doesn't rotate very far to make the retraction.  It looks to be about 11° of rotation per mm of filament.  That would be pretty hard to see.
Post one of the gcode files that you feel is in error.  I have some analysis tools I can run it through.

I'll mark this as a duplciate report regarding the speed problem.  If the retraction issue seems like a bug it should go on a separate report.

**Comment by wulfhednar02** [comment]
Thank you. I have everything working at this moment, nothing seems to be lacking. I would say just close this issue and I will get more information if I run across the retraction thing again. I think it is a thing, but there is no telling where it could be if I do not have information for you to track it down. :stuck_out_tongue: I know what that is like...

**Comment by GregValiant** [comment]
I'll leave the "duplicate bug report" on this and go ahead and close it then.  Glad to hear things are working.
