### ISSUE TITLE
Cannot load any file

### ISSUE THREAD

**Issue by kayosx3** [Ultimaker/Cura#18175]
### Cura Version

5.6.0

### Operating System

linux

### Printer

ender 3 v2

### Reproduction steps

I have had cura before when i go to load in a file it will just crash as soon as i click file from disk it just crashes 

### Actual results

crash

### Expected results

open up the disk files so i can add a print 

### Add your .zip and screenshots here ⬇️

i did not take a screen shot

**Comment by nallath** [comment]
Can you provide us with more info? This isn't enough for us to debug it. We will need log files and/or the file that you used that caused this issue.
