### ISSUE TITLE
Slicing failed with unexpected error

### ISSUE THREAD

**Issue by chiefbueno88** [Ultimaker/Cura#18189]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo nepptune 4

### Describe your model

Yes.  Printer cable chain

### Add your .zip here ⬇️

[EN3_cableChain_link_v3.zip](https://github.com/Ultimaker/Cura/files/14111088/EN3_cableChain_link_v3.zip)

**Comment by nallath** [comment]
Duplicate of #18190
