### ISSUE TITLE
SECTIONATION FAILED

### ISSUE THREAD

**Issue by Mr1oV1eira** [Ultimaker/Cura#18184]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality Ender 3 S1

### Name abnormal settings

No, i just sliced 30 pieces of the stl and it runs ok. Now with 25 pieces gives me a error.

### Describe model location

I rotate 90 degrees and it is centered.

### Describe your model

Its a hat. Tradicional hat of Madeira Island.

### Add your .zip here ⬇️

[ERROR_PORTUGUESE.zip](https://github.com/Ultimaker/Cura/files/14105843/ERROR_PORTUGUESE.zip)

**Comment by Vandresc** [comment]
Could you try it again with this build: https://github.com/Ultimaker/Cura/discussions/18080 It doesn't contain a fix, but it has a lot more logging options, which will help us figure out what is going wrong. Thank you!
