### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by help2get** [Ultimaker/Cura#18194]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Geeetech thunder

### Name abnormal settings

Nope

### Describe model location

center of the build plate, just dragged from file folder

### Describe your model

doesn't matter the model won't slice a thing. 

### Add your .zip here ⬇️

Have been using Ultimaker Cura for about a month or so and so far, it has been great. But now the program wont slice anything doesn't matter what settings are changed, or what model is being prepared to slice. The bar graph gets about halfway then stops and reports back as an unknown error.

**Comment by Vandresc** [comment]
Could you try it again with this build: https://github.com/Ultimaker/Cura/discussions/18080 It doesn't contain a fix, but it has a lot more logging options, which will help us figure out what is going wrong. Thank you!
