### ISSUE TITLE
slice failed

### ISSUE THREAD

**Issue by princebass75** [Ultimaker/Cura#18209]
### Cura Version

5.5.0

### Operating System

win11

### Printer

ender3 neo max

### Name abnormal settings

none

### Describe model location

center

### Describe your model

110mm x 65mm x 25mm box

### Add your .zip here ⬇️

[cura.zip](https://github.com/Ultimaker/Cura/files/14139888/cura.zip)

**Comment by Vandresc** [comment]
Could you try it again with this build: https://github.com/Ultimaker/Cura/discussions/18080 It doesn't contain a fix, but it has a lot more logging options, which will help us figure out what is going wrong. Thank you!
