### ISSUE TITLE
Unable to restore default settings once profile saved

### ISSUE THREAD

**Issue by tcm0116** [Ultimaker/Cura#1820]
If I edit a setting in a profile and then save the profile, there doesn't appear to be any way to remove that override from the profile other than by manually editing the .cfg file externally to Cura.

**Comment by Ghostkeeper** [comment]
Indeed there is none. Should there be? I think the use case for this feature is very small.

You can set it back in the interface to whatever value the original profile had, but not if the original profile scaled in combination with other settings.

**Comment by tcm0116** [comment]
The most significant case is if the print temperature is changed and then the quality profile is saved. When that happens, the temperature defined I'm the selected material profile will never be utilized unless that setting is manually removed from the quality profile. 

Another case is for dynamically computed values. Once a manual value is entered and saved, there is no way to go back to using the dynamically computed value without manually editing the profile.

**Comment by nallath** [comment]
It should show an "i" icon next to the setting if its dynamicly calculated. Pressing that should restore the calculated value.

**Comment by tcm0116** [comment]
I didn't realize that. Thanks for pointing​ it out. 

I still think it would be nice to have a similar option for non-cannulated values.

**Comment by fieldOfView** [comment]
A long, long time ago, I drew up this:

![image](https://cloud.githubusercontent.com/assets/143551/25999176/5fb6fd84-3724-11e7-86b5-9d2a0ff2b904.png)

The ability to add/remove settings from a profile, and even edit the values of settings in profiles.

**Comment by nallath** [comment]
I don't think i ever saw that design. Shouldn't be that hard to implement. Especially not if you only want to  remove  a setting from a profile.

**Comment by tcm0116** [comment]
@fieldOfView  I really like that!

**Comment by fvrmr** [comment]
We have a ticket on our backlog for this. Developers see CURA-6722

**Comment by GregValiant** [comment]
@tcm0116 does the FieldOfView "Material Settings" plugin address this request bug?
