### ISSUE TITLE
Z-Seam Alignment 'Random' has bad printing quality

### ISSUE THREAD

**Issue by FPrefect20** [Ultimaker/Cura#18208]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

(any printer)

### Reproduction steps

1. Slicing of multi-corner objects (or cylinder)  with Setting "Z-Seam Alignment" = "random"
2. Use "preview" to check result

### Actual results

Significantly poorer quality compared to previous versions of CURA

### Expected results

"Random" arrangement of the z-seam at the surface 
(see screenshots)

### Add your .zip and screenshots here ⬇️

![cura](https://github.com/Ultimaker/Cura/assets/65475741/bd1a3a64-6310-4e9c-a17a-32e9dc175ea8)

**Comment by Vandresc** [comment]
Hi FPrefect20, thank you for your feedback! We had a look and we currently don't consider this an issue, keep in mind that we changed the way the engine works after 4.13, so the comparison is not very accurate. This, and also the seam being dependent on the shape of the model, which contains some corners, more circular shapes generate a more random seam than compared with models with "corners". 
So for now we will close this ticket but feel free to re-open it with a use case in mind, thank you!
