### ISSUE TITLE
Slicing failed bug

### ISSUE THREAD

**Issue by BackalleySolutions** [Ultimaker/Cura#18204]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender-3 pro

### Name abnormal settings

I don;t have anything I would consider Abnormal, it works on other prints

### Describe model location

if I rotate it on end it will slice, but not how I would like to try and print it to test overhang

### Describe your model

Half circle with wings on it

### Add your .zip here ⬇️

[pic scope mount.zip](https://github.com/Ultimaker/Cura/files/14131391/pic.scope.mount.zip)

**Comment by Vandresc** [comment]
Could you try it again with this build: https://github.com/Ultimaker/Cura/discussions/18080 It doesn't contain a fix, but it has a lot more logging options, which will help us figure out what is going wrong. Thank you!
