### ISSUE TITLE
Overlapping models with "Multiply Selected" option

### ISSUE THREAD

**Issue by zowper** [Ultimaker/Cura#18201]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3

### Reproduction steps

1- Import a model (I used a box that's 10 mm wide, 60 mm long, and 2 mm tall)
2- Right click and select, "Multiply Selected"
3- Change the "Number of Copies" to 40
4- Click "OK"
5- Right click and select, "Multiply Selected"
6- Click "OK" (to make an additional 40 copies)

### Actual results

When you do the first multiply, everything works as expected.  When you do the second multiply, it tries to place the models in the center of the build plate.  This doesn't happen with smaller quantities.  I'm not sure what causes it, but I think it happens when the build plate overflows (instead of placing models off to the side of the build plate like normal).

### Expected results

I would expect new copes to be placed in open space and then to the side of the build plate (rather than overlapping previously created copies).

### Add your .zip and screenshots here ⬇️

First 40 copies:
![First Forty](https://github.com/Ultimaker/Cura/assets/6466307/e9eb3423-8fab-4844-87ea-a69a93b3e95e)

Second 40 copies:
![Second Forty](https://github.com/Ultimaker/Cura/assets/6466307/73d366e7-cc09-45c9-b2a4-4463217d6bf2)

Rectangle STL used (10x60x2 mm)
[Rectangle.stl.zip](https://github.com/Ultimaker/Cura/files/14130431/Rectangle.stl.zip)

**Comment by Vandresc** [comment]
Hi @zowper, thank you for your feedback! Did you try enabling [Keep models apart] from Preference? This will prevent the models from overlapping when multiplying them.
