### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by fmfalcao** [Ultimaker/Cura#18229]
### Cura Version

5.6.0

### Operating System

Win 10 pro

### Printer

Anycubic Kobra 2

### Name abnormal settings

Wont slice

### Describe model location

Center of plate

### Describe your model

Never sliced before.  

### Add your .zip here ⬇️

[A4_Johnny Pole.zip](https://github.com/Ultimaker/Cura/files/14154444/A4_Johnny.Pole.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
