### ISSUE TITLE
Slicing Failed 

### ISSUE THREAD

**Issue by DarkNinja-Lab** [Ultimaker/Cura#18220]
### Cura Version

5.5.0

### Operating System

Windows 11 64 Bit

### Printer

Ender 3

### Describe model location

back of buildplate

### Describe your model

body of ButtonBox

### Add your .zip here ⬇️

[ButtonBox_Main_Body.zip](https://github.com/Ultimaker/Cura/files/14146858/ButtonBox_Main_Body.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
