### ISSUE TITLE
Forcing a wizard with no opt-out is user-UNfriendly

### ISSUE THREAD

**Issue by allanonmage** [Ultimaker/Cura#18237]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

n/a

### Reproduction steps

1. Install Cura
2. Start Cura
3. Rage because you can't load your config file

### Actual results

1. Install Cura
2. Start Cura
3. Rage because you can't load your config file

### Expected results

A button to skip a setup wizard. On a commonly reinstalled software most of your users are not newbies who appreciate a startup wizard, therefore there is no reason to have an unskippable startup wizard.  That's as nonsensical as Firefox having a "what is a browser" training video when it starts.

### Add your .zip and screenshots here ⬇️

n/a

**Comment by nallath** [comment]
Cura isn't firefox. And contrary to firefox, Cura needs some information before it can work. One of those pieces of information is "what printer do you have". Since Cura can't properly function without it, you can't skip that step.
