### ISSUE TITLE
It's not obvious that you can add a non-networked printer, also Cura doesn't import settings

### ISSUE THREAD

**Issue by allanonmage** [Ultimaker/Cura#18239]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

n/a

### Reproduction steps

1. Install Cura
2. Run Cura
3. Rage at startup wizard
4. Close Cura
5. Place config files in appdata
6. Run Cura
7. Rage at startup wizard
8. Find webpage: https://community.ultimaker.com/topic/43527-bypass-cura-531-appimage-setup-for-ultimaker-printers/
9. Scroll down, add random printer
10. SETTINGS NOT LOADED!!!!!!!!!!!!!1111111111111111 /RAGE

### Actual results

1. Install Cura
2. Run Cura
3. Rage at startup wizard
4. Close Cura
5. Place config files in appdata
6. Run Cura
7. Rage at startup wizard
8. Find webpage: https://community.ultimaker.com/topic/43527-bypass-cura-531-appimage-setup-for-ultimaker-printers/
9. Scroll down, add random printer
10. SETTINGS NOT LOADED!!!!!!!!!!!!!1111111111111111 /RAGE

### Expected results

I expected Cura to pick up the settings I carefully backed up and put in the folder (3.6, 4.9, 4.11 folders), since there is no way to import them during the startup wizard.

### Add your .zip and screenshots here ⬇️

n/a

**Comment by nallath** [comment]
Without logs or your config folders, I can't help you. Can you please provide them?
