### ISSUE TITLE
"I am a returning user" button when starting for the "first" time

### ISSUE THREAD

**Issue by allanonmage** [Ultimaker/Cura#18238]
### Is your feature request related to a problem?

The first-run startup wizard is very annoying, and I made a bug report for that.  Since you probably won't understand that (idk why, but you internet-people never understand what bugs are), this is how you solve that problem:

Add a button "I'm a returning user" or "I'm an experienced user" or "Load a previous configuration", or somethign to that effect.

### Describe the solution you'd like

The first-run startup wizard is very annoying, and I made a bug report for that.  Since you probably won't understand that (idk why, but you internet-people never understand what bugs are), this is how you solve that problem:

Add a button "I'm a returning user" or "I'm an experienced user" or "Load a previous configuration", or somethign to that effect.

### Describe alternatives you've considered

n/a

### Affected users and/or printers

n/a

**Comment by nallath** [comment]
If we don't understand things, why even bother to write a report? 

As i explained in the other ticket, there is a good reason why there is a forced screen. It also only shows that if cura was unable to detect a previous installation.
