### ISSUE TITLE
Slicing error when selecting Tree Support

### ISSUE THREAD

**Issue by sscro** [Ultimaker/Cura#18231]
### Cura Version

5.6.0

### Operating System

Windows 10 Pro

### Printer

ELEGOO Neptune 4 PRO

### Name abnormal settings

standard draft profile - only selected Tree support

### Describe model location

any place 

### Describe your model

shared model from PRINTABLE. Sliced as it is

### Add your .zip here ⬇️

[CFFFP_karpa.zip](https://github.com/Ultimaker/Cura/files/14156184/CFFFP_karpa.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
