### ISSUE TITLE
support

### ISSUE THREAD

**Issue by schlichtmaierdima** [Ultimaker/Cura#18233]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Longer LK5 Pro

### Name abnormal settings

Stützstruktur, Tree

### Describe model location

60 Grad

### Describe your model

ein mal wird es geschnitten aber zweites mal nicht 

### Add your .zip here ⬇️

[Shelly_RGBW2_Rail.zip](https://github.com/Ultimaker/Cura/files/14156430/Shelly_RGBW2_Rail.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
