### ISSUE TITLE
Trying to slice a flex turtle for Ender 3 Prod

### ISSUE THREAD

**Issue by gkdante** [Ultimaker/Cura#18242]
### Cura Version

5.6.0

### Operating System

macos sonoma 14.2.1

### Printer

Ender 3 pro

### Name abnormal settings

I tried to use the tree support which I don't use often

### Describe your model

it is a turtle with some articulations

### Add your .zip here ⬇️

[flexi_turtle.3mf.zip](https://github.com/Ultimaker/Cura/files/14158922/flexi_turtle.3mf.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
