### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by emixalot** [Ultimaker/Cura#18243]
### Cura Version

5.6.0

### Operating System

macOS Catalina

### Printer

Anycubic Viper

### Describe model location

I have moved it around on the plate and no luck

### Describe your model

It's part of a helmet. I have merged parts of the helmet. They all print online, but I need them to print merged

### Add your .zip here ⬇️

File won't attach

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
