### ISSUE TITLE
The material diameter isn't updated when changing materials

### ISSUE THREAD

**Issue by Seeyainthex** [Ultimaker/Cura#1825]
I set up two different materials with different temps & diameters.  Only the temps are updated.

**Comment by fieldOfView** [comment]
@Seeyainthex what version of Cura are you using?
Duplicate of https://github.com/Ultimaker/Cura/issues/1687

**Comment by Seeyainthex** [comment]
Just installed 2.5. Problem still there.  Also used 2.3.  on Windows.

**Comment by Seeyainthex** [comment]
OK I'll wait for 2.6.

**Comment by Seeyainthex** [comment]
Fixed in upcoming rlse
