### ISSUE TITLE
Unable to open any 3MF projects

### ISSUE THREAD

**Issue by jzmatrix** [Ultimaker/Cura#18259]
### Cura Version

1.7.2

### Operating System

Windows 11

### Printer

SV-04

### Reproduction steps

- Create a new project
- Import an object to slice (doesn't matter if you perform a slice or not)
- Save the project to a 3MF file
- Close, and reopen Sovol3D Slicer
- Attempt to open previously saved project
- Fail

### Actual results

Receive error of 'Unable to Open File', stating the file could be corrupt. inaccessible or does not contain any models.

### Expected results

The project that was just saved should be opened, restoring the workbench and settings to those reflected when the project was saved.

### Add your .zip and screenshots here ⬇️

[SSSM01_Holder - 1.zip](https://github.com/Ultimaker/Cura/files/14187354/SSSM01_Holder.-.1.zip)

**Comment by Asterchades** [comment]
There isn't a Cura 1.7.2. As such I can only assume you're using the Sovol3D Cura 1.7.2, which is a branch of the main Cura project maintained by Sovol3D.

The main Cura team only maintains the primary branch. Any customisations that others have done on top of that - including those that create faults with importing or exporting files - will need to be dealt with by their respective maintainers. In this case you will need to contact Sovol3D directly as they don't appear to have any kind of repository for their customised Cura version (which may even be in violation of the LGPL-3.0 license).
