### ISSUE TITLE
Can't slice

### ISSUE THREAD

**Issue by HineStar** [Ultimaker/Cura#18252]
### Cura Version

5.7.0-alpha.0

### Operating System

Windows 11

### Printer

Ultimaker S5

### Name abnormal settings

Brim and support is added.

### Describe model location

It worked to move it away from center, thank you!

### Describe your model

It has sliced succesfully before. I Moved it away from center and rotated and now it can slice. When I move back to center it is slicing forever.

**Comment by HellAholic** [comment]
Hey @HineStar,
could you please also share your project file for this crash? That would help greatly to verify the potential issue and possible fixes.
