### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by reboot689** [Ultimaker/Cura#18265]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3 V3 SE

### Name abnormal settings

not sure? it prints anything else just fine. You don't yet have "Default" profiles for the E3V3SE yet

### Describe model location

Centered, rotated 45 degrees to fit

### Describe your model

I have not. it IS but it's a skeleton. not exactly hole free? Mesh tools crashed the Program

### Add your .zip here ⬇️

https://we.tl/t-YAIHuk1Mg1

**Comment by HellAholic** [comment]
Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
