### ISSUE TITLE
cura 2.5.0 insert disk error

### ISSUE THREAD

**Issue by eric231** [Ultimaker/Cura#1826]
I've downloaded cura version 2.5.0 and it ran once and that was when I installed it, but know when I open it I get an error saying for me to insert disk and cura just crashes 
I tried restarting my computer but the error still comes up anyone know what I can do?

**Comment by fieldOfView** [comment]
What drive letter is it complaining about?

(duplicate of https://github.com/Ultimaker/Cura/issues/1602, but that one is not resolved yet either)
