### ISSUE TITLE
Нарезка на слои не выполнена из-за непредвиденной ошибки.

### ISSUE THREAD

**Issue by 7ARTA7** [Ultimaker/Cura#18267]
### Cura Version

5.5.0

### Operating System

Windows 10 PRO

### Printer

Anycubic Vyper

### Describe your model

Moon

### Add your .zip here ⬇️

[Uploading AV_moon.zip…]()
Moon

**Comment by HellAholic** [comment]
Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
