### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by satguy74** [Ultimaker/Cura#18261]
### Cura Version

5.7

### Operating System

windows 11

### Printer

ender-3 s1 pro

### Name abnormal settings

no

### Describe model location

i have moved it around

### Describe your model

have not been able to slice

### Add your .zip here ⬇️

[failedslice.zip](https://github.com/Ultimaker/Cura/files/14188081/failedslice.zip)

**Comment by atamico** [comment]
No error images were shown, ZIP file is empty. There are no details about the error.
