### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by thecurator09** [Ultimaker/Cura#18273]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Longer LK5 Pro

### Name abnormal settings

no abnormal settings. 

### Describe model location

It slices if I rotate it.

### Describe your model

I have not sliced it before.

### Add your .zip here ⬇️

[LLK5PRO_CR90_chess_piece.zip](https://github.com/Ultimaker/Cura/files/14216820/LLK5PRO_CR90_chess_piece.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
