### ISSUE TITLE
cant get any supports to show up

### ISSUE THREAD

**Issue by soundtechscott** [Ultimaker/Cura#18274]
### Cura Version

5.6

### Operating System

win 10

### Printer

neptune 4  max - custom upgrades - klipper with octopus pro

### Reproduction steps

hover a print above build plate, 5mm, 50,, 500mm... doesnt mater.. just make it not touch teh build playe by some amount
select to add supports...
cant get any supports to generate

### Actual results

no supprts generated..

### Expected results

this should at least generate something....

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/51548286/4d8468cb-cd1e-4be9-a099-2c7c08adffe3)
[CutHorn v6.zip](https://github.com/Ultimaker/Cura/files/14217045/CutHorn.v6.zip)

**Comment by Asterchades** [comment]
Double check that they're even set to be visible in the preview. Use the `Color Scheme` dropdown in the centre top to bring up the legend and ensure `Helpers` is checked - this will toggle the visibility of both Supports _and_ and Bed Adhesion in use (Skirt, Brim, Raft).

Being that you're using regular-style supports on what is a fairly basic geometric surface, Supports are almost certainly being generated.
