### ISSUE TITLE
slicing not possible

### ISSUE THREAD

**Issue by Desperado8701** [Ultimaker/Cura#18286]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ultimaker S5

### Describe model location

No 

### Describe your model

No chance 

### Add your .zip here ⬇️

[UMS5_suspended-millenium-falcon.stl.zip](https://github.com/Ultimaker/Cura/files/14228390/UMS5_suspended-millenium-falcon.stl.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
