### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by brookscarr** [Ultimaker/Cura#18281]
### Cura Version

5.6.0

### Operating System

Linux 5.15

### Printer

Elegoo Neptune 4 Pro

### Describe your model

Banana for scale

### Add your .zip here ⬇️

[CFFFP_Banana v 1.1.zip](https://github.com/Ultimaker/Cura/files/14225501/CFFFP_Banana.v.1.1.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
