### ISSUE TITLE
Tree supports not working

### ISSUE THREAD

**Issue by Doinikdrnz** [Ultimaker/Cura#18282]
### Cura Version

elegoo cura 5.6.0

### Operating System

Windows 11

### Printer

elegoo neptune 4 pro

### Name abnormal settings

chanched from normal supports to tree supports

### Describe model location

center

### Describe your model

yes i have it stopped working as i turned on tree supports

### Add your .zip here ⬇️

[EN4PRO_safe_handle.zip](https://github.com/Ultimaker/Cura/files/14225656/EN4PRO_safe_handle.zip)

**Comment by WhatNot911** [comment]
Same issue as mine
[#17916](https://github.com/Ultimaker/Cura/issues/17916)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
