### ISSUE TITLE
Darth Maul Face slice fail

### ISSUE THREAD

**Issue by rbenites** [Ultimaker/Cura#18283]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Creality End3 S1 Pro

### Describe model location

Center of build plate. I tried to move it around and try the slice again but it consistently fails at about 25%

### Describe your model
I have not sliced this before. Cura says it might not be water tight but the error is not calling that out. I have tried the Mesh tools to fix the simple issues

### Add your .zip here ⬇️

[Uploading CFFFP_meda_V4_cura.zip…]()

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
