### ISSUE TITLE
Error de corte

### ISSUE THREAD

**Issue by XxbazingaxX** [Ultimaker/Cura#18287]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anet A8

### Describe your model

es una tapa

### Add your .zip here ⬇️

Se ha producido un error inesperado al realizar el corte o slicing. Le rogamos que informe sobre este error en nuestro rastreador de problemas.
[Magazine_BaseV2.zip](https://github.com/Ultimaker/Cura/files/14229260/Magazine_BaseV2.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
