### ISSUE TITLE
????

### ISSUE THREAD

**Issue by ECoSEDE** [Ultimaker/Cura#18295]
### Cura Version

5.6.0

### Operating System

Windows 10 Pro

### Printer

Anycubic i3 Mega X

### Name abnormal settings

??

### Describe model location

nein

### Describe your model

nein

### Add your .zip here ⬇️

[minion alles.zip](https://github.com/Ultimaker/Cura/files/14232470/minion.alles.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
