### ISSUE TITLE
Tree Supports Causing Problems

### ISSUE THREAD

**Issue by njsokalski** [Ultimaker/Cura#18290]
### Cura Version

5.7.0-Alpha.0

### Operating System

Windows 10

### Printer

Creality Ender 3 S1 Plus

### Name abnormal settings

Support Structure

### Describe model location

No

### Describe your model

Yes

### Add your .zip here ⬇️

[CE3S1P_InsulinDispenser.zip](https://github.com/Ultimaker/Cura/files/14230664/CE3S1P_InsulinDispenser.zip)
I successfully sliced this model using Cura 5.5, but then (after adjusting several standard settings) tried to sliced it again, and received either unsuccessful slicing messages or it would (after a significant amount of time slicing) display only the Slice button (not the save to removable store or print via USB options) as if it was never sliced. So I installed the 5.6.0, that did not help. The 5.7.0-alpha.0 also did not help. If I change the Support Structure setting to Normal (instead of Tree), it slices successfully (although the result would be worthless for my model). But the Tree structure was working the first time, so I think it is some kind of unique combination of settings with these settings & my model. I have tried using the same profile with other models, and this model with other profiles, and those both worked.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
