### ISSUE TITLE
Crash slicing

### ISSUE THREAD

**Issue by rom119** [Ultimaker/Cura#18294]
### Cura Version

5.6.0

### Operating System

Win 11 Pro

### Printer

Anycubic Kobra Go

### Name abnormal settings

Normal PLA

### Describe model location

Center on plate

### Describe your model

YES

### Add your .zip here ⬇️

[Záslepka D8mm.zip](https://github.com/Ultimaker/Cura/files/14232030/Zaslepka.D8mm.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
