### ISSUE TITLE
Echec de la découpe

### ISSUE THREAD

**Issue by sebou8301** [Ultimaker/Cura#18302]
### Cura Version

5.6.0

### Operating System

windows 11 x64 amd ryzen 3900x gpu rx6800xt

### Printer

FLSUN SR

### Name abnormal settings

warping

### Describe model location

Oui selon la position ou les options choisi le modèle est découpé

### Describe your model

Oui déja découpé et non pas de mesh fix

### Add your .zip here ⬇️

[Support cache plaque immat.zip](https://github.com/Ultimaker/Cura/files/14238608/Support.cache.plaque.immat.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
