### ISSUE TITLE
Error slicing with using supports

### ISSUE THREAD

**Issue by npab19** [Ultimaker/Cura#18306]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 5 Plus

### Describe your model

tablet mount

### Add your .zip here ⬇️

[CE5P_TabletMountClip.zip](https://github.com/Ultimaker/Cura/files/14249381/CE5P_TabletMountClip.zip)

**Comment by npab19** [comment]
Doing more testing, it seems like it happens when useing Tree.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
