### ISSUE TITLE
echec de la decoupe

### ISSUE THREAD

**Issue by donow27** [Ultimaker/Cura#18301]
### Cura Version

5.6

### Operating System

windows 10

### Printer

annycubic kobra 2

### Describe model location

centre

### Describe your model

peiti cylindre

### Add your .zip here ⬇️

cura ne veut plus de découpe depuis que j'ai mis un programme et je les enlevé derrière

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
