### ISSUE TITLE
deadpool helmet

### ISSUE THREAD

**Issue by cors92** [Ultimaker/Cura#18300]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

ender 3 v2

### Describe model location

deadpool helmet 

### Describe your model

will slice at 80%

### Add your .zip here ⬇️

https://we.tl/t-1MVokEncLA

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
