### ISSUE TITLE
fails when i add tree support

### ISSUE THREAD

**Issue by lazuskica** [Ultimaker/Cura#18304]
### Cura Version

5.6.0

### Operating System

windows 10, laptop, amd radeon 610m

### Printer

ender 3 v3 se

### Name abnormal settings

tree support

### Describe your model

it slices normally without tree support

### Add your .zip here ⬇️

[CE3V3SE_enkoderskitocak3mm.zip](https://github.com/Ultimaker/Cura/files/14241432/CE3V3SE_enkoderskitocak3mm.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
