### ISSUE TITLE
"per model settings" doesn't have a selection for "retraction"

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1831]
Cura 2.4:
I was planning to do some tests with different retraction settings. In "per model settings" there isn't an option for "retraction" and I think it would be helpful to have that.
thanks!

**Comment by BagelOrb** [comment]
What about the moves between models? Should those have the retraction settings of the model it came from or the model it moves to?

Sadly this is probably not going to be implemented by Ultimaker any time soon...

**Comment by wstoettinger** [comment]
there is a discussion and more detailed explanation here #3193
