### ISSUE TITLE
slicing issue

### ISSUE THREAD

**Issue by SinclairWhitewolf** [Ultimaker/Cura#18326]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

anycubic Kordoba max

### Reproduction steps

opened file and attempted to slice it

### Actual results

slicing failed message

### Expected results

able to slice model for export to print

### Add your .zip and screenshots here ⬇️

unavailble at this time

**Comment by HellAholic** [comment]
Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.
