### ISSUE TITLE
Will not slice

### ISSUE THREAD

**Issue by FlashMoonUK** [Ultimaker/Cura#18327]
### Cura Version

5.5.0

### Operating System

MacOS 14.3.1

### Printer

Dremel 3D45

### Name abnormal settings

none

### Describe model location

In center of plate

### Describe your model

lid with hinge

### Add your .zip here ⬇️

[D_Split charger over ride button x2 ASA V2 Lid.3mf.zip](https://github.com/Ultimaker/Cura/files/14283516/D_Split.charger.over.ride.button.x2.ASA.V2.Lid.3mf.zip)

**Comment by HellAholic** [comment]
Hey @FlashMoonUK ,
The project slices on the latest alpha build but your printer definition/settings is not part of the Cura, so we cannot try that.
Keep an eye out for the next release and try it there.
