### ISSUE TITLE
Angle of Slope Slice

### ISSUE THREAD

**Issue by Y13Lab** [Ultimaker/Cura#18333]
### Is your feature request related to a problem?

I can't find a slicer with an angled cut feature.
More precisely, this function should work well.

### Describe the solution you'd like

In the slicer CrealityPrint, in the experimental section
there is a setting Angle of Slope Slice.
When this setting is enabled, the slicer prints at the selected angle.
In this mode, movement occurs in three coordinates x,y,z.
![изображение_2024-02-15_142822896](https://github.com/Ultimaker/Cura/assets/125975032/bbd1cdff-9640-4897-aa4b-f6a3854c52e3)
But there are some flaws in it that prevent it from being used.

I would like to have this functionality
in my favorite slicer Cura.
Please add this functionality to cura slicer.

### Describe alternatives you've considered

Until recently, I thought that there were no alternatives.
But I came across a slicer Crealityprint in which the angled cutting mode is implemented.
I was very happy, but after a lot of trying I realized
that it is poorly implemented and not suitable for full use.

### Affected users and/or printers

This is a feature needed by 3D printing enthusiasts and innovators.

**Comment by HellAholic** [comment]
Hey @Y13Lab ,
We had a discussion about this feature a while back. See https://community.ultimaker.com/topic/35805-slice-at-an-angle/
I'll bring it up with the team to see if it's something we can pick up.

**Comment by HellAholic** [comment]
Given the complications around this feature, we believe we will not work on this anytime soon and will therefore close this issue. If there are any updates regarding similar functionalities or features from the community developers we will included it in the future.

Cheers!
