### ISSUE TITLE
Print error

### ISSUE THREAD

**Issue by tatkamedved007** [Ultimaker/Cura#18336]
### Cura Version

5.6.0

### Operating System

Windows 10 Pro

### Printer

Anet ET4 PRO V1.0.2

### Reproduction steps

Turn on the printer.
Run Cura 5.6.0.
Open the STL file.
Set the temperature to 220 degrees.
Start printing.
After a few layers, the X-axis motor will growl and the print will shift in the X-axis (see attachment).
Windows has all the updates.
An error will always occur with this procedure.
The problem persists in at least all versions of Cura 5.
The error can be circumvented by the following procedure: after starting printing, turn off the printer with the power switch and immediately turn it on again.
Printing will then start again from the beginning and proceed normally.

### Actual results

See description above.

### Expected results

See description above.

### Add your .zip and screenshots here ⬇️

[AET4PRO_Ortur cudlik1.zip](https://github.com/Ultimaker/Cura/files/14300977/AET4PRO_Ortur.cudlik1.zip)
![20240215_191817](https://github.com/Ultimaker/Cura/assets/111526433/d2082109-be5d-48be-8ef8-bfb4e439a746)

**Comment by HellAholic** [comment]
Hey @tatkamedved007 , 
This might be a potential hardware issue you're experience judging from the issue description you provided. It's also good to perform some hardware maintenance on the printer to see if that resolves the issue.
I cannot see any action that we could take to help you with the current issue you're describing but if you find additional information feel free to re-open this issue.
