### ISSUE TITLE
Estou com problema de fatiamento em algumas peças

### ISSUE THREAD

**Issue by connectlab3d** [Ultimaker/Cura#18341]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

ender 3 v2

### Name abnormal settings

não

### Describe model location

não

### Describe your model

os modelos sempre fatiaram normais, agora estão demorando mais de 25 minutos para fatiar e alguns não fatiam 

### Add your .zip here ⬇️

Por gentileza verificar o problemas apresentado, aguardo um parecer técnico.

Desde já agradeço!

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
