### ISSUE TITLE
ironman helmet slicing failed

### ISSUE THREAD

**Issue by brelyt300** [Ultimaker/Cura#18348]
### Cura Version

5.6.0

### Operating System

windows 10 

### Printer

QIDI x plus 

### Name abnormal settings

default 

### Describe model location

centered on build plate 

### Describe your model

stl pre split helmet

### Add your .zip here ⬇️

[Mk 2 Helmet Base.zip](https://github.com/Ultimaker/Cura/files/14317045/Mk.2.Helmet.Base.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing the model so I am unable to duplicate the problem.  The model isn't watertight though and might not print correctly.
--> 6 Non-manifold edges
--> 10 Inverted faces
This is with the model repaired in MS 3D Builder.  It looks the same as the un-repaired model.
(0.2 layer height and 0.4 line width.)
![image](https://github.com/Ultimaker/Cura/assets/64202104/24b4158c-2f85-443c-8ba6-233b0893a850)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
