### ISSUE TITLE
Slicing under 0,3mm

### ISSUE THREAD

**Issue by eredchon** [Ultimaker/Cura#18347]
### Cura Version

5.6.0

### Operating System

Window1 11

### Printer

Elegoo Neptune 3 Pro

### Name abnormal settings

Resolution under 0,3mm, using standard profiles Extra Fast works, Fast doesnt 

### Describe model location

Center

### Describe your model

25 cm figure, slices with 0,3 extra Fast profile setting, if i pick Fast or change 0,3 to 0,2 it fails

### Add your .zip here ⬇️

When slicing the figure under 0,3mm is fails to slice if i slice with the standard extra fast(0,3mm) is slices.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
