### ISSUE TITLE
Cannot slice file

### ISSUE THREAD

**Issue by iu2frl** [Ultimaker/Cura#18345]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Neptune 4 Pro

### Name abnormal settings

None

### Describe model location

Either single piece or multiple instances, same issue

### Describe your model

Single slicing works

### Add your .zip here ⬇️

[Clip_and_Chain_for_Elegoo_Neptune_4_series.zip](https://github.com/Ultimaker/Cura/files/14315065/Clip_and_Chain_for_Elegoo_Neptune_4_series.zip)
![Immagine 2024-02-16 201339](https://github.com/Ultimaker/Cura/assets/61653175/9afdce7e-1d5b-4c9a-bfa5-93821ddee11d)

**Comment by iu2frl** [comment]
Issue seems to be related with the tree setting in supports, disabling them solves the issue
![Immagine 2024-02-16 202156](https://github.com/Ultimaker/Cura/assets/61653175/bdb3c5b7-bea4-4f2b-b099-45ef34a7f0a3)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
