### ISSUE TITLE
Error Slice 

### ISSUE THREAD

**Issue by SaffronFR** [Ultimaker/Cura#18352]
### Cura Version

5.6.0

### Operating System

OS : Windows 10 22H2 GPU : RTX3060TI

### Printer

Flsun Super Racer

### Name abnormal settings

Le paramètre "Scale"

### Describe model location

Fonctionne quand on le déplace, mais pas quand il est au milieu

### Describe your model

La modèle est des toilettes fait sous blender à des fins de test avec ma machine. Je n'ai pas essayé de faire un mesh fix rapide avec le plugin meshtools

### Add your .zip here ⬇️

[FSR_Toilet_Printer-Cube_004.zip](https://github.com/Ultimaker/Cura/files/14319482/FSR_Toilet_Printer-Cube_004.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
