### ISSUE TITLE
Slicing Failed with support and correct without support

### ISSUE THREAD

**Issue by Matlef53** [Ultimaker/Cura#18355]
### Cura Version

5.6

### Operating System

Windows 10

### Printer

Neptune 4 plus (personalized profile)

### Name abnormal settings

Supports

### Describe model location

no

### Describe your model

Yes, without support

### Add your .zip here ⬇️

[CFFFP_bolv1.zip](https://github.com/Ultimaker/Cura/files/14320201/CFFFP_bolv1.zip)

When I try to slice the model with support, it gives an error whereas if I use another printing profile everything goes well.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
