### ISSUE TITLE
5.7.0 a slicing unexpected error

### ISSUE THREAD

**Issue by Skipper488** [Ultimaker/Cura#18350]
### Cura Version

5.7.0-alpha.0

### Operating System

Windows 10

### Printer

Creality Ender-3 / Ender-3 v2

### Name abnormal settings

none

### Describe model location

It did slice after moving away from the center of the buildplate.

### Describe your model

It sliced correctly in other slicers

### Add your .zip here ⬇️

[CE3E3V2_Screw_Driver_Holder.zip](https://github.com/Ultimaker/Cura/files/14317886/CE3E3V2_Screw_Driver_Holder.zip)

I really wish somewhere had mentioned moving the model away from the center of the buildplate before I went through loading 5.7.0 alpha as well as trying this in several other slicers. I use Cura 99+% of the time so I really don't know the other slicers as well nor do I have all of my filaments loaded. It did slice in Orca, Bambu and Creality slicers. I really don't understand how Creality sliced it as it's based on Cura.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
