### ISSUE TITLE
Slice crash on a fairly simple, small model

### ISSUE THREAD

**Issue by VeloSteve** [Ultimaker/Cura#18358]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Elegoo Neptune 3 Pro

### Name abnormal settings

Selecting Normal with defaults, it slices okay.  Turning on tree support made it crash again.

### Describe model location

No change when rotating and moving.

### Describe your model

Mesh tools says it is watertight.  Fix simple holes and randomize location do not help.

### Add your .zip here ⬇️

I was not able to save the project file!  The error box says `'time'`.
I will attach the *.stl file instead.  You may consider it public domain.
[LidFor50x65plastic_8mmH.zip](https://github.com/Ultimaker/Cura/files/14320015/LidFor50x65plastic_8mmH.zip)

This model works fine in 5.7 alpha and with support turned off in 5.6.
I have sliced many other files without trouble.

Saving the project file works with a different model.

Here is the log file:
[cura.zip](https://github.com/Ultimaker/Cura/files/14320024/cura.zip)

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
