### ISSUE TITLE
Cura cannot laminate file

### ISSUE THREAD

**Issue by MarcoZambrana94** [Ultimaker/Cura#18362]
### Cura Version

5.6.0

### Operating System

Windows 10 pro

### Printer

Creality Ender 3 pro

### Reproduction steps

Open the Stl file, from Cura.
File preparation is complete.
The file preview does not complete, and the slicer bar does not complete

### Actual results

None

### Expected results

None

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/102870437/626e686f-fccc-479b-b5f9-ae7c1544cbca)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and a log file there can be no investigation.  If you would provide those then we would have something to check on.
