### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by storytellinsteve** [Ultimaker/Cura#18363]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Max

### Name abnormal settings

No

### Describe model location

No

### Describe your model

No. Yes. Yes.

### Add your .zip here ⬇️

[24AECAVE01 - 2x4 Water Corner Chasm 1.zip](https://github.com/Ultimaker/Cura/files/14324271/24AECAVE01.-.2x4.Water.Corner.Chasm.1.zip)

**Comment by HellAholic** [comment]
Hey, we had a few fixes that resolve your issue, they will be included in the next release.
I double checked you project file and it slices with no issues in the latest internal build. (w/o support - normal & tree support)
![image](https://github.com/Ultimaker/Cura/assets/28710690/ea15d686-58c6-4231-833f-c20e4775a85f)

Feel free to reopen if you still experience the issue after the next release.
Thanks for your report.
Cheers!
