### ISSUE TITLE
Erro al cortar cuernos de demonio, no logra cortar

### ISSUE THREAD

**Issue by Oswalgm** [Ultimaker/Cura#18376]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Kingroon KP3S PRO

### Name abnormal settings

No se corta

### Describe model location

no hace nada

### Describe your model

Un vez solamemente lo corto bien

### Add your .zip here ⬇️

[KKPRO_cuernos demon 1 error.zip](https://github.com/Ultimaker/Cura/files/14335060/KKPRO_cuernos.demon.1.error.zip)

**Comment by HellAholic** [comment]
Thanks for the report!
I'm able to reproduce the issue.

**Comment by HellAholic** [comment]
Issue has been resolved. Fix will be included in 5.7 Stable release.
Cheers!
