### ISSUE TITLE
Slicing with tree suport on 0.6mm print

### ISSUE THREAD

**Issue by VictorEscribano** [Ultimaker/Cura#18377]
### Cura Version

5.4.0

### Operating System

Windo1s 11

### Printer

Ender 3 Pro

### Name abnormal settings

Tree support 

### Describe model location

Vertical

### Describe your model

Case for 4wd motor. Sliced siccesfull with 0.8mm and 1mm.

### Add your .zip here ⬇️

https://we.tl/t-3Zg4mNc6UM

**Comment by HellAholic** [comment]
Hey, we had a few fixes regarding the tree supports in PRs by ThomasRahm (https://github.com/Ultimaker/CuraEngine/pull/2028)
They will be included in the next release.

Feel free to reopen if you still experience the issue after the next release.
Thanks for you report.
Cheers!
