### ISSUE TITLE
ver 5.6 on Chiron prints 1st layer w/ large gaps

### ISSUE THREAD

**Issue by jbastan** [Ultimaker/Cura#18370]
### Cura Version

5.6

### Operating System

windows 11

### Printer

anycubic Chiron

### Reproduction steps

Printing PLA with nozzle 0.6 (verified extruder is also set to 0.6 in print settings), I've tried various layer heights from 0.3 to 0.48 and layer widths from 0.5 to 0.56 and always gets the same gaps In the skin. I've also increased initial layer feed rate to 150% (seems way too high) and it helps very little. I've confirmed the skin overlap is reasonably the same as my existing profiles if not more 15-20%
Using Line pattern, haven't tried other patters yet.

Using same profile on cure 5.2.2 things work fine.

### Actual results

First layer prints always have wide gaps. Seems it's more pronounced towards the ends of the skin run at every other line. Walls print properly regardless of qty. All subsequent layers including bottoms and tops print as expected (no gaps).

### Expected results

Expecting no gaps. Especially going up to 150% feed rate or higher overlap percentage.

### Add your .zip and screenshots here ⬇️

I no longer have the log files since I'm using 5.2.2 now.
I've started to use IdeaMaker too, it was printing fine with that, even before I rolled back to your 5.2.2

**Comment by GregValiant** [comment]
Thanks for the report.
We really need a project file to investigate this.  Use the "File / Save Project" command and then zip the 3mf file and post the zip folder here.  Some images of what you see as the problem would be helpful as well.
