### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by JALinker** [Ultimaker/Cura#18378]
### Cura Version

5.6.0

### Operating System

WIN 11 23H2 22631.3155

### Printer

Ender-3 V3 SE

### Describe model location

middle various rotations

### Describe your model

first time for this model

### Add your .zip here ⬇️

[CE3V3SE_pantherme.zip](https://github.com/Ultimaker/Cura/files/14337514/CE3V3SE_pantherme.zip)

**Comment by HellAholic** [comment]
Thanks for the report!
I checked the model in the latest internal build and it sliced successfully.
![image](https://github.com/Ultimaker/Cura/assets/28710690/38b4c725-64b4-42b9-8888-b50a5061273c)

Issue should be resolved in the next Cura release. If you still experience the issue, please feel free to re-open.
Cheers!

**Comment by JALinker** [comment]
Any way to sign up to be a beta tester?
