### ISSUE TITLE
Wrong Ender 3 V3 SE Start G-code (First layer temperature code)

### ISSUE THREAD

**Issue by cymise** [Ultimaker/Cura#18383]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender 3 V3 SE

### Reproduction steps

The start G-code from default profile of Ender 3 V3 SE is wrong.
The wrong line is M109 S[material_print_temperature_layer_0].
It shall be M109 S{material_print_temperature_layer_0}.

The square brackets[] are inappropriate. It should be replaced with brace {}.

Therefore, resources/definitions/creality_ender3v3se.def.json
should be fixed.

Because I don't know about how to edit the profile directly, I'm submitting the issue. Thank you.

### Actual results

Default Start G-code: 
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position
M109 S[material_print_temperature_layer_0] ;**!!!WRONG DEFAULT GCODE!!!**
G1 X10.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X10.4 Y145.0 Z0.28 F5000.0 ;Move to side a little
G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0  ;Reset Extruder
G1 E-1.0000 F1800 ;Retract a bit
G1 Z2.0 F3000 ;Move Z Axis up
G1 E0.0000 F1800

Sliced G-code **(Default):**
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position
M109 S[material_print_temperature_layer_0] ;**!!!IT'S NOT REPLACED!!!**
G1 X10.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X10.4 Y145.0 Z0.28 F5000.0 ;Move to side a little
G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0  ;Reset Extruder
G1 E-1.0000 F1800 ;Retract a bit
G1 Z2.0 F3000 ;Move Z Axis up
G1 E0.0000 F1800 

Sliced G-code **(Fixed):**
G92 E0 ;Reset Extruder
G1 Z2.0 F3000 ;Move Z Axis up
G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position
M109 S200; **It's now replaced!**
G1 X10.1 Y145.0 Z0.28 F1500.0 E15 ;Draw the first line
G1 X10.4 Y145.0 Z0.28 F5000.0 ;Move to side a little
G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line
G92 E0  ;Reset Extruder
G1 E-1.0000 F1800 ;Retract a bit
G1 Z2.0 F3000 ;Move Z Axis up
G1 E0.0000 F1800 

### Expected results

Because of the wrong M109 Gcode, the error happens.

### Add your .zip and screenshots here ⬇️

Sliced G-code with default ender 3 v3 se profile
![image](https://github.com/Ultimaker/Cura/assets/83527948/100869c9-1eaf-4ccb-85ff-9d120f3973cd)

Sliced G-code with fixed ender 3 v3 se profile

![image](https://github.com/Ultimaker/Cura/assets/83527948/01ebdeaa-74d8-4690-a22f-b54ab1a18ec8)

**Comment by Asterchades** [comment]
A PR already exists to correct this - #17781. Note that at the very least this will not be implemented until 5.7 goes live (not the alpha) as there's no way currently to provide separate definition downloads (I've asked and it's just not feasible at present with the distribution methods available).
