### ISSUE TITLE
can not remove printers

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1838]
I can not seem to remove printers (activated or not).
It does show me the "are you sure message"

**Comment by nallath** [comment]
I fixed an issue regarding this yesterday.

**Comment by Ghostkeeper** [comment]
The interface freezes for like 5 seconds, but eventually it does remove the printer for me.

**Comment by maukcc** [comment]
That is how it used to work for me too. And during the 5 sec. wait it was not possible to do something else.
Now I can wait forever(if I want), and I can close the pop-up. So that lets me know he has finished the removing process, but nothing got removed.
tested on 2 different ubuntu 16.04 machines

**Comment by maukcc** [comment]
I just did a 2nd update today and it is fixed now. this can be closed
