### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by rahulgkhs** [Ultimaker/Cura#18389]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality CR-6 SE

### Name abnormal settings

Tree Support

### Describe model location

No it doesn't

### Describe your model

Yes, with normal support structure.

### Add your .zip here ⬇️

[CCR6SE_Aquarium ATO (Auto Top Off)(soda bottle) V2.zip](https://github.com/Ultimaker/Cura/files/14360071/CCR6SE_Aquarium.ATO.Auto.Top.Off.soda.bottle.V2.zip)

**Comment by HellAholic** [comment]
Hey @rahulgkhs , we had a few fixes regarding the tree supports in PRs by ThomasRahm (https://github.com/Ultimaker/CuraEngine/pull/2028)
They will be included in the next release.
I also double checked you issue and it seems to be resolved in the latest internal build.
![image](https://github.com/Ultimaker/Cura/assets/28710690/0d422ea8-0248-4b76-b2ef-9015330df770)

Feel free to reopen if you still experience the issue after the next release.
Thanks for you report.
Cheers!
