### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by MBry123** [Ultimaker/Cura#18388]
### Cura Version

5.6.0

### Operating System

Windows 10, CPU i3-6300, GPU GT 730, SSD

### Printer

German RepRap X350 Pro

### Describe model location

Almost central, slices if moved along X away from home

### Describe your model

No, new model, but moving it seems to help.

### Add your .zip here ⬇️

[Front Case Slicing Error.zip](https://github.com/Ultimaker/Cura/files/14357866/Front.Case.Slicing.Error.zip)

**Comment by HellAholic** [comment]
Hey, the issue has been resolved in the latest internal build. 
The fixes will be included in the next release.
![image](https://github.com/Ultimaker/Cura/assets/28710690/c165963a-17e2-42bd-8f9f-ba75f117d597)


Feel free to reopen if you still experience the issue after the next release.
Thanks for you report.
Cheers!
