### ISSUE TITLE
Slicing failed. Standard settings.

### ISSUE THREAD

**Issue by Grandsolution** [Ultimaker/Cura#18384]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Chiron

### Name abnormal settings

Normal settings

### Describe model location

90 degrees

### Describe your model

Very simple model

### Add your .zip here ⬇️

[Connection test.zip](https://github.com/Ultimaker/Cura/files/14344792/Connection.test.zip)

**Comment by whitnejo** [comment]
I also have the same slicing error while slicing a model turned 90 degrees for my Chiron using Cora 5.6.0 but MacOS 14.2.1. Same model slices fine for my Ender3 using the same OS and Cura versions.

**Comment by HellAholic** [comment]
Hey, I checked your model with the latest internal build and it sliced without issues.
![image](https://github.com/Ultimaker/Cura/assets/28710690/250bdb43-aeb6-4846-9695-5da860d7e5fa)
The fixes will be included in the next release.

Feel free to reopen if you still experience the issue after the next release.
Thanks for you report.
Cheers!
