### ISSUE TITLE
Slicing Failed in Cura 5.6 but not in 5.5

### ISSUE THREAD

**Issue by WILFR38** [Ultimaker/Cura#18382]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

CR10  SMART PRO + CREALITY SONIC PAD

### Describe model location

Yes rotate model 90 degrees, model slice but not the best to print.

### Describe your model

I can slice it in the Cura 5.5

### Add your .zip here ⬇️

[SPACER 297.zip](https://github.com/Ultimaker/Cura/files/14341425/SPACER.297.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing this "as received" in 5.6.0.

The Cura team will take a look.

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
