### ISSUE TITLE
Cannot save project on disk, only on digital library

### ISSUE THREAD

**Issue by LasseBLC** [Ultimaker/Cura#18399]
### Cura Version

1.7.2

### Operating System

windows 10

### Printer

sovol sv06

### Reproduction steps

when i save my projects om the disk, i get an error when i open the project

### Actual results

i get an error when i try to open project

![image](https://github.com/Ultimaker/Cura/assets/160837647/26963169-6d77-41f8-bead-2791cdd0b982)

### Expected results

being able to open project

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/160837647/70cd0c07-2df6-4674-a9da-d44ab98f2631)

**Comment by Vandresc** [comment]
Hi @LasseBLC , the Cura version you are using is not a part of Ultimaker Cura, probably a fork based on the Cura engine, so unfortunately we cannot help you as we cannot reproduce the issue. Please report on their repository, thank you!
