### ISSUE TITLE
Slicing Failed a no reason given

### ISSUE THREAD

**Issue by 1MariaSN** [Ultimaker/Cura#18391]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Wasp 2040

### Name abnormal settings

None

### Describe your model

Tolerance Test File

### Add your .zip here ⬇️

I've attached the file I'm having issues with. It works in Prusa Slicer.
[Tollerance Test v2.zip](https://github.com/Ultimaker/Cura/files/14362345/Tollerance.Test.v2.zip)

**Comment by Vandresc** [comment]
Hi @1MariaSN , it slices for us in our internal build. The fix will be in the next release, but again I didn't have access to your printer. so I used one of our printers (Um S5) for testing.

**Comment by 1MariaSN** [comment]
Thanks!
Would you happen to know when it would be released next?

Many thanks,

Maria

**Comment by Vandresc** [comment]
We try to release every 3 months.
And a little birdy told me that a release is coming up, so you hopefully don't have to wait that long.
Thanks again for reporting! Together we can make Cura better.

**Comment by 1MariaSN** [comment]
Thanks!
