### ISSUE TITLE
Printing order of models in mode "One at a time"

### ISSUE THREAD

**Issue by SamAntUA** [Ultimaker/Cura#18393]
### Is your feature request related to a problem?

I believe this question arised a lot of times because it is very wanted and, I believe, very simple to implement.
I'm always frustrated with printing order of models in "One at a time" mode! With the fact that I cannot define it. And that its automatic setting is chaotic, instead of following some logic. What I mean: when I placed let say 5 copies of tall objects (taller then gantry height), logically that they must be printed the way when already printed details move farther from a gantry to avoid collision with it.
And adjacent thing to "One at a time" mode: context menu item "Arrange all models in a grid" locates objects too close to each other (doesn't consider print head dimensions). And (again) this order is chaotic, random instead of following some logic (e.g. zig-zag).

### Describe the solution you'd like

Just let to drag and drop models in a list (at the bottom left) and let Cura to slice models according to this list.
And implement described logics of printing order and collision avoiding techniques.

### Describe alternatives you've considered

It is manually moving objects, checking what order Cura gave to you.

### Affected users and/or printers

Everytime

**Comment by Vandresc** [comment]
Hi @SamAntUA , we are actually working on this, received a PR (https://github.com/Ultimaker/Cura/pull/17893) from one of our community members. For our internal reference Cura-11617.
