### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Heatley2001** [Ultimaker/Cura#18396]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3 Max Neo

### Name abnormal settings

Wont slice with default

### Describe model location

Wont slice straight ahead or rotated to the left.

### Describe your model

Has never sliced. Fails each time.

### Add your .zip here ⬇️

https://we.tl/t-q6j8e5CDU7     file download link from WeTransfer

**Comment by Vandresc** [comment]
Hi @Heatley2001 , thank you for your report, I could slice the model in our internal build, so the fix will be present in the next release.
