### ISSUE TITLE
Cura 5.7.0 Local deployment of source code

### ISSUE THREAD

**Issue by yan990703** [Ultimaker/Cura#18394]
### Cura Version

5.7.0

### Operating System

Windows11

### Printer

None

### Reproduction steps

Follow the steps in the wiki to implement deployment

### Actual results

[17/190] Building CXX object CMakeFiles\_CuraEngine.dir\src\LayerPlan.cpp.obj
FAILED: CMakeFiles/_CuraEngine.dir/src/LayerPlan.cpp.obj
C:\PROGRA~1\MICROS~3\2022\PROFES~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\cl.exe  /nologo /TP -DAGRPC_BOOST_ASIO -DARCUS -DBUILD_TESTS -DCARES_STATICLIB -DCURA
_ENGINE_VERSION=\"5.7.0-alpha.0\" -DENABLE_PLUGINS -DNOMINMAX -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSTB_TEXTEDIT_KEYTYPE=unsigned -IC:\.conan\48118dc\1\i
nclude -IC:\.conan\48118dc\1\build\Release -external:IC:\.conan\03fb8f\1\include -external:IC:\.conan\7bc969\1\include -external:IC:\.conan\4629b0\1\include -ext
ernal:IC:\.conan\9d3754\1\include -external:IC:\.conan\947143\1\include -external:IC:\.conan\98be21\1\include -external:IC:\.conan\66c1ac\1\include -external:IC:
\.conan\1d1a1a\1\include -external:IC:\.conan\1ac290\1\include -external:IC:\.conan\e93481\1\include -external:IC:\.conan\755237\1\include -external:IC:\.conan\5
26a08\1\include -external:IC:\.conan\b09ce1\1\include -external:IC:\.conan\5031af\1\include -external:IC:\.conan\9f3e78\1\include -external:IC:\.conan\9152f7\1\i
nclude -external:IC:\.conan\26857d\1\include -external:IC:\.conan\f4be54\1\include -external:IC:\.conan\0e0feb\1\include -external:IC:\.conan\797c5b\1\include -e
xternal:W0 /DWIN32 /D_WINDOWS /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD /permissive- /showIncludes /FoCMakeFiles\_CuraEngine.dir\src\LayerPlan.cpp.obj /FdCMakeFiles\_CuraEngine.dir\_CuraEngine.pdb /FS -c C:\.conan\48118dc\1\src\LayerPlan.cpp
C:\.conan\48118dc\1\build\Release\Cura.pb.h(17): fatal error C1189: #error:  This file was generated by an older version of protoc which is
[20/190] Building CXX object CMakeFiles\_CuraEngine.dir\src\FffGcodeWriter.cpp.obj
ninja: build stopped: subcommand failed.
curaengine/5.7.0-alpha.0: 
curaengine/5.7.0-alpha.0: ERROR: Package '7f4188e9845d7f02c44b286c42266f8f8b7672ca' build failed
curaengine/5.7.0-alpha.0: WARN: Build folder C:\.conan\48118dc\1\build\Release
ERROR: curaengine/5.7.0-alpha.0: Error in build() method, line 174
        cmake.build()
        ConanException: Error 1 while executing cmake --build "C:\.conan\48118dc\1\build\Release" -- -j12

### Expected results

None

### Add your .zip and screenshots here ⬇️

cmake version 3.28.3
ninja version 1.11.1.git.kitware.jobserver-1
sip version Version  6.5.1
python version 3.11.7

**Comment by jellespijker** [comment]
Should be fixed with this commit https://github.com/Ultimaker/Cura/commit/5f884c737b4d331627ee53b074419263b5a848e1
Can you please try again
