### ISSUE TITLE
it just failed

### ISSUE THREAD

**Issue by hotntot11** [Ultimaker/Cura#18390]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

ender 3v2

### Name abnormal settings

no

### Describe model location

no

### Describe your model

yes

### Add your .zip here ⬇️

"C:\Users\Antoni\Downloads\FREE_MECH_STL.zip"

**Comment by Vandresc** [comment]
Hi @hotntot11 , you uploaded the path of where your file is located, could you please try to save it as a project, zip it, and upload it here? Thank you!
