### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by benclewett** [Ultimaker/Cura#18405]
### Cura Version

5.6.0

### Operating System

Mac 14.2.1 (23C71)

### Printer

Creality v2 Neo

### Describe your model

I have slices similar models from the same engine and printed them successfully.  This model is complete and correct.

### Add your .zip here ⬇️

https://we.tl/t-LcwStCB1mc

**Comment by Vandresc** [comment]
Hi @benclewett thank you for the report, it was sliced for me in our internal build, so the fix will be in the next release.
 If still an issue please re-open.

**Comment by Vandresc** [comment]
We try to release every 3 months.
And a little birdy told me that a release is coming up, so you hopefully don't have to wait that long.
Thanks again for reporting! Together we can make Cura better.

**Comment by benclewett** [comment]
I’m looking forward to it…..

Thanks for excellent support.
