### ISSUE TITLE
Creality Ender-3 V3 SE start G-code BUG

### ISSUE THREAD

**Issue by zanghao912** [Ultimaker/Cura#18400]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender-3 V3 SE

### Reproduction steps

There is an error in this field in the start G-code
M109 S[material_print_temperature_layer_0]

### Actual results

This value is not available after slicing with the slicing software.

### Expected results

It should be fixed to
M109 S{material_print_temperature_layer_0}

### Add your .zip and screenshots here ⬇️

not

**Comment by GregValiant** [comment]
Thanks for the report.
@HellAholic - will you be putting in a PR to change the brackets?

**Comment by zanghao912** [comment]
Yes, I've committed.![image](https://github.com/Ultimaker/Cura/assets/42427653/b8fceb44-0447-4281-8712-0729896ea0dd)

**Comment by HellAholic** [comment]
Found the existing PR that fixes this issue https://github.com/Ultimaker/Cura/pull/17781
Thanks for the report.

Cheers!
