### ISSUE TITLE
Audi modell cant slice

### ISSUE THREAD

**Issue by SzTomy** [Ultimaker/Cura#18409]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Wanhao Duplicator 5S

### Describe your model

Car model

### Add your .zip here ⬇️

[Uploading WD5S_AUDI MODELL KERÉK NÉLKÜL.zip…]()

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
