### ISSUE TITLE
relleno no aparece 

### ISSUE THREAD

**Issue by JUANMX499** [Ultimaker/Cura#18412]
### Cura Version

5.6

### Operating System

mac m1

### Printer

genius 

### Name abnormal settings

lo normal para una litofonia

### Describe model location

no aparece el relleno cuando lo segmento

### Describe your model

si, ese y otros mas

### Add your .zip here ⬇️

<img width="1186" alt="Captura de pantalla 2024-02-23 a la(s) 13 00 15" src="https://github.com/Ultimaker/Cura/assets/113067188/76c3258f-c24a-4a8d-b84c-d4d919a17ac7">

**Comment by Vandresc** [comment]
Hey,
We've implemented several fixes in hopes of eliminating most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue persists.
Cheers!
