### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by Federbein0815** [Ultimaker/Cura#18410]
### Cura Version

5.7.0. Alpha 

### Operating System

Windows 11

### Printer

Snapmaker A250T

### Describe your model

I scaled  up to 190% - with 100% no problem 

### Add your .zip here ⬇️

[S2A_Celestial Resonance_ Unseen Dimensions.zip](https://github.com/Ultimaker/Cura/files/14386839/S2A_Celestial.Resonance_.Unseen.Dimensions.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
