### ISSUE TITLE
Slicing not possible

### ISSUE THREAD

**Issue by aitorvv** [Ultimaker/Cura#18427]
### Cura Version

5.5.0

### Operating System

Linux

### Printer

Kingroon KP3S

### Describe your model

no, it was the first time

### Add your .zip here ⬇️

[Uploading KK_DBZ_goku_Phone_Stand.zip…]()

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
