### ISSUE TITLE
Slicing fehlgeschlagen

### ISSUE THREAD

**Issue by supermarioiv** [Ultimaker/Cura#18429]
### Cura Version

5.6.0

### Operating System

Windows 11 updates aktuell

### Printer

Sovol SV02

### Describe model location

Gartenzaun

### Describe your model

Ja

### Add your .zip here ⬇️

[GB Zaun groß.zip](https://github.com/Ultimaker/Cura/files/14396314/GB.Zaun.gross.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
