### ISSUE TITLE
Error slicing model

### ISSUE THREAD

**Issue by joaopjrn** [Ultimaker/Cura#18431]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 4

### Name abnormal settings

tree supports enabled

### Describe your model

it does slice fine if i make it shorter or change the layer height, crashes at layer height 0.32, it also does slice at 0.32 if i lay the model on its side (90 degrees)

### Add your .zip here ⬇️

[EN3_ImageToStl.com_hl._elisabeth2.zip](https://github.com/Ultimaker/Cura/files/14396857/EN3_ImageToStl.com_hl._elisabeth2.zip)

slicing error occurs when trying to slice the model, scaled to have 200mm on the z axis, with uniform scaling enabled.

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
