### ISSUE TITLE
Slicing Hangs with Tree Support even though not needed.

### ISSUE THREAD

**Issue by snafu76** [Ultimaker/Cura#18437]
### Cura Version

5.7.0 alpha

### Operating System

Windows 11

### Printer

Ender 3 Max/Marlin 2.7

### Reproduction steps

Exported design directly from Fusion 360 into Cura 5.7.0 alpha.  (Running beta due unexpected slicing errors with 5.6.0.) Support option with Tree Support from Everywhere was already selected even though not required for this design.
Started slicing process.
Process hung after a couple seconds at about 25% - waited several minutes for it continue but nothing changed.
Cancelled slicing and tried again - same results.

### Actual results

Turning off Support or changing to use Tree Support only touching Build Plate worked.  Changed support back to Tree/Everywhere and slicing hangs consistently.

### Expected results

Works with other versions of Cura, including 5.6.0.

### Add your .zip and screenshots here ⬇️

[Bug_Report.zip](https://github.com/Ultimaker/Cura/files/14397879/Bug_Report.zip)

**Comment by Asterchades** [comment]
This is, unfortunately, expected at the moment. The good news is that patches have already been made which should correct the issue in the next build of 5.7.

See [PR 2028](https://github.com/Ultimaker/CuraEngine/pull/2028) for the actual fix itself.
