### ISSUE TITLE
I would like to add new features

### ISSUE THREAD

**Issue by wzb261643358** [Ultimaker/Cura#18439]
### Is your feature request related to a problem?

Yes, I would like to try printing a layer on the first layer as a platform for material adhesion, and I would like the software to add this option
At this time, I have two extruders. The second extruder extrudes the first layer of printed material, and the printing part is completed using the first extruder

### Describe the solution you'd like

Yes, I would like to try printing a layer on the first layer as a platform for material adhesion, and I would like the software to add this option
At this time, I have two extruders. The second extruder extrudes the first layer of printed material, and the printing part is completed using the first extruder

### Describe alternatives you've considered

Of course, I can design two files to be stacked together, but its settings are quite complex

### Affected users and/or printers

me

### Additional information & file uploads

not file

**Comment by Asterchades** [comment]
This sounds like the same basic behaviour as a Raft, which has been present for years. The only real difference is that a Raft is a minimum of three layers tall, which is by design as it was intended to compensate for the older, less refined printer beds that were available over a decade ago.

**Comment by HellAholic** [comment]
We've improved the behavior of the Raft we currently have as build plate adhesion. Users can (in near future) modify the behavior to suit their needs.
Keep an eye out for a beta release coming :)
