### ISSUE TITLE
issue slicing

### ISSUE THREAD

**Issue by littlespike24** [Ultimaker/Cura#18449]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

ender 3v2

### Name abnormal settings

sam

### Describe model location

If I make it really small it will slice

### Describe your model

never before

### Add your .zip here ⬇️

File is to big but its called airless basketball on thingy verse. Also the print is too big for my printer so I sized it down.

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
