### ISSUE TITLE
Large Models Will Not Slice

### ISSUE THREAD

**Issue by JPrint69** [Ultimaker/Cura#18447]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3 Max

### Name abnormal settings

Tree Supports? 

### Describe model location

Center of bed. It slices if I shrink the model size.

### Describe your model

Large Mech Robot

### Add your .zip here ⬇️

I have tried multiple setting options. Tree supports, normal supports, no supports. The only way I can the model to slice is if I reduce
[Large Mech Robot Project.zip](https://github.com/Ultimaker/Cura/files/14409345/Large.Mech.Robot.Project.zip)
the z height below 100mm and even that has proven to be hit or miss.

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
