### ISSUE TITLE
Error path in slicing

### ISSUE THREAD

**Issue by constantinsta** [Ultimaker/Cura#18440]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality CR-10S Pro V2

### Reproduction steps

I am slicing the object.
And I press preview. 

### Actual results

After the first printed level, the printer head is moving to a specific point, after each line is printed.

### Expected results

A working g-code file without bugs

### Add your .zip and screenshots here ⬇️

[Box.zip](https://github.com/Ultimaker/Cura/files/14402471/Box.zip)
![Screenshot 4](https://github.com/Ultimaker/Cura/assets/149818552/26ade363-d118-48a4-98b8-81aed16c1d30)
![Screenshot 1](https://github.com/Ultimaker/Cura/assets/149818552/0233b7fa-9302-41e4-ab9a-bbe4e6dabbd0)
![Screenshot 2](https://github.com/Ultimaker/Cura/assets/149818552/1a1f5196-9362-46b9-92a0-f46e2bf2c6af)
![Screenshot 3](https://github.com/Ultimaker/Cura/assets/149818552/4fa972e6-7922-4a3c-80d3-f1d45f2abd9f)

**Comment by GregValiant** [comment]
Thanks for the report.
I agree, that doesn't look right.  It might be a problem with the combing mode "Not in skin".  In the "Travel" section, changing the combing mode to "All" appears to make the problem go away.

The Cura team will take a look.

**Comment by HellAholic** [comment]
Thanks for the report. 
We have a ticket on the backlog related to the combin not in skin.
Internal reference: CURA-10308

Cheers!
