### ISSUE TITLE
Failed slice

### ISSUE THREAD

**Issue by SweetMelange** [Ultimaker/Cura#18444]
### Cura Version

5.5.0

### Operating System

Windows 11 

### Printer

AnkerMake M5

### Name abnormal settings

no

### Describe model location

articulated skeleton

### Describe your model

I have sliced this model with an older version of Cura 

### Add your .zip here ⬇️

file is more that 25 MB

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
