### ISSUE TITLE
slicing failure

### ISSUE THREAD

**Issue by azreal2012** [Ultimaker/Cura#18454]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

sovol SV01 Pro

### Reproduction steps

dragged stl file to cura. selected petg settings and attempted to slice. 

### Actual results

will not slice

### Expected results

provide a sliced file

### Add your .zip and screenshots here ⬇️

[SS_PT111_rc1 with holster rail.zip](https://github.com/Ultimaker/Cura/files/14422654/SS_PT111_rc1.with.holster.rail.zip)
![Screenshot 2024-02-27 ](https://github.com/Ultimaker/Cura/assets/161494207/254cd355-9734-49ae-ba4a-9d8bd5be7ba0)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
