### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by RickLezzMorty84** [Ultimaker/Cura#18451]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

sovol 6 pluss

### Name abnormal settings

none

### Describe model location

middle

### Describe your model

spiderman 2099 mask 

### Add your .zip here ⬇️

[196132-spider-man-2099-inspired-helmet-9bdace13-5ab4-481d-83c4-83b740062617.pdf](https://github.com/Ultimaker/Cura/files/14414829/196132-spider-man-2099-inspired-helmet-9bdace13-5ab4-481d-83c4-83b740062617.pdf)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
