### ISSUE TITLE
Error al segmentar un archivo.

### ISSUE THREAD

**Issue by Rizzzos** [Ultimaker/Cura#18452]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

LotMaxx SC-10

### Reproduction steps

1. Inicié Cura
2. Agregué el archivo STL que quería laminar.

### Actual results

Saltó el error de segmentación.

### Expected results

Que me dejara modificar los parametros de laminado para crear el GCODE

### Add your .zip and screenshots here ⬇️

[Logitech_foot_replacement_V3.zip](https://github.com/Ultimaker/Cura/files/14417205/Logitech_foot_replacement_V3.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
