### ISSUE TITLE
Min Figure Slicing Error after new profile is added

### ISSUE THREAD

**Issue by eAddict** [Ultimaker/Cura#18458]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3

### Name abnormal settings

Tried new Cura profile for Minis from Fat Dragon Games

### Describe model location

Center of plate

### Describe your model

Mini for D&D.   Sliced and printed fine before new profile

### Add your .zip here ⬇️

[CE3E3V2_ADnDv1.zip](https://github.com/Ultimaker/Cura/files/14435370/CE3E3V2_ADnDv1.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
