### ISSUE TITLE
the printer is not in the list

### ISSUE THREAD

**Issue by Filipossss77** [Ultimaker/Cura#18459]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3 V3 KE

### Reproduction steps

I did everything according to the IP address procedure, but I can't find the printer and the printer isn't even in the list where I can add it manually, it's just not there

### Actual results

I didn't find it in the list, there is only ender 3 v3, but I didn't find ender 3 v3 anywhere

### Expected results

I would like to print in two colors because Creality does not have the possibility to change the g code

### Add your .zip and screenshots here ⬇️

nemam co pridat dakujem

**Comment by GregValiant** [comment]
Thanks for the report.
I have no idea what the difference is between a "Ender 3 V3 SE" and a "Ender 3 V3 KE".  Someone submitted the "SE" definition files but whether they would be appropriate for the KE model is something you would need to check.

All definition files for non-UltiMaker printers come from the community or from the manufacturer.  You would need to get with Creality to find out if they will be supplying a definition file for your printer.
I'll remove the bug label from this and close it as it isn't an "UltiMaker Cura" problem.
