### ISSUE TITLE
Tree Support Slicing Issue

### ISSUE THREAD

**Issue by kodamoor** [Ultimaker/Cura#18462]
### Cura Version

5.6.0

### Operating System

Windows11

### Printer

Anycubic Kobra Neo

### Name abnormal settings

It slices when I dont have tree supports

### Describe model location

If I rotate it the it does slice but if I move it it still doesnt

### Describe your model

Yes it slices without the tree supports.

### Add your .zip here ⬇️

It's more than 1 file where I cannot slice when using tree supports but normal supports it does slice.
[Phone_Case_Troubleshoot.zip](https://github.com/Ultimaker/Cura/files/14440242/Phone_Case_Troubleshoot.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
