### ISSUE TITLE
Failed slicing with user overrides

### ISSUE THREAD

**Issue by AdamWHY2K** [Ultimaker/Cura#18461]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Neptune 2

### Name abnormal settings

Slices correctly without user overrides. Not sure which would cause the error though

### Describe model location

No

### Describe your model

Never printed this one before, it's 5 five different STLs so maybe that has something to do with the issue.

### Add your .zip here ⬇️

[slice_error.zip](https://github.com/Ultimaker/Cura/files/14439884/slice_error.zip)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
