### ISSUE TITLE
Slicing stops

### ISSUE THREAD

**Issue by MrBommy** [Ultimaker/Cura#18467]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender-3 / Ender-3 v2

### Reproduction steps

I downloaded this file:
https://cults3d.com/en/3d-model/game/baseball-trophy-ball-holder
When opening in Cura it stops while making the slice

### Actual results

It stops and gives a message to send bug

### Expected results

Need to slice this so I can print as present!
Please help me fix

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/Ultimaker/Cura/files/14447275/cura.log)
![03](https://github.com/Ultimaker/Cura/assets/161714069/5aca27b0-2358-43c5-a9e3-d0f7a63a55a3)
![01](https://github.com/Ultimaker/Cura/assets/161714069/8f8c4cbd-9f10-4b7e-9604-da9b1655250d)
![02](https://github.com/Ultimaker/Cura/assets/161714069/faf06fa0-28cf-4cca-bd37-9f27caf5e7a9)

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
