### ISSUE TITLE
Slicing failed 

### ISSUE THREAD

**Issue by Nike1807** [Ultimaker/Cura#18471]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3 Neo

### Name abnormal settings

No

### Describe model location

No

### Describe your model

No, I have never done it. It always fails

### Add your .zip here ⬇️

[Uploading CFFFP_Crest Side -Crash.zip…]()

**Comment by HellAholic** [comment]
Hey,
We've implemented several fixes in hopes to eliminate most of the slicing errors. These fixes will be included in the next Cura release that will be available soon.
Please retry with the upcoming beta and feel free to re-open if the issue still persists.

Cheers!
