### ISSUE TITLE
Can't slice anything

### ISSUE THREAD

**Issue by Handydoug** [Ultimaker/Cura#18486]
### Cura Version

Full Version Cura 5.7 Alpha

### Operating System

Ubuntu 22.04.4 LTS

### Printer

Creality Ender 5 Plus

### Name abnormal settings

No and No

### Describe model location

No and No

### Describe your model

No. And yes

### Add your .zip here ⬇️

[CE5P_red cube.zip](https://github.com/Ultimaker/Cura/files/14468390/CE5P_red.cube.zip)

**Comment by HellAholic** [comment]
Hey, 
Your issue might be the same as what has been described in https://github.com/Ultimaker/CuraEngine_plugin_infill_generate/issues/7 , you can try the workaround suggested there to see if that resolves the issue. Outside of that you can always go back to the last stable release version that functions on your device. The alpha builds are not meant for production use so please keep that in mind.

Cheers!
