### ISSUE TITLE
Version 5.6.0

### ISSUE THREAD

**Issue by MBE23** [Ultimaker/Cura#18505]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

ZONESTAR Z9V5

### Reproduction steps

Après découpe, le bouton n'est pas traduit (Save - enregistré)

### Actual results

rien

### Expected results

rien

### Add your .zip and screenshots here ⬇️

Pas de traduction voir image (SaveTo Disk  -> Enregistré sur le disque)
![image](https://github.com/Ultimaker/Cura/assets/77835047/fca3c5dc-82a2-4e0f-8819-2d10d5a3b12c)

**Comment by Vandresc** [comment]
Hi @MBE23 , we fixed that a while ago, the fix will be included in the next release, thank you for your feedback
![image (28)](https://github.com/Ultimaker/Cura/assets/77665581/9193898d-6d49-4172-adf5-9dd7f6733581)

**Comment by MBE23** [comment]
Thanks, this is fixed in version 5.7.0-beta.1
