### ISSUE TITLE
Usability error, when the supports don't fit on the bed, there's only a random error.

### ISSUE THREAD

**Issue by allanonmage** [Ultimaker/Cura#18506]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender 3v2

### Describe your model

Scaled up to fill the bed

### Add your .zip here ⬇️

If there isn't enough room on the bed to fit tree like supports, slicing fails with an "unknown error".  It's good that you are checking for this, it's bad that your error is "unknown error".  For example, scale up "BT-b_MechBay-Single-2.11.stl" to 300% or so and try to use tree supports.  They fail, presumably because they would be off the bed.
[scifi-building-war-robot-storage-bay-single-6mm-model_files.zip](https://github.com/Ultimaker/Cura/files/14475067/scifi-building-war-robot-storage-bay-single-6mm-model_files.zip)

You should display a clear message, something like "tree supports don't fit on the bed, choose another kind of support", or make the base of the supports on the bed adaptive.

**Comment by Vandresc** [comment]
Hi @allanonmage, thanks for the feedback we will take note of it. Could you please include a project file where the error is reproduced? This depends on your model orientation and placement which we do not get from the .stl files.
