### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by TragicEndings** [Ultimaker/Cura#18510]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

biqu

### Name abnormal settings

no wont slice either way

### Describe model location

center of build plate

### Describe your model

airless basketball

### Add your .zip here ⬇️

[BB1_Basketball_ver_0.4.zip](https://github.com/Ultimaker/Cura/files/14489965/BB1_Basketball_ver_0.4.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura's Mesh Tools said the model was watertight but MS3D Builder didn't like the model at all.
The on-line repair tool I use says there are 91,627 Inverted faces.  That's a fair percentage of the 534,270 total faces.  When a surface is inverted the slicer can't tell the inside of the model from the outside.

I'll remove the bug label and close this as it is a model issue.  I hope you understand.

This took a long time to slice and it's a 33 hour print.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c27110cc-1f93-4e5e-bd70-f5322ec7cbd0)
