### ISSUE TITLE
Drop Down Model

### ISSUE THREAD

**Issue by Luigi80bn** [Ultimaker/Cura#18513]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

WASP 4070I

### Reproduction steps

I wanted to point out this error:
After removing the check in Drop Down Model and setting the measurement parameters of an object used as a mesh cutout (I use it to create an area with greater filling) and saving the model in 3mf, when I reopen the saved file the program resets the parameters to 0 and puts the checkmark back in Drop Down Model. How can I solve it?

### Actual results

Non cambia nulla

### Expected results

Dovrebbe mantenere i miei parametri.

### Add your .zip and screenshots here ⬇️

![Prima](https://github.com/Ultimaker/Cura/assets/161583478/bce79ad6-cde7-4dfe-a54e-4b8af28906c0)
![Dopo](https://github.com/Ultimaker/Cura/assets/161583478/9e0ddb9d-17c3-460a-bcfe-0b81bf39fca3)

**Comment by Asterchades** [comment]
There's a setting rather appropriately named `Automatically drop models to the build plate` in the Cura preferences. I'm unsure what this will translate to, but it should be about the fourth option up from the bottom of the preferences when you first open them.
