### ISSUE TITLE
Cura loads but Window doesn't show on Linux

### ISSUE THREAD

**Issue by unluckynelson** [Ultimaker/Cura#18538]
### Cura Version

5.6.0

### Operating System

Garuda Linux

### Printer

Creality 3 pro

### Reproduction steps

Run the appimage

Terminal output:
```
λ ./UltiMaker-Cura-5.6.0-linux-X64_cbc4dfea87e29f7635e925d1ba0769c0.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: Windows, Fusion
QQmlApplicationEngine failed to load component
QQmlComponent: Component is not ready

** (UltiMaker-Cura:8904): WARNING **: 17:30:03.264: atk-bridge: get_device_events_reply: unknown signature
```
It seems like it is running but with no window

Here's the log files:
[cura.log](https://github.com/Ultimaker/Cura/files/14526592/cura.log)

Tried installing:
sudo pacman -S qt6-wayland

### Actual results

The splash screen shows and finishes loading but the window doesn't open

### Expected results

I expect the main window to display

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/8517425/db801b1f-7eea-455b-96ff-f44f1fd4e5b7)

**Comment by unluckynelson** [comment]
The suggestion in this issue solved my problem: https://github.com/Ultimaker/Cura/issues/12940

Running the appimage with `QT_STYLE_OVERRIDE=""` worked for me

**Comment by Vandresc** [comment]
Hi @unluckynelson , glad the workaround did work for you.

**Comment by doobes** [comment]
> The suggestion in this issue solved my problem: #12940
> 
> Running the appimage with `QT_STYLE_OVERRIDE=""` worked for me

Thanks.

How, exactly, is this done?

I'm a bit of a Linux neophyte

chris

**Comment by unluckynelson** [comment]
You just run it inline with the appimage.$> QT_STYLE_OVERRIDE="" ultimaker_cura.appimageSent from my Galaxy
-------- Original message --------From: Chris ***@***.***> Date: 2024/03/08  15:12  (GMT+02:00) To: Ultimaker/Cura ***@***.***> Cc: Johan ***@***.***>, Mention ***@***.***> Subject: Re: [Ultimaker/Cura] Cura loads but Window doesn't show on Linux (Issue #18538) 

The suggestion in this issue solved my problem: #12940
Running the appimage with QT_STYLE_OVERRIDE="" worked for me

Thanks.
How, exactly, is this done?
I'm a bit of a Linux neophyte
chris

**Comment by doobes** [comment]
Nope.


![Screenshot from 2024-03-09 10 30 33](https://github.com/Ultimaker/Cura/assets/23409761/16b24a33-235b-42db-bdba-34da02c6ab23)

**Comment by doobes** [comment]
Nope:

![Screenshot from 2024-03-09 10 33 45](https://github.com/Ultimaker/Cura/assets/23409761/7abad8a3-eef9-4946-bc7f-08e01750b52a)

**Comment by unluckynelson** [comment]
Before calling appimage. Not afterSent from my Galaxy
-------- Original message --------From: Chris ***@***.***> Date: 2024/03/09  17:34  (GMT+02:00) To: Ultimaker/Cura ***@***.***> Cc: Johan ***@***.***>, Mention ***@***.***> Subject: Re: [Ultimaker/Cura] Cura loads but Window doesn't show on Linux (Issue #18538) 
Nope:
Screenshot.from.2024-03-09.10.33.45.jpeg (view on web)
