### ISSUE TITLE
Unable to slice Megatron statue

### ISSUE THREAD

**Issue by HydroidPrym** [Ultimaker/Cura#18544]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

none

### Describe model location

no

### Describe your model

no

### Add your .zip here ⬇️

[Megatron Cura.zip](https://github.com/Ultimaker/Cura/files/14532079/Megatron.Cura.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Those are the most error filled models I have seen in a while.  They need to be repaired before they will slice.
This is the first megatron file.
The polka-dot surfaces indicate surfaces that are inside-out.
![image](https://github.com/Ultimaker/Cura/assets/64202104/dec627d0-29f8-447c-8a46-652dca58a036)

This is another file in Cura x-ray view.  The red surfaces are errors.
![image](https://github.com/Ultimaker/Cura/assets/64202104/822f4a3c-902a-4339-9992-9af5dc485cd1)

This is the right arm after slicing with PrusaSlicer.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5f09a6ef-5733-4dd7-b085-5d3206bee644)

I'll remove the bug label from this.  The model is really bad and needs repair before we can figure out if there is a bug involved here.  I'll close this as well.
