### ISSUE TITLE
Parametric cable holder

### ISSUE THREAD

**Issue by drwillden** [Ultimaker/Cura#18543]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Cobra 2

### Describe your model

First attempt on model

### Add your .zip here ⬇️

[Parametric Cable Holder - 6397545.zip](https://github.com/Ultimaker/Cura/files/14531945/Parametric.Cable.Holder.-.6397545.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file I can't tell what your settings are and consequently there can't be an investigation.
Please provide a project file that shows whatever problem you are having.  Right now I have no idea what's going on.
