### ISSUE TITLE
Tree support Failing

### ISSUE THREAD

**Issue by DustinCulver** [Ultimaker/Cura#18562]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3 V2

### Reproduction steps

Changed support to Tree clicked slice.

### Actual results

Error shows and it does not slice.

### Expected results

Slicing as with normal support.

### Add your .zip and screenshots here ⬇️

none

**Comment by Asterchades** [comment]
There is a known fault with Tree Supports as of 5.4 where slicing a model that results in no supports being generated will cause it to fail when being sliced. This has already been corrected for 5.7.

If this is not your issue then you will need to provide more information - such as a project file requested when initially making this report.
