### ISSUE TITLE
Trouble slicing a predator bust.

### ISSUE THREAD

**Issue by BizzarePrinter** [Ultimaker/Cura#18586]
### Cura Version

5.4

### Operating System

MacOS

### Printer

Elegoo Neptune 3 PRO

### Name abnormal settings

I have changed basicaly every setting available.

### Describe model location

It will slice if I rotate it 90 degrees

### Describe your model

I haven't ever sliced it before, this is the first time. No I have not tried to fix the mesh issues. I did not know that there might be mesh issues.

### Add your .zip here ⬇️

[predator-ultra-detailed-support-free-bust-3d-model copy.zip](https://github.com/Ultimaker/Cura/files/14582343/predator-ultra-detailed-support-free-bust-3d-model.copy.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model is full of errors.  There is no way to tell if this is a model problem or a Cura slicing bug.
The repaired model successfully sliced for me in 5.6.0.

I'll remove the Bug and Slicing Error tags and close this.  I hope you understand.
