### ISSUE TITLE
Small and not importan fails on Cura GUI

### ISSUE THREAD

**Issue by luisonoff** [Ultimaker/Cura#186]
On machine settings, when I select skirt speed as an option to be displayed, I lose bottom layer speed. Why? I find them to be compatible and want to be able to tune both.

The SAVE button at the end of right panel has to options, SD save or Disk save. I does not matter what I leave chosen, every time I open Cura, if I have an SD card on my PC, it defaults this button to SD save, which I never use.

I never use SD save because it does not let me choose destination folder inside SD card nor choose a name for this gcode. Is this intentionally? I find it useless. I would love an option that defaults to my SD card route, but then lets me choose folders inside and name.

**Comment by nallath** [comment]
I made a post here about how the settings work; http://ultimaker.com/en/official-ultimaker-news/view/16592-we-made-it-the-new-cura?page=8#reply-113814 
It seems that the skirt speed is a child of the bottom layer speed. This is a bit of a weird relation imho (which will need to be changed)

With regards to the SD & Disk saving; The SD card saving is meant as a quick way of doing things. This is why it doesn't give you the option to rename stuff or put it in a folder. It would be possible to make a plugin that does what you want, but it doesn't have priority for us right now (as you are the only one who reported this issue).
