### ISSUE TITLE
No way to put Relative extrusion

### ISSUE THREAD

**Issue by Benraay** [Ultimaker/Cura#1862]
Hi everybody,

Thanks for the work you all do on this Slicer.
I have a printer that does not support Absolute extrusion, I need absolutely to output Gcode with Relative E values, I searched for a long time and Googled but nothing on how to change that setting in the Machine settings can someone help ?

**Comment by nallath** [comment]
Not as far as I know. @BagelOrb

**Comment by BagelOrb** [comment]
It's not possible and we don't need it for our machines so we're not going to implement it.

**Comment by Ghostkeeper** [comment]
This could be solved with a post-processing script, perhaps. Basically you need to go over every line and see how much extrusion is used and subtract the previous E-value from the current extrusion.

**Comment by Benraay** [comment]
yes it's what I planned to do, looks not so difficult.

Benjamin Raaymakers


CONFIDENTIALITY NOTICE:

The contents of this email message and any attachments are intended solely
for the addressee(s) and may contain confidential and/or privileged
information and may be legally protected from disclosure. If you are not
the intended recipient of this message or their agent, or if this message has
been addressed to you in error, please immediately alert the sender by
reply email and thendelete this message and any attachments. If you are not
the intended recipient, you are hereby notified that any use,
dissemination, copying, or storage of this message or its attachments
is strictly
prohibited.


2017-05-24 11:57 GMT+02:00 Ghostkeeper <notifications@github.com>:
