### ISSUE TITLE
Everything works fine but when i add specifically tree supports

### ISSUE THREAD

**Issue by VicLeComique** [Ultimaker/Cura#18628]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Kobra Go

### Name abnormal settings

Tree supports

### Describe model location

when i set the model standing up, it doesn't slice, when i rotate the model 25 degrees, it works

### Describe your model

Its a splatoon inkling in obj format

### Add your .zip here ⬇️

Everything works fine but when i add specifically tree supports, i get an error, and its just on certain models

**Comment by HellAholic** [comment]
Hey @VicLeComique 

We had a few issues regarding tree support that have been addressed in the latest Beta release for 5.7
Could you give the beta version a try and see if your issues have been resolved there?

https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1
