### ISSUE TITLE
Slicing Error with Zinogre model

### ISSUE THREAD

**Issue by NewEra-09** [Ultimaker/Cura#18624]
### Cura Version

5.6.0.

### Operating System

windows 10

### Printer

Ultimaker 3

### Name abnormal settings

Changed spool 2 to PVA bb .4 as required by print shop

### Describe your model

I've sliced this model before but never with ultimaker and meshtool plugin did not help.

### Add your .zip here ⬇️

https://we.tl/t-7jj9WpmTKM

**Comment by HellAholic** [comment]
Hey @NewEra-09 ,
Please include a project file without unwelcome guests. Upload your zip file directly to github or trusted file sharing platforms such as google drive.
