### ISSUE TITLE
Mounting bracket print fail to slice

### ISSUE THREAD

**Issue by sstarkny** [Ultimaker/Cura#18627]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

tree supports, brim enabled

### Describe model location

lip of the bracket faces up

### Describe your model

Breadboard mounting bracket

### Add your .zip here ⬇️

[breadboard_mount_rev_2.zip](https://github.com/Ultimaker/Cura/files/14621826/breadboard_mount_rev_2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There have been numerous reports regarding Cura having trouble on Win11 systems.
I'll mark this as a duplicate as I didn't have any trouble slicing the model on my Win10 system.
The Cura team is aware of this bug and hopefully it will be repaired in 5.7.

**Comment by MariMakes** [comment]
Hi @sstarkny 

Thanks for your report 👍
Several slicing crashes have been resolved with the 5.7 Beta release.

I was able to slice your file in that version of Cura. 
![image](https://github.com/Ultimaker/Cura/assets/40423138/c25e57bf-07e4-4465-9497-803aacda3d9a)

You can download the Cura version here: [https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)

Can you let us know if that version of Cura resolves your issue? 

Thanks again, and please let us know if you run into any other issues 💪
