### ISSUE TITLE
Placa madre quemada

### ISSUE THREAD

**Issue by josellopz** [Ultimaker/Cura#18629]
### Cura Version

5.7.0 Beta1

### Operating System

Windows 11

### Printer

Mingda Magician X

### Reproduction steps

Actualización a version Beta
Carga de STL
Creacion de GCode y pasarlo a la SD
Inicio de impresion
Humo y placa madre quemada
![placa](https://github.com/Ultimaker/Cura/assets/163620456/861e0bb3-673b-40dd-a99b-a8f8088810d9)

### Actual results

Sin impresora

### Expected results

Verifiquen que sucede con el voltaje

### Add your .zip and screenshots here ⬇️

![placa 2](https://github.com/Ultimaker/Cura/assets/163620456/8ac00620-0940-43a4-8761-8348aff8a74a)

**Comment by GregValiant** [comment]
Thanks for the report.
It simply is not possible for this to be a Cura problem.  There is no gcode command for "Start the mainboard on fire".

I'll go ahead and remove the bug label and close this.  You have a hardware problem.
