### ISSUE TITLE
No way to edit printer after it has been added

### ISSUE THREAD

**Issue by zipCoder933** [Ultimaker/Cura#18622]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Every printer

### Reproduction steps

Go to 
Preferences > Configure Cura > Printers

### Actual results

Preferences > Configure Cura > Printers
There is no machine settings button, just update firmware

### Expected results

Preferences > Printers
There should be a machine settings button alongside the update firmware button

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-03-15 091257](https://github.com/Ultimaker/Cura/assets/67439766/6b9a233e-61fe-4692-aff8-527e4d850583)

**Comment by GregValiant** [comment]
Thanks for the report.
This is not a Cura bug but rather an indication that the FlashForge Adventure 3 definition files are not correct or incomplete.  That printer is not included in the over 300 that Cura supports.
How did you install it (network printer, non-network printer?) and where did the definition files come from?
Did you install the FlashForge Printer Integration plugin?

I'm sure that if you activate that Ender 3 you will see that the Machine Settings will be available.  Even on your computer this is not likely an "every printer" bug.  I don't have the problem on my computer and I have over 20 printers installed at any given time.
