### ISSUE TITLE
Slicing Issue

### ISSUE THREAD

**Issue by ch4r003** [Ultimaker/Cura#18636]
### Cura Version

5.6.0

### Operating System

MacOS

### Printer

Creality CR10S

### Describe your model

I have sliced it succesfully before yet it's not working.

### Add your .zip here ⬇️

When I tried to angle the model I was trying to slice, cura suddenly got an error.

**Comment by MariMakes** [comment]
Several slicing crashes have been resolved with the 5.7 Beta release.

You can download the Cura version here: [https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
