### ISSUE TITLE
CD mount for a SatNav v2

### ISSUE THREAD

**Issue by iandavys** [Ultimaker/Cura#18640]
### Cura Version

5.5.0.

### Operating System

windows 11

### Printer

Flsun Q5

### Reproduction steps

As Hope fully you can see i printed out my CD mount. while I was printing it I noted that on one side it was hollow and there was no infill! i carried on untill it was finished, and it is ok but not as rigid this is because of the lack of infill!
I have no idea what i have done, as it is probably me that has done somthing incorrectly.

### Actual results

 I carried on printing the mount out untill it was finished, and it is ok but not as rigid this is because of the lack of infill!
I have no idea what i have done, as it is probably me that has done somthing incorrectly.

### Expected results

the voided areas were supposed to have infill in them.
Hopefully someone will be able to tell me what has happend.
I have seen this before with other prints i have done, but thought it would be better not to say any thing.
Thank you for all the work you guys put in to this software!

### Add your .zip and screenshots here ⬇️

![infill CD mount 2024](https://github.com/Ultimaker/Cura/assets/105819713/a74e634f-5873-4c48-8967-510d65b91cfd)
[Sat Nav mount v2.zip](https://github.com/Ultimaker/Cura/files/14627175/Sat.Nav.mount.v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You have "Infill Support" enabled.  De-select it.

Infill Support creates structure inside a model like "Support" does on the outside of a model.  In this case, your infill only needs to be large enough to support the "roof" of your model.  Turning the setting off makes the infill a normal situation where it will fill the inside of the model.

I'll remove the bug label and close this as it is a setting issue.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b19d3ec2-3e23-4b3b-b8d3-6ef8fa5ba628)
