### ISSUE TITLE
Cura Slicer 5.6

### ISSUE THREAD

**Issue by AaronBielik** [Ultimaker/Cura#18643]
### Cura Version

5.6.0

### Operating System

MacOS 10.15

### Printer

Ender 3 V3 SE

### Reproduction steps

I downloaded Cura version 5.6 and then do the installation process.

### Actual results

Then I go to open Cura but it “jumps” up and down once or twice and then does not open.

### Expected results

What should have happened is it should have opened up letting me to use the Slicer.

### Add your .zip and screenshots here ⬇️

https://github.com/Ultimaker/Cura/assets/163752494/1b184a59-200e-4d52-8f21-e84679a474f7

**Comment by nallath** [comment]
Can you try if this still happens with the 5.7 beta and post the log files?
