### ISSUE TITLE
After Mac blanks the screen it doesn't refresh when I come back

### ISSUE THREAD

**Issue by royfusa** [Ultimaker/Cura#1864]
My Mac screen blanks after 30 minutes. When I come back my Cura window no longer updates. I'm running Cura 2.5 on MacOS 10.12.5.

**Comment by Ghostkeeper** [comment]
This issue was just rejected by our project manager for being inactive for 3 months.

**Comment by royfusa** [comment]
Thank you! Very helpful. 

Roy
