### ISSUE TITLE
Towel Hook slicing failed

### ISSUE THREAD

**Issue by mrlinux1** [Ultimaker/Cura#18645]
### Cura Version

5.6.0

### Operating System

Linux Mint 

### Printer

Artillery Sidewinder X3

### Name abnormal settings

Support Tree

### Describe model location

Slice worked 90 degfees rotated

### Describe your model

Towel hook

### Add your .zip here ⬇️

[ASX3_towel_holder.zip](https://github.com/Ultimaker/Cura/files/14628120/ASX3_towel_holder.zip)

Rotating 90 degrees around y axis then it works.

**Comment by HellAholic** [comment]
Give the 5.7 beta a try. Issue has been resolved there.
![image](https://github.com/Ultimaker/Cura/assets/28710690/43b2f2e9-b82d-4fc9-895a-cc9647b7edfb)

Thanks for the report!
Cheers
