### ISSUE TITLE
Support roof not building correctly in some areas

### ISSUE THREAD

**Issue by carhifitrier** [Ultimaker/Cura#18657]
### Cura Version

5.7.0 Beta

### Operating System

W11

### Printer

Tronxy X5SA (Pro, H2 Extruder)

### Reproduction steps

Slice the Model with tree supports and my settings

### Actual results

Model gets sliced, but the supported square areas do not get correct density amd/or shape as intended.

### Expected results

Slice with correct support roof for these areas too

### Add your .zip and screenshots here ⬇️

![cura 5 7 0 roof](https://github.com/Ultimaker/Cura/assets/42651956/5fdd8a19-f1c4-4cfb-9102-a50e076ca4c7)
[cura_roof.zip](https://github.com/Ultimaker/Cura/files/14637868/cura_roof.zip)

**Comment by casperlamboo** [comment]
hi @carhifitrier,

Thanks for reporting the issue back to us. Raising issues like this in a beta period is helping us improve our product, and making it more stable before the actual release.

As @ThomasRahm mentioned you exported the project, rather then creating a cura project. Saving projects like this looses all cura related setting data. If I try to open your model on a "Trony X5SA" printer and slice the model with tree support the gcode looks fine.
<img width="1680" alt="Screenshot 2024-03-19 at 17 16 42" src="https://github.com/Ultimaker/Cura/assets/6638028/c7566da4-e9cc-4a95-af9e-df02d7a26946">
You can save a cura project file via the file->save as dialog, or press ctrl+s
<img width="216" alt="Screenshot 2024-03-19 at 17 18 11" src="https://github.com/Ultimaker/Cura/assets/6638028/e57ec30f-b683-476f-9391-af3f925836d7">
