### ISSUE TITLE
Voron with more than one extruder / toolhead

### ISSUE THREAD

**Issue by walterwissmann** [Ultimaker/Cura#18652]
### Cura Version

5.6 and higher

### Operating System

Linux Appimage

### Printer

Voron 2.4r2

### Reproduction steps

- open machine settings
- Drop down menue 'Number of Extruders'

There i can not switch to more than 1 extruder.

The same at 'add Printer' and there 'machine settings'.
I can not select more than 1 extruder.

See pictures.

BR
Walter

### Actual results

- not more than 1 extruder / toolhead

### Expected results

- needed up to 6 toolheads

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/42293697/6fc0d6e6-8963-46df-b64f-c013cc761da2)

![image](https://github.com/Ultimaker/Cura/assets/42293697/649ed1f4-fec1-49d0-9d54-b1a1c47710b9)

**Comment by GregValiant** [comment]
Thanks for the report.
Non-UltiMaker printer definitions are created by members of the community, or by the manufacturer.  UM cannot keep track of al the different printers on the planet.
You can try going back to Voron and see if they have an updated definition for a multi-extruder version of the printer.
If you customized the machine and added the extruder yourself you will have to go in and edit the definition file that you used and add an extruder file.  You could try adding a "Custom FFF" printer and configure that the way you need it.

I'll remove the bug label and close this as it is not a problem with Cura.  I hope you understand.
