### ISSUE TITLE
Ultimaker Materials speed settings Cura 5.6.0 

### ISSUE THREAD

**Issue by GeTurps** [Ultimaker/Cura#18665]
### Cura Version

5.6.0

### Operating System

Win 11

### Printer

Ultimaker S5

### Reproduction steps

When selecting any of the Ultimaker (colour) materials it changes all the speed settings to too fast.
Image on left is Cura 5.1.0 the image on the right right is 5.6.0

![cura speeds](https://github.com/Ultimaker/Cura/assets/164042657/84a086bb-1764-467c-a60a-9b2676e9e141)

### Actual results

Speeds are too quick.

### Expected results

Expect settings be same as cura version 5.1.0

### Add your .zip and screenshots here ⬇️

![cura speeds](https://github.com/Ultimaker/Cura/assets/164042657/7a8fef55-bc2a-442a-a5a0-2a2dbf589cc6)

**Comment by nallath** [comment]
That is entirely intentional. We've pretty recently added a new feature called "gradual flow", which allows for much higher speeds while retaining the same quality levels.
