### ISSUE TITLE
Slicing "Failed with an Unexpected Error"

### ISSUE THREAD

**Issue by BrainSlugs83** [Ultimaker/Cura#18661]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

CR-10

### Reproduction steps

I tried to slice a file, and it gives me an error message telling me that it failed.  Didn't say why or how it failed, just that it "failed".  And offered to take me to GitHub to log a bug. 🤷‍♂️

I have been using Cura for years, with Printers I've built myself even, and in all that time I've never seen it "Fail" to slice a model. -- Sure, I've generated bad settings or whatever that caused a model to not be sliced well... but I've never seen it outright "Fail".

How can I fix this?

### Actual results

It gave me an error message that said it "Failed", with no GCODE, preview, or reason.

### Expected results

At least try to slice it; you can give me a warning if you really need to -- but I'm going to check the preview and make sure what I'm printing looks good before I export it to the SD card...

### Add your .zip and screenshots here ⬇️
- [Project File](https://drive.google.com/file/d/1dS_Xm08-x41R0novl60Qc3ybfn0e51dS/view?usp=sharing)
- [Log File](https://drive.google.com/file/d/1PQlb3dqVdDPEYsdmbDNoqZwozrd96cxc/view?usp=sharing)

![image](https://github.com/Ultimaker/Cura/assets/5217366/614f6948-af11-48f2-a7b7-9135cb2b141b)

**Comment by GregValiant** [comment]
Thanks for the report.
This crashed for me in 5.6.0 but it sliced with no problem in 5.7beta.  Try installing 5.7b and see if this problem has been fixed.
