### ISSUE TITLE
Fractional support calculations can create additional support walls directly below overhang.

### ISSUE THREAD

**Issue by ThomasRahm** [Ultimaker/Cura#18678]
### Cura Version

5.7.0-beta.1

### Operating System

Windows 10

### Printer

Ultimaker 2+

### Reproduction steps

Set support wall line count to 1 and slice. (If in a profile without support horizontal expansion, set it something large enough (>2mm should be very obvious) )

### Actual results

![grafik](https://github.com/Ultimaker/Cura/assets/67757218/a981486a-5ff2-449d-b7ef-6200fc1ab033)

### Expected results

Correct amount of wall lines.

### Add your .zip and screenshots here ⬇️

[TestCradleRemvoePinBugReport.zip](https://github.com/Ultimaker/Cura/files/14686923/TestCradleRemvoePinBugReport.zip)
I encountered this while debugging something else. I do not need help slicing this file correctly! 
Cause lies in SupportLayer::fillInfillParts as the fractional support calculation does not consider horizontal expansion.

**Comment by GregValiant** [comment]
Thanks for the report.
This is a settings issue.  Per your request I won't explain.
I'll go ahead and remove the bug label and close this.  I hope you understand.

This is the top layer of the support structure in 5.7beta when the settings are configured correctly for this model.
![image](https://github.com/Ultimaker/Cura/assets/64202104/32d0cc74-7dde-414c-aa5e-729758fc4bc1)
