### ISSUE TITLE
.curaprofile bad fileformat

### ISSUE THREAD

**Issue by TheTesla** [Ultimaker/Cura#18673]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender 3s1

### Reproduction steps

1. Create printprofile
2. export printprofile
3. open saved .curaprofile in plain text editor

### Actual results

A .ini like .curaprofile with mixed plaintext and binary content is created.

### Expected results

The .curaprofile should have plaintext only, like a normal .ini file, the format used for the .inst.cfg files.

### Add your .zip and screenshots here ⬇️

[test.zip](https://github.com/Ultimaker/Cura/files/14667392/test.zip)
![Screenshot 2024-03-20 145332](https://github.com/Ultimaker/Cura/assets/2584345/b4c17be6-8453-4cf2-828c-9094ff3e8dfa)

**Comment by nallath** [comment]
It actually contains multiple files, so it's not just an ".ini" file. We opted for using a simple zipped file format instead. So if you want to check what is in there, open it with a unzip program (or rename the extension to .zip).
