### ISSUE TITLE
adding new printers

### ISSUE THREAD

**Issue by mdouna** [Ultimaker/Cura#18681]
### Is your feature request related to a problem?

no Creality K1 series

### Describe the solution you'd like

please add support to creality K1C printer

### Describe alternatives you've considered

please add support to creality K1C printer

### Affected users and/or printers

please add support to creality K1C printer

**Comment by GregValiant** [comment]
The printer definitions must come from a member of the community or from the manufacturer.  Ultimaker has no way to write definition files for some other companies hardware.  See #17531
