### ISSUE TITLE
Slicing failed with an unexpected error when Support is on and Support Type is Tree

### ISSUE THREAD

**Issue by The43rdOrange** [Ultimaker/Cura#18688]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Ultimaker 2 Extended +

### Reproduction steps

1. Import STL files that don't need supports and arrange in a way that supports won't be needed
2. Turn on supports and then set support type to tree
3. Slice model 

### Actual results

An error is shown. 'Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.'

### Expected results

Model should be sliced successfully

A valid work around is 
4. Turn off supports or set support type to normal
5. Slice model -> model is successfully sliced 

[ControllerExtensionCount2.zip](https://github.com/Ultimaker/Cura/files/14720459/ControllerExtensionCount2.zip)

### Add your .zip and screenshots here ⬇️

With Support On and Support type as tree
![image](https://github.com/Ultimaker/Cura/assets/116906513/4e977288-aa3c-4d74-891f-76041e6a5168)

With support On and Support type as normal 
![image](https://github.com/Ultimaker/Cura/assets/116906513/475d4029-3fb0-4865-83c2-d0e9ef3d17d4)

With support off
![image](https://github.com/Ultimaker/Cura/assets/116906513/ead37284-bc0f-43e6-9971-3c511d7ef401)

Cura file
[ControllerExtensionCount2.zip](https://github.com/Ultimaker/Cura/files/14720476/ControllerExtensionCount2.zip)

**Comment by HellAholic** [comment]
Hey @The43rdOrange , 
Thanks for the report!
We resolved several issues resulting in Fail slice attempts, fixes are currently available in the 5.7 Beta build. You can check it out there. 5.7 Stable will soon follow :) 
![image](https://github.com/Ultimaker/Cura/assets/28710690/e47a6bd1-483b-4746-90b3-07a1c5660774)

Cheers!
