### ISSUE TITLE
Slicing failed after resize

### ISSUE THREAD

**Issue by DJToke1** [Ultimaker/Cura#18696]
### Cura Version

5.6.0

### Operating System

Mac OS Sonoma

### Printer

Ender 3

### Describe model location

center

### Describe your model

print in place dragon

### Add your .zip here ⬇️

[Generic_Silk_PLA,55_Cinderwing3D_CrystalDragon_0,0_bug.3mf.zip](https://github.com/Ultimaker/Cura/files/14726448/Generic_Silk_PLA.55_Cinderwing3D_CrystalDragon_0.0_bug.3mf.zip)

**Comment by saumyaj3** [comment]
Hey @DJToke1! Have you tried it on our new cura version 5.7.0? We have solved a bunch of slicing error in the latest version. 
I see I can slice the model. however if it still doesn't slice for you. Can you mention if any plugins you're using Cura?
