### ISSUE TITLE
layer bar says 11 layers, but there is only 1

### ISSUE THREAD

**Issue by luisonoff** [Ultimaker/Cura#187]
On cura 15.06.2, layer view, this model (https://drive.google.com/file/d/0BwXWVri7t3tAWF9uT0hXLU1MN3c/view).

Layer bars says and lets you move 11 layers, but all of them are empty except first.
Expected behaviour should be only 1 layer shown, since model is 0.3mm thick and first layer is 0.3mm heigth.

**Comment by nallath** [comment]
There have been changes in how the layer view works. I believe this should be fixed for the next version.
