### ISSUE TITLE
échec du découpage 

### ISSUE THREAD

**Issue by domraph** [Ultimaker/Cura#18707]
### Cura Version

cura 5.7 beta 

### Operating System

Windows 11

### Printer

Neptune 4 pro 

### Name abnormal settings

0

### Describe your model

message de erreur  bug au découpage 

### Add your .zip here ⬇️

depuis que j'ai installer la nouvel mise ajour de cura 5.7 je ne peu plus découper le fichier stl

**Comment by HellAholic** [comment]
Hey @domraph,
Could you check which plugins you have installed and try to remove them for the 5.7 Beta?
See if that resolve your issue and let me know.
