### ISSUE TITLE
Tree support fails slicing

### ISSUE THREAD

**Issue by V-Roger** [Ultimaker/Cura#18718]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Creality CR-10

### Name abnormal settings

Tree support / build-plate only causes the crash

### Describe model location

no

### Describe your model

Basic quarter-sphere shell

### Add your .zip here ⬇️

[cura_crash_model.zip](https://github.com/Ultimaker/Cura/files/14740415/cura_crash_model.zip)

**Comment by HellAholic** [comment]
Hey @V-Roger,
Could you check and see if you're still getting a crash in the 5.7 Beta? We've made quite a few improvements and significantly reduced the number of slice fails.

Cheers!

**Comment by V-Roger** [comment]
Sure thing, I'll download it right away.

**Comment by V-Roger** [comment]
That's a big yes from me!
Works as expected in 5.7beta, well done :)

![image](https://github.com/Ultimaker/Cura/assets/6457990/bae85343-fd63-4559-8d6a-39dd3e8cd4b9)
