### ISSUE TITLE
O fatiamento falhou com um erro não esperado. Por favor considere relatar um bug em nosso issue tracker.

### ISSUE THREAD

**Issue by 3DMMR** [Ultimaker/Cura#18714]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

Elego Neptune 4 MAX

### Name abnormal settings

Suporte arvore

### Describe model location

Não

### Describe your model

Sim corta normalmente

### Add your .zip here ⬇️

O problema diagnosticado foi na Aba suporte / Estrutura do suporte / Árvore  
![ERRO CURA 1](https://github.com/Ultimaker/Cura/assets/134332857/4d814fd1-2df8-4e77-a329-7b57f509a1ae)
![ERRO CURA 2](https://github.com/Ultimaker/Cura/assets/134332857/4ed36420-fe59-40c8-bbd8-3b0c6d12337b)

**Comment by GregValiant** [comment]
Thanks for the report.
Try the new 5.7beta version.  It seems that many of these "won't slice" bugs were addressed in the new version.

I'll mark this as a duplicate.

**Comment by 3DMMR** [comment]
Problema resolvido na versão 5.7 beta.
Obrigado!
