### ISSUE TITLE
lids won't slice until I use ctrl + R

### ISSUE THREAD

**Issue by KamiKage9** [Ultimaker/Cura#18723]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ultimaker S5

### Describe your model

Its watertight and it slices after using the auto arrange function and after rotating/moving it manually, but won't slice when it first loads in

### Add your .zip here ⬇️

[Part Studio 1 - wtr and others.zip](https://github.com/Ultimaker/Cura/files/14748796/Part.Studio.1.-.wtr.and.others.zip)

**Comment by HellAholic** [comment]
Hey @KamiKage9 ,
We addressed a significant number of slicing fails in the 5.7 beta, could you give that one a try? Hopefully it resolves your issue.
Let me know if that helps.

Cheers!
