### ISSUE TITLE
Randomly fails to slice on one computer, regardless of settings, model, or position of model

### ISSUE THREAD

**Issue by arakinas** [Ultimaker/Cura#18729]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Custom: Creality Ender 3 S1

### Name abnormal settings

This will randomly slice or fail, regardless of the project, regardless of the settings

### Describe model location

Mostly centered, but the location doesn't matter. I can have it way off to one side or another and it still happens.

### Describe your model

Parts from https://www.printables.com/model/3407-articulating-raspberry-pi-camera-mount-for-prusa-m/files

### Add your .zip here ⬇️

[CE3S1_RasPi Camera V3 Module back.zip](https://github.com/Ultimaker/Cura/files/147
[CE3S1_RasPi Camera V3 Module back.zip](https://github.com/Ultimaker/Cura/files/14757297/CE3S1_RasPi.Camera.V3.Module.back.zip)
57287/CE3S1_RasPi.Camera.V3.Module.back.zip)
(https://github.com/Ultimaker/Cura/files/14757209/CE3S1_RasPi.Camera.V3.Module.back.zip)
I can click the slice button again and it will work about a quarter of the time without changing anything. This happens on multiple models, on this computer only. I have a second system with Windows 10 where this has never happened. This computer is a recently installed/upgraded 11 but it was happening before the upgrade as well. It had a fresh install of Windows 10 about two months ago, and upgraded to 11 a few days ago. 

Regardless of model, slicing randomly fails.

**Comment by GregValiant** [comment]
Thanks for the report.
There were problems with Cura under Windows 11.  Try installing [Cura 5.7beta](https://github.com/Ultimaker/Cura/releases) and see if they have been resolved for you.

**Comment by arakinas** [comment]
Installed this morning. Sliced appropriately 10/10 times. Thanks!
