### ISSUE TITLE
Unexpected error causes cura engine to crash. can slice other parts of this model with no issue

### ISSUE THREAD

**Issue by bthomas878** [Ultimaker/Cura#18728]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

Ender 3 Pro

### Describe your model

I have not sliced this model before but have sliced other parts as it is a multipart model according to mesh fix the model has no problems and is watertight

### Add your .zip here ⬇️

[CE3PRO_Dice_tower_Small_Tower_Middle_Plain_v1.0.zip](https://github.com/Ultimaker/Cura/files/14756924/CE3PRO_Dice_tower_Small_Tower_Middle_Plain_v1.0.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Many of the slicing errors of Cura 5.6 have been addressed in [Cura 5.7beta](https://github.com/Ultimaker/Cura/releases).  Try installing it and see if the problem goes away.
This failed for me in 5.6 but sliced in 5.7b.
![image](https://github.com/Ultimaker/Cura/assets/64202104/aaa36bdb-110d-40ac-84dc-0a97f4b09a69)
