### ISSUE TITLE
I CANT PUT MULTIPLE STLS IN ONE FILE TO PRINT ALL AT ONCE

### ISSUE THREAD

**Issue by Lintypine** [Ultimaker/Cura#18726]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

Elegoo neptune 3 plus

### Reproduction steps

tried to drag n drop files and then when that failed clicked the file button and couldn't put them in

### Actual results

nothing

### Expected results

have multiple files in one

### Add your .zip and screenshots here ⬇️

[hidden blade (2023 remix) READ DESCRIPTION TUTORIAL POSTED - 5717722.zip](https://github.com/Ultimaker/Cura/files/14753354/hidden.blade.2023.remix.READ.DESCRIPTION.TUTORIAL.POSTED.-.5717722.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I've never had this problem and it wasn't a problem with your files.  Both dragging them in and opening multiple at once worked for me (as it always has).
This is in 5.5.0 (Windows 10) as I don't have 5.4 installed.
![image](https://github.com/Ultimaker/Cura/assets/64202104/cb923d66-d87d-4507-8cc8-7349c69d5ded)

I'll leave this open.  You will want to install [5.7beta](https://github.com/Ultimaker/Cura/releases) and see if it is still an issue.  Several slicing problems and some incompatibility with Win11 have been addressed in 5.7.  Let us know if that works for you.

**Comment by Lintypine** [comment]
how do i install 5.7beta?

**Comment by Lintypine** [comment]
nvm i didnt scroll all the way down

**Comment by Lintypine** [comment]
im so stupid i wasnt doing it right but thank you for alerting me to a newer better version of cura
