### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Guehan** [Ultimaker/Cura#18720]
### Cura Version

5.4.0

### Operating System

windows

### Printer

ender 3 

### Describe your model

non

### Add your .zip here ⬇️

[support de casque et de manette xbox mercedes - 5189666.zip](https://github.com/Ultimaker/Cura/files/14747772/support.de.casque.et.de.manette.xbox.mercedes.-.5189666.zip)

**Comment by rburema** [comment]
The attached file contains an .stl -- we can't really test this if it's just an stl without any instructions with which settings the crash(?) happens. (Is it a crash? you just say 'bug'...)

It seems to slice just fine with the default settings (with or without support) of an Ender 3 in 5.4, 5.6 and the 5.7-beta though.

In order make a project file, please select 'Save Project ...' from the file menu.

----

It (still) _could_ be one of the slicing-crashes we solved in the [5.7.0-beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1) though, please try again with that version if it was a slicing crash. We solved a significant amount of slicing crashes!

(The final version of 5.7.0 will be out in a couple of weeks.)
