### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by NobbyLA** [Ultimaker/Cura#18727]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycube Viper

### Name abnormal settings

No

### Describe model location

No

### Describe your model

No

### Add your .zip here ⬇️

[blinksync2mount-europe-v2.zip](https://github.com/Ultimaker/Cura/files/14754198/blinksync2mount-europe-v2.zip)
[blinksync2mount-europe-v2.zip](https://github.com/Ultimaker/Cura/files/14754248/blinksync2mount-europe-v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Several problems between Cura and Windows 11 were addressed for [Cura 5.7](https://github.com/Ultimaker/Cura/releases) and the beta is available.  Install it and see if your problem has been fixed.  Let us know how you make out.
