### ISSUE TITLE
Successful imported profile not showing up

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#1873]
Ultimaker 2+
Windows 10
Cura 2.6 Beta

When I try and import a profile it says "Successfully imported profile profile_name" but it does not show in the list.

Spent a little while stuffing around and found changing 
`[metadata]
quality_type = draft`
to
`[metadata]
quality_type = fast`

Allowed it to be imported so I'm guess something there is some issue importing draft quality types or under a UM2+ machine you can't import a draft type :/ if you can't import a draft type for a UM2+ maybe it should not say it was Successfully imported but give a warning saying its not supported.

**Comment by fieldOfView** [comment]
Please post the profile you are trying to import somewhere, so we can have a look.

**Comment by ChrisRiddell** [comment]
[Draft.zip](https://github.com/Ultimaker/Cura/files/1024853/Draft.zip)

**Comment by nallath** [comment]
Hmm. I wonder how you managed to export a "quality" profile. It should only allow for "quality_changes" to be exported. Importing is designed to work for quality_changes, but it seems to not fail properly if you use it on something else.

**Comment by ChrisRiddell** [comment]
@nallath This profile was sent to me by a friend so not sure if he exported it or made it by hand in an editor but changing the type to `type: quality_changes` made no difference still does not show if imported only works if i change the quality_type to fast.

I had a look over some of the profile's in the github and there is ones with a draft quality_type.

**Comment by awhiemstra** [comment]
So I just had a look at the profiles for the UM2+. It turns out that we have some profiles that specify their type as "draft" and some that specify it as "fast". Since the exported material came from a machine that does not specify machine-specific profiles, it was based off the global "Draft" profile.

On import, we do set the right machine and material as far as I know, but we assume the quality type to be correct. Since we now have non-matching quality types, the profile would never show up since there is no "draft" type for PLA 0.4 for example.

**Comment by Ghostkeeper** [comment]
We just added a warning message to be shown when this happens.

**Comment by noderat** [comment]
Looks like I'm running into a similar issue, but I don't seem to have the same setting in my profile. The profile was imported from GCode using Cura 15.04.6, then exported and does not appear in Cura 2.6 beta. I've included the gcode, exported profile and cura.log in the below zip.

[TempTowerCuraProfile.zip](https://github.com/Ultimaker/Cura/files/1036588/TempTowerCuraProfile.zip)

**Comment by Ghostkeeper** [comment]
The warning message wasn't added on time for the 2.6 beta.
