### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by JSCoobs** [Ultimaker/Cura#18739]
### Cura Version

5.6

### Operating System

mac senoma 14.4

### Printer

jgaurora A-8

### Reproduction steps

crashed in the middle of printing

### Actual results

could do nothing

### Expected results

would like to pickup where it stopped 

### Add your .zip and screenshots here ⬇️

none

**Comment by rburema** [comment]
I'm sorry, but there isn't nearly enough information for us to reproduce this, or even guess at what might be wrong.

What model where you slicing? With which settings? Do the logs say anything? Did Cura crash or did the printer?
