### ISSUE TITLE
Slicing failed sherman tank but shrunk down

### ISSUE THREAD

**Issue by JoelStolarski** [Ultimaker/Cura#18738]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

ender3v2 0.2 nozzle super quality

### Name abnormal settings

didn't try

### Describe model location

middle

### Describe your model

sherman tank with mesh problems

### Add your .zip here ⬇️

[CE3E3V2_jmbo_sherman_tracks_fixed_project_3mf.zip](https://github.com/Ultimaker/Cura/files/14765669/CE3E3V2_jmbo_sherman_tracks_fixed_project_3mf.zip)

**Comment by rburema** [comment]
I can confirm that this is a slicing crash in 5.6 for me. The good news is, that this seems to be one of the many slicing-errors we've managed to solve in 5.7.0(-beta).

Can you try the [5.7.0-beta here](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)?
