### ISSUE TITLE
Unexpected error slicing

### ISSUE THREAD

**Issue by strumdaddy** [Ultimaker/Cura#18758]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender 3 KE

### Name abnormal settings

None, I selected and deselected Adaptive Layers and Fuzzy skin

### Describe model location

not tried

### Describe your model

It is a percussion frog, It has always sliced until now, and I checked : the mesh is good

### Add your .zip here ⬇️

[percussion_frog.zip](https://github.com/Ultimaker/Cura/files/14799291/percussion_frog.zip)
[percussion_frog.zip](https://github.com/Ultimaker/Cura/files/14799311/percussion_frog.zip)

**Comment by HellAholic** [comment]
Can you try [the 5.7.0-beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)? We've fixed a lot of the slicing errors we saw in the 5.x-series in the upcoming 5.7.0 version.
