### ISSUE TITLE
[2.6.0] Supports been generated in mid air

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#1875]
Windows 10
Ultimaker 2+
Cura 2.6 Beta

with supports enabled there is some sections where the supports are been placed that will make them floating 3+ layers above the bottom even with the support bottom layer setting as 0.1mm

(happens on both normal 0.15mm and fine 0.1mm profiles)

File from https://www.thingiverse.com/thing:2187088

![capture](https://cloud.githubusercontent.com/assets/2055566/26395676/fcc1a61c-40af-11e7-9e25-e0d4eecda45c.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2055566/26395675/fcb560d2-40af-11e7-93b4-02e335de405a.PNG)

**Comment by Ghostkeeper** [comment]
> support bottom layer setting as 0.1mm

You mean support bottom distance?

What I see in your screenshot looks relatively normal. There is one layer of distance between support-top and the model visible on the left-hand side of the first screenshot. Support bottom distance seems to be 0.

**Comment by ChrisRiddell** [comment]
Sorry yes the support bottom distance

Here is a video showing what I mean 
https://www.youtube.com/watch?v=XXNcijpaGrI

**Comment by Ghostkeeper** [comment]
Hmm, perhaps the pieces of support there are too small to print. Could you try setting the support line distance to something very small, just for testing? Like 0.01mm.

You could also try reducing the support X/Y distance, or set Z to override X/Y.

**Comment by ChrisRiddell** [comment]
Changing the support line distance done nothing, But changing  support X/Y distance from 0.7 to 0.4 some what worked.

**Comment by Ghostkeeper** [comment]
Sorry, I meant Support Line Width, not Support Line Distance :(

**Comment by ChrisRiddell** [comment]
Changing Support Line Width to 0.1 still see section of supports been printed in mid air.

**Comment by Ghostkeeper** [comment]
Hmm, well that's strange. So it's probably not that the support is too small to print in that bit then.

Is there a way in which we can reproduce this? It doesn't seem to be happening with the construed examples I'm trying.

**Comment by ChrisRiddell** [comment]
Hmmm not to sure, I'll uninstall cura, delete the folder in the %appdata% then reinstall just in case my install is doing something weird.

**Comment by ChrisRiddell** [comment]
The issue after reinstalling cura seems pretty much fixed only notice one floating support.
![floater](https://user-images.githubusercontent.com/2055566/27912050-97c6460c-629a-11e7-9540-f09d9249105a.PNG)

**Comment by ianpaschal** [comment]
@ChrisRiddell Can you share the model so I can check if this is still reproducing and which setting is causing it?

**Comment by ianpaschal** [comment]
This no longer reproduces in Cura 3.4.1.
