### ISSUE TITLE
sopport interface failing

### ISSUE THREAD

**Issue by jamen023** [Ultimaker/Cura#18765]
### Cura Version

5.6.0

### Operating System

Windows 11 Pro

### Printer

Voron 2.4

### Reproduction steps

When I went into creating support, I selected the option "support interface"
After clicking 'slice', i get an error. 
If I unclick the 'support interface' and then click 'slice', i don't get the error.

### Actual results

![image](https://github.com/Ultimaker/Cura/assets/165447909/b1528cb0-269d-431b-b11f-c59be6bcaae6)

### Expected results

I am gathering CURA should be able to slice the part I am wanting to print if I select the option 'support interface'

### Add your .zip and screenshots here ⬇️

[bracket.zip](https://github.com/Ultimaker/Cura/files/14810135/bracket.zip)

**Comment by HellAholic** [comment]
Can you try [the 5.7.0-beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)? We've fixed a lot of the slicing errors we saw in the 5.x-series in the upcoming 5.7.0 version.

![image](https://github.com/Ultimaker/Cura/assets/28710690/248d9cf7-c8a1-4223-9b30-47c7ec9b4759)
