### ISSUE TITLE
Are you guys adding Elegoo's Neptune 4 / Neptune 4 Pro anytime soon?

### ISSUE THREAD

**Issue by geraldopp** [Ultimaker/Cura#18762]
### Is your feature request related to a problem?

There are multiple Neptune 4 profiles that one can use scattered throughout the internet, but I am not still getting good results. Cura used to offer good support in terms of Elegoo's printers, I mean, it is a fairly recognized brand with a wide user base. I don't understand why Cura no longer supports Elegoo's FDM printers. Neptune 4 is almost 1 year old now, but still no profiles for this printer.
I love Cura and I want to keep using it for my Neptune printers, but sadly there is no way for me.

### Describe the solution you'd like

Elegoo's Neptune 4 / 4 Pro printers profile added to Cura.

### Describe alternatives you've considered

Elegoo's Neptune 4 / 4 Pro printers profile added to Cura.

### Affected users and/or printers

Elegoo's Neptune 4 / 4 Pro printers.

### Additional information & file uploads

None.

**Comment by HellAholic** [comment]
@geraldopp Have you tried the 5.7 Beta? This will be included in 5.7 Stable.
![image](https://github.com/Ultimaker/Cura/assets/28710690/0ad6b57b-0999-4c96-9e0a-8a015a8722a3)
Community PR: https://github.com/Ultimaker/Cura/pull/17576

Please note that any 3rd party printer is added by community contributors like the PR marked above.
