### ISSUE TITLE
sliced failed

### ISSUE THREAD

**Issue by UF0000** [Ultimaker/Cura#18763]
### Cura Version

5.6.0

### Operating System

win11

### Printer

elegoo neptune 4 plus

### Name abnormal settings

a

### Describe model location

0

### Describe your model

a

### Add your .zip here ⬇️

a

**Comment by HellAholic** [comment]
Can you try [the 5.7.0-beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)? We've fixed a lot of the slicing errors we saw in the 5.x-series in the upcoming 5.7.0 version.
