### ISSUE TITLE
no slice, will when smaller

### ISSUE THREAD

**Issue by SecretCos** [Ultimaker/Cura#18771]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

A custom one for the ender-3 neo

### Name abnormal settings

Start code:      G28 ;Home G92 E0 ;Reset extruder G1 Z2.0 F3000 ;Move Z Axis up G1 X10.1 Y20 Z0.28 F5000.0 ;Move to start position G1 X10.1 Y200.0 Z0.28 F1500.0 E15 ;Draw the first line G1 X10.4 Y200.0 Z0.28 F5000.0 ;Move to side a little G1 X10.4 Y20 Z0.28 F1500.0 E30 ;Draw the second line G92 E0 ;Reset extruder G1 Z2.0 F3000 ;Move Z Axis up         End code:     G91 ;Relative positionning G1 E-2 F2700 ;Retract a bit G1 E-2 Z0.2 F2400 ;Retract and raise Z G1 X5 Y5 F3000 ;Wipe out G1 Z10 ;Raise Z more G90 ;Absolute positionning G1 X0 Y0 ;Present print M106 S0 ;Turn-off fan M104 S0 ;Turn-off hotend M140 S0 ; Turn-off bed M84 X Y E ;Disable all steppers but Z

### Describe model location

center flat upright, no position edits

### Describe your model

at 70 percent scale it works, it says its not water tight 

### Add your .zip here ⬇️

[Rafayel Necklace 1 (1.4.1).zip](https://github.com/Ultimaker/Cura/files/14813996/Rafayel.Necklace.1.1.4.1.zip)

**Comment by HellAholic** [comment]
Can you try [the 5.7.0-beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)? We've fixed a lot of the slicing errors we saw in the 5.x-series in the upcoming 5.7.0 version.
