### ISSUE TITLE
Display Progress On LCD - Hidden fields

### ISSUE THREAD

**Issue by lethuer** [Ultimaker/Cura#18781]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Artillery Genius (NOT Pro)

### Reproduction steps

"Time Reporting Method" and "Update frequency" becomes only visible if "Time Remaining" is selected.
But also "Percentage" is affected (if selected).
Afterwards you can deactivate "Time remaining" to only display percentage and selected "time reporting method" is considered.
![image](https://github.com/Ultimaker/Cura/assets/67121474/d7957ba3-07e9-44ba-a88b-96ca8e656ce7)

### Actual results

See above

### Expected results

"Time Reporting Method" and "Update frequency" should become visible if "Time Remaining" OR "Percentage" is selected.
It's not only "Time Reporting Method", rather more it is just "Reporting Method".

Might be obsolete because of new add in "DisplayInfoOnLCD" in a future release ?!

### Add your .zip and screenshots here ⬇️

![Display Progress On LCD](https://github.com/Ultimaker/Cura/assets/67121474/9a60c4c4-f538-4b19-bf2d-ad73412f087d)

**Comment by GregValiant** [comment]
"Display Progress on LCD" and "Display Filename and Layer on LCD" have been obsoleted starting with Cura 5.7.
If you have further comments you can add a "Feature Request" to add things like your M118 with the A1 and P0 parameters (which is invalid for some firmware/print server combinations).

I'll go ahead and close this as it will no longer apply.  I hope you understand.
