### ISSUE TITLE
Slicing Issue

### ISSUE THREAD

**Issue by twoinchcrow** [Ultimaker/Cura#18793]
### Cura Version

5.60

### Operating System

Windows

### Printer

Custom printer but its Ender 3 Pro settings

### Describe your model

I have sliced this model before. N/A. No.

### Add your .zip here ⬇️

N/A

**Comment by HellAholic** [comment]
Hey @twoinchcrow ,
Try the [latest release 5.7](https://github.com/Ultimaker/Cura/releases/tag/5.7.0), a lot of slicing issues have been resolved there.
Without a project file it is impossible to help you further with this.
