### ISSUE TITLE
Echec de decoupage

### ISSUE THREAD

**Issue by Ben823d** [Ultimaker/Cura#18800]
### Cura Version

5.6.0

### Operating System

windows

### Printer

Elegoo neptune 4max

### Name abnormal settings

non

### Describe model location

dans tous les sens, ca plante... 

### Describe your model

non, je n'ai pas réussi a le découper

### Add your .zip here ⬇️

[CFFFP_calandre2-triangle.zip](https://github.com/Ultimaker/Cura/files/14844341/CFFFP_calandre2-triangle.zip)

**Comment by HellAholic** [comment]
Hey @Ben823d ,
Issue has been resolved in the [latest release 5.7](https://github.com/Ultimaker/Cura/releases/tag/5.7.0)
![image](https://github.com/Ultimaker/Cura/assets/28710690/636876bb-73dc-4a38-b4a1-fe72978bacb2)
Give that build a try, if you're still experiencing the same issue, feel free to re-open.
