### ISSUE TITLE
Cura 2.6 Beta - Changed project name is not saved

### ISSUE THREAD

**Issue by jaybaugh** [Ultimaker/Cura#1880]
Using Cura v2.6 Beta

To replicate:
Load a model
Save to file. Note the filename.
Click cancel.
Change the project name by clicking the little pencil next to the project name. (Bottom right of main window.)
Click "Save to file" button.
Note that filename has not been updated.

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this in Cura 2.5 on Windows 8.1. Perhaps this is a regression, or something that happens only on Linux? (I saw on one of your other bug reports that you were using Linux.)

**Comment by jaybaugh** [comment]
After clearing my settings and configuration and using the latest 2.6 Beta, I was not able to replicate this either. Closing this issue.

**Comment by Ghostkeeper** [comment]
Hmm, curious what could've cause this then. But oh well, let's hope the bug stays down :)
