### ISSUE TITLE
切片失敗

### ISSUE THREAD

**Issue by h830729UMR** [Ultimaker/Cura#18817]
### Cura Version

5.6

### Operating System

windows 11

### Printer

creative ender3 s1

### Reproduction steps

設定樹狀支撐時 顯示切片失敗
換成一般支撐時就切片成功了

### Actual results

設定樹狀支撐時 顯示切片失敗
換成一般支撐時就切片成功了

### Expected results

我想要使用樹狀支撐並切片成功

### Add your .zip and screenshots here ⬇️

![未命名](https://github.com/Ultimaker/Cura/assets/106732577/daef24d1-375c-4362-97a7-9f79f4a2097c)

**Comment by GregValiant** [comment]
Thank you for the report.
Many of the problems that occurred in 5.5 nd 5.6 seem to have been resolved in 5.7.0.  Please install it and see if the problem persists.

I'll go ahead and mark this as a duplicate and go ahead and close it as the Cura team is well aware of the problem.  I hope you understand.
