### ISSUE TITLE
failed to slice print

### ISSUE THREAD

**Issue by seriousfreedom** [Ultimaker/Cura#18816]
### Cura Version

5.7.0

### Operating System

MX Linux

### Printer

ender 3 pro

### Name abnormal settings

NONE

### Describe model location

center of bed

### Describe your model

kubota rops mount

### Add your .zip here ⬇️

[CE3PRO_CE3PRO_Kubota_ROPS_bracket_A&B.zip](https://github.com/Ultimaker/Cura/files/14865810/CE3PRO_CE3PRO_Kubota_ROPS_bracket_A.B.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That doesn't appear to be a proper project file.  Use the "File | Save Project" command then zip and post the 3mf file.
