### ISSUE TITLE
Error en el corte

### ISSUE THREAD

**Issue by ethanallen25** [Ultimaker/Cura#18819]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

Ender 3 Pro/V2

### Name abnormal settings

Ninguna

### Describe model location

No, directamente no segmenta mis piezas porque informa de un error de laminado (Error de corte)

### Describe your model

Son todos cuerpos gemoétricos

### Add your .zip here ⬇️

![error cura](https://github.com/Ultimaker/Cura/assets/137233368/d1ddcf0c-6ab0-451d-afb8-41826caad91e)

**Comment by GregValiant** [comment]
Thanks for the report.
Have you checked all those models for errors?  It only takes one bad model to confuse the slicer.
Without a project file and Cura.log file we have nothing to look at to investigate.
