### ISSUE TITLE
Cura 2.6 Beta - Default Qualities are Inconsistent

### ISSUE THREAD

**Issue by tcm0116** [Ultimaker/Cura#1882]
First of all, I really like the fact that Cura 2.6 will include more default quality settings for Custom FDM Printers. However, I've noticed that they are somewhat inconsistent.

For example, Extra Coarse Quality, Coarse Quality, Draft Quality, and Fine all leave the default print speeds intact. However, Extra Fine and Low Quality do not. Specifically, Low Quality increases the Infill Speed to 100, which is way too fast for my printer.

Seeing as the speeds are normally derived from the Print Speed, perhaps it would be a better idea to make speed changes in the default quality profiles be computed values as a function of print_speed rather than hard-coded values. Here is a modified Low Quality config file that follows my recommendation:

[low.inst.cfg.txt](https://github.com/Ultimaker/Cura/files/1027817/low.inst.cfg.txt)

**Comment by Ghostkeeper** [comment]
I'd think that if Low Quality has an infill speed of 100, then at least Draft, Coarse and Extra Coarse should have the same. But I also think that these default quality profiles should work reasonably well for just about any printer, so perhaps we should set the speed to 80 and do that consistently?

Or just do away with this guesswork and only adjust layer height. They were introduced here: https://github.com/Ultimaker/Cura/commit/e0ebe960acc9e0d8d9eea9448d3df82909c8ff03
CURA-1612 is a bug in our internal tracker that only PLA is visible for Ultimaker 2. It seems to be unrelated (or very far related perhaps).

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.
