### ISSUE TITLE
Slicing a .3mf file I made in fusion 360

### ISSUE THREAD

**Issue by jldavis1969** [Ultimaker/Cura#18836]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Tronxy X5SA

### Name abnormal settings

Tree support causes error upon slicing

### Describe model location

No,model does not slice at 90 degrees or at 10mm off center

### Describe your model

Slices with normal supports on

### Add your .zip here ⬇️

With tree supports (Default settings) turned on it does not slice. but if you goto normal supports (Default settings) it will slice.
[JBL GO2 Case.zip](https://github.com/Ultimaker/Cura/files/14896113/JBL.GO2.Case.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There were a lot of these reports regarding both 5.5 and 5.6.  The bugs were worked on and 5.7.0 seems like it is MUCH improved.  I would suggest you install it and give it a try.
I'll mark this as a duplicate and go ahead and close this as it appears to have been addressed.  Let me know if you feel that is premature.
That little ledge is tough to support so I made some changes.
![image](https://github.com/Ultimaker/Cura/assets/64202104/1679b4e4-e3af-4e00-b3df-46da774a8ba1)
