### ISSUE TITLE
Thingiverse 'Open in Cura' not working with 5.7

### ISSUE THREAD

**Issue by gh13** [Ultimaker/Cura#18832]
### Cura Version

5.7

### Operating System

Windows 10

### Printer

Ender 3 S1 PRO

### Reproduction steps

Cura 5.7.0 is installed on the PC.
Opened Thingiverse in Chrome, selected a model then the files tab.
Clicked the 'Open in Cura' icon. for the STL file

### Actual results

Nothing happens

### Expected results

Model should open Cura 5.7 & load the model

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/27573229/c1ed9abe-b43d-4f58-9bab-a138ead9980a)

**Comment by HellAholic** [comment]
Hey @gh13 ,
The **Open in Cura** works through the Windows Registry association with links from Thingiverse. If you uninstalled other Cura versions (Beta 5.7 as an example) after installing the 5.7 you might have remove those registries. If that is the case, re-installing the 5.7 should fix the issue.
If that is not the case, check if you see some sort of pop up like the image below when you click on Open in Cura button,
![image](https://github.com/Ultimaker/Cura/assets/28710690/07f00d29-f045-4232-a836-ca1af817d5ec)
This pop up might look different depending on your browser but the message is the same. Check if you blocked this somehow or did not allow for it.

**Comment by gh13** [comment]
I had uninstalled the 5.7 beta following installing the release version, which may have done as you said. 
I've ran the 5.7 installer again & the Thingiverse integration is now working. Thanks :-)

**Comment by gh13** [comment]
I had uninstalled the 5.7 beta following installing the release version, which may have done as you said. 
I've ran the 5.7 installer again & the Thingiverse integration is now working. Thanks :-)
