### ISSUE TITLE
slice fail

### ISSUE THREAD

**Issue by hwhitney24** [Ultimaker/Cura#18833]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

creality ender 3 s1

### Reproduction steps

pressed slice

### Actual results

gives error message says report bug

### Expected results

idk

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-04-06 094031](https://github.com/Ultimaker/Cura/assets/57195515/10dd2da2-32a1-45fc-96f5-fc4e78816125)

**Comment by GregValiant** [comment]
Thanks for the report.
There were a lot of slicing bugs reported in 5.5 and 5.6.  Cura 5.7.0 is out and is much better.

I'll mark this as a duplicate and go ahead and close it as the problem seems to be fixed.  I hope you understand.
