### ISSUE TITLE
slice failed with lego lightsaber

### ISSUE THREAD

**Issue by A-Generic-Duck** [Ultimaker/Cura#18838]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

flsun superracer

### Name abnormal settings

tree supports i believe thats all

### Describe model location

tried in lots of different places around the bed

### Describe your model

this model at 102% size

### Add your .zip here ⬇️

[Lightsaber_Vader.zip](https://github.com/Ultimaker/Cura/files/14897137/Lightsaber_Vader.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and a log file there can't be an investigation.
