### ISSUE TITLE
Impossible to slice any STL

### ISSUE THREAD

**Issue by romanopanzano** [Ultimaker/Cura#18842]
### Cura Version

5.7.0

### Operating System

MacOS Big Sur

### Printer

FLsun Super Racer

### Name abnormal settings

everything normal

### Describe model location

classic on the center

### Describe your model

test cube before printing the whole parts

### Add your .zip here ⬇️

[FSR_PolyCube.3mf.zip](https://github.com/Ultimaker/Cura/files/14898355/FSR_PolyCube.3mf.zip)

Impossible to slice any parts, any STL ... is like not functionning at all, I have to downgrade Cura to use it, Now I use Cura 5.0 to slice ...

**Comment by GregValiant** [comment]
I didn't have any trouble on my Windows system.
Use the "Help | Show Configuration Folder" command and zip and post the Cura.log file.  It will often give a clue as to what the problem might be.
