### ISSUE TITLE
Model locations from exported 3MF files don't re-import into the same location on the print bed

### ISSUE THREAD

**Issue by SailorJerry9254** [Ultimaker/Cura#18852]
### Cura Version

5.7.0

### Operating System

Windows 10 Home, v10.0.19045 BUild 19045

### Printer

Mingda Magician X

### Reproduction steps

1. Launch UltimMaker Cura 5.7.0
2. Click File > Open Files > Browse to desired folder > Select STL file with a singular model
3. Center the model on the print bed in Cura
4. Select the model > Click CTL + M > Set number of copies to "1" > Click OK
5. Position the second model on the print bed
6. Click CTL + S > save the 3MF file to desired folder
7. Click CTL + D to clear the print bed
8. Click File > Open Files > Browse to desired folder > Select the recently saved 3MF file with two models on the print bed

### Actual results

Once the 3MF file opens only one of the models is centered on the bed, while the rest are off to the side off of the print bed.  This happens with importing 3MF files eported originally exported from Cura v5.6.0 and v5.7.0.

### Expected results

What should happen is that the models within the 3MF file should retain their location on the print bed, instead of only one model remaining on the print bed.
![models after import](https://github.com/Ultimaker/Cura/assets/166399467/79f473b2-f4be-4f1e-bf28-4e27143b01f0)

### Add your .zip and screenshots here ⬇️

[STL and 3MF.zip](https://github.com/Ultimaker/Cura/files/14905613/STL.and.3MF.zip)

**Comment by HellAholic** [comment]
@SailorJerry9254 importing models will not follow the original position of the models and will try to put them centered on the build plate.
If you would like to retain the position then you would need to open as project.
![image](https://github.com/Ultimaker/Cura/assets/28710690/d3e997da-9aa8-4280-af7a-5e37e496a72a)

We have another option that allows an in between functionality called Universal Cura Project.
You can choose what settings will be saved in that format so if you want to store models with positions then that is your best option. You will still need to Open as UCP and not import model in that as well.

**Comment by HellAholic** [comment]
Side note, you might have checked the Import models as default in your preferences.
If so, go to Preferences > Configure Cura > General > and change from always import models.
Picture below:
![image](https://github.com/Ultimaker/Cura/assets/28710690/96a774f9-33f8-4d8c-b8ac-c0ef961d12b1)

**Comment by SailorJerry9254** [comment]
I tried both of your proposed solutions and they both worked.  Thank you!
