### ISSUE TITLE
slicing failure

### ISSUE THREAD

**Issue by maxw3ll90** [Ultimaker/Cura#18850]
### Cura Version

5.6

### Operating System

10

### Describe your model

n/a

### Add your .zip here ⬇️

[CE3E3V2_8.zip](https://github.com/Ultimaker/Cura/files/14904145/CE3E3V2_8.zip)

**Comment by fieldOfView** [comment]
Have you tried 5.7 instead? It was released last week, and fixes a number of slicing issues.

**Comment by jellespijker** [comment]
@maxw3ll90 thank you for uploading your file with a slicing error. We will investigate what might cause this crash.
Did you try 5.7.0 where we put in a lot of effort to fix frequently occurring crashes.

please let me know if it slices in 5.7.0

On an unrelated note:
I would like to remind you that there are still actual people working on this complex piece of software. It is not AI generated code... yet...
But people who put there blood sweat and tears into it and do their best to provide a decent piece of free software for free, to the community. 
Could you take that into account when you write a bug report?
