### ISSUE TITLE
Cura 2.6 Beta - g-code printer scripts do not save

### ISSUE THREAD

**Issue by notnyt** [Ultimaker/Cura#1885]
I edited my gcode for print completion.  It does not save.

**Comment by fieldOfView** [comment]
Could you check if adding a new printer and changing the settings on that new printer works?
I think your issue is caused by a bug in the version upgrade of the old printer instance.

**Comment by notnyt** [comment]
Adding a new printer to a clean install of 2.6 allows settings to be changed.  Likely a bug related to upgrading as you say.

**Comment by davidedmundson** [comment]
Possibly relevant warning on opening dialog:

15:48:31.128 ?libQt5Qml.so.5?|QQmlEnginePrivate::warning|?libQt5Qml.so.5? file:///tmp/.mount_HL8KKi/usr/bin/resources/qml/Preferences/MachinesPage.qml:120: TypeError: Cannot read property 'onCompleted' of null

**Comment by fieldOfView** [comment]
No, not relevant, but thanks anyway

**Comment by xia0** [comment]
Old printer did not save. Added new printer, saved ok. Re-opened Cura and settings are gone again. OS X.

**Comment by fieldOfView** [comment]
@xia0, could you zip up your entire configuration folder and post a link to it here?
