### ISSUE TITLE
Modify or turn off the last layer of the Spiralize outer contour function.

### ISSUE THREAD

**Issue by Eazao** [Ultimaker/Cura#18872]
### Is your feature request related to a problem?

We recently upgraded Cura to the latest version, Cura 5.7, and turned on "spiralize outer contour" in the settings, but did not turn on "enable ironing". We slice and print the cylindrical model. At the end of the cylindrical model, the nozzle will maintain the final Z value and print another circle, as shown in the figure below. There is no such problem in Cura 4.13.

We use ceramic 3D printers, mainly using Cura to slice ceramic 3D printed vases and other models. We only need to print the bottom and spiral outer wall, and do not need to print the last layer.

The current updated function of "Spiralize outer contour" will cause the printing of the last layer to interfere with the already printed vase model.

### Describe the solution you'd like

In cura, is there a function button or option? We can revert the "Spiralize outer contour" of Cura 5.7 version to the "Spiralize outer contour" of Cura 4.13 version, because in Cura 4.13 version, there is no such problem.

### Describe alternatives you've considered

Fall back to "Spiralize outer contour" in Cura 4.13, because in Cura 4.13, there is no such problem.

### Affected users and/or printers

Most ceramic 3D printers are troubled by this problem.

### Additional information & file uploads

Here are the questions we asked:
https://github.com/Ultimaker/Cura/issues/18860

https://community.ultimaker.com/topic/45389-the-settings-for-the-last-layer-of-spiralize-outer-contour-how-to-cancel-the-last-layer/#comment-332900

**Comment by GregValiant** [comment]
I'll link this request to #18860 and go ahead and close this one as a duplicate request.
