### ISSUE TITLE
slicing failed error

### ISSUE THREAD

**Issue by esupernova** [Ultimaker/Cura#18871]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

1. clicked slice

### Actual results

"Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

### Expected results

The image should be sliced and ready to print.

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-04-10 cura error ](https://github.com/Ultimaker/Cura/assets/166661855/8067d5b5-38df-46c9-a33f-0e689beb287f)
![Screenshot 2024-04-10 cura slicer error message](https://github.com/Ultimaker/Cura/assets/166661855/2423f8f9-5b3e-4d67-a0b3-dc563be32d8f)

**Comment by GregValiant** [comment]
Thanks for the report.
There were a lot of slicing errors in 5.5 and 5.6.  The problem was addressed and many have been fixed in 5.7.0.  I would suggest installing it and giving it a try.

I'll mark this as a duplicate and close it as the team has worked on the problem.  I hope you understand.
