### ISSUE TITLE
Can't slice, somitimes can, Naples model on printables, it has like, littles holes on the model that appears on slicer, but i can't fix them

### ISSUE THREAD

**Issue by Xerooth** [Ultimaker/Cura#18886]
### Cura Version

5.4.0

### Operating System

Win 10

### Printer

E3V2

### Describe model location

Centered, tried also moving slightly from center. Nothing changed

### Describe your model

Sometimes it slice it.. idk why

### Add your .zip here ⬇️

Can't slice, somitimes can, Naples model on printables, it has like, littles holes on the model that appears on slicer, but i can't fix them

**Comment by HellAholic** [comment]
Hey,
Models with disconnected faces and models with issues have the appearance you're describing. Unfortunately we cannot help you in that regard. You can download softwares like 3D builder that repair the models and attempt to fix them.
This is not a cura issue so I'm closing this report.
