### ISSUE TITLE
quest_2_to_quest_3_strap_adapter.stl

### ISSUE THREAD

**Issue by frozentoasty** [Ultimaker/Cura#18880]
### Cura Version

5.6

### Operating System

Windows 11

### Printer

Anycubic Vyper

### Name abnormal settings

normal

### Describe model location

its in the center

### Describe your model

its a meta quest 2 to quest 3 headstrap adapter 

### Add your .zip here ⬇️

![Screenshot 2024-04-11 214644](https://github.com/Ultimaker/Cura/assets/159488851/f4b42b3b-a378-4344-8dda-d57e401fc410)
[AV_quest_2_to_quest_3_strap_adapter.zip](https://github.com/Ultimaker/Cura/files/14950711/AV_quest_2_to_quest_3_strap_adapter.zip)

**Comment by HellAholic** [comment]
@frozentoasty give the 5.7 version a try, there were a few improvements to tree support and slicing performance. I can slice your model in 5.7 without issue.
![image](https://github.com/Ultimaker/Cura/assets/28710690/1069715e-4231-40ce-9f60-3cb2eabddf21)

**Comment by frozentoasty** [comment]
Yes i did the same and it worked. Thank you very much for your answer!

HellAholic ***@***.***> schrieb am Do., 11. Apr. 2024, 23:54:
