### ISSUE TITLE
Non va lo slice

### ISSUE THREAD

**Issue by QUATTRO74po** [Ultimaker/Cura#18899]
### Cura Version

5.4.0

### Operating System

Windows 10 

### Printer

Anycubic Kobra

### Reproduction steps

Ho inserito il modello 3d per fare lo slice, premo il tasto slice e mi dice che non va

### Actual results

Non va lo slice

### Expected results

Dovrebbe fare lo slice

### Add your .zip and screenshots here ⬇️

.

**Comment by HellAholic** [comment]
@QUATTRO74po without a project file we cannot really help you.
Try downloading the latest version of Ultimaker Cura 5.7 and see if that resolves the issue.
