### ISSUE TITLE
Slicing Failed on Print-in-Place Bearing

### ISSUE THREAD

**Issue by okokel** [Ultimaker/Cura#18895]
### Cura Version

5.7.0

### Operating System

Windows 10

### Printer

Ender-3 V2

### Name abnormal settings

Using default Standard Quality settings for 0.4mm nozzle, 0.2mm layer height

### Describe model location

Center of bed

### Describe your model

3d-printable bearing, multiple parts that are very close but do not overlap.  Slices fine in Cura 5.6

### Add your .zip here ⬇️

[Slicing Failure Cura 5.7.zip](https://github.com/Ultimaker/Cura/files/14978956/Slicing.Failure.Cura.5.7.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble on my Win 10 system.
Try right-clicking on the Cura icon on your desktop and select "Run as Administrator".  Let us know if that makes a difference.  

In the meantime I'll mark this as a duplicate.

**Comment by jellespijker** [comment]
Thanks for reporting this, when I try slicing this in our upcoming 5.7.1 release, it slices with out problem. Closing this issue as fixed
![image](https://github.com/Ultimaker/Cura/assets/8535734/868275f0-af97-4b34-b347-2d6808f01381)
