### ISSUE TITLE
ANET A8 PLUS

### ISSUE THREAD

**Issue by NightFoxBrz** [Ultimaker/Cura#18894]
### Cura Version

5.0.4

### Operating System

WINDOWS PROFESSIONAL 11

### Printer

ANET A8 PLUS

### Reproduction steps

No Work online in cura

### Actual results

no conect in port com usb

### Expected results

no conect in usb no detect anet on cura

### Add your .zip and screenshots here ⬇️

no conect in usb port
[Captura de tela 2024-04-14 210234.zip](https://github.com/Ultimaker/Cura/files/14972609/Captura.de.tela.2024-04-14.210234.zip)

**Comment by HellAholic** [comment]
Hey @NightFoxBrz ,
as UltiMaker, we do not have access to 3rd party printers for testing and validating issues.
I would suggest updating to 5.7 Cura and seeing if your printer works there. Otherwise please follow up with the printer support/manufacturer for instructions how to connect the printer.
