### ISSUE TITLE
after clicking on slice button it gets crash

### ISSUE THREAD

**Issue by Govardhan3d** [Ultimaker/Cura#18897]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

Ender 3v2

### Name abnormal settings

default profiles

### Describe model location

center of the buildplate only

### Describe your model

yes

### Add your .zip here ⬇️

[CE3E3V2_Body1.zip](https://github.com/Ultimaker/Cura/files/14980092/CE3E3V2_Body1.zip)

**Comment by Govardhan3d** [comment]
![Desktop Screenshot 2024 04 15 - 19 42 24 59](https://github.com/Ultimaker/Cura/assets/131440401/4f346715-7c5b-4c5d-b67f-ee4d36c12c7f)

**Comment by HellAholic** [comment]
Duplicate report of #18898
