### ISSUE TITLE
Machine Profiles

### ISSUE THREAD

**Issue by Searider** [Ultimaker/Cura#189]
It seams the only way to retrieve settings that are used for a part (Quality, speed, infill, cooling etc...) is to save it in a "Machine" profile. I don't think this is the best way to do this, but if this is the way, please make it easy to clone the current settings when creating a new Machine profile. I will end up with a list of several machine profiles but now I have to start from scratch on configuring each profile. If I could clone a previous profile the, I only have to adjust areas that change.

**Comment by Xisle** [comment]
See Issue #87

**Comment by nallath** [comment]
Closing as its a duplicate
