### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by mihaivla** [Ultimaker/Cura#18905]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

Ideagen3D Sapphire Plus

### Name abnormal settings

I add supports to model. 

### Describe model location

it sliced ater rotating the model.

### Describe your model

yes, but no supports

### Add your .zip here ⬇️

[ISP_ans_bucsa filet +y pipe.zip](https://github.com/Ultimaker/Cura/files/15008713/ISP_ans_bucsa.filet.%2By.pipe.zip)

**Comment by jellespijker** [comment]
Thank you for reporting this. After trying out the 3mf project file in our upcoming release 5.7.1 it slices correctly. Closing this issue as fixed.

![image](https://github.com/Ultimaker/Cura/assets/8535734/1537cee1-1b00-4c05-80aa-7cf5a0da26ea)
