### ISSUE TITLE
Error slicing STL

### ISSUE THREAD

**Issue by juankart-git** [Ultimaker/Cura#18902]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Sovol 07 plus

### Name abnormal settings

Normal settings, no support

### Describe model location

Platafform

### Describe your model

Sauron plattform

### Add your .zip here ⬇️

[Uploading 1008-16-17_platform_SLA(repaired).zip…]()
The file here

**Comment by GregValiant** [comment]
Thanks for the report.
Many of the slicing problems of 5.6.0 have been fixed in 5.7.0.  I would suggest you install it and give it a try.

I'll mark this as a duplicate report and go ahead and close it.  I hope you understand.
