### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by Govardhan3d** [Ultimaker/Cura#18908]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

creality ender-3 ender-3 v2

### Name abnormal settings

yes its in default profiles

### Describe model location

center of buildplate

### Describe your model

After slicing and it gets failed and i tried to mesh fix too

### Add your .zip here ⬇️

![Desktop Screenshot 2024 04 17 - 08 22 54 85](https://github.com/Ultimaker/Cura/assets/131440401/641b725b-85bd-4a93-80e8-814b16aa25c8)
[CE3E3V2_Body1.zip](https://github.com/Ultimaker/Cura/files/15013189/CE3E3V2_Body1.zip)

**Comment by chross** [comment]
Same problem here.
Using the Linux x64 AppImage on Ubuntu 22.04 in a VM on Windows 11 host.

**Comment by jellespijker** [comment]
The zip file contains GCode which seems to indicate that slicing succeeded.
Can you please share the 3mf project file from the actual failed slice
