### ISSUE TITLE
slicer won't print thin walls

### ISSUE THREAD

**Issue by delta1981** [Ultimaker/Cura#18915]
### Cura Version

5.7.0

### Operating System

windows 11

### Printer

creality ender 2 pro

### Reproduction steps

I just sliced the file as normal with the settings I used in the last version of cura, 3 walls, cubic infill, 50mms print speed, skirt print bed adhesion

### Actual results

when printed there are gaps where there should be solid walls
![IMG_20240419_112128886](https://github.com/Ultimaker/Cura/assets/142016520/7923919e-82e2-46ba-a73f-29ce07614349)

### Expected results

this is what it should look like when sliced,
![IMG_20240419_114154870](https://github.com/Ultimaker/Cura/assets/142016520/3efc7177-8578-4076-9499-f1e81eab017b)
 this one was done on creality print and matches my previous print results with cura 5.6.0

### Add your .zip and screenshots here ⬇️

here is the file as requested above along with a screen shot 
![CE2_Flame light back fence - UltiMaker Cura 19_04_2024 12_09_18](https://github.com/Ultimaker/Cura/assets/142016520/c0ee519f-079f-47ab-963c-1b53be83ffd8)
[CE2_Flame light back fence.zip](https://github.com/Ultimaker/Cura/files/15039490/CE2_Flame.light.back.fence.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
In the Wall Settings is "Print Thin Walls".  It is not enabled in your project file and I get the same results that you show.

When I enable "Print Thin Walls" this is the result in 5.7.0
![image](https://github.com/Ultimaker/Cura/assets/64202104/ad6b32c5-883c-4d69-8304-500a6cbb3a73)

This looks like a settings issue.  I'll remove the bug label for now and leave this open so you can respond.

**Comment by delta1981** [comment]
this has fixed the issue don't know why it became unchecked when I upgraded from 5.6.0 to 5.7.0 hanks for all the help and the quick response

**Comment by GregValiant** [comment]
In the printer definition files for both 5.6 and 5.7 it is set to "false".  Maybe you had an override in a custom profile.
