### ISSUE TITLE
Combining "Gradual Infill Steps" and "Infill Overlap Percentage" produces extraneous "dots"

### ISSUE THREAD

**Issue by daniels220** [Ultimaker/Cura#18924]
### Cura Version

5.6.0

### Operating System

macOS Sonoma

### Printer

CR-10

### Reproduction steps

1. Start with default settings (which include an Infill Overlap Percentage), any reasonable model with some interior volume that will get infill.
2. Enable "Gradual Infill Steps", and values.

### Actual results

Observe little "dots" of infill appearing in the lower-density layers, where the full-density infill would/will overlap the walls.

### Expected results

Wall-overlap segments are only generated where actual infill appears.

### Add your .zip and screenshots here ⬇️

[curabug.3mf.zip](https://github.com/Ultimaker/Cura/files/15049557/curabug.3mf.zip)
<img width="933" alt="Screenshot 2024-04-20 at 4 04 53 PM" src="https://github.com/Ultimaker/Cura/assets/1410866/96be364a-4a5c-411b-b0f6-5814de92a64e">

**Comment by GregValiant** [comment]
Thanks for the report.
I can duplicate this and I've seen it before.  It sort of makes the setting useless when the nozzle is spitting little dots everywhere.
![image](https://github.com/Ultimaker/Cura/assets/64202104/327b9d9d-fa01-46aa-8977-f2b243f99bf8)

[18924.zip](https://github.com/Ultimaker/Cura/files/15049774/18924.zip)

**Comment by HellAholic** [comment]
Hey @daniels220,
Thanks for the report. Issue is resolved in 5.7.1 available to download now.
![image](https://github.com/Ultimaker/Cura/assets/28710690/10bdb873-f07a-421a-9484-7fb8c627d432)

@GregValiant I also checked your model and no more ant trails. Magic performed by PR from Remco :)
![image](https://github.com/Ultimaker/Cura/assets/28710690/aa957989-e3b4-42b1-92be-b7dfe692395f)

Could you double check if it is the case for you as well?

**Comment by GregValiant** [comment]
@HellAholic  Looks like it's fixed.  Congrats to Remco on the quick service.
(It does make me a little suspicious about where the bug came from.  Could it have been an "unexpected consequence" of something somebody did?)

@daniels220 this looks to be resolved in the new release.  I don't see the problem with 5.7.1.
Can we close this?

**Comment by fieldOfView** [comment]
For reference:
https://github.com/Ultimaker/CuraEngine/pull/2062

**Comment by daniels220** [comment]
Yep, fixed for me as well.
