### ISSUE TITLE
Tengo un problema ya que no me permite segmentar mi pieza y poder trabajarla....

### ISSUE THREAD

**Issue by leo1929** [Ultimaker/Cura#18927]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ender SE

### Name abnormal settings

No, todo lo tengo igual que siempre, es más 5 minutos antes use el slicer y todo funciono bien con una pieza

### Describe model location

No

### Describe your model

No

### Add your .zip here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/65140715/da7394ef-0632-4c22-8c61-a1667510c5fe)

**Comment by jellespijker** [comment]
Please attach the project file (save as 3mf)
