### ISSUE TITLE
Not slicing when i move the part

### ISSUE THREAD

**Issue by JuLVD** [Ultimaker/Cura#18932]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ultimaker 2

### Describe your model

Bird head

### Add your .zip here ⬇️

[base_tete.zip](https://github.com/Ultimaker/Cura/files/15062089/base_tete.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This was a problem in 5.6.0.  A lot of work was put into it and it seems to be fixed in 5.7.0.  Install the new version and see if it works for you.

I'll mark this as a duplicate and go ahead and close this as it appears to have been fixed.  I hope you understand.
