### ISSUE TITLE
cura delete my walls 

### ISSUE THREAD

**Issue by nikita090309** [Ultimaker/Cura#18934]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

ender3-v2 Neo

### Name abnormal settings

no

### Describe your model

its my first try to make it 

### Add your .zip here ⬇️

[Новая сжатая ZIP-папка.zip](https://github.com/Ultimaker/Cura/files/15062647/ZIP-.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
As I mentioned on Reddit, that model isn't formed correctly and won't print.  I tried to repair it wiht MS3D Builder but it didn't look right.
Your model is on the left and the repaired model is on the right.  All those polka-dot surfaces are made wrong.  You need to go back to Blender and try again.  
![image](https://github.com/Ultimaker/Cura/assets/64202104/f9f07558-44ea-41cd-a3cc-83f0ff29e303)

I'll go ahead and remove the bug label and close this.  I hope you understand.
