### ISSUE TITLE
Problem slicing on tree supports...

### ISSUE THREAD

**Issue by GreenGrande115** [Ultimaker/Cura#18944]
### Cura Version

5.6

### Operating System

w11

### Printer

Ender 3

### Name abnormal settings

support and layer high 

### Describe model location

upside

### Describe your model

usb hub green

### Add your .zip here ⬇️

[report_Ugreen_USB_Hub_Mount.zip](https://github.com/Ultimaker/Cura/files/15087118/report_Ugreen_USB_Hub_Mount.zip)
this problems usually happen d when i use tree supports and then change the layer high on oe number difeerent that 0.1 i dunno why

**Comment by GregValiant** [comment]
Thanks for the report.
5.6.0 had a lot of slicing errors.  5.7.0 shows a huge improvement.
Install [5.7.0](https://github.com/Ultimaker/Cura/releases/tag/5.7.0) and see if the problem has been addressed.  I didn't have any trouble slicing this.
I'll mark this as a duplicate and go ahead and close it.  I hope you understand.

![image](https://github.com/Ultimaker/Cura/assets/64202104/cd6ca03d-f9ff-4d77-af84-8d6dfd8dad7f)
