### ISSUE TITLE
problème de découpe

### ISSUE THREAD

**Issue by Clara-Dubocage** [Ultimaker/Cura#18941]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

Anycubic Kobra

### Name abnormal settings

oui

### Describe model location

oui

### Describe your model

non je ne l'avais pas encore découpé et le problème persiste. oui j'ai essayé de faire un Mesh Fix rapide avec le plugin Meshtools mais rien ne s'améliore.

### Add your .zip here ⬇️

[masque bleach.zip](https://github.com/Ultimaker/Cura/files/15080126/masque.bleach.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
5.7.0 has been released and many of these slicing errors no longer happen.  Install [5.7.0](https://github.com/Ultimaker/Cura/releases) and see if the problem does away.

I'll mark this as a duplicate report and go ahead and close it.
