### ISSUE TITLE
Schuifmaat doos

### ISSUE THREAD

**Issue by brdi** [Ultimaker/Cura#18950]
### Cura Version

5.7.0

### Operating System

MacOS 11.7.10

### Printer

FLSUN V400

### Name abnormal settings

Own Config

### Describe model location

No, whatever I changed, or seperated, it fail

### Describe your model

Box with inlay and box lid, almost no support 

### Add your .zip here ⬇️

[3mfModelfile_Schuifmaat_doos.zip](https://github.com/Ultimaker/Cura/files/15100314/3mfModelfile_Schuifmaat_doos.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You attached 3mf model files and we need project files.
Use the "File | Save Project" command to create a project file, zip it and post the zip folder here.  A project file contains the model, your printer, and all your Cura settings.
I installed a V400 and both of the files you posted sliced for me without any problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/46fe204a-23b4-4dcf-8e03-94ff1725c568)
