### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by SpceCdt** [Ultimaker/Cura#18969]
### Cura Version

5.6.0

### Operating System

WIndows 11

### Printer

ETINA TINA 2S

### Describe your model

pins and small parts

### Add your .zip here ⬇️

[ReiGun - Remington Derringer 95 Cap Gun BB 6mm.zip](https://github.com/Ultimaker/Cura/files/15135765/ReiGun.-.Remington.Derringer.95.Cap.Gun.BB.6mm.zip)

**Comment by HellAholic** [comment]
Hey @SpceCdt ,
Please include a project file as described in the page where you've submitted the issue.
Without a project file, there is no possible way to help you with the issue.
