### ISSUE TITLE
Sorry, you have been blocked You are unable to access ultimaker.com

### ISSUE THREAD

**Issue by kos19191** [Ultimaker/Cura#18972]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

kingroon kp3s

### Reproduction steps

registration in the application
Immediately after installation I cannot register in the application

### Actual results

Sorry, you have been blocked You are unable to access ultimaker.com

### Expected results

registration in the application

### Add your .zip and screenshots here ⬇️

![Снимок экрана 2024-04-28 001709](https://github.com/Ultimaker/Cura/assets/81749973/b7fea34f-bbf7-4dc5-9f14-9c4d31078ac4)
![Снимок экрана 2024-04-28 001654](https://github.com/Ultimaker/Cura/assets/81749973/fb0aeefb-45b5-4455-8e93-7c73b3015004)
![Снимок экрана 2024-04-28 001637](https://github.com/Ultimaker/Cura/assets/81749973/f10a92ae-ee84-4ee7-812b-b37eb24fbe04)

**Comment by fieldOfView** [comment]
This will not fix your access to ultimaker.com, but you do not need to be logged in in Cura to be able to use it.

**Comment by HellAholic** [comment]
Sorry but we cannot help you here from Cura repository. Whether it was due to your activity, regulation changes, or an issue of the website, it is outside of Cura.

**Comment by kos19191** [comment]
Can you tell me where I should go with this question?

**Comment by kos19191** [comment]
Can you tell me where I should go with this question?

**Comment by fieldOfView** [comment]
Again, you do not have to create an account or log in to use the application.

**Comment by ZEX-SPb** [comment]
Что делать, если при входе в аккаунт Cura написано: "Sorry, you have been blocked
You are unable to access ultimaker.com"?
![WhatsApp 2024-05-24 в 15 32 14_52c9fd0d](https://github.com/Ultimaker/Cura/assets/141618418/e837fceb-061f-4938-b0af-58579cdc6644)

**Comment by HellAholic** [comment]
@ZEX-SPb I've removed your IP address due to security reasons for your own benefit. Please do not share your IP on public places.

Regarding your lack of access, you're attempting to access the Ultimaker.com from a country that has been banned from accessing the Ultimaker website. As such, we cannot help you with this issue. It is out of our hands.

**Comment by nick140891** [comment]
Подтверждаю. Данная проблема существует и в настоящее время. Дискриминация по признаку местонахождения человека - это, мягко-говоря, крайне не дружественный жест. Прошу исправить эту несправедливость.
