### ISSUE TITLE
Heinz

### ISSUE THREAD

**Issue by lauimaus** [Ultimaker/Cura#18978]
### Cura Version

5.7 beta 

### Operating System

Windows 10

### Printer

Zonestar Z8pm pro

### Name abnormal settings

nein

### Describe model location

nein

### Describe your model

erster versuch mit diesem drucker

### Add your .zip here ⬇️

[Z8WE4H_Color_2.zip](https://github.com/Ultimaker/Cura/files/15142805/Z8WE4H_Color_2.zip)

**Comment by lauimaus** [comment]
bestimmt ein Einstellungs Fehler

**Comment by GregValiant** [comment]
That was quick.  I'll remove the bug label and close it.
