### ISSUE TITLE
failed to slice a project

### ISSUE THREAD

**Issue by bluetriggerfis** [Ultimaker/Cura#18980]
### Cura Version

5.0.6

### Operating System

windows 11

### Printer

creality Ender-3 / Ender-3 v2

### Name abnormal settings

i just set the model on a generic ABS profile with some custom settings like walls,infill,support,speed

### Describe model location

its in the middle with the highest ammount of space i can use on this printer

### Describe your model

its a airless basketball modell

### Add your .zip here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/168378018/30b6c782-731b-405c-b446-546cb1ccf190)

**Comment by bluetriggerfis** [comment]
it also will not slice on any other profile or other fillament i tested it

**Comment by GregValiant** [comment]
Thanks for the report.
That "Airless Basketball" model has been here several times.  It's full of errors.
If you zoom in on the image you supplied you can see red surfaces facing upwards.  All those red surfaces are flipped inside-out and they confuse Cura.
After repairing the model it should slice in 5.7.1.

I'll mark this as a duplicate report and go ahead and close it.  I hope you understand.
Between the model errors and slicing errors in some installations of 5.6.0, this probably can't be made to slice in 5.6.0.
