### ISSUE TITLE
Error in slicer

### ISSUE THREAD

**Issue by NeoNarco** [Ultimaker/Cura#18981]
### Cura Version

5.2.1

### Operating System

Win11

### Printer

Artillery X1

### Reproduction steps

Set the models to print, click on slice, wait 30secs then the error comes up. 

### Actual results

I get a message saying there´s an error and that I should report it here.

### Expected results

Please fix this. It never happened to me before. 

### Add your .zip and screenshots here ⬇️

Nothing else

**Comment by HellAholic** [comment]
Hey @NeoNarco , there is a new version of Cura available to download (5.7.1), give that one a try and see if your issue still persists.

Cheers!
