### ISSUE TITLE
"Use value from material" is missing from the right-click menu on a setting box

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#18983]
### Cura Version

5.7.0 and 571

### Operating System

Windows 10 Pro

### Printer

Ender 3 Pro

### Reproduction steps

1. Made a change to the print temperature.
2. Right-click on the setting box and view the menu options.

### Actual results

1. The right-click menu has two items "remove from favorites" and "configure favorites".  There were 3 options in 5.6.0 and earlier and the top option was "Use value from material".

### Expected results

It could have been removed on purpose, it was useful.

### Add your .zip and screenshots here ⬇️

5.7.0 and 5.7.1
![A1](https://github.com/Ultimaker/Cura/assets/64202104/23438c4a-b48f-4a48-8b41-451e07967e18)

5.6.0
![A2](https://github.com/Ultimaker/Cura/assets/64202104/7fd0b4e3-91ba-47a0-9ef9-2cd2c3a6132d)

**Comment by HellAholic** [comment]
Hey @GregValiant ,
I still see the option 🤔 
![image](https://github.com/Ultimaker/Cura/assets/28710690/aaba1ec6-6a95-4421-a002-1e6e14ab0275)

Maybe missing a plugin?

**Comment by GregValiant** [comment]
I'm going thru it now.  I haven't found it yet, but I do play around with things a bit.  

I had neglected to load "Material Settings".  I guess it comes in with the plugin.
