### ISSUE TITLE
Problem when using "AutoTowers Generetor v2.6.0" from Marketplace on Cura v5.7.0

### ISSUE THREAD

**Issue by dragonimpressoes** [Ultimaker/Cura#18986]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

Creality Ender 3 V2

### Reproduction steps

1.: Installed "AutoTowers Generetor v2.6.0" from marketplace in cura v5.7.0, wich i use since cura version v5.5.0. 
2.: When going to Extensions, Post Processing, and then Modify G-Code, the custom added Scripts of "Speed Tower" and "Retract Tower" aren't avaible.

OBSERVATION.: Then i did go to Help, Show Configuraton Folder. Windows explorer opened. Saw some archives and folders. Did go to Plugins, AutoTowersGenerator, AutoTowersGenerator, Postprocessing, and then on this folder i saw all the files with the custom script wich cura should had loaded into "Modify G-Code" tab. The files are there. 

### Actual results

Custom scripts doesn't load in cura v5.7.0.

### Expected results

The use of custom added scripts into Post Processing: Modify G-Code. Those were "Speed Tower" and "Retract Tower".

Couldn't fix nothing yet and couldn't use till the moment of this issue report the cutom scripts. Cura v5.7.0 just don't load then. It was working on the latest version of cura i've used, wich was v5.5.0.

### Add your .zip and screenshots here ⬇️

![1](https://github.com/Ultimaker/Cura/assets/168498304/a13de9db-accf-41ec-b6c6-f7e062649b08)
![2](https://github.com/Ultimaker/Cura/assets/168498304/96d6cfa4-6ce5-42c8-b65f-eb19fb7a3e8d)
![3](https://github.com/Ultimaker/Cura/assets/168498304/255ce016-a4b8-4c10-999c-901a6d564851)

**Comment by Asterchades** [comment]
The AutoTowers plugin is not maintained by the Cura team. Any issues with it that are not being caused by underlying Cura functionality will need to be reported to its author over on its GitHub repository.

https://github.com/kartchnb/AutoTowersGenerator
