### ISSUE TITLE
Print starts before bed has reached temperature

### ISSUE THREAD

**Issue by LilBub** [Ultimaker/Cura#18996]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Ultimaker 2+

### Reproduction steps

Printer has a 0.6 nozzle installed and using Ultimaker Blue ABS material.
Used default settings for the Ultimaker Blue ABS in Cura.  Verified 0.6mm nozzle selected (Settings - Extruder 1- Nozzle)
Checked default temps, 230C for hotend, 80C for buildplate
Loaded print.
Expected it would take 5-10 mins for Ultimaker 2+ bed to reach temp, then hotend....then print.
Print started as soon as hot end hit 230C , bed was at 51C
See below from Octoprint capture
![image](https://github.com/Ultimaker/Cura/assets/14837299/b6bb4150-c67e-47c3-a723-da5af1abf27f)

### Actual results

Print starts despite bed not to temp.  Thankfully it stayed stuck down.

### Expected results

Bed heats first, nozzle, then print starts

### Add your .zip and screenshots here ⬇️

[Ultimaker.zip](https://github.com/Ultimaker/Cura/files/15182693/Ultimaker.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I think you have a printer problem.  Your gcode is correct.  If you post a question on the [UM Forum](https://community.ultimaker.com/discover/) and mention @Torgeir he is real good with the UM 2's.

In the Cura "Printer Settings" the boxes for "Wait for nozzle heatup" and "Wait for build plate heatup" are both checked.

This is from the gcode file you posted and I get the same thing when I slice the project.  (I've added the comments.)
;TARGET_MACHINE.NAME:Ultimaker 2+
;Generated with Cura_SteamEngine 5.7.0
M140 S80    >> start heating the bed
M105           >> report the temperature
**M190 S80 >> wait for the bed to hit 80**
M104 S230  >> start heating the nozzle
M105           >> report temperature
M109 S230  >> wait for the nozzle to hit 230
M82 ;absolute extrusion mode

So the "Wait for bed" command is being properly inserted into the Gcode but your printer is ignoring it.

I don't see a problem here with what Cura is doing so I'll remove the bug label and go ahead and close this.  I hope you understand.
