### ISSUE TITLE
unknown Slicing Error when turn the 3D printpart on the larger side

### ISSUE THREAD

**Issue by Tschezzel** [Ultimaker/Cura#18994]
### Cura Version

5.7.0-beta.1

### Operating System

Windows 11

### Printer

Creality CR-6-SE

### Describe model location

it only slice if you rotate on the short sides

### Describe your model

its one piece off 4 from a sieve

### Add your .zip here ⬇️

The slicing works if the components are made smaller. For example, at 70% of the original size, or if the parts are tilted onto their shorter edges. I have included the components, photos of the error message, and a video showing the error in a zip file. With the Creality slicer, I can place and slice the parts without any issues.
[Cura Ulitimaker Failed Slicing Photos,Video and All Models.zip](https://github.com/Ultimaker/Cura/files/15178330/Cura.Ulitimaker.Failed.Slicing.Photos.Video.and.All.Models.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Install 5.7.1 and see if the problem persists on your system.  I didn't have any trouble slicing the models on my Win10 system using Cura 5.7.1.

I'll mark this as a duplicate.  The slicing errors present in 5.5 and 5.6 were worked on and 5.7 stable and now 5.7.1 are considerably improved.  I'll go ahead and close this.  If you have a problem slicing the models with 5.7.1 let us know.
