### ISSUE TITLE
total fail

### ISSUE THREAD

**Issue by flak0o** [Ultimaker/Cura#19009]
### Cura Version

5.7.1

### Operating System

wndows 10

### Printer

ender 3 v2

### Name abnormal settings

no

### Describe model location

no

### Describe your model

yes, i sliced it before in another pc, but with the same configuration... also with the new version it cant be sliced

### Add your .zip here ⬇️

[alastor-horns-hasvin-hotel20240418-1-jnmne9.zip](https://github.com/Ultimaker/Cura/files/15196358/alastor-horns-hasvin-hotel20240418-1-jnmne9.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate this with my Ender 3 Pro active.  We will need a project file and the Cural.log file.  The instructions are on the form.
