### ISSUE TITLE
Problema de cortado

### ISSUE THREAD

**Issue by eduardoag2005** [Ultimaker/Cura#19008]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

artillery X1/X2

### Name abnormal settings

no

### Describe model location

no se corta el modelo, solo aparece el error al querer segmentar el modelo

### Describe your model

antes, con este modelo es la primera vez que pasa

### Add your .zip here ⬇️

[ASX1_BUFF_PSYDUCK_2.zip](https://github.com/Ultimaker/Cura/files/15196013/ASX1_BUFF_PSYDUCK_2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The only thing in that zip file is an empty zip file.
