### ISSUE TITLE
tolerance failing the slice

### ISSUE THREAD

**Issue by supersonicsalt** [Ultimaker/Cura#19000]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

elegoo neptune 3 plus

### Name abnormal settings

slicing tolerance: exclusive     i isolated it

### Describe model location

location, rotation and scale doesnt matter

### Describe your model

gear bearing, its twisty and polygon heavy especially at the "almost connection" points

### Add your .zip here ⬇️

[gear bearing 3d model.zip](https://github.com/Ultimaker/Cura/files/15188700/gear.bearing.3d.model.zip)

**Comment by GregValiant** [comment]
Thanks for the report
There were a lot of fixes made to 5.7 and 5.7.1.  Both are much more reliable than 5.6 so I would suggest you install 5.7.1 and see if your slicing error has been addressed.

I'll mark this as a duplicate and go ahead and close it.  If the problem still exists in 5.7.1 then this report can be updated or you can fill out another report concerning 5.7.1
