### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by majey2410** [Ultimaker/Cura#19001]
### Cura Version

5.6.0

### Operating System

window 11

### Printer

flsun sr

### Name abnormal settings

no

### Describe model location

same

### Describe your model

all my model do not slice

### Add your .zip here ⬇️

![Uploading Capture d'écran 2024-05-02 153506.png…]()

**Comment by GregValiant** [comment]
Thanks for the report.
We need a project file and the Cura.log file to investigate.  The instructions for posting them are on the form you filled out.
