### ISSUE TITLE
Erro ao tentar fatiar arquivo

### ISSUE THREAD

**Issue by Narlon89** [Ultimaker/Cura#19013]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Sovol 07 plus

### Describe your model

Sim, mas a impressora foi outra

### Add your .zip here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/168884533/93338a2b-a4f4-4d1a-9b6d-47f1ea285f80)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file and Cura.log file we have nothing to investigate.  The instructions are on the form.
