### ISSUE TITLE
5.6.0切面失败

### ISSUE THREAD

**Issue by shakulamao** [Ultimaker/Cura#19014]
### Cura Version

5.6.0

### Operating System

win11

### Printer

ELEGOO NEPTUNE4

### Describe your model

其他软件切片正常

### Add your .zip here ⬇️

![微信截图_20240504144316](https://github.com/Ultimaker/Cura/assets/113078134/e48c32ee-1894-4639-b83c-4e0c4ffcca41)

**Comment by GregValiant** [comment]
Thanks for the report.
There were problems in 5.5 and 5.6.  They were worked on and 5.7 and now 5.7.1 are MUCH better at avoiding these "won't slice" problems.  I suggest you update your Cura version and see if the problem with this model goes away.  Let us know if that works for you.

I'll mark this as a duplicate and go ahead and close it.  This was a well known problem in 5.6.0.
