### ISSUE TITLE
Slicing fails when model is horizontally oriented

### ISSUE THREAD

**Issue by damp-canary** [Ultimaker/Cura#19022]
### Cura Version

5.6.0

### Operating System

Window 10

### Printer

Anet A8

### Name abnormal settings

I use same custom settings(in attachment) for all my prints

### Describe model location

It slices if I make model vertical

### Describe your model

This is first slicing of my model

### Add your .zip here ⬇️

[cord_metro_v2_base.zip](https://github.com/Ultimaker/Cura/files/15214515/cord_metro_v2_base.zip)
[anet3d_extruder_0_%232_draft_high_spped.inst.zip](https://github.com/Ultimaker/Cura/files/15214524/anet3d_extruder_0_.232_draft_high_spped.inst.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Many of the slicing bugs that were present in 5.5 and 5.6 have been repaired in 5.7 and now 5.7.1.  I suggest you [install 5.7.1](https://github.com/Ultimaker/Cura/releases) and see if the problem persists.

I'll mark this as a duplicate as this was a well-known bug.  It appears to have been fixed so I'll go ahead and close this.  I hope you understand.
