### ISSUE TITLE
(5.7.1) Problemas de inicio de sesión

### ISSUE THREAD

**Issue by 000DarkGhost000KingofDarkness000** [Ultimaker/Cura#19024]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Ender 3

### Reproduction steps

fallo al 
<img width="959" alt="Captura de pantalla 2024-05-06 010644" src="https://github.com/Ultimaker/Cura/assets/117627272/87892f1f-fb9c-45e3-bf9c-caf16f463ea1">
iniciar sesión

### Actual results

la aplicación no responde al tratar de iniciar sesión

### Expected results

ojala puedan resolver eso 

### Add your .zip and screenshots here ⬇️

<img width="959" alt="Captura de pantalla 2024-05-06 010644" src="https://github.com/Ultimaker/Cura/assets/117627272/7fe32604-5e98-4273-ab58-16ab64a638f6">

**Comment by GregValiant** [comment]
Thanks for the report.
This might be an installation issue.  Do you have an UltiMaker account?  You can try re-installing 5.7.1 and pay close attention to the dialog boxes.  When you see a reference to Cloud printing or Network printing you should "Skip" it.  Those are intended for use with UltiMaker printers.
