### ISSUE TITLE
STL Failed to Slice

### ISSUE THREAD

**Issue by moccajava** [Ultimaker/Cura#19038]
### Cura Version

5.7

### Operating System

MacOS Catalina

### Printer

Snapmaker 2

### Describe your model

Yes it is. Brush holder

### Add your .zip here ⬇️

[Snapmaker_CNC_suction_Brushes_holder.stl.zip](https://github.com/Ultimaker/Cura/files/15233771/Snapmaker_CNC_suction_Brushes_holder.stl.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The STL file seems to be fine with no errors.  I didn't have any trouble slicing it on Windows 10.
Use the "File | Save Project" command to create a project file.  Use "Help | Show Configuration Folder" to locate the Cura.log file.
Zip the log file and the project file and post the zip folder here.
