### ISSUE TITLE
Failed to slice unless model was moved or rotated

### ISSUE THREAD

**Issue by radchad24** [Ultimaker/Cura#19032]
### Cura Version

5.7.0

### Operating System

Windows 10

### Printer

Voron Trident 300

### Name abnormal settings

Fast profile

### Describe model location

center, slices if rotated

### Describe your model

carbon filter for bento box mod

### Add your .zip here ⬇️

[carbon.zip](https://github.com/Ultimaker/Cura/files/15227617/carbon.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing it on my Win10 system, Cura 5.7.1.  My Ender 3 Pro was the active printer.

Use the "Help | Show Configuration Folder" command to locate the Cura.log file and post that file here.  Maybe it will give a clue.
![image](https://github.com/Ultimaker/Cura/assets/64202104/29c7bb93-c3fb-4dfb-bf95-a218d2812cfc)
