### ISSUE TITLE
Error de Corte

### ISSUE THREAD

**Issue by thebryanaes** [Ultimaker/Cura#19045]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3

### Reproduction steps

1. Escale un objeto a 450%
2. Le di a laminar

### Actual results

Me dijo que se produjo un error a la hora de realizar el corte

### Expected results

Que se laminara

### Add your .zip and screenshots here ⬇️

[CE3E3V2_toothless_keychain.zip](https://github.com/Ultimaker/Cura/files/15255795/CE3E3V2_toothless_keychain.zip)
![imagen_2024-05-08_170311701](https://github.com/Ultimaker/Cura/assets/169314362/0c740349-b9c9-40e6-a453-ae7e635aa67f)

**Comment by GregValiant** [comment]
Thanks for the report.
I suggest you upgrade to Cura 5.7.1.  Many slicing errors have been fixed in the new version so it should take care of your problem.

I'll mark this as a duplicate and close it.  I hope you understand.
