### ISSUE TITLE
Issue: ❌ Slicing Failed

### ISSUE THREAD

**Issue by uNbAs** [Ultimaker/Cura#19047]
### Cura Version

5.6.0 and 5.7.1

### Operating System

Ubuntu 22.04 LTS

### Printer

Ender 3 PRO

### Describe model location

Center

### Describe your model

keychain

### Add your .zip here ⬇️

[CE3E3V2_ChameleonUltra_Keyring.zip](https://github.com/Ultimaker/Cura/files/15260001/CE3E3V2_ChameleonUltra_Keyring.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't find anything wrong with the model and it sliced for me without problems on Win10 and Cura 5.7.1.

Use the "Help | Show Configuration Folder" command to locate the Cura.log file and post that file here.  Maybe it will give a clue regarding the problem.

**Comment by uNbAs** [comment]
Sorry, I delete ~/.local/share/cura and reconfigure the printer and now works normally.

Close the issue

**Comment by GregValiant** [comment]
Good that you got it working.
I'll close this.
