### ISSUE TITLE
Hi Resolution Display issue with dialog boxes

### ISSUE THREAD

**Issue by seanmcne** [Ultimaker/Cura#1905]
On high DPI/Resolution monitors I can't see the entire dialog box contents: 

![image](https://cloud.githubusercontent.com/assets/2292260/26584552/ca6fd360-450e-11e7-9fb0-8421ff801d23.png)

**Comment by nallath** [comment]
@Appesteijn; Seems like you didn't find all cases.

**Comment by TachyonStream** [comment]
FYI, Appears to be a duplicate of #1893 I opened a few days ago.  Caused by display scaling, which is used on high res monitors too.

**Comment by seanmcne** [comment]
Yep def a duplicate of that bug - thanks!
