### ISSUE TITLE
when opening a file for second time after update the date-Time does not change

### ISSUE THREAD

**Issue by hcopray** [Ultimaker/Cura#19067]
### Cura Version

5.7.1

### Operating System

windows 11

### Printer

ultimaker 3 extended

### Reproduction steps

>File >Open file
change file in other program (Blender)
reload with >File>Open File
all works well, but Time does not change in file list

### Actual results

File List field date keep first time and dont change

### Expected results

time change by reload file
It seems an little error and doesnt effect the print result, but I prefer to check the right file.

### Add your .zip and screenshots here ⬇️

![afbeelding](https://github.com/Ultimaker/Cura/assets/169601986/f98112be-d335-4ea7-b55c-efe659dda405)

**Comment by HellAholic** [comment]
Not exactly sure what you're expecting to happen. Open file / reload file is a read action, that does not modify a STL or a project file in Cura without the user saving the file. If you save the file as a project or as another STL then the timestamp will update.
