### ISSUE TITLE
all i know is slice failed

### ISSUE THREAD

**Issue by seriousfreedom** [Ultimaker/Cura#19079]
### Cura Version

5.7

### Operating System

linux mint -edge

### Printer

ender 3

### Name abnormal settings

none

### Describe model location

center of bed

### Describe your model

modular wrench organizer

### Add your .zip here ⬇️

/home/klipper/Desktop/faliled slice.zip

**Comment by seriousfreedom** [comment]
/home/klipper/.local/share/cura/5.7/cura.log

**Comment by GregValiant** [comment]
That link doesn't work.
