### ISSUE TITLE
Slices with more layers than it should. It is also larger in size.

### ISSUE THREAD

**Issue by TomTay56** [Ultimaker/Cura#19074]
### Cura Version

5.7.1

### Operating System

Linux Mint

### Printer

Ender-3 with Skr Mini E-3 V2.0

### Reproduction steps

1. Just slice as normal.

### Actual results

5.7.1 shows 128 mm and prints 672 layers at .2 Adaptive layers is off.

### Expected results

Sliced with 5.4 and it shows 128 mm and prints 640 layers at .2 Prusa slicer also prints 640 layers at .2
![DSC01113](https://github.com/Ultimaker/Cura/assets/19932770/9223a3b0-4910-48b2-947f-933cf547c125)
![DSC01114](https://github.com/Ultimaker/Cura/assets/19932770/7d5af702-1430-4a50-9834-bbf7b858c253)

### Add your .zip and screenshots here ⬇️

![Cura](https://github.com/Ultimaker/Cura/assets/19932770/6aa4eaf8-5f16-47d8-9be5-39fac00b6ff9)

**Comment by HellAholic** [comment]
@TomTay56 Check your shrinkage factors for the material you're using.
Generic material does not have the shrinkage factor (set at 100%) so when you slice with 0.2mm, you get 640.
If you have the ABS with shrinkage factor above 100%, you'll get more layers with all the same variables. 
That is a guess without a project file. If you would like a more concrete answer or investigation, include a project file as instructed by the report forms.

![image](https://github.com/Ultimaker/Cura/assets/28710690/17b78e71-3ef1-4fa1-823e-2f82290f6da4)
![image](https://github.com/Ultimaker/Cura/assets/28710690/4e36581b-ae56-4585-aae7-d330adb5593d)

**Comment by TomTay56** [comment]
Deleted old profile. 
Made changes and saved new profile. 
All is good now.
