### ISSUE TITLE
Cura 2.6.0 Beta not slice even a simple model

### ISSUE THREAD

**Issue by vmzsoft** [Ultimaker/Cura#1907]
Only show "Slicing..." and nothing.
But Cura 2.5 works normally.
Win7x64
Custom printer Mikromake D1

**Comment by smartavionics** [comment]
Although the Cura devs are clever people, their talents don't extend to mind reading. You're going to have to provide more info (images, model, profile, etc.) if there is going to be any chance of anybody understanding what the problem is here.

**Comment by vmzsoft** [comment]
Model - any, even a simple little cube.
Profile - any. I tried default profile for the Ultimaker, and asked settings for my Micromake.
Why these details?
I didn't even connect the printer, I'm just interested to try new version of slicer and see the difference ...

**Comment by fieldOfView** [comment]
We need logs.

Please read the readme, specifically the part about reporting issue.
https://github.com/Ultimaker/Cura/blob/master/README.md

**Comment by Ghostkeeper** [comment]
I don't have your custom printer Mikromake D1, but when I load a 1x1x1cm cube in to slice for the Ultimaker 2+ it slices fine. Not able to reproduce this issue...

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.
