### ISSUE TITLE
Slicing failed on any model

### ISSUE THREAD

**Issue by minich21** [Ultimaker/Cura#19078]
### Cura Version

5.7.1 Beta

### Operating System

Windows 11

### Printer

Elegoo Neptune 4 Max

### Name abnormal settings

Default settings

### Describe model location

No

### Describe your model

Multiple models have been tried, freshly downloaded ones as well

### Add your .zip here ⬇️

Having issues with Elegoo Cura 4.8, Elegoo Cura 5.6, Cura 5.7.1 Beta

**Comment by seriousfreedom** [comment]
im on linux mint and im unable to get any of the last 3 builds of cura to slice

**Comment by GregValiant** [comment]
This is the UltiMaker Cura site.  You need to report this on the Elegoo website as they are responsible for their version.

I'll go ahead and close this.  I hope you understand.
