### ISSUE TITLE
Monster Truck Bumps

### ISSUE THREAD

**Issue by reure1** [Ultimaker/Cura#19099]
### Cura Version

5.7.0

### Operating System

Windows 10

### Printer

Ender-3 S1 Pro

### Describe model location

It will slice if the track standing on end. Track goes up and down.

### Describe your model

It sliced standing on end but needed a lot more supports so it would not fall down.

### Add your .zip here ⬇️

[Bumps Generic PLA lw 0.4mm lh 0.2mm if 20% ext1 200C bed 60C.zip](https://github.com/Ultimaker/Cura/files/15366431/Bumps.Generic.PLA.lw.0.4mm.lh.0.2mm.if.20.ext1.200C.bed.60C.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I could not get it to "not slice".  No matter how I oriented it, it still sliced.
If you can get it to fail again, use the "Help | Show Configuration Folder" command to locate the Cura.log file.  Zip that file and post the zip folder here and someone from the Cura team will take a look.

I sliced it with both normal and tree supports.  With tree supports it's a 6:50 print.
I enabled "Remove all Holes" and with Grid Infill at 15% density and Infill Layer Thickness at 2X layer height it's a 4:10 print.
Here I configured the supports as if they were infill.  They won't need to be removed so the Roof Z distance is zero and the XY distance is zero..
![image](https://github.com/Ultimaker/Cura/assets/64202104/402c63e5-b5d2-4c18-8ec9-f250bf6e0644)
