### ISSUE TITLE
Slicing creates a gcode with hotend temp 250 despite setting 200 in project. 

### ISSUE THREAD

**Issue by nicksephton** [Ultimaker/Cura#19108]
### Cura Version

1.7.2

### Operating System

Windows 11

### Printer

Sovol SV06 Plus

### Reproduction steps

1. Load project file.
2. Observe that printing temperature is set to 200.
3. Slice.
4. Save gcode file.
5. Open gcode file in notepad, observer that M104 and M109 are set to 250.

### Actual results

Printing temperature is set to 250.

### Expected results

Printing temperature should be set to 200.

### Add your .zip and screenshots here ⬇️

[SSPM_MultiboardSmallScrewdriverHolder.zip](https://github.com/Ultimaker/Cura/files/15377223/SSPM_MultiboardSmallScrewdriverHolder.zip)

**Comment by GregValiant** [comment]
There is no such thing as an "Ultimaker Cura version 1.7.2".  The gcode file states:
**";Generated with Sovol Slicer 1.7.2"**
You need to go to Sovol for support.

I'll close this as it is not an Ultimaker Cura problem.
