### ISSUE TITLE
No model loading on Ubuntu 24.04

### ISSUE THREAD

**Issue by lalmat** [Ultimaker/Cura#19104]
### Cura Version

5.7.1

### Operating System

Ubuntu 24.04 LTS

### Printer

Ender 3v3 SE

### Reproduction steps

Under Ubuntu 24.04 (Wayland or XOrg) :
- Launch Cura AppImage, 
- Open a STL file

### Actual results

Nothing append. 
No error message on screen.
No error message when started from command line.

### Expected results

Model loaded on platform

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/2410437/22633ced-102a-4710-a51d-5e79511700b4)

**Comment by lalmat** [comment]
Ok, seem to be solved...

When showing the about screen, the model appear just after... Very strange...

**Comment by T00rk** [comment]
I have the same problem but showing the about screen doesn't work

**Comment by lalmat** [comment]
Have you tried the xorg desktop ?  
Le lun. 20 mai 2024 à 13:43, T00rk ***@***.***&gt; a écrit :  I have the same problem but showing the about screen doesn't make the model appear

**Comment by T00rk** [comment]
Yes I tried both Xorg and Wayland. Nothing works

**Comment by T00rk** [comment]
My bad. It opens the file after 10 minutes

**Comment by arsabe75** [comment]
Same issue in Kubuntu 24.04, using last app image of Cura, when I open a STL file, nothing is shown in the screen bed

**Comment by T00rk** [comment]
> Same issue in Kubuntu 24.04, using last app image of Cura, when I open a STL file, nothing is shown in the screen bed

You have to wait for a loooong time. Maybe 5 or 10 minutes

**Comment by sausix** [comment]
Don't understand why this issue has been closed?

As mentioned in the other issue thread, the problem is probably the `USB Printing plugin` which blocks the apllication while trying to connect to a printer.
Most people don't need that plugin since they use USB drives or Octoprint.

Can someone confirm it helps?

**Comment by gtollini** [comment]
> Don't understand why this issue has been closed?
> 
> As mentioned in the other issue thread, the problem is probably the `USB Printing plugin` which blocks the apllication while trying to connect to a printer. Most people don't need that plugin since they use USB drives or Octoprint.
> 
> Can someone confirm it helps?

It 100% works, you can test it yourself. Here's how:

> I fixed this by disabling USB printing altogether (I've never had an USB printer to begin with). To do that:
> 
>     * Go to the “Installed” tab of the Marketplace.
> 
>     * Scroll down to USB Printing and click "disable".
> 
>     * Restart Cura.

If you wanna know _why_ it works, here's [a quick explanation](https://github.com/Ultimaker/Cura/issues/16249#issuecomment-2095377905).

**Comment by lazee486** [comment]
I dont use the usb plugin, fresh download this morning, setup ender3 pro and octoprint plugin....10 minute loads :(

**Comment by fieldOfView** [comment]
The "USB Printing" plugin, not to be confused with "USB Printing NG" or "OctoPrint" plugins, is installed and enabled in Cura by default even if you do no need it. You _can_ configure Cura to disable the "USB Printing" plugin. This is independent of other plugins you may or may not have installed.

The instructions still stand:

* Go to the “Installed” tab of the Marketplace (the gear icon on the top right of the dialog).
* Scroll down to "USB Printing" and click "disable".
* Restart Cura.
