### ISSUE TITLE
Slicing failed after a long time trying.

### ISSUE THREAD

**Issue by benclewett** [Ultimaker/Cura#19127]
### Cura Version

 5.6.0

### Operating System

MacOS 14.4.1

### Printer

Enders 3 v2 Neo

### Describe your model

Never sliced yet.

### Add your .zip here ⬇️

Project file here:
https://we.tl/t-PIK6eD36Xh

**Comment by GregValiant** [comment]
Thanks for the report.
Your model is loaded with errors.  Cura marks surfaces with a polka-dot pattern when they are inverted or have other problems.
I used 5.7.1 for these screenshots.  I do have the "Mesh Tools" plugin installed.
![image](https://github.com/Ultimaker/Cura/assets/64202104/24df861d-128f-4fc3-94b0-02f9f494b32c)

This is in "x-ray" view.  Most of this model appears to be "Invalid".
![image](https://github.com/Ultimaker/Cura/assets/64202104/7aaf574f-25bc-4904-8770-45bf4a8604f5)

At 507mb it's a really large STL.  Both MS 3D Builder and PrusaSlicer's NetFabb worked on it for a long time and neither was able to affect a complete repair.  I think this model needs to go back to CAD to be fixed.
There isn't a way to tell if the model is keeping Cura from slicing, or if it is a bug in Cura.

This model can't be sliced by Cura, PrusaSlicer, IdeaMaker, or OrcaSlicer.  PrusaSlicer crashed during the slice and Orca slicer informed me that even after the repair by NetFabb, the model still had 630,000+ non-manifold edges.

I'm going to remove the bug label and close this.  Your model is invalid.  I hope you understand.

**Comment by benclewett** [comment]
Thanks for your email.  I will install the Mesh Tool plugin, I can see this
is extremely useful.  And return to the CAD system to find the errors.

Many thanks for your time.

Ben
