### ISSUE TITLE
When i click Slicing says: Slicing Failed

### ISSUE THREAD

**Issue by BLAI38** [Ultimaker/Cura#19130]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

Anycubic Kobra 2

### Describe your model

Are 6 gears 

### Add your .zip here ⬇️

![Cura 5 7 1 error](https://github.com/Ultimaker/Cura/assets/97628256/1a5ff587-d9dc-489c-b2cf-bd1a21fc8f2c)

**Comment by GregValiant** [comment]
Thanks for the report.
Yes, they look like gears and there are six of them.
Unfortunately, without a Project File and the Cura log that's all I can tell from here.  The instructions are on the original page you filled out for this report.

**Comment by BLAI38** [comment]
I am sending you the link of a handheld fan grip, along with the gears for this project. Also, I want to let you know that I set it at 80% of the size, just in case. Thank you.

Best regards.
Link: https://cults3d.com/en/3d-model/tool/cool-squeeze-grip-fan

**Comment by BLAI38** [comment]
> I am sharing with you the hand fan grip link and gears project. Just a heads up, I've reduced it to 80% of the size. Also, I have attached the .log file. Thanks.
> 
> Best regards. Link: https://cults3d.com/en/3d-model/tool/cool-squeeze-grip-fan .log file: [cura.log](https://github.com/user-attachments/files/15524745/cura.log) "I have issues only with these files: GripFan_Wheel_2A GripFan_Wheel_2B GripFan_Wheel_3A GripFan_Wheel_3B GripFan_Wheel_4A GripFan_Wheel1
