### ISSUE TITLE
Unable to slice anything.... even calibration prints that I had just sliced and printed a few hours ago.

### ISSUE THREAD

**Issue by Dan-Kroll** [Ultimaker/Cura#19137]
### Cura Version

5.7.1 and 5.4.1

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

Using standard settings and standard start and end code

### Describe model location

No

### Describe your model

sinlgle layer calibration prints, vaces and ring part.

### Add your .zip here ⬇️

"Arrange all" caused the slicer to crash multiple times. I tried Cura 5.7.1 and Cura5.4.1 and the same issue has arisen for all the files I've uploaded.

**Comment by GregValiant** [comment]
Thanks for the report.
Since it's happening with two different versions something might have changed on your computer.  Try right-clicking on the desktop icon and select "Run as Administrator" and see if it will slice.
