### ISSUE TITLE
slicing will fail when you have an extension open  

### ISSUE THREAD

**Issue by Rudewolf300** [Ultimaker/Cura#19138]
### Cura Version

5.7.1

### Operating System

windows 11

### Printer

ender 3 v2

### Reproduction steps

it kept crashing then i looked it up and found a similar problem. the problem others had would be when trying to slice while having another of the apps window open. i noticed i had the thingyverse extension open every time it would crash so i closed it and tried to slice.

### Actual results

without the extension open it wont crash but with the extension open it is in consistent but will crash every time after the first crash. restarting my computer will stop it as well but just for a few slices 

### Expected results

i would think it wouldnt matter if i have other in-app windows open to slice things

### Add your .zip and screenshots here ⬇️

[Uploading CE3E3V2_PlaKit_HarryPotter_LOW.zip…]()

**Comment by GregValiant** [comment]
Thanks for the report.
I'm unable to duplicate this on Wn10.
Use the "Help | Show Configuration Folder" command to locate the "Cura.log" file.  Right after a crash happens go to that folder and zip the cura.log file and post the zip folder here.  The log file may give a clue.  This is the first report of this behavior so it isn't likely to be something that is happening to everyone.

The Cura team will take a look.
