### ISSUE TITLE
découpe erreur

### ISSUE THREAD

**Issue by Matthias6440** [Ultimaker/Cura#19160]
### Cura Version

5.6.0

### Operating System

WINDOWS 11

### Printer

flsun super racer

### Describe model location

il tranche quand il est pivoté de 180° (à l'envers, le toit sur le sol)

### Describe your model

il tranche quand il est pivoté de 180° (à l'envers, le toit sur le sol

### Add your .zip here ⬇️

![AA](https://github.com/Ultimaker/Cura/assets/171193286/884f4c66-5065-41ef-8736-50c6753715c7)

**Comment by GregValiant** [comment]
OK.
