### ISSUE TITLE
Sli

### ISSUE THREAD

**Issue by Icelamacplay** [Ultimaker/Cura#19164]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

Anycubic Kobra

### Describe your model

Medalion Kette

### Add your .zip here ⬇️

[valyrian-steel-pendant-the-house-of-the-dragon20220930-60-ubiidf.zip](https://github.com/Ultimaker/Cura/files/15496091/valyrian-steel-pendant-the-house-of-the-dragon20220930-60-ubiidf.zip)

**Comment by GregValiant** [comment]
You did not describe any problem and I don't see any problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/2e6e50ca-0c65-4fc3-96ec-695310fa4d63)

I'll go ahead and close this as there is no problem.
