### ISSUE TITLE
Gradual infill improvements

### ISSUE THREAD

**Issue by hoegge** [Ultimaker/Cura#1917]
The new gradual infill feature is really great. It would, though, make a lot more sense if you could also choose "distance to surface" as the parameter for when to half the infill, so you would get a uniform strength of your print. Not sure if that is easy to do or not

**Comment by BagelOrb** [comment]
You mean to the sides and to the bottom, rather than only the top?

Wouldn't be the easiest to implement... But doable. But if you want that you should look at cubic subdivision infill pattern.

**Comment by hoegge** [comment]
Thought it worked both to bottom and top. Yes - to all sides (in 3D). Similiar to Makerbot's I think

**Comment by BagelOrb** [comment]
Please take a look at cubic subdivision infill.

**Comment by ianpaschal** [comment]
As part of our new ticket handling strategy, we voted as a team on the likelihood of fixing this issue. Unfortunately, we’ve decided that we will not take time to fix it, and are marking it as `Status: Won’t Fix/Do` and closing the issue.
