### ISSUE TITLE
Elegoo cura failed slicing

### ISSUE THREAD

**Issue by Bananaduck308** [Ultimaker/Cura#19179]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 4 Plus

### Name abnormal settings

I have noticed that my models will slice fine if they are not using tree supports. As soon as I turn tree supports on, the slicing fails.

### Describe model location

Model doesn't slice at all with tree  supports

### Describe your model

I have sliced the model succuss before, but my klipper printer descovered an issue and wasn't able to continue printing after half way through the first layer.

### Add your .zip here ⬇️

[Cover_SamsungGalaxyS24ULTRA_HexagonDesign.zip](https://github.com/user-attachments/files/15536687/Cover_SamsungGalaxyS24ULTRA_HexagonDesign.zip)

**Comment by Asterchades** [comment]
Several issues with regards to tree supports were already corrected in Cura 5.7, which released on April 3. It's up to Elegoo to update their own branch of the software to incorporate those fixes - neither Ultimaker nor the Cura team has any control over third parties.
