### ISSUE TITLE
CURA 2.5.0. cant save to removable drive

### ISSUE THREAD

**Issue by SpatsS7** [Ultimaker/Cura#1918]
Win 10 saves as .gcode without the file name to removable disk. If saving to file, filename has to be determined. Doesnt read filenames from stl projects and in the folowing - printer wont read filename from the card. Also projects show up upon deleting as 0 bytes athou they weigh more than 50 MB. maybe its a size issue..

when trying to drag and drop this file after slicing to Gcode file says it is hidden so i can not upload it here. It doesnt matter if the file is old or new from thingverse or designed on spot. 

This is a slicer to removable drive issue.

**Comment by fieldOfView** [comment]
This has been fixed in Cura 2.6 beta
