### ISSUE TITLE
Starting Cura Makes Bluetooth heaphones flap (connect and disconnect) until cura closed.

### ISSUE THREAD

**Issue by hossimo** [Ultimaker/Cura#19195]
### Cura Version

5.7.2

### Operating System

Windows 11

### Printer

AnyMax Stock

### Reproduction steps

- Connect Bluetooth headphones to Windows PC
- Start Cura, tested with 5.4 and 5.7.2
- Once Cura has started the bluetooth headphones will connect then disconnect over and over about 1once every second until Cura is exited.

### Actual results

Now that I figured out why it happens its very reliable. as soon a cura starts headphones flap, as soon as cura is quit the flapping stops and everything is normal again.

I tried to screen the phanonanum but as soon as I started OBS the issue stops and the headphones stayed connected as expected, I'll try rebooting and recording my display with my phone.

### Expected results

Headphones should not be affected.

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/user-attachments/files/15653035/cura.log)

**Comment by hossimo** [comment]
Here's a video of it happening.


https://github.com/Ultimaker/Cura/assets/1986602/80fe9852-9b7e-4556-8736-cb3ae96862b2


One time when trying to film it with my phone I accidentally started three instances of the application then it stopped happening for about 20 minutes. then I was able to make it happen reliably again.

Of all the applications on my machine this is the only one that causes the flapping to happen.

**Comment by GregValiant** [comment]
Thanks for the report.
Cura has the USB Printing plugin enabled by default.  It automatically polls the ports by sending a Gcode command and waiting for a proper response.

- Go to the Cura MarketPlace.
- Click on the "Gear" icon.
- Scroll down to "USB Printing" and disable it.
- Click on the exit button and then restart Cura.

I'll leave the bug label on this for now.  Let me know if disabling the plugin fixes the problem.

**Comment by hossimo** [comment]
That was exactly it, I was thinking that maybe the earbuds were presenting a uart or something but looking through the preferences I didn't see anything about usb connections. seems like that should be a preference in the UI but thanks so much for point me to it.

I'll close this up since it really wasn't a bug.


Thanks for the help!
