### ISSUE TITLE
Cura not slicing 

### ISSUE THREAD

**Issue by Aether1777** [Ultimaker/Cura#19191]
### Cura Version

5.7.2

### Operating System

Windows 11, 4090, i9 14900k, 64 gig of ram

### Printer

ender3 v2

### Name abnormal settings

default profile

### Describe model location

no changes to location

### Describe your model

i sliced it on a older laptop using same settings and version

### Add your .zip here ⬇️

[CE3E3V2_FM7UD6WIWMQUV05.zip](https://github.com/user-attachments/files/15604566/CE3E3V2_FM7UD6WIWMQUV05.zip)
I recently had to reset my pc but before that when slicing it would cause a BSOD

**Comment by GregValiant** [comment]
Thanks for the report.
The model doesn't appear to have any errors and it sliced fine on my Win10 system.
The Cura team will take a look.
When you get a minute, recreate the problem in Cura and then use the "Help | Show Configuration Folder" command.  In that config folder will be "Cura.log".  Zip that log file and post the zip folder here.  Maybe it will have a clue.
In 4 years of doing triage here, this is the first bug report I've seen where a Cura crash also crashed Windows to a blue screen.

Your current support settings are using a lot of material and taking a long time.  When you get it to slice you can knock a couple of hours off the print time by considering some changes.
Support Overhang Angle - 60°
Support Density - 10%
Support Infill Layer Thickness - 2X Layer Height (0.40)
Support Distance Priority - Z overrides XY
Minimum Support Interface Area - 1.0

![image](https://github.com/Ultimaker/Cura/assets/64202104/a37b7b33-6650-45cd-a7d4-ca1a0c1f1759)

**Comment by Aether1777** [comment]
[logs.zip](https://github.com/user-attachments/files/15696225/logs.zip)
here are the logs

**Comment by Aether1777** [comment]
Ok i figured it out there was a issue with intel 13th and 14th gen cpus that caused instability and crashes a bios update by gigabyte that literally just released fixed that problem i installed and revert to defaults and everything works now thanks!

**Comment by GregValiant** [comment]
Thanks for that.
I'll go ahead and close this.

@HellAholic this is something I hadn't heard.

**Comment by HellAholic** [comment]
@GregValiant technically you can get any program to cause a BSOD by overclocking the system to an unstable state, but it's then  the system instability that is causing the issue rather than the program. It is a fun side of the overclocking hobby - if you will - that comes with building computers. It's entirely out of the context of 3D printing but using a benchmark tool for CUP & GPU after doing bios updates/changes or overclocking is usually best practice.
But thanks for the poke, I'll keep this in mind as well :)

**Comment by GregValiant** [comment]
This is similar to #19185 and the same fix (update to bios) worked to eliminate the problem.

**Comment by Aether1777** [comment]
Yep ik (im kinda the person that figured it out)
