### ISSUE TITLE
Cura 5.7.1 will not slice single layer object

### ISSUE THREAD

**Issue by eSonOfAnder** [Ultimaker/Cura#19196]
### Cura Version

5.7.1

### Operating System

Windows 11 Home, Ryzen 9 5900x CPU, 32 GB DDR4 RAM, RTX 2080 Super GPU

### Printer

Ender 3 v2

### Reproduction steps

1. Add single layer object to build plate
2. Verify Z heigh of object is the same as the layer height (in this instance, 0.2 mm)
3. Slice

### Actual results

Produces an empty slice with no output

### Expected results

The object should be printed as as, at a single layer. If you do an adjustment of the object's scale within Cura to make the Z height slightly more than the initial layer height, in this example 0.21 mm, then it will slice correctly. This was apparently a bug that had been squashed in a much earlier version of Cura, but it appears to have been reintroduced at some point.

### Add your .zip and screenshots here ⬇️

![Single Layer Object on Plate](https://github.com/Ultimaker/Cura/assets/4420108/3053ed7f-a8e9-4653-8b90-83ebfb01c7b0)
![Single Layer Slice Time](https://github.com/Ultimaker/Cura/assets/4420108/3023921a-2abf-4972-a5a1-6cd4d3360019)
![Single Layer Slice Preview](https://github.com/Ultimaker/Cura/assets/4420108/a48d3caf-8fbe-4f39-9871-c54b06057bf6)
![Increased Object Height](https://github.com/Ultimaker/Cura/assets/4420108/62b32334-a83d-4ad1-8e98-30848ab8c2f8)
![Increased Object Height Slice Estimate](https://github.com/Ultimaker/Cura/assets/4420108/691632fc-7f87-4c77-871c-846d5d945c0c)
![Increased Object Height Slice Preview](https://github.com/Ultimaker/Cura/assets/4420108/413ba4b9-d9ac-4535-9825-42a98fea1a8b)

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate the problem in either 5.7.1 or 5.7.2..
Please provide a project file.  Without knowing how you have set up the slice there can't be an investigation.

This is 0.20 thick with a 0.20 Initial Layer Height.  I get the same results with a 0.1 model and 0.1 layer height.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b97d03a8-0b60-4fc3-9975-8b636831f328)
