### ISSUE TITLE
Hexagon with 30° not filled

### ISSUE THREAD

**Issue by Mnanfiodkfna** [Ultimaker/Cura#19207]
### Cura Version

5.3.1 and 5.7.2

### Operating System

macOS Monterey

### Printer

Anycubic Chiron

### Reproduction steps

I created a STL-file which has two hexagons with an angle of 30° to the ground plate.
I sliced the STL file with Cura.
[Xiaomi_Halter.stl.zip](https://github.com/user-attachments/files/15754466/Xiaomi_Halter.stl.zip)

### Actual results

The hexagons are not filled from Cura.

### Expected results

The hexagons should be filled.
Other slicers for example REXprint fill the 30° hexagons.
![Bild 10 06 24 um 01 06](https://github.com/Ultimaker/Cura/assets/109997272/45441b96-44f3-4690-8497-cad7f3a5b7a6)

### Add your .zip and screenshots here ⬇️

See screenschot
![Bild 10 06 24 um 01 06](https://github.com/Ultimaker/Cura/assets/109997272/47ad89f1-e2c0-45e8-89d1-276cb10b441e)

**Comment by GregValiant** [comment]
You have "Infill Support" turned on so it's only building infill to hold up the roof.
