### ISSUE TITLE
Slicing Failed dialogue (Report a bug) when using Support Structure: Tree instead of Normal. 

### ISSUE THREAD

**Issue by GunnerNelson** [Ultimaker/Cura#19208]
### Cura Version

5.6.0 (Elegoo Cura)

### Operating System

Windows 10 Pro

### Printer

Elegoo Neptune 3 (slicer is Elegoo Cura)

### Reproduction steps

1. Changed Support Structure from Normal to Tree. 
2. Clicked Slice Button

### Actual results

Pop-up window: Slice Failed, Report a bug

### Expected results

Successful slice

### Add your .zip and screenshots here ⬇️

[EN3_syn8_Throat_NoPorts.zip](https://github.com/user-attachments/files/15755251/EN3_syn8_Throat_NoPorts.zip)

**Comment by GregValiant** [comment]
This is the UltiMaker Cura bug reporting site.  For problems with other versions you need to contact the version admins (in this case Elegoo).
