### ISSUE TITLE
json 'str' issue in Post-Processing Plugins

### ISSUE THREAD

**Issue by ZhuDaHai** [Ultimaker/Cura#1921]
Using the following structure in getSettingDataString, does not function as expected:
```

                "line1":
                {
                    "label": "First Line",
                    "description": "First Inserted Line",
                    "type": "str",
                    "default_value": "This",
                    "enabled": true
                },
```

If the field is initialized (default_value) with alpha characters, then additional alpha characters can be entered (abc / Thor / bifrost / happy), however:
- If field is initialized as blank (""), then only numeric characters can be entered (123 / 0.13 / 2,145)
- If field alpha character contents are deleted, then only numeric characters can be entered.
- If field is initialized with numeric characters, then only numeric characters can be entered.
- Only 10 alphanumeric characters can be entered in total into the field.

**Comment by ZhuDaHai** [comment]
P.S: 
Windows 10 Professional (64bit)
Cura 2.5.0 Release

**Comment by nallath** [comment]
String type is not really supported. As far as I know there is a fallback that sorta tries to make it work, but thats about it.

**Comment by Ghostkeeper** [comment]
It works in the Search-And-Replace script: https://github.com/nallath/PostProcessingPlugin/blob/master/scripts/SearchAndReplace.py#L25

**Comment by Ghostkeeper** [comment]
Ah, but you have to use 2.6. I made some changes to 2.6 to implement Search-and-Replace to allow this sort of thing.
