### ISSUE TITLE
adding a new printer

### ISSUE THREAD

**Issue by rdailey20** [Ultimaker/Cura#19221]
### Cura Version

5.4

### Operating System

widows 11

### Printer

qidi xmax3

### Reproduction steps

when i try to add the Qidi xmax 3 printer the app just closes i tried uninstalling program and re downloading it and i also restarted computer nothing seems to work

### Actual results

app still closes

### Expected results

needs to be patched so that i can add my 2 xmax3 qidi printers

### Add your .zip and screenshots here ⬇️

cant screen shot an app closing

**Comment by GregValiant** [comment]
Thanks for the report.
From what I can see, the QIDI printers aren't directly supported by UM Cura.  That could just mean that there are no "official" definition files as I see some people are using them with Cura.
If you are trying to install definition files you received from somewhere there may be errors in the files.  You might want to go back to the source and discuss this.  Errors in the definition files can keep them from loading and Cura will crash.

You can try to install a Custom FF printer and set it up with whatever your printers actually need (bed size, firmware flavor, etc.).  The "Custom FF" is the generic printer in Cura.

I'm inclined to remove the bug label from this.  If no one has ever submitted the definition files for the QIDI Max3 then that's likely why it isn't supported.
