### ISSUE TITLE
Bug a cut

### ISSUE THREAD

**Issue by nzpij** [Ultimaker/Cura#19239]
### Cura Version

5.7.1

### Operating System

windows 11

### Printer

ender 3 v3se

### Reproduction steps

vérification de la mise a jour 

### Actual results

recherche de nouvelle version
changement de fichier importé
passage sur un slicer concurrent : ok

Coupure de fichier interne pour test non fonctionnel

### Expected results

finalisation du tranchage

### Add your .zip and screenshots here ⬇️

https://we.tl/t-NCyvN2o6V9

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate this on my Windows 10 laptop.  There have been several reports made in regards to slicing errors on Windows 11 systems.
Use the "Help | Show Configuration Folder" command and you will find the Cura.log file.  Please post that file here.  It may provide a clue.
I'll mark this as a duplicate and the Cura team will take a look.
