### ISSUE TITLE
Checksum mismatches

### ISSUE THREAD

**Issue by Hoverhead** [Ultimaker/Cura#1925]
While 2.6.0-Beta generated code with Printerface, these messages were sent.
Faulty file attached, zipped

"Error:checksum mismatch, Last Line:4
[ERROR] Error:checksum mismatch, Last Line:4

Resend:5
echo:Unknown command:""
Error:Line Number is not Last Line Number+1, Last Line:10714
[ERROR] Error:Line Number is not Last Line Number+1, Last Line:10714

Resend:10715
o
echo:Unknown command:""
Error:Line Number is not Last Line Number+1, Last Line:24586
[ERROR] Error:Line Number is not Last Line Number+1, Last Line:24586

Resend:24587"

[CD_Support_moteur_Slic3r_concentric.gcode.zip](https://github.com/Ultimaker/Cura/files/1047679/CD_Support_moteur_Slic3r_concentric.gcode.zip)

**Comment by nallath** [comment]
Who's errors are those? Those don't seem to be errors created by Cura.

**Comment by Ghostkeeper** [comment]
The lines in question seem to be correct. For instance, here are lines 24586 and 24587 from your file:

    G1 X96.918 Y122.16 E493.3385
    G0 F675 X97.068 Y121.98

Looks normal. Perhaps Pronterface is doing something wrong.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by Ghostkeeper** [comment]
I'm thinking this was never an issue with Cura itself.
