### ISSUE TITLE
Slicing failed only on 3 extended printer

### ISSUE THREAD

**Issue by gsto1987** [Ultimaker/Cura#19255]
### Cura Version

5.7.0

### Operating System

Windows 10 Enterprise, Intel i7, 32GB Ram, RTX 3500

### Printer

3 Extended

### Name abnormal settings

default settings

### Describe your model

Yes, slices fine on S5

### Add your .zip here ⬇️

[New folder.zip](https://github.com/user-attachments/files/15901011/New.folder.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file there is no way to tell how you set up the slice.  I didn't have any trouble slicing this and there doesn't appear to be any errors in the model.
I don't know how you had it oriented but I laid it down to slice it.
![image](https://github.com/Ultimaker/Cura/assets/64202104/d9967d9a-10fe-49f7-b804-4f5b843d2740)
