### ISSUE TITLE
No hay modelos en el archivo (.3mf)

### ISSUE THREAD

**Issue by Gschlund** [Ultimaker/Cura#19261]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

Hellbot Magna 2 300

### Reproduction steps

1. Arrastre el archivo que quería en formato .3mf
2. Me salta el error "no hay modelos en el archivo"

### Actual results

No se carga el archivo

### Expected results

Cargar el modelo para poder slice

### Add your .zip and screenshots here ⬇️

![Captura](https://github.com/Ultimaker/Cura/assets/97751348/f45523c2-6873-45bd-9a3f-b8b45aab110f)

**Comment by GregValiant** [comment]
Thanks for the report.
That can happen when the 3mf file was put together incorrectly or if it is corrupted in some way.
This is something that happened before Cura got the file so it isn't a Cura problem.  I open a lot of 3mf files and this does happen occasionally.  The fault is with the file, not Cura.
I'll remove the bug label and close this.  You need to go back to wherever the file came from and ask for help there.
