### ISSUE TITLE
se ha producido un error inesperado al realizar el corte

### ISSUE THREAD

**Issue by israel1527** [Ultimaker/Cura#19277]
### Cura Version

5.4.0

### Operating System

windows 11

### Printer

ender 2 pro

### Name abnormal settings

no

### Describe model location

central

### Describe your model

primera vez

### Add your .zip here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/173626602/c364a615-6c3f-4b3c-aba3-8afd3817ef26)

**Comment by GregValiant** [comment]
Thank you for the report.
Without a Project File and the Cura.log file there can be no investigation.  The instructions are on the page you filled out for this report.
