### ISSUE TITLE
crashed while slicing with 0.6 nozzle

### ISSUE THREAD

**Issue by SchwartzMonster** [Ultimaker/Cura#19274]
### Cura Version

5.7.2

### Operating System

windows 11

### Printer

cr-10 s

### Name abnormal settings

no

### Describe model location

center

### Describe your model

sink caddy

### Add your .zip here ⬇️

[Sink_Tray.zip](https://github.com/user-attachments/files/15938348/Sink_Tray.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The STL file doesn't appear to have any errors and it sliced fine for me on Win10 using 5.7.2.
Please post a project file and the Cura.log file (the instructions are on the page you filled out for this report.)
