### ISSUE TITLE
Unexpected slice fail

### ISSUE THREAD

**Issue by John-Fallout** [Ultimaker/Cura#19276]
### Cura Version

5.2.1

### Operating System

Windows 11

### Printer

Anycubic Kobra Plus (I had to enter the specifics manually. The printer isn't listed in cura)

### Describe model location

0, 0, 0

### Describe your model

T-45 Power helmet, Front Left Face, probably not watertight, hasn't successfully sliced before.

### Add your .zip here ⬇️

[T-45-FLF (1).zip](https://github.com/user-attachments/files/15942341/T-45-FLF.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
5.2.1 was 9 versions ago.
I don't see any problems with the model you uploaded.  It appears to be watertight and MS 3D Builder didn't find any other errors.  I sliced for me in 5.7.2 with Tree supports turned on.
I suggest you upgrade your Cura installation.  If you have an ABL use version 5.7.1.  Without an ABL 5.7.2 is fine.  (There is a bug in 5.7.2 that always adds the heating commands before the StartUp Gcode and that can cause oozing during the leveling process.)

I'll go ahead and close this as the problem doesn't appear to exist in the latest Cura versions.
