### ISSUE TITLE
when cutting large models there is a bug

### ISSUE THREAD

**Issue by jorgecohen** [Ultimaker/Cura#19272]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

artillery hornet

### Describe your model

mantaray 

### Add your .zip here ⬇️

i didnt understand

**Comment by GregValiant** [comment]
Thanks for the report.
5.5.0 and 5.6.0 had trouble slicing "organically" shaped models which I assume your Manta Ray is.  It was a well known bug and was addressed in later releases.
I suggest you upgrade to 5.7.1.

I'll mark this as a duplicate and go ahead and close it.  I hope you understand.

**Comment by jorgecohen** [comment]
Oh there is a new version? OK so I will upgrade

בתאריך שבת, 22 ביוני 2024, 11:59, מאת GregValiant ***@***.***
