### ISSUE TITLE
Failed to slice multiple parts but slices same single part

### ISSUE THREAD

**Issue by mfransch** [Ultimaker/Cura#19282]
### Cura Version

5.7.2

### Operating System

windows 11

### Printer

Ultimaker S7

### Describe model location

2 parts centralised 

### Describe your model

no

### Add your .zip here ⬇️

[05-101-001-A 2mm.zip](https://github.com/user-attachments/files/15963618/05-101-001-A.2mm.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a "Cura Project File" there can be no investigation.
