### ISSUE TITLE
flower without tree suport

### ISSUE THREAD

**Issue by argetlarm** [Ultimaker/Cura#19291]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic cura

### Describe your model

flower 

### Add your .zip here ⬇️

[flower 1.0 - 1090657.zip](https://github.com/user-attachments/files/15990935/flower.1.0.-.1090657.zip)

**Comment by GregValiant** [comment]
Please upgrade to Cura 5.7.1.  5.6.0 had slicing issues that seem to have been fixed.
