### ISSUE TITLE
2.5.0 infill settings not working with 100 % infill

### ISSUE THREAD

**Issue by Fass-ohne-Hoden** [Ultimaker/Cura#1929]
When I set infill density to 100 %, the infill line directions setting has no effect. Instead, top/bottom line directions are used for the whole piece. Also, the whole piece is displayed in the top/bottom colour (yellow instead of orange).

Dirty fix: sett infill density to 99 % ... but, you know ... it's dirty

**Comment by smartavionics** [comment]
You need to set an explicit value for "Bottom Layers" because when the infill density is 100%, bottom layers defaults to a silly large number.

**Comment by Fass-ohne-Hoden** [comment]
Thanks a lot! That helped.

It is still a bug, considering I had top/bottom thickness set to a value that didn't equal 9999999 (not sure how many 9s there were) bottom layers ...

**Comment by fieldOfView** [comment]
Or set infill percentage to 99

**Comment by Ghostkeeper** [comment]
Or even 101%.
