### ISSUE TITLE
slicing fail

### ISSUE THREAD

**Issue by bobthebold09** [Ultimaker/Cura#19307]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

elegoo neptune 3 pro

### Name abnormal settings

no

### Describe model location

no

### Describe your model

i have not sliced it successfully, it is watertight    

### Add your .zip here ⬇️

[EN3PRO_2 Step v2.zip](https://github.com/user-attachments/files/16037271/EN3PRO_2.Step.v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You should upgrade to 5.7.1.  These slicing errors were a well known bug in 5.5 and 5.6.
I'll mark this as a duplicate report and close it since it seems to have been fixed in later versions.
