### ISSUE TITLE
Release candidate or final release / 5.7.2-RC or 5.7.2 ?

### ISSUE THREAD

**Issue by Rotzbua** [Ultimaker/Cura#19305]
### Cura Version

5.7.2-RC2?

### Operating System

win11

### Printer

-

### Reproduction steps

Compare release version and github tag.

### Actual results

The github tag: [5.7.2-RC2](https://github.com/Ultimaker/Cura/tree/5.7.2-RC2)
The release version: 5.7.2

### Expected results

Consistent version and clear definition of whether it is a release candidate or a final release.

### Add your .zip and screenshots here ⬇️

![grafik](https://github.com/Ultimaker/Cura/assets/7337347/4baf7d9b-4221-4afd-b3eb-a69602484fbc)

**Comment by wawanbreton** [comment]
Hi @Rotzbua,

Well you're right, during the 5.7.2 I made a mistake that made the "RC2" tag visible. I was trying a new process and didn't expect this to happen.
The RC tag should not be directly visible, and it should no more be the case for next releases.
