### ISSUE TITLE
Opening STL immediately after starting Cura results in infinite slicing loop

### ISSUE THREAD

**Issue by ElijahCuff** [Ultimaker/Cura#19344]
### Cura Version

5.7.2

### Operating System

Windows 10

### Printer

Anycubic Kobra 2

### Describe your model

Cross with hole for Pool Que

### Add your .zip here ⬇️

[Uploading AK2_snookerX.zip…]()

**Comment by GregValiant** [comment]
Thanks for the report.
That zip file didn't upload correctly and the link just bounces back to this page.  If you didn't include the log file, please do and then try again.

**Comment by zhou123aw** [comment]
Have you solved this problem? I am also in the same situation too

**Comment by GregValiant** [comment]
I can't investigate because @ElijahCuff 's uploaded file is glitched.  We have nothing to look at.
We need a Project File "zipped" and please include the Cura.log file.
