### ISSUE TITLE
Cura crashes on OSError 28/No space left on device

### ISSUE THREAD

**Issue by supermanny81** [Ultimaker/Cura#1934]
Maybe better to be reported in the Uranium repository.   As the description says, Cura crashes with an uncaught exception when the SD card is full.

![error 28](https://cloud.githubusercontent.com/assets/1137338/26766745/714dc886-494c-11e7-9e3c-e7e2d37281c1.png)

**Comment by nallath** [comment]
Nice find!

**Comment by nallath** [comment]
Fixed for next release.
