### ISSUE TITLE
cura 5.7.2 fails to slice 

### ISSUE THREAD

**Issue by keramade** [Ultimaker/Cura#19354]
### Cura Version

5.7.2

### Operating System

windows 10

### Printer

aquila X2

### Name abnormal settings

support, from normal to tree

### Describe model location

have not tried that

### Describe your model

 no , no and no

### Add your .zip here ⬇️

Aquila_X2_tool_hdr.zip](https://github.com/user-attachments/files/16156173/Aquila_X2_tool_hdr.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The model seems to be fine and the project sliced for me without any problems.
Use the "Help | Show Configuration Folder" command.  In that folder will the Cura.Log.  Please zip that file and post it here and maybe it will provide a clue as to what is happening on your system.
The Cura Team will take a look.
![image](https://github.com/Ultimaker/Cura/assets/64202104/fa7260e8-cec4-4801-b291-d5c773590b6b)
