### ISSUE TITLE
supports not generating

### ISSUE THREAD

**Issue by vadimvladimirovichchernov** [Ultimaker/Cura#19381]
### Cura Version

5.7.2

### Operating System

macos

### Printer

ultimaker 2+ connect

### Reproduction steps

1.placed a file that requires support 2.checked the supports section

### Actual results

![Screenshot 2024-07-14 at 09 23 53](https://github.com/user-attachments/assets/6040938b-28bf-42e9-a01e-a54bb512d4fc)

### Expected results

supports should have been generated

### Add your .zip and screenshots here ⬇️

![Uploading Screenshot 2024-07-14 at 09.23.53.png…]()

**Comment by GregValiant** [comment]
Thanks for the report.
We need a Cura Project file to investigate this.  Use the Save Project command, zip the file, and post the zip folder here.
In the mean time, click on "Color Scheme" and make sure "Helpers" is enabled.
![image](https://github.com/user-attachments/assets/766c34b1-8cf6-4caa-89b5-12df19dcc6d0)

![image](https://github.com/user-attachments/assets/812172f6-10e2-4bc1-a71e-719240a48d82)
