### ISSUE TITLE
"Initial Layer Printing Speed" does not work as supposed to be

### ISSUE THREAD

**Issue by 369Martin369** [Ultimaker/Cura#19382]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Core XY (HevORT)

### Reproduction steps

Normal slicing with option "Initial Layer Printing Speed" enabled and speed set to 20mm/s

### Actual results

Green layer speed supposed to be blue ...thought this is setting "initial Layer Printing Speed", but as you can see, in color scheme, it is green (around 50mm/s).
![image](https://github.com/user-attachments/assets/743fa507-5a80-41d3-ad93-e896da8f342e)

### Expected results

The Circles should be slow speed like it is done in Bambu Studio...makes no sense to ignore "Initial Layer Printing Speed"
![image](https://github.com/user-attachments/assets/45a7381a-27ef-4a49-be0f-ee09d32e5f92)

### Add your .zip and screenshots here ⬇️

[knobel.zip](https://github.com/user-attachments/files/16227915/knobel.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That was a bug in 5.5 which is 4 versions behind.  The bug has been fixed in current versions.
I'll mark this as a duplicate and close it.
This is in 5.7.2.
![image](https://github.com/user-attachments/assets/40e90f89-502f-421a-9699-76e155be1991)
