### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by companycmd** [Ultimaker/Cura#19399]
### Cura Version

5.7.0

### Operating System

windows 10x

### Printer

on startup; no printer selected yet

### Reproduction steps

started program  
![image](https://github.com/user-attachments/assets/daea190f-3c3d-482e-8fca-6e13581066de)

### Actual results

program starts with no known issues

### Expected results

startup without runtime error

### Add your .zip and screenshots here ⬇️

![image](https://github.com/user-attachments/assets/3d3e531c-28d2-4055-a933-20774244e9e9)
![runtime error](https://github.com/user-attachments/assets/2931cb17-5ded-42e0-9e87-2f4cb6bf1457)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.8 beta-1 has been released and I suggest you upgrade to it.  5.7.0 is 3 versions behind the current version.

This problem has not been previously reported for 5.7.0 so I'll leave the bug label on it but I'm going to close this as being for an out-of-date version.  If you still have the problem with 5.8 let us know and I will re-open this.  I hope you understand.
