### ISSUE TITLE
Error de slicing en Cura 5.6

### ISSUE THREAD

**Issue by GPCsoftware** [Ultimaker/Cura#19400]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Hellbot Magna 2 230

### Name abnormal settings

Capas adaptativas

### Describe your model

iiii

### Add your .zip here ⬇️

[1.zip](https://github.com/user-attachments/files/16315504/1.zip)
![1](https://github.com/user-attachments/assets/61f18c90-455f-4dd7-86e8-f49e438c1e03)
![2](https://github.com/user-attachments/assets/06372112-5532-4330-b84a-23113a555247)
![3](https://github.com/user-attachments/assets/47e81934-e0ce-493c-8b34-dc0a7c1cbdf8)

**Comment by LilBub** [comment]
Let me try via Google Translate

Just trying to be helpful posting here; have you tried the newer version of Cura, 5.7.2?  Also, you file contains only screenshots.  A project file would be useful.

Solo intento ser útil publicando aquí; ¿Has probado la versión más nueva de Cura, 5.7.2?  Además, su archivo contiene solo capturas de pantalla.  Un archivo de proyecto sería útil.

**Comment by GregValiant** [comment]
Cura 5.6.0 is 4 versions behind.  The Cura 5.8 beta appears to be very good and does not have the slicing issues that 5.5 and 5.6 had.
