### ISSUE TITLE
Incomplete raft path

### ISSUE THREAD

**Issue by andreikovari** [Ultimaker/Cura#19404]
### Cura Version

5.3.0

### Operating System

Windows 10

### Printer

Artilllery Sidewinder X1

### Reproduction steps

1. Import object
2. Slice object
3. Preview result

### Actual results

The generated raft has an incomplete path.
![image](https://github.com/user-attachments/assets/f4bd55b6-f3f9-4236-b991-c8ec3cf8869b)
![image](https://github.com/user-attachments/assets/4562e1f9-b3c7-47dc-b14b-f35d554da3c0)
![image](https://github.com/user-attachments/assets/efef1f06-b3cd-4eb4-8268-0b2e1fafbd7e)

### Expected results

Raft generated normally.

### Add your .zip and screenshots here ⬇️

STL of file attached
[3030to2020.zip](https://github.com/user-attachments/files/16321104/3030to2020.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This was a known bug in 5.3 and it has been fixed in later versions.
I'll mark this as a duplicate and go ahead and close it.  5.8 beta is out and appears to be very good.
