### ISSUE TITLE
Error en la informacion de los tiempos

### ISSUE THREAD

**Issue by secheve** [Ultimaker/Cura#1941]
![image](https://cloud.githubusercontent.com/assets/29232405/26835898/aa302796-4ad9-11e7-8827-70a287b7fdca.png)

**Comment by ChrisTerBeke** [comment]
Closing since we cannot reproduce and no further information has been provided. Please comment if this is still an issue for you.

**Comment by Ghostkeeper** [comment]
Looks like this is a duplicate of #1912 actually. Please look there for more conversation.
