### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by AGUFER04** [Ultimaker/Cura#19426]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

Hellbot Magna SE

### Reproduction steps

I upload a file and click on "slice"

### Actual results

It fails in the slicing

### Expected results

The program should give me de GCODE

### Add your .zip and screenshots here ⬇️

![Captura de pantalla 2024-07-24 112436](https://github.com/user-attachments/assets/23f7b6e3-d9c4-4411-8823-a758a38379bc)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 did struggle with "organic" shapes and those seem to qualify.
5.6 is 4 versions behind now.  I would suggest upgrading to 5.8 beta-1.  It's much improved.
I'll mark this as a duplicate and go ahead and close this as the problem appears to have been addressed in more recent versions.  I hope you understand.
