### ISSUE TITLE
Error en el inicio de cura 2.6.0

### ISSUE THREAD

**Issue by secheve** [Ultimaker/Cura#1942]
para iniciar cura exige poner una tarjeta SD en el PC
y luego no imprime con USB si no se quita la tarjeta SD

**Comment by Ghostkeeper** [comment]
¿Hablo Inglés?

Starting Cura doesn't require an SD card. What error are you getting?

You can still print via USB if there is an SD card in the computer: just click on the little arrow next to the save button.

**Comment by secheve** [comment]
Starting cura, if the sdcard is not in, I get the error saying there is no sdcard.
Then I plug the card, cuts starts and then I need to remove it, otherwise I cannot print through usb
--
Enviado desde mi móvil a través de Mail.Ru sábado, 10 junio 2017, 11:00p. m. +02:00 de Ghostkeeper  notifications@github.com :

**Comment by Ghostkeeper** [comment]
I can't reproduce this.

Starting Cura without SD card works fine.

Printing via USB cable works fine too. Tested using an UM2+ (and changing the g-code flavour to RepRap).

Printing via USB still works when there's an SD card inserted. But you have to click the arrow besides the print button first to select USB printing.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?
