### ISSUE TITLE
Hang on load model

### ISSUE THREAD

**Issue by ernestp** [Ultimaker/Cura#19420]
### Cura Version

5.8.0-beta1

### Operating System

MacOS Sonoma 14.5

### Printer

Creality Ender 3 V2

### Reproduction steps

1. Start Cura
2. Drag n drop model to a plate

### Actual results

Cura hangs forever with high CPU usage

While previous version (5.7.0) loads model fine

### Expected results

Cura loads and display model

### Add your .zip and screenshots here ⬇️

https://drive.google.com/file/d/1h1_0mcfrQwTF5k5WB53Icys7qQROD5Gt/view?usp=sharing 

(File size too big to attach here: 25 MB are allowed, 197 MB were attempted to upload.)

**Comment by GregValiant** [comment]
Thanks for the report.
Go to the MarketPlace and click on the "Gear" icon.  Scroll down and disable "USB Printing".  There have been reports that loading files has been impacted by USB printing if there are additional USB devices plugged into the computer and the devices are configured as "serial" devices.
Let us know if that helped or not.
