### ISSUE TITLE
Turn off printer name on saving file does not work

### ISSUE THREAD

**Issue by donaldv9** [Ultimaker/Cura#19433]
### Cura Version

7.7.1

### Operating System

windows 10

### Printer

Elegoo Neptune 3 pro

### Reproduction steps

1. Unchecked; add machine prefix to job name

### Actual results

saved file and it still added the machine prefix to the job name even though it does not show on the bottom left of screen.

### Expected results

Saving the file should not have the machine prefix added to the job name when it is unchecked in preferences.

### Add your .zip and screenshots here ⬇️

![2024-07-25](https://github.com/user-attachments/assets/7ee06d59-aaa8-4b6e-99c5-ef39181bee89)
![Cura machine name error](https://github.com/user-attachments/assets/d77af351-902a-4ca3-b66a-22a6cee1bf71)

**Comment by donaldv9** [comment]
Made an error on the version number. It is 5.7.1

**Comment by donaldv9** [comment]
![machine prefix error second example](https://github.com/user-attachments/assets/939ce2e2-4e2b-4766-b45b-11ab8ddc8437)

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate this.  I have the same printer and I tried with 5.7.1 on a Win10 system.  It's a setting I always disable and I've never had a problem with it.
The Cura.log file is in your Configuration Folder.  Zip it and post it.  It might have a clue as to what is stuck on your system.

**Comment by donaldv9** [comment]
Thank you Greg for your help. I have the Cura.log file attached in zip format as you requested.

Donald Velasco
________________________________

**Comment by GregValiant** [comment]
Sorry but attachments don't work via email.  They must be posted directly to the site (Github rules).

**Comment by donaldv9** [comment]
[curalog.zip](https://github.com/user-attachments/files/16395505/curalog.zip)

Sorry Greg, here it is.

**Comment by GregValiant** [comment]
We're having a heck of a time here.  The zip folder is empty.

**Comment by donaldv9** [comment]
[cura.zip](https://github.com/user-attachments/files/16397444/cura.zip)

on my end it shows the size as 273kb in zipped format. not sure what happened the first time but this should work. Thanks Greg!

**Comment by GregValiant** [comment]
Got it.
There are a lot of warnings that I'm not familiar with.  You have several plugins installed as well.  Maybe a plugin like "MakerBotWriter" didn't receive the setting change regarding the file name prepend.

@HellAholic of the Cura team will take a look.

**Comment by donaldv9** [comment]
Thank you so much Greg and Hellaholic for your help persistence on getting this resolved. I have removed the plugin and it is now working perfectly! You all are an amazing team and I am so grateful for all your help!

**Comment by donaldv9** [comment]
![Capture](https://github.com/user-attachments/assets/639669ea-5913-4a0b-b826-b310aa2cdbc0)
showing that it is fixed.

**Comment by GregValiant** [comment]
Thanks guys.  I'll go ahead and close this.
