### ISSUE TITLE
Wipe routine not working sv04

### ISSUE THREAD

**Issue by SR2205** [Ultimaker/Cura#19448]
### Cura Version

5.7.2

### Operating System

Windows 10

### Printer

Sovol sv04

### Reproduction steps

When using the wipe settings, my extruder moves almost to the wipe bumper but not quite, then immediately returns to printing. It does not actually wipe, and it doesn't cycle over the brush repeatedly like it is told to in the settings. I have retraction wipe on, and retraction off so they do not conflict. 

[cu_petg_7-29-24.csv](https://github.com/user-attachments/files/16417534/cu_petg_7-29-24.csv)

### Actual results

the nozzle does not reach the wipe brush, nor execute the wipe movements. 

### Expected results

should wipe nozzle on brush several times

### Add your .zip and screenshots here ⬇️

screen shot not needed, printer settings submitted in another field

**Comment by GregValiant** [comment]
Thanks for the report.
You were asked to provide a Project File and Cura.log file.  I'll go ahead and close this and you can try again.
So far as I know, Ultimaker Cura does not provide a "Brush Station" code.
Sre you running Sovol Cura?  If it is Sovol Cura you need to submit a report on their site.
