### ISSUE TITLE
2.6.0 Beta  - Infill does not regenerate after changing parameters

### ISSUE THREAD

**Issue by jmagella** [Ultimaker/Cura#1946]
The Infill in the viewport does not regenerate after changing parameters in the mac version,

**Comment by nallath** [comment]
You mean in the layer view? 

Is it slicing again if you change the setting?

**Comment by jmagella** [comment]
Yes in the layer view. 

It re-slices when I change settings. But the infill does not visually change. Not sure if the file itself changes. The estimated time changes so I assume the gcode has changed.

**Comment by Ghostkeeper** [comment]
What setting did you change, then?

Perhaps you changed those settings on the wrong extruder? Or you override the settings in the per-mesh settings?

**Comment by BagelOrb** [comment]
Maybe you disabled viewing the infill?

**Comment by ChrisTerBeke** [comment]
There was a bug in the per object settings that affected the infill density if an override extruder was used. This is fixed for 3.0. Closing for now, please comment if the upcoming 3.0 release still gives you issues.
