### ISSUE TITLE
No video in octoprint preview

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1947]
OS ubuntu 16.04
Cura 2.5.99 master

Since a couple of days the video feed from Octoprint is gone in Cura.
Also when setting Octoprint up, sometimes you can see the xxxx_octoprint._tcp.local but most of the times it is not there and you manually have to enter the IP address.

**Comment by nallath** [comment]
@fieldOfView This is your cup of tea :)

**Comment by awhiemstra** [comment]
Probably broke due to change of making the print monitor more pluggable.

**Comment by fieldOfView** [comment]
Continued here: https://github.com/fieldOfView/OctoPrintPlugin/issues/40

This issue can be closed.
