### ISSUE TITLE
Cura terminates when extruder settings get checked

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#1948]
OS Ubuntu 16.04
Cura 2.5.99 master

Cura crashes instantly when one of the following settings get checked:
Wall Extruder
Outer Wall Extruder
Inner Wall Extruder
Top/Bottom Extruder
Infill Extruder

It only crashes when the settings are visible in the mainscreen(when the dropdown list is unfolded)

**Comment by awhiemstra** [comment]
Yes, this is a bug in PyQt that has been solved in the meantime. You need to upgrade to PyQt 5.8.2, otherwise things crash.

**Comment by maukcc** [comment]
@thopiekar : is this something you can fix? or do we need to do this manually?

**Comment by maukcc** [comment]
I tried installing manually. Had to 1st install pip3 then pyqt5.
Now Cura will not start any more. It will not even generate the .local/share/cura directory.
Tried to remove pyqt5 and pip3 and even purged cura* and reinstalled it, but no deal.
The appImage does work.

**Comment by Ghostkeeper** [comment]
What does it say when you start a Python terminal and type:

    > import PyQt5.QtCore
    > PyQt5.QtCore.PYQT_VERSION_STR

**Comment by maukcc** [comment]
I formatted my machine yesterday, so it says 5.6 now

**Comment by Ghostkeeper** [comment]
That needs to become 5.8 eventually if you want to use these drop-downs.

**Comment by maukcc** [comment]
Well, I tried it manually and had to format my machine. So that will not happen again :)
I will wait for @thopiekar
