### ISSUE TITLE
Pause at height

### ISSUE THREAD

**Issue by lebele79** [Ultimaker/Cura#19486]
### Cura Version

5.7.2

### Operating System

Windows 11

### Printer

Ender 3 S1 Pro with Sonic Pad (Klipper)

### Reproduction steps

1.I used Post Processing Script - Pause at height.

### Actual results

Generated by script:
;added code by post processing
;script: PauseAtHeight.py
;current layer: 2
M83 ; switch to relative E values for any needed retraction
G1 F300 Z1.75 ; move up a millimeter to get out of the way
G1 F9000 X190 Y190
G1 F300 Z15 ; too close to bed--move to at least 15mm
M104 S210 ; standby temperature
M0 ; Do the actual pause
M104 S210
**M104 S0 ; resume temperature**
G1 F300 Z0.75
G1 F9000 X108.597 Y114.327
G1 F300 Z0.75 ; move back down to resume height
G1 F4800 ; restore extrusion feedrate
M82 ; switch back to absolute E values
G92 E78.8099

### Expected results

I think that the M104 S0 line should not be generated

### Add your .zip and screenshots here ⬇️

![Zrzut ekranu 2024-08-05 213948](https://github.com/user-attachments/assets/f663ca11-f5d3-4111-8553-fd9d4fd7bb10)

**Comment by GregValiant** [comment]
Thanks for the report.
The temperature for that "M104 S0 ; Resume Temperature" line is pulled from a previous line in the gcode.  I can envision something like that happening with a multi-extruder printer, but it should not happen with a single extruder machine.
Did you happen to have any other post processors running?

Post the entire gcode file as there may be a clue on a line up above the pause code.
