### ISSUE TITLE
Print time breakdown popup often refuses to appear

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#1949]
The new popup that shows the print time breakdown is great but I am finding it often refuses to appear when I mouse over the total print time. This is on a Ubuntu Linux system that supports the new OpenGL layer view. Sometimes it appears, often not and I cannot yet determine what determines whether it will or not. The popups that appear when you mouse over the settings are all 100% reliable, it's just the time breakdown popup that's flaky.

**Comment by nallath** [comment]
In that case I'm kind of afraid its a Qt issue :(

**Comment by smartavionics** [comment]
Hmm, well I shall try to find out if anything in particular makes it not appear.

**Comment by Ghostkeeper** [comment]
I find that it doesn't appear when the time estimate is 0. But that could be intended.

**Comment by BagelOrb** [comment]
Is this still an issue?

**Comment by smartavionics** [comment]
Yes, it's very unreliable.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by smartavionics** [comment]
Hi,no I think it's working OK at the moment (master branch). I will close the issue.
