### ISSUE TITLE
Slicing the attached file fails

### ISSUE THREAD

**Issue by tjhayko** [Ultimaker/Cura#19496]
### Cura Version

5.70

### Operating System

windows 11

### Printer

Custom Sovol SV06Plus

### Reproduction steps

Slice the attached file

### Actual results

Crash

### Expected results

Model should be sliced.

### Add your .zip and screenshots here ⬇️

[C8_Dew_Shield_v4.zip](https://github.com/user-attachments/files/16517711/C8_Dew_Shield_v4.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There are no errors in the model and I didn't have any trouble slicing it in either 5.8.0 or 5.7.0.
If you attach a cura.log file and a project file we can investigate.

**Comment by tjhayko** [comment]
I've also tried to recreate the error, and I've been unsuccessful :(

I suggest closing this since I can't seem to reproduce it.

**Comment by GregValiant** [comment]
Just another _"I wonder what the heck happened!"_ moment in 3d printing.  I'll go ahead and close this then.
