### ISSUE TITLE
Slicing failed - I cannot slice anything

### ISSUE THREAD

**Issue by ilansuku** [Ultimaker/Cura#19491]
### Cura Version

5.8.0

### Operating System

Ubuntu 22.04.2 LTS

### Printer

Ender 3 V2 NEO 

### Describe your model

Just a test that I could slice in cura 5.5

### Add your .zip here ⬇️

[test_slicing_failed.zip](https://github.com/user-attachments/files/16510604/test_slicing_failed.zip)

Any slicing fails in Cura 5.8. I've tried downloading 5.7 and it keeps failing. Cura 5.5 works fine though.

**Comment by GregValiant** [comment]
Thanks for the report.
Use the "Help | Show Configuration Folder" command to locate the "Cura.log" file.  Zip that file and post it here (don't use e-mail, the file must be posted here directly).
What's happening is likely a local problem on your computer and hopefully the log file will have a clue as to why it's happening.
