### ISSUE TITLE
feature request : Brim on wipe tower ONLY

### ISSUE THREAD

**Issue by UltiArjan** [Ultimaker/Cura#1950]
I often use a thicker wipe tower than needed, just to secure bed adhesion.
I would really like the option to add brim to the wipe tower, but not top the printed object.

**Comment by UltiArjan** [comment]
Oh, and another option on wipe tower, i feel it makes not a lot of sense to have walls and infill for the tower. It would be faster to make it walls only.

**Comment by Dim3nsioneer** [comment]
+1 This was one of the original idea of issue #1503 - in the meantime it turned out it has to be solved differently so I fully support this feature request.

**Comment by Ghostkeeper** [comment]
We already had an issue about this, apparently requested by UltiArjan during the 2.4 beta (though there is no Github page in that issue in our tracker). It's in our top 50 issues, which means that it is considered important. We're getting there.

**Comment by UltiArjan** [comment]
ah, good news, though is got lost somewhere, thanks for the update

**Comment by Ghostkeeper** [comment]
We've tried making the prime tower consist of only walls. Or rather, we've tried concentric infill, which makes it look like walls and more importantly, prevents having to make lots of sharp corners. The problem with that is that it's hard to guarantee a certain volume of material. It's either 4 walls or 5, not 4.5. Still, in my opinion it was leagues better than the vibrator we're simulating now... But I don't know what happened to that idea. Perhaps we were too ambitious in the improvements we wanted to put in that issue.

**Comment by UltiArjan** [comment]
any news on killing the vibrator?

**Comment by Ghostkeeper** [comment]
The ladies seem to like it.

But owing to the shortage of ladies in our R&D department, this issue is nonetheless in our top 50. At position 20, in fact.

**Comment by zerspaner-gerd** [comment]
**+1**

**Comment by jackha** [comment]
We're going to make a brim for helper option.
Devs: CURA-5487

**Comment by Enverex** [comment]
@jackha Have you guys made any progress on this? I'm finding tree supports are very finicky if you're not using a brim right now as it often tries to print some incredibly tiny tree bases which inevitably fail well before the print finishes, but using a brim for the whole print gives a rough edge to the actual model, so "brim on supports only" would be a perfect fix.

**Comment by Ghostkeeper** [comment]
Cura 4.0 has a "Support Brim" that can be enabled separately from the normal brim.

Brim for prime tower is in the works but won't make it for 4.0. It'll be in for 4.1 most likely. It's almost finished. When that is finished we would close this ticket.

**Comment by Enverex** [comment]
Thanks Ghostkeeper, so it does.

I had Cura in Expert Mode and it still wasn't showing, I had to enable "Show All Options" before it appeared - just for anyone else wondering where that option actual is.

**Comment by Enverex** [comment]
Just tried, that option doesn't seem to do anything for tree supports (which are the ones that need it the most):

![image](https://user-images.githubusercontent.com/958670/52244677-a225a800-28d6-11e9-8647-f1da0bbb0a8a.png)

**Comment by Enverex** [comment]
You're right, I hadn't thought to look underneath:
![image](https://user-images.githubusercontent.com/958670/52274898-e9974d00-2945-11e9-8f12-78759096b960.png)

That said (not so much in this example, but others) there are some incredibly small trees that struggle with adhesion and I don't think even an inside brim would help (as it would only add a single line, two at most). Would it be possible to have a "minimum brim-size" for the supports so that they don't end up in that state, or do you think that may be a symptom of another issue with tree supports?

**Comment by nallath** [comment]
As the feature has been implemented for 4.0, this can be closed.
