### ISSUE TITLE
Relative Extrusion is ignored when importing G-Code

### ISSUE THREAD

**Issue by EmJay276** [Ultimaker/Cura#19514]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

All

### Reproduction steps

- Slice any model with relative extrusion setting
- Import the G-Code

### Actual results

![grafik](https://github.com/user-attachments/assets/55eb1b89-7bf4-4161-84bf-8ec36a7fa6eb)

### Expected results

![grafik](https://github.com/user-attachments/assets/6a90a17c-9fe9-4100-b963-0c9e06fd2d93)

### Add your .zip and screenshots here ⬇️

[gcode.zip](https://github.com/user-attachments/files/16560211/gcode.zip)

**Comment by smartavionics** [comment]
A quick look at the Cura 4 code shows that it only recognises relative extrusion (due to M83 in gcode) when the gcode flavour is RepRap.

**Comment by GregValiant** [comment]
I see the same thing (looking in FlavorParser.py) and the behavior does appear to go back to at least 4.13.1.
Arc Welder's G2 and G3 lines continue to be unsupported as well.

**Comment by EmJay276** [comment]
Should adding these lines to the "general" FlavorParser.py not just fix it?
https://github.com/Ultimaker/Cura/blob/e3287a1c161b63c75bc3dfd82257c0c5c2a69dca/plugins/GCodeReader/RepRapFlavorParser.py#L14-L20

**Comment by EmJay276** [comment]
I just tested it in my local installation, and yes, it does fix it.
I will create a PR.

**Comment by EmJay276** [comment]
You can test it in https://github.com/Ultimaker/Cura/pull/19515 if you want 👍
