### ISSUE TITLE
settings toolbox is blank white now.

### ISSUE THREAD

**Issue by theriospen** [Ultimaker/Cura#19519]
### Cura Version

5.7.2

### Operating System

Win 11

### Printer

Snapmaker 2.0 a350

### Reproduction steps

1. all working fine
2. installed BETA
3. Beta changed toolbox settings to white with no text nor checkboxes
4. uninstalled Beta
5. reinstalled 5.7.2
6. worked fine for a couple of slices
7. then settings toolbox went back to all white

### Actual results

have not attempted to duplicate

### Expected results

expected that BETA was the issue. But appears that BETA caused issue. Not sure what could have changed that didnt change back.

### Add your .zip and screenshots here ⬇️

![image](https://github.com/user-attachments/assets/fa81f901-5f75-47d6-a544-36ecddf185a5)

**Comment by GregValiant** [comment]
Thanks for the report.
That's bizarre.  It looks like you using @fieldOfView's "Tabbed Settings" and "SidebarGUI".  I see in your screenshot that the MarketPlace button is showing a red circle with a "2" in it.  That indicates that 2 plugins have been updated in the MarketPlace and you need to update them on your computer.  Let us know if updating fixes the problem.
