### ISSUE TITLE
me da error a la hora de laminar y ya es mas de una vez

### ISSUE THREAD

**Issue by taikus98** [Ultimaker/Cura#19532]
### Cura Version

5.6.0

### Operating System

windows 10

### Printer

ender 3 v2

### Describe your model

una keycap de pikachu 

### Add your .zip here ⬇️

![image](https://github.com/user-attachments/assets/01fae8b3-bceb-43c2-9afd-aa3d35d9eedb)

**Comment by GregValiant** [comment]
Thanks for the report.
CUra 5.6 had problems slicing certain shapes of models.  That has been repaired in later versions.  I suggest you upgrade to 5.8.0.
I'll mark this as a duplicate and go ahead and close it since the problem appears to be fixed.

**Comment by taikus98** [comment]
Muchas gracias
