### ISSUE TITLE
Changelog cut off on hi-dpi displays

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#1953]
<img width="406" alt="changelog hidpi" src="https://user-images.githubusercontent.com/606923/26950427-3049a962-4c63-11e7-9ff8-6fbc2dbbe5d1.png">

This is under 2.6 beta.

**Comment by Ghostkeeper** [comment]
This was just rejected by our project manager for being more than 12 weeks old.

**Comment by fieldOfView** [comment]
See #2068 
This can be fixed by updating the Intel GPU drivers.

**Comment by Ghostkeeper** [comment]
Ah, that was the same issue? Indeed it looks that way now that you say it. I initially thought this was a problem with offsets of the scroll area or something.
