### ISSUE TITLE
No Trigger on Z after full movement

### ISSUE THREAD

**Issue by GardnerFamily** [Ultimaker/Cura#19541]
### Cura Version

4.8.0

### Operating System

windows 11

### Printer

Neptune 4 max 

### Reproduction steps

Trying to get the bed to calibrate and level

### Actual results

erroe code no trigger on z after full movement

### Expected results

the bed should level and calibrate so I can start a new 

### Add your .zip and screenshots here ⬇️

no additional

**Comment by Asterchades** [comment]
This honestly sounds more like a hardware (or perhaps firmware) issue than a software one. Cura can only issue the commands to the printer - it cannot force them to behave properly once they get there. Endstop activation (whether a separate stop or a Z probe) is entirely up to the printer during its homing and ABL processes, and the firmware will have values for the expected amount of maximum Z travel.

As such I feel like you're going to get much better results asking somewhere more appropriate to the issue, such as on an Elegoo forum or subreddit, or indeed contacting Elegoo support directly.

**Comment by GregValiant** [comment]
I agree with Asterchades.  This isn't a UM Cura problem.
You note that the version is 4.8.0.  Is that correct?  UltiMaker Cura is currently on 5.8.0 which is about 15 versions ahead of 4.8.0.  The Elegoo and Creality versions of Cura used 4.8.0 as a base.  If you are using one of those forks of Cura you would need to contact the appropriate support team.
I'll go ahead and close this as it isn't a problem with UM Cura.  I hope you understand.
