### ISSUE TITLE
Unable to Transfer Print to SD Card to Print 

### ISSUE THREAD

**Issue by TerrellMassiah342** [Ultimaker/Cura#19543]
### Cura Version

5.8.0

### Operating System

Windows 11

### Printer

Monoprice Select Mini V2 (ED3) 

### Reproduction steps

I restarted the program and cleared some junk files. Then downloaded a program to fix the issue but I had to pay for it using a credit card which I don't have. 

 

### Actual results

I watched a YouTube video on how to fix the issue and it bought me here. 

### Expected results

The file should go to the SD card with no issue 

### Add your .zip and screenshots here ⬇️

f2.STL

**Comment by TerrellMassiah342** [comment]
I reformatted the card yesterday and it worked

**Comment by GregValiant** [comment]
Good to go.  I'll close this then.
