### ISSUE TITLE
Connect printer dialog on hi-dpi displays

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#1957]
Under Cura 2.6 beta:

<img width="321" alt="connect printer dialog" src="https://user-images.githubusercontent.com/606923/27000928-4e768dea-4d82-11e7-97a9-dbbb6a11b473.png">

**Comment by Ghostkeeper** [comment]
This was just rejected by our project manager for being inactive for more than 12 weeks.

**Comment by fieldOfView** [comment]
This is actually two issues. See https://github.com/Ultimaker/Cura/issues/2068#issuecomment-324917547 and https://github.com/Ultimaker/Cura/pull/2484

**Comment by Ghostkeeper** [comment]
Ah, right. Indeed, it seems to duplicate both of these.
