### ISSUE TITLE
Cura Infill "hole" 

### ISSUE THREAD

**Issue by hahaxd35** [Ultimaker/Cura#19593]
### Cura Version

5.8

### Operating System

Linux (Debian) 

### Printer

Elder 3

### Reproduction steps

just slice

### Actual results

hole thats need to bee hole was infilled

### Expected results

leave the hole a hole :D

### Add your .zip and screenshots here ⬇️

[crusher lager.stl.zip](https://github.com/user-attachments/files/16785803/crusher.lager.stl.zip)

**Comment by hahaxd35** [comment]
fogott to say that Top and Bottom layer makes a on top layer that close the "hole"
![prepai-view-shows-hole](https://github.com/user-attachments/assets/a5f3df53-3c7a-4843-8033-5905ede9b7d5)
![with-infill](https://github.com/user-attachments/assets/1806795e-66bc-49bd-a8b9-4509840c39d7)
![toplayer-on](https://github.com/user-attachments/assets/42d82ca9-f525-4727-b9e7-d1a3c46b7ed0)
![should-be](https://github.com/user-attachments/assets/98e62aea-81f8-41ea-a808-a3e9a63fce70)

**Comment by GregValiant** [comment]
Thanks for the report.
When you look down at a model in Cura Prepare screen and see "red surfaces" facing upwards, that is a sign of a flipped surface.  Cura can't tell where the outside ends and the inside begins.  Your model needs repair.
Microsoft MS 3D Builder is pretty good and there are on-line sites.  Cura itself has some basic repair functions if you load the "Mesh Tools" plugin from the MarketPlace.
This is a report from [onlinestlrepair"](https://formware.co/OnlineStlRepair)
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 0 Non-manifold edges (?)
--> 136 Inverted faces (?)
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 290ms ------
-> Vertex count changed from 257 to 454 (+197)
-> Triangle count changed from 510 to 904 (+394)

Once repaired it slices fine.
![image](https://github.com/user-attachments/assets/a97598ec-999f-44c9-865b-a326d2710863)

So this is a model problem and I'll remove the bug label and go ahead and close this.  I hope you understand.
