### ISSUE TITLE
Cura crashed while slicing

### ISSUE THREAD

**Issue by george-genovezos-by** [Ultimaker/Cura#19594]
### Cura Version

5.7.1

### Operating System

windows 11

### Printer

Creality 5 pro

### Reproduction steps

simple bottom version of https://www.thingiverse.com/thing:3574895/files

Used the open in cura feature, made a duplicate of the item

sliced and failed

### Actual results

slice failed but didn't crash the app

### Expected results

the send to printer button should have appeared

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-08-28 173150](https://github.com/user-attachments/assets/8a0a7534-29a8-44c4-be61-a4652c055ed1)

**Comment by GregValiant** [comment]
Thanks for the report but without a project file there isn't anything we can do.  We need your printer and your Cura settings as well as the model.
