### ISSUE TITLE
error en los soportes de arbol

### ISSUE THREAD

**Issue by saritaperez11** [Ultimaker/Cura#19616]
### Cura Version

5.8.1

### Operating System

windows 11

### Printer

mizar pro

### Reproduction steps

generando los soportes de arbol.
solo aparecen en las 2 primeras capas y despues no pone nada.
o simplemente no los pone.
![Captura de pantalla 2024-09-04 135305](https://github.com/user-attachments/assets/52103796-7f1a-46b9-a371-fde4a4bda989)
![Captura de pantalla 2024-09-04 135351](https://github.com/user-attachments/assets/9400308e-b013-4b37-a578-08bb90469c75)

### Actual results

no me aparece ningun soporte

### Expected results

que genere correctamente los soportes.

### Add your .zip and screenshots here ⬇️

[error de soporte.zip](https://github.com/user-attachments/files/16880234/error.de.soporte.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for Cura Project Report ("File | Save Project") because videos that don't show anything are no help in debugging.  Please generate a project report, zip it, and post the zip folder.
