### ISSUE TITLE
No brim when enabling supports - 2.6.0 beta

### ISSUE THREAD

**Issue by bipsendk** [Ultimaker/Cura#1962]
In Cura 2.6.0 Beta   - when slicing the front brace STL file from https://www.thingiverse.com/thing:2118713 and choosing to have a brim around the printed object, brims are only put where the supports are constructed.

![2017-06-11 19_05_42-cura](https://user-images.githubusercontent.com/8531428/27012866-15607248-4ed9-11e7-96f0-c3c51ba149c3.png)

**Comment by Ghostkeeper** [comment]
Doesn't happen here: 
![Support and brim working fine](https://user-images.githubusercontent.com/2448634/27274752-e2998988-54d4-11e7-99b9-addce8955c50.png)

**Comment by Ghostkeeper** [comment]
Perhaps the model wasn't entirely aligned to the build plate? If it's floating in the air, only the support will be touching the first layer.

**Comment by BagelOrb** [comment]
Caused by the same issue as https://github.com/Ultimaker/Cura/issues/2050
