### ISSUE TITLE
Elegoo cura 5.6.0 wont slice

### ISSUE THREAD

**Issue by Tarman70** [Ultimaker/Cura#19625]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Neptune 4Plus

### Reproduction steps

1 loaded saved project to build plate then pressed slice and it starts and then fails about 40% or less.

### Actual results

it pops up the error that slicing fails and asks to report the bug

### Expected results

Should finish slicing and then i can save to flash drive

### Add your .zip and screenshots here ⬇️

[EN4P_RH4C-D-E1.zip](https://github.com/user-attachments/files/16918856/EN4P_RH4C-D-E1.zip)

**Comment by GregValiant** [comment]
This is the **UltiMaker** Cura support site.  You will need to make a report on the Elegoo website as their fork of Cura is different.
I'll go ahead and close this.  I hope you understand.
