### ISSUE TITLE
Macbook pro not doing anything after trying to import a file

### ISSUE THREAD

**Issue by Hunter201o** [Ultimaker/Cura#19635]
### Cura Version

5.4.0

### Operating System

macos montery

### Printer

ender 3 

### Reproduction steps

The software wasnt letting me import files it just woundnt do anything at all.

### Actual results

The software would let do every thing as normal i just couldnt import

### Expected results

it should import my file so i can slice it.

### Add your .zip and screenshots here ⬇️

i dont have any

**Comment by GregValiant** [comment]
Thanks for the report.
The current Cura version is 5.8.1 so you are 7 versions out of date.  In addition you didn't provide a log file or project file wo we have nothing to look at.  I suggest moving up to 5.8.0 or 5.8.1.

I'll go ahead and close this as 5.4.0 is obsolete, and this is the only report I recall regarding simply "not working".  I hope you understand.
