### ISSUE TITLE
Slicing a cylinder makes rendering bug out 

### ISSUE THREAD

**Issue by ignas-rss** [Ultimaker/Cura#19651]
### Cura Version

5.8

### Operating System

Mac OS 14.6.1

### Printer

VEHO-600

### Reproduction steps

1. Add cylinder - any of these should do:
https://www.dropbox.com/scl/fo/zzjgylj1snf6bn60sadho/ADpx2Pngeqcit93kHr4K64k?rlkey=qps6scuk812bwats4mhxxpxsb&st=osccchp8&dl=0
2. Try slicing
3. Preview 
4. Weird result
<img width="402" alt="Screenshot 2024-09-13 at 20 45 04" src="https://github.com/user-attachments/assets/16f81537-7be7-4562-b348-906aeb0bfbe9">

### Actual results

Hard to describe that like the image shows
<img width="402" alt="Screenshot 2024-09-13 at 20 45 04" src="https://github.com/user-attachments/assets/304c2dac-06de-4046-9eaa-441d8f2ecb9d">

### Expected results

Sliced cylinder

### Add your .zip and screenshots here ⬇️

[cylinder.3mf.zip](https://github.com/user-attachments/files/16998691/cylinder.3mf.zip)
[cura.log](https://github.com/user-attachments/files/16998711/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
You have successfully re-discovered what I call the "Peter Maxx" bug.  So far it remains illusive.  I've only had it happen once and that was on my previous computer.  It won't duplicate for me with your models.
![image](https://github.com/user-attachments/assets/e6d4c822-8cbb-414f-a1ff-d9ea6f8da0dc)

This one is my favorite:
![Peter Maxx bug](https://github.com/user-attachments/assets/ffc64ef5-32ea-492b-93d0-06da3af9f8f8)

I like this one as well:
![Peter Maxx 2](https://github.com/user-attachments/assets/8d33cd87-da3c-4f4d-a630-d39187647625)

This bug has showed up very infrequently over the last 8 or 10 versions of Cura.  It doesn't affect the gcode, but it looks really bizarre when it happens.  The Cura team will take a look.

**Comment by ignas-rss** [comment]
I was initially reproducing it consistently even with app restarts, but now seems to stop happening after a bit even without restarting the app

**Comment by GregValiant** [comment]
That's what has happened before.  The bug appears and disappears apparently at random which makes chasing it down near impossible.  It's like trying to find an intermittent electrical fault.
Something seems to be going on between Cura and the video system/OpenGL driver.
