### ISSUE TITLE
"open project" dialog box too small

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1966]
cura 2.6.0 beta:
when opening a project I get this dialog box with the text cut off:
![image](https://user-images.githubusercontent.com/19934504/27017792-fc601eb8-4edf-11e7-97fc-c04bb47ae2fd.png)

**Comment by nallath** [comment]
Ugh, not this again :( What is your operating system, resolution & screen?

**Comment by uwe999** [comment]
win10, 1920x1080 and "change the size of text, apps, and other items: 150%
(recommended)"

**Comment by Ghostkeeper** [comment]
Our project manager just kicked this off our planning because the ticket was older than 12 weeks.

**Comment by fieldOfView** [comment]
Sure, you can ignore it. Doesn't mean it is not broken
https://github.com/Ultimaker/Cura/commit/7bc715a9bd5e61efcfef4b54f7d004b3f6248f5a

I have said this before, and several others have too. Specifying sizes in pixelsizes without taking Screen.devicePixelRatio is not correct on Windows when the user sets the "Change the size of text, apps and other items" to anything but 100%. On high-ish DPI screens the default is often 150% or even 200%. It worked correctly before, but then the Screen.devicePixelRatio was removed willy-nilly in a number of QML files, breaking those windows.

**Comment by fieldOfView** [comment]
Should be fixed now, can be closed.
https://github.com/Ultimaker/Cura/pull/2484
