### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by wickedconstructs** [Ultimaker/Cura#19660]
### Cura Version

5.8.1

### Operating System

windows 10

### Printer

ender3 v3 se

### Describe your model

hueforge

### Add your .zip here ⬇️

slicing a 2.2mm hueforge when slice failed

**Comment by GregValiant** [comment]
Thanks for the report.
Without any documentation there isn't anything that can be done with this.  It might be the model, your settings, or a bug.  That's why we ask for a project file and the Cura.log file.  The instructions are on the form you filled out for the report.
