### ISSUE TITLE
visual bug when slicing layer view 

### ISSUE THREAD

**Issue by BeSome1** [Ultimaker/Cura#19663]
### Cura Version

5.8.1

### Operating System

win 11

### Printer

sovol sv06 plus

### Reproduction steps

slice enter layer view go layer by layer until bug is seen 

### Actual results

visual bug where 1 or more of the layers are some how stretched across the build plate to the corner of the build plate, not allowing for me to accurately view prints layer by layer.
![Screenshot 2024-09-19 083506](https://github.com/user-attachments/assets/22dc5b0b-53b4-4309-9e64-10edc03c15d2)

### Expected results

picture added of results.

### Add your .zip and screenshots here ⬇️

screenshoot above

**Comment by GregValiant** [comment]
Thanks for the report.
There is a growing list of display issues cropping up.  I'll mark this as a duplicate and go ahead and close it in favor of the previous reports like #13417 .  I hope you understand.
