### ISSUE TITLE
Support adjustments for misaligned gantries

### ISSUE THREAD

**Issue by blended-bram** [Ultimaker/Cura#19672]
### Is your feature request related to a problem?

I own a EasyThreed Nano, it is a cube-like device where the gantry is controlled through vertical screw rods. There are 4 of these, one on each corner of the cube. There are 4 Y screw-rods because these are used to raise and lower a H-shaped gantry which implements the X and Z movement of the print head. This is how the printer implements a cube-like structure that does not require the buildplate to move.

The H-shaped gantry is raised and lowered by the 4 rods turning in sync, internally the Nano runs a belt along the four rods and moves them with a single motor.

My problem is that one or two of these rods can be misaligned. For example, the belt may have slipped and now the Y position of the bolt on this rod is out of sync with the other 3. In this case the gantry is warped with a single corner sitting lower/higher than the other 3. If two are out of sync then there can be even more warp (in the diagonal case) or the gantry becomes slanted (in the case the out-of-sync bolts are on neighboring corners))
If one rod is out-of-sync.

Turns out, fixing this is rather cumbersome for this printer.
Thinking about how some printer firmware now has automatic buildplate levelling, perhaps this problem can also be accounted for in software.

## Gantry warp / Y-offset parameters

Introduce a 4 parameter gantry warp input; which allows you to describe how the gantry movement surface is misaligned from a plane that is parallel to the build plate.

- Y-offset at maxX, maxZ
- Y-offset at maxX, minZ
- Y-offset at minX, maxZ
- Y-offset at minX, minZ

By default these are all 0. These offsets describe the offset the print head experiences at every extreme on the XZ-plane in the buildvolume. The user can do this manually by setting the printhead at some Y and measure the distance to the buildplate, then take the corner(s) that trigger the Y-homing switch as 0 and fill out the relative distances for the remaining corners as the Y-offsets.

## Pathing changes

After rendering the layers, the pathing can be adjusted such that as the print head moves across the XZ plane, the Y axis is adjusted to take into account the alignment of the gantry.
In the case the 4 offsets produce a coherent plane then the Y offset can be linearly interpolated.
For the cases where the gantry is actually warped I'm not sure what the formula should be. Linear interpolation may be a first good attempt but I suspect that the warping may be more smooth in real-life.

### Describe alternatives you've considered

Taking apart the printer, but due to the design this is actually incredibly tedious and hard to get right.

### Affected users and/or printers

Beyond my particular printer, this may also help other printers where the XZ gantry can become misaligned compared to the build plate. For example one where the buildplate is lowered by multiple screws.

## Picture of EasyThreed Nano

![Picture of EasyThreed Nano](https://github.com/user-attachments/assets/29de8b7d-6c57-4a67-b860-2728894f3579)

**Comment by fieldOfView** [comment]
I would say that this belongs in the printer firmware - if anywhere. A gcode file ideally does not include printer aspects that change over time; a gcode file should print predictably on the same printer the way it printed before; calibration should happen in the firmware.

Additionally this does not affect Ultimaker printers, so it is unlikely Ultimaker employees are going to be able to put time towards the feature. So I am closing this issue, I hope you understand.

**Comment by blended-bram** [comment]
Well understood, thanks for clarifying on the role of firmware
