### ISSUE TITLE
bug report, failure to slice

### ISSUE THREAD

**Issue by CivilSoap** [Ultimaker/Cura#19689]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ender 3 v2

### Reproduction steps

went to slice 2 models (duplicates), and it failed. files provided

### Actual results

fails to slice?

### Expected results

fails to slice?

### Add your .zip and screenshots here ⬇️

[CE3E3V2_arm_joint.zip](https://github.com/user-attachments/files/17151112/CE3E3V2_arm_joint.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 had definite problems trying to slice certain shapes.  Those problems seem to all have been addressed in newer versions.  I suggest you update to Cura 5.8.0.

I'll mark this as a duplicate and go ahead and close it.
