### ISSUE TITLE
Model not flat on build plate

### ISSUE THREAD

**Issue by uwe999** [Ultimaker/Cura#1968]
Cura 2.6.0 beta:
I had several failed print on this T-rex skull enlarged to 120%. I have my bed leveled and print on PEI and rarely have an issue with a print coming unstuck during printing.
After doing some more debugging it turns out that the model isn't flat on the build plate after enlarging to 120 percent. To duplicate:
Drag & drop https://www.thingiverse.com/download:550809 to the build plate. Enable brim and supports. The "layer view" shows that supports and first layer are printed with brim.
Now enlarge to 120%. "Layer view" now shows that main model isn't printed on first layer (see screenshot).

I wasn't able to duplicate this issue with a more simple stl.

![image](https://user-images.githubusercontent.com/19934504/27042078-cdb39340-4f4a-11e7-9866-ca626a9fe51f.png)

**Comment by smartavionics** [comment]
Hi, it worked OK for me using the current master branch...
![screenshot_2017-06-12_18-21-03](https://user-images.githubusercontent.com/585618/27046367-0d5f1798-4f9c-11e7-9280-4b359428ac01.png)

**Comment by ChrisTerBeke** [comment]
please re-open if it's really still an issue (but I can't reproduce it anywhere).

**Comment by Ghostkeeper** [comment]
This was fixed in release Cura 3.2 (or at least a bug that looks very much like it).
