### ISSUE TITLE
The error on a gcode creation with 3 elements

### ISSUE THREAD

**Issue by antho27** [Ultimaker/Cura#19698]
### Cura Version

5.8.1

### Operating System

Windows 10

### Printer

Geeetech A20

### Reproduction steps

1. I place 4 elements (one bigger and 3 smal).
2. I click on cut
3. I click on save on my external drive
4. I got an error say "cut fail"

### Actual results

I can't save a gcode file

### Expected results

I click on report bug form this error

### Add your .zip and screenshots here ⬇️

[stuff.zip](https://github.com/user-attachments/files/17189752/stuff.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I cannot duplicate the problem with an A20 using the stock settings.  If you include a project file and log file they might show something.
I'll remove the bug label for now.  If your additional documentation shows a problem I can add the label again.
