### ISSUE TITLE
Tab Through Fields

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#1969]
Hi guys, would it be a pain to allow tabbing through the setting fields? 

It would really be nice to tab through when setting up a print!

**Comment by fieldOfView** [comment]
I agree that would be nice. I remember a couple of small complications from when I last tried to implement this. For example all the controls will need a "has keyboard focus" state. Not all controls respond to keyboard input at the moment (eg checkboxes, section headers).

**Comment by DDDirk** [comment]
Keyboard control is more than just nice. At the moment my RSI is really bad, to the extent that it really hinders me in my work (reduced control over finger movements). Tabbing through the fields is just one thing. Simply using the menu in a standard way is something that would also help. (So all menus accessible with Alt-<key> and moving through the menu structure with the arrow keys.)

**Comment by nallath** [comment]
This has been implemented.

**Comment by CCS86** [comment]
@nallath , which version? 

I just installed 2.6.2, and don't have that functionality.

**Comment by fieldOfView** [comment]
Cura 2.7, which has not yet been released. I expect a beta to be available in a week or so

**Comment by CCS86** [comment]
Is it possible to change the behavior so that the current field value is selected when tabbing I to the field?

This would make it so much more efficient to tab through, quickly keying values, instead of having to delete every current entry value first.

**Comment by fieldOfView** [comment]
I have made a PR (#3017) to implement this. It is something you can try/test for yourself by editing resources/qml/Settings/SettingTextField.qml (it is a single line addition)

**Comment by CCS86** [comment]
Awesome, thanks @fieldOfView , that worked perfectly!
