### ISSUE TITLE
Falha no Fatiamento

### ISSUE THREAD

**Issue by Biel-S2** [Ultimaker/Cura#19696]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Anet A8

### Name abnormal settings

Erro no Fatiamento Quando é Colocado 100% de Preenchimento !!

### Describe your model

Já Obtive várias impressões com o mesmo modelo, porém, dessa vez acabei fazendo algumas modificações no meu projeto, quando seleciono a opção para por o preenchimento em 100% da minha peça, apresenta erro fatal na hora do seu fatiamento

### Add your .zip here ⬇️

Quando adicono 100% de preenchimento, acontece o erro !!

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Cura Log file and a Project File we have no way to investigate this.  The instructions are on the page you filled out for this report.
