### ISSUE TITLE
Keyboard shortcut for Print

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#197]
Could you add a Print option to the File menu with associated shortcut (CMD-P or CTL-P)?

**Comment by nallath** [comment]
What would the behavior be? Print if a printer is connected with USB?

**Comment by Xisle** [comment]
Add "Print" to File menu but make it inactive (gray it out) when "Print to USB" is NOT available.

The Print menu item can be inactive when the print button is gray..

![screen shot 2015-07-29 at 3 37 40 am](https://cloud.githubusercontent.com/assets/12257213/8956592/f25a4558-35a3-11e5-8388-1dcf296ec5f2.png)

..and active when it is blue (or would be blue, even if "Save to SD" is currently selected)

![screen shot 2015-07-29 at 3 38 23 am](https://cloud.githubusercontent.com/assets/12257213/8956687/d5a1be9a-35a4-11e5-95a2-2f485ec38ca2.png)

**Comment by nallath** [comment]
We're having some internal discussion as to what good behaviour would be in this regard, as pressing ctrl + p and then seeing a save to local file menu pop up is somewhat confusing.

**Comment by Xisle** [comment]
ctrl-p and ctrl-s should work as expected (when printing or saving is available) regardless of the current blue button status. Why would ctrl-p show a save dialog?

The user could have "Save to USB" selected and still hit ctrl-p to print just like ctrl-s should work even when "Print to USB" is selected.

**Comment by nallath** [comment]
Because we don't have an internal difference between save to file and send to printer. Both are output devices.

**Comment by BagelOrb** [comment]
Ctrl-P normally (in most standard programs) pops up a window with all printer settings (color/black-white etc.) and profiles (quality etc.). It is in this popup window where you can hit the button to actually print.

The analogue in 3D prining should be that Cura starts up when you press Ctrl-P from Solidworks for example.

I think it's a bit scary to connect a real-world action to a keyboard short-cut - when you accidentally hit it and don't notice, a print is started and material might be wasted.
