### ISSUE TITLE
Issues logging into cura

### ISSUE THREAD

**Issue by SeanKelly03** [Ultimaker/Cura#19704]
### Cura Version

5.8.1

### Operating System

Windows 11 : Enterpise

### Printer

Utimaker S7 and Utimaker 2+ connect

### Reproduction steps

Simply try to sign in.

### Actual results

Go throught the webpage and shows the "SIGNED IN!" page; but going to the cura application shows that it tries to connect and fails OR does not even try.

### Expected results

Signin into cura using my utimaker account

### Add your .zip and screenshots here ⬇️

[Cura data.zip](https://github.com/user-attachments/files/17214370/Cura.data.zip)

**Comment by nallath** [comment]
Could you share the cura.log file (and not the cura.log.1) file? The cura.log.1 file is the old logging, so it doesn't contain any recent info.
