### ISSUE TITLE
Cura Stops Responding

### ISSUE THREAD

**Issue by LAdodgers82** [Ultimaker/Cura#19708]
### Cura Version

5.8.1

### Operating System

MacOs

### Printer

Creality Ender Plus

### Reproduction steps

Takes forever to load STLs and when I try to adjust the programs stops responding.
![IMG_1201](https://github.com/user-attachments/assets/805ffa71-9174-4872-a394-565eeee42c80)

### Actual results

I have to force quit and try to restart again.

### Expected results

Hoping program re-sets

### Add your .zip and screenshots here ⬇️

![IMG_1201](https://github.com/user-attachments/assets/13e9eac5-2864-43df-a1c6-cb2bdd0b0d60)

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for log files and project files so we have something to look at to try to duplicate the problem.
Something you might try would be to go to the Cura MarketPlace (button at the top right of the Cura workspace) and click on the "gear" icon.  Scroll down and disable "USB Printing".  Restart Cura and try to reproduce the problem.

This is unrelated to this report but looking at your screenshots, have you had trouble with the "move/rotate/scale, etc." handles being huge when you zoom in in Cura?
