### ISSUE TITLE
Cura doesn't respect initial gcode

### ISSUE THREAD

**Issue by felipebraz** [Ultimaker/Cura#19717]
### Cura Version

5.7.2

### Operating System

Windows 11

### Printer

Creality Ender 3 (Custom)

### Reproduction steps

Create a custom initial gcode with custom bed and nozzle temperatures.

In my case:

; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

M140 S{material_bed_temperature} ;set bed temperature

G28 ; Home all axes

M190 S{material_bed_temperature} ;wait for bed temperature
M104 T0 S{material_print_temperature} ;set hotend temperature

G29 ; Auto leveling

M109 T0 S{material_print_temperature} ;wait for hotend temperature

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish

### Actual results

;FLAVOR:Marlin
;TIME:26003
;Filament used: 26.5148m
;Layer height: 0.28
;MINX:41.132
;MINY:53.825
;MINZ:0.28
;MAXX:170.636
;MAXY:183.328
;MAXZ:117.88
;TARGET_MACHINE.NAME:Creality Ender-3
;Generated with Cura_SteamEngine 5.7.2
M104 S195 -- shouldn't exist in here
M105 -- shouldn't exist in here
M109 S195 -- shouldn't exist in here
M82 ;absolute extrusion mode -- shouldn't exist in here
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

M140 S55.0 ;set bed temperature

G28 ; Home all axes

M190 S55.0 ;wait for bed temperature
M104 T0 S195.0 ;set hotend temperature

G29 ; Auto leveling

M109 T0 S195.0 ;wait for hotend temperature

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line

### Expected results

;FLAVOR:Marlin
;TIME:26003
;Filament used: 26.5148m
;Layer height: 0.28
;MINX:41.132
;MINY:53.825
;MINZ:0.28
;MAXX:170.636
;MAXY:183.328
;MAXZ:117.88
;TARGET_MACHINE.NAME:Creality Ender-3
;Generated with Cura_SteamEngine 5.7.2
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

M140 S55.0 ;set bed temperature

G28 ; Home all axes

M190 S55.0 ;wait for bed temperature
M104 T0 S195.0 ;set hotend temperature

G29 ; Auto leveling

M109 T0 S195.0 ;wait for hotend temperature

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line

### Add your .zip and screenshots here ⬇️

![image](https://github.com/user-attachments/assets/07a8a848-7c24-4eb8-baa1-7e6a1e8ad587)

![image](https://github.com/user-attachments/assets/b8430b58-3e15-4e56-ae33-fa3881d0a5ee)

**Comment by Asterchades** [comment]
There is a bug specific to 5.7.2 which will cause it to continue generating automatic temperature code even in the presence of the appropriate tokens in the Start Gcode. This has already been fixed in 5.8.0, released on August 1.

https://github.com/Ultimaker/Cura/releases/tag/5.8.0
- Fix a bug where material_print_temp_prepend not being disabled, resolves https://github.com/Ultimaker/Cura/issues/19204
