### ISSUE TITLE
revo deksel

### ISSUE THREAD

**Issue by sidemountdiver** [Ultimaker/Cura#19711]
### Cura Version

5.3.1

### Operating System

windows11

### Printer

S5

### Describe model location

center 

### Describe your model

in cura 4.13.1 was het geen probleem, model is watertight

### Add your .zip here ⬇️

[UMS5_rEvo cover.zip](https://github.com/user-attachments/files/17263552/UMS5_rEvo.cover.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.3 through 5.6 suffered with slicing problems and there were numerous reports.  Starting with 5.7 much (if not all) of that was fixed.  I would advise to upgrade to Cura 5.8 which is 7 versions newer.

I'll mark this as a duplicate and go ahead and close it as it appears that the problem has been fixed.  I hope you understand.
