### ISSUE TITLE
Profiles and Material confusing

### ISSUE THREAD

**Issue by ogoudge** [Ultimaker/Cura#1972]
The linking of profiles and materials is confusing and appears to be broken, or possible needs to be more clear and simple.

1. It be nice to be able to remove the default material and build my own with my own retraction settings etc.
2. When making the changes in the material also found I need to build a new profile. However this still did not work.
3. To have both is to redundant.

The issue I have a print that I need 100% fill on, The best I can get is about 10% even though all my setting show 100% someplace along the line its pulling settings from someplace you can not see.

To me having this flaw or poor flow makes this version of the software not even usable.

One simple fix for this would be to set any changes made in the custom setting override any material or profile settings. Personally I think you should just drop those features all together or give an option to not use them and allow people to simple set there perimeters under the costume settings.

**Comment by fieldOfView** [comment]
You can change the "has_materials" metadata of your printer definition to false. This will remove material selection for that printer.

> One simple fix for this would be to set any changes made in the custom setting override any material or profile settings.

That should already be the case.

**Comment by nallath** [comment]
Could you share a project file of your setup? It seems like something is going wrong.

**Comment by ogoudge** [comment]
I had to install and resetup the software here is a project.

________________________________

**Comment by ogoudge** [comment]
I do not see this "has_materials" I have also tried to set the defaults but they are still settings from someplace. It really seams unnecessary to have Material, profile, and print setup. Should lose profile keep material and make it so print setup options override profile options.

**Comment by fieldOfView** [comment]
All definitions inherit from fdmprinter.def.json. This definition sets the "has_materials" metadata to true, and there are very few definitions that don't use materials, so you do not often see a "has_materials" metadata entry. But you can add it to the "metadata" section of the definition file.

See the Moai definition for an example:
https://github.com/Ultimaker/Cura/blob/master/resources/definitions/peopoly_moai.def.json#L13

NB: pay close attention to the syntax of the json file, specifically the comma at the end of the line. The last line in the metadata section should not have a comma, the others do.

**Comment by Ghostkeeper** [comment]
> I had to install and resetup the software here is a project.

The project seems to have gone lost. If you post that as an attachment via the e-mail it won't get attached to the issue here. That attachment gets lost.

**Comment by ianpaschal** [comment]
OP never responded about the missing project, so I am closing this.

**Comment by ogoudge** [comment]
Yea quit using cura that was the fix

Sent from BlueMail<http://www.bluemail.me/r?b=12095>
On Feb 27, 2018, at 9:51 AM, Ian Paschal <notifications@github.com<mailto:notifications@github.com>> wrote:

OP never responded about the missing project, so I am closing this.
