### ISSUE TITLE
Flashing of Dialogue box when Preferences>Printers>Machine Settings is open

### ISSUE THREAD

**Issue by rushdb** [Ultimaker/Cura#19745]
### Cura Version

5.8.1

### Operating System

windows 11 Home 23H2

### Printer

all printer with profiles Creality Ender 3 Pro and Anycubix Mega X

### Reproduction steps

I opened the dialogue box and it started flashing

### Actual results

No Change

### Expected results

No Flicking of dialogue window

### Add your .zip and screenshots here ⬇️

Hard to get picture of a screen blinking on and off

**Comment by GregValiant** [comment]
Thanks for the report.
I have not heard of this one and it might be system specific.  What video subsystem does the computer have?
Use the "Help / Show Configuration Folder" command the find the Cura.log file.  Zip the file and post the zip folder here.
