### ISSUE TITLE
can't use full height of the machine

### ISSUE THREAD

**Issue by Rick-TRIGGER** [Ultimaker/Cura#19750]
### Cura Version

5.8.1

### Operating System

Mac OS sonoma

### Printer

Artillery sw-x2

### Reproduction steps

just want to print a 300mm part up but the built plat show me only a 200 mm... 
the parameter in the machine was 300x300x400 

### Actual results

can print a part longer tahn 200 mm on the Z axis

### Expected results

cant print

### Add your .zip and screenshots here ⬇️

<img width="1792" alt="Capture d’écran, le 2024-10-14 à 17 43 02" src="https://github.com/user-attachments/assets/566e8161-afd7-45b4-9559-b7db41235283">

<img width="1792" alt="Capture d’écran, le 2024-10-14 à 17 42 53" src="https://github.com/user-attachments/assets/c81256fb-1d5d-4129-b4c5-d94d8c829730">

**Comment by Rick-TRIGGER** [comment]
<img width="1792" alt="Capture d’écran, le 2024-10-14 à 17 55 23" src="https://github.com/user-attachments/assets/c9b57e4c-84a2-4ffe-8638-ef0a772d25bb">

**Comment by Rick-TRIGGER** [comment]
the last version that work was cura 5.6 on macx64

**Comment by GregValiant** [comment]
Thanks for the report.
Please use the File | Save Project command and then zip that new 3mf file and post the zip folder here.  We need something to investigate.

**Comment by Rick-TRIGGER** [comment]
I find that the probleme apear since 5.7.5.6 was okEric Trudel450 521-9330 ***@***.*** 16 oct. 2024 12 h 39, GregValiant ***@***.***> a écrit :
Thanks for the report.
Please use the File | Save Project command and then zip that new 3mf file and post the zip folder here.  We need something to investigate.
