### ISSUE TITLE
After supports are done the print stops. only when drop down model is used and raised by any number of mm. shown in slicer aswell.

### ISSUE THREAD

**Issue by themasterblimp** [Ultimaker/Cura#19775]
### Cura Version

5.8.0

### Operating System

Windows 10

### Printer

Creality Ender 3 V3 SE

### Reproduction steps

Deselected drop down model option and raised the model on the z axis by 5 mm. No model flaws. No slicing error.

### Actual results

Print stops after the support has finished.

### Expected results

Slices as expected.

### Add your .zip and screenshots here ⬇️

[CE3V3SE_Parts_Tray_Holder.zip](https://github.com/user-attachments/files/17435595/CE3V3SE_Parts_Tray_Holder.zip)
![image](https://github.com/user-attachments/assets/30fc8405-038a-41d9-9c73-1873deb918e1)
![image](https://github.com/user-attachments/assets/d1fedb2a-c2fe-4304-9040-6bca2482f845)
![image](https://github.com/user-attachments/assets/bb65be2c-c553-4793-8a85-e65357762d8a)

**Comment by GregValiant** [comment]
Thanks for the report.
I don't see any problems in the gcode I generated.  It would print on my Ender.
Zip and post your problem Gcode file.  Maybe there is something in there that will give a clue as to what is going on.
