### ISSUE TITLE
Parts do not snap to ground

### ISSUE THREAD

**Issue by mitchbarbon** [Ultimaker/Cura#1979]
When parts are brought into Cura, they sometimes **_do not snap to ground plan_**. The attached image show this perfectly with three different part files. When the part is above the surface, Cura allows you to "eyeball it" and move the part down. If it is below the surface, **_you cannot move the part upward_**. The parts are scaled in the image, but this issue occurs before converting to inches. I have also tried drag and drop, versus opening the file through Cura. To my knowledge, this is happening in at least the previous few generations of Cura including its most recent release. We use Creo PTC for modeling in case that means anything.
![cura_problems](https://user-images.githubusercontent.com/29459986/27187586-9c8978b8-51b9-11e7-88fd-19c804086d1b.png)

**Comment by nallath** [comment]
Can you share the part? I think this is something about this model that is causing issues.

**Comment by mitchbarbon** [comment]
I can share this part.
![prt0003](https://user-images.githubusercontent.com/29459986/27225639-1da3a284-5269-11e7-9d25-5775abbbb3f7.png)

[PRT0003.zip](https://github.com/Ultimaker/Cura/files/1080674/PRT0003.zip)

**Comment by Ghostkeeper** [comment]
Seems that this happens when it auto-scales the model. Because this model was modelled in a different unit, Cura auto-scaled it to something that's more logical (it displays a message that it did so). If I rescale it in CloudCompare and then load the model in Cura it works correctly.

**Comment by Ghostkeeper** [comment]
Our project manager just removed this bug from our planning because it's more than 12 weeks old.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by mitchbarbon** [comment]
Hello,

This is not an issue if the part is in mm. But we always work in inches so this is still a problem if we do not convert the file to mm before exporting.

Thanks,
Mitch

**Comment by Ghostkeeper** [comment]
We've been experimenting with a fix yesterday for these (there are a lot of duplicates of this issue). We found something but it might have a performance impact so we're testing that a bit.

**Comment by Ghostkeeper** [comment]
This is fixed for Cura 3.2.

**Comment by mitchbarbon** [comment]
Thanks! This will be such great help!
