### ISSUE TITLE
Slicing Fails with 0.25mm layer height on certain hexagonal models

### ISSUE THREAD

**Issue by AnvilEnjoyer** [Ultimaker/Cura#19809]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Creality Ender-3 pro

### Name abnormal settings

0.25mm layer height fails with this model. 0.28 works. 0.25 works with other models.

### Describe model location

it's in the center, no and no.

### Describe your model

the mesh is good, as seen in the "abnormal settings" section.

### Add your .zip here ⬇️

[CE3PRO_Hex wall cura error fix attempt v1.zip](https://github.com/user-attachments/files/17528217/CE3PRO_Hex.wall.cura.error.fix.attempt.v1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I am unable to duplicate the problem.  The project sliced fine for me in 5.7.1 regardless of the layer height.

The Cura team will take a look.
It would be helpful if  - after a failure you immediately zip the Cura.log file (it's in your Configuration Folder) and post it here.
