### ISSUE TITLE
Unable connect my MakeiT pro-M via USB

### ISSUE THREAD

**Issue by dhiraj1000** [Ultimaker/Cura#1980]
Cannot connect printer via USB. I tried to restart, both pc as well as printer. I was able to connect mattercontrol 1.6 over USB. I would like to print via USB as well as update firmware. Please suggest any methods which might work and resolve this issue. Thanks!!

**Comment by nallath** [comment]
Contact the manufacturer of your printer. We don't have access to their firmware or their machines. We can't provide any support for non Ultimaker printers.
