### ISSUE TITLE
Failed while slicing

### ISSUE THREAD

**Issue by lpedrop** [Ultimaker/Cura#19813]
### Cura Version

5.8.1

### Operating System

Windows 11 Home

### Printer

FLSun Q5

### Describe your model

Just some supports and pins for a RC car cover.

### Add your .zip here ⬇️

[FQ5_Untitled.zip](https://github.com/user-attachments/files/17530958/FQ5_Untitled.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate the problem.  Slicing your project "as received" worked OK.  The small piece was 9mm below the build plate.  After moving it up I re-sliced and that worked as well.

Force the same behavior from Cura and then go to your Configuration Folder, zip the cura.log file, and post that zip folder here.
