### ISSUE TITLE
Support Blocker Failure

### ISSUE THREAD

**Issue by Annoyed123x** [Ultimaker/Cura#19824]
### Cura Version

5.7.1

### Operating System

windows 11

### Printer

ulimaker s3

### Describe your model

bolt, only way to print without support on the threads is to completely turn off support

### Add your .zip here ⬇️

![image](https://github.com/user-attachments/assets/3cf4c031-f8e2-4cad-abf8-50e7f67b773b)

**Comment by Annoyed123x** [comment]
Solved. Cura can't seem to use support blocker if you are printing from nozzle #2.

**Comment by fieldOfView** [comment]
Check the "Support horizontal expansion" setting for your second nozzle. Set it to 0.

**Comment by Annoyed123x** [comment]
Sorry, I went and got a different print running. I'm not sure I see that setting you are referring to. 
Both nozzles seem to have the same settings 
![image](https://github.com/user-attachments/assets/212b468d-204c-4709-a2a6-a7d4c4616811)
Update though, if I have both nozzles enabled it will generate correctly. If just nozzle 1 is enabled, it also works. But if I only have nozzle 2 enabled is when the error shows up. 
![image](https://github.com/user-attachments/assets/204a5cd1-bde0-48b6-86d0-5ffebd56544f)
![image](https://github.com/user-attachments/assets/4d84c4b6-58fa-4fe0-8e86-4010aa2b2c86)

**Comment by Annoyed123x** [comment]
That's the one. Didn't realize I needed to reassign the blocker also.
