### ISSUE TITLE
Tree support Causes slicer fail

### ISSUE THREAD

**Issue by gageLink** [Ultimaker/Cura#19825]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender 3

### Name abnormal settings

Support type - tree

### Describe model location

Yes

### Describe your model

Half a chain link. Has been sliced before, only setting I changed was support type, and changing it back to normal causes it to not fail. Moving the model will also stop it from failing. Seems like the issue is slicing a model with tree supports while the model is in the default position.

### Add your .zip here ⬇️

[CE3E3V2_Staff Chain.zip](https://github.com/user-attachments/files/17547845/CE3E3V2_Staff.Chain.zip)

**Comment by Asterchades** [comment]
Make sure to update your Cura installation. Multiple bugs with Tree Supports were already fixed with the release of 5.7.0, as were several generic slicing bugs. The current release version is 5.8.1 (released August 30) and 5.9.0 is currently in open beta.

**Comment by GregValiant** [comment]
Cura 5.5 an 5.6 had problems slicing certain models, and with supports.  Those were well known bugs and have been fixed.
I agree with Asterchades that upgrading to one of the latest stable versions (5.8.0 or 5.8.1) will likely fix your problem.

I'll mark this as a duplicate and go ahead and close it as the problem has been addressed.  If you continue to have problems with a new version let us know.
