### ISSUE TITLE
Wrong placement after slice

### ISSUE THREAD

**Issue by vtl-btz** [Ultimaker/Cura#19838]
### Cura Version

5.*

### Operating System

Windows 10

### Printer

Any

### Reproduction steps

1. Place the model in the air without or with manual supports (Automatically Drop to build plate is disabled in settings)
2. Slice

### Actual results

No manual support and model have been dropped to the bed

### Expected results

Expected sliced in the air with or without manual supports

### Add your .zip and screenshots here ⬇️

![image](https://github.com/user-attachments/assets/7ee5335c-d228-422e-beac-95666ebd6f4f)

**Comment by fieldOfView** [comment]
See the setting "Remove Empty First Layers". This is enabled by default, and for your usecase you will want to disable it.
