### ISSUE TITLE
Way to cancel Octoprint upload

### ISSUE THREAD

**Issue by changedsoul** [Ultimaker/Cura#1983]
Would be nice to cancel an octoprint upload. I have had a few hang on me for what every reason, poor wifi, bug in cura, who knows. 
A way to cancel other than restarting would be a great addition.

**Comment by fieldOfView** [comment]
I implemented that this week, and mistakenly added it to the 2.6 branch so you won't even have to wait for Cura 2.7. 

The feature will be part of the official 2.6 release soon.
