### ISSUE TITLE
cieere inmediato del programa cuando añado gcode

### ISSUE THREAD

**Issue by ismaelgomez01** [Ultimaker/Cura#19844]
### Cura Version

5.8.1

### Operating System

windows 11

### Printer

artillery hornet

### Reproduction steps

abro el programa
añado un archivo stl
añado codigo gcode
se cierra el programa

### Actual results

el programa se cierra cuando añado gcode

### Expected results

el programa se cierra cuando añado gcode

### Add your .zip and screenshots here ⬇️

el programa se cierra cuando añado gcode

**Comment by GregValiant** [comment]
Thanks for the report.
What do you mean when you say "When I add Gcode"?
The normal way is:
1. Start Cura
2. Load an STL
3. Slice
4. Save the Gcode to removeable SD card, or to the hard drive.
    a. If copied to the hard drive it would need to then be copied to an SD card, or sent via some other means.
6. Print the file.
