### ISSUE TITLE
Bug no pós processamento

### ISSUE THREAD

**Issue by ramon202424** [Ultimaker/Cura#19862]
https://github.com/user-attachments/assets/08d6a4e1-fdea-4a54-aac8-9a8d3bc46b8a

https://github.com/user-attachments/assets/1092bfb8-85d3-4885-988d-ed3368de2637

![IMG_20241105_182340](https://github.com/user-attachments/assets/b2ab8f00-5496-4df3-81bf-6ec78f7a97b4)

![IMG_20241105_182611](https://github.com/user-attachments/assets/a4a75eef-68db-4cdd-81bd-5f8907d67e7c)
### Cura Version

5,8,1

### Operating System

Windows 11 

### Printer

Ender 3v2 neo

### Reproduction steps

Pegue um projeto e coloque para fazer troca de cor no pós processamento 

### Actual results

Chegando na camada desejada da troca de cor o comando e feito levando a cabeca de imprenssao para o canto da mesa logo apos chegar no local seguro da troca do filamengo o eixo Z aparece como 0 no monitor ... acionando para voltar a imprenssao o mesmo nao reconhece mais a altura do eixo Z assim entao comecando a imprimir no ar por que conta do 0 que estava na para para cima e nao volta na imprenssao que esta na mesa 

### Expected results

deveria acontecer da cabeca de imprenssao voltar a imprimir na imprensao que ja estava na mesa .obs usei o prusa slicer e a imprensora reconheceu o eixo Z na para de troca de cor normalmelte ... espero que resolvam isso gosto muito de usar o cura ...

### Add your .zip and screenshots here ⬇️

.

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for project files so we can check all the settings and see what happened.  I use PauseAtHeight a lot and I am familiar with Filament Change.  Filament Change passes all the parameters to the firmware which then decides how to handle the pause.  PauseAtHeight does not depend on the firmware.  It would be good to know which one you are having trouble with.  No one else has reported any problems and neither script has been changed for several versions.

Please post a project file.  You cannot post files by email so you will need to zip the project and post it directly here.  You might post the problem Gcode as well.  More information is better.

**Comment by ramon202424** [comment]
Testei a opção Filamento Change aconteceu o mesmo erro começa a imprimir quando manda o comando para troca de cor ela subiu até os 20mm depois quando voltei a impressão novamente voltou a imprimir no ar com menos distância do que a outra opção mais mesmo assim não volta na impressão

**Comment by ramon202424** [comment]
Não tem como ter nada de errado com meus arquivos são arquivos que já imprimi outra vezes mais de 10 vezes e sempre dava certo e também não acredito que seja algo com sensor do equipamento já que ele faz o zeramento normal

**Comment by GregValiant** [comment]
I cannot duplicate the problem using my settings.  I don't see any problem in the code for PauseAtHeight or FilamentChange (which at any rate work completely differently) and yet you have the problem with both of them.
I'll close this now because without a project file nothing further can be done.  If you provide one then this can be re-opened.  I hope you understand.
