### ISSUE TITLE
Загрузка первого STL файла выполняется очень медленно

### ISSUE THREAD

**Issue by sv-lary** [Ultimaker/Cura#19861]
### Cura Version

5.4.0

### Operating System

Linux Fedora 41

### Printer

Creality Ender 5

### Reproduction steps

1. Запустил приложение Cura
2. File / Open File(s) 

### Actual results

Приложение очень долго (2-3 минуты) замирает. После этого выполняется загрузка STL файла. Все последующие загрузки STL файлов выполняются быстро.

### Expected results

Я хочу ускорить загрузку первого STL файла.

### Add your .zip and screenshots here ⬇️

![Cura](https://github.com/user-attachments/assets/372c9bc6-c1f1-4f83-a5a0-77867ccd6abb)

**Comment by GregValiant** [comment]
Thanks for the report.
The USB printing plugin has been known to cause this behavior.
Go to the "Marketplace" (button in the top right of the Cura workspace) and click on the "Gear" icon.  Scroll down and disable "USB Printing".
If you have USB devices plugged into the computer and they are configured as "serial" devices, then Cura tries to connect with them.  It can take a while to figure out that it can't connect to a pair of headphones and then the STL loads.

Let us know if that fixes the problem.  If it does then I'll mark this as a duplicate report.
