### ISSUE TITLE
Luffy+bust+v1.stl

### ISSUE THREAD

**Issue by matiousoan** [Ultimaker/Cura#19888]
### Cura Version

cura 5.6.0

### Operating System

Windows 11

### Printer

wahnao d12.230

### Describe your model

c'est la premier fois que je l'utilise 

### Add your .zip here ⬇️

sa me fait une erreur Lore de la découpe

**Comment by GregValiant** [comment]
Without a project file we cannot duplicate the problem.
Cura 5.5 and 5.6 had slicing problems.  Those problems were addressed in 5.7.1.  I suggest you upgrade to 5.8.1 which is the latest stable version.
I'll mark this as a duplicate and close it as the problem no longer exists.
