### ISSUE TITLE
Can I modify the GCode Flavor?

### ISSUE THREAD

**Issue by Super169** [Ultimaker/Cura#1988]
I'm going to use Cura with my old 3D printer, a Makerbot Replicator Dual clone.
I tried to use the Makerbot Replicator profile, but I find that the gcode generated does not work, it does not match the gcode customized by makerbot.

For example,  the following code was generated by CURA:
```
;FLAVOR:Makerbot
;TIME:29
;Generated with Cura_SteamEngine 2.6.0-BETA
M190 S70
M104 T1 S200
M109 S0
M109 T1 S200
```

M190 S70 - intends to wait for bed temperature, but in Makerbot machine it should be M109 S70 T0

Is there any way I can modify the template of the gcode flavor?

**Comment by Ghostkeeper** [comment]
Not really. We didn't make that customisable but basically implemented the g-code flavours in CuraEngine.

If you have experience with C++ programming you could try to modify this. It's in the GCodeExport class. But it's a bit mixed-up like.

If you have experience with Python programming the alternative would be to make a post-processing script that keeps track of the current tool (iterate over all lines, and track the tool when you encounter the regex `^T\d+$`). When it encounters a line that starts with `M190 ` you would add the string ` T{tool}`.

Both of these solutions require programming skills though.
