### ISSUE TITLE
I have sliced this file before and it won't let me now?

### ISSUE THREAD

**Issue by gillyag** [Ultimaker/Cura#19918]
### Cura Version

5.4.0

### Operating System

MACOS Sequoia 15.1

### Printer

SOVOL SV06

### Name abnormal settings

sliced 4 models before no problem. sliced this model before 

### Describe model location

it started to slice and then stopped when I raised it on the y 2 mm

### Describe your model

yes, printed before. it is a chained angel kneeling

### Add your .zip here ⬇️

[ChainedAngelStatueD.stl.zip](https://github.com/user-attachments/files/17791277/ChainedAngelStatueD.stl.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Sometimes model errors can be overcome, but some are severe enough to give Cura problems.
![image](https://github.com/user-attachments/assets/ba5abbc1-f1b4-4267-84b4-d93acc9d8674)

There aren't many errors but they are enough to fool a slicer.
I'll mark this as a duplicate and close it.  Cura 5.4 is 7 versions out of date.  I suggest you upgrade to 5.8.1.  5.9.0 will be out in a week or so.

This is the un-repaired model in 5.8.1.  I never trust the slices of models that have errors. 
![image](https://github.com/user-attachments/assets/8b90cd13-cbf9-4106-8b7a-75b0d7724405)

**Comment by gillyag** [comment]
Hi!Thank you very much! I didn’t design it, and like I said, I’ve printed it before, I didn’t know there was a problem in the water tightness of the model. I also thought Cura auto-updated so I will try to figure that out now. Sorry for the trouble.- GillianOn Nov 17, 2024, at 12:17, GregValiant ***@***.***> wrote:﻿
Thanks for the report.
Sometimes model errors can be overcome, but some are severe enough to give Cura problems.
image.png (view on web)
There aren't many errors but they are enough to fool a slicer.
I'll mark this as a duplicate and close it.  Cura 5.4 is 7 versions out of date.  I suggest you upgrade to 5.8.1.  5.9.0 will be out in a week or so.
This is the un-repaired model in 5.8.1.  I never trust the slices of models that have errors.
image.png (view on web)
