### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by elquattro** [Ultimaker/Cura#19916]
### Cura Version

5.8.0

### Operating System

OS X Sequoia 15.1

### Printer

Ultimaker S5

### Describe your model

a mainboard cover to replace a broken one

### Add your .zip here ⬇️

[UMS5_mobocover v1.zip](https://github.com/user-attachments/files/17788431/UMS5_mobocover.v1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
It won't slice with your "Digistruct-1-DF" printer active ("Backend exited abnormally with return code 3221226505!") but it sliced with the other 4 printers I tried including a "stock" UM S5.
Did you use the S5 printer definition in Cura or was it a custom definition file from Digistruct?
