### ISSUE TITLE
Coasting speed did not work with aktual speed on 2.5

### ISSUE THREAD

**Issue by 4styler** [Ultimaker/Cura#1991]
Version 2.5:
However, if the printer prints slower due to cooling, the coasting will still run at 100% of the printing speed resulting in severe irregularities in the perimeter. The perimeter is than smaller where the coasting occurs.

**Comment by BagelOrb** [comment]
Fixed: https://github.com/Ultimaker/CuraEngine/commit/53d4fa9db1f2f9bb412f7033f0be8ba6ed051f06

**Comment by BagelOrb** [comment]
Thanks for the report!
