### ISSUE TITLE
try to slice a module

### ISSUE THREAD

**Issue by AlphaBull** [Ultimaker/Cura#19928]
### Cura Version

5.7.0

### Operating System

windows10

### Printer

ender 3 pro

### Describe your model

i had it sliced bevor succesfully

### Add your .zip here ⬇️

![image](https://github.com/user-attachments/assets/1b0cbec9-1e95-4f77-8c26-f157a8332a48)
![image](https://github.com/user-attachments/assets/fc4e1df7-ece6-487a-956f-0958f969fa37)

**Comment by GregValiant** [comment]
You haven't given us anything to work with here.
I'll go ahead and close this.  If you feel it should be investigated then please include supporting files (Cura Project File and cura.log file) so this can be investigated.  I can re-open this if you do that.
