### ISSUE TITLE
Unsuccessful cut

### ISSUE THREAD

**Issue by AlexLyandres** [Ultimaker/Cura#19925]
### Cura Version

UltiMaker-Cura-5.9.0-beta.1-macos-X64

### Operating System

MAC OS Ventura 13.7.1

### Printer

Creality Ender 3 v2

### Describe your model

Extruder MK3

### Add your .zip here ⬇️

<img width="582" alt="Снимок экрана 2024-11-18 в 21 48 22" src="https://github.com/user-attachments/assets/be1bb9d3-79aa-4525-bf31-3eee61ae3c95">

**Comment by GregValiant** [comment]
You have given us no information and nothing to investigate.  I'll go ahead and close this.  If you wish to report a bug please follow the instructions on the form.
