### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by ethan1234567890hub** [Ultimaker/Cura#19929]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

neptune 3 pro

### Name abnormal settings

no

### Describe model location

y

### Describe your model

i have sliced it befor

### Add your .zip here ⬇️

[Blade v312345667989.zip](https://github.com/user-attachments/files/17822615/Blade.v312345667989.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
5.5 and 5.6 had issues slicing certain models (organic shapes for instance).  I recommend upgrading to 5.8.1.

I'll go ahead and close this as it was a known bug in 5.6 and appears to have been fixed.
