### ISSUE TITLE
2.6 beta MAC material save issues

### ISSUE THREAD

**Issue by schestag3d** [Ultimaker/Cura#1993]
I use the 2.6 beta for mac. If i save a temperature at a new created filament, the temperature doesn't save well. I typed in 230 degree, and when the print starts, it is 200 degree.

**Comment by nallath** [comment]
Could you share the project file?

**Comment by fieldOfView** [comment]
Probably the same issue as #2007 
@schestag3d, can you confirm that you use a single extrusion printer based on "Custom FDM Printer"?

**Comment by ethanspitz** [comment]
I have the same issue, but on windows and #2007 seems to have resolved it for me!
