### ISSUE TITLE
option to append print time to file name

### ISSUE THREAD

**Issue by michaelshewitt** [Ultimaker/Cura#19947]
### Is your feature request related to a problem?

...I have saved number of files ready to load and print but then cannot remember the estimated print time of each to allow me to efficiently schedule - say, choosing to commence printing an item when going to bed that will be finished early enough in the morning to allow me to start another print before leaving for work.

### Describe the solution you'd like

Preferences>General>Opening and saving files
A checkbox that will, when checked, append the estimated print time to the system-generated file name

### Describe alternatives you've considered

...I currently do this manually (when I remember to)

### Affected users and/or printers

All

**Comment by Asterchades** [comment]
This can already be achieved with both the *Gcode Filename Format Plus* and *Printjob Naming* plugins on the Marketplace.

**Comment by GregValiant** [comment]
This should work in either of those plugins.
[base_name] [print_time_hours]h[print_time_minutes]m
That would result in a suggested file name similar to:
Timer Shade 6h20m.gcode

@michaelshewitt does one of the plugins work for you?  Can I close this?
