### ISSUE TITLE
Can't open other files, Cura doesn't close

### ISSUE THREAD

**Issue by steven5655** [Ultimaker/Cura#19956]
### Cura Version

5.9.0

### Operating System

Mac OS X Sequoia 15.1

### Printer

Ender 3 V3 SE

### Reproduction steps

Open a file then when I close cura doesn't close or open any other file I have to right click and quit few time to close it and open another file

### Actual results

Cura doesn't close or open another file

### Expected results

Cura close or open another file

### Add your .zip and screenshots here ⬇️

No zip

**Comment by GregValiant** [comment]
Thanks for the report.
There have been a few instances where users had USB devices plugged in to a computer USB port (headphones and such) and internally those devices are configured as "Serial Devices".  Cura's "USB Printing" plugin is enabled by default and so when Cura starts - it sees the serial device and assumes it's a printer.  Cura keeps sending "M105" to a pair of headphones which keep going "What??" and the UI is unresponsive while that is going on.
Go to the MarketPlace in Cura and click on the "Gear" icon.  Scroll down and disable "USB Printing".  Restart Cura and see if that resolves the problem.
