### ISSUE TITLE
Adhesion button showing off in shortcut menu when is switched on in advanced menu

### ISSUE THREAD

**Issue by foxy51** [Ultimaker/Cura#19953]
### Cura Version

5.9

### Operating System

Windows 11

### Printer

Factor 4

### Reproduction steps

Switched on the adhesion in the advanced menu

### Actual results

Still indicates off in shortcut menu at the top of the prepare screen.

### Expected results

The adhesion icon should show on in the top Right Hand bar.

### Add your .zip and screenshots here ⬇️

[UMF4_GORDIANNO1V1.zip](https://github.com/user-attachments/files/17918127/UMF4_GORDIANNO1V1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
It appears that the quick menu "Adhesion" button is not updating when "Skirt" is selected.  It works correctly for "None", "Brim", and "Raft".
Someone from the Cura team will take a look.

**Comment by foxy51** [comment]
Thanks for the prompt reply.
Kind regards M. Fox

**Comment by GregValiant** [comment]
I guess I can go ahead and close this as it is expected behavior.  @foxy51 let me know if you think it is premature.
