### ISSUE TITLE
Build Plate Adhesion - Skirt Settings Ignored

### ISSUE THREAD

**Issue by JHBP2** [Ultimaker/Cura#1996]
I set Build Plate Adhesion Type to None, but it still creates a skirt. The Skirt Distance setting is also ignored. It is stuck on 0, in contact with the first layer. Tried switching profiles, exporting / importing, turning off and on. Still ignores it.

![image](https://user-images.githubusercontent.com/29574503/27334553-086993e0-560d-11e7-942d-3ed98a20a2be.png)

**Comment by nallath** [comment]
Uh, what kind of machine do you have? If a machine has one extruder, it shouldn't have the extruder tab.

**Comment by JHBP2** [comment]
The machine only has one extruder.

**Comment by JHBP2** [comment]
I also noticed that even though the skirt settings are displaying
incorrectly, and rendering incorrectly in layer view, turning it off
actually works in the gcode...?!? I am not sure if the distance setting
would do the same i.e. display as 0, render as 0, but then work correctly
and leave the proper gap in a real print.

**Comment by JHBP2** [comment]
Nope... The Skirt Distance setting is being ignored in the gcode. This "Extruder 1" could be the problem... It does not seem to pick up the settings, and may be overriding them...?

![image](https://user-images.githubusercontent.com/29574503/27430461-050be74a-578c-11e7-9296-2a64083309ab.png)

**Comment by fieldOfView** [comment]
@JHBP2: you're using "Custom FDM Printer", right? In that case this is fixed with #2009

You can test this fix:
* Download this file: https://raw.githubusercontent.com/fieldOfView/Cura/adc547fa36b3edc288369543d1c97c648f6f22c5/plugins/CuraEngineBackend/StartSliceJob.py
* Replace the file on your computer that is located in [cura install location]/plugins/CuraEngineBackend (eg: ```C:\Program Files\Cura 2.6\plugins\CuraEngineBackend\StartSliceJob.py``` on windows) 
* Restart Cura and test if it works now.

**Comment by JHBP2** [comment]
@fieldOfView Thanks! Yes, I am using "Custom FDM Printer"... This fix looks good so far in Layer view, but I'll have to wait until my current print is finished tomorrow before I can do a real print test. Thanks again 👍

![image](https://user-images.githubusercontent.com/29574503/27431046-5856a1ae-578e-11e7-8705-ff95c8294d9c.png)

**Comment by fieldOfView** [comment]
If it is good in layerview, it is good in the print.

- knocks on wood -

**Comment by JHBP2** [comment]
@fieldOfView Success! Skirt settings work with this fix!

![image](https://user-images.githubusercontent.com/29574503/27482364-830c2bea-5864-11e7-899d-575cf43cde0e.png)

![image](https://user-images.githubusercontent.com/29574503/27482370-885d0376-5864-11e7-85ca-3f3ed06bb6dc.png)
