### ISSUE TITLE
Cannot open files of the type of C:/Users/vncnt/Downloads/Katana - 6820081.zip

### ISSUE THREAD

**Issue by VMD2013** [Ultimaker/Cura#19973]
### Cura Version

 5.9

### Operating System

 Windows 11

### Printer

Creality Ender 3

### Reproduction steps

Downloaded image from thinkiverse to open file
Error message occurred that says (Cannot open files of the type of C:/Users/vncnt/Downloads/Katana - 6820081.zip)

### Actual results

Image does not populate into UltiMaker

### Expected results

In the past we did not have issues with images populating into Ultimaker from Thinkiverse or from downloads like this ->Cannot open files of the type of C:/Users/vncnt/Downloads/Katana - 6820081.zip

### Add your .zip and screenshots here ⬇️

Cannot open files of the type of C:/Users/vncnt/Downloads/Katana - 
[Uploading Katana - 6820081.zip…]()
6820081.zip

**Comment by GregValiant** [comment]
Thanks for the report.
Cura has never been able to open zip archive files.  You must extract the files first.
In File Explorer - right-click on the file and select "Extract All...".
I'll remove the bug label and close this.  Let me know if you feel that is premature.
![image](https://github.com/user-attachments/assets/297fe890-aac0-41e3-b599-25ac57e21d59)
