### ISSUE TITLE
Slicing failed 

### ISSUE THREAD

**Issue by williamho1234** [Ultimaker/Cura#19995]
### Cura Version

5.9.0

### Operating System

Windows 10

### Printer

Elegoo neptune 4 max

### Name abnormal settings

n/a

### Describe model location

n/a

### Describe your model

several models pieced together

### Add your .zip here ⬇️

[Crash sliced.zip](https://github.com/user-attachments/files/18011797/Crash.sliced.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The project sliced for me without a problem.
Use the "Help | Export Package for Technical Support" command.  Zip that 3mf file and post it here.  It will have your log file in it and maybe there will be a clue as to what is happening on your system.

BTW the little round model has numerous errors in it and it should be repaired.  It is also extremely high resolution and is made up of 1234 separate pieces.  That might be part of the problem.
Here I have split the model into parts with Mesh Tools and the random piece I selected is miniscule.
![image](https://github.com/user-attachments/assets/c6aef091-1642-41a9-a734-047a7650438a)
