### ISSUE TITLE
Cura 5.6 and 5.9 crashing upon opening a file

### ISSUE THREAD

**Issue by cmjones1234** [Ultimaker/Cura#20010]
### Cura Version

5.9.0

### Operating System

Linux

### Printer

Ender 3 Pro

### Reproduction steps

1 Started linux appimage normally
2 Program opened correctly to the build plate
3 Able to access all menus fluidly
4 Attempted to use FILE > OPEN FILE to open folder to import a .stl
8 Cura disappears and has to be restarted
9 Started linux appimage normally again
10 Program opened correctly to the build plate
11 Still able to access all menus fluidly
12 Attempted to use FOLDER icon in top left to open folder to import a .stl
13 Cura disappears and has to be restarted
14 Unable to open a file
15 Attempted with older versions up to 5.6.0 with same results.

### Actual results

Cura crashes when attempting to open any file

### Expected results

File folder should open to select printable file extensions.

### Add your .zip and screenshots here ⬇️

/home/UltiMaker-Cura-5.9.0-linux-X64.AppImage
/home/UltiMaker-Cura-5.6.0-linux-X64.AppImage

**Comment by GregValiant** [comment]
Thanks for the report.
Before you attempt to open a file use the "Help | Show Configuration Folder" command to locate the Cura.log file.
Try to open a file.  After the crash go to the Cura.log file, zip the file, and post the zip folder here.
