### ISSUE TITLE
Anti-overhang meshes are ignored if they go out of bounds

### ISSUE THREAD

**Issue by TheAMM** [Ultimaker/Cura#2001]
This makes excluding generated supports near build plate edges/corners bothersome, as the user will have to make sure the A-O mesh won't go out of bounds *or* use several meshes near corners.

As meshes marked anti-overhang are not printed, they should not be ignored for going out of bounds.

**Example images** *(although not from a real use-case)*
Functioning support exclusion
![image](https://user-images.githubusercontent.com/6820963/27372183-57d9d5a2-566c-11e7-8503-a72746fd064e.png)
Anti-overhang mesh ignored for going out of bounds
![image](https://user-images.githubusercontent.com/6820963/27372198-6ab49acc-566c-11e7-8e05-04eb855d53aa.png)

**Comment by nallath** [comment]
For our reference CURA-3951

I tried to make a quick fix for this (as i thought this was "just" a front-end issue), but it seems the engine also needs a bit of work to fix this.

**Comment by Ghostkeeper** [comment]
The engine typically doesn't take these bounds into account at all, right? Only to find the centre of the build plate sometimes.

**Comment by Ghostkeeper** [comment]
Fixed this here: https://github.com/Ultimaker/Cura/commit/71c146f4379c24af2e05ffadd690c3b24e5ed4eb
