### ISSUE TITLE
Unable to add any non-networked printers.

### ISSUE THREAD

**Issue by Innovate3D** [Ultimaker/Cura#20043]
### Cura Version

5.9

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

1. I tried to add another printer in cura since I recently got the Elegoo Neptune 4 plus.

### Actual results

It pulled up the screen like normal, but it didn't let me add any printers.

### Expected results

It should let me add another printer profile.

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-12-14 195909](https://github.com/user-attachments/assets/f5d36c00-c9a6-4609-8b4b-b9952df20e9c)

**Comment by Innovate3D** [comment]
Thank you this worked

**Comment by GregValiant** [comment]
Thanks @fieldOfView .  I'll go ahead and close this.
