### ISSUE TITLE
print fails

### ISSUE THREAD

**Issue by hideawayhobbies** [Ultimaker/Cura#20042]
### Cura Version

5.9

### Operating System

windows 10

### Printer

ender 3 v2

### Reproduction steps

sliced claimed good slice loaded file adjusted printed and calibrated now wont print was printing on prior update that was not beta now does not fallow its commands starts first half then makes a mess of movements

### Actual results

a mess

### Expected results

print like it was

### Add your .zip and screenshots here ⬇️

i have no files to share

**Comment by GregValiant** [comment]
Without at least a gcode file that shows that the error is in fact within the Cura generated gcode, there isn't anything we can do.

This sort of thing is always a printer problem, but if you post a gcode file I will look at it.
If you are printing from the SD card then you can try reformatting the card (to FAT32) and that will often fix the problem.  A bad memory sector on a card can cause the printer to start reading one file and jump to another right in the middle of the print.
