### ISSUE TITLE
Fan not run

### ISSUE THREAD

**Issue by tanbruk** [Ultimaker/Cura#20053]
### Cura Version

5.9.0

### Operating System

Win 10

### Printer

two trees Sapphire plus

### Name abnormal settings

all model

### Describe model location

no

### Describe your model

all

### Add your .zip here ⬇️

non run fan

**Comment by GregValiant** [comment]
It is impossible to know what to do with this as you have not posted any files to investigate and only provided 3 words regarding your problem.
I'll go ahead an close this.  If you post a project file or gcode file as you were asked to when you filled out the form this maybe something could be done.
