### ISSUE TITLE
Build plate not loading when program opened

### ISSUE THREAD

**Issue by MadeInAK** [Ultimaker/Cura#20050]
### Cura Version

5.9.0

### Operating System

Windows 11

### Printer

Ender pro 3

### Reproduction steps

Downloaded the program. First time opening it build plate was there and was able to slice as normal. Closed program. Next time I opened it build plate would not load. Uninstalled and installed again. Build plate would load first opening but after closing program build plate will not load
![2024-12-18 21_30_11-](https://github.com/user-attachments/assets/89ed736f-c970-44a1-a969-9e7cf44cc47c)

### Actual results

Build plate wont load

### Expected results

Build plate should load

### Add your .zip and screenshots here ⬇️

![2024-12-18 21_30_11-](https://github.com/user-attachments/assets/aedddb03-51fe-4744-84e3-aa006f5ebc18)

**Comment by MadeInAK** [comment]
Windows had an update that needed to be installed - seems to be fix after updating windows

**Comment by GregValiant** [comment]
Thanks for the report.
I'll leave the bug label on this (in case it comes up again) but I'll go ahead and close this as it seems to have been a Windows issue.
