### ISSUE TITLE
slicing failed!!

### ISSUE THREAD

**Issue by lamoreaux90** [Ultimaker/Cura#20062]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

elegoo neptune 3 pro

### Name abnormal settings

no

### Describe model location

no

### Describe your model

yes

### Add your .zip here ⬇️

[Jig for Paracord Bracelets - 5524616 (2).zip](https://github.com/user-attachments/files/18222546/Jig.for.Paracord.Bracelets.-.5524616.2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The round nut could use repair, but I don't think the errors are enough to keep it from slicing.  I didn't have any trouble slicing all the models at once on this Win10 laptop in 5.9.0.

Cura 5.6 (and 5.5) had problems slicing certain types of models.  I suggest you upgrade to the latest Cura version.

I'll mark this as a duplicate report and go ahead and close this as the issues were fixed starting with 5.7.0.  I hope you understand.
