### ISSUE TITLE
[Running Cura from Source] Unable to find `virtual_python_env.ps1` after configuring with Conan

### ISSUE THREAD

**Issue by FreeFallingSnow** [Ultimaker/Cura#20084]
### Cura Version

5.10.0-alpha.0

### Operating System

Windows 11

### Description
I have followed the instructions in the [Running Cura from Source · Ultimaker/Cura Wiki](https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source) to configure the environment using Conan. However, after completing the configuration steps, I am unable to locate the `virtual_python_env.ps1` file, which is needed for setting up the virtual Python environment.

### Reproduction steps

1. Follow the steps in the deployment wiki.
2. Configure the environment using Conan as instructed.
3. Look for the `virtual_python_env.ps1` file in the `Cura/build/generators/`.

### Actual results

The `virtual_python_env.ps1` script should be available as mentioned in the wiki.

### Expected results

The `virtual_python_env.ps1` file is missing.

### Additional information:

- The `virtual_python_env.bat` file is present, but the PowerShell script (`virtual_python_env.ps1`) is not available.
- I am working on a Windows machine and am trying to set up the environment for Cura.

Could you please assist in providing the missing script or clarifying the setup process?

Thank you!
[tree.txt](https://github.com/user-attachments/files/18273551/tree.txt)

**Comment by zebin-xlogic** [comment]
you can find activate.ps1 under Cura\build\generators\cura_venv\Scripts , but i recommend you creat a new env. 

Run the following commands in the new env. 
pip install -r build/generators/pip_requirements_core_basic.txt
pip install -r build/generators/pip_requirements_core_hashes.txt

Then place all the files from the cura\venv folder, except for python312.dll, into the DLLs folder of your Python interpreter, as that is where Python extensions are managed

open project 'cura' on pycharm and attach the Uranium folder to Cura. 
run cura_app.py with PyCharm

The above are the steps I followed to successfully run it. I hope they can help you.

**Comment by FreeFallingSnow** [comment]
> you can find activate.ps1 under Cura\build\generators\cura_venv\Scripts , but i recommend you creat a new env.
> 
> Run the following commands in the new env. pip install -r build/generators/pip_requirements_core_basic.txt pip install -r build/generators/pip_requirements_core_hashes.txt
> 
> Then place all the files from the cura\venv folder, except for python312.dll, into the DLLs folder of your Python interpreter, as that is where Python extensions are managed
> 
> open project 'cura' on pycharm and attach the Uranium folder to Cura. run cura_app.py with PyCharm
> 
> The above are the steps I followed to successfully run it. I hope they can help you.


It looks like Cura is running successfully. Thank you for your help!
