### ISSUE TITLE
Not loading or slicing in Portugese

### ISSUE THREAD

**Issue by Guisao5** [Ultimaker/Cura#2010]
Na linguagem em portugues nao aparece a mesa da maquina e nao e possivel carregar arquivos.

**Comment by Ghostkeeper** [comment]
I've tested the Portuguese language in Cura myself. Just retesting to confirm:

* The printer list is properly filled in when you click "Adicionar Impressora". Adding a printer works fine.
* Loading a file works fine, and it starts to "Fatiando" right away.

In other words, I can't reproduce your problem.

**Comment by Ghostkeeper** [comment]
Perhaps you can share a log file with us? I'd expect these problems to show up there.

**Comment by ChrisTerBeke** [comment]
Closing since we cannot reproduce and no futher information has been provided. Please comment if this is still an issue for you.
