### ISSUE TITLE
Feature request: Change LED brightness on UM3 through Cura

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/Cura#2020]
With the video feed in Cura you can check what your UM3 is doing. As some people might be doing this pretty remote (via VPN), it would be nice to have a possibility in Cura to set the LEDs on the UM3. While you need the LEDs on to see what the printer is doing you might want to have them dimmed or off the major time. So in addition to the pause and cancel buttons in Cura I suggest a setting for the LED brightness on the interface page during print.

**Comment by nallath** [comment]
What would be good position to put the control for that do you think?

**Comment by Dim3nsioneer** [comment]
Somewhere left of the cancel button so people realise it's something they can change? Alternatively close to the preheat control.

**Comment by Dim3nsioneer** [comment]
something maybe like this:

-----------------
| - LEDs: 60% + |
-----------------

**Comment by UltiArjan** [comment]
+1

**Comment by Ghostkeeper** [comment]
Would've been nice to have, but our project manager just removed this from our planning because it was older than 12 weeks.
