### ISSUE TITLE
Custom FDM Extruder 1 not accepting changes

### ISSUE THREAD

**Issue by DkOuvE** [Ultimaker/Cura#2021]
Changing the filament when you only have 1 extruder and using a Custom FDM doesn't change the filament settings Extruder 1 is using.
    In other words, you can see a new filament has been selected in solid view as it changes colour, but Extruder 1 doesn't change.

Furthermore, the settings that you set don't transfer to the final gcode or layer view.
    For example I would change the infill to 100% from 0% and the final model will still only use 0% infill.

Fully uninstalling and reinstalling Cura has no effect.

Only when you add a second extruder does Extruder 1 begin to accept changes.

**Comment by fieldOfView** [comment]
Thanks for reporting. It has already been fixed here:
https://github.com/Ultimaker/Cura/pull/2009

I have heard there should be a Cura 2.6.1 soon, including this fix. You can fix it locally with these steps:
* Download this file: https://raw.githubusercontent.com/fieldOfView/Cura/adc547fa36b3edc288369543d1c97c648f6f22c5/plugins/CuraEngineBackend/StartSliceJob.py
* Replace the file on your computer that is located in [cura install location]/plugins/CuraEngineBackend (eg: ```C:\Program Files\Cura 2.6\plugins\CuraEngineBackend\StartSliceJob.py``` on windows). The file should already be there. If it is not, you are looking in the wrong location.
* Restart Cura and test if it works now.

**Comment by DkOuvE** [comment]
Thanks!
