### ISSUE TITLE
Line width problem in new layer view

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#2026]
I have noticed that the new layer view shows some pretty weird line widths. Here's an example:

![screenshot_2017-06-25_17-39-07](https://user-images.githubusercontent.com/585618/27517970-3a5e1722-59cd-11e7-81eb-4fdf00b8b266.png)
The top layer has two walls close together and with wall overlap compensation enabled, the outer wall gets thinned. But look at the outer wall in the above image, the longish straight segments are all too thin and the corners are rather bumpy. The actual print looks absolutely fine so it must be a graphics issue. This is just one example, I could post lots of images of other walls whose widths (in the layer view) are silly.
My current theory is that the array of line widths sent to the UI are not synchronised with the vertices. So in ProcessSlicedLayersJob, if I add this line (after line 128) to rotate the array of line widths:

line_widths = numpy.roll(line_widths, -1);

I now get this:
![screenshot_2017-06-25_17-46-17](https://user-images.githubusercontent.com/585618/27518030-38f4d366-59ce-11e7-9dac-1b656673308d.png)
Which is much more sensible and other wall lines that had weird widths now look good too so that rotation of the array is good for the walls. Unfortunately, it causes the skins and infill to be replaced with very thin lines as shown below and I don't know what to do next.

![screenshot_2017-06-25_17-48-05](https://user-images.githubusercontent.com/585618/27518048-8f926a4e-59ce-11e7-8668-4f8524e04027.png)
Could someone who understands this python + GL stuff please look into this as I don't want to waste loads of time working out a fix if someone who is familiar with the code can do the same in a fraction of the time?

**Comment by smartavionics** [comment]
OK, I figured out a fix so that now all lines are showing with sensible widths but I would be the first to admit that I am thrashing around in the dark here so it could well be that the real problem is elsewhere and this change is just compensating for a bug elsewhere?

**Comment by nallath** [comment]
@jackha You made the original implementation of this, what do you think?
