### ISSUE TITLE
15.06.2 Unable to set extruder head size

### ISSUE THREAD

**Issue by luotinen** [Ultimaker/Cura#203]
I have Ultimaker Original and I have manually added a second fan on the right side of the head. In previous Cura I've been able to set a custom clearance. In 15.06.2 this setting has been removed. How can I increase the clearance in the positive X axis side of the extruder head?

**Comment by Xisle** [comment]
What OS?

You can edit **ultimaker_original.json**. Look for this line:
     "machine_head_shape_max_x": { "default": 18 },

**Comment by luotinen** [comment]
Windows 8.1

Thanks for the workaround. :)

**Comment by nallath** [comment]
Actually this is not a work around; this is intended to work like this. This changes fundamental stuff of the machine and is seen as an advance use.
