### ISSUE TITLE
CURA 2.6 high cpu usage

### ISSUE THREAD

**Issue by hoegge** [Ultimaker/Cura#2040]
Is it really normal that CURA use around 25-50% CPU while printing? Assuming it just sends G-code to the printer (Prusa USB connected) - how can that take so much CPU?

**Comment by nallath** [comment]
Depends on the machine. The USB code isn't al that efficient either (as it's not something we're spending any time on). It could probably be done a whole lot better, but hardly any UM machines still work on USB.

**Comment by Ghostkeeper** [comment]
I can see it happening if it redraws the entire screen for every line of g-code in order to update the progress bar...

**Comment by jackha** [comment]
Deferred because of inactivity.

**Comment by digitalfrost** [comment]
Stale ticket.
This ticket refers to Cura 2.6 . and complains of high CPU usage.
Can be closed?

**Comment by hoegge** [comment]
Most likely (can be closed). I have left Cura for Prusa Slicer a long time ago ;-)
