### ISSUE TITLE
Split into parts

### ISSUE THREAD

**Issue by Guisao5** [Ultimaker/Cura#2052]
Group and Ungroup not active in menu

**Comment by nallath** [comment]
I just tried it; When I have multiple objects selected, the group & merge options are available. When i have a group selected, the ungroup is active.

**Comment by Guisao5** [comment]
Correct, but when the stl comes grouped do not ungroup, Cure 15 ungroups.

**Comment by nallath** [comment]
Ah, you mean split into parts? That's indeed not implemented for the new Cura yet.

**Comment by PJParish** [comment]
I'll follow it here.  Thanks.

**Comment by Ghostkeeper** [comment]
Our project manager just removed this feature from our planning because it was not modified for 12 weeks. Or rather, it would be next week.

**Comment by ScottWell1** [comment]
The feature is still desired.  It's a big loss for a lot of people coming from legacy Cura, particularly those with small build plates who need to split plated models into parts in order to print them.

**Comment by cscott** [comment]
Especially folks using services like thingiverse to get their STLs, who
don't necessarily have the ability to "not plate" unrelated parts.​  They
are at the mercy of whoever uploaded the STL (and that person's build plate
size).

**Comment by fieldOfView** [comment]
I am working on it as a plugin for the next version of Cura:
![meshtools](https://user-images.githubusercontent.com/143551/44579333-5783f980-a796-11e8-838f-1843ea1a0810.gif)

**Comment by fieldOfView** [comment]
"Split into parts" is now available as part of "Mesh Tools" in the Toolbox of Cura 3.5
