### ISSUE TITLE
can't save to sd card

### ISSUE THREAD

**Issue by rawdilz** [Ultimaker/Cura#2057]
it works the first time i save to card but if i clear the plate and try to save another project it doesn't save it. i have to close cure and reopen.

**Comment by kr15uk** [comment]
Same here.
I'm still able to save by manually browsing through the "Save File"
I'm on macOS 10.12.5, Cura 2.6.1

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/2024 and https://github.com/Ultimaker/Cura/issues/2038.
