### ISSUE TITLE
Everything prints as a support on Linux (both 2.6.1 and 2.4.0)--MacOS works fine

### ISSUE THREAD

**Issue by ppesek** [Ultimaker/Cura#2061]
I am having an odd issue where if I turn on supports and slice in Cura under Linux, the whole model prints as flimsy support-like material.  I have narrowed down the problem to only linux (2.6.1 and 2.4.0 AppImages under Ubuntu 16.04).  

Using MacOS Cura 2.4.0, I was not able to reproduce the problem using the same STL file.  Attached are example files that cause the issue to occur and a picture of the result.

[CuraIssue.zip](https://github.com/Ultimaker/Cura/files/1120269/CuraIssue.zip)

**Comment by ppesek** [comment]
I should probably add I printed using a Prusa i3 Mk2 with the latest firmware (3.11).

**Comment by smartavionics** [comment]
Hi, I am using the master branch on linux and it appears to slice OK, here's a typical cross section...
![screenshot_2017-07-03_19-49-09](https://user-images.githubusercontent.com/585618/27804808-d4dec132-6028-11e7-9f9b-e7149abf85db.png)

**Comment by ppesek** [comment]
It seems like you changed something in the settings to get that screenshot as the supports are closer together than I had them (not that it made a difference--started with something like what you had)--did you load the brokensupports profile I included?

**Comment by smartavionics** [comment]
Oops, no, I used a different profile. Here's another sample using your profile...
![screenshot_2017-07-03_19-59-57](https://user-images.githubusercontent.com/585618/27805072-50251476-602a-11e7-80e0-f2f8b7b9acc0.png)

**Comment by ppesek** [comment]
Yeah...the display is different on my end--notice the texture difference?  Not sure what is causing that as it prints the same way...

![screenshot from 2017-07-03 15-02-50](https://user-images.githubusercontent.com/24851355/27805129-bede8426-6000-11e7-865d-38b269ab82a3.png)

**Comment by smartavionics** [comment]
You are displaying the travels (blue) but I did not? It's quite hard to see the detail on your screenshot.

**Comment by ppesek** [comment]
Notice the texture on the red part though?  That remains if I turn blue off and seems to represent the main difference.  It actually looks like that if I turn supports off (though they are necessary to print this)--so maybe the issue is unrelated to supports.  My initial theory was that it was printing the whole thing as 'like a support structure'--but maybe not...

**Comment by smartavionics** [comment]
To me, that texture just looks like aliasing in the graphics? Does it alter as you rotate the view?

**Comment by ppesek** [comment]
It does--guess you are right...  Still not sure why my models are printing as flexible mush suddenly.  The same STL sliced on a Mac printed fine (and with Slic3r on Linux also).

**Comment by Ghostkeeper** [comment]
The specialised profile included in the .zip doesn't seem to be used in your MacOS g-code. It specifies a layer height of 0.2mm. The object is about 4cm high. In the MacOS g-code there are 411 layers and in the Linux g-code there are 206 layers, so the MacOS clearly uses 0.1mm layer height and the Linux g-code uses 0.2mm layer height. That's the difference you're seeing.

So it looks like the 0.2mm profile just isn't working properly for your printer. Have you tried reducing the speed a bit? Perhaps the nozzle is a bit half-clogged and isn't keeping up with the double extrusion rate that's required for the greater layer height?

**Comment by BagelOrb** [comment]
This seems to be a hardware problem unrelated to Cura.
