### ISSUE TITLE
skirt setting isnt working

### ISSUE THREAD

**Issue by 40kdominator** [Ultimaker/Cura#2066]
when I go to print build plate adhesion it resets the parameters to brim I go and change it to skirt but I go back and it turned off build plate adhesion but when I turn it back on it resets again so there is no way to use the skirt it just started yesterday

**Comment by nallath** [comment]
What version did you use? 
What machine did you have active?
Could you post logs?

**Comment by 40kdominator** [comment]
i tried 2.6.1 and 2.3.1 i was using my own costom 3d printer i have no idea what post logs is?

**Comment by Ghostkeeper** [comment]
Instructions for sharing the logs are here: https://github.com/Ultimaker/Cura#logging-issues

Perhaps you're using a dual extrusion printer and the second extruder still specifies that it wants to print with a brim.
