### ISSUE TITLE
View Mode: Layers

### ISSUE THREAD

**Issue by dmfishermd** [Ultimaker/Cura#2080]
I just downloaded Cura 2.6.2. The View Mode: Layers box extends below the Cura window and cannot be visualized.

**Comment by nickthetait** [comment]
Would it be possible to post a screenshot? Also what Operating system are you using?

**Comment by fieldOfView** [comment]
I have fixed this for Cura 2.7 a week or so ago. If the layerview pane does not fit, it is moved upwards.

**Comment by dmfishermd** [comment]
Im using OS 10.10.5
