### ISSUE TITLE
Cannot centre camera view for an Ultimaker 2 model in Cura 2.6.2

### ISSUE THREAD

**Issue by dtims1** [Ultimaker/Cura#2081]
The option to "Center camera  when item is selected", is unavailable in Preferences >General settings.
How do I restore this function? 
[Cura 2.6.2 Camera View Issue.docx](https://github.com/Ultimaker/Cura/files/1130451/Cura.2.6.2.Camera.View.Issue.docx)

**Comment by nallath** [comment]
Duplicate of #1811, #1772 & #1566
