### ISSUE TITLE
Save to Removable Drive

### ISSUE THREAD

**Issue by slurton** [Ultimaker/Cura#2086]
With this new release 2.6.2 I can only save to a removable drive one time each time I start the problem. To save again I have to exit the program and start it again. This is really annoying. I'm on the latest version of mac OS/X

**Comment by PapaG-Design** [comment]
I am also having this same issue, Windows 7 64bit.  Started in 2.6.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/2038.
