### ISSUE TITLE
Feature request: Perimeter processing order - complete wall thickness for each perimeter before going to the next

### ISSUE THREAD

**Issue by bipsendk** [Ultimaker/Cura#2096]
When printing with materials that can ooze a bit during traveling (e.g PETG), it is a challenge to print objects with multiple perimeters, e.g. a square with multiple holes/circles inside.

If 5 perimeter lines need to be printed, the slicicng/printing process will take (depending on the order), first the outer or inner perimeter on all "objects), then the second, then the third and so on.
When material is oozing, if can result in incomplete circles  (in the example above), even though "Retraction extra prime amount" is enabled.

It would be nice, if it was possible to tell the slicer to generate the gcode in such a way, that eeach perimeter should be printed in one "flow" until the wall thickness was reached.
In the example with the square with multiple holes, the square outer perimeter would be printed first, then all perimeter "lines" for the first circle, then all for the second circle, then the third and so on.
This will ensure better bonding between the perimeter lines, and reduce the problem with oozing during travel, as it in this case only will be a part of the inner/outer perimeter for each "object" that potentially not will be printed in full due to delay with filament getting ready at the nozzle.

**Comment by BagelOrb** [comment]
There's currently a community member working on that very issue: https://github.com/Ultimaker/CuraEngine/pull/524

It's very hard to solve, though.
