### ISSUE TITLE
cura-plugin-orientation crashes cura

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#2097]
os ubuntu 16.04
Cura 2.6.1 stable

cura-plugin-orientation crashes cura

**Comment by fieldOfView** [comment]
![s3_proxy](https://user-images.githubusercontent.com/143551/28016175-899e5e12-6573-11e7-8cd6-6ea00a324754.png)?

**Comment by maukcc** [comment]
:) 
When we install cura-plugin-orientation, Cura will not start.
When we remove cura-plugin-orientation, Cura will
[cura.log.txt](https://github.com/Ultimaker/Cura/files/1135306/cura.log.txt)
 start.

**Comment by nallath** [comment]
You didn't use the right plugin version :( You're either using the 2.6 plugin with master or the master plugin with 2.6

**Comment by fieldOfView** [comment]
> You're either using the 2.6 plugin with master or the master plugin with 2.6

If Cura crashes because of that, that is going to be an "interesting" issue when people upgrade to 2.7 in a month or so when they have plugins in their configuration folder.

**Comment by nallath** [comment]
Well, it's actually using the 2.7 version plugin with the 2.6 release. There is an issue with how the old code handles invalid data; It raises an exception and stops loading other plugins.

**Comment by ChrisTerBeke** [comment]
Plugin incompatibility, plus it's a plugin issue, not a Cura issue, closing...

**Comment by fieldOfView** [comment]
The underlying issue that plugins can cause Cura not to load is not fixed though
