### ISSUE TITLE
Text color blends in with platform tiling

### ISSUE THREAD

**Issue by quillford** [Ultimaker/Cura#21]
This could have a white background as the rotate/mirror/scale button labels do upon hovering to be more consistent with the theme.

![cura_and_cura_cura_qt_pot_at_7e841d429e9200ad4241c6a4b1a12deb49b2b4eb_ _ultimaker_cura](https://cloud.githubusercontent.com/assets/8762862/7924631/d6e88334-0871-11e5-8775-bb98c5a9714c.png)

**Comment by awhiemstra** [comment]
Indeed, the colours are a bit tricky. We have plans to add a background to the panel, as that also makes it possible to associate the extra controls more clearly with the active tool.
