### ISSUE TITLE
Non smooth surface texture when printing cylinder

### ISSUE THREAD

**Issue by quebeck5** [Ultimaker/Cura#2100]
Using Cura 2.6.2

The surface texture when printing a cylinder is not smooth at certain heights. 

Attached photo shows the cura print on the right, and the same print on the left with slic3r with same settings.

I believe the gcode paths are different, when I watch the Cura print at a certain height the print head will vibrate, causing the non smooth surface, whereas the Slic3r print will be a smooth continuous circular motion.

Attached zip file has the STL of the cyclinder, and the gcode output from Cura and Slic3r.

[cura cylinder bug.zip](https://github.com/Ultimaker/Cura/files/1137659/cura.cylinder.bug.zip)

![cylinder](https://user-images.githubusercontent.com/30064999/28049947-165799e8-663e-11e7-9fe5-56229cf9a131.jpg)

**Comment by BagelOrb** [comment]
Are you sure you attached the cura cylinder gcode?

The test_cylinder.gcode looks perfectly fine to me. There's no vibrating moves in there.

**Comment by Ghostkeeper** [comment]
Well it says `;Generated with Cura_SteamEngine 2.6.2` at the top of the file...

**Comment by Ghostkeeper** [comment]
The file from Slic3r prints at at `F1380`. The file from Cura prints at `F2160`. I think you just need to reduce the speed in Cura a bit.
