### ISSUE TITLE
can't  open  cura 2.3 （32） with old computer xp system

### ISSUE THREAD

**Issue by cisforcer** [Ultimaker/Cura#2101]
and   cant find any  log files  to show  what happen .when i click the cura.exe   nothing happen ,nothing show

**Comment by fieldOfView** [comment]
I don't think Windows XP is supported, not even by Cura 2.3.

**Comment by cisforcer** [comment]
thank you very much

**Comment by rmcolbert** [comment]
The folder paths used in Cura for logging and user data didn't exist in XP so it may be crashing trying to create the logs. Download the SysInternals application FileMon or ProcMon and run that before launching Cura. You should be able to see where Cura is attempting to write files to get (at the very least) the error log.

**Comment by Ghostkeeper** [comment]
Yes, we require Windows 7 or higher from our Windows users.

Or rather, we require Qt 5.7 which requires Windows 7.

The crash happens before we even try to log anything.
