### ISSUE TITLE
Feature request: Search and Replace, Multiple Gcode Lines in Replace Frame

### ISSUE THREAD

**Issue by PM2189** [Ultimaker/Cura#2103]
When Using the "Search and Replace" Post Processing Script it would be useful if it were possible to type in multiple lines of Gcode in the Replace frame. The main benefit would be the ability to add comments to the end of each line.

**Comment by zerspaner-gerd** [comment]
To the info one can replace with `\n` several lines
Example:
![image](https://user-images.githubusercontent.com/29805503/28096572-21889d6e-66aa-11e7-832c-8ec59fe0bfab.png)

**Comment by Ghostkeeper** [comment]
This just got removed from our planning by Cura's project manager because it was older than 12 weeks.
