### ISSUE TITLE
Clicking to add in windows explorer should add to the currently running CURA application

### ISSUE THREAD

**Issue by FuzzySadist** [Ultimaker/Cura#211]
Currently, double clicking an STL file in windows explorer causes a new CURA application to be started with the one item located on it.

Clicking to add in windows explorer should add to the currently running CURA application, or if none exists, then start a new one

**Comment by awhiemstra** [comment]
While it is a good feature to add, it is actually quite tricky to implement as it would require some form of IPC and process tracking. So do not count on getting this in any time soon.
