### ISSUE TITLE
wont print horizontal surfaces

### ISSUE THREAD

**Issue by tcgfilm** [Ultimaker/Cura#2118]
I cannot get this software to print horizontal surfaces!!!!
![capture](https://user-images.githubusercontent.com/30188414/28234741-06eafc76-68b8-11e7-9b7a-2a167a6082b7.JPG)

**Comment by tcgfilm** [comment]
Any level surface disappears from the print.
There is supposed to be a a solid bottom and top on this arch object.

**Comment by tcgfilm** [comment]
Is there anyone supporting this software other than forums?.

**Comment by smartavionics** [comment]
You can open an issue on the GitHub Cura or CuraEngine repos. But before you do, please provide more information about your model and the settings you are using. Can you make the model available for people to look at? How many top/bottom layers are you using, etc. BTW, that image rather looks like it's using spiralize mode and spiralize is never going to be able to print a horizontal surface.

**Comment by fieldOfView** [comment]
The image also looks like a very old version of Cura, which is no longer supported. Please use Cura 2.6.2

**Comment by tcgfilm** [comment]
I'll try reloading a newer version.

Thanks,  JP.
![cura 1](https://user-images.githubusercontent.com/30188414/28275785-ce7d6efa-6ac9-11e7-8995-62c6a4c6cb60.JPG)
![cura 2](https://user-images.githubusercontent.com/30188414/28275791-d25ed87e-6ac9-11e7-91c0-7457238b81f5.JPG)

**Comment by BagelOrb** [comment]
You have the setting Only Follow Mesh Surface enabled. That setting causes the engine to only print the outlines in the horizontal direction.
If you want to print the topbottom you should disable that setting.

Perhaps you jsut wanted to set the infill peercentage to zero?

**Comment by tcgfilm** [comment]
Thanks Tim.

That’s great to know.

I’ll look into it.

Cheers,   Joe.

**Comment by Ghostkeeper** [comment]
This is a question about legacy Cura. Please direct those questions to https://github.com/daid/LegacyCura/issues
