### ISSUE TITLE
USB communications to MP Maker Select v2.1

### ISSUE THREAD

**Issue by Grayfox98** [Ultimaker/Cura#2119]
When I sent the item to be printed USB it starts out fine but then during the print it starts printing all over the place. It seems to go to home positions both x and y out of nowhere. then it starts printing again in another location. I have a bunch of other slicers installed that have no issue printing the same item. Even the Cura that the printer comes with prints fine. If I save the g code and print it directly it prints fine so I guessing its a communication issue between the driver and Cura.

**Comment by BagelOrb** [comment]
I don't think Ultimaker has any incentive to fix this problem, because it doesn't affect our printers.

Hopefully somebody who is also experiencing this problem can solve it and get his code merged into the main Cura program.

**Comment by Kadah** [comment]
@Grayfox98 Mini v2 + OctoPrint works well with Cura 2.6. OctoPi 1.4 added support for the Pi Zero W, which sells for $10.

**Comment by Ghostkeeper** [comment]
There's really no way in which we can test whether this is a Cura bug or something in the machine itself. Unless you know what g-code command we send is causing the problem?
