### ISSUE TITLE
Lay Flat Does Not Work

### ISSUE THREAD

**Issue by slurton** [Ultimaker/Cura#2120]
Lay flat does not work on small objects.

**Comment by BagelOrb** [comment]
How small?
What kind of shape do they have?

Can you attach the file - or if that's not possible: a screenshot?

**Comment by slurton** [comment]
The part was no more than 2mm in width. I discovered that if I took snap off it worked.

**Comment by BagelOrb** [comment]
Problem reproduces easily with a cube scaled such that either X or Y is 2mm.

Problem goes away if total object is scaled to be larger.

This bug is genuine .

**Comment by Ghostkeeper** [comment]
I also found the problem with a 10x10x2mm cuboid (Z was 2 mm, the other two dimensions were 10mm).

**Comment by Ghostkeeper** [comment]
Our project manager just removed this from our planning though, because the issue is more than 12 weeks old.
