### ISSUE TITLE
Feature request: hide Dual Extrusion tab

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2126]
It would be nice if the Dual Extrusion tab in the side menu was hidden on machines that do not have dual extrusion, Maybe have it like the Travel tab if there is no settings to show hide the whole tab.

**Comment by fieldOfView** [comment]
Agreed. This should actually already be the case, so it is sort of not a feature request but a bug report.

**Comment by LipuFei** [comment]
@fieldOfView I think you have fixed this in https://github.com/Ultimaker/Cura/pull/2108

**Comment by fieldOfView** [comment]
No, (I think) this is about the category header in the sidebar, whereas that PR is about the extruder button in the toolbar.

The problem with the category header is that SettingDefinitionModel:_isAnyDescendantVisible() only checks if there are settings that are marked to be "visible" (in the Settings Visibility page), but not if they are "enabled" for the current stack. In this particular case, ```"Enable Prime Tower"``` is a setting that is made visible by default, but it is disabled (hidden) with ```"enabled": "machine_extruder_count > 1"```. So you get an empty category.

**Comment by ChrisRiddell** [comment]
You are correct this is about the category header.

**Comment by fieldOfView** [comment]
I have made a quick fix. https://github.com/Ultimaker/Uranium/issues/267
