### ISSUE TITLE
Cura does not save to removable drive after first save

### ISSUE THREAD

**Issue by Mrts00** [Ultimaker/Cura#2131]
After saving a file to the removable drive (using the button), ejecting it, then reinsert, make modifications, then try to save a 2nd time, the file does not save.

After reinserting the SD Card, then selecting File>new project, the option for saving to removable drive is not visible. Using the button "save to file", then selecting the removable drive does save the file though. A Cura restart also solves the issue.

The bug appears only in the last version: Cura 2.6.2.

**Comment by fieldOfView** [comment]
Duplicate of #2086, #2038, #2057 and probably others
