### ISSUE TITLE
Connect to several Octoprint with different API key

### ISSUE THREAD

**Issue by UM2EXTENDED** [Ultimaker/Cura#2138]
Cura 2.6.2 OS X
Detected Octoprints
octopi1._octoprint._tcp.local
octopi2._octoprint._tcp.local
octopi3._octoprint._tcp.local
octopi4._octoprint._tcp.local

I have tried to connect to Octoprint and it works but with some problems:

It's not possible to save separate API key for each octoprint.
Also I have the camera in upside down position and can't turn it in Cura.

**Comment by nallath** [comment]
@fieldOfView I can't assign you, but this is your cup 'o tea!

**Comment by fieldOfView** [comment]
The OctoPrintPlugin is maintained here: https://github.com/fieldOfView/OctoPrintPlugin

Handling multiple octoprint instances with different API keys more clearly is on my list for Cura 2.7:
https://github.com/fieldOfView/OctoPrintPlugin/issues/46
Note that it is possible to have a different API key for each octoprint, though it is not very intuitive. The api key is stored/used when you press connect. 

The camera orientation has already been implemented for Cura 2.7:
https://github.com/fieldOfView/OctoPrintPlugin/issues/29

**Comment by ChrisTerBeke** [comment]
Closing here as it's a 3rd party plugin issue.
