### ISSUE TITLE
2.6.2 Layers view options

### ISSUE THREAD

**Issue by PJParish** [Ultimaker/Cura#2144]
Under preferences in 2.3.1 there is an option to show the top layer only.  While this seems a strange place to put that feature it is really useful and seems to be missing in 2.6.2.  I'm not finding that view mode anywhere.

**Comment by fieldOfView** [comment]
You have probably figured out that you can drag both the top and the bottom handles of the layerview slider. If you drag the top and bottom handle close together, you get 1 layer. What you can do now is click the gray area between the top and bottom handle and drag that up/down.

**Comment by PJParish** [comment]
Got it.  Now I see that the grey span is clickable and keeps the layer span.  Cleaver.  Is there a help for these learning these new hidden feature controls?

**Comment by Ghostkeeper** [comment]
There is an online guide for Cura: https://ultimaker.com/en/resources/20410-view-modes

An integrated help/what's this?/tip of the day/first start guide is something we'd like to do one day, but no concrete plans have been made yet as far as I know.
