### ISSUE TITLE
Cost of print display - where did it go?

### ISSUE THREAD

**Issue by PJParish** [Ultimaker/Cura#2146]
When a value for the filament was entered the estimated cost of the print used to be displayed below the estimated time.  Very useful to see this on the front screen.  Can this be brought back?

**Comment by fieldOfView** [comment]
It is there. You need to enter the cost per spool and weight per spool in Preferences/Materials.

**Comment by PJParish** [comment]
Ah,got it.  Missing weight of spool.  Sorry for the bother.  Thank you.
