### ISSUE TITLE
Tower is invalid

### ISSUE THREAD

**Issue by yufanyufan** [Ultimaker/Cura#2154]
The stl file is https://www.thingiverse.com/download:3892329
Support placement setting is everywhere. 

<img width="111" alt="screen shot 2017-07-23 at 1 55 32 pm" src="https://user-images.githubusercontent.com/2504014/28502785-cf48485c-6fae-11e7-96a5-363b44f5a736.png">

**Comment by AlucardF0X** [comment]
I've been getting a ton of these lately.
I use the experimental conical supports, and I also use support expansion. They seem to be the perpetrators of this. 

Can you share your settings? I bet you have conical support also on!

**Comment by BagelOrb** [comment]
I think this is caused just by the Support Towers, which are on by default.

The problem is that they get generated even for support which is too small to even be printed.

**Comment by Ghostkeeper** [comment]
Our project manager removed this issue from our planning because it's older than 12 weeks.

**Comment by ianpaschal** [comment]
This no longer reproduces in 3.3.1.

**Comment by Ghostkeeper** [comment]
No, it still reproduces. This is in current master:
![screenshot from 2018-06-07 12-50-43](https://user-images.githubusercontent.com/2448634/41095356-7a4975d0-6a51-11e8-9985-48d92986e42d.png)
[The project file (rename to .3mf)](https://github.com/Ultimaker/Cura/files/2080091/CheeseShaver.curaproject.zip)
