### ISSUE TITLE
Default material profile missing

### ISSUE THREAD

**Issue by Thijxx** [Ultimaker/Cura#2157]
Cura 2.6.1 in Arch Linux, the default PLA profile is missing and therefore I cannot make ANY materials. I searched high and low all over the web to download the default profile but I cannot find it anywhere. Could someone please point me to the file?

Also, my material folder is empty..

`2017-07-24 17:19:01,669 - DEBUG - cura.Settings.ContainerManager.createMaterial [752]: Unable to create a new material by cloning Generic PLA, because it cannot be found for the material diameter for this machine.`

**Comment by fieldOfView** [comment]
Are you running Cura from source?

The materials are in this repo: https://github.com/ultimaker/fdm_materials

**Comment by Thijxx** [comment]
Yes, and thanks for the link!

**Comment by lf-** [comment]
As for the "running from source", not really, the package build script grabs a git checkout of the given tag. Seems that it misses that bit.

I submitted a bugreport and a patch to the package: https://bugs.archlinux.org/task/54948

**Comment by ctag** [comment]
I agree with lf-'s comment on the bug report that the lack of materials makes for a frustrating introduction to Cura.

In the meantime [cura-fdm-materials-git](https://aur.archlinux.org/packages/cura-fdm-materials-git/) from the AUR suffices to bring default materials to the official Cura package... As far as I know; this is my first foray into Cura land.
