### ISSUE TITLE
Hole and External wall offset

### ISSUE THREAD

**Issue by AlucardF0X** [Ultimaker/Cura#2158]
So, since the dawn of 3D Printing, the feature "Model Horizontal Offset" a.k.a. "Size compensation" has been a very valuable feature. 

Except I've ran into a few 3D Models that don't wanna slice correctly.
After printing, the external dimensions of the model are consistently 0.5mm smaller than designated.
The hole dimensions are spot-on. 

If I use any of the settings, it'll make the hole too big, or too small. Oof!

There really needs to be a setting that allows configuration of internal holes and external walls, rather than moving both. So I can independently resize holes (internal walls) and external walls.

A work-around is to size-compensate with 0.5mm, thus make the holes 0.5mm smaller... Then drill out the holes, but that's a pain. 

I don't think there's a slicer that currently supports this at all. So I'm a sitting duck with a few projects I'm trying to complete, just because cura decided to make external walls too small, somehow.

It isn't a "plastic shrinks" problem because I'm pretty sure across 2mm, 0.5mm is NOT plastic shrinkage, that'd be a whopping 25% shrinkage, and that's awesomely impossible. 

![bad diameters](https://user-images.githubusercontent.com/10225169/28544885-ccbf5620-70bc-11e7-9046-9d9970d39dfd.JPG)

PS: Those little pegs are also, 0.5mm smaller than they should be. 
If I try to thicken them by horizontal offset, I'd need to apply 0.25mm horizontal offset. 
That would *thicken* the model by volume, making holes smaller by 0.25mm, and pegs thicker by 0.25mm, but that'd make all my holes that much smaller... Once again not a good fit.

So I'd need to compensate horizontally by some half-value to make the two parts fit? But be off-spec? 

If my peg is 2.5mm and the hole is 3mm, I'd transfer 0.25mm from bigger to smaller, so that'd result in 
2.75mm peg and 2.75mm hole, a perfect fit, but then they'd be off-spec as they're meant to be 3mm...

The wall-inset and horizontal-offset settings only move units from one to the other. 
There isn't a setting that would let me increase the peg, without decreasing the hole. 
There isn't a setting that would let me increase the hole, without decreasing the peg. 

I essentially need the hole to STAY, and the peg to THICKEN. 
Or, if I balance them first with horizontal offset:
I'd need to THICKEN (make it bigger) the hole (wall-wise), and THICKEN the peg... Which there isn't currently a setting for. 

Asking me to fix this in my model is like asking me to design a frankenstein 3d model just to make it printable in a cruddy software that reads wingdings only. 

Edit 2: 
One would assume I'm over-extruding... That would have the same effect as increasing horizontal offset, it wouldn't disbalance the two. I combed over the settings, nothing really... can disbalance the two settings like has happened in this model... I restarted the software, resliced, re-exported the model.. Sumthin' weird is going on with the slicing process. It clearly says the part is 45.5mm wide, but the physical part is 45mm... The internal hole is 15mm as the model is... Aaaaaaa why is this happeniiiing

**Comment by AlucardF0X** [comment]
It isn't shrink/overcompensation either: I guess can explain this if I'm printing it with too much compensation (-0.09mm? that's barely any), making the model thin... But then it shrinks due to cooling, and it fits the ID, at the sacrifice of the OD? 

But that's like 0.5mm for 45.5mm... that's like 0.01% shrink... But then why are the holes PERFECT as-designed 3mm? And why is the diameter CONSISTENTLY PERFECTLY shrunk 0.5mm everywhere, in diameters and lengths? 2.5mm pegs! 45mm walls, when they should be 45.5mm.. 

It isn't a weird "delete 0.5mm blyat" because my 3mm pegs got shrunk by 0.5mm to 2.5mm...

Argh I need help this is beyond me

**Comment by BagelOrb** [comment]
You shouldn't think in terms of outer perimeter and holes, but in terms of concave (inward) and convex (outward) corners.

I think most modeling software makes a round hole into a regular polygon which has its vertices on the circle, which means that the edges of the polygon take short-cuts off of the model.
Perhaps Cura is even doing that when it reduces the vertex count of each layer. It has te do this because most firmware cannot handle gcode with too many verts close to each other.

But that isn't the only thing at play here. I think there are also mechanical interactions between consecutively printed line segments which cause the filament to take shortcuts when being printed.

I think the easiest way to cover several effects at once is to compensate corners outward wrt the corner.
I know there already is an extensive thread about different algorithms for this and a pull request of somebody who implemented one of the algorithms in a post-processor, but I cannot find those ATM.

**Comment by BagelOrb** [comment]
Ah here it is:
https://github.com/nallath/PostProcessingPlugin/pull/47
https://github.com/Ultimaker/CuraEngine/pull/94

**Comment by BagelOrb** [comment]
I think this is the most important bug for dimensional accuracy which we would have to compensate for.

**Comment by AlucardF0X** [comment]
So I found a huge problem with slicing software. 

... Wouldn't it be easiest to split the "x/y horizontal offset" option into 
"x/y horizontal CONCAVE offset" and "x/y horizontal CONVEX offset" that shrink the external sides of the model and the internal sizes of the model?

Then it'd be a simple matter of trial and error to get it right. Then eventually someone will have a formula for it...

The software already has the inherent logic of identifying which direction to scale vertices towards - away from the model's VOLUME, rather than its origin (standard scale). Surely it isn't difficult to split it into two settings?

I can 99.9% fix this feature in the software, if you guys give me a guarantee that it'll get implemented, because Im too lazy to fork/pullreq and then cry in a corner when you never accept it. I'll only post the changes here in this issue report and expect you guys to implement it.

**Comment by nallath** [comment]
Most of the pull requests get accepted. The few that don't get accepted is usually because we have some issues with codestyle / solution (we have a 100% peer review & test system) and the original author doesn't resolve those issues.

**Comment by BagelOrb** [comment]
It wouldn't make sense to compensate the concave corner shortcuts with a
static amount of offset.
Suppose we have an almost straight wall with a few very shallow corners.
You solution idea would cause the wall to become jagged because it would be
switching between the two offsets every so often.

If you ask me then an algorithm to solve this should:
- cause less divergence from the outline for more straight corners
- don't affect long straight walls in the middle when the end is connected
to a 90° corner

Op 26 jul. 2017 09:38 schreef "Jaime van Kessel" <notifications@github.com>:

**Comment by AlucardF0X** [comment]
I already told you my IDs are consistently fine, my ODs are consistently 0.5mm smaller. 

If you're so afraid of jagged walls, make a setting for the detail holes are sliced down to. My printer can handle the higher amount of gcodes. 

It just feels like you guys are proactively making sure the software doesn't get updated, talking all theory without any attempt on your part to do anything. I've seen your github, you reject basically every change or let it get auto-deleted due to lack of attention, the same way you manage this issues tracker. 

I tried to contribute a suggestion several times, you guys made excuses and delete my suggestion. You do the same "appease customer with words but do no work" all over the damn forum. This is why I didn't buy a Ultimaker machine but instead a china clone. I've heared all over that Ultimaker support is the epitome of shit and this here just proves it. 

I tried to contribute, I tried to offer my skills, but you guys nallath and bagelorb are actively getting in the way of the development. I don't give a shit if you ban me or whatever. Im no longer interested in associating with cura or ultimaker, I'm making my own slicer that doesn't suck balls and won't need any updating. 

I can share with you the design since you guys are too lazy to do anything, maybe you'd patent troll it? A progressive/procedural image-based slicer that generates bitmap images, analyzes before/after layers to generate a smart toolpath on an interative bitmap process, where it manually draws with a "paint brush" head, where it'll compensate for any and all extruded plastic, no shitty "path trace" algorithms. This means that people can just input custom fill formulas similar to Photoshop's shader codes for patterns, meaning you dont need to update the software, just share slicing profiles. 

This slicer could then be used for laser cutting, or ram-EDMing. Since it would be GPU accelerated, it wouldn't suck balls like all y'all shitty slicers that can't fucking draw 100 lines on screen without crawling to a halt. And it won't be written in shitty PEETHOON FOR LEENUUXX CROSS PLATFORM INSTALL GENTOO SHITLORD languages. Have fun, I certainly didn't. Enjoy shit-talking me and climbing on your high throne.

**Comment by fieldOfView** [comment]
Are you alright? How was your day?

**Comment by nallath** [comment]
You know that once you share a design on teh interwebs we can't actually patent it. Noone can. 

Good luck making the slicer.

**Comment by smartavionics** [comment]
Hi, I'm not an Ultimaker person and I don't use an Ultimaker printer so I can say what I like. If you work up a  PR that does what you want and it conforms to the Cura devs style guidelines and is likely to be useful to other people then it will most likely be accepted into Cura. If you produce something that is coded like shit, looks like shit and does something that only you have a use for, it probably won't get included. Of course, that doesn't stop you using a private version of Cura that includes your ideas. That's the beauty of open source, right?

**Comment by BagelOrb** [comment]
Let me reiterate:
I think this is the most important bug for dimensional accuracy which we would have to compensate for.

**Comment by jackha** [comment]
Closed because of inactivity.

**Comment by TNTINC** [comment]
It has been almost three years now.

Will this ever be fixed?

**Comment by smartavionics** [comment]
Hi folks, I've added a Hole Horizontal Expansion setting to my Cura and here's an example of its use (and limitations).

![Screenshot_2020-01-17_17-38-45](https://user-images.githubusercontent.com/585618/72633430-5ab1f380-3950-11ea-8dfe-68b4817a1d62.png)

![Screenshot_2020-01-17_17-38-20](https://user-images.githubusercontent.com/585618/72633431-5ab1f380-3950-11ea-8fb7-4d04c8e02e6d.png)

You can see that the holes that come through the sloping surface are not expanded. That's because they are not holes as they encroach on the part's outline.

Anyway, if you're interested in testing this I will be building a release over the weekend.

**Comment by smartavionics** [comment]
My latest (20200118) Cura build (at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0) now has this setting. Please read the README.md there for more information on my builds.

**Comment by mahtDFR** [comment]
There is a workaround by using a post processing script. If you enable 'post stretch script' you can modify the movements of the extruder to compensate for the process limitations that can make holes to small when printing.

**Comment by nallath** [comment]
> Extensions > Post Processing > Modify G-Code > Add a script > Post stretch script

True, but this is extremely slow. An actual solution in the engine is to be preferred.

**Comment by louleluk** [comment]
Hi guys i have test horizontal expansion with cura but for thin wall the slicer give me a lot of infill mistake!! But if anyone have tested out the streching post treatment, it will affect only the small holes or the design itself?

**Comment by smartavionics** [comment]
Hello @louleluk , can you provide an example project or at least a screen shot to show the problem? Thanks.

**Comment by louleluk** [comment]
finally i have tested my original design and i have enable the horiz
ontal expansion but i also have fix my problem with line width 0.3mm value
 for me the hotend have a diameter 0.4mm 
![Capture d’écran (4)](https://user-images.githubusercontent.com/60312058/73175677-00aced00-410b-11ea-957e-97a259057598.png)here above the problem is the infill between walls.
And now below with horizontal expansion and 0.3 width line.
![Capture d’écran (5)](https://user-images.githubusercontent.com/60312058/73175828-571a2b80-410b-11ea-9131-d9c76eca2208.png)
dimensions are correct

**Comment by smartavionics** [comment]
Thanks for the info. Yes, Cura really doesn't cope well with walls that are an odd number of line widths width. Glad you have a solution.

**Comment by evtrados** [comment]
This issue can now be compensated using the 'Hole Horizontal Expansion' setting, where the user can manually enlarge or shorten the holes. This setting will be available in the next release.

**Comment by Paragon1970** [comment]
> This issue can now be compensated using the 'Hole Horizontal Expansion' setting, where the user can manually enlarge or shorten the holes. This setting will be available in the next release.

Great news! 
Do you have a link to the source branch that has this feature, please?

**Comment by smartavionics** [comment]
See https://github.com/Ultimaker/Cura/pull/7010 and https://github.com/Ultimaker/CuraEngine/pull/1186.

**Comment by Conti93** [comment]
Hole Horizontal Expansion doesn't work when the layer hasn't got an internal circle, e.g. when you have a hole on a side:
![image](https://user-images.githubusercontent.com/58734181/81482276-1ff10580-9236-11ea-9dd3-5ad64c882d63.png)
Ideas to make this fit without modifying the part?

**Comment by smartavionics** [comment]
That's because on those layers, it's not a hole but part of the outline.

**Comment by smartavionics** [comment]
As for a workaround, what I would do is create a cube model that is simply a wall width wide and use it to block off the horizontal tubes so that the inner region is no longer part of the model's outline. Once the part is printed, just drill through the thin walls.

**Comment by smartavionics** [comment]
Not really a cube but a thin plate that is large enough to block the horizontal holes, just load the mesh and move it into position.
