### ISSUE TITLE
15.06.03 Raft Not Displaying in Layers View 

### ISSUE THREAD

**Issue by Fuzionist1** [Ultimaker/Cura#216]
The raft is not displaying in Layers view. Instead, the first layer shown is as if there was no raft at all. I have tried complex and completely basic models. 
![capture](https://cloud.githubusercontent.com/assets/13238025/9066902/3254a258-3aa8-11e5-9141-60003a918759.PNG)

**Comment by Xisle** [comment]
It looks like the raft is just not being rendered or included in the layer count. The model gets raised up when Raft is present though.

**Comment by BagelOrb** [comment]
Fixed in next release
