### ISSUE TITLE
Original + Not working at all

### ISSUE THREAD

**Issue by UnicornCustomPerfomance** [Ultimaker/Cura#2163]
A little background; I bought and built this a little over a year ago and due to life events I haven't been able to actually print anything yet until now. I went to go start it up and the screen comes up fine. Then once it tries to do anything (heat the bed/nozzle, move any axis) the screen goes blank but stays lit up and then restarts itself. Then when I went to do a bed level test once the bed starts moving instantly it does what is listed above and will no longer connect to Cura. I have to unplug the printer and replug it in for Cura to recognize it again.

**Comment by fieldOfView** [comment]
Sounds like you are having a hardware issue, where the microcontroller is not getting enough power. The funny technical term is a "brown-out".

There is not much that can be done about this from Cura. I think you should be able to get more help through your reseller or http://ultimaker.com/en/community, eg https://ultimaker.com/en/community/50455-ultimaker-original-shut-off-during-preheat
