### ISSUE TITLE
If printer is not on when Cura is started cura will not connect

### ISSUE THREAD

**Issue by astecme** [Ultimaker/Cura#2167]
If a printer is not turned on when Cura is started Cura will not connect. The only way to connect afterwards is to shut Cura down and restrt it.

**Comment by Ghostkeeper** [comment]
I assume you're talking about a USB cable, considering your previous bug reports.

I can't reproduce this problem. I can start Cura, then connect a printer via a USB cable, and Cura will detect the new device and connect to it. Perhaps Cura tries to connect to some other USB port on your computer? Cura can only handle one USB connection at a time, after all...

**Comment by astecme** [comment]
NO, its as I said.

**Comment by Ghostkeeper** [comment]
I believe you! But for us to fix the problem we need to reproduce the problem on our end as well. How can we reproduce it? What operating system are you using, perhaps? Or maybe the printer model you're connecting to?
