### ISSUE TITLE
There is no manual connect/reconnect for USB printer

### ISSUE THREAD

**Issue by astecme** [Ultimaker/Cura#2169]
There is no manual connect/reconnect ability so if the printer is off when Cura is started you must restart Cura rather than requesting a re-connect.

**Comment by Ghostkeeper** [comment]
This sort of ties in with being able to disconnect. If you can't disconnect and it always connects upon inserting a USB cable, you won't be able to reconnect either. See #1049.

**Comment by jackha** [comment]
Closed because of inactivity
