### ISSUE TITLE
Printing sequence (one at a time) in Cura 2.6.2

### ISSUE THREAD

**Issue by Nickduino** [Ultimaker/Cura#2170]
When you're printing with a different temperature for the first layer than for the others **and** printing _one at a time_, the nozzle stops on top of the first print while the printer is  heating up before starting the second print.

This results in a messy top layer on the first print. The slicer should, at the very least, do a Z hop of 10 mm.

**Comment by fieldOfView** [comment]
Could you create a more descriptive issue title?

**Comment by Nickduino** [comment]
I'm sorry, I wrote the version of Cura while waiting to retrieve the name of the feature and then I forgot to adjust the title.

**Comment by guiseco** [comment]
Same problem here.

**Comment by Ghostkeeper** [comment]
Duplicates https://github.com/Ultimaker/Cura/issues/1737
