### ISSUE TITLE
Flow (%) has no effect in version 15.04.06 (Mac Version)

### ISSUE THREAD

**Issue by andypugh** [Ultimaker/Cura#2171]
I get identical G-code with flow compensation at 100% and 5%. 
I tried the same experiment on a Windows PC, also with 15.04.xx and saw the expected change in E-numbers.

**Comment by fieldOfView** [comment]
That version is not supported here. Please see https://github.com/daid/cura

**Comment by andypugh** [comment]
OK, thanks.
