### ISSUE TITLE
Restart Cura for every STL File

### ISSUE THREAD

**Issue by DanielQuintana2** [Ultimaker/Cura#2173]
When using Cura for multiple 3D prints I have to restart it to upload to an SD card. For example, I open cura, slice an STL, upload to SD. Then if I want to print another in the same session it wont let me upload to an SD. I found that closing it then reopening it works but it takes a lot of time.

**Comment by patricknn** [comment]
This is also happening to me since the update to 2.6.2
Every time that you upload to SD the Cura freezes in a way that you can't do it again.

**Comment by Vandrasc** [comment]
It should be fixed in the next release.

**Comment by MFHFozzy** [comment]
And when *is* the next release?

**Comment by Ghostkeeper** [comment]
Next week, most likely.

**Comment by Ghostkeeper** [comment]
I can't verify that since the bug didn't occur in Linux. Could you try, @ChrisTerBeke?

**Comment by ChrisTerBeke** [comment]
I do not experience this issue anymore when using the Save to file (or SD) export multiple times in a row with different models without restarting Cura (on Windows 10, 3.0 branch). I also didn't get this on 2.7 though (was on Mac back then).
