### ISSUE TITLE
Duplicated material cannot be removed in Cura 2.6.1

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/Cura#2174]
When I duplicate a material in Cura 2.6.1 I cannot remove it again; the remove button stays disabled (Win-64). I tried:
- unlinking
- restart Cura
But both didn't work.
It seems a material duplicated in an older version can be removed in 2.6.1

**Comment by Ghostkeeper** [comment]
Make sure that the material is not activated in any printer. If it is active, the button is disabled on purpose.

**Comment by Ghostkeeper** [comment]
Apart from the exception mentioned above, I wasn't able to reproduce this bug.

**Comment by Dim3nsioneer** [comment]
It seems this was the problem. The material was activated. Maybe it's not a bad thing to have this specialty documented here.
