### ISSUE TITLE
Purpose of Filament Diameter in Machine Settings?

### ISSUE THREAD

**Issue by PJParish** [Ultimaker/Cura#2179]
What is the purpose of the Filament diameter display in the Machine Settings window?  It displays the filament diameter of the Profile selected but does not allow you to change it from the Machine settings view.   I would expect it to be modifiable from either side or simply show the default filament size of the machine.

**Comment by fieldOfView** [comment]
It is broken in 2.6, but has been fixed for 2.7.

**Comment by Ghostkeeper** [comment]
Indeed, it is now modifiable from either side.
