### ISSUE TITLE
Better overhang quality

### ISSUE THREAD

**Issue by zerspaner-gerd** [Ultimaker/Cura#2181]
I get better overhang quality by printing the "Top / Botton Pattern" with Concentric?

Since the inner "Top / Botton Pattern" layers are printed in Concentric, maybe you can add a setting that only prints the "Concentric" overhangs

![concentic](https://user-images.githubusercontent.com/29805503/28757449-c525c018-7583-11e7-9acc-0fd3739c6f2b.jpg)
![lines](https://user-images.githubusercontent.com/29805503/28757450-c9429590-7583-11e7-93e7-59f316f4cf95.jpg)

But only on the side of the overhang, at bridges, it has a negative effect.

Here is a picture of my test prints, and this confirms my impression
![test print](https://user-images.githubusercontent.com/29805503/28757484-688f912a-7584-11e7-8268-239212d911e5.jpg)

Test file:
https://www.youmagine.com/designs/make-2015-3d-printer-shoot-out-test-geometries - part Overhang Test

**Comment by Ghostkeeper** [comment]
Concentric bottom (tee hee) produces better bridging, it's well known.

The problem with the concentric pattern on the top/bottom is that it produces a fairly extreme blob in the middle where the concentric lines centre around. It also has some bad worst-case properties for how the pattern lies on top of the infill.

We'll have bridging areas eventually. Perhaps then we'll be able to modify the line directions with more fidelity like this.

**Comment by zerspaner-gerd** [comment]
> The problem with the concentric pattern on the top/bottom is that it produces a fairly extreme blob in the middle where the concentric lines centre around. It also has some bad worst-case properties for how the pattern lies on top of the infill.

The problem I have also observed, so it would be nice if there was a setting only for the overhang areas.


The Extra Skin Wall Count feature does something similar.

**Comment by Ghostkeeper** [comment]
We expect to improve this via better bridging detection rather than via skin patterns on overhang parts. Discussion is ongoing.
