### ISSUE TITLE
get_filename_component unknown component CACHE error in building Cura-2.6.0

### ISSUE THREAD

**Issue by MacroHu** [Ultimaker/Cura#2187]
Hi guys, I got some problems in building **Cura-2.6.0**, things many of  you may had ever met.

I am trying to build **cura-2.6.0 to .deb package** in **Ubuntu16.04-desktop-amd64**, these are my steps.

Step1: Use **cura-build-environment-2.6.0** to install the dependencies of cura-2.6.0.

Step2: Use **cura-build-2.6.0** to build **cura-2.6.0.**

I have fixed up the build errors of **cura-build-environment-2.6.0** and finished step1.

[  6%] Built target Python
[ 12%] Built target PySerial
[ 17%] Built target PythonNetifaces
[ 23%] Built target Qt
[ 28%] Built target Sip
[ 33%] Built target PyQt
[ 38%] Built target AppImageKit
[ 43%] Built target OpenBLAS
[ 48%] Built target NumPy
[ 54%] Built target SciPy
[ 60%] Built target python-utils
[ 66%] Built target NumpySTL
[ 72%] Built target Protobuf
[ 78%] Built target Arcus
[ 84%] Built target PythonSix
[ 89%] Built target PythonZeroconf
[ 10%] Built target pugixml
[ 94%] Built target Savitar
[100%] Built target cx_Freeze
[100%] Built target projects

My cmake command of cura-build-environment-2.6.0：

	cmake .. -DCMAKE_INSTALL_PREFIX=/0-A/Install_Dir_Cura-Build-Environment-2.6.0 -DCMAKE_BUILD_TYPE=Release
----------
Quote from ~/cura-build-environment-2.6.0/README.md:
<<<<<<<<<<<<<<<<<<
The end result of this project should be a complete build environment
installed to CMAKE_INSTALL_PREFIX. **This environment can be used in
combination with the [cura-build] repository to produce Cura executables for
all three supported platforms.**
>>>>>>>>>>>>>>>>>>

So I try the same CMAKE_INSTALL_PREFIX to build cura-build-2.6.0 but failed.
<<<<<<<<<<<<<<
root@yue-virtual-machine:/0-A/Package/cura-build-2.6.0/build# **cmake .. -DCMAKE_INSTALL_PREFIX=/0-A/Install_Dir_Cura-Build-Environment-2.6.0**
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
**CMake Error at CMakeLists.txt:23 (get_filename_component):
   get_filename_component unknown component CACHE**

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/libprotobuf.a (Required is at least version "3.0.0") 
-- Found PythonInterp: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/bin/python3.5 (found suitable version "3.5.2", minimum required is "3.5.0") 
-- Found PyQt: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/PyQt5 (found suitable version "5.8.2", minimum required is "5.6") 
-- Found SciPy: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/scipy (found suitable version "0.17.1", minimum required is "0.17") 
-- Found cx_Freeze: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/lib/python3.5/site-packages/cx_Freeze (found suitable version "5.0", minimum required is "5.0") 
-- Found AppImageKit: /0-A/Install_Dir_Cura-Build-Environment-2.6.0/bin/AppImageAssistant  
-- Found GPG: /usr/bin/gpg  
-- Found SHA1Sum: /usr/bin/sha1sum  
-- Configuring incomplete, errors occurred!
See also "/0-A/Package/cura-build-2.6.0/build/CMakeFiles/CMakeOutput.log".
See also "/0-A/Package/cura-build-2.6.0/build/CMakeFiles/CMakeError.log".
root@yue-virtual-machine:/0-A/Package/cura-build-2.6.0/build# 
>>>>>>>>>>>>>>
      **get_filename_component unknown component CACHE**

 I can't fix this CACHE error in CmakeList.txt  ↑

target info in CmakeList.txt
<<<<<<
//# This should care that our CMAKE_PREFIX_PATH is absolute at the end...
get_filename_component(CMAKE_PREFIX_PATH
                       ${CMAKE_PREFIX_PATH}
                       ABSOLUTE
                       **CACHE** FORCE)
>>>>>>
Do somebody know how to fix it? And most importantly，Is that my method to combine cura-build-environment-2.6.0 with cura-build-2.6.0 wrong?  
How to combine cura-build-environment-2.6.0 with cura-build-2.6.0 ??

**Comment by Ghostkeeper** [comment]
Did you find a solution for this? Perhaps you're willing to share it for posterity?
