### ISSUE TITLE
Cura 2.7 beta - center model resets rotation

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2193]
After I have rotated a model on the build plate, if I right-click it and select "center selected model", it centers the model but resets my custom rotation :/
macOS Sierra 10.12.6

**Comment by nickthetait** [comment]
I just confirmed that this feature works correctly on Ubuntu 17.04

**Comment by Ghostkeeper** [comment]
This bug also doesn't reproduce for me. It stays in its modified rotation.
