### ISSUE TITLE
Cura 2.7 beta - file name does not include printer prefix

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2194]
Even though the setting "Add machine prefix to file name" is activated, Cura does not add it.
macOS Sierra 10.12.6

![screen shot 2017-08-02 at 12 02 31](https://user-images.githubusercontent.com/1069286/28868780-c4495594-777a-11e7-8750-4ee0670bfe35.png)

**Comment by fieldOfView** [comment]
It uses a different name altogether (shell vs insert). Not sure what happened here. Steps to reproduce?

**Comment by nickthetait** [comment]
Cannot reproduce this using Ubuntu 17.04. Machine prefix is correctly added.

**Comment by Ghostkeeper** [comment]
The prefix is correctly added for me too. When I change the name after it has loaded and then save, the new (changed) name is correctly saved for me.

**Comment by ianpaschal** [comment]
6+ months old and not possible to reproduce. Also pretty sure we've made fixes/improvements in the last few weeks that would have corrected this if it was still going on.
