### ISSUE TITLE
Cura 2.7 beta - wrong file name when adding more models to the buildplate

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2196]
The first model added to the build plate sets the name for the generated .gcode file. But when I add other model files and then save the .gcode file, the file name of the last model is used even though Cura still shows the first model file name bottom right.
This is probably related to #2194 

macOS Sierra 10.12.6

**Comment by Vandrasc** [comment]
Yes, a known issue. Thank you!

**Comment by ianpaschal** [comment]
Fixed in version 3.0
