### ISSUE TITLE
CURA 2.7 [idea]

### ISSUE THREAD

**Issue by darkdvd** [Ultimaker/Cura#2197]
Some shadow between menus and the background in the "dark" theme will be great !

**Comment by darkdvd** [comment]
![cura_dark_shadow](https://user-images.githubusercontent.com/16816760/28877641-44e29d24-779d-11e7-8faf-88d12e53aa6e.jpg)

**Comment by Ghostkeeper** [comment]
Indeed, and it would have to be themeable.

**Comment by Ghostkeeper** [comment]
Our project manager just removed this from our planning because it's older than 12 weeks.

**Comment by ChrisTerBeke** [comment]
There's a new design since 3.0 in which the dark theme menu's are fixed as well.

**Comment by Ghostkeeper** [comment]
What do you mean by "fixed"?

**Comment by ChrisTerBeke** [comment]
Personally I'm not a fan of drop shadows. The issue is that there's not enough contrast between sidebar/topbar/toolbar and 3D viewer background. Maybe toning down the background color a bit will help for the contract without needing drop shadows. We don't use drop shadows anywhere else in the design of Cura.

**Comment by darkdvd** [comment]
Come on, man! It's time to make CURA sexy!

**Comment by ianpaschal** [comment]
As part of our new ticket handling strategy, we voted as a team on the likelihood of fixing this issue. Unfortunately, we’ve decided that we will not take time to fix it, and are marking it as `Status: Won’t Fix/Do` and closing the issue.

**Comment by darkdvd** [comment]
:-(

**Comment by ianpaschal** [comment]
Cura 4.0 is on the radar and will likely involve lots of UI reworks (including, I hope, a better theming system). In light of that we're not going to invest much time in modifying the UI unless it's to accommodate bug fixes or new features until then. Sorry!

**Comment by ChrisTerBeke** [comment]
Please use QtQuick2 with reusable components :)
