### ISSUE TITLE
[2.7.0] outdated changelog

### ISSUE THREAD

**Issue by nickthetait** [Ultimaker/Cura#2199]
Application Version: 2.7.0
Platform: Ubuntu 17.04

Steps to Reproduce:
First time launch of Cura

Maybe this is expected, but the latest info shown by changelog is from 2.6.1

![changelog](https://user-images.githubusercontent.com/11818614/28894502-43389696-7792-11e7-8183-2bcbf664b97a.png)

**Comment by Vandrasc** [comment]
Expected :) Thank you! It will be updated in 2.7 release.
