### ISSUE TITLE
Cura does not create ultiflavor gcode

### ISSUE THREAD

**Issue by Bas-van-Deursen** [Ultimaker/Cura#220]
Application Version: 15.06.03
Platform:Windows 7 64-bit

Display Driver: NVIDEA Quattro

Steps to Reproduce:

Selected printer: UM2

slicing a model with advanced settings and save to sd card. The generated gcode does not have the right starting lines for UM2 gcode:

;Generated with Cura_SteamEngine DEV
;LAYER:0
M107
G0 F9000 X56.243 Y76.312 Z0.299
G0 X58.764 Y75.628
;TYPE:SKIRT

**Comment by Bas-van-Deursen** [comment]
Tried to replicate the problem, but I can't get it to fail again... Now it does work.

**Comment by awhiemstra** [comment]
Seems like prepending the start GCode failed. I wonder how that can happen. If it happens again, can you save and post the engine log?

**Comment by Bas-van-Deursen** [comment]
will do.

-Bas

On Wed, Aug 5, 2015 at 4:32 PM, awhiemstra <notifications@github.com> wrote:

> Seems like prepending the start GCode failed. I wonder how that can
> happen. If it happens again, can you save and post the engine log?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ultimaker/Cura/issues/220#issuecomment-128017162>.
>



-- 

*Bas van Deursen *Design Engineer
Ultimaker B.V.

*Watermolenweg 2, 4191 PN, Geldermalsen*
*T *+31 (0)345 712017 | *E *b.vandeursen@ultimaker.com | *W *
www.ultimaker.com

-- 


IMAGINE IT >> MAKE IT

Meet us online at Twitter <http://twitter.com/ultimaker>, Facebook 
<http://facebook.com/ultimaker>, Google+ <http://google.com/+Ultimaker>

www.ultimaker.com
