### ISSUE TITLE
2.7 Beta cannot switch to dark theme (crash) (well, it does switch after a while)

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#2202]
Mac OS Sierra
Cura Beta 2.7

![image](https://user-images.githubusercontent.com/16858474/28938804-702bd1f6-788f-11e7-8b9e-bc49a122ae31.png)

### Reproduce problem: 

1. go to settings and switch to dark theme
1. close the settings
1. close cura
1. cura crashes on close
1. start cura
1. theme is still the default white one

### Edit 1 somehow it worked

after doing this 5 times, cura DID switch the theme to dark. 
still, it never closed without 'cura has crashed' notification, and 
it did take 5 tries...

### edit 2 now I can't get out of the dark theme

same problem...

**Comment by biocode3D** [comment]
Same thing on Linux.
Dark theme won't take If I "quit" from the menu. I also get a segfault when it exits.

But it works if I kill the window! Theme change takes, no segfault.

**Comment by fieldOfView** [comment]
Note that this is not strictly limited to setting the dark theme, but it is true for any preference. As a workaround, either wait ~10 seconds before closing Cura (so autosave kicks in) or close Cura by closing the window instead of using Quit in the menu

**Comment by filipgoc** [comment]
@fieldOfView good workaround with the 10s. 

however, for me Cura crashes even when closing the window. (i.e., not using the quit function.)

**Comment by Ghostkeeper** [comment]
The crash when closing the window via the X button on MacOS has been fixed now.
