### ISSUE TITLE
Cura 2.7 Beta crashes at slicing

### ISSUE THREAD

**Issue by zerspaner-gerd** [Ultimaker/Cura#2211]
Extra Skin Wall Count feature does not work, crashes CuraEngine.exe

[cura.txt](https://github.com/Ultimaker/Cura/files/1201737/cura.txt)

**Comment by Vandrasc** [comment]
Confirmed, thank you for reporting it. Dev's see CURA-4122.

**Comment by Ghostkeeper** [comment]
Fixed for 2.7: https://github.com/Ultimaker/CuraEngine/commit/ee5f62c4b18985e624e224113fde51df3cc8f688
