### ISSUE TITLE
Cura won't slice anything. Tried every possible solution to my knowledge

### ISSUE THREAD

**Issue by RedDropOriginal** [Ultimaker/Cura#2219]
Recently I fired up Cura 2.6.1, never had any issues before today. but now it will 'slice' the model but the estimates of time and weight are just zero. The gcode generated is just start and end-script. 
It happened after I wanted to try the spiralise mode, it didn't really work out so I unchecked it and now I have this going on.
I tried:
→ Different model
→ Different profile/material
→ Restarting Cura/PC
→ Checking and unchecking every setting

![cura 1](https://user-images.githubusercontent.com/30777766/29007104-af2c6338-7afc-11e7-92fa-1c40cc9aaea6.PNG)

**Comment by RedDropOriginal** [comment]
Here are all the settings I use: 
![cura 2](https://user-images.githubusercontent.com/30777766/29007170-d78bc1d8-7afd-11e7-9a36-2cfeca056fe4.PNG)
![cura 3](https://user-images.githubusercontent.com/30777766/29007171-d78d8108-7afd-11e7-934e-67a47a7f8549.PNG)
![cura 4](https://user-images.githubusercontent.com/30777766/29007172-d78da840-7afd-11e7-87fa-9e4c5c25855a.PNG)
![cura 5](https://user-images.githubusercontent.com/30777766/29007173-d78e3ca6-7afd-11e7-8ebd-b593aa1e12c7.PNG)

**Comment by Vandrasc** [comment]
I can't seem to reproduce this one, you tried removing your user directory folder?

**Comment by Ghostkeeper** [comment]
Doesn't reproduce for me either. I copied over all the settings and it just slices my Benchy.

**Comment by nickthetait** [comment]
@RedDropOriginal, could you try the same test but using the latest beta (2.7.0) release?

**Comment by nallath** [comment]
Alternatively; Share a project file with us.

**Comment by RedDropOriginal** [comment]
@nallath what type of file is this? How do I shzre a project file?

**Comment by RedDropOriginal** [comment]
@Vandrasc @Ghostkeeper @nickthetait I reinstalled cura. Tried new versions, nothing helps. But I did find out that when I switch to a different printer in cura everything works fine... I matched the printer settings of both machines, same start/end scripts and everything, but still my original machine that I had first won't work...

**Comment by nallath** [comment]
file->save project

**Comment by ianpaschal** [comment]
`Needs info` but never got it + irreproducible. Closing.
