### ISSUE TITLE
change filament, determine percentage

### ISSUE THREAD

**Issue by maaspt** [Ultimaker/Cura#2234]
Is there any function in Cura that can stop printer in determine percentage to change filament color ?

If we have only one extruder in printer .

I can do this in printer menu but I must control myself percentage to stop printer and change it.

I just need to change layers colors in some projects.

Regards

maaspt

**Comment by fieldOfView** [comment]
Check out Extensions -> Post Processing -> Modify G-code. Here you can add a "Pause at Height" script.

**Comment by maaspt** [comment]
Hi
It works great for me like that.

Thanks for your help.

**Comment by maaspt** [comment]
Hi

I upgraded to two extruders, one nozzle, how to change extruder in determine layer/percentage ?

In Post processing I can Pause at Heigth, and change filament manually in the same extruder, but with two extruder is there any function to change them auto ?

Regards

**Comment by maaspt** [comment]
Hi

I upgraded to two extruders, one nozzle, how to change extruder in determine layer/percentage ?
In Post processing I can Pause at Heigth, and change filament manually in the same extruder, but with two extruder is there any function to change them auto ?

Regards
