### ISSUE TITLE
infill not showing in preview

### ISSUE THREAD

**Issue by fernx** [Ultimaker/Cura#2236]
infill not showing in preview
![screen shot 2017-08-09 at 10 14 26 pm](https://user-images.githubusercontent.com/20249399/29151572-2a1abd7e-7d50-11e7-80b9-fbffd0282201.png)

**Comment by fieldOfView** [comment]
What is your infill percentage? Is it by any chance 100? An infill percentage of 100 actually results in no infill, but all layers being considered as top layers.

**Comment by fernx** [comment]
The infill is at 25%

**Comment by RedDropOriginal** [comment]
do your models kinda look like this by any chance?

![cura error](https://user-images.githubusercontent.com/30777766/29207052-f0648638-7e84-11e7-9935-1ef4cccc81c8.PNG)

**Comment by fernx** [comment]
Print without the infill and have 25% of cubic infill.

**Comment by fernx** [comment]
![img_0273](https://user-images.githubusercontent.com/20249399/29244137-db0b57ee-7f7e-11e7-8dba-d55e8434be17.JPG)

**Comment by Ghostkeeper** [comment]
So it's not just the layer view then but also the actual print that's missing infill?

**Comment by ianpaschal** [comment]
Since this needs info but the OP did not respond for 6+ months, I'm closing this issue.

**Comment by Ghostkeeper** [comment]
We'd need some information about what settings he was using if the actual infill is missing.
