### ISSUE TITLE
[2.7] Profiles window shows incorrect information 

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2237]
The profiles window shows all profiles with data from the last saved or created profile and not of its own

An image tells a better story see the speed 
![profile](https://user-images.githubusercontent.com/2055566/29163512-e30b97a8-7dfb-11e7-87c0-d4cd82dcf249.PNG)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/2151
