### ISSUE TITLE
gcode save file should default to the same name as the first stl file opened on a clear platform

### ISSUE THREAD

**Issue by FuzzySadist** [Ultimaker/Cura#224]
gcode save file should default to the same name as the first stl file opened on a clear platform

So you open: 
thing1.stl
thing2.stl

When you save, it should default to:
thing1.gcode

**Comment by TMHogenhout** [comment]
Why the first and not the last? In the case of the last, you see the name changing every time you open a file and then at least the functionality is clear.. Could easily change it, just wondering why..

**Comment by Ghostkeeper** [comment]
The first is more common for similar applications, I reckon.

**Comment by TMHogenhout** [comment]
Easiest fix ever! :D
