### ISSUE TITLE
[2.7] Use full window width

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#2241]
This is on openSUSE LEAP 42.3 with KDE Plasma 5.10.90.

![](https://pbs.twimg.com/media/DG0PxNYXsAMZ9eN.png)

Versions before 2.7 did not have this.

**Comment by Ghostkeeper** [comment]
Hmm, we haven't changed anything in that dialogue since January... Weird!

Doesn't happen on Ubuntu 17.04 or Windows 8.1.

**Comment by Ghostkeeper** [comment]
Any other dialogues or modal windows that show the same problem?

**Comment by probonopd** [comment]
I did not see this in other dialogs so far.
