### ISSUE TITLE
Skirt Minimum Length does not work

### ISSUE THREAD

**Issue by sfandersen** [Ultimaker/Cura#226]
The Skirt Minimum Length does not seem to work. It have some effect on the skirt form, just not the length. 

I also checked with http://gcode.ws/ and the generated gcode file does not contain the right length of skirt.

I am using Cura 15.06.03 (It is the same problem in Cura 15.06.02).

![skirt_min_length](https://cloud.githubusercontent.com/assets/12411130/9110861/8ba2275a-3c41-11e5-9875-6acb2b57d571.JPG)

**Comment by BagelOrb** [comment]
This has (coincidentally) just been fixed for the next major release.
