### ISSUE TITLE
Walls Bug

### ISSUE THREAD

**Issue by Rh3tt** [Ultimaker/Cura#2264]
![img-2553](https://user-images.githubusercontent.com/30961612/29243698-6615077e-7f5a-11e7-90cd-dce11c79a756.JPG)
When I try to print anything it doesn't fill in the wall completely. It turns it into a model with spider wed walls.

**Comment by Ghostkeeper** [comment]
Looks like you have a severe case of under extrusion.

Are you sure that the material diameter setting is correct for your printer?
