### ISSUE TITLE
BUG, Cura Scale?

### ISSUE THREAD

**Issue by zerspaner-gerd** [Ultimaker/Cura#2265]
## BUG, Cura Scale?

Why do occasionally not some decimal numbers appear at"Scale"?
![cura 2 7 beta](https://user-images.githubusercontent.com/29805503/29244144-6c34d75e-7fb1-11e7-8f6c-436b961d0747.JPG) Cura
![s3d](https://user-images.githubusercontent.com/29805503/29244152-7fc7fddc-7fb1-11e7-88d8-94c8e5620043.JPG)S3D
![fusion 360](https://user-images.githubusercontent.com/29805503/29244153-8724dadc-7fb1-11e7-871b-2cbee48a79e2.jpg)Fusion 360

Is not the case for every stl file.
Here is one where I saw it again
[Fidget Spinner v7_Farbe eins.stl.zip](https://github.com/Ultimaker/Cura/files/1220055/Fidget.Spinner.v7_Farbe.eins.zip)

Is this a bug?
How is it scaling with the percentages, which value is used here?

**Comment by zerspaner-gerd** [comment]
Seems to be file sizes dependent.
Here a cube (150,123 x 150,123 x 150,123) with different quality setting exported
[cube.stl.zip](https://github.com/Ultimaker/Cura/files/1220131/cube.stl.zip)

The Medium file is displayed correctly.

**Comment by Ghostkeeper** [comment]
The scaling with percentages is the ratio between the current scale and the scale of the original file.

**Comment by Ghostkeeper** [comment]
The bug reproduces for me, yeah, with both the High cube and the fidget spinner.

**Comment by zerspaner-gerd** [comment]
> The scaling with percentages is the ratio between the current scale and the scale of the original file.

Cura counts the wrong displayed value or the real correct value?
e.g. With cube high
Scaled 100.19% Result Cura = 150.285
Correct would be 150,408

Does not make a trustworthy impression, especially if you want to print accurately

**Comment by Ghostkeeper** [comment]
You can find that out by setting the line width to 0.001mm and inspecting the bounding box of the g-code (make sure to remove brim/skirt/raft first though).

The Cube High at default 100% scale, sliced on an UMO this way, results in a bounding box of X from 27.437 to 177.563 and Y from 27.436 to 177.563. The difference between those is 150.127. So the actual slice seems to be 2µm off, which can be attributed to rounding errors.

**Comment by zerspaner-gerd** [comment]
Would be nice if the ad error could be fixed. 😀

**Comment by Ghostkeeper** [comment]
Yeah, I agree. But our project manager just removed this from our planning, meaning that we won't be able to spend time on this issue on Ultimaker's time.
