### ISSUE TITLE
Slicer does not see some of the model in the stl file

### ISSUE THREAD

**Issue by Diramu** [Ultimaker/Cura#2268]
Using 2.6.2.

Slicing  models https://www.thingiverse.com/thing:2445461
file https://www.thingiverse.com/download:3932029  (T13_B2_HD_hull.stl) was incomplete.
The a model for a tank (a friend ask me to print :-), the bottom half of the model does not show up in Cura.  It worked fine using ideaMaker.

**Comment by Ghostkeeper** [comment]
Looks fine to me:
![image](https://user-images.githubusercontent.com/2448634/29708485-0873caea-8989-11e7-8168-6bd9240eb67a.png)
Using the Thingiviewer on Thingiverse as reference, that is.

**Comment by Ghostkeeper** [comment]
I do note that CloudCompare seems to also show the bottom side as missing!
![image](https://user-images.githubusercontent.com/2448634/29708559-4c129736-8989-11e7-8a78-5a8fb352a8aa.png)
Maybe something is up with the model. CloudCompare says that it removed duplicate vertices and faces, so perhaps that has something to do with it.

**Comment by ianpaschal** [comment]
Not an issue with Cura. Model seems to be bad.
