### ISSUE TITLE
Advanced parameter side window: very narrow scroll bar, difficult to manipulate (Widnows 8.1) 

### ISSUE THREAD

**Issue by pascalmayer** [Ultimaker/Cura#227]
See picture:
![capture](https://cloud.githubusercontent.com/assets/13658076/9117701/3284b6bc-3c6c-11e5-8640-2abb1800ebbe.jpg)
Thanks for the attention,
PM

**Comment by fieldOfView** [comment]
You don't have the use the scrollbar; you can grab (almost) anywhere inside the sidebar to scroll it (on the labels, not on the values). But the simple fact that I have to tell you that indicates that there is a usability issue.

**Comment by nallath** [comment]
The interface will be changed quite a bit for the new version, so closing this. If the new layout in 15.10 still has this issue you can open a new issue.

**Comment by pascalmayer** [comment]
Many thanks.

Pascal.

 

De : Jaime van Kessel [mailto:notifications@github.com] 
Envoyé : vendredi 21 août 2015 11:54
À : Ultimaker/Cura <Cura@noreply.github.com>
Cc : pascalmayer <pascal.mayer@alphanosos.com>
Objet : Re: [Cura] Advanced parameter side window: very narrow scroll bar, difficult to manipulate (Widnows 8.1) (#227)

 

The interface will be changed quite a bit for the new version, so closing this. If the new layout in 15.10 still has this issue you can open a new issue.
