### ISSUE TITLE
Concentric Top/Bottom Pattern Enhancement

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#228]
I am really liking the concentric top/bottom pattern so far! That's all I've been using.

I do have an issue with how the pattern is generated from outside to center sometimes and center to outside others. When the pattern starts in the center of a section it has nothing to connect to. It would be best if the concentric "rings" were always built from outside to center.

**Comment by BagelOrb** [comment]
This should be fairly easy to fix. Will look into it..

**Comment by nallath** [comment]
This is actually an CuraEngine issue, so closing it here.

**Comment by BagelOrb** [comment]
So did you open the issue there then?
Op 14 aug. 2015 15:59 schreef "Jaime van Kessel" <notifications@github.com>:

**Comment by nallath** [comment]
No, but it's not a Cura issue, so it's up to the orignal poster to change it as otherwise they don't get the status updates if anyone posts there.

**Comment by BagelOrb** [comment]
This is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/235
