### ISSUE TITLE
TypeError: unable to convert a Python 'NoneType' object to a C++ 'double' instance

### ISSUE THREAD

**Issue by greenlee** [Ultimaker/Cura#2280]
[crashreport.txt](https://github.com/Ultimaker/Cura/files/1225936/crashreport.txt)

threw an error when sending sliced file to octoprint.
winders 10 pro 10.0.15063 Build 15063
Cura 2.7.0 beta

**Comment by fieldOfView** [comment]
Does it do this repeatably, or did it happen just once? Could you post your logs?
Help -> Show Configuration Folder, cura.log from that folder.

**Comment by Ghostkeeper** [comment]
Perhaps the bed temperature ended up at `None` somehow?

**Comment by ChrisTerBeke** [comment]
No info given, not reproducible. Closing.
