### ISSUE TITLE
With Cura 2.7 beta on MacOS, changing Views using the menubar does not always change

### ISSUE THREAD

**Issue by rtideas** [Ultimaker/Cura#2294]
Switching Views back and front between X-ray and Solid using the menubar does not always update the view. Switching to Layers seems to help when switching back.

**Comment by Ghostkeeper** [comment]
Not able to reproduce this using the 2.7 beta on Windows 8. It might be a MacOS-only issue here.

**Comment by ChrisTerBeke** [comment]
Confirmed issue on my Mac.

**Comment by nallath** [comment]
@ChrisTerBeke Did you also logged this on Jira?

**Comment by ianpaschal** [comment]
Can no longer reproduce this; it appears to be fixed in Cura 3.4.1.

**Comment by rtideas** [comment]
Thanks!
