### ISSUE TITLE
Sometimes wrong, the version is 2.6.2

### ISSUE THREAD

**Issue by 651851996** [Ultimaker/Cura#2296]
orz
![0170819194204](https://user-images.githubusercontent.com/28496904/29486409-7fb4c864-8517-11e7-8c48-0447fd0f8015.png)

**Comment by 651851996** [comment]
2.7b also has this problem

**Comment by Ghostkeeper** [comment]
Duplicate of #1979.

**Comment by Ghostkeeper** [comment]
This is fixed for Cura 3.2.
