### ISSUE TITLE
Ironing feature in 2.7.0 beta extrudes filament

### ISSUE THREAD

**Issue by bipsendk** [Ultimaker/Cura#2297]
When trying to do ironing on a STL file, the target printer sounds like a it is extruding a bit of filament some places on the layer being ironed (the object is a flat model with some mounting-holes).

It happens on the layer at 6.00mm (layer thickness 0.2mm).

Would you prefer to have both STL file and generated gcode file ?

**Comment by fieldOfView** [comment]
That is by design. Extruding a tiny bit of material fills in tiny gaps while ironing. It has the additional benefit of keeping the nozzle primed while preventing material from degrading due to staying inside the hot hotend for too long.

**Comment by bipsendk** [comment]
It just leaves some "bumps" on the object in question (places with small distance between mounting hole and edge of object) - not exactly what I was expecting. I think the ironing feature then probably is best suited for objects with larger flat surfaces without any holes or similar in them.

**Comment by sco01** [comment]
The Ironing Flow setting (default: 10%) controls the amount of extrusion during ironing. You can try with a lower value and see if it helps.

**Comment by nallath** [comment]
This is also why it's experimental; we haven't found perfect settings for it yet. Finding those is left "As an exercise to the reader" for the moment being. We do want to hear what values you found to work though.
