### ISSUE TITLE
Group common Profiles?

### ISSUE THREAD

**Issue by changedsoul** [Ultimaker/Cura#2298]
I know this is still in development, and not sure where to post a request, so posting here.
It would be nice to have the Profiles able to be grouped into sub categories? For example, by project names, then component profiles?
For example, I am print a Plane, and need to tweak various print parameters for various parts.
It would be fantastic if the Profiles sections would be able to have for example, 
Profiles -> 
- Profile Name (Plane) ->
- - Stubborn Wing settings
- - Fuselage Settings
- - Etc settings

That way you dont have to have a long list of profiles to sort through if you have many of them.

**Comment by Ghostkeeper** [comment]
This feature was removed from our planning because it's older than 12 weeks, so our project manager thinks it's no longer applicable.
