### ISSUE TITLE
Model modifying tools not scaling

### ISSUE THREAD

**Issue by quillford** [Ultimaker/Cura#23]
The tools overlayed on the model for repositioning, rotating, etc. don't scale with the rest of the platform.
![cura](https://cloud.githubusercontent.com/assets/8762862/7945854/2c32e72e-0928-11e5-961d-c79712c14d8d.png)
![cura 2](https://cloud.githubusercontent.com/assets/8762862/7945856/2dbb80d8-0928-11e5-9835-a58bf979786c.png)

**Comment by nallath** [comment]
I believe this is by design, but that does not mean it cannot be changed / improved.

What behaviour would you expect?

**Comment by awhiemstra** [comment]
This is indeed intentional and different from legacy Cura. This is behaviour from 3D modelling programs that we copied.

**Comment by quillford** [comment]
Ah. It is different from the current Cura release, so I thought it may have been a bug.
