### ISSUE TITLE
master branch - OTT spaghetti infill

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#2306]
Just tried enabling the spag infill, didn't alter any params, came out rather thick!

![screenshot_2017-08-22_20-50-41](https://user-images.githubusercontent.com/585618/29584471-b33ed48e-877b-11e7-9af5-eabd64daea3e.png)

**Comment by nallath** [comment]
That's why it's experimental ;)

**Comment by smartavionics** [comment]
Indeed, do you want any more info re settings, system, etc.?

**Comment by nallath** [comment]
@BagelOrb; Is this something we want to improve on?

**Comment by BagelOrb** [comment]
Errrr. I don't really understand what's expected from me here.

Spaghetti infill works weird. It is generating lines which are supposed to fill downward, but the frontend is interpreting those extrusion paths as being very thick. The frontend cannot simulate how the filament will curl up into spaghetti.

**Comment by Ghostkeeper** [comment]
I think we might have to reduce the default setting for maximum height to 1.0mm instead of 2.0. Perhaps that works better in most printers.

**Comment by BagelOrb** [comment]
I haven't tested that much. That's why it's experimental. I have no idea whether 1mm works better than 2mm. Did you test this @Ghostkeeper ?

**Comment by Ghostkeeper** [comment]
No, I didn't test that. It was just a feeling. 1mm is plenty to create spaghetti, but you might get more reliable extrusion. I did test the default settings for spaghetti infill and that just produced a giant blob of plastic on one of the walls.

Even with 1mm layers, you'll still get humongous lines. That's just the way that the layer view visualises it, not knowing that the material will/should just fall down.

**Comment by ianpaschal** [comment]
Closing because this is 6+ months without activity. Exper'mental features gon' exper'ment.
