### ISSUE TITLE
Wrong font size

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#2309]
Just noted while playing with themes that there are some texts, which are not in the same size.
For example:

![image](https://user-images.githubusercontent.com/1847437/29614432-66d9f6f2-880a-11e7-9346-2fce17845255.png)

**Comment by nallath** [comment]
The code didn't correctly set the font in all cases. Should be fixed now.

**Comment by thopiekar** [comment]
Thanks, @nallath :+1:
