### ISSUE TITLE
Cura 2.7 crashes on exit under OS X

### ISSUE THREAD

**Issue by kaimikael** [Ultimaker/Cura#2314]
I am running Cura 2.7 beta under OS X 10.10.5, and consistently, every time I quit the application, it crashes with a segmentation violation.
I attach the cura log as well as the OS X crash log for the latest incident.
[cura.zip](https://github.com/Ultimaker/Cura/files/1248207/cura.zip)

**Comment by nallath** [comment]
This should be fixed for the 2.7 final release (which will be out soon). Could you retest it with the final if it's out?

**Comment by kaimikael** [comment]
Confirmed that this works in 2.7.0.
