### ISSUE TITLE
Cura 2.7: Editing new material deletes all other materials

### ISSUE THREAD

**Issue by kaimikael** [Ultimaker/Cura#2315]
As shown in the attached video, I duplicated a material and when editing the properties of the new material, all other materials were deleted.  I can get around this by deleting the ~/Library/Application Support/cura/2.7/ directory and rerun Cura, which will restore the materials.
I also attach the cura log file.
I run Cura 2.7 beta under OS X 10.10.5.
[cura.zip](https://github.com/Ultimaker/Cura/files/1248243/cura.zip)
[video.zip](https://github.com/Ultimaker/Cura/files/1248248/video.zip)

**Comment by nallath** [comment]
This should be fixed for 2.7 final release. I just tested this myself and it did not happen for me anymore. Could you retest this when the final is out?

**Comment by kaimikael** [comment]
I can confirm that in 2.7.0 the materials are no longer deleted when editing a duplicate.
