### ISSUE TITLE
Cura 2.6.2: Multiple Machines and Profiles

### ISSUE THREAD

**Issue by tisfablab** [Ultimaker/Cura#2317]
I've set up Cura for 3 machines (UM2+, UM2, and a Custom FDM Printer)

After a while I discovered that the UM2 and Custom FDM Printer share print profiles - i.e., when I create a new profile for the Custom FDM Printer (with a rather unique name), it is also listed when i switch to the UM2 machine, and vice versa.

When I switch to the third machine, the UM2+, I do not see the profiles I create for the other two machines.

**Comment by nallath** [comment]
This is correct. The UM2 does not have profiles per material per nozzle (same as the custom machine). The UM2+ does have this.
