### ISSUE TITLE
Random Lines with Raft

### ISSUE THREAD

**Issue by SovietOvinnik** [Ultimaker/Cura#2319]
I have raft selected and for some reason it prints lines way off the raft.
![20170824_191745_hdr 1](https://user-images.githubusercontent.com/31331238/29696992-4577820c-8901-11e7-9870-43d54474fb6d.jpg)

**Comment by LipuFei** [comment]
@SovietOvinnik Could you provide the model you were printing and the settings you have? A log file will also be appreciated.

**Comment by Ghostkeeper** [comment]
Doesn't reproduce for me using the Ultimaker 2+/0.4mm/PLA with default settings except setting the adhesion type to raft with a 1cm cube.
