### ISSUE TITLE
cura 2.6.2

### ISSUE THREAD

**Issue by JAUYEB** [Ultimaker/Cura#2323]
Spanish traslation is not correct:

"nozzle" not is "tobera" in spanish, is "boquilla".

Thanks a lot!

**Comment by Ghostkeeper** [comment]
Wikipedia named it `tobera`, but both seem to be correct according to my dictionary. `boquilla` seems to indicate more of a beak-type thing than an orfrice-type thing.

I can't change this myself as I am no native speaker of Spanish. Changing the wording may also change the inflections and particles surrounding the word `tobera`, so a native speaker of Spanish will have to make these changes in the Spanish .po files.

**Comment by JAUYEB** [comment]
I'm a native speaker of Spain.  "tobera" is big, "boquilla" is small. The nozzle is small.

I will change the .po files. 

Thanks!
