### ISSUE TITLE
Rearranged printjob area

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#2325]
Recently, part of the printjob area was moved into the sidebar. When watching the print monitor, the data that is now shown in the sidebar suggests it is relevant for the currently monitored print, which may not be true.

**Steps to reproduce:**
* Load and slice an object
* Send it to the printer for printing (either through USB, UM3 or OctoPrint)
* Go back to the settings tab and load another model, change settings etc.
Note that the time in the sidebar will reflect the changes
* Now switch back to the monitor tab to check in on the ongoing print
Note that the time in the sidebar is now confusingly not relevant to the currently printing job

The previous design purposefully subdued the viewport and the print job stats area to prevent this confusion.

An additional problem is visible here:
![image](https://user-images.githubusercontent.com/143551/29740726-4c7d590c-8a5d-11e7-90d3-2cb3cd953b69.png)
You may also note the misalignment, but I believe that is going to change with the dark sidebar redesign.

**Comment by nallath** [comment]
I've notified our UX guys.

**Comment by Ghostkeeper** [comment]
Did you get a response yet, @nallath?

**Comment by nallath** [comment]
Nope. But i'm asuming any next re-design will take this into account. 
I did hide the print time widget in monitor as it was confusing.

**Comment by ChrisTerBeke** [comment]
Recent UI changes fixed this (?)
