### ISSUE TITLE
User submitted profiles not in release package

### ISSUE THREAD

**Issue by quillford** [Ultimaker/Cura#233]
Why are user submitted profiles not in the release package? If the user knows how to compile Cura and is willing to, they are going to know how to edit a JSON file to put in basic properties for their printers and there is no point in merging PRs with profiles.

**Comment by daid** [comment]
Minor patch releases are done from the release branch, only containing bugfixes:
https://github.com/Ultimaker/Cura/tree/15.06

Next major release will have the extra profiles.

**Comment by quillford** [comment]
Thanks for clearing that up. Should people make PRs against 15.06 or master then?

**Comment by BagelOrb** [comment]
Against master.

**Comment by nallath** [comment]
Unless if it's a bug fix, then you should do it against the version branch (15.06 in this case)
