### ISSUE TITLE
CURA 2.6.2 Cost Calculation error

### ISSUE THREAD

**Issue by Geoloog** [Ultimaker/Cura#2336]
There are cost calculation errors when calculation for different materials.

1.  If one has sliced a model with one type of material and then choose another type of material with a significant change in price the values stays the same.

2.  This calculation is true also in so far as that the cost is incorrectly calculated.  
eg.  I have a model that uses 4.73m of filament that cost R0.85/m.  The actual cost is R4.03 but Cura returns a value of R6.06

Regards,

Hendrik Bosman
Western Cape
South Africa

**Comment by nallath** [comment]
I can't reproduce either of your issues on the master branch. If I switch to another material, the price changes accordingly. 
If you look at the Cost per Meter setting (which is automatically calculated) and multiply this by the length used, I get the correct value.

**Comment by Geoloog** [comment]
Hi there Jaime,

Please check that attached photo.

Kindest regards

Hendrik Bosman

**Comment by nallath** [comment]
Attachements need to be uploaded to github. If you attach them to the email, they get lost. 

Did you also check this with 2.7? This is the release that is closest to master.

**Comment by Geoloog** [comment]
Hi Jaime,

Sorry did not know that.

Yes I did and it is the same problem.

Using length X cost as calculated where the material is configured differs
from the final amount provided by Cura.  Both 2.7 and 2.6.2

I also did a manual calculation by determining the g cost and multiplying
by g calculated by Cura the reply given by Cura is about 40% incorrect.

Kind regards,

Hendrik


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Hi   ,





*Kind regards,Hendrik*



*=======================================================NOTICE:  Be
Environmentally Responsible.Only print this email if absolutely unavoidable
!!!!!!!*

2017-08-30 15:12 GMT+02:00 Jaime van Kessel <notifications@github.com>:

**Comment by Geoloog** [comment]
![image](https://user-images.githubusercontent.com/22645522/29875458-66821a5a-8d9a-11e7-983c-7bcc37df544e.png)

I don`t know but Cura 2.7 & 2.6.2 use the cost values in "Materials and get R23.02 but manually calculated 18.38m = Cost R15.6230 and 54g = Cost R15.4165

Regards,

Hendrik
![cura problem](https://user-images.githubusercontent.com/22645522/29875737-293a2cea-8d9b-11e7-8831-202546dfa286.png)

**Comment by Geoloog** [comment]
Seem to have made another boo-boo :p 

Sorry
