### ISSUE TITLE
Cura 2.7.0 Cancel print

### ISSUE THREAD

**Issue by Orlandoknox** [Ultimaker/Cura#2344]
When cancelling a started print job the printer runs a z-calibration (on Prusa MK2), which causes a collision with the cancelled print (and potentially causes damage to the printhead).

**Comment by nallath** [comment]
I'm not familliar with the Prusa machines, but this sounds like something that your printer does. Cura doesn't trigger any calibration as far as I'm aware.

**Comment by Orlandoknox** [comment]
Just to be more precise: This happens when printing over USB and cancelling the print in the Cura software.  It is fine to cancel the print on the printer when started from SD card (the gcode is fine). So the problem could well be with the machine and I'll address it with Prusa.

**Comment by Jhinta** [comment]
Duplicate of #2307
