### ISSUE TITLE
2.7 Gcode name for multiple model

### ISSUE THREAD

**Issue by yyh1002** [Ultimaker/Cura#2346]
The generated Gcode has a different name from the project title. 
Happens to 2.7b and 2.7.0 on Windows 10.

Load several model on the printbed one by one. 
The first model loaded is named "a.stl", and the last is named "d.stl".
The default project name on bottom right corner is "UM2_a" as usual. 
Then save the slice to removable device. 
However, the generated Gcode name is "d.gcode", instead of "UM2_a.gcode", which is not the project name.

**Comment by LipuFei** [comment]
Hi @yyh1002, I can confirm that this is a bug. Thanks for the report!

**Comment by Vandrasc** [comment]
Dev's see CURA-3947.
