### ISSUE TITLE
Can't slice correctly in Moai Printer Profile

### ISSUE THREAD

**Issue by ComicBit** [Ultimaker/Cura#2351]
If i try to slice at 0.025 um on this profile on cura 2.6 i obtain this:
<blockquote class="imgur-embed-pub" lang="en" data-id="RVao8ki"><a href="//imgur.com/RVao8ki">View post on imgur.com</a></blockquote>

Instead in Cura 2.7 with the identical same settings i get this:
<blockquote class="imgur-embed-pub" lang="en" data-id="nljbplU"><a href="//imgur.com/nljbplU">View post on imgur.com</a></blockquote>

**Comment by LipuFei** [comment]
Hi @ComicBit, could you create a project file out of your print and share with us if you don't mind? It may have something to do with the settings.

**Comment by Ghostkeeper** [comment]
The only meaningful change made to the Moai in between the two versions was this one: https://github.com/Ultimaker/Cura/commit/c3dcee7f1499f751125796a50641b3cf120a4a7a#diff-ac4f35f8ba7567a9d992cd26210bfeb6

Perhaps `infill_overlap` has something to do with it?

**Comment by Ghostkeeper** [comment]
> slice at 0.025 um

:open_mouth: 25 nanometres!

**Comment by ComicBit** [comment]
@LipuFei there you go [https://www.dropbox.com/s/86gozjma90zg5fl/PM_2%20%28repaired%29_Hollowed.curaproject.3mf?dl=0](url)

@Ghostkeeper about 0.025 um..... LOL i'd made a mistake :D

**Comment by ComicBit** [comment]
Any guess on this?

**Comment by Ghostkeeper** [comment]
I tried and could reproduce the bug there too.

I don't know what's causing this and I can't think of anything done between 2.6 and 2.7 that would change it. I could perform a bisect on CuraEngine to see, but with a heavy model such as this and my computer not having enough memory to show this in Layer View that would take quite a lot of time.

**Comment by ComicBit** [comment]
Let me know if i can help you in any way. My computer is pretty powerful

**Comment by ianpaschal** [comment]
@ComicBit Sorry for the delay, are you still experiencing this issue on later versions of Cura?

**Comment by Ghostkeeper** [comment]
Yeah, the bug still exists.

![screenshot from 2018-03-26 11-34-25](https://user-images.githubusercontent.com/2448634/37898687-c242ef48-30e9-11e8-8898-3b490cb91b21.png)

It's worth trying some of the meshfixing settings maybe. But I still don't get why this broke in version 3.0.

**Comment by diegopradogesto** [comment]
This issue is somehow fixed or not happening anymore for this model:

![Screenshot 2019-09-10 at 17 20 04](https://user-images.githubusercontent.com/15830521/64627104-551b2e80-d3ef-11e9-9b64-0ca2e51369c9.png)
