### ISSUE TITLE
Cura 2.7.0 lagging when typing in values. Mac OS 10.12.6

### ISSUE THREAD

**Issue by supersoulman** [Ultimaker/Cura#2355]
when ever i enter values there is major lag. Tried a system restart and it did not fix the issue.
video is attached. when i started to type i did not pause keystrokes between numbers. its kinda hard too tell in the video you can really see it with the last digit in the layer height (6)

[cura2.7.0lag.zip](https://github.com/Ultimaker/Cura/files/1269143/cura2.7.0lag.zip)

**Comment by Ghostkeeper** [comment]
We made a fix that reduces this problem a bit: https://github.com/Ultimaker/Cura/commit/c614f02d0ff9cbaf8476fb764ac7849c49fc0e45

**Comment by supersoulman** [comment]
is there a way to update with that fix

**Comment by Ghostkeeper** [comment]
You'd have to build Cura yourself, or wait for our next release.

**Comment by ianpaschal** [comment]
Since this was fixed, I'm closing this issue.
