### ISSUE TITLE
Install/Remove older versions of Cura 

### ISSUE THREAD

**Issue by konvoj** [Ultimaker/Cura#2359]
Lately i was upgrading from Cura 2.6.2 to 2.7 and it was quite confusing that now both versions are installed.

As part of the installation a dialog or a tick box shall be offered to the user saying something like "Do you want to remove older Cura versions". 
This would allow user to have only the most recent version if needed, without manual action of removing the older Cura version by hand.

**Comment by Ghostkeeper** [comment]
It does. When you install Cura it should find that older versions are installed and should ask you whether you want to uninstall them.

**Comment by Ghostkeeper** [comment]
![image](https://user-images.githubusercontent.com/2448634/30249475-9f208bfc-963d-11e7-85ac-c6f60eac91a7.png)

**Comment by modem7** [comment]
The folders for those versions are still on the system.
![capture](https://user-images.githubusercontent.com/4349962/30289116-efddcff6-9722-11e7-8bef-e2ed26a177f5.JPG)

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/1151

**Comment by Ghostkeeper** [comment]
This is still a problem. The Windows uninstaller doesn't remove the configuration files.
