### ISSUE TITLE
Cura 2.7 Unable to zoom out

### ISSUE THREAD

**Issue by weithiam** [Ultimaker/Cura#2361]
After zooming in to check layer by layer I am unable to zoom out anymore.  Other view changes still work.

Neo

**Comment by Jhinta** [comment]
+1 this random happens

**Comment by nickthetait** [comment]
Bizarre! After restarting the application everything returns to normal? How often would you describe this occurring?

**Comment by Drayson80** [comment]
+1 
And additionally sometimes when manipulating the model, I get a very strange behavior of pan/zoom/turn so that at the end, the whole print platform is out of sight... any idea how to center the print platform again?

**Comment by nallath** [comment]
We had the feature request for a while to reset the camera view to the home position. Haven't found the time to build it yet.

**Comment by Ghostkeeper** [comment]
I've seen this sometimes when using the new "Zoom to mouse position" feature. But it's hard to reproduce.

Were you using the Zoom to mouse position thing?

**Comment by Drayson80** [comment]
Acc. to my experience, it has the same behavior independend of with or w/o the Zoom to mouse position thing...

**Comment by ianpaschal** [comment]
This is fixed in the most recent version of Cura (3.2.1).
