### ISSUE TITLE
Cura 2.7 unable to select nested materials

### ISSUE THREAD

**Issue by stephanpark** [Ultimaker/Cura#2365]
Unable to select materials that require drill down.  Only one level opens rarely allowing selection and actual material to be used for print.  Only able to select "Generic" materials because they are not nested.

Windows 10 Pro 64bit.

**Comment by LipuFei** [comment]
Hi @stephanpark, by "unable to select", do you mean that the options are there but when you click, it doesn't react, or there is no multi-level options for you to select at all?
And could you provide your log file as well? Thanks.

**Comment by stephanpark** [comment]
The UI element pops up but hot-zone is missing thus not triggering sub item flyout.  It instead triggers whatever is beneath such as "more-info" info bubbles from anything behind it.  Log file location unknown, no errors triggered to have seen an error dialog, where is it?

**Comment by LipuFei** [comment]
The log file is here: `C:\Users\<your-username>\AppData\Roaming\cura\2.7\cura.log` on Windows.

**Comment by nallath** [comment]
No machines that we currently support have settings that depend on "specific" materials. If you select red ultimaker PLA, it will use the profiles as provided by the generic material.

As for not being able to select them; i fear that there is little we can do about this. The generation of those popups is done by our GUI library, Qt.

**Comment by Ghostkeeper** [comment]
I'm not entirely sure what you mean, actually. What UI element is this issue talking about? The specific-colour materials in the list of materials? What do you mean with "sub item flyout"?

**Comment by ianpaschal** [comment]
Needs info but never got it.
