### ISSUE TITLE
[Request] Use the delete button on keyboard for removing objects from platform

### ISSUE THREAD

**Issue by quillford** [Ultimaker/Cura#237]
This was in daid's cura and was very useful.

**Comment by daid** [comment]
Which OS? as it works for me in Windows 7

**Comment by quillford** [comment]
OS X 10.10.4

**Comment by nallath** [comment]
This is OSX being its bitching self. The delete button on mac isn't a delete button, it only masquerades as one. It is in fact a backspace. Try using fn+delete.

**Comment by BagelOrb** [comment]
Still we could make it so that Backspace also deletes an object. (Even on Windows, for simplicity)

**Comment by nallath** [comment]
We should.
