### ISSUE TITLE
Splash screen low resolution on retina displays

### ISSUE THREAD

**Issue by ChrisTerBeke** [Ultimaker/Cura#2378]
When running Cura on a retina MacBook Pro, the splash screen looks very pixelated. Probably higher resolution images needed for screens with higher DPI?

Application Version: 2.7 (but happened before as well)
Platform: MacOS
Display Driver: Integrated Intel graphics

Steps to Reproduce:
Start Cura -> watch splash screen

Actual Results:
Pixelated splash screen

Expected results:
A nice high-res splash screen (as it's the first thing you see!)

**Comment by Ghostkeeper** [comment]
A redesign was planned already for the 3.0 release.

**Comment by ChrisTerBeke** [comment]
Indeed, just to make everyone aware that we need high-res assets :)

**Comment by ChrisTerBeke** [comment]
@riodoro1 indeed, it turned out to be quite complicated as we don't have access to all QT features yet in the splash screen phase. We're looking for alternative solutions but it will take some time.
