### ISSUE TITLE
Postprocessing plugins with cura 2.7

### ISSUE THREAD

**Issue by JPFrancoia** [Ultimaker/Cura#2381]
Hi,

Are the PostrProcessingPlugins operational with cura 2.7 ? It seems not at the moment.
Cura installed on Linux.

I cloned the PostProcessingPlugin repo in ~/.local/share/cura/master/plugins, but the menu doesn't appear.

Cheers

**Comment by JPFrancoia** [comment]
Ah, I found the issue.

Before cura 2.7:

```
.local/share/cura/master/plugins/PostProcessingPlugin
```

After cura 2.7 it needs to be:
```
.local/share/cura/master/plugins/PostProcessingPlugin/PostProcessingPlugin
```

And it also needs a ```plugin.json``` file, it doesn't have one now.

```
{
	"name": "PostProcessing plugin",
	"author": "John do",
	"version": "2.2",
	"api": 4,
	"description": "Post processing"
}
```

It's probably not the right json, and also the author of the plugin doesn't get credit, but sorry I was in a rush.

Also, maybe you could improve the "what's new" (like putting a link ?) when compatibility is broken like that ?

**Comment by fieldOfView** [comment]
You probably got the wrong branch of the PostProcessingPlugin. You need the 2.7 branch or the master branch. Those come with a plugin.json file.

**Comment by JPFrancoia** [comment]
True.
