### ISSUE TITLE
AppData folder for 'stderr.log' and 'stdout.log' under macOS

### ISSUE THREAD

**Issue by wojtusch** [Ultimaker/Cura#2382]
Hi,

it seems like Cura 2.7 is automatically creating an 'AppData' folder in the home folder under macOS Sierra (10.12.6). Other versions might be affected as well. The folder contains a 'Local/cura' folder with the log files 'stderr.log' and 'stdout.log'. This folder and files are always recreated when Cura is loaded.

**Comment by fieldOfView** [comment]
Thanks for reporting. It was fixed this morning.
