### ISSUE TITLE
Master branch lagging after released version

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#2385]
The released version at this time is 2.7, master branch is at 2.6.99
How is it possible that the master branch (which should be used for alpha testing) is lagging the released version?

**Comment by nallath** [comment]
master just uses "master" as a version number. At least, that what it's doing for me.

**Comment by smartavionics** [comment]
I think that must be the PPA, the OP is referring to.

**Comment by nallath** [comment]
Ah, well the PPA is not officially supported as @thopiekar does that in his own free time. So it can occasionally be a bit behind.

**Comment by thopiekar** [comment]
Yep, and I'm too busy to do the update currently.

**Comment by maukcc** [comment]
Ahh, I see now. Your master branch is a couple of commits behind :) the ultimaker one.
No worries, thanks for your efforts anyhow thopiekar, I am loving it.

**Comment by maukcc** [comment]
this can be closed
