### ISSUE TITLE
Cura 2.7.0 - Number of Layers UI issue

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#2396]
Incorrect space for the number of layers in "View Mode: Layers" when are less than 100 layers.

![screenshot_2](https://user-images.githubusercontent.com/12901952/30161481-a82f1ac8-93c8-11e7-9d5d-6d9c48ab7fe2.jpg)

![screenshot_1](https://user-images.githubusercontent.com/12901952/30161485-ae58d86c-93c8-11e7-9151-9161dcf1d40d.jpg)

**Comment by ChrisTerBeke** [comment]
As this interface element is completely changed in the next release, closing this for now. Please re-open if the upcoming release still gives you issues with this.

**Comment by Ghostkeeper** [comment]
This still occurs:
![image](https://user-images.githubusercontent.com/2448634/31076183-56d426cc-a779-11e7-8d4f-94219cb892a2.png)
I loaded an 1cm cube with UM3's default settings.
