### ISSUE TITLE
2.7 Beta worked new 2.7 does not

### ISSUE THREAD

**Issue by PapaG-Design** [Ultimaker/Cura#2400]
Uploaded latest version replacing the Beta version and now the program will not open goes through the opening process get to preparing scenes and then nothing loading screen goes away.  Tried reloading it same issue.  2.7 Beta was working great.

**Comment by Thisismydigitalself** [comment]
Try renaming cura 2.7 folder to 2.7BETA and reinstall 2.7 which will create a fresh folder.

**Comment by PapaG-Design** [comment]
Did not work.

On Sep 7, 2017 11:49 AM, "Thisismydigitalself" <notifications@github.com>
wrote:

Try renaming cura 2.7 folder to 2.7BETA and reinstall 2.7 which will create
a fresh folder.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/Cura/issues/2400#issuecomment-327856721>, or mute
the thread

**Comment by MFHFozzy** [comment]
try this:
Uninstall everything.
Then Delet all cura fodlers in
%homepath%\appdata\local\cura 
and
%homepath%\appdata\roaming\cura
Then Empty all temp folders.
Then re-install 2.7 release.

They dont do a good job when uninstalling.

**Comment by Ghostkeeper** [comment]
Renaming the file didn't work properly because it then found a 2.6 folder and upgraded those again.

To actually fix this, I'd like to see a log file of when you open Cura 2.7.

**Comment by ianpaschal** [comment]
No info was provided after several weeks, so I'm closing this.
