### ISSUE TITLE
Cura 15.06.03 does not work with Ultimaker Original

### ISSUE THREAD

**Issue by TheNeuron** [Ultimaker/Cura#242]
Recently I updated Cura to 15.06.03 and updated the firmware of the Ultimaker, now Cura refuses to print since it wants to "Bed heating" even though there is none installed. The printer is defined as an Ultimaker Original and every box concerning the bed heating is disabled. Still in the display of the Ultimaker it says "Bed heating". Since there is no Bed to heat it does not print.

**Comment by Xisle** [comment]
Enable "Bed Temperature" and set it to zero.

**Comment by awhiemstra** [comment]
The original should have a machine setting that indicates there is no heated bed. The engine currently does not account for that when adding bed temperature. As a workaround, you can set bed temperature to 0 as @Xisle suggests.

Can you open a new bug on the engine for this? (http://github.com/ultimaker/CuraEngine/issues)

**Comment by TheNeuron** [comment]
Done

Thanks, the workaround works
