### ISSUE TITLE
XY-Jerk

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2424]
Is it possible to set different value for either X and/or Y Jerk?
It looks as though both X & Y are linked. for my printer i like to set lower Jerk for Y due to heavy printbed.

**Comment by nallath** [comment]
Nope, that's not possible now.

**Comment by Ghostkeeper** [comment]
There is no g-code for it: http://reprap.org/wiki/G-code#M205:_Advanced_settings

I'm afraid X and Y will always be linked, or at least until the standard moves on.
