### ISSUE TITLE
Feature Request - Z Hop only on outer shell/top

### ISSUE THREAD

**Issue by Eganwp** [Ultimaker/Cura#2426]

**Comment by Eganwp** [comment]
Final product print quality could be HUGELY improved if there was an option to enable Z-hop on the outer shell/top. Then we wouldn't have these great big nozzle travel lines showing on our finished prints. I don't want to enable Z-hop for the entire print job because of the zits it leaves on the outter shell. This would give everyone a vastly improved final product for print quality!

**Comment by konvoj** [comment]
Have you tried the new experimental ironing feature in 2.7? When tuned right, this will give you the best looking top surface currently possible.
I agree however that having a Z-hop on top layer is a logical proposal. I could even imagine this to be a default setting.

**Comment by Ghostkeeper** [comment]
This one was older than #3115, but the other one has more information now so let's close this and continue discussion over there.
