### ISSUE TITLE
Cura 2.7 wont start without SD card in computer

### ISSUE THREAD

**Issue by Jasp-design** [Ultimaker/Cura#2436]
As above. If I start Cura without inserting an SD card I get a dialogue box that cannot be dismissed. 
![capture](https://user-images.githubusercontent.com/31987946/30480210-8e19cfd6-9a10-11e7-9f35-9ab16f165aeb.JPG)

This is easy to fix (by inserting an SD card, but is clearly not right!)

**Comment by nallath** [comment]
This is a known issue. Our build system did some weird stuff here. We're looking into it.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/1022
