### ISSUE TITLE
[Request] Visual marker for origin

### ISSUE THREAD

**Issue by quillford** [Ultimaker/Cura#244]

**Comment by Ghostkeeper** [comment]
The origin is always in the centre. Perhaps it is useful, but I think the effect should be fairly subtle. Perhaps it is good style to draw a small cross of like 10 pixels wide in the centre in a slightly darker shade of grey than the platform surface. Is that the sort of thing that you meant?

**Comment by quillford** [comment]
I mean the origin of the printer (i.e. 0,0).

**Comment by quillford** [comment]
It was like this in daid/Cura 
![](https://cloud.githubusercontent.com/assets/8762862/9218409/1e2dac72-4087-11e5-8146-8fd9bb643462.png)

**Comment by BagelOrb** [comment]
Why is that origin of any importance to the user?

**Comment by quillford** [comment]
If there is no platform model for their printer's profile, it shows the orientation of the model on the bed.

**Comment by BagelOrb** [comment]
Every printers profile should have a platform model. We're not going to introduce features which only have use when content supplied by other printers is lacking.
