### ISSUE TITLE
[master] Test suite failing

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#2443]
They are already failing for a while. Thus I guess the reason is not a trivial typo, which has been merged accidentally.

https://launchpadlibrarian.net/337309023/buildlog_ubuntu-zesty-amd64.cura_1%3A2.7.99-master~201709171402~rev2163~pkg165~ubuntu17.04.1_BUILDING.txt.gz

**Comment by Ghostkeeper** [comment]
Meanwhile, our CI system has been failing too, but with a different error message, and only since 5 days (this issue was created 7 days ago). The reason is quite weird:

    ImportError while importing test module '/home/jenkins-slave/workspace/Ultimaker_Cura_master-BQUA4C4UM3FZISSZVJXNSISBBFG5AEAYDAHVRJLN4JM7YCXFMM2Q/tests/Settings/TestCuraContainerRegistry.py'.
    Hint: make sure your test modules/packages have valid Python names.
    Traceback:
    ../tests/Settings/TestCuraContainerRegistry.py:10: in <module>
        from cura.Settings.CuraContainerRegistry import CuraContainerRegistry #The class we're testing.
    ../cura/Settings/CuraContainerRegistry.py:13: in <module>
        from UM.Settings.ContainerRegistry import ContainerRegistry
    ../../Ultimaker_Uranium_master-56PCSSZQ33LNXFR4F3B5G5VXQLJWEM733JUXWYEOW6UTTGQ5FCIA/UM/Settings/ContainerRegistry.py:35: in <module>
        import UM.Qt.QtApplication
    ../../Ultimaker_Uranium_master-56PCSSZQ33LNXFR4F3B5G5VXQLJWEM733JUXWYEOW6UTTGQ5FCIA/UM/Qt/QtApplication.py:15: in <module>
        from UM.FileHandler.ReadFileJob import ReadFileJob
    ../../Ultimaker_Uranium_master-56PCSSZQ33LNXFR4F3B5G5VXQLJWEM733JUXWYEOW6UTTGQ5FCIA/UM/FileHandler/ReadFileJob.py:5: in <module>
        from UM.Application import Application
    ../../Ultimaker_Uranium_master-56PCSSZQ33LNXFR4F3B5G5VXQLJWEM733JUXWYEOW6UTTGQ5FCIA/UM/Application.py:15: in <module>
        from UM.Settings.ContainerRegistry import ContainerRegistry
    E   ImportError: cannot import name 'ContainerRegistry'

I'm getting the same error when running the unit tests locally.
