### ISSUE TITLE
[idea] Option to just upload file on Octoprint 

### ISSUE THREAD

**Issue by BrokenFire** [Ultimaker/Cura#2445]
Hi!

It will be nice if we can just upload G-Code on Octoprint for a later print.

**Comment by fieldOfView** [comment]
This is already possible in the "Connect to OctoPrint" dialog; uncheck the "Automatically start print job after uploading" checkbox.

**Comment by fieldOfView** [comment]
Requests for the OctoPrint plugin go to https://github.com/fieldofview/octoprintplugin/issues

**Comment by BrokenFire** [comment]
Oh ! Thanks !
