### ISSUE TITLE
Maybe a slice problem with 2.6.2

### ISSUE THREAD

**Issue by ReggaeRoy** [Ultimaker/Cura#2446]
Hi
Started using 2.6.2 a few days ago. Printed 3 jobs with no problems, on the 4 job it wold get about 4 slices into it and the feed would chuck a small fit and block up, seemed to try and feed to much filament through, all bent up between the nozzle and feed wheel. After a few try's with minor adjustments the best I could get was to brake the filament. tried repositioning the job etc. Gave up and loaded 15.04.6 and it printed first time.
**I don't claim to be an expert so I was wondering if anyone wants more details and perhaps the gcode or something to cast an eye over it?** Maybe I missed something!
Roy

**Comment by Ghostkeeper** [comment]
What printer were you using? It could be a filament diameter issue, if 15.04.6 worked better. Check out the material manager, see what the material properties are, and whether the filament diameter is correct there.
