### ISSUE TITLE
Preferences "Defaults" button not working

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#245]
This bug was reported by user 3dnerd on the Ultimaker forum. I've reproduced the bug on my computer. See [the forum topic](https://ultimaker.com/en/cura/view/17006-default-button-not-working) for possible details.

Application version: 15.06.03
Platform: Windows 7

Steps to reproduce:
* Start Cura (I used a fresh install, maybe it matters but probably not).
* Go to preferences. Change some preferences around so they are non-default.
* Click the "Defaults" button.

Expected behaviour:
* The preferences are reset to the original settings as if it were a fresh install of Cura.
* The changes are immediately visible in the preferences window.

Actual behaviour:
* Seemingly nothing happens.

**Comment by awhiemstra** [comment]
The General page and the View page both reset the preference properly but do not display that correctly. Neither the settings page nor the plugins page currently implements reset().
