### ISSUE TITLE
Cura 2.7 will not show helpers/infill/shell

### ISSUE THREAD

**Issue by Racingf3** [Ultimaker/Cura#2451]
After upgrading to Cura 2.7 i can not see helpers/infill/shell. I have Cuta also on my laptop (2.7) here it works fine.

**Comment by smartavionics** [comment]
Sounds like a graphics driver problem, are you using the latest OS/graphics drivers/etc?

**Comment by Racingf3** [comment]
Yes, all updated.

I can se travelers.

Thor-Christian Ebbesvik
Daglig leder
Autosalg A/S
tc@autosalg.no<mailto:tc@autosalg.no>
www.autosalg.no<http://www.autosalg.no>

Den 18. sep. 2017 kl. 23.38 skrev Mark Burton <notifications@github.com<mailto:notifications@github.com>>:


Sounds like a graphics driver problem, are you using the latest OS/graphics drivers/etc?

-

**Comment by Ghostkeeper** [comment]
Strange. Just to be sure, you did activate the check marks for the Helpers, Shell and Infill in the layer view panel, didn't you? 😛 

You could try upgrading your graphics drivers. The intended rendering requires OpenGL 4.1.

Or you could set Cura's rendering to legacy mode: Go to Preferences -> Configure Cura... -> Force layer view compatibility mode (restart required). This will disable the fancy 3D tubes in Layer View, but at the paths should become visible again. The compatibility mode only requires OpenGL 2.0.

**Comment by Racingf3** [comment]
I am running gtx780 ti so should work fine.

Works on Cura 2.6

Thor-Christian Ebbesvik
Daglig leder
Autosalg A/S
tc@autosalg.no<mailto:tc@autosalg.no>
www.autosalg.no<http://www.autosalg.no>

24. sep. 2017 kl. 16:18 skrev Ghostkeeper <notifications@github.com<mailto:notifications@github.com>>:


Strange. Just to be sure, you did activate the check marks for the Helpers, Shell and Infill in the layer view panel, didn't you? ?

You could try upgrading your graphics drivers. The intended rendering requires OpenGL 4.1.

Or you could set Cura's rendering to legacy mode: Go to Preferences -> Configure Cura... -> Force layer view compatibility mode (restart required). This will disable the fancy 3D tubes in Layer View, but at the paths should become visible again. The compatibility mode only requires OpenGL 2.0.

-

**Comment by ianpaschal** [comment]
@Racingf3 Is this still an issue for you in the latest version (3.2.1)? Since it's possibly graphics card specific I can't test it myself before closing.
