### ISSUE TITLE
Cura 2.7: Reset Viewport in "Zoom / center to mouse location".

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2456]
Due to mouse resolution issue the viewport went crazy and the built plate got lost from screen. i could not get it back to view other than to kill and restart Cura.

**Steps to Reproduce**
Set Zoom to mouse location  - checked, and play with zoom till Built plate disappears.
 
**Actual Results**
A way to reset view - i might missed this option . could not find it in GUI nor in right click menu.

**Expected results**
Reset view button.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/pull/2439

**Comment by Thisismydigitalself** [comment]
Cool!

**Comment by fieldOfView** [comment]
This can be closed now that #2439 is merged

**Comment by nallath** [comment]
It was a bit too late for next release (it has a string, so it will only be in the release after the next). Sorry about that.

**Comment by CoreyBurger** [comment]
Can we reopen this? I've ended up with a view I cannot reset and the "Reset View" option in #2439 seems to have vanished in 5.1.1
