### ISSUE TITLE
SidebarSimple sliders are not DPI aware on Windows

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#2457]
The new sliders on the Recommended tab render inconsistent on scaled displays (eg Hi DPI screens):
![image](https://user-images.githubusercontent.com/143551/30596632-fe0888d6-9d54-11e7-85df-f0ae8a8bb2fe.png)

* The layer height texts are much too small on the top slider
* The marker dots are much smaller than on 100% scaled displays on the top slider
* The bottom slider is not wide enough
* There's an inconsistency between the linewidts of the two sliders

Steps to reproduce:
In "Display settings" (context menu on the desktop), set the "Change the size of text, apps and other items" setting to anything but 100%
Restart Cura

Other things to note: splash-screen alignment is broken as well, and many dialogs and margins in dialogs are too small.

**Comment by nallath** [comment]
I've added your remarks to the issue regarding the slider.

**Comment by Appesteijn** [comment]
This should be fixed with the latest changes to the sidebar

**Comment by ChrisTerBeke** [comment]
Fixed by today's changes to DPI calculation.
