### ISSUE TITLE
Cut objects

### ISSUE THREAD

**Issue by leobel96** [Ultimaker/Cura#2472]
Please add the possibility to cut objects such as in slic3r

**Comment by nallath** [comment]
I'll have a look as to how slic3r does it.

**Comment by leobel96** [comment]
Perfect, thank you!!!

**Comment by leobel96** [comment]
@nallath or maybe here https://github.com/kennethjiang/OctoPrint-Slicer/issues/133

**Comment by leobel96** [comment]
And here https://github.com/kennethjiang/3tk/pull/5

**Comment by nallath** [comment]
The one made by aleph objects seems to be a bit dead in the water.

**Comment by nickthetait** [comment]
You mean non-fuctional or hasn't been updated in a while?

**Comment by nallath** [comment]
A bit of both; It cuts the object but then it doesn't fill up the area that it cut, leaving you with an unprintable model. 
It's not the cutting that's hard, its the cutting and then ending up with two printable objects that is hard.

**Comment by eyal0** [comment]
@nallath If it's useful for you, you can check my latest progress on https://github.com/kennethjiang/OctoPrint-Slicer/issues/135 .  I am able to cut the object and also fill the remaining hole pretty well!
