### ISSUE TITLE
Printing Speeds

### ISSUE THREAD

**Issue by jasonprovencher** [Ultimaker/Cura#2473]
I am having issues with speeds in cura 2.7.0 on Mac. If you look at the screen shot, my speeds are pretty normal. As soon as it start printing, it appears that it goes faster over time AND not honoring the initial layer speed etc.

Am I missing a setting or is there a bug?

<img width="423" alt="screen shot 2017-09-23 at 1 37 54 pm" src="https://user-images.githubusercontent.com/6002495/30776931-72579b5c-a064-11e7-9059-52ccc2a1462f.png">

**Comment by smartavionics** [comment]
Check that you have number of slow layers > 0.

**Comment by jasonprovencher** [comment]
This setting is @ 2. Is there a setting that will accelerate the speed over time? All of my other settings are default.

**Comment by smartavionics** [comment]
Not as far as I know. Could you please post a link to the gcode so that I can take a look at it?
