### ISSUE TITLE
Cura 2.7 100% infill always ZigZag

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#2475]
If you set 100% infill pattern is always ZigZag.
Printing 2020 extrusion wheels with 100% infill and want to use Concentric infill...

**Comment by smartavionics** [comment]
That's because 100% infill is treated as skin - try setting it to 99% (or setting skin pattern to concentric).

**Comment by kr15uk** [comment]
Thanks for the reply. 99% it is. Can't find where I can set skin pattern though.

**Comment by smartavionics** [comment]
Hi. It's a Shell setting "Top/Bottom Pattern".
