### ISSUE TITLE
Cura-2.7 couldn't start CuraEngine

### ISSUE THREAD

**Issue by MacroHu** [Ultimaker/Cura#2477]
Did someone met this problem, CuraEngine no run while silcing, I can't slice model.

Console info:
----------------------------------------------
- DEBUG - UM.Backend.Backend._logSocketState [174]: Socket state changed to Listening
2017-09-25 10:08:46,166 
- ERROR - UM.Backend.Backend._runEngineProcess [144]: Couldn't start back-end: No permission to execute process.
----------------------------------------------

Version info:
--------------------------
Cura: 2.7
CuraEngine: 2.7
Uranium: 2.7
Cura-build-environment: 2.7.0
--------------------------
System: Ubuntu-16.04 , IDE: Eclipse

How to fix it ?

**Comment by nallath** [comment]
Uh, give it the permission that it needs?
