### ISSUE TITLE
master branch - infill density changes value from X to X.0 on profile load

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#2482]
I expect this is just a transient glitch but with the current master branch when you change to a different profile, the infill density changes from an integer value to the same value with .0 appended and so the profile becomes "dirty".

**Comment by Ghostkeeper** [comment]
Yeah, we found this too. It actually sets it to the nearest multiple of 10% by the looks of it. I think it's the infill slider causing this.

**Comment by ChrisTerBeke** [comment]
To be fixed by https://github.com/Ultimaker/Cura/pull/2498.
