### ISSUE TITLE
When there is only 1 quality, Recommended mode always shows "slower"

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#2485]
With the new quality selection slider, if there is only a single available quality, the slider is always showing a "Slower" print speed. This will not look great when the user picks a 0.8mm nozzle for their Ultimaker 2+ (you would think that a 0.8mm slice at 0.2mm layer height is not "slow").

From a UX perspective, it would be better if the disabled "nub" that is visible when there is only a single layerheight is in the center (neither slower nor faster).

![image](https://user-images.githubusercontent.com/143551/30865285-7077dcc4-a2d6-11e7-9c06-2cfeae58fe3a.png)

**Comment by nallath** [comment]
Put it in our current sprint; CURA-4383

**Comment by Appesteijn** [comment]
Just discussed this and it might be to difficult with the Qt slider (especially before the 3.0 launch)

**Comment by fieldOfView** [comment]
FTFY

**Comment by ChrisTerBeke** [comment]
Noice, reviewing right now

**Comment by ChrisTerBeke** [comment]
There's an issue where if you change the material of the extruder back to something that 'unlocks' more values on the slider, the value doesn't update and the slider handle is in the middle between 2 tick marks (for example: PVA + PVA -> ABS + PVA).

**Comment by ChrisTerBeke** [comment]
Closing now that issue has been picked up internally and has a PR.
