### ISSUE TITLE
Infill icon looks like a control

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#2487]
The new infill slider has a icon that visualizes the current setting. This indicator looks very much like the checkbox control. It affords clicking on.

![image](https://user-images.githubusercontent.com/143551/30868415-d85885e8-a2de-11e7-90e3-1bda6267f634.png)

Suggestion: make the outline of that indicator box a light shade of gray, so that it at least looks disabled. Note that the graphic in the box was recently toned down (for the same reason as this issue?), but since the checkmark in a checkbox is also shown in a grey tone, that did not help.

**Comment by ChrisTerBeke** [comment]
Agreed, fixed in 3ddb45160d47d5c458619c6f5113f0e40b13fa05.
