### ISSUE TITLE
Opening multiple STL models in a row does not update the model name for saving

### ISSUE THREAD

**Issue by yourhead** [Ultimaker/Cura#2491]
The bug is that when you open up several models in a row. Then export the produced gcode of each model Cura provides a suggested name for the gcode file based on the original STL file of the model. The expectation is that the suggested name would be based on the most STL you are actually exporting -- but it is not. Instead it's based on the very first STL filename. It doesn't update as you open more STLs.

Like this:

- Open "Model_File_A.stl"
- Slice
- Save to File

The suggested name is "Model_File_A.gcode"  👍

Then:

- Open "Model_File_B.stl"
- Slice
- Save to File

The suggested name is "Model_File_A.gcode" 👎🐞

**Comment by ChrisTerBeke** [comment]
Hi @yourhead,

This issue has already been taken care of and will be fixed in the next release.
