### ISSUE TITLE
"Discard or Keep Changes" dialog shown when switching to a printer

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#2499]
When switching to a printer, Cura should just load the previously selected Quality, Quality Changes and User profiles. When switching to a printer (with specific set of profiles?) it currently asks the user to Discard or Keep changes.

Steps to reproduce:
* Have two printers in Cura, one of which an UM2+
* In the UM2+, select PLA, 0.8mm nozzle
* Change eg Wall Thickness to 1.11
* Switch to other printer
* Switch back to the UM2+ with the 1.11 Wall Thickness

Expected result:
Just switch back to the printer
Actual result:
"Discard or Keep changes" pops up

**Comment by nallath** [comment]
Good find, it was part of a regression; The progress slider triggered an extra setActiveQuality
