### ISSUE TITLE
The splash window looks pixelated on retina displays

### ISSUE THREAD

**Issue by yourhead** [Ultimaker/Cura#2504]
Everything just looks scaled up and blurry/pixelated. If there is an @2x resource for this window it's not being used. If there isn't one, maybe there should be.  😃 

<img width="199" alt="pasted_image_9_27_17__3_38_pm" src="https://user-images.githubusercontent.com/98634/30937903-db243c80-a39d-11e7-8883-4bbc9ad2e351.png">

**Comment by fieldOfView** [comment]
In Cura 3.0, the splash-screen renders at the native pixel size. It will be small, but it won't look pixelated.

**Comment by ChrisTerBeke** [comment]
Closing because of 3.0 splash screen re-design.
