### ISSUE TITLE
Allow Import/Export of Machine Profiles

### ISSUE THREAD

**Issue by jed-frey** [Ultimaker/Cura#2519]
I have a Creality CR-10 and the instructions for adding it to Cura 2.x on Windows mean digging around in the folder internals and dropping a profile in there.

Doing the same thing on Linux is a major PITA because of AppImage and not a set of instructions I would give to a newbie.

Allow Import/Export of Machine profiles similar to how material profiles can be imported & exported.

**Comment by nallath** [comment]
It's not the best solution, but loading from project should also load the machine.

**Comment by fieldOfView** [comment]
Note that it is not necessary to put the definition files in the application resources. You can already put them in the same folders inside the configuration folder (~/.local/shared/cura/2.7 or something like that)

**Comment by jackha** [comment]
Creality CR-10 support is now bundled with Cura.

**Comment by fieldOfView** [comment]
Chances of Ultimaker putting development effort/time into this are slim to none. It could be implemented as a plugin.
