### ISSUE TITLE
all cura versions: rotating model changes slicing

### ISSUE THREAD

**Issue by jeroensomers** [Ultimaker/Cura#2520]
When I rotate my model the slicer is filling up holes in my STL that is not good.

Example Cura 2.7.0
![afbeelding](https://user-images.githubusercontent.com/7030107/31019843-5f4db434-a531-11e7-84f6-1827b6e0cbe5.png)
You can clearly see that the letters are sliced correctly.
![afbeelding](https://user-images.githubusercontent.com/7030107/31019868-7408a6e0-a531-11e7-8f74-166e7905085d.png)
Now I rotate the model 90 degrees
![afbeelding](https://user-images.githubusercontent.com/7030107/31019944-b367ac14-a531-11e7-951c-ac0f77d71e56.png)
The letters are gone
![afbeelding](https://user-images.githubusercontent.com/7030107/31019966-c7b965d6-a531-11e7-8501-22cfea2be37e.png)

Example Cura 15.04.6
![afbeelding](https://user-images.githubusercontent.com/7030107/31019553-50cbba2e-a530-11e7-8530-5c6c8fa52be9.png)
You can clearly see that the letters are sliced correctly.
![afbeelding](https://user-images.githubusercontent.com/7030107/31019569-63d81c8e-a530-11e7-8095-85eab0cb5f65.png)
Now I rotate the model 90 degrees
![afbeelding](https://user-images.githubusercontent.com/7030107/31019609-8e6512a4-a530-11e7-9162-048a5394345d.png)
The letters are gone
![afbeelding](https://user-images.githubusercontent.com/7030107/31019678-bff3d260-a530-11e7-88a8-6f16fd14e7a9.png)

The model is made in sketchup
I added the model that I usesd for this.
[Fem sleutelhanger.zip](https://github.com/Ultimaker/Cura/files/1344633/Fem.sleutelhanger.zip)

**Comment by fieldOfView** [comment]
Sketchup has a tendency to create 3d models that are unsuitable for 3d printing. They need to be "repaired".

What you could try (but no guarantees) is to use the "Search" in the Advanced sidebar to look for the "Union Overlapping Volumes" setting and turn it off.

**Comment by jeroensomers** [comment]
Damnn, that was a very quick fix.

Thnx for the help!
