### ISSUE TITLE
anet a8 usb ubuntu or linux not found.

### ISSUE THREAD

**Issue by teclauin** [Ultimaker/Cura#2524]
I can not find the way to make the anet a8 work by usb from linux

**Comment by ChrisTerBeke** [comment]
The printers from Anet have a lot of issues regarding USB (built one myself, had to manually install serial drivers to make it work). Please have a look at this thread abut Anet USB drivers: https://www.thingiverse.com/groups/anet-a8-prusa-i3/topic:11548.
