### ISSUE TITLE
2.7 Model features vanish depending on orientation

### ISSUE THREAD

**Issue by davebelleville** [Ultimaker/Cura#2529]
Changing the orientation (or not) will cause entire areas not to be printed. For instance, if this model is oriented on its side, you see the internal features. Placed vertical, all internal features vanish.

[EZ_BULB.zip](https://github.com/Ultimaker/Cura/files/1346963/EZ_BULB.zip)

**Comment by smartavionics** [comment]
Freecad says your model has problems...

![screenshot_2017-10-01_09-16-07](https://user-images.githubusercontent.com/585618/31052932-3c832304-a689-11e7-9a95-43a59a6422f6.png)

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/issues/2520

**Comment by Thisismydigitalself** [comment]
Same here. I was trying to check your stl just to find out it has problems.

**Comment by davebelleville** [comment]
I corrected the normals and it is fine now.

**Comment by smartavionics** [comment]
Great, please close the issue.
