### ISSUE TITLE
Dialogs display "Yes" / "No" buttons instead of actions

### ISSUE THREAD

**Issue by thinkyhead** [Ultimaker/Cura#2532]
Human interface guidelines for OS applications have long stressed that you should avoid using generic buttons like "Yes" and "No" in dialogs that ask for a user response. Instead, dialogs should use buttons that express the precise actions that will be performed.

Notice how this dialog shows "Cancel" and "Replace" buttons:

![image](https://user-images.githubusercontent.com/698003/31059198-f327204c-a6c5-11e7-87fd-c4f4f98acf09.png)

This makes it easier to recognize the dialog and allows the user to proceed without feeling the need to read the dialog text first to figure out which one it is.

I'd submit the change as a PR, but I'm just getting familiar with the codebase and have to focus on another project today. If this lingers a while, I will see about submitting a PR.

**Comment by nallath** [comment]
Pull requests are of course always welcome, but i've notified our UX team in the meantime.

**Comment by Ghostkeeper** [comment]
We do a lot of "OK" and "Cancel", but we never actually have "Yes" and "No".

**Comment by ianpaschal** [comment]
I've just scanned through with the search and I can't find any cases of this. Considering this is also a pretty old issue I think it's safe to consider it fixed.

**Comment by LukeChen-Ultimaker** [comment]
button that states for "action" is a common way to make user clear what to do and to some extend shows the meaning of that action. @thinkyhead do you have any concrete examples (screenshots) that we can look into? I guess reviewing strings of all buttons is unavoidable to get a better and coherent user experience.

**Comment by fieldOfView** [comment]
Note that it is not always as simple as replacing a string. Qt - the UI framework we use - has standard dialogs with Yes/No options. Creating a dialog with custom buttons is more work, and it is actually harder to make these look like system-native dialogs.

**Comment by thinkyhead** [comment]
> Qt - the UI framework we use - has standard dialogs with Yes/No options. Creating a dialog with custom buttons is more work, and it is actually harder to make these look like system-native dialogs.

Indeed! I set out to do this myself, examined the code that uses standard "yes/no" dialogs and compared them to the more involved dialogs that would require more work. Not being well-versed in Qt, I didn't get too far and left it for someone with more Qt savvy.

I think it will be worth the effort in the long run to eschew the Qt-standard "yes/no" dialogs altogether and implement an improved [cancel] [action] dialog function that does its best to emulate the dialog layout appropriate to the platform it's running on.
