### ISSUE TITLE
Cura cant resume after Pause

### ISSUE THREAD

**Issue by SacrilAI** [Ultimaker/Cura#2533]
i was needing to change the filament, so i paused, then when i try to resume, i dont work, im using Cura 2.7

**Comment by nallath** [comment]
Resuming over USB? Network? On the printer? What printer?

**Comment by SacrilAI** [comment]
USB, my printer is Anet A8

**Comment by Ghostkeeper** [comment]
I just tried pause and resume on an Ultimaker 2+. Works fine.

To implement the pause, Cura just stops sending normal commands but periodically requests the temperature (every 2 seconds I think) to keep the connection alive.

**Comment by sadigov** [comment]
I had the same issue with UItimaker 2+ today. It looks like the printer's CPU/memory got overwhelmed, took a long time to resume, and when it resumed, it started with the wrong Z-axis height, by about 5mm, bumped into the build and melted part of it. I have restarted the print from scratch.

**Comment by ianpaschal** [comment]
Needs more info for reproducibility but did not receive it. Closing.
