### ISSUE TITLE
Cura 2.6.1 fails to slice

### ISSUE THREAD

**Issue by jpathuber** [Ultimaker/Cura#2547]
I used the standard ppa (ppa:thopiekar/cura) to install Cura, which has been fine for months.  Now I'm getting a failure similar to the person using the latest build, but with a different error in cura.log:

DEBUG - UM.Backend.Backend._backendLog [90]: [Backend] [ERROR] Trying to retrieve unregistered setting with no value given: 'xy_offset_layer_0'

This started today, all was well last Friday. Cura says it's slicing but then never gets to saving the file. Should I build it myself from github or what? BTW, I can pull in an stl file, muck about with it and save as .3mf no problem.

**Comment by hogerson** [comment]
I have same problem. Was away some days, came home last Friday start up and not slice.
Works in windows on same computer

**Comment by thopiekar** [comment]
Thanks @nallath , the reason is that the PPA is blocked by this: https://github.com/Ultimaker/Uranium/issues/286

**Comment by thopiekar** [comment]
@jpathuber @hogerson Build of Uranium has passed now.. Cura 2.7.0 is on the way..

**Comment by hogerson** [comment]
Thanks, After last update total crash

**Comment by thopiekar** [comment]
@jpathuber Yeah, sorry for this! 😞

**Comment by jpathuber** [comment]
No worries, I understand stuff happens. It's a great program and I'm looking forward to the fix!

**Comment by gummybearoz** [comment]
2.7.0 fails to slice less i force infill to different % then back to what it was when cura open up last 
in last 3 days you have wrecked this program

**Comment by ChrisTerBeke** [comment]
2.7.0 was released quite a while ago, so nothing in the last 3 days changed there...

**Comment by jpathuber** [comment]
Okey-dokey let's just say AppImage is the way and close this out.....

**Comment by maukcc** [comment]
Please re-open this until there is a solution.

**Comment by jpathuber** [comment]
Re-opening at maukcc's reasonable request. Although, now it is a problem with 2.7.0 and not 2.6.1 so I'm not sure whether that's right. Also the symptoms are different - it crashes. Votes?

**Comment by nallath** [comment]
I'd prefer it if people don't re-use issues. It makes it bloody hard for us to figure out why something is still open.

As for doing development; The best way to do that is to run it from source. If you only want to change profiles, you don't really need this. If you need help setting it up on source, send us a message. I'm sure we can work something out.

**Comment by maukcc** [comment]
@nallath : thanks for the offer to help us setting it up from source. That would be wonderful.
We are both in the Netherlands? Maybe we should have a meeting sometime.

**Comment by Ghostkeeper** [comment]
Try me over at r.dulek at ultimaker com (or any of the other e-mail addresses that I sign my commits off with).
