### ISSUE TITLE
time estimate

### ISSUE THREAD

**Issue by mypeopoly** [Ultimaker/Cura#2548]
Hi Cura team,

We would like to learn what part of Cura should we look at if the print estimated time is off?  We are using Cura to slice for Moai, a SLA printer and the laser movement speed is about 4 times of the print speed set in Cura.  Obviously, the print time would be off and we like to adjust that. What is a good place to start looking? 

![image](https://user-images.githubusercontent.com/22469610/31102294-4873e2ae-a786-11e7-9ae2-121ef8181719.png)

**Comment by nallath** [comment]
I think that using the right print speeds & acceleration in Cura should do the trick.

**Comment by mypeopoly** [comment]
@nallath 

thanks for the quick reply.  It won't because the firmware interprets the print speed different.  the actual laser spot speed movement is about 4 times of the print speed parameters.

**Comment by nallath** [comment]
Then there is little you can do about this.

**Comment by mypeopoly** [comment]
can I times the print speed by 4 in the code where it does the estimated time calculation?

**Comment by nallath** [comment]
Yes, but it will be a pretty nasty hack to do it like that (as changing it on that spot will break the code for all other machines). I think it's better to not have a machine that interprets speed differently.

**Comment by mypeopoly** [comment]
@nallath  we have a forked version just for Moai. Perhaps we will just mod that one for now and let the users know about the changes.   In the long run, we like to update the firmware back to interpret the value as it is.

**Comment by nallath** [comment]
Ah, in that case; Have a look at the PrintInformation.py file; That's where the frontend receives / distributes the print times.

**Comment by fieldOfView** [comment]
A "if moai then divideSpeed" (pseudocode, if you hadn't guessed) will make sure it does not break other printers too hard.

**Comment by fieldOfView** [comment]
A clean(ish) way to do this without affecting other printers by the way would be to add a custom setting (eg "moai_speed_multiplier") to your definition file, and set the value (eg to "4"). Then in PrintInformation.py check for the existence of that setting and use its value. 

I do similar stuff for BlackBelt. 
Adding a custom setting: https://github.com/fieldOfView/Cura/blob/blackbelt/resources/definitions/blackbelt.def.json#L30
Using the custom setting: https://github.com/fieldOfView/Cura/blob/blackbelt/plugins/BlackBeltPlugin/BlackBeltPlugin.py#L108

**Comment by mypeopoly** [comment]
thanks guys. will test and revert
