### ISSUE TITLE
v2.7 my drive keeps being read

### ISSUE THREAD

**Issue by ns78** [Ultimaker/Cura#2549]
Hello. May you please fix this bug where the A drive keeps being read over and over and over again until I exit the program. Why is it reading my drive? Yes I still have and use a floppy (3.5") drive. Old habits are hard to die off. 

Thanks

**Comment by ChrisTerBeke** [comment]
It seems this issue is related to https://github.com/Ultimaker/Cura/issues/2438.

**Comment by nallath** [comment]
Yup. It's a duplicate.
