### ISSUE TITLE
Cannot view buildplate when opening a .stl file

### ISSUE THREAD

**Issue by jamietaylor13** [Ultimaker/Cura#255]
When i open a .stl the build plate disappears and i can't seem to get it back even in layer view. The program is still slicing well but i cant see anything.

I'm running it on OSX 10.10.4 on MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by daid** [comment]
This is a bug in the specific 3D driver used by OSX. The problem is fixed in Cura for the next Cura release.
