### ISSUE TITLE
View Zoom, Pan, etc

### ISSUE THREAD

**Issue by UltimateSports** [Ultimaker/Cura#2552]
Can we please have an option to select that the center of the build plate is kept central in the window so zoom, pan, tilt are all around the center of the build plate, rather than being able to zoom and then suddenly the build plate is dissapeared never to be seen again!

**Comment by Thisismydigitalself** [comment]
https://github.com/Ultimaker/Cura/pull/2439

**Comment by nallath** [comment]
Zoom & tilt are around the center of the build plate by default. If you pan, the only way to do this is to move the center.
