### ISSUE TITLE
cura 2.7.0 stl file not loading, using Windows8

### ISSUE THREAD

**Issue by dadmezz** [Ultimaker/Cura#2554]
new to 3d....file from thingivers selected (tried couple different files-stl or gcode) to open, then goes to Cura screen but nothing but x/y/z arrows showing on center of plate...any suggestions would be appreciated.
1. found by clicking stl file it opens Cura and loads the file.
2. double checked the suggestions about size...zoomed out but didn't find image...did find that sometimes I could get images to reload after clicking file name to load in Cura then could load them again using the file, recent open selection....thanks for the suggestions,

**Comment by smartavionics** [comment]
Have you tried zooming out? If the object is too big to fit on the build plate it will be placed outside of that area and you can't see it unless you zoom out.

**Comment by ChrisTerBeke** [comment]
There is a preference that re-scales models that are too large. You can try enabling this preference and see if the model then appears for you.

**Comment by ChrisTerBeke** [comment]
Did my suggestion work out for you?
