### ISSUE TITLE
Q A Z W shortcuts

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#2556]
Very handy but It seems these works only when we click on these manipulation's icons on the left side panels. if we click on bed, than select the model these Q A Z W do not work anymore. there is a need to highlight the model with mouse than click again on the manipulation's icons on the left side panels for these to work again.

**Comment by Ghostkeeper** [comment]
This issue doesn't reproduce on my computer. I can click the bed (everything unselects), then select a model and immediately push Q, A, Z or W and the appropriate tools activate.

**Comment by nallath** [comment]
Could you provide a bit more information about your system (operating system, graphics card, etc)?

**Comment by Thisismydigitalself** [comment]
Following your reply I ran some tests and managed to reproduce this and so it looks like a bug. 
running cura 2.7 on win10/64/nvidia i750. stay tuned. will shortly let you know what invokes this behavior.

**Comment by Thisismydigitalself** [comment]
- Start cura 2.7
- Load STL
- Touch built plate > model > Shortcuts = all is well.
- Touch built plate > model > Side panel manipulators > Shortcuts = not working anymore and need to restart cura to regain functionality.

**Comment by Thisismydigitalself** [comment]
Just checked with Cura 3.0 - same.
looks like a bug in both 2.7 and 3.0

**Comment by Drayson80** [comment]
in addition (sorry for adding it here) - is there a way to modify the choosen letters? just asking because on a german keyboard, z and y are changed... :-)

**Comment by Ghostkeeper** [comment]
> Start cura 2.7 or 3.0 and load STL
>
>- Touch built plate > model > Shortcuts = all is well.
>- Touch built plate > model > Side panel manipulators > Touch built plate > model  = not working anymore and need to restart cura to regain functionality. 

It still doesn't reproduce on my end. Using Windows 8.1, Cura version 3.0.3 (so 64-bit). NVIDIA GeForce GTX 560, but that probably wouldn't matter for this sort of thing.

We're considering making those shortcuts configurable. You're not the first to request it: https://github.com/Ultimaker/Cura/issues/2523

**Comment by Thisismydigitalself** [comment]
Same issue with 3.1.
Shortcuts wont work if you first click on print bed then select the object  - in this case shortcuts will not work. for the shortcuts to work one must first click on the manipulation icons on the left, then select the object(s) - only then shortcuts works for me.

**Comment by Ghostkeeper** [comment]
Still not reproducing. To be clear, this is what I'm doing precisely:

* Start Cura.
* Load a model by going into File -> Open Recent -> Cube1cm.stl.
* Click the build plate.
* Click the cube.
* Press the A button.

**Comment by Thisismydigitalself** [comment]
Please follow my instructions to the letter - just tried it with Cura 3.1Beta and the bug is still there:

Touch built plate > model > **Left Side panel manipulators** > Touch built plate > model = not working

**Comment by Ghostkeeper** [comment]
Ah, yes sorry, I didn't read that properly.

* Start Cura.
* Load model by going into File -> Open Recent -> Cube1cm.stl.
* Click the build plate.
* Click the cube.
* Click on "Scale" button.
* Click the build plate (stuff deselects).
* Click the cube.
* Press the Q button.

Then it reproduces.

**Comment by Ghostkeeper** [comment]
As a workaround, you can get it to work again by clicking any setting field and then the build plate. It seems to be related to focus. Something swallows those key presses.

**Comment by Ghostkeeper** [comment]
Our project manager removed this from our planning. We won't be able to get around to fixing this soon.
