### ISSUE TITLE
Cura 2.7.0 slicer failure

### ISSUE THREAD

**Issue by JPN3D** [Ultimaker/Cura#2559]
Hi,

I have this object which print out nicely with Cura 2.6.2 but 2.7.0 invents the fillings inside area. The most odd thing is that the extra artifacts depends on the position of the object (Win10-64).
[kaiutinjalusta.zip](https://github.com/Ultimaker/Cura/files/1360319/kaiutinjalusta.zip)

**Comment by Ghostkeeper** [comment]
I don't know why there's a difference between 2.6.2 and 2.7.0, but I do know why you're seeing strange infill. Here's X-ray view of your model:
![image](https://user-images.githubusercontent.com/2448634/31586160-a6db0470-b1cd-11e7-8763-441819e3074b.png)

Your model has double walls in some places. With some walls being double, it's ambiguous what the inside of the model is and what the outside is. You can try repairing your model using an application such as Meshlab.
