### ISSUE TITLE
No "Move" Button Cura 2.7.0

### ISSUE THREAD

**Issue by cool-junk** [Ultimaker/Cura#2569]
There is no "move" button on my Cura 2.7.0 
This is really driving me crazy. I have searched everywhere and can't find a solution for this. I even uninstalled and reinstalled to no avail..... Still no "Move" Button...... 
I have no way to move things on the build bed.
See image for reference.

![2017-10-09_203650](https://user-images.githubusercontent.com/32659389/31365575-a7416d64-ad31-11e7-94a3-5af7999d278a.png)

**Comment by smartavionics** [comment]
The move buttons doesn't become active until one or more objects are selected. That object on the build plate doesn't have a blue outline so it isn't selected?  What happens when you click on the object?

**Comment by ChrisTerBeke** [comment]
Mm that button should definitely be there. Seems like the plugin that exposes it didn't properly load. Can you post some logs here? Information on how to find the logs can be found at https://github.com/Ultimaker/Cura#logging-issues.

**Comment by ChrisTerBeke** [comment]
@smartavionics The button would indeed not be activated, but it should still be listed in the toolbar at all times.

**Comment by smartavionics** [comment]
> @smartavionics The button would indeed not be activated, but it should still be listed in the toolbar at all times.

Where does it get listed? I can't find it other than on the LHS?

**Comment by smartavionics** [comment]
Sorry, it's too early here, please ignore my above comments!

**Comment by nallath** [comment]
Could you share logs? If the tool can't be loaded, it should be clear from the logs.

**Comment by cool-junk** [comment]
Thanks for the replies fellas. I will get the logs and post them this evening when I get home from work.

**Comment by cool-junk** [comment]
Here is my Log file. 

[cura.log](https://github.com/Ultimaker/Cura/files/1373851/cura.log)

**Comment by cool-junk** [comment]
I noticed that the Logs go back way before I tried to reinstall that last time. I just uninstalled and manually cleaned out the app data etc... I am re-downloading it not and will post my results after this install. Fingers Crossed......

**Comment by cool-junk** [comment]
Okay, my issue is now resolved. 
1st: I uninstalled Cura through "uninstall programs" on Windows. 
2nd: I did a search for "Cura" in windows explorer and manually deleted any associated files I could find. 
3rd: I downloaded and reinstalled Cura from the website.
All Fixed!

**Comment by ChrisTerBeke** [comment]
The logs contain the following line:

2017-08-06 12:45:57,433 - DEBUG - UM.PluginRegistry.loadPlugin [148]: Plugin TranslateTool was disabled

This means that the move tool plugin was disabled somehow, which is weird because it's a required plugin.

**Comment by fieldOfView** [comment]
It is possible to (accidentally) disable required plugins by clicking their names. Fixed in https://github.com/Ultimaker/Uranium/pull/294

**Comment by ChrisTerBeke** [comment]
Nice catch!
