### ISSUE TITLE
Skirt or Brim not going around object base completely

### ISSUE THREAD

**Issue by chuffpdx** [Ultimaker/Cura#2570]
Load "Creepy_Hand" object at the following:
https://www.thingiverse.com/thing:1524972

Set brim or skirt and notice it cuts through middle of object and not around base completely. 

I was able to confirm this in v2.7 and v2.6.1

**Comment by smartavionics** [comment]
The bottom of the model isn't flat, just lower it into the build plate a little like this:

![screenshot_2017-10-10_06-22-57](https://user-images.githubusercontent.com/585618/31370541-8be356b6-ad83-11e7-8c11-138cd4c4a79b.png)

**Comment by Thisismydigitalself** [comment]
hmm.. was that a sneak peek teaser of Cura 3.0 built plate?..

**Comment by fieldOfView** [comment]
It is no secret, there are more screenshots of the new UI to be found around here

**Comment by smartavionics** [comment]
And you can see it for yourself if you install the beta 3.0 which has been announced today.

**Comment by Thisismydigitalself** [comment]
> And you can see it for yourself if you install the beta 3.0 which has been announced today.
Wow, - I must have been asleep 👍 
I can only see the announcement. no file to download.

**Comment by smartavionics** [comment]
Yes, you're asleep because the link is in the posting!

http://software.ultimaker.com/Cura_open_beta/

**Comment by chuffpdx** [comment]
My mistake, thank you.  I rotated -1 degree and it skirted properly.
