### ISSUE TITLE
Please include x3d MIME type in desktop file

### ISSUE THREAD

**Issue by petterreinholdtsen** [Ultimaker/Cura#2571]
Cura is able to load x3d files, but do not announce this in its desktop file, making the Linux GUI file browsers fail to suggest Cura as an alternative for opening x3d files.  Please add model/x3d+xml to the list of supported MIME types, for example like this:

```
diff --git a/cura.desktop.in b/cura.desktop.in
index ceb5c99..fb9e5bf 100644
--- a/cura.desktop.in
+++ b/cura.desktop.in
@@ -11,6 +11,6 @@ TryExec=@CMAKE_INSTALL_FULL_BINDIR@/cura
 Icon=@CMAKE_INSTALL_FULL_DATADIR@/cura/resources/images/cura-icon.png
 Terminal=false
 Type=Application
-MimeType=application/sla;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;image/bmp;image/gif;image/jpeg;image/png
+MimeType=application/sla;application/vnd.ms-3mfdocument;application/prs.wavefront-obj;image/bmp;image/gif;image/jpeg;image/png;model/x3d+xml
 Categories=Graphics;
 Keywords=3D;Printing;
```

**Comment by thopiekar** [comment]
@petterreinholdtsen You can easily edit the file in your browser and send us an pull request with your change.
Just go to the file: https://github.com/Ultimaker/Cura/blob/master/cura.desktop.in
Click on the edit button, make the change, add some comments and send the change to us 😃
