### ISSUE TITLE
prints 1st layer only 1/2 then full on 2nd layer

### ISSUE THREAD

**Issue by gummybearoz** [Ultimaker/Cura#2577]
prints 1st layer only 1/2 then full on 2nd layer
![screenshot 10](https://user-images.githubusercontent.com/32675984/31389446-cb9e45f6-ae1c-11e7-9519-ad5ae3518f7f.png)
![screenshot 11](https://user-images.githubusercontent.com/32675984/31389485-df56ffca-ae1c-11e7-9424-6ce3adfad0f2.png)

**Comment by ChrisTerBeke** [comment]
Seems like the bottom surface of your model is not entirely flat (or angled).

**Comment by gummybearoz** [comment]
iv seen this comment on many other posts 
is this your go to cut past 
im not this silly 
iv done that test and cut a clean face then lowered it to 0-zero so this dis prooves the its not flat argument

**Comment by DDDirk** [comment]
In Cura, did you do 'lay flat' (click the rotate-icon on the left, then the lay flat-icon)?
If that solves it, it may get printed at a (slight) angle, so it might be better to correct it in the model (make the surface completely horizontal).

**Comment by ChrisTerBeke** [comment]
If you post the model here I can double check for you, but it's not the first time I've seen an issue with screenshots like these....

**Comment by gummybearoz** [comment]
https://www.tinkercad.com/things/8BnQ6lkCTKD-9lay-flat-

**Comment by ChrisTerBeke** [comment]
You have a link that doesn't force me to create an AutoDesk account?

**Comment by gummybearoz** [comment]
In Cura, did you do 'lay flat' (click the rotate-icon on the left, then the lay flat-icon)?If that solves it, it may get printed at a (slight) angle, so it might be better to correct it in the model (make the surface completely horizontal).
--


yes this worked but iv never had to lay flat before in last year of printing with cura 
thank you for the tip ill make it part of my must do before saving.
as said above iv cut a new face then lowered to zero so my model is flat.

**Comment by gummybearoz** [comment]
how to upload .stl didn't let me on making this post 
in zip?

**Comment by fieldOfView** [comment]
I have checked the STL from TinkerCAD. Sorry, the block with the cylinder, triangle and square subtracted from it does _not_ have a flat bottom. The bottom two vertices on the front are .405 units (mm) higher than the other vertices.

**Comment by gummybearoz** [comment]
![screenshot 12](https://user-images.githubusercontent.com/32675984/31390998-1930d280-ae21-11e7-81ee-56daed59f6ee.png)
wow im sorry for this mistake you make sence now its 1 am hear and uninstalled cura twice sorry for my rant 
apology from down under 
sorry
