### ISSUE TITLE
Unable to export 2 files from one session.  Requires shut down, reload, then save

### ISSUE THREAD

**Issue by Olive109** [Ultimaker/Cura#2580]
When a drawing is loaded, sliced, and exported to an external drive, CURA allows changes to the slicing but will not allow exporting of the new sliced part to the external drive.  The only fix i've found is to close the program, open it, start over.  VERY inefficient.  

Is there another fix?

**Comment by fieldOfView** [comment]
What version of Cura do you use?

**Comment by Olive109** [comment]
2.6.2

**Comment by fieldOfView** [comment]
Try Cura 2,7, or the Cura 3.0 beta that was released today.

**Comment by Olive109** [comment]
Ok – trying to download 7 now

**Comment by Olive109** [comment]
2.7 worked – I can save a second time to an external disc.

By the way, the update lists several great changes, but I’m not seeing them in my list of options when setting up a ‘custom’ print.  Things like Relative Z seam, Top surface skin, first layer line width, etc.  where do I go to activate or deactivate these functions?

Eric

**Comment by nallath** [comment]
Check the settings visibility. You can find it in preferences->settings

**Comment by Olive109** [comment]
Found it. Thank you.

From phone

On Oct 11, 2017, at 4:42 PM, Jaime van Kessel <notifications@github.com<mailto:notifications@github.com>> wrote:


Check the settings visibility. You can find it in preferences->settings
