### ISSUE TITLE
When Cura 2.7.0 is loaded it goes all black!

### ISSUE THREAD

**Issue by rjm01** [Ultimaker/Cura#2597]
Cura 2.7.0 has gone black on me. Removed the program from programs, reloaded a fresh copy of Cura and still see a complete y black screen with the usual Platform and task windows.
![cura with a black screen](https://user-images.githubusercontent.com/31594137/31508977-a968e22a-af34-11e7-98c8-c1726ab2429f.jpg). Please assist.

**Comment by nallath** [comment]
You loaded the dark theme. You can change it in preferences.

**Comment by rjm01** [comment]
Had not seen that tool since installing 7.0. Thanks
