### ISSUE TITLE
Typo in SidebarHeader.qml

### ISSUE THREAD

**Issue by TinkerGnome** [Ultimaker/Cura#2605]
just found a typographical error in [qml/SidebarHeader.sql](https://github.com/Ultimaker/Cura/blob/master/resources/qml/SidebarHeader.qml#L47) (line 47 - height vs. hieght)

**Comment by fieldOfView** [comment]
Good catch. I think that whole Item{} should be removed, since it would do the same as the Item{} above it if it had a non-0 height.
