### ISSUE TITLE
 Cura 3 Beta: Raft does not go to correct size when printing with supports

### ISSUE THREAD

**Issue by DubSidious** [Ultimaker/Cura#2615]
Just thought i'd let you know that im trying to print with a raft on the beta of cura 3, and the raft does not seem to go to the correct size, meaning part of the first layer would print in mid air.
![untitled](https://user-images.githubusercontent.com/32884114/31689386-2ae5e2e8-b387-11e7-9635-e7c7b6ef679b.png)

Picture attached to show what i mean. Not moaning in anyway, i know its a beta :) Just thought i'd let you guys know about the issue

Thanks for the software, and keep up the good work. Love using cura, have done since trying it on my first day of printing.

**Comment by Ghostkeeper** [comment]
Usually when this happens it turns out that the bottom of the model was not entirely flat at the bottom, or not laid flat properly.

**Comment by DubSidious** [comment]
Seems the problem went away with the release of the latest version.
And can assure you the bottoms of those objects were perfectly flat. Have printed this item with those stl's many times before.
