### ISSUE TITLE
Layer height slider missing 0.1

### ISSUE THREAD

**Issue by Chrankus** [Ultimaker/Cura#2620]
The layer height slider in recommended settings ranges from 0.06 to 0.6, but after 0.06 it says 0.2, then 0.15 0.2 again,0.4 and then 0.6. The 0.1mm option is missing from this slider.

![](https://i.gyazo.com/926eca9c37c7bce729e05c5fb10dae2f.png)

**Comment by Appesteijn** [comment]
What printer do you use?

**Comment by Chrankus** [comment]
I just loaded a standard profile for the Creality CR-10

**Comment by Appesteijn** [comment]
Something we missed. We fixed it and it will be in Cura 3.1 (or immediately if you run from source)

**Comment by Chrankus** [comment]
Cool, good job :)
