### ISSUE TITLE
Serious UI problem! 

### ISSUE THREAD

**Issue by 5N44P** [Ultimaker/Cura#2624]
Top menu bar is not showing (but it's clickable)
![image](https://user-images.githubusercontent.com/17505995/31742378-ab9e2c44-b457-11e7-889e-d161cf9cde62.png)

In add custom printer menu if i try to edit the Y param, the cursor appears on the X param
![image](https://user-images.githubusercontent.com/17505995/31742438-dd853afe-b457-11e7-8005-787bb92ac180.png)

It is unusable, and this problem shows at least since version 2.6.1
I've tried twice to reinstall 2.6.1, and now i'm on 3.0.3. And i always get the same issue. This is preventing users to use the software. 

If any additional information is required, please ask

**Comment by fieldOfView** [comment]
Duplicate of #2068
You have to either upgrade ir downgrade your GPU driver

**Comment by 5N44P** [comment]
Thank you
