### ISSUE TITLE
Cura 3 Mac OSX UI Glitch

### ISSUE THREAD

**Issue by Intoxinator** [Ultimaker/Cura#2630]
The print bed appears completely black when starting Cura on my Mac Mini. Models load fine, slicing works and have had successful prints. The print bed just does not appear with the grid.

Screenshot here: https://www.dropbox.com/s/f2o5hg8kiv70oi0/Screenshot%202017-10-19%2023.17.24.png?dl=0

**Comment by Intoxinator** [comment]
Cura 3.0.3
Mac OS 10.13
Mac Mini (Mid 2011) 
Intel HD Graphics 3000 512 MB

**Comment by ChrisTerBeke** [comment]
We've seen this happening with certain graphics cards. A fix was already made but not added to the 3.0 release. Not sure if there's gonna be an updated 3.0 release that contains a fix for this, otherwise it'll be fixed in 3.1.

**Comment by foreachthing** [comment]
Same with Windows 7 Pro and Quadro FX 3800 (341.92).

**Comment by fieldOfView** [comment]
Does it make sense to cherry-pick the fix to the 3.0 branch already, just in case there is a Cura 3.0.4? It would be a shame if it was overlooked again.

**Comment by fieldOfView** [comment]
It was just confirmed that this is more than just an aesthetic issue; on some gpu/driver combinations it causes a crash, see #2644
