### ISSUE TITLE
OpenGL graphical mode Windows 7, Nvidia card, the screen freezes

### ISSUE THREAD

**Issue by sim31r** [Ultimaker/Cura#2632]
This is typical for all programs. Cura 14, 15, 2.7, 3.0, Repeater Host. Every 2-3 minutes the screen freezes when working actively. This is a known problem. Helps minimize the window to the tray, change the size. Or press the button Print Screen. Whether it is possible to make separately for Windows augmentation. The easiest way is to simulate an optional press Print Screen, for example every 2 seconds. Perhaps there are other ways of dealing with this problem whith Windows API.

**Comment by ChrisTerBeke** [comment]
You describe this happens to more software than just Cura for you, so I'm not sure what we can fix about this. We're not really directly using any Windows APIs, it's all abstracted away by Qt and Python. But we're open for specific suggestions either here or via pull request!
