### ISSUE TITLE
Cura 3.0.3 Crashes to Desktop after choosing printer model and clicking "Add Printer"

### ISSUE THREAD

**Issue by wolfcry0** [Ultimaker/Cura#2635]
Steps to reproduce:

1. Install 3.0.3
2. Open Cura
3. Select "Printrbot Simple" from list
4. Click "Add Printer"
5. Cura crashes to desktop instantly

[stderr.log](https://github.com/Ultimaker/Cura/files/1399672/stderr.log)
stdout is empty so I did not attach.

Cura 15.04.2 is working fine on the same system, I've been printing with that.

**Comment by nallath** [comment]
I think this is the same issue as https://github.com/Ultimaker/Cura/issues/2644

**Comment by wolfcry0** [comment]
Replacing the `grid.shader` file solved the crash issue, thanks!
