### ISSUE TITLE
Machine Settings Tooltip Timer

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#264]
Cura 15.06.03
OS X 10.9.5

The tooltips for Machine Settings have an issue with the display timer. It looks like the mouseEntered() is being handled before mouseExited() and mouseEntered() isn't stopping the previous Timer.

https://www.youtube.com/watch?v=TJU-aoBvDw0&feature=youtu.be

**Comment by Xisle** [comment]
With the length of some tooltips, maybe no Timer would be better?

**Comment by nallath** [comment]
No timer also feels a bit off. I will experiment a bit with shorter timers, see how that works. It doesn't have that high of a priority though.

**Comment by Xisle** [comment]
Shortening the timer would likely not leave enough time to read the longer tooltips. No timer seems more standard; display tooltip until mouseExited. Not everyone reads at the same rate.

I just tried 15.09.82 and the tooltips are now gone in Cura > Preferences > Settings. They work great in the Print Setup section though.

**Comment by Ghostkeeper** [comment]
I agree with Xisle. Having it the way that users are most used to from web browsers is best, I think.

**Comment by awhiemstra** [comment]
15.10 uses a different mechanism for tooltips that is closer to the platform implementation. The timer issue should now be resolved.
