### ISSUE TITLE
about support mesh

### ISSUE THREAD

**Issue by 651851996** [Ultimaker/Cura#2640]
How to use support mesh，drop down support mesh and anti overhang mesh？？？

**Comment by Vandrasc** [comment]
See the discussion on the forum for more information: https://ultimaker.com/en/community/35603-support-mesh-anti-overhang-mesh
I hope this helps, otherwise feel free to come back :)

**Comment by 651851996** [comment]
I think I can not guess this in any way XD

**Comment by Vandrasc** [comment]
Hi 651851996,

See the below Word document for a small guide about the Support/Drop down/Anti overhang mesh, I hope this makes it a bit clearer on how to use them. For the Support and drop down mesh you don't need the Generate Support to be enabled. Good luck! 
Let me know if you could download the file. 


[Support:Drop down:Anti overhang mesh.docx](https://github.com/Ultimaker/Cura/files/1404157/Support.Drop.down.Anti.overhang.mesh.docx)

**Comment by 651851996** [comment]
Thank you so much，I already know how to use it.
（This method is really hard to find by myselfヽ(￣▽￣)ﾉ）
