### ISSUE TITLE
3.0 German Translation - Button text overlaps time information

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2643]
A german user reported this issue (Windows 7 64bit).
![overlap](https://user-images.githubusercontent.com/1069286/31828577-f2e04484-b5ba-11e7-8fd1-a84bf4a02706.png)

**Comment by hannover345** [comment]
![2017-10-20_21h55_59](https://user-images.githubusercontent.com/32967836/31839749-bf14100e-b5e2-11e7-9d8c-ab62ca298209.png)
![2017-10-20_21h55_15](https://user-images.githubusercontent.com/32967836/31839762-c4fc0f12-b5e2-11e7-8f0f-0694fd615b1c.png)

**Comment by Vandrasc** [comment]
Devs:4478

**Comment by Ghostkeeper** [comment]
Is there a shorter German text we could use than "Speichern auf Wechseldatenträger"? Or maybe we should elide that as well just to be sure...

**Comment by fieldOfView** [comment]
See #2700

**Comment by hannover345** [comment]
I can suggest for Speichern auf Wechseldatenträger
Speichern auf SD/USB
or
Speichern auf SD

On my last Post, second image
"Open Octoprint..."  "Pausieren"  "Drucken Abbrechen"
may be you can change with    

"Octoprint..." "Pausieren"  "Druck Abrechen"

**Comment by fieldOfView** [comment]
Problem is, we don't know if it is an sd-card. Could be a Compactflash card, or a floppy disk.

I am considering changing the "Open OctoPrint..." button to a graphical button (with a monochrome OctoPrint logo) so it takes up less space.

**Comment by nicolinux** [comment]
Couldn't we just use "Speichern"? That's pretty general and could by anything compactflash card, floppy, hard disk...

**Comment by ChrisTerBeke** [comment]
@nicolinux we use different button texts for outputting to disk or to removable drive (to indicate you've selected the correct output method).

**Comment by Ghostkeeper** [comment]
[Wikipedia](https://de.wikipedia.org/wiki/Wechseldatentr%C3%A4ger) suggest "Wechselmedium" as alternative. Is that better, German-speaking folk?

**Comment by ianpaschal** [comment]
This hasn't been touched in 3+ months and is marked as Fixed in JIRA so I'm marking it the same here and closing it.

**Comment by Ghostkeeper** [comment]
Corrected the text in question to `Speichern auf Datenträger`, which was suggested by a colleague. It's a bit better now.
