### ISSUE TITLE
own Post Processing Plugin (script) with appimage

### ISSUE THREAD

**Issue by hexxter** [Ultimaker/Cura#2645]
Hi,
how can i use my own Post Processing Plugin (script) if i use the appimage? I can not mount the appimage  rw.

BR Hexxter

**Comment by fieldOfView** [comment]
See https://github.com/nallath/PostProcessingPlugin/issues/48

**Comment by jypma** [comment]
I've been trying to find out how to make a custom script ([`ChangeAtHeight.py`](https://www.thingiverse.com/thing:2077884)) available when running as appimage. I couldn't make it work with Cura 3.2.1, tried:
```
~/.local/share/cura/3.2/plugins/PostProcessingPlugin/scripts
~/.local/share/cura/3.2/scripts
```
So what's the magic location to place the `.py` file?

**Comment by fieldOfView** [comment]
It should be ~/.local/share/cura/3.2/scripts

There may be an error message in the cura.log file.

**Comment by jypma** [comment]
Interestingly, the code's auto-creation actually made a `scripts` folder at `~/.config/cura/3.2/scripts`. And placing the `.py` there, it is indeed picked up. Curious, since cura does store all other settings in `~/localshare`...

**Comment by fieldOfView** [comment]
My bad, probably (I contributed https://github.com/nallath/PostProcessingPlugin/pull/51). The linux distribution is the only one that splits up the config and "other data" locations, so I never noticed it uses the "wrong" path.

**Comment by jypma** [comment]
Yeah, I expected something like that. I'm using Arch linux, btw. Shall I create a new issue for this? It might just be a matter of documentation.

**Comment by jypma** [comment]
Created https://github.com/Ultimaker/Cura/issues/3356.
