### ISSUE TITLE
Cura crashes when uploading to octoprint

### ISSUE THREAD

**Issue by MarioStoilov** [Ultimaker/Cura#2649]
After updating to Cura 3.0.3, whenever I try to start a printon octo via cura, it get's to about 3% uploadng, stuters and crashes. This was working perfectly on 2.7

Here are some logs

[Cura.zip](https://github.com/Ultimaker/Cura/files/1403856/Cura.zip)

**Comment by Vandrasc** [comment]
@fieldOfView ? Maybe something you can help with? :) Thank you anyways

**Comment by Ghostkeeper** [comment]
That log doesn't seem to contain any information regarding the Octoprint plug-in. It's going to be hard to debug this if it doesn't occur for other people.
