### ISSUE TITLE
Sacrificial Bridging for overhanging holes not printed correctly

### ISSUE THREAD

**Issue by PvtPrivate** [Ultimaker/Cura#2656]
There is an old trick when designing parts for FDM printing, one of them is creating a sacrificial bridge to avoid supports on overhanging holes. More details at https://hackaday.com/2017/10/17/sacrificial-bridge-avoids-3d-printed-supports/

Other slicers detects the bridge and prints it correctly, but cura further separates the bridge. Printing the skin on nothing.

![1](https://user-images.githubusercontent.com/16520813/31860953-6f8cc802-b74d-11e7-96e9-71e1510de833.PNG)
![2](https://user-images.githubusercontent.com/16520813/31860956-732f784c-b74d-11e7-930b-95dfb88780a4.PNG)
![3](https://user-images.githubusercontent.com/16520813/31860958-75b3319e-b74d-11e7-834e-5fce1a5e35fc.PNG)
![4](https://user-images.githubusercontent.com/16520813/31860969-b085906e-b74d-11e7-8515-5894e0fbf986.PNG)

This makes overhanging holes for countersunk screws near impossible to print.

**Comment by smartavionics** [comment]
I use that technique with no problems and I can't really see what the problem is from your above images but have you tried the expand skins into infill option? If you set that to a few mm the skin that goes under your countersunk hole should be expanded out into the infill region and be well anchored.

**Comment by smartavionics** [comment]
Also, a recent addition setting added to Cura is a thing called "extra skin wall count" which, by default, has been set to 1. This puts extra walls around the perimeter of a skin region which in your example above reduces the contact area of the skin itself so it's only supported by the width of 1 wall. The idea behind extra skin wall count is that when the skin is being printed on sparse infill like you have, surrounding it first with a wall can stop the skin drooping when it finishes within the infill gaps. It's a new option and I don't use it (yet) but that's their rational behind it.

**Comment by PvtPrivate** [comment]
On the second picture and the fourth picture, you can see there are some travel moves forming another circle. That inner circle is printing in mid air. On the fourth picture you can clearly see the smaller circle with a different color.

S3D:
![s3d 1](https://user-images.githubusercontent.com/16520813/31861614-ba02f4a8-b75a-11e7-838b-4ee13eb24e5f.PNG)
![s3d 2](https://user-images.githubusercontent.com/16520813/31861628-0540c562-b75b-11e7-8904-daa3317b2e21.PNG)

Cura:
![cura 1](https://user-images.githubusercontent.com/16520813/31861631-0a43ac0a-b75b-11e7-8bc5-964972886622.PNG)
![cura 2](https://user-images.githubusercontent.com/16520813/31861632-0b5d2bf2-b75b-11e7-9f52-a1c516273162.PNG)

**Comment by PvtPrivate** [comment]
Found out that this problem only occurs on the last top skin of the bridge, so if i set the sacrificial bridge to be 2 layers thick, the first layer is fine.

![cura 1](https://user-images.githubusercontent.com/16520813/31861654-5175fefc-b75b-11e7-9a15-b7e74951e292.PNG)
![cura 3](https://user-images.githubusercontent.com/16520813/31861655-529763e8-b75b-11e7-887c-e36a122ebb82.PNG)
![cura 2](https://user-images.githubusercontent.com/16520813/31861656-54951adc-b75b-11e7-9cde-c1976e7d08cc.PNG)

I used to design my sacrificial bridge to be only one layer thick, which is why i noticed this problem.

**Comment by smartavionics** [comment]
There is another setting called Top Surface Skin Layers. When that is non-zero, it has the effect that you have observed. I have a model that uses this technique and when Top Surface Skin Layers is zero, it prints just fine, setting it to 1 causes the same problem as you have seen:

![screenshot_2017-10-22_13-31-13](https://user-images.githubusercontent.com/585618/31861924-507c4d0e-b72d-11e7-86de-5f2bb2f4db1d.png)

**Comment by PvtPrivate** [comment]
You are right. The problem disappear when i turned off Top Surface Skin Layers.

**Comment by filipgoc** [comment]
Nice work figuring this out guys!
