### ISSUE TITLE
Cura 2 Wanhao Beta Edition crashes

### ISSUE THREAD

**Issue by wildbeast91** [Ultimaker/Cura#2658]
Hello Guys

When I try to Print from USB Cura 2 Wanhao Beta Edition crashes everytime.
Knows someone why this happens?

**Comment by ChrisTerBeke** [comment]
You're using Wanhao's own version of Cura? If so, we can't really give support for that here as we don't know what they changed. I think it's best if you contact Wanhao about this issue.
