### ISSUE TITLE
Cost of print behind print button

### ISSUE THREAD

**Issue by AnaGallego86** [Ultimaker/Cura#2662]
Hello!

I just updated to Cura 3.0.

I decided to assign price for the different filaments to Cura gives me the price of the print.

If I decide to use PVA as support the price total estimation becomes to large, so that the liner appears right behind the PRINT OVER NETWORK button. I can read the total cost but you kind of have to guess a little bit.

![image](https://user-images.githubusercontent.com/33025296/31885919-15fa7fd0-b7ea-11e7-9739-5cb96aacce06.png)

Is it just me?

**Comment by ChrisTerBeke** [comment]
Nope, I've seen that as well, but not really using the print cost feature though. Overall this part of the UI needs some re-thinking (e.g. why is the label "Print time" below the actual print time?

**Comment by ChrisTerBeke** [comment]
Fixed in above referenced pull requests, due for next release.
