### ISSUE TITLE
Slicing with large models is continuous so almost impossible to use

### ISSUE THREAD

**Issue by nevetsnikam** [Ultimaker/Cura#2673]
As Cura slices all the time with any change that is made so its almost impossible to use with a large model, 

Suggest to disable the save button and add a "slice now" button so you can finish positioning, mirroring, scaling and then slice. Once sliced enable the save button until another change is made.

**Comment by smartavionics** [comment]
See Preferences -> General -> Slice Automatically checkbox (you'll want to disable this).

**Comment by nevetsnikam** [comment]
Thanks for that, missed that one somehow, probably looking too hard. Thanks
