### ISSUE TITLE
Cura 2.7.0 Wall Lines order?

### ISSUE THREAD

**Issue by darrelhunt** [Ultimaker/Cura#2679]
My line width is 0.40 mm and I have wall thickness to 1.2 mm.  It's drawing 3 lines for the shell as I expect but It's doing it in a wierd order.  I have an item that is a shape and has 2 holes in it.  Cura is drawing the innermost line of the item, then innermost line of each of the holes, then does the next most outer line of them in the same order, then the outermost line in the same order.

I notice that I'm getting gaps in between some of them.  I would like it to draw all 3 lines for a particular feature at once.

For example, draw the outer shell of the item, all 3 lines right after the previous.  Then move to one of the holes, complete all 3 lines, then move to the next hole.

Is there a setting I can set to make it act like this?

**Comment by smartavionics** [comment]
Hi, not in 2.7.0 but if you install 3.0.3 then you will find in the experimental section a setting called Optimize Wall Printing Order which will do what you want.
