### ISSUE TITLE
Mesh color when normal is aligned with camera

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#268]
When looking straight at a face of a model, the color is too bright.

![cura_normals_and_z_pos](https://cloud.githubusercontent.com/assets/8895761/9329301/97a0e8fc-45b0-11e5-92b2-a2de5718d49b.png)

**Comment by BagelOrb** [comment]
current master:
![cura_normals_2](https://cloud.githubusercontent.com/assets/8895761/9437793/43acf512-4a59-11e5-8261-e611c82be15c.png)

**Comment by BagelOrb** [comment]
![cura_normals_3](https://cloud.githubusercontent.com/assets/8895761/9439533/41a206a4-4a68-11e5-9747-6ac5a2603629.png)

**Comment by nallath** [comment]
Lowering the specular even further will pretty much remove the specular effect. This only happens in this very specific orientation.

**Comment by BagelOrb** [comment]
Working
![cura_normals_4](https://cloud.githubusercontent.com/assets/8895761/9440532/257f012c-4a70-11e5-8a2c-8449420d8d37.png)
