### ISSUE TITLE
Minor change in the german-language translation

### ISSUE THREAD

**Issue by app-js** [Ultimaker/Cura#2689]
This is a suggestion for the German translation.
There is an unfortunate translation in the settings for "Setting Visibility".
The "Check all" option should not be „Alle prüfen„ but „Alles wählen" or better „Alles auswählen".
„Alle prüfen" has more of the importance of checking.
„Alles auswählen“ has the meaning "Select all".
![cura_en](https://user-images.githubusercontent.com/22818534/32079387-b7f6cfa6-baaa-11e7-8092-f9fc7ab320c9.png)
![cura_de](https://user-images.githubusercontent.com/22818534/32079393-bfae532c-baaa-11e7-94af-25f80369ba74.png)

**Comment by Ghostkeeper** [comment]
Thanks for the suggestion. I've changed it for the next release.
