### ISSUE TITLE
Z positioning during lifting up

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#269]
When transposing an object up in the z direction, the model is 'dropped' on the build plate while I'm dragging.

I think it would be better if it only drops when I let go of the object.

**Comment by Ghostkeeper** [comment]
I agree. Combined with the problem of putting items partly below the buildplate, I think it's worth discussing how the Z positioning should function.

**Comment by BagelOrb** [comment]
This doesn't look solved at all.

**Comment by nallath** [comment]
I'd suggest updating, as this works for me. The object is dropped when I release the translate tool (it no longer drops them while moving, which was the issue)

**Comment by BagelOrb** [comment]
I have updated.

**Comment by BagelOrb** [comment]
Working
