### ISSUE TITLE
Build plate temperatures thinks a change was made

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2694]
Cura 3.0.3
Windows 10

If you click into the build plate temperatures field then click out with out making a change, Cura thinks a change was made as adds the circular reset arrow next to the field.

**Comment by Thisismydigitalself** [comment]
Same here, both 2.7 and 3.x are acting the same in regards to the build plate temperatures field.

**Comment by nallath** [comment]
This isn't something we can change easily unfortunately.

**Comment by fieldOfView** [comment]
I have not yet found problems with this approach:
https://github.com/Ultimaker/Cura/pull/2703

This does not fix the "problem" of changing the build plate temperature to eg 10 and back to 60. In that case the reset button stays visible.
