### ISSUE TITLE
Cannot open 3mf as project: edit: stupid confusion because mac filenames. No problem. 

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#2698]
Cura 3.0.3
Mac 10.12.6 (Sierra)

Trouble: 
- Basically, Cura always imports object from projects only, and not slicing settings. It does not ask even if 'always ask' is on and it does not open project even if 'always open as a project' is on. 
- I tried turning the preferences into various states and restarting Cura many times. No luck. 
- Interestingly, it did open a project once, (since 3.0.3 installation), but never since. 
- I am using 3mf files generated by Cura 3.0.3. NO 2.7 version crossing here. 

Reproduce: 
- Select 3mf file in finder, open with: Cura, imports object automatically 
- In Cura, use cmd+o shortcuts, select a .3mf file, imports object automatically
- In Cura, click on file: Open File(s), select a 3mf file, imports object automatically

Ideas on what could be corrupted or buggy ?

**Comment by filipgoc** [comment]
Edit: I think this is only because I erroneously saved some files as .3mf and confused them with the .3mf that is a project. 

Trouble of course is it's the same on Mac now (and we all know why), so... that's the tradeoff.

**Comment by filipgoc** [comment]
Edit2: Nope It was NOT the file confusion problem. 

New data: 

I managed to open several files as projects. All working as expected, loading both objects and settings. 

Then it stopped working again. Now I get the Project? dialog: 
![image](https://user-images.githubusercontent.com/16858474/32138077-3f2d7adc-bc2d-11e7-9752-3893dbad984b.png)

But after that nothing happens. No project summary, no loading of settings, no loading of objects. Nothing.

**Comment by filipgoc** [comment]
**Update 3:** Now it works again with the same exact files with which it did not work 10 minutes ago. Didn't even restart Cura. No clue.

**Comment by ChrisTerBeke** [comment]
Closing until issue re-appears and can be debugged.
