### ISSUE TITLE
Cura 15.05.93 application window not visible until a "File > Open"

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#27]
When launching Cura on OS X 10.9.x, the application window is not visible until I attempt to open a file.

**Comment by ErikDeBruijn** [comment]
I had the same. You can also have the window appear pressing the icon, but it doesn't appear by itself. I'm on 10.10.3.

**Comment by ErikDeBruijn** [comment]
I just tested it on version .94 but the window didn't appear by itself.

**Comment by ErikDeBruijn** [comment]
FYI: I just tested it on version .95 on OS X 10.10.3 but the window still didn't appear by itself.

**Comment by nallath** [comment]
It's fixed in .96
