### ISSUE TITLE
Supports multiple independent movements xy and extruder Improve printing speed

### ISSUE THREAD

**Issue by yangxing1007** [Ultimaker/Cura#2706]
A group of XY printing speed is too slow，Especially for large machines。

**Comment by Ghostkeeper** [comment]
I think that your automated translator is leaving out a lot of vital information...

Here's what I think you meant: With some [mechanical arrangements](http://reprap.org/wiki/Category:Mechanical_arrangement), the X and Y axles move independent of each other. Therefore, a diagonal movement can reach higher top speeds than just moving in X or Y direction. This can be used to improve printing speed.

Is that what you meant to say? I used short sentences to help your translator...
