### ISSUE TITLE
Printer's (Sigma R17) figure incorrect

### ISSUE THREAD

**Issue by S3D-r** [Ultimaker/Cura#2711]
View shows bed figure of a delta printer, not Sigma's.

Preferences - Printers  shows Printer type: 101Hero.   Don't know, how could that be changed.

![image](https://user-images.githubusercontent.com/19798034/32300512-7f960444-bf62-11e7-9df9-e642ef91cdc4.png)

![image](https://user-images.githubusercontent.com/19798034/32300582-de979e30-bf62-11e7-84f1-399ad5e6790a.png)

**Comment by ChrisTerBeke** [comment]
As the BCN Sigma is not shipped by default I assume this is a Custom FDM printer or a machine loaded from a project file? If so, the machine settings which contain fields for printer type and build plate model are incorrect.

**Comment by ChrisTerBeke** [comment]
Closing because like the other issue it's a result of BCN Cura doing weird things with saving user data and settings.
