### ISSUE TITLE
Minor glitch on new costing popup

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#2712]
Price overflows onto new line, see here...

![screenshot_2017-11-02_10-54-25](https://user-images.githubusercontent.com/585618/32322427-65c9ace6-bfbc-11e7-9e77-cf563f62ec42.png)

**Comment by Ghostkeeper** [comment]
I think it's very dependent on your OS and the pixel scaling of the monitor or something. On my screen it doesn't even come close; there's like 2cm of space on the right hand side.
