### ISSUE TITLE
Holes disapearing after slicing

### ISSUE THREAD

**Issue by Peterzij** [Ultimaker/Cura#2728]
I made a simple 90 degree angle bracket. STL downloaded in Cura 3.0.4 (using Fusion 360 to draw it) and in the solid view I can see all the holes. But going to layer view the holes are gone. 
![layer-view](https://user-images.githubusercontent.com/33375966/32406844-e3de496a-c17f-11e7-89a0-98d6477a38d8.PNG)
![solid-view](https://user-images.githubusercontent.com/33375966/32406845-e3f7fe6e-c17f-11e7-850c-76e0df75c550.PNG)
In the solid view there are on both surfaces 4x holes.. In the layer view only the vertical surface has holes 4x.. The horizontal surface does not contain any holes anymore. 

I jusst tried to put the other side (vertical) on the heated bed (in Cura) to see if the holes will stay now.. but as soon as this surface hits the "heated bed) the holes are gone.

**Comment by Thisismydigitalself** [comment]
check to see if you have "Remove all holes" checked..

**Comment by fieldOfView** [comment]
If that does not work, search for the setting "Union Overlapping Volumes" and turn it off. If that helps, your model has issues.

**Comment by Peterzij** [comment]
My God.. That it can be so simple... Thanks.. I never thought about that. Thanks Guys

**Comment by Thisismydigitalself** [comment]
Not your fault.
I love Cure.  Cura is a very powerful slicer but this comes with a price. much too often I can't see the wood for the trees as they are so many settings to play with and much too often an hidden setting can and will have negative effect on the finished product and I find myself going back and forth between layer view and solid view for making sure that WYSIWYG . I proposed to the Cura team to add favorites or some color mapping for settings which we use most for not getting lost in the forest. like filters for profiles.

**Comment by dunk7** [comment]
Thx for info, but for future reference for anyone else: Make sure you have your face normals flipped the right way

**Comment by dunk7** [comment]
oh actually I was using blender and I guess you have to leave your cavities as separate objects and doing the boolean modifier messes up the mesh or something.
