### ISSUE TITLE
Cura 2.7.0 on Ubuntu 16.04 closes when creating a custom FDM printer

### ISSUE THREAD

**Issue by Orlasgrandad** [Ultimaker/Cura#2729]

**Comment by ChrisTerBeke** [comment]
Can you attach the logs so we can see what's going on?

**Comment by Ghostkeeper** [comment]
Doesn't happen on my end when using Ubuntu 16.04.3.

**Comment by maukcc** [comment]
Use the appimage. 
Thopiekar`s PPA is not working for multi extruder machines since 2.7 (4 months)
