### ISSUE TITLE
opening an object causes object view / print bed to dissappear

### ISSUE THREAD

**Issue by triola** [Ultimaker/Cura#273]
Using Cura 15.06.3 on a Macbook Air

When I load ANY object (.stl or .obj, even if it's just a cube) the view where I'd normally see the print bed and object displayed just becomes a solid color.

I thought maybe it had zoomed in to a micro level, but I tried zooming out with no success.

15.04 loads my models fine.

**Comment by daid** [comment]
Already fixed for the next release.
