### ISSUE TITLE
Cura 3.0 Not actually changing print settings.

### ISSUE THREAD

**Issue by Mav68erick** [Ultimaker/Cura#2730]
When open for to long, I notice changing anything in your profile, although it may change on the screen and you save it. Sometimes doesn't actually change it. I can have nozzle temp at 215. Save my gcode and load it. and its back to 200 or 205. I can visually notice when this isn't working by changing my infil %. turn t to 1% or to 100% and it visual makes no changes on the preview. When you close cura and re open it, its back to the same invisible settings it reverts too.

Sometimes when you save a current profile. and select a different one, it automatically changes the one you've switched to, to the same as the last profile you are in,

**Comment by Vandrasc** [comment]
Hi @Mav68erick, which version are you using? 3.0.3 or 3.04?

**Comment by Mav68erick** [comment]
I will check when I get home. I haven't updated to the very latest. It's
whatever the current version was 2 weeks ago

**Comment by Mav68erick** [comment]
Im using 3.0.3 Its was the latest when this happened. No matter what
profile settings I changed, it would change on screen, I would slice, and
save the gcode. Run it on my printers, it would default back to something
else.

**Comment by nallath** [comment]
Could you post your logs and a project file?

**Comment by konvoj** [comment]
The issue can be that you are changing the settings for the second extruder. It happened to me several times that the object was set to different extruder that i was changing in the setting. I already reported the issue.

**Comment by Mav68erick** [comment]
Ok. I did accidentlt turn multiple extruders on, and turned them off. And
haven't noticed an issue yet. But I do close cura dialy

**Comment by Ghostkeeper** [comment]
Let's assume that was it then. This is quite a common problem. Is there anything we can do to make it more clear that you're editing on the wrong extruder?

**Comment by Mav68erick** [comment]
I remember when extruder 1 2 3 tabs were at the top slightly.  How about
slightly change the background of each extruder to different colors? Or
different shades, that people can edit as they wish.

I have yet to have this issue happen again now.

The only other issue is switching profiles and even if I say keep or
discard, it will sometimes change a few of the settings. And I have to go
back and say info. I have to update that profile before selecting another
faithfully or if you wait for the pop up menu it can mess up

**Comment by Ghostkeeper** [comment]
They now have different outline colours, but I think that might already have been the case when this issue was reported.
