### ISSUE TITLE
3.0.4 - No post processing cgode feature available

### ISSUE THREAD

**Issue by Raffa2s** [Ultimaker/Cura#2737]
Hi, 
I just have installed the lastest version of Cura (version 3.0.4)  on my W10 pc, but i can't run Post Processing option under Extension :(
The botton "Modify G-Code" is unclickable (it doesn't turn blue when I pass on it), what can i do? I've just uninstalled and clean my whole pc and nothing changed.
Thanks

**Comment by nallath** [comment]
Post your log files please.

**Comment by Raffa2s** [comment]
This is my log file, i've tried to manually add the PostProcessing folder but nothing works.
`
[cura.log](https://github.com/Ultimaker/Cura/files/1457150/cura.log)
`

**Comment by diegopradogesto** [comment]
I tried the same with your same configuration and I can use the postprocessing plugin. As you can see in the picture 
![postprocessing](https://user-images.githubusercontent.com/15830521/32599861-15f3550a-c53e-11e7-95e5-c23f17778d7f.PNG)
, the button is enabled.

I checked the log and the weird thing is that after you upgrade the Cura version, the PostProcessingPlugin is trying to load twice at start-up.
Could you please try to deactivate the plugin, restart Cura, and then activate it again (and restart again). You can do it at Plugins -> Installed plugins.

Send the logs after that, please.

**Comment by Raffa2s** [comment]
Hi,
i've tried to deactive one of those two and nothing come from it :( what can i do? i also have unistalled and reinstall the software 
![cattura](https://user-images.githubusercontent.com/18658128/32606033-013b5624-c554-11e7-8f42-f67fb4dbe738.PNG)
this is teh log
[cura.log](https://github.com/Ultimaker/Cura/files/1457591/cura.log)

**Comment by Raffa2s** [comment]
i have also tried to cut the folder "PostProcessing" and now i have only one tick in Plugins
![cattura2](https://user-images.githubusercontent.com/18658128/32606396-7914a5aa-c555-11e7-835e-9bad02bea0fa.PNG)
here the log file
[cura.log](https://github.com/Ultimaker/Cura/files/1457620/cura.log)

**Comment by diegopradogesto** [comment]
For some reason you got several copies of the plugin and there were some conflicts.
Are you able to access the Modify GCode in extensions now?

**Comment by Raffa2s** [comment]
no :(

**Comment by Ghostkeeper** [comment]
Maybe you could take a look here: `C:\Users\<Raffa2s>\AppData\Roaming\cura\3.0\plugins\`. Is there a PostProcessingPlugin folder there? If there is (somehow) then that could cause the plug-in to load twice.

Why in hell that would disable the menu item, I wouldn't know though.

**Comment by russgraus** [comment]
having the exact same issue with cura 3.2.1

**Comment by fieldOfView** [comment]
Try selecting the menu item with your cursor keys, and then select the item with the enter key.

**Comment by russgraus** [comment]
Thank you that worked

**Comment by luckylad99** [comment]
Have the same problem in 3.3.1 and 'filedOfView's above solution worked .... thanks.
