### ISSUE TITLE
New version popup not clickable

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#2741]
I get this message:
![image](https://user-images.githubusercontent.com/8895761/32436161-68b44086-c2e3-11e7-806d-acbca9c2ce27.png)

But when I click on it nothing happens.

Also happens after restart.

Version: Cura 3.0.3
OS: Windows 10 Home 64bit
GPU: NVIDIA GeForce GTX 1050 Ti
Open browser: chrome

**Comment by ChrisTerBeke** [comment]
Known issue, fixed in 3.1.
