### ISSUE TITLE
Download new version button doesn't work on OSX

### ISSUE THREAD

**Issue by mennoberg** [Ultimaker/Cura#2748]
When I start up Cura 3.0.0 I got notified by a new version is available. The problem with it is that I can't download this version as this button doesn't seem to work.

![screen shot 2017-11-08 at 09 38 28](https://user-images.githubusercontent.com/6329918/32539086-976662d4-c468-11e7-92fa-a5201134e535.png)
![screen shot 2017-11-08 at 09 36 59](https://user-images.githubusercontent.com/6329918/32539008-5f56143e-c468-11e7-975c-32591b3f82ba.png)

**Comment by ChrisTerBeke** [comment]
The button is indeed broken, it is fixed in the next release.
