### ISSUE TITLE
Layer thickness order in Cura 3.04 is wrong

### ISSUE THREAD

**Issue by MyGitCat** [Ultimaker/Cura#2755]
Hi,
there is a wrong order in Layer thickness (Schichtdicke): 0.06 0.25 0.15 0.2 0.4 0.6.
My be that only the text in the window is wrong ...
![grafik](https://user-images.githubusercontent.com/33512016/32596699-76877cca-c534-11e7-8fb8-fdcba22b5175.png)

**Comment by fieldOfView** [comment]
What printer definition do you use?

This happens when a printer definition (the .def.json file) contains a default layer height. Instead it should specify a default quality. See this commit that fixes it for the Creality CR-10 definition:
https://github.com/Ultimaker/Cura/commit/e897431c959491a8cf27fbf275bd2bcabdb15d01

**Comment by LipuFei** [comment]
@MyGitCat I guess you are using a Rigid 3D? The whole family have default layer_height = 0.25.

**Comment by MyGitCat** [comment]
I am using a 3DP-100. Default layer-height sounds very good, but I coud not find it in cura 3.04 which is very new for me. I will search for it and I am sure that is my problem.
Thank you so far.

**Comment by MyGitCat** [comment]
Hello fieldOfViwe,
thank you for your info. I did not know that there are a lot of JSON printer files inside cura. I think I have to create my own 3DP-100.json now. Is there something like a default.json printer? And if where is it defined?

**Comment by fieldOfView** [comment]
>  I think I have to create my own 3DP-100.json now.

Not necessarily. You have not answered the question what *definition* you used. IE: when adding your printer to Cura, what printer type did you choose from the list?

**Comment by MyGitCat** [comment]
My Printer was not part of the list. I added my own printer configuration "Daycom" with 15.04.6 or earlier. And "Daycom" was the automatic default in Cura 3. Maybe it is better to configure a new printer in Cura 3.

**Comment by MyGitCat** [comment]
The problem is fixed!
I had to configure a new printer (Custom FDM Printer). I used the same values as before. After this session the order was correct! 
By the way: I thought that the thickness values comes from Cura 3 but Cura used the values I defined 2 years ago with an old cura version (protected profiles).

--- Thank you ---
