### ISSUE TITLE
Phantom "tower" when generating support (3.0.4)

### ISSUE THREAD

**Issue by stere0atypical** [Ultimaker/Cura#2757]
I'm having this strange issue where when choosing to generate support, I get this phantom "box" in the edge of the plane: 

![solid view no support](https://user-images.githubusercontent.com/33526943/32624467-654658fa-c557-11e7-9fa1-492f99faefec.jpg)

![solid view](https://user-images.githubusercontent.com/33526943/32624416-42171f36-c557-11e7-9a63-eb21dfc4e56d.jpg)

When going into layer view, it actually generates layers for it:

![layer view](https://user-images.githubusercontent.com/33526943/32624415-420652be-c557-11e7-85b7-bf045a1e4f85.jpg)

Any idea what's causing this? I'm using all default settings and Cura 3.0.4

**Comment by ChrisTerBeke** [comment]
That's the prime tower. The printer uses it to wipe the nozzles when switching to prevent filament leaking on your model. If you want you can disable it under custom settings.
