### ISSUE TITLE
disabling retraction doesn't entirely work (cura 15.06.03)

### ISSUE THREAD

**Issue by hooyah** [Ultimaker/Cura#276]
Switching off "Enable Retraction" doesn't stop the slicer to insert retracts every now and then.
It removes most of the retracts but leaves some of them in.
My Ultimaker Original doesn't retract very well and when I print a part that looks like a tube with a thread on the outside, every now an then the slicer decides it has to move to the opposite side of the circle it is printing, retracts and then moves through open space (even though combing its enabled) to the opposite side and continues printing there.

**Comment by BagelOrb** [comment]
That is a quite serious bug! Thanks for submitting it!
It will be fixed in the next release.
