### ISSUE TITLE
Mac 3.0.4 Monitor Page Incorrect Target Temperature + Missing Job Name

### ISSUE THREAD

**Issue by EnumC** [Ultimaker/Cura#2760]
Hello everyone. I noticed an issue with Cura 3.0.4 on Mac, and as you can see in the screenshot below, the target temperature display "0C" for both extruder and build plate despite it properly being set, indicating a UI issue? Job name, print name, estimated time left are also either empty or at 00:00:00. Is this the normal behavior for anything that's not an "official" ultimaker? I would normally try to fix an issue and do a pull request, but unfortunately I am unfamiliar with this project. Can anyone chime in and check what's going on?

![screen shot 2017-11-09 at 3 50 22 pm](https://user-images.githubusercontent.com/5799869/32635594-d8f04cc6-c565-11e7-8a9a-27358ebdac1c.png)

![screen shot 2017-11-09 at 3 55 32 pm](https://user-images.githubusercontent.com/5799869/32635764-73b32bb6-c566-11e7-92fd-8d749c7113d6.png)

**Comment by Vandrasc** [comment]
Hi @EnumC ,

If connected to a printer via USB, the target temperature shows a temperature of 0°C. This is an unfortunate by-product of how the USB connection was implemented and the fact that there is no g-code to obtain this data. At least this was the idea behind it when we implemented this feature. If any thoughts/ideas please feel free to share :)

The second issue, show time estimate and print job name in wifi printing and USB printing, it is a known issue, our product manager just removed this from our planning for being inactive for too long. https://github.com/Ultimaker/Cura/issues/1448

**Comment by EnumC** [comment]
@Vandrasc Doesn't Marlin regularly return current temperature and set temperature in ACK messages? Wouldn't there be a way to grep a certain part of that message which contains the set temperature from serial?

**Comment by fieldOfView** [comment]
Marlin only reports the current temperature, not the target temperature

**Comment by EnumC** [comment]
I thought it returns something like this:

`T:23.61 /0 @:0 T0:23.61 /0 @0:0 T1:23.89 /0 @1:0`

Where `/0` is the target temperature?

**Comment by ChrisTerBeke** [comment]
That depends heavily on the Marlin version and manufacturer modifications. I've seen so many different responses over the years, including T:XX / X, T:XX, TX, T0X, etc. To find your printer's version try hooking it up to Repetier Host and check the serial console.

**Comment by fieldOfView** [comment]
@EnumC, you are quite right, at least in the case of the UM2 and UMO. I will see what I can do.
