### ISSUE TITLE
Per Model Setting default unchecked - Generate Support

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2762]
There is a problem with "per model settings" where the default unchecked state of a settings does not produce the desired outcome. For example when two objects are added and only one should not be printed with support. If "generate support" is enabled globally and then per object setting for one object is set to "generate support" - it is unchecked in the default state. Cura would still slice with support. One needs to check once the per model setting and un-check it again for the UI to pick it up.
For a real-life case, please see this forum post:
https://ultimaker.com/en/community/51898-about-the-supporting-material

**Comment by fieldOfView** [comment]
The same is true for other setting, eg if the infill density is set to 30% in the sidebar, and I add the infill density to the per object settings, I expect it to show 30% initially. Instead it shows 20%

**Comment by fieldOfView** [comment]
This works correctly for single extruder printers

**Comment by Ghostkeeper** [comment]
This doesn't work correctly any more for single extrusion printers since that was streamlined in 3.0 to behave the same.

**Comment by Ghostkeeper** [comment]
This bug was removed from our planning since it was untouched for 12 weeks.

**Comment by fieldOfView** [comment]
“Ultimaker Cura, now equally broken for multi- and single-extruder printers”

**Comment by Ghostkeeper** [comment]
This is fixed in more recent versions.
