### ISSUE TITLE
[3.0] Tweak UI to fit 'Custom Setup' section better on small screens

### ISSUE THREAD

**Issue by lucaspiller** [Ultimaker/Cura#2763]
I'm running Cura on a 13" Macbook Air with a 1440x900 screen. Other Macs have even smaller vertical height. The changes in 3.0 have expanded some elements while shrinking the 'Custom Setup' section a lot - which is the main thing I use on the sidebar. Here a side by side view of 3.0 vs 2.7 with the window maximised:

![screen shot 2017-11-11 at 10 17 05](https://user-images.githubusercontent.com/18404/32687630-903fa516-c6c9-11e7-8e9a-a7b23a8399fc.png)

Is it possible to optimise the sidebar, so this section better fits on small screens?

**Comment by fieldOfView** [comment]
See #2678

**Comment by ianpaschal** [comment]
Sidebar compactor is now a thing and we won't be redesigning the UI much prior to 4.0 at least. Also this is super old.
