### ISSUE TITLE
gcode gen by CURA3.0.4 cause Marlin to reset during print.

### ISSUE THREAD

**Issue by dream4magi** [Ultimaker/Cura#2772]
[CFP_The_Ultimate_Spool_Holder_v2.zip](https://github.com/Ultimaker/Cura/files/1465021/CFP_The_Ultimate_Spool_Holder_v2.zip)
![untitled-1](https://user-images.githubusercontent.com/11450878/32702457-93c4402a-c822-11e7-9dbf-c157fafaf06a.png)

Marlin resets at the same line every time.
I don't know if this is a bug of Cura or Marlin.
This line seems to be a normal G1.

Just happen to this model.
Tried:
1.slice again -same
2.delete model in cura, import stl again then slice it -same
2.restart cura and do all from beginning -same

Cura 3.0.4
Marlin 1.1.6 
Printer:Self made delta type

thanks.

**Comment by ChrisTerBeke** [comment]
Looking at the G-code, which is completely normal, I'd say it's a firmware bug. How about the hidden characters (like new lines or end lines)? An editor like Notepad++ can show those for you. It should have a `\n` at the end of every line.

**Comment by smartavionics** [comment]
The gcode does look OK in craftware gcode viewer. Have you tried moving the print on the build plate or changing any print settings to alter the speeds/line widths, etc?

**Comment by dream4magi** [comment]
After then, i rotate the model and slice again.
The printer didn't reset.
I do think the bug is belong to Marlin, since the gcode is so normal.

**Comment by Ghostkeeper** [comment]
You might want to report this in Marlin's repository?
