### ISSUE TITLE
My cura 3.03 or 3.04 cannot read the STL file，why？？？

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#2775]
My cura 3.03 or 3.04 cannot read the STL file，why？？？how to repaired？

**Comment by ChrisTerBeke** [comment]
Can you provide some more details like the STL file?

**Comment by robin1015** [comment]
cura2.7  read stl ok。but 3.03 or 3.04 can not read any stl file（It can be read before，what happen？） ，open any stl file，cura just display nothing

**Comment by ChrisTerBeke** [comment]
No idea, nothing changed with loading STLs between those version. I can't help you further without STL file and maybe some screenshots of what's happening to you.

**Comment by robin1015** [comment]
ok。justok。thank you

**Comment by nallath** [comment]
Nothing changed in the STL loading in 2.7 or 3.0. Without logs or the STL file, there is nothing we can do to help.

**Comment by ChrisTerBeke** [comment]
No new info, closing.
