### ISSUE TITLE
cura generate a wrong gcode.

### ISSUE THREAD

**Issue by ledinger** [Ultimaker/Cura#2776]
When I insert the stl file flat to cura, cura generate a gcode with printtime 4 Minutes.
When I insert the same file upright, cura generate a gcode with printtime more then 2 hours.

Best regards

leo E aus S

**Comment by ChrisTerBeke** [comment]
Can you give us some more information like the STL file and screenshots of how you slice it?

**Comment by ledinger** [comment]
![cura 3 04 fehler](https://user-images.githubusercontent.com/33639181/32749261-1d10ed64-c8bf-11e7-80c4-f5cb0643
![cura 3 04 fehler](https://user-images.githubusercontent.com/33639181/32749299-3d78a042-c8bf-11e7-8a5a-9e57b59582b2.png)
574c.png)
how can I sent you the png with this info? How can I sent you the stl file?

**Comment by ChrisTerBeke** [comment]
Can you check the G-gcode preview for both to see how it sliced? 

* STLs you can upload by dragging and dropping them in the text field.

**Comment by ledinger** [comment]
The stl file is not supported, I rename the stl to png and put the file to the text field.
![001 225 main plate halbe dicke 3 1](https://user-images.githubusercontent.com/33639181/32749716-6e08cd30-c8c0-11e7-97f1-1f74b9a45700.png)

rename the png to stl please.

**Comment by ledinger** [comment]
I am a german and my english is not so good. I think for this I make some mistakes. Please excue me.

**Comment by ledinger** [comment]
In my cura version 2.62 and 3.04 I can not open the gcode files.

**Comment by ChrisTerBeke** [comment]
Haha downloading and renaming actually worked, magic...

Imported the model and it seems all faces are inverted, so it's only printing the holes and a brim:

<img width="977" alt="screen shot 2017-11-13 at 22 22 13" src="https://user-images.githubusercontent.com/1134120/32749893-20c53602-c8c1-11e7-9d94-7416f165dbdc.png">

You can fix some of this by enabling "Keep disconnected faces" in the custom settings panel, but ideally you want to get a proper STL file with the faces pointing outwards.

<img width="826" alt="screen shot 2017-11-13 at 22 23 36" src="https://user-images.githubusercontent.com/1134120/32749943-5053b45c-c8c1-11e7-9c56-87572acbf4cd.png">

Closing this issue now as it's now a Cura issue.

**Comment by ledinger** [comment]
Thankyou verry much for your Help.

Best regards 

Leo E aus S.
