### ISSUE TITLE
Wrong Layer # with new Model

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2777]
In Cura 3.0.4 ... have the layer view open at a lower than the topmost level. Open a new model. See the new layer count but the layer selecting slider still at the previous position.

Expected: Update layer count and slider to the topmost layer (preferred) or update the layer count relatively to the slider position.

**Comment by ChrisTerBeke** [comment]
This will be fixed in 3.1, it's already working in master branch.
