### ISSUE TITLE
Combing

### ISSUE THREAD

**Issue by EstebanPacheco** [Ultimaker/Cura#278]
Hello I'be made an small test between Cura 15.04 and Cura 15.06.03, i don't know why the outter surface looks like this, i think in some way the combing function is not working:
First image>15.04
second image>15.03.06
![img_4728 2](https://cloud.githubusercontent.com/assets/13565879/9428817/a47484da-49bb-11e5-8228-bd7bfab92982.JPG)
![img_4733 2](https://cloud.githubusercontent.com/assets/13565879/9428839/258e7d1e-49bc-11e5-9787-16a4d94c783e.JPG)

thanks...

**Comment by nallath** [comment]
@BagelOrb This looks like a cura-engine issue.

**Comment by BagelOrb** [comment]
I cannot reproduce your exact problem without the STL and the settings.

However, I've just solved a couple of bugs concerning the outer walls. One bug resulted in warts and another in wavy skins. These bugs are now solved, so I expect your bug to be solved as well.

In the next release the whole combing mechanism has been overhauled. Computation is slower, but the results should be better.
