### ISSUE TITLE
3.04 Auto Layout raising model by first layer height

### ISSUE THREAD

**Issue by silycr** [Ultimaker/Cura#2792]
Model is automatically placed 0.1mm above bed level.
Using supports and skirt
*First Layer
![image](https://user-images.githubusercontent.com/32662182/32861040-a27721a0-caa7-11e7-8d4b-241d2bed0abd.png)
*Second Layer
![image](https://user-images.githubusercontent.com/32662182/32861112-e4e24bf0-caa7-11e7-98fd-787d7b5bc41f.png)
*Z offset -0.1mm ; First Layer
![image](https://user-images.githubusercontent.com/32662182/32861082-c529d85a-caa7-11e7-8dc8-b9d709b2d9fa.png)

**Comment by Vandrasc** [comment]
Hi @silycr, I am not able to reproduce using a default profile. I noticed that you are using a customised profile, is it possible to link your project file so we can see what went wrong? Thank you!

**Comment by Ghostkeeper** [comment]
Correction: Apparently that didn't make it into 3.1, so it'll be 3.2 then :(

**Comment by BagelOrb** [comment]
Not all those are duplicates. Some are a similar problem caused by the engine.

The first layer might be too small to be printed. If another model does have a first layer then this model will be printed on the second layer.
