### ISSUE TITLE
If object is under the build plate no error message is flagged up (or object greyed out)

### ISSUE THREAD

**Issue by robinbon** [Ultimaker/Cura#2793]
I have series of objects on build plate.

Inadvertently found 1 was below the build plate on printing.

Seems no error message is flagged up if this is the case.
<img width="550" alt="screen shot 2017-11-16 at 12 57 21" src="https://user-images.githubusercontent.com/33720787/32890115-bdb32ace-cacd-11e7-8226-0d59d4214dce.png">

**Comment by nallath** [comment]
That's because it's not an error. This is used to print parts of the object. Everything below the build plate is ignored (and not sliced). This is quite usefull for scanned objects, which quite frequently don't have flat surfaces.

**Comment by robinbon** [comment]
Ok, but thought that would be an option (bit like drop to build plate).
