### ISSUE TITLE
Feature Request - Z-hop for ironing

### ISSUE THREAD

**Issue by Chompworks** [Ultimaker/Cura#2794]
When ironing, there is still nozzle travel over previously ironed surfaces, slightly reducing the smooth result that ironing is meant to achieve.
Would it be possible to add a toggleable option for ironing travel moves to z-hop? [or is it tied to retractions z-hopping or a similar separate control elsewhere in Cura?]
![img_1066](https://user-images.githubusercontent.com/33717818/32898011-e27cca70-cade-11e7-83da-3d68f4603d7c.jpg)

**Comment by smartavionics** [comment]
Hi, do you have combing enabled? If so, setting to "no skin" could stop that happening?

**Comment by Chompworks** [comment]
Thats actually with no skin combing enabled - was present in Cura 2 and just remembered to test it in Cura 3 while dealing with a different issue.

**Comment by smartavionics** [comment]
OK, can you please make the project available and then I can see where those travels are being created?

**Comment by Chompworks** [comment]
Sure, here you go:
[MaterialSampleCura.3mf.zip](https://github.com/Ultimaker/Cura/files/1479220/MaterialSampleCura.3mf.zip)

**Comment by smartavionics** [comment]
Thanks for the project. I notice two things:

1 - combing was set to all, you want it to be no-skin so that it retracts when moving over skin.

2 - you need to z-hop on retract otherwise it will just drag the nozzle.

Hope this helps.

**Comment by Ghostkeeper** [comment]
The No-Skin combing setting is sort of meant for this.

**Comment by GregValiant** [comment]
I'm cleaning house and checking to see if these old requests are still valid.
Can this be closed?

**Comment by Chompworks** [comment]
> I'm cleaning house and checking to see if these old requests are still valid. Can this be closed?

I’ll be frank - I’ve stopped using Cura as a slicer for my printing workflows now, so it can be closed as far as I’m concerned.

**Comment by GregValiant** [comment]
I have a post-processor that accomplishes this by adding z-hops just for particular layers.  At some point I'll get it added to Cura.
