### ISSUE TITLE
3.0.4: Priming at the end of the retraction happening too early

### ISSUE THREAD

**Issue by badvision** [Ultimaker/Cura#2795]
I have a MakerSelect 3D, upgraded with a Ramps 1.4 running Repetier firmware and a microswiss hotend.  (there's other mods, but not important for this issue)

I have retraction and coasting enabled, and there's no stringing on the edges where the head starts retraction.  However, within 2mm or so of the next surface, I'm getting blobbing.  There's an extra priming amount setting that helps solve under extrusion at the end of retraction, but I see no way to control when priming starts, only the feed rate.  Is there any way to tell it to prime less material at the end of a retraction?

**Comment by badvision** [comment]
[MS_Retraction Towers.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/1479021/MS_Retraction.Towers.curaproject.3mf.zip)

Here is the model I am using to test my retraction settings.  Cura is printing the shapes in the same clockwise order, making it easier to see the priming issue.

**Comment by badvision** [comment]
I think this is the same as #2667 -- A negative setting is yielding the same result as a zero-setting.

**Comment by Ghostkeeper** [comment]
This is indeed a duplicate.
