### ISSUE TITLE
UM2 Crashes into metal build plate bracket

### ISSUE THREAD

**Issue by martinjacala** [Ultimaker/Cura#2799]
I sliced my stl with latest cura 3.0.4 with pretty much basic settings. When i tried to print it i realised my UM2 crashed into the left glass plate bracket mid-print of the first layer. 

I have then tried to check the gcode and indeed, there is a strange move towards left the corner.
Attached is the gcode and the cura profile i used. I can also attach the stl if needed.

![screenshot 2017-11-17 16 07 16](https://user-images.githubusercontent.com/1102746/32953867-c4ac31b0-cbb1-11e7-9519-2ac9178e4142.png)
[Archive.zip](https://github.com/Ultimaker/Cura/files/1482762/Archive.zip)

**Comment by smartavionics** [comment]
Hi, this could possibly be related to #2704 which has been fixed (I hope). As a workaround, if you slightly reduce the line width, the erroneous moves may go away. This worked for the other model that was showing a similar problem. I hope this helps.

**Comment by Ghostkeeper** [comment]
Could you try this again with the 3.1 beta (or wait for the 3.1 release in 2 weeks)?

**Comment by martinjacala** [comment]
I tried to slice the same file with same profile in 3.1 beta and the issue **is** gone! Thank you!
