### ISSUE TITLE
Drop on build plate broken: Object suddenly moved down through build plate

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#280]
If a model was placed/dropped on the buildplate then rotating it shouldn't make it so that it is suddenly half way through the buildplate.

perhaps there should be some checkbox "Always place on buildplate" which automatically gets unchecked when you cchange the z position.

**Comment by nallath** [comment]
Whoops, typo on the close.

**Comment by BagelOrb** [comment]
Same still happens after a scale-up.

**Comment by BagelOrb** [comment]
Also happens after (dual extrusion) merge

**Comment by BagelOrb** [comment]
Fixed
