### ISSUE TITLE
Infill Line Directions Character Limit

### ISSUE THREAD

**Issue by get2500** [Ultimaker/Cura#2802]
The box for infill line directions prevents the user from typing (or copy/paste) more characters than the box can hold, thus limiting how many infill directions can be in the list. It seems as if this input box should scroll to the left and right so there isn't a low character limit preventing the user from creating complex infills manually.

**Comment by Ghostkeeper** [comment]
There was a limit on it. On purpose, because if the text field became too wide then the text would just exceed the text box and go over the setting label. I found a fix for that and removed the limit.
