### ISSUE TITLE
offsetting of the center of rotation of the table

### ISSUE THREAD

**Issue by voice2001** [Ultimaker/Cura#2806]
When I turn the table in CURA, the center of rotation is shifted behind the object.
Even if the option "center camera when item is selected" is checked in the settings, and I chose the model, at first the table will be focused on it and the table rotates normally. But after changing the zoom, the center of rotation is shifted again.
Please note that this is not the rotation of the model , but the rotation of the table in the CURA.
This is happening in LinuxMint 18.1, Cura 2.7.0 and 3.0.4

**Comment by ChrisTerBeke** [comment]
Do you have "zoom to mouse position" enabled as well?

**Comment by voice2001** [comment]
Thank you sooooo much )))))
