### ISSUE TITLE
CR10 printhead settings

### ISSUE THREAD

**Issue by bzed** [Ultimaker/Cura#2808]
I think the printhead settings for the CR10 series printers are still based on the default fdm profile. My measurements are:

Xmin: 30mm
Xmax: 29mm
Ymin: 32mm
Ymax: 34mm
gantry: 24mm

**Comment by ChrisTerBeke** [comment]
We're not maintaining 3rd party machines ourselves, so any community pull request is welcome for this!

**Comment by Ghostkeeper** [comment]
I'm not above a bit of data entry. It's probably faster than to have a pull request made, an internal ticket, to review that pull request or even than just entering the merge and push commands.

The gantry height was already set to 30, so I left that in.

**Comment by bzed** [comment]
Thanks @Ghostkeeper (I'd have created a pull request at some point, just too busy to come to the point on my todo list...)
