### ISSUE TITLE
3.0.4 not working with FABtotum

### ISSUE THREAD

**Issue by lahines100** [Ultimaker/Cura#2818]
I loaded the new 3.0.4 (64) release into my FABtotum Core. When I tried to change the nozzle parameter the program quit.
[cura.log](https://github.com/Ultimaker/Cura/files/1488194/cura.log)

**Comment by PaoloP74** [comment]
Uninstall Cura 3.0.4 and all the previous versions.
On Windows, remove the C:\Users\xxxx\AppData\Roaming\cura and C:\Users\xxxx\AppData\Roaming\cura
(Replace xxxx with your username)
Reinstall Cura 3.0.4.

**Comment by lahines100** [comment]
In your instructions it looks as if I should remove the same file twice.

------ Original Message ------

**Comment by PaoloP74** [comment]
I edit previus comment.
Subdirectory are Roaming and Local.

**Comment by lahines100** [comment]
Still have a problem.
When FABtotum printer loads, program quits.
From the log, looks as if problem is with container metadata:
"2017-11-23 14:04:39,249 - WARNING - 
cura.Settings.ContainerManager.getContainerMetaDataEntry [184]: Could 
not get metadata of container  because it was not found."
Complete log is attached.

------ Original Message ------

**Comment by nallath** [comment]
You didn't attach the logs. Github doesn't allow for email replies to have attachments.

**Comment by lahines100** [comment]
Although I couldn't attach the logs, the problem statement was included 
in the email.

------ Original Message ------

**Comment by Ghostkeeper** [comment]
The warning that you posted from the log is fairly common in normal use and doesn't result in Cura quitting. I fixed it in the `feature_local_container_server` branch which is going to be included in version 3.2. I'm thinking it must be something else because that was just a minor display issue.

**Comment by Ghostkeeper** [comment]
We haven't been able to reproduce this issue.
