### ISSUE TITLE
Cura is extremely slow display and GUI if model sliced model

### ISSUE THREAD

**Issue by hoegge** [Ultimaker/Cura#2823]
Whenever your model is just a bit bigger than a tiny (i.e. bigger than around a couple of centimeters) thing Cura becomes extremely slow when viewing at the result in layer view but also in solid view- rotating etc., takes 2-3-4 seconds before the model actually move. When you have sliced a file also the GUI becomes extremely slow just scrolling the menus, i.e., it takes 2-3 seconds before the menus move. It is the size of the sliced result (gcode) that decides if it is slow - not the size of the STL file. If I slice a 500 k or 25 MB STL file does not matter - it is the volume of the result, that matters.
If I load a model and have turned of auto-slicing everything responds quickly. As soon as I have sliced a big item everything including the menu starts to crawl. 

There is an issue somewhere that delays all UI interaction when the sliced result is big and since it is also the menu with auto-slicing turned off it is probably not related to the actual slicing or graphics. [http://gcode.ws/](url) can visualize and rotate the resulting Gcode in real time on the same computer and so can Simplify3D.

**Comment by diegopradogesto** [comment]
We found an issue some time ago regarding this. The layer view can be very slow when rendering a lot of lines and of course it depends on how many lines it has. The problem was that when switching back to Solid View, Cura was still unresponsive.
What we fix for the next 3.1 release is that switching to Solid View is not slow any more. We could not improve the performance of the Layer View a lot, because it also depends on the graphic card and computer performance.
Could you please share information about what OS are you using, graphic card model and Cura version?
Just to check whether it's something different or not.

**Comment by hoegge** [comment]
Actually I don't think it is related to CPU and graphics card. If you have just sliced a model, whether you are in layer view or solid view also the mouse starts to react slowly when in the CURA program. If you have auto-slicing turned off this very slow behavior continues until you change a single parameter, without re-slicing - then Cura responds fast again. So it is not due to any rendering of the layers. Also any other program like Simplify3D and others can easily render such big paths. I think the issue is hiding somewhere else, going into an unnecessary loop or something after having sliced the model.

I have no issues with 3D rendering and use the same machine CAD design using Fusion 360 

Windows 10 64 bit, 32 GB RAM,
NVIDIA Quadro K1000M
Cura 3.0.4

**Comment by Ghostkeeper** [comment]
I have Windows 8.1 64-bit, 32 GB RAM and an NVIDIA GeForce GTX 560. This GPU has about half of the memory of your K1000M. For me it runs fine though, up until models of like 20cm diameter; then it'll start to stutter from all those lines.

If even your mouse starts to react slowly that could be an indicator of your RAM running out, but with 32GB you'd expect it to be fine. What you describe sounds like a framerate issue for the rest, though.

As a workaround, you could go back to compatibility mode (in the preferences under Viewport Behaviour).

Our rendering is not very efficient right now. We don't even have backface culling or frustum culling. That alone will more than double the framerate...
