### ISSUE TITLE
Cura 3.0.4 - incurrect wall count printed with nozzle >0.4

### ISSUE THREAD

**Issue by pumpal** [Ultimaker/Cura#2825]
Cura 3.0.4, have nozzle set to 0.6, wall thickness set to 1.2. Wall count then automatically shows as 2, which is correct. In layer view mode though, as well as in the actual print, 3 wall lines are shown and printed respectively, as if the line width/nozzle size was the default 0.4.  Cura 2.7 (with the same profile) is fine.

**Comment by smartavionics** [comment]
In cura 3 a new setting appeared called extra skin wall count which they defaulted to 1, set it to 0 and you should only get 2 walls.

**Comment by pumpal** [comment]
Perfect - I know it must be something like that - thank you very much!
