### ISSUE TITLE
Cannot move object in +Z direction

### ISSUE THREAD

**Issue by fgvdla** [Ultimaker/Cura#2831]
When i place two objects which i want to merge it is impossible to move an object in the +Z  direction.
Cura places both objects on Z = 0, one object should be at Z= 9  (STL by OpenSCAD). When i try to move an object I can move in X and Y, in Z only to Z - when i try to move it Z + it  resets to Z 0
If i create a small dot on Z= 0 by the object (in the STL) that should be at Z 9, it appears at the right height but still i cannot move it in Z +.
When i use the merge command then it is oké (the first object is placed on top of the second ),but it should be possible to move by hand ?

**Comment by ChrisTerBeke** [comment]
There is a preference "Automatically drop models on the build plate" which is enabled by default to prevent users from printing things in the air. If you still want this however you can disable this preference and the models will stay at the new z position.
