### ISSUE TITLE
How to calculate the size of model in Cura?

### ISSUE THREAD

**Issue by RNDAlex** [Ultimaker/Cura#2836]
At the corner of 3D view, there are serveral parameters about stl loaded, including width, depth, height, volume and so on. I want to know how to calculate these or what method the program called after I put my model in. Thanks!

**Comment by ChrisTerBeke** [comment]
There's a lot of code that is involved with this, you could check these files:

**Comment by RNDAlex** [comment]
THX and I'll take time to read files
