### ISSUE TITLE
Layer Count Indicator cut off

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2843]
Changing the layer height the new layer value (was 70 is now 60) is cut off on the left, see screenshot:
![screen shot 2017-11-24 at 18 26 57](https://user-images.githubusercontent.com/91770/33219894-3390df8e-d145-11e7-8686-0907422b1ad4.png)

**Comment by smartavionics** [comment]
Also doesn't cope with more than 999 layers!
![screenshot_2017-11-29_10-26-46](https://user-images.githubusercontent.com/585618/33370595-ee1997da-d4ef-11e7-9b1a-5c6d0c84b7c5.png)

**Comment by Ghostkeeper** [comment]
We've had a few fixes related to this during the beta period of 3.1. Could you test again using the 3.1 stable version?

**Comment by thesec** [comment]
Would love to but 3.1 messes up my settings from 3.0.4 so all materials, extruders and other are gone ... :/

**Comment by thesec** [comment]
Confirmed done w/ me.
