### ISSUE TITLE
Feature: Filename: append ".gcode" or ".stl"

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#287]
When saving to file, automatically append the right extension when no extension has been provided.

**Comment by nallath** [comment]
There is no 'right' extension when no extension has been provided. You can save to a number of filetypes (saving to OBJ is also possible for instance)

**Comment by Ghostkeeper** [comment]
Normally, a save menu has a little drop-down that determines the file type with which the file is saved, right? And then it would add the appropriate extension.

**Comment by nallath** [comment]
Yeah, which is what happens now.
