### ISSUE TITLE
Could not Abort Print via Ultimaker Cura / Cura Connect

### ISSUE THREAD

**Issue by goodstevening** [Ultimaker/Cura#2878]
Although I received the dialogue box, asking me if I wanted to abort the print (clicked yes), Cura Connect did not abort the print. I had to manually abort the print at the machine itself.

Ultimaker 3
4.1.1.20171124
Ultimaker Cura 3.1 BETA

**Comment by ChrisTerBeke** [comment]
Did you start this print job from Cura?

**Comment by ChrisTerBeke** [comment]
Indeed it now only works for Cura-started print jobs. We're working on retry and USB print jobs to get the same functionality, but I don't know the timeline on that.

**Comment by nallath** [comment]
Cura Connect just started a new sprint in which we will tackle this issue.

**Comment by goodstevening** [comment]
Thank you for the update @ChrisTerBeke @nallath.
