### ISSUE TITLE
First time: cannot get out of adding printers

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#288]
Steps:
- delete .local/share/cura/settings/[printer].cfg
- start cura
- add printer (UM2) by clicking finish
- new printer platform etc is loaded

Expected: window closes
Actual: add printer window stays and won't go away

**Comment by nallath** [comment]
Workaround; Use the right mouse button to close the window.

**Comment by BagelOrb** [comment]
Such inventiveness ^^
