### ISSUE TITLE
Cura 3.1beta - hotend temperature issue

### ISSUE THREAD

**Issue by caoxiangfish** [Ultimaker/Cura#2881]
When I saved the G-code file. The hot-end temperature was always 205° except the initial layer, whatever the value of the "printing temperature" setting is.

**Comment by ChrisTerBeke** [comment]
There were some issues in the 3.1 beta with resolving settings. Please remove the user data folder and try again with the 3.1 stable when it comes out next week.

**Comment by badvision** [comment]
I was also having the same problem.  It shows the settings correctly at the end of the file but the M104 and M109 commands are also showing an incorrect temp.   Temp should have been 240 but was set to 215

**Comment by ChrisTerBeke** [comment]
This is fixed in the stable release today. Please make sure to throw away your beta user data folder in order to get the correct settings upgrade.

**Comment by vursalov** [comment]
I founf a woraround. In the configuration settings of printer (change G-code):
M109 S{material_print_temperature} need to set M109 S235 where 235 is a temperature first layer
