### ISSUE TITLE
View orientation buttons should not change distance of camera to build plate?

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#2891]
The new view orientation buttons (or whatever they are known as) are quite nice but I don't want to use them because they zoom out too far and make the object tiny. I would much prefer if they didn't alter the distance of the camera from the build plate (or whatever the datum is).

Too far away!

![screenshot_2017-12-01_16-59-22](https://user-images.githubusercontent.com/585618/33493762-053d7ace-d6b9-11e7-90ef-533b6a858013.png)

**Comment by Thisismydigitalself** [comment]
If you're talking about Quick camera controls, i second that. 
in addition when you click on any of these and then zoom in, even if the object is selected it will not zoom to center of screen. Also too dark to notice in dark Theme.

Can i ask how to get this working?..
![ice_screenshot_20171201-211144](https://user-images.githubusercontent.com/30949968/33499100-475c01be-d6dc-11e7-95c7-424bf342c4b8.png)

**Comment by smartavionics** [comment]
I'm talking about the little buttons that have recently appeared in top right hand corner of the screen:

![screenshot_2017-12-01_19-37-55](https://user-images.githubusercontent.com/585618/33500017-3c13ff1c-d6cf-11e7-85ab-268f21f6135d.png)

The variable layer height stuff is in the current development source (master branch). I should think that it will most likely appear in version 3.2 but I am not an Ultimaker person so that's just a guess.

**Comment by Thisismydigitalself** [comment]
Yes, these are quick camera controls.
On dark Theme they are almost invisible.
![ice_screenshot_20171201-202721](https://user-images.githubusercontent.com/30949968/33500450-7e8a7a58-d6e1-11e7-9db2-3314c28a0574.png)

**Comment by ChrisTerBeke** [comment]
Adaptive layers will indeed be in 3.2 as experimental mode feature. I've created a new internal ticket for improvements to the view orientation buttons.

**Comment by ChrisTerBeke** [comment]
Devs: CURA-4663 (not added to current sprint yet).

**Comment by cmatthes** [comment]
I would second @smartavionics note regarding the zooming behavior. 
Maybe not the most left icon but the other four on the right shouldn't zoom out. 
Personally they are currently of no use to me due to the zooming out.
