### ISSUE TITLE
SLICINGSLICINGSLICINGSLICINGSLICINGSLICING

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#290]
For every reslice another slice message is appended.
![slicing](https://cloud.githubusercontent.com/assets/8895761/9444350/6fc2636c-4a86-11e5-8bb1-079bde84bf43.png)

**Comment by TMHogenhout** [comment]
yeah saw it, will be working on it this afternoon

**Comment by TMHogenhout** [comment]
https://github.com/Ultimaker/Uranium/commit/3f563244bd5fd2b4f52579de436f89b028281432
