### ISSUE TITLE
NO reconoce puerto COM3 con Prusa i3

### ISSUE THREAD

**Issue by edugarci** [Ultimaker/Cura#2907]
hola buenas noches, tengo un problema grave, perdí la comunicación con mi impresora Prusa i3
y lo intente con  casi todo sin lograrlo, no reconoce el puerto. haber si me podéis ayudar porfa.
Borré los puertos para que me la reconociera automáticamente como ultimo recurso y sigue sin comunicarse con el ordenador

**Comment by ChrisTerBeke** [comment]
Please ask you question in English?

**Comment by edugarci** [comment]
hello good night, I have a serious problem, I lost communication with my Prusa i3 printer
and try with almost everything without achieving it, does not recognize the port. have if I like to help porfa.
Delete the ports so that I am automatically alerted as a last resort and still do not communicate with the computer

**Comment by ChrisTerBeke** [comment]
Does it work with other USB printing software? If not, I'm afraid we can't really do anything in Cura to fix it. If it does, it might be that Cura doesn't support the Prusa's type USB connection, but I've seen others use it without issues though.

**Comment by edugarci** [comment]
Si, la placa arduino la reconoce, pero no la de la prusa I que es la V1. 2

El 5 dic. 2017 19:14, ChrisTerBeke <notifications@github.com> escribió:

Does it work with other USB printing software? If not, I'm afraid we can't really do anything in Cura to fix it. If it does, it might be that Cura doesn't support the Prusa's type USB connection, but I've seen others use it without issues though.

**Comment by edugarci** [comment]
Yes, with the arduino plate alone, but with the prusa i3 do not, which has the plate V1. 2

**Comment by ChrisTerBeke** [comment]
Then it's not really a Cura issue but a firmware/board issue with the printer itself. I'll close this thread then.

**Comment by Ghostkeeper** [comment]
Other people seem to work with the Prusa i3 boards fine though. I've seen it work.
