### ISSUE TITLE
Can't save project, getting "illegal name", Cura 3.1

### ISSUE THREAD

**Issue by roches1969** [Ultimaker/Cura#2913]
When choosing "Save Project" and there is not already given an name to the project.

When saving a project-file "3mf" i get an notification "illegal name".

So project can't be saved by name "test.3mf" or whatever...

When you choose "Save as..." it works good...

**Comment by Vandrasc** [comment]
Hi @roches1969, I am not able to reproduce on my Win10. What OS are you using?

**Comment by LipuFei** [comment]
@roches1969 The project files are saved as ".curaproject.3mf". Could you try that extension?
