### ISSUE TITLE
Profiles lost after update to Dec 5 release of Cura

### ISSUE THREAD

**Issue by realismrocks** [Ultimaker/Cura#2925]
I've tried installing fresh (post removing %appdata% folder) but do not see default profiles. 
Can these be downloaded somewhere?

**Comment by ChrisTerBeke** [comment]
Hi. Can you show a screenshot of your situation maybe? Which printer do you have selected?

**Comment by Ghostkeeper** [comment]
The default profiles are not stored in the AppData subfolder, but in Program Files, so you haven't deleted them, don't worry. But we will need to know what printer you're using at least, or perhaps a project file (File -> Save Project).

**Comment by ianpaschal** [comment]
Reporter has not provided more information for more than 2 weeks, so closing.
