### ISSUE TITLE
Front View not working

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#2927]
Windows 10, GTX Titan, etc.

Front view button doesn't set view to front, but to a different position.

Front view button: 
![image](https://user-images.githubusercontent.com/8895761/33707980-7a4e483c-db39-11e7-8aac-1baa64c22774.png)

Produces:
![image](https://user-images.githubusercontent.com/8895761/33708012-8eb87298-db39-11e7-8fc4-10ee772dabb2.png)

Rather than:
![image](https://user-images.githubusercontent.com/8895761/33708025-9c8187c0-db39-11e7-8db2-63fab8ddf5db.png)

Also:
the angled view button produces unexpected results, but I don't know whether this is intended.

I mean this button: 
![image](https://user-images.githubusercontent.com/8895761/33708095-cb115c1e-db39-11e7-89e4-014fec502bc6.png)

Produces:
![image](https://user-images.githubusercontent.com/8895761/33708119-d914cbb6-db39-11e7-834a-0dca94f53b7d.png)

Rather than:
![image](https://user-images.githubusercontent.com/8895761/33708133-e8bbd03c-db39-11e7-86e6-579090d8e9d6.png)

**Comment by nallath** [comment]
@alekseisasin; Could you have a look at this?

**Comment by alekseisasin** [comment]
We already have a ticket for this CURA-4642, it will be solved before next realize.

**Comment by ChrisTerBeke** [comment]
Fixed in https://github.com/Ultimaker/Cura/commit/5a9e3a8efd0a9e1a69fbcd0c8e4873906bcbcca2. The "3d" view will remain the same, even though it doesn't 100% reflect the icon, but that's just an icon representation.
