### ISSUE TITLE
Enabled support with initial layer height of 0.1 and support confuses build plate adhesion generation

### ISSUE THREAD

**Issue by Gh0stWalk3r** [Ultimaker/Cura#2931]
I tried to slice the file Filament-Spool-Mount-Universal_-_Base.stl from https://www.thingiverse.com/thing:2179768 and recognized, that with an _Initial Layer Height_ of 0.1 and with _Support_ enabled confuses the build plate adhesion-generator and produces a _Build Plate Adhesion_ only around the Support-Material.
![image](https://user-images.githubusercontent.com/10714600/33726941-d083b01a-db76-11e7-8981-c2e214697f45.png)

Disabling _Support_ or increasing _Initial Layer Height_ to 0.2 produces a correct result.
![image](https://user-images.githubusercontent.com/10714600/33727143-80d4f3f2-db77-11e7-8831-36b640a0285b.png)

The issue can be easily reproduced since Cura 3.1 Beta on Windows 10 x64.

**Comment by ChrisTerBeke** [comment]
Can you remove all your 3.1 user data and try the 3.1 stable that came out 2 days ago?

**Comment by Ghostkeeper** [comment]
This looks suspiciously like https://github.com/Ultimaker/Cura/issues/1229, but it's not the same since this seems to have something to do with support (which was disabled in that issue).

**Comment by ChrisTerBeke** [comment]
We had this in the office last week. The problem then was the model (it was broken on the bottom). After repairing with netfabb the skirt was correct.

**Comment by Ghostkeeper** [comment]
So in the engine it's possibly using a different polygon for generating the skin than the one it uses for generating the skirt.

**Comment by ChrisTerBeke** [comment]
Probably, see CURA-4718 for details.

Here an image from before and after fixing:

![image-2017-12-15-15-13-19-978](https://user-images.githubusercontent.com/1134120/34201147-dce52a08-e573-11e7-9e09-eb3b8bcb4229.png)
