### ISSUE TITLE
Scroll bar not accesible 

### ISSUE THREAD

**Issue by Wouw** [Ultimaker/Cura#2935]
When you change setting for example from the support, and you close the tab.
It happens that when your are to far scrolld down that you cant scroll back up to matarials becaus the scroll bar has vanishd.

**Comment by Ghostkeeper** [comment]
It works for me. See this small video: [scrollbar.zip](https://github.com/Ultimaker/Cura/files/1575047/scrollbar.zip)

It automatically scrolls back up.

**Comment by Wouw** [comment]
![image](https://user-images.githubusercontent.com/34341541/34209075-09069eba-e591-11e7-863b-e245869cbdeb.png)

when i have multiple tabs open and close the largest one, de top most tabs are almost always gone.
i have to reopen a tab and scroll back up or close the window to reset everything and make the scroll bare visible again.

**Comment by alekseisasin** [comment]
This issue a bit difficult to reproduce, but I found the way how to do it. Thank you @Wouw 
Devs: CURA-4732

**Comment by Ghostkeeper** [comment]
Using alekseisasin's reproduce steps I could reproduce it too. Or basically a simpler version:
* Expand a category.
* Expand a different category.
* Collapse the first category.
* Position the scroll bar such that it's not entirely at the top (so scroll down slightly).
* Collapse the second category.

I made a fix that will be included in version 3.2.
