### ISSUE TITLE
Cura Crash on Create New Profile

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2936]
Cura 3.1
Windows 10
Ultimaker 2+

Cura crashed on me when I tried to "create profile from current settings/overrides"

[cura.log](https://github.com/Ultimaker/Cura/files/1542370/cura.log)

**Comment by LipuFei** [comment]
Hi @ChrisRiddell, if you have used Cura 3.1 BETA, please make sure your cura 3.1 beta directory is removed. If that's not the case, could you send your cura directory to us? I cannot find anything useful in the log...

**Comment by ChrisRiddell** [comment]
Fresh install of Cura 3.1 all appdata folders where removed from beta before I got this.

Do you want the one from C:/ programs or the folder from appdata?

**Comment by LipuFei** [comment]
From `AppData\Roaming\cura`. Thanks!

**Comment by ChrisRiddell** [comment]
[cura.zip](https://github.com/Ultimaker/Cura/files/1542698/cura.zip)

There you are hope it helps

**Comment by LipuFei** [comment]
Hi @ChrisRiddell , sorry that I cannot reproduce this problem with and without your cura settings. Do you still get this crash?

**Comment by ChrisRiddell** [comment]
Only had the crash twice it seems to be super random if it happens or not when making the new profile.

**Comment by ChrisRiddell** [comment]
Can't reproduce this no more not sure what was happening but seems to of fixed it's self.
