### ISSUE TITLE
Inner size

### ISSUE THREAD

**Issue by Franks3dShop** [Ultimaker/Cura#2943]
Hi, the problem I have come up with, say I print a cube of 20mm x 20mm x 20mm and I make a hole in the middle of 10mm vertically, on the printed part the hole is 0.4mm smaller.

Is this normal behaviour or I'm I doing something wrong?

Thanks.

**Comment by nallath** [comment]
Yep, this can happen. Your material can shrink, some settings aren't correctly compensating, etc. This is something that we are trying to improve, but it's quite hard to do this for all cases.

**Comment by Ghostkeeper** [comment]
You could also try the Post Stretch Script post-processing script. It's explicitly meant to compensate for this sort of thing.
