### ISSUE TITLE
new 3.1 prints items several layers off the raft

### ISSUE THREAD

**Issue by conroymp** [Ultimaker/Cura#2944]
Several support layers will print, but the first model layer is not over support and off the raft many times the  air gap.  Brim and skirt are fine.  Was in 3.0 as well.  

By layer, prints raft (3 layers), 2 layers of support, then piece (1 layer), then starts printing both on layer 8.

**Comment by nallath** [comment]
Could you share projects in which this happens? This is not enough info for us to pick it up.

**Comment by conroymp** [comment]
Jamie,

Sure, that attached file, when printed on its side, on a raft caused the problem.

Mike


Sent from Mail for Windows 10

**Comment by nallath** [comment]
You only sent a mail, which fails with attachments on github. Could you please upload it via github?

**Comment by Ghostkeeper** [comment]
Here's what happens with default settings on an Ultimaker 3 (layer height 0.1mm, raft air gap 0.3mm):

* 4 raft layers.
* 4 layers of only support (seems to be 1 layer too many).
* The rest onwards is model+support.

**Comment by conroymp** [comment]
What Ghostkeeper said.   

Seems related to the first layer, elephant foot scaling.  Cannot prove it though.   Take the attached file, place the item on its side, on a raft, and slice.  Look at the results.  There will be a missing layer for a long edge.  I cannot install cura on the machine I have at this time.  

[Fence Latch.zip](https://github.com/Ultimaker/Cura/files/1657225/Fence.Latch.zip)

**Comment by RagingRyno** [comment]
I'm having the same issue atm, did you find a fix for it?

**Comment by Ghostkeeper** [comment]
I don't think we fixed this, no.

**Comment by ianpaschal** [comment]
No, it was the OP who closed it. @RagingRyno are you still experiencing this? If so, I will reopen this. (Would rather reopen than create a new issue.)
