### ISSUE TITLE
Update to Cura 3.0.4 wrongfully changes material diameter

### ISSUE THREAD

**Issue by couka** [Ultimaker/Cura#2946]
I just updated from Cura 2.x.x to 3.0.4 and noticed serious underextrusion.
I found that the material diameter for my machine (Anet A8) was wrongfully changed from 1.75 to 2.85mm for no reason.

A working quick fix for already exported gcode is setting the extrusion multiplier to 265% (assuming 100% was fine before)

**Comment by ChrisTerBeke** [comment]
Does changing the diameter back to 1.75 fix the issue as well? Not sure about the version upgrade itself as we don't test on any 3rd party machines.

**Comment by ChrisTerBeke** [comment]
Related to https://github.com/Ultimaker/Cura/issues/2922?

**Comment by LipuFei** [comment]
For reference, I have created a JIRA ticket for this: CURA-4708

**Comment by Ghostkeeper** [comment]
This is a duplicate of #2922.
