### ISSUE TITLE
Infill Mesh

### ISSUE THREAD

**Issue by novio8** [Ultimaker/Cura#2949]
Infill Mesh is Broken. 
Cura 2.7 is working, 3.1 is broken

Regards
Mario

**Comment by smartavionics** [comment]
Hi, how is it broken, it seems to be working for me:
![screenshot_2017-12-10_08-01-52](https://user-images.githubusercontent.com/585618/33803137-75cc2db2-dd80-11e7-8894-88d29ee6eb29.png)

**Comment by novio8** [comment]
I attached Image, there is no infill, no Top Layer
![1](https://user-images.githubusercontent.com/29116262/33805253-ee90d312-ddb5-11e7-841a-110a29472bf8.png)

**Comment by smartavionics** [comment]
You need to make the mesh type specific to that object (special modes -> mesh type), have you done that?

**Comment by novio8** [comment]
second image using Infill Mesh
![2](https://user-images.githubusercontent.com/29116262/33805298-c5421380-ddb6-11e7-9fe2-47408923621c.png)

**Comment by smartavionics** [comment]
OK, I can see that is infill mesh.

**Comment by smartavionics** [comment]
That model that you have selected to be infill mesh, is solid, isn't it? If it was hollow then it won't be filled with infill.

**Comment by novio8** [comment]
Am I doing something wrong ?

**Comment by novio8** [comment]
It is a solid no naked edges, no non man-fold edges

**Comment by smartavionics** [comment]
Just noticed that you have some very weird shell lines here:

![screenshot_2017-12-10_13-37-02](https://user-images.githubusercontent.com/585618/33805350-46cea7ea-ddaf-11e7-8efe-9fd56c89827c.png)

Look at those red lines that converge towards the top right of the image, their not right!

**Comment by smartavionics** [comment]
Hah!, you have spiralize enabled????

**Comment by smartavionics** [comment]
No problem, please close the issue when you are happy there is not a real problem, cheers!
