### ISSUE TITLE
gcode

### ISSUE THREAD

**Issue by ve3sqb** [Ultimaker/Cura#2951]
can not open edit gcode in 3.1 stable

**Comment by ChrisTerBeke** [comment]
Can you be more specific? Which menu are you trying to open?

**Comment by ve3sqb** [comment]
In the extensions tab,
post processing, Modify g-code.

**Comment by fieldOfView** [comment]
As a workaround, can you try using the cursor keys and enter to navigate the menu?

**Comment by ve3sqb** [comment]
cursor keys work

**Comment by Ghostkeeper** [comment]
It looks like this is a duplicate of https://github.com/Ultimaker/Cura/issues/1940
