### ISSUE TITLE
Cura 3.1.0 not showing "Material View"

### ISSUE THREAD

**Issue by claude1000** [Ultimaker/Cura#2955]
Cura 3.1.0 not showing "Material View"

**Comment by fieldOfView** [comment]
Needs more info. What printer are you using, what do you call "Material View"?

**Comment by claude1000** [comment]
Ultimaker 3  


![layer view](https://user-images.githubusercontent.com/33101288/33808759-05a8aff8-ddec-11e7-809b-f02449cd1025.jpg)

Cura 3.1
- computer at home : can't see material color 
- computer at my job : I see  material color  (see attached picture)

**Comment by ChrisTerBeke** [comment]
Are they both the same OS and version? Do they have the same Cura machine configuration?

**Comment by Ghostkeeper** [comment]
I can't reproduce this. "Material Color" is an option in the "Color scheme" drop-down and when selected it properly displays the colours of the current materials.

**Comment by ChrisTerBeke** [comment]
No new info added, cannot reproduce. Closing.
