### ISSUE TITLE
how to resolved the unwanted lines on surface

### ISSUE THREAD

**Issue by claude1000** [Ultimaker/Cura#2956]
how to resolved the unwanted lines on surface

https://ultimaker.com/en/community/52344-unwanted-lines-on-surface

**Comment by smartavionics** [comment]
Did you try those settings I gave you on the forum? Perhaps they will provide a solution to your problem?

**Comment by claude1000** [comment]
I launch to day a print with your setup tomorrow I will return back to see 
I will inform you if it's resolved
rgs
Claude

**Comment by smartavionics** [comment]
Maybe related to https://github.com/Ultimaker/CuraEngine/issues/625

**Comment by Ghostkeeper** [comment]
I think I remember that we won't z-hop or retract for very small travel moves, smaller than 2 line widths or so. Maybe that could be what's happening here.

**Comment by ianpaschal** [comment]
Didn't hear back from OP for 6 months so closing.
