### ISSUE TITLE
hole

### ISSUE THREAD

**Issue by carleas** [Ultimaker/Cura#2959]
hello, 

i have a problem when i'm go to print a figure with one central hole.
In the model the figure have this, but when i print or i put the layer view the printer print all and the hole disappears.

What its the possible problem?

Tanks.

![image](https://user-images.githubusercontent.com/34423772/33808481-842ed532-dde7-11e7-9f91-6bb984ab540c.png)

![image](https://user-images.githubusercontent.com/34423772/33808485-8da1d1fa-dde7-11e7-8c23-05c2f397f580.png)

**Comment by Vandrasc** [comment]
Hi @carleas, could you attach your file/model here so we can give it a try? I loaded different models but I did not encounter this issue.
As a workaround, you could set your Top Layers to 0 ( CustomTab/Shell/TopLayers )
Thank you!

**Comment by carleas** [comment]
Hi! I send a E-mail with de model.

I’m waiting for the Solution.

Tanks

**Comment by nallath** [comment]
This is probably because your model is not manyfold. Check the model in x-ray. If there are red parts visible, the model has issues.

**Comment by carleas** [comment]
Hi, tanks for your answer,

I draw another model and i check in x-Ray, the problem it's the same.
I have in 2 diferent dimencions and the problem persist.

Plis have me a solution. I wanted to do it for a chrismas gift.


[image: Imatge inserida 2] [image: Imatge inserida 3][image: Imatge
inserida 5]

2017-12-19 16:22 GMT+01:00 Jaime van Kessel <notifications@github.com>:

**Comment by Ghostkeeper** [comment]
You said you sent an e-mail with the model. Where did you send it to? Maybe you could put it in a .zip and upload it here on Github?

**Comment by Ghostkeeper** [comment]
You could try fixing the model in MeshLab.
