### ISSUE TITLE
Nozzle offset cannot be set correctly

### ISSUE THREAD

**Issue by PatSmith1969** [Ultimaker/Cura#2963]
I have a chimera print head. I need to set nozzle 2 exactly 18mm off-set on the X axis. When I do so, it changes BOTH nozzles to 18mm off-set in the printer properties page. Setting Nozzle 1 back to 0 offset, changes BOTH nozzles to 0 off-set. 

I am using Cura 3.1.0 on a windows 10 machine. The printer is a d-bot. Cura did not do this in version 2.7 which was the version I had previous to this (it had other problems however).

**Comment by ChrisTerBeke** [comment]
Hi. Did you use the 3.1 beta version before using the stable? If so, try removing the 3.1 user data folder and then start the 3.1 stable. If not, please let us know so we can investigate!

**Comment by an-tech** [comment]
Same problem. I've used 3.1 beta. Tried delete data in users/userfolder/appdata/local/cura3.1 and reinstall with no success

**Comment by an-tech** [comment]
Workaround: You can set extruder2 as active. Then you can change values.

**Comment by AlfredVischermann** [comment]
I've got the same problem using Cure 3.1, 
setting extruder 2 as the active one didn't work for me

**Comment by an-tech** [comment]
Exactly. It's saving values but it appears in both tabs ext1 and ext2. When you change to extruder1 it shows ext1 values also in both tabs. Not a big problem but watch out for another bug when using ext2 supports #2976.

**Comment by ChrisTerBeke** [comment]
This will be fixed in the next release (3.2), of which the beta is planned in January.
