### ISSUE TITLE
Wall number makes diferent infill

### ISSUE THREAD

**Issue by ciberwizz** [Ultimaker/Cura#2977]
Using the same settings only diferent wall thickness creates very diferent infill. Next Layer will print in mid-air.

![screenshot from 2017-12-14 00 16 05](https://user-images.githubusercontent.com/288056/33969292-5b20cb76-e064-11e7-8bf4-01c53da7c826.png)
![screenshot from 2017-12-14 00 16 23](https://user-images.githubusercontent.com/288056/33969293-5b42f73c-e064-11e7-85b3-0a00ff7ce329.png)

**Comment by Ghostkeeper** [comment]
That's not infill, that's skin. Because you reduced the number of walls, there is more of the inside being exposed to air at the top and it needs to create more skin. Or am I seeing this wrong? It's a bit hard to see, and I also don't see anything that would really print in mid-air.

**Comment by ianpaschal** [comment]
Needs more info but never got it.
