### ISSUE TITLE
REQUEST: Double layer height option for infill and supports

### ISSUE THREAD

**Issue by jimb15122** [Ultimaker/Cura#2981]
Please provide an option to print infill and supports only on even numbered layers, but print in double layer height.  This option would be disabled/ignored if normal layer height is > 1/2 of the max supported height.  This would halve support/infill print time without sacrificing quality.
Perhaps the option should only affect layers 3 and above, so as to not effect adhesion and the possibly thicker first layer height.

**Comment by ChrisTerBeke** [comment]
These already exist... They're called "infill layer thickness" and "support infill layer thickness". Both keep in mind that bottom and top should be printed normally to get good adhesion and surface quality.
