### ISSUE TITLE
Extruder Preheater

### ISSUE THREAD

**Issue by azeemiqbal123** [Ultimaker/Cura#2989]
There is no option to preheat the extruder. When I click on the print button it starts heating the bed where there is no ability in my printer version of heating the bed. I need an option to directly heating and loading the extruder and starting to print.

**Comment by fieldOfView** [comment]
I’ll try adding that in time for Cura 3.2

**Comment by azeemiqbal123** [comment]
Please do! It has been a really painful experience trying to go about it. I
had to download 14.0.7 version to make that happen.

**Comment by Ghostkeeper** [comment]
Have to be a bit careful with this though because the plastic filament could degrade.

**Comment by Ghostkeeper** [comment]
This was removed from our planning by our project manager. It has no priority right now.

**Comment by fieldOfView** [comment]
But... there’s a PR for it!

**Comment by Ghostkeeper** [comment]
Oh, yes, here it is: https://github.com/Ultimaker/Cura/pull/3144

Seems we had two tickets about it. CURA-4949 is still in there.

**Comment by diegopradogesto** [comment]
The PR was merged so I close this issue.
