### ISSUE TITLE
Feature Request: More Settings in Pref->Material->Filament

### ISSUE THREAD

**Issue by damon-atkins** [Ultimaker/Cura#2990]
This idea is for the Public Domain.  Some times its nice to printer hotter bed for the first layer and then allow the bed to cool down a bit to a different temperature.

**Comment by smartavionics** [comment]
Err, it can already do that.

**Comment by damon-atkins** [comment]
I'll look harder for the option.

**Comment by damon-atkins** [comment]
Setting should be under materials of the filament setting, it has bed temp but does not have first layer bed temp (however it is in with all the other settings)

**Comment by Thisismydigitalself** [comment]
![ice_screenshot_20171216-184322](https://user-images.githubusercontent.com/30949968/34072495-15b098ee-e291-11e7-831e-859cbbc8d831.png)

**Comment by damon-atkins** [comment]
The screen shot is not from where you define the material. Under Preferences -> Materials

![image](https://user-images.githubusercontent.com/9368124/34075433-09666de0-e31b-11e7-991d-2066ead2431a.png)

Should be a lot more settings here, and then what you have shown show be just a view or have an option to save it back to the material setting in preferences.

**Comment by filipgoc** [comment]
That's a fair point @damon-atkins; there's no user-facing reason not to have 1st layer temp as a part of the fallback material defaults.

Trouble is, the material definition (XML) supports only a limited number of settings - not the full shebang.

I first ran into this with granular fan speed control per material definitions a long time ago, but now the the team already has some improvements in this department on their internal tracker ([mentioned in this issue](https://github.com/Ultimaker/Cura/issues/1135)), so my guess is this could reasonably soon be addressed.

**Comment by damon-atkins** [comment]
I assume the idea of Under "Preferences -> Materials" is that you get a new role and do some test prints to work out the settings and the "real thickness" and then create a profile for it.  Maybe even give it a number as well and label the role of filament.  The main interface should just be a viewer, or have adjustments which are saved back to the preference->material settings.  Maybe allow two lines for the description of the material and always show it even if the search does not match. (Maybe section heading should always be shown if not already)

**Comment by damon-atkins** [comment]
Closed, handed over to https://github.com/Ultimaker/Cura/issues/1135
