### ISSUE TITLE
Cura 3.1 is not launching on Win 7

### ISSUE THREAD

**Issue by labrador21** [Ultimaker/Cura#3001]
Hello,

I'am trying to install Cura 3.1 on a laptop with windows 7(64bit). Although the installation process finishes, cura can not be started.
I already installed the new update "Cura-3.2.0-master.20171211145115-win64.exe" from #2916 but this doesn't work, too.

**The following report.wer-file can be found on the computer after the installation process:**

Version=1
EventType=APPCRASH
EventTime=131580212030874823
ReportType=2
Consent=1
UploadTime=131580212031484858
ReportIdentifier=b30beec3-e374-11e7-a203-c80aa9954bf4
IntegratorReportIdentifier=b30beec2-e374-11e7-a203-c80aa9954bf4
Response.BucketId=604453047
Response.BucketTable=28
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=Cura.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=0.0.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=59ad373a
Sig[3].Name=Fehlermodulname
Sig[3].Value=atio6axx.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=6.14.10.9704
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=4b8ddfd7
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=0000000000d28ffb
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=6.1.7601.2.1.0.768.3
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=6199
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=619904affd4215a865c62e683071933d
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=8bd8
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=8bd87424258359e26be90bd5ce4bc1d2
UI[2]=C:\Program Files\Ultimaker Cura 3.2\Cura.exe
UI[3]=Cura.exe funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=C:\Program Files\Ultimaker Cura 3.2\Cura.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[5]=C:\Windows\system32\GDI32.dll
LoadedModule[6]=C:\Windows\system32\USER32.dll
LoadedModule[7]=C:\Windows\system32\LPK.dll
LoadedModule[8]=C:\Windows\system32\USP10.dll
LoadedModule[9]=C:\Windows\system32\msvcrt.dll
LoadedModule[10]=C:\Program Files\Ultimaker Cura 3.2\python35.dll
LoadedModule[11]=C:\Windows\system32\WS2_32.dll
LoadedModule[12]=C:\Windows\system32\RPCRT4.dll
LoadedModule[13]=C:\Windows\system32\NSI.dll
LoadedModule[14]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[15]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[16]=C:\Windows\system32\VCRUNTIME140.dll
LoadedModule[17]=C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[18]=C:\Windows\system32\ucrtbase.DLL
LoadedModule[19]=C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
LoadedModule[20]=C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll
LoadedModule[21]=C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll
LoadedModule[22]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
LoadedModule[23]=C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
LoadedModule[24]=C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll
LoadedModule[25]=C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[26]=C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[27]=C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[28]=C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[29]=C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[30]=C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[31]=C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[32]=C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[33]=C:\Windows\system32\api-ms-win-crt-process-l1-1-0.dll
LoadedModule[34]=C:\Windows\system32\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[35]=C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[36]=C:\Windows\system32\IMM32.DLL
LoadedModule[37]=C:\Windows\system32\MSCTF.dll
LoadedModule[38]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[39]=C:\Windows\system32\rsaenh.dll
LoadedModule[40]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[41]=C:\Program Files\Ultimaker Cura 3.2\python3.dll
LoadedModule[42]=C:\Program Files\Ultimaker Cura 3.2\Arcus.pyd
LoadedModule[43]=C:\Program Files\Ultimaker Cura 3.2\sip.pyd
LoadedModule[44]=C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[45]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtNetwork.pyd
LoadedModule[46]=C:\Program Files\Ultimaker Cura 3.2\Qt5Network.dll
LoadedModule[47]=C:\Program Files\Ultimaker Cura 3.2\Qt5Core.dll
LoadedModule[48]=C:\Windows\system32\SHELL32.dll
LoadedModule[49]=C:\Windows\system32\ole32.dll
LoadedModule[50]=C:\Windows\system32\MPR.dll
LoadedModule[51]=C:\Windows\system32\WINMM.dll
LoadedModule[52]=C:\Program Files\Ultimaker Cura 3.2\MSVCP140.dll
LoadedModule[53]=C:\Windows\system32\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[54]=C:\Windows\system32\DNSAPI.dll
LoadedModule[55]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[56]=C:\Windows\system32\WINNSI.DLL
LoadedModule[57]=C:\Windows\system32\CRYPT32.dll
LoadedModule[58]=C:\Windows\system32\MSASN1.dll
LoadedModule[59]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtCore.pyd
LoadedModule[60]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtQml.pyd
LoadedModule[61]=C:\Program Files\Ultimaker Cura 3.2\Qt5Qml.dll
LoadedModule[62]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtWidgets.pyd
LoadedModule[63]=C:\Program Files\Ultimaker Cura 3.2\Qt5Widgets.dll
LoadedModule[64]=C:\Program Files\Ultimaker Cura 3.2\Qt5Gui.dll
LoadedModule[65]=C:\Windows\system32\UxTheme.dll
LoadedModule[66]=C:\Windows\system32\dwmapi.dll
LoadedModule[67]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtGui.pyd
LoadedModule[68]=C:\Program Files\Ultimaker Cura 3.2\numpy.core.multiarray.pyd
LoadedModule[69]=C:\Program Files\Ultimaker Cura 3.2\mkl_rt.dll
LoadedModule[70]=C:\Program Files\Ultimaker Cura 3.2\numpy.core.umath.pyd
LoadedModule[71]=C:\Program Files\Ultimaker Cura 3.2\_ctypes.pyd
LoadedModule[72]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[73]=C:\Program Files\Ultimaker Cura 3.2\_bz2.pyd
LoadedModule[74]=C:\Program Files\Ultimaker Cura 3.2\_hashlib.pyd
LoadedModule[75]=C:\Program Files\Ultimaker Cura 3.2\numpy.linalg.lapack_lite.pyd
LoadedModule[76]=C:\Program Files\Ultimaker Cura 3.2\numpy.linalg._umath_linalg.pyd
LoadedModule[77]=C:\Program Files\Ultimaker Cura 3.2\numpy.fft.fftpack_lite.pyd
LoadedModule[78]=C:\Program Files\Ultimaker Cura 3.2\numpy.random.mtrand.pyd
LoadedModule[79]=C:\Program Files\Ultimaker Cura 3.2\scipy._lib._ccallback_c.pyd
LoadedModule[80]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse._sparsetools.pyd
LoadedModule[81]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse._csparsetools.pyd
LoadedModule[82]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse.csgraph._shortest_path.pyd
LoadedModule[83]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse.csgraph._tools.pyd
LoadedModule[84]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse.csgraph._traversal.pyd
LoadedModule[85]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse.csgraph._min_spanning_tree.pyd
LoadedModule[86]=C:\Program Files\Ultimaker Cura 3.2\scipy.sparse.csgraph._reordering.pyd
LoadedModule[87]=C:\Program Files\Ultimaker Cura 3.2\scipy.spatial.ckdtree.pyd
LoadedModule[88]=C:\Program Files\Ultimaker Cura 3.2\scipy.spatial.qhull.pyd
LoadedModule[89]=C:\Program Files\Ultimaker Cura 3.2\scipy.spatial._voronoi.pyd
LoadedModule[90]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg._fblas.pyd
LoadedModule[91]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg._flapack.pyd
LoadedModule[92]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg._flinalg.pyd
LoadedModule[93]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg._solve_toeplitz.pyd
LoadedModule[94]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg._decomp_update.pyd
LoadedModule[95]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg.cython_blas.pyd
LoadedModule[96]=C:\Program Files\Ultimaker Cura 3.2\scipy.linalg.cython_lapack.pyd
LoadedModule[97]=C:\Program Files\Ultimaker Cura 3.2\scipy.spatial._distance_wrap.pyd
LoadedModule[98]=C:\Program Files\Ultimaker Cura 3.2\scipy.spatial._hausdorff.pyd
LoadedModule[99]=C:\Program Files\Ultimaker Cura 3.2\PyQt5.QtQuick.pyd
LoadedModule[100]=C:\Program Files\Ultimaker Cura 3.2\Qt5Quick.dll
LoadedModule[101]=C:\Program Files\Ultimaker Cura 3.2\unicodedata.pyd
LoadedModule[102]=C:\Windows\system32\profapi.dll
LoadedModule[103]=C:\Program Files\Ultimaker Cura 3.2\platforms\qwindows.dll
LoadedModule[104]=C:\Windows\system32\opengl32.dll
LoadedModule[105]=C:\Windows\system32\GLU32.dll
LoadedModule[106]=C:\Windows\system32\DDRAW.dll
LoadedModule[107]=C:\Windows\system32\DCIMAN32.dll
LoadedModule[108]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[109]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[110]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[111]=C:\Windows\system32\atig6pxx.dll
LoadedModule[112]=C:\Windows\system32\atio6axx.dll
LoadedModule[113]=C:\Windows\system32\VERSION.dll
LoadedModule[114]=C:\Windows\system32\atig6txx.dll
LoadedModule[115]=C:\Windows\system32\atiadlxx.dll
LoadedModule[116]=C:\Windows\system32\WINTRUST.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=604453047/nBucketTable=28/nResponse=1/n
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=Cura.exe
AppPath=C:\Program Files\Ultimaker Cura 3.2\Cura.exe

**And this stderr.log-file can be found in the cura-folder:**

Fatal Python error: Segmentation fault

Current thread 0x00001f2c (most recent call first):
  File "X:\master\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 29 in setContext
  File "X:\master\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 104 in detectBestOpenGLVersion
  File "X:\master\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 77 in __init__
  File "X:\master\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 212 in __init__
  File "X:\master\build\inst\lib\python3.5\site-packages\UM\Application.py", line 330 in getInstance
  File "X:\master\build\inst\bin\cura_app.py", line 85 in <module>
  File "Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load

**Any help is appreciated!**

**Comment by LipuFei** [comment]
Hi @labrador21 that "Cura-3.2.0-master.20171211145115-win64.exe" from #2916 is not a stable version and it doesn't contain a working fix for network storage on Windows.

Could you Remove this unstable version and post the log file you get with 3.1? Thanks!

And please also remove the following folders if they exist, otherwise when a future 3.2 release actually arrives, there might be problems with that.
`C:\Users\<your-username>\AppData\Roaming\cura\3.2`
`C:\Users\<your-username>\AppData\Roaming\cura\master`
`C:\Users\<your-username>\AppData\Local\cura\3.2`
`C:\Users\<your-username>\AppData\Local\cura\master`

**Comment by labrador21** [comment]
Hi LipuFei,

thanks for your quick response.
I uninstalled the "Cura-3.2.0-master.20171211145115-win64.exe" and  removed all files you mentioned above. After that I installed Cura 3.1.0. While the installation window was shown, the programm stayed quite a long time at the following position:

**Starte: "C:\Program Files\Ultimaker Cura 3.1\vcredist_x64.exe" /install /quiet /norestart**

Allthough the finished window was shown after a while, cura didn't start at all.
I found the following files after the installation on my laptop:

**Report.wer**
Version=1
EventType=APPCRASH
EventTime=131580957144638142
ReportType=2
Consent=1
UploadTime=131580957145328182
ReportIdentifier=2f3e8900-e422-11e7-a28d-c80aa9954bf4
IntegratorReportIdentifier=2f3e88ff-e422-11e7-a28d-c80aa9954bf4
Response.BucketId=604453047
Response.BucketTable=28
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=Cura.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=0.0.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=59ad373a
Sig[3].Name=Fehlermodulname
Sig[3].Value=atio6axx.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=6.14.10.9704
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=4b8ddfd7
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=0000000000d28ffb
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=6.1.7601.2.1.0.768.3
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=6199
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=619904affd4215a865c62e683071933d
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=ab74
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=ab749ae48f27a682ed705821884e2a92
UI[2]=C:\Program Files\Ultimaker Cura 3.1\Cura.exe
UI[3]=Cura.exe funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=C:\Program Files\Ultimaker Cura 3.1\Cura.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[5]=C:\Windows\system32\GDI32.dll
LoadedModule[6]=C:\Windows\system32\USER32.dll
LoadedModule[7]=C:\Windows\system32\LPK.dll
LoadedModule[8]=C:\Windows\system32\USP10.dll
LoadedModule[9]=C:\Windows\system32\msvcrt.dll
LoadedModule[10]=C:\Program Files\Ultimaker Cura 3.1\python35.dll
LoadedModule[11]=C:\Windows\system32\WS2_32.dll
LoadedModule[12]=C:\Windows\system32\RPCRT4.dll
LoadedModule[13]=C:\Windows\system32\NSI.dll
LoadedModule[14]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[15]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[16]=C:\Windows\system32\VCRUNTIME140.dll
LoadedModule[17]=C:\Windows\system32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[18]=C:\Windows\system32\ucrtbase.DLL
LoadedModule[19]=C:\Windows\system32\api-ms-win-core-timezone-l1-1-0.dll
LoadedModule[20]=C:\Windows\system32\api-ms-win-core-file-l2-1-0.dll
LoadedModule[21]=C:\Windows\system32\api-ms-win-core-localization-l1-2-0.dll
LoadedModule[22]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.dll
LoadedModule[23]=C:\Windows\system32\api-ms-win-core-processthreads-l1-1-1.dll
LoadedModule[24]=C:\Windows\system32\api-ms-win-core-file-l1-2-0.dll
LoadedModule[25]=C:\Windows\system32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[26]=C:\Windows\system32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[27]=C:\Windows\system32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[28]=C:\Windows\system32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[29]=C:\Windows\system32\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[30]=C:\Windows\system32\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[31]=C:\Windows\system32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[32]=C:\Windows\system32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[33]=C:\Windows\system32\api-ms-win-crt-process-l1-1-0.dll
LoadedModule[34]=C:\Windows\system32\api-ms-win-crt-conio-l1-1-0.dll
LoadedModule[35]=C:\Windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[36]=C:\Windows\system32\IMM32.DLL
LoadedModule[37]=C:\Windows\system32\MSCTF.dll
LoadedModule[38]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[39]=C:\Windows\system32\rsaenh.dll
LoadedModule[40]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[41]=C:\Program Files\Ultimaker Cura 3.1\python3.dll
LoadedModule[42]=C:\Program Files\Ultimaker Cura 3.1\Arcus.pyd
LoadedModule[43]=C:\Program Files\Ultimaker Cura 3.1\sip.pyd
LoadedModule[44]=C:\Windows\system32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[45]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtNetwork.pyd
LoadedModule[46]=C:\Program Files\Ultimaker Cura 3.1\Qt5Network.dll
LoadedModule[47]=C:\Program Files\Ultimaker Cura 3.1\Qt5Core.dll
LoadedModule[48]=C:\Windows\system32\SHELL32.dll
LoadedModule[49]=C:\Windows\system32\ole32.dll
LoadedModule[50]=C:\Windows\system32\MPR.dll
LoadedModule[51]=C:\Windows\system32\WINMM.dll
LoadedModule[52]=C:\Program Files\Ultimaker Cura 3.1\MSVCP140.dll
LoadedModule[53]=C:\Windows\system32\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[54]=C:\Windows\system32\DNSAPI.dll
LoadedModule[55]=C:\Windows\system32\IPHLPAPI.DLL
LoadedModule[56]=C:\Windows\system32\WINNSI.DLL
LoadedModule[57]=C:\Windows\system32\CRYPT32.dll
LoadedModule[58]=C:\Windows\system32\MSASN1.dll
LoadedModule[59]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtCore.pyd
LoadedModule[60]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtQml.pyd
LoadedModule[61]=C:\Program Files\Ultimaker Cura 3.1\Qt5Qml.dll
LoadedModule[62]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtWidgets.pyd
LoadedModule[63]=C:\Program Files\Ultimaker Cura 3.1\Qt5Widgets.dll
LoadedModule[64]=C:\Program Files\Ultimaker Cura 3.1\Qt5Gui.dll
LoadedModule[65]=C:\Windows\system32\UxTheme.dll
LoadedModule[66]=C:\Windows\system32\dwmapi.dll
LoadedModule[67]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtGui.pyd
LoadedModule[68]=C:\Program Files\Ultimaker Cura 3.1\numpy.core.multiarray.pyd
LoadedModule[69]=C:\Program Files\Ultimaker Cura 3.1\mkl_rt.dll
LoadedModule[70]=C:\Program Files\Ultimaker Cura 3.1\numpy.core.umath.pyd
LoadedModule[71]=C:\Program Files\Ultimaker Cura 3.1\_ctypes.pyd
LoadedModule[72]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[73]=C:\Program Files\Ultimaker Cura 3.1\_bz2.pyd
LoadedModule[74]=C:\Program Files\Ultimaker Cura 3.1\_hashlib.pyd
LoadedModule[75]=C:\Program Files\Ultimaker Cura 3.1\numpy.linalg.lapack_lite.pyd
LoadedModule[76]=C:\Program Files\Ultimaker Cura 3.1\numpy.linalg._umath_linalg.pyd
LoadedModule[77]=C:\Program Files\Ultimaker Cura 3.1\numpy.fft.fftpack_lite.pyd
LoadedModule[78]=C:\Program Files\Ultimaker Cura 3.1\numpy.random.mtrand.pyd
LoadedModule[79]=C:\Program Files\Ultimaker Cura 3.1\scipy._lib._ccallback_c.pyd
LoadedModule[80]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse._sparsetools.pyd
LoadedModule[81]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse._csparsetools.pyd
LoadedModule[82]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse.csgraph._shortest_path.pyd
LoadedModule[83]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse.csgraph._tools.pyd
LoadedModule[84]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse.csgraph._traversal.pyd
LoadedModule[85]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse.csgraph._min_spanning_tree.pyd
LoadedModule[86]=C:\Program Files\Ultimaker Cura 3.1\scipy.sparse.csgraph._reordering.pyd
LoadedModule[87]=C:\Program Files\Ultimaker Cura 3.1\scipy.spatial.ckdtree.pyd
LoadedModule[88]=C:\Program Files\Ultimaker Cura 3.1\scipy.spatial.qhull.pyd
LoadedModule[89]=C:\Program Files\Ultimaker Cura 3.1\scipy.spatial._voronoi.pyd
LoadedModule[90]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg._fblas.pyd
LoadedModule[91]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg._flapack.pyd
LoadedModule[92]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg._flinalg.pyd
LoadedModule[93]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg._solve_toeplitz.pyd
LoadedModule[94]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg._decomp_update.pyd
LoadedModule[95]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg.cython_blas.pyd
LoadedModule[96]=C:\Program Files\Ultimaker Cura 3.1\scipy.linalg.cython_lapack.pyd
LoadedModule[97]=C:\Program Files\Ultimaker Cura 3.1\scipy.spatial._distance_wrap.pyd
LoadedModule[98]=C:\Program Files\Ultimaker Cura 3.1\scipy.spatial._hausdorff.pyd
LoadedModule[99]=C:\Program Files\Ultimaker Cura 3.1\PyQt5.QtQuick.pyd
LoadedModule[100]=C:\Program Files\Ultimaker Cura 3.1\Qt5Quick.dll
LoadedModule[101]=C:\Program Files\Ultimaker Cura 3.1\unicodedata.pyd
LoadedModule[102]=C:\Windows\system32\profapi.dll
LoadedModule[103]=C:\Program Files\Ultimaker Cura 3.1\platforms\qwindows.dll
LoadedModule[104]=C:\Windows\system32\opengl32.dll
LoadedModule[105]=C:\Windows\system32\GLU32.dll
LoadedModule[106]=C:\Windows\system32\DDRAW.dll
LoadedModule[107]=C:\Windows\system32\DCIMAN32.dll
LoadedModule[108]=C:\Windows\system32\SETUPAPI.dll
LoadedModule[109]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[110]=C:\Windows\system32\DEVOBJ.dll
LoadedModule[111]=C:\Windows\system32\atig6pxx.dll
LoadedModule[112]=C:\Windows\system32\atio6axx.dll
LoadedModule[113]=C:\Windows\system32\VERSION.dll
LoadedModule[114]=C:\Windows\system32\atig6txx.dll
LoadedModule[115]=C:\Windows\system32\atiadlxx.dll
LoadedModule[116]=C:\Windows\system32\WINTRUST.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=604453047/nBucketTable=28/nResponse=1/n
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=Cura.exe
AppPath=C:\Program Files\Ultimaker Cura 3.1\Cura.exe

**stderr.log**
Fatal Python error: Segmentation fault
Current thread 0x000015ec (most recent call first):
  File "X:\3.1\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 29 in setContext
  File "X:\3.1\build\inst\lib\python3.5\site-packages\UM\View\GL\OpenGLContext.py", line 104 in detectBestOpenGLVersion
  File "X:\3.1\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 73 in __init__
  File "X:\3.1\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 209 in __init__
  File "X:\3.1\build\inst\lib\python3.5\site-packages\UM\Application.py", line 323 in getInstance
  File "X:\3.1\build\inst\bin\cura_app.py", line 82 in <module>
  File "Console.py", line 24 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "__startup__.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
  File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load


**Thanks for your help in advance!**

**Comment by LipuFei** [comment]
Hi @labrador21 , I'm not sure what happened, but it could be related to the graphics driver. Could you upgrade your graphics driver(s) to the latest version(s) and try again? Thanks

**Comment by labrador21** [comment]
Hi LipuFei, although I had the latest graphics driver installed, I deleted my grahic hardware and reinstalled it again. Nevertheless I couldn't start cura 3.1. After that I tried the different versions of cura. I had to go down to cura 2.5. This programm runs on my labtop. The main difference I recogniced is, that this version installs "visual studio 2010 redistibutable" and all newer programms install "visual studio 2015 redistibutable". Maybe this could be the reasion why cura 2.6 and all newer versions do not work on my computer.

**Comment by labrador21** [comment]
Hi @LipuFei  , after several trials with the newest drivers from my graphic card manufacturer with no results, I installed the latest drivers from the web page of my laptop manufacturer. Although this driver was older,  I now can start curo 3.1.
Many thanks for your hint!
