### ISSUE TITLE
model size wrong on cura 3.1

### ISSUE THREAD

**Issue by nathanieltsh** [Ultimaker/Cura#3003]
this seems to an issue on certain models below is a comparison between cura 3.1 and cura 15.04.6 
the value in cura 15 is the correct one with the design
![image](https://user-images.githubusercontent.com/34644772/34097297-9e47a8a4-e413-11e7-9dbe-000013792d1d.png)
![image](https://user-images.githubusercontent.com/34644772/34097332-c6db3f56-e413-11e7-8002-73543eecb84e.png)

is there a setting i missed out 
or is it a bug?

**Comment by alekseisasin** [comment]
We had some changes for model loading and it can be it is related to them. Can you check the measurements in AutoCad, SolidWorks?
