### ISSUE TITLE
[question] Creating and sharing profiles

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#3004]
Hello,

I have a question if I want to make a material for eg: PETG for UM2+ that has its own set of profiles is it best to make the files like these

- resouces
  - materials
    - colorfabb_petg.xml.fdm_material
  - quality
    - ultimaker2_plus
      - um2p_cf_petg_0.4_fast.inst.cfg
      - um2p_cf_petg_0.4_normal.inst.cfg

and in the inst.cfg files ref the material using the metadata tag 

`material = colorfabb_petg_ultimaker2_plus_0.4_mm`

if this is the right way of going about this is their any doc on what all the metadata vars do for eg looking at the ones already used their is 

`weight = -1` or `weight = 1`

What does weight mean as I noticed some of the quality profiles use a -1 and a 1

also for the version and setting_version what does that mean as they ones already their are set to a 4 is this just the version of the profile so Id use a 1?

**Comment by fieldOfView** [comment]
The "weight" metadata is only used for sorting the profile in lists.
The "setting_version" is used for compatibility with certain version of Cura. The current version of Cura requires the setting_version to be 4.

**Comment by ChrisRiddell** [comment]
if i have a couple colours 

eg 

colorfabb_petg_white.xml.fdm_material
colorfabb_petg_black.xml.fdm_material

How do I tell the quality files to be available to both what would I need to set my `material`` as as when I just had the one I done `material = colorfabb_petgeconomy_ultimaker2_plus_0.4_mm`

**Comment by nallath** [comment]
Cura has some fallback strategies. As you might have noticed, all our quality profiles refer to generic materials. If you have a specific material type selected (say blue PLA), it will first try to find a quality based on blue PLA. As there is no quality for blue PLA, it will try to find one for generic PLA, and use that.

**Comment by ChrisRiddell** [comment]
I have anther question is their an easier way to package and import these type of profiles that have a materiel and related quality files? as the only way I have found is getting the user to copy the files to the correct location in the C drive or add it to the OSX app package.

**Comment by fieldOfView** [comment]
You don’t have to add the files to the application folder, you can also drop them in the configuration folder. Having said that, a .curaresources package similar to the .curaplugin would be nice.

**Comment by ChrisRiddell** [comment]
configuration folder?

**Comment by ChrisRiddell** [comment]
Do I keep the directory structure? eg: resouces/** or do I put the materials and quality files just in AppData\Roaming\cura\3.1

**Comment by ChrisTerBeke** [comment]
We're thinking a lot currently about how to improve material/profile packages, resource paths and plugins that provide resources. I expect more details soon. We'll take these suggestions into consideration as well.

@Appesteijn input for us :)

**Comment by ChrisRiddell** [comment]
Is their a list of Keys that are available to use in the xml.fdm_material?

**Comment by ChrisTerBeke** [comment]
https://github.com/Ultimaker/Cura/blob/master/plugins/XmlMaterialProfile/XmlMaterialProfile.py#L943

**Comment by ChrisRiddell** [comment]
Anther suggestion for a .curaresources file is to make it possible not to just have material/profiles but also have optional printer def as well that would make it very powerful so printer manufacturers can make a full package for Cura if they choose not to submit it to be apart of Cura.

**Comment by fieldOfView** [comment]
... and themes, and postprocessing scripts

**Comment by ChrisRiddell** [comment]
Going to close this as my question has been answered and I'm guessing their is already internal talk about a curaresources package file.

**Comment by ianpaschal** [comment]
Thanks for helping keep things tidy @ChrisRiddell. There is indeed on-going internal discussions about how this sort of thing might work.
