### ISSUE TITLE
.25 gcode problem

### ISSUE THREAD

**Issue by tclancey** [Ultimaker/Cura#3006]
I'm not a gcode/ultimaker person so I don't know where the problems is, but any object sliced with the .25 nozzle selected does the following:
1 Heating bed....
2 Head moves to prime blob position.
3 Print finished.
4 Please remove print from buildplate.

But nothing happens between 2 and 3.

**Comment by nallath** [comment]
Have you looked at the layer view? It could be that it didn't even slice anything. If so, that might indicate that you have a non-manifold object. Could you share the model?
