### ISSUE TITLE
Non manifold objects crash.

### ISSUE THREAD

**Issue by tclancey** [Ultimaker/Cura#3008]
In the previous version any non manifold (or at least 'only surface') objects threw an error pop up message.  In the latest version the object fails to load, puts a big white form in the middle of the main form, no information, then crashes to desktop.

**Comment by nallath** [comment]
Could you share logs or models?

**Comment by Ghostkeeper** [comment]
The difference is that the crash reporter (error pop up message) was broken in 3.1. This has been fixed in version 3.2.

But still it shouldn't crash on non-manifold objects.

**Comment by ianpaschal** [comment]
Reporter has not provided more information for more than 2 weeks, so closing.
