### ISSUE TITLE
Not syncing UM3 materials

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#3010]
Cura 3.1.0
Linux AppImage

Latest stable firmware (4-12)

Cura wouldn't see the materials on the machine had changed until I restarted Cura.
Even clicking [Activate Configuration] didn't help.

- I had PLA (white) in the left extruder and PLA (generic) in the right one.
- Open Cura
- Switch materials around physically on the printer using the menu and make sure the right material is recognized on the right slot.
- Go back to computer
- Trying a lot of stuff to get Cura to sync the materials automatically

[ultimakersystem-ccbdd300017e.4.1.4.20171204.config.tar.gz](https://github.com/Ultimaker/Cura/files/1568588/ultimakersystem-ccbdd300017e.4.1.4.20171204.config.tar.gz)
[ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-4.log.gz](https://github.com/Ultimaker/Cura/files/1568589/ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-4.log.gz)
[ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-3.log.gz](https://github.com/Ultimaker/Cura/files/1568590/ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-3.log.gz)
[ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-2.log.gz](https://github.com/Ultimaker/Cura/files/1568591/ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-2.log.gz)
[ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-1.log.gz](https://github.com/Ultimaker/Cura/files/1568592/ultimakersystem-ccbdd300017e.4.1.4.20171204.boot-1.log.gz)
[ultimakersystem-ccbdd300017e.4.1.4.20171204.boot0.log.gz](https://github.com/Ultimaker/Cura/files/1568611/ultimakersystem-ccbdd300017e.4.1.4.20171204.boot0.log.gz)

[cura.log](https://github.com/Ultimaker/Cura/files/1568597/cura.log)

**Comment by BagelOrb** [comment]
Something weird happened

**Comment by ChrisTerBeke** [comment]
Are you connected to a CuraConnect host or slave machine?

**Comment by BagelOrb** [comment]
Host.

**Comment by nallath** [comment]
That's because it's hacked together. There is a re-write on the way.

**Comment by Ghostkeeper** [comment]
This feature was explicitly dropped, iirc. They'll put it back in, hopefully for Cura 3.2.

**Comment by ChrisTerBeke** [comment]
3.2 will not contain the rewrite, however syncing with the host still works in the old networking code. the rewrite will have new syncing options that are being determined right now.

**Comment by diegopradogesto** [comment]
Should this ticket be closed? The rewrite is already in, and we have the Configuration Sync Button feature for a long time now.

**Comment by BagelOrb** [comment]
idk

**Comment by Ghostkeeper** [comment]
This was about syncing materials from Cura to the printer. That is fixed in Cura version 3.5 if you have a firmware version of 5.2 or higher.
