### ISSUE TITLE
Printing time and estimated time left are non-functional within the "Monitor" tab

### ISSUE THREAD

**Issue by madmodder123** [Ultimaker/Cura#3025]
Application Version:
3.1.0

Platform:
Windows 10

3D Printer:
ANET A8

Steps to Reproduce:
1. Connect the printer to the PC via USB
2. Open Cura 3.1.0
3. Load any model into Cura
4. Select "Print via USB"
5. While on the "Monitor" tab, wait for the bed/hot end to heat up and start printing

Actual Results:
"Printing Time" and "Estimated time left" remain at 00:00:00 throughout the printing process.

Expected results:
Print time should increase over time, estimated time left should raise or lower accordingly.

Additional Information:
Estimated print time displays on the "Prepare" tab.
The "Printing" progress bar increases over time correctly.
I have had the same printer profile since Cura 2.8.x.
I could not find any other issues related to this on this GitHub.

**Comment by fieldOfView** [comment]
This has been fixed for Cura 3.2
