### ISSUE TITLE
When double color printing, how to cancel standby temperature, printing often needs to wait for temperature to rise to the specified temperature.

### ISSUE THREAD

**Issue by xc3dmaker** [Ultimaker/Cura#3027]
Application Version:

Platform:

Qt:

PyQt:

Display Driver:

Steps to Reproduce:

Actual Results:

Expected results:

Additional Information:

**Comment by ChrisTerBeke** [comment]
You can change the standby temperature in the custom settings. We recommend against it though as the current settings have been tested thoroughly.

**Comment by xc3dmaker** [comment]
The standby temperature is set at 210 degrees, and it will continue to wait and wait

**Comment by xc3dmaker** [comment]
The printing temperature is in accordance with the standby temperature

**Comment by ChrisTerBeke** [comment]
Which Cura version are you using?

**Comment by xc3dmaker** [comment]
cura 3.1





At 2017-12-21 18:32:46, "ChrisTerBeke" <notifications@github.com> wrote:


Which Cura version are you using?

**Comment by ChrisTerBeke** [comment]
Can you send a project file so we can debug this? You can export your whole workspace under file -> save as project. Then upload that file here (not via email but the GitHub interface).

**Comment by xc3dmaker** [comment]
At 2017-12-21 19:48:07, "ChrisTerBeke" <notifications@github.com> wrote:


Can you send a project file so we can debug this? You can export your whole workspace under file -> save as project. Then upload that file here (not via email but the GitHub interface).

**Comment by Ghostkeeper** [comment]
Attachments to e-mails that reply to Github notifications won't work. You need to actually go on the Github website and upload it there.

**Comment by Ghostkeeper** [comment]
If you want to eliminate the temperature changes, you need to remember to adjust the "Initial Printing Temperature" and "Final Printing Temperature" as well. Otherwise it will still cool.

It might be worth your while to improve the heating/cooling speed estimates for your printer type in the definition file, if you are technically inclined.
