### ISSUE TITLE
Cura, 3.04 and 3.1.0, wrong extruder temperature for PETG

### ISSUE THREAD

**Issue by joselauro** [Ultimaker/Cura#3044]
It is not 215ºC! The correct value is about 240ºC. I lost many printings until realised this.

**Comment by linuxglobal** [comment]
mine will stay at 210C for output gcode no matter what material is used..

**Comment by joselauro** [comment]
But do you print in PETG? 210, 215ºC is for PLA.

**Comment by linuxglobal** [comment]
no matter what material is selected, cura will display the correct 255C i request, yet when the PRUSA mk2 loads the gcode it will still warm up nozzle to 210. If i alter the bed temperature within cura, the value will correspond in the gcode bed temp.

**Comment by ChrisTerBeke** [comment]
Probably a duplicate of #1296. Fixed in next release.
