### ISSUE TITLE
Cura 3.1.0 MacOS 10.11.6 Incorrect Nozzle Temperatures not updated, always uses 210C, bed temp updates correctly.

### ISSUE THREAD

**Issue by linuxglobal** [Ultimaker/Cura#3045]
Issue occurs with all materials, the nozzle temperature will default to 210C in the gcode. 
Bed temperature updates as indicated, however the nozzle will not  change. Tried changing materials, no change.

**Application Version**
3.1.0

**Platform**
MacOS

**Steps to Reproduce**
Prusa Mk2 printer
use ABS material generic
change temperature to 255C
Gcode output nozzle temp will show 210C

**Actual Results**
Gcode output nozzle temp will show 210C

**Expected results**
Nozzle temperature should display 255C on prusa screen.

**Additional Information**

**Comment by ChrisTerBeke** [comment]
Duplicate of #1296. Please search through old issues before opening a new one.
