### ISSUE TITLE
Cura 3.1.0 Button "Save to removable disk" appears but not working

### ISSUE THREAD

**Issue by frankschu** [Ultimaker/Cura#3046]
Application Version: Cura 3.1.0
Platform: macOS 10.12.6

The Button "Save to removable disk" appears but clicking it has no effects.
When I'm using "Save to file" and choose the sd-Card everything is working fine.
I have tried to disable an enable the "Removable Drive Output Device Plugin", restart Cura, Restart Computer all without success.

**Comment by nallath** [comment]
Could you share the logs?

**Comment by frankschu** [comment]
Thanks for your response.
I have done a complete reinstall - now everything works fine.

Regards Frank
