### ISSUE TITLE
cura3.1 cpu occupy high in Ubuntu16.04 above.

### ISSUE THREAD

**Issue by ghostry** [Ultimaker/Cura#3054]
The APPimage file downloaded from the Ultimaker website.
When printing through usb, cpu occupy particularly high.
The same machine, below normal cpu win7.

**Comment by jackha** [comment]
How much is "particularly high" in comparison with "normal" ?
The code that is run is the same, possibly it's an OS issue?

**Comment by ghostry** [comment]
![qq 20171228230746](https://user-images.githubusercontent.com/1111786/34483226-fd7eab5c-eff7-11e7-9792-38a201588543.png)

**Comment by ghostry** [comment]
When using Windows, all core usage rates fluctuate around 10%, not over 50%.

**Comment by ghostry** [comment]
Ubuntu, do not open cura, cpu usage at 5%, not more than 20%.Smooth operation, open cura started printing, you can clearly find the system becomes slow.

**Comment by ghostry** [comment]
3.0.3 version of the cpu to normal.
