### ISSUE TITLE
bug - Cura3.1 "sub settings" overriding "main settings" does not work anymore

### ISSUE THREAD

**Issue by UltiArjan** [Ultimaker/Cura#3062]
cura 3.1.0
win 10

[CableHook.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/1594059/CableHook.curaproject.3mf.zip)

When I changed "wall line count" from 3 to 4 cura starts slicing, and then sets it back to 3.
I can change it when setting "wall thickness"

The issue is cura will not let a "sub setting" override a "main setting" anymore. I can set the wall line to 4 only by changing the "wall thickness"

The same issue also occurs with other settings , I can't change top layers (but can change layer thickness) and I can't change "infill speed", but can change it when setting "print speed"

I enclosed the project file.

**Comment by ChrisTerBeke** [comment]
Did you use the 3.1 beta before using the stable version?

**Comment by UltiArjan** [comment]
yes I did

**Comment by fieldOfView** [comment]
The beta left your configuration in a broken state. To repair it, go to Help -> Show configuration folder and close Cura. In the folder that opens, go up one level and remove the folder named "3.1" (and only that folder). When you launch Cura again, your configuration from 3.0 will be re-imported and upgraded.

**Comment by UltiArjan** [comment]
ah ok, thanks

**Comment by fieldOfView** [comment]
(it is in the release notes)
