### ISSUE TITLE
Controlling the sequence in "One at a Time" printing

### ISSUE THREAD

**Issue by brolifen** [Ultimaker/Cura#3070]
This is more of a feature request. When choosing to print one at a time it's nice to have more control on the printing sequence by adding a sequence ID perhaps per model which defines the order objects are printed to allow for more user control.

**Application Version**
3.1.0

**Platform**
Windows 10

**Steps to Reproduce**
**Actual Results**
**Expected results**
**Additional Information**

**Comment by Ghostkeeper** [comment]
The order in which the objects are printed affects their collision area. We currently edit the collision area to make it as small as possible for which we can still compute an order that prints all of them without colliding the print head to an object.

**Comment by ianpaschal** [comment]
Based on the above, I'm going to close this for now. It's a big change to something that isn't really a problem.

**Comment by redxeth** [comment]
I think it'd be useful.  Trying to design a multiprint using 20mm squares for bed levelling and would like to control the order that each square prints.
