### ISSUE TITLE
Gcode viewer only shows colors for T0 and T1

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#3080]
There should be a color for T2 (and more) also
e.g. T2 for diamond hotend emulation
e.g. T3 for Prusa MMU emulation

**Comment by ChrisTerBeke** [comment]
Can you fill out the issue template and post a screenshot?

**Comment by MB3Y** [comment]
I'll be glad to add screenshots, but didn't figure out how to do it yet. Should I upload somewhere and link to it?

Sorry not to have used template, will update later this evening. Issue seemed so straight forward to me (add T2 in Gcode and load up to Cura)

________________________________

**Comment by MB3Y** [comment]
**Application Version**
3.1

**Platform**
Win10

**Steps to Reproduce**
File - Open - Something.gcode

**Actual Results**
Representation for T0 and T1 is Ok, T2 and higher are not show / as transparent.

**Expected results**
I expect to see a representation for each extruder.

**After slicing using standard only 1 extruder**
![image](https://user-images.githubusercontent.com/29209302/34686665-9d618b4a-f4ac-11e7-9350-ba21633917aa.png)

**After striping in 12 equal parts using 3 extruders**
![image](https://user-images.githubusercontent.com/29209302/34686987-a75ea028-f4ad-11e7-992c-069bcfa725df.png)

**Comment by ChrisTerBeke** [comment]
@diegopradogesto any ideas given that you worked on the layer view recently?

**Comment by diegopradogesto** [comment]
It seems not to be related with layer view but with the GCode reader.
Devs: CURA-4778

**Comment by ChrisTerBeke** [comment]
Fixed in https://github.com/Ultimaker/Cura/commit/e3e6f301f9172c6bf811ac5ee432c277ba08deb2

**Comment by MB3Y** [comment]
It definitely is ! 👍 
![2018-02-22 1](https://user-images.githubusercontent.com/29209302/36607084-e0f6c68a-18c5-11e8-94b8-6fb642774466.png)
