### ISSUE TITLE
building without appimage?

### ISSUE THREAD

**Issue by clytle374** [Ultimaker/Cura#3084]
On Gentoo with sources from git. Is it possible to build without having appimagekit installed? Looks like appimagekit might be a bit of a mess to install. 
Thanks
Cory

**Comment by jackha** [comment]
If you only want to run it and not make an AppImage, then you don't need the appimagekit.

**Comment by clytle374** [comment]
That is what I am hoping to do.  How is that disabled in cmake to configure without appimagekit?

**Comment by nallath** [comment]
It's python. You don't need to build at all (The engine, libArcus & libSavitar need to be build). 

So runinng it can be done with "python3 cura_app.py"

**Comment by ianpaschal** [comment]
This question has been answered. [More information can be found in the wiki.](https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source)
