### ISSUE TITLE
master branch - gcode filename doesn't get updated for subsequent models

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3087]
**Application Version**

master branch

**Platform**

Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Load a model, slice it, note that the gcode file name is based on the model file name. Clear the build plate and load and slice another model.

**Actual Results**

The gcode file name doesn't change (it's still based on the first model's file name not the second).

**Expected results**

The gcode filename should be based on the name of the model just loaded. I appreciate that this becomes more complex when there are multiple models on the build plate but I'm talking about just having a single model at a time.

**Additional Information**

**Comment by ChrisTerBeke** [comment]
@jackha due to multi-buildplate merge?

**Comment by smartavionics** [comment]
This looks like it has been fixed, thanks. Closing...
