### ISSUE TITLE
Wire feed problem Prusa i3 with cura

### ISSUE THREAD

**Issue by 11argosy** [Ultimaker/Cura#309]
everything loads up OK, SD card inserted print file chosen but as soon as the print head gets to the bed to start printing the printer unloads the wire/filament and will not reload, I assume it is a software problem as it was ok until Friday.

**Comment by nallath** [comment]
Well, Cura hasn't updated since Friday if you're using one of the official releases.

**Comment by 11argosy** [comment]
I am using an official version and I have uninstalled this and re-installed but to no avail, my friend thinks its a print profile issue but I don't know how to check this.  John

**Comment by 11argosy** [comment]
By the way, thanks Nallath

**Comment by nallath** [comment]
If it worked friday with Cura and now it doesn't, there is little I can do to help. Cura didn't change, so it's probably the machine.

**Comment by 11argosy** [comment]
Thanks Jaime I May have the problem solved but will know more tomorrow,thanks for your help, regards John 

-----Original Message-----

**Comment by BagelOrb** [comment]
This sounds like a firmware issue.
