### ISSUE TITLE
Layer View does not show enough characters in layer bar

### ISSUE THREAD

**Issue by lunaticcalm** [Ultimaker/Cura#3094]
**Application Version**
Cure 3.1.0

**Platform**
Win10x64 RS3

**Steps to Reproduce**
Load a model that will slice with several hundred layers, switch to layer view.

**Actual Results**
The UI element which displays the layer count bar is only wide enough to display a little over 2 characters, leading to the 3 or 4 character layer count being cut off.

**Expected results**
Layer count bar should display all characters, expanding as needed. 

**Additional Info**
https://i.imgur.com/rIuLue1.png - You can see the '2' is only partially visible. If there were a fourth character (for 1000+ layers) it wouldn't be visible at all.

**Comment by ChrisTerBeke** [comment]
This will be fixed in 3.2.

![layer_view_chars](https://user-images.githubusercontent.com/1134120/34674016-8f6628a2-f484-11e7-999d-6180076c01e7.png)
