### ISSUE TITLE
Cura 3.1.0 - Color picker can appear under Materials window on OS X

### ISSUE THREAD

**Issue by combs** [Ultimaker/Cura#3100]
**Application Version**

3.1.0

**Platform**

10.11.4 and 10.12.6

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

- Choose Settings->Material->Manage Materials...
- Click a material on the left
- Attempt to alter its color

**Actual Results**

- The color picker appears but is not the foremost window. If its default placement overlaps the Materials dialog, user may be mildly confused. Moving the Materials dialog reveals the missing color picker

**Expected results**

- The color picker appears and is the foremost window. 

**Additional Information**

**Comment by ChrisTerBeke** [comment]
For me it's always the top window (on Windows and MacOS). Can you send a screenshot of what's happening maybe?

**Comment by combs** [comment]
I will grab a screenshot when I can (sorry, on wrong machine right now). But it won't be a surprising screenshot :) Just shows the color picker as a background window.
I'll play with it some more and see if a logout/restart changes anything.

**Comment by combs** [comment]
![screen shot 2018-01-10 at 20 04 31](https://user-images.githubusercontent.com/6174018/34803476-8826119c-f641-11e7-81f7-d7b4a59db833.png)

Restarting didn't change. Seeing it on two machines with different OS versions (not a cloned workstation setup)

**Comment by ChrisTerBeke** [comment]
Mm interesting, can't reproduce on master branch currently. Do you mind testing it in the 3.2 beta that comes out in ~1.5 weeks?

**Comment by Ghostkeeper** [comment]
It still seems to work all right on 3.2 on Windows, but I can't test with MacOS.

**Comment by ianpaschal** [comment]
This still reproduces on macOS in master.
