### ISSUE TITLE
Infill mesh influences skirt shape

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3110]
**Application Version**

master branch

**Platform**

Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Add model with rectangular base to build plate. Add infill mesh that extends past outline of model. Define skirt with skirt distance of 1mm.

**Actual Results**

Skirt is influenced by the infill mesh so it doesn't follow the rectangular outline of the mode.

**Expected results**

Skirt should follow rectangular outline of first layer of model.

**Additional Information**

![screenshot_2018-01-09_11-49-16](https://user-images.githubusercontent.com/585618/34719733-cd5b581c-f533-11e7-93d3-a41a894835c4.png)

**Comment by Ghostkeeper** [comment]
I can't reproduce this. Here is a cube with a skirt, and an infill mesh punching through it.

![screenshot from 2018-01-25 09-29-12](https://user-images.githubusercontent.com/2448634/35378200-41c16ef0-01b2-11e8-958c-2be55ec9afe6.png)

The skirt does not go around the infill mesh, nor does it seem to be influenced by it.

Was it only happening on that specific model?

**Comment by smartavionics** [comment]
Sorry, I blundered, it's not related to the infill mesh, it's something related to where the support towers would be placed. Here's the same model with the infill mesh removed and first support without towers and then support with towers. You can see the skirt bends around where the tower bases would be. Let's forget this. Sorry to have wasted your time.

![screenshot_2018-01-26_08-18-40](https://user-images.githubusercontent.com/585618/35430802-c0c934ca-0271-11e8-98b3-4dc8127b92f7.png)

![screenshot_2018-01-26_08-20-35](https://user-images.githubusercontent.com/585618/35430826-d7cda2c8-0271-11e8-8cab-208a8a6845c4.png)

**Comment by Ghostkeeper** [comment]
That is also buggy, but that would make this a duplicate of https://github.com/Ultimaker/CuraEngine/issues/544 .
