### ISSUE TITLE
UI weirdness and slow sluggisch behavior

### ISSUE THREAD

**Issue by paulbeumer** [Ultimaker/Cura#3125]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**
![cura](https://user-images.githubusercontent.com/35351662/34852156-84dfd59e-f72d-11e7-80c9-1926d809c0a9.jpg)
Additional Information**

**Comment by ChrisTerBeke** [comment]
Maybe the mouse driver and display driver don't agree on positions? Does this happen with other software for you as wel? Or at least other QT (UI framework) based software?

**Comment by fieldOfView** [comment]
See #2068

Intel gpu driver issue.
