### ISSUE TITLE
Option to edit printer settings missing?

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3126]
**Application Version**

master branch

**Platform**

Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Open manage printers dialog.

**Actual Results**

Dialog opens but there is no button to edit the printer settings.

**Expected results**

I expected a button to be visible that would open the machine settings dialog.

BTW - removing the printer and adding it again makes no difference.

**Additional Information**

![screenshot_2018-01-12_08-58-14](https://user-images.githubusercontent.com/585618/34867213-3c994a14-f777-11e7-9048-f3988517ddac.png)

**Comment by fieldOfView** [comment]
I can't reproduce this on current master. Logs?

Looks like some plugins fail to load (MachineSettingsAction, and OctoPrintPlugin too?)

**Comment by smartavionics** [comment]
Oops! My bad, somehow, that plugin had been disabled. Must have been finger trouble on my part. Sorry to waste your time. Closing...
