### ISSUE TITLE
Cura 3.1.0 not importing saved profiles from Beta version

### ISSUE THREAD

**Issue by chimera992** [Ultimaker/Cura#3129]
Note. I've looked online and it says this issue has been rectified with 3.1.0, however I haven't seen it until I updated to this version.

**Application Version**
3.1.0

**Steps to Reproduce**
Recently have upgraded from beta version to current latest (3.1.0).
Before updating, I saved all my profiles to a file on my computer.
Installed 3.1.0

Manage Profiles - Import Profile
Navigate to my selected profiles and choose one (have tried with all of them now)
Get a pop-up saying 'Successfully imported profile (profile name)'
Press OK
Cura returns to preferences-profiles page
Profile does not show up 

**Actual Results**
Cura says successful import, however there is no file

**Expected results**
Cura actually imports the profiles

**Additional Information**
None

**Comment by ChrisTerBeke** [comment]
The beta version had some issues. To recover, remove all data from the 3.1 folder that was used in the beta and re-import 3.0 profiles by re-starting the stable 3.1 cura after removing that data.
