### ISSUE TITLE
Import .xml material file with missing tag in the XML cause material cannot be deleted anymore

### ISSUE THREAD

**Issue by noisemaker00** [Ultimaker/Cura#3139]
Import a bad formatted material XML (eg. without GUID, etc) cause the material will be added to the list but it cannot be removed anymore (where those XML are saved to remove them manually??)
I suggest to add a syntax check on the XML to avoid potential issues.

EDIT:
In addiction to this, I had problem even to editing a material without a name.
I had to open the material XML file manually and editing the `<label>` tag

**Comment by alekseisasin** [comment]
What OS system do you use ?

**Comment by noisemaker00** [comment]
Windows 7 x64

**Comment by ChrisTerBeke** [comment]
You can remove the custom material from your user data folder (https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations) for now. Of course loading an incorrect XML file shouldn't totally break your Cura install, so we'll put that on our internal ticket system.

**Comment by ChrisTerBeke** [comment]
Devs: CURA-4851

**Comment by noisemaker00** [comment]
In addiction to this, I had problem even to editing a material without a name.
I had to open the material XML file manually and editing the `<label>` tag

**Comment by alekseisasin** [comment]
@noisemaker00  What do you expect from us to do with <label> tag

**Comment by noisemaker00** [comment]
I don't know how is handled internally, but I'm a software developer too and if a field is missing I think an exception handler should be implemented. Is quite frustrating when you add a material without name to be unable to open it again from the materials manager screen.
No all materials have names, because they are easily identified using only manufacturer/material type and color

**Comment by alekseisasin** [comment]
So far as I know the label tag in not required, it is optional. If labels is missing the name was defined different. 
For now I am checking the implementation and there will be some changes.
Do you use the latest Cura 3.1 version ?

**Comment by LipuFei** [comment]
Hi @noisemaker00 , a fix has just been made to validate an imported material file as you have suggested:
- https://github.com/Ultimaker/Cura/commit/e5c72cfdc5cef3d1cb995d5e9504e45fb94216c6
- https://github.com/Ultimaker/Cura/commit/a446ca2759170b78bb17d14fdc15c9d5c9e00010

**Comment by Ghostkeeper** [comment]
This issue has been verified by QA and should be fixed in Cura 3.3.
