### ISSUE TITLE
Bed is a bit warped

### ISSUE THREAD

**Issue by a4jp-com** [Ultimaker/Cura#314]
Can you add a setting to check more bed points if the bed is slightly warped? The wizard only checks 3 points now. Even an advanced setting to do this would be nice.

**Comment by nallath** [comment]
The bed point checking is just for leveling, not for checking if it's warped. 

Did you have this problem with an Ultimaker? We could look into making an plugin that does this, but it probably wont have priority.

**Comment by a4jp-com** [comment]
Yes. 

A plugin like that would be fantastic. Everything else is great with your program I just need to fix this problem.

**Comment by nallath** [comment]
How did you get a bed to warp with an Ultimaker? Thinking a bit more on this; even if we have the warp of the platform, we don't have any software in place that could compensate for this. It's a much harder problem than just finding what the warp is.

**Comment by a4jp-com** [comment]
I'm not sure, the glass is just a tiny bit higher near the center and lower near the edges for some reason. Any plugin or idea would be great.

**Comment by nallath** [comment]
This would take a lot of time to implement. You're better off getting a proper (flat) bed.
