### ISSUE TITLE
Duplicate object does not duplicate per-object settings

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#315]
Steps to reproduce:
* Load model
* Select model and use the "per-object settings" tool
* Press "override settings" and add a setting (eg layer height)
* Notice how the shadow of the object turns green 
* Duplicate the object
* Notice how the shadow of the newly created object is grey
* Use the "per-object settings" tool to inspect settings

Actual result:
Per-object settings have not carried over
Expected result:
Per-object settings are duplicated with the object

**Comment by awhiemstra** [comment]
This should already be fixed, I changed the duplication code to use deepcopy also for single objects.
