### ISSUE TITLE
Open recent menu now includes nozzle and machine STLs

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3153]
**Application Version**

master branch

**Platform**

Linux

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Start Cura, go to open recent menu

**Actual Results**

The open recent menu includes entries for the machine and nozzle STL files.

**Expected results**

The open recent menu should only include files that the human has explicitly opened.

**Additional Information**

![screenshot_2018-01-19_10-36-29](https://user-images.githubusercontent.com/585618/35147039-0157a82c-fd05-11e7-97c0-339073a932db.png)

**Comment by ChrisTerBeke** [comment]
We just saw this last night as well, an internal ticket has been created already. Thanks for reporting!

**Comment by Ghostkeeper** [comment]
This seems to be fixed now.
