### ISSUE TITLE
OctoPrint plugin in 3.2

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#3166]
I just found out from the release notes for the 3.2 beta that OctoPrint is no longer distributed with Cura by default. A notice would have been courteous. 

Unfortunately, the version that is distributed through the plugin browser is the 3.1 branch of the plugin. Since the API was changed to support multiple buildplates (without changing the api_version I might add!), this 3.1 version does not work with Cura 3.2. Please update the plugin in the plugin repository with the appropriate version.

Might I suggest to put some order in the listed plugins? Alphabetical might be expected. Also please be so kind to spell my name correctly in the author field: fieldOfView with an undercast 'f'.

**Comment by ChrisTerBeke** [comment]
You're totally right, you should have been informed! Apologies for that.

I'll raise a ticket for upgrading the plugin API version as well as updating the plugin on our server and give it priority.

Sorry again for the sudden changes.

**Comment by ChrisTerBeke** [comment]
Devs: CURA-4857

**Comment by ChrisTerBeke** [comment]
(bug in cura, 3rd_pary for the plugin upload)

**Comment by ChrisTerBeke** [comment]
The plugin repo has been updated (v2 for Cura 3.1 and earlier does not contain Octoprint, v3 for Cura 3.2 has the OctoPrint plugin and several others that we have tested with this release so far).

@ianpaschal a change in the list order of plugins is suggested here, anything you can do in your refactor?

**Comment by fieldOfView** [comment]
Would it be an idea to make a github repo for the plugin repository? That way 3rd party developers can issue a PR to have their plugins (and metadata) updated. The cura-plugins repo could use branches for (Cura) API versions.

**Comment by ianpaschal** [comment]
@ChrisTerBeke They are displayed alphabetically by default as part of the refactor. There's no custom sort/filter for now but I think that's OK.

@fieldOfView We've been talking a lot lately about what the plugin system might look like in the future and how it would integrate with a bigger "marketplace" with plugins, material profiles, etc. for download. This would likely include some sort of infrastructure similar to other package managers which would allow an author to publish a new of their package. A repo could be helpful in the mean time.

**Comment by fieldOfView** [comment]
> The plugin repo has been updated 

Unfortunately that means that people who download the beta now don't have access to OctoPrint anymore, until a new 3.2 release is made (right?)

**Comment by chking999** [comment]
Where do you get the Octoprint plugin from?

**Comment by ChrisTerBeke** [comment]
Main menu -> plugins -> browse plugins -> OctoPrint connection -> install

**Comment by Morgul** [comment]
Just came across this issue while trying to figure out how to get Cura working with OctoPrint again after an upgrade to 3.2, and I'd like to give a little bit of feedback to the team on this issue.

I read the release notes, and knew that OctoPrint was being moved to a plugin, but it was not clear that the plugin would not be _included_ in 3.2 by default. So my experience was updating, getting read to do a print, and then being confused when I couldn't connect to my printer. Until this point, I'd never used a plugin in Cura and was unfamiliar with the plugin browser, and mistakenly thought that `Settings -> Plugins` was it. It was only after finding the response above mine that I was able to get back up and running. Not a huge deal, but a little but of unintended friction, I'm sure.

Currently, the [release notes](https://ultimaker.com/en/products/cura-software/release-notes) say:

> **OctoPrint plugin added to plugin browser.** This plugin has moved to the plugin browser. This plugin enables printers managed with OctoPrint to print via Ultimaker Cura interface (version 3.2 or later).

They do not, however, say you will need to install the plugin if you were already using it. I would suggest changing the release notes to something like this:

> **OctoPrint plugin added to plugin browser.** This plugin has moved to the plugin browser. This plugin enables printers managed with OctoPrint to print via Ultimaker Cura interface (version 3.2 or later).
>
> _Note: If you used the OctoPrint plugin prior to 3.2, you will now need to install it. Simply go to `Plugins -> Browse plugins...` and click `Download`. Your previous settings will remain._

**Comment by lenalebt** [comment]
That does not work or me. The "print with octoprint" button disappered, and I cannot get it to work again. Currently I need to save to file, upload to octopi manually and start the print job there, really annoying. Happy for input :).

Cura 3.3.1, Re-Installed the plugin multiple times, removed all settings as well (removing ~/.config/cura folder throwing away all settings). Octoprint reachable in the network (octopi.local), octopi 0.14.0, octoprint 1.3.8.

**Comment by fieldOfView** [comment]
Is there a "Connect OctoPrint" button in the Printers pane of the preferences?
Can you post your logs (cura.log from ~/.config/cura) somewhere where we can have a look?

**Comment by lenalebt** [comment]
I just found the issue. It forgot the API key for some reason. In case somebody else falls into the same trap, go to Preferences -> Configure cura -> Printers -> select your model -> Connect Octoprint and check that the API has not been removed. My bad, layer 8 problem. Thanks!
