### ISSUE TITLE
3.2 Beta is out. will it be it safe to install it side by side with 3.1?

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3167]
Thank you all for Cura 3.2 Beta.
Will it be it safe to install it side by side with 3.1?

**Comment by fieldOfView** [comment]
Yes.

Since Cura 2.6, new versions make a copy of the last version configuration they can find, and upgrade that copy (leaving the previous versions unaffected).

**Comment by Thisismydigitalself** [comment]
Good to know but i though of asking again due to my (bad) experience back when i upgraded from 3.04 to 3.1Beta.

**Comment by ChrisTerBeke** [comment]
Side by side is always OK. When it doesn't work for you, go back to 3.1 and you'll find nothing changed there. We always copy when upgrading to the newer version and only modify the copied data.

**Comment by Thisismydigitalself** [comment]
Once bitten, twice shy.
I will give it a try now after I've backup 3.1 and copied:
C:\Program Files\Ultimaker Cura 3.1\
C:\Users\~\AppData\Roaming\cura\3.1\

**Comment by Thisismydigitalself** [comment]
Just installed 3.2B.
For those who want to keep 3.1, just click NO when asked to uninstall 3.1.
![ice_screenshot_20180123-173119](https://user-images.githubusercontent.com/30949968/35284358-45aa8e02-0063-11e8-8cfe-aa5c3668f3f0.png)

Installing 3.2B was fast and with no issue.
Loading time for 3.1R is: 32 seconds.
Loading time for 3.2B is: 9 seconds.

Impressive.
Will try it out and report back.
Thank you.

**Comment by ChrisTerBeke** [comment]
Let's use this thread to report 3.1 vs 3.2 startup times so we have an average improvement overview for the final release.
