### ISSUE TITLE
Cura 15.06.03 Does not Slice, Can not save

### ISSUE THREAD

**Issue by lilmac024** [Ultimaker/Cura#317]
The model will not slice and as a result I can't save it to my SD card, it won't calculate any time, and won't show any layers in the layer view.

![image](https://cloud.githubusercontent.com/assets/4022171/9670422/8592c9e4-525a-11e5-8736-5937725f5c3f.png)

**Comment by nallath** [comment]
Could you post your log file?

**Comment by lilmac024** [comment]
The engine log appears totally empty.  

![image](https://cloud.githubusercontent.com/assets/4022171/9684087/4114defe-52e3-11e5-8405-36e1277e8e4e.png)

**Comment by lilmac024** [comment]
I have uninstalled and reinstalled 2 times as well.

**Comment by lilmac024** [comment]
I think I may have found the issue, it appears that I'm actually missing the CuraEngine.exe.  Will install that and see if it's resolved.

![image](https://cloud.githubusercontent.com/assets/4022171/9685695/dee50a64-52ed-11e5-8559-21ec61ce4ca0.png)

**Comment by lilmac024** [comment]
problem resolved...my antivirus was deleting the CuraEngine.exe when it was turned on.  If I turn off the antivirus and install Cura it works perfectly.

**Comment by nallath** [comment]
Yeah, we've heard about this before. Most anti-viruses don't like local sockets (which we use to communicate). Thanks for posting the solution.
