### ISSUE TITLE
[PostProcessingPlugin - PauseAtHeight] Please add "pause before layer N" in addiction to height in mm (and custom GCODE too)

### ISSUE THREAD

**Issue by noisemaker00** [Ultimaker/Cura#3172]
The `PauseAtHeight` plugin is cool, but it will be more useful if you can set the layer number BEFORE which the printer should pause and wait.
When you embed extra parts (like nuts) you can check in the "Layer view" the layer which will cover the part, so you must set a pause before that layer. This is faster and easier than calculate the height.

It will be cool if you can also set a custom GCODE script to replace the one generated from the plugin itself.

**Comment by Ghostkeeper** [comment]
Something similar to TweakAtHeight would be nice to have, where you can specify a layer number.

**Comment by Ghostkeeper** [comment]
I've implemented this for Cura 3.3, but I didn't port it for the Repetier or BQ versions yet. Kind of difficult since we have 3 implementations of the same thing...
