### ISSUE TITLE
Initial Layer Width (%)

### ISSUE THREAD

**Issue by tzminversion** [Ultimaker/Cura#318]
In Cura 15.02.1 there is the option Initial Layer Width (%).

I use this all the time for PLA, WoodFill in particular and it seems to be missing in 15.06.03.

I keep having to return to Cura 15.02.1, because it has more features than the newer version!

Please add this feature! Thanks.

**Comment by BagelOrb** [comment]
This is a duplicate of https://github.com/Ultimaker/Cura/issues/184

Please see there why the feature is missing and how we will probably solve it.
