### ISSUE TITLE
Installpath from CMakeLists.txt inconsistent with call to addPluginLocation

### ISSUE THREAD

**Issue by StefanBruens** [Ultimaker/Cura#3195]
https://github.com/Ultimaker/Cura/blob/master/cura/CuraApplication.py#L533
`self._plugin_registry.addPluginLocation(os.path.join(QtApplication.getInstallPrefix(), "lib", "cura"))`

i.e. the plugins should be installed to something like "/usr/lib/cura/plugins/", which is likely correct, as all plugins are currently pure python plugins.

There are two solutions:
- correct the install path in CMakeLists.txt (see #3194)
- add `/<prefix>/lib64/cura/` to the search path

**Comment by Ghostkeeper** [comment]
I've added a few common lib suffixes for now. If there needs to be a different install path for OpenSUSE and Fedora we'll take a look at that in #3194.
