### ISSUE TITLE
can't use removable drive for ultimaker 2, errno 13, no permission

### ISSUE THREAD

**Issue by Riagel** [Ultimaker/Cura#3199]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Vandrasc** [comment]
Hi @Riagel ,

I do not think this is related to Cura, it seems you have insufficient permission, do you have all the rights and running as administrator?

**Comment by fieldOfView** [comment]
> running as administrator?

Noooo! Don't run Cura as administrator!

@Riagel, we need *much* more information to be able to help you. Please fill in the template.

**Comment by Vandrasc** [comment]
Hey, that was the next step ^-^, thank you @fieldOfView

**Comment by ianpaschal** [comment]
No information was provided. Going to consider this forgotten.
