### ISSUE TITLE
material_print_temperature problem

### ISSUE THREAD

**Issue by SphaeroX** [Ultimaker/Cura#3205]
My start code looks like this:

```
M107; Fan off
M140 S{material_bed_temperature_layer_0}; Set bed temp
G28; home all axes
G21; set units to millimeters
G1 X-33 Y200 F7200; drive forward to clean the bed to clean it
M109 S{material_print_temperature_layer_0}; Set nozzle temp and wait
M190 S{material_bed_temperature_layer_0}; Set bed temp and wait
G29; Renew Auto Leveling
M420 S1; Leveling Switch on
G1 X2.5 Y10.0 F7200; Position to the left of the bed
G1 Z0.1; lower the duese in preparation for stripping the material
M109 S{material_print_temperature_layer_0}; Set nozzle temp and wait
M190 S{material_bed_temperature_layer_0}; Set bed temp and wait
G92 E0; zero the extruded length
G1 F200 E15; extrude
G92 E0; zero the extruded length
G1 X5; Wipe off material
G1 X10 Z0; Strip material
G1 Z0.2; raise these slightly for material feed
```

If I now set the temperature for the first layer to 190, he makes 210 in GCode from it, I think he takes the values of the material. He shouldn't do that because I entered the temperature manually.

No matter if material_print_temperature_layer_0 or material_print_temperature always the same error

**Application Version**
3.1

**Platform**
Windows 10

**Comment by Vandrasc** [comment]
Hi @SphaeroX, this should be fixed in 3.2. The 3.2 Beta is already online and the stable release will be deployed in few days. Thank you for reporting it!
