### ISSUE TITLE
Minor bug: Menu closes when clicking on expandable item

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#321]
When I go to 
[ File ]
...
[ Save All   >]  [ Save to File ]

and click on Save All, the menu closes.

expected
---
The menu stays open and the [ Save to File ] submenu shows if it isn't shown already.

**Comment by nallath** [comment]
Nice find. I don't see a quick solution for this as the menu is built by QT

**Comment by nallath** [comment]
Won't fix
