### ISSUE TITLE
Same Cura, different menus using different graph proc

### ISSUE THREAD

**Issue by TiborUjj** [Ultimaker/Cura#3210]
My laptop: ASUS N53S/w10home/I7/RAM 8GB/NvidiaGT540M Cuda 1 GB/1920*1080
Cura 14.07 is ok.
Ver 3.2 is strange: 
Running the cura with integrated graph card and Nvidia graphcard: The menus are different, the colors are different. See the attached pictures.
Drag the cura window and touch the right/left side the display. The window has to fit the half screen. Cura 14.07 does it well. The 3.2 will be wider (see the pictures).
[cura32.zip](https://github.com/Ultimaker/Cura/files/1681013/cura32.zip)

**Comment by Ghostkeeper** [comment]
This is sort of intended.

In Cura 3.2 we have a nicer rendering of layer view, where the printed lines are rendered as 3D tubes. However this mode requires OpenGL version 4.0 or higher. Your integrated graphics card probably doesn't support that yet or you need to update the drivers for that integrated graphics card. Therefore Cura will revert to the legacy rendering mode where the lines are drawn as 2D layers.
