### ISSUE TITLE
cannot find token to change temp on certain exctruder

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#3212]
My setup is dual extruder one nozzle smoothieware.
The problem of smoothieware: It cannot change temp when Second extruder is active
So I want to change it in gcode section first extruder definition file.
But I cannot find how to correct adress {print_material_temp} to second extruder
I expect something like {2/print_material_temp} or Id of extruder

**Comment by Ghostkeeper** [comment]
You should be able to use `{print_material_temp, 2}` in the next version (Cura 3.3). That will allow you to do something like this.
