### ISSUE TITLE
Cannot save postprocess script settings to project

### ISSUE THREAD

**Issue by karabas** [Ultimaker/Cura#3217]
**Application Version**
Cura 3.2beta

**Platform**
win10

**Steps to Reproduce**
Set postprocess script Search and replace
Save project.
Load project and see.

**Actual Results**
No script settings

**Expected results**
script settings saved.

**Additional Information**

**Comment by ChrisTerBeke** [comment]
This is a known restriction, reported several times before on this repository.

**Comment by Ghostkeeper** [comment]
This would be fixed by https://github.com/Ultimaker/Cura/issues/3217. Maybe Cura 3.3, but that's uncertain still.

**Comment by jackha** [comment]
It made it to 3.3!
