### ISSUE TITLE
Cura doesn't generate first layer raft for internal support if "brim only on outside" is enabled.

### ISSUE THREAD

**Issue by KubaAseph** [Ultimaker/Cura#3224]
Cura 3.1.0 / Win10 x64

As I said in title. OFC it's kinda rational that the fishnet pattern won't print if it has nothing to connect to, but could you add some slicing alert about support lines mid-air? Or maybe let the net or support lines print on first layer then? For now no matter what they print only from second layer upwards, what results in instant spaghetti.
For me it ended only in broken thermistor wire, but at more advanced printers this could generate much more damage.

![off](https://user-images.githubusercontent.com/19820244/35766595-98ae88d0-08db-11e8-9661-83fb19066d10.png)
![on](https://user-images.githubusercontent.com/19820244/35766596-98ca2e6e-08db-11e8-8f9a-78ce21b12738.png)
![rip](https://user-images.githubusercontent.com/19820244/35766648-438a944c-08dc-11e8-9c65-606d25fdd709.jpg)

**Comment by Ghostkeeper** [comment]
Support should always be printing on top of... something. Was support floating in mid-air?

**Comment by KubaAseph** [comment]
Yes. The layer after the shown one was always support - both with inside brim enabled and disabled, but as you can guess on the 2nd one there was no first layer grid supporting the support so it was printed too high and scratched the rest of print off.

**Comment by Ghostkeeper** [comment]
For me it always creates this fishnet pattern underneath all support. I don't see any support floating in mid-air.
