### ISSUE TITLE
3.2 Beta Error at launch

### ISSUE THREAD

**Issue by JulienDevillers** [Ultimaker/Cura#3225]
**Application Version**
3.2 Beta

**Platform**
WIN7 64 SP1

**Qt**
version from ultimaker's site. 

**PyQt**
version from ultimaker's site. 

**Display Driver**
quadro K2200

**Steps to Reproduce**
Launch Cura. That's all... :D

**Actual Results**
Error dialog (splash screen still displayed, in "loading machines") : 
Error in sys.excepthook
Exception : list index out of range
Original Exception : arguement of type 'NoneType' is not iterable

**Expected results**
See cura window.

**Additional Information**
I have both cura 3.1 and 3.2 beta installed.
Joined are my configurations files for version 3.1 .
[3.1.zip](https://github.com/Ultimaker/Cura/files/1691709/3.1.zip)
If I remove them and re-install cura 3.2b, it works.

**Comment by ryamoo** [comment]
I also have this error when launching 3.2, the version I have just download from ultimaker's website.
I have 3.0 and 3.1 installed. I have been using 3.0, but not 3.1 (I had issues printing around the time I installed 3.1, never pinpointed if they were related, so stopped using 3.1 and carried on using 3.0).

If i hit the "backup and reset configuration" then Cura 3.2 will launch, but I need to re-setup my printer/profiles/materials which I would rather not do. 
I'll stick to 3.0 for now.

**Comment by ChrisTerBeke** [comment]
We gathered these reports and it's fixed for 3.3.

**Comment by ryamoo** [comment]
Great, thanks for the update.
Is that beta available for download yet?

**Comment by ianpaschal** [comment]
@ryamoo No. But Cura will notify you with a little notification box at the bottom of the window when the update is available to download.

**Comment by ryamoo** [comment]
@ianpaschal well, I'm still using 3.0.4 because it was the last one I could use whilst keeping my profiles, so I already get the update notification everytime I launch Cura, which I'm ignoring ;-) 
I'd like to test 3.3 for the fix, if/when the beta goes public.

**Comment by Ghostkeeper** [comment]
(The 3.3 beta is public now.)
