### ISSUE TITLE
dropdown colour in print setup

### ISSUE THREAD

**Issue by notmine642** [Ultimaker/Cura#3241]
**Application Version**

3.2.0 beta

**Platform**

windows7

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

I use cura in black and when I go into dropdown text is written in white on white background... it is difficult to read the options.
**Actual Results**

**Expected results**

**Additional Information**

**Comment by fieldOfView** [comment]
This has already been fixed in the release version of Cura 3.2

**Comment by notmine642** [comment]
thanks,
3.2 was released today and I have not yet installed it ! what a shame :p
