### ISSUE TITLE
Cura 3.2 incorrectly displaying text in sidebar on OSX

### ISSUE THREAD

**Issue by JustinW23** [Ultimaker/Cura#3250]
**Application Version**
3.2 (also 3.2 beta)

**Platform**
OSX 10.13.4 on Macbook Pro Retina 15" Mid 2014

**Qt**
downloaded from Ultimaker website

**PyQt**
downloaded from Ultimaker website

**Display Driver**
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB

**Steps to Reproduce**
Open the software.

**Actual Results**
The text in the right hand menu had white "blotches over the text"  Attached a screenshot. The whited out blotches scroll with the text

**Expected results**

**Additional Information**
Have tried complete reinstall. Also deleted the contents of ~\library\application support\cura\ folder. Tried a reinstall and same issue.  Reinstall 3.1 and the issue does not occur
<img width="476" alt="cura3 1-menu" src="https://user-images.githubusercontent.com/36227837/35911735-bdb8c3b8-0c4e-11e8-9864-40c60813b900.png">
<img width="457" alt="cura3 2-menu1" src="https://user-images.githubusercontent.com/36227837/35911736-bdf01bba-0c4e-11e8-80a2-e5a002a05c81.png">
<img width="445" alt="cura3 2-menu2" src="https://user-images.githubusercontent.com/36227837/35911737-be388ca6-0c4e-11e8-8702-29cf88247be8.png">

**Comment by Marlequeen** [comment]
Seconding this, I have exactly the same behavior on the exact same Mac book Pro release with OSX 10.13.2
I also tried the beta version, re-installing from scratch (also deleting all Cura folders) :

![cura](https://user-images.githubusercontent.com/36244343/35939492-96c2a4d8-0c4c-11e8-8f8c-19b03849da15.jpeg)

I have tried : changing language, changing theme to Ultimaker Dark, to no avail.
Cura 3.1 and 3.0.3, which I reinstalled, just work fine regarding this specific issue.

**Comment by pbannister** [comment]
I also see this issue, on MacO3 10.13.3 with my MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by JustinW23** [comment]
I tried looking at those environment variables for QT but no luck at all.  It doesn't explain why  3.0 and 3.1 work fine though and 3.2 doesn't.

**Comment by Appesteijn** [comment]
Devs see CURA-4941, https://github.com/Ultimaker/Cura/pull/3270

**Comment by Appesteijn** [comment]
Could you try Cura 3.2.1: https://stack.mybacklog.info/s/MgLnKXLL0P9ro4M ? It is from my personal cloud storage, but currently we don't have a fast way of distributing a build (yet).

**Comment by JackTirol** [comment]
Same problem here! Cura 3.2.1 didn't solve it. Went back to 3.1.0 which works fine.

OSX 10.13.3 on Macbook Pro Retina 15" Late 2013
<img width="425" alt="bildschirmfoto 2018-02-09 um 19 00 49" src="https://user-images.githubusercontent.com/21315949/36042769-363c280a-0dcd-11e8-9f39-b79128005769.png">

**Comment by JustinW23** [comment]
3.2.1 didn't fix the issue for me either.

**Comment by Appesteijn** [comment]
I made a PR https://github.com/Ultimaker/Cura/pull/3279 in which all divisions and multiplications on Cura and Uranium are rounded. If this doesn't fix it, I give up.
On Monday I can create a new testbuild.

**Comment by pbannister** [comment]
Yeh. The 3.2.1 version seems to be that same, with shredded text. Off to
figure out hold to build development versions from Github...

**Comment by fieldOfView** [comment]
This thread has a new private build that should fix the issue:
https://github.com/Ultimaker/Cura/issues/3277#issuecomment-365911053

Alternatively you can install this plugin, which also fixes the issue:
http://files.fieldofview.com/temp/PrepareStageCompactor.curaplugin

**Comment by ianpaschal** [comment]
@fieldOfView: Thanks again Aldo! Closing this thread since those links will solve the issue.
