### ISSUE TITLE
void filled when using dual extrusion 

### ISSUE THREAD

**Issue by sofa-bear** [Ultimaker/Cura#3256]
When I add a second object for dual extrusion a void in my model gets filled its fine on its own and in cura 16 but in 3.2 it just wont work 

I'm using cura 3.2 on windows 10 

![cura](https://user-images.githubusercontent.com/36248927/35948848-834383cc-0c66-11e8-800d-2761ee31d5d1.png)

**Comment by Vandrasc** [comment]
Hi @sofa-bear, is it possible to share the model and the steps to reproduce (or the project file)? It may be that it is taking some of the settings from the second extruder? Thank you!

**Comment by BagelOrb** [comment]
Look at the X-ray view. Your model is broken.
