### ISSUE TITLE
Mac, delete selected Model by just hitting the delete key, does not work.

### ISSUE THREAD

**Issue by tmblue** [Ultimaker/Cura#3257]
**Application Version**
 3.1 3.2

**Platform**
 MacOS Sierra

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
 Have an item on the build plate, switch windows, click it and hit the delete key, nothing happens, one has to right click and use delete selected model, this is incorrect, I should be able to at anytime hit the delete key to remove a selected model (and sometimes it  works, but most times it requires a right mouse click and delete selected model)

**Actual Results**
 . 95% of the time it won't delete with just pressing the delete key

**Expected results**
 100% of the time if I have a model selected I should be able to hit the delete key and make it go poof, into the ether.,

**Additional Information**

None, noticed it in 3.1 still there in 3.2, has to be more Mac users that this is bothersome? This is my second Mac , this one does it as well, so it's software.

**Comment by Vandrasc** [comment]
Hi @tmblue, are you using the Fn+Delete shortcut in order to remove the model and it doesn't work? We had an issue but I thought we fixed it in 3.2.

**Comment by Ghostkeeper** [comment]
Didn't we also allow backspace as delete just for this reason?

**Comment by LeviMThomas** [comment]
The Mac Delete key is a Delete key... It is literally a key with nothing on it at all but the word, "Delete" ! lol.
