### ISSUE TITLE
Estimated filament length shown incorrect in 3.2

### ISSUE THREAD

**Issue by foxel** [Ultimaker/Cura#3258]
Cura 3.2 started showing incorrect filament length for a project. It's about 2.6 times lower than it was shown in Cura 3.1.
![image](https://user-images.githubusercontent.com/1551926/35953211-2362492a-0cb6-11e8-9f65-b7104881cb3d.png)

**Application Version**
3.2.0

**Platform**
Linux

**Steps to Reproduce**
Load model, slice

**Actual Results**
Incorrectly estimated filament length

**Expected results**
Correctly estimated filament length

**Additional Information**
Interesting that estimated cost looks like calculated with correct length in mind
https://www.dropbox.com/s/p56p6cohl5zj4wk/K_Headphone_Hanger?dl=0

**Comment by smartavionics** [comment]
Similar to https://github.com/Ultimaker/Cura/issues/3117 ?

**Comment by ChrisTerBeke** [comment]
Duplicate indeed.

**Comment by foxel** [comment]
I don't see it's a duplicate. In my case is not driven by any filament diameter change. Is just constantly 2.6 times smaller than expected

**Comment by Ghostkeeper** [comment]
The issue #3117 says it only occurs when changing filament diameter, but it was actually a matter of obtaining the diameter from the wrong location in our data structures and was also occurring without changing it manually.
