### ISSUE TITLE
Cura 3.2 failing some (?) settings import from 3.1.

### ISSUE THREAD

**Issue by pbannister** [Ultimaker/Cura#3259]
**Application Version**
3.2.0

**Platform**
MacBook Pro (Retina, 15-inch, Late 2013)
https://github.com/Ultimaker/Cura/issues/3177

**Steps to Reproduce**
Install Cura 3.2 in place of 3.1 (latest).

**Actual Results**
Printer settings are carried over, correctly.
Added Materials settings are lost.
Added Profiles settings are lost.

**Expected results**
User's custom settings should be preserved/imported.

**Additional Information**

**Comment by nallath** [comment]
Please provide logs. There is little we can do to help you if you don't provide them.

**Comment by ianpaschal** [comment]
Reporter has not provided more information for more than 2 weeks, so closing.
