### ISSUE TITLE
[15.09.80] No printer settings available until a global profile is selected

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#326]
Steps to reproduce:
* remove the cura profile folder
* start cura
* add a new machine

Result: machine is added, but the Print Setup panel contains no settable options (only the headers show)

* select the Normal Qaulity profile

Result: Print Setup is now populated with settings

15.09.80, Win7/64bit

**Comment by nallath** [comment]
I've fixed this already :) Could you test 15.10 branch?

**Comment by fieldOfView** [comment]
Automatically selects the High Quality profile now. Normal Quality might be a better choice, but it works.
