### ISSUE TITLE
3.2 Adaptive Layers don't work for merged objects as expected

### ISSUE THREAD

**Issue by skobkars** [Ultimaker/Cura#3263]
If object consists of two (or more?) merged parts then selecting "Use adaptive layers" causes strange issues and artefacts.

**Application Version**
3.2

**Platform**
MacOS

**Steps to Reproduce**
Add two STL files to the project, select both and merge, or change infill for the top part and merge.

**Actual Results**
Slicing either crashes on the first layer, or after completing bottom part of the merged object

**Expected results**
Fully sliced object

**Additional Information**
<img width="1385" alt="screen shot 2018-02-08 at 1 44 03 am" src="https://user-images.githubusercontent.com/9848633/35966052-95a80f46-0c71-11e8-8d97-1d1ecacfe5de.png">

**Comment by ChrisTerBeke** [comment]
Adaptive layers is experimental and not tested with multiple / merged objects. We'll add this to the list of known issues so we can further improve it in the next iteration.

**Comment by ChrisTerBeke** [comment]
Devs: CURA-4933.
