### ISSUE TITLE
Cura 3.2 Official Release - gMax 1.5+

### ISSUE THREAD

**Issue by gordo3di** [Ultimaker/Cura#3265]
Has Cura 3.2 Officially been released? It looks like it has released on Ultimaker's website but its not listed under:
https://github.com/Ultimaker/Cura/releases

We ask because after installing it, the gMax 1.5+ configurations are not coming up. The config files were pulled into the "master" about 20 days ago. Should they have been pulled into the 3.2 branch instead?

Just wondering. Thanks.

**Comment by diegopradogesto** [comment]
You can find the official 3.2 release in Ultimaker's website. In the next few days we will create the downloadable release in GitHub.
The profiles for gMax 1.5+ are in master branch but not in 3.2 since they were added after the 3.2 branch was created.

**Comment by gordo3di** [comment]
Ah thanks for the info. I was under the impression the master was always the latest compile and the 3.2 branch was just for testing/bug fixing. Make sense now.
