### ISSUE TITLE
Feature Request : Inner Wall Extruder 

### ISSUE THREAD

**Issue by kickhad** [Ultimaker/Cura#3278]
I have a case where I'm wanting to print TPU95A exterior with a rigid (ABS perhaps) inner structure.

**Comment by diegopradogesto** [comment]
We already have this feature. Is this what you mean?
![inner_wall](https://user-images.githubusercontent.com/15830521/36089168-bc48c638-0fda-11e8-84ef-47cbcd2ccd80.PNG)

**Comment by kickhad** [comment]
Exactly! Not sure how I missed that.

**Comment by diegopradogesto** [comment]
Good luck!
