### ISSUE TITLE
Poor font rendering with High DPI scaling

### ISSUE THREAD

**Issue by codemonkeh** [Ultimaker/Cura#3280]
**Application Version**
3.2.0

**Platform**
Windows 10 Pro x64

**Qt**
n/a

**PyQt**
n/a

**Display Driver**
nVidia GeForce 390.65

**Other particulars**
* Screen Resolution: 3840 x 2160
* Scaling: 150%

**Steps to Reproduce**
1. Adjust scaling to 150%
2. Open Cura
3. Open Preferences > Configure Cura

**Actual Results**
The text in the Print Setup and Preferences is sharp, however random characters in the preferences dialog are displayed in slightly different sizes / scaling. Further more they will 'dance', i.e. continually adjust, if you resize the dialog.

E.g. the *Interface* and *Viewport behavior* sub headings.

![image](https://user-images.githubusercontent.com/14917019/36061910-08353598-0eb6-11e8-94a5-8c22f00c9ef4.png)

I do note that if you adjust to override the high DPI scaling to System or System (Enhanced), e.g.

![image](https://user-images.githubusercontent.com/14917019/36061927-4b8223ce-0eb6-11e8-8e0e-863c9473d144.png)

then the text is correctly rendered, however it is slightly blurry (as i presume it is using bitmap scaling).

![image](https://user-images.githubusercontent.com/14917019/36061935-6954d108-0eb6-11e8-8d9e-233314d42c91.png)

**Expected results**
The text should be sharp and scaled to a consistent size.

**Comment by diegopradogesto** [comment]
We are aware of some issues with fonts, such as #3277. We are trying to fix them in the next release. Thanks for the feedback.

**Comment by Appesteijn** [comment]
Could you try: https://stack.mybacklog.info/s/F78VhDOiMOQ9Qay

**Comment by Appesteijn** [comment]
Could you try: https://stack.mybacklog.info/s/LDltcUP2BXur7AZ ?

**Comment by codemonkeh** [comment]
Sorry @Appesteijn, I am getting a *Pagina niet gevonden* for that link

**Comment by ianpaschal** [comment]
@codemonkeh I think that's because @Appesteijn replaced it with an updated version. Try:
https://stack.mybacklog.info/s/wOg49yivjI6AIHv

**Comment by codemonkeh** [comment]
@ianpaschal / @Appesteijn This appears to be a macOS build, was there a windows build to test?

Apologies for the delay in my reply.

**Comment by diegopradogesto** [comment]
@codemonkeh do you still see font rendering issues in our latest 3.4 version? Can you try it out?
