### ISSUE TITLE
Icon not applied to .STL files

### ISSUE THREAD

**Issue by lunaticcalm** [Ultimaker/Cura#3281]
**Application Version**
Cura 3.2

**Platform**
Win10x64 RS3

**Display Driver**
Radeon 17.12.1

**Steps to Reproduce**
Install Cura 3.2

**Actual Results**
.STL files appear in File Explorer with the generic Windows 'unknown file type' icon

**Expected results**
.STL files appear with Cura's icon

**Additional Information**
Screenshot showing the generic icon:
![image](https://user-images.githubusercontent.com/25539911/36064876-e1713c96-0e5f-11e8-9006-0fd1286c82c3.png)
Here's an example I found showing how it used to look in 3.1: 
![image](https://content.invisioncic.com/ultimake/monthly_2017_10/2.5.png.7f983a40a0b6765a3254921ead3008d6.png)
I've tried reinstalling Cura, changing the file association for .STL away then back to Cura, no luck.

**Comment by Spankyty** [comment]
Same issue...

**Comment by Ghostkeeper** [comment]
I've seen it work though... Let's investigate when this happens and when this doesn't happen.

**Comment by SuddenlyPineapple** [comment]
Same problem in 4.9.1. Reinstall (without deleting settings) won't work. Change for other default app (like Paint 3D) apply other app icon and changing back to Cura switch to default windows icon :/ Seem to me like problem with paths to icon somwhere in code or when configuring file type extension <-> icon assotiation. I will try do it manualy and let know you ;)

**Comment by SuddenlyPineapple** [comment]
I've found it. Seems like paths from previous intalation persist ;) 
![image](https://user-images.githubusercontent.com/19464921/119983863-05b0d380-bfc1-11eb-9124-0d6b117b633f.png)

This article helped find it ;) https://www.howtogeek.com/howto/12383/change-a-file-types-icon-in-windows-7/

**Comment by GregValiant** [comment]
Has this been fixed in current versions (5.8 and up)?  Can this be closed?
