### ISSUE TITLE
multiple objects on buildplate in 3.2

### ISSUE THREAD

**Issue by benfordr** [Ultimaker/Cura#3286]
When I added about 5 small objects to the buildplate I set it to build them all at once.
It built the shortest object well but stopped building all the others at this level.

Seem fine when building one at a time.

Many thanks

**Comment by jackha** [comment]
Can you share a project file / screenshots / logs to show us the problem so we can investigate?

**Comment by ianpaschal** [comment]
Reporter has not provided more information for more than 2 weeks, so closing.

**Comment by Ghostkeeper** [comment]
I suspect that this is due to the adaptive layer height. We fixed that bug for 3.3.
