### ISSUE TITLE
Cura 3.2.0 - Prepare/Canel button overlaps modify post-processing scripts - button

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#3287]
**Application Version**
3.2.0

**Platform**
macOS 10.12.6

**Qt**
bundled

**PyQt**
bundled

**Display Driver**
macOS default

**Steps to Reproduce**
When automatic slicing is _disabled_ and g-code post-processing scripts are enabled, the button prepare/cancel overlaps the post-processing scripts button

**Actual Results**
overlaping

**Expected results**
no overlaping

**Additional Information**
Screenshots:
![screen shot 2018-02-11 at 21 29 35](https://user-images.githubusercontent.com/1069286/36078202-dee6776a-0f73-11e8-8f0d-67da4ff56077.png)
![screen shot 2018-02-11 at 21 30 55](https://user-images.githubusercontent.com/1069286/36078204-e18583e4-0f73-11e8-9afc-1d6d38691d0b.png)

**Comment by fieldOfView** [comment]
Already fixed for 3.3 here: https://github.com/Ultimaker/Cura/commit/e157d8e0455143cdb52afad430563352e0464a12
