### ISSUE TITLE
Solid/Layer view drop-down issue

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#329]
Version: 15.09.80
Platform: OS X 10.9.5

The Solid and Layer options get swapped around after the first change making changes counterintuitive. The "tooltip" is also cut-off.

Prior to changing View Mode:

![screen shot 2015-09-04 at 7 57 45 am](https://cloud.githubusercontent.com/assets/12257213/9688301/d2f07f58-52da-11e5-90db-66dae3efe30d.png)

After changing View Mode:

![screen shot 2015-09-04 at 7 58 58 am](https://cloud.githubusercontent.com/assets/12257213/9688338/06e9f71c-52db-11e5-9c17-3f17b7957db0.png)

**Comment by nallath** [comment]
Can't reproduce this for Ubuntu. The sequence remains the same.

**Comment by nallath** [comment]
Fixed for 15.09.82
