### ISSUE TITLE
Allow printer export which includes all related profiles

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3291]
I have created for myself multiple profiles for each of my printers.
Please allow exporting printers which includes all associated profiles or multi select multiple profiles for export.

**Comment by ianpaschal** [comment]
Internal ticket: CURA-5058

**Comment by Ghostkeeper** [comment]
Our project manager removed this from our planning because it isn't considered important. For now we won't consider working on this.
