### ISSUE TITLE
CuraEngine.exe has stopped working - When enabling Ironing feature

### ISSUE THREAD

**Issue by easycheese** [Ultimaker/Cura#3304]
Slicing while using the ironing feature fails for quality > .25

**Application Version**
3.1.0

**Platform**
Windows 10

**Qt**
Website version

**PyQt**
Website version

**Display Driver**
DxDiag attached

**Steps to Reproduce**
Load Prusa i3 Mk2 profile
Load any STL
Set quality to .4mm
Check 'Enable Ironing' 

**Actual Results**

CuraEngine.exe has stopped working

**Expected results**
STL slices successfully

**Additional Information**
If I manually set the layer height, I need to set it to .25 or lower before it will successfully slice

[cura.log](https://github.com/Ultimaker/Cura/files/1721997/cura.log)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/1721995/DxDiag.txt)
[PI3MK2_Laundry Holder.zip](https://github.com/Ultimaker/Cura/files/1722006/PI3MK2_Laundry.Holder.zip)

**Comment by diegopradogesto** [comment]
I could reproduce it in 3.1, but trying to do the same in 3.2 it's not happening. So I encourage you to try the new version and test whether the bug is still there or it is fixed.

**Comment by easycheese** [comment]
Ah yep, didn't realize that 3.2 was out.  It's working there, thanks!
