### ISSUE TITLE
UMO Printing doesn't send start.gcode first?

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#331]
Version: 15.09.8
OS X 10.9.5

After choosing "Print" from the print dialog, my UMO immediately starts printing without first heating up or homing the head.

**Comment by nallath** [comment]
Hmm, odd. We changed a ton of stuff in the settings files, so I'm guessing it failed finding the start-gcode and sending it. I'll have a look monday.

**Comment by nallath** [comment]
I can't reproduce this. I'm testing this on an umo+, which heats up fine when printing with USB.

**Comment by Xisle** [comment]
I tried again this morning and my printer IS heating up. I will report back if I can reproduce the original issue.
