### ISSUE TITLE
Extruder temperature 0°C

### ISSUE THREAD

**Issue by sfornengo** [Ultimaker/Cura#3311]
**Application Version**
Cura 3.2 / 3.1

**Platform**
Ubuntu 16.04

I am using Cura AppImage. My printer is a printrBot simple metal.
The reported extruder is 0°C and the setpoint is also 0°C... the printing never start.
I must close and restart cura 3.2 multiple times and sometimes the setpoint and the extruder temperature are ok, and then I can succeed to print.
However, during the nozzle temperature rise, the displayed temperature is not updated although I can confirm it is heating. This problem of update was also present in Cura 3.1.

**Comment by alekseisasin** [comment]
Hi @sfornengo  . What do you mean under "succeed to print"? Do you mean  print over network or save as file ? Did you have same problem with Cura 3.0?
Did you try contact Printbot and ensure that this happens with all printers (printrBot simple) of this brand. 
We do not have an issue with Ultimaker printers and it is difficult to find the reason why it does not work without having the Printbot printer.

**Comment by sfornengo** [comment]
I am printing via USB.
It worked with old Cura version, so something has changed in 3.1 and 3.2

**Comment by Ghostkeeper** [comment]
Perhaps you could load up Prontrface and see what the printer responds when you send the "M105" g-code command? That's what Cura uses to request the temperature.

**Comment by Raul-VLC** [comment]
Hi, I have the same problem. 
Extruder temp 0º and I check with PronterFace and says 16º of extruder temp.

![captura de pantalla 2018-03-20 22 12 17](https://user-images.githubusercontent.com/37598655/37683393-c447adf8-2c8c-11e8-91f1-000453f85dd7.png)
![captura de pantalla 2018-03-20 21 53 29 2](https://user-images.githubusercontent.com/37598655/37683394-c46a5312-2c8c-11e8-8a50-fe215e5c6814.png)

So, in Cura 3.2.1 it doesn't start to print, always stay in "printing 0%". 
In older Cura, we printed normally, with the same machine yesterday.
I cancel the print, and I can move correctly X, Z & Y axis... 
Can you help me please?

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?
