### ISSUE TITLE
Multiple Extruders - Differences and Syncing

### ISSUE THREAD

**Issue by gregspruce** [Ultimaker/Cura#3314]
I'd really like an icon that would show next to a setting when the setting is different between extruder 1 and extruder 2.
I'd also like an easy way to sync all settings, or even section by section, between the 2 extruders.

Edit: Also, a way to display the settings for both extruders simultaneously instead of having 1 tab always hidden.

**Comment by Ghostkeeper** [comment]
It's easier for us if you make 3 issues if you have 3 feature requests. Then we can more easily say yay or nay to each.

* You'd see this icon for nearly all commonly-used settings if you have different materials loaded. I don't think that's really desirable.
* The easier syncing between extruders is indeed in our planning. But we're not yet quite sure how to approach this. Syncing categories of settings can cause lots of things to go wrong in a print. At least if you're syncing setting-per-setting (right click on a setting, then "Copy value to all extruders") it's more of an explicit action that the user must know about. So if you have some suggestions we'd love to hear them.
* Displaying settings for both extruders simultaneously becomes a bit difficult if you have 8 extruders.

**Comment by ChrisTerBeke** [comment]
We now have "copy to all extruders" and "copy all settings to all extruders" when right-clicking on a settings. This should fix this ticket. If not, please re-open.

**Comment by VasiliyRock** [comment]
It would be convenient to add the "Copy value for all extruders" buttons next to each value. And like to see a similar button not only for the value, but also for the section.

**Comment by Ghostkeeper** [comment]
That real estate in the settings list is too valuable to add a button there for copying settings between extruders, in my opinion. I think the context menu thing is fine.
