### ISSUE TITLE
Cura 3.2.1 Build plate model reloaded and centered when reloading all models

### ISSUE THREAD

**Issue by PvtPrivate** [Ultimaker/Cura#3315]
**Application Version**
Cura 3.2
Cura 3.2.1

**Platform**
Windows 10

**Steps to Reproduce**
1. Import any model
2. Reload all models (F5)

**Actual Results**
All models are reloaded, but the buildplate model and nozzle model also gets reloaded and centered.

**Expected results**
All models are reloaded, no changes on build plate and nozzle model.

**Additional Information**
Before:
![image](https://user-images.githubusercontent.com/16520813/36219520-4e39c7c0-11ea-11e8-94bb-581379ed19f9.png)
After:
![image](https://user-images.githubusercontent.com/16520813/36219607-8aace110-11ea-11e8-815b-21b5595fe896.png)
![image](https://user-images.githubusercontent.com/16520813/36219635-a47e84cc-11ea-11e8-9562-44b8b96a9286.png)

**Comment by Vandrasc** [comment]
Hi @PvtPrivate, good catch, thank you for reporting it!

Devs see Cura-4963!

**Comment by ianpaschal** [comment]
Fixed as of today. Should be in the next release.
