### ISSUE TITLE
Incomplete files for 3.2

### ISSUE THREAD

**Issue by hairbandrocker76** [Ultimaker/Cura#3317]
Since the latest update, I'm not getting full prints.  The print will just stop early as if it is complete or it will get a SD read card error and sit there cooking the filament in the nozzle.  Has happened twice over 5 prints.  I make sure the file is completely copied to the sd card before ejecting it but it still happens.  Please look into this.  Thank you.
-->

**Application Version**

**Platform**

**Steps to Reproduce**

**Comment by ianpaschal** [comment]
Can you share some example files that did not print successfully (mesh and gcode)? That way we can analyze them for potential problems but right now it could be a hundred things, many of which are not related to the software.

**Comment by hairbandrocker76** [comment]
I'm sorry, I don't have any now.  I deleted them and re did the prints.
Invite dies it again I'll hang on to it and send it out to you.  Thanks

**Comment by ianpaschal** [comment]
That's understandable. Just deleting and trying again is my first instinct as well in such cases.

Keep us posted.

**Comment by Ghostkeeper** [comment]
Were you using adaptive layer height with these prints?

**Comment by hairbandrocker76** [comment]
Hello.  No I wasn't.  I haven't used that option yet.  I haven't come
across this problem again thankfully.  I'll let you know if it does
though.  thank you for the follow up.

Thomas

**Comment by Ghostkeeper** [comment]
We aren't able to reproduce this.

I think Hairbandrocker76 hasn't been able to reproduce this either, so let's hope it fixed itself in the meanwhile.
