### ISSUE TITLE
cura 3.2.1 wrong full window on Mac hight sierra

### ISSUE THREAD

**Issue by meeroczz** [Ultimaker/Cura#3319]
on Mac High Sierra, the Cura app 3.2.1 is not maximising to the full window. 
The dashboard is kept on, unhidden, not using the whole screen.

**Comment by ianpaschal** [comment]
I believe this is intentional. Lots of "professional" software is not meant to go full scale.
Another example of this would be all the Adobe software such as Photoshop.

Perhaps another member of the Cura team could confirm or disconfirm if this is the case.

**Comment by Appesteijn** [comment]
You are right, we don't hide the menu-bar. This won't be fixed in the near future.

**Comment by ianpaschal** [comment]
Closing. Can always re-open at a later time.
