### ISSUE TITLE
2 color slicing overlapping filament

### ISSUE THREAD

**Issue by notmine642** [Ultimaker/Cura#3322]
Hello, 

I am trying to print a QR code using 2 different color.
It seems that the slicer make some layer overlapping...
hard to explain, I have attached pictures, Git does not accept the project.
Thanks for your help
layer 10
![image](https://user-images.githubusercontent.com/36200667/36260378-8bb35130-1261-11e8-862d-59c714a40515.png)
layer 9

![image](https://user-images.githubusercontent.com/36200667/36260390-9627a238-1261-11e8-9ca3-b260153cc435.png)

**Comment by Ghostkeeper** [comment]
Github will accept your project or models if you put it in a .zip.

**Comment by Ghostkeeper** [comment]
It's kind of hard to debug this without it occurring on my side. Maybe you can play a bit with the "Union Overlapping Volumes" setting, or "Alternate Mesh Removal"?

**Comment by ianpaschal** [comment]
Haven't heard back from OP so I'm closing this for now.
