### ISSUE TITLE
Experimental **Infill travel optimization** on multiple pieces wont work.

### ISSUE THREAD

**Issue by kapperi** [Ultimaker/Cura#3327]
**Application Version**
 3.2

**Platform**
 Windows 10

**Qt**
 Official

**PyQt**
 Official

**Display Driver**
 

**Steps to Reproduce**
 Optimization on with multiple pieces.

**Actual Results**
 Optimiztion wont work.

**Expected results**
 Expect to work like in one piece slicing.

**Additional Information**

**Comment by smartavionics** [comment]
The infill travel optimization only affects the travels within a single part.It does not attempt to modify the travels when multiple parts are being printed.

Just to make sure I understand your issue, please post a screen shot showing the parts and their infill. Thanks.
