### ISSUE TITLE
Preferances/Configer Cura/General/Materials/Print Settings crashing

### ISSUE THREAD

**Issue by 3dbuildmono** [Ultimaker/Cura#3328]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ChrisTerBeke** [comment]
Can you be more specific? Which error are you seeing? Can you share your user settings so we can see what's wrong?
