### ISSUE TITLE
[3.2.1] Bed Temp Not Shown in Monitor

### ISSUE THREAD

**Issue by Nuklear47** [Ultimaker/Cura#3332]
**Application Version**
3.2.1 and earlier (3.0.4 works ok)

**Platform**
Older Hictop I3 Mk2

**Display Driver**
NVIDIA GeForce 710

**Steps to Reproduce**
whenever Cura 3.2.1 or earlier is opened (3.0.4 works ok) you go preheat the bed and the current temp
is shown as 0 degrees even though the temp is ambient or current bed temp.

**Expected results**
This should be self explanitory...

**Additional Information**
3.0.4 worked ok originally then i upgraded to 3.1 and lost bed temp info in the monitor screen

**Comment by slundell** [comment]
Are you printing over USB/Serial?

**Comment by Nuklear47** [comment]
Usb

On Feb 21, 2018 6:16 AM, "slundell" <notifications@github.com> wrote:

Are you printing over USB/Serial?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/Cura/issues/3332#issuecomment-367339478>, or mute
the thread

**Comment by alekseisasin** [comment]
Hi @Nuklear47, did you succeed to send manually M105 command. Or do you still have the same issue in the latest Cura ?

**Comment by Nuklear47** [comment]
It was just cura being glitch, now that they have updated it works again

**Comment by diegopradogesto** [comment]
Good to hear! I will close the issue then.

Which version are you using now, that you say it works? Is it 3.4.1?
