### ISSUE TITLE
Autoscale Failing in 3.2.1

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#3333]
Autoscaling of large models fails in 3.2.1 (Mac OS).

I have a few models in meters that scaled fine to bed size with previous version but do no longer with 3.2.1.
With autoscale turned on the message says it automatically scaled to 0% and does not show the model at all, with autoscale turned of in settings the message says the same and Cura stops responding.

**Comment by ianpaschal** [comment]
@alekseisasin Is this the bug you fixed the other day? Can we close this?

**Comment by alekseisasin** [comment]
@ianpaschal , yes, sure. The issue was fixed.
