### ISSUE TITLE
[3.2.1] badly formatted "printing time"

### ISSUE THREAD

**Issue by cmock** [Ultimaker/Cura#3343]
**Application Version**

Cura 3.2.1 Appimage

**Platform**

Debian 9 / amd64

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Print something and watch under "Monitor", and see negative minutes:
![time](https://user-images.githubusercontent.com/2141141/36342874-ff0cbb7c-1404-11e8-8c20-8660cc7d96c0.png)

I've also seen the "minus" sign in the "seconds" field.

**Actual Results**

Negative minutes shown.

**Expected results**

positive minutes.

**Additional Information**

**Comment by GMagician** [comment]
I confirm issue, I had same yesterday

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this. When putting any value as input in our `getPrettyTime()` function that's used there, the minutes and seconds are always positive.

When I tried actually printing (via USB) the printing time also stayed positive.

**Comment by cmock** [comment]
``getPrettyTime()`` was the right hint: look at the code in the 3.2 branch and at commit af89209cdeb31eec4abf9ebcb30266239ac35676 which probably has fixed this issue...
