### ISSUE TITLE
[3.2.0] "Abort Print" cancels another (ongoing) session on Octopi instead of the last one running through USB

### ISSUE THREAD

**Issue by D4rw1n0zor** [Ultimaker/Cura#3349]
**Application Version**
Cura 3.2.0 from Ultimaker

**Platform**
macOS Sierra 10.12.6 & Octoprint Version 1.3.6

**Steps to Reproduce**
In this scenario, 2 printers are being used. The first one is connected via USB to octoprint server. The second printer is connected to the laptop via USB.

1) Configure 2 different printer profiles that share the same octopi IP address though.
2) Setup your custom slicer settings, prepare the print and then hit the button "Print with Octoprint".
3) Once the print has started, cancel the print from octoprint WEB interface.
4) re-start the print from octoprint interface (from the list of latest prints).
5) With Cura still open, select the second printer profile in your printers list.
6) Setup your custom slicer settings, prepare the print and then hit the button "Print via USB".
7) Hit "Abort print" when the directly attached 3d printer is heating.

**Actual Results**
Outcome of this described scenario is a cancellation of the print on the Octoprint (i.e. first 3d printer), and not on your last selected 3d printer.

**Expected results**
Cura should drop all memory of ongoing session once we change the profile and/or decide to print using another connection type, i.e. changing from Octoprint to local USB or the opposite.

**Additional Information**
Having both printer profiles sharing the same IP address is, IMHO, a common use case. I'm used to connect my octopi to my Tevo tornado or my Anycubic delta when I want to run a long 3d print (>10 hours) and keep the possibility to shutdown my laptop when it's printing.

**Comment by ChrisTerBeke** [comment]
Sounds like a bug where the incorrect output device is used to execute the abort command. The output devices have been completely refactored for the 3.3 release, so I expect it to be fixed in that release. Closing for now, please re-open if 3.3 also has this problem

**Comment by Ghostkeeper** [comment]
This is still happening in 3.3.

The Abort button cancels the print that's going on in the currently active device. The currently active device is the one selected in the drop-down where you choose to print via USB or to print via Octoprint. It doesn't cancel the one that was started last. It cancels the one that's currently active.

So this is expected behaviour currently.
