### ISSUE TITLE
Changelog text encoding

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#335]
Version: 15.09.80
Platform: Windows 7
Qt: 5.4.1
PyQt: 5.4.1

Expected behaviour:

* Cura launches after installing and displays a changelog describing what changed since the last version.

Observed behaviour:

* The changelog appears, but at several places, characters are replaced by symbols that shouldn't be there. It looks like this:

![Changelog with encoding errors](https://i.imgur.com/jEt3sxE.png)

**Comment by BagelOrb** [comment]
Same on my home computer with Windows 7
