### ISSUE TITLE
Rimane inattivo la parte riguardante separa o raggruppa modelli.... perchè?

### ISSUE THREAD

**Issue by Sandro47** [Ultimaker/Cura#3355]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Appesteijn** [comment]
Our Italian is a little bit rusty, could you ask in English please?

**Comment by Sandro47** [comment]
Problema risolto.... Grazie.
