### ISSUE TITLE
[3.2.1] No temp shown for 2nd nozzle

### ISSUE THREAD

**Issue by GMagician** [Ultimaker/Cura#3361]
**Application Version**
Cura 3.2.1

**Platform**
Windows 10

**Display Driver**
ATI unknown ver

**Steps to Reproduce**
Create a custom printer with 2 nozzle

**Actual Results**
No temperature on 2nd nozzle, just on 1st

**Expected results**
Temperature value shown for both nozzles

As noted above with a printer with 2 nozzle everything can be managed but temp of 2nd nozzle is not shown

**Comment by fieldOfView** [comment]
Needs more info:
What printer, what printer definition (Custom FDM Printer?), are you using USB printing or OctoPrint, what do the logs say?

**Comment by GMagician** [comment]
Yes, started from Custom FDM printer and using USB, I'll check log

**Comment by GMagician** [comment]
> 2018-02-20 21:51:14,880 - WARNING - [(1236)-Thread-10] USBPrinting.USBPrinterOutputDevice._listen [567]: Could not parse hotend temperatures from response: b'ok T:21.47 /0.00 B:24.00 /0.00 T0:21.47 /0.00 T1:21.16 /0.00 @:0 B@:0 @0:0 @1:0\n'

I think that is is almost clear...
I don't know what should be correct message from Marlin to be correctly parsed.
If you can help me I could post a PR to it

**Comment by fieldOfView** [comment]
I currently don’t think the message from the firmware is wrong, but the parsing makes a wrong assumption about something. I screwed up a little hiding the actual error. I hope to have time thursday to try to reproduce the issue and create a fix for it.

**Comment by GMagician** [comment]
Duplicated report. I close mine since #3563 is newer and has been labeled as bug

**Comment by kirilledelman** [comment]
@GMagician when you say "everything can be managed but temp of 2nd nozzle is not shown", does that mean you were able to preheat, and start print, despite this bug? I'm 99% done putting together a dual extruder upgrade, and encountered this bug while testing. Wasn't sure if I'll be able to print.

**Comment by GMagician** [comment]
@kirilledelman sorry but I'm also starting up my printer. Just 1 extruder is working now.
I made some gcode test and I saw that T0/1 commands are generated but I saw some strange things with temperature. It lower extruder temp before changing to new extruder but temp is not the same with T1 and T0. Not investigated further

**Comment by kirilledelman** [comment]
@GMagician I'll finish my setup, try printing with two nozzles, and report back.
