### ISSUE TITLE
15.09.80: Setting dialogs linked

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#338]
Application Version: 15.09.80

Steps to Reproduce:
-Enable "Infill density" and "infill thickness"
-Set infill density
-Set infill thickness

Actual Results:
-Value entered for infill thickness also populates infill density

Expected results:
-Value only populates the highlighted field.

This is also happening in other related fields. Luckily it doesn't happen in reverse, so it is possible to get them set correctly.

**Comment by CCS86** [comment]
Setting Z-hop distance overwrites printing temperature as well.

**Comment by CCS86** [comment]
Clearing the "spiralize" setting also clears the "print sequence" field

**Comment by nallath** [comment]
Confirmed the issue.

**Comment by nallath** [comment]
Hmm, It seems to always change the first setting of a category.
