### ISSUE TITLE
Visibility of execution time not readable in german version

### ISSUE THREAD

**Issue by Diavolothecat** [Ultimaker/Cura#3380]
**Application Version**
CURA 3.2.1

**Platform**
Windows 10

**Display Driver**
Intel 1920x1080 resolution

**Steps to Reproduce**
Set german language and introduce some SD or USB storage

**Actual Results**
The text "Speichern auf Wechseldatenträger" is too large. So it makes execution time left beside unreadable.

**Expected results**
Proposal: Show Icon instead of text button or use smaller font for large text.

![cura issue](https://user-images.githubusercontent.com/36756671/36582327-5a2db2c0-1871-11e8-9265-fd54d5e5caf0.png)

**Comment by ianpaschal** [comment]
Related to #3385.

**Comment by Ghostkeeper** [comment]
If you're a native German speaker and you've got a better suggestion for what should be displayed on the button, please let us know.
We hired a translation bureau to make this translation for us but they don't always have the knowledge of how much space they can use.

**Comment by Diavolothecat** [comment]
Hello,
I speak that language fluently. I suggest, you replace "Speichern auf Wechseldatenträger" by "Auf Datenträger speichern". By the way, you could also replace "Speichern in Datei" by "In Datei speichern". I understand your difficulties because I'm also working sometimes on UI.

**Comment by Ghostkeeper** [comment]
We've now changed it to "Speichern auf Datenträger" which makes it a bit better to read.
