### ISSUE TITLE
MAC Couldn't find  Arcus,fixed already ，Mac电脑安装，提示找不到Arcus,已解决

### ISSUE THREAD

**Issue by yiyu1234654** [Ultimaker/Cura#3384]
CMake Error at CMakeLists.txt:24 (get_filename_component):
  **get_filename_component unknown component CACHE**

CMake Error at projects/CuraEngine.cmake:1 (find_package):
  By not providing "FindArcus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Arcus", but
  CMake did not find one.

  **Could not find a package configuration file provided by "Arcus" (requested
  version 1.1) with any of the following names:**

    ArcusConfig.cmake
    arcus-config.cmake

  Add the installation prefix of "Arcus" to CMAKE_PREFIX_PATH or set
  "Arcus_DIR" to a directory containing one of the above files.  If "Arcus"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)

-- Configuring incomplete, errors occurred!

===========================================
the solution:
1 https://github.com/Ultimaker/cura-build-environment  ,build the environment first.
now build the environment first.
according the README.md ,you should change the following line:
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_BUILD_TYPE=Release  
to cmake .. -DCMAKE_INSTALL_PREFIX=**~/workspace/python/cura_env_build**  -DCMAKE_BUILD_TYPE=Release  
notice here,~/workspace/python/cura_env_build is my absolute path in my system, you can change the build path to other path
After you build the environment(you will encounter many strange problem),go to the step2 

2  now we begin to build cura
cmake ..           ----->>>>.   change to the following line
cmake ..  -DCMAKE_PREFIX_PATH=~/workspace/python/cura_env_build/

then the error disappear

================我用中文再简单说一下，国人的外语可能不那么好============
上面的提示有两个错误，一个是不认识CACHE,另一个是找不到Arcus,这两个错误应该都是同一个原因，错误提示里面有这样一句话“Add the installation prefix of "Arcus" to CMAKE_PREFIX_PATH ”，想必大伙是一脸蒙B,解决方案就是，先把cura依赖的环境安装起来先，链接看这个
https://github.com/Ultimaker/cura-build-environment
安装过程中，设置一下自己的安装路径 
cmake .. -DCMAKE_INSTALL_PREFIX=**~/workspace/python/cura_env_build**  -DCMAKE_BUILD_TYPE=Release  

在安装过程中，会遇到很多奇怪的总是，根据我的记忆，大概会有这样几个问题
1 在安装QT的过程中，会遇到一个文件的源码编译不过，找到该源码，把出错的那几行注释掉（我那出错的几行，删除掉不会有太多影响）
2 安装的过程中，调setup.py的时候，会提示找不到setuptools未安装，原因是python调的是刚刚编译出来的python(在你的安装路径下)，而不是系统路径，解决办法是在自己的电脑上，先安装python3.5,然后通过pip3 install setuptools,安装一下，然后再python  系统路径的site-packages找到setuptools文件夹，整个复制到你的安装路径下的site-packages,你如果用pycharm集成工具的话，找文件夹会方便一点，以后但凡缺什么库，你都用此方法。当然可能还有其他办法，主要是没有在安装路径下找到pip,所以只能先能用这种笨方法
3 后面还会出现setup.py 有个什么选项--single-version-externally 不认识，你找到相关的.mk文件，将这个选项去掉，你用pycharm找会比较快一点
4 后面在安装protobuf的时候，会重复下载好几次，然后错误停止，原因是md5检验不对，通过pycharm找到所有原md5，全部替换成新的md5就可以了
5 再会遇到一个提示pytest-runner下载不了的错误，仔细看提示，在前面还有一个找不到cython的警告，其实你只要把cython，pytest-runner,pytest,先都在系统上安装好，然后再复制到安装路径下的site-packages下，即可

环境全部安装好之后，再回到cura-build路径下来
cmake ..          将这一个命令改下下面这个就可以了，注意，后面的路径是你实际安装路径，不要原样抄
cmake ..  -DCMAKE_PREFIX_PATH=~/workspace/python/cura_env_build/

**Comment by ianpaschal** [comment]
Our Chinese colleague says that 已解决 means "fixed" so I am closing this ticket. I'm glad you were able to work it out.

For future reference, please only use English here, so that way more people in the future can read your solution.
