### ISSUE TITLE
Print via usb does not start

### ISSUE THREAD

**Issue by Enano79** [Ultimaker/Cura#3388]
**Application Version**
CURA 3.2.1

**Platform**
Windows 7

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**
I have a Prusa i3  and with this new version when I try to print via usb. Does not do any thing. if I cancel the printing IT got to home. 
Does not start to heating .. nothing. I have try to pre heat and thats works. regads

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment]
Hi, can you share your log files or an example project which fails?

**Comment by Enano79** [comment]
Sorry I cant find the log file. 
Also I have install again version 3.1.0 and print with that leaving both version installed.
today trying to find the logs, I have send a print on 3.2.1 and Seems like is working

I will let you know THANKS!!!!

**Comment by Ghostkeeper** [comment]
Looks like it was fixed with Cura 3.2 then.
