### ISSUE TITLE
Print to USB Button Submenu

### ISSUE THREAD

**Issue by julianmallett** [Ultimaker/Cura#3394]
**Application Version**
3.2.1

**Platform**
Mac osX 10.13.3 Sierra

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
Plug USB cable in to Anycubic Kossel Delta, goto to select print to USB.

**Actual Results**
 The selection scroll button is off to the very top right hand of the screen and not immediately obvious.

**Expected results**
Would expect the choice between print to file and print to USB to be visible near the print button.

**Additional Information**
<img width="1277" alt="cura3 2 1-macosx siera" src="https://user-images.githubusercontent.com/32347136/36639623-937515ee-1a08-11e8-83e3-f5f789869f1c.png">

**Comment by fieldOfView** [comment]
This should go away after resizing the window. It is something that has happened sometimes, but it happens in the UI framework we use which makes it hard for us to fix, other than shipping with an upgraded version of the framework.

**Comment by julianmallett** [comment]
Many thanks, that worked for me.
have a great day

Julian
