### ISSUE TITLE
[3.2.1] Non-Uniform Scaling Misbehaviour

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#3395]
**Application Version**
3.2.1

**Platform**
Windows 10

**Display Driver**
AMD 18.2.1

**Steps to Reproduce / Actual Results**
Add a cube turn off Uniform Scaling and scale Z, X or Y then try and scale it back once the mouse goes passed the gray marker it start scaling the wrong way, This is really annoying when trying to use the model as a Mesh Type for custom support or infill for eg.

![nnuniscale](https://user-images.githubusercontent.com/2055566/36640804-93843c0a-1a75-11e8-95c6-113af1b609c2.gif)

**Expected results**
It keep scaling the correct way.

**Comment by Ghostkeeper** [comment]
Fixed in 4.0.

**Comment by Ghostkeeper** [comment]
Ah, nevermind. I misunderstood. The scale goes at the proper speed now, but still becomes larger when going beyond the origin since it just depends on the distance to the origin.

**Comment by GregValiant** [comment]
This does not seem to be a problem in current versions of Cura (5.8.0 and up).  I'll go ahead and close this.
