### ISSUE TITLE
Moving/rotating model arrows stay in old position after Reset model position

### ISSUE THREAD

**Issue by mvangils** [Ultimaker/Cura#34]
Application Version: << 15.05.93>>
Platform: << Win7 64bit >>
Qt: << The version of Qt used >>
PyQt: << The version of PyQt used >>
Display Driver: << intel graphics 8.15.10.2559 >>

Steps to Reproduce:
1. move model
2. rotate model
3. right click > reset all object positions.

Actual Results:
origin of the move/rotate arrows stays in position before reset.

Expected results:
The origin of the arrows should follow the model or disappear after reset.

Additional Information:

![cura bug](https://cloud.githubusercontent.com/assets/11736783/8055740/0c77cb96-0ea2-11e5-8c2b-1a27b43e0543.PNG)

**Comment by awhiemstra** [comment]
This has been fixed. See ttps://github.com/Ultimaker/Uranium/commit/01eb0fed31992f7278b4bad5559f693804293db0
