### ISSUE TITLE
15.09.80: False warning value

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#340]
Cura seems to be falsely reporting a top/bottom thickness value as an error here. I have tried acount for the initial layer height, and not accounting for it:

![image](https://cloud.githubusercontent.com/assets/12439543/9705330/068fedc8-5487-11e5-8a28-45ad016fb3dd.png)

![image](https://cloud.githubusercontent.com/assets/12439543/9705335/1accd63e-5487-11e5-881a-32cd9234428d.png)

**Comment by nallath** [comment]
Confirmed.

**Comment by BagelOrb** [comment]
In the json it says: "max_value_warning": "1",
There shouldn't be a max value warning.

When infill is set to 100%, the bottom thickness is set to 999999 and the top thickness to 0. This way all infill is replaced by skin. Just to give you an idea why there shouldn't be a max value warning.
