### ISSUE TITLE
The letterfonts are broken on my Imac

### ISSUE THREAD

**Issue by Kitcarhans** [Ultimaker/Cura#3402]
Apple

It is also helpful to attach a project (.3MF) file and Cura log file so we can debug issues quicker.
Information about how to find the log file can be found at https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations.

Ther latest version in NL
**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment]
Can you please share a screen shot to show the problem?

But it sounds like a duplicate of #3277.

**Comment by Kitcarhans** [comment]
Ja, het is gezeefd probleem. Wat kan ik er aan doen?

Groet, Hans

**Comment by fieldOfView** [comment]
Read that issue. There's a newer test-build to download and test.

**Comment by Kitcarhans** [comment]
OK,

3.2.2 works for my. Thank you


Hans de Bruijn
hans@marhans.nl

**Comment by ianpaschal** [comment]
Good to hear!
