### ISSUE TITLE
15.09.80: Layout obscuring unit values

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#341]
![image](https://cloud.githubusercontent.com/assets/12439543/9705347/40a89168-5487-11e5-9fb6-5623bbc3724f.png)

**Comment by nallath** [comment]
A known issue. Thanks for reporting it.

**Comment by fieldOfView** [comment]
Instead of using a "R(eset)" button, a UI pattern for showing changes in settings I know from other applications (Firefox, Cinema4d, probably others) is to render the setting in bold. Double-click (and/or a context menu) to reset to the default setting.

**Comment by nallath** [comment]
Fixed for 15.09.82

**Comment by fieldOfView** [comment]
@Nallath: I would not necessarily agree the issue is fixed (though the button no longer overlays the units); now the [R] button is obscured by the scrollbar...

**Comment by nallath** [comment]
Technically that would make it a new issue. But you're right. We should fix that aswell (hadn't noticed that yet)

**Comment by CCS86** [comment]
Hey Jaime, will we see .82 on the beta site any time soon?

**Comment by awhiemstra** [comment]
@CCS86 Probably thursday
