### ISSUE TITLE
[3.2.1] Cura does not set bed temp according to material profile

### ISSUE THREAD

**Issue by pbartko** [Ultimaker/Cura#3415]
**Application Version**
3.2.1

**Steps to Reproduce**
Selecting Material from Material list to change printing temp and build plate temp.

**Actual Results**
Printing temperature is changed, but build plate temp is not changed.

**Expected results**
build plate temp should be changed when changing material

![image](https://user-images.githubusercontent.com/34517866/36822831-1d3ffc46-1cc8-11e8-8a4c-495564e69ff6.png)

![image](https://user-images.githubusercontent.com/34517866/36822867-55f10242-1cc8-11e8-9232-a879204568ee.png)

**Comment by ianpaschal** [comment]
Pretty sure this would be fixed by the refactor, right @jackha @LipuFei ?

**Comment by LipuFei** [comment]
@ianpaschal Fixed in the refactor
