### ISSUE TITLE
Make zoom factor editable

### ISSUE THREAD

**Issue by herrdeh** [Ultimaker/Cura#3430]
On my ubuntu system, the zoom by the mouse wheel does very big zoom steps, and so do the + and - keys. - I'd like very much a control where I can could change the zoom factor per keystroke or per mouse wheel rotation degree.

**Comment by Ghostkeeper** [comment]
Isn't this quite... specific for a preference though? I can't imagine a lot of people will feel the need to adjust their zoom speed.

**Comment by ianpaschal** [comment]
Agreed. I'd be in favor of actually listing this as a won't do as I think adding more settings actually will detract more than improve the software.

**Comment by Ghostkeeper** [comment]
Let's just suggest then to adjust the scroll speed in your OS as a workaround.
