### ISSUE TITLE
[3.2.1] Maybe a bug?

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3434]
Hello,

When I use this command at "start gcode" section:
M140 S{material_bed_temperature_layer_0}

The command M190 Sxxx from settings > Material > Plate temperature initial layer  is completely ignored...

**Comment by ianpaschal** [comment]
Please share some examples/screen shots as well as providing other information such as what platform you're on, what printer you're using, etc.

**Comment by mtmello2003** [comment]
Using win10 x64

When I set in Material > Build Plate temperature initial layer, gcode give a M190 Sxxx command:
![b1](https://user-images.githubusercontent.com/15361590/36947808-cd46d9fe-1faf-11e8-9420-2ff1cf785ad6.png)

![b2](https://user-images.githubusercontent.com/15361590/36947809-d248b026-1faf-11e8-95ca-aa5deabaf055.png)

But if I set M140 in start code, my setting in Material looks like is ignored:
![b3](https://user-images.githubusercontent.com/15361590/36947821-eec8bfde-1faf-11e8-9933-d1c2623f61b1.png)

![b4](https://user-images.githubusercontent.com/15361590/36947823-f6e08e0e-1faf-11e8-99d5-172ca8857b62.png)

**Comment by fieldOfView** [comment]
That’s by design. Cura checks if your startgcode contains bed preheating commands. If it does, Cura won’t add preheat commands of its own. Same with extruder preheating commands

**Comment by Ghostkeeper** [comment]
Maybe we should look for `M140` or `M190` commands instead?
