### ISSUE TITLE
[3.2.1] Top Layer incomplete

### ISSUE THREAD

**Issue by mcdum** [Ultimaker/Cura#3435]
**Application Version**
3.2.1

**Platform**
Linux - Xubuntu

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

ANET A8 Merlin gcode
Same setup for both Cura versions.

![img_9336](https://user-images.githubusercontent.com/37039846/36945414-85a86228-1fb6-11e8-930a-6994d0f8dc7c.JPG)
![img_9337](https://user-images.githubusercontent.com/37039846/36945415-8632d548-1fb6-11e8-9e45-1d352cbbeea3.JPG)
![img_9342](https://user-images.githubusercontent.com/37039846/36945417-866ec8fa-1fb6-11e8-9e47-39df81c2fd63.JPG)
![img_9344](https://user-images.githubusercontent.com/37039846/36945418-869b0cd0-1fb6-11e8-9882-68bd52c5837d.JPG)

https://www.dropbox.com/s/ek9ht6nplbzid78/TEST.curaproject.3mf?dl=0

**Comment by fieldOfView** [comment]
Could you try the following: open the gcode in a decent texteditor, and put -say- 20 lines of dummy text to the end of the file, each line prepended with a ;

I have seen reports that some marlin firmwares eat the last couple of lines of the gcode file. Cura 3.2.1 does not always add the profile settings to the end of the gcode file.

**Comment by Ghostkeeper** [comment]
The reports that you saw were specific to Ultimaker 2, fieldOfView. The bug was in the Ultimaker 2 display code for the main menu (yeah don't ask).

I am interested in knowing the difference in the g-code between these two prints. Maybe you could zip them up and post them here? Or provide a project file that can be opened in both Cura versions, created in Cura 3.1?

**Comment by mcdum** [comment]
I send you a zip with g-code from Cura 3.1 and Cura 3.2 with project file. Difference in g-code in parts position because Cura 3.2 don't import correct position of parts from Cura 3.1.

    On Wednesday, March 28, 2018, 4:51:13 PM GMT+3, Ghostkeeper <notifications@github.com> wrote:  
 
 
The reports that you saw were specific to Ultimaker 2, fieldOfView. The bug was in the Ultimaker 2 display code for the main menu (yeah don't ask).

I am interested in knowing the difference in the g-code between these two prints. Maybe you could zip them up and post them here? Or provide a project file that can be opened in both Cura versions, created in Cura 3.1?

**Comment by Ghostkeeper** [comment]
Attachments via e-mail submissions to Github don't work. You'll have to upload an attachment via the website.

**Comment by ChrisTerBeke** [comment]
No new info was added. Closing.
