### ISSUE TITLE
[3.2.1] Dual extrusion - Prime Tower incomplete 

### ISSUE THREAD

**Issue by J-charles-C** [Ultimaker/Cura#3441]
**Application Version : 3.2.1
**Platform : OSX

**Steps to Reproduce**

Sorry  for my english.
I have an E3D Chimera head with on nozzle of 0.4mm and one of 0.8mm.
Parameters for the two extruders are the same.

When i select extruder one for large part and extruder two for detail, all is ok. 
![2](https://user-images.githubusercontent.com/22807221/37015884-f450a31c-2109-11e8-8692-2c6b98bb70fa.jpeg)

But if i reverse, tower is not complete ans is mid air.
![test 1](https://user-images.githubusercontent.com/22807221/37015885-f46daa34-2109-11e8-8748-fc5c341db83f.jpeg)

I have this problem with another STL dual color
https://www.thingiverse.com/thing:1681618

regards

**Comment by BagelOrb** [comment]
Please attach your project file.

**Comment by BagelOrb** [comment]
The prime tower should at least have a thickness of twice the nozzle size, so it should be 1.6.

**Comment by J-charles-C** [comment]
I,

Exact. All is ok.  Many thanks.

regards
