### ISSUE TITLE
Missing layers in G Code

### ISSUE THREAD

**Issue by TyNiDesign** [Ultimaker/Cura#3444]
Exporting from Solidworks 2014 as STL. When I preview layer view there are missing layers, the same thing happens when I print it.

I have tried changing the definition of the STL file and this has made no difference.
![layers](https://user-images.githubusercontent.com/37112578/37037234-c34b4d86-2149-11e8-9032-c0338e7c0065.jpg)

**Comment by smartavionics** [comment]
Could you please make the STL available?

**Comment by TyNiDesign** [comment]
Hi Mark,

 

Thanks for the quick reply.

 

Attached is the STL file.

 

I’m currently using Cura 3.2.1

 

Best regards,

 

Steve

 

email reply

**Comment by smartavionics** [comment]
Sorry, attachments don't work with emails to github, please send it directly to markb@smartavionics.com

**Comment by smartavionics** [comment]
Hi Steve, I loaded that STL into FreeCAD and nothing was displayed and it reported a whole bunch of problems so I don't think Cura can make a good job of that.

![screenshot_2018-03-06_15-35-21](https://user-images.githubusercontent.com/585618/37041413-15971cb4-2154-11e8-91f6-47e82841589d.png)

**Comment by TyNiDesign** [comment]
Thanks! I will take a look at freeCAD.

⁣Sent from Blue ​

**Comment by alekseisasin** [comment]
@TyNiDesign , how is your model, did you find the issue?

**Comment by TyNiDesign** [comment]
Yes fixed the problem. Solidworks was exporting a corrupt STL. I used FreeCAD to create the STL and all is now perfect.

⁣Sent from Blue ​
