### ISSUE TITLE
[3.2.1] Retraction invariably enabled

### ISSUE THREAD

**Issue by williamlcordes** [Ultimaker/Cura#3453]
**Application Version**
Cura 3.2.1

**Platform**
Windows 10

**Printer**
Custom - MP Mini Delta

**Steps to Reproduce**
From Preferences > Settings > Materials - Enable Retraction (Not Selected)

**Actual Results**
Retraction is always engaged regardless of settings selected. 

**Expected results**
I would expect no retraction when retraction is not enabled. 

**Additional Information**
I've adjusted subsettings within Retraction and within Travel to minimize blobbing and no change made seems to have any effect on any part of the retraction. 

[WLC-Table.zip](https://github.com/Ultimaker/Cura/files/1791666/WLC-Table.zip)

**Comment by ChrisTerBeke** [comment]
Mm I can't reproduce this using an Ultimaker 3 with normal settings (then just exporting G-code with and without retraction enabled). I can't test with an MP Mini Delta, but I expect it's some different settings in that machine that might cause it?

**Comment by ianpaschal** [comment]
This hasn't gotten any more info for almost 3 months, so it's a cold case.
