### ISSUE TITLE
[3.2.1][2.7]Print job "larger than build volume" issue  ultimaker3 extended

### ISSUE THREAD

**Issue by recarens** [Ultimaker/Cura#3454]
With curaEngine 3.2.1 I created a gcode correctly for Ultimaker3 extended with the default parameters of de ultimaker3_extended.def.json and the printer shows me: "This print job is larger than the printer's build volume." and if i load the same gcode from a Cura2.7 it loads correctly and i can print it.

For example, i can't print this object. It's build in CuraEngine 3.2 

![image](https://user-images.githubusercontent.com/7501288/37142757-4d57250c-22b9-11e8-9f0e-c5e0a8355aca.png)

Loading it from the usb :
![image](https://user-images.githubusercontent.com/7501288/37143306-1432d490-22bb-11e8-9cf6-9cecb0369cd3.png)

**Comment by recarens** [comment]
For example, is imposible is bigger than the base the object.

![image](https://user-images.githubusercontent.com/7501288/37142757-4d57250c-22b9-11e8-9f0e-c5e0a8355aca.png)

**Comment by recarens** [comment]
Loading it from the usb :
![image](https://user-images.githubusercontent.com/7501288/37143306-1432d490-22bb-11e8-9cf6-9cecb0369cd3.png)

**Comment by Ghostkeeper** [comment]
This was a bug in command line slicing that was fixed in 3.3.
