### ISSUE TITLE
[3.2.1] Camera stream not visible after upgrade

### ISSUE THREAD

**Issue by cdrose** [Ultimaker/Cura#3457]
**Application Version**
3.2.1

**Platform**
Windows

**Display Driver**
Intel HD Graphics 4000 20.19.15.4835

**Printer**
Ultimaker 3 Extended

**Steps to Reproduce**
After upgrade to 3.2.1 the camera stream is no longer visible in the Monitor tab. The stream is still available on http://<ip_address>:8080/?action=stream Everything else seems to be working nicely, I just cant watch my printer printing.

**Comment by ianpaschal** [comment]
Could you please share your log file so we can look for possible causes?

**Comment by cdrose** [comment]
[stderr.log](https://github.com/Ultimaker/Cura/files/1804464/stderr.log)
[stdout.log](https://github.com/Ultimaker/Cura/files/1804465/stdout.log)

**Comment by Legor** [comment]
Same problem here

**Comment by peteros85** [comment]
I have the same problem, Running Ultimaker 3 Extended over our company network, occasionally you will get a still from the camera but most of the time it wont load at all.

**Comment by cdrose** [comment]
Good to see its not just me!

I just did a clean install of Cura 3.2.1 on a machine that has never had Cura installed before and the issue is the same.

**Comment by peteros85** [comment]
Is this ever going to get looked in to? Its a big issue for me

**Comment by cdrose** [comment]
Just upgraded to 3.3.1 and this issue appears to be fixed. Although I also did a firmware update on the printer at the same time so I am not sure which of the two actions solved the problem.

**Comment by fieldOfView** [comment]
@peteros85, is it also fixed for you?

**Comment by Legor** [comment]
Problem for us is solved with the latest version 3.3.1

**Comment by ed8metzler** [comment]
Same problem on Octoprint 1.8.4 and Cura 4.13.1

**Comment by fieldOfView** [comment]
@ed8metzler, for problems with the OctoPrint plugin, please see https://github.com/fieldofview/cura-octoprintplugin/issues
