### ISSUE TITLE
Feature request - don't use case sensitive sorting of profile names

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3460]
**Application Version**

master branch

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Printer**

**Steps to Reproduce**

Click on profile selector - look at names in list!

**Actual Results**

Names are sorted with the upper-case names first followed by the lower case names.

**Expected results**

Names should be sorted in alphabetic order irrespective of the letter case.

**Additional Information**

As the title suggests, it would be nice if the profile names in the drop down list were sorted irrespective of  case.

**Comment by Ghostkeeper** [comment]
I agree. It's also very simple to do, so I've just done that in between: d8853b8a98618ba18d050a9b893c84df987c8845
