### ISSUE TITLE
[3.2.1] when supports are enabled, first layer will print only supports

### ISSUE THREAD

**Issue by Ragnarre** [Ultimaker/Cura#3467]
First layer without supports
![screenshot 2018-03-10 13 49 14](https://user-images.githubusercontent.com/10742617/37242012-e291a4be-246a-11e8-9c14-3c992382ced3.png)

First layer with supports
![screenshot 2018-03-10 13 50 18](https://user-images.githubusercontent.com/10742617/37242013-e2b0c9f2-246a-11e8-9110-0960134196c8.png)

**Application Version**
<!Cura 3.2.1>

**Platform**
Win 10 x64

**Comment by smartavionics** [comment]
This may be the same issue that I came across. I provided a fix for it (https://github.com/Ultimaker/CuraEngine/pull/685) but that hasn't yet made it into Cura. Hopefully, it will be in before 3.3 arrives.

**Comment by Ghostkeeper** [comment]
That pull request has been merged now.
