### ISSUE TITLE
[3.2.1] Layer Height + brim + Support =  issue

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3471]
Windows 10

When I set the layer height to 0.30, using brim and tree (or even regular) support, the layer 0 is on the air.

If I change the layer weight to 0.29 with all other option unchanged, layer 0 is ok.

![029](https://user-images.githubusercontent.com/15361590/37250367-a49705cc-24d9-11e8-9cd9-d7d98f94a560.png)

![030](https://user-images.githubusercontent.com/15361590/37250368-aaeca03a-24d9-11e8-9e6f-2e632aa191ed.png)

**Comment by diegopradogesto** [comment]
As a workaround you can play with the "slicing tolerance" setting and set it to "inclusive". Probably is related with it.

**Comment by ianpaschal** [comment]
Closing because `Duplicate`
