### ISSUE TITLE
Add G-code at the end of "one at a time" objects

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3480]
Can be great if there is an option to execute a custom gcode when cura end to print a piece and go to the next one when the option "one at a time" is set.

![cura](https://user-images.githubusercontent.com/15361590/37313497-3f619a90-262e-11e8-9bb6-f2456b0f8803.png)

I wish to add M600 for example, to change filament collor but the post script gcode do it only by layer, not by pieces at a time...

**Comment by BagelOrb** [comment]
Because one at a time printing is fundamentally a lot more difficult for dual extrusion machines, this feature won't have priority for ultimaker.

One at a time mode is disabled for dual extrusion printers.

**Comment by Ghostkeeper** [comment]
You can still print with only one of the nozzles on a dual extrusion printer though :stuck_out_tongue: 

In the post-processing script Filament Change you can give layer numbers that go beyond the first model though. If you have two models of 200 layers each, you should be able to indicate that it needs to pause at layer 75 and at layer 275, just like how Layer View indicates it.

**Comment by coreyfaure** [comment]
I would also like to see this feature, as I would like to add an M300 beep code after every individually printed object.
