### ISSUE TITLE
Support Direction (Angle)

### ISSUE THREAD

**Issue by darkdvd** [Ultimaker/Cura#3481]
I posted something on the forum Ultimaker:
https://community.ultimaker.com/topic/21946-support-direction-angle/

**Comment by ChrisTerBeke** [comment]
It seems indeed that there is no infill direction parameter for support infill. I've flagged this ticket with the correct tags.

**Comment by darkdvd** [comment]
Merci Chris !

**Comment by darkdvd** [comment]
I suggest adding a function to the supports management in CURA: "Support Direction".

By default, the supports are printed along the X and Y axes, regardless of the angle of the object.
(Note that the object is positioned by default along the X and Y axes as well).

In certain cases, the geometry of the object to be printed poses a problem during printing: this is particularly the case for objects intended to be molded (The walls of these objects generally have angles of 2 ° in order to optimize demolding, sometimes it is the design of the piece that uses very tight angles ...).

I took as an example the piece that hides the linear bearings of the UM3: this piece is intended to be made of molded plastic (1905-H).

![support_angle_01](https://user-images.githubusercontent.com/16816760/37388252-0cb72bb8-2760-11e8-9070-ba25ec5c6a5e.JPG)

The front of this object has an angle of 2 °.
In my example, I print the object vertically to limit the amount of supports. 

![support_angle_02](https://user-images.githubusercontent.com/16816760/37388277-2468d2a2-2760-11e8-8d2a-20d864481c1c.JPG)

Problem # 1: this wall at 2 ° will be badly printed because the displacement of the head will not be precise enough to restore the wall which must be perfectly rectilinear.

Solution # 1: rotate the object at 45 °. The angle of this wall will be no longer 2 ° but 47 °, which changes everything. 
  
![support_angle_03](https://user-images.githubusercontent.com/16816760/37388294-329a3be0-2760-11e8-83d4-f108d7bc19c8.JPG)

Problem # 2: the supports remain positioned on the X and Y axes and they overflow the object and the printing will necessarily be a failure.

Solution # 2: give the possibility to change the angle of the supports.
In this case, if the object is turned at 45 °, it is necessary to rotate the supports by 45 °, which is not possible at present (or I missed something ....). 
Note #1 : The object contained in the STL has been modified to be printed vertically to limit the number of supports.
Note #2 : I use zigzag supports because they are (far) the best support in terms of finishing and easier to remove.
Note #3 : I am french...

**Comment by ChrisTerBeke** [comment]
I think by default we could even align the support infill and normal infill directions, with the option to override that.

**Comment by darkdvd** [comment]
Good idea.

**Comment by darkdvd** [comment]
The "liberty" to choose the direction is a good option too.

By default, the value "align Infill to Object" is not checked.
If checked, the value "0" can be modified to any other value...

**Comment by darkdvd** [comment]
So... ?

**Comment by ChrisTerBeke** [comment]
Cura's backlog is super cramped, it takes a while until things are picked up. In the mean time, any developer is free to make a pull request for this.

@Appesteijn is this something you think is useful?

**Comment by darkdvd** [comment]
Thank you @ChrisTerBeke !

Note : not only "useful" but "necessary"

**Comment by ChrisTerBeke** [comment]
Haha, that's always a matter of opinion 😄

**Comment by darkdvd** [comment]
(I'm not sure my last sentence was in English...)

**Comment by Appesteijn** [comment]
I think it is very useful, but it will also depend on how much work this is if (and when) we can pick this up. I hope some devs can mingle in this discussion :)

**Comment by darkdvd** [comment]
Thank you !

**Comment by Ghostkeeper** [comment]
The work on this is probably very little. We just have to fill this variable properly instead of hard-coding it to 0:
https://github.com/Ultimaker/CuraEngine/blob/2e8d4b0eca8702a9833349f4e7b306610f80e852/src/FffGcodeWriter.cpp#L2064

**Comment by Ghostkeeper** [comment]
Even still, our project manager just removed this feature from our planning. We won't be able to spend time on it soon.

**Comment by fieldOfView** [comment]
I'll see what I can do.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/CuraEngine/pull/819 and https://github.com/Ultimaker/Cura/pull/4212
