### ISSUE TITLE
Strange printing artifact between 2.7 and 3.2

### ISSUE THREAD

**Issue by biscuitlad** [Ultimaker/Cura#3486]
**Application Version**

3.2
**Platform**

Linux, Ubuntu Artful
**Qt**

**PyQt**

**Display Driver**

**Printer**

Vertex K8400

**Steps to Reproduce**

Print first in 2.7, then I'm 3.2
**Actual Results**

Strange lip on printed object of succeed by 3.2
**Expected results**

Objects should be identical.
**Additional Information**

**Comment by biscuitlad** [comment]
Can't leave photo via my mobile. So completely wasted my time doing this.

**Comment by ianpaschal** [comment]
You can update it later, right?

**Comment by biscuitlad** [comment]
Started another thread. This can be closed.
