### ISSUE TITLE
[3.1+] Mistranslation of "Hollow out objects" in French

### ISSUE THREAD

**Issue by MajorSlug** [Ultimaker/Cura#3489]
**Application Version**
Since 3.1 at least 

**Platform**
Windows

**Actual Results**
"Éviter les objets" means "avoid objects", not "hollow out objects"

**Expected results**
"Évider les objets"

**Comment by ChrisTerBeke** [comment]
@Ghostkeeper Something you might wanna pass on to the translators?

**Comment by 7Guillaume7** [comment]
Hello,


Cura
Version : 3.21
Windows

Actual Results :
"Touche" et "touché par" Ils définissent une action du corps humain.
They define an action of the human body.

Expected results :

Touche->Dirige
Touché par -> Est dirigé par

**Comment by Ghostkeeper** [comment]
Thanks guys. I've fixed these for the release of 3.3 [here](https://github.com/Ultimaker/Cura/commit/0f39b36bd6bf9aee10e6bbc830614a857b3a5100) and [here](https://github.com/Ultimaker/Cura/commit/1b173e8119ed384ada9942baf952beb97dc91569).

Keep 'em coming if you see more mistakes.
