### ISSUE TITLE
[Master] UM2+ material with no quality

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#3494]
**Application Version**
Master as of (8efc3b8b5d454d5b5bae8687da8740879d444c48)

**Platform**
MacOS 10.13

**Qt**
No idea hahaha

**PyQt**
PyQt_5.8.2

**Printer**
Ultimaker 2+

**Steps to Reproduce**
Click the drop down you will see a material that was not their in 3.x and that's PETG

**Expected results**
I don't think that should be there as there is no quality for it in `resources/quality/ultimaker2_plus/
`

**Comment by ianpaschal** [comment]
Yesterday we fixed some issues relating to materials and quality. Can you provide a more detailed explanation of how to reproduce?

**Comment by ChrisRiddell** [comment]
in the photo below you can see there is two materials in the dropdown that where not their in 3.2< and their is no quality files for them in the folder resources/quality/ultimaker2_plus/

<img width="1680" alt="screen shot 2018-03-15 at 8 37 16 pm" src="https://user-images.githubusercontent.com/2055566/37457208-36f8ea74-2891-11e8-8025-da76b4269f57.png">

**Comment by ianpaschal** [comment]
Ah those! Yes that's to be expected. You can feel free to make a quality file for them if you like but it was mentioned in stand up and our product owner said we should keep them as is for now.

**Comment by ChrisRiddell** [comment]
Okay after looking at some of the code and the FDM_Materials repo this now makes sense.
