### ISSUE TITLE
Add button to "slice" and stop automatic slicing from lagging out my PC

### ISSUE THREAD

**Issue by adamantiz** [Ultimaker/Cura#3499]
Hey, I have 16GB of ram, 6 Cores and a beefy graphics card.

Your program slices the model after each setting change. This results in unwanted lag.

I only want it to slice the models AFTER I finish changing settings. When I command it to by clicking "Slice".

You guys must have quantum computers or something?

**Comment by smartavionics** [comment]
Goto Preferences -> General and turn off "Slice automatically".

**Comment by ianpaschal** [comment]
^That.
