### ISSUE TITLE
Button change proposal

### ISSUE THREAD

**Issue by mennoberg** [Ultimaker/Cura#35]
Change proposal in color, icon size & drop shadow.

![button behaviour](https://cloud.githubusercontent.com/assets/6329918/8060852/cdd5c5a2-0ec7-11e5-84aa-dfcbc535cbbe.png)

**Comment by BagelOrb** [comment]
What do you mean by 'drop shadow in voxel'?

Does this mean the greyscale color of the button will be different than that of the build platform squares?

**Comment by mennoberg** [comment]
drop shadow is the shadow that exists under the button, displays itself on the grey background.
