### ISSUE TITLE
Changelog not easily closable

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#350]
Changelog has no button [ OK ] and/or [x] at the top right corner.

This is a frustrating UX issue.

**Comment by awhiemstra** [comment]
...which is caused by your platform. But we should add a dedicated close button as well, yes.

**Comment by BagelOrb** [comment]
PS: platform = ubuntu

**Comment by BagelOrb** [comment]
The close button is at an awkward position:
![cura_changelog_close_position](https://cloud.githubusercontent.com/assets/8895761/9757699/5e2190c0-56e2-11e5-94c1-5018339d5ffd.png)

**Comment by nallath** [comment]
Must be some form of system thing going on, as its correct on my screen.
