### ISSUE TITLE
Unneeded movement

### ISSUE THREAD

**Issue by Metroprinter** [Ultimaker/Cura#3508]
I have Cura 2.6.2 and I have trouble with my printer because it goes back and forth and side to side without printing anything. It extra movement isn't part of the print and it can mess with my prints making them not print by say "ejecting and leaving small pieces of plastic on my print (if it even prints fully) 
Thank you! :smile:

**Comment by Metroprinter** [comment]
tried using the newest version of Cura and still does the same thing. Is this normal?

**Comment by smartavionics** [comment]
Unless you post a screen shot or make the gcode available, nobody is going to be able to suggest how you may solve your issue. We're not mind readers...

**Comment by Metroprinter** [comment]
​
 MAH05970.MP4
<https://drive.google.com/file/d/19fMbyKplgBVUGF9kSoky6ijEC2NW5ku6/view?usp=drive_web>
​This is what happens I couldn't get G-code yet but I shall try through
E-mail like this video

**Comment by Metroprinter** [comment]
and this was what thing I was trying to print.

**Comment by Metroprinter** [comment]
![cura 3_17_2018 7_10_12 am](https://user-images.githubusercontent.com/37455557/37555100-9eb2e674-29b8-11e8-995d-fcab46373b4a.png)

**Comment by smartavionics** [comment]
Please post the gcode, I can't make out what's happening in the video. Thanks.

**Comment by Metroprinter** [comment]
what you want is the 3d design?
Here is the gcode of what I was trying to print

**Comment by Metroprinter** [comment]
but this happens on all usb prints not just that print.

**Comment by smartavionics** [comment]
Github ignores mail attachments. You have to attach them via the website.

**Comment by Metroprinter** [comment]
I tried but it doesn't support it. It won't load.

**Comment by smartavionics** [comment]
Either zip it or rename it to .txt

**Comment by Metroprinter** [comment]
[MSV_batrang.zip.zip](https://github.com/Ultimaker/Cura/files/1821859/MSV_batrang.zip.zip)

**Comment by smartavionics** [comment]
Thanks for the gcode, I don't really see lots of movement from side to side except for the little bits of extra skin it does at the end of each layer to fill the gaps between the walls which you can stop it doing by turning off the fill gaps between walls setting.

**Comment by Metroprinter** [comment]
Thanks. I don't see all the things I see when it's printing, maybe it's my printer.

**Comment by BagelOrb** [comment]
It's a hardware issue.

**Comment by Ghostkeeper** [comment]
I've seen this before...
Here: https://www.reddit.com/r/3Dprinting/comments/7h0i75/unnecessary_travel_moves_with_maker_select_v2_and/

Nobody seems to have found a real solution. It's got something to do with the USB connection to the printer. Apparently Simplify3D refuses to connect at all. The workaround that was found there was to only use SD cards.

**Comment by ChrisTerBeke** [comment]
That video reminded me of an issue I saw when developing drivers for 3D printers before. This happens when not enough lines can be sent to the printer over USB because the receiving end (aka the printer firmware) can't process them fast enough, and then it only executes partial commands (e.g. an X or Y coordinate with the other one getting a value of 0). That results in movements to the side of the print bed, then back, and then continuing the print. Maybe check if there is a firmware update available for the printer, or otherwise contact the manufacturer to ask for a fix. Especially cheaper printer kits are subjected to this as they use cheap hardware that sometimes can't run Marlin (or similar) properly.

**Comment by Metroprinter** [comment]
Thank you, but the SD card has errors so...

**Comment by ChrisTerBeke** [comment]
Well, that's why the Maker Select v2 costs only 300 Dollars...

Also started off with cheap printers, most of them worked okay but got shitty over time or had issues like these.

**Comment by Metroprinter** [comment]
Agreed, I wish I still had my Warranty. It's sad to say this is my second
printer (I returned the first one).

**Comment by Metroprinter** [comment]
Do you know of any good cheaper printers? One that won't have so many
problems.

**Comment by ianpaschal** [comment]
Sorry @Metroprinter, I think at Ultimaker we would all agree you should buy an Ultimaker! 😉
