### ISSUE TITLE
Bug: layer view: skin same color as infill

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#351]
Now skin and infill are yellow.

Infill should be magenta, and skin should be yellow.

**Comment by nallath** [comment]
I find magenta to f*cking ugly. 
![uglymagenta](https://cloud.githubusercontent.com/assets/3922611/9934079/63fe4506-5d4f-11e5-804d-a75b84bac272.png)

**Comment by nallath** [comment]
I've changed it to amber.
