### ISSUE TITLE
Cura 3.2.1 Text on Menus is messed up

### ISSUE THREAD

**Issue by fredhag** [Ultimaker/Cura#3515]
**Application Version**

Version 3.2.1

**Platform**

MacOS High Sierra

**Qt**

**PyQt**

**Display Driver**

Inherent iMac display driver

**Printer**

UM3

**Steps to Reproduce**

Open Cura and click custom print setup

**Actual Results**

The text of the print settings appears garbled.

**Expected results**

Should be able to read the text (most of it is readable, but some of the custom options cannot.

**Additional Information**

![image](https://user-images.githubusercontent.com/17429951/37556835-f024b348-29d1-11e8-8525-19cefe548d43.png)

**Comment by fieldOfView** [comment]
Duplicate of #3277

**Comment by fredhag** [comment]
Ugh, I didn't search "font".
