### ISSUE TITLE
[3.2.1] Crash when attempting to change material diameter in machine settings

### ISSUE THREAD

**Issue by ewortzman** [Ultimaker/Cura#3517]
**Application Version**
3.2.1

**Platform**
Windows 10

**Printer**
An custom machine was selected

**Steps to Reproduce**
Attempt to change the material diameter in machine settings

**Actual Results**
Cura immediately crashes

**Expected results**
The material diameter setting should be saved and Cura should not crash

**Comment by ChrisTerBeke** [comment]
Please post the logs here, without them we can't even begin to guess what happened.

**Comment by smokey1300** [comment]
Same problem.

**Comment by ianpaschal** [comment]
In the words (pictures?) of @fieldOfView:

![guillaume-jaillet-401050-unsplash](https://user-images.githubusercontent.com/1137232/38663561-6325a9fa-3e37-11e8-8e2b-60891e6139f2.jpg)
![romain-rullaud-491560-unsplash](https://user-images.githubusercontent.com/1137232/38663567-658ddf3c-3e37-11e8-880c-ea74015d1e5d.jpg)
![sven-scheuermeier-61236-unsplash](https://user-images.githubusercontent.com/1137232/38663570-676fcd74-3e37-11e8-8e2f-99d091b2bcaf.jpg)
![dorelys-smits-200737-unsplash](https://user-images.githubusercontent.com/1137232/38663574-6942d790-3e37-11e8-91b8-0ce5a197de48.jpg)

**Comment by ChrisTerBeke** [comment]
No new information appeared. Closing.
