### ISSUE TITLE
[3.2.1] changing material diameter when creating a custom material causes material to disappear

### ISSUE THREAD

**Issue by ewortzman** [Ultimaker/Cura#3518]
**Application Version**
3.2.1 

**Platform**
Windows 10

**Printer**
An machine selection

**Steps to Reproduce**
1. Create a new custom material, or duplicate an existing material
2. Attempt to change the material diameter

**Actual Results**
The material immediately disappears from Cura and cannot be retrieved

**Expected results**
The new diameter setting should be saved and the material should not disappear

**Additional Information**
According to Issue #3283, This bug was fixed in version 3.2.1.  However, I still experience it.  I have confirmed that I am, in fact, running version 3.2.1

**Comment by t-paul** [comment]
Confirmed on Debian/Testing with the AppImage 3.2.1.

Activating the material sometimes seems to accept and store some of the values so the material appears in the list. But even then it does randomly lose settings, e.g. changing temperature, tab to next setting, close dialog will just discard the setting and revert to the previous temperature.

**Comment by ChrisTerBeke** [comment]
We only show materials that fit the current machine selection. If you have a 2.85mm extruder selected and change the material to be 1.75 (or visa versa) it'll indeed be removed from the materials list. Try changing the extruder filament diameter to match the material diameter, then it should appear again.

I'm not saying this is the best UI/UX, but this is how it currently works and that's expected. @LukeChen-Ultimaker any ideas to improve this in the future?

**Comment by ewortzman** [comment]
I can understand materials that are not compatible not showing up in the main view.  But when in settings and creating a new material or modifying an existing one, all materials should be present.

**Comment by RacerBo** [comment]
Same issue here. 
Per my issue report  #3503, i notice it only happens after the dia.(1.75mm) is inputted.
Otherwise, all the other new material settings will stick. 
Also, my my custom umo+ (nozzle 1.75mm) printer was selected when the new materials are being created.

**Comment by LukeChen-Ultimaker** [comment]
A way we can handle this:
1. Once user input a different diameter then show a gentle warnings to remind the users that the diameter does not match with extruder.
2. The text will state something like "Material diameter does not match extruder diameter, please change extruder extruder at machine settings".
3. The duplicated material profile should remain and keep the original diameter value.

**Comment by Ghostkeeper** [comment]
We already have a warning like that:
![screenshot from 2018-04-20 11-25-01](https://user-images.githubusercontent.com/2448634/39043375-8abc26f4-448d-11e8-975a-05f6a5ee6801.png)

**Comment by Ghostkeeper** [comment]
We've chosen not to display materials with different diameters on purpose, because then half of the materials are not applicable to your current extruder. Most people have only one type of printer so for most people it would be unnecessary.
