### ISSUE TITLE
Autorescale not rescaling

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#352]
The object is larger than the print volume, but the scaling is 100% and the reported scaling is 0%!

![cura_auto_rescale_bug](https://cloud.githubusercontent.com/assets/8895761/9733703/ca8e7828-562d-11e5-9196-91c240fbb81b.png)

**Comment by nallath** [comment]
It works for my test model. Could you send me yours?

**Comment by awhiemstra** [comment]
It looks like a 20x20x20 or similar cube. This probably confuses the scaling code as there is no clear "maximum" axis.

**Comment by BagelOrb** [comment]
It is.

Here! :P 

solid OpenSCAD_Model
  facet normal -0 0 1
    outer loop
      vertex 0 100000 100000
      vertex 100000 0 100000
      vertex 100000 100000 100000
    endloop
  endfacet
  facet normal 0 0 1
    outer loop
      vertex 100000 0 100000
      vertex 0 100000 100000
      vertex 0 0 100000
    endloop
  endfacet
  facet normal 0 0 -1
    outer loop
      vertex 0 0 0
      vertex 100000 100000 0
      vertex 100000 0 0
    endloop
  endfacet
  facet normal -0 0 -1
    outer loop
      vertex 100000 100000 0
      vertex 0 0 0
      vertex 0 100000 0
    endloop
  endfacet
  facet normal 0 -1 0
    outer loop
      vertex 0 0 0
      vertex 100000 0 100000
      vertex 0 0 100000
    endloop
  endfacet
  facet normal 0 -1 -0
    outer loop
      vertex 100000 0 100000
      vertex 0 0 0
      vertex 100000 0 0
    endloop
  endfacet
  facet normal 1 -0 0
    outer loop
      vertex 100000 0 100000
      vertex 100000 100000 0
      vertex 100000 100000 100000
    endloop
  endfacet
  facet normal 1 0 0
    outer loop
      vertex 100000 100000 0
      vertex 100000 0 100000
      vertex 100000 0 0
    endloop
  endfacet
  facet normal 0 1 -0
    outer loop
      vertex 100000 100000 0
      vertex 0 100000 100000
      vertex 100000 100000 100000
    endloop
  endfacet
  facet normal 0 1 0
    outer loop
      vertex 0 100000 100000
      vertex 100000 100000 0
      vertex 0 100000 0
    endloop
  endfacet
  facet normal -1 0 0
    outer loop
      vertex 0 0 0
      vertex 0 100000 100000
      vertex 0 100000 0
    endloop
  endfacet
  facet normal -1 -0 0
    outer loop
      vertex 0 100000 100000
      vertex 0 0 0
      vertex 0 0 100000
    endloop
  endfacet
endsolid OpenSCAD_Model

**Comment by nallath** [comment]
The reported scaling is rounded (the scale does happen correctly!). It does not take the disallowed areas into account.

**Comment by BagelOrb** [comment]
The reported scaling is the actual scaling, you are right.

However, the scaling did not happen correctly.

Actual: model is higher than build volume.
Expected: model just fits within build volume.

**Comment by nallath** [comment]
Weirdly enough, it works for me. Do you get this issue consistantly? Or with all objects?

**Comment by BagelOrb** [comment]
I get it consistently with that model. Can you provide me with other huge models? Then I could check.

**Comment by nallath** [comment]
I just made a huge box with Blender, which worked. I'm sending you an email with the files.

**Comment by BagelOrb** [comment]
![cura_auto_rescale_bug_2](https://cloud.githubusercontent.com/assets/8895761/9757405/bdcd713a-56e0-11e5-855c-3049081a05eb.png)
![cura_auto_rescale_bug_3](https://cloud.githubusercontent.com/assets/8895761/9757441/e51b0d42-56e0-11e5-911c-44614224138a.png)

It seems they are scaled to fit in the X and Y dimension, but that leaves Z too high.

**Comment by nallath** [comment]
Ah, nice catch. You're right. I'll look into it.
