### ISSUE TITLE
missing Holes 

### ISSUE THREAD

**Issue by HgSiegenthaler** [Ultimaker/Cura#3521]
Hi there
Cura can see the two holes but I cant print the unit with the 2 holes.
The unit is constructed with Rhino5.
Regards
Hg

![holes2](https://user-images.githubusercontent.com/37517045/37570805-b7d592fe-2af4-11e8-8c67-aafbe19ef4fd.jpg)
![holes1](https://user-images.githubusercontent.com/37517045/37570806-b7ee50f0-2af4-11e8-92e7-26a640aaa404.jpg)
![holes3](https://user-images.githubusercontent.com/37517045/37570807-b8075e92-2af4-11e8-875f-13cdda165aed.jpg)

**Comment by ChrisTerBeke** [comment]
Can you show the mesh fixed category settings?

**Comment by HgSiegenthaler** [comment]
This one?

Attached also the Cura project file.

 

Regards

Hg

 

 

Von: ChrisTerBeke <notifications@github.com> 
Gesendet: Sonntag, 18. März 2018 23:07
An: Ultimaker/Cura <Cura@noreply.github.com>
Cc: HgSiegenthaler <hgs@uitikon.ch>; Author <author@noreply.github.com>
Betreff: Re: [Ultimaker/Cura] missing Holes (#3521)

 

Can you show the mesh fixed category settings?

**Comment by ChrisTerBeke** [comment]
GitHub doesn't support sending attachments via email, please login to GitHub and upload the project file from there.

**Comment by HgSiegenthaler** [comment]
![screenshot 2018-03-19 10 47 09](https://user-images.githubusercontent.com/37517045/37591371-9b7498fe-2b6b-11e8-981a-e3c776976b09.png)

How can I upload a Project?

**Comment by ChrisTerBeke** [comment]
rename to .zip and then drag and drop in here.

**Comment by HgSiegenthaler** [comment]
[Hole Test.curaproject.zip](https://github.com/Ultimaker/Cura/files/1824769/Hole.Test.curaproject.zip)

**Comment by diegopradogesto** [comment]
Something looks wrong in the 3D model. Probably some normals are inverted. Very typical with Rhino. 
You can see a red area in the solid view:
![image](https://user-images.githubusercontent.com/15830521/37610830-f9523ad2-2ba0-11e8-99c4-23f799d24da3.png)
Also using Meshmixer for instance you can see some errors in the model:
![image](https://user-images.githubusercontent.com/15830521/37610914-33627f34-2ba1-11e8-859f-fbaee8269931.png)

You need to fix it first.
