### ISSUE TITLE
[3.2.1] Estimated time remaining counting up

### ISSUE THREAD

**Issue by nrgbistro** [Ultimaker/Cura#3522]
**Application Version**
Cura 3.2.1

**Platform**
A Tarantula running Marlin software

**Qt**
---

**PyQt**
---

**Display Driver**

**Printer**
TEVO Tarantula

**Steps to Reproduce**
1. Send print to printer over USB

**Actual Results**
In the monitor screen, time remaining starts at 'Printing Time' and counts up

**Expected results**
In the monitor screen, time remaining should start at 'Printing Time' and count down to 00:00:00

**Additional Information**
![image](https://user-images.githubusercontent.com/35301702/37571348-f9e3d174-2ad1-11e8-986c-b18469bef0cd.png)

Print has been going for about 20 minutes; time remaining is higher than total print time. When print finishes, time remaining will be at about 8 hours, which does not make much sense...

**Comment by nrgbistro** [comment]
After pausing and un-pausing for an unrelated reason, the timer seemed to fix itself. However I don't think this would have happened if I did not pause the print.

**Comment by alekseisasin** [comment]
Hi @nrgbistro , I tested and I saw strange estimate time left counting, I created ticket for this bug.
Devs: CURA-5145

**Comment by alekseisasin** [comment]
Hi @nrgbistro , the issue was fixed long time ago. You also can check it in version 3.4. Thank you.
