### ISSUE TITLE
Add printer starts where it was exited

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#353]
Steps:
Add printer
- UMO+
- [ next ]
- [ cancel ]
- Machine > Add new printer...

Expected:
get wizard on the page with all printers listed

Actual:
get wizard on the page on UMO+ at the second step

--------------------------------------------------------------

After the above steps, do:
- [ previous ]
- UMO+
- [ cancel ]
- Machine > Add new printer...
- repeat

Expected: nothing special
Actual:
every time you do the above, the wizard steps get appended to the list once more:
![cura_add_printer_wizard](https://cloud.githubusercontent.com/assets/8895761/9736644/bc81119a-5642-11e5-9aed-3a50e657cf4d.png)

**Comment by nallath** [comment]
Confirmed
