### ISSUE TITLE
master branch - layer view slider for selecting line stuck on 100%

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3537]
**Application Version**

master branch

**Platform**

Linux

**Qt**

5.8.0

**PyQt**

5.8.2

**Display Driver**

2018-03-22 11:27:02,763 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [92]: Initialized OpenGL subsystems.
2018-03-22 11:27:02,763 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [93]: OpenGL Version:  4.5 (Core Profile) Mesa 17.2.4
2018-03-22 11:27:02,763 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [94]: OpenGL Vendor:   Intel Open Source Technology Center
2018-03-22 11:27:02,764 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [95]: OpenGL Renderer: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 

**Printer**

Kossel Mini

**Steps to Reproduce**

Load model, slice, select layer view, try to move line selection slider

**Actual Results**

Slider bug tries to move but then jumps back to 100% immediately.

**Expected results**

Slider bug moves like it used to and you can select the line currently being drawn.

**Additional Information**

Not sure when this change occurred but it must be pretty recent as I use the slider a lot.

**Comment by smartavionics** [comment]
Found it, https://github.com/Ultimaker/Cura/commit/da00bdf9c325e9e124ea1c20f351470bf01e3b4e is the culprit.

**Comment by BagelOrb** [comment]
@ghostkeeper should be an easy fix then.

**Comment by smartavionics** [comment]
You would have thought so, whaddyathink @LipuFei  ?

**Comment by LipuFei** [comment]
Perhaps we need to connect to both signals.

**Comment by smartavionics** [comment]
Perhaps. I have no opinion on that, it's all black magic in the front end!

**Comment by smartavionics** [comment]
Thanks @ianpaschal, closing...

**Comment by smartavionics** [comment]
Err, I think that was @alekseisasin who comitted the fix, thanks!

**Comment by alekseisasin** [comment]
I am not sure about connecting both signals, the onSceneChange is triggered constantly ( after each mouse move), This _self._controller.getScene().sceneChanged.connect(self._onSceneChanged)_ , is correct it was before.
If you apply this:
_self._controller.getScene().getRoot().childrenChanged.connect(self._onSceneChanged)_
Then simulation is broken, try to click play button.
