### ISSUE TITLE
Cura 3.2.1 Auto Scale Large Object not working

### ISSUE THREAD

**Issue by Franks3dShop** [Ultimaker/Cura#3538]
**Application Version**
3.2.1

**Platform**
OS X 10.13.3

**Qt**

**PyQt**

**Display Driver**
NVIDIA GeForce GT 750M 2 GB, gMux Version:	4.0.8 [3.2.8]

**Printer**
Monoprice mini custom setup, same problem using CR-10S builtin preset.

**Steps to Reproduce**
Activate option "Scale Large Models" option in General/Open and Saving Files.
Load a model bigger than the build plate.

**Actual Results**
It show at the bottom, Auto Scale Object to 46% of original size". But it is not actually scaled down, it just says so. 

**Expected results**
It should apply the resize factor, not just show a text as if it did.

**Additional Information**
![screen shot 2018-03-22 at 3 31 03 pm](https://user-images.githubusercontent.com/33358566/37793807-10154876-2de6-11e8-85bf-bda746e31719.jpg)

[Christmas-Imp-Female.stl.zip](https://github.com/Ultimaker/Cura/files/1838987/Christmas-Imp-Female.stl.zip)

Thank you.

**Comment by alekseisasin** [comment]
Hi @Franks3dShop , yes you a right this functionality was broken in Cura 3.2.1 and it is already fixed. In next Cura version the "Scale large models" functionality will work correct. 
Thank you for letting us know of any wrong Cura behavior.
