### ISSUE TITLE
Merge keeps objects on platform

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#354]
Merge keeps each object on platform instead of combination of all.

Actual:
![cura_merge](https://cloud.githubusercontent.com/assets/8895761/9739514/57fcacda-5650-11e5-9a4f-bd6211e53a56.png)

Expected:
![cura_merge_2](https://cloud.githubusercontent.com/assets/8895761/9739519/5d87e8e0-5650-11e5-8efe-b57020a341fd.png)

**Comment by nallath** [comment]
Do you have a download link of that object?

**Comment by BagelOrb** [comment]
https://www.youmagine.com/designs/guy

**Comment by BagelOrb** [comment]
The combined object should still fall on the platform.
![cura_merge_fall_on_platform](https://cloud.githubusercontent.com/assets/8895761/9758261/cc14e1d8-56e5-11e5-8bae-d47990070c3b.png)

**Comment by nallath** [comment]
According to the bounding box it is ;) It seems like the bounding box is calculated wrong. I'm not able to reproduce this. Could you send me the file where this happens?

**Comment by BagelOrb** [comment]
Its just two cubes translated up in openscad...

**Comment by BagelOrb** [comment]
* translate([0,0,10]) cube([10,10,10]);
translate([0,0,20]) cube([10,10,10]);
