### ISSUE TITLE
[3.2.1] Extruder doesn't move away from part at end of print

### ISSUE THREAD

**Issue by KolfMAKER** [Ultimaker/Cura#3544]
Since having installed Cura 3.2.1 on my Mac, I have an error in the final stage of printing. This is what happens:
- At the very end of printing, the extruder stays in the final position and does not move away from the just finalised object.
- While staying in position the nozzle extrudes some filament material, but as the nozzle is still on top of the printed object, it causes a 'blob' of material.
- The result is spilled material on the printed object. I either have to throw away the print or manually work the print to remove the 'blob' of spilled material. Which is not easy and also causes damage to the printed object.

I reloaded firmware _2.6.2 to the printer, but that didn't make any difference.

How can I solve this problem? I experience great difficulty in my work (professional photo typing), so I am looking for a quick resolve of this issue.

Thanks in advance for helping me.
![foto 23-03-18 14 47 04](https://user-images.githubusercontent.com/37700707/37832532-29454b66-2ea9-11e8-8cce-390126caa38f.jpg)

**Application Version**
Cura 3.2.1. for Mac

**Platform**
iMac, MacOS High Sierra, v10.13.3

**Qt**
From Ultimaker's website

**PyQt**
From Ultimaker's website

**Display Driver**
Not applicable

**Printer**
Ultimaker 2 (FW _2.6.2) + Olsen block (correctly calibrated)
[UM2_PIRtop v1.0f1.3mf.zip](https://github.com/Ultimaker/Cura/files/1841657/UM2_PIRtop.v1.0f1.3mf.zip)

**Steps to Reproduce**
See description above

**Actual Results**
See description above

**Expected results**
See description above

**Additional Information**
Extra information relevant to the issue, like screenshots (replace this text)

**Comment by smartavionics** [comment]
Hasn't this been seen recently and (if I remember right) it was something to do with the gcode at the end of the print not being executed for some reason and the workaround was to pad the end of the gcode file?

**Comment by KolfMAKER** [comment]
I think you are right this is the explanation why it happens.
I do not know what code I should change in the Code file. Do you?
Though I do prefer to have a bug fix in Cura, as manually editing each Code file is not productive.

**Comment by fieldOfView** [comment]
Just add a number lines of of dummy text (prepended by a ; ) to the end of your gcode.

**Comment by smartavionics** [comment]
Yes, it has been fixed for the next release, see https://github.com/Ultimaker/Cura/commit/7b794249f68326e8db1b05913b7a16f6971a00a9

**Comment by Ghostkeeper** [comment]
The actual fix is here: https://github.com/Ultimaker/UM2.1-Firmware/commit/0253832c8a70560c6acd763ffa32249c64dad341
