### ISSUE TITLE
How to setup Marlin firmware with RUMBA broad and Diamond 3 in and 1 out extruder?

### ISSUE THREAD

**Issue by mubarak111nsu** [Ultimaker/Cura#3548]
Dear respected friends, I am new in 3D printing. 
For last few months, I am working on 3D printing. In my 3D printer, I am using RUMBA bord and Diamond 3 in and 1 out extruder. 
I am also using Marlin firmware and Ultimaker Cura. 
MY Printer dimension is X-axis 1000mm, Y-axis 700mm and Z-axis 600mm 
But I am facing some problem to setup Marlin firmware. Please sir, I am begging for help.

Please sir, Help me. I will be grateful to you
![3d printer](https://user-images.githubusercontent.com/21698962/37861007-2c3d11ce-2eee-11e8-8faf-3bfd18a1f5b4.png)

**Comment by jackha** [comment]
Hi @mubarak111nsu 
I'm sorry to hear you have problems with your marlin firmware, but here we're only doing Cura related issues. Please refer to the manufacturer (or designer) of your printer on how to set up your Marlin. Good luck!

**Comment by Ghostkeeper** [comment]
Try this place: https://github.com/MarlinFirmware/Marlin
