### ISSUE TITLE
printer setting bug

### ISSUE THREAD

**Issue by xia01eng** [Ultimaker/Cura#3549]
![image](https://user-images.githubusercontent.com/31816340/37864539-95c0a238-2fab-11e8-8eb7-93465816d5eb.png)
As shown in this picture, every time you close the cura application the nozzle size configuration just cannot be stored. Thus every time I restart cura, I have to change that setting. It's really ... . Hope to fix that bug.

**Comment by fieldOfView** [comment]
A screenshot shows us nothing in this case. Please locate and share your logs (cura.log in the configuration folder)

**Comment by xia01eng** [comment]
Sorry, where to find configuration folder. OSX

**Comment by xia01eng** [comment]
@fieldOfView

**Comment by xia01eng** [comment]
Unfortunately, it did not display any information about this issue in the log. But just like I described before, this problem did exist.

**Comment by Thisismydigitalself** [comment]
> this problem did exist. 

> 
Still exists in 3.2.1.
You mean fixed in 3.3? any ETA for 3.3?

**Comment by ianpaschal** [comment]
Duplicate of #3511.

This is fixed and will be in the 3.3 beta released this week.
