### ISSUE TITLE
Feature: gcode settings should allow for setting token replacement

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#355]
Starting gcode in the old Cura contained gcode which looked like:

```
M109 S{print_temperature}
G1 Z15.0 F{travel_speed} ;move the platform down 15mm
```

The new Cura should also allow for setting values to be used within custom gcode settings (start gcode, end gcode, extruder start gcode, etc.).
Example: `M109 S{material_print_temperature}` should result in `M109 S210`

See https://github.com/Ultimaker/CuraEngine/issues/240

**Comment by fieldOfView** [comment]
Issue can be closed

**Comment by nickthetait** [comment]
yeah this was fixed ages ago :laughing:
