### ISSUE TITLE
[3.2.1] Adpative layer + prime tower

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3551]
Win10 x64

When I set "enable prime tower" plus "adpative layer", no layers are showing.

![image](https://user-images.githubusercontent.com/15361590/37864834-7d896f00-2f52-11e8-89a1-e0664b985fbb.png)

**Comment by alekseisasin** [comment]
Hi @mtmello2003 , I did same steps and Cura it works fine. I see you are using Compatibility mode, maybe this is the case. Then the problem is related to your hardware.
I can test again if you will upload your project here.

**Comment by mtmello2003** [comment]
Hi,

The stl file is from https://www.thingiverse.com/make:467481

Thank you!

**Comment by alekseisasin** [comment]
@mtmello2003 , can you save model as project, then I will ensure that I do not miss any setting. To do this please go the menu bar and in "File" section choose "Save Project...".  This project you can archive and upload here.

**Comment by diegopradogesto** [comment]
I don't get the crash, so maybe it's already fixed. Which version of Cura are you using? Next time, please also fill the form that is included when you create the issue, it contains very useful information for us to trace the error.
As @alekseisasin says, you project is very helpful also in this case.

**Comment by mtmello2003** [comment]
This issue is completely vanish with cura 3.3 B.

Please close the call

Thank you

![image](https://user-images.githubusercontent.com/15361590/37998805-84afbdf6-31f6-11e8-992a-b8b59b93a1fc.png)

**Comment by diegopradogesto** [comment]
Thanks for checking.
