### ISSUE TITLE
Choix du matériaux

### ISSUE THREAD

**Issue by Mmanga78** [Ultimaker/Cura#3554]
**Application Version**
 3.2.1

**Platform**

Windows
**Qt**

**PyQt**

**Display Driver**

**Printer**

Annycubic-i3 Méga
**Steps to Reproduce**

**Actual Results**

Je ne peux choisir pas mon matériaux et du-coup mon prix ne s'affiche pas en dessous du temps d'impression.
**Expected results**

Je suis sensé choisir mon matériaux parmi ceux proposer et donc  aussi changer mes paramètre en fonction du matériaux, le prix de l'impression est aussi sensé s'afficher en dessous du temps d'impression.
![capture d ecran 19](https://user-images.githubusercontent.com/37746161/37866424-e7937458-2f8a-11e8-81a7-dd760685872f.png)

**Additional Information**

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3266. See the explanation there.
Please note that the language here is english. The Ultimaker forums have a french section.

**Comment by ianpaschal** [comment]
Thanks @fieldOfView 

@Mmanga78: Nous faisons de notre mieux pour prendre en charge le matériel de tierce partie, mais en fin de compte vous êtes à la merci de la tierce partie pour faire des profils appropriés.
