### ISSUE TITLE
[3.2.1] CuraEngine crashes when slicing with a raft and Number of slower layers = 0

### ISSUE THREAD

**Issue by MajorSlug** [Ultimaker/Cura#3555]
**Application Version**
3.2.1

**Platform**
Windows 7

**Printer**
Custom FDM printer

**Steps to Reproduce**
- load a STL file
- choose any profile (eg. low quality - 0.15mm)
- set Number of slower layers to 0
- choose "raft" Build Plate Adhesion Type
- prepare

**Actual Results**
CuraEngine crash message pops up and no slicing is done.

**Expected results**
Having the mesh sliced laying on a raft.

**Additional Information**
![image](https://user-images.githubusercontent.com/37349730/37869889-0b7f971c-2fc1-11e8-9d74-45802ff4bd68.png)
![image](https://user-images.githubusercontent.com/37349730/37869645-bbeb709a-2fbb-11e8-9f44-e08b857652f1.png)

**Comment by smartavionics** [comment]
Either the bug has been fixed or it's more subtle than just those two settings because I can slice using that combo with the current dev version of Cura without it crashing...

![screenshot_2018-03-24_22-55-14](https://user-images.githubusercontent.com/585618/37869810-95161c9a-2fb6-11e8-95b3-1967fa47b017.png)

**Comment by smartavionics** [comment]
Interesting that the displayed min feed rate is complete bollocks.

![screenshot_2018-03-24_22-58-18](https://user-images.githubusercontent.com/585618/37869821-ddecc518-2fb6-11e8-9ba0-56025eb3cce1.png)

**Comment by MajorSlug** [comment]
My machine is a "Custom FDM printer". I updated the issue.

**Comment by smartavionics** [comment]
I do, however, see a couple of these messages which could be relevant:

2018-03-25 07:43:45,940 - WARNING - [MainThread] cura.PrintInformation._updateTotalPrintTimePerFeature [190]: Received NaN for print duration message

**Comment by smartavionics** [comment]
Possibly fixed by https://github.com/Ultimaker/CuraEngine/pull/730.

**Comment by MajorSlug** [comment]
I'm pretty sure it is not fixed by Ultimaker/CuraEngine#730.
The change being:
![image](https://user-images.githubusercontent.com/37349730/37876107-4ab3e3a2-3048-11e8-8539-431bbc4ab1f1.png)
I don't see how layer_nr could be < 0.
Anyway, didn't you mean
`if (layer_nr >= 0 && layer_nr < initial_speedup_layer_count)`

**Comment by smartavionics** [comment]
I think you will find that layer_nr will be negative while the raft is being printed. So I am stopping that function being called for the raft layers.

**Comment by diegopradogesto** [comment]
I don't see my CuraEngine crashing with those settings.
However what I see is that all the feedrates (wall, infill, first layers, travel moves, ...) are the same. That's the reason why the model is all orange and why the min_feedrate is the float's minimum value. I'm more worried about that.
I will investigate a bit more.

**Comment by smartavionics** [comment]
Hi @diegopradogesto , please check my engine PR that I believe fixes this issue.

**Comment by diegopradogesto** [comment]
Yes, I will do that.

**Comment by diegopradogesto** [comment]
The only concern with the PR is that the two first layers of the Raft will print slowly, not taking into account the "Number of slower layers"

**Comment by diegopradogesto** [comment]
Yes, I will do it. I was just thinking aloud :-)

**Comment by diegopradogesto** [comment]
This bug is fixed in the next release. Thanks @MajorSlug for the report and @smartavionics for the quick fix.
