### ISSUE TITLE
Good afternoon. I'm just starting to explore the 3d world and want to ask a couple of questions about the Cura Engine. Is it possible to get the model data (the file) when you load the model (for example, the weight of the model, the manufacturing model).

### ISSUE THREAD

**Issue by Creativ671** [Ultimaker/Cura#3556]
Platform
Windows 10
Good afternoon. I'm just starting to explore the 3d world and want to ask a couple of questions about the Cura Engine. Is it possible to get the model data (the file) when you load the model (for example, the weight of the model, the manufacturing model).

**Comment by ianpaschal** [comment]
I don't totally understand what you are asking.

After you slice a model with Cura, and CuraEngine returns the gcode (machine paths), it also shows how much filament will be used by length, and by weight (or more specifically, by mass).

**Comment by Creativ671** [comment]
I want to make an stl file calculator for the website using the Cura slicer. But I don't know how to do it.  (Sorry for my English)

**Comment by ianpaschal** [comment]
Ah okay.

It's possible, but I'm not sure I can really explain how to arrange all your code and what to build via a GitHub comment.

I suggest looking [here](https://github.com/Ultimaker/Cura/tree/master/plugins/CuraEngineBackend). This is the Cura backend which is responsible for sending the meshes to CuraEngine and then listening for the machine code (gcode) response.

Hopefully that gets you started!

**Comment by Ghostkeeper** [comment]
The print time and material usage is normally put in the g-code header.
