### ISSUE TITLE
Unable to import settings profile from gcode file

### ISSUE THREAD

**Issue by lokster** [Ultimaker/Cura#3560]
**Application Version**
3.2.1

**Platform**
ANY

**Printer**
Custom FDM Printer

**Steps to Reproduce**
Slice something with Cura, and save the gcode file. Go to Settings -> Profiles and try to import the settings from the gcode file

**Actual Results**
It shows an error message: "The machine defined in profile XXXX.gcode doesn't match with your current machine, could not import it."

**Expected results**
To successfully import the settings.

**Additional Information**
HOW TO FIX MANUALLY: open the gcode file with a text editor, and scroll down to the end. Replace "definition = custom" with "definition = fdmprinter". Try importing again. The import works as expected.

**Comment by ianpaschal** [comment]
This is fixed in version 3.3. The Beta will be released this week.
