### ISSUE TITLE
master branch - some settings changes are reset to original value

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3564]
**Application Version**

master branch

**Platform**

Linux

**Qt**

5.8.0

**PyQt**

5.8.2

**Display Driver**

**Printer**

Kossel Mini

**Steps to Reproduce**

Change a setting such as Printing Temperature and slice model.

**Actual Results**

After slice has finished, the setting jumps back to the original value and the new value was not used
for the slice.

**Expected results**

The new setting value should not revert back and the slice should use the new setting value.

**Additional Information**

**Comment by smartavionics** [comment]
Could it possibly be caused by https://github.com/Ultimaker/Uranium/commit/d9c4e7423036affb8ce5ebfeeb0d2671d05cb02a ?

**Comment by smartavionics** [comment]
Could it possibly be related to https://github.com/Ultimaker/Uranium/commit/d9c4e7423036affb8ce5ebfeeb0d2671d05cb02a ?

**Comment by smartavionics** [comment]
I am getting nowhere with this, mainly due to my ignorance of how the whole UI functions. Why should the rate at which digits are entered into a setting field influence the behaviour? Anyone got any ideas?

**Comment by smartavionics** [comment]
This appears to have been fixed today, closing...

**Comment by Ghostkeeper** [comment]
Yeah this was a duplicate of https://github.com/Ultimaker/Cura/issues/3590 .
