### ISSUE TITLE
[3.2.0] Add option to import and export machine settings (printer, extruders)

### ISSUE THREAD

**Issue by aguadopd** [Ultimaker/Cura#3568]
**Application Version**
3.2.0

**Platform**
Linux AppImage

**Qt**
Not relevant.

**PyQt**
Not relevant.

**Display Driver**
Not relevant.

**Printer**
Not relevant.

**Steps to Reproduce**
User wants to easily reproduce printer and extruder settings on a different computer.

**Actual Results**
User cannot find options for importing or exporting machine settings. He only can import and export profiles. User finds that he can do it by copying some files available [in his user folder](https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations). But this is not easy to find and could be easier to do.

**Expected results**
User can find options to import and export machine settings.

**Additional Information**
Slightly related issues: #1510, #2934, #3177.

**Edits**
There is a workaround reported by user @fieldOfView in this issue and also seen [here](https://community.ultimaker.com/topic/21069-printer-exportimport/). 
```You can save a project, and open that project on another computer. That also copies over the printer and extruder settings.```

**Comment by fieldOfView** [comment]
You can save a project, and open that project on another computer. That also copies over the printer and extruder settings.
