### ISSUE TITLE
Cura Connect - Print marked finished while printing.

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#3572]
Hi i don't know if this is the right repo but while i haven't succeed in finding a better one i'll dump my findings here:
**Application Version**
4.3.2.20180308

**Platform**
Ultimaker 3

**Printer**
Same as Platform

**Steps to Reproduce**
Start a print from Cura and open the web view of the printer the file was send to.

**Actual Results**
Print is marked as finished, 
![screen shot 2018-03-27 at 14 42 06](https://user-images.githubusercontent.com/759145/37967974-3811dcb4-31cd-11e8-8fe0-4a5b3041cb20.png)

![screen shot 2018-03-27 at 14 45 14](https://user-images.githubusercontent.com/759145/37968083-80b68136-31cd-11e8-9610-65f5ab41eb7f.png)

**Expected results**
I would expect that the message indicates the actual state the printer is in.

**Additional Information**
Slicer: Cura 3.2.1 using adaptive layer height.

**Comment by ianpaschal** [comment]
You're in the right place. We tend to try and funnel all issues here since GitHub doesn't have an easy mechanism for moving issues to a different repository. And congratulations, you're one of the 0.1% of people who actually put effort into that. Thank you, haha.

Also, paging @nallath

**Comment by Ghostkeeper** [comment]
Doesn't reproduce for me, even when I disconnect from the network while printing or something.

**Comment by Spirou42** [comment]
Ok, so how can I help to get the needed information?

**Comment by ianpaschal** [comment]
Can you share the Cura project (just add .zip to the end of the file name since it's technically a zip file already)?

Then we can try to recreate the scenario _exactly_.

If we're still not able to reproduce it then I'm afraid we can't really try to fix it, but maybe we will see that there's something specific in your setting combination or model that is triggering it.

**Comment by Spirou42** [comment]
I can reproduce it  every time. The discrepancy between the display in Cura and in Cura Connect are consistent. 
[DummyTest.3mf.zip](https://github.com/Ultimaker/Cura/files/1950918/DummyTest.3mf.zip)
Created the project for testing a few minutes ago. 

CuraConnect in Safari:
![screen shot 2018-04-26 at 13 35 44](https://user-images.githubusercontent.com/759145/39303671-5560cd24-4957-11e8-95e8-e7da676b1367.png)


Cura (3.3.1) display of printer status at almost the same time:
![screen shot 2018-04-26 at 13 35 38](https://user-images.githubusercontent.com/759145/39303555-e28ff130-4956-11e8-90b9-3164910caa74.png)

**Comment by Spirou42** [comment]
Is it possible, that some print job status entry got stuck on the UM3 so it got displayed in CuraConnect over and over again? I ask that question cause the "finished" entry does not display the name of the last print but always the same "old" name. The status of the printers cores on the other hand is updated and showed the correct values.
So maybe there is an status snippet in CuraConnect on my printer, that the software can't get rid off cause there is no "real" print job any more that can trigger a state change for this orphan status.

**Comment by Spirou42** [comment]
Oops, there might be a slight misunderstanding here. 
The actual print starts, runs, and finnisches without any problem. The problem I have described seams to be a "display only" problem. 
The name of the print marked as finished stays the same. It is an old print job name. The current print job works well but is not displayed in CuraConnect correctly. Thats why i asked the question about a possibly stuck job status on my UM3 a while ago (directly above your comment).

**Comment by Spirou42** [comment]
after resetting cura connect on the printer, the problem has gone.
