### ISSUE TITLE
[3.2.1] Buildplate temperature set on highest, even if material not used.

### ISSUE THREAD

**Issue by Sterke-Yerke** [Ultimaker/Cura#3578]
**Application Version**
Cura 3.2.1.

**Platform**
Windows 10

**Qt**
NA

**PyQt**
NA

**Display Driver**
NA

**Printer**
Ultimaker 3

**Steps to Reproduce**
In Cura 3.2.1., do next actions:
1. Select PLA material in extruder 1. Buildplate temperature automaticly set to 60 degr.C 
2. Select ABS material in extruder 2. Buildplate temperature automaticly set to 80 degr.C
3. Load any model in Cura. Select PLA for material and if applicable PLA material for buidplate adhesion and/or support.

**Actual Results**
Buildplate temperature is set to the highest (ABS) temperature.

**Expected results**
While no ABS is used in the print, it is expected the lower buildplate temperature of PLA is choosen.
**When just one material is choosen in a print, I expect the buildplate temperature of the choosen material.** 

**Additional Information**
I like to have two different materials in my Ultimaker to be able to quickly change from quick and easy to final and more robust materials. Every time I switch to the other material, I have to remember manualy (re)setting the buildplate temperature to the correct one, even if just one of the materials is used. Because buildplate temperature is a shared parameter, every time the other material is adapted as well.

**Comment by ianpaschal** [comment]
This is fixed by using the "disable extruder" feature in 3.3. That way you can keep ABS on your 2nd extruder and disable it when not in use, causing Cura to use your PLA settings.
