### ISSUE TITLE
In both 3.2.1 and 3.3 Cura locks up just going thru the pull down menus

### ISSUE THREAD

**Issue by jayyusko** [Ultimaker/Cura#3586]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment]
Please at least _try_ to use the issue template.

**Comment by Ghostkeeper** [comment]
Cannot reproduce. The pull-downs work fine.
![screenshot from 2018-04-25 11-11-41](https://user-images.githubusercontent.com/2448634/39236585-78348608-4879-11e8-8a7e-bf8b41dc2baf.png)
