### ISSUE TITLE
Cura 3.3B Open Project.

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3587]
**Application Version**
3.3B
**Platform**
Win10/64

**Display Driver**
NV 391.01

**Steps to Reproduce**
Open saved Project
**Actual Results**
Cura still messes object's placement on Print bed.
**Expected results**
Cura must open saved projects exactly as saved.
**Additional Information**
Same issue reported for 3.2.1: https://github.com/Ultimaker/Cura/issues/3201

**Comment by fieldOfView** [comment]
Overloading devs with badly filed duplicate issues will not get this fixed sooner.

**Comment by LipuFei** [comment]
Hi @Thisismydigitalself , could you share your project file that has this problem? Thanks.

**Comment by Ghostkeeper** [comment]
This is a duplicate of #3201.
