### ISSUE TITLE
Cura 3.3B profiles - Imported half of my 3.2.1 Profiles.

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3588]
**Application Version**
3.3B
**Platform**
Win10/64
 
**Display Driver**
NV 391.01
 
**Steps to Reproduce**
Just install 3.3B and check Profiles list (can't take screenshot as Cura UI closes this pull down menu when trying to capture).

**Actual Results**
Expect to see all my profiles imported/copied over to 3.3
**Expected results**
About half my profiles are not shown.

**Comment by jackha** [comment]
Can you share your 3.2.1 config folder? That would really help us debug this.

**Comment by mtmello2003** [comment]
Same issue here....

Example:
![image](https://user-images.githubusercontent.com/15361590/38088871-d03c92e2-3333-11e8-91d5-105d7872b36f.png)

**Comment by diegopradogesto** [comment]
I will close this since it seems to be the same as #3589
