### ISSUE TITLE
Cura 3.3 Printer settings (Custom FDM)

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3589]
**Application Version**
3.3B
**Platform**
Win10/64
 
**Display Driver**
NV 391.01
 
**Steps to Reproduce**
after installing 3.3B I checked my printer settings. they were all wrong - Start/End gcodes and also the printer profile as well.

**Actual Results**
Wrong settings (same printer name though..)
**Expected results**
Expect to see all my printers imported/copied over to 3.3 as-is in 3.2.1

**Comment by jackha** [comment]
I think you upgraded from 3.2.1? Is it possible to get your 3.2.1 config folder?
What's wrong? Does it give different values / is it empty / something else?

**Comment by diegopradogesto** [comment]
@Thisismydigitalself can you try with 3.3.1 if it still happens? If not, can you please send us the 3.2 data folder?

**Comment by ianpaschal** [comment]
Never heard back; closing.
