### ISSUE TITLE
Marlin 1.1.8 configuration issue for Anet A6 with a BlTouch sensor

### ISSUE THREAD

**Issue by XAVIER59165** [Ultimaker/Cura#3591]
You do a great job !

**Application Version**
1.1.8

**Platform**
MARLIN

**Qt**

**PyQt**

**Display Driver**

**Printer**
ANET A6

**Steps to Reproduce**

**Actual Results**
I can not configuration Marlin 1.1.8 for ANET A6 with a BlTouch sensor.

**Expected results**
I would like to have a marlin ( it does not matter the version ) configure for my ANET A6 with a BlTouch sensor installed.

**Additional Information**
here is the sensor support :
 https://www.thingiverse.com/thing:2451350

**Comment by fieldOfView** [comment]
We don't support Marlin (or any firmware) here. This repository is only about Cura.
