### ISSUE TITLE
Improvement Request: Adhesion extruder option

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3594]
Please add a option to "no override" to build plate adhesion > build plate adhesion extruder that will use the active extruder.

Actually, I need to choose between left or right (2 extruder in my case).

![image](https://user-images.githubusercontent.com/15361590/38090605-838baf0e-3339-11e8-8b6d-a87f6e88ba30.png)

**Comment by ChrisTerBeke** [comment]
There is no default for this as the setting is not inherited, so you can't 'not override'.

**Comment by mtmello2003** [comment]
in 3.3B there is an option to disable and make active an extruder btw I guess if I use select just one extruder with a part to be printed, this one is the "default".

**Comment by BagelOrb** [comment]
It is not clear to me whether your suggestion is what the OP means.

Could you explain the issue a bit more? Could you formulate the problem you are faced with without the suggested feature?

**Comment by Ghostkeeper** [comment]
We've solved this in a different way: If you disable an extruder but had one of these settings (such as Build Plate Adhesion Extruder) set on the extruder that you disabled, it'll select a different extruder that is still active.

So now if you disable all extruders except one, the extruder setting will always end up on the one extruder that you didn't disable.

**Comment by mtmello2003** [comment]
Perfect solution! tks
