### ISSUE TITLE
Feature request: "important faces" / reduction of travel entry/exit points

### ISSUE THREAD

**Issue by rms95** [Ultimaker/Cura#3600]
I'm mostly printing mechanincal stuff for prototyping. Sometimes the place where a movement/travel of the head starts/stops is just on an annoying place (like in the middle of a sliding/hinging/bearing part), generating these tiny parts of plastic on an otherwise perfect surface. I understand that travel is necessary and minimized allready, but would it be possible to have the option to select some faces that wont be used to "travel through", and get these marks on them? This can of course go at the cost of other faces.

Not sure if I'm the only one with this problem, but fine tuning the retraction speed does not really to the trick.

Maybe an option to start and stop the travel vertically instead of horizontal/sidewards could solve this as well. (This would probably add significant print time, but that would be totally worth it in my case.)
2-4mm Z-travel might do the trick already.

**Comment by BagelOrb** [comment]
Very interesting! Maybe add an option to load meshes and set those areas as disallowed travel area.

It is doable and I do see the usecase here.

It could work similar to how support removal meshes work. You should read up on those if you don't know own about them.

Will keep this idea in mind..
