### ISSUE TITLE
Three perimeter (1.2mm) wall  

### ISSUE THREAD

**Issue by kondzio29** [Ultimaker/Cura#3605]
**Application Version**
3.3.0

**Platform**
Windows 10

**Qt**

**PyQt**

**Display Driver**
It is not related to GUI 

**Printer**
Custom printer setup

**Steps to Reproduce**
I am making a model with 1.2 wall thickness, and in CURA i set wall thickness to 1.2mm, in ver. 2.7 it is working fine, and generates wall made of three perimeters, with no additional infil. But in 3.2.1 and also in 3.3 it generates mess that causes my printer to retract after each dot of wall infill

**Actual Results**
Results produced by version above 2.7.0 including 3.3.0
![photo_2018-03-30_22-12-59](https://user-images.githubusercontent.com/37940885/38152321-85c42d3a-3467-11e8-8452-201bb1dc356f.jpg)
those yellow lines causes printer to retract and make a dot of filament, and not onlu the print tooks more time, but I experienced filament jams and failed prints due to that behavior.

**Expected results**
Results that were produced by version 2.7.0 
![photo_2018-03-30_22-15-19](https://user-images.githubusercontent.com/37940885/38152389-e07ac04a-3467-11e8-99cd-f9646614558d.jpg)
Those lines resulted in good prints and none of them failed. 

**Additional Information**
in both versions i used the same settings with 100% infill if that matters. 
I tried resetting settings, reinstalling cura, and wiping the registry without sucess. Only on cura 2.7 i was getting result i was expecting. 

[CFDMP_maly top_curaproject.ZIP](https://github.com/Ultimaker/Cura/files/1864704/CFDMP_maly.top_curaproject.ZIP)

**Comment by Appesteijn** [comment]
Could you try to change the 'Maximum resolution' to 0.02 ? And I can't open the zipfile you attached, what is the original extension?

**Comment by Ghostkeeper** [comment]
Looking at the magic number, `50 4B 03 04`, it does appear to be a zip archive. 7-zip and Windows get an error when opening this archive though. HxD finds file names in there like `3D/3dmodel.model` which indicates that this is a 3MF file.

I've been thinking that this bug has always been in Cura. It's the natural result of how we create the walls by creating insets from the outer perimeter. You've just found a case where the second inset doesn't fit between the perimeters in the straight bits but does fit in the corners. Maybe some of the settings that relate to the walls were changed in between those two versions (such as Outer Wall Inset).

I haven't been able to reproduce it yet though. I'm now testing with this model: [ThinCylinder.zip](https://github.com/Ultimaker/Cura/files/1869659/ThinCylinder.zip)
I tried saving as CuraProject but that gave an error so I'll just say that I used an outer wall line width of 0.345 and inner wall line width of 0.359 to produce a similar but different effect that seems to be the result of rounding errors. With an inner wall line width of 0.358 or 0.360 the result is as expected. So it seems to be a property of how the model was triangulated. My triangulation was done by OpenSCAD, which doesn't taper the corners in any way.

**Comment by kondzio29** [comment]
@Ghostkeeper but how it is that Cura 2.7 can generate such walls using the same model as 3.3? It is exact same STL. I have been using Cura like that for printing walls for a long time without problems. It reduces print time greatly. When cura wants to make that weird infill inside walls it causes a ton of retraction between each dot of extruded filament and finally nozzle blockage.

**Comment by BagelOrb** [comment]
Yellow is infill. It might be a problem of the infill overlap setting.

Or it might be perimeter gaps. Does the problem reproduce if Fill gaps between walls is enabled?

Note: your model cannot have a wall thickness of 3 walls, because the model itself is as thick as 3 walls, meaning that it can only fit 1.5 wall on each side. That's why it's having more trouble with this model than if it was 1.6mm thick, which supports 2 walls on each side.

**Comment by BagelOrb** [comment]
* if Fill Gaps is _disabled_

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper but how it is that Cura 2.7 can generate such walls using the same model as 3.3? It is exact same STL. I have been using Cura like that for printing walls for a long time without problems. It reduces print time greatly. When cura wants to make that weird infill inside walls it causes a ton of retraction between each dot of extruded filament and finally nozzle blockage.

Because you are using different settings in 2.7. You can see in your screenshot that the line width is 0.4mm in Cura 3.2 and 0.38mm in Cura 2.7.

**Comment by gumert** [comment]
I reproduced similar behavior in Cura 3.2.1 and 2.7. I tried with a smaller diameter cylinder initially and didn't have any luck. At some point, I thought about trying a larger diameter cylinder and got a similar looking, but slightly different, behavior.

![cura1](https://user-images.githubusercontent.com/14635011/38282413-f2c9ce62-377d-11e8-950a-329bf73db3e9.png)

Interesting, it looks like the behavior is a function of the wall thickness. The top of the wall is 1.2 mm wide, and then tapers after a few layers. Every layer of the taper, aside from one, looks normal. However, one of the layers in the tapered section contains a similar looking anomaly. 

![cura2](https://user-images.githubusercontent.com/14635011/38282414-f2dbd76a-377d-11e8-98dc-11a9897b05f6.png)

[STL can be found here](https://www.thingiverse.com/thing:2849537)

**Comment by Xtrudor** [comment]
Same here. 1.2 mm wall. Wall thickness 0.8 mm. Line width 0.4 mm. No middle line!
![nowhere](https://user-images.githubusercontent.com/38377436/38768297-893f9bf8-3fbf-11e8-8a2c-782e299ffad4.jpg)
![everywhere](https://user-images.githubusercontent.com/38377436/38768296-892f4e2e-3fbf-11e8-9a9d-e9a9162bc0a5.jpg)

**Comment by lolorc** [comment]
issue confirmed here as well

**Comment by Xtrudor** [comment]
If that helps... Flat rail with 4 mm walls... no walls. Print Thin Walls = ugly wall. Negative Outer Wall Inset looks ok...
![nowall](https://user-images.githubusercontent.com/38377436/39135569-3d474802-46e7-11e8-96f5-f5fda2cfe22c.jpg)
![uglywall](https://user-images.githubusercontent.com/38377436/39135582-4552e9de-46e7-11e8-91aa-89f51839131a.jpg)
![wallinset](https://user-images.githubusercontent.com/38377436/39135594-4b90c4ce-46e7-11e8-9fdc-4b2e39995f2c.jpg)

**Comment by lolorc** [comment]
thought the small negative outer wall inset was not needed anymore. IIRC it was useful to print hollowed objects with wall width==line width

**Comment by fatalelieberi** [comment]
I have this problem too when printing my model. In case some data are needed, I'm sharing with you guys the STL, Project, and Setting files.

[MyPrinter.curaproject.zip](https://github.com/Ultimaker/Cura/files/2019059/MyPrinter.curaproject.zip)
[ArcReactorMkI v3_P17009-0008-Arc Base_2.zip](https://github.com/Ultimaker/Cura/files/2019060/ArcReactorMkI.v3_P17009-0008-Arc.Base_2.zip)

![thin walls problem](https://user-images.githubusercontent.com/19477587/40264266-939bb938-5b49-11e8-86e2-720784ae5209.png)

**Comment by fatalelieberi** [comment]
Awesome! I tried Cura 3.4 and it worked perfectly! No more rough thin wall surface anymore.

![image](https://user-images.githubusercontent.com/19477587/41961497-d249cf52-7a1c-11e8-875b-950b2aae8f5b.png)

**Comment by hwgfp** [comment]
Hi, everyone.
I think I have the same issue with Version 3.6 (i am just starting with cura and 3d printing).  I made a simple cylinder and set the infill to 100 %. Unfortunately, the infill is no continuous circle. 

![image](https://user-images.githubusercontent.com/9553493/52899812-9a2b0980-31ee-11e9-9fae-9bd1401c2b28.png)

.stl file:
[becher.zip](https://github.com/Ultimaker/Cura/files/2871895/becher.zip)

**Comment by Ghostkeeper** [comment]
> I think I have the same issue with Version 3.6.0 (i am just starting with cura and 3d printing). I made a simple cylinder and set the infill to 100 %. Unfortunately, the infill is no continuous circle.

Your model doesn't have equal thickness everywhere. You can see it in the screenshot you made. It looks like the inside perimeter has a different resolution than the outside one, causing the vertices to misalign. At the top of the cylinder in your screenshot, you can see that the inside corners of the inner perimeter are about halfway along an edge in the outside perimeter. That makes the perimeter slightly thinner in that part of your cylinder and prevents Cura from fitting another wall in there.

**Comment by hwgfp** [comment]
Thank you. I think I exported the mesh not precise enough from FreeCaD. Therefore was my object more angular than round.

**Comment by rolpal** [comment]
Thanks to the comment of @Ghostkeeper above pointnig at the accuracy of the perimeters I solved a similar problem.
I want to print a square with rounder corners and three lines of thickness as a part of a design.
I made the wall 1,2mm (0,4mm nozzle ) and wall line count set to 3 (for the sake of the rest of the print). This gave me continuous lines in outer and inner wall but the inside was sliced as diagonal infills.
After changing one of the wall line width to 0,395 the wall became three continuous lines.
Any experimentation with infill pattern, %, wall line counts etc. had no effect.

Conclusion(?): Cura will only use continuous line if it will fitt IN the gap and 0,4 does not fit IN 0,4.

I hope this will add some insight to the problem of not getting continuous lines in walls.

**Comment by Ghostkeeper** [comment]
> This gave me continuous lines in outer and inner wall but the inside was sliced as diagonal infills.

You might be encountering this issue: https://github.com/Ultimaker/Cura/issues/5110

> BUT... it gave me another problem with uneven (over) extrusion in the outer wall next to the Z-seam.
Tried different settings but cant fix it but that is not for this thread...

Maybe try adjusting the Coasting settings.
