### ISSUE TITLE
Cura3.2.1 material parameters for UM2+

### ISSUE THREAD

**Issue by 2ndClassUser** [Ultimaker/Cura#3610]
**Application Version**
3.2.1

**Platform**
win 10

**Qt**

**PyQt**

**Display Driver**
Geforce gtx

**Printer**
Ultimaker 2+

**Steps to Reproduce**
make material parameters visible and tunable.
 Esp. initial printplate temp, printplate temp.

**Actual Results**
nothing, except for UM3-users

**Expected results**
visible and tweakable material-parameters for UM2+ (second-class)-users.

**Additional Information**
(I alternatively tried to activate the included "TweakatZ"-plugin, but the new Cura refuses to load that  ".py"-file.
Im not a progrmmer to convert it to a ".curaplugin"-file.
Im tired of searching forums and communities)

**Comment by alekseisasin** [comment]
Unfortunately it is correct behavior. Even it was already in Cura 3.1
If will open a Preferencse, in Settings you can find "Initial Printing Temperature", hover mouse cursor over the exclamation mark. You will see that the settings has dependency on 'Enable Nozzle Temperature Control ' and this setting is available for certain Gcode flavour. It means UM2 uses different flavor and the setting is not available for it.

**Comment by fieldOfView** [comment]
@2ndClassUser, if you go to Machine Settings on the Printers pane of the Preferences, you can set the gcode flavor to "Marlin" (instead of "Ultimaker 2"). Among other things, this will give you full control over temperatures.
