### ISSUE TITLE
(3.3.0 beta)   Support blocker size on resize object

### ISSUE THREAD

**Issue by macaron16** [Ultimaker/Cura#3611]
**Application Version**
3.3.0 beta

**Platform**
OsX high sierra

**Printer**
Anet A8

**Steps to Reproduce**
After import a STL file, change the size.
For example : 200%
Select support blocker... the size of the box will be huge.

**Actual Results**
On a 1000% resize object, i had a support blocker box higher than the printing area !

**Additional Information**
Could be great to let the user define the size box...

**Comment by fieldOfView** [comment]
Already fixed in https://github.com/Ultimaker/Cura/pull/3545
Thanks for reporting.
