### ISSUE TITLE
[3.x] Request: Turning the fan on or off, depending on the type line

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#3624]
I want regulate the type line dependent fan. For example i want off fan in the infills and on in external perimeters.

**Comment by AbeFM** [comment]
I was just going to request a feature to turn off fan on priming tower and ooze shield. It would really help.

**Comment by ianpaschal** [comment]
For internal reference: JIRA CURA-5305

**Comment by Ghostkeeper** [comment]
Our project manager removed this from our planning because it was not seen as important enough. We'll defer it for now.

**Comment by GregValiant** [comment]
Hello.
The post-processor "Advanced Cooling Fan Control" has been added to Cura and has options for both "By Feature" and "By Layer".
I'll go ahead and close this.
