### ISSUE TITLE
Special modes -> surfaces mode - surface acting strange

### ISSUE THREAD

**Issue by rooiejoris** [Ultimaker/Cura#3629]
**Application Version**
Cura 3.2.1

**Platform**
MacOS 10.11.6

**Printer**
see project file attached

**Steps to Reproduce**
make a mesh
and use the settings as in the project file, or basically use follow mesh surface

**Actual Results**
Sometimes very strange travel moves. [And I have seen and heard sometimes lines are double]
If it is a closed mesh, I do get the desired result, but I would expect with an open mesh that it would travel towards the beginning or just reverse the path. Don't know what would be best, maybe it should even be an option...

**Expected results**
It should just generate a line which is following the mesh surface. It works great in the 'old' cura, the feature was called "Only follow mesh surface"

**Additional Information**
See screenshot with the excessive travel moves [you shuold see none if it would follow the mesh]
I use and abuse this functionality to really control the print moves on some parts. You get complete freedom and control in the print strategy. Also nice to experiment with custom infill paterns. Would be very nice if this could also be implemented for infill meshes

<img width="408" alt="image" src="https://user-images.githubusercontent.com/1224023/38431950-387c7636-39c6-11e8-952f-43dd78326d11.png">

[two_project_files.zip](https://github.com/Ultimaker/Cura/files/1884758/two_project_files.zip)

and the application which motivated me to write this issue... : )
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1224023/38432606-525425c0-39c8-11e8-92b2-85fd26a06bd1.png">

**Comment by Ghostkeeper** [comment]
Wow, slicing that thing took like half an hour on my computer.

**Comment by Ghostkeeper** [comment]
It looks like the lines are not properly attached to each other in this mode. Normally this is done when creating the polygons, but in surface mode we don't create polygons. It seems to behave as if every sliced triangle is a separate line.

http://dulek.net/work/breaking_lines.webm

**Comment by jackha** [comment]
So there is actually a thing which is the same as "Only follow mesh surface": In Surface Mode you choose Surface. But as @Ghostkeeper said, on this model it breaks up in smaller pieces. Although in my slice it jumps only a few times per layer instead of all the time. 

@rooiejoris can you try to print with it and see if that helps?

btw awesome application :-)

**Comment by rooiejoris** [comment]
Hi @jackha,

I tried Surface, but it acts different than the 'same' feature as in the old cura's.
That exactly is the problem... : )

cheers / joris

**Comment by jackha** [comment]
I'm currently printing one of those, see what comes out.

**Comment by jackha** [comment]
Also as part of another issue, we've greatly reduced the "jumping around". Only on a few layers I see a single jump.

For reference: CURA-5317 CURA-5455
