### ISSUE TITLE
[3.2.1] Reload all models reloads printer visualization above bed

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#3633]
**3.2.1**

**Win10**

**Prusa MK2 predefined**

**Steps to Reproduce**
Right click on bed, Reload all models

**Actual Results**
Next to the model you are slicing, also the nozzle.stl and prusai3_platform.stl get reload.
 (and placed in the recently opened files)

**Expected results**
- do not put the nozzle and bed stl in the recently opened files list
- keep bed visualization in correct location

**Additional Information**
Fresh opened view
![2018-04-08 png](https://user-images.githubusercontent.com/29209302/38464976-58509ed2-3b16-11e8-8f92-df9e570d4cf5.jpg)
After reload all models
![2018-04-08 1 png](https://user-images.githubusercontent.com/29209302/38464980-78f1e86c-3b16-11e8-9e05-5aa6b2cf72f5.jpg)

**Comment by Ghostkeeper** [comment]
This has been fixed in 3.3.
