### ISSUE TITLE
[3.3-beta] Improvement Request: Moveable and Scalable Support Blocker

### ISSUE THREAD

**Issue by fatalelieberi** [Ultimaker/Cura#3636]
**Application Version**
Cura 3.3 beta

**Platform**
Windows 10

**Printer**
Tevo Tornado 

**Actual Results**
The support blocker is rather difficult to use. When I want to block some spots from any support, the placement of the block is rather difficult to be predicted. Also, when I put it near the bottom of the model, it causes the model to be lifted and more supports are generated for the lifted part.

**Expected results**
The placement of the blocker should be easy. It can be very helpful if there's a preview where the blocker will be placed. At least, it will be great if the blocker cube can be moved and scaled just like regular model. Also, please don't make the part lifted if the blocker cube is close to the bed.

**Additional Information**
![blocker lifts model](https://user-images.githubusercontent.com/19477587/38469587-548d58f6-3b81-11e8-99c1-c5ff6d1c32d5.png)

**Comment by smartavionics** [comment]
> At least, it will be great if the blocker cube can be moved and scaled just like regular model. 

You can do that, just select the move or scale tool and then click on a blocker cube and you can move or scale it.

**Comment by fatalelieberi** [comment]
Damn, I didn't notice that. I thought I couldn't move it because each time I clicked on the cube, it just disappeared (removed).

**Comment by fieldOfView** [comment]
>  Also, when I put it near the bottom of the model, it causes the model to be lifted and more supports are generated for the lifted part.

A general tip: don't hide a bug report in a feature request. I'll see what I can do to fix this before the 3.3 release.

**Comment by fieldOfView** [comment]
Regarding the feature request: My original plan was to be able to click and drag on an area if the model. Dragging would scale the support blocker. The same would work for already placed supports; drag them to resize. Dragging them with the shift or control key could move them around. The tool could remember the scale of the last placed support blocker.

**Comment by fatalelieberi** [comment]
> A general tip: don't hide a bug report in a feature request. I'll see what I can do to fix this before the 3.3 release.
Sorry about that, I will remind myself make a new thread if I find a new bug.

> My original plan was to be able to click and drag on an area if the model. Dragging would scale the support blocker. The same would work for already placed supports; drag them to resize. Dragging them with the shift or control key could move them around. The tool could remember the scale of the last placed support blocker.
That's a good idea so user can manipulate the blocker intuitively as long there's a Help Pop-up box. However, in my opinion, dragging to scale seems counter intuitive, people are used to moving things by dragging. So, it might be better to assign dragging as a move command.

**Comment by smartavionics** [comment]
Hi, I must have missed the update, where did this get fixed/solved?

**Comment by ianpaschal** [comment]
From fieldOfView:

> Update: Fixed in #3545

**Comment by smartavionics** [comment]
Ah, OK, I was thinking of some other changes for the support blocker that had been discussed.

**Comment by ianpaschal** [comment]
If anyone wants to open a new issue specifically for those things that's fine but the original question was answered and improvements were made so to me that qualifies as closable. And this sort of proves the trick of not knowing if an issue/ticket is "done" if it mutates too much along the way.

**Comment by fieldOfView** [comment]
The original request was NOT implemented/fixed. I’m still planning to do so, but would request to keep this issue open untill the original request is implemented (or rejected)

**Comment by ianpaschal** [comment]
Okay thanks for clarifying.

**Comment by ianpaschal** [comment]
I'm a bit confused but the original request for "Moveable and Scalable Support Blocker" is very much existing (thank you Aldo). Additionally, I can't recreate the bug of the support blocker pushing the model off the build plate (well, it does, but corrects).
