### ISSUE TITLE
Can't escape Layer View!

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#364]
When in layer view, selecting solid view again reloads the layer view instead of going back to the solid view.

**Comment by BagelOrb** [comment]
perhaps related:
double layer view (after rescaling)
![cura_double_layer_view](https://cloud.githubusercontent.com/assets/8895761/9785649/34665a9a-57b4-11e5-8c46-a56aa3298008.png)

**Comment by BagelOrb** [comment]
Possibly related: https://github.com/Ultimaker/Cura/issues/302

**Comment by nallath** [comment]
Confirmed the issue.

**Comment by awhiemstra** [comment]
The layer change bug is fixed now. The dupe bug is unrelated.
