### ISSUE TITLE
[Beta 3.3.0] How to update plugins?

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#3647]
I read [here](https://github.com/fieldOfView/OctoPrintPlugin/issues/73#issuecomment-380122314) that it should be possible to update plugins, but how? There is no "Update" button...

![screenshot from 2018-04-10 16-53-34](https://user-images.githubusercontent.com/2480569/38564615-0a3cd6e2-3ccf-11e8-9193-6cef35132d2f.png)
![screenshot from 2018-04-10 16-54-07](https://user-images.githubusercontent.com/2480569/38564616-0a637e8c-3ccf-11e8-8b85-ca641fdb3099.png)

cc @fieldOfView

**Comment by fieldOfView** [comment]
It does not help that neither the plugin browser nor the plugin manager show version numbers.

**Comment by LipuFei** [comment]
Hi @probonopd , there was a bug in plugin upgrade detection and it has been fixed in CURA-5202. Here are the commits:
 - 19937d1be07eb919ae1f6f791216c95fc2ffcdbc
 - 95f4515e93144e5a1c23f9773a2d58b69fcdd0ab

**Comment by probonopd** [comment]
Thanks, so looking forward to the next beta. Keep up the great work!
