### ISSUE TITLE
 problem covered holes

### ISSUE THREAD

**Issue by carleas** [Ultimaker/Cura#3654]
HI!

I have a problem with cura 3.2.1 i import a model with holes and the program cover this.
I import diferents models, with everyone do the same.
The model doesn't have issues if i check  with X ray.
If I fixing the model in the floor the problem persist.

I hope an answer as soon as possible.

Tanks

PD: attach diferents pictures with the problem 

![image](https://user-images.githubusercontent.com/34423772/38628822-99bd289c-3db2-11e8-9188-7062c3933cd5.png)

![image](https://user-images.githubusercontent.com/34423772/38628867-bdaf00a4-3db2-11e8-8ae8-0e7ec6383c7c.png)
![image](https://user-images.githubusercontent.com/34423772/38628953-f663da14-3db2-11e8-8033-66d4de98ad86.png)

**Comment by smartavionics** [comment]
Hi, it may be a problem with the model, can you please make that available so we can check it. Thanks.

**Comment by BagelOrb** [comment]
Try fiddling with the mesh fix settings. Try disabling Union Overlapping Volumes.

**Comment by carleas** [comment]
How can i make model available?
Sorry but i have the program with another lenguage and i don't find where stay this option?


Tanks

**Comment by smartavionics** [comment]
Zip the STL file and then attach the zip file to this issue.

**Comment by BagelOrb** [comment]
Better yet, save the .curaproject.3mf file, rename it to zip and attach
that.

**Comment by carleas** [comment]
[Hole problem.zip](https://github.com/Ultimaker/Cura/files/1919279/Hole.problem.zip)
[Hole problem.zip](https://github.com/Ultimaker/Cura/files/1919280/Hole.problem.zip)

**Comment by smartavionics** [comment]
If you turn off "Union overlapping volumes" then the hole appears.

Freecad reports this model as having self-intersections, perhaps that is the reason that Cura has a problem with it.

**Comment by carleas** [comment]
Solver tanks!

I turn off Union overlapping volumes and i import te model in format .obj now all correct!

Tanks!
