### ISSUE TITLE
Bug: layer view nr doesnt fit

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#366]
layer view nr higher than 9 doesnt fit and gets abbreviated to "..."
![cura_layer_view_nr](https://cloud.githubusercontent.com/assets/8895761/9786281/2f474e20-57b9-11e5-873e-16beb2895f92.png)

**Comment by BagelOrb** [comment]
It also doesn't support negative numbers, which is needed for visualizing the raft.

**Comment by Ghostkeeper** [comment]
Was this fixed, or not reproducible?

**Comment by TMHogenhout** [comment]
I couldn't reproduce the problem, but I put it in Jira to look at it anyways.

**Comment by nallath** [comment]
I dont see it on my system. I used to have it, so i'm guessing its fixed.
