### ISSUE TITLE
[3.2.1] Rotated+scaled object slices incorrectly

### ISSUE THREAD

**Issue by kaimikael** [Ultimaker/Cura#3660]
**Application Version**

Ultimaker Cura 3.2.1
**Platform**

OS X 10.13.4
**Qt**

**PyQt**

**Display Driver**

Chipset Model:	Intel HD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x591b
  Revision ID:	0x0004
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.29 [3.2.8]
  Metal:	Supported, feature set macOS GPUFamily1 v3

**Printer**

Ultimaker 2+

**Steps to Reproduce**

1. Open STL file (attached)
2. Select Lay flat.
3. Use Layer view
4. Layers look OK.
5. Rotate object to lie on its side
6. Layers look OK
7. Scale up object to approx 200%
8. Layers are incomplete
9. Raise object to standing position
10. Layers look OK.
I attach a video to show what I do.

**Actual Results**

The slicing seems to partially fail when the object has been rotated+scaled.  There are error messages in the log that may be related to this.

**Expected results**

I expected that the object would slice correctly regardless of orientation.

**Additional Information**

It is of course perfectly possible that the STL file is somehow broken, but I've done my best to clean it up in meshlab and if it still is faulty, I would appreciate if Cura could warn about it.  I'm quite keen to try to print the object on its side, in the hope that it will reduce warping—standing up the rectangular bottom plates warp so badly they catch on the the print head and ruin the print no matter what I do to attach them to the build plate.

Attaching STL file, project file, log file, screen video.
[Scalingproblem.3mf.zip](https://github.com/Ultimaker/Cura/files/1902278/Scalingproblem.3mf.zip)
[ScalingProblem.log.zip](https://github.com/Ultimaker/Cura/files/1902279/ScalingProblem.log.zip)
[ScalingProblem.mp4.zip](https://github.com/Ultimaker/Cura/files/1902280/ScalingProblem.mp4.zip)
[ScalingProblem.stl.zip](https://github.com/Ultimaker/Cura/files/1902284/ScalingProblem.stl.zip)

**Comment by diegopradogesto** [comment]
Probably is because the model is incorrect. This is what I see when I open it in Meshmixer and in Cura itself.
![image](https://user-images.githubusercontent.com/15830521/38723466-7bd4f8aa-3f01-11e8-838d-65d46193a4d4.png)
![image](https://user-images.githubusercontent.com/15830521/38724614-0e378b10-3f05-11e8-95d5-2e5272f5281b.png)

Please fix the model and then try again to see if it still happens.

**Comment by kaimikael** [comment]
Yes, netfabb did the trick, so a faulty model.  Still, it would be nice to get some kind of warning.  I see in the log file that there were a number of warnings, but they did not propagate to me, the user, in an obvious way.

**Comment by Ghostkeeper** [comment]
More obvious than the bright red areas in your model?

**Comment by kaimikael** [comment]
The red areas, as I understand it, simply represent the outer shell of the object; in other words all models will show red areas, and this will not be an error.  
I think that it would be nice to have seen the warnings that now ended up in the log file in, say, a console window, possibly with some small marker indicating there is output in the console window if it isn't visible at the moment.

**Comment by kaimikael** [comment]
Oh, in the solid view!  I see.  I have been working with the layer view.
So what you are saying is that I should never be seeing red surfaces on the top of objects, only on the undersides of objects.
Well, what can I say, I was unaware of this.  The Layer View has a legend explaining the colours displayed, maybe a similar legend could be added to the Solid view.
