### ISSUE TITLE
No project extension after gcode

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#3664]
**Application Version**
Master (around the time of 3.3 beta

**Platform**
Linux Mint

**Printer**
UM3

**Steps to Reproduce**
Save project
Save gcode
Save project

**Actual Results**
first project saved automatically with .curaproject.3mf extension
second project didn't automatically get the extension

**Expected results**
Saving a project always automatically adds the extension.

**Additional Information**
I couldn't find a duplicate, while I thought this issue was known.
I've never before explicitly experienced that it only bugs after saving to gcode, though.

**Comment by Vandrasc** [comment]
I really cannot reproduce in the latest build, maybe magically fixed? :) I tried on Ubuntu and Win and it received the extension each time.
