### ISSUE TITLE
Jerk is labeled in wrong units?

### ISSUE THREAD

**Issue by gnarf** [Ultimaker/Cura#3687]
Sorry to blow up the issue template, but this is in the current version and I imagine spans all platforms/printers.

Jerk is labeled in `mm/s` which is the wrong unit for the setting as far as I can tell.

* Speed (or velocity) is `mm/s`.
* Acceleration is `mm/s²` - or "speed change per second"
* Jerk is `mm/s³` - or "acceleration change per second"

**Comment by fieldOfView** [comment]
"jerk" in Cura is 3d printer jargon, and should not be confused with the "jerk" we know from physics. The "jerk" in Cura is actually a speed(-change), so the unit is correct:

> Jerk: The maximum instantaneous velocity change of the print head

"_instantaneous_ velocity change" means this is not "over time", so it is the difference between two speeds.

**Comment by gnarf** [comment]
Thanks!  Sorry, I'm still a bit getting into the 3d print jargon, and was confused by my physics ;)

Does the info you quoted go any more into this? I'm trying to understand what this setting means now, it made more sense to me when jerk was a "max change in acceleration".  Instant velocity change just sounds like an impossible measurement?

**Comment by fieldOfView** [comment]
A 3d printer is bound by physics, but the controller is digital. So it is very possible for a controller to "instruct" the motor to change speed instantaneously. The motor would not manage doing that (and would create actual "jerk" and "jolt" trying to do it), so firmwares implement a sort of threshold for the maximum difference in current and new speed they are making the motors turn. And this threshold was (improperly?) named "jerk". Confusing, but a fact of life.

**Comment by gnarf** [comment]
Thanks for the education! This makes a lot more sense now.
