### ISSUE TITLE
Build plate temperature is not possible to set

### ISSUE THREAD

**Issue by JeyPi** [Ultimaker/Cura#3689]
How do I set the built plate temperature. it is hidden by some feature

**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment]
Have you tried searching in the settings for "temp"? You'll find it there for sure.

Please fill out the issue template or this issue will be closed.

**Comment by diegopradogesto** [comment]
@JeyPi let us know if @fieldOfView 's message has answered your question.

**Comment by ianpaschal** [comment]
I'm going to assume it has.

**Comment by JeyPi** [comment]
Yes sorry it has.
The new cura confused me. Thanks a lot for help
