### ISSUE TITLE
[3.2.1] Print time won't display correctly in German

### ISSUE THREAD

**Issue by 10MINT** [Ultimaker/Cura#3692]
**Application Version**
3.2.1

**Platform**
Windows 10

**Display Driver**
NVIDIA GeForce GTX 1050 Ti @ 1920 x 1080 pixels
driver nvldumdx.dll in version 23.21.13.8871

**Printer**
Tevo Tarantula

**Steps to Reproduce**
1. Set lanuage to German
2. Slice any file

**Actual Results**
The print time won't display correctly (You can't read the time because the minutes are cut

**Expected results**
The print time should be readable

**Additional Information**
![screenshot 21](https://user-images.githubusercontent.com/10596945/39084677-6f8e88a8-4579-11e8-966f-9a85f800dc8b.png)

**Comment by Appesteijn** [comment]
Do you have a suggestion on how we could shorten the text on the button?

**Comment by fieldOfView** [comment]
I think the “wechseldatentrager” was changed to “datentrager” recently for this reason. “Stunden” could als be shortened to St.

**Comment by 10MINT** [comment]
What @fieldOfView suggested could solve the issue

**Comment by Ghostkeeper** [comment]
The "datentrager" translation was already applied. I've now also applied the other suggestion with these two commits:

* https://github.com/Ultimaker/Cura/commit/8e3e5f50b4d3d7fb5263fe1a90ca66f3ae7e8943
* https://github.com/Ultimaker/Uranium/commit/63b6da99c3447509810b6a862a097f335b5d37a1

It should be easier to read next release.
