### ISSUE TITLE
Zig-zag skin pattern sometimes has spurious lines at ends

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3698]
**Application Version**

Master branch
**Platform**

Linux
**Qt**

5.8.0
**PyQt**

5.8.2
**Display Driver**

OpenGL Version:  4.5 (Core Profile) Mesa 17.2.8
**Printer**

Kossel XL
**Steps to Reproduce**

Load model, slice using zigzag skin pattern, view layers.

**Actual Results**

Zig-zag skin sometimes has extra line segments.

**Expected results**

Zig-zag skin should not have extra line segments.

**Additional Information**

This image shows an example. In the top left corner is an extra line.

![screenshot_2018-04-22_16-41-42](https://user-images.githubusercontent.com/585618/39096899-4228bd8c-464d-11e8-9fc4-c40cab7f21a4.png)

Before that line is output, it looks correct:

![screenshot_2018-04-22_16-51-17](https://user-images.githubusercontent.com/585618/39096932-81d207a4-464d-11e8-8ff6-e58baf5d76d1.png)

**Comment by smartavionics** [comment]
The extra lines are fairly harmless except for the fact that they require an extra travel move. I don't think this used to happen so something has changed in the zig-zag department.

**Comment by Ghostkeeper** [comment]
It seems to have something to do with skins, since I can't reproduce this with infill but I can with skin.

**Comment by jackha** [comment]
We discussed it and we're not going to fix this.

**Comment by smartavionics** [comment]
That's OK because I have a PR (https://github.com/Ultimaker/CuraEngine/pull/792) that can help reduce the effect of these spurious lines.
