### ISSUE TITLE
Filename

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#370]
![cura_filename](https://cloud.githubusercontent.com/assets/8895761/9787862/82c941cc-57c6-11e5-826d-868b29cd4257.png)

How is this supposed to work?
I would expect the filename should correspond to the filename specified.

Should the filename field get autogenerated from the model filename?

**Comment by Ghostkeeper** [comment]
You mean that the gcode file should have the same filename as the "Printjob name" specified above?

**Comment by BagelOrb** [comment]
What else is Printjob name?

What's a printjob?

**Comment by nallath** [comment]
printjob name doesnt work yet if i recall correctly.

**Comment by awhiemstra** [comment]
It does not. We are currently still even debating the label for that item. :)

**Comment by awhiemstra** [comment]
This has been implemented for the next build.
