### ISSUE TITLE
Different Layer Heights (normal/initial) cause wrong support

### ISSUE THREAD

**Issue by pappy15** [Ultimaker/Cura#3701]
**Application Version**
3.2.1

**Platform**
Windows 10

**Steps to Reproduce**
Layer Height 0.2
Initial Layer Height 0.1
Generate Support

**Actual Results**
The model moves one layer up, so the initial layer only consists of support and brim. If the initial layer height is set to 0.2 like normal layer height, model and support start together at layer one.

**Expected results**
Model and support should start together at layer one, like it is with same layer height and initial layer height.

layer height 0.2 | initial layer height 0.1
![wrong support](https://user-images.githubusercontent.com/31917424/39183655-0af9df6a-47c1-11e8-814d-9198e11cce31.jpg)

layer height 0.2 | initial layer height 0.2
![right support](https://user-images.githubusercontent.com/31917424/39183820-9b704638-47c1-11e8-8326-31f50ab60b30.jpg)

**Comment by pappy15** [comment]
I updated to cura 3.3 and the problem seems to be fixed now. Thank you.

**Comment by smartavionics** [comment]
OK, great, please close the issue if you are happy.
