### ISSUE TITLE
minor bug: Z-fighting in layer view

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#371]
The top skin is z-fighting with the 'ghost' of the object.

BTW: is it intended behaviour that the ghost is there? It seems a bit hacky, but I kinda like it! You can change the position of an object while looking at the layer view!
Can't really specify why it looks like a hack to me...

![cura_z_fighting_top](https://cloud.githubusercontent.com/assets/8895761/9788197/65073188-57c8-11e5-831c-4d110e7bf039.png)

**Comment by awhiemstra** [comment]
Yes, the ghost is intended. This way you do not end up with major editing workflow differences between one view and another. I guess one reason it feels a bit hacky is that you expect to change the position of the layers and not a selection ghost. However, actually changing the layers is currently technically quite tricky.

**Comment by BagelOrb** [comment]
When a reslice has been triggered, the layer view should get cleared.

This to prevent the confusion some people have with changing the ghost and seeing the gcode stay at the same place.
https://ultimaker.com/en/community/view/17296-cura-1510-open-beta?page=2#reply-117818

**Comment by fieldOfView** [comment]
This issue can be closed. Ghosts are now rendered in a different pass than layers, so z-fighting does no longer occur
