### ISSUE TITLE
[3.3.0] Newer Marlin versions don't change bed origin on G29

### ISSUE THREAD

**Issue by tenten8401** [Ultimaker/Cura#3711]
**Application Version**
3.3

**Platform**
Manjaro Linux KDE

**Printer**
Printrbot Simple Metal

**Steps to Reproduce**
- Update Marlin to latest build on Printrbot
- Print anything

**Actual Results**
Print gets mashed against side of buildplate

**Expected results**
Print should be centered

**Additional Information**
Here's a short video of the issue: https://www.youtube.com/watch?v=WXLWZ5NAMmo

Here's the line I commented out in the printer Gcode to fix the uncentered print:
![image](https://user-images.githubusercontent.com/6174343/39223641-28102ece-4811-11e8-9cfc-bc54a61ee440.png)

**I will do some testing later with an unmodified Printrbot Simple to see if this line is even required and update the issue with my findings.**

**Comment by tenten8401** [comment]
Alright so it appears that line isn't even needed on a unmodified Printrbot running the Marlin build that came with it...
![img_20180425_101644](https://user-images.githubusercontent.com/6174343/39251981-9f97e048-4872-11e8-8c0d-903deee3be99.jpg)
![img_20180425_101651](https://user-images.githubusercontent.com/6174343/39252061-d04d101e-4872-11e8-9d69-29f6797f75c8.jpg)
![img_20180425_102929](https://user-images.githubusercontent.com/6174343/39252405-92e479b4-4873-11e8-87ae-4634a2552dc2.jpg)

**Comment by Ghostkeeper** [comment]
Thanks for testing. I've removed the line from the default starting g-code so it'll be fixed in Cura's next release.
