### ISSUE TITLE
solid view looks great, prints messed up, layer view shows messed up

### ISSUE THREAD

**Issue by superalpha0** [Ultimaker/Cura#3716]
The solid view looks fine, print it and there are slots missing on top of model.  Layer view shows missing slots.

**Application Version**
3.3.0 and 3.2

**Platform**
Windows 10

**Display Driver**
Intel HD

**Printer**
TEVO Tornado

**Steps to Reproduce**
open solid view and compare to layer view

**Actual Results**
top features/slots are missing and filled in

**Expected results**
slots should be there, just like model view

[s.zip](https://github.com/Ultimaker/Cura/files/1947261/s.zip)

**Comment by smartavionics** [comment]
You mean like this:

![screenshot_2018-04-25_15-11-54](https://user-images.githubusercontent.com/585618/39251386-096e34ea-489b-11e8-9da1-e1406227d850.png)

**Comment by smartavionics** [comment]
Sorry, try again... I think the model has some problems, the solid model has some missing surfaces:

![screenshot_2018-04-25_15-15-45](https://user-images.githubusercontent.com/585618/39251587-996fdff8-489b-11e8-8667-e29b6d4a66d9.png)


This is what freecad thinks:

![screenshot_2018-04-25_15-14-42](https://user-images.githubusercontent.com/585618/39251531-7390d346-489b-11e8-96dd-738ed03a6c6b.png)

**Comment by fieldOfView** [comment]
The model is not "watertight" or "manifold". Or in other words: it is broken. Just because Cura is able to display it does not mean it can slice it.

**Comment by ianpaschal** [comment]
You'll have to use something like MeshLab to repair it. This is not an issue with Cura.

**Comment by superalpha0** [comment]
I see what you mean.  Thanks.
