### ISSUE TITLE
Crash to desktop without error message when pressing connect to OctoPrint

### ISSUE THREAD

**Issue by mortenvat** [Ultimaker/Cura#3719]
**Application Version**
<3.3.0>

**Platform**
<Windows 10>

**Display Driver**

**Printer**
<Creality CR-10s -->

**Steps to Reproduce**
<Open CURA, Add printer/machine, Select connect OctoPrint, Configure Octoprint, Press connect >

**Actual Results**
< CURA crashes to desktop without any error message or any windows error>

**Expected results**
< Connected to Octoprint>

**Comment by ianpaschal** [comment]
This has been fixed today and is in 3.3.1, being released shortly.
