### ISSUE TITLE
[Request] Direct Download Links for logged-in users?

### ISSUE THREAD

**Issue by Snowflake6** [Ultimaker/Cura#3722]
**Application Version**
All

**Platform**
All

**Steps to Reproduce**
Try to download a copy of Cura.

**Actual Results**
Note the same form comes up every. damn. time. and you have to fill in the same. damn. info.

**Expected results**
Site should recognize a returning user and offer up a direct download link  without a survey.

**Comment by filipgoc** [comment]
In the meantime, you can use the 'I don't want to share any information' or something option to avoid filling in all the info...

**Comment by Snowflake6** [comment]
@filipgoc That is *a* solution, but I was hoping for one that allowed Ultimaker to still know that i'm a customer.  I don't mind them knowing that i'm downloading the latest versions... I just want to do it without typing it in every time.

**Comment by filipgoc** [comment]
@Snowflake6 I understand and agree. Hence the "in the meantime" in the original post, just in case you or someone else missed the no info option. Cheers.
