### ISSUE TITLE
[3.3.1] Profile name for 0.15mm layer height

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#3723]
**Application Version**
3.3.1

**Platform**
macOS 10.12.6

**Printer**
Ultimaker 2+

Profile name for 0.15mm layer height is set to `Low Quality`. I think this is misleading since 0.15 is no way "low quality". Shouldn't 0.2mm layer height be "low quality"?

![screen shot 2018-04-25 at 19 05 10](https://user-images.githubusercontent.com/1069286/39261255-41a3a720-48bc-11e8-8840-291f271fff4a.png)

**Comment by jackha** [comment]
Hi @nicolinux . Thanks for your feedback. There are and have been discussions about this. For now we developers are not going to push changes on this.

**Comment by Ghostkeeper** [comment]
Elsewhere we called it "Normal" though because "Low Quality" sounds negative.

**Comment by Vandrasc** [comment]
Fixed in master, CURA-5462.
