### ISSUE TITLE
[3.3.1] Plugin browser font color and popup after plugin update

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#3724]
**Application Version**
3.3.1

**Platform**
macOS 10.12.6

**Printer**
Ultimaker 2+

**Steps to Reproduce**
1. Menu Plugins -> Browse Plugins.

2. Update a plugin.

**Actual Results**
The info at the bottom of the plugin browser is displayed in a black font over a dark background - not readable.

![screen shot 2018-04-25 at 19 11 16](https://user-images.githubusercontent.com/1069286/39261515-00b833ec-48bd-11e8-807f-6fd65d2e5f91.png)

After updating a plugin (OctoPrint), the popup with the info to restart Cura is behind the plugin browser and not visible.

![screen shot 2018-04-25 at 19 11 41](https://user-images.githubusercontent.com/1069286/39261513-fdecb1ec-48bc-11e8-84ff-0ecfe10a85cc.png)

**Expected results**
Text should be readable and the popup should be visible in front of the plugin browser.

**Comment by fieldOfView** [comment]
Known issue, will be fixed in Cura 3.4

**Comment by ianpaschal** [comment]
Yup. Sorry about that. Will be fixed in the next version.
