### ISSUE TITLE
[3.3.1] File Name back to default when slicing

### ISSUE THREAD

**Issue by genghisnico13** [Ultimaker/Cura#3726]
**Application Version**
3.3.1

**Platform**
Linux

**Steps to Reproduce**
Load a STL, change the Save Name, change any print setting to trigger slicing.

**Actual Results**
The name gets back to the one that had when imported .

**Expected results**
The name shouldn't change as it was in version 3.2.1

Let me know if you need more info or need me to test something.

**Comment by ianpaschal** [comment]
Indeed. Reproduces for me.

**Comment by AbeFM** [comment]
+1
Frustrating when I delete model, load a new one, and it defaults to name of wrong model

**Comment by ianpaschal** [comment]
This is fixed and will be included in the 3.4 release in June. Sorry for the inconvenience in the meantime!
