### ISSUE TITLE
[3.3.1] Material profiles missing

### ISSUE THREAD

**Issue by Sterke-Yerke** [Ultimaker/Cura#3728]
**Application Version**

[3.3.1] and [3.3.0]
**Platform**

Windows 10
**Qt**

**PyQt**

**Display Driver**

intel HD Graphics 4400
**Printer**

Ultimaker 3
**Steps to Reproduce**

In a previous version of Cura (2.7) I made a profile for a new material (PETG)  from another supplier. In version 3.3.1 I want to select the material for my new print.
**Actual Results**

The material just vanished. In version 3.3.1. this material cannot be found anymore. It cannot be selected in the material selection tab (because it's not there) nor is the material visible anymore in the "manage materials" preference menu. The strange thing is that some other custom made material profiles still can be selected and are visible, while others dissapear. Moreover one of the materials (Jupiter PLA rood from 123-3D.nl) shows up twice in the material menu.
**Expected results**

I expect that when I upgrade to the next version, all material profiles are ported. I checked with the older version 3.2.1. and here the material profile is still available (See screenshots)
**Additional Information**

This is the file I found in my AppData folder of Cura 3.3, that is not shown in the menu:
[custom_material+%232.xml.zip]
(https://github.com/Ultimaker/Cura/files/1948937/custom_material.232.xml.zip)

Next two screenshots in Cura 3.3.1 and 3.2.1
![image](https://user-images.githubusercontent.com/37849195/39272125-51de96a8-48db-11e8-9ac5-eb3c747baea3.png)
The above screen is of material profiles in Cura 3.3.1. No PETG profile of Real(123-3D.nl) visible, or the PLA material from Ice. Notice the PLA rood material from 123-3D.nl shows up twice.
![image](https://user-images.githubusercontent.com/37849195/39272224-9d19a8d8-48db-11e8-960a-c7ab7e28b57f.png)
This is the screen of material profiles in Cura 3.2.1.

**Comment by Sterke-Yerke** [comment]
After a few days of experimenting by uninstalling and installing Cura 3.3.1 and resetting my printer to solve problem #3727, suddenly some custom materials appeared again and a duplicate material disappeard. It lools like a similar issue as #3744.
However not all materials appeard. The PETG profile is still not in the list, while present as a file in my AppData folder.

**Comment by jackha** [comment]
Hi @Sterke-Yerke , Thanks for your detailed report! I've investigated this and this is the result of a bug that was recently introduced. 

Workaround (for now): 
- Go to your cura install dir, then resources/definitions. On my computer it's `C:\Program Files\Ultimaker Cura 3.3\resources\definitions`
- Open ultimaker.def.json with a text editor (make sure you have permissions to write)
- Remove "generic_petg" from the exclude list, so the line looks like this: `"exclude_materials": [ "generic_hips" ]`
- Save and (re)start Cura.

Devs: See workaround, it's a problem with the excluded_materials. It somehow also excludes this specific material which is not generic_petg.

**Comment by Sterke-Yerke** [comment]
Hi Jack,

Thanks for your reply. I’m happy it’s a known issue. I can live with the work around.


Greetings,

Ype Brada

**Comment by Ghostkeeper** [comment]
This was fixed in 3.4 (according to our issue tracker).
