### ISSUE TITLE
[3.3.1] Compressed gcode file?

### ISSUE THREAD

**Issue by jossfb** [Ultimaker/Cura#3729]
[cura.zip](https://github.com/Ultimaker/Cura/files/1949115/cura.zip)

**Application Version**
3.3.1
**Platform**
Windows 10

**Display Driver**
Nvidia - 23.21.13.9065

**Printer**
Ultimaker 3

**Steps to Reproduce**
Using Slice button then Save to removable drive or file

**Actual Results**
Saves as .gcode.gz

**Expected results**
Save as .gcode

**Additional Information**
Maybe it was when i was tweaking my settings but all i was doing was adding more options to my layer height and some of the beta settings like fuzzy skin. Cant for the life of me see where to set the default slice as file type etc.. Hoping someone can shed some light.

**Comment by Ellecross** [comment]
Hey @jossfb, this is the new behavior now as compressed gcode sends faster via Network.
However, you can still save it as gcode, when you Save to File, you can still select *gcode. 
![image](https://user-images.githubusercontent.com/32929710/39301435-592695cc-494f-11e8-99b4-f6ea0a9cef1a.png)

There's a small bug there though, when you select *.gcode, it creates a double extension. But it saves it as gcode file, nevertheless.

**Comment by jackha** [comment]
Hi @jossfb . Maybe a stupid question, but do you have the most recent firmware on your UM3? I think the behavior of saving .gcode.gz for UM3 is correct from the Cura standpoint. We try to optimize all workflows, so if it doesn't work flawlessly with gcode.gz then we'll have to fix that (in the firmware).

**Comment by Ghostkeeper** [comment]
> Is there a way to change this back?

There is no way to change the default back for Ultimaker 3 and S5. It's not our intention to (and we've received some positive response from the community on ultimaker.com about it too).

You shouldn't get those warnings though. That is a bug but we can't reproduce that here. Maybe share the file?

**Comment by ChrisTerBeke** [comment]
This is now intended behaviour.

**Comment by Ghostkeeper** [comment]
> It lists an error regarding it not being optimized for the printer and when i choose to ignore these and start the print anyway: the printer then doesnt show a time reading of print time as it carries out the print.

->

> This is now intended behaviour.

I don't think this is intended behaviour. It shouldn't give warnings for .gcode.gz files. I think it might have some trouble reading the metadata without libCharon?

**Comment by Ghostkeeper** [comment]
I guess that the next question would be: What firmware version are you using on your printer?

**Comment by Ghostkeeper** [comment]
Since we haven't been able to reproduce this and we aren't receiving any indication on how it occurred, let's assume that this is no longer a problem.
