### ISSUE TITLE
[3.3.1] Fails to start after upgrade

### ISSUE THREAD

**Issue by modem7** [Ultimaker/Cura#3734]
**Version 3.3.1**

**Windows 7 x64**

**Wanhao i3 2.1**

When upgrading from 3.2, it refuses to startup with the attached error message.

Error Traceback attached.

Resetting configuration works, but realistically, re-doing the entire configuration isn't what is expected. 

![1](https://user-images.githubusercontent.com/4349962/39315834-94956f6e-496f-11e8-9ecb-7de4ea4648e6.JPG)
[crash.txt](https://github.com/Ultimaker/Cura/files/1951887/crash.txt)

Running Octoprint as well. 

**Full config folder:** 
[3.3_20180426_162019.zip](https://github.com/Ultimaker/Cura/files/1955809/3.3_20180426_162019.zip)

**stderr:**
[stderr.log](https://github.com/Ultimaker/Cura/files/1955832/stderr.log)

Thoughts on resolving?

**Comment by modem7** [comment]
Could be related to #3706?

**Comment by Ellecross** [comment]
Hey @modem7 , thanks for attaching the 3.3 config folder. I will try to replicate your issue.... but it will be easier if you attach the 3.2 config folder as well - so that we easily see what causes the crash.

**Comment by diegopradogesto** [comment]
It seems that you have a custom material called `test.xml.fdm_material` without GUID tag in it (that is mandatory). May I ask where this material profile comes from? Normally adding custom profiles from not official sources raise some issues like this since they were not created correctly.

**Comment by modem7** [comment]
Ah,

I think that came from an old version as at the time, the prices weren't
calculated correctly, so I created my own material that had that

**Comment by ChrisTerBeke** [comment]
Closing as it's not an issue with Cura itself (but rather with completely custom files).

**Comment by ChrisTerBeke** [comment]
@modem7 you can just open the file and put any valid GUID field in it. Check the other materials for examples.
