### ISSUE TITLE
[3.3.0] Cura on macOS doesn't add file extension .3mf

### ISSUE THREAD

**Issue by adrianmihalko** [Ultimaker/Cura#3735]
**Application Version**
3.3.0

**Platform**
Mac Os X

**Printer**
Ender 3

**Steps to Reproduce**
Save a project.

**Actual Results**
Saved file does not have .3mf extension

**Expected results**
Saved file does have .3mf extension, so when I click on it Cura opens it automatically. Without extension it is not possible to open project file with Cura.

**Additional Information**
Nope, that's all.

**Comment by ianpaschal** [comment]
Can you post a screen shot of your save dialog? I have a suspicion of the problem but seeing that will confirm or disconfirm that suspicion.

**Comment by adrianmihalko** [comment]
Here you go:

<img width="695" alt="screen shot 2018-04-26 at 23 04 56" src="https://user-images.githubusercontent.com/733361/39331948-49136154-49a6-11e8-8195-0a6d4dcdfa9e.png">

**Comment by adrianmihalko** [comment]
The problem is same if I save sliced model to file locally.

**Comment by johnnygizmo** [comment]
This is not just with 3mf files. If you do not at .gocde to your sliced file, it saves without one. Standard behaviour should be that if the file name does not have a matching extension to the "files of type" drop down, it should be added automatically.

**Comment by Ghostkeeper** [comment]
We've changed the dialogue that caused this bug completely for the next release. In all of our tests this now seems to be fixed.
