### ISSUE TITLE
3.3.1 Cura fails with cura.exe stopped on startup

### ISSUE THREAD

**Issue by stuartsmi** [Ultimaker/Cura#3737]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

[stderr.log](https://github.com/Ultimaker/Cura/files/1953405/stderr.log)

**Comment by stuartsmi** [comment]
None of the template items are showing. Will re log issue.

**Comment by Ghostkeeper** [comment]
You seem to have a custom profile with formulas that refer to each other circularly.

**Comment by stuartsmi** [comment]
The interesting thing is that the profile worked in 3.2.1.
