### ISSUE TITLE
Positioning and merging

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#374]
Steps:
- load model 3 times
- apply some scalings (EDIT: see below for instructions without scaling)
- merge two
- apply some scaling
- merge the third with it

Problems:
- origins of merged objects don't coincide

![cura_weird_merge_1](https://cloud.githubusercontent.com/assets/8895761/9790444/56c765ee-57d6-11e5-8936-7f7e49dbe833.png)

For clarity: a view from below showing there's a small dodecahedron in the big one:
![cura_weird_merge_2](https://cloud.githubusercontent.com/assets/8895761/9790445/57f25ef6-57d6-11e5-9ef2-39cb097075c7.png)

Merging another time lead to:
![cura_weird_merge_3](https://cloud.githubusercontent.com/assets/8895761/9790571/0ae6490a-57d7-11e5-8538-3e62220c557d.png)

perhaps the push-free causes the origins not to coincide anymore

**Comment by nallath** [comment]
This is a weird way of doing it. Objects that are merged should be objects that are -supposed- to be merged in the first place. If you scale one of those objects, but not the other, this relation is already broken.

**Comment by nallath** [comment]
We need to come up with good behaviour for this; What would be expected in this case? Would the object scale on the largest object or simply to a unity scale?

**Comment by Ghostkeeper** [comment]
Our project manager just removed this one from our planning because it's older than 12 weeks.

**Comment by fieldOfView** [comment]
@BagelOrb, wouldn't grouping instead of merging work here?

**Comment by BagelOrb** [comment]
No, the problem is that merging groups isn't well behaved.

I would expect that performing a merge on a merged group and another model would result in the same positioning as merging all objects as once.

![image](https://user-images.githubusercontent.com/8895761/33554343-91d2fb9a-d8fc-11e7-887a-f6df0bb2da5d.png)

Still it's not a big problem because you can just ungroup all and do the merge on all objects at the same time.

[pie_slices.7z.txt](https://github.com/Ultimaker/Cura/files/1527143/pie_slices.7z.txt)

**Comment by Vandrasc** [comment]
Is this still an issue? Can we close this one?

**Comment by BagelOrb** [comment]
Yep it's still an issue:
![image](https://user-images.githubusercontent.com/8895761/38495950-e232b956-3bfb-11e8-893e-d12c42422fe4.png)

It's not a big issue, though. The workaround is to unmerge the models and doing a merge on all at once.
