### ISSUE TITLE
Where is macos interface ?

### ISSUE THREAD

**Issue by mikcura** [Ultimaker/Cura#3742]
MacOS 10.12.6 and 10.13.4  - Cura 3.3.1 

All file requester are "unix like"

Is it a bug or a new feature ?

![capture d ecran 2018-04-27 a 15 04 15](https://user-images.githubusercontent.com/38787449/39364064-e2d25c2e-4a2c-11e8-9083-28773530a951.png)

Before (3.2.1)
![capture_d ecran_2018-04-27_a_15_09_31](https://user-images.githubusercontent.com/38787449/39364134-2df83c14-4a2d-11e8-816c-68628ab2dc9a.jpg)

**Comment by fieldOfView** [comment]
It is neither a bug or a feature; it is a workaround for a bug between Qt and OSX that caused double extensions not to work (eg .curaproject.3mf)

**Comment by ianpaschal** [comment]
@fieldOfView is correct. I know it's ugly looking but there was no other option. 😢
