### ISSUE TITLE
[3.3.1] without filling in

### ISSUE THREAD

**Issue by PabloSica** [Ultimaker/Cura#3745]
I updated the Cure this week to 3.3.1 and now it does not add any padding to any file.
I use MacOs and Printer Graber i3

**Comment by ianpaschal** [comment]
Please fill out the issue template including screen shots and logs or this issue will be closed.

**Comment by Ghostkeeper** [comment]
Should Cura add padding...? Maybe you meant infill? Did you accidentally hide infill from layer view? Or maybe you set the infill line distance or infill density to something weird? We have no built-in profile for Graber i3 so we can't help you much for the rest.
