### ISSUE TITLE
lil bug: print times don't fit

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#375]
Not a big issue, but long print times can overlap with the materials info:
![cura_long_print_time](https://cloud.githubusercontent.com/assets/8895761/9791167/0571f642-57da-11e5-820b-ff9a42d58b0d.png)

**Comment by BagelOrb** [comment]
Moreover, I don't really like the format. I would rather see

1d 22h 11m

or

82h 11m

problems now:
- zero in front
- *d*ays have different format style than *h*ours and *m*inutes
- string can be too long for its space

**Comment by BagelOrb** [comment]
another problem: the unit for time and length are both 'm' 

I think minutes should be abbreviated as 'min'.

**Comment by Ghostkeeper** [comment]
Please do retain the number of days. It's important to the common use case of people that make models that take several days to print.

That said, I agree that the "22:11 h:m" part is a bit strange.

**Comment by nallath** [comment]
Fixed for 15.09.82
