### ISSUE TITLE
[3.3.1] layer view slider missing and layer selections don't work

### ISSUE THREAD

**Issue by dmsulliva** [Ultimaker/Cura#3755]
![screenshot from 2018-04-30 18-22-51](https://user-images.githubusercontent.com/38870589/39454980-c83c75c4-4ca3-11e8-83b8-4b8c74a2131f.png)
**Application Version**
3.3.1

**Platform**
Linux

**Printer**
Tevo Tarantula

**Steps to Reproduce**
I have only been able to see the layer view slider once after I clicked one of the view cubes, but I have not been able to recreate since.  The layer selections did work this one time as well.  

**Actual Results**
It normally just shows the dark grey model

**Expected results**
I expect it to work as well as the other versions

**Additional Information**
none

**Comment by fieldOfView** [comment]
Press “prepare” in the lower right corner, or go into the General preferences and turn automatic slicing back on.
