### ISSUE TITLE
Extruder keep continue to pass printed higher level support layer. 

### ISSUE THREAD

**Issue by wizeiot** [Ultimaker/Cura#3757]
**Application Version**
3.3.1

**Platform**
Mac OS

**Printer**
Creality CR-10S

**Steps to Reproduce**
You can check with this file. https://www.thingiverse.com/thing:2793110
"Bracket_stock_stepper_pos._with_CR10_marking.stl". When printed 25% or more, printer head passing already printed higher support layer with click sound. 

**Actual Results**
It makes keep hot end and support crash.

**Expected results**
It should not pass higher level.

**Additional Information**

**Comment by BagelOrb** [comment]
The higher level is caused by oozing, it's not in the gcode. Try enabling Z Hop.

**Comment by wizeiot** [comment]
I will try. Than this issue is closed.
