### ISSUE TITLE
Bug: [ Delete ] deletes wrong objects

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#376]
Pressing [delete] deletes the wrong object.

First I had it deleting the other object (group), while something else was selected.
Then I got it to delete the right thing again.
Now it's not deleting anything anymore.

Please try to replicate any such bug by playing around.

Close this issue if you cannot replicate it after playing around for  quite a while.

**Comment by nallath** [comment]
I've not been able to reproduce this. I did make quite a bit of changes in how grouping is handled, so i might have accidently fixed this.

**Comment by BagelOrb** [comment]
This is still a problem.

I now did these steps twice and the problem reoccured.

Steps:
-Load model
-Load model 2
-Merge models
-Load model
-left click on last loaded model
- press [delete]
- watch wrong model get deleted

**Comment by BagelOrb** [comment]
just before pressing delete:
![cura_delete_bug](https://cloud.githubusercontent.com/assets/8895761/10660394/fd1c92e8-78a6-11e5-8ed5-b38ac96a7628.png)

**Comment by BagelOrb** [comment]
Cannot reproduce
