### ISSUE TITLE
[3.3.1] Shortcuts and file order are not saved in file picker in ubuntu

### ISSUE THREAD

**Issue by guysoft** [Ultimaker/Cura#3763]
**Application Version**
3.3.1
Did not work in 3.2.1 neither.

**Platform**
Ubuntu 17.10

**Printer**
Rigidbot / Pursa

**Steps to Reproduce**
1. Open a file picker to load an STL
2. drag a folder to the "look in tab"
3. Folder is saved, and will be saved when you open again
4. close Cura, and open it again

**Actual Results**
* No shorcuts are visable

**Expected results**
* Shortcut should be saved

**Additional Information**
Order by date, name of size is also not saved.
Here is what I am talking about
![spectacle zu2166](https://user-images.githubusercontent.com/325670/39472997-3c063f2e-4d55-11e8-9d94-2af403deef07.png)

**Comment by guysoft** [comment]
Any pointers in the code to what is causing this?

**Comment by jackha** [comment]
This is the native file dialog, I don't exactly know what's happening there. Can you bookmark the folder outside Cura and see if that works?

**Comment by guysoft** [comment]
@jackha Ok, did a little digging and I see you use Pyqt5. So I opened the example in their docks for a file picker:
https://pythonspot.com/pyqt5-file-dialog/

The problem is that the state of the dialog is not saved.
I can't seem to figure out myself what to do (swamped).

But its has to do with using ``from PyQt5.QtCore import QSettings`` to save the state of the dialog and restoring it. I can't seem to find a good bit of code to do that for the example above.

**Comment by jackha** [comment]
It seems like a problem in Ubuntu?
I've discussed it in the team and we're not going to fix this. So closing. Thanks for the effort though!

**Comment by guysoft** [comment]
Can you at least point me where this happens? I can PR.
Its making me not use Cura because It means any file pick takes me a long time.

**Comment by jackha** [comment]
Look for FileDialog in Cura.qml:
https://github.com/Ultimaker/Cura/blob/master/resources/qml/Cura.qml

It's a qt FileDialog object that opens the native open file dialog:
http://doc.qt.io/qt-5/qfiledialog.html

Thanks for having a look.
Maybe some workaround may work in the mean while? Make a symlink in your base folder?

**Comment by AdronTech** [comment]
Is there any progress? This bug is still present.

**Comment by Ghostkeeper** [comment]
Indeed, it still exists, but we've closed this because the user base for this feature is too small for the difficulty of fixing it. QML doesn't give us an interface to save or restore these as far as we've found.
