### ISSUE TITLE
[3.3.1] Post processing filament change, changes filament at the wrong layer

### ISSUE THREAD

**Issue by CPS-3** [Ultimaker/Cura#3775]
**Application Version**
3.3.1 

**Platform**
W10 

**Printer**
Creality CR10S-S4 

**Steps to Reproduce**
 filament change with a print, in my case, @ layer18 - text on a print... print is black and text should be white 

**Actual Results**
filament change happens @ layer 16 

**Expected results**
filament change @ layer 18 

**Additional Information**

![image](https://user-images.githubusercontent.com/38820490/39658125-0f5fbf14-5010-11e8-8164-d8a027765a6e.png)

**Comment by dmsulliva** [comment]
Same thing happens for me with my Tarantula, it was supposed to stop at layer 12, but stopped at 9 instead

**Comment by diegopradogesto** [comment]
Yes, confirmed. I set the filament to change in layer 50 and instead the script set the change in layer 47:

`G0 X46.039 Y47.619`
`G0 X44.487 Y44.487`
`;TIME_ELAPSED:902.097665`
`;LAYER:47`
`G0 X44.487 Y44.487 Z4.8`
`M600 E30.00 L300.00 ; Generated by FilamentChange plugin`
`;TYPE:FILL`
`G1 F3600 X46.024 Y46.024 E149.4953`
`G1 X46.103 Y46.103`
`G0 F7200 X46.176 Y47.606`

**Comment by diegopradogesto** [comment]
For developers' reference: CURA-5335

**Comment by CPS-3** [comment]
@diegopradogesto thank you for confirming

**Comment by djunisol** [comment]
yup same as CPS-3

**Comment by southsidebrewer** [comment]
I have this exact same issue. I have to manually set any filament changes now. I am pretty sure this is a new issue with the latest release, but I do not know for sure.

**Comment by AbeFM** [comment]
Every time I use this plug in I did test print columns to figure out what really happens.

Also the retract sometimes tries to *feed* several mm of material through nozzle at high speed.

Every single wrong in the macro meds to be tested each time to use safely. By adding or subtracting an offset, negating inputs, etc, it works.

**Comment by CPS-3** [comment]
Is anybody working on this yet?

**Comment by diegopradogesto** [comment]
It is in the planning.

**Comment by CPS-3** [comment]
Ok thank you for the heads up

**Comment by jackha** [comment]
Fixed in master. Unfortunately it just didn't make it to 3.4, so it's in the release after.

**Comment by diegopradogesto** [comment]
I thought that it is not dangerous and I just add it to the next 3.4 RC.

**Comment by uwezi** [comment]
is the problem back in 3.6.0? It appears that the pause is inserted randomly at +/- 1 layers from the desired position

`;TIME_ELAPSED:1440.249614
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current layer: 27
M83
G1 F1500 E-15
G1 F300 Z6.4
G1 F9000 X190 Y190
G1 F300 Z15
M104 S150; standby temperature
M0;Do the actual pause
M109 S210; resume temperature
G1 F1500 E15
G1 F199.998 E3
G1 F1500 E-15
G1 F300 Z6.4
G1 F9000 X96.636 Y86.693
G1 F1500 E15
G1 F9000
M82
G92 E1608.46202
;LAYER:26
;MESH:Uwe Zimmermann.stl
G0 X96.636 Y86.693 Z5.4
;TYPE:WALL-OUTER
G1 F2100 E1608.46202`

**Comment by Ghostkeeper** [comment]
Note that the `;LAYER` comment in the g-code is zero-indexed while Cura's interface shows the layer indices as one-indexed. So you'd expect Cura to indicate the layer number as one higher than what it says in the g-code.

**Comment by abrenoch** [comment]
How is this still a problem?

![image](https://user-images.githubusercontent.com/2146139/107852284-e4dfbc00-6ddd-11eb-9fa5-e947711a0a57.png)

![image](https://user-images.githubusercontent.com/2146139/107852295-f0cb7e00-6ddd-11eb-867c-59a41d68f423.png)

With cura 4.8.0

**Comment by AbeFM** [comment]
The process for change-at-z is slice-check-iterate. It should be documented.

                  Thanks!
                          -Abe.
