### ISSUE TITLE
[3.3.1] Exporting blank .gcode files

### ISSUE THREAD

**Issue by Joshua-The-Eagle** [Ultimaker/Cura#3779]
Whenever i try to open a .gcode file from cura in another application it is totally blank. My printer wont read the files either, as it just restarts when I try to print the file. any clue on how to fix this? im using cura 3.3.1 and my printer is a tevo tarantula (part of Rep-Rap)

**Comment by smartavionics** [comment]
Hello, please fill out the info required in the issue template and it would be very helpful if you could attach one of your gcode files to this issue and even better would be the .3mf file.

**Comment by jackha** [comment]
No reply in a month, let's close it.

**Comment by Ghostkeeper** [comment]
What application were you using to open the .gcode files from Cura?
