### ISSUE TITLE
[3.3.1] No retractions when first layer is printed

### ISSUE THREAD

**Issue by SorenBNielsen** [Ultimaker/Cura#3782]
**Application Version**
Cura 3.3.1

**Platform**
All

**Printer**
FLXPrint233

**Steps to Reproduce**
Just start a print of a model and the first layer is devastating the print.

**Comment by smartavionics** [comment]
It would be very helpful if you code post either the gcode (zip or change suffix to .txt) or even better the .3mf file (add .zip suffix). Thanks.

**Comment by ianpaschal** [comment]
> The first layer is devastating the print.

Like, emotionally?

Please upload the project file in question (so we can diagnose not only the gcode but also the printer definition, etc.) otherwise there's not much we can do.

**Comment by SorenBNielsen** [comment]
Ok, right, sorry for the lack of files. 
Here is a picture of the problem, where oozing is devastating the top layer of a display. 
![oozing first layer](https://user-images.githubusercontent.com/39032923/39695990-9eb485e0-51ec-11e8-8d86-b6795bdbd2ef.jpg)

I am attaching the project file and the G-code file here. 

[F_DisplayTop_180406C.curaproject.zip](https://github.com/Ultimaker/Cura/files/1979405/F_DisplayTop_180406C.curaproject.zip)
[F_DisplayTopx1_180406C_02_0912_3H.zip](https://github.com/Ultimaker/Cura/files/1979407/F_DisplayTopx1_180406C_02_0912_3H.zip)

**Comment by SorenBNielsen** [comment]
Sorre, I think that I closed this issue, but it is still open.

**Comment by smartavionics** [comment]
I tried loading your project but my Cura stopped because it doesn't have a definition for the printer you use.

**Comment by SorenBNielsen** [comment]
I have attached the .stl file here, so you can verify that there is oozing in the first layer. 
[DisplayTop_180406C.zip](https://github.com/Ultimaker/Cura/files/1982839/DisplayTop_180406C.zip)
I have attached the Cura definitions for the printer, material and quality here. 
[CuraSetup_180508.zip](https://github.com/Ultimaker/Cura/files/1982875/CuraSetup_180508.zip)

**Comment by smartavionics** [comment]
Sorry, those definitions are not compatible with my Cura version and I still cannot load your project - it's not your fault.

Looking at your gcode example, it seems to me that you do not have retractions enabled.

**Comment by SorenBNielsen** [comment]
This is the settings used, so it seems to me that retractions are enabled: 
![2018-05-08 10_40_24-ultimaker cura](https://user-images.githubusercontent.com/39032923/39747012-5e54c3fa-52ac-11e8-8b32-f103e70c6afe.jpg)

**Comment by SorenBNielsen** [comment]
It is only in the first layer that the problem shows up. There are no problem in the next layers, where many retractions are performed.

**Comment by smartavionics** [comment]
Set combing to "no skin".

**Comment by SorenBNielsen** [comment]
THANK YOU ! That did the trick. I am attaching the first layer that is now printed perfectly. 
![img_2636 2](https://user-images.githubusercontent.com/39032923/39749749-c454aaec-52b3-11e8-9718-ddd7649e3eea.JPG)

**Comment by padcom** [comment]
Thanks for the info! My prints look a lot better now! Print longer (I don't really care about that) but the quality is just AWESOME by comparison!

**Comment by Exi666** [comment]
thanks, I had the same problem too!

**Comment by Jaggana69** [comment]
> Set combing to "no skin".

Thx a lot!!
