### ISSUE TITLE
Delete all objects warning

### ISSUE THREAD

**Issue by hezhao** [Ultimaker/Cura#379]
There is no warning for deleting all objects after right clicking on the view window, it's quit dangerous as someone can accidentally delete all objects after carefully placing them on the platform.

![screen shot 2015-09-10 at 11 10 25 am](https://cloud.githubusercontent.com/assets/497136/9796745/8f24cf78-57ac-11e5-9c09-de4d8eddd7ba.png)

**Comment by nallath** [comment]
The screenshot you posted is of the old Cura. The new cura doesn't have this option either.

**Comment by awhiemstra** [comment]
Well "clear platform" removes all objects from the platform which basically does the same. However, since we have undo support in the new Cura this should be undoable and not be an issue.
