### ISSUE TITLE
[3.3.1] Option Mold (Special Modes) works only for extruder 1

### ISSUE THREAD

**Issue by tthurow** [Ultimaker/Cura#3791]
**Application Version**
Cura 3.3.1

**Platform**
Windows 10 x64

**Printer**
Ultimaker 3

**Steps to Reproduce**

1. Load a model and select Special Modes -> Mold. CURA generate a mold model.

![extruder_1](https://user-images.githubusercontent.com/6584969/39760109-c984a4c4-52d4-11e8-8806-fc1716469964.png)

2. Selelct material from extruder 2 for the model. CURA generate a normal model. 

![extruder_2](https://user-images.githubusercontent.com/6584969/39760118-d4e1c39c-52d4-11e8-84c6-8b8b1bad4b17.png)

**Actual Results**
Only by extruder 1 option mold works.

**Expected results**
Option mold should be work on both extruders.

**Comment by Vandrasc** [comment]
Hi @tthurow, silly question, but did you enabled the mold option for the second extruder as well? As it is not a global setting it has to be manually enabled in the second extruder tab as well.

**Comment by Ghostkeeper** [comment]
I think that was the problem. I can't reproduce this bug in any case.

**Comment by tthurow** [comment]
Oh no, sorry for so long time ... yes, I repeat this and it was my mistake! So sorry!
