### ISSUE TITLE
[3.3.1] Print thumbnail image contains support blocker blocks!

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3797]
**Application Version**

3.3.1

**Platform**

Any

**Printer**

S5

**Steps to Reproduce**

Load model into Cura and add support blocks, send job to printer.

**Actual Results**

The support blocks are shown in the print thumbnail image.

**Expected results**

The support blocker blocks should not be in the image?

**Additional Information**

I am reporting this issue on behalf of another.

![img_20180510_081213566 2](https://user-images.githubusercontent.com/585618/39858786-81788d1a-542f-11e8-8736-b19e8bbd64b3.jpg)

**Comment by ianpaschal** [comment]
Oh dear.

**Comment by Vandrasc** [comment]
Ehm, @ianpaschal see CURA-5019, according to the comment this behavior is acceptable.

**Comment by smartavionics** [comment]
LOL, really? How can an image that shows the model encased in concrete be acceptable?

**Comment by smartavionics** [comment]
BTW, I notice that infill modifier meshes are also rendered in the image which, again, isn't that useful.

**Comment by fieldOfView** [comment]
The fix is very trivial in PreviewPass.py; non-printing meshes are already filtered, they should just not be rendered, or rendered transparently.

**Comment by ianpaschal** [comment]
@Vandrasc I actually don't see any comments there which say it's acceptable. I see that it's "Fixed" which is apparently is not.

**Comment by ianpaschal** [comment]
This is fixed so should be immediately visible in master and coming soon to 3.4 beta.
