### ISSUE TITLE
Cura 3.2.1 / 3.3.1 clash when I change to layer view using large(?) STL data.

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#3799]
**Application Version**

Cura 3.2.1 / 3.3.1

**Platform**

Windows 10 (Notebook : 4G, Desktop : 8G Memory)
Notebook : Core i5, Intel HD Graphics 4000, OpenGL 4 compatible mode(OpenGL 2)
Desktop : Core i5, Intel HD Graphics 4600, OpenGL 4

**Printer**

Raise3D N2 Plus Dual / Ultimaker S5 / ...

**Steps to Reproduce**

STL source(Dual Color Labrador) : https://www.thingiverse.com/thing:2738228

I used dual color stl file for dual extruder.  1st nozzle is used for PLA, 2nd nozzle is used for ABS. At print setup, check "Generate Support" and "Enable Prime Tower". And Scale up to 200%. Merge two models.
After Slice is OK, I changed view mode from "Solid view" to "Layer view"

**Actual Results**

At Process Layer 99%, Windows system(mouse, explorer,...) very slow down for a few minutes without reaching 100%. And when I use Notebook, cura is stopped. And some debugging dialog window opens and cura closes.

Or when I use desktop, layer view is OK, but Windows system, Cura(scale, move, mirror,...) are very slow.

**Expected results**

Layer view change done. Windows system is OK.

**Additional Information**

Slice is OK, so the slice engine seems to have no problems. But there seems to be a problem with the simulation view plugin or pyqt, opengl, numpy???

cura log files : [cura.zip](https://github.com/Ultimaker/Cura/files/1993869/cura.zip)

Event Viewer Log:
System 
  - Provider 
   [ Name]  Windows Error Reporting 
  - EventID 1001 
   [ Qualifiers]  0 
    Level 4 
    Task 0 
    Keywords 0x80000000000000 
   - TimeCreated 
   [ SystemTime]  2018-05-11T07:43:00.390903600Z 
    EventRecordID 6471 
    Channel Application 
    Computer xxx
    Security 
 - EventData 
   1173820095910229450 
   4 
   APPCRASH 
   0 
   Cura.exe 
   0.0.0.0 
   5a2fae1f 
   ig7icd64.dll 
   10.18.10.4653 
   58e7c0a3 
   c0000005 
   00000000000941e1 
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WEREAEB.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5015.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5061.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5091.tmp.txt

**Comment by ChrisTerBeke** [comment]
I don't see any errors in the logs, but it might simply be that your machine ran out of memory.

**Comment by Ghostkeeper** [comment]
Try switching to compatibility mode for layer view:

* Open Preferences.
* Tick "Force layer view compatibility mode (restart required).
* Restart Cura and load your model again.

I suspect that your GPU is running out of memory.

To fix that sort of thing, we'd have to apply compression to the vertex data. That's not easy to implement though. Or we'd have to leave out the normal vectors if the memory is not large enough, which might be more feasible...

**Comment by jackha** [comment]
When I look at the logs I first suspect you have to update your graphics card drivers. 

The graphics card reports it supports all kinds of stuff, but it also reports that it's OpenGL 4.0. It should be at least OpenGL4.1

    2018-05-02 17:29:49,242 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [92]: Initialized OpenGL subsystems.
    2018-05-02 17:29:49,245 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [93]: OpenGL Version:  4.0.0 - Build 10.18.10.4653
    2018-05-02 17:29:49,248 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [94]: OpenGL Vendor:   Intel
    2018-05-02 17:29:49,250 - DEBUG - [MainThread] UM.View.GL.OpenGL.__init__ [95]: OpenGL Renderer: Intel(R) HD Graphics 4000

**Comment by joonghochoe** [comment]
Thanks,
Just now, Cura works well in version 3.4.
My notebook HP Ultrabook is a 5 year old product. So lastest intel HD4000 driver version is 10.18.10.4885. And Cura is operated at 4.0 compatibility mode.
