### ISSUE TITLE
Fuzzy skin negates brim

### ISSUE THREAD

**Issue by ozfunghi** [Ultimaker/Cura#3807]
I think there should be an option to let fuzzy skin (the best cura feature since FOREVER) start on layer 2.

If you have a tricky model that needs to be printed with a brim, the brim will lose 80% of its efficiency when fuzzy skin is turned on, since the brim will start on the outside of the fuzzy skin wall.

![afbeelding](https://user-images.githubusercontent.com/19844189/39961715-9698f306-563c-11e8-9c52-39c1cbd13b02.png)

**Comment by BagelOrb** [comment]
Good point. This is a oneline fix. Will do it this evening. If not then please remind me ;)

**Comment by BagelOrb** [comment]
Fixed in 657609e74387349c5a163adf2fd4a2eaa05a9811

**Comment by fieldOfView** [comment]
Dude, that’s two lines, not one !
