### ISSUE TITLE
[3.3.1 and previous] Freezing on Setting/Profile Changes

### ISSUE THREAD

**Issue by wcj97** [Ultimaker/Cura#3809]
I've had an issue with Cura freezing for a while. It used to happen every once in awhile when changing print settings. I disabled auto-slice and that fixed the issue for awhile. Now, recently, I've started trying to use Cura to slice for my custom FDM printer, but the issues is back. Now Cura freezes any time I attempt to make setting changes to the printer profile in 'Manage Printers'. This is becoming incredibly frustrating because it's preventing me from using Cura as a slicer for my new printer. A bit ago I read that there is a bug in the grid.shader file that can cause this issue, and someone suggested replacing that file with a different one from GitHub. Others (having fairly similar problems) said this worked for them, but I was not able to replace the file (something about not having permission from the owner to make changes). Is anyone else having this issue? Can anyone help me find a way to resolve the problem?

Thanks!

**Application Version**
3.3.1 and all other 3.x.x iterations

**Platform**
Microsoft Windows 10 Pro
Version 10.0.16299 Build 16299

**Printer**
The problem occurs when slicing for any printer, but especially when I try to make setting or profile changes for my custom printer profile

**Additional Information**
I'm running Cura on an MSI WS-72 workstation. It runs all of my other CAD and manufacturing related software with absolutely no issues, but Cura freezes every time I try to use the program.

**Comment by ChrisTerBeke** [comment]
Please share a video of your situation. We're aware that setting changes can be slow on some machines, but it's super hard to debug without seeing the issues visually. Possibly also share the log files that Cura generates in the user data folder.

**Comment by ianpaschal** [comment]
Needs info; didn't get it.
