### ISSUE TITLE
15.09.81: Coast glitch

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#381]
Hi guys, just installed .81 today. So far much better!

I enabled "coasting" and left the default values. The posted code shows an occasional anomaly:

![image](https://cloud.githubusercontent.com/assets/12439543/9805760/72db8e3c-5802-11e5-89f6-5474be2cd66d.png)

**Comment by BagelOrb** [comment]
This seems like it's caused by the z alignment bug, which is the result of the fact that each layer starts on a vertex and slight differences cause the vertices of different layers not to be aligned.

**Comment by BagelOrb** [comment]
I'm more interested in why the skirt seems to penetrate the model. Can you maybe send me the model so that I can test on it to make it print better?

**Comment by CCS86** [comment]
Sorry for the delay. The skirt actually doesn't penetrate the model. There is just a very small contact patch and an immediate overhang. I'll post the model up.

**Comment by BagelOrb** [comment]
This doesn't seem like a bug per se, so I'm closing this.
