### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setOrigin'

### ISSUE THREAD

**Issue by cncpadawan** [Ultimaker/Cura#3810]
**Application Version**
Built from 3.3 source a few days ago

**Platform**
Windows 10.0.16299

**Printer**
N/A

**Steps to Reproduce**
Built from source

**Actual Results**
Crashes when starting

**Expected results**
Shouldn't Crash

**Additional Information**

I have built a version of Cura from the repository, and it crashes on start.  I have deleted the profile folders and ensured no version of Cura was still installed on the computer.  However, the splash screen will appear momentarily and then it crashes.  It provides the following info:

Qt Version: 5.8.0
PyQt version: 5.8.2
OpenGL: Not yet initialized

Error traceback:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "Console.py", line 24, in <module>
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\bin\cura_app.py", line 141, in <module>
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 687, in run
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 753, in runWithGUI
AttributeError: 'NoneType' object has no attribute 'setOrigin'

Logs:

Current thread 0x000044d0 (most recent call first):
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 364 in _logInfoWidget
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 214 in _createDialog
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 82 in __init__
  File "C:\BuildAgent\work\6c1654b53e942396\build\inst\bin\cura_app.py", line 101 in exceptHook

Now, the location/path being mentioned is the build directory (I have TeamCity set up to do a build when the git repo is updated), so clearly the log files won't exist in that location, and that path doesn't even exist on the system.  

Any suggestions on how to start troubleshooting this?  The environment had been successful at building an earlier version of 3.x.

**Comment by cncpadawan** [comment]
I should also note that in the configuration folder, the only 2 folders that get created are plugins and set_visibility, which are empty folders.

**Comment by cncpadawan** [comment]
Another note - the code being pulled is still the current from the 3.3 branches for cura and curaengine.

**Comment by smartavionics** [comment]
Hi, I also build from source and sometimes I have to also delete the cura cache folder. On Linux it is located at ~/.cache/cura but I don't know where it is on other systems, sorry.

**Comment by cncpadawan** [comment]
Hello smartavionics, 

Thanks for the tip!  Hmmm..  The build server should be pulling and building everything clean (except the build environment) so in theory it should be clean every time.  Do you think this is something to do with the way it was built?.

**Comment by smartavionics** [comment]
Hi, the cache I am referring to is used by cura when it runs not during the build. I don't know much about how the front-end python code works but I think it holds binary versions of the various profiles and configuration data and it sometimes gets out of sync with the text versions.

**Comment by cncpadawan** [comment]
Ah, ok... I think you may be thinking of the folder created in AppData?  I did delete that, and I deleted all folders in Program Files related to Cura (it left some remnants). 

I just tried creating a Hyper-V VM and installing it in there.. that didn't go so well (it blew up, no OpenGL support), so I'll try a laptop that I have never installed Cura onto before and see what I get there.

**Comment by smartavionics** [comment]
OK, good luck!

**Comment by cncpadawan** [comment]
Thanks!  But... same issue.  Same errors.  Also, it seems the error dialog doesn't like 4k monitors that well... lol.

So it seems to be something in the way my system is building it.

**Comment by cncpadawan** [comment]
Anyone have any other thoughts on this?

**Comment by cncpadawan** [comment]
No other thoughts or ideas on this?  Nobody else is running into this when building?

**Comment by cncpadawan** [comment]
I'm the only one seeing this, or has seen this?

**Comment by diegopradogesto** [comment]
If you are running from source you should be able to do your own research on what is happening because it can be related with your own environment. If you go exactly to the point where the error points to you, it's line 753 of the file CuraApplication.py, in the function runWithGUI. The error says `AttributeError: 'NoneType' object has no attribute 'setOrigin'` that in this case means the `camera_tool` was not correctly initialized since it's still `None`. Then I encourage you to check in the logs whether the `CameraTool` plugin was loaded or not. You should see something like **`Loaded plugin CameraTool`**. If you see something different, then you need to start debugging from there.

**Comment by cncpadawan** [comment]
Diegopradogesto, thanks for the info!  The problem is there ARE no logs created for me to see what loaded and what didn't load.  I understand it could have something to do with the build environment.. but since it has worked fine with 2.x, I'm trying to understand what would have changed, i.e. narrow the issue down.

**Comment by cncpadawan** [comment]
Well, got it figured out.  The issue was the build environment.  Apparently there were some undocumented changes to the build environment requirements.  Rebuilt the build environments (for both Windows and Mac, both have exactly the same issue) and the problem is gone.

**Comment by diegopradogesto** [comment]
Oh, good to here that you found the problem. You said that there are some undocumented changes in the requirements. Can you tell me which ones so we can update the documentation properly?

**Comment by cncpadawan** [comment]
Unfortunately, I can't say for certain.  I rebuilt the build environment from the environment build github.  I am guessing something changed in there but I can't say for certain what it was.  The last time I built the build environments, it was in the 2.x era.
