### ISSUE TITLE
First save of project doesn't append .curaproject.3mf to suggested file name

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3812]
**Application Version**

3.3.1

**Platform**

Linux

**Printer**

Kossel Mini (or any other as far as I can tell)

**Steps to Reproduce**

Start cura afresh, load a model, fiddle with settings, etc. and then save as a project.

**Actual Results**

File save dialog appears with the model name but no .curaproject.3mf suffix

**Expected results**

File save dialog should include the .curaproject.3mf suffix.

**Additional Information**

![screenshot_2018-05-14_12-49-34](https://user-images.githubusercontent.com/585618/39995843-7a92b478-5775-11e8-8a23-8d0ead93e2e8.png)

Slicing and then saving to file does show the .gcode extension (i.e. KMMB_wolf.gcode in my above example).

**Comment by Vandrasc** [comment]
Devs, see CURA-5368. 

Thank you, @smartavionics !

**Comment by LipuFei** [comment]
@smartavionics Fixed in master: 3a7a1dbc6d935b94e4c9b080259618f2f55551bf
