### ISSUE TITLE
Layer Not in correct Z height

### ISSUE THREAD

**Issue by Ritch2125** [Ultimaker/Cura#3815]
For some strange reason Cura placed a layer that should around 24mm at z=0.  See attached screen shots

At layer 171 all is fine
![image](https://user-images.githubusercontent.com/39283830/40028645-10e220ca-57ae-11e8-8eb7-b11d30b9ebaa.png)

layer 172, suddenly there is a new lines at the z=0 level

![image](https://user-images.githubusercontent.com/39283830/40028666-2fabdb90-57ae-11e8-83f8-6ea3e131cf46.png)

Finally at the next layer you can see the gap in the object
![image](https://user-images.githubusercontent.com/39283830/40028681-48f20868-57ae-11e8-9ee0-aa9cf0ce3d7b.png)

[TBW_Fan Mount  30mm Vertical - Fan Mount 30mm Vertical final.3mf.log](https://github.com/Ultimaker/Cura/files/2002942/TBW_Fan.Mount.30mm.Vertical.-.Fan.Mount.30mm.Vertical.final.3mf.log)

Version 3.3.1 on Windows 10.
Tevo BW

The 
[Fan Mount  30mm Vertical - Fan Mount 30mm Vertical9.stl.log](https://github.com/Ultimaker/Cura/files/2002953/Fan.Mount.30mm.Vertical.-.Fan.Mount.30mm.Vertical9.stl.log)

Any thoughts?

**Comment by fieldOfView** [comment]
I wonder if it is actually in the gcode like that, or a visualisation glitch in Layer View. Does the layer stay out of place like that if you save the gcode and load it back in?

**Comment by ChrisTerBeke** [comment]
Having the gcode would also help to debug this for the developers.

**Comment by smartavionics** [comment]
Yes, please post the gcode for that. Thanks.

**Comment by Ritch2125** [comment]
I didn't save the gcode.  But I will try and relod it tonight to get the
gcode.  I did try to switch layer heights to make the error go away but it
stayed.  Can the gcode be created from the FMF file?

**Comment by BagelOrb** [comment]
[reminder] can you reproduce it?

Could you please share both the gcode and the project file? (Put them in a .zip)

**Comment by Ritch2125** [comment]
Tim, I loaded the fmf fille already.  I think the stl as well.  They both
were remained with a .log on the end.  I did not save the gcode when I
spotted the error.  I should of. Time was tight last night and after a
couple of attempts I could not reproduce the error to get the code. I will
try again tonight.

**Comment by Ritch2125** [comment]
I tried for 40 mins to recreate the problem but couldn't.  I will watch for this in the future and make sure I save the gcode next time.

**Comment by smartavionics** [comment]
OK, thanks for trying. If it happens again, please save the gcode and attach to this issue. Cheers!

**Comment by Ghostkeeper** [comment]
I've seen this problem once in a while too. I think it's some kind of data corruption inside the socket or a data race from CuraEngine. It happens very rarely, maybe once a month (with my 40 hour per week job). This bug has been in there for at least 2 years.
