### ISSUE TITLE
Use different layer height for infill and for perimeter to speed up the prints?

### ISSUE THREAD

**Issue by Harvie** [Ultimaker/Cura#3816]
I think we can use bigger layer height for infill, than for perimeter to speed up the prints, while preserving detailed surface. Eg.: here's example of infil using 300% layer height of perimeter:

![image](https://user-images.githubusercontent.com/276504/40053094-48c4e36e-5840-11e8-9fe1-679f59a4b923.png)

At first we can print 3 layers of perimeter and then add one thick layer of infill to the inside. Given that these 3 layers of perimeter always have inner alignment to match the thick layer of infill.

Maybe this will even increase overall toughness of the infill.

What do you think?

**Comment by ChrisTerBeke** [comment]
Have a look at the "infill layer thickness" option.
