### ISSUE TITLE
Brim only on Prime Tower

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#3818]
Problem: The low area contact of the Prime Tower cause tower unstick. 
Solution: The possibility to choose Brim only for the Prime Tower.

**Comment by cmatthes** [comment]
I think it would also be useful to have an option for a multi layer brim. Creating an even better base.

**Comment by cmatthes** [comment]
A raft would probably work too. 
I would choose a brim over a raft because a brim is way simpler for the user as it requires far less settings to be set. 

Enable Prime Tower Brim   [ X ]    
   - Brim width                     [     ]
   - Brim Thickness             [     ]
      - Brim Layers                [     ]

**Comment by ChrisTerBeke** [comment]
Related to https://github.com/Ultimaker/Cura/issues/3824.

**Comment by jackha** [comment]
Devs: see CURA-5487

**Comment by printingotb** [comment]
I also think a brim on supports only will be really useful.
What would be even better is if we were also able to print a solid initial support layer against the buildplate.

**Comment by AbeFM** [comment]
A raft only for supports is what I really want.

Dense layer, raft, brim, all these ideas point in one direction: support
adhesion is important to people who use soluble supports.

Perhaps on a case by case basis you can dismiss it, but ten topics that are
all variations on a theme says that this is something there is interest in.

                  Thanks!
                          -Abe.

**Comment by BagelOrb** [comment]
Cura 4.3 has Prime Tower Brim feature. This feature is implemented.
![image](https://user-images.githubusercontent.com/8895761/67750580-c5c5eb00-fa2f-11e9-8d60-420191041b5a.png)
