### ISSUE TITLE
Moves from printer settings don't show in G-code preview

### ISSUE THREAD

**Issue by AbeFM** [Ultimaker/Cura#3819]
![image](https://user-images.githubusercontent.com/42385/40088504-1b514636-585c-11e8-9254-93acb2344c62.png)

**Application Version**
3.3.1

**Platform**
win10

**Printer**
Custom CR10/Dual Ext

**Steps to Reproduce**
"Extruder End G-Code" in machine settings set to:
`G1 X150 Y280`
on both tools. Slice File, Layer View

**Actual Results**
![image](https://user-images.githubusercontent.com/42385/40088546-4014d488-585c-11e8-9289-9596cd310610.png)

**Expected results**
Toolpath should show going beyond the tower?

**Additional Information**
Not terribly certain this is a bug.

**Comment by BagelOrb** [comment]
Yes this is a bug. ...or a feature.

We never implemented interpreting the gcode. The layer view is from what Cura thinks it is doing and Cura doesn't look inside the user provided gcode settings.

**Comment by BagelOrb** [comment]
However, it is not a problem for Ultimaker printers, so Ultimaker is not going to spend time on this.

**Comment by fieldOfView** [comment]
> Cura doesn't look inside the user provided gcode settings.

The same is true for moves in the "global" start and end gcode

**Comment by Ghostkeeper** [comment]
This issue is a duplicate of https://github.com/Ultimaker/Cura/issues/3128 .

You can still see the start and end g-code by saving the g-code to file and re-loading that g-code into Cura.
