### ISSUE TITLE
Feature Request - Dashboard function for print metrics, i.e. metrics on # of prints, filament, username, etc.

### ISSUE THREAD

**Issue by jkennard** [Ultimaker/Cura#3821]
We wish there was a way that Cura Connect could aggregate data from the printers in the system so that we could start getting metrics on our printing. We would like to see how many prints we are doing, the filaments we are using, username, print settings, etc. I would love to have a way to quantify and analyze all this for our group of printers in Cura Connect. Is this in development for Cura Connect? 

**Application Version**
3.3.1

**Platform**
Windows 10

**Printer**
3 Extended

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ChrisTerBeke** [comment]
This won't come to Cura, Cura Connect might have something like this in the future but I can't comment on details about that development here.
