### ISSUE TITLE
Show Configuration Folder - Not Working 

### ISSUE THREAD

**Issue by goks95** [Ultimaker/Cura#3833]
I have installed the 3.2.1 and the latest one as well. And I wanted to load my 3dprinter json file into the configuration folder and the "show the configuration folder" under "Help" tab doesnt seem to be working. 
How can I fix this? Thanks

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by goks95** [comment]
Yeah.

**Comment by ChrisTerBeke** [comment]
Mm this is hard to debug without the logs, which are in the configuration/data folder. You can find details on finding the folder manually here: https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations. Please share the logs in that folder.

**Comment by goks95** [comment]
Got it fixed. Thanks!
