### ISSUE TITLE
[3.3.1] Project Summary Box Problem

### ISSUE THREAD

**Issue by fatalelieberi** [Ultimaker/Cura#3835]
**Application Version**
3.3.1

**Platform**
Windows 10

**Printer**
Tevo Tornado - Custom FDM
[MyPrinter.curaproject.zip](https://github.com/Ultimaker/Cura/files/2019056/MyPrinter.curaproject.zip)

**Steps to Reproduce**
1. Open menu File -> Save Project

**Actual Results**
Unclear writings inside the Project Summary
![summary of cura project](https://user-images.githubusercontent.com/19477587/40264213-ff179e80-5b48-11e8-87a3-cd022f1038e4.png)

**Comment by ianpaschal** [comment]
Indeed. No doubt this is caused by the dialog having a fixed size dialog which can't fit 8 extruders. Simple fix is putting the summary in a small scroll area.

**Comment by ianpaschal** [comment]
Internal ticket created, devs see CURA-5385.

**Comment by ianpaschal** [comment]
We've fixed this; will be in 3.4 released in June.
