### ISSUE TITLE
[3.3.1] Bridging feature causes brittle layers

### ISSUE THREAD

**Issue by b14ckyy** [Ultimaker/Cura#3839]
**Application Version**
Cura 3.3.1

**Platform**
Windows 10 Pro x64

**Printer**
Anet A8 - Modified with e3D v6 Hotend, Bowden Extruder,  

**Steps to Reproduce**
Print an object with thin pillars and bridges between them. Added an STL Model I designed where it is easy to reproduce, also the gcode and cura Project file.

[CFDMP_Gimbal Camera Mount v9.curaproject.zip](https://github.com/Ultimaker/Cura/files/2020678/CFDMP_Gimbal.Camera.Mount.v9.curaproject.zip)
[CFDMP_Gimbal Camera Mount v9.zip](https://github.com/Ultimaker/Cura/files/2020679/CFDMP_Gimbal.Camera.Mount.v9.zip)
[Gimbal Camera Mount v9.zip](https://github.com/Ultimaker/Cura/files/2020680/Gimbal.Camera.Mount.v9.zip)

**Actual Results**
the layer, where the bridging happens seems to have full reduced Extrusion to 50%. So the outer wall has one layer with many small holes in it. This causes to have weak Points in layers. 

**Expected results**
Normal layer Extrusion before and after the Bridge.

**Additional Information**
Picture of print:

![dsc_0506_li](https://user-images.githubusercontent.com/33039058/40283707-d83eeecc-5c82-11e8-995f-1f04332406e6.jpg)

**Comment by jackha** [comment]
@b14ckyy:
- Does the lag of filament flow start about 3 mm before the bridge? Or is it still the whole layer?

- What results do you get of you turn bridging off? I'm mostly wondering if you still have the under extrusion.

**Comment by smartavionics** [comment]
My experiments have shown that step changes in extruder rate such as are used when the bridge segment is printed with a different flow or speed to the normal wall have a big impact on wall visual quality. So if you want to avoid these underextrusions, you need to not change the speed or flow for the bridge wall segments compared to the normal settings. If your printer/filament/settings combination cannot print the bridge walls successfully using the normal speed/flow then you have the problem to decide whether you want to preserve the visual quality of the non-bridge segments of the wall line or you want the bridge segments of the wall line to be better. It's a tradeoff.

**Comment by jackha** [comment]
Let's see what @b14ckyy experiences the same. Then we may be able to close this issue.

**Comment by b14ckyy** [comment]
Hi. My Printer was not running since a few days. I'll search a nice test model to try different Settings. I'll report back asap

**Comment by Ghostkeeper** [comment]
Any luck?

**Comment by diegopradogesto** [comment]
Long time waiting for a response. Feel free to reopen if this still reproduces for you.
