### ISSUE TITLE
*.3mf's may load in with dead volume

### ISSUE THREAD

**Issue by AbeFM** [Ultimaker/Cura#3847]
Repost from: https://github.com/Ultimaker/CuraEngine/issues/778
Reposted from https://community.ultimaker.com/topic/22569-bed-not-detected-right-in-slicingpositioning/

**Application Version**
2.? - 3.3.1

**Platform**
win10

**Display Driver**
NVidia 388.73

**Steps to Reproduce**
Load a *.3mf file. (Might happen on solidworks import, too, unsure)

**Actual Results**
SOME models, (for example: [DHookP110_110_120.zip] (https://github.com/Ultimaker/CuraEngine/files/2019602/DHookP110_110_120.zip) ) when loaded seem to refrence an invisible "origin" and CURA treats the object as if it were a solid extended body. In fact, in solid body mode, the limits are shown, and in many cases I not only cannot get the part onto the bed without manually positioning to a few microns, but look at how it is treated:
![image](https://user-images.githubusercontent.com/42385/40270407-d4345f52-5b41-11e8-9d28-0903ff9355fa.png)
As the object, and it's dead volume, won't fit on the bed, I can't even slice this hook.

**Expected results**
Object's boundaries are determined from triangles in body. Save item as .stl and it opens and behaves normally

**Additional Information**
I've made complaints on the forums in the past about this behavior, but only noticed it was with .3mf files recently. In my other posting, a user found my model loaded ok. If this is broadly the case, I'd like to know why I'm having issues.

**Comment by ChrisTerBeke** [comment]
It seems the 3MF file has been 'grouped' and exported that way. Some programs (like MS 3D Builder) do that. You can right-click on the part to ungroup it and then auto center the object. In short: the model was exported by the design software incorrectly.

**Comment by ChrisTerBeke** [comment]
If a 3MF is constructed in this particular way, Cura has to read it like this, as 3MF is a standard so we can't just make up behaviour for this. It's more an issue with the modelling software is a 3MF was exported like this in the first place.

**Comment by Ghostkeeper** [comment]
We had a bug in Cura at some point that the coordinate origin (0, 0, 0) was always included in the bounding box in 3MF. Maybe that is back. The 3MF file still loads wrong in current Cura.

In other words, it is correct that Cura loads the 3MF file as a group. It is not correct that the bounding box is not close to the model.

**Comment by AbeFM** [comment]
THAT sounds right to me. It reflects what I'm seeing.

                  Thanks!
                          -Abe.

**Comment by Ghostkeeper** [comment]
This is fixed for version 3.5!
