### ISSUE TITLE
[3.3.1] Unexpected huge retraction on tools change

### ISSUE THREAD

**Issue by Renha** [Ultimaker/Cura#3849]
**Application Version**

Cura 3.3.1

**Platform**

Windows 10

**Printer**

Custom Delta

**Steps to Reproduce**

Just slice attached project

**Actual Results**

Print fails because filament travels over 10 mm backwards, leaving hotend (almost) completely. Retractions configured to be 2 mm.

**Expected results**

Print not fails because filament not travels over 10 mm backwards, not leaving hotend (almost) completely.

**Additional Information**

GCODE lines starting from line 6777:
```
G1 F1200 E-16
T0
M109 S246
M104 T1 S256
G1 F1200 E14
G0 F7200 X16.111 Y-5.79 Z1.4
G0 X18.596 Y-1.995
M104 S256
;TYPE:SUPPORT
```

Also I don't get why temperature changed (there is M104 T0 S246 at line 6691), I've set up all tools temperatures to 256 exactly everywhere.
[renha.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2034395/renha.curaproject.3mf.zip)

**Comment by smartavionics** [comment]
This is the setting that is controlling the retraction amount, you need to set that to a suitably low value.

                "switch_extruder_retraction_amount":
                {
                    "label": "Nozzle Switch Retraction Distance",
                    "description": "The amount of retraction: Set at 0 for no retraction at all. This should generally be the same as the length of the heat zone.",
                    "type": "float",
                    "unit": "mm",
                    "enabled": "retraction_enable",
                    "default_value": 20,
                    "value": "machine_heat_zone_length",
                    "minimum_value_warning": "0",
                    "maximum_value_warning": "100",
                    "settable_per_mesh": false,
                    "settable_per_extruder": true
                },

**Comment by smartavionics** [comment]
Sorry, the above was from fdmprinter.def.json. Your actual project file contains this:

                "switch_extruder_retraction_amount": {
                    "value": "=machine_heat_zone_length", 
                    "type": "float", 
                    "settable_per_extruder": "True", 
                    "settable_per_mesh": "False", 
                    "enabled": "=retraction_enable", 
                    "maximum_value_warning": "=100", 
                    "minimum_value_warning": "=0", 
                    "label": "Nozzle Switch Retraction Distance", 
                    "default_value": "20", 
                    "children": {}, 
                    "description": "The amount of retraction: Set at 0 for no retraction at all. This should generally be the same as the length of the heat zone.", 
                    "unit": "mm"
                }

**Comment by Renha** [comment]
Wow thank you! Didn't know about that setting...
