### ISSUE TITLE
[3.3.1] Buttons are blank / icons not displayed

### ISSUE THREAD

**Issue by krebsd** [Ultimaker/Cura#3857]
**Application Version**
3.3.1

**Platform**
Windows 10 Pro x64
Intel Core i7-7700K
Nvidia GTX970

**Steps to Reproduce**
Open cura

**Actual Results**
Buttons are blank, icons are not shown
[Screenshot](https://user-images.githubusercontent.com/37480802/40579388-8381706e-6126-11e8-8489-de726325791a.PNG)

**Expected results**
Icons should be shown inside buttons

**Additional Information**

[cura.log](https://github.com/Ultimaker/Cura/files/2041875/cura.log)
Cura log shows QML Errors for svg images: e.g.
QML Image: Error decoding: file:///C:/Program Files/Ultimaker Cura 3.3/resources/themes/cura-light/images/logo.svg: Unsupported image format
svg files can be opened with Internet Explorer and are displayed correctly.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/issues/1722

The last couple of posts there have a solution (clearing a systemwide environment variable that shouldn’t have been set in the first place)
