### ISSUE TITLE
anycubic i3 Mega wird bei Programmstart nicht gefunden 

### ISSUE THREAD

**Issue by fbsln** [Ultimaker/Cura#3858]
**Application Version**
3.3.1

**Platform**
Windows10

**Printer**
ANYCUBIC I3 MEGA

**Steps to Reproduce**
On the right side, where two weeks ago it still showed the printer with the settings, there is nothing any more. It says "Compatibility Mode"??? I don't know wny :-(

**Actual Results**
I uninstalled Cura and deleted the rest via Regedit. After reinstallation, the problem remained :-(

??? Who can help ???

Thanks

**Comment by ChrisTerBeke** [comment]
English please.

**Comment by Ghostkeeper** [comment]
Translated this to English.

**Comment by Ghostkeeper** [comment]
If the entire side bar is gone, try pressing Ctrl+E to get it back. It is a toggle that you can press to get more screen space for your model.

If the side bar is there but is empty and white, I think you have a problem with rendering. We don't display "Compatibility mode" as separate text anywhere (only in the preferences menu regarding layer view). I think something from your computer is putting that there.

**Comment by jackha** [comment]
If it says compatibility mode out of nothing, it may have to do with your gpu. Did you install the newest video card drivers?

If you don't mind your old settings, you can also delete your config folder to see if that helps.

**Comment by Ghostkeeper** [comment]
I think we'll have to assume that Ctrl+E or updating video drivers fixed the problem then.
