### ISSUE TITLE
Makerbot Replicator 2 Noise

### ISSUE THREAD

**Issue by lopesff** [Ultimaker/Cura#3861]
**Application Version**
Ultimaker Cura 3.3.1

**Platform**
Windows 10

**Printer**
Makerbot Replicator 2

**Steps to Reproduce**

**Actual Results**
I´m trying to use CURA in my Makerbot Replicator 2 but, I can not. When I slice my part and create a x3g file I put sd card in my printer but doesn´t work.
My printer only make some noise and doesn´t start to print.
I can use makerware or S3D and I don´t have problems.
I select at CURA Makerbot and GCODE flavor I put Makerbot.
My makerbot not home axes neither start to print.

**Expected results**
 I would like to fix it.

**Additional Information**
I saw a youtube video with the same problem
https://www.youtube.com/watch?v=dtHib1chdoI

**Comment by ChrisTerBeke** [comment]
Cura does not officially support Makerbot printers. All support via plugin is purely based on community efforts. It would be best to contact the author of the relevant plugin for support.
