### ISSUE TITLE
3.3.1 - Initial Infill Path

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#3862]
**Application Version** - CURA 3.3.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Generate the gcode and in "Layer View" analyze the toolpath.

**Actual Results** - The path of the Infill starts far away from the last wall path extrude.

**Expected results** - Infill path extrude starts near as possible from the last wall extrude.

![screenshot_2](https://user-images.githubusercontent.com/12901952/40619719-128b3e8a-628e-11e8-9f39-530127696ee2.jpg)

**Comment by ChrisTerBeke** [comment]
My guess is that it selects a starting point that results in the largest single line to print the infill so no extra retractions are needed.

**Comment by smartavionics** [comment]
It's not possible from a single image to understand the ordering used but, in general, the infill writer tries to output "chains" of lines. Two line segments are chained if one starts very close (within um) of the other ending.  Having finished one chain it then finds the nearest start to another chain. It does not attempt to order the chains to minimise the overall distance travelled. If you post a project file, I can comment in more detail on your example.

**Comment by amagr0** [comment]
[cube50.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2047375/cube50.curaproject.3mf.zip)

**Comment by smartavionics** [comment]
Thanks for the project. I loaded it and without changing any settings got a result that doesn't look the same as your picture. All the infill layers look the same. The chains are being followed and the total amount of travel is small (2%).

![screenshot_2018-05-29_09-39-49](https://user-images.githubusercontent.com/585618/40647688-695b63ca-6324-11e8-92eb-d0c0735fb28b.png)

**Comment by dmitrygorbenko** [comment]
@smartavionics can you show where is the beginning of the first line on "infile" ? please, show us a start point in a way like @amagr0 did.

I have many concerns about the same problem -- Cura (3.3.1) does a lot of movements instead of printing. Maybe it's a 2%, like you wrote, but these movements don't make to much sense to me. Why not to start extruding as near as possible ? Why the nozzle moves to other side of the wall and continues printing there instead of continue printing right here next to the place where is has just stopped ?

**Comment by smartavionics** [comment]
Here is an image showing the first infill line, you can see that it is close to the corner where the walls start/finish.

![screenshot_2018-05-29_13-39-00](https://user-images.githubusercontent.com/585618/40659296-c665204e-6345-11e8-9d5f-420197da3684.png)

Cura 3.3.1 has a horrible bug in the combing that makes it travel "the long way round" although that doesn't appear to be the problem in the OP's image. There have been various other changes so perhaps it has been fixed for the next release?

**Comment by amagr0** [comment]
This is the same exact layer (276), and it's not starting as the previous image. 
![screenshot_2](https://user-images.githubusercontent.com/12901952/40663358-5f9347e6-6350-11e8-9d0b-2bba7ac3bc07.jpg)

**Comment by smartavionics** [comment]
Something must be different in the engine. I am using a derivative of the master branch so the change that has been made will probably be in 3.4 (along with the latest selection of bugs!)

**Comment by amagr0** [comment]
Ok, it's explained!
Is there already a release date for the 3.4 ?

**Comment by smartavionics** [comment]
Sorry, I don't know but I noticed today that 3.4 branches have appeared in the Cura repos so I guess there will be a beta available in a few weeks from now.

**Comment by amagr0** [comment]
It seems that was not solved in 3.4 beta.

![screenshot_4](https://user-images.githubusercontent.com/12901952/41034743-7b1870da-6982-11e8-9307-39b29662a9ea.jpg)

**Comment by smartavionics** [comment]
That's odd because it's solved in a 3.4 related release that I have here:

![screenshot_2018-06-06_13-10-28](https://user-images.githubusercontent.com/585618/41037367-10471370-698b-11e8-9ce0-dd059dd0d823.png)

**Comment by amagr0** [comment]
Can anyone else confirm this issue was solved on 3.4 beta?

**Comment by jackha** [comment]
In the current master, I see exactly what @smartavionics also sees. I hope it also does that for @amagr0 because otherwise we can't reproduce it and thus fix it.

![gh-3862-master](https://user-images.githubusercontent.com/1016604/42764271-7ddb105e-8915-11e8-8113-09aba34e07a7.png)
