### ISSUE TITLE
[3.3.1] After hit "Prepare" button nothing happens.

### ISSUE THREAD

**Issue by Kikerumbo** [Ultimaker/Cura#3871]
**Application Version**
Cura 3.3.1

**Platform**
Windows 10 x64

**Printer**
Ender 3 (Custom CR-10 profile)

[CCR10_Matek F405-Wing mount.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2058028/CCR10_Matek.F405-Wing.mount.curaproject.3mf.zip)

**Steps to Reproduce**
Hit "PREPARE" button

**Actual Results**
Nothing, it just shows the "Slicing" text, but the bar doesn't move. Waited for 2 hours and nothing happened

**Expected results**
Obtain a G-Code file to put in a SD card.

**Additional Information**
Tried putting the Cura folder in the exception list of the firewall/antivirus, executing Cura as administrator, reinstalling it. Looked for solutions for older versions.

Cura.exe process is running, but not using CPU. No new process when I try to slice.

[cura_CFG.zip](https://github.com/Ultimaker/Cura/files/2058079/cura_CFG.zip)
![cura_3 3 1](https://user-images.githubusercontent.com/39798064/40780791-f386ae4a-64d9-11e8-88b9-d04607b047a0.jpg)

Total noob in 3D printing. This is my first attempt. Surely I'm doing something wrong, but I can't figure what.

Thanks.

**Comment by diegopradogesto** [comment]
In my first attempt using 3.3.1 it slices correctly and instantly. I will take a look at the current configuration and I will come back to you.

**Comment by ChrisTerBeke** [comment]
I think this has been addressed several times before on GitHub. It mostly turned out to be a permission issue with CuraEngine on Windows. Try running Cura as administrator?

**Comment by Kikerumbo** [comment]
Thanks for your answers.

As told in my previous post, yes, I already tried to run Cura as administrator. Same behavior.

**Comment by ChrisTerBeke** [comment]
MM weird. I also tried to open your 3MF project but Cura (3.3.1) just won't open it...

**Comment by Kikerumbo** [comment]
I tried with different .stl files. Not one works. If I use other slicing software they seems to work just fine producing the G-code.

I suppose that when I hit the Prepare button CuraEngine.exe should start running, but I can only see the Cura.exe process in the task manager.

Any suggestion?

By the way, thanks for trying.

**Comment by ChrisTerBeke** [comment]
Best thing I can still think of is a permission issue. Maybe a complete re-install (maybe on another drive even?) could fix something. If not, you could try the 3.4 Beta which is due next week.

**Comment by diegopradogesto** [comment]
Probably is related with permissions as @ChrisTerBeke says. Maybe we can find something interesting in the logs. Can you provide the log file?

**Comment by Alesky07** [comment]
To share my experience,
My Cura installation is on an old computer, and after clicking on prepare button I have to wait several seconds (sometimes 20 seconds) until it start to slice.
I did not have this lag on a recent computer.

**Comment by diegopradogesto** [comment]
@Kikerumbo , are you still experiencing these problems? Have you tried with version 3.4? Is it maybe due to lagginess with your computer?

We need more info in order to address your issue.

**Comment by Kikerumbo** [comment]
I no longer use CURA.

I do not have any lag with other slicing software (i5@4.6Ghz, 16Gb RAM and SSD).

**Comment by diegopradogesto** [comment]
Ok, so... since nobody else is having this problem for now, I'll close this issue.
