### ISSUE TITLE
Support with own groundplane

### ISSUE THREAD

**Issue by BruderTack** [Ultimaker/Cura#3873]
Support should have an own closed groundplane separated from the main body for maximum build plate adhesion

**Comment by AbeFM** [comment]
There are maybe 5 other threads about exactly this.

It seems not to be a concern for the CURA team, but it seems significant to many of the users.

I feel this is a duplicate topic.

**Comment by Ghostkeeper** [comment]
Indeed, this looks like a duplicate of https://github.com/Ultimaker/Cura/issues/3759.
