### ISSUE TITLE
3.3.1 not start after pause

### ISSUE THREAD

**Issue by askmix** [Ultimaker/Cura#3885]
1. Сura 3.3.1 (ru language) do not start after pause, firmware marlin 1.1.8, win10 64bit. Сonstantly shows the temperature of the bed and hotend on 1 degree Celsius below the target. 2. With a quick double-click on the navigation buttons does not move a short distance (some twitch), with a single press movement is smooth. 3. heating does not always start after the part is re-printed. (v3.2.1)

**Comment by askmix** [comment]
mega 2560

**Comment by askmix** [comment]
request developers, You can do to CURA showed current stance and tier in texts, if perhaps visually. ability to view the exchange of messages with the printer in text

**Comment by ChrisTerBeke** [comment]
Please make separate issues for these different topics and and fill out the issue template for each of them. Like this we can't properly respond and track things.

**Comment by Ghostkeeper** [comment]
> 1. Сura 3.3.1 (ru language) do not start after pause, firmware marlin 1.1.8, win10 64bit. Сonstantly shows the temperature of the bed and hotend on 1 degree Celsius below the target. 2. With a quick double-click on the navigation buttons does not move a short distance (some twitch), with a single press movement is smooth.

I think this is more up to the printer than up to Cura. Cura just sends a command to the printer to heat up and wait until the temperature is reached. If the printer doesn't report that the temperature is reached, then Cura will keep waiting with sending more commands. For 2., Cura more or less immediately sends the command via USB upon pressing. It's up to the printer to execute it smoothly.

> 3. heating does not always start after the part is re-printed. (v3.2.1)

This one will be fixed for the upcoming release.
