### ISSUE TITLE
Sliced model covering up through-hole

### ISSUE THREAD

**Issue by slikk66** [Ultimaker/Cura#3888]
**Application Version**
3.3.1

**Platform**
Mac OS

**Printer**
Cr10s

**Steps to Reproduce**
slice this part: https://printabrick.org/bricks/55982

**Actual Results**
The center "cross" hole is covered up

**Expected results**
the center "cross" hole should be open all the way top to bottom

**Additional Information**
https://imgur.com/a/nygZS84
images of the sliced model

**Comment by smartavionics** [comment]
Freecad thinks the model is broken:

![screenshot_2018-06-05_08-04-57](https://user-images.githubusercontent.com/585618/40960318-3d6feef2-6897-11e8-88ca-76dbd959bfba.png)

**Comment by coreyfaure** [comment]
Confirmed to be the model, not Cura in this situation. https://www.reddit.com/r/3Dprinting/comments/8ondye/cura_weird_slicing_issue_covers_up_main_hole_in/

**Comment by smartavionics** [comment]
Hi, if you are happy it's not cura, please close the issue. Thanks.

**Comment by slikk66** [comment]
Seems to be the model, not cura.. closing!
