### ISSUE TITLE
dual extrusion going past home after material layer change

### ISSUE THREAD

**Issue by sofa-bear** [Ultimaker/Cura#3895]
![screenshot 55](https://user-images.githubusercontent.com/36248927/41007016-c3cbe0f8-691b-11e8-8adc-ac9b9110421c.png)
so using a custom printer in cura version 3.4    3.3.1   3.21   3.0.4 and 2.7 (they are all the ones I have tested)
after the material changes in the model the print head homes but too far in the x axis It prints fine until it is just one material then it homes too far causing the belt to skip and then the rest of the print being offset. old cura anything before 15.04.6 is fine but the prints are messy with that.

**Comment by smartavionics** [comment]
There is a PR waiting to be merged into Cura that fixes a problem with erroneous travels to 0,0 when using multiple extruders (https://github.com/Ultimaker/CuraEngine/pull/776). Perhaps you are seeing that issue?

**Comment by ChrisTerBeke** [comment]
This issue has been reported several times here and there is indeed a PR to fix this.
