### ISSUE TITLE
[3.3.1] Invisible font in the dropdown menus

### ISSUE THREAD

**Issue by jfrankenau** [Ultimaker/Cura#3900]
**Application Version**

3.3.1 but also on 3.2

**Platform**
NixOS/Linux

**Steps to Reproduce**

Open one of the dropdown menus in the Print Setup sidebar.

**Actual Results**

Invisible font, see screenshot below.

**Expected results**

All availabe options in a readable font.

**Additional Information**
![cura-dropdown](https://user-images.githubusercontent.com/2736480/41029997-cbc50bb2-696c-11e8-8107-e618a571d3d1.png)

**Comment by fieldOfView** [comment]
Do you have a dark system theme?

**Comment by Vandrasc** [comment]
Do you also experience the same in 3.4? We just had a 3.4 Beta release. Thank you!

**Comment by jfrankenau** [comment]
No, I am not using a dark system theme. However, I am using plain xmonad without a desktop environment and have just been testing to manually set `QT_QPA_PLATFORMTHEME` to `qt5ct` and it seems to work. I have no idea why other Qt applications are not affected by this. So it seems to more like a NixOS/xmonad issue.

I will test 3.4 later this day.

**Comment by jfrankenau** [comment]
The issue persists with 3.4. I've also tested Cura's Ultimaker Dark theme which doesn't help.

**Comment by alekseisasin** [comment]
I hope in the next Cura version the pyqt version will be updated and this issue will be solved for you.

**Comment by ianpaschal** [comment]
> So it seems to more like a NixOS/xmonad issue.

Sounds like it to me too. Unfortunately this is far too narrow of a use case for us to debug or test, and we won't be spending any time on it.

Sorry about that.
