### ISSUE TITLE
you delete a object but it still prints!

### ISSUE THREAD

**Issue by robomaniac** [Ultimaker/Cura#391]
Hello

I drag and drop new .STL file in Cura 15.06.03 (The one on the RIGHT)
![ultimaker_before_delete](https://cloud.githubusercontent.com/assets/5814871/9838592/882a32d2-5a2f-11e5-8805-dbfc43d3ebc6.png)

I right click on the left object and click "delete". (I deleted the LEFT part)
![ultimaker_delete](https://cloud.githubusercontent.com/assets/5814871/9838601/bbe9b8c2-5a2f-11e5-9404-178dddaa216d.png)

I then click "save to SD card"

I go print it and print both parts instead of the single one!!!

**Comment by Ghostkeeper** [comment]
Maybe it fails to trigger a re-slice after deleting it?

**Comment by Xisle** [comment]
Maybe it's already fixed in 15.09.8x?

**Comment by robomaniac** [comment]
I have the new 15.09.81 and will let you guys know.
That bug already happen at least 3 times.

I will take great note when I try to reproduce this bug.

Thank you

**Comment by nallath** [comment]
Should be fixed now (starting a new print now clears existing data)
