### ISSUE TITLE
Adding new filaments/materials to Cura

### ISSUE THREAD

**Issue by jpurcelay** [Ultimaker/Cura#3921]
Hello there,

I'm looking to add to the software the profiles for the filaments my company produces (FFF world), but is not clear to me where should I put them. My interest is to add them to the material list and to have them available without the need of importing manually the xml files.

If you could tell me where are the files I should tamper with, I would be very pleased.

Thank you!

**Comment by ChrisTerBeke** [comment]
@Appesteijn

**Comment by Appesteijn** [comment]
You can make a Pull Request on Cura:
Material and Quality profiles (for the UM3) can be found https://github.com/Ultimaker/Cura/tree/master/resources/quality/ultimaker3

**Comment by diegopradogesto** [comment]
@jpurcelay I will close this issue since you already got the answer. I you need more help, please feel free to open again the issue.
