### ISSUE TITLE
printer changing

### ISSUE THREAD

**Issue by Drewf19** [Ultimaker/Cura#3926]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

cur keeps changing from the wanhao setting to the stupid maker 5 and now I cant print anything for work and everything is late now why cant is just stay at what I want

**Comment by ChrisTerBeke** [comment]
Please fill in the full issue template and add logs, screenshots or other materials we can use to properly debug.

**Comment by ianpaschal** [comment]
More than 2 weeks with no response. Closing or else this will be forgotten and stay open forever.
