### ISSUE TITLE
Imported materials cannot import associated profiles

### ISSUE THREAD

**Issue by brianzhang-git** [Ultimaker/Cura#3929]
**Application Version**
3.2.21

**Platform**
Windows 10

**Printer**
Taz 5

**Steps to Reproduce**
From a host computer, export a material and associated profile(s). On a different computer, import the material and the the profile(s).

**Actual Results**
The profiles cannot be imported, with the error message: 

> Failed to import profile from C:/Users/Brian/Desktop/GrabCAD/Conforming Underactuated Gripper/Printing Settings/abs-highquality-regularspeed.curaprofile: Could not find a quality type custom for the current configuration.

**Expected results**
The profiles should import.

**Additional Information**
The new material, after importing, lacks any valid profiles at all. If a material is created with identical properties, the profile imports successfully and with the right parameters. Consider adding a default profile to all imported materials to prevent this issue.

**Comment by ChrisTerBeke** [comment]
Not an Ultimaker release (https://github.com/Ultimaker/Cura/issues/3930).
