### ISSUE TITLE
Custom materials buried in 2-deep menus

### ISSUE THREAD

**Issue by brianzhang-git** [Ultimaker/Cura#3930]
**Application Version**
3.2.21

**Platform**
Windows 10

**Printer**
Taz 5

**Steps to Reproduce**
Create a new profile.

**Actual Results**
When selecting the profile from the materials menu, two sub-menu's must be navigated no matter what. Even if the material brand and type have been set to [blank], they are filled in as "Unknown". 

**Expected results**
A material that has not been set with a brand or type should be visible at the top-level, making it as easy to access custom materials as the built-in materials.

**Additional Information**
When Cura is full-screen, this ends up causing menus to go back-and-forth instead of traditionally opening to the right. 
![image](https://user-images.githubusercontent.com/8885230/41382881-18d11e4e-6f3c-11e8-905f-7cb2470126f5.png)

**Comment by nallath** [comment]
This isn't the cura version that we make. By the looks of it, it's the Lulzbot version from Aleph Objects. I don't know what changes they made to it, but you should contact them.
