### ISSUE TITLE
Parameter minimum infill not working

### ISSUE THREAD

**Issue by jtronics** [Ultimaker/Cura#3933]
**Application Version**
Cura 3,3,1

**Platform**

**Printer**
Ultimaker

**Steps to Reproduce**
try the Parameter minimum infill 

**Actual Results**
it does nothing

**Expected results**
don't fill small areas with infill

**Comment by Vandrasc** [comment]
Hi @jtronics, could you provide us with some more information? Can you upload your project file so we can have a look at what could have gone wrong?  Maybe also attach a screenshot? 

Thank you!

**Comment by LemaruX** [comment]
I also have issues with this feature. Though I find it does work once you set the value's appropriately, but it often then removed the top layer of skin from certain areas. I posted details here https://community.ultimaker.com/topic/23131-minimum-infill-area/

Whilst smartavionics tried to explain that the feature is broken but would not perform what I require, I dine that it does do exactly what I require it to, as per the description of this feature on the Cura website. But I cannot use it when it then causes small areas of skin to be missing, 

This can be replicated using this model. If you set the minimum infill to 50mm^2 you will see the top skin in the small holes disappear (as per the screenshots in my forum post). https://www.thingiverse.com/thing:2495538

(This may not be the same issue as the OP who claims it doesn't work at all, so happy to raise it seperately if required).

**Comment by Ghostkeeper** [comment]
This was fixed via https://github.com/Ultimaker/Cura/issues/4053.
