### ISSUE TITLE
Spurious "file reload?" notifications posted

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#3936]
**Application Version**

master branch

**Platform**

Linux

**Printer**

Kossel Mini

**Steps to Reproduce**

Load a gcode file to view, delete that and then load model(s), slice and save gcode using the same filename as was viewed earlier.

**Actual Results**

Unexpected notifications appear offering to reload the gcode file that was previously viewed.

**Expected results**

Notifications should not appear.

**Additional Information**

See attached screenshot.

I have also seen many of these notifications appearing when I have a part duplicated and I update the part's STL file. Only one need be posted in that situation, not one for each of the instances of the part.

![screenshot_2018-06-15_13-41-05](https://user-images.githubusercontent.com/585618/41468571-584efd04-70a2-11e8-9a22-e4fca089a428.png)

**Comment by Vandrasc** [comment]
Ah, @Ellecross, look at this :) What was the decision regarding the unnecessary messages and Reload button?

**Comment by diegopradogesto** [comment]
For devs.: CURA-5478

**Comment by Ghostkeeper** [comment]
This issue was fixed yesterday, so you shouldn't get the message twice any more, the reload button should work properly, the message should disappear when you reload, and when you save a file from Cura on top of a currently opened file you should not get a message to reload.

**Comment by smartavionics** [comment]
Back on this again. Current master branch posts multiple notifications when stl file is updated. This is with just one update to a single instance of the model.

![screenshot_2018-08-15_20-05-21](https://user-images.githubusercontent.com/585618/44167691-c42c3380-a0c6-11e8-818c-2950e0004019.png)

**Comment by smartavionics** [comment]
This needs to be reopened.

Also, I notice today that the gcode files that I save are now appearing the recent file list which is not what I want at all. Surely that's a regression?

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce it at this time.

![screenshot from 2018-10-15 11-55-49](https://user-images.githubusercontent.com/2448634/46944032-558d3700-d071-11e8-8c24-25f64a81aea2.png)

Maybe it was fixed again in the meanwhile?

I do remember that the g-codes in the recent file list was a regression at some point.
