### ISSUE TITLE
[3.3.1] critical flat top/bottom broken shell issue

### ISSUE THREAD

**Issue by St007** [Ultimaker/Cura#3939]
**Application Version**
3.3.1

**Platform**
Win10

**Printer**
All printers

**Steps to Reproduce**
Slice model with default settings https://www.thingiverse.com/thing:2524462

**Actual Results**
Shell is interrupted with infill.

**Expected results**
Shell + outside perimeter must form continues object

**Additional Information**
Attachments: schematic of issue, broken printed object (it is really easy to broke because of this issue), compare with Simplify3D (how it must be)
![cura_issue](https://user-images.githubusercontent.com/5739480/41497956-953562d6-7169-11e8-95f2-fdcb88066fc4.png)
![photo_2018-06-16_13-31-48](https://user-images.githubusercontent.com/5739480/41497959-a77b78f4-7169-11e8-9176-91a3093154c0.jpg)
![photo_2018-06-16_12-54-48](https://user-images.githubusercontent.com/5739480/41497961-ac153648-7169-11e8-9143-79229183500c.jpg)

**Comment by smartavionics** [comment]
Hi, the only way I can recreate what you are showing above is to have a few mm of skin removal width and zero skin expansion. If you reduce the skin removal width it won't zap so much skin. In fact, for this model you probably want the skin removal width to be zero and have a non-zero amount of skin expansion.

![screenshot_2018-06-16_13-10-26](https://user-images.githubusercontent.com/585618/41498486-15384898-7167-11e8-9bfb-58c85d9f47cf.png)

**Comment by St007** [comment]
smartavionics, thank you for suggestion
After correction, now I have same result as with Simplify3D, however these settings are hidden by default/ Default value for Skin Removal Width equals shell width which leads into issue of this topic. So, for new users who do not know which settings affecting such result, the behavior will look like critical issue. I think Skin Removal Width must be zero by default. So, my suggestion is to keep open with issue report and wait for Ultimaker dev team response.
![after_crrect_settings](https://user-images.githubusercontent.com/5739480/41498625-46525a7c-717b-11e8-9223-b943c73f6f3b.png)

**Comment by smartavionics** [comment]
I agree, leave it open so that a discussion can be had around the default value of skin removal width. Personally, I would tend to agree with you that it should default to zero or a low value.
