### ISSUE TITLE
Cura USB Fehler Ramps 1.4 (Cura 3.* Error on Ramps 1.4 USB)

### ISSUE THREAD

**Issue by uudesignRene** [Ultimaker/Cura#3940]
Das drucken per Ramps 1.4 über USB funktioniert ab Version 3 mit Cura nicht mehr.

USB Connection (ausführen) -> Die Temperatur wird nicht geändert.

The Print do not start, and the temperatur do not Change.

![unbenannt](https://user-images.githubusercontent.com/40316971/41498222-264b95bc-7168-11e8-80f4-62fc65906c68.png)

**Comment by ChrisTerBeke** [comment]
We don't have RAMPS boards to test anything with, so this is really up to the community I'm afraid.

**Comment by GregValiant** [comment]
I'll go ahead and close this.  It's been 6 years and no contributors have picked in up.
