### ISSUE TITLE
incorrect scaling

### ISSUE THREAD

**Issue by jagmode** [Ultimaker/Cura#3941]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ChrisTerBeke** [comment]
Please fill out the issue template, attach logs and/or screenshots or anything else to clarify your issue.

**Comment by jagmode** [comment]
I found that my Solidworks settings for STL corrupted the file.

I reset solidworks STL settings and all is well.

Adam
Adam Spencer
17657 Pomerado Road Unit 49
San Diego CA 92128

**Comment by smartavionics** [comment]
Hi Adam, if all is OK now, please close the issue, thanks.

**Comment by ChrisTerBeke** [comment]
Thanks for responding :)

**Comment by jagmode** [comment]
Thanks you for your very quick response.
Adam Spencer
17657 Pomerado Road Unit 49
San Diego CA 92128
