### ISSUE TITLE
[3.3.1] appdata.xml contains invalid XML entities

### ISSUE THREAD

**Issue by onitake** [Ultimaker/Cura#3944]
**Application Version**
Cura 3.3.1 (and all previous versions)

**Platform**
Linux

**Printer**
Not applicable

**Steps to Reproduce**
Run `xmllint` on cura.appdata.xml

**Actual Results**
`xmllint` complains about unescaped entities:
```
cura.appdata.xml:29: parser error : EntityRef: expecting ';'
page">https://ultimaker.com/en/products/cura-software?utm_source=cura&utm_medium
                                                                               ^
cura.appdata.xml:29: parser error : EntityRef: expecting ';'
r.com/en/products/cura-software?utm_source=cura&utm_medium=software&utm_campaign
                                                                               ^
```

**Expected results**
No errors.

**Additional Information**

This issue appeared because Linitian includes a new check for appstream XML validity since 4.1.4, but the file was incorrect before.

**Comment by onitake** [comment]
:+1: Here you go.

**Comment by ChrisTerBeke** [comment]
Thanks! Closing this in favor of the PR.
