### ISSUE TITLE
Cura 3.3.1 doesn't work

### ISSUE THREAD

**Issue by Lucacenci** [Ultimaker/Cura#3949]
after the Upgrado of the Cura software the printer is not working, (invalid code), some help?
thank you

**Comment by ChrisTerBeke** [comment]
Please fill out the issue template, attach logs and/or screenshots or anything else to clarify your issue.

**Comment by Lucacenci** [comment]
![cura](https://user-images.githubusercontent.com/40350777/41528844-cd4658d4-72da-11e8-9386-ac937575320a.jpg)
this is the message, all the program made with new Printer is not working

**Comment by ChrisTerBeke** [comment]
And the explanation on ultimaker.com/ER26 doesn't help you further? Seems like you're slicing for the wrong machine in Cura?

**Comment by Lucacenci** [comment]
yes but thr printer is correct

**Comment by ChrisTerBeke** [comment]
Can you share a project file (in Cura click file -> safe as project)?

**Comment by ianpaschal** [comment]
More than a week without response. If @Lucacenci gets back to us we can reopen otherwise this is going to be forgotten about.

**Comment by Ghostkeeper** [comment]
Most likely this is the result of accidentally enabling "Origin at Center".

Could you go into the Machine Manager, click "Machine Settings" and make sure that "Origin at Center" is disabled?
