### ISSUE TITLE
Monitor - Active Print - Printing Time not showing after print is ready - Cura 3.3.1

### ISSUE THREAD

**Issue by waterwin** [Ultimaker/Cura#3953]
**Application Version**
Cura 3.3.1

**Platform**
Windows 10 64 bit

**Printer**
Ultimaker Original

**Steps to Reproduce**
Do a print 

**Actual Results**
Print is ok but Printing time is empty

**Expected results**
Software should show the time it took to print
![printing time not showing](https://user-images.githubusercontent.com/21102829/41557304-7da8752e-733d-11e8-8a96-17dede79656d.JPG)

**Additional Information**
When the print start a count down timer is showing starting from -2.00.00 and counting down which has no relation to the estimated printing time before starting the print via usb

**Comment by alekseisasin** [comment]
@waterwin , we fixed the starting time should be fixed. Please check the latest Cura version.

**Comment by ianpaschal** [comment]
^Haven't heard back so I will consider this a "yes"
