### ISSUE TITLE
shortcuts and slicing improvments 

### ISSUE THREAD

**Issue by ASAFHOLTZ** [Ultimaker/Cura#3955]
Hi
Must have shortcuts for move, scale, rotate
also the slicing every move is reall annoing
cheers

**Comment by ASAFHOLTZ** [comment]
Thanks a lot !

**Comment by AbeFM** [comment]
Some indication of the existence of those hotkeys would be nice (letter on the button).

Glad to learn them!

**Comment by ChrisTerBeke** [comment]
Available already as @fieldOfView indicated (thanks!). Also please fill out the issue template next time or otherwise your issue might not be picked up.
