### ISSUE TITLE
Can someone tell me why Version 15 of Cura prints way better than 3.3 with the same settings 

### ISSUE THREAD

**Issue by Ninjarev** [Ultimaker/Cura#3956]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ninjarev** [comment]
I have a Maker select V2 and I switched to 3.3 cura from 15 and my prints have went way down hill 
I checked both programs for settings differences and they are the same but the 3.3 the prints are not near as good..   I can upload pics too

**Comment by smartavionics** [comment]
What would be useful is if you provided the gcode for the same part sliced using similar settings with both of the slicers. Then I could compare them and maybe come to some conclusion. As it is, your report is worthless.

**Comment by Ninjarev** [comment]
And here are the pics
![cura 2](https://user-images.githubusercontent.com/12824354/41627473-4a646982-73d5-11e8-9f08-f1ae8425cb85.JPG)
![cura 3](https://user-images.githubusercontent.com/12824354/41627474-4a833f92-73d5-11e8-9733-38d5367b5a2f.JPG)
![cura 4](https://user-images.githubusercontent.com/12824354/41627475-4a9ca1e4-73d5-11e8-9171-1afb536ef6e2.JPG)
![cura 5](https://user-images.githubusercontent.com/12824354/41627476-4ab86d2a-73d5-11e8-8d57-bef77f50f59a.JPG)
![cura 3 3](https://user-images.githubusercontent.com/12824354/41627477-4ad2ca3a-73d5-11e8-9e39-13a2b1efe448.JPG)
![cura15](https://user-images.githubusercontent.com/12824354/41627478-4b03d36e-73d5-11e8-9d21-f00c694bb8f8.JPG)

**Comment by smartavionics** [comment]
Thanks for the gcode - I've had a quick look and obvious differences are that one has the inner and outer wall z-seams aligned and the other doesn't so to get 3.3 to align the z-seams turn on the wall printing order optimization. Also, I notice that you have changed to use relative extrusion. I know nothing about your printer but I am wondering if the extruder resolution (steps/mm) is too low for successful use of relative extrusion. You may find that using absolute extrusion produces a better quality finish. If I see anything else worth mentioning I will come back.

**Comment by Ninjarev** [comment]
WOW great thanks for looking that over  Ill try what you said and see if that helps it..

JIM


________________________________

**Comment by ianpaschal** [comment]
Almost 3 weeks, considering this question answered. Thanks Mr. Avionics.
