### ISSUE TITLE
z-hop not working on Cura 3.4 beta

### ISSUE THREAD

**Issue by TheSpirit** [Ultimaker/Cura#3963]
z-hop when retract is activated, but my CR-10 does not perform a z-hop.
can someone look at my profile and tell me why?
Thanks

[my.curaprofile.txt](https://github.com/Ultimaker/Cura/files/2128824/my.curaprofile.txt)

**Comment by diegopradogesto** [comment]
Please fill out the issue template or this ticket will be closed.

Which version of Cura are you using? Which model? Can you provide a **project file** (File -> Save project)?
