### ISSUE TITLE
15.09.81: machine_platform_offset does not make any difference

### ISSUE THREAD

**Issue by nicanor-romero** [Ultimaker/Cura#397]
Changing this value in the machine settings has no effect in the mesh position.

In the Engine Log, this appears:

"Unrecognized data type in JSON: machine_platform_offset has type array"

**Comment by nallath** [comment]
The engine log doesn't need the offset (but gets it anyway). That error can be safely ignored. For some reason the code that actually moves the platform mesh based on that setting has been commented out. 

If you feel like it, you could experiment a bit with the code that you can find in _onActiveMachineChanged of curaApplication.py. 

We're rather busy with fixing bigger issues, so this won't have a very high priority with us, sorry.

**Comment by nicanor-romero** [comment]
Will do, thanks!

**Comment by nallath** [comment]
Any progress with regards to this? I'm curious if you're able to get it working. We'd love to get more contributions from other people outside of UM.

**Comment by awhiemstra** [comment]
Hmm, I was the one that commented out that code as it should be done by the Platform class, since that handles all other platform related settings. I just completely forgot to move the code there.

**Comment by nallath** [comment]
Should be fixed in next release, we needed it as well.
