### ISSUE TITLE
[discussion] Logging is too verbose

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#3978]
The logs show vital information, but currently much of this vital information is "snowed under" because of too verbose logging. Eg showing each material that gets excluded one by one for each MaterialModel that gets created adds useless noise to the logs.

**Application Version**
3.4, master

**Platform**
all

**Printer**
all

**Steps to Reproduce**
configure Cura with multiple types of printers
start Cura
check the logs

**Actual Results**
Logs are extremely verbose, to the point of being almost unreadable.

**Expected results**
Logs are less verbose, so it is possible to spot actual warnings and errors.

**Additional Information**
Note that logs are still copied over from version to version, so log files that are close to a gigabyte large are not uncommon. This helps nooone.

**Comment by Ghostkeeper** [comment]
I wholeheartedly agree with this. It's gotten much worse in the last 2 releases.

**Comment by ChrisTerBeke** [comment]
Maybe we should define which logging levels should be used for what (and write some docs for that)?

**Comment by Ghostkeeper** [comment]
There is one here now: https://confluence.ultimaker.com:8443/display/SD/20180903-2+Logging but it's behind a login for Ultimaker employees only. This sort of thing should normally go under https://github.com/Ultimaker/Meta.

**Comment by fieldOfView** [comment]
I don't think it is useful to keep this issue open after almost 2 years.

**Comment by df7cb** [comment]
Hi @fieldOfView,
the problem is still there and is also being tracked as a Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950580
I don't think it should be closed.
