### ISSUE TITLE
15.09.81: start_gcode not always included in gcode

### ISSUE THREAD

**Issue by nicanor-romero** [Ultimaker/Cura#398]
When using the RepRap gcode flavour, the start_gcode is only added when one of the settings are modified. The end_gcode is always added. In the Cura profile string the both start and end gcodes are present.

**Comment by nallath** [comment]
Sounds like an engine issue. The software engineer that works on the engine is on a holiday, so don't expect a solution to this any time soon (~2 weeks).

**Comment by BagelOrb** [comment]
This sounds like a frontend issue.
Especially the dependency on other settings makes me think it's a frontend issue.

What version of Cura are you using?

**Comment by BagelOrb** [comment]
Fixed

**Comment by BagelOrb** [comment]
Fixed
