### ISSUE TITLE
print sequence should take into account extruder geometry

### ISSUE THREAD

**Issue by tmbdev** [Ultimaker/Cura#3985]
As far as I can tell, when placing multiple objects and printing them "One at a time", the print sequence seems to be "order added" or something like that. But the optimal print sequence depends on extruder geometry. For example, for an Anycubic i3 Mega extruder, the fan is to the left of the nozzle, so printing objects right-to-left allows them to be spaced more closely.

Ideally, placing and print ordering for multiple objects would take into account extruder geometry. However, at least a preferred print order (specified perhaps as a vector) would already be quite helpful.

**Comment by ChrisTerBeke** [comment]
Cura does this, but it might be that your machine configuration does not have the right geometry in it?

**Comment by tmbdev** [comment]
I see no such configuration option either in the printer definition or in the extruder definition; where would that be found, for example for the Prusa mk2?

**Comment by ChrisTerBeke** [comment]
It's not configurable in the UI, only in the source files of the printers.

UM3: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/ultimaker3.def.json#L42
Fallback value: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json#L414

The creators of the Prusa mk2 and Anycubic i3  did not set these values, so it uses the default fallback value.

**Comment by fieldOfView** [comment]
> It's not configurable in the UI,

Yes it is, that's what the Printhead Settings in Machine Settings control.

**Comment by ChrisTerBeke** [comment]
@fieldOfView ah cool. I never dive into those :P
