### ISSUE TITLE
3.3.1 Can't set up custom material, prusa i3 (1.27mm 0.05" Nylon) similar to issues 3980 & 3965

### ISSUE THREAD

**Issue by huramentzefix** [Ultimaker/Cura#3988]
**Application Version**
3.3.1

**Platform**
WIndows 10 (comma seperated decimals)

**Printer**
Prusa i3

**Steps to Reproduce**
>Material > create (or copy) > Nylon 1,27mm
A message will be displayed that this is not compatible with this machine, asking if I want to continue.
when I select "Yes" it will just dissapear and not show anywhere.
also my custom set materials from before will dissapear or be deleted.

**Actual Results**
Setting will dissapear and erase previous saved custom materials

**Expected results**
To save custom settings.

**Additional Information**
I have noticed that the factory stored profiles are being displayed with a decimal point.
the windows that shows the cost in € shows a decimal comma.

When I create a new material the decimal comma is pre-defined.
I tried to enter it with the given comma which doesn't store the profile.
When I try to enter it with a decimal point it won't accept the input.

Try to set your decimal seperation to a comma on your machine and try to reproduce the isse.

please contact me if I can be of any help.

**Comment by LipuFei** [comment]
Hi @huramentzefix , For Prusa i3, the default compatible material diameter for it is 1.75 mm, which rounds up to 2 mm. Your 1.27 mm Nylon has a "1 mm" rounded material diameter which is considered incompatible with your machine's 1.75 mm. This is explained in that message.

If you want to use that 1.27 mm material, you can go to your machine settings, switch to the Extruder tab, and change your material diameter for that Extruder to 1.27mm. See screenshot below:
![image](https://user-images.githubusercontent.com/2630468/42083032-0595e648-7b8a-11e8-8eb8-38226028e96d.png)
