### ISSUE TITLE
Cura 3.4 crash when Add custom printer

### ISSUE THREAD

**Issue by gaerank** [Ultimaker/Cura#3991]
**Application Version**
3.4

**Platform**
Fedora27

**Printer**
Custom printer

**Steps to Reproduce**
Add new printer type as custom printer. click "Add Printer" button then crash.
cura closed.

**Actual Results**
cura crash. end of program.

**Expected results**
process custom printer setting.

**Additional Information**

**Comment by LipuFei** [comment]
Hi @gaerank, could you provide the log files? Thank you.

**Comment by gaerank** [comment]
I found  " ~/.local/share/cura/stderr.log "
Is this right file??
[stderr.log](https://github.com/Ultimaker/Cura/files/2153536/stderr.log)

**Comment by gaerank** [comment]
Hi, I've solve the problem.
I delete all from ~/.config/cura and ~/.local/share/cura.
and run again. it works fine.

Thank you.

**Comment by Ghostkeeper** [comment]
Whatever it was, I believe this particular bug was fixed anyway when @diegopradogesto saw your bug report. Fix is here: 762a1b1bfdbb7fcb37bfa08013870793f5d20640
