### ISSUE TITLE
[3.3.1 & 3.4] Cannot display the adaptive layer height

### ISSUE THREAD

**Issue by Tcadiou** [Ultimaker/Cura#3993]
**Application Version**
Cura 3.3.1 and 3.4

**Platform**
Windows 10

**Printer**
Custom Printer (not relevant to the problem I think)

**Steps to Reproduce**
I use adaptive layer to print,
I let the other parameters as they are and then I slice

**Actual Results**
It slices, the adaptive layers are taken into account (I can tell with the time of the print changing if I use it or not) but it doesn't show the layers height as it usually do.

**Expected results**
showing the layers heigh on the screen 

**Additional Information**
it worked before on the 3.2 versions of cura

**Comment by fieldOfView** [comment]
In general preferences, is the "Force layer view compatibility mode" checkbox checked?

**Comment by Tcadiou** [comment]
The "Force layer view compatibility mode" box is checked!


________________________________
De : Aldo Hoeben <notifications@github.com>
Envoyé : jeudi 28 juin 2018 14:10
À : Ultimaker/Cura
Cc : Tcadiou; Author
Objet : Re: [Ultimaker/Cura] [3.3.1 & 3.4] Cannot display the adaptive layer height (#3993)


In general preferences, is the "Force layer view compatibility mode" checkbox checked?

**Comment by Tcadiou** [comment]
I unchecked it and now it works!!!


Thanks


________________________________
De : Aldo Hoeben <notifications@github.com>
Envoyé : jeudi 28 juin 2018 14:10
À : Ultimaker/Cura
Cc : Tcadiou; Author
Objet : Re: [Ultimaker/Cura] [3.3.1 & 3.4] Cannot display the adaptive layer height (#3993)


In general preferences, is the "Force layer view compatibility mode" checkbox checked?

**Comment by Ghostkeeper** [comment]
So the bug then seems to be that compatibility mode doesn't display the correct layer heights.

**Comment by Ghostkeeper** [comment]
I can't reproduce this problem though.

**Comment by Tcadiou** [comment]
Hi, 
It seemed to be rela ted to the computer not to the version of Cura.

Anyway now we have better versions
