### ISSUE TITLE
Variable Layer Height needs to have "average" and "range"

### ISSUE THREAD

**Issue by AbeFM** [Ultimaker/Cura#3995]
I've already made a number of suggestions about this topic - I think there is some low hanging fruit on the variable layer height feature which would make it a lot more useful in the real world: Let the user pick the AVERAGE layer height, set sensible limits for max and min, and get a model where you can make some predictions about what you're going to get before hitting slice.

Currently I can take two models, turn on variable layer heights, and get one to half its print time while the other triples, and short of tweaking every number in the settings, you can't really get an average layer height/print time other than tweaking the sensitivity and seeing what you get with iterative, manual slicing.

I've seen the suggestion ignored, but never commented on. What is it I am missing about NOT doing this that makes the feature easy to use?

I thought the suggest was self evident, and I'm no mathematician, but I think if you told me to scale a bunch of numbers so that they remained proportional but had a particular average, I could do it this way:

You take each layer's height initially calculated height, Zstep(layer#), and average those:
Zstep(AVG) = (Zstep1 + Zstep2 + Zstep3 .... + Zstepn)

After slicing, you take the calculated Z steps, and scale them by LayerThickness / Zstep(Avg):

ZstepFinal(n) = Zstep(n) / Zstep(Avg)

Using those Z-steps will completely allow you to set up a print, and turn "variable height" on and off and keep the same average print time, and make MEANINGFUL changes to the settings.

You can Check out the last couple posts here: https://community.ultimaker.com/topic/21520-adaptive-layers/?page=2 which discusses a bug (multiple objects not slicing), but mainly shows this isn't a new suggestion....

Can we please at least chime in on the value of this feature? It seems reasonable to implement and the current way sucks.

Typical Model:
`

Desired Avg | thickness | Corrected Thickness
-- | -- | --
5 | 5 | 5.43478260869565
  | 6 | 6.52173913043478
Scale Factor | 4 | 4.34782608695652
1.08695652173913 | 8 | 8.69565217391305
  | 9 | 9.78260869565218
  | 2 | 2.17391304347826
  | 1 | 1.08695652173913
  | 6 | 6.52173913043478
  | 3 | 3.26086956521739
  | 2 | 2.17391304347826
AvgSliced | 4.6 | 5

`

Highly Slopped Model:
`

Desired Avg | thickness | Corrected Thickness
-- | -- | --
5 | 5 | 9.61538461538462
  | 4 | 7.69230769230769
Scale Factor | 4 | 7.69230769230769
1.92307692307692 | 4 | 7.69230769230769
  | 3 | 5.76923076923077
  | 2 | 3.84615384615385
  | 1 | 1.92307692307692
  | 1 | 1.92307692307692
  | 1 | 1.92307692307692
  | 1 | 1.92307692307692
AvgSliced | 2.6 | 5

`

**Comment by ChrisTerBeke** [comment]
`the current way sucks`

You're welcome...

**Comment by AbeFM** [comment]
Welcome to... ? I am trying to help here. The current set up express many
of the knobs, but they aren't presented in a meaningful way.

You can't make any predictions about what you're going to get without
picking the average.

If you're convinced I'm missing something that is just great about the
current method, please share it, cause I'm missing out.

I made a logical argument for my POV, if you don't have the time, ok. If
you think I'm wrong, I'd like to know.

Otherwise, I'm trying to make an industry leading feature widely accessible
and better than the competition.

                  Thanks!
                          -Abe.

**Comment by fieldOfView** [comment]
Developers who put their heart and soul into developing a feature don’t respond well to having their work called “rubbish”.

**Comment by AbeFM** [comment]
Fine.


I can't try harder to help. If you want to take this suggestion as a
personal attack instead of a compliment, if you read over the attacks of
compliments I put in there, or the past several threads...

You're just looking for an excuse to start shit.

You show me the disparagement. You show me how pages of "here's how to make
sketching technically great into something broadly usable.

The math required is middle school level, and you don't even need to think
it to yourself.

What's your damn problem?

                  Thanks!
                          -Abe.

**Comment by fieldOfView** [comment]
Just use other words. “Doesn’t work very well” would have been much more palletable than “sucks”.

**Comment by AbeFM** [comment]
Ok. The feature doesn't work very well.

Now, does anyone have any feeling or related input into the matter at hand - the layer thickness and how it is generated?

**Comment by ianpaschal** [comment]
> The math required is middle school level, and you don't even need to think
it to yourself. What's your damn problem?

We look forward to your pull request.

**Comment by ianpaschal** [comment]
Closing until we discuss it as a team since this is getting off topic preeeeetty fast.

**Comment by ianpaschal** [comment]
Ok, this has been discussed internally and we've decided it's too much work to implement for now. Obviously the math is fairly straight forward but it involves a *lot* of work adding new UI elements, handling compatibility, modifying the backend/slicer to use the new settings, etc.

We encounter this issue a lot where a non-programmer feels something is trivial to implement because they don't understand that it's not. Most, however, are more gracious than you were, @AbeFM. Insulting our intelligence, saying the feature sucks, accusing one of Cura's most dedicated contributors of "just trying to start shit," and asking us "What's your damn problem?" all leave a *really* bad taste.

There's a lot that can be improved about adaptive layers, we're aware of this. But there is a shortage of time and man power. If you'd like to make a pull request with a proposed solution we'd be really, really excited to review and merge it. But this kind of thread is not contributive and we'll just leave it at that until we're able to address the issue properly, probably before v4.0 in the fall.
