### ISSUE TITLE
Octoprint PlugIn is not showing camera view in CONNECT pane

### ISSUE THREAD

**Issue by LilBub** [Ultimaker/Cura#3997]
New PC, first time Cura install.
Installed 3.4 
Installed Octoprint Plugin
Went through the steps and no video.

After some general debugging (video works on Octoprint webserver), I referred to the recent GitHub ticket (https://github.com/Ultimaker/Cura/issues/3725#issuecomment-401177296) and downloaded and replaced that file.

Works now.

For some reason, the fix didn't get carried into the Production release?

**Comment by diegopradogesto** [comment]
We are currently deploying the new OctoPrint cura package, and luckily today you will find the new version 3.4.1 provided by @fieldOfView in the new Toolbox. In fact this version was specifically created to fix this issue with the camera.

**Comment by Vandrasc** [comment]
This should be now fixed.

**Comment by fieldOfView** [comment]
Toolbox still seems to serve up OctoPrintPlugin 3.4.0. This was fixed in OctoPrintPlugin 3.4.1

**Comment by diegopradogesto** [comment]
Still waiting for somebody to merge our staging branch into production.

**Comment by LilBub** [comment]
I am not seeing 3.4.1 on the download page?  Unless this is rebundling 3.4?

**Comment by diegopradogesto** [comment]
It should be now available for download in the toolbox.

**Comment by LilBub** [comment]
Will test.
