### ISSUE TITLE
Can't save a mesh file

### ISSUE THREAD

**Issue by stevie-r** [Ultimaker/Cura#40]
Hi - imported large STL (120Mb) and Cura 15.04 can't save a mesh file. Writes a file of 0Kb. Please fix. Seems to be a hard limit. Thanks.

**Comment by Ghostkeeper** [comment]
Stevie and I discussed this bug [here](http://ultimaker.com/en/community/view/16368-unable-to-save-mesh-file).

**Comment by nallath** [comment]
Is this issue still in the latest version?
