### ISSUE TITLE
СURA does not save print profile data.

### ISSUE THREAD

**Issue by Sadhaka87** [Ultimaker/Cura#4003]
СURA does not save print profile data when the program is restarted

СURA 3.4
WIN 10
This fuss with the profiles is already boring. After every update of the program, will I have to reset everything and create it again?

**Comment by messengert** [comment]
I am having the same problem after upgrading. It worked fine for me on 3.1, but no longer. 

Cura 3.4
WIndows 10

**Comment by ianpaschal** [comment]
Please fill out the issue template or this ticket will be closed.

What happened? What didn't save? Are values different? Is the file gone? Without specifics we won't be capable of doing anything to help.

**Comment by Sadhaka87** [comment]
I updated the program version 3.3.1 to version 3.4. The printer profile and print profile profiles were automatically imported from the old version, as usual. I change the print settings (layer thickness, fill and any others), I click save the profile. The profile is saved successfully. I close the program. Then I run the program again and I have the settings that were originally after the update.

**Comment by diegopradogesto** [comment]
We have automated tests that performs similar scenarios and it works as expected. However it can be a case that we don't test. Can you please provide your 3.3.1 configuration folder? Then we can investigate a bit more.

**Comment by diegopradogesto** [comment]
I just tried using your 3.3 folder and starting up the new 3.4.1 release and it seems to work fine. Can you try with the newest version?

Here you have two screenshots comparing versions:

**Ultimaker Cura 3.3**
![image](https://user-images.githubusercontent.com/15830521/42618755-5641199c-85b6-11e8-8ec8-7fba83df481d.png)
![image](https://user-images.githubusercontent.com/15830521/42618785-6c4ae6dc-85b6-11e8-8b44-de892d10822c.png)

**Ultimaker Cura 3.4.1**
![image](https://user-images.githubusercontent.com/15830521/42618881-946e390c-85b6-11e8-81cb-52e11bb15680.png)
![image](https://user-images.githubusercontent.com/15830521/42618911-ab4450c6-85b6-11e8-9529-8a381b58bad3.png)

**Comment by Sadhaka87** [comment]
Updated to 3.4.1 and now it works correctly. Thank you.

**Comment by diegopradogesto** [comment]
Nice, glad to hear!
