### ISSUE TITLE
Cura 3.4 changed project name not effective

### ISSUE THREAD

**Issue by yyh1002** [Ultimaker/Cura#4007]
**Application Version**
3.4
**Platform**
Windows 10
**Printer**
UM2+
**Steps to Reproduce**
Load model "a a". Change project name on lower right corner from "UM2_a a" to "UM2_a b". Save to SD. 
**Actual Results**
Saved gcode file named as "UM2_a_a"
**Expected results**
Save gcode file named as "UM2_a_b"

**Comment by ianpaschal** [comment]
Yup. I'm able to reproduce this. Thanks for reporting.
