### ISSUE TITLE
[3.4.1] Turning "Brim only on outside" OFF, increases print time + weird lines

### ISSUE THREAD

**Issue by UltiArjan** [Ultimaker/Cura#4009]
**Application Version**
3.4

**Platform**
WIN10

**Printer**
UM3 / UMs5

load a model, default settings, toggle the "Brim Only on Outside"﻿ checkbox.

**Actual Results**
see screenshot, turning it on will add many hours to a simple print of a few minutes.

strange thing is it results in a new crazy print time every time you toggle the button again.

**Expected results**
just a few minutes of extra print time

BUG was reported on the forum by klaus_kreamer here:
https://community.ultimaker.com/topic/23583-cura-34-brim-only-on-outside/

![image](https://user-images.githubusercontent.com/9219556/42138581-e704d71e-7d7f-11e8-9796-fe68f0a70ca5.png)

![image](https://user-images.githubusercontent.com/9219556/42138583-f6c0d360-7d7f-11e8-97b1-fbf300eb583f.png)

**Comment by Vandrasc** [comment]
Yes, reproduced on other models as well, it seems that we generate random slicing times each time a slicing is retriggered.
Thank you!

**Comment by AbeFM** [comment]
I've seen this a bunch, across a lot of models from a lot of sources.

Generally with multiple build plates turned on, not sure if it's related.

**Comment by Vandrasc** [comment]
Devs, see CURA-5533

**Comment by SimonRafferty** [comment]
Also having this issue in 3.4.0 & 3.4.1
It's refusing to print an object I printed OK a couple of weeks ago.  Unfortunately, it needs the brim on the inside to be successful.
![image](https://user-images.githubusercontent.com/13219057/42750126-f2ba0764-88dd-11e8-9c1d-c944798c6e83.png)

**Comment by PimpTrizkit** [comment]
I second this issue.

Anycubic i3 Mega, Cura 3.4.1. 

Im trying to print the Articulating Phone Mount: https://www.thingiverse.com/thing:2448971
(i first noticed it on the "Arm - Threaded.stl" file)

PT

**Comment by diegopradogesto** [comment]
This is now fixed!

**Comment by SimonRafferty** [comment]
>This is now fixed!
In which version?  It's happening in 3.4.1 which appears to be the latest.
![image](https://user-images.githubusercontent.com/13219057/43761109-00067840-9a1c-11e8-84fa-2a76879d6034.png)

**Comment by diegopradogesto** [comment]
Sorry for the confusion. It's fixed in master branch, that will be the next release. So, you need to wait a bit until we release the new version.
