### ISSUE TITLE
Custom Material Profiles not showing up after import sucessfully

### ISSUE THREAD

**Issue by braga-dev** [Ultimaker/Cura#4010]
**Application Version**
3.4.0

**Platform**
Windows

**Printer**
Custom FDM Printer

**Steps to Reproduce**
When creating  a custom fdm printer I want to add my custom materials profile.

**Actual Results**
When I use the import function, Cura says it successfully imported the material profile but it doesn't shows up in my material list. It only shows the basic profile for each material and Ultimaker Material Profiles.

**Expected results**
Show a Custom tab where i have all my custom material profile.

**Comment by LipuFei** [comment]
Hi @braga-dev , The material list only shows the materials with diameters compatible with your current printer's extruder. For example, if your currently active extruder has a material diameter of 2.85, but the imported material has 1.75, it won't show up because it's not compatible. You can go to "Machine Settings" to your extruder and change your nozzle size to see if your material shows up.

**Comment by braga-dev** [comment]
Hi @LipuFei i just noticed there is a slight bug or a mis-understanding on my part. So when I create my printer I said the nozzle diameter was "1,75" instead of "1.75" and the difference between using a dot ou a comma was the problem in the appearing profiles. Nevertheless when creating a material profile we use 1,75 with a comma which induced me in error.

**Comment by LipuFei** [comment]
Sounds like a bug, we will check that. Thanks for the report!

**Comment by Ghostkeeper** [comment]
I can't reproduce this bug. At least, not here on Linux.
* In the Material Manager the diameter is localised and so I can only use commas (as per the Dutch localisation). Typing a period doesn't add a period; nothing happens.
* In the Machine Manager it says `2.85` by default. Typing `1,75` is possible changes immediately into `1.75` when focus is removed from the text box. And then the 1.75mm materials load fine.

**Comment by Ghostkeeper** [comment]
Did it reproduce on Windows?

**Comment by LipuFei** [comment]
I didn't have a chance to try this on Windows...

**Comment by Ghostkeeper** [comment]
@Vandrasc Could you try this on Windows? Using a comma instead of a period for the filament diameter?

**Comment by Ghostkeeper** [comment]
We've since determined that this is caused by the user's locale. If the operating system is in a locale that is using commas as delimiter (e.g. German) then you also need to use commas in the machine settings dialogue.
