### ISSUE TITLE
Will not save updated print over old file 

### ISSUE THREAD

**Issue by astecme** [Ultimaker/Cura#4012]
Cura 3.4.0 will not overwrite an existing file on an SD card. It says it has but does not do it, the file remains the same.

**Comment by diegopradogesto** [comment]
Is it maybe because you don't have write permissions? Are you able to save a file for the first time from Cura? Can you provide the log files?

**Comment by astecme** [comment]
Ah no. Sorry I dont have log files however I changed the orientation of the print and swapped from skirt to brim. I did this a few times, the last time I checked the file on the card and the timestamp had updated but the content was the same. Deleted all files on the card and did the save again and it printed fine.

**Comment by diegopradogesto** [comment]
Is there something we can help with? Otherwise I will close the issue.
