### ISSUE TITLE
Cura 3.4.0 plugin browsr missing

### ISSUE THREAD

**Issue by derdigge** [Ultimaker/Cura#4026]
**Application Version**
3.4

**Platform**
Windows 10

**Printer**
ultimaker 3

**Steps to Reproduce**
open cura

**Actual Results**
no plugin browser

**Expected results**
a plugin browser

**Additional Information**
none given

After update to 3.4 my plugin browser is missing. I scrolled the first two issue pages and found no other report. Whats wrong here? 
https://www2.pic-upload.de/img/35581058/Unbenannt.png

**Comment by fieldOfView** [comment]
See the Toolbox menu.

**Comment by derdigge** [comment]
#stupidme 

Thanks -> close
