### ISSUE TITLE
infill support on 0% infill

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4029]
This isn't so much as a bug, but a suggestion.
Along side the infill, especially at medium to 0% infill, certain layers require extra internal support, ie parts of a layer that would float in mid air because the infill doesn't happen to fall in the right place. These parts could be given their own extra support, specifically around their circumference and maybe a little extra infill inside the circumference, depending on the size of the area being printed. A good 0% support structure would be arches, like the sort used under bridges.

I would find this very useful as I would like to be able to use 0% infill, where additional strength or a lot of infill support is not required, but only where a flat surface needs support and not filling the whole internal space with filament.

**Application Version**
all

**Platform**
windows 10

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by fieldOfView** [comment]
See the setting "Infill Support"  (added in version 3.4)
