### ISSUE TITLE
[3.4.0] "one at a time" mode does not use user-defined printhead settings for built-in printer profiles

### ISSUE THREAD

**Issue by hgarrereyn** [Ultimaker/Cura#4034]
**Application Version**
3.4.0

**Platform**
macOS 10.12.6

**Printer**
Prusa i3 profile & custom FDM profile

**Steps to Reproduce**
1. Go to `Settings > Printer > Add printer ...` and chose "Prusa i3"
2. Load a model into Cura and change "Print Sequence" to "One at a time"
3. A light grey box will appear around the model to indicate the "no-go" zones for the printhead
4. Navigate to `Settings > Printer > Manage printer`then select the Prusa i3 machine and click "Machine settings"
5. In the Printer tab, change X min, X max, Y min and Y max to 1 mm
6. Close the dialogue and select the model in the build space 

**Actual Results**
The light grey box does not change size to reflect the new printhead dimensions

**Expected results**
The light grey box should change size to roughly 1 mm around the edge of the model

**Additional Information**
I tried this same method using the "Custom FDM Printer" profile and the settings were applied as expected so I think the issues is that the built-in machine settings take priority over the user-defined settings in the "one at a time" mode.

**Comment by alekseisasin** [comment]
Yes, it looks like a big, we will check it. Thank you.

**Comment by alekseisasin** [comment]
DEVS: CURA-5569
You can find the fix under this commit. If it is urgent for you can update your profile according to this fix.
