### ISSUE TITLE
Cura 3.4.0 does not start Anet A6

### ISSUE THREAD

**Issue by Hannus52** [Ultimaker/Cura#4035]
Cura 3.4.0 does not start the Anet A6 printer. It only heats up the nozzle and the printbed and then nothing happens. I used the json file from the previous version (3.3.1) also for the 3.4.0 version.
[anet_a6.def.json.zip](https://github.com/Ultimaker/Cura/files/2168235/anet_a6.def.json.zip)

**Comment by kirilledelman** [comment]
Related? https://github.com/Ultimaker/Cura/issues/4033

**Comment by Hannus52** [comment]
Looks the same. I am using Windows 7.


Op vr 6 jul. 2018 om 00:32 schreef Kirill Edelman <notifications@github.com>

**Comment by kirilledelman** [comment]
At least we know they're looking at it now.

**Comment by ololobus** [comment]
I have the same problem on Windows 10 and Cura 3.5.0. Heat up, but no movement. At the same time gcode to file and print from file works well
