### ISSUE TITLE
15.09.82: Won't Launch

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#404]
Hi guys,

Just installed .82 and found that it won't launch, and gives no error. Any ideas on how to troubleshoot this?

**Comment by thopiekar** [comment]
OS? release? Were is it running on?

**Comment by CCS86** [comment]
Sorry, hadn't had my coffee yet ;)

I am running Windows 10. Cura is installed in the default location on the primary drive.

**Comment by nallath** [comment]
Post the logs.

**Comment by CCS86** [comment]
Where are they stored again? I looked in ProgramData and AppData, and didn't find anything this time.

**Comment by nallath** [comment]
https://github.com/Ultimaker/Cura#logging-issues

**Comment by CCS86** [comment]
Cura has not created the AppData directory, but here is my dxdiag log.

(I gave it a jpg extension to push straight here. Just download and rename to .txt. Hopefully that works)


![dxdiag](https://cloud.githubusercontent.com/assets/12439543/9976858/e0122ab4-5eb6-11e5-99be-29477ea50423.jpg)

**Comment by Ghostkeeper** [comment]
That log doesn't mention Cura, since Cura doesn't use DirectX. Ctrl+F shows up nothing.

**Comment by thopiekar** [comment]
I know it is offtopic, but since you use an updater as plugin why is the version needed in the application path? (Sorry for starting this here - I'm just interested)

**Comment by CCS86** [comment]
![image](https://cloud.githubusercontent.com/assets/12439543/9978464/11261126-5ef6-11e5-9aaf-4703a58b67e6.png)

I know one of the other logs would be far more helpful, but apparently Cura isn't making it far enough to even create the Appdata directory.

.80 and .81 both launched fine on Windows 10 for me. This is a first. 

Yes, I have definitely launched Cura, multiple times. I tried all the different "compatibility modes", as administrator, with both of my video cards. Same. Just a brief hourglass, then nothing.

Is there a command line parameter to enable additional logging?

**Comment by nallath** [comment]
Nope. If it doesn't even get to the logging, it dies fairly early into the process.

**Comment by CCS86** [comment]
Fixed in .83!

**Comment by awhiemstra** [comment]
Yeah there was an issue with fcntl on Windows (Ultimaker/Uranium#69) that caused the initial build for Windows to fail. I replaced the .82 build with a correct one but you apparently ended up with the incorrect build. Glad to hear it is all solved for .83.
