### ISSUE TITLE
My Monoprice Delta Mini G code

### ISSUE THREAD

**Issue by Mysignupname** [Ultimaker/Cura#4040]
My Monoprice delta mini used to print with g code provided by the cura 15.04.6
After I updated to newest cura version, the g code provided by the newest cura stopped printing.

When I used the Cura 15.04.6 I always had to copy and past a line that start with M109 onto the g code file and delete the 2 lines that was there before. It will not print with the 2 lines so I use the M109 and it does work.

The Newest version Cura 3.4.0 does not work on my monoprice 3d printer. I tried putting in the start and end g code from the monoprice weki page. (the same ones I used on 15.04.6) The start and end g code did not work well with the newest cura version. I then tried copy and past the m109 line and replace the 2 lines that was there. It still did not work.

The first 2 screen shots was with the cura version 15.04.6   number 1 is the g code it first provided that did not work with my monoprice delta 3d printer. number 2 screen shot is the one that does work now everytime I copy and past the M109 line and delete the 2 lines that it provides me. number 3 screen shot is the newest version cura 3.4.0 that does not work. (even after I switched start and end g code, I copy and past M109 line and delete the 2 lines it provides.)

Can cura add a default setting for monoprice delta mini printer? 
 

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

![capture lego print did not start](https://user-images.githubusercontent.com/40958140/42421808-a231dfa4-82a9-11e8-9f72-99e7e19dc9d0.PNG)
![capture revise did print change first line to same as with auto file](https://user-images.githubusercontent.com/40958140/42421809-a827bee2-82a9-11e8-93b8-4ab917ea66bf.PNG)
![3 4 0 cura g code dnw](https://user-images.githubusercontent.com/40958140/42421811-aab2b540-82a9-11e8-89f6-e9269f30d289.PNG)

**Comment by ianpaschal** [comment]
> Can cura add a default setting for monoprice delta mini printer?

Unfortunately the answer to this is "No." since we don't have any non-Ultimaker printers at our disposal.

We can investigate the issue though. Although it's worth noting it sounds like it never worked, since you still had to manually edit the gcode in Cura 15.
