### ISSUE TITLE
I am printing with usb and since the update it freezes mid print & leaves everything hot (not good) will stop using for now :((

### ISSUE THREAD

**Issue by iceboxpaul** [Ultimaker/Cura#4045]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by iceboxpaul** [comment]
of to look for new software

**Comment by fieldOfView** [comment]
If you don't supply enough information, noone can help you. That's as true for Cura as for the new software. Good luck.

**Comment by ianpaschal** [comment]
Closed because no effort was taken to file an actual bug report.
