### ISSUE TITLE
Bridge walls on layers 2+3 of a bridge.

### ISSUE THREAD

**Issue by jarrodasmith** [Ultimaker/Cura#4052]
**Application Version**

3.4

**Platform**

All Platforms

**Printer**

CR-10

**Steps to Reproduce**

Select "Enable Bridge Settings" under Experimental.  Customize any of the bridge wall options (e.g. Bridge Wall Speed and Bridge Fan Speed), then select "Bridge Has Multiple Layers".

**Actual Results**

Only skin is treated with bridge settings on the second and third layer of the bridge.  Walls are treated as regular walls on layers 2 and 3 of the bridge.  This most commonly causes the edges of a bridge to sag.

**Expected results**

When you enable "Bridge Has Multiple Layers", walls should be treated as "bridge walls" on layers 2 and 3 of a bridge.  It may or may not be needed to add additional settings to customize bridge wall settings specifically for layers 2 and 3 of the bridge as you have for skin.  Inheriting the wall settings from layer 1 of the bridge may be sufficient.

**Comment by smartavionics** [comment]
Hi, thanks for your report. Could you please post images showing how the 2nd/3rd bridge layer walls are failing. Personally, I have not had any issues when the 2nd/3rd layer walls are printed using their normal settings. Thanks.

**Comment by jarrodasmith** [comment]
![img_9182](https://user-images.githubusercontent.com/30091341/42533618-fd58c5e4-844f-11e8-9b3a-46427ab06e34.jpg)
![img_9183](https://user-images.githubusercontent.com/30091341/42533619-fd6d6904-844f-11e8-9131-aecd877486cb.jpg)

**Comment by jarrodasmith** [comment]
Granted that is not the best bridge (I've got settings that do better) but clearly illustrates the issue - the center of the bridge is pretty level, but the sides sagged.  You can watch this during the print.  When the nozzle does the perimeter on the second layer of the bridge, it softens the first layers and they sag.  When it does the center (skin) where I slow things down and turn up the fan, it behaves nicely.   If I slow the whole print down and turn the fan up it behaves better but of course then you lose the benefit of custom settings for bridging...you can just print the whole thing like a bridge and it will take forever :-).  Also I print a lot of things that are 100% walls, and I feel confident that the ability to build up a few layers of wall by slowing down and turning up the fan would greatly improve those bridges.

**Comment by smartavionics** [comment]
OK, thanks for the photos. Could you please do an experiment for me? Print that same model but stop the print after the 3 bridge layers have been printed and provide a photo similar to the above. Thanks.

Interesting that you turn up the fan for the 2nd and 3rd layer skins as I get better results with no fan at all for those skins.

**Comment by jarrodasmith** [comment]
Here's a better "true" example.  This is a 100mm bridge that came out quite decent, but if you turn it over you see that from the side it actually looks much worse than it really is.  There is a "ledge" running along each edge that's about 1mm deep, where the perimeters slightly sagged as the nozzle came back over the first bridge layer at normal print speed/fan settings.  It gets *much* worse the more perimeters you have set.  This example was setup to print with just two perimeters.

![img_9185](https://user-images.githubusercontent.com/30091341/42535887-48baa830-8456-11e8-82f1-1c85fd38452c.jpg)

**Comment by smartavionics** [comment]
Sorry, that picture is hard for me to interpret. I can't really see what's happening there.

I find it very difficult to get good images of prints.

**Comment by jarrodasmith** [comment]
I want to point out a couple things that might explain the different results we are getting:  I'm using a 0.8mm nozzle with 0.4mm layers.  I'm also using a volcano-style nozzle, i.e. short and wide.  My theory is that the edge of the nozzle comes quite close to the previously printed perimeters and that is what causes the sag.  Turning up the fan mitigates this.  I wonder if I was using a more "pointy" nozzle if this issue would be less pronounced.

I'll gladly do your test.  Stay tuned.

**Comment by smartavionics** [comment]
Ah, OK, maybe you have a good point there as I am only using a 0.4mm nozzle.

BTW, the reason I use no fan for the 2nd and 3rd skins is because I found that when the nozzle is moving slowly (which I believe is required for those skins to get good adhesion) the fan just blows the air heated by the nozzle directly onto the 1st skin which makes the skin lines sag. By not having any fan, I get less sag on the skins. YMMV.

**Comment by jarrodasmith** [comment]
![img_9190](https://user-images.githubusercontent.com/30091341/42536922-0e936a9a-8459-11e8-923a-bf9207719562.jpg)

**Comment by smartavionics** [comment]
BTW, can you either build Cura from source or run a Linux version? If so, then I could look into making a version that you could test. Sorry, I can only build for Linux.

**Comment by jarrodasmith** [comment]
I think I used about 1/2kg of this yellow filament printing this model in about 100 different combinations of these settings so I'm definitely familiar with what you mean :-)  On my setup, an in-between setting for what I'll call "upper bridge skin" is best.  So I'll do 60% fan for the overall print so it can go pretty fast ~45-50mm/sec, 100% fan for the first bridge layer (10mm/sec), and something like 80% for bridge layers 2/3 so I get decent adhesion but minimize sagging of previous bridge layer(s) as the nozzle passes by.  Always a balancing act :-)

**Comment by jarrodasmith** [comment]
In theory I can build for Linux.  Currently in between machines so at this very moment I could build it at work but could not run it at home :-D

**Comment by jarrodasmith** [comment]
So I tried to get Cura to build on OSX per the directions and failed due to broken protobuf python dependencies (even inside a virtualenv stack, even with everything installed exactly per the official instructions).  So....I'll be moving ahead with Linux on my brand new Win10 box.  But I'll be on vacation until next week.  Just wanted to let you know I'm still thinking about this.  Thanks!

**Comment by Ghostkeeper** [comment]
I wonder if they were not marked as "bridge walls" on the higher bridge layers on purpose?

**Comment by Kaptn225** [comment]
Issue is still present in Cura 5.1.0

Ticking the "bridge has multiple layers" checkbox has no effect, nor do any of the settings that appear. Second and third bridge layers just get printed with regular wall settings. 

Only the first bridge layer can be changed.

https://imgur.com/a/5xpO2TH
