### ISSUE TITLE
[master] No open with entry for stl files

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#406]
So far I just opened stl files with Cura. Checked my filemanager and found this:

![cura-open-with](https://cloud.githubusercontent.com/assets/1847437/9976832/6759e870-5ef0-11e5-8575-632d1a0e6cd5.png)

I at least expected to find Cura there ("Öffnen mit"=="Open with")

---------------
Version: 15.09.82
Platform: Linux-4.2.0-10-generic-x86_64-with-Ubuntu-15.10-wily
Qt: 5.4.2
PyQt: 5.4.2
Installation using https://launchpad.net/~thopiekar/+archive/ubuntu/cura

**Comment by thopiekar** [comment]
PR #407 gives now the following result:

![cura-open-with2](https://cloud.githubusercontent.com/assets/1847437/9977863/d698cafa-5f16-11e5-846c-c646316ea87a.png)

**Comment by nickthetait** [comment]
:+1:

**Comment by thopiekar** [comment]
Already merged, so closing...
