### ISSUE TITLE
Düsengröße nicht änderbar, nach der Änderung auf 0,4 nach dem Neustart wieder 0,5

### ISSUE THREAD

**Issue by ViktorHelwer** [Ultimaker/Cura#4062]
**Application Version**
Cura 3.4.1

**Platform**
Windows 10

**Printer**
Anycubic Kossel Plus

**Steps to Reproduce**
Unter Einstellungen > Drucker >DeltaBot > Geräteeinstellungen >Extruder > Düsengröße

Die Düsengröße von 0,5 lässt sich nicht verändern! Wenn diese auf 0,4 eingestellt worden ist und Ultimaker beendet wird, bleibt nach dem neustarten der Software Düsengröße bei 0,5!
![ultimakerbug](https://user-images.githubusercontent.com/6752517/42602746-27ee1d4c-856b-11e8-895b-ab3448d42dfd.PNG)

**Comment by diegopradogesto** [comment]
English please.

**Comment by fieldOfView** [comment]
Duplicate of #3338 and #3981
