### ISSUE TITLE
Plateform .stl

### ISSUE THREAD

**Issue by ValentinPitre** [Ultimaker/Cura#4066]

**Comment by ValentinPitre** [comment]
Hello,
I would like to add my own 3D printer, should the file .stl  contain some constraints?

**Comment by diegopradogesto** [comment]
I'd say that it should be a closed non-manifold mesh and the size should be preferably not bigger than 1MB.

In any case, when you send the PR to include this to Cura, we will review the whole thing. If there is a problem with the mesh, we will reply you and ask for modifications.

**Comment by diegopradogesto** [comment]
Hey @ValentinPitre , is that enough? Do you need more help? I'll close the issue but you can always open again if you have more related questions.
