### ISSUE TITLE
Wrong Supports.

### ISSUE THREAD

**Issue by Dj-EKI** [Ultimaker/Cura#4093]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Anet A8

**Steps to Reproduce**
With 0,8 Nozzle.
![image](https://user-images.githubusercontent.com/15943202/42832342-3678826e-89f1-11e8-896a-6fa8fb2e3c21.png)

**Actual Results**
Many lines are not supported.

**Expected results**

**Additional Information**
These lines are going in a wrong direction. Layer 29 would have to be across.
![image](https://user-images.githubusercontent.com/15943202/42832906-ff97f408-89f2-11e8-9052-db0ed0ca7e92.png)

These lines that make a turn are not supported.
![image](https://user-images.githubusercontent.com/15943202/42832843-cfcce882-89f2-11e8-93d5-8fac1970e4bc.png)

Line in Air.
![image](https://user-images.githubusercontent.com/15943202/42834636-783e2be4-89f7-11e8-869a-2b71e9d982c9.png)

**Comment by diegopradogesto** [comment]
We would need some model to see this. Can you please attach the **Project File**. Be sure you use **File > Save Project...** menu.

**Comment by ianpaschal** [comment]
It could be possible to try and ensure that the bridging lines run perpendicular to support but for images 2 and 3 there's nothing that can be done. You'd have to make the support run at different intersecting angles everywhere which is not feasible.

**Comment by Ghostkeeper** [comment]
The first problem could be solved in theory but we are thinking that it's a lot of work for little gain. An easier solution for the developers is to allow modifying the direction of support lines like we allow this for the direction of infill and skin lines.

**Comment by M0Dark1** [comment]
CURA loves to start lines in thin air too. An ability to manually select a layer start point would help to mitigate this, however for what you are showing it wouldn't help. 
Being able to rotate the orientation of an individual support block could be the answer. I assume this is a complex thing for the dev team to achieve.

**Comment by Dj-EKI** [comment]
Unfortunately, I can not upload a file because Cura has already reported an error on startup. The profile could not be loaded and was reset. I'll wait until a few more versions have been released and will take another program as long.

**Comment by Ghostkeeper** [comment]
You can manually select a layer start point, sort of. It would be the Z seam position. You can set that to Custom.

We decided that we will not be implementing an automated way to rotate parts of your support differently. The complexity of selecting regions to rotate is just too great and you won't get the support lines to align nicely. So that makes this issue a won't-fix.

This issue is still open though as an alternative: https://github.com/Ultimaker/Cura/issues/3481
