### ISSUE TITLE
Application Upgrades n Suggestions

### ISSUE THREAD

**Issue by kornshadow097** [Ultimaker/Cura#4095]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Tevo Tarantula

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

Feedback for Software Upgrades:

I'd like to see nozzle sizes become part of the print setup menu vs having them stuck on the machine, because i switch nozzles on my machine all the time and dont think it should be considered a different machine due to that one option.

The side menu is a dauntingly long list. Although i enjoy the many options available I lose track of options when scrolling down the long list with small section breaks to identify the sections... I'd like to see several tabs in that space instead, one for each category ex. Extrusion sizes, Speed, Retraction,  etc.

I'd also like to see a better layer print preview that is animated as layers and as lines. Although S3D has pros and cons, their preview is very good. Cura's only shows possible zones that could come out bad...so far they have been wrong and areas it doesn't show in red print with holes or not at all sometimes... Once example is the vase mode woman and flexirex. Skin layers are much better with Cura however and I commend you for that.

I'd also like better one handed controls on the mouse...having to hold shift is not ideal and  very counter intuitive, especially since the left click does nothing... I'd say just use the left click for what shift does or something vs not using it at all.

 I'd like controls similar to that of S3D as well as an option to apply fixes to overhangs and areas that may not work in a print. Not only modifying the model its self and Showing it in the preview, but recommending speeds for fan and print etc in those specific areas to help with the print.

I'd also like more options to integrate this with Linear Advance and help determining things like acceleration and jerk settings etc in a simulated environment.

**Comment by diegopradogesto** [comment]
One by one:
1. This is possible indicating "has_variants" in the machine definition. It's the same as our UM3 works for instance. You can switch nozzles without switching printers.
2. You can play with the setting visibility and just show the settings you are interested on.
3. We implemented this already. In the layer view now you can see a horizontal slider that allows you to see the lines within a layer.
4. This depends on your preferences, of course. Some other people may prefer the current combination. This can be an improvement, to implement different mouse controls that you can choose.
5. I don't know what you mean with "controls similar to that of S3D". What kind of fixes? Support? Visual advices? The profiles are intended for that recommendations of fan and print speeds (among other settings). Some printers (such as Ultimaker) have good profiles that are tested by companies and people, and some other printers are not that good. But you can adjust as you prefer and create your own profiles.
6. Acceleration and jerk can be also adjusted, but it depends on your firmware.

**Comment by diegopradogesto** [comment]
I would suggest you to create different issues for the improvements that are not yet implemented, instead of writing down all together.

**Comment by ianpaschal** [comment]
Since these questions are answered, "Controls like S3D" is a measurable objective, and an issue ticket system is not really the place for a big idea dump like this, I'm going to go ahead and close the "issue."

The [Cura section of the Ultimaker forums](https://community.ultimaker.com/forum/108-cura-plugins/) is a much better place to do idea dumps.

**Comment by kornshadow097** [comment]
@diegopradogesto 1. I'm not sure how that works in the settings. 

2. Yes, but if i hide settings i feel like I'm being ignorant of settings ... all the settings looks useful... but  they all sound too similar and intertwined to know the right way to adjust them. Besides my main point was to organize the settings so that they can be found quickly based on the section the long list...which sometimes clicking the arrow to minimize the category eliminates the category and i literally have to mess around clicking things and opening and closing things for it to come  back (infill category did this... i had to hit search and other things to get it to  show up...it was totally blanked out)

3.yea i saw that, but i meant something more like an animated walkthrough of how it would print vs a jumpy random layer display. its impossible to get it to  go layer by layer..its pretty random and i haven't seen a way to make it go up by 1 layer at a time without clicking and manually typing a layer number one by one by one (sometimes i do this to find where a fan should start or speed should change).

4.yes, I like being able to zoom in, rotate the model  but also go up and down to see different parts of the models height without hitting shift. ex. left click and hold to make model rotate(think rotating table)and tilt up and down, then holding right mouse to move your pov in any direction leaving the model alone and only moving in x or y. no need for shift key doing it this way. seriously get a free trial to s3d and see for yourself. curas method is counter intuitive and annoying vs the simple movements in s3d.

5. I meant mouse controls like mentioned above and improvements like a model analyzer and even model orientation guide like in meshmixer. then based on the model its self and over hangs or  narrow spots etc the speeds can set recommendations based on input on past attempts and model failures or success and selecting where or how the failures occurred. Cura can be a AI based on user input and learning from settings and faults from our own experience and community shared data.

6. I know it can be set, but it cant be tested based on the model we import and tight turns etc.

Yea, I'll do that next time.

sorry, i am new. i thought i posted this in insights...

thanks

ill check out the link

**Comment by ianpaschal** [comment]
> Yes, but if i hide settings i feel like I'm being ignorant of settings ... all the settings looks useful... but they all sound too similar and intertwined to know the right way to adjust them. Besides my main point was to organize the settings so that they can be found quickly based on the section the long list...which sometimes clicking the arrow to minimize the category eliminates the category and i literally have to mess around clicking things and opening and closing things for it to come back (infill category did this... i had to hit search and other things to get it to show up...it was totally blanked out)

The upcoming "Cura Settings Guide" plugin might be able to help you, but unfortunately the truth is that 3D printing is complicated and there's a lot of settings to learn about. We've added several different methods (collapsable panels, search, setting-visibility presets) to help you navigate, or Recommended Mode to just take the "generally ideal settings", but yeah... you'll need to familiarize yourself over time. If you've found a bug though, please make an issue ticket with reproduction steps and screen shots of that specific bug.

> i meant something more like an animated walkthrough of how it would print vs a jumpy random layer display. its impossible to get it to go layer by layer..its pretty random and i haven't seen a way to make it go up by 1 layer at a time without clicking and manually typing a layer number one by one by one (sometimes i do this to find where a fan should start or speed should change).

If you have clicked the layer slider the up and down arrow keys will let you jump up and down layer by layer. The play button literally does exactly what you're asking for, animating the execution of the gcode.

> I meant mouse controls like mentioned above and improvements like a model analyzer and even model orientation guide like in meshmixer. then based on the model its self and over hangs or narrow spots etc the speeds can set recommendations based on input on past attempts and model failures or success and selecting where or how the failures occurred.

First of all, we're not going to copy mesh mixer into Cura, because, of course, mesh mixer already exists, and second of all, there's an Auto Orientation plugin which can assist with a lot of this.

> Cura can be a AI based on user input and learning from settings and faults from our own experience and community shared data.

@diegopradogesto has been working on using neural networks to estimate print time based on model size. However, you yourself said you can't figure out all of Cura's settings, do you really think AI will be able to in this case? Someday, maybe yes, but somehow I feel like it's not going to make it into the next version of Cura. 🤔

**Comment by diegopradogesto** [comment]
1. This is in the machine definition files. I don't know if the Tevo Tarantula printer allows by default to switch nozzles or not. We have this in some of our Ultimaker printers (the ones that allow changing nozzles, such as UM3, UMS5, ...)
2. I understand your point know. It would be nice if the search text field allows more intelligent filtering, such as `category:Shell top`, then just show up the settings that contains the string "top" just in the category "Shell". +1
3. You can use the play button and then you will see a simulation of your print line by line, layer by layer. You can also play with the handles in the sliders. The horizontal slider has one handle to move the lines. The vertical slider has two handles that you can move independently to select a range of layers. Also you can click on any of the handles in both sliders and it becomes blue, then you can use arrow keys (UP/DOWN for the layers and LEFT/RIGHT for the lines) to move one by one, or use SHIFT+<arrow key> to move it 10 by 10.

For the rest of the points, I would really love to have an ULTRA SMART slicer capable to do that. Using data collected from the users for automatically slice without setting any setting. I'm doing some tests with NN to estimate printing time, but this is just a very small part of the whole thing. But I would love if Cura moves towards that, but it's not my decision.
