### ISSUE TITLE
[3.4.1] Temperatures in Monitor do not update

### ISSUE THREAD

**Issue by sacks21** [Ultimaker/Cura#4105]
when sending to print the temperatures in the cure do not increase but in lcd they rise

**Comment by diegopradogesto** [comment]
Please fill out the template that appears when you create the issue. We need to know more details such as printer type, maybe pictures, ... Otherwise this issue will be closed due to lack of information.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3741. Please look there for more information.
