### ISSUE TITLE
Software blinks on Dell Inspiron with Windows 7

### ISSUE THREAD

**Issue by mariogayoso** [Ultimaker/Cura#4107]
Not much to add  but is anybody else experiencing White Blinking on your laptop with Windows 7?
Maybe is a video card issue, resolution, or drivers?

Please let me know if anybody knows how to fix this.

Thanks

Mario!

**Comment by diegopradogesto** [comment]
Is this related with Cura? In this case, please fill the template that appears when you create a new issue. Otherwise we can't analyse it. Please provide also useful information such as pictures, video, graphic card model and version, ...
