### ISSUE TITLE
The Application Clicking Is not right

### ISSUE THREAD

**Issue by gxldCptRick** [Ultimaker/Cura#4109]
**Application Version**

v3.4.1

**Platform**

OS: Windows 10 Pro
Intel Core i7-7820HQ

**Printer**

Monooprice Mini v2
**Steps to Reproduce**

Launch Application try to select any item on the menu in particular the top right items
**Actual Results**

the point in which you click does send the click event, in fact, the click event is launched at a much higher position approximately 10px higher
**Expected results**

have the click event register to the gui item that i clicked
**Additional Information**

**Comment by fieldOfView** [comment]
Duplicate of #2068. You need to update your Intel HD Graphics driver to a newer version.

**Comment by diegopradogesto** [comment]
Please @gxldCptRick confirm that updating your driver fixes the issue. If not, you can reopen the issue again.

**Comment by gxldCptRick** [comment]
thank you guys i updated the driver and it has started working correctly
