### ISSUE TITLE
15.09.83: Gap Filling

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#411]
I have tried different combinations of these related settings, and seen no attempt to fill these small gaps. Repetier visualizes the same.

![image](https://cloud.githubusercontent.com/assets/12439543/9993882/de264a16-603f-11e5-86a3-1d207f39ba45.png)

**Comment by nallath** [comment]
Sounds like a Cura engine issue.

**Comment by awhiemstra** [comment]
This should be fixed for the next build.
