### ISSUE TITLE
Disable saving gcode before gcode has been generated

### ISSUE THREAD

**Issue by is05458** [Ultimaker/Cura#4112]
I'm using cura 3.4.1 at Mac and Windows 7 but I have the same error warning when I try to export a model to gcode. It happens with all models.

If I use Cura 15.04.6 with Windows 7 I don't have this issue and I can export correctly the gcode file. But I want to use the last version with more parameters.

I reviewed the log application but it doesn't seem to help.

-- edit: the user has not realized he had to hit [ Prepare ] first

**Application Version**
3.4.1

**Platform**
macOS Sierra & Windows 7

**Printer**
Anycubic i3 Mega

**Actual Results**
Warning : Could not save to [file_location] : None.

**Comment by diegopradogesto** [comment]
This error is raised when there is a PermissionError, so probably you are trying to save to a location where you don't have permissions. Try another folder and see if it works.

**Comment by is05458** [comment]
Hi Diego,
I've tried on several folders with the same result.
I've uninstalled 3.4.1 and installed 3.3.1 and it works fine. So I don't think that's a folder permission issue.

Thx!

**Comment by ianpaschal** [comment]
^That doesn't really prove that it's not. Can you try what Diego suggested anyway?

**Comment by rxharr6** [comment]
I had this issue when I tried to save before selecting "prepare" first time I tried to use the app.

**Comment by BagelOrb** [comment]
@rxharr6 is right. This error happens when you try to export to gcode before you have sliced.

- Turn off slice automatically
- load model
- File > Export ... > select gcode > selection location where you could save the gcode.

**Comment by BagelOrb** [comment]
One choice, two options:

- make export as gcode unselectable when the build plate is empty or when a setting has changes (just like layer view)
- Selecting Export > gcode slices for you wit hthe current settings.

**Comment by ianpaschal** [comment]
We discussed this as a team and we're not going to change the behavior here. We also don't really consider it a bug because saving an empty gcode file before you've generated gcode is very much "expected behavior."

We thought it might be nice to also not generate the empty file but it quickly became obvious we'd need to write a pre-writer for the file since we don't know that the file job failed until after creating the file on disk, attempting to put gcode into it, and failing. This is too much work for not enough gain.

In the process we did discover another bug though which is that if you generate gcode, then move your model, the old gcode is not erased from memory until new gcode replaces it, meaning if you forget to hit prepare you might save the old gcode a second time thinking it's taking the new position into account.

This one is an easy fix, so we went ahead and changed it.

**Comment by ianpaschal** [comment]
Change was made in #4185

**Comment by fieldOfView** [comment]
I am (still) convinced that saving geometry/projects and saving sliced results (gcode or ufp) are two entirely different things and should not be included in the same "Save as..." command. If they were split into two commands, this issue would be a lot simpler to fix.

**Comment by ianpaschal** [comment]
This is true, and we've been discussing lately how to break apart the various "save", "save as", "export" nomenclature, but we consider this ticket to be a more distal issue.

**Comment by BagelOrb** [comment]
Well it is in some sense expected behavior, but it is still bugging new users. For them it will be a mystery why their gcode doesn't do anything when they give it to the machine. I would still consider this a bug - even if it is a minor bug.

**Comment by diegopradogesto** [comment]
We just add this PR https://github.com/Ultimaker/Uranium/pull/374 that shows some information to the users when something went wrong saving files. I know that it doesn't solve the problem, but at least the users will be aware that the gcode is empty.

**Comment by Ghostkeeper** [comment]
The splitting of nomenclature is implemented in Cura 3.5. See if you think that this fixes the issue.

**Comment by BagelOrb** [comment]
If I now try the steps it gives an error "Please generate gcode before saving."
Good!

Little remark: I think it should be "Please **prepare** gcode before **exporting**."
The button at the bottom right is called [Prepare] and the item selected in the menu is called [Export...]

**Comment by Ghostkeeper** [comment]
Agreed. I've corrected that text.

**Comment by lquochuy** [comment]
It is simply to click on 'Slice' button on the right bottom then it allows to save.
