### ISSUE TITLE
Add custom material

### ISSUE THREAD

**Issue by ValentinPitre** [Ultimaker/Cura#4113]
Hello,
I'm adding a new brand of 3D printer on Cura. I would like to add custom materials. I've seen that there is specific a folder on windows (C:\Program Files\Ultimaker Cura 3.4\resources\materials) but none on github.

Thank you for your help

**Comment by fieldOfView** [comment]
See the https://github.com/ultimaker/fdm_materials repository for the material files that are included with Cura.

Note that you can create materials from inside the Cura application (See the Materials pane of the Preferences)
