### ISSUE TITLE
Cura: Change Filament Script does not extract Filament

### ISSUE THREAD

**Issue by Sislar** [Ultimaker/Cura#4114]
**Application Version**
3.4.0

**Platform**
Windows 10

**Printer**
Ender 3

**Steps to Reproduce**
Create any valid print,  do go to postprocessing and add "Change filament at layer"
Keep the defaults
   initial retraction  30mm
   retraction            300mm
save as "gcode"

**Actual Results**
The printer pauses for filament change at the correct spot but the filment moves forward (well
not really as it can't go forward that much) instead of backward

Gcode is inserted as follows
M600 E30.00 L300.00 ; Generated by FilamentChange plugin

**Expected results**
Filament should be retracted I edited the gcode and changed
M600 E30.00 L300.00 ; Generated by FilamentChange plugin
to
M600 E-30.00 L-300.00 ; Generated by FilamentChange plugin

With this change the filament retracted correctly.

**Comment by diegopradogesto** [comment]
You're right, in Marlin firmware this is how it should be: http://marlinfw.org/docs/gcode/M600.html
