### ISSUE TITLE
Cura Projects not showing on the Recent Files list

### ISSUE THREAD

**Issue by SuperconductingCarbon** [Ultimaker/Cura#4129]
**Application Version**

3.4.4
**Platform**

Linux a6 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Printer**

Creality CR-10S
**Steps to Reproduce**

Save as a  Project.  It does not show in the "Recent Files" list. 
**Actual Results**

Only .stl files show in the "Recent Files" list.
**Expected results**

Expect to see the Project files and well as STL's in the Recent files list.
**Additional Information**

<3 Cura!

**Comment by alekseisasin** [comment]
@SuperconductingCarbon , Thank you for your feedback. 
We will implement this improvement. 
DEVS: CURA-5601

**Comment by Ghostkeeper** [comment]
This should be implemented for the next release.
