### ISSUE TITLE
Z Seam user specified position different on 3.4.1 from 3.3.1

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4131]
**Application Version** - CURA 3.4.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Generate a gcode with the following settings:

- Z Seam Aligment: User Specified

- Z Seam X: 0

- Z Seam Y: -100

**Actual Results** - The Z Seam is not on the same position of the same model generated on Cura 3.3.1

**Expected results** - The Z Seam position on the indicated coordinates, like the Cura 3.3.1

![screenshot_5](https://user-images.githubusercontent.com/12901952/43196213-2e7e8766-8fff-11e8-95c9-255358a795be.jpg)

[Cura_Projects_341_331.zip](https://github.com/Ultimaker/Cura/files/2227597/Cura_Projects_341_331.zip)

**Comment by amagr0** [comment]
And also on the 3.4.1 the Z Seam is not vertical aligned.

![screenshot_1](https://user-images.githubusercontent.com/12901952/43205146-99a8f1c8-901a-11e8-9f19-6936c7a94a98.jpg)

**Comment by smartavionics** [comment]
Hi, I just sliced your 3.4.1 project using my master branch Cura (with my mods) and the z-seam is where it should be and it looks reasonably aligned.

![screenshot_2018-07-25_15-16-35](https://user-images.githubusercontent.com/585618/43206481-c44103dc-901d-11e8-8e14-97db88be2177.png)

I also sliced it with a 3.4 based release (without my mods) and the result looks pretty much the same.

Sorry, I cannot reproduce the issue from your project file.

**Comment by diegopradogesto** [comment]
Loading the file Piramide_50_Cura331.curaproject.3mf, this is the result in 3.3.1:
![image](https://user-images.githubusercontent.com/15830521/43275839-401c2726-9103-11e8-8690-4dbb6f4411a4.png)

And this is what I see in 3.4.1:
![image](https://user-images.githubusercontent.com/15830521/43275875-58075162-9103-11e8-9d21-8c827bfe54f2.png)

Scrolling all the layers, they seem to be the same, so I don't see any issue here.
