### ISSUE TITLE
Starting print over wifi is not working for Ultimaker S5

### ISSUE THREAD

**Issue by flodenh** [Ultimaker/Cura#4133]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Ultimaker S5

**Steps to Reproduce**
I have added my new Ultimaker S5 printer and it appeared nicely in the Connect to Networked Printer list. So I picked it from this list, uploaded a model that was sliced. 

**Actual Results**
The button for sending to the printer does not appear. 

**Expected results**
The button for sending directly to the printer should have appeared

**Additional Information**
When I navigate to Printers->Settings->Manage Printers and choose Connect vis Network on my Ultimaker S5 I get back to the "Connect to Networked Printer"-screen. Here I see the printer with and IP-address and firmware version but also with the following text: "This printer is not set up to host a group of Ultimaker 3 printers" - see attached screenshot. I have tried setting it up on to different computers with the same result
![screenshot](https://user-images.githubusercontent.com/41697487/43213868-f2410466-9037-11e8-852a-20203c905a4d.jpg)

**Comment by diegopradogesto** [comment]
This means that your S5 is connected to a printer group but it is not the host of this group. Do you have more Ultimaker printers (UM3 or UMS5) in the network?

**Comment by flodenh** [comment]
No this is my only one. When I open a browser, enter the IP-address of the printer and click Cura Connect I get to a strange looking page that tells that the printer is part of a group and the group host is my machine - see attached image. Guess this is more of a printer issue than a Cura issue...
![screenshot](https://user-images.githubusercontent.com/41697487/43274286-15b8418a-90ff-11e8-8119-8496b947a8f4.jpg)

**Comment by flodenh** [comment]
When I press the "Go to group" button it just take me to the exakt same page.

I will try your suggestions. Thank you for your help!

**Comment by flodenh** [comment]
The Cura Connect Reset did the trick. Thank you for your help!

**Comment by diegopradogesto** [comment]
Glad to help!
