### ISSUE TITLE
How to create curapackage files

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#4134]
Hey guys,

do you have any info around the curapackage file?
Looked for docs what is new in this fileformat, but could not find anything.
Also in Uranium there is still the old script for building curaplugin/umplugin files.

An example file would be great, too.

Thanks!

**Comment by ChrisTerBeke** [comment]
There's a Wiki page about it.

BUT..... we'll launch a managed service for this very shortly to build and distribute your packages from your source files. I can give you beta access if you want to try it out soon.

**Comment by fieldOfView** [comment]
Gimme, gimme!

**Comment by Kriechi** [comment]
Me too!

**Comment by ChrisTerBeke** [comment]
Expect an invite in your inbox in about 2-ish weeks :)

**Comment by thopiekar** [comment]
Awesome 🤘

**Comment by fieldOfView** [comment]
It is not too hard to reverse engineer a current package...

**Comment by thopiekar** [comment]
Sure, but if people say that there is a document describing it already, why should I reverse engineer it?

**Comment by ChrisTerBeke** [comment]
https://github.com/Ultimaker/Cura/wiki/Creating-Packages

**Comment by ChrisTerBeke** [comment]
Closing this as ticket (we can still continue to discuss about packages).

**Comment by thopiekar** [comment]
Thanks!

There is the first question already. Does the directories name inside ```plugins``` correspond to the plugin's id?
So ```"MyPlugin" == "ExamplePackage"``` or is there no convention how the directory inside ```plugins``` is called?

![image](https://user-images.githubusercontent.com/1847437/43367997-260efad4-9356-11e8-8822-1c1e69eefe20.png)

**Comment by ChrisTerBeke** [comment]
Yes, it does :)

Our upcoming tooling will check the directory names and required filenames in there as well (and tell you what's wrong if one of them is not there).

**Comment by thopiekar** [comment]
Ok, and what does the 2.7.0+ mean? Is there a check per Cura version? Is it possible to roll new releases for older Cura versions out? Eg. only with bugfixes?

**Comment by ChrisTerBeke** [comment]
You can indicate which Cura versions a release of your package is compatible with. You can simply make a new release of your package with bug fixes and not click the toggle for a newer Cura version. It's very App Store / Google Play like :)
