### ISSUE TITLE
wall line width problem/bug, cursor selection bug, exitting search bug. 

### ISSUE THREAD

**Issue by kornshadow097** [Ultimaker/Cura#4139]
**Application Version**
3.4.1

**Platform**
windows 10

**Printer**
tevo tarantula

**Steps to Reproduce**
 1)  look at the print setup area with 3 categories visible "wall line width, inner and outer wall line width"
2)click anything with a number in the text box and try to erase a number and type another in its place with auto slicing on.
3)hit search, look for something and then hit the x to close out of search area

**Actual Results**

1)if i set wall line width to 0.8mm, inner and outer line width turn to that same number, but lets say i dont have the wall line width option displayed and only use inner and outer wall width.. that would
tell me that my line width will be 0.8mmx2 = 1.6mm but it prints as 0.8mm. In the slicer preview it also shows 2 sections...both looking split in two wall sections. But that is not possible as 
having it set to 0.8mm line width with a 0.8mm nozzle is the minimum multiple and it displaying 2 line widths together as if you can choose a smaller section but can't. but showing the wall sizes together 
leads you to believe the inner wall and outer wall would be added together to creata a solid wall... but it doesnt..its confusing.

so either the app has a bug or the language used here makes no sense when trying
to figure out what will print if you use all three of these settings and like to
mostly use wall line width but sometimes want to adjust inner and outer walls so have them all visible..even having just the 2 of 3 available would be confusing though.  only one that makes sense is "wall line width"

2) after clicking layer height or initial lline width... possible any other option
right before it decides to auto slice... it removed the cursor from the box you 
just selected and tried to slice... which makes you have to reclick it again..this
especially happens after you click on a number and begin to change it like 80,
i click and remove the 0 and am about to put in 5 to make it 85 and now the cursor
is no longer selecting the box...

3)After hitting search and doing what you're going to do and you click X to 
close search within the print setup area it just turns black and partially 
shows a few items but the scroll bar flickers up and down and eventually it all 
loads but usually you have to move the scroll bar down the menu so you can see
other options and then let go and drag it up again and the menus items start appearing
again.

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment]
1
----
I'm not sure what your bug report means to say. Could you write down clearly what you're seeing and what you're expecting to see, and how those two are different?

> i dont have the wall line width option displayed and only use inner and outer wall width.. that would
tell me that my line width will be 0.8mmx2 = 1.6mm but it prints as 0.8mm

No, it would tell you that your line width will be 0.8mm, not 1.6mm. Your wall thickness will be 1.6mm though, consisting of two lines. You can adjust the two lines to have different widths but in this case they will be the same. Do you think this language is the confusing part?

2
----
I've also seen this but it's hard to reproduce reliably. If you know the precise reproduction steps, please tell us! It doesn't seem to happen always and usually I can type fine.

3
----
This is a known issue. For 3.5 we've improved the performance of this by a factor of 8, but it's not gone yet. There are just a lot of interface elements to create, so it's a difficult problem.
