### ISSUE TITLE
Package install

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4146]
**Application Version**

3.4.1

**Platform**

Windows 10

**Printer**

not applicable

**Steps to Reproduce**

Toolbox/browse packages
select solidworks
install

**Actual Results**

Goes through the install procedure etc. Doesn't appear to show any problems.
Once Cura is restarted, the package doesn't show.
Back in the package browser, Solidworks shows as "install" not "installed"
And there is an extra button in Solidworks to "Export to Cura". Click on it and Solidworks starts Cura, but the file conversion the package is supposed to do, doesn't happen.

**Expected results**

Expected to see the Solidworks package option in the Extensions menu.
Back in the package browser, Solidworks shows as "installed" not "install"

**Additional Information**

This package installed into Cura in the previous version, but did not show anything in Soldidworks itself.

This time, although it does not appear to install into Cura, there is now an extra button in Solidworks to "Export to Cura"

The screenshots were taken in order of procedure to install package and try to use.

![screenshot 1](https://user-images.githubusercontent.com/18093484/43320932-3792d344-91a2-11e8-8fa3-96c92d48fbcc.png)
![screenshot 2](https://user-images.githubusercontent.com/18093484/43320933-37b1344c-91a2-11e8-8c7c-db125b218bd1.png)
![screenshot 3](https://user-images.githubusercontent.com/18093484/43320934-37d4201a-91a2-11e8-9b8a-19045c5c5f6b.png)
![screenshot 4](https://user-images.githubusercontent.com/18093484/43320935-37fb4852-91a2-11e8-8a6b-a95aa374d24f.png)
![screenshot 5](https://user-images.githubusercontent.com/18093484/43320936-383ae2e6-91a2-11e8-997a-7021f73d26a4.png)
![screenshot 6](https://user-images.githubusercontent.com/18093484/43320937-38a82126-91a2-11e8-98a2-91675bb488c0.png)
![screenshot 7](https://user-images.githubusercontent.com/18093484/43320939-3911c284-91a2-11e8-8da1-5940e54e0cf9.png)
![screenshot 8](https://user-images.githubusercontent.com/18093484/43320940-398abaae-91a2-11e8-9987-2794b11df4c3.png)

**Comment by FynDestiny** [comment]
Hi
Sorry for late response.
It appears to have installed properly now.
I just tried to upload the log file, but it's too big

**Comment by diegopradogesto** [comment]
OK, no worries, let me know if it still happens.
