### ISSUE TITLE
resize bug on os x 

### ISSUE THREAD

**Issue by sybold** [Ultimaker/Cura#415]
15.09.83
resizing the window on a retina macbook pro makes the 3d view change size.

<img width="1285" alt="screen shot 2015-09-21 at 19 59 21" src="https://cloud.githubusercontent.com/assets/1087890/10000322/b78e7836-609b-11e5-942a-62d170a11c34.png">

<img width="1047" alt="screen shot 2015-09-21 at 19 59 12" src="https://cloud.githubusercontent.com/assets/1087890/10000323/b791167c-609b-11e5-88cf-271ec5d751fa.png">

**Comment by awhiemstra** [comment]
Looks like there is a missing correction for pixel density somewhere in the resize code. I will have a look at it.
