### ISSUE TITLE
Slice Lines in Air

### ISSUE THREAD

**Issue by Dj-EKI** [Ultimaker/Cura#4155]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Anet A8
Ultimaker 3

**Steps to Reproduce**
It produces lines in the air. (Layer 71, Object Rotate 90°.)
![image](https://user-images.githubusercontent.com/15943202/43364240-cd7ce406-9316-11e8-93cf-f042dfdaeeec.png)

From layer 28 to layer 29, the lines are wrong. No support. (Object in default Position)
![image](https://user-images.githubusercontent.com/15943202/43364305-e0441702-9317-11e8-9a54-a5be90ffb633.png)

**Additional Information**
I had already created a report for you, but this time I can upload a project file.

[CFDMP_RadioLenovoLinks.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2238603/CFDMP_RadioLenovoLinks.curaproject.3mf.zip)

I have now made a few advanced settings to try to fix this problem, but I expect from a program that the default will work fine too.

**Comment by smartavionics** [comment]
You need to enable the support interface. Here's some example settings:

![screenshot_2018-07-29_09-29-50](https://user-images.githubusercontent.com/585618/43364441-1c8e2fa0-9312-11e8-8368-dbc2bb582c99.png)

**Comment by Dj-EKI** [comment]
Thanks, a problem is fixed. The airlines are unfortunately still to fix.

![image](https://user-images.githubusercontent.com/15943202/43364768-eca02064-9320-11e8-8044-e4ce58453276.png)

**Comment by smartavionics** [comment]
Sorry, I can't see where that part is on the model, please post an image that isn't so zoomed in.

**Comment by Dj-EKI** [comment]
It produces lines in the air. (Layer 71, Object Rotate 90°.)

**Comment by smartavionics** [comment]
Please post another image not so zoomed in because I cannot recognize that part of the model from the image above.

**Comment by Dj-EKI** [comment]
![image](https://user-images.githubusercontent.com/15943202/43364885-c1491918-9323-11e8-80eb-179828353c62.png)

**Comment by smartavionics** [comment]
Thanks.

**Comment by Dj-EKI** [comment]
If I use tree, then I could fix this error. But it does not do too much support and some of it is not very good.

**Comment by smartavionics** [comment]
![screenshot_2018-07-29_10-45-43](https://user-images.githubusercontent.com/585618/43364967-97fd9324-931c-11e8-90ef-bb975c757880.png)

**Comment by Dj-EKI** [comment]
Thanks, Support Density fixes my mistake. This issues can be closed.

**Comment by smartavionics** [comment]
Great, glad it's fixed. I can't close this issue but you can do that. Cheers!

**Comment by Dj-EKI** [comment]
Unfortunately, I still have a problem. Why is my support not filled.
![image](https://user-images.githubusercontent.com/15943202/43365222-8367f046-9329-11e8-89af-0852f998033c.png)

**Comment by smartavionics** [comment]
You have set support density to 2%!
