### ISSUE TITLE
Does this animation require additional plugins?

### ISSUE THREAD

**Issue by jianqingHuang** [Ultimaker/Cura#4160]
I found this cura 3.4.1 version to have an animation that plays the print track. Does this animation require additional plugins?The version I compiled from the master branch on github is missing this stuff.

![plugin](https://user-images.githubusercontent.com/39265427/43405371-40630690-944c-11e8-8968-8fe039e02478.png)
![Uploading plugined.png…]()

**Comment by fieldOfView** [comment]
Your layer view is in "compatibility mode". This mode does not support the simulation.

Compatibility mode is used either because your gpu(-driver) does not support OpenGL 4.1, or because you have forced Cura to use this mode in the General preferences.
