### ISSUE TITLE
Z position ignored when slicing

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4166]
**Application Version**

4.3.1

**Platform**

Windows 10

**Printer**

[CCR10_balance.curaproject.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2247205/CCR10_balance.curaproject.curaproject.3mf.zip)

**Steps to Reproduce**

Add STL
change Z axis, in my case +10
Slice

**Actual Results**

Solid View, after slicing, shows item in expected position, Z10.
![screenshot 33](https://user-images.githubusercontent.com/18093484/43490241-c5d08b1a-9517-11e8-9f79-55dc442e0fa5.png)

Layer View shows item starting a Z0
![screenshot 32](https://user-images.githubusercontent.com/18093484/43489243-3f4aa326-9514-11e8-941e-0491aa52d61e.png)

**Expected results**

Layer View should show item starting a Z10
This pic (taken before slicing), shows where I expect the Layer View should show the item.
![screenshot 31](https://user-images.githubusercontent.com/18093484/43489241-3f2b933c-9514-11e8-8b51-cee5b0b1dde0.png)

**Additional Information**

 I want to print one item on top of another, using a different colour.
Unfortunately my printer has only one hot-end, so I have to print in two or more stages to complete my print ( I don't want to glue items together if I can print one atop another ).
With the ability to position an item at a higher Z axis, as you can in Cura, makes my print possible.
Unfortunately I don't know enough about gcode to edit the file to correct this.

**Comment by fieldOfView** [comment]
See the setting "Remove Empty First Layers" in the Mesh Fixes category.

**Comment by FynDestiny** [comment]
Did as you suggested. But it did not slice all of the item, it missed off the top few laters

**Comment by Ghostkeeper** [comment]
The missing layers at the top have been fixed in 3.5.

**Comment by fieldOfView** [comment]
Was this fixed post-beta, or should the fix be included in the beta?
