### ISSUE TITLE
15.09.83: Crash on rotate part

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#417]
I rotated my model, then chose layer view. I saw two progress bars, both processing layers, then like you see here, the old layer data remained with the new, and cura crashed verbosely:

![image](https://cloud.githubusercontent.com/assets/12439543/10010105/a6c48a3a-60ab-11e5-9393-886609226ce1.png)

**Comment by iakapulko** [comment]
Agree. But, in my case, Cura just shutdown, whithout any error log.
