### ISSUE TITLE
Layer view does not account for floating objects

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4172]
**Application Version**

4.3.1

**Platform**

Windows 10

**Printer**

[CCR10_Border.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2249090/CCR10_Border.curaproject.3mf.zip)

**Steps to Reproduce**

Load STL
Set Z height
Uncheck "Remove Empty Layers First"
Slice

**Actual Results**

This pic shows what happened.
If you look at the shadow at the back of the print, you can see the top of the domes that was not sliced.
![screenshot 37](https://user-images.githubusercontent.com/18093484/43517454-a3463b12-9580-11e8-9dd8-f57829e0015f.png)

**Expected results**

Expected all of the STL to be sliced.

**Additional Information**

If you increase the Z to 5 ( because my "border STL" is only 2mm thick ), you can see in this pic, there is no Layer data to display. It appears that the +Z is deducted from the overall project height prior to slicing.
![screenshot 38](https://user-images.githubusercontent.com/18093484/43518192-2c746524-9583-11e8-8514-a14bb1a2cdca.png)

It would be easier to treat the project as though the "Remove Empty Layers First" is checked.
Then, if the user unchecks "Remove Empty Layers First", run an algorithm on the gcode to add the +Z position, before displaying the "Layer View".
This should make the process easier to do that try to include the +Z into the gcode beforehand.

( I don't intend to step on anyone's toes, but I have a programming background, and this is how I would have approached this option in Cura  )

**Comment by ianpaschal** [comment]
This is indeed a bug where it looks like the slicer is only slicing up to the height of the model. If the model is floating, say, 1mm, then it stops slicing 1mm before the top because it's reached the height of the model.

>It would be easier to treat the project as though the "Remove Empty Layers First" is checked.
Then, if the user unchecks "Remove Empty Layers First", run an algorithm on the gcode to add the +Z position, before displaying the "Layer View".
>This should make the process easier to do that try to include the +Z into the gcode beforehand.

This we are not going to do. If you want to make gcode changes later you can use a post-processing script, but we're absolutely not going to make multiple passes on the gcode. Features requiring this have been proposed in the past and rejected because it will slow the software to a crawl and often introduce recursive errors. Guessing and checking is also just bad programming most of the time.

The correct fix is to slice up to the z = highest point from the build plate, not z = model height.

**Comment by fieldOfView** [comment]
I have a hunch that this is a bug in Layer View, and that the actual gcode is fine. Could you check by saving the gcode and loading it back in?

Something like that the layer data used for layer view contains the empty layers that are skipped in the gcode.

**Comment by ianpaschal** [comment]
Hmm good call Aldo. It sounded a bit crazy in my head that we would only slice to the model height regardless of transformations, but it did look that way.

**Comment by FynDestiny** [comment]
Thank you for your responses.
Yes, it does appear that the fault is in the Layer View. I loaded the gcode as suggested, and it appears to start at Z1 and completes the whole item.
I have just checked it against the "all-in-one" version of my project, and the "border" part starts at layer 15 in both versions of projects.

Even though that is not affecting the actual gcode, it's definitely giving that feeling when looking at it in Layer View, you can see my dilemma in issuing this thread.

**Comment by FynDestiny** [comment]
Oh, on a different note, when you load a project, and it asks if you want to "remember my choice" in the "Open project file" pop-up window. It doesn't "remember my choice", and asks every time you load a project file.

**Comment by ianpaschal** [comment]
Please do not stick new bug reports into the comment thread of another issue.

**Comment by FynDestiny** [comment]
Sorry Ian. It just popped up when I was looking into this one.
I'll create another thread, if I can't see one.

**Comment by ianpaschal** [comment]
I'll investigate tomorrow but since the gcode has the right number of layers I think it's the layer view's slider which is incorrectly interpreting what to set its own "max" value to.
