### ISSUE TITLE
jupe sans fil

### ISSUE THREAD

**Issue by Snipersdimages** [Ultimaker/Cura#4174]
Bonjour,
Je ne sais pas si le Français est lisible chez cura, mais je ne maîtrise pas assez bien l'Anglais pour m'exprimer dans cette langue.
Je voulais vous suggérer de rajouter un fil à la jupe (bordure ou radeau) de démarrage, pour forcer le collage de l'impression avant de la construire. IL y a souvent un fil de quelques centimètres qui n’adhère pas au plateau au début de l'impression. Ce fil se ballade sous la buse jusque ce qu'il soit collé avec l'impression ou sur la buse elle même.
Ce fil est plus énervant que nuisible à la qualité du produit final, mais il suffirait de coller le début de l'impression, au point de base avec un gros point de résine pour l’empêcher de se promener sous l'impression en cour.

**Comment by ianpaschal** [comment]
Utiliser Anglais ici SVP. Je parle un peut Francais mais je pense c'est seulement moi dans Cura team. Si vous n'utilisez pas le template d'issue et en Anglais, je dire fermer le ticket.

**Comment by ChrisTerBeke** [comment]
Baguette?

**Comment by fieldOfView** [comment]
Omelette du fromage!

**Comment by ianpaschal** [comment]
Galette complete!

**Comment by ChrisTerBeke** [comment]
Google Chrome suggested me to translate this page :P
