### ISSUE TITLE
[3.4.1] Send gcode doesn't works when lowercase

### ISSUE THREAD

**Issue by GMagician** [Ultimaker/Cura#4178]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Custom Prusa i3 MK2S DIY clone

**Steps to Reproduce**
Select "control" tab and type any gcode command in lowercase into "send gcode" field

**Actual Results**
Nothing happens

**Expected results**
Printer executes command

**Additional Information**
None

**Comment by ChrisTerBeke** [comment]
We just send the exact text to the printer, so probably the firmware doesn't understand lowercase then.

**Comment by ianpaschal** [comment]
^I think Chris is right but not sure how we'll be able to test this with our UM3s.

**Comment by ChrisTerBeke** [comment]
We're not, it's a USB only feature.

**Comment by ianpaschal** [comment]
Well yeah so... won't fix?

**Comment by Ghostkeeper** [comment]
Fixed, because I'm spending more time by updating the status about this ticket than actually typing `.upper()` somewhere.
