### ISSUE TITLE
[3.41] Cura exits out when opening STL files

### ISSUE THREAD

**Issue by Wtacey18** [Ultimaker/Cura#4179]
3.4.1

Windows

New matter Mod-t

When dragging and dropping, opening from the file and opening in Cura

Cura exits out and does not run again.
The file should open.

Log:
[cura.log](https://github.com/Ultimaker/Cura/files/2255328/cura.log)

**Comment by diegopradogesto** [comment]
It seems to be something related with the Arranger trying to arrange the model in the buildplate. I will investigate further.
