### ISSUE TITLE
Slicing starts at each change of position while holding the button

### ISSUE THREAD

**Issue by iakapulko** [Ultimaker/Cura#418]
During the rotation of the object along the axes, slicing runs each time you change the degree of tilt. All this time the mouse button is pressed. The log is no issue, but i can make a small video, if necessary.

**Comment by iakapulko** [comment]
Update: During the rotation at the bottom there is the inscription "Slicing", then within a second start slicing (percentage of completion). Even if changes were not made (+15 degrees, and return to the original state in one clamping mouse) slicing still starts.

**Comment by nallath** [comment]
Videos are always good :) helps us a lot.

**Comment by iakapulko** [comment]
https://www.dropbox.com/s/zkybc4wbq8ua5eo/cura%20slicing.exe?dl=0 Play with a fullscreen mode.

**Comment by awhiemstra** [comment]
Hmm, we postpone platform physics processing while performing an operation, but not slicing it seems. It should be fairly simple to fix.

**Comment by nallath** [comment]
That was a really, really silly bug. All the implementation was there, it just wasn't called. Ever.
