### ISSUE TITLE
[Master] Variables in string settings not filled in anymore

### ISSUE THREAD

**Issue by KangDroid** [Ultimaker/Cura#4181]
**Application Version**

Branch: Master

**Platform**

MacBook Air macOS High Sierra 10.13.6, with Python3

**Printer**

All, Including Ultimaker series. 

**Steps to Reproduce**

1. Make some printer profile(either pre-configured Ultimaker, or custom FFF Printer, else.)
2. Add some variable object like : 
    M109 S{material_print_temperature_layer_0} Or {material_print_temperature} to Start Gcode
3. Load any 3d Model(I've done STL) and start slice.
4. See the results and log.

**Actual Results**

That variable, material_print_temperature_layer_0 or material_print_temperature should changed with value that we set, but result just came out like:
 "M109 S{material_print_temperature_layer_0}", without changing variable to actual value.
For my settings, I have set those two variables to 200. Without heating GCode it works well.

Just something with variable makes this error.

**Expected results**

Variable should changed to its value, for me, it should have changed to 200.

**Additional Information**

: Looks like putting EXTRUDER variable(not bed temperature, etc) objects to Extruder start/end gcode seems like working, but not Printer start/end GCode. Maybe I misunderstood functions in cura?

: Extruder variable is working on extruder start/end GCode, but we cannot put bed temperature variable in extruder start/end code so we still need to figure out why variable objects are not working on printer start/end Gcode

: I changed get_value functions in https://github.com/Ultimaker/Cura/blob/master/plugins/CuraEngineBackend/StartSliceJob.py to https://github.com/Ultimaker/Cura/blob/3.4/plugins/CuraEngineBackend/StartSliceJob.py . I just copy get_value function from 3.4's branch to master branch and it solved problem. Maybe it has to do with StartSliceJob.py

And the log was:
2018-08-03 14:19:55,186 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [219]: Starting to slice...
2018-08-03 14:19:55,186 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend.slice [236]: Going to slice build plate [0]!
2018-08-03 14:19:55,828 - WARNING - [Thread-1] CuraEngineBackend.StartSliceJob.get_value [68]: Unable to replace 'material_print_temperature_layer_0' placeholder in start/end g-code
2018-08-03 14:19:56,168 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onStartSliceCompleted [422]: Sending slice message took 0.9822251796722412 seconds

**Comment by diegopradogesto** [comment]
I did a fix (#4199) that hopefully fix the issue. Can you please try it?
