### ISSUE TITLE
"Support Blocker" preventing Slicing in "One at a Time" Print Sequence

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4193]
**Application Version**

4.3.1

**Platform**

Windows 10

**Printer**

Creality CR-10S

**Steps to Reproduce**

Load multiple models.
Set Support Blocker where desired.
Switch to "One at a Time" Print Sequence.
Slice.

**Actual Results**

Slicing starts, gets about half way through, then appears to "crash".
The progress bar clears itself, but Cura appears to be still slicing, and remains this way until "Cancel" is clicked.
![screenshot 52](https://user-images.githubusercontent.com/18093484/43680204-8cc5d632-982c-11e8-9a5f-9b1546ea3c6a.png)
![screenshot 51](https://user-images.githubusercontent.com/18093484/43680198-6c96dac8-982c-11e8-9f66-340d3cedfebe.png)

**Expected results**

Expected results are for the slicing to complete with the support missing from the blocked areas.

**Additional Information**

This arrangement of settings works fine in the "All at Once" Print Sequence.
But I require a multiple print done, one model at a time, but with limited support.

Alternatively, a third option in "Support Placement" of "On Model Only", allowing support material to be "everywhere needed on the model" except on the print bed

**Comment by fieldOfView** [comment]
Please add a project file (file -> save project)

**Comment by FynDestiny** [comment]
Hi.
Since writing this I've changed to a different project and this issue doesn't appear to be happening this time.
If it should repeat this issue, I will update you.

**Comment by FynDestiny** [comment]
Though my idea of a third option of "On Model Only" would make some prints easier, where support is only wanted for an overhang that is only over the model and not the printbed

**Comment by Ghostkeeper** [comment]
I don't really see an advantage of supporting only when above model, and not on the build plate. What case would need something like that? Support resting on the build plate should be fine.

**Comment by FynDestiny** [comment]
What is the point in having so many print options when they are not all available in both print modes. Same issue with individual model settings, you should be able to print any number of models (space dependent of course), with any of the settings, even different layer thickness if wanted.

Cura is good, easy to use, but lacks total flexibility.

**Comment by fieldOfView** [comment]
I am not suggesting that the current situation is ideal, I just came to the realisation that you uncovered a bug that I don't think the developers have thought about before. When you print "on at a time", Cura will currently try to print the main model first, and then the support blockers one by one, because those are seen by Cura as individual models too. At least, I think they are.

**Comment by GregValiant** [comment]
Is this still an issue with current versions of Cura (5.8.0 and up)?  Can this be closed?
