### ISSUE TITLE
[3.4.1] Minor issue/Potential user error: Cura can be closed while gcode is written -> incomplete file

### ISSUE THREAD

**Issue by Cyberman-tM** [Ultimaker/Cura#4195]
**Application Version**
3.4.1

**Platform**
Windows 10 64Bit

**Steps to Reproduce**
*) Slice a file
*) save gcode
*) immediately close cura (X at top right)
*) check gcode file

**Actual Results**
The gcode file is cut off near the end, after ";TIME_ELAPSED:"

**Expected results**
Cura should either complete the write process, or prevent the user from closing the program while it writes.
(Please don't add a constant "do you really wish to close?" question :-)

**Comment by ChrisTerBeke** [comment]
It should indeed not close before an action is finished (like writing G-code).

**Comment by Cyberman-tM** [comment]
I *think* the problem might be that the current action IS completed - the action of writing the actual core-gCode - the next action would be finishing up the file, adding the closing gcode, the parameters, etc...

**Comment by ChrisTerBeke** [comment]
I'd say all of that is part of 1 export 'action'.

**Comment by alekseisasin** [comment]
@Cyberman-tM , We have discussed your request and unfortunately we are not going to make changes in exporting/saving Gcode process because we already have a message box with a progress bar which indicates whether a file is ready or not.

**Comment by ChrisTerBeke** [comment]
@alekseisasin can you update the ticket labels and open status then?

**Comment by Cyberman-tM** [comment]
@alekseisasin: No problem, as I said, it's basically a user error. It's just something I thought worth mentioning, maybe someone else encounters this situation and finds this. I'll close the ticket.

**Comment by alekseisasin** [comment]
@ChrisTerBeke , I do not close immediately, I have a sticky on my table, to check reply from a person who created the ticket. I saw a couple of times opening and closing tickets because of a misunderstanding.
@Cyberman-tM , thank you for your idea and closing the ticket.

**Comment by Ghostkeeper** [comment]
This was fixed in 3.5.
