### ISSUE TITLE
The version of Cura available in the Ubuntu Software app is old

### ISSUE THREAD

**Issue by mrjohnc** [Ultimaker/Cura#4197]
The current version of Cura that is available through the Ubuntu Software app is very out of date (3.1.0-1 vs 3.4.1 on the Ultimaker website).

![screenshot from 2018-08-05 23-49-11](https://user-images.githubusercontent.com/7293392/43690429-30c4e4a2-990a-11e8-9683-6b671a5cdb3f.png)

**Comment by ChrisTerBeke** [comment]
Ultimaker doesn't maintain that so you'll have to contact the publisher directly.

**Comment by mrjohnc** [comment]
OK, so its Ubuntu who added it, not Ultimaker? 

Thanks

**Comment by fieldOfView** [comment]
That is correct. Ultimaker only distributes the AppImage version of Cura for Linux distributions.

**Comment by mrjohnc** [comment]
OK, thanks very much for the information

**Comment by mrjohnc** [comment]
Ok, one last question, then I'm done I promise :) Would it be possible to add a function to Cura on Linux which looked for new versions and installed them from within Cura. So no matter which out of date source it was downloaded from it would still give an easy and obvious path for users to keep Cura up to date.

In practice this would mean a box popped up when you start Cura that says 'a new version of Cura is available' and then you can click a button to update

**Comment by fieldOfView** [comment]
This is already in place in the official distribution, but I think whoever packaged Cura for Ubuntu has left out that functionality because they intend for the package manager to be used instead of the Cura-internal update check.

**Comment by mrjohnc** [comment]
Ok, thanks, I'll find out who it was and ask them nicely to add it back in

**Comment by mrjohnc** [comment]
I found them :) Its @thopiekar
