### ISSUE TITLE
[3.4.1] cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by dwiinberg** [Ultimaker/Cura#4198]
The following error occurs after installing and running the Cura on my conputer. Seems to be an error with cx_Freeze but i don't have much information besides that. Hopefully the screenshot of the error message will be enough to provide the information needed. 

**Application Version**
<Ultimaker Cura 3.4.1>

**Platform**
<Windows 7 Enterprise>

**Printer**
<Haven't reached that point>

**Steps to Reproduce**
<Installed, can't open>

**Actual Results**
<->

**Expected results**
<->

**Additional Information**
![image](https://user-images.githubusercontent.com/42134017/43702226-6b72e7da-9959-11e8-9da9-56ad742b0ad1.png)

**Comment by alekseisasin** [comment]
@dwiinberg ,You have security issues. In the last line: PermissionError [WinError 5] Access is denied. Probably you have additional system restrictions. You might try to run the program as administrator. (right click, run as administrator.)

**Comment by dwiinberg** [comment]
That solved my problem. I haven't experienced that before on my machine though, so a bit surprising.

**Comment by alekseisasin** [comment]
ok, then I will close the issue.
