### ISSUE TITLE
An object's "ghost" remains visible after deleting

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#42]
When I delete an object through the context menu, the controls (e.g. scale elipses or arrows) and a wire mesh stay visible until I click somewhere in the 3D viewport.

Where: Main interface

Actions: Using the 15.05.94 Darwin release.

Expected behavior: 
 - I would like to see the object and controls disappear entirely.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/191236/8145337/3de79a52-1204-11e5-9098-a915d22f0bb4.png)

Specs: OS X 10.10.3

**Comment by nallath** [comment]
This is a known issue. I've also had this problem but posted it on Asana.

**Comment by awhiemstra** [comment]
This is now fixed. Seems I again failed to reference the right issue though.
