### ISSUE TITLE
Cura3.3, add printer lead to breakdown. Why?

### ISSUE THREAD

**Issue by Kun-Tian** [Ultimaker/Cura#4201]
Cura3.3, I run the project and the application start up.
When I add a printer, if I chose "Custom FDM printer", it will break down immediately.
But, if I chose "Ultimaker ***", it will start up with no crash.

What is the reason? Thanks!

**Comment by Kun-Tian** [comment]
Here is the log.
[cura.log](https://github.com/Ultimaker/Cura/files/2261951/cura.log)

**Comment by Kun-Tian** [comment]
It is not installation application.
I use pycharm run the code(Branch3.3), not the installation.
Thanks!

**Comment by ianpaschal** [comment]
I'm not able to recreate this issue. Do you have all the dependencies installed correctly?

**Comment by Kun-Tian** [comment]
It is the official version. 
I didn't change any code. The code is from:
https://github.com/Ultimaker/Cura/tree/3.3  and  https://github.com/Ultimaker/Uranium/tree/3.3

I just combine Cura and Uranium together, the file of materials, quality, variants, or other config file is initial file, didn't been changed.

If I chose the printer of Ultimaker, such as Ultimaker3, it will installed correctly.

Please download the code  from the above URL, and have a try, it will be recreate.
Thanks!

**Comment by fieldOfView** [comment]
Don’t combine Cura and Uranium in one folder. Instead use the PYTHONPATH variable to “include” uranium when running cura_app.py.

Why do you use the 3.3 branches instead of the 3.4 branches?

**Comment by Kun-Tian** [comment]
Now I separate Cura and Uranium in two folder, and use the PYTHONPATH variable to include Uranium , it still crashed.
I use 3.3 because the develop environment(cura-build-environment3.3) was build months ago, the build environment process is not easy, so I still use 3.3.  I will try 3.4 later.

But how to figure this problem.

Thanks!

**Comment by ianpaschal** [comment]
Unfortunately we cannot spend time trouble shooting this. Without seeing your whole dev environment and making sure that everything is set-up properly, we can only guess what might be wrong.

Also, since we are all running Cura, we are unable to reproduce the issue, and by definition it affects 0% of our end users running the distributable binaries.

I'm afraid this is one you'll need to troubleshoot yourself.
