### ISSUE TITLE
Cura 3.4.1 Crashes When Hit Up Arrow in Layer View, cant scroll through layers either

### ISSUE THREAD

**Issue by Bulldogger** [Ultimaker/Cura#4209]
Says it all
I'm not able to find the App Data log on my Windows 10 machine using the guidance elsewhere on this site.  Would appreciate a steer to it.

**Comment by fieldOfView** [comment]
> Says it all

No, it doesn't. Please fill in the issue template.

As for the log, see Help -> Show configuration folder. The file you are looking for is Cura.log.

**Comment by Bulldogger** [comment]
Thank you fieldOfView, but I cannot find anything marked .log in the configuration folder.  I did not customize my install in any way, so don't understand why nothing seems to be where it's supposed to be.

Is there another place the log might be?

**Comment by fieldOfView** [comment]
What files are in your Configuration folder?

**Comment by Bulldogger** [comment]
I've been trying to find this log.  It definitely doesn't show up in that location.  I have no idea why.  I downloaded and installed 3.5.1 and it is still a little odd.  When I click on Layer View sometimes the layers show (the slider shows up and I can slide through) and sometimes I only see the color codes for the types of lines or whatnot.I give up.Alex-----Original Message-----

**Comment by Bulldogger** [comment]
The recently available newer software version seems to have fixed this crashing, whether on purpose or by simple fact of a reinstall.  I did notice that there is sometimes a lag while the layer view is generated, and maybe I was not waiting long enough before hitting keys, but we're talking half a minute sometimes, which does seem long either way.I never could find the Log folder...Alex -----Original Message-----
