### ISSUE TITLE
[3.4.1] Circles strange infill/gapfill

### ISSUE THREAD

**Issue by PatrickAntalus** [Ultimaker/Cura#4217]
I can't get Cura to do a complete circle.
![strange-infill](https://user-images.githubusercontent.com/41518003/43902845-60e40c56-9beb-11e8-8059-507870c39ca2.png)
[CFDMP_ring.zip](https://github.com/Ultimaker/Cura/files/2274409/CFDMP_ring.zip)

**Comment by BagelOrb** [comment]
You could increase the wall line count to prevent this behaviour in this case.

It is a known limitation of how our infill algorithm works.

**Comment by PatrickAntalus** [comment]
Thanks for the feedback. I did try 3 walls, but it's the same. Problem is that this third wall does not fit. If this is really standard behavior of Cura, it is unfortunately not usable. In this way, the model needs so much more travel and time.
