### ISSUE TITLE
Support Material printed where it is not needed

### ISSUE THREAD

**Issue by FynDestiny** [Ultimaker/Cura#4219]
**Application Version**

3.4.1

**Platform**

Windows 10

**Printer**

CR-10S
[CCR10_Bobbin Spring.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2275701/CCR10_Bobbin.Spring.curaproject.3mf.zip)

**Steps to Reproduce**

Loaded a few models.
Selected Support Material "Touching Buildplate Only"
Slice

**Actual Results**

As depicted in photos...
![screenshot 53](https://user-images.githubusercontent.com/18093484/43922165-d89d9fd0-9c15-11e8-85fa-a988ca17218d.png)
![screenshot 54](https://user-images.githubusercontent.com/18093484/43922229-02f1fd9e-9c16-11e8-8535-56db452c2086.png)
![screenshot 55](https://user-images.githubusercontent.com/18093484/43922254-106c1edc-9c16-11e8-8af2-2b81827fcd46.png)

**Expected results**

Expected results would be for the support material not be printed where it is not supporting anything 

**Additional Information**

**Comment by BagelOrb** [comment]
It is trying to support the top cross sections, but it isn't able to because of the clearance distance or other such support settings.

**Comment by alekseisasin** [comment]
You can try to adjust the setting "Support Join Distance" to 0.5mm

**Comment by FynDestiny** [comment]
I'll give that a try when I get back onto this part.

**Comment by Ghostkeeper** [comment]
In the project file, the problem does reproduce. Setting Support Join Distance to 0.5mm fixes it, so it was the joining of support components that are close together that causes this problem.

Shouldn't it remove support that is not above the build plate BEFORE joining the support areas together?

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?
