### ISSUE TITLE
[3.4.1] Cannot connect to 3rd-party printer

### ISSUE THREAD

**Issue by Millervill** [Ultimaker/Cura#4227]
I am using a Da Vinci Jr 1.0 Pro printer. I have recently tried to use it with Cura, however after adding the printer, Cura does not detect it. I know it is not a USB issue nor a computer detection issue as the printer connects to other software and is visible in the devices section on the computer. Im not sure why the software cannot detect my printer. 

Application Version
Cura 3.4.1

Platform
Windows 10 64 bit

Printer
Da Vinci Jr 1.0 Pro

Steps to Reproduce
Connecting USB cable between PC and Printer

Actual Results
Message of Printer Not Connected In Cura under Printers => Manage Printers

Expected results
Printer should connect to PC and be recognized by Cura so that a 3D print can be done

Additional Information
none

![printer detection](https://user-images.githubusercontent.com/42317363/44002073-098d3f08-9e35-11e8-854b-561bd432cecf.jpg)

**Comment by ChrisTerBeke** [comment]
Da Vinci runs proprietary firmware that Cura cannot talk with. You have to use the desktop software provided by them. Unfortunately there's nothing we can do about this.

**Comment by mishu28nmv** [comment]
*Only support Cura and Slic3r software (Flavor Selected: RepRap (Marlin/Sprinter))
This is from xyzPrinting site. Tried everything but it doesn't connect!
