### ISSUE TITLE
Linux - Open dialog is case sensitive

### ISSUE THREAD

**Issue by Hyna** [Ultimaker/Cura#424]
Open dialog for opening .stl files is case sensitive. It accept only the lowercase stl extensions. .STL and any other combination with upper case letters is ignored. 

Cura:15.10
OS: Fedora 21

**Comment by awhiemstra** [comment]
Which desktop environment is this?

**Comment by Hyna** [comment]
Its GNOME.

**Comment by mtowara** [comment]
Same for Xfce

**Comment by thopiekar** [comment]
I can see these *.STL files in the open files dialog.
Maybe fixed in 2.1 branch?

**Comment by Ghostkeeper** [comment]
Ah, yes. We must've forgotten to close this issue.

It now lists both *.stl and *.STL. Not *.sTl or *.StL or something though, but we thought the use case for though was too small to pollute the dialogue further.
