### ISSUE TITLE
"Cura 3.4.1" Save as

### ISSUE THREAD

**Issue by Kernfusion** [Ultimaker/Cura#4241]
When I klick the Bottom "Save as" is always double "gcode.gz" for examble  UM3E**********.gcode.gz.gcode.gz 
WINDOWS10

**Comment by BagelOrb** [comment]
We are aware of this issue and we are currently discussing what to do with it. Somehow it is hard to get rid of this thing.

**Comment by ChrisTerBeke** [comment]
Duplicate of multiple tickets.
