### ISSUE TITLE
Profiles dropdown improvements 3.4.1

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#4250]
**Application Version**
3.4.1

**Platform**
Windows 7 64bit

**Printer**
any

**Steps to Reproduce**
Create lots of profiles. 
(I run a small business where it makes sense to have a separate profile for each part in every product that I print and sell).

**Actual Results**
When entering the dropdown, we need to scroll all the way down to choose "Create", "Update", or "Discard"

**Expected results**
Put the "Create", "Update", "Discard" and "Manage Profiles" buttons near the top for convenience.

**Additional Information**
Also, when using a highly sensitive mouse, if we accidentally move the cursor one pixel while clicking to open the drop-down menu, it will select a profile from the list when we release the mouse button.
Would it be possible to prevent the release of the mouse button from opening a profile?

Another suggestions is a way to put profiles in folders and/or the possibility to hide/archive profiles from the list temporary. I realise that we can already export and import profiles but that can only be done with one profile at a time. Just a suggestion.
![namnlos](https://user-images.githubusercontent.com/32172100/44255732-46bc0c80-a207-11e8-9e0b-a7022725b778.png)

**Comment by lf-** [comment]
You can do it with the keyboard as follows: Alt+S, (let go of alt) P, then C/U/D for Create/Update/Delete. I should make a PR to add keyboard nav support to the "Manage profiles" at the bottom as well though!

**Comment by printingotb** [comment]
Hmm, nothing happens when I press Alt+S. If I click settings, I can press P to open the profile menu but I can't use C to create a profile.

**Comment by Ghostkeeper** [comment]
I think for your workflow it would be easier to save project files rather than create print profiles...

**Comment by Ghostkeeper** [comment]
We can't change the behaviour of the drop-down list. It's your operating system creating that drop-down list.

We can change the ordering, such as to put "create", "update" and "discard" at the top. But for user experience it might not be very useful. What's your opinion, @Yian-Lai?

**Comment by Ghostkeeper** [comment]
Adding a hotkey for those menus sounds like a good idea to me.

**Comment by Ghostkeeper** [comment]
Scrolling that list should be possible, though...

**Comment by printingotb** [comment]
This is how it looks, especially annoying when I reach the end and the arrow moves:
https://youtu.be/EQSvE4plIXU

**Comment by printingotb** [comment]
Or could you do this? (made in paint)
![namnlos](https://user-images.githubusercontent.com/32172100/47708787-23fa9b00-dc2f-11e8-88ca-edba1f5499ee.png)

**Comment by Ghostkeeper** [comment]
That Manage Profiles button is also under the "Profile" submenu so that would look illogical.

**Comment by printingotb** [comment]
Doesn't work for me though since I still have to get through my long list of profiles to reach it.
![namnlos](https://user-images.githubusercontent.com/32172100/47710336-d849f080-dc32-11e8-8b84-5144989f539a.png)

**Comment by Ghostkeeper** [comment]
Yes, I understand that :stuck_out_tongue: But for most users it would look weird.

It's not in version 3.6, but the release after that will have a shortcut key Ctrl+J to open the profiles manager.

**Comment by printingotb** [comment]
Perfect!
