### ISSUE TITLE
Insufficient clearance for prime blob with 0.8mm print core

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#4254]
**Application Version**
3.4.1

**Platform**
Windows 10 x64

**Printer**
Ultimaker 3 Extended

**Steps to Reproduce**
Print with 0.8mm print core and prime blob enabled

**Actual Results**
There is insufficient clearance for the prime blob, the print head ends up swimming in the ejected blob.

**Expected results**
The print clearance should take into account the print core diameter, flow rate multiplier, and possibly even material density/plasticity.

**Comment by fieldOfView** [comment]
You mean 3.4.1, right?

**Comment by mqudsi** [comment]
I do indeed.

**Comment by Sembiance** [comment]
I have this same problem but with the 0.4mm BB core.

Is there any way to modify how high above the print bed the blob is extruded from? I'd like to raise it higher in general to avoid the blob touching the exterior of the hot end.

**Comment by BagelOrb** [comment]
@sembiance: please create a new ticket for your request.

**Comment by BagelOrb** [comment]
@mqadsi you are talking about clearance in the XY direction, right?

**Comment by mqudsi** [comment]
No, in the z.

**Comment by diegopradogesto** [comment]
Long time waiting for a reply. Is this still causing you problems, @mqudsi ? 

Feel free to reopen if necessary.
