### ISSUE TITLE
Extruder stops 3.4.1

### ISSUE THREAD

**Issue by davchr1** [Ultimaker/Cura#4257]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smartavionics** [comment]
Please zip up and attach the gcode and also the curaproject file so they can be examined. Without those, it's impossible to investigate your issue. Thanks.

**Comment by davchr1** [comment]
[CCR10_Problem Print.zip](https://github.com/Ultimaker/Cura/files/2300441/CCR10_Problem.Print.zip)
[Garage cover plate 3.zip](https://github.com/Ultimaker/Cura/files/2300442/Garage.cover.plate.3.zip)
Here is the problem gcode file and what I believe is the .STL input file.

**Comment by smartavionics** [comment]
Hi, I'm not familiar with M221 but are you sure that setting a value of -1 is sensible? Your gcode contains lines like this:
````
M221 T0 S-1.000000
````

What is your intention there?

**Comment by smartavionics** [comment]
Yes, the M221s are being created by the ChangeAtZ plugin. Sorry, I have no experience of that but, perhaps, you have specified something incorrectly there?

**Comment by davchr1** [comment]
I have changed bed and extruder temperatures there, but not flowrate - at least no intentionally.  I will go back to using the 3.4.1 and look carefully at the ChangeAtZ parameters if I have problems again.

Thanks for your help.  Lets close this until I have problems again.

thanks

**Comment by smartavionics** [comment]
OK, good luck!

**Comment by davchr1** [comment]
Thanks.  I have changed extruder and bed temps with the ChangeAtZ plugin.  But not the flow rate, at least intentionally.  I will go back to the 3.4.1 and watch for that if I have problems again.
thanks
    On Sunday, August 19, 2018, 11:09:54 AM MST, Mark Burton <notifications@github.com> wrote:  
 
 
Yes, the M221s are being created by the ChangeAtZ plugin. Sorry, I have no experience of that but, perhaps, you have specified something incorrectly there?

**Comment by Ghostkeeper** [comment]
I found a potential issue with the flow rate adjustment in ChangeAtZ if you were using dual extrusion. See https://github.com/Ultimaker/Cura/commit/2eb9b111fc099d73d555f26fb76d42232dffb0b5.
