### ISSUE TITLE
15.09.83: Issue's and crashes on add printer

### ISSUE THREAD

**Issue by mennoberg** [Ultimaker/Cura#426]
- Cura crashes when I add any other Printer then an Ultimaker 2.

It also starts up without with an empty list of machines in the list, without the question if i would like to add a machine.

![screen shot 2015-09-24 at 11 29 13](https://cloud.githubusercontent.com/assets/6329918/10069938/aac346ca-62af-11e5-8570-131de8ec9b93.png)

Osx 10.10.5

**Comment by awhiemstra** [comment]
Not showing the Add Machine Dialog should now be fixed. Unfortunately I do not know what causes the crash with non-UM2 machines.

**Comment by TMHogenhout** [comment]
fixed
