### ISSUE TITLE
Backup plugin error

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#4261]
I did a downgrade from win10 to win7 x64 SP1 and when I try to restore the backup:

default backend - 404

(happen after click in SIGN button in cura plugin window and IE open and try to open this URL:
https://api.ultimaker.com/auth/v1/authorize?state=CuraDriveIsAwesome&response_type=code&code_challenge=QAVaLJ_0N5LJHdK4ib0Eb3ur5CHWpxcd63pV7OEUiL_vYZ9BYZV1O2lkfTOuGedwJPuvIars6D6TnnCjav9YBg%3D%3D&code_challenge_method=S512&scope=user.read+drive.backups.read+drive.backups.write&client_id=um---------------ultimaker_cura_drive_plugin&redirect_uri=http%3A%2F%2Flocalhost%3A32118%2Fcallback
)

**Comment by fieldOfView** [comment]
See https://community.ultimaker.com/topic/24134-cura-backups-account/
