### ISSUE TITLE
Feature Request: Plugin to insert gcode at the "corner of each layer"

### ISSUE THREAD

**Issue by truglodite** [Ultimaker/Cura#4266]
**Application Version**
3.4.1

**Platform**
na

**Printer**
na

**Steps to Reproduce**
na

**Actual Results**
na

**Expected results**
Another cool feature!

**Additional Information**
There is a python post processing script available for skeinforge users that inserts gcode at the corner of every layer. This allows octolapse (a popular time lapse creation plugin for octoprint) to take snapshots for stabilized time lapse videos without causing significant print artifacts. See this page for reference (link to gege2b's code on bottom):

https://github.com/foosel/OctoPrint/issues/1983

I request that a similar feature be added to Cura.

Currently when using Cura as a slicer (no additional post processing), the best that can be done for stabilized videos goes something like this: octolapse looks for layer changes indicated by Cura's ";LAYER:X" code, then it pauses the print immediately after the layer change, moves to a predefined spot to take a snapshot (typically this is set to X0 Ymax), then resumes the print. The resulting long pause/movement at each layer results in blobbing/stringing artifacts, which can be a deal breaker when printing aesthetic models or tricky materials like TPU.

After scanning over gege2b's script, it appears to flow like this: locate a layer section in the gcode, find G1 lines containing "Xmin" for that layer, then find Ymin within those lines, and append M240 (octolapse snapshot Gcode) right after that line. To me programming the logic seems simple enough, but it's not C++ so I'm totally lost. At least with Cura's ";LAYER:" code, parsing layer sections shouldn't be too hard.

**Comment by gege2b** [comment]
Hi there, sorry to bump this issue after a while of inactivity just to add my two cents. 

Firstly, it's not my script, I mainly hacked the original script from [this website](https://eclecti.cc/bytes/reprap-controlled-time-lapse-photography) so it could run outside of the skeinforge environment. Dirty but it just works :) 

Secondly, if you're still interested by this kind of timelapse, the author of octolapse is actually working on this [feature](https://github.com/FormerLurker/Octolapse/issues/319#issuecomment-460848183) (called "quasi stabilized timelapse") witch will be available out of the box, slicer-independent
