### ISSUE TITLE
Entire application is useless garbage

### ISSUE THREAD

**Issue by zinenu** [Ultimaker/Cura#4269]
**Application Version**
ALL

**Platform**
ALL

**Printer**
ALL

**Steps to Reproduce**
USE THE SOFTWARE TO DO LITERALLY ANYTHING

**Actual Results**
CRASHES, BUGS

**Expected results**
ABILITY TO HANDLE A THERMAL RUNAWAY OR ABORTED PRINT

**Additional Information**
CURA IS FUCKING TRASH AND YOU SHOULD FEEL BAD FOR MAKING IT, JUST QUIT. LITERALLY ANY OTHER SLICER IS BETTER.

**Comment by nallath** [comment]
![](https://i.kym-cdn.com/photos/images/original/000/001/881/ha_ha_lies.jpg)
Just because it's cruise control, doesn't mean you don't have to steer. 

That being said; Cura can handle aborts and thermal runaway is the firmware of the printer that is messing up.

**Comment by ChrisTerBeke** [comment]
Thanks for this positive feedback. We will most certainly look into it.

**Comment by ChrisTerBeke** [comment]
Don't wanna make this bigger than it is, but (stock) Marlin has plenty of issues with thermal runaway, just Google for it.
