### ISSUE TITLE
File name not saved

### ISSUE THREAD

**Issue by Lizartin** [Ultimaker/Cura#4276]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by ChrisTerBeke** [comment]
Please fill out the issue template properly, this is not enough information.

**Comment by CCS86** [comment]
Same issue here.

3.4.1 / Windows 10 x64 / multiple printers

Click to edit file name. Change name. Click save-> original name is saved. Trigger a settings change that causes reslicing->displayed filename reverts to original, automatic file name.

**Comment by fieldOfView** [comment]
Could you try the 3.5 beta? I remember fixing this.

**Comment by CCS86** [comment]
I just did a little test. This issue was occuring for me only during 'save to removable drive'. I switched to 'save to file' and in the windows save dialog, the edited file name was correctly displayed. I cancelled, then switched back to removable drive, and it saved with the correct edited file name.

**Comment by Lizartin** [comment]
Hi,
I almost always just save to "removable file".  This just started happening with one of the recent updates.
Liz



-----Original Message-----

**Comment by CCS86** [comment]
Another issue I see is that after the little trick above to allow saving directly to a removable drive, the file name gets truncated if it contains a period. For example:

"ConcreteMold0.8_2" gets saved as "ConcreteMold0.gcode"

**Comment by fg89o** [comment]
> Could you try the 3.5 beta? I remember fixing this.

In 3.5 beta is working fine. Thanks.

**Comment by fieldOfView** [comment]
@Ccs86, when you find another bug, please open another issue or it will get lost.

**Comment by CCS86** [comment]
I just installed 3.5 final and the bug is still present. 

Actually, even the 'save as file' workaround I was using won't work now:

![image](https://user-images.githubusercontent.com/12439543/46492694-ecd1cf00-c7d3-11e8-9765-99b5af4e80c4.png)
