### ISSUE TITLE
Z Seam Alignment change print order

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4282]
**Application Version** - CURA 3.4.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Generate print paths with different "Z Seam Alignment"

**Actual Results** 
In the images below we can see the print order indicated with the numbers.

1 - Z Seam Alignment: **User Specified**
![user_specified](https://user-images.githubusercontent.com/12901952/44579067-205d1a80-a78d-11e8-8f07-220deb772847.jpg)

2 - Z Seam Alignment: **Shortest**
![shortest](https://user-images.githubusercontent.com/12901952/44579091-31a62700-a78d-11e8-8f4d-f8137843ffa9.jpg)

3 - Z Seam Alignment: **Random**
![random](https://user-images.githubusercontent.com/12901952/44579114-408cd980-a78d-11e8-85bb-f8423cdad006.jpg)

4 - Z Seam Alignment: **Sharpest Corner**
![sharpest_corner](https://user-images.githubusercontent.com/12901952/44579133-51d5e600-a78d-11e8-9e4d-d07013a560f9.jpg)

**Expected results**
Same print path with different "Z Seam Alignment" options.

[B2X300_TMC.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/2317930/B2X300_TMC.curaproject.3mf.zip)

**Comment by diegopradogesto** [comment]
I only see one difference, with the **User specified** seam. And indeed it is correct in this case. You selected to print the Z Seam in the closest point to the position (0, 100) and this is what CuraEngine does. You can better see it in the image:
![zseam2](https://user-images.githubusercontent.com/15830521/44902708-febede80-ad0a-11e8-8f85-8bae78c591d4.png)

Based on the idea that (0, 0) is the center of the buildplate, position (0, 100) is where I set the red cross. Then the shortest distance to start is the pillar marked as 1 (first item to print). Then it is following the shortest distance again, so it moves to 2, then to 3 and so.

I don't see any issue here.
