### ISSUE TITLE
Settings lost between Cura sessions

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#43]
Application Version: 15.05.94
Platform: OS X 10.9.x

Steps to Reproduce:
Change settings in Cura, close Cura, reopen Cura

Actual Results:
Settings changes are lost

Expected results:
Previous settings would be retained between sessions

**Comment by Ghostkeeper** [comment]
This seems to be platform-specific. It doesn't happen on my Windows 7 computer. Settings are properly retained.

**Comment by awhiemstra** [comment]
Can you check if the directory .cura exists in your home directory and if so, if that contains a file cura.cfg and a directory settings?

**Comment by Xisle** [comment]
![screen shot 2015-06-15 at 9 13 47 am](https://cloud.githubusercontent.com/assets/12257213/8165681/e3082d5e-133e-11e5-806e-4100ea2dc606.png)

**Comment by Xisle** [comment]
Above is the complete contents of cura.cfg from .cura folder

**Comment by Xisle** [comment]
Settings are still lost between sessions on 15.05.96.

**Comment by awhiemstra** [comment]
So just to narrow things down, which settings specifically are not restored properly? Because your config file suggest at least window size and recent files are saved properly. Can you check if those are restored properly?

**Comment by Xisle** [comment]
Size is maintained, but not location. That wasn't actually my issue.

The Advanced Settings are lost between sessions. Old Cura allowed these settings to be saved as a Profile, but also maintained settings between sessions.

Open Cura, change layer height or any other setting, close Cura
Open Cura... Advanced Settings revert to "default" values.

**Comment by Xisle** [comment]
This appears to be fixed. I DO now see settings in my ~/.cura/settings/*.cfg file and they are retained between sessions.

I did not fully test yet, however.

Issue #76 is still an issue for me though.
