### ISSUE TITLE
[15.09.83][regression] Add machine wizard not started when no machine is configured

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#430]
It used to be that when starting Cura with no machines configured, the Add machine wizard would open automatically. Currently I get an empty 3d view and no settings, until I manually add a machine.

Steps to repro:
* Remove cura profile from disk
* Start Cura

Result:
release notes, then empty 3d view, not settings

Expected:
add machine wizard pops up after showing the release notes

**Comment by awhiemstra** [comment]
This was already noted by @mennoberg in #426 and is fixed in the next build.
