### ISSUE TITLE
Temp changes in gcode

### ISSUE THREAD

**Issue by Peggsy** [Ultimaker/Cura#4305]
**Application Version**

Cura 3.4.1
**Platform**

Windows 7
**Printer**

Ender 3
**Steps to Reproduce**

Generating gcode for anything over 98 layers
**Actual Results**

gcode M104 inserted throughout the file. I set M104 S212 in Cura. at layer 98 this changes to 226. Then the temp is reduced by 4 degrees every 100 layers from there on.
**Expected results**

**Additional Information**

gcode file attached. This happens to any gcode file over 98 layers.
[SE-14R_-_Barrel.zip](https://github.com/Ultimaker/Cura/files/2335158/SE-14R_-_Barrel.zip)

**Comment by alekseisasin** [comment]
@Peggsy , do you use any post-processing script?

**Comment by Peggsy** [comment]
@alekseisasin Yep I found it.... well the problem was found for me, and did I feel dumb!!! It was a post-processing script I had left live after printing a heat tower.... sorry I should have closed the issue.
Thanks alekseisasin.
