### ISSUE TITLE
Nozzle size error on the printer setting

### ISSUE THREAD

**Issue by fdapport** [Ultimaker/Cura#4306]
Version: Ultimaker Cura 3.4.1
Operative system: Win 10 PRO

Printer: DeltaBot

On Setting/ printer/manage printer menu.
Machine setting screen Extruder folder, Nozzle size default is 0.5mm, when I changed it is nor memorized, so any time I need to check it.. Other information is recorded correctly, like "compatible material diameter".

Thanks for the help,
Franco

**Comment by diegopradogesto** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3773.

Fixed in the next release.
