### ISSUE TITLE
Fill in unexpected areas

### ISSUE THREAD

**Issue by nauzadt** [Ultimaker/Cura#4315]
**Application Version**
3.4.1

**Platform**
Win10

**Printer**
Cocoon HE170703 / Wanhao Duplicator i3 mini

**Steps to Reproduce**
Load model.
View model in solid view and Layer View

**Actual Results**
![image](https://user-images.githubusercontent.com/42888861/44944716-3fa81780-ae1f-11e8-90bd-0133383c774c.png)

**Expected results**

![image](https://user-images.githubusercontent.com/42888861/44944719-4df63380-ae1f-11e8-8e82-f215494e4515.png)

**Additional Information**
Seems like Cura wants to fill in the gap in the lettering

**Comment by ianpaschal** [comment]
Please save your project as a .curaproject, zip it, and attach it. Very hard to guess what is going wrong looking at a picture.

**Comment by nauzadt** [comment]
Hi Ian, I have a .stl file that has lettering in it. For some reason, this version of Cura wants to fill the inside space within the letter. .

The "actual results" is a screenshot of a layer view, while the "Expected results is a screenshot of the .stl file.

**Comment by ianpaschal** [comment]
Yeah, I see that. ;)

Please save your project as a .curaproject, zip it, and attach it. I see something is going wrong but can't tell what if I can't look closely at the model, configuration, etc.

**Comment by nauzadt** [comment]
@ianpaschal Reloaded the file. Its generating the right STL now. Thanks
