### ISSUE TITLE
Some layers skipped while slicing model

### ISSUE THREAD

**Issue by goganchic** [Ultimaker/Cura#4320]
**Application Version**
3.4.1

**Platform**
Mac OS X 10.12.6

**Printer**

[CFDMP_facelessHighPoly.3mf.zip](https://github.com/Ultimaker/Cura/files/2345297/CFDMP_facelessHighPoly.3mf.zip)

**Steps to Reproduce**

Try to slice this model https://www.thingiverse.com/thing:171674

**Actual Results**

Some layers skipped

**Expected results**

All layers sliced correctly.

**Additional Information**

![screen shot 2018-09-03 at 14 17 29](https://user-images.githubusercontent.com/193946/44984073-22408e00-af84-11e8-8c76-7b098b118ab9.png)

When using slic3r everything is ok.

**Comment by ChrisTerBeke** [comment]
Does the model show any non-manifold faces in X-ray view?

**Comment by goganchic** [comment]
@ChrisTerBeke would you please explain it to me, how can I understand that model has non-manifold faces? Does such faces has some special color?

**Comment by ChrisTerBeke** [comment]
In x-ray view, faces that are incorrect (e.g. reversed, or not watertight) are shown in red. Everything else is purple/translucent.

**Comment by goganchic** [comment]
Thanks!
