### ISSUE TITLE
Cura 64 Bit ONLY Crashes on startup

### ISSUE THREAD

**Issue by morsyfadl** [Ultimaker/Cura#4324]
**Application Version**
Any 64-Bit version. I tired 3.4.1, 3.3.1, 3.2, 3 and  2.7
**Platform**
Windows 8 64 Bit
 i3-2120
 Intel HD 2500
2GB DDR3 Ram

**Printer**
Custom Prusa (irrelevant)

**Steps to Reproduce**
Install any version that is 64 bit, and try to run it right after installing, even on a clean windows with the appdata/roaming files deleted

**Actual Results**
cura barely opens a white windows - doesnt really load- and give a "has stopped working" error
Meanwhile, Every single 32-bit version that i tried works flawlessly, from 15.06 to 2.3

**Expected results**
It should load normlly

**Additional Information**
I got my graphics drivers up to date and the performance on 32 bit version is smooth.
OpenGL Checker/viewer extension thingy identifies my system as version opengl 4.0 capable.

**Comment by alekseisasin** [comment]
@morsyfadl , probably you have a problem with the graphical card drivers. Please upload log file, maybe it will say more information. I am not sure about your virtual memory, might be also not enough.

**Comment by alekseisasin** [comment]
I used to close the issue because I assume it is related to your computer hardware. Otherwise, we would have similar issues from Cura 2.7 version.
