### ISSUE TITLE
Dual Extrusion - Ooze Shield in the Prime Tower 

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4336]
**Application Version** - CURA 3.4.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Select Prime Tower and also Ooze Shield; analyse the toolpath
**Actual Results** - Prime Tower with Ooze Shield
![screenshot_3](https://user-images.githubusercontent.com/12901952/45207787-e443b280-b280-11e8-9b6c-a74f1e40d790.jpg)

**Expected results** - A Prime Tower without the Ooze Shield

**Comment by alekseisasin** [comment]
Hi @amagr0 
From your side you are right the prime tower should not have extra walls around it. As I understand CuraEngine generates the extra walls around all objects. 
In the next release, the prime tower will have the extra wall only outside.
