### ISSUE TITLE
Save Project : Windows : Error: "No filetypes available to write with"

### ISSUE THREAD

**Issue by nauzadt** [Ultimaker/Cura#4340]
**Application Version**
Cura 3.4.1

**Platform**
Windows 10

**Printer**
Cocoon Create mini / Wanhao Duplicator i3 mini

**Steps to Reproduce**
Load .STL file
Modify default settings (e.g: Add supports everywhere)
File>Save Project
Summary-Cura Project>Save

**Actual Results**
Error: "No filetypes available to write with

**Expected results**
Project Settings should be saved to a file

**Additional Information**
![image](https://user-images.githubusercontent.com/42888861/45248830-baaa8a00-b359-11e8-8f24-bb881fe763dd.png)
![image](https://user-images.githubusercontent.com/42888861/45248847-c302c500-b359-11e8-856e-6ebc4e15069b.png)

**Comment by fieldOfView** [comment]
Could you check to see if you have disabled the 3MF Writer plugin on the “installed” tab of the Toolbox?

**Comment by nauzadt** [comment]
Awesome! That worked!

Any chances of adding the statement in the Error displayed to the user in a future update?

**Comment by fieldOfView** [comment]
I think a quicker fix would be to make the 3MF plugins required plugins that cannot be disabled.
