### ISSUE TITLE
Detail got messed up on slice stage

### ISSUE THREAD

**Issue by QuestionAndAnswer** [Ultimaker/Cura#4343]
**Application Version**
3.4.1

**Platform**
Windows 10 x64

**Printer**
Anet A6, used as Prusia i3 with extended table size.
[PI3_Part6^PowerSupplyAirBox.curaproject.zip](https://github.com/Ultimaker/Cura/files/2363474/PI3_Part6.PowerSupplyAirBox.curaproject.zip)

**Steps to Reproduce**
Try to slice. Attaching print profile and model in STL.
[Part6^PowerSupplyAirBox.zip](https://github.com/Ultimaker/Cura/files/2363471/Part6.PowerSupplyAirBox.zip)
[PLAProfile.zip](https://github.com/Ultimaker/Cura/files/2363475/PLAProfile.zip)

**Actual Results**
Rotation not helps. Support disabling also. And somewhy slicer tries to cap hole where it shouldn't.
I also tried to used other slicers and they behaved pretty much the same way. They just caped hole on different height. 

![image](https://user-images.githubusercontent.com/6842709/45256219-11d14e80-b39c-11e8-9b10-d6128ca0bf1b.png)
![image](https://user-images.githubusercontent.com/6842709/45256224-2281c480-b39c-11e8-9e54-2e77f6122de6.png)

**Expected results**
That it would be sliced popperly. 

**Additional Information**
That is how part is looking in Solidworks directly before export to STL.

![image](https://user-images.githubusercontent.com/6842709/45256255-c1a6bc00-b39c-11e8-8ad2-8c25b21e2161.png)

But Cura also exports detail correclty if you look in Solid View mode to imported STL.

**Comment by diegopradogesto** [comment]
Probably is a problem with the model.
