### ISSUE TITLE
Tall support are unstable and almost useless 

### ISSUE THREAD

**Issue by Bricksnspace** [Ultimaker/Cura#4354]
Got an stl from thingiverse, https://www.thingiverse.com/thing:2122792

It is a barrel extension for a Nerf toy gun.

Cura generates support for side "grooves" but that support are unstable during printing. They are attached only on a very small area on bottom and on top, but during printing the support "wobbles" when extruder put a layer on it. At some point, one of them detached and fell off. 

Anyway, the object was perfectly printed, but supports are useless.
 

**Application Version**
Cura 3.4.1 (Linux x64 appimage)

**Platform**
Linux Fedora 28 (x86_64)

**Printer**
Creality3D Ender 3

**Steps to Reproduce**
Load object https://www.thingiverse.com/thing:2122792.
Select generic PETG material and "Draft Quality" profile. Check "Generate support" and "Build Plate Adhesion"
Click on "Prepare" button. 

**Actual Results**
Switch to "Layer view" and select layer in the middle.
![cura-support-2](https://user-images.githubusercontent.com/20813693/45350429-0d7f7e00-b5b4-11e8-94e1-95f84c97e00f.png)

Look at the support. It is "glued" to model only on top/bottom (start-end) layers of the side grooves.

**Expected results**
IDK. IMHO, generated support needs some lateral "link" to the object to increase stability.

**Additional Information**
A closer look to the lower side
![cura-support-3](https://user-images.githubusercontent.com/20813693/45350463-22f4a800-b5b4-11e8-9b53-12b9186fd1ba.png)

**Comment by Bricksnspace** [comment]
I'm a little confused. 
This was generated with 1.6mm horizontal expansion.
![cura-support-4](https://user-images.githubusercontent.com/20813693/45352012-c72c1e00-b5b7-11e8-856c-bf960e174089.png)
It is the intended result? Or I mess something?

**Comment by fieldOfView** [comment]
Yes, this is the intended result. There is virtually no chance of that support falling over.

**Comment by Bricksnspace** [comment]
Ok, I understand now. 
Thanks for your time :+1:

**Comment by fieldOfView** [comment]
Have you noticed that you can also set a negative value for Support Horizontal Expansion? That could remove the unneeded support altogether here.

**Comment by Ghostkeeper** [comment]
Conical support was made to fix this issue.
