### ISSUE TITLE
15.09.84: Deleting all machines crash

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#436]
From the manage machines dialog, when I delete all machines, cura crashes:

![image](https://cloud.githubusercontent.com/assets/12439543/10123392/1a57b93a-64fe-11e5-84e5-5b05af261ce8.png)

**Comment by awhiemstra** [comment]
Hmm, the bug here is that it should not be possible to delete all machines. But I guess the check for that is failing.

**Comment by Ghostkeeper** [comment]
How about allowing the last to be deleted, but then triggering the add new machine wizard?

**Comment by CCS86** [comment]
That sounds better

**Comment by TMHogenhout** [comment]
fixed for Cura 2.0
