### ISSUE TITLE
Add Ultimaker robot at first launch

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#437]
If I recall correctly, previous versions of Cura used to load the standard Ultimaker robot at first launch. Shall we do that again? It gives the user something to see and work with immediately to try Cura out.

**Comment by fieldOfView** [comment]
I would much prefer the "drop file to ..." overlay ui design pattern to show people how to get started:
https://www.google.co.uk/search?q=drop+file+to+upload

Loading a default model does not teach new users anything, and creates an extra step for experienced users.

**Comment by nallath** [comment]
I think this can be closed; Pre-loading a model is a bit annoying. I don't think we will ever re-introduce this.
