### ISSUE TITLE
[3.4.1] No warning before application close while printing via USB

### ISSUE THREAD

**Issue by hawkerm** [Ultimaker/Cura#4372]
**Application Version**
3.4.1

**Platform**
Windows 10

**Steps to Reproduce**
1. Open Cura
2. Start a print via USB
3. Hit 'X' button in top-right of application

**Actual Results**
Application closed immediately and stopped print

**Expected results**
Warning should ask if you want to cancel the print in progress without stopping current print before response.

**Additional Information**
I accidently double tapped my touch screen and closed an application I had running in front of Cura, and then also Cura!  It immediately closed and stopped my print that was running. :(

**Comment by alekseisasin** [comment]
@hawkerm , we already made dialog before application close while printing via USB, it will be next Cura version. The fix is here: 
https://github.com/Ultimaker/Cura/pull/4070

**Comment by hawkerm** [comment]
Thanks!
