### ISSUE TITLE
My config directory is 19 GiB

### ISSUE THREAD

**Issue by larsch** [Ultimaker/Cura#4377]
**Application Version**
3.4.1

**Platform**
Lubuntu 18.04

**Printer**
CFDMP

**Steps to Reproduce**
Upgrade from 2.x, via 3.0, 3.1, 3.2, 3.3 to 3.4.

**Actual Results**
Cura copies all old configuration recursively. 

`.local/share/cura/3.0` folder contains copy of 2.x.

`.local/share/cura/3.1` contains copy of 2.x and 3.0 (with the old copy of 2.x)

`.local/share/cura/3.2` contains a copy of 2.x, 3.0 (with copy of 2.x), 3.1 (with the copy of 2.x, 3.0 (with the copy of 2.x), 3.1 (with the copy of 2.x, 3.0 (with the copy of 2.x)).

You see where this is going... We're just at 3.2 and already have 5 individual copies of the 2.x configuration. When we get to 3.4, there's a million copies of old configurations. This goes factorial!

**Expected results**
Sanity.

**Additional Information**

**Comment by fieldOfView** [comment]
The biggest offender is the log file, which keeps growing and growing, all while copies of it being left behind.

The good news is that I my PR to not copy over the cura.log and folders named "old" when creating a new configuration folder was merged a while ago:
https://github.com/Ultimaker/Uranium/pull/356

This does not clean up your current configuration folders, but at least it should stop ballooning further.

**Comment by alekseisasin** [comment]
So far as this issue was fixed before, I propose to close this issue.

**Comment by fieldOfView** [comment]
I agree
