### ISSUE TITLE
Scale tool becomes NaN and Inf

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#438]
Version: 15.09.84
Platform: Ubuntu 15.04 Unity
Qt version: 5.4.1
PyQt version: 5.4.1

Steps to reproduce:
- Start Cura and make sure it stays approximately in the default viewing angle (such that the buildplate's UM2 logo is towards the top left of the viewport).
- Load a model.
- Select the model.
- Click the scale tool.
- Now drag the _green_ axis handle (the one that scales the Y-direction) all the way to the top-left of the screen. This possibly depends on screen resolution; my display is 1920x1200. This doesn't seem to depend on the size of the Cura window itself.

Expected behaviour:
- The model becomes very large.
- CuraEngine doesn't start, because it wouldn't fit on the buildplate.

Observed behaviour:
- The model first becomes very large, but then disappears.
- The scale tool displays a scale of "nan".
- Slicing starts, but gets stuck at 0%.

I think the way that scaling is computed when handling the handles of the scale tool could use some tweaking. I've also gotten it to scale to negative values sometimes, but it's difficult to reproduce the movements for that, let alone describe them here. Just fiddle with it and you'll get it to go negative.

**Comment by BagelOrb** [comment]
Cannot reproduce
