### ISSUE TITLE
Won't accept my custom settings

### ISSUE THREAD

**Issue by richardkaer** [Ultimaker/Cura#4380]
Dremel Digilab 3D Slicer (New)

Windows 10

Dremel Digilab

I have changed the settings multiple times and saved them to a new profile but when I go to print none of the new settings are used, it just returns to the default settings.

How do I get the custom settings to override the default settings or is this a bug?

An example is the default setting for Eco-ABS temperature is 255 but that strings really bad.  The file wants 220 degrees.  The slicer settings are set for the 220 and it saves the settings but when I ship it to the printer it doesn't use any of the new settings.

**Comment by fieldOfView** [comment]
Sounds like a bug, but we can't be sure.

The Dremel Digilab 3D Slicer is a modified version of Cura, based on a fairly old release (Cura 2.7, one year old). We don't really know what they've changed, and as a result we cannot help you much here. Please ask Dremel for support for their printers and their software.

**Comment by alekseisasin** [comment]
@richardkaer , if you are using modified (not official) version of Cura then we cannot guarantee the correct workflow. You can share the project and we can test it in official Cura or you can do it by yourself downloading Cura from https://ultimaker.com/en/products/ultimaker-cura-software.

**Comment by ChrisTerBeke** [comment]
We do not support modified versions of Cura here. Please contact Dremel directly.
