### ISSUE TITLE
Z-hop not working over empty bed.

### ISSUE THREAD

**Issue by YerBabiE** [Ultimaker/Cura#4392]
**Application Version**
Latest v3.4.1

**Platform**
Mac OS

**Printer**
anet A8

**Steps to Reproduce**
z hop feature does not work over blank bed, so nozzle if putting streaks on bed which is transfering to the 1st layer.

**Actual Results**
my mirror finish is not good on first layer.

**Expected results**
Z hop should treat the bed like the rest of the print if there will be filli going down.

**Additional Information**

**Comment by smartavionics** [comment]
You don't provide any useful information like a cura project or screen shots or gcode so it's difficult to understand exactly what is happening but if you try the new cura 3.5 beta and use the no skin combing mode you may find that you get better results.

**Comment by YerBabiE** [comment]
yer, I don't know what to say, the gcode / project does not matter, the problem is pretty basic, z hop does not work over a "blank" bed, only printed areas, so if that area of the bed is going to be printed on (first layer) then it can be market by a move prior to this first layer going down.

**Comment by smartavionics** [comment]
OK, but if you don't provide any useful info, you can't expect to get your issue resolved. If you provided me with a project file (.3mf) for some example I could load that here and look into what is happening and whether more recent cura releases have already fixed your issue.

**Comment by Ghostkeeper** [comment]
Disable the setting: "Z Hop Only Over Printed Parts".
