### ISSUE TITLE
[3.5]Importing trimesh does not work on frozen builds

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Cura#4394]
**Application Version**
3.5 beta

**Platform**
Windows, likely others as well

**Printer**
n/a

**Steps to Reproduce**
* create a plugin that imports trimesh
```import trimesh```

**Actual Results**
The plugin won't load (with an ImportError)

The frozen build has the following unmet dependencies:
* decorator (https://pypi.org/project/decorator/)
* packaging (https://pypi.org/project/packaging/)
* pyparsing (https://pypi.org/project/pyparsing/)

Some required resources are also stripped from the frozen build, namely trimesh/resources/*.template

There's also a soft dependecy on rtree (https://pypi.org/project/rtree/) for some functionality in trimesh that would be very nice to have, but this is not blocking.

**Expected results**
Importing trimesh works and the plugin loads

**Comment by Appesteijn** [comment]
CURA-5752

**Comment by Appesteijn** [comment]
This also blocks your MeshTools plugin

**Comment by LipuFei** [comment]
@fieldOfView Do you have a plugin that I can test with? I'm creating new 3.5 builds now with trimesh dependencies.

**Comment by Appesteijn** [comment]
It is in the contribution portal, I'll send you a link

**Comment by fieldOfView** [comment]
For reference: https://github.com/fieldOfView/MeshTools
