### ISSUE TITLE
[3.4.1] Supports don't touch the model

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4397]
Hi there. 
**Application Version**
3.4.1

**Platform**
Windows 10 x64

**Printer**
Creality cr-10s

**Steps to Reproduce**
Use normal or tree supports

**Actual Results**
Supports don't touch the models both from the bottom and the hairs. 

**Expected results**
Supports work as intended.

**Additional Information**
Also, I will ask why in the left it is seeable a yellow "overextrusion"(while it should still follow the red shell shape), and the model sliced itself as seen doesn't follow the blue perimeter. 
I don't know if it is related, but the sharp edges are completely skipped too, like the hairs.
![supports 1](https://user-images.githubusercontent.com/20385116/45828861-e2a2d180-bcf9-11e8-955d-873dfbad874e.png)
![supports 2](https://user-images.githubusercontent.com/20385116/45828862-e2a2d180-bcf9-11e8-919a-bc658fd12600.png)

**Comment by rburema** [comment]
Hi @Liger0, I'm sorry, but we've decided to defer this one until later, as too many other pressing issues need our attention. cheers, Remco.

**Comment by adrianmihalko** [comment]
Same problem here.
<img width="1225" alt="screenshot 2019-01-05 at 01 26 23" src="https://user-images.githubusercontent.com/733361/50717770-31e2f700-108a-11e9-9996-acaa0bf3c923.png">

[project.3mf.zip](https://github.com/Ultimaker/Cura/files/2728965/project.3mf.zip)
