### ISSUE TITLE
Show progressbar when loading a file

### ISSUE THREAD

**Issue by TMHogenhout** [Ultimaker/Cura#44]
Application Version: 15.05.94
Platform: Ubuntu 15.04 64-bit
Qt: 5.4.1
PyQt: 5.4.1
Display Driver: xserver-xorg-video-intel 2.99.917

Steps to Reproduce:
 - Open a file

Actual Results:
- There is no progress shown, so the user does not know what to expect 

Expected results:
- There is progress shown. The user knows whether to wait or to get a cup of coffee.

**Comment by awhiemstra** [comment]
This is now fixed.
