### ISSUE TITLE
Support material on top surfaces (dual bent surfaces?)

### ISSUE THREAD

**Issue by tebz** [Ultimaker/Cura#4400]
I get support printed on top of dual bent surfaces.

Cura 3.4.1
UM3
Windows 10
[UM3_MTME410 lucka V1 Debug.curaproject.zip](https://github.com/Ultimaker/Cura/files/2406294/UM3_MTME410.lucka.V1.Debug.curaproject.zip)

**Comment by alekseisasin** [comment]
Hi @tebz , I loading your project I discovered settings which I could not update, the setting "Enable Conical Support" was enabled and I could not disable. In your case, the setting Support Horizontal Expansion is high and should not be 2, set it to 1 and it will work fine.
But default Fine quality has Support Horizontal expansion value 0.2, in your project 3, it is also strange. For this reason, I assume something went wrong before while updating the project or the default settings were changed.
I will close this ticket for reason that used parameters had high values.
