### ISSUE TITLE
[3.4.1] Cura making wrong GCODE with "Scalable Extra Prime"

### ISSUE THREAD

**Issue by digiTALker** [Ultimaker/Cura#4401]
**3.4.1**

**Win7x64**

**RepRap Repetier  firmware**

[CFDMP_EGG_SEPERATOR_V3.zip](https://github.com/Ultimaker/Cura/files/2406832/CFDMP_EGG_SEPERATOR_V3.zip)

**Steps to Reproduce**
Check if Scalable Extra Prime are enabled.
![Check Scalable Extra Prime](https://i.imgur.com/JDuavIX.png)
Put script to end of GCODE
![Put script to end of GCODE](https://i.imgur.com/iTex2Ao.png)

**Actual Results**
Open generated GCODE and look at the part with END-script.
![Open generated GCODE and look to part with END-script.](https://i.imgur.com/8nxhkTN.png)
And instead of retraction we get extruding.

**Expected results**
Correct END SCRIPT

**Additional Information**

**Comment by fieldOfView** [comment]
Scalable Extra Prime is a plugin by @Pheneeny, the best is to open an issue over at its own issue queue:
https://github.com/Pheneeny/CuraPlugin-ScalableExtraPrime

A hint to the author of the plugin (which you may want to add to the issue) is that the plugin should not process the last "layer" in the gcode_data.

**Comment by Pheneeny** [comment]
This should be covered by this issue: [Retraction in End G-Code also modified by plugin](https://github.com/Pheneeny/CuraPlugin-ScalableExtraPrime/issues/6)

I unfortunately didn't see that issue until today, but I'm currently working on a fix.

This issue can probably be closed on this repository.
