### ISSUE TITLE
Cura 3.4.1 Layer view no layer height scroll bar

### ISSUE THREAD

**Issue by icerabbitje** [Ultimaker/Cura#4407]
**Application Version**

Cura 3.4.1
**Platform**

OS X 10.12.4
**Printer**

Creality Ender 3
**Steps to Reproduce**

Switch to layer view
**Actual Results**

Layer view starts without vertical scroll bar
**Expected results**

Layer view starts with vertical scroll bar
**Additional Information**

![screen shot 2018-09-22 at 11 16 12 am](https://user-images.githubusercontent.com/43499027/45918711-2c55fe00-be59-11e8-9ecc-2442b066a25d.png)

**Comment by fieldOfView** [comment]
You probably have to press "prepare" in the lower right corner first.

Auto-slicing has been turned off by default in a previous version. You can enable it on the General pane of the preferences.
