### ISSUE TITLE
[OS X] Lost settings

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#441]
I'm unable to reproduce this, but still wanted to show you that I'm getting this. In case someone else has seen the same problem:
![image](https://cloud.githubusercontent.com/assets/191236/10135883/96be87f8-65f1-11e5-9b01-08c97ce34bf5.png)

It's with the currently [latest](http://software.ultimaker.com/Cura_closed_beta/15.10/Cura-15.09.84-Darwin.dmg) version on OS X 10.10.5.

**Comment by quillford** [comment]
I got the same issue on 15.06.03. I think it was caused by partially deleting some Cura files while leaving others. Once I removed all the Cura files (including <15.04) and reinstalled 15.06.3, it worked fine.
