### ISSUE TITLE
The gcode generated prints a totally different model vis-a-vis the stl file

### ISSUE THREAD

**Issue by AshokBaijal** [Ultimaker/Cura#4412]
**Application Version**
 Ver 3.2.1

**Platform**
Windows 10

**Printer**
 Tevo Tarantula

**Steps to Reproduce**
 The stl file MiniPlaners.stl attached with the generated MiniPlaners.gcode 

**Actual Results**
The model printed is different from the stl file. The model as shown in Cura in Solid view is different to what is seen in Layer view. The print is as shown in the Layer view

**Expected results**
 The gcode should represent the model as per the stl file. (I have added a txt extension for upload purpose only)

**Additional Information**
 The original Sketchup file used for creating the model is also attached

[MiniPlaners.gcode.txt](https://github.com/Ultimaker/Cura/files/2408407/MiniPlaners.gcode.txt)
[MiniPlaners.skp.txt](https://github.com/Ultimaker/Cura/files/2408408/MiniPlaners.skp.txt)
[MiniPlaners.stl.txt](https://github.com/Ultimaker/Cura/files/2408409/MiniPlaners.stl.txt)

**Comment by fieldOfView** [comment]
When you inspect your model in X-ray view, you will see that it has defects:
![image](https://user-images.githubusercontent.com/143551/45925737-9505af00-bf1b-11e8-92de-e40c87330911.png)

You will have to repair the model before it prints well.

Sketchup will let you create models that are horrible for 3d printing. Unless you know exactly what you are doing, I advice against using Sketchup for 3d printing. TinkerCAD is somewhat comparable, and its output is almost always 3d printable.
