### ISSUE TITLE
brim on the inside of the model produces crap

### ISSUE THREAD

**Issue by nikscha** [Ultimaker/Cura#4415]
**Application Version**
3.4

**Platform**
win 10 64 bit

**Printer**

**Steps to Reproduce**
dont know, just sliced with attached settings

**Actual Results**
brim prints everywhere, also next to the buildplate and seemingly to infinity.

**Expected results**
brim should be neat and tidy inside the model

**Additional Information**
screenshot of layerview attached, slicing profile attached
![screenshot 1](https://user-images.githubusercontent.com/38561129/45928661-a664b080-bf47-11e8-8ee0-83cc9571fb02.png)
[TevolmBugReport.zip](https://github.com/Ultimaker/Cura/files/2408762/TevolmBugReport.zip)

**Comment by alekseisasin** [comment]
Hi @nikscha , Indeed it was a bug in Cura 3.4 version. It is fixed and the fix will be added to the next Cura version.
Thank you for reporting this to us.
