### ISSUE TITLE
[3.4.1] Cura does not reconnect to octoprint when computer wakes up

### ISSUE THREAD

**Issue by biz2000** [Ultimaker/Cura#4421]
**Application Version**
3.4.1

**Platform**
Windows 7

**Printer**
CR10

**Steps to Reproduce**
Connect to octoprint. The "print with octoprint" button is available. Make the  computer go to sleep. Get out of sleep.

**Actual Results**
Button turns to "save to file". You have to go to your printer's settings menu to connect to octoprint again.

**Expected results**
Either try to reconnect when back from sleep mode, or add a shortcut button "connect to octoprint" somewhere, like near the current printer's name at the top of the settings menu.

**Comment by nallath** [comment]
Please report this issue on https://github.com/fieldOfView/OctoPrintPlugin
