### ISSUE TITLE
[3.3.1] Can't save and load support blocks -- any workarounds?

### ISSUE THREAD

**Issue by fusentasticus** [Ultimaker/Cura#4424]
Positioning a support block may be challenging. So I'm trying to save this work -- for when I later print a new version of my model. 

But `Save as` STL, followed by later `open` loads the block as as something to be printed, not as a support block.

Is this a bug? Or, maybe I'm asking for a feature request? Searched around -- didn't find answers.

Thx

**Comment by fieldOfView** [comment]
STLs can only have single models, and cannot distinguish between a normal model and a support mesh.
Save your files as a "project", and they should retain all models and settings.

PS: do you realize that you can use the move, rotate and scale tools on the placed support blocks?

**Comment by ChrisTerBeke** [comment]
@fieldOfView is right here. To save all settings associated with Cura, save it as project. Otherwise you loose Cura specific data. In the new version, we've made this more clear by calling other options 'export' instead of 'save'.
