### ISSUE TITLE
Not responding after some time [3.0.4-3.5]

### ISSUE THREAD

**Issue by Austin4705** [Ultimaker/Cura#4426]
**Application Version**
3.0.4-3.5

**Platform**
Windows 10

**Printer**
Tevo Tornado 

**Steps to Reproduce**
Install Cura and have it not respond 

**Actual Results**
Cura doesn't respond and crashes

**Expected results**
CURA should open and work properly

**Additional Information**
When I install cura it works for a bit, then about 4-5 hours later it doesn't respond and crashes. Then closing the program or rebooting the pc doesn't work. After that, I uninstall the software  (which includes deleting all AppData for CURA as well) and install a new version. The same issue happens again.
Here is the Link to the CURA log file:
https://drive.google.com/file/d/1_aD9jT2DzSDCrjgCp9D116ymzuDiTl7N/view?usp=sharing

**Comment by alekseisasin** [comment]
Do you have the issue for all Cura version 3.0.4 to 3.5Beta? If yes, then I suspect the issue is related to your computer. Please check the virtual memory, maybe you do not have enough free space on hard drive, or some other application uses all computer resources, like your antivirus.

**Comment by Austin4705** [comment]
I do, I have 20 GB free on my SSD and about 1tb on my hard drive. I don't use an antivirus, while I should. Do you think it could because I had recently upgraded my pc from intel to amd? If you have any ideas please tell me.

**Comment by alekseisasin** [comment]
I cannot explain why it works only for a couple of hours and after restart no more. Only after installation. We do not have a similar issue.
In your log file, I am missing Initialized OpenGL subsystems. Do you have proper drivers for your graphical card?

**Comment by LipuFei** [comment]
Hi @Austin4705 , did you do anything before you left it for 4-5 hours? Any specific thing/steps can help, thanks!

**Comment by Ghostkeeper** [comment]
We could not reproduce this problem. We can't do anything to help fixing it unless we get more information.
