### ISSUE TITLE
15.10 Can't switch view 

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#443]
I cannot switch to layer view after I have viewed the layers and then cleared the platform.

I just wanted to switch to normal view before loading the new object in.

**Comment by nallath** [comment]
Stangely enough it does work when you only delete the objects (and not clear the platform)

**Comment by BagelOrb** [comment]
In that case it might be related to https://github.com/Ultimaker/Cura/issues/444

**Comment by BagelOrb** [comment]
I just tried with Clear platform and got the same results...
