### ISSUE TITLE
Material Compatibility

### ISSUE THREAD

**Issue by Lschmitendorf** [Ultimaker/Cura#4432]
What's up the the material compatibility check in 3.4.1 for the Ultimaker 3 and 3 Extended?  This feature has essentially disabled the second extruder on my Ultimaker 3 Extended even though Ultimaker shows PLA and PVA as compatible materials because the Cura software deems the materials incompatible.

![capture2](https://user-images.githubusercontent.com/43620474/46104536-3188b500-c199-11e8-9c5d-1cb495f7e3bd.PNG)
![capture1](https://user-images.githubusercontent.com/43620474/46104537-3188b500-c199-11e8-86c6-a29a79edace1.PNG)

**Comment by fieldOfView** [comment]
I think it wants you to use a BB core for PVA.

**Comment by ChrisTerBeke** [comment]
> I think it wants you to use a BB core for PVA.

This

**Comment by Lschmitendorf** [comment]
I am using a BB cove for PVA, the printer will not let you load the material any other way.

**Comment by ChrisTerBeke** [comment]
If you have your printer network connected Cura will sync the physical configuration of the printer.

**Comment by Lschmitendorf** [comment]
The printer is network connected.  I manually change the second core in Cura and it is printing.  Letting it run and see what happens.

Thanks all for the quick feedback!
