### ISSUE TITLE
15.10 object options while non-selected

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#444]
Steps:
- delete sliced object
- right click on empty platform
- select Center object on platform

Result:
-----------------------------------------

Version: 15.09.83
Platform: Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "/home/tim/Development/Cura/cura/CuraApplication.py", line 297, in centerObject
    if node.getParent() and node.getParent().callDecoration("isGroup"):
AttributeError: 'NoneType' object has no attribute 'getParent'

**Comment by awhiemstra** [comment]
Should be fixed in .90
