### ISSUE TITLE
Combing mode not working when printing gear

### ISSUE THREAD

**Issue by Taiko1976** [Ultimaker/Cura#4446]
**Application Version**
3.4.1

**Platform**
Windows 7 64-bit

**Printer**
Selfmade RepRap

**Actual Results**
Nozzle moves outside printed area when printing gear, resulting in closed gear teeth from oozing

**Expected results**
When Combing Mode is set to "All" the description says that the nozzle will stay within the printed area.

**Additional Information**
![gear](https://user-images.githubusercontent.com/18835558/46253967-262ed580-c488-11e8-8f67-d3112309f024.png)

[CFDMP_Part Studio 1 - gear.zip](https://github.com/Ultimaker/Cura/files/2431290/CFDMP_Part.Studio.1.-.gear.zip)

**Comment by diegopradogesto** [comment]
It doesn't happen with a freshly new Custom FDM Printer with by-default settings (combing_mode = All). 
![image](https://user-images.githubusercontent.com/15830521/46335991-b1939c80-c629-11e8-9ce3-a4372b007ba4.png)

So I'm pretty sure there are others settings you defined that are creating this output. Please provide a Cura Project File (_File->Save Project_)

**Comment by Taiko1976** [comment]
As requested:

[Untitled.zip](https://github.com/Ultimaker/Cura/files/2440744/Untitled.zip)

**Comment by diegopradogesto** [comment]
The culprit is the value of the _Retraction Minimum Travel_. You set it to 10mm, indicating that no retraction is happening if the distance between points is less than this value.

However it should comb anyway, so it seems like a bug. For the moment, the workaround for you is to change this value.

**Comment by Taiko1976** [comment]
Thank you, looking forward to the bug fix. I'll try the workaround, too, although I tried it before and opted against it because of grinding issued on the filament. But thank you for the hint.

**Comment by Vandrasc** [comment]
Devs see CURA-5818

**Comment by nallath** [comment]
This should be fixed for the next release.
