### ISSUE TITLE
[3.4.1] Can only select models on primary display in OSX

### ISSUE THREAD

**Issue by sbuzonas** [Ultimaker/Cura#4457]
**Application Version**
3.4.1

**Platform**
OSX High Sierra

**Steps to Reproduce**
Open Cura, import STL.
Move window to second screen.
Try to select object.

**Actual Results**
Objects can only be selected on primary screen.

**Expected results**
Objects should be able to be selected on any screen the window is displayed on.

**Additional Information**
Can be selected in other workspace as long as it is on the primary screen.
Object can be selected with Select All.
If the object is selected; any attempts to use a handle, like to rotate; the object becomes deselected.

**Comment by alekseisasin** [comment]
We do the same thing every day and do not have any issue with selecting models. 
Try to rotate your build plate and select the model
How do you connect the second screen?

**Comment by sbuzonas** [comment]
One screen is hdmi the other is thunderbolt. Rotating the build plate does not change the ability to select a model.

If the primary screen is unavailable (laptop lid closed) I can select the model on both displays.

**Comment by alekseisasin** [comment]
Then obviously it is the drivers' issue. You can try Cura 3.5 version, it was recently released.

**Comment by alekseisasin** [comment]
Good to know, then I will close the issue.
