### ISSUE TITLE
Feature request: Cost estimation

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#446]
From Martijn van Gils and many others:

Make a simple cost estimate based on the printing time and the material.

Perhaps a button next to the time estimates taking you to a new menu where you can enter time costs and material costs?

Perhaps a disclaimer saying the price is an indication based on average costs.

**Comment by nallath** [comment]
https://github.com/nallath/PrintCostCalculator

**Comment by awhiemstra** [comment]
Addionally, any effort to integrate this into the main Cura Ui will need to wait until we have a better way of handling materials since you can then set density/cost per material properly.
