### ISSUE TITLE
[3.5.0] Cura will not connect to Ender 3 Via USB

### ISSUE THREAD

**Issue by Delaser** [Ultimaker/Cura#4464]
Issue appears to be identical to the 3.4.1 version,
https://github.com/Ultimaker/Cura/issues/4196

however the workaround of editing the USBPrinting plugin does not resolve the issue in 3.5.0
https://github.com/Ultimaker/Cura/issues/4196#issuecomment-412273718

**Comment by nallath** [comment]
The answer, unfortunately, is also the same. We can't test with the Ender 3.

**Comment by ianpaschal** [comment]
Since the issue is identical, please comment there that the workaround doesn't work in 3.5.0. In the future, please avoid opening duplicate issue threads as it makes it very hard to keep track of.
