### ISSUE TITLE
15.10 - Feature Center object on platform center model in Z axis.

### ISSUE THREAD

**Issue by Hyna** [Ultimaker/Cura#447]
Feature "Center object on platform" should center model only in X and Y axis. Currently it center the object also in Z axis. Half of the model is then under the build plate. Correct behavior is that object should be placed on platform.

**Comment by nallath** [comment]
Hmm, thats odd. I did made some changes so that should work. Seems that it doesn't correctly work for all models.

**Comment by Hyna** [comment]
Tested on Dev .85@Win64bit, same behavior on .83@Linux

**Comment by nallath** [comment]
Should be fixed for next release.
