### ISSUE TITLE
Nobody responds to cura-build-environment issues

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#4476]
**Application Version**

master

**Platform**

Any

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

I have two open cura-build-environment issues and nobody has responded in any way. I really would appreciate some help if that is possible?

**Comment by ChrisTerBeke** [comment]
I actually proposed closing those issue threads and converge everything here (so it get's actually look at), but others didn't deem it necessary, apparently now resulting in things getting overlooked...

My suggestion to you is to open all issues here and have the devs deal with it.

**Comment by smartavionics** [comment]
Understood.

I'll close this now.
