### ISSUE TITLE
Cura won't detect my Printer!

### ISSUE THREAD

**Issue by MeSheepMan** [Ultimaker/Cura#4479]
**Application Version**
3.2.1

**Platform**
Win 10

**Printer**
Monoprice Delta mini

**Steps to Reproduce**
I open up Cura

**Actual Results**
It Detected my printer twice at two different occasions and won't find it again

**Expected results**
It's suppose to see that my printer's connected

**Additional Information**
![image](https://user-images.githubusercontent.com/43858760/46491073-8d1cf900-c7be-11e8-9649-723e0213aca9.png)

**Comment by MeSheepMan** [comment]
If anyone knows away to fix this that would be amazing!

**Comment by ChrisTerBeke** [comment]
A fix for this was made a while back (https://github.com/Ultimaker/Cura/pull/3855), please try a newer version of Cura. As we don't have this printer we can't test it, so we have to go by the community contributions when it comes to 3rd party printers.

**Comment by MeSheepMan** [comment]
Thank you very much! (sorry I posted such a easy problem) It's now running and great at that. :D
