### ISSUE TITLE
save as gcode

### ISSUE THREAD

**Issue by smitty101** [Ultimaker/Cura#4481]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smitty101** [comment]
why wont the new cura let me save files as gcode

**Comment by Vandrasc** [comment]
Hi @smitty101 , could you please fill in the above template so we can help you better? What printer are you using? Are there any errors in the log? Which platform are you using? 

Thank you!

**Comment by ChrisTerBeke** [comment]
Did you try file -> export -> Gcode?

**Comment by ChrisTerBeke** [comment]
Or after slicing, use 'save to file' in the bottom right?

**Comment by Ghostkeeper** [comment]
We'll assume that the problem arose from the File menu being restyled. Please use "Export..." or just press the blue button in the bottom right hand corner.
