### ISSUE TITLE
Migration from 3.4 to 3.5 will use backup folders if they exist

### ISSUE THREAD

**Issue by steckdev** [Ultimaker/Cura#4482]
As a user if I have copied my %appdata%/cura/3.4 folder to create a manual back and named it something like 3.4-backup then this will be used when loading 3.5 for the first time.

I believe this issue exists in this script.
https://github.com/Ultimaker/Cura/blob/master/plugins/VersionUpgrade/VersionUpgrade34to35/VersionUpgrade34to35.py

**Application Version**
3.4 -> 3.4

**Platform**
Windows 10

**Printer**
Ender 3 (But not relevant)

**Steps to Reproduce**
Install 3.4
Create profiles
go to %appdata%/cura copy the 3.4 to 3.4-backup
Make additional changes to 3.4 
Download 3.5
Load 3.5 with the %appdata/cura/3.5 removed

**Actual Results**
Previous backup settings appear in the UI

**Expected results**
You are looking specifically at the versions expected or atleast looking for a regex patter of 3.4+ decimal or number after it with specific behavior

**Additional Information**
Work around exists... but not easy to know what is going on easily.

**Comment by alekseisasin** [comment]
Hi @steckdev , did you try to make a backup folder with a name: "backup-3.4". Or just copy the backup folder to another.
By the fact, your suggestion for improvement might lead to edge cases where we need to verify folder how it should be, the change might require a lot of testing on different Operation Systems. For this reason, I advise to use name "backup-3.4" and it will work.
