### ISSUE TITLE
15.10 Revert to default not working

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#449]
Steps:
- edit a setting
- click [ Reset to default ] the refresh button

Expected: value changes to default
Actual: (displayed) value remains the same

**Comment by robomaniac** [comment]
yes! I approve this msg!  :stuck_out_tongue: I have the same bug I was going to post this too.

**Comment by nallath** [comment]
It's only the displayed value that doesn't change.

**Comment by TMHogenhout** [comment]
https://github.com/Ultimaker/Uranium/commit/61aea7acf6599dd2143a3c97be0b64af493d5e18
https://github.com/Ultimaker/Uranium/commit/537c7c5e361527eb6009f188b84e7ecc45aa4722
https://github.com/Ultimaker/Uranium/commit/f36e9f5074f664ab27aa36fde6ab5563045b314c
