### ISSUE TITLE
CuraEngine can crash when Tree Support is enabled

### ISSUE THREAD

**Issue by PierreAuge** [Ultimaker/Cura#4491]
**Application Version**
3.5.0

**Platform**
windows 10

**Printer**
modified anet a8

**Steps to Reproduce**
attempt to slice more than one model at a time using tree supports

**Actual Results**
hangs indefinitely

**Expected results**
slicing

same platter and settings in 3.4.1 works with no issues

**Additional Information**

<img width="1035" alt="capture" src="https://user-images.githubusercontent.com/4925365/46535861-a1263080-c87a-11e8-9021-443d4cc45bb7.PNG">

[CFFFP_X Roller.zip](https://github.com/Ultimaker/Cura/files/2450317/CFFFP_X.Roller.zip)

[cura.log](https://github.com/Ultimaker/Cura/files/2450330/cura.log)

**Comment by alekseisasin** [comment]
DEV: CURA-5798

**Comment by diegopradogesto** [comment]
Weird... it does slice to me with 3.5 in Windows 10
![image](https://user-images.githubusercontent.com/15830521/46660147-b5d63180-cbb6-11e8-9858-c0cadc020c48.png)

**Comment by LipuFei** [comment]
Hi @PierreAuge , looks like you are running more than 1 Curas side by side. Could you try just running 3.5 see if the problem is there?

**Comment by LipuFei** [comment]
Hi @PierreAuge , we have found that this is a bug in TreeSupport. You don't need to try running one Cura.

**Comment by PierreAuge** [comment]
Thank you!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Lipu FeiSent: Tuesday, October 9, 2018 8:43 AMTo: Ultimaker/CuraReply To: Ultimaker/CuraCc: PierreAuge; MentionSubject: Re: [Ultimaker/Cura] cura 3.5.0 fails to slice (#4491)Hi @PierreAuge , we have found that this is a bug in TreeSupport. You don't need to try running one Cura.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ultimaker/Cura","title":"Ultimaker/Cura","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ultimaker/Cura"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LipuFei in #4491: Hi @PierreAuge , we have found that this is a bug in TreeSupport. You don't need to try running one Cura."}],"action":{"name":"View Issue","url":"https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428176920"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428176920",
"url": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428176920",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Ultimaker/Cura] cura 3.5.0 fails to slice (#4491)",
"sections": [
{
"text": "",
"activityTitle": "**Lipu Fei**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@LipuFei",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Ultimaker/Cura\",\n\"issueId\": 4491,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Ultimaker/Cura\",\n\"issueId\": 4491\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428176920"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388543562\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by LipuFei** [comment]
Hi @PierreAuge , after discussed with the team, we decided to fix this for the next major release but not in `3.5.x`. As a workaround, could you try using the regular support instead of tree support? Tree support is still experimental.

**Comment by PierreAuge** [comment]
Yes, already on it. Cheers,Pierre                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Lipu FeiSent: Wednesday, October 10, 2018 4:32 AMTo: Ultimaker/CuraReply To: Ultimaker/CuraCc: PierreAuge; MentionSubject: Re: [Ultimaker/Cura] [3.5] CuraEngine can crash when Tree Support is enabled (#4491)Hi @PierreAuge , after discussed with the team, we decided to fix this for the next major release but not in 3.5.x. As a workaround, could you try using the regular support instead of tree support? Tree support is still experimental.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ultimaker/Cura","title":"Ultimaker/Cura","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ultimaker/Cura"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LipuFei in #4491: Hi @PierreAuge , after discussed with the team, we decided to fix this for the next major release but not in `3.5.x`. As a workaround, could you try using the regular support instead of tree support? Tree support is still experimental."}],"action":{"name":"View Issue","url":"https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428485464"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428485464",
"url": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428485464",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Ultimaker/Cura] [3.5] CuraEngine can crash when Tree Support is enabled (#4491)",
"sections": [
{
"text": "",
"activityTitle": "**Lipu Fei**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@LipuFei",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Ultimaker/Cura\",\n\"issueId\": 4491,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Ultimaker/Cura\",\n\"issueId\": 4491\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Ultimaker/Cura/issues/4491#issuecomment-428485464"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 388543562\n}"
}
],
"themeColor": "26292E"
}
]
