### ISSUE TITLE
octoprint

### ISSUE THREAD

**Issue by phillroy** [Ultimaker/Cura#4494]
I have a problem with CURA and OCTOPRINT

CURA 3.5.0

MAC OS 

Prusa 3 mk2

Says no printer attached as it doesn't have octoprint in this version 
Having to revert back to old version as this doesn't work
Need Octoprint with this version 
Can't connect to printer as no octoprint.

**Comment by fieldOfView** [comment]
You have to install a new version of the plugin from the Toolbox.

**Comment by phillroy** [comment]
Didn't realise that needed to reinstall plugin
