### ISSUE TITLE
Tell it when to finish a print at the maximum quality

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#45]
As a user I'd like to tell Cura to finish a print at the highest quality settings possible, and finish before the time I tell it to.

Suggested during Ultimaker Evening.

**Comment by BagelOrb** [comment]
This will be implemented by the time vs quality slider which can be found in simple mode.

**Comment by awhiemstra** [comment]
It is a feature request on top of the time/quality slider, so that you can say "finish at 20:00 tonight" and it will try and find settings that match that time.

**Comment by BagelOrb** [comment]
That should be fairly easy to implement.

Better say "Finished around 20:00" for example...

**Comment by Appesteijn** [comment]
Closing this issue, because it is from 2015
