### ISSUE TITLE
The distance along the Z-axis does not match the number of layers

### ISSUE THREAD

**Issue by alexand1** [Ultimaker/Cura#4503]
The distance along the Z-axis does not match the number of layers

**Application Version** - 3.5.0

**Platform** - Windows 10

**Printer** - Ultimaker 2

![1](https://user-images.githubusercontent.com/43906115/46571725-cdc56f80-c982-11e8-8af4-4d3746e0bcec.png)

**Comment by alekseisasin** [comment]
@alexand1 , Could you please share your project?

**Comment by nallath** [comment]
Also, if you want to change the layer height, it's best to switch the profile altogether.

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this issue. I loaded a cube of 40mm tall, and sliced it with 0.1mm layer height and 0.27mm initial layer height. This produced 398 layers, which is correct.

It must be model dependent.
