### ISSUE TITLE
[3.5.0] Connect Infill Lines + Gradual Infill steps = Missing intermediate infill!!

### ISSUE THREAD

**Issue by lapidations** [Ultimaker/Cura#4507]
**Application Version**
Cura 3.5.0

**Platform**
Windows 10 fully Up-to-date

**Printer**
CR10 Running last Marlin version (1.1.8 I guess?)
[ConnectInfillBug.zip](https://github.com/Ultimaker/Cura/files/2453285/ConnectInfillBug.zip)

**Steps to Reproduce**
Simple cube or cylinder as model
50% infill
Gradual infill steps 3
Gradual infill height 1mm
Connect infill lines is set to ON

**Actual Results**
When Connect Infill lines is on, The intermediate infill densities will not be printed, I.E.: Only the first and last "steps" of the gradual infill are printed, there will be vertical gap in between them, making the gradual infill pratically useless. Without connect infill lines it will work fine.

**Expected results**
In Cura 3.4.1, this combination would result in progressivelly more dense infill towards the top surface, while still having the infill lines connected.

**Additional Information**

You can see the problem below:
![withconnectinfilllines](https://user-images.githubusercontent.com/3412087/46574554-77086780-c97b-11e8-8e99-c0e80d8e9cce.png)

Here is what you get without connect infill lines. In Cura 3.4.1 you could have gradual infill while still having connected infill lines.
![withoutconnectinfilllines](https://user-images.githubusercontent.com/3412087/46574555-77a0fe00-c97b-11e8-98c8-a046dd702aab.png)

**Comment by lapidations** [comment]
I'd like to say that I love the work you have done with Cura 3.5.0, congratulations, you are the best! But as I mainly print Nylon engineering parts that need to be super sturdy, I will need to keep using Cura 3.4.1 while this issue is not fixed.

**Comment by Ghostkeeper** [comment]
This is fixed in Cura 3.6.0. Thanks for the report!
