### ISSUE TITLE
lost printer profile

### ISSUE THREAD

**Issue by stilgarhammer** [Ultimaker/Cura#4508]
**Application Version**
2.5.0

**Platform**
windows 7

**Printer**
prusa i3

**Steps to Reproduce**
close cura

**Actual Results**
reopen cura and printer profile and all settings gone

**Expected results**
no issues, all settings intact

**Additional Information**

**Comment by ChrisTerBeke** [comment]
2.5.0? That's very old, we're not supporting it anymore.

**Comment by stilgarhammer** [comment]
everything was working good, I closed it last night. open it this morning and all settings gone. is there a file i can fine to restore those setting?
I liked 2.5.0

**Comment by LipuFei** [comment]
Hi @stilgarhammer , you can have a look at your configuration folder, which should be located in `C:\Users\<your-user-name>\AppData\Roaming\cura`. Unfortunately, we have officially ceased support for Cura versions before 2.7. Could you try 2.7 or something?

**Comment by alekseisasin** [comment]
@stilgarhammer , did you have recent updates in windows? On the internet a lot of articles that Windows 10 update might remove personal data. For Windows 7 it could be also.

**Comment by Ghostkeeper** [comment]
We can't really help you with this. We have not enough information to reproduce the issue and it's very unlikely that it reproduces in version 4.0. We're not going to release a new version of 2.5.
