### ISSUE TITLE
15.09.85 x64: Crash on Machine Create

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#451]
![image](https://cloud.githubusercontent.com/assets/12439543/10221699/8114808a-6815-11e5-975f-c510e67d0e44.png)
![image](https://cloud.githubusercontent.com/assets/12439543/10221705/8bdd23fa-6815-11e5-973b-e0cc83ef20d6.png)

**Comment by awhiemstra** [comment]
Looks like your UMO+ config file got corrupted. You also seem to be missing the UMO file. As far as I can tell they are included in the installer, maybe try reinstalling?

**Comment by Ghostkeeper** [comment]
How could this happen, though? Maybe with the upgrade from .84 to .85?

**Comment by CCS86** [comment]
@awhiemstra , you are right about the UMO file. I changed a setting in there to get the heated bed setting working, and forgot a comma, so it skipped that file. The UMO+ file was unmodified though. 

Now that I know where the cura.log moved, I figured out my syntax error, and created a machine from the UMO file successfully.
