### ISSUE TITLE
Cant find "Prime Tower Purge Volume" in settings?

### ISSUE THREAD

**Issue by shellcracker789** [Ultimaker/Cura#4516]
I cant seem to find "Prime Tower Purge Volume in 3.5.

**Comment by alekseisasin** [comment]
It was removed: 
"The entire purging algorithm is gone now since it purges by printing the prime tower. The prime tower should be sufficiently strong now to not need this."

**Comment by Ghostkeeper** [comment]
The reason this was removed is because we now purge along the border of the inside curve of the prime tower. If you need more purging, just make the tower thicker.
