### ISSUE TITLE
release 3.5 not on github?

### ISSUE THREAD

**Issue by burdickjp** [Ultimaker/Cura#4518]
Why isn't release 3.5 available under "releases" on github?
My package manager pulls from github.

**Comment by wilriker** [comment]
The same already happened with previous release (see https://github.com/Ultimaker/Cura/issues/4019). It seems this is very delayed.

**Comment by nallath** [comment]
Because we're very good at forgetting this

**Comment by burdickjp** [comment]
You can take comfort in knowing that you can forget this and we'll remind you every time.

**Comment by Ghostkeeper** [comment]
It's not so much the forgetting but more that I'm lazy and slightly worried that we might hit a file upload limit some day, so I'm trying to only upload one release per minor version increase. If I see a patch release coming up I'll wait for a bit to upload the version with the patch.

Anyway, 3.5.1 is uploaded now so this is fixed.
