### ISSUE TITLE
CURA 3.5 Closes when trying to add ant printer

### ISSUE THREAD

**Issue by LouieRodotech** [Ultimaker/Cura#4519]
**Application Version**

Cura 3.5
**Platform**

Win 10
**Printer**

JG Aurora A5
**Steps to Reproduce**

Open program add printer, select printer to configure application closes. 
**Actual Results**

Application closes
**Expected results**

Setup bed size
**Additional Information**

![aurora printer setings](https://user-images.githubusercontent.com/38634638/46588516-c928b600-ca6b-11e8-8cea-d392bc217846.JPG)
 works fine in ver 3.4

**Comment by Appesteijn** [comment]
Adding a custom FFF printer with that names works fine on my Mac. Can you post your logfiles?

**Comment by LipuFei** [comment]
Hi @karabas , for you JG Aurora A5, did you follow the steps on their website? For example, copying the *.json files to the latest Cura?

Link: https://jgaurorawiki.com/a5/printing-profiles

**Comment by nallath** [comment]
Since no more information was provided, I'm closing this issue.
