### ISSUE TITLE
15.09.85: Not creating log file

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#452]
On both the x32 and x64 .85 builds, Cura is no longer writing a log file that I can find, and I can't find where/if it is writing a cura.cfg file either

**Comment by awhiemstra** [comment]
It accidentally creates files in AppData/Local/UM instead of cura. This should be solved for the next build. Additonally, you can find logs etc. there.

**Comment by CCS86** [comment]
Thanks!
