### ISSUE TITLE
[Feat.REQ] "Support only" Coasting

### ISSUE THREAD

**Issue by swatti87** [Ultimaker/Cura#4533]
Coasting that only aplies to supports and its components. Entirely separate from "normal" coasting.

I have small overhangs that droop if not supported, they are very close to a nearby wall and supports tend to carry over a bit of filament leaving a "fish fin" like leftover attached to the wall.

Suppose i used "a bit too large value" of coasting in each support, they would be cut short and no filament would be carried over to the wall.

"Just an idea"

**Comment by swatti87** [comment]
Maybe an easier thing to implement: retract after support with sub-options to double the ret-distance, z-hop and run backwards to wipe the nozzle. Each separate option.

**Comment by Ghostkeeper** [comment]
This is already implemented. Please enable the Enable Bridge Settings setting and adjust the Bridge Wall Coasting setting as needed.

It only works for walls though. Implementing this also for skin is a technical problem due to the way in which skin lines are generated.
