### ISSUE TITLE
Cura 3.4.1 - Profile settings can't be updated

### ISSUE THREAD

**Issue by X-PRESSIVE** [Ultimaker/Cura#4535]
Button "Update Profile with current settings / override" in Preferences / Profiles does not update the existing profile with the current settings. It worked on 3.2 though.

Workaround is to create a new profile with the current settings and delete the old one, which is very tedious.

**Comment by LipuFei** [comment]
Hi @X-PRESSIVE Could you upload your log file and maybe your cura directory? Thanks.

**Comment by Ghostkeeper** [comment]
We have not been able to reproduce this issue. It seems to work all right. Sorry! If we have more information that allows us to reproduce the bug we might be able to solve this issue.
