### ISSUE TITLE
[3.5] Combing "not in the coating" and "in the  infill" are both present

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4536]
**Application Version**
3.5

**Platform**
Windows 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Check the combing mode options.

**Actual Results**
You can select either "not in the coating" and "in the infill"

**Expected results**
Since even in the combing description it says the "In the infill" is the option which has made obsolete the old "not in the coating" option, the latter should not be present.

**Additional Information**
![not in coating and in the infill](https://user-images.githubusercontent.com/20385116/46738840-77687180-cc9f-11e8-91fe-962fba50ca03.png)

**Comment by Liger0** [comment]
> 
> 
> Hello. The old implementation has been retained so that if people do not like the new implementation they can always go back to what they had before. Sorry, I can only work in English so if your issue is with the language then someone else will have to answer.

The description says they are the same settings, just in old cura versions it was called "not in the coating" while now it is called "in the infill". If they are the same, why keeping both?

**Comment by smartavionics** [comment]
They are not the same, they behave very differently. Perhaps the translation is poor?

**Comment by Liger0** [comment]
> 
> 
> They are not the same, they behave very differently. Perhaps the translation is poor?

Seems so then.
It literally translates into "Note that the "In infill" settings just acts like "not on the coats" of the old cura versions." 
So I can't catch the differences.

**Comment by Ghostkeeper** [comment]
The English options are "Not in Skin" (meaning, don't avoid collisions when moving inside the skin but retract instead), or "Within Infill" (meaning, only avoid collisions when moving through the infill).

What should the Italian translations be for those options, you think? The word "skin" seems to be translated as "coat" in your language so we should keep that consistent.

**Comment by Ghostkeeper** [comment]
I think the confusion comes from the last sentence of the description:

    Note that the 'Within Infill' option behaves exactly like the 'Not in Skin' option in earlier Cura releases.

I think I'll remove that sentence now and consider this fixed. The translators will then also remove the sentence and then the confusion should be gone. Information about an old release of Cura will become gradually less relevant over time.
