### ISSUE TITLE
[Feat.REQ] Set speed for printing on top of supports/sup.interface

### ISSUE THREAD

**Issue by swatti87** [Ultimaker/Cura#4545]
See the red and green with no infill. Those were run at full speed on top of the supports. 
Dat be baaad.

![1](https://user-images.githubusercontent.com/39729998/46811426-6f7dff80-cd7b-11e8-9d30-9084a4aaf3fe.jpg)

They wont really connect to the supports or the support-interface so when the nozzle changes direction in the end-corner, it pulls the whole string of wall with it. It evens out at later layers but its ugly.

Notice that part of the layer is on supports, while some parts are not.

If the area printing on the supports had speed setting, OR the entire layer went at set speed, it would be great.

At the moment i cant really raise the supports any higher or they tend to fuse with the print.
EDIT: this tends to be an issue mostly on high speeds.

**Comment by swatti87** [comment]
Tested "bridging options" and they dont effect the walls... 

"Everything on top of supports considored bridge" -option would work.

**Comment by alekseisasin** [comment]
Can you share the project?

**Comment by Ghostkeeper** [comment]
"Bridge Wall Speed" should affect the walls. It does, or at least when I try it.

I think that is sufficient for this use case. We should not implement a second feature to do the same.
