### ISSUE TITLE
Model generates incorrect gcode

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#4552]
**Application Version**
Cura 3.4.1

**Platform**
Windows 10 64-bit (likely N/A)

**Printer**
Ultimaker 3 Extended

**Steps to Reproduce**
Prepare and print the attached project.

**Actual Results**
I aborted the print once it became apparent that it did not match what Cura was showing me, but midway through the model (where the bulge is in the design) the hollow interior was closed off with a bridge, and the printer began printing a solid form (without a hollow interior). Additionally, about the same place, instead of the exterior being a single surface, it created an exterior ring that was a separate component not attached to the former.

**Expected results**
A single, hollow shape should have been printed.

**Additional Information**
I imagine the STL I imported into Cura has a gap, I'm not trying to say that Cura should have been able to handle it (if that's the case) but merely that even if the STL were bad, whatever Cura rendered on-screen should have been what was (attempted) to print.

Project: [UM3E_32mm Adapter v1.curaproject.zip](https://github.com/Ultimaker/Cura/files/2470609/UM3E_32mm.Adapter.v1.curaproject.zip)

What Cura shows:

![image](https://user-images.githubusercontent.com/606923/46832240-27ef7780-cd6b-11e8-833c-9f243298d067.png)

Aborted print gone wrong:

![img_0847](https://user-images.githubusercontent.com/606923/46832497-cd0a5000-cd6b-11e8-95de-988fc7655186.jpg)

**Comment by smartavionics** [comment]
>I imagine the STL I imported into Cura has a gap, I'm not trying to say that Cura should have been able to handle it (if that's the case) but merely that even if the STL were bad, whatever Cura rendered on-screen should have been what was (attempted) to print.

You mean like this image showing the Layer View ?

![screenshot_2018-10-11_22-31-10](https://user-images.githubusercontent.com/585618/46835234-7588d600-cda5-11e8-9060-861be6a7a079.png)

**Comment by mqudsi** [comment]
Well never mind then!

In my defense, my layer view is broken:

![image](https://user-images.githubusercontent.com/606923/46835378-a5b78100-cd73-11e8-9c5e-aa7efcb8c5d7.png)

As you can see, there are no controls for actually controlling which layer is viewed. Perhaps this is fixed in 3.5, I should upgrade and see if I need to  file a bug report.

**Comment by smartavionics** [comment]
You need to slice the object to get the layer view controls and the layers displayed. Bye!

**Comment by fieldOfView** [comment]
Automatic slicing was turned off a couple of versions ago. You can turn it back in the General prrferences.

**Comment by mqudsi** [comment]
I think it might be helpful for a message to be displayed where the controls would be when the model isn’t sliced?
