### ISSUE TITLE
Extremely aliased text rendering on hi-dpi displays in printer management dialog

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#4553]
Under Cura 3.5 under Windows 10 64-bit running at 150% DPI mode:

![image](https://user-images.githubusercontent.com/606923/46834657-9c2d1980-cd71-11e8-9730-9218b53ed513.png)

(Make sure to open the image in a new tab and look at it at full size)

Note the glitching in the name of the printer in the listbox, glitching in "network connected printers," and aliasing in "printer is not connected" text.

**Comment by Ghostkeeper** [comment]
Hopefully this is fixed by https://github.com/Ultimaker/Uranium/commit/398996dd2827049b88f369cf22deeb24db3bce59
