### ISSUE TITLE
[3.5.0] Unable to slice in "One at a time" sequence if object placed at edges. 

### ISSUE THREAD

**Issue by JannSchulte** [Ultimaker/Cura#4558]
**Application Version**
3.5.0

**Platform**
Windows 10 64bit 1803

**Printer**
Tevo Tornado (with CR10 profile)

**Steps to Reproduce**
add small objects (1x1x1) at edges of print area
change Print Sequence to "one at a time"

**Actual Results**
Error: Unable to slice 

**Expected results**
working slicing, since "All at once" slices successfully and the objects are pretty small and printable.

**Additional Information**
![image](https://user-images.githubusercontent.com/3199186/46864441-b66f0200-ce1a-11e8-9e8f-5e1c36b0967b.png)
![image](https://user-images.githubusercontent.com/3199186/46864464-ca1a6880-ce1a-11e8-9cb9-44696decba89.png)

**Comment by Ghostkeeper** [comment]
It can't print it because it's going to print a brim around each one of these.

**Comment by dimake** [comment]
Bit of help for One at a Time settings on Cura 3.4.1 which is unable to slice
![3](https://user-images.githubusercontent.com/48066104/53985646-de8e3300-4124-11e9-80f2-a95c2209bd53.png)

**Comment by Ghostkeeper** [comment]
Maybe all of your meshes are too high to fit in the build volume? Some printer models reduce the build volume height when slicing multiple models in one-at-a-time mode because the suspension of the print head can collide with the models.
