### ISSUE TITLE
[3.5 & master] skin regions deformed when using zigzag lines and optimizePaths() is used

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#4559]
**Application Version**

3.5 and master.

**Platform**

Linux for me, don't know about the OP.

**Printer**

Ender 3.

**Steps to Reproduce**

Load project, slice.

**Actual Results**

Skin regions are deformed (stuff missing, lines in wrong places, etc.)

**Expected results**

Skin regions should be right.

**Additional Information**

The original report is here:

https://community.ultimaker.com/topic/24833-cura-35-first-layer-issues/

The OP's project file is available via that page.

Setting the top/bottom skin pattern to lines seems to cure the problem and also (for my master branch at least) so does disabling the call to optimizePaths().

![screenshot_2018-10-12_13-21-22](https://user-images.githubusercontent.com/585618/46868872-c0e0ca00-ce21-11e8-8e7e-20150512459f.png)

**Comment by smartavionics** [comment]
Master branch (presumably, 3.6 also) still gets this horribly wrong.

With optimizePaths() being called...

![screenshot_2018-11-01_15-00-41](https://user-images.githubusercontent.com/585618/47859854-1ab42e80-dde7-11e8-9ae1-727b9b2eceb8.png)


Without...

![screenshot_2018-11-01_15-00-10](https://user-images.githubusercontent.com/585618/47859872-256ec380-dde7-11e8-9dd1-66b2369b342e.png)

**Comment by smartavionics** [comment]
This bug is printer agnostic. Whether it occurs or not appears to be controlled by the area being filled, line widths, etc.

[UMS5_tip_led_case_bottom.3mf.zip](https://github.com/Ultimaker/Cura/files/2539553/UMS5_tip_led_case_bottom.3mf.zip)

![screenshot_2018-11-01_18-11-21](https://user-images.githubusercontent.com/585618/47870639-f285f900-de01-11e8-8fac-5cc7f452199d.png)

**Comment by Ghostkeeper** [comment]
We now consider this issue fixed (in 4.0 beta 2). Some refactor work is coming on there, but this bug should no longer occur now.

**Comment by ctmakro** [comment]
![image](https://user-images.githubusercontent.com/9973364/50977089-6f350200-152c-11e9-8a66-4f5f56add745.png)

so when do we get 4.0 beta 2?
