### ISSUE TITLE
[Feature req.] Optional cr-10s second extruder

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4560]
Hi there. I am in the process to add a second extruder on my cr-10s. On the stock motherboard you just need to solder a <1€ chip to get a second extruder and you're set, since the motherboard is a semi arranged double extrusion board. 
So I am wondering if you could just add the optional second extruder option in the Cr-10S profile.
Thank you.

**Comment by fieldOfView** [comment]
This is up to Creality or the community to add; Ultimaker does not generally make or change profiles for 3rd party printers.

If you want to try to add/customize your own definition, see this post:
https://community.ultimaker.com/topic/24732-create-a-printer-def/?tab=comments#comment-220889
