### ISSUE TITLE
Cura 3.5.0 no Infillprint

### ISSUE THREAD

**Issue by Revo75** [Ultimaker/Cura#4571]
**Application Version**
Cura 3.5.0

**Platform**
Windows 7 64bit

**Printer**
Custom CoreXY

**Steps to Reproduce**
in all Models

**Actual Results**
no print Infill, in the Settings 70%

**Expected results**
anyone models

**Additional Information**
can't upload a pic

**Comment by smartavionics** [comment]
Please save the project and zip the .3mf file and attach to this issue. Without that, we can do nothing.

**Comment by Revo75** [comment]
here

**Comment by Revo75** [comment]
next try 
[2te CFFFP_Y Axis Threaded Rod Mount.zip](https://github.com/Ultimaker/Cura/files/2478283/2te.CFFFP_Y.Axis.Threaded.Rod.Mount.zip)

**Comment by smartavionics** [comment]
OK, got that. I think the problem is that you have gradual infill steps set to 2. Set it to 0 and you get the density you expect.

**Comment by Revo75** [comment]
who is the setting for this `?

**Comment by smartavionics** [comment]
![screenshot_2018-10-15_12-44-28](https://user-images.githubusercontent.com/585618/46949082-11e9fb80-d078-11e8-835f-be16cc758b8c.png)

**Comment by Revo75** [comment]
filldepth ist here 0.3

**Comment by smartavionics** [comment]
> filldepth ist here 0.3

Sorry, I do not understand what you are saying there. Please provide more info or post a screenshot.

**Comment by Revo75** [comment]
ok i have recalc and its the same .3mf and a pic is attached
[3te CFFFP_Y Axis Threaded Rod Mount.zip](https://github.com/Ultimaker/Cura/files/2478596/3te.CFFFP_Y.Axis.Threaded.Rod.Mount.zip)
![cura350_infill_problem1](https://user-images.githubusercontent.com/44144164/46949473-d2c0a800-d081-11e8-8716-e419eca3e771.PNG)

**Comment by Revo75** [comment]
7-18 has no infill partially 19 is in the air

**Comment by smartavionics** [comment]
Have you tried setting gradual infill steps to 0?

**Comment by Revo75** [comment]
ahh :) thanks, i have this not being set, in 3.4.x no prob with infill
