### ISSUE TITLE
[3.5] Monoprice Select Mini V1 & V2 Compatible material diameter is incorrect

### ISSUE THREAD

**Issue by MatthewUpp** [Ultimaker/Cura#4573]
**Application Version**
3.5.0

**Platform**
Windows 10 Professional 64bit

**Printer**
Monoprice Select Mini V1 and Monoprice Select Mini V2 (E3D)

**Steps to Reproduce**
Add new printer

**Actual Results**
Compatible material diameter setting is 2.85

**Expected results**
Compatible material diameter setting should be 1.75

**Additional Information**
The Malyan M200 filament diameter is set correctly at 1.75 when it is added.
It is easy enough to manually change the diameter to 1.75 but the reason I am filing and issue is because I have seen post about it on the subreddit and Facebook groups for the Select Mini
[Monoprice Select Mini V2 (E3D).zip](https://github.com/Ultimaker/Cura/files/2477529/Monoprice.Select.Mini.V2.E3D.zip)
![2018-10-14_22-51-21](https://user-images.githubusercontent.com/1350411/46932275-dada0280-d003-11e8-8e83-07cf73a9692c.jpg)
[cura.log.zip](https://github.com/Ultimaker/Cura/files/2477543/cura.log.zip)

**Comment by Vandrasc** [comment]
Devs see CURA-5817

**Comment by LipuFei** [comment]
Fixed in 73de72094

**Comment by fieldOfView** [comment]
Note that this is also wrong for Alya3dp, Creality CR10S4, Creality CR10s5, deltabot, grr_neo, kupido, makeR pegasus, maker_starter and printrbot_play_heated extruders.

**Comment by Ghostkeeper** [comment]
What is that deltabot printer actually? I can't find it online.

**Comment by Ghostkeeper** [comment]
See this commit to fix the rest: https://github.com/Ultimaker/Cura/commit/02efd7a1f5a312ea4124a45025ac2dc3bdac99da
