### ISSUE TITLE
Cura often disturbs standard Mac function keys fo luminosity

### ISSUE THREAD

**Issue by mimobis** [Ultimaker/Cura#4574]
As far as I use Cura (around 3.4.0) I notice that, after a while, function keys for luminosity are no more working.

**Application Version**
? -> 3.4.0 -> 3.5.0.

**Platform**
iMac 27" with Mac OS X High Sierra.

**Printer**
Geeetech I3 + Dagoma Neva Magis... independent from printer.

**Steps to Reproduce**
Use Cura for a while with common operations: view layers, generate code...

**Actual Results**
The keyboard keys decrease and increase luminosity often stop working after a while.
(located with F1 and F2).

**Expected results**
What one can do!

**Additional Information**
To have the keys back, must reboot!

**Comment by Ghostkeeper** [comment]
We're unable to reproduce that here on MacOS 10.14 (Mojave) with Cura 4.0.

**Comment by mimobis** [comment]
Hello,
Thank you for your answer, I’m still under High Sierra and the issue happens every day I use Cura,  after a while (not immediately).
Days I don’t use Cura, I don’t face the issue, so I think it is the cause, but…

🎄Bon Noël et Joyeuses Fêtes🤶

Cordialement,
---
Michel Morat
