### ISSUE TITLE
[3.5.1] [3.5.0] Cura does random connections from supports - support material intersects model

### ISSUE THREAD

**Issue by P3D-1** [Ultimaker/Cura#4575]
**Application Version**
3.5.0
3.5.1 (bug still there)

**Platform**
W7

**Printer**
Ultimaker S5

**Steps to Reproduce**
Open the project file, slice, enable layer view
[UMS5_Breakaway_Problem.zip](https://github.com/Ultimaker/Cura/files/2478803/UMS5_Breakaway_Problem.zip)

**Actual Results**
Random Breakaway lines intersecting the model, leading to unwanted print results.

**Expected results**
No model intersection

**Additional Information**
![breakawayproblem](https://user-images.githubusercontent.com/44166390/46952854-65664480-d08c-11e8-9098-bb5a90dd5e58.PNG)

**Comment by BagelOrb** [comment]
FYI: This bug is unrelated to Connect Polygons.

Perhaps this is something which @smartavionics can shed light into off the top of his head?

**Comment by BagelOrb** [comment]
See also https://community.ultimaker.com/topic/24775-breakaway-support-intersects-model-with-cura-350/

**Comment by smartavionics** [comment]
This slices OK for me using my master branch based Cura so perhaps the problem has already been fixed upstream for a future release. If you want to try for yourself, you could install one of my Cura releases that are based on the master branch.

https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

![screenshot_2018-10-15_14-29-44](https://user-images.githubusercontent.com/585618/46953900-05b96a80-d087-11e8-9eff-5fe30e321efa.png)

**Comment by BagelOrb** [comment]
@Appesteijn We should find out which commit fixed this issue and cherry-pick that commit to the 3.5 branch before 3.5.1

I would categorize this as a major bug.

**Comment by diegopradogesto** [comment]
Devs. see CURA-5828

**Comment by P3D-1** [comment]
The issue is still there for me in Cura 3.5.1.

**Comment by smartavionics** [comment]
Do all of the infill patterns cause this problem? If not, could another pattern be used as a workaround? Does turning off the connecting lines setting make a difference?

**Comment by P3D-1** [comment]
> Do all of the infill patterns cause this problem? If not, could another pattern be used as a workaround? Does turning off the connecting lines setting make a difference?

All support patterns available show this problem. Turning off the "connect support lines" option doesn't make a difference.

**Comment by smartavionics** [comment]
Oh, well it was worth asking the question.

**Comment by BagelOrb** [comment]
I've found the problem together with @Appesteijn 

The support bottoms automatically connect infill polygons independent of any user setting.

`FffGcodeWriter::addSupportBottomsToGCode` line 2461

The bug is still present in 3.5.1 and in master.

The Cura team will discuss what to do with this tomorrow.

**Comment by Appesteijn** [comment]
![screenshot 2018-10-16 at 16 42 10](https://user-images.githubusercontent.com/353164/47024969-00315280-d163-11e8-8762-001bd4f3e0a3.png)

This solves your problem for me.

**Comment by BagelOrb** [comment]
For now: a work-around is to set the Support Floor Pattern to ZigZag or to Lines

**Comment by smartavionics** [comment]
it's great that you have a workaround. I wonder why I am not seeing the problem here.

![screenshot_2018-10-16_15-51-00](https://user-images.githubusercontent.com/585618/47025432-5c907400-d15b-11e8-9585-db248361493c.png)

**Comment by BagelOrb** [comment]
Please set the visualization coloring to line type. This is hard to look and understand.

The problem might be easier to see on the standard benchy model.

PS: I'm sorry for introducing this bug in the first place!!! Please forgive me.

**Comment by smartavionics** [comment]
![screenshot_2018-10-16_15-56-43](https://user-images.githubusercontent.com/585618/47025822-1d165780-d15c-11e8-886f-a103cfa32dec.png)

**Comment by P3D-1** [comment]
Thanks @BagelOrb for the workaround, this also works for me in 3.5.1. You are forgiven ;)

**Comment by BagelOrb** [comment]
I don't know where the bug comes from. It's some sort of memory corruption. I can't explain why you don't reproduce the bug now @smartavionics 

I do know that the bug has been fixed in my PR tho.

**Comment by P3D-1** [comment]
Seems to be fixed in Cura 3.6.0. Thanks for your work, everyone!

**Comment by diegopradogesto** [comment]
Thanks for the feedback!
