### ISSUE TITLE
Wifi drops when Cura is started

### ISSUE THREAD

**Issue by TheLion** [Ultimaker/Cura#4588]
**Application Version**
3.4.1 / 3.5.0 / 3.5.1

**Platform**
Windows 10

**Printer**
Creality CR-10S

**Steps to Reproduce**
Start Cura

**Actual Results**
A lot of network traffic on wifi times out or gets dropped

**Expected results**
No network traffic loss

**Additional Information**
I attached one screenshot with Cura not started and two with Cura started. In the second one you can also see very high response times.

I only notice this when using wifi. When I connect the same laptop with an UTP cable to the network, there are no timeouts/drops.

I also pinged my local gateway and some other networked devices, but they all showed the same timeouts/drops.

![cura_not_started](https://user-images.githubusercontent.com/3755011/47029250-66ba6e80-d16b-11e8-9218-04b742035319.JPG)
![cura_started](https://user-images.githubusercontent.com/3755011/47029251-66ba6e80-d16b-11e8-872b-e9df69180802.JPG)
![cura_started_2](https://user-images.githubusercontent.com/3755011/47029252-67530500-d16b-11e8-978a-6217fee0c6dd.JPG)

**Comment by ChrisTerBeke** [comment]
I guess this is because Cura tries to find printers on the same network.

**Comment by fieldOfView** [comment]
Do you have the Octoprint Connection plugin installed?

**Comment by TheLion** [comment]
> Do you have the Octoprint Connection plugin installed?

Yes. I do. But that is also installed when using a cable, so I don't understand the connection.

**Comment by ChrisTerBeke** [comment]
Probably both are affected, but cable has higher bandwidth so you notice the difference less.

**Comment by TheLion** [comment]
I disabled the Octoprint plugin and even uninstalled it, but the timeouts/drops still exist when Cura is started.

**Comment by ChrisTerBeke** [comment]
The other networking Cura does it the anonymous analytics and the Toolbox, but that's only when printing/exporting or actually opening the Toolbox. Could you try a tool like wireshark to see what's actually being done over the network?

**Comment by nallath** [comment]
The looking for printers shouldn't take that much network trafic. That's just listening to some broadcasting packets.

**Comment by ChrisTerBeke** [comment]
Zeroconf has given issues before on Windows.

**Comment by nallath** [comment]
Sure, but not with regards to causing massive network problems (at least, not to my knowledge). We only had issues with zero-conf not finding printers or finding outdated ones.

**Comment by TheLion** [comment]
Got the WireShark traces.

The first (Wireshark_20181018_1953) is with Cura just opened and the Octoprint plugin installed and enabled. The second (Wireshark_20181018_1958) is with Cura opened and with the Octoprint plugin de-installed.

A little info about my network. My laptop (running the Wireshark and Cura) is nb3ict01.3ict.nl with IP 192.168.206.176 and I'm currently connected to the fourpets.net network in the 192.168.206.0/24 range.
My Octoprint 192.168.206.103, DNS is 192.168.206.102 and gateway 192.168.206.254.

I can see a ot of re-transmits in the first trace to Octoprint, but there are also a lot in the second one, with Octoprint plugin de-installed.

Very curious what you guys can make of this.

[Wireshark.zip](https://github.com/Ultimaker/Cura/files/2493054/Wireshark.zip)

**Comment by ChrisTerBeke** [comment]
I see a lot of requests to backup & CDN platforms like Akamai, pcloud and Fastly (151.101.38.133), but nothing that Cura usually connects to and could have initiated. Are you running other desktop services that use these?

**Comment by TheLion** [comment]
Yes, I use pCloud, but about the others I don't know. I closed every application that I could close, but I'll check again tomorrow and close even more and stop any services and make a new trace.

**Comment by lilphil** [comment]
Could it be related to this? https://bugreports.qt.io/browse/QTBUG-40332

**Comment by TheLion** [comment]
What is QNetworkAccessManager?

**Comment by ChrisTerBeke** [comment]
http://doc.qt.io/qt-5/qnetworkaccessmanager.html. It's the networking part of the Qt library that we use to make Cura's GUI.

**Comment by ChrisTerBeke** [comment]
We run Qt 5.10 though since Cura 3.5, which is not in the list of affected versions according to https://bugreports.qt.io/browse/QTBUG-40332.

**Comment by TheLion** [comment]
Ah. So not something I can update/change :-)

**Comment by ChrisTerBeke** [comment]
Nope. And unfortunately us neither, as QT is engrained in pretty much every part of Cura.

**Comment by TheLion** [comment]
:-(

**Comment by lilphil** [comment]
For what its worth, we use 5.10.0 at $work and we've noticed that it is affected by similar issues, to the point where we no longer release with the bearer plugins.

**Comment by ERICRAC** [comment]
I just upgrade Cura 3.x to 4.4 on windows 10 and the same network (wifi drops) is appearing. I already had network issue with 3.x but not so much and didn't make relation with Cura.
That time with 4.4 started wifi loose connection very soon and wifi is back to life when Cura is closed. It looks that Cura is changing computer network configuration.
Could you help please?
Is it ok to downgrade cura to 4.3 with parameters...?

**Comment by Ghostkeeper** [comment]
If that QTBUG reported above is still not solved, then this could occur for you in recent releases because we've been progressing to using the QNetworkManager everywhere. It'll be even worse in the next release if we manage to get [this change](https://github.com/Ultimaker/Uranium/pull/553) in on time. The QNetworkManager is used because it doesn't hold the GIL while the request is ongoing, meaning that Cura won't freeze.

We haven't seen the problem though. The ping is unchanged for me.
