### ISSUE TITLE
Software Bug for 3.5.1

### ISSUE THREAD

**Issue by kornshadow097** [Ultimaker/Cura#4591]
**Application Version**
3.5.1

**Platform**
windows 10 64bit

**Printer**
tevo tarantula

**Steps to Reproduce**
 Anytime I select a different nozzle size profile dropdown or in the configuration menus, it crashes. i was on 0.6mm and it was fine, i switched to my 0.8mm and it froze but came back and when i switched to 1.0 the program crashed 5x. so then i tried to go back to 0.6mm and it just keeps crashing everytime i open the program and try to revert to my nozzle size

**Actual Results**
it crashes

**Expected results**

**Additional Information**

**Comment by nallath** [comment]
Could you also post your logs?

**Comment by Abraiator** [comment]
Application Version
3.5.1

Platform
windows 10 64bit

Printer
Framebox Prusa Clone
Foldarap

Similar thing here. Both with the 3.5.0 and the 3.5.1 versions. 

Every time I change the printer in use (in the top right corner menu) Cura crashes.

My printer profiles are inherited from previous Cura versions and always worked flawlessly before.

**Comment by nallath** [comment]
Same as before; I need logs to diagnose the problem. If no-one provides them, there is nothing I can do to resolve the issue.

**Comment by Abraiator** [comment]
Ok, I'm attaching a log (in order to keep it small I deleted the old one, opened Cura, tried to change the printer on the right top menu and... voilá! Cura crashed.

Thanks.
[cura.log](https://github.com/Ultimaker/Cura/files/2492664/cura.log)

**Comment by ZerialLim** [comment]
Having the same problem. Attaching my own log.
[cura.log](https://github.com/Ultimaker/Cura/files/2499379/cura.log)

**Comment by ZerialLim** [comment]
0. According to the log file, there must be something wrong with the extruder config file.
1.  I deleted all extruder cfg files from /definition_changes
2. Run Cura
3. Configuration Error message pops up, saying fdmextruder settings and robo3dR1 extruder settings are corrupted (yeah that's the files I removed)
4. Printer change works fine.

**Comment by ZerialLim** [comment]
problem continues after reboot.

**Comment by nallath** [comment]
I think the issue has been fixed for the 3.6 final release. Could you try again once it's released?

**Comment by Ghostkeeper** [comment]
This was fixed in 3.6 stable.
