### ISSUE TITLE
Monitor right click text is black on black in dark theme

### ISSUE THREAD

**Issue by rbarbrow** [Ultimaker/Cura#4592]
Click on print info to delete a queued Print will produce a menu with dark text with dark blackground using the ultimaker dark theme 

**Application Version**
3.5.1

**Platform**
Windows 10 Pro

**Printer**
Ultimaker 3

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by diegopradogesto** [comment]
OK, thanks we are aware of it. We will notify once is fixed.

**Comment by nallath** [comment]
We forgot to close this. I just checked in the latest version; it's fixed now.
