### ISSUE TITLE
Layered view no longer working

### ISSUE THREAD

**Issue by thomaskilian** [Ultimaker/Cura#4595]
**Application Version**
3.5.1

**Platform**
Mac

**Printer**
DIY

**Steps to Reproduce**
Render any model and choose the 3rd view. The German name is Schichtenansicht, which is probably Layered View.
Well, aside the fact that moving the layer slide is now slow as molasses it does not show any layer at all. Compared to the previous version I had (was it 3.4?) where I could smoothly scroll through the single layers it's now a how-can-I-effectively-waste-CPU-time.

**Comment by Ghostkeeper** [comment]
Oh, from here it seems to work fine, also on MacOS. Was it a particularly heavy model? Lots of g-code? Perhaps the layer view data is still processing?

**Comment by thomaskilian** [comment]
Well, no. It's not complex and as said it worked smoothly before. I skipped the version before 3.5.0 which is also unusable. Here's the .stl file:

[ControllerCase.gcode.zip](https://github.com/Ultimaker/Cura/files/2493629/ControllerCase.gcode.zip)

**Comment by thomaskilian** [comment]
This is what it looks like now:
![pic20181020202759](https://user-images.githubusercontent.com/69296/47259238-fd0dcd80-d4a6-11e8-8f0b-f141451c3e4c.png)

And that's the 3.4.1 output:
![pic20181020202923](https://user-images.githubusercontent.com/69296/47259245-0c8d1680-d4a7-11e8-8def-98675d9338f0.png)

Except that 3.5.1 is now slower than a snail it doesn't have any valuable improvements (for me). So I'm just reverting back.

**Comment by diegopradogesto** [comment]
Maybe related with the compatibility mode in the layer view? Does it happen when loading a gcode or after slicing a STL? Can you please share a project file with us? (In 3.4, File > Save Project...)

**Comment by thomaskilian** [comment]
When I load the G-code it's different as the body is shown completely blue. But the layer can't be distinguished anyway. Also dragging the layer slider is awfully slow in any case. No comparison to 3.4.1. I'm working on OSX High Sierra. Here's a sample stl/gcode:

[Archiv.zip](https://github.com/Ultimaker/Cura/files/2563520/Archiv.zip)

**Comment by diegopradogesto** [comment]
I can't do anything to reproduce your environment with STL and Gcode, that's why I asked for a project file (In 3.4 is `File -> Save Project...`, in 3.5 is `File -> Save...`). Please attach it to investigate more.

**Comment by thomaskilian** [comment]
Well, no. I just can state that 3.4 works fluently when sliding through layers and from 3.5 on it's anything else but fluent. It's more of the viscosity of tar. Will try on my other (older) Mac at home.

**Comment by Ghostkeeper** [comment]
You can change the colours from "material color" to "line type" in the drop down in the top-centre of the screen. That's why it appears all blue for you.

If performance is an issue, you can revert to the old behaviour by enabling the compatibility mode for layer view in the preferences.
