### ISSUE TITLE
M107 is deprecated

### ISSUE THREAD

**Issue by thomaskilian** [Ultimaker/Cura#4605]
According to [RepRap](https://reprap.org/wiki/G-code#M107:_Fan_Off) M107 is deprecated. However, Cura sends it initially at layer 0:

> ;----------------
;LAYER:0
M107
G0 F3600 X51.92 Y82.155 Z0.2 
...

**Comment by stelgenhof** [comment]
That is not correct. The documentation says "Deprecated in **Teacup** firmware and in **RepRapFirmware**.". Firmwares like Marlin for example still supports this GCode command (See: 
http://marlinfw.org/docs/gcode/M107.htm)

**Comment by thomaskilian** [comment]
Unfortunately the Teacup flavor is not available :-/

**Comment by thomaskilian** [comment]
Probably I have to do that in my Teacup post-processor. Would just need to remove that very line from the record. Well....

**Comment by stelgenhof** [comment]
In that case I would add the M106 command in the start GCode section :)

**Comment by thomaskilian** [comment]
That does not stop Cura to send M107. However, as long as I can post-process the code it's probably just fine. You may close this issue.

**Comment by stelgenhof** [comment]
Correct it will still send, but shouldn't be an issue when you put the M106 S0 command in.
(I can't close this issue, only you or the maintainer(s) of this repository can).

Cheers! Sacha
