### ISSUE TITLE
Camera icon (and image) missing in monitor page when the printer is idle

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/Cura#4607]
**Application Version**
3.5.1

**Platform**
Win10

**Printer**
UM3

**Steps to Reproduce**
Open monitor page and open printer entry on the right

**Actual Results**
No camera icon visible if the printer is idle

**Expected results**
Camera icon visible all the time

**Additional Information**
sorry, have no idle printer atm...

**Comment by rburema** [comment]
Hi @Dim3nsioneer, The monitor part is the 'Connect'-teams field of expertise. I'll forward the issue to them. cheers, Remco.

**Comment by ianpaschal** [comment]
Thanks for tapping me on this one @rburema.

I also think this is a bit weird but the decision to not show it was made immediately before I moved from Cura to Cura Connect team. I will ask the Cura Connect UX designer about it though.

**Comment by ianpaschal** [comment]
Hmm the answer is that it's on our backlog and we're planning on fixing it. The rationale is that there's no real-estate on the smaller, idle printer card to show the camera button so once that's worked out design wise we'll add it in.

**Comment by Dim3nsioneer** [comment]
Thx guys for the quick check!

**Comment by diegopradogesto** [comment]
I think this was a UX decision. Can you confirm, @LukeChen-Ultimaker?

**Comment by Ghostkeeper** [comment]
This is fixed in version 4.0. We got a lot of feedback about this, internally and from users.
