### ISSUE TITLE
[3.5.1] - Cannot import native Inventor parts

### ISSUE THREAD

**Issue by LairOfPLA** [Ultimaker/Cura#4608]
**Application Version**
Noticed issue on 3.5.1.  I think it still worked on 3.4.2

**Platform**
Windows 10 Pro, Version 1709, OS Build 16299.726

**Printer**
Creality CR-10S
(https://github.com/Ultimaker/Cura/files/2492295/curaproject.zip)

**Steps to Reproduce**
Open Cura, navigate to any folder containing Autodesk Inventor part files (*.ipt), attempt to open one of them.

**Actual Results**
Error pop-up saying "cannot open file of type...."

**Expected results**
File used to import with no problem.  Expected same functionality.

**Additional Information**
Using Autodesk Inventor Professional 2017, 64-Bit, Build 196, SP1

**Comment by rburema** [comment]
Hi @LairOfPLA, It seems support for that feature is supplied by a [plugin](https://community.ultimaker.com/topic/21489-autodesk-inventor-plugin-015/) (see also [here](https://thopiekar.eu/cura/plugins/cad/inventor/)), so you'd need to reinstall that if it becomes available for the new version. cheers, Remco.
