### ISSUE TITLE
How does "has_variant_buildplates" parameter work?

### ISSUE THREAD

**Issue by MajorSlug** [Ultimaker/Cura#4616]
I'm actually making a custom definition set on Cura 3.5+ and I'm having trouble using variant buildplates.

Could anyone give me a good example of how "has_variant_buildplates" parameter works?

In the default definitions, I can see that the Ultimaker s5 definition uses it. If I instanciate this machine, I can't see any place where I can change between buildplate variants in the Cura UI.

**Application Version**
3.5.1, 3.6.0 BETA

**Platform**
Windows

**Printer**
fdmprinter

**Comment by fieldOfView** [comment]
AFAIK, the feature has not been officially released, and the build plate variants for the S5 are not yet distributed with Cura. If they were, you would see a dropdown menu above the material dropdown.

**Comment by MajorSlug** [comment]
Thanks for your answer.
This would mean that I'd have to wait it's been released before I can use and test my definitions, as it's a key feature of my printer.

**Comment by fieldOfView** [comment]
Actually, no, you should be able to use it now, because the _code_ seems to be all in place, but the _profiles_ are missing.

**Comment by diegopradogesto** [comment]
Yes, this is the situation, we implemented the feature in Cura, but the profiles are not yet ready. At this moment for Ultimaker S5 we have one global variant that represents the glass buildplate, but we are now hiding the buildplate selector because it looks weird that you have a selector but only one possible selection. That's why we are hiding the UI elements now, even if the feature is ready.

**Comment by MajorSlug** [comment]
Ok thanks. 
I'll then try to implement that asap.

**Comment by MajorSlug** [comment]
@diegopradogesto, There actually are 2 variants for the S5 (ultimaker_s5_aluminum.inst.cfg and ultimaker_s5_glass.inst.cfg), could you please explain what still makes the selector hidden?

I tried a bit more but I'm not able to see any variant selector for my printer.
Here are my definition files, could someone tell me what is wrong?
[Cura_3_ZMorph.zip](https://github.com/Ultimaker/Cura/files/2497141/Cura_3_ZMorph.zip)

Regards.

**Comment by MajorSlug** [comment]
Could still someone try my variants definitions included above.
I need to know if there are flows in my settings or if it's a bug in Cura 3.5.1.

**Comment by Ghostkeeper** [comment]
Your profiles are probably fine, the entire selector is not made visible:

https://github.com/Ultimaker/Cura/blob/65f1c9a304bae55181306b38d35afd4c58ec4214/resources/qml/Menus/SettingsMenu.qml#L63

It's only made visible if your Cura's SDK version is "dev", for which you would need to be running from source.
