### ISSUE TITLE
Menu selections cause build plate to change color (from white to grey)

### ISSUE THREAD

**Issue by LilBub** [Ultimaker/Cura#462]
Any time I select on a pull down menu, the background graphic of the build plate changes color from white to grey.

This happens for about 4 seconds then changes back.  

To duplicate (on my system)....Click on Settings and highlight/mouse over Preferences.

This also happens in the Extensions menu when you select a setting then hover over the next option.

Windows 10 system running Windows 64-bit version of 15.09.85

![image](https://cloud.githubusercontent.com/assets/14837299/10326651/b727eb76-6c6b-11e5-9950-53406a2f1d09.png)

**Comment by fieldOfView** [comment]
This was fixed by making sure there is always a texture for the buildplate mesh.
Issue can be closed
