### ISSUE TITLE
Ultimaker Cura 3.5.1 does not complete ironing.

### ISSUE THREAD

**Issue by gzumwalt** [Ultimaker/Cura#4623]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smartavionics** [comment]
This is a completely useless issue report. See https://github.com/Ultimaker/Cura/issues/4524 for a much better report of this problem.

**Comment by diegopradogesto** [comment]
No more comments.
