### ISSUE TITLE
Anet A8 seen by Repetier but not by Cura 3.5.1 on MacOS 10.14.1

### ISSUE THREAD

**Issue by DavidMnDenver** [Ultimaker/Cura#4625]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by DavidMnDenver** [comment]
I am using an Anet A8 on MacOS 10.14.1 over Cura 3.5.1. Repetier, on the same station, sees and controls the printed but Cura can't find it. I tried loading the newest firmware I could find and have changed the timeout to 5 - nothing.

Any ideas?

**Comment by honza-kasik** [comment]
Are you trying to connected with both Cura and Repetier at the same time?

**Comment by DavidMnDenver** [comment]
Sequentially.

**Comment by Ghostkeeper** [comment]
How do I go about debugging this without having the Anet A8 printer available? What is it about A8 that prevents Cura from finding the printer?
