### ISSUE TITLE
Cura 3.5.1 deleted my printer profile settings

### ISSUE THREAD

**Issue by JoeyStam** [Ultimaker/Cura#4627]
After updating from Cura 3.5.1, all of my printer setting and configurations are gone and it is asking me to set up a new printer

-->

**3.5.0 -->3.5.1**

** Windows 10 64-bit**

**Wanhao Duplicator i3 with Flexion HT Hotend**

**Comment by rburema** [comment]
Hi @JoeyStam, Is there anything in the logs? What do the configuration-folders currently look like? cheers, Remco.

**Comment by JoeyStam** [comment]
Sorry still learning, where do I find the logs and configuration folders? 

-thanks, Joey

**Comment by rburema** [comment]
@JoeyStam, on Windows your configs of the different version should be in `%APPDATA%/cura`, (then select the folder for the relevant version, which is 3.5 in both cases) you can type that in the folder-explorer directly, or go to `C:\Users\<your_username>\AppData\Roaming\cura\3.5` which is what `%APPDATA%` ususally points to. The log-file is also in the config-folder.

Note also that during installation, the installer asks if you want to keep/delete all settings of the previous install (while deinstalling the prev. version). Do you remember what you answered for that question?

**Comment by JoeyStam** [comment]
![capture 2](https://user-images.githubusercontent.com/37965665/47620246-41582980-dab6-11e8-932c-d41779995c1d.PNG)
![capture 3](https://user-images.githubusercontent.com/37965665/47620247-41582980-dab6-11e8-9db9-42d15f3196cb.PNG)
![capture 4](https://user-images.githubusercontent.com/37965665/47620248-41582980-dab6-11e8-9621-0cb06c5c5aa6.PNG)
![capture 5](https://user-images.githubusercontent.com/37965665/47620249-41582980-dab6-11e8-88b7-196ffe06dc75.PNG)
![capture 6](https://user-images.githubusercontent.com/37965665/47620250-41582980-dab6-11e8-8106-561c7f8a9974.PNG)
![capture 7](https://user-images.githubusercontent.com/37965665/47620251-41f0c000-dab6-11e8-9114-d1954fd6a92a.PNG)
![capture 8](https://user-images.githubusercontent.com/37965665/47620252-41f0c000-dab6-11e8-933b-9bcc2c5b1dbf.PNG)
![capture 9](https://user-images.githubusercontent.com/37965665/47620253-41f0c000-dab6-11e8-9a8e-6d69faa77c26.PNG)
![capture 10](https://user-images.githubusercontent.com/37965665/47620254-41f0c000-dab6-11e8-89cb-91c76642beea.PNG)
![capture 11](https://user-images.githubusercontent.com/37965665/47620255-41f0c000-dab6-11e8-935d-5d20933febbd.PNG)
![capture 12](https://user-images.githubusercontent.com/37965665/47620256-41f0c000-dab6-11e8-8673-e4cab4695714.PNG)
![capture](https://user-images.githubusercontent.com/37965665/47620257-41f0c000-dab6-11e8-816f-999374248e49.PNG)
![aaaaa capture](https://user-images.githubusercontent.com/37965665/47620258-41f0c000-dab6-11e8-991f-286f7a3d33d1.PNG)

**Comment by rburema** [comment]
>  If so is there anyway to get those profiles back?

If you did indeed do that, then no, sorry, there isn't a way to get them back. Otherwise, there might not be a way to get them back either, but we can try to figure out what went wrong: Can you please post the log file (the 'Text Document' in your last screenshot)?

**Comment by JoeyStam** [comment]
Thank you soooooo much for all your time and help, Remco, but with your last post about the file locations, I was able to restore the files from an old backup without having restore my entire system.

Again I thank you so much for all your help and I greatly appreciate everything. You have helped me a great deal.

Joey
