### ISSUE TITLE
3.5.1 - Dual Extrusion - "Wipe Nozzle After Switch" missing

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4631]
**Application Version** - CURA 3.5.1
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Install Cura 3.5.1, go to "Dual Extrusion" menu.

**Actual Results** - The "Wipe Nozzle After Switch" feature is missing.

**Cura 3.5.1**
![351](https://user-images.githubusercontent.com/12901952/47304061-78918b00-d61d-11e8-89ef-4b6c9c0f2ea1.jpg)

**Cura 3.4.1**
![341](https://user-images.githubusercontent.com/12901952/47304046-716a7d00-d61d-11e8-9eb2-65153b96d3b2.jpg)

**Comment by rburema** [comment]
Hi @amagr0, Those settings have indeed been removed. 'Wipe Nozzle After Switch' was deemed unnescesary after changes (because something similar happens now anyway), and 'Prime Tower Purge Volume' couldn't be correctly calculated in the front-end. cheers, Remco.
