### ISSUE TITLE
Custom definition - Hide Generic Materials 

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#4635]
Hello,
I'm working on a custom definition set on Cura 3.5.1 and I'd like to know how can I hide the generic materials.

In metadata I use "exclude materials", and declare all the materials and is seems to work well, with the exception of the PLA. How can I also hide it?

Thanks

![image](https://user-images.githubusercontent.com/12901952/47307649-81875a00-d627-11e8-83c4-19c036fb5c76.png)

"exclude_materials": ["PLA", "tizyx_abs", "tizyx_pla", "tizyx_pla_bois", "chromatik_pla", "dsm_arnitel2045_175", "dsm_novamid1070_175", "fabtotum_abs", "fabtotum_nylon", "fabtotum_pla", "fabtotum_tpu", "fiberlogy_hd_pla", "filo3d_pla", "filo3d_pla_green", "filo3d_pla_red", "generic_abs", "generic_abs_175", "generic_bam", "generic_cpe", "generic_cpe_175", "generic_cpe_plus", "generic_hips", "generic_hips_175", "generic_nylon", "generic_nylon_175", "generic_pc", "generic_pc_175", "generic_petg", "generic_petg_175", "generic_pla", "generic", "generic_pla_175", "generic_pp", "generic_pva", "generic_pva_175", "generic_tough_pla", "generic_tpu", "imade3d_petg_green", "imade3d_petg_pink", "imade3d_pla_green", "imade3d_pla_pink", "innofill_innoflex60_175", "octofiber_pla", "polyflex_pla", "polymax_pla", "polyplus_pla", "polywood_pla", "ultimaker_abs_black", "ultimaker_abs_blue", "ultimaker_abs_green", "ultimaker_abs_grey", "ultimaker_abs_orange", "ultimaker_abs_pearl-gold", "ultimaker_abs_red", "ultimaker_abs_silver-metallic", "ultimaker_abs_white", "ultimaker_abs_yellow", "ultimaker_bam", "ultimaker_cpe_black", "ultimaker_cpe_blue", "ultimaker_cpe_dark-grey", "ultimaker_cpe_green", "ultimaker_cpe_light-grey", "ultimaker_cpe_plus_black", "ultimaker_cpe_plus_transparent", "ultimaker_cpe_plus_white", "ultimaker_cpe_red", "ultimaker_cpe_transparent", "ultimaker_cpe_white", "ultimaker_cpe_yellow", "ultimaker_nylon_black", "ultimaker_nylon_transparent", "ultimaker_pc_black", "ultimaker_pc_transparent", "ultimaker_pc_white", "ultimaker_pla_black", "ultimaker_pla_blue", "ultimaker_pla_green", "ultimaker_pla_magenta", "ultimaker_pla_orange", "ultimaker_pla_pearl-white", "ultimaker_pla_red", "ultimaker_pla_silver-metallic", "ultimaker_pla_transparent", "ultimaker_pla_white", "ultimaker_pla_yellow", "ultimaker_pp_transparent", "ultimaker_pva", "ultimaker_tough_pla_black", "ultimaker_tough_pla_green", "ultimaker_tough_pla_red", "ultimaker_tough_pla_white", "ultimaker_tpu_black", "ultimaker_tpu_blue", "ultimaker_tpu_red", "ultimaker_tpu_white", "verbatim_bvoh_175", "Vertex_Delta_ABS", "Vertex_Delta_PET", "Vertex_Delta_PLA", "Vertex_Delta_TPU", "zyyx_pro_flex", "zyyx_pro_pla" ],

**Comment by fieldOfView** [comment]
Note that it is a good idea to keep generic PLA enabled for your machine; creating a "new" material in the Materials pane of the preferences actually creates a copy of that PLA material.

For BlackBelt Cura I am patching around these issues using a plugin (but that is somewhat dirty, in an as clean as possible way):
https://github.com/BlackBelt3D/Cura/blob/bb-3.4/plugins/BlackBeltPlugin/BlackBeltPlugin.py#L127
https://github.com/BlackBelt3D/Cura/blob/bb-3.4/plugins/BlackBeltPlugin/PatchedMaterialManager.py

**Comment by amagr0** [comment]
The problem with the generic materials, is that they are pre-config for the Ultimakers machines. 

Is there anyway to override them, in order to adjust for the current machine?

**Comment by diegopradogesto** [comment]
Yes, it is. By creating a pull request in our fdm_materials repository. There you can define a new entry in the generic_pla file for your printer with custom values for the material settings.

You can take a look at how we do it for our Ultimaker printers.a

**Comment by amagr0** [comment]
@diegopradogesto and is there any way to hide the generic materials?

**Comment by diegopradogesto** [comment]
I've just tried and by excluding all the generic materials, you can get rid of all of them. However it's not possible to get rid of the "Generic" brand because we always keep it as default, and so you will get the "Generic" category with an empty list of materials (as you can see in the image)
![image](https://user-images.githubusercontent.com/15830521/47483506-ba971880-d839-11e8-9f08-94ada73bc9a5.png)

**Comment by Ghostkeeper** [comment]
I think this question is answered then. Here is an example of how to hide materials such as Generic PLA:

https://github.com/Ultimaker/Cura/blob/e8febaff59dacd03ac71917b4508c68117a1ad2a/resources/definitions/ultimaker.def.json#L10
