### ISSUE TITLE
Raft line widht and height calculated values are too high.

### ISSUE THREAD

**Issue by edgary777** [Ultimaker/Cura#4636]
**Application Version**
Cura 3.5.1

**Platform**
Windows and Linux

**Printer**
Tevo Tornado

**Steps to Reproduce**
Select Raft on the "Build Plate Adhesion" menu.

**Actual Results**
For a 0.4 nozzle the calculated value for the first layer **line width** was **0.8**, and for the **height** **0.36**.

For the middle layer it calculated a **line width** of **0.8** and  a **height** of **0.3**

For the top Layers the calculated values were the same as the ones configured in the "Quality" menu.

**Expected results**
The values, specially the line width, were so high the printer refused to print and took me a long time to realize these settings were the culprits.

I see no reason for the line width to be nearly double the regular one, nor for the line height to exceed the regularly accepted maximum of 75% of the nozzle diameter.

**Comment by nallath** [comment]
We don't define the values for non Ultimaker profiles. If these need to be changed, pull requests are welcome.
