### ISSUE TITLE
[3.5.1 / 3.6 / 4.0 ] Multiple issues when displaying the Cura application interface.

### ISSUE THREAD

**Issue by bliser3d** [Ultimaker/Cura#4637]
**Application Version** - 3.5.1
**Platform** - ALT Linux, KDE5, Plasma Color Schemes - "Breeze Dark variant" end "Breeze High contrast".
**Printer** - Any

**Steps to Reproduce** end **Actual Results**
Red color highlights some (not all) problems.
1. Cura themes - **cura-dark**, KDE5 Plasma Color Schemes - "Breeze Dark variant" end "Breeze High contrast" (I use it all the time.)
![default](https://user-images.githubusercontent.com/35381319/47317676-e310ee00-d652-11e8-85e5-a3b9d9264cf5.png)
For comparison, version 3.4.1
![default](https://user-images.githubusercontent.com/35381319/47317831-2e2b0100-d653-11e8-89ac-5add1c98348a.png)

2. Cura themes - cura-dark, KDE5 Plasma Color Schemes - "Breeze Dark .....".
![default](https://user-images.githubusercontent.com/35381319/47318089-d214ac80-d653-11e8-8569-dc668854c337.png)

![default](https://user-images.githubusercontent.com/35381319/47318206-1acc6580-d654-11e8-82e1-b45457dcf0bc.png)

![default](https://user-images.githubusercontent.com/35381319/47318343-7b5ba280-d654-11e8-92ba-e997a60261c9.png)

3. Cura themes - **cura-light**, KDE5 Plasma Color Schemes - "Breeze Dark .....".
![default](https://user-images.githubusercontent.com/35381319/47318995-3d5f7e00-d656-11e8-9313-dc4b01811a33.png)

Further I will not continue - there are still a lot of shortcomings in the interface.

**Expected results**
1. When using the light theme in the Cura, all the interface elements of the application must match the settings for the light theme.
2. When using the dark theme in Cura, all the interface elements of the application must match the settings for the dark theme.
3. The display of all interface elements of the Cura application should not depend on the color theme used in the KDE.

**Additional Information**
Similar issues were reported in: https://github.com/Ultimaker/Cura/issues/4522

I hope I did not tire you.

**Comment by bliser3d** [comment]
This problem is completely repeated in version 3.6.0.

**Comment by bliser3d** [comment]
This problem is completely repeated in version 4.0 (beta).
Maybe someone knows when this problem can be eliminated?

**Comment by matibarriento** [comment]
Yes, I have the same issue with KDE and Cura version +3.6

**Comment by captNtinker** [comment]
![image](https://user-images.githubusercontent.com/47804922/54501429-a4c6e480-48fb-11e9-9dc7-6b519555e593.png)
Issue with my screen being stuck to the right side (minimized) and when large, can't see the menus open?

**Comment by captNtinker** [comment]
can't drag it off, it's stuck to the right side :(

**Comment by fieldOfView** [comment]
@captNtinker that is a different problem altogether, but I guess you already came to the same conclusion since you opened a new issue here: https://github.com/Ultimaker/Cura/issues/5443

**Comment by captNtinker** [comment]
Yah- I wasn’t sure how to put in the question- it’s got to be a window issue - still can’t get it to work- gonna ask the tech at work today see what he says! Might get a solution?

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this problem, not on Ubuntu 18.10 (using theme Yaru-dark) nor on Fedora (I don't know which theme my colleague was using, but it was dark).

**Comment by bliser3d** [comment]
Thanks **yodor** (https://github.com/Ultimaker/Cura/issues/4826) for the prompt. 
Used the command "QT_QUICK_CONTROLS_STYLE=Desktop /home/User/Cura/AppRun".
It helped me.

![image](https://user-images.githubusercontent.com/35381319/54634460-551b2100-4a93-11e9-95e6-4666eb4eed10.png)

![image](https://user-images.githubusercontent.com/35381319/54634677-bfcc5c80-4a93-11e9-8bb6-25b910687794.png)

Small remarks remained, but this does not prevent the Cura from using.
Thank you all. I close the topic.

**Comment by muesli** [comment]
@bliser3d That's a work-around at best. This is still broken in 3.6 and 4.0.

**Comment by bliser3d** [comment]
Some shortcomings in the dark theme, I tried to fix it in #5499.

**Comment by Ghostkeeper** [comment]
We're planning to replace the system-themed parts in the preferences dialogue for Cura-themed elements, which would solve this issue. Combining the two themes is never a good idea.

**Comment by VCF** [comment]
@bliser3d , could you please clarify how you passed `QT_QUICK_CONTROLS_STYLE=Desktop /home/User/Cura/AppRun` to the application? Is there a command line flag I should use in conjunction with it? Also, I presume the command is a string literal, as opposed to needing to substitute for a specific file path?

Running under Mint 18.3, a very large number of the menus and text entry boxes are white-on-white, such that I have to interact with the system by trial-and-error. Thanks!

**Comment by bliser3d** [comment]
**VCF**, 
**QT_QUICK_CONTROLS_STYLE=Desktop /home/User/Cura/AppRun** - this is the start command **Cura**.
If interested, you can improve the interface further and in this way - #5499

**Comment by e-anima** [comment]
bliser3d thank you. Totally fixed it for me.

**Comment by captNtinker** [comment]
The resolution for me was to unload it and load an earlier version :( but it’s working again!

**Comment by captNtinker** [comment]
Rather the old version is working fine- I would have to hit Maximize just to get to it and then hit escape to even work in it, then couldn’t anchor it out of the way- it went way off the screen where I couldn’t get it :/

**Comment by bliser3d** [comment]
In version 4.1-beta, problems with the display of the interface (previously indicates by me) remained.
Fixed only the display of the window "Machine Settings" - thanks for the correction.

**Comment by Ghostkeeper** [comment]
In 4.1, only the machine settings and the add printer dialogue was replaced with Cura-themed elements. The rest of the preferences menu is still system-themed. It's a lengthy process, sorry.
