### ISSUE TITLE
Feature request: adaptive layer height for improving small vertical holes

### ISSUE THREAD

**Issue by AletheianAlex** [Ultimaker/Cura#4638]
I wanted to inquire as to the feasibility of adding an adaptive layer height mode that will prioritize internal features such as small vertical holes to improve the accuracy of their shape/dimensions, i.e. improve Z-axis resolution using shorter layers only where necessary. I have not looked at the source code in any depth to see how this may be achieved (I have quite a bit on my plate at the moment), but I thought I would post this request in case it appears to be a quick change for anyone already familiar with the code:

I like the time saving and/or improved detail of adaptive slicing, and it treats the accuracy of external curves and protuberances very well, but it also seems to have no effect on the z-axis dimensional accuracy of features such as small holes. With both equal layer heights or adaptive layers, circular holes tend to print more as ellipses, and even worse either the top or the bottom will be more flattened than the other side, leading to a slightly off-position hole if cleaned up in post-processing with a hand drill, that may not align with parts printed in different orientation.  

Adaptive slicing that decreases the layer height near the bottom and top of vertical holes would greatly improve rapid prototyping of mechanical parts by decreasing thew need for post-processing (i.e. drill press boring of the holes to ensure dimensions and position), and improving alignment/placement.

I have been using a bit of a workaround by adding a few small sacrificial surface features  around the top and bottom of the holes, which are sanded off after printing.  That seems to somewhat force the behavior that I am looking for (or at least it usually produces a hole that is round enough that it can be designed slightly smaller than needed in CAD and then reamed to proper diameter with a hand drill afterward). Getting the top of the hole to “round out” is easier than getting the bottom ‘side’ to behave.

Below, I have an envelope sketch of the desired behavior, as well as a screenshot of how the adaptive layer option treats a 3mm diameter, horizontal hole, and then a screenshot of the slicing behavior of the workaround I have been using with the exact same slicer settings (not exactly the results I would want, but definitely an improvement).  

![adaptive_layers](https://user-images.githubusercontent.com/6373527/47320326-1e91c500-d61f-11e8-9467-cc0fe0bbaa4a.png)

(An additional feature that would improve adaptive slicing would also be layer-height-dependent variation of parameters like temperature/speed/etc to prevent surface-sheen banding, dimensional issues, and poorer print quality on layers whose optimal print settings fall outside of the ‘baseline layer’ height’s optimal settings… but I suppose that is a different feature request. If there is a large section of particularly small layers, I will occasionally adjust those parameters on the fly via trial-and-error through LCD screen menus while printing to improve quality, but an automated option in the slicer would be much preferred — i.e. options for temperature and speed variation % delta between max and min layer heights, etc.)

**Comment by ChrisTerBeke** [comment]
The current adaptive layer height looks at all slopes of the model. It's hard to detect which slopes are on the 'outside' and which on the 'inside'. It looks at the steepest slope in the entire layer(s). Maybe you can get better results when tweaking the adaptive layer height settings?

A for the speed and temperature regulations, it was discussed (and also hinted at in the final paper I wrote about it) but it will take a lot of time to implement and there are not plans for now to put in that effort.
