### ISSUE TITLE
Can't connect to OctoPrint via .local (possibly IPv6 issue?)

### ISSUE THREAD

**Issue by SteveDC2** [Ultimaker/Cura#4639]
**Application Version**
3.5.1

**Octoprint Version**
Version 1.3.9 but other versions also exhibit the same behavior

**Platform**
Windows 10

**Printer**
CR10s & Mendel RepRap

**Steps to Reproduce**
Try to connect a printer to OctoPrint

**Actual Results**
I can't get Cura to connect to Octoprint, Cura continually sits "Checking the API key" and never returns.
I get this result whenever the printer IP/Hostname is set to a ".local" name, e.g. "cr10s.local". If I use an IPv4 address then everything seems OK.

If I ping the address "cr10s.local" then ping displays an IPv6 address, not an IPv4 address so I think there might be an issue with v6 addressing.

If I click "Open in browser" I correctly get a connection to Octoprint in my browser.

**Comment by fieldOfView** [comment]
For me the .local name also resolves to an IPv6 address, and the connection works just fine.

Could you post cura.log? See Help -> Show configuration folder.

**Comment by SteveDC2** [comment]
Sorry for the delayed response. I was in the middle of some prints.

Another interesting observation is that if I go to the "Connect to Octoprint" dialog and paste the API key it sits "Checking the API". If I close the dialog and return to the normal Cura window then go back to manage printers and select "Connect Octoprint" again, I can no longer type anything in to the API key text box. Clicking in the box does not present a cursor and nothing I type appears. the only way to get back to being able to enter the key is to completely close Cura and start again. I get exactly the same result even if I add a completely new Octoprint instance.

Log file is attached

[cura.zip](https://github.com/Ultimaker/Cura/files/2521403/cura.zip)

**Comment by fieldOfView** [comment]
I have created a new issue on the OctoPrintPlugin issue tracker:
https://github.com/fieldOfView/OctoPrintPlugin/issues/93
