### ISSUE TITLE
diameter of filament in cura 3.5.1

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#4655]
Application Version
3.5.1
Platform
Win64

Where can i see diameter of filament?

**Comment by pinchies** [comment]
I had a similar issue to the one I think you are experiencing... 
https://github.com/Ultimaker/Cura/issues/4660

**Comment by userosos** [comment]
@pinchies No, I can not find anywhere parameter filament diameter.

**Comment by pinchies** [comment]
It is in the machine settings.

**Comment by userosos** [comment]
@pinchies in the machine settings I set the approximate value. This is indicated in the description.

**Comment by pinchies** [comment]
Ok, then if you want to, you can set the exact value in the material settings - you can set the exact diameter for each material you use.

**Comment by userosos** [comment]
@fieldOfView i updated the plugin. Now it work! Thx!
