### ISSUE TITLE
[3.5] Little misplacement of a tree support circle

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4657]
**Application Version**
3.5.0

**Platform**
Windows 10 x64

**Printer**
Cr-10S

**Steps to Reproduce**
Use tree supports

**Actual Results**
There is a little misplacement on a support layer. You can see the inside, so it will have an empty area thus making the support weak.

**Expected results**
The supports should be linear. 

**Additional Information**
![tree support](https://user-images.githubusercontent.com/20385116/47538333-0cd44a00-d8cb-11e8-9d13-3b8e7f9203f4.png)
![tree support 2](https://user-images.githubusercontent.com/20385116/47538603-8fa9d480-d8cc-11e8-8e13-0f305aeecc76.png)

[CCR10S tree support.zip](https://github.com/Ultimaker/Cura/files/2517214/CCR10S.tree.support.zip)

**Comment by alekseisasin** [comment]
Hi @Liger0, Thank you for your report. We know about this edge case and it is expected behaviour with the current implementation. In a short-term, we will not be able to fix it, sorry. What you can do, try to adjust the Tree Support Collision Resolution. (please check related settings to Tree Support), I hope it will improve quality.

**Comment by Liger0** [comment]
> 
> 
> Hi @Liger0, Thank you for your report. We know about this edge case and it is expected behaviour with the current implementation. In a short-term, we will not be able to fix it, sorry. What you can do, try to adjust the Tree Support Collision Resolution. (please check related settings to Tree Support), I hope it will improve quality.

So now I am facing related but more extreme situations.
In some cases, a support layer is completely skipped, in some other case, some layer is completely printing in the air and so the tree won't be printed and the print will fail.
I'll attach a screen and the model.

[tree.zip](https://github.com/Ultimaker/Cura/files/2659251/tree.zip)
![tree](https://user-images.githubusercontent.com/20385116/49680208-687d2000-fa92-11e8-8d32-a2162a967678.png)

**Comment by Ghostkeeper** [comment]
This problem should be fixed in Cura 4.1.
