### ISSUE TITLE
Anet A6 stops at initial G-code and waiting for user confirmation

### ISSUE THREAD

**Issue by sim31r** [Ultimaker/Cura#4665]
Init G-code, standart for Marlin, I added only a pause of 5 seconds (for table check level)
error occurs 50% of the time, not stable
At old version 3.0 everything was fine 
At new version 3.5.1, 3.5.0 this error

Ibitial G-Code, standart and my small parts
OS Windows 7 64bit
Printer Prusa I3, G-code type Marlin

(deleted the code as it is not needed here)

The printer stops forever, until you press the button on the front panel. Whith the message "Waiting for user..."
But I am not send "M0" - endless waiting
M105 added for stability, but it is not necessary
The error is big. The printer is waiting with a heated nozzle and a table (If, for example, went to drink coffee and forgot about the printer)
If export the G-code to Repeater Host, work fine, pause 5 seconds if specified. 
I think the Cura 3.5.1 (Cura 3.5.0) sends the wrong code to the printer, in the case when there is a long wait (heat, pause).
I can see the exchange in the COM port, I think there is a reason.

**Comment by sim31r** [comment]
I try the beta version. 
Ultimaker Cura-3.6.99-fix_press_to_resume-win64.exe
At the moment, once launched, all is well.

**Comment by sim31r** [comment]
At the moment everything is working well with v3.6.99. Printed 10-15 small objects.

**Comment by diegopradogesto** [comment]
This issue seems to be fixed in 3.6 BETA. Next week we will release the stable version. Thanks for the tests!

**Comment by BatLab1** [comment]
I have version 3.6.0 and I have the same problem, totally ruined hours of printing. So what is a good for this issue.

**Comment by HuguesDug** [comment]
Same issue.

Anet A8, marlin firmware 1.1.9
Cues 3.6

After heating, request user confirmation randomly.

But is still there.
