### ISSUE TITLE
Cura 3.5.1 imported mesh orientation not respecting original positions as exported from modeling app. 

### ISSUE THREAD

**Issue by jkushwara** [Ultimaker/Cura#4673]
First post on this board - hope I've done everything correctly !

Cura 3.5.1

Windows 7

Creality CR10S5

1. Disable auto drop to plate and keep objects apart in preferences
2. Import two sample meshes
3. Reset all model positions and transformations

Models show the proper XY positioning but Z position of both are on the bed. Cube object does not maintain desired embedded position within sphere.

Expected results would be meshes maintain original orientation either on import (after disabling the relevant preferences) or after resetting positions and transformations. 

![cura_object import orientation](https://user-images.githubusercontent.com/44510891/47591255-f666d680-d93c-11e8-94aa-6bd9c7ddaa21.jpg)

[import test meshes- embedded cube.zip](https://github.com/Ultimaker/Cura/files/2520824/import.test.meshes-.embedded.cube.zip)

**Comment by nallath** [comment]
If you want this, you need to use the merge option.
