### ISSUE TITLE
[3.5.1] Slicing error, several wrong layer in the middle of a print

### ISSUE THREAD

**Issue by Plek324** [Ultimaker/Cura#4681]
**Application Version**
3.5.1

**Platform**
Windows 10, 64 bit

**Printer**
custom: Cartesian style from FLsun, 

**Steps to Reproduce**
Slice the attached STL, with the largest flat side facing down, at 0.2mm

**Actual Results**
Layers 33-48 are wrong, large parts of the structure is missing

**Additional Information**
- Similar errors occur also at when slicing at different heights
- when rotating the object (green circle) it is ok, except when rotating it 180 degrees
- I also tried cura engine in reperier-host 2.0.5, this worked fine
- All files are included in the attached zip
[CableRack.zip](https://github.com/Ultimaker/Cura/files/2523233/CableRack.zip)

**Comment by Vandrasc** [comment]
Hi @Plek324 ,  In x-ray view, the red areas show issues with the model, you can verify that by clicking the “View mode” button in the top right corner, there is a big "red" area in the model which means that the model contains some holes/gaps. 

![screen shot 2018-10-29 at 08 35 17](https://user-images.githubusercontent.com/26549794/47635776-79af4480-db56-11e8-9ead-8b42eede6d5b.png)

You can use any of the open source repair .stl files application and give it another try, though I think it will be hard filling in those gaps.

**Comment by Plek324** [comment]
Hi thanks for clearing that out. I'm still a bit confused though, because if I now open the same .stl file it's fine. But if I open the .3mf I get the red arc again.

Also, wouldn't it be possible to give a warning when the model is not watertight? An error like this could easily come by unnoticed, potentially ruining a long print. 

Peter

**Comment by alekseisasin** [comment]
One of the options is to provide a setting in preferences to perform extra model validation for defects.
Then we need to create a "clear" feature request with proper workflow.
