### ISSUE TITLE
[master] layer view missing layer slider

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#4683]
**Application Version**

master

**Platform**

Linux

**Printer**

CR-10

**Steps to Reproduce**

Load project & slice. Select layer view.

**Actual Results**

All looks good except the layer slider is missing!

**Expected results**

Layer slider should be displayed.

**Additional Information**

![screenshot_2018-10-29_15-28-58](https://user-images.githubusercontent.com/585618/47660764-9d42b100-db8f-11e8-88c0-22ea72155cc5.png)

And no, it's not hiding behind the panel!

**Comment by smartavionics** [comment]
[cura.log.txt](https://github.com/Ultimaker/Cura/files/2526240/cura.log.txt)

**Comment by smartavionics** [comment]
I removed the cache directory and it didn't make any difference.

I notice that it isn't just missing the sliders but also the other controls that affect the layer view.

**Comment by Vandrasc** [comment]
FYI @Ghostkeeper, this is what we were discussing yesterday.

**Comment by Vandrasc** [comment]
Devs CURA-5885

**Comment by LipuFei** [comment]
@smartavionics I made a commit in Uranium and it seems to fix the problem. Could try that?
https://github.com/Ultimaker/Uranium/commit/cbb847a1a2e67858b009abd2db20313e3148c763

**Comment by smartavionics** [comment]
Hi @LipuFei , just off to the dentist!, will try later this morning.

**Comment by smartavionics** [comment]
Just tried that and it works OK, closing...
