### ISSUE TITLE
3.5.1 & 3.6B zoom stuck @far when inverted in config

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#4693]
**Application Version**
3.5.1 & 3.6B

**Platform**
win10/64, Mouse FlipFlopWheel set to "1" (reversed) in regedit
![ice_screenshot_20181030-161438](https://user-images.githubusercontent.com/30949968/47724259-fcbbc200-dc5e-11e8-916e-11d516c4bcdd.png)

**Printer**
CustomFDM

**Steps to Reproduce**
In Cura 3.5.1 try zooming **all the way** in/near and out/far. if not stuck, try inverting zoom direction in config and try again. in my case builtplate stuck at far (zoom all the way out) when zoom is inverted in config.

**Actual Results**
zoom stuck at the far end. pressing any of the top camera manipulators releases the zoom. 
![ice_screenshot_20181030-161056](https://user-images.githubusercontent.com/30949968/47724078-9636a400-dc5e-11e8-86df-52475a2f3451.png)
**Expected results**
zoom should never freeze or lock at any stage.

**Additional Information**

**Comment by nallath** [comment]
This is a bit to obscure for us to actually try and fix.

**Comment by Thisismydigitalself** [comment]
For the record, in my case builtplate stuck at far (zoom all the way out) when zoom is inverted in config.
[ZoomStuck.zip](https://github.com/Ultimaker/Cura/files/2557128/ZoomStuck.zip)

**Comment by Thisismydigitalself** [comment]
Same with 3.6 released version. zoom stuck either zoomed all the way in and/or out.
