### ISSUE TITLE
A way to zoom in on small or flat objects

### ISSUE THREAD

**Issue by jaxelsson** [Ultimaker/Cura#4697]
Currently I can't seem to zoom in on the print bed itself, to view smaller or flat objects.  This is a big hindrance.  Would be good if the center point of the zoom was by default the center of the object or the bed, instead of 50% of the way up into thin air.  (See screenshot)  

Love the app, but this is becoming a deal breaker for printing small/flat things, as I sort of just have to hope for the best without inspecting the path.

<img width="956" alt="screen shot 2018-10-30 at 4 05 38 pm" src="https://user-images.githubusercontent.com/8505743/47747129-fc6ef700-dc5d-11e8-8c10-2c18d7fb56df.png">

**Comment by Thisismydigitalself** [comment]
Have you tried this?
![ice_screenshot_20181031-070311](https://user-images.githubusercontent.com/30949968/47767213-4e099700-dcdb-11e8-93e7-21dd6a948b3c.png)

**Comment by alekseisasin** [comment]
@jaxelsson , Did you try the setting "Center camera when item is selected"

**Comment by GregValiant** [comment]
@jaxelsson is this still relevant in new cura versions (5.8.0 and up).
I'll close this.  Let me know here if you feel that is premature.
