### ISSUE TITLE
[feature-req] Show current layer number in progress when printing via USB 使用USB联机打印时，能否让打印进度显示当前打印的层数？

### ISSUE THREAD

**Issue by Leonswilly** [Ultimaker/Cura#4699]
无人值守的远程打印可能会出现打印自动中断或者由其他原因造成的打印未能按计划完成，亦或打印时间过久需要中途暂停很长时间，甚至关闭打印机的项目，如果可以显示当前的打印层数，将来继续打印的时候就可以知道从第几层开始继续打印，可以避免因中途暂停导致的项目作废。

**Comment by LipuFei** [comment]
你好 @Leonswilly，由于Ultimaker的打印机包括2和3不支持USB打印，我们讨论之后决定我们不会专门增加这个功能，我们也无法在Ultimaker打印机上测试这个功能是否正确。不过你可以使用PostProcessingScript这个插件实现这个功能。下面是一个演示动图：
![2](https://user-images.githubusercontent.com/2630468/48062228-be278980-e1c1-11e8-9cbb-b99e3321c9f9.gif)
