### ISSUE TITLE
Hello world / example plug-in

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#47]
As a developer I'd like to be able to develop a plugin while starting from a simple example, so that I don't have to figure out everything or have advanced programming skills nor deep knowledge of Cura's architecture.

**Comment by Dim3nsioneer** [comment]
+1

**Comment by BagelOrb** [comment]
This should be included when solving https://github.com/Ultimaker/Cura/issues/13

**Comment by awhiemstra** [comment]
Those are actually unrelated, the discussion in #13 is about post processing GCode, this is about documentation of the base plugin system.

**Comment by nallath** [comment]
I've made a pretty horrible (but very simple) plugin. Should clarify things. 
https://github.com/nallath/PrintCostCalculator
