### ISSUE TITLE
Children settings visible when they shouldn't

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#471]
Steps:
- make the following settings visible: Enable Support, Enable support roofs, Support Roof Thickness 
- check Enable Support roofs
- uncheck Enable Support
- See how Enable Support roofs gets invisible
- See how Support Roof Thickness is still visible

The setting [Enable Support Roofs] is invisible, but has a user defined setting while there is no message "there is a hidden setting with user defined value"

![cura_support_roof_setting_visible](https://cloud.githubusercontent.com/assets/8895761/10368758/32c74ea4-6dd7-11e5-995b-35f92c1226f7.png)

**Comment by nallath** [comment]
I think this has already been fixed.
