### ISSUE TITLE
Hollow bell is made solid

### ISSUE THREAD

**Issue by iainmack52** [Ultimaker/Cura#4713]
**Application Version**
3.5.1

**Platform**
Windows 10 Home 64 Bit

**Printer**
As soon as I figure out how to attach - I will. Printer is Anet E10

**Steps to Reproduce**
Just import STL and slice. I tried several different SketchUp and Blender files, creating different STL files. They all had the same result.

**Actual Results**
A hollow bell becomes an object that prints with a solid/covers the whole base layer.

**Expected results**
I expected to see a circle of print, becoming a bell shaped object. This used to happen with this printer on this PC a month or so ago. May have been before 3.4 even?
[AnetSketchUpBellProject.zip](https://github.com/Ultimaker/Cura/files/2541242/AnetSketchUpBellProject.zip)

**Additional Information**
On the screen it all looks just fine, including in Cura, but this file is coming out with a complete layer rather than just the edges, meaning the body of the bell. The only thing that has changed is Cura. Blender is the same version, SketchUp is the same version, the Anet E10 has not been changed or updated in any way. I don't want a bottom layer in the central void of the bell.

**Comment by smartavionics** [comment]
Turn off the Union Overlapping Volumes setting...

![screenshot_2018-11-02_09-18-53](https://user-images.githubusercontent.com/585618/47906079-649d2300-de80-11e8-88f7-49af7447d4e5.png)

**Comment by smartavionics** [comment]
This is what the mesh tools plugin thinks of your model...

![screenshot_2018-11-02_09-21-27](https://user-images.githubusercontent.com/585618/47906242-b9409e00-de80-11e8-9556-2b849c4c3383.png)

**Comment by iainmack52** [comment]
Thank you Mark. You can probably tell I am new at this - and didn't even
know that option existed.

Regards,
Iain

**Comment by smartavionics** [comment]
Yes, but if your model was good you would not need to change that option. The model needs fixing.

**Comment by iainmack52** [comment]
No idea. None of the models used were mine.

**Comment by rburema** [comment]
Since this is an issue with the model, rather than with Cura, I'm closing the issue.
