### ISSUE TITLE
Repetier Crashes because of Cura interference! [Solved]

### ISSUE THREAD

**Issue by gnuion** [Ultimaker/Cura#4714]
The issue is simple and I believe it will happen to all printers. When using Repetier to run the gcode and the printer is USB connected, Cura tries to take control of the USB connection therefor crashes Repetier destroying the print. it really makes me angry when I need to open Cura, forget about Repetier and my print stops!

**Comment by smartavionics** [comment]
Hello @gnuion , I'm sorry I can't help directly with your issue but the people who could help you would really like to know some more info like what OS you are using, Cura version, etc. Thanks.

**Comment by fieldOfView** [comment]
You can disable the USB Printing plugin in Toolbox/Marketplace on the "installed" tab. This will disable any USB trickery by Cura.

**Comment by gnuion** [comment]
fieldOfView thank you! I can mark this as solved now!

**Comment by fieldOfView** [comment]
Cura shouldn't crash other applications even with USB Printing enabled. Having said that, if repetier is crashing because it is letting Cura take over the serial port, then that would be strange behavior from repetier. Like @smartavionics says, what OS and version(s) are you using?

**Comment by gnuion** [comment]
I am using Windows 10, Repetier V2.1.3, Cura 3.5.0. Had the same issues on older Windows OS, Cura and Repetier versions. Didn't try it under Linux.

**Comment by gnuion** [comment]
It doesn't happen right away though, usually the print stops after 30 minutes. If I don't open Cura while Repetier is running the print finishes even if it takes a day. So it took time for me to notice the cause.
