### ISSUE TITLE
Gyroid Is great! one small thing thou..

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#4718]
**Application Version**
3.6B

**Platform**
Win10/64

**Printer**
CFFFP

**Steps to Reproduce**
Use Gyroid infill - it's great!

**Actual Results**
Not sure if this is an issue, but infill overlap % does not effect Gyroid infill. it does influance other infill patterns.

**Expected results**
To be able to control overlap. 

**Additional Information**
Thank you for Gyroid Infill @smartavionics and all.

**Comment by smartavionics** [comment]
Ah, yes. I forgot about that. Sorry, will take a look over the weekend.

**Comment by smartavionics** [comment]
Fixed that, thanks for the report.

**Comment by Thisismydigitalself** [comment]
![img_20181103_130809](https://user-images.githubusercontent.com/30949968/47951466-e2892900-df69-11e8-9ef9-92ef52a23d42.jpg)

**Comment by smartavionics** [comment]
Nice colour! Is that PETG? I use it a lot and find I get very good results. I use no-skin combing with retracts for travels > 10mm.

**Comment by Thisismydigitalself** [comment]
You are an observant person. 
Combing was Off. i've now updated my profile to no-skin. 
This is red PLA+. i find PLA+ colours to be more vivid than regular/cheap PLA's. overall much better stuff.

**Comment by smartavionics** [comment]
I would also set the max combing distance without retraction to something like 10mm as that allows short non-retract travels but retracts for the longer moves which reduces the dribble.

**Comment by Thisismydigitalself** [comment]
Retraction, on my direct drive system, was set to 5mm . 10 or 5 does not change print time so if 10 wont worsen things up while cutting retractions in half, than 10 would be the new 5.

**Comment by smartavionics** [comment]
I don't mean the retraction distance, I mean the Max Comb Distance With No Retract setting.

**Comment by Thisismydigitalself** [comment]
I did not even know this setting exists and so never used it before.
Wanted to try it out on this same project but guess what - 3.6B crashes when i try to load it back.
No joy.

**Comment by smartavionics** [comment]
Ha! that's Cura for you, each release is guaranteed to provide both good and bad changes!

**Comment by fieldOfView** [comment]
Totally off-topic, but WAT?
![image](https://user-images.githubusercontent.com/143551/47962487-a2837e00-e01d-11e8-8f66-f43b2963395c.png)

**Comment by Thisismydigitalself** [comment]
One cannot appreciate good with and/or without bad.
Curadox.

**Comment by Thisismydigitalself** [comment]
> 
> 
> Totally off-topic, but WAT?
> ![image](https://user-images.githubusercontent.com/143551/47962487-a2837e00-e01d-11e8-8f66-f43b2963395c.png)

A glitch in the Matrix

**Comment by smartavionics** [comment]
Hmm, does that mean that we can now submit PRs for bugs that haven't occurred yet?

**Comment by Thisismydigitalself** [comment]
@smartavionics 
Question: mm/s wise - when infill wiggles like with Gyroid, what is being considered as the legth of it?
the overall length of the line or th top footprint end to end? Sometimes i feel the need to reduce infill speed cause in tight corners the printhead breaks my printer's speed limit.

**Comment by smartavionics** [comment]
Hi @Thisismydigitalself , the length is going to be the sum of all of the individual line segments that make up the gyroid curve. All of the line segments are printed at the same speed (the infill mm/s). I don't know why a tight corner should be a problem. What I have seen is that resonance can occur when the frequency of the gyroid wave matches the printer's resonant frequency. In that situation the print head can thrash around rather alarmingly. The solution is to either reduce the mm/s or density as that lowers the gyroid wave frequency.

**Comment by diegopradogesto** [comment]
The fix for this bug was added to master.
