### ISSUE TITLE
Program crashes after deleting second extruder

### ISSUE THREAD

**Issue by ShozoMotoSerwis** [Ultimaker/Cura#4722]
Hello.
Just because of my curious I've added second extruder in printer settings.
Next I've tried to remove that extra extruder and the Cura simply turns off after clicking "1" in numbers of extruders.

**Comment by LipuFei** [comment]
Hi @ShozoMotoSerwis , could you describe the steps you take in details and upload your log file? If you are on Windows, you can find the log file in
```
C:\Users\<your-username>\AppData\Roaming\cura\3.6\cura.log
```

**Comment by Ghostkeeper** [comment]
We couldn't reproduce this. Let's assume it is no longer an issue, since the author is not responding.
