### ISSUE TITLE
[3.5] Empty part

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4725]
**Application Version**
3.5.0

**Platform**
Win 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Load the file and try to slice

**Actual Results**
The part on the head is empty.

**Expected results**
The part on the head is full.

**Additional Information**
![bl](https://user-images.githubusercontent.com/20385116/47958187-9ddfab00-dfc6-11e8-8042-b83ba3d55d37.png)
![bl2](https://user-images.githubusercontent.com/20385116/47958188-9ddfab00-dfc6-11e8-8b1d-fd24e309a404.png)
[CCR10S_BL.zip](https://github.com/Ultimaker/Cura/files/2545417/CCR10S_BL.zip)

**Comment by smartavionics** [comment]
If you use a wall line width of 0.3 or less then those head walls are printed, they must be very thin.

![screenshot_2018-11-04_07-34-47](https://user-images.githubusercontent.com/585618/47961503-3a746e00-e004-11e8-8d63-85ad1563036b.png)

**Comment by Liger0** [comment]
> 
> 
> If you use a wall line width of 0.3 or less then those head walls are printed, they must be very thin.
> 
> ![screenshot_2018-11-04_07-34-47](https://user-images.githubusercontent.com/585618/47961503-3a746e00-e004-11e8-8d63-85ad1563036b.png)

Hi there. Why doesn't it fill in instead?

**Comment by smartavionics** [comment]
Because the model isn't solid?

**Comment by Liger0** [comment]
I found the errors in my model, it seems there were 2 vertices not needed. Thanks.
