### ISSUE TITLE
[3.5] Weird pattern on the top layer

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4727]
**Application Version**
3.5

**Platform**
Windows 10 x64

**Printer**
Cr-10S

**Steps to Reproduce**
Use 0.1 line width and nozzle on printer settings.

**Actual Results**
The top layer is different than the previous ones.

**Expected results**
The top layer should be more circular.

**Additional Information**
[CCR10S_body.zip](https://github.com/Ultimaker/Cura/files/2546572/CCR10S_body.zip)
![top layer 2](https://user-images.githubusercontent.com/20385116/47973102-a9a09f80-e0a2-11e8-85ea-3f2af66c256a.png)
![top layer](https://user-images.githubusercontent.com/20385116/47973103-a9a09f80-e0a2-11e8-8f59-fb26741f8ad9.png)

**Comment by smartavionics** [comment]
Using Middle slicing tolerance...

![screenshot_2018-11-05_07-27-43](https://user-images.githubusercontent.com/585618/47983800-5f341880-e0cc-11e8-9094-9eec89d08ec5.png)

Using Inclusive slicing tolerance...

![screenshot_2018-11-05_07-26-30](https://user-images.githubusercontent.com/585618/47983750-31e76a80-e0cc-11e8-8920-9411b3e37d6e.png)

**Comment by Liger0** [comment]
I didn't think of that setting. Thanks.
