### ISSUE TITLE
cura 3.5.1 crashes

### ISSUE THREAD

**Issue by vair327** [Ultimaker/Cura#4729]
**Application Version**

**Platform**
Windows

**Printer**
gt2560 a+ borad

**Steps to Reproduce**
 print with repetier server.

**Actual Results**
locks up and does not finish sending complete gcode.

**Expected results**

**Additional Information**

**Comment by LipuFei** [comment]
Hi @vair327 , The vanilla Cura releases don't support printing via repetier server, and this can only be done via a Cura plugin or some other means. If you are using a plugin for this, you need to contact the plugin maintainers about this bug.
