### ISSUE TITLE
[3.5]  Stuck at dissectioning on most models with tree supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4735]
**Application Version**
3.5.0

**Platform**
Windows 10 x64

**Printer**
Cr-10S

**Steps to Reproduce**
Load the model and use tree supports

**Actual Results**
The slicing doesn't dissect most of the models I tried

**Expected results**
It dissects correctly

**Additional Information**
![sectioning](https://user-images.githubusercontent.com/20385116/48027707-c8a63c80-e149-11e8-9049-df6fd2e7a6f5.png)
[Sectioning.zip](https://github.com/Ultimaker/Cura/files/2550699/Sectioning.zip)

**Comment by nallath** [comment]
What do you mean by "dissect"?

**Comment by pynej** [comment]
i'm guessing he means the slicer it's processing the model. In my experience the tree support code is VERY slow. I'm guessing that is just never finished for him judging at the complete of the model.

**Comment by pynej** [comment]
FYI, tree supports are only really needed when you have overlapping elements or voids in the sides and you don't want supports affecting the lower surface quality.

**Comment by Liger0** [comment]
Most of the time I try to slice the sectioning remains at 0 like in the image even after an hour. It is good if it works on 1 / 5 models. I would use it because much times it reduces the waste of material. On 3.4.1 it worked, now it doesn't.

**Comment by Liger0** [comment]
I update this saying it doesn't slice using normal suppoorts too.

**Comment by alekseisasin** [comment]
Hi @Liger0,  I tried to slice your model in Cura 3.6 and it works well for me.

**Comment by Liger0** [comment]
> 
> 
> Hi @Liger0, I tried to slice your model in Cura 3.6 and it works well for me.

With cura 3.6 sometimes it still doesn't even start to slice, same as 3.5.0

**Comment by alekseisasin** [comment]
@Liger0 , Do you still have this issue? Otherwise, I suggest closing this issue.

**Comment by Liger0** [comment]
> 
> 
> @Liger0 , Do you still have this issue? Otherwise, I suggest closing this issue.

As of now on cura 3.6 I haven't seen it yet. i'll reopen it in case I'll notice it again. Cheers.
