### ISSUE TITLE
Problem printing 3 line width cuboid

### ISSUE THREAD

**Issue by zz9pa** [Ultimaker/Cura#4746]
**Application Version**
3.5.1

**Platform**
Windows

**Printer**
CR10 mini

**Steps to Reproduce**
Generate a STL with a vertical cube 1.2mm wide, print with .4 nozzle and line width, and "lines" for top/bottom pattern

**Actual Results**
Prints outer edge and then uses "lines" to fill the gap, taking ages to print something that should be quick.

**Expected results**
print 3 lines

![image](https://user-images.githubusercontent.com/2507509/48096034-1f754a00-e20e-11e8-81b1-c0c38e91f277.png)

Cant upload an STL - but you can generate one using openscad with

cube([1.2,61,39]);

**Comment by diegopradogesto** [comment]
Was it different in 3.4 or previous versions? We changed some behaviour in the merge small lines algorithm and I'm wondering if it's is related.

PS. You can upload a STL or project file if you zip the file.

**Comment by zz9pa** [comment]
Its fine in 3.4.1
![image](https://user-images.githubusercontent.com/2507509/48302442-f0ecbd00-e4f4-11e8-9a66-4d4e56e43f87.png)

**Comment by zz9pa** [comment]
[test1.zip](https://github.com/Ultimaker/Cura/files/2568489/test1.zip)

**Comment by zz9pa** [comment]
Still present in 3.6
