### ISSUE TITLE
Not entire build plate available (Skirt&Brim: OFF) [Cura 3.5.1]

### ISSUE THREAD

**Issue by kulfuerst** [Ultimaker/Cura#4750]
**Application Version**
Cura 3.5.1

**Platform**
Windows 10

**Printer**
Anycubic i3 Mega

**Steps to Reproduce**
Select Anycubic i3 Mega printer profile (print bed size 210x210 mm), import a model of 210x210 mm size or even 209x209 mm size.

**Actual Results**
Cura does not allow slicing of the model, claims it does not fit on print bed. 

**Expected results**
Normal slicing, no issues

**Additional Information**
Cura does not allow usage of the entire print bed. Settings that normally affect this, like skirt and brim are turned off. Outer edge of build plate appears in dark grey and is effectively blocked.
![45548018_10156020797264422_6052313084247146496_o](https://user-images.githubusercontent.com/43445551/48161980-2d919c00-e2dc-11e8-86d1-8bec94e3a491.jpg)
![45761073_10156020819324422_4553442117250187264_o](https://user-images.githubusercontent.com/43445551/48161981-2d919c00-e2dc-11e8-9e36-4ddc08c6c0be.jpg)

.

**Comment by kulfuerst** [comment]
Setting the print sequence to "one at a time" removes the grey edge, but cura still doesn't allow for slicing of the model though, for whatever reason.

**Comment by nallath** [comment]
Infill wipe distance, travel avoid distance and travel avoid other parts also influence that border.
