### ISSUE TITLE
Monoprice Mini Delta Does not home when pressing home button in monitor tab

### ISSUE THREAD

**Issue by A-n-o-r-a-k** [Ultimaker/Cura#4751]
**Application Version**
3.6 beta

**Platform**
Windows 10

**Printer**
Monoprice Mini Delta

**Steps to Reproduce**
Start Cura 3.6 beta, verify printer shows connected, goto monitor tab, click on home button.

**Actual Results**
Nothing happens

**Expected results**
Printer should home

**Additional Information**
no additional information

**Comment by Ghostkeeper** [comment]
Can't reproduce this. Both of the home buttons work fine on an Ultimaker 2. I think it's something with your printer's firmware (or with Ultimaker's firmware), or maybe it was already fixed in the meanwhile?
