### ISSUE TITLE
Disabled extruder selected

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#4758]
Here's a small UI issue for you:

When you have the left extruder selected and are looking at the advanced settings and then load a project file which has the left extruder disabled, the UI doesnt automatically switch to the right extruder.

You are then able to edit settings of an extruder which isn't even enabled.

Not a big issue, but perhaps this is fixable in 5 minutes.

**Comment by diegopradogesto** [comment]
Good catch!

**Comment by Vandrasc** [comment]
devs CURA-5930
