### ISSUE TITLE
Project file doesn't respect positioning

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#4767]
**Application Version**
3.5.1

**Platform**
Linux Mint

**Printer**
UM3

**Steps to Reproduce**
Install Mesh tools from Aldo
Load [hex_tiles.stl.zip](https://github.com/Ultimaker/Cura/files/2565514/hex_tiles.stl.zip)
scale to 10%
Split into parts
( Try disabling all preferences related to scaling and positioning )
save project
clear build plate
load project

**Actual Results**
Objects are all over the place

**Expected results**
Objects retain their positioning

**Additional Information**
Before save:
![image](https://user-images.githubusercontent.com/8895761/48257730-a0e9f980-e413-11e8-801f-83d81abc7341.png)

After load:
![image](https://user-images.githubusercontent.com/8895761/48257768-b9f2aa80-e413-11e8-8a0c-d22853025b04.png)

Project:
[repositioning_problem.3mf.removeextension.zip](https://github.com/Ultimaker/Cura/files/2565520/repositioning_problem.3mf.removeextension.zip)

**Comment by BagelOrb** [comment]
Here's my preferences:
![image](https://user-images.githubusercontent.com/8895761/48257820-e73f5880-e413-11e8-908b-8e6914f62850.png)

**Comment by diegopradogesto** [comment]
It's really weird, but I can confirm it. I also attach another small STL that consist in 4 small parts and something similar happens.
[objects.stl.zip](https://github.com/Ultimaker/Cura/files/2569324/objects.stl.zip)

**Comment by diegopradogesto** [comment]
Do you have any ideas about this, @fieldOfView ? We saw that it only happens after using the 'Split object into parts'

**Comment by fieldOfView** [comment]
I am not sure, but it could be that all of the created meshes have the same origin; the origin of the original non-split mesh. If the mesh origin is somehow included in the convex hull of the now individual meshes when loading the 3mf file, and this is used to push the models apart even though the preferences say not to do that, then this spreading apart would be an expected outcome. I remember issues about both these phenomena, but don't remember the outcome.

An interesting way to test this hypothesis is to select all subparts after loading them back in and merge them. They should snap back to their correct relative position. If this confirms the hypothesis, then Cura is doing two things wrong: (1) it makes the origin of a mesh in a 3mf part of the convex hull and (2) it rearranges models after loading even if the push apart option is turned off.

**Comment by diegopradogesto** [comment]
OK, we will investigate. Thanks for the tips.

Devs. CURA-5931

**Comment by fieldOfView** [comment]
For the record, these are the related issues I was thinking about:
https://github.com/Ultimaker/Cura/issues/2132 / https://github.com/Ultimaker/Cura/issues/3847 and https://github.com/Ultimaker/Cura/issues/3201

**Comment by diegopradogesto** [comment]
I can confirm that after merging the model, they snap back to the original position.

**Comment by LipuFei** [comment]
@diegopradogesto @fieldOfView I made a PR to fix this issue: https://github.com/fieldOfView/Cura-MeshTools/pull/8

**Comment by LipuFei** [comment]
I also found that one part in the hex tiles model seems to get split too much.

![image](https://user-images.githubusercontent.com/2630468/64015216-5d888500-cb24-11e9-8e3e-f56b04e8a168.png)

**Comment by BagelOrb** [comment]
That's just because I modelled it badly. Not water-tight.

**Comment by diegopradogesto** [comment]
We were taking a look at this issue and after some trials and errors, we've decided to defer this for now at least.

**Comment by BagelOrb** [comment]
From my point of view this has nothing to do with the split into parts plugin.

If I save a build plate I expect it to be loaded the same as I saved it, but somehow there is some discrepancy and the model doesn't get loaded the same way it is saved - or not all data used to determine the positions of objects is saved to the project file.

**Comment by mahtDFR** [comment]
Not a fix, but a workaround: close file, open Cura preferences and uncheck 'automatically drop models to build plate'. Then reopen the project file.

**Comment by BagelOrb** [comment]
Wait a minute. If it is still an issue and it clearly is a bug, then shouldn't it be deferred, rather than Wont fix?

**Comment by mahtDFR** [comment]
Ok, I will switch it back to deferred. It's unlikely we will be able to devote time to fixing it.
