### ISSUE TITLE
Layer Slider Deadzone / Sensitivity

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#477]
I have been struggling with the layer slider, especially on prints with higher layer counts. There seems to be an excessively large deadzone, followed by overly sensitive movement. It is nearly impossible to move only one layer, and it seems that the layer keyboard shortcut is no longer functional.

**Comment by nallath** [comment]
The keyboard shortcut is now ctrl + arrow key.

**Comment by CCS86** [comment]
I'll try that (could have sworn I tried every modifier key + arrow combination)

HAve you noticed the deadzone and sensitivity feeling off on large prints?

**Comment by nallath** [comment]
Not really, but to be honest i've only tried it with smaller prints.

**Comment by CCS86** [comment]
I noticed that one of the more intrusive aspects is actually that there is a big lag in the layer control. It seems to wait until the drawing of the layers is complete before updating the slider position. 

It seems much better if instead, the slider was independent of layer drawing. Meaning that you could have immediate control of layer slider position, then the layer drawing would follow.

**Comment by nallath** [comment]
It should be independent of drawing, but python has a the infamous GIL which messes with things.

**Comment by BagelOrb** [comment]
not a problem any more
