### ISSUE TITLE
[3.5.1] brim on the inner supports

### ISSUE THREAD

**Issue by mixtur** [Ultimaker/Cura#4778]
**Application Version**
3.5.1

**Platform**
Windows 7

**Printer**
[CCR10_tail.zip](https://github.com/Ultimaker/Cura/files/2569287/CCR10_tail.zip)

**Actual Results**
![iany0sr](https://user-images.githubusercontent.com/2968077/48312095-bea59300-e5ba-11e8-8b37-5b38eee68865.jpg)

**Expected results**
I would expect to see brim around that inner part of the support. It keeps unsticking.

**Comment by alekseisasin** [comment]
After loading the project I see that you are using tree support, it is experimental and we cannot guaranty the correct output for all models. But we already had a fix/workaround for this case. You can wait for a new Cura 3.6 stable version or download 3.6 Beta version. In this version, you can find a setting "Enable Support Brim". After enabling the setting it, you will the brim around inner parts in the model.
For now, I will close the issue if you will still have the same issue in 3.6 version then we can re-open the issue.

**Comment by mixtur** [comment]
The same happens with concentric supports, so I believe it is more general than that. I can't send you project right now but I will as soon as I can.

**Comment by mixtur** [comment]
Ow. Sorry I didn't read the whole response. Ok. I'll wait for 3.6.

**Comment by alekseisasin** [comment]
New Cura 3.6 is online. You can try it.
