### ISSUE TITLE
cura 3.5.1 gives holes in the print where they should be closed.

### ISSUE THREAD

**Issue by khan04what** [Ultimaker/Cura#4786]
**Application Version**
<Cura 3.5.1>

**Platform**
<WINDOWS 10 64 bit>

**Printer**
<ANYCUBIC I3 Mega>

**Steps to Reproduce**
<don't understand this question?>

**Actual Results**
<
- The result is thats Cura3.5.1 giving holes in the print where they should be closed. and I print these when saved as g-code file on sd-card and the print has than other place on the print more holes or little lines that not printed. >

**Expected results**
<This fixed hole and line bug>

**Additional Information**
<Everytime a open an stl file go to layer view and view the file to print also fixed print leave holes behind.>

**Comment by smartavionics** [comment]
Please zip the project file and attach to this issue. Without that it's impossible to investigate - thanks.

**Comment by khan04what** [comment]
http://www.thingiverse.com/thing:1229240
Zombie Cyclist (ZombWar) by Deividcole 

I tried to send my stl file via 7zip but that did not work, he did not accept it.
i have picture: 
![image](https://user-images.githubusercontent.com/42573250/48386640-f3b50100-e6f2-11e8-9468-83a668b70094.png)

![biker2](https://user-images.githubusercontent.com/42573250/48386822-94a3bc00-e6f3-11e8-8a74-6361a2b1a06d.jpg)

maybe this will help you?

**Comment by smartavionics** [comment]
Not really, I needed the project file to be able to check your settings. Anyway, it looks like you have coasting enabled. Try disablng that.

**Comment by khan04what** [comment]
I disabled coasting it looks better in layer view now. I want to say that I had no problem with previous versions and certainly because the function had to reduce stringing. but I will also try another print. but for now in cura the print has no holes and looks oke.

**Comment by rtorresca** [comment]
Same problem in 3.6.
Disabling coasting also works.

**Comment by nallath** [comment]
This is intentional; Coasting is useful if your extruder needs some time to stop extruding. Even though that layer view shows that there is a hole, it does not mean there actually will be a hole.
