### ISSUE TITLE
Z Seam

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#4792]
How can I move the Z Seam of  Wall one to wall 2 and so on?  For a better waterproof. 
![screenshot 3](https://user-images.githubusercontent.com/43827576/48439305-42f84180-e786-11e8-9240-6cbc97d004aa.png)

**Comment by nallath** [comment]
As far as I know, there is currently no way to do that. You could try and see what setting the z-seam orientation to random, but that's about it.

**Comment by Liger0** [comment]
Did you disable the external wall compensation?
