### ISSUE TITLE
[3.6] Slice Issues - broken model lines when slicing.

### ISSUE THREAD

**Issue by ncwhale** [Ultimaker/Cura#4795]
**Application Version**
3.6

**Platform**
WIndows 10 64bit with i7 4770 / 32G MEM

**Printer**
Anycube Chiron
[PI3_Midchildan system(v2).zip](https://github.com/Ultimaker/Cura/files/2581643/PI3_Midchildan.system.v2.zip)

**Steps to Reproduce**
Open Cura -> Import my model -> Display slice view.

**Actual Results**
Slice broken model lines which can be printed.

![cura_2018-11-14_23-45-54](https://user-images.githubusercontent.com/1552933/48496412-e91e7700-e86c-11e8-9023-21e483f950b7.jpg)

**Expected results**
Let the model be printed use one or two lines.

![cura_2018-11-14_23-45-54](https://user-images.githubusercontent.com/1552933/48496804-c8a2ec80-e86d-11e8-8b5c-956bf201137a.jpg)

**Additional Information**
I disabled support to let the capture image more clear.

Strange things happen when turn support layer on:

![cura_2018-11-15_00-57-38](https://user-images.githubusercontent.com/1552933/48498646-a3b07880-e871-11e8-8054-e12fad328510.jpg)

It's clearly that support layer got the right way,but the model layer does not.

**Comment by smartavionics** [comment]
The model has problems.

![screenshot_2018-11-14_17-15-29](https://user-images.githubusercontent.com/585618/48499712-f289ee00-e830-11e8-8c25-41ddb1a8dbda.png)

**Comment by ncwhale** [comment]
What's this tool's name?

**Comment by smartavionics** [comment]
It's the mesh tools plugin.

![screenshot_2018-11-15_14-57-14](https://user-images.githubusercontent.com/585618/48560927-c7fa6c80-e8e6-11e8-83ab-f87ffad2108a.png)

**Comment by Liger0** [comment]
> 
> 
> What's this tool's name?
> 
> Oh, I See. Any tools suggest to fix this model? I made it by tinkdesk...

You could try windows 3d builder for fast automatic fixes.

**Comment by ncwhale** [comment]
I tried almost every tool can find to fix the .STL file, and still, got the Gcode generate error: some lines are missing.
