### ISSUE TITLE
[3.6.0] Problems with displaying the Cura interface settings windows when using dark themes in KDE.

### ISSUE THREAD

**Issue by bliser3d** [Ultimaker/Cura#4797]
**Application Version** - 3.5.0 / 3.5.1 / 3.6.0
**Platform** - Linux, KDE5, Plasma Color Schemes - "Breeze Dark variant" end "Breeze High contrast".
**Printer**, **Steps to Reproduce** , **Actual Results**, **Expected results** , **Additional Information** - same as described in message https://github.com/Ultimaker/Cura/issues/4637

**Comment by fieldOfView** [comment]
> same as described in message #4637

Then it is a duplicate, and this new issue only creates more "noise". Please update / comment to the original issue instead, and close this one.

**Comment by bliser3d** [comment]
Closed as a duplicate.

**Comment by bliser3d** [comment]
This problem is completely repeated in version 3.6.0.
