### ISSUE TITLE
3.6.0 printer instelling,printer /extruder  foute weergave

### ISSUE THREAD

**Issue by bertus45** [Ultimaker/Cura#4798]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by bertus45** [comment]
bij printer instelllng,van  printer  naar extruder  geeft bij extruder foute weergave

**Comment by fieldOfView** [comment]
Please fill in the issue template, and please use english; about half of Cura developers aren't native dutch speakers.
