### ISSUE TITLE
[3.6.0] Gaps in outer walls on solid model

### ISSUE THREAD

**Issue by Toxicable** [Ultimaker/Cura#4799]
**Application Version**
3.6.0

**Platform**
Win 10

**Printer**
Tevo Tornado
[Safe_airsoft_knife_handle_only-3mf.zip](https://github.com/Ultimaker/Cura/files/2582244/Safe_airsoft_knife_handle_only.zip)

**Steps to Reproduce**
Slice this model
[Safe_airsoft_knife_handle_only.zip](https://github.com/Ultimaker/Cura/files/2582246/Safe_airsoft_knife_handle_only.zip)

**Actual Results**
Gaps in outer walls

**Expected results**
No gaps in outer walls

**Additional Information**
![image](https://user-images.githubusercontent.com/13490925/48506345-19d2d080-e8ae-11e8-8f5f-d246f791b3f1.png)
![image](https://user-images.githubusercontent.com/13490925/48506355-248d6580-e8ae-11e8-9a15-dffa3ab64854.png)

**Comment by smartavionics** [comment]
Coasting enabled?

**Comment by Toxicable** [comment]
@smartavionics Yup.
I also noticed this happened on another model aswell, im not at my system anymore so cant provde the files for that one untill im back home this afternooon.
here's my profile though: 
[tevo_tornado_extruder_0_tevotornadocura #2.zip](https://github.com/Ultimaker/Cura/files/2582621/tevo_tornado_extruder_0_tevotornadocura.2.zip)

**Comment by smartavionics** [comment]
Isn't it the coasting that produces the gaps? Turn off the coasting and the gaps go away?

**Comment by Toxicable** [comment]
@smartavionics Ah ok, turning off costing made the gaps go away.
I don't understand why though, that nozzle still needs to go over that area during the cost to print it.
Or maybe this representation of the gcode isn't accurate to what happens during the print?

**Comment by fieldOfView** [comment]
When coasting is enabled, the nozzle still moves over the same path, but it stops extruding so pressure in the hotend gradually decreases. Material is still being pushed/oozed out by residual pressure, but the layer view does not show that ooze.

**Comment by smartavionics** [comment]
There's a checkbox to enable display of travel moves, if you enable that you can see the travel move that occurs during the coast. So, in fact, the layer view is quite good at showing where extrusion is being commanded and where it isn't. Of course, what the layer view doesn't accurately portray is what actually comes out of the nozzle. You have to imagine that bit.

**Comment by Toxicable** [comment]
Ah right! of cause, that makes sense.
Thanks for taking the time to explain it to me
