### ISSUE TITLE
Scratch interface for basic plugin development by novice

### ISSUE THREAD

**Issue by ErikDeBruijn** [Ultimaker/Cura#48]
As a novice developer I'd like to be able to develop a plugin via drag and drop. Blockly/scratch could be a good way to create this interface. I've developed a scratch interface before and there is a Blockly system that allows you to output in the python language. E.g. GCode processing could be a fairly simple procedural script, but Blockly will help you without having to know the syntax.

**Comment by BagelOrb** [comment]
Sounds like a fairly large project.

Perhaps this is out of scope?

**Comment by nallath** [comment]
Completely out of scope. We don't have the resources for this.
