### ISSUE TITLE
Top View not above bed center [Any version].

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#4806]
To begin with, Thank you for Cura 3.6. so far looking good.

**Application Version**
3.6 or any other recent version

**Platform**
Win10/64

**Printer**
CFFFP, Delta & Cartesian

**Steps to Reproduce**
click on top-view

**Actual Results**
Camera never directly above center of bed which makes it a bit tricky to place multiple objects close to bed edge.

**Expected results**
Not sure.. i always expect to see the camera diretly above center of bed, preferbly in orthographic view.

**Additional Information**
Just wondering what one should expect. i think i prefer Top orthographic view.

![ice_screenshot_20181115-151916](https://user-images.githubusercontent.com/30949968/48555989-4b1dc180-e8eb-11e8-9666-782a5f42db5f.png)
![ice_screenshot_20181115-152139](https://user-images.githubusercontent.com/30949968/48555990-4b1dc180-e8eb-11e8-8150-13d52cdefbcb.png)
![ice_screenshot_20181115-152023](https://user-images.githubusercontent.com/30949968/48555991-4b1dc180-e8eb-11e8-8859-5e7a89050c50.png)
![ice_screenshot_20181115-152110](https://user-images.githubusercontent.com/30949968/48555992-4b1dc180-e8eb-11e8-881c-11e03ce12586.png)

**Comment by Ghostkeeper** [comment]
Fixed in version 4.2.

**Comment by Ghostkeeper** [comment]
You can't move the camera 100% to the top view because of the gimbal lock. Clicking on the button now sets it to the exact top view, but if you move the camera it'll reset to a 0.1 radian angle from the top.
