### ISSUE TITLE
Spacing 3+ items on buildplatform

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#481]
Version: Master, commit 20fc97
Platform: Ubuntu
Qt version: 5.4.1
PyQt version: 5.4.1

Steps to reproduce:
- Download [this](http://dulek.net/work/cube111.stl) model, or make your own. This is a cube of 10 by 10 by 10 millimetres.
- Load it into Cura 3 times. I did this by dragging the file from the folder onto the Cura window.

Expected results:
- Each model shows up onto the build platform, next to each other.

Observed results:
- The first model shows up properly in the centre of the platform.
- The second model shows up properly next to the first.
- The third model doesn't seem to show up, but actually it is placed exactly on top of the second model. The shadow below the second model darkens.

**Comment by BagelOrb** [comment]
fixed by now
