### ISSUE TITLE
The machine settings window is too short at the start and need to be stretched everytime.

### ISSUE THREAD

**Issue by a4jp-com** [Ultimaker/Cura#4813]
**Application Version** Version 3.6.0

**Platform** Windows 10 64 bit

**Printer** Dreammaker Overlord Pro

**Steps to Reproduce** Just open machine settings in the settings area

**Actual Results** popup is too small

**Expected results** The popup should be a bit longer so we don't have to stretch it everytime

**Additional Information**

**Comment by alekseisasin** [comment]
Hi @a4jp-com , On of the possible solutions is to store the machine settings pop up window size in cura.cfg. Another side of this request Cura team does not have much time for it.

**Comment by a4jp-com** [comment]
Can you tell me where the code is and I'll edit the code and create a push if that works?

**Comment by alekseisasin** [comment]
You might check how Cura stores/updates the "window_width" in file cura.cfg. The file is located here:
https://github.com/Ultimaker/Uranium/blob/master/UM/Qt/Bindings/MainWindow.py

**Comment by GregValiant** [comment]
@a4jp-com I'm cleaning house around here.  This has been open for several years.  Can I close this?
