### ISSUE TITLE
Ver 3.6.0 Crash on file open

### ISSUE THREAD

**Issue by ajtomany** [Ultimaker/Cura#4818]
**Application Version**
3.6.0

**Platform**
Windows 10 Profesional

**Printer**
Anet A8

**Steps to Reproduce**
File open

**Actual Results**
Crashes

**Expected results**
File open dialog

**Additional Information**
Happens any time I try to open a file from within the program.  I am, however, able to "Drag-and-Drop" files into the program and work normally.  This is an ongoing issue.  The same thing has been happening with all previous versions.

**Comment by diegopradogesto** [comment]
Could you please provide the entire configuration folder? You can zip the folder `cura` that you will find in `C:\Users\<user>\AppData\Roaming\` and attach it here.
