### ISSUE TITLE
Not conect Anet A8

### ISSUE THREAD

**Issue by plugato** [Ultimaker/Cura#4824]
**Application Version**

3.6.0
**Platform**

Windows 10 64
**Printer**

FFF
**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by plugato** [comment]
cura 3.2.1 working

**Comment by alekseisasin** [comment]
Information from your issue description does not provide data to understand your issue. Please fill the form correctly.

**Comment by alekseisasin** [comment]
Duplicated issue: https://github.com/Ultimaker/Cura/issues/4625
