### ISSUE TITLE
Material settings - Cannot read anything in darkmode

### ISSUE THREAD

**Issue by OliverWieland** [Ultimaker/Cura#4826]
**Application Version**

3.6.0

**Platform**

Ubuntu 18.10

**Printer**

Anet A8

**Steps to Reproduce**

- Change color theme to "Ultimater Dark"
- Open Material settings

**Actual Results**

The color font color is nearly the same than the background color

**Expected results**

The background color should be dark, as in all other dialogs

**Additional Information**

![screenshot_20181118_133915](https://user-images.githubusercontent.com/837634/48672536-5a914a80-eb37-11e8-9d9e-8db3b672df1b.png)

**Comment by alekseisasin** [comment]
It is very strange. I checked on Win10 and Ubuntu 18.10, and I have proper dark theme style in Materials settings.
I do not know what to suggest to do. I can say it works well on my computer.

**Comment by diegopradogesto** [comment]
This may happen, because this dialog uses the system palette instead of our internal dark theme. This is an example how it looks like in my Windows laptop:
![image](https://user-images.githubusercontent.com/15830521/48760656-dbbb1f80-eca6-11e8-9759-54a1fd9068ad.png)

That being said, if system palette indicates to use black background and we use black text (or the other way around), this will happen.

**Comment by diegopradogesto** [comment]
Developers, look at internal ticket CURA-5955

**Comment by yodor** [comment]
I was able to partially mitigate this using environment variable QT_QUICK_CONTROLS_STYLE=Desktop
After using this variable my menus and other elements are rendered mostly correctly but still the materials List/View is using incorrect palette.
![screenshot_20190109_153919](https://user-images.githubusercontent.com/2721164/50902864-d10a4480-1424-11e9-90de-c4938f609156.png)

**Comment by Ghostkeeper** [comment]
Yes, the materials list there was custom made without the palette since the system-styled elements were not powerful enough for what we needed it to do.

**Comment by bliser3d** [comment]
Thanks **yodor** for the prompt.
Used the command "QT_QUICK_CONTROLS_STYLE=Desktop /home/User/Cura/AppRun".
It helped me.

**Comment by LightTemplar** [comment]
Same here. Using the last AppImage in KDE Neon, dark theme. 
![image](https://user-images.githubusercontent.com/453783/71449736-9b548d80-2753-11ea-85f9-68652b5cfbb0.png)
And with "QT_QUICK_CONTROLS_STYLE=Desktop" it looks not much better, even main menu have become unreadable: 
![image](https://user-images.githubusercontent.com/453783/71449747-e4a4dd00-2753-11ea-9240-d7dd763115c3.png)

**Comment by Ghostkeeper** [comment]
We have some duplicates going on here. Please continue the conversation here: https://github.com/Ultimaker/Cura/issues/5490
