### ISSUE TITLE
Increase size of the settings area

### ISSUE THREAD

**Issue by dmitrygorbenko** [Ultimaker/Cura#4828]
Hi,

the settings area is too small compared to the other sections of the right part of the panel.
Check the image below and you'll understand what do I mean:

![screenshot_20181118_195602](https://user-images.githubusercontent.com/1971759/48676272-0c973980-eb6d-11e8-9d60-3b94605104cb.png)

Can you make it bigger ?

Thanks,
Dima

**Comment by fieldOfView** [comment]
There's the so aptly named "Prepare Stage Compactor" plugin that does just that. Thing is, the version for Cura 3.6 needs testing. If you are interested in a version of this plugin for Cura 3.6, please help test this prerelease:

http://files.fieldofview.com/cura/PrepareStageCompactor-v5-2018-10-29T14_11_04Z.curapackage

Just drop that file into a running Cura window and restart Cura.

**Comment by dmitrygorbenko** [comment]
YEAH !! Much better ))
Thank you !

Would be great to have this plugin somewhere around for those who want to enable it thr the Cura Settings, I think.

Thanks

**Comment by nallath** [comment]
The UI will get a redesign in the next release.
