### ISSUE TITLE
Save gcode button unclickable

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#483]
There is an area at the right bottom corner of the Save Gcode (to removable drive) button, where it doesn't respond. It doesn't even highlight.

Version: master
Platform: Linux-3.19.0-28-generic-x86_64-with-Ubuntu-15.04-vivid
Qt: 5.4.1
PyQt: 5.4.1

**Comment by nallath** [comment]
Does this also happen with the 15.10 version?

**Comment by BagelOrb** [comment]
yes
