### ISSUE TITLE
3.6.0

### ISSUE THREAD

**Issue by danstancil** [Ultimaker/Cura#4831]
**Application Version**
3.6.0

**Platform**
MacOS High Sierra

**Printer**
printrbot simple metal

**Steps to Reproduce**
Attempt to print any file

**Actual Results**
The software indicates the printer is connected, but the printer does not respond to any command, either printing, heating, or position jogs.

**Expected results**
Printer should properly respond to commands

**Additional Information**
When I revert to 3.5.1, everything works ok again.

**Comment by nallath** [comment]
Could you please share your logs?

**Comment by ksoviero** [comment]
@nallath I have the same problem on Linux Mint 18.3 (Ubuntu 16.04), and I also have a Printrbot Simple Metal. That's probably not a coincidence. 

I've attached my Cura log as requested. The log contains me starting Cura, loading an object, and attempting to print to USB. Upon doing so the printer does nothing and the monitoring page is "empty". I'll also attach a screenshot of what I mean.

Oh, and also, I loaded up the version 3.5.1 and the printer still works there, so it's a software bug in 3.6.

Thanks

![image](https://user-images.githubusercontent.com/1642394/48976360-a9fddc00-f04b-11e8-87c5-d3c443388e55.png)

[cura.log.gz](https://github.com/Ultimaker/Cura/files/2612887/cura.log.gz)

**Comment by danstancil** [comment]
I apologize for the delay; I believe I have attached the appropriate log.

Thanks,
Dan

**Comment by nallath** [comment]
We don't have a printerbot here, so it's really not something we can test for. All I can see from the logs is that it does seem to be able to detect & connect to the printer.

**Comment by danstancil** [comment]
Thanks for checking. There is a simple solution for me: keep using the
previous version of Cura!
Note that a subsequent post from Kevin Soviero indicated the same problem
with Linux and a Printrbot Simple Metal.

**Comment by InnovationSystemsAU** [comment]
Geday,

I have the same issue here with a printrbot PLUS.

Logs attached.

Hopefully someone can find the cause as I'd love to use the new features.

[cura.log](https://github.com/Ultimaker/Cura/files/2623065/cura.log)
