### ISSUE TITLE
3.6.0 Printing Bottom When None Exists In Model

### ISSUE THREAD

**Issue by brandoncristwright** [Ultimaker/Cura#4845]
**Application Version**
Cura 3.6.0

**Platform**
Windows 10

**Printer**
Prussa I3

**Steps to Reproduce**
Load Model, Slice, Print

**Actual Results**
The bottom of the model is supposed to be open but when it prints, it prints a closed bottom.

**Expected results**

**Additional Information**

![image](https://user-images.githubusercontent.com/45217810/48811857-3aa78580-ecf5-11e8-92b2-8eb91683e849.png)

**Comment by smartavionics** [comment]
Please attach either the zipped project file or the model to this issue, thanks.

**Comment by diegopradogesto** [comment]
I'm guessing that the problem is with the mesh itself. If you share the STL we can take a look. You can also check in the X-Ray view if the model has open parts, or use the MeshTools plugins to see if the model is correct.

**Comment by Sheraphin** [comment]
I have the same issue. Cura 3.6 is making a bottom where there should be none.

**Comment by smartavionics** [comment]
Please attach either the zipped project file or the model to this issue, thanks.

**Comment by smartavionics** [comment]
I don't get a layer at the bottom but it does put a weird skin layer in. Model doesn't appear to have any faults so I can't imagine what the problem is here.

![screenshot_2018-12-16_20-10-42](https://user-images.githubusercontent.com/585618/50058336-b2d75e80-016e-11e9-814a-a9aac1a57521.png)
