### ISSUE TITLE
[3.6.0] zig zag iron does not cover the whole surface

### ISSUE THREAD

**Issue by cabravara** [Ultimaker/Cura#4850]
**Application Version**
3.6.0

**Platform**
windows 10

**Printer**
creality cr10

**Steps to Reproduce**
set ironing on, ironing pattern to zig zag, .

**Actual Results**
narrow elements in the print do not get ironing on the whole surface

**Expected results**
all the surface should be ironed

[CCR10_voronoi_plano_2mm_1.zip](https://github.com/Ultimaker/Cura/files/2605008/CCR10_voronoi_plano_2mm_1.zip)

**Comment by alekseisasin** [comment]
Thank you. This issue is known.
Duplicate:  https://github.com/Ultimaker/Cura/issues/4524
