### ISSUE TITLE
[3.5.1/3.6.0] Missing supports on multiplied models

### ISSUE THREAD

**Issue by sheastreet** [Ultimaker/Cura#4852]
**Application Version**
3.5.1 / 3.6.0

**Platform**
Windows 10

**Printer**
CR-10 Mini

**Steps to Reproduce**
Multiply model with supports on

**Actual Results**
Different instances of the model has supports fully or partially missing on overhangs that some instances have and are fine.

**Expected results**
Supports to be there for all overhangs on all instance of the part and to possibly be the same supports

**Additional Information**
Screenshot from 3.5.1 for the supports only showing the different issues
![support_issues](https://user-images.githubusercontent.com/11021662/48876421-a3f5ca00-edc3-11e8-93f6-de3c446f1483.PNG)
3.5.1 project file
[CCR10_bx_valves_x2_support_issues.zip](https://github.com/Ultimaker/Cura/files/2606301/CCR10_bx_valves_x2_support_issues.zip)

**Comment by rburema** [comment]
Hi @sheastreet, I can confirm that this happens in current master as well. It even happens if I remove all models but one (that is affected), so it doesn't seem that 'multiply' is the culprit. I'll discuss this with the other devs. cheers, Remco.

**Comment by rburema** [comment]
A quick workaround is to set the 'Support Pattern' to 'Triangles', hope that works for you until this is fixed. (This also gives us some insight into where the bug might be located.)

[ Devs: CURA-5974 ]

**Comment by LipuFei** [comment]
I can confirm this problem in Cura 4.1 and versions before that, but it doesn't reproduce in Cura 4.2.1 and the current master branch.

With Cura 4.2.1, I opened the project file, and quality will be set to "Standard Quality 0.2 mm". I tried "Standard Quality 0.2 mm" and "Low Quality 0.28mm" with all the user changes kept. This problem doesn't show up in either case.

@sheastreet Could you try Cura 4.2.1?
