### ISSUE TITLE
Zits on curved walls 

### ISSUE THREAD

**Issue by rlesac** [Ultimaker/Cura#4860]
I have an issue with printing curved walls.
It manifests as zits on walls. 

The zits are always in the same position and most settings I tried have no effect on them.
Using other slicers (Slic3r, Simplfy3D) produces smooth walls.

The results are entirely reproducible between changing filament, nozzles, PTFE tube.

An extreme example:
![cura-vs-s3d](https://user-images.githubusercontent.com/10945003/48914149-e29a8b80-ee7a-11e8-93ab-ddb821f1994c.jpg)

Simple test STL:
https://www.thingiverse.com/thing:3229413

Simplify3D on top, Cura middle and bottom.  Setting z seam to user defined got rid of some zits in the sides of the oval, but others still persist.

24. Simplfy3D
27. z seam set to user defined
12. z seam set to shortest
![20181121_231952](https://user-images.githubusercontent.com/10945003/48914542-0a3e2380-ee7c-11e8-886e-8649e2c555d2.jpg)

![20181121_232026](https://user-images.githubusercontent.com/10945003/48914379-93a12600-ee7b-11e8-8b41-34e01c135ec8.jpg)

Settings changed, from top to bottom:
18. combing off
16. reset to draft profile, extra prime amount to 0.4 (to counteract under extrusion after long travel, has no impact on the zits)
13. z seam alignment to sharpest
12. z seam alignment to shortest﻿
![20181121_190137](https://user-images.githubusercontent.com/10945003/48914593-38bbfe80-ee7c-11e8-9183-88258d51f96a.jpg)

MF file
[CE3_Test retraction-extra prime amount v1.zip](https://github.com/Ultimaker/Cura/files/2608784/CE3_Test.retraction-extra.prime.amount.v1.zip)

**Application Version**
Cura 3.6

**Platform**
Win10 x64

**Printer**
Ender 3 stock.

**Steps to Reproduce**
Slice the file and print.

**Actual Results**
Zits and bumps on the walls

**Expected results**
Smooth walls

**Additional Information**

**Comment by rlesac** [comment]
They even show up when printing the oval ring without the pins.
Always in the same place.
![20181122_193042](https://user-images.githubusercontent.com/10945003/48918820-47f87780-ee8f-11e8-83ce-4791a5a2cdf4.jpg)
![20181122_192955](https://user-images.githubusercontent.com/10945003/48918821-47f87780-ee8f-11e8-9c4e-d832f594dfb0.jpg)

**Comment by rlesac** [comment]
I also found new artifacts, vertical lines. Looking at the printer it seems to slow down in those places.
S3D also printed 40% faster.

S3d left and top. Cura right an bottom. Uh seems my photos got rotated upside down. Anyway, Cura is the one with all the zits.
![20181125_164409](https://user-images.githubusercontent.com/10945003/48981259-72d30d80-f0d3-11e8-9745-92cc5248e327.jpg)
![20181125_164300](https://user-images.githubusercontent.com/10945003/48981260-72d30d80-f0d3-11e8-9fac-958091060a6d.jpg)
![20181125_164127](https://user-images.githubusercontent.com/10945003/48981261-72d30d80-f0d3-11e8-80c3-5b6ed8a0ee68.jpg)

Vertical lines:
![20181125_165312](https://user-images.githubusercontent.com/10945003/48981264-7c5c7580-f0d3-11e8-87ad-d7f186f0b233.jpg)
![20181125_165302](https://user-images.githubusercontent.com/10945003/48981265-7c5c7580-f0d3-11e8-9f0d-a40795366d66.jpg)

**Comment by Liger0** [comment]
Apart of the parts which need coasting and extra restart, I have the behaviour you have in your layers image on the right side too, that is very annoying.

**Comment by Appesteijn** [comment]
Cura 3.6.0 & S5:

![2018-11-26 11 54 43](https://user-images.githubusercontent.com/353164/49010034-605be100-f172-11e8-93ef-df3c98d21074.jpg)

**Comment by rlesac** [comment]
> Cura 3.6.0, Default 0.10 profile & S5:
> 
> ![2018-11-26 11 54 43](https://user-images.githubusercontent.com/353164/49010034-605be100-f172-11e8-93ef-df3c98d21074.jpg)
So much brim :)  

I don't see any zits on your print.
Different layer heights produced different results with 0.2 being the worst and is my most often used layer height.

Do you have any ideas what could be causing such different behavior compared to other slicers?

I'll try some more test prints tomorrow.

**Comment by Appesteijn** [comment]
So this is Cura 3.6 with 0.2 layerheight on a S5
![2018-11-27 15 53 28](https://user-images.githubusercontent.com/353164/49089898-e3596600-f25c-11e8-9a68-cdc11924b5ec.jpg)

**Comment by rlesac** [comment]
> So this is Cura 3.6 with 0.2 layerheight on a S5
> ![2018-11-27 15 53 28](https://user-images.githubusercontent.com/353164/49089898-e3596600-f25c-11e8-9a68-cdc11924b5ec.jpg)

This one seems to have the aforementioned zits on the walls, but it's hard to tell.
I have since switched from Marlin to Klipper firmware, and can't reproduce them with this test, I am getting different kind of artifacts, namely vertical lines.

But in other prints, more complex ones, they show up, as shown in the Star Trek cookie cutter.

[cc-star-trek-emblem-captain-70mm.zip](https://github.com/Ultimaker/Cura/files/2620730/cc-star-trek-emblem-captain-70mm.zip)

Only in Cura. Both Slic3r and Simplify3D are free of such defects.

I'm in the middle of a long print, so can¨do test at the moment.

**Comment by Bobertso** [comment]
![vertex zits](https://user-images.githubusercontent.com/45434643/49172803-d6895080-f2f6-11e8-9c48-c57859b8d8f0.jpg)
I have the same issue, found the cause by printing a lower resolution stl of my object. The zits are the model's vertexes, Cura's doing something weird at a vertex to make them. (low resolution on left, standard on right )

Solved by exporting model at extremely high resolution.

**Comment by Liger0** [comment]
I even noticed weird behaviorus that show the inprecision of the skirt. Maybe this is related.

![vertex](https://user-images.githubusercontent.com/20385116/50295918-7f037e00-0479-11e9-977d-e3a71087386b.png)

**Comment by cshunt** [comment]
I think the zits are start/stops on layer change. I ran a couple test and if you set z seam to aligned I had them show up all in one row. I tried adjusting retract extra prime amount without success, this had helped in 3.4. Retract at layer change did not help. I thought it might be overlap at layer start/stop, coasting changed the shape of the zit.

Settings i have tried to adjust
Retract extra prime amount - worked in previous versions
retract on layer change - no change
z-seam location - this lined the zits up.
coasting

**Comment by tablatronix** [comment]
What was the outcome of this, anyone resolve this, I seem to have this on certain layer heights and z seam settings

**Comment by alfrix** [comment]
i have come across this yesterday printing a cylinder, i solved it by disabling "Compensate wall overlaps"

**Comment by tablatronix** [comment]
Ill try that, I am printing lots of cylinders

**Comment by nallath** [comment]
This is probably a combination of compensate wall overlaps and the resolution settings. A much more in depth writeup can be found on https://github.com/Ultimaker/Cura/issues/8321

**Comment by tablatronix** [comment]
Thanks, related ? #6676
