### ISSUE TITLE
[3.6.0] Anycubic i3 mega doesnt shows material selection tab 

### ISSUE THREAD

**Issue by dmolpas** [Ultimaker/Cura#4867]
**Application Version**
Cura 3.6.0

**Platform**
win 10 64

**Printer**
Anycubic i3 mega

**Steps to Reproduce**
Just select the printer from the menu 

**Actual Results**
NO Material tab appears under the printer name . If you want to set the material proper temperatures you have to go by settings , profile , manage profile , material. 

**Expected results**
The Menu tab MATERIAL should appear under the printer name above print setup in the right part of the screen just as in any other printer 

**Additional Information**
Anycubic i3 mega
![menu1](https://user-images.githubusercontent.com/45294590/48954744-2066e500-ef4b-11e8-9ac7-6377edc94bee.jpg)
Anycubic 4 max (and many others)
![menu2](https://user-images.githubusercontent.com/45294590/48954837-6328bd00-ef4b-11e8-9bfc-0ca2467b917e.jpg)

**Comment by edallas** [comment]
I can second that - on macOS Mojave with Cura 3.6.0 and Any Cubic i3 mega

**Comment by shums** [comment]
It seems that Cura 3.6 supplied with wrong printer settings.
For WIN it can be overridden C:\Program Files\Ultimaker Cura 3.6\resources\definitions\anycubic_i3_mega.def.json 
(need administrator rights).

Change setting "has_materials" from **false** to **true**

**Comment by edallas** [comment]
followed shums' lead - looked in application support but eventually found it in the application... /Applications/Ultimaker Cura/Contents/Resources/resources/definitions -> anycubic_i3_mega.def.json (you have to show package contents on the Cura.app to get there) 
Modified as suggested and reloaded Cura - now works on macOS Mojave!

**Comment by dmolpas** [comment]
> It seems that Cura 3.6 supplied with wrong printer settings.
> For WIN it can be overridden C:\Program Files\Ultimaker Cura 3.6\resources\definitions\anycubic_i3_mega.def.json
> (need administrator rights).
> 
> Change setting "has_materials" from **false** to **true**

Thank you so much , works perfectly for me !
