### ISSUE TITLE
Scroll of drop down menu

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#487]
With the scroll of drop down menu you change settings while skimming through the settings. Single use.

I'd like to see an option - I guess in Preferences > general - which disables the functionality that when your pointer is over a multiple choice setting and you scroll, you change the setting.

Quite often I am just scrolling through all settings (currently I have ***all*** settings visible) and suddenly I'm changing the platform adhesion type, it starts to reslice and the layer view is cleared.
This bugs me a lot!!!

**Comment by awhiemstra** [comment]
I actually fixed this just now for the 15.10 branch. That simply disables the scrolling to change setting.
