### ISSUE TITLE
[3.6.0] "Cura can't start" on upgrade from 3.5 to 3.6

### ISSUE THREAD

**Issue by mpsdskd** [Ultimaker/Cura#4870]
**Application Version**
3.6.0

**Platform**
Kubuntu 18.10

**Printer**
Custom FDM

**Steps to Reproduce**
Start Program

**Actual Results**
Error Window, Program does not start

**Additional Information**
I tried the "backup and restart" option in the error window - I then can open Cura 3.6 but cannot restore my config using the backup addon.

[cura.log](https://github.com/Ultimaker/Cura/files/2611517/cura.log)
[3.6_20181123_194345.zip](https://github.com/Ultimaker/Cura/files/2611518/3.6_20181123_194345.zip)

"Error Traceback" in Error Window
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/build/3.6/build/inst/bin/cura", line 138, in <module>
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 686, in run
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 287, in run
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Application.py", line 207, in run
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 426, in startSplashWindowPhase
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 185, in startSplashWindowPhase
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 137, in upgrade
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 341, in _upgradeFile
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 398, in updateFilesData
> TypeError: 'NoneType' object is not iterable

"Error Log" in Error window

> Thread 0x00007f19137fe700 (most recent call first):
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 160 in _storeStderrToLogThread
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 862 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f1913fff700 (most recent call first):
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Backend/Backend.py", line 152 in _storeOutputToLogThread
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 862 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f19299ea700 (most recent call first):
>   File "/tmp/.mount_fsLn1y/usr/bin/plugins/plugins/USBPrinting/USBPrinterOutputDeviceManager.py", line 78 in _updateThread
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 862 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f192a7fc700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 297 in wait
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/zeroconf.py", line 1153 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f192affd700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 297 in wait
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/zeroconf.py", line 1569 in wait
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/zeroconf.py", line 1017 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f192b7fe700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/site-packages/zeroconf.py", line 946 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f192bfff700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 297 in wait
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 549 in wait
>   File "/tmp/.mount_fsLn1y/usr/bin/plugins/plugins/UM3NetworkPrinting/src/UM3OutputDevicePlugin.py", line 299 in _handleOnServiceChangedRequests
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 862 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f1946bab700 (most recent call first):
>   File "/tmp/.mount_fsLn1y/usr/bin/plugins/plugins/RemovableDriveOutputDevice/RemovableDrivePlugin.py", line 61 in _updateThread
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 862 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f19477fe700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f1947fff700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f194c940700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Thread 0x00007f194d141700 (most recent call first):
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 293 in wait
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 424 in acquire
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 86 in _nextJob
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/JobQueue.py", line 112 in run
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 914 in _bootstrap_inner
>   File "/build/env/3.6/inst/lib/python3.5/threading.py", line 882 in _bootstrap
> 
> Current thread 0x00007f196b068740 (most recent call first):
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 310 in _logInfoWidget
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 160 in _createDialog
>   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 81 in __init__
>   File "/build/3.6/build/inst/bin/cura", line 116 in exceptHook

Error Message in log file

> 2018-11-23 19:52:18,820 - INFO - [MainThread] UM.VersionUpgradeManager._getUpgradeTasks [285]: Create upgrade task for configuration file [./custom_extruder_1_0.2_-_abs.inst.cfg] with type [quality] and source version [3000004]
> 2018-11-23 19:52:20,728 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [65]: An uncaught error has occurred!
> 2018-11-23 19:52:20,740 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: Traceback (most recent call last):
> 2018-11-23 19:52:20,752 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
> 2018-11-23 19:52:20,763 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
> 2018-11-23 19:52:20,774 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
> 2018-11-23 19:52:20,784 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
> 2018-11-23 19:52:20,796 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
> 2018-11-23 19:52:20,807 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
> 2018-11-23 19:52:20,818 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
> 2018-11-23 19:52:20,828 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
> 2018-11-23 19:52:20,839 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
> 2018-11-23 19:52:20,849 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/env/3.6/inst/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
> 2018-11-23 19:52:20,860 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
> 2018-11-23 19:52:20,872 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
> 2018-11-23 19:52:20,881 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
> 2018-11-23 19:52:20,891 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
> 2018-11-23 19:52:20,902 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/bin/cura", line 138, in <module>
> 2018-11-23 19:52:20,912 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 686, in run
> 2018-11-23 19:52:20,929 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 287, in run
> 2018-11-23 19:52:20,938 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Application.py", line 207, in run
> 2018-11-23 19:52:20,949 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CuraApplication.py", line 426, in startSplashWindowPhase
> 2018-11-23 19:52:20,960 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/Qt/QtApplication.py", line 185, in startSplashWindowPhase
> 2018-11-23 19:52:20,970 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 137, in upgrade
> 2018-11-23 19:52:20,981 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 341, in _upgradeFile
> 2018-11-23 19:52:20,993 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/UM/VersionUpgradeManager.py", line 398, in updateFilesData
> 2018-11-23 19:52:21,004 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [68]: TypeError: 'NoneType' object is not iterable
> 2018-11-23 19:53:19,151 - INFO - [MainThread] cura.CrashHandler._sendCrashReport [364]: Sending crash report info to [https://stats.ultimaker.com/api/cura]...
> 2018-11-23 19:53:19,275 - ERROR - [MainThread] UM.Logger.logException [84]: Exception: An exception occurred while trying to send crash report
> 2018-11-23 19:53:19,284 - ERROR - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
> 2018-11-23 19:53:19,290 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 1254, in do_open
> 2018-11-23 19:53:19,297 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 1106, in request
> 2018-11-23 19:53:19,303 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 1151, in _send_request
> 2018-11-23 19:53:19,310 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 1102, in endheaders
> 2018-11-23 19:53:19,317 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 934, in _send_output
> 2018-11-23 19:53:19,323 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 877, in send
> 2018-11-23 19:53:19,330 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/http/client.py", line 1260, in connect
> 2018-11-23 19:53:19,337 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/ssl.py", line 377, in wrap_socket
> 2018-11-23 19:53:19,343 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/ssl.py", line 752, in __init__
> 2018-11-23 19:53:19,350 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/ssl.py", line 988, in do_handshake
> 2018-11-23 19:53:19,357 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/ssl.py", line 633, in do_handshake
> 2018-11-23 19:53:19,363 - ERROR - [MainThread] UM.Logger.logException [88]: ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
> 2018-11-23 19:53:19,370 - ERROR - [MainThread] UM.Logger.logException [88]: 
> 2018-11-23 19:53:19,376 - ERROR - [MainThread] UM.Logger.logException [88]: During handling of the above exception, another exception occurred:
> 2018-11-23 19:53:19,383 - ERROR - [MainThread] UM.Logger.logException [88]: 
> 2018-11-23 19:53:19,390 - ERROR - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
> 2018-11-23 19:53:19,396 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/3.6/build/inst/lib/python3.5/site-packages/cura/CrashHandler.py", line 369, in _sendCrashReport
> 2018-11-23 19:53:19,403 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 163, in urlopen
> 2018-11-23 19:53:19,410 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 466, in open
> 2018-11-23 19:53:19,416 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 484, in _open
> 2018-11-23 19:53:19,423 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 444, in _call_chain
> 2018-11-23 19:53:19,429 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 1297, in https_open
> 2018-11-23 19:53:19,436 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.6/inst/lib/python3.5/urllib/request.py", line 1256, in do_open
> 2018-11-23 19:53:19,443 - ERROR - [MainThread] UM.Logger.logException [88]: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

**Comment by Appesteijn** [comment]
Do have have a zip file of you settings folder? We are looking to reproduce this error for some time now but couldn't.

**Comment by mpsdskd** [comment]
It is attached in the link below the link to the log in the original post.
[](https://github.com/Ultimaker/Cura/files/2611518/3.6_20181123_194345.zip)

**Comment by Ghostkeeper** [comment]
Fixed in the next release here: https://github.com/Ultimaker/Cura/commit/ae2b3124721c9c74730073d178c0ac1927819b1c

Also fixed an underlying issue here that would've prevented the buggy code from being called in the first place: https://github.com/Ultimaker/Uranium/commit/57a16e55c93ce0de5f392209144ca46aeba10862

Thanks for the report! We'd seen this bug before via the crash window's report button but your settings folder was helpful to reproduce the bug ourselves and then trace it down to verify that we had actually fixed it.

**Comment by mpsdskd** [comment]
I'm glad I could help.
Thank you very much for (hopefully) solving the problem :+1:
