### ISSUE TITLE
Change number of walls/perimeters for first 4 layers

### ISSUE THREAD

**Issue by debil1** [Ultimaker/Cura#4873]
I tried all scripts but can't found a solution to change from layer 0 to 4 -> 2 walls/perimeter and then further on only one.

**Comment by nallath** [comment]
You could try and do this with infill meshes. Put an infill mesh on the first few layers.

**Comment by diegopradogesto** [comment]
Yes, so you can place another mesh at the bottom and use the per object settings (e.g. "Modify settings for overlap with other models") and then select the settings you want to change, such as `Wall Line Count` and `Infill Density`.

Take a look at the picture:

![image](https://user-images.githubusercontent.com/15830521/49143752-fd965100-f2fb-11e8-97e2-96bc6b5a1c6a.png)

**Comment by BagelOrb** [comment]
With zero percent infill that can be a problem. Just put infilll to 0.1% and set the infill offset X and y to large values so that there is factually no infill in your part.
