### ISSUE TITLE
Cura3.6, Heat up default, nozzle got to wait bed to heat up, cost more time.

### ISSUE THREAD

**Issue by Shlom0** [Ultimaker/Cura#4875]
Can Nozzle and bed heat up at the same time?

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by fieldOfView** [comment]
Typically the nozzle heats up much quicker than the bed. This means that - while waiting for the bed to heat up - the nozzle will start oozing material and/or degrading material that is stagnant in the hotzone of the nozzle. Depending on the material, heat can creep up the hotzone to the cold zone of your extruder, possibly causing clogs.

Having said that, if you add your own heatup sequence to your start gcode, you can do whatever you think works best for your printer.
