### ISSUE TITLE
Anycubic i3 Mega Quality Profiles not loaded Cura 3.6.0

### ISSUE THREAD

**Issue by hanturk** [Ultimaker/Cura#4876]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by hanturk** [comment]
Because entry "global_quality = True" is missing at the three Quality Profiles under "C:\Program Files\Ultimaker Cura 3.6\resources\quality\anycubic_i3_mega" they are not loaded to Cura 3.6.0. After adding this value to the profiles there are loaded like in Cura 3.4.1. I'am not shure if this correction is O.K. the author of the profiles @thetobby should check this issue.

**Comment by thetobby** [comment]
Feel free to take over or submit improvements. I'm not activly maintaining the profiles so might be bugs with never versions.

**Comment by diegopradogesto** [comment]
I just did it. Thanks for reporting!

**Comment by thetobby** [comment]
Thank you @diegopradogesto

**Comment by hanturk** [comment]
Thank you all. Have a nice day.
