### ISSUE TITLE
Rotation Feature Request

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#488]
I miss the Rotate functionality from legacy Cura. It rotated based on the difference in angle from mouse press to mouse release using a center point. I could easily flip a part 180 degrees by dragging the mouse to the opposite side of the part after clicking.

Now it rotates based on how far you drag the mouse around the part.

**Comment by TMHogenhout** [comment]
+1 I liked that better as well. At the moment this is not our highest priority, but we will definitely keep it in mind.

**Comment by BagelOrb** [comment]
I think this is how it works now.
