### ISSUE TITLE
[3.6] OBJ fails to load, Invalid file while stl is loaded correctly

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4881]
**Application Version**
3.6.0

**Platform**
Windows 10 x64

**Printer**
Cr-10S

**Steps to Reproduce**
Load the models here.

**Actual Results**
Even being the same models, the obj literally fails to load, while the stl is loaded succesfully. It is to be noted that the model has big dimensions and goes over the print volume, so that may be part of the culprit.

**Expected results**
The OBJ should be loaded correctly.

**Additional Information**

[OBJ and STL.zip](https://github.com/Ultimaker/Cura/files/2613645/OBJ.and.STL.zip)

**Comment by nallath** [comment]
That's because the OBJ is invalid. Some of the indices are "nan" (Not a number). So it might be the same model, but the program where you got the model from has a bug.
