### ISSUE TITLE
Items Being Unexpectedly Cloned

### ISSUE THREAD

**Issue by ArtairGeal** [Ultimaker/Cura#4896]
**Application Version**

Cura 3.6.0 plus OctoPrint Connection plugin.

**Platform**

macOS Mojave 10.14.1

**Printer**

JGAURORA A5

**Steps to Reproduce**

1) Make sure the OctoPrint server isn't connected to the actual printer due to power cycling the printer, etc.
2) Slice and submit a job while printer is disconnected.
3) Cura will prompt to queue the job. Click the "X" to close this dialog and cancel.
4) Reconnect OctoPrint with the printer.
5) Try to submit the job again.
6) The job will upload and start printing, but...

**Actual Results**

...all items in the original print job will be doubled, with the duplicates arbitrarily rearranged on the build plate. Some items may overlap and create malformed items. (My JGAURORA was "making spaghetti" this morning by trying to print a copy of an item on top of the original item.)

**Expected results**

A single copy of all items, as originally placed, should be printed.

**Additional Information**

Printer also seems unaware of where all items are actually placed. Print head collided with a (substantial, dense) print when I aborted, but I was able to wrench the print free before any damage was done.

**Comment by fieldOfView** [comment]
This issue was fixed last week, see https://github.com/fieldOfView/OctoPrintPlugin/issues/94. Please check the Marketplace; there should be an updated OctoPrint Connection plugin (version 3.5.3, published last week).
