### ISSUE TITLE
Application form and mouse X,Y positioning is off

### ISSUE THREAD

**Issue by Jollym** [Ultimaker/Cura#4898]
**Application Version**
3.6 (Just downloaded & installed it 2018/11/27)

**Platform**
Windows 10 Enterprise 64 (Just installed it 2 days ago)

**Printer**
Ender 3

**Steps to Reproduce**
Constent

**Actual Results**
ALL forms / mouse positions are negitivly hight offset

**Expected results**
All forms and windows and mouse positions should start at 0 , 0

**Additional Information**

I have tried stopping and restarting the app, I have tried rescaling the desktop, I have tried rebooting, nothing fixes the issue

![2018-11-27 21_05_48-window](https://user-images.githubusercontent.com/1746414/49108873-87590680-f289-11e8-84c2-545e16d778d9.png)
![2018-11-27 21_06_14-window](https://user-images.githubusercontent.com/1746414/49108874-87590680-f289-11e8-9066-f0e6715aa592.png)
![2018-11-27 21_08_15-ultimaker cura](https://user-images.githubusercontent.com/1746414/49108875-87f19d00-f289-11e8-8471-51b74ec07eef.png)

**Comment by fieldOfView** [comment]
Looks like https://github.com/ultimaker/cura/issue/2068

In short: update your intel gpu driver.

**Comment by diegopradogesto** [comment]
@Jollym can you please confirm that updating the drivers fixes the issue? Thanks.

**Comment by Jollym** [comment]
![2018-11-28 20_31_03-courier indesirable - chris beezup com - outlook](https://user-images.githubusercontent.com/1746414/49177099-a8cef680-f34c-11e8-8ff3-3e77297d93d0.png)

Confirmed Fixed.

NOTE: Originally #2068 was returning a 404 error but now the link is working.

**Comment by fieldOfView** [comment]
Sorry, I made a typo in the url to #2068 when I initially posted my answer. I fixed it after the notification you received was sent.

**Comment by fieldOfView** [comment]
Please close the issue.
