### ISSUE TITLE
Extruder change over model

### ISSUE THREAD

**Issue by lokanaft** [Ultimaker/Cura#4901]
**Application Version**
3.6

**Platform**
**Printer**
Any

**Steps to Reproduce**
Use 2 extruder and prime tower

**Actual Results**
Extruder change over model, wait temperature and only then go to prime tower

**Expected results**
Extruder should go to prime tower and change and heat over prime tower, otherwise it flow filament over model in this time

**Comment by rburema** [comment]
Hi @lokanaft,
Does this happen for any model? If not, could you Save it to a 3mf file and attach it to this ticket?
cheers, Remco.

**Comment by lokanaft** [comment]
For any model.
In #4855 it's realy Cura not understand, where to go for change extruder, but with prime tower it's obviously

**Comment by amagr0** [comment]
https://github.com/Ultimaker/Cura/issues/3451

**Comment by Ghostkeeper** [comment]
> Printer
Any

This part of your description is wrong. It doesn't happen with any printer. UM3 is fine in this regard.

To move to a location where it's safe to change extruders, Cura needs to know where to move to. This is in your printer's definition. It would need to mention something like this:

    "machine_extruder_start_pos_abs": {"default_value": true},
    "machine_extruder_start_pos_x": {"default_value": 0},
    "machine_extruder_start_pos_y": {"default_value": 0},
    "machine_extruder_end_pos_x": {"default_value": 0},
    "machine_extruder_end_pos_y": {"default_value": 0},

I'm closing this as a duplicate of #3451 then.
