### ISSUE TITLE
Inqiury of Cura software (Add other printer profile to Cura)

### ISSUE THREAD

**Issue by Hyvision** [Ultimaker/Cura#4904]
Hello, my name is Byeon Ho cheol works in Cubicon.
We, Cubicon, are the manufacturer of 3D Printers. I would like to ask a question about adding printer preferences on “Cura”.
So, I created a “Cubicon” profile, but I can not commit to Cura Git due to permissions issues.
I have attached the profiles I created, so please check them out.

**Application Version**
Cura 3.5.1

**Platform**
Windows / OSX

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**
[Cubicon Home](http://www.3dcubicon.com/en/cubicon/): http://www.3dcubicon.com/en/cubicon/
[Cura for Cubicon.zip](https://github.com/Ultimaker/Cura/files/2627397/Cura.for.Cubicon.zip)

**Comment by rburema** [comment]
Hi @Hyvision,
Please make a ['Pull Request'](https://help.github.com/articles/creating-a-pull-request/) and we can have a look at it sometime in the future.
cheers, Remco.
