### ISSUE TITLE
Can't change Setting Visibility with Preferences Menu

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#4907]
**Application Version**

Cura 3.6 and master version

**Platform**

Windows 10 64bit

**Printer**

...

**Steps to Reproduce**

1. Select Preferences of menu bar
2. Select Setting tab
3. Select the one of presets(basic ~ expert)

**Actual Results**

setting visibility is not changed

**Expected results**

selection is ok

**Additional Information**

setting visibility can be changed with 3 bar selection icon of sidebar

...maybe there is some problem at qml/Preferences/SettingVigibilityPage.qml

>  settingVisibilityPresetsModel.items[i].id -> settingVisibilityPresetsModel.items[i].presetId

**Comment by nallath** [comment]
Yup. I've just fixed that in ad26962cb91a3d7e4e9deb32fddb63e5955bae16
