### ISSUE TITLE
Looking for advice from the experts

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#4908]
**Application Version**
3.6

**Platform**
Win10/64/SSD

**Printer**
CFFFP

**Steps to Reproduce**
Printing a BOWL

I am sorry if this is not the place for such a question - feel free to close this issue, but i am looking to hear what the experts have to say. i need to print this bowl but with the settings i like print will take 19 hours. i have tuned my settings and print time is down to 12 hours. i don't mind long prints (other than the need to stay close to the printer) but i was wondering how should one set Cura up for a bowl where the first layers are almost horizontal and so i believe that's what takes most of the printing time - these roofs printed for supporting next layers so i was wondering if you have better settings for such cases and if there is a way around this and maybe disable these roofs might lead to better/faster print.

Thank you.

![ice_screenshot_20181129-172925](https://user-images.githubusercontent.com/30949968/49233143-096a3c00-f3fe-11e8-8aa2-8c9e8ef1d798.png)
![ice_screenshot_20181129-172952](https://user-images.githubusercontent.com/30949968/49233145-0a02d280-f3fe-11e8-99af-2cc5878453ad.png)
![ice_screenshot_20181129-173055](https://user-images.githubusercontent.com/30949968/49233146-0a02d280-f3fe-11e8-8bdb-6ef7b478f471.png)
![ice_screenshot_20181129-173144](https://user-images.githubusercontent.com/30949968/49233147-0a02d280-f3fe-11e8-9adf-d0377f674ee1.png)

**Comment by rburema** [comment]
Hi @Thisismydigitalself,
Gyroid-infill is a new feature, and may take up a lot of time, because we've had to switch some of the optimizations off for it. Have you tried an estiamte with other types of infill?

In general, the place for these kinds of questions is the [forum](https://community.ultimaker.com/forum).
cheers,
Remco.
