### ISSUE TITLE
Cura-15.6.3 fail to run with PyQt-5.5

### ISSUE THREAD

**Issue by cor-mt** [Ultimaker/Cura#492]
TypeError: invalid result from AvailableMachinesModel.roleNames(), a dict value has type 'str' but 'QByteArray' is expected
Aborted

Seem to be related to:
http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html
http://comments.gmane.org/gmane.comp.python.pyqt-pykde/28741

**Comment by awhiemstra** [comment]
This has already been resolved for the more recent beta version of Cura.
