### ISSUE TITLE
I can't get Cura 3.6 to print using my AdimLab Gantry. No matter what i do to the settings I can't get the layers to stick together but I get Cura 15.04 to work just fine with my printer.

### ISSUE THREAD

**Issue by JDHannon** [Ultimaker/Cura#4920]
**Application Version**Cura 3.6

**Platform**Windows 10

**Printer**AdimLab Gantry

**Steps to Reproduce** I don't know what to say here.

**Actual Results** Print layers don't adhere

**Expected results**Good prints

**Additional Information**I get good results from Cura 15.04

**Comment by smartavionics** [comment]
Please save the Cura 3.6 project, zip up the file and attach to this issue so we can check your settings, model, etc. Thanks.

**Comment by smartavionics** [comment]
Cool, please close this issue. Thanks.
