### ISSUE TITLE
Cura 3.6 flashes on screen then disappears

### ISSUE THREAD

**Issue by freebird1963** [Ultimaker/Cura#4921]
**Application Version**

3.6.0
**Platform**

Win 7 x64
**Printer**

Generic
**Steps to Reproduce**

Go to programs
Click on cura
watch it open up
then watch it disappear
tried running as administrator. same results
**Actual Results**

nothing. no cura on the screen. nothing. blank screen.
**Expected results**

cura should be running on the screen
**Additional Information**

processes show curaengine.exe running at 4460K working memory
tried running as administrator, failed to load also. 
Ran when first installed but not since.

**Comment by nallath** [comment]
Could you share your log files?

**Comment by freebird1963** [comment]
Sorry I got annoyed with it and removed it from my system. I am going to download and install again to see if maybe something went wrong.If it continues on this new install I will send them.
Thanks

**Comment by thucar** [comment]
I'm having the same issue with both 3.5.1 and 3.6.0

[cura.log](https://github.com/Ultimaker/Cura/files/2660326/cura.log)

**Comment by Ghostkeeper** [comment]
I think this issue has been fixed in 4.7 due to some defensive coding we've implemented to not use the `extruders` dictionary any more but access the list of extruders by index.
