### ISSUE TITLE
[3.6] Mach3 flavor has no effect, generates G-Code with Marlin flavor

### ISSUE THREAD

**Issue by TheTiEr** [Ultimaker/Cura#4929]
**Application Version**
Cura 3.6

**Platform**
Win 10, 64-Bit

**Printer**
Custom FDM Printer with Mach3 Flavor

**Steps to Reproduce**
Add a new Printer / or update from Cura 3.5.1 with a printer with Mach3 Flavor

**Actual Results**
The generated G-Code has Marlin flavor.

**Expected results**
Generated G-Code with Mach3 flavor

**Additional Information**
I have tested the flavor Griffin as a test. This works with no problem. Only the Mach3 settings has this problem

[Mach3-flavor-test.3mf.zip](https://github.com/Ultimaker/Cura/files/2641126/Mach3-flavor-test.3mf.zip)
[CFFFP_Quadrat1.gcode.txt](https://github.com/Ultimaker/Cura/files/2641128/CFFFP_Quadrat1.gcode.txt)
![bildschirmfoto 2018-12-03 um 21 03 22](https://user-images.githubusercontent.com/40594118/49399377-68eb8300-f741-11e8-837c-a8dc9181f98f.png)

Edit:
The beginning of the generated G-Code
`;FLAVOR:Marlin
;TIME:88215
;Filament used: 17.0265m
;Layer height: 0.1
;Generated with Cura_SteamEngine 3.6.0
M104 S200
M105
M109 S200
M82 ;absolute extrusion mode
G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 A0
G1 F200 A3
G92 A0
G92 E0
G1 F1500 E-6.5
;LAYER_COUNT:2730
;LAYER:0
M107
G0 F3600 X157.274 Y144.922 Z0.3
;TYPE:SKIRT
G1 F1500 E0
G1 F1800 X157.817 Y144.349 E0.00495
G1 X158.416 Y143.834 E0.0099
G1 X159.064 Y143.383 E0.01485
G1 X159.754 Y142.999 E0.0198
G1 X160.48 Y142.687 E0.02476
G1 X161.233 Y142.45 E0.02971
G1 X162.007 Y142.291 E0.03466
G1 X162.792 Y142.21 E0.03961
G1 X163.194 Y142.2 E0.04213
G1 X164.003 Y142.2 E0.04721
G1 X164.792 Y142.24 E0.05216`

**Comment by smartavionics** [comment]
Bug fix PR submitted. Good luck!

**Comment by smartavionics** [comment]
BTW I will build a release with that fix now, should be available later tonight.

**Comment by smartavionics** [comment]
I have built a Cura release that should work for the Mach3, you can find it at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0.

**Comment by TimoErdmann** [comment]
Thank you for your efforts.
