### ISSUE TITLE
Software updates Fail

### ISSUE THREAD

**Issue by Bog97th** [Ultimaker/Cura#4930]
I am using the Cura that came with the machine but I am trying to get Cura v3.6.0. All versions of this program crash on start up after install on my machine and the "Update" for the original 15.04 fails also.
And recourse?

**Application Version**
Cura 15.04 
**Platform**
 Windows 8 
**Printer**
 ADIMLab 3D Printer Assembled 24V Prusa I3 

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by nallath** [comment]
There is no legacy version above 15.04. As for Cura 3.6.0 not working, we need logs before we can debug it.
