### ISSUE TITLE
[3.6] Imperfections in a model preview

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4938]
**Application Version**
3.6

**Platform**
Windows 10 x64

**Printer**
Cr-10s

**Steps to Reproduce**
Load the attached file

**Actual Results**
There is some weird imperfection

**Expected results**
The model should be linear.

**Additional Information**
[imperfecitons.zip](https://github.com/Ultimaker/Cura/files/2650490/imperfecitons.zip)
![imperfections](https://user-images.githubusercontent.com/20385116/49541967-856bf480-f8d4-11e8-882c-7f76adc8e4ae.png)

**Comment by Liger0** [comment]
So I actually used more fusion 360 and made various models, they all when printed have rough surfaces because of the same behavriour I had in that model. No matter what, I won't even have completely flat surfaces. All other slicers slice fine. This on latest cura 4.1

**Comment by nallath** [comment]
I've managed to remove these imperfections by lowering the "maximum resolution" setting to 0.1

**Comment by Ghostkeeper** [comment]
Those imperfections are caused by the wall overlap compensation. It probably kicks in because of the many line segments slightly overlapping each other.
