### ISSUE TITLE
Save/Print Dropdown wrongly positioned

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#494]
Cura 15.09.91
OS X 10.9.5

When Cura application window is touching the bottom of the screen, the dropdown options appear near the Cura titlebar. When Cura is maximized, I see the following...

![screen shot 2015-10-20 at 7 23 30 am](https://cloud.githubusercontent.com/assets/12257213/10612098/d5b7307a-76fb-11e5-8a06-316a17c13ece.png)

**Comment by awhiemstra** [comment]
This is a bug in Qt that has been fixed in Qt 5.5.1 . Once we update, this will be fixed. Currently the most major thing preventing upgrading is some issues with number formatting, next to testing.
