### ISSUE TITLE
"Collapse All" command does not work...

### ISSUE THREAD

**Issue by kenansatir** [Ultimaker/Cura#4940]
**Application Version**
3.6.0

**Platform**
Windows 10 Home

**Printer**
Anycubic i3 Mega

**Steps to Reproduce**
Try "Collapse All" command on settings...

**Actual Results**
Nothing collapses!

**Expected results**
Setting menus must be collapsed.

**Additional Information**
Nothing

**Comment by nallath** [comment]
Works in the latest version.
