### ISSUE TITLE
3.6.0 Print one at a time print head is twice the actual sice

### ISSUE THREAD

**Issue by maksdampf** [Ultimaker/Cura#4941]
**Application Version**
3.6.0

**Platform**
macOS

**Printer**
UM2

**Steps to Reproduce**
- Set to "Print one at a time" and load any stl, this is not tied to a specific stl.  
- Now check the gray print head size that is being displayed.
- To amplify the problem now try to place 2 stl-objects with 60mm Diameter in an axis along the width of the printbed. Cura will not be able to slice that.  y-axis of the printhead is also twice the size, but since this is only 1/3rd of the x-axis printhead size (width) it is less notable.
- Check machine settings for actual print head size.

**Actual Results**
- The Print head is displayed and being handled as if it was twice as big

 as its actual size and settings are. 
- In my case the grey area of the print head is shown as being even wider than the bed itself.
- Trying to place 4 stl-objects with 60mm Diameter, Cura 3.6.0 refuses to slice ("Unable to slice") due to the grey areas of the printhead overlapping with the objects.

**Expected results**
- In Cura 3.2.1 the printhead size was handled correctly and is roughly half as wide.
- Placement and slicing of 4x Cylinders with 60mm Diameter is no problem in Cura 3.2.1

**Additional Information**

Screenshot of Cura 3.6.0 with the mentioned options: <img width="1291" alt="bildschirmfoto 2018-12-06 um 09 14 30" src="https://user-images.githubusercontent.com/14014285/49570835-f690c380-f937-11e8-9c93-e51705c485cb.png">

Screenshot of expected behaviour as in Cura 3.2.1:
<img width="1199" alt="bildschirmfoto 2018-12-06 um 09 16 21" src="https://user-images.githubusercontent.com/14014285/49570830-f42e6980-f937-11e8-9444-57296c0e560b.png">

[one at a time bug.zip](https://github.com/Ultimaker/Cura/files/2652246/one.at.a.time.bug.zip)

**Comment by nallath** [comment]
This has been fixed in master, so it will be fixed in the next release.

**Comment by maksdampf** [comment]
thx for letting me know, will wait for the next release then. Strangely, i could not find the fixed Issue by search, so naming and description was probably quite exotic.
