### ISSUE TITLE
Wont change skit line count, software changes it but still prints 4 skit lines

### ISSUE THREAD

**Issue by supak111** [Ultimaker/Cura#4948]
Cura 3.6.0 on MacOS 12.14.1

Just noticed that on newest Cura 3.6.0 changing the number of skits lines does not work.  No matter what number I set for skit lines it keeps printing 4 skit lines.

**Comment by smartavionics** [comment]
Hello @supak111, please save the project file, zip it up and attach to this issue so I can take a look. Thanks.

**Comment by supak111** [comment]
My apologies, after some research and digging though settings I realize that this was because of "skit/brim minimum length" settings I had
