### ISSUE TITLE
OS X Fullscreen application

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#495]
Cura 15.09.91
OS X 10.9.5

Cura basically dies when put in fullscreen mode (ctrl-command-F). The application goes all white and doesn't seem to recover even after exiting fullscreen mode.

**Comment by Ghostkeeper** [comment]
My condolences.

**Comment by TMHogenhout** [comment]
I found this as well on Windows 7 (only then it goes black..).

**Comment by awhiemstra** [comment]
Since there are several major upstream bugs relating to fullscreen we have temporarily disabled the fullscreen option. Once the upstream bugs are resolved we can re-enable it.
