### ISSUE TITLE
Brim inside when Brim Outside only

### ISSUE THREAD

**Issue by Abelma1500** [Ultimaker/Cura#4954]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Abelma1500** [comment]
Brim inside model when Only Brim Outside activated

**Comment by smartavionics** [comment]
This maybe a duplicate of https://github.com/Ultimaker/Cura/issues/4222 but as you don't provide any useful information it's hard to know for sure.

**Comment by Ghostkeeper** [comment]
Yeah I'm closing this as a duplicate of #4222.
