### ISSUE TITLE
3.6.0:  bug in layer view

### ISSUE THREAD

**Issue by nesergen** [Ultimaker/Cura#4979]
**Application Version**
 3.6.0 

**Platform**
LinuxMint 18 

**Printer**
Creality - CR10mini

**Steps to Reproduce**
- open any 3d model
-  prepare
- go to LayerView
- color scheme - ANY type
- The CheckBoxes in Visualization selected randomly

**Actual Results**
What I see on display - shape (shadow) of the 3d model .  The Layer time slider at the end. The Layer number slider at the top. If I move  Layer number  slider nothing happen. If I move Layer time slider the 3d model (helpers, shell, infill and others) appears. If I move Layer number slider again the 3d model disappears. Only if all CheckBoxes in Visualization selected the 3d model viewed always.

**Expected results**
To see the 3d model with any combination of CheckBoxes , Layer sliders positions.

**Additional Information**
I have posted the topic on Forum. There are placed  a video in gif format .
https://community.ultimaker.com/topic/25603-bug-in-gui/

[cura.log.zip](https://github.com/Ultimaker/Cura/files/2673462/cura.log.zip)
[cura.cfg.zip](https://github.com/Ultimaker/Cura/files/2673466/cura.cfg.zip)

**Comment by fieldOfView** [comment]
This is not a bug, it seems to be behaving as expected. If you turn off the display of output of your (single) extruder, there is nothing left. The "Extruder" checkbox does not make too much sense for a single-extrusion printer, but there would be "Extruder 1", "Extruder 2", ... checkboxes for a multi-extruder printer, so you can check what each individual extruder does.

For single extruder printers, just keep that "Extruder" checkbox checked.
