### ISSUE TITLE
.3mf.3mf in the filename

### ISSUE THREAD

**Issue by zhou13** [Ultimaker/Cura#4984]
**Application Version** 3.6.0

**Platform** Linux

**Printer** Not related

**Steps to Reproduce**
Client menu File -> Save

**Actual Results**
Filename should be `Untitled.3mf`.

**Expected results**
Filename is `Untitled.3mf.3mf`.

**Comment by nallath** [comment]
Unfortunately, the file dialog sometimes does this on it's own. It's outside of our control what actually happens in this case.

**Comment by zhou13** [comment]
I don't quite understand why this is out of the control. If the file dialog automatically add `.3mf`, then you can just pass `Untitled` rather than the `Untitled.3mf` to the function call.  I think this is a bug that should be fixed so please at least leave the issue open.
