### ISSUE TITLE
Obvious difference Between 25% & 26% Infill

### ISSUE THREAD

**Issue by Tonyiiii** [Ultimaker/Cura#4988]
i have observed an obvious difference between the 25% and 26% infill when looking at the layer view of a simple PLA 3D Print. 

perhaps i miss something and it's not a bug but seems to mee there is much more infill in the jump from 25% to 26%, compared to (for example) 24% to 25%.
see attached 3x screen grabs.

24% example:
![cura 3 6 24 infill](https://user-images.githubusercontent.com/45852623/49946540-4cbac380-ff43-11e8-8f82-2355135dd399.jpg)

25% example:
![cura 3 6 25 infill](https://user-images.githubusercontent.com/45852623/49946539-4cbac380-ff43-11e8-9a64-d74da7bf8fe8.jpg)

26% example:
![cura 3 6 26 infill](https://user-images.githubusercontent.com/45852623/49946541-4cbac380-ff43-11e8-8a14-aa65052cfd8f.jpg)

**Comment by AbeFM** [comment]
ORLY!

I guess I saw this before, and just thought I was multitasking too much and forgetting what I was doing.
