### ISSUE TITLE
Slider bar is missing in layer view

### ISSUE THREAD

**Issue by crazymumu** [Ultimaker/Cura#4989]
**Application Version**
3.7-PPA

**Platform**
Linux Mint 19 Cinnamon
Cinnamon version 3.8.9

**Printer**
Creality CR-10

**Steps to Reproduce**
Loads any .stl file and switch view mode to layer view.

**Actual Results**
The slider bar info panel is not showing.

**Expected results**
When layer view is selected, the layer slider bar and panel should display on the screen.

**Additional Information**
[screenshot](https://i.ibb.co/RgKtQ92/Screenshot-from-2018-12-13-10-55-47.png)
#4683

**Comment by diegopradogesto** [comment]
3.7-PPA is not an official release from Ultimaker. This is probably and intermediate version and we know about this problem because we are working in a new design. It will be available as BETA on December 18th.

Thanks for sharing.
