### ISSUE TITLE
[Feature Req] Speed: Small Perimeters

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#4991]
Due to the motion control limitations of essentially all 3D printers, handling acceleration and jerk becomes increasingly difficult on smaller radii. Especially on small holes (short perimeters / walls), speeds which work very well on larger loops, are problematic. STL tolerancing means that the segment to segment angles get exaggerated, requiring more jerk and higher acceleration. This results in poor printed form.

The simple solution is to just do them at lower speed. Developing a feature (like Slic3r has) to evaluate the length of loops, and below a certain threshold, enact a slower (defined) printing speed, would be super useful!

**Comment by smartavionics** [comment]
Hello @CCS86 , that capability already exists in my Cura releases which you can find at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by Thisismydigitalself** [comment]
Always wondered about this issue. 
I will definatly give this version a try.

**Comment by CCS86** [comment]
@smartavionics, very cool!

Is there a reluctance to merge that feature into the main release branch?

**Comment by smartavionics** [comment]
They (the Cura guardians) had the opportunity to merge this feature for several months but they didn't do it. I get bored keeping PRs up to date with the changes to the master code base so if PRs don't get any attention in a few months I close them. You can lead a horse to water, ...

**Comment by Thisismydigitalself** [comment]
@smartavionics 
In regards to small features, Your version works like a charm.

Much Obliged.

**Comment by smartavionics** [comment]
You're welcome.

**Comment by DDDirk** [comment]
A problem with changing the print speed is that the extrusion speed (feed rate) also changes. But with a bowden tube, there is a delay between the feeder and what comes out the nozzle. So if the print speed slows down, there will initially be too much pressure in the nozzle, which will cause overextrusion. Especially with a small feature, that might be a problem. Except if it is printed after a travel move. The pressure may have oozed away, and you can actually get underpressure and underextrusion. Of course the two may also cancel out.

**Comment by CCS86** [comment]
That's what linear advance and coasting are for. Avoiding all print speed changes, isn't a solution for bowden induced lag. 

Cura already has like 9+ print speed settings. One more for small loops would be a real benefit.

**Comment by Thisismydigitalself** [comment]
I have only direct drive printers. 
Couple of hours ago i used @smartavionics version to print a model with small round holes & small text and for the first time ever I saw my printhead print those slowly and gracefully that i am now hooked to this feature. instead of printing these holes like blazingly fast they came out perfect.

**Comment by AbeFM** [comment]
I have used a similar feature on other slicers and I miss it every time I come back.

**Comment by CCS86** [comment]
Devs?

**Comment by KampfGurke20** [comment]
@smartavionics
What must i do to get RepetierIntegration working with your Version?
I Downloaded the Plugin into "C:\Program Files\Ultimaker Cura master\plugins\RepetierIntegration" as i did with the Original 3.6, but there is No Button to Setup the Printer :(
![1](https://user-images.githubusercontent.com/25879166/51688298-8ed02e00-1ff4-11e9-9a3b-58924359d10d.JPG)
![2](https://user-images.githubusercontent.com/25879166/51688299-8f68c480-1ff4-11e9-9e7e-28244dfff06e.JPG)

**Comment by fieldOfView** [comment]
Don't download plugins into the program files folder, but put them in the Configuration folder instead. See Help -> Show configuration folder, and then find the plugins folder contained in that.

While you are in the Configuration folder, locate the file named "Cura.log". It should show the reason why the plugin is not loading.

**Comment by KampfGurke20** [comment]
I had tried both, first in the program folder and then in the configuration folder!
(Thats the Plugin: https://github.com/VMaxx/RepetierIntegration ) 
Because it has a Master Branch i thought it should work :(

So I can only wait until the plugin gets an update, right?
I think I'm too stupid to repair that myself.

Well, as long as I have to upload the GCode by hand.

Thanks for your help! :)

**Comment by CCS86** [comment]
Guys, this seems unrelated to the feature request.

**Comment by smartavionics** [comment]
It's true, we digress...

**Comment by diegopradogesto** [comment]
Discussed internally with our materials and processing team and it seems that it's a nice feature to have. However we think it's also good to add **acceleration** and **jerk** as separate settings for the small features.

For internal reference: CURA-6158

**Comment by Thisismydigitalself** [comment]
@smartavionics 
Hi Mark, Any chance your small featuers solution can be added to 3.6 release version?
I don't see myself moving to 4.x any time soon and would like to stick with 3.6 as i had some issues with Master versions.

Cheers.

**Comment by fieldOfView** [comment]
New features will never be added to old/current versions of Cura. In other words: there will not be a version of Cura 3.6 with new features, unless they can be added in a plugin.

**Comment by Thisismydigitalself** [comment]
I really hope this so invaluable feature will one day become a plugin and the sooner - the better.

**Comment by smartavionics** [comment]
Hi @Thisismydigitalself , I'm afraid I can't make a 3.6+ release now. Sorry about that.

**Comment by Thisismydigitalself** [comment]
:(

**Comment by JorgeUliana** [comment]
Hi @smartavionics.
Thank you very much for creating this feature.
I was searching for him some time.
They should include it urgently in version 4.0, because to me this seems like a failure in Cura.
I did not have time to print the piece using its version, but in the simulated mode I noticed a series of improvements in the path between the printed parts and the printed parts.
I used the enable ironing, and the percussion on it also got better.

**Comment by smartavionics** [comment]
Hello @JorgeUliana , this feature was presented to the Cura devs about 10 months ago and they ignored it for so long that I gave up keeping it up to date WRT the master branch. I have dusted it off and made it available again. As I already have around a dozen contributions (PRs) that are also being ignored, I wouldn't expect this to be available in Ultimaker Cura anytime soon. Let's be optimistic, they may surprise us yet.

**Comment by SonOfSardaar** [comment]
I want this badly please, cura is not handling small holes good enough

**Comment by AlexPl81** [comment]
> Hello @JorgeUliana , this feature was presented to the Cura devs about 10 months ago and they ignored it for so long that I gave up keeping it up to date WRT the master branch. I have dusted it off and made it available again. As I already have around a dozen contributions (PRs) that are also being ignored, I wouldn't expect this to be available in Ultimaker Cura anytime soon. Let's be optimistic, they may surprise us yet.

Thanks for the release you have uploaded. I can't believe such vital feature is missing. I have it on Prusa Slicer, and my Prusa MK3  prints small holes well, however my Ender 3, for which i use Cura makes quite a mess racing through 2mm holes at full speed. I started looking for solution (i didn't want to switch to Prusa Slicer for everything) and here it is. Thanks again.

**Comment by Ghostkeeper** [comment]
This is added to Cura a few releases ago.
