### ISSUE TITLE
The extruder Does not heat up [RAISE3DN2PLUS]

### ISSUE THREAD

**Issue by spacyje** [Ultimaker/Cura#5016]
Hello,

I downloaded cura 3.6 and used the profile for my raise 3D N2 plus dual.

I use the nozzle on the left 1, set to 200 C with a bed at 60 C.  Once the gcode is in the printer, the bed starts to heat up but there is no increase in temperature of the extruder.  I don't understand the problem.

Thank you for your help.

**Comment by Ghostkeeper** [comment]
Maybe it needs an `M109 S{material_print_temperature_layer_0}` in the start g-code or something.
