### ISSUE TITLE
Cura 3.6.0 Save Naming Issue

### ISSUE THREAD

**Issue by limks27** [Ultimaker/Cura#5024]
**Application Version**

3.6.0
**Platform**

Win10 Pro
**Printer**

Dobot Mooz2
**Steps to Reproduce**

Save with Removable Drive
**Actual Results**

Naming incorrect when save to removable drive
![cura_3 6_removable_naming](https://user-images.githubusercontent.com/46010771/50259131-c23ffb80-043d-11e9-94a9-2e628f34fa97.JPG)
**Expected results**

Added a "." at the end of naming to have the naming save correctly to removable drive 
![cura_3 6_removable_naming_ok](https://user-images.githubusercontent.com/46010771/50259189-07642d80-043e-11e9-9268-8c21e4390e14.JPG)
**Additional Information**

**Comment by Ellecross** [comment]
Hey @limks27 thanks for reporting this and sorry for the very very very late reply. 
I'm going to close this issue as it is already fixed in 4.1 and in the cura master branch. 
![image](https://user-images.githubusercontent.com/32929710/60277494-ee14d000-98fd-11e9-9036-12b4a4f23b0a.png)
