### ISSUE TITLE
[master] simple model becomes segmented

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#5025]
**Application Version**

master branch

**Platform**

Linux

**Printer**

Any

**Steps to Reproduce**

Load the model below and slice.

**Actual Results**

The layer view shows that one end of the model is segmented into a "string of sausages" but a similarly curved region on the other end of the model is not segmented.

**Expected results**

The wall outline is not segmented.

**Additional Information**

Most issues like this are normally caused by a bad model but, so far, I cannot find a problem with this model. S3D and craftware can slice it OK, freecad says that it has no issues.

[40x10.zip](https://github.com/Ultimaker/Cura/files/2697867/40x10.zip)

![screenshot_2018-12-20_07-53-39](https://user-images.githubusercontent.com/585618/50271583-0a0a5700-042d-11e9-91db-794081047547.png)

![screenshot_2018-12-20_07-52-56](https://user-images.githubusercontent.com/585618/50271584-0a0a5700-042d-11e9-8573-b6a09b28337c.png)

**Comment by smartavionics** [comment]
I found a workaround, using just a tiny amount of horizontal expansion joins the segments.

![screenshot_2018-12-20_08-15-30](https://user-images.githubusercontent.com/585618/50272371-78e8af80-042f-11e9-8285-fd84e76c762a.png)

Perhaps Cura should add a similarly small amount by default although that would require doing an offset on every mesh.

**Comment by nallath** [comment]
Does the issue also occur with older versions of Cura (3.6 / 3.5?)

**Comment by smartavionics** [comment]
3.4.1 doesn't have the problem so it's a regression introduced since that release.

**Comment by Ellecross** [comment]
Hey guys, I see it happen still in 3.4.1. 
Then in 3.3 and 3.2, it looked even worse. 
I have a feeling it has always been this way? :/ 

See images below: 
![3-2-1](https://user-images.githubusercontent.com/32929710/50636506-a0269d00-0f56-11e9-9eea-86bd224834ab.PNG)
![3-3-1](https://user-images.githubusercontent.com/32929710/50636507-a0269d00-0f56-11e9-94e5-2e72f048a99f.PNG)
![3-4-1](https://user-images.githubusercontent.com/32929710/50636509-a0269d00-0f56-11e9-95eb-daec1a140275.PNG)

**Comment by smartavionics** [comment]
Hi @Ellecross , you're absolutely right, I was mistaken to say earlier that 3.4.1 did not have the problem.

(Maybe) interestingly, I have discovered that if you set the wall line width such that it only prints with thin walls enabled, the thin wall isn't segmented...
![screenshot_2019-01-03_13-45-06](https://user-images.githubusercontent.com/585618/50640864-08c54800-0f5e-11e9-9074-9c69d43eb6e3.png)

**Comment by smartavionics** [comment]
I think this is caused by a non-zero Outer Wall Inset, setting that to zero gives OK results.

![screenshot_2019-01-04_08-17-08](https://user-images.githubusercontent.com/585618/50678972-25628e00-0ff9-11e9-9e51-7ad94c6513aa.png)

Closing...

**Comment by PaulD79** [comment]
I solved it by changing to a different print orientation.
PaulD79
