### ISSUE TITLE
Cura 3.3.1: Solid not well printed

### ISSUE THREAD

**Issue by Zapillo** [Ultimaker/Cura#5035]
I'm trying to print a draft of thread, the solid view is like the design but layers doesn't match up with it. In attachment, images of both pictures. I can't upload the stl file.

![captura rosca capas](https://user-images.githubusercontent.com/46046599/50337755-5ed3cd80-0512-11e9-909e-9473de410387.JPG)
![captura rosca solido](https://user-images.githubusercontent.com/46046599/50337756-5f6c6400-0512-11e9-8daa-42a177d5b77c.JPG)

**Comment by nallath** [comment]
How does the model look in x-ray view? It seems like the model has mistakes in it.

**Comment by alekseisasin** [comment]
To upload the *.stl files first you need to archive them and then upload. Or another option: https://wetransfer.com/

**Comment by Zapillo** [comment]
In attachment xray view
![captura rosca capas xray](https://user-images.githubusercontent.com/46046599/50351429-79259f80-0542-11e9-944f-f917da19ac74.JPG)

**Comment by Zapillo** [comment]
STL file in attachment by zip
[prueba rosca dremel.zip](https://github.com/Ultimaker/Cura/files/2703408/prueba.rosca.dremel.zip)

**Comment by Zapillo** [comment]
I have just downloaded Cura 3.6.0 version but with the same result

**Comment by nallath** [comment]
That's because the model is invalid; The red areas indicate that the model has faults in it. So pass the model through a model fixer and try again.

**Comment by Zapillo** [comment]
Thanks Jaime for your return.

I will try to check it again.

Have a good day.
