### ISSUE TITLE
End G code only partially sent to printer

### ISSUE THREAD

**Issue by metzb1** [Ultimaker/Cura#5042]
**Application Version**
3.6

**Platform**
Windows 10 Pro 64 bit

**Printer**
SeemeCNC Rostock V3.21

**Steps to Reproduce**
Export G code, upload to printer, print.

**Actual Results**
Machine did not home, bed heat stayed on

**Expected results**
End G code specified to home machine and turn off bed heat.

**Additional Information**
End G code specified:
M203 Z24000
M104 S0
M140 S0
M107
G28
M84

End G code exported by CURA:
; MatterSlice Completed Successfully
M104 S0 ; turn off temperature
G91
G1 Z5.0 E-3.5 F12000
G90
G28
M84     ; disable motors

**Comment by GregValiant** [comment]
Is this still an issue?
