### ISSUE TITLE
Setting floater is far too small

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#5044]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ellecross** [comment]
Hey @tlhintoq , what do you mean 'setting floater'? 
Can you provide more information please?

**Comment by tlhintoq** [comment]
Hi @Ellecross 
Here is a screen shot with the Settings pallet labeled.
Along with all the other dead/wasted space that could be tightened up to make more room for working space.
![image](https://user-images.githubusercontent.com/11351506/50482044-c080b580-09b2-11e9-92af-0280069716d0.png)

**Comment by tlhintoq** [comment]
That's great news @Ghostkeeper.  Resizability and remembering state between sessions is a big improvement and the kind of UI expectations most people have in 2019.

Dragable/dockable panels would be AWESOME especially when so many people have multiple monitors.  It would be great to put all the pallets on the second monitor leaving the 3d Model ("build plate") view completely unobstructed and full screen.

**Comment by Ghostkeeper** [comment]
Yeah, but we're not going to be able to implement that for 4.0. Maybe in a later release though. It's not going to be trivial, especially if we also want it to be able to detach from the main window.

**Comment by fieldOfView** [comment]
In the mean time, I'm working on a plugin that changes the new GUI in Cura to be more settings-centric by adding back the concept of a sidebar. If you can't get used to the floating panels in the new GUI, there will soon be a plugin for you.

![image](https://user-images.githubusercontent.com/143551/50640174-5a70d100-0f64-11e9-8d1c-8ad950f9dfad.png)
