### ISSUE TITLE
[3.6] No indentation in machine definitions

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5045]
**Application Version**
3.6

**Platform**
Windows 10 x64

**Printer**
Any.

**Steps to Reproduce**
Go to ...\Ultimaker Cura 3.6\resources\definitions and open any machine definitions.

**Actual Results**
There isn't any indentation and so any customization becomes hard to do.

**Expected results**
There should be an indentation.

**Additional Information**
![indentation](https://user-images.githubusercontent.com/20385116/50379427-c8a2c300-0649-11e9-91de-ed4ada373f0f.png)

**Comment by fieldOfView** [comment]
Use a better text editor that supports unix-style line-endings. Notepad++, Sublime Text, something like that. Just not Notepad, and not Wordpad either.

**Comment by smartavionics** [comment]
Even better, use Linux and not Windows!

**Comment by Liger0** [comment]
Perfect, it was the problem. Thanks.
