### ISSUE TITLE
[3.6] Primer tower skirt can be over the build plate when using tree supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5052]
**Application Version**
3.6

**Platform**
Windows 10 x64

**Printer**
Cr-10s modified for dual extrusion

**Steps to Reproduce**
Put the purge tower at a corner and use a skirt

**Actual Results**
When using a tree support, the skirt can go over the build plate and it is printed. It can be dangerous for the printer.
However, using normal supports, the slicer notices it and the slicing correctly fails advising the purge tower has an invalid position.

**Expected results**
Cura should be able to tell the skirt of the purge tower is made out of the build plate when using tree supports, not only when using normal supports. 
The shape of the purge tower skirt is weird too, it isn't circular.

Also, why isn't there a way to disable skirt/brim for the purge tower?

 

**Additional Information**
![prime tower skirt](https://user-images.githubusercontent.com/20385116/50388199-7deb7e80-070f-11e9-8127-31d7c1d102c4.png)

**Comment by Vandrasc** [comment]
Hi @Liger0 , thank you for your feedback, took as a while to reply but in the meanwhile, we did fix this issue. If time allows you could you please give 4.1 a try? Please re-open the ticket if the issue still occurs for you.

Thank you!
