### ISSUE TITLE
change nozzle diam cura 4.0

### ISSUE THREAD

**Issue by cool0025** [Ultimaker/Cura#5055]
**Application Version**
cura 4.0

**Platform**
win 10 

**Printer**
dymco p802

**Steps to Reproduce**
want change nozzle diam

**Actual Results**
dont find option , before in printer setting

**Expected results**
 juste change nozzle diam 

**Additional Information**
 when i want do a brim , the plate change dimensions and go smaller . if i want do a ez christmas tree , with 30 mm brim , around to be stable on a table , i need to place this tree in the middle ,

**Comment by Ghostkeeper** [comment]
It's still in the printer settings (under the tab of the appropriate extruder). If you actually changed your hardware to have a different nozzle size, you should still be able to change it there.

If you didn't change any hardware, I advise you to just change the line width.

**Comment by cool0025** [comment]
![2018-12-24](https://user-images.githubusercontent.com/46098523/50405148-89c25980-077e-11e9-98ee-57c6c048ff22.png)
i dont find the place , can you  show me where they are now , before in this option , with the setting of the filament

**Comment by Liger0** [comment]
Marketplace -> Printer settings

**Comment by cool0025** [comment]
![2018-12-25 1](https://user-images.githubusercontent.com/46098523/50428481-173ca100-0886-11e9-831c-3105f24a083e.png)
![2018-12-25 2](https://user-images.githubusercontent.com/46098523/50428482-173ca100-0886-11e9-9121-e4f40329734e.png)
![2018-12-25](https://user-images.githubusercontent.com/46098523/50428483-173ca100-0886-11e9-9e58-f29f815dcd95.png)
nothing in marketplace no printer setting here if you know where in cura beta 4.0 , take a picture and let me know , i have the setting for 1 printer with 0.6 nozzle , and 1 another model with 0.4 , ok 2 different model , but i swich between 3 king of nozzle , and i just saying i see nothing in this version of cura to change dhis setting , before present and easy to find .

**Comment by fieldOfView** [comment]
The Printer Settings plugin has not yet been released for 4.0. I have submitted a compatible version but it hasn’t been sanctified yet.

**Comment by cool0025** [comment]
haha , ty , i have reinstall 3.6 , and use both , i like the new 4.0 interface ,
