### ISSUE TITLE
[3.6] Cura crashes enabling the second extruder by the top right button all the times

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5064]
**Application Version**
3.6

**Platform**
Windows 10 x64

**Printer**
Any dual extrusion machine

**Steps to Reproduce**
Use a double extrusion machine and disable, then re-enable again the second extruder by right clicking the top right tool

**Actual Results**
Cura crashes

**Expected results**
Cura shouldn't crash

**Additional Information**
[cura log.zip](https://github.com/Ultimaker/Cura/files/2709128/cura.log.zip)

**Comment by Ellecross** [comment]
Ahh yeah. I see it. 

In 4.0, it doesn't crash, but it does not load the machine configurations anymore. 
In 3.6, it also doesn't crash for me, but the same behavior shows up - configurations are not loaded. 

4.0 
![image](https://user-images.githubusercontent.com/32929710/50484972-884d9700-09f3-11e9-80c5-420001cec618.png)

3.6
![image](https://user-images.githubusercontent.com/32929710/50484981-913e6880-09f3-11e9-8d26-4cedb8266a14.png)

In one of the tickets you raised, you mentioned that you have manually modified CR-10 file to have dual extrusion, is that correct? 

I don't know how to repair this at this moment, but I can ask one of our devs when they get back (it's holiday season now, most people are away). In the meantime, I think you'll have to reset your settings so you can continue. :/ sorry, man. 

That's why the https://github.com/Ultimaker/Cura/issues/5047 will be good to have someday too!

**Comment by Liger0** [comment]
> 
> 
> Ahh yeah. I see it.
> 
> In 4.0, it doesn't crash, but it does not load the machine configurations anymore.
> In 3.6, it also doesn't crash for me, but the same behavior shows up - configurations are not loaded.
> 
> 4.0
> ![image](https://user-images.githubusercontent.com/32929710/50484972-884d9700-09f3-11e9-80c5-420001cec618.png)
> 
> 3.6
> ![image](https://user-images.githubusercontent.com/32929710/50484981-913e6880-09f3-11e9-8d26-4cedb8266a14.png)
> 
> In one of the tickets you raised, you mentioned that you have manually modified CR-10 file to have dual extrusion, is that correct?
> 
> I don't know how to repair this at this moment, but I can ask one of our devs when they get back (it's holiday season now, most people are away). In the meantime, I think you'll have to reset your settings so you can continue. :/ sorry, man.
> 
> That's why the #5047 will be good to have someday too!

Okay, I understand. Though I don't have any configuration error message, and cura also crashes using ultimaker machines with double extrusion.
I am sure the only reason you have those errors is that indeed I didn't share my cura install folder, which is in the D drive, and that is where my machine definition are stored, so for me all is fine why to you you have those errors because you have some link present in the C drive but not the fies needed, which are just stored elsewhere.

To make it clear, it is the cura folder I shared: C:\Users\Account\AppData\Roaming\cura
While this is where definitions are stored: D:\Programmi\Cura\Ultimaker Cura 3.6\resources\definitions

**Comment by Liger0** [comment]
I completely uninstalled cura using Revo uninstaller, and then I pasted again the custom definitions and extruders I made making everything as it was before, but now I don't have those crashes. I don't know if it was some other settings interfering with it or if the install was somehow damaged.
But, now, I just noticed the material bug of the ticket #5071

**Comment by Liger0** [comment]
> 
> 
> > But I have just found possibly the culprit. I noticed that the crash only happens after this window appears for whatever reasons
> 
> That narrows it down a bit, but I'm not able to reproduce it here yet.
> 
> That message appears when you have settings in a custom profile that need to be changed because you're reducing the number of extruders. My reproduce steps are:
> 
>     1. Start Cura completely clean. Accept the license and such.
> 
>     2. Add Ultimaker S5 printer.
> 
>     3. Load a model.
> 
>     4. Set Wall Extruder to extruder 2.
> 
>     5. Save the current changes to a profile called "bla".
> 
>     6. While "bla" is active, go to the machine manager and the machine settings.
> 
>     7. Change the number of extruders to 1.
> 
>     8. (Slice.)
> 
>     9. Change the number of extruders back to 2.
> 
>     10. (Slice again.)
> 
> 
> I'm not getting any crashes this way. What were your steps taken?

Is it possible that it may be indirectly caused by my custom definitions? 
I have those custom definitions made by myself, but Cura doesn't report any error, and also the crashes happen on other machines.
So basically it may happen that a somewhat wrong configuration may make cura crashe even while other machines are in use, maybe?
https://github.com/Ultimaker/Cura/files/2715021/custom.cr-10.definition.and.extruder.zip
