### ISSUE TITLE
Cura 1.1beta for Wanhao crashes when printing via USB

### ISSUE THREAD

**Issue by paulnaude** [Ultimaker/Cura#5073]
**Application Version** 1.1 beta

**Platform** Windows 10 64bit

**Printer** Duplicator i3

**Steps to Reproduce** Send file to printer via USB

**Actual Results** Windows reports that Cura stopped working.

**Expected results** Windows message appears that Cura stopped working
![cura crash](https://user-images.githubusercontent.com/23168020/50494571-b13e4e00-0a2c-11e9-8800-1125c4f34f48.png)

**Additional Information**

**Comment by Vandrasc** [comment]
Hi @paulnaude, this is not our code, the Cura Wanhao may be based on Cura but it is not Ultimaker Cura so unfortunately, we cannot help you here. Maybe you can contact the Cura Wanhao instead? 

Also, we do not have the Duplicator i3 machine definition in Cura so no idea if that will work here either. 

Good luck!
