### ISSUE TITLE
Feature: turn off drop on platform

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#508]
For some materials the bed adhesion is a large problem.
It is sometimes needed to print support and then also a raft.

However, sometimes the support doesn't attach to the raft very well and it would be nicer to just raise the mesh, so that support is also generated for the bottom of the object, instead of needing a raft there.

Cura frontend: 
- have option to turn off drop object on build plate
- make [drop on build plate] a context menu item

CuraEngine:
- make an option to not remove empty first layers

**Comment by fieldOfView** [comment]
This has been implemented, issue can be closed
