### ISSUE TITLE
Make elephant foot compensation easier to find and enabled by default

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#5081]
![Elephant foot](https://d3v5bfco3dani2.cloudfront.net/photo/image/1300x0/599be979ec055/image10.png)

**Application Version**
3.6

**Platform**
Linux, probably any

**Printer**
Ender-3, probably any

**Steps to Reproduce**
Search for "Elephant"
![elepant](https://user-images.githubusercontent.com/2480569/50540913-ed8bbe80-0b92-11e9-949a-7364383bdf50.png)

**Actual Results**
Nothing shows up

**Expected results**
An entry field shows up to enter the desired amount of elephant foot compensation

**Additional Information**
https://ultimaker.com/en/blog/50847-introducing-cura-27 talks about "horizontal expansion on initial layer" but it would be good if searching for "elephant" would find this

![explain](https://user-images.githubusercontent.com/2480569/50540912-e9f83780-0b92-11e9-8d7d-e1f900c1bd71.png)

**Comment by probonopd** [comment]
Note to self: This works for me (0.6 mm nozzle):

![solution](https://user-images.githubusercontent.com/2480569/50540949-8a4e5c00-0b93-11e9-95cb-8e5559870e13.png)

**Comment by Liger0** [comment]
It's just that you are using a world invented by yourself.
The correct term is "linear advance", and it's done by enabling it in the firmware and/or Cura marketplace.

**Comment by probonopd** [comment]
Elephant foot compensation is about the first layer being to large in the x-y direction. It is not to be confused with Linear Advance, which is about the corners.

**Comment by Liger0** [comment]
> 
> 
> Elephant foot compensation is about the first layer being to large in the x-y direction. It is not to be confused with Linear Advance, which is about the corners.

I think you can play with the line width and line height for the first layer to adjust it.

**Comment by probonopd** [comment]
> How about adding a feature where the search function also searches the help texts?

I think this is a _great_ idea. I would always type "elephant" because I have already forgotten how the Cura name for this feature is...

**Comment by Ghostkeeper** [comment]
There are many ways to deal with elephant foot though, and initial layer horizontal expansion is not usually the best of them. My first approach would be to look at the strength of the walls above the first layers (since quite often the strongest effect is that the skin doesn't shrink but the walls around the infill do). And then I tend to look at the build plate temperature and cooling. And only after that will I look at compensation methods like initial layer horizontal expansion. I think labelling this as "this will fix elephant foot" is misleading.

**Comment by Ghostkeeper** [comment]
Maybe it's an idea to include the setting descriptions in the search filter?

**Comment by probonopd** [comment]
@Ghostkeeper yes, pretty much so. (I search for "Elephant" in Cura every time...)

**Comment by mahtDFR** [comment]
We discussed this morning and think it's a good suggestion. It's on the backlog to be implemented in a future release.

**Comment by probonopd** [comment]
Looking at [this video](https://youtu.be/vuKuil0dJqE?t=44), it seems like version 4.7 is my lucky version :-)

Especially like how the video explains the feature with the __elephant foot__ example :+1: 

![image](https://user-images.githubusercontent.com/2480569/91220883-6185bd80-e70c-11ea-8497-65ba93cf7d7f.png)

Thank you very much Ultimaker Team!

**Comment by nallath** [comment]
It only took us 1.5 year to implement it ;)

**Comment by Ghostkeeper** [comment]
It's really effective when combined with the option in the Settings Guide to show the articles in the setting tooltips (which makes it replace the setting descriptions and thus changes what the search function searches through).
