### ISSUE TITLE
Issue with slow rendering performance and high CPU on certain Macs still present in 4.0 beta rendering

### ISSUE THREAD

**Issue by ubermacin** [Ultimaker/Cura#5088]
Application Version
Cura 4.0 Beta

Platform
Macbook Pro 2010 running High Sierra

Printer
Ender 3

Steps to Reproduce
run the program, load any STL (multiple tested)  Even no model loaded will have very slow response

Actual Results
Model view or empty bed frame rate is very slow compared to Cura 3.4.1

Expected results
Same frame rate or faster (Please!)

Additional Information
This is the same issue reported for Cura 3.5 and has persisted since.  3.4.1 runs like a dream, 3.5+ runs in single digit frame rates.

Related issue: https://github.com/Ultimaker/Cura/issues/4505

**Comment by app-js** [comment]
+1

**Comment by ubermacin** [comment]
This is now fixed in 4.1
