### ISSUE TITLE
Cura 4.0 'master' settings

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#5097]
**Application Version**
4.0 Master

**Platform**
Win10/64
 

I see improvement in regards to settings window which now can be pulled all the way from top to bottom of main workspace but..

- Why the free space on the right to the settings? why wasting real-estate?
- Why Xray view opens in the middle of the screen covering most of the workspace?
- Will we have Expand/Collapse all settings for as quickly as possible jump between settings in different categories? of course best would be what i asked for more than a year now - to see a summery of my prefered settings at all times and being able to click on these for quick tweaking. my work with Cura is mostly tweaking & Re-Slicing many times again and again before printing. 

Still slicing with 3.6 and lovin' it.

![ice_screenshot_20190102-173025](https://user-images.githubusercontent.com/30949968/50598964-1ecafe00-0eb5-11e9-9018-ae0d3834cff6.png)
![ice_screenshot_20190102-173004](https://user-images.githubusercontent.com/30949968/50598966-21c5ee80-0eb5-11e9-95a6-b0c8bac0883c.png)

**Comment by diegopradogesto** [comment]
This is fixed in the next 4.1 version, by adding an empty placeholder in between.

![image](https://user-images.githubusercontent.com/15830521/57127379-7e1c1a80-6d90-11e9-9c68-7075c9736058.png)

**Comment by Ghostkeeper** [comment]
> Why the free space on the right to the settings? why wasting real-estate?

This is reduced in 4.1 and you can also drag the panel around if you want.
