### ISSUE TITLE
help needed: ImportError: "No Module named UM" in Eclipse

### ISSUE THREAD

**Issue by smsunny** [Ultimaker/Cura#510]
Hello, I am a newbie programmer in python. I was trying to run the 'Cura' project in Eclipse. I have cloned the github repository in Eclipse and created a PyDev project. But whenever I am trying to run any .py file, it creates error: "ImportError: No module named 'UM'". I am not sure what to do now. Can anyone please help me how can I fix this? Thanx in Advance

**Comment by Xisle** [comment]
Grab Uranium also.. not certain what else you need.

https://github.com/Ultimaker/Uranium

**Comment by smsunny** [comment]
I have cloned uranium also, but as a separate project. Do I need to have all the files of Uranium in the same directory as Cura?

**Comment by awhiemstra** [comment]
No, you need to set the right PYTHONPATH enironment variable. Not sure how Eclipse handles this, but from the command line you would do PYTHONPATH=/path/to/uranium/repo cura_app.py .

**Comment by zhenhuashao** [comment]
请问您这边解决了嘛

**Comment by zhenhuashao** [comment]
my prompt is wrong：ModuleNotFoundError: No module named 'UM'

**Comment by Ghostkeeper** [comment]
On Windows 10 it works the same way. You need to change the `PYTHONPATH` environment variable to include the path to Uranium. I think [this search result](https://superuser.com/a/949577) explains it well enough. It's the same as any other Windows release, really.
