### ISSUE TITLE
Problems with BMP and JPEG import

### ISSUE THREAD

**Issue by nyponen** [Ultimaker/Cura#5100]
**Application Version**

3.6.0
**Platform**

Windows 10
**Printer**

Ultimaker 2 Go
**Steps to Reproduce**

1. Open a BMP or JPEG file.
2. Click Prepare.
**Actual Results**

The weight of filament needed is given as 0g.
**Expected results**

The correct weight of filament should be given.
**Additional Information**

I print things to spin cast in silver and bronze. In order for the casting to work properly, I need to know the exact weight of the metal needed. If I know the weight of the PLA, I can calculate the weight of metal needed, but Cura doesn't tell me the weight of the PLA.

There are other issues that prevent BMP/JPEG import from being as useful as it could be. For example, the amount of smoothing should be able to be input as a specific number, which would give more reproducible results than using a slider.

**Comment by nallath** [comment]
I've just tried to reproduce this with the 4.0 beta, and I get a weight & amount of material used as expected.

**Comment by nyponen** [comment]
I just tried this with the 4.0 beta, and got the same problem. The weight is given as 0g.
![curabug](https://user-images.githubusercontent.com/17462467/50650092-5c22a080-0f34-11e9-90cb-925cf97d3ea1.JPG)

**Comment by nyponen** [comment]
I get the same problem when I slice an STL. The weight is shown as 0g.

![curabug2](https://user-images.githubusercontent.com/17462467/50650569-ace6c900-0f35-11e9-823b-0be51fca21b9.JPG)

**Comment by nyponen** [comment]
The problem only happens when I specify the Ultimaker 2 Go printer. If I specify Ultimaker 2+, I get the correct filament weight.

**Comment by fieldOfView** [comment]
Ah, that makes sense. The Ultimaker 2 Go does not have materials in Cura. Materials are selected on the printer, so Cura does not know what material is used. Because Cura does not know what material is used, it cannot calculate the weight.

**Comment by nyponen** [comment]
The Ultimaker 2 Go only supports PLA. You cannot select any other material on the printer.

**Comment by fieldOfView** [comment]
What you could do is go to "Machine Settings" (on the Printers pane of the preferences) and select "Marlin" instead of "Ultimaker 2" as the GCode flavor for your printer.
