### ISSUE TITLE
[Feat.REQ] loop shorter than X, run at speed X

### ISSUE THREAD

**Issue by swatti87** [Ultimaker/Cura#5101]
Imagine a big'ish "plate" full of 3mm holes. A mounting plate maybe... 

All those circles running at high speed will be a challenge to any setup. At 100mm/s and high acc, even more and thats where i'm at.

Correct me if i'm wrong but the entire distance of that loop, doing the 3mm hole walls in this case can be calculated.
If that distance is below X amount in mm, reduce speed for the loop down to XX

No need to reduce acc/jerk that will affect the whole print, but it will then do small holes for example a bit slower, or lot slower.

Space-age stuffz! REQ : 
Lots of small surface-elements coming up. Slow down.
Imagine ~0.3mm text extruded or cut into a surface. Lots of small little "bits" in the outer wall. Running those at high speed will look terribad. 
Or you have to tweak acc/jerk and slow the whole print down.

Two settings: X amount of lines below length X -> Run at speed XX

I'm not sure if this is possible since it has to calculate longer forward.

**Comment by GregValiant** [comment]
@swatti87 I'm cleaning house around here.  This has been open for 6 years and UM has not picked it up.  Can I close this?
