### ISSUE TITLE
[3.6.0] Funky Support Structure

### ISSUE THREAD

**Issue by ryannhos** [Ultimaker/Cura#5108]
<img width="1666" alt="screen shot 2019-01-04 at 1 24 36 am" src="https://user-images.githubusercontent.com/35934202/50678093-b2d6bb80-0fc2-11e9-81b9-96c4dcc38095.png">

[cura.log](https://github.com/Ultimaker/Cura/files/2726254/cura.log)

[MSMV2E3D_xyzCalibration_cube.3mf.zip](https://github.com/Ultimaker/Cura/files/2726257/MSMV2E3D_xyzCalibration_cube.3mf.zip)

**Application Version**
3.6.0

**Platform**
Mac OS 10.14.2

**Printer**
Monoprice Select Mini V2 E3D

**Steps to Reproduce**
Open project, slice on Normal profile with support generation enabled, single extruder.

**Actual Results**
Support structure is divided between the legs of the X, instead of choosing one side.  This leaves part of the support structure....unsupported.

**Expected results**
Support structure should be continuous, up one leg (or both?) from lowest "floor" all the way to the bridge requiring support.

**Additional Information**
It's not just a weird rendering artifact.  That's the way it came out in the G-code too.

**Comment by nallath** [comment]
This has to do with your settings. Try changing the support X/Y distance.
