### ISSUE TITLE
Commandeering USB tty at startup

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Cura#511]
Johan reported this to me. He had a different connection open to an Ultimaker Original+ printer, with a different application. When Cura starts, the other program loses connection.

Platform: OSX
Version: 15.09.91

Steps to reproduce:

* Obtain an UMO+. Connect it to a computer via USB.
* Launch Pronterface (or something similar) and set up a connection to your printer.
* Launch Cura.

Expected results:
* Nothing happens in Pronterface. It retains connection.
* Cura is not able to obtain a USB connection. If both programs would be able to obtain a connection, g-code could mix up and this should not happen.

Observed results:
* Pronterface loses connection.
* Cura connects to the printer.

Note that I haven't tested this myself, but this is just a re-formatting of what Johan told me. Also, Johan didn't specify which program was making a USB connection (and I can't find him right now to ask).

**Comment by Xisle** [comment]
See issue #70

**Comment by Ghostkeeper** [comment]
Ah right, duplicate then.
