### ISSUE TITLE
[3.6] Tree supports, normal and interface layers are fused, distance between branches exaggerated

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5112]
**Application Version**
3.6

**Platform**
Win10x64

**Printer**
Custom cr-10s double extrusion

**Steps to Reproduce**
Use tree supports on the following model

**Actual Results**
There basically are 3/4 issues:

1. The branches come in contact, and then one of them disappears, to only reappear at the interface layer. 

2. At that point, that's not only extruded in air, but the normal and the interface layers also fuse together.

3. There is an huge spot where the tree supports don't touch the model. It is even worse because there they lies the "fill small gaps" lines, which are small multiple extrusions which can't just sit into the air like a singular contiguos line would do.

**Expected results**
1. The branches should remain separate
2. The first material support and the second material interface supports shouldn't fuse together, and they shouldn't be extruded in the air.
3. There souldn't be an unsupported spot

**Additional Information**
[Video](https://youtu.be/peGubrGUhXA)
[tree supports.zip](https://github.com/Ultimaker/Cura/files/2727621/tree.supports.zip)

**Comment by Ghostkeeper** [comment]
Fixed this by increasing the default distance between the support branches. I don't think that the branches should remain separate, especially since a small-ish model can easily generate hundreds of branches. The whole point of a tree is that it has splitting branches.
