### ISSUE TITLE
Support Calculation Problems Cura 3.6

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#5117]
Application Version
3.6

Platform
Windows 10

Steps to Reproduce
Open Cura and unhide the Support Z Distance or check the fdmprinter.def.json file

Actual Results
No matter what layer height you use the default Support Z Distance is 0.1mm even though the description says "..This value is rounded up to a multiple of the layer height."

Expected results
The value to be calculated to match it's description.

In fdmprinter.def.json definition file all support values (e.g. support_z_distance,support_top_distance,support_bottom_distance ...) have default values set to 0.1.
Any Printer definition inherited from fdmprinter do not calculate these values, until these are overidden by printer, quality or material definitions.
See in file e.g. um2p_pp_0.4_normal.inst.cfg = "support_z_distance = =layer_height * 2". If layer_height is set to 0.3 than support_z_distance is calculated to 0.6.
In this case I get warning that this value is out of range, because of the entry in fdmprinter.def.json "maximum_value_warning": "machine_nozzle_size"!!! 
(My Nozzle Size is 0.4) On Mastering Cura Web page (https://ultimaker.com/en/resources/21932-mastering-cura) the explanation is not understandable (Cura can either add support on any given layer or not add support. Unfortunately, there are no "half layers of support." So if a 0.3mm Z Distance setting 
for a print with a layer height of 0.15mm is too much, and the Z Distance of 0.15mm is not enough, you're out of Z Distance options). In this example only a value 
of 0.02 is added to layer_height.

In all that confusing explanations can somebody pls. provide a guide or the formulas required for support calculations or a correct explanation.
I have comment same time closed bug report "Support Z Distance not calculated #3157" see for details.

**Comment by hanturk** [comment]
@nallath 
Sorry why you closed query. It's still not understandable. You say "it can either use a z distance of 0, 0.3, 0.6, ..., etc." if I set 0.6 it gives an error because it is out of range of nozzle_diameter of 0.4. In the explanation says "it is multiple of layer_hight" and it's never calculated in fdmprinter.def.json as stated in #3157 .

**Comment by nallath** [comment]
It gives a warning. Not an error. The warnings are just there to tell you that the values you chose seem to be a bit extreme. It doesn't mean that it's impossible to do at all.
