### ISSUE TITLE
[3.6.0 Windows 10] Part Cooling Fan doesn't turn on during print

### ISSUE THREAD

**Issue by mxhffmn** [Ultimaker/Cura#5132]
**Application Version**
CURA 3.6.0

**Platform**
Windows 10

**Printer**
CR-10s

**Steps to Reproduce**
Simply slice a random model and start the print with the settings below

**Actual Results**
The print is carried out as it should be, except for the part cooling fan. The fan is turned off for the whole print although it should start working from layer two on.

**Expected results**
The part cooling fan should start from layer two on. The fan definitely is working because it runs if you turn it on manually.

**Additional Information**
I will attach my current profile and especially the cooling settings.
![cooling_settings](https://user-images.githubusercontent.com/34124907/50789179-cd0ee300-12bb-11e9-9485-43e20171415b.jpg)
[profile.zip](https://github.com/Ultimaker/Cura/files/2734034/profile.zip)

**Comment by smartavionics** [comment]
Hi @maxx2803 , please attach a sample gcode file that shows this problem. Thanks.

**Comment by maxx2803** [comment]
For me it is every G-Code, but here is a sample. Thank you.

[sample.zip](https://github.com/Ultimaker/Cura/files/2735570/sample.zip)

**Comment by maxx2803** [comment]
Update: The issue is resolved now. Changing the G-Code flavor from Makerbot to Marlin did the job..

**Comment by smartavionics** [comment]
Hi @maxx2803 , thanks for the update, sorry I had not got around to responding before.

**Comment by GregValiant** [comment]
Can this be closed?

**Comment by mxhffmn** [comment]
Yes. Thanks for the help!
