### ISSUE TITLE
[3.6.0] Unnecessary Supports on Low Angle

### ISSUE THREAD

**Issue by fdamstra** [Ultimaker/Cura#5134]
**Application Version**
3.6.0

**Platform**
Windows

**Printer**
Tevo Tornado - Custom Profile

**Steps to Reproduce**
All relevant files are in my [shared google drive folder](https://drive.google.com/drive/folders/1lUxa083Bb9mpuW-S_oUFLmWJg5q6xO9P?usp=sharing).
The custom designed "body3.stl" when printed upside down as in the attached "body3.3mf" project, has supports on the outside that are unnecessary given the '50 degree' overhang setting. The angle of the outer wall, while curved, is 73.1 degrees and easily printed without overhangs.

This is using "Draft" setting and clicking "Enable Supports". But seems to persist regardless of what settings I change.

**Actual Results**
Supports are added around the exterior.

**Expected results**
There should be supports around the inner circle, but not around the outside.

**Additional Information**
[Screenshot of Layer View Showing Supports](https://drive.google.com/open?id=1H8unjowapAdHzlt8LxQOl34hT-7hmTqI "Layer View Showing Supports")
[Screenshot of Layer View Showing No Overhang](https://drive.google.com/open?id=1nhDN3jNvHqJZYjJkPD7d1eMDLIlE68BB "Clearer View Showing No Overhang")

**Comment by nallath** [comment]
I've just tried this with the latest & greatest on the 4.0 branch (the code that's going to be the second beta for the 4.0.0 release) and the issue doesn't occur there if I load your project file.
If I set the support overhang angle to 20 degrees it does start trying to support the parts that you indicated.
