### ISSUE TITLE
The font is ugly.

### ISSUE THREAD

**Issue by jockeysoft** [Ultimaker/Cura#5135]
![fankui](https://user-images.githubusercontent.com/22589204/50813539-b3b87600-1351-11e9-8e69-67e4dd2dca60.png)

**Comment by ianpaschal** [comment]
Please fill out the issue template or this issue will be closed.

**Comment by nallath** [comment]
We can already close this, since we just added a fix for the Chinese font looking a bit weird (it also fixes issues with Japanese)
