### ISSUE TITLE
Feature Request: (new setting) Raise model on top of the bed x mm, auto add support between them

### ISSUE THREAD

**Issue by davidngrc** [Ultimaker/Cura#5141]
I try to print this Flexi Tri-atops,
https://www.thingiverse.com/thing:3186616

I have try many times, and the first layer always print too thin.
the top layer looks fine. (see below image)
someone suggest calibrate the extruder, and level the bed.
I try that, it looks better, but the bottom layer still not look as look as the top.

so I was thinking, why not raise the model on top of the print bed, then auto add support in between?
this way, we can have higher tolerance on bed leveling and extruder multiplier.

![too_thin_first_layer](https://user-images.githubusercontent.com/33573086/50875686-7234d300-1404-11e9-9ca5-1ee96ccf5eb8.jpg)

**Comment by nallath** [comment]
That's exactly what raft does.
