### ISSUE TITLE
Wall line spacing broken?

### ISSUE THREAD

**Issue by dgrat** [Ultimaker/Cura#5147]
For nozzles > 0.4mm I get gaps beween my walls and skin/infill. My wall width is correct and matches the nozzle width. I think this might be a bug. Even the preview looks wrong. The higher the wall width, the bigger the gaps :D The prints look like the preview: faulty. I highly suggest to fix this with priority, because it makes CURA basically unusable with nozzles > 0.4mm . 

![grafik](https://user-images.githubusercontent.com/4668178/50985121-d8ece600-1503-11e9-8a5a-8fc761816b8a.png)
![grafik](https://user-images.githubusercontent.com/4668178/50985135-e4401180-1503-11e9-9713-15c6f8e4b047.png)

**Comment by smartavionics** [comment]
Hi @dgrat, please zip up a cura project that has this problem and attach to this issue so it can be investigated. Thanks.

**Comment by dgrat** [comment]
[KPRO_Fantastic Snicket-Hillar(2).zip](https://github.com/Ultimaker/Cura/files/2750443/KPRO_Fantastic.Snicket-Hillar.2.zip)

**Comment by smartavionics** [comment]
Yes, that's right, the flow rate alters the line width. In your project file, the flow was only 80% so that's why it had big gaps between the lines. Cheers!
