### ISSUE TITLE
Arrange All Models when using Support Blocker arranges the support blocker as a separate model

### ISSUE THREAD

**Issue by pfjason** [Ultimaker/Cura#5153]
**Application Version**

3.6.0
**Platform**
Windows 10
**Printer**

Any
**Steps to Reproduce**

Add a block support block to a model that is not centered on the build plate
Click "Arrange All Models"
Observe Result
**Actual Results**
The Block Support block moves in relationship to the model that it was created on

**Expected results**
The "block support" block should keep it's position in relationship to the model 

**Additional Information**
Before
![image](https://user-images.githubusercontent.com/16055757/51074206-25dad480-164a-11e9-8382-33b5289657e1.png)
After
![image](https://user-images.githubusercontent.com/16055757/51074213-34c18700-164a-11e9-9257-36902f4cc7b6.png)

**Comment by rburema** [comment]
Devs: Internal ticket CURA-6120 was made due to this issue.

**Comment by Ellecross** [comment]
Hey @rburema the CURA-6120 is fixed. :D Good work! I just checked it now. 
@pfjason a fix was applied and tested for this issue. This fix will be available in the next Cura 4.0. Thank you for reporting it! Wheeeeee!

**Comment by rburema** [comment]
Should be in 4.0-BETA-2 as well (_should_ be later this month I think) if you want to check and don't want to wait for 4.0 final release (which probably won't be a long wait counting from beta-2, but still).
