### ISSUE TITLE
Fill density issue. I can't print models with 100% Fill density.

### ISSUE THREAD

**Issue by Fossy01** [Ultimaker/Cura#5157]
**Application Version**
Ultimaker Cura 3.6.0

**Platform**
Mac OS High Sierra.

**Steps to Reproduce**
Set 100% in "Fill density", load any model and see it layers.

Hello!!. The issue is that fill density 100% is not really 100%, is about 50% or 60%. I can't print models with 100% filled.

I attached an screen capture.

Thanks!!.
Jose.

![relleno](https://user-images.githubusercontent.com/46638451/51080817-acdb8b80-16e2-11e9-9660-7f5f5e44c02b.jpg)

**Comment by smartavionics** [comment]
Hello @Fossy01 , please save the project (.3mf) file, zip it up and attach to this issue so it can be investigated. Thanks.

**Comment by fieldOfView** [comment]
Can you try 99.9% infill?

**Comment by Vandrasc** [comment]
Hi @Fossy01 , silly question but is it possible that you are customizing the infill of the second extruder and printing the model with 1st extruder instead? Or vice-versa? 

Thanks!

**Comment by Ghostkeeper** [comment]
In theory it'd be 100% infill. In practice, plastic characteristics prevent it from reaching 100%.

You can see it in the screenshot as well. 100% infill is resulting in 1.2mm distance between the lines. With a 0.4mm line width, it fits exactly 3 lines in those 1.2mm. But you have triangle infill, so it's going to create 3 times as many lines. So the total amount of plastic would fill 100% of the infill volume.

To put it in a bit less technical terms, the gaps that you see between the lines have exactly the same area as the overlap between the lines in the crossing points. The amount of material that would be extruded should fill the volume completely, were it not that you'll have more material slip in those overlap areas.

That said, triangle infill is not the best candidate for reaching high infill rates. You're better off using lines infill, which becomes the default if you set the infill rate high enough. But this is working as intended as far as I can see.

**Comment by Fossy01** [comment]
Thanks for all!!.

I will use Lines instead Triangles with 0.4mm line width. Understand perfectly Ghostkeeper!.

Thanks!!.
