### ISSUE TITLE
Artifacts in/on Part

### ISSUE THREAD

**Issue by tukbuk23** [Ultimaker/Cura#5159]
**Application Version**
4.0.0. Also occurs in 3.6.0.

**Platform**
Windows 10 x64.

**Printer**
Monoprice Select Mini v1.
[MSMV1_keycap.3mf.zip](https://github.com/Ultimaker/Cura/files/2753372/MSMV1_keycap.3mf.zip)

**Steps to Reproduce**
1. Open attached project file.
2. Slice and open layer view (preview).

**Actual Results**
Artifacts appear on the part walls even though part is smooth. 

**Expected results**
Part walls should consist of smooth lines.

**Additional Information**
See attached screenshot.
![image](https://user-images.githubusercontent.com/6304678/51089365-e8ee0b00-1739-11e9-990b-64a18d04af6b.png)

**Comment by smartavionics** [comment]
Turn off coasting.

**Comment by tukbuk23** [comment]
That fixed it. Many thanks!
