### ISSUE TITLE
global settings vs machine-local setting visibility

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#516]
When I goto [ Settings ] > [ Preferences ] I expect to find all global settings and not settings specific to the current setup.

However, when I change the machine to a multi-extrusion machine then the settings under [ Setting Visibility ] are different.

If the settings are machine-specific, I would think they should be accessed via [Settings] > [Preferences] > [Setting Visibility] > [MACHINE] > .... actual list of settings with checkboxes

Is this a UX bug?

**Comment by BagelOrb** [comment]
The settings visibility in the preferences should either be categorized under a machine selection dropbox or hold for all printers the same.

**Comment by Ghostkeeper** [comment]
The settings visibility list is the same for every machine, right? What is different?

**Comment by BagelOrb** [comment]
Errr yes. Mindfuck here!

**Comment by BagelOrb** [comment]
This is not an issue. Sorry to have opened it in the first place.
