### ISSUE TITLE
Only first model piece is getting updated after multiply and reload (due to change of STL)

### ISSUE THREAD

**Issue by TangoTom** [Ultimaker/Cura#5160]
**Application Version**

3.5.1

**Platform**

Linux

**Printer**

ANET A8

**Steps to Reproduce**

1. Load STL.
2. Multiply it.
3. Change STL and accept reload.

**Actual Results**

Only the fist piece is changed. All multiplications stay the same.

**Expected results**

All pieces should be updated.

**Additional Information**

**Comment by rburema** [comment]
Tested this with 4.0-BETA-1 and this behaviour doesn't occur there. Feel free to reopen if you disagree (but please explain why in that case).
