### ISSUE TITLE
[4.0.0 BETA] Fullscreen stops top menus from working

### ISSUE THREAD

**Issue by frank26080115** [Ultimaker/Cura#5161]
**Application Version**
4.0.0 BETA

**Platform**
Windows 10 Pro 64 bit
Nvidia GTX 970, 4GB of graphic RAM, driver version 23.21.13.8813

**Steps to Reproduce**
Enable full screen mode from the View menu
Once the full screen mode has been entered, try clicking on any of the menu items, such as View, or try right clicking anywhere for the context menu

**Actual Results**
Screen blinks black for a brief moment, and the menu may or may not appear

Applies to both the top menu bar and right click context menus

**Expected results**
The screen does not blink, the menu always appears

**Additional Information**
I am forced to use F11 to exit fullscreen mode

**Comment by Jockebanan** [comment]
I have the same problem, no drop downs on menus and no right click.
Win10 Home 64 bit.
F11 don't work to get out of full screen, only to get to full screen (it works on other programs though)

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
