### ISSUE TITLE
[Cura 4.0.0 Beta] Post Processing Scripts windows bug

### ISSUE THREAD

**Issue by Robyrob** [Ultimaker/Cura#5168]
**Application Version**
Cura 4.0.0 Beta

**Platform**
Windows 10 Home  64bit

**Steps to Reproduce**
Open Cura 4.0.0-Beta
Open Extensions --> Post Processing --> Modify G-Code
Add a script and select any script

**Actual Results**
The post processing icon is over the word "Post...!
In the right window with script settings words are cut

**Expected results**
The post processing icon should be down right near "Save to file"
In the right window I should read read all the settings

![cattura](https://user-images.githubusercontent.com/19575380/51117642-ae09d700-180e-11e9-90c1-e55f4c092b2b.JPG)
 should be readable

**Additional Information**

**Comment by fieldOfView** [comment]
Thanks for reporting. Both issues have already been fixed for the next beta release.
