### ISSUE TITLE
[Settings] vs. [Preferences]

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#517]
Currently the only place where the Preferences window can be accessed is via the [Settings] menu bar item,
while the Preferences window again contains a tab for [Settings].

This is quite confusing.

Please put the the Preferences menu item under [edit](and remove the Settings menu bar item altogether) or rename the Settings menu bar item to something different.

**Comment by Ghostkeeper** [comment]
I'm voting for renaming the Settings menu bar item to Preferences, though I can't currently see the menu bar at all.

**Comment by BagelOrb** [comment]
But then it would be 
```
[ Preferences    ]
[ Preferences... ]
```
which seems a bit ugly

**Comment by mpbomil** [comment]
You could rename the "Settings" tab in preferences to "Print" or "Printer", since it contains settings for the printer

**Comment by BagelOrb** [comment]
The preferences also cover general preferences, view preferences and plugin preferences...

**Comment by fieldOfView** [comment]
In Cura 2.3 (and beyond) the chosen solution is Preferences -> Configure Cura... -> Settings

This can be closed
