### ISSUE TITLE
Seam indent where the print starts at each layer in the same exact spot

### ISSUE THREAD

**Issue by ahowansky** [Ultimaker/Cura#5170]
wheel not round - gcode produces bad part - I have a part that is small about 1/2 inch in diameter. I try to print it and it has a continuous seam indent where the print starts at each layer in the same exact spot. Is there a way to offset the start location for each layer so there is no continuous indent?
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smartavionics** [comment]
> Is there a way to offset the start location for each layer so there is no continuous indent?

Use the random z-seam alignment setting, that should give you what you want.

**Comment by rburema** [comment]
I'm closing this issue. Feel free to reopen if you feel your complaint was not adressed properly.
