### ISSUE TITLE
[3.6.0] High CPU usage on idle

### ISSUE THREAD

**Issue by crazzzik** [Ultimaker/Cura#5192]
**Application Version**
[3.6.0]

**Platform**
Windows 10

**Printer**
Prusa i3 over Octopi

**Steps to Reproduce**
-Start application
-Add model
-Send Print
-Wait until print finished
-Observer CPU usage

**Actual Results**
Cura uses between between 14% and 40% CPU doing nothing on Prepare, Monitor or even background.

**Expected results**
Expected to go to idle CPU consumption (0-2%)

**Additional Information**

![image](https://user-images.githubusercontent.com/5152586/51350436-2920f680-1a76-11e9-8453-1d3a7fc8c2be.png)

Logs:
https://we.tl/t-lHoqYvrKEh

**Comment by smartavionics** [comment]
There was a recent issue where the engine would sit using 100% CPU after cura started. Once the first slice had been done, the CPU usage dropped to 0 (in the engine). Maybe it is that you are seeing. Currently, on a Linux cura, the idle CPU usage is low unless I waggle the mouse around over the cura window when it uses more.

**Comment by nallath** [comment]
This issue has been fixed in the meantime.

**Comment by Venryx** [comment]
In Cura 4.9.0, I'm still noticing a 5-6% continuous CPU usage, even when Cura is without a loaded model + defocused + minimized.

Not as bad as 30%, but a 5% continuous load when it should be ~0% is still worth fixing. (and my processor is 8-core, 16-thread, so it's actually using half a core for doing nothing [or at least it should be])
