### ISSUE TITLE
4.0-BETA: UX bug: Unclear that printer is not connected

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#5193]
**Application Version**
4.0.0-BETA

**Platform**
Linux Mint

**Printer**
UM3

**Steps to Reproduce**
Add printer over one WiFi
Switch to another WiFi (My WiFi automatically switches to a public WiFi when I leave the area of the 3D printing lab)
Change printing material

**Actual Results**
Unclarity about syncing with printer

**Expected results**
Cura somehow informs me that it cannot connect to a network connected printer.

Cura already knows that the printer *should* be connected:
![image](https://user-images.githubusercontent.com/8895761/51381966-d860da80-1b15-11e9-99c5-6255d44a28e0.png)
so it makes sense to me to communicate to the user that there is something wrong with the connection.

For example:
![image](https://user-images.githubusercontent.com/8895761/51382111-34c3fa00-1b16-11e9-89a7-7fed9f3ecfaa.png)

**Additional Information**
After not using Cura for a while I came back to Cura and changed some materials around and then I wanted to change back to the actual material and start a print, but there was no option to sync materials.

I've experienced this multiple times with earlier versions as well.
I then wonder: "Is the material syncing functionality broken?" "Is it moved somewhere else?" "Why can't I sync materials?" "Why can't I start a print?" "Is it defaulting back to USB stick saving for some reason?"

These thoughts could be avoided if the broken link to the printer is clearly communicated.

**Comment by nallath** [comment]
This has been implemented some time ago.
