### ISSUE TITLE
[4.0.0 Beta]  just 2x plugins

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#5197]
**Application Version**
4.0.0.Beta

**Platform**
macOS 10.11.6 El Capitan
**Printer**
Ultimaker Orignal
**Steps to Reproduce**
Go to Marketplace
**Actual Results**
Only 2x items in Plugins
**Expected results**
More plugins
**Additional Information**
Clean install of macOS, I get full list of plugins on the machine which had 3.6 before - although that machine is on 10.14.2 so not really apples to apples comparison.

![screen shot 2019-01-19 at 11 15 26](https://user-images.githubusercontent.com/5671041/51426051-dca3fb00-1bdc-11e9-9fd5-8296a31f0d6e.png)

**Comment by ChrisTerBeke** [comment]
This is expected. Other plugin developers still need to make their plugins compatible with the new version and then publish them in the Marketplace. This typically happens during the Beta period for most plugins.

**Comment by fieldOfView** [comment]
That's not quite the full story. For completeness, there's an issue with the Marketplace, where there's no way to publish a plugin that works with Cura 4.0 beta 1 without unpublishing the version for Cura 3.6. This is why most plugin authors are not yet publishing their updated plugins. Cura 4.0 beta 2 will have a mechanism to allow plugins to work with both Cura 3.6 and Cura 4.0, so most plugins should become available when Ciura 4.0 beta 2 launches.
