### ISSUE TITLE
No Infill rendering in Layer View

### ISSUE THREAD

**Issue by awhiemstra** [Ultimaker/Cura#52]
Application Version: 15.05.94
Platform: ArchLinux 64-bit
Qt: 5.4.2
PyQt: 5.4.2
Video Driver: xf86-video-intel 2.99.917

Steps to Reproduce:
* Load a model.
* Wait for it to slice.
* Go to Layer view.
* Scroll down a few layers to see the infill of the model.

Actual Results:
* Nothing is visible from the inside structure of the model.

Expected results:
* Infill structure is made visible for a few layers.

**Comment by zews39** [comment]
In 15.06.03 no infill in Layers view, and no printing of infill either. This makes this version of Cura not  fit for use.
