### ISSUE TITLE
[4.0 beta] Z offset missing

### ISSUE THREAD

**Issue by RickBlan** [Ultimaker/Cura#5201]
**Application Version**
4.0 beta
**Platform**
windows 10
**Printer**
Ender 3
**Steps to Reproduce**
Could not find the Z Offset setting at all. Search for "offset" did not find it either.
**Actual Results**
Not found
**Expected results**
Was there in 3.6
**Additional Information**
No file was loaded. Just opened the app and looked for the setting.

**Comment by fieldOfView** [comment]
Z Offset relies on a plugin (from the Marketplace) which will not be available until Cura 4.0 beta 2
