### ISSUE TITLE
One-at-a-time prime blob

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#5205]
**Application Version**
Cura 4.0.0 BETA

**Platform**
Linux MInt

**Printer**
UM3

**Steps to Reproduce**
Disable second extruder
(Load TPU on first extruder? Not sure if required.)
load multiple objects
Set print sequence to one-at-a-time

**Actual Results**
Prime blob is on same location each print, which makes the prints fail.

**Expected results**
Prime blobs are at different locations,
or brime blobs are automatically disabled

**Additional Information**
See project file; 
[UM3_hark_overlaps.3mf.remove.zip](https://github.com/Ultimaker/Cura/files/2779961/UM3_hark_overlaps.3mf.remove.zip)

**Comment by Vandrasc** [comment]
Fixed for the next release.
