### ISSUE TITLE
Add layer time and fans peed per layer to layerview 

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#5206]
Hi! Can you add info for layer like in the pic, layer time and speed fan into layer.
![default](https://user-images.githubusercontent.com/22872748/51497460-3fabb280-1dd4-11e9-88a0-d3716cb049eb.png)

**Comment by Ghostkeeper** [comment]
Fan speed is not the same for an entire layer. Due to bridging you can have different fan speeds in different parts of the layer. So that one is impossible unless implemented with a colour scheme.

Layer time could be done. But what are you going to do with that information? Or is it just out of interest?

**Comment by userosos** [comment]
@Ghostkeeper Will be good if the can edit. You can do that the parameter depends on the position of the hot end (in picture) in Cura. If it difficult you can do it for only information. 
![изображение](https://user-images.githubusercontent.com/22872748/54670838-9a783680-4b05-11e9-842a-a3a940b2241a.png)
![изображение](https://user-images.githubusercontent.com/22872748/54670899-bd0a4f80-4b05-11e9-8ce5-ace3be2cdd5a.png)
I think that can add more options for singl layer or range layers like the pic:
![изображение](https://user-images.githubusercontent.com/22872748/54671228-8bde4f00-4b06-11e9-90ec-511e8af99c1b.png)
I think that it will be good options.
Here you can add the whole range of possible settings already available in Cura. It also makes sense to create groups of such presets.

**Comment by Ghostkeeper** [comment]
I think that a colour scheme like is currently used for feedrate would make more sense than a label there.

**Comment by Ghostkeeper** [comment]
Oh, you wanted to be able to edit it as well? That requires a lot more thought for the UI then.

**Comment by userosos** [comment]
> Oh, you wanted to be able to edit it as well? That requires a lot more thought for the UI then.
It will be good. You can do info, now. But in the future it is better to edit it. It will be good!
