### ISSUE TITLE
Cura 4.0.0 beta - Z Seam Relative not correctly working

### ISSUE THREAD

**Issue by amagr0** [Ultimaker/Cura#5209]
**Application Version** - CURA 4.0.0 beta
**Platform** - Win 10 Pro, 64 bit
**Display Driver** - NVIDIA GeForce 840M

**Steps to Reproduce** - Open Cura Project; Slice; analyse the toolpath.

**Actual Results** - Different Z seam alignment on parts.

![image](https://user-images.githubusercontent.com/12901952/51532139-44ee1900-1e37-11e9-9859-6225beb51250.png)

[z_seam_aligm.zip](https://github.com/Ultimaker/Cura/files/2782526/z_seam_aligm.zip)

**Comment by smartavionics** [comment]
Hello @amagr0 , please provide the project file that includes the settings and not just the model. Thanks.

**Comment by smartavionics** [comment]
Ah, I think I know what is happening. Those 6 items have been grouped into a single mesh so the z-seam is relative to the whole bounding box and not the bounding boxes of the individual parts. You need to ungroup them.

**Comment by amagr0** [comment]
Hi @smartavionics,
By mistake I exported the model, and not the project.
I normally use Netfabb to organize multiple parts that could be till 100 by bed, Cura is not so effective to deal with so many parts, and then I export a single stl file to Cura with all the parts.

I will start to export in 3mf format, this seems to solve this problem.
![image](https://user-images.githubusercontent.com/12901952/51541254-47a93800-1e50-11e9-844b-88a31367902c.png)

[Proj_z_seam_aligm_3MF.zip](https://github.com/Ultimaker/Cura/files/2783122/Proj_z_seam_aligm_3MF.zip)


Thanks

**Comment by smartavionics** [comment]
That looks better, please close this issue if you are now happy.
