### ISSUE TITLE
Math in Start / End GCode

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#5211]
Hi guys,

Is there a document on what settings variables are accessible in the start / end gcode, and whether/how math is supported?

A similar line of code works fine in Slic3r, but does not post code correctly in Cura:

M104 S{material_print_temperature_layer_0 - 40}

**Comment by fieldOfView** [comment]
If you have no further questions, please close the issue.

**Comment by mydevpeeps** [comment]
Sorry for commenting on a closed issue, but, shouldn't this have been ported to an Enhancement Request?
