### ISSUE TITLE
Poor graphics display

### ISSUE THREAD

**Issue by handyandyS3** [Ultimaker/Cura#5220]
**Application Version**

3.6
**Platform**

Window 10
**Printer**

Original Prusa Mk3
**Steps to Reproduce**

Load a model
**Actual Results**

Very poor graphics on the part - very much like 'moire' on a TV. Slic3rPE does a much better display!
**Expected results**

?
**Additional Information**

![image](https://user-images.githubusercontent.com/34400691/51760372-36fff880-20c2-11e9-9257-1972fa2afa50.png)

**Comment by Thisismydigitalself** [comment]
https://github.com/Ultimaker/Cura/issues/3313

**Comment by nallath** [comment]
Closing because it's a duplicate.
