### ISSUE TITLE
[3.6] Tree Supports cross the model and go inside

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5223]
**Application Version**
3.6

**Platform**
Win10 x64

**Printer**
Custom dual extrusion

**Steps to Reproduce**
Load the project

**Actual Results**
The infill goes into the model

**Expected results**
The infill should be separated from the model

**Additional Information**
![supports in a model](https://user-images.githubusercontent.com/20385116/51778065-41d97e00-2100-11e9-8f07-28aba8f8e086.png)
[supports in a model.zip](https://github.com/Ultimaker/Cura/files/2798232/supports.in.a.model.zip)

**Comment by smartavionics** [comment]
I could not import your settings from the project because the printer was unknown to my cura. I did get the model which sliced OK using my settings. Could you please provide another project that has this problem and uses a known printer type. Thanks.

![screenshot_2019-01-26_07-48-28](https://user-images.githubusercontent.com/585618/51784332-f85c5380-213e-11e9-8c19-ce982a351f69.png)

**Comment by Liger0** [comment]
> 
> 
> I could not import your settings from the project because the printer was unknown to my cura. I did get the model which sliced OK using my settings. Could you please provide another project that has this problem and uses a known printer type. Thanks.
> 
> ![screenshot_2019-01-26_07-48-28](https://user-images.githubusercontent.com/585618/51784332-f85c5380-213e-11e9-8c19-ce982a351f69.png)

Could you try with a double extrusion 1.75 filament? nozzle distance is 30mm.
Mine is a modded cr-10s with double extrusion definition.

**Comment by smartavionics** [comment]
Even with tree supports enabled, I do not get this problem. Does it only happen with tree supports?

**Comment by Liger0** [comment]
> 
> 
> Even with tree supports enabled, I do not get this problem. Does it only happen with tree supports?

Yes.

**Comment by Ghostkeeper** [comment]
I'm also unable to reproduce this on a different multi-extrusion printer (UM3). I tried setting the support extruder to something else than the build extruder, and setting both extruders to the same extruder. I couldn't get the support to clip the model.

And I tried setting the filament diameter to 1.75 in Custom FFF Printer but that obviously didn't make any difference to layer view.

**Comment by Liger0** [comment]
It still happens on cura 4.0.
I have saved the project file but I can't share it publically because it's not a public stl, so let me know how can I share it to you. It happens along with a strange point where the tree supports starts in the air.
This time I just used a basic custom dual extrusion machine done directly by Cura itself and a new profile, so everything is fresh, and the bug persists.
![supports inside the model](https://user-images.githubusercontent.com/20385116/55444405-97c21a80-55b6-11e9-81dc-ec9b235adebe.png)
![tree support starts in air](https://user-images.githubusercontent.com/20385116/55444406-985ab100-55b6-11e9-9c28-36e018cfb27a.png)

**Comment by Ghostkeeper** [comment]
You could send a project file to me on r.dulek at ultimaker.com. I swear to share it only with colleagues working on Cura, and only for debugging purposes!

**Comment by Liger0** [comment]
> 
> 
> You could send a project file to me on r.dulek at ultimaker.com. I swear to share it only with colleagues working on Cura, and only for debugging purposes!

I tried to sent you a message: "r.dulek cannot receive messages."

**Comment by Ghostkeeper** [comment]
Oh, eeh, that is a serious concern if I can't receive messages from outside then. I'll have IT look into this. You can try to send it to my personal one at rubend at tutanota.com then.

**Comment by Liger0** [comment]
> 
> 
> Oh, eeh, that is a serious concern if I can't receive messages from outside then. I'll have IT look into this.
> 
> EDIT: I can send e-mails from my personal account to my work account. I think you may have typed some e-mail address wrong then?

I just used the function to send a message to a user using the nickname.

**Comment by Ghostkeeper** [comment]
You can send PMs to people in Github? I didn't know that and I can't find it. Please use e-mail instead.

**Comment by Liger0** [comment]
> 
> 
> You can send PMs to people in Github? I didn't know that and I can't find it. Please use e-mail instead.

I was referring to Ultimaker forum. How can I send you an e-mail?

**Comment by Ghostkeeper** [comment]
Ah, I understand the mistake. r.dulek at ultimaker.com was meant to be my e-mail, not my Ultimaker forum username. My username on the Ultimaker forum is also Ghostkeeper. Either one works.

**Comment by Liger0** [comment]
I didn't know a name without the @something.something would be an email. By the way, I've sent the message.

**Comment by Ghostkeeper** [comment]
The issue is reproduced with this project file. Strange how the support does have a proper border on the inside but the infill lines don't stop there.

**Comment by Liger0** [comment]
The dot on the bottom in the air is also something I noticed very frequently with cura 4.0

**Comment by Ellecross** [comment]
Devs see CURA-6465.

**Comment by Liger0** [comment]
Any update?

**Comment by Ghostkeeper** [comment]
Nothing changed recently in this ticket, no. Sorry. It's still on the ToDo list.

**Comment by Lieste** [comment]
I had this recently with a model, it happened at the layer where the tree supports completely wrapped the model, and lasted for the height where the ring was complete. I had a properly formed ring of infilled support, as well as an additional disk with infill.
If I slightly reduced the tree support branch angle, the ring opened and the support didn't cross into the model, but I also lost supports over around half the target overhangs... https://www.myminifactory.com/object/3d-print-spring-frost-101774 set to 355mm high, supports touching base, I only get supports reaching the buttock overhang at support branch angle =55 not at 50. At 55, I get the failure at layer ~1210 (0.2mm) where the ring of tree supports forms a complete circle, and the infill covers the outer ring completely, instead of only the portion between inner and outer walls.

**Comment by nallath** [comment]
This has been fixed for 4.7
