### ISSUE TITLE
[3.6] [4.0 beta] Too big brim width will crash the app

### ISSUE THREAD

**Issue by jatson** [Ultimaker/Cura#5225]
**Application Version**
3.6 or 4.0 beta

**Platform**
Windows 10

**Printer**
Anet E10

**Steps to Reproduce**
You can try to type any bigger number into the brim width cell. For e.g. 400mm will do the job

**Actual Results**
in case of 3.6 the app is crashing totally.
in case of 4.0 beta, the will give you crash report and after closing

**Expected results**
I would expect some message or cell highlight due to the wrong settings

**Additional Information**
The problematic input field is showing in the picture bellow
![capture](https://user-images.githubusercontent.com/3874067/51786316-c65ce880-2162-11e9-8c56-9ce4cf8a73a7.PNG)

**Comment by Vandrasc** [comment]
Hi @jatson, this is already fixed in the second beta 4.0. 

Thank you for your feedback!
