### ISSUE TITLE
Closing after saving

### ISSUE THREAD

**Issue by Delt4Squad** [Ultimaker/Cura#5237]
After setting the printing parameters and preparing the part, when I want to save it (with the media and printing parameters) in STL or GCODE, in both cases, the software crashes and the file it created contains barely 1/10 of the part (contains very few layers on the total number). Could you please help me, I checked the settings several times and it's only on my PC that it doesn't work (I tried with the same settings but on another PC and the result is perfect). 
Sincerely.

**Application Version**
Cura 3.6.0

**Platform**
Windows x64

**Printer**
Creality CR-10

**Comment by Ghostkeeper** [comment]
There are three things that could help us reproduce/solve your problem:
1. The logs (`C:\Users\<your username>\AppData\Roaming\cura\3.6\cura.log`). The issue template actually asks for this 
2. A project file (in Cura go to File -> Save... and attach that file on github.com to the issue; e-mail attachments don't work).
3. The entire Cura configuration folder (`C:\Users\<your username>\AppData\Roaming\cura\3.6`). Probably not necessary but we might ask it from you if we can't reproduce the problem with just the project file.

The issue template actually asks for 1. and 2. but you ignored that it seems.

**Comment by Delt4Squad** [comment]
- This is the file "Cura.log". The last time I used Cura, I tried to save a part in GCODE format and the same problem occured :
[cura.log](https://github.com/Ultimaker/Cura/files/2808959/cura.log)


- When I save a project file, the 3mf file is 0 bytes and Cura stops during the backup.


- And there is the file "3.6", with all configuration :
[3.6.zip](https://github.com/Ultimaker/Cura/files/2809035/3.6.zip)


Thank you in advance for your help !

**Comment by Delt4Squad** [comment]
And I've tested with other identical PC and I've a same problems (the file work with other different PC) : 
![capture](https://user-images.githubusercontent.com/29871736/51930510-135aec00-23fb-11e9-9ee5-b122777a792d.PNG)

**Comment by Ghostkeeper** [comment]
Ah, well there is a workaround in this case: Go to the preferences and disable the preference: "Send (anonymous) print information". You will then no longer help the Cura developers with providing statistics on the sorts of prints you're making, but it will not crash.

This was a bug in Qt that we've been unable to reproduce on this side. It happens only on some computers apparently, but we don't have those computers here. Also, we can't upgrade our Qt version unless we drop support for a pretty common MacOS version from 2011 so it's hard to get a version with a fix if Qt would fix it.

**Comment by Delt4Squad** [comment]
Thank you very much, the software works perfectly now !
