### ISSUE TITLE
[15.09.91] Only retraction settings show in Material section

### ISSUE THREAD

**Issue by DexCisco** [Ultimaker/Cura#524]
I have checked off all of the options in the material section of the settings visibility preferences, but nothing above enable retraction is showing.  e.g. Temps, diameter, flow.

**Comment by DexCisco** [comment]
After disabling all the shown settings, the material section says "4 hidden settings use custom values".  I assume that this is the UM2 profile overriding the settings because using a different printer profile shows those settings.  So these settings are not adjustable for the UM2?

**Comment by awhiemstra** [comment]
Material settings are handled by the printer on the UM2. Cura does not allow overriding the material settings when using an UM2. The "X hidden settings use customised values" message should not be shown though, so that part is a bug.

**Comment by EldRick** [comment]
This also gets pretty screwed up when selecting a Prusa printer profile, with the Bed Temp option vanishing after first use.
