### ISSUE TITLE
[Cura 4.0.0-BETA] add a global "[x] Do not warn about unknown materials" setting

### ISSUE THREAD

**Issue by MoonCactus** [Ultimaker/Cura#5250]
Cura 4.0.0-BETA / ubuntu18.04.1 LTS / UM3
+ print over network

I really wish there was a "global setting" somewhere to avoid all the annoying "unknown material" warnings when I am using third party filament. Something like:

`[x] Do not warn about unknown materials`

If the printer cannot detect the filament it should not try to outsmart itself: the printer does too much to "protect the user" here, and it ends up annoying him a lot IMHO. When someone already uses a third-party filament, he already knows very well it is unknown and that the printer will not be able to recognize it... So a simple "by the way" warning would be well enough in the overall slicing/printing process.

Now, if and only if I had loaded a filament that the printer recognizes (NFC) **and** if I was not selecting the proper filament in the interface, then I would expect and welcome the existing "serious" warnings.

**Comment by nallath** [comment]
With the new firmware upgrades, you will be able to select synchronized materials on the machine (even if those materials don't have NFC). So you will just have to wait until that is released.
