### ISSUE TITLE
[Cura 4.0.0-BETA] Override config changes has no effect in app Monitor (contrary to Cura Connect)

### ISSUE THREAD

**Issue by MoonCactus** [Ultimaker/Cura#5251]
**Application Version**
Cura 4.0.0-BETA

**Platform**
Xubuntu 18.04.1 LTS (Bionic Beaver)

**Printer**
UM3

**Steps to Reproduce**

Start a job with an "unknown" filament that was loaded manually (no NFC, that was loaded as "PLA" manually)
Slice and try to print remotely from Cura 4
Cura "MONITOR" panel tells that it "Requires configuration changes"
Click "Details" button
Click the "Override" button of the corresponding button
It has no effect

![confirm_no_effect](https://user-images.githubusercontent.com/1990793/52009876-491fd380-24d4-11e9-8dd1-0d05df5c9995.png)

**BUT**

Go to Cura Connect
You are being told about the same issue
But there you can proceed!

![confirm_has_effect](https://user-images.githubusercontent.com/1990793/52009867-41f8c580-24d4-11e9-9a8c-e35c6a92013e.png)

**Comment by Ghostkeeper** [comment]
Apparently none of the posting API calls work right now from the entire monitor. We're working on it.

**Comment by MoonCactus** [comment]
I was able to override the config in Cura 4.0.0 for the last weeks, maybe this issue was addressed & can be closed?

**Comment by Ghostkeeper** [comment]
Yup, I believe this was fixed. Thanks for re-testing!
