### ISSUE TITLE
[15.09.91] just crash

### ISSUE THREAD

**Issue by robomaniac** [Ultimaker/Cura#526]
So, I just downloaded 15.09.91 and it crash.

![15 91](https://cloud.githubusercontent.com/assets/5814871/10864221/886c4cb8-7fbd-11e5-81b6-29cc69e4e1f0.png)

I uninstall and reinstall same problem.

**Comment by robomaniac** [comment]
Calling engine with: ['C:\\Program Files\\Cura 15.09\\CuraEngine.exe', 'connect', '127.0.0.1:49674', '-j', 'C:\\Program Files\\Cura 15.09\\resources\\machines\\fdmprinter.json', '-vv']

Cura_SteamEngine version DEV
Copyright (C) 2014 David Braam

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
Loading polygon setting machine_disallowed_areas not implemented...
Unrecognized data type in JSON: machine_platform_offset has type array
Loading polygon setting machine_head_polygon not implemented...
Loading polygon setting machine_head_with_fans_polygon not implemented...

**Comment by robomaniac** [comment]
installed 15.09.90 and I can now print.

**Comment by BagelOrb** [comment]
fixed for next release
