### ISSUE TITLE
DuetRRFPlugin not able to configure

### ISSUE THREAD

**Issue by tvannieuwenhuizen** [Ultimaker/Cura#5262]
**Application Version**
Cura 4.0 Beta

**Platform**
Windows 10 / 64 Build 18323.19h1
**Printer**
Duet3D equipped FDM printer

**Steps to Reproduce**
Marketplace; DuetRRFPlugin v1.02 > install plugin.
Quit Cura and restart.

**Actual Results**
No Extension added to the Extensions dropdown
**Expected results**
The DuetRRFPlugin added to the Extensions dropdown

**Additional Information**
Does / did work in Cura version 3.6

**Comment by fieldOfView** [comment]
The DuetRRFPlugin issue gueue is here:
https://github.com/Kriechi/Cura-DuetRRFPlugin/issues

**Comment by Kriechi** [comment]
Thanks for reporting this @tvannieuwenhuizen - please use the [correct repository](https://github.com/Kriechi/Cura-DuetRRFPlugin/issues) in the future.
I'm not monitoring the main Cura issues.

Cura log indicates a problem with the API versioning:
`UM.PluginRegistry.loadPlugin [410]: Plugin [DuetRRFPlugin] with API version [5.0.0] is incompatible with the current API version [6.0.0].`

I submitted a new version for review.
This issue can be closed.
