### ISSUE TITLE
Fan control is not working correctly

### ISSUE THREAD

**Issue by EldRick** [Ultimaker/Cura#527]
Using 9.11, the cooling fans are not behaving correctly with UM2. 
If I set Full on 20% at layer 3, I get 1% at layer 2 and 2% at layer 3. I can only get fan control to work correctly by selecting Prusa as the printer type, instead of UM2.
When selecting Prusa as a printer type, M109 and M104 commands are used, and don't wait for temp to come up to setpoint.
Here are the settings with UM2 selected:
[general]
version = 1
name = Low Quality (Customised)

[settings]
speed_topbottom = 15
cool_min_layer_time = 11
skirt_line_count = 2
magic_fuzzy_skin_enabled = True
infill_sparse_combine = 2
magic_fuzzy_skin_point_dist = .7
layer_height_0 = 0.25
line_width = 0.625
shell_thickness = 2.5
speed_slowdown_layers = 3
infill_sparse_density = 40
speed_layer_0 = 20
bottom_layers = 10
print_sequence = one_at_a_time
infill_line_width = 0.6
coasting_enable = True
z_seam_type = random
cool_min_speed = 5
cool_fan_full_layer = 4
speed_travel = 180
skin_line_width = 0.6
layer_height = 0.25
support_enable = False
cool_fan_speed = 20
speed_print = 30
retraction_enable = False
top_layers = 10
magic_fuzzy_skin_thickness = .4

**Comment by BagelOrb** [comment]
I think this was fixed quite a while ago
