### ISSUE TITLE
build plate adhesion settings in simple menu

### ISSUE THREAD

**Issue by nbennett1978** [Ultimaker/Cura#5274]
**Application Version**
3.6

**Platform**
windows 10 

**Printer**
alya3dp
**Steps to Reproduce**
load any stl, go to simple settings, deactivate "build plate adhesion" checkbox, and re-activate
**Actual Results**
this causes it to use brim from adhesion
**Expected results**
i expect it to return to standard settings, which is a raft in this case
**Additional Information**

**Comment by Vandrasc** [comment]
The fix will be present in the next 4.2 release, CURA-6182 for our reference. 

Thank you for your feedback @nbennett1978 !
