### ISSUE TITLE
Model gets filled completely with skin

### ISSUE THREAD

**Issue by AndreKR** [Ultimaker/Cura#5277]
Here are two models, sliced together with the same settings:

![image](https://user-images.githubusercontent.com/1188538/52314567-89d78b00-29b3-11e9-902b-ef3ec070585e.png)

As you can see, the one on the left has a bottom and then the infill starts, as expected.

But the one on the right is filled completely with top/bottom lines.

This is more obvious when I hide the infill in the "Color scheme" box:

![image](https://user-images.githubusercontent.com/1188538/52314657-f3579980-29b3-11e9-9f42-c5c83a594dc3.png)

My screenshot shows a certain layer, but the model on the right is much higher than that layer, so this cannot be the top skin.

Any ideas what might be going on?

**Comment by Ghostkeeper** [comment]
Hopefully the next release is going to connect these gap pieces better. But yeah this is expected behaviour.

Normally there would be another inner wall there.
