### ISSUE TITLE
Show current phase in LCD

### ISSUE THREAD

**Issue by guestisp** [Ultimaker/Cura#5281]
With marlin firmware is possible to set custom LCD text with command `M117`

Would be possible to automatically add, in gcodes, the current phase being run, like:

`M117 Printing raft...`
`M117 Printing layer1...`

and so on ?

**Comment by nallath** [comment]
There is a post-processing script for that. You can find it under extensions -> post-processing.

**Comment by Ghostkeeper** [comment]
The post-processing script doesn't display that it's working on the raft but only displays layer -3 or so.
