### ISSUE TITLE
post processing plugin bugs

### ISSUE THREAD

**Issue by sim31r** [Ultimaker/Cura#5284]
**Application Version**
ver 3.6.99 (beta)

**Platform**
Windows 7 

**Printer**
Prusa i3

**Steps to Reproduce**
Post pocessing plugin
layer 0, flow 120% (keep value)
layer 10, flow 100% (keep value)
export to .gcode
try to print or read gcode

**Actual Results**
...
M117 Printing....
G92 E0
G1 F3600 E-1
;LAYER_COUNT:64

;LAYER:0
M106 S127.5
M204 S300
G0 F1200 X48.099 Y77.039 Z0.0 ;adjusted by z offset
G92 Z0.3 ;consider this the original z before offset
;ChangeAtZ V5.1.1: executed at Layer 0
M117 Printing... ch@L   0
M221 S120.000000
;ChangeAtZ V5.1.1: reset below Layer 0
M221 S-1.000000 (!!!!!!!!!!!!!!!!!!!!!!!!!!!!)
;TYPE:SKIRT
G1 F3600 E0.08315
G1 F2400 X49.219 Y76.401 E0.17961
G1 X49.74 Y76.147 E0.22299
G1 X51.087 Y75.595 E0.33193

FLOW RATE -1 (!)
gcode work, if I am remove this string manually
M221 S-1.000000

**Comment by nallath** [comment]
Sorry for not getting back to you earlier, but it has been fixed for 4.1 final
