### ISSUE TITLE
No RepRap printer type as in earlier versions

### ISSUE THREAD

**Issue by EldRick** [Ultimaker/Cura#529]
Two aspects:
- there needs to be a RepRap printer type, to generate non-Ultigcode, as in earlier versions. One requirement is the ability to specify gcode pre- and post-print, as in earlier Cura versions.
- if one selects Prusa as the printer type, it generates bad temp codes: M104 and M109, both with the same S-value as the temp setting, and in the wrong sequence. Should be M190 to set bed temp and wait, then M109 for extruder temp as set.

**Comment by fieldOfView** [comment]
This issue can be closed.

There is no "RepRap" printer, but there is a "Custom FDM Printer" now. In Cura 2.6 this printer even has a variable number of extruders, to support printers with up to 8 extruders.

The second issue can be solved by editing the start gcode. Cura only inserts M104/M109 codes at the start if the start gcode does not specify them. The start gcode can be edited in Machine Settings.
