### ISSUE TITLE
Cura 3.6.0 Blank screen / no gui after startup 

### ISSUE THREAD

**Issue by nicknugget** [Ultimaker/Cura#5296]
**Application Version**
3.6.0 AppImage

**Platform**
XUbuntu 18.04.2 LTS amd64

**Printer**
Custom

**Steps to Reproduce**
Open / start Cura

**Actual Results**
 Blank screen. No usable GUI available. See attached screenshot.

**Expected results**
User interface showing.

**Additional Information**
Happened after a recent system update via update-manager. All my available cura versions down to version 3.5 show this behaviour. Version 3.4.1 and lower just work fine.

![screenshot_cura_3_6](https://user-images.githubusercontent.com/11063442/52645472-2680b800-2ee1-11e9-8afc-8031d57c08bc.jpg)

**Comment by Ghostkeeper** [comment]
Not seeing this on normal Ubuntu 18.10 right now. Do you know what packages were updated? It appears like something broke in the Qt library.

**Comment by nicknugget** [comment]
Unfortunately I can't remember which packages were updated during the update. I didn't pay any attention to this at first. 

On another computer with a current Xubuntu 18.10 it doesn't work for me either.

I also suspect that it has something to do with Qt. Unfortunately, I don't know enough about it.

**Comment by nicknugget** [comment]
I added the stderr.log from cura. It contains all messages from the last program start.

[stderr.log](https://github.com/Ultimaker/Cura/files/2857529/stderr.log)

**Comment by Ghostkeeper** [comment]
That log looks fairly normal. Nothing special to see that could be related to the GUI missing.

**Comment by mboberlin** [comment]
Same problem here.. also Ubuntu 18.04.2 LTS.

**Comment by nallath** [comment]
But it should just use the qt that we ship with the appimage right? So that pretty much leaves graphics drivers as the culprit.

**Comment by mboberlin** [comment]
Hi,
yes, i am using the original appimages. Problem exists in Cura 3.5 to
4.0beta.
Greetings,
Michael

Am Mi., 13. Feb. 2019 um 13:44 Uhr schrieb Jaime van Kessel <
notifications@github.com>:

**Comment by nicknugget** [comment]
At least it looks like i'm not alone with the problem. The funny thing is, that it works just fine in a fresh XUbuntu 18.10 installation with all current system updates running in a virtual machine (virtualbox)

**Comment by mikeyancey** [comment]
I'm also having this issue (Cura 3.6.0, Ubuntu 18.04 LTS).
(For me, anyway) the menus are 'there', if you click about - but they're blank. 
Right-click menu is present, but blank.
I have variously deleted .cache, .config, and .local/share/cura items, with no effect. 
I'll attach cura.log (from .local/share/cura/3.6/). There are warnings: "UM.Qt.QtApplication.__onQmlWarning"...

[cura.log](https://github.com/Ultimaker/Cura/files/2862314/cura.log)

**Comment by mboberlin** [comment]
I have a Thinkpad T510 with Intel Ironlake Mobile Graphics.
It really seems to be a problem with the graphics driver, using a more actual driver from the PPA mentioned in [https://askubuntu.com/questions/1065852/how-to-upgrade-intel-graphics-driver]  it works again.

**Comment by mikeyancey** [comment]
Aha - I was about to wipe all traces of Cura's files and re-install.
In ~.cache folder, there's a cache of 'qtshadercache'.
I saved it (mv qtshadercache to xyzzy-qtshadercache - shouldn't matter if I deleted it, it should re-gen, but - saving it in case it's important).
RUN (for the 45th time today) - Cura 3.6.0
ALL menus are back; right-click menu back; the Printer side-bar is back.
![screenshot from 2019-02-13 16-41-59](https://user-images.githubusercontent.com/299278/52749365-8d1fd780-2fae-11e9-9373-fa5a81c7f1cf.png)

I believe in my instance, Cura was shutdown (forced) improperly; it wasn't a 'QT was updated' or 'Display driver was updated' issue.
So, possibly QT cache related - it's clearly going to the qtshadercache (under .cache), but receiving some 'half-baked' info.

**Comment by mikeyancey** [comment]
Glad you got it working. Very cool.

Well - I guess the problem can be arrived at both ways, then.
A driver that causes complaint from QT and a corrupt 'QT Shader Cache' have
the same effect.

I swear, mine looked exactly as the original screencap - white panel where
the 'Selected Printer' should be... etc.
..
Mike Yancey
Dallas, Texas
https://www.mikeyancey.com <http://www.mikeyancey.com>

**Comment by nicknugget** [comment]
Previously i tried to get rid of all cura-folders in ~./ - nothing changed. 

As suggest by @mikeyancey I deleted the ~./cache/qtshadercache folder this morning. 

YES! Cura is working again!

**Comment by wgaonar** [comment]
So many thanks to @mikeyancey. It is working now

**Comment by kitts82** [comment]
> Aha - I was about to wipe all traces of Cura's files and re-install.
> In ~/.cache folder, there's a cache called: 'qtshadercache'.
> I saved it (mv qtshadercache to xyzzy-qtshadercache - shouldn't matter if I deleted it, it should re-gen, but - saving it in case it's important).
> RUN (for the 45th time today) - Cura 3.6.0
> ALL menus are back; right-click menu back; the Printer side-bar is back.
> ![screenshot from 2019-02-13 16-41-59](https://user-images.githubusercontent.com/299278/52749365-8d1fd780-2fae-11e9-9373-fa5a81c7f1cf.png)
> 
> I believe in my instance, Cura was shutdown (forced) improperly; it wasn't a 'QT was updated' or 'Display driver was updated' issue.
> So, possibly QT cache related - it's clearly going to the qtshadercache (under .cache), but receiving some 'half-baked' info.

Thanks. This fixed it for me.

**Comment by Ghostkeeper** [comment]
Cura is not the only application whose Qt shaders get cached in that folder. The files in that folder are not labelled to belong to which application. So it's hard for us to reset that folder...

**Comment by dvoros** [comment]
Faced the same issue after the update of the following qt-related packages (standard update with 18.04):
```
qt5-gtk-platformtheme:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5dbus5:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5widgets5:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5printsupport5:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5gui5:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5core5a:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
libqt5network5:amd64 (5.9.5+dfsg-0ubuntu2.1, 5.9.5+dfsg-0ubuntu2.3)
```
Removing `~/.cache/qtshadercache/`, as suggested by @mikeyancey, resolved the issue. Thanks for that!

**Comment by Ghostkeeper** [comment]
If the issue is related to upgrading Qt version, then maybe it would also happen when using multiple applications with different Qt versions. Cura's AppImage always uses Qt 5.10 (for the latest couple of Cura versions anyway). So if a different application uses different Qt versions it might get corrupt?

**Comment by Ghostkeeper** [comment]
In Cura 4.5 we've added a workaround for this issue. These are the steps to apply this workaround:

* Make sure that Cura is not running.
* Go to the configuration storage location for Cura. On Windows that's `C:\Users\<username>\AppData\Roaming\cura\4.5`. On MacOS that's `~/Library/Application Support/cura/4.5`. On Linux that's `~/.config/cura/4.5`.
* Open the cura.cfg file with a text editor.
* Under the `[view]` header, add a new key:
      `force_empty_shader_cache = True`

This will cause Cura to not use the shader cache any more and clear its part of the cache. It'll fix your issue in the same way as removing the `qtshadercache` folder every time you start Cura. The flipside of this is that your start-up will take a performance hit of 1 or 2 seconds. Given how rare this is, we don't like to disable the shader cache by default. And given that it tends to get corrupted sporadically (not repeatedly on the same computer), it might just be easier to find and delete that `qtshadercache` folder just once.

We're still looking for a better way to fix this, but we have no idea how. Ideally we'd be able to detect somehow that things got corrupted.

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?

**Comment by nicknugget** [comment]
I have not encountered this problem in the newer versions of Cura (5.8.0 and up) since then.

**Comment by GregValiant** [comment]
Thanks.  I go ahead and close this.
