### ISSUE TITLE
Please create an AppData file for Cura

### ISSUE THREAD

**Issue by hughsie** [Ultimaker/Cura#530]
Please consider writing and installing an AppData file with the application description and some screenshots, else Cura looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. I use Cura quite a lot, and would love to feature it on the front page. If you need help or an example file, please just ask.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by nallath** [comment]
Shouldn't take too much effort I guess.

**Comment by hughsie** [comment]
I'm getting reports from people that cura isn't visible in gnome-software and I'm pointing them to this bug. Would you like me to try to create an AppData PR for this functionality?

**Comment by nallath** [comment]
Please do. We're very close to a release, so our minds are focused on other things right now. 
Sorry that this issue fell through the cracks
