### ISSUE TITLE
Support haning lose

### ISSUE THREAD

**Issue by Perohlsson123** [Ultimaker/Cura#5318]
**Application Version**
Beta 4.0.0

**Platform**
Windows 10

**Printer**
Ultimaker S5

**Steps to Reproduce**
Slicing with "enable conical support" enabeld, Conical support settings is 35 degrees and 5mm.

**Actual Results**
See atteched file

**Expected results**
it should not hang lose, becuse its not that complex. 

**Additional Information**
Atteched Picture:
![support haning lose](https://user-images.githubusercontent.com/47686538/52896719-bc5f6000-31cb-11e9-86c7-e17dd6dc911a.PNG)

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this using my test models. Can you provide us with a project file that reproduces the problem?

**Comment by Perohlsson123** [comment]
Hi

I cant get it to be unsupported again, and im using the same profile and part???.

But now im having another unsupported issue. See attached Picture.

Attached is:
Profile:     2. EUPart, Normal, V00
Part:         33880-00_R0_3DP

Best regards
Per Ohlsson

Phone: +46 8 620 20 94
Mobile: +46 72 571 35 94
per.ohlsson@georgfischer.com<mailto:per.ohlsson@georgfischer.com>

production Engineer
System 3R International AB
Sorterargatan 1
162 50 Vällingby
Sweden
www.system3r.com<http://www.system3r.com/>

**Comment by Ghostkeeper** [comment]
Attachments don't work via the e-mail reply feature of Github. You have to actually go on the site and upload it there.

**Comment by Perohlsson123** [comment]
Ok

Trying with this :)

[Hanging loose.zip](https://github.com/Ultimaker/Cura/files/2875257/Hanging.loose.zip)

**Comment by Ghostkeeper** [comment]
Yeah, I can't reproduce that either with your model. It seems to work fine so far.

![screenshot from 2019-02-18 12-03-53](https://user-images.githubusercontent.com/2448634/52946820-4f87c980-3375-11e9-8c49-a757556284d8.png)

I would really print that upside down, by the way, but maybe you need that top surface to be pretty :P

**Comment by Ghostkeeper** [comment]
The conical angles are not visible on the sides because it's already at the minimum thickness for the cones there (the inside is hollow).
