### ISSUE TITLE
Use PLA not PVA for all but 2-3mm vertically of support

### ISSUE THREAD

**Issue by BonyJordan** [Ultimaker/Cura#5323]
Use non-PVA for "most" support.  Since PVA is expensive and PLA is cheap (and usually a bit stronger), when there is a part which needs >5mm or so of vertical support, the bottom part of the support should use the PLA and only use a couple of mm worth of PVA.

**Comment by Ghostkeeper** [comment]
To do this, enable Support Interface and set the Support Interface Extruder to the extruder of your PVA (while keeping the Support Infill Extruder to the PLA extruder).

Be wary of steep slopes that get supported by PVA. You don't want too small of an area to fill with PVA. Or use a prime tower.
