### ISSUE TITLE
Cura 3.6 filling error of the second extruder

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#5330]
Hello, looks like I have found an error that most likely goes from version to version of the program.
If you turn off the first extruder in the slicer and leave only the second, then the infilling of the model works fine and changes depending on the percentage. But if the program is closed and opened the next time, the infilling section in "custom" stops responding. But at the same time the infilling section in "Recomended" still works.
The same happens to the infilling pattern.

**Application Version**
version 3.6 , 4.0

**Platform**
windows 8.1

**Printer**
delta printer 

**Steps to Reproduce**

turn on the second extruder,
turn off the first extruder
close the program
open the program
load model
change infilling in the "custom" section
try slicing with new filling 

**Actual Results**
Infilling remains on default

**Expected results**
Infilling must change 

**Additional Information**
if you do it with the first extruder, everything is fine. The problem occurs if you turn off the first extruder and use only the second one

**Comment by rburema** [comment]
The settings that can be changed per extruder require that the current extruder is selected. What I think happened is that you only changed the infill setting for the first extruder:

With the first (disabled) extruder selected:
![1st_extruder_selected](https://user-images.githubusercontent.com/41987080/53076576-3bb4a280-34f0-11e9-8fea-bcb05cae019b.png)

With the second (enabled) extruder selected:
![2nd_extruder_selected](https://user-images.githubusercontent.com/41987080/53076577-3bb4a280-34f0-11e9-8a62-ba54da3b6c28.png)

This does raise some UX/GUI questions about those options being active, but conversely, what if the user wants to change those options and later enable the extruder?

Can you confirm or deny that this is what happened, or is there something else going on?

cheers,
Remco.

**Comment by Goodfeat** [comment]
Filling is changed only in the section "recommended", in "custom" the filling does not respond to the setting.
the second extruder is turned on, the first is turned off and there is no access to it in the settings
![0](https://user-images.githubusercontent.com/44455128/53078359-c2dd3700-353f-11e9-8268-8fcb1c863632.png)
![1](https://user-images.githubusercontent.com/44455128/53078370-c8d31800-353f-11e9-9f5e-0017dca1d7f1.png)
![2](https://user-images.githubusercontent.com/44455128/53078378-ce306280-353f-11e9-8432-973bd59d6866.png)

**Comment by Goodfeat** [comment]
Indeed, there is no such problem in CURA 4.0, but in 3.6 there is

**Comment by rburema** [comment]
I see what the problem is now.

I'm sorry, but fixes always go into the latest version. If you want a stable build with this fixed, you'll have to wait until 4.0.0 is out (hopefully somewhere next month, but we'll release 4.0-BETA-2 hopefully next week or thereabouts).

**Comment by Goodfeat** [comment]
OK, I will wait for the update
Thanks
