### ISSUE TITLE
CURA 3.6.0 Upon loading it defaults to the R side of my screen, the only VIEW options I have are full screen or this> can't see CURA?

### ISSUE THREAD

**Issue by captNtinker** [Ultimaker/Cura#5334]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by rburema** [comment]
Could you fill the form? Or at least provide a screenshot, since it's not very clear (to me at least) what you mean by 'this>' for example. cheers, Remco.

**Comment by Ghostkeeper** [comment]
Try pressing Windows Key + Left/Right Arrow to move the Cura screen around your monitor.
