### ISSUE TITLE
Minor change in spanish language translation

### ISSUE THREAD

**Issue by burnham** [Ultimaker/Cura#5340]
**Application Version**
3.6.0

**Platform**
Windows 10

**Printer**
Ender 3

**Actual Results**
Wrong translation.

**Additional Information**
![cura](https://user-images.githubusercontent.com/249632/53122053-e6ab7780-3555-11e9-880c-90e98fccf5d2.jpg)

**Comment by rburema** [comment]
Thanks for reporting this, I could fix it right away. It should be in the 4.0-BETA-2. cheers, Remco.
