### ISSUE TITLE
[3.6.0] Infill layer thickness gap bug

### ISSUE THREAD

**Issue by Levious** [Ultimaker/Cura#5345]
**Application Version**
3.6.0

**Platform**
MacOS Mojave 10.14

**Printer**
Custom ULTI

**Steps to Reproduce**
Layer height - 0.05
Infill layer thickness - 0.2

**Actual Results**
Big gap between infill and wall

**Expected results**
No gap

**Additional Information**
I changed the infill overlap from 10% to 80% and the result did not change. For the experiment, I tried the same model on the same settings in the simpliify - everything was fine.
Is this a bug or am I doing something wrong somewhere?
If the thickness of the layer coincides with the thickness of the infill - everything is ok. If not, a gap appears.

10% overlap
![img_6712](https://user-images.githubusercontent.com/47891135/53253528-8857d380-36d2-11e9-9fee-76bd234392ab.JPG)

80% overlap
![img_6713](https://user-images.githubusercontent.com/47891135/53253529-8857d380-36d2-11e9-8090-ab197ef7bc84.JPG)

Update 23.02.18
I tried all infill types and in all the problem remains. Attached to the walls only filling type "lines" without "connect infill lines". Also in 9/9 cases different people have the same bug in version 3.6.0. We have not had time to check other versions yet.

**Comment by smartavionics** [comment]
Hello @Levious, please zip up and attach a project that exhibits this problem. Thanks.

**Comment by Levious** [comment]
> Hello @Levious, please zip up and attach a project that exhibits this problem. Thanks.

You can create any simple object of your own like a cube or cylinder and see this bug in yourself. I attach my project. Thank.
[Just 20 box.3mf.zip](https://github.com/Ultimaker/Cura/files/2905142/Just.20.box.3mf.zip)

**Comment by smartavionics** [comment]
Hello @Levious , that's not a project file, it only contains the model. Please do File -> Save to create a project file that also contains your settings. Thanks.

**Comment by Levious** [comment]
> Hello @Levious , that's not a project file, it only contains the model. Please do File -> Save to create a project file that also contains your settings. Thanks.

[Just 20 box.3mf.zip](https://github.com/Ultimaker/Cura/files/2907455/Just.20.box.3mf.zip)

**Comment by smartavionics** [comment]
Hello @Levious , I have fixed this issue for most of the infill types and will submit a PR so that the fix can be incorporated in Ultimaker's Cura sometime in the future. Thanks for the bug report.

**Comment by smartavionics** [comment]
![img_20190227_084807180](https://user-images.githubusercontent.com/585618/53477433-98720900-3a6c-11e9-80ca-17283fa14453.jpg)

**Comment by Ghostkeeper** [comment]
Good find!

**Comment by Block137** [comment]
Any temporary workaround for this?

Appears to affect support as well, I have a problem where PVA interface does not adhere to PLA support infill.

**Comment by Block137** [comment]
Can we(users) expect this fix to be in next release?

My current workaround is to half the line width and double the flow rate.

**Comment by smartavionics** [comment]
Yes, unless some problem is discovered, it will be in 4.4.

You can already benefit from this fix if you are using one of my builds which you can find at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0.

**Comment by Ghostkeeper** [comment]
Yes, it's merged for 4.4.
