### ISSUE TITLE
Cura Engine Print Time and Filament Usage

### ISSUE THREAD

**Issue by sarahSamonte** [Ultimaker/Cura#536]
What is the unit used for printing time and filament usage? When I tried opening the same stl file in Cura, the units used for print time is hours and minutes. It's not the case in this picture, though. The same issue goes for filament usage.

I am using a previous version of Cura (15.04). 

![time](https://cloud.githubusercontent.com/assets/11551855/11114006/2e69a0f0-895c-11e5-8f30-f8bec063ad14.png)

**Comment by daid** [comment]
Seconds and mm

**Comment by sarahSamonte** [comment]
Follow up question on Print Time, does it consider the support material for the model?

**Comment by Ghostkeeper** [comment]
Yes, it should include the printing of support material.
