### ISSUE TITLE
Draft Wall Speed?

### ISSUE THREAD

**Issue by tablatronix** [Ultimaker/Cura#5373]
**Application Version**
3.6.0
**Platform**
osx
**Printer**
monoprice smv2

What speed is used for draft wall feedrate ?
Might be useful to clarify in docs.

I thought it might be wall speed, but when I dropped my first layer speed I felt like it was printing slower for all layers, the full height ( limited 2mm )

**Comment by Ghostkeeper** [comment]
It's using the speed, acceleration, jerk, line width, layer thickness, flow and fan speed of the skirt or brim. So specifically it's going to use the setting "Skirt/Brim Speed", to answer your question.

**Comment by tablatronix** [comment]
So i guess my follow up is should it? Since skirt and brim are single layer, If I use a painfully slow first layer, then my entire wall is slow for entire z height. Seems non ideal, but I do see that it might need to be limited somehow since it is a thin wall.

**Comment by tablatronix** [comment]
Ok I see what the actual problem is here, `skirt/brim speed` is hidden if `build plate adhesion` is none.

So it cannot be changed manually

**Comment by Ghostkeeper** [comment]
Right, good find! Draft shields aren't used very often, so there's probably some bugs in there still.

That said, I don't see the need to configure the draft shield very carefully. If it's printing a little too fast, it's probably going to print fine. If it's printing a little too slow, it still doesn't take a whole lot of time.

**Comment by tablatronix** [comment]
True,  of course I had the first layer speed at 10 for some first layer issues, and I had a full wall, so it was certainly noticeable, but normally it would not be an issue.

**Comment by Ghostkeeper** [comment]
You can change the first layer speed separately from the skirt/brim speed by the way.

**Comment by tablatronix** [comment]
Well yeah but I could not change it before unless I had a wall and a brim enabled, before your fix.
I guess the workaround is to enable a BPA, change brim speed, then un-enable the BPA, I did not think to try that, as the setting would still be set perhaps.

**Comment by Ghostkeeper** [comment]
Then I think we'll close this issue with a "good enough" now. We won't implement being able to tune the draft shield speed separately.
