### ISSUE TITLE
Beta 4 Crash on slicing

### ISSUE THREAD

**Issue by NaloMeliful** [Ultimaker/Cura#5379]
**Application Version**

Cura Beta 4
**Platform**

Windows 10
**Printer**

Anycubic i3 Mega Full Metal
**Steps to Reproduce**

Any STL I try to slice even on recommended settings crashes (freezes the app)
**Actual Results**

I have to close Cura from Task Manager. I have totally uninstalled and reinstalled. Same issue.
**Expected results**

It should slice and allow me to save
**Additional Information**

**Comment by Ghostkeeper** [comment]
Not able to reproduce. Slices fine here. But I must admit that I'm using the Anycubic i3 Mega profile that Cura gets shipped with. I don't know of any profile for the "Full Metal" version, if that's any different.
