### ISSUE TITLE
wanhao duplicator i3 no mods , not connect to cura ultimaker 3,6 Suggestion ?

### ISSUE THREAD

**Issue by miguelcnc** [Ultimaker/Cura#5381]
i connect my wanhao duplicator i3 , standard , without important modifes , only goood alignement of belt and bed , 

i install the 3.6 versio n of ultimaker cura , but i can't connect the sw to my printer, with other sw ( matter control ) work fine ... 

any suggestion for me ? i reinstall win 7 64 clean and i ( crazy.... ) upgrade all ms updates, but nothing change , the sw ask me  " not connected to the printer ks to the comunity for help ."   any idea for solve this issue ? 

thanks  , Stefano , Fron ITALY

**Comment by Ghostkeeper** [comment]
You're connecting via USB cable?

Maybe MatterControl can tell you what Baud rate it is using in order to connect?

**Comment by miguelcnc** [comment]
Hi , yes i hVe connected via usb cable , the speed of ports are 115200 , i try also to update drivers for the interface converter and also for usb port , but nothing change , if i use other sw ( matter control ) the Machine print.... I Begin to be crazy ...The cable is good mini usb ended long 1 mt only , the os is win 7 64 , i reinstall also from dvd and all drivers are ( i suppose ) correct , i tri with 2 notebook  and same issue...Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Ghostkeeper <notifications@github.com> Data: 04/03/19  16:59  (GMT+01:00) A: Ultimaker/Cura <Cura@noreply.github.com> Cc: miguelcnc <miguelcnc@alice.it>, Author <author@noreply.github.com> Oggetto: Re: [Ultimaker/Cura] wanhao duplicator i3 no mods , not connect to cura ultimaker 3,6 Suggestion ? (#5381) You're connecting via USB cable?
Maybe MatterControl can tell you what Baud rate it is using in order to connect?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ultimaker/Cura","title":"Ultimaker/Cura","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Ultimaker/Cura"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Ghostkeeper in #5381: You're connecting via USB cable?\r\n\r\nMaybe MatterControl can tell you what Baud rate it is using in order to connect?"}],"action":{"name":"View Issue","url":"https://github.com/Ultimaker/Cura/issues/5381#issuecomment-469306189"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Ultimaker/Cura/issues/5381#issuecomment-469306189",
"url": "https://github.com/Ultimaker/Cura/issues/5381#issuecomment-469306189",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Ghostkeeper** [comment]
115200 seems normal. It's the first baud rate that Cura will try, even.
Since your printer connected fine with MatterControl but not with Cura, the fault seems to be in Cura.

However I have no way to debug this since I don't have a Wanhao Duplicator 1 here. I can't test anything.

**Comment by miguelcnc** [comment]
are you developer of cura team ? if you like , i can also permit you to connect to my pc with teamviewer , so you can check if all is in order ... 

Thanks for now, if think matter control , use proprietary drivers to connect to the printer, but the melzi board  use the ftdi drivers and is updated drivers... i begin to  be crazy -... 
 thanks fo rnow .




  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 5-mar-2019 17.16
 
 A: "Ultimaker/Cura"<Cura@noreply.github.com>
 
 Cc: "miguelcnc"<miguelcnc@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [Ultimaker/Cura] wanhao duplicator i3 no mods , not connect to cura ultimaker 3,6 Suggestion ? (#5381)
 

 

 
115200 seems normal. It's the first baud rate that Cura will try, even.
 Since your printer connected fine with MatterControl but not with Cura, the fault seems to be in Cura. Not with any cables, drivers or OS.
 
However I have no way to debug this since I don't have a Wanhao Duplicator 1 here. I can't test anything.

**Comment by Ghostkeeper** [comment]
Yes, I'm one of the [Cura developers](https://github.com/Ultimaker/Cura/graphs/contributors). But I think that even in a remote desktop application I couldn't help a whole lot. I would check the baud rates and if it responds to `M105` g-code, but that's all I could really do.

**Comment by miguelcnc** [comment]
i check  in the later afternoon ... and i reply you . Thsanks for now . 
Stefano


  ----Messaggio originale----
 
 Da: notifications@github.com
 
 Data: 7-mar-2019 9.59
 
 A: "Ultimaker/Cura"<Cura@noreply.github.com>
 
 Cc: "miguelcnc"<miguelcnc@alice.it>, "Author"<author@noreply.github.com>
 
 Ogg: Re: [Ultimaker/Cura] wanhao duplicator i3 no mods , not connect to cura ultimaker 3,6 Suggestion ? (#5381)
 

 

 
Yes, I'm one of the Cura developers. But I think that even in a remote desktop application I couldn't help a whole lot. I would check the baud rates and if it responds to M105 g-code, but that's all I could really do.

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?
