### ISSUE TITLE
STL from Design spark mech "failed to load" able to open in MS 3d PRint

### ISSUE THREAD

**Issue by agfrvf** [Ultimaker/Cura#5382]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by smartavionics** [comment]
It's probably a bad STL that is causing the problem rather than Cura  so please zip up the STL and attach to this issue so we can check it. Thanks.

**Comment by agfrvf** [comment]
Smartavonics, I think you were right. I put it through a bunch of stuff in meshmixer and its loading. The file was way too big to upload zipped @66%.
