### ISSUE TITLE
Cura not slicing entire object

### ISSUE THREAD

**Issue by jruckman91** [Ultimaker/Cura#5389]
When slicing in Cura, it only slices the last couple of layers and not the whole object. I've reinstalled the program, adjusted settings, tried to repair the object but nothing is working. I was able to print everything just fine but it is doing this with every .stl file.
![cura screenshot](https://user-images.githubusercontent.com/48216517/53746966-1e1ffb00-3e57-11e9-9acd-3da68b09b839.png)

**Comment by smartavionics** [comment]
Hello @jruckman91 , please save a project file, zip and attach to this issue. Thanks.

**Comment by jruckman91** [comment]
[tabletop 1.zip](https://github.com/Ultimaker/Cura/files/2927618/tabletop.1.zip)

**Comment by jruckman91** [comment]
Hopefully I sent it correctly.

**Comment by smartavionics** [comment]
I'm afraid not. You sent the model but I want the whole project (that includes the model and the settings you are using). So do File->Save and that should produce a .3mf file which you can zip and attach.

**Comment by smartavionics** [comment]
That's File->Save from within Cura!

**Comment by jruckman91** [comment]
[AI3M_tabletop 1.zip](https://github.com/Ultimaker/Cura/files/2927632/AI3M_tabletop.1.zip)

**Comment by smartavionics** [comment]
it slices fine for me and looking at your image above it looks like it has sliced OK for you. The lower layers are greyed out but they can be displayed by moving the layer slider down and up again (not sure why it has started greying out the lower layers. Perhaps that's a bug?)

**Comment by jruckman91** [comment]
It slices in cura and shows that it did just fine. But when you go to layer view and use the slider next to the play button it only shows it only printing that last layer or so. Then when I save it to print it only prints the last layer or 2 that it showed in cura. Hopefully that makes sense.

**Comment by smartavionics** [comment]
I saved the gcode and looked at it in a gcode viewer and it shows all the layers so I can't see there's a problem.

![screenshot_2019-03-04_18-40-53](https://user-images.githubusercontent.com/585618/53754953-49cdd000-3ead-11e9-83be-650dd4e00f16.png)

**Comment by jruckman91** [comment]
Do you think its some kind of bug in Cura? I am unable to print anything. Even things I have printed previously are not being sliced correctly and only have the last layer printed. I will send you another example.

**Comment by jruckman91** [comment]
![tabletop legs](https://user-images.githubusercontent.com/48216517/53755556-a5776980-3e6b-11e9-9630-1e42d598f4be.png)
If you look closley it only shows the last layer being printed. If I were to save this and print it out, only the yellow portion would be printed.

**Comment by smartavionics** [comment]
Please send me both the project file and the gcode that you get from it so I can slice it myself using the same settings and compare the gcode I get with what you are getting. Thanks.

**Comment by jruckman91** [comment]
[tabletop legs.zip](https://github.com/Ultimaker/Cura/files/2927828/tabletop.legs.zip)
Here is the gcode for the legs. The profile is the same as the one I have sent previously.

**Comment by jruckman91** [comment]
I am about to leave for work so I will not be able to send any more information. But I can comment from my phone. Thank you for your help!

**Comment by smartavionics** [comment]
LOL, that wasn't gcode, that was an image! Don't worry, please send the STL and the gcode when you can.

**Comment by jruckman91** [comment]
Oh oops haha. My bad, I will send you it once I get home tonight. Thank you!

**Comment by jruckman91** [comment]
[table_legs.zip](https://github.com/Ultimaker/Cura/files/2929249/table_legs.zip)

**Comment by jruckman91** [comment]
hopefully I did it correctly now haha

**Comment by smartavionics** [comment]
Thanks for the table legs model. Well, I can slice this and the gcode looks OK so I really don't know where the problem is here.

**Comment by jruckman91** [comment]
I just don't understand what is going on. I've had my 3d printer for about a year and haven't changed anything as far as the way I print. This issue just happened the other day. I must have some kind of bug. I will try to reinstall it again. Maybe an older version. Thank you for all your help.

**Comment by jruckman91** [comment]
Still no luck. It does the same thing no matter what version I download.

**Comment by Ghostkeeper** [comment]
> (not sure why it has started greying out the lower layers. Perhaps that's a bug?)

Yes, something to do with how it detects that it should be greyed out and the initial state after a reslice ending up like that.

> I just don't understand what is going on. I've had my 3d printer for about a year and haven't changed anything as far as the way I print. This issue just happened the other day. I must have some kind of bug. I will try to reinstall it again. Maybe an older version. Thank you for all your help.

Maybe it would help to compare the g-code that Cura generates now with the g-code that Cura used to generate in versions that did work. Maybe some g-code is causing it to skip towards the last layer?

**Comment by jruckman91** [comment]
I've had Cura 3.6 and its been slicing just fine and my prints are great. Then all of the sudden this started happening two days ago. It does this with every g-code no matter what version of Cura I use. I even tried other slicer software and I get the same issue.

**Comment by Ghostkeeper** [comment]
If it happens with all slicers then you need to take a hard look at the firmware. Perhaps do a factory reset?

**Comment by jruckman91** [comment]
A factory reset on my pc?

**Comment by Ghostkeeper** [comment]
No, on your printer.

**Comment by jruckman91** [comment]
Its not the printer that is the problem. Its the slicer software. I don't have my printer hooked up to my pc. I save the g-codes to a sd card and then load them up in my printer. When I am in Cura, I load in a stl file, slice it and then when I check it in layer view it only shows the last layer being printed.

**Comment by jruckman91** [comment]
![bumper car bottom](https://user-images.githubusercontent.com/48216517/53816420-65ba8b80-3f18-11e9-9e5a-d4912cbcae75.png)
Here is another example. If I were to save this to my sd card and have my printer print it, it will only print the yellow area.

**Comment by jruckman91** [comment]
No settings were changed. I've used the same settings for the past year. Only things changed are layer height and infill percentage.

**Comment by smartavionics** [comment]
> Here is another example. If I were to save this to my sd card and have my printer print it, it will only print the yellow area.

Are you saying that it would print that yellow area on the print bed (i.e. z = 0) or that it would try to print it way up in the air (and fail, of course).

**Comment by Ghostkeeper** [comment]
> I even tried other slicer software and I get the same issue.

So you're saying that all slicer software has the exact same bug, that it only prints the top-most layer?

**Comment by jruckman91** [comment]
For me yes, I've tried two other slicers and I get the same issues. The picture I sent I have printed before and printed just fine. But it will print directly on the bed only the yellow area now.

**Comment by smartavionics** [comment]
> For me yes, I've tried two other slicers and I get the same issues. The picture I sent I have printed before and printed just fine. But it will print directly on the bed only the yellow area now.

OK, well if it's occurring with gcode from other slicers also then it can't be a problem that is specific to Cura. Your printer must be having a bad hair day!

**Comment by jruckman91** [comment]
I haven't tried printing from the other slicers I used because when I preview the layers and travels it only shows that last layer. So I haven't even attempted to print anything anymore because it just fails. It can't be a problem with my printer because its not even involved in this issue. It's when I load in the stl file to slice it. thats when the problem occurs.

**Comment by smartavionics** [comment]
OK, I'm really confused now. So you're not actually printing anything, you're just viewing the gcode in Cura?

BTW, Just because the layers are shown as grey in the layer view doesn't mean that they won't be printed.

**Comment by jruckman91** [comment]
This is exactly what happened. I loaded in a stl file into Cura. Sliced it, saved it to my sd card and went to print it. The print failed and only printed the last layer. So I checked it in the layer viewer in Cura and just like the failed print, it only showed that last layer. I closed Cura, opened it back up to slice it again. The same file sliced perfectly and it showed all the layers that would be printed. I saved it to my sd card to print and it printed perfectly. But now every time I load in a file to slice within Cura it only shows the last layer. I havent tried to print anything since then. I've only been printing what is on my sd card because I have orders that need to be printed. Hopefully this makes sense. Sorry for any confusion. I'm trying to explain it the best way I can.

**Comment by Ghostkeeper** [comment]
Here's a thought then: Maybe the file on the SD card was corrupted? Was the SD card ejected before removing it from the computer?

**Comment by jruckman91** [comment]
Yes I eject it every time.

**Comment by jruckman91** [comment]
Its possible that file got corrupted but why would it not show me every layer and travel when I slice a file in Cura? It has previously.

**Comment by Predator75** [comment]
I have just installed the last version today and I have the same problem, Cura slice only the last layer

**Comment by blkexp98** [comment]
I am having the same issue.  I dont even get to the SD card portion and use Octoprint anyway.  This is a new computer and I havent tried to print again until now.   Also when I login to octoprint I can load and simulate an old file which works fine (within octoprint) but the new ones I have tried all do what the original poster described.   So this has to be something with how the slicer is working.  The only other variable would be I was using an older intel based computer and now I built  AMD Ryzen based PC.

**Comment by Ghostkeeper** [comment]
I think your issue is different then Blkexp98, since the original report says that this happens with every slicer software.

**Comment by blkexp98** [comment]
Do you want me to start a new thread so its easier to keep track of?

**Comment by Ghostkeeper** [comment]
It's probably best to start a different thread about it. Be sure to include some reproduce steps and maybe a project file. Loading that calibration cube in an Ultimaker 3 printer for me makes it print fine, though some of the letters are significantly thinner than 0.4mm and won't get printed then.
