### ISSUE TITLE
Cura 3.6 Slicing Error

### ISSUE THREAD

**Issue by novio8** [Ultimaker/Cura#5391]
I printed Delta Calibration tool and the print has a Geometry error
as seen from Picture of Repetier Preview (Red Arrow pointing at error)
Cura shows Preview as it should be sliced.
I attached  Repetier Preview

Cura 3.6
Mac OSX 10.13.6
Kossel Delta
![repetier preview](https://user-images.githubusercontent.com/29116262/53790102-62c69780-3f26-11e9-872d-15589e688d7c.jpeg)

**Comment by novio8** [comment]
I used the same Cura 3.6 profile in Cura 2.5.1
and at firs glance Model is sliced correctly, so there must
be something going on with 3.6

**Comment by smartavionics** [comment]
See https://community.ultimaker.com/topic/26878-cura-36-slicing-bug/

**Comment by Ghostkeeper** [comment]
I'm also not able to reproduce that, using the model that's posted on the forum :disappointed:

**Comment by novio8** [comment]
sorry for delay, I solved the problem by the following procedure
1. saved my Cura profiles and materials
2. removed  all Cura installations
3. Reinstalled Cura 3,6
4. Imported back my Profiles
 
Now it seems everything is just fine

**Comment by Ghostkeeper** [comment]
Something in your configuration was awry I guess, but I suppose we'll never find it out now. I'm glad you found a workaround for it.

**Comment by ediciuStsaF** [comment]
![grafik](https://user-images.githubusercontent.com/28952057/54074617-03a1b380-4295-11e9-9f72-68e02c12dedf.png)

TOP doesn´t slide correctly

for me new install doesn´t work....

![grafik](https://user-images.githubusercontent.com/28952057/54074627-2e8c0780-4295-11e9-8727-ce85c86bf729.png)

**Comment by Ghostkeeper** [comment]
In your case it looks like the top surface there is exactly on the border between two layers. What happens if you change the initial layer height to be 0.01mm higher?

It's hard to say whether the model is at fault here or the slicer.

**Comment by ediciuStsaF** [comment]
In Slic3r this Model slices correct. I‘ll give it a try bei changing 0,1mm
