### ISSUE TITLE
Cura 3.6 printed 2 items (one at a time) despite only requesting one item printed

### ISSUE THREAD

**Issue by dshapdesign** [Ultimaker/Cura#5394]
**Application Version**
3.6.0

[cura.zip](https://github.com/Ultimaker/Cura/files/2932138/cura.zip)

**Platform**
Windows 7 Pro SP1

**Printer**
Ultimaker 2+ Extended

**Steps to Reproduce**
Placed single object in Cura. File sent to octoprint. 

![singleobjectonscreen](https://user-images.githubusercontent.com/25356674/53826489-51898500-3f3e-11e9-82e6-7fc9ab2e8b37.png)

[UM2E_DrainCatcherV3.zip](https://github.com/Ultimaker/Cura/files/2932152/UM2E_DrainCatcherV3.zip)

**Actual Results**
Whole object printed then additional copy of object begins printing. Print canceled because I only needed one.

**Expected results**
Only one should have printed.

**Additional Information**
This is the second time this has happened.
It has only occurred with the current TPU settings.

Octoprint Log
[octoprint.log](https://github.com/Ultimaker/Cura/files/2932174/octoprint.log)

**Comment by fieldOfView** [comment]
Please update your OctoPrint Connection plugin in the Marketplace. This bug was fixed two versions ago.

**Comment by dshapdesign** [comment]
Thanks!
