### ISSUE TITLE
"Minimum diameter" (support towers) should be called "maximum diameter"

### ISSUE THREAD

**Issue by AndreKR** [Ultimaker/Cura#5395]
The tooltip for Support -> Minimum Diameter says:

> Minimum diameter in the X/Y directions of a small area which is to be supported by a specialized support tower.

This ("minimum") sound like an overhang has to have **at least** this diameter to get a support tower.

[The docs](https://ultimaker.com/en/resources/20422-cura-support-settings) make it a bit clearer, but still call it a "minimum diameter":

> Support towers are only printed for support areas that are **smaller** than the set minimum diameter.

(Emphasis mine.)

Shouldn't it be the "**maximum** diameter of an area to still be supported by a support tower"?

**Comment by Ghostkeeper** [comment]
Yeah, I think you're right. This is where the setting is being used:

https://github.com/Ultimaker/CuraEngine/blob/24e57cbd6b215ca21b4cfb31ca474dec600042a9/src/support.cpp#L966

I think we'd have to rename this one. In general "Minimum Diameter" was a bit of a weird name as it did not specify that it belongs to support towers, which is okay if reading the settings in the list but not if you're filtering settings via the search box.

**Comment by LipuFei** [comment]
JIRA ticket: CURA-6311

**Comment by Ghostkeeper** [comment]
The setting has been renamed to Maximum Tower-Supported Diameter now, which is more accurate and more specific in that it mentions towers.
