### ISSUE TITLE
interface v2. Proposal Save toolpath button 

### ISSUE THREAD

**Issue by mennoberg** [Ultimaker/Cura#54]
Changing content....work in progress

**Comment by awhiemstra** [comment]
What does the toggle button do?

Also, I would prefer to avoid the term "toolpath". I think using "Save to ..." is clear enough.

**Comment by mennoberg** [comment]
![buttons2](https://cloud.githubusercontent.com/assets/6329918/8186956/7cc6ff42-144d-11e5-856c-9a83c9f3a053.png)
![cura v8 2](https://cloud.githubusercontent.com/assets/6329918/8186957/7ccb4b42-144d-11e5-9697-ba82bc48ff7d.png)

**Comment by mennoberg** [comment]
Save button function's in this environment

![cura v8 2](https://cloud.githubusercontent.com/assets/6329918/8187012/cfe70c9e-144d-11e5-9099-540175a6222d.png)

**Comment by BagelOrb** [comment]
@awhiemstra I think it's good to explicitly disambiguate between saving toolpath and saving the model. Peerhaps your problem is woth the word 'toolpath'? Perhaps just replace the term with 'gcode'?
