### ISSUE TITLE
[4.0.0 BETA2] Configuration reset removes plugins

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#5400]
Don't know if I'm wrong, but we don't want this, right? 😅 
Got a message which complained that there is something wrong with some settings of my printer.
Well, agreed to reset and it also killed my plugins. Luckily no uncommited contents have been removed.

**Comment by fieldOfView** [comment]
This is by design

**Comment by thopiekar** [comment]
Oh, well, then forget about it :grimacing:

**Comment by Ghostkeeper** [comment]
Some plug-ins install profiles to Cura (to support a certain type of printer) so it's best to remove all at once to be sure that Cura is completely reset to factory defaults.
