### ISSUE TITLE
Cura Connect: 3MF from another computer cannot print over network

### ISSUE THREAD

**Issue by BenoitValin** [Ultimaker/Cura#5422]
**Application Version**
3.6.0

**Platform**
MacOS Mojave

**Printer**
S5 and UM3

**Steps to Reproduce**
Save a 3MF on computer A, open 3MF on computer B, try to print via Cura Connect 

**Actual Results**
Cannot print build via connected Cura Connect Hosts on Computer B, a new printer is created instead.

**Expected results**
Print build via connected Cura Connect Hosts on Computer B, no new printer created. 

**Additional Information**
If 3MF is saved on Computer B, then opened again on Computer B, the build can be printed via connected Cura Connect Hosts on Computer B, same goes for A to A.

**Comment by Ghostkeeper** [comment]
Did you expect this:

1. Connect to printer on Computer A.
2. Save 3MF.
3. Load 3MF on Computer B.
4. Print via network to the printer that you connected to on Computer A.

Or did you expect this?

1. Connect to printer on Computer **B**.
2. Save 3MF from Computer A.
3. Load 3MF on Computer B.
4. Print via network to the printer that you were already connected to on Computer B.

We could implement one or the other, but not both. Currently (without testing) I'd expect the first scenario to work.

**Comment by BenoitValin** [comment]
Hi, 

  Both scenarios do not work, but the second scenario is what i am referring to
1 - Save 3MF from Computer A (prepare a build for a client)
2- Connect to printer on Computer B (client opens cura and connect to their Cura Connect Host)
3- Load 3MF on Computer B (client opens 3MF I sent them)
4 - Print via network to the printer that you were already connected to on Computer B (client prints on a printer connected to their Cura Connect Host)

  The problem is that at step 3, Cura creates a new local printer (even when no local printers are defined). Switching from a local printer to a Cura Connect Host deletes all the parameter over-rides specified in the 3MF to that of the last used on that Cura Connected printer. 

  The only way is saving to USB and printing with USB.

  This applies to 2 computer on the same LAN connected to the same Cura Connect Host, or computers in different locations (i.e. Ultimaker office and client's office)

I hope this clarifies the matter.

**Comment by nallath** [comment]
This has been fixed in the meantime.
