### ISSUE TITLE
Gap Filling needs optimization.

### ISSUE THREAD

**Issue by NicholasTracy** [Ultimaker/Cura#5423]
**Application Version**

3.6.0
**Platform**

Windows 10
**Printer**

Tevo Tarantula
**Steps to Reproduce**

Created a model that has a wall section that is 1.2mm thick. (Or exactly 3 line widths at 0.4mm)
Nozzle diameter is 0.4mm
Line Width is 0,4mm
Fill gaps setting set to Everywhere
Slice.

**Actual Results**

Tiny zig zag patterns are used to fill the gaps.
Print Time is greatly increased
Printer Vibrate furiously during this micro moves, can cause artifacts in the print.
![screenshot_20190312_013213](https://user-images.githubusercontent.com/33187904/54185977-867a6800-4467-11e9-93b9-0faca0b541c4.png)

**Expected results**

The Gaps should be instead filled with a straight wall section.
Print time should be much less.
**Additional Information**

Turning off filling gaps leaves a void the width of a singe wall line.
![screenshot_20190312_013128](https://user-images.githubusercontent.com/33187904/54185988-8bd7b280-4467-11e9-95a5-941f744fa5b6.png)

**Comment by smartavionics** [comment]
This has received some attention in 4.0 so please try the beta and see if it is better.

Alternatively, you can try one of my releases (also based on 4.0) that has a different implementation of wall gap filling and thin wall support along with other useful features and bug fixes. You can find releases for Linux and Windows at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by NicholasTracy** [comment]
Thanks I will take a look at it. I assume the most recent .exe file is safe to use?

**Comment by smartavionics** [comment]
Hi, if you are referring to my releases, then all I can say is that I try not to release anything that has any known bad problems, but, of course, I can't exhaustively test and the releases are based on the Ultimaker master branches so it's a case of YMMV. If you find a problem that is specific to my release (compared to the Ultimaker release), please open an issue on my Cura repo (smartavionics/Cura).

**Comment by NicholasTracy** [comment]
Will do. I will give it a try. I will also try 4.0 beta to see if its any better there.

**Comment by NicholasTracy** [comment]
The final verdict on this:
4.0 seems to be better at gap filling but some areas still cause issues. particularly when there is a gap wider than 2 wall thicknesses, it still does micro zigzags.
I have had the best luck so far with @smartavionics release all around.
