### ISSUE TITLE
[4.0.0-BETA-2] Adaptive Layers - maximum variation not honored for maximum

### ISSUE THREAD

**Issue by rwese** [Ultimaker/Cura#5431]
**Application Version**

4.0.0-BETA-2

**Platform**

Windows 10

**Steps to Reproduce**

* Set Layer Height 0.2
* Activate "Adaptive Layers"
* Adaptive layers max. variation 0.08
* Adaptive layers variation step size 0.04

**Actual Results**
* Layer Height, 0.2 max variation 0.08, steps 0.04, Result: 0.12 - 0.30
![grafik](https://user-images.githubusercontent.com/7153716/54436796-81513d80-4733-11e9-9923-5f3486d06386.png)
* Max variation 0.02 result in 0.18 - 0.30
![grafik](https://user-images.githubusercontent.com/7153716/54436920-cecdaa80-4733-11e9-901e-ae1ae2dd48c4.png)

**Expected results**

* Layer Height, 0.2 Max variation 0.08 should result in 0.12 - 0.28
* Layer Height, 0.2 Max variation 0.02 should result in 0.18 - 0.22

**Additional Information**

[PI3_xyzCalibration_cube.3mf.zip](https://github.com/Ultimaker/Cura/files/2971410/PI3_xyzCalibration_cube.3mf.zip)

Did work properly on 3.6.0

Hope this is complete "enough", i will try my luck looking at the source.

**Comment by rwese** [comment]
I am very very sorry, this is a user error... the initial layerheight was reset to 0.3 that threw me off.

**Comment by ChrisTerBeke** [comment]
Indeed the initial layer height is left untouched by this feature as its needed to ensure proper adhesion. Thanks for filing this quite detailed report though!
