### ISSUE TITLE
[3.1.0] File > New Project doesn't reset display

### ISSUE THREAD

**Issue by webware-nach-mass** [Ultimaker/Cura#5435]
**Application Version**
3.1.0

**Platform**
Kubuntu Linux

**Printer**
N/A

**Steps to Reproduce**
Load Model
Click "Prepare"
Save .gcode file
Use File > New Project or Ctrl+N

**Actual Results**
Printing time, filament length and weight remain displayed
"File saved" message remains displayed

**Expected results**
Informations relating to previous project (printing time, filament length and weight, messages) should be removed from display.

**Additional Information**
N/A

**Comment by nallath** [comment]
Does this also occur with the latest versions (eg 3.6 or 4.0)?

**Comment by Ghostkeeper** [comment]
Can't reproduce this in 4.0 right now.

**Comment by webware-nach-mass** [comment]
@nallath How can I install Cura 3.6 or 4.0 under Kubuntu Linux?
@Ghostkeeper 4.0 on which Platform?

**Comment by nallath** [comment]
You download the app image from the website, you change it's permissions so you can execute it and then run it.

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper 4.0 on which Platform?

This is on Ubuntu 18.10. However as this is all in Python I would not expect the behaviour to be different between my system and yours.
