### ISSUE TITLE
With nothing in "Preview", should default to "Prepare"

### ISSUE THREAD

**Issue by fiddlekrazy** [Ultimaker/Cura#5438]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by nallath** [comment]
Cura already defaults to prepare when there is nothing loaded. I'm not quite sure what you mean. Could you elaborate a bit more?

**Comment by fiddlekrazy** [comment]
It is not a big deal but after I have sliced, previewed, saved and deleted an object, I think it would be nice to automatically go back to Prepare.

**Comment by Ghostkeeper** [comment]
I usually tend to stay in Preview unless I want to change printers or printer configuration. I'd not like to have it automatically switch back.
