### ISSUE TITLE
how to judge that slicing is  finished

### ISSUE THREAD

**Issue by JockJo** [Ultimaker/Cura#5446]
**Application Version**

cura 3.6

**Platform**

windows 10

**Steps to Reproduce**

i got a problem when i ran a plugin wrote by myself. The detail as follow.

i ran it successfully from source. 
![Snipaste_2019-03-18_23-50-01](https://user-images.githubusercontent.com/27145141/54543502-b8944880-49d8-11e9-91cf-e9817fc21e4c.png)

but i ran it failed when i add the plugin into the plugin directory from Ultimaker Cura 3.6 that i download from website. the batchPrintOut window did not display.
![Snipaste_2019-03-19_00-30-36](https://user-images.githubusercontent.com/27145141/54546271-44f53a00-49de-11e9-965f-5df525822ff5.png)
 
In the end, i found that a parameter `self._backend` are different when i ran from source and download program. the source of `self._backend` as follow:
![Snipaste_2019-03-19_00-36-20](https://user-images.githubusercontent.com/27145141/54546636-0dd35880-49df-11e9-975e-8b2fce73394e.png)

**Expected results**

is there any method to judge  whether the  slicing  finished or not?
**Additional Information**

**Comment by Ghostkeeper** [comment]
I suggest looking into the Cura log to see whether it actually loaded the plug-in.

To see how you can make a package that you can drag-and-drop into Cura, I suggest you take a look at this: https://github.com/Ghostkeeper/X3GWriter/releases/tag/v1.1.9

The .curapackage files are .zip files with a certain format. You can mimic it there.
