### ISSUE TITLE
Multiple Objects -- only one has a first layer, the rest start at layer 2, floating

### ISSUE THREAD

**Issue by nebarnix** [Ultimaker/Cura#545]
Hi. When I load a bed full of objects, the first one loaded gets the skirt and the first layer, and the rest 'float' up at layer 2 with the fans on. The print fails spectacularly.

![image](https://cloud.githubusercontent.com/assets/643268/11196049/9a8c203c-8c72-11e5-8849-38b693b72135.png)

![image](https://cloud.githubusercontent.com/assets/643268/11196054/a42cb3d6-8c72-11e5-975d-18783d5ebfc9.png)

![image](https://cloud.githubusercontent.com/assets/643268/11196060/a8cc9ad2-8c72-11e5-82c4-77922074174a.png)

See them floating?!
![image](https://cloud.githubusercontent.com/assets/643268/11196080/c0fef7a8-8c72-11e5-9500-d8dde58086da.png)

**Comment by fieldOfView** [comment]
Note that this is legacy-cura, which is hosted here (but won't get any new development): https://github.com/daid/Cura
If you could check if this still happens with the recent betas, that would be great.
http://software.ultimaker.com/Cura_closed_beta/15.10/

**Comment by BagelOrb** [comment]
Problem persists in current Cura.
Solution is to pass drop_on_buildplate to the engine and enforce it per model.

**Comment by Ghostkeeper** [comment]
This is fixed for Cura 3.2.
