### ISSUE TITLE
Cura 4.0 Shutdown on "print to usb"

### ISSUE THREAD

**Issue by tdubya03** [Ultimaker/Cura#5451]
I'm using an anet a8 flashed to the latest marlin firmware and connected via usb to my pc. Just updated to 4.0 and now when i press Print to Usb the program itself shuts down. Doesn't matter if it's one small piece to print or large, whatever I load gives me the same end result. No prompt or error message, Cura just disappears. Guess I'll just do a rollback for now.

**Comment by fieldOfView** [comment]
Please upload the log from Cura 4.0 somewhere and post a link.
The log can be found via Help -> Show configuration folder. The file you are looking for is named cura.log

**Comment by Ghostkeeper** [comment]
Doesn't reproduce when I try printing via USB cable.
