### ISSUE TITLE
Support retraction is not working. 

### ISSUE THREAD

**Issue by SquidCap2** [Ultimaker/Cura#5453]
Support retraction is not working. It is impossible to use supports if you want perfect first layer finish since Cura does not retract properly between supports. There is an option to limit it but it clearly does not respect any settings but just goes from support to support. [https://imgur.com/a/KgKX1qJ](url)

This is kind of urgent; we are not kind of fucked if this is not fixed. Ok, i'm not so angry anymore, just wait until i get back to sanding a surface finish that has NOTHING else wrong with it, except 4 not even symmetrical diagonal lines across it.

**Comment by smartavionics** [comment]
Hi @SquidCap, without any further information, your angry rant is pretty much useless. Please, save the project file (File -> Save), zip it up and attach to this thread, then I may have some idea what you are talking about and can possibly be able to help. Thanks.

**Comment by smartavionics** [comment]
I have tried to reproduce this but can't as the travels between support all use retraction. So please provide the project file if you want some help. Thank.s

**Comment by Ghostkeeper** [comment]
![Screenshot from 2019-03-20 10-53-25](https://user-images.githubusercontent.com/2448634/54675232-72390980-4afe-11e9-91a6-822f2fac8c7c.png)

Also unable to reproduce this so far. Make sure that the "Limit Support Retractions" setting is disabled though.

**Comment by Enverex** [comment]
One bug I've noticed that may be related to this is that the "Limit Support Retractions" option is available only if you enable Supports, which makes sense, but when using Tree Supports, the main "Generate Support" option should be disabled, which in turn hides the "Limit Support Retractions".

In short: "Limit Support Retractions" isn't available when using tree supports as it's tied specifically to the original "Generate Supports" option and not enabling of support in general.

**Comment by Ghostkeeper** [comment]
Indeed, it was not being enabled for tree support. I fixed that [here](https://github.com/Ultimaker/Cura/commit/52ed79805e499bb7fe46872dff5550bc3c3c29b6) and at the same time found a whole slew of other settings that influence tree support but were not enabled by it (like support print speed).

**Comment by Ender3D** [comment]
> One bug I've noticed that may be related to this is that the "Limit Support Retractions" option is available only if you enable Supports, which makes sense, but when using Tree Supports, the main "Generate Support" option should be disabled, which in turn hides the "Limit Support Retractions".
> 
> In short: "Limit Support Retractions" isn't available when using tree supports as it's tied specifically to the original "Generate Supports" option and not enabling of support in general.

(Yes, I know.  Old post)
Not sure of prior versions, but in version 4.9.1, when using Tree Supports, you can enable the option in Settings for "Limit Support Retractions", and uncheck it.

If I understand the issue the OP was stating, I was having the same issue.  With the "Limit Support Retractions" checked, I was getting stringing/blobs between support towers which would mess up the layer in that area.  Unchecking this option solved this problem, at least for the print I currently have running.
