### ISSUE TITLE
cura 4.0 Languange settings 

### ISSUE THREAD

**Issue by Arseyticaret** [Ultimaker/Cura#5454]
Seems that when you choose local languange on preferences screen  it doesnt apply on main screen , Main screen languange still english , so i uninstall 4.0 for now and will load 3.6 again until this issue being solved

**Comment by Ellecross** [comment]
Hey @Arseyticaret, did you try restarting Cura after setting the language in preferences? 
If it still doesn't work, can you let me know which language were you trying with? 
Thanks.

**Comment by Ghostkeeper** [comment]
Until you've restarted, only the dialogues that you haven't opened in this run of Cura yet will have their language updated, because it generates the text upon first opening the dialogue.
