### ISSUE TITLE
Split model into parts disappeared 

### ISSUE THREAD

**Issue by paparico** [Ultimaker/Cura#5458]
**Application Version**
Cura 4.0

**Platform**
Linux (Kubuntu 18.04)

**Printer**
UMO+ (though irrelevant)

**Steps to Reproduce**
Load a multi parts model, try to split into parts (in order, for instance, to make it fit onto the plate)
Search for the good old "Split Model into parts"
do not find it
cry a litle

**Actual Results**
i cannot split the model into parts. 
when i move/rotate/scale the model, the 3 parts are affected

**Expected results**
3 parts can be moved and placed independently on the build plate

**Additional Information**
![image](https://user-images.githubusercontent.com/1750595/54648232-bc41d100-4aa5-11e9-89f5-7e6790adca06.png)

**Comment by smartavionics** [comment]
I think the mesh tools plugin that is available in the marketplace can split meshes...

![Screenshot_2019-03-19_23-23-29](https://user-images.githubusercontent.com/585618/54648423-163e9880-4a9e-11e9-9bdc-d16358163382.png)

**Comment by smartavionics** [comment]
Yes, it can, I just tested it.

**Comment by Ghostkeeper** [comment]
Probably this just happened because of the version upgrade and the user needs to update their plug-ins before they work again. We need to improve that UX.

**Comment by nallath** [comment]
The next version of Cura (4.1) is expected to have a notification system for plugin updates, so that should make it a lot easier to see that this is the case.

**Comment by paparico** [comment]
Ok, i thouht this was a core feature, i did not realize that this functionnality was provided by a plugin.
