### ISSUE TITLE
Localization problem in Spanish

### ISSUE THREAD

**Issue by alejandroluengogomez** [Ultimaker/Cura#5465]
**Application Version**
4.0.0

**Platform**
macOS

**Printer**
N/A

**Steps to Reproduce**
Open the app in Spanish, select Move (T)

**Actual Results**
Text says: 'Modelo Bloquear'

**Expected results**
Text should say: 'Bloquear modelo'

**Comment by Ghostkeeper** [comment]
Thanks for the suggestion. Corrected it for the next release.
