### ISSUE TITLE
Not remembering save path

### ISSUE THREAD

**Issue by regularlabs** [Ultimaker/Cura#5468]
Using Cura 4 on OSX.

When opening Cura and trying to save a file (gcode), the location is always set to HD (it was Applications in Cura 3).
![image](https://user-images.githubusercontent.com/13553242/54741155-cbb43d80-4bbd-11e9-8aa7-5f8891908750.png)

You can't save files to that location and you need to manually select the location to save to.
All fine.

However, after closing Cura and restarting it, it is reset to that default HD location again.

So question is:
Can the default location be set somewhere?
If not, can this issue be fixed, so that it remembers the last save location.

**Comment by regularlabs** [comment]
PS: May be connected to #4774, however that concerns the open path.

**Comment by Ghostkeeper** [comment]
Seems to be OSX-specific, since it seems to work fine on Ubuntu 18.10 and Windows 8.

**Comment by regularlabs** [comment]
Ok, but still a bug...

**Comment by regularlabs** [comment]
To make this even more confusing:
- I click on save, it shows me the incorrect HD root path
- I click on cancel
- I click on save again, it now DOES shows me the correct Downloads folder!

Go figure!

**Comment by diegopradogesto** [comment]
Confirmed, it happens on macOS.

For internal reference CURA-6411. I already did a fix [here](https://github.com/Ultimaker/Uranium/tree/fix_save_path_macOS), let's see if that still works for the three platforms.
