### ISSUE TITLE
Supports to nowhere - new option minimum surface area to support?

### ISSUE THREAD

**Issue by slikk66** [Ultimaker/Cura#5473]
CURA 4.0.0-BETA

https://imgur.com/a/jjpVciW

How to disable these tall thin supports that don't really seem to do anything?  Lots of times I get supports like these on tall objects that print all the way up (and usually fail) in tall thin towers, only to not really do anything.  Perhaps introduce a setting that needs to have a minimum surface area for a supported section?  Like unless the section is 2mm(square) don't bother with a support.

Thanks!

**Comment by Vandrasc** [comment]
Hi @slikk66, in Support category you have a setting called [Use Towers], can you disable the setting and reslice? Are the support towers then gone? Thanks!

**Comment by Ghostkeeper** [comment]
The minimum surface area to support is already implemented. It's new in Cura 4.0 in fact.
