### ISSUE TITLE
[4.0] UI issue in printer dropdown

### ISSUE THREAD

**Issue by muesli** [Ultimaker/Cura#5487]
**Application Version**
4.0

**Platform**
Linux

In the printer dropdown, there are two links displayed on top of each other:

![image](https://user-images.githubusercontent.com/146378/54865955-563b9f00-4d6e-11e9-8326-4ce29aa8079c.png)

**Comment by Ghostkeeper** [comment]
I can't reproduce this. Are you using the AppImage of Cura 4.0.0, or are you using a non-official release?

**Comment by DoXer67** [comment]
I can confirm the issue. Running LINUX ARCH with KDE (uptodate)

**Comment by nallath** [comment]
Are you using the appimage or using the build provided by the arch maintainer?

**Comment by DoXer67** [comment]
I use it from AUR, so the build provided by the arch maintainer.
https://aur.archlinux.org/packages/cura-git/

**Comment by muesli** [comment]
Same here actually. 43" UHD. Fairly regular DPI.

**Comment by Ghostkeeper** [comment]
Does this also occur in the [AppImage](https://github.com/Ultimaker/Cura/releases/download/4.0.0/Cura-4.0.0.AppImage)? If not, we may have to take this up with the AUR package maintainer.

**Comment by muesli** [comment]
@Ghostkeeper: yes, this only happens with the package from Arch, using Qt 5.12. The AppImage behaves fine in that regard.

**Comment by DoXer67** [comment]
Same for me, AppImage is OK

**Comment by Ghostkeeper** [comment]
I'm running from source as well using Qt 5.12 and it's not displaying here (Ubuntu 19.04)

![Uploading Screenshot from 2019-04-29 10-51-06.png…]()

**Comment by arvind-d** [comment]
I have the exact same issues with the UI. I'm running Manjaro with KDE & QT 5.13 on a 27" 4K monitor, 1.5x scaling and 144DPI font settings.

Running the AUR package I get weird UI issues such as the first application run wizard buttons disappearing. The AppImage works as intended only when setting QT_SCREEN_SCALE_FACTORS=1. If I attempt to run it directly I don't have positioning issues but the texts are all fuzzy and gunky. The AppImage version also doesn't integrate well with the system theme like the AUR version does (in the configuration window mostly, getting dark gray texts on dark backgrounds).

![cura_display](https://user-images.githubusercontent.com/5394380/61661929-5dec5f80-acde-11e9-9fd9-25bbbb4f3bd6.png)

Interestingly though, when running the AUR package via `sudo cura`, everything works as intended and displays perfectly. So, given that the app is running under the same QT version and displaying correctly with sudo, does this still have something to do with the QT version or maybe it could be some other conflicting settings?

![sudo vs appimage](https://user-images.githubusercontent.com/5394380/61661973-79576a80-acde-11e9-9116-b0557a2f0240.png)

**Comment by nallath** [comment]
Since this doesn't occur in the appimage, this issue can be closed.
