### ISSUE TITLE
[4.0] UI display issues

### ISSUE THREAD

**Issue by muesli** [Ultimaker/Cura#5489]
**Application Version**
4.0

**Platform**
Linux

Layout issues in print settings dropdown:

![image](https://user-images.githubusercontent.com/146378/54866055-c3036900-4d6f-11e9-96c7-e30b5f1280aa.png)

**Comment by nallath** [comment]
What version of linux are you using? Are you using the app image? What drivers are you using?

**Comment by fieldOfView** [comment]
As commented ![here](https://github.com/Ultimaker/Cura/issues/5496#issuecomment-475958896) @muesli uses an unofficial distribution of Cura on ArchLinux with Qt 5.12.2

**Comment by Ghostkeeper** [comment]
I'm also using Qt 5.12.2 when running from source, at the moment, but I'm not experiencing this problem. But if it doesn't occur when using the AppImage I think we can close this one. Let's hope that some updates from the package maintainers are able to figure out what the difference is between the versions of their libraries and the versions that the AppImage is using.
