### ISSUE TITLE
[4.0] Labels in config dialog are illegible

### ISSUE THREAD

**Issue by muesli** [Ultimaker/Cura#5490]
**Application Version**
4.0

**Platform**
Linux

Group labels for Material are illegible:

![image](https://user-images.githubusercontent.com/146378/54866075-08279b00-4d70-11e9-9b23-7b252d5dc055.png)

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/4637

**Comment by muesli** [comment]
@fieldOfView I've actually seen that ticket (and commented there as well), however it's marked as closed by the original reporter. I don't think it's really fixed though, he merely remarked a (wonky, if I may say so) work-around himself. Should probably re-open that one and close this one?

**Comment by bliser3d** [comment]
Some shortcomings in the dark theme, I tried to fix it in #5499.

**Comment by Ghostkeeper** [comment]
We've had the intent for a while to change the preferences screens to be Cura-themed rather than system-themed. That would resolve this issue as well.

**Comment by esopalumpa** [comment]
Comparing the image from this bug and the images from #6195, the situation got worse.
![62895591-7edd2900-bd4f-11e9-916c-bb4a77e51eeb](https://user-images.githubusercontent.com/39732563/63011358-6de40300-be88-11e9-9db2-4052c153cf7c.png)
![62895593-7edd2900-bd4f-11e9-85c8-5bbe36288262](https://user-images.githubusercontent.com/39732563/63011380-79372e80-be88-11e9-88b8-44b408577aa6.png)

**Comment by Ghostkeeper** [comment]
I don't think it got worse since we didn't really change anything here in that regard. But it'll depend on your system colours (and which part of those system colours Qt can read).

**Comment by esopalumpa** [comment]
Possible.
But this is the standard “Breeze dark” theme from KDE, so nothing fancy or makeshift.

**Comment by esopalumpa** [comment]
It get’s a bit better if -style windows is given as option.

**Comment by berberic2** [comment]
Problem still exists in 4.3

**Comment by MaxVerevkin** [comment]
Problem still exists in 4.5 and -style option only partially solve it

**Comment by NovaViper** [comment]
Will this issue ever get fixed?

**Comment by Ghostkeeper** [comment]
It's still on our planning, since it's really quite difficult/messy code in the material manager. It's sometimes in the way of making improvements there, so we'd like to refactor that and at the same time give it Cura's theming rather than system theming which would fix this issue.

**Comment by jaggzh** [comment]
> this seems to fix the issue (on kde plasma 5)
> env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP /bin/cura

This works for me. KDE Plasma also.

**Comment by NovaViper** [comment]
> this seems to fix the issue (on kde plasma 5)
> env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP /bin/cura

This works! I have KDE Neon, I also used Cura's app image instead of the bin. However it makes the menu use the light theme instead of dark theme; but it's better than nothing

**Comment by Schokobecher** [comment]
Sadly only a partial workaround for me. Start and End Gcode are not readable, but if copy/pasted into another window are correct. I assume some issues with the font used

![image](https://user-images.githubusercontent.com/1642634/93620929-ff676200-fa04-11ea-9b74-ffb61818f2c4.png)

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?

**Comment by LightTemplar** [comment]
@GregValiant 
I think so. Version 5.8.1, appimage, "Ultimaker Dark" theme:
![image](https://github.com/user-attachments/assets/ae79d550-6f83-4a34-aac5-04c996184bb0)

**Comment by GregValiant** [comment]
Thanks.  I go ahead and close this.
