### ISSUE TITLE
[4.0] UI DPI unawareness

### ISSUE THREAD

**Issue by muesli** [Ultimaker/Cura#5496]
**Application Version**
4.0

**Platform**
Linux

The UI seems generally pretty unaware of the underlying display's DPI. Mixed with what seems to be hard-coded positioning instead of using anchors and alignments, this leads to the UI breaking in many, many ways.

I've already filed separate tickets for the first few issues I encountered, but by now I'm aware that this is broken throughout the entire UI and it shows in so many places, that I'm not even sure where to begin and end with opening new tickets.

![image](https://user-images.githubusercontent.com/146378/54870121-b2b8b180-4da2-11e9-8b9a-3434e7f500e1.png)

![image](https://user-images.githubusercontent.com/146378/54870138-d5e36100-4da2-11e9-929b-e4a086fb8d2a.png)

**Comment by fieldOfView** [comment]
Perhaps ypu can share more about your environment and how you run Cura?

What Linux (version and distro), how did you install Cura (note that the only officially supported way is using the AppImage), and what version of Qt do you use?

**Comment by fieldOfView** [comment]
Other users have reported layout issues with Qt 5.12. The official AppImage uses Qt 5.10.

**Comment by muesli** [comment]
@fieldOfView This is running on ArchLinux with Qt 5.12.2. I'll try the official AppImage and report back.

**Comment by muesli** [comment]
Confirmed, the AppImage looks a lot healthier. Thank you!

**Comment by fieldOfView** [comment]
Could you check/update/close your other issues related to ui issues too?
