### ISSUE TITLE
How does cura15.10 has "printer with USB" function ?

### ISSUE THREAD

**Issue by shawnlintw** [Ultimaker/Cura#550]
Hi there,

I install the cura 15.10 version on my PC.
OS : Windows 7 64 bit.  There is a COM port on my computer (COM 1).
FDM : Prusa i3 

Usually, I plug in the FDM via USB connection. 
I has checked the connection status, FDM using the virtual COM port 3 to communication.
The driver has installed. It works good in Cura 15.04 on the same computer.

The question is I can't see any "printer with USB" button as when I change Cura to version 15.10.
Has anything I forget did ?
Could anyone helps ?

**Comment by Ghostkeeper** [comment]
Perhaps Cura 15.04 is still running? An instance of Cura tends to hog the USB connection for itself. The new Cura 15.10 checks for available USB connections at startup.

**Comment by nallath** [comment]
Post the logs. It should mention something about trying to connect with certain ports (and how well that went)
