### ISSUE TITLE
[4.0] models can no longer be moved freely with the mouse

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#5501]
Cura 4.0.0
My printer have a dual Extruder.
1. Can the Print settings of both Extruder be displayed side by side  (without switching)?

2. The objects can no longer be moved freely with the mouse. Only with the help of the three arrows.

**Comment by rburema** [comment]
@lwbsbde 
1. No, sorry :-(
2. I find that it works if I first select (let go) then do the drag. If this isn't working for you, it's a bug.

**Comment by rburema** [comment]
In the latter case, please provide wich platform you are on (win, mac, linux), and which graphics card you use.

**Comment by Ghostkeeper** [comment]
Also take care that you don't start dragging too close to the origin point of the three arrows. It's ambiguous then which of the directions you want to drag, so we've prevented that. I think we can make some improvements in that regard.

**Comment by lwbsbde** [comment]
Yes. It works the way you described it. For small objects, I have to enlarge the view to make it work.

**Comment by lwbsbde** [comment]
a simultaneous view of the settings of 2 extruders would be great.

**Comment by fieldOfView** [comment]
Please open a new issue for that. Add a sketch.

**Comment by Ghostkeeper** [comment]
Made a fix for that: https://github.com/Ultimaker/Uranium/commit/1aa4fe1ee5a27ce6789cebfa39a0489e1ac9ad0a
