### ISSUE TITLE
supports density, Cura 4.0

### ISSUE THREAD

**Issue by jornada812** [Ultimaker/Cura#5525]
strange behavior of the field density support. it is impossible to change the value if you do not change the distance between the support lines

**Comment by Ghostkeeper** [comment]
Yeah that's because a higher support density can only be achieved by putting the support lines closer together. Your printer can't actually change the mass of the filament so it needs to put the filament closer together to change the density of the support infill.

We compute the support line distance from a combination of the line width and desired density using this formula: https://github.com/Ultimaker/Cura/blob/4f5aee629894e8d8f5dd2414affbb155d59a9f4b/resources/definitions/fdmprinter.def.json#L3886

**Comment by jornada812** [comment]
It is beautiful, but intuitively incomprehensible. Disabled fields must be accompanied by tooltips or other instructions why the user can not change the value and how it can be changed. Otherwise, this leads to an opaque interface and lack of understanding in working with your program.

Отправлено из приложения "Почта" для Windows 10

От: Ghostkeeper
Отправлено: 29 марта 2019 г. в 12:55
Кому: Ultimaker/Cura
Копия: jornada812; Author
Тема: Re: [Ultimaker/Cura] supports density, Cura 4.0 (#5525)

Yeah that's because a higher support density can only be achieved by putting the support lines closer together. Your printer can't actually change the mass of the filament so it needs to put the filament closer together to change the density of the support infill.
We compute the support line distance from a combination of the line width and desired density using this formula: https://github.com/Ultimaker/Cura/blob/4f5aee629894e8d8f5dd2414affbb155d59a9f4b/resources/definitions/fdmprinter.def.json#L3886

**Comment by nallath** [comment]
I've added an extra hint to the tooltip that should make this easier to understand. 
![ChangedTooltip](https://user-images.githubusercontent.com/3922611/55314846-4a856200-546b-11e9-85ae-87ca16582bb8.png)

**Comment by Liger0** [comment]
> 
> 
> I've added an extra hint to the tooltip that should make this easier to understand.
> ![ChangedTooltip](https://user-images.githubusercontent.com/3922611/55314846-4a856200-546b-11e9-85ae-87ca16582bb8.png)

I don't want to be a dumb, but "overriden" is missing a d.

**Comment by Ghostkeeper** [comment]
That's not dumb. In fact, it seems some of us got this consistently wrong. Fixed here: https://github.com/Ultimaker/Cura/commit/bd1712cb10749914d79053426ff0397c1219b583
