### ISSUE TITLE
[Feature]Add object height in generated gcode

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#5526]
**Application Version**
4.0.0-BETA-2
**Platform**
Any
**Printer**
Any
**Steps to Reproduce**
Generate any gcode
**Actual Results**
Meta information is available in gcode - like amount of layers and layerheight - filament used ...
**Expected results**
Learn also the object height from the meta data in all possible slicing modes.
Actually one can easily calculate the model height as (#layers * layerheight), but this is not working in case adaptive layer feature is activated - nor can you tell if it is activated just looking at a generated gcode header.
**Additional Information**
Total model height would come in super handy for post-processing gcode. Obviously one can know about total object height by checking at the end of the file what was the highest Z value on which extrusions happen, but that requires more effort of the post-processor...

**Comment by Ghostkeeper** [comment]
This information is available in the Griffin header at the moment (if you were to slice for an Ultimaker 3 or S5). We could put it in the RepRap header as well, maybe.

**Comment by Ghostkeeper** [comment]
It'll now be printed at the top of the file like this:

```
;FLAVOR:Marlin
;TIME:626
;Filament used: 0.111376m
;Layer height: 0.1
;MINX:37.2
;MINY:37.2
;MINZ:0.3
;MAXX:62.8
;MAXY:62.8
;MAXZ:10
;Generated with Cura_SteamEngine master
```

That is a 10mm cube. In the X and Y direction the cube is centred on the 100x100mm build plate, and there's a brim around it. In The Z direction you can see the height of the last layer and the height of the first layer.

**Comment by MB3Y** [comment]
:thumbsup: :yum:
