### ISSUE TITLE
[4.0] Gantry height preset

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5528]
**Application Version**
4.0

**Platform**
win 10 x64

**Printer**
Doesn't matter

**Steps to Reproduce**
Add a new printer

**Actual Results**
In the Gantry height field there are so many 9 that the mm unit measure is not even visible.

**Expected results**
The numbers and the mm should be kept separate

**Additional Information**
![gantry height](https://user-images.githubusercontent.com/20385116/55251882-cf952f00-5251-11e9-8249-7b2d8d54b385.png)

**Comment by Ghostkeeper** [comment]
I've made this value default to the printer height. Makes sense anyway.

**Comment by maukcc** [comment]
Unless specified in the definition file, the printer height is a good value.
At present it is printer height, regardless of what is in the definition file.

**Comment by Ghostkeeper** [comment]
No, the printer definition can still overwrite it. Only the `default_value` gets hidden by the `value` now. Fixed that: https://github.com/Ultimaker/Cura/commit/e26e825d8318c70e4755a25f9b21b5f91293eca8
