### ISSUE TITLE
[4.0.0] Price not showing

### ISSUE THREAD

**Issue by konqiDAM** [Ultimaker/Cura#5529]
**Application Version**
4.0.0

**Platform**
Any

**Printer**
Any

**Steps to Reproduce**
Just slice anything

**Actual Results**
Price cost is not showing

**Expected results**
Price cost should be next to filament usage

![Price](https://user-images.githubusercontent.com/44301655/55265975-ed2abe80-527a-11e9-973f-75bf57c63b71.png)

**Comment by wize1** [comment]
It shows, but shows incorrectly. For me it shows 1/10 of the price.

**Comment by nallath** [comment]
Fixed for 4.1! 

I've made it in such a way that it only shows if the material cost is set (as to not confuse people why by default the price is always 0)
