### ISSUE TITLE
Per Object Settings Wrong Global

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#553]
Build: 11-17

Steps:

Set global profile up for one object.
Duplicate Object
Click per object settings, and customize one setting on one object.

Expected behavior: 

Customized object prints with identical settings, besides those chosen to customize.

Observed behavior:

Customized object uses wrong baseline profile, and settings are not matched with object 1.

![image](https://cloud.githubusercontent.com/assets/12439543/11326437/73554446-912f-11e5-8e42-9e58895bec4a.png)

![image](https://cloud.githubusercontent.com/assets/12439543/11326440/879a595a-912f-11e5-9484-1f909d029a6c.png)

![image](https://cloud.githubusercontent.com/assets/12439543/11326441/979550d0-912f-11e5-8f0f-5d2543128d05.png)

**Comment by BagelOrb** [comment]
most probably fixed in the mean time
