### ISSUE TITLE
[4.0.0] Price shows wrapped

### ISSUE THREAD

**Issue by wize1** [Ultimaker/Cura#5532]
**Application Version**
4.0.0

**Platform**
Windows

**Printer**
Any

**Steps to Reproduce**
Set price for filament to prefix with RUB and slice any model. 

**Actual Results**
![image](https://user-images.githubusercontent.com/8410799/55273912-d7e97a80-52e2-11e9-95b7-42756981ee25.png)

It wraps half of price value to next line, which is confusing.

**Expected results**
Whole price should be displayed on one line.

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?
