### ISSUE TITLE
heated platform M190 command missed after #postprocess

### ISSUE THREAD

**Issue by EugeneSkrebnev** [Ultimaker/Cura#554]
dev 20151117
got this gcode:
;FLAVOR:RepRap
;TIME:167

;POSTPROCESSEDM190 S36.000000
M104 S200.000000
M109 S200.000000
; [mm] mode
G21
; absolute mode
G90
; Home
G28
; Heated bed control
; Absolute E
M82
M107
G92 E0
G1 Z6 E15 F600     ; prime to get pressure
G92 E0
..........
..........
..........

**Comment by nallath** [comment]
With what post processing script did you generate this?

**Comment by nallath** [comment]
Oh nevermind, this was fixed by commit nallath/PostProcessingPlugin@714ffaa7cac6c0dd13e1268720e083650b563a6a

**Comment by EugeneSkrebnev** [comment]
:+1: nice work!
