### ISSUE TITLE
[4.0.0] Text Font corrupted on Neon (Ubuntu + KDE)

### ISSUE THREAD

**Issue by alvaro893** [Ultimaker/Cura#5542]
**Application Version**
4.0.0

**Platform**
KDE Neon 5.15
Ubuntu 18.04 is the base system

**Printer**
Anycubic i3 mega

**Steps to Reproduce**
It is quite inconsistent.  It randomly happens when using the UI. Sometimes it doesn't happen at all.

**Actual Results**
Text Fonts get corrupted. Impossible to read

**Expected results**
Unmodified text

**Additional Information**
![cura-problem0](https://user-images.githubusercontent.com/8163929/55292581-50406080-53f5-11e9-959b-35d6aee2fe85.png)
![Screenshot_20190331_204507](https://user-images.githubusercontent.com/8163929/55292671-6ac70980-53f6-11e9-8d06-15642d4cda5d.png)

**Comment by droidmahn** [comment]
I'm having similar issues Arch linux + KDE

**Comment by nallath** [comment]
Are you using the appimage?

**Comment by alvaro893** [comment]
@nallath  yes.

**Comment by Ghostkeeper** [comment]
Haven't seen this happen, so far. Neither on the AppImage or running from source on my Ubuntu 18.10 computer.

I'm not quite sure how to approach a fix for this. Do you know if this happened also in 3.6 or before?

**Comment by alvaro893** [comment]
I downloaded the 3.6 AppImage to test it. It seems that it works just fine. No text corruption. Could this be related somehow to Nvidia drivers?

**Comment by Ghostkeeper** [comment]
Maybe. Hard to say unless we find a pattern in the people who experience this. I'm not seeing this on the NVidia drivers on Windows but that's a whole different beast of course.

It's funny how the Prepare, Preview and Monitor stages are still rendering fine.

**Comment by alvaro893** [comment]
I tried 4.0.0 AppImage in a old laptop with Kubuntu installed on it. It worked fine. This laptop uses Intel Integrated Graphics (rev 02) instead.

**Comment by Ghostkeeper** [comment]
Maybe it only happens for text that is not exactly pixel-aligned?

**Comment by fieldOfView** [comment]
It looks like it is a specific font size. That could mean the bitmap representation that is created when a font is loaded at a certain size is corrupted somehow.

The text looks well aligned to me; I checked the rendering of those element, and non-aligned text shows up on Windows because it uses a different renderer.

**Comment by alvaro893** [comment]
Some news about this issue!

After going to Settings->Fonts->Anti-aliasing and set it from "vendor default" to "enabled". The font corruption disappear altogether.

Also fonts look a bit better.

**Comment by bmveee** [comment]
One more note to add to this - it's not enough to 'enable' anti-aliasing, you have to go to Configure (from the Font menu) and set it to Full hints. At least that's what I had to do...
