### ISSUE TITLE
[4.0] Sidebar GUI plugin messes positions

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5548]
**Application Version**
4.0

**Platform**
Windows 10 x64

**Printer**
Custom

**Steps to Reproduce**
Install from the market the "Sidebar GUI" plugin

**Actual Results**
The position of the words and graphics is messed up.

**Expected results**
Graphics should be kept in order.

**Additional Information**
![GUI](https://user-images.githubusercontent.com/20385116/55337931-e03ae480-549f-11e9-92a3-7ab6fa4ea02d.png)

**Comment by fieldOfView** [comment]
The Sidebar GUI plugin has its own issue queue here:
https://github.com/fieldofview/cura-sidebarguiplugin/issues
