### ISSUE TITLE
[4.0] Error message on startup, then crash.

### ISSUE THREAD

**Issue by ryandavidsongns** [Ultimaker/Cura#5551]
Hey,

I've been using 4.0 since it was released but this morning when i tried to open it i get the error in the screenshot. Once i close the error, cura also closes. I believe there were some microsoft updates rolled out on our work PCs over the weekend, so this may have something to do with it?
Also 3.6 works fine.

![Cura Crash](https://user-images.githubusercontent.com/49169057/55355223-30f42100-5524-11e9-8cd4-39ba4c44ea34.JPG)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/3031084/DxDiag.txt)
[cura.log](https://github.com/Ultimaker/Cura/files/3031085/cura.log)

**Comment by ryandavidsongns** [comment]
> It looks like a file in your Cura configuration got corrupted in an interesting way.
> 
> If you go to C:\Users\ryand\AppData\Roaming\cura\ and rename the folder 4.0 to something like 4.0.bak, you should be able to start Cura again.

Thanks, that sorted it!

**Comment by fieldOfView** [comment]
Good to hear. If you could zip up that old 4.0 folder and post a link to it, we can see what actually went wrong (and hopefully get at least a more useful crash dialog that helps you reset Cura the way you now did manually).

**Comment by ryandavidsongns** [comment]
> Good to hear. If you could zip up that old 4.0 folder and post a link to it, we can see what actually went wrong (and hopefully get at least a more useful crash dialog that helps you reset Cura the way you now did manually).

Here you go

**Comment by ryandavidsongns** [comment]
> Good to hear. If you could zip up that old 4.0 folder and post a link to it, we can see what actually went wrong (and hopefully get at least a more useful crash dialog that helps you reset Cura the way you now did manually).

Here you go
[4.0.bak.zip](https://github.com/Ultimaker/Cura/files/3031540/4.0.bak.zip)

**Comment by fieldOfView** [comment]
DEVS: in GlobalStack.configuredConnectionTypes, there is no resilience against a None in the list of connectiontypes. Needs a try/except.

**Comment by nallath** [comment]
Good spot. Fixed that for 4.1
