### ISSUE TITLE
[4.0] "Infill layer thickness" -setting wont become visible

### ISSUE THREAD

**Issue by swatti87** [Ultimaker/Cura#5553]
Even if i tick ALL the boxes some settings wont become visible.

This is a VERY important setting for me as i do my infilling every 3-4 layers to save time.

EDIT: It also seems 4.0 has settings from 3.6 with my layer thickness in it and now it cant even slice the model... [Rage smiley]

**Comment by fieldOfView** [comment]
Make sure that the 'infill density' is greater than 0, and 'spaghetti infill' is not enabled.

**Comment by Ghostkeeper** [comment]
Not able to reproduce, unless I set Infill Density to 0 or enable Spaghetti Infill. Seems to be behaving as expected. What are your reproduce steps?

Maybe there is a bug that this setting gets shown too often if you set the infill line distance to 0. It shouldn't show up then I suppose.

**Comment by swatti87** [comment]
Hmm... It may be due to the fact that i used a different-than my layer height in 3.6

Is there a way to just "force" all settings to be visible when toggled? I fully prepared to face all mess that might introduce.

**Comment by Ghostkeeper** [comment]
If your infill layer thickness is not an exact multiple of the layer height it will get rounded.

There is a mod that you could make to make all settings visible even if they don't have an effect on your print: Go into C:\Program Files\Ultimaker Cura 4.0\resources\definitions\fdmprinter.def.json and remove all lines there with `"enabled":` in them. However that will make settings visible of which Cura thinks they are not used in your print, so if you then edit the setting nothing will happen. Of course, be sure to also use the hamburger menu next to the settings search bar to set "Show All Settings".
