### ISSUE TITLE
GCode viewer shows invisible color for extruder 8 (T7)

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#5562]
**Application Version**
4.0.0
**Platform**
Windows
**Printer**
Curstom
**Steps to Reproduce**
Slice gcode - add extruder T7 in your gcode

**Actual Results**
Lines under T7 are not shown - but present for the carefull watcher... rotate your model to see that these invisible lines sometimes hide other lines correctly as if they are there.

**Expected results**
I expect a "regular" extruder color also for the 8th extruder (T7) - since that is the current max supported by Cura.

**Additional Information**
Segment 3 of the slug in attached picture is there, but with transparent color
![2019-04-03](https://user-images.githubusercontent.com/29209302/55480240-199a5e00-5620-11e9-98ca-54bd40f01c8e.png)

**Comment by Ghostkeeper** [comment]
Not able to reproduce this bug. Here's all 8 extruders. Looks colourful.
![Screenshot from 2019-04-04 12-57-19](https://user-images.githubusercontent.com/2448634/55550745-49f20300-56d9-11e9-9444-32cff2a7cde8.png)

Maybe you can click on the Colour Scheme drop-down and make sure that Extruder 8 is checked?
