### ISSUE TITLE
Color Scheme "Material Color" doesn't allow (de)selection of extruders 5 till 8

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#5563]
**Application Version**
4.0.0
**Platform**
Windows
**Printer**
Custom defined : max possible extruders: 8
**Steps to Reproduce**
Slice multi part object (articulated items are pretty easy to do and use Mest Tool "Split")
Select a separate extruder for each object.
Now select Color Scheme " Material Color"
**Actual Results**
Observe that you can hide/view extruders T0 until T3, but T4 until T7 are disabled for the user despite that the printer has as many extruders.
**Expected results**
I'd like to be able to enable and disable each extruder defined in my printer.
**Additional Information**
Attached picture shows this behavior from gcode view - but also directly after slicing these extruders are disabled - even though (some of) these extruders where used in the slicing.
![2019-04-03 (1) png](https://user-images.githubusercontent.com/29209302/55480890-85c99180-5621-11e9-886f-89be3d0eefc5.jpg)

**Comment by Ghostkeeper** [comment]
Yeah, I see this as well! Weird bug.

**Comment by LipuFei** [comment]
Fixed in f2234cffa for `master`.
