### ISSUE TITLE
Setting up materials for 8 extruder custom machine fails on material 8

### ISSUE THREAD

**Issue by MB3Y** [Ultimaker/Cura#5564]
**Application Version**
4.0.0
**Platform**
Windows
**Printer**
Custom 8 extruder machine
**Steps to Reproduce**
Define an 8 extruder machine and set the materials per extruder.
All fine up till extruder 7 - full dropdownbox available.
**Actual Results**
For extruder 8 you can only select a very limited amount of materials in the dropdown
**Expected results**
I expect to have the same possibilities for selection in extruder 8
**Additional Information**
In the attached pictures the Head and all next sections are selected as extruder 8-7-6-5-4-3 (as a good observer can see of course due to the colors matched to them 👍 )
![CorrectMaterialSelectionForExtruderNo7](https://user-images.githubusercontent.com/29209302/55481552-f1602e80-5622-11e9-945c-1f1a579c4b4f.png)
![InCorrectMaterialSelectionForExtruderNo8](https://user-images.githubusercontent.com/29209302/55481623-16ed3800-5623-11e9-8fa1-3828bf8431f4.png)

**Comment by Ghostkeeper** [comment]
I can't reproduce this, but I have a strong feeling that your 8th extruder is not configured the same way as the rest. So please do these steps:

1. Click your printer's name and click on "Manage printers".
2. Click the "Machine Settings" button.
3. Go to the tab for extruder 8.
4. Check whether the "Compatible Material Diameter" field is properly set to 1.75mm.

**Comment by MB3Y** [comment]
And - yes - we got a winner!!
Filament diameter was indeed still on the default instead of the 1.75mm like all the others!
Thanks for figuring that out. You can close this point.
