### ISSUE TITLE
Support when Support not selected

### ISSUE THREAD

**Issue by slopsjon** [Ultimaker/Cura#5567]
**Application Version**

Version 4.0
**Platform**

Windows 10
**Printer**

Ender 3
**Steps to Reproduce**

Open file and look at preview and support settings
**Actual Results**

Printed with support when support not selected
**Expected results**

See picture
**Additional Information**

Screenshot
![cura](https://user-images.githubusercontent.com/45715389/55513392-78ca9380-565d-11e9-9320-bd6ceb0547bd.jpg)
[CE3_SquashFeet_pk8_m5_v2.3mf.zip](https://github.com/Ultimaker/Cura/files/3040758/CE3_SquashFeet_pk8_m5_v2.3mf.zip)

**Comment by smartavionics** [comment]
Perhaps the tree support option is enabled?

**Comment by slopsjon** [comment]
Ah yes it is
