### ISSUE TITLE
Cura 4.0.0 slicing hangs at 50%

### ISSUE THREAD

**Issue by ericduns** [Ultimaker/Cura#5568]
**Application Version**
4.0.0

**Platform**
Windows 10 Enterprise

**Printer**

Creality Ender 3

**Steps to Reproduce**

Added an .stl file and clicked slice

**Actual Results**

slices to about 50%, after a while backs up to about 30% and jumps back up to 50% and then stays hung.

**Expected results**

slicing hangs at 50%

**Additional Information**

[curaLogFile.zip](https://github.com/Ultimaker/Cura/files/3040962/curaLogFile.zip)

[CE3_Horn.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/3040966/CE3_Horn.curaproject.3mf.zip)

![hungSlice](https://user-images.githubusercontent.com/12908400/55516572-d7c2e500-562a-11e9-80f6-4e1674d2b3b0.PNG)

**Comment by Ghostkeeper** [comment]
Did you find a solution to this? Why was it closed?

**Comment by ericduns** [comment]
Yes, turned out that having tree supports enabled on this project seemed to
make it hang. After switching back to default supports it sliced just fine.

**Comment by Ghostkeeper** [comment]
For some highly detailed and tall models, tree support can take a significant amount of time. As in, half an hour is not entirely unusual.

**Comment by ericduns** [comment]
Oh wow thanks for the info!
