### ISSUE TITLE
Nozzle undefined when saving project

### ISSUE THREAD

**Issue by Nekksys** [Ultimaker/Cura#5572]
Whenever I save a project in Cura, the nozzle always shows as "undefined" on the summary page. I can provide the project file if needed.

**Application Version**

Cura 3.6 and 4.0

**Platform**

Linux (Ubuntu)

**Printer**

Creality Ender 3 

**Steps to Reproduce**

Create printer. Check settings. Create material. Check material settings. Load STL. Save project. Nozzle is undefined in summary.

**Actual Results**

Nozzle is undefined in sunnary

**Expected results**

Nozzle should be defined as per settings in machine; in my case, 0.4mm.

**Additional Information**

See attached screen caps.
![CE3-Settings1](https://user-images.githubusercontent.com/49285869/55574532-4313c200-56d2-11e9-8c3d-1ec8afa7a8fa.png)
Creality Ender 3 settings, printer with adjusted bed size defaults.

![CE3-Settings2](https://user-images.githubusercontent.com/49285869/55574543-47d87600-56d2-11e9-8b55-86c8a38e0964.png)
Creality Ender 3 settings, extruder; note nozzle size is set to 0.4mm.

![Cura-NozzleError](https://user-images.githubusercontent.com/49285869/55574558-4d35c080-56d2-11e9-9b38-c5f9a509208a.png)
Save project, summary window; note nozzle size is undefined.

**Comment by nallath** [comment]
You're right, but only partially. Your machine doesn't have a selectable nozzle type (in the way that some printers have it, such as the um2 or um3), so it should not be shown at all.

This has been fixed for the next release (4.1)

**Comment by Nekksys** [comment]
So basically, it was an oversight on the part of the Cura programmers?

**Comment by nallath** [comment]
No, it is using it. We also have a thing called "variant profiles", which actually changes what profiles are used based on what nozzle type you have selected. Those profiles are pre-defined.

Most third party profiles don't have that well-defined profiles and thus don't use all the cool features that are out there. This is also the case for the ender profiles.

**Comment by Ghostkeeper** [comment]
Your printer defines a nozzle size, which is saved with the project. You don't have different built-in profiles for different nozzles, so you can't select that, but you might have changed the nozzle size yourself and that would just get saved right along.

Many people identify a "nozzle" only by the size of the opening in the bottom, but Cura sees a "nozzle" as a profile which could be any collection of settings. Nozzle size is not a special setting in any way. It gets saved right along with the profiles. We have no reason to display just the nozzle size there. For instance, the Ultimaker S5 has a nozzle profile for AA0.4 and BB0.4 which have the same nozzle size but have different other properties.

**Comment by Nekksys** [comment]
OK. There is, however, a very sound reason to display a single head printer's nozzle size in the summary: so it doesn't look like an error. To anyone with programming experience, "undefined" is an error to be avoided at all costs. Glad you got that sorted for v4.1!
