### ISSUE TITLE
Support Brim ignored if Build Plate Adhesion set to none

### ISSUE THREAD

**Issue by krz4tw** [Ultimaker/Cura#5575]
As mentioned by paukstelis in #4829

Quote "If Build Plate Adhesion is None, support brim is ignored, even if the box is checked. There would be plenty of cases where you want the support brim but not other types of adhesion."

**Comment by Ghostkeeper** [comment]
Ah, we found this as well and fixed it in master. It should get fixed for you in the upcoming 4.1 release.
