### ISSUE TITLE
[4.0] Wrong material assignment for dual extruder machine

### ISSUE THREAD

**Issue by yyh1002** [Ultimaker/Cura#5580]
**Application Version**
4.0

**Platform**
Windows 10

**Printer**
Ultimaker 2+ DXU mod
gMax 1.5 Plus Dual Extruder

**Steps to Reproduce**
Load a model, set it to extruder 2 (blue). 
Change adhesion and support extruder to extruder 2 (blue).
Slice the model. 
Basically attempting to do a pure extruder 2 print without heating up extruder 1.
![Screenshot (144)_](https://user-images.githubusercontent.com/2662990/55627389-ce3ba780-57f9-11e9-9cdb-4fb2457e5bda.png)

**Actual Results**
The tool path shows color of extruder 1 (yellow). 
![Screenshot (145)_](https://user-images.githubusercontent.com/2662990/55627407-d85da600-57f9-11e9-92a5-f4551f7677a1.png)

**Expected results**
The tool path shows color of extruder 2 (blue). 

**Additional Information**
I tested with both the Mark2/DXU for UM2 custom machine and the included gMax 1.5 plus dual extruder, same problem occurs. 
I've been doing this in 3.6 with no problem. Only 4.0 has this issue. 

Thanks

**Comment by Block137** [comment]
#5550
Discovered just few days ago

**Comment by nallath** [comment]
Fixed for 4.1
