### ISSUE TITLE
Model generated differs depends on orientation

### ISSUE THREAD

**Issue by mqudsi** [Ultimaker/Cura#5584]
**Application Version**
Cura 4.0

**Platform**
Windows 10 64-bit

**Printer**
Ultimaker S3

**Steps to Reproduce**
Load the attached project and change orientation, once facing up and again facing down.

**Actual Results**
The model contains support-like structures in the primary object not present in the original STL when the negative space faces down, but not when facing up.

![image](https://user-images.githubusercontent.com/606923/55675781-f0cad080-588c-11e9-88b9-a196e97c85bc.png)

![image](https://user-images.githubusercontent.com/606923/55675787-0dff9f00-588d-11e9-93d8-bf078c881f4f.png)

**Expected results**
There should be no additional support-like filling in either orientation. If there as an error in the STL, the result should be the same regardless of orientation. If additional filler material is needed that isn't present in the STL, it should be generated as support, not as primary.

**Additional Information**
Project attached: [UM3E_Kitchen Baseboard Hooks v2.zip](https://github.com/Ultimaker/Cura/files/3050978/UM3E_Kitchen.Baseboard.Hooks.v2.zip)

**Comment by nallath** [comment]
You have "Make overhang printable" enabled. As per the description; _"Change the geometry of the printed model such that minimal support is required."_

So in this case you told Cura to change the model in such a way that there is less overhang (and print the changed bits with the primary extruder)
