### ISSUE TITLE
'getSettingValue' Log Errors

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#559]
Not sure how important these are, but thought I would report it anyway:

[cura.log.txt](https://github.com/Ultimaker/Cura/files/46781/cura.log.txt)

**Comment by Ghostkeeper** [comment]
It's almost like your machine setting files are corrupt.

**Comment by nallath** [comment]
Did you manually change the definition file?

**Comment by CCS86** [comment]
I have not modified the machine configuration file, which is in the install directory.

The machine instance file in App data is pretty simple:

[general]
name = Ultimaker Original
type = ultimaker_original
version = 1

[machine_settings]
machine_extruder_drive_upgrade = True
machine_heated_bed = True

**Comment by Ghostkeeper** [comment]
Doesn't reproduce for me.

**Comment by BagelOrb** [comment]
I think you actually reopened instead of closed, because it doesn't reproduce for you.
And also this ticket is from 2015.
