### ISSUE TITLE
[4.0.0] Monitor screen becomes unresponsive after aborting print

### ISSUE THREAD

**Issue by wouteb** [Ultimaker/Cura#5592]
**Application Version**
4.0.0

**Platform**
Windows 10 Home version 1809

**Printer**
Printrbot Simple Maker's Kit (1405)

**Steps to Reproduce**
Start a print and at any point during printing hit abort.

**Actual Results**
Print aborts but the monitor screen becomes unresponsive. I can't raise the printhead to clear any issues, or even start a new print without closing Cura and restarting. I can hit print via usb and it takes me to the monitor screen again with the countdown timer showing but nothing happens.
[stderr.txt](https://github.com/Ultimaker/Cura/files/3051931/stderr.txt)

**Expected results**
I should be able to use the monitor screen to jog the printhead and then restart the print.

**Additional Information**

**Comment by nallath** [comment]
Ah, the control thread seems to have crashed. Lucky for you, it's an easy enough fix!
