### ISSUE TITLE
Cura 4.0.0 Does Not Slice Models Correctly (Cura 3.6.0 Will Slice Same Models Correctly)

### ISSUE THREAD

**Issue by drewshipley** [Ultimaker/Cura#5597]
**Application Version**
Cura 4.0.0

**Platform**
macOS 10.14.4

**Printer**
Creality Ender-5

[Ender-5 Cura Project Files.zip](https://github.com/Ultimaker/Cura/files/3054273/Ender-5.Cura.Project.Files.zip)

*I've included project files for two different sets of models from Cura 4.0.0 and from Cura 3.6.0.

**Steps to Reproduce**
1. Open either of the Cura 4.0.0 project files (Ender_5-01-Cura_400.3mf or Ender_5-02-Cura_400.3mf) 

or 

Import one pair of the STL files [STL files.zip](https://github.com/Ultimaker/Cura/files/3054297/STL.files.zip)

2. Slice models

3. Switch to Preview to see Layer View

**Actual Results**
In Cura 4.0.0 the models appear correctly in Solid View. After slicing in Layer View there are a number of issues with how the models have been sliced...

- Shells that travel between the two models
- Missing top layers on some parts of model
- No inner walls between some inner and outer shells
- Holes that do not exist in solid view are created
- Some portion of the models disappear completely leaving the remaining portion to be printed in mid-air

These issues do not exist when using Cura 3.6.0 to slice the same models on the same machine. I've included projects for both sets of models from Cura 3.6.0 (Ender_5-01-Cura_360.3mf and Ender_5-02-Cura_360.3mf).

**Expected results**
Expect that models that Cura 3.6.0 slices correctly will also slice correctly in Cura 4.0.0.

**Additional Information**
_Screen Shots of Project 1_ 
In Cura 4.0.0...
![Ender_5-01-Cura_400-SS01](https://user-images.githubusercontent.com/49399993/55725177-241b7580-59db-11e9-9de5-7e2705f879a4.png)
![Ender_5-01-Cura_400-SS02](https://user-images.githubusercontent.com/49399993/55725195-2e3d7400-59db-11e9-81e8-cd5b50b02d4d.png)

In Cura 3.6.0...
![Ender_5-01-Cura_360-SS01](https://user-images.githubusercontent.com/49399993/55725402-9d1acd00-59db-11e9-9b77-4b15cdb49ffc.png)
![Ender_5-01-Cura_360-SS02](https://user-images.githubusercontent.com/49399993/55725407-a015bd80-59db-11e9-9427-5d219662ad9b.png)

_Screen Shots of Project 2_ 
In Cura 4.0.0...
![Ender_5-02-Cura_400-SS01](https://user-images.githubusercontent.com/49399993/55725479-cdfb0200-59db-11e9-849a-7ba7dbc989e4.png)
![Ender_5-02-Cura_400-SS02](https://user-images.githubusercontent.com/49399993/55725484-cfc4c580-59db-11e9-8934-ed8137f3acdf.png)

In Cura 3.6.0...
![Ender_5-02-Cura_360-SS01](https://user-images.githubusercontent.com/49399993/55725579-000c6400-59dc-11e9-8aa4-5bf1da90cff6.png)
![Ender_5-02-Cura_360-SS02](https://user-images.githubusercontent.com/49399993/55725584-01d62780-59dc-11e9-8dd4-e62e40f8055b.png)

**Comment by nallath** [comment]
In the 4.0 project, you have spiralize outer contour enabled. You don't have this in the 3.6 project.

![Without spiralize](https://user-images.githubusercontent.com/3922611/55727003-521bac80-5a11-11e9-9e8f-68887ceb4ab8.png)
