### ISSUE TITLE
Tree support generates dots in 3.6 & 4.0

### ISSUE THREAD

**Issue by batesman1** [Ultimaker/Cura#5598]
[Model_and_project_file.zip](https://github.com/Ultimaker/Cura/files/3055621/Model_and_project_file.zip)

**Application Version**
3.6 & 4.0

**Platform**
Windows 7

**Printer**
Creality Ender2 and 3

**Steps to Reproduce**
As the issue appears to lie with this specific model, just slice this model with tree support enabled. 

**Actual Results**
Small dots appear and are printed. The number of dots goes up as the tree support branch distance is increased or decreased.

**Expected results**
I expect proper tree supports to be generated without all the extra dots

**Additional Information**
The profile used doesn't seem to make any difference as I have tried with custom profiles as well as .2 and .15 standard profiles as well. In the attached .3mf file, the tree support branch distance is set to 3 to shorten slicing time and support is being generated only off the buildplate.

**Comment by Liger0** [comment]
I noticed a very high amount of random dots using 4.0 too. I have also a doubel extrusion machine and the top and bottom layers use the second extruder (PVA), and the dots are traited like interface layers, so they use the second extruder.

**Comment by batesman1** [comment]
Another user had this issue using 3.2.1 on a separate model.

https://community.ultimaker.com/topic/27473-tree-support-dots/

**Comment by batesman1** [comment]
![Capture](https://user-images.githubusercontent.com/49410803/55757038-f6f1b600-5a20-11e9-8259-dc3188dfb960.JPG)

**Comment by rburema** [comment]
Could _maybe_ be related to an internal ticket we have, CURA-6424, _however_ the behaviour here is different. _I also notice that on layer 6, the support seems to skip a layer._ I think we'll need to investigate.

**Comment by batesman1** [comment]
So, I went back into tinkercad and adjusted the model. Specifically, I changed the radius which affects how round the corners (internal and external) are. By reducing the radius and making the object more square, it now slices correctly.
[baffle redux.zip](https://github.com/Ultimaker/Cura/files/3066762/baffle.redux.zip)
![Capture1](https://user-images.githubusercontent.com/49410803/55928456-ae83f500-5be6-11e9-8724-d4882625b803.JPG)


Project file, revised stl

**Comment by batesman1** [comment]
Different model. Same problem. The issue appears to be tied to the tree support branch distance.

![image](https://user-images.githubusercontent.com/49410803/56634166-f5360e00-662e-11e9-850d-2a076334e737.png)

Now observe the same model with only the tree support branch distance changed from 1 to 2.

![image](https://user-images.githubusercontent.com/49410803/56634215-26aed980-662f-11e9-9c4e-ff57f0888f8b.png)

and from 2 to 3

![image](https://user-images.githubusercontent.com/49410803/56634256-50680080-662f-11e9-9ec9-7710925a31eb.png)

**Comment by batesman1** [comment]
By changing the tree support branch diameter, I can make the tree supports do this, even when there is no roof to support.

![image](https://user-images.githubusercontent.com/49410803/56634659-cd47aa00-6630-11e9-8df5-0d3085dd763f.png)

**Comment by batesman1** [comment]
Here is the project file and stl
[model_ project.zip](https://github.com/Ultimaker/Cura/files/3110678/model_.project.zip)

**Comment by batesman1** [comment]
Or perhaps the issue stems from models that have rounded internal structure? This is the same model, flipped upside down.

![image](https://user-images.githubusercontent.com/49410803/56635827-f4a07600-6634-11e9-8a1f-f2b2d9af5703.png)

**Comment by Ghostkeeper** [comment]
I've seen it happen quite often with round holes. I think that for some reason it's ignoring the holes in an object when determining the area that should be supported with tree branches.

**Comment by Ghostkeeper** [comment]
This got fixed by @schneider007 through this pull request: https://github.com/Ultimaker/CuraEngine/pull/937
