### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by graphics80** [Ultimaker/Cura#561]
If I start Cura 15.06.03 on my Win7 64bit. It starts, as soon as I choose a Printer-Model (Ultimaker 2, Ultimaker 2 extended, Ultimaker 2 Go, Ultimaker Original+) it crashes. 
Ultimaker Original works.

When I choose Original at first start Up, I can add a Ultimaker 2 extended or other afterwards. But when I select then Machine > Ultimaker 2 Extended Cura crashes again...

Nothing is written in the Engine Log
## cura.log

2015-12-01 13:09:28,255 - INFO - Loaded plugin FileLogger
2015-12-01 13:09:28,374 - INFO - Loaded plugin LocalFileStorage
2015-12-01 13:09:28,379 - INFO - Loaded plugin LayerView
2015-12-01 13:09:28,388 - INFO - Loaded plugin MeshView
2015-12-01 13:09:28,395 - INFO - Loaded plugin WireframeView
2015-12-01 13:09:28,398 - INFO - Loaded plugin OBJReader
2015-12-01 13:09:28,400 - INFO - Loaded plugin STLReader
2015-12-01 13:09:28,404 - INFO - Loaded plugin STLWriter
2015-12-01 13:09:28,406 - INFO - Loaded plugin GCodeWriter
2015-12-01 13:09:28,411 - INFO - Loaded plugin CameraTool
2015-12-01 13:09:28,416 - INFO - Loaded plugin MirrorTool
2015-12-01 13:09:28,434 - INFO - Loaded plugin RotateTool
2015-12-01 13:09:28,444 - INFO - Loaded plugin ScaleTool
2015-12-01 13:09:28,452 - INFO - Loaded plugin SelectionTool
2015-12-01 13:09:28,457 - INFO - Loaded plugin TranslateTool
2015-12-01 13:09:28,466 - INFO - Checking for new version of cura
2015-12-01 13:09:28,466 - INFO - Loaded plugin UpdateChecker
2015-12-01 13:09:28,480 - INFO - Loaded plugin USBPrinting
2015-12-01 13:09:28,481 - INFO - Loaded plugin CuraEngineBackend
2015-12-01 13:09:29,159 - DEBUG - Loaded theme C:/Program Files (x86)/Cura_15.06.03/resources/themes/cura
2015-12-01 13:09:29,359 - INFO - Started engine process: C:\Program Files (x86)\Cura_15.06.03\CuraEngine.exe
2015-12-01 13:09:29,898 - DEBUG - Backend connected on port 49674
## dxDiag

[DxDiag.txt](https://github.com/Ultimaker/Cura/files/48485/DxDiag.txt)
## Report.wer

Version=1
EventType=APPCRASH
EventTime=130934442240492920
ReportType=2
Consent=1
UploadTime=130934442241082920
ReportIdentifier=b43e1341-9821-11e5-bee1-54197e20b41d
IntegratorReportIdentifier=b43e1340-9821-11e5-bee1-54197e20b41d
WOW64=1
Response.BucketId=63994886
Response.BucketTable=25
Response.Str=http:////oca.microsoft.com//resredir.aspx?SID=1&iBucketTable=1&iBucket=107438177286&BucketHash=0fafb01e9a2967bae4728258eb66304d
Sig[0].Name=Anwendungsname
Sig[0].Value=Cura.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=0.0.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=536d0024
Sig[3].Name=Fehlermodulname
Sig[3].Value=atioglxx.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=6.14.10.11568
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=4f752055
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=006faa28
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=2055
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=0a9e
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=0a9e372d3b4ad19135b953a78882e789
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=0a9e
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=0a9e372d3b4ad19135b953a78882e789
UI[2]=C:\Program Files (x86)\Cura_15.06.03\Cura.exe
UI[3]=Cura.exe funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=C:\Program Files (x86)\Cura_15.06.03\Cura.exe
LoadedModule[1]=C:\windows\SysWOW64\ntdll.dll
LoadedModule[2]=C:\windows\syswow64\kernel32.dll
LoadedModule[3]=C:\windows\syswow64\KERNELBASE.dll
LoadedModule[4]=C:\windows\syswow64\USER32.dll
LoadedModule[5]=C:\windows\syswow64\GDI32.dll
LoadedModule[6]=C:\windows\syswow64\LPK.dll
LoadedModule[7]=C:\windows\syswow64\USP10.dll
LoadedModule[8]=C:\windows\syswow64\msvcrt.dll
LoadedModule[9]=C:\windows\syswow64\ADVAPI32.dll
LoadedModule[10]=C:\windows\SysWOW64\sechost.dll
LoadedModule[11]=C:\windows\syswow64\RPCRT4.dll
LoadedModule[12]=C:\windows\syswow64\SspiCli.dll
LoadedModule[13]=C:\windows\syswow64\CRYPTBASE.dll
LoadedModule[14]=C:\windows\syswow64\SHELL32.dll
LoadedModule[15]=C:\windows\syswow64\SHLWAPI.dll
LoadedModule[16]=C:\windows\system32\MSVCR100.dll
LoadedModule[17]=C:\windows\system32\IMM32.DLL
LoadedModule[18]=C:\windows\syswow64\MSCTF.dll
LoadedModule[19]=C:\Program Files (x86)\Cura_15.06.03\python34.dll
LoadedModule[20]=C:\windows\system32\CRYPTSP.dll
LoadedModule[21]=C:\windows\system32\rsaenh.dll
LoadedModule[22]=C:\Program Files (x86)\Cura_15.06.03_ctypes.pyd
LoadedModule[23]=C:\windows\syswow64\ole32.dll
LoadedModule[24]=C:\windows\syswow64\OLEAUT32.dll
LoadedModule[25]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtCore.pyd
LoadedModule[26]=C:\Program Files (x86)\Cura_15.06.03\Qt5Core.dll
LoadedModule[27]=C:\windows\syswow64\WS2_32.dll
LoadedModule[28]=C:\windows\syswow64\NSI.dll
LoadedModule[29]=C:\windows\system32\MPR.dll
LoadedModule[30]=C:\Program Files (x86)\Cura_15.06.03\icuin53.dll
LoadedModule[31]=C:\Program Files (x86)\Cura_15.06.03\icuuc53.dll
LoadedModule[32]=C:\Program Files (x86)\Cura_15.06.03\icudt53.dll
LoadedModule[33]=C:\windows\system32\MSVCP100.dll
LoadedModule[34]=C:\Program Files (x86)\Cura_15.06.03\sip.pyd
LoadedModule[35]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtQml.pyd
LoadedModule[36]=C:\Program Files (x86)\Cura_15.06.03\Qt5Qml.dll
LoadedModule[37]=C:\Program Files (x86)\Cura_15.06.03\Qt5Network.dll
LoadedModule[38]=C:\windows\system32\DNSAPI.dll
LoadedModule[39]=C:\Program Files (x86)\Cura_15.06.03\SSLEAY32.dll
LoadedModule[40]=C:\Program Files (x86)\Cura_15.06.03\LIBEAY32.dll
LoadedModule[41]=C:\windows\syswow64\CRYPT32.dll
LoadedModule[42]=C:\windows\syswow64\MSASN1.dll
LoadedModule[43]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtNetwork.pyd
LoadedModule[44]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtWidgets.pyd
LoadedModule[45]=C:\Program Files (x86)\Cura_15.06.03\Qt5Widgets.dll
LoadedModule[46]=C:\Program Files (x86)\Cura_15.06.03\Qt5Gui.dll
LoadedModule[47]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtGui.pyd
LoadedModule[48]=C:\Program Files (x86)\Cura_15.06.03\numpy.core.multiarray.pyd
LoadedModule[49]=C:\Program Files (x86)\Cura_15.06.03\numpy.core.umath.pyd
LoadedModule[50]=C:\Program Files (x86)\Cura_15.06.03\numpy.core._dotblas.pyd
LoadedModule[51]=C:\Program Files (x86)\Cura_15.06.03\numpy.core.scalarmath.pyd
LoadedModule[52]=C:\Program Files (x86)\Cura_15.06.03_bz2.pyd
LoadedModule[53]=C:\Program Files (x86)\Cura_15.06.03_hashlib.pyd
LoadedModule[54]=C:\Program Files (x86)\Cura_15.06.03\numpy.lib._compiled_base.pyd
LoadedModule[55]=C:\Program Files (x86)\Cura_15.06.03\numpy.linalg.lapack_lite.pyd
LoadedModule[56]=C:\Program Files (x86)\Cura_15.06.03\numpy.linalg._umath_linalg.pyd
LoadedModule[57]=C:\Program Files (x86)\Cura_15.06.03\numpy.fft.fftpack_lite.pyd
LoadedModule[58]=C:\Program Files (x86)\Cura_15.06.03\numpy.random.mtrand.pyd
LoadedModule[59]=C:\Program Files (x86)\Cura_15.06.03\PyQt5.QtQuick.pyd
LoadedModule[60]=C:\Program Files (x86)\Cura_15.06.03\Qt5Quick.dll
LoadedModule[61]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\platforms\qwindows.dll
LoadedModule[62]=C:\windows\system32\WINMM.dll
LoadedModule[63]=C:\windows\system32\uxtheme.dll
LoadedModule[64]=C:\Program Files (x86)\Hewlett-Packard\HP ProtectTools Security Manager\Bin\DpoFeedb.dll
LoadedModule[65]=C:\windows\system32\VERSION.dll
LoadedModule[66]=C:\windows\syswow64\USERENV.dll
LoadedModule[67]=C:\windows\syswow64\profapi.dll
LoadedModule[68]=C:\windows\system32\dwmapi.dll
LoadedModule[69]=C:\Program Files (x86)\Cura_15.06.03_socket.pyd
LoadedModule[70]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qdds.dll
LoadedModule[71]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qgif.dll
LoadedModule[72]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qicns.dll
LoadedModule[73]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qico.dll
LoadedModule[74]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qjp2.dll
LoadedModule[75]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qjpeg.dll
LoadedModule[76]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qmng.dll
LoadedModule[77]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qsvg.dll
LoadedModule[78]=C:\Program Files (x86)\Cura_15.06.03\Qt5Svg.dll
LoadedModule[79]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qtga.dll
LoadedModule[80]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qtiff.dll
LoadedModule[81]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\imageformats\qwebp.dll
LoadedModule[82]=C:\windows\syswow64\CLBCatQ.DLL
LoadedModule[83]=C:\Program Files (x86)\Hewlett-Packard\HP ProtectTools Security Manager\Bin\DpoSet.dll
LoadedModule[84]=C:\Program Files (x86)\Cura_15.06.03_lzma.pyd
LoadedModule[85]=C:\Program Files (x86)\Cura_15.06.03_ssl.pyd
LoadedModule[86]=C:\Program Files (x86)\Cura_15.06.03\unicodedata.pyd
LoadedModule[87]=C:\windows\system32\mswsock.dll
LoadedModule[88]=C:\windows\System32\wshtcpip.dll
LoadedModule[89]=C:\windows\System32\wship6.dll
LoadedModule[90]=C:\windows\system32\IPHLPAPI.DLL
LoadedModule[91]=C:\windows\system32\WINNSI.DLL
LoadedModule[92]=C:\windows\system32\rasadhlp.dll
LoadedModule[93]=C:\windows\System32\fwpuclnt.dll
LoadedModule[94]=C:\windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\comctl32.dll
LoadedModule[95]=C:\windows\syswow64\SETUPAPI.dll
LoadedModule[96]=C:\windows\syswow64\CFGMGR32.dll
LoadedModule[97]=C:\windows\syswow64\DEVOBJ.dll
LoadedModule[98]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick.2\qtquick2plugin.dll
LoadedModule[99]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick\Controls\qtquickcontrolsplugin.dll
LoadedModule[100]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick\Layouts\qquicklayoutsplugin.dll
LoadedModule[101]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick\Dialogs\dialogplugin.dll
LoadedModule[102]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick\Window.2\windowplugin.dll
LoadedModule[103]=C:\windows\system32\apphelp.dll
LoadedModule[104]=C:\windows\system32\opengl32.dll
LoadedModule[105]=C:\windows\system32\GLU32.dll
LoadedModule[106]=C:\windows\system32\DDRAW.dll
LoadedModule[107]=C:\windows\system32\DCIMAN32.dll
LoadedModule[108]=C:\windows\system32\atiglpxx.dll
LoadedModule[109]=C:\windows\system32\atioglxx.dll
LoadedModule[110]=C:\windows\system32\aticfx32.dll
LoadedModule[111]=C:\windows\system32\atiadlxy.dll
LoadedModule[112]=C:\windows\system32\WTSAPI32.dll
LoadedModule[113]=C:\windows\syswow64\PSAPI.DLL
LoadedModule[114]=C:\windows\syswow64\WINTRUST.dll
LoadedModule[115]=C:\windows\system32\atigktxx.dll
LoadedModule[116]=C:\windows\system32\RpcRtRemote.dll
LoadedModule[117]=C:\Program Files (x86)\Cura_15.06.03\PyQt5\plugins\iconengines\qsvgicon.dll
LoadedModule[118]=C:\Program Files (x86)\Cura_15.06.03\PyQt5._QOpenGLFunctions_2_0.pyd
LoadedModule[119]=C:\Program Files (x86)\Cura_15.06.03\qml\QtQuick\PrivateWidgets\widgetsplugin.dll
LoadedModule[120]=C:\windows\System32\comdlg32.dll
LoadedModule[121]=C:\windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.7601.18201_none_ec80f00e8593ece5\COMCTL32.dll
LoadedModule[122]=C:\windows\system32\DUser.dll
LoadedModule[123]=C:\windows\system32\DUI70.dll
LoadedModule[124]=C:\windows\system32\WindowsCodecs.dll
LoadedModule[125]=C:\windows\system32\EhStorShell.dll
LoadedModule[126]=C:\windows\system32\PROPSYS.dll
LoadedModule[127]=C:\PROGRA~2\MICROS~3\Office14\GROOVEEX.DLL
LoadedModule[128]=C:\windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\MSVCR90.dll
LoadedModule[129]=C:\windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57\MSVCP90.dll
LoadedModule[130]=C:\windows\WinSxS\x86_microsoft.vc90.atl_1fc8b3b9a1e18e3b_9.0.30729.6161_none_51cd0a7abbe4e19b\ATL90.DLL
LoadedModule[131]=C:\PROGRA~2\COMMON~1\MICROS~1\OFFICE14\Cultures\office.odf
LoadedModule[132]=C:\PROGRA~2\MICROS~3\Office14\1031\GrooveIntlResource.dll
LoadedModule[133]=C:\windows\system32\ntshrui.dll
LoadedModule[134]=C:\windows\system32\srvcli.dll
LoadedModule[135]=C:\windows\system32\cscapi.dll
LoadedModule[136]=C:\windows\system32\slc.dll
LoadedModule[137]=C:\windows\system32\msls31.dll
LoadedModule[138]=C:\windows\system32\XmlLite.dll
LoadedModule[139]=C:\windows\system32\LINKINFO.dll
LoadedModule[140]=C:\windows\system32\NetworkExplorer.dll
LoadedModule[141]=C:\windows\System32\drprov.dll
LoadedModule[142]=C:\windows\System32\WINSTA.dll
LoadedModule[143]=C:\windows\System32\ntlanman.dll
LoadedModule[144]=C:\windows\System32\davclnt.dll
LoadedModule[145]=C:\windows\System32\DAVHLPR.dll
LoadedModule[146]=C:\windows\system32\netutils.dll
LoadedModule[147]=C:\windows\system32\WINHTTP.dll
LoadedModule[148]=C:\windows\system32\webio.dll
LoadedModule[149]=C:\windows\system32\credssp.dll
LoadedModule[150]=C:\windows\syswow64\urlmon.dll
LoadedModule[151]=C:\windows\syswow64\api-ms-win-downlevel-ole32-l1-1-0.dll
LoadedModule[152]=C:\windows\syswow64\api-ms-win-downlevel-shlwapi-l1-1-0.dll
LoadedModule[153]=C:\windows\syswow64\api-ms-win-downlevel-advapi32-l1-1-0.dll
LoadedModule[154]=C:\windows\syswow64\api-ms-win-downlevel-user32-l1-1-0.dll
LoadedModule[155]=C:\windows\syswow64\api-ms-win-downlevel-version-l1-1-0.dll
LoadedModule[156]=C:\windows\syswow64\api-ms-win-downlevel-normaliz-l1-1-0.dll
LoadedModule[157]=C:\windows\syswow64\normaliz.DLL
LoadedModule[158]=C:\windows\syswow64\iertutil.dll
LoadedModule[159]=C:\windows\syswow64\WININET.dll
LoadedModule[160]=C:\windows\system32\dhcpcsvc.DLL
LoadedModule[161]=C:\windows\system32\dhcpcsvc6.DLL
LoadedModule[162]=C:\windows\system32\wkscli.dll
LoadedModule[163]=C:\windows\System32\StructuredQuery.dll
LoadedModule[164]=C:\windows\System32\Secur32.dll
LoadedModule[165]=C:\windows\system32\mssprxy.dll
LoadedModule[166]=C:\windows\system32\SHDOCVW.dll
LoadedModule[167]=C:\windows\system32\ieframe.DLL
LoadedModule[168]=C:\windows\system32\api-ms-win-downlevel-shell32-l1-1-0.dll
LoadedModule[169]=C:\windows\system32\api-ms-win-downlevel-shlwapi-l2-1-0.dll
LoadedModule[170]=C:\windows\system32\ntmarta.dll
LoadedModule[171]=C:\windows\syswow64\WLDAP32.dll
LoadedModule[172]=C:\windows\system32\PortableDeviceApi.dll
LoadedModule[173]=C:\Windows\SysWOW64\actxprxy.dll
LoadedModule[174]=C:\windows\system32\EhStorAPI.dll
LoadedModule[175]=C:\Program Files (x86)\Internet Explorer\ieproxy.dll
LoadedModule[176]=C:\windows\system32\IconCodecService.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
State[1].Key=DataRequest
State[1].Value=Bucket=63994886/nBucketTable=25/nResponse=http:////oca.microsoft.com//resredir.aspx?SID=1&iBucketTable=1&iBucket=107438177286&BucketHash=0fafb01e9a2967bae4728258eb66304d/n
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=Cura.exe
AppPath=C:\Program Files (x86)\Cura_15.06.03\Cura.exe

**Comment by fieldOfView** [comment]
Please try one of the more recent builds of the open beta instead of 15.06.03:
https://ultimaker.com/en/community/17296-cura-1510-open-beta
A lot has happened since 15.06.03

**Comment by graphics80** [comment]
Just tried with dev20151117, same Issue...

**Comment by ripper121** [comment]
I had also Startup Problem but with config file.


Version: 15.06.03
Platform: Windows-7-6.1.7601-SP1
Qt: 5.4.1
PyQt: 5.4.1

Exception:
Traceback (most recent call last):
  File "cura_app.py", line 9, in <module>
  File "c:\dev\uranium\UM\Application.py", line 329, in getInstance
  File "c:\dev\cura\cura\CuraApplication.py", line 56, in __init__
  File "c:\dev\uranium\UM\Qt\QtApplication.py", line 48, in __init__
  File "c:\dev\uranium\UM\Application.py", line 67, in __init__
  File "c:\dev\uranium\UM\Preferences.py", line 56, in readFromFile
  File "c:\dev\uranium\UM\Preferences.py", line 122, in _loadFile
  File "c:\dev\python34\lib\configparser.py", line 672, in read
  File "c:\dev\python34\lib\configparser.py", line 1088, in _read
configparser.ParsingError: Source contains parsing errors: 'C:\\Users\\sts/AppData/Local/cura\\cura.cfg'
	[line 17]: 'end]\n'
	[line 19]: ' 2\n'

**Comment by nallath** [comment]
@ripper121; This is an issue with 15.06 specifically. Upgrading should resolve it.

**Comment by BagelOrb** [comment]
outdated
