### ISSUE TITLE
[4.0.0] Selection of second Extruder for skirt causes incorrect extruder selection in layer 1  for dual color models

### ISSUE THREAD

**Issue by lterrill** [Ultimaker/Cura#5615]
**Application Version**
Cura 4.0.0

**Platform**
Mac OS 10.14.4

**Printer**
Any dual extruder printer, I used Ultimaker Original Dual Extrusion. Select two different colors of material for extruder 1 and extruder 2 to better illustrate this issue, Ultimaker Red for extruder 1, Ultimaker Yellow for extruder 2.

**Steps to Reproduce**
- Drop two models on the build plate. I used a single 20mm calibration cube and performed a 'multiple\y selected model' resulting in two models. 
- Assign extruder 1 to first model, extruder 2 to the second model.
- Select Skirt for Build Plate Adhesion, select extruder 2  as the Build Plate Adhesion Extruder. 
Note that the unexpected behavior appears unaffected by Prime tower setting

**Actual Results**
The first extruder is used to build the skirt, then the first layer of both models. The second extruder is never used on the first layer. Subsequent layers are built as expected (each extruder is used on the correct model). 
![Results extruder 2 skirt layer 1](https://user-images.githubusercontent.com/535763/56031376-ebceac80-5ce4-11e9-82e7-f0ed207b9ba5.png)
![Results extruder 2 skirt layer 2](https://user-images.githubusercontent.com/535763/56031386-f5581480-5ce4-11e9-9dd7-402587b32619.png)

**Expected results**
Expected the model assigned to extruder 2 to have a first layer built with extruder 2. Note that I did receive the expected results when Extruder 1 is selected as the Build Adhesion Extruder and this is my current work-around. This error only occurs when Extruder 2 is selected as the Build Adhesion Extruder.
![Results extruder 1 skirt layer 1](https://user-images.githubusercontent.com/535763/56031410-0a34a800-5ce5-11e9-89f7-c21c1627db0f.png)

This bug appears to have been introduced in Cura version 4.

**Comment by Ghostkeeper** [comment]
Not able to reproduce this. Maybe you have a project file for us?

![Screenshot from 2019-04-12 17-13-18](https://user-images.githubusercontent.com/2448634/56047716-56640480-5d46-11e9-98e6-0b6c010738fa.png)

**Comment by lterrill** [comment]
Including requested project file
[Two cubes, bad first layer.3mf.zip](https://github.com/Ultimaker/Cura/files/3074055/Two.cubes.bad.first.layer.3mf.zip)

**Comment by Block137** [comment]
#5550 
#5580 
Only occur when "Build plate adhesion extruder" is not extruder1
The generated G-code does use correct extruder BUT wont set temperature for it, there will be duplicate M104 T0, printer will cold extrude the skirt.

**Comment by Ghostkeeper** [comment]
That project file produces a different result for me using current master.

![Screenshot from 2019-04-15 09-24-45](https://user-images.githubusercontent.com/2448634/56114198-7242f280-5f60-11e9-9ec6-199084365d26.png)

However your bug does reproduce if I load it in 4.0. So I think that the current master introduced a new bug that caused it to not load the correct extruder from the project file, which is just hiding the bug...

It also doesn't help that due to #5550 the actual extruder that is being used is (sometimes?) hidden...

**Comment by lterrill** [comment]
This issue appears to be completely resolved in Cura 4.1

**Comment by Ghostkeeper** [comment]
Thanks for re-testing!
