### ISSUE TITLE
[4.0.0] Dock / Expand Settings Pane

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#5624]
Maybe I am just missing it, but how can the full height settings pane be restored?

I am really not a fan of moving the settings pane off the right side of the screen, and isolating the layers slider in a corridor of wasted space.

**Comment by fieldOfView** [comment]
There’s a plugin for that: Sidebar GUI, available in the Marketplace.

**Comment by CCS86** [comment]
Thank you, much better!

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5097
