### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Renha** [Ultimaker/Cura#563]
installed cura-git package at Arch, which i believe installs master branch, and that's what i have: 
http://pastebin.com/UNHHgzEt

**Comment by ad1217** [comment]
I maintain the cura-git package in the AUR, and it still seems to work for me. Do you also have the latest versions of uranium-git, libarcus-git, and curaengine-git?

**Comment by Renha** [comment]
Wow, thank you, i thought i had last versions, but after reinstalling all of them issue has been resolved.
