### ISSUE TITLE
[4.0] Ultimaker Cloud can't find printers added with IP address

### ISSUE THREAD

**Issue by zouden** [Ultimaker/Cura#5633]
**Application Version**

Cura 4.0, UM firmware 5.2

**Platform**

Windows 10
**Printer**

Ultimaker S5
**Steps to Reproduce**

Connect to network with VPN. Add Ultimaker (IP needs to be added manually when I use the VPN). Cloud feature asks if I want to connect the printer. Say yes, enter the code from the UMS5 display. Cloud connected! Now disconnect from VPN.
**Actual Results**

Printer connection is lost when VPN disconnected. Printer icon does not change to a cloud.
**Expected results**

Printer should be available through the cloud.

**Additional Information**

I'm unable to test if the Cloud feature works when the printer is automatically detected (instead of manual IP), because the detection doesn't work. Presumably to do with the VPN.

**Comment by ChrisTerBeke** [comment]
This is a known issue and will be fixed in the next release.
