### ISSUE TITLE
support eraser, per object setting tool has problems

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#5639]
**Application Version**

master version

**Platform**

windows 10 64bit

**Printer**

any printer

**Steps to Reproduce**

1. support eraser tool
    - open any model
    - select support eraser tool
    - change size or position eraser mesh
    - cura master version crash
2. per object setting tool
    - open any model for printing mesh
    - open any model for per object setting test
    - select per object setting tool to test mesh
    - select setting option
    - slice
    - change setting option of per object setting tool
    - don't change slice button status to slice ready

**Actual Results**

1. support eraser tool
    - cura master version is crashed
2. per object setting tool
    - slice button status is not changed

**Expected results**

1. support eraser tool
    - when change size, position of eraser mesh, cura is OK
2. per object setting tool
    - when change setting option of per object mesh, slice button is changed

**Additional Information**

If I revert def _onSettingChanged() in SettingOverrideDecorator.py, 1, 2 issues is cleared.
1. support eraser tool - if setCalculateBoundingBox is deleted
2. per object setting tool - if new*, changed variables is deleted

**Comment by Ghostkeeper** [comment]
1. Reproduces here too. Pretty serious!
2. Indeed it should already start reslicing at the 4th step (if anything was sliced).

**Comment by nallath** [comment]
Both of them are fixed for 4.1

**Comment by myloverby** [comment]
It says this is Solved? With Cura 4.1.. but I have 

--Cura 4.6 and the "eraser Tool" still Doesn't Work!--

I need to use it as a support blocker, tried every setting on the left, tried setting to "0 infill on the left menu" but it blocks nothing!!!

**Comment by myloverby** [comment]
![20200815_162153](https://user-images.githubusercontent.com/69734839/90321935-ea824500-df13-11ea-876e-1099a3105cd1.jpg)
![20200815_162450](https://user-images.githubusercontent.com/69734839/90321939-ee15cc00-df13-11ea-9db5-060268d07db7.jpg)
![Uploading 20200815_162105.jpg…]()

**Comment by Ghostkeeper** [comment]
I think your confusion is that you expect the support "eraser" to actually erase support if you place it somewhere down lower in the support structure. While the support blocker tool actually only prevents support from being generated at all. It needs to intersect with the red parts of your model. If you place it down somewhere lower it won't prevent any support from being generated.

**Comment by myloverby** [comment]
I figured it out, I just needed to set it to "normal mode" and set the
walls/infill all to zero on the support.
