### ISSUE TITLE
CURA + UV LCD (Inkspire)

### ISSUE THREAD

**Issue by cederom** [Ultimaker/Cura#5643]
Hello, what are the changes to adapt CURA for UV LCD printers like Zortrax Inkspire? Maybe Ultimaker is working on printer like this? :-)

**Comment by nallath** [comment]
Currently, Cura is optimized for FDM printing (So toolpath based 3D printing). It is possible to change the workflow in such a way that this is possible, but that is going to take quite a significant bit of effort. 

Whether or not we are working on any such printer is obviously not something I can say anything about.
