### ISSUE TITLE
Slicing Fails on many of my Models

### ISSUE THREAD

**Issue by bryancostanich** [Ultimaker/Cura#5644]
Hi folks! 

I'm having some real troubles with the slicer in cura. Slicing doesn't complete on a lot of my .stl models I've created in AutoCad. It seems to finish, it says it's finished in cura; but when I go to print, the print just stops. I got in touch with LulzBot and they said it was due to .stl errors, and so I started to dig into it, and I no longer believe that's the case. It seems like it's a problem in the slicer. The .STL files open in and view just fine in a number of applications, including xcode, github's stl viewer, and some 3D apps I've tried. I've even tried to open the STLs up and "fix" them in sketchup, but often times the 3D fix plugins say there's nothing wrong.

So I think there's two issues here:

 1. Cura doesn't notify you if the slicer fails.
 2. The slicer is failing on these STLs

I've attached a problematic STL model, the printer config, and the project file.

**Application Version**
v3.2.32

**Platform**
macOS v10.14.4

**Printer**
LulzBot Taz 5

[LulzBot+TAZ+5+DualExtruder+v3.global.cfg.zip](https://github.com/Ultimaker/Cura/files/3100424/LulzBot%2BTAZ%2B5%2BDualExtruder%2Bv3.global.cfg.zip)
[Pogo_Mount_Bottom_PLA_Detail.3mf.zip](https://github.com/Ultimaker/Cura/files/3100425/Pogo_Mount_Bottom_PLA_Detail.3mf.zip)

[Meadow_F7_Micro_Pogo_Mount_Bottom.stl.zip](https://github.com/Ultimaker/Cura/files/3100429/Meadow_F7_Micro_Pogo_Mount_Bottom.stl.zip)

**Steps to Reproduce**
Try to slice the attached .stl. 

**Actual Results**
Slicing doesn't complete. If you try to print it will abruptly stop

**Expected results**
Slicing should finish, and if it doesn't finish, it should notify.

**Additional Information**

<img width="1149" alt="Screen Shot 2019-04-20 at 10 28 56 AM" src="https://user-images.githubusercontent.com/947633/56460467-10b3c700-6358-11e9-975b-48e249f5c8e1.png">

**Comment by bryancostanich** [comment]
Also, FWIW, it looks fine in x-ray and layer view (no red):

<img width="1022" alt="Screen Shot 2019-04-20 at 10 41 41 AM" src="https://user-images.githubusercontent.com/947633/56460523-f5958700-6358-11e9-9ca0-d5487faed6b3.png">

<img width="1039" alt="Screen Shot 2019-04-20 at 10 41 47 AM" src="https://user-images.githubusercontent.com/947633/56460526-f8907780-6358-11e9-90f8-e8daa8df139d.png">

**Comment by smartavionics** [comment]
Hello @bryancostanich , I tried to open your project file in my Cura which is based on Ultimaker's source + my own tweaks and additions and it bombed so I can't test your profile but it slices your model just fine. I am not going to bother to print it as I know it will be OK.
Here's the layer view..

![Screenshot_2019-04-20_19-28-48](https://user-images.githubusercontent.com/585618/56460941-9c524580-63a2-11e9-9b59-1a9f7ba57bbd.png)

BTW, the stl file does have some problems as identified by FreeCAD...

![Screenshot_2019-04-20_19-28-31](https://user-images.githubusercontent.com/585618/56460947-af651580-63a2-11e9-92dc-b99cfb81d415.png)

Hope this helps.

**Comment by bryancostanich** [comment]
Why do you suppose my print always stops then? I contacted LulzBot and they told me it's because the slicer has failed.

**Comment by smartavionics** [comment]
I also checked the model with Cura's own tools and it reports...

![Screenshot_2019-04-20_20-04-16](https://user-images.githubusercontent.com/585618/56461266-927f1100-63a7-11e9-8802-f40e5c223107.png)

> Why do you suppose my print always stops then? I contacted LulzBot and they told me it's because the slicer has failed.

Well, perhaps your Cura (which is derived from Ultimaker Cura but, in reality, is a completely different application) generates bad gcode when given a broken model. Basically, if the model is bad, all bets are off.

**Comment by bryancostanich** [comment]
I can't seem to use Mesh tools with the Cura Lulzbot edition.  

In any case, I looked at the GCODE (attached), and it's complete through to the end. 

[Pogo_Mount_Bottom_PLA_Detail.gcode.zip](https://github.com/Ultimaker/Cura/files/3100516/Pogo_Mount_Bottom_PLA_Detail.gcode.zip)

**Comment by fieldOfView** [comment]
MeshTools requires Cura 3.5 or newer.

The fact that an STL can be loaded and displayed does not mean that its geometry is suitable for 3d printing. Sketchup is not a tool that is suitable to repair a model for 3d printing.

**Comment by bryancostanich** [comment]
> MeshTools requires Cura 3.5 or newer.

I upgraded to 3.6.2, and still don't see them. Maybe because it's the "Lulzbot" edition or whatever. 

> The fact that an STL can be loaded and displayed does not mean that its geometry is suitable for 3d printing. 

Sure, but if it's actually slicing, it should print using those gcode instructions, no? I viewed it in slice mode, and it's all there.

I looked at the GCODE output and it finishes, I see the end GCODE. But something in there is causing Marlin (the firmware) to actually reboot. :) What could cause that? I just took a glance through the GCODE and it looked normal, but I could have missed it. 

> Sketchup is not a tool that is suitable to repair a model for 3d printing.

There are a number of mesh repair plugins for Sketchup.

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this issue. When slicing the 3MF file I do get these errors: 
```
2019-04-24 09:55:20,768 - DEBUG - [Thread-50] UM.Backend.Backend._backendLog [101]: [Backend] [ERROR] Clipper::offset failed. See generated debug.html!
```
That could indicate something wrong in the mesh, such as not being watertight, or being self-intersecting. I'm also not able to load your profiles though as the zip file seems to be corrupt.

Unless you're finding the M999 command (which is not generated by Cura by default), your printer should not restart. If your printer is restarting, that would be a firmware bug. The g-code generated on this side looks fine. You say that the g-code looks fine as well. The g-code is the only thing that is communicated between Cura and the printer, and the printer is doing something wrong as a result.

**Comment by GregValiant** [comment]
Can we close this?

**Comment by bryancostanich** [comment]
Sure.
