### ISSUE TITLE
[3.3.1] Missing most text after upgrade to Ubuntu 19.04

### ISSUE THREAD

**Issue by mtib** [Ultimaker/Cura#5645]
**Application Version** 3.3.1

**Platform** Ubuntu 19.04

**Steps to Reproduce**
- Updated from Ubuntu 18.10 to 19.04
- Started cura

**Actual Results**
- Most text is missing
- Unusable

**Expected results**
- Text to show up

**Additional Information**
![image](https://user-images.githubusercontent.com/3661529/56470589-4932ce00-6448-11e9-8cd7-379a6c7ce681.png)
![Screenshot from 2019-04-21 15-16-55](https://user-images.githubusercontent.com/3661529/56470619-b47ca000-6448-11e9-9fef-25c25d4f55ef.png)
![Screenshot from 2019-04-21 15-17-14](https://user-images.githubusercontent.com/3661529/56470620-b47ca000-6448-11e9-9444-d8dd06dbc626.png)

Some text as well as all keyboard shortcuts show up, but most UI text doesn't. Everything was fine before the upgrade to Ubuntu 19.04 and I haven't had this problem with any other application.

Startup log: [cura.log](https://github.com/Ultimaker/Cura/files/3101219/cura.log)

**Comment by mtib** [comment]
Deleting the files in `.config/cura/3.3` leaves me with this on startup: 
![image](https://user-images.githubusercontent.com/3661529/56470682-5c926900-6449-11e9-9054-0193973ad10a.png)

**Comment by mtib** [comment]
Couldn't fix that, but running the AppImage of 4.0 from the website works. So...

**Comment by nallath** [comment]
The 3.3.1 version is probably from the PPA, which is not supported by us. Since the 4.0 app image is working, this issue will be closed.

**Comment by Ghostkeeper** [comment]
Works for me both from source and via the AppImage in 19.04.

**Comment by mtib** [comment]
Then something must have gone wrong when upgrading from 18.10 to 19.04. Then again, I found a fix.
