### ISSUE TITLE
[4.0.0] show toolhead movement in preview mode

### ISSUE THREAD

**Issue by moham96** [Ultimaker/Cura#5648]
**Application Version**
4.0.0

**Platform**
Gnu/Linux

**Printer**
not important

**Steps to Reproduce**
slice any model and go to preview mode, you can see individual layers added on top of each other using the slider on the right, but you can't see how the layer is being deposited.

**Actual Results**
You can see individual layers added on top of each other using the slider on the right, but you can't see how the layer is being deposited.

**Expected results**
It would be useful to see the tool head as it moves to form a layer, this is helpful for example to know where exactly a layer begins to form and ends.

**Comment by guestisp** [comment]
Just move the single layer slider (on the bottom side of the screen) to see the toolhead moving around

**Comment by guestisp** [comment]
Or hit "play" in the same place

**Comment by moham96** [comment]
@guestisp  maybe I'm missing something, I don't see any slide on the bottom or a "play" button !!
![pic-full-190423-1914-55](https://user-images.githubusercontent.com/10559702/56598251-d9b20f80-65fc-11e9-8300-493fec43cfc7.png)

**Comment by fieldOfView** [comment]
Your layer view is in "compatibility mode", probably because your GPU does not support the advanced OpenGL 4.1 functionality that the normal layer view uses. Compatibility mode does not have the horizontal slider to "play" the layers.

**Comment by Ghostkeeper** [comment]
We don't intend to backport this feature to compatibility mode. While possible, the compatibility mode is currently just showing a bunch of polygons which is kind of easy.
OpenGL 4.0 got released in 2010. You'd expect most devices to be up to date by now...
