### ISSUE TITLE
Cant place duplicated object

### ISSUE THREAD

**Issue by EugeneSkrebnev** [Ultimaker/Cura#566]
If there is no space after duplicating object. cura cant select place for it.
see gif file below:
https://gyazo.com/3ea39b5a1234f62863d3fcaf2e4773a0

**Comment by nallath** [comment]
Switch to 1.99. You can find it on http://software.ultimaker.com/Cura_closed_beta/15.10/

**Comment by EugeneSkrebnev** [comment]
Cura-1.99.0-dev.20151117-Darwin.dmg	17-Nov-2015 14:14	54M	 
it was this version. i already use Cura_closed_beta builds

as i can see its the latest one

**Comment by nallath** [comment]
Odd, this should have been fixed in that version.

**Comment by EugeneSkrebnev** [comment]
it was easy to reproduce. just add alot of small objects about 1 by 1 sm in (xy) and after that start duplicating them using right click - duplicate. at first them start jumping as in checkers game,
and after few iterations it fails with infinity loop.

**Comment by Ghostkeeper** [comment]
Checkers is a very good way to describe it :stuck_out_tongue:

**Comment by BagelOrb** [comment]
outdated

**Comment by Ghostkeeper** [comment]
Fixed in the meanwhile.
