### ISSUE TITLE
[4.0.0] Layer path is not smooth

### ISSUE THREAD

**Issue by kolczynsky** [Ultimaker/Cura#5669]
**Application Version**
4.0.0

**Platform**
Windows 10

**Printer**
Creality Ender 3

**Steps to Reproduce**
Nozzle: 0.4 mm
Layer height: 0.12 mm
Wall thickness: 1.2 mm

**Actual Results**
After slicing, outer wall is not smooth everywhere as it should be. At lower layers it looks like this:

![err1](https://user-images.githubusercontent.com/50015237/56801288-60ddce00-681d-11e9-9646-fe719532747f.jpg)

But on upper layers it is already fine:

![err2](https://user-images.githubusercontent.com/50015237/56799728-ce87fb00-6819-11e9-85f8-20f9de64aac0.jpg)

Below is the sliced model. As you can see, the issued part is simple cilindrical shape, so layers should look the same on whole item.

![err4](https://user-images.githubusercontent.com/50015237/56799994-54a44180-681a-11e9-83d3-624c2d2941fb.jpg)

**Expected results**
Here is how it is properly sliced in third-party slicer:

![err3](https://user-images.githubusercontent.com/50015237/56800036-6ab20200-681a-11e9-8671-816a669a7095.jpg)

**Additional Information**
This glitch is not caused by seam, because I moved the seam to some other point. I've tried to resolve the problem by playing with "Outer Wall Inset" option, but it does not help.

At the end you can compare the print results. Cura's one is on top. Red arrows mark the glitches. At the bottom is a print prepared in other slicer. Print settings (material, temperature, layer height, nozzle diameter etc.) were the same in both cases.

![err5](https://user-images.githubusercontent.com/50015237/56800827-3e978080-681c-11e9-88b0-3adfb9aa6bf9.jpg)

If you find .3mf file is useful, here it is:

[.curaproject.zip](https://github.com/Ultimaker/Cura/files/3120812/default.curaproject.zip)

**Comment by smartavionics** [comment]
Hello @kolczynsky. Unfortunately, your .3mf file only contains the model and not the settings. So please do a File -> Save (not export) and the resulting .3mf will contain both the model and the settings. Thanks.

**Comment by kolczynsky** [comment]
My mistake :) As requested:

[.curaproject.zip](https://github.com/Ultimaker/Cura/files/3121335/default.curaproject.zip)

**Comment by smartavionics** [comment]
Those glitches are being produced by the wall overlap compensation which is long known to have problems. If you disable that, the layer view looks nicer. Whether it will print nicer or not is another matter. Hope this helps.

![Screenshot_2019-04-26_13-51-36](https://user-images.githubusercontent.com/585618/56808941-9ccb6000-682a-11e9-9ce8-cd420f1da695.png)

**Comment by kolczynsky** [comment]
Thank you! Disabling 'Compensate Wall Overlaps' resolved the problem completely. Printed part looks great now:

![err6](https://user-images.githubusercontent.com/50015237/56828245-3dd50d80-6861-11e9-850b-160c8d7cb79a.jpg)

 As I remember 'Compensate Wall Overlaps' is hidden and enabled by default. So if it's known that it causes issues, maybe it would be a good idea to disable it by default in future Cura releases?

**Comment by smartavionics** [comment]
> So if it's known that it causes issues, maybe it would be a good idea to disable it by default in future Cura releases?

But for a lot of models it is beneficial so even though flawed, it's probably better to keep it enabled by default.

**Comment by kolczynsky** [comment]
Sure. Thanks a lot!
