### ISSUE TITLE
4.0.0 Sliced model is incomplete

### ISSUE THREAD

**Issue by bkrahmer** [Ultimaker/Cura#5675]
**Application Version**
4.0.0

**Platform**
Ubuntu 18.04

**Steps to Reproduce**
Open the attached file.  Note that slicing it in the default orientation looks fine.  Now rotate it 90 degrees on the red axis.  When I slice it, regardless of support settings, only a few layers of parts of the model are being sliced correctly.  I double-checked the file with slic3r, and it looks fine there.  The number of layers seems almost correct (16mm high x 0.2 layer height = 80, and I'm getting 86 layers), but the screenshot shows the preview slider on the top layer.  Notice also that in the area on the left, the layers stop after only a few, and don't match the number of layers on the right.

[bowl.zip](https://github.com/Ultimaker/Cura/files/3128864/bowl.zip)

![Screenshot from 2019-04-29 21-17-39](https://user-images.githubusercontent.com/3302854/56920709-3fead680-6ac4-11e9-9e33-43e176853b1f.png)

**Comment by smartavionics** [comment]
The model has problems.

Cura says...

![Screenshot_2019-04-29_23-10-53](https://user-images.githubusercontent.com/585618/56930360-526d0c00-6ad4-11e9-904f-4ffb11a2d8c6.png)

Freecad says...

![Screenshot_2019-04-29_23-12-13](https://user-images.githubusercontent.com/585618/56930367-56992980-6ad4-11e9-9267-61db36ffaf08.png)

**Comment by bkrahmer** [comment]
Will you please tell me how you saw that message in cura?  I didn't get any warnings.  I know that the model is not watertight, as it's half of an object, but I don't understand what that has to do with it.  Conceptually, that model is printable (as I mentioned, slic3r seems as if it will print it).  Can you shed any light on the subject?  Thanks!

**Comment by smartavionics** [comment]
Install the mesh tools plugin from the marketplace.

![Screenshot_2019-04-29_23-19-56](https://user-images.githubusercontent.com/585618/56930664-5c433f00-6ad5-11e9-8b75-45dd0a68d07f.png)

Sorry, I don't know much about models except that when they are invalid they don't print correctly. Good luck!

**Comment by Ghostkeeper** [comment]
Yeah, the entire top surface is missing. Cura can't know what is inside the model or outside, then.
Fixed it for you: [bowl.zip](https://github.com/Ultimaker/Cura/files/3130159/bowl.zip)

**Comment by bkrahmer** [comment]
Thanks for looking at it.  I see that you added tessellated sides for the two sides that were missing.  Unfortunately, I want both of those sides to be missing.  What I'm hearing from you is that the only thing I can do is to change my shape so that it's a closed manifold, and give thickness to the entire model where I want it to be printed.  Do I have that right?

**Comment by Ghostkeeper** [comment]
Ah. Yeah, you've got that right. Cura is only meant to work with closed manifolds, watertight models. It will try to make something out of non-manifold meshes but it's not expected to work properly.

For one, Cura will not read minds so it cannot determine how thick you wanted your model to be :wink:
