### ISSUE TITLE
[4.0.0] Cura adding top and bottom layers where none exist and then adding infill.

### ISSUE THREAD

**Issue by TimCraig** [Ultimaker/Cura#5685]
I noticed Cura 4.0.0 adding top layers, bottom layers, and infill to models where none exist in the STL file.  The simplest case is a hollow cylinder.  Case I used was ID 20 mm, OD 25 mm, and height 20 mm.  After slicing and looking at the layer view, it has both top and bottom layers added across the cylinder opening and added infill.  The inner wall of the cylinder disappears.  If in the profile the top and bottom layers are reduced to 0 thickness and the infill set to 0%, only the outer wall of the cylinder is sliced.  The inner wall is not produced.

I first noticed this on more complex models.  One was the shell for an enclosure with no top or bottom.  Also on a model that had cylindrical screw bosses with a hole in their center.  A "cap" was added to the top of the screw hole.

**Application Version**
4.0.0  (Downloaded and installed 5/2/19)

**Platform**
Windows 10

**Printer**
Creality Ender-3

**Steps to Reproduce**
Slice the cylinder and compare the model in Prepare with the lines in Preview. 

**Actual Results**
If the gcode allowed to print, the extra layer is verified as actually there and not a GUI artifact.

**Expected results**
The sliced mode should look like the STL file.

**Additional Information**

[Cylinder.zip](https://github.com/Ultimaker/Cura/files/3140416/Cylinder.zip)

**Comment by smartavionics** [comment]
Hello @TimCraig , in your profile, the Remove All Holes setting was enabled (oops!) Cura was just doing your bidding. Hope this helps.

![Screenshot_2019-05-03_07-14-18](https://user-images.githubusercontent.com/585618/57122077-39ce5180-6d73-11e9-86de-b488d7076ab1.png)

**Comment by TimCraig** [comment]
Was "Remove All Holes" enabled by default in 4.0.0.  It was not not visible in my profile in either 4.0.0 or 3.5.1.   In 3.5.1 it was not enabled.  I didn't enable it in either version.

**Comment by smartavionics** [comment]
Unlikely that it was enabled by default as that would cause mass hysteria.

**Comment by Ghostkeeper** [comment]
The "Remove All Holes" setting was not enabled by default in 4.0 (nor was it ever):

https://github.com/Ultimaker/Cura/blob/59b3046c0f04a357593f18434a286832fd072a89/resources/definitions/fdmprinter.def.json#L5379-L5386

The setting is also not overwritten by Creality Ender 3 or the one in that project file, Creality CR10 (which was renamed to Creality Ender-3).

In your project file it shows that it was enabled by the user, not in any of the profiles. I think you must've clicked it accidentally.
