### ISSUE TITLE
Gaps

### ISSUE THREAD

**Issue by henkie1** [Ultimaker/Cura#5689]
Hello
Design from tinkercad,
When i slice it in Cura in the preview there are 2 gaps in the line. 

![cura-3 preview in cura](https://user-images.githubusercontent.com/50237374/57137796-30fc7080-6db1-11e9-902f-9ae90878556c.jpg)

**Comment by smartavionics** [comment]
The wall must be too thin. Try enabling the Print Thin Walls setting or reducing the wall line width.

**Comment by Ghostkeeper** [comment]
Please supply some reproduce steps or a project file. I agree that it's probably that the model is thinner than the line width. Or else it could be coasting (but then I would expect only one hole).

**Comment by henkie1** [comment]
Well, I tried a lot but nothing helps.
Attached the stl file. Perhaps sombody gives it a try.

[dalia 1,5.stl.txt](https://github.com/Ultimaker/Cura/files/3148958/dalia.1.5.stl.txt)

**Comment by henkie1** [comment]
I think I have got it. Option "print thin walls" on.  It seems its ok now.
I print wil print it this evening and let you know.
![afbeelding](https://user-images.githubusercontent.com/50237374/57241223-ce190c80-7030-11e9-88f3-52646a51b593.png)

**Comment by Ghostkeeper** [comment]
The thinnest part of your model (the tip of the leaf left of the most negative Y coordinate) is 0.347mm thick. If you set the line width to 0.347mm or lower, you'll find that all of the walls print continuously without gaps. Print Thin Walls is an easier alternative (but will result in some extra travel moves).
