### ISSUE TITLE
[4.X GIT] Unnecessary Nozzle Move Every Layer

### ISSUE THREAD

**Issue by Enverex** [Ultimaker/Cura#5690]
I've never seen this before and no-one I've asked has been able to explain what is happening here. Basically, at the start of every layer, the nozzle will move to the front of the print,  move back and forth a bit and then carry on with the print. It's hard to explain so here's a video of it happening - https://www.youtube.com/watch?v=sRfVzFExcMQ

This "dance" is even visible in sliced view itself (the purple line closest to the camera in the bottom left). 
![image](https://user-images.githubusercontent.com/958670/57168566-36ca7400-6dfa-11e9-89f3-7ac885a28cee.png)

It doesn't extrude when it does this, it purely seems to be a travel move, but with no obvious purpose. For reference, I've attached the 3MF file of the model/setup.
[Ocarina.zip](https://github.com/Ultimaker/Cura/files/3143692/Ocarina.zip)

**Comment by smartavionics** [comment]
Sorry, I can't investigate this as the project file won't load. Can you create another user a standard printer type? Thanks.

![Screenshot_2019-05-04_07-22-29](https://user-images.githubusercontent.com/585618/57174905-79fa0680-6e3d-11e9-8043-91bf97998b60.png)

**Comment by smartavionics** [comment]
Actually, just attaching the gcode would probably be good enough, thanks.

**Comment by Enverex** [comment]
Here you go. 
[Ocarina.zip](https://github.com/Ultimaker/Cura/files/3144314/Ocarina.zip)

**Comment by smartavionics** [comment]
OK, I discovered what the problem was, you had the Wipe Nozzle Between Layers feature enabled.

![Screenshot_2019-05-04_13-22-09](https://user-images.githubusercontent.com/585618/57178929-ceb67500-6e6f-11e9-84c6-4c048e11f8d2.png)

**Comment by Enverex** [comment]
Is there anything else that would enable this? As it's not something I would have turned on (due to not having a multi-head setup). Also, what does it think it's wiping it on?

**Comment by smartavionics** [comment]
> Is there anything else that would enable this? As it's not something I would have turned on (due to not having a multi-head setup).

No, there is nothing else that would enable this.

> Also, what does it think it's wiping it on?

Good question, I don't know. I guess the creator of this feature had a brush mounted somehow.

**Comment by smartavionics** [comment]
FYI https://github.com/Ultimaker/Cura/pull/5356

**Comment by Enverex** [comment]
Thanks, I'll chalk it up to an unnoticed misclick at some point then.

**Comment by Ghostkeeper** [comment]
> Also, what does it think it's wiping it on?

Yeah, this is intended for printers with a wiping brush.
