### ISSUE TITLE
[4.1] Wrong text inserted into printer name label

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#5697]
**Application Version**
All built from 4.1 branches

**Platform**
Doesn't matter.

**Printer**
Doesn't matter.

**Steps to Reproduce**
Choose "Monitor" tab

**Actual Results**
Label shows "Extruder 1"

**Expected results**
Label should show the printers name

**Additional Information**

![image](https://user-images.githubusercontent.com/1847437/57191115-480ea000-6f22-11e9-8e42-130f503854bf.png)

![image](https://user-images.githubusercontent.com/1847437/57191135-8ad07800-6f22-11e9-8be0-eadbfe3f383e.png)

![image](https://user-images.githubusercontent.com/1847437/57191154-a6d41980-6f22-11e9-9364-8d2c52f24f5b.png)

**Comment by Ghostkeeper** [comment]
I could reproduce this, but only when switching to a printer that wasn't created during the same session. So these were my reproduction steps:
1. Add two printers.
2. Restart Cura.
3. Switch to the Monitor page.
4. Switch printers.

**Comment by thopiekar** [comment]
Ok, had both printers added already.

>

**Comment by thopiekar** [comment]
Has the problem been solved for the beta? Or is it going to be resolved before the final release?
Personally, I would find it wise to care about getting that fixed.

I think it is an annoying one.

**Comment by Ghostkeeper** [comment]
Ah yeah we fixed this for 4.1. It was in fact also happening in the main printer selection drop-down in the prepare stage.

**Comment by thopiekar** [comment]
Great, thanks! 👍
