### ISSUE TITLE
[4.0.0] Frequent Corrupt Configuration Errors

### ISSUE THREAD

**Issue by si-hb** [Ultimaker/Cura#5706]
**Application Version**
4.0.0

**Platform**
Windows 10 on Microsoft Surface Book

**Printer**
UM3

**Steps to Reproduce**
Unsure, problem happens occasionally when booting Cura. I do not recall this happening with earlier versions

**Actual Results**
All my custom material configurations are lost and I have to re-enter them.

**Expected results**
For there to be no configuration errors when launching Cura

**Additional Information**
I add material costs to all my filaments, perhaps this is a clue. 
[Cura Files](https://drive.google.com/file/d/1wSkgR3ULCww0v0LvWZAy5sMiPn5bYa8d/view?usp=sharing)
[Error Message](https://drive.google.com/file/d/1wRjFg_jpat2pnjn4HNCx4DCjjw10pIox/view?usp=sharing)

**Comment by Liger0** [comment]
Same. All the custom printers and profiles get corrupted at every restart since 4.0

**Comment by Ghostkeeper** [comment]
When starting Cura 4.0 with your settings folder, I get the following message in the log:

```

2019-05-07 11:06:13,003 - ERROR - [MainThread] UM.Settings.ContainerStack.getConfigurationTypeFromSerialized [335]: Could not get configuration type: File contains no section headers.
file: '<string>', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

This looks like the files `definition_changes/Ultimaker+3_settings.inst.cfg` and `Ultimaker+3.global.cfg` got corrupted, meaning that Cura unexpectedly closed while it was writing these files. Maybe it got killed by the task manager, or maybe it crashed completely.

In any case, that data is lost.

Question is really, what caused Cura to crash?

Other question in a different line of search, do you often use multiple instances of Cura at the same time?

**Comment by si-hb** [comment]
I do not use multiple instances intentionally, though it's likely I have launched multiple instances accidentally from time to time. The second instance is always closed.

At any rate, I've had the above error at least a half dozen times since using 4.0.0. Never had the problem in earlier versions of Cura.

**Comment by Ghostkeeper** [comment]
Well once it's corrupt it's going to stay corrupt until the files are either removed or restored.

Except on first run of a new version, Cura doesn't save anything to file if you don't change anything in the interface, so it shouldn't get corrupt by accidentally opening two instances.

We haven't seen this happen ourselves though. We have no idea yet what causes these files to get corrupt :confused:

**Comment by Ghostkeeper** [comment]
It writes configuration files every 10 seconds if there has been a change to any profile or added printer. It puts a message in the log then that it's autosaving. It also writes configuration files when closing Cura (normally, not when crashing) and when upgrading from a previous version during start-up.

**Comment by si-hb** [comment]
If I may suggest, perhaps on each config write, rename existing as backup and write new. If Cura detects an onerous config on start it can ask user "Use last known good config?".

**Comment by Ghostkeeper** [comment]
We do keep a backup from before upgrading.

It's a bit too big to make a back-up every 10 seconds though.

**Comment by si-hb** [comment]
You're writing the backup repeatedly every ten seconds? That would certainly indicate a potential problem to me, and an unnecessary waste of resources and disk write cycles.

**Comment by Ghostkeeper** [comment]
No, we're writing only the profiles that have changed. When changing profiles they get marked as "dirty" and then written to disk upon the next autosave, instead of immediately. This saves resources and disk write cycles.

**Comment by betavr** [comment]
I just lost my printers' configurations after a power outage. My custom startup/finish g-codes are gone, apparently the cfg files have been overwritten with zeros.  :(

**Comment by Kira0tori** [comment]
Hello everyone. Same problem here with Cura 4.4.0. A power outage happened while Cura was open but not used. After a restart, all definitions/profiles were corrupted. I tried to go see in %APPDATA%/Local or Roaming or into Programs/Ultimaker Cura 4.4 but I waw unable to find old defintions or at least to restore them. Is there any way or should I give up already and re-write them from scractch ?
Thanks for your help

**Comment by Ghostkeeper** [comment]
Look in %APPDATA%/Roaming/cura/4.4 and see if there is anything there that you need to remove or fix references in. All files there are plaintext.

**Comment by eman717** [comment]
This happened to me tonight. I've reentered my Printer's settings a bit ago and it freaked out and corrupted itself again. I've ran CCleaner and updated my graphic driver. This happens for me when hte screen starts flashing a bunch of random colors, and that only happens when i'm running this software. I can't do anything with the PC when taht happens, just a hard reboot. When the PC starts back up and reaches desktop, those config files are all corrupted again.

**Comment by Ghostkeeper** [comment]
I'm not really sure what to say. It's not like we are calling a command that makes all the pixels on your screen flash pink and green. Not directly anyway.

If the screen is flashing in random colours, I'd really put the blame somewhere between the graphics driver and the screen. It could be anything from faulty drivers to a broken cable. Cura may be the only application you found that triggers this, maybe because it tends to only re-render parts of the window (something that the Qt framework does for us). I'm not sure if there is something we can really do to help you.

The configuration files are most likely corrupt because your computer was still writing the changes to disk when it freezes or is rebooted.

**Comment by Thisismydigitalself** [comment]
I had to come back here and post about corrupt configurations which once in a while happens to me and to so many others. this is going on for years now so i am guessing before 4.x as well. now when i got these errors i want to fix this and not get this message every time i launch Cura. i am running 4.7.0 which i really like. i was searching for the profiles listed in this error message and tried to delete those. i deleted one by one.  first, second, maybe the third one as well were removed from this list which made me believe i can do this, but deleting the next one just made the list twice as long so i restored the files i deleted and the error list got back to how you see. I really hate running Cura and get this annoying error message. please help me get rid of it. thank you.
![ice_screenshot_20201018-203539](https://user-images.githubusercontent.com/30949968/96375730-589cef80-1183-11eb-90a8-93844eb1653e.png)

**Comment by fieldOfView** [comment]
> the startup optimizer plugin that has the option to only delete the broken profiles.

Minor correction: it does not delete anything; it prevents files from being loaded by Cura.

**Comment by Thisismydigitalself** [comment]
Must I sign in for downloading and/or add this plugin to Cura?..

**Comment by Thisismydigitalself** [comment]
Ok, Found it.
Installed
![ice_screenshot_20201020-002401](https://user-images.githubusercontent.com/30949968/96513662-1e0e8200-126b-11eb-826a-62df58d5ca81.png)

Yes,disable please
![ice_screenshot_20201020-002529](https://user-images.githubusercontent.com/30949968/96513717-38e0f680-126b-11eb-9696-1640ea73aa35.png)

Done.
![ice_screenshot_20201020-002548](https://user-images.githubusercontent.com/30949968/96513735-3ed6d780-126b-11eb-9e94-ad80c0b6dd24.png)

No more errors.
![ice_screenshot_20201020-002633](https://user-images.githubusercontent.com/30949968/96513763-4c8c5d00-126b-11eb-92d7-b0d40f78bb13.png)

Aldo, you're the man.
Thank you.
