### ISSUE TITLE
[4.0] Retract in start g-code issue

### ISSUE THREAD

**Issue by ilko-k** [Ultimaker/Cura#5713]
Whenever a retraction line is inserted in the start g-code, it is over-retracting like 10mm lenght (I did not measure), even if it is set to 0.1mm. It seems that the value is ignored and does an absolute retraction.

note : it occurs when printing via USB. Will try via SDC soon

**Comment by ilko-k** [comment]
Hey @smartavionics, I'll tell more about that when my actual print wil be finished. For now, I'm not sure what details I could provide, this occurs when I print via USB and with any project. I didn't try by SDC yet but I'll try.

**Comment by ilko-k** [comment]
ok, so here is the two lines that are written after the custom start g-code : 

```
; End of custom start GCode
G92 E0
G1 F2400 E-4
```

An additional retraction is generated whereas it's not needed.

**Comment by smartavionics** [comment]
OK, but that in isolation tells me next to nothing. Without seeing your settings it's very difficult to guess what's happening. Please either attach the complete gcode file or the project file (they will need to be zipped to let you attach them). Thanks.

**Comment by ilko-k** [comment]
ok, I've zipped a project plus the settings I'm using. I'm printing PETG.
[Calicube.zip](https://github.com/Ultimaker/Cura/files/3159533/Calicube.zip)

**Comment by smartavionics** [comment]
Thanks for the files, all is clear now.

> An additional retraction is generated whereas it's not needed.

Well, that retraction (and the prime that follows after moving to where the skirt is printed) are OK, the real problem is your include of this line in your start code:

```
G1 F2000.0 E-1 ; retract 1mm
```

Remember, you are using absolute extrusion mode and so that -1 means wind 21 mm of filament back as you have previously extruded 20 mm of filament!

Hope this helps.

**Comment by Ghostkeeper** [comment]
> An additional retraction is generated whereas it's not needed.

This retraction prevents a big fat line from being drawn across your build plate, which the rest of the print may collide with, leaving a scar across the bottom of your print. The retraction is unretracted a couple of lines later:

```
;TYPE:SKIRT
G1 F2400 E0
```

**Comment by GregValiant** [comment]
Can we close this?  It appears it was a StartUp Gcode issue.

**Comment by ilko-k** [comment]
Oh wow i completely forgot this. Closing. Sorry for the inconvenience.
