### ISSUE TITLE
An unusuable space around the platform

### ISSUE THREAD

**Issue by jokinb** [Ultimaker/Cura#572]
There is an unusuable space of 15 mm around the printer plataform. In this area you can not put any object, so the useful space is reduced. .by 30 mm.
![img 111](https://cloud.githubusercontent.com/assets/16365942/11915510/a016c6be-a6a9-11e5-8ed4-144ffb89b3cc.jpg)

**Comment by Ghostkeeper** [comment]
This is intended.

If you'd place your object there, the brim, skirt or raft would go off the platform. If you reduce the radius of your brim, skirt or raft it should make these borders smaller so you can place your object there.
