### ISSUE TITLE
[3.6.0] It is not sliced if the initial layer is high.

### ISSUE THREAD

**Issue by yoch2015** [Ultimaker/Cura#5734]
Hello.
In order to print nylon, since a bed of 1 mm is covered with a phenol board, if it is sliced ​​by plus 1 mm to initial layer height, printing will start from the middle without being sliced ​​about 1 mm.
Is there a solution?
The photo is a layer view with the first layer selected, but the part that is not printed below is already displayed.
<img width="720" alt="screenshot 2019-05-13 14 39 30" src="https://user-images.githubusercontent.com/16486394/57598832-b3deb180-758f-11e9-8b1a-43611270e91f.png">

**Comment by fieldOfView** [comment]
Try the Z Offset plugin.

**Comment by yoch2015** [comment]
Thank you.
I installed the plug-in and set it to 1.1mm.
The generated g code was started at 1.25 mm, so it was resolved.
<img width="720" alt="screenshot 2019-05-13 15 27 18" src="https://user-images.githubusercontent.com/16486394/57600144-f1ddd480-7593-11e9-801d-2aa9b13143ab.png">

**Comment by Ghostkeeper** [comment]
Alternatively, disable the setting "Remove empty first layers".
