### ISSUE TITLE
'Placing objects' message does not have close button.

### ISSUE THREAD

**Issue by Eyos** [Ultimaker/Cura#5749]
Cannot close those messages and they obscure the working area.

**Comment by Ghostkeeper** [comment]
Most of our progress bars don't have a close button because that would cause people to think you can abort them, but you can't.

**Comment by diegopradogesto** [comment]
This message should automatically close when the process is finished. I tested in 4.1 and it works as expected.

I'll close the ticket but if you find a different behaviour, please reopen it and provide more information, such as which version of Cura you are using, OS, ... (based on the issue template)
