### ISSUE TITLE
[4.1 beta] nozzle icon out of its window

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5751]
**Application Version**
4.1 beta

**Platform**
WIn10 x64

**Printer**
Dual extrusion

**Steps to Reproduce**
-

**Actual Results**
The section that cointains the nozzle icon isn't high enough, so when switching to the other nozzle, the unselected one has the tip going over its cointainer.

**Expected results**
Add a padding on the bottom and/or center the nozzle icon

**Additional Information**
![nozzle out of tab](https://user-images.githubusercontent.com/20385116/57972364-8d5ab500-7999-11e9-86f2-a65848251c26.png)

**Comment by nallath** [comment]
That's odd, it does have the padding you would expect on my screen 
![ExtruderIconPadding](https://user-images.githubusercontent.com/3922611/58003577-5a233d80-7ae1-11e9-83bd-a28d90dd4c6f.png)

Is there some more info you could share about your screen size & DPI?

**Comment by Liger0** [comment]
I use 125% window resize in Windows 10 because 100% is unplausible on QHD and higher resolutions.

**Comment by Ghostkeeper** [comment]
I'm also using 125% scale on my laptop screen, but since I'm using Ubuntu the font renderer is different, and because Cura's screen scale resizing is based on font sizes, it probably causes the total height to be different here as well than on Windows.

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?

**Comment by Liger0** [comment]
It seems fixed now.
