### ISSUE TITLE
[4.1 beta] Marketplace tab glitches

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5755]
**Application Version**
4.1 beta

**Platform**
Win10 x64

**Printer**
-

**Steps to Reproduce**
Open the marketplace tab

**Actual Results**
The custom setting visibility set creator and its description are crossing each other.
The marketplace tab also can't resize

**Expected results**
Separate title and description. Make the tab resize

**Additional Information**
![marketplace tab](https://user-images.githubusercontent.com/20385116/57983250-e8e77a00-7a4f-11e9-8e53-b3d0c7697d47.png)

**Comment by nallath** [comment]
Thanks for reporting. Fixed it for the 4.1 release.
