### ISSUE TITLE
missing  2 layer (one at begin, one at the end)

### ISSUE THREAD

**Issue by xvalerix** [Ultimaker/Cura#5757]
**Application Version**
4.0 & 4.1 beta

**Platform**
Ubuntu Linux

**Printer**
Ender 3, but non important

**Steps to Reproduce**
slice with same layer height setting (also the first layer) with another slicer

**Actual Results**
CURA 63 layer

**Expected results**
Simplify or PrusaSlicer 2, 65 layer 

**Additional Information**
Found the difference:
Set slicing tolerance in "Exclusive", ok with "Middle" and with "Inclusive"
Also if print in vase mode (spiralize) with 1 bottom layer, first layer is missing and do only the perimeter.
*****
If it is not clear, ALL layers set to the same value, no matter what, in my case 0.12 (yes ALL, ALSO FIRST)

**Comment by nallath** [comment]
Did you also take "Initial layer height" into consideration?  By default that's set higher than the normal layer height (0.3 vs 0.1).

**Comment by xvalerix** [comment]
> Did you also take "Initial layer height" into consideration? By default that's set higher than the normal layer height (0.3 vs 0.1).

Obviously and I write it in  >"(also the first layer)"<

**Comment by xvalerix** [comment]
it very easy to duplicate, get an stl cube of 20x20, slice with 0.2 layer height.
- with slicing tolerance set to "Middle" or "Inclusive" you get 100 layer (100 x 0.2)
- with slicing tolerance set to "Exclusive" you 
![Exclusive](https://user-images.githubusercontent.com/50801152/58005638-665dc980-7ae6-11e9-9207-c113a6bc5e32.png)
![inclusive](https://user-images.githubusercontent.com/50801152/58005639-665dc980-7ae6-11e9-8e6e-63a4a11bbb5f.png)
![middle](https://user-images.githubusercontent.com/50801152/58005640-665dc980-7ae6-11e9-87d5-63ce7175fc82.png)


get 98 layer... 2 are missing

**Comment by Ghostkeeper** [comment]
Yes, when setting the slicing tolerance to "Exclusive", it's intended that you get somewhat looser tolerances in the sliced (Z) direction. That's really what the setting is made for.

**Comment by xvalerix** [comment]
> Yes, when setting the slicing tolerance to "Exclusive", it's intended that you get somewhat looser tolerances in the sliced (Z) direction. That's really what the setting is made for.

So missing 2 layer isn't a bug but "a features"
Ok good to know.
Any other "features"?

**Comment by Ghostkeeper** [comment]
It's omitting some part of the model because you asked it to give greater tolerances.

> Any other "features"?

If you set the infill density to 0%, it's going to be missing some infill lines :stuck_out_tongue: 

Perhaps more to the point, if you set Horizontal Expansion to -0.2mm, you're going to get a similar tolerance in the X/Y direction. Very useful if you're trying to get parts to fit together but your material isn't flowing exactly as you want it to.
