### ISSUE TITLE
Top layer flow setting

### ISSUE THREAD

**Issue by kyjak** [Ultimaker/Cura#5767]
**Application Version**
Any

**Platform**
Any

**Printer**
Any

**Actual Results**
Cura allows to change flow for bottom layer and the rest of the model only

**Expected results**
Change flow for top layers, as they are very often printed in a different way

**Additional Information**
This is a feature request, not a bug

**Comment by Ghostkeeper** [comment]
This is to be implemented through https://github.com/Ultimaker/CuraEngine/pull/874

**Comment by kyjak** [comment]
great, thx!
