### ISSUE TITLE
[2.1] GCode generated by Slic3r failes to open

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#578]
After selecting a GCode file (generated by Slic3r), a dialog said that opening that file failed.
The console output does not show any interesting error messages.

The download link is https://github.com/bq/hephestos-2/blob/master/Samples/Samples.zip?raw=true .

**Comment by Ghostkeeper** [comment]
Same reason as #577

**Comment by thopiekar** [comment]
Having #577 open should be enough...
