### ISSUE TITLE
[4.0.0] Add Flow rate to material profile

### ISSUE THREAD

**Issue by zebons** [Ultimaker/Cura#5785]
Flow rate is directly link with material used so it'd be managed at material level and added in material profile. 
Already asked in previous versions and alternatives solutions given here but not working in Cura 4.0.

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3946
There's a plugin for this here:
https://github.com/Ultimaker/Cura/issues/3946#issuecomment-487315588

**Comment by zebons** [comment]
Works fine with the plugin MaterialSettingsPlugin as decribe in issue #3946
