### ISSUE TITLE
[4.0.0] Text corruption on Monitor view on Mojave

### ISSUE THREAD

**Issue by martynbrearley** [Ultimaker/Cura#5789]
**Application Version**
4.0.0

**Platform**
MacOS 10.14.5 (Mojave)
MacBook Pro Retina 15" Mid 2014

**Printer**
S5

**Steps to Reproduce**
Frequently occurs when trying to monitor a print in progress, after creating the job and swipe-switching desktops a few times.
Only seems to happen once an object has been rotated/moved. During the rotation/move, the font of the rotation angle/distance label shows a small amount of corruption, but it's then the Monitor page that shows it the worst.
Closing Cura app and restarting it usually clears the issue.

**Actual Results**
Text becomes heavily corrupted

**Expected results**
Text should remain readable

**Additional Information**
<img width="869" alt="Screenshot 2019-05-27 at 17 59 12" src="https://user-images.githubusercontent.com/6032961/58432637-49f3fb00-80ab-11e9-9421-97d2a4ea8c8c.png">

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?

**Comment by martynbrearley** [comment]
Thanks for checking Greg. It does appear to have been fixed a while back. I've currently got 5.7.2 and it doesn't occur there. I'm on Sonoma 14.7 so it could have been MacOS that changed. Hard to say.
Please go ahead and close.

**Comment by GregValiant** [comment]
Thanks.  I'll close it.
