### ISSUE TITLE
Prime Tower Brim self-intersections

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#5792]
**Application Version**
4.1 beta

**Platform**
Windows 10

**Printer**
UM3

**Steps to Reproduce**
Enable brim for prime tower
put object close to prime tower

**Actual Results**
Toolpaths for prime tower intersect toolpaths for model

**Expected results**
There should never be multiple toolpaths in the same location.
The areas of print features should never be overlapping (except for as much as the infill overlap etc.)

**Additional Information**
![image](https://user-images.githubusercontent.com/8895761/58472720-29797e80-8147-11e9-986b-f23878880351.png)

**Comment by BagelOrb** [comment]
Also happens in 4.1 final, which was just posted online:
![image](https://user-images.githubusercontent.com/8895761/58483601-e0362880-8160-11e9-8c39-008bfff504e5.png)

**Comment by BagelOrb** [comment]
[tower_brim_bugs.3mf.rename.zip](https://github.com/Ultimaker/Cura/files/3228010/tower_brim_bugs.3mf.rename.zip)

**Comment by rburema** [comment]
Thanks for the report: See https://github.com/Ultimaker/Cura/pull/5806

**Comment by Liger0** [comment]
It would also be useful to calculate a working position for the purge tower.
Normally, when enabling it, the slicing will fail because the purge tower by default is over the build plate.

**Comment by BagelOrb** [comment]
@Liger0 that's a wholly different issue. For Ultimaker machines the tower *has* to be on the build plate.

**Comment by Ghostkeeper** [comment]
Fixed for the next release. Thanks for the report!

**Comment by rburema** [comment]
That depends on what you mean by the brim-width issue? If you mean that the brim becomes double-wide if both 'brim for prime tower' is selected _and_ the 'normal' adhesion method is also set to brim, then it's expected behaviour.

**Comment by Ghostkeeper** [comment]
No, the fact that the brim is wider than the disallowed area of the prime tower wasn't changed because it's not a bug.

Like the brim around printed models, the brim around the prime tower brim can intersect with other brims. They will be unioned then, so models are allowed to be placed close to the prime tower.

**Comment by BagelOrb** [comment]
> If you mean that the brim becomes double-wide if both 'brim for prime tower' is selected and the 'normal' adhesion method is also set to brim, then it's expected behaviour.

No I didn't mean that, but that sounds like a bug which is easily fixed, just by subtracting the normal brim width from the user specified towre brim width when creating the tower.

**Comment by BagelOrb** [comment]
Never mind the original (second) issue. I was confused that the tower was smaller than the disallowed area, while the tower brim was larger than the disallowed area.

**Comment by BagelOrb** [comment]
Why not fix the double brim issue, though?

**Comment by rburema** [comment]
Why? It can be a feature as well. Removing it would limit the ammount of different behaviour you can get, and the double brim may be useful in certain contexts. Plus may be sort of expected depending how you interpret both settings being present/on.

**Comment by rburema** [comment]
It is different, since right now the prime-tower brim is just an on or off thing, and you can't specify the brim-width specifically for prime-tower right now, which means that, if you want a larger brim for prime tower than the rest of the model, you can.

I see your point though, I'll bring it up during the CCB.
