### ISSUE TITLE
4.1 does not import most recent profiles / settings

### ISSUE THREAD

**Issue by theWaldschrat** [Ultimaker/Cura#5799]
**Application Version**
Issue occurred in 4.1, but could also affect older versions (not tested).

**Platform**
Windows

**Printer**
Creality Ender 3, but that's irrelevant

**Steps to Reproduce**
I had three subfolders in the cura folder of my windows profile: "3.6", "4.0 - Kopie" and "4.0".
I had 3.6 and 4.0 installed when 4.1 was released, but I had been using only 4.0. The "4.0 - Kopie" folder was left over from some tests when transitioning from 3.6 to 4.0.
After deinstalling 3.6 but keeping the settings, I installed 4.1 and started it.

**Actual Results**
4.1 imported setting from either "3.6" or "4.0 - Kopie", i.e. old setting that hadn't been updated in a while.

**Expected results**
4.1 imports settings from the most recently used "4.0" folder.

**Additional Information**
After closing 4.1, deleting the new "4.1" folder and all folders except "4.0" and then restarting 4.1, the correct settings were imported.

**Comment by Ghostkeeper** [comment]
Yeah your bug reproduces for me as well. I could give the easy answer of "don't muck with the config files" but there could be something underneath here.

Let's see. The folder that it imports setting with is determined here:

https://github.com/Ultimaker/Uranium/blob/341937cc876eabada25fbe0674b90e443e59f629/UM/Resources.py#L516

20 lines below it finds a folder that matches this regex. This regex includes the clause `.*` towards the end, which matches on the ` - kopie` part of your folder name. The folders are sorted alphabetically (different bug: this will be a problem when we reach version 4.10) and the last one is taken, which is the `4.0 - kopie` in your case.

I don't know why it matches on `.*`. Files are never stored there, not even for our daily development versions. So I removed it. Thanks for the report, it should work better in version 4.2.
