### ISSUE TITLE
Cura 4.1 Prints very slow Tevo Tornado

### ISSUE THREAD

**Issue by TerryLSmith** [Ultimaker/Cura#5801]
**Application Version**
4.1

**Platform**
Octiprint

**Printer**
Tevo Tornado

**Steps to Reproduce**
I updated Cura from 4.0 which I had just printed from, created an file and dropped it in opctiprint and started the job and watch as it tried to do the first layer and killed the job because it took 5 min to do a 1.5 inch circle of support.

**Actual Results**
I killed the job as I was on lunch and did not have time to try to diagnose it. It looked like it was trying to think about what to do next then it would do it again. I watched it several time move then hesitate.

**Expected results**
On ver 4.0 It never started that slow. Then hesitated

**Additional Information**

**Comment by diegopradogesto** [comment]
We would need a little bit more information

**Comment by Ghostkeeper** [comment]
Yeah some information was hidden away in the `<!--` `-->` comments that are there for the template. I edited the post so that they are visible.

**Comment by Ghostkeeper** [comment]
Could you provide a project file that reproduces the problem? You can create a project file in Cura by going to File -> Save...
You'd need to zip up the file to be able to upload it here on Github.

**Comment by chiefcw** [comment]
I found that if the maximum z-axis speed is left at zero Cura sends G1 F17987547480000 to Marlin on z-moves which resulted in the z-axis moving extremely slow.  When changed to 5 in Cura it then sent G1 F300 in the gcode.

**Comment by TerryLSmith** [comment]
Worked like a charm thanks.
