### ISSUE TITLE
Cura 4.0 slow and not slicing

### ISSUE THREAD

**Issue by voodooherbalist** [Ultimaker/Cura#5802]
Cura 4.0 is taking forever to open projects and when it does open it gives me an error for slicing....
Slicing engine for Cura has stopped working
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available..

**Application Version** 4.0

**Platform** Windows 10

**Printer** Ender 3

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by nallath** [comment]
Without any logging, there is nothing we can do to help you. Please fill in the entire bug report, it's there for a reason.

**Comment by Ghostkeeper** [comment]
Could be that problem with scanning for USB ports blocking the job queue?
