### ISSUE TITLE
[4.1] Interface layers on dual extrusion machines missing if the part is small

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5812]
**Application Version**
4.1

**Platform**
Win10 x64

**Printer**
Custom dual extrusion

**Steps to Reproduce**
Use interface layers

**Actual Results**
The interface layers will be missing on both bottom (normal layers used instead) and top (layers on the top are just missing)
I also used a 0.00 XY distance on supports but it is pretty far from the model.

**Expected results**
Use interface layers. Separation distance should be followed.

**Additional Information**
![missing inbterface layers supports](https://user-images.githubusercontent.com/20385116/58592637-2bd3f980-8269-11e9-9607-98041b67dca9.png)
[missing interface layers supports.zip](https://github.com/Ultimaker/Cura/files/3234543/missing.interface.layers.supports.zip)

**Comment by Ghostkeeper** [comment]
That's caused by this open bug: https://github.com/Ultimaker/Cura/issues/2205

So I consider this a duplicate then.
