### ISSUE TITLE
Manual Supports not working in 4.1

### ISSUE THREAD

**Issue by OldGaf** [Ultimaker/Cura#5813]
In Cura 4.0 I am able to have _ONLY_ manually added supports created.
This does not work in 4.1.
![Man-Sup_not_working](https://user-images.githubusercontent.com/47789457/58594760-f1f0fc00-8244-11e9-9c02-f30df63aa660.jpg)

**Application Version**
4.1.0

**Platform**
Win7

**Printer**
CR10S

**Steps to Reproduce**
Un-check Supports, manual add supports and slice/preview

**Actual Results**
No supports are created.

**Expected results**
Manually added supports should be created.

**Additional Information**
This works in 4.0

**Comment by Ghostkeeper** [comment]
For me it doesn't even print if Enable Support is properly checked. Seems broken altogether.

**Comment by OldGaf** [comment]
Confirmed. 
I did not try to print as I saw them nor displayed in the preview. 
I created a test print and let it print the first layer to check, no manual support created at all.

**Comment by Italque** [comment]
Hi, same problem here. The support will be printed only if checked generate supports. If I use some print as supports model they won’t be printed. Useful working  feature in previous versions. If anybody knows how to solve it, please keep me posted about. Thanks

**Comment by seltix5** [comment]
Yes it's not printing supports, only if they are touching the bed

**Comment by Ghostkeeper** [comment]
Oops, yeah we fixed this in version 4.2, but forgot to close the ticket here. Try the beta, see what you think!
