### ISSUE TITLE
General: Missing release tags across all (sub-)projects

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#5820]
The 4.1.0 tag is missing across all subprojects including Cura itself. Here a checklist for you:
- [ ] Cura
- [ ] CuraEngine
- [ ] Uranium
- [ ] libSavitar
- [ ] libArcus
- [ ] libCharon
- [ ] fdm_materials
- [ ] cura-binary-data

**Comment by Ghostkeeper** [comment]
Yup. Didn't have time on Wednesday to do this and Thursday was ascension day. Sorry. Done this morning.
