### ISSUE TITLE
Gyroid Support affects visibility of Connect Support Lines

### ISSUE THREAD

**Issue by mbartlett21** [Ultimaker/Cura#5821]
**Application Version**
4.1.0

**Platform**
Windows 10 1903

**Steps to Reproduce**
Tick "Generate Support"
Change support pattern to gyroid
Untick "Generate Support"

**Actual Results**
"Connect support lines" parameter is visible

**Expected results**
"Connect support lines" parameter  should not be visible

**Additional Information**
![image](https://user-images.githubusercontent.com/29034492/58682271-300c2e00-83b3-11e9-9fa7-7fc0dfe3508a.png)

**Comment by smartavionics** [comment]
Yes, and it also occurs when the support pattern is grid, triangles or cross.

**Comment by mbartlett21** [comment]
Thankyou!
