### ISSUE TITLE
4.1 Creality CR-10S random pauses

### ISSUE THREAD

**Issue by zipspence** [Ultimaker/Cura#5825]
Issue resolved - case #5753 Enable Maximum Z Speed under the Speed options and set to your choice (mine is 60 which is slow for the printer but slow and steady wins the race)

**Application Version** 4.1 (happened with 4.0 also)

**Platform** Win10, i7-7700K, Nvidia 1070's in SLI Driver 430.86.

**Printer** CR-10S, issue happens with all projects. 

**Actual Results** The printer randomly pauses during the print, seems to happen more at the end/start of a layer. Printing either through usb or via sd card. However it seems printing via sd card does seem to cause the issue to happen less.

**Expected results** The printer will not stop or pause during the print. 

**Additional Information** I am using the Marlin from TH3D version R2.11
I also have the EZABL and various other upgrades.

**Comment by smartavionics** [comment]
Most likely same as #5753.

**Comment by zipspence** [comment]
testing various settings now.

**Comment by Seref** [comment]
Same here!
**Application Version 4.1** (didn't happen with 4.0)
**Platform** Win10
**Printer** Modified/Custom 3D Printer, issue happens with all projects at the start on Layder 1&2

I upgraded to 4.1 and the first thing that happened was that everything just stopped after some certain point.
Doesn't matter if I print over USB or export it onto a SD Card and print it from there, the printer just stops (it doesn't freeze since the you can still access the menu and stop the print).

**Comment by zipspence** [comment]
Issue has been corrected, default value on Maximum Z Speed was the issue, *input 60 mm/s* 

Case resolved, thankyou  for the help smartavionics for the tip. 

I had to read further into the case #5753 in order to see the resolution

**Comment by zipspence** [comment]
Issue was resolved set max z speed

**Comment by xavierator** [comment]
Hi, I think I have a similar problem, but difficult to understand for me.

I just purchase the printer 1 week ago, I finished right 2 prints and after that all prints stop randomly.

I'm using CURA 4.8.0.

What dou you think ?

Ned I to change the maximum Z speed in printer settings, upgrade the printer firmware, change something in CURA, ... ?

Many thanks, Xavi

**Comment by zipspence** [comment]
Go into cura and go into your speed options. You will need to expand the
extra options for this menu in your setting and find your Z axis speed
setting and set it to a reasonable value. 150 or so.

**Comment by xavierator** [comment]
I just expanded all speed options:

![imagen](https://user-images.githubusercontent.com/72919602/106768237-03a2bd80-663c-11eb-8f5c-8be47207570b.png)

But I can't find Z axis speed:

![imagen](https://user-images.githubusercontent.com/72919602/106768273-0b626200-663c-11eb-9ce2-152a9b9356d8.png)

Thanks

**Comment by Ghostkeeper** [comment]
Maximum Speed Z is a machine setting and not visible in the interface. It can normally only be changed by printer definitions.
There is a plug-in in the marketplace called Printer Settings which will make those settings visible. This then allows you to change settings which Cura considers to be inherent to the printer or its firmware.

In Cura 4.8, the Maximum Speed Z is only used as maximum for setting values, not as default, unless you've modded Cura. So changing it would not have an effect on the print, just on the time estimates and on how far you can adjust settings that relate to Z movement speed (like Z hop speed and wire printing speeds).

**Comment by zipspence** [comment]
Z hop speed

**Comment by xavierator** [comment]
**Mistery discovered:** in my case is a filament sensor problem, I'll need to change the filament sensor that detect wrong the end of filament when there are filament.
Thanks for your help
