### ISSUE TITLE
[4.0.0] Preview color scheme is not distinct enough

### ISSUE THREAD

**Issue by protist** [Ultimaker/Cura#5827]
**Application Version**
4.0.0

**Platform**
Arch Linux

**Printer**
N/A

**Actual Results**
Select `Preview` > `Color Scheme` > `Line type`.

Two colours in particular are difficult to tell apart: `Top / Bottom` is yellow, and `Infill` is orange.

**Expected results**
It should be easy to tell them apart. There are quite a few unused colours, so using more distinct colours would be helpful. Alternatively, the colours could be customisable.

**Additional Information**
I've picked a simple area for the screenshot, but with more complex models, it can be difficult to discern infill from top/bottom.
![Screenshot](https://i.imgur.com/qaB4NXd.png)

**Comment by Ghostkeeper** [comment]
I agree with this actually. Bit of a long-standing issue that has always been a bit of a papercut.

**Comment by Ghostkeeper** [comment]
Similarly with support and support interface.

**Comment by Ghostkeeper** [comment]
![Screenshot from 2019-06-07 13-16-30](https://user-images.githubusercontent.com/2448634/59100495-8256cd00-8926-11e9-8fd5-2186a5f7d4b2.png)
Better.

**Comment by protist** [comment]
That looks great; thank you!
