### ISSUE TITLE
[4.1.0]Cura wont start to print via usb

### ISSUE THREAD

**Issue by mechanicmem** [Ultimaker/Cura#5829]
Whenever I try to print via USB directly, the printing process won't start, I can control the printer on the Cura monitor, and the start movements (the g codes ones like bed leveling) are working fine, the temperature of the bed and the extruder are working fine too, but when everything is ready to print the printer just stops, if I save the gcode and print via Repetier the print works fine too, I just can't print directly via USB, anyone know how to fix this? 

**Application Version**
4.1.0

**Platform**
Windows 10

**Printer**
Prusa i3 Reprap

**Comment by Ghostkeeper** [comment]
Could you save the g-code to a file and post that here? I'm suspecting that something in the g-code is causing it to stop.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
