### ISSUE TITLE
[Feature Request] Printer name in Preview Mode

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#5830]
**Is your feature request related to a problem? Please describe.**

Printer name is not displayed in Preview Mode

**Describe the solution you'd like**

Please, display current printer name in Preview Mode

**Describe alternatives you've considered**

display current printer name in Preview Mode

**Affected users and/or printers**
 
**Additional context**

The printer name not being displayed in Preview Mode is somewhat confusing as the "Print with Octoprint" button also does not tell where it will send the file.

**Comment by Ghostkeeper** [comment]
Good point. Let's give this to our UX designer.

What do you think would be a good place to display it?

**Comment by yet-another-average-joe** [comment]
The layout could be like so, the printer combobox being on the left 

I just realize that the material also is not displayed in preview mode. There's probably room for it. 

![bandeau 1](https://user-images.githubusercontent.com/43514870/58811808-c5602a00-8620-11e9-9d13-a7458246beb6.PNG)

![bandeau 2](https://user-images.githubusercontent.com/43514870/58811826-cd1fce80-8620-11e9-939c-8352a7ce033d.PNG)

![bandeau 3](https://user-images.githubusercontent.com/43514870/58811842-d4df7300-8620-11e9-99c7-a4d3256bd717.PNG)

The combo could be beside the Cura logo in the tab ribbon. But it would not be very logical...

**Comment by GregValiant** [comment]
I'm cleaning house.
Using the "Sidebar GUI" plugin from the Marketplace rearranges the workspace so that the information you are asking for is displayed.
Can this be closed?
