### ISSUE TITLE
Material length cost

### ISSUE THREAD

**Issue by cesar77muse** [Ultimaker/Cura#5836]
The calculated material in meters is completely out of range, it says more than what it relly uses. like a small 20mm cube will use like 20cm of material and cura says 1.24m this causes problems in calculating material cost and amount for bigger prints

**Comment by nallath** [comment]
Please use the provided bug template. It's there for a reason. I'm not able to reproduce this, so there must be something you're doing differently.

**Comment by Ghostkeeper** [comment]
It's usually pretty spot on. The material usage in filament length is what Cura actually commands the feeder wheel to rotate.
