### ISSUE TITLE
Post Processing Plugin scripts support input type different from number like text, string?

### ISSUE THREAD

**Issue by danrain** [Ultimaker/Cura#584]
I found that Post Processing Plugin scripts only support input type boolean, number,float . I want to input text ,string but i cant find how to?

![screenshot from 2016-01-05 15 59 50](https://cloud.githubusercontent.com/assets/7451198/12111126/87d17d1e-b3c5-11e5-85bc-db9d6ed31f07.png)

**Comment by nallath** [comment]
Using "type": "string" should be possible. 

The mistake I see in your code is that there are two objects with the same name (eg; there are two "a":{} objects).

**Comment by danrain** [comment]
you can give me sample code run properly? that code i write for this asking. I did the right but i cant run.

**Comment by nallath** [comment]
It should use the same formating as the machine definition stuff found in machines/fdmprinter.json

**Comment by fieldOfView** [comment]
Strings may not currently work:
https://github.com/Ultimaker/Uranium/issues/76

**Comment by nallath** [comment]
Is that issue also in the Jira tracker?

**Comment by fieldOfView** [comment]
It is now (this was from before I had access to jira)

**Comment by danrain** [comment]
when have we fixed String issue? I need to write Custom Code Plugin Scripts that having regular expression from input box. Or i must write another private plugin ? Nallath

**Comment by nallath** [comment]
We haven't fixed the string issue, but it's logged in our own tracker, so it will be fixed at some point in time.
What is it that you want to do that requires a regex?

**Comment by danrain** [comment]
that is post processing plugin script which input a regular expression
string and replace that regex with the existing string inside gcode.

for example :







2016-01-07 16:12 GMT+07:00 Jaime van Kessel <notifications@github.com>:

**Comment by danrain** [comment]
![screenshot from 2016-01-07 16 57 31](https://cloud.githubusercontent.com/assets/7451198/12167674/3317bd1e-b560-11e5-9f78-eed163d18dd8.png)
