### ISSUE TITLE
Upgraded to Cura 4.1. Can see my models normally as before but after slicing, I am only to see them in preview as x-ray view (in blue). Casnnot see anything on the screen (no grid or frame either) under layer view.

### ISSUE THREAD

**Issue by hol-tech** [Ultimaker/Cura#5843]
**Application Version**

**Platform**

**Printer**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment]
This usually means that slicing failed somehow.

Could you share a project file with us? You can save the project file using File -> Save... and then upload it on the Github website in a comment.

**Comment by hol-tech** [comment]
![cura preview view xray](https://user-images.githubusercontent.com/51356180/58962761-6ea04f00-87de-11e9-85c9-f130517d5b16.jpg)
![cura preview view (empty)](https://user-images.githubusercontent.com/51356180/58962762-6ea04f00-87de-11e9-9e9f-4feea8ab7ca2.jpg)

The two screenshots show that in x-ray view the object can be seen but when going into layer view everything is just white. 
this happens with different models placed.

**Comment by hol-tech** [comment]
![cura preview -preview before slicing](https://user-images.githubusercontent.com/51356180/58962942-cfc82280-87de-11e9-9610-c90e18f98d30.jpg)

here is the model in 'prepare' mode before slicing. Once sliced and clicking onto the 'preview' button it disappears but can be seen in x-ray view.

**Comment by hol-tech** [comment]
all i can see in preview window are the sliders on the right and in the bottom.

**Comment by hol-tech** [comment]
from seeing the slicing happen (it took around 20 seconds) it looks to me that there is no problem with that but there is a display/ graphics issue at stake...

**Comment by Ghostkeeper** [comment]
Hmm, looks like a rendering error to me.

Perhaps you also have a log file for me? It should indicate if you don't have a supported OpenGL version.

You could try going into Preferences and enabling the compatibility mode for layer view. That creates a less nice looking layer view, but using a lower OpenGL version so it will be supported on more computers.

You could also try updating your graphics drivers.
