### ISSUE TITLE
[4.1 & 4.0] Does not support .3mf file type

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#5846]
**Application Version**
Both 4.0 and 4.1

**Platform**
Windows 10
Acer Predator Helios H300

**Actual Results**
Cura can export but will not open .3mf project file
.3mf is not in the list of supported file type.
![Screenshot (59)](https://user-images.githubusercontent.com/23495338/58867700-1f2a2800-86e5-11e9-850b-4e08e72590c5.png)

**Expected results**
Prompt asking to import models only or whole project

**Additional Information**
"Open 3MF files with Cura" was checked during install
![Screenshot (60)](https://user-images.githubusercontent.com/23495338/58867912-79c38400-86e5-11e9-9c70-2d289f789016.png)

**Comment by Ghostkeeper** [comment]
Could you supply a log file of Cura? See https://github.com/Ultimaker/Cura#logging-issues

I suspect that it'll say something about the 3MF reader plug-in not being able to load.

I'm unable to reproduce this myself. It could also be platform-dependent.

**Comment by Block137** [comment]
> I suspect that it'll say something about the 3MF reader plug-in not being able to load.

I checked Marketplace and re-enabled 3MF reader. Probably disabled by accident since its's on top of the list.
Its's working now
