### ISSUE TITLE
Cura 4.1.0. G-code z-hop errors

### ISSUE THREAD

**Issue by Penguin-fach** [Ultimaker/Cura#5847]
[CE3_FischerTechnik Solenoid - Bobbin - Rev D.zip](https://github.com/Ultimaker/Cura/files/3251451/CE3_FischerTechnik.Solenoid.-.Bobbin.-.Rev.D.zip)

Cura 4.1.0
Windows 7 Pro Service Pack 1 - 64-bit
Creality Ender 3 Pro - Standard firmware

Had the attached model printing OK with a brim but had issues with the nozzle clipping the model and have noticed that with the update to 4.1.0 the printer is sometimes pausing a little long between executions of individual G-code instructions which was allowing the nozzle to melt small divots into the surfaces.

Added some z-hops at retraction and while travelling. Z-hops are now glacial. A 1mm z-hop takes about 10 seconds at about 0.1mm per second. Result is unprintable.

Thought initially that I had a faulty SD card but I was able to flawlessly print an earlier version without retractions. Each time I slice this model with these settings i get the same result.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5753.
