### ISSUE TITLE
[4.1] Minimum Support Area: eating into small parts of model

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#5860]
**Application Version**
4.1

**Steps to Reproduce**
1.Set either "Minimum Support Interface Area" or Minimum "Support Area" to non-zero (larger than area of the part's slice)

**Actual Results**
Support interface (yellow) does not leave space for small feature of the model (red)
Certain areas ended up merged to support.
Can occur for multiple layers until the area is large enough.

See left side:
![Screenshot (62)](https://user-images.githubusercontent.com/23495338/59007558-20786380-8851-11e9-9b69-c2b9291f7349.png)

**Expected results**
Support leaves holes for the model to be

**Additional Information**
This is 3 extruder setup
Nozzle 1: 0.25mm (red) model walls
Nozzle 2: 0.4mm (yellow) support interface
Nozzle 3: 0.5mm (white) support infill

**Comment by Vandrasc** [comment]
Hi @Block137 , would it be possible for you to confirm the fix in the latest master build?

**Comment by Block137** [comment]
I don't have experience building Cura myself but I'll give this .3mf for you to test. Downward pointing horns are perfect for getting this bug.
Print settings are for testing only and are not practical at all.
[MinSupAreaTest.zip](https://github.com/Ultimaker/Cura/files/4072280/MinSupAreaTest.zip)

This file when sliced with 4.4.1
![Screenshot (196)](https://user-images.githubusercontent.com/23495338/72542472-cb0c3680-38b6-11ea-8a11-7be4c392abc9.png)

**Comment by Vandrasc** [comment]
Hi @Block137 , thank you for your prompt reply. I would have sent you the build but sharing the project file with us helped a lot in confirming the fix, so thanks!

Both the support and infill leave space for small and thin parts of the model, the printing time did increase a bit, as expected, but nothing dramatic (2 minutes for your model) and the material usage decreased of course. 

See screenshot 
![minimum](https://user-images.githubusercontent.com/26549794/72593678-e18dae80-3905-11ea-8411-0bc7f7363079.png)

Also many thanks to @smartavionics for making a PR for this and fixing this kind of issues.

The fix will be in the next release.
