### ISSUE TITLE
When the dimensions are scaled percentage of the wrong axis are updated

### ISSUE THREAD

**Issue by Eyos** [Ultimaker/Cura#5872]
When scaling an object, especially after it was rotated, the wrong percentage field is updated.
For example: you can set dimensions of the Y axis, but the percentage of the Z axis will get updated.
I think it happens if the object was rotated before, but not sure.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/4136.
