### ISSUE TITLE
Camera Stream not working after 4.1 upgrade

### ISSUE THREAD

**Issue by khmusicman** [Ultimaker/Cura#5873]
**Application Version**
4.1

**Platform**
windows 10

**Printer**
Creality Cr10s

**Actual Results**
Printer responds to Cura 4.1, but camera does not work

**Expected results**
camera should work. I can see the stream via web browser, and printoid app, but not cura

**Additional Information**

**Comment by WkRPcoN** [comment]
Experience same issue with Ender3 + Octoprint 1.13

**Comment by Ghostkeeper** [comment]
Please report this to the maintainer of the OctoPrint plug-in.

They currently have an issue open about this in their repository: https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/116
