### ISSUE TITLE
I want to request "only retract when crossing open space"

### ISSUE THREAD

**Issue by Silithas** [Ultimaker/Cura#5883]
Simplify 3d has an option where you can choose to only retract when moving from one print area to another when traveling over open space whether it be to another model on the same bed or say to a different part of the same model. 

I want to request such a feature. If it already exists, please name it.

**Comment by Block137** [comment]
This
![Screenshot (64)](https://user-images.githubusercontent.com/23495338/59244611-534e9d00-8c3f-11e9-8e52-bbe1a72355e1.png)

**Comment by smartavionics** [comment]
The closest that cura can provide is setting combing mode to all.

**Comment by Ghostkeeper** [comment]
There are probably some detailed differences between combing mode `All` and the way that Simplify3D implemented it, like support being a separate setting or whether or not it needs to retract when crossing draft shields and prime towers and whatnot. But the goal is to provide good print quality, not to be the same as Simplify3D. So I think then the current state of this feature is as Silithas requested it.
