### ISSUE TITLE
ooze shield's brim is merged with object's first layer

### ISSUE THREAD

**Issue by wuyuanyi135** [Ultimaker/Cura#5886]
**Application Version**
4.1.0 Appimage

**Platform**
Ubuntu 18.10

**Printer**
N/A

**Actual Results**
When ooze shield is on, the brim of it will be merged with the object's first layer and unable to remove
![Screenshot from 2019-06-12 00-54-49](https://user-images.githubusercontent.com/11760870/59324397-c2aea600-8cac-11e9-9fa9-51a83166dbff.png)

Left: Ideamaker Right: Cura
![image](https://user-images.githubusercontent.com/11760870/59324447-f7baf880-8cac-11e9-8c38-49c7e1cd4ecd.png)

**Expected results**
The brim should not be overlapping with the object

**Additional Information**
Project file
[CFFFP_cali_1-R.zip](https://github.com/Ultimaker/Cura/files/3279622/CFFFP_cali_1-R.zip)

**Comment by rburema** [comment]
Still happens in master. I'll discuss it with the rest of the devs.

**Comment by wuyuanyi135** [comment]
Thank you guys!

**Comment by Ghostkeeper** [comment]
Should work in 4.2.
