### ISSUE TITLE
More details when printing via USB

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#589]
The current USB printing dialog is very minimalistic.

Most 'makers' might probably not be interested in a lot of details, but what I would personally like to see is:
- [current line]/[total lines]
- [current pos]
- command being progressed, eg. "Moving to pos [x],[y],[z]", or "Waiting for nozzle to be heated"
- or a expandable text dialog, where the currently progressed line is marked bold

Btw, I also worry about this issue #402 .

**Comment by ianpaschal** [comment]
Seeing as this is inactive for more than an year I'm going to go ahead and close it.
