### ISSUE TITLE
code regresssion : Wrong temperature in Gcode with cura version 4.1.0

### ISSUE THREAD

**Issue by manuprendlair** [Ultimaker/Cura#5897]
Hello,

I got an incorrect temperature in Gcode.
I have 260° in my print setting but gcode temperature is 275 °:

![image](https://user-images.githubusercontent.com/10948827/59517143-2f9b8900-8ec3-11e9-8db5-3a2044b15c59.png)

![image](https://user-images.githubusercontent.com/10948827/59517196-4d68ee00-8ec3-11e9-8d08-5fc5afa5a522.png)

[adaptateur_helice.zip](https://github.com/Ultimaker/Cura/files/3291094/adaptateur_helice.zip)

It's look like to a code  regression.

Emmanuel FIANCETTE
From France

**Comment by smartavionics** [comment]
> It's look like to a code regression.

Or could the temperature substitutions in the start gcode have some error? e.g. wrong keyword used, wrong brackets, etc.?

**Comment by Ghostkeeper** [comment]
Could you submit a project file that has this problem? Under `File` -> `Save...`

I'm suspecting that it has something to do with the initial layer printing temperature. Cura doesn't just make up numbers by itself. Not usually, anyway.
