### ISSUE TITLE
[4.1.0] Fill gaps between walls does not do anything.

### ISSUE THREAD

**Issue by Beeblebrox666** [Ultimaker/Cura#5898]
**Application Version**

Cura 4.1.0
**Platform**

Windows 10
**Printer**

Ender 3 Pro
**Actual Results**

print creates two thin walls with tiny gap between them.
**Expected results**

I expected the walls to be solid. only the inside of the circle empty, do not want any infill.
**Additional Information**

see photo in zip file
[cura410.zip](https://github.com/Ultimaker/Cura/files/3291486/cura410.zip)

**Comment by smartavionics** [comment]
Hello @Beeblebrox666 , you need to provide the settings you used. Please save the project file (File -> Save) and zip and attach to this issue. Thanks.
