### ISSUE TITLE
Feature Request - Show filament usage by volume

### ISSUE THREAD

**Issue by czucker** [Ultimaker/Cura#59]
Would it be possible to add cm3 to the filament length and weight stats?

**Comment by awhiemstra** [comment]
We can probably add it, would you want that information in addition to the existing or instead of the exisitng information?

**Comment by Dim3nsioneer** [comment]
Would it be a possibility to make it flavor dependent? Flavors like the UMO would show mm and flavors like Ultigcode would show cm3...

**Comment by BagelOrb** [comment]
I think this is a UX issue. It's about passing information to the user, which is not particularly concerned with the Gcode flavor.

**Comment by czucker** [comment]
I would prefer that it be in addition to the existing information. So you would get grams, meters and cm3.

**Comment by BagelOrb** [comment]
Update: as it is now, the engine passes the information to the frontend in mm^3. The only thing left to do is to display it.

**Comment by Mitrasmit** [comment]
Is it just me or doesn't it show any information anymore, except the printing time? I really valued all stats; meters, grams, costs...Or is it hidden somewhere where I can't find it?

**Comment by nallath** [comment]
https://github.com/nallath/PrintCostCalculator <- It's a work in progress, but it could have all these features.

**Comment by nallath** [comment]
The PrintCostCalculator has this now.

**Comment by TMHogenhout** [comment]
https://github.com/Ultimaker/Cura/issues/194
