### ISSUE TITLE
[4.0/4.1] multiple, skirt issues

### ISSUE THREAD

**Issue by kornshadow097** [Ultimaker/Cura#5903]
**Application Version**

4.0 and 4.1
**Platform**

Windows 10
**Printer**

tevo Tarantula 0.6mm nozzle
**Steps to Reproduce**

enable skirts and print any number of them
**Actual Results**

it always puts 4minimum, even in the preview. *setting minimum length helped but lead to other issues. see comments section
**Expected results**

it should put 1, 2 or 3... not 4+
**Additional Information**

**Comment by smartavionics** [comment]
Hello @kornshadow097 , without the project file it's hard to be sure what the problem is but it's probably because the skirt/brim min length you are using is increasing the number of skirts.

![Screenshot_2019-06-16_10-19-45](https://user-images.githubusercontent.com/585618/59562102-6aff9a00-9020-11e9-8d90-a8f4ea2e7484.png)

**Comment by kornshadow097** [comment]
Thanks. you were right. odd that it only started doing that in version 4.0+ I had that item hidden. maybe the default hidden values changed and screwed up my older profiles...

**Comment by kornshadow097** [comment]
do you happen to know what items were changed from default after version 3.6.0? because ill have to go back and check every hidden setting and makes sure it wasnt automatically changed to something i DIDNT  want or setup. it might explain a few other features working strangely.

**Comment by smartavionics** [comment]
Sorry, no I don't know what has changed. The changes could be in the base settings which all profiles inherit from or they could be in the printer specific settings.

**Comment by kornshadow097** [comment]
so i just did a test print and it still acts weird. it used to automatically calculate what it would take to create a full circle of skirts i input that i wanted. I'd just leave the minimum off and it would not use that value which was default to 300mm which i guess is 4 skirts. 

Now it seems to go off the minimum, but it treats that minimum as an exact value. so if i put down 50mm it will print x skirts at an exact value of 50mm each. Even if 50mm isn't a full skirt, it will print whatever portion of the skirt is 50mm long and leave a gap after the last skirt.

instead of what its supposed to do which is use the minimum as a MINIMUM.  

Also, It no longer spaces the skirts apart, it lays them down next to each other like a brim which is fine but odd. Then it DOESN'T retract after the skirts are finished. It just move right into the project leaving a string of filament that leads into my project and connects it to the skirts...

**Comment by Ghostkeeper** [comment]
> Now it seems to go off the minimum, but it treats that minimum as an exact value. so if i put down 50mm it will print x skirts at an exact value of 50mm each. Even if 50mm isn't a full skirt, it will print whatever portion of the skirt is 50mm long and leave a gap after the last skirt.

I'm unable to reproduce your bug that it prints half skirts. It always closes the contour completely for me. In the code, this setting is only used in the part that generates a polygon for the skirt or brim, and this polygon must always be closed so I don't see how it could ever do that. It doesn't check whether the minimum length is exceeded line by line.

> Also, It no longer spaces the skirts apart, it lays them down next to each other like a brim which is fine but odd.

The skirt has never spaced individual lines apart, unless you set the initial layer flow to be very low and the line width high (then it'll space all lines apart on the first layer).

**Comment by Vandrasc** [comment]
Hi @kornshadow097, I am also not able to reproduce. It will help us a lot if you could share your project file with us.

Thank you!
