### ISSUE TITLE
New material diameter not effective until after restart

### ISSUE THREAD

**Issue by larsch** [Ultimaker/Cura#5906]
**Application version**: 4.0 + 4.1

**Platform**: Windows

**Printer**: CFDM

**Reproduction steps**: Create a custom material. Set diameter to 1.75 mm. Restart Cura. Duplicate previous material and change diameter of copy to something else, e.g. 1.9 mm. Select old material and slice. Select new material and slice.

**Actual results**: Both slicings result in same length of filament used (consistent with 1.75mm)

**Expected results**: The 1.9 mm material should use a shorter length of filament.

**Additional information**:

Original material:

![image](https://user-images.githubusercontent.com/15712/59628654-726a9480-9141-11e9-95f0-3e9c87b19a31.png)

Slice result:

![image](https://user-images.githubusercontent.com/15712/59628676-7c8c9300-9141-11e9-9c69-4895999cef4b.png)

Duplicated material & changed to 1.9mm:

![image](https://user-images.githubusercontent.com/15712/59628705-8c0bdc00-9141-11e9-937a-575583840cd5.png)

Slice result after selecting new material:

![image](https://user-images.githubusercontent.com/15712/59628733-a1810600-9141-11e9-8c51-bab459db3ad2.png)

Only after **restarting Cura** completely, it works as expected:

![image](https://user-images.githubusercontent.com/15712/59628837-cd03f080-9141-11e9-9db6-acd39de2e4d8.png)

**Comment by Ghostkeeper** [comment]
When trying to reproduce this bug, I found that it didn't update the diameter at all (under water). As in, it didn't affect the used filament length but also reset to the original diameter after restarting Cura. We may have a regression on top of this bug in 4.2 right now.

**Comment by LipuFei** [comment]
JIRA ticket: CURA-6590

**Comment by Ellecross** [comment]
Hey @larsch, FYI - the original issue you reported is now fixed in Cura master build. (yaay!) But we put the ticket back to do as there is still a remaining small issue to be resolved. So as what Ghostkeeper said, we expect this fix to be officially in 4.2. :D

**Comment by bullestock** [comment]
I can confirm that this bug is still present in Cura 4.5.0.

**Comment by fieldOfView** [comment]
I ran into this issue with the Material Settings plugin, and the next version of that plugin will contain a fix for this issue. I will see if I can backport (forwardport?) this fix to upstream.
