### ISSUE TITLE
[2.1] G-Code filename not set when opening cura with a file

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#591]
As I own a bq Hephestos 2 the filename for my printer is called BH2_[filename of model]. So when opening a file on Cura it works very well, but when I use a filemanager and open stl file, for example, with Cura, it loads the model, slices it, but doesn't set the filename. So the resulting name is "BH2_".

**Comment by Ghostkeeper** [comment]
You're right. I haven't got Cura installed since I always work from source, but I was able to reproduce this issue by calling from the command line on Ubuntu:

    python3 cura_app.py <model file>

The file is loaded but no name is given other than "UM2_".

**Comment by thopiekar** [comment]
Can confirm it works now on Linux :+1:

**Comment by Ghostkeeper** [comment]
Nice, thanks!
