### ISSUE TITLE
cura 4.1 Preview(Layer view) Skirt Line error

### ISSUE THREAD

**Issue by leey99** [Ultimaker/Cura#5917]
**Application version**

4.1

**Platform**

Windows 10 64bit

**Printer**

Creality CR-10 S4

**Reproduction steps**

View: Preview(Layer view)
Build Plate Adhesion Type: Skirt
Skirt Line Count: 4
Skirt Distance: 5mm
Skirt Minimum Length: 250mm

**Actual results**

Skirt Line in Print result

**Expected results**

Cura 3.6 is output normally.

**Additional information**

![cura 4 1](https://user-images.githubusercontent.com/22333869/59844816-bf937400-9396-11e9-9e9b-f2d744703cc0.png)
![cura 3 6](https://user-images.githubusercontent.com/22333869/59844822-c1f5ce00-9396-11e9-8055-af6ed792c7c3.png)

**Comment by diegopradogesto** [comment]
Can you please share the project file? (`File`->`Save...`)

**Comment by smartavionics** [comment]
That just looks like some of the models are not flat on the buildplate.

**Comment by leey99** [comment]
> Can you please share the project file? (`File`->`Save...`)

I uploaded the project file.
Please analyze it.

[Dental Demonstration Mandibule.zip](https://github.com/Ultimaker/Cura/files/3320296/Dental.Demonstration.Mandibule.zip)

**Comment by smartavionics** [comment]
Hello @leey99 , as far as I can tell, it looks fine. You could increase the skirt distance to space it further from the first layer outlines like I show here.

![Screenshot_2019-06-24_11-20-30](https://user-images.githubusercontent.com/585618/60011669-37e98600-9672-11e9-826c-9c12134d8b0a.png)

BTW @diegopradogesto , when I sliced this, the UI came over all weird using 100% CPU on all the cores and the object list was animating! sort of scrolling up and down. This was without me moving the mouse or selecting anything. Never seen that before. Have a play with this project and see if it does the same for you!

**Comment by Ghostkeeper** [comment]
> BTW @diegopradogesto , when I sliced this, the UI came over all weird using 100% CPU on all the cores and the object list was animating! sort of scrolling up and down. This was without me moving the mouse or selecting anything. Never seen that before. Have a play with this project and see if it does the same for you!

Not seeing this happen. The model takes a while to load and this uses 1 core on 100% for about 5 seconds, but that's not out of the ordinary for loading a 300MB XML file. The object list only contains one object in the end and was not animating.

**Comment by smartavionics** [comment]
If I remember right, after loading the model, I clicked on some of the teeth to check their z heights and it was after doing that things went weird.

**Comment by Ghostkeeper** [comment]
The reason why the skirt looks so weird is because the models touch the build plate only in a very small spot in their centres. This makes the skirt go underneath the model, which makes it look like it's too small. But it's not. Here is what the first layer looks like:

![Screenshot from 2019-06-26 09-00-26](https://user-images.githubusercontent.com/2448634/60158175-e3b8e000-97f0-11e9-8cb9-69b254813881.png)

The skirt goes around the first layer, not around all of the layers. That would not be useful. So this is working as intended as far as I can see.

**Comment by smartavionics** [comment]
I also think that when it was being weird, the layer view was displayed not the prepare view.

**Comment by leey99** [comment]
Thanks to you, I understand.
@smartavionics Thank You.
@Ghostkeeper Thank You.
