### ISSUE TITLE
Initial Layer Flow affects whole print

### ISSUE THREAD

**Issue by john2288** [Ultimaker/Cura#5925]
**Application version**
4.1.0

**Platform**
Windows 10 home

**Reproduction steps**
slice a print at 100% initial layer flow and 100% flow
Slice a print at 120% initial layer flow and 100% flow
compare gcode

**Actual results**
the 120% initial layer flow file also increases the other layers by 120%

**Expected results**
only first layer should print at 120%

**Additional information**
my printer likes a higher initial flow for adhesion, however it casues the other layers to squish by not returning to the flow setting.
100% initial layer
![flow 100 2](https://user-images.githubusercontent.com/2762729/59936133-4854f300-941d-11e9-873f-7320ae77c4b1.png)

120% initial layer
![flow120 2](https://user-images.githubusercontent.com/2762729/59936174-63276780-941d-11e9-9f9d-0739a93f6587.png)

As seen above the initial layer does the some moves but the extrusion is increased as expected by 120%

100% other layer flow
![flow100](https://user-images.githubusercontent.com/2762729/59936229-7e927280-941d-11e9-936b-3187e5fb60f4.png)

120% other layer flow
![flow 120](https://user-images.githubusercontent.com/2762729/59936255-8ce08e80-941d-11e9-90fa-8ba2bee51a04.png)

As seen above for example on line 6247, the move itself is the same however the extrusion values are not the same and the extrusion is increased by 120% on the second image

**Comment by smartavionics** [comment]
Hello @john2288, please save the project file (File -> Save) and either rename to .zip or zip it and attach to this issue.  Without that it's not possible to investigate. Thanks.

**Comment by john2288** [comment]
Sorry about that. i saved it but forgot to attach it.
[a flow test.3mf.zip](https://github.com/Ultimaker/Cura/files/3315650/a.flow.test.3mf.zip)

**Comment by smartavionics** [comment]
Thanks for the file. I think Cura's OK and you are getting misled by the fact that the first layer is lower than the others. That means that the extrusion rate for the first layer is proportionally lower. So if I set the first layer height to be 0.4 (same as the others) the extrusion rate used for the wall lines is 0.08 mm/mm and for subsequent layers it's 0.067 which is a ratio of 1.19 (or thereabouts). Hope this helps.

**Comment by john2288** [comment]
thanks for your reply.
I understand what you were saying but still wasn't getting it. however as i was trying to put together an image to maybe explain better i realized how what you said makes sense and completely forgot about the fact that the e value is absolute not relative and constantly goes up so the initial 120% will make the other values inflated.
My apologies for the trouble.
