### ISSUE TITLE
[4.1] Wrong PREVIEW

### ISSUE THREAD

**Issue by leonirz** [Ultimaker/Cura#5927]
**Application version**

4.1

**Platform**

WINDOWS 10

**Printer**

Creality cr-10

**Reproduction steps**

1) Open STL
2) Slice
3) PREPARE mode is all right.
4) Preview mode (where presents much errors in view)

**Actual results**

In PREVIEW mode, areas that should be open (recessed) are closed (filled) as a single plane. If you compare the PREPARE mode with the PREVIEW mode, you may notice the error. So as you navigate through the layers, the first layers are mostly with many errors, because areas that should appear open (cropped) are filled.

**Expected results**

View of piece right as PREPARE mode.

**Additional information**

![cura-pre-slice-normal-design](https://user-images.githubusercontent.com/52092300/59963957-9971ef00-94d0-11e9-87dc-cfe9891cee9e.PNG)
![cura-pos-slice-normal-design](https://user-images.githubusercontent.com/52092300/59963959-a0006680-94d0-11e9-8e00-25fc3e3b1876.PNG)
![cura-preview-mode-wrong-design](https://user-images.githubusercontent.com/52092300/59963960-a68ede00-94d0-11e9-8d47-b4a02c1f4679.PNG)
![cura-preview-mode-wrong-design--first-layer-wrong-wronng-wrong](https://user-images.githubusercontent.com/52092300/59963963-ab539200-94d0-11e9-888b-34b12e25943c.PNG)
[LOG cura.zip](https://github.com/Ultimaker/Cura/files/3316822/LOG.cura.zip)
[CCR10_CAIXA-FRENTE-V4.zip](https://github.com/Ultimaker/Cura/files/3316823/CCR10_CAIXA-FRENTE-V4.zip)

**Comment by smartavionics** [comment]
Hello @leonirz , your model has problems as detected by the mesh tools and the x-ray view...

![Screenshot_2019-06-22_14-39-24](https://user-images.githubusercontent.com/585618/59964689-d0112f00-94fb-11e9-9fd1-4fbdd6df0484.png)

![Screenshot_2019-06-22_14-40-41](https://user-images.githubusercontent.com/585618/59964692-d43d4c80-94fb-11e9-82c7-068635ba9472.png)

Red regions have problems.

**Comment by leonirz** [comment]
I have no idea what these red notes mean. Nothing appears in the design program. I imagine it will be necessary to draw everything again from zero. :(

**Comment by leonirz** [comment]
My CURA program does not have this MESH tool.

**Comment by smartavionics** [comment]
> My CURA program does not have this MESH tool.

It's a plugin you install from the Cura marketplace...

![Screenshot_2019-06-22_20-48-10](https://user-images.githubusercontent.com/585618/59968283-12a02f00-952f-11e9-9a84-528181e5f566.png)

**Comment by diegopradogesto** [comment]
The problem is related with the model. Please fix the model and see if the problem stays.

It's a good idea to install the MeshTool plugin for that purpose, as @smartavionics suggested.
