### ISSUE TITLE
[4.1.0] Monitor tab screen does not display properly

### ISSUE THREAD

**Issue by Beeblebrox666** [Ultimaker/Cura#5941]
**Application version**

4.1.0
**Platform**

Windows 10 home v. 1809, Intel(R) HD Graphics 4000, v. 10.18.10.4358
**Printer**

Ender 3-Pro
[Roller_insert_485.zip](https://github.com/Ultimaker/Cura/files/3330193/Roller_insert_485.zip)
![curascreenshot](https://user-images.githubusercontent.com/29876058/60183557-8888ec80-97f4-11e9-9902-4b0493c7be6b.jpg)

**Reproduction steps**

After slicing selected print directly to usb device (My Ender 3 Pro)
I do not believe that the file being processed to print has anything to do with this, it is a display formatting issue with the application. all the monitor information is crammed into the right third of the screen  and the bottom is cut off.
**Actual results**

always happens, does not scroll like the settings list on the prepare tab
**Expected results**

all available information should be visible. 2/3 of the screen is not being used. poor layout of the app.
**Additional information**

**Comment by Ghostkeeper** [comment]
Yeah, this is the result of legacy. We didn't spend time to redesign the GUI for USB printing when we removed the sidebar, so we put it in a sidebar there.
