### ISSUE TITLE
Cura Ultimaker 4.1.0 Toolbox icon missing 

### ISSUE THREAD

**Issue by mobleydmz** [Ultimaker/Cura#5945]
**Application version**

**Platform**
 

**Printer**

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by fieldOfView** [comment]
Toolbox has been renamed to Marketplace.

**Comment by Ghostkeeper** [comment]
There was never an icon for the toolbox (as far as I know) but there is a button for the Marketplace now in the top-right hand side of the screen.
