### ISSUE TITLE
Проблемы при переходе на русский язык (пробелы между всеми символами)

### ISSUE THREAD

**Issue by SmolyaninovAA** [Ultimaker/Cura#5950]
![Снимок экрана от 2019-06-30 10-23-19](https://user-images.githubusercontent.com/23167483/60393653-6d361e00-9b21-11e9-9ec9-3bae2394637d.png)

Работать так конечно можно, но через пару минут идет кровь из глаз. Кто может помочь, как сделать нормальное представление? На английском языке все хорошо

**Comment by Ghostkeeper** [comment]
أنا حقا لا أعرف الروسية جيدا بما فيه الكفاية لمساعدتك. هل يمكنك إعادة صياغة تذكرتك باللغة الإنجليزية في المرة القادمة؟

**Comment by Ghostkeeper** [comment]
Purely looking at the screenshot, I suppose this is a duplicate of https://github.com/Ultimaker/Cura/issues/3880: Russian font has too much spacing in Linux.
