### ISSUE TITLE
Start Z up, stop repeatedly during printing

### ISSUE THREAD

**Issue by wdpa23a8101** [Ultimaker/Cura#5951]
Great programmer, hello!
         Please help me solve my bug.

**Application version**
4.1

**Platform**
w10 X64

**Printer**
CR-10S PRO

**Reproduction steps**
Enable Z hop when retracted

**Actual results**
No matter what STL is printed, it is normal to print the outer wall. However, when the print is infill (internal) or supported, the nozzle will stop somewhere for about 1 minute and then continue to work. The whole process is stopped and stopped.

**Expected results**
I want to be able to print the model normally using Z elevation.

**Additional information**
Sorry, I don't know where CURA exports log files.

**Comment by smartavionics** [comment]
Duplicate of #5753.

**Comment by wdpa23a8101** [comment]
> 重复[＃5753](https://github.com/Ultimaker/Cura/issues/5753)。
Thank you, let me try
