### ISSUE TITLE
Only 1 extruder is displayed although the printer has 2

### ISSUE THREAD

**Issue by Pepitapolka** [Ultimaker/Cura#5954]
My printer has 2 extruders and I want to use both but only one extruder will show up in the program so I can not use both.

**Comment by Vandrasc** [comment]
Hi @Pepitapolka , could you please fill in the bug template? This will help us to understand what the issue could be, we need to know the type of printer you are using. 

1. Did you check the machine settings window? 
![1](https://user-images.githubusercontent.com/26549794/60422685-ce76f380-9bec-11e9-8737-c678345c9922.png)
![Screenshot 2019-07-01 at 10 40 30](https://user-images.githubusercontent.com/26549794/60422703-d6369800-9bec-11e9-8cf0-de9e43f27d4b.png)
Here you can select the extruder numbers you desire. 

2. Is one of the extruders disabled? You can verify that by checking the extruder checkbox.
![Screenshot 2019-07-01 at 10 43 07](https://user-images.githubusercontent.com/26549794/60422797-0e3ddb00-9bed-11e9-8182-f44367e96a3f.png)

If all the above are correctly set, then we will also need your user configuration folder, besides the filled in template, this will hopefully help us to reproduce your issue. 
You can copy the cura user folder from Help > Show configuration folder

Thank you!
