### ISSUE TITLE
CURA v4.1.0 Fullscreen View toggle 

### ISSUE THREAD

**Issue by Twopusses** [Ultimaker/Cura#5956]
**Application version**
CURA 4.1.0

**Platform**
Windows 10/AMD Radeon 7970m

**Printer**
CTC i3

**Reproduction steps**
I accidentally hit F11 

**Actual results**
 F11 apparently toggles FULL SCREEN VIEW but that left me with 'disabled' menu headers so I couldn't see how to UNDO this. 

**Expected results**
Since I accidentally came across the feature, I can only say that F11 did what it was intended to do BUT I'd have expected it to be printed somewhere in the screen HOW TO REVERSE F11 Change to Full Screen View otherwise you're left hanging like a plum : ) I had to close my program to get out of this and to my way of thinking that's either a BUG or 'bad' programming, but I just want to quickly say, I LOVE Cura. As a piece of software it's brilliant., and yes, this is my first ever Bug Report.

**Additional information**
 I don't know what LOG FILES are in this context or how to obtain them. If you send details to me I'm sure I can locate what you need.

**Comment by mbartlett21** [comment]
@Twopusses 
You can hit F11 again to get out of that mode :)

**Comment by Ghostkeeper** [comment]
I don't think we should print somewhere in the screen how to get out of F11. That would not look good for the 99% of users that do know how they got in F11. The application menu should show fine though. Here's how it looks on my computer:

![Screenshot from 2019-07-02 10-21-17](https://user-images.githubusercontent.com/2448634/60496554-56bfcc00-9cb3-11e9-916d-80f609595d16.png)

The application menu is there at the top. Is it not for you? This could be platform-dependent.

**Comment by mbartlett21** [comment]
@Ghostkeeper I am on Windows 10 1903 and I see the bar at the top, but no menus open up when I click on them.

**Comment by diegopradogesto** [comment]
We tested on Windows and it works. When pressing F11 (or View > Toggle Full Screen) it goes to full screen mode and the menu shows up on top. However it seems that it's not working correctly. 

First thing I noticed is that it's laggy and sometimes the submenu doesn't appear, making this functionality a bit unusable. However there is the workaround of pressing F11 again and then the menus work correctly again.

**Comment by Twopusses** [comment]
My Thanks to everyone who's pointed out that pressing F11 again will undo the action, but it remains true that if you don't know how you got into Full Screen Mode, having to systematically press "every key/combination on your keyboard" trying to find out which one might achieve that, and in so doing you may crash your machine, close CURA or lose your file etc. this isn't a good 'resolution'. It is "a Bug" albeit one of a hidden knowledge issue than strictly a coding flaw although it seems others have spotted other issues associated with this functionality. I agree that printing "F11 for Original Screen Mode" would be clumsy/untidy. Thanks again for your help & attention with my first Github Bug Report.

**Comment by mbartlett21** [comment]
Maybe a popup could be added that fades away after a few seconds (like fullscreen on chrome)

**Comment by Ghostkeeper** [comment]
Oops. I didn't mean to close this via the commit. Sorry.

We've discussed this with the team, and agreed that adding Escape as hotkey to exit full screen should make it easier to discover.

The issue with the application menus not working while in full screen mode is still open, but we haven't been able to reproduce that problem. The menus are working fine here, except that the Settings menu is a bit slow (because it needs to build that model upon opening it, which takes a second).

**Comment by rburema** [comment]
While some of us can reproduce the problem now (but others on the same OS are fine), we've decided to defer the rest of this issue, sorry.
