### ISSUE TITLE
v4.1.0 Scal value change issue

### ISSUE THREAD

**Issue by loloz3** [Ultimaker/Cura#5965]
If we rotate 90° a model and then wants to change the z % scal value...  y % is modified !

is it normal ?

**Comment by rburema** [comment]
There are some known issues with rotation and scaling, see (for example) #4136 

There a comment reads:
> We decided to wait with this until we can transition to transformations via the Trimesh library. Trimesh should simplify this sort of thing for us.

We're still going to do that, it's just taking longer than expected because of other responsibilities.
