### ISSUE TITLE
Backup Errors

### ISSUE THREAD

**Issue by HACKER-3000** [Ultimaker/Cura#5968]
**Application version**

**Platform**

Windows 10

**Printer**

Ender 3

**Reproduction steps**

Do a Backup and try to restore it!

**Actual results**

Config Corrupted, and parts not even there!

**Expected results**

Fine restore of Backup.

**Additional information**

A screenshot of the disaster:
![grafik](https://user-images.githubusercontent.com/29732082/60602385-f5335680-9db3-11e9-9fe1-f5f8c854988d.png)

Also, is there a way to get the backup ZIPs directly?

**Comment by nallath** [comment]
Is this the case with all backups? Was this already the case when the backup was done? Could you share your configuration folder and logs?

**Comment by HACKER-3000** [comment]
yep it is with all and allready happend once a few months ago... Also i tried to restore it(This backup from 03.07.19) just a few hours after createing it because i screwd the configuradion of visible settings...

Heres my cura folder: http://hacker3000-data.bplaced.net/cura.zip

**Comment by Ghostkeeper** [comment]
Hmm, that Cura folder is not downloading for me.

As a workaround, you can try restoring just the preferences file (`cura.cfg`) from the zip. That preferences file contains the list of visible settings.

I just tried the back-up system and I'm not getting any problems with restoring it. No configuration errors.

**Comment by HACKER-3000** [comment]
its just SLOW AF

**Comment by HACKER-3000** [comment]
new link: https://hacker3000.goip.de/cura.zip

**Comment by Ghostkeeper** [comment]
Hmm, well I see one thing wrong with Cura here. Loading up that folder causes me to log in successfully under your name. Since the cura.cfg file contains a log-in token I can access your account from here. You'd best take that zip file down if you can (I've got a copy, but I promise I won't do anything weird).

We should probably store that log-in token somewhere else, or encrypt it with an xor of your CPU ID or something so that it can't be shared...

**Comment by Ghostkeeper** [comment]
It's not the back-up plug-in. Your original configuration folder has the same error. The file is missing that contains the changes that were not saved to a profile.

I don't know how your configuration folder got into that state. I'm unable to reproduce that except by copying your configuration folder in. Perhaps your configuration got into that state via faulty back-ups at some point? It's hard to tell, now.

**Comment by HACKER-3000** [comment]
@Ghostkeeper I allready expected sth like this with the Login...
Btw the idea with the cpu id xor isnt that bad!

**Comment by HACKER-3000** [comment]
and ive removed the file and replaced it with a html saying that is was removed
