### ISSUE TITLE
[2.1] Linux: combobox outside of the screen

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#597]
As you can see when expanding the combobox the list is shown out of the screen. The current workaround is to make the Cura window smaller and choose the location for saving the gcode.
Sometimes, when clicking on the "expand-button", the buildplate gets black and when moving the cursor a but it is getting back.

![cura-combobox](https://cloud.githubusercontent.com/assets/1847437/12372553/09641572-bc5d-11e5-9cfd-ae9070ba3378.png)

**Comment by Ghostkeeper** [comment]
Related to #494.
