### ISSUE TITLE
workspace vanished

### ISSUE THREAD

**Issue by blindwolfcosplay** [Ultimaker/Cura#5972]
ive encountered an issue that is recurring more and more recently. I open up cura 4.0.0 and the workspace just vanishes, I can load in an object and can even slice it. I just cant see it I have a blank space where the workspace should be. 

![Untitled](https://user-images.githubusercontent.com/52515169/60633408-79142f80-9e02-11e9-9e23-f86396a3184a.jpg)

**Comment by mbartlett21** [comment]
@blindwolfcosplay 
Can you try clicking on one of the view buttons in the bottom left?

**Comment by blindwolfcosplay** [comment]
I can click on them. as well as clicking the same things up in the view menu on the top bar. It doesn't do anything,  or doesn't seem to as nothing changes in the viewport
