### ISSUE TITLE
Preview colour bugs

### ISSUE THREAD

**Issue by mbartlett21** [Ultimaker/Cura#5977]
**Application version**
Cura 4.1.0

**Platform**
Windows 10 1903

**Reproduction steps**
1. Load GCode below
2. Change preview mode to feedrate

**Actual results**
Lines after retractions fade from the retraction speed to their actual speed

**Expected results**
Lines after retractions show as their actual speed

**Additional information**
Screenshot:
![image](https://user-images.githubusercontent.com/29034492/60696079-870fa080-9f27-11e9-8c2b-788f0353a6cd.png)

<details>
<summary>
Example GCode (made with my own script on <a href="https://cad.onshape.com/documents/2e6cdddbacf401fc60fd2b91">Onshape</a>)
</summary>
<pre>;Start GCode
;Generated with Layers 2 gcode (https://cad.onshape.com/documents/2e6cdddbacf401fc60fd2b91)
;filamentDiameter 1.75
;lineWidth 0.4
;lineHeight 0.3
;filamentMMPer3dMM 0.0499
;minPathWithoutRetract 1.2
M140 S60  ;Heat bed to 60
M105      ;Report temperatures
M190 S60  ;Wait for bed temperature to reach 60
M104 S200 ;Heat hotend to 200
M105      ;Report temperature
M109 S200 ;Wait for hotend to heat
M82       ;Absolute extrusion mode
G28       ;Home
G1 Z15.0 F6000 ;Move the head down to 15mm above buildplate
;Prime the extruder
G92 E0    ;Reset the extruder value
G1 F200 E3 ;Extrude 3mm of filament
G92 E0
G92 E0
G92 E0
G1 F2100 E-7.5 ;Retract filament 7.5mm
M107 ;Fan off
G0 F3600 X-2.8685 Y-21.7882 Z0.3
G0 F2100 E0
G1 F700 X2.8685 Y-21.7882 E0.28622
G1 X8.4099 Y-20.3034 E0.57244
G1 X13.3783 Y-17.4349 E0.85865
G1 X17.4349 Y-13.3783 E1.14487
G1 X20.3034 Y-8.4099 E1.43109
G1 X21.7882 Y-2.8685 E1.71731
G1 X21.7882 Y2.8685 E2.00352
G1 X20.3034 Y8.4099 E2.28974
G1 X17.4349 Y13.3783 E2.57596
G1 X13.3783 Y17.4349 E2.86218
G1 X8.4099 Y20.3034 E3.14839
G1 X2.8685 Y21.7882 E3.43461
G1 X-2.8685 Y21.7882 E3.72083
G1 X-8.4099 Y20.3034 E4.00705
G1 X-13.3783 Y17.4349 E4.29326
G1 X-17.4349 Y13.3783 E4.57948
G1 X-20.3034 Y8.4099 E4.8657
G1 X-21.7882 Y2.8685 E5.15192
G1 X-21.7882 Y-2.8685 E5.43813
G1 X-20.3034 Y-8.4099 E5.72435
G1 X-17.4349 Y-13.3783 E6.01057
G1 X-13.3783 Y-17.4349 E6.29679
G1 X-8.4099 Y-20.3034 E6.583
G1 X-2.8685 Y-21.7882 E6.86922
G1 F2100 E-0.63078
G0 F3600 X-4.8 Y-4.8
G1 F2100 E6.86922
G1 F700 X4.8 Y-4.8 E7.34817
G1 X4.8 Y4.8 E7.82711
G1 X-4.8 Y4.8 E8.30606
G1 X-4.8 Y-4.8 E8.785
G0 F3600 X-4.4 Y-4.4
G1 F700 X4.4 Y-4.4 E9.22404
G1 X4.4 Y4.4 E9.66307
G1 X-4.4 Y4.4 E10.10211
G1 X-4.4 Y-4.4 E10.54114
G0 F3600 X-4 Y-4.2
G1 F700 X-4 Y4.2 E10.96022
G0 F3600 X-3.6 Y4.2
G1 F700 X-3.6 Y-4.2 E11.37929
G0 F3600 X-3.2 Y-4.2
G1 F700 X-3.2 Y4.2 E11.79837
G0 F3600 X-2.8 Y4.2
G1 F700 X-2.8 Y-4.2 E12.21745
G0 F3600 X-2.4 Y-4.2
G1 F700 X-2.4 Y4.2 E12.63653
G0 F3600 X-2 Y4.2
G1 F700 X-2 Y-4.2 E13.05561
G0 F3600 X-1.6 Y-4.2
G1 F700 X-1.6 Y4.2 E13.47468
G0 F3600 X-1.2 Y4.2
G1 F700 X-1.2 Y-4.2 E13.89376
G0 F3600 X-0.8 Y-4.2
G1 F700 X-0.8 Y4.2 E14.31284
G0 F3600 X-0.4 Y4.2
G1 F700 X-0.4 Y-4.2 E14.73192
G0 F3600 X0 Y-4.2
G1 F700 X0 Y4.2 E15.15099
G0 F3600 X0.4 Y4.2
G1 F700 X0.4 Y-4.2 E15.57007
G0 F3600 X0.8 Y-4.2
G1 F700 X0.8 Y4.2 E15.98915
G0 F3600 X1.2 Y4.2
G1 F700 X1.2 Y-4.2 E16.40823
G0 F3600 X1.6 Y-4.2
G1 F700 X1.6 Y4.2 E16.8273
G0 F3600 X2 Y4.2
G1 F700 X2 Y-4.2 E17.24638
G0 F3600 X2.4 Y-4.2
G1 F700 X2.4 Y4.2 E17.66546
G0 F3600 X2.8 Y4.2
G1 F700 X2.8 Y-4.2 E18.08454
G0 F3600 X3.2 Y-4.2
G1 F700 X3.2 Y4.2 E18.50362
G0 F3600 X3.6 Y4.2
G1 F700 X3.6 Y-4.2 E18.92269
G0 F3600 X4 Y-4.2
G1 F700 X4 Y4.2 E19.34177
G0 F7200 X4.4 Y4.4 Z0.6
G1 F1050 X4.4 Y-4.4 E19.7808
G1 X-4.4 Y-4.4 E20.21984
G1 X-4.4 Y4.4 E20.65887
G1 X4.4 Y4.4 E21.09791
G0 F7200 X4.2 Y4
G1 F1050 X-4.2 Y4 E21.51698
G0 F7200 X-4.2 Y3.6
G1 F1050 X4.2 Y3.6 E21.93606
G0 F7200 X4.2 Y3.2
G1 F1050 X-4.2 Y3.2 E22.35514
G0 F7200 X-4.2 Y2.8
G1 F1050 X4.2 Y2.8 E22.77422
G0 F7200 X4.2 Y2.4
G1 F1050 X-4.2 Y2.4 E23.19329
G0 F7200 X-4.2 Y2
G1 F1050 X4.2 Y2 E23.61237
G0 F7200 X4.2 Y1.6
G1 F1050 X-4.2 Y1.6 E24.03145
G0 F7200 X-4.2 Y1.2
G1 F1050 X4.2 Y1.2 E24.45053
G0 F7200 X4.2 Y0.8
G1 F1050 X-4.2 Y0.8 E24.86961
G0 F7200 X-4.2 Y0.4
G1 F1050 X4.2 Y0.4 E25.28868
G0 F7200 X4.2 Y0
G1 F1050 X-4.2 Y0 E25.70776
G0 F7200 X-4.2 Y-0.4
G1 F1050 X4.2 Y-0.4 E26.12684
G0 F7200 X4.2 Y-0.8
G1 F1050 X-4.2 Y-0.8 E26.54592
G0 F7200 X-4.2 Y-1.2
G1 F1050 X4.2 Y-1.2 E26.96499
G0 F7200 X4.2 Y-1.6
G1 F1050 X-4.2 Y-1.6 E27.38407
G0 F7200 X-4.2 Y-2
G1 F1050 X4.2 Y-2 E27.80315
G0 F7200 X4.2 Y-2.4
G1 F1050 X-4.2 Y-2.4 E28.22223
G0 F7200 X-4.2 Y-2.8
G1 F1050 X4.2 Y-2.8 E28.6413
G0 F7200 X4.2 Y-3.2
G1 F1050 X-4.2 Y-3.2 E29.06038
G0 F7200 X-4.2 Y-3.6
G1 F1050 X4.2 Y-3.6 E29.47946
G0 F7200 X4.2 Y-4
G1 F1050 X-4.2 Y-4 E29.89854
G0 F7200 X-4.8 Y-4.8
G1 F1050 X-4.8 Y4.8 E30.37748
G1 X4.8 Y4.8 E30.85643
G1 X4.8 Y-4.8 E31.33538
G1 X-4.8 Y-4.8 E31.81432
G0 F7200 X-4.4 Y-4.4 Z0.9
G1 F1050 X4.4 Y-4.4 E32.25336
G1 X4.4 Y4.4 E32.69239
G1 X-4.4 Y4.4 E33.13142
G1 X-4.4 Y-4.4 E33.57046
G0 F7200 X-4 Y-4.2
G1 F1050 X-4 Y4.2 E33.98953
G0 F7200 X-3.6 Y4.2
G1 F1050 X-3.6 Y-4.2 E34.40861
G0 F7200 X-3.2 Y-4.2
G1 F1050 X-3.2 Y4.2 E34.82769
G0 F7200 X-2.8 Y4.2
G1 F1050 X-2.8 Y-4.2 E35.24677
G0 F7200 X-2.4 Y-4.2
G1 F1050 X-2.4 Y4.2 E35.66585
G0 F7200 X-2 Y4.2
G1 F1050 X-2 Y-4.2 E36.08492
G0 F7200 X-1.6 Y-4.2
G1 F1050 X-1.6 Y4.2 E36.504
G0 F7200 X-1.2 Y4.2
G1 F1050 X-1.2 Y-4.2 E36.92308
G0 F7200 X-0.8 Y-4.2
G1 F1050 X-0.8 Y4.2 E37.34216
G0 F7200 X-0.4 Y4.2
G1 F1050 X-0.4 Y-4.2 E37.76123
G0 F7200 X0 Y-4.2
G1 F1050 X0 Y4.2 E38.18031
G0 F7200 X0.4 Y4.2
G1 F1050 X0.4 Y-4.2 E38.59939
G0 F7200 X0.8 Y-4.2
G1 F1050 X0.8 Y4.2 E39.01847
G0 F7200 X1.2 Y4.2
G1 F1050 X1.2 Y-4.2 E39.43754
G0 F7200 X1.6 Y-4.2
G1 F1050 X1.6 Y4.2 E39.85662
G0 F7200 X2 Y4.2
G1 F1050 X2 Y-4.2 E40.2757
G0 F7200 X2.4 Y-4.2
G1 F1050 X2.4 Y4.2 E40.69478
G0 F7200 X2.8 Y4.2
G1 F1050 X2.8 Y-4.2 E41.11386
G0 F7200 X3.2 Y-4.2
G1 F1050 X3.2 Y4.2 E41.53293
G0 F7200 X3.6 Y4.2
G1 F1050 X3.6 Y-4.2 E41.95201
G0 F7200 X4 Y-4.2
G1 F1050 X4 Y4.2 E42.37109
G0 F7200 X4.8 Y4.8
G1 F1050 X-4.8 Y4.8 E42.85003
G1 X-4.8 Y-4.8 E43.32898
G1 X4.8 Y-4.8 E43.80793
G1 X4.8 Y4.8 E44.28687
G0 F7200 X4.4 Y4.4 Z1.2
G1 F1050 X4.4 Y-4.4 E44.72591
G1 X-4.4 Y-4.4 E45.16494
G1 X-4.4 Y4.4 E45.60397
G1 X4.4 Y4.4 E46.04301
G0 F7200 X4.8 Y4.8
G1 F1050 X4.8 Y-4.8 E46.52195
G1 X-4.8 Y-4.8 E47.0009
G1 X-4.8 Y4.8 E47.47985
G1 X4.8 Y4.8 E47.95879
G1 F2100 E40.45879
G0 F7200 X4.2 Y3.2
G1 F2100 E47.95879
G1 F1050 X-4.2 Y3.2 E48.37787
G1 F2100 E40.87787
G0 F7200 X-4.2 Y1.6
G1 F2100 E48.37787
G1 F1050 X4.2 Y1.6 E48.79695
G1 F2100 E41.29695
G0 F7200 X4.2 Y0
G1 F2100 E48.79695
G1 F1050 X-4.2 Y0 E49.21602
G1 F2100 E41.71602
G0 F7200 X-4.2 Y-1.6
G1 F2100 E49.21602
G1 F1050 X4.2 Y-1.6 E49.6351
G1 F2100 E42.1351
G0 F7200 X4.2 Y-3.2
G1 F2100 E49.6351
G1 F1050 X-4.2 Y-3.2 E50.05418
G1 F2100 E42.55418
G0 F7200 X-4.4 Y-4.4 Z1.5
G1 F2100 E50.05418
G1 F1050 X4.4 Y-4.4 E50.49321
G1 X4.4 Y4.4 E50.93225
G1 X-4.4 Y4.4 E51.37128
G1 X-4.4 Y-4.4 E51.81032
G0 F7200 X-4.8 Y-4.8
G1 F1050 X4.8 Y-4.8 E52.28926
G1 X4.8 Y4.8 E52.76821
G1 X-4.8 Y4.8 E53.24715
G1 X-4.8 Y-4.8 E53.7261
G1 F2100 E46.2261
G0 F7200 X-3.2 Y-4.2
G1 F2100 E53.7261
G1 F1050 X-3.2 Y4.2 E54.14518
G1 F2100 E46.64518
G0 F7200 X-1.6 Y4.2
G1 F2100 E54.14518
G1 F1050 X-1.6 Y-4.2 E54.56425
G1 F2100 E47.06425
G0 F7200 X0 Y-4.2
G1 F2100 E54.56425
G1 F1050 X0 Y4.2 E54.98333
G1 F2100 E47.48333
G0 F7200 X1.6 Y4.2
G1 F2100 E54.98333
G1 F1050 X1.6 Y-4.2 E55.40241
G1 F2100 E47.90241
G0 F7200 X3.2 Y-4.2
G1 F2100 E55.40241
G1 F1050 X3.2 Y4.2 E55.82149
G1 F2100 E48.32149
G0 F7200 X4.4 Y4.4 Z1.8
G1 F2100 E55.82149
G1 F1050 X4.4 Y-4.4 E56.26052
G1 X-4.4 Y-4.4 E56.69955
G1 X-4.4 Y4.4 E57.13859
G1 X4.4 Y4.4 E57.57762
G0 F7200 X4.8 Y4.8
G1 F1050 X4.8 Y-4.8 E58.05657
G1 X-4.8 Y-4.8 E58.53551
G1 X-4.8 Y4.8 E59.01446
G1 X4.8 Y4.8 E59.49341
G1 F2100 E51.99341
G0 F7200 X4.2 Y3.2
G1 F2100 E59.49341
G1 F1050 X-4.2 Y3.2 E59.91248
G1 F2100 E52.41248
G0 F7200 X-4.2 Y1.6
G1 F2100 E59.91248
G1 F1050 X4.2 Y1.6 E60.33156
G1 F2100 E52.83156
G0 F7200 X4.2 Y0
G1 F2100 E60.33156
G1 F1050 X-4.2 Y0 E60.75064
G1 F2100 E53.25064
G0 F7200 X-4.2 Y-1.6
G1 F2100 E60.75064
G1 F1050 X4.2 Y-1.6 E61.16972
G1 F2100 E53.66972
G0 F7200 X4.2 Y-3.2
G1 F2100 E61.16972
G1 F1050 X-4.2 Y-3.2 E61.58879
G1 F2100 E54.08879
G0 F7200 X-4.4 Y-4.4 Z2.1
G1 F2100 E61.58879
G1 F1050 X4.4 Y-4.4 E62.02783
G1 X4.4 Y4.4 E62.46686
G1 X-4.4 Y4.4 E62.9059
G1 X-4.4 Y-4.4 E63.34493
G0 F7200 X-4.8 Y-4.8
G1 F1050 X4.8 Y-4.8 E63.82388
G1 X4.8 Y4.8 E64.30282
G1 X-4.8 Y4.8 E64.78177
G1 X-4.8 Y-4.8 E65.26071
G1 F2100 E57.76071
G0 F7200 X-3.2 Y-4.2
G1 F2100 E65.26071
G1 F1050 X-3.2 Y4.2 E65.67979
G1 F2100 E58.17979
G0 F7200 X-1.6 Y4.2
G1 F2100 E65.67979
G1 F1050 X-1.6 Y-4.2 E66.09887
G1 F2100 E58.59887
G0 F7200 X0 Y-4.2
G1 F2100 E66.09887
G1 F1050 X0 Y4.2 E66.51795
G1 F2100 E59.01795
G0 F7200 X1.6 Y4.2
G1 F2100 E66.51795
G1 F1050 X1.6 Y-4.2 E66.93702
G1 F2100 E59.43702
G0 F7200 X3.2 Y-4.2
G1 F2100 E66.93702
G1 F1050 X3.2 Y4.2 E67.3561
G1 F2100 E59.8561
G0 F7200 X4.4 Y4.4 Z2.4
G1 F2100 E67.3561
G1 F1050 X4.4 Y-4.4 E67.79514
G1 X-4.4 Y-4.4 E68.23417
G1 X-4.4 Y4.4 E68.6732
G1 X4.4 Y4.4 E69.11224
G0 F7200 X4.8 Y4.8
G1 F1050 X4.8 Y-4.8 E69.59118
G1 X-4.8 Y-4.8 E70.07013
G1 X-4.8 Y4.8 E70.54908
G1 X4.8 Y4.8 E71.02802
G1 F2100 E63.52802
G0 F7200 X4.2 Y3.2
G1 F2100 E71.02802
G1 F1050 X-4.2 Y3.2 E71.4471
G1 F2100 E63.9471
G0 F7200 X-4.2 Y1.6
G1 F2100 E71.4471
G1 F1050 X4.2 Y1.6 E71.86618
G1 F2100 E64.36618
G0 F7200 X4.2 Y0
G1 F2100 E71.86618
G1 F1050 X-4.2 Y0 E72.28525
G1 F2100 E64.78525
G0 F7200 X-4.2 Y-1.6
G1 F2100 E72.28525
G1 F1050 X4.2 Y-1.6 E72.70433
G1 F2100 E65.20433
G0 F7200 X4.2 Y-3.2
G1 F2100 E72.70433
G1 F1050 X-4.2 Y-3.2 E73.12341
G1 F2100 E65.62341
G0 F7200 X-4.4 Y-4.4 Z2.7
G1 F2100 E73.12341
G1 F1050 X4.4 Y-4.4 E73.56244
G1 X4.4 Y4.4 E74.00148
G1 X-4.4 Y4.4 E74.44051
G1 X-4.4 Y-4.4 E74.87954
G0 F7200 X-4.8 Y-4.8
G1 F1050 X4.8 Y-4.8 E75.35849
G1 X4.8 Y4.8 E75.83744
G1 X-4.8 Y4.8 E76.31638
G1 X-4.8 Y-4.8 E76.79533
G1 F2100 E69.29533
G0 F7200 X-3.2 Y-4.2
G1 F2100 E76.79533
G1 F1050 X-3.2 Y4.2 E77.21441
G1 F2100 E69.71441
G0 F7200 X-1.6 Y4.2
G1 F2100 E77.21441
G1 F1050 X-1.6 Y-4.2 E77.63348
G1 F2100 E70.13348
G0 F7200 X0 Y-4.2
G1 F2100 E77.63348
G1 F1050 X0 Y4.2 E78.05256
G1 F2100 E70.55256
G0 F7200 X1.6 Y4.2
G1 F2100 E78.05256
G1 F1050 X1.6 Y-4.2 E78.47164
G1 F2100 E70.97164
G0 F7200 X3.2 Y-4.2
G1 F2100 E78.47164
G1 F1050 X3.2 Y4.2 E78.89072
G0 F7200 X3.2 Y4.4 Z3
G1 F1050 X-4.4 Y4.4 E79.26988
G1 X-4.4 Y-4.4 E79.70892
G1 X3.2 Y-4.4 E80.08808
G1 X3.2 Y4.4 E80.52712
G0 F7200 X3 Y4
G1 F1050 X-4.2 Y4 E80.88633
G0 F7200 X-4.2 Y3.6
G1 F1050 X3 Y3.6 E81.24553
G0 F7200 X3 Y3.2
G1 F1050 X-4.2 Y3.2 E81.60474
G0 F7200 X-4.2 Y2.8
G1 F1050 X3 Y2.8 E81.96395
G0 F7200 X3 Y2.4
G1 F1050 X-4.2 Y2.4 E82.32316
G0 F7200 X-4.2 Y2
G1 F1050 X3 Y2 E82.68237
G0 F7200 X3 Y1.6
G1 F1050 X-4.2 Y1.6 E83.04158
G0 F7200 X-4.2 Y1.2
G1 F1050 X3 Y1.2 E83.40079
G0 F7200 X3 Y0.8
G1 F1050 X-4.2 Y0.8 E83.76
G0 F7200 X-4.2 Y0.4
G1 F1050 X3 Y0.4 E84.11921
G0 F7200 X3 Y0
G1 F1050 X-4.2 Y0 E84.47842
G0 F7200 X-4.2 Y-0.4
G1 F1050 X3 Y-0.4 E84.83763
G0 F7200 X3 Y-0.8
G1 F1050 X-4.2 Y-0.8 E85.19684
G0 F7200 X-4.2 Y-1.2
G1 F1050 X3 Y-1.2 E85.55605
G0 F7200 X3 Y-1.6
G1 F1050 X-4.2 Y-1.6 E85.91526
G0 F7200 X-4.2 Y-2
G1 F1050 X3 Y-2 E86.27447
G0 F7200 X3 Y-2.4
G1 F1050 X-4.2 Y-2.4 E86.63368
G0 F7200 X-4.2 Y-2.8
G1 F1050 X3 Y-2.8 E86.99289
G0 F7200 X3 Y-3.2
G1 F1050 X-4.2 Y-3.2 E87.3521
G0 F7200 X-4.2 Y-3.6
G1 F1050 X3 Y-3.6 E87.7113
G0 F7200 X3 Y-4
G1 F1050 X-4.2 Y-4 E88.07051
G0 F7200 X-4.8 Y-4.8
G1 F1050 X3.6 Y-4.8 E88.48959
G1 X3.6 Y4.8 E88.96854
G1 X-4.8 Y4.8 E89.38762
G1 X-4.8 Y-4.8 E89.86656
G0 F7200 X-4.4 Y-4.4 Z3.3
G1 F1050 X1.2 Y-4.4 E90.14595
G1 X1.2 Y4.4 E90.58498
G1 X-4.4 Y4.4 E90.86437
G1 X-4.4 Y-4.4 E91.3034
G0 F7200 X-4 Y-4.2
G1 F1050 X-4 Y4.2 E91.72248
G0 F7200 X-3.6 Y4.2
G1 F1050 X-3.6 Y-4.2 E92.14155
G0 F7200 X-3.2 Y-4.2
G1 F1050 X-3.2 Y4.2 E92.56063
G0 F7200 X-2.8 Y4.2
G1 F1050 X-2.8 Y-4.2 E92.97971
G0 F7200 X-2.4 Y-4.2
G1 F1050 X-2.4 Y4.2 E93.39879
G0 F7200 X-2 Y4.2
G1 F1050 X-2 Y-4.2 E93.81787
G0 F7200 X-1.6 Y-4.2
G1 F1050 X-1.6 Y4.2 E94.23694
G0 F7200 X-1.2 Y4.2
G1 F1050 X-1.2 Y-4.2 E94.65602
G0 F7200 X-0.8 Y-4.2
G1 F1050 X-0.8 Y4.2 E95.0751
G0 F7200 X-0.4 Y4.2
G1 F1050 X-0.4 Y-4.2 E95.49418
G0 F7200 X0 Y-4.2
G1 F1050 X0 Y4.2 E95.91325
G0 F7200 X0.4 Y4.2
G1 F1050 X0.4 Y-4.2 E96.33233
G0 F7200 X0.8 Y-4.2
G1 F1050 X0.8 Y4.2 E96.75141
G0 F7200 X1.6 Y4.8
G1 F1050 X-4.8 Y4.8 E97.07071
G1 X-4.8 Y-4.8 E97.54965
G1 X1.6 Y-4.8 E97.86895
G1 X1.6 Y4.8 E98.3479
G1 F2100 E90.8479
G0 F7200 X-0.8 Y4.4 Z3.6
G1 F2100 E98.3479
G1 F1050 X-0.8 Y-4.4 E98.78693
G1 X-4.4 Y-4.4 E98.96653
G1 X-4.4 Y4.4 E99.40557
G1 X-0.8 Y4.4 E99.58517
G0 F7200 X-1 Y4
G1 F1050 X-4.2 Y4 E99.74482
G0 F7200 X-4.2 Y3.6
G1 F1050 X-1 Y3.6 E99.90447
G0 F7200 X-1 Y3.2
G1 F1050 X-4.2 Y3.2 E100.06412
G0 F7200 X-4.2 Y2.8
G1 F1050 X-1 Y2.8 E100.22377
G0 F7200 X-1 Y2.4
G1 F1050 X-4.2 Y2.4 E100.38342
G0 F7200 X-4.2 Y2
G1 F1050 X-1 Y2 E100.54306
G0 F7200 X-1 Y1.6
G1 F1050 X-4.2 Y1.6 E100.70271
G0 F7200 X-4.2 Y1.2
G1 F1050 X-1 Y1.2 E100.86236
G0 F7200 X-1 Y0.8
G1 F1050 X-4.2 Y0.8 E101.02201
G0 F7200 X-4.2 Y0.4
G1 F1050 X-1 Y0.4 E101.18166
G0 F7200 X-1 Y0
G1 F1050 X-4.2 Y0 E101.34131
G0 F7200 X-4.2 Y-0.4
G1 F1050 X-1 Y-0.4 E101.50096
G0 F7200 X-1 Y-0.8
G1 F1050 X-4.2 Y-0.8 E101.66061
G0 F7200 X-4.2 Y-1.2
G1 F1050 X-1 Y-1.2 E101.82025
G0 F7200 X-1 Y-1.6
G1 F1050 X-4.2 Y-1.6 E101.9799
G0 F7200 X-4.2 Y-2
G1 F1050 X-1 Y-2 E102.13955
G0 F7200 X-1 Y-2.4
G1 F1050 X-4.2 Y-2.4 E102.2992
G0 F7200 X-4.2 Y-2.8
G1 F1050 X-1 Y-2.8 E102.45885
G0 F7200 X-1 Y-3.2
G1 F1050 X-4.2 Y-3.2 E102.6185
G0 F7200 X-4.2 Y-3.6
G1 F1050 X-1 Y-3.6 E102.77815
G0 F7200 X-1 Y-4
G1 F1050 X-4.2 Y-4 E102.93779
G0 F7200 X-4.8 Y-4.8
G1 F1050 X-0.4 Y-4.8 E103.15731
G1 X-0.4 Y4.8 E103.63626
G1 X-4.8 Y4.8 E103.85577
G1 X-4.8 Y-4.8 E104.33472
G0 F7200 X-4.4 Y-4.4 Z3.9
G1 F1050 X-2.8 Y-4.4 E104.41454
G1 X-2.8 Y4.4 E104.85358
G1 X-4.4 Y4.4 E104.9334
G1 X-4.4 Y-4.4 E105.37244
G0 F7200 X-4.0044 Y-4.2
G1 F1050 X-4.0044 Y4.2 E105.79151
G0 F7200 X-3.6044 Y4.2
G1 F1050 X-3.6044 Y-4.2 E106.21059
G0 F7200 X-3.2044 Y-4.2
G1 F1050 X-3.2044 Y4.2 E106.62967
G0 F7200 X-2.4 Y4.8
G1 F1050 X-4.8 Y4.8 E106.74941
G1 X-4.8 Y-4.8 E107.22835
G1 X-2.4 Y-4.8 E107.34809
G1 X-2.4 Y4.8 E107.82703
G1 F2100 E100.32703
G0 F7200 X-4.8 Y4.8 Z4.2
G1 F2100 E107.82703
G1 F1050 X-4.4 Y4.8 E107.84699
G1 X-4.4 Y-4.8 E108.32594
G1 X-4.8 Y-4.8 E108.34589
G1 X-4.8 Y4.8 E108.82484
G0 F7200 X-4.4044 Y4.4 Z4.411
G1 F1050 X4.4044 Y4.4 Z3.089 E109.26923
G1 X4.4044 Y-4.4 E109.70826
G1 X-4.4044 Y-4.4 Z4.411 E110.15266
G1 X-4.4044 Y4.4 E110.59169
G0 F7200 X-4.2066 Y4 Z4.381
G1 F1050 X4.2066 Y4 Z3.119 E111.01613
G0 F7200 X4.2066 Y3.6
G1 F1050 X-4.2066 Y3.6 Z4.381 E111.44056
G0 F7200 X-4.2066 Y3.2
G1 F1050 X4.2066 Y3.2 Z3.119 E111.865
G0 F7200 X4.2066 Y2.8
G1 F1050 X-4.2066 Y2.8 Z4.381 E112.28943
G0 F7200 X-4.2066 Y2.4
G1 F1050 X4.2066 Y2.4 Z3.119 E112.71387
G0 F7200 X4.2066 Y2
G1 F1050 X-4.2066 Y2 Z4.381 E113.13831
G0 F7200 X-4.2066 Y1.6
G1 F1050 X4.2066 Y1.6 Z3.119 E113.56274
G0 F7200 X4.2066 Y1.2
G1 F1050 X-4.2066 Y1.2 Z4.381 E113.98718
G0 F7200 X-4.2066 Y0.8
G1 F1050 X4.2066 Y0.8 Z3.119 E114.41161
G0 F7200 X4.2066 Y0.4
G1 F1050 X-4.2066 Y0.4 Z4.381 E114.83605
G0 F7200 X-4.2066 Y0
G1 F1050 X4.2066 Y0 Z3.119 E115.26048
G0 F7200 X4.2066 Y-0.4
G1 F1050 X-4.2066 Y-0.4 Z4.381 E115.68492
G0 F7200 X-4.2066 Y-0.8
G1 F1050 X4.2066 Y-0.8 Z3.119 E116.10936
G0 F7200 X4.2066 Y-1.2
G1 F1050 X-4.2066 Y-1.2 Z4.381 E116.53379
G0 F7200 X-4.2066 Y-1.6
G1 F1050 X4.2066 Y-1.6 Z3.119 E116.95823
G0 F7200 X4.2066 Y-2
G1 F1050 X-4.2066 Y-2 Z4.381 E117.38266
G0 F7200 X-4.2066 Y-2.4
G1 F1050 X4.2066 Y-2.4 Z3.119 E117.8071
G0 F7200 X4.2066 Y-2.8
G1 F1050 X-4.2066 Y-2.8 Z4.381 E118.23154
G0 F7200 X-4.2066 Y-3.2
G1 F1050 X4.2066 Y-3.2 Z3.119 E118.65597
G0 F7200 X4.2066 Y-3.6
G1 F1050 X-4.2066 Y-3.6 Z4.381 E119.08041
G0 F7200 X-4.2066 Y-4
G1 F1050 X4.2066 Y-4 Z3.119 E119.50484
G0 F7200 X4.8 Y-4.8 Z3.03
G1 F1050 X-4.8 Y-4.8 Z4.47 E119.98915
G1 X-4.8 Y4.8 E120.46809
G1 X4.8 Y4.8 Z3.03 E120.9524
G1 X4.8 Y-4.8 E121.43134
G1 F2100 E113.93134
M140 S0 ;Cool heatbed
M107 ;Fan off
M104 S0 ;Cool head
M140 S0 ;Cool heatbed
;Retract the filament
G92 E1 ;Reset extruder value
G1 E-1 F300 ;Retract 2mm
G28 X0 Y0 ;Home axes
M84 ;Loosen motors
M82 ;absolute extrusion mode
M104 S0 ;Cool head
;End of gcode</pre>
</details>

**Comment by Ghostkeeper** [comment]
This could be a problem of us only being able to render colours per vertex. Since g-code produces a gigantic amount of vertices to render, the beginning and ending of a line segment share the same vertex, and that vertex can only have one colour.
Am I right in this analysis, @nallath, or did we indeed duplicate all vertices at the borders? We must be doing something right in order to get the line width correct, but maybe we split up the polylines for different line widths.

This is not a problem for filament colour (since all polylines must get printed with one filament), line type (since connected lines always have the same line type and we do duplicate vertices for travel moves) or layer height (since all polylines belong to the same layer and thus have the same height).

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?

**Comment by mbartlett21** [comment]
It is fine with 5.9.0.
![image](https://github.com/user-attachments/assets/2fadcf2c-f65b-4d7c-8144-acbc5088140a)
