### ISSUE TITLE
F5 fails to reload gcode file

### ISSUE THREAD

**Issue by mbartlett21** [Ultimaker/Cura#5978]
**Application version**
4.1.0

**Platform**
Window 10 1903

**Reproduction steps**
Load a GCode.
Edit the gcode
Press f5 in Cura

**Actual results**
Nothing happens

**Expected results**
Cura reloads gcode

**Comment by Ghostkeeper** [comment]
This happens because F5 causes Cura to iterate over all scene nodes and reload each of them. However the g-code is not in a scene node. We need additional logic there to also track the file name of the loaded g-code, and if any exists, reload that too.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
