### ISSUE TITLE
Add suspend inhibition when printing via USB (KDE and Windows*)

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#598]
I think this will be very useful when using a laptop or even a desktop computer, which uses suspending a lot. I found this feature in Amarok together with the KDE desktop. The usage there is to inhibit suspending the system as long as playing music.
So in our case this would be useful during USB printing!

I found the commit which adds the initial feature to Amarok:
https://quickgit.kde.org/?p=amarok.git&a=commit&h=71e55e7bdd9b31642d09145a5801777c0e120454

However, at the moment https://github.com/Ultimaker/Cura/issues/402 is more important...

**Comment by daid** [comment]
For windows I have this code in the old Cura:
https://github.com/daid/Cura/blob/SteamEngine/Cura/gui/printWindow.py#L12

**Comment by Ghostkeeper** [comment]
If we add a type of job that is "critical" then we can generalise this to also happen while doing other critical jobs, such as writing to devices and other things that shouldn't be interrupted that we'll do in the future.

**Comment by ianpaschal** [comment]
Hasn't been touched in almost 2 years.
