### ISSUE TITLE
Cura 4.1.0 crashes after slicing

### ISSUE THREAD

**Issue by allenlawrence** [Ultimaker/Cura#5990]
Every time I load up stl and slice it while saving gcode as soon as I click "Save" the whole software crashes. Please, devs look into the issue.
[cura.log](https://github.com/Ultimaker/Cura/files/3369425/cura.log)

**Comment by allenlawrence** [comment]
![Untitled5](https://user-images.githubusercontent.com/52664272/60828470-150db480-a1d0-11e9-8c4b-233f0be97871.png)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5937
