### ISSUE TITLE
Interface unusably slow

### ISSUE THREAD

**Issue by fvlasie** [Ultimaker/Cura#5991]
Hello,

I am noticing incredible slowness when trying to use the Cura interface. It literally take several seconds to respond to a button push. Trying to rotate the model takes several mouse clicks just to get the model to select. I am not using a slow computer either: Mac Pro 3.46Ghz 6 core, 32GB RAM, 1TB SSD, Mac OS 10.13.5.

Thank you

FV
[slowcura.mp4.zip](https://github.com/Ultimaker/Cura/files/3369804/slowcura.mp4.zip)

**Comment by Ghostkeeper** [comment]
The slowness when enabling support is known. There's a lot of settings that need to be updated when this happens. Some settings have it worse than others, but the "Enable" checkboxes are particularly bad in this aspect.

The other issue is not that it's slow, but that there are sometimes zones on the screen that you can't seem to click on. Also a known issue, but hard to reproduce if you actually want to reproduce it: https://github.com/Ultimaker/Cura/issues/5880

**Comment by fvlasie** [comment]
OK! thanks for the info.
