### ISSUE TITLE
Post Processing - ChangeAtZ 5.1.1 Not Working Correctly

### ISSUE THREAD

**Issue by NickTom88** [Ultimaker/Cura#5995]
I tried searching for this issue and didn't run across anything so hopefully this isn't an extra. Also, I know it says Experimental, so hopefully this helps move it along.

**Application version**
4.1

**Platform**
Windows 10

**Printer**
Creality Ender 3 Pro

**Reproduction steps**
When making a Flow Rate tower I added 8 blocks of "ChangeAtZ" starting at layer 1 and select Keep Value for 40 layers(80%, 85%, 90%, etc...) 

**Actual results**
Instead of holder the assigned value until the next ChangeAtZ block, the flow rate just progressively increased through the entire print. Reviewing the GCode shows this as well.

**Expected results**
My impression is that ChangeAtZ should hold exactly the values you input and only change when the layers/height are outside it's parameters or the values have been changed by another block. eg. @ layer 1 - 80% flow rate for 40 layers, @ layer 41 - 85% flow rate for 40 layers...

**Additional information**
View attachments for job and screenshot
![2019-07-09](https://user-images.githubusercontent.com/52723322/60929397-0b369080-a266-11e9-9b8e-12333c412513.png)

[Extrusion_multiplier_test..curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/3375104/Extrusion_multiplier_test.curaproject.3mf.zip)

[Extrusion_multiplier_test.gcode.zip](https://github.com/Ultimaker/Cura/files/3375116/Extrusion_multiplier_test.gcode.zip)

**Comment by Ghostkeeper** [comment]
Set the "No. Layers" parameter to 1 then. In Cura 4.2 we've renamed that to "Layer Spread" to better indicate what it does.
