### ISSUE TITLE
4.1 White screen but menus are fine.

### ISSUE THREAD

**Issue by SaltyLiquorice** [Ultimaker/Cura#6003]
**Application version**
4.1.0

**Platform**
Win10 1803

**Printer**
Both UM3 and SidewinderX1

**Reproduction steps**
Open Cura

**Actual results**
White screen

**Expected results**
Not a white screen

**Additional information**
![CuraWhite](https://user-images.githubusercontent.com/31382454/61122357-f6b3fb80-a4e4-11e9-93c3-f4209ea9b310.PNG)

Heres the log of the last time I opened Cura:
[BadLog.txt](https://github.com/Ultimaker/Cura/files/3386118/BadLog.txt)

**Comment by fieldOfView** [comment]
What GPU does your computer use? Cura is having trouble opening an OpenGL context.
Interestingly, Cura is "trying to" crash with a critical error, but doesn't.

**Comment by SaltyLiquorice** [comment]
Dedicated, 1080ti.

**Comment by fieldOfView** [comment]
It is unlikely that reinstalling Cura will do anything. Updating drivers may help.

**Comment by SaltyLiquorice** [comment]
And a PC restart fixed it.

**Comment by fxh1357** [comment]
I got the same issue - Restarting the PC can't be the fix^^

**Comment by Ghostkeeper** [comment]
PC restarting might be the fix if you updated your graphics drivers and didn't restart the PC yet afterwards.
