### ISSUE TITLE
[4.0.0] Rotate->Flat progress goes beyond 100%

### ISSUE THREAD

**Issue by 10MINT** [Ultimaker/Cura#6009]
**Application version**

4.0.0

**Platform**

Windows 10

**Printer**

Custom (Tevo Tarantula)

**Reproduction steps**

Load a geometrically complicated model into Cura and click "Rotate" then "Flat"

**Actual results**

The progress bar goes beyond 100% and does weird transformations, like rotating the object and putting it out of bounds

**Expected results**

The progress should stop at 100% and should only rotate the model

**Additional information**

![Screenshot (27)](https://user-images.githubusercontent.com/10596945/61184137-67c0f380-a64a-11e9-8cbf-92cd9985687c.png)
Tested with Iron Man mask chin part

**Comment by Ghostkeeper** [comment]
Yup, I see it happening. Just need to load a model with a reasonable size otherwise the progress bar is too fast to read. (I was using [this one](https://github.com/Ghostkeeper/SlicerTestModels/blob/master/my/rotary_tumbler.scad).)

**Comment by BagelOrb** [comment]
Still happens in 4.2.1
![image](https://user-images.githubusercontent.com/8895761/62541158-7ec5c080-b859-11e9-83e3-6dcab3f03d4d.png)

**Comment by BagelOrb** [comment]
At 100% the object is already laid flat, but the loading bar continues for no apparent reason.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
