### ISSUE TITLE
Incorrect UI description for Ironing Feature

### ISSUE THREAD

**Issue by dstulken** [Ultimaker/Cura#6031]
**Application version**
Cura 4.1.0

**Platform**

(All?)

**Printer**

(Doesn't matter)

**Reproduction steps**

Hover mouse cursor over the "Enable Ironing" setting to view the description

**Actual results**

Cura 4.1.0's misleading description of Ironing (bolding emphasis is mine):
> "Go over the top surface one additional time, **_but without extruding material_**.  This is meant to melt the plastic on top further, creating a smoother surface."

**Expected results**

We would expect the ironing description to reflect the actual operation of the feature, something to the effect of:
> "Go over the top surface one additional time, **_while extruding a small amount of additional material_**.  This is meant to melt the plastic on top further, **_while also filling any remaining small gaps_**, creating a smoother surface."

(The "Ironing Flow" parameter defaults to 5%, so extrusion *is* enabled by default with Ironing.)

**Additional information**

See attached screenshots of misleading description in Cura software, and the more accurate feature description from the Cura 2.7 release announcement.

![Screen Shot 2019-07-19 at 10 51 09 AM](https://user-images.githubusercontent.com/43459037/61548692-e4b9e780-aa13-11e9-83ed-2336fcdf9b04.png)

![Screen Shot 2019-07-19 at 10 53 15 AM](https://user-images.githubusercontent.com/43459037/61548724-f00d1300-aa13-11e9-8ed1-45a87d6a6360.png)

**Comment by Vandrasc** [comment]
Hi @dstulken , thank you for your feedback, we will have a look and try to improve the description.

**Comment by Ghostkeeper** [comment]
I agree. Fixed it here: https://github.com/Ultimaker/Cura/commit/eca8f3ab577a3157db72137cf8bc7328eca85dd8 .

**Comment by dstulken** [comment]
Looks good, thanks!
