### ISSUE TITLE
No top layer while reducing section

### ISSUE THREAD

**Issue by notmine642** [Ultimaker/Cura#6038]
**Cura 4.1.0**

**Win 7 64bit**

**Custom**

**Reproduction steps**
Print a part that has a section that is reduced at mid height

**Actual results**
top layer is not printed and gap appears between inner layer of lower part and outer layer of upper part

**Expected results**
few layers to fill the gap

**Additional information**
![image](https://user-images.githubusercontent.com/36200667/61617004-2a6fed80-ac6a-11e9-9086-81cf79fc65f8.png)
layer 151
![image](https://user-images.githubusercontent.com/36200667/61617055-3e1b5400-ac6a-11e9-8af2-6ec39eec5cf9.png)
layer 152
![image](https://user-images.githubusercontent.com/36200667/61617076-4a9fac80-ac6a-11e9-80ba-94c474c72cef.png)
![image](https://user-images.githubusercontent.com/36200667/61617141-673be480-ac6a-11e9-928c-6dc22fef8dce.png)

I have 2 wall line count, if I put 3 it is quite ok.
The question is why Cura does not add a full layer to support the upper part ?

Thanks for your help

**Comment by Ghostkeeper** [comment]
Reduce the value of the Skin Removal Width if you want it to support the walls on top better. For models with curved lower and upper sides the Skin Removal Width is very useful, but for your case it is detrimental to your part's strength.

**Comment by notmine642** [comment]
thanks for your help, there is so many parameters in cura, I know the use of one more now !
Best regards
