### ISSUE TITLE
[2.1] Overlapping widgets in "Convert image..." dialog

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#604]
I think there is not much so say:
![cura-convertimage](https://cloud.githubusercontent.com/assets/1847437/12427296/ad4b6248-bede-11e5-92bb-b092d046b170.png)

If it is a known problem, as someone is currently working on this, sorry for reporting it so early..

**Comment by Ghostkeeper** [comment]
Yeah, we saw that one. The window is a bit too small. Should be an easy fix!

**Comment by thopiekar** [comment]
![cura-import-image](https://cloud.githubusercontent.com/assets/1847437/12793235/e7f29d4e-caaf-11e5-8f4c-130a931add1a.png)

Fixed via https://github.com/Ultimaker/Cura/commit/e7ab686318885a87ac3daa4e5ccc7d4d36fd5408
