### ISSUE TITLE
Customizable preview color schemes

### ISSUE THREAD

**Issue by DOCaCola** [Ultimaker/Cura#6040]
Feature request: Allow customization of preview color schemes.

The current color scheme is not ideal in some scenarios. I will quote a [forum post](https://community.ultimaker.com/topic/27233-change-color-of-preview-color-scheme/) that illustrates the issue:

------

Is it possible in CURA 4.0 to modify the color in the mode "Preview" => "Line type" => "Color Scheme"?

Currently the Top/Bottom-Layer is represented in a kind of light yellow. The infill is represented in let me say a kind of less light yellow color. As we are all aware about the fact that millions of colors are available I do not understand why this extremly similar colors have been choosen for representation by CURA.

E.g. why not follow the PRUSA Slicer approach?

Cura Approach:
![ulti_color thumb jpeg 3dff0a812a8aadb16b77ce7d02d775ac](https://user-images.githubusercontent.com/2077396/61637204-69686800-ac97-11e9-91f9-5b24bb072b76.jpg)

PRUSA Slicer Approach:﻿﻿

![prusa_color thumb jpeg 8b3aef5a02f0800329c2931c30d91681](https://user-images.githubusercontent.com/2077396/61637272-83a24600-ac97-11e9-9aa7-a51dc8dc53e8.jpg)

------------

Allowing user customizable color schemes would mitigate this issue.

**Comment by nallath** [comment]
The main reason for it is simply "legacy". It's pretty much how the first versions of Cura did it, so it made sense to keep them. 
That being said you can change these values in the theme. It's not super user friendly to change, but at least there is a way to do it.

**Comment by Ghostkeeper** [comment]
That being said, we've changed the default two themes such that infill is now a darker orange for Cura 4.2. That should address the actual issue. Theming should take care of the rest. I don't see the need for the user being able to customise that himself.
