### ISSUE TITLE
Allow bypassing getting started.

### ISSUE THREAD

**Issue by MrStonedOne** [Ultimaker/Cura#6044]
**Is your feature request related to a problem? Please describe.**
There is zero reason UMC *needs* to know what printer I have. Ya, its nice to have info, that can be used to provide a better UX, but not ***needed***. Give me at most a form to enter size and offsets and hit checkmarks for gcode features.

**Describe the solution you'd like**
An X button on the getting started prompt after agreeing to the terms.

**Describe alternatives you've considered**
A skip for now button on the printer setup.

**Affected users and/or printers**
Power users, people in a hurry who have a custom printer and don't want to have to go lookup the closest analogue.  

**Additional context**
My anet a8 printer has a custom and slightly bigger hotplate, a custom gentry with different offsets, a custom hotend, and custom firmware compiled at my house. You won't have my printer, and making me set up a fake one before I can access the settings menu to setup my real one is shitty UX.

edit: Also you *still* don't have the anet a8 in the presets. Why try and force people to choose their printer if you won't even bother to try and maintain a comprehensive list of printers.

**Comment by rburema** [comment]
You can select Custom FFF from that menu, which does exactly that (it pops up a menu asking for size, etc.).

> edit: Also you still don't have the anet a8 in the presets. Why try and force people to choose their printer if you won't even bother to try and maintain a comprehensive list of printers.

Printer profiles (other than Ultimaker) are added by the community. If you feel an important printer is missing, please don't hesitate to make a pull request.
