### ISSUE TITLE
USB-/COM open

### ISSUE THREAD

**Issue by 3dmecanico** [Ultimaker/Cura#6049]
When you open Cura it´s try to connect to printer If it´s succesefully Cura get port. This action have to problems: First , some printer reset when connect. Second if you need to use this port (ex. Pronterface) is busy. It`s possibly to turn this auto connect to manually opción. This option is necessary a long time ago. Please sorry for mi bad english
--

**Comment by Ghostkeeper** [comment]
This is a duplicate of #5207. Please continue discussion there. Sorry for the confusion!
