### ISSUE TITLE
Screen issues

### ISSUE THREAD

**Issue by bruster555** [Ultimaker/Cura#6055]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by bruster555** [comment]
In the monitor section, the extruder and build plate dialogue boxes are covered. In the prepare section, the X arrow (RED) for movement when selected to move, disappears, but only on part of the build plate.

**Comment by Ghostkeeper** [comment]
I'm not sure which dialogue boxes you mean. Is this for USB printing, connected via Wifi to an Ultimaker printer, or maybe OctoPrint?

And I've never seen the arrow disappear. It's going behind the selection outline though, but that doesn't seem like what you meant.
