### ISSUE TITLE
Cura slicing issue, but same settings work perfect in simplify

### ISSUE THREAD

**Issue by mateusbatatais** [Ultimaker/Cura#6062]
**Application version**
4.1.0

**Platform**
Windows 10

**Printer**
Custom Hypercube Hevolution

**Reproduction steps**
I have a problem setting up my Cura... Check out my cat print (in gray) made in simplify 3d. Then look at my black print made in Cura(ignore interrupted printing). I used the same settings a friend uses on his printer, just like mine (a Hypercube Hevo we assemble with the same parts and size).

What I want to make clear is that my printer works normally with Simplify, but I would like to use Cura. The problem is that when I print with it, it looks like my printer is defective.

Any suggestion? Everything indicates an overextrusion, but my extruder calibration is fine and I am using a 1.75mm filament, set correctly ...

My cure is 4.1.0, ABS printing, 60mm / s, nozzle 225, table 110.
All identical to my friend's who perfectly with an identical printer.

**Actual results**
Cat looks like overextrusion

**Expected results**
Correct print

**Additional information**
Printer works fine with another slicer, like Simplify 3d
![IMG_20190726_093838](https://user-images.githubusercontent.com/5104733/61953218-3a4e4100-af8c-11e9-9f64-6d0ead08ce74.jpg)
![IMG_20190726_093850](https://user-images.githubusercontent.com/5104733/61953219-3a4e4100-af8c-11e9-8ea7-7db2da396246.jpg)
![IMG_20190726_094414](https://user-images.githubusercontent.com/5104733/61953220-3a4e4100-af8c-11e9-8434-0e5d2a1e70f1.jpg)
![IMG_20190726_094422](https://user-images.githubusercontent.com/5104733/61953221-3a4e4100-af8c-11e9-998f-6e280c7f2a38.jpg)
![IMG_20190726_094433](https://user-images.githubusercontent.com/5104733/61953223-3ae6d780-af8c-11e9-8c76-858b3addde9f.jpg)
![IMG_20190726_094443](https://user-images.githubusercontent.com/5104733/61953225-3ae6d780-af8c-11e9-8396-d423129557c0.jpg)

**Comment by smartavionics** [comment]
Those photos don't tell us much (and the're far too big for my feeble broadband to cope with, please don't upload any more that size!). What would actually be useful would be if you could save the cura project file (File -> Save) and then zip the .3mf file or rename to .zip and attach that. Thanks.

**Comment by mateusbatatais** [comment]
Ok. Sorry for the images. Attached the project zipped. Look at Hevo Normal.
[Untitled.zip](https://github.com/Ultimaker/Cura/files/3437297/Untitled.zip)

**Comment by smartavionics** [comment]
Thanks for the file. Unfortunately, it doesn't contain the model. Could you also attach that or another .3mf file with the model.

Sorry for whining about the images but my broadband is currently running at 20 KB/S download speed (that's not a typo). Engineer hopefully will turn up tomorrow and fix it!

**Comment by mateusbatatais** [comment]
with the model. Thank you!

[CFFFP_calicat.zip](https://github.com/Ultimaker/Cura/files/3437377/CFFFP_calicat.zip)

**Comment by mateusbatatais** [comment]
update. I have another printer, prusa i3x. I just tried the same settings there and it worked. A good print. The strange thing is that I'm making another impression here in my Hevo, sliced by simplify and it's happening normally.

**Comment by smartavionics** [comment]
I looked at your project and can't see anything at all obviously wrong. I would recommend enabling the optimize wall printing order but I doubt if that's what the problem is.

Those photos reminded me of a problem I had a while back where seemingly random layers over or under extruded. It turns out it was a faulty thermistor in the hotend.

**Comment by Ghostkeeper** [comment]
Two things I'd suggest to change here:
* Outer before inner walls. This normally gives greater dimensional accuracy.
* Enable Jerk Control and turn the jerk down a bit. We could be flexing the belts a bit.

**Comment by mateusbatatais** [comment]
Thank you for your help. After a few more tests and attempts, I noticed a small flaw that did not happen in simplify but in Cura ... The extruder is slightly weak and when this problem started to become more evident, I could notice even in other slicers. I squeezed the nozzle and adjusted small items. Problem solved. Thank you again.
