### ISSUE TITLE
[4.2 beta] Slicing stalls, and PC usage is low. Tree supports are slow to generate since this version

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6066]
**Application version**
4.2 beta

**Platform**
Win 10 x64. Ryzen 5 1600. RX vega 56.

**Printer**
Cr10s

**Reproduction steps**
Slice a complex model or use tree supports

**Actual results**
It just stalls. No advancement after 15+ minutes. GPU is unused, cpu total usage is 10-15% (does cura support multi threading?).

**Expected results**
It should use the available hardware to slice fast. Older Cura versions were way faster.

**Additional information**
![PC resources](https://user-images.githubusercontent.com/20385116/61983028-09f3ba80-afff-11e9-9ad5-4616882a53e7.png)

**Comment by Ghostkeeper** [comment]
Yeah, this reproduces. During the tree support processing it seems to use only one thread.

**Comment by Block137** [comment]
The no advancement after 15+ minutes happened to me when the model file size *in total* is above 400 MB. Cura seems to not start slicing at all, progress bar at 0% "Slicing", 0% CPU usage.

At this size of model file, Tree Support takes multiple hours to generate (never waited to see the result).

**Comment by Ghostkeeper** [comment]
For that you might want to check your log. If CuraEngine crashed (for instance due to running out of memory) you'd see it in there.

**Comment by MariMakes** [comment]
When using the tree supports generation, apparently only one thread is used, and therefore, the slicing time increases a lot. We have an item on our backlog to adress it. For internal reference CURA-6692

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
