### ISSUE TITLE
Cura 4.1.0 Cannot "Disable Extruder"

### ISSUE THREAD

**Issue by martijn1874** [Ultimaker/Cura#6069]
Hello,

I have an ultimaker 3 with a 0.8mm and 0.4mm printer core. I use the 0.8 for quickly printing jigs 
 and fixtures with tough PLA and the 0.4 for more detailed prototypes with normal PLA.

In Cura 4.1.0, when I have the 0.8 core mounted my 0.1 default profiles are not visible. This used to be a quick fix with "Disable Extruder". Also handy when printing multiple objects with the second print head so you don't have to manually change the extruder for each part.

However, recently the Disable Extruder setting is not working anymore. Nothing happens when I click it.

![image](https://user-images.githubusercontent.com/53366049/61991978-591a0980-b058-11e9-9029-4c112ad6f7c3.png)

**Comment by nallath** [comment]
Thanks for reporting it! As we're just finishing up the testing for the final 4.2 release, it will be fixed for 4.3. 
As a workaround, you can still use the checkboxes in the custom tab of the config selector
