### ISSUE TITLE
Ironing option stops middleprint cura 4.0

### ISSUE THREAD

**Issue by Erokawa** [Ultimaker/Cura#6080]
**Application version**
Cura 4.0

**Platform**
Windows 10 64bits version 1804, GPU: GTX 1060, Nvidia drivers: 413.60

**Printer**
Custom printer (SKR 1.3 - TMC2208 UART - BMGV6 - MARLIN 2.0)

**Reproduction steps**
Activating Ironing 

**Actual results**
The printer prints but ramdomly stops and the temperature of the extruder and bed will keep heating without error showing on the screen/ponterface

**Expected results**
The printer won't finish the print, it'll stop suddenly

**Additional information**

GCODE:
https://drive.google.com/file/d/1mTNV2KXd1NAYhKE6hsT-RMH2CFqMRRdr/view?usp=sharing

**Comment by Ghostkeeper** [comment]
I don't see anything wrong in the g-code. The ironing parts don't have any extrusion so Cura sees them as travel moves, but there is no pause command or heating command anywhere in between the ironing commands. I don't know why your custom printer is pausing halfway.

Are you printing via USB cable or via local file? Perhaps the printer couldn't keep up with reading the file?

**Comment by Erokawa** [comment]
Hi Sakamoto-san, i have to point up that i had another hardware before (MKS GEN 1.4 - TMC 2208 - ANET A8 EXTRUDER) and it happend the same. That time i just reinstalled cura and doing a new profile. It didn't stopped since some days ago when putting on ironing and it happens. I'm printing by tft32 touch panel with SD card.

**Comment by Ghostkeeper** [comment]
> Hi Sakamoto-san

:laughing: You know that's the first time someone actually recognised it and pointed it out?

I don't see anything in the g-code that should halt your printer, really. Maybe we can make a more controlled test of a cube with ironing or something?

**Comment by Erokawa** [comment]
Definitly not the ironing... for some reason with a simple model i made with Fusion 360 it stops some seconds and continues after, for sure are buffer size problems because maybe i didn't put M502 when i uploaded the firmware. I'll close this because the ironing definitely is not the problem, sorry for the trouble and thanks
