### ISSUE TITLE
[4.2] Failure to Slice with supports

### ISSUE THREAD

**Issue by lordpreto** [Ultimaker/Cura#6084]
Application version
4.2

Platform
Windows 10 x64

Printer
Creality Ender 3

Reproduction steps
Installed Cura 4.2. Created new printer. Default Profiles. Check Generate Support box. Hit Slice button.

Actual results

Error Message: "Unable to slice with the current settings: The Following settings have errors: Z Hop Speed"

If I try to disable Z Hop or lower Z Hop Speed, the error message changes to "Unable to slice with the current settings: The Following settings have errors:"

Expected results
It should slice.

**Comment by smartavionics** [comment]
See https://github.com/Ultimaker/Cura/issues/6073 (just reopened).

**Comment by lordpreto** [comment]
I will close this one then, thank you
