### ISSUE TITLE
[4.2.0]&[4.2.1] Support Brim generation depends on Buildplate Adhesion settings

### ISSUE THREAD

**Issue by GMaidana88** [Ultimaker/Cura#6094]
**Application Version**
4.2.0 & 4.2.1

**Platform**
Win 7 x64

**Printer**
Creality Ender 3

**Steps to Reproduce**
Enable Support Brim with Buildplate Adhesion set to None or Raft.

**Actual Results**
Support Brim is not generated if Buildplate Adhesion is set to None or Raft. If the latter is set to Skirt or Brim it's generated correctly.

**Expected results**
Expected Support Brim generation in all cases, regardless of Buildplate Adhesion selection.

**Additional Information**
01: Support Brim: ON, Buildplate Adhesion: None
![No Support Brim with Buildplate None](https://user-images.githubusercontent.com/43276970/62175798-4718bf00-b315-11e9-8198-65e3bc8bdc1a.jpg)

02: Support Brim: ON, Buildplate Adhesion: Raft
![No Support Brim with Buildplate Raft](https://user-images.githubusercontent.com/43276970/62175803-50099080-b315-11e9-8ae3-1ed0054d4239.jpg)

03: Support Brim: ON, Buildplate Adhesion: Skirt
![Support Brim with Buildplate Skirt](https://user-images.githubusercontent.com/43276970/62175810-5861cb80-b315-11e9-9c7b-6fcc5c0239b0.jpg)

04: Support Brim: ON, Buildplate Adhesion: Brim
![Support Brim with Buildplate Brim](https://user-images.githubusercontent.com/43276970/62175818-5e57ac80-b315-11e9-8ee0-2c064d249581.jpg)

**Comment by rburema** [comment]
Devs, see CURA-6700.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?

**Comment by GMaidana88** [comment]
Hi Greg,

I just checked on Cura 5.8.0, Win 10:

01) Support Brim: ON, Buildplate Adhesion: None = Works as expected
02) Support Brim: ON, Buildplate Adhesion: Raft = Does not generate brim on first support layer
03) Support Brim: ON, Buildplate Adhesion: Skirt = Works as expected
04) Support Brim: ON, Buildplate Adhesion: Brim = Works as expected

This is a non-issue to me, as I've never encountered a situation where I needed support brim over a raft, but just to be precise about it, this is the actual behaviour:

![image](https://github.com/user-attachments/assets/452e75c2-756d-4dd9-9ce5-542134984dad)


Cheers!

**Comment by GregValiant** [comment]
I think it's a non-issue too.  The raft supersedes the support brim and so the support brim would not be required in that scenario.
I'll go ahead and close this.

**Comment by GMaidana88** [comment]
> I think it's a non-issue too. The raft supersedes the support brim and so the support brim would not be required in that scenario. I'll go ahead and close this.

My thoughts exactly, go ahead and close it.

Thanks!
