### ISSUE TITLE
4.2 version Changelog

### ISSUE THREAD

**Issue by joseitor** [Ultimaker/Cura#6110]
You have release the new version 4.2 but there is no changelog anywhere. It would be useful to know the change is we have to adapt something in our Cura config or we can take advantage of new features.

**Comment by nallath** [comment]
It was moved to help-> whats new?

**Comment by Ghostkeeper** [comment]
The change log is still in the same place as it was in Cura 4.1. It should display upon first upgrading to 4.2 as well as from Help -> What's New.
