### ISSUE TITLE
[4.2.1] Supports cross the brim

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6118]
**Application version**
4.1.2

**Platform**
Win10 x64

**Printer**
Custom dual extruder

**Reproduction steps**
Use tree supports and brim

**Actual results**
They cross each other creating blobs and eventual fail

**Expected results**
there should be no support where there is the brim

**Additional information**
![support crossing brim](https://user-images.githubusercontent.com/20385116/62314745-05625280-b494-11e9-94d8-2dad60c88100.png)
[brim and support crossing.zip](https://github.com/Ultimaker/Cura/files/3458040/brim.and.support.crossing.zip)

**Comment by Vandrasc** [comment]
Hi @Liger0 , is the support brim enabled? Then the support should indeed be generated above the brim, for better adhesion of the support.

**Comment by Liger0** [comment]
Hi there. What you see in the preview is only the first layer, not the second.
On the first layer, different features cross each other, thus the nozzle clogs and the print fails, also the nozzle drags and moves out the first layer.
I never printed that model nor I intend to, I just use it because it is a simple yet complex enough model that helped me to test out settings and find multiple cura bugs until now.
The support brim is enabled, and the project is shared under the image.

**Comment by Ellecross** [comment]
Will it help if you disable the Support Brim? 

If you do, it will have only the support in the brim and one line with extruder 1 at the outermost. 

![image](https://user-images.githubusercontent.com/32929710/62634626-8313db80-b936-11e9-888f-0aaf3bd67c8f.png)

**Comment by Ghostkeeper** [comment]
I think the actual problem here is that you have both Tree Support and ordinary Generate Support enabled. This will generate the support twice which is not generally what you want and causes overextrusion.

We're planning to remove this possibility.

**Comment by Vandrasc** [comment]
We created a ticket internally for removing the possibility of enabling both type support, devs for our reference see CURA-6711.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
