### ISSUE TITLE
No Support Structure

### ISSUE THREAD

**Issue by Splodgeink** [Ultimaker/Cura#6134]
Tried 4.2.1 to print https://www.thingiverse.com/thing:3207754

Using recommended settings of 0.2mm and 50% with Support Structures ON.

No support structures were generated. 
![20190802_100054](https://user-images.githubusercontent.com/53603374/62358601-ef44a880-b50c-11e9-901a-1ef110849205.jpg)
![20190802_100100](https://user-images.githubusercontent.com/53603374/62358616-f1a70280-b50c-11e9-84f2-3c7c1f41ac7f.jpg)

I am using Windows 10 with the latest updates. Printing using an Ender 3 Pro (Which is working fine with Cura 4.1 (Windows 8 Compatibility set). I am printing via SD card.

**Application version**
4.2.1
**Platform**
Windows 10 64bit - latest updates installed

**Printer**
Ender 3 Pro
**Reproduction steps**
See pictures
**Actual results**
See Pictures
**Expected results**
Using preview in 4.1 I could see the support structures. These weren't there on 4.2.1
**Additional information**
See above

**Comment by Splodgeink** [comment]
![20190802_100100](https://user-images.githubusercontent.com/53603374/62358867-87429200-b50d-11e9-9523-f463c572bdae.jpg)
![20190802_100054](https://user-images.githubusercontent.com/53603374/62358878-8c9fdc80-b50d-11e9-8950-d4a5e649fc12.jpg)

Ha! New to programming and what I had typed in is not there! (still in those funny comment characters!)

Cura 4.2.1 is not generating support structures despite the setting being selected. It is working fine with 4.1 as I can see them in preview, but not in 4.2.1. I was printing https://www.thingiverse.com/thing:3207754 with the recommended settings.

**Comment by Splodgeink** [comment]
Found the edit function...

**Comment by JohnEdwa** [comment]
Even if you have supports on, the default setting for the Creawesome profiles is to have them limited to "Build Plate Only", which is a stupid idea.

**Comment by 2-k** [comment]
This is a major issue, I have a part that clearly needs support it's not going to get it with Cura 4.2, super annoying as this worked yesterday. The issue is clearly with the conical support function. Turned off support shows up, guess that's why it's still in the experimental section.

**Comment by Splodgeink** [comment]
Perfect print with 4.1! No changes to any profiles.

**Comment by Splodgeink** [comment]
![image](https://user-images.githubusercontent.com/53603374/62398906-04075780-b572-11e9-9192-daf43e73aa8a.png)

**Comment by Ghostkeeper** [comment]
In Cura 4.2, if you set Support Placement to Everywhere, does that:

1. Fix the problem, and
2. allow support to be removed from the model with reasonable ease?

I think setting the default to Everywhere is probably better from what we've heard people say. But we might need to adjust the Support Bottom Distance. So I have another question: What value for Support Bottom Distance gives the best results?

**Comment by 2-k** [comment]
The funky/no supports are caused by the conical support function. If you have it on then they 99% of the time won't show up. 
I got them to show up once when I set support to everywhere and 0° but never would slice supports in again. This is probably why it's still in the experimental section of the settings.

Sorry I didn't seem to post the solution for this. I figured it out shortly after posting this and must have put the answer on a different one I guess.

**Comment by 2-k** [comment]
All values should be based off your nozzle diameter and layer hight. For supports then you have to factor in removability, which is different for every printer, print and filaments. My philosophy is under extrude supports and over extrude infill.
