### ISSUE TITLE
[4.2.1] Materal price not calculating

### ISSUE THREAD

**Issue by Jord4n** [Ultimaker/Cura#6141]
Cura 4.2.1
Windows 10x64
Ender 3

Not getting a price calculation from my material.  
![curaprice](https://user-images.githubusercontent.com/13922382/62415375-aa3c7700-b5dd-11e9-8a18-ea692a0dc845.jpg)

**Comment by Ghostkeeper** [comment]
(For posterity, this problem is solved by filling in how much material is on one spool in the Filament Weight field.)
