### ISSUE TITLE
Missing Layers on Very Small Models

### ISSUE THREAD

**Issue by Kaigott** [Ultimaker/Cura#6144]
**Application Version**

4.2.1

**Platform**

Windows 10

**Printer**

Ender 3

[CE3_3DBenchy.zip](https://github.com/Ultimaker/Cura/files/3464532/CE3_3DBenchy.zip)

**Steps to Reproduce**

Add any model and make it very small.

**Actual Results**

Many layers disappear and chunks of the print float in the air

**Expected results**

Layers are displayed in the preview tab and it prints them like normal

**Additional Information**

![image](https://user-images.githubusercontent.com/35390498/62419562-a0476200-b637-11e9-9acb-e989a542099b.png)

**Comment by Block137** [comment]
This is normal. Your printer (Ender 3) is not capable of printing such small features.
You can enable "Print Thin Walls" to help with this.
