### ISSUE TITLE
All support types are surrounded by a wall - V4.2.1

### ISSUE THREAD

**Issue by Eyos** [Ultimaker/Cura#6145]
All support types now have a wall around them.
![Support issue](https://user-images.githubusercontent.com/6457448/62419952-550f6c80-b694-11e9-9716-ab64f3c7d925.jpg)
.

**Comment by fieldOfView** [comment]
See the "Support Wall Line Count" setting.

**Comment by nallath** [comment]
With support line count at 1:
![WithSupportLineCount](https://user-images.githubusercontent.com/3922611/62613222-55fd0400-b909-11e9-93ea-d40082f68c11.png)
With support line count at 0:
![NoSupportWallLineCount](https://user-images.githubusercontent.com/3922611/62613224-55fd0400-b909-11e9-827d-39dacc833b80.png)

**Comment by Eyos** [comment]
Thanks for the information.I never used this option, it was always set to 0. When opening files in 4.2, this option was set to 1 automatically, without notice.Regards,YossiOn Aug 7, 2019 12:50, Jaime van Kessel <notifications@github.com> wrote:With support line count at 1:

With support line count at 0:
