### ISSUE TITLE
Split -> Reload duplicates objects

### ISSUE THREAD

**Issue by TruculentMC** [Ultimaker/Cura#615]
Using the rightclick menu in Cura to split an STL into parts, then reloading all parts, results in massive duplication of models.

**Comment by Ghostkeeper** [comment]
There is no split into parts in this version of Cura. For issues with Cura 15.04, I'd like to refer you to [the original repository](https://github.com/daid/Cura). We'd like to keep the issues from these separate.

**Comment by nickthetait** [comment]
Is there a separate task for implementing "Split object into parts" feature in Cura 2?

**Comment by nallath** [comment]
Nope, not yet. It is something I'd love to get back though (ugh, time issues).
