### ISSUE TITLE
"Spiralizing outer contour" infill Issues

### ISSUE THREAD

**Issue by mouseyjonny** [Ultimaker/Cura#616]
Without the "Spiralize the outer contour" option selected, infill is calculated correctly,
When selecting "Spiralize the outer contour" option, the Infil does not generate. (See two images) .

No other option has been touched between these 2 screenshots.

Cura version 15.04.4 64 bit.
OS Linux Mint 17.3 64 bit.

![spiralize_unticked](https://cloud.githubusercontent.com/assets/16179055/12625223/c1472a78-c52a-11e5-8856-e932763a106e.png)
![spiralize_ticked](https://cloud.githubusercontent.com/assets/16179055/12625226/c39f638a-c52a-11e5-8b17-54aef536f5dc.png)

**Comment by fieldOfView** [comment]
Bugs for the 15.4 and older versions should be reported at https://github.com/daid/cura

In this particular case though I'll say that this is how spiralise is supposed to work. It is a bit of a hack intended for vase-like objects only.
