### ISSUE TITLE
Z Hop elevation not used between test extrusion and print area

### ISSUE THREAD

**Issue by sailorgreg** [Ultimaker/Cura#6172]
**Application version**
4.2.1

**Platform**
Windows

**Printer**
Creality Ender 3

**Reproduction steps**
Set Z Hop Height to 10. Looking at the GCode for the moves, it adds the Z Hop Height for every other move but not for the initial move to the print area after the test extrusion lines.

**Actual results**
The move between the test extrusion line and the print area happens at the initial print layer elevation.

**Expected results**
I would think that the move would be at the initial print layer elevation + Z Hop Height

**Additional information**
I added the comment 
"; !!! With Z Hop Height set to 10, shouldn't this be 10.3? It keeps running into my previously printed structure !!!" 
on the line I believe is in error.

[CE3_F Letter.gcode.txt](https://github.com/Ultimaker/Cura/files/3476283/CE3_F.Letter.gcode.txt)

**Comment by Vandrasc** [comment]
Devs CURA-6718.

**Comment by LipuFei** [comment]
Fixed via https://github.com/Ultimaker/CuraEngine/pull/1112
