### ISSUE TITLE
Cura error every time It starts 

### ISSUE THREAD

**Issue by thomllama** [Ultimaker/Cura#6184]
Cura wont start simply, I get this error every time.  done everything I can think of including deleting older versions wiping all ultimaker/cura files from the computer, downloading fresh Cura installer.. nothing  Mac OSX 10.14.6
![Screen Shot 2019-08-09 at 8 58 41 AM](https://user-images.githubusercontent.com/22606587/62781920-07757400-ba87-11e9-8c75-d3092ad5c7bd.png)

**Comment by nallath** [comment]
If you don't copy the actual detailed crash report, I don't know which one you had. We mean it when we make the crash reports anonymous.

**Comment by fieldOfView** [comment]
Seems to have been resolved here:
https://community.ultimaker.com/topic/29010-ultimaker-cura-42-released/?do=findComment&comment=244856

**Comment by LipuFei** [comment]
Thanks @fieldOfView ! I'll close this issue.
