### ISSUE TITLE
Holes in slicing

### ISSUE THREAD

**Issue by techfreak111** [Ultimaker/Cura#6190]
**3.5.0**

**Windows**
Nvidia Quadro M500M, Nvidia Quadro M550

**Anycubic I3 Mega**

**2 different Computers, the same Version, 2 different slices**

**On 1 Computer everything is fine, on the other i have the holes above und underneath 1 letter. I have tried an update on the pc with the holes, but on the actual Version of cura, i think something with 4. i had the same failure with the holes**

**what changes i may make in the Options to have not the holes in the slicing?**

![defqon-1](https://user-images.githubusercontent.com/53973555/62822666-e431ee00-bb86-11e9-9298-bdd1c24dea01.JPG)

![defqon-2](https://user-images.githubusercontent.com/53973555/62822708-60c4cc80-bb87-11e9-938c-d9cf32738b0c.JPG)

**Comment by Vandrasc** [comment]
Hi @techfreak111 , could you please share your project file with us so we a have a look at your configurations and what settings you have customized. Use the same configuration as in the one where you encounter the holes in the model then go to File>Save...

Thank you!

**Comment by rburema** [comment]
If it's the exact same file, with the exact same settings, it _might_ be a visual artifact. Are the drivers of your video card up to date on both machines?

**Comment by Ghostkeeper** [comment]
Looks like Coasting to me. Did you accidentally enable coasting?

**Comment by Liger0** [comment]
I also had that weird issue on cura 3.6, and there wasn't coasting.
