### ISSUE TITLE
[4.2.1] I can not change nozzel. It is constant 0.4 mm

### ISSUE THREAD

**Issue by SirWinni** [Ultimaker/Cura#6199]
**Application version**
4.2.1

**Platform**
Window 10.

**Printer**
Ultimaker 2+

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by LipuFei** [comment]
@SirWinni Could you fill in the bug report form and let us know:
 - Which platform/OS you are on?
 - Which printer do you have?
 - What did you do to reproduce this issue?
 - What did you expect and what happened instead?

**Comment by Ghostkeeper** [comment]
The user did fill in some of the template but didn't remove the `<!--` and `-->` so it was not displayed. I made the parts that were filled in visible.

However I'm not able to reproduce this. Here is the UM2+ with the nozzle size changed to 0.8mm:

![Screenshot from 2019-08-14 12-48-23](https://user-images.githubusercontent.com/2448634/63015667-19895500-be81-11e9-8a9f-bec40c17031f.png)

**Comment by SirWinni** [comment]
OK. they use a different route.
That's how it works for me too.
But I did it differently (see attached picture) and it does not work that way.
The value set does not change.
![Cura4 2 1](https://user-images.githubusercontent.com/30130057/63040587-077dd580-bec6-11e9-8ce3-f2e96a55ba2c.png)

**Comment by nallath** [comment]
This is a known bug for 4.2.1 (and has been fixed for 4.3). The workaround is to change the nozzle size through the menu bar below that.

**Comment by Ghostkeeper** [comment]
(See also https://github.com/Ultimaker/Cura/issues/6086).

**Comment by SirWinni** [comment]
Thank you very much.
