### ISSUE TITLE
Remove limit of 3000 on Density (kg/m3) preference

### ISSUE THREAD

**Issue by czucker** [Ultimaker/Cura#62]
Metal infused filaments can exceed this limit, making it impossible to get accurate printing stats. BronzeFill, for instance, is 3.99 g/cm3.

It would be great if the 3000 limit was either removed, or increased to account for newer filaments.

**Comment by awhiemstra** [comment]
Since we do not have such a setting currently this bug is invalid for this Cura.

**Comment by czucker** [comment]
See the attached image for the setting that I'm speaking about:
![curadensity](https://cloud.githubusercontent.com/assets/5024630/8357490/2127b5c2-1b29-11e5-83cf-f6b2a22cc1f9.jpg)

**Comment by czucker** [comment]
I hadn't realized that this setting was not present in 15.06. Will there be a place to enter filament density? If not, then how can filament volume be calculated?

**Comment by nallath** [comment]
Density has nothing to do with volume. Density is used to calculate weight (by multiplying it by volume).
