### ISSUE TITLE
download fail？

### ISSUE THREAD

**Issue by robin1015** [Ultimaker/Cura#6212]
To upgrade and install the latest version of cura（window7 64）, the download of installation files always fails. I have tried for several days. Version: Ultimaker Cura 4.2.1, etc. Address: Shanghai, China.

**Comment by LipuFei** [comment]
Hi @robin1015 , our download is now on GitHub, which is hosted on AWS US. It can be blocked by "the firewall". Could you checkout Ultimaker's CN site see if that works for you?

http://ultimaker.cn/Ultimaker-cura-software/Download

**Comment by LipuFei** [comment]
BTW, I asked some of my friends in Shanghai to test the links on both GitHub and ultimaker.cn. Both worked for them. Could you try it again?

**Comment by Ghostkeeper** [comment]
Ultimaker's website has a provider specific to China to prevent the issue of the "Great" Firewall. Download from ultimaker.com rather than from Github, I'd advise.

**Comment by robin1015** [comment]
thank very much。https://ultimaker.com/en/products/ultimaker-cura-software，，The website I used in the past is not available in China. The website you gave is OK. Thank you very much.

**Comment by robin1015** [comment]
ultimaker.cn ok

**Comment by robin1015** [comment]
> Ultimaker's website has a provider specific to China to prevent the issue of the "Great" Firewall. Download from ultimaker.com rather than from Github, I'd advise.

http://ultimaker.cn/Ultimaker-cura-software/Download  ok            
thank you
