### ISSUE TITLE
[4.2.1] Print area on Ender 3 incorrect

### ISSUE THREAD

**Issue by ChoccyHobNob** [Ultimaker/Cura#6227]
**Application version**

4.2.1

**Platform**

macOS 10.14.6

**Printer**

Creality Ender 3

**Reproduction steps**

Try to print a model with a large footprint. I used the Buildplate_square_200x200mm_Complete_set_-_3DBenchy.com.stl from 
https://www.thingiverse.com/thing:1085472

**Actual results**

Cura refuses to slice, giving a message about nothing fitting on the build volume.

**Expected results**

Cura should slice OK. the 198x198 model I used is well under the 220x220 build plate size.

**Additional information**

I changed the printer settings X & Y to 235 (the actual size of the Ender3 bed), assuming the print head settings were being subtracted from the build volume instead of being added to it and I got Cura to slice however the print doesn't sit in the center of the bed
![IMG_2076](https://user-images.githubusercontent.com/12753/63261041-1ce95b80-c248-11e9-840a-774ddb2efdf0.jpeg)
.

**Comment by nallath** [comment]
You have a skirt enabled. This also takes up some space. This is represented by the dark borders in the print area.

**Comment by ChoccyHobNob** [comment]
Thank you!
