### ISSUE TITLE
[4.2.1 & 4.1.0]Cura Slicing Adds Block Of Material To Model When Rotated

### ISSUE THREAD

**Issue by xantos117** [Ultimaker/Cura#6232]
**Application version**
[4.2.1] and [4.1.0] both have the error occur

**Platform**
Windows 10 x64, issue has occurred on 3 machines, each with different hardware. 

**Printer**
Ultimaker-007eec

**Reproduction steps**
1. Import skull stl into Cura
2. Rotate skull model to have flat top as base of print
3. Slice and preview model

**Actual results**
Slicing generates a large filled block of material within the skull that isn't part of the model. Additionally, a number of layers are missing. This second part is rotation invariant, and the missing layers are always parallel to the printing surface. 
These errors occur whether support material is selected or not, irrespective of the material.

**Expected results**
The sliced skull is the same as the stl model, without added material. All slices are present.

**Additional information**
Zip of stl file to be printed: [006 trimmed mandible removed 2 - skull base - support arch top removed - sealed.zip](https://github.com/Ultimaker/Cura/files/3521558/006.trimmed.mandible.removed.2.-.skull.base.-.support.arch.top.removed.-.sealed.zip)
Zip of Cura Project: 
[UMS5_006 trimmed mandible removed 2 - skull base - support arch top removed - sealed.zip](https://github.com/Ultimaker/Cura/files/3521563/UMS5_006.trimmed.mandible.removed.2.-.skull.base.-.support.arch.top.removed.-.sealed.zip)
Missing print layers: 
![Cura skull preview missing layers](https://user-images.githubusercontent.com/1074410/63364349-64a0dd80-c343-11e9-8a9d-5e25c3dbb8ca.png)
Skull positioning: 
![Cura skull positioned](https://user-images.githubusercontent.com/1074410/63364375-708c9f80-c343-11e9-811a-eace4c7839ff.png)
Skull after slicing, notice the filled section in the center: 
![Cura skull preview](https://user-images.githubusercontent.com/1074410/63364407-7e422500-c343-11e9-93f0-bd751d740080.png)

Filled block doesn't appear when skull rotated to other orientations, but missing layers appear no matter what. 

This skull stl is a modified version of a larger skull that I don't believe I can easily paste in to this report. I modified it by passing rectangular prisms through the original and using a boolean subtraction to remove material. Once parts were separated, I could remove them from the model, and they were thus deleted. Inspection of verticies and faces in Blender show no oddities that I can figure out would cause this issue.

**Comment by smartavionics** [comment]
The model has problems. It is unlikely to be sliced well until those problems are fixed. Sorry, I don't know how you would do that.

![Screenshot_2019-08-20_22-34-55](https://user-images.githubusercontent.com/585618/63386380-d6f0dc80-c39a-11e9-96ef-655b5849e934.png)

**Comment by Ghostkeeper** [comment]
The model is open on the inside. You can see the open insides where there is just a sheer cut out from the model. It is ambiguous then what parts of the model are inside the model and what parts are outside. Cura cannot fix this for you, because it doesn't know what you want printed, though it tries to mend it as good as it can.

There is nothing we can realistically do to prevent this. Mesh fixing is outside of Cura's scope. Sorry!
