### ISSUE TITLE
Non planar printing

### ISSUE THREAD

**Issue by kyjak** [Ultimaker/Cura#6249]
Slicer SW introduced non planar printing as seen at https://www.reddit.com/r/3Dprinting/comments/ctxns4/nonplanar_3d_printing_functionality_added_to/
this is such a cool feature, Cura should adopt the code and follow.

I'd like to have an option to do non-planar slicing in Cura.

All printers and users are affected.

**Comment by mbartlett21** [comment]
Duplicate #5980
