### ISSUE TITLE
Travel moves unnecessarily crossing walls

### ISSUE THREAD

**Issue by larsch** [Ultimaker/Cura#6251]
**Application version**: 4.2.1

**Printer**
Custom FDM

[travel_moves.3mf.zip](https://github.com/Ultimaker/Cura/files/3537360/travel_moves.3mf.zip)

**Reproduction steps**
Set "Combing" to "Not in skin" or "Inside infill".

**Actual results**
Cura generates travel moves with many jerks, crossing over skin instead of staying inside print when clearly possible.

**Expected results**
Normal travel moves without jerks

**Additional information**
Default slicing where "pointy" travel moves are visible everywhere:

![travel_moves](https://user-images.githubusercontent.com/15712/63639865-474c7600-c699-11e9-84c0-0ced395cb06a.jpg)

Example: After printing outer wall, nozzle coasts a bit forward, then jerks outside print, crosses print to other hole in print, then jerks back to next outer wall being printing, even though the inside is fully connected. 

![travel_moves_2](https://user-images.githubusercontent.com/15712/63639893-8d093e80-c699-11e9-84dd-0606691c2605.png)

![image](https://user-images.githubusercontent.com/15712/63639928-23d5fb00-c69a-11e9-97e7-a6f732c8d5a8.png)

**Comment by smartavionics** [comment]
Turn off the avoid printed parts when travelling setting.

**Comment by larsch** [comment]
Turning off _Avoid Printed Parts_ does prevent the jerk travel moves. OK for this print.

**Comment by Ghostkeeper** [comment]
Yeah, looks buggy to me. I can see that it's combing correctly along the first inner wall, but when it needs to separate from that wall it decides to do a `moveOutside` which crosses the wall, and then makes a straight run for the `moveOutside`-location of the destination because it sees that it needs to cross the outer wall anyway (because it's now outside). It shouldn't do that `moveOutside` there.

**Comment by smartavionics** [comment]
Yes, it's because it can't comb within the skin. Notice that the spikes don't occur on the layers that don't have skin.

**Comment by smartavionics** [comment]
It would be better if it did a non-combed direct travel move with retraction (and, hopefully, z-hop to avoid wrecking the skin).

**Comment by Liger0** [comment]
I also have the nozzle going into empty areas going from start point to the ending one on a straight line instead of staying within the model on cura 4.3 beta, no matter if I use non in skin, in infill or all.

**Comment by smartavionics** [comment]
Please provide the .3mf file.

**Comment by Liger0** [comment]
Literally any model does it.

**Comment by smartavionics** [comment]
Unless you provide an example, I cannot help.

**Comment by Liger0** [comment]
[Combing.zip](https://github.com/Ultimaker/Cura/files/3614107/Combing.zip)

**Comment by smartavionics** [comment]
Thanks for the file. I have sliced it but can't see an obvious problem yet, please say what layer is causing the issue and maybe show an image of the problem. Thanks.

**Comment by Liger0** [comment]
I am not very good understanding everything combing does, but I think the travel on the top are not supposed to be there.
![combing](https://user-images.githubusercontent.com/20385116/64925900-5daca400-d7f7-11e9-8e8f-b275e0a05f6b.png)

**Comment by smartavionics** [comment]
Ah, I see. Thing is, I don't get those travels when I slice with my cura. I think I fixed the bug that causes them a long time ago but the cura developers have not yet incorporated the fix. That was https://github.com/Ultimaker/CuraEngine/pull/973.

![Screenshot_2019-09-15_20-22-00](https://user-images.githubusercontent.com/585618/64926544-7d8f9800-d7f6-11e9-94c4-82e1993c5253.png)

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
