### ISSUE TITLE
[4.2.1] Speed legend disappears when clicking

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6258]
**Application version**
4.2.1

**Platform**
Win10  x64

**Printer**
Cr-10S, probably any tho.

**Reproduction steps**
After slicing, click on the model

**Actual results**
The speed legend disappears.

**Expected results**
No difference in the speed legend

**Additional information**
Some other click in different parts make it reappear
https://www.youtube.com/watch?v=apVg7FpoSuA&feature=youtu.be

**Comment by Ghostkeeper** [comment]
Yup, easy to reproduce. Good eye!
