### ISSUE TITLE
Brim distance / gap

### ISSUE THREAD

**Issue by Xtrudor** [Ultimaker/Cura#6260]
**Is your feature request related to a problem? Please describe.**
Brim is hard to remove.

**Describe the solution you'd like**
Could you please add a Brim Distance / Gap option similar to the Skirt Distance and Raft Air Gap options so that we can add a little distance to make it easier to remove the brim.

**Comment by Liger0** [comment]
That's the brim purpose. 😕

**Comment by smartavionics** [comment]
Hello @Xtrudor , my Cura builds already have that feature. You can find builds for Linux and Windows at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. They can be installed alongside the Ultimaker releases without causing any problems.

I find it useful to have a little gap sometimes as that gives you the thermal benefit of having a brim without the hassle of removing it (especially with PLA).

**Comment by Ghostkeeper** [comment]
Is there any reason why you wouldn't use a skirt instead, then?

**Comment by smartavionics** [comment]
> Is there any reason why you wouldn't use a skirt instead, then?

Skirts are OK if the outline is convex, not so good when the outline is concave as they then no longer hug the part at a constant distance.

**Comment by Xtrudor** [comment]
Exactly. Most parts we print have irregular ouline that a skirt won't stick to.

**Comment by smartavionics** [comment]
So here's an example of skirt vs brim. Both are using a gap of 0.25mm. 

![Screenshot_2019-08-29_16-12-18](https://user-images.githubusercontent.com/585618/63952668-e1386800-ca77-11e9-98df-cc61dfecdc60.png)

![Screenshot_2019-08-29_16-11-44](https://user-images.githubusercontent.com/585618/63952669-e1386800-ca77-11e9-893c-0bc68e532f7b.png)

**Comment by smartavionics** [comment]
This part is printed in PLA and the skirt is 0.5mm from the outline. It's a very solid part with 90% infill. If I don't use that skirt the sharper corners on the sides bend upwards more than if I do use the skirt. In this example a skirt can be used rather than a brim.

![Screenshot_2019-08-29_16-22-14](https://user-images.githubusercontent.com/585618/63953578-856ede80-ca79-11e9-8596-2db9439a3a70.png)

**Comment by smartavionics** [comment]
Given that I have already done the work for this, I'll just submit the PRs anyway.

**Comment by Liger0** [comment]
Another thing I think would work even better is to to a "pointy" brim, so it isn't linear but attaches every few fraction of mm, like when a page is meant to be cut from a book so it isn't completely solid with it. So the brim is weavy.

**Comment by nallath** [comment]
Just merged the PR's, so this can be closed.

**Comment by Firedrops** [comment]
Was about to suggest this feature, I've been working with skirt distance=0.12mm until I ran into prints with weird base shapes.

May I know whether this is in 4.4.1, and if so, how to find this setting?

**Comment by smartavionics** [comment]
No, it is not in 4.4.1 but should arrive in 4.5. In the meantime, you can install one of my Cura builds which you can find at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md file there for more information.
