### ISSUE TITLE
[4.2.1] Cura adding gcode after my end gcode

### ISSUE THREAD

**Issue by Pugsworth** [Ultimaker/Cura#6261]
**Application version**
4.2.1

**Platform**
Windows 7

**Printer**
Ender 3/5

**Reproduction steps**
Print anything

**Actual results**
```
M82 ;absolute extrusion mode
M104 S0
;End of Gcode
```
is added at the end of my gcode no matter what.

**Expected results**
No gcode should be added at the end of my gcode.

**Additional information**
I use gcode to toggle the power of my printer. This is simply accomplished using the standard gcode of M81. My printer will automatically turn back on because Cura is adding gcode to set the temperature of my hotend to 0, which I already have in my end gcode.

My end gcode is :
```
; Ender 5 Custom End G-code

G4 ; Wait

M220 S100 ; Reset Speed factor override percentage to default (100%)
M221 S100 ; Reset Extrude factor override percentage to default (100%)

G91 ; Set coordinates to relative

G1 E-2 F2700 ; Retract a bit
G1 E-2 Z0.2 F2400 ; Retract and raise Z
G1 X5 Y5 F3000 ; Wipe out
G1 Z10 ; Raise Z more

; G1 F3000 Z20 ; Move Z Axis up 20 mm to allow filament ooze freely
G90 ; Set coordinates to absolute

M300 P50 S260 ; Play Finished Tone
M300 P50 S260 ;

G1 X0 Y0 ; Present print
M106 S0 ; Turn off fan
M104 S0 ; Turn off hotend
M140 S0 ; Turn off bed

; G1 X0 F3000 ; Move Extruder
; G1 Z200 F3000 ; Move Heat Bed to the bottom

M84 X Y E ; Disable all steppers but Z

M28 X10 Y10 ; Move close to home


M81 ; Power off
```

**Comment by fieldOfView** [comment]
I think the quickest way to work around this issue is a Search & Replace gcode postprocessing script (See Extensions -> Post process gcode) to remove the offending lines.

Replace ```M82 ;absolute extrusion mode\nM104 S0\n;End of Gcode``` with an empty string.

**Comment by Ghostkeeper** [comment]
I guess it should leave out the `M104 S0` if there is another `M104` in the end g-code?

The other command, `M82`, is there because of the g-code flavour not matching up with the preference of relative vs. absolute g-code. For RepRap flavour, the g-code should be relative. For the rest, it should be absolute. If the printer settings say otherwise, it'll reset to the flavour's specification at the end of the print. However since the user wants to specify the g-code coordinates in the end g-code also relative then (if the machine setting says relative), this needs to happen after the end g-code. Perhaps we can have it leave out the command if the end g-code switches to absolute as well. It becomes very magical then though.

**Comment by Ghostkeeper** [comment]
We've discussed this with the team and decided that we can't justify spending time on this soon due to the very specific case involved. The preferred solution would be to check the end g-code whether it already contains `M104` or `M109` and leave out the `M104` command if it does, and similarly for `M82`.

For now, I hope that fieldOfView's workaround suffices.

**Comment by Pugsworth** [comment]
Thank you for taking the time to look at this issue.
fiieldOfView's workaround would appear to work for now.

Worst case, I could try to make an octoprint plugin to ignore that specific set of commands back to back.

**Comment by JohnTasto** [comment]
There are also a couple lines added before the end g-code:

```gcode
M140 S0
M204 S4000
```

My end g-code contains a `M140 S70` to cool the bed just enough to remove PETG without warping while saving time warming up for the next print. The only semi-meaningful negative impact of briefly setting the temp to 0 first is a blip on the OctoPrint temp chart, but maybe `M140` and `M204` should be added to the list if this issue ever gets priority.

**Comment by vaderag** [comment]
I'd like to chime in on this as it's causing me issues with octoprint.

This is added to the end of my gcode no matter what which causes octoprint to think that the print has failed every time
> M82 ;absolute extrusion mode
> M104 S0
> ;End of Gcode

This is because i have an M81 in my end code which powers off the machine, and because it isn't the last line things are going awry.

This is a huge bug imho as if you display end code a user should not need to second guess that additional code is being added afterwards.

**Comment by xbk666** [comment]
I am having the same issue. Previous it worked well and no additional gcode was added after my end gcode. However I don't know what I did and suddenly there are two new lines just like what was described as others. Additionally, I also have several new lines like:
`;SETTING_3 {"global_quality": "[general]\\nversion = 4\\nname = Prime Quality\\n
;SETTING_3 definition = creality_ender3\\n\\n[metadata]\\ntype = quality_changes
;SETTING_3 \\nquality_type = standard\\nsetting_version = 17\\n\\n[values]\\nadh
;SETTING_3 esion_type = skirt\\nbridge_settings_enabled = True\\ncarve_multiple_
;SETTING_3 volumes = True\\nmaterial_bed_temperature = 40\\nmaterial_bed_tempera
;SETTING_3 ture_layer_0 = 50.0\\nsupport_enable = False\\nsupport_structure = no
;SETTING_3 rmal\\nsupport_type = everywhere\\n\\n", "extruder_quality": ["[gener
;SETTING_3 al]\\nversion = 4\\nname = Prime Quality\\ndefinition = creality_ende
;SETTING_3 r3\\n\\n[metadata]\\ntype = quality_changes\\nquality_type = standard
;SETTING_3 \\nintent_category = default\\nposition = 0\\nsetting_version = 17\\n
;SETTING_3 \\n[values]\\nbridge_fan_speed_2 = 100\\nbridge_fan_speed_3 = 100\\nb
;SETTING_3 ridge_skin_density_2 = 100\\nbridge_skin_density_3 = 100\\nbridge_ski
;SETTING_3 n_material_flow = 70\\nbridge_skin_material_flow_2 = 90\\nbridge_skin
;SETTING_3 _material_flow_3 = 90\\nbridge_wall_material_flow = 70\\nclean_betwee
;SETTING_3 n_layers = False\\ncool_lift_head = True\\ncool_min_layer_time = 10\\
;SETTING_3 nfill_perimeter_gaps = everywhere\\nfilter_out_tiny_gaps = True\\nhol
;SETTING_3 e_xy_offset = 0.05\\ninfill_pattern = grid\\ninfill_sparse_density = 
;SETTING_3 20\\ninitial_bottom_layers = 3\\nmaterial_flow = 90\\nmaterial_flow_l
;SETTING_3 ayer_0 = 90\\nmaterial_print_temperature = 215\\nmeshfix_maximum_reso
;SETTING_3 lution = 0.1\\nmultiple_mesh_overlap = 0\\nraft_base_line_spacing = 2
;SETTING_3 \\nretract_at_layer_change = True\\nretraction_prime_speed = 25.0\\nr
;SETTING_3 etraction_speed = 50.0\\nroofing_layer_count = 1\\nskin_outline_count
;SETTING_3  = =0 if top_bottom_pattern == 'concentric' and top_bottom_pattern_0 
;SETTING_3 == 'concentric' and roofing_layer_count <= 0 else 1\\nskirt_gap = 15\
;SETTING_3 \nsmall_hole_max_size = 0.0\\nsupport_angle = 75\\nsupport_pattern = 
;SETTING_3 lines\\ntravel_compensate_overlapping_walls_0_enabled = True\\nwall_t
;SETTING_3 hickness = 1.2\\nwipe_retraction_prime_speed = 25\\nxy_offset = 0\\nx
;SETTING_3 y_offset_layer_0 = -0.15\\nz_seam_corner = z_seam_corner_inner\\nz_se
;SETTING_3 am_type = back\\n\\n"]}
`
I tried to uninstall some plugins that I think might add the additional gcode, Arc Welder & Export HTML Cura Settings, but nothing happens.

Any help is greatly appreciated.

**Comment by Ghostkeeper** [comment]
Yes, Cura also puts the profile changes at the end of the g-code in comments. This can't currently be disabled. But should also be ignored by the printer.

**Comment by LouiseTGUK** [comment]
This is also creating an issue for the Anycubic Vyper, after these commands are executed it leaves the motors  enabled and prevents the printer from turning off the motherboard  fans after a print is finished..

It would appear the search and replace workaround no longer works as the gcode output is not changed, unless i am doing something wrong with the search!

**Comment by mistic100** [comment]
> This is also creating an issue for the Anycubic Vyper, after these commands are executed it leaves the motors  enabled and prevents the printer from turning off the motherboard  fans after a print is finished..
> 
> 

It still work, just don't make the same mistake as I did : you must not write "\n" literally, but an actual line break.

The easiest way is to copy paste all the lines at once from an existing gcode file

The line break will be invisible but still here.

It is really not user friendly....

**Comment by fieldOfView** [comment]
> you must not write "\n" literally, but an actual line break.

The literal `\n` string works if you tick the "Use Regular Expressions" checkbox.
