### ISSUE TITLE
[master] support bottom distance now ignored

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#6264]
**Application version**

**Platform**

Linux (probably any)

**Printer**

Kossel Mini (probably any)

**Reproduction steps**

Profile uses support with non-zero bottom distance.

**Actual results**

Support extends all the way down to the model, the bottom distance is ignored.

**Expected results**

Bliss.

**Additional information**

The commit that broke this is https://github.com/Ultimaker/CuraEngine/commit/edc6706e4c530c62a0ed3216b263afc5c8fa4c1c.

If I revert that commit, I get gaps below my support again. Note that I am using a support stair step height of 0.

This is how it should look...

![Screenshot_2019-08-27_09-06-40](https://user-images.githubusercontent.com/585618/63752945-0c6d5c80-c8aa-11e9-9fab-da7ce0d89313.png)

**Comment by smartavionics** [comment]
I realise that in the above image the support on the right is very narrow at the bottom and so if the z distance is made 0 it won't touch the model below anyway but I can assure you that this bug is real and increasing the z-distance will not have any affect at the bottom of the support.

**Comment by smartavionics** [comment]
Here's what I mean, the z-distance is now set to 1mm top and bottom.
![Screenshot_2019-08-27_10-38-00](https://user-images.githubusercontent.com/585618/63760220-cf5b9700-c8b6-11e9-9329-0b6d2581e359.png)

**Comment by smartavionics** [comment]
Interestingly, if the support is expanded horizontally enough so that it now touches the build plate, the z-gap at the bottom does appear...

![Screenshot_2019-08-27_15-02-35](https://user-images.githubusercontent.com/585618/63777979-efea1800-c8db-11e9-8928-04cf2676a2d6.png)

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
