### ISSUE TITLE
New Visual Layout is Obscuring Elements of Interface

### ISSUE THREAD

**Issue by ficklecycler** [Ultimaker/Cura#6275]
**Is your feature request related to a problem? Please describe.**
The new "floating windows" direction that cura is going in is visually cluttered and obscuring elements of the interface. Without the ability to push the various windows to the edges of the screen, we end up with wasted space all around each box. This makes the interface feel claustrophobic and messy. Further, the print settings box can now cover elements on the far left and right. This is annoying mainly when you are scrolling through the layer by layer view as the print settings box can totally cover the layer sliding bar. It's just not good design to allow elements to block one another. The entirety of cura's core functionality should be visible on one plane, not layered and windowed.

**Describe the solution you'd like**
Save interface space and create a more organized look by allowing us a setting where the windows don't float but stay tight to the left or right of the interface. Or just go back to the design direction of pre 4.0

**Describe alternatives you've considered**
Alternatively you could move the layer view slider so that it is on the bottom horizontally instead of vertical on the right side. That way it might not get covered by the print settings window

**Affected users and/or printers**
This will benefit all cura users.. I think! Thanks for listening to your users!--> 

**Additional context**

**Comment by fieldOfView** [comment]
Have you tried the Sidebar GUI Plugin from the Marketplace?

**Comment by fieldOfView** [comment]
I’m glad you like it

**Comment by rburema** [comment]
You can also drag (and resize) the settings pane.

**Comment by GregValiant** [comment]
I'm cleaning house.
Given the SideBarGUI and TabbedSettings plugins - Is this still relevant?  Can I close this?
