### ISSUE TITLE
[2.1] Uranium translations in Cura tree

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#628]
I was wondering why no translations were uploaded to Uranium so far and then by an accident I found them here.
But I'm sure you wanted to place them here: https://github.com/Ultimaker/Uranium/tree/2.1/resources/i18n/ :smile:

**Comment by Ghostkeeper** [comment]
Yeah, that's right :P The new languages are also not yet in the menu, which I'm going to have to take a look at.

**Comment by Ghostkeeper** [comment]
Fixed in the 2.1 branches of Cura, Uranium and cura-binary-data.

**Comment by thopiekar** [comment]
Thanks :+1:
