### ISSUE TITLE
Right click --> Crash

### ISSUE THREAD

**Issue by Knusperhas** [Ultimaker/Cura#6280]
**Application Version**
4.2.1

**Platform**
Windows 7 Home Premium 64 Bit

**Printer**
Custom Printer Standard Profile

**Steps to Reproduce**
1. I can start Cura, slice and everything.
2. I make a right click or try to open the menu on top (File, Edit, View,...)

**Actual Results**
Cura crashes and Windows is closing the program. 

**Expected results**
The Pop Up menu from the right click should open ...
 or the File menu should open

**Additional Information**
The Slicer settings on the right have no problem
It's a new installed windows on an old laptop. 
All Drivers are Updated by Dell Update Software.
All Windows Updates installed. 
Open GL until Version 2.1 is supported.

(I had Cura 3.5.1 running on this machine before new installation of Windows.)

I tried to remove Cura and install the 3.5.1 but it's the same behavior, so i upgraded back to 4.2.1...

Also tried all without antivirus and in administrator mode.

I installed Java and adobe flash Player, but nothing changes a thing.
I hope you understand what i mean and can help me out. 
If you need further information please ask for it, i would try my very best.

[cura.cfg.txt](https://github.com/Ultimaker/Cura/files/3556900/cura.cfg.txt)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/3556921/DxDiag.txt)
[curaRoaming.zip.txt](https://github.com/Ultimaker/Cura/files/3556908/curaRoaming.zip.txt)
[cache.zip.txt](https://github.com/Ultimaker/Cura/files/3556909/cache.zip.txt)

**Comment by LipuFei** [comment]
@Knusperhas The logs files unfortunately don't contain very useful information. Is it possible for you to create a crash dump when that happens? Could you email it to me l.fei@ultimaker.com? The crash dump file should be a `.DMP` file. Thanks.

**Comment by Knusperhas** [comment]
I sent you an private email with .dmp file.

**Comment by LipuFei** [comment]
It seems to have something to do with OpenGL. From your `DxDiag.txt` file, looks like you have an Intel graphics card. Do you have the latest Intel graphics driver installed? Could you also try using the compatibility mode? You can enable it via the preferences dialog (see screenshot below). And you also need to restart Cura.

![image](https://user-images.githubusercontent.com/2630468/64207683-6fa85180-ce9d-11e9-8979-565880054014.png)

**Comment by Knusperhas** [comment]
I am using the latest Driver. I checked it a couple of times. 
Sorry but i can Not Open the settings window because it is in these top Menü, where Cura also Crashes. 
Is it possible to Change it in some config File?
I tried an openGL Test program and Out of it i got the Info that OpenGL until 2.1 is supported

**Comment by LipuFei** [comment]
Yes, you can change it in the configuration file. You can find it in `C:\Users\<your-usernamer>\AppData\Roaming\cura\4.2\cura.cfg`. You can open it with a text editor and add the line below in the `[view]` section:

```
force_layer_view_compatibility_mode = True
```

![image](https://user-images.githubusercontent.com/2630468/64230351-f0426e80-ceec-11e9-964a-359965b7743f.png)

**Comment by Knusperhas** [comment]
It's working correctly in new Cura Version
