### ISSUE TITLE
Slicer adds extra 'top/bottom layer' in middle of model

### ISSUE THREAD

**Issue by jcjveraa** [Ultimaker/Cura#6287]
**Application version**
4.2.1

**Platform**
Windows 10 
**Printer**
Anycubic mega i3

**Reproduction steps**
Slicing my model with some 'recessed' letters at any of the 'built in' settings.

**Actual results**
From layer 134 Slicer adds 5 'top/bottom' layers (= 0.5 mm) underneath where some 'recessed' lettering will be printed, and then from layer 139 fills over that same area and the rest of the top with another 0,5mm completely filled top/bottom layers, making the earlier layers disappear and seemingly add no real value over just printing infill. If it is for strengthening, while not needed, it should at least then use a high printing rate. 

**Expected results**
No extra top/bottom layers in the middle of the model. 
[extra_top_bottom.zip](https://github.com/Ultimaker/Cura/files/3563277/extra_top_bottom.zip)

Images showing **feedrate** (blue 20mm, orange 50mm)
layer 133
![133](https://user-images.githubusercontent.com/3942301/64073838-c34f4b00-cca3-11e9-992b-09f3151d8625.PNG)
134
![134](https://user-images.githubusercontent.com/3942301/64073843-cb0eef80-cca3-11e9-97c5-7cd7ab3c6793.PNG)
139
![139](https://user-images.githubusercontent.com/3942301/64073845-d235fd80-cca3-11e9-87c9-981c68abb82a.PNG)
146
![146](https://user-images.githubusercontent.com/3942301/64073848-d7934800-cca3-11e9-9516-fbeb08e4d6ec.PNG)

**Comment by smartavionics** [comment]
Your profile specifies 12(!) top layers so it's doing exactly what you asked for. If you count them you will see that there are 12 layers under the letters.

**Comment by jcjveraa** [comment]
Ah :)
Makes some sense I suppose, being equal to the 1.2 mm wall thickness?
But why does it then not start with complete layers but rather tracing the
outline of the letters?

Note, forgot to mention, this is a fairly hypothetical case - I can print
the object without the lettering to get rid of the problem.

Op zo 1 sep. 2019 11:08 schreef Mark Burton <notifications@github.com>:

**Comment by smartavionics** [comment]
> But why does it then not start with complete layers but rather tracing the
outline of the letters?

Because then the areas around the letters would have more than 12 layers (17 in your example).

**Comment by jcjveraa** [comment]
Ok, case solved, but still it feels slightly unintuitive.

Op zo 1 sep. 2019 11:15 schreef Mark Burton <notifications@github.com>:
