### ISSUE TITLE
Time Lapse

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#6295]
Hallo,

I use Cura 4.2.1 and Repetierserver 0.9.2 with Raspberry3

If i use Time lapse with the Trigger @make_snapshot for Repetier , Cura adds an additional comment in the Gcode .  " @make_snapshot;Snap Photo "
But Repetier dont like this and make no snapshot.

**Comment by fieldOfView** [comment]
You can use a Find and Replace gcode postprocessing script to remove the comment.

**Comment by Ghostkeeper** [comment]
In general, g-code parsers should ignore comments like `;Snap Photo`. I'd say that Repetier is in the wrong here.

**Comment by lwbsbde** [comment]
if I put a space after the command, it works.

**Comment by Ghostkeeper** [comment]
In that case, I'll make the post-processing script put a space between the command and the comment. Thanks for the debugging!
