### ISSUE TITLE
Crash when opening Web Browser

### ISSUE THREAD

**Issue by nickthetait** [Ultimaker/Cura#63]
Version:
Cura 15.05.95

Specs:
Windows 8.1

Where:
Help dropdown menu

Actions:
Click either "Show Online Documentation" or "Report a Bug"

Behavior:
Cura crashes. Windows gives a popup: "Cura.exe has stopped working"
No new log messages on the command line.
Web browser is correctly opened.

Expected behavior:
Cura continues to function normally

**Comment by nickthetait** [comment]
A side effect of this is any printers that I added/configured during this session get deleted.

Open cura, add printer, close cura. (This printer remains)
Open cura, add printer, trigger this bug & crash. (This printer is lost)

**Comment by Dim3nsioneer** [comment]
The crash issue is known and seems to happen on Windows only.
