### ISSUE TITLE
[master] mime type installation removed

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#630]
https://github.com/Ultimaker/Cura/commit/29562090b671ba3ef690f2653d49a3311d49baba

**Comment by fieldOfView** [comment]
We're sorry about that. This should not have been merged into master this way. We'll talk about this internally (and fix it), but it may take until after the weekend.

**Comment by thopiekar** [comment]
Please reopen. I guess you think it was reverted by @bburrough, but he only reverted one of two commits by @filushka.

**Comment by nallath** [comment]
Oh, my bad.

**Comment by thopiekar** [comment]
Hmm, found my lines again in [master]. Can be closed now.
