### ISSUE TITLE
Per model settings and cubic subdivision, possible bug CURA 4.2.1

### ISSUE THREAD

**Issue by Queneri** [Ultimaker/Cura#6303]
**4.2.1**

**Windows 10 and MacOs Mojave**

**Ultimaker 3 extended**

**Opening several files. Selecting per model settings, changing the infill of one of those files applies the change to all**

**Apply the change to all models**

**Apply the change to the selected file**

**only happens when cubic subdivision pattern is selected in general print settings and per model settings**

**Comment by Queneri** [comment]
Per model settings produces an error when cubic subdivision is the general infill parameter. When attempting to change the infill parameter of a single model, it applies to all remaining models. 
another result that you can expect when processing the model is 0% infill
![Screen Shot 2019-09-04 at 14 22 40](https://user-images.githubusercontent.com/54904776/64277344-7f1cae80-cf20-11e9-806d-0bac86f2f94d.png)
![Screen Shot 2019-09-04 at 14 25 49](https://user-images.githubusercontent.com/54904776/64277353-83e16280-cf20-11e9-942d-2975e46634d8.png)

**Comment by Queneri** [comment]
Playing a little more with the problem, I found another result. This time the infill is cut and leaves hollow parts inside the model
![Screen Shot 2019-09-04 at 15 28 30](https://user-images.githubusercontent.com/54904776/64281610-dffcb480-cf29-11e9-84a3-0e95ba7425bb.png)
![Screen Shot 2019-09-04 at 15 29 01](https://user-images.githubusercontent.com/54904776/64281611-dffcb480-cf29-11e9-8e40-24f0ce04d8d0.png)
![Screen Shot 2019-09-04 at 15 33 47](https://user-images.githubusercontent.com/54904776/64281613-e0954b00-cf29-11e9-800e-e75c2dbe461b.png)
![Screen Shot 2019-09-04 at 15 34 29](https://user-images.githubusercontent.com/54904776/64281614-e0954b00-cf29-11e9-8de7-c6fb459df5cd.png)
![Screen Shot 2019-09-04 at 15 36 17](https://user-images.githubusercontent.com/54904776/64281615-e0954b00-cf29-11e9-807b-9eb2918a4e41.png)

**Comment by rburema** [comment]
I can reproduce this on an UM3, I'll discuss it with the others.

**Comment by tecnocat** [comment]
Cura 4.7.1 and Windows 10 with same issues.

General infill set to 0% and Gyroid, and each box of model infill with all of them, every infill per model works perfectly except the Cubic Subdivision:

![cura-4 7 1-infill-cubic-subdivision-buggy](https://user-images.githubusercontent.com/726494/150414588-bfefd838-1f95-461a-b513-6147f0e41009.png)
![cura-4 7 1-infill-cubic-subdivision-buggy-printing](https://user-images.githubusercontent.com/726494/150415182-854ee4fe-9c28-4d65-861b-26b62967537a.png)

**Comment by tecnocat** [comment]
I uploaded the project to test by yourself, GitHub block the file type so rename to .3mf first.

[cura-4.7.1-infill-patterns-3mf-file.txt](https://github.com/Ultimaker/Cura/files/7908262/cura-4.7.1-infill-patterns-3mf-file.txt)

**Comment by Ghostkeeper** [comment]
Your issue is different though, @tecnocat. The original issue is that changing the infill of one object to Cubic Subdivision causes all models to use Cubic Subdivision, and that's clearly not the case for you.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
