### ISSUE TITLE
GCode file 0 Bytes

### ISSUE THREAD

**Issue by koopie66** [Ultimaker/Cura#6307]
When I tried to export a previous loaded stl file to  GCode the program creates a GCODE file with lengt of 0-bytes.

**Comment by nallath** [comment]
We're going to need a bit more information to resolve this. Please fill in the provided issue report so we have the data we need.

**Comment by fieldOfView** [comment]
Did you press the "slice" button?

**Comment by koopie66** [comment]
I did some additional testing:
It happens in thet following case 
step 1:load a STL file
step 2: change something (ie rotate)
step 3: do an export to GCODE
-> result an empty GCODE file
If the file is saved first then the GCODE file is correctly saved

**Comment by nallath** [comment]
What version of Cura did you use? On what operating system did you try this? With what settings did you try it?

I've just tried to slice an STL and save it to g-code and it works fine, so there must be something that is different.

**Comment by koopie66** [comment]
Cura version 4.2.1
OS: Windows 10 version 1903
Processor: Intel i7-2600CPU
12GB Ram
Cura settings: default from installation
Printer: ANET A6 with default settings

**Comment by nallath** [comment]
Could you share the STL as well, because i'm also able to just slice an object on an Anet A6

**Comment by koopie66** [comment]
[360mm_15_R_Bridge_for_Marklin_24130.zip](https://github.com/Ultimaker/Cura/files/3580410/360mm_15_R_Bridge_for_Marklin_24130.zip)

his is the stl file

**Comment by fieldOfView** [comment]
> step 1:load a STL file
step 2: change something (ie rotate)
step 3: do an export to GCODE

Between 2 and 3, do you "Slice"? The default in Cura is not to slice automatically. You can turn automatic slicing on in the general preferences.

**Comment by jimarcher** [comment]
I'm having the same issue, and have not found a workaround. I'm using Cura 4.7.1 on my MacOS Catalina 10.15.5. I load an STL file, rotate it on the build plate, select the profile and click "slice." I can then preview the slice niely and I click "save to file." A dialog opens and I select the path and filename and a file is created. But the file size is zero bytes. Opening the file in Atom confirms that the file is empty.

I'm using a FlashForge Creator Pro with this profile:

https://www.thingiverse.com/thing:3569113

**Comment by Ghostkeeper** [comment]
Are you saving to an X3G file? There is an issue with your symptoms in the X3GWriter: https://github.com/Ghostkeeper/X3GWriter/issues/30
