### ISSUE TITLE
Optional, Stop auto scanning serial ports on startup

### ISSUE THREAD

**Issue by tablatronix** [Ultimaker/Cura#6310]
When I start cura, it seems to scan all my serial ports this messes with all serial devices I have connected sometimes, namely microcontrollers with auto reset or DTR circuitry..

Any way to disable this , or make it manual ?

**Comment by smartavionics** [comment]
Yes, go into the marketplace dialog and in the list of installed plugins, turn off the USB printing plugin. Hope this helps.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.
