### ISSUE TITLE
Pop-up when hovering over info is not displaying correctly

### ISSUE THREAD

**Issue by mboratko** [Ultimaker/Cura#6319]
**Application version**
4.2.1

**Platform**
Arch Linux

**Printer**
Creality Ender-3

**Reproduction steps**
After slicing, I place the cursor over the "info" icon on the bottom right.

**Actual results**
The text is displayed but it is all jammed together and runs off the screen. It looks like a pop-up window is trying to display but it is not working.

**Expected results**
Information displayed in a pop-up.

**Additional information**
![Screenshot from 2019-09-06 22-50-45](https://user-images.githubusercontent.com/611553/64469019-7e8b4000-d0f9-11e9-909c-33dedbfb664c.png)

**Comment by smartavionics** [comment]
Hello @mboratko , are you using an AppImage or some other release? I ask because I know that the Arch people make their own releases which use later versions of Qt that cause some little glitches like you show above. The next release of Cura should have better compatibility with recent Qt (5.13).

**Comment by mboratko** [comment]
@smartavionics you are correct, I was using [the version from the AUR](https://www.archlinux.org/packages/community/any/cura/), when I installed the AppImage from Cura's website the popup displayed correctly. Thanks for the quick diagnosis!
