### ISSUE TITLE
F5 Relaod - Better visualization of changes before and after.

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#6323]
**Is your feature request related to a problem? Please describe.**
I use F5 a lot, mostly for updating minute changes to objects before printing. I don't always create new cad versions for quick tweaks. 

**Describe the solution you'd like**
Add an option to toggle and/or distinguish between the two models - before F5 and after F5 
Like PreF5 & PostF5 message on the UI. some changes are 100 microns or so and it is impossible to see/know which one is loaded or if load took place at all. of course best would be saving new iterations with new names but then one should ask - why having F5 reload to begin with?

**Describe alternatives you've considered**
I fully understand the need to save new cad models with new names but it is much faster to print prototypes using F5.

Again, I fully understand if this feature is not a must, but very good to have.
A penny for your thoughts..

**Comment by Ghostkeeper** [comment]
I think tracking the changes in multiple iterations of your design is outside of scope for Cura. It's more of a task for the PDM or version control software you're using, or perhaps for the CAD software itself. Cura is meant to print. F5 is meant to make it easier to print the latest version.
