### ISSUE TITLE
Question - Issue Skirt/brim arc radius, curve angle?

### ISSUE THREAD

**Issue by tablatronix** [Ultimaker/Cura#6324]
4.2.1 OSX
Ender 3 pro

I am having issues onmy ender 3 pro printing skirts..

Is it possible to change the arc radius on skirts ?

For some reason my ender gets all jerky and cannot seem to print these well.. NO idea why, I have not checked for changes or reverted to an older version to see if this is new or not, never had this issue on my mpsmv2

![Screen Shot 2019-09-08 at 10 05 54 AM](https://user-images.githubusercontent.com/807787/64490312-40893b80-d221-11e9-9e91-3b0c10bddf06.png)

I have video

**Comment by Ghostkeeper** [comment]
With the Skirt Distance setting?

**Comment by tablatronix** [comment]
tried 10 and 5

**Comment by tablatronix** [comment]
vid https://youtu.be/P6iAfghjX7A

**Comment by Ghostkeeper** [comment]
I suggest increasing the Jerk for skirt and brim.

The skirt's arc radius is exactly the distance between the skirt and the model, so that's worth a try as well.

**Comment by Liger0** [comment]
Same on my cr10s. I don't have this on s3d and I don't have jerk/ascceleration control in cura.

**Comment by tablatronix** [comment]
ok so I tested again with jerk and acceleration control and it is much better.
I am going to try to drop the skirt acceleration and see what that does, maybe its too high.

**Comment by Ghostkeeper** [comment]
I think the default jerk of your printer is set very low. This means that it's not allowed to make a corner without slowing down significantly.

I've done a write-up of what jerk is exactly here in the Settings Guide plug-in: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/jerk_enabled.md

**Comment by tablatronix** [comment]
Thanks, I thought I understood it apparently not, going to read some more, great write up.

**Comment by Liger0** [comment]
I have a jerk of 8 in my firmware and in S3d have no issue.

**Comment by Ghostkeeper** [comment]
Does Simplify3D put any M205 g-codes in its output?
