### ISSUE TITLE
Cura goes unresponsive (beachball) on Mac during long print.

### ISSUE THREAD

**Issue by kilpatds** [Ultimaker/Cura#633]
This sounds a lot like issue https://github.com/daid/Cura/issues/1115 in the older fork.

It goes unresponsive.  The print finishes fine, but the laptop has to spin the fan up as it's taking 100% of a CPU.

If I force-quit it, a 2nd Cura process then spins up to take 100% of CPU.  I briefly trussed it, and it was a python process in a tight loop, but I don't have details handy.

Cura version: 15.04.4
Printr: printrbot play

The next time it happens, I'll try and attach some debugging info.

**Comment by nallath** [comment]
Please post issues for 15.04 < on the cura/daid github. This is for the re-worked Cura.
