### ISSUE TITLE
expect more intuitive custom supports

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6333]
cura by custom supports plugin:
![Screen-2019-09-11_10-51-17](https://user-images.githubusercontent.com/16573747/64664705-88f36400-d482-11e9-9ed9-fb70cad28636.jpg)

simplify3d:
![Screen-2019-09-11_10-47-15](https://user-images.githubusercontent.com/16573747/64664729-9d376100-d482-11e9-890a-264f6ddd5540.jpg)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Affected users and/or printers**
 
**Additional context**

**Comment by rburema** [comment]
Hi! (A lot of) Plugins aren't the responsibility of the people developing Cura (though there is significant overlap), you'll want to repost your request [at the issue tracker of the plugin](https://github.com/lokster/cura-custom-supports/issues) instead.

I'm sure though that when you do, they'd appreciate some more information: e.g. what do you think is unintuitive about their current approach?

**Comment by Ghostkeeper** [comment]
Discussion is continued here: https://github.com/lokster/cura-custom-supports/issues/5
