### ISSUE TITLE
translation to Czech

### ISSUE THREAD

**Issue by adekarem** [Ultimaker/Cura#6337]
good evening,

I would like to ask you how to proceed if I would like to translate Ultimaker Cura into Czech.

I never translated programs, translated movies and dramas, documentaries, I would like to try. I have already found some information on the Internet, and I would therefore like to make sure that this is the right procedure. I found in the c: \ Program Files \ Ultimaker Cura \ resources \ i18n template folder to accurately translate 4 templates that can be opened and translated in poedit. I don't know how to proceed please

**Comment by S474N** [comment]
> good evening,
> 
> I would like to ask you how to proceed if I would like to translate Ultimaker Cura into Czech.
> 
> I never translated programs, translated movies and dramas, documentaries, I would like to try. I have already found some information on the Internet, and I would therefore like to make sure that this is the right procedure. I found in the c: \ Program Files \ Ultimaker Cura \ resources \ i18n template folder to accurately translate 4 templates that can be opened and translated in poedit. I don't know how to proceed please

Postoupila si nejak? Pripadne nabizim pomocnou ruku s prekladem!

**Comment by adekarem** [comment]
Omlouvám se za pozdní odpověď něco přeloženého mám, ale momentálně z důvodu
nemocí jsem překlad pozastavila, mohu se zeptat zda víte jak to dát do kupy
poslala bych vám co mám a popřípadě bych něco i přeložila navíc děkuji za
odpověď

Dne po 23. 12. 2019 20:36 uživatel S474N <notifications@github.com> napsal:

**Comment by Ghostkeeper** [comment]
The most common way to share translation files is via .po files, if that's what you're asking. Google Translate is borking on your sentence a bit.

**Comment by Ghostkeeper** [comment]
Someone else has recently translated the Cura repository to Czech. It just needs to also translate Uranium now before we can add it.

See https://github.com/Ultimaker/Cura/pull/7141

**Comment by Ghostkeeper** [comment]
This is merged for Cura 4.6.
