### ISSUE TITLE
coasting and infill wipe distance

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#6339]
Is it intentional that coasting only works on walls?

is it intentional that infill wipe distance only works below 50% infill?

**Comment by BagelOrb** [comment]
Remember that only half of the line ends will show a wipe because we only wipe at the end of a printed line...

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
