### ISSUE TITLE
[4.2.1] ChangeAtZ generates too much empty strings.

### ISSUE THREAD

**Issue by fox1047** [Ultimaker/Cura#6343]
**Application version**

4.2.1

**Platform**

Windows 10 x64
**Printer**

Flyingbear Ghost 4
**Reproduction steps**

Add 7 or more ChangeAtZ scripts in Modify G-code menu.
**Actual results**

Printer freezes at the end of last layer before turning nozzle temperature to 0
**Expected results**

File should print normally
**Additional information**

I encountered this bug while slicing temperature tower. It printed normally until the end of last layer where it just stopped with nozzle over model.
[ChangeAtZ6.gcode.zip (Prints normally)](https://github.com/Ultimaker/Cura/files/3607214/ChangeAtZ6.gcode.zip)
[ChangeAtZ7.gcode.zip (Freezes at the end)](https://github.com/Ultimaker/Cura/files/3607215/ChangeAtZ7.gcode.zip)
I tried to find what triggers freeze and found that it was amount of empty strings before finishing part of g-code.

**Comment by rburema** [comment]
Fixed it; see https://github.com/Ultimaker/Cura/commit/756c21cd1928b91f9e82e84a94f81c1e43877709

Change should be in 4.3-final (as opposed to beta, which is out now).
