### ISSUE TITLE
[4.3 beta] Micro freezes

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6344]
**Application version**
4.3 beta

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Randomly, not always but pretty frequently. It happens when saving a file, opening machines, saving values, etc

**Actual results**
The software freezes (typical semi-blank screen) for some seconds to a minute and then continues to work normally until it re-happens

**Expected results**
No blockage

**Additional information**
It never happened on any earlier versions, 4.2.1 included.
I did a clean install of 4.3 beta.

**Comment by Ghostkeeper** [comment]
I wouldn't call "up to a minute" micro! We would definitely have noticed this if it occurs for us. What plug-ins have you installed?

**Comment by Liger0** [comment]
Auto orientation, Barbarian units, Custom setting visibility, custom supports, mesh tool, printer settings, z offset. trimesh reader is also isntalled by default.

**Comment by fieldOfView** [comment]
I'm guessing you have a lot - if not all - settings visible? Could you check if the same pauses happen with just the "Basic" set visible?

**Comment by Liger0** [comment]
I have my own settings visibility with the settings I use which is the same as older Curas, also my hardware is up to the task (16gb of ram, ryzen 5 1600, vega 56), with an idle system.
I will give it a try in the spare time.

**Comment by Ghostkeeper** [comment]
We haven't been able to reproduce this yet on any of our Windows or Linux computers.
