### ISSUE TITLE
[4.3 beta] Supports are flat and don't follow model geometry

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6345]
**Application version**
4.3 beta

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Use supports

**Actual results**
The support won't follow the model geometry if multiple parts have to be supported, but instead they will stop being generated at the first layer that joined lines of a support can reach. 
This is especially shown on the support on the left of the image, since the support(s) only touch each other at the bottom but then they are completely separated, yet the part of the left stops when the one on the near  right also stops, instead of going up.

**Expected results**
Supports should follow the mesh.

**Additional information**
![supports flat](https://user-images.githubusercontent.com/20385116/64829507-e85d8b00-d5cc-11e9-86f9-352c79d93320.png)

[CCR10S_supports.zip](https://github.com/Ultimaker/Cura/files/3607890/CCR10S_supports.zip)

**Comment by rburema** [comment]
I hope I interpreted this issue correctly, but I think: If you want the support to 'follow the mesh' as you put it, you should put the 'support placement' setting to 'everywhere' (as opposed to 'touching the buildplate' as it is now).

**Comment by Ghostkeeper** [comment]
It's not entirely generating as Liger0 says: On the right leg in the picture (left for the figurine) you can see that it doesn't stop at the first place where it hits the model.

I think this is again an issue of the Minimum Support Area. Can you try setting that to 0?

**Comment by Liger0** [comment]
Indeed, it seems my support settigns have been deleted with cura 4.3 beta so I didn't notice it. I need to set minimum support area to 0, minimum x-y distance to 0.1, and x-y distance to 0.4 to get the support barely reach the model (with still some layers empty(.

**Comment by Ghostkeeper** [comment]
In that case this is expected behaviour.
