### ISSUE TITLE
Custom profile cannot be added to the Ender 3 machine profile

### ISSUE THREAD

**Issue by MisterPrintf** [Ultimaker/Cura#6346]
**Application version**

Ultimaker Cura 4.2.1

**Platform**

Windows 7 home

**Printer**

Creality Ender 3 (stock profile)

**Reproduction steps**

If you attempt to open the included profile (which was created for and on a custom Ender 3 machine profile) while having the Creawesome mod's Ender 3 profile selected, you will recieve the following error:
The machine defined in profile C:/Users/Brandt/Documents/Thingiverse Profile.curaprofile (fdmprinter) doesn't match with your current machine (creality_base), could not import it.

**Expected results**

The profile should import without issue.

**Additional information**

Profile is attached as a .zip.
[Broken Profile.zip](https://github.com/Ultimaker/Cura/files/3608246/Broken.Profile.zip)

**Comment by nallath** [comment]
This has been fixed for 4.3. You can try this already when you install the beta.
