### ISSUE TITLE
Make 3d models list completely visible

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6348]
**Is your feature request related to a problem? Please describe.**
Yes, the names of the models are not entirely visible

**Describe the solution you'd like**
Insert an horizontal scroll bar to scrall the entirety of the name.

**Describe alternatives you've considered**
There are quite a few possibilities over the scroll bar, like an expansive menu, a popup that shows the name of the model you are pointing, making the name go over multiple lines, etc.

**Affected users and/or printers**
Any

**Additional context**
![models list](https://user-images.githubusercontent.com/20385116/64864200-e3352600-d636-11e9-9d34-64ab80a77311.png)

**Comment by Ghostkeeper** [comment]
Fixed here: https://github.com/Ultimaker/Cura/commit/cd4f6ff3f4bc0f97f9e7b65f608f1f42c66bb016
