### ISSUE TITLE
[4.3 beta] Main Wipe retraction speed not inherit

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6356]
**Application version**
4.3 beta

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Enable wipe

**Actual results**
The main wipe retraction speed is unused by the profile, because both its submenus inherit the speed directly from the retraction speed instead of the upper field.

**Expected results**
The subvalues should inherit values from the upper value, which then inherits it by the material retraction speed

**Additional information**
I think it's been forgotten when implemented because even the description doesn't report it being an inherit value, but then it doesn't make sense to exist (and have a 5 value by default) if its value is never used.
![retraction wipe](https://user-images.githubusercontent.com/20385116/64913380-6772d080-d73f-11e9-9ce9-3a2787f967f5.png)

**Comment by rburema** [comment]
Seems like those inherit the value from 'retraction_speed' instead of 'wipe_retraction_speed'.

**Comment by Ghostkeeper** [comment]
I think we should remove the parent setting and let it inherit from the retraction settings then. Maybe we could even put them as child settings of the retraction speed setting.

**Comment by rburema** [comment]
See new Jira ticket: CURA-6789.

**Comment by rburema** [comment]
Seems this was fixed in commit https://github.com/Ultimaker/Cura/commit/e2b8a44 by making the parent setting relevant again.
