### ISSUE TITLE
[4.0.0] Infill Density Doesn´t Match (URGENT!)

### ISSUE THREAD

**Issue by Regiux** [Ultimaker/Cura#6361]
**Application version**
4.0.0

**Platform**
Windows 10 Home - Nvidia GeForce GTX1050Ti

**Printer**
Creality Ender 3

**Reproduction steps**
Open Cura > Load Model > Slice and Preview

**Actual results**
Infill Density doesn´t match the resulted infill desired in the sliced model

**Expected results**
Infill Density designated for slicing should be the same as in the sliced model

**Additional information**
This issue only happens with some models
![InfillError](https://user-images.githubusercontent.com/43587782/64924396-9000d600-d7e4-11e9-8dba-7468e939825b.png)

**Download Files**
STL:
[Moneda_Cupon.zip](https://github.com/Ultimaker/Cura/files/3614349/Moneda_Cupon.zip) 

**Project**:
[CE3_Moneda_Cupon.zip](https://github.com/Ultimaker/Cura/files/3615135/CE3_Moneda_Cupon.zip)

**Comment by Liger0** [comment]
Without a project file I don't think anyone could help.

**Comment by Regiux** [comment]
Added file download for project reference

**Comment by smartavionics** [comment]
Sorry, that's not a project file it only contains the model but we need to see the settings. Please do File -> Save to produce a .3mf file, either rename or zip and attach to this issue. Thanks.

**Comment by Regiux** [comment]
> Sorry, that's not a project file it only contains the model but we need to see the settings. Please do File -> Save to produce a .3mf file, either rename or zip and attach to this issue. Thanks.

Uploaded project file for possible study

**Comment by smartavionics** [comment]
Thanks for the file. The reason that you don't get infill is because top layers is currently set to 999999! If you explicitly set top layers to something less, say 10, you get this...

![Screenshot_2019-09-16_08-52-15](https://user-images.githubusercontent.com/585618/64941723-4e614100-d85f-11e9-928b-2550c5acd442.png)

**Comment by Regiux** [comment]
Great Thanks !!!! This solved a lot for me!
