### ISSUE TITLE
Printing nonexistent object

### ISSUE THREAD

**Issue by tphan26363** [Ultimaker/Cura#6363]
Recently. the Cura 4.2.1 is having a problem that I can't figure out and don't know how to fix it.

It started printing outside the object at a a position 100 mm far way like a ghost image or some thing.  I have a video and a G-code file attached.  This is a huge problem for me since it create a lot of artifact grown out from the printing object.  A profile also included.  I look at the slicer but I don't see any problem from the preview
![Capture](https://user-images.githubusercontent.com/53447108/64925946-93786b00-d7ac-11e9-8fcb-4883b2ce69bb.PNG)

[Slicer.zip](https://github.com/Ultimaker/Cura/files/3614120/Slicer.zip)

[IMG_0638.zip](https://github.com/Ultimaker/Cura/files/3614118/IMG_0638.zip)

**Comment by fieldOfView** [comment]
Check the "Wipe Nozzle Between Layers" setting.

**Comment by Ghostkeeper** [comment]
Or rather, uncheck it!
