### ISSUE TITLE
Cura 4.2.1 resumes printing at wrong layer height after pausing at specified layer number

### ISSUE THREAD

**Issue by 4cpus4me** [Ultimaker/Cura#6369]
**Application version**
4.2.1

**Platform**
Windows 8.1, GPU: Radeon RX580

**Printer**
Creality Ender-5

**Reproduction steps**
Simply slice a print with an optional post-processing option "Pause at Layer Number" configured.

**Actual results**
When the Gcode is created, the wrong Z-height is used when the printer resumes printing and the print fails.

**Expected results**
Printer should resume printing correctly.

**Additional information**
Screenshot of the issue is attached.
![CuraBug](https://user-images.githubusercontent.com/55416569/65000172-a6786180-d8b8-11e9-97ab-f5b0014cd256.jpg)

**Comment by rburema** [comment]
Sounds like [this issue](https://github.com/Ultimaker/Cura/issues/5924). If so, should be fixed in 4.3-BETA, which is avialable right now.

Feel free to reopen if it's not fixed for you!
