### ISSUE TITLE
Weird holes/artifacts on surface after slicing for monoprice select mini v2.

### ISSUE THREAD

**Issue by Gzalo2188** [Ultimaker/Cura#6377]
**Application version**
4.2.1

**Platform**
[Personal Laptop]
Windows 10
GTX 1650

[School Desktops]
Windows 10
GTX 1080

**Printer**
Monoprice Select Mini v2

**Reproduction steps**
Happens with most meshes that have a shell.

**Actual results**
Defects appear on the surface of the print. Usually as big holes or smaller dips.

**Expected results**
Surface should be smooth.

**Additional information**
I run a maker space at a community college so we have multiple computers with cura. The issue seems to appear frequently on all computers when slicing for the monoprice select mini v2. However when slicing for the ultimaker 2+ the issue doesnt show up.

[Cura_Issue.zip](https://github.com/Ultimaker/Cura/files/3627884/Cura_Issue.zip)
Ive attached both the test object and a project file. Also here's a picture of the [issue](https://i.imgur.com/wGfu7Uy.png).

**Comment by smartavionics** [comment]
Hello @Gzalo2188 , in that profile you are using coasting, if you turn that off the large gaps shown on the layer view go away. Personally, I never use coasting but if you wish to use it, perhaps you should reduce the amount of coasting?

With coasting...

![Screenshot_2019-09-18_20-26-47](https://user-images.githubusercontent.com/585618/65179588-f559fe80-da52-11e9-9ba5-34cf88adf6e4.png)

Without coasting...

![Screenshot_2019-09-18_20-27-17](https://user-images.githubusercontent.com/585618/65179587-f559fe80-da52-11e9-91dc-e3b0b459c3f2.png)

**Comment by Gzalo2188** [comment]
@smartavionics Thanks! That definitely solved the issue.

For some reason coasting is turned on by default with the select mini profile when switching to expert mode.
