### ISSUE TITLE
Print Settings Hide Save Dialog

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#6399]
Since release of v4 the print settings come at full height, hiding the - now separate - save dialog:
![Screenshot 2019-09-23 at 15 33 18](https://user-images.githubusercontent.com/91770/65430459-446baf00-de18-11e9-9b68-53cd2daa53be.png)

Please limit the settings' height to leave space for the dialog underneath as before so I do not have to close them prior being allowed to save.

**Comment by smartavionics** [comment]
But you can drag the bottom of the settings by grabbing the three dots so you can alter the height of that panel.

**Comment by fieldOfView** [comment]
Or you can install the Sidebar GUI plugin, which properly fixes this foolishness

**Comment by thesec** [comment]
Hihi, excellent @smartavionics ... I just did not wear my jeweller's magnifiying lens to realize there being three fly sh... for dragging the panel in such a non-standardized fashion ;)

Yet I will leave this open. It should neither require a lens on the nose, nor user interaction or even a plugin to get around this.

**Comment by rburema** [comment]
Also you can drag the panel around with the header.

**Comment by rburema** [comment]
Shouldn't be completely full height though, it should stop (unless someone drags it) right above the 'action panel' (the one with the slice button in it).

Do you have multiple different sized monitors you work on? Was it always like this since first startup of 4.0.0?

**Comment by thesec** [comment]
@rburema - it was always like it. Yes, I have two differently sized displays I work on.

**Comment by thesec** [comment]
...
- a icon that is more obvious than the rotated hamburger (does it make it a hot dog?), see https://www.visualpharm.com/free-icons/mouse/drag%20mouse for commonly used ones
...

**Comment by tablatronix** [comment]
This new UI has some annoyances, mostly that it makes all the UI elements on total opposite sides of the screen, everything is as far away from each other as possible.

The time slider and layer sliders should be next to each other, this pushes one all the way to the right, going back and forth is a pain. Controls are all the way on the left, viewport, all the way on the bottom, view control top left, layer control, the whole top, but the dialog is on the left ?

God forbid you have one of those widescreen monitors... lol

And an actual BUG
**The floating side bar covers the layer # popup..**

**Comment by fieldOfView** [comment]
There is the Sidebar GUI plugin in the Marketplace, which solves most of these issues.

**Comment by tablatronix** [comment]
@fieldOfView I know I installed it, it was awesome to have it back!, but I turned it off for a bit while I narrow down the source of my performance issues, not sure if it was related or not

**Comment by fieldOfView** [comment]
OT: So, was it the cause of the slowdowns?

**Comment by Ghostkeeper** [comment]
> And an actual BUG
The floating side bar covers the layer # popup..

Yeah, we found that as well and fixed it in Cura 4.4. See https://github.com/Ultimaker/Cura/pull/6499 and https://github.com/Ultimaker/Cura/pull/6592.

**Comment by tablatronix** [comment]
So you fixed this?
![Screen Shot 2019-11-04 at 12 17 20 PM](https://user-images.githubusercontent.com/807787/68146249-3459eb80-fefd-11e9-9208-149b53c7ae5c.png)

**Comment by Ghostkeeper** [comment]
No, as I said, for the floating settings panel we still don't have a real solution. Other than moving the panel a bit to the left, that is.

**Comment by nallath** [comment]
> So you fixed this?

We have a solution for it in https://github.com/Ultimaker/Cura/pull/6607

**Comment by rburema** [comment]
That's pulled into master though, so it's not in 4.4

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
