### ISSUE TITLE
Version 4.2.1 Wall Thickness: Is grayed out in box and does not reflect the correct wall number thickness, even when changing numerical values.

### ISSUE THREAD

**Issue by H-DieterK** [Ultimaker/Cura#6406]
Version 4.2.1 Wall Thickness: Is grayed out in box and does not reflect the correct wall number thickness, even when changing numerical values.

**Comment by Ghostkeeper** [comment]
This happens when all of the sub-settings override the Wall Thickness setting. That is, if you've changed both the Inner Wall Thickness and the Outer Wall Thickness. The value for the Wall Thickness is not used any more then.
