### ISSUE TITLE
Display travels in top-visible layer differently

### ISSUE THREAD

**Issue by drewnoakes** [Ultimaker/Cura#6410]
It can be hard to see which travels belong to which layer.

Here is a screenshot that gives an example of what I mean:

![image](https://user-images.githubusercontent.com/350947/65560834-82d1ad00-df83-11e9-84f1-3a8117c7d496.png)

Zooming in doesn't always help:

![image](https://user-images.githubusercontent.com/350947/65560866-9a109a80-df83-11e9-9fdc-e99f9f5ad6c3.png)

To that end, I would like the travels in the 'current' layer (by which I mean the top-visible one) to be distinct from those below it.

Two ideas come to mind:

- Show the top layer's travels using a different colour
- Allow hiding travels below the top layer

My goal is to better understand why this model will spend over half its time in travels, and see if there's anything I can do to reduce that time.

This should benefit anyone who is investigating issues with travels.

**Comment by rburema** [comment]
You can already show (a) specific layer(s) if you drag the scroll-points on the right in preview mode.

![draglayers_feature](https://user-images.githubusercontent.com/41987080/65580307-b4457b00-df79-11e9-8e86-1ded24aa1a27.png)

**Comment by drewnoakes** [comment]
@rburema thank you, that addresses my requirement perfectly and in a much more general way!
