### ISSUE TITLE
[4.3.0] Support Interface Line Direction inheritance

### ISSUE THREAD

**Issue by Asterchades** [Ultimaker/Cura#6412]
**Application version**
4.3.0

**Platform**
Windows 10 Pro x64 1903

**Printer**
Creality3D Ender-2 (custom profile)

**Reproduction steps**
Adjust the primary Support Interface Line Direction value.

**Actual results**
No change will be observed in either the preview or the generated G-code. This is as a result of both the Floor and Roof sub-values not inheriting the parent value by default. Instead, these must be changed separately.

The default "fdmprinter.def.json" as per the repository confirms this is currently by design. Both "support_roof_angles" and "support_bottom_angles" declare a default_value of "[ ]".

**Expected results**
Both the Floor and Roof sub-values will, at least by default, inherit the parent value. Otherwise the parent value serves exactly zero purpose.

This would require setting both of the aforementioned default_value to "support_interface_angles".

**Additional information**

**Comment by Ghostkeeper** [comment]
Indeed! Good find. I've fixed it for the next release.
