### ISSUE TITLE
After upgrading Cura from 4.0.0 to 4.3.0 version lost Ultimaker materials information

### ISSUE THREAD

**Issue by rkorczynski** [Ultimaker/Cura#6413]
I lost Ultimaker materials information after upgrading Cura from 4.0.0 to 4.3.0 version.

**Comment by Ghostkeeper** [comment]
What do you mean with "lost"? The materials are no longer in the list of available choices?

**Comment by rkorczynski** [comment]
That's exactly what I mean. The Ultimaker materials were on the available choice list in version 4.0 and after upgrading they disappeared. No more Ultimaker materials are on the list of materials to choose from.

**Comment by fieldOfView** [comment]
What printer do you use?

**Comment by rkorczynski** [comment]
Monoprice Maker Ultimate 3D.

**Comment by Ghostkeeper** [comment]
We don't have a printer definition for Monoprice Maker Ultimate 3D. What printer did you add in Cura? Or did you install a mod for Cura to add it?

**Comment by Ghostkeeper** [comment]
I'd say though, that according to the [specs](https://www.monoprice.com/product?p_id=15710) it's correct that the Ultimaker filaments are not shown for your printer since your printer accepts only 1.75mm diameter filaments, while all Ultimaker filaments are 2.85mm.

**Comment by rkorczynski** [comment]
I installed as Monoprice Ultimate printer that I found on the list of available printers.

**Comment by Ghostkeeper** [comment]
The Monoprice Ultimate is using the [Wanhao D6 extruder](https://github.com/Ultimaker/Cura/blob/648f167911134ce15ac7b9e44619bfa47589817f/resources/definitions/monoprice_ultimate.def.json#L15) according to our profiles. This extruder has been using [1.75mm](https://github.com/Ultimaker/Cura/blob/648f167911134ce15ac7b9e44619bfa47589817f/resources/extruders/wanhao_d6_extruder_0.def.json#L14) filament for the past year or so. I wouldn't expect anything has changed with that recently.

**Comment by rkorczynski** [comment]
Thank you for the info.
