### ISSUE TITLE
After upgrading Cura from 4.0.0 to 4.3.0 version. I can not add User Specified XY Coordiantes for Z Seam Alignment.

### ISSUE THREAD

**Issue by Roboman10** [Ultimaker/Cura#6415]
**Application version**
Cura 4.3.0

**Platform**
Windows 10 Pro x64 1903

**Printer**
Creality CR-10 S4

**Reproduction steps**
Select User Specified for Z Seam Alignment.

**Actual results**
Can NOT add the X and Y Coordinates for Z Seam Alignment when selecting User Specified.

**Expected results**
Should be able to add the X and Y Coordinates 

**Additional information**

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this issue so far:
![Screenshot from 2019-09-25 11-49-25](https://user-images.githubusercontent.com/2448634/65590260-038bab80-df7a-11e9-9075-d31c4900fbf1.png)
The X and Y coordinates for the seam appear to be fine.

**Comment by Roboman10** [comment]
Looks like the Z Sean Position was turns off. Not sure why but it shows up now.
