### ISSUE TITLE
Question: Removing boundary box and graph paper

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#6422]
As a little follow up on the question of how to replace, the next question:
Is it possible to remove the boundary box and graph paper, too?

Right now I have the following result: (Which is already very pleasant! - thank you again @nallath )
![65640793-741ee080-dfeb-11e9-8a4e-07525f3dbbf8](https://user-images.githubusercontent.com/1847437/65642804-67e95200-dff0-11e9-9bda-e98643680325.png)
![65640869-a4667f00-dfeb-11e9-8660-dcbc1e7c407c](https://user-images.githubusercontent.com/1847437/65642808-69b31580-dff0-11e9-8211-40f6859cbb60.png)

I couldn't any nice function that could give me the boundary box and the grid paper as done for the build platform. I guess that nobody asked for this ever before.

Could you give me a hint where I can find the critical code at least?
That would be awesome! 🤓

**Comment by fieldOfView** [comment]
How is this a bug?

**Comment by nallath** [comment]
I forgot to commit the fix I made that also enables the hiding of the build volume if you set it to invisible.

> How is this a bug?

If you set the visibility of the BuildVolume scene node, you'd expect it to be ya know. Invisible.

**Comment by thopiekar** [comment]
Great! Thank you again @nallath
