### ISSUE TITLE
[4.3] Overhanging wall angle changes feedrate if used with support blockers as modifiers

### ISSUE THREAD

**Issue by alfrix** [Ultimaker/Cura#6430]
Using support blockers to modify settings that overlap with other models changes the feedrate, (even without selecting anything to modify) if "overhanging wall angle is set to less than 90"
Normal slice
![1](https://user-images.githubusercontent.com/1247237/65736324-f91ffd80-e0b0-11e9-9940-92a722a3fe4d.JPG)
with a support blocker set on "Modify settings that overlap with other models " and "overhanging wall angle 50"
![2](https://user-images.githubusercontent.com/1247237/65736323-f8876700-e0b0-11e9-97dd-8ba1043d98f4.JPG)

**Comment by nallath** [comment]
Could you share the project file of this? I've tried reproducing this with the following steps:
1. Add a model & print it with defaults
2. Add another model and use that as "modify settings for overlaps"
3. Set the support overhang angle of the modifier mesh to 90
4. Check the preview

I don't see any feed rate differences when doing that.

**Comment by Ghostkeeper** [comment]
Yeah, this is easy to reproduce. It seems that the cutting mesh messes with the overhang detection. Here is a project file in a zip that reproduces the issue.

[overhanging_wall_detection.zip](https://github.com/Ultimaker/Cura/files/3662425/overhanging_wall_detection.zip)

**Comment by alfrix** [comment]
> 3.Set the support overhang angle of the modifier mesh to 90

90 is disabled, it should be less than 90 (i used 50 for the example)
it happens on all the models i've tried

normal slice
![1](https://user-images.githubusercontent.com/1247237/65766240-d61d3a00-e100-11e9-8d2b-acbf661b3faf.JPG)
overhanging wall angle 50 with cube set as modify
![2](https://user-images.githubusercontent.com/1247237/65766241-d61d3a00-e100-11e9-8be6-9b8b215e34f4.JPG)

**Comment by alfrix** [comment]
it's a lot more broken than i thought, maybe this behaviour is related, with a normal slice with no extra changes and a cube set as modifier (the example it's a benchy)

![modify settings that overlap with other models](https://user-images.githubusercontent.com/1247237/65767091-37460d00-e103-11e9-9b64-fa6954d7c8bd.JPG)

**Comment by Ghostkeeper** [comment]
That is expected behaviour for a cutting mesh. It breaks up the model into several pieces and adjusts settings for each of them. CuraEngine is at this moment unable to change the line configs halfway through a contour, so they are made into separate contours.

**Comment by Ghostkeeper** [comment]
The issue with the overhanging wall angle has been deferred to a day when we have blue skies. There are more important things for us to fix, especially since the Overhanging Wall Angle is still experimental.

**Comment by alfrix** [comment]
Add bridge settings to the list, for the time being you can sort of workaround these problems, by disabling both the overhanging and bridge settings in the modifier mesh, and because of the contour limitation, the mesh should completely enclose or cut the entire object transversally as i show here:

![workaround](https://user-images.githubusercontent.com/1247237/65959262-e9ddde80-e427-11e9-8434-0ba7bf67bfe2.JPG)

not perfect, but still useful for some testing and advanced stuff
