### ISSUE TITLE
Ultimaker Cura 4.3.0 Printer Selection not available

### ISSUE THREAD

**Issue by tronicgr** [Ultimaker/Cura#6433]
I have two printers, an Ultimaker3 and Ultimaker3 extended. They are setup as group with one of them being the host using the Cura Connect. But I cannot select which one will print over network anymore, the pop up window is missing.

**Application version**

**Platform**
 Windows 10 Enterprise 

**Printer**
 Ultimaker3 and Ultimaker3 extented 

**Reproduction steps**
 In previous Cura version, when I pressed the button to "Print over network" it would popup a printer selection menu to choose which one to send the print to. 

**Actual results**
 Now after installing the Cura 4.3.0 this window does not pop up anymore and the print is send to the first available. This is inconvenient as I have different color material on each and I'd like to chose which one can print...  

**Expected results**
Can you bring back that printer selection menu? Is there a setting somewhere to enable it back?

**Comment by tronicgr** [comment]
I have two printers, an Ultimaker3 and Ultimaker3 extended. They are setup as group with one of them being the host using the Cura Connect.
 
In previous Cura version, when I pressed the button to "Print over network" it would popup a printer selection menu to choose which one to send the print to. Now after installing the Cura 4.3.0 this window does not pop up anymore and the print is send to the first available. This is inconvenient as I have different color material on each and I'd like to chose which one can print...

I have Windows 10 Enterprise.
 
Can you bring back that printer selection menu? Is there a setting somewhere to enable it back?

**Comment by Ghostkeeper** [comment]
I'm told it was intentionally removed. It was no longer possible due to a refactor that was made during this release. I'll ask the developers of that plug-in on whether it needs to be put back.

**Comment by tlum2** [comment]
Not being able to select from our 4 printers is a huge feature deletion, basically it is now taking us back to putting everything on thumb drives so we can select the correct printer. Please consider reinstating this feature.

**Comment by ChrisTerBeke** [comment]
Addressed by https://github.com/Ultimaker/Cura/pull/6580.
