### ISSUE TITLE
Geschwindigkeit für überhängende Wände

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#6436]
Cura 4.2.1

Hallo
Die Geschwindigkeit der überhängenden Wände wird beim Druck mit Support nicht angepasst. 
Oder es fehlt die Einstellung für die Geschwindigkeit bei Druck auf Support.
 Besonders bei Verwendung von Dualextruder und PVA . 

The speed of the overhanging walls is not adjusted when printing with support.
Or you may not have the speed setting when printing on support.
especially when using dualextruder and PVA

**Comment by Ghostkeeper** [comment]
This is intended. The overhanging wall speed only applies to overhang that is not supported. There is no setting right now to adjust the speed of the layer printed on top of support, only the fan speed (Fan Speed Override).

I'll clarify this in the setting description.

**Comment by lwbsbde** [comment]
How can I print slow on PVA support

**Comment by Ghostkeeper** [comment]
We don't have a specific set of settings for the layer above support, other than the fan speed via the Fan Speed Override setting. You could achieve that with a separate mesh but it's going to be very hairy to model that. So it's honest to say then that Cura doesn't support that at the moment.

**Comment by lwbsbde** [comment]
I also miss a customizable Fan speed when overhanging Wall without support. Experimental Settings.

Overhanging Wall Angle
Overhanging Wall Speed
+Overhanging Wall Fan Speed
