### ISSUE TITLE
Can't see printer start and end  g-code textbox

### ISSUE THREAD

**Issue by josemiguelsfaria** [Ultimaker/Cura#6442]
**Application version**
4.3.0
**Platform**
windows 10 pro 64bits
**Printer**
Creality 3d Ender

**Reproduction steps**
go to printer settings
**Actual results**
Textboxes for start g-code and end g-code are too small

**Expected results**

**Additional information**

![image](https://user-images.githubusercontent.com/16255407/65819767-669a6e00-e218-11e9-8cce-2d68965a9738.png)

**Comment by daniel2887** [comment]
Why was this closed? Was a fix merged?
