### ISSUE TITLE
JG Aurora z-603s profile sends print head crashing into frame at end of print

### ISSUE THREAD

**Issue by oorail** [Ultimaker/Cura#6451]
**Application version**
4.3.0

**Platform**
Linux (Ubuntu 16.xx LTS)

**Printer**
JG Aurora z-603s

**Reproduction steps**
Send any print via USB to the printer, wait for the print to end.

**Actual results**
1. print completes
2. printer homes x-axis (expected)
3. printer sends print head into the front frame of the printer
4. printer hits it 2-3 times, then stops
5. print head and x-axis rods are blocking about 50% of the print bed, makes removing print challenging

**Expected results**
1. print completes
2. printer sends print head home (rear right hand corner)

**Additional information**
I provided a fix at https://github.com/Ultimaker/Cura/pull/6450

I have several JG Aurora printers, it looks like the contributed change for the A1/A3/A5 was used for the z-603S. The A1/A5 profiles are great, as they are a different style of printer, sending the print bed to the front works great. However the z-603S is a corexy style printer, so the print bed only moves up and down, the print head should dock in the rear right (home/origin), but you do not want to home the z-axis at the end of the print because about 50% of the print head and the x-axis rods the print head travels would impede the print on the print bed.

The fix above simply homes the y-axis instead of sending it to the front.

**Comment by rburema** [comment]
Seems like your fix was merged already! I'm closing this.
