### ISSUE TITLE
[4.3] and older: Print sequence of skirt and prime tower brim

### ISSUE THREAD

**Issue by Schleichmichl** [Ultimaker/Cura#6455]
**Application version**

4.3
**Platform**

Windows 10

**Printer**

[PrimeTowerbrimBeforeSkirt.zip](https://github.com/Ultimaker/Cura/files/3675296/PrimeTowerbrimBeforeSkirt.zip)

**Reproduction steps**

1) Open attached project file
2) Slice

**Actual results**

Brim of prime tower is printed first

**Expected results**

Skirt must be printed first

The Skirt is there to prime the nozzle. Also, you can check if print bed calibration is fine for this job. The brim of the prime tower should stabilize the tower. If it is only printed partly, this could get a problem in the end of the print, thus wasting a lot of time, material and energy.

**Additional information**

![image](https://user-images.githubusercontent.com/5862890/65948870-5c0bee80-e43b-11e9-9892-e5e646cc1555.png)

**Comment by nallath** [comment]
We're looking into it to see if we can find a quick fix.

**Comment by Ghostkeeper** [comment]
Thanks for the report!
