### ISSUE TITLE
MeshType ModifySettingsforOverlap does not work for Horizontal Expansion setting

### ISSUE THREAD

**Issue by daT4v1s** [Ultimaker/Cura#6457]
**Application version**

4.3.0

**Platform**

Linux Ubuntu LTS 18.04 Intel Graphics

**Printer**

ultimaker 2+

**Reproduction steps**

1. import stl with thin text
2. apply a horizontal expansion value of -0.1mm
3. since the text is now mangled/corrupted, exclude horizontal expansion where the text is
by adding an object, that envelops just the text-part of the shape
4. Set the new object's MeshType as ModifySettingsforOverlap, and add custom settings HorizontalExpansion, and set to 0.0mm

**Actual results**

the text is still corrupted, the local settings are not followed, only the global ones

**Expected results**

HorizontalExpansion of -0.1mm,
 except where the ModifySetting block that envelops the text is

**Additional information**

![animated](https://user-images.githubusercontent.com/47403824/65935456-30f7af80-e3e7-11e9-9f54-1146e6519973.png)

**Comment by Ghostkeeper** [comment]
Yes, right now we apply horizontal expansion before the special mesh types. This way the settings can be changed of part of the expanded mesh. Like this:

![Screenshot from 2019-10-02 09-48-05](https://user-images.githubusercontent.com/2448634/66026762-0726b180-e4e9-11e9-9a21-2322182fc2a7.png)

We can support one or the other, not both.

**Comment by Ghostkeeper** [comment]
While we think that the suggested precedence would be more useful than the current one, we don't consider it very important to change it around now. Let's defer this to a later time.

**Comment by daT4v1s** [comment]
workaround: 2 meshes with different settings
turn off AutomaticallyDropMesh (preference setting) to allow for positioning

**Comment by pyrokidd89** [comment]
I have this issue also. I would like to apply horizontal expansion to the first ~4 layers to reduce elephants foot. Can you explain more about this 2 mesh workaround?

**Comment by Ghostkeeper** [comment]
What daT4v1s meant is to actually break up the 3D model (e.g. STL) into 2 model files. One model file is the large structure of the model, the other is the text. Then apply the horizontal expansion only on the big model. In your case, you could cut your model into 2 parts: One thin model that is just the bottom 4 layers, and another model for the rest of the print. Then stack them on top of each other (perhaps with Ctrl+G as an actual merge like one would for dual extrusion) Then you can adjust the horizontal expansion differently for those two models.

We have a different workaround for the original use case here now as well, with a separate Horizontal Expansion setting for holes.
