### ISSUE TITLE
The timing label partialy hides the layers bar in monitor mode

### ISSUE THREAD

**Issue by AMI3** [Ultimaker/Cura#6466]
**Application version**

**Platform**

cura 4.3.0
windows 10

**Printer**

**Reproduction steps**

move from prepare to plan tab

**Actual results**

the program calculated the time it would take and showed it on an unmovable label, which partialy hides the layer bar

**Expected results**

**Additional information**

screenshot added
![cura_bug](https://user-images.githubusercontent.com/56076966/66045957-660e1a00-e52d-11e9-9636-415585f5e8cf.png)

**Comment by Ghostkeeper** [comment]
Yup, I see it. It seems to happen if the window is smaller about the height of an 11" screen or so.

**Comment by Liger0** [comment]
Also related to the GUI, the layer number is hidden by the profile settings.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
