### ISSUE TITLE
Support Thickness

### ISSUE THREAD

**Issue by B14d3r11** [Ultimaker/Cura#6472]
After upgrading from 4.0 to 4.3 my supports are stupid thick and take ALOT of effort from flush cutters to even cut through them (i even tried brand new out of package ones)

**Comment by Ghostkeeper** [comment]
Do you have a project file to share with us that reproduces the problem? When it slices with stupid thick supports, press File -> Save... and zip the resulting file, then upload it here. We may be able to point out a particular setting that's causing this then.

**Comment by B14d3r11** [comment]
[Pan Hooks.zip](https://github.com/Ultimaker/Cura/files/3693652/Pan.Hooks.zip)

I printed these and it was fairly difficult to snap off the supports. I kept the same settings before the 4.0 to 4.3 upgrade I did

**Comment by Ghostkeeper** [comment]
That's not a project file but the g-code. I can't see all your settings then. I do see that you've enabled Conical Support and gave it a minimum diameter of 25mm though. That's something you might want to disable since it's not something you're using in this print.

**Comment by B14d3r11** [comment]
Yeah sorry, I misread what you said. Heres the project file (I think?)
[Project.zip](https://github.com/Ultimaker/Cura/files/3697988/Project.zip)

**Comment by Ghostkeeper** [comment]
That's a project file! It's not made with the same settings as what you were using for that g-code though.

**Comment by Ghostkeeper** [comment]
Ah, it's weird. I have to import the project twice in order to get it to load PLA - Coarse. Buggy there. And now it also has conical support enabled which I saw from your g-code.

**Comment by Ghostkeeper** [comment]
It doesn't look particularly fat to me.

![Screenshot from 2019-10-10 10-32-43](https://user-images.githubusercontent.com/2448634/66552348-b3dfdf00-eb38-11e9-9c59-d79435125d90.png)

Maybe you mean that the Support Wall Line Count is set to 1? If you set that to 0, does that solve your issue?

**Comment by B14d3r11** [comment]
The supports are thicker now than they were before. When it prints they were just, thinner. And I am using the same settings from 4.0 to 4.3 just Cura changed...

Its just harder to remove supports now than it was before

I am about to print something so i can try to show you what the supports look like now

**Comment by Ghostkeeper** [comment]
Maybe you need to reduce the support line width? Is that what you mean?
