### ISSUE TITLE
Improve Zoom Behavior

### ISSUE THREAD

**Issue by alsmithson** [Ultimaker/Cura#6476]
Zooming in Cura (and to be fair, PrusaSlicer and IdeaMaker) is a multi-step affair because zoom is always based on the screen center. You have to zoom, pan, zoom more, pan again, etc. This is okay if you have a 3-button mouse, but is tedious on a laptop sans mouse.

However, with zooming based on the cursor position, one can usually zoom to the desired position in a single motion, mouse or not. Corel Draw, Google Maps, MapInfo, and many other programs do this. Adobe products and Fusion 360 work this way with a mouse, but do not work with a trackpad.

Another option is windowed zooming, but that would require several interface changes and would be much more work to implement.

Zoom on cursor would make navigation within Cura much faster and all Cura users would benefit from this new feature, especially laptop users.

**Comment by nallath** [comment]
Check preferences-> configure cura -> Zoom towards mouse direction
