### ISSUE TITLE
[4.3] Printer and Materials parameters suddenly change or disappear

### ISSUE THREAD

**Issue by benjacusu** [Ultimaker/Cura#6478]
**Application version**
Cura 4.3

**Platform**
Windows 10

**Printer**
Custom FFF Printer whith 1 extruder

**Reproduction steps**
While setting the parameters to generate the .gcode, the selected custom material disappears. Also the parameters of the printer, start and end of gcode change.

**Actual results**
In order for the .gcode to be generated correctly, it is necessary to manually modify the parameters of the printer each time a slice is made.

**Expected results**
In previous versions, the parameters only needed to be loaded once. They only changed when I modified them.

**Additional information**
 I have uninstalled the software and reinstalled to test if the problem was solved but it persists.

**Comment by Ellecross** [comment]
@benjacusu Did you accidentally submit this ticket unfinished? 
Can you please complete it, otherwise, we're going to close it.

**Comment by Ghostkeeper** [comment]
(benjacusu has edited his ticket to complete the template.)

Basically what the report seems to be, is:

* Add a custom material.
* Change any setting.
* The material disappears?

I don't see that happening though. I duplicated PLA and renamed it to BLA. Then I changed the infill density to 42%. BLA was still selected.

**Comment by deathfrozen** [comment]
Also found this problem. Can't maintain the correct diameter of plastic in the extruder settings - resets to default.
