### ISSUE TITLE
Firmware update is stuck / crashes

### ISSUE THREAD

**Issue by MetrohmAutolab** [Ultimaker/Cura#6481]
New firmware version 5.1.94 is placed on usb and put into Ultimaker S5.
Just done after a print, when one of the cores was still cooling down.
When I installed the firmare, it is stucked for a few hours already and the same print core is still 'cooling down'. The firmare is still trying to install, but nothing happens.

Any advice on what to do?

**Comment by nallath** [comment]
Since this isn't a Cura issue but something with the S5 itself, you will need to contact your local reseller for support.

**Comment by Ghostkeeper** [comment]
(Generally you'll want to download a system restore image and reinstall the firmware that way.)
