### ISSUE TITLE
Fail to import Ender 3 print profile in Cura 4.3

### ISSUE THREAD

**Issue by MisterPrintf** [Ultimaker/Cura#6485]
**Application Version**

Cura 4.3

**Platform**

Windows 7

**Printer**

Creality Ender 3 included with Cura by default.

**Steps to Reproduce**

Select the Creality Ender 3 printer and attempt to import the included profile.

**Actual Results**

Cura creates a pop-up which gives the following message:
Failed to import profile from C:/Users/Brandt/Documents/3D Prints/Thingiverse Profiles/1.0 Final.curaprofile: Could not find a quality type fast for the current configuration.

**Expected results**

The profile should import correctly,

**Additional Information**

[1.0 Final.zip](https://github.com/Ultimaker/Cura/files/3693447/1.0.Final.zip)

**Comment by Ghostkeeper** [comment]
This is because the profile was based off a quality profile that doesn't exist any more in Cura 4.3. See also https://github.com/Ultimaker/Cura/issues/6453 for more of an explanation.
