### ISSUE TITLE
Qidi X-Pro Support

### ISSUE THREAD

**Issue by CryptoKong** [Ultimaker/Cura#6489]
It would be great if you could add support for the Qidi X-pro in the "add printer" section, I found some start/ end Gcode online that someone put together but it doesn't seem to be working too well for me.

**Comment by nallath** [comment]
All third party printers (Non- Ultimaker printers) have been added by a community contributor. So if you want the printer to be added, you will either have to make a pull request to do so, or find someone to help you with that.
