### ISSUE TITLE
monitor: show the current xy coordinate in printer control

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6497]
monitor: show the current xy coordinate in printer control

**Comment by Ghostkeeper** [comment]
This could be implemented with the [M114](https://reprap.org/wiki/G-code#M114:_Get_Current_Position) command in a similar way to how we currently display the temperature.

**Comment by Ghostkeeper** [comment]
It's been decided that we won't implement this at all. Just use Pronterface instead, that's what that software is for.
