### ISSUE TITLE
ironing Issue

### ISSUE THREAD

**Issue by kaeltaz** [Ultimaker/Cura#6510]
![image0](https://user-images.githubusercontent.com/25663430/66481918-2d78be00-eaa2-11e9-9d31-e6e12200c3e2.jpeg)
3d printer after ironing scratches the print surface.

**Comment by smartavionics** [comment]
Set combing to "no skin". Also, if you don't use z-hop, perhaps you should?

**Comment by kaeltaz** [comment]
I have set combing mode to "no skin". I don't want to use z-hop all over print.

**Comment by Ghostkeeper** [comment]
Setting it to No Skin should cause it to retract. Hopefully that reduces the issue. The only other way to prevent scratching the skin is to go over the skin, i.e. z hop. So this is expected behaviour then.

**Comment by kaeltaz** [comment]
> Setting it to No Skin should cause it to retract

Unfortunately, this does not help solve the problem.

**Comment by Ghostkeeper** [comment]
What is your expected behaviour then?

**Comment by Ghostkeeper** [comment]
Moved to https://github.com/Ultimaker/Cura/issues/6517 I guess.
