### ISSUE TITLE
Position with Cura 4.3.0

### ISSUE THREAD

**Issue by GilbertGC** [Ultimaker/Cura#6529]
After preparing the object, I save it as usual. 
when I transfer to my 3D printer Anet A8, it do not start at the middle of the bed but just in the left front side of it;
I changed the configuration of the printer in Cura but still the same problem.

**Comment by GilbertGC** [comment]
I change the size of bed
The origin is at center, I check the G code, from Cura,  With another
software and I find the object near the bed!!
There is some problem with Cura 4.3.0 I was using another version
without any problem.

Best regards

Gilbert Couic

couicg@orange.fr

Tel mobile +33(0)683751383


Le lun. 14 oct. 2019 à 09:01, Aldo Hoeben <notifications@github.com> a
écrit :

**Comment by fieldOfView** [comment]
Like I said above:

> In Machine Settings, make sure the "Origin at center" setting is **not** checked. This option should basically only be used for delta-style printers.

**Comment by GilbertGC** [comment]
Ok 
I will try!

**Comment by GilbertGC** [comment]
Nice!!
Working correctly now.
the other problem I have also is to connect my printer to Cura, 
Cura did not find it. It is on com3.
and Cura did not see anything.

**Comment by Ghostkeeper** [comment]
Using Printrun or something similar, do you know what baud rate the printer is on and how the printer responds to a temperature probe with `M105`?

I'll close this issue since the original problem has been fixed. We can't change it in the mainline Cura distribution since we don't have an Anet A8 printer definition.

**Comment by GilbertGC** [comment]
ok

Thanks
Best regards

Gilbert Couic

couicg@orange.fr

Tel mobile +33(0)683751383


Le lun. 14 oct. 2019 à 14:38, Ghostkeeper <notifications@github.com> a
écrit :
