### ISSUE TITLE
Hang with SKR 1.3 + TMC2208 + DRV8825

### ISSUE THREAD

**Issue by anjoze** [Ultimaker/Cura#6531]
**Application version**

Cura 4.3
Cura 4.2

**Platform**

Windows 10

**Printer**

Hephestos with SKR 1.3
X and Y: TMC2208
Z and Extruder: DRV8825

**Reproduction steps**
Just print something

**Actual results**

It stops / freeze after 2 or 3 minutes

**Additional information**

Printing from USB
I'm using Repetier Host with no problem, printing for hours.
Tried disable the "anonymous data" as suggested here: https://github.com/Ultimaker/Cura/issues/4016

Does anybody have this configuration working?
Thanks for any help.

**Comment by Ghostkeeper** [comment]
To fix this, we'd need to know what Cura should send differently via USB. We don't have every printer available to test with.

> It stops / freeze after 2 or 3 minutes

Cura stops / freezes, or the printer stops / freezes?

**Comment by anjoze** [comment]
Ok, sorry for the missing info.
The printer freezes and the fans still running.
I'm not sure if the extruder and bed keep ON or OFF. I will test it maybe tomorrow and let you know.
I can click on Abort and the popup message comes, so it's not freezed but I'm unable to close CURA.
When I try to close it it will be stucked until I switch off the printer power supply.

**Comment by Ghostkeeper** [comment]
Could be either that the firmware breaks (which would be an issue for the BQ developers) or that Cura stops sending stuff. We've seen before that if some commands take a long time (such as heating commands) then Cura sends temperature probes to update its temperature as well and these temperature probes queue up too much causing the firmware to break itself. This may be similar, though your description is different with that it does print for 2 minutes.

**Comment by anjoze** [comment]
I've tested and it looks you are right, something is happening with temperature.
As you can see in the picture, the temperature is set to 242/60 but it stops to hold it.
In this test stopped at 14% and start to decrease temperature some seconds before.

On Repetier I'm using Crua 1.3
I have a inductive probe and no more extras like SD card or Screen.

![Freeze](https://user-images.githubusercontent.com/11679993/66833416-b9339400-ef53-11e9-9e9b-6b13e07512a4.png)

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
