### ISSUE TITLE
Prime tower

### ISSUE THREAD

**Issue by maaspt** [Ultimaker/Cura#6534]
Prime tower prints first layer before changing extruder.

When extruder is changed, it does not print prime tower, that layer of prime tower was already printed by the extruder that was printed first.

Prime tower should be printed only after extruder change, and color change.

**Comment by Ghostkeeper** [comment]
Cura considers it more important to print the first layer of the prime tower with the same material as the outer shell of the prime tower. The outer shell is always complete from bottom to top and is used for strength. Different materials don't adhere as well to each other as otherwise, so if the first layer is printed with the other extruder, the prime tower has more chance of falling over which ruins the print.

In the first layer, the skirt or brim is supposed to be priming for you. Is it not priming?

**Comment by maaspt** [comment]
No, in first layer it primes extruder 1 before printing part, and after skirt.

I removed brim or skirt to test, changed many setting, and getting always the same result.

I think this started after updating to Cura version 4.0, before was working ok.

The problem is that, in first layer with two colors, after printing prime and part with Extruder 1, it changes to extruder 2 but it does not prime after that change. Second color gets printed with remaing color from extruder 1.


Extruder 1 primed before part

![20191015_140505](https://user-images.githubusercontent.com/29154277/66834176-11b76100-ef55-11e9-8023-2ba31cd55a76.jpg)

Extruder 1 printing

![20191015_140518](https://user-images.githubusercontent.com/29154277/66834197-1aa83280-ef55-11e9-8dba-544838950873.jpg)

Extruder 2 printing without prime

![20191015_140557](https://user-images.githubusercontent.com/29154277/66834203-23006d80-ef55-11e9-9ae6-da0ce0e6fdbe.jpg)

Second layer extruder 1 not priming ok

![20191015_141113](https://user-images.githubusercontent.com/29154277/66834710-13cdef80-ef56-11e9-80e3-ddc049b3bda8.jpg)

**Comment by Ghostkeeper** [comment]
If you disable the skirt and brim then I'd indeed expect that it doesn't prime. The same will happen when you disable the skirt and brim in single extrusion prints.

If platform adhesion is enabled I'd expect it to prime an extra line with all extruders though. I've made a screenshot of that here when using brim:
![Screenshot from 2019-10-17 14-01-34](https://user-images.githubusercontent.com/2448634/67007005-f9228480-f0d5-11e9-92fe-3ba7d2ea4004.png)

And here from my settings guide when using skirt:
![Prime tower example screenshot](https://raw.githubusercontent.com/Ghostkeeper/SettingsGuide/master/resources/articles/images/prime_tower_brim_enable.png)

The function of the skirt is to prime. You can disable it if you don't want it to prime unnecessarily (e.g. if your printer's firmware always primes before a print or something). But normally you'll need at least a skirt.

**Comment by AbeFM** [comment]
I've noticed the same thing - it doesn't really effect my prints - but one COULD save a little material by having the skirt be only in the second material, allowing you to prime that nozzle.

Perhaps the inner part of the tower floor could be printed in the secondary material - the brim and first layer under the tower ExtA, but the circle WITHIN the tower could be ExtB?

**Comment by Ghostkeeper** [comment]
The inner part of the tower floor was chosen on purpose to be the same as the rest of the first layer to contribute more to adhesion of the prime tower. Otherwise it might fall over more easily.

**Comment by Ghostkeeper** [comment]
We'll close this as it's expected behaviour.
