### ISSUE TITLE
Infill layer Height

### ISSUE THREAD

**Issue by MichelCHAVOT** [Ultimaker/Cura#6538]
![Test](https://user-images.githubusercontent.com/36966985/66821982-a2854100-ef43-11e9-98e9-f6d4ce5925f9.jpg)
I use an infill layer thickness equal to 2 times the layer thickness.
This works very well, except if the infill density equals 100%. Is that normal?
Thanks

Michel CHAVOT.

**Comment by rburema** [comment]
Hi @MichelCHAVOT,

100% Infill _always_ defaults to the line pattern, as it's supposed to be solid. This is expected behaviour.

cheers, Remco.

**Comment by ninovanhooff** [comment]
The Cura Marketplace provides a SettingsGuide plugin with visual explanation. 
It mentions that some layers can be combined, which may explain why there is infill in layer 10 for 100% but not for 99%.
See
https://github.com/Ghostkeeper/SettingsGuide/blob/d954be25b30c1877ec7ce75a0b233367a2a46a13/resources/articles/infill_sparse_thickness.md

**Comment by Ghostkeeper** [comment]
Instead of infill it'll print everything with skin then. That tends to produce a stronger part since there will be no border any more between infill and skin.
