### ISSUE TITLE
Ironing causing extra travel moves when enabled

### ISSUE THREAD

**Issue by gvnlws** [Ultimaker/Cura#6544]
**Application version**
4.3 but have observed with previous versions too, just was not sure what was causing it.

**Platform**
Windows

**Printer**
Custom FDM printer based on default model with modified build plate settings.

**Reproduction steps**
Enable ironing for the whole model (untick "only highest layer")

**Actual results**
Noticed extra travel moves on external skin of object and sometimes a random 'top / bottom' coloured extrusion move outside of the object area.  This causes external print quality to deteriorate when using TPU. This is occuring throughout the whole model, even on layers where no ironing would be performed, i.e. no flat horizontal surfaces.

**Expected results**
Flat surfaces get ironed with no extra travel moves inserted.

Examples:

With ironing set to highest layer only or off it slices as expected
![image](https://user-images.githubusercontent.com/42818303/66922833-c28a3280-f01f-11e9-8545-be86c98c811c.png)

With ironing enabled for the whole object (no other changes to settings) we get this.
![image](https://user-images.githubusercontent.com/42818303/66922939-e6e60f00-f01f-11e9-8b8a-2417f6dfae31.png)

**Comment by smartavionics** [comment]
Possibly fixed by https://github.com/Ultimaker/CuraEngine/pull/1099 ?

**Comment by gvnlws** [comment]
Oh yes, that does seem to be the same behaviour I am seeing here. Thanks!

I did try to search but didn't think about searching the pull requests

**Comment by gvnlws** [comment]
Can confirm was fixed with latest Cura 4.4 version that included this fix. Thank you so much!
