### ISSUE TITLE
Cura Mirror and make overhangs printable

### ISSUE THREAD

**Issue by dienerbilt** [Ultimaker/Cura#6553]
If you mirror and object and make overhangs printable cura ignores infill and sets it to 100 percent as far as i can tell. Basically doubing the print time at best.

**Comment by Ghostkeeper** [comment]
Yes, I can reproduce that problem. Very weird!

The problem seems to be that the normal vectors are inside-out then. We should fix that in general (not particular to making overhang printable).

**Comment by dienerbilt** [comment]
Yeah it was a wierd part that im making for a customer and through me off
guard also. Great program other wise, its my goto. Thanks for the reply.

**Comment by LipuFei** [comment]
Fixed in https://github.com/Ultimaker/Uranium/pull/535
