### ISSUE TITLE
[4.3.0] global flow rate is not taken into gcode

### ISSUE THREAD

**Issue by High8** [Ultimaker/Cura#6558]
**Application version**
4.3.0

**Platform**
W10

**Printer**
Ender 3

**Reproduction steps**
When setting the Flow in the Expert settings -> Material -> Flow e.g. from 100 to 90% the generated gcode still contains the flow rate of 100%

[..]
M220 S100 ;Reset Feedrate
M221 S100 ;Reset Flowrate
G28 ;Home
[..]

no further code with an M221 line is created

**Actual results**
The flow is not adjusted unless the gcode is manually corrected

**Expected results**
The gcode should take the adjusted flow from the Cura setting

**Additional information**

**Comment by nallath** [comment]
That's because Cura changes the actual extrusion since we want to be able to estimate how much material is used.
