### ISSUE TITLE
Infill overlapping other lines in combination with infill steps [4.3.0]

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#6571]
**Application version**
4.3.0

**Printer**
Custom FDM printer

**Reproduction steps**
Enable infill steps and slice. More infill steps escalates the issue.
The issue is most noticeable on top layers or expanded top skin (or where it should be if I hadn't removed it with the "skin removal width").
See attached projects and pictures.

**Actual results**
Infill wall lines overlap each other and other lines in some cases.
(Not caused by the infill overlap setting!)

**Expected results**
no overlapping lines

**Additional information**
![Infill wall bug](https://user-images.githubusercontent.com/32172100/67400592-24addf00-f5ae-11e9-8a30-34f48b892ba0.PNG)
![infill wall bug2](https://user-images.githubusercontent.com/32172100/67400599-28416600-f5ae-11e9-8f66-31543a638f00.PNG)
[Infill wall bug.3mf.zip](https://github.com/Ultimaker/Cura/files/3762724/Infill.wall.bug.3mf.zip)

From another project, disabling infill steps fixes the issue. For some reason I also get more infill walls than asked for:
![3](https://user-images.githubusercontent.com/32172100/67401711-d39eea80-f5af-11e9-87c1-041ccc547826.PNG)
[Bugsteps.3mf.zip](https://github.com/Ultimaker/Cura/files/3762762/Bugsteps.3mf.zip)

**Comment by rburema** [comment]
Developers, I've made internal issue CURA-6926 to track this in our system.
