### ISSUE TITLE
How to make .curapackage files?

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#6573]
Is there a way to manually make .curapackage files?

**Comment by nallath** [comment]
The easiest way to do this is to upload them to contribute.ultimaker.com 

It will generate these packages even if you don't release them (so that you can test them locally if everything went right)

**Comment by maukcc** [comment]
This will not work as the package is not specifically for UM hardware :(
Please reopen this

**Comment by nallath** [comment]
So when you upload the package it immediately says that it must have UM hardware in it? 

Once you upload a package, you can click the SDK version numbers to download the package.

**Comment by maukcc** [comment]
Ahh, got it. click on the SDK to download.
Thanks !!

**Comment by Ghostkeeper** [comment]
For posterity, the .curapackage file is just a .zip archive so you can edit the contents with an archiver application.

**Comment by maukcc** [comment]
We can not edit or delete files that are in the curapackage file. We can add files and edit and delete the added files.
