### ISSUE TITLE
Horizontal Expansion - No minus

### ISSUE THREAD

**Issue by RegRayRat** [Ultimaker/Cura#6575]
**Application version**

**Platform**

**Printer**

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by nallath** [comment]
Could you please fill in the

**Comment by Ghostkeeper** [comment]
The template was filled in but invisible because it was still in the HTML comment tags. I've updated the template now so that this can't happen any more.

Duplicate of https://github.com/Ultimaker/Cura/issues/6277
