### ISSUE TITLE
User preference for New Project to switch to default view

### ISSUE THREAD

**Issue by photodude** [Ultimaker/Cura#6588]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Currently when you select "New Project" the view remains on the view you were currently on.

What I would like to see is the ability to set a User Preference to go to the user's desired view automatically on selecting "New Project" 

For myself, if I'm on the Preview view with a model I've sliced and I select "New Project" from the menu I would like to have the view switch to the "Prepare" view. Remaining on the Preview view doesn't seem logical for me with a dual extruder where I often need to do a large amount of preparation selecting which nozzle does what before slicing. But I can see how some users might have a different workflow preference.

User preference options for "new project"
- Default
  - remains on current view
- Prepare
  - switches to prepare view
- Preview
  - switches to preview
    - maybe also add an option to "auto slice on adding a model in the preview view" to shorten the steps a user has to do. 

**Describe alternatives you've considered**
Alternative is to keep the existing behavior, but with a dual extruder, I'm always having to switch.
Another alternative is to always switch to the Prepare view on New Project, but some users may have a different preference.

**Affected users and/or printers**
Dual extruder printers, and Tool change printers, and users of those printers would likely benefit the most. Other users may find this fits their preferred workflow

**Additional context**

**Comment by nallath** [comment]
I've added a very basic variant of this in 41d1ef5f932144511fd6517fc6126b80c45c3261
