### ISSUE TITLE
Scale UI is mixed up when scaling in non-uniform mode.

### ISSUE THREAD

**Issue by mastory** [Ultimaker/Cura#659]
Changing scale with the 'Uniform scale' box unticked, gives unexpected, non-intuitive results.  Changing the X scale on its own seems to work as expected.  When a new scale is typed into the X field, the model changes scale in the correct direction, and the typed text is retained in the correct text field.  X axis non-uniform scaling seems to work as expected.

If a new scale is typed into the Y scale field, the model changes scale on the Y axis, the text in the Y field reverts back to 100, and the text in the Z field updates to the scale factor entered into the Y box.  The scale of the model does not change in respect to Z.

Non-uniform scaling on the Z axis works in the same way as on the Y, but in reverse.

I first noticed this in the 1.99.0 version, where the model acted the same as above, but the input text field stayed in the box where it was typed.  I would hazard a guess that someone may have already looked into this, but maybe didn't dig deep enough since the behavior is slightly different.

**Comment by nallath** [comment]
This should be fixed for the closed beta.
