### ISSUE TITLE
Layer View/Color Scheme color labels become incorrect view

### ISSUE THREAD

**Issue by gravit0n78** [Ultimaker/Cura#6603]
Application Version
4.3.0
Platform
Windows 8.1 , 64 bit

Printer
ender 3 pro + skr1.3 + marlin 2

Steps to Reproduce
Import model  (also this bug appeared without slising, just switch to layer view)
Slice model
Switch to Layer View
Set layer view overlay to Feedrate or Layer Thickness
Select your model
Observe the color chart's labels.

Actual Results (as you can see, the color scheme is rotated 90 degrees, which makes it difficult to evaluate print settings)
![2019-10-31_104204](https://user-images.githubusercontent.com/52930917/67928052-29385000-fbcb-11e9-8991-08ca141832c3.jpg)

Expected results 
![50731619-79b35e00-111e-11e9-936c-c88674201441](https://user-images.githubusercontent.com/52930917/67927813-9992a180-fbca-11e9-9bbe-b20c4df274dc.jpg)

This bug appeared in my versions 3.6 / 4.0.0 / 4.2.0 also it does not depend on the application interface theme and plugin Sidebar GUI

**Comment by Ghostkeeper** [comment]
I've tried in Cura 4.3 and 4.4 (upcoming), but couldn't reproduce the issue. Could it be that this was accidentally fixed? Could you try this in Cura 4.3?
