### ISSUE TITLE
print completed is not saved across power cycle

### ISSUE THREAD

**Issue by marvin42b** [Ultimaker/Cura#6617]
**Application version**  4.2.1
(The version of the application this issue occurs with.)

**Platform** Linux, Ubuntu
uname -a
Linux irobot 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(Information about the operating system the issue occurs on. Include at least the operating system. In the case of visual glitches/issues, also include information about your graphics drivers and GPU.)

**Printer**
UM2extended
(Which printer was selected in Cura? If possible, please attach project file as .curaproject.3mf.zip.)

**Reproduction steps**
1. Something you did.
2. Something you did next.

Always if the last thing before I power off is to acknowledge that the last print has been removed then the next time I power up it is forgotten. This means that I have to stand next to the printer to wait for the message "remove print" to have the next job done.

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

The status of an empty platform should be put into non-volatile memory immediately after pushing the button so that it can be retrieved after the next power-up.

**Additional information**
(Extra information relevant to the issue, like screenshots. Don't forget to attach the log files with this issue report.)

**Comment by Ghostkeeper** [comment]
Cura does not save whether a print is completed or not, and is not intended to maintain information about a USB connection after power cycling your computer.

I think you wanted to report this at the [Ultimaker 2 firmware repository](https://github.com/Ultimaker/Ultimaker2Marlin/issues)?
