### ISSUE TITLE
Keep apart works on support blockers

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#6618]
**Application version**
4.3

**Platform**
?

**Printer**
?

**Reproduction steps**
1. Have keep models apart enabled in preferences
2. Load model
3. Add a support blocker
4. Add a support blocker nearby

**Actual results**
Original support blocker gets pushed away

**Expected results**
Support blocker don't listen to the keep apart preference

**Additional information**
From 
https://www.reddit.com/r/3Dprinting/comments/dqnhe2/cura_43_custom_support_issue/

**Comment by fieldOfView** [comment]
I can't reproduce this on master

**Comment by BagelOrb** [comment]
Can't reproduce either. I'm assuming this got fixed somehow.
