### ISSUE TITLE
[FR] printer name in Machine Settings dialog

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#6622]
**Is your feature request related to a problem? Please describe.**

Not really a problem... When editing printer properties, the dialog does not show the printer name, and the user could be confused. At leats I am... ;) (1 printer, 8 printers created depending on the nozzle diameter). But many people have 2, 5 or 20 printers !

**Describe the solution you'd like**

The currently edited printer name could be dispalyed in the "Machine Settings" dialog title bar, or even be editable in the "Printer" panel.

**Describe alternatives you've considered**

Workaround : moving the "Machine Settings" dialog uncovers the slected printer name in the "Preferences" dialog.

**Affected users and/or printers**

Every user, every printer, as long as the user owns at least 2 printers, or defines one printer for each and every nozzle he/she will mount on he/she's printer.

**Additional context**

The blank edit fields "Start Gcode" & "End G-code" bug is still there... But this is another (old) story...
This being said, I think that adding the printer name to the "Machine Settings" dialog title bar is very little work ! At least I could do it if the GUI was written with Win32 SDK. But for some reason, it is written with Qt. And I'm too old to learn Qt. ;) (just kidding about multiplatform dev)

**Comment by LipuFei** [comment]
Added in b843210fd

![image](https://user-images.githubusercontent.com/2630468/68197096-ed7dfb80-ffb9-11e9-81a8-2853517f37f3.png)
