### ISSUE TITLE
Printhead settings has a mind of it's own

### ISSUE THREAD

**Issue by FlailAway** [Ultimaker/Cura#6625]
**Application version**
4.3.0

**Platform**
Mint+Cinnamon

**Printer**
Custom

**Reproduction steps**
In Printhead Settings set 
X min = -10
Y min = -10
I need 30-behind the nozzle and 15 to the right
Click in X min and change to -30
Click Y-min box and X min reverts to -10 
Change Y min -15
Click X min box and Y-min reverts to -10
Now, change nothing and click Y min box and X-min now changes to -30

Even after they show the desired offsets with that merry dance in and out of boxes, nothing changes with the Shadow on the build plate. It still gives more clearance to the X-sides of things than the Y-front to back. It then crashes into the item just printed with the rear overhang of the head.

**Actual results**
As above

I have read about your philosophy on equal clearances, but this is crazy behaviour, changing things. https://www.youtube.com/watch?v=aqAUmgE3WyM

Why not hide all the tricky stuff (if that is what is happening) and let the user just give measurements for the 4 distances of the head relative to the nozzle point?
I need 30mm behind, 15 either side and 10 to the front.

**Comment by Ghostkeeper** [comment]
This issue is fixed in Cura 4.4 (actual commit here: https://github.com/Ultimaker/Cura/commit/497648ffe71f1a96fb7d2f63d0a38f6b88d372d4). It should not be resetting these values as soon as they lose focus.

It should then basically behave as you suggest.
