### ISSUE TITLE
[2.1] fan speed doesn't seem to change

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#663]
Today I tried to play with the fan settings to improve my print of this ornament: http://www.thingiverse.com/thing:1349055

At the beginning the problem was that the ornament was strongly wrapping. So I decided to start (and test) with a fan speed of 50% and choose 90% as max speed. So I set to start with min. speed and go up to max. speed at the 6th layer, like this:
![cura](https://cloud.githubusercontent.com/assets/1847437/13715436/ec10dc00-e7d4-11e5-88a7-028504304f89.png)

GCode: https://mega.nz/#!oxoTQRCD

Did I get something wrong or did I catch a bug?

**Comment by daid** [comment]
We've noticed a bug with the fan speed in relation to material selection ourselves. So maybe this is the same bug? (The fan speed in the material selection seems to overrule the use value)

**Comment by nallath** [comment]
There is also a reported bug that the fan will always go on, regardless of what you set at "fan full on at height" value.

**Comment by thopiekar** [comment]
If you mean the issue report I made before, then it was a firmware bug that
bq already fixed.
Isn't it closed?

**Comment by nallath** [comment]
It seems to be an engine issue. It actually sends a g-code that puts the fanspeed at full on.

**Comment by thopiekar** [comment]
Ok, in the past I sent the command to change the fan speed manually via
serial console and had the behaviour too. So contacted bq, they confirmed
that and they fixed it in the latest firmware.

**Comment by nallath** [comment]
I assume this is no longer an issue, as we had a number of fixes regarding this recently. If this is still an issue, please re-open it.
