### ISSUE TITLE
Feature request: Settings | Collapse All button

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#6631]
As referenced on the Cura Forum:
https://community.ultimaker.com/topic/26462-feature-request-settings-panel-collapse-all-button/

Right now every job sliced is the same process:

- Close all the groups
- Open the top Group (Quality) confirm or change
- Close that group, open the next.
- {...} repeat all the way down the settings, times about 15 settings groups.

This is truly tedious job after job.  It would be really helpful if there was a button that would 'collapse all' of the settings groups (Quality, Shell, Infil, Material {...}). So the user can then just walk down the groups one at a time double checking everything, without having to either open/close every group every time or leaving them all open for a massively long list to scroll every time. 
![image](https://user-images.githubusercontent.com/11351506/68311030-f08eef80-007e-11ea-9d7a-6543513f75e9.png)

**Comment by alexjx** [comment]
I would like this feature.

**Comment by nallath** [comment]
For our reference: CURA-6959

**Comment by nallath** [comment]
We just merged this, so it will be in 4.5>

**Comment by tlhintoq** [comment]
AWESOME!

**Comment by LouiseTGUK** [comment]
Even better.. Have ability to only open one section at a time, so when you open a second one it closed the first..

Many progs with long categorized lists like this have that ability including my photo editor, makes things MUCH easier to navigate
