### ISSUE TITLE
No pause at height plugin works with height in mm, just layer.

### ISSUE THREAD

**Issue by hedefalk** [Ultimaker/Cura#6634]
**Application version**
4.3.0 
**Platform**
OSX

**Printer**
UM2

**Reproduction steps**
1. Adding a post-process to pause at height:
![image](https://user-images.githubusercontent.com/116520/68340676-2b2c7280-00e7-11ea-9c19-06076c12b6f6.png)

2. Slice

**Actual results**
No postprocessing.

The vactrol1 file is without the PauseAtHeight and vactrol2 is with the plugin enabled

```
✗ diff ~/Desktop/temp/UM2_vactrol1.gcode ~/Desktop/temp/UM2_vactrol2.gcode
11a12
> ;POSTPROCESSED
```

**Expected results**
I expect actual GCode to be inserted.

**Additional info**
See nothing but this in log:

```
tail -1000f  ~/Library/Application\ Support/cura/4.3/cura.log | grep ERROR

2019-11-06 22:43:59,700 - ERROR - [MainThread] LocalContainerProvider.LocalContainerProvider.saveContainer [91]: Failed to get MIME type for container type [<class 'cura.Settings.PerObjectContainerStack.PerObjectContainerStack'>]
```

**Comment by hedefalk** [comment]
Ooh, it was in fact that all the plugins I tried with setting layer height in mm doesn't work. It works for an integer layer height, but not for defining the height in mm. They all just silently fail in this case. Updated header

**Comment by Ghostkeeper** [comment]
Looks like it just pauses too late? I tried to slice a cube with the pause height set to 5mm (the default). It produced this g-code:

```
G0 X160.56 Y124.44
G0 X160.8 Y124.2
;TIME_ELAPSED:624.086894
;TYPE:CUSTOM
;added code by post processing
;script: PauseAtHeight.py
;current z: 9.1
;current height: 9.1
M0 ; Do the actual pause
;LAYER:89
;MESH:cube.stl
G0 X160.8 Y124.2 Z9.1
M204 S1000
M205 X10 Y10
;TYPE:WALL-INNER
G1 F1800 X160.8 Y115.8 E97.43324
G1 X169.2 Y115.8 E97.47274
```

**Comment by hedefalk** [comment]
I got nothing, see my diff. I paused a 7mm print at 3.5. Overshoot? But why?

**Comment by Ghostkeeper** [comment]
If the pause happens above the print, that could happen. Like overshoot, yeah.

But that it pauses at the wrong height is definitely buggy.

**Comment by b-morgan** [comment]
I believe you will discover the problem if you modify the PauseAtHeight.py script to add a couple of lines, one to print the layer_0_z (which I suspect is the problem) and one to print the pause_height (for a sanity check):

`                prepend_gcode = ";TYPE:CUSTOM\n"
                prepend_gcode += ";added code by post processing\n"
                prepend_gcode += ";script: PauseAtHeight.py\n"
                if pause_at == "height":
                    prepend_gcode += ";layer_0_z: {z}\n".format(z = layer_0_z)
                    prepend_gcode += ";current z: {z}\n".format(z = current_z)
                    prepend_gcode += ";pause height: {height}\n".format(height = pause_height)
                    prepend_gcode += ";current height: {height}\n".format(height = current_height)
                else:
                    prepend_gcode += ";current layer: {layer}\n".format(layer = current_layer)
`

**Comment by nallath** [comment]
This has been fixed by https://github.com/Ultimaker/Cura/pull/6690
