### ISSUE TITLE
[4.3.0] - Windows 10 - Managing Materials Causes Cure to Exit

### ISSUE THREAD

**Issue by lathemaster** [Ultimaker/Cura#6647]
**Application version**
4.3.0

**Platform**
Windows 10

**Printer**
TEVO

**Reproduction steps**
Preferences->Configure Cura->Materials
**Actual results**
Cura Crashes
**Expected results**
Manage my Materials

**Additional information**
N/A

**Comment by nallath** [comment]
Please fill in the entire bug report by including the log files. This is not enough information for us to debug / resolve the issue.

**Comment by lathemaster** [comment]
Solved - Issue was mine wrong printer selected
