### ISSUE TITLE
Cura Plugin

### ISSUE THREAD

**Issue by prahjister** [Ultimaker/Cura#6653]
Hello there.

I don't have enough programming experience so I thought I would post this here. I created a spreadsheet to help with dialing in retraction settings and I think it would be a great plug in for cura and make it easier.

Here is the write up I did explaining how to use it. https://www.cnx-software.com/2019/09/05/how-to-easily-calibrate-retraction-in-3d-printers/

If this could be incorporated into cura i think it would be fantastic and make it much simpler to understand. I have found it very useful

**Comment by Ghostkeeper** [comment]
Here are some example plug-ins that you can draw from: https://github.com/Ultimaker?utf8=%E2%9C%93&q=UraniumExample

I hope that this helps to create your plug-in. However if you're making a Cura plug-in, perhaps the user would expect some integration with Cura's UI as well to guide them to tuning their retraction settings.

I understand that you're posting this here with the hope that someone develops a plug-in for you. With a title like this I don't think anyone will really pick this up though. Perhaps you'll have more luck on the [Ultimaker forum dedicated to Cura and plug-ins](https://community.ultimaker.com/forum/108-cura-plugins/)?
