### ISSUE TITLE
Gaps in corners of walls when they are horizontal

### ISSUE THREAD

**Issue by ShakieVan** [Ultimaker/Cura#6659]
**Application version**
4.3.0

**Platform**
Win10

**Printer**
custom FFF printer
Sidewinder X1

**Reproduction steps**
1: Insert the screw
2: Place it vertical
3: Slice

**Actual results**
There are gaps in the corners, where the "next" wall sits on the infill. So the part breaks at this point at low forces.
When placing it horizontal, The walls are strongly connected.
![Cura Gap](https://user-images.githubusercontent.com/55868847/68897567-10cd4700-072e-11ea-848f-bba1c2f9694a.jpg)

**Expected results**
The walls should connect in the corners like they do when placing it horizontal.

**Additional information**
[Cura Gap.zip](https://github.com/Ultimaker/Cura/files/3848687/Cura.Gap.zip)

**Comment by smartavionics** [comment]
It's happening because that skin region is narrower than the value of Skin Removal Width. If you set that to 0 the skin region survives...

![Screenshot 2019-11-14 at 21 56 35](https://user-images.githubusercontent.com/585618/68899574-e2e60380-0729-11ea-8532-4015ae736f63.png)

**Comment by ShakieVan** [comment]
![Thumbs Up](https://user-images.githubusercontent.com/55868847/68927616-73ebc780-0788-11ea-8b48-9f8017272f9e.jpg)

Thank You!!!

**Comment by Ghostkeeper** [comment]
This is expected behaviour. It's really part of the [trade-off](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/bottom_skin_preshrink.md) when adjusting this setting.
