### ISSUE TITLE
UMODE BUG Cura 4.3.0 setting: Enable Support Interface activates travels outside object.

### ISSUE THREAD

**Issue by PvD77** [Ultimaker/Cura#6660]
**Application version**
Cura 4.3.0

**Platform**
Windows

**Printer**
Ultimaker Original Dual Extruder

**Reproduction steps**
Setting the setting: Enable Support Interface
(When this setting or support is not used, there is no problem)

**Actual results**
Extra long travels outside the object. (not needed)

**Expected results**
Normal result, but without the extra travels.
![UMODE BUG Cura 4_3_0 setting Enable Support Interface activates travels outside object BUG](https://user-images.githubusercontent.com/57791198/68928739-1efd8080-078b-11ea-91b8-761bf4d2a869.png)
![UMODE BUG Cura 4_3_0 setting Enable Support Interface activates travels outside object GOOD](https://user-images.githubusercontent.com/57791198/68928778-3177ba00-078b-11ea-94be-f6e5202ef563.png)

**Additional information**
(Extra information relevant to the issue, like screenshots. Don't forget to attach the log files with this issue report.)

**Comment by Ellecross** [comment]
UM Cura devs, see CURA-7018

**Comment by PvD77** [comment]
Hello Ellecross,

CURA-7018 ? Please help me further....

I have discovered that this position outside the model is the prime tower position.
Even when the setting is not activated.
When the other nozzle is activated, the head goes to the prime tower position.
And leaving directly, without building the prime tower.

If I activate the prime tower and move it. (X, Y location) 
And then deactivate the prime tower again.
Then the head goes to the new position!

**Comment by Ghostkeeper** [comment]
> CURA-7018 ? Please help me further....

Sorry for the confusion. This is a reference to an internal issue in Ultimaker's tracker. It means it was put in our planning software.

The extra information that it's travelling to the prime tower location helps. Thanks!
