### ISSUE TITLE
4.4: Windows: Start menu entry in separate folder

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#6664]
Just installed the installer I received from @rburema and I noticed the following.
Normally, when installing Cura on Windows, it will be placed in the Ultimaker Cura directory in the start menu.
However, using this installer it gets placed into a separate versioned directory like this:
![image](https://user-images.githubusercontent.com/1847437/68991512-eb405a80-085f-11ea-863d-8a7e71b9da08.png)
I would expect the shortcut to be placed with all the other shortcuts. Additionally, it would just lokk very clean as before.

**Comment by Ghostkeeper** [comment]
Yeah I noticed this as well using Windows 8.1.

**Comment by Ellecross** [comment]
It started happening in Cura 4.3. Hehe
![image](https://user-images.githubusercontent.com/32929710/70158326-58088100-16b7-11ea-97a7-6a7cf3612c07.png)
We'll take a look, maybe something not too hard to resolve.

**Comment by Ellecross** [comment]
UM devs, see CURA-7029

**Comment by thopiekar** [comment]
@Ellecross No problem! Thank you for bringing this onto your board! :+1: 
I'm doing good. Just busy more than ever. Hope you are doing well, too! :blush:

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
