### ISSUE TITLE
[2.1] Cherry-picking commits made on USBPrinting

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#667]
Yesterday I sent a PR where I translated the if-clauses into dictionaries.
Do you want this in [2.1]? If you are too busy I would try to prepare another PR for [2.1] where I cherry-pick the commits from [master].

* The PR: https://github.com/Ultimaker/Cura/pull/664

**Comment by nallath** [comment]
How big do you think the chances of regression are? That the main concern right now. We should only be fixing bugs in 2.1 (in order to minimise the risk of stuff going wrong)

**Comment by thopiekar** [comment]
I think it is save to be moved into 2.1.
It should make easier for vendors adding their firmware into Cura. On top
of the dictionary, which lists the firmware files, there is also a short
description how to add the firmware files, too.

I'm fine if you like to keep it for the next release, but I think it might
be useful for the current release, too.

**Comment by Ghostkeeper** [comment]
I agree that it is safe to be moved. The code is fairly simple, really contained and verified by me. But it doesn't add much value either since no change should be visible by the user.

**Comment by nallath** [comment]
Then let's just leave it how it is now (and save thopiekar the effort ;))

**Comment by thopiekar** [comment]
OK :+1:
