### ISSUE TITLE
Alternate direction of nozzle rotation.

### ISSUE THREAD

**Issue by ffaille** [Ultimaker/Cura#6672]
I've noticed that with some nozzle (reprappro quickset nozzle is the best example) print defaults due to plastic accumulation (mainly when printing a little above nothing - starting with a angle near 30%) are always on the same side of the printed part.

Could you add an option to alternate the direction of rotation of the nozzle to each layer for wall printing ? This will prevent the accumulation of plastic and distribute the remaining printing defects over the entire part.

I have, of course, tried to better calibrate and adjust everything that could be calibrated. I have tested different qualities of plastics at different temperatures with different printing speeds. The problem observed is that the plastic remains "stuck" to the nozzle.

I have noticed these kinds of problems when the nozzles are not very sharp.

I think that this option has the potential to improve the rendering in any case.

**Comment by rburema** [comment]
Have you tried putting the 'Z Seam Alignment' to 'Random'?

**Comment by ffaille** [comment]
Yes, this is not a Z-seam problem related.

**Comment by Ghostkeeper** [comment]
I'm not really sure how alternating the direction of printing walls would fix your overextrusion problem though.

**Comment by jf3303** [comment]
I would also like to alternate the direction of rotation. I think it would help to make perfect circle with cheap printers. Because of small loose in the printer parts I see crack in thin cylinders between internal and external shell.

**Comment by Ghostkeeper** [comment]
But if you switch directions of the wall lines you would see more cracks, due to hysteresis, right?

**Comment by jf3303** [comment]
The defect would be on the opposite side from the previous layer each time. Structural integrity would be optimized at the cost of an inferior surface finish.

**Comment by Ghostkeeper** [comment]
If the Seam settings still work the same way, the seam would still be placed in the same location as it is now, not alternating from the previous layer.

**Comment by dnasir** [comment]
I think this would be useful when dealing with overhangs as well. I noticed that my overhangs tend to slightly curl up on one side, usually at the seams.

Then again, I probably just need better cooling.

**Comment by rburema** [comment]
Already implemented as _"Alternate Wall Directions"_, under the _'Experimental'_ heading.

**Comment by Zomflax** [comment]
> 

Thank you, that is indeed a nice implementation! However, at first we were thinking of alternating the wall directions from one layer to another, but your option does more than that and alternate each printed lines, which is great! Then, would it be possible to have the lines of the same layer go in the same direction, but the next layer would have them in the opposite direction?

**Comment by rburema** [comment]
@Zomflax You're welcome! Currently, as written, the behaviours are indeed combined. Is this a problem in some way?

**Comment by Zomflax** [comment]
@rburema Actually, I noticed alternating the wall direction on the same layer results in a more "messy" surface, not really flat, which is pretty logic. So having the same wall direction on a layer would let the next layer to have a flat surface to stick on. But still having the walls going in the opposite direction for the next layer may help layer adhesion.
NB: Even without this option on, when doing cylinders, sometimes the walls alternate directions anyway on the same layer, so the "messy" surface can still appear...
