### ISSUE TITLE
Velleman Vertex K8600 printer definition wrong

### ISSUE THREAD

**Issue by Leleu256** [Ultimaker/Cura#6673]
**Application version**
4.3.0

**Platform**
Windows 10 1909 64bit French

**Printer**
Velleman Vertex K8600 Nano

**Reproduction steps**
try printing using the current printer definition

**Actual results**
The head move but does not get warm

**Expected results**
The print head should warm up and print the model

**Additional information**

**Comment by Leleu256** [comment]
Checking the vertex_nano_k8600.def.json figure where is the issue. The file does not include "\n" special character.
Also, the nozzle is defined to 0.35mm but the stock model use a 0,4mm nozzle.

I've tried to correct the file but for a reason I ignore, even if I modify the file, cura ignore my modifications.

What I propose is as below : 


    "overrides": {
        "machine_start_gcode": {
            "default_value": "M104 T0 S{material_print_temperature} \nG28 ; Home extruder\nG90 ; Absolute positioning\nM82 ; Extruder in absolute mode\nG92 E0 ; Reset extruder position\nM109 T0 S{material_print_temperature} \nG1 E20 F100\nG92 E0 ; Reset extruder position\n"
        },
        "machine_end_gcode": {
            "default_value": "; Default end code\nG1 X0 Y0 Z130 ; Get extruder out of way. Uncomment to use!\nM107 ; Turn off fan\n; Disable all extruder\nG91 ; Relative positioning\nT0\nG1 E-1 ; Reduce filament pressure\nM104 T0 S0\nG90 ; Absolute positioning\nG92 E0 ; Reset extruder position\nM140 S0 ; Disable heated bed\nM84 ; Turn steppers off\n"
        },
        "infill_line_width": {
            "value": 0.4
        },
        "wall_thickness": {
            "value": 0.8
        },
}

**Comment by Leleu256** [comment]
The default start gcode by the manufacturer is  : 

{IF_EXT0}M104 T0 S{TEMP0}
G28 ; Home extruder
G90 ; Absolute positioning
M82 ; Extruder in absolute mode
G1 Z1 F{Z_TRAVEL_SPEED}
G92 E0 ; Reset extruder position
{IF_EXT0}M109 T0 S{TEMP0}
G1 E20 F100
G92 E0 ; Reset extruder position
G1 Z5 F{Z_TRAVEL_SPEED}

the default stop gcode is : 

; Default end code
;G1 X0 Y0 Z130 ; Get extruder out of way. Uncomment to use!
M107 ; Turn off fan
; Disable all extruder
G91 ; Relative positioning
{IF_EXT0}T0
{IF_EXT0}G1 E-1 ; Reduce filament pressure
M104 T0 S0
G90 ; Absolute positioning
G92 E0 ; Reset extruder position
M140 S0 ; Disable heated bed
M84 ; Turn steppers off

**Comment by nallath** [comment]
The if statements (eg; {IF_EXT0}) won't work within Cura, so unless the firmware can parse those they won't work.

You can also just try to change the start codes in the machine settings dialog. Could you try if that works (that way we at least know if the start & end g-code you propose will work.

**Comment by fieldOfView** [comment]
The other replacement patterns (text between {}) is also incorrect. You have to use eg `{material_print_temperature_layer_0}` instead of `{TEMP0}` for Cura.

For the (unofficial, but complete) list of patterns you can use, see http://files.fieldofview.com/cura/Replacement_Patterns.html

**Comment by Leleu256** [comment]
> You can also just try to change the start codes in the machine settings dialog. Could you try if that works (that way we at least know if the start & end g-code you propose will work.

Unfortunately, I could not test the GCODE as the interface do not let me see/modify the START or END GCODE. There must be a bug in the display or maybe because the provided gcode is not valid.
Picture attached.
![cura bug](https://user-images.githubusercontent.com/9988196/69187803-8f095f00-0b1b-11ea-9704-2ae20f6a9d44.png)

I will try with an upgraded Cura 4.4

**Comment by Leleu256** [comment]
> I will try with an upgraded Cura 4.4
I'm dumb... The window needed to be expanded to show the content... :-( 

I will try with theses custo GCODES and let you know...

START : 
```
M104 T0 S{material_print_temperature_layer_0}
G28 ; Home extruder
G90 ; Absolute positioning
M82 ; Extruder in absolute mode
G92 E0 ; Reset extruder position
M109 T0 S{material_print_temperature_layer_0}
G1 E20 F100
G92 E0 ; Reset extruder position
```
STOP
```
; Default end code
G1 X0 Y0 Z130 ; Get extruder out of way. Uncomment to use!
M107 ; Turn off fan
; Disable all extruder
G91 ; Relative positioning
T0
G1 E-1 ; Reduce filament pressure
M104 T0 S0
G90 ; Absolute positioning
G92 E0 ; Reset extruder position
M140 S0 ; Disable heated bed
M84 ; Turn steppers off
```

**Comment by nallath** [comment]
You can drag the window so it re-scales (and you can see the start & end g-code)
