### ISSUE TITLE
[4.4.0 BETA] Cannot deactivate auto start print job and webcam image

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#6680]
**4.4.0 BETA/OctoPrint Connection 3.5.10**
**Windows 10**
**Tevo Tornado/Marlin 2.0**
(only one printer, but 8 were created depending on the nozzle)

**Reproduction steps**
Install 4.4.0 BETA 
Connect a printer (OctoPrint dialog)
Uncheck auto start print job and webcam (I always deactivate these options, and they got activated after installation of 4.4.0 BETA)

**Actual results**
These options are forced "on" by 4.4.0 beta. They can be changed but they are not saved. Closing and reopening Preferences, auto start + webcam are always back.

**Expected results**
The user's choice should be used and saved

[EDIT] modifying these options for one printer changes them for all printers at once. But nothing is saved when closing the Preferences dialog.

**Comment by fieldOfView** [comment]
Could you open an issue at the OctoPrintPlugin issue queue instead?
https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues

**Comment by yet-another-average-joe** [comment]
Done !

I was thinking of a problem with Cura 4.4.0 beta, as I had another issue after installing it.
