### ISSUE TITLE
Drops UM Original nozzle size in to default

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#6685]
Cura 4.2-4.4 do not save nozzle size changes for UMO in machine settings.
I change default 0,4 to my 0,5, and after closing a window nozzle size returns to 0,4.
![image](https://user-images.githubusercontent.com/58006200/69268225-c5a8ad80-0bdf-11ea-8cdc-233fa9372cfd.png)

**Comment by rburema** [comment]
Can't seem to reproduce this in 4.4 (even if I try it with a `,` instead of a '.') It stays the same even after restart.

Perhaps it's (still) related to locale settings though, could you  try it with a '.'?

Alternatively, is this a machine that has been there before the upgrade? Does this still happen when adding a 'new' UMO?

**Comment by alexshorokhov** [comment]
It still happens when adding a new UMO. No matter if it is dott or comma, no result.

**Comment by rburema** [comment]
What's your locale? Maybe I can reproduce it that way.

**Comment by alexshorokhov** [comment]
What do you mean "locale"? English is not my common language, so I can misunderstand you.

**Comment by rburema** [comment]
A 'locale' in the sense that I meant is basically the (collection of) internationalisation settings that (a program or) the OS is set to. For instance, if I set my locale to Dutch (nl_NL), then, not only will the language change, but the default decimal separator will be a `,` while the thousands separator will be a `.` (the opposite of what it is in English (en_EN)).

**Comment by alexshorokhov** [comment]
Locale is Russia. Cura language is english.
I've just done it! I've typed ",5" when the keyboard language was English instead of Russian and pressed enter. Then Cura automatically changed " , " to ". " and saved this setting. Now it is 0.5.
Many thanks!

**Comment by alexshorokhov** [comment]
I think, I will close tthis issue now)

**Comment by rburema** [comment]
You're welcome!

I'm not sure if it _should_ be closed though... it should still work after all, even if your language isn't English.

**Comment by Ghostkeeper** [comment]
No, we'd like to keep this open because Cura should also work properly in the Russian locale.

**Comment by alexshorokhov** [comment]
Ok.

**Comment by Ellecross** [comment]
Ok - this is weird. I have tried it myself, change my locale to Russia, had a Russian language keyboard - but had to switch to english when change the Nozzle size setting. 

I also switched to Russian keyboard and Cura converts 0,5 to 0.5 automatically. 

So, I cannot reproduce it. :/ The values always get saved.

**Comment by Ellecross** [comment]
> No, we'd like to keep this open because Cura should also work properly in the Russian locale.

I don't know, I think we should close it and keep an eye out for this in the future.

**Comment by Ghostkeeper** [comment]
Hmm, maybe it's different per platform?

**Comment by DenKoren** [comment]
I just faced the same problem on Mac OS X with Russian system locale.

When I tried to change nozzle size Cura siletly ignored my changes until I found this thread and tried to use comma instead of dot as a separator.

I think, it would be great to detect system locale and show the values using the default separator for current system locale, if it affects the UI. This will give users a clue about the symbol they should use.

**Comment by Ghostkeeper** [comment]
Our idea so far is that the user can type any radix and all of them should work. However they will all be converted to period as to keep things simple and consistent.

**Comment by DenKoren** [comment]
Shure, it would be much more convenient. 

My idea was about the quickfix to be considered before the normal patch. It may be easier and faster than locale-independent solution.

**Comment by Nemori27** [comment]
Have the same issue, cand change nozzle diameter, whatever i do its still the same. After reading this page i tried to type 0.2 in russian keyboard and it seems to work! Howewer its strange, as my default keyboard language is english and i tiped values in english when it refused to work

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
