### ISSUE TITLE
two or more extruders are not created for delta

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#6688]
Hello. I encountered the error of slicing parts in Cura 4.4. (the program could not finish the cut after the start).
I decided that it was a profile issue from previous versions.

The next step I tried to create a new profile for delta
![create profile](https://user-images.githubusercontent.com/44455128/69306865-a740c180-0c74-11ea-9529-cb065c35b3b8.PNG)

However, when I went into the printer settings, I could not put two extruders.
![not extruders](https://user-images.githubusercontent.com/44455128/69306871-ab6cdf00-0c74-11ea-9964-9127a41b906f.PNG)

Windows 10
Cura 4.4
Delta printer
nozzle 0.4
dual extruder (extr 1 + extr.support)

**Comment by Goodfeat** [comment]
I solved the problem. It turns out that the profile of the delta was not originally intended to be printed by two extruders.

The solution was simple. I added a new line in to the file "deltabot.def.json"
"1": "deltabot_extruder_1"

![add string](https://user-images.githubusercontent.com/44455128/69311631-84181100-0c78-11ea-8840-6b53e83e6531.PNG)

I also had to create an additional file deltabot_extruder_1.def.json

it was not implemented initially due to bugs?

**Comment by rburema** [comment]
I'll ask around if there was a reason for that.

**Comment by rburema** [comment]
Originally, deltabot wasn't in custom, since 'Custom FFF Printer' can also handle this use case. The recommended way to do this (for now) is to use 'Custom FFF Printer', where you _can_ select multiple extruders.

Pull requests are welcome, though!

**Comment by Goodfeat** [comment]
I tried the method described above. It seems to work.

**Comment by Ghostkeeper** [comment]
> I'll ask around if there was a reason for that.

History. Deltabot was made as an easier way to create a custom Delta printer. It's in fact older than Custom FFF Printer and was implemented before we had multi-extrusion support.

**Comment by fieldOfView** [comment]
I don't know why Deltabot ended up in the "Custom" category. Having it there only confuses matters. The definition is a legacy from way back:
https://github.com/daid/LegacyCura/blob/SteamEngine/resources/machine_profiles/DeltaBot.ini

**Comment by Goodfeat** [comment]
Indeed, this is confusing.
This option offers no benefits other than the selected circle-shaped bed.
... and only one extruder

**Comment by Ghostkeeper** [comment]
Yeah we could try removing it but that involves deleting a bunch of profiles from the users' configuration as well.

**Comment by fieldOfView** [comment]
Pull request is here: #7331
