### ISSUE TITLE
[4.4] Comments removed from Start/End G-codes after update

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#6689]
**Application version**
4.4 after updating from 4.3

**Platform**
Win10

**Printer**
Custom built

**Reproduction steps**
1. Put some G-code descriptions as new line comments in Start/End G-codes in 4.3
2. Update from 4.3 to 4.4 (uninstalled 4.3 beforehand, kept configuration files)
3. Open machine settings window again

**Actual results**
MOST comment only lines (lines starting with ";") were removed. Comments following actual G-codes ("G28 ;home" for example) remain unchanged.
Commented first line didn't get removed.

No more change between restarts, only once after update.

**Expected results**
Whole G-code scripts remain unchanged.

**Additional information**
https://github.com/Ultimaker/Cura/issues/1237 fixed this issue before, only difference is this doesn't happen between restarts.

My End G-code is as follows:
```
;<END>
G0 Z305 F1500 ; lower bed
M140 S0
M104 S0 ; M104 T0 S0
M124 S0 ; M104 T1 S0
M134 S0 ; M104 T2 S0
M107
;<DOCK>
T0
G28 X0 
G28 Y0
M84
;</END>
```

Only `;<DOCK>` and `;</END>` got removed. `;<END>` at the top remained.

`;<DOCK>` and other brackets in comments are used by my external post processing script as fix for #5861 and other patches for Smoothieware.

**Comment by rburema** [comment]
I can reproduce this. It seems the problem is the upgrade itself as opposed to the script, because if I go into the machine settings in 4.4, the code is reduced there as well. However, if I then put it back and restart (in 4.4), it _does_ remember.

**Comment by fieldOfView** [comment]
If the UpgradeManager parses the instance container ini file and writes it back to disk, it should disable comments like here:
https://github.com/Ultimaker/Uranium/pull/301/files

**Comment by rburema** [comment]
Traceback: We've made (internal) ticket CURA-6994 for this.

P.S.: @DonExo this is how we can track it back to 'our' system, so we don't spend ages looking if a ticket has already been made (like you just did) from this internally :-)

**Comment by Block137** [comment]
@rburema I just discovered this problem again in 4.5 after opening .3mf file.

The .3mf was generated in 4.5 and opened as project in 4.5.

Should I make a new bug report?

**Comment by rburema** [comment]
@Block137 Yes please. As CURA-6994 has been in the done column for a while, so this might be a new (but probably related) issue.
