### ISSUE TITLE
Support stream does not work ( cura 4.3-4.4)

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#6691]
Hello. I noticed that the support flow  setting does not work.
![support 100](https://user-images.githubusercontent.com/44455128/69345053-2e655800-0cbc-11ea-8177-180609056bb2.PNG)
![support 5](https://user-images.githubusercontent.com/44455128/69345074-3b824700-0cbc-11ea-8aec-ebaa7c968d76.PNG)

after changing the setting, nothing changes, the plastic consumption remains the same

Windows 10
Cura 4.3-4.4
Delta printer
nozzle 0.4
dual extruder (extr 1 + extr.support)

**Comment by rburema** [comment]
You're right. I can't find `support_material_flow` only once in the settings (nothing else refers to it) and not in the engine at all!

**Comment by rburema** [comment]
I've pushed a fix for this, should be in next release unless reverted.

(See https://github.com/Ultimaker/CuraEngine/commit/e40ac1c6c322a464805d49c3ddd450bcec54e740 )
