### ISSUE TITLE
4.4 - View -Zoom,move is fubar

### ISSUE THREAD

**Issue by Bajotaz** [Ultimaker/Cura#6692]
Bring back Cura 4.3 mouse movement, the Cura 4.4 mouse movements is FUBAR!
Can not turn an object without loosing object from center of screen...

**Comment by fieldOfView** [comment]
AFAIK, Nothing changed wrt zooming and moving between 4.3 and 4.4. 
Have you checked the viewport behavior options in the preferences?

**Comment by nallath** [comment]
We also need a bit more information about what it is that you're doing (and what it is that is going wrong). Could you make a (short) video that shows the problem?

**Comment by Bajotaz** [comment]
Hi.

I was unable to cirkle around a object.
But it works now.
Had to enable all options in viewport behavior, restart cura, disable all,
restart cura then enable my choices and it worked.

Maybe something with porting saved options to next version?

Den tors 21 nov. 2019 16:42Jaime van Kessel <notifications@github.com>
skrev:

**Comment by Ghostkeeper** [comment]
Maybe your camera dolly position ended up weird and a restart fixed the problem.
