### ISSUE TITLE
[OS X] Store user settings in standard location

### ISSUE THREAD

**Issue by nilrog** [Ultimaker/Cura#670]
In v15.04.3 Cura stored settings etc. in the proper location on OS X (which is **~/Library/Application Support/appname/**).

But the new 2.1 beta doesn't store it's settings there. Instead it uses a hidden directory in the root of the home directory (**~/.cura/**), which is how it usually is on a Linux system.

To further confuse users, this directory does not contain a **"plugins"** subfolder where you can put Cura plugins. But if you manually create that subfolder and put plugins there they are found by Cura. So an empty folder should be put there by default.

**Comment by nallath** [comment]
I'm not so sure about your first point (i'm not familliar enough with mac to say anything about "proper" locations), but the second thing is definately something we should look into.

**Comment by nilrog** [comment]
https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

**Comment by nilrog** [comment]
And the fact the the current "stable" version uses that folder.

**Comment by fieldOfView** [comment]
As an occasional OSX user I agree with @nilrog

**Comment by fieldOfView** [comment]
For our reference: CURA-1390

**Comment by awhiemstra** [comment]
Yes to saving in the standard location (though I find the standard location incredibly weird on OSX), no to always creating a plugins folder. The directories are created as needed by the application. Adding logic to create directories when not needed gets ugly way too quickly. The plugin dir should simply be documented a bit better.

**Comment by nilrog** [comment]
Well, it is not any weirder than the location in Windows... ;)

And having the folder there would make it a lot easier for user to know where to put them...unless you plan on a fancy UI to handle installing plugins. You know, users tends to skip reading documentation.

**Comment by Ghostkeeper** [comment]
Fixed by awhiemstra in https://github.com/Ultimaker/Uranium/commit/9cc143057963937fa17b4c046d33e8b214c11abe.
