### ISSUE TITLE
Feature Infill Line Multiplier conflict with Randomize Infill Start and leads to crush.

### ISSUE THREAD

**Issue by digiTALker** [Ultimaker/Cura#6702]
**Application version**
Cura 4.4.0

**Platform**
Win 7. Intel, Nvidia

**Printer**
Custom printer Priusa kinematic. Repitier.

**Reproduction steps**
1. Check box "Randomize Infill Start"
2. Set Infill Line Multiplier to "2"

**Actual results**
Leads to crush some function of Cura. But after closing error message Cura still works. Looks like crash in code generating module.

**Expected results**
Expected correct end of slising. 

**Additional information**
(Extra information relevant to the issue, like screenshots. Don't forget to attach the log files with this issue report.)
[https://i.imgur.com/9BtTN87.png](url)

**Comment by digiTALker** [comment]
https://i.imgur.com/9BtTN87.png

**Comment by smartavionics** [comment]
Which infill pattern are you using? I just tried those settings and it worked OK. Please save the project file (File -> Save) and zip or rename the .3mf file and attach to this issue, thanks.

**Comment by Ghostkeeper** [comment]
I can reproduce this problem. Here is a project file inside a zip file:
[UM3_tetrahedron.zip](https://github.com/Ultimaker/Cura/files/3922421/UM3_tetrahedron.zip)

**Comment by DkOuvE** [comment]
Can also confirm this bug. When I turn off randomise, it slices fine.

**Comment by Ghostkeeper** [comment]
We discussed this a long time ago, but I don't know what happened with the ticket.

I've made a fix that prevents it from crashing when using a polygonal-type infill like Concentric or an even number of multiplied infill lines, together with Randomize Infill Lines.

**Comment by jellespijker** [comment]
Looks like https://github.com/Ultimaker/CuraEngine/pull/1206 fixes it
