### ISSUE TITLE
CURA 4.4.0 Program freezes  at each action

### ISSUE THREAD

**Issue by OUPS65** [Ultimaker/Cura#6707]
**Application version**
4.4.0

**Platform**
Spectre, Windows 10 family 64 bits, Intel I7 6500 CPU, 8Go

**Printer**
PRUSA MK2

**Reproduction steps**
1. Something you did.
2. Something you did next.

**Actual results**
[BUG.zip](https://github.com/Ultimaker/Cura/files/3883656/BUG.zip)

He,
I just installed the new release. 
Program freezes (« not responding »)  during  5 à to 10 seconds at each action / profile param value update, insert or delete or move any item on the build plate, record profile, etc. 
Loading a project is so so slow.
De-installed with Revo Uninstaller and re-installed : no change.
I do not have any of these problems with my current 4.3.0  version fortunately still active.
Sorry
Philippe

**Comment by smartavionics** [comment]
Hello @OUPS65 , I do not know for sure what the problem is but I am guessing that it could be something that I have already fixed in my Cura builds. My builds can be found at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0 and they may be installed alongside the UM releases without conflict. Please read the README.md file there if you wish to learn more.

**Comment by Ellecross** [comment]
crosspost from the [forum](https://community.ultimaker.com/topic/30191-ultimaker-cura-44-released-with-new-intent-profiles/?do=findComment&comment=251308). :D FYI

**Comment by OUPS65** [comment]
Correct. I’m not sure where to call for help when a new program version is involved.
solution from the forum :
Tks, @RoboDLC
What I made, based on your suggestion:
norton -> pare feu -> controle programme -> ajouter ( add a new programme autorisation) -> selected CURA 4.4.0 and gave full autorisation.
Now, the problem is solved.

**Comment by rburema** [comment]
@OUPS65 Usually (read: we prefer) here, but in this case there's more information/an already ongoing discussion on the forum.

@Ellecross Don't forget to attach the ticket number to here as well if we make one! :-)

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
