### ISSUE TITLE
set parameter problem

### ISSUE THREAD

**Issue by lyfbuaa** [Ultimaker/Cura#6710]
Application version
Cura-4.4.0.AppImage

Platform
fedora 31 x86_64

Printer
diy printer like ultimaker with marlin 1.0.2-2

Reproduction steps
1. shell-》bottom thickness : 24 mm
maybe tell me how to set <240 layer  solid

Actual results
<240 layer  hollow

Expected results
<240 layer  solid

![Screen-2019-11-25_16-34-53](https://user-images.githubusercontent.com/16573747/69526574-6e228d00-0fa5-11ea-87ed-cdcba23a5eb4.jpg)

**Comment by nallath** [comment]
I've tried to reproduce your issue, but when I set the bottom thickness to 24 I get a lot of very thick layers. 
Could you share your project file? It could be that you have other settings changed / set that are interfering with this.

**Comment by lyfbuaa** [comment]
en,sorry.  please close it,I find it's the prolem of my cura .
