### ISSUE TITLE
Add favorite options please (star mark)

### ISSUE THREAD

**Issue by ZhenyaKa** [Ultimaker/Cura#6711]
Hiding some options in list is good, but in 99% cases we need to change 2-5 options.
Now I need to scroll list to find it or use very slow filter.

If I'll have any "star-button" near each line of options, what move that option to top of the list I will be happy!

**Comment by nallath** [comment]
You mean like the custom visibility plugin?

**Comment by ZhenyaKa** [comment]
> You mean like the custom visibility plugin?

I can't find that plugin.

I need 5-10 marked options at top of global list, which I can mark any method from main list.

For fast changing them and not scrolling each time

**Comment by rburema** [comment]
I think @nallath meant the 'Setting Visibility Set Creator', available in the Marketplace (the 1st button in the top right, just above the settings fold-out).

**Comment by Ghostkeeper** [comment]
I think the proposed solution (or workaround if you see it that way) works fine for this use case.
