### ISSUE TITLE
Add flag that group title can be filtered

### ISSUE THREAD

**Issue by ZhenyaKa** [Ultimaker/Cura#6712]
If I need to go to Support group for example, I need to scroll to that group.

I can write "support" in filter field, but that method hide some lines, that not include that word.

It will be good if will be posibility to filter group header without hiding lines that this group include.

Hot keys like ctrl+1, ctr+2... etc for fast moving to each group will be good solution too (with key combination hint).

**Comment by Ellecross** [comment]
Hey @ZhenyaKa thanks for the comment, I'll ask the team ;)

**Comment by Ghostkeeper** [comment]
@Ellecross What was the result of asking the team?

**Comment by ninovanhooff** [comment]
I see this request was referenced in an internal ticket CURA-6959: "Collapse all" for all settings categories.

So we looked at @ZhenyaKa problem which is: "Getting to settings category X takes too long" and we are addressing this by having a way to collapse all categories.

**Comment by evtrados** [comment]
Closing this issue, since the "Collapse All Categories" option is addressing the original problem.
This option will be available in the next release.
