### ISSUE TITLE
Clearing option filter frozes cura

### ISSUE THREAD

**Issue by ZhenyaKa** [Ultimaker/Cura#6713]
I write in filter field "support" for example.

When I clear that word I got freeze while list building - about 5-7 seconds.

**Comment by Ellecross** [comment]
Which version are you using? @ZhenyaKa

**Comment by ZhenyaKa** [comment]
> Which version are you using? @ZhenyaKa

this freeze appear in all versions including 4.4 beta

**Comment by fieldOfView** [comment]
How many settings do you have visible?
Does the same freeze also happen if you have the "Basic" set visible (from the hamburger menu next to the filter box)?

**Comment by ZhenyaKa** [comment]
I have almost all settings visible

**Comment by rburema** [comment]
> ... including 4.4 beta

Also in 4.4.0 (final) itself?

**Comment by fieldOfView** [comment]
> Does the same freeze also happen if you have the "Basic" set visible

**Comment by Ghostkeeper** [comment]
Seems to me that the problem is to create 495 text fields, labels, mouse areas, reset buttons, function restore buttons, setting value labels and unit labels.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
