### ISSUE TITLE
post proces script linked to quality definition

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#6715]
Is it possible to incorporate a post process script to quality definition files?
example:
If we choose a specific quality setting, it will automatically add the "Time Lapse" script with values.

**Comment by nallath** [comment]
Currently there is no way to do this. The profile system knows nothing about the post processing.

I also don't see a quick way to incorporate that feature into the profile system.

Could you perhaps explain the complete scenario why you would want this? I might be able to provide a different solution.

**Comment by maukcc** [comment]
The way we came to this is that we wanted to do a Nozzle wipe (G12) every xx seconds or layers

**Comment by nallath** [comment]
I'd say that's something the engine should do (and not a post processing script).

**Comment by rburema** [comment]
There is something similar (but implemented without the `G12`, I think) in the experimental settings: Turn on 'Wipe Nozzle Between Layers' and a number of related options should appear.

**Comment by maukcc** [comment]
@rburema We did not see that one, thanks. unfortunately that is not usable for us. We will make a new issue about this.
