### ISSUE TITLE
[4.4.0] When changing settings in an imported Cura profile, the slice button does not re-appear

### ISSUE THREAD

**Issue by Richhe01** [Ultimaker/Cura#6717]
**Platform**
Windows 10 Home 64 bit

**Printer**
Printrbot Play no heated bed

**Reproduction steps**
Selected imported cura settings (settings were imported from 4.3)
Changed a value in the imported settings. (raft extra margin for example)
Bottom right still has "save to file" button

**Actual results**
Bottom right still has "save to file" button, un-updated gcode preview still displayed. 

**Expected results**
Bottom right should have "slice" button

[cura.log](https://github.com/Ultimaker/Cura/files/3893204/cura.log)

**Comment by Ellecross** [comment]
Hey @Richhe01 I cannot reproduce this. 

This is my reproduction scenario: Can you let me know if it's similar to what you did? 
1. In 4.3, Add printrbot
2. Change settings(any setting) and create custom profile
3. Export that custom profile 
4. Open 4.4 (upgrade) 
5. Re-import that profile I exported in step#3 and activate it. (Cura sliced)
6. Change settings - slice is shown 

Unless you and I are doing something different. ;)
