### ISSUE TITLE
Ultimaker Original with Heated Bed does not have Bed Temperature Control

### ISSUE THREAD

**Issue by michael-ring** [Ultimaker/Cura#672]
When configuring a new Ultimaker in Cura 2.1.99 I can define that I have a heated bed but the control that allows me setting the bed temperature does not show up.

I have configured in Preferences->Settings that I want to see Bed Temperature, does not help.

As a workarround I have added the Heated Bed definition to the machine profile, after this change I see the bed temperature control, but this is only a hack...

**Comment by nallath** [comment]
This should be fixed. I just tested this with source and it correctly displays bed temperature when I select an UMO with heated bed upgrade.

**Comment by michael-ring** [comment]
TnX, will retry in next release
