### ISSUE TITLE
Can't see the path line in the preview model

### ISSUE THREAD

**Issue by juchenboo** [Ultimaker/Cura#6725]
Why the path in the Pre-View model looks like that:
[https://github.com/juchenboo/myfile/blob/master/prob.PNG](url)

I am not sure that it is a problem ,but I can't check the path line like that. I need help ^_^
Is tha a bug? or I can set in some where?

**Comment by fieldOfView** [comment]
It is not a bug; it looks like your layer view is in "compatibility mode", probably because your GPU does not support the features needed for the full layer view.
