### ISSUE TITLE
[4.4.0] Profile type in profile list have incorrect color

### ISSUE THREAD

**Issue by NeoProg2013** [Ultimaker/Cura#6726]
Environment:
- Windows 10 (x64)
- Tevo Tarantula
- Cura Ultimaker 4.4.0 with dark theme

Profile type in profile list have incorrect color. You can see it on screenshots. 
![2](https://user-images.githubusercontent.com/58175138/69786593-cb982300-11cb-11ea-8b27-68fb1bc3c12b.png)

I think "Custom profiles" section name should be have color equal "Default" section name (gray). May be also add some separator after section name?

**Comment by Ellecross** [comment]
@NeoProgAIM hey, thanks for reporting this. @Yian-Lai and I will take a look. There are actually a bunch more that are incorrect in the dark theme that we have to correct. :)

**Comment by Ellecross** [comment]
UM Cura devs, we're tracking all dark theme issues in CURA-6941

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
