### ISSUE TITLE
Octoprint busy

### ISSUE THREAD

**Issue by tablatronix** [Ultimaker/Cura#6733]
I have not been able to print to octoprint lately, no idea what has changed, any tips on debugging this? Latest version stable

![Screen Shot 2019-11-29 at 12 09 23 PM](https://user-images.githubusercontent.com/807787/69885323-30be4800-12a2-11ea-8178-cb71f1bc0e8a.png)

**Comment by fieldOfView** [comment]
Can you please open an issue at https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues and close this one?
