### ISSUE TITLE
[4.4.0] Won't start on Mac OS Catalina due to "cannot check it for malicious software"

### ISSUE THREAD

**Issue by mjparme** [Ultimaker/Cura#6736]
**Application version**

4.4.0

**Platform**

Mac OS 10.15.1

**Printer**

Maker Select

**Reproduction steps**

Double-click on the Cura Application

**Actual results**
Get the following error dialog:

<img width="422" alt="Screen Shot 2019-11-30 at 3 24 36 PM" src="https://user-images.githubusercontent.com/1580996/69906229-f1692780-1385-11ea-945f-3e3ac86a2cdd.png">

**Expected results**

Cura should start up.

**Additional information**

**Comment by smartavionics** [comment]
Looks like what is discussed in https://www.winytips.com/installer-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/

**Comment by mjparme** [comment]
> Looks like what is discussed in https://www.winytips.com/installer-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/

Yeah, I discovered I could convince it to open on the privacy & security pref pane.

**Comment by SamCB** [comment]
Can also open it by right clicking->open->open. That said, Apple is definitely making life difficult for Open Source developers right now.

I'm not sure that this issues should be closed. For any mac user, this is now the first thing they see when they try opening the app and for a general consumer who doesn't know to look around on github for workarounds, they're going to have a pretty rough time. What's the process for an open source app like Cura to receive notarization?

**Comment by wifiprintguy** [comment]
If you can leverage the info documented here (https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow) then you can automate the notarization process. That is what we do in the istopwg/ippeveselfcert project.
