### ISSUE TITLE
no cura connection to octoprint

### ISSUE THREAD

**Issue by Rene046** [Ultimaker/Cura#6741]
hi there is it just me.... can't connect to octoprint anymore from Cura only saving into file... ?

regards Rene

**Comment by Ghostkeeper** [comment]
-> https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues

**Comment by Ghostkeeper** [comment]
-> https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
