### ISSUE TITLE
GUI widegets are missing or invisible

### ISSUE THREAD

**Issue by michaesc** [Ultimaker/Cura#6744]
**Application version**
Cura: 3.3.1
Package: Newest most up to date in the Ubuntu Eoan repository (3.3.1-2)

**Platform**
Ubuntu Desktop Eoan 19.10
$ uname -a
Linux host 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Printer**
The problem appears when no printer is selected or any of all available printers is selected.

**Reproduction steps**
1. Upgrade the Ubuntu OS
2. Execute cura(1) by menu or command line

**Actual results**
The cura(1) application starts and displays a defective window as shown in additional information.

**Expected results**
The cura(1) application should start and display all GUI widgets correctly.

**Additional information**
![curaprob](https://user-images.githubusercontent.com/4779602/69955303-ab36d400-14fd-11ea-89e2-f084fc4967ef.png)

**Comment by nallath** [comment]
We didn't create the PPA or maintain it. So if you want to use the PPA, please contact the listed maintainer. Alternatively, you can use the appimage that we provide.
