### ISSUE TITLE
[4.4.0] Please add Creality CR-10 V2 profile

### ISSUE THREAD

**Issue by eXistenZ** [Ultimaker/Cura#6745]
Hey, please add a profile for Creality CR-10 V2 printer! Or I can just use the old Creality CR-10 profile and it will work fine?

Thanks!

**Comment by Ellecross** [comment]
That would be great! But we as Ultimaker do not create them. If someone creates a pull request, then we'll add it. ;)

**Comment by Ghostkeeper** [comment]
Can't fix this since we don't have your printer model in the office. It's impossible to buy all printer models out there. If someone wants to make profiles for your printer, we'll gladly add them to Cura. But we'll close this bug report until then because there is nothing we can really do about it.

**Comment by kubilesti** [comment]
what if someone sent you the printer and you returned it afterwards?

**Comment by Ghostkeeper** [comment]
Then it's a matter of us finding the heart and time to create profiles for you in their free time.
