### ISSUE TITLE
Cura is resetting connected Arduinos

### ISSUE THREAD

**Issue by Paul-F-Hanson** [Ultimaker/Cura#6760]
**Application version**
(The version of the application this issue occurs with.)
4.4 and earlier versions

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system. In the case of visual glitches/issues, also include information about your graphics drivers and GPU.)
PC
**Printer**
(Which printer was selected in Cura? If possible, please attach project file as .curaproject.3mf.zip.)
IrrelevanT
**Reproduction steps**
1. Something you did.
2. Something you did next.
IrrelevanT
**Actual results**
(What happens after the above steps have been followed.)
IrrelevanT
**Expected results**
(What should happen after the above steps have been followed.)
IrrelevanT
**Additional information**
(Extra information relevant to the issue, like screenshots. Don't forget to attach the log files with this issue report.)

Cura seems to assume ownership ofall connected Arduino devices as if they are printers.
I have a homemade 8 way relay controller which is Arduino controlled. Every time I have Cura running it seems to reset my device. Why is cura probing ports to which it is notdirectly associated?

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5207.
