### ISSUE TITLE
Plugin - PostProcessing timelapse- add retract and extrude option pre/post head park

### ISSUE THREAD

**Issue by S2Gilly** [Ultimaker/Cura#6761]
**Application version**
4.4

**Printer**
S5

**Reproduction steps**
Using post processing and timelapse, there is a lot of stringing while moving from the print to the park location.  We couldn't find any where to enter in a retract and extrude again to help prevent this.  could just be missing it though.

**Comment by Ellecross** [comment]
Hello @S2Gilly, is this similar to https://github.com/Ultimaker/Cura/issues/6730? ;)

**Comment by S2Gilly** [comment]
I'm not 100% sure if it is similar, it very well could be related.  I'll double check to see if turning combing off works.  (I did do a search prior to posting and having my fat thumbs hit post before anything was actually in the post haha. But I guess I didn't search enough!! sorry! )

Also, I actually just went through the settings in cura again... and realized I forgot about the "retract at layer change" option.  I will be trying this this morning to see if that helps!

So I have several things to try.   

Thanks!!!

**Comment by Ghostkeeper** [comment]
> (I did do a search prior to posting and having my fat thumbs hit post before anything was actually in the post haha. But I guess I didn't search enough!! sorry! )

Maybe that search didn't work because the other issue is written in German...

I'm closing this because to me this issue looks exactly alike #6730.
