### ISSUE TITLE
when placing 2 or mor eobjects the remove all holes is been executed automaticly

### ISSUE THREAD

**Issue by alexvancoyghem** [Ultimaker/Cura#6768]
**Application version**
(The version of the application this issue occurs with.)
4.4
**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system.
In the case of visual glitches/issues, also include information about your graphics drivers and GPU.)
windows 10
**Printer**
(Which printer was selected in Cura?
own (ira 3D)
**Reproduction steps**
1. Something you did.
I added the model and sliced it, remove all holes not active, so sliced ok with the needed holes, then I multiplied the part and sliced again, all holes were removed allthough  not being activated
2. Something you did next.
Remove the parts and went back to one part, sliced again, this was wiht th eholes, so ok.

**Screenshot(s)**
Adding screenshot(s) is a very good idea to identify what exactly the problem is. We get lots of bug reports and a screenshot is also a great help to tell them apart without downloading and opening a project file. 
Feel free to add text either inside or below the screenshots. Before (earlier, working version of Cura) / After (Problematic version of Cura) screenshots might work well, too. 
![image](https://user-images.githubusercontent.com/58599607/70331651-266ef180-1840-11ea-83ca-0ffe9d061a16.png) two parts on th eplate same profile
![image](https://user-images.githubusercontent.com/58599607/70331690-40a8cf80-1840-11ea-9697-a1df01a00fae.png)
one part on the plate

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)
hole sin the part
[lock outside.3mf.zip](https://github.com/Ultimaker/Cura/files/3932708/lock.outside.3mf.zip)

**Project file**
Provide a project which clearly shows the bug.
Rather than providing a model file, provide a project (.3mf or .curaproject) file. This will include all the settings you used, which is crucial to reproducing your problem.
To upload a project, try changing the extension to e.g. bug_example.3mf.zip so that GitHub accepts uploading the file.
If the file is too big, we recommend http://wetransfer.com, but other file hosts like Google Drive or Dropbox work well too. Please make sure the file is publicly available ie. "shared with everyone"

**Log file**
It is important to provide a log file. It might provide us info about why a certain material was selected, or is not compatible, for example.
Information about how to find the log file can be found at https://github.com/Ultimaker/Cura#logging-issues 

**Additional information**
(Extra information relevant to the issue)

**Comment by Ghostkeeper** [comment]
This is because the mesh is oriented such that the entire universe is on the inside of the mesh except the actual volume. Cura tries to repair it for you but didn't succeed completely.

I suggest that you try and install the "Mesh Tools" plug-in from fieldOfView. Once that plug-in is installed you can try going to Extensions -> Fix model normals. That fixes it for this case. Here is a project file where the normals of the models are fixed: 
[CFFFP_lock_outside_fixed.3mf.zip](https://github.com/Ultimaker/Cura/files/3939680/CFFFP_lock_outside_fixed.3mf.zip)
