### ISSUE TITLE
Support Z-distance ignored if smaller than layer height

### ISSUE THREAD

**Issue by avogra** [Ultimaker/Cura#678]
Cura version: 1.99.00 on Windows 7 x64
When I set a support z-distance of 0.15mm (default) and a layer height of 0.2mm there is no gap all between support and part. Seems like the z-distance is truncated to units of the layer height. I think it would be more useful to either read the z-distance as minimum value or at least round it to the next multiple of the layer height.
Compare also Cura 15.04.02, which creates a one layer gap between support and part.

**Comment by Ghostkeeper** [comment]
So round it up? That sounds like a good idea and should be fairly easy to fix.

**Comment by avogra** [comment]
Sounds perfect to me :)

**Comment by Ghostkeeper** [comment]
Made an issue for you in our internal bug tracker. I think it could be implemented for version 2.2 or 2.3.

**Comment by meros** [comment]
Still a problem? Ran into this today, +1 for rounding up!

**Comment by Ghostkeeper** [comment]
No longer a problem. Fixed in 2.3. We're rounding up now.

**Comment by meros** [comment]
The help text still says rounding down...

**Comment by Ghostkeeper** [comment]
Ah :( Good catch. String freeze now though.
