### ISSUE TITLE
Shrinkage ratio blocked by printer settings

### ISSUE THREAD

**Issue by TheGarethGrey** [Ultimaker/Cura#6783]
**Application version**
4.4

**Platform**
win10 1901

**Printer**
Anycubic 4max Pro

**Reproduction steps**
Tried to activate the shrinkage ratio settings

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/58717060/70493796-84b10400-1ace-11ea-9e3c-a6dd3ff0a17b.png)

**Actual results**
nothing

**Expected results**
the shrinkage ratio setting should show up?

**Project file**

[A4_Body2.zip](https://github.com/Ultimaker/Cura/files/3942942/A4_Body2.zip)

**Log file**
(yeah the log file really doesn't show up when i run dxdiag, i'm probably just dumb though

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment]
The engine does not use this value. It's only used by the front-end to decide when to show a warning that something might be too big to print without glue. That is also the reason it's not settable in the interface.
