### ISSUE TITLE
It says minimum extrusion distance should be by default the same as the retraction distance... by default it is not... just pointing this out as something interesting.

### ISSUE THREAD

**Issue by christianpatrickgalles** [Ultimaker/Cura#6789]
**Application version**
(The version of the application this issue occurs with.)

**Platform** windows 10
(Information about the operating system the .)

**Printer** cr10 mini 
(Which printer was selected in Cura?)

**Reproduction steps** changing any setting dies not result in the alteration of said default error
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Yes, that's correct. The default has been overwritten by your printer's definition file:

https://github.com/Ultimaker/Cura/blob/1415db7b7631ebcbdd6c27f615bb1e43d607b5cc/resources/definitions/creality_base.def.json#L226

So this is expected then.
