### ISSUE TITLE
Cura 4.4 Fonts Issue at Configure Setting Menu 

### ISSUE THREAD

**Issue by Ywang1233** [Ultimaker/Cura#6790]
**Application version**
Cura 4.4 Windows

**Platform**
Windows 10 Home 64bit 1909
AMD 2600X 3.6GHz
RX580 8GB
DDR4 3200 16GB 

**Printer**
Custom Corexy BLV Cube

**Reproduction steps**
1. Click Perfomance =>Configure Cura
2. Fonts in setting meun shown as squeezed and garbled.
**Screenshot(s)**
![Cura 4 4_1](https://user-images.githubusercontent.com/36858897/70596989-25640880-1c22-11ea-9785-90c8e6981adb.jpg)
![Cura 4 4_2](https://user-images.githubusercontent.com/36858897/70596997-2bf28000-1c22-11ea-9985-8c38b87efbcf.jpg)
![Cura 4 4_3](https://user-images.githubusercontent.com/36858897/70597015-31e86100-1c22-11ea-9be7-32f27f6da0d9.jpg)

**Actual results**
I have installed Noto fonts. It makes no difference.
I have tried the method by putting theme.json listed in https://github.com/Ultimaker/Cura/issues/4784#issuecomment-443146888 to setting folder. No difference.
I changed the theme file with Arial font, no difference.

Texts in menu still squeezed and garbled

**Expected results**
Clear and readable texts in setting menu. 
**Project file**
[Cura Theme.zip](https://github.com/Ultimaker/Cura/files/3948766/Cura.Theme.zip)

**Log file**
N/A

**Additional information**
Thank you!

**Comment by Ghostkeeper** [comment]
Whoa, this is pretty seriously garbled. I haven't seen anything like this before except maybe the issue with the Cyrillic characters on Linux. I wonder why it's different on your computer than anyone else since the font rendering system is not something that's loaded from Cura's configuration or anything.

**Comment by Ghostkeeper** [comment]
Is it still messed up in the Machine Settings dialogue?

The labels in the main preferences screen are drawn using system settings for anti-aliasing, I think.

**Comment by Ywang1233** [comment]
If I roll the setting list to very bottom, the fonts would change back to normal. But once I roll it back when the Italic sentance' You will need restart the application for blablabla...' shows up, all the fonts are garbled again. I havenot seen any issue like this before either.  Here is the Mechine Setting menu, readable but not fully correct font size. 
![Mechine Setting](https://user-images.githubusercontent.com/36858897/70645226-7fdf8200-1c7f-11ea-82f9-e86824cb7232.jpg)

**Comment by Ywang1233** [comment]
Now I scaled my system display to 120%. The configure menu is readable and much better. I still can see the Italic font not fully correct displayed.
![120%](https://user-images.githubusercontent.com/36858897/70645684-6559d880-1c80-11ea-8c6e-f06e97284a16.jpg)

The mechine setting menu font remains same without noticable difference.

**Comment by Ywang1233** [comment]
By the way, my display setting is 1920*1080 60Hz, previously with 100% scale, current scale is 120%.

**Comment by Ellecross** [comment]
hey @Ywang1233 do you have specific regional system settings that are different than english? I cannot reproduce your issuem unfortunately. :/

**Comment by Ywang1233** [comment]
Thanks for comment. Yes, I do have different setting.  But only one of two
my computers I installed cura on has this issue. Both of them are set as
region China and display language simplified Chinese. The computer
encountering this problem installed windows 10 home from genuine Chinese
image. The other PC with no issue are factory installed English windows 10
home from Dell. But even if I set cura with Chinese, I still see this
issue. So I am not very sure is it because my system setting.

**Comment by Ghostkeeper** [comment]
Maybe your system font doesn't have symbols for Latin characters? What is your system UI font?

**Comment by Ywang1233** [comment]
Well, I did install the Noto font set, so it may not be miss of Latin characters I think. Even I set Cura to simplified Chinese, I still met this issue. It might be more like a font size issue, not font itself. Now since I run Cura with 125% system UI scale, I do not see this issue anymore.

Yanda

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ghostkeeper<mailto:notifications@github.com>
发送时间: 2019年12月17日 16:34
收件人: Ultimaker/Cura<mailto:Cura@noreply.github.com>
抄送: Ywang1233<mailto:lelexiao12@gmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Ultimaker/Cura] Cura 4.4 Fonts Issue at Configure Setting Menu (#6790)


Maybe your system font doesn't have symbols for Latin characters? What is your system UI font?

―

**Comment by Ghostkeeper** [comment]
Can you try something for me?

1. Download this file: http://dulek.net/work/theme.json (perhaps right click -> save as)
2. Save that file in place of `C:\Program Files\Ultimaker Cura 4.4\resources\themes\cura-light\theme.json` (or wherever you installed Cura). You'll need to provide admin access to do this, so download it first to somewhere like your desktop and then copy it over with the file browser.
3. Make sure your system UI scale is back at normal, where you originally had the issue.
4. Restart Cura. Are the fonts normal now?

**Comment by Ywang1233** [comment]
Thanks for help, unfortunately, Issue remains. I recorded a short screen record video to demonstrate this issue, hope you can see it. I shared it with a google drive link cause it is over sized for attachment.
https://drive.google.com/open?id=12oK0UJcXczwGo69sVpPMOOVPuI05FB03


Yanda

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Ghostkeeper<mailto:notifications@github.com>
发送时间: 2019年12月18日 17:58
收件人: Ultimaker/Cura<mailto:Cura@noreply.github.com>
抄送: Ywang1233<mailto:lelexiao12@gmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [Ultimaker/Cura] Cura 4.4 Fonts Issue at Configure Setting Menu (#6790)


Can you try something for me?

  1.  Download this file: http://dulek.net/work/theme.json (perhaps right click -> save as)
  2.  Save that file in place of C:\Program Files\Ultimaker Cura 4.4\resources\themes\cura-light\theme.json (or wherever you installed Cura). You'll need to provide admin access to do this, so download it first to somewhere like your desktop and then copy it over with the file browser.
  3.  Make sure your system UI scale is back at normal, where you originally had the issue.
  4.  Restart Cura. Are the fonts normal now?

―

**Comment by Ghostkeeper** [comment]
Hrm, yeah I see it. That was the one idea I had that could've been causing this. With that other theme file it's drawing this text just in the OS default font size and style. It should be the most basic way to draw text, really.

It's very hard to debug this remotely. We're only guessing in the dark here until we know how to reproduce this problem.

**Comment by Ywang1233** [comment]
Yeah, I understand. The other functions act really well. Thanks alot.

**Comment by shmyu12** [comment]
I have same problem and I use RX580.
I guess AMD graphics card is the cause.
I don't know any more...

**Comment by Ywang1233** [comment]
Yep, you are right. I have the same graphic card. AMD hasn't fixed the
driver yet.

**Comment by AndreVanKammen** [comment]
![image](https://user-images.githubusercontent.com/10424550/81692928-6c6b5980-945f-11ea-9efa-ab1c7ef43941.png)

I have the same Problem,
Windows 10
GTX 1070
4K TV as monitor

**Comment by Mathieu1972** [comment]
Hi,
I had the same problem with Cura 4.6.1. It was just displayed unreadable characters in fields of parameters. You can see what is inside the field of parameter by copy/paste in a notepad to confirm that there is a parameter but it is still not readable.
The problem for me was the font Noto Sans that was not known or set correctly. Close Cura and then 
edit with Notepad++ or other editor the C:\Program Files\Ultimaker Cura 4.6\resources\themes\cura-light\theme.json and replace the Family font to "Times" instead of "Noto Sans". Times is a common type of font in most systems.

You can do the same for the others theme.json in the others directories.
Restart finally Cura and it should work well..

**Comment by Ywang1233** [comment]
I tried this method first, it doesn't work for me. Seem like multiple
causes could lead to this phenomena.

**Comment by eduncan911** [comment]
I'm getting the same.  Clean Windows 10 install, nothing installed.

However, I am trying to use Dremel's branded version of Cura, which is version... Actually, I have no clue as I can't read the About screen.

![Screenshot from 2020-07-16 20-25-47](https://user-images.githubusercontent.com/104980/87735242-f8249d80-c7a2-11ea-8302-b61ee06ae739.png)

![Screenshot from 2020-07-16 20-23-40](https://user-images.githubusercontent.com/104980/87735246-fc50bb00-c7a2-11ea-8bc5-72cf11587eef.png)

![Screenshot from 2020-07-16 20-24-19](https://user-images.githubusercontent.com/104980/87735248-ff4bab80-c7a2-11ea-84a2-481eb4f8a866.png)

if it matters, I am running Windows 10 within VirtualBox on Linux.  The latest Cura for Linux works fine: however, there are no profiles for Dremel's 3D45 in them (there is a plugin for 3D20 that works great for that printer, but not so much for the 3D45).

**Comment by Ghostkeeper** [comment]
@eduncan911 Your Cura version is rather old. Somewhere around 3.5 I'm guessing, based on those screenshots.

Your issue is different from what this topic is about. Please see https://github.com/Ultimaker/Cura/issues/6822 instead.

**Comment by AndreVanKammen** [comment]
![image](https://user-images.githubusercontent.com/10424550/95737795-84523e00-0c88-11eb-8241-bbab4b7d224d.png)
I keep having these barely readable fonts in Cura on my windows 10 PC throughout all versions. I'm working on a 4K tv, seems the font's are rendered to small so they fall in between pixels.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by Ywang1233** [comment]
I don't know. I have updated my pc os to win11, haven't seen it on win 11
yet.

**Comment by GregValiant** [comment]
I'll close it then.
