### ISSUE TITLE
Marlin and Junction Deviation

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#6792]
**Is your feature request related to a problem? Please describe.**

Not really a problem ; it is related to a new feature in marlin 2.0.x commit 5103cdc, realeased 2019/12/01 : Junction Deviation, that can be accessed through M205, and now activated by default in the firmware (it was implemented in 1.1.9 and 2.0.x 12 months ago if I remember correctly). This will make jerk control obsolete for Marlin based printers in a near future. See Configuration.h, line 768

**Describe the solution you'd like**

An option allowing the user to edit the Junction Deviation value, the way we can choose to activate jerk control and edit its values. Jerk Control and Standard Deviation Control being mutually exclusive.

**Describe alternatives you've considered**

- hardcoding the macro and the value in firmware (needs compiling + flashing)
- using M205 in the start gcode 

**Affected users and/or printers**

All Marlin users who switch to marlin 2.0.x, and all printers that will come with marlin 2.0.x and this feature activated (it is by default). All Marlin 1.1.9 users who activate Junction Deviation on a recently downloaded Marlin 1.1.9.

**Comment by Ghostkeeper** [comment]
Setting the M205 in the start g-code is our current solution for all of these printer or firmware specific things. We're not about to change that, I think it's an acceptable solution.
