### ISSUE TITLE
Add the Monoprice Maker Select to the printer presets

### ISSUE THREAD

**Issue by Pikamander2** [Ultimaker/Cura#6812]
**Is your feature request related to a problem? Please describe.**
The Monoprice Maker Select (and Monoprice Maker Select v2) aren't on the 3D printer presets list (AKA "Add a printer").

**Describe the solution you'd like**
It would be nice if the Monoprice Maker Select v2 was on the list. Since there are only three printers listed under the Monoprice submenu, there should be enough room for it.

**Affected users and/or printers**
The Monoprice Maker Select v2 was one of the more popular and recommended budget printers a few years ago, so there should still be a fair number of people who would benefit from this.

**Comment by nallath** [comment]
If someone makes a pull request for the printer, we will hapily review it. But we don't have the printer, so we can't test (and thus, make) profiles for it.
