### ISSUE TITLE
[4.4.0] - Fan Controls on USB Prints

### ISSUE THREAD

**Issue by Audune** [Ultimaker/Cura#6824]
4,4,0

Windows 10 1903 - Nvidia Geforce 2070

Anycubic Chiron

**Reproduction steps**
1. Printing via USB connection

**Actual results**
Fan GCODE M107 Off in Startup Scripts causes the printer to ignore all future fan commands.  Manually sending M106 nnn does nothing.  Fan control's based on layer does nothing.  Starting fan at layer 0 at 255 changes nothing.

**Expected results**
Fan should start Off, then at layer 2 go to 100%.

**Project file**

[AC_xyzCalibration_cube.zip](https://github.com/Ultimaker/Cura/files/3981739/AC_xyzCalibration_cube.zip)

**Log file**
Nothing i could see generated during print in the log file?
[cura.log](https://github.com/Ultimaker/Cura/files/3981734/cura.log)

**Additional information**
Regardless of file used and sliced, printing from USB does not engage the fans with default starting GCODE scripts.  Exporting the file to the SD card and printing from there works correctly.  If I comment out the M107 in the starting script, and add M106 1 (to start the fan low) it does start cooperating as expected.

If M107 is sent, while a Print is active, starting, and after, sending M106 commands do nothing at the printer.  The only way to recover from this is to power cycle the printer.

**Comment by Ghostkeeper** [comment]
So you're saying that you have to edit the start g-code?

As far as what I can see in [this popular source of documentation](https://reprap.org/wiki/G-code#M107:_Fan_Off), `M107` means "fan off" and `M106` means "fan on". So from that description I would make out that sending out `M106 S###` would turn the fan on even though it was off before.

If your printer doesn't work that way and sending out any `M107` breaks the printer's fans until you do a power cycle, you have to edit the start g-code to use `M106 S0` instead, which should be equivalent. If you think that all Anycubic Chiron printers work that way, you can send us a pull request to change it.

Normally `M106` would remain working even after `M107`. Your printer may be an exception, but I can't test that with your printer, so there's nothing we can do from this side to fix it. We rely on the community to maintain printer profiles (except for Ultimaker in a way, being our employer). So I'll close this; there's nothing we can do about it.
