### ISSUE TITLE
Out of the blue errors on startup: phantom profiles with extruders that I do not have 

### ISSUE THREAD

**Issue by ylectron** [Ultimaker/Cura#6835]
![CuraErr](https://user-images.githubusercontent.com/11709995/71299507-e5bdbf00-238d-11ea-97a2-21e6418e9dae.png)

**Comment by Ghostkeeper** [comment]
When I start up Cura I don't get these errors. Do you have any more reproduction steps? Or a log? We need you to fill up the issue template in order to begin debugging this.
