### ISSUE TITLE
Most text in cura has disappear

### ISSUE THREAD

**Issue by LuisLlana** [Ultimaker/Cura#6841]
Hello,
  I have the same problem an in issue #5645, most of the test has disappeared.  I was running Ubuntu 18.04 when this problem first arose. I have not been using Cura for a time. Meanwhile, I ugraded to Ubuntu 19.10. The problem persists. 

**Application version**
 dpkg -l cura
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-====================================
ii  cura           3.3.1-2      all          GUI G-code generator for 3D printers

**Platform**
Ubuntu 9.10

00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0, IRQ 16
        Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
        Capabilities: [88] Subsystem: ASUSTeK Computer Inc. Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller
        Capabilities: [80] Power Management version 3
        Capabilities: [90] MSI: Enable- Count=1/1 Maskable- 64bit-
        Capabilities: [a0] Express Root Port (Slot+), MSI 00
        Capabilities: [100] Virtual Channel
        Capabilities: [140] Root Complex Link
        Capabilities: [d94] #19
        Kernel driver in use: pcieport

**Reproduction steps**
I cannot say.

**Screenshot(s)**
![cura1](https://user-images.githubusercontent.com/1461088/71326239-70bac880-24f8-11ea-8f96-f352e78b67d0.png)
![cura2](https://user-images.githubusercontent.com/1461088/71326240-70bac880-24f8-11ea-8bae-ec9c9f41a2f8.png)

**Comment by Ghostkeeper** [comment]
Could you try moving or deleting the `~/.qtshadercache` folder (while Cura is not running)?

**Comment by LuisLlana** [comment]
I did not have that directory. Instead, there were two similar direcories inside ~/.cache: qtshadercache and qtshadercache-x86_64-little_endian-lp64
I removed both without success. In fact, I have deleted the whole .cache directory.
I have other users in the same machine and all of them have the same problem. I have removed (with --purge option) and install again the package and it still does not work.

**Comment by Ghostkeeper** [comment]
Does the problem also occur when you're using our AppImage releases?

If not, then it's some dependency coming from your system that renders these fonts differently. It could be FreeType, or perhaps Qt itself. Myself I'm running from source on Ubuntu 19.10 as well. I'm using `libfreetype6/eoan,now 2.9.1-4` to render the fonts, and Qt 5.13.2 via the PyQt5 Pip package.

**Comment by canonex** [comment]
I confirm this behavior on Debian 10.
The version that comes with the Debian installer is the 3.3.1, quite old.
_An updated appimage (v. 4.x) has no issue._

**Comment by Ghostkeeper** [comment]
We are not maintaining the Debian installer. Debian has a maintainer to release it to their package manager but they are not really involved in development with us. We only support the AppImage.

Though we're happy to fix issues the package maintainers are encountering as long as they're not in the way of our normal development, we don't have the resources to maintain releases on all those platforms out there. AppImage is our only Linux distribution.

**Comment by onitake** [comment]
If #5645 was fixed by #7139 , then it's not in 4.8 yet, as far as I can see. You'll have to wait for the next Cura release.

And a workaround for the rendering issue is forcing the material Qt theme:

```shell
QT_QUICK_CONTROLS_STYLE=material cura
```

**Comment by onitake** [comment]
Debian buster (stable) still carries Cura 3.3, which is severely outdated now.

If you want to try a newer version, please upgrade to bullseye (testing) or wait until it becomes stable later this year.
Or rely on the AppImage version provided by UltiMaker for the time being.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by onitake** [comment]
To my knowledge, this has been working fine since at least Cura 5.0.
I think the issue can be closed.
