### ISSUE TITLE
[4.4.0] Tree support not generated for overhang

### ISSUE THREAD

**Issue by MisterScott** [Ultimaker/Cura#6842]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by MisterScott** [comment]
Works when I adjust Tree Support Branch Diameter Angle from 15 down to 10.  I think this supports the non-intersecting-cones hypothesis.

![WorksWithSmallerAngle](https://user-images.githubusercontent.com/6548614/71341728-7ff94080-250f-11ea-8948-5b886c9fcbd5.png)

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this problem. Here I have a bit of overhang, and clearly it's generating tree support:
![Screenshot from 2019-12-23 13-21-43](https://user-images.githubusercontent.com/2448634/71357858-49f7a300-2587-11ea-8427-57d2e0e5c8e0.png)

Please fill in the issue template with your reproduction steps and observed behaviour. You seem to have had some trouble editing that so maybe it didn't publish it in the end?

**Comment by Ghostkeeper** [comment]
Note that the default for Branch Diameter Angle is 5 degrees. I tried with 15 as well and it seemed to work fine. But of course there will be values for this angle where it produces unprintable results, like 89.999 degrees and such.
