### ISSUE TITLE
[2.1] Rotate tool: white text on light gray background

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#685]
I would also love to see a dark blue border around the box. The box is inside the model so you can see it, but on the normal white background you won't. So a border would highlight it.

![cura](https://cloud.githubusercontent.com/assets/1847437/14150222/4d0369f6-f6a8-11e5-8162-51e40d405e02.png)

**Comment by Ghostkeeper** [comment]
The text properly appears black for me: http://i.imgur.com/sdxtxCX.png

**Comment by thopiekar** [comment]
That's strange. Maybe we are using a system value here. I'll recheck using
a light theme, as I'm using "Breeze Dark" here (KDE).

**Comment by thopiekar** [comment]
Yes, it is! It seems to use the default color whereas the rest of the UI uses light colors.

![cura](https://cloud.githubusercontent.com/assets/1847437/14172607/205643d8-f739-11e5-92c9-75da63fcec83.png)
![cura1](https://cloud.githubusercontent.com/assets/1847437/14172610/2451cc96-f739-11e5-8d84-ec396ccaf36b.png)

**Comment by Ghostkeeper** [comment]
Good find!

**Comment by fieldOfView** [comment]
Fixed in https://github.com/Ultimaker/Cura/commit/a32c00141ac28ff116ed11eb2b10f77f989cf812

**Comment by thopiekar** [comment]
Thanks!

**Comment by fieldOfView** [comment]
You're welcome. Taking this a bit off-topic... In some of your previous screenshots, I noticed black text on a dark background that I found quite hard to read (I remember a USB print progress dialog). Is that a combination you would expect with the theme you use? I'm not overly familiar with themes in Linux.

**Comment by thopiekar** [comment]
I guess the best text color there, would be the default given by Qt5 (theme
used by the desktop).
In that case it should be the light gray color that was found in this issue.

So I would be fine with that or to overwrite all colors. But bad thing
would be that the window decorator will still remain black in my case.

**Comment by fieldOfView** [comment]
@thopiekar I think I fixed most of the occurrences of the text in dark color on dark background with your theme. Could you check?

**Comment by thopiekar** [comment]
@fieldOfView, of course! I'll give feedback as soon as possible :wink:

**Comment by thopiekar** [comment]
Sorry, but the color is still not black.

**Comment by thopiekar** [comment]
@Ghostkeeper @fieldOfView Better reopen this issue so you don't forget to fix it before releasing 2.1 :wink:

**Comment by fieldOfView** [comment]
It won't be fixed for 2.1, but it has been fixed in master. Even though it is only a "cosmetic" change with little to no risk, we are too close to release to merge this in.

**Comment by thopiekar** [comment]
Ah, ok. I thought you wanted to fix that in 2.1, too. I've got a PPA for
master builds, but don't use it at the moment.
