### ISSUE TITLE
Remove auto connect

### ISSUE THREAD

**Issue by Vertabreak** [Ultimaker/Cura#6857]
As one of the geeetech forum admins cura has bricked 100s of board from the auto connect feature. It would be much safer to have a connect button like many other slicers have. It is true these board can be revived with a in circuit programmer but the amount of returns and issues filed over the auto connect feature in cura is hard to ignore.

**Comment by nallath** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5207
