### ISSUE TITLE
Cura Wont' Start

### ISSUE THREAD

**Issue by bstott** [Ultimaker/Cura#686]
Cura will not start. I get a splash screen. Then nothing. When the splash screen is clicked on it goes away. I have uninstalled the previous versions with the uninstall.exe and Windows program uninstall.

**Application Version:** 15.04.03

**Platform:** Windows 8.0	
**Qt:** 4.8.5
**PyQt:** 4.10.3
**Python:** 2.7.8
**Display Driver:** AMD Radeon 	HD 6310 Graphics, Driver version 14.100.0.0

**Steps to Reproduce:**
Try to run Cura 15.04.03

**Actual Results:**
Splash Screen stays on window until clicked on. Then disappears without Cura application starting.

**Expected results:**
Should be able to see the Cura GUI and use the application to slice stl files and 3D print.

**Additional Information:**
N/A

Note: Pronterface (python app) works.

Output log attached. Note that the output log is located in the ...User/.cura directory not in Appdata...

[output_log.txt](https://github.com/Ultimaker/Cura/files/200336/output_log.txt)

**Comment by Ghostkeeper** [comment]
This is regarding the old Cura version. It has its own repository here: https://github.com/daid/Cura/issues

It looks like it can't find the GLUT library in Python.
