### ISSUE TITLE
Crash on Custom Filament Form

### ISSUE THREAD

**Issue by zurtox** [Ultimaker/Cura#6873]
**Application version**
4.3.0

**Platform**
Windows 10 version 1809 Build 17763.914

**Printer**
Ender 3

**Reproduction steps**
1. Go to preferences -> Material (Ctrl+K)
2. Create new custom material.
3. Type on brand 'Generic'
4. Go to next field

**Actual results**
It crashes unexpectly.

**Expected results**
Can type or continue making actions in order to save the form.

**Log file**
[error.log](https://github.com/Ultimaker/Cura/files/4008471/error.log)

**Additional information**
n/a

**Comment by nallath** [comment]
Does this issue also happen with 4.4.1?

**Comment by roberto081194** [comment]
Yes, it happens too.

**Comment by nallath** [comment]
I don't see anything in the logs about a crash and I can't reproduce it myself (although I am on Fedora, not Windows)
