### ISSUE TITLE
Extreme Priming After Start G-Code

### ISSUE THREAD

**Issue by bmxorcist** [Ultimaker/Cura#6874]
**Application version**
CURA 4.4.1

**Platform**
Windows 7, 64 bit

**Printer**
Custom ("Precision Prusa")

**Reproduction steps**
1. Start any print with any profile
2. After performing my Start G-Code, the printer moves to X-Max and Y-Max and starts spewing ridiculous amounts of filament to no end. I have to abort the print.

Here's my G-Code. Anyone see anything weird? 

;FLAVOR:Marlin
;TIME:10236
;Filament used: 7.93095m
;Layer height: 0.3
;MINX:24.735
;MINY:94.444
;MINZ:0.3
;MAXX:163.265
;MAXY:183.556
;MAXZ:9
;Generated with Cura_SteamEngine 4.4.1
M140 S65
M105
M190 S65
M104 S190
M105
M109 S190
M82 ;absolute extrusion mode

;BEGINNING OF MY START G-CODE
M280 P0 S160  ; BLTouch Alarm Release
G4 P100   ;delay for BLTouch
G28  ; start from home position
G34  ; LEVEL Z STEPPERS
G29 L1  ; Load saved bed leveling data
G29 J  ; Adjust the existing mesh with a 3 point check
;END OF MY START G-CODE

G92 E0
G92 E0
G1 F1800 E-1            ;<------------? This is where it extrudes violently forever
;LAYER_COUNT:30
;LAYER:0
M107 P1
G1 F600 Z0.8
G0 F900 X33.32 Y95.015 Z0.8

**Comment by nallath** [comment]
Nope. The only thing I can come up with is that it's not liking the negative extrusion, but that's more of a printer issue than one with Cura.

**Comment by Ghostkeeper** [comment]
Underflow? I think you're looking at a firmware bug here.

**Comment by bmxorcist** [comment]
I would think that too, but the same firmware works flawlessly on any other slicer. Anyway, I've moved to Prusa Slicer and I don't think I'll ever turn back. This program is great.

**Comment by Ghostkeeper** [comment]
So if you let another slicer write the same g-code to a file and send that over to the printer it works?

There must be something different in the g-code.

**Comment by bmxorcist** [comment]
I agree. I think it's something Cura does before or after sending the starting gcode. Could it be the M82?
But I've reflashed my firmware and it's running beautifully with Prusa Slicer, and I do still have the gcode in question... I'll run it and see if it still spews on the new firmware and running off the SD instead of over USB.

**Comment by Ghostkeeper** [comment]
It could be the M82 since that should change how extrude commands are interpreted. If it is though that is still a firmware bug. Since Cura sets the current E position to 0 at the beginning of the print with the `G92 E0` commands, it shouldn't matter whether it's relative or absolute. `0 + -1` is still `-1` after all.

**Comment by FlailAway** [comment]
Not sure if it is any help, but that E-1 works fine as a blob-suck at the start on a stock A6 board and a Delta with Gen-L both running Marlin 1.1.9. I actually use it in my end-code to release pressure on the filament in Bowden on both. Been using it for a looong time.

PrusaSlicer? You will be back. :)
