### ISSUE TITLE
Bridge intitial infill should span abutments

### ISSUE THREAD

**Issue by gcanzalone** [Ultimaker/Cura#688]
The direction of the initial infill layer for bridges should span abutments instead of attempting to connect perimeters as the current version does. Bridges as currently implemented sag badly as a result of connecting infill to only thin perimeters.

**Comment by BagelOrb** [comment]
The size of the abutment is not related to the direction of infill layers. As it is now it's simply the breadth of the walls.

Bridging is currently in quite a poor state. It will be renovated in hopefully not too much time.

**Comment by carbonrim** [comment]
BagelOrb would you mind to answer what does it mean "not too much time"? Is it 2 months or a year? I'm just curious, because I really like Cura and use it, but only for projects/objects not demanding bridges (I don't like supports).

**Comment by BagelOrb** [comment]
It has been too much 😓 
Again I'm inclined to say it will be here in a couple of months, sooooo maybe at least another year.

:(

**Comment by ianpaschal** [comment]
This has been fixed.
