### ISSUE TITLE
[4.4.1] some holes are blocked in printing and in previewing - in prepare they open 

### ISSUE THREAD

**Issue by guy-maker** [Ultimaker/Cura#6895]
**Application version**
4.4.1

**Platform**
windows OS 64 bit 

**Printer**
Creality Ender Pro 10 

**Reproduction steps**
1.open STL file and rotate it so it lies on the floor 
2. slice 
3. preview 

you can see that after preview some holes are blocked by filament - and also when printing - these would be blocked

<img width="496" alt="avter preview" src="https://user-images.githubusercontent.com/59409247/71640396-ed386e80-2c91-11ea-99a2-b6bb6be18c77.PNG">

<img width="483" alt="open" src="https://user-images.githubusercontent.com/59409247/71640389-b5312b80-2c91-11ea-87dd-89d5cf37c312.PNG">

**Comment by smartavionics** [comment]
This is very likely to be a problem with the model. Please save the project file (File -> Save) and then zip (or rename to .zip) the .3mf and attach to this issue. Thanks.

**Comment by guy-maker** [comment]
[back7.zip](https://github.com/Ultimaker/Cura/files/4014013/back7.zip)

attached the model

**Comment by smartavionics** [comment]
Thanks for model, it has problems as you can see from the mesh tools plugin message...

![Screenshot_2020-01-01_11-41-13](https://user-images.githubusercontent.com/585618/71640939-bf502b80-2c8b-11ea-93c0-093591d2a2d0.png)

**Comment by guy-maker** [comment]
was issue with the model - don't know what issue exactly - I redraw it again and it is ok.
