### ISSUE TITLE
[4.4.1]Duplicating material presets copies wrong data

### ISSUE THREAD

**Issue by Marlor** [Ultimaker/Cura#6899]
When you duplicate a generic material, the copy will get wrong data.
This happens with some presets like PLA, PETG and ABS but not all of them like PC and PVA

**Application version**
4.4.1

**Platform**
Windows 10

**Printer**
Creality CR10s

**Reproduction steps**
1. Klick on Duplicate on a Preset like PLA (Build Plate Temp is 60°C)
![PLA Preset](https://user-images.githubusercontent.com/3026213/71671130-7030f600-2d72-11ea-83ee-7d276cfbd9ed.png)

2. You will get a copy were Build Plate Temp is 50°C, retraction is different too
![PLA Preset 2](https://user-images.githubusercontent.com/3026213/71671138-758e4080-2d72-11ea-888e-a4e9d5144973.png)

**Comment by rburema** [comment]
Seems to happen when a printer of that type is active.

**Comment by rburema** [comment]
We've made a ticket for it in our internal system: CURA-7087

**Comment by evtrados** [comment]
The issue has been resolved and the normal behavior of the material duplication will be working in the next Cura release.
