### ISSUE TITLE
Plugin Inventor Dosn't Work

### ISSUE THREAD

**Issue by Beppo86** [Ultimaker/Cura#6914]
the plugin that should read the inventor files, from version 4.4.1 is no longer present on the store.
serves in remedy or a procedure to reactivate it
thank you

**Comment by fieldOfView** [comment]
That plugin is a 3rd party plugin by @thopiekar, and it needs to be updated to be compatible with Cura 4.4 and newer.

**Comment by Beppo86** [comment]
thanks, but I didn't think it was an external plugin, since ultimaker advertises it very evidently

**Comment by fieldOfView** [comment]
It is though:
https://thopiekar.eu/cura/cad/inventor/

**Comment by Beppo86** [comment]
do you know if there is a method to add this extension? because there is nothing on that page.
or do you know if you can download the old version? and if so, can you also give me the link?
thank you

**Comment by fieldOfView** [comment]
The old version does not work with Cura 4.4

You can download Cura 4.3, and use the Inventor plugin in that version of Cura.

**Comment by rburema** [comment]
If you want to contact @thopiekar regarding this plugin, please do so here: https://github.com/thopiekar/CuraInventorPlugin/issues
