### ISSUE TITLE
ImportError: No module named 'Arcus'

### ISSUE THREAD

**Issue by easonyuexcellent** [Ultimaker/Cura#692]
I compiled libArcus-master with cygwin. But I cannot find Arcus.py.

**Comment by nallath** [comment]
That's because there is no such thing as Arcus.py

We use sip to create python bindings for arcus.

**Comment by easonyuexcellent** [comment]
Thanks, I see.
How to find the module then? I build and installed sip and libarcus, but can't find it...

**Comment by nallath** [comment]
Have you correctly set your python path?

**Comment by Ghostkeeper** [comment]
Your build should leave something like `Arcus.pyd` somewhere. That file needs to be in a directory on your `PYTHONPATH` environment variable.

**Comment by easonyuexcellent** [comment]
IC, now it can run. Thanks a lot.
