### ISSUE TITLE
[4.4.1] Incorrect line width when "Support Infill Layer Thickness" is thicker than "Layer Height"

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#6938]
**Application version**
4.4.1

**Reproduction steps**
1. Set "Support Infill Layer Thickness" to multiple of Layer Height
2. Enable Support Interface with 100% density and Concentric pattern

**Screenshot(s)**
![Screenshot (191)](https://user-images.githubusercontent.com/23495338/71973711-44b27d80-3242-11ea-958c-381fb620f9de.png)
Pic1: 0.08 Layer Height , 0.45 Support Line Width , **0.24 Support Infill Layer Thickness**

![Screenshot (192)](https://user-images.githubusercontent.com/23495338/71973715-467c4100-3242-11ea-804e-732af8d95269.png)
Pic2: 0.08 Layer Height , 0.45 Support Line Width , 0.08 Support Infill Layer Thickness

Note that in both pictures, Line Width is 0.45mm

**Actual results**
There is a gap between Support Interface and Support Infill because Support Infill is treated as multiple times wider than actual Line Width.

**Expected results**
Support Infill Line Width treated as regular Line Width
Will appear to overlap with support interface in layer view
![Screenshot (194)](https://user-images.githubusercontent.com/23495338/71974172-62ccad80-3243-11ea-978f-cfe2a518e4dc.png)

**Additional information**
Possibly the same cause as https://github.com/Ultimaker/Cura/issues/5345

**Comment by rburema** [comment]
Have you tried printing this? I think it might be a visual issue: If I take a dual extrusion printer, and slice with a different support material, then try to reproduce this, I should be able to get wildly different estimates for the length of the support-material used, but I'm not.

This would make (some) sense because, AFAIR, the line width in the preview is calculated from the amount of material extruded, which is more when it's for > 1 layers (relative to the 1 of the other types at least). In other words, those lines _would_ approximately as thick if they where to be printed on each z that is visited, but they are not.

Still mostly a bug though, even if I'm correct, just in a different system (the preview one).

**Comment by Block137** [comment]
I tried and got issue with PVA support interface not adhering to PLA support infill (I have 3 extruders).

I don't think it's just visual because after #5345  got fixed, there was visible difference in preview. I thought it would have fixed both infill and support but only infill gap problem got fixed.

I got around this by reducing line width to a third and 300% flow and some crazy offset to compensate walls.

**Comment by Block137** [comment]
> Have you tried printing this? I think it might be a visual issue: If I take a dual extrusion printer, and slice with a different support material, then try to reproduce this, I should be able to get wildly different estimates for the length of the support-material used, but I'm not.

The issue is not material used, just the actual gap created by mistaken line width.

**Comment by rburema** [comment]
Hm... I just had a look at the fix that was applied, and it might be the reason this is happening, as the fix (unlike the original code) references the (global) layer-height and the sparse thickness specifically for infill, even though the algorithm is also used for support.

**Comment by rburema** [comment]
Devs: It's on our backlog/internal system as CURA-7104 now.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by Block137** [comment]
It is working as expected in 5.8.1
![Screenshot 2024-11-23 022124](https://github.com/user-attachments/assets/fc901bff-6c1c-4f54-b348-647079855b18)
