### ISSUE TITLE
[4.4.0]Stuck on Welcome screen 

### ISSUE THREAD

**Issue by lestofante** [Ultimaker/Cura#6941]
**Application version**
4.4.0

**Platform**
arch linux, amdgpu

**Printer**
none

**Reproduction steps**
1. open cura
2. the welcome screen appear, but nothing can be done

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1166173/72016696-90761e80-3264-11ea-9f20-c6297713cadd.png)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4037229/cura.log)

**Comment by smartavionics** [comment]
Your system is missing a couple of python modules. try installing trimesh and zeroconf. As you are not using the UM build you need to get whoever built your copy of cura to ensure that the required module dependencies are satisfied.

**Comment by fieldOfView** [comment]
Alternatively, use the AppImage provided by Ultimaker.

**Comment by smartavionics** [comment]
> Alternatively, use the AppImage provided by Ultimaker.

Good idea. Even better, use the AppImage provided by me!

**Comment by nallath** [comment]
I'm closing this, since we only support the appimage.
