### ISSUE TITLE
Send to cura 2.3.1 not working dell vostro

### ISSUE THREAD

**Issue by radamiBR** [Ultimaker/Cura#6952]
Send to cura 2.3.1 not working

Windows 7 
Machine: dell vostro 32bits
erro open cura 2.3.1

cura.log stop line
Initialized OpenGL subsystems.
OpenGL Version:  2.1.0 - Build 8.15.10.2008
OpenGL Vendor:   Intel
OpenGL Renderer: Intel(R) Graphics Media Accelerator HD

**Comment by fieldOfView** [comment]
Cura 2.3.1 is not supported anymore. Unfortunately, it is the last version that runs on your 32 bit windows version.
