### ISSUE TITLE
Options for topmost wall lines

### ISSUE THREAD

**Issue by thelastWallE** [Ultimaker/Cura#6953]
**Is your feature request related to a problem? Please describe.**
The topmost lines of the walls have no options like you can set for the top surface skin lines.

**Describe the solution you'd like**
Have a whole option-set for the toplines of walls like the options for topsurface skin lines

**Describe alternatives you've considered**
The other not so perfect solution: take the values from the top surface skin for these wall lines. This would be not really a nice continuity for the options because these lines are for the walls and the others would be counted as skin.

**Affected users and/or printers**
All prints there you would like to have a nice toplayer.

**Additional context**
https://imgur.com/ek2YMuK

**Comment by mahtDFR** [comment]
We have discussed this and decided we have other priorities for the time being.
