### ISSUE TITLE
Layered fan speed

### ISSUE THREAD

**Issue by Snaiper1945** [Ultimaker/Cura#6960]
I would like to see the layered fan speed, by analogy with the material flow.

**Comment by Ghostkeeper** [comment]
What do you mean?

**Comment by lbibass** [comment]
Perhaps they mean they would like to have the fan speed change depending on the volume of material coming out? a .07mm layer would need less cooling than a 1mm layer.

Though that matters more with adaptive layers.

**Comment by Snaiper1945** [comment]
No, your know layer mode with defferent colors in cura? It would be nice to have a fan speed display mode.

**Comment by fvrmr** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7495
