### ISSUE TITLE
Mistake in wiki, configuration page

### ISSUE THREAD

**Issue by ArnaudTa** [Ultimaker/Cura#6963]
Hello, this [page](https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations#linux) in wiki could be improved.

$USER should be replaced by $HOME you don't have to explain it and the paths from wiki could be copy/paste directly in file manager.

Thanks.

**Comment by rburema** [comment]
Isn't it distribution/shell dependent which one gets set?

**Comment by ArnaudTa** [comment]
AFAIK it's true for all distribution/shell

**Comment by Ghostkeeper** [comment]
Not in Windows apparently though: https://superuser.com/questions/607105/is-the-home-environment-variable-normally-set-in-windows

**Comment by fieldOfView** [comment]
But for Windows, that page should really just use %APPDATA% instead of $USER/AppData/Roaming and %APPDATALOCAL% instead of $USER/AppData/Local. $USER is syntactically the wrong notation in Windows (not even recognised in a path), and it semantically wrong in systems that have changed the location of the roaming app data (eg stored on a network drive).

**Comment by ArnaudTa** [comment]
The link leads to the Linux section. I should have precise it in report.

**Comment by Ghostkeeper** [comment]
As far as I could find, for Linux indeed the $HOME seems to be available everywhere.

**Comment by Ghostkeeper** [comment]
Fixed it!

**Comment by Ghostkeeper** [comment]
For Windows we need to look into further improvements. Didn't anyone test that?

**Comment by rburema** [comment]
The linked page is for linux only :-)

The windows one has been updated a number of times now. The latest changes where just last week when Matt needed to install from source.

**Comment by mahtDFR** [comment]
Thanks for the report, investigating Windows now

**Comment by mahtDFR** [comment]
Updated, if there are further comments please raise them and I can make improvements.
https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations

**Comment by fieldOfView** [comment]
The Windows paths should use `\` (backslash) instead of `/` (forward slash). Also the HOMEPATH that is explained is not used in the paths.

**Comment by mahtDFR** [comment]
> The Windows paths should use `\` (backslash) instead of `/` (forward slash). Also the HOMEPATH that is explained is not used in the paths.

Good points, updated.
