### ISSUE TITLE
Add new TEVO Tarantula PRO profile 

### ISSUE THREAD

**Issue by FN5969** [Ultimaker/Cura#6970]
Tevo relise new printer Tarantula PRO and there is no existing profile for it. 
This will help for Tarantula PRO users
I made simple json profile and simple but correct printing platform 3d model. Json has correct "Printer Settings", Printhead Settings", "Start G-code". And of corse i tested it in several cura ver. and it works fine.

[TarantulaPro.zip](https://github.com/Ultimaker/Cura/files/4058411/TarantulaPro.zip)

**Comment by mahtDFR** [comment]
To add your machine profile to Cura you need to make a pull request. Instructions to do this can be found here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
