### ISSUE TITLE
Build volume temperature can not be set

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#6973]
Cura PPA master
When setting the Build volume temperature manually, it automatically jumps back to the minimum value.
Bug or feature?
If you select another profile it does show the changed value at the customized settings.

**Comment by mahtDFR** [comment]
Can you give me some specific reproduction steps here?

**Comment by maukcc** [comment]
The build volume temperature is at 20 degrees, manually change it to 30 and press enter. 30 remains. When the cursor goes out of the build volume temperature field it changes back to 20. 
The gcode file will read M141 S20.
A change profile dialog box will show a customized build volume temperature of 30.

**Comment by mahtDFR** [comment]
Not seeing a build volume temperature. Which printer profile are you using for this? Would you be able to share it with me? It will make it easier to reproduce the issue.
Also, which step of the PPA is it on?

**Comment by Ghostkeeper** [comment]
Yeah I could reproduce this (with the additional steps of installing the Printer Settings plug-in first and checking the "Has Build Volume Temperature Stabilization" setting then). It's not in the PPA.

It's probably related to the bug we found yesterday with the prime tower setting not working, and the reports from @smartavionics in a certain commit that I can't find back any more. This is a critical.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
