### ISSUE TITLE
I cannot drag a stl file into cura like on the non-beta versions. Could you please access this possibility?

### ISSUE THREAD

**Issue by R3DK** [Ultimaker/Cura#698]

**Comment by R3DK** [comment]
After closing and restarting Cura it works.

**Comment by fieldOfView** [comment]
Please add more information to issues like this, such as the platform you are using.

In this case, I am guessing you are using Windows. The installer is running in "elevated" mode so it can write to Program Files. If the installer then launches Cura, that is also elevated, and this screws with the rights to drop in files from the desktop. As you discovered the functionality works as intended if you launch Cura normally.

**Comment by R3DK** [comment]
Bedankt,  Aldo.

Groeten, René
Op 14 apr. 2016 12:34 schreef "Aldo Hoeben" <notifications@github.com>:
