### ISSUE TITLE
Separate extruder for skirt and brim

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6996]
**Is your feature request related to a problem? Please describe.**
While a skirt can use the same material as the piece to avoid waste of time or pricier soluble supports, brim can benefit of soluble materials so you don't have to post process it.
The extruder used is shared between skirt and brim.

**Describe the solution you'd like**
Use separate options for skirt and brim extruder material

**Describe alternatives you've considered**
Make the adhesion options all separate, so you can use skirt/brim and raft at the same time to purge and make the raft clean, and you can easily configure everything.
Using both skirt and brim can also be useful to avoid a ruined brim that instead of helping adhesion would be the cause of the print lifting (on abs, especially)

**Affected users and/or printers**
Multiple extrusion printers

**Comment by Ghostkeeper** [comment]
This would require allowing skirt, brim and raft to be printed in the same print in the first place, of course.

**Comment by TCPILOT** [comment]
Is this why I can't print a brim with my second extruder? It makes no sense to allow the selection of the second extruder if it will not print the brim.

**Comment by Ghostkeeper** [comment]
Currently Cura still allows you to print the brim with a second extruder. It just doesn't allow you to automatically switch the extruder based on whether "skirt" or "brim" is selected.

**Comment by GregValiant** [comment]
There currently are:
{skirt_brim_extruder_nr}
{adhesion_extruder_nr}
{raft_base_extruder_nr}
{raft_interface_extruder_nr}
{raft_surface_extruder_nr}
Is that sufficient?  Can we close this?
