### ISSUE TITLE
Circle geometry damaged in slicing process

### ISSUE THREAD

**Issue by crysxd** [Ultimaker/Cura#6998]
**Application version**
4.4.0

**Platform**
macOS 10.15.2

**Printer**
Ender 3  Pro

**Reproduction steps**
1. Open attached .3mf file
2. Click "Open" in "Open Project" dialog
3. Click "Slice"
4. Select "Preview"

**Screenshot(s)**
<img width="1648" alt="Screen Shot 2020-01-16 at 14 47 32" src="https://user-images.githubusercontent.com/5859228/72660358-fbde8f80-39cc-11ea-95fc-0cb02d7a0692.png">
<img width="1648" alt="Screen Shot 2020-01-16 at 14 47 29" src="https://user-images.githubusercontent.com/5859228/72660359-fe40e980-39cc-11ea-8cfb-0148caaf2527.png">

**Actual results**
3 holes are properly sliced keeping the circle geometry but one hole is damaged

**Expected results**
All 4 holes should be round

**Project file**
[Cura_Bug.3mf.zip](https://github.com/Ultimaker/Cura/files/4080113/Cura_Bug.3mf.zip)

**Comment by smartavionics** [comment]
The problem is the model is not valid. Install the Cura Mesh Tools from the Marketplace and then you can check yourself.

![Screenshot_2020-01-18_09-40-02](https://user-images.githubusercontent.com/585618/72661800-98f1f600-39d6-11ea-9678-18dd3975b3f8.png)

**Comment by crysxd** [comment]
Fair point! Maybe a simple check like this would be a good feature for a future version of Cura. 

Thanks for the quick feedback!
