### ISSUE TITLE
Save for all Profiles

### ISSUE THREAD

**Issue by fictivecreations** [Ultimaker/Cura#7022]
**Is your feature request related to a problem? Please describe.**
Currently in the UI it is not possible to save certain settings per printer or per filament, like initial line width, initial layer temperature, initial layer speed, etc that I might want to persist across all my more specific profiles.

**Describe the solution you'd like**
A right-click option (or button) of some kind to update a specific setting to the new value on all my profiles. 

**Describe alternatives you've considered**
I think I've read that you all would like to update the UI to allow for more specific profiles on printer and filaments which would also solve this problem but I know (as a ui developer, albeit a javascript one and not a python one or I'd probably consider helping make this) that that's likely a lot more work, and this would be a decent interim solution. 

The alternative that already exists is to just go through all my existing profiles and update them manually, but that becomes very confusing and time consuming very quickly.

**Affected users and/or printers**
Mostly users who only have one printer I think. Since if you've only got one printer, all the profiles should have the same base settings in certain cases and as you figure out better ones then you'd want to update all your profiles. If you've got multiple printers, then you'd only want to update a subset and then this wouldn't be as helpful.

**Comment by mahtDFR** [comment]
Thanks for the feature request. Unfortunately we've had to defer this, we don't have the development resources, and it would also add a lot of complexity to our current profile system.
