### ISSUE TITLE
Scaling Issue V2.1 open Beta

### ISSUE THREAD

**Issue by JohannesK91** [Ultimaker/Cura#703]
if you open a Model it says 100%...
http://www.bilder-upload.eu/show.php?file=97c1b0-1460966861.jpg 

if you rotate it that changes... i think this is a bit confusing 
http://www.bilder-upload.eu/show.php?file=185a71-1460966894.jpg

**Comment by nallath** [comment]
Yeah, I know. This was a last minute fix on my end. It was either this behaviour or something completely broken. 
I (obviously) chose the slightly confusing one of the broken one. I do hope to get a bit of rework done on this for the 2.2 release.
