### ISSUE TITLE
Slicer includes infill inside of holes in model

### ISSUE THREAD

**Issue by tkbletsc** [Ultimaker/Cura#7032]
**Application version**
4.4.1

**Platform**
Windows 10 x64

**Printer**
Prusa i3 Mk2S

**Reproduction steps**
1. Load model with my specific array of holes.
2. Slice using "Draft" defaults
3. Observe in preview that infill grid extends into the holes of the model where none should be.
4. (Optional) Print the model and get actual strings of infill in the holes.

**Screenshot(s)**
https://imgur.com/a/mFxUK7e
The first shows the model in prepare mode, the second shows the toolpath including the erroneous infill in the holes, the third zooms in on this infill, and the fourth is a photograph of the printed result.

**Actual results**
Infill is applied through the whole interior where the holes are, leading to plastic stringing through the holes when printed in real life.

**Expected results**
Infill should only be applied to the interior of the model, regardless of the number/size/shape of holes in the model. 

**Project file**
STL: https://dsss.be/f/dat/ScienceBot_01%20-%20Part%20-%20chassis.stl
3MF: https://dsss.be/f/dat/PI3MK2_ScienceBot_01%20-%20Part%20-%20chassis.3mf

**Log file**
I cleared the log file, ran Cura, and had it slice the model described above. Log:
https://dsss.be/f/dat/cura.log

**Additional information**
n/a

**Comment by smartavionics** [comment]
This bug has been fixed for the next Cura release. In the meantime, you can use one of my releases which also have this bug fixed. You can find them at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md file there for more information.
