### ISSUE TITLE
[4.4.1] Concentric pattern is not so concentric

### ISSUE THREAD

**Issue by LightTemplar** [Ultimaker/Cura#7040]
**Application version**
4.4.1

**Platform**
KDE Neon

**Printer**
Ender 5

**Reproduction steps**
1. loaded STL with a big round base.
2. Set "Bottom Pattern Initial Layer": Concentric
3. Sliced

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/453783/73323205-eed06480-4246-11ea-826f-99f29eacaa19.png)
 

**Actual results**
All lines on the first layer are crooked.

**Expected results**
All lines on the first layer are circular or spiral

**Project file**
https://we.tl/t-87WDQ7MgTN

**Comment by smartavionics** [comment]
I found that increasing the value of Maximum Resolution to 0.5 mostly fixed this issue. Not perfect but quite a bit better...

![Screenshot_2020-01-29_07-38-03](https://user-images.githubusercontent.com/585618/73336724-82675c80-426a-11ea-90cb-1d17ad68a9d3.png)

**Comment by smartavionics** [comment]
I think I have a fix for Cura. With this fix and your project unchanged, it now looks like this...

![Screenshot_2020-01-29_08-58-52](https://user-images.githubusercontent.com/585618/73342034-b6944a80-4275-11ea-8be3-1563c4753a52.png)
