### ISSUE TITLE
[4.4.1] Stringing and underextrusion when there are supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7042]
**Application version**
4.4.1

**Platform**
Win10x64

**Printer**
Cr10S

**Reproduction steps**
1. Use supports
2. Enable combing (I tried All and In-infill)
3. Printer with Estep, flow and Marlin's Linear Advance perfectly tuned (stringing is unexistant in all stringing tests)

**Screenshot(s)**

![ooze 1](https://user-images.githubusercontent.com/20385116/73408084-56e08280-42fb-11ea-9f97-9539a2b752c4.jpg)
![ooze 2](https://user-images.githubusercontent.com/20385116/73408085-56e08280-42fb-11ea-959a-b230c1410321.jpg)
![ooze 3](https://user-images.githubusercontent.com/20385116/73408086-57791900-42fb-11ea-8dcb-6ff5cf425a1d.jpg)

This screenshot is not the one of the file I printed but should be similar as I used same settings, maybe only different position.

![Ooze preview reconstruction](https://user-images.githubusercontent.com/20385116/73403713-542c6000-42f0-11ea-9033-acaae67e2d2a.png)

**Actual results**
As all is calibrated, a minimal material loss will make gaps in some other parts.
Supports are partially missing and print's perimeters are so thin that they don't touch because of the previously missed plastic.
All my prints fail if there is support.

**Expected results**
No filament (even solid parts like they were printed) hanging.

**Project file**

[ooze between supports profile.zip](https://github.com/Ultimaker/Cura/files/4131130/ooze.between.supports.profile.zip)

Gcode on request privately if needed

**Additional information**
I see both light blue and dark blue lines in the preview. I can't find which is which (retracted or un-retracted) in the legend, but there shouldn't be any un-retracted travel either way.
If the dark blue lines mean travel without retraction, how can they be disabled? I even disabled combing but they are still there.
Linear advance along with un-retracted movement is a big NO. I need to force retraction.

**Comment by Liger0** [comment]
Oh well, I totally forgot that setting, I'm sorry.
I set up combing All with 1mm of max distance, then 50 retractions within 3mm and it now doesn't show dark blue lines.
Would it be possible to show the light and dark blue lines in the legend? Because it doesn't show the difference.

**Comment by rburema** [comment]
> Oh well, I totally forgot that setting, I'm sorry.

We have a lot of settings, no need to be sorry :-)

> Would it be possible to show the light and dark blue lines in the legend? Because it doesn't show the difference.

I'll have a look/ask if we can spend some time on that.

Does it work for your actual print as well?

**Comment by Liger0** [comment]
I'll let you know when I have to print something like that again, thanks.

**Comment by Ghostkeeper** [comment]
A long time ago we had the idea to make the legend a bit more clear by drawing all applicable colours in the box. So the travel move would have two triangles in the legend colour box, one dark blue and one light blue. We never got around to it.

The original issue is found not to be a problem, so I'll close this issue then.
