### ISSUE TITLE
Layer Selector missing from 3.6 to 4.4.1

### ISSUE THREAD

**Issue by Stup1dTwitB0ts** [Ultimaker/Cura#7044]
**Application version**
4.4.1

**Platform**
Win 10 Pro Version 1903

**Printer**
Alfawise U20 ONE

**Reproduction steps**
1. Was running Cura v3.6 - was able to see layer sliders and layer selector in preview mode
2. Installed Cura 4.4.0 - lost the layer sliders and selector
3. Installed Cura 4.4.1 - still not there
4. Back leveled to Cura v4.3 then 4,2 then 4.1 and finally 3.6 - layer selector on available.

**Screenshot(s)**

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
To see the layer selectors so I can determine a layer at which to change the filament

**Project file**
N/A

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4132220/cura.log)

**Additional information**
none

**Comment by rburema** [comment]
The sliders have moved. If you go to the Preview stage, there should be the layer slider at the very right of the screen (past even the print settings), and one for the 'time within layer' in the middle at the very bottom of the screen.

**Comment by Stup1dTwitB0ts** [comment]
rburema, thanks for the reply.

I still don't see them. 

![image](https://user-images.githubusercontent.com/29710954/73595882-f7dd6200-44e2-11ea-8b62-97d5b11ff5d8.png)

**Comment by smartavionics** [comment]
Have you actually sliced the model? What happens when you click the slice button hiding under the settings?

**Comment by Stup1dTwitB0ts** [comment]
Well I'm a damned idiot.

Thank you @smartavionics!

**Comment by Ghostkeeper** [comment]
Added a warning to let you know next time.
