### ISSUE TITLE
[4.1.1] Interface layer support without the main support using tree supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7050]
**Application version**
4.4.1

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Load project
2. Tree supports
3. 0.8mm xy distance

**Screenshot(s)**
![support dots in air](https://user-images.githubusercontent.com/20385116/73555806-8a7ff180-444e-11ea-89ec-42f9e35b0f9d.png)

**Actual results**
The interface layer dot is printed in the air even though nothing stands beneath them.
If I decrease x-y distance to 0.3, the tree are generated and the dot (dark blue) is is separated by 1 layer from the last tree layer (light blue)

**Expected results**
Only print interface layer dots if a tree is generated

**Project file**
[Dots in air.zip](https://github.com/Ultimaker/Cura/files/4140414/Dots.in.air.zip)

**Comment by Liger0** [comment]
I am in general having issues with tree supports now because the latest layers are often miss even if the part is far from the model on x-y in the case that the part that gets supported is small.

I don't get why this happens, the fact that the model has a very little point as a overhang doesn't mean the support also does have to be that small, so small that the layers are not even generated.

**Comment by luxology** [comment]
Use Support Blocker cube (E) on this dots.

**Comment by Liger0** [comment]
Yeah but they are really a lot and it's a good waste of time.

**Comment by mahtDFR** [comment]
Thanks for the report. I reproduced it and it's on our backog - devs: CURA-7168

**Comment by nallath** [comment]
This has been fixed for 4.7

**Comment by Liger0** [comment]
Not solved. Recreated in #8477
