### ISSUE TITLE
[2.1.0] Disable draft shield does not fully disable

### ISSUE THREAD

**Issue by Ppyromann** [Ultimaker/Cura#706]
If 'enable draft shield' is unchecked, the draft shield is still printed if an absolute value has been entered in the 'Draft shield height' field.

I would expect this to behave the same way 'Enable support' works, if the box is unchecked, all values & fields are disabled.

**Comment by Ghostkeeper** [comment]
Hehe, yeah I suspect that "Enable Draft Shield" just sets the default height for the draft shield to 0.0. Bad design there. The engine needs to be explicitly checking for this value.

**Comment by BagelOrb** [comment]
still persists to my knowledge..

**Comment by Ghostkeeper** [comment]
No, doesn't reproduce. Seems to have been fixed.
