### ISSUE TITLE
[4.4.1] Unsupported points

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7060]
**Application version**
4.4.1

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Use supports on parts that start with little dots
2. Minimum support area: 0

**Screenshot(s)**

Watch on left side
![unsupported 2](https://user-images.githubusercontent.com/20385116/73687665-da6aec80-46ca-11ea-96f4-e359988f7d69.png)

Watch on right side
![unsupported 1](https://user-images.githubusercontent.com/20385116/73687666-da6aec80-46ca-11ea-9531-2ec510c3c098.png)

**Actual results**
No support

**Expected results**
Supported points

**Project file**
[unsupported.zip](https://github.com/Ultimaker/Cura/files/4150062/unsupported.zip)

**Comment by mahtDFR** [comment]
Thanks for the report. I could reproduce the results and it's a bug. Also tried enabling 'use towers' which gave some weird results. It's up for discussion.

**Comment by mahtDFR** [comment]
We will investigate. I've added this to our backlog - CURA-7167

**Comment by Block137** [comment]
Might not be related but by setting "Support Join Distance" to higher number, some support structure got removed. Worth looking into. If it's not related I'll make another bug report.

**Comment by mahtDFR** [comment]
We have decided not to prioritise this in our sprints.
For now, a workaround is to use Support Horizontal Expansion.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
