### ISSUE TITLE
Support flow

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#7065]
**Describe the solution you'd like**

Is there a reason that Support flow is shared between extruders?

**Comment by Liger0** [comment]
How could they be separate?
You can use an extruder for the perimeters/infill of the support and one for the interface layer, and use different flow on the feature

**Comment by fieldOfView** [comment]
Yes. The reason is the supports are internally all calculated into a single mesh, and a single mesh has only one flow.

**Comment by maukcc** [comment]
Thanks for the clarification

**Comment by fieldOfView** [comment]
Another way of thinking about your question is that supports are only printed with one of the extruders. The value isn’t actually shared between extruders, but the value from the extruder that prints (all) the supports is used.

**Comment by maukcc** [comment]
> the value from the extruder that prints (all) the supports is used.

this is actually not true, the lowest value is used

**Comment by fieldOfView** [comment]
It should take the value of the Support Infill Extruder, per here:
https://github.com/Ultimaker/Cura/blob/4.4/resources/definitions/fdmprinter.def.json#L2590
If it doesn't, that's a bug.

**Comment by maukcc** [comment]
It does as expected now
