### ISSUE TITLE
[4.4.1] Settings are very slow to update if a model is on the build plate

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7070]
**Application version**
4.4.1

**Platform**
Win10 x64, Ryzen 5 1600, RX Vega 56

**Printer**
Cr10S

**Reproduction steps**
1. Import a model of medium complexity
2. Open the settings panel

**Actual results**
The settings need a lot of seconds to update when clicking anything or open the dropdowns, easily over 10 seconds. 

**Expected results**
Model should not impact on the settings before slicing.

**Comment by nallath** [comment]
This should be fixed for the 4.5 beta. Previously, we would re-render the entire screen (including the 3d scene) when a setting was updated. This should no longer happen.
