### ISSUE TITLE
[4.4] source install fails at Qt step

### ISSUE THREAD

**Issue by iforgetware** [Ultimaker/Cura#7076]
**Application version**
4.4

**Platform**
Debian 10
**Printer**
Generic FFF - MTW Create

**Reproduction steps**
1. Followed instructions to install from source
2. make fails at - Performing configure step for 'Qt'

**Screenshot(s)**
[ 56%] Performing configure step for 'Qt'
+ cd qtbase
+ /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/configure -top-level -release -prefix /usr/local -archdatadir /usr/local/lib -datadir /usr/local/share -opensource -confirm-license -nomake examples -nomake tests -nomake tools -no-cups -no-sql-db2 -no-sql-ibase -no-sql-mysql -no-sql-oci -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-sql-tds -skip qtconnectivity -skip qtdoc -skip qtlocation -skip qtmultimedia -skip qtscript -skip qtsensors -skip qtwebchannel -skip qtwebengine -skip qtandroidextras -skip qtactiveqt -skip qttools -skip qtxmlpatterns -skip qt3d -skip qtcanvas3d -skip qtserialport -skip qtwayland -skip qtgamepad -skip qtscxml -rpath -pkg-config -opengl desktop -no-gtk -qt-xcb -fontconfig -system-freetype -system-zlib -ssl -openssl-runtime -I /usr/local/include -L /usr/local/lib
Creating qmake...
/opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:101:12: error: ‘int renameat2(int, const char*, int, const char*, unsigned int)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int renameat2(int oldfd, const char *oldpath, int newfd, const char *newpath, unsigned flags)
            ^~~~~~~~~
In file included from /usr/include/c++/8/cstdio:42,
                 from /usr/include/c++/8/ext/string_conversions.h:43,
                 from /usr/include/c++/8/bits/basic_string.h:6400,
                 from /usr/include/c++/8/string:52,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/../../src/corelib/tools/qbytearray.h:52,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/qbytearray.h:1,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/../../src/corelib/tools/qstring.h:49,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/qstring.h:1,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/../../src/corelib/io/qiodevice.h:50,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/qiodevice.h:1,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/../../src/corelib/io/qfiledevice.h:43,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/include/QtCore/qfiledevice.h:1,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfile.h:44,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_p.h:54,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:43:
/usr/include/stdio.h:164:12: note: previous declaration of ‘int renameat2(int, const char*, int, const char*, unsigned int)’
 extern int renameat2 (int __oldfd, const char *__old, int __newfd,
            ^~~~~~~~~
In file included from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:106:
/usr/include/linux/stat.h:56:8: error: redefinition of ‘struct statx_timestamp’
 struct statx_timestamp {
        ^~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/mkspecs/linux-g++/qplatformdefs.h:75,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:42:
/usr/include/x86_64-linux-gnu/bits/statx.h:25:8: note: previous definition of ‘struct statx_timestamp’
 struct statx_timestamp
        ^~~~~~~~~~~~~~~
In file included from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:106:
/usr/include/linux/stat.h:99:8: error: redefinition of ‘struct statx’
 struct statx {
        ^~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/mkspecs/linux-g++/qplatformdefs.h:75,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:42:
/usr/include/x86_64-linux-gnu/bits/statx.h:36:8: note: previous definition of ‘struct statx’
 struct statx
        ^~~~~
/opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:107:12: error: ‘int statx(int, const char*, int, unsigned int, statx*)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static int statx(int dirfd, const char *pathname, int flag, unsigned mask, struct statx *statxbuf)
            ^~~~~
In file included from /usr/include/x86_64-linux-gnu/sys/stat.h:446,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/mkspecs/linux-g++/qplatformdefs.h:75,
                 from /opt/cura/cura-build-environment/build/Qt-prefix/src/Qt/qtbase/src/corelib/io/qfilesystemengine_unix.cpp:42:
/usr/include/x86_64-linux-gnu/bits/statx.h:87:5: note: previous declaration of ‘int statx(int, const char*, int, unsigned int, statx*)’
 int statx (int __dirfd, const char *__restrict __path, int __flags,
     ^~~~~
make[3]: *** [Makefile:429: qfilesystemengine_unix.o] Error 1
make[2]: *** [CMakeFiles/Qt.dir/build.make:109: Qt-prefix/src/Qt-stamp/Qt-configure] Error 2
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/Qt.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Actual results**
Doesn't create make install

**Expected results**
Does create make install

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
Trying to see if running from source will improve speed of UI over the downloaded AppImage or if I can identify the problem and fix it.

My main issue is that switching extruder tabs takes multiple seconds.
This is a problem when checking that both extruders have the same settings.  I may be using the profile incorrectly, but I don't see a way to get the same settings in E2 as E1 without entering them maually and swithcing back and forth to check that they are all the same.

As far as source install goes...
First time using cmake ( I may be the weak link here )
Chose Unix Makefiles / native compilers
After "Configure" the following values are listed in red...
CMAKE_BUILD_TYPE ( no value )
CMAKE_INSTALL_PREFIX /usr/local

**Comment by Ghostkeeper** [comment]
This seems to be a bug in Qt. See also here: https://github.com/meta-qt5/meta-qt5/issues/94

The Qt bug has been fixed in a later release, but since we're still using Qt 5.10 it's not been fixed yet for us. You can try applying the patch that they suggest there (though it's a patch for a newer version, so you might have to resolve the merge conflict manually then).

Maybe it's easier to just install Qt via `python3 -m pip install pyqt5` and leave the build environment out, for your case. You won't produce the entire build from source like us, but it's much easier.
