### ISSUE TITLE
Trying to print something, and can't seem to change support pattern. 

### ISSUE THREAD

**Issue by CptanPanic** [Ultimaker/Cura#7077]
**Application version**
4.4.1

**Platform**
Win64

**Printer**
Ender 3

**Reproduction steps**
1. Added support
1. Changed support pattern to cocentric, view changes.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/4087170/74090259-3345d680-4a77-11ea-90e5-27f851530804.png)

**Actual results**
Support pattern doesn't seem to have any affect.

**Expected results**
Should see something like zig-zag or cocentric.

**Comment by valeria-gomez** [comment]
Is it the Support Interface Pattern that you want to change? The baby blues in the middle look like the SIPs. The regular support has cyan color. 

![image](https://user-images.githubusercontent.com/60856983/74109732-3b406c00-4b86-11ea-92a7-b694f1deed2e.png)

**Comment by rburema** [comment]
Closing this as @valeria-gomez is right. If you still experience (related) problems, feel free to reopen. (Glad we made the difference between normal and SIP more clear a few versions ago...)
