### ISSUE TITLE
[4.4.1] Selecting Settings in Mesh Type dialog changes mesh type back to Normal Model 

### ISSUE THREAD

**Issue by pfjason** [Ultimaker/Cura#7082]
**Application version**
4.4.x

**Platform**
Ubuntu 19.10

**Printer**
Any

**Reproduction steps**
1. Add a model to the build plate
2. Add a support blocker block to the model and select it
3. Change the mesh type to "Modify Settings for Overlaps"
4. Click "Select Settings" and select any setting.
5. Notice that the Mesh Type is now "Normal model"

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/16055757/74195042-6ed3d280-4c28-11ea-966b-99c4c3037fcd.png)

![image](https://user-images.githubusercontent.com/16055757/74195057-74c9b380-4c28-11ea-86fa-e0bdea368ffe.png)

![image](https://user-images.githubusercontent.com/16055757/74195067-7bf0c180-4c28-11ea-8779-4a804e64afcf.png)

**Actual results**
Mesh Type for the support blocker / Settings Modifier block is now "Normal Model" and slicing the model will now produce a cube in that spot. 

**Expected results**
Mesh Type should not be changed

**Comment by valeria-gomez** [comment]
This is a bug in 4.4.1. 

I'm literally checking out Cura 4.5 at this moment.  It looks like it was fixed in the recent 4.5. Huurah!

https://github.com/Ultimaker/Cura/releases/tag/v4.5-beta

**Comment by Ghostkeeper** [comment]
Yup, we found this too and fixed it. Thanks for the report nonetheless!
