### ISSUE TITLE
Can't display model at Preview mode

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#7083]
**Application version**
Cura 4.4.1, 4.3.0, Master

**Platform**
Windows 10 1909, Intel HD Graphics 630

**Printer**
Custom FFF, HMS434

**Reproduction steps**
1. Install Cura
2. Chose Custom FFF or HMS434
3. Setting 8 for Number of Extruders (X : 300, Y : 300, Z : 300)
4. Load Model
5. Multiply model to 1
6. Assign 2nd model to Extruder 8
7. Slice
8. Change to Preview mode

**Screenshot(s)**
![Cura Master](https://user-images.githubusercontent.com/39176348/74202498-f1ec3b80-4caf-11ea-8f47-3857bfd106a6.png)

**Actual results**
The second model I assigned to extruder 8 is not displayed. 

**Expected results**
I want show all model at Preview mode.

**Project file**
[CFFFP_cylinder.zip](https://github.com/Ultimaker/Cura/files/4183708/CFFFP_cylinder.zip)

**Log file**
[cura.zip](https://github.com/Ultimaker/Cura/files/4183706/cura.zip)

**Additional information**
On some PCs the above problem appears. On other PCs, there is other problems at preview mode.
1. Setting 8 to Number of Extruders
2. Load Model and Multiply 7
3. Assign each 8 extruder to 8 models
4. Slice
5. Change Preview mode
6. Uncheck Extruder 1 or 4 at Color scheme
7. Disappear Model 1(or 4) and Model 5, 6, 7, 8 at the same time.

**Comment by rburema** [comment]
Confirmed, even just setting a single model to 8 will do it (in my case at least), no need for the other reproduction steps. Looks like an 'off by one' bug in a comparison somewhere.

**Comment by Ghostkeeper** [comment]
I remember this being brought up with the team, but what was our conclusion? We try this as a small fix?

**Comment by rburema** [comment]
Yes, we'll try to timebox it. I've already spent some time of the timebox, but it wasn't immediately obvious.

**Comment by joonghochoe** [comment]
Any good news about this bug? This bug still seems to remain in version 4.6.

Some desktop PC(Windows 10 Pro 64-bit (10.0, Build 18363), Intel(R) HD Graphics 630)
1. Solid View is OK
![주석 2020-04-29 162753](https://user-images.githubusercontent.com/39176348/80863754-5e784480-8cb9-11ea-82d9-86b48d0c5946.png)

2. Layer View, Simulation View is not OK, Only at 8th model
![주석 2020-04-29 162751](https://user-images.githubusercontent.com/39176348/80863800-8a93c580-8cb9-11ea-875f-870cf817d6a3.png)
![주석 2020-04-29 162752](https://user-images.githubusercontent.com/39176348/80863803-941d2d80-8cb9-11ea-8053-71052fe752fe.png)

Another desktop PC(Windows 10 Pro 64-bit (10.0, Build 18363), Intel(R) HD Graphics 4600)
1. Extruder 1 is checked at Layer View
![주석 2020-04-30 232443](https://user-images.githubusercontent.com/39176348/80863854-e3fbf480-8cb9-11ea-94b3-69feb95fc295.png)

2. Uncheck only extruder 1
![주석 2020-04-30 232444](https://user-images.githubusercontent.com/39176348/80863856-e8c0a880-8cb9-11ea-8690-58dc1ce33317.png)

**Comment by rburema** [comment]
I _think_ I fixed this with these PR's:
 https://github.com/Ultimaker/Uranium/pull/606
and
 https://github.com/Ultimaker/Cura/pull/7693

_If_ so, it'll probably be fixed in 4.7

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
