### ISSUE TITLE
Gentoo Package

### ISSUE THREAD

**Issue by tomboy-64** [Ultimaker/Cura#709]
I'm currently working on packaging Cura for Gentoo. The relevant pull request can be found [here](https://github.com/gentoo/gentoo/pull/1298). For input I'm always grateful.

For you, in particular the patches I'm applying might be of interest; they enable setting python's sitedir through a flag passed to cmake.

With kind regards,
tomboy64

**Comment by BagelOrb** [comment]
outdated
