### ISSUE TITLE
[4.5 beta] no start or ending gcode field at the first start

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7094]
**Application version**
4.5 beta

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Install cura
2. Select cr10s printer

**Screenshot(s)**
![no gcode at first start](https://user-images.githubusercontent.com/20385116/74360811-0884b680-4dc6-11ea-994b-4d5a13f076a1.png)

**Actual results**
No space or way to make gcode visible

**Expected results**
Space and bars to make gcode visible and the areas bigger

**Comment by Vandrasc** [comment]
Hi @Liger0 , did you tried to maximize the window by dragging it? 
For me, the windows do show for both start and end gcode but the space is very small.

**Comment by mahtDFR** [comment]
Thanks for the report. I couldn't reproduce this in Windows 10 x64
![Add Printer 2020-02-13 13 04 56](https://user-images.githubusercontent.com/17821912/74433924-a8dbe900-4e61-11ea-8628-18ff5b17d1b6.jpg)

Any details about your screen resolution?

I also noticed when resizing the window and scaling it down again it produced some weird behaviour so I'll look into that.
![Add Printer 2020-02-13 13 05 27](https://user-images.githubusercontent.com/17821912/74434549-f2790380-4e62-11ea-98f2-bf4b0d43f752.jpg)

**Comment by mahtDFR** [comment]
![image](https://user-images.githubusercontent.com/17821912/74440276-ffe7bb00-4e6d-11ea-9995-c0be0ed0e471.png)
@Liger0 What's your display scaling setting? Just tried it on 150% and it creates similar issues. I'll put it up for discussion on how to handle scaling above 100%

**Comment by Liger0** [comment]
I use 125%. I tried to increase the screen or use full screen but no difference.

**Comment by mahtDFR** [comment]
Thanks for the report. We discussed briefly and decided to defer this for now. We recognise it's a bug, but don't have the resources to cover it at this time.

**Comment by Aardvarx55** [comment]
I have just installed a BLTouch to my Ender-3 Pro, but when I go to add the required G-code, the displayed areas for this are too small (Mac)
![Screen Shot 2020-03-22 at 23 06 57](https://user-images.githubusercontent.com/42945630/77264368-1addf400-6c92-11ea-8e36-4267f17f83bb.png)

**Comment by Liger0** [comment]
Reopen?

**Comment by Ghostkeeper** [comment]
Indeed this is still a problem. For our planning we're waiting with a solution until we've removed the system theming from this dialogue.
