### ISSUE TITLE
change direction of z-axis when importing an STL file

### ISSUE THREAD

**Issue by Bas-van-Deursen** [Ultimaker/Cura#71]
Some CAD programs (for example Solidworks) have a different direction for the z-axis. When importing an STL file into Cura, the model is displayed in a different orientation than in the CAD program in which it was created. It would be a nice feature if Cura would recognize this and would do a translation on the model.

**Comment by nallath** [comment]
I wouldn't know of a way to find out what axis frame a model is supposed to have (and compensate for that), save for checking header files and compensating on a program by program basis.

**Comment by Bas-van-Deursen** [comment]
Does the STL file not contain information about from which software package it was exported?

-Bas

> On 25 jun. 2015, at 11:34, Jaime van Kessel <notifications@github.com> wrote:
> 
> I wouldn't know of a way to find out what axis frame a model is supposed to have (and compensate for that), save for checking header files and compensating on a program by program basis.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


IMAGINE IT >> MAKE IT

Meet us online at Twitter <http://twitter.com/ultimaker>, Facebook 
<http://facebook.com/ultimaker>, Google+ <http://google.com/+Ultimaker>

www.ultimaker.com

**Comment by awhiemstra** [comment]
Yes, that is what @nallath means with "checking header files" I think.

What I suggested when discussing this with @Bas-van-Deursen was to have an option to indicate what Axes to use for loading files, with the defaults of that set based on the STL header.

**Comment by Bas-van-Deursen** [comment]
That would be nice!

However very low priority I think.

-Bas

> On 25 jun. 2015, at 11:58, awhiemstra <notifications@github.com> wrote:
> 
> Yes, that is what @nallath means with "checking header files" I think.
> 
> What I suggested when discussing this with @Bas-van-Deursen was to have an option to indicate what Axes to use for loading files, with the defaults of that set based on the STL header.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


IMAGINE IT >> MAKE IT

Meet us online at Twitter <http://twitter.com/ultimaker>, Facebook 
<http://facebook.com/ultimaker>, Google+ <http://google.com/+Ultimaker>

www.ultimaker.com

**Comment by BagelOrb** [comment]
For now people can just rotate the object.

**Comment by Bas-van-Deursen** [comment]
Ofcourse, that's why it's low priority

-Bas

> On 29 jun. 2015, at 16:42, Tim Kuipers <notifications@github.com> wrote:
> 
> For now people can just rotate the object.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


IMAGINE IT >> MAKE IT

Meet us online at Twitter <http://twitter.com/ultimaker>, Facebook 
<http://facebook.com/ultimaker>, Google+ <http://google.com/+Ultimaker>

www.ultimaker.com

**Comment by BagelOrb** [comment]
I think this is fixed for 3MF. For STL it would be nice to have a preference for this.

**Comment by Ghostkeeper** [comment]
Our project manager just removed this from our planning for being older than 12 weeks.

**Comment by ianpaschal** [comment]
Labelling as `Won't Fix` as it's very old and very low priority: not really an "issue."

**Comment by ianpaschal** [comment]
@Ghostkeeper Why did you re-open this? We have so many features and bugs to work on, I think we are lying to ourselves saying we'll get to it eventually. Gotta say "no" sometimes.

**Comment by ianpaschal** [comment]
As part of our new ticket handling strategy, we voted as a team on the likelihood of fixing this issue. Unfortunately, we’ve decided that we will not take time to fix it, and are marking it as `Status: Won’t Fix/Do` and closing the issue.
