### ISSUE TITLE
interface problem (Сura 4.0 - 4.5)

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#7107]
Hello. there is one small problem that is present in all versions of the program

in order to fit as many options as possible in the window, I use a custom theme

but the problem is that not all configuration cells look the same,
can this bug be fixed?
![image](https://user-images.githubusercontent.com/44455128/74600450-a980b380-50dd-11ea-8d6c-603ccd103e91.png)
![image](https://user-images.githubusercontent.com/44455128/74600463-daf97f00-50dd-11ea-992c-4974b6e6b721.png)

**Comment by Ghostkeeper** [comment]
Seems to be something with the `NumericTextFieldWithUnit.qml` file we wrote. It's using a `TextField` element which has the default of `verticalAlignment: TextInput.AlignVCenter` which is supposed to align the text vertically. However it doesn't do this properly; clearly the text is aligned too high. Problem is though that this QML element doesn't allow customising the label in any way other than with its own fields (like `verticalAlignment`).

We just have an extra label for the unit in there that is put inside the TextField by ourselves and aligned with its centre. The label for the unit is working properly.

I couldn't find a quick solution for this. We have seen similar things before where users reported that the text was hard to read in some pixel scales.

**Comment by smartavionics** [comment]
The same problem occurs even if you don't use a custom theme. This is what I see on Linux.

![Screenshot_2020-02-25_10-02-24](https://user-images.githubusercontent.com/585618/75236689-0d7a3a80-57b6-11ea-8c0e-a68291f864e6.png)

**Comment by Goodfeat** [comment]
There is a temporary solution that I have to use
its essence is that you need to add a value to an existing variable in the NumericTextFieldWithUnit.qml file

I just open the file NumericTextFieldWithUnit.qml
and add to the string another value to the string
![image](https://user-images.githubusercontent.com/44455128/75240015-675b1e80-580f-11ea-8ac5-21ca20690e5a.png)

this way I have to correct the code for my style every time a new version of the program comes out
