### ISSUE TITLE
[Cura 4.5 beta] unsupported dual extrusion prime tower

### ISSUE THREAD

**Issue by pawien** [Ultimaker/Cura#7113]
With a 2-color print, the 2nd color starts printing in the air at the tower.
![Screenshot (56)](https://user-images.githubusercontent.com/45520404/74610313-73016380-50f2-11ea-9f70-fee0a3f84f51.jpg)
[GA_test1.zip](https://github.com/Ultimaker/Cura/files/4216147/GA_test1.zip)

**Comment by mahtDFR** [comment]
Thanks for the report. Can you attach a .3mf file that reproduces the problem?

* In Cura, click File > Save...
* Zip the 3mf
* Attach it here

Then we can test it

**Comment by mahtDFR** [comment]
Thanks for the report. Can you attach a .3mf file that reproduces the problem? (In Cura go to File > Save...) then .zip it and attach it here.
Thanks for the report. Can you attach a .3mf file that reproduces the problem?

* In Cura, click File > Save...
* Zip the 3mf
* Attach it here

Please include a [log file](https://github.com/Ultimaker/Cura#loggingissues) if you haven't already.

**Comment by pawien** [comment]
[GA_test1.zip](https://github.com/Ultimaker/Cura/files/4216143/GA_test1.zip)

**Comment by pawien** [comment]
[GA_test1.zip](https://github.com/Ultimaker/Cura/files/4216149/GA_test1.zip)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/6909
