### ISSUE TITLE
[4.5 beta] Rendering issue and crash

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7115]
**Application version**
4.5 beta

**Platform**
Win10 x64

**Printer**
CR 10S

**Reproduction steps**
1. My profile selected
2. Enabled adaptive layers, disabled supports
3. Sliced

**Screenshot(s)**
https://www.youtube.com/watch?v=F7W39th0890

**Actual results**
Rendering issues, crash

**Expected results**
No rendering issue, no later crash

**Log file**
[cura.zip](https://github.com/Ultimaker/Cura/files/4210883/cura.zip)

**Comment by Liger0** [comment]
It has happened again. I have saved the project just in case, though I doubt it could be of any use. 
If it is, please tell me who to send it privately.

**Comment by fieldOfView** [comment]
If you slice the same model/ settings again, does the issue reappear?

**Comment by mahtDFR** [comment]
@Liger0 Email sent to you. Can you reply to it with an attached 3mf?

**Comment by Liger0** [comment]
It doesn't seems to appear everytime I slice.
Project sent.

**Comment by mahtDFR** [comment]
Hi @Liger0, thanks for the 3mf. I couldn't reproduce the issue as you described it in Win10 x64,  and it seems there's some extra parts of the model missing in the file you provided.

This is what I have:
![image](https://user-images.githubusercontent.com/17821912/74821381-ca2a5280-5303-11ea-8ed6-416728b5631b.png)

We suspect the issue might be down to your graphics card. Is there another PC you can test it on with similar specs?

Maybe you can send another 3mf with the complete model as well? You can send it to the same address as before.

**Comment by fieldOfView** [comment]
Didn’t @smartavionics see the same glitch after @nallath comitted some optimisations to layer view pre-beta?

**Comment by Liger0** [comment]
The project I sent is the second one I posted the image of.

**Comment by smartavionics** [comment]
Yes, I do sometimes see a glitch that has only started appearing recently but it looks different...

![Screenshot_2020-01-05_10-53-50](https://user-images.githubusercontent.com/585618/74831930-23977f00-530e-11ea-8a78-6d7218d42a52.png)

**Comment by smartavionics** [comment]
Actually, I haven't seen it for a couple of weeks so perhaps they have fixed it.

**Comment by Liger0** [comment]
May the defective layer where the rendering line goes to be the one that's referred  in the log?

`2020-02-16 21:29:25,444 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [101]: [Backend] [WARNING] Layer 453 is empty (or it has empty extruder plans). Temperature control and cross layer travel moves might suffer!`

**Comment by nallath** [comment]
> May the defective layer where the rendering line goes to be the one that's referred in the log?
> 
> `2020-02-16 21:29:25,444 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [101]: [Backend] [WARNING] Layer 453 is empty (or it has empty extruder plans). Temperature control and cross layer travel moves might suffer!`

I don't think so. In that case, a project would have issues regardless of the machine it ran on.
