### ISSUE TITLE
Skirt Issue: Skirt printing under models

### ISSUE THREAD

**Issue by pmcsr** [Ultimaker/Cura#7120]
**Application version**
4.5 beta (but was doing the same thing with the previous version)

**Platform**
windows 10

**Printer**
Prusa MK3s

**Reproduction steps**
1. Reloaded models
2. rearranged models and re-sliced

**Screenshot(s)**
![skirt issue](https://user-images.githubusercontent.com/61135048/74628028-82000a00-5122-11ea-9590-ab5dc960deac.png)

**Comment by Ghostkeeper** [comment]
Do you have a project file that reproduces this issue? It doesn't happen with any model, I suppose.

**Comment by bergie5737** [comment]
Hi. I have just got the same problem. I cleared build plate. Imported a model. Multiplied it and saw skirt under the parts.
![Skirt bug](https://user-images.githubusercontent.com/10572409/74792743-d9aa9b00-5305-11ea-93e7-959deef6c43d.jpg)

I printed the exact same footprint several times today with small tweaks to the height, and they printed with no problem. 
Restarting solved it for me.

**Comment by smartavionics** [comment]
This will occur if the bottom of the model is not completely flat or the model is not aligned with the build plate. In such cases, a quick fix is to drop the model down by just enough so that all of the base is touching the build plate.

**Comment by bergie5737** [comment]
Mmmm. I never checked that it was not flat so cannot rule it out with
absolute certainty.  I cleared the build plate and imported again and even
pulled a larger version in.  It's unlikely that I made the same mistake
again by not laying it flat. As soon as I restarted Cura again, I was able
to lay my model flat again...😁

I will check if this is the case next time I use Cura. On skirts, I had an
issue (that I did not report as I suspect I set something wrong,) where a
skirt near the edge of the build plate refused the model to be sliced -
which I understand if it goes out of bound. The skirt was under an overhang
that was wider than the skirt. Just removing the skirt, and the model
sliced. I thought at the time that the skirt gets put down wider than the
overhang even though the model itself fitted the build plate. The actual
contact area on the built plate was about 20mm inside the overhang.

**Comment by bergie5737** [comment]
In the hope it helps by adding adding more...
I have deliberately not laid the model perfectly flat, then the skirt became a problem as stated.  (And I know that) I use "snap rotation" which for me is 15 deg at the minimum, and at 15 deg it is pretty obviously not laying flat. 

The other issue I describe where the skirt causes failure to slice, I can reproduce. I am attaching a screenshot. As you can see the shadow shows a much wider build area than the skirt. I can put one skirt line down, as soon as I add more, it shows my model is too big for the build plate.  The brim behave as expected up to where it eventually run out of real space.
Feel free to move or request me to log a separate issue for this behaviour.
![Skirt bug2](https://user-images.githubusercontent.com/10572409/74885216-8b0c0800-53bc-11ea-99ec-83675bccf871.jpg)

**Comment by Ghostkeeper** [comment]
That area is also affected by:
* Horizontal Offset
* Horizontal Offset Initial Layer
* Mold Width

And in one-at-a-time mode:
* Everything related to the bed adhesion
* Travel Avoid Distance
* The print head shape

**Comment by Dragon12764** [comment]
I had to turn skirt off as it was making the skirt a completely different shape with part of it under the model.
![2020-02-28](https://user-images.githubusercontent.com/53074501/75602424-dc319100-5a79-11ea-9dff-b1a64c61aa9f.png)

**Comment by Ghostkeeper** [comment]
For you also then: Do you have a project file that reproduces the issue?

**Comment by Dragon12764** [comment]
No it was the model not the software, sorry.

**Comment by fleutot** [comment]
Did you use "Select face to align to the build plate"? This [issue](https://github.com/Ultimaker/Cura/issues/7839) might be related.
