### ISSUE TITLE
[4.5.0 beta] Initial Layer Bed Temperature fooled by comments

### ISSUE THREAD

**Issue by jmelquist** [Ultimaker/Cura#7124]
**Application version**
v4.5.0 beta

**Platform**
Windows

**Printer**
Ender 3 Pro

**Reproduction steps**
In Machine Settings -> "Start G-Code", I have an M140 / M190 defined which over-rides Cura's temperature settings (that's fine/expected behavior).  However, when I comment out these lines (with a ";" char) Cura still doesn't not insert it's own bed-temp settings - specifically the "Initial Layer Bed Temp".  

**Screenshot(s)**
n/a

**Actual results**
When I remove the commented M140 / M190 lines, then Cura correctly inserts the bed temperature settings, including the initial layer temp and the non-initial layer temps.

**Expected results**
I'm assuming there is a substring search of [the user-defined start/end gcode] for M140/M190 and if found, it doesn't insert this command (since the user is overriding it) but Cura needs to ignore comments when this search is done (1. clean comments from gcode, 2. substring search).  ?possibly this is a larger problem with other settings?

**Project file**
N/A

**Log file**
N/A

**Additional information**
N/A

**Comment by Ghostkeeper** [comment]
In fact it's searching for the string `{material_bed_temperature}`, `{default_material_bed_temperature}` or `{material_bed_temperature_layer_0}`. Not for `M140` or `M190`. In my opinion it should search for those M-codes instead, really. That would be more reliable if people are not letting it be filled in automatically by the setting values but hard-code their temperatures.

I think though that parsing through comments is perhaps acceptable since it offers a workaround if for some reason you don't want it to emit a heating command at all?

**Comment by jmelquist** [comment]
Noted that **{*}** is the search condition, not the **M**code.  I casually agree with you on the codes being probably a better strategy over-all.

As for include/exclude comments during search:  I think it's non-intuitive to the user that general commented code would have an impact on Cura's behavior.  However, if you do ignore general Gcode comments, then the team might consider implementing a "Cura Directive" syntax... something like:
     **;#CURA#KEYWORD=VALUE(S)#**
For Instance, **;#CURA#OBJECTS_WITH_BRIM=1,2,5\r\n**  would...
 - be ignored by the printer (thanks to the semi-colon prefix)
 - be obvious to the user that it has a specific meaning to Cura
 - indicate to Cura that objects 1, 2 and 5 should be printed with a brim (but objects 3 and 4 should not be printed with a brim... a feature that 99% of users don't need)
This functionality could be used in many ways...
 - advanced users looking to override default cura behavior
 - allow beta features to be easily/quickly tested by the community w/o having to wrap UI around it.
 - when 99% of users don't need a feature, but 1% do have a valid need

Regardless, I appreciate the response and the consideration of the UserDirective idea.  thanks for a great product!  cheers!
-jas

**Comment by nallath** [comment]
I've added a bit of code that ignores comments when checking if the heating commands need to be inserted. It's too late for the 4.5 release, but it will be in the 4.6 release.

**Comment by fieldOfView** [comment]
This change will break configurations where people are counting on the previous behavior.

**Comment by Ghostkeeper** [comment]
> This change will break configurations where people are counting on the previous behavior.

That's basically what I said before here as well, yeah:

> I think though that parsing through comments is perhaps acceptable since it offers a workaround if for some reason you don't want it to emit a heating command at all?

However there is an argument to be made that this was then depending on a bug for its implementation. And the use case is very small.

**Comment by fieldOfView** [comment]
So, what's the new official workaround for this case:
> it offers a workaround if for some reason you don't want it to emit a heating command at all

![relevant xkcd](https://imgs.xkcd.com/comics/workflow.png)

**Comment by jmelquist** [comment]
+1 for the "Cura Directive" feature to prevent loss of functionality... oh wait, that my suggestion so I probably can't "+1" it...  +1 all the same :)

**Comment by Ghostkeeper** [comment]
You can workaround this you can add a `M117 {material_bed_temperature}` or `G88 {material_bed_temperature}`? It'll depend a bit on the printer firmware.
