### ISSUE TITLE
[OS X] Cura hangs when hitting Cmd-Q (Quit)

### ISSUE THREAD

**Issue by nilrog** [Ultimaker/Cura#713]
I was playing with a model in Cura 2.1 open beta on OS X (10.11.4) and then I hit Cmd-Q to quit. But Cura never quit...it just sits there open with the beachball spinning.

Cura's log file ends with this:

```
2016-04-20 21:27:01,431 - DEBUG - Shutting down cure
2016-04-20 21:27:01,437 - ERROR - Exception while emitting shutdown signal: NotImplementedError('Stop should be implemented by subclasses',)
```

But that doesn't seem to be related because if Cura exits normally it logs the same thing.

The only way to end it was to force quit Cura.

The fault is reproducible...but you need to hit Cmd-Q at the right time. If I do it when the slicing progress is at ~10% it hangs everytime. If I let it slice a bit longer it quits as it should.

**Comment by Ghostkeeper** [comment]
Thanks for reporting. We found this one too recently.

This was fixed yesterday but no build has been published to the public yet and I think it needs to be backported to 2.1 as well. You can expect it to close properly soon!
