### ISSUE TITLE
Ender 3 Pro Support Material Contact

### ISSUE THREAD

**Issue by SynthwaveFox** [Ultimaker/Cura#7130]
**Application version**
4.4.1

**Platform**
macOS 10.14.6 (Mojave)

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Put a file on the bed
2. Enable supports (any type)
3. Start printing.

**Actual results**
When done with a layer, the printer will travel to start the next layer, but the nozzle doesn't seem to move up before doing that, so it hits every piece of support that it printed.
**Expected results**
The printer should print normally without making contact with the supports.

**Additional information**
The printer nozzle hits the support material when moving to the start of a new layer.

If you need a video, I might be able to provide one in a few days if requested.

**Comment by rburema** [comment]
Can you attach the saved project? (Save, not export -- you'll have to zip it to get github to accept it.)

**Comment by bobster22388** [comment]
I have noticed this same issue. I will try find the project I had that did it last. I even tried changing the avoid height to something higher like 2mm, but still had the issue. Thankfully didn't affect the supports, but always worried the nozzle was going to knock them over.

**Comment by bobster22388** [comment]
[CE3_frame.zip](https://github.com/Ultimaker/Cura/files/4270060/CE3_frame.zip)

**Comment by Ghostkeeper** [comment]
If you want the nozzle to move up (over) the previously printed parts, you need to enable [Z Hops](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/travel/retraction_hop_enabled.md). For your profile that is by default disabled, it looks like.
