### ISSUE TITLE
[4.4.1] Slicer creating additional structures and filling hole

### ISSUE THREAD

**Issue by hobiseven** [Ultimaker/Cura#7134]
Hi.
I try to print this extruder bracket for my Alfawise U30, and the slicer creates weird additional structures under the location of the extruder motor, and also fills the filament hole ( 2mm long horizontal hole) half way.

[Filament_detector_support_slicing problems.zip](https://github.com/Ultimaker/Cura/files/4223807/Filament_detector_support_slicing.problems.zip)

None of the settings I could change made any effect. 
When rotating the part to be vertical ( filament hole is then aligned with Z axis) , the slicing is then OK, but why would you print suc a part oriented like that?  

I attach the STL, as well as the pictures of the 2 problems. 1 - the filament long 2mm hole is being filled by the slicer at multiple locations. 2 - the weird 45 degrees additional structure created by the slicer where the surface should be totally flat.

Can any of you help? 
Thank you.

**Comment by smartavionics** [comment]
Meshtools says the model has problems....

![Screenshot_2020-02-19_08-20-05](https://user-images.githubusercontent.com/585618/74815184-b0334480-52f0-11ea-90fa-ef24427d7eca.png)

**Comment by hobiseven** [comment]
Thank you for the fast answer! Ok, then I guess the model is not well prepared. 
I will do my own! 

BTW, your PB4 works really well. Greetings from France!

**Comment by smartavionics** [comment]
> BTW, your PB4 works really well. Greetings from France!

Ah good, glad to hear it. Do you know Mike Goodrich? He is a good friend and expert gyro balancer who lives near Le Havre. (He knows nothing about 3d printing!)

**Comment by smartavionics** [comment]
When I sliced your model it didn't show the same problems as your images show. So I think that maybe with some tweaks to the profile settings you can get a decent print. Please zip or rename the .3mf project file and attach to this issue. Thanks.

**Comment by smartavionics** [comment]
![Screenshot_2020-02-19_09-03-24](https://user-images.githubusercontent.com/585618/74818509-b4faf700-52f6-11ea-9961-bc4d94a8802c.png)
![Screenshot_2020-02-19_09-03-12](https://user-images.githubusercontent.com/585618/74818518-b75d5100-52f6-11ea-813f-055b8f3448ed.png)

**Comment by smartavionics** [comment]
Setting the horizontal expansion to 0.05 gets rid of that weird slot...

![Screenshot_2020-02-19_09-08-24](https://user-images.githubusercontent.com/585618/74818939-744fad80-52f7-11ea-8510-ddbff6f303a1.png)

**Comment by hobiseven** [comment]
Here is the 3mf file zipped... My profile might be really broken, as I am a rookie in 3D prints.
[CE3_GuideFilament+Detecteur_assemble_v2.zip](https://github.com/Ultimaker/Cura/files/4224163/CE3_GuideFilament%2BDetecteur_assemble_v2.zip)

**Comment by smartavionics** [comment]
Thanks for the project file. I tried fiddling with the settings but I could not stop it from filling the tube. I think you need to get a better model or somehow fix this one.

**Comment by hobiseven** [comment]
It will take me only a little bit of time to redo a full model in Solidworks.... I will do that. It is better this way rather than banging the heads against the wall.
However, Cura developpers might look in this broken model to get a more bulletproof slicer behavior...

**Comment by hobiseven** [comment]
@smartavionics  Mark, it is definitely linked to the profile parameters. With the default ender3 0.2mm profile, it is correct.... See attached. 
[CE3_GuideFilament+Detecteur_assemble_v2.zip](https://github.com/Ultimaker/Cura/files/4227918/CE3_GuideFilament%2BDetecteur_assemble_v2.zip)

**Comment by Ghostkeeper** [comment]
MeshLab even crashes on the MC edge collapse filter on that model o.O
