### ISSUE TITLE
bad slicing horizontal drill with 0 bottom layer

### ISSUE THREAD

**Issue by DorianPIERRE** [Ultimaker/Cura#7155]
**Application version**
Cura 4.4.1

**Platform**
Windows 7 64bit

**Printer**
Wanhao Duplicator 9

**Reproduction steps**
1. Part with horizontal drill
2. Ask 0 bottom layer
3. Show slicing detail of the top of drill

**Screenshot(s)**
![capture1](https://user-images.githubusercontent.com/19405304/75171237-9c8e4080-572b-11ea-97d1-ef615da59181.png)
![capture2](https://user-images.githubusercontent.com/19405304/75171243-9ef09a80-572b-11ea-92c3-0c1eb64f6566.png)
 
**Actual results**
No sliced layer on the top of drill

**Expected results**
Wall layer on the top of drill

**Project file**
[Uploading WD9_TestPourProfilSkate.zip…]()

**Log file**

**Additional information**
I need 0 layer in the bottom of part because i want to flow epoxy resine in printed model for mecanical compression required in case of gyroid infill

I try same on simplify3D with same result...

**Comment by smartavionics** [comment]
Hi, the link you give for the project file is broken. My guess is that the model is not valid.

**Comment by DorianPIERRE** [comment]
sorry ...
[WD9_TestPourProfilSkate.zip](https://github.com/Ultimaker/Cura/files/4245700/WD9_TestPourProfilSkate.zip)

**Comment by DorianPIERRE** [comment]
> Hi, the link you give for the project file is broken. My guess is that the model is not valid.
the model is very simple ... no ?

**Comment by smartavionics** [comment]
I recommend two changes to your profile:

1 - turn off Connect Top/Bottom Polygons as that makes the concentric skins ugly.

2 - set Bottom Layers to a value > 0 and Initial Bottom Layers to 0 to get the open bottom.

Hope this helps!

![Screenshot_2020-02-24_18-50-23](https://user-images.githubusercontent.com/585618/75181601-889c0c00-5736-11ea-9e2a-4649405e320b.png)

**Comment by DorianPIERRE** [comment]
I try tomorow but it looks good ...
Thanks

**Comment by DorianPIERRE** [comment]
Ok for me.
