### ISSUE TITLE
differences between inserted object and preview displayed

### ISSUE THREAD

**Issue by battistipaolo** [Ultimaker/Cura#7163]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by battistipaolo** [comment]
![Cattura1](https://user-images.githubusercontent.com/49492839/75353664-0f262a00-58ac-11ea-9a7b-02d32a81b2f9.PNG)
![Cattura2](https://user-images.githubusercontent.com/49492839/75353681-14837480-58ac-11ea-8d8e-802d93bc3f5e.PNG)

**Comment by Ghostkeeper** [comment]
Did you intend to close this issue? Did you find a solution?

If not, I suggest looking at whether the walls you're trying to print are not too thin to be printed with your line width.

**Comment by Ghostkeeper** [comment]
Here is an article with several possible causes for missing parts in your print: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/missing_parts.md

**Comment by battistipaolo** [comment]
Hello,
solved the problem, if the thickness of the loop is smaller than the diameter of the nozzle does not preview well.example: loop shell of .39mm. extruder of .40mm.
result: layers are not displayed well.
paolo battisti


    Il venerdì 28 febbraio 2020, 15:04:17 CET, Ghostkeeper <notifications@github.com> ha scritto:  
 
 
Did you intend to close this issue? Did you find a solution?

If not, I suggest looking at whether the walls you're trying to print are not too thin to be printed with your line width.
