### ISSUE TITLE
Allow "Save to File" to be the default (instead of "Save to Removable")

### ISSUE THREAD

**Issue by mjskier** [Ultimaker/Cura#7168]
**Is your feature request related to a problem? Please describe.**

I have a Western Digital My Book attached to my machine.
Every time I start Cura and slice a model, the default saving location for the .gcode file is **Save to Removable**. I need to click on the down arrow and select **Save to File**

**Describe the solution you'd like**

I would like to be able to save a setting so that the default is **Save to File** even if I have removable medias on the system.

**Describe alternatives you've considered**

I can use File->Export, or I can select the down arrow and select "Save to File". But it is annoying when that save dialog is obviously meant as a convenience.

**Affected users and/or printers**

Anybody who has removable devices attached to the machine when Cura is started and don't need to write the sliced model to a SD or other removable media. So pretty much anybody who use Octoprint or similar interface to their printer.

**Additional context**
![save_to](https://user-images.githubusercontent.com/1435545/75416843-b4f98900-58ec-11ea-8c07-271c9b4b7cc8.png)

**Comment by leothehuman** [comment]
Second this request!

**Comment by smartavionics** [comment]
As a workaround, you can just disable the removable drive support in the Marketplace dialog...

![Screenshot_2020-02-27_09-08-00](https://user-images.githubusercontent.com/585618/75428880-c53b5380-5940-11ea-8730-04a5bce22e8e.png)

**Comment by nallath** [comment]
Anyone using octoprint would be better off installing the octoprint plugin, since it enables an even easier flow; Directly sending it to octoprint.

Anyhow, I will discuss the feature request with the rest of the team.

**Comment by nallath** [comment]
Anyone using octoprint would be better off installing the octoprint plugin, since it enables an even easier flow; Directly sending it to octoprint.

Anyhow, I will discuss the feature request with the rest of the team.

**Comment by mjskier** [comment]
Thank you for the quick replies. I will try the suggestions.
The most user friendly behavior would be for Cura to remember the last choice over exit and restart.

**Comment by mjskier** [comment]
The workaround from @smartavionics works great for me.
So I'm going to close this issue. If somebody feels strongly about it I assume they can just reopen it.

**Comment by fieldOfView** [comment]
> So I'm going to close this issue. If somebody feels strongly about it I assume they can just reopen it.

Please don't. I feel strongly about it, but I cannot reopen the issue. I agree with you that the most user friendly behavior would be for Cura to remember the last choice over exit and restart.

**Comment by fieldOfView** [comment]
I have a PR here: https://github.com/Ultimaker/Uranium/pull/585. This remembers the last used output device between sessions.

**Comment by mahtDFR** [comment]
We have an internal ticket for this: CURA-7269

**Comment by fieldOfView** [comment]
Cura now remembers the last used option, so I think this can be closed.

**Comment by mjskier** [comment]
I don't know, the code was merged on April 1st. It could be a joke... ;-)
