### ISSUE TITLE
Add reload dialog for AMF models

### ISSUE THREAD

**Issue by jcharaoui** [Ultimaker/Cura#7192]
When overwriting an STL model file which is open in Cura, Cura detects this change and displays a helpful dialog offering to reload the model on the build plate. This doesn't work for models loaded from AMF files. Cura doesn't detect when the AMF source file changes.

It would be nice for Cura to also detect when the AMF source file is changed, and offer to reload the model on the build plate, just like with STL models.

**Comment by fieldOfView** [comment]
Good catch. See PR #7205 (which also fixes DAE and the other formats supported by Trimesh)

**Comment by Ghostkeeper** [comment]
We got this reported internally a month ago as well, but it ended up on our backlog since then. Thanks for the fix, @fieldOfView. I'll give that a test.
