### ISSUE TITLE
Support around round part is creating a solid perimeter that keeps from being removed.

### ISSUE THREAD

**Issue by ForceConstant** [Ultimaker/Cura#7209]
**Application version**
4.5.0

**Platform**
Win64

**Printer**
Ender3

**Reproduction steps**
I am trying to print a special gear, that has a top that needs support. The problem I have is the support that is being generated isn't able to be removed as it creates a continuous circle around part. Any ideas on how to print this successfully? I tried all the different support types, but they all seem to make the same outer shell around the support.

**Screenshot(s)**

![dvom5w8n3vj41](https://user-images.githubusercontent.com/26015318/75677158-d219b900-5c58-11ea-91e9-698c244bf494.png)
![hnbtovrt3vj41](https://user-images.githubusercontent.com/26015318/75677156-d1812280-5c58-11ea-8d4f-97069460084d.png)

**Actual results**
Zig Zag pattern is encased in a circle that makes it not able to remove support.

**Expected results**
Have a zig zag pattern that is easy to remove.

**Project file**
TBD

**Log file**
TBD

**Comment by mahtDFR** [comment]
Not really sure if this can be called a bug but I've put it up for discussion.
What if you change the support settings to make support easier to remove? Can you share a project file please? (File > Save as...) so I have your settings.

**Comment by ForceConstant** [comment]
> Not really sure if this can be called a bug but I've put it up for discussion.
> What if you change the support settings to make support easier to remove? Can you share a project file please? (File > Save as...) so I have your settings.


[CE3_Hex Cap Gear.zip](https://github.com/Ultimaker/Cura/files/4278352/CE3_Hex.Cap.Gear.zip)

**Comment by mahtDFR** [comment]
As a specific workaround for your situation, I'd suggest setting support walls to '0'. This means support walls won't be printed, only support infill, so you can grab the infill with pliers easily to remove it. Here's the result I got with your project file in 4.5. I've also attached a 3mf for you here.
[CE3_Hex Cap GearMJ.zip](https://github.com/Ultimaker/Cura/files/4280948/CE3_Hex.Cap.GearMJ.zip)


![image](https://user-images.githubusercontent.com/17821912/75770145-b80ad400-5d47-11ea-8542-c3a5d03e2ab9.png)

I don't think we're going to take this further as a feature, so I'll close this ticket. But thanks for your suggestion!

**Comment by ForceConstant** [comment]
> As a specific workaround for your situation, I'd suggest setting support walls to '0'. This means support walls won't be printed, only support infill, so you can grab the infill with pliers easily to remove it. Here's the result I got with your project file in 4.5. I've also attached a 3mf for you here.
> [CE3_Hex Cap GearMJ.zip](https://github.com/Ultimaker/Cura/files/4280948/CE3_Hex.Cap.GearMJ.zip)
> 
> ![image](https://user-images.githubusercontent.com/17821912/75770145-b80ad400-5d47-11ea-8542-c3a5d03e2ab9.png)
> 
> I don't think we're going to take this further as a feature, so I'll close this ticket. But thanks for your suggestion!

Thanks. Yes I didn't know about support walls,
