### ISSUE TITLE
Top layer infil. 

### ISSUE THREAD

**Issue by rewolff** [Ultimaker/Cura#721]
Infills are done along Y+X = C or Y-X=C lines. The top layer too. As the optimization (greedy) may cause moves along the just-laid surface, this leaves visible marks on the object. For better visual appearance, it would help to do: 
for the toplayer, handle all the infill lines in strictly ascending or descending C order. (only two optimization choices allowed, descending or ascending.)

 (As a matter of fact, I would want to enable this feature for the second-to-last layer as well: I can see the moves in that layer in my finished object. )

From a software-engineering  point-of-view, I would implement an "is_toplayer () " function. At first this can be very simple: If this is the last layer to be printed: yes, otherwise: no. Then the effects can already be seen on test-objects. Then later the "is_toplayer () " function can be improved. For example, if a piece of infill "sees the sky" then it could be called a toplayer. 

This may cause an increase in print-time. For example a cup shape with a large rim that requires an infill. The greedy algorithm would start at one point follow the rim, and once the cut-through to the other side happens, it will chose the wrong side to do first, so it will fill the other side first and then later come back to do the "top" of the circle. My suggestion will strictly alternate between the two sides of the cup with lots of long moves in between. Print time increases, but quality improves.

**Comment by Ghostkeeper** [comment]
In the upcoming version we have a new option for combing: No Skin. This avoids the skin when making travel moves (if possible). It does something completely different but the intent is similar.
