### ISSUE TITLE
Cura 4.5 MacOSX Model viewport rendering problem

### ISSUE THREAD

**Issue by kmarinelli** [Ultimaker/Cura#7212]
In Cura 4.5 in MacOSX Catalina, moving the window between screens does not trigger a rescale/redraw of the viewport for the model. Resizing the window resolves the problem. The program does not appear to be apropriately detecting or respecting redraw requests from the operating system when the screen is changed.

<img width="1979" alt="Cura 4 5_Catalina_Viewport pproblem" src="https://user-images.githubusercontent.com/5761495/75692117-1023d680-5c73-11ea-915a-c17d52dc09de.png">

**Comment by mahtDFR** [comment]
Thanks for the report. After some discussion we're not going to fix this as the user can still see the model and they can also use the cubes at the bottom-left corner to retrieve the view.
