### ISSUE TITLE
Unnamed version uninstaller (Windows)

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#7214]
**Application version**
4.5.1

**Platform**
Windows 10

**Reproduction steps**
1. have older Cura installed (e.g. 4.2)
2. install cura 4.5
3. Windows start menu > ultimaker  cura > uninstall cura

**Actual results**
uninstalls 4.5

**Expected results**
uninstalls 4.2

**Additional information**
The uninstaller doesn't mention the name its going to uninstall. It just says "Uninstall Ultimaker Cura" instead of "Uninstall Ultimaker Cura 4.5"

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
