### ISSUE TITLE
Retraction distance not visible

### ISSUE THREAD

**Issue by rofugos** [Ultimaker/Cura#7221]
**Application version**
4.5

**Platform**
Windows 10

**Printer**
Cr10s, Ender 

**Reproduction steps**
Don't know
![retracion](https://user-images.githubusercontent.com/8948999/75792566-70e40980-5d6e-11ea-8b20-14b56a2eee87.png)

**Screenshot(s)**
![retracion](https://user-images.githubusercontent.com/8948999/75792566-70e40980-5d6e-11ea-8b20-14b56a2eee87.png)

**Actual results**
I can't change retracton distance

**Expected results**
Change retraction

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Retraction Distance should be visible unless retraction is disabled or the g-code flavour is set to "Ultimaker 2". And for me using the CR10s defaults, the retraction distance setting is visible.
![image](https://user-images.githubusercontent.com/2448634/76209824-1a118080-6203-11ea-888b-c426825c5bac.png)

I'm unable to reproduce the problem in the way you describe it.

Could you provide us with a project file? As in, go to File -> Save... , zip the result and upload that here?
