### ISSUE TITLE
Wipe Nozzle Between N(!) Layers

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#7225]
Please add a setting allowing a user to set the count of layers at which the wipe gcode for "Wipe Nozzle Between Layers" is to be executed.

**Comment by thesec** [comment]
While at it - where to find and edit the script?

**Comment by mahtDFR** [comment]
> where to find and edit the script?

You'll find post processing scripts here (and at the same location in your install)
https://github.com/Ultimaker/Cura/tree/master/plugins/PostProcessingPlugin/scripts

I don't think this request fits in with our roadmap, but contributions are welcome. A post processing script would be a good way to implement it IMHO.

**Comment by thesec** [comment]
Thank you, but that does not sound like any match for the "Wipe Nozzle Between Layers" setting what you seem to be referring to. Seems like "script" brought you up that twig, so I edited the description accordingly.

**Comment by thesec** [comment]
... and am looking for the location of what's being referred to as "wipe G-Code" in that setting.

**Comment by mahtDFR** [comment]
Yep, no script exists yet, but if someone created a script for this it would be a good way to implement it. You could consider adapting one of the existing scripts for this.

**Comment by thesec** [comment]
You still seem on the wrong track. None is referring to any script any longer @mahtDFR !

@nallath, did you defer it according to @mahtDFR misinterpretation or other?

**Comment by mahtDFR** [comment]
It's deferred because this is not a priority in our roadmap right now. I suggested that it can be achieved with a post processing script, but we don't have the resources to make one now.

**Comment by thesec** [comment]
It will be a lot easier to modify the UI and have it writing the `;WIPE_SCRIPT_BEGIN ... ;WIPE_SCRIPT_END` only every nth layer which is what the request is about.

**Comment by thesec** [comment]
Would still love to know where the few lines of wiping gcode come from ... does not seem an easy find :/

**Comment by thesec** [comment]
Found the "wipe script" hardcoded in the engine's gcode export now.

**Comment by Ghostkeeper** [comment]
The "wipe script" was originally a post-processing script provided by DesktopMetal. It's been integrated in CuraEngine since. See also https://github.com/Ultimaker/CuraEngine/pull/1000 . This is why people are confused, I think.

**Comment by thesec** [comment]
That's explaining, yes.
