### ISSUE TITLE
Allow to Edit the "Wipe Script"

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#7234]
"Wipe Nozzle Between Layers" adds a automatically generated "wipe script" to the gcode.
Being able to edit that script, the same way as for the printer's and nozzle's start and end scripts would be helpful.

**Comment by Ghostkeeper** [comment]
This script is integrated into CuraEngine. You can edit CuraEngine, but that requires compiling CuraEngine.

I don't think we'll make this easier in the near future. The "wipe script" is just as much a script as the "outer wall script" now.

**Comment by Ghostkeeper** [comment]
It's somewhat ugly that this wiping always wipes horizontally to the X axis. It's really specific to the DesktopMetal type of printers that have their brushes on the side. In my opinion this sort of thing should not get merged into CuraEngine and so perhaps we should remove it from there.

**Comment by thesec** [comment]
🥺
