### ISSUE TITLE
The disappearance of the bridge

### ISSUE THREAD

**Issue by deniman** [Ultimaker/Cura#7244]
**Application version**
4.4.1 and 4.5.0

**Platform**
Windows 7 x64

**Printer**
Creality3D Enrder-3 

**Reproduction steps**
I rotate my model for 90 degrees and  I click on the slice button and get the bridge disappearing in the preview.

**Screenshot(s)**
![cura_bug_01](https://user-images.githubusercontent.com/3313032/76166585-44fac680-6168-11ea-8172-0f380bb1c4e3.png)
![cura_bug_02](https://user-images.githubusercontent.com/3313032/76166588-4926e400-6168-11ea-96cd-37bb4bf714cb.png)

**Actual results**
There is no bridge.

**Expected results**
The model must be slice with all the details.

**Project file**
[CE3_Body1.zip](https://github.com/Ultimaker/Cura/files/4303482/CE3_Body1.zip)

**Log file**
[log.zip](https://github.com/Ultimaker/Cura/files/4303487/log.zip)

**Comment by fieldOfView** [comment]
Check your model in X-Ray view. There are two faces that (one on each side of the bridge) that should not be there.

![image](https://user-images.githubusercontent.com/143551/76166825-dfa3d700-6161-11ea-971c-499f1cdd0e6f.png)

**Comment by deniman** [comment]
In my version of Crua there is no this option.

**Comment by fieldOfView** [comment]
Yes it does, though it has been hidden away on the Preview tab:
![image](https://user-images.githubusercontent.com/143551/76192890-284fa480-61e3-11ea-8bb0-f8064d0be604.png)

**Comment by Ghostkeeper** [comment]
You can also try the Extensive Stitching option in the Mesh Fixes category. It's made to handle this case.
