### ISSUE TITLE
[4.5.0] Setting max resolution does not work as intended when set below 0.5mm

### ISSUE THREAD

**Issue by Virtox** [Ultimaker/Cura#7245]
Cura 4.4.1 and 4.5.0 
Windows 10 x64
Ender 5 Plus

With max deviation set to the default 0.05mm and max resolutions set to 0.05mm (the defaults) segment length is way bigger than that.
Looks like setting max resolution below 0.5 mm increases line segments instead of decreasing.
Setting it to 0.1mm creates segments longer than when set to 1.0mm.
See attached images for various settings and results, see distance between previous and current nozzle position.
Changes to max deviation do not seem to help here (it does when max resolution>1.0mm)

Attached a simple project file of a 100mm diamter disc with 0.1 mm segment length around the perimeter.

![MaxRes_0 10_Dev_0 05](https://user-images.githubusercontent.com/5301471/76170648-420dcf00-6184-11ea-8542-ea061c5e2929.jpg)
![MaxRes_0 25_Dev_0 05](https://user-images.githubusercontent.com/5301471/76170650-42a66580-6184-11ea-888c-a903a92f2b17.jpg)
![MaxRes_0 50_Dev_0 05](https://user-images.githubusercontent.com/5301471/76170651-433efc00-6184-11ea-8ea2-9e940dfa4d1b.jpg)
![MaxRes_1 00_Dev0 05](https://user-images.githubusercontent.com/5301471/76170652-44702900-6184-11ea-9cd1-34fc7fa7aecb.jpg)
[DiscR50mmS0.1mm.zip](https://github.com/Ultimaker/Cura/files/4303831/DiscR50mmS0.1mm.zip)

**Comment by Ghostkeeper** [comment]
Also reported here: https://github.com/Ultimaker/CuraEngine/issues/1151

This is still on our backlog and one of the more important slicing bugs at the moment if you ask me. I hope we can get a fix in for v4.6 or v4.7.
