### ISSUE TITLE
Lay flat menu not complete

### ISSUE THREAD

**Issue by cinealfa** [Ultimaker/Cura#7246]
**Application version**
4.5.0

**Platform**
mac OSX 10.12

**Printer**
ENDER 3

**Reproduction steps**
1. Try to Rotate an object
2.Icon doesn't include the last choice for lay selected face flat.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**

**Expected results**
Item is there on all my other machines

**Additional information**
Didd a complete clean install including throwing all old support files away no change.
![Screen Shot 2020-03-08 at 9 05 11 PM](https://user-images.githubusercontent.com/32920432/76182127-e4c44e80-6180-11ea-838a-7fe5959abd27.png)

**Comment by Ghostkeeper** [comment]
It hides that option if your GPU doesn't support identifying the face that you're clicking on. For laying the object flat on a face, Cura needs to know which face lies underneath the cursor. This is a feature in OpenGL 4. If your GPU doesn't support OpenGL 4 yet, Cura can't provide that feature.

Most likely your layer view will also be flat 2D then. It's been set to compatibility mode.
