### ISSUE TITLE
Cura [4.5.0] Incorrect display of program screen with Kubuntu 19.10

### ISSUE THREAD

**Issue by Gleis1234** [Ultimaker/Cura#7253]
4.5.0
**Application version**
(The version of the application this issue occurs with.)
Kubuntu 19.10
**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
doesn't matterr
**Printer**
(Which printer was selected in Cura?)
Start Cura
**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

Screenshot attached
**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
Not all Information on screen is displayed.
**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

This happens after upgrading Kubuntu from 19.04 to 19.10
Cura 4.4.1 has the same problem.
![Screenshot_20200310_095109](https://user-images.githubusercontent.com/36842709/76295388-d11a0480-62b4-11ea-9a66-3dc4394695fa.png)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Gleis1234** [comment]
Adding Logfile
[cura.log](https://github.com/Ultimaker/Cura/files/4311277/cura.log)

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/issues/5296

**Comment by Gleis1234** [comment]
Thank you for the quick help. The information solved my problem.
