### ISSUE TITLE
Supportless overhang pattern

### ISSUE THREAD

**Issue by Avamander** [Ultimaker/Cura#7257]
**Is your feature request related to a problem? Please describe.**
When printing something **around** an object, object is placed in the print mid-print, for example a lockpick handle or an enclosure for something, causes the issue that Cura tends to print mid-air when the top layer has (necessary) holes. That means the layer usually goes to waste because Cura assumes next layers can adhere to the bottom ones, but in reality there's nothing below and can't be below.

**Describe the solution you'd like**
I would like a way of telling Cura to use a specific pattern for the supportless overhang's first layer that would always start from the edges, for example spiral to the middle. So that the printer never starts printing mid-air without supports, that are logically impossible to properly print.

**Describe alternatives you've considered**
I currently solve it by letting that first layer go to waste and wait for enough plastic to be deposited on the object so that layers on top end up nice.

**Affected users and/or printers**
Affects every print that prints around an object

**Additional context**
Example print: https://www.thingiverse.com/thing:4083032
But there are many many others.

**Comment by smartavionics** [comment]
Could you please attach a screenshot showing the above lockpick object on the buildplate in the orientation that you are having problems with? Thanks.

Here's how I would expect it to be printed...

![Screenshot_2020-03-10_17-56-03](https://user-images.githubusercontent.com/585618/76343724-6f7b8980-62f8-11ea-9aad-76876658f725.png)

I can't see any big problems with that.

**Comment by Avamander** [comment]
I'd expect the print to be rotated 90deg towards top right, so it'd be flat with the bed, otherwise I don't see how the pick could be placed inside during the print.

**Comment by smartavionics** [comment]
I don't believe it was intended to be printed like that but, anyway, this is what the first layer above the big hole looks like and you can see the skin lines go across the gap quite nicely...

![Screenshot_2020-03-10_18-41-54](https://user-images.githubusercontent.com/585618/76347726-fdf30980-62fe-11ea-9c5b-39e082cee9ac.png)

**Comment by Avamander** [comment]
Okay yeah, in that case it works if the top layer doesn't have any holes. My bad, that specific model is not a good example of this specific issue, only as a type of print where object is placed inside.

Here's a model of mine intended to fit snugly around a key:
![image](https://user-images.githubusercontent.com/5392141/76348668-40bddd00-6311-11ea-9126-408c4888ea72.png)

Here the what gets extruded first:
![image](https://user-images.githubusercontent.com/5392141/76348759-6ba83100-6311-11ea-9ab2-5db66d0e6ff0.png)

As you can see, without adhesion (which is unlikely to happen on an unheated, uneven surface such as a key), this layer is likely to fail.

**Comment by smartavionics** [comment]
Ah, OK, I understand now. Yes, that's going to fail. If I was doing that model I would not have the hole go all the way through that top surface so that the first layer over the key is without holes and the hole gets cut out after the print has finished. I use that technique whenever I have a wall that is completely unsupported.

**Comment by Avamander** [comment]
Yes, that works to a certain extent, but I was exactly thinking that Cura could build paths that start building off from the walls e.g. a spiral pattern towards the middle, that would increase the likelihood that the "first" layer won't fail.

**Comment by smartavionics** [comment]
In the general case, you can't assume there's any support at all under the skin so I doubt very much that a spiral skin would be successful.

This issue is really the same as https://github.com/Ultimaker/Cura/issues/7162.

**Comment by Avamander** [comment]
I've found that I can get the first layer succeed everywhere except that hole, when I make sure the diagonal extrusions don't detach from the wall. So I do think it would improve the chances it does succeed when extra attention is paid by the slicer not to print mid-air.

**Comment by Ghostkeeper** [comment]
They have some interesting ideas on how to tackle this for general shapes over at #7162. Please continue the discussion there.
