### ISSUE TITLE
Turn Off Helpers

### ISSUE THREAD

**Issue by hatrickseanmikal** [Ultimaker/Cura#7258]
**Application version**
CURA 4.5  & http://3dp.rocks/lithophane/

**Platform**
WINDOWS 10

**Printer**
ENDER 5

**Reproduction steps**
1. PUT LITHOPHANE INTO CURA
2. LOOKED AT PREVIEW BEFORE PRINTING & SAW EXTRA SUPPORTS ON BUILD PLATE CALLED " HELPERS" IN YELLOW
3. I PROCEEDED TO PRINT THINKING SUPPORTS WOULD NOT INTERFERE WITH PRINTING

did next.)**Screenshot(s)**
[hatrick-lithophane-screenshot.docx](https://github.com/Ultimaker/Cura/files/4314053/hatrick-lithophane-screenshot.docx)

**Actual results**
THE " HELPER SUPPORTS" CAUSED THE LITHOPHANE TO DELAMINATE OFF OF THE PRINT BED AROUND LAYER 300 AS THEY CAME CLOSER TO TO CONNECT WITH LITHOPHANE

**Expected results**
I EXPECT TO BE PROVIDED WITH A WAY TO TURN OFF OR REMOVE THE 
" HELPER SUPPORTS" AS THEY ARE NOT NEEDED

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment]
We expect you to fill in the template. An issue is never just the title; we need more information.

**Comment by Ghostkeeper** [comment]
AH, I SEE YOU ALSO INSTALLED A CRUISE CONTROL BUTTON ON YOUR KEYBOARD.

> I EXPECT TO BE PROVIDED WITH A WAY TO TURN OFF OR REMOVE THE " HELPER SUPPORTS" AS THEY ARE NOT NEEDED

INDEED, YOU ARE PROVIDED WITH A WAY TO TURN OFF SUPPORTS:
![WHERE SUPPORT IS](https://user-images.githubusercontent.com/2448634/76632657-d345c280-6543-11ea-9aaf-79cc3f16a807.png)
