### ISSUE TITLE
[4.5.0] cura error : cx_freeze: python error in main script, importerror : no module named 'gcura__init__'

### ISSUE THREAD

**Issue by Collins-rcs** [Ultimaker/Cura#7271]
i can't opend cura in my computer, please help !!

> https://live.staticflickr.com/65535/49652603833_3cd3d3630f_h.jpg

**Comment by nallath** [comment]
Could you please fill in the bug template. It's there for a reason (most notably; It contains questions that can help us solve the problem). As it stands, we don't have enough information to help you out.
