### ISSUE TITLE
Poor slicing modeling

### ISSUE THREAD

**Issue by jornada812** [Ultimaker/Cura#7273]
https://yadi.sk/d/OufBRC8v68UNkQ (Model Link)
 https://yadi.sk/i/uC7awodqO7EN7A (Photo slicing)
For a long time I wondered why Simplifiy3d prints better than Сura, until I looked at what our favorite slicer slices. With any standard settings, I get errors on the surface. Maybe I don’t know any settings? Or is the slicer corrupted? Model checked and printed in s3d without these artifact. Perhaps Сura is so cool that he makes predictions where my printer will give a mechanical error? ;)

**Comment by CCS86** [comment]
Try disabling "compensate wall overlaps". See if that helps.

**Comment by nallath** [comment]
I'm not quite sure it's compensate wall overlaps. It's looking an aweful lot like artefacts caused by the "maximum resolution" setting. You might want to look at that setting too.

**Comment by Ghostkeeper** [comment]
This is the issue that triggered research into a fix that eventually led to this PR: https://github.com/Ultimaker/CuraEngine/pull/1214

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
