### ISSUE TITLE
Cura 4.5 doesn't saving an filament dia in printer settings

### ISSUE THREAD

**Issue by il4masta** [Ultimaker/Cura#7279]
**Application version**
Cura 4.5

**Platform**
Win10

**Printer**
Custom FF printer (it's the FLSun Cube actually)

**Reproduction steps**
1. I'm going to the machine settings and trying to change "Compatible material diameter" from 2.85 (which was as default) to 1.75
2. Closing and opening again, dia stay 2.85
3. Even after I've added a new printer and setting the material dia as 1.75 if I'm going to the machine settings again I see the 2/85 dia again 
![Clipboard07](https://user-images.githubusercontent.com/56682417/76685399-5b9b9480-6624-11ea-9fb3-329e4a1a5265.jpg)

**Comment by fieldOfView** [comment]
Could you try with a comma instead of a dot? There is (or was?) a similar issue with the nozzle size where using a comma was a workaround.

**Comment by rburema** [comment]
What're your 'locale' settings? (More pertinent, what's the decimal separator that's been configured in windows?)

**Comment by Ghostkeeper** [comment]
Probably the same issue as https://github.com/Ultimaker/Cura/issues/6546 (but with a different setting).

**Comment by mituritsyn** [comment]
4.6.1 Same issue with the filament diameter
Ubuntu 18.04 Russian and English locales.
By deafult it is 2.85 (with dot). Was trying to change to 1.75 or 1,75 - no difference afrer closing it is dropped to 2.85

**Comment by Thisismydigitalself** [comment]
Same here.  4.6.1 on Win10/64 keeps defaulting back to 2.85 in printer settings. changed to 1.75 and 1,75 - after restart it's back to 2.85. what's worst is that i saw the issue in printing quality so i checked the gcode and loaded it back to cura and it looks perfect - the gcode / gcode parser does not reflect this issue.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
