### ISSUE TITLE
[4.5.0] Failure Midprinting Almost Constantly

### ISSUE THREAD

**Issue by TheGangster1023** [Ultimaker/Cura#7282]
**Application version**
4.5.0

**Platform**
Windows 10 Home

**Printer**
Monoprice Select Mini v2

**Reproduction steps**
1. I was printing a large mass of parts and the extruder just stopped and wouldn't continue even after a pause and unpause.
2. I thought this was just because there were so many parts on the bed at one time, so I did the same print again and it worked fine. As that has been some time ago and I have printed a lot since then, I can conclude that it is random and there are no certain situations that it appears to do it on more often than others.

**Additional information**
Some of the people with this problem have stated that it is because of using a USB tether and moving to a transfer with a micro SD card has fixed the problem, but I have asked people that use a USB tether with the same printer if they have run into any issues and they said they haven't.

**Comment by nallath** [comment]
So if I understand correctly, the printer freezes sometimes when it's connected via an USB thether (and it doesn't freeze when using an SD card)?

**Comment by TheGangster1023** [comment]
I haven’t been able to try using an SD card yet because the adapter I ordered to I could write to it hasn’t come in yet.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rburema** [comment]
Is it always happening on the same layer?

**Comment by Ghostkeeper** [comment]
Maybe this happens when the computer goes into sleep mode?

**Comment by TheGangster1023** [comment]
Everytime I’ve had it happen I have been actively doing something on my PC, so there would be no way that could be it and I have it were it never sleeps in my Windows settings.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TheGangster1023** [comment]
It doesn’t seem to happen until late into the print but I don’t believe its on the same layer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Ghostkeeper** [comment]
Some more possible causes are written down in the Settings Guide: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/unfinished_print.md#printer-failures

Cheaper printers seem to sometimes get their stepper drivers to fail because they become too hot.

As it stands, we're not really able to help you because we can't pinpoint where Cura is doing it wrong. When I'm making a print it finishes every time (unless I abort).

**Comment by TheGangster1023** [comment]
Where would the stepper driver be located? I would be fine with modding my printer to have another fan.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Ghostkeeper** [comment]
On my printer it's towards the edge of the electronics board. Built into the board design.

Here's an article on the RepRap Wiki with some example pictures: https://reprap.org/wiki/DRV8825
