### ISSUE TITLE
[4.5.0] (very?) high memory usage

### ISSUE THREAD

**Issue by ukd1** [Ultimaker/Cura#7285]
**Application version**
4.5.0

**Platform**
iMac 5k, 2015, 4ghz i7, 48g ram
AMD Radeon R9 M395

**Printer**
Ender 3, marlin 2.0.5 - was set to remote with octopi plugin

**Reproduction steps**
open it
load stl (xyzCalibration_cube.stl)
slice
print
wait (shrug to exact, but log started at 10:36am --> now at ~5pm)

**Screenshot(s)**
<img width="852" alt="image" src="https://user-images.githubusercontent.com/44345/76713388-901f5700-66dd-11ea-8068-023da4ff2b9b.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/44345/76713522-67e42800-66de-11ea-8675-ee012de876a5.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/44345/76713525-6b77af00-66de-11ea-824c-335defc6c0a8.png">

<img width="932" alt="image" src="https://user-images.githubusercontent.com/44345/76713533-7df1e880-66de-11ea-816b-e8180bb696e0.png">

(all content: https://gist.github.com/ukd1/474618ada441056995907d969bbf7ddd)

![image](https://user-images.githubusercontent.com/44345/76713380-839afe80-66dd-11ea-85f1-8e858f27c467.png)

**Actual results**
11g + of ram used

**Expected results**
a reasonable amount of ram used...?

**Project file**
https://www.thingiverse.com/thing:1278865 is the cube I used

**Log file**
https://gist.github.com/ukd1/c4262257271eaa282247f7edfe0d9100

**Additional information**
/shrug

**Comment by Ghostkeeper** [comment]
We (or rather, @evtrados) ran your reproduction steps: Starting Cura (it was around 11:00 at the time), loading a model file, slicing, then waiting. It's 18:00 now and it's using about 300MB still. We're not seeing any excessive memory usage.

What we are not able to test is to print with an Ender 5 using OctoPrint. We don't have any OctoPrint printer here. Perhaps the problem is localised to this plug-in. We've had before that the Ultimaker wifi-printing plug-in was having a memory leak in the camera feed.

**Comment by fieldOfView** [comment]
@ukd1, it helps if you could try if you can reproduce this in a couple of variations
* does it also happen if you keep Cura open without printing?
* does it also happen if you don't have the OctoPrint instance running?
* does it also happen if you add another printer to Cura that is not connected to OctoPrint?

Also, did you have Cura open on the Monitor tab for most of the time, or on the Prepare tab as in your screenshot?

**Comment by fieldOfView** [comment]
If I could, I would add a "Status: Needs info" label

**Comment by ukd1** [comment]
@fieldOfView closing, as I don't have any more info
