### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by MrCanan** [Ultimaker/Cura#7287]
Removed

**Comment by fieldOfView** [comment]
Go to the "Installed" tab of the Marketplace, and scroll down to "USB Printing". Uncheck that checkbox and restart Cura.

**Comment by MrCanan** [comment]
Thank you for your help,
For sure, if I disable the USB plugin, I will not have the problem. ^^
But it not solves it because it makes Cura unusable via USB (as I print with it, so I need it).

I remember something like editing a Python in "C:\Program Files\Ultimaker Cura 4.5\plugins\USBPrinting" folder.
Can someone help me?


NB: My printer is the Ender 3 Pro.

**Comment by fieldOfView** [comment]
I hope my answer did not make you go away.

If you solved your problem by yourself, it is more customary (and helpful for others) to share how you fixed it, than to remove your post.
