### ISSUE TITLE
failed to enable bed leveling. 

### ISSUE THREAD

**Issue by 0emission** [Ultimaker/Cura#7288]
**Application version**
fractory v 3.0.b9

**Platform**
windows 10

**Printer**
julia plus

**Reproduction steps**
1.After creating g code for Julia plus using this software**(Fractory Version: 3.0.b9)** I downloaded the g code file into the printer, 
2. Printer accepts the file and start showing the status as operational.
3. Nozzle and bed begins to heat up and come back to their home position to start printing but 
then the error occurs **" Failed to enable bed leveling".**  

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
The printer stops after the error and needed to restart to print the other files made by using Fractory (Version 2.0). 

**Expected results**
Printer should read and print the gcode file. 

**Project file**
Download the g code file 
**https://we.tl/t-2UZXOUEeTv**

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
> fractory v 3.0.b9

We mean the version of Cura, like 'Cura 4.5.1'.
I wasn't able to find any information on a 'Fractory' version.
We can't support any version we don't know about.

Please contact the people responsible for packaging that version.

If I open up the gcode file, I see the following line:

> ;Generated with Cura_SteamEngine mb-master-20191116

I know @smartavionics always tags branches with those initials, so maybe some people are using that master as a basis for a packaged version?
