### ISSUE TITLE
2.1 no longer remembers last window position in multi-Monitor config

### ISSUE THREAD

**Issue by Searider** [Ultimaker/Cura#729]
I have multiple monitors. 2.1 will always open on the "Primary" monitor. This was an issue in a previous beta but was fixed in 1.99 and now it is back with 2.1. It is very annoying to have to move the Window to the Monitor that I use for CURA everytime I open it. 

Great Product  -  Thanks

**Comment by fieldOfView** [comment]
This has been fixed on the master branch, so it will be in the 2.2 release.
