### ISSUE TITLE
[4.5.0] Firmware Retract Missing?

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7295]
Am I just missing something, or is the firmware retraction option gone?

I have even tried creating a new, custom FFF machine and still do not see it.

**Comment by DivingDuck** [comment]
You are maybe looking for the plugin "Printer settings":  https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/PrinterSettingsPlugin

**Comment by CCS86** [comment]
I didn't realized it had been moved into a plugin

**Comment by CCS86** [comment]
I installed that plugin and restarted Cura, but no new sidebar has appeared. 

![image](https://user-images.githubusercontent.com/12439543/76994355-3fe20800-691c-11ea-9709-e279cecd2c01.png)

**Comment by DivingDuck** [comment]
Set Setting visibility to all. 

![settings](https://user-images.githubusercontent.com/8143022/76995297-f4495180-694f-11ea-8b7e-d8a1ca238f14.PNG)

I use an additional plugin for all settings. Maybe its helpful for you too. It is called Sidebar Gui: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/SidebarGUIPlugin

**Comment by CCS86** [comment]
I had misread the description of the plugin. I see that it added a new category to the settings sidebar.

Thanks guys!
