### ISSUE TITLE
[Change at Z]: Add retraction distance / speed

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7296]
It would really be helpful to add some retraction settings (distance, speed, etc) to the 'change at Z' script. 

Dialing in retraction distance and speed is one of the fundamental, printer-specific settings to be tuned. The change at Z script is very useful for creating these types of test prints.

Thanks!

**Comment by rburema** [comment]
We've discussed this internally and chosen to defer it due to workload and priorities.

Pull-requests are of course welcome.

**Comment by Ghostkeeper** [comment]
This has been implemented for us, actually, through this pull request: https://github.com/Ultimaker/Cura/pull/6778
It will be included with Cura 4.7!
