### ISSUE TITLE
Machine settings dialog cannot be resized / G-Code fields not visible

### ISSUE THREAD

**Issue by noswall** [Ultimaker/Cura#7306]
**Application version**
Cura 4.5.0

**Platform**
Mac OS 10.15.3

**Printer**
Monoprice Mini Delta

**Reproduction steps**
When selecting manage printers, then clicking machine settings, the Start and End G-Code fields are very small, and the Machine Settings dialog cannot be resized. This occurs whether Cura is run in low- or in high-resolution mode.

**Screenshot(s)**
<img width="674" alt="Screenshot 2020-03-19 at 16 46 34" src="https://user-images.githubusercontent.com/58133937/77087005-d38e0400-6a02-11ea-8285-63aa3bea2ba5.png">

**Comment by rburema** [comment]
This has been fixed, but the fix unfortunately was made after we branched off 4.5
It should be in the upcoming 4.6

For future reference: If this still will persist in the next version (4.6.0) please make a new issue.
