### ISSUE TITLE
Don't include scripts when installing v4.5

### ISSUE THREAD

**Issue by Alvgon** [Ultimaker/Cura#7307]
**Application version**
Cura v4.5 std

**Platform**
Windows 10

**Printer**
Creality Ender 3

**Reproduction steps**
Just after installation of new version

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

When v4.5 is installed, Cura includes postprocessing scripts that change extruder temp every 25 layers. 

Took me some time and half a kg of filament to understand what it was happenning. 

Please, please ... don't include active postprocessing scripts at installation time !!

**Comment by fieldOfView** [comment]
Any postprocessing scripts are not added "out of the blue" upon installation, but they are copied over from a previous configuration, along with the printer configuration and other settings.

**Comment by fieldOfView** [comment]
To mitigate your problem, Cura 4.6 will show more clearly the number of postprocessing scripts that are active, like this:
![](https://user-images.githubusercontent.com/143551/75591030-fd48b080-5a7e-11ea-883e-433d30e8bd57.png)

**Comment by Alvgon** [comment]
> 
> 
> Any postprocessing scripts are not added "out of the blue" upon installation, but they are copied over from a previous configuration, along with the printer configuration and other settings.

Thanks for answering so quickly. If the scripts are not part of v4.5, then they were from v4.5 beta.
I upgraded from v4.0 that didn't have those scripts, to v4.5 beta.; and following day to v4.5 standard. Took me a while to understand what was happenning with the extruder temp.

If somebody else took the same version path, probably will have those (asumed for testing purposes) scripts active.

**Comment by fieldOfView** [comment]
> If somebody else took the same version path, probably will have those (asumed for testing purposes) scripts active.

Not unless they manually activated those scripts, or imported a project with those scripts activated. Cura does not (and has not, in any version) activate postprocessing scripts on its own.

**Comment by Ghostkeeper** [comment]
I took the following reproduction steps:
* Cleaned any previous Cura configuration.
* Start Cura 4.0.0.
* Add a Creality Ender 3 printer.
* Close Cura 4.0.0.
* Start Cura 4.5.0.
* Load a model (otherwise the post-processing scripts button is not visible).

No post-processing scripts have been loaded then, as can be seen by there not being this wrench and hammer icon near the slicing panel: 
![image](https://user-images.githubusercontent.com/2448634/77402283-b5cbf080-6dae-11ea-99b5-b01a2ffe800c.png)

There are also no post-processing scripts active when opening the actual dialogue in Extensions.

Maybe you loaded a project file that had the post-processing scripts in them?

**Comment by Alvgon** [comment]
Hace hoy tries v4.5 beta?

**Comment by Ghostkeeper** [comment]
I did now, though supporting that beta is not a concern of course. But I get the same result:

![image](https://user-images.githubusercontent.com/2448634/77627022-8354fb80-6f46-11ea-942e-ed74c211fa74.png)

The code for the version upgrade didn't change during the beta.

**Comment by Alvgon** [comment]
Ok then, lets close this. Many thanks for your attention to this. BRs.
