### ISSUE TITLE
Using "display file name and layer on LCD" with " pause at height" causes extruder value to be wrong - Ender 3

### ISSUE THREAD

**Issue by pnwdan** [Ultimaker/Cura#7309]
Cura 4.5.0
Creality Ender 3 Pro
Not model specific

If i use these two post processing modifications together, the extruder G92 E value is wrong after the M0.

Instead of returning the G92 E value to where it needs to be next, the G92 line has an E3 causing the extruder to over extrude on top of the print.

![Capture1](https://user-images.githubusercontent.com/62411524/77131587-4e621980-6a19-11ea-9a84-e4207ee62287.PNG)
![Capture2](https://user-images.githubusercontent.com/62411524/77131588-4efab000-6a19-11ea-9c98-32ebd1731866.PNG)

**Comment by rburema** [comment]
I know you said it's not model specific, but I haven't had any luck reproducing this so far. Could you attach the (saved, not exported) project file? (Zip it to get github to accept it.)
