### ISSUE TITLE
[2.1 Beta] Flow isn't read from profile

### ISSUE THREAD

**Issue by Raniz85** [Ultimaker/Cura#731]
When saving a profile the flow rate as set is shown in the profile manager but in the GUI it's always set to the default when switching profiles - regardless of what it's set to in that profile.

**Comment by nallath** [comment]
What profile did you use? Material or Quality? 

Could you give us your profiles (so we can see what's in them & test this ourselves)?

**Comment by Raniz85** [comment]
It's read correctly from the profile when I open up Cura btw.

```
[general]
version = 1
name = White ABS 0.1mm 5mm Brim
weight = 0

[settings]
brim_width = 5
material_print_temperature = 230
alternate_extra_perimeter = True
retraction_amount = 2
cool_fan_enabled = False
cool_fan_speed = 50
material_bed_temperature = 100
````

**Comment by BagelOrb** [comment]
probably solved
