### ISSUE TITLE
Straight infill of full layer

### ISSUE THREAD

**Issue by Rendojack** [Ultimaker/Cura#7319]
Need ability to prevent Cura slicer from leaving certain object parts for later infill. Let it go straight lines for full layer. Prusa slicer has this feature by default.

Illutration of issue:
https://imgur.com/a/fFaGwaB

**Comment by smartavionics** [comment]
So how does Prusa slicer do it? Please post some more images that illustrate that.

**Comment by Rendojack** [comment]
Prusa does a nice and smooth surface, then builds those towers on top of that.
Cura is starting to build towers inside of top layer, then leaves infill gaps to finish later. 

Images: https://imgur.com/a/XAppoSE
Stl for slicing: https://easyupload.io/flm2yn

**Comment by smartavionics** [comment]
Increase the skin expand distance...

![Screenshot_2020-03-21_15-15-18](https://user-images.githubusercontent.com/585618/77229608-d31e7600-6b86-11ea-9dfa-1b688511bf49.png)

**Comment by Rendojack** [comment]
Thanks. That is the answer. Didn't know this feature existed, even cura community on facebook weren't able to help with this.
