### ISSUE TITLE
Preview not functional.

### ISSUE THREAD

**Issue by marave** [Ultimaker/Cura#7323]
**Application version**
4.4, 4.5

**Platform**
Windows 10, RTX2060

**Printer**
Custom

**Reproduction steps**
1. Went to Preview tab

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/5278075/77237388-26e88980-6b9e-11ea-83ae-05223c7348bc.png)

**Actual results**
Preview doesn't show layers and moving the slider does nothing.

**Expected results**
Should show layers.

**Project file**
Happens on all projects.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4364328/cura.log)

**Additional information**
Works fine on my MacBook.

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this problem:
![Screenshot from 2020-03-24 15-57-54](https://user-images.githubusercontent.com/2448634/77440215-525eb480-6de8-11ea-85c5-1e33f634377a.png)

You could try to go in the preferences and check the "Force layer view compatibility mode" option? Does that help any?

The log reveals that your GPU claims it supports OpenGL4, which is all it should need.

**Comment by marave** [comment]
That does improve things.  Doesn't work quite right though.  Thanks

![image](https://user-images.githubusercontent.com/5278075/79518190-7051ba80-801e-11ea-9d4e-542c496bca9b.png)

**Comment by Ghostkeeper** [comment]
Yeah, the compatibility mode has fewer features and looks a bit dated. Sorry.
