### ISSUE TITLE
[4.5] Can't Control Speed

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7325]
I really want to take control of all posted speeds, and ditch any formulas. But I just can't seem to get there:

![image](https://user-images.githubusercontent.com/12439543/77241311-38da2480-6bbe-11ea-8638-b39a2b06be31.png)

![image](https://user-images.githubusercontent.com/12439543/77241312-3bd51500-6bbe-11ea-80bd-90d2e8007261.png)

What am I missing?

**Comment by smartavionics** [comment]
Do you have a minimum layer time set? Perhaps it's slowing the outer wall down because of that? Or maybe you have a script active that has modified the speed?

**Comment by CCS86** [comment]
Doh, you called it.

That setting wasn't visible, but it was enforcing a 5 second layer time. After dropping down the perimeter count, I infringed on that. Thank you.
