### ISSUE TITLE
 When slicing a multi-level nested model, the gaps were filled incorrectly.

### ISSUE THREAD

**Issue by gailulun** [Ultimaker/Cura#7327]
cura4.x
windows10
**When slicing a multi-level nested model, the gaps were filled incorrectly.**

Original model
![Snipaste_2020-03-22_12-10-29](https://user-images.githubusercontent.com/50689883/77242253-8d6db600-6c37-11ea-95d5-490dc10df892.png)

Effect of slicing
![Snipaste_2020-03-22_12-10-44](https://user-images.githubusercontent.com/50689883/77242263-ad04de80-6c37-11ea-95d0-f6581600be85.png)
![Snipaste_2020-03-22_12-11-01](https://user-images.githubusercontent.com/50689883/77242265-aecea200-6c37-11ea-8034-ef2aaa24aef7.png)
![Snipaste_2020-03-22_12-11-09](https://user-images.githubusercontent.com/50689883/77242269-b55d1980-6c37-11ea-858b-4cf55be60064.png)

the solution
![Snipaste_2020-03-22_12-11-43](https://user-images.githubusercontent.com/50689883/77242278-ce65ca80-6c37-11ea-92b6-814e95ced8f8.png)
![Snipaste_2020-03-22_12-11-58](https://user-images.githubusercontent.com/50689883/77242386-c8241e00-6c38-11ea-83be-36758e72b7b4.png)

![Snipaste_2020-03-22_12-24-41](https://user-images.githubusercontent.com/50689883/77242314-243a7280-6c38-11ea-9e5a-9254b1b09d10.png)
It seems that this is related to the design logic of the stl file. The added bar connects the models into a whole (three independent models before this), and also helps cura distinguish the direction of the face.

**Comment by mahtDFR** [comment]
This could be down to an engine issue. Please save the project file (File -> Save...) and then zip up the .3mf file and attach to this issue so I can reproduce it.

**Comment by gailulun** [comment]
[3D.zip](https://github.com/Ultimaker/Cura/files/4368656/3D.zip)
There are two models in the compressed package, one is not working properly and the other is modified.

**Comment by gailulun** [comment]
Fortunately, I have n’t cleaned the recycle bin.😂

**Comment by mahtDFR** [comment]
Thanks, I was able to reproduce it with the files you provided. Will discuss

**Comment by rburema** [comment]
Seems to happen in master, 4.0.0 and 3.2.1 as well, so it's not due to a recent fix/regression.

**Comment by rburema** [comment]
Though, if I check the model with the 'Mesh Tools' plugin (download from the Marketplace), I get the following:

![not_ok_model](https://user-images.githubusercontent.com/41987080/77432547-7f0dce80-6dde-11ea-838d-edd671aee57d.png)

We don't support models that aren't watertight or contain sub-meshes. Please adjust this in the modeller you are using.

**Comment by gailulun** [comment]
OK,i'll check it.
