### ISSUE TITLE
(Semi-)automated support generation

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#7332]
This is an advanced feature request...

It seems to me that it should be possible to calculate the weight of overhanging material and (assuming some parameters about the filament being used) calculate whether supports are needed and then add them either automatically (with / without approval / adjustment by the user) or even just indicate to the user where supports might be needed.

(Also Pathio Beta allows user to simply colour in the surface of the model to show where supports are needed and then autogenerate the supports.)

**Comment by fieldOfView** [comment]
See the "Generate Support" setting. This generates support automatically, based on a user-settable overhang angle. Cura also shows the areas of the model where supports sre needed in red.

**Comment by mahtDFR** [comment]
![image](https://user-images.githubusercontent.com/17821912/77318094-b9a73680-6d0c-11ea-80c7-512a63789419.png)

@Sophist-UK As above, check support settings in Custom mode.

Since the features you describe exist already, I'll close this off.

**Comment by Sophist-UK** [comment]
Fair enough.
