### ISSUE TITLE
Cura 4.5.0. no deja rotar.

### ISSUE THREAD

**Issue by newmagobe** [Ultimaker/Cura#7345]
Hola, la ultima version de cura solo me deja rotar las piezas con el circulo rojo, los circulos verde y azul no me deja realizar la rotacion, por lo que me genera problemas a la hora de poder colocar las piezas de manera que pueda imprimir a mi gusto.
Muchas gracias por su atencion,
un saludo.

**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by mahtDFR** [comment]
Generally we answer these in English. Can you try again and please save a project file (File -> Save...), zip up the .3mf file and attach to this issue so we can try to reproduce it.
