### ISSUE TITLE
only 8 extruders in cura ?...why ???

### ISSUE THREAD

**Issue by SpectroMaledikto** [Ultimaker/Cura#7346]
I'm making a 3d printer prototype with 10 extruders in 1.

I realized that but the maximum limit is 8 extruders in Cura Software.

How can configure for 10 extruders ?

Thank you

**Comment by fieldOfView** [comment]
You will have to make your own printer definitions (.def.json) with 10 extruder definitions.

**Comment by SpectroMaledikto** [comment]
I can't found the file...
I have created my custom printer in Cura...
The name is STACKMATT ... but no have config files in cura directories for this custom printer.

**Comment by fieldOfView** [comment]
Cura will not create .def.json files for you; you will have to create them for Cura. See https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
