### ISSUE TITLE
I cannot change the display language,even though I have restart Cura. 

### ISSUE THREAD

**Issue by civic220** [Ultimaker/Cura#7353]
<!--
Processing an issue will go much faster when this is filled out, and issues which do not use this template WILL BE REMOVED and no fix will be considered!

Before filing, PLEASE check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.

Also, please note the application version in the title of the issue. For example: "[3.2.1] Cannot connect to 3rd-party printer". Please do NOT write things like "Request:" or "[BUG]" in the title; this is what labels are for.

Thank you for using Cura!
-

**version**
the newest one

**Platform**
Windows10

**Printer**
ultimaker s5

**Reproduction steps**
1. change the display language in settings
2. close cura
3. restart cura by command line "python cura_app.py"

**Comment by mahtDFR** [comment]
The issue template you've posted isn't very helpful here. Have you changed the display language in settings?

**Comment by fieldOfView** [comment]
How do you run Cura, and on what platform? It may take additional steps to get the translations working if you run Cura from source.

**Comment by civic220** [comment]
> The issue template you've posted isn't very helpful here. Have you changed the display language in settings?



> The issue template you've posted isn't very helpful here. Have you changed the display language in settings?

thanks for reminding me. 

> How do you run Cura, and on what platform? It may take additional steps to get the translations working if you run Cura from source.

I run cura from source, use the command line "python cura_app.py"…The platform is windows10.

**Comment by civic220** [comment]
> The issue template you've posted isn't very helpful here. Have you changed the display language in settings?

I havw changed the display language in settings.However，it doesn't work.

**Comment by fieldOfView** [comment]
It would be my guess that your resources/i18n folder only contains .po files, and not the "compiled" .mo files. Those can be found here:
https://github.com/Ultimaker/cura-binary-data/tree/master/cura/resources/i18n

**Comment by civic220** [comment]
> It would be my guess that your resources/i18n folder only contains .po files, and not the "compiled" .mo files. Those can be found here:
> https://github.com/Ultimaker/cura-binary-data/tree/master/cura/resources/i18n

thanks a lot！
