### ISSUE TITLE
[3.6.0, 4.4.1] Strange Gui/High Contrast Error

### ISSUE THREAD

**Issue by FastSam** [Ultimaker/Cura#7357]
**Application version**
All tested versions, 3.6.0, 4.4.1, 4.0.0, 4.5.0

**Platform**
Windows 10 MSI laptop, running GTX 970

**Printer**
All, Ender 3, Creality CR-10

**Reproduction steps**
1. Set my computer to high-contrast mode
2. Nothing worked, even when I re-installed it the windows came up blank white. When I turned off high-contrast, everything went to normal.

**Screenshot(s)**
See the screencap in the zip file.

**Expected results**
Everything works normally, I can translate and rotate freehand, I can adjust sliders and actually do stuff.

**Actual results**
When I try to move anything or change anything in the main GUI or the sliders to the right, nothing happens. If I then click away to a drop-down menu, then the screen updates instead of as I change things.

**Project file**
Any .stl file I have.
[Cura Error.zip](https://github.com/Ultimaker/Cura/files/4390541/Cura.Error.zip)

**Comment by Ghostkeeper** [comment]
Can you try these instructions? https://github.com/Ultimaker/Cura/issues/5296#issuecomment-585120329

It looks like you might have a similar issue. It seems that Qt sometimes corrupts its shader cache and is then unable to draw some interface elements.
