### ISSUE TITLE
Improve "Fill Gaps Between Walls"

### ISSUE THREAD

**Issue by michcior2** [Ultimaker/Cura#7366]
**Is your feature request related to a problem? Please describe.**
Setting up the feature "Fill Gaps Between Walls" sometimes is necessary, because that's the only way to fill some areas:
![image](https://user-images.githubusercontent.com/55734517/77820874-d1eccc00-70e5-11ea-9012-3e1105cc20c6.png)

Unfortunately, it generates huge number of small particles, which waste a lot of time for travel, retract etc in some specific cases: sharp inner corners. See my case (file attached):
![image](https://user-images.githubusercontent.com/55734517/77820899-11b3b380-70e6-11ea-882e-7d9d9c7ee257.png)

**Describe the solution you'd like**
There is need for some kind "Filter small particles" or "Minimum extrusion length" etc.

[CFFFP_fillgapsissue.zip](https://github.com/Ultimaker/Cura/files/4396947/CFFFP_fillgapsissue.zip)

**Comment by smartavionics** [comment]
Until UM provide a better gap filling implementation (which is being worked on, I believe) you can use my Cura builds which do this differently and make a better job of it. You can find my builds at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. Please read the README.md file there before using.

**Comment by Ghostkeeper** [comment]
> There is need for some kind "Filter small particles" or "Minimum extrusion length" etc.

You mean [Filter Out Tiny Gaps](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/shell/filter_out_tiny_gaps.md)?
