### ISSUE TITLE
[master] buildvolume not displayed correctly

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#739]
Based on the codebase from yesterday I noticed this when opening Cura.
The buildvolume of the ```Ultimaker 2``` is shown correctly.

![cura_1](https://cloud.githubusercontent.com/assets/1847437/15267443/8d22ec36-19c2-11e6-83dd-409b8cf0f369.png)
![cura_2](https://cloud.githubusercontent.com/assets/1847437/15267444/91cfd0aa-19c2-11e6-8196-279ddcd8bbdc.png)

**Comment by fieldOfView** [comment]
Could it be related to https://github.com/Ultimaker/Cura/issues/717 ?

**Comment by thopiekar** [comment]
Seems so. The only difference is that the contour lines are not flickering anymore.

**Comment by thopiekar** [comment]
After a lot of time playing with the JSON file for my printer I couldn't find the reason there, but when removing ```~/.local/share/cura/*``` the problem just went away. Sorry, that I didn't made a backup of it to be able to debug it :disappointed:

**Comment by fieldOfView** [comment]
```
def on_new_issue(self, issue):
    if "buildvolume" in issue.subject and issue.printer.brand="bq" and issue.submitter == "topiekar":
        self._self_resolving_issues.append(issue)
        self.smile()
        return

    # \todo handle all other issues
```

**Comment by thopiekar** [comment]
The code says everything :smile:
