### ISSUE TITLE
segunda vez que arroja error, sw 3.4.1

### ISSUE THREAD

**Issue by guevaragus** [Ultimaker/Cura#7390]
es la segunda vez que el sw se corta informando que no puede continuar dando algún tipo de error, he perdido dos veces las piezas a imprimir, casi 30 metros de filamento ABS. mi OS es win 8.1

**Comment by rburema** [comment]
A couple of things of note before we can even begin determining what's wrong:

- Posting via github is more or less direct communication with the developers. As such, each time anything isn't in English, a lot of us have to rely on online translation. Please use English if possible.
- We mostly support the latest version (3.4.1 is almost 2 years old at this point). Does this error happen with 4.5.0 as well?
- We need specifics, _like in the template for example_ to tell us what's wrong. We wouldn't know where to even begin to look if it's just 'an error of some type'. Can you _at least_ tell us what the error said?
