### ISSUE TITLE
[4.5] Retract Continue PP Script Non-Functional

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7396]
4.5.0 / Win 10 / UMO

I suspected the "retract continue" post processing script wasn't working and made a simple test:

![image](https://user-images.githubusercontent.com/12439543/78299868-3059e600-74fc-11ea-8634-5225ef4da8ab.png)

Using this setup it is easy to look at retraction moves for increasing distances. The result is that they are all 2mm retraction moves, as defined in the print settings, and unaltered by the PP script.

**Comment by Ghostkeeper** [comment]
Indeed, I can reproduce this issue with 3 cubes on the build plate. It doesn't seem to do anything at all any more.

**Comment by Ghostkeeper** [comment]
I fixed this for 4.6, primarily here: https://github.com/Ultimaker/Cura/commit/9b997d421b25c1bfc56be7c68ba75fd8f6902653

This is one of those cases where I wonder how it could ever have worked, while I'm very sure that it did work at some point.

**Comment by CCS86** [comment]
Thank you for looking into this. 

I downloaded the updated script and tested it out. The script is now modifying retracts. At first it looked incorrect, but I think that is a bug when relative extrusion is enabled. I don't usually use that setting, but for quickly testing stuff like this it is helpful. 

Here is a side by side of relative vs absolute extrusion with 0.05 retract continue:

![image](https://user-images.githubusercontent.com/12439543/78945334-ae326a00-7a85-11ea-9910-5a1bfec92a7b.png)

**Comment by CCS86** [comment]
Seems that the new version creates a much bigger issue:

https://github.com/Ultimaker/Cura/issues/7458
