### ISSUE TITLE
Bed has islands you cannot print on

### ISSUE THREAD

**Issue by boatguy86** [Ultimaker/Cura#7397]
**Application version**
4.5

**Platform**
windows 10. nvidia mx250

**Printer**
ender 3

**Reproduction steps**
1. manually changed bed size to 400x400
2. nothing else was changed

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/52140226/78321739-cad91a00-753a-11ea-82f3-4945e57510eb.png)

**Actual results**
cannot place model in the shaded portions in the middle of the build plate without slicing being blocked

**Expected results**
i should be able to use my entire bed like i could in 4.3

**Additional information**
you should really implement some code that automatically ports over the profiles from the old version of cura before having the option to uninstall old versions first. i just lost all my profiles installing this new version and that is rather infuriating.

**Comment by mahtDFR** [comment]
> cannot place model in the shaded portions in the middle of the build plate without slicing being blocked

Please see the discussion here #7252 which gives details on why this change was made.

> you should really implement some code that automatically ports over the profiles from the old version of cura before having the option to uninstall old versions first

There are scripts in place that will port settings from previous versions. To be extra safe you can back up the contents of your userdata folder located in `%appdata%/roaming/cura/<cura-version>`

As this is a duplicate issue, I will close it.
