### ISSUE TITLE
Memory for Cura application window not cleared before window is displayed

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#74]
Application Version: 15.05.97
Platform: OS X 10.9.5
Video: Radeon HD 6xxx, Device ID: 0x6759

Steps to Reproduce:
Launch new Cura

Actual Results:
Application window shows previous contents of graphics memory used

Expected results:
Solid background while application finishes loading assets

**Comment by nallath** [comment]
Could you add a screenshot?

**Comment by Xisle** [comment]
![screen shot 2015-06-28 at 11 52 52 pm](https://cloud.githubusercontent.com/assets/12257213/8403404/dc8f80dc-1df0-11e5-914b-86b46e273449.png)

**Comment by Xisle** [comment]
![screen shot 2015-06-28 at 11 54 37 pm](https://cloud.githubusercontent.com/assets/12257213/8403435/2e33d712-1df1-11e5-9636-03fe30c9d5b7.png)

**Comment by Xisle** [comment]
I launched Cura twice to capture screenshots. The first time was right after closing it, the second time I waited 10 seconds and switched tasks a couple of times before reopening it (just to see the change).

**Comment by BagelOrb** [comment]
This is art! I like it! :P

**Comment by nallath** [comment]
Is this still an issue in the latest release?

**Comment by Xisle** [comment]
yes

**Comment by nallath** [comment]
It's already quite late in the process. The splashscreen is already in front of it, so is the plugin / machine loading. 
So far you've been the only one with this bug, so i think this is not a fundamental issue, but a very specific one to your system.

**Comment by Xisle** [comment]
Fair enough.

**Comment by nallath** [comment]
Does this happen on every startup or just every so often?

**Comment by Xisle** [comment]
Every startup.

This issue can definitely be put on low priority if no one else is experiencing it.

**Comment by awhiemstra** [comment]
Well, I have some ideas about improving this since the issue seems to be that the interface loading happens while the window is already shown. If we can delay showing the window until more stuff is loaded things might be better. I have also seen something similar on Windows, though it is only OSX where there is actual garbage in the window.

**Comment by Xisle** [comment]
Same on 15.09.8

**Comment by nallath** [comment]
Ugh :(

**Comment by Xisle** [comment]
No worries. Low priority.
