### ISSUE TITLE
Smarter zigzag infill pattern

### ISSUE THREAD

**Issue by men8ifr** [Ultimaker/Cura#7406]
**Is your feature request related to a problem? Please describe.**
it is very difficult to get infill patterns to work well in hollow objects e.g open box or bin with 2 walls etc 

**Describe the solution you'd like**
Have a zig zag mode so that the nozzle touches one wall, then moves to the other wall and does that all the time withe the lines at 45deg to the walls. This should result in fast, smooth printing of infill that is strong since the nozzle prints continuously, the nozzle does not go back on itself in one direction, it is always moving forward. 

**Describe alternatives you've considered**
Current zig zag or grid patterns, but you cannot tune them properly to get the pattern you want. 

**Affected users and/or printers**
Every-one that pronts hollow ojects with 2 walls and infill 

**Additional context**
(Add any other context or screenshots about the feature request here.)

![image](https://user-images.githubusercontent.com/63108610/78372382-1f26dd00-75c1-11ea-9ee6-c1e7f2e7a07b.png)

In this screenshot I use a grid infill but it is not possible to get a nice zig-zag between the walls, here the spahe is a cross, the printer has to reverse one direction to complete the infill and this adds a lot of time. 

Also note in the corner the default infill patterns  can add infill near the corner and this can cause print quality problems with too much filament building up here.

**Comment by Ghostkeeper** [comment]
This exists. It's called Connect Infill Lines. The [Settings Guide](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/zig_zaggify_infill.md) has some pictures and an explanation of how it works.

There's also an [alternative for patterns with closed loops](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/connect_infill_polygons.md) such as concentric infill or multiplied infill.
