### ISSUE TITLE
Why appeared margins for Y axis

### ISSUE THREAD

**Issue by VijitCoder** [Ultimaker/Cura#7408]
Probably it is not a bug. But I could figure out, what happened with Y axis. So..

**Application version**
Cura 4.5

**Platform**
KUbuntu 19.10

**Printer**
Creality Ender 3

**Reproduction steps**
Added a cube 235x10x10.

**Screenshot(s)**
Printer settings
![settings](https://user-images.githubusercontent.com/8523131/78394266-82425f00-7615-11ea-9471-1430b2092190.png)

Model size
![size](https://user-images.githubusercontent.com/8523131/78394269-83738c00-7615-11ea-9669-85d9c202ff0b.png)

Model position
![posion](https://user-images.githubusercontent.com/8523131/78394261-80789b80-7615-11ea-9f8f-406f80cb5da5.png)

**Actual results**
Strange margins appeared for the Y axis

**Expected results**
No margins.

**Comment by fieldOfView** [comment]
See https://github.com/Ultimaker/Cura/issues/7252

**Comment by VijitCoder** [comment]
Thanks.
