### ISSUE TITLE
Iron temperature

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#7410]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
A temperature setting for use during ironing.

I suspect (without any hard evidence) that ironing might benefit from a higher temperature in order to promote a clean smooth flow of filament.

**Describe alternatives you've considered**
None

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/4058.
