### ISSUE TITLE
Spanish translate

### ISSUE THREAD

**Issue by cherokykyky** [Ultimaker/Cura#7422]
![image](https://user-images.githubusercontent.com/63082970/78510456-7da4b480-7795-11ea-81e0-b60527543ed2.png)

**Comment by Ghostkeeper** [comment]
Thanks! I fixed it for release 4.7. To fix it for release 4.6 is a bit difficult since the translators have the translation files at the moment and we copy-paste those back into our source code, which would erase my change again.
