### ISSUE TITLE
Vertical/horisontal filp.

### ISSUE THREAD

**Issue by krsshtx** [Ultimaker/Cura#7424]
Hi!

Would suggest these 2 buttons in "rotate" row.

(tired rotating with mouse)

**Comment by nallath** [comment]
You mean like the mirror tool?

**Comment by krsshtx** [comment]
gimp-like rotate 180 degree 
- change top with bottom (Z flip)
- change front with back (X flip)

rotate 90 deg is also useful
- rotate 90 deg by X
- rotate 90 deg by Y

> You mean like the mirror tool?

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/6404.
