### ISSUE TITLE
Printer setting display

### ISSUE THREAD

**Issue by Ender3Nya** [Ultimaker/Cura#7427]
Does anyone know how to fix the number display shifted to the top?
![Number shifted to the top](https://user-images.githubusercontent.com/63229069/78537020-c148fe00-7829-11ea-8c2c-6bac66dbc6f9.jpg)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7300

There is some weirdness going on in this screen with things not properly scaling with the font size. I've seen it before. It's probably due to the window being a mix of system-styled elements and Cura-styled elements.
