### ISSUE TITLE
error G-code, stop the machine in midle

### ISSUE THREAD

**Issue by Dragon3DPrinter** [Ultimaker/Cura#7430]
![image](https://user-images.githubusercontent.com/13982996/78559037-f64a5600-7813-11ea-9318-4462cd63b0dc.png)
![image](https://user-images.githubusercontent.com/13982996/78559377-90aa9980-7814-11ea-84b2-69b48869dcf8.png)

[rueda_cajon_cocina.zip](https://github.com/Ultimaker/Cura/files/4438429/rueda_cajon_cocina.zip)

**Comment by mahtDFR** [comment]
Hello, can you please fill out the issue template that you deleted so we can understand the issue and try to help?

**Comment by nallath** [comment]
Also, I don't see what is wrong with that g-code. It's a travel move and your machine should be capable of handling those.

**Comment by Dragon3DPrinter** [comment]
> Hola, ¿puede completar la plantilla de problema que eliminó para que podamos entender el problema e intentar ayudarlo?

Printing starts and suddenly stops at the first layer without turning off motors or changing temperatures, so I assume the error is from the slicer.

Sorry I deleted the template

**Comment by Dragon3DPrinter** [comment]
> Además, no veo lo que está mal con ese código g. Es un movimiento de viaje y su máquina debería ser capaz de manejarlos.

I think I cannot guarantee with certainty that the printers always work with code G1 work and not G0 translation.

**Comment by Ghostkeeper** [comment]
If your printer doesn't support the `G0` command, I suggest switching the g-code flavour to "Bits from Bytes":

![image](https://user-images.githubusercontent.com/2448634/78796871-3bf35400-79b7-11ea-85ef-f2ab68a5b687.png)
