### ISSUE TITLE
Cura 4.5 appears top have problem processing JPG files if "Base" is greater than "Height" 

### ISSUE THREAD

**Issue by CluelessNewB** [Ultimaker/Cura#7445]
**Application Version**
4.5

**Platform**
Windows 10

**Printer**
Creality CR-10S 

**Reproduction steps**
There appears to be a bug processing jpg files.    If I load a jpg file and leave all of the settings as the defaults it seems to behave as expected.  If I change  the value for "Base" to something that is larger than the value for "Height" it appears to get really confused.   This works fine in Cura 4.4.1.  This problem appears before slicing.  

 
**Screenshot(s)**
This is with the default settings (height =2.5 base=0.4, darker is higher) it  looks ok:  
![Cura4 5defaults](https://user-images.githubusercontent.com/10787798/78705439-78518200-78db-11ea-8906-fb666820c72b.PNG)

This with height =2.5 and base=20.0, darker is higher) it appears really confused:
![Cura4 5_base20](https://user-images.githubusercontent.com/10787798/78705621-bf3f7780-78db-11ea-9603-7ccf3142dfdd.PNG)
 
This is using Cura 4.4.1 height = 2.5 and base =20.0 darker is higher and appears to be correct:

![Cura4 4 1_base20](https://user-images.githubusercontent.com/10787798/78705818-0fb6d500-78dc-11ea-86bb-17c038793512.PNG)

**Actual results**
Please see examples above, Cura 4.4.1 processes jpg correctly, Cura 4.5 does not.  This is repeatable with any black and white JPG file.  

**Expected results**
I would expect to see the characters to be raised above the base not below.  

**Project file**
This is the JPG file I have been using but any black and white JPG appears to have the same problem: 
![sake01_kanji_reversed](https://user-images.githubusercontent.com/10787798/78706346-e6e30f80-78dc-11ea-940f-b2c011a34aaa.jpg)

**Log file**
N/A

**Additional information**
N/A

**Comment by CluelessNewB** [comment]
This bug still exists in Cura 4.6.1

**Comment by Ghostkeeper** [comment]
Yeah, we didn't get around to it. One of our developers said he'd take a look if he could make a small fix but had to do stuff for the 4.6 release first. And then when that was done I think he forgot this. I'll prod him again.

**Comment by CluelessNewB** [comment]
4.8 still has problems importing jpg & png files although behavior is different.  There still seems to be some confusion, it appears to add base ok but the jpg object itself is too high.  For example if I set the base at 20mm and the height as 5mm I would expect the overall height to be base+height (25mm)0.   What I get is 45mm 2 x base + height.

**Comment by rburema** [comment]
Seems to be fixed in the current main branch (which is going in 4.9), versus 4.8.

![solved_bug_img_read](https://user-images.githubusercontent.com/41987080/107030941-b0eb1200-67b1-11eb-801c-29deee798983.png)

As such, I'm closing this ticket. Sorry it took so long to resolve.
