### ISSUE TITLE
Bug slice hole

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#7449]
Cura 4.5 (Cura 4.6) Windows 10 x64 has the error also. Not correct slice some hole in the model. 
![Cura not correct slice](https://user-images.githubusercontent.com/22872748/78791368-74dff880-79b8-11ea-9c83-5e735078c6a8.jpg)
[CFFFP_mainsail_entry_NEW_long_PRINT_1(3).zip](https://github.com/Ultimaker/Cura/files/4450822/CFFFP_mainsail_entry_NEW_long_PRINT_1.3.zip)

**Comment by smartavionics** [comment]
Please provide the project file (File -> Save, rename or zip .3mf) or at lease the STL so we can check the model(s). Thanks.

**Comment by userosos** [comment]
> 
> 
> Please provide the project file (File -> Save, rename or zip .3mf) or at lease the STL so we can check the model(s). Thanks.

I checked the models it not work.

**Comment by smartavionics** [comment]
> I checked the models it not work.

OK, if you don't want to supply any more info, I am not bothering to respond to this issue any more, goodbye.

**Comment by userosos** [comment]
> OK, if you don't want to supply any more info, I am not bothering to respond to this issue any more, goodbye.

I think that i not understend you. I mean that i add 3mf file in the first message. I repeat now again.
[CFFFP_mainsail_entry_NEW_long_PRINT_1(3).zip](https://github.com/Ultimaker/Cura/files/4451458/CFFFP_mainsail_entry_NEW_long_PRINT_1.3.zip)

**Comment by Ghostkeeper** [comment]
That's a .gcode file, not the project file (.3mf).

**Comment by userosos** [comment]
@Ghostkeeper I apologize for my stupidity
[CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)

**Comment by eskeyaar** [comment]
> 
> 
> @Ghostkeeper I apologize for my stupidity
> [CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)

still its a gcode, not a 3mf project file.

**Comment by eskeyaar** [comment]
> 
> 
> @Ghostkeeper I apologize for my stupidity
> [CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)

still its a gcode, not a 3mf project file.

**Comment by userosos** [comment]
> 
> 
> > @Ghostkeeper I apologize for my stupidity
> > [CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)
> 
> still its a gcode, not a 3mf project file.

Oh sorry. I think that i zipped 3mf file.
[CFFFP_EPSILON_113_ins_end_simple_part2.zip](https://github.com/Ultimaker/Cura/files/4458552/CFFFP_EPSILON_113_ins_end_simple_part2.zip)

**Comment by eskeyaar** [comment]
> 
> 
> > > @Ghostkeeper I apologize for my stupidity
> > > [CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)
> > 
> > 
> > still its a gcode, not a 3mf project file.
> 
> Oh sorry. I think that i zipped 3mf file.
> [CFFFP_EPSILON_113_ins_end_simple_part2.zip](https://github.com/Ultimaker/Cura/files/4458552/CFFFP_EPSILON_113_ins_end_simple_part2.zip)

The model looks good only. what issue are you facing? you mean the hole is small? if so then change in desgin. Everything looks ok in the preview.

**Comment by userosos** [comment]
> 
> 
> > > > @Ghostkeeper I apologize for my stupidity
> > > > [CFFFP_EPSILON_113_ins_end_simple_part2 GREG PETg lw 0.4mm lh 0.2mm if 30% ext1 210C bed 60C.gcode.zip](https://github.com/Ultimaker/Cura/files/4458142/CFFFP_EPSILON_113_ins_end_simple_part2.GREG.PETg.lw.0.4mm.lh.0.2mm.if.30.ext1.210C.bed.60C.gcode.zip)
> > > 
> > > 
> > > still its a gcode, not a 3mf project file.
> > 
> > 
> > Oh sorry. I think that i zipped 3mf file.
> > [CFFFP_EPSILON_113_ins_end_simple_part2.zip](https://github.com/Ultimaker/Cura/files/4458552/CFFFP_EPSILON_113_ins_end_simple_part2.zip)
> 
> The model looks good only. what issue are you facing? Do you mean the hole is small? if so then change in design. Everything looks ok in the preview.
> ![image](https://user-images.githubusercontent.com/6142521/78983368-ff8d3880-7b1b-11ea-9d18-3cb5de7aa815.png)
May be. Prusaslicer work is Ok. The model not from me. I checked the mode

**Comment by Ghostkeeper** [comment]
The model does have a hole there.
![image](https://user-images.githubusercontent.com/2448634/79221545-4cdc1380-7e56-11ea-8815-8ad763032606.png)

What's wrong with the hole, exactly? Could you fill in the issue template? What is the expected behaviour and what is the behaviour that you're seeing?
