### ISSUE TITLE
Cura 4.5 not getting connected with USB for Anycubic Kossel Plus (deltabot)

### ISSUE THREAD

**Issue by fredkimu** [Ultimaker/Cura#7454]
Dear all,

I have a problem connecting Cura 4.5 with Anycubic Kossel Plus through cable USB both on Mac and Window version. Is there a way to solve this?

I don't know much about coding.....Thank you!

**Comment by eskeyaar** [comment]
Did you download the latest drivers for that machine? 

https://www.anycubic.com/collections/3d-printers/products/anycubic-kossel-3d-printer

**Comment by fredkimu** [comment]
> Did you download the latest drivers for that machine?
> 
> https://www.anycubic.com/collections/3d-printers/products/anycubic-kossel-3d-printer

it
