### ISSUE TITLE
Changing setting in Cura (Advanced Setup) leads to wrong material choice

### ISSUE THREAD

**Issue by Stefan001Sch** [Ultimaker/Cura#7455]
When chaning the setting (especially Adhesion Plate, Dual Extrusion), the software is visualizing incorrect materials (almost every time on all my machines). The materials in the menu are set and listed correctly however.

**Comment by nallath** [comment]
I don't understand what you mean. Could you make a screenshot of what settings aren't changing according to you? (and describe what you would expect them to be)
