### ISSUE TITLE
Cura GUI Graphical Issues

### ISSUE THREAD

**Issue by Linkeb3** [Ultimaker/Cura#7459]
**Application version**
(The version of the application this issue occurs with.)
4.5.0

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

Manjaro

**Printer**
(Which printer was selected in Cura?)
Ender3

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)
Open cura

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![cura_fail](https://user-images.githubusercontent.com/53415225/78961215-beb30680-7abe-11ea-8032-1549e90be916.png)

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)
the GUI works?

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
won't open

**Additional information**
(Extra information relevant to the issue.)
This problem is on the AUR as well.

**Comment by nallath** [comment]
Did you use the appimage?

**Comment by Linkeb3** [comment]
I did not, I’m unfamiliar with appimage.

**Comment by nallath** [comment]
Well, the packages provided by some Linux distros have different versions of Qt (the graphical framework that we use). This is known to cause all kinds of issues, including the one that you seem to have. 

Since we don't maintain these packages (and only the appimage) we only give support for the appimage.

**Comment by Linkeb3** [comment]
I’ll look into it, thanks for the reply

**Comment by rburema** [comment]
The appimage can be downloaded from [here](https://github.com/Ultimaker/Cura/releases). (Scroll down if you want a final instead of a beta.)

**Comment by MaxVerevkin** [comment]
try this
env -u DESKTOP_SESSION -u KDE_FULL_SESSION -u XDG_CURRENT_DESKTOP /bin/cura
