### ISSUE TITLE
M105 commands on Raise3D N2 Printer

### ISSUE THREAD

**Issue by puerlin** [Ultimaker/Cura#7460]
**Application version**
4.4.0

**Platform**
MAC

**Printer**
Raise3D N2 Dual

**Reproduction steps**
1. Every gcode output

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
My printer pauses indefinitely

**Expected results**
My printer should start printing

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
Well, [`M105` is a valid part of Marlin](https://marlinfw.org/docs/gcode/M105.html) and the Raise3D N2 Dual is supposed to use the Marlin-flavour of g-code [according to a reply from a member of their staff on their forum](https://forum.raise3d.com/viewtopic.php?t=6600).

It's considered such a safe command, that we even send it to USB devices to see if a printer is connected.

Is the firmware on the printer up to date? If not, please raise this issue with them (pun not originally intended, but hopefully appreciated nonetheless).
