### ISSUE TITLE
2.1.1: Slicing continues after undo loading an stl

### ISSUE THREAD

**Issue by nilrog** [Ultimaker/Cura#748]
Cura 2.1.1 on Win7 x86_64.

If you load an stl in Cura it will start slicing the model. If you then press "undo" so that the object is removed from the build plate, Cura will continue to slice the model. Expected behavior is that Cura will stop slicing since there is nothing to slice. If you right-click and select "clear build platform" this does not happen.
1. Load a model
2. Press Ctrl-Z (undo)
3. Watch Cura continuing slicing, but there is no longer any model visible.

When slicing is done it also says that you can now save the gcode. And you can view the model in layer mode. Even though the build plate is empty.

**Comment by nallath** [comment]
This seems to have been fixed in the meantime.
