### ISSUE TITLE
[master] signing in causes cura to use 100% CPU

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#7482]
**Application version**
master branches as of 12th April 2020

**Platform**
Linux

**Printer**

Creality

**Reproduction steps**
Sign in to account.

**Screenshot(s)**

**Actual results**
Sign in appears to happen but then Cura continues to run at 100% CPU (1 core busy) forever.

**Expected results**
After doing the sign in, Cura should slumber as per normal.

**Project file**

**Log file**

**Additional information**
Couldn't see any obvious error/warning messages that related to sign in from either stderr or cura.log.

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this so far.
![image](https://user-images.githubusercontent.com/2448634/79878415-ae1f5c00-83ed-11ea-9fcb-70f441fe5edd.png)

I guess we'll have to keep an eye out for it. If we know how to reproduce the issue we can run a profiler on it to see what it's busy doing.

**Comment by smartavionics** [comment]
Here's some profile data...

[yappiProfile.zip](https://github.com/Ultimaker/Cura/files/4511541/yappiProfile.zip)

![Screenshot_2020-04-21_18-23-32](https://user-images.githubusercontent.com/585618/79894354-3c4f0e80-83fd-11ea-940c-211df543b71d.png)

**Comment by Ghostkeeper** [comment]
Hmm, the `_handle_request_noblock` is not a function of ours. We're not calling it directly. Neither `get_request` or `process_request`. Seems that something froze in the webserver that's waiting for a response from the login form, maybe?

**Comment by nallath** [comment]
We quite recently fixed this (so after signing in, it didn't close the signing in server correctly)
