### ISSUE TITLE
Postprocessing script disappears

### ISSUE THREAD

**Issue by Vallerik** [Ultimaker/Cura#7485]
Hello, I want to change the script from the CURA section "Post-processing, change g code". Location scripts are: C:\Program Files\Ultimaker Cura 4.5\plugins\PostProcessingPlugin\scripts
The problem is that after my changes the script ceases to be displayed in the CURA program.
I know a little programming and understand what I edit and what I do. I take a ready-made script (working) as a basis and, by analogy, edit it. The script is simple, it adds a certain G code after each layer you have written, I just want to add a few more lines of G code. But after I add at least one line of code, the script stops appearing in the program. I don’t understand why this is happening and what I am doing wrong.
I conducted a lot of experiments, tried to understand what the problem was, but I could not find an answer. I thought it was a conflict of names or variables, no, it’s not.

**Application version**
CURA 4.4 and 4.5

**Platform**
Win 7 64x, marlin

**Printer**
Tevo Tornado

**Reproduction steps**
1. Step one shows the source script and the fact that the script is running in the program
![1](https://user-images.githubusercontent.com/31063731/79078077-94f01e80-7d0e-11ea-8ba4-573ce456f324.png)
![2](https://user-images.githubusercontent.com/31063731/79078078-96b9e200-7d0e-11ea-89b6-664de609e3d5.png)

2.Step two, I add another line from the script. (If you do not add and replace one line, then everything works)
After this I go into the program and there is no script
![3](https://user-images.githubusercontent.com/31063731/79078080-97527880-7d0e-11ea-950b-ec4addae5cd5.png)
![4](https://user-images.githubusercontent.com/31063731/79078081-97eb0f00-7d0e-11ea-8960-492464214350.png)

**Expected results**
I need you to tell me how to deal with this nonsense. If something I’m doing wrong, please explain how to do it correctly, there are no complicated algorithms.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4466947/cura.log)

**Comment by rburema** [comment]
Just as I thought. Python has some nasty whitespace rules (don't ask me, I didn't make them) set your notepad++ to convert tabs to spaces and run again.

From the logs:
> 2020-04-12 22:46:48,687 - ERROR - [MainThread] UM.Logger.logException [98]: Exception: Exception occurred while loading post processing plugin: inconsistent use of tabs and spaces in indentation (TimeLapse.py, line 86)

You can also slightly rename the script and copy it over to `%appdata%/cura/<version>/scripts/.` if you want to keep the original scripts. (I'd recommend this, because then error reports make sense to us, instead of having a strange version that has all kinds of user-changes.)
