### ISSUE TITLE
Cura 2.1.1 placing / rotating models might cause endless model translation 

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#749]
Hi, while trying to slice http://www.thingiverse.com/thing:584714 cure got confused and endlessly tries to position the model inside the build chamber. This process of positioning and repositioning might have 3 endings.
1. after a couple of repositioning sequences cura stops and the model is off screen 
2. after a couple of repositioning sequences cura stops and the model is on the build plate
3. cura never stops and the positions oscillates between two incorrect positions.

have a look at https://youtu.be/isWzPVfWhvY for case 2 and 3

**Comment by Ghostkeeper** [comment]
Hmm, something seems up with the bounding box calculations...

**Comment by mokusolo** [comment]
Would you please tell me how you optimize this?
I haven't met this problem with Cura 2.3.Maybe you've revised it?
My friend used to try to read stl file and show view with vc. He has the problem too. It just run everywhere.

**Comment by Ghostkeeper** [comment]
We had fixes in 2.3.0 that revised this code thoroughly. Then we also had fixes in 2.4.0 that tweaked it a bit further. We don't seem to have this problem in 2.4 any more, or I haven't seen it yet anyway.

We also have a research project going on to see if we can make the platform collision completely anew (for the better) with an actual physics engine.

**Comment by nallath** [comment]
This is no longer an issue.
