### ISSUE TITLE
Slicer is filling in holes

### ISSUE THREAD

**Issue by men8ifr** [Ultimaker/Cura#7506]
[CCR10_half monitor mount.zip](https://github.com/Ultimaker/Cura/files/4480352/CCR10_half.monitor.mount.zip)

**Application version**
4.5

**Platform**
Win 10 Core I7 Geoforce GTX

**Printer**
CR10

**Reproduction steps**
1. Made a simple model in Fusion
2. Slice it 

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/63108610/79322732-232df580-7f05-11ea-987f-e79e73a39a4f.png)

![image](https://user-images.githubusercontent.com/63108610/79322791-3771f280-7f05-11ea-99ed-37f451759714.png)

**Actual results**
Cura fills the holes in - it should not

**Expected results**
The sliced model should have a hole through it - as per the STL

**Project file**
Zip file Should be uploaded 

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues
[cura.log](https://github.com/Ultimaker/Cura/files/4480409/cura.log)
 to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
There seem to be quite a few similar issues with no clear resolution I can see, if it's related to my settings it doesn't seem obvious

**Comment by men8ifr** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/4480469/cura.log)

**Comment by nallath** [comment]
I'm still investigating a bit more, but your model doesn't seem to have any issues with it (my first guess was that it was non-manifold). But when resetting all the settings to default, it does print the holes correctly.

**Comment by nallath** [comment]
Ah! Found it! You had "Make Overhang Printable" enabled. So it's to be expected that this happens.

**Comment by men8ifr** [comment]
Many thanks. How did you compare my profile to the standard? Maybe that is a good way to debug other issues in the future. It is easy to get lost in the many options available under all the settings.

**Comment by Ghostkeeper** [comment]
It lists the changes in a profile when you open the profile manager (the last page of the Preferences screen) and select the profile you want to view.
