### ISSUE TITLE
Infill Line Distance should not be shown if Infill Density is 0%

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#7514]
**Application version**
4.5.0

**Platform**
Windows

**Printer**
N/A

**Reproduction steps**
1. Set Infill Density to 10%. Infill settings show.
2. Set Infill Density to 0%. Most infill settings hide except Infill Line Distance.

**Actual results**
Infill Line DIstance is still shown.

**Expected results**
Infill Line Distance is hidden.

**Comment by Ghostkeeper** [comment]
This is intended. Infill Line Distance overrides Infill Density. In fact, I pretty much see them as the same setting except that they are different units, or different ways of looking at it.
