### ISSUE TITLE
[4.5.0] brim not printed in one of a two object stl file.

### ISSUE THREAD

**Issue by Fedonecchia** [Ultimaker/Cura#7522]
**Application version**
4.5.0
**Platform**
macOS Catalina (10.15.2)

**Printer**
Anet A8

**Reproduction steps**
1 imported an stl file consisting of two objects spaced out by a few millimiters.
2 sliced and exported gcode
3 looked at printer
4 looked at preview's first layer

**Screenshot(s)**
<img width="770" alt="Schermata 2020-04-17 alle 12 51 39" src="https://user-images.githubusercontent.com/30243154/79562098-bfddc800-80aa-11ea-8a60-051a4691e3bb.png">

<img width="813" alt="Schermata 2020-04-17 alle 12 51 33" src="https://user-images.githubusercontent.com/30243154/79562128-cb30f380-80aa-11ea-9a1c-7dbeecccf536.png">

**Actual results**
spaghetti
![photo_2020-04-17_12-59-00](https://user-images.githubusercontent.com/30243154/79562366-45617800-80ab-11ea-9240-4df3a3efe21a.jpg)

**Expected results**
prints brim on both structures

**Project file**
[simple box v0.stl.zip](https://github.com/Ultimaker/Cura/files/4492523/simple.box.v0.stl.zip)

**Additional information**
I had tree supports on, only on the buildplate. Don't know if that's relevant.
Also, when I imported the same objects as separate stl files the brim was there and the print went fine.

**Comment by smartavionics** [comment]
it's because when you rotate the model to that orientation what are now the bottom surfaces are not at the same height. You have to sink the model into the buildplate to ensure that both bottom surfaces intersect with the buildplate.

![Screenshot_2020-04-17_12-41-26](https://user-images.githubusercontent.com/585618/79565593-f286c100-80a8-11ea-9706-d0e2ca8c18c6.png)

**Comment by Fedonecchia** [comment]
Thanks a lot! do I need to mark the issue as closed or something?
fedo

Il ven 17 apr 2020, 13:43 Mark Burton <notifications@github.com> ha scritto:
