### ISSUE TITLE
[4.5.0] Profiles section in Settings window doesn't show differences to active profile anymore

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#7530]
< !--
Processing an issue will go much faster when this is filled out, and issues which do not use this template WILL BE REMOVED and no fix will be considered!
-->
I love you, too.

**Application version**
4.5.0

**Platform**
Windows 10, Nvidia GeForce GTX 1050

**Printer**
Custom Profile

**Reproduction steps**
1. Select some profile in the drop down
2. Open the drop-down again and select Manage Profiles...
3. select another profile in the now open window

**Screenshot(s)**
![Screenshot](https://user-images.githubusercontent.com/43012099/79691313-12f87c00-825f-11ea-92a7-7b0c67d9bc0d.PNG)

**Actual results**
The Extruder tab is empty.

**Expected results**
I expect to see the differences of the selected profile compared to the active profile as it was in Cura 3.6.0

**Additional information**
I just switched from Cura 3.6.0 to Cura 4.5.0.

**Comment by Ghostkeeper** [comment]
Yeah, I could reproduce this issue. It seems to be specific to per-extruder settings.

**Comment by Vandrasc** [comment]
Devs see CURA-7392 for reference.
