### ISSUE TITLE
Cura 4.5 slicing off center

### ISSUE THREAD

**Issue by Silversurfer79** [Ultimaker/Cura#7532]
Can any tell me why Cura 4.5 is doing this and how to resolve this issue please? 
![ScreenClip](https://user-images.githubusercontent.com/58236890/79697157-0b45d100-8279-11ea-88f4-1b9532dcdbe8.png)

If I slice with Cura 4.4.1 its perfect.
![ScreenClip](https://user-images.githubusercontent.com/58236890/79697171-1f89ce00-8279-11ea-8a2e-b40468060dea.png)

It seems that the start G Code has changed, and which U have update and has made now difference. 
![ScreenClip](https://user-images.githubusercontent.com/58236890/79697263-9a52e900-8279-11ea-817e-708e5a02e037.png)

Sorry if this has already been posted and thanks for the help.

**Comment by fieldOfView** [comment]
It looks like you have selected the “Origin at Center” setting in the Machine Settings, which should only be selected for delta-style printers.

**Comment by Silversurfer79** [comment]
> 
> 
> It looks like you have selected the “Origin at Center” setting in the Machine Settings, which should only be selected for delta-style printers.

Thats it thanks! Have a good reset of your day ;-) Stoked!
