### ISSUE TITLE
Multi-monitor setup on Windows 10 causes odd resolution change

### ISSUE THREAD

**Issue by ScruffR** [Ultimaker/Cura#7540]
I'm using v4.6.0 beta on Win10 Pro 64bit on MS Surface Pro 2017 with a secondary monitor 1920x1200 21".
When I move the Cura window from my primary tablet screen (2736x1824 12.3" - Windows scaling factor 200%) to the secondary screen (100% scaling) the resolution of the window rather unwieldy. 
The font size and all static objects become massive leaving next to no space for the actual work area.

Primary screen
![image](https://user-images.githubusercontent.com/6604878/79755583-a7271980-8319-11ea-873f-41c1c46737fb.png)

Secondary Screen
![image](https://user-images.githubusercontent.com/6604878/79755743-dfc6f300-8319-11ea-9ddb-071bc1e443d5.png)

In both cases the screenshot shows the full screen.

While moving the window over from primary to secondary, the resolution seems fine, but as soon the _majority_ of the window is on the secondary screen, the re-scaling kicks in and messes things up.

**Comment by Ghostkeeper** [comment]
I think you're running into this open Qt bug: https://bugreports.qt.io/browse/QTBUG-65805

Is it better when restarting Cura after moving it to the second screen?
