### ISSUE TITLE
Cura 4.5.0 - slicing removes part of model

### ISSUE THREAD

**Issue by CaptainDario** [Ultimaker/Cura#7542]
**Application version**
Cura 4.5.0

**Platform**
Windows 10 Pro 
AMD Rx 560

**Printer**
Creality CR 10S Pro

**Reproduction steps**
1. open the "toolholder.stl"
2. rotate it 45 degrees so that it looks like on the screenshot

**Screenshot(s)**
![toolholder_blender](https://user-images.githubusercontent.com/51273483/79789439-7a3f2a80-834a-11ea-8c72-aec1d16f014c.PNG)
![toolholder_bug](https://user-images.githubusercontent.com/51273483/79789450-7c08ee00-834a-11ea-86dc-7abb9a791726.PNG)

[CCR10SPRO_CR_10S_pro_tool_holder_v2.zip](https://github.com/Ultimaker/Cura/files/4505592/CCR10SPRO_CR_10S_pro_tool_holder_v2.zip)

**Actual results**
The backside of the toolholder gets removed.

**Expected results**
The backside is still there.

**Project file**
projet is attached as a zip as well as the .stl file
[CR_10S_pro_tool_holder_v2.zip](https://github.com/Ultimaker/Cura/files/4505597/CR_10S_pro_tool_holder_v2.zip)
[CCR10SPRO_CR_10S_pro_tool_holder_v2.zip](https://github.com/Ultimaker/Cura/files/4505597/CCR10SPRO_CR_10S_pro_tool_holder_v2.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4505577/cura.log)

**Additional information**
 The issue is a little hard to put in words but the images from Blender to Cura show the issue quite nicely I guess.

**Comment by smartavionics** [comment]
The model has problems...

![Screenshot_2020-04-20_21-44-54](https://user-images.githubusercontent.com/585618/79798020-39e2ab00-8350-11ea-9d29-79aeb2322f45.png)

**Comment by CaptainDario** [comment]
Okay, than I am sorry for opening this.

Why do I not get this "Model Errors" notifications?
Is there a place where I can enable this

**Comment by smartavionics** [comment]
The model errors message is by a new cura feature that isn't yet available in a release.

The mesh tools message which really tells you the same thing is available in the mesh tools plugin from the marketplace.

**Comment by CaptainDario** [comment]
Thank you very much for your help and time.
