### ISSUE TITLE
Cura default profile for Anycubic Chiron

### ISSUE THREAD

**Issue by moosehaed** [Ultimaker/Cura#7543]
Cura mistakenly has the part cooling initial fan set to 100% instead of 0% as it should be.

 

**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
I don't think this was a mistake. It's written down quite deliberately in the [quality profiles](https://github.com/Ultimaker/Cura/blob/a0dc78cb391272d69f3d16e4954ce8854a60fd89/resources/quality/anycubic_chiron/anycubic_chiron_normal.inst.cfg#L21).

@BluefireXD do you know why the initial layer fan speed is set to 100%?
