### ISSUE TITLE
Ender3 Pro Profile Nozzle missing

### ISSUE THREAD

**Issue by Strahler85** [Ultimaker/Cura#7550]
**Application version**
4.6

**Platform**
Windows 10 64Bit

**Printer**
Ender3 Pro

**Reproduction steps**
Create new printer Ender3 Pro

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/49564229/79882415-de1d2e00-83f2-11ea-90b2-6c60efc264d1.png)

**Actual results**
No Nozzle Size

**Expected results**
Nozzle Size selectable

**Comment by jerryfudd** [comment]
+watching

**Comment by spacecraft1013** [comment]
I have the same issue, same printer

**Comment by andyscriv** [comment]
Same issue as well, no nozzle size selection :(

**Comment by jerryfudd** [comment]
I don't believe the Pro profile is going to be any different to that of the Ender 3

**Comment by benjareuland200** [comment]
Same issue too

**Comment by Strahler85** [comment]
Found the issue, in \resources\variants there are no ender3pro files

If you copy these files in this folder than it should work
[ender3pro_variants.zip](https://github.com/Ultimaker/Cura/files/4516778/ender3pro_variants.zip)

**Comment by andyscriv** [comment]
> Found the issue, in \resources\variants there are no ender3pro files
> 
> If you copy these files in this folder than it should work
> [ender3pro_variants.zip](https://github.com/Ultimaker/Cura/files/4516778/ender3pro_variants.zip)

Awsome sauce! 
Thanks for that :)

**Comment by Ghostkeeper** [comment]
Thanks for the solution. That was indeed wrong. Normally we check that sort of thing before merging. It must have been an oversight (I think I was the one that merged it in this case actually...)

I've tested and added your profiles for the next release. They contain no setting overrides, but it's better than nothing I guess and the quality profiles for the Ender printers are sufficiently well designed to give decent defaults nonetheless.

See https://github.com/Ultimaker/Cura/commit/83adb98a5f3c9a51ec71bf3a8bdd41c27273fbc5.

**Comment by uyesercan** [comment]
> Found the issue, in \resources\variants there are no ender3pro files
> 
> If you copy these files in this folder than it should work
> [ender3pro_variants.zip](https://github.com/Ultimaker/Cura/files/4516778/ender3pro_variants.zip)

Working very well. Thanks for solution.

**Comment by Ghostkeeper** [comment]
We're probably creating a 4.6.1 release to fix a bug with the Z seam placement. We've decided to merge this fix into that as well, since it's relatively low-risk and seems to be high value based on issue reports.

**Comment by hpandelo** [comment]
I can't see this menu for Anet A8 Plus.. Expected??

**Comment by Ghostkeeper** [comment]
Yes, the Anet A8 Plus doesn't have any nozzle profiles to choose from. You need to adjust the settings yourself if you have a different nozzle than the standard one.

**Comment by maludwig** [comment]
To those who are on a version later than 4.6 and are still experiencing this issue, I bet you're expecting that under:
Settings -> Manage Printers -> Machine Settings -> Extruder, you'll have a nozzle size.

This is not where it is. You're in the wrong spot. I feel stupid cuz this whole time I've been looking there, meanwhile, dead center of the screen it's been clearly displaying "Generic PLA - 0.4mm Nozzle", not under any setting or anything. It's just right there, just to the left of all your other print settings.

I feel dumb.
