### ISSUE TITLE
[4.6] All my custom Print settings and Material profiles disappeared

### ISSUE THREAD

**Issue by Mosher23** [Ultimaker/Cura#7554]
All my custom prinst settings and Material profiles disappeared after update from 4.5 to 4.6

**Application version**
4.6

**Platform**
Mac OS 10.15.4

**Reproduction steps**
1. update from 4.5 to 4.6
2.  custom profile disappeared

**Comment by nallath** [comment]
Please provide logs. There is nothing we can do to fix the issue without logs.

**Comment by Ghostkeeper** [comment]
> All my custom prinst settings and Material profiles disappeared after update from 4.5 to 4.6

Mine didn't! Can't reproduce this so far.

**Comment by Sophist-UK** [comment]
When I installed 4.6 it installed in a separate directory to 4.5 and I also had to copy profiles across by exporting them from 4.5 and importing them into 4.6.
