### ISSUE TITLE
Top/Bottom Layer count miscalculated

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#7563]
**Application version**
4.6.0

**Platform**
Windows 10

**Printer**
Dagoma DiscoEasy200

**Reproduction steps**
1. Changed Top/Bottom layer count and then clicked the Fx button to recalculate defaults.

**Actual results**
For top / bottom layer thickness of .4mm (with Fine profile of 0.1mm layer height):

Top Layers: 0
Bottom Layers: 999999

**Expected results**
Top Layers: 4
Bottom Layers: 4

**Comment by Sophist-UK** [comment]
No - 10% Gira.

**Comment by Sophist-UK** [comment]
It didn't happen in 4.5.0.

**Comment by rburema** [comment]
I could not get this to reproduce (with anything else than 100% infill set that is) . Could you send a project file, so we can check what's going on? (Save, don't export, rename in order for github to accept it.)
