### ISSUE TITLE
Layer slider V and H missing

### ISSUE THREAD

**Issue by ffbboy30** [Ultimaker/Cura#7586]
Hi,
I'm working on the last cura version 4.6.0
On Windows 10 up to date
with a RTX1070 with nvidia up to date

When I load a file , the 3D model appears but I've only the xray view.
Impossible to activate th layer view , I've installed the slidebar gui plugin but same result.
Is there a trick to activate the layer view ?

Thanks

**Comment by fieldOfView** [comment]
We need your logs to figure out why layer view is not available. See Help -> Show configuration folder. The file we need is Cura.log
