### ISSUE TITLE
Cura 4.6 open files is not working

### ISSUE THREAD

**Issue by psternik** [Ultimaker/Cura#7593]
I just upgraded to Cura 4.6 and the icon and dropdown for opening files is not doing anything.

**Comment by fieldOfView** [comment]
Please fill in the template and add logs when you open an issue.

**Comment by Ghostkeeper** [comment]
Seems to be working fine here. Please fill in the template next time. We need to be a bit more aggressive to close those tickets as the template promises that we do.
