### ISSUE TITLE
Settings lost when switching between Advanced and Simple settings

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#76]
Application Version: 15.06
Platform: OS X 10.9.5

Steps to Reproduce:
Change something in Advanced Settings
Switch back to Simple Settings
Switch back to Advanced Settings

Actual Results:
Advanced Settings changes are lost

Expected results:
Cura would retain settings

**Comment by awhiemstra** [comment]
I tried this on my local OSX install and there settings are retained. Are any files created in ~/.cura/settings ? Additionally, if you start through the command line using <Install Dir>/Cura.app/Contents/MacOS/Cura , do you get any errors?

**Comment by Xisle** [comment]
![screen shot 2015-07-01 at 1 27 05 am](https://cloud.githubusercontent.com/assets/12257213/8451516/55aa5d98-1f90-11e5-8872-260e278cd5f6.png)

**Comment by Xisle** [comment]
![screen shot 2015-07-01 at 1 29 47 am](https://cloud.githubusercontent.com/assets/12257213/8451566/afe0fe02-1f90-11e5-9dad-7dff04a9daf4.png)

**Comment by Xisle** [comment]
Launching from command line produces this:

![screen shot 2015-07-01 at 1 31 46 am](https://cloud.githubusercontent.com/assets/12257213/8451617/fec59b86-1f90-11e5-81f0-85868c2bbfe4.png)

**Comment by Xisle** [comment]
This issue could be related to issue #43

**Comment by nallath** [comment]
I have the same issue; Switching back somehow forces the defaults.

**Comment by nallath** [comment]
Fixed for 15.10
