### ISSUE TITLE
Infill layer thickness causes unidirectional infill

### ISSUE THREAD

**Issue by carbogit** [Ultimaker/Cura#760]
Setting Infill layer thickness to 2x layer height (0.3 mm infill layer + 0.15 mm layer) causes infill direction for lines and zigzag pattern to become unidirectional; infill direction does not alternate with each layer any more (or every second layer, as expected for those settings).

2.1.1 beta

**Comment by Ghostkeeper** [comment]
Aye, we saw that one too. It was fixed in https://github.com/Ultimaker/CuraEngine/commit/5f8f0110cf79da1fdde7846656e4cf2edb1be969 but this was not included in the beta release on the website.
