### ISSUE TITLE
Z Seam Alignment does not work in Cura 4.6

### ISSUE THREAD

**Issue by BERT-LZ** [Ultimaker/Cura#7600]
Z Seam Alignment does not work in Cura 4.6
Z Seam Alignment - Sharpest Corner, Seam Corner Preferenz does not work in Cura 4.6.
But it works in Cura 4.5
I have already deleted the Cura folder on Appdata, and reconfigured Cura - the error is still there.

**Comment by smartavionics** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7557.
