### ISSUE TITLE
When in preview mode and srcoll up and down with slider the screen turn blue . The colour of the support is the smae colour as the model to be printed .This is from 4.6 update

### ISSUE THREAD

**Issue by Blockbusted** [Ultimaker/Cura#7602]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment]
Please fill in the issue template, or we won't (be able to) help.

**Comment by Blockbusted** [comment]
Have done so .

**Comment by nallath** [comment]
The template still isn't filled in. Could you try again?

**Comment by Blockbusted** [comment]
The support material is the same color as the material that is being used
to print , henceforth one can't see clearly what is support or the model to
be printed ....

When you zoom in or out to see detail the model can not be seen as it
disappears at the bottom of the picture (screen).Hope this is more clear ..

**Comment by jellespijker** [comment]
Can you please fill in the issue template

**Comment by Blockbusted** [comment]
Hi 

I don’t know how to do that .If this is the only way to get help then we call it quitt’s.

 

Thank you for your time .

**Comment by jellespijker** [comment]
![Peek 2020-06-21 00-09](https://user-images.githubusercontent.com/8535734/85212510-daa31600-b353-11ea-8b74-cd28ef74e7f0.gif)

**Comment by jellespijker** [comment]
Just checking if you're familiar with the `color scheme` drop down in the preview mode

![Peek 2020-06-21 00-17](https://user-images.githubusercontent.com/8535734/85212603-b85dc800-b354-11ea-989d-b252b18f3776.gif)

**Comment by Blockbusted** [comment]
Thanking you for this information Jelle . Much appreciated .

**Comment by jellespijker** [comment]
Did this solve your issue?

**Comment by Blockbusted** [comment]
Hi
Yes this did resolve my query.
Thank you for your assistance .
