### ISSUE TITLE
Layer height in preview screen

### ISSUE THREAD

**Issue by KevinFairgrieve** [Ultimaker/Cura#7607]
Would it be possible to have a second bar next to the layers that indicate the height.
![Untitled](https://user-images.githubusercontent.com/20424058/80350918-58253b00-8869-11ea-8315-b68db090aec2.png)
Thus enabling me to marry it up to the display on my printer.

**Comment by mahtDFR** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7576
