### ISSUE TITLE
Random Travel Movements at complicated Prints

### ISSUE THREAD

**Issue by ardlc-1212** [Ultimaker/Cura#7610]
please check the link below i mentioned more detailed at there
I used cura to slice but cura didn't show me those travel movements.
**Application version**
Cura 4.5
**Platform**
i7 9700
rtx 2060
512gb ssd
1tb harddisk
**Printer**
DIY marlin 2.0.x

**Screenshot(s)**
![Adsız](https://user-images.githubusercontent.com/39709207/80370451-da792380-8898-11ea-870c-8d5e2ce50c3a.jpg)

**Additional information**
https://community.ultimaker.com/topic/32268-cura-ruins-my-prints/?tab=comments#comment-262586

**Comment by rburema** [comment]
Handled in the forums. Cause was mangled SD card.
