### ISSUE TITLE
Unknown setting causing 10mm at y max and min to be reserved

### ISSUE THREAD

**Issue by clfaye** [Ultimaker/Cura#7612]
**Application version**
4.6

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
Cura is reserving 10mm at y min and y max for no reason that I can determine.  Build Plate Adhesion is set to none - so it's not the reservation normal for a skirt.

**Screenshot(s)**
![cura](https://user-images.githubusercontent.com/31780294/80422680-79028600-8893-11ea-97fe-a352df31f0f1.PNG)

**Comment by mahtDFR** [comment]
This is because the machine profile has specified this to allow space for the clips on the bed. See discussion here: https://github.com/Ultimaker/Cura/issues/7252

**Comment by clfaye** [comment]
This was indeed a no go area in the definition file.  If you delete that limit the bars go away.
