### ISSUE TITLE
Blurry text Cura 4.5, and 4.6

### ISSUE THREAD

**Issue by KelpyGsus** [Ultimaker/Cura#7613]
**Application version**
Cura 4.5 beta, 4.5, 4.6 beta, 4.6.

**Platform** 

Windows 10 Version 10.0.018362 Build 18362
GTX 1080, driver version 445.75

**Printer**

Ender 3

**Reproduction steps**

Not really repeatable, just constantly blurry. 
Blurry text regardless of light mode, or dark mode. 
I uninstalled and reinstalled multiple times, tried version 4.5 beta, 4.5, 4.6 beta, and 4.6.
Text is normal in the preferences tab.

**Screenshot(s)**

https://imgur.com/a/6GGZtuy
Top screenshot is Cura 4.4. The rest are 4.6

**Actual results**

Nothing changes.

**Expected results**

N/A

**Project file**

N/A

**Log file**

[cura.log](https://github.com/Ultimaker/Cura/files/4542326/cura.log)

**Additional information**

N/A

**Comment by mahtDFR** [comment]
Possibly related to this? https://github.com/Ultimaker/Cura/issues/5586

**Comment by fieldOfView** [comment]
What strikes me as odd is that the titlebar text and menu item text in your screenshots looks suspect too:
![image](https://user-images.githubusercontent.com/143551/80501723-0ddab180-8970-11ea-8d77-9450d1b02cc9.png)

The top 2 are yours, the bottom one is mine.

**Comment by Ghostkeeper** [comment]
Yeah that's really weird. Are title bars for other applications blurry as well?

**Comment by KelpyGsus** [comment]
> 
> 
> Yeah that's really weird. Are title bars for other applications blurry as well?

No, Cura 4.5 and above is the only time I've had this issue. 4.4 and below work fine.

**Comment by KelpyGsus** [comment]
It was an issue with Windows ClearType text.
