### ISSUE TITLE
Cura 15.04.6 Mac Line Endings Error

### ISSUE THREAD

**Issue by Omniwheel** [Ultimaker/Cura#762]
On Mac when editing start and end GCode in Cura, Cura inserts Windows carriage returns. When Cura is closed and then reopened the windows carriage returns turn into Unix new lines.

This is particularly problematic on some printers like XYZ machines. Due to a separate bug, XYZWare on Mac and/or XYZ printers don't properly handle Windows carriage returns.

**Comment by fieldOfView** [comment]
Please report issues for legacy versions of Cura here: https://github.com/daid/cura
