### ISSUE TITLE
trying to add a non-network printer in 4.6.1, only Ultimaker BV printers listed 

### ISSUE THREAD

**Issue by VOCAPTAIN** [Ultimaker/Cura#7634]
following guidance from your ultimaker support page on how to add a custom printer to Ultimaker Cura

**Application version**
(The version of the application this issue occurs with.)
4.6.1 and 4.6.0
**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
windows 10 pro 64, Intel i32310M
**Printer**
(Which printer was selected in Cura?)
n/a
**Reproduction steps**

Following guidance from your ultimaker support page on how to add a custom printer to Ultimaker Cura

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![thumbnail_IMG_3779](https://user-images.githubusercontent.com/64589354/80707816-83668f00-8ae2-11ea-8b02-44d6d59b5aa3.png)

**Actual results**
(What happens after the above steps have been followed.)
![Screenshot (8)](https://user-images.githubusercontent.com/64589354/80708042-e5bf8f80-8ae2-11ea-80e5-a4767173b693.png)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fieldOfView** [comment]
You can scroll the list of printers. There's a scrollbar that is hidden until you use it.

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/7614

**Comment by VOCAPTAIN** [comment]
thanks silly me the hidden scroll bar got me :-)
