### ISSUE TITLE
black project

### ISSUE THREAD

**Issue by diego8866** [Ultimaker/Cura#7641]
good morning,
when I load the projects under care in the prepare section, the drawings are always seen in black color also change the color of the filament, the problem is solved only using version 3.6, with subsequent versions the STLs are black,
what can I do? thanks

**Comment by fieldOfView** [comment]
Can you add a screenshot, and the next time pretty please fill in the issue template?

**Comment by diego8866** [comment]
![Immagine](https://user-images.githubusercontent.com/64637725/80800206-36012500-8ba9-11ea-836f-f86c67c96466.png)

**Comment by fieldOfView** [comment]
Have you pressed that nice blue "Sezionamento" button?

**Comment by diego8866** [comment]
in preview the problem does not arise once pressed sectioning I see the slycing correctly, the problem is only in the initial view on the prepare section

**Comment by fieldOfView** [comment]
This is how Cura works. You have to slice a model before you can preview how it will print. If you don't want to press the slice button, turn on "Slice automatically" checkbox on the General page of the preferences. You can also install the "Automatic Slicing Toggle" plugin from the Marketplace to quickly toggle that option.

**Comment by diego8866** [comment]
ok but in preparation I should see the piece with the color of the filament.
for example in the image the filament is purple, instead the object is black..
I tried to change filament and color but it does not change even after clicking sectioning

**Comment by mahtDFR** [comment]
That much is true. Please save a project file (File -> Save...), zip up the .3mf file and attach to this issue so we can try to reproduce it.

If you haven't already, please can you attach a [log file](https://github.com/Ultimaker/Cura#logging-issues).

**Comment by diego8866** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/4563996/cura.log)

**Comment by diego8866** [comment]
[1.zip](https://github.com/Ultimaker/Cura/files/4564010/1.zip)

i have only the stl...

**Comment by mahtDFR** [comment]
I'm afraid I can't reproduce it from that: 

![image](https://user-images.githubusercontent.com/17821912/80803757-87aead00-8bb3-11ea-9362-0418f529216f.png)

If you follow the instructions I posted above to save a project file, I will be able to try with your specific setup. Otherwise we're just guessing.

**Comment by diego8866** [comment]
[AA8_1.zip](https://github.com/Ultimaker/Cura/files/4564072/AA8_1.zip)
ok sorry

**Comment by diego8866** [comment]
is there a folder where custom filaments are saved?
the origin of the problem is that I had made a black filament but changing the filaments the color remained

it is as if the color setting had been saved and that the program could no longer change it

**Comment by mahtDFR** [comment]
Thanks. I have the information to try and reproduce it now. But I can't reproduce it! I think it's a problem with your configuration.

![image](https://user-images.githubusercontent.com/17821912/80807280-078d4500-8bbd-11ea-850a-a82df993fca2.png)

You could try [resetting your user data](https://github.com/Ultimaker/Cura/wiki/Cura-Preferences-and-Settings-Locations). You can back up your configuration first by zipping the relevant folder if you need to save things.

One side-note: you're using PVA as a build material - is that intended? This is usually a support material. Are you sure you don't want PLA?

**Comment by diego8866** [comment]
no pva is selected only to try to change the colour 
i must delete the file of prefferences?

**Comment by mahtDFR** [comment]
I can't think why that's happening. As I can't reproduce it here, that would guess there's an error in your configuration somewhere. One way to verify that would be if you zip your configuration file to make a backup. Then delete the original and open cura with out-of-the-box settings to verify if the behaviour persists. If it does, then we know there's an error in your original config file.

If you wish to revert it to how it was, all you need to do is unzip the file again into your settings directory.

**Comment by diego8866** [comment]
i removed the files from appdata and localappdata and configured again cura..i had some files of 2 other version of cura, configured again cura but i have no changes..do you know if i can search in other position?

**Comment by Ghostkeeper** [comment]
Maybe this is a rendering issue? Like, GPU? Maybe something with the new X-ray in Solid View feature there is something not supported on some graphics cards?

**Comment by diego8866** [comment]
THANKS A LOT was only a problem of GPU solved with an update of the driver i have an nvidia geforce GT525M 
nice idea I hadn't really thought about it
