### ISSUE TITLE
Random overextruded layers

### ISSUE THREAD

**Issue by hagan66** [Ultimaker/Cura#7642]
**Application version**
4.6.1

**Platform**
MacOS

**Printer**
Prusa MK2.5S

**Reproduction steps**
1. Sometimes one or more layers appear overextruded in a print while the rest of the print is perfect. 
2. If I print the same g-code again, the lines are still there. If I change something and reslice they can dissappear or show up att different height.

**Screenshot(s)**

![IMG_1816](https://user-images.githubusercontent.com/9168083/80810307-d95f3380-8bc3-11ea-9bc0-2e195287567f.jpeg)

**Additional information**
I posted about this in the Cura user group on facebook, and other people had observed this aswell.

**Comment by mahtDFR** [comment]
That's strange. Maybe you can share a project file with me?

**Comment by smartavionics** [comment]
Missing z-steps due to too high jerk/accel or too low stepper current?

**Comment by hagan66** [comment]
Hi! 

These two cubes are printed from the same settings, except for infill, which is grid for the bad one, and gyroid for the good one. I can send you the project file shortly aswell.

:-)

/Robert



Skickat från min iPhone

**Comment by hagan66** [comment]
Project file and gcode

**Comment by hagan66** [comment]
Hi! I tried to repy via email but it did not work with my attachments. I now attach two images of prints printed with exact same settings except for infill, which is grid infill for the bad looking cube and gyroid infill for the good one. Also attached you will find project file and gcode.
![IMG_1868](https://user-images.githubusercontent.com/9168083/80835693-9321c880-8bf3-11ea-9e3a-9c22217d00cc.jpeg)
![IMG_1869](https://user-images.githubusercontent.com/9168083/80835699-974de600-8bf3-11ea-9765-df70dd0e4420.jpeg)
[Bug Report.zip](https://github.com/Ultimaker/Cura/files/4566029/Bug.Report.zip)

**Comment by Ghostkeeper** [comment]
Seems to be a flow rate problem with your nozzle then, to me. I suggest you keep using Gyroid or other infill patterns that don't produce overlap, such as Lines, Zigzag, Concentric or Cross (3D). That's what those infill patterns are there for.

**Comment by hagan66** [comment]
Hmm, I never had this until the last two versions of Cura.

I will do some checking and get back.

There were actually several people on Cura FB group that also had noticed this recently.

:-)



R

**Comment by hagan66** [comment]
I just wanted to say you are probably right, now I got these ugly lines in Prusaslicer as well. So probably not Curas fault :-)

I suspect sticky rods messing up z-movement. I have now oiled them up and printing the same g-code. I will report the result.

R
