### ISSUE TITLE
Prime tower processing when "machine_extruders_share_heater" is true

### ISSUE THREAD

**Issue by furuiie** [Ultimaker/Cura#7646]
I can't speak English but I use machine translation.
I'm worried if it will be transmitted, but I'm looking forward to working with you.

Red: extruder_0   
Blue: extruder_1

In the first layer, when the blue color is not needed, the blue color is printed on the skirt (brim), and unnecessary material is replaced.
![1-2設定](https://user-images.githubusercontent.com/59741407/80810552-1563ba00-8bff-11ea-8c27-e2933e9a8e2d.png)
![1-2ビュー](https://user-images.githubusercontent.com/59741407/80810644-4512c200-8bff-11ea-8088-2fb7d3197e9a.png)

The first layer should be purging for the blue material, but it is not.
![2-1設定](https://user-images.githubusercontent.com/59741407/80812156-54dfd580-8c02-11ea-899a-8424c6682c82.png)
![2-1ビュー](https://user-images.githubusercontent.com/59741407/80812174-5f9a6a80-8c02-11ea-89b3-0239ec961693.png)

The ideal prime tower in the first tier
For red (extruder_0) only [If prime_tower_enable is true]
Do not print around the skirt (brim) with another extruder.
![1](https://user-images.githubusercontent.com/59741407/80817267-151deb80-8c0c-11ea-91a9-ba3c677f198f.png)

For two or more colors
Make a prime tower in red and purge the blue inside.
![2](https://user-images.githubusercontent.com/59741407/80818017-71353f80-8c0d-11ea-8fa9-89f26c3b0d29.png)
or
![3](https://user-images.githubusercontent.com/59741407/80818124-9fb31a80-8c0d-11ea-9824-10c520a03cbe.png)

Added: "value" formula for prime tower position
I think this is better. When "adhesion_type" is "skirt" "skirt_line_count" is ignored. (If the skirt exceeds the width of "brim_width", it will protrude from the plate.)

"prime_tower_position_x": {"value": "machine_width - max(((extruderValue(adhesion_extruder_nr, 'brim_width') * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 * (1 if not prime_tower_brim_enable and adhesion_type == 'brim' else 0)) if adhesion_type == 'brim' or (prime_tower_brim_enable and adhesion_type != 'raft') else (extruderValue(adhesion_extruder_nr, 'raft_margin') if adhesion_type == 'raft' else 0)) + (extruderValue(adhesion_extruder_nr, 'skirt_gap') + (skirt_line_count + 1) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 if adhesion_type == 'skirt' else 0), max(extruderValues('travel_avoid_distance'))) - max(extruderValues('support_offset')) - (resolveOrValue('draft_shield_dist') if resolveOrValue('draft_shield_enabled') else 0) - 1" },
"prime_tower_position_y": {"value": "machine_depth - prime_tower_size - max(((extruderValue(adhesion_extruder_nr, 'brim_width') * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 * (1 if not prime_tower_brim_enable and adhesion_type == 'brim' else 0)) if adhesion_type == 'brim' or (prime_tower_brim_enable and adhesion_type != 'raft') else (extruderValue(adhesion_extruder_nr, 'raft_margin') if adhesion_type == 'raft' else 0)) + (extruderValue(adhesion_extruder_nr, 'skirt_gap') + (skirt_line_count + 1) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 if adhesion_type == 'skirt' else 0), max(extruderValues('travel_avoid_distance'))) - max(extruderValues('support_offset')) - (resolveOrValue('draft_shield_dist') if resolveOrValue('draft_shield_enabled') else 0) - 1" },

**Comment by furuiie** [comment]
I made a mistake in the calculation formula

"prime_tower_position_x": {"value": "machine_width - max(((extruderValue(adhesion_extruder_nr, 'brim_width') * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 * (1 if not prime_tower_brim_enable and adhesion_type == 'brim' else 0)) if adhesion_type == 'brim' or (prime_tower_brim_enable and adhesion_type != 'raft') else (extruderValue(adhesion_extruder_nr, 'raft_margin') if adhesion_type == 'raft' else 0)) + (extruderValue(adhesion_extruder_nr, 'skirt_gap') + (skirt_line_count + 1) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 if adhesion_type == 'skirt' else 0), max(extruderValues('travel_avoid_distance'))) - max(extruderValues('support_offset')) - sum(extruderValues('skirt_brim_line_width')) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 - (resolveOrValue('draft_shield_dist') if resolveOrValue('draft_shield_enabled') else 0) - 1" },

"prime_tower_position_y": {"value": "machine_depth - prime_tower_size - max(((extruderValue(adhesion_extruder_nr, 'brim_width') * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 * (1 if not prime_tower_brim_enable and adhesion_type == 'brim' else 0)) if adhesion_type == 'brim' or (prime_tower_brim_enable and adhesion_type != 'raft') else (extruderValue(adhesion_extruder_nr, 'raft_margin') if adhesion_type == 'raft' else 0)) + (extruderValue(adhesion_extruder_nr, 'skirt_gap') + (skirt_line_count + 1) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 if adhesion_type == 'skirt' else 0), max(extruderValues('travel_avoid_distance'))) - max(extruderValues('support_offset')) - sum(extruderValues('skirt_brim_line_width')) * extruderValue(adhesion_extruder_nr, 'initial_layer_line_width_factor') / 100 - (resolveOrValue('draft_shield_dist') if resolveOrValue('draft_shield_enabled') else 0) - 1" },

**Comment by Ghostkeeper** [comment]
I will use short sentences. This makes translating easier for computers.

> In the first layer, when the blue color is not needed, the blue color is printed on the skirt (brim), and unnecessary material is replaced.

This is not a bug. We intended this. One of the functions of the skirt is to prime the nozzle. This makes the nozzle ready for printing. It ensures that the material is aligned to the tip of the nozzle. This needs to happen for every extruder. Once you're at the blue layers, it will be too late to go back down to the build plate. The print head would collide with the red cube. Therefore, it must prime during the first layer.

The prime tower is intended for dual extrusion. The setting is not visible for printers with 1 extruder.

> The first layer should be purging for the blue material, but it is not.

This is also intended. Cura chooses one material for the prime tower as the most important material. It chooses the material with the best layer adhesion for this. That way the prime tower is strong. This material is used for the outer shell of the prime tower. It is ALSO used for the base layer of the prime tower.

The first layer MUST consist of the same material as the outer shell. Two different materials don't stick well to each other. They shrink at different rates when cooling down. If they consist of different materials, the adhesion won't be as strong. This makes the prime tower topple.

In your case, it chose the red material as the best one. If you use different colours of PLA, the choice is arbitrary. However, if you use PLA and ABS, it will always choose PLA for the outer shell and the base layer.

> When "adhesion_type" is "skirt" "skirt_line_count" is ignored.

Good find! We'll take a look at this. It can indeed go outside of the build volume. This is not only for the prime tower though. This is the case for the entire print! The shadowy border needs to become wider.

**Comment by rburema** [comment]
> > When "adhesion_type" is "skirt" "skirt_line_count" is ignored.

> Good find! We'll take a look at this. It can indeed go outside of the build volume. This is not only for the prime tower though. This is the case for the entire print! The shadowy border needs to become wider.

This particular bug is now on our backlog as (internal) ticket CURA-7432 -- Since we're experiencing an increase in number of issues reported, it might be a while before we get to it though.

**Comment by furuiie** [comment]
Excuse me. I didn't include the desired picture description.
I think the prime tower brim and outer shell can be left as they are.
It is better to prime inside the outer shell only when using materials other than the outer shell.
![4](https://user-images.githubusercontent.com/59741407/81338328-6be16480-90e7-11ea-927b-44e3b9fba1fd.png)

Prime Tower with shared heater (in my case)
If the red block is below, I don't think you need the first layer of blue prime, as it can be processed by the prime tower when using the blue material.
I thought it was a prime tower for that.

If the blue block is below, I print it first with the red material and then the blue around the skirt and brim, but since there is one nozzle, it gradually changes from red to blue.
That distance may not be enough. Therefore, it is necessary to replace it at the Prime Tower.
I set "prime_tower_min_volume" to 40.
"prime_tower_size": {
　　　　"default_value": 30,
　　　　"maximum_value_warning": "35"
},
"prime_tower_min_volume": {"default_value": 40},

![5](https://user-images.githubusercontent.com/59741407/81339452-30479a00-90e9-11ea-948c-bdb22057bfa5.png)
材料の固定位置はノズルの先端から-35 mmです（私の場合）。
なるべく材料の交換は避けたいです。

Incidentally. I think that it is better to print the outer shells of the second and subsequent layers from the inside. This is because the other material gradually changes to the original material outward.

In the case of a shared heater, there are other types, but it is good because you can handle it later with settings etc. There is no way to handle the prime tower.
Please reconsider.
[My environment.zip](https://github.com/Ultimaker/Cura/files/4595604/My.environment.zip)

**Comment by Ghostkeeper** [comment]
The prime tower brim is not always enabled though, and also not always sufficient adhesion if it is enabled.

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features from our community and from Ultimaker, we have decided to remove this feature request from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
