### ISSUE TITLE
[4.6.1] Manual check for printer

### ISSUE THREAD

**Issue by sk8nfool** [Ultimaker/Cura#7647]
Cura checks for the presence of a printer when it starts but there also needs to be a way to manually trigger the same check. I often start Cura without turning on the printer and it takes an unknown time for it to be *discovered* it. Perhaps when going to the **Monitor** screen when there isn't a printer currently connected would trigger the discovery process.

**Comment by Ghostkeeper** [comment]
There is a manual check. You go to your printer in the printer management screen, click on "Connect via Network" and in that screen there is a button that says "Refresh" that makes it check again for the printers that it can discover on your LAN. I think it makes sense that this button is in the screen where you want to connect to these discovered printers. Would you disagree?
