### ISSUE TITLE
Possibility to change Velocity 

### ISSUE THREAD

**Issue by JRRN** [Ultimaker/Cura#7652]
As a Cura user I want to be able to add a Post-processament script to change the velocity in a layer or between selected layers.

**Comment by Ghostkeeper** [comment]
This exists! You would add a Change at Z post-processing script and check the "Change Speed" option.

The Change at Z script has the option to change it for only one layer or every layer after it as well. If you want to change it back you need to add another Change at Z script that alters the speed again at a higher layer. For instance, if you change the speed from 5.0mm and higher to 200%, and want to change it back at 10.0mm height, you would add another script that changes the speed to 50% from that height onwards.
