### ISSUE TITLE
[4.6.1] supports not showing.

### ISSUE THREAD

**Issue by 00ihsan** [Ultimaker/Cura#7662]
win10 x64
Ender 3 Pro

**Reproduction steps**
1. added .stl.
2. enabled supports.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
no supports showed and time and other data is unchanged.
**Expected results**
time and ussage data changed and supports showed.
**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by smartavionics** [comment]
Please save the project file (File -> Save) and then zip or rename the .3mf file and attach to this issue. Thanks.
