### ISSUE TITLE
Allow to enforce --single-instance via config file

### ISSUE THREAD

**Issue by reibuehl** [Ultimaker/Cura#7664]
**Is your feature request related to a problem? Please describe.**
Opening new instances of Cura 4.x takes longer and longer with each version. Fusion 360 seems to not use the --single-instance command line parameter when starting Cura and the default file association that is created by the Cura installer also seems to not use it.

**Describe the solution you'd like**
It should be possible to enforce the use of --single-instance even if not specified on the command line by setting a config file setting and/or preference that ensures that --single-instance is always used when starting Cura. This would reverse the default behavior of creating a new instance each time. 

**Describe alternatives you've considered**
Wrapping the Cura.exe in a batch file would be a workaround but would require additional changes to the default file associations that are not easy to do for end users.

**Affected users and/or printers**
Most users of Cura would benefit from this behavior that was the default in earlier versions of Cura like 15.04.

**Additional context**
<none>

**Comment by fieldOfView** [comment]
I have looked into this before. The reason why this is not an easy fix is that in the current architecture it takes a little while before the application preferences are read. By the time the preferences are fully loaded Cura is already well underway starting up a new instance. Perhaps an environment variable could help, but that is not easily user-settable in preferences.

**Comment by reibuehl** [comment]
I understand... is there a technical reason why multiple instances became the default in the first place? I think it used to be the opposite in old versions of Cura. 
An environment variable would at least be easier to set for user - compared to modifying the registry for the file association and would also help with Fusion 360 AFAIK.

**Comment by Ghostkeeper** [comment]
No, it's always been like that. Here's a screenshot of 3 instances of Legacy Cura running at the same time:

![image](https://user-images.githubusercontent.com/2448634/81299965-59c7dd80-9077-11ea-8317-2d5a9830f864.png)

**Comment by reibuehl** [comment]
Maybe on Linux...? On Windows, when I opened a STL in legacy Cura and then another one, it got added to the build platform of the existing instance.

**Comment by Ghostkeeper** [comment]
Maybe the operating system implemented that then, because Cura didn't, until the `--single-instance` parameter was [added](https://github.com/Ultimaker/Cura/commit/0e306df1bcc0c0e6126530a28a498073be85898c) in Cura 2.5. Neither Legacy nor modern Cura.

**Comment by fieldOfView** [comment]
We can talk long or short about whether the feature existed or not, but here's a PR that works around the problem of the preferences system not yet existing early in the boot process: https://github.com/Ultimaker/Cura/pull/7708
