### ISSUE TITLE
Coasting/ recoasting

### ISSUE THREAD

**Issue by sanczess** [Ultimaker/Cura#7674]
Processing an issue will go much faster when this is filled out, and issues which do not use this template WILL BE REMOVED and no fix will be considered!

Before filing, PLEASE check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.
Dear makers and programers of Cura
when I print with 0,6mm nozzle (and I do often) then coasting requires an ampount of About 0,6mm³ and that works. But for a restarton a outline this coasted volume appears as an underextrusion. how to deal with that issue? Maybe you could make a function like retract/ backretract for coasting as well?

**Comment by mahtDFR** [comment]
> Processing an issue will go much faster when this is filled out, and issues which do not use this template WILL BE REMOVED and no fix will be considered!

Before filing, PLEASE check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.

Please fill out the issue template.

**Comment by Ghostkeeper** [comment]
That is normal if you use too much coasting. Reduce your coasting amount. Coasting depletes the nozzle by oozing instead of printing a line. As always with oozing, the oozed material is lost and manifests itself as underextrusion just afterwards.

Try Retraction Extra Prime Amount to compensate.
