### ISSUE TITLE
Freeze on right clic !

### ISSUE THREAD

**Issue by eiscorp** [Ultimaker/Cura#7678]
Hi,
If start cura on my first display no problem but when i put cura on my other display if i do a right clic on model, cura freeze. that's very strange and i didn't have this bug on cura 4.5

cura 4.6.1
My config w10 1909
Asus x570-f gaming
amd 3700x
rtx2070

**Comment by rburema** [comment]
Please send us the logs (and just fill out the template... where it's even specified _where_ you can find the logs) so we can diagnose what's wrong.
