### ISSUE TITLE
cura brim error

### ISSUE THREAD

**Issue by Richi956** [Ultimaker/Cura#7688]
**Application version**
(The version of the application this issue occurs with.)
V 4.6.1
**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Windows 10 Pro 64-bit
Nividia GTX 1060

**Printer**
(Which printer was selected in Cura?)
Sovol Sv01
**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)
brim on
**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)
brim not on all sufaces
![cura error Brim](https://user-images.githubusercontent.com/64890858/81148831-4cc6c380-8f7d-11ea-9e4f-5e6d56c4fbcd.jpg)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)
crua creats brim but not on all sufaces. print fail.

**Comment by mahtDFR** [comment]
It's possible your model isn't completely flat on the build plate. Check that first.
You can lay the model flat by selecting the "Rotate" tool and choosing "Lay flat" in the flyout menu.

Hope this helps.

**Comment by Richi956** [comment]
Thanks, now it works.
![cura error Brim02](https://user-images.githubusercontent.com/64890858/81150041-92848b80-8f7f-11ea-864a-bc3ed4188029.jpg)
![cura error Brim03](https://user-images.githubusercontent.com/64890858/81150047-93b5b880-8f7f-11ea-90e7-e8902d8db331.jpg)
