### ISSUE TITLE
Rotating and Scaling are not commutative

### ISSUE THREAD

**Issue by brazenrain** [Ultimaker/Cura#769]
Rotating a part before scaling it causes the inputs for scaling to go haywire.

**Comment by sedwards2009** [comment]
There are a bunch of problems related to the tools and especially rotating and scaling. A heap of them have been solved in the `simple_convex_hull` branches for Cura and Uranium. The Cura team is really busy for the next week or two and after that we will merge this branch.

**Comment by luukakkerman** [comment]
Just to confirm this issue: Rotating an object makes the displayed scaling info on X, Y and Z go wild.
The resulting values seem to have some logic in them though: the percentages seem to be calculated by comparing the new X, Y and Z box dimensions with the original ones before rotating.

See attached model that was orginally placed vertical and was only rotated 90 degrees around its X axis (red).

Hope this can help the team.

![90degree-rotate-causes-weird-scaling-info](https://cloud.githubusercontent.com/assets/19990275/16143924/35762322-3470-11e6-91a6-36b778334f10.jpg)

**Comment by nallath** [comment]
This has been fixed.

**Comment by cranking** [comment]
I think this issue should be reopened -- I'm experiencing the same issue in the UltiCura 3.5
