### ISSUE TITLE
(Crash) Incomplete transfer of settings from the old version to the new version (from cura 4.5 to cura 4.6.1)

### ISSUE THREAD

**Issue by Goodfeat** [Ultimaker/Cura#7691]
found a small error while updating the program.
the program does not transfer files correctly

I have a separate printer, its settings are based on an ultimaker.
![image](https://user-images.githubusercontent.com/44455128/81174391-191f8400-8fe5-11ea-9efb-99d05b22c078.png)

I decided to update the program and was faced with the fact that the program crashes when switching to another printer

the problem was found right away, so no reports needed

it turns out when updating the program does not change the version settings to the current

![image](https://user-images.githubusercontent.com/44455128/81174007-59cacd80-8fe4-11ea-9670-efb9af7d14db.png)

I needed to go into the settings options and fix the setting_version parameter manually.

from setting_version = 11 
to  setting_version = 13

![image](https://user-images.githubusercontent.com/44455128/81174152-a4e4e080-8fe4-11ea-92b5-6a8555ffd973.png)

After that everything worked

If I’m not mistaken, usually when transferring the settings, the program itself should fix the settings version. for some reason this does not happen with this folder

**Comment by nallath** [comment]
This is correct. We don't have an upgrade for the variants. The upgrade scripts generally only update profiles that can be created through the interface.

**Comment by Ghostkeeper** [comment]
Yes, I agree. This is outside of the scope of the version upgrade at the moment, in order to keep things a bit more simple for us. We don't want to be testing the version upgrade with manually created profiles.
