### ISSUE TITLE
clean top layer for reflective metal filaments

### ISSUE THREAD

**Issue by dennik** [Ultimaker/Cura#7694]
**Is your feature request related to a problem? Please describe.**
Ive tried to print with silver PLA and noticed that when the top layer has a hole or several holes on it, the path gets interrupted, the printhead jumps to a different location, and by the time it fills up all the gaps, unpleasing patches appear cause the plastic reflects light in a different way from patch to patch. 
![top_layer_patches](https://user-images.githubusercontent.com/1870430/81199154-4c83f380-8f90-11ea-8027-c0293dbc37a6.jpg)
The reason this is happening is unknown to me but I imagine it happens with most reflective metal filaments.

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

I would hope for an option to close top layers removing any vertical through holes to avoid the print path getting interrupted. That way all flat areas are printed evenly and cleanly before the next layer starts.

**Describe alternatives you've considered**
I have already simulated this solution by separating the letters from the flat surface below them by 0.02mm. Enough so that the slicer closes that through hole under each letter, and starts the letter on the next layer. Adhesion and structural integrity is probably even better than with just fill in walls underneath. The gap needs to increase if the layer height increases so that the slicer doesn't re generate that hole.
![new_print](https://user-images.githubusercontent.com/1870430/81199535-c4521e00-8f90-11ea-8ee7-e02975218082.jpg)
The result is a much cleaner print with the patches gone.

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
Anyone who prints with reflective materials could benefit from this. I imagine most people would love to have clean looking top layers without those patches showing up. I imagine this problem might not show up with matte finish materials, or flat surfaces without through holes.
I've only tested this on a UM3 printer.

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by 64Florian** [comment]
Hello,
You have this feature / workaround using top / bottom layer to 0 and  infill 100%:
![Base 2](https://user-images.githubusercontent.com/34726380/81240774-9f00f680-9008-11ea-8932-4e3676184608.png)
![no top](https://user-images.githubusercontent.com/34726380/81240777-a1635080-9008-11ea-9c18-bbab294da222.png)

I attached my file (I sliced @ 0.1 mm/layer)
[TestJoy.stl.zip](https://github.com/Ultimaker/Cura/files/4590058/TestJoy.stl.zip)

**Comment by smartavionics** [comment]
Even simpler, just use a larger value of top skin expand distance....

![Screenshot_2020-05-07_09-19-37](https://user-images.githubusercontent.com/585618/81271393-ee184d00-9043-11ea-90c0-f0b742d66029.png)

**Comment by mahtDFR** [comment]
Good suggestions above. 'Enable Ironing' might also improve your results.
It seems there are sufficient solutions already so I don't think we're going to do more with this.

**Comment by 64Florian** [comment]
> Even simpler, just use a larger value of top skin expand distance....

Doesn't work for me ... (@smartavionics did you try to "play" the layer ? )
![Capture d’écran 2020-05-07 à 12 57 35](https://user-images.githubusercontent.com/34726380/81287166-9b01c280-9062-11ea-802f-a1adc972d042.png)

**Comment by smartavionics** [comment]
You probably also need to set top surface skin layers to 0.

**Comment by 64Florian** [comment]
> You probably also need to set top surface skin layers to 0.
As I can see in my tests, if skin layers = 0 I have to set infill to 100% 
with this settings I'm not able to see any influence for skin expand distance but I could have miss something ...

@mahtDFR  I have try to see for ironing, the finish could be better but it could have the same issue too because: this issue is linked to the way the head add filament and move on the surface 
-> To have all particulate in the same "way" you have to apply exactly the same travel 
unfortunately it's not possible for zigzag mode .. 
![Capture d’écran 2020-05-07 à 13 32 11](https://user-images.githubusercontent.com/34726380/81290457-66910500-9068-11ea-8cd9-255f2302da67.png)
![Capture d’écran 2020-05-07 à 13 32 29](https://user-images.githubusercontent.com/34726380/81290467-6abd2280-9068-11ea-96eb-376e4d7c1eda.png)

it could give a good result for concentric mode (if the last layer doesn't break definitively the chances to made a good finish (Tests has to be done))
![Capture d’écran 2020-05-07 à 13 40 10](https://user-images.githubusercontent.com/34726380/81290495-76104e00-9068-11ea-9b45-01a33a77f0d7.png)

**Comment by dennik** [comment]
> 
> 
> Good suggestions above. 'Enable Ironing' might also improve your results.
> It seems there are sufficient solutions already so I don't think we're going to do more with this.


> 
> 
> Even simpler, just use a larger value of top skin expand distance....
> 
> ![Screenshot_2020-05-07_09-19-37](https://user-images.githubusercontent.com/585618/81271393-ee184d00-9043-11ea-90c0-f0b742d66029.png)

Yes I can confirm that top skin expand distance is doing the same trick in a different way.

**Comment by dennik** [comment]
> 
> 
> Good suggestions above. 'Enable Ironing' might also improve your results.
> It seems there are sufficient solutions already so I don't think we're going to do more with this.

Ironing alone won't do the trick. It will just smear the same reflectivity difference in other directions.
![ironing](https://user-images.githubusercontent.com/1870430/81304677-5cacd900-904b-11ea-9774-f65226b444bb.jpg)
it does enhance the quality though on a clean top layer.

**Comment by 64Florian** [comment]
@dennik did you try my settings ? 0 top and infill 100% lines infill:

> ![no top](https://user-images.githubusercontent.com/34726380/81240777-a1635080-9008-11ea-9c18-bbab294da222.png)

as I can see in "play" mode in preview, it should be OK for full clean layer

**Comment by dennik** [comment]
> 
> 
> @dennik did you try my settings ? 0 top and infill 100% lines infill:
> 
> > ![no top](https://user-images.githubusercontent.com/34726380/81240777-a1635080-9008-11ea-9c18-bbab294da222.png)
> 
> as I can see in "play" mode in preview, it should be OK for full clean layer
Yes, the 100% infil definitely closes all holes although it adds to the 3D print time and also filament consumption. I didn't see any difference with the top/bottom thickness setting though.

**Comment by 64Florian** [comment]
"Bottom" is overkill .. but with my test if you have 1 top layer you're back to the issue (as I can see when you "play" the layer)
If you want to preserve your print time / filament consumption, you have to add a second object to "modify settings on overlaps" as said before:

> P.S. if you want an empty product or a 20% infill for the bottom, you can add another shape and use "modify settings on overlaps" or the other options to customize the bottom of the product
> ![Capture d’écran 2020-05-07 à 02 24 00](https://user-images.githubusercontent.com/34726380/81241227-04091c00-900a-11ea-9f43-69d6c01ab905.png)

Have you ever use this feature ? (_"modify settings on overlaps"_)

**Comment by dennik** [comment]
> 
> 
> "Bottom" is overkill .. but with my test if you have 1 top layer you're back to the issue (as I can see when you "play" the layer)
> If you want to preserve your print time / filament consumption, you have to add a second object to "modify settings on overlaps" as said before:
> 
> > P.S. if you want an empty product or a 20% infill for the bottom, you can add another shape and use "modify settings on overlaps" or the other options to customize the bottom of the product
> > ![Capture d’écran 2020-05-07 à 02 24 00](https://user-images.githubusercontent.com/34726380/81241227-04091c00-900a-11ea-9f43-69d6c01ab905.png)
> 
> Have you ever use this feature ? (_"modify settings on overlaps"_)

That's a great feature to use. Had no idea about the functionality of that button. For now I think it is probably best to use the "top skin expand distance" as  mahtDFR suggested. Although it is a hard setting to find unless you know exactly what you are looking for.
