### ISSUE TITLE
[4.6.1] Support pattern

### ISSUE THREAD

**Issue by sinedied** [Ultimaker/Cura#7696]
**Application version**
4.6.1

**Platform**
OSX 10.12.6

**Printer**
Creality Ender 3 Pro

**Reproduction steps**
1. Enable support, try to change support type

**Screenshot(s)**
<img width="1038" alt="Capture d’écran 2020-05-06 à 20 17 09" src="https://user-images.githubusercontent.com/593151/81213905-609f1380-8fd7-11ea-9b02-581080cae1dd.png">
While I defined zigzag with the break support size option enabled, I always get the outer contour drawn. I expect the support tower 

**Actual results** vs **Expected results**
Using Cura 4.6.1 it seems that support patterns are incorrect: while I defined zigzag pattern support with the break support size option enabled, I always get a support with outer contour drawn, in a single chunk. I expected the support tower to be in zigzag form, split in multiple pieces.

**Project file**
Project: https://we.tl/t-rHSt4SyICW
STL: https://www.myminifactory.com/object/3d-print-hippo-nikoss-animals-17282

**Additional information**
Maybe related: https://github.com/Ultimaker/Cura/issues/7676

**Comment by Ghostkeeper** [comment]
Set the Support Wall Line Count setting to 0. Then the outline disappears.
