### ISSUE TITLE
Direct access to "Slice automatically"

### ISSUE THREAD

**Issue by 64Florian** [Ultimaker/Cura#7698]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I change a setting with a big STL file and the opposite when it's a small one and the setting is disable

**Describe the solution you'd like**
Please add a checkbox:
![Adding checkbox](https://user-images.githubusercontent.com/34726380/81234925-1418ff80-8ffa-11ea-919b-d582dbd52a9d.png)

**Affected users and/or printers**
Everyone going to benefit from these changes. -> time saver than settings -> pref-> check -> close
and better workflow for beginners and basics users how don't see this feature and have to wait or click as fast as the can on cancel button when they fine tune settings of they profiles (in preview mode)

**Comment by yet-another-average-joe** [comment]
It seems you just need the "Slicing Toggle by fieldOfView" plugin. Did you give it a try ? It does exactly what you're asking for, with a "run/pause" toggle graphic button :

https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/PauseBackendPlugin

**Comment by mahtDFR** [comment]
The above is correct, this feature already exists via a plugin. Will close this now.

**Comment by 64Florian** [comment]
Thanks a lot !
That's exactly what I wanted
