### ISSUE TITLE
Infill Speed bug

### ISSUE THREAD

**Issue by SJC28** [Ultimaker/Cura#7702]
Hi.

I have the infill speed selected in settings, but it does not appear under Speed when I want to modify it. If I select any other speed setting it works perfectly.

![WkSvMgr 5_7_2020 12_28_40 PM_LI](https://user-images.githubusercontent.com/64959916/81284628-a357fe80-905e-11ea-8213-978a3b5d784f.jpg)

**Comment by smartavionics** [comment]
Perhaps infill density is 0?

**Comment by SJC28** [comment]
The Infill it's at 15%

**Comment by 64Florian** [comment]
Have you try:
 - to search for "infill" in the search settings area ? 
 - to disable the visibility, close cura, reopen, and re-enable the visibility ? 
 - to use another profile

**Comment by SJC28** [comment]
Yes. I have tried that and nothing. Also tried updating Cura and still
nothing.

The only thing that helped was uninstalling Cura and every profile I had
and then install it again and create all the profiles again.

**Comment by Ghostkeeper** [comment]
Could you provide a project file that reproduces the issue? It's most likely one of your setting overrides that makes it disappear.
