### ISSUE TITLE
[4.6.1] Unable to install material from market place.

### ISSUE THREAD

**Issue by WorldOfGZ** [Ultimaker/Cura#7725]
Hello 
I just tried to install material from Market place but the new material is not on material manager.
On market place -> Material marked as "Installed"
On appData i have folder with xml profiles

I also try directly from material manager to import the profile on appData. That's create a new file, but this is not loaded

I tried with Fillamentum_ASA1 & colorfabb_woodfill

**Application version**
4.6.1

**Platform**
Windows 10 up to date

**Printer**
Creality CR-10

**Reproduction steps**
1. Add material from Market place
2. Restart Cura
3. Check on material manager

**Screenshot(s)**
![Cura](https://user-images.githubusercontent.com/12786921/81477787-e01c2500-9219-11ea-9c0b-0a686e7e0235.png)

**Actual results**
No material from market place on material manager

**Expected results**
Use wood filament on material proposed on marketplace

**Log file**
https://gist.github.com/WorldOfGZ/6c34e7b7b6ba3606c3ae8e36e4095ab6

**Additional information**

**Comment by Ghostkeeper** [comment]
The problem is that the material in the marketplace is 2.85mm filament which is not supported by your printer.
