### ISSUE TITLE
Overhang not generated unless Overhang Angle = 0

### ISSUE THREAD

**Issue by mikebruns99** [Ultimaker/Cura#773]
Hi all,  Hope this is the right place to post this, I'm new to the 3D printing community.  

I have a Lulzbot Taz 6, we're just getting into it.  We exported from Autodesk Inventor 2016 in High-Detail, loaded the .STL into the Lulzbot version of Cura 19.12.  

I have support type set to "Touching buildplate", but the only way it will generate support is if I set the Overhang Angle to 0 degrees.  Setting it 1 (or above) omits the support.  

This is the part with Overhang angle set to 1: (bad): ![nooverhang](https://cloud.githubusercontent.com/assets/6955769/15842550/ed9f66a8-2c27-11e6-9586-be7b8978c8fb.png)

This is the part with Overhang angle set to 0: (good) ![overhang](https://cloud.githubusercontent.com/assets/6955769/15842551/eda200e8-2c27-11e6-8b4b-967912ccbb02.png)

Is there something I'm missing?  The actual print matched the preview, so I unfortunately, ruined a 22-hour print. Would like to figure out what I did wrong so I correct it going forward. 

I've included the .STL file below.

[Twister.zip](https://github.com/Ultimaker/Cura/files/301627/Twister.zip)

Thanks!

**Comment by Ghostkeeper** [comment]
You'd do better to report this at https://github.com/daid/LegacyCura or try a more modern version of Cura.
