### ISSUE TITLE
[4.6.1] Error message "Invalid file" when it should actually be "Permission denied" when opening a file

### ISSUE THREAD

**Issue by justinotherguy** [Ultimaker/Cura#7731]
**Application version**
4.6.1

**Platform**
macOS 10.15
Linux Mint 19.3

**Printer**
Ultimaker S5

**Reproduction steps**
1. create an legit STL file (test1.stl)
2. open it in Cura
3. confirm: opens perfectly
4. copy the file ("cp test1.stl test2.stl")
5. remove read permissions from the copied file ("chmod 000 test2.stl")
6. open it in Cura
7. error message: 
"Invalid File
Failed to load <path>/test2.stl"

**Screenshot(s)**
![Ohne Titel](https://user-images.githubusercontent.com/199173/81509209-5a77a280-9309-11ea-9a80-3466489789be.png)

**Actual results**
File does not open, error message appears
(What happens after the above steps have been followed.)

**Expected results**
Title of error message should say "Permission Denied"

**Comment by mahtDFR** [comment]
I think what's happening here is the error is using the 'catch all' handling rather than the specific handling set up. We discussed this morning and decided to defer it for now. Thanks for the report.
