### ISSUE TITLE
change the first gcode send

### ISSUE THREAD

**Issue by 00ihsan** [Ultimaker/Cura#7734]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

i use octoprint with the plugin gcode system command. i made a gcode that turns on the priner. but it wont work because the bed starts heating before the gcode for turning the printer on is send. so the printer gets into thermal runawaymode before the code is send.

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

a textbox where i can set the start gcode. i know there is a kind of simmilar box. dut as i said that waits first for the bed to warm up. the textbox i want has to be executed before any other gcode.

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

a scriptthat does it for me.

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

everyone using octoprint.

**Additional context**
(Add any other context or screenshots about the feature request here.)
![image](https://user-images.githubusercontent.com/57139073/81521541-d690db00-9347-11ea-9174-929f33509c3a.png) before

![image](https://user-images.githubusercontent.com/57139073/81521583-f0cab900-9347-11ea-922a-22bf6b3226b1.png) after

**Comment by fieldOfView** [comment]
Use a Search and Replace post processing script.
Search `;Generated with`
Replace `OCTO100 ; Generated with`

**Comment by 00ihsan** [comment]
I don’t know how to make such a script.

**Comment by fieldOfView** [comment]
You don't have to make it, you can just "add" it.
See Extensions -> Post processsing -> Modify gcode".
Press "add a script" and select "Search and Replace"

**Comment by 00ihsan** [comment]
👍
