### ISSUE TITLE
spire support may fail when 'support infill layer thickness' is larger than layer height

### ISSUE THREAD

**Issue by elsbiet** [Ultimaker/Cura#7738]
**Application version**
4.6.1

**Platform**
linux

**Printer**
self built
**Reproduction steps**
- create an model with a spire pointing downwards. 
- alter print settings: set 'support infill layer thickness' to the double of the layer thickness (.4mm in my case)
- slize the model
- observe the support of the above spire in the preview window

**Screenshot(s)**
-

**Actual results**
in my case 2 support layers are missing which made my print fail

**Expected results**
- at least one more support layer beneath the spire

**Project file**
on demand

**Log file**
-

**Additional information**
- when 'support infill layer thickness' is the same as layer height i could print the model

**Comment by mahtDFR** [comment]
What's 'spire support'? Can you provide some screenshots and 
save a project file (File -> Save...), zip up the .3mf file and attach to this issue so I can try to reproduce it with the same settings as you.

**Comment by elsbiet** [comment]
i meant support for a downward pointing spire.

question: does cura has a way to cut a cuboid shaped part out of my slized model which i could send to you? (i'm not supposed to publish the complete model)

**Comment by Ghostkeeper** [comment]
No, Cura can't export only part of a model.

Perhaps you meant how it supports something like this? 
![image](https://user-images.githubusercontent.com/2448634/82330151-be255e00-99e2-11ea-8b6e-1b219563e830.png)
