### ISSUE TITLE
Add printer by IP: only one network plugin can be enabled at the time

### ISSUE THREAD

**Issue by loociano** [Ultimaker/Cura#7739]
**Application version**
Cura 4.6.1

**Platform**
Windows 10. Possibly any.

**Printer**
Monoprice Select Mini V2

**Reproduction steps**
1. Add Printer
2. Add printer by IP
3. Enter printer IP address
4. Add

**Screenshot(s)**
N/A 

**Actual results**
Cannot connect to network printer if two network plugins are enabled. Only `UM3NetworkPrinter` plugin issues HTTP requests.

**Expected results**
Method `addManualDevice()` is invoked on all enabled network plugins.

**Project file**
N/A

**Log file**
N/A

**Additional information**
Hi! I am unsure whether this issue is a bug or a feature request, feel free to tag.

I am developing a network plugin for a 3rd party network-enabled printer, and noticed that, when trying to add a printer manually by IP address, two network plugins cannot operate at the same time as of Cura 4.6.1.

Method `checkManualDevice` in `DiscoveredPrintersModel` only selects the top network plugin based on `PRIORITY`:
https://github.com/Ultimaker/Cura/blob/fe27da5e8a945d8b79834aa5779b323045f7e742/cura/Machines/Models/DiscoveredPrintersModel.py#L164

Setting `ManualDeviceAdditionAttempt.PRIORITY` in a second network plugin does not guarantee that it is chosen by Cura. In fact, `UM3NetworkPrinter` plugin always prevails in my testing.

Workaround is to disable `UM3NetworkPrinter` plugin to let the second network plugin operate, although this is not ideal.

**Comment by nallath** [comment]
Yeah, you're right. It shouldn't work like that. All plugins should try and see if they can (manually) connect to that printer (and based on if it succeeds, a discovered printer should be added).

**Comment by loociano** [comment]
Thanks for confirming Jaime.
