### ISSUE TITLE
Bed Adhesion Skirt Option - Allow user to force Cura to draw the skirt in one continuous line without picking the print head up.

### ISSUE THREAD

**Issue by midnighttofurun** [Ultimaker/Cura#7748]
**Is your feature request related to a problem? Please describe.**
I have noticed in Cura 4.6.1 that sometimes the skirt will draw one complete loop, then stop extruding, move to a completely different point in the loop, and start drawing the next loop again.  Often, the print head travels within the space where the first layer will be.  This can mess up the initial layer.  

**Describe the solution you'd like**
A solution for this would be to allow the user to check a box to force Cura to draw the skirt as one continuous line (overriding whatever setting is being applied that optimizes drawing the skirt).  The slicer should still determine where best to start the skirt.  

**Describe alternatives you've considered**
There is a lack of options for the Bed Adhesion Skirt Option.  

**Affected users and/or printers**
All users who use the Skirt option as their Bed Adhesion preference

**Comment by rburema** [comment]
Not printing continuously was a bug.

This will be fixed for 4.7, because of [this pull request](https://github.com/Ultimaker/CuraEngine/pull/1231) @smartavionics made.
