### ISSUE TITLE
Creality3D Ender 4 wrong settings

### ISSUE THREAD

**Issue by JBMedeiros** [Ultimaker/Cura#7750]
**Application version**
4.6.0 - 4.6.1

**Platform**
macOS
Windows

**Printer**
Creality3D Ender 4

**Reproduction steps**
1. Add local printer
2. Add Creality3D Ender 4

**Screenshot(s)**
![Captura de Tela 2020-05-13 às 10 22 50](https://user-images.githubusercontent.com/13773887/81818345-4e0b6980-9504-11ea-961d-86ea4e53ea37.png)
![Captura de Tela 2020-05-13 às 10 22 56](https://user-images.githubusercontent.com/13773887/81818356-506dc380-9504-11ea-9222-beab62f54ec2.png)

**Actual results**
![Captura de Tela 2020-05-13 às 10 22 56](https://user-images.githubusercontent.com/13773887/81818381-58c5fe80-9504-11ea-9e1f-1164b243ec96.png)

**Expected results**
![Captura de Tela 2020-05-13 às 10 29 29](https://user-images.githubusercontent.com/13773887/81818774-d722a080-9504-11ea-8461-a20d1e379c13.png)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
Believe this is wrong server information.

**Comment by mahtDFR** [comment]
The author of this definition or someone else in the community will need to fix these values and submit an updated definition as a pull request to us. We take a hands-off approach to third-party profiles as we have no way of testing them, but we are happy to accept them if submitted (and thoroughly tested).
