### ISSUE TITLE
[4.6.1] Ultimaker ABS update request stuck

### ISSUE THREAD

**Issue by imodre** [Ultimaker/Cura#7764]
**Application version**
4.6.1

**Platform**
Win 10

**Printer**
Custom (FlyingBear Ghost 4s with MKS Wifi plugin from marketplace)

**Reproduction steps**
1. Update from 4.4.0 to 4.6.1
2. See that there is an update request in marketplace.
3. Update it
4. See that it's still there.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/39004057/82051728-a00ae580-96e4-11ea-912d-f4c665eab32c.png)
![image](https://user-images.githubusercontent.com/39004057/82051765-b2851f00-96e4-11ea-8334-d48400373b25.png)
![image](https://user-images.githubusercontent.com/39004057/82051777-b618a600-96e4-11ea-9428-02d185aa0a10.png)

**Actual results**
Unremovable material update request + account sync request.

**Expected results**
No such behaviour after trying to update this material.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4634470/cura.log)
Searching 'ABS' in file could help maybe.

**Additional information**
Tried to run as administrator, no success.

**Comment by mahtDFR** [comment]
Thanks for the report. I'm able to reproduce it. We're investigating

**Comment by Phenix2984** [comment]
I think I have the same problem: from Cura 4.6.1 install, Cura ask for "Ultimaker ABS" plugin update at each start.
I don't use this plugin and I can't uninstall.

**Comment by loulou-uoluol** [comment]
Hello, 
can't update also on Mac OS 10.15.4

**Comment by mahtDFR** [comment]
This package was updated recently after a request from our product managers.
The version number is now higher than what ships with Cura, and the current Cura release has a bug that skips built-in packages when comparing.

There is a fix for this already in Cura, but it is yet to be released. Sorry for the hassle.

**Comment by mahtDFR** [comment]
Relevant internal ticket(s):
CURA-6269
CURA-7366

**Comment by Ghostkeeper** [comment]
The ticket where this fix was made was reported here: https://github.com/Ultimaker/Cura/issues/7426 . This is a duplicate.
