### ISSUE TITLE
[4.6.1] Dark theme bugs

### ISSUE THREAD

**Issue by dsvi** [Ultimaker/Cura#7766]
`Ultimaker Dark` theme has a lot of issues.
For example if you go to `Profile` -> `Manage Profiles`, most of the text is not readable, since font is of black color on the black background.
<img width="1902" alt="cura dark" src="https://user-images.githubusercontent.com/23555438/82066141-b494b100-96d7-11ea-9dfb-96fb444c70f5.png">

**Application version**
4.6.1

**Platform**
Suse Linux KDE

**Comment by mituritsyn** [comment]
Same issue
**Application version**
4.6.1
**Platform**
Kubuntu 18.04

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/4826 .

The elements in this preferences screen are partially system-themed, so if you change your system theme to a dark theme but not Cura, or if you change Cura to a dark theme but not your system, it's looking weird to the point of text being illegible.

**Comment by dsvi** [comment]
Nah, that's not my case. I do have system-wide dark theme. And Cura is the only app affected by thins on my desktop.
