### ISSUE TITLE
[4.6.1] Cura White Screen on Startup, not responding

### ISSUE THREAD

**Issue by Brzam** [Ultimaker/Cura#7779]
**Application version**
4.6.1

**Platform**
Windows 10 (GFX = AMD Radeon RX 5700 XT)

**Printer**
AnyCubic i3, but issue occurs prior to this

**Reproduction steps**
Unsure of the steps, this bug appears to occur randomly, but frequently for me.
**Screenshot(s)**
![Screenshot_1](https://user-images.githubusercontent.com/3620016/82150390-88e90680-9850-11ea-83e7-cebb8a9f3031.png)

**Actual results**
Cura displays a white screen with no option to continue, the only option being to force close the application. This issue disappears when deleting the entire contents of %appdata%/cura, but obviously all settings are deleted.

**Expected results**
Cura starts up normally.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
[stderr.log](https://github.com/Ultimaker/Cura/files/4640381/stderr.log)

**Additional information**
This issue has been occurring for me since 4.5 but have has been heappening more frequently recently.

**Comment by nallath** [comment]
Do you have extra /multiple montitor(s) attached?

**Comment by Brzam** [comment]
I do indeed, am running 3 1920x1200 monitors.

**Comment by fieldOfView** [comment]
Try disabling two of them temporarily. If Cura starts succesfuly with a single monitor, go to the General preferences and uncheck the "Restore window position on start". Then you can reenable the other screens, and Cura should always open on your primary screen.

**Comment by Brzam** [comment]
Done! Will re-open this if the issue persists, thank you both :)

**Comment by d-rez** [comment]
This is a bug still in 5.4.0 and 5.7.0beta and it needs to be fixed. Disconnecting / disabling monitors isn't a solution...

**Comment by sajjadkurd1999-lang** [comment]
Pubg white body
