### ISSUE TITLE
Cura [2.1.2] -profile cannot save  bug???

### ISSUE THREAD

**Issue by QoooQ** [Ultimaker/Cura#778]
i change value and update but can not save?  Why?

when i change value then select other profile    it ask me want update profile  i select update  but value is not save ?! bug???

**Comment by Ghostkeeper** [comment]
Sounds like a bug to me. If you say you want to update the profile it should update the profile you were coming from before switching to the new profile.

**Comment by QoooQ** [comment]
please try   it      and you will find bug(no save)!!

**Comment by carbogit** [comment]
Confirm, some settings, esp. the material section, do not save. Retraction distance stays 6.5 mm whatever I do.

**Comment by Ghostkeeper** [comment]
We've since fixed this issue per https://github.com/Ultimaker/Uranium/pull/133

The issue was that material profiles were overriding the user profiles. User profiles are now always on top.

**Comment by DarkRabbit19** [comment]
I stil have te problem

**Comment by fieldOfView** [comment]
@DarkRabbit19: with what version? 
This has been fixed in Cura 2.2, which is not yet released.
