### ISSUE TITLE
HTPLA from ProtoPasta not Showing for Ender 3 even though it is 1.75

### ISSUE THREAD

**Issue by jrgleason** [Ultimaker/Cura#7780]
**Application version**
4.6

**Platform**
OSX

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Add Proto Pasta Matte from the store
2. Doesn't show for Ender 3 Pro but shows for the Ultimaker S5

**Expected results**
I would like to use it with my Ender 3 Pro since it is 1.75

**Comment by jrgleason** [comment]
Looks like I can just reconfigure the size after imported but still feels like it should at least be available in both sizes.

**Comment by nallath** [comment]
The marketplace only has profiles & materials for 2.85mm (aka: For Ultimakers).

This might change in the future, but I wouldn't expect it any time soon.
