### ISSUE TITLE
A bug linked to the location of the hints

### ISSUE THREAD

**Issue by Ranil007** [Ultimaker/Cura#7803]
Hello, Cura. I noticed the bug. It is in the tab "Monitor" when I connect my printer to Cura, in this tab you can manage it. But, guys, Ultimaker, you have traced such a bug related to the location of the QDialog window, and so it is not displayed correctly. See the screenshot for more details:
https://yadi.sk/i/QLuA0iT7dbLRRg

**Comment by 64Florian** [comment]
Hello,
Do you use a mouse or a touch screen on you computer ?

**Comment by Ranil007** [comment]
> Hello,
Do you use a mouse or a touch screen on you computer ? 

Hi, I use a mouse!
