### ISSUE TITLE
Ender 3 initial Line

### ISSUE THREAD

**Issue by JacobMcBride** [Ultimaker/Cura#7805]
<!--
When Downloading the latest version of Cura I noticed a problem. The beginning line that starts the filament flowing is way off where it usually is. In Cura 4.4 which I've been using for the longest time. that line is a few mm away from the edge. now in Cura 4.5 and 4.6 it is right on top of it, causing problems with the line. I am using an Ender 3. I contacted Ultimaker directly and was told the latest update 4.6.1 should have fixed it but it hasn't. 

**Application version**
4.6.1
**Platform**
Windows 10, RTX 2060 Super

**Printer**
Ender 3

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by jellespijker** [comment]
Could you give us some more info, maybe fill in the bug report template and he go nuts, send a log file while you're at it ;-)
