### ISSUE TITLE
Cura 4.6.1 prints outside the Printbed - Anycubic Mega.

### ISSUE THREAD

**Issue by Gothmoth88** [Ultimaker/Cura#7809]
**Application version**
Version 4.6.1

**Platform**
Windows 10 Build 1909 - Ryzen 3700x 64GB Ram

**Printer**
Anycubic Mega i3

**Reproduction steps**

i slice a model in cura and save the gcode file to a SD card. i print from the SD card.

the prints are not centered on the printbed. 
print is shiftet to the front and left, like shown in the attached topview sketch.
when i wanted to print a big model the brim was printed outside the printbed.

when i home all axis the print nozzle is exactly at the lower left corner of the printbed.
so i don´t understand why the prints with cura are off.

also the printhead settings in cura only allow negativ numbers. 
i have no idea if this has something to do with my print problem.
but i was told to input positive numbers, but that does not work in cura v4.6.1.
i did not change these settings.
only negative numbers are accepted by cura.

on the image you can see the model is totally in the printable area in cura.
the brim is still on the printbed.
when printed the brim is outside the printbed and the edge of the actual model is right up to the edge of the printbed.

PS:
i removed cura 4.6.1 and all remainings.
installed cura v4.4.1 and i have the same problem... it only accepts negativ numbers for X min and Y min in the printhead settings.
i enter for example 20 or 30.... close the window.... next time i open the window it is back to -20.
when i enter -30 it stays at -30. same as with version 4.6.1.

**Screenshot(s)**
![2020-05-22_185459](https://user-images.githubusercontent.com/65809730/82727319-0a75e400-9cea-11ea-968e-83fde0f6a32e.jpg)
![print](https://user-images.githubusercontent.com/65809730/82727322-0c3fa780-9cea-11ea-860e-5fc36bc52c36.jpg)
![print2](https://user-images.githubusercontent.com/65809730/82727323-0c3fa780-9cea-11ea-89c1-94f6cee014cd.jpg) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**

here is the start of a gcode file that goes wrong.
i must admit i have not clue about gcode files so i don´t know if this helps.

;FLAVOR:Marlin
;TIME:675
;Filament used: 0.622532m
;Layer height: 0.3
;MINX:6.225
;MINY:24.305
;MINZ:0.2
;MAXX:203.775
;MAXY:185.695
;MAXZ:0.275
;Generated with Cura_SteamEngine 4.6.1
M140 S65
M105
M190 S65
M104 S205
M105
M109 S205
M82 ;absolute extrusion mode
G21 ;metric values
G90 ;absolute positioning
M82 ;set extruder to absolute mode
M107 ;start with the fan off
G28 X0 Y0 ;move X/Y to min endstops
G28 Z0 ;move Z to min endstops
G1 Z15.0 F100 ;move the platform down 15mm
G92 E0 ;zero the extruded length
G1 F200 E3 ;extrude 3mm of feed stock
G92 E0 ;zero the extruded length again
G1 F100
G0 Y20 F100
M117 Printing...
G5
G92 E0
G92 E0
G1 F4200 E-7
;LAYER_COUNT:1
;LAYER:0
M106 S255
M204 S3000
M205 X10 Y10
G1 F600 Z0.275
G0 F3000 X91.828 Y25.759 Z0.275
M204 S1800
M205 X8 Y8
;TYPE:SKIRT
G1 F600 Z0.2
G1 F4200 E0
G1 F1320 X92.335 Y25.745 E0.02168
G1 X117.288 Y25.745 E1.08832
G1 X118.061 Y25.756 E1.12137
G1 X118.706 Y25.805 E1.14902
G1 X119.3 Y25.922 E1.17489

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by 64Florian** [comment]
Hello @Lightboxx
> i removed cura 4.6.1 and all remainings.

Did you try to "cleaup" your profile too ? 
Just in case, 
- open Cura, 
 - click on "Help" -> "Show configuration folder" -> you should have a new file explorer opened in a 4.6 folder ...
 - Close Cura
 - rename the 4.6 folder to 4.6_Ko 
 - restart Cura 

Thank you

**Comment by 64Florian** [comment]
> ![print2](https://user-images.githubusercontent.com/65809730/82727323-0c3fa780-9cea-11ea-89c1-94f6cee014cd.jpg)

in fact, red circle are for the "size of the head" with the nozzle as reference (those settings are used when you define _print sequence_ on "one at the time" to prevent collision of the head and a previously printed object)

**Comment by Lightboxx** [comment]
why are only negative numbers allowed? 
people tell me i should use positive numbers. but cura won´t accept positive numbers as i wrote.

> Did you try to "cleaup" your profile too ?

yes as i wrote, i removed cura 4.6.1 and all remainings.
i was even ging through the windows registry.

**Comment by 64Florian** [comment]
Hello @Lightboxx 
In fact registry and 4.6.1 folder are **Not** your profiles folder ... 
Please try to do this : 

  -  open Cura,
   - click on "Help" -> "Show configuration folder" -> you should have a new file explorer opened in a 4.6 folder ...
   - Close Cura
   - rename the 4.6 folder to 4.6_Ko
   - restart Cura

**Comment by gravesfamily** [comment]
I have the same issue, I think.

New install of Win10, so I had to install a fresh copy of Cura 4.6.1. I had written down a bunch of my settings, including the printhead settings, the ones I've been using successfully for years. Those settings are:
X min 35mm
Y min 70mm
X max 55mm
Y max 60mm

However, using the dialog box, I cannot make the xmin or ymin anything other than a negative number. Fortunately, I am able to edit the inst.cfg file in the definition_changes folder and set the line to be:
machine_head_with_fans_polygon = [[35, 60], [35, 70], [55, 60], [55, 70]]

The awesome thing is that if I open Cura and go into the dialog box, it still shows 0 for the xmin and ymin fields. Fortunately, it doesn't seem to rewrite those numbers if I edit something else, like the start gcode.

I did try running Cura as an admin, but that didn't change anything. I also went back to Cura 4.3 and it had a similar issue, so this has been around for awhile, at least in my Windows configuration.

**Comment by Ghostkeeper** [comment]
> people (some) always tell me i should put in positive numbers to fix this problem.

That information used to be correct, but is outdated now. These are the coordinates of the edges of the print head, relative to the nozzle position. Assuming your nozzle is inside your print head, the two "min" values must be negative and the two "max" values must be positive.

> others say the printhead settings have no influence except when i choose to print "one at a time" in cura.

That's correct. So let's not talk about these because they really don't have anything to do with your issue.

Real problem
----
If the build volume is not centred on the physical build plate, then either the printer dimensions are wrong, the endstops are wrong on the printer, or the firmware is wrong.

The printer dimensions are [listed](https://www.anycubic.com/products/anycubic-i3-mega) as 210x210x205, which is also the default in Cura so that part seems to be correct to me.

The endstops determine on your printer where the 0,0 coordinate is. So you can try adjusting those to centre the print better.

Sometimes the firmware applies an offset in an attempt to centre the print. I don't expect that to be wrong if Anycubic did that themselves, but maybe if you loaded up your custom firmware you need to adjust that offset as well.

**Comment by Lightboxx** [comment]
hi,

thx for the answers. 

the endstop for the y-axis (which is most affected) is fixed on my printer. i can´t adjust that.
and when i home all axis the printhead moves to the lower left edge of the printbed , that seems to be ok too.

how can i check if the gcode is centered to the bed? 
i have no clue about gcode commands.

**Comment by Ghostkeeper** [comment]
To check if anything is centred to the bed, you have to measure with a ruler. The printer has no sensor of where the bed is, so you can't tell by just the g-code or the display.

If you open the g-code file with a text editor you'll find loads of `G0` and `G1` commands. Those tell your printer to move somewhere, and they usually have coordinates with them to tell the printer where it needs to move. I'd expect that those correspond with the coordinates you see on that display.

**Comment by GregValiant** [comment]
It's been years so I'll go ahead and close this.  Let me know if that is premature.  The problem I see here is the "Home Offset" setting in the printer so it is not a Cura issue.
