### ISSUE TITLE
No Experimental tree wall thickness 4.6.1

### ISSUE THREAD

**Issue by n5vei** [Ultimaker/Cura#7819]
I am using 4.6.1 Cura. I used trees for support material before upgrading to 4.6.1.  Now when I use tree support, the tree wall thickness is extremely thick!  I have all boxes showing when I try to find wall thickness, but it is not there.  I cannot use tree support because of the thickness.

**Comment by 64Florian** [comment]
Hello,
Could you share your workspace please ? 
Open your project with an object inside, then select "Flie" -> "save" -> "save" -> provide a filename -> select "open folder" 
Zip this your new "3mf" file and add it in this ticket

Thank you

**Comment by n5vei** [comment]
[CCR10S_Pilgrim_City_House_C_Back1.zip](https://github.com/Ultimaker/Cura/files/4674597/CCR10S_Pilgrim_City_House_C_Back1.zip)

**Comment by Ghostkeeper** [comment]
The wall thickness of that support seems pretty normal to me:

![image](https://user-images.githubusercontent.com/2448634/82895321-53c96c00-9f54-11ea-90b5-6cf3dae7fcd6.png)

If it prints wrong, try adjusting the Support Line Thickness setting.
