### ISSUE TITLE
Cura 4.6.1 flow does not work

### ISSUE THREAD

**Issue by Kaicura** [Ultimaker/Cura#7821]
Cura 4.6.1
Egal was ich bei Fluss einstelle, es ändert sich nichts an der Wandstärke.
Testwürfel mit 2 Wänden a 0,42 mm bei 100 % Fluss = 0,76 mm breite
Bei 150% Fluss auch 0,76mm breite
Habe mal das Profil mit 100% Fluss hochgeladen

[Test_Profil_CUBE.zip](https://github.com/Ultimaker/Cura/files/4674876/Test_Profil_CUBE.zip)

Google translated version below:

Cura 4.6.1
No matter what I set in the river, nothing changes in the wall thickness.
Test cube with 2 walls a 0.42 mm at 100% flow = 0.76 mm wide
At 150% flow also 0.76mm wide
I uploaded the profile with 100% flow

**Comment by mahtDFR** [comment]
I'm seeing this when I open your project file.
![image](https://user-images.githubusercontent.com/17821912/82822484-26be8000-9ea6-11ea-8215-945c0623fbf0.png)

How did you add this machine definition?

**Comment by Kaicura** [comment]
It is from Site 3D nexus
, Artillery Sidewinder x1 cura Profil s and Printer and Nozzel definations 
--
Gesendet über myMail für Android Montag, 25 Mai 2020, 04:39PM +02:00 von maht  notifications@github.com :

**Comment by Kaicura** [comment]
Here the Files for CURA 4.6.1 
[3DN Artillery SWX1 and Genius Cura 4.6.1.zip](https://github.com/Ultimaker/Cura/files/4678687/3DN.Artillery.SWX1.and.Genius.Cura.4.6.1.zip)

Import the  Cura profils at Profilsmanager, Copy the  Folders to Cura / resources

**Comment by Ghostkeeper** [comment]
The reason is that your object overrides the Flow setting in its per-object settings.

![image](https://user-images.githubusercontent.com/2448634/82896914-0ef30480-9f57-11ea-8c46-e0c98993af35.png)

The per-object settings override the global (or per-extruder) settings.

**Comment by Kaicura** [comment]
Thanks a lot for your great and fast support
