### ISSUE TITLE
I don't know how to use sdk.

### ISSUE THREAD

**Issue by Shine6Z** [Ultimaker/Cura#7822]
How do I find specific SDK documentation for the software, such as method descriptions?

**Comment by fieldOfView** [comment]
What do you want to do with the SDK?

There is a wiki for both Cura and Uranium:
https://github.com/Ultimaker/cura/wiki
https://github.com/Ultimaker/uranium/wiki

There is also a number of example plugins to learn from:
https://github.com/Ultimaker?q=example

**Comment by Shine6Z** [comment]
Specific descriptions of classes and methods in the code, such as references to some classes in the UM namespace, but I don't know how many of them came about.




---Original---

**Comment by Shine6Z** [comment]
@mahtDFR waht information ?

**Comment by fieldOfView** [comment]
Again, what do you want to do with the SDK? Do you want to write a plugin to achieve a certain task? We can help you get started with that. But there is currently not a single document that you can read to know all about all the classes in Cura and Uranium.

**Comment by mahtDFR** [comment]
@Shine6Z as above, to help you it would be good to know your intention.
