### ISSUE TITLE
Geeeteck A10 setting :  Printer Area is Wrong 

### ISSUE THREAD

**Issue by anauff** [Ultimaker/Cura#7827]
In cura 4.6.1 when selecting the geeeteck A10 printer the default printable area is : 

X : 220
Y : 260
Z : 220

It is wrong, the right area ( verified in printer manual) is  

x : 220
Y : 220
Z : 260

**Comment by mahtDFR** [comment]
We're not really responsible for these profiles, they're externally contributed. As a temporary solution are you able to edit the area in your machine settings? Someone will need to contribute a fix for it as a pull request.

**Comment by anauff** [comment]
hello,

Sure I change the parameter in my local cura printer configuration. I just
rapport for the others


David
