### ISSUE TITLE
Work window scale issue

### ISSUE THREAD

**Issue by Ac1dDra90n** [Ultimaker/Cura#783]
ON systems where I have two monitors of different size/dpi the working window does not auto scale for the current window. i.e. going from a MS Surface screen to a 1080p 40" monitor. The scale of the window stays at the 150% enlargement of the MS Surface for both monitors. Cura 15.4.6 does auto scale the working window.

**Comment by ianpaschal** [comment]
This is almost 2 years old and a very minor problem so I'm closing this.

**Comment by Ghostkeeper** [comment]
We've had similar reports around development of 2.5 and 2.6. As far as I know they are now all fixed.
