### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#7833]
Image here is missing
https://appimage.github.io/Cura/

**Comment by 64Florian** [comment]
For support team: 
![Capture d’écran 2020-05-27 à 00 25 29](https://user-images.githubusercontent.com/34726380/82956232-a8023980-9fb0-11ea-9f3a-cfe7445a755e.png)

The image link is 
https://github.com/Ultimaker/cura-build/packaging/screenshot.png
-> HTTP 404 Not found

**Comment by nallath** [comment]
Where does it get the URL from? It should be https://github.com/Ultimaker/cura-build/blob/master/packaging/screenshot.png

**Comment by leoheck** [comment]
The current and broken image address is this one
https://github.com/Ultimaker/cura-build/packaging/screenshot.png

**Comment by nallath** [comment]
> The current and broken image address is this one
> https://github.com/Ultimaker/cura-build/packaging/screenshot.png

Yes, I know, but that URL can't ever work. But where does it get that (broken) url from?

**Comment by Ghostkeeper** [comment]
That's here: https://github.com/Ultimaker/cura-build/blob/c43b8bce8c38e493bd28291402cc1f53b72e27b6/packaging/cura.appdata.xml#L15

**Comment by Ghostkeeper** [comment]
I added a screenshot. The README of the main Cura repository badly needed one anyway.
