### ISSUE TITLE
Cura does not slice unless reinstalled

### ISSUE THREAD

**Issue by sszymecz** [Ultimaker/Cura#7846]
Hi, since couple of days I have problems with Cura. It does not want to slice at all. I load the STL, choose profile, press Slice and the small window pops up in the right bottom corner stating "Slicing" but nothing is happening. The procesor usage is zero. Cura basicly is not doing anything. It applies to all kinds of different STLs. Restarting PC doesn't help. Restarting Cura doesnt help. The only thing that cures the problem is uninstalling and installing cura again. Then it works fine, it slices on the first run. The moment I close it and reopen the problem starts again. Running it on Win10 64bit.
![cura](https://user-images.githubusercontent.com/66139025/83296258-60fe8900-a1e8-11ea-9113-8d4fbd5ca21e.jpg)

**Comment by Ghostkeeper** [comment]
Could you fill in the bug template? Things like a log would be very helpful. Or even a project file. You graciously erased the template when you created that ticket.
