### ISSUE TITLE
https://github.com/Ultimaker/Cura/wiki/Plugin-Directory contains plugins links that dont work?

### ISSUE THREAD

**Issue by twobob** [Ultimaker/Cura#7853]
**Application version**
4.6

**Platform**
windows

**Printer**
creality

**Reproduction steps**
I visitied https://github.com/Ultimaker/Cura/wiki/Plugin-Directory and noted that the link to ElectricPrintCostCalculator seems to be a plugin that no longer works.

**Additional information**
I installed it and it didn't work

**Comment by nallath** [comment]
Oh yeah, that list is completely outdated (and has been replaced by a built in plugin repository called "Marketplace"). 

I will remove the wiki page.
