### ISSUE TITLE
Drag and Drop functionality on OS X

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#79]
Application Version: 15.06
Platform: OS X 10.9.5

Steps to Reproduce:
Drag and drop a .stl file onto Cura

Actual Results:
Cura accepts the .stl file, but OS X shows an animation that implies otherwise (the file moves back to where it was dragged from)

Expected results:
OS X would be notified that the drag and drop succeeded to eliminate the reverse animation (just a guess)

**Comment by Ghostkeeper** [comment]
It's really nice to have such extensive bug tests, Xisle :) Thank you!

**Comment by Xisle** [comment]
You're welcome. When I finally get a Print button to show up, I can continue testing ;)

**Comment by Xisle** [comment]
I think objects dropped into Cura should be centered on the coordinates of the drop if possible.

**Comment by Xisle** [comment]
It would also be nice if the Cura icon (in the OS X tray) accepted drag-and-drop events.

**Comment by awhiemstra** [comment]
I actually committed a change for the last one yesterday, though I need to check if it actually works now.

**Comment by nallath** [comment]
So, does it work now?
