### ISSUE TITLE
Support separation Layer (with permanent marker)

### ISSUE THREAD

**Issue by EcoPrinter96** [Ultimaker/Cura#7912]
I recently found a very cool method to make very nice support surfaces. (https://forum.prusaprinters.org/forum/english-forum-general-discussion-announcements-and-releases/new-method-of-printing-perfect-supports/)

I already made some tests with Simplity3D but it is very difficult to get a usable gcode. 

I tried some settings in cura to make it work. I got decent results with using Gradual support infill steps to get 100% density with the regular extruder. And using the interface layer with my permanent marker (second extruder). The only problem is that the layer thickness of the permanent marker layer can only be set to half of the normal layer height. Witch means that there is a gap of half the layer hight between the support layer and the part. With this permanent marker method it is possible to directly print on the marker layer with no gap.(surface quality is very nice)

 
The easyest way to make it work is: the ability to set the layer thickness of the (pen) extruder to 0 or almost 0 (like 0.01). 

To implement the Feature correctly:
Make a new custom setting called separation layer for example. 
There you can set witch extruder to use for this separation layer and the thickness. (maybe "density" of the layer but this should be 100%)
And to avoid the need of configuring a second extruder in the firmware of the printer: a setting in the extruder configuration to set the extruder as a virtual extruder (this offsets the extruder in the gcode directly (in x,y and if possible in z direction) 

I have added a video to show the idea. 

I hope the implementation is possible.

**Comment by mahtDFR** [comment]
We discussed this and decided that it's something that's heavily dependent on printer modification, so not something we're can give priority to. I have deferred it.
What you're trying to do could probably be achieved with a post processing script, though.

**Comment by fieldOfView** [comment]
A halfway point to implement this, which could be useful for other usecases too, is being able to set an extruder for ironing.

**Comment by EcoPrinter96** [comment]
The modification for the 3D Printer is very simple. You just need a clickable permanentmarker and some 3D printed parts. 

Yes, an ironing feature for the imterface layer with another extruder would work. And is probably useful for other applications as well. 

Here are some pictures of my modification. 
![1591956811743877375179542851509](https://user-images.githubusercontent.com/66730918/84492228-2ac00f80-aca6-11ea-91bd-f48484ca74a7.jpg)
![15919568341962723696643109704532](https://user-images.githubusercontent.com/66730918/84492271-3c091c00-aca6-11ea-85ac-636b38e05173.jpg)
