### ISSUE TITLE
PauseAtHeight getting wrokg next XY position

### ISSUE THREAD

**Issue by adripo** [Ultimaker/Cura#7918]
**Application version**
4.7(master)

**Platform**
Wondows

**Printer**
FlyingBear Ghost 4S

**Reproduction steps**
1. Set pauseAtHeight in Post Processing extension
2. Generate gcode
3. Open file and find wrong position after pause

**Additional information**
I find out that the wrong X and Y positions are the values set to max jerk M205, that is the first X and Y values found on the next layer.
I already fixed this by excluding lines that start with command M205.
If you have a better solution please edit my pull request.

**Comment by GregValiant** [comment]
The fix was merged so I'll close this.
