### ISSUE TITLE
unreadable text in "Discard or Keep changes" window

### ISSUE THREAD

**Issue by GalaxAjh** [Ultimaker/Cura#7926]
**Application version**
4.6.1

**Platform**
Mac OSX 10.13.6

**Printer**
Dagoma DiscoEasy 200 (dual extruder)

**Reproduction steps**
Changing the material in tab (top of screen in window "prepare")

**Screenshot(s)**
![Capture d’écran 2020-06-11 à 23 05 12](https://user-images.githubusercontent.com/28156006/84439494-9bc8de00-ac38-11ea-9502-1354fd5ec1d6.png)
![Capture d’écran 2020-06-10 à 22 28 01](https://user-images.githubusercontent.com/28156006/84439498-9e2b3800-ac38-11ea-8bbb-ee5dd433ecc3.png)

**Actual results**
The text in unreadable

**Expected results**
Readable text. Eventually, to resize the window 

**Additional information**
ScreenShots are in english and in french

V.

**Comment by rburema** [comment]
What is your screen resolution? Do you apply any screen-scaling?

**Comment by GalaxAjh** [comment]
No it is just a part of the screen. My monitor is an old Apple 30' display at the native résolution
juste below, a screen shot of the full display. 
![Capture d’écran 2020-06-12 à 12 00 01](https://user-images.githubusercontent.com/28156006/84491091-4f1aec80-aca4-11ea-899b-072a393e3ba1.png)
![Capture d’écran 2020-06-12 à 11 51 22](https://user-images.githubusercontent.com/28156006/84491113-55a96400-aca4-11ea-8aaa-46c54a9b67be.png)

**Comment by rburema** [comment]
I did some investigation, and it seems this (sub)window doesn't listen to the width/height we get from the theme, but stays the same dimensions no matter what value is put in there.

I'll bring it up with the rest of the team next week.

**Comment by Ghostkeeper** [comment]
I've made three changes:
* I've fixed getting the width/height from the theme.
* I've allowed resizing that dialogue.
* I've turned on eliding of the setting names. So if the setting names are too long they'll be cut off with an ellipsis. This way the text remains readable.
