### ISSUE TITLE
Translation error -> French

### ISSUE THREAD

**Issue by GalaxAjh** [Ultimaker/Cura#7927]
**Application version**
4.6.1

**Platform**
Mac OSX 10.13.6

**Printer**
Dagoma DiscoEasy 200

**Reproduction steps**
Translation error 
On the translation, it is written "_Tour primaire_" witch means "_Primary Tower_"
The good text for "_Prime Tower_"must be "_Tour d'amorçage_"
Prime -> Amorçage

**Screenshot(s)**
![Capture d’écran 2020-06-11 à 23 31 53](https://user-images.githubusercontent.com/28156006/84441983-0ed45380-ac3d-11ea-9b22-4458cf89a8ae.png)
![Capture d’écran 2020-06-11 à 23 03 34](https://user-images.githubusercontent.com/28156006/84441998-1693f800-ac3d-11ea-9bbd-2b153c1c61f4.png)

**Actual results**
You can find this in tabs Material and Dual Extrusion. Probably in other tabs but I do not use for the moment

V.

**Comment by fieldOfView** [comment]
I think this was recently fixed (for Cura 4.7) here: https://github.com/Ultimaker/Cura/pull/7838

**Comment by mahtDFR** [comment]
Fixed indeed, will close this off now.
