### ISSUE TITLE
[4.6.1] Scaling updates incorrect values after rotation

### ISSUE THREAD

**Issue by Mearman** [Ultimaker/Cura#7946]
After rotating the model and updating the absolute scale for the Z axis, the scale percentage updates on the Y axis.

![image](https://user-images.githubusercontent.com/1331872/85015978-cfd45f80-b160-11ea-8447-9b32c1a3556c.png)

**Comment by jellespijker** [comment]
Yes. this is probably a duplicate of #4136

**Comment by nallath** [comment]
It is.
