### ISSUE TITLE
[4.6] problem in generating walls 

### ISSUE THREAD

**Issue by mehran-Bgh** [Ultimaker/Cura#7949]
**4.6**

**Windows 10**

**Ender 3**

I have designed a heart shape mold with Autodesk Inventor. after I generate the G-code and print it I realized some surface problems on the model. when I rechecked the preview of the Cura I realized the walls didn't generate in some simple parallel lines. 

**Screenshot(s)**
![Annotation 2020-06-19 100321](https://user-images.githubusercontent.com/50265019/85100153-a5dc7500-b214-11ea-8ab4-0eb5c97850f1.png)
![Annotation 2020-06-19 100355](https://user-images.githubusercontent.com/50265019/85100158-ab39bf80-b214-11ea-8460-25f34004614d.png)
![image](https://user-images.githubusercontent.com/50265019/85100197-c99fbb00-b214-11ea-983d-2387456b4586.png)

Generating this kind of wall increased the build time and ruin the quality of the surface. 
**Project file**
[CE3_Under side mold.zip](https://github.com/Ultimaker/Cura/files/4802634/CE3_Under.side.mold.zip)

**Comment by smartavionics** [comment]
Unfortunately, the model has problems. Install the Mesh Tools plugin from the marketplace to get these warnings...

![Screenshot_2020-06-19_06-55-29](https://user-images.githubusercontent.com/585618/85101291-f98d9500-b1f9-11ea-8ba4-d141bf55cae7.png)

The model appears to have thickness to the walls but also a solid top and bottom, that's not going to work...

![Screenshot_2020-06-19_06-58-05](https://user-images.githubusercontent.com/585618/85101446-54bf8780-b1fa-11ea-8f7e-83a7e0226b89.png)

**Comment by mehran-Bgh** [comment]
you are absolutely right. thanks my friend
