### ISSUE TITLE
Gap being added to wall section

### ISSUE THREAD

**Issue by nguse** [Ultimaker/Cura#7964]
**Application version**
4.6.1

**Platform**
Mac

**Printer**
Creality Ender 3

**Reproduction steps**
The wall size is 2.4mm and I'm using a 0.4mm tip with a wall line count of 3 (other than increasing the wall line count from 2 to 3, no changes have been made to the default configuration from the standard print quality 0.2 profile).

**Screenshot(s)**
With addition:
![Screen Shot 2020-06-22 at 9 30 18 AM](https://user-images.githubusercontent.com/20205998/85312550-d36f2b80-b46b-11ea-98a0-296955cbe135.png)

Without addition:
![Screen Shot 2020-06-22 at 9 40 47 AM](https://user-images.githubusercontent.com/20205998/85313242-bc7d0900-b46c-11ea-8f20-43e90f999e1d.png)

**Actual results**
The "with-addition" model adds a tiny gap in the middle of the wall attached to the addition, large enough that it becomes two separate walls after the print completes.

The  "without-addition" does not have the gap and prints as expected.

The gap does not really show up until it's printed, but I noticed on the first layer of the preview, the slicer is adding a weird infill to one section of the wall.

**Expected results**
Gap added inside of the wall shouldn't exist.

**Project file**
STL files:
[models.zip](https://github.com/Ultimaker/Cura/files/4814494/models.zip)

**Comment by rburema** [comment]
> The wall size is 2.4mm and I'm using a 0.4mm tip

The size of the tip isn't always precisely the width that gets deposited, depending on a whole host of factors, most of which are outside of Cura's control. This is why it says 'reducing line width slightly could result in better prints' on the hover-over text of 'line width'. In fact, on our own Ultimaker profiles, line-width is set to 0.35mm (or even lower in some instances for inner walls), even though the tip is also 0.4mm (other profiles are contributed by the community, and we can't test them here, so we just have to trust that they are correct).

This is (probably) also why it doesn't show up in the preview, but it might show up in your print.

> but I noticed on the first layer of the preview, the slicer is adding a weird infill to one section of the wall.

We're working on this ('weird infill') part (as well as a whole host of related issues & improvements) in the engine. It's a rather large change, so it might be a while before it makes it into a release though.

**Comment by nguse** [comment]
Interesting, so by setting that line width to less than the nozzle, it's forcing some additional overlap between the walls then if I understand properly?

**Comment by Ghostkeeper** [comment]
You understood that properly. It tends to make the walls a bit stronger at the cost of having a more equalised flow. Line width isn't necessarily the same as the nozzle size. However your profile doesn't do this (it just has a line width of 0.4mm everywhere) so that is off topic.

I think what you really just want to do is either to set "Fill Small Gaps Between Walls" to "Nowhere" or to enable "Filter Out Tiny Gaps". You're explicitly creating a gap between the walls here so you probably don't want that gap to be filled.
