### ISSUE TITLE
temprature in profiles 

### ISSUE THREAD

**Issue by Alssund** [Ultimaker/Cura#7982]
if I change a temperature in a profile, then shows it right in print options but not update the value in profile manager when I have pressed the update bottom

**Comment by mahtDFR** [comment]
Please save a project file (File -> Save...), zip up the .3mf file and attach to this issue so I can try to reproduce it with the same settings as you.

**Comment by Alssund** [comment]
I have made a document hope you understand it! (se attachement 
[temp differense.docx](https://github.com/Ultimaker/Cura/files/4838521/temp.differense.docx)

**Comment by Alssund** [comment]
Now I have made a Custom printer profile, and the truble is gone!
It Look like it is when I used you pre installed "Anycubic Chiron" printer settings

**Comment by nallath** [comment]
Check the value in the Extruder 1 tab. It should be correctly set there.

**Comment by Ghostkeeper** [comment]
The Extruder 1 tab will be empty, sadly, due to a different bug.
