### ISSUE TITLE
Tool Path Cloning for Duplicated Models

### ISSUE THREAD

**Issue by BusterCh3rry** [Ultimaker/Cura#7987]
**Is your feature request related to a problem? Please describe.**

When duplicating an imported model to create multiple copies, models are often sliced in a way such that the path of the extruder is not identical for each duplicated part. While Cura attempts to slice the entire array of models in an optimized way with priority on minimizing travel moves, the process often results in inconsistency of both surface finish and structural strength between models.

Currently, the only reliable process to to ensure that 10 printed objects are virtually identical, the same object must be printed in 10 separate jobs which requires start-up and cool-down time for each job as well as time for part removal.

**Describe the solution you'd like**

An option to generate duplicate models such that the toolpath for each layer relative to each duplicated model is identical.

Where identical geometry is detected, in point, walls, infill, and out point tool path moves should also be identical. If the toolpath movement of a single model can be calculated first, duplicate models may be created by maintaining the same toolpath movement while translating the position of the starting point for each duplicate model relative to its position on the build surface.

Using the same relative start and stop point per model may increase time for travel moves between duplicated models, but the resulting uniformity in structural strength and surface finish would be certainly worth any extra time required. As an example, if the requested feature results in an additional tool path travel of 5-7 minutes per print job for an array of 10 parts, it would still save time in eliminating redundant start-up and cool-down sequence for 10 different print individual print jobs. The integrated cost savings over time of reducing start-up, cool-down, and part removal labor could be significant. Most importantly, tool path cloning ensures virtually identical surface finish and structural strength between parts without having to run multiple print jobs.

I am unclear as to which point of the slicing process would be most beneficial to implement the option, however I suspect that it may be during the layer-part creation step and/or gcode generation step.

**Describe alternatives you've considered**

Manual adjustment of Z-seam alignment settings may be used to influence the starting position of the extruder for each model in the array of duplicate parts but use of these options does not guarantee identical tool-path travel for each layer including inner wall order and exact infill.

**Affected users and/or printers**

All - Specifically users who desire uniform surface finish and mechanical strength between printed models.

This feature would be particularly valuable to makers and/or small businesses that may not have the luxury of running multiple machines. To my knowledge at this time, this feature is not available in any other commercial or open source slicing software for Ultimaker or other desktop class FDM machines.

**Additional context**

Can provide screenshots, photos, or video of evidence of differences in toolpath behavior between duplicated models.

**Comment by Ghostkeeper** [comment]
Given correct seam and infill settings, I'd expect the tool path to come out the same for duplicate objects. There is no randomness involved except for some explicit settings (e.g. Z Seam Alignment to "Random"). CuraEngine plans each object separately, even if that object has multiple parts on a layer. Within the part it places the seam in the same way.

The Z Seam Alignment needs to be set to "User Specified" with Z Seam Relative enabled, or to "Sharpest Corner". And helper structures such as support or the brim will not necessarily be unique because they combine with neighbouring helper structures in some cases. For instance that's very visible with Tree Support.

Can you provide a project file where it's different?
