### ISSUE TITLE
[4.6.1] Print Settings - text in input boxes invisible

### ISSUE THREAD

**Issue by Protazy21** [Ultimaker/Cura#7998]
**4.6.1**
**Windows**

**Ender 3 Pro**

**Reproduction steps**
1. Installed Cura with additional plugins: Octoprint, Settings Guide, Sidebar GUI, Thingiverse Browser
2. Noticed the saved values are invisible in the input fields
3. uninstalled Sidebar GUI, Settings Guide - no change
4. reset to default settings by deleting cura folder, went trheough the initial set up - no change
5. uninstalled cura, deleted cura folder from roaming again, installed back, went through initial set up - no change

**Screenshot(s)**

![image](https://user-images.githubusercontent.com/4419551/86096362-1902a880-baab-11ea-8fe0-20f47f3cfc10.png)

**Actual results**
No visible text in any of input boxes

**Expected results**
predefined/saved values visible

**Project file**
N/A

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4850098/cura.log)
**Additional information**

**Comment by Protazy21** [comment]
The text is visible today...

**Comment by Ghostkeeper** [comment]
Maybe a corrupt shader cache or something then.
