### ISSUE TITLE
[4.6.1] MONITOR GUI is a mess

### ISSUE THREAD

**Issue by PigeonFX** [Ultimaker/Cura#8011]
Is this just happening for me or is the GUI for the Monitor tab screwed up for everyone? 

![Screenshot (41)](https://user-images.githubusercontent.com/39096995/86258208-76cde800-bbb2-11ea-8219-0faa5ac594ae.png)

**Comment by fieldOfView** [comment]
You seem to be using a plugin that might be the cause of the mess; none of the "Open fan", "Close fan", "Unlock motor", "Cool down", "SD File" and "Opening Print Job" buttons are provided by Cura itself, and the "Resume" and "Abort print" buttons also look different from the standard ones. Even the button next to the IP address is not a standard button.

The MKS Cura Plugin may need an update.

**Comment by nallath** [comment]
As @fieldOfView says, this is not implemented by us, but by a third-party plugin. Other plugins don't have this issue.
