### ISSUE TITLE
Add "Manage toolheads..." option for non-standard nozzle diameters

### ISSUE THREAD

**Issue by kauedg** [Ultimaker/Cura#8013]
**Is your feature request related to a problem? Please describe.**
VoronDesign printers' toolhead list doesn't offer a customizable toolhead option, for adding nozzles with diameter not listed in the "toolhead" menu (Cura 4.6.1)

**Describe the solution you'd like**
Adding a "Manage toolheads..." option in "Settings->Toolhead->Toolhead" menu.

**Describe alternatives you've considered**
There's the option of setting the line width parameter manually but that requires the creation of new print profiles and we miss the field's auto-calculation feature.

**Affected users and/or printers**
VoronDesign users who use nozzles with 0.1 or 0.2 in diameter.
VoronDesign printers, including the "custom" option.

**Comment by fieldOfView** [comment]
In Cura, the nozzle/toolhead/printcore dropdown is often much more than just a setting for the nozzle size; it selects a different set of quality profiles to use. That is why it is not trivial to just add more sizes; you would also have to add new profiles and for many printers that would mean new profiles for all supported materials.
