### ISSUE TITLE
2.1.2 Retraction Distance setting reseting

### ISSUE THREAD

**Issue by chinzw** [Ultimaker/Cura#802]
When i change the retraction distance from the default of 6.5 it always returns to that value, saving a new profile, or updating doesn't work.

**Comment by chinzw** [comment]
I think i found the culprit of this.
the Material settings are overriding the Profile settings and by default the material profiles have this line in them:
retraction_amount = 6.5

**Comment by fieldOfView** [comment]
Good find. If you remove that line from the material profiles, it should indeed work. All of this has been fully reworked for 2.2 which will handle this much better.

**Comment by soldanr** [comment]
Thanks. I just verified that!
Opened resouces\profiles\materials\pla.cfg and changed the settings.

[general]
version = 1
type = material
name = PLA

[settings]
material_bed_temperature = 55
retraction_amount = 1.5
