### ISSUE TITLE
Foreign language translation is not being done in the profile menu dialog.

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#8024]
**Application version**
Cura Master(or 4.*)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Windows 10 + Intel i5

**Printer**
(Which printer was selected in Cura?)
Any 3D Printer

**Reproduction steps**
1. Select Preferences > Profiles > Select any active quality
2. Displayed only English settings at right table

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![IMG_20200703_144729](https://user-images.githubusercontent.com/39176348/86448323-92232980-bd51-11ea-86c2-6db6d7de0df5.jpg)

**Actual results**
(What happens after the above steps have been followed.)
Even if I change the language, only English name is displayed.

**Expected results**
(What should happen after the above steps have been followed.)
If I change the language, I want to see the setting's name for that language.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)
don't need project file

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
don't need project file

**Additional information**
(Extra information relevant to the issue.)
In the DiscardOrKeep dialog, it is displayed normally in the translated language.
![IMG_20200703_144747](https://user-images.githubusercontent.com/39176348/86448346-99e2ce00-bd51-11ea-93bf-ef42d6363d8e.jpg)

"self._I18n_catalog" processing in QualitySettingsModel.py doesn't seem to be perfect unlike in UserChangesModel.py.

**Comment by mahtDFR** [comment]
Thanks for the report, will discuss

**Comment by mahtDFR** [comment]
This is on our backlog as CURA-7575

**Comment by Ghostkeeper** [comment]
This is fixed for Cura 4.7, through this commit: https://github.com/Ultimaker/Cura/commit/56fc5f9706c9d7e7d3f70a7fc166ad91aedbbc0e
