### ISSUE TITLE
no me permite visualizar la temperatura de la placa de impresión.

### ISSUE THREAD

**Issue by magalicervio** [Ultimaker/Cura#8038]

**Comment by Ghostkeeper** [comment]
![image](https://user-images.githubusercontent.com/2448634/86936413-43550580-c13e-11ea-8058-bf8330203eb3.png)

**Comment by magalicervio** [comment]
[image: image.png]
Buenas tardes, a mi no me sale, ni en ingles, ni en español. No se cual
será el problema. Lo desinstalé y volví a instalar, anteriormente tenía la
versión 4.1.1 y se visualizaba perfectamente.

Saludos

**Comment by magalicervio** [comment]
![image](https://user-images.githubusercontent.com/67930583/86974369-959d2300-c14c-11ea-98cd-48236cf60397.png)

**Comment by fieldOfView** [comment]
![since we're only communicating with images](https://user-images.githubusercontent.com/143551/87014965-1b60b300-c1cd-11ea-9341-e04788187822.png)

**Comment by magalicervio** [comment]
Muchísimas gracias!!!!!
