### ISSUE TITLE
Cura 4.6.1 - continuously hang

### ISSUE THREAD

**Issue by bonoboxita** [Ultimaker/Cura#8047]
Cura 4.6.1 just installed after removing previous Cura 4.5

I'm using Win10 pro, 16GB ram, GTX1080, SSD, triple monitor configuration using Nvidia surround option.

The software is hanging /freezing for few seconds for ANY actions i do. If you change any printing parameters or move an object. 
Even just typing a parameter like layer height is freezing the software.

I saw previous open case suggesting the issue was due to an overlay from the graphic cards software but i'm not using anything similar.

EDIT: i saw also people saying that using multiple monitors is creating issue. I've just tried on one single monitor and still have the same problem.

**Comment by nallath** [comment]
Did you also have the issue with 4.5 or is this a new thing for 4.6.1?

**Comment by bonoboxita** [comment]
no, 4.5 no issue.

**Comment by Ghostkeeper** [comment]
Strange issue! Does the task manager indicate that Cura is using a lot of CPU power while it's freezing, or is it just idling at 0-10%? Is something else taking processing power, such as firewall software?

**Comment by bonoboxita** [comment]
yes...CPU start to spike at 30% and triggering also the fan to increase speed.
It is annoying that even to write the layer height is hanging... i mean, as soon as you click the layer height box Cura is start to hang and slow down

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this issue so far. It's like butter, on my computer.

Could you maybe share a log file then? There may be something in there that can be of help.

**Comment by bonoboxita** [comment]
here the logs file
[cura.log](https://github.com/Ultimaker/Cura/files/4941101/cura.log)
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/4941102/DxDiag.txt)

**Comment by nallath** [comment]
Oh, I see it already. You're slicing 62 objects at the same time. We've recently made a number of improvements regarding that. I also see some other things in the log that have gotten significant improvements for 4.7 

Changing the layer height is probably the most expensive setting to change, since alot of other settings depend on it. 

I'd suggest trying again with 4.7 and see if that solves the issues.
