### ISSUE TITLE
duplicated items start with z-position 0 and not with z-position of source item

### ISSUE THREAD

**Issue by Kiluko70** [Ultimaker/Cura#8056]
I use cura 4.6.1

When i try to duplicate an item with has e.g. z-Position -10 (to print only upper part of item) all the duplicated parts have the z=0 position, so they would be printed completely what cant be the intention of copies.

**Comment by nallath** [comment]
I could reproduce this, so I'll add it to our backlog.

**Comment by mahtDFR** [comment]
This is on the backlog as CURA-7592

**Comment by konskarm** [comment]
After some backlog cleaning, we decided that we won't fix this bug, as we believe it won't get prioritized over other tickets in our already long list of items.

**Comment by Ghostkeeper** [comment]
Lack of priority means it's deferred, right?
