### ISSUE TITLE
Cura 15.04.01 and 03 for Win 64 : missing layers

### ISSUE THREAD

**Issue by lefredo25** [Ultimaker/Cura#806]
For some parts (2) cura generate GCODE file with several empty layer.
I load my .STL file
place it on bed
generate GCODE file
And when I reopen the GCODE file to check it is ok, layers are missing 
several layers everywhere for 1 file and about 15th first layers for the other file.

**Comment by nallath** [comment]
Issues for Cura 15.04 need to be reported on www.github.com/daid/cura. I'd also recommend upgrading to the latest version (since you aren't using it)

**Comment by lefredo25** [comment]
I'm not sure about the version, I'm not using my home computer...
