### ISSUE TITLE
UM2+ stops in middle of print

### ISSUE THREAD

**Issue by eskeyaar** [Ultimaker/Cura#8066]
Strangely after updating to the latest firmware, when I tried to print with a USB cable using repetier host/S3D, Machine just stops printing. S3D Console shows " WARNING: Firmware unresponsive. Attempting to force continue.." nothing happens
Is it due to the latest firmware? 
It happens in the random file, random time.

Thanks in advance.

**Application version**
Marlin 1.0.0
 Mar 15 2018 13:04:08 | Author: Vers:_3.3.0

**Platform**
Windows 64bit

**Printer**
UM2+

**Reproduction steps**
Used Cura 4.6 to update my UM2+ to latest firmware.
Slice older version cura to generate gcode, ( changing the Gcode flavour to Marlin)
Ran sliced gcode print from Repetier host/S3D with USB cable.

**Comment by Ghostkeeper** [comment]
This is not a Cura issue (unless you find that Cura is uploading the firmware wrong) but an issue with the [Ultimaker 2+ firmware](https://github.com/Ultimaker/UM2.1-Firmware). I'll close this issue for that reason. You could make a new issue there. Knowing Ultimaker from the inside though, I can tell you two reasons why it probably won't get fixed.

Ultimaker has no plans - as far as I know - to ever update that again unless a security or health related issue comes up. I had once proposed to add a Tough PLA profile to it but that never got released. There is no team in Ultimaker working on the Ultimaker 2+ any more, or even anyone responsible for it within R&D, although some people are still subscribed to that repository.

Secondly, USB cable printing is never officially supported for the Ultimaker 2 family. While it sort of works (at least via Cura), you'll need to change the g-code flavour in Cura to get it to work okay-ish. The USB port exists to be able to update the firmware only. It was a remnant from Marlin and the UMO that it also accepts g-code input.
