### ISSUE TITLE
Misconfiguration guide

### ISSUE THREAD

**Issue by SandervanG** [Ultimaker/Cura#8089]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
It would be helpful for users when a material selection turns orange, that there is a message explaining why or at least a general direction. This happens for example when you select a material profile that is for an UMS3 when you have an UMS5 printer configuration loaded. You remember it is S3 when you just download it, but after a month you'll forget and it will be quite a task to figure out why it is orange. Screenshot: https://take.ms/b6uQN

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)
There could be like a little description underneath saying: 'Your printer configuration does not match the material'. Or 'Your print core does not match the material profile'. Cura can recognize somewhere in its code that it should be orange, so perhaps this same detection can be converted into a message that at least gives a clue where to look. 

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
 

**Additional context**
(Add any other context or screenshots about the feature request here.)
I believe UX was working on something like this before, not sure if it is the same or just similar, where they were working on improving the messaging. This is a screenshot they shared with me back then. Something like that would probably be a good solution for this too. https://take.ms/cU5Vrb

**Comment by Ghostkeeper** [comment]
I think two people from the forum have been reporting this at the same time. Sorry Sander, I'll close this one because the other discussion has been progressing a bit further and is really about the same issue: https://github.com/Ultimaker/Cura/issues/8086
