### ISSUE TITLE
Slice when you press enter

### ISSUE THREAD

**Issue by zaquarius** [Ultimaker/Cura#8108]
Automatic slicing is nice, so I don't have to click it every time, but then when I want to change multiple settings at once (especially complex settings that take a while to slice) I often have to wait for it to load. It would be nice if I could just press enter to slice (just make it an option under 'slice automatically'). Imo the only thing really missing from cura right now.

Thanks

**Comment by chepo92** [comment]
I think I remember previous versions had a buton to pause auto slice next to slice button

**Comment by fieldOfView** [comment]
That pause/resume button is now a plugin:
https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/PauseBackendPlugin

I think a hotkey to start slicing (when auto slicing is turned off) would be a good addition. Perhaps Ctrl+Enter.

**Comment by chepo92** [comment]
> 
> 
> That pause/resume button is now a plugin:
> https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/PauseBackendPlugin
> 
> I think a hotkey to start slicing (when auto slicing is turned off) would be a good addition. Perhaps Ctrl+Enter.

That one was!, i knew i had saw in my cura at some point, after some reinstalls I forgot to add the plugin, thanks for it anf for octoprint plugin Aldo

**Comment by Ghostkeeper** [comment]
There is a hotkey for this: Ctrl+P. Like, for printing.

**Comment by nallath** [comment]
Well, since it's already there, I guess this can be closed.
