### ISSUE TITLE
[4.6.1] Slicing skips a layer

### ISSUE THREAD

**Issue by louiswouters** [Ultimaker/Cura#8109]
**Application version**
4.6.1

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
1. Load the STL file in Cura
2. Slice the profile with default setting on Standard Quality (0.2mm)

**Screenshot(s)**
![Layer View](https://user-images.githubusercontent.com/66208055/88467130-ef834400-ced3-11ea-98f9-62c41bfd7150.PNG)

**Actual results**
one of the layers is skipped completely

**Expected results**
The print is a continuous part

**Project file**
[Layer Skip.zip](https://github.com/Ultimaker/Cura/files/4976738/Layer.Skip.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4976751/cura.log)

**Additional information**
When rotating the part around the z-axis, other layers are sometimes skipped. Changing the layer height also seems to have an effect on which layers are skipped

**Comment by smartavionics** [comment]
The model isn't manifold (watertight) so you can expect there to be problems. Install the mesh tools plugin from the marketplace to get these warnings.

![Screenshot_2020-07-26_07-28-17](https://user-images.githubusercontent.com/585618/88473060-b8338800-cf11-11ea-9bec-1348d158e422.png)

**Comment by louiswouters** [comment]
Thanks, I will install the plugin.
