### ISSUE TITLE
Printer Axis Origin (Cartesian )

### ISSUE THREAD

**Issue by soldanr** [Ultimaker/Cura#811]
It would be great to see the Cartesian origin in the bounding box of the printer area again to give a frame of reference on the bed like in the old Cura. It makes it a lot easier for teaching purposes to people unfamiliar with motion controllers.

![image](https://cloud.githubusercontent.com/assets/3262413/16153344/8fb8301e-346b-11e6-9ff9-c74357d94a15.png)

**Comment by Ghostkeeper** [comment]
Agreed. What do you think would look nice for the case when the axis origin is in the centre of the bed though?

**Comment by soldanr** [comment]
I like to teach the right hand-rule for the axis layout. I think if we had an X-axis and a Y-axis it will be easy to visualize the Z-axis. It would be neat to have a semi-transparent X and Y axis only so we don't bother with a Z axis on the center of the plate. This way we know at last which quadrant is positive and negative on both axis. I like the bluish arrows to match the color of the GUI. Here are some options:

![image](https://cloud.githubusercontent.com/assets/3262413/16198345/385341ee-36cb-11e6-83ff-9d0a50dfe4ef.png)

**Comment by fieldOfView** [comment]
I like the subtle marks on the middle of the buildplate edges. The red/green axis indication on the buildplate origin also works with the overall feel of the app.

The mark in the center of the buildplate looks a bit out of place to me. I think a "center-indication" (it's not the origin!) could be useful though.

**Comment by Ghostkeeper** [comment]
> (it's not the origin!)

It could be. When `machine_center_is_zero` is true, it is the origin.

**Comment by fieldOfView** [comment]
It's... complicated ;-). The translate tool presents it as the origin, regardless of the machine_center_is_zero setting.

**Comment by bond4u** [comment]
Machine zero marker would be nice.

**Comment by fieldOfView** [comment]
2.4 has an origin indication, see https://github.com/Ultimaker/Cura/pull/1078#issuecomment-256182691
This indication moves to the center of the buildplate if machine_center_is_zero is checked
