### ISSUE TITLE
Creality Ender Pro 3 print settings issue

### ISSUE THREAD

**Issue by YEETmaxter** [Ultimaker/Cura#8124]
Greetings, 
We are new to this, so please bear with us. THANK YOU for any information you can offer us. Cheers.

**Ultimaker Cura Version 4.6.2**
**Mac 10.14.6 Mojave**
**Selected: Creality Ender 3 Pro - Printer**

1.Added Printer
2.Attempted to print, but it continues to print off-center. 
We are seeking the correct coordinates for the printer settings, please and thank you! 

Here are our current settings:
Printer Settings:
x-235mm
y-235mm
z-250mm
Rectangular build plate shape

Printhead settings:
x min: -26
y min: -32
x max: 32
y max: 34
gantry height - 25
number of extruders - 1

; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder
G28 ; Home all axes
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish

G91 ;Relative positioning
G1 E-2 F2700 ;Retract a bit
G1 E-2 Z0.2 F2400 ;Retract and raise Z
G1 X5 Y5 F3000 ;Wipe out
G1 Z10 ;Raise Z more
G90 ;Absolute positionning

G1 X0 Y{machine_depth} ;Present print
M106 S0 ;Turn-off fan
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed

M84 X Y E ;Disable all steppers but Z

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
Make sure 'origin at center' is unchecked. It should be by default, but I can find some reports online of people who struggled with that.

Otherwise, as far as we know, the offsets in Cura are 'correct', in as far as they where contributed by the community.

This might not be a problem within Cura, but with the (calibration of) the printer?

**Comment by YEETmaxter** [comment]
Thank you, rburema. Origin at center was not checked. Just want to make sure all our offsets (especially G-codes) are correct. Might you or anyone know anywhere we could find all correct coordinates? I have tried contacting Creality - no response as of yet. Sigh.

**Comment by rburema** [comment]
Though I seem to remember this coming up in a different context. It might depend on the firmware? In that case, you could perhaps try x/y = 220x220mm since that is the case for the not-pro version.

**Comment by YEETmaxter** [comment]
I'll look into firmware - many thanks, rburema.

**Comment by Ghostkeeper** [comment]
I've also seen that the end stops are sometimes mounted wrong or inaccurately on the Ender 3 Pro which would make it print off-centre.

**Comment by Ghostkeeper** [comment]
We are not in a position to really help you with this, because we don't have an Ender 3 Pro in the Ultimaker office. If you've found what the problem is, can you let us know?
