### ISSUE TITLE
cura 4.6.2 plante

### ISSUE THREAD

**Issue by tipoussin17** [Ultimaker/Cura#8130]
bonjour je dois ré-installer cura a chaque fois que je le ferme et que je veux le ré-ouvrir. est-ce Normal?

**Comment by fieldOfView** [comment]
No, that is not normal.

Could you please ask your question in english, and fill in the template, so we can help you better?

**Comment by tipoussin17** [comment]
the layer view is not displayed at certain height, I cannot preview when I cut my part.
la vue du calque n'est pas affichée à une certaine hauteur, je ne peux pas prévisualiser lorsque j'ai coupé ma pièce.

**Comment by tipoussin17** [comment]
the layer view is not displayed at certain height, I cannot preview when I cut my part.
