### ISSUE TITLE
Add movement control by 3DCONNECTION SpaceMouse

### ISSUE THREAD

**Issue by meltonpieman** [Ultimaker/Cura#8132]
**Is your feature request related to a problem? Please describe.**
As a spacemouse user I find having to resort to 'ordinary' mouse use to control the view of the build platter a little anoying. 

**Describe the solution you'd like**
Addthe necessary module/code to enable control by the 3DCONNECTION SpaceMouse. 
 
**Describe alternatives you've considered**
Prusaslicer have added it already.

**Affected users and/or printers**
Anyone who uses the SpaceMouse for 3D design would welcome this.

**Additional context**
nil

**Comment by fieldOfView** [comment]
Duplicate of #1152

There is a plugin here: https://github.com/smartavionics/RawMouse
