### ISSUE TITLE
Infill Layer Thickness => Infill Layer Multiplier

### ISSUE THREAD

**Issue by pietchaki** [Ultimaker/Cura#8140]
When I change the _Layer Height_ setting, it leads to "incorrect" _Infill Layer Thickness setting_ (not a multiple of _Layer Height_).

Adding a new setting to infill, that sets a _Layer Height Multiplier_, so when I change the _Layer Height_, the infill height changes accordingly would solve this. 

Not sure if this is really useful for much people, I use it only in some prints, and thought it can help.

**Comment by Ghostkeeper** [comment]
We did have an "Infill Layers" setting at some point. But it was removed at the behest of UX: https://github.com/Ultimaker/Cura/commit/d0b5fe84b8fb6e039652ca0ffabfabfcaf853c79.

It was seen as confusing.
