### ISSUE TITLE
[master] wrong results in LayerView?

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#815]
I just noticed to much support in my LayerView, so enabled support only for "touching buildplate", and finally got this.

![cura_6](https://cloud.githubusercontent.com/assets/1847437/16186525/3f7a6970-36cb-11e6-95bc-e59ace09b844.png)

![cura_7](https://cloud.githubusercontent.com/assets/1847437/16186531/476a1ab8-36cb-11e6-8efd-dbc84c020960.png)

Did I miss something or is that a (known) bug?

**Comment by nallath** [comment]
How does the model look in x-ray mode? It looks a bit like the model is faulty.

**Comment by thopiekar** [comment]
![cura_8](https://cloud.githubusercontent.com/assets/1847437/16187012/1bf713ba-36ce-11e6-9986-227ceed6e7e5.png)

**Comment by thopiekar** [comment]
I prepared my model a bit and added some bevels. Now it looks fine :+1: 
![cura_9](https://cloud.githubusercontent.com/assets/1847437/16187319/e3cbe75c-36cf-11e6-9910-d2a13e4f9e5d.png)
