### ISSUE TITLE
render the z-seam on a 3d model

### ISSUE THREAD

**Issue by nesergen** [Ultimaker/Cura#8153]
Dealing with the Z-seam settings. And I want to see how changes in the settings affect the printed model (seams position). Therefore, I go to the preview mode, but I do not see where the seam is located.

It would be nice to render the seam on a 3d model. And highlight it with color.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/6072.
