### ISSUE TITLE
Cura really slow when switching between filament settings

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#8154]
**Application version**
Cura 4.6.2

**Platform**
Windows 10 on a 1 year old PC with an Intel I7 8700 and Quadro P620

**Printer**
Diabase H-series Hybrid (uses a Duet wifi)

**Reproduction steps**
1. Load my model with 5 different materials
2. Click on a extruder
3. Click on another extruder

**Screenshot(s)**

![image](https://user-images.githubusercontent.com/6079002/89537629-e494b180-d7f9-11ea-8997-e1784778ac4f.png)

**Actual results**
Cura freezes up for 12 seconds. (maxing out one core of the CPU)

**Expected results**
Cura shows the settings of the other extruder immidiately

**Project file**
[calibration_rev6.zip](https://github.com/Ultimaker/Cura/files/5035077/calibration_rev6.zip)

**Log file**
[logs.zip](https://github.com/Ultimaker/Cura/files/5035101/logs.zip)

**Additional information**
Possible duplicate of #7476 (but other issue was not resolved)

**Comment by Ghostkeeper** [comment]
#7476 didn't have reproduction steps that we could really do anything with. You do though! I can reproduce this problem in Cura 4.6.2, where it indeed takes ~5s to switch tabs.

However it doesn't seem to be a problem in Cura 4.7. We've made optimizations there especially w.r.t. the settings list and with having many objects in the scene. Both are applicable in your case. That reduces the time to switch the tabs to 0.3s. Not without a frame drop, but much more acceptable.
