### ISSUE TITLE
Cura 4.7 freezes when going back from a manufacturer in the market place

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#8161]
**Application version**
4.7.0-beta

**Platform**
Windows 10 on a Lenovo P53 with an Intel I7 9850H and a Nvidia Quadro T1000

**Printer**
Diabase H-series hybrid

**Reproduction steps**
1. Click on market place -> materials> one of the premium materials
2. Click on back

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/6079002/89693195-17c86500-d90e-11ea-8dae-78923d20b80d.png)

**Actual results**
Cura freezes for 14 seconds

**Expected results**
Cura does not freeze

**Project file**
[CFFFP_calicat_x60_rev4_with_cleaning.zip](https://github.com/Ultimaker/Cura/files/5044052/CFFFP_calicat_x60_rev4_with_cleaning.zip)

**Log file**
[log.zip](https://github.com/Ultimaker/Cura/files/5044068/log.zip)

**Comment by evtrados** [comment]
This has now been fixed for the 4.7 release candidate. The transition should now be almost instant. Using my laptop it used to take ~5.5 seconds and now it takes ~0.2 seconds. For you @martijnschouten maybe it will take a slight bit longer than that, but it will still be way faster than before.
