### ISSUE TITLE
Image or label for front of print bed

### ISSUE THREAD

**Issue by mzagrabe** [Ultimaker/Cura#8164]
My problem is this: I slice my print with Cura and then I forget the orientation (in the XY plane) of my print when I walk from my computer that has the SD card to my printer to transfer the gcode file. The printer is in the basement and my computer is on a different floor of the house. In the 30 seconds to 3 minutes (via sneakernet) I forget the profile of the print and I don't want to waste adhesive on the print bed if I don't need to by coating the whole bed (or a majority of the bed) with adhesive.

It would be great to have a preference setting for each printer in Cura to specify an image file to show on the front of the print bed - or any configured place on the print bed.

I think an image on the Cura bed would give a good visual reminder and frame of reference for remembering where the print will be printed on the bed.

I think many users would like to label their print bed for configuring Cura to look more like their printer.

Thanks for considering this request.

**Comment by Ghostkeeper** [comment]
We do allow you to give your print a label through the project name. This is the default for the file name, which most printers show on their displays.

There is an option to show an image on one side of the print bed in Cura's 3D view. But which image (or indeed whether or not there is really a "front" side) depends on the printer. For instance here's how it looks with an Ultimaker 3.
![image](https://user-images.githubusercontent.com/2448634/89788710-e1623400-db1f-11ea-90e0-a92d5e1f4b76.png)
Not every printer has a model for their build plate in Cura, so if the model is missing for your printer it would need to be added.

For printers where Cura doesn't know the model, there is still the origin in the 3D view to indicate the coordinate origin, as additional orientation point:
![image](https://user-images.githubusercontent.com/2448634/89788835-09519780-db20-11ea-9a7e-341d9a77eb2d.png)

This coordinate origin is where it would move if the g-code indicates to move to coordinate 0,0. That's usually the front-left corner of the printer, but in reality it can be anywhere. For instance, there are delta printers that have the origin in the centre of the build plate. They don't really have a front side.
