### ISSUE TITLE
Cura all versions. The file name is moderately dark grey on slightly on slightly lighter grey.  

### ISSUE THREAD

**Issue by Peter2055** [Ultimaker/Cura#8169]
This is an idea again. Why is the file name is shown as a moderately dark grey against a background of lighter grey. Its actually difficult to read, even see, where the file name is, to edit it, especially when there is a model sitting in the window again behind, with strong colours.

**Comment by nallath** [comment]
What file name? There are a number of places where the filename is displayed. 

Could you add a screenshot and circle the file name that you mean?
