### ISSUE TITLE
[4.7.0-beta] No extruder temperature in 'Monitor' session.

### ISSUE THREAD

**Issue by protywu** [Ultimaker/Cura#8176]
**Application version**
4.7.0-beta

**Platform**
Win 10, 64 bit.

**Printer**
Several including Ultimaker S5.

**Reproduction steps**
Simply open the software and click on the 'Monitor' tab.
Also tried running Cura after powering on the printer so that the printer was automatically connected to Cura when Cura is up.

**Screenshot(s)**
![Cura47-bug-2020-08-11 111816](https://user-images.githubusercontent.com/69508764/89887283-e7125500-dbc5-11ea-9f5f-561c5d87fdb6.png)

**Actual results**
The 'extruder temperature' session is missing.

**Expected results**
The 'extruder temperature' session should show up as in the versions before 4.7.0-beta.

**Project file**
N/A

**Log file**
N/A

**Additional information**
Have tried to manually put in the MKS Cura plugin into the 'plugins' directory and the results were the same, no 'extruder temperature'.

**Comment by nallath** [comment]
Please contact the developer of the MKS Cura Plugin. We can't control what plugins do / show.

**Comment by protywu** [comment]
> Please contact the developer of the MKS Cura Plugin. We can't control what plugins do / show.

The plugin comes with the Cura official download, so we don't know where the official Cura got the plugin from.

**Comment by nallath** [comment]
The MKS plugin is not bundled with the Ultimaker Cura release. It is available on the market place, where you can also find the contact information of the developer (https://marketplace.ultimaker.com/app/cura/plugins/Jeredian/MKSWifiPlugin).
