### ISSUE TITLE
Highlight unsupported overhangs with Touching Buildplate/Tree supports

### ISSUE THREAD

**Issue by MarkMan0** [Ultimaker/Cura#8180]
**Is your feature request related to a problem? Please describe.**
I prefer using Touching Buildplate supports, for easier removal. This results in certain overhangs not being supported. I'd like to Cura to highlight these overhangs, either in the prepare of preview window. This would allow me to easier reconsider whether to use supports Everywhere, use custom modelled supports in those places or just ignore it.
Right now, I have to manually check the model, which is error-prone and lengthy - especially with Tree Supports.

**Describe the solution you'd like**
I'd like Cura to highlight overhangs, which are not supported, Or highlight supported overhangs in different colour - orange?

**Describe alternatives you've considered**
Manually checking, which is error-prone a takes along time. On large models, Cura also gets laggy, especially on slower PC, which makes it harder to search for these overhangs.

**Affected users and/or printers**
Everyone, but especially advanced users.

**Additional context**
None

**Comment by rburema** [comment]
Hi @MarkMan0 

Your request makes a lot of sense, but unfortunately it's nearly impossible to implement given the way it's set up now. We'd have to  detect (parts of) model faces from already generated toolpaths and match those up with both the model and the toolpaths of already generated support. If the model contains large faces, this will be very error prone.

So we've chosen not to implement this, sorry.
