### ISSUE TITLE
BUG: Different material selection does not change bed temperature - Cura 4.6.2

### ISSUE THREAD

**Issue by reefwarrior** [Ultimaker/Cura#8184]
Hi all,

**Application version**
Cura Slicer 4.6.2

**Platform**
Windows 10

**Printer**
Creality Ender 3

**Reproduction steps**
1. Define material with print temperature of 197, bed temperature 62)
2. Define material with print temperature of 235, bed temperature 82)
3. Select either; and check in print settings. Print temperature changes, but bed temperature does not. 

**Screenshot(s)**
![197_62](https://user-images.githubusercontent.com/6298432/90100644-68402800-dd3d-11ea-8168-6823829e91e3.png)
![235_82](https://user-images.githubusercontent.com/6298432/90100648-6a09eb80-dd3d-11ea-8af8-c1a4e0cdcd0d.png)

**Actual results**
As discussed under 3.

**Expected results**
Bed temperature needs to update.

Rgds
Tinus

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this problem. It updates fine for me:
![image](https://user-images.githubusercontent.com/2448634/90236731-75374700-de23-11ea-95fc-c4becae8d4b7.png)
![image](https://user-images.githubusercontent.com/2448634/90236769-81230900-de23-11ea-89fe-8e20ae240bc1.png)

Can you provide us with a project file? Like the template asked for, before you deleted that?

**Comment by reefwarrior** [comment]
Hello,

Sure, included please find. I have also included the generated .gcode files, if that helps.

Thank you for the help!
Tinus

PS. Included in the .zip file
[CURA Issue.zip](https://github.com/Ultimaker/Cura/files/5073914/CURA.Issue.zip)

**Comment by nallath** [comment]
That's because your custom quality profile overrides the material temperature. I've fixed that for you.

For the next time, you can see that this is going on by looking at the text of the setting. If it's italic, your profile is overriding it. 
[fixedprofile.zip](https://github.com/Ultimaker/Cura/files/5083400/fixedprofile.zip)

**Comment by reefwarrior** [comment]
Thank you! :)
