### ISSUE TITLE
4.7 beta "Connect Support Lines" option only available when "Grid" is selected

### ISSUE THREAD

**Issue by GregValiant** [Ultimaker/Cura#8192]
**4.7 beta**
(The version of the application this issue occurs with.)

**Win 10 Home 64bit**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Creality Ender 3 Pro**
(Which printer was selected in Cura?)

**Reproduction steps**
1. Select - Support/Support Pattern/Lines the "Connect Support Lines" option gets hidden
2. Select Support/Support Pattern/Grid the "Connect Support Lines" option is available

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Select the Grid option and then the Connect Support Lines option becomes available.  Enable Connect Support Lines and then switch the Grid option back to Lines.  The lines do get connected.

**Expected results**
Whether selecting either Grid or Lines, the Connect Support Lines option should be available.
(When selecting ZigZag the Connect Support ZigZags option is correctly displayed.)

**Project file**
Not applicable

**Log file**
Not applicable

**Additional information**
Not Applicable

**Comment by rburema** [comment]
ZigZag support is basically equivalent to what Lines + 'Connect Support Lines' would be. For completions sake we could consider adding 'Lines' to the 'show if' ('enable') field of 'Connect Support Lines'.

**Comment by GregValiant** [comment]
![Grid](https://user-images.githubusercontent.com/64202104/90345498-11fa1000-dfef-11ea-9dab-abdfbe1e63d2.png)
![Lines](https://user-images.githubusercontent.com/64202104/90345499-1292a680-dfef-11ea-85ce-666d3aa8b172.png)
![ZigZag](https://user-images.githubusercontent.com/64202104/90345500-132b3d00-dfef-11ea-848c-0dc70ceb50ec.png)

In the first screenshot the Support Pattern "Grid" is selected.  The "Connect Support Lines" option is visible and selectable.
In the second screenshot the Support Pattern "Lines" is selected.  There is no option to "Connect Support Lines".  I believe it should be visible.  The work-around is to select "Grid", select Connect Support Lines, and then switch back to "Lines".
In the Third screenshot the Support Pattern "ZigZag" is selected.  The "Connect Support ZigZags" option is visible and selectable.

**Comment by Ghostkeeper** [comment]
Yeah, this is an inconsistency, for two reasons:
* Settings that are not visible in the interface should not influence the slice result (aside from explicitly invisible settings such as the machine settings).
* In the infill settings, the Connect Infill Lines setting is visible even when the infill pattern is "Lines". It effectively then turns the infill pattern into zigzag except it doesn't connect the endpoints.

Note that "Connect Support ZigZags" is an entirely separate feature specific to the zigzag pattern. It's got little to do with this bug.

So I guess this is easy enough to fix to solve both inconsistencies at once: Just make the setting visible for the lines pattern in support as well.

**Comment by GregValiant** [comment]
Works for me.  Thank You.
