### ISSUE TITLE
Zoom view locked

### ISSUE THREAD

**Issue by MikatDude** [Ultimaker/Cura#8194]
When in top view and max zoom into model base plate, then play a small print cycle for that layer. Now the zoom locks and one cannot zoom back out.

**Comment by rburema** [comment]
I can't reproduce this. Could you fill out the rest of the template, please? Logs and such might reveal a bit more.

**Comment by MikatDude** [comment]
I have now tried to replicate this issues I had for three days prior to posting the report, and have not been able to replicate it today, so this may have been an issue from the OS, as I believe the .NET 3.5 & 4.8 framework got update last night on my computer in preparation for Windows 10 build 2004.
