### ISSUE TITLE
Can't open 

### ISSUE THREAD

**Issue by razzshaan** [Ultimaker/Cura#8197]
![20200813_162608 1](https://user-images.githubusercontent.com/69708610/90308283-da5e6b80-defb-11ea-9255-7e570fc68938.jpg)

**Comment by rburema** [comment]
https://support.microfocus.com/kb/doc.php?id=7024041

**Comment by Ghostkeeper** [comment]
When installing Cura, did you let it install the Visual C++ Redistributable?
