### ISSUE TITLE
[4.6.2] pause at layer Repetier 

### ISSUE THREAD

**Issue by SBWZFH** [Ultimaker/Cura#8199]
**Application version**
4.6.2
4.6.1
4.6.0
(maybe even older)

**Platform**
WINDOWS 10   1050gtx

**Printer**
Custom

**Reproduction steps**
1. Select pause at layer height for 3 separate layers
2. Confirm GCODE

**Actual results**
All instances of "Pause" is applied only to the earliest layer. Also, Z height returns 1mm above desired height. 

**Expected results**
Pause at layer should happen on the different specified layers. 

**Project file**  See end of layer 8 begin of layer 9
[CFFFP_Snorkle to fender grommettest.zip](https://github.com/Ultimaker/Cura/files/5079621/CFFFP_Snorkle.to.fender.grommettest.zip)

**Comment by rburema** [comment]
I _think_ this might be fixed in 4.7-beta, could you try that?

**Comment by SBWZFH** [comment]
Downloading now.  Thanks!


Stephen Williams
University of Missouri Science and Technology
Undergraduate in Mechanical Engineering
Cell: (816) 645-6715
Email: SBWZFH@umsystem.edu
