### ISSUE TITLE
[4.6.2] Surface mode appears to ignore Mesh Fixes setting

### ISSUE THREAD

**Issue by janherich** [Ultimaker/Cura#8211]
**Cura version 4.6.2**

**Operating system Mac OS**

**Reproduction steps**
Surface mode appears to ignore Mesh Fixes settings, or at least `Maximum Resolution` and always generates print move commands based on exact mesh/plane intersection.
I discovered this when my printer started to stutter/vibrate and print curved sections very slow compared to coarse grained polygons, but that happened only when model was sliced using the surface mode.
I can of course decrease the resolution of the generated model, but that is in many cases quite poor solution, because complex bezier/nurbs curves are usually approximated in non-uniform manner, eq more fine grained in more curved sections, etc.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1910609/90568111-87124480-e1ab-11ea-8679-90b063aa8659.png)
Comparing two G-code files of the exact same model (100mm long 10mm tall airfoil section with 200 points per each upper/lower surface), `wing_stub_normal.gcode` generated with normal mode, compared to `wing_stub.gcode` generated with surface mode, surface mode gcode is almost one order of magnitude bigger - ~3K vs ~27K lines) 

**Actual results**
Mesh fixes doesn't work with surface mode slicing

**Expected results**
Surface mode should respect mesh fixes settings, or at least display warning about ignoring them (the only `Affects` point mentioned is `Union Overlapping Volumes`)

**Comment by rburema** [comment]
This happens because our current implementation of the simplify algorithm we use for (amongst other things) maximum resolution works on closed polygons, rather than open ones (like spirals). Also it should happen in another part of the program (after the  polygons have already converted to extrudable segments), which is another data-structure.

We discussed this, and unfortunately the effort required to fix this outweighs the priority of this issue, so, sadly, we chose to defer this for now.

**Comment by smartavionics** [comment]
Surface mode does not ignore max-res/max-dev as you can see here...

Normal mode with fine and coarse res/dev...

![Screenshot_2020-08-19_11-06-22](https://user-images.githubusercontent.com/585618/90621816-249d6080-e20c-11ea-9a4d-d51067afe082.png)

![Screenshot_2020-08-19_11-05-52](https://user-images.githubusercontent.com/585618/90621818-2535f700-e20c-11ea-91a2-748027cb62d4.png)

Surface mode with fine and coarse res/dev...

![Screenshot_2020-08-19_11-06-41](https://user-images.githubusercontent.com/585618/90621880-3da61180-e20c-11ea-9858-da3b238e8cc9.png)

![Screenshot_2020-08-19_11-05-28](https://user-images.githubusercontent.com/585618/90621885-3ed73e80-e20c-11ea-85d8-f17e3a0aba51.png)

**Comment by smartavionics** [comment]
Maybe you are only altering max-res and not max-dev? Max-dev has far more of an influence than max-res does on the number of segments output.

**Comment by janherich** [comment]
Hmm, this is strange, it just doesn't work for my model -> here is screenshot where I increase the max resolution/deviation to absurd high amounts and as you can see it only affected the skirt shape (which behaves correctly), but not the model:
![image](https://user-images.githubusercontent.com/1910609/90624303-0a697f80-e218-11ea-8840-d259da832f96.png)
This is the actual STL model I used for slicing -> https://gist.github.com/janherich/8add63127438cc6131df1ad786956c2d

**Comment by smartavionics** [comment]
You're right, for that model, max-res/max-dev are ignored. I shall look into that...

**Comment by smartavionics** [comment]
Solved it! the problem is with the model, its normals are wrong. If you correct the normals, you get the expected output...

![Screenshot_2020-08-19_12-55-09](https://user-images.githubusercontent.com/585618/90631827-510ca900-e21b-11ea-91b4-693a1423a254.png)

**Comment by janherich** [comment]
Awesome, thanks @smartavionics ! Yes, the airfoil has one surface pointing in the wrong directions (normals are reverse), I suspected that it wouldn't matter with surface mode, but apparently, it does (@rburema provided explanation why, mesh fixes work on closed polygons representing slices).
Unfortunately it doesn't fix all situations, because sometimes, the polyline is not closed.

**Comment by smartavionics** [comment]
But the mesh tools plugin fixes the normals just fine.

**Comment by smartavionics** [comment]
The polygons do get closed when the normals are correct.

**Comment by janherich** [comment]
Correct, but imagine model like smoothly corrugated surface -> in x/y plane cut, it's just one open polyline.
Surface mode is great because you can easily create such mesh and not worry about generating correct thickness, etc, as it will be always nozzle width. 
Unfortunately max resolution/deviation doesn't work in that case.

**Comment by smartavionics** [comment]
That's true, I'll ponder that.

**Comment by TheRooster13** [comment]
Being able to adjust resolution on non-closed meshes would be a HUGE benefit for me. As it is, the prints take too long to be practical because of small features in the mesh.
