### ISSUE TITLE
[master] Cura does not start due to missing "self" in MachineManager

### ISSUE THREAD

**Issue by TheGlitch76** [Ultimaker/Cura#8215]
**Application**
Tested on 6b8fe48ddd1195dd80850df48360dafbc59116bd of master.

**Platform**
Arch Linux x64

**Printer**
Occurs with default configuration ("Backup and Reset Configuration")

**Reproduction steps**
1. Launch Cura

**Actual results**
Fatal error occurs during "Loading UI stage"

**Log file**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cura/Settings/MachineManager.py", line 628, in extruderPositionsWithNonActiveIntent
    global_container_stack = _application.getGlobalContainerStack()
NameError: name '_application' is not defined
```

**Additional information**
Recommended change:
https://github.com/Ultimaker/Cura/blob/6b8fe48ddd1195dd80850df48360dafbc59116bd/cura/Settings/MachineManager.py#L627-L628
Change `_application.getGlobalContainerStack()` to `self._application.getGlobalContainerStack()` as in the rest of the file

**Comment by fieldOfView** [comment]
Fixed here: https://github.com/Ultimaker/Cura/commit/1097dbdfa5b45c01ce07a81792a4ceb198c1c13b

**Comment by nallath** [comment]
Yeah, i made a stupid copy-paste mistake. Shame on me!
