### ISSUE TITLE
Cura turning wrong fan on

### ISSUE THREAD

**Issue by cbldwn** [Ultimaker/Cura#8219]
I'm running dual extruders on a single nozzel with a shared fan (0) and i have set both extruders to fan 0 but cura is not adding the P0 to designate fan 0, It only puts M106 S255. As a result if the first half of the print is with T1 then when it sends the command M106 S255 it tries to turn on Fan 1 instead of Fan 0. If I set both extruders to Fan 1 then it outputs the P1 as it should. Need to add the P0 designation to Fan 0 to fix problem.

**Comment by cbldwn** [comment]
Yes I am using marlin 2.0.6, thanks defining SINGLENOZZLE_STANDBY_FAN  seems to have done the trick.

**Comment by Ghostkeeper** [comment]
Another workaround would be to use the Search and Replace post-processing script to replace all `M106 S` by `M106 P0 S`.

**Comment by smartavionics** [comment]
BTW, I just noticed that Marlin 2.0.6.1 has a commit that forces the fan number to 0 when SINGLENOZZLE is enabled without needing SINGLENOZZLE_STANDBY_FAN being enabled. That makes more sense.
