### ISSUE TITLE
Change Filament 

### ISSUE THREAD

**Issue by justchenook** [Ultimaker/Cura#8227]
**Application version**
(The version of the application this issue occurs with.)
4.6.2

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
windows
**Printer**
(Which printer was selected in Cura?)
cr10 s4
**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)
nothing I've done every time I slice a project then save it to SD card  as soon as I put the sd card into the printer to print for same reason the Gcode as been saved with a change filament command at the end of every code line.
I've had a look to see what extensions are turned on but there is non turned on.
I'm not sure how to remove this command on the Gcode

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Uh, so let me get this straight, instead of this normal g-code:

```
M204 S625
M205 X6 Y6
G1 F600 Z2.27
G0 F4285.7 X90.977 Y97.25 Z2.27
M204 S500
M205 X5 Y5
;TYPE:SKIRT
G1 F600 Z0.27
G1 F1500 E0
G1 F1200 X91.566 Y96.795 E0.01323
G1 X92.2 Y96.406 E0.02645
```
...you would be seeing something like this?
```
M204 S625M600 E10 L500
M205 X6 Y6M600 E10 L500
G1 F600 Z2.27M600 E10 L500
G0 F4285.7 X90.977 Y97.25 Z2.27M600 E10 L500
M204 S500M600 E10 L500
M205 X5 Y5M600 E10 L500
;TYPE:SKIRTM600 E10 L500
G1 F600 Z0.27M600 E10 L500
G1 F1500 E0M600 E10 L500
G1 F1200 X91.566 Y96.795 E0.01323M600 E10 L500
G1 X92.2 Y96.406 E0.02645M600 E10 L500
```

Could you provide a project file that reproduces this issue for us?
