### ISSUE TITLE
Slicing never finishes. 

### ISSUE THREAD

**Issue by Hix777** [Ultimaker/Cura#8237]
Slicing never finishes. The project isn't even that big, or detailed.

**Comment by Liger0** [comment]
The template, tho.

**Comment by enkiera** [comment]
I am also getting the same issue after upgrading to 4.7. when trying to slice any model the slicing never completes. The loading bar on the bottom right doesn't show any progress. I've tried reinstalling and downgrading back to 4.6 but this is now also doing the same thing.

**Comment by jellespijker** [comment]
please fill in the bug report and send us your log
