### ISSUE TITLE
Import profiles impossible

### ISSUE THREAD

**Issue by loulou-uoluol** [Ultimaker/Cura#8239]
**Application version**
4.7
**Platform**
Mac OS X ( Catalina)

**Printer**
Predator (Cura Printer)
Predator (my Custom printer)

**Reproduction steps**
1. export an profile (my custom printer)   
2. Import the profile (Predator)
3. Unknown file type or is corrupted.
4. Same message with olds profiles

**Screenshot(s)**
<img width="441" alt="Capture d’écran 2020-08-26 à 08 22 01" src="https://user-images.githubusercontent.com/62318662/91268472-b3166280-e775-11ea-88ad-8ce1a7a334fc.png">

**Comment by nallath** [comment]
Please fill in the entire bug template. We're missing log files and the profile files that don't work for you.

I've just tried to reproduce this, but the profile exported and imported  correctly.

**Comment by loulou-uoluol** [comment]
I completely removed Cura, and after restarting my mac.
I reinstalled Cura. It works normally, I can import my profiles.
Thanks for your help.
