### ISSUE TITLE
Cura 4.7.0 resets after creating new profile

### ISSUE THREAD

**Issue by skarasov** [Ultimaker/Cura#8245]
**Application version**
4.7.0

**Platform**
Win 10 2004

**Printer**
Anycubic i3 mega

**Reproduction steps**
1. Start Cura 4.7.0 (fresh install in my case).
2. Welcome screen -> skip cloud -> Add printer Anycubic i3 mega.
3. Goto prefs -> Profiles -> Duplicate "normal" profile, activate it.
4. Close all.
5. Start Cura - again.

**Screenshot(s)**
![welcome](https://user-images.githubusercontent.com/50782570/91315811-cbf83580-e7c0-11ea-88a5-750d8de8831a.png)

**Actual results**
Cura welcomes you again and error msg about profiles.

**Expected results**
Work without reseting.

**Log file**
[cura.zip](https://github.com/Ultimaker/Cura/files/5130413/cura.zip)

**Comment by nallath** [comment]
It specifically breaks for the duplicate. It doesn't happen when you use "create new profile from settings/overides"

**Comment by choppy420** [comment]
I to am having a problem importing the profiles, after I import them the do not show up

**Comment by nallath** [comment]
> I to am having a problem importing the profiles, after I import them the do not show up

Okay, could you create a new issue for this and fill in the bug template?

**Comment by Ghostkeeper** [comment]
We've fixed this issue in an upcoming release, likely early next week.
