### ISSUE TITLE
Missing default profiles in dropdown

### ISSUE THREAD

**Issue by mrloofer** [Ultimaker/Cura#8253]
**Application version**
4.7

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
Select the profile dropdown box.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/315708/91382513-e7cafe00-e7f7-11ea-8f45-2b02892c9a9e.png)

**Actual results**
Only shows custom profiles

**Expected results**
Should show default profiles. The only way to select a default profile is to click the star icon to open profile manager, choose the default profile, click activate.

Cura 4.6.2:
![image](https://user-images.githubusercontent.com/315708/91382734-6162ec00-e7f8-11ea-9d6b-dabc98814d6d.png)

**Comment by nallath** [comment]
4.6.2 was incorrectly showing the default profiles in this case. You can find more information about this here https://github.com/Ultimaker/Cura/issues/8229
