### ISSUE TITLE
unable to slice

### ISSUE THREAD

**Issue by jdilks4** [Ultimaker/Cura#8256]
Upgraded to 4.7 
deleted all old profiles
ultimaker3
unable to slice material incompatible with machine (ABS)
using Ultimaker material with NFC printer recognizes material and preferences changed to match material.

**Comment by nallath** [comment]
Please fill in the entire bug template. This isn't enough information for us to help you.

**Comment by jdilks4** [comment]
The problem was resolved through support at Ultimaker.
The printer settings for the second extruder was set to a default AA and I had PLV loaded which requires BB
