### ISSUE TITLE
Conical support did't work on delta printers

### ISSUE THREAD

**Issue by MrStump** [Ultimaker/Cura#8258]
**Application version**
4.6 and 4.7

**Platform**
windows 10 and MAC

**Printer**
delta printer, any. "Buildplate Elliptic", "Origin at center"

**Reproduction steps**
Create new custom delta printer, enable "Conical Support"

**Screenshot(s)**
below

**Actual results**
No Conical Support

**Additional information**
I have few printers, on CoreXY profile, Ender profile "Conical supports" work well.
On delta printer don't
ALSO when i rise model on any distance above the buildplate and slice it on NON-Delta printer - Cura build support to the model as it should.
when i rise model above the buildplate on Delta printer and slice - Cura show me ghost model on it's position where i rise it, but slice from the table. This happens ONLY when "Conical Supports" enabled. 
This was checked on few different PC's

here is Conical Support **Disabled**:
![CuraSupportBug3](https://user-images.githubusercontent.com/24597450/91507897-ad885c00-e8de-11ea-860d-9747720edc0e.png)

here is Conical Support **Enabled**:
![CuraSupportBug2](https://user-images.githubusercontent.com/24597450/91507852-8d589d00-e8de-11ea-991f-7c8f2ac8e804.png)

just switch to CoreXY printer and slice with "Conical Support", all works great:
![CuraSupportBug4](https://user-images.githubusercontent.com/24597450/91508091-32737580-e8df-11ea-8a12-7a29b9670af3.png)

**Comment by fieldOfView** [comment]
See the setting "Remove Empty First Layers". Apparently it is set for your Delta printer(s), and not for your CoreXY printer(s)

**Comment by MrStump** [comment]
> See the setting "Remove Empty First Layers". Apparently it is set for your Delta printer(s), and not for your CoreXY printer(s)

sorry, my bad. it was **enabled** by default, and it became invisible when support is **enabled**, but it still did't generate **Conical Support**

**Comment by Ghostkeeper** [comment]
It seems to work fine for me. Here is a cylinder with a rod in the middle to keep it upright:
![image](https://user-images.githubusercontent.com/2448634/91829105-4dc4e480-ec41-11ea-8875-bba2edfa2f51.png)

Or just a floating cylinder (with "drop models to build plate" disabled):
![image](https://user-images.githubusercontent.com/2448634/91829297-92508000-ec41-11ea-93ab-311e47ccbac4.png)

Do you have a project file by which we can reproduce the problem? It's requested in the issue template.

**Comment by MrStump** [comment]
here is test STL, disabled and enabled conical support

enbled support, disabled **Conical**
![Supp1](https://user-images.githubusercontent.com/24597450/91914780-8c01e880-ecc1-11ea-9369-a7fcedf9d5db.png)

enabled support, enabled **Conical**
![supp2](https://user-images.githubusercontent.com/24597450/91914812-a3d96c80-ecc1-11ea-8a5a-3bf39a5ce580.png)

and both 3mf files
[conical_test.zip](https://github.com/Ultimaker/Cura/files/5159222/conical_test.zip)

Thanks.

**Comment by Ghostkeeper** [comment]
Indeed, it seems to depend on the Origin at Center setting, not necessarily on the build plate shape.

**Comment by Ghostkeeper** [comment]
Fixed for 4.8.
