### ISSUE TITLE
(Cura 4.7) Profiles not imported when chnaging nozzle size 

### ISSUE THREAD

**Issue by Chuggers9** [Ultimaker/Cura#8260]
Application version**
4.7

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
1. Import printer profiles on the default nozzle (0.4mm)
2. Change the nozzle size to any other setting (i.e 1.0mm)
3. No profiles are stored in CURA
4. Import your own printer profile, a message appears saying import Succesful
5. No profile loaded 

**Screenshot(s)**
Nozzle setting 0.4
![image](https://user-images.githubusercontent.com/70369271/91540092-353b8e00-e912-11ea-89fc-53ba39e34640.png)

Nozzle setting 1.0mm

![image](https://user-images.githubusercontent.com/70369271/91539958-06bdb300-e912-11ea-8b88-bc4fb8eb0530.png)

Import profile on 1.0mm nozzle

![image](https://user-images.githubusercontent.com/70369271/91540328-8a779f80-e912-11ea-9ebf-35d4c01b7480.png)

After Import

![image](https://user-images.githubusercontent.com/70369271/91540384-a1b68d00-e912-11ea-96f1-32ea1cca25df.png)

**Actual results**
No profiles inserted after import.

**Expected results**
Compared to 4.6.2 the profiles never needed to be imported as it was automatically set for each nozzle size.

**Additional information**
Rolled back to 4.6.2 as this was working as intended

**Comment by nallath** [comment]
That was a bug in 4.6.2. The profile you're trying to import is based on the "super" quality, which is one with a 0.12 layer height. The 1.0 nozzle doesn't have a 0.12 base profile, only a "draft" profile (0.32 mm layer height).

User profiles are so-called "quality_changes". You can find a bit more information on what that means on our wiki: https://github.com/Ultimaker/Cura/wiki/Profiles-&-Settings#quality-changes

**Comment by Ghostkeeper** [comment]
Should it maybe say something in that message about that the profile is not currently visible because one of the extruders doesn't support it?
