### ISSUE TITLE
Cura's UM dependencies: version tags don't have a "v" prepended

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#8264]
As far as I heard that is one of your conventions that is missing there.

**Comment by thopiekar** [comment]
Just noticed the same in libCharon and the others. Is there something to the convention I missed? Does it only apply for the Cura repo?

**Comment by thopiekar** [comment]
Looks like there is no "v" prepended anymore. Never mind as I can't find it anywhere across all repos anymore.

**Comment by Ghostkeeper** [comment]
As far as I know we've always done without the `v`. But maybe we've had a couple of releases that had a `v` by mistake.
