### ISSUE TITLE
Assemblies translate off of the build platform when merging models in 4.7.0

### ISSUE THREAD

**Issue by hexxxx** [Ultimaker/Cura#8267]
**Application version**
4.7.0

**Platform**
Windows 10 Enterprise, Xeon W-2265, NVIDIA Quadro RTX 4000

**Printer**
UM S5

**Reproduction steps**
1. Import several STLs that have been previously trimmed into separate files from a larger original
2. Select all models
3. Right click -> merge

**Screenshot(s)**
https://i.imgur.com/0XOELWO.png
https://i.imgur.com/2anum4o.png

**Actual results**
Merged models translate some distance, in both XY and Z axes. 

**Expected results**
Merged model stays on the build platform rather than off the the side and 20mm too low. 

**Log file**
[https://pastebin.com/p6Vjw7g9](url)

**Additional information**
I use the merge function daily for work but I've only seen this behavior in 4.7.0

**Comment by Ghostkeeper** [comment]
The merged group is expected to be moved to the average X/Y position of the centres of each bounding box of the models that got merged. As far a I can see with the models that I tried, it's doing that correctly. I tried merging big models with small models, models that overlapped before merging them, multiple models (>3) and models that start partially out of the build plate, but the result seems to be the same.

Is it possible to share a project file just before you merge? The project file contains the models and their placement on the scene, so we can then try merging it and see how it arrives at the calculations of the new position of the merged group for you. Or if that is not possible, maybe you have a different set of models that you are allowed to share.
