### ISSUE TITLE
Grouped models not sliceable if one of group parts is below Z=0

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8268]
**Application version**
4.7.0

**Platform**
Mac OSX 10.15.6

**Printer**
CR-10S as substitute for CR-10v2

**Reproduction steps**
Load two or more models
Position one model below other modes
Group Models
Lower so that the shortest or lowest model is below Z=0
Attempt to slice

**Screenshot(s)**
Models loaded:
![Loaded](https://user-images.githubusercontent.com/57936294/91618535-78f8bc80-e93f-11ea-8485-fda55e2aedb4.jpg)

Models grouped:
![Grouped](https://user-images.githubusercontent.com/57936294/91618551-83b35180-e93f-11ea-9495-a2a1532c24f6.jpg)

Models sunk below bed:
![Sunk Below Bed](https://user-images.githubusercontent.com/57936294/91618557-8746d880-e93f-11ea-8f17-b4aab16a2dde.jpg)

Models ungrouped in place to show exposed, ungrouped model will still slice
![Ungrouped](https://user-images.githubusercontent.com/57936294/91618560-89109c00-e93f-11ea-9357-d9a012db375c.jpg)

**Actual results**
Entire model becomes unsliceable

**Expected results**
A grouped model should be considered for slicing on the basis of the entire group, not just one part.    Sometimes complex models/projects need to be sunk and resliced to continue a failed print or other reasons, and should not have to be disassembled to do so.

**Comment by BagelOrb** [comment]
I have the same problem even if the model is not below the build plate. Still I have a feeling it is the same underlying issue.

![image](https://user-images.githubusercontent.com/8895761/92309024-286a0a80-efa2-11ea-82ff-4c6df9444fdf.png)

[UMS5_vase_bottom.3mf.renamed.zip](https://github.com/Ultimaker/Cura/files/5178327/UMS5_vase_bottom.3mf.renamed.zip)

I seem to be unable to slice anything that's grouped. Can reproduce in Cura 4.7.0 and in Cura 4.6.2

I don't think being below the build plate should ever be enough ground to mark the model as unslicable.

**Comment by BagelOrb** [comment]
[gietr_2.zip](https://github.com/Ultimaker/Cura/files/5178329/gietr_2.zip)

Had the same problem if I duplicate and group this model.

Reproducibility is weird. Now all of a sudden I am able to slice. Reproduction conditions are not 100% clear.

**Comment by nallath** [comment]
@BagelOrb Could you check the PR?

**Comment by BagelOrb** [comment]
Couldn't reproduce the gietr problem, but I did reproduce the vase problem in both 4.7.0 and in your branch.

**Comment by BagelOrb** [comment]
So your PR doesn't fix the vase issue.

**Comment by nallath** [comment]
Well, that means your feeling is wrong ;) It's not the same underlying issue.

**Comment by BagelOrb** [comment]
Shall I make a new issue then?

**Comment by nallath** [comment]
Please do!

**Comment by BagelOrb** [comment]
Done: https://github.com/Ultimaker/Cura/issues/8336
