### ISSUE TITLE
Layout assistance

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8269]
"Arrange Models" is very simplistic, and does not work well a lot of the time.  LuBan, while not a slicer, has a 2d and 3d "nesting" feature that does a bunch of calculations to get the best layout no matter how many and how complex the shapes (https://www.dropbox.com/sh/fxmo3mklf8oa7ex/AABsRVsgkxleHh8lpH3ThVBWa/Doc/English?dl=0&preview=LuBan2D+Draw_Nest.pdf&subfolder_nav_tracking=1)

Could something such as this more exacting arrangement please be added?

![Nesting](https://user-images.githubusercontent.com/57936294/91619963-726c4400-e943-11ea-9ee0-993473ee36dd.jpg)

![Nesting 2](https://user-images.githubusercontent.com/57936294/91619913-5799cf80-e943-11ea-99eb-3bc38e6080b8.jpg)

**Comment by nallath** [comment]
An improved version of the nesting algorithm is scheduled for 4.8

**Comment by Ghostkeeper** [comment]
Normally we'd keep it open then until it's fixed. However this is a duplicate of https://github.com/Ultimaker/Cura/issues/2781 anyway.
