### ISSUE TITLE
Cubic infill doesnt work with assembled objects

### ISSUE THREAD

**Issue by Eigo-staf** [Ultimaker/Cura#8271]
The differents type of infill doesn't affect the slicing with multiple objects assembled. the square infill is applied every times. (with cura 4.7)

**Comment by nallath** [comment]
Could you please fill in the entire bug template and provide pictures of what you mean. It's not clear to me what the actual issue is.

**Comment by Eigo-staf** [comment]
My bad, everything works..sorry. I didn't see that the infill pattern can
be different for each extruder... sorry ^^'I'll delete my ticket.

Thanks

Le lun. 31 août 2020 à 16:22, Jaime van Kessel <notifications@github.com> a
écrit :
