### ISSUE TITLE
Model preview bug

### ISSUE THREAD

**Issue by SJC28** [Ultimaker/Cura#8274]
Hi there. 
     I have an issue with the new Cura update 4.7
  Everything works fine preparing the model and slicing it, but when I try to Preview the model, it's a blank page. The x-ray works, but Previewing the layer doesn't. 

Everything worked fine until I updated to version 4.7 

I have selected my Ender 3 like always, and use the same settings like everytime I prepare models.

**Comment by nallath** [comment]
Please fill in the entire bug template and provide the log files.
