### ISSUE TITLE
GCODE not saved correctly

### ISSUE THREAD

**Issue by ALSFelix** [Ultimaker/Cura#8275]
**Application version**
Cura 4.7

**Platform**
Linux - Ubuntu/Xubuntu 18.04.5

**Printer**
Geeetech A10T 3 into 1

**Reproduction steps**
Copied the GCODE from Cura 4.6.1 for printer and all extruders start AND END gcode.
Closed and reopened the window to verify the code. This was ok.
Closed Cura and when reopened the code for extruders was not all there. only the first four lines.
Repeated this several times and re-downloaded Cura several times to make sure.
It keeps happening.

Thanks

**Comment by ALSFelix** [comment]
Forgot to add my GCODE:

;EXTRUDER START G-CODE
M117 Purge E1     ; Message
M211 S0           ; Turn off soft stops
G1 X-17 F6000     ; Go to X=-17 at 100 mm/sec
G92 E0            ; Reset extrusion distance on new tool
G1 E150 F90       ; Extrude 150 mm of filament at 1.5 mm/s on new tool
G92 E0            ; Reset extrusion distance on new tool
G1 E-1 F90        ; Retract 1mm
;CLEAN NOZZLE SEQUENCE
G0 Z3 F1000       ; Raize nozzle to 3mm
G0 X10 Y-6 F6000  ; goto brush
G0 X25 Y-10 F6000 ; Move 15mm to the right and 4mm to the front
G0 X25 Y-6        ; Move 4mm backwards
G0 X10 Y-10 F6000 ; Move 15mm to the left and 4mm to the front
G0 X10 Y-6        ; Move 4mm backwards
G0 X25 Y-10 F6000 ; Move 15mm to the right and 4mm to the front
G0 X25 Y-6        ; Move 4mm backwards
G0 X10 Y-10 F6000 ; Move 15mm to the left and 4mm to the front
G0 X10 Y-6        ; Move 4mm backwards
G0 X25 Y-10 F6000 ; Move 15mm to the right and 4mm to the front
G0 X25 Y-6        ; Move 4mm backwards
G0 X10 Y-10 F6000 ; Move 15mm to the left and 4mm to the front
G0 X10 Y-6        ; Move 4mm backwards
G0 X25 Y-10 F6000 ; Move 15mm to the right and 4mm to the front
G0 X25 Y-6        ; Move 4mm backwards
G0 X10 Y-10 F6000 ; Move 15mm to the left and 4mm to the front
G0 X10 Y-6        ; Move 4mm backwards
G0 X25 Y-10 F6000 ; Move 15mm to the right and 4mm to the front
G0 X25 Y-6        ; Move 4mm backwards
G0 X10 Y-10 F6000 ; Move 15mm to the left and 4mm to the front
G0 X10 Y-6        ; Move 4mm backwards
M211 S1           ; Turn on soft stops
M117 Printing     ; Message
G92 E0            ; Set current extruder position to 0mm
G0 F10000         ; Increase feed rate before next travel

Cura is not saving after 4th line...

**Comment by MimirDroid** [comment]
I have this same problem on Windows 10 version.  
Add new printer
paste in custom starting g-code which worked just fine in 4.6
Cura works fine until you close it down.
When you re-open Cura you don't get any error dialog, but the material tab is gone and extruder 1 is not listed under the settings menu.  when you go back into the machine settings of the printer, there is no extruder tab and only the first 4 lines of the starting gcode is in the custom starting gcode box.
Added zip of cura.log and stderr.log
[Cura_logs.zip](https://github.com/Ultimaker/Cura/files/5146155/Cura_logs.zip)

**Comment by mrzottel** [comment]
There is actually an equal sign in this line:

G1 X-17 F6000 ; Go to X=-17 at 100 mm/sec

which will cause this. As this is only a part of a non functional argument, just remove it and it should work.

**Comment by ALSFelix** [comment]
How did I missed that...
Thanks 
I will try it today and report back...

**Comment by ALSFelix** [comment]
I missed the = sign...
Without it it works fine...

Will try to close or delete this...

Thank you

**Comment by mrzottel** [comment]
From the logs of MimirDroid I would say it is the same issue.

@MimirDroid : Please check your startup or end gcode for equal signs and remove them. If you are using octolapse and the octolapse script, which contains a lot of equal signs, please either do not use this script until the next version of cura or have a look here: https://github.com/Ultimaker/Cura/issues/8235 for a workaround.

**Comment by ALSFelix** [comment]
Ok. When MimirDroid replays i will close this...

**Comment by MimirDroid** [comment]
I confirmed this morning that it is the same problem.  I do use octolapse, and after reading that it was likely the equals that was causing the problem, I tried without the octolapse script and Cura started up normally.

**Comment by nallath** [comment]
A patch for this is already undergoing testing!
