### ISSUE TITLE
[4.7.0] Settings accordion open/close icons don't change direction

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#8283]
**Application version**
4.7.0

**Platform**
Windows 10 64-bit

**Printer**
N/a (but it is a Dagoma DiscoEasy200)

**Reproduction steps**
Open / Close custom settings sections

**Screenshot(s)**
4.6.2:
![image](https://user-images.githubusercontent.com/3001893/91749423-5a055f00-ebb9-11ea-8d83-42de3f328a4c.png)

4.7.0:
![image](https://user-images.githubusercontent.com/3001893/91749437-5d98e600-ebb9-11ea-9331-cdd0c4a2f269.png)

**Actual results**
In 4.6.2 the triangular arrows on the section headers change direction as you open and close sections.

In 4.7.0 they do not change.

**Expected results**
4.7.0 should work like 4.6.2.

**Project file**
N/a

**Log file**
N/a

**Comment by Ghostkeeper** [comment]
Huh, indeed. They don't rotate any more when expanding a category. Good find!
