### ISSUE TITLE
[4.7.0] Unable to slice floating/raised model with adaptive layers

### ISSUE THREAD

**Issue by ekul3434** [Ultimaker/Cura#8285]
**Application version**
4.7.0

**Platform**
Windows 10

**Printer**
Creality ender 3

**Reproduction steps**
1. Untick "automatically drop models to the build plate" in general settings
2. Insert any model
3. Raise model off the build plate (floating)
4. Turn on supports (in my case tree type)
5. Slice (works perfectly fine and provides model floating on supports)
6. Turn on "Use Adaptive Layers" in Experimental
7. Reslice (slices but result is nothing with a 0 minute print time)

**Screenshot(s)**
Slice of floating model with tree supports and adaptive layers tuned off.
![Cura_bug1](https://user-images.githubusercontent.com/70542074/91760516-d67a5b00-ec16-11ea-834e-cb71f629d8d6.JPG)

Slice of floating model with tree supports and adaptive layers turned on.
![Cura_bug2](https://user-images.githubusercontent.com/70542074/91760530-db3f0f00-ec16-11ea-982a-52b938b1f352.JPG)

**Actual results**
Slice is able to take place but result is of nothing with 0 minute print time

**Expected results**
Floating/raised model sitting ontop of supports (In this case of type tree) similar to first screenshot but with adaptive layers instead of fixed thickness layers.

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/3183 . Fairly old issue! Adaptive layers stops slicing when it encounters the first empty layer, so if you have a model with floating pieces, or if the model itself floats, it may miss the floating bits.

As a workaround, consider using a raft to get a similar effect.
