### ISSUE TITLE
4.7 garbage at end of print

### ISSUE THREAD

**Issue by rfaass** [Ultimaker/Cura#8289]
**Application version** 4.7
(The version of the application this issue occurs with.)

**Platform** win 10 64 bit
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
custom (Monoprice Delta Pro

**Reproduction steps**
1. sliced in 4.7: printed; garbage at the end
2. sliced and printed in 4.6: printed fine
3: compared gcode, 4.7 included this at the end:
 G1 F2400 E80.39361
G1 F600 X3.762 Y-.922 E80.39737
G1 X3.762 Y-1.275 E80.40618
G1 X3.912 Y-1.275 E80.40947
G1 X3.913 Y-.923 E80.41277
G0 F7200 X3.762 Y-.922
G0 X3.762 Y-.971

**Screenshot(s)** none
(Image showing the problem, perhaps before/after images.) 

![image](https://user-images.githubusercontent.com/45519846/91792812-43680380-ebcb-11ea-8b41-e69668a80c27.png)

**Actual results**
When I deleted the "extra" code, the print was correct and no garbage at the end

**Expected results**

**Project file**

Any file I slice with 4.7

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
From that snippet of g-code all we can really see is that it's printing a line, then making a travel move, which is part of any normal print.

You say that this happens with any file in Cura 4.7 but I'm not seeing the problem here. For instance, my print ends with a few skin lines:

```
G1 F1800 X114.03 Y103.758 E118.42088
M204 S5000
M205 X30 Y30
G0 F15000 X113.535 Y103.758
M204 S500
M205 X5 Y5
G1 F1800 X112.756 Y104.537 E118.42693
M204 S5000
M205 X30 Y30
G0 F15000 X112.756 Y104.042
M204 S500
M205 X5 Y5
G1 F1800 X113.04 Y103.758 E118.42913
```

Could you still provide a project file? We can then take a look for ourselves.
