### ISSUE TITLE
[4.7.0] Full Object name doesn't appear if you place your cursor on the Name in the List 

### ISSUE THREAD

**Issue by Mehl0** [Ultimaker/Cura#8290]
**Application version**
Cura 4.7.0

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
UM S5

**Reproduction steps**
1. Placing Cursor on object name

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/70564256/91809207-06345d80-ec2d-11ea-82bf-bb4c349b60c6.png)
 

**Actual results**
Nothing happened

**Expected results**
In further Versions the full name of the object appeared

**Comment by nallath** [comment]
Fixed it for the 4.8 release!
