### ISSUE TITLE
Adjustment settings

### ISSUE THREAD

**Issue by gmarkowitz82** [Ultimaker/Cura#8291]
**Application version**
4.7

**Platform**
Windows 10
**Printer**
Ender 3

**Reproduction steps**
1. When fine tuning my printer, i use "Teaching Tech 3d"s tutorial. I notice when i open multiple iterations of Cura, my adjusted settings from the previous step, do not keep.
2. When changing: Settings>Configure Settings Visibility>Materials> Print Settings> [make adjustments]
ps, im just noticing "Preferences" on the top bar, i feel like it should be under settings
3. "Close"
4. Repeat x times until satisfied to move on
5. New instance of Cura by opening a Generated G-code from the tutorial
**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
When I open up the Print settings from the new instance of Cura, the newest values are not reflected in print settings

**Expected results**
Id expect that the settings would be kept from the most recent update. Would it hurt to give me a "save" button that can confirm a locked in setting. When I use my scroll wheel on a mouse, i can accidentally adjust so many settings and not realize.,

**Project file**
N/A

**Log file**
I don't happen to have a specific instance to download a log for

**Additional information**
Please note that step 4 could also have been an issue of not "closing" out of settings during a currently open instance of Cura

**Comment by nallath** [comment]
That is correct! Cura stores settings to file, so when multiple instances of Cura are open, it's impossible to correctly figure out how to merge the settings from these instances (since they might conflict with one other). As such, it simply stores the settings of the last version of Cura that was closed down.
