### ISSUE TITLE
Right clicking model doesnt bring up full intended menu

### ISSUE THREAD

**Issue by mastory** [Ultimaker/Cura#83]
First 3 items in object right click menu don't display as described here:

https://ultimaker.com/en/support/view/16518-mouse-control

Win7, Logitech g700

**Comment by BagelOrb** [comment]
The website should probably be updated.

**Comment by mastory** [comment]
This may be related to #84

**Comment by awhiemstra** [comment]
The same code is used to check what is underneath the cursor, so if it fails for selection it will also fail for this, so that sounds likely.

**Comment by awhiemstra** [comment]
Closing this as a duplicate of #84
