### ISSUE TITLE
[4.6] Since Cura ~4.4 slicing not possible anymore (also 4.7)

### ISSUE THREAD

**Issue by maxpd1** [Ultimaker/Cura#8300]
**Application version**
Mainly 4.6. But also 4.7 on one PC

**Platform**
Notebook and Desktop Windows 10.

**Printer**
Anycubic i3 Mega

**Reproduction steps**
1. I start cura
2. I import a model
3. I press Slice

**Screenshot(s)**
Here is where it stops:
![image](https://user-images.githubusercontent.com/15956503/91934183-f8dda880-ecea-11ea-89b6-3e3020ca03e6.png)

**Actual results**
Cura doesn't slice

**Expected results**
Cura should start slicing

**Project file**
Every project file I tried during the last half year.

**Log file**
Complete Log of 4.6 attached

**Additional information**
With Cura 4.7. on my Notebook slicing is possible if I turn of the firewall. Even if all Cura interfaces are allowed to communicate through firewall. 
With Cura 4.6 it isn't even working with deactivated firewall on both PCs.
I think it is since 4.4 as I can still use 4.3 without problems.
I also deinstalled all versions and reinstalled them one by one new.

[cura.log](https://github.com/Ultimaker/Cura/files/5160221/cura.log)

**Comment by nallath** [comment]
As far as I can see from the logs, the slicing happened as expected.

**Comment by maxpd1** [comment]
Puhhh, that's even more strange :D

**Comment by Ghostkeeper** [comment]
Indeed in the log it says that it took 14.8s to slice. You then saved the g-code to `D:/AI3M_Lampenfuss6.gcode`. Is that file empty or something? What happened with that file?
