### ISSUE TITLE
[4.5.0] Scaling issue

### ISSUE THREAD

**Issue by Stoorn** [Ultimaker/Cura#8304]
**Application version**
4.5.0

**Platform**
Win 10, MSI z97 gaming 7, i7 4790, Nvidia 980 GTX

**Printer**
CR20pro

**Reproduction steps**
1. loaded a model (that had been rotated 60 degrees prior to saving project) so it loads already rotated.
2. Wanted to print in 99% scale. Thus entered 99 in x percentage box. Hit enter. Now both x and y percentage boxes changes value: x becomes 99.75 (not 99 as entered), y becomes 99.25. It was expected x become 99 and y still 100, whereafter I would enter 99 in the y box.

**Screenshot(s)**
no need

**Actual results**
Described above.

**Expected results**
Described above

**Project file**
I assume no need for that

**Log file**
no need?

**Additional information**
This issue has been reported in several posts but still seems not to have been solved. Before it can be solved (because I dont think it is as easy as a mixup of the mm and % scaling boxes) it must be decided if the scaling is:

Global
Acting on the printer coordinate system x,y,z, or 

Local
Acting on the model coordinate system

and if the scaling is a per model setting or lumped setting.

The issue was reported for other versions of Cura:
https://github.com/Ultimaker/Cura/issues/8100
https://github.com/Ultimaker/Cura/issues/4136
https://github.com/Ultimaker/Cura/issues/5221
https://github.com/Ultimaker/Cura/issues/5189

**Comment by Ghostkeeper** [comment]
Duplicate of #4136 . It doesn't need to get re-reported for every release.
