### ISSUE TITLE
Extruder cooling fan number changed after update to 4.7.0

### ISSUE THREAD

**Issue by qlf** [Ultimaker/Cura#8308]
**Application version**
4.7.0

**Platform**
win7 64

**Printer**
CR10
**Reproduction steps**
1. update to new verison from 4.6 to 4.7.0
2. Settings->Printer->Manage printers->Machine settings->Extruder1 tab->Cooling fan number->changed from 1 to default 0

**Actual results**
After changed to default number "0" Cooling fan started working

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this issue. The cooling fan number still defaults to 0 as far as I can see. Do you have a project file for us where this problem is occurring?
