### ISSUE TITLE
Scaling model dimensions in(%) do not travel from one axis to another after rotating

### ISSUE THREAD

**Issue by qlf** [Ultimaker/Cura#8309]
**Application version**
4.7.0

**Platform**
win 7 64

**Printer**
CR10
**Reproduction steps**
1. Scale down object from 10mm(100%) to 7mm (70%) in a "Y" axis. Flip the object so the dimensions travel from "Y" axis to "Z". And now the new dimensions is for "Z" is 7mm but (100%) and the (70%) left in the field of "Y" axis. The percentage don`t travel with "mm" while flipping objects
The "%" in the box of "Y" axis working for "Z" axis.

**Comment by rburema** [comment]
This has been a longstanding issue, and as such, one of the duplicates of #4136 
Our policy is to close duplicates and to continue discussion in the original ticket.
