### ISSUE TITLE
triangle infill not right

### ISSUE THREAD

**Issue by gompa** [Ultimaker/Cura#8311]
**Application version**
4.7.0

**Platform**
ubuntu 20.04
**Printer**
u20

**Reproduction steps**
import a triangle
slice triangle with 25% infill

**Screenshot(s)**
![infillsquare](https://user-images.githubusercontent.com/6430515/92131809-b27d6c00-ee06-11ea-90fb-74dfb9d7319b.png)

**Actual results**
strange infill in the triangle

**Expected results**
infill in the triangle

**Project file**

[AU20_Fabulous Fyyran.3mf.zip](https://github.com/Ultimaker/Cura/files/5169446/AU20_Fabulous.Fyyran.3mf.zip)
remove zip extention

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
Turn 'infill support' off. The way you do it now, you only get infill where the top of the model needs to be supported, which happens to be a thin strip in the middle of the model.
