### ISSUE TITLE
[4.7]bugged 0g slices ender 3 pro

### ISSUE THREAD

**Issue by Dishyboar** [Ultimaker/Cura#8313]
**Application version**
4.7

**Platform**
win 10 
ryzen 3600
rx 570
**Printer**
ender 3 pro

**Reproduction steps**
when i slice the preview menu is showing some weirdness and says 0g for the print amount. ive tried default profiles and
Note ive already printed this once i dont know whats going on.
**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/70726961/92178963-b95dac00-ee11-11ea-8b47-6be41ebd0a0d.png)

**Project file**

[CE3PRO_Fighter01_Horns.zip](https://github.com/Ultimaker/Cura/files/5171662/CE3PRO_Fighter01_Horns.zip)

**Comment by rburema** [comment]
That model isn't manifold ('watertight') and therefore may have those problems with slicing. In fact, it's broken enough that even the meshfix plugin couldn't fix it completely.

You may be able to see it in preview (the non-yellow parts that show are where the models is 'broken').

I've tried it with the newest version (4.7.0) as well as an older version (4.0.0) and I get basically the same result. Are you sure this was the version of that model that you printed before?

**Comment by nallath** [comment]
There are actually _so many_ overlapping and self-intersecting faces, that the highlighting algorithm is having trouble displaying them correctly. 

I've loaded your model into meshlab and selected the self intersecting faces. There are ~71.000 incorrect faces in this model (which is almost 50% of the model). 
![SelfIntersectingAreas](https://user-images.githubusercontent.com/3922611/92248076-6b57af80-eec8-11ea-9379-d7d1d4407463.png)

By enabling "Remove all holes" in the Mesh fixes category I could get it to print with some semblance of the actual model, but i fear that this model is just too broken for any real attempt to print it.

**Comment by Dishyboar** [comment]
i must have gotten lucky when i got it to print the first time, because repairing this model took me a long time. i have the g code cura 4.7 
[d9.zip](https://github.com/Ultimaker/Cura/files/5175697/d9.zip)
managed to produce if your interested.
(note that the print quality of this gcode wasnt great as you could imagine)
