### ISSUE TITLE
Drop down arrows don't animate in print settings. Cura 4.7

### ISSUE THREAD

**Issue by GamerGuy95953** [Ultimaker/Cura#8319]
**Application version**
4.7

**Platform**
Windows 10, AMD RX 570 XXX Edition

**Printer**
JG Maker Magic

**Reproduction steps**
Click the drop down arrow in the print settings.
you will see that the drop down arrow is not animated.

**Screenshot(s)**
**Example:** https://gyazo.com/7b5b87dddfe8c26b3896266bd1709a9e
**Version:** ![image](https://user-images.githubusercontent.com/61068086/92241090-a7b8ea80-ee8b-11ea-98bb-5935c7fac7a3.png)

**Actual results**
The drop down arrow does not animate.

**Expected results**
The drop down arrow should animate like in the previous versions of cura.

**Additional information**
Started happening on the latest 4.7 update as of this post.
This can be annoying because you wont know if there are settings available for that section if the arrows don't animate.

**Comment by nallath** [comment]
Duplicate https://github.com/Ultimaker/Cura/issues/8283
