### ISSUE TITLE
Post Processing Script "Pause at height" does not work with relative extrusion

### ISSUE THREAD

**Issue by mickeprag** [Ultimaker/Cura#8320]
If "Relative Extrusion" is set under "Special mode" then this value is not respected by the Pause at height script.

This line will reset the script to absolut extrusion and the rest of the script will be broken.
https://github.com/Ultimaker/Cura/blob/8c0e21f0d58549b645cbd5e5823acdfee0c44781/plugins/PostProcessingPlugin/scripts/PauseAtHeight.py#L509

A proper solution is if the script checks if the extrusion is absolute or relative and only switches back to absolute when needed.

**Comment by Ghostkeeper** [comment]
Yup, this would cause a huge retract after the pause, and cause the rest of the print to not extrude anything any more.
