### ISSUE TITLE
Text errors in the marketplace

### ISSUE THREAD

**Issue by gailulun** [Ultimaker/Cura#8322]
![批注 2020-09-05 022549 - 副本](https://user-images.githubusercontent.com/50689883/92274303-8dc8e780-ef1f-11ea-8ae1-c501de8846c3.png)
windows10
After the plug-in is installed in the marketplace, we need to exit Cura and restart it to make the plug-in take effect. When the plug-in is installed, this window will be displayed. The text on the button in the lower right corner of the window is wrong. The red box should have displayed "Ultimaker Cura". Now it shows "%1", which appears in version 4.6-4.7 in Chinese.When I changed the language back to English, the text displayed normally.
![批注 2020-09-05 023644](https://user-images.githubusercontent.com/50689883/92274996-d6cd6b80-ef20-11ea-94d0-d1334f61265f.png)

**Comment by gailulun** [comment]
It seems that only simplified Chinese(简体中文) has this bug. If you change to traditional Chinese(正體字), it will be OK.
![image](https://user-images.githubusercontent.com/50689883/92309456-3b97cd00-efd8-11ea-9a29-26bcf77fdd68.png)

**Comment by gailulun** [comment]
Similarly, the button that prompts you to restart Cura after you uninstall the plug-in is also wrong.
![image](https://user-images.githubusercontent.com/50689883/92310183-69801000-efde-11ea-8abf-177b1f69bd90.png)

**Comment by rburema** [comment]
I can see what happened here; `%1` is used as a placeholder in our strings (application name in this case). The translators are not supposed to change these, but it appears there's a separate unicode `%` character for this language that is different from the basic ASCII `%` character, that got inserted there instead.

I'll fix it for the next minor version (not the patch, sadly), and hope that this won't be repeated.

**Comment by gailulun** [comment]
Thanks a lot :)

**Comment by Ghostkeeper** [comment]
Thanks for the report! Slipped through, somehow.
