### ISSUE TITLE
Left bar feature name when hovering

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8324]
**Is your feature request related to a problem? Please describe.**
On the bar on the left where there are the objects management options there is no word about how they are called, so new people can have an hard time with some options like for example the support blocker.

**Describe the solution you'd like**
A popup saying the feature name.

**Affected users and/or printers**
Any

**Comment by Ghostkeeper** [comment]
This is considered a bug. Because we used to have tooltips there, and they are still in the code too, but the tooltips stopped working. This is from 4.0 while hovering the mirror tool:
![image](https://user-images.githubusercontent.com/2448634/92397315-e7e7c980-f126-11ea-9eb8-14a2fdd8a741.png)

**Comment by Liger0** [comment]
They work in 4.6.2 indeed, they got broken in 4.7

**Comment by tinker3433** [comment]
Yes, This is very frustrating for me as a new user trying to first learn the software.

**Comment by fieldOfView** [comment]
This was fixed in https://github.com/Ultimaker/Cura/pull/8731, which will be part of Cura 4.9
