### ISSUE TITLE
When using "One at a Time", "Arrange all models" doesn't maximise space usage

### ISSUE THREAD

**Issue by Mearman** [Ultimaker/Cura#8329]
Arranging when using "one at a time" print sequence leaves unnecessary space between models and does not place models near enough to the edge of the build plate

**Comment by Ghostkeeper** [comment]
Indeed, the collision areas are wrong in one-at-a-time mode. The effect of that is also visible when enabling the "Ensure models are kept apart" preference.
We had already discovered this internally and have a bug about it in our backlog (devs: see CURA-6833).

**Comment by daton89** [comment]
In my case it puts only one model in the center and all the others outside of the bed. 
But it works ok when I use `All at once` as _Print Sequence_

**Comment by Taomyn** [comment]
Any ETA on when this will be fixed?

**Comment by Ghostkeeper** [comment]
Hard to say. We haven't planned it in for a specific release. It's about halfway down our priority list.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
