### ISSUE TITLE
How to get rid of the lines around model ?

### ISSUE THREAD

**Issue by snuchitp** [Ultimaker/Cura#833]
![screen shot 2016-06-30 at 10 16 16 pm](https://cloud.githubusercontent.com/assets/12837769/16510015/8c36c590-3f10-11e6-91af-d69b5ce5d936.png)

I want to get rid of the three dark green lines around the model. What should I do?

Thanks

**Comment by markwal** [comment]
@snuchitp I believe that is the skirt.  For version 15.04, you choose Platform Adhesion: None instead of Skirt.

**Comment by fieldOfView** [comment]
For issues with Cura 15.04, please see https://github.com/daid/cura

**Comment by snuchitp** [comment]
![screen shot 2016-07-01 at 7 37 32 am](https://cloud.githubusercontent.com/assets/12837769/16520551/ba6b9a0a-3f5e-11e6-89cf-57de2b8a9087.png)

It is none for platform adhersion

**Comment by snuchitp** [comment]
I click ... bottom at the end of platform adherson type. It pop up a new window as shown in a picture below that skirt line count =1

![screen shot 2016-07-01 at 7 40 16 am](https://cloud.githubusercontent.com/assets/12837769/16520609/30df4fa6-3f5f-11e6-93b3-00ba5e95765c.png)


after I tried to change the value of skirt line count to zero. Those three lines are gone as shown in a picture below

![screen shot 2016-07-01 at 7 43 36 am](https://cloud.githubusercontent.com/assets/12837769/16520659/8e3b887c-3f5f-11e6-9639-0030247c4828.png)


Thanks
