### ISSUE TITLE
4.7.1 Crashes on Loading STL

### ISSUE THREAD

**Issue by edm00se** [Ultimaker/Cura#8338]
**Application version**
4.7.1

**Platform**
macOS Catalina 10.15.6

**Printer**
Creality CR-10

**Reproduction steps**
1. Upgraded from 4.7.0 to 4.7.1 (which I thought would fix the bug)
2. Dragged STL file into Cura (previously working in 4.6.2, not in 4.7.0)
3. Crash

**Screenshot(s)**
<img width="1680" alt="Untitled" src="https://user-images.githubusercontent.com/622118/92406133-dab5e500-f0fc-11ea-85e6-c5c72539ada5.png">

**Actual results**
Cura crashes 😢 

**Expected results**
Cura should display my newly imported STL file (this is one I've sliced with Cura previously).

**Project file**
I can't get that far sadly.

**Log file**
Here's [my `cura.log` saved in a gist](https://gist.github.com/edm00se/bfd2bd619f8b5c975fc7c0725381a6d9).

**Additional information**
Based on #8328 and #8230, I thought for sure I was in the clear; sadly this doesn't seem to be the case.

**Comment by nallath** [comment]
Could you copy your configuration folder? It could be that 4.7.0 messed up something so that it still doesn't work.

**Comment by edm00se** [comment]
I've got it zipped up, assuming you mean the dir from `~/Library/Application Support/cura`. I omitted the older 4.1, 4.3, and 4.5 sub directories.

https://www.dropbox.com/s/ahrqpzbufmszyko/cura.zip?dl=0

**Comment by nallath** [comment]
Yeah, it's as I feared. 4.7.0 stored your start g-code incorrectly. 

You need to change the Creality+CR-10+%232_settings.inst.cfg file to:
```

[general]
version = 4
name = Creality CR-10 #2_settings
definition = creality_cr10

[metadata]
type = definition_changes
setting_version = 15

[values]
extruders_enabled_count = 0
layer_height = 0
machine_end_gcode = G91 ;Relative positioning
	G1 E-30.0 F2700 ;Retract a bit
	G1 E-2 Z0.2 F2400 ;Retract and raise Z
	G1 X5 Y5 F3000 ;Wipe out
	G1 Z10 ;Raise Z more
	G90 ;Absolute positionning
	
	G1 X0 Y{machine_depth} ;Present print
	M106 S0 ;Turn-off fan
	M104 S0 ;Turn-off hotend
	M140 S0 ;Turn-off bed
	
	M84 X Y E ;Disable all steppers but Z
machine_extruder_count = 0
machine_start_gcode = ; Script based on an original created by tjjfvi (https://github.com/tjjfvi)
	; An up-to-date version of the tjjfvi's original script can be found
	; here:  https://csi.t6.fyi/
	; Note - This script will only work in Cura V4.2 and above!
	; --- Global Settings
	;
	; magic_mesh_surface_mode = {magic_mesh_surface_mode}
	;
	; retraction_amount = 0
	; retraction_enable = {retraction_enable}
	;
	; retraction_hop = 0
	; retraction_hop_enabled = {retraction_hop_enabled}
	;
	; retraction_prime_speed = 0
	; retraction_retract_speed = 0
	; retraction_speed = 0
	; smooth_spiralized_contours = {smooth_spiralized_contours}
	;
	; speed_travel = 0
	; speed_z_hop = 0

```

**Comment by edm00se** [comment]
Oof yeah. I’m guessing that happened when I first tried with 4.7.0? Either way I can give this a try later tonight and report back.

**Comment by nallath** [comment]
> Oof yeah. I’m guessing that happened when I first tried with 4.7.0? Either way I can give this a go later tonight and report back.

Yeah. Unfortunately, this isn't something we can detect / recover automatically. The shitty thing is, we can see that >500 people have had this issue, so I hope we don't have to manually fix all of those...

**Comment by edm00se** [comment]
To update, I tried copying and pasting the above contents for `Creality+CR-10+%232_settings.inst.cfg` and it didn't do the trick for me. I saved [a screen shot and a copy of my `cura.log` (gist)](https://gist.github.com/edm00se/802529f4d925912b09e3c9874e44e36f) from that crash if it would be helpful.

I did wind up trying the alternate approach you mentioned, which was to delete the 4.7 directory (I renamed it to something else that shouldn't be used) and was happy to find that it worked as expected when importing an STL file.

So, to compare both the correctly working copy of things and the mangled copy, as well as the proposed above copy, I've got that here as screen shots from FileMerge.

Mangled vs the good copy of things (created without 4.7 folder with 4.7.1, does the migration from my prior 4.6.2 settings and works):
<img width="1680" alt="Untitled 3" src="https://user-images.githubusercontent.com/622118/92490757-05fd0a80-f1b7-11ea-905f-587dca6c280b.png">

The proposed above vs the same good copy of things:
<img width="1680" alt="Untitled 2" src="https://user-images.githubusercontent.com/622118/92490789-0d241880-f1b7-11ea-957d-f5757f19fb67.png">

It looks like not just the comments from the octolapse dump of settings mostly comes across, but still missed my actual start gcode in addition to a `machine_extruder_count=0` being added.

I'm able to use Cura again at 4.7.1, so thank you. Also if there's something else you can gain from my setup, settings, or logs, please let me know. Also it seems I can give any remedial actions you'd like to try a go, as I have a saved copy of a mangled 4.7 environment.

**Comment by nallath** [comment]
Ah, right, it also mangled the order. I didn't notice that when manually patching the start-gcode. 

Thanks for looking into it (and for the detailed write up). If more people would write bug reports like this, our life would be so much easier!

**Comment by Ghostkeeper** [comment]
I've also seen [reports where 4.7.1 did fix it for people that were previously experiencing the bug](https://www.reddit.com/r/Cura/comments/ij1r7b/cura_47_cant_import_any_models/). I think that it automatically gets fixed as long as the user doesn't modify their machine settings in 4.7.0. Because if these settings are not modified, the file doesn't get re-saved and never actually gets corrupt (only interpreted wrong in 4.7.0).
