### ISSUE TITLE
why it print the layer at the wrong place

### ISSUE THREAD

**Issue by snuchitp** [Ultimaker/Cura#834]
I used cura v 15.04.6 to display my model. From layer 1-9, it looked correct that built each layer up on top. But from layer 10- the end  started to build from the bottom of the model. The detailed lines are different too.

layer 0-9
![screen shot 2016-07-01 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/12837769/16528681/57645856-3f8c-11e6-9dc0-2d558b7e7f1e.png)

layer 10 -14
![screen shot 2016-07-01 at 12 59 06 pm](https://cloud.githubusercontent.com/assets/12837769/16528683/5bf05032-3f8c-11e6-9692-c90ec3e63927.png)

Thanks

**Comment by thopiekar** [comment]
This is an "old" version of Cura.

Please reopen at: https://github.com/daid/Cura

**Comment by snuchitp** [comment]
I need to use this version because of my  3D printer

**Comment by fieldOfView** [comment]
Feel free to use that version, but that version is not supported here. It still gets some support over at https://github.com/daid/Cura

**Comment by thopiekar** [comment]
@snuchitp If your printer does not work at the moment with Cura 2.1, you can try to convert your printers definitions from "old" Cura to our new version. I'm sure someone can help getting it done if you open a new issue on that :wink:

**Comment by snuchitp** [comment]
Could you please give me any suggestion how to convert my printers definitions from "old" Cura to your new version?

I am very very new user.
I have started to learn cura two days ago.

Thank you so much

**Comment by thopiekar** [comment]
Welcome to Cura :smile: 

Which printer do you have?

**Comment by Ghostkeeper** [comment]
Regardless of Cura 2, I suspect that what happens is that the new layers actually do get built on top of the old ones, but since the camera moves along with the highest layer, it looks like there are new layers on the bottom when you scroll up.
