### ISSUE TITLE
Abnormal perimeter slicing in Cura 4.7 and 4.7.1

### ISSUE THREAD

**Issue by Whiskaya** [Ultimaker/Cura#8343]
**Application version**
4.7 and 4.7.1

**Platform**
macOS Catalina

**Printer**
Creality Ender 5

**Reproduction steps**
1. Slice a Benchy in Cura 4.7 and print it.

**Screenshot(s)**
Slicing
<img width="2560" alt="Slicing" src="https://user-images.githubusercontent.com/64118649/92426670-edfa9c00-f160-11ea-9f7c-4b9ff5d13783.png">

Reviewing GCODE (notice the blobs on the bow)
<img width="2560" alt="GCode" src="https://user-images.githubusercontent.com/64118649/92426694-fb178b00-f160-11ea-9a09-186626d15326.png">

**Actual results**
The perimeters get these strange dots coming out.

**Expected results**
Get smooth perimeters.

**Project file**
[GCODE.zip](https://github.com/Ultimaker/Cura/files/5185752/GCODE.zip)

**Log file**
(Irrelevant)

**Additional information**
1. It's not the STL: MatterControl, PrusaSlicer and Cura 4.6.2 work fine (even using the same profile).
2. Doesn't happen with every STL (I just noticed in this one because the Benchy was particularly awful)
3. Tried the stock profile for Ender 5, same result.
![IMG_9859](https://user-images.githubusercontent.com/64118649/92427330-93fad600-f162-11ea-9acb-b105341521fb.jpg)
![IMG_9858](https://user-images.githubusercontent.com/64118649/92427340-9826f380-f162-11ea-9623-97085f86810a.jpg)

**Comment by jellespijker** [comment]
Probably duplicate copy of #8321

**Comment by Whiskaya** [comment]
> Probably duplicate of #8321 

Indeed.
Sorry, seems like I didn't look for it long enough.
