### ISSUE TITLE
4.7.0: M190 in gcode mispulled from M109 - 

### ISSUE THREAD

**Issue by highcast** [Ultimaker/Cura#8344]
After upgrading from older version to 4.7.0, I had to reconfigure device and filament settings. 

I found a way to utilize smarter startup for the machine: 

**M140 S{material_bed_temperature} ;Start heating bed
M104 S{material_print_temperature} ;Start heating extruder
G28 ;home
G90 ;absolute positioning
G1 X-10 Y-10 F3000
G1 Z0 F1800
M109 S{material_print_temperature} ;Wait for extruder to reach temp before proceeding
M190 S{material_print_temperature} ;Wait for bed to reach temp before proceeding
G92 E0
G1 E20 F200
G92 E0**

The material temperatures are set in correct place, as well it's printing and bed temperatures. 

However, in GCODE, when viewing from the start of a print, this is produced:

**Generated with Cura_SteamEngine 4.7.0
M82 ;absolute extrusion mode
M140 S60.0 ;Start heating bed
M104 S197.0 ;Start heating extruder
G28 ;home
G90 ;absolute positioning
G1 X-10 Y-10 F3000
G1 Z0 F1800
M109 S197.0 ;Wait for extruder to reach temp before proceeding
M190 S197.0 ;Wait for bed to reach temp before proceeding**

This M190 causes device to try to heat the bed over it's limits. This value actually should stand for 60. It seems to pull the value from the wrong place.

**Comment by nallath** [comment]
>M190 S{material_print_temperature} ;Wait for bed to reach temp before proceeding
>
>M190 S197.0 ;Wait for bed to reach temp before proceeding**
> 
> This M190 causes device to try to heat the bed over it's limits. This value actually should stand for 60. It seems to pull the value from the wrong place.

It's doing exactly what you asked it to do. I think you meant to have it be:

`M190 S{material_bed_temperature} ;Wait for bed to reach temp before proceeding`
