### ISSUE TITLE
[4.7] Incorrect g-code generated?

### ISSUE THREAD

**Issue by jtrmal** [Ultimaker/Cura#8352]
**Application version**
Cura  4.7

**Platform**
 MacosX

**Printer**
Ender 5 Pro

**Reproduction steps**
The g-code generated does not produce expected results -- I'm not sure if it's problem with the slicer or the printer, but with I got a fine print with a slightly different number of bottom layers

**Screenshot(s)**
![IMG_8546 copy](https://user-images.githubusercontent.com/11054175/92584547-c4756980-f261-11ea-8db5-14a534ebbf2e.jpg)

**Actual results**
Seems like part of the segment was not printed correctly

**Expected results**
... would be printed correctly

**Project file**
See the project and the g-code  in the following zip file
[Archive.zip](https://github.com/Ultimaker/Cura/files/5194333/Archive.zip)

**Comment by jtrmal** [comment]
Never mind, probably not a problem in Cura -- could not reproduce for this g-code (could reproduce for a g-code where it didn't happen yesterday). IE issue somewhere else...

**Comment by Ghostkeeper** [comment]
If we get a problem like this, we also need to know what's wrong about the g-code. We can't reproduce what's wrong with the print because that is dependent on the printer and environment.

**Comment by jtrmal** [comment]
Yeah, I thought the  g-code contains some operation "move diagonally"
instead of "up" and "left", which I'd assumed would be obvious.
Anyway, not an issue with cura, sorry for bothering...
y.
