### ISSUE TITLE
Alternate print direction to reduce missing line with fast speed

### ISSUE THREAD

**Issue by Entretoize** [Ultimaker/Cura#8354]
When printing at (too) fast speed each print segment miss flow at the beginning creating walls at the same position for each layer. It is worst with support.

By alternating clockwise/counter-clockwise direction the issue should be limited.

https://ibb.co/RzY3z6t

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/6672.
