### ISSUE TITLE
[4.7.1] Tree support interface not connecting to model

### ISSUE THREAD

**Issue by ZEBaker98** [Ultimaker/Cura#8357]
**Application version**
This issue started happening after I upgraded from 4.6.2 to 4.7.0 and continued with 4.7.1

**Platform**
MacOS Catalina 10.15.6

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Opened right front bottom section of model of mandalorian helmet in Cura 4.7.1
2. Oriented the object with the straight edge down
3. Sliced with tree supports enabled

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/5280110/92642127-5fdbfe00-f2a5-11ea-90fb-eaef2165255e.png)
 
**Actual results**
There is a significant gap between the tree supports and the model. This causes the support to print completely seperate from the model.

**Expected results**
The tree supports should have been connected. After redownloading the older version of cura I was able to slice and successfully print the object.

**Project file**
I included a project file for 4.6.2 and 4.7.1. The 4.6.2 project does not contain the issue
[CE3PRO_helmet-right-front-bottom-Cura4.6.2.3mf.zip](https://github.com/Ultimaker/Cura/files/5197483/CE3PRO_helmet-right-front-bottom-Cura4.6.2.3mf.zip)
[CE3PRO_helmet-right-front-bottom-Cura4.7.1.3mf.zip](https://github.com/Ultimaker/Cura/files/5197485/CE3PRO_helmet-right-front-bottom-Cura4.7.1.3mf.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
[cura4.6.log](https://github.com/Ultimaker/Cura/files/5197537/cura4.6.log)
[cura4.7.log](https://github.com/Ultimaker/Cura/files/5197535/cura4.7.log)

**Additional information**

**Comment by Ghostkeeper** [comment]
We made adjustments here: https://github.com/Ultimaker/Cura/issues/5759 but the top distance isn't fixed yet. I'll close this as duplicate because that issue is still ongoing.

As a workaround, setting the Support X/Y Distance and Minimum Support X/Y Distance to 0 makes the Z distance correct.
