### ISSUE TITLE
after the last update of ultimaker cura 4.7.1 the profile doesn't work. They aren't exist at all and sometimes reappears. I'm also trying to import an old one.

### ISSUE THREAD

**Issue by theodore0310** [Ultimaker/Cura#8362]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/8229 .

In 4.7 it's filtering custom profiles on whether the quality level is available for your current configuration, whereas previously it was selecting a random profile underneath which was causing unreliable and unreproducible prints. It's advisable to change the material type to a material type that does have your profile's quality level available.
