### ISSUE TITLE
[4.7.1] Initial Layer Bed Temp doesn't work

### ISSUE THREAD

**Issue by mark4allenorg** [Ultimaker/Cura#8364]
Setting an <Initial Build Plate Temperature> different from the <Build Plate Temperature> generates gcode at Layer:1, but uses <Build Plate Temperature> instead of <Initial Build Plate Temperature>.

**Application version**
4.7.1

**Platform**
Windows 10

**Printer**
Tronxy XY-2

**Reproduction steps**
1. Specified <Build Plate Temperature> 45
2. Specified <Initial Build Plate Temperature> 55

**Actual results**
Reviewed gcode file for M140.  Discovered M140 S45 in start gcode and at Layer:1

**Expected results**
Expected start gcode M140 S55 and M140 S45 at Layer:1

**Comment by Ghostkeeper** [comment]
Applied that correction for the next release.
