### ISSUE TITLE
Material Profiles Not Downloading to Printer

### ISSUE THREAD

**Issue by rachael7** [Ultimaker/Cura#8365]
**Application version**
4.7.1

**Platform**
Windows 8.1 Pro, Version 6.3.9600 Build 9600, NVIDIA Quadro 7000

**Printer**
Ultimaker S5 w/Material Handler, Firmware ver 5.8

**Reproduction steps**
1. Create new material by cloning a generic profile
2. Unlink the new material from old material
3. Modify new material name, brand, color, etc to match material I want to use
4. Restart Cura

or

1. Delete Material
2. Restart Cura

**Actual results**
When creating a new material in Cura, it is never downloaded to the printer for use. When removing an unwanted material from Cura, it is never removed from the printer. The Material Handler has a bunch of material profiles it can't even use because the profiles are not compatible with the Material Handler, but I have no way to remove them. And I cannot get a material I made by cloning the generics to download to the printer. Cura says it's downloading new materials when it starts up, but the printer never changes.

**Expected results**
After restarting Cura, new materials should be downloaded to the S5 Material Handler. There should be some way to remove unwanted materials from the Material Handler, but I can find no such method.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5205116/cura.log)

**Comment by Ghostkeeper** [comment]
Yeah I can reproduce that with the UM3 as well.

When you start a print, it says that you need to change the material to "unknown".

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
