### ISSUE TITLE
Name "Support Structure" from print settings not in italic when choosing Normal type support

### ISSUE THREAD

**Issue by Adammat** [Ultimaker/Cura#8366]
**Application version**
4.7.1

**Platform**
Windows 10 Education

**Printer**
Ender 3 pro

**Profile**
CHEPV4.5_0.24

**Reproduction steps**
1. Went to settings visibility
2. Marked Support Structure
3. Went to the profile
4. Choose Tree Structure
5. Choose Normal Structure

**Screenshot(s)**
Expected look: (Which works with the tree support option)
![2020-09-11 08_16_34-CE3PRO_token-3 - Ultimaker Cura](https://user-images.githubusercontent.com/31769674/92873334-36d37e80-f407-11ea-8799-3fa9e3586bbc.png)

Look when "Normal" is choosen:
![2020-09-11 08_15_53-CE3PRO_token-3 - Ultimaker Cura](https://user-images.githubusercontent.com/31769674/92873337-376c1500-f407-11ea-9d5e-a147fb78f225.png)

**Actual results**
The name "Support structure" is not in italic

**Expected results**
The name should be in italic

**Project file**
Not relevant. Happens on any file

**Log file**
Not relevant

**Additional information**
Not tested on any other non standard options, only Support Structure

**Comment by nallath** [comment]
Normal is the default support structure, so if you leave it at that, it's not set by the profile (and as such, not italic)
