### ISSUE TITLE
When I update the price for one custom filament it doesn't seem to save.  When I switch to another filament, the price stays the same as previously selected filament.

### ISSUE THREAD

**Issue by DavidRizzo** [Ultimaker/Cura#8371]
**Application version**
Ultimaker Cura Version 4.7.1

**Platform**
Windows 10
Processor: Intel(R) Core (TM) i7-7700 CPU @ 3.60GHz 
Ram: 16 GB
System Type: 64-Bit OS, Windows

**Printer**
Creality Ender-3 Pro

**Reproduction steps**
1. Preferences **Configure Cura**
2. Manage **Materials**
3. Entered **Filament Cost**
4. Switched to another custom filament and the price did not change
5. One Price was $22.99 the other was $23.99, when I switched from the one that costs $23.99 to the one that costs $22.99 the price stayed $23.99.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
**This one should be $23.99**
![image](https://user-images.githubusercontent.com/20258284/92981002-1981cd00-f466-11ea-9e35-bf03e6c5009b.png)

**This one should be $22.99**
![image](https://user-images.githubusercontent.com/20258284/92980981-0c64de00-f466-11ea-95f7-af0a200b8e63.png)

**Actual results**
When I switched from the one that costs $23.99 to the one that costs $22.99 the price stayed $23.99.

**Expected results**
The price should change to $22.99 and not remain $23.99.

- Strongman is $23.99
- Hatchbox is $22.99

**Project file**
N/A

**Log file**
N/A

**Additional information**
I'm using this to track materials, it would be nice if I could also clear out materials I am not using and only see my inventory.
The important additional information is that each field be SAVED this information is important!

**Comment by fieldOfView** [comment]
See the remark about the materials being "linked" in your screenshot. Linked materials share price information. If you "unlink" them you can enter a different price per material.

**Comment by DavidRizzo** [comment]
That resolved it, thanks.  Me happy again!

**Comment by Ghostkeeper** [comment]
The UX of this is less than ideal. It's communicated through a message saying "some metadata is shared", but it's not really intuitive or clear to the user.
