### ISSUE TITLE
[4.7.1] Print Setting "Tips" Remain After Print Setting Dialog Dismissed

### ISSUE THREAD

**Issue by mbmast** [Ultimaker/Cura#8378]
![2020-09-13](https://user-images.githubusercontent.com/15057985/93025666-a470dd80-f5b4-11ea-9177-e000e3878a0a.png)

**Application version**
4.7.1

**Platform**
Windows 10

**Printer**
Most likely, not applicable to this issue, but it was a custom printer setting (CreateBot 3D).

**Reproduction steps**
All I did was open the Print setting, reviewed a few settings and dismissed the dialog box.  I don't think I changed anythingl

**Screenshot(s)**
Attached

**Actual results**
The Tips dialog box ("Generate Support / Generate structures to support parts of the model which ...") remains orphaned on the screen, obscuring things behind it.

**Expected results**
When the Print dialog box is dismissed, I would expect any displayed Tips windows to also be dismissed.

**Project file**
Not included.  Cura functions fine.  No issues.  The only issue is the Tips window remains.

**Log file**
Attached, but probably not relevant as no crashes occured.

**Additional information**
(Extra information relevant to the issue.)

**Comment by konskarm** [comment]
Hi @mbmast. I tried reproducing the issue, but once I move my cursor away from the setting, the tooltip disappears. Can you reproduce it reliably? Maybe this was a one time thing.

**Comment by mbmast** [comment]
I can't reproduce it either.

**Comment by Ghostkeeper** [comment]
This happens very rarely, but once in a while. We haven't been able to fix it since it's so rare, and the workaround of just hovering over any setting is easy enough.
