### ISSUE TITLE
[4.7.1] Tree support option not visible

### ISSUE THREAD

**Issue by yael-lorenzo** [Ultimaker/Cura#8387]
**Application version**
4.7.1

**Platform**
MacOs Catalina 10.15.6

**Printer**
Creality Ender 3 Pro

**Reproduction steps**
1. Open model
2. Go to slice options and search for Tree Support
3. The option is not there.
4. Go to visibility options and it is not there either

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/22622247/93203941-23991980-f74d-11ea-9cfa-69c83a48df25.png)

**Actual results**
There are no tree support options.

**Expected results**
I should see the options

**Project file**
Any

**Additional information**
Cura has been behaving really strange since the last 3 updates.

**Comment by yael-lorenzo** [comment]
F**k, I found the option under support structure, sorry for the noise.

**Comment by DreadKnight** [comment]
Had issues as well finding it xD

**Comment by Ghostkeeper** [comment]
Yeah, I guess it's confusing. I do consider this location to be more logical than what it was before though. Hopefully these are just transitional pains from people who are still used to the old location of the setting. And the improved search function helps.

**Comment by DreadKnight** [comment]
Indeed. I've bumped into lots of old video tutorials on YouTube, which didn't help with the issue and nothing while googling :D
