### ISSUE TITLE
[4.7.1] Unsupported material on second layer of tree supports

### ISSUE THREAD

**Issue by jtatum** [Ultimaker/Cura#8390]
**Application version**
4.7.1

**Platform**
Mac OS X 10.15.6

**Printer**
Creality Ender-3 Pro

**Reproduction steps**
1. Enable tree supports touching buildplate
2. Slice file

**Screenshot(s)**
Layer 1:
![image](https://user-images.githubusercontent.com/340001/93276162-b6e54580-f773-11ea-9a50-882312d4bd3a.png)

Layer 1 and 2:
![image](https://user-images.githubusercontent.com/340001/93276190-c8c6e880-f773-11ea-8551-560880a1f0ed.png)

**Actual results**
Note that layer 2 has a new oval shape, with no brim or other supporting material underneath it on layer 1. There are actually two similar areas.

**Expected results**
All supports would extend down to layer 1 (and include brims where needed).

**Project file**
[IWPLA_triceratops-skull-repair.3mf.zip](https://github.com/Ultimaker/Cura/files/5228767/IWPLA_triceratops-skull-repair.3mf.zip)

**Log file**
N/A

**Additional information**
None.

**Comment by konskarm** [comment]
I can reproduce this. I'll put it up for discussion with the team.

**Comment by Ghostkeeper** [comment]
Hmm, I couldn't find this myself.
![image](https://user-images.githubusercontent.com/2448634/93603400-4123e880-f9c4-11ea-862e-afaaecc182d4.png)
Where is it going wrong?

**Comment by konskarm** [comment]
That's interesting. For me it occurs in the front of the model, under the tip of the jaw. Nevertheless, I couldn't find the exact same spot as @jtatum.

![image](https://user-images.githubusercontent.com/19388042/93603698-a8419d00-f9c4-11ea-924b-ea23418cf066.png)

In your picture, it should be here 
![image](https://user-images.githubusercontent.com/19388042/93604222-5fd6af00-f9c5-11ea-94e7-2c168307d105.png)

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
