### ISSUE TITLE
[4.7.1] retract into top/bottom layers

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#8394]
I have a lot of movements on the lower and upper layer. Each blank movement of the Cura makes a retract. As a result, each new line at the bottom or top is accompanied by a retract. After all the lines (see pic 2) cura make retract. See 3mf file also in the zip.
![изображение](https://user-images.githubusercontent.com/22872748/93344676-9fbd5b00-f83a-11ea-82b0-f0d7ecf786bf.png)
![изображение](https://user-images.githubusercontent.com/22872748/93344733-aea40d80-f83a-11ea-8e93-dca8facebc27.png)
[CFFFP_Neat_Jarv.zip](https://github.com/Ultimaker/Cura/files/5232497/CFFFP_Neat_Jarv.zip)

**Comment by Asterchades** [comment]
Nothing looks out of place there. Dark blue is just a travel - light blue shows a travel with retract.

**Comment by userosos** [comment]
> 
> 
> Nothing looks out of place there. Dark blue is just a travel - light blue shows a travel with retract.

Ok. Thx! I will check my printer. I think that need add into cura visual points for check retract and re-retract pont please!

**Comment by Asterchades** [comment]
Can't say that I disagree with you. The distinction between travels is there but it isn't immediately apparent which is which unless you start playing around with settings or someone tells you.

More to the subject at hand, does your printer actually retract at those points or was it just the preview that had you concerned?

**Comment by userosos** [comment]
> 
> 
> Can't say that I disagree with you. The distinction between travels is there but it isn't immediately apparent which is which unless you start playing around with settings or someone tells you.
> 
> More to the subject at hand, does your printer actually retract at those points or was it just the preview that had you concerned?

It will bug the printer. I reboot it and ok now. But in cura i want see point retract too.

**Comment by Ghostkeeper** [comment]
We've considered adjusting the legend in layer view to show this but never came around to a new design. It's now more likely that we'd implement some new way to see retractions because there is a desire to see Z seams too.

Maybe your printer is moving the feeder for those travels because of Linear Advance?

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
