### ISSUE TITLE
Improvement to gap filling in the works?

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#8396]
Hi guys,

I have struggled with inconsistent gap filling in Cura for a long time. I'm wondering is any improvement is in the works for 4.8 and beyond?

Here is a comparison between Cura and Slic3r.

Slic3r: Difference between identical layers is minimal. Perimeters minimize gaps. Gap filling is concise.
![image](https://user-images.githubusercontent.com/12439543/93374671-a3da8000-f81c-11ea-988e-80a8ffbf92ae.png)
.
.
.
.

Cura w/ gap filling: Significant difference between paths on identical layers. Gap filling is sporadic. With tiny gaps filtered out, relatively large gaps are left.
![image](https://user-images.githubusercontent.com/12439543/93375076-37ac4c00-f81d-11ea-9c81-5124d1f064ba.png)

.
.
.
.

Cura w/ gap filling w/ filter out tiny gaps: Similar to above, but with relatively large gaps left. On this print, filtering tiny gaps reduces estimated print time by 28%
![image](https://user-images.githubusercontent.com/12439543/93375227-7c37e780-f81d-11ea-8e1c-0c3384c73037.png)

.
.
.
.

Compensate wall overlaps definitely increases the ragged path appearance. But without it on a print like this, Cura generates enough wall overlap to cause over extrusion issues.
![image](https://user-images.githubusercontent.com/12439543/93375877-670f8880-f81e-11ea-9579-97d9f3715413.png)

**Comment by rburema** [comment]
Yes, though very likely not in 4.8

You can check some of the progress towards variable line width, which (we have good reason to believe) will be a huge help with overfill/underfill (as well as a host of other things) here: https://github.com/Ultimaker/CuraEngine/pull/1210
