### ISSUE TITLE
Request for steps: For Creation of AppImage of the CURA software to be run on Linux platform.

### ISSUE THREAD

**Issue by JaideepBgit** [Ultimaker/Cura#8401]
**Application version**
CURA application.

**Platform**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Reproduction steps**
1. Attempting to create app image from the soure. So that I can just run the app image of build particular version on another computer.
2. Can you provide the step by step method to create an app image. *(I couldn't do it and as it requires different file and folder creation which I couldn't complete)

**Actual results**
Could not create an AppImage which can be run.

**Expected results**
AppImage should be created

**Comment by nallath** [comment]
You can find the instructions here: https://github.com/ultimaker/cura-build/#build-cura-linux-appimage-with-docker
