### ISSUE TITLE
[4.7.1] Problem Materials E-sun

### ISSUE THREAD

**Issue by Rodrifrn** [Ultimaker/Cura#8402]
I'm having trouble placing Esun's Black PLA + material ... The settings appear as unsupported.

**Comment by nallath** [comment]
That is because PLA+ doesn't have a quality profile associated with it. You can still print with it, but it might not have all that great default profiles.

You can find a bit more in depth discussion about this here: https://github.com/Ultimaker/Cura/issues/8229

**Comment by Rodrifrn** [comment]
Thank's for your help.
