### ISSUE TITLE
Delete the custom add printer option from source code and remove it from the GUI.

### ISSUE THREAD

**Issue by JaideepBgit** [Ultimaker/Cura#8417]
**Application version**
CURA application. 3.6

**Platform**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Reproduction steps**
Ran ultimaker cura from github source, and when adding printers, there is custom add printer option. I want to delete that option.

**Actual results**
Could not find the place where Custom Add printer option is programmed in code to delete it.

**Expected results**
Custom Add printer option should be deleted

**Comment by nallath** [comment]
You need to remove the following files:

resources/extruders/custom_extruder_1.def.json
resources/extruders/custom_extruder_2.def.json
resources/extruders/custom_extruder_3.def.json
resources/extruders/custom_extruder_4.def.json
resources/extruders/custom_extruder_5.def.json
resources/extruders/custom_extruder_6.def.json
resources/extruders/custom_extruder_7.def.json
resources/extruders/custom_extruder_8.def.json
resources/definitions/custom.def.json
