### ISSUE TITLE
Mac OS BigSur Cura in 10 start times 1 work and is too slow

### ISSUE THREAD

**Issue by drakanfc** [Ultimaker/Cura#8426]
rocess:               cura [66978]
Path:                  /Applications/Ultimaker Cura.app/Contents/MacOS/cura
Identifier:            nl.ultimaker.cura
Version:               4.7 (4.7.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           cura [66978]
User ID:               501
Date/Time:             2020-09-20 20:01:11.401 +0200
OS Version:            Mac OS X 10.16 (20A5364e)
Report Version:        12
Anonymous UUID:        77150E70-E0E2-60BE-EFA0-D2F0A2ECC1A4

Time Awake Since Boot: 340000 seconds
System Integrity Protection: enabled
Crashed Thread:        0
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000001322a90000
Exception Note:        EXC_CORPSE_NOTIFY
VM Regions Near 0x1322a90000:
    JS JIT generated code        1322a8f000-1322a90000       [    4K] r-x/rwx SM=COW  
--> 
    mapped file                  1322a92000-1322a93000       [    4K] r--/r-x SM=S/A  Object_id=3fe17a29
ID   Vend/Dev
7005 67df1002
Seconds Ago   ID   Type
   340000.0   7005 Attach
Thread 0 Crashed:
0   libsystem_kernel.dylib            0x00007fff2398150a __pthread_kill + 10
1   libsystem_c.dylib                 0x00007fff23ad2bc3 raise + 26
2   libsystem_platform.dylib          0x00007fff23b52d7d _sigtramp + 29
3   ???                               000000000000000000 0 + 0
4   GLEngine                          0x000000131cabed0f glDrawArrays_IMM_Exec + 904
5   PyQt5._QOpenGLFunctions_2_0.so    0x0000001322a4250b meth_QOpenGLFunctions_2_0_glDrawArrays(_object*, _object*) + 123
6   nl.ultimaker.cura                 0x0000000106df4535 PyCFunction_Call + 165
7   nl.ultimaker.cura                 0x0000000106e72ccf PyEval_EvalFrameEx + 25599
8   nl.ultimaker.cura                 0x0000000106e77d12 0x106d9f000 + 888082
9   nl.ultimaker.cura                 0x0000000106e72733 PyEval_EvalFrameEx + 24163
10  nl.ultimaker.cura                 0x0000000106e77d12 0x106d9f000 + 888082
11  nl.ultimaker.cura                 0x0000000106e72733 PyEval_EvalFrameEx + 24163
12  nl.ultimaker.cura                 0x0000000106e77d12 0x106d9f000 + 888082
13  nl.ultimaker.cura                 0x0000000106e72733 PyEval_EvalFrameEx + 24163
14  nl.ultimaker.cura                 0x0000000106e77d12 0x106d9f000 + 888082
15  nl.ultimaker.cura                 0x0000000106e72733 PyEval_EvalFrameEx + 24163
16  nl.ultimaker.cura                 0x0000000106e774b2 0x106d9f000 + 885938
17  nl.ultimaker.cura                 0x0000000106e6c8ae PyEval_EvalCodeEx + 78
18  nl.ultimaker.cura                 0x0000000106dd489d 0x106d9f000 + 219293
19  nl.ultimaker.cura                 0x0000000106dab0b5 PyObject_Call + 101
20  nl.ultimaker.cura                 0x0000000106dc0bed 0x106d9f000 + 138221
21  nl.ultimaker.cura                 0x0000000106dab0b5 PyObject_Call + 101
22  nl.ultimaker.cura                 0x0000000106e76425 PyEval_CallObjectWithKeywords + 165
23  PyQt5.QtCore.so                   0x00000001099ca238 PyQtSlot::call(_object*, _object*) const + 40
24  PyQt5.QtCore.so                   0x00000001099ca136 PyQtSlot::invoke(void**, _object*, void*, bool) const + 374
25  PyQt5.QtCore.so                   0x00000001099cab28 PyQtSlotProxy::unislot(void**) + 88
26  PyQt5.QtCore.so                   0x00000001099caa9a PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) + 58
27  libQt5Core.5.dylib                0x00000001076c1437 QMetaObject::activate(QObject*, int, int, void**) + 1959
28  libQt5Quick.5.dylib               0x000000010cc25db4 QQuickWindowPrivate::renderSceneGraph(QSize const&) + 116
29  libQt5Quick.5.dylib               0x000000010cbb7abd 0x10cb0d000 + 699069
30  libQt5Quick.5.dylib               0x000000010cc2c4fc QQuickWindow::event(QEvent*) + 460
31  PyQt5.QtQuick.so                  0x000000010ca005aa sipQQuickWindow::event(QEvent*) + 106
32  libQt5Widgets.5.dylib             0x000000010a4a80ba QApplicationPrivate::notify_helper(QObject*, QEvent*) + 314
33  libQt5Widgets.5.dylib             0x000000010a4aa6ed QApplication::notify(QObject*, QEvent*) + 5181
34  PyQt5.QtWidgets.so                0x0000000109f6bd62 sipQApplication::notify(QObject*, QEvent*) + 114
35  libQt5Core.5.dylib                0x000000010768dae4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
36  libQt5Gui.5.dylib                 0x000000010aaa1136 QWindowPrivate::deliverUpdateRequest() + 54
37  libqcocoa.dylib                   0x0000001317bdbc05 0x1317bbc000 + 130053
38  com.apple.AppKit                  0x00007fff26daac9a -[_NSOpenGLViewBackingLayer display] + 868
39  com.apple.QuartzCore              0x00007fff297c469c CA::Layer::display_if_needed(CA::Transaction*) + 874
40  com.apple.QuartzCore              0x00007fff298fdc07 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 517
41  com.apple.QuartzCore              0x00007fff297a2135 CA::Transaction::commit() + 783
42  com.apple.AppKit                  0x00007fff26f971fe __62+[CATransaction(NSCATransa

**Comment by nallath** [comment]
Please fill in the bug template. This is not the information we need to debug / resolve the issue.
