### ISSUE TITLE
Align face to platform fails if the model is outside the build volume

### ISSUE THREAD

**Issue by gitcnd** [Ultimaker/Cura#8429]
title says it all.

if you're printing things that are almost the same size as the build volume, this happens all the time and is a major pain.

to reproduce - create something 440 x 390 x 390 and load it into a 400x400x450 build volume, then try to use the align-face option to make it the correct way up to print...

**Comment by rburema** [comment]
I can confirm this, we have put a bug on our backlog as internal ticket CURA-7734 -- meaning we're going to be working on this at some point. As always, we got a lot on out plate (no pun intended) so it might be a while before we get to it.

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
