### ISSUE TITLE
Problema na hora de abrir o arquivo > trava e fechaa

### ISSUE THREAD

**Issue by thailuar** [Ultimaker/Cura#8436]
**Application version**
4.7, a ultima versão disponivel

**Platform**
Intel core i5 inside, notebook asus, 4gb ram

**Printer**
Ender 3
**Reproduction steps**
1. Cliquei em arquivo
2. Abrir arquivo
3. Cliquei na pagina de downloads
4. Programa travou e posteriormente fechou

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/71820937/94130509-c5de8e80-fe2a-11ea-9189-c7c23c750965.png)
 

**Actual results**
O programa travou e fechou

**Expected results**
abrir a pagina de downloads para eu abrir o arquivo

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by konskarm** [comment]
Hi @thailuar. Please provide the bug description in English next time. Also, you should upload a log file which _may_ help us with what the problem is.
