### ISSUE TITLE
Rename "Keep Profiles" in Update Process to "Keep and import Profiles"

### ISSUE THREAD

**Issue by MarkusvonStaden** [Ultimaker/Cura#8440]
**Is your feature request related to a problem? Please describe.**
Every Time I update to a new Version, I accedently delete my old profiles and settings, due to the unclear terminology in the update process.

**Describe the solution you'd like**
Rename "Do you want to keep the Profiles" Window after deleting the old version to "Do you want to keep and import the Profiles"

**Describe alternatives you've considered**
A built-in update process, that automatically keeps all the settings and profiles

**Affected users and/or printers**
All clumsy users like me

**Comment by Ghostkeeper** [comment]
Our previous decision was that it should be made into a checkbox in the installer that is by default not checked, saying something like "reset to factory defaults". Or at least to make the option to not destroy data the default one and give appropriate warnings. See https://github.com/Ultimaker/Cura/issues/8233 for the previous discussions.
