### ISSUE TITLE
Settings Guide gets hidden

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8448]
If you open the Cura Settings Guide (BEST CURA PLUGIN EVER!), then click in the main window, the guide gets hidden behind the main window and won't automatically come forward.  This may confuse some (it did me for a while) because it appears as if the window has closed, but it will not reopen by reselecting the guide, as you would expect it to if it had closed.

**Application version**
All tested, 4.5.* through 4.7.1

**Platform**
Mac OSX Catalina (10.15.6)

**Printer**
Irrelevant

**Reproduction steps**
1. Open Cura Settings Guide
2. Click in main window
3. ::Poof::

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Settings Guide window gets hidden by main window, with no way to bring it forward without minimizing or moving the main window.  No "Windows" menu exists (I understand why) to choose which window is front-most, and reselecting "Cura Settings Guide" or right-clicking on a setting fails to bring the window forward.

**Expected results**
The window should either refuse to be hidden (as with the Marketplace window, which just throws a beep at you if you click outside of it), or, 1) there should be a "Windows" menu which lists open windows to select from (In understand why this is not there - there are usually no multiple windows in Cura - this menu could be set to only appear if there is a second window of some sort), or, 2) reselecting "Cura Settings Guide" from either the Extension menu or via right click on a setting should bring the window forward again.

**Project file**
N/A

**Log file**
N/A

**Additional information**
N/A

**Comment by Asterchades** [comment]
The Settings Guide plugin is not maintained by Ultimaker, despite being written (and maintained) by Ghostkeeper.

You're probably better approaching him on its Guy page: https://github.com/Ghostkeeper/SettingsGuide
