### ISSUE TITLE
I can't find delta machines

### ISSUE THREAD

**Issue by famfilho** [Ultimaker/Cura#845]
Hi I'm from Brazil and I have a delta printer that I bought here

I downloaded the Cura 2.1.2 and for my surprise I can't find any delta machines. So, how can I do to setting my machine in this SW version?
data of my machine:
Company: PUZZLES 3D (this is a very small campany)
Bed Diameter: 200mm
Height: 300mm
Nozzle diameter: 0,4mm
Extruder N°: single
Control Board: RAMPS 1.4
![img_20160528_202241834](https://cloud.githubusercontent.com/assets/19826770/16547841/ac43e36a-4148-11e6-8252-7b528384308e.jpg)

**Comment by fieldOfView** [comment]
Cura 2.x does not have support for circular beds at the moment. It has to be re-implemented, either by us or by the community.

Cura 15.04 is still available for download if you want support for delta printers out of the box.

**Comment by famfilho** [comment]
Dear all
Thank you for the quickly return.
Sincerely.
Francisco Machado 

Enviado por TypeApp



Em 4 de jul de 2016 01:23, em 01:23, Aldo Hoeben <notifications@github.com> escreveu:
