### ISSUE TITLE
Prime tower dont print layers for 2nd extruder

### ISSUE THREAD

**Issue by thorstensd** [Ultimaker/Cura#8454]
Hello,

It looks like there is a bug in Cura depending to prime tower.
The Prime tower dont print layers for 2nd extruder if they are not needed up to a certain layer (for me layer 39 see file).
This produces a problem, that if the 2nd extruder will be used up to a specific layer (in this case layer 40 see file), it will print in to nowhere on the prime tower, becasue up to layer 39 there was nothing printed in the inside of the primetower for 2nd extruder.
Its good, to dont waste material and dont do unnecassary extruder changes - but start printing in layer 40 wont work. 

Version 4.6.1
Windows 10
Costum Printer

![layer39](https://user-images.githubusercontent.com/25565461/94361106-364b1100-00b2-11eb-8789-6cd7de73af8f.png)
![layer40](https://user-images.githubusercontent.com/25565461/94361108-377c3e00-00b2-11eb-8b40-5626ebef2b23.png)

Thank you very much.

Best regards Thorsten

**Comment by rburema** [comment]
Hi @thorstensd 

That is correct. The prime tower is a helper structure and doesn't need to be printed perfectly, as long as it doesn't interfere with the actual model. As such, if the outer shell is printed correctly, the prime tower can just be used as a 'bucket' to dump prime material in.
