### ISSUE TITLE
Empty spaces on z seam

### ISSUE THREAD

**Issue by BerkhanB** [Ultimaker/Cura#8455]
Cura version: 4.7.1

OS: W10, GPU RTX2060 mobile

Anet A8

**Reproduction steps**
1. I normally sliced Calibration Cube without changing the settings.

**Screenshot(s)**
Turned to this:
![2020_09_27_13_05_43_xyzCalibration_cube_Ultimaker_Cura](https://user-images.githubusercontent.com/34602506/94362380-78c91980-00c3-11eb-8d87-3182d22696eb.png)

Previously:
![2020-09-27 13_17_08-AA8_phone_mount_top - Ultimaker Cura](https://user-images.githubusercontent.com/34602506/94362416-ccd3fe00-00c3-11eb-9545-70a86e443196.png)

Why there is a gap there and how can I solve it?

**Project file**
[xyzCalibration_cube.zip](https://github.com/Ultimaker/Cura/files/5288111/xyzCalibration_cube.zip)

**Log file**
[DxDiag.txt](https://github.com/Ultimaker/Cura/files/5288113/DxDiag.txt)

**Comment by fieldOfView** [comment]
Check the "Coasting" setting.

**Comment by BerkhanB** [comment]
Thank you, I realized that I enabled coasting before my last prints but I didn't check the preview for that.
