### ISSUE TITLE
Support Blocker not working in [4.7.1]

### ISSUE THREAD

**Issue by Pshaire** [Ultimaker/Cura#8461]
When trying to use support blocker button in 4.7.1, nothing happens. You can click on and select the support blocker button, but when clicking on the workspace or object, there is no grey blocker box. Nothing occurs. I rebooted both application and computer multiple times. Once I downgraded to Cura 4.6.2, the problem resolved itself.

**Comment by nallath** [comment]
Please fill in the entire bug template. We need things like logs and on what system you're trying to do this.

**Comment by Pshaire** [comment]
Disregard. All in my head.
