### ISSUE TITLE
SOVOL SV02 printer problem

### ISSUE THREAD

**Issue by Fabdu57** [Ultimaker/Cura#8471]
Hello,

I have two printers at home : SOVOL SV02 and CREALITY Ender 3 V2.
I use on both exactly same profile : [Creality V2  Figurine.zip](https://github.com/Ultimaker/Cura/files/5305831/Creality.V2.Figurine.zip)

Strangely, when i prepare my item with SV02 profile, i have a lot of defect :
![Defects](https://user-images.githubusercontent.com/69864038/94692003-512bb880-0332-11eb-9fd9-942dd0899765.png)

If i make the same item with Ender 3 printer and profile, no problem.
In attachment both 3.m files : 
[Item.zip](https://github.com/Ultimaker/Cura/files/5305869/Item.zip)

I'm not sure, but i think that problem is Cura with SV02 printer.

Can you help me please ?

**Comment by nallath** [comment]
The Sovol 2 has coasting enabled by default. The Creality 3 does not.

**Comment by Fabdu57** [comment]
So how can i do in this case ?

**Comment by nallath** [comment]
You click the checkmark in the setting list next to "Enable coasting" 

![image](https://user-images.githubusercontent.com/3922611/94704087-d5386d00-033f-11eb-8980-460424fb22c1.png)

**Comment by Fabdu57** [comment]
Like if i enable it, i have still the problem

**Comment by nallath** [comment]
You can also try to change the maximum resolution / maximum deviation setting.

**Comment by Fabdu57** [comment]
I am sorry but i don't understand.
You close my topic and propose me some ideas.

As i say, on printer creality i don't have this problem.
Is the slicer is the same for ender 3 pro and SV02 in Cura ?

**Comment by Fabdu57** [comment]
Finaly i find the solution...
Your firs proposal was good : activation of coasting, then modify "coasting volume" and put 0 instead of 0.06mm². Then my problem dissapear.

**Comment by fieldOfView** [comment]
> Like if i enable it, i have still the problem

What @nallath meant was that by default the Sovol 2 is configured with Coasting enabled. If you turn it off in the sidebar (ie: don't HIDE the setting, but uncheck the checkbox in the sidebar), the defects will probably disappear.

**Comment by fieldOfView** [comment]
>  modify "coasting volume" and put 0 

That is effectively the same as unchecking the "Enable coasting" checkbox.

**Comment by Fabdu57** [comment]
I don't understand.
After make "0" no holes.
If i put again 0.064mm², no hole again.

For me; slicer for SV02 have a problem...

**Comment by Fabdu57** [comment]
Problem is solve.
Thanks to nallath and fieldOfView for your help
