### ISSUE TITLE
chunk missing from gcode

### ISSUE THREAD

**Issue by daboss257** [Ultimaker/Cura#8482]
when i slice a file, a chunk of the gcode is just cut out of the center. any way to fix this?

**Comment by eskeyaar** [comment]
can you share your project file? need some more info. Pls, fill the template.

**Comment by Ghostkeeper** [comment]
See also https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/missing_parts.md
