### ISSUE TITLE
ultimaker cura 4.7.1 

### ISSUE THREAD

**Issue by battistipaolo** [Ultimaker/Cura#8484]
strange condition:
A) - fulfillment enabled.
B) - support disabled.
action: does not fill.
question: where am I wrong?

regards
paolo battisti

**Comment by battistipaolo** [comment]
[250_220_petg.zip](https://github.com/Ultimaker/Cura/files/5321351/250_220_petg.zip)

file .zip (problem)

**Comment by battistipaolo** [comment]
Hi, 
section the drawing, positioned on line 30,
 see inside: 
you will also see that the filling is missing
regards
paolo battisti

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

**Comment by Ghostkeeper** [comment]
Your model is hollow.
![image](https://user-images.githubusercontent.com/2448634/95097003-435ca580-072d-11eb-8ea8-800579f62633.png)
It should not get infill if it's hollow.
