### ISSUE TITLE
Print head display

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8487]
**Application version**
Ver.4.6.2

**Platform**
Win10

**Printer**
custom

Hi.
There seems to be something wrong with the print head display that appears when you move the slider bar in the preview.
When the slider bar is increased, the print head in the current position is lighter in color than the print head in the previous position.
![無題](https://user-images.githubusercontent.com/69872727/94988384-bb995e80-05a7-11eb-9be4-30acb7e09036.png)

I think the colors are reversed.
If you move the screen even slightly, the print head in the current position becomes darker in color.
![無題](https://user-images.githubusercontent.com/69872727/94988445-29de2100-05a8-11eb-8a19-04039a256597.png)

Also, when the slider bar is reduced, the print head seems to be in the wrong position.
![無題](https://user-images.githubusercontent.com/69872727/94988497-922d0280-05a8-11eb-9561-23b75db6a57b.png)

My preference would be for the print head to be displayed in the current position only. Or I would like to be able to optionally specify whether or not to display one previous position.

Best regards.

**Comment by Ghostkeeper** [comment]
Yeah, this issue was known to us already. It's a rendering update bug. If you rotate the camera the rendering updates and it shows the more opaque nozzle in the correct position.

It's been like this since 4.4 or so. I'll see if the team thinks it's worth investigating since I don't think that was ever discussed.

**Comment by zyddst** [comment]
hello  could you tell me how to add a printer? l have no printer  ,so i can use cura?

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
