### ISSUE TITLE
2 slicing profiles selected at the same time

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#849]
Cura 2.1.2 on MacOS.
I just added the file 
https://gist.github.com/fieldOfView/ae85f755fc70d1c65e6968a870dfef0c
to ~/.cura/machines
https://github.com/Ultimaker/Cura/issues/847#issuecomment-230454073
then created a machine with that new type and selected an existing profile.

I'm sure this is not supposed to happen:
![screenshot](https://cloud.githubusercontent.com/assets/604692/16606539/0f083626-4339-11e6-990e-493f33d48501.png)

**Comment by MarcusWolschon** [comment]
I got the same thing when adding a new machine.
Goes away after restarting Cura.

Then I can select another slicing profile but the selection shown in the collapsed list-view stays the same regardless of what I select in the expanded list.

**Comment by Ghostkeeper** [comment]
Fixed in version 2.2.
