### ISSUE TITLE
[4.7.1.AppImage] select face align to the build plate

### ISSUE THREAD

**Issue by juckendesAuge** [Ultimaker/Cura#8490]
Hello,
i cant find in the rotations menu:
select face align to the build plate

![Bildschirmfoto_2020-10-03_14-33-12](https://user-images.githubusercontent.com/24550429/94991819-c9d68300-0585-11eb-8ebb-1a04fad52eaa.png)
:

**Comment by nallath** [comment]
Since you didn't post any logs, I am going to assume that your openGL support is too old. Only newer versions support the lay flat operation.

For the next time, please fill in the entire issue template. It has information that we need to fix issues like this.
