### ISSUE TITLE
Ultimaker Cura 2.70 and 2.71 takes unusually long time to load

### ISSUE THREAD

**Issue by zipCoder933** [Ultimaker/Cura#8492]
Ultimaker Cura 2.7.0 and 2.7.1 takes an unusually long time to load.  Just recently it has taken so long I wondered if was stuck there forever.

I was wondering if this is a bug or maybe a performance issue on your side.

**Application version**
2.7.0 and 2.7.1

**Platform**
Windows 10

**Printer**
(Not important for this specific bug)

**Reproduction steps**
1. I re installed Cura 2.71 several times and then tried to re-install 2.70 several times also, only with the same issue.

**Screenshot(s)**
(Not needed)

**Actual results**
I just sat and spun in the Splash GUI for 10-15 minutes, it could have just kept going and going, Windows was telling me the program was not responding, and so eventually, I had to just shut it down. This happened every time I tried to run both Cura versions.

**Expected results**
It only takes 2 minutes MAX time to load. I installed Cura 2.6.0 and it only took 20 seconds to load the application.

**Project file**
(Not related)

**Log file**
I couldn't find it...

**Additional information**
None

**Comment by jellespijker** [comment]
Please fill in the bug template and provide some logs because this information is to limited for.

FYI I just opened up my personal archive and. I didn't notice any significant change for version for Cura 2.7 ( running on Linux )

**Comment by jellespijker** [comment]
There should be a Cura folder in the `C:\Users\<usernamer>\Appdata\Local` in here there is a log file located.
Alternatively you can go to the help menu and click on the item show config folder

btw is there a reason why you are still using 2.7.0 and 2.7.1? We're currently on version 4.7.1 and I estimate that Cura 2.7.0 was released somewhere in 2017
