### ISSUE TITLE
not printing hollow?

### ISSUE THREAD

**Issue by yzorgone** [Ultimaker/Cura#85]
Newest Cura 
I wanted to print a hollow object.  however i cant get cura to not fill my object.
i have set the infill parameter to 0% for this.

also i have a slight feeling that opening stl files takes somewhat longer in new Cura.
![bildschirmfoto 2015-07-02 um 10 58 43](https://cloud.githubusercontent.com/assets/1657305/8473366/5fe3d540-20a9-11e5-82eb-5c49617e8038.png)

**Comment by BagelOrb** [comment]
This bug is resolved in the master branch in fdmprinter.json
The inherit function for infill_line_distance was wrong in the 15.06 branch

**Comment by BagelOrb** [comment]
Fixed on 15.06

**Comment by yzorgone** [comment]
okay…  that doesn’t tell me how to fix my problem.
i get the error  Cura-15-06-01 if you got anything newer. please
can you point me the direction to the download?

**Comment by BagelOrb** [comment]
It will be included in the distributed Cura soon. 

However, until then you can unhide the infill line distance setting (Machine Preferences > scroll down > tick the checkbox next to [Infill Line Distance]) and set it to zero. 

(Zero is a special case, meaning the distance between the infill lines is infinite, i.e. there are no infill lines.)

**Comment by yzorgone** [comment]
thx
