### ISSUE TITLE
Sliced file not saved when custom machine is used in alternative json location

### ISSUE THREAD

**Issue by MarcusWolschon** [Ultimaker/Cura#850]
Cura 2.1.2 on MacOS.
I just added the file
https://gist.github.com/fieldOfView/ae85f755fc70d1c65e6968a870dfef0c
to ~/.cura/machines
as per https://github.com/Ultimaker/Cura/issues/847#issuecomment-230454073
then created a machine with that new type and selected an existing profile.

Slicing works fine, I can select a location to save the .gcode file, but no file is actually saved there.

Cura engine log:

```
 Calling engine with: ['/Users/marcuswolschon/Desktop/Cura 2.1.2.app/Contents/MacOS/CuraEngine',     'connect', '127.0.0.1:49674', '-j', '/Users/marcuswolschon/.cura/machines    /ultimaker2_extended_reprap.json', '-vv']

Cura_SteamEngine version DEV
Copyright (C) 2014 David Braam

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
Couldn't open JSON file.
ERROR: Failed to load json file: /Users/marcuswolschon/.cura/machines    /ultimaker2_extended_reprap.json
Connecting to 127.0.0.1:49674
Connected to 127.0.0.1:49674`
```

Aparently the UI can load json files from that location but the engine can't ?

**Comment by MarcusWolschon** [comment]
When you copy fdmprinter.json, ultimaker2.json ... from
..../Cura 2.1.2.app/Contents/Resources/cura/resources/machines
into 
~/.cura/machines

then everything works.
Aparently it looks for the parent files only in the same directory, where it got the json file given by the UI.

**Comment by awhiemstra** [comment]
Yeah this is a known issue with the engine and how things are communicated between the two. For 2.2 this will be less of an issue.

**Comment by ChrisTerBeke** [comment]
Is this still an issue?

**Comment by Ghostkeeper** [comment]
If I understand this correctly, it was worked around in 2.2 and completely resolved by https://github.com/Ultimaker/Uranium/commit/a3c77e86fc23c91d5084a7530616ead95776f86e in 3.0.
