### ISSUE TITLE
cura 4.7.1 no puede agregar nueva impresora.

### ISSUE THREAD

**Issue by hakael** [Ultimaker/Cura#8504]
Ultimaker Cures 4.7 and 4.7.1, when trying to add a new printer, the program freezes and closes.

App version
4.7 and 4.7.1

Platform
Windows 10, 64-bit.

Printer
(not important for this specific bug)

Playback steps
Picho configuration, printer, add printer, a window with several options is displayed, when you click on any of the options the program blocks and closes, preventing the possibility of adding a new printer.

Results
The program hangs and closes.

Expected results
add a new printer and use your profile.

File of
project (not related)

File of
record I couldn't find ...

training
no additional

**Comment by konskarm** [comment]
Hi @hakael. Please include a cura log file which may help us identify your problem. See instructions in https://github.com/Ultimaker/Cura#logging-issues.
