### ISSUE TITLE
Changing LA value from special modes section

### ISSUE THREAD

**Issue by SFRSKZ** [Ultimaker/Cura#8511]
Adding Linear advance value to starting script can be problematic when using different materials's profiles under 1 printer config. 
making LA settings part of filament profile would be easier to use instead of changing printer' starting gcode script for every different filament type.

**Comment by fieldOfView** [comment]
The Linear Advance Setting plugin in combination with the Material Settings plugin - both available from the Marketplace - will let you do this.
