### ISSUE TITLE
Add a printer

### ISSUE THREAD

**Issue by zyddst** [Ultimaker/Cura#8516]
Hello, everyone. I am now configuring the Cura environment. I have a problem. The problem is as follows: when I run (python3 Cura)_ app.py ）The page of adding printer appears, but I don't have a printer. Can't I use Cura? If it works, how can I solve it? Thank you.

https://github.com/zyddst/restudy/blob/master/Screenshot%20from%202020-10-11%2020-01-07.png

**Comment by Ghostkeeper** [comment]
If you have an Ultimaker printer (UM3 or later), make sure it's turned on and connected to the network.
If you have an OctoPrint-connected printer, make sure the OctoPrint plug-in for Cura is installed too. You can find it in the Marketplace.

If your printer doesn't have any network connectivity, just open up the "Add a non-network connected printer" panel below and select your printer model manually from the list.
