### ISSUE TITLE
Import location of stl in an assembly from an stl

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#8519]
**Is your feature request related to a problem? Please describe.**
I want to export my assembly from Autodesk Inverter to Cura. This assembly contains 7 parts and i don't want to manually have to allign all stl's. Also some parts need to be printed from a different material. If i import the assembly with the Inventer plugin I can't select the individual parts. Inventor as far as I know can't export in the 3mf format.
![image](https://user-images.githubusercontent.com/6079002/95689552-cbe9b300-0c11-11eb-9df2-5540654f8667.png)
![image](https://user-images.githubusercontent.com/6079002/95689611-4286b080-0c12-11eb-8b8a-7a4d94b6db3a.png)
[parts.zip](https://github.com/Ultimaker/Cura/files/5361994/parts.zip)

**Describe the solution you'd like**
If I export an stl for all the parts in Inventor and open this in Simplify3D they are all alligned as they were in the assembly in inventor. If i do the same in cura they all end up with their center on top of each other I have to allign them manually.

**Describe alternatives you've considered**
- export stl's individually and align the manually -> time consuming, especially since this is only a small test structure and I want to go to a design with even more parts.
- export 3mf file -> not supported by inventor
- Try drawing in solidworks and export an 3mf file -> I prefer drawing in inventor.

**Comment by nallath** [comment]
The inventor plugin isn't created by us, so any issues should be discussed there. The official thread can be found here: https://community.ultimaker.com/topic/21489-inventor-plugin-official-thread/

**Comment by martijnschouten** [comment]
Check thank you modifying the inverter app indeed would solve the issue. But you as the title of the issue says, I would like to see an option in cura to not manually reassign the origin of my stl's.

**Comment by fieldOfView** [comment]
Could you try selecting all imported models in Cura and merging them? You can ungroup them afterwards.

**Comment by martijnschouten** [comment]
Thank you fieldOfView, merging all models does align then as how they were aligned in the assembly in the inverter. This solves the issue.
