### ISSUE TITLE
Profile management - update profile button

### ISSUE THREAD

**Issue by danilius** [Ultimaker/Cura#853]
I'm finding the profile management a bit fiddly.

I would like to see an "Update profile" button, as well as a "Duplicate Profile" button.

**Comment by nallath** [comment]
2.2 (The stuff that is on master now) has a duplicate & update profile function.

**Comment by fieldOfView** [comment]
> 2.2 (The stuff that is on master now) has a duplicate & update profile function. 

...and so much more...

@danilius: I totally agree with this request. I feel partly responsible for this, because I implemented the profile management. Rest assured that it has been reimplemented by people much smarter than me (and with more time than I had).

**Comment by danilius** [comment]
Thanks for that.

I would love to download the build from git, but had too many problems with
getting it to compile or run so I gave it up. It would be a great idea to
have nightly builds, which we can download, test and delete as we see fit!

**Comment by nallath** [comment]
If you drop me a mail (or contact me on irc / forum) I can send you a nightly master build.
