### ISSUE TITLE
cura 2.1 default material profiles inconsistent: mess up retraction and profile management

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#854]
issue: inconsistent default profiles that contain retraction settings make it impossible to easily make custom profiles (seen as a saving bug by some...)
but more importantly exemplify that the current profile management flow is flawed by design. 

see the issue worked out here: https://ultimaker.com/en/community/21569-cura-212-doesnt-load-retraction-distance-from-selected-profile?page=1&sort=#reply-150604

best course of action?  
i'm not sure. right now problem is that without hacking with text editor, even as simple setting as retraction or material print temperature cannot be changed. that's pretty extreme for any slicer. 

ideally there would be material profile management just like for general slicing settings, but then the gui would need to be adjusted so that it's clear what goes where. that's a big change.

so in the meantime maybe make default material profiles small, predictable, and consistent? at least the same variables in all?

**Comment by Ghostkeeper** [comment]
Yeah, this is known to us, and we have a solution: https://github.com/Ultimaker/Uranium/pull/133
This is the most invasive change we have for 2.2 and hopefully that we'll have ever again. One of the changes that's directly visible is that the user profile is never overwritten by any other profile, so there should be no problem any more where some profile prevents the user from setting the temperature.

For the next release, the setting overriding, inheritance and profile management should be more intuitive. Also for next release, we have a better plan to keep the individual profiles small and consistent. They won't have the same variables set, of course. Profiles will allow using a formula to set a setting though, so we can make them a lot smaller and separate them better.
