### ISSUE TITLE
popup windows appearing blank

### ISSUE THREAD

**Issue by russlam** [Ultimaker/Cura#8572]
**Application version**
4.7.1

**Platform**
windows 7 64bit

**Printer**
cr10s pro

since updating, whenever a popup window opens in cura, such as "discard or keep changes" or "settings", it is devoid of all text and buttons until I resize the popup window. after resizing the window all proper text show up. this happens on all popup windows in cura. 

![Untitled](https://user-images.githubusercontent.com/73134579/96497350-8ed87e80-1218-11eb-8e02-6b224f0669c4.png)
![Untitled2](https://user-images.githubusercontent.com/73134579/96497365-939d3280-1218-11eb-8a73-d0c3c3c0d161.png)

**Comment by Ghostkeeper** [comment]
Do you have a log file for us?
