### ISSUE TITLE
Two Trees Bluer Profile

### ISSUE THREAD

**Issue by teixeiramichael00** [Ultimaker/Cura#8584]
Hello guys, first of all I want to say thank you about everything you all have done to the comunity.
My request is just to ask if is possible to create a Two tree bluers profile in the Cura.

Thank you!!

**Comment by nallath** [comment]
It's possible, but we only create / maintain the Ultimaker profiles. Any non-ultimaker profile has been contributed to us by others (either the comunity or the party that made the printer).

You can find more information about how to make these profiles here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
