### ISSUE TITLE
Some Exception Error with 3mf "platform" and "platform_offset"

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#8585]
**Application version**
(The version of the application this issue occurs with.)
master version

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
windows 10

**Printer**
(Which printer was selected in Cura?)
any printer with *.3mf "platform" and "platform_offset" in machine definition *.json(for example, creality cr-10s pro)

**Reproduction steps**
1. change machine to Creality CR-10S Pro
2. restart cura
3. not display platform
4. check cura.log file
`INFO - [MainThread] cura.CuraApplication.run [792]: Initializing container manager`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: Exception: An exception occurred in 3mf reader.`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: Traceback (most recent call last):`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:   File "3MFReader\ThreeMFReader.py", line 202, in _read`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:     um_node = self._convertSavitarNodeToUMNode(node, file_name)`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:   File "3MFReader\ThreeMFReader.py", line 112, in _convertSavitarNodeToUMNode`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:     um_node.addDecorator(ConvexHullDecorator())`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:   File "Scene\ConvexHullDecorator.py", line 49, in __init__`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]:     self._build_volume.raftThicknessChanged.connect(self._onChanged)`
`ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: AttributeError: 'NoneType' object has no attribute 'raftThicknessChanged'`
`DEBUG - [MainThread] UM.Scene.Camera._preferencesChanged [255]: Changing perspective mode to perspective.`

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
not display platform
![image](https://user-images.githubusercontent.com/39176348/96687798-545b1700-13bb-11eb-9f61-a378a96829cb.png)

if change to another machine and change to "CR-10S PRO" again, display platform
![image](https://user-images.githubusercontent.com/39176348/96687899-7a80b700-13bb-11eb-88c4-d7516e707573.png)

**Actual results**
(What happens after the above steps have been followed.)
if there are *.3mf platform and platform_offset data in machine definition file *.json, not display platform

**Expected results**
(What should happen after the above steps have been followed.)
display platform

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: Exception: An exception occurred in 3mf reader.
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: Traceback (most recent call last):
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: File "3MFReader\ThreeMFReader.py", line 202, in _read
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: um_node = self._convertSavitarNodeToUMNode(node, file_name)
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: File "3MFReader\ThreeMFReader.py", line 112, in _convertSavitarNodeToUMNode
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: um_node.addDecorator(ConvexHullDecorator())
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: File "ConvexHullDecorator.py", line 49, in __init__
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: self._build_volume.raftThicknessChanged.connect(self._onChanged)
ERROR - [Thread-2] 3MFReader.ThreeMFReader._read [258]: AttributeError: 'NoneType' object has no attribute 'raftThicknessChanged'

**Additional information**
(Extra information relevant to the issue.)
if *.3mf platform without platform_offset is used  or delete um_node.addDecorator(ConvexHullDecorator()) in ThreeMFReader.py or stl, obj platform is used, displaying platform is ok. And it doesn't happen 100% every time restart. About 2 times every 5 restarts???

**Comment by konskarm** [comment]
I tested it and it is now fixed. Nice catch @joonghochoe!
