### ISSUE TITLE
Perca dos perfis

### ISSUE THREAD

**Issue by fabriciosilveira-sjc** [Ultimaker/Cura#8588]
O meu app Cura para Windows perdeu todos os perfis de configuração de impressão.
Mesmo eu tentando importar os perfis de backup o cura não aceita.

![Imagem_Cura](https://user-images.githubusercontent.com/73246642/96750995-05a18300-13a3-11eb-9785-af1b56d724e1.PNG)

**Comment by fabriciosilveira-sjc** [comment]
O perfil de material da empresa eSUN está com bug.
Quando ele seleciono o PLA desta impressa os perfirs de configuração do Cura desaparecem.

**Comment by nallath** [comment]
Could you please report your problem / issue in English?

**Comment by fabriciosilveira-sjc** [comment]
The material profile of the eSUN company has a bug.
When he selects the PLA from this form, the Cura configuration profiles disappear.

**Comment by Ghostkeeper** [comment]
eSUN's "PLA Pro" is listed as being of the PLA+ material type. Most likely your printer has no profiles for PLA+. Sadly, not all combinations of printer & material type have any profiles. This is expected behaviour.

See also https://github.com/Ultimaker/Cura/issues/8229 .
