### ISSUE TITLE
some problem of "Merge Models"

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/Cura#8597]
**Application version**
(The version of the application this issue occurs with.)
Master Version

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Windows 10 V.2004

**Printer**
(Which printer was selected in Cura?)
Any Printer

**Reproduction steps**
1. load multi color model(ex. https://www.thingiverse.com/thing:4511733)
2. merge models

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
- In master version
loaded models
![화면 캡처 2020-10-23 110131](https://user-images.githubusercontent.com/39176348/96948396-88038180-1520-11eb-9a77-a03c3a967b33.jpg)
merged models
![화면 캡처 2020-10-23 110205](https://user-images.githubusercontent.com/39176348/96948427-9782ca80-1520-11eb-9d83-683b1ca510ef.jpg)

- 4.7.1 version
loaded models
![화면 캡처 2020-10-23 105345](https://user-images.githubusercontent.com/39176348/96948460-aa959a80-1520-11eb-8df5-7d116a185512.jpg)

merged models
![화면 캡처 2020-10-23 105439](https://user-images.githubusercontent.com/39176348/96948481-b7b28980-1520-11eb-9a1a-61e701f27cd7.jpg)

**Actual results**
(What happens after the above steps have been followed.)
The multiple models are merged in an arranged shape.

**Expected results**
(What should happen after the above steps have been followed.)
want to be put together in the right shape.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)
[CE5P_24.zip](https://github.com/Ultimaker/Cura/files/5426889/CE5P_24.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)
This is the master version with the libnest2d, pynest2d  library(?) applied. This problem is caused by automatic arrange, so I have to manually rotate each model to the appropriate angle. Or is it possible to merge normally through options or menus?

**Comment by joonghochoe** [comment]
I have found a normal merge procedure.
1. load models
2. select all models
3. select rotation tool
4. reset rotation
5. merge models

**Comment by nallath** [comment]
For our reference: CURA-7796

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)? Can this be closed?
