### ISSUE TITLE
rotating problem

### ISSUE THREAD

**Issue by yzorgone** [Ultimaker/Cura#86]
i maybe found another bug. ;)
Cura version 15.06.01, rotating objects has no effect on previously generated gcode.
it should trigger a reslice though.
![bildschirmfoto 2015-07-02 um 11 51 25](https://cloud.githubusercontent.com/assets/1657305/8474597/7fdd823a-20b1-11e5-8e28-77e6f0a23e6c.png)

**Comment by BagelOrb** [comment]
Sounds like a legit bug. What does the screenshot have to do with it?

**Comment by yzorgone** [comment]
the screenshot shows what i get to see...  :)
gscode view with blended in 3dmodel... the gcode object leans to the back (is tilted)' the mesh is not leaning back.
