### ISSUE TITLE
Fortis Profile Bugging Material Estimation

### ISSUE THREAD

**Issue by Mikaledoux** [Ultimaker/Cura#8600]
**Application version**
Version 4.7

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
Ultimaker S5

**Reproduction steps**
1. I imported my model in Cura.
2. Choosed my registered Fortis Profile. 
3. I Desactivated PrintCore 2 because i don't need it.
4. I sliced it as usual
 
**Screenshot(s)**

![Problme Fortis Profile 1](https://user-images.githubusercontent.com/73349210/97013849-d9743680-1549-11eb-8897-3ac98d6b130d.png)

![Problme Fortis Profile 3](https://user-images.githubusercontent.com/73349210/97013905-ed1f9d00-1549-11eb-9ba8-84a59e454b4e.png)

![Problme Fortis Profile 2](https://user-images.githubusercontent.com/73349210/97013921-f3157e00-1549-11eb-81b0-1a89eec83631.png)

**Actual results**
In estimated material, Cura say me that PrintCore 2 is activated and that it prints almost all of my job.

**Expected results**
PrintCore2 should be turned off and my job printed on PrintCore1.

**Project file**

**Log file**

**Additional information**
This is not the first time this kind of problem has happened. But until then I simply had to reactivate the PrintCore2 and deactivate it again. It was finally working. Now I have this problem that persists.

**Comment by nallath** [comment]
Could you check again with 4.8 beta? We recently fixed another issue that might influence this.

**Comment by Mikaledoux** [comment]
Thank you, I'll try, and I'll keep you posted.
________________________________
De : Jaime van Kessel <notifications@github.com>
Envoyé : lundi 26 octobre 2020 15:01
À : Ultimaker/Cura <Cura@noreply.github.com>
Cc : Michael Ledoux <michael@spentys.com>; Author <author@noreply.github.com>
Objet : Re: [Ultimaker/Cura] Fortis Profile Bugging Material Estimation (#8600)


Could you check again with 4.8 beta? We recently fixed another issue that might influence this.

**Comment by nallath** [comment]
Any update on this? Was the issue resolved in the beta?
