### ISSUE TITLE
Wizard engine

### ISSUE THREAD

**Issue by Gotgot59** [Ultimaker/Cura#861]
When we install Cura on the segond screen of the configuration wizard is asked to chose other machine information we can't see all the machine. 
It's needed to have a scroll down to can chose all the machine. 
Can you please make the change on the wizard ? Or just give me the link to the problem so i can resolv it myself.
Thanks for all you done for the community and have fun !

**Comment by Ghostkeeper** [comment]
Sounds like the hi-I'm-a-high-DPI-screen-but-not-really issue again. :disappointed:

**Comment by fieldOfView** [comment]
@Gotgot59: what version of Cura do you use?

**Comment by Ghostkeeper** [comment]
These have been fixed, as far as we know, in Cura 2.7 and 3.0.
