### ISSUE TITLE
path of files

### ISSUE THREAD

**Issue by RoRi3D** [Ultimaker/Cura#862]
Today I noticed that Cura 2.1.2 is not using, when saving the G-code,  as default the path of the STL opened. 
Can this be fixed?
Now you have to click many times before you can save.

**Comment by Ghostkeeper** [comment]
The expected behaviour is not that it should take the directory from where the STL was loaded, but that it should remember the directory you used last to save to.

**Comment by nallath** [comment]
Nope it doesn't. It used to be that way but I was told to change this. The behavior now is that it _always_ looks in the home directory.

**Comment by Ghostkeeper** [comment]
We have put this on the planning again to reinstate the remembering of save/load locations.

**Comment by nallath** [comment]
I think this has already been fixed.
