### ISSUE TITLE
[4.8 beta] Gapfill appears on the extra skin wall of expanded skin. 

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#8626]
**Application version**
4.8 beta

**Platform**
Windows 7, NVIDIA GeForce GT 730. (Using dual monitors).

**Printer**
Custom fff

**Reproduction steps**
1. See attached project. Fill gaps is active, Extra skin wall is on.
2. Turning off fill gaps removes the short tiny lines. 
    Surprisingly, setting infill density to 0 also removes them.

**Screenshot(s)**
![Gap fill at edge of skin expansion](https://user-images.githubusercontent.com/32172100/97287076-6f5ada80-1844-11eb-8adf-0fcb1401c33d.PNG)

**Actual results**
Gap-fill at edge of extra skin wall

**Expected results**
No gap-fill

**Project file**
[Gap fill at edge of skin expansion.zip](https://github.com/Ultimaker/Cura/files/5444447/Gap.fill.at.edge.of.skin.expansion.zip)

**Comment by jellespijker** [comment]
Devs see CURA-7804. Same problem as reported at the eCCB

**Comment by jellespijker** [comment]
Fixed for 4.8
Thank you for reporting it.

**Comment by Ghostkeeper** [comment]
4.9 and 4.10 had this bug again due to mistakes in merging, but for 4.11 it should be fixed again.
