### ISSUE TITLE
[4.8 beta] Freezes while syncing settings from on-line account

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#8634]
Trying to sync settings - total lock up.
![image](https://user-images.githubusercontent.com/11351506/97305371-601f6100-1833-11eb-85e8-fbccc522fb8d.png)

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

**Comment by Ghostkeeper** [comment]
Could be failing to connect somehow?
