### ISSUE TITLE
[4.7.1] Supports cannot interface properly on large slopes

### ISSUE THREAD

**Issue by NerfEspeon** [Ultimaker/Cura#8640]
[4.7.1]

**Platform**
Windows 10

**Printer**
Creality Ender 3 Pro (actually using an Ender 3 V2, but I doubt that matters

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![Screenshot 2020-10-27 172823](https://user-images.githubusercontent.com/73554030/97373064-a64be300-187a-11eb-8795-b247958ad352.png)
![Screenshot 2020-10-27 173146](https://user-images.githubusercontent.com/73554030/97373083-b4016880-187a-11eb-8ed8-f74accb9b7a0.png)
![Screenshot 2020-10-27 173359](https://user-images.githubusercontent.com/73554030/97373090-b82d8600-187a-11eb-8ecc-dbd0c1e70180.png)
It's trying to put support in midair!

**Expected results**
support should not be generating midair

**Project file**
Sadly, the models concerned are not mine to share. I bought them on Etsy, If you're wondering, it's GavinFuzzy's SPAMF kit for the Nerf Falconfire

**Additional information**
The affected area is rather high up on the print.

**Comment by Ghostkeeper** [comment]
You can reduce that distance by setting Support Distance Priority to Z overrides X/Y and reducing the Minimum Support X/Y Distance setting.
Those settings seem to be working as expected, from what I can see.
