### ISSUE TITLE
[4.8 beta] Activate button isn't disabled for active machine profile

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#8643]
**Application version**
4.8 beta

**Platform**
 Windows 7, NVIDIA GeForce GT 730. (Using dual monitors).

**Printer**
Custom FFF or Creality cr10

**Reproduction steps**
Activate a printer profile

**Screenshot(s)**
Machine profiles menu:
![Activate button](https://user-images.githubusercontent.com/32172100/97445115-334f7480-192d-11eb-836b-1d204090dd35.PNG)

The settings profile menu greys out the button:
![Activate button2](https://user-images.githubusercontent.com/32172100/97445260-5c700500-192d-11eb-91c3-f93610b5ccfa.PNG)

**Actual results**
Button stays active

**Expected results**
Button should be disabled for the active machine.

**Project file**
[button.zip](https://github.com/Ultimaker/Cura/files/5452333/button.zip)

**Comment by nallath** [comment]
Whoops. This has been blatantly wrong for over 4 years...

**Comment by fieldOfView** [comment]
... nervously checks git blame ...

Wasn't me!

**Comment by printingotb** [comment]
While I'm at it, I found some inconsistencies that may or may not be intended :wink:

Add machine - it activates but doesn't automatically get selected

Create settings profile from overrides - activates and selects profile
Duplicate profile - doesn't activate or select

Create material - activates and selects
Duplicate material - activates and selects

Active machine can be removed and the next machine in the list activates. (Until now at least).
Active settings profile can't be removed
Active material can't be removed

**Comment by nallath** [comment]
> Active machine can be removed and the next machine in the list activates. (Until now at least).
> Active settings profile can't be removed
> Active material can't be removed

This is intentional.

**Comment by Ghostkeeper** [comment]
The inconsistency is necessary because while it's pretty clear what happens when you delete the active printer, a material or custom quality profile may be active on any number of printers, even ones that are not active right now. So deleting your custom material would also need to change the material on different printers. You wouldn't notice that this happens.
