### ISSUE TITLE
[4.8 beta] No tree supports on external perimeters

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8644]
**Application version**
4.8 beta

**Platform**
Windows 10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Tree supports
2. Any overhang to support.

**Screenshot(s)**
![no tree supports externally](https://user-images.githubusercontent.com/20385116/97452182-c2ac5600-1934-11eb-8c16-f3251b0ee85b.png)

**Actual results**
Only tree supports inside

**Expected results**
Tree supports on the left overhang

**Project file**
[CCR10S_no tree supports externally.zip](https://github.com/Ultimaker/Cura/files/5452650/CCR10S_no.tree.supports.externally.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Indeed, this reproduces!

This is a more general case of the bug you reported earlier: https://github.com/Ultimaker/Cura/issues/8614

What happens is that a branch is started with a certain Z distance below the overhang. But if that starting point falls within the X/Y distance, it is immediately removed and no branch is created at all. Increasing the Z distance works around the issue, or reducing the X/Y distance. In your case, I'd reduce the X/Y distance.

I'll close this as a duplicate and add the information we found through this test case to the other ticket.
