### ISSUE TITLE
[4.8 beta] Tree supports not generated externally

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8645]
**Application version**
4.8 beta

**Platform**
Windows 10 x64

**Printer**
CR10S

**Reproduction steps**
1. Tree supports
2. Max overhang 25°

**Screenshot(s)**
![no tree supports externally](https://user-images.githubusercontent.com/20385116/97452418-03a46a80-1935-11eb-9d24-fd9a635f867f.png)

**Actual results**
Tree supports are not generated externally, only internally

**Expected results**
Tree supports should support left overhang

**Project file**
[CCR10S_no tree supports externally.zip](https://github.com/Ultimaker/Cura/files/5452655/CCR10S_no.tree.supports.externally.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
(See https://github.com/Ultimaker/Cura/issues/8614)
