### ISSUE TITLE
Extruder 2 does not print build plates when selected for Bibo 2 dual extruder printer

### ISSUE THREAD

**Issue by WoodridgeBill** [Ultimaker/Cura#8652]
**Application version**
Cura 4.7.1

**Platform**
Windows 10

**Printer**
Bibo 2

**Reproduction steps**
I have a print that works perfectly when I select extruder 1 for Build Plate Adhesion Extruder and Extruder 2 for actual print but when I change the Build Plate Extruder to extruder 2 the printer goes through the motions but does not print anything.
Steps:
1. Import STLs
2. Change extruder for STLs to Extruder 2
3. Change Build Plate Extruder to Extruder 2
4. Slice project and save as - g-code.

**Screenshot(s)**

**Actual results**
Printer goes through motions but does not print any material from Extruder 2 (if I use Extruder 1 it prints the Build Plate using Extruder 1 fine and the print using Extruder 2 fine)

**Expected results**
Printer should print material

**Project file**

**Log file**

**Additional information**

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this issue. When I try this, it clearly instructs the printer to extrude filament. Here is a snippet, with my annotations:

```
G1 F1200 X2.968 Y-3.819 E99.67032 ; <-- Still printing with first extruder.
G0 F3600 X3.534 Y-3.819
G1 F1200 X3.819 Y-3.534 E99.69043
G1 F1500 E93.19043
;MESH:cube.stl(1)
G0 F3600 X4.386 Y4.386
G0 X5.665 Y4.386
G0 X50 Y50
G1 F1200 E83.69043
G1 F600 Z1.3
G92 E0                             ; <-- Reset extruder position of first extruder to 0.
T1                                 ; <-- Switch to second extruder.
G92 E0                             ; <-- Reset extruder position of second extruder to 0.
M105
M109 S200
M104 T0 S190
G1 F1500 E-6.5
G0 F3600 X50 Y50 Z1.3
G0 X11.559 Y11.163
G0 X11.713 Y10.375
;TYPE:SKIRT
G1 F600 Z0.3
G1 F1500 E0                        ; <-- Unretract.
G1 F1200 X11.164 Y10.997 E0.04139  ; <-- Extrude 0.04mm of filament with second extruder.
G1 X10.558 Y11.563 E0.08276
G1 X9.9 Y12.068 E0.12414
G1 X9.197 Y12.507 E0.16549
```

Do you have a project file that reproduces your issue?

Are you sure it's not just the feeder slipping or something?
