### ISSUE TITLE
Cura 4.8Beta - SideBar GUI plugin installed but not working

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#8664]
**Application version**
4.8 Beta

**Platform**
Win10/64/NV

**Printer**
Custom 

**Reproduction steps**
installed 4.8 side by side to 4.7.0, expecting to have this good old sidebar which is installed to no avail.

**Screenshot(s)**
 
![ice_screenshot_20201030-171126](https://user-images.githubusercontent.com/30949968/97722646-86632c00-1ad3-11eb-9791-1bc15d55fe79.png)

**Actual results**
Expecting to have the sidebar working as i just can't work with 4.x default settings menu - i just can't stand having the layer slider on the right of this setting menu which makes absolutely no sense to me whatsoever.

**Expected results**
I sure hope  4.8 released version will support this plugin.

**Comment by nallath** [comment]
Please report this with the github of the sidebar plugin: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/

**Comment by fieldOfView** [comment]
A test version of SidebarGUIPlugin that is compatible with Cura 4.8 is avilable here:
https://community.ultimaker.com/topic/26014-sidebar-gui-for-cura-4/page/4/?tab=comments#comment-275194

For details, see https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues/17

The next version of SidebarGUIPlugin is awaiting review for release in the Marketplace
