### ISSUE TITLE
Infill Density

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8667]
**Application version**
4.7.1

**Platform**
Win64

I'm not sure if this is a bug or not, so let me ask you a question.
If I change the value of InfillDensity, the density does not change.

![無題1](https://user-images.githubusercontent.com/69872727/97768487-bb6c8e80-1b66-11eb-9dd4-22702f5a2d74.png)
![無題2](https://user-images.githubusercontent.com/69872727/97768492-bdcee880-1b66-11eb-848b-7ac0a85d4253.png)
Changing the InfillLineDistance will change the density.
It appears on the left side of the text box where you enter the value.
I don't understand the arrows and fx buttons either, as they seem to only return to the initial values.
Is it a specification that the value of InfillDensity(%) is not reflected even if it changes? Is it a bug?

**Comment by fieldOfView** [comment]
The `Infill Line Distance` is normally calculated from the `Infill Density` (and the `Line Width` and the 'Infill Pattern'). However, once you put a "literal" value in the Infill Line Distance, this overrides the calculated value. I think there is a literal value in the profile you selected.

**Comment by viper0078** [comment]
Thanks for the reply.
I've downloaded and used the profile for Snapmaker, which means it's customized.
I used the Default profile in PrinterSettings and was able to get the two parameters to work together.
Thank you.
