### ISSUE TITLE
Feature Request: Save/Load session as project-file

### ISSUE THREAD

**Issue by OctagonHex** [Ultimaker/Cura#868]
Hi,
I would like to have an option to save all the settings and the file name of 3D-file in a "project-like" file. So that, when I open that project again, my model, the orientation it is in, and all the print settings are restored.

This is useful, if you come back after some time and look at what you did when you printed this or that model, how this support setting/pattern/... worked better or not. It's simply not possible and/or practical to recover that from the GCode-files.

Thanks!

Edit:
As suggested over at: https://ultimaker.com/en/community/21724-feature-request-save-load-session-as-project-file?page=1&sort=#reply-150930
the settings seem to be saved at the end of GCode-file. Would it be possible to expand this approach to fully cover all settings (placement information, reference to original file name, etc...) and add an menu option "Restore session from GCode..."

**Comment by fieldOfView** [comment]
I do agree with the feature request, but more for placement and per-object-settings of multiple files.

**Comment by nallath** [comment]
3mf should be able to support this without a whole lot of problems.

**Comment by OctagonHex** [comment]
I tested 3MF-file format, but it doesn't work.

What I did:
- Open a model in Cura 2.1.2
- change layer thickness to e.g. 0.1234
- File-> save selection as file -> test.3MF
- Clear Build plate
- Reset settings to "Fast Print"
- Open the previously generated test.3MF
- layer thickness is _not_ restored to previous value.

**Comment by nallath** [comment]
Because i said; "Should" not "Can" ;)

**Comment by Ghostkeeper** [comment]
3MF is able to support it, but it's just not implemented in Cura yet :yum:

This one has been on the planning for a while now. Workspace saving (On Jira: CURA-1263).

**Comment by nickthetait** [comment]
Would like to add a +1, I have had several users request this functionality. As a extra bonus I think this would be a very helpful feature for debugging and testing purposes.

**Comment by Ghostkeeper** [comment]
Our overlords have put this up as feature for release 3.1. That'd take a while...

**Comment by nallath** [comment]
Still think we should do it at an earlier data.

**Comment by nallath** [comment]
This has already been implemented since now.
