### ISSUE TITLE
[4.8 beta] Connect Top/bottom polygons. Setting "top surface pattern"- or "bottom pattern inital layer" to concentric does not make the setting visible

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#8683]
**Application version**
4.8 beta

**Printer**
any

**Reproduction steps**
1. Set top/bottom pattern to lines
2. Set Bottom pattern initial layer and/or Top surface skin pattern to concentric

**Screenshot(s)**
![Connect polygons](https://user-images.githubusercontent.com/32172100/97998863-ecf58c00-1dea-11eb-863e-ef6f89f4dd83.PNG)
![Connect polygons2](https://user-images.githubusercontent.com/32172100/97998867-ee26b900-1dea-11eb-80d0-2d7a84bad8c2.PNG)

**Actual results**
Connect Top/bottom polygons setting is hidden
(However, it is still active and working)

**Expected results**
Setting should be visible

**Additional information**

**Comment by Ghostkeeper** [comment]
Yup, can confirm. It still works but it was hidden.

We can easily change the visibility condition there. I've fixed it in master (so 4.9).

You're on a roll recently. Thanks for all the bug reports!

**Comment by printingotb** [comment]
> You're on a roll recently. Thanks for all the bug reports! 

You are welcome! Thanks for an amazing software :smiley:
