### ISSUE TITLE
[4.7.1-1][Linux] Can't get past the "Welcome to Cura" screen

### ISSUE THREAD

**Issue by J2xWo** [Ultimaker/Cura#8688]
**Application version**
Cura 4.7.1-1

**Platform**
My full specifications can be found here: [pastebin](https://pastebin.com/UVfZzm7A)

**Reproduction steps**
1. Install Cura from the Manjaro repository
2. Start Cura
3. Can't get past the welcome screen since the buttons seem to be missing. Parts of white letters are visible above the word "Ultimaker". Also the text for the Marketplace and Sign in are misaligned.

**Screenshot(s)**
![2020-11-03_11-45](https://user-images.githubusercontent.com/22383957/98057892-af711d00-1e43-11eb-8de6-0f3eed9b593d.png)

**Expected results**
That buttons appear to progress in the set up of Cura.

**Log file**
[Cura.log](https://pastebin.com/cLgE9knq) (Sorry for some reason pastebin gives a warning)

**Additional information**
When using the AppImage of Cura everything is fine. The "Get started" button appears and works. The buttons for the marketplace and to sign in are also properly aligned.

**Comment by jellespijker** [comment]
For Linux we only support the AppImage.
What is probably happening is that your system wide Qt5 version is incompatible with Cura's version.
