### ISSUE TITLE
Feature Request: Load old settings

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#87]
It would be nice if people wouldn't have to reconfigure all the setting preferences they saved from the old Cura.

The new Cura should be able to read and 'translate' those files to the new settings.

**Comment by loelkes** [comment]
Same question: did i miss it or is there no way to load 'old' cura profiles.

**Comment by nallath** [comment]
There is no way to load old cura profiles at this moment.

**Comment by loelkes** [comment]
Is is possible to export profiles?

**Comment by nallath** [comment]
It's possible for the old cura, but the new one cant import them. This is because a lot of the naming in the old cura was really weird, so we had to break it.

**Comment by loelkes** [comment]
OK. I'll stay with the old Cura until the new one has at least an import/export feature since i have different computer at differentes places where i use the same profile.

**Comment by BagelOrb** [comment]
It is a difficult feature atm, since the values of hidden settings are now calculated from other settings values. Should loading a settings profile from the old cura mean that all included settings become visible? What about settings that are new in the new Cura (e.g. coasting, support towers, etc.), or settings which are replaced by totally different settings (e.g. retraction limitation settings)?

**Comment by loelkes** [comment]
The 'import from old cura' feature would be nice but if it's not possible... but if i manually set up my new profile in Cura i would like to be able to backup it and send it to other computers or friends.

**Comment by nallath** [comment]
The current values of the settings are saved in [machine_name].cfg and the location is pased on the operating system. For windows its in appdata/local/cura/settings, linux its ~/.local/share/cura/settings and mac is home/.cura/settings

**Comment by loelkes** [comment]
OK, thanks, works for me. Maybe a button for less advanced users in the next version could be nice.

**Comment by nallath** [comment]
Agreed. It's on the roadmap for next release.

**Comment by nickthetait** [comment]
This one got fixed some time ago correct?

**Comment by fieldOfView** [comment]
Yes, thanks
