### ISSUE TITLE
Keep Z-Axis Stepper Motor On, When aborting Prints

### ISSUE THREAD

**Issue by mojotaker** [Ultimaker/Cura#8708]
When Aborting Prints, on my ender 5 pro, the print bed falls down. 
This causes issues later :

- Such as when issuing home/auto home command, the z - axis upon init first spins the wrong way and causes a very loud grinding noise. This can damage the motor.

- I heard that the quick manual movements of these axises (z-axis in this case) can cause electrical damage.

A good solution to this issue, would be when the abort print button is hit, and the confirmation button is pressed, not only should an abort command be issued, but a command to either keep the build plate at the same level it already is, or let it drop a few millimeters down should be issued, or be part of the abort sequence.

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

Users of Ender 5 and its clones, or anyone where the bed moves on the z-axis

**Comment by nallath** [comment]
Please report this with the firmware developers of the team. Cura can't control what happens once an abort is triggered.
