### ISSUE TITLE
Disallowed Areas grow when you decrease the line width

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#8716]
**Application version**
at least Current master

**Platform**
At least linux

**Printer**
at least UM3

**Reproduction steps**
1. decrease line width

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/8895761/98522555-23ad2580-2275-11eb-9f02-fff74d0dda3d.png)

**Actual results**
Disallowed areas are increased in size

**Expected results**
disallowed areas stay approximately the same size or become smaller as well

**Comment by konskarm** [comment]
This is in now in our backlog. Devs see CURA-7835.
