### ISSUE TITLE
Print with Octoprint issue

### ISSUE THREAD

**Issue by Nickelindgren** [Ultimaker/Cura#8719]
**Application version**
4.7.1

**Platform**
Win10

**Printer**
Creality Ender 3 PRO

**Reproduction steps**
1. Sliced and sent to octoprint

**Actual results**
Sometimes my extruder starts feeding backwards right after completing the ABL and just when it's about to print the first line. 

**Expected results**
It should print without any issues

**Comment by rburema** [comment]
Can you attach the generated gcode, and the logs?

**Comment by dxgldotorg** [comment]
Does this occur when you save the gcode to SD card, or save to file then upload to OctoPrint via browser?

**Comment by Nickelindgren** [comment]
Now I'm not so sure this is an bug in the cura software. I discovered that I sometimes got the same issue when sending a gcode straight to octoprint and not through cura. I will close this issue since the problem seams to be elsewere.
