### ISSUE TITLE
Rotate by green ring doesn't output correct code

### ISSUE THREAD

**Issue by NigelWebbZUK** [Ultimaker/Cura#873]
Cura 2.1.2
When I open a STL file, click on it, select rotate, select green ring and drag to rotate by 180 (do not touch any other ring even slightly). The model rotates on the screen but if you produce gcode it is not rotated.

A similar problem can also be observed if after rotating by 180 deg by the green ring, if you select the object and click duplicate, the new object is 'as loaded', ie without rotation.

Nigel

**Comment by Ghostkeeper** [comment]
I couldn't reproduce this. I tried on 2.1.3 as well as on the current master version. The g-code is produced of the rotated model.

The problem with the duplicating is known to us though. It has been fixed for version 2.2.

**Comment by 3DAmsterdam** [comment]
I have seen this too, After reloading the objects it seem to work fine.

**Comment by nallath** [comment]
I can't reproduce this. Since then we also redid parts of code that handled this, so it's most likely fixed.
