### ISSUE TITLE
starting 4.8 encountering error with profile

### ISSUE THREAD

**Issue by g097103** [Ultimaker/Cura#8733]
![image](https://user-images.githubusercontent.com/74325858/98862534-1048b880-2435-11eb-915d-287147c6cb97.png)

This error does not occur in 4.6.1 using the same profiles. For obvious reasons, I do not allow it to delete existing profiles which work well in 4.6.1

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

Could you also provide your configuration folder?

**Comment by g097103** [comment]
I delete the m200 profile which was a monoprice mini, uninstalled 4.8 the reinstalled 4.8 and it seems to have resolved this issue.
