### ISSUE TITLE
Color for contact zone to platform

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#8735]
**Is your feature request related to a problem? Please describe.**
In the past, I asked that the area of the object under the bed be colored in a different color as it is used to cut objects. This has been implemented in version 4.8.
Along with this they said they adjusted the height where the bed is drawn.

The current problem is: If I place an object on the bed, I want to see all the parts that are in contact with it for cases where I don't want to cut objects.

THIS IS VERY IMPORTANT when we rotate objects and use automatic functionalities to deposit them on the bed ensuring that it is not slightly tilted resulting in layers in the air and a failed print.

https://github.com/Ultimaker/Cura/issues/8469

**Describe the solution you'd like**
Perhaps it would be good to have a darker blue or another color to indicate the parts of the objects that are in contact with the bed.
Do not confuse the red zone indicating overhang.
I leave you a riddle so you can see how confusing it can be. What parts touch the bed? 1,2,3?
![imagen](https://user-images.githubusercontent.com/11767960/98866055-18135780-244b-11eb-900b-d8e7fd45a0be.png)

Only 2 and 3. apparently...

![imagen](https://user-images.githubusercontent.com/11767960/98866389-9b34ad80-244b-11eb-9d29-5f1a8612a772.png)

**Comment by Ghostkeeper** [comment]
There is a colour for that. Can you guess which of these pillars is touching the build plate?

![image](https://user-images.githubusercontent.com/2448634/99423690-18a36680-2901-11eb-99e4-28151bd51837.png)

Only, maybe for your mug the actual contact area is so small that it doesn't show up? It could be infinitesimally small.

**Comment by Zogar89** [comment]
> Only, maybe for your mug the actual contact area is so small that it doesn't show up? It could be infinitesimally small.

That is the problem, when the area is small it does not color it. You can see it on the legs of the tyrannosaurus or on the base of the sphere.

You have previously told me that the contact plane was being drawn slightly above the real plane. In this version of cure 4.8 they have modified it. The problem is that it is so real that in spheres or other shapes, the contact area is infinitesimally small, causing no area to be painted. (In the sphere you can see that even an unpainted point of red appears, strange ...)

I think that the contact plane to paint light blue should move up a few tenths to generate larger blue areas or instead of being a plane, it should be a 3D area with small height.

![imagen](https://user-images.githubusercontent.com/11767960/99472844-359f6000-2928-11eb-8699-86e5aa9ab509.png)

![imagen](https://user-images.githubusercontent.com/11767960/99472879-48b23000-2928-11eb-823f-d197cbae0810.png)

![imagen](https://user-images.githubusercontent.com/11767960/99472941-654e6800-2928-11eb-81c1-599a77d2cc29.png)

![imagen](https://user-images.githubusercontent.com/11767960/99472979-77300b00-2928-11eb-81cb-764729aa7e7e.png)

**Comment by Zogar89** [comment]
For example, if you rotate the cube, the contact surface is so small that the blue part disappears.
![imagen](https://user-images.githubusercontent.com/11767960/99473780-0984de80-292a-11eb-887f-cf382427ff60.png)

[0h0m0g-Cube_Shape.zip](https://github.com/Ultimaker/Cura/files/5557285/0h0m0g-Cube_Shape.zip)

**Comment by Ghostkeeper** [comment]
Yeah, that's the problem then. The feature was intended to show which parts of the model are below the build plate, so it would just check for `Z < 0`. We extended that to `Z <= 0` to make it show also the parts on the build plate. But CuraEngine actually slices a bit above the build plate.

**Comment by fieldOfView** [comment]
How about "Z <= intial layer height"?

**Comment by rburema** [comment]
@fieldOfView That's the approach I went for, mostly (see the linked PR):
`init_layer_height = extruder.getProperty("layer_height_0", "value")`
I mean, besides adjusting it to half or a quarter of that, depending on slicing tolerance.
