### ISSUE TITLE
when i save a file it moves from its position

### ISSUE THREAD

**Issue by Croketaaa** [Ultimaker/Cura#8738]
So i downloaded a file from things-verse then when i open it in cura it loads perfectly so then i pass to save the file but when i put the SD card on my printer nothing happens so i decided to open the file and i found that the design moved from its place i remember leaving it , so then i tried loading the file and doing nothing but the same thing happens , every time i load a file it moves so i need help , Thank you.

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.
