### ISSUE TITLE
[4.8.0b] Tree support inconsistency

### ISSUE THREAD

**Issue by VicOnTheBeach** [Ultimaker/Cura#8739]
[Bishop.zip](https://github.com/Ultimaker/Cura/files/5530687/Bishop.zip)

**Application version**
4.8.0b

**Platform**
Windows 10 Familly x64

**Printer**
CREALITY CR10s Pro

**Reproduction steps**
0.Download Cura project here.
1. Set up tree support with overhang angle of 70 degrees then slice. The support reach some model's spots.
2. Lowering the overhang angle value to 60 degrees makes the support not reaching those spots. 

**Screenshot(s)**
See below

**Expected results**
Should be the opposite results

**Project file**
.3mf file attached here

Keep up the good work guys, Cura is the best slicer ever <3

**Comment by konskarm** [comment]
Hi @VicOnTheBeach. Could you please post your pictures here? The Facebook links don't work.

**Comment by VicOnTheBeach** [comment]
Hi Konstantinos,

Sure, here it is :)

Have a nice day
Le 12/11/2020 09:23:56, Konstantinos Karmas <notifications@github.com> a écrit :
Hi @VicOnTheBeach [https://github.com/VicOnTheBeach]. Could you please post your pictures here? The Facebook links don't work.

**Comment by konskarm** [comment]
Since they don't show up properly when they are sent via email, I am uploading them for visibility:

70 degrees:
![image](https://user-images.githubusercontent.com/19388042/98917517-c4495280-24cc-11eb-9b5c-a0e7c64df3ac.png)

60 degrees:
![image](https://user-images.githubusercontent.com/19388042/98917545-cdd2ba80-24cc-11eb-93a2-07b83afb1854.png)

**Comment by konskarm** [comment]
The file is also not available in the given thingiverse link. Could you create a Cura project file (File -> Save project...) and upload it?

**Comment by VicOnTheBeach** [comment]
[Bishop.zip](https://github.com/Ultimaker/Cura/files/5530692/Bishop.zip)

**Comment by Ghostkeeper** [comment]
I'm not getting the same results with that project file. Here is the bishop at 70 degrees overhang (reduced support):
![image](https://user-images.githubusercontent.com/2448634/99425731-85b7fb80-2903-11eb-9adb-166d6db516e4.png)

And here is the bishop at 60 degrees overhang (increased support):
![image](https://user-images.githubusercontent.com/2448634/99425997-e3e4de80-2903-11eb-956c-e2c5cedb6735.png)

It looks like the 60 degree overhang gets strictly more support than the 70 degree overhang.

Is this something that may have changed between the beta and stable? There were some changes to your printer's defaults in that time.

**Comment by VicOnTheBeach** [comment]
Hi,

You're right, I've installed the stable release and the issue does not occurs anymore. Thank you for your investigations anyway.

Kind regards,
Le 17/11/2020 18:38:55, Ghostkeeper <notifications@github.com> a écrit :
I'm not getting the same results with that project file. Here is the bishop at 70 degrees overhang (reduced support):
[image] [https://user-images.githubusercontent.com/2448634/99425731-85b7fb80-2903-11eb-9adb-166d6db516e4.png]
And here is the bishop at 60 degrees overhang (increased support):
[image] [https://user-images.githubusercontent.com/2448634/99425997-e3e4de80-2903-11eb-956c-e2c5cedb6735.png]
It looks like the 60 degree overhang gets strictly more support than the 70 degree overhang.
Is this something that may have changed between the beta and stable? There were some changes to your printer's defaults in that time.
