### ISSUE TITLE
Cura 2.12 scale bug

### ISSUE THREAD

**Issue by SEADEMON** [Ultimaker/Cura#874]
in old Cura 15.04 if you scale model write 0,03 on one axe and all axe scale to 0,03.
in new cura when you scale one axe all ok. 
X 3%
Y 3%
Z 3%
But if you rotate and than scale you have 
X 3%
Y 10.06%
Z 0.89%
If you scale and rotate and than try scale you have this bug to
![scale](https://cloud.githubusercontent.com/assets/13207539/16800978/c1b34988-4900-11e6-8932-d270e47a03dd.jpg)

**Comment by Ghostkeeper** [comment]
Duplicate of #769.
