### ISSUE TITLE
Profiles Disabled ("Not Supported") when changing Material Type

### ISSUE THREAD

**Issue by evilC** [Ultimaker/Cura#8744]
**Application version**
4.7.1

**Platform**
Windows

**Printer**
Ender 3

**Reproduction steps**
1. Change Material Type field from the name of one of the Generic materials to something else

**Screenshot(s)**
![](https://i.imgur.com/rvc4Gb1.gif)

**Actual results**
Profiles become "Not Supported"

**Expected results**
Profiles still supported

**Comment by nallath** [comment]
This is by design. See https://github.com/Ultimaker/Cura/issues/8229
