### ISSUE TITLE
Change part color in Prepare/Preview modes without affecting print settings.

### ISSUE THREAD

**Issue by AlexAnYuEn** [Ultimaker/Cura#8753]
**Is your feature request related to a problem? Please describe.**
We use mostly black PLA, however in Cura, Black PLA is barely visible or has no light/shadow features and is extremely hard to discern details. 

**Describe the solution you'd like**
Please add an option that allows us to change the colour of the part without affecting the print settings. Or am I missing something? I have not found any settings that allow me to do this, so maybe it's just a UI issue.

**Describe alternatives you've considered**
I have to change the material to Blue PLA for example just to preview my parts, then switch to Black PLA before I print. 

**Affected users and/or printers**
All Cura users that use Black PLA?

**Additional context**
![image](https://user-images.githubusercontent.com/74390651/99021237-34bea500-259b-11eb-9af3-cbe9cbd4be49.png)
![image](https://user-images.githubusercontent.com/74390651/99021267-44d68480-259b-11eb-9597-04bdc9aa9c80.png)

**Comment by nallath** [comment]
If you duplicate the material you can set the color to be lighter (click the color in the preference page and select a new one).
