### ISSUE TITLE
preenchimento

### ISSUE THREAD

**Issue by eddbull** [Ultimaker/Cura#8755]
as configuraçoes de velocidade de preenchimento e fluxo de preenchimento nao estao sendo exibidas no cura assim nao podendo edita-las, minha impressora é a Ender 3, tambem gostaria de pedir que melhorassem a velocidade de conexao com a impressora, eu notei uma coisa estranha na atualizaçao do cura, ele esta mostrando que vai demorar muito para impressao de um modelo simples mas talvez só seja algo da minha mente mesmo.

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

Also please fill in the template in English.
