### ISSUE TITLE
Add grams (g) amount used in print job history.

### ISSUE THREAD

**Issue by AlexAnYuEn** [Ultimaker/Cura#8756]
**Is your feature request related to a problem? Please describe.**
We try to use as much as our rolls as possible without leaving any waste. We manually insert the grams used per print in an excel sheet just to keep tabs our prints. However sometimes we forget and need to go back and check, or we just play a guessing game and eyeball it.

**Describe the solution you'd like**
Show how many grams are used per print in the Print Job History or some other feature that can tell us how many grams are left on our rolls. Maybe in the Print Job History there could be a little calculator that allows you to input your roll selection in grams (750g for example) and then you can either manually or automatically select the print jobs that were used on that roll.

**Describe alternatives you've considered**
Counting.

**Affected users and/or printers**
All Cura users?

**Additional context**
The grams used is shown here when you Slice, but never shown again anywhere else.
![image](https://user-images.githubusercontent.com/74390651/99021938-bb27b680-259c-11eb-84b9-b1461501dd90.png)
When viewing parts history, there's not a lot of info shown.
![2020-11-13 10_41_55 – Ultimaker Digital Factory](https://user-images.githubusercontent.com/74390651/99022206-3c7f4900-259d-11eb-9977-f0a2752dd77d.jpg)

**Comment by ChrisTerBeke** [comment]
This feature request seems to be for Ultimaker Digital Factory (formerly cloud & connect), not Cura. I'll make sure this request ends up at the product owner of Digital Factory and close it here.
