### ISSUE TITLE
Zichzack-Elemente Stützstruktur verbinden läßt sich nicht deaktivieren

### ISSUE THREAD

**Issue by Krasi50** [Ultimaker/Cura#8759]
Die Stützstruktur wird immer verbunden obwohl es deaktiviert ist. 
Cura 4.8.0
Windows 8.1 pro 
 64 bit
Ultimaker 3

![Cura3](https://user-images.githubusercontent.com/35507995/99045244-531fa300-2591-11eb-8cb6-62b228a7e911.jpg)

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

Please provide a bug report in English and provide a project file that exhibits the issue.

**Comment by Krasi50** [comment]
forget it - i will use simplify ...

 

Von: Jaime van Kessel <notifications@github.com> 
Gesendet: Freitag, 13. November 2020 10:33
An: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Krasi50 <p.krasnitzer@aon.at>; Author <author@noreply.github.com>
Betreff: Re: [Ultimaker/Cura] Zichzack-Elemente Stützstruktur verbinden läßt sich nicht deaktivieren (#8759)

 

It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

Please provide a bug report in English and provide a project file that exhibits the issue.

**Comment by nallath** [comment]
Okay. I'll close the issue then.
