### ISSUE TITLE
Fan speed not reset when printing "One at a time"

### ISSUE THREAD

**Issue by AndreasALu** [Ultimaker/Cura#8768]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
CraftBot Flow IDEX

**Reproduction steps**
I´m printing multiple objects "one at a time". In "Cooling", I set "Initial Fan speed" to 0% and "Regular Fan Speed at Layer" to 4. The first object prints fine. When ending the first object, the fan speed is at 100%, which is correct. Then when printing the first layer of the second object, the fan speed is not set to 0%, instead it stays with 100%. Result: the first layer of the second and all following objects does not stick well to the print bed.

**Actual results**
Fan speed at Initial Layer of second and following objects is not reset.

**Expected results**
Fan speed at Initial Layer *of every object* should start with 0% (or whatever is set up in the Print settings).

**Project file**
[Multiple Testcubes.zip](https://github.com/Ultimaker/Cura/files/5540466/Multiple.Testcubes.zip)

**Comment by soadergi** [comment]
I`m facing this issue in the 5.6.0 version
