### ISSUE TITLE
"Open Project" Dialog too small to show printer names

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#8773]
**Application version**
4.8

**Platform**
MacBook Pro/Mac OS 10.15.7 (no, I'm not ready to upgrade to 11.0 yet, until bugs are worked out in the OS)

**Printer**
N/A

**Reproduction steps**
1. Open a  saved project
2. Attempt to set printer profile to update

**Screenshot(s)**
![Open Project 2020-11-14 09-42-22](https://user-images.githubusercontent.com/57936294/99153815-bc6de780-265f-11eb-80a3-b18d0f58b515.jpg)

**Actual results**
Dropdown is too narrow to show some full printer names, so it's a guessing game as to which one to choose when similar printer names exist.

**Expected results**
Dropdown control should show full names, or at least create some tooltips when hovering over an option that will show full name.

**Project file**
N/A, happens in all projects

**Log file**
N/A

**Additional information**
N/A

**Comment by Ghostkeeper** [comment]
Thanks for the report! I've fixed it for 4.9.

**Comment by Ghostkeeper** [comment]
Until then, you can make the dialogue wider to display more text. This combobox scales with the total width of the dialogue.
