### ISSUE TITLE
Cura crashes on file opening

### ISSUE THREAD

**Issue by RBO85** [Ultimaker/Cura#8775]
**Application version**
4.7.1 & 4.8.0

**Platform**
MacOS Big Sur (11.0.1)

**Printer**
Creality Ender-3

**Reproduction steps**
1. Open file via Drag-Drop, via file menu or via export function on Fusion360 (all same result)

**Screenshot(s)**
![Schermafbeelding 2020-11-13 om 13 02 29](https://user-images.githubusercontent.com/29069381/99185731-07652900-274c-11eb-861d-7a4dad0cc4d0.png)

**Actual results**
App crashes instantly

**Expected results**
File should be opened

**Project file**
unable to create project file since app crashes instantly on opening file

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5542382/cura.log)

**Additional information**
N/A

**Comment by nallath** [comment]
What I can see from the logs is that something seems to be corrupted with your machine configuration. 

Could you try removing the machine and re-adding it? 

If that still doesn't resolve the problem, could you share your configuration folder?

**Comment by RBO85** [comment]
Hi Nallath,

Re-adding the printer did indeed solve the issue. Thanks a lot for your help.
