### ISSUE TITLE
CURA 4.8 temperature BUG and FlashForge Creator profile

### ISSUE THREAD

**Issue by moutig893** [Ultimaker/Cura#8782]
**Cura 4.8**
**WINDOWS10**
**FLASHFORGE CREATOR PRO**

**Actual results**
**1st problem** : 
Extruder temperature in cura: 240 ° C
Extruder real temperature in the 3D printer : 200°

**2nd problem :** 
With each update, obligation to reinstall the "custom" printing profiles for FlashForge Creator pro.

**3rd problem** : 
If I don't do the CURA update, the recorded files are 0Kb

**Additional information**
Is it possible for you to create a profile for the FlashForge Creator pro?

thank you!

**Comment by nallath** [comment]
Please create one issue per problem that you have and fill in the template for all of them individually. You can find the information about this on https://github.com/Ultimaker/Cura/wiki/Reporting-issues.
