### ISSUE TITLE
Can't exit onboarding

### ISSUE THREAD

**Issue by TheAlgorythm** [Ultimaker/Cura#8785]
**Application version**
Latest version in the Ach Linux Repository (cura 4.7.1-1).

**Platform**
Manjaro with an 4K monitor. X11 with KDE and 1.25x scaling (but tried without scaling).

**Reproduction steps**
1. Start Cura the first time

**Screenshot(s)**
![Cura_Startup](https://user-images.githubusercontent.com/36081522/99383571-5a66e980-28ce-11eb-9741-9d5ecde64109.png)

**Actual results**
There is no button to proceed or exit the onboarding.

**Expected results**
On macOS there is a button to proceed or exit the onboarding.

**Comment by fieldOfView** [comment]
There's a (known) incompatibility with the version of Qt on your system. That is why the AppImage includes versions that are known to be compatible for all of its dependencies. Use the AppImage.
