### ISSUE TITLE
Bad slicing object coming from Fusion360

### ISSUE THREAD

**Issue by Chrispizz** [Ultimaker/Cura#8792]
**Application version**
CURA 4.8.0

**Platform**
Windows 10 / Radeon R9 380 

**Printer**
ANET A6

**Reproduction steps**
Just slice the STL objet and slice it , then go to PREVIEW
[CUBE Fusion360.zip](https://github.com/Ultimaker/Cura/files/5559899/CUBE.Fusion360.zip)

**Screenshot(s)**
See attached screenshot 
![Slice bug CURA](https://user-images.githubusercontent.com/6710050/99528995-653d7f00-299f-11eb-8c73-5889d61e40f6.jpg)

**Actual results**
After slice step , the holes is filled by threads as it adds not existing thing inside.

**Expected results**
The holes should be empty , without matter inside ( see the difference between PREVIEW and PREPARE mode )

**Project file**
You will find the project in attachment too 
[CURA Project CUBE Fusion360.zip](https://github.com/Ultimaker/Cura/files/5559931/CURA.Project.CUBE.Fusion360.zip)

**Log file**
Log file is here 
[cura.log](https://github.com/Ultimaker/Cura/files/5559950/cura.log)

**Additional information**
No more to say about this , I hope you will find the solution ...

Many thank's 

Chrispizz

**Comment by nallath** [comment]
You have "Make Overhang Printable" enabled.

**Comment by Chrispizz** [comment]
Nallath , Many thanks for this 
I'm going to coorect and try
