### ISSUE TITLE
Cura 4.8 - Garbled machine "logos" when adding new machine - Apple Silicon aka Apple M1 ARM SoC

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#8795]
<img width="1392" alt="Screenshot 2020-11-17 at 22 16 37" src="https://user-images.githubusercontent.com/5671041/99598380-58497b80-29f1-11eb-8711-1839cc9a2895.png">

**Comment by nallath** [comment]
But we don't support ARM, so how did you get a build that runs on it?

**Comment by fieldOfView** [comment]
OSX uses "Rosetta 2" emulation of Intel instruction set on ARM.

**Comment by Ghostkeeper** [comment]
This seems to me like a bug in Qt, as it's very specific to one platform and our QML is [very simple](https://github.com/Ultimaker/Cura/blob/39acad87d916b32c98e852b9e14b6b76b0070852/resources/qml/WelcomePages/AddLocalPrinterScrollView.qml#L209-L217) over there. I couldn't find it on their bug tracker though. And I can't create a minimum reproducible case either without being able to reproduce it myself :(

**Comment by nallath** [comment]
So should we close this as an upstream issue?

**Comment by Ghostkeeper** [comment]
Well, I wonder why it's just this one label and not any others. Maybe it's not pixel-aligned?

**Comment by kr15uk** [comment]
> Well, I wonder why it's just this one label and not any others. Maybe it's not pixel-aligned?

Well now on v4.9 there are more of these...

<img width="892" alt="Screenshot 2021-04-27 at 16 34 42" src="https://user-images.githubusercontent.com/5671041/116270422-fac31300-a776-11eb-8eb8-6cf458a38b22.png">

Also this is different M1 machine so doubt it user/machine specific.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
