### ISSUE TITLE
Cura 4 8 Odd Pattern on print surface  This and other methods used to make sure it is flat, it 3D Prints flat:- Lay flat on the bed TinkerCad https://youtu.be/oSyJrLuiVOQ

### ISSUE THREAD

**Issue by ProtomakerSprint** [Ultimaker/Cura#8796]
Cura 4 8 Odd Pattern on the print surface
https://youtu.be/rm70XN_Gdnc

This and other methods used to make sure it is flat, it 3D Prints flat:-
Lay flat on the bed TinkerCad
https://youtu.be/oSyJrLuiVOQ

**Comment by nallath** [comment]
I think that the bottom of the model isn't flat. It's drawing some parts in blue because they are below the buildplate. 

If you can share the model, we can check if this is really the case.
