### ISSUE TITLE
Paint on Supports

### ISSUE THREAD

**Issue by TAZMANUK2020** [Ultimaker/Cura#8798]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see paint on supports like pursa slicer has it makes very easy work of placing supports, or a better way of putting on supports

**Describe alternatives you've considered**
using pursa slicer for all models that require supports

**Affected users and/or printers**
as pura slicer has this more people will move to use the other slicer

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by nallath** [comment]
Duplicate of #5955
