### ISSUE TITLE
I can't monitor my ANET A6 with USB connection

### ISSUE THREAD

**Issue by Chrispizz** [Ultimaker/Cura#8819]
**Application version**
CURA 4.8.0

**Platform**
WINDOWS 10

**Printer**
ANET A6

**Reproduction steps**
Connect ANET A6 from USB 
Nothing appears on MONITOR tab

**Screenshot(s)**
Nothing to show , just MONITOR tab empty 
![ANET A6 USB COM5](https://user-images.githubusercontent.com/6710050/99914370-46bbe880-2cfd-11eb-9279-99a7d3510f85.jpg)

**Actual results**
Nothing happens , just MONITOR tab empty 

**Expected results**
My ANET A6 is connected to USB ( COM5 ) then MONITOR tab should let me monitor the ANET A6 with controls buttons on the screen 

**Project file**
No project to show 

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5580075/cura.log)

**Additional information**
I hope you will tell me how I can do it work

**Comment by nallath** [comment]
You didn't give Cura permission to actually read data over the USB port.

It's stating that an "Accès refusé." exception happend.

**Comment by Chrispizz** [comment]
I've just added the diver CH340G for windows 10
I see more good logs for still not works , MONITOR tab is still empty without control buttons

[cura.log](https://github.com/Ultimaker/Cura/files/5582630/cura.log)

**Comment by nallath** [comment]
You still have the same error; Cura doesn't get the permission to read the serial.
