### ISSUE TITLE
Launching cura interrupts running print

### ISSUE THREAD

**Issue by marcvandort** [Ultimaker/Cura#882]
I am using cura 2.1.2. I was running a print on my Ultimaker 2,  with my laptop connected to the printer via usb, but not turned on. The print (approx 16h total :(  )  was almost finished, so I turned on my laptop to slice my next print. When I launched cura 2.1.2 it automatically connected to the printer, rebooting it.

**Comment by fieldOfView** [comment]
I'm sorry about your print! 
I am closing this issue, not because we don't care about it, but because it is a known issue:
https://github.com/Ultimaker/Cura/issues/856

**Comment by marcvandort** [comment]
Ah, I had searched but apparently using the wrong terms.
