### ISSUE TITLE
Splitting stl's disjunctive parts to independent entities

### ISSUE THREAD

**Issue by yagarea** [Ultimaker/Cura#8827]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I download stl file containing two disjunctive parts and there is now way to remove one and print only one of them. 

**Describe the solution you'd like**
There should be an option to split disjunctive mashes in to independent entities, which can be scaled, rotated, moved and removed independently on each other.

**Describe alternatives you've considered**
Add boolean set minus block (Do not print everything in this box; similar to no support box)

**Affected users and/or printers**
From this feature will benefit every lame user like me.

**Additional context**
Example: I want only one of these:
![cura-feature](https://user-images.githubusercontent.com/14349169/100164597-795e1080-2eb8-11eb-8fa9-c2aa752ea2ca.png)

**Comment by nallath** [comment]
There is a plugin that enables this: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
