### ISSUE TITLE
Reading STL from Smoothie-3d into Cura v4.8

### ISSUE THREAD

**Issue by JJRacoon** [Ultimaker/Cura#8828]
When opening an STL file created in Smoothie-3d in Cura Ver 4.8 all that is processed is a 2d image of the footprint on the buildplate.  Works in v4,7

**Application version**
4.8

**Platform**
Windows 10

**Printer**
CR10s

**Reproduction steps**
1. Opened file in Cura v4.7 -success - 3d
2. Opened file in Cura 4.8 - failure - 2d

**Screenshot(s)**
Version 4.7:
![On Cura v4 7](https://user-images.githubusercontent.com/47133589/100165148-2025bb00-2e7f-11eb-8b95-f82fa0cc015e.png)

Version 4.8:
![On v4 8](https://user-images.githubusercontent.com/47133589/100165174-3469b800-2e7f-11eb-95b7-128b4dd635e3.png)

**Actual results**
See screenshot "On v4.8" above

**Expected results**
See screenshot "On v4.7" above

**Project file**
[Pot from Smoothie3d.zip](https://github.com/Ultimaker/Cura/files/5593474/Pot.from.Smoothie3d.zip)

**Comment by nallath** [comment]
This is a known issue; It doesn't seem to correctly drop the model to the buildplate. It's placing the object very high above the build plate. 

You can either rotate the camera to look up, or select the model from the object list and then set the z to be zero.

**Comment by JJRacoon** [comment]
Thanks nallath

**Comment by Ghostkeeper** [comment]
(See https://github.com/Ultimaker/Cura/issues/8752.)
