### ISSUE TITLE
Startup Changelog dialog issues

### ISSUE THREAD

**Issue by juj** [Ultimaker/Cura#883]
After installing Cura 2.1.2 64 bit and starting up, there's some (minor) issues that I notice with the Changelog dialog that greets the user:

![startup_screen](https://cloud.githubusercontent.com/assets/225351/17078287/4a97dac2-50f7-11e6-84bb-8934928248c2.png)

a) The Close button overlaps with the horizontal scrollbar. This might have something to do with high DPI displays, I'm running on a 4K monitor with Windows display scaling set to 150%

b) The dialog is very small, tiny really, but there is a lot of text in it. Why not make the dialog, say, 4x bigger?

c) For some reason, scrolling the dialog is very slow and sluggish. After scrolling the mouse wheel, it takes about a second for the dialog to actually scroll.

**Comment by fieldOfView** [comment]
AFAIK, we're working on fixing this in Cura 2.2. 
Are you running Cura on a desktop or a laptop? Is the 4K monitor your only connected display?

**Comment by juj** [comment]
The part c) ended up being #884, and no longer occurring after rebooting. I'm running on a Windows 10 with Intel 5960X and 2xSLI GTX980Ti. The 4K monitor is the only connected display. Also, I now notice that b) was not so much of an issue, since the dialog is after all resizable, which I didn't notice at first due to the lagginess trouble I had with c).

**Comment by nallath** [comment]
This should already be fixed.
