### ISSUE TITLE
[4.7.1] Glitched lines visible in gcode preview

### ISSUE THREAD

**Issue by knoellle** [Ultimaker/Cura#8838]
**Application version**
4.7.1

**Platform**
Arch Linux (5.9.10-arch1-1)

**Printer**
Creality Ender 3

**Reproduction steps**
1. Loaded Model L-A and L-B from [here](https://www.thingiverse.com/thing:3033662/files) simulaneously
2. Slice (I'm using the Default Ender 3 on Standard quality. Only changed print sequence to `One at a Time`)
3. Go to preview and scroll through the layers.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/33729490/100390140-aed93a00-302f-11eb-8abe-6666409d3f64.png)
Object placement doesn't matter:
![image](https://user-images.githubusercontent.com/33729490/100390870-1bedcf00-3032-11eb-865c-bea17f5c5a03.png)
Nor does orientation
![image](https://user-images.githubusercontent.com/33729490/100390890-26a86400-3032-11eb-8289-f9830ee05aa6.png)

**Actual results**
Somewhere around the last ten or so layers, there are a bunch of lines going to the 0,0,0 point. It's not always on the same layer, but I have restarted cura a few times now and was able to reproduce this every time, although the line pattern is always different.
The lines only appear from one of the objects to the coordinate origin, but it's not necessarily the the object currently being printed in the viewed layer.

**Expected results**
There shouldn't be weird lines

**Project file**
Zipped, as github doesn't like .3mf
[project.zip](https://github.com/Ultimaker/Cura/files/5604962/project.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5604949/cura.log)

**Additional information**
This doesn't seem to affect the generated gcode file, loading it in gcode viewers doesn't show the lines.

**Comment by Kveri** [comment]
I have the same issue. I'm printing Hero Me Gen 5 parts and using the following settings:
Low Quality (0.28mm layer height) default Cura profile with these overrides: wall line count = 3, bed temp = 115, combing mode = infill, support = yes, support placement = buildplate, adhesion = brim, print sequence = one at a time

First there is this at layer 170:
![image](https://user-images.githubusercontent.com/3380181/100516496-a5151b00-3184-11eb-8b68-343af0d37f7d.png)

But when I go to layer 171 it changes to this:
![image](https://user-images.githubusercontent.com/3380181/100516506-b2caa080-3184-11eb-80b6-19507fdfaf5e.png)

And then all subsequent layers display properly. But when I go back from layer 171 to layer 170 this happens:
![image](https://user-images.githubusercontent.com/3380181/100516516-c6760700-3184-11eb-9dd8-27a3da883624.png)

Then going back to layer 169 everything is normal again. I restarted Cura, reload file, remove all objects and re-inserted them. I can replicate it consistently.

When I disabled combing it changed to this (still errors):
![image](https://user-images.githubusercontent.com/3380181/100516549-fae9c300-3184-11eb-87c6-b49f1432076d.png)

Here are: cura profile, all 4 STLs, 3mf and also gcode.
[cura-issue-8838.zip](https://github.com/Ultimaker/Cura/files/5610651/cura-issue-8838.zip)

**Comment by Ghostkeeper** [comment]
Indeed this reproduces. This seems to have something to do with it creating way too many layers for that second object which are all empty.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
