### ISSUE TITLE
Gyroid infill sudden direction changes

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8846]
**Application version**
4.8.0

**Platform**
Windows 10 x64

**Printer**
CR10S

**Reproduction steps**
1. Gyroid infill

**Screenshot(s)**
![gyroid 1](https://user-images.githubusercontent.com/20385116/100490287-9eea5480-311a-11eb-9636-0001acbdfc0d.png)
![gyroid 2](https://user-images.githubusercontent.com/20385116/100490284-9db92780-311a-11eb-93da-ab68c6c4a5c0.png)

**Actual results**
Gyroid infill suddenly changes direction by 90° from a layer to the other, so the layers split as the bond is very weak, and the infill bridges

**Expected results**
Smoother gyroid transition between layers

**Project file**
[CCR10S_gyroid direction.zip](https://github.com/Ultimaker/Cura/files/5609876/CCR10S_gyroid.direction.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Honestly it looks accurate to me. You have a fairly high infill density of 30%, so the pattern is small. And a pretty big layer thickness of 0.28mm. At this infill density, the pattern oscillates in a space of about 3mm, which is 10-11 layers at your layer height. It's going to have to make quite big steps at every layer.

And the steps aren't very big in reality. It's bridging gaps of about 0.5mm.

Reducing the layer height shows a much smaller switching point:
![gyroid_switch](https://user-images.githubusercontent.com/2448634/100731647-f06d3a80-33cb-11eb-869d-3819dd609c8d.gif)

**Comment by Ghostkeeper** [comment]
I think the Gyroid pattern may just not be the right choice at great infill densities. You're not going to get a whole lot of flexibility out of the pattern then.
