### ISSUE TITLE
Mirrored Text

### ISSUE THREAD

**Issue by Bobbyjab** [Ultimaker/Cura#885]
I have a part which is to be a mould, it has text that is mirrored. The imported STL created in TinkeCAD and which views correct in 3D Builder and also looks correct when opened in Cura. When the G-Code is created and printed, the text is NOT mirrored.
Just used a G-Code viewer and it looks correct.
Machine is Tevo tarantula i3

**Comment by thopiekar** [comment]
Well, if even your G-Code reader shows that the code is correct, then it looks like there is something wrong with your printer?

**Comment by Bobbyjab** [comment]
Thanks,

                I figured out that I had mounted my Y axis motor on the wrong side. I swapped it over and all is good now.

 

Greg
