### ISSUE TITLE
Small typo in Settings Guide

### ISSUE THREAD

**Issue by ahernsean** [Ultimaker/Cura#8858]
**Application version**
4.8.0

**Reproduction steps**
1. Open Settings Guide for "Wipe Nozzle Between Layers".
2. Look at last paragraph

The word "debris" is misspelled as "debree".

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1649300/100562682-68cbe280-328a-11eb-84ec-8650758beac7.png)

**Comment by jellespijker** [comment]
Thank you for your report. The settings guide is an external plugin, can you therefor create an issue in @Ghostkeeper repository of the settings guide https://github.com/Ghostkeeper/SettingsGuide

**Comment by ahernsean** [comment]
Oops, yes. Of course. Sorry.

**Comment by Ghostkeeper** [comment]
I've made this mistake more often... Looking at you, Minecraft!
