### ISSUE TITLE
new auto arrange when loading parts

### ISSUE THREAD

**Issue by dsudweeks56** [Ultimaker/Cura#8862]
when opening multiple part files or added part files to partially
 loaded plate it places them on top of each other and over lapping.
![Capture](https://user-images.githubusercontent.com/55361829/100682299-02e76580-3333-11eb-95c7-06a511da6971.PNG)

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.
