### ISSUE TITLE
Option to conditionally connect distant raft elements

### ISSUE THREAD

**Issue by MarcinOrlowski** [Ultimaker/Cura#8876]
I sometimes print projects that require raft. But in some cases raft alone is not enough and I'd like to add additional hooks by connecting separated rafts together. For example, this project: https://www.thingiverse.com/thing:571949 works better for me when I use raft. 

But slicing it with rafts enabled produces this (raft margin 6 mm):

![cura1](https://user-images.githubusercontent.com/8041294/100929572-24d61900-34e8-11eb-9f63-ee680a6971c3.png)

So I have two 2 alone "islands". I could increase raft margin, so it overlaps but IMHO that unnecessary wastes the filament and increased print time as other areas do not really need bigger raft really. This is with raft width doubled to 12 mm:

![cura2](https://user-images.githubusercontent.com/8041294/100929792-72528600-34e8-11eb-8670-77c8bd597e9d.png)

As we can see, the still last leg's raft is not connected with others. This is a problem for me because sometimes (and whole print of this model takes hours) the last left got loose mid-print and the everything gets ruined.

To work that around I created small 0.4x0.4 mm rod and keep it as separate SLT. I then add it to problematic projects, place it as needed (in this case between rear last legs):

![cura3](https://user-images.githubusercontent.com/8041294/100930153-f7d63600-34e8-11eb-9449-c97345b73765.png)

I then group with main model and slice. This makes Cura produce a raft for that rod too, which in my case gives connected raft as I desired:

![cura4](https://user-images.githubusercontent.com/8041294/100930310-323fd300-34e9-11eb-81bc-0caddaec1732.png)

I believe I am not the only one having such problems and it would be good to have the option to solve the "raft problem" without the rod STL. For now I think that the sufficient solution would be this: if (new) "Connect raft elements" option is enabled then it should create connection (of user defined too, width) to any other raft elements that is in given radius (additionally it could also have user defined limit so connection is made up to X elements, not to everything aroud) That would make such raft better fixed in place for good and solve the problem.

What you think?

**Comment by konskarm** [comment]
Hi @MarcinOrlowski. We discussed this feature request today with the team and, although we see the value in it, we know that it won't get prioritized sometime soon and it will get lost in our already long backlog. Therefore we decided to defer it. The workaround you used with the thin model is the one I would personally suggest too for models like the one you posted.

**Comment by MarcinOrlowski** [comment]
Thanks for considering the request. Quick question (I absolutely know nothing about Cura plugins, APIs and internals). Would that be doable by a plugin? I mean is plugin able to "pre-slice" to see in case raft is used and then alter geometry?

**Comment by Ghostkeeper** [comment]
No, the slicing process is done in CuraEngine. CuraEngine has no plug-in structure (yet). Cura's plug-ins are only for the front-end.

What you could do from a plug-in is add a strip to the build plate similar to what your workaround is right now. That strip then gets sliced along with CuraEngine. That is very similar to what for instance the Support Blocker tool does (which is implemented as a plug-in too) or the Custom Support plug-in that you can find on the Marketplace.
