### ISSUE TITLE
There is no retraction

### ISSUE THREAD

**Issue by viper0078** [Ultimaker/Cura#8887]
I checked the GCODE because the filament is badly threaded and there is no retraction code.

![無題12](https://user-images.githubusercontent.com/69872727/101233028-f5e2c180-36f8-11eb-8773-1964c028e697.png)
![無題11](https://user-images.githubusercontent.com/69872727/101233037-085cfb00-36f9-11eb-9a2f-eb66993b972b.png)

[CFFFP_test.zip](https://github.com/Ultimaker/Cura/files/5646455/CFFFP_test.zip)

Is this a bug?

**Comment by eskeyaar** [comment]
you can increase the  maximum retraction count to 10 and see ? That should make retract for you.

**Comment by viper0078** [comment]
Thanks for the reply.

I see that the retraction was suppressed by the combination of MuxmumRetractionCount and MinimumExtrusionDistanceWindow.
I had two retractions at a distance of 1-2 mm with the extruder and I had to adjust the value because I had cut the filament, but I didn't think it would have such a negative effect.
I have the impression that Cura can make advanced settings, but it is difficult to print consistently.
