### ISSUE TITLE
cura 4.8.0 crash when loading .3mf file with metadata element

### ISSUE THREAD

**Issue by kcris** [Ultimaker/Cura#8891]
Attached below the same 3mf file, exported twice
* without cura metadata (mini_bridge.3mf)
* with cura metadata (mini_bridge.cura.3mf)

The only difference between these two 3mf files is the following section
```
<metadatagroup>
	<metadata name="cura:extruder_nr" type="string" preserve="1">1</metadata>
	<metadata name="cura:infill_mesh" type="string" preserve="1">True</metadata>
</metadatagroup>
```
The 3mf file without cura metadata (without section above) is loaded in cura 4.8.0.
Loading the second file (which contains the section above) results in a cura crash. 

[cura-crash.zip](https://github.com/Ultimaker/Cura/files/5649415/cura-crash.zip)

**Comment by nallath** [comment]
I can't reproduce this. Could you also share your configuration folder? It might be that the active machine causes this issue.

**Comment by kcris** [comment]
sure, here it's the contents of my `AppData\Roaming\cura\4.8` folder, zipped
[cura4.8-configfolder.zip](https://github.com/Ultimaker/Cura/files/5653392/cura4.8-configfolder.zip)

**Comment by nallath** [comment]
I've found (and fixed the issue). 

As a work around: Add an extra extruder to your custom ff printer. The file that you had referenced an extruder that was not available.

**Comment by kcris** [comment]
Thanks, this helps a lot! 
I will make sure to check and use the appropriate extruder!
