### ISSUE TITLE
[4.8.0] Crazy Travels Mid-Print

### ISSUE THREAD

**Issue by yngndrw** [Ultimaker/Cura#8896]
**Application version**
4.8.0

**Platform**
Windows 10 / Nvidia GTX 1080

**Printer**
Custom (E3D Toolchanger)

**Reproduction steps**
Sliced these two parts with my normal profile, see attached

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1834655/101381296-7f87c000-38ae-11eb-88df-38a8c878b82f.png)

**Actual results**
During layer #18, while printing the right-hand part it keeps jumping back to the left part multiple times

**Expected results**
It should print the layer for one part, then move onto the second part

**Project file**
[CFFFP_Caddx Vista Mount.zip](https://github.com/Ultimaker/Cura/files/5654093/CFFFP_Caddx.Vista.Mount.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
I've never seen this behaviour within Cura, but since upgrading I've noticed this issue. I haven't tried any other prints.

I did also notice some a strange result when printing the flat surface of the left-hand part (layer #4) - The finish is horrible with lots of blobs all over the surface, however the flat surface of the right-hand part (layer #20) came out perfectly.

**Comment by Ghostkeeper** [comment]
I believe this was a bug with reading uninitialised memory that has been fixed for Cura 4.9. This is how it looks in the current Master branch:

![image](https://user-images.githubusercontent.com/2448634/101619392-81b75f00-3a13-11eb-9421-71ad6ac1250c.png)
