### ISSUE TITLE
Latest Cura Release does not work on ubuntu 16.04.01 LTSs

### ISSUE THREAD

**Issue by mgiaco** [Ultimaker/Cura#890]
Try to start cura the normal way happens in nothing. So i tried to start curo on a terminal and then I get.

So anything is missing - but what?

```shell
cura
/usr/bin/cura: line 3: python3.4: command not found
```

**Comment by fieldOfView** [comment]
Unfortunately Canonical switched to Python 3.5 and removed Python 3.4 from Ubuntu 16.04. This is being fixed for Cura 2.2.

In the meantime, you can use @thopiekar's awesome PPA, which works around the issue:
https://launchpad.net/~thopiekar/+archive/ubuntu/cura
Note that the PPA comes with no official support from Ultimaker. But he, it works!
