### ISSUE TITLE
Incorrect thickness of part from imported image in Cura 4.8.0

### ISSUE THREAD

**Issue by bellzw** [Ultimaker/Cura#8902]
**Application version**
Cura 4.8.0

**Platform**
Windows 10 64 bit running on a Lenovo Yoga 14
**Printer**
BIBO2 Dual

**Reproduction steps**
1. Drag grey-scale (0 - 255 pixel values) png file into work area (see attached file)
2. Set Height to 5.2, Base to 0.8, Width to 120.0, Depth to 120.0, Darker is higher, Linear color model, no smoothing (see attached screen capture), initial layer height 0.3 mm, layer height 0.1 mm.
3. Clear the work area, and import the image again with base at 0.6 mm or anything you like.  I've done this with 0, 0.2, 0.4, 0.6 and 0.8.  Cura 4.8.0 will think the thickness of the object should be 5.2 + 2*base mm.

**Screenshot(s)**
![convert image](https://user-images.githubusercontent.com/51066449/101427505-0481d200-38cd-11eb-9e7f-613aa766514d.png) - capture of the convert image screen
![converted image](https://user-images.githubusercontent.com/51066449/101427637-427ef600-38cd-11eb-80d8-8753bf02060d.png) - screen shot of converted png.  Note the dimensions at lower left 120x120x6.8 and number of slices at the right 66.
![Vulpes grey4x4](https://user-images.githubusercontent.com/51066449/101427735-6d694a00-38cd-11eb-9769-0ea94b8269bf.png) - image that was imported

**Actual results**
Cura shows the imported image and shows the thickness to be 6.8 mm and 66 slices (0.3 mm first layer, 65 0.1 mm additional layers), whereas it should be 6.0 mm and 58 layers (0.3 +57 layers of 0.1 mm) since Base + Height = 6.0.  The last layer of base is at layer 6  (0.3 + 5 layers of 0.1 mm), which is correct for 0.8 mm as specified.  This can be seen by scanning through the layers starting at layer 1. If other values of height and base are used, Cura 4.8.0 thinks the thickness of the object should be height + 2*base mm  The factor of 2 applied to the base thickness does not depend on the height or base specified by the user.  Cura 4.8.0 has the number of layers for the base correct, so it must be that the converted maximum height is actually height as specified by the user + base.

**Expected results**
The thickness should be than user specified height + base.

**Project file**
[Vulpes grey.zip](https://github.com/Ultimaker/Cura/files/5656341/Vulpes.grey.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
I have not tried this with other printers.  The objective here is to make lithophanes.

**Comment by Ghostkeeper** [comment]
Yup, you're right. Quite an obvious mistake and not so hard to fix. It's fixed in 4.9.
