### ISSUE TITLE
[4.8.0] Convert image (open image file) screen does not allow leading non-numeric keys

### ISSUE THREAD

**Issue by bellzw** [Ultimaker/Cura#8906]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Windows 10 64-bit running on Lenovo Yoga 14 laptop

**Printer**
BIBO Dual

**Reproduction steps**
1. Open an image file (jpg, png, etc.)
2. Set base (or any other field) to .8 mm (omit the 0 before the decimal point)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
The decimal point is not put in the field; you see only the 8 (or any other digit you typed)

**Expected results**
0.8 or .8

**Project file**
not applicable

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
The text boxes correctly reject alphabetic and punctuation characters other than comma and period, however those two characters are not accepted as the leading character.

**Comment by rburema** [comment]
Thanks for reporting this. It was such an easy fix that I took the liberty of directly pushing it to the main branch. Should be in for next version.
