### ISSUE TITLE
Monitor tab doesn't show current progress nor items in queue

### ISSUE THREAD

**Issue by chriskewl** [Ultimaker/Cura#8913]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Ultimaker 3

**Reproduction steps**
1. Print something, watch in Monitor tab.
2. Once done, print something else, watch in Monitor tab.
3. Notice the item still shows the original item printed in the Monitor tab with no update on progress.
4. You can still see correct status if you "Manage in browser".

**Screenshot(s)**
Cura Monitor tab: https://cdn.discordapp.com/attachments/316634826407149569/786163615245926420/unknown.png
Browser Connect: https://cdn.discordapp.com/attachments/316634826407149569/786163636980678656/unknown.png

**Actual results**
Notice the item still shows the original item printed with no update on progress. It also doesn't show anything in the queue.

**Expected results**
Should show the progress of the currently printed object with any items in the queue.

**Comment by Ghostkeeper** [comment]
It would be good to have separate issues for different bugs.

I'm not able to reproduce this issue. I can see different items in the queue fine:

![image](https://user-images.githubusercontent.com/2448634/102604728-e44fdf80-4124-11eb-841d-0707a2ffe4aa.png)

Maybe the firmware version on the printer is outdated? What version are you using?
It kind of sounds like Cura has just lost connection to the printer.

**Comment by chriskewl** [comment]
I uninstalled Cura and reinstalled it. Still no change. Also Cura is sending items to the printer just fine. Firmware is at latest version.

**Comment by Ghostkeeper** [comment]
I still haven't seen this issue, though I use my printer pretty much every workday.

Perhaps other people have seen it too. Then we can find the commonalities between your set-ups. Maybe it's something network-related? Or maybe the API on the printer is not functioning reliably?

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by chriskewl** [comment]
> Is this still an issue in current Cura versions (5.8.0 and up)? Can this be closed?

You can close it for now, we'll see if this comes back.
