### ISSUE TITLE
Tooltips for buttons on left panel

### ISSUE THREAD

**Issue by leoheck** [Ultimaker/Cura#8914]
Is it possible to have tooltips on buttons in the left panel? I don't know what are these 4 from the bottom up.
Actually, can you add tooltips everywhere?

**Comment by fieldOfView** [comment]
Tooltips were fixed here: https://github.com/Ultimaker/Cura/pull/8731
The fix will be part of Cura 4.9

**Comment by leoheck** [comment]
Yay, awesome.
