### ISSUE TITLE
[4.8] Manual support plugin causes cura model absolute positioning errors

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8919]
**Application version**
4.8

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Use tree support
2. Place manual supports with plugin
3. A manual support didn't touch the object (a plugin bug?)
4. Change the manual support dimension.

**Screenshot(s)**
![tree support with manual support absolute positioning](https://user-images.githubusercontent.com/20385116/101697171-9b8a8d80-3a77-11eb-8b2e-5ba07732e36f.png)

**Actual results**
The eventual bug with the plugin caused an eventual bug with the cura positioning coordinates.
When I enlarged the support on the Z, the model to print went high from the plane, but the Z coordinate on cura didn't update accordingly.

**Expected results**
Z coordinates should account edge case support behaviours.

**Project file**
[CCR10S_manual support with tree support changes positioning.zip](https://github.com/Ultimaker/Cura/files/5669152/CCR10S_manual.support.with.tree.support.changes.positioning.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
If the error/bug/issue is within the plugin, you might want to notify the author of the plugin instead.

Info about that plugin, including the authors' email, can be found here: https://marketplace.ultimaker.com/app/cura/plugins/lokster/CustomSupports

**Comment by Liger0** [comment]
> 
> 
> If the error/bug/issue is within the plugin, you might want to notify the author of the plugin instead.
> 
> Info about that plugin, including the authors' email, can be found here: https://marketplace.ultimaker.com/app/cura/plugins/lokster/CustomSupports

As I said, the support placement may be a plugin bug, but I doubt the Z positioning and reading is.

**Comment by Ghostkeeper** [comment]
Probably the same problem as https://github.com/Ultimaker/Cura/issues/8878.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
