### ISSUE TITLE
THICKNESS Changes when Using Lay Flat command "Twice" for full lay on bed , even the Slicers Last layer is not complete

### ISSUE THREAD

**Issue by Ruweshed** [Ultimaker/Cura#8922]
![image](https://user-images.githubusercontent.com/72483110/101715608-d2c76180-3aac-11eb-8e8d-26c92b44c2f3.png)
![image](https://user-images.githubusercontent.com/72483110/101715667-ef639980-3aac-11eb-934f-00ec455a107d.png)
![image](https://user-images.githubusercontent.com/72483110/101715742-099d7780-3aad-11eb-94e5-c9aa95de2ec4.png)

You can see the THICKNESS actually is 5 mm ,, then after using Lay Flat to lay it on bed it becomes 6.4   beside that the LAST layer is rubbish.... its halfs or quarters...  Hope it get fixed

**Comment by nallath** [comment]
Can you also share the model?

**Comment by Ruweshed** [comment]
That's the Model  - just click Lay Flat twice ... and check the THICKNESS ,, goes from 5 mm to 6.4 mm  

also Slice it after laying it on bed.... and see how bad are the last layer...


[Ruweshed 3.zip](https://github.com/Ultimaker/Cura/files/5677225/Ruweshed.3.zip)

**Comment by fieldOfView** [comment]
The two texts are not equally thick. The layflat tool naively tries to find a way to have tree points touch the buildplate. Apparently the second time the layflat tool is used, it finds a solution where the three points make the model rotate a little.

Compare it to a wooden board that is not quite flat. Depending on where you put your weight when you stand on it, it will have slightly different orientations.

Cura is not doing anything wrong here. The model does not have a nice flat side so there are multiple stable or not so stable orientations where three points of the model touch the buildplate.
