### ISSUE TITLE
Pre-heat button on Extruder1 conflicts with tooltip

### ISSUE THREAD

**Issue by edolis** [Ultimaker/Cura#8928]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Custom, 3 extruders

**Reproduction steps**
1. select monitor tab
2. try to set temperature and preheat extruder 1. The tooltip explaining the functionality keeps blinking on and off over the temperature and pre-heat button. This is conflicting with attempts to click the underlying Pre-heat button. Need to click repeatedly to try to get the lucky time windows the tooltip is off

This seems to be linked to the fact that there are multiple extruders in the panel. No issues with extruder 2 and 3

**Comment by fieldOfView** [comment]
A screenshot is really helpful

**Comment by edolis** [comment]
![Screenshot 2020-12-13 133901](https://user-images.githubusercontent.com/2226075/102012074-a16ac200-3d48-11eb-99b8-44afbf464b93.png)
Here you go. The grayed area is the tooltip blinking. If you try to click on Preheat, nothing happens

**Comment by Ghostkeeper** [comment]
Those two extruders are also expected to be positioned besides each other rather than underneath each other. That may have something to do with this problem.

**Comment by edolis** [comment]
well, I don't know why this screenshot came like that. First time it happened, the extruders were two beside and one lower, but the issue was exactly the same.

**Comment by Ghostkeeper** [comment]
Oh, so then the issue is not caused by the layout. Good to know.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
