### ISSUE TITLE
App is freezing after last update

### ISSUE THREAD

**Issue by equipment66** [Ultimaker/Cura#8937]
Hi.

Ultimaker Cure v4.8.0 continuously freezing during operation. Situation was noted after last update of MKS plugin. Freezing appears continuously, on every operation inside UI - manipulating with 3d objects, switching windows or using menu. Freezes varies from 1 to  5 -10 seconds.

**Application version: 4.8.0**

**System: Win10 x64**

**Printer: It takes to mach time to find it with freezing app :(**
(Which printer was selected in Cura?)

**Comment by nallath** [comment]
If I understand you correctly, the issue only occurred after upgrading the MKS plugin? If that is the case, please contact the developer of that plugin.

**Comment by equipment66** [comment]
Hi.
  

  
Not absolutely correct. It was noted after last upgrade of MKS. But many guys who are working with FB Ghost from Telegram channels complaints about slowing down Cura right now.
  

  

  

  
  
  
  
>

**Comment by nallath** [comment]
Is the issue still there if the plugin is not installed?

**Comment by equipment66** [comment]
1) will try uninstall it this evening;
  
2) will make short screen video for you before.
  

  
Now I'll go offline for about 2 hours.
  

  

  

  
  
  
  
>

**Comment by equipment66** [comment]
Good Afternoon.

As promised, some videos for you.
Btw, it works much better when screen recorder is active. Mostly likely because priority of processes is changed. But, anyway, you can see freezes on the screen.

https://youtu.be/CnUXljG7Ik0

https://youtu.be/Wkd5ZYdyaU4

https://youtu.be/4Eiha71UXNs

Btw, how to uninstall MKS correctly? Simply delete it from plugins folder?

Geros dienos / Have a nice day,

Vilius Grinkevičius
GSM: +370 660 05003
