### ISSUE TITLE
[4.7.1] Splitting at the top of opening

### ISSUE THREAD

**Issue by guytas** [Ultimaker/Cura#8971]
Love Cura.  Great work guys...  Thanks!

I'm fairly new at 3d printing, and english is not my main language. So excuse my difficulties to explain the problem clearly.

What seems to happen is a missing layer at the very top of opening in the object.  It does not happen every time.  When it happens, the object is fragile as it may split in half easily at that weak point.  Unfortunatly, I do not have the project file related to the exact problem I have picture of.  But strange enough, I already used this same gcode with a different filament (PETG) and it came out OK (not 100% as I could see some lines aligned with openings). Today, (using the same gcode), I used PLA and the splitting was obvious.  See the pictures.

**Application version**
4.7.1

**Platform**
Windows 10

**Printer**
Creality Ender-3

**Reproduction steps**
Not sure exactly but it does not happen every time. But it is always on a layer that happens exactly at the top of an opening in the object.

**Screenshot(s)**
![IMG_20201218_121151](https://user-images.githubusercontent.com/64649145/102643789-c76bda00-412d-11eb-89e9-82e71c991b7a.jpg)
![IMG_20201218_121135](https://user-images.githubusercontent.com/64649145/102643814-d2bf0580-412d-11eb-9f7a-a8d6c61f8247.jpg)
![IMG_20201218_121108](https://user-images.githubusercontent.com/64649145/102643830-d81c5000-412d-11eb-87fd-9f3e53f22b8c.jpg)

**Actual results**
Missing layer

**Expected results**
no missing layer,

**Project file**
As noted, no project file that matches the photos.

**Log file**
No log. Sorry :(

**Additional information**
Here is the gcode file.  Even if the temperature was set to 230, I had changed it to 215 while printing.
[V29D_Fixed.zip](https://github.com/Ultimaker/Cura/files/5717211/V29D_Fixed.zip)

**Comment by nallath** [comment]
You used the same g-code for different materials? That's generally not likely to work. Different materials tend to need different settings (more than just a different temperature).

So this doesn't look like an issue with the slicer. If you have a model where this problem reproduces, we can have a look at it.
