### ISSUE TITLE
[4.8.0] Seam issues (overextrusion?) compared to 4.6.2 on identical settings.

### ISSUE THREAD

**Issue by Gridzilla** [Ultimaker/Cura#8972]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Creality CR-10 S5 levelling probe and a Volcano V6 hotend with .6 nozzle.
OctoPi Octoprint 1.5
Klipper (calibrated e-steps, flow, pressure advance, input filtering and mesh bed levelling)

**Reproduction steps**
1. Install a fresh copy of Cura 4.8.0 and 4.6.2 and set them up identically:
2. Select Creality CR-10 S5 as the printer
3. Install Octoprint plugin
4. Connect Octoprint, copy identical start/end G-Codes into the settings
5. Select .6 nozzle, ABS filament and configure 10% fan (instead of 0)
6. Slice a custom 1.6mm walled flow calibration cube and print

**Screenshot(s)**
4.8.0 on the left, 4.6.2 on the right:
![image](https://user-images.githubusercontent.com/4488015/102685660-97324300-41e2-11eb-8f19-07f77309b89c.png)

More 4.8.0 results:
![image](https://user-images.githubusercontent.com/4488015/102685687-bb8e1f80-41e2-11eb-8d64-65f9c5fab8fe.png)

**Actual results**
The calibration cube is printed. On 4.8.0 the seam seems broken - overextruded? and with a gap inside. On 4.6.2 with identical profile and settings the seam is very nice.

**Expected results**
Given an identical profile and identical set of settings Cura 4.8.0 should produce at least as good results as 4.6.2

**Project file**
[projects.zip](https://github.com/Ultimaker/Cura/files/5719112/projects.zip)

**Log file**
Not a crash so skipping the log file part.

**Additional information**
This is not a printer interface performance issue. The print takes 20 minutes, and is a very simple one. Also my chosen combination of RPi + Octoprint +Klipper has in the past shown to be highly capable. https://github.com/KevinOConnor/klipper/blob/master/docs/Features.md
The issue occurs only on Cura 4.8.0 and does not occur on 4.6.2 and Prusa Slicer.

**Comment by Ghostkeeper** [comment]
Your settings are not the same though. In the 4.6 project the Maximum Resolution and Maximum Deviation settings are both 0.05mm. In the 4.8 project the Maximum Resolution is set to 0.25mm and the Maximum Deviation to 0.025mm.

And indeed the settings should not be the same. In particular, the algorithm for maximum resolution changed in 4.7 to fix the resolution being too low and as a result you should now use a different setting value to arrive at a similar result. The new setting value for Maximum Resolution was determined by the Creality community.
The developers are not able to print with your printer so we are not able to address issues with print quality. We will only fix bugs that are objective mistakes in the g-code output of Cura. Only then can we see whether it's working correctly. We are not even responsible for ensuring good print quality with Ultimaker's printers who are actual customers of our developers, let alone third-party printers. Ultimaker has process engineers that tune the settings; other printers should have something similar to ensure it.

Can you indiate where in the g-code Cura's output is wrong? What should we fix here? The only real difference I can find is in how well the gap filling between your walls is stitched together but that appears to work better in Cura 4.8.
