### ISSUE TITLE
Options for fan on when printing overhangs

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#8975]
Add options for fan on when printing  perimeters and if model have acute angle - fan on too, please. It will be good for ABS with models with an acute angle. This is usually critical at the hot bedf.
![изображение](https://user-images.githubusercontent.com/22872748/102696542-4a7d5500-4240-11eb-82c1-a8bb613dfd55.png)

**Comment by Ghostkeeper** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/5140.
