### ISSUE TITLE
Ability to rename current project

### ISSUE THREAD

**Issue by MarcinOrlowski** [Ultimaker/Cura#8979]
I often load multiple models into one print, then slice and print via OctoPrint without saving gcode. My problem is that Cura uses file name of first loaded model when writing gcode and pushing to OctoPrint and this very unlikely matches the content of the print. For clarification (just in case)

 - start new project
 - drop/load A.stl
 - drop/load B.stl
 - drop/load C.stl
 - ...
 - slice and push (or even save) to printer -> it goes as A.gcode

It would be extremely useful to be able to set project a new name without a need of writing it back and reloading. Just `File -> Set new name` and voila - from now on it would be project name (with all implications) -> i.e. if I rename above example to say `Z` (or `Z.stl`) then hit `Save project` then said `Z` should be base of project filename, not `A` as it is now.

**Comment by fieldOfView** [comment]
You can already do that by pressing the little pencil icon next to the project name in the lower right corner and typing your new name. Or actually you don;t need to press the pencil icon; you can just click the project name and edit it.
