### ISSUE TITLE
Problems importing profiles Cura 4.8

### ISSUE THREAD

**Issue by Br0stein** [Ultimaker/Cura#8982]
**Application version**
(The version of the application this issue occurs with.)

4.8

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

Windows 1909 and Ubuntu 20.04 Snap Package

**Printer**
(Which printer was selected in Cura?)

Ender 3 Pro.

**Reproduction steps**
1. (Downloaded profile from this link https://www.thingiverse.com/download:7084901)
2. (Tried importing it)

**Screenshot(s)**
![Screenshot from 2020-12-20 19-50-53](https://user-images.githubusercontent.com/55747312/102721697-c76e0480-42fc-11eb-9217-86058f8256b6.png)

Clicking the import button and choosing the .curaprofile file.

![Screenshot from 2020-12-20 19-57-26](https://user-images.githubusercontent.com/55747312/102721847-a823a700-42fd-11eb-8630-30bce6605e6c.png)

**Actual results**
See screenshot or additional information

**Expected results**
Profile should be imported.

**Log file**
(Wasn't able to find logs)

**Additional information**
Failed to import profile from /home/torstein/Downloads/1.0_Final.curaprofile: Quality type 'fast' is not compatible with the current active machine definition 'creality_base'.

**Comment by nallath** [comment]
Well, as the error message already explains; The profile you're trying to import isn't compatible with your current machine. 

The profiles that are provided with the 2.x version nr do work.
