### ISSUE TITLE
[4.8] "Initial Layer Horizontal Expansion" has no effect in negative direction

### ISSUE THREAD

**Issue by 877dev** [Ultimaker/Cura#8985]
**Application version**
4.8

**Platform**
Windows 10 Pro x64, 8700K CPU, GTX1080 GPU

**Printer**
Creality Ender-3 Pro

**Reproduction steps**
Using standard 4.8 profile, adjust "Initial Layer Horizontal Expansion" in order to reduce elephants foot

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
Set to 0
![image](https://user-images.githubusercontent.com/46575282/102777836-51fc4580-4389-11eb-8938-3c0ecc63599f.png)

Set to +1
![image](https://user-images.githubusercontent.com/46575282/102777870-65a7ac00-4389-11eb-8a82-98e265d7b7de.png)

Set to -1
![image](https://user-images.githubusercontent.com/46575282/102777957-912a9680-4389-11eb-8755-64efa8100895.png)

**Actual results**
The actual print comes out with elephants foot, always the same no matter what value is used.
![image](https://user-images.githubusercontent.com/46575282/102778564-b4097a80-438a-11eb-9425-fcea3710aa4c.png)

**Expected results**
Reduction of elephants foot when choosing -1

**Project file**
https://www.dropbox.com/s/1uskms1ezs4el1k/CE3PRO_Cura%20Flow%20Rate%20Extruder%20Calibration%20cube%204mm_nozzle.3mf?dl=0

**Log file**
https://www.dropbox.com/s/3zfygy98owg4do9/cura.log?dl=0

**Additional information**
Tried using lower "Initial Layer Flow" which just caused underextrusion/gaps.
Started printing 1/2 cube to save time.

**Comment by nallath** [comment]
This isn't a Cura bug. The initial horizontal expansion is applied correctly, as you've already shown in your screenshots.

**Comment by Ghostkeeper** [comment]
Elephant's foot is not just a matter of the initial layer. In your case it looks like it's caused by the material being able to shrink where it's just thin walls, but not shrink in the flat base of 100% density skin of the model.
