### ISSUE TITLE
Support And Model Issue for macOS Big Sur

### ISSUE THREAD

**Issue by sannsint99** [Ultimaker/Cura#8987]
**Application version**
(4.8.0)

**Platform**
(macOS Big Sur)

**Printer**
(Ender 3 pro)

**Reproduction steps**
1. (I sliced.)
2. (I found Issue.)

**Screenshot(s)**
(![IMG_1793](https://user-images.githubusercontent.com/76437132/102782118-36b02b00-43c7-11eb-983c-85c9013a6b31.jpg)
![IMG_1794](https://user-images.githubusercontent.com/76437132/102782146-3dd73900-43c7-11eb-9d73-268bb65d4db4.jpg)
![IMG_1796](https://user-images.githubusercontent.com/76437132/102783555-7c6df300-43c9-11eb-827d-18a5c8666fda.jpg)) 

**Actual results**
(I attached three screenshots and the first one shows the actual 3d model, the second is after sliced with support and the last one is the sliced model with hidden helpers. The problems is that you can see what's wrong with nose and bag that i circled. Not only in this model, I always faced with this issue for some 3d models. So, can you tell me what i have to do. Please email me on sannsint99@gmail.com 
Thank You. )

**Expected results**
(I want my 3d print to be printed like the actual 3d model.)

**Project file**
(I can't upload 3mf files.)

**Log file**
(-)

**Additional information**
(No more. Thanks.)

**Comment by nallath** [comment]
Disable the setting "Make Overhang Printable"
