### ISSUE TITLE
Print Status: Layer Number

### ISSUE THREAD

**Issue by ArtZL** [Ultimaker/Cura#8989]
In Ultimaker Cura, on the Monitor screen while printing...
It would be helpful if it lists the layer # it is on, out of how many layers.
eg:  21/57

**Comment by evtrados** [comment]
Hi @ArtZL ,

Thanks for opening this Feature Request. We discussed it with the whole team and we think that, even though it could be helpful to some extent, we do already have a progress bar, so we don't believe it is something will implement. As a result, I will have to reject it, sorry.

**Comment by ArtZL** [comment]
The reason I requested this enhancement is because I often want to watch the print when it gets to a certain layer.  A progress percentage is not precise enough.
