### ISSUE TITLE
[4.8.0] Text / characters are jumbled on screen during model translations

### ISSUE THREAD

**Issue by gr3333** [Ultimaker/Cura#8993]
**Application version**
4.8.0

**Platform**
Mac. OS 11.1 on new M1 Mac Mini.

**Printer**
CR-10S

**Reproduction steps**
1. Load an STL model
2. Select the model on the build plate and attempt to move or rotate it

**Screenshot(s)**
![Screen Shot 2020-12-21 at 3 13 03 PM](https://user-images.githubusercontent.com/76456703/102832027-1c178b00-43a2-11eb-9f0c-1b04311fb5ee.png)

**Actual results**
The text that shows the move/rotation is garbled/not legible

**Expected results**
I should get a legible display to assist with move

**Project file**
n/a

**Log file**
n/a

**Additional information**
As noted above, this may have to do with the graphics of the new M1 Macs.

**Comment by Ghostkeeper** [comment]
This is an upstream bug in the Qt GUI framework we're using: https://bugreports.qt.io/browse/QTBUG-89379 .

It's not really anything we can do anything about until Qt fixes the problem. We can't claim to support Apple M1 at the moment because Qt doesn't support it.

**Comment by jottr** [comment]
This is happening to me on Macos since `Mavericks` I belive. 
Currently I'm on `Big Sur` and the issue remains:

```
$sw_vers
ProductName:     macOS
ProductVersion: 11.6
BuildVersion:   20G165
```

`Cura v4.10.0`.

**Comment by jottr** [comment]
It seems a [bugfix](https://codereview.qt-project.org/c/qt/qtbase/+/354944) has been merged to the following QT versions: `6.2 6.1 5.15 5.12`.

**Comment by julianCast** [comment]
This is happening to us on a Intel chip (not a M1) but only on Big Sur OS.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by gr3333** [comment]
I haven’t seen this issue recently.On Nov 19, 2024, at 6:36 PM, GregValiant ***@***.***> wrote:﻿
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
