### ISSUE TITLE
Tree supports + brim generates outside of build area.

### ISSUE THREAD

**Issue by Cortexian** [Ultimaker/Cura#8995]
**Application version**
4.8.0

**Platform**
Windows 10 Pro
i7-6800k
32 GB RAM
GeForce GTX 1080ti

**Printer**
Ender 3 V2 (Based on Ender 3 settings)

**Reproduction steps**
1. Import a large/relatively tall print that takes up most of the bed.
2. Generate tree supports on overhangs on the outside of the model.
3. Generate a brim.

**Screenshot(s)**
![Brim Error](https://i.imgur.com/BjR6RIb.jpg)

**Actual results**
Brim is generated outside  of build area if the tree support determines it needs to be generated near the edge of the print area.

**Expected results**
Brim should be fully contained within the safe build area. Tree support should be forced to generate closer to the center of the print volume.

**Project file**
I cannot share this as it is a purchased model. I do not have the rights to share it.

**Comment by rburema** [comment]
Hi! We've created ticket internal ticket CURA-7940 for this. Posting this so we can link up our internal ticket with this one, and let you know that, while we might not get to it for a while, it is now in our system as a bug to be fixed.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
