### ISSUE TITLE
Iron top layer only, does not work as adverterised with multiple objects with varying heights

### ISSUE THREAD

**Issue by tjennex** [Ultimaker/Cura#8997]
**Application version**
4.8

**Platform**
Linux

**Reproduction steps**
1. Open / bring in an file such as a cube.
2. Place another object that is taller than the first beside the first. You can use a cube that is twice as tall either have the file built outside of Cura to be twice as tall as the first cube or open and bring in the same cube again then adjust the scaling to be twice as big or just noticeably larger so the top of one of them is taller than the other. If you make the second at least twice as tall you will later be able to see the seam in the middle of the taller cube which creates a weak bond and you can snap the cube in half at the weak point.
3. Enable Ironing
4. Enable Top layer only highest layer
5. All other Ironing settings are default to what Cura 4.8 had set.
5. I was using super quality and 100% infill settings

**Actual results**
Both cubes iron top layer, but taller cube also has the layer which lines up with the top of the shorter cube ironed. If your cube is twice as tall you can then break it in half at the ironing point. The first layer that is taller than the first cube (shorter cube) is a very weak.

**Expected results**
Both cubes should have top layer ironed only.

**Comment by rburema** [comment]
I have tried this with a model (import STL. duplicate, scale one in Z 200%, put 'ironing' and 'highest layer only'), but could not reproduce it. Could you make a project file, and attach it here? (Zip to appease github.)
