### ISSUE TITLE
Rotating object not working

### ISSUE THREAD

**Issue by perfoWorks** [Ultimaker/Cura#9002]
**Application version**
4.8.0

**Platform**
MacOS Bir Sur (11.0.1)

**Printer**
Repetier

**Reproduction steps**
1. Select model in Cura
2. Click on rotate button
3. By selecting axis to rotate the axis disappear so there is no way to rotate part

**Expected results**
Be able to rotate parts.. Sorry new to Cura but I believe I do these steps correctly.. Or am I missing something again?

**Comment by fieldOfView** [comment]
Probably a duplicate of https://github.com/Ultimaker/Cura/issues/8831

**Comment by Ghostkeeper** [comment]
Yeah. Closing as a duplicate of https://github.com/Ultimaker/Cura/issues/8745.
