### ISSUE TITLE
Ultimaker s3

### ISSUE THREAD

**Issue by dimitriosapostolou** [Ultimaker/Cura#9013]
It is unfair to pay this amount of money for a product that has a software that is worst than Windows Millennium.
Honestly i regret the money that I spend.
So many issues with the software.
There are so many issues that I have to write a book to explain how software engineering employee of the company they have to do their job and I am not this kind of engineer.
And I am not the only one. Google '' Ultimaker issues'' and you will see how many people have  problems with the software.
I can't refund my money, the only way is to wait some sort of updates.
But after 8 months I don't see a lot.
Really disappointed 
Look forward to find another solution.

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.
