### ISSUE TITLE
cura4.8.0-display problem 

### ISSUE THREAD

**Issue by 342358472** [Ultimaker/Cura#9021]
![1608991502(1)](https://user-images.githubusercontent.com/76620613/103153318-b5221980-4787-11eb-9a47-dad559fb222b.jpg)

Menu interface appears disorderly code, other software display normal
![捕获](https://user-images.githubusercontent.com/76620613/103153372-f3b7d400-4787-11eb-80cd-75b33c0aef77.PNG)

**Comment by Ghostkeeper** [comment]
Hmm, definitely something weird with how Qt displays that drop-down there. We're not really doing anything special. It's using the default system-themed drop-down there.

On other Windows computers it's apparently normal. Maybe it has something to do with the locale of Windows or the font rendering specific to the Chinese locale? Weird.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
