### ISSUE TITLE
Cure doesn´t retract anymore

### ISSUE THREAD

**Issue by Demhat21** [Ultimaker/Cura#9024]
Hi,
I printed many stuff with Cura Version 4.8.0 and my Creality CR 6-SE and it worked well. But since one day I struggle with the retraction. I use a GCode simulator to look if there is any retract but there isnt. I also teste the Creality slicer with the same object and it retracted, so it must be Cura. I even disabled combing, but it still wont work. Do anyone know what to do?
I hope I can solve it.

**Comment by Ghostkeeper** [comment]
Using the default profile of Creality CR6 SE I'm getting retractions fine, loading in two cubes: [retracting_properly.zip](https://github.com/Ultimaker/Cura/files/5748733/retracting_properly.zip)

They show up in the g-code like this:

```
G1 X104.298 Y95.458 E12.79247
G1 X104.866 Y94.756 E12.8225
G1 F1500 E6.3225
;MESH:cube.stl(1)
G0 F6000 X111.835 Y101.914
G0 X112.914 Y101.914
```

Could you fill in the issue template when you report a bug?
