### ISSUE TITLE
Slicing freeze

### ISSUE THREAD

**Issue by naedioba** [Ultimaker/Cura#9025]
**Application version**
Arachne engine alpha

**Platform**
Windows 10

**Printer**
Ender-3 Pro and Ender-3 v2

When I load a file and slice it, the slicing starts then freezes automatically.
I tried with even very small files, but it does the same.

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
Could you fill in the issue template, please? You've deleted the section "project file" which is extremely important to be able to reproduce your issue. I tried loading in a simple cube using default settings but the issue doesn't reproduce for me.
