### ISSUE TITLE
Fine grained acceleration and jerk controls for travel moves

### ISSUE THREAD

**Issue by JohnTasto** [Ultimaker/Cura#9026]
**Is your feature request related to a problem? Please describe.**
When travel acceleration and jerk are high, it causes ringing at the start of the next print move, as well as a rougher Z seam.

**Describe the solution you'd like**
There should be additional fine grained controls for travel acceleration and jerk, in particular for travels just before the start of a wall, especially the outer wall.

Another option that avoids adding a bunch of additional user settings: for any travel move immediately followed by a print move, limit that travel move's acceleration and jerk to those of the following print move. The existing travel acceleration and jerk settings would still apply to travel moves not immediately followed by a print move.

**Describe alternatives you've considered**
Reducing acceleration and jerk of all travel moves improves the Z seam, but at the expense of slowing down the whole print.

**Affected users and/or printers**
All users and all printers.

**Additional context**
Ideally, the start and end of travel moves should have separate settings, since the end will have a greater effect on the next print move. This would require firmware support and changes to the G code API, however.

**Comment by fvrmr** [comment]
Thanks for your feature request, we will defer this for now. This is not a priority right now.
