### ISSUE TITLE
Cura Froze after material export

### ISSUE THREAD

**Issue by DonBower** [Ultimaker/Cura#9038]
**Application version**
4.8.0

**Platform**
macOS Catalina 10.15.7

**Printer**
Ender 3 v2

**Reproduction steps**
1. Open Preferences, Materials
2. Selected current material
3. Clicked Export

**Screenshot(s)**
<img width="892" alt="Screen Shot 2020-12-29 at 10 15 12 AM" src="https://user-images.githubusercontent.com/20584853/103306160-bb9bd580-49c1-11eb-8504-a3a3188eba50.png">

**Actual results**
Cura Froze

**Expected results**
Not Freeze

**Project file**
None

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5751761/cura.log)

**Additional information**
Had to Force Quit

**Comment by Ghostkeeper** [comment]
I've not been able to reproduce this issue so far on my computer. It's properly exporting the file and not freezing.

The fact that the pop-up appears with a success message shows that the file was properly exported completely, and the file handle closed. Writing that file should have nothing to do any more with the freeze. But I don't see why a simple pop-up would cause Cura to freeze. Maybe there is another pop-up underneath that has the actual focus or something?

**Comment by DonBower** [comment]
After rebooting my Mac, I too, am unable to replicate this issue.
We should just close this i think.
