### ISSUE TITLE
Render display not on the right spot

### ISSUE THREAD

**Issue by timobrabant** [Ultimaker/Cura#9042]
**Application version**
4.7.1

**Platform**
MacOS Catalina 10.15.7

**Printer**
Ender 3

**Reproduction steps**
MacBook Pro 15'', 2880 x 1800px display

when i open a game like minecraft in fullscreen at 1080p and then switch to the desktop again this happens.

**Screenshot(s)**
<img width="1680" alt="Bildschirmfoto 2020-12-30 um 03 01 21" src="https://user-images.githubusercontent.com/74685896/103325486-57722380-4a4c-11eb-928e-79ac2eeb533d.png">
 
<img width="1680" alt="Bildschirmfoto 2020-12-30 um 03 09 53" src="https://user-images.githubusercontent.com/74685896/103325541-7ffa1d80-4a4c-11eb-8e22-ba62050e9888.png">

**Actual results**
this

**Expected results**
this

**Project file**
its not in a project

**Log file**
what log?

**Additional information**

**Comment by fvrmr** [comment]
We need the log file for this. You can find your log file here: $USER/Library/Application Support/cura/<Cura version>/cura.log (OSX)
