### ISSUE TITLE
Cura Not saving profile changes

### ISSUE THREAD

**Issue by Fabrizio3** [Ultimaker/Cura#9065]
i was trying to modify some settings and when i opened cura the next day, the speeds were reverted, so i thought it was cura limiting the max speed allowable (installed printer settings plugin to modify it) but nothing, then i found out its cura not saving profiles, or what i suspect reading from an older version, its not reading from the changes file and its reading from the default one

**Application version**
Cura 4.8.0

**Platform**
Windows 10

**Printer**
Custom Printer (Modified Anet A8)

**Reproduction steps**
1. tried changing speeds on the settings from 150 to 250, when i re-opened cura speeds were back to 150
2. changed a random setting like minimum layer time from 4 to 3, saved the profile (update profile with current settings like i always do), closed cura and opened it back up, sure enough it didn't save any changes

**Actual results**
No profile changes were saved

**Expected results**
"update profile with current changes" saves the profile's changes and when you open cura again, it loads them

Yes, i do use those speeds, sometimes going up to 300mm/s with the high flow hotend i have installed and my travels are set at 300 too, those are actual speeds

**Comment by fvrmr** [comment]
I followed your reproduction steps but when I changed speeds to 250 and re-opened Cura it was still on 250.
Can you share your log file?
