### ISSUE TITLE
MacOS Big Sur

### ISSUE THREAD

**Issue by baraop** [Ultimaker/Cura#9067]
Too much information! Just check a lot of errors using the new MacOS.
Especially when you add some cube on model to overlap.

Thanks

**Comment by fvrmr** [comment]
Please specify your errors, maybe you can share some screenshots?

**Comment by Ghostkeeper** [comment]
We've ran Cura on Big Sur ourselves and the only Big Sur specific issue we can currently reproduce is this one: https://github.com/Ultimaker/Cura/issues/8745
