### ISSUE TITLE
Advanced wipe, coast, combing

### ISSUE THREAD

**Issue by Julius971** [Ultimaker/Cura#9081]
**Is your feature request related to a problem? Please describe.**
Stringing, caused by melting printed filament during retract

**Describe the solution you'd like**
The idea is that the retraction move is during a wipe move or similar or even the travel move itself.

**Affected users and/or printers**
Fdm printers

**Comment by fvrmr** [comment]
What do you mean with a wipe move?

We have something familiar and that is post processing scripts - retract continue. 
You can find this in: Extensions - Post processing - Modify G-code - Add a script - Retract Continue.

**Comment by Julius971** [comment]
The problem is, that the printhead stops during retract moves. And i wonder if it could retract while moving.

Julius Maetzig

**Comment by Ghostkeeper** [comment]
The Retract Continue post-processing script does this. Just set the normal retraction length to 0mm though.
