### ISSUE TITLE
[4.8.0] Cutting Mesh triggers bridging

### ISSUE THREAD

**Issue by intercipere** [Ultimaker/Cura#9083]
**Application version**
4.8.0

**Reproduction steps**
1. Load model
2. Place Modifier Mesh on model
3. Select 'Modify Settings for Overlaps' and 'Cutting Mesh' for the Mesh Modifier

**Screenshot(s)**
![Screenshot 2021-01-07 120220](https://user-images.githubusercontent.com/11316917/103885380-39599280-50e0-11eb-8e52-0a8932dd7e06.png)

**Actual results**
Cura will partially produce thin walls on the modified mesh, and also change Acceleration settings as seen in the image, even if no parameters have been selected or changed for the cut mesh. It will also print exactly as Cura shows it, it is not a display bug. Changing Line Width, Wall Thickness, Flow etc has no influence on the result.

**Expected results**
The wall thickness and Acceleration should not change if no parameters have been changed for that.

**Comment by fvrmr** [comment]
Can you share your project file? Because I can't reproduce this right now.

**Comment by intercipere** [comment]
Oh sorry, here it goes:

[test.zip](https://github.com/Ultimaker/Cura/files/5783105/test.zip)

**Comment by fvrmr** [comment]
Thanks, I got the same issue. Will discuss this with the team.

But found a workaround, search in settings for bridge and disable bridge settings. 

![Screenshot (3)](https://user-images.githubusercontent.com/77000924/104004931-ac2c4180-51a4-11eb-93aa-dff2d7210edd.png)

**Comment by intercipere** [comment]
Thank you, the workaround works for me aswell.

**Comment by fvrmr** [comment]
We discussed it with the team. Bridge is in experimental mode, it is not a big issue for now. Luckily you have a workaround for future projects.

**Comment by Triangulix** [comment]
In cura 5.1.0 this Bug ist still present.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
