### ISSUE TITLE
[4.7.1] Ooze shield does not respect setting for Initial Layer Print Speed

### ISSUE THREAD

**Issue by ludgerus** [Ultimaker/Cura#9090]
[4.7.1] Cura

macOS Catalina 10.15.7

UMS5

**Reproduction steps**
- Dual Extrusion with TPU and PETG
- TPU needs to be printed very slowly on the initial layer
1) The object's first layer was printed fine and very slowly at 5 mm/s
2) After that the initial layer of the Ooze shield was "printed" much too quickly and didn't stick.

I know it might be disputed if this is actually a bug because the initial layer of the ooze shield is not the same as the initial layer of the object. The initial layer of the ooze shield is one layer above the initial layer of the object. Cura obviously doesn't see the first layer of the ooze shield as an initial layer. I say: Of course it should.

Print quality is not as good as it could be for the first few layers.

Thanks for your attention

Ludger

**Comment by fvrmr** [comment]
I couldn't reproduce this, can you share your project file?
