### ISSUE TITLE
Missing Z Layers When Using "Raft" and "One At A Time" Cura 4.8

### ISSUE THREAD

**Issue by spanse** [Ultimaker/Cura#9091]
**Application version**
4.8.0

**Platform**
Windows 10 1809

**Printer**
CR10

**Reproduction steps**
1. Add multiple STLs to the project
2. Select "Raft" for bed adhesion
3. Select "One At A Time" in special print options
4. Successfully slice the project

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/18105892/104056304-e6eaa580-51b5-11eb-8095-ffa723abd26d.png)

**Actual results**
Several layers at a certain Z height are moved to the bottom layers.

**Expected results**
Layers should remain at their proper Z height. As they do whenever the "Raft" and "One At A Time" option aren't used together.

**Project file**
[MissingZLayers.zip](https://github.com/Ultimaker/Cura/files/5789052/MissingZLayers.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5789059/cura.log)

**Additional information**
Issue reoccurs at the same z height, and only occurs when "Raft" and "One At A Time" options are used together. objects that print entirely below this height do not appear to have any issues.

**Comment by fvrmr** [comment]
Thanks for your project file, we can finally reproduce this with your file.

This is a known issue. You can find it here: https://github.com/Ultimaker/Cura/issues/7412
