### ISSUE TITLE
[Enhancement request] Separate coasting values for Walls and other types

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/Cura#9095]
**Is your feature request related to a problem? Please describe.**
I have tuned my coasting values in order to almost eliminate surface seams - however I am still getting blobs where retractions occur internally.

**Describe the solution you'd like**
I would like to be able to have a higher coasting volume for internal retractions / combs as slight under-extrusion internally is not really a major issue.

**Describe alternatives you've considered**
None.

**Affected users and/or printers**
All users.

**Comment by fvrmr** [comment]
We will discus this with the team. Keep you posted.

**Comment by fvrmr** [comment]
We will defer this for now, because we think this is not one of our priorities right now. But we are experimenting with some alternatives to improve the transition in flow rate.
