### ISSUE TITLE
after "select face to align build plate", object does not touch the buildplate 

### ISSUE THREAD

**Issue by Jogge92** [Ultimaker/Cura#9099]
**Application version**
Cura4.8.0

**Platform**
Windows10

**Printer**
UM2+

**Reproduction steps**
1. Import STL FIle
2. Select face to align to build plate

**Actual results**
![grafik](https://user-images.githubusercontent.com/77214339/104110744-df70ec80-52da-11eb-87ff-aa768667927e.png)

**Expected results**
![grafik](https://user-images.githubusercontent.com/77214339/104110785-3f679300-52db-11eb-90d5-4b42bb5c69c6.png)

**Comment by fvrmr** [comment]
I can't reproduce this issue, when I try this my Z = 0. Can you share your model or another model that has the same problem?

**Comment by Jogge92** [comment]
I cant upload the original file, sorry...but this file hast the same problem!
the surface i want to align is still the as in the pictures. thx
[buggy_part.zip](https://github.com/Ultimaker/Cura/files/5797706/buggy_part.zip)

**Comment by konskarm** [comment]
I cannot reproduce that either. I tried with your stl file, but whatever face I select to align it ends up properly at Z=0.
