### ISSUE TITLE
Naming gcode files while saving

### ISSUE THREAD

**Issue by hygroscopiccarpaccio** [Ultimaker/Cura#9103]
**Is your feature request related to a problem? Please describe.**
I normally save all my gcodes for reuse at a later date. When doing so, I sometimes cant remember if the settings were optimal or not, hence naming the gcodes with some information. I'm not into opening the gcode and analyzing it, especially since it's hosted on the octopi.

**Describe the solution you'd like**
Currently when saving gcode files I manually add this to the filename so I can easily print it again
+profile (ie draft/fine)
+material
+infill 
+plate adhesion
+print time

It would be great to have these and more options to be added to the filename automatically. Perhaps also dates and other people might have more requirements.
It would also be great to be able to set the default directory for opening and saving files. -Remembering the last option is not always enough.

**Describe alternatives you've considered**

Doing it manually, but it's not concise 

**Affected users and/or printers**

re-printers

**Additional context**

Rather than to have a tickbox such as for "adding machine prefix" to the name, I'd like to see an option where you can compose your own prefix. For instance %p-%m-%i-%p-%P (or similar) in the example above. 

THANKS

**Comment by fieldOfView** [comment]
There are 2 plugins that will let you do what you propose:

https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/CustomJobPrefix and https://marketplace.ultimaker.com/app/cura/plugins/lokster/CustomSupports

**Comment by hygroscopiccarpaccio** [comment]
Great, thanks

**Comment by KenLucke** [comment]
Have to second the GcodeFilenameFormat recommendation.  I use it heavily, and the author is highly responsive to feedback.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/57936294/104133188-c7c75180-5336-11eb-8586-8e3307b4f2b3.png">

**Comment by nallath** [comment]
Since there are plugins that can do this, I'm going to close this.
