### ISSUE TITLE
[4.8.0] OpenGL glitch on M1 MacBook with large project size

### ISSUE THREAD

**Issue by jamesloper** [Ultimaker/Cura#9107]
**Application version**

4.8.0

**Platform**

2020 M1 Macbook Air

**Printer**

Ender 3 V2

**Reproduction steps**

1. Import 14 STL files to print in one go.
2. Select Standard Quality and change to Gyroid infill
3. Click preview

**Screenshot(s)**

![image](https://user-images.githubusercontent.com/8919598/104144016-c1b18f00-538f-11eb-93e7-05caca42d901.png)

On some frames it partially recovers and looks like this:

![image](https://user-images.githubusercontent.com/8919598/104144435-35a06700-5391-11eb-99d9-efba8be64457.png)
In this ss there the bug is maybe manifesting itself differently. Some of the tool paths are actually missing

**Actual results**

Multiple vertex explosions and some serious lag

**Expected results**

The visuals should accurately represent the underlying polygon data.

**Project file**

https://drive.google.com/file/d/1reB8H5fc3PTBRx_UNsxYtokS-lnjEzOY/view?usp=sharing

**Log file**
There was no log file, as in...
```
james@M1 ~ % tail "$USER/Library/Application Support/cura/4.8.0/cura.log"
tail: james/Library/Application Support/cura/4.8.0/cura.log: No such file or directory
```

**Comment by bkarr123** [comment]
I'm having this same issue as well. I just tried to slice a file and this is what my preview looks like then Cura crashed when I mess with the preview. 

This has happened with 2 different STL files. Both are single STL files with 1 or 2 objects

Running Cura 4.8.0 on a Macbook Air M1 (2020)


![IMG_8913](https://user-images.githubusercontent.com/76626217/104663247-30456400-5692-11eb-80ac-d1ec37b103dc.jpg)

**Comment by fvrmr** [comment]
Cura is currently not supported on new Macbooks containing the M1 chip. Apple introduced incompatibilities between the OpenGL libraries used and the latest firmware used by the Macbook. 
You can read more about the [Apple M1 chip on their website](https://www.apple.com/mac/m1/). 

We look into fixing this in an upcoming version.

**Comment by bkarr123** [comment]
> Cura is currently not supported on new Macbooks containing the M1 chip. Apple introduced incompatibilities between the OpenGL libraries used and the latest firmware used by the Macbook.
> You can read more about the [Apple M1 chip on their website](https://www.apple.com/mac/m1/).
> 
> We look into fixing this in an upcoming version.

Wow, that's unfortunate. Please keep us posted.

**Comment by bkarr123** [comment]
Is there an update on Cura being supported with the Apple M1 chip in the new macbook?

**Comment by nallath** [comment]
> Is there an update on Cura being supported with the Apple M1 chip in the new macbook?

Not yet.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
