### ISSUE TITLE
Cura fails using Full Screen mode.

### ISSUE THREAD

**Issue by TxarlyM** [Ultimaker/Cura#9115]
**Application version**
4.8

**Platform**
Windows 10 20H2

**Printer**
Anycubic Mega Zero

**Reproduction steps**
1. When I set Full Screen from the Menu (View-> Alternate Full Screen) or pressing F11, the whole screen blinks each time a menu option is selected, and sometimes the options selected from menu is not shown.
2. Press F11 again to return to windowed mode.

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Only the application works without problems in windowed mode.

**Expected results**
The screen might not to blink any time if it is in Full Screen or not. In my computer none of the applications installed have problems in full screen mode.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
The computed has a GPU Nvidia GT440... It's a quite old gpu, and I never had any problem to use it.The resto of the computer mounts an i3-2400 CPU with 16 Gb SDRAM and a 260Gb SSD.

**Comment by fvrmr** [comment]
Can you share your log file? You can find it here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.lo`
