### ISSUE TITLE
Feature Request: Add back selection of comport and speed

### ISSUE THREAD

**Issue by boelle** [Ultimaker/Cura#912]
as subject says we badly need this

and yeah yeah i know some will say its my printer that is wrong

but no.. inde 15.04.06 its the same thing... it works as soon i select manual

**Comment by Ghostkeeper** [comment]
We can make a machine setting out of that. Would be nice to put it in fieldOfView's machine edit menu too.

**Comment by Ghostkeeper** [comment]
Ah, I found that we already had a ticket for this. It was linked to an earlier feature request: https://github.com/Ultimaker/Cura/issues/799

**Comment by boelle** [comment]
so then next q is when 2.3 is out?

i'm stuck with 15.04.06
