### ISSUE TITLE
Barra horizontal en vista previa (NO SALE ) 

### ISSUE THREAD

**Issue by fml9217** [Ultimaker/Cura#9121]
Cuando de carga cualquier archivo y se da a VISTA PREVIA  , no sale la barra horizontal de abajo. 
Cura. 4.8 o cualquiera version . W7. 64bit . ordenador se ha reiniciado varias veces , se ha desistalado CURA , varias veces .

![cura4 8](https://user-images.githubusercontent.com/77402611/104479933-42f16780-55c4-11eb-8865-dad8938a5d97.png)

**Comment by fvrmr** [comment]
Can you share your log file? 
You can find that here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

I'm also wondering if your screen is scaled over 100%?

**Comment by fml9217** [comment]
scaled 100%
    En jueves, 14 de enero de 2021 14:04:15 CET, fvrmr <notifications@github.com> escribió:  
 
 


Can you share your log file?
You can find that here: C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log

I'm also wondering if your screen is scaled over 100%?

**Comment by juanmomos** [comment]
tengo el mismo problema
