### ISSUE TITLE
Arachne engine crashes when ejecting sd card

### ISSUE THREAD

**Issue by JoeEnderman** [Ultimaker/Cura#9122]
**Application version**
Cura Arachne Engine Alpha build

**Platform**
Windows 10 AMD Ryzen7 laptop

**Printer**
Ender 3

**Reproduction steps**
Slice file
Save file to sd card and click "eject"

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
Cura closes

**Expected results**
Cura remains open in the event I still intend on using it.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Prickly-Pear** [comment]
The same issue was reported earlier: [https://github.com/Ultimaker/Cura/issues/9057#issue-777368763]

This problem also occurs on MacOSX (v10.15.7). After saving gcode to memory card, clicking the eject button makes the program close unexpectedly.
