### ISSUE TITLE
Arachne engine alpha - doesn't slice with voron 2.4 setting

### ISSUE THREAD

**Issue by n7484443** [Ultimaker/Cura#9124]
**Application version**
Arachne engine alpha

**Platform**
Window 10

**Printer**
Voron 2.4

**Reproduction steps**
1. setting up to voron 2.4 normal setting.
2. I tried to slice 3Dbenchy.

**Screenshot(s)**
![not](https://user-images.githubusercontent.com/7384324/104636701-1b46f000-56e7-11eb-9a14-58344efa7f85.png)

**Actual results**
At first, the status bar fills up, and after reaching 100%, it stops at 0% and never change.

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5816484/cura.log)

**Comment by fvrmr** [comment]
We have a lot of issues for Arachne, see the discussions here: https://github.com/Ultimaker/Cura/discussions/8965 
We hope to solve a lot of issues soon.

**Comment by n7484443** [comment]
ah, I found it was bridge issue. Thank you

**Comment by fvrmr** [comment]
Since you've found the solution, I will close this issue.
Bridge issue can be found here: https://github.com/Ultimaker/Cura/discussions/8965#discussioncomment-234502
