### ISSUE TITLE
configuraçoes desaparecendo

### ISSUE THREAD

**Issue by eddbull** [Ultimaker/Cura#9134]
o ultimaker cura 4.8.0 faz algumas configuraçoes sumirem como a velocidade do brim, elas só aparecem quando reinicio o cura.

the cure ultimaker 4.8.0 makes some configurations disappear as the brim speed, they only appear when I restart my healing.

**Comment by jellespijker** [comment]
Please fill in the bug report template, in either English or Dutch. Makes sure you attach the project file and log files
