### ISSUE TITLE
resolução do suporte

### ISSUE THREAD

**Issue by eddbull** [Ultimaker/Cura#9135]
mudar a resolução só do suporte, porque resoluções mais altas da peça fazem os suportes mais finos não serem impressos corretamente, editar a resolução só do suporte pode resolver o problema invés de mudar a resolução da peça inteira.

changing the resolution of the media only, because higher resolutions of the part cause the thinner media not to print correctly, editing the resolution of the media alone can solve the problem instead of changing the resolution of the entire part.

**Comment by jellespijker** [comment]
Please fill in the bug report, preferably in English or Dutch
