### ISSUE TITLE
Can't start Cura without printer

### ISSUE THREAD

**Issue by ColinPitrat** [Ultimaker/Cura#9143]
I used to use an old version of Cura on my personal computer to prepare prints that I was then executing at my Fablab.
This was working well.
I recently updated my Cura version and found out that I cannot start it without connecting to a printer, which prevents me from preparing my print ...

Could you please add a "Skip" option to the screen for connecting to a printer?

**Comment by fieldOfView** [comment]
See "Add a non-networked printer". This is not about connecting a printer, but telling Cura what sort of printer you want to slice for.

**Comment by ColinPitrat** [comment]
This screen is completely empty for me apart from a field to name my printer:
![cura_add_printer](https://user-images.githubusercontent.com/1541863/104904761-74c64d80-5979-11eb-851b-1e019d1882da.png)

**Comment by fieldOfView** [comment]
Then we need to see your cura.log. It can be found in `%APPDATA%\cura\4.8\`.

**Comment by ColinPitrat** [comment]
Sorry, I should have provided more details as it turns out it's not "work as designed".
I'm using v4.7.1 on ubuntu.
There's a $HOME/.config/cura/4.7 directory but no logs in it.
`strace cura 2>&1 | grep open | grep "\.log"` doesn't show any log file being opened (even `cura --debug`).

**Comment by fvrmr** [comment]
On ubuntu you can find it here: `$USER/.local/share/cura/<Cura version>/cura.log`

**Comment by fieldOfView** [comment]
Given that you are not using the current version, I suggest you also try the official AppImage provided by Ultimaker.

**Comment by ColinPitrat** [comment]
`~/.local/share/cura/4.7/` exists but doesn't contain any log:

```
$ find ~/.local/share/cura/ -name \*.log
$ 
```

The AppImage version works fine though, so I'll go with it.

Thanks for your help. I'll closed this for now as this solves the problem on my side.
