### ISSUE TITLE
Object List order does not match order sliced for One at a Time

### ISSUE THREAD

**Issue by FlyMyPG** [Ultimaker/Cura#9172]
**Application version**
4.8.0

**Platform**
Win10 on Lenovo Legion 5 (Ryzen 4800H, nVidia 2060)

**Printer**
Artillery/EVNOVO Sidewinder X1 v4

**Reproduction steps**
1. Ensure Settings -> Printer -> Manage Printers -> Machine Settings -> Printhead Settings values are correct.
2. Simultaneously select multiple STLs in same directory to place on bed (to intentionally obfuscate part load order).
3. Set Print Sequence to One at a Time
4. Arrange parts so all are printable.
5. Observe content and order of Object list at bottom left corner of the Prepare view.
6. Slice.
7. Select Preview, and move slider.
8. Observe order in which parts are printed.
9. Observe this order does not match the Object list order.
10. Scratch head.

**Screenshot(s)**
![Untitled](https://user-images.githubusercontent.com/9974733/105621570-b6ae2400-5dbd-11eb-9529-7a5ee87f4884.png)

Notice the 4th part printed, the screw, is the 5th item in the Object list.  The prior parts are printed in the order of the Object list.

**Actual results**
Only the Slicer knows the Secret Part Print Order!

**Expected results**
The Object list order should match the order parts are printed for One at a Time.

**Project file**

**Log file**

**Additional information**

**Comment by fvrmr** [comment]
Thank you for your issue. This is expected behaviour, the object list has nothing to do with the print order. 
You can find more information about printer order here: https://github.com/Ultimaker/Cura/issues/4835
Feel free to continue the thread there, that's why I will close this issue.
