### ISSUE TITLE
3D Printer - Anycubic Mega Pro - Add Printer

### ISSUE THREAD

**Issue by jpsmyth** [Ultimaker/Cura#9174]
Hi, loving the software so far however my printer is not listed in the "add printer" listing. Could you please include it? If not could you please guide me as to how I can create one using the "Custom / other" settings?

**Comment by fvrmr** [comment]
Hi @jpsmyth, you can follow this guide for adding new machines profiles to Cura: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura

I will close this issue, since it is not a new feature. But please let me know if you need more help!
