### ISSUE TITLE
Cura 32bit findet den HE3D nicht

### ISSUE THREAD

**Issue by Berni-Nord** [Ultimaker/Cura#9178]
Hallo,
ich habe eine HE3D Drucker. Bei der Cura 2.3.1 Software für mein 32bit PC wird der HE3D zwar angezeigt aber nicht verbunden. Was kann ich tun?

**Comment by fvrmr** [comment]
Can you fill in the issue form in English. I understand you are using Cura 2.3.1. Did you try the newest version (4.8) of Cura?

**Comment by fvrmr** [comment]
The 2.3.1. version of Cura is the latest version that is for a 32bit. 
Unfortunately we don't support this version anymore, so we can't really help you with this.
That's why I will close this issue.
