### ISSUE TITLE
Add cura print support for M3D micro +

### ISSUE THREAD

**Issue by epicodertime** [Ultimaker/Cura#9180]
**Is your feature request related to a problem? Please describe.**
No it's not
**Describe the solution you'd like**
(The ability to use the M3d printer on cura without any configuration 

**Affected users and/or printers**
(This will help M3D users who use the m3d micro printer as it will help improve there productivity with cura

**Comment by fvrmr** [comment]
Thank you for your feature request. You can add a machine manually by following this guide: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura

If you want that other users can use this profile you can make a pull request. 
I am also closing this issue, but please let me know if you need any help.
