### ISSUE TITLE
Cura 2.1.2 - Allow to change to regular RepRap Gcode

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#919]
Right now you have to edit the .json definitions which is super user unfriendly (if you have selected an Ultimaker 2 printer). However there are valid use cases where an Ultimaker 2 user wants to have regular gcode and not Ultigcode.

**Comment by fieldOfView** [comment]
See https://github.com/fieldofview/machinesettingsactionplugin. We plan to include this plugin in Cura 2.2. It currently looks like this:
![machinesettings](https://cloud.githubusercontent.com/assets/143551/17582668/3e0dab6e-5fad-11e6-923c-f0803e3ba18e.png)

**Comment by fieldOfView** [comment]
For 2.1, you can add this machine definition to cura/resources/definitions:
https://gist.github.com/fieldOfView/ae85f755fc70d1c65e6968a870dfef0c

**Comment by nicolinux** [comment]
Perfect, thanks!
