### ISSUE TITLE
Scaling not correct if there are screens with different zoom setting

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#9194]
**Application version**
4.8

**Platform**
Windows 10 X64

**Printer**
Anycubic Mega S

**Reproduction steps**
In Windows Multi Screen environments it is possible to set different zoom levels for a single monitor. So e.g. for a small laptop screen 150% zoom is set. Simple set different Zoom levels and move Cura window from 1 screen to another. The size of text and dilogs is wrong then. Not all elements of Cura will be changed.

**Screenshot(s)**
![Bild 1](https://user-images.githubusercontent.com/51311453/106035326-4876a380-60d4-11eb-8097-8cddaa293333.png)

**Actual results**
Text of the Cura Windows no not at the correct size

**Expected results**
All window elements should be scaled correctly or at least Cura should never adapt to different setting of the zoom.

**Project file**
-

**Log file**
-

**Additional information**
-

**Comment by fvrmr** [comment]
Hi @NilsRo thank you. This is a known issue. I will discuss this with the team and I will let you know when I have more information.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
