### ISSUE TITLE
Retraction speed cannot be increased above 50mm/s with the SV-01 printer profile

### ISSUE THREAD

**Issue by Splic3dBread** [Ultimaker/Cura#9197]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Sovol SV-01

**Reproduction steps**
Using my printer's default profile, the retraction speed cannot be increased beyond 50mm/s without an error. I tested out a cr-10 and ender-3 profile on the same installation and didn't run into this problem.

**Screenshot(s)**
![screenshot](https://user-images.githubusercontent.com/37781046/106081860-a496f300-60e7-11eb-9bd5-009b05d4dbf2.PNG)

**Actual results**
Increasing the retraction speed beyond the default value results in an error.

**Expected results**
Increasing the retraction speed beyond the default value should not result in an error / failure to slice

**Project file**
n/a

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5884380/cura.log)

**Additional information**
n/a

**Comment by fvrmr** [comment]
Hi @Splic3dBread this is not a bug.
This is related to your printer definitions. We don't maintain the printer profiles for this printer. But you can change it yourself and even make a pull request if you want, so others can use it too. 

You can change the `maximum_value` for `retraction_speed` in this file: `SV01.def.json`
You can find that file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\definitions`

Please let me know if you need help or have more questions.

**Comment by Ghostkeeper** [comment]
The maximum value is by default the limit imposed by your firmware. Indeed it can't be increased beyond 50mm/s if the movement speed limit of the firmware is 50mm/s.

**Comment by Ghostkeeper** [comment]
This is not deferred because it's not an issue of priority. It's just an issue of that we can't change profiles for 3rd party printers since we don't have those printers.

**Comment by Oderik** [comment]
Is the maximum speed actually read from the firmware of the printer (if it's connected via OctoPrint) or is it just a configuration value that eventually reflects a firmware default?

**Comment by Ghostkeeper** [comment]
It's a configuration value. The people that make the printer definition files are expected to align it with what the firmware's default is.
People who edit their firmware can also edit it in the .def.json files or using the Printer Settings plug-in.
