### ISSUE TITLE
Feature Request: Multiple beds in the same project

### ISSUE THREAD

**Issue by aryez91** [Ultimaker/Cura#9205]
**Idea: Multiple beds at same project.**

**Why?**

Image you're preparing a big printing batch. and it doesn't fit in on go.
You would normally leave some meshes out of the bed, slice it, and for the remaining parts you either create a new project or you simply move those inside while taking the parts you already sliced out of the bed. That's great but could be better.

If you didn't save the first layout on a different file, in order to preview again you'd need to replace the parts again. slice. preview, or preview a gcode file.

But if you could have multiple bed regions inside the same project, your layout process, file management, your preview and troubleshooting could possibly become more elegant.

So instead of dragging those parts out of the bed into the unprintable void, you could drag them to a second bed, just besides the first one.

**With multiple beds you could:**
1. Slice & preview each bed by itself
2. Have an overview of the whole batch, make consistent settings adjustments if you like.
3. Could automatically pack many parts into multiple beds.
4. Copy-Paste settings from one bed to another.
5. Save in one file, for easier file management.
6. If you have a farm or few printers you could prepare a batch for all of them quicker.

Just crossed my mind...
Thanks a lot for all who contribute to this software.
Cheers.

**Comment by fvrmr** [comment]
Hi @aryez91 thank you for your feature request. 
Multiple beds was a feature we had in Cura 3.2.0 but we removed this, because to not many users used this feature. Also it is very complex with saving .3mf files. 
That's why I will close this issue and label it with won't fix/do, hope you understand.
