### ISSUE TITLE
[4.8.0] Skin Edge Support multiplied by Gradual Infill Steps

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#9210]
**Application version**
4.8.0

**Platform**
Win10

**Printer**
Any

**Reproduction steps**
1. Set Skin Edge Support Thickness to > 0 mm (enable)
2. Set Gradual Infill Steps to > 0 (enable)

**Screenshot(s)**
(Problem no visible in preview)

**Actual results**
Skin Edge Support has multiple passes. The number of extra passes is equal to value of "Gradual Infill Steps".
Example: if "Gradual Infill Steps" = 2, Skin Edge Support is printed 3 times in 1 layer (in same position), resulting in over extrusion.

**Expected results**
Skin Edge Support is printed once regardless of Gradual Infill Steps.

**Project file**
(none)

**Log file**
(none)

**Additional information**
Extra passes are in same position so the problem is not apparent in layer view, the slice needs to be simulated with bottom slider to see this bug.

**Comment by jellespijker** [comment]
We recently came across this bug and fixed it in master. It should be fixed for version 4.9. I will close this issue.

Devs see CURA-7115
