### ISSUE TITLE
can't slice model

### ISSUE THREAD

**Issue by tomohulk** [Ultimaker/Cura#9215]
**Application version**
4.8
**Platform**
Late 2017 MBP with the latest public version of BigSur 16GB of memory

**Printer**
Ender3, using the Klipper firmware

**Reproduction steps**
open model
slice model

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/52005101/106399925-8d0e8180-63e9-11eb-883a-bbdd27665a2d.png)

**Actual results**
just hangs and hangs during slicing.  I have sliced and printed many models with the settings selected.

**Expected results**
the model would slice for printing

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)
[CE3_Ender-3_Display_Cover_factory_srews_with_bell_closed.3mf.zip](https://github.com/Ultimaker/Cura/files/5900839/CE3_Ender-3_Display_Cover_factory_srews_with_bell_closed.3mf.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
couldn't find the log where it says it should be on MacOS.

**Comment by fvrmr** [comment]
Hi @tomohulk I need you .log file to see what is happening. 
Do you maybe use a VPN or have a firewall? Because it is possible that a Firewall or VPN is blocking it. See: https://github.com/Ultimaker/Cura/issues/9144
