### ISSUE TITLE
4.8 Modifiers not working when Print Sequence is set to One at a Time

### ISSUE THREAD

**Issue by PoiMechanic** [Ultimaker/Cura#9219]
Application version
4.6, 4.7, and 4.8

Platform
MacOS Catalina AMD Radeon Pro 5600M 8 GB
Intel UHD Graphics 630 1536 MB

Printer
Prusa mk3s

Reproduction steps
Models with a modifier (infill mesh, for overlaps) on it will print fine if the Print Sequence is set to One at a Time but as soon as you click All at Once the modifier settings no longer work and it shows in the preview.
I've tried stock profiles and everything else with no luck. Tried reinstalling and even going to older versions. Happens with any model or modifier settings.

In the attached pictures the modifier is puck shaped and on the bottom with a 100 percent infill setting.

Actual results
 Prints as if modifiers are not there. 

Expected results
I need to print multiple objects that are the same and have the same modifiers but one at a time. This works fine in Prusaslicer but I looooove Cura

**Additional information**
<img width="1383" alt="Screen Shot 2021-01-31 at 9 35 45 PM" src="https://user-images.githubusercontent.com/73767173/106415694-f5bb2580-640c-11eb-85af-13f4207fa2ee.png">
<img width="1335" alt="Screen Shot 2021-01-31 at 9 35 59 PM" src="https://user-images.githubusercontent.com/73767173/106415704-fc499d00-640c-11eb-97a6-787ed134ed9b.png">

[cura.log](https://github.com/Ultimaker/Cura/files/5901935/cura.log)

(Extra information relevant to the issue.)

**Comment by fvrmr** [comment]
Hi @PoiMechanic thank you for your report. 
If you group your models(the object and the modifier) it won't happen and it will print them one at a time. 

But I will discuss it with the team. Keep you posted.

**Comment by PoiMechanic** [comment]
@fvrmr Thank you so very much. I never knew about that option. This helps me with another problem too. Life saver

**Comment by Ghostkeeper** [comment]
Developers, please refer to issue CURA-8031.

**Comment by nallath** [comment]
This was fixed in https://github.com/Ultimaker/Cura/pull/11494
