### ISSUE TITLE
Cant select the model for modify or move or rotate IOS Big Sur 11.2

### ISSUE THREAD

**Issue by diegoboco** [Ultimaker/Cura#9239]
**Application version**
4.8.0

**Platform**
IOS BIG SUR 11.2

**Printer**
ENDER 3 PRO

**Reproduction steps**
1. All normal steps

**Screenshot(s)**
<img width="770" alt="Captura de Pantalla 2021-02-04 a la(s) 20 30 22" src="https://user-images.githubusercontent.com/76824716/106977193-daf7f200-6727-11eb-9728-6b2baae23522.png">

**Actual results**
When I upload a file I can't select it so I can modify it.

**Expected results**
That I can modify or move my models

**Project file**
I can save the model but just like it is uploaded

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fvrmr** [comment]
Hi @diegoboco thank you for your bug report.
It is a known issue, you can find it here: https://github.com/Ultimaker/Cura/issues/8745. That's why I will close this issue. 
We hope to have a solution soon.
