### ISSUE TITLE
Cura 4.8 adds additional support 

### ISSUE THREAD

**Issue by 3dparade** [Ultimaker/Cura#9242]
Hello,

we have a support issue on Cura 4.8.
The model is a tube-shape, with vertical wall, which should not be supported at all.
But Cura 4.8 is adding support columns around it. We have tried the support blocker solution,
but without any good result. In spite of the support blocker, the columns are still there.
![c2](https://user-images.githubusercontent.com/76786162/107028088-5c459800-67ad-11eb-91d2-b6fdcdbd6e27.JPG)
![c1](https://user-images.githubusercontent.com/76786162/107028091-5cde2e80-67ad-11eb-8ae5-953212c3cb4f.JPG)

Thanks for help in advance.
Gábor

**Comment by fvrmr** [comment]
Hi @3dparade could you share your project file? So I can have a look?

**Comment by 3dparade** [comment]
> Hi @3dparade could you share your project file? So I can have a look.
> Did you try to change the `support overhang angle` already?

Hi fvrmr,

thanks for reply. Yes, I have tried it... the support disappears if the value is 90, but in that case all support are gone, even
the needed one.

**Comment by fvrmr** [comment]
Can I take a look at your project file then?

**Comment by 3dparade** [comment]
[UM3_cura4.8_issue.3mf.zip](https://github.com/Ultimaker/Cura/files/5933511/UM3_cura4.8_issue.3mf.zip)

**Comment by fvrmr** [comment]
Ah, if you disable `use towers` your problem should be solved. 

![Screenshot (38)](https://user-images.githubusercontent.com/77000924/107056965-30d5a400-67d3-11eb-8988-54ed8b94a567.png)

I will close this issue, because there is a solution. Please let me know if it worked!

**Comment by 3dparade** [comment]
Perfect, thanks for prompt help!
