### ISSUE TITLE
New Request to reprint last print job at printer

### ISSUE THREAD

**Issue by rickj61** [Ultimaker/Cura#9243]
**Is your feature request related to a problem? Please describe.** No issue just frustrating to go to web (manage printers) to reprint when you are already at the printer to remove print previous print.
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

**Describe the solution you'd like**  Have option to print again (last print job). Much like after aborting you ask to reprint Yes/No
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

**Describe alternatives you've considered** Must manage printers from web page and reprint from history
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers** All users I would think would benefit from this feature
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by fvrmr** [comment]
Hi @rickj61 thank you for your feature request. I know the struggle. 
But I will have to defer this, because it is not on our priority list.
Hope you understand!
