### ISSUE TITLE
[4.8]Intermittent freezing Cura

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#9252]
**Application version**
4.8

**Platform**
Windows 10 64 bit 20H2 19042.746

**Printer**
Custom

**Reproduction steps**
1. Move an parts or just do nothing

**Actual results**
Sometimes i can see an freezing (~5-10 sec) an window Cura

[cura.log](https://github.com/Ultimaker/Cura/files/5939215/cura.log)

**Comment by fvrmr** [comment]
Hi @userosos thank you for your report. 
I looked into your log file but couldn't find anything.

Could you log out in Cura and see if that helps from freezing.

**Comment by userosos** [comment]
> 
> 
> Hi @userosos thank you for your report.
> I looked into your log file but couldn't find anything.
> 
> Could you log out in Cura and see if that helps from freezing.

Only the Cura window hangs. The system continues to work fine.

**Comment by fvrmr** [comment]
> Or did you mean logging out of your Cura account?

Yes I mean your Cura account!

**Comment by userosos** [comment]
> 
> 
> > Or did you mean logging out of your Cura account?
> 
> Yes I mean your Cura account!

I unlogged and just moved the part. It not helped.
[cura.log](https://github.com/Ultimaker/Cura/files/5943968/cura.log)

**Comment by Ghostkeeper** [comment]
I'm using the exact same laptop as you, so the hardware is not the problem.

**Comment by fvrmr** [comment]
I still couldn't find anything weird in your log file. So unfortunately I can't help you with this right now, because we can't reproduce this and can't find the problem. 
So we'll have to wait for others with this problem.

**Comment by userosos** [comment]
> 
> 
> I still couldn't find anything weird in your log file. So unfortunately I can't help you with this right now, because we can't reproduce this and can't find the problem.
> So we'll have to wait for others with this problem.

Ok. I think that ii some problem with an other software maybe.

**Comment by userosos** [comment]
Who can tell me how to diagnose the problem of frequent Cura hangs from third-party software/settings?

**Comment by Ghostkeeper** [comment]
If you suspect that other software is causing Cura to hang, the obvious way to test that would be to disable or shut off that software and see if the issue is resolved then.

Perhaps it helps to narrow down when exactly Cura freezes. Maybe it freezes after 10 seconds of inactivity? Maybe it freezes when you're starting a slice?

**Comment by userosos** [comment]
> 
> 
> If you suspect that other software is causing Cura to hang, the obvious way to test that would be to disable or shut off that software and see if the issue is resolved then.
> 
> Perhaps it helps to narrow down when exactly Cura freezes. Maybe it freezes after 10 seconds of inactivity? Maybe it freezes when you're starting a slice?

I noticed that it hangs every ~30-60 seconds.

**Comment by userosos** [comment]
I think it happens every 5-10 mouse clicks.

**Comment by Ghostkeeper** [comment]
Maybe it is the autosave? The symptoms are like that.

**Comment by userosos** [comment]
> Maybe it is the autosave? The symptoms are like that.

The autosave in Cura?

**Comment by fieldOfView** [comment]
Autosave saves preferences and setting changes to your configuration folder.

**Comment by userosos** [comment]
> Autosave saves preferences and setting changes to your configuration folder.

In the properties of the folder did not find autosaves.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
