### ISSUE TITLE
Load projects without overwriting printer config

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#9253]
*Is your feature request related to a problem? Please describe.*

I just found out that Cura overwrites the printer configuration when I open an old project and choose to also load the parameters.
Has anyone ever thought "When opening an old print I whished I could also load my old printer config from before all the upgrades I did to the printer since this project."?
Really. The printer configuration belongs to the printer and its current state and not to the print project. Loading a project should never overwrite the printer configuration.

BTW: Why does Cura when opening a project only give me these options:
- Import the models but ignore every parameter I tweaked for this print.
- Create a usually usable profile that I have to delete afterwards.
- Overwrite every setting in Cura that I changed since the time this project file was saved.

Why isn't there the option:
- Load the current version of the profile (by name) and temporarily update the values that I changed for the project. (Which means: Use the current version of the profile but use infill, shell, support, etc. that I adapted to this specific print.)

*Describe the solution you'd like*

My suggested option. I like to use the current version of the appropriate profile overlayed with the print specific changes like infill, support, cooling etc.

*Describe alternatives you've considered*

At the moment I have to choose to import only the models and then re-create the print specific settings. Any other choice could potentially break my printer since Cura loads old printer parameters with maximum positions and print head sizes that are no longer correct.

*Affected users and/or printers*
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

This behavior affects everyone who modifies his printer and sometimes wants to re-print something.

**Comment by fvrmr** [comment]
Hi @Triangulix thank you for your feature request.

Your request looks the same as #9000 that's why I will close this issue.
But I will discuss this topic again with the team. Keep you posted!
