### ISSUE TITLE
Holes in outer wall

### ISSUE THREAD

**Issue by drewlucas98** [Ultimaker/Cura#9257]
**Application version**
4.8.0
**Platform**
Windows 10 pro 64 bit with an rx5700xt

**Printer**
ender 3v2

**Reproduction steps**
1. try to print this https://www.thingiverse.com/thing:3612920
2. rotated object so that its flat side is facing down. 
3. sliced
4. top of the mount has gaping holes in the preview

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/13401164/107377145-9bfdde00-6b25-11eb-9de9-59fa97a1cd9b.png)
![Cura_FcGRf7COuC](https://user-images.githubusercontent.com/13401164/107377200-aae49080-6b25-11eb-878d-823a53cf1c55.png)

**Actual results**
same thing

**Expected results**
obviously it wouldn't have those holes in the preview

**Project file**
https://drive.google.com/file/d/1P3ROjtgEneVnVkWH4EbPZW9rrNXujGlh/view?usp=sharing

**Log file**
too hard dont have time for that

**Additional information**

**Comment by StuSerious** [comment]
@drewlucas98 I can't reproduce the issue on my Ender-3, but I would bet thatwhat you are seeing is the effect of excessive coasting!
Try to turn off '**Coasting**' or to reduce its volume [you can find the setting tree under the Experimental category].

If after turning off coasting it still has those gaps, can you please share your Project File? 
Thanks!

**Comment by fvrmr** [comment]
Hi @drewlucas98 I can't reproduce this either. This is how I slice it on a Ender 3. 

![Screenshot (48)](https://user-images.githubusercontent.com/77000924/107391956-807cde00-6af9-11eb-84b8-69fd25019529.png)

A project file would be helpful!
Disabling coasting is a good suggestion! Thanks @StuSerious
