### ISSUE TITLE
Cura stopped slicing my STL files from Fusion 360 last week. It was working great up until then. When I try to load to the SD card I get an error massage and the file ends with .ufp instead of g-code, but not on the SD card.

### ISSUE THREAD

**Issue by Jangbongo** [Ultimaker/Cura#9259]
**Application version**
(The version of the application this issue occurs with.)

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by fvrmr** [comment]
Hi @Jangbongo could you please fill in the form. And give us more information, screenshots, log file etc. 
So it's easier for us to understand and take a look at it.
