### ISSUE TITLE
Cura adds a new layer in my hollow object

### ISSUE THREAD

**Issue by nay0219** [Ultimaker/Cura#9262]
**Application version**
4.8.0

**Platform**
Windows 10 Home 64 Bit operating system, 16GB

**Printer**
Ultimaker S5

**Reproduction steps**
1. Uploaded STL file made from C4D. Printed with PVA.
2. Sliced--model is hollow when "Preparing" but once sliced, the "Preview" shows a new layer formed on the base of the design.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/78872640/107551930-df496280-6ba0-11eb-9597-7264d29cff66.png)
^^what i want it to look/print like (PREPARE stage). It's should be hollow inside.

![image](https://user-images.githubusercontent.com/78872640/107552017-fbe59a80-6ba0-11eb-88f8-1431a38cb115.png)
^^^ what it looks like after sliced. As you can see, there is a yellow layer on the bottom that wasn't visible in the PREPARE stage.

![image](https://user-images.githubusercontent.com/78872640/107552733-e4f37800-6ba1-11eb-9eaa-54fbc68b2dfd.png)
^^^how it actually printed. Thought that maybe the issue was the brim settings. But if I turn the Brim off, the layer still appears. It also is a pretty thick layer.

![image](https://user-images.githubusercontent.com/78872640/107552561-aa89db00-6ba1-11eb-941e-488d1c48a8ee.png)
^^^settings

**Actual results**
The lampshade prints with a layer on the wider end of the shade. Thought that maybe it was a brim issue and that I can maybe pop it off but once printed, there's a thick layer that cannot be cut/popped off. Even if I rotate the object 180 degrees on CURA the layer still shows up in the same location. It may be a model issue? 

**Expected results**
Should be hollow throughout. There should be no layer in between.

Here is the project file:

[lamp low poly.zip](https://github.com/Ultimaker/Cura/files/5966002/lamp.low.poly.zip)

**Comment by fvrmr** [comment]
Hi @nay0219 could you share your project file? So I can have a look at your model myself!

**Comment by nay0219** [comment]
> Hi @nay0219 could you share your project file? So I can have a look at your model myself!

[lamp low poly.zip](https://github.com/Ultimaker/Cura/files/5965998/lamp.low.poly.zip)

**Comment by GregValiant** [comment]
Cura didn't report any errors when opening the file but it doesn't typically make things up.  I think there were reversed faces 7.2mm tall at the bottom.  Service.Netfabb.com repair utility fixed them.  The attached is the repaired model from the STL so it isn't scaled the same as the 3mf was.
[lamp_low poly_fixed.zip](https://github.com/Ultimaker/Cura/files/5971849/lamp_low.poly_fixed.zip)

**Comment by fvrmr** [comment]
Hi @nay0219 could you let us know if the fix of @GregValiant works for you?
