### ISSUE TITLE
Cura Marktplatz

### ISSUE THREAD

**Issue by MeckyGT** [Ultimaker/Cura#9264]
Hallo,
At the cura Marketplace    Calibration Shapes     the Link in the left corner isn´t right.
And the Version is to day 1.0.9     not 1.07.
The change is very interesting because the is now the PETG Test Tower.
Thank you.

**Comment by nallath** [comment]
The link is something that @5axes needs to fix. The newer version of the plugin is still under review by us, but you can expect that to be released soonish.

**Comment by 5axes** [comment]
What is this link you're talking about?

**Comment by nallath** [comment]
@5axes I think he means this (there is a double https:// in there):

![image](https://user-images.githubusercontent.com/3922611/107660846-fcf1f700-6c88-11eb-9447-c1cee6be0eff.png)

**Comment by MeckyGT** [comment]
Yes that is what I meen.
--
Gesendet über myMail für Android Donnerstag, 11 Februar 2021, 04:49nachm. +01:00 von Jaime van Kessel  notifications@github.com :
