### ISSUE TITLE
Support Layer Height / Combine Support Layers Ever X Layers

### ISSUE THREAD

**Issue by Cortexian** [Ultimaker/Cura#9269]
In the interest of saving the most time possible, and speeding up overall print time, it would be excellent to have more refined control over the layer heights of different line types. We can already do this for Infill lines, but it would be excellent to have the option for support height as well!

Please add a setting under the "Support" section of Print settings for "Support Layer Height" or "Combine Support Layers Every X Layers". This would behave similar to different Infill layer heights, printing multiple perimeters and then printing a support layer at a taller support layer height.

The only alternative to this feature right now, is to use a different slicer.

Everyone will benefit from this, since less print time means more overall prints!

**Comment by fvrmr** [comment]
Hi @Cortexian thank you for your feature request.
We have already have a setting for this and that is `support layer infill thickness`.

I will close this issue because there is a fix for your request.
But please reach out if you have questions.
