### ISSUE TITLE
Cannot select models and prepare view and preview stop displaying content

### ISSUE THREAD

**Issue by jikometrix** [Ultimaker/Cura#9273]
**Application version**
4.8.0

**Platform**
Mac OS 11.2.1, Radeon Pro 455 2 GB

**Printer**
Ender 3 Pro

**Reproduction steps**
I keep have interface issue. First, there are times when Cura decides in the middle of setting up slicing to not display the prepare area models or printer limits. It will also do the same for the preview area, it will not display model or printer limits at random times. Quitting and restarting Cura fixes it for a short time. 

Second, If I leave Cura open for a while doing nothing, just open, it will loose the ability to select models. e.g. I open an STL to print, cura won't let me select it to move it or rotate it. All tools are grayed out. Quitting and restarting Cura fixes it for a short time. 

**Screenshot(s)**
nothing to show

**Actual results**
interface issues

**Expected results**
I should be able to view prepare are and preview without issue. I should be able to select models to apply tools to them.

**Comment by fvrmr** [comment]
Hi @jikometrix thank you.
This is a known issue. You can read more about it here: #8745 and on [our website](https://support.ultimaker.com/hc/en-us/articles/360018141480-Ultimaker-Cura-won-t-run-on-my-new-Macbook).
We hope to fix this soon. 

I will close this issue because it is a duplicate.
