### ISSUE TITLE
Ausgleich Filamentfluss

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#9280]
CURA 4.8.0
Die "Maximale Geschwindigkeit für Flussausgleich" wird beim Slicen nicht übernommen.
The maximum speed for flow compensation is not adopted when slicing.

**Comment by fvrmr** [comment]
Hi @lwbsbde could you please fill in the form and add screenshots, a project file and a log file. So we can help you properly.

**Comment by lwbsbde** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/43827576/108125211-71250400-70a8-11eb-834d-6596032b2282.png)

**Comment by fvrmr** [comment]
Hi @lwbsbde thank you for the screenshot. 
I will discuss it with the team if the maximum speed for flow doesn't affect the infill speed. 
Keep you posted.

**Comment by fvrmr** [comment]
Hi @lwbsbde I have to defer this issue. Because it is correct that the `maximum speed for flow equalization` doesn't affect the `infill speed`. 
Hope you understand. Please reach out if you have more questions.

**Comment by Ghostkeeper** [comment]
The Flow equalisation only affects the gap filling at the moment.
