### ISSUE TITLE
Print Preview after Slicing

### ISSUE THREAD

**Issue by benyetter** [Ultimaker/Cura#9281]
**Application version**  4.8.0
(The version of the application this issue occurs with.)

**Platform**  Win 10
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)

**Printer** HyperCube 300 and Taz 5
(Which printer was selected in Cura?)  Both

**Reproduction steps**
1. (Something you did.)  Nope
2. (Something you did next.)   Report the bug 

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
(What happens after the above steps have been followed.)

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

![image](https://user-images.githubusercontent.com/61129978/108103921-37c0aa00-7050-11eb-8f31-94c699967a20.png)

**Comment by jellespijker** [comment]
Please fill in the bug template as completely as possible and provide the log files / project file.
