### ISSUE TITLE
[4.8] Changes to nozzle size didn't saved

### ISSUE THREAD

**Issue by mykola-corgi** [Ultimaker/Cura#9286]
**Application version**
4.8

**Platform**
Windows 10 x64

**Printer**
Custom FFF Printer

**Reproduction steps**
1. Modify nozzle size for the machine in Machine Settings from 0.4 to 0.6.
2. Close menu
3. Back to the nozzle size settings

**Screenshot(s)**
![Cura_4_8_nozzle_size_bug](https://user-images.githubusercontent.com/63592057/108251944-bad12580-7160-11eb-8ce6-8d82dda03d04.gif)

**Actual results**
Nozzle size is still 0.4 

**Expected results**
Nozzle size is 0.6

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5997878/cura.log)

**Comment by fieldOfView** [comment]
Try using a comma instead of a dot. This has been fixed in the next version of Cura.

**Comment by mykola-corgi** [comment]
Thanks, comma works like a charm
