### ISSUE TITLE
[Ironing] move nozzle to edge after finishing

### ISSUE THREAD

**Issue by Tinkot** [Ultimaker/Cura#9296]
after ironing, the nozzle retracts on the ironed area. resulting in a bad spot at the surface.
it would be better if the nozzle could move out of the ironed area before retracting.

You can replicate this by slicing benchy with Concentric and line space 0.3

**Comment by fvrmr** [comment]
Hi @Tinkot thank you for your feature request. 
Could you please fill in the form correctly. See the topics you need to fill in here below.

> **Is your feature request related to a problem? Please describe.**
> (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
> 
> **Describe the solution you'd like**
> (A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)
> 
> **Describe alternatives you've considered**
> (A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)
> 
> **Affected users and/or printers**
> (Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
> 
> **Additional context**
> (Add any other context or screenshots about the feature request here.)

That helps us to understand your feature request and look into it.
