### ISSUE TITLE
slowly raise temperature based on mass

### ISSUE THREAD

**Issue by shimondoodkin** [Ultimaker/Cura#9300]
<img src="https://support.ultimaker.com/hc/article_attachments/360009279100/How_to_fix_warping_Warping_model.jpg" width="300">

**Is your feature request related to a problem? Please describe.**
a large print gets separated from the bed and wraps at the edges.

although there is a pid for temperature it is in the middle. so center heat is maintained but edges get cold.  

from my best understanding, the large part works better as a heat sink and dissipates temperature from the bed better.
so as the print gets larger, the bed becomes cooler at the base and especially the edges. 

**Describe the solution you'd like**

I think, if the bed would be a little hotter it will still be ok.

the solution is to raise the temperature slowly. to maintain the temperature at the edges.

put in gcode commands to set bed heat to wanted bed temperature at certain percentages like every 10%.. or every x mass add.  

- to calculate wanted bed temperature:
  - heat lost from the heatsink = temperature at bed center - temperature at edges after heatsink heat transfer.
  - wanted bed temperature= base temperature + heat lost from the heatsink.

maybe the next step is to automate it based on the material library.

**Describe alternatives you've considered**

- a sophisticated solution is 
  - to calculate based on material heat conductivity. maybe there is some code to calculate 3D object heat transfer. and take probably the lowest temperature of the bottom layer, probably at the edges.
- simple solutions:
  - to raise the temperature based on percentage and a temperature curve may be based on mass or manual chart.  this could be estimated using manual measurements.
  - to raise the temperature based on percentage and a range.
  - just suggest higher global temperature. for larger mass. not sure if it will work.

**Affected users and/or printers**
everyone with an FDM printer will benefit from this.

**Additional context**

**Comment by fvrmr** [comment]
Hi @shimondoodkin thank you for your feature request.
I really like the idea you have. I will discus this with the team. Keep you posted. 

And for next time, please fill in our form correctly, that helps us to understand feature request better.

**Comment by shimondoodkin** [comment]
thank you for liking the idea.

a possible build up for the idea for the nozzle too, probably insignificant though:

a hypothesis: maybe the model also takes heat from the nozzle. but it is only a hypothesis, should be checked.

last time I printed a 50g petg box of 2mm shell, with 3x7x15hmm sticks at top and bottom.  I noticed stress in the print. the sticks at top were more brittle and broken more easily, but I can't blame for sure that the reason was stress in the print. 

a guess is maybe it is because of dragging a cold melted filament from the nozzle and stretching it.

**Comment by fvrmr** [comment]
Hi @shimondoodkin thanks for the reply.
But I have to reject this issue. I have discussed it with the team and we agreed that this is more depending on the printer settings.
And adding this feature would also be very difficult to understand for other users and probably not many users will use this.

A few work around you can use to avoid warping are: 
- Better adhesion, something like tape or glue.
- Printing with a brim or raft.
- Change `top/bottom pattern` to `concentric`. 

Please feel free to reach out if you have more questions.
