### ISSUE TITLE
[4.8.0] Per model infill override affects other model

### ISSUE THREAD

**Issue by mulder999** [Ultimaker/Cura#9306]
**Application version**
4.8.0

**Platform**
Win 10x64 v1909

**Printer**
AnyCubic i3 Mega S

**Reproduction steps**
1. Load a 3MF file with at least 2 parts
2. Ungroup model, you now have 2 parts: A and B
3. Choose 15% infill ratio with cubic subdivision (global setting)
4. Set 100% infill ratio for part B (per model setting)
5. Slice

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/1905023/108625843-55758100-744d-11eb-8986-8d7156ee6ef9.png)

**Actual results**
* Part A uses about 90% infill / triangle subdivision (WRONG)
* Part B uses 100% infill

**Expected results**
* Part A uses 15% infill / cubic subdivision
* Part B uses 100% infill

**Project file**
[PerModelInfillBug.zip](https://github.com/Ultimaker/Cura/files/6017730/PerModelInfillBug.zip)

**Comment by smartavionics** [comment]
A workaround is to use a different infill pattern for part B, e.g. lines.

**Comment by smartavionics** [comment]
As far as I can tell, this bug is specific to the cubic-subdivision infill pattern as you can use other patterns OK.

**Comment by smartavionics** [comment]
Yes, I looked at the code and it appears that it can only support a single density of cubic-subdivision infill so all objects that use that infill pattern must use the same density.

**Comment by mulder999** [comment]
Indeed, the workaround is working, for eg cubic infill works as intended. Only cubic-subdivision seems affected.

**Comment by fvrmr** [comment]
Hi @mulder999 thank your for your bug report. 
Thank you @smartavionics for suggesting the work around and that this works for you. But I will discus this with the team.
Keep you posted.

**Comment by fvrmr** [comment]
Hi @mulder999 I have discussed it with the team. Cubic subdivision isn't used by that many users, so it is not a priority for us right now. And because there is a work around I will defer this issue for now. 
Hope you understand.
