### ISSUE TITLE
Stuck at prepare Slice

### ISSUE THREAD

**Issue by TYR3D** [Ultimaker/Cura#931]
Once object was dropped in. It prepared the slice but when I rotate any way it then just says preparing slice but nothing happens

**Comment by Ghostkeeper** [comment]
In 2.1, there is a known bug that it gets stuck in Preparing to Slice sometimes when you use one-at-a-time mode.

In the current master, it seems to get stuck in preparing to slice sometimes if you interrupt the slicing process while it is already preparing to slice.

**Comment by TYR3D** [comment]
Hi just to let you know it happen in all at once mode too.
Thanks

**Comment by nallath** [comment]
I'm working on this issue as we speak. It's a nasty one, as it also behaves differently on different operating systems.

**Comment by TYR3D** [comment]
when placing the item on the bed and rotate it some times it bounces all over the place and disappears as well need to then turn of and reboot. Might have something to do with that too?

**Comment by Ghostkeeper** [comment]
Happens a lot with printing bouncy balls out of flex materials, I've heard :laughing:

No but the bouncing is also a known issue. It seems to happen more with combinations of large and small objects on the build plate, but we haven't really analysed it yet.

**Comment by nallath** [comment]
Yes we did. I just made a fix for that :) Not sure if it solves all cases though.

**Comment by robygladio** [comment]
[SOLVED] On WINDOWS 10 64 bit just execute in compatibility mode windows 8 
I flag also Run As Administrator for both cura and curaengine.exe
Now work again

**Comment by sedwards2009** [comment]
@robygladio Does it work now using compatibility mode but *not* using admin rights?

**Comment by sedwards2009** [comment]
@robygladio Does it work now using compatibility mode but *not* using admin rights?

**Comment by robygladio** [comment]
@sedwards2009   
I use admin rights  too. 
both cura and curaengine.exe set as compatibility win 8 and admin rights.
Just the dual extrusion get crash if set as 1. leaving dual extrusion to 0 it work fine

**Comment by mokusolo** [comment]
I had the similar problem when using 2.1.2 with win8. To test,the stl file size is nearly 57M.
I would appreciate that if anyone can tell me how long the normal time it costs when"preparing to slice".
Does it relate to file size/transmission speed from cura to curaEngine(I'm not sure if there's transmission)?
Thanks a lot anyway.

**Comment by fieldOfView** [comment]
The "preparing to slice" stage should not take too long. For small objects you should not really see it much if at all. Highly detailed objects may take longer, but I would say that if it takes more than tens of seconds, something is wrong.

Important question: is the model yellow or grey? If it is grey, Cura thinks it does not fit in the buildvolume and does not slice it.

**Comment by Ghostkeeper** [comment]
Preparing to slice is indeed 99% the transmission towards CuraEngine. There's a few other checks such as which meshes to slice (only those in the build volume), what order to print in one-at-a-time mode, and a few tiny things.

Cura 2.1 had a bug where it would sometimes still try to slice, and get stuck in preparing to slice, even if the model was grey.

**Comment by thopiekar** [comment]
@TYR3D Is that problem still existing on Cura 2.3?

**Comment by TYR3D** [comment]
Seams to be gone. Found my self now using other slicers a little more as it is still too unstable
