### ISSUE TITLE
Cura won't slice when assigning stls to Extruder 2 and 3 and disabling Extruder 1 (T0)

### ISSUE THREAD

**Issue by Soureaver666** [Ultimaker/Cura#9322]
**Application version**
Cura 4.8.0

**Platform**
Windows 10 64bit 1909

**Printer**
Custom FFF Printer with 3 tools

**Reproduction steps**
1. set support and buildplate adhesion extruder to extruder 2
2. disable extruder 1
3. load both bi-color benchy .stl files from https://www.thingiverse.com/thing:763622 into Cura
4. assign extruder 2 to one .stl (should be already predefined here) and extruder 3 to the other one
5. merge models

**Actual results**
merged model gets shaded and becomes "unable to slice"
![slicing error when extruder 1 disabled](https://user-images.githubusercontent.com/33988636/108982185-d1f6a280-768d-11eb-9577-2c54822ee77b.PNG)

when enabling extruder 1 (T0) again -> slicing works

I guess this behavior results from automatically inserting and also pre-heating "T0" when pre-heating the print bed at the start of the print. 
I don't use any start scripts and as stated, support and adhesion extruder are changed to T1 and thererfore, there is no reason for upper behavior?

**Expected results**
model should be slice-able with extruder 1 disabled

**Project file**
![dualprint-benchy_error.3mf.txt](https://github.com/Ultimaker/Cura/files/6035005/dualprint-benchy_error.3mf.txt)

just remove .txt ending

**Comment by fvrmr** [comment]
Hi @Soureaver666 thank you for your bug report. 
I can reproduce this to. Will discuss this with the team. Keep you posted.

**Comment by fvrmr** [comment]
We have discussed it with the team. And can also reproduce this with a dual extrusion, we've created a ticket on our backlog.
Developers see CURA-8054
