### ISSUE TITLE
Exclude the extra skin walls from "Small feature speed"

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9324]
**Is your feature request related to a problem? Please describe.**
Enabling small feature speed is great for printing small holes and threads and minis but a side-effect is that expanded skin is reduced in speed as well, increasing printing time dramatically for certain geometries. 

**Describe the solution you'd like**
Make the setting only affect inner and outer walls.

**Affected users and/or printers**
Anyone

**Additional context**
![Exclude small feature speed from expanded skin](https://user-images.githubusercontent.com/32172100/109001176-e8f4bf00-76a4-11eb-9a29-bb6011059448.PNG)

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your feature request.
I will discuss this with the team. Keep you posted!

**Comment by fvrmr** [comment]
We have discussed it and this feature request is on our backlog now. 
Developers see CURA-8052.

**Comment by printingotb** [comment]
Thanks a lot 🙂

**Comment by fvrmr** [comment]
Closing this issue because it has been removed from the backlog. We understand the need of it, but don't see anytime to work on this anytime soon.

**Comment by fvrmr** [comment]
Changing the status to defer instead of won't fix/do because we do not have the time to work on it, some one else is always welcome to work on this and create a pull request.
