### ISSUE TITLE
Layer view not showing up on Apple M1

### ISSUE THREAD

**Issue by ManyBaby** [Ultimaker/Cura#9336]
Everything is in the video

https://www.loom.com/share/dd94d8d6ef4d45778c036b5fea98c75b

**Comment by jellespijker** [comment]
We still need log files.

**Comment by rafaljot** [comment]
Everything works on Apple M1 except layer preview.
Fortunately it works with "Force layer view compatibility mode" but old-fashioned.

**Comment by rafaljot** [comment]
Now it woks. I can't reproduce this issue. Last think a made was turn on, restart, turn off "Force layer view compatibility mode" , restart.

**Comment by ManyBaby** [comment]
@rafaljot Thank you it works for me too now
@jellespijker I close the issue
Thanks to all the team behind this wonderful software
