### ISSUE TITLE
Change angle of first layer after supporty

### ISSUE THREAD

**Issue by loggyboy** [Ultimaker/Cura#9338]
My first layer after a support structure is a fixed angle (appears to be about 10 degrees). I cannot find any setting to adjust the angle, or pattern that this initial layer is. General shell settings do not affect this one layer.
Layer 72, shows last layer of support. (concentric)

![image](https://user-images.githubusercontent.com/46853692/109368666-c378d880-7891-11eb-9fed-3edebddefff4.png)

Layer 73 shows first layer of shell after support - I cannot find a way to adjust this layer.

![image](https://user-images.githubusercontent.com/46853692/109368686-d25f8b00-7891-11eb-96be-fdf02cf4bf8c.png)

Layer 74 shows 2nd layer of shell, this is affected by shell setting of direction and pattern. (lines, 45deg)

![image](https://user-images.githubusercontent.com/46853692/109368747-0aff6480-7892-11eb-9036-c810b267f5e6.png)

**Comment by fvrmr** [comment]
Hi @loggyboy thank you for your feature request. Could you provide us more information, why is this better and what will affect this and a project file, so I can take a closer look.

**Comment by Ghostkeeper** [comment]
Looks like it's just bridging. Adjusting the Bridge Skin Support Threshold should allow you to tune it better.

**Comment by loggyboy** [comment]
> Looks like it's just bridging. Adjusting the Bridge Skin Support Threshold should allow you to tune it better.

Bridge was switched off (was only in experimental so hadnt looked at this). However turning this on has now aligned the first layer with the others so I will play around with these settings. Thanks.

**Comment by fvrmr** [comment]
I will close this issue, since this is solved by enabling the bridge settings. 
But please feel free to reach out if you have more questions.

**Comment by Ghostkeeper** [comment]
Counterintuitively, bridging can only be turned off by enabling the setting to get more bridging settings, then setting those bridging settings such that bridging is effectively turned off.
