### ISSUE TITLE
Resize/Scale giving incorrect percentage

### ISSUE THREAD

**Issue by 8biten** [Ultimaker/Cura#934]
When I try to resize a file I created in Pro/E - it gives incorrect percentages, such as 700 or 1000+ on an axis.  Upon exiting, the object is huge.  Doing an undo/ctl-Z will then bring the object to the correct (intended size after resize) size.  
<img width="796" alt="cura_2 1 2_scale_issue" src="https://cloud.githubusercontent.com/assets/18336391/17821175/40fa722c-661e-11e6-96b1-9d8d33436a2d.png">
[stl_file.zip](https://github.com/Ultimaker/Cura/files/427704/stl_file.zip)

**Comment by nallath** [comment]
We re-did a bunch of code that has to with scaling for 2.2, which will be released soon.

**Comment by Ghostkeeper** [comment]
You're doing a uniform rescale?

The percentages look fine in comparison with the dimensions it reports. The mesh is only 4mm wide in the Y-direction. If it's not doing a uniform rescale while you had the uniform scaling activated, then we probably already fixed that just after 2.1 was released when we fixed a lot of things with scaling.

**Comment by 8biten** [comment]
Hmm, I did rotate it first.  It is not 4mm wide - it is 4mm tall.  (it was on it's side in the STL file).

**Comment by nallath** [comment]
This is probably fixed already.
