### ISSUE TITLE
Slicing errors in version 4.8

### ISSUE THREAD

**Issue by jornada812** [Ultimaker/Cura#9341]
version 4.6.2
![2021-02-27_14-33-00](https://user-images.githubusercontent.com/32206704/109386003-c4008600-7908-11eb-9d98-7bae606c7708.png)

version 4.8 with imported profile from 4.6
![2021-02-27_14-38-59](https://user-images.githubusercontent.com/32206704/109386110-9a942a00-7909-11eb-80b3-59608efe27b3.png)

version 4.8 
![2021-02-27_14-41-07](https://user-images.githubusercontent.com/32206704/109386169-ee067800-7909-11eb-8b3e-c254dccbb5c2.png)
default profile 0.1 

stlmodel - https://yadi.sk/d/kEV_49wS19pz-Q
profile from version 4.6 - https://yadi.sk/d/T2zzspP_aYvb0w

**Comment by GregValiant** [comment]
Can you post the STL here?  I don't install software just to download a file.

**Comment by jornada812** [comment]
What software do you not want to install? These files are available for saving by link. any whim of yours

**Comment by GregValiant** [comment]
That was my bad.  There was a popup over the download button and all I noticed was "Install yanex".

**Comment by jornada812** [comment]
I close the task. This defect occurs when the function of "Coasting" is active, which for some reason is enabled by default in the experimental section

**Comment by GregValiant** [comment]
Did you have Coasting enabled?  If you have the preview set to show extrusions there is no extruding during a coast so there are no lines there.  In the profile though, coasting was off.  When I turned it on, the preview looked like your screen shots.

**Comment by jornada812** [comment]
in profile 4.6 the coasting was turned off, I never used it. But after importing to 4.8 for some reason it's included. And in all profiles by default in version 4.8 it is also enabled for some reason.

**Comment by Ghostkeeper** [comment]
Since you didn't fill in the template, I can't check if people changed the default profiles for your configuration.

It could also be that you loaded in a project file or a profile from someone else that enabled the setting?

**Comment by jornada812** [comment]
Well, it doesn't matter anymore, the main thing is that the reason is found
