### ISSUE TITLE
Nozzle diameter change is not saved in the printer profile

### ISSUE THREAD

**Issue by jornada812** [Ultimaker/Cura#9342]
![2021-02-27_14-45-35](https://user-images.githubusercontent.com/32206704/109386267-a0d6d600-790a-11eb-8344-621c7847dd42.png)

and the default config file (in my case predator_extruder_0+%232_settings.inst.cfg) does not contain a parameter machine_nozzle_size,  i have to add it manually

**Comment by fvrmr** [comment]
Hi @jornada812 thank you. I am not familiar with Anycubic printers. When I add a Anycubic printer in Cura the nozzle size is 0.4 mm. We don't maintain the config files for these printers, so if it needs to be changed by a pull request.

Please let me know if this is the case, if not could you provide me your config file and more information.
Thank you in advance.

**Comment by jornada812** [comment]
I didn't understand your answer. In any printer, the user can change the
nozzle. Put 0.3, 0.6 or any other value. The interface does not allow you
to remember the new nozzle in any printer model, even branded, even custom.
I suggest you fix it or describe the algorithm, as I can do it in the
interface. This error moves from version to version. Sometimes they write
that it was fixed, but it comes back again

пн, 1 мар. 2021 г., 14:16 Fenne <notifications@github.com>:

**Comment by fieldOfView** [comment]
Try entering the value with a comma instead of a dot.
This has been fixed for Cura 4.9

**Comment by jornada812** [comment]
> Try entering the value with a comma instead of a dot.
> This has been fixed for Cura 4.9

It works. thank
