### ISSUE TITLE
Conical support leaves towers all the way down

### ISSUE THREAD

**Issue by RafaeleValanten** [Ultimaker/Cura#9343]
**Application version**
4.8

**Platform**
Windows 10

**Printer**
Cr10s5 creality

**Reproduction steps**
1. Recently i uploaded one stl , and in the preview i saw a strange supports line made its way to the corner of the model. 
![Screenshot_2021-02-27-20-04-41-703_com google android apps photos](https://user-images.githubusercontent.com/79719957/109392706-122c7e00-7937-11eb-8647-904589e749b2.jpg)
![Screenshot_2021-02-27-20-04-53-615_com google android apps photos](https://user-images.githubusercontent.com/79719957/109392709-13f64180-7937-11eb-96c7-622404352193.jpg)

2. Then i created in cad two simple cubes , both were with internal geometry so that cura could generate supports under the top of them , with only one difference, one was with two open sides. ( but it didn't matter) And supports were good with them.
3. Next step was , i tried my first model again with standart cura profile. And there was no an issue. After that i switched on conical supports, set them to 45° with the rest default. And there was all fine, proper structure.
4. Finally in the standard cura profile i changed the Supports overhang angle to 55° as in my profile and here was the bug hiding: )) in the images below u can see the differences and how this bug jumps from one to another model by changing the ° . It didn't affect only left  one cube with only one open side beneath it. 

**Screenshot(s)**
![Снимок экрана 2021-02-27 171418](https://user-images.githubusercontent.com/79719957/109393069-2d988880-7939-11eb-8ae4-a9513cc7d549.jpg)
![Снимок экрана 2021-02-27 171534](https://user-images.githubusercontent.com/79719957/109393073-30937900-7939-11eb-97d2-dc919d94d494.jpg)
![Снимок экрана 2021-02-27 171600-1](https://user-images.githubusercontent.com/79719957/109393075-325d3c80-7939-11eb-9673-7df8d8f7bfd8.jpg)
![Снимок экрана 2021-02-27 171735](https://user-images.githubusercontent.com/79719957/109393076-338e6980-7939-11eb-83f7-9b693b9e3abd.jpg)

**Actual results**
The suppors weird wall still appears in different ° of the Suport overhang angle.

**Expected results**

**Project file**
[CCR1_St_400gr.zip](https://github.com/Ultimaker/Cura/files/6056436/CCR1_St_400gr.zip)

**Additional information** 
So, use standard profile, then activate conical supports and set supports overhang angle over 40-59°

**Comment by jellespijker** [comment]
You have peeked my curiosity. I would love to see that weird support behaviour. Does it dance, time travel or maybe it turns into cheese?

Please fill in the issue template and provide log files and project files.

**Comment by jellespijker** [comment]
Thank you for filling in the issue report. Could you also add the project file.

**Comment by RafaeleValanten** [comment]
> Thank you for filling in the issue report. Could you also add the project file.



> Thank you for filling in the issue report. Could you also add the project file.

may i ask what else should i paste? the status sais that "needs info"

**Comment by jellespijker** [comment]
My apology, I overlooked the project file. I think this should be enough information for us to investigate further.

FYI @fvrmr

**Comment by fvrmr** [comment]
Thank you @RafaeleValanten, is this behaviour failing your print? 
I am able to reproduce this, so I will discuss this with the team. Keep you posted.

**Comment by RafaeleValanten** [comment]
> Thank you @RafaeleValanten, is this behaviour failing your print?
> I am able to reproduce this, so I will discuss this with the team. Keep you posted.

Actually not.. It is only makes blobs on the outer wall in places where this supports line approaching the outer wall , cz i set till 5 mm no retraction.

**Comment by fvrmr** [comment]
Hi @RafaeleValanten I have discussed it with the team. And we have to defer this issue, because conical support is in experimental mode it is not a priority for us right now. Hope you understand.
