### ISSUE TITLE
Coasting Inconsistent with 1 Wall

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#9344]
4.8 / Win10 x64

When trying to make a hollow cylinder with one wall, coasting is only triggered on some of the layers:

![image](https://user-images.githubusercontent.com/12439543/109398728-2c009d80-7904-11eb-8113-e80408d9292e.png)

Add a second wall and it triggers on every layer:

![image](https://user-images.githubusercontent.com/12439543/109398733-33c04200-7904-11eb-9582-dc1d02f1693e.png)

[UMO_Circle2.3mf.txt](https://github.com/Ultimaker/Cura/files/6063762/UMO_Circle2.3mf.txt)

**Comment by fvrmr** [comment]
Hi @CCS86 thank you for your bug report. 
Did you try to enable to the surface mode? If that doesn't work for you, could you please share a project file (file - save project) then I can try to reproduce your problem.

**Comment by CCS86** [comment]
I have not tried surface mode, but the project is at the bottom of the original post.

**Comment by fvrmr** [comment]
Hi @CCS86 can you let me know if that works for you. If not share a project file, because that file is also just a 3mf file.

**Comment by CCS86** [comment]
Sorry about that. I must have chosen export. See if this works:

[UMO_Circle2.3mf.txt](https://github.com/Ultimaker/Cura/files/6063762/UMO_Circle2.3mf.txt)

**Comment by fvrmr** [comment]
Thanks, I am also able to reproduce this. 
Will also discuss this with the team. Keep you posted.

**Comment by Ghostkeeper** [comment]
We discussed this with the Cura team and found it worthy to give this some priority. We couldn't reproduce this with different models but there's a chance that it happens with other models as well. While the coasting feature isn't used a whole lot (at least not on purpose) we also don't think that this is all too difficult to fix in general. @konskarm don't forget to create a ticket in Jira!

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
