### ISSUE TITLE
1. to be able to move filament in extruder

### ISSUE THREAD

**Issue by VladekRo** [Ultimaker/Cura#9352]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by fvrmr** [comment]
Hi @VladekRo please fill in the form correctly for your feature request. Otherwise we don't know what you exactly want. 
Thank you in advance.
