### ISSUE TITLE
Please include layer by layer preview in "monitor" while printing via USB

### ISSUE THREAD

**Issue by RaminShalom** [Ultimaker/Cura#9355]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)

**Additional context**
(Add any other context or screenshots about the feature request here.)

**Comment by RaminShalom** [comment]
While printing via USB & in the "Monitor" window, please include the layer by layer preview

**Comment by fvrmr** [comment]
Hi @RaminShalom please fill in the form. So we can understand what you exactly want.
Thank you in advance.

**Comment by RaminShalom** [comment]
I would like to see a layer by layer graphical representation of the object while being printed via USB

**Comment by fvrmr** [comment]
Why would you want this? Is this related to a problem? See the form below for the questions we need before discussing this with the team. 

> Is your feature request related to a problem? Please describe.
> (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
> 
> Describe the solution you'd like
> (A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)
> 
> Describe alternatives you've considered
> (A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)
> 
> Affected users and/or printers
> (Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
> 
> Additional context
> (Add any other context or screenshots about the feature request here.)

**Comment by Ghostkeeper** [comment]
I think he means something like this? https://github.com/Ultimaker/Cura/issues/6020

**Comment by RaminShalom** [comment]
Absolutely correct,

 

The gcode can be translated to the visual representation as the print progresses.

**Comment by fvrmr** [comment]
As you can see in that thread we've decided to defer this issue. Because we don't support USB printing on our printers anymore. 
A pull request is always welcome off course. 
Hope you understand.
