### ISSUE TITLE
Calculation of number of bottom layers.

### ISSUE THREAD

**Issue by mpoling2016** [Ultimaker/Cura#936]
When bottom layer thickness is set to 1 and layer height is 0.04, the number of bottom layers calculates to 999999.
I'm no mathematician but I don't think that's quite right.

**Comment by fieldOfView** [comment]
Try setting the infill to anything but 100%. The number of bottom layers is actually set to that high number to get a solid object that does not consist of a shell and infill.

**Comment by mpoling2016** [comment]
Yup, that worked.

**Comment by Ghostkeeper** [comment]
For reference, we set the bottom/top layer count to 999999 when you have 100%, because in practice the infill works better that way. You get an infill density closer to 100% than when you'd use the infill algorithms to fill 100%.
