### ISSUE TITLE
Slams shut on "Eject"

### ISSUE THREAD

**Issue by FlailAway** [Ultimaker/Cura#9375]
### Application Version

Arachnid

### Platform

Mint 20.1+Cinnamon

### Printer

Custom

### Reproduction steps

Slice
Clicked "Save to removable"
Clicked "Eject"

### Actual results

Slammed shut back to desktop.

### Expected results

Stay where it was, but close the "Eject" Dialog as I may want to continue slicing other stuff.

**Comment by fieldOfView** [comment]
Duplicate of https://github.com/Ultimaker/Cura/issues/9057

**Comment by konskarm** [comment]
We just released the 4.9 beta. @FlailAway can you give it a try to see if the issue persists? So far we haven't been able to reproduce it in the 4.9 beta release.
