### ISSUE TITLE
Arrange without rotate

### ISSUE THREAD

**Issue by rophiroth** [Ultimaker/Cura#9382]
### Is your feature request related to a problem?

Yes, since 4.8 arrange rotate objects, and for some proyects thats not optimal

### Describe the solution you'd like

option to disable auto rotation

### Describe alternatives you've considered

no necessary 

### Affected users and/or printers

cura v4.8

**Comment by fvrmr** [comment]
Hi @rophiroth this is a duplicate of #8860 
We have a ticket on our backlog for this. 
Developers see CURA-7951

**Comment by rophiroth** [comment]
This issue dont have anything to do with #8860 ! please help.
