### ISSUE TITLE
Arachne - Hard upper limit on extrusion width

### ISSUE THREAD

**Issue by Erichrandfor** [Ultimaker/Cura#9384]
### Application Version

Arachne _Engine_Alpha

### Platform

Windows 10

### Printer

Ultimaker 2+

### Reproduction steps

1. Set Line Width to anything greater than or equal to 1mm. 
2. Slice

### Actual results

No G-code produced, progress bar stays blank (presumed failure to slice)

### Expected results

A toolpath mainly consisting of 2x 1mm thick walls.

1mm definitely seems to be the hard limit. 0,999mm line width slices succesfully. 

[UM2_testbox.zip](https://github.com/Ultimaker/Cura/files/6122555/UM2_testbox.zip)

**Comment by nallath** [comment]
I've just tried this on the latest version of Arachne (which we will release really soon!), and it even slices with line widths of 2mm

![image](https://user-images.githubusercontent.com/3922611/110780815-6acc1700-8265-11eb-9345-c950662a9652.png)
