### ISSUE TITLE
When setting a distance between prints it is ignored when doing a duplicate print

### ISSUE THREAD

**Issue by wwendorf** [Ultimaker/Cura#9391]
### Application Version

3.6.0

### Platform

Windows 7

### Printer

Creality Print Mill

### Reproduction steps

Tried to print a repeating part and set the spacing to 300mm and it was ignore and stuck with the default 20mm.

### Actual results

Part started to repeat after 20mm

### Expected results

Part should have started to repeat after 300mm

Parts are not being spaced by 300mm as I am inputting, rather 20mm.

**Comment by fvrmr** [comment]
Hi @wwendorf thank you for your report.
Unfortunately this is something we don't maintain, because we don't use this in Cura. 
See this repository of Blackbelt https://github.com/BlackBelt3D/Cura

I will close this issue, hope you understand.
