### ISSUE TITLE
Raft in Layers View draws on last layers vs first layers.

### ISSUE THREAD

**Issue by opensourcefan** [Ultimaker/Cura#941]
This is a bit strange. It happens to me on 2.1.2 on Ubuntu 14.04 and 2.1.3 on Windows 10. (Haven't tried it elsewhere) 

When Raft is selected and when I'm in Layer View the raft appears on the last layers and not at the very beginning where it obviously should. I'm scared to actually try and print anything with it just in case it decides to actually print the raft after the whole model is printed. Is this just me?

**Comment by fieldOfView** [comment]
I would guess that this is a visualisation issue only. I don't see it with Cura 2.2 which we are working on at the moment, so the visualisation issue has been fixed.

If you want to be triple-sure, load the gcode into the old Cura and use that to inspect the gcode.
