### ISSUE TITLE
very weird slicing

### ISSUE THREAD

**Issue by IxyR4** [Ultimaker/Cura#9416]
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Sliced model with settings for PETG

### Actual results

VERY weird layer making, see files.

### Expected results

I was expecting a normal slice.

![image](https://user-images.githubusercontent.com/44159774/111612707-074e6600-87de-11eb-8447-701174e7d9d1.png)
![image](https://user-images.githubusercontent.com/44159774/111612797-20efad80-87de-11eb-9918-4210348fb4d6.png)
![image](https://user-images.githubusercontent.com/44159774/111612754-17664580-87de-11eb-89ef-56cfe232a782.png)
![image](https://user-images.githubusercontent.com/44159774/111613060-690ed000-87de-11eb-937f-2bc054d00938.png)

SCREENSNAPS

CURAPROFILE
[https://drive.google.com/file/d/10tLTnR1bQ4zuh3NnkHA9MocZa_dQRTJs/view?usp=sharing](url)

**Thank you for help
//IxyR4**

**Comment by IxyR4** [comment]
And it slices fine with my PLA settings

**Comment by fvrmr** [comment]
Hi @IxyR4 thank you for your bug report. 
Could you share a project file (file - save project) instead of a cura profile and share it in a comment on Github as a .zip.
So I can take a look at it.

Thank you in advance.

**Comment by IxyR4** [comment]
Yeah sure, just give me some hours and i'll be home

**Comment by Ghostkeeper** [comment]
I think the issue is simply that the parts are too thin to print. But there's no telling without having access to the project file.
