### ISSUE TITLE
Big STL Slicing problem

### ISSUE THREAD

**Issue by GTech92** [Ultimaker/Cura#9424]
### Application Version

4.8.0

### Platform

Windows 10, Windows 7

### Printer

Ender 3 

### Reproduction steps

1. Imported Big STL file (800MB)
2. Clicked SLICE

### Actual results

After clicked SLICE button Cura software do nothing...  Even after hour of waiting there is no progress. 0% GPU usage and 0% CPU usage. The STL file is a cylindered litophane. Tested on PrusaSlicer and there is no problem.

### Expected results

Should slice and generate gcode.

**Comment by fvrmr** [comment]
Hi @GTech92 thank you for your bug report. 
This is a duplicate #3105 here you can see why this is happening. 
Because this is a duplicate I will close this issue.
