### ISSUE TITLE
Vasemodus mit Adaptive Layer Heights

### ISSUE THREAD

**Issue by lwbsbde** [Ultimaker/Cura#9425]
### Application Version

4.8.0

### Platform

Windows10

### Printer

Custom

### Reproduction steps

1. Spiralisieren der äußeren Konturen
2. Adaptive Layer Heights verwenden

### Actual results

Im fertigen GCODE sind an den Stellen, an denen sich die Schichtdicke ändert G0 Befehle. Diese verursachen beim drucken kurze Stops und somit Blobs an der Außenwand.

### Expected results

Gcode ohne diese G0 Befehle

![Screenshot (18)](https://user-images.githubusercontent.com/43827576/111905060-1e918b80-8a4a-11eb-9d36-b67551eea1b3.png)

**Comment by fieldOfView** [comment]
Please use english in this issuequeue.

On a sidenote, "Anpassschichten verwenden" seems like a fairly bad translation of "Use Adaptive Layers". Then again, "Use Adaptive Layers" is a bad name in the first place; "Use Adaptive Layer Heights" would be much clearer.
