### ISSUE TITLE
replacing dots and whitespace in filenames with an underscore or dash

### ISSUE THREAD

**Issue by itCarl** [Ultimaker/Cura#9431]
### Is your feature request related to a problem?

emtrax-ltd/Cura2MoonrakerPlugin#2

### Describe the solution you'd like

it would be really nice if the dots and whitespaces/spaces would be replaced with an underscore or a dash instead of cutting/stripping the Filename.

Examples:
i have a .stl file with the filename "test_head_v1.4 (small).stl"
current filename handling is like "test_head_v1.[gcode | ufp]" (file extension doesn't really matter in thsi example)

would i would like is something like this "test_head_v1_4_small.gcode" or "test_head_v1_4-small.gcode"

EDIT
i would really like to inplement it by myself but unfortunately i dont know python that well.

### Describe alternatives you've considered

renaming the output files by hand isn't fun if you have 50+ files to rename just because cura cuts them every time there is a dot in as versioning in a gcode filename.

### Affected users and/or printers

i always get confused when cura cuts my filenames.

Cura version 4.8.0

**Comment by fvrmr** [comment]
Hi @itCarl thank you for your feature request.
There is a plugin from @fieldOfView that does this: https://github.com/fieldOfView/Cura-CustomJobPrefix
You can download it from the marketplace: Printjob naming or via the link above and add it to the plugin map of Cura.
I will close this issue but let me know if you have more questions.
