### ISSUE TITLE
Cura will not open after install

### ISSUE THREAD

**Issue by jdandy46** [Ultimaker/Cura#9435]
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

I recently Purchased a new HP laptop that runs on Windows (the newest version I assume). I am able to download Cura 4.8 from the Cura website. After downloading, Cura will open and I can add my printer and manipulate files, however, once I close and attempt to open Cura again, it prompts me to uninstall the "old version" before installing the new version (which I just installed). This happens every time. Is there a way to fix this? 

### Actual results

The program runs in administrator mode. when I close the program after initial install, it prompts me to un install.

### Expected results

II do not want to have to do the above steps. I just want the program to work correctly.

**Comment by drsurfer** [comment]
Are you really sure you're clicking the program Icon in start menu, and not the installation program again?
Try to go in C:\Program Files\Ultimaker Cura 4.8.0 and double click on Cura icon there.

**Comment by fvrmr** [comment]
Hi @jdandy46 thank you for your bug report. 
Like @drsurfer mentioned above, could you please check if that works for you. 
Let me know if this works for you.

**Comment by jdandy46** [comment]
So the program is working now. I believe it was installed incorrectly. Thanks 

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 25, 2021 at 6:48 AM, ***@***.***> wrote:   


Hi @jdandy46 thank you for your bug report.
Like @drsurfer mentioned above, could you please check if that works for you.
Let me know if this works for you.

**Comment by fvrmr** [comment]
Great to hear. I will close this issue since it is working!
