### ISSUE TITLE
Print via cloud

### ISSUE THREAD

**Issue by Thes3D** [Ultimaker/Cura#9436]
### Application Version

4.6.3 Enterprise

### Platform

Windows 10

### Printer

Ultimaker 2+ Connect

### Reproduction steps

Setup UMC on network
Connect printer via digital factory
Digital factory sees printer but can not connect because it says it is in different group

### Actual results

Can not print via cloud

### Expected results

Print via cloud

This may seem minor, but clients are paying extra for this feature and it does not work on Cura Enterprise 4.6.3
Is there a more recent version than 4.6.3 for Enterprise?

**Comment by fvrmr** [comment]
Hi @Thes3D thank you for your bug report. 
Could you try to add your printer manually in Cura Enterprise via ip adress? And see if that works.

And 4.6.3 is the most recent version for Enterprise.

**Comment by Thes3D** [comment]
Hi,

Yes I tried with the IP address for the printer and it doesn't work either
manually.

**Comment by fvrmr** [comment]
Could you share your log file in a comment on Github?
You can find you log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by fvrmr** [comment]
Hi @Thes3D please ignore my previous comment because you can't connect your UM2+ Connect in Cura 4.6.3 Enterprise because the UM2+ C profile wasn't in the release of Cura 4.6.3.

**Comment by Ghostkeeper** [comment]
This is supposed to be fixed with release 4.9. Or rather, the UM2+C printer was added in 4.7 but the next Enterprise release is supposed to become 4.9, so it will be available then, once that is stable.

**Comment by Thes3D** [comment]
Ok, thanks for the update.

Kind Regards,

Jaime Cavazos, CEO
THES3D
3D Solutions Partner
Zaimi 43, Triandria
55337 Thessaloniki, GREECE
Tel. +30 2313 052 143
Fax. +30 2313 052 144
Site. thes3d.gr



Subscribe to our Newsletter here
<https://thes3d.us10.list-manage.com/subscribe?u=76c7d3734086dfb36f2b77554&id=8a071fc1e4>
.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
