### ISSUE TITLE
No weight display in Cura

### ISSUE THREAD

**Issue by tukartheek** [Ultimaker/Cura#944]
I am using 2.1.3 and cannot find weight displayed.

**Comment by fieldOfView** [comment]
2.1 does not know about the density of materials, so it cannot calculate the weight of the extruded material.

2.2 has better materialsupport, including the weight.

**Comment by Ghostkeeper** [comment]
There is also Nallath's PrintCostCalculator plug-in: https://github.com/nallath/PrintCostCalculator/commit/baab06bb8e0005fc5241d2084998beeacac6d229
