### ISSUE TITLE
Change dialogue wording Model to Group when working with groups. 

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9448]
### Is your feature request related to a problem?

Not really a problem, it would just feel more intuitive.

### Describe the solution you'd like

Change "Center Selected model" to Center Selected Group" and so on.

### Describe alternatives you've considered

None

### Affected users and/or printers

everyone

(Sorry for the ugly picture, couldn't print screen the dialogue)
![IMG_20210325_093046](https://user-images.githubusercontent.com/32172100/112443930-c9a58c00-8d4d-11eb-8e86-00129008837d.jpg)

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your feature request.
I will also discuss this with the team. Keep you posted!

**Comment by rburema** [comment]
Mad a commit that fixes this (or more accurately, works around it). Should be in 4.9, since we didn't have string-freeze yet :-)

We decided it was easier (also for translations) to just make it 'Center/Delete/Multiply Selected' instead. Hope that addresses the problem!

**Comment by printingotb** [comment]
That works, thanks!
