### ISSUE TITLE
[4.8] Erasing Z-coordinate in the move tool should change the value to 0 instead of empty

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9450]
### Application Version

4.8.0

### Platform

Win7

### Printer

Custom fff

### Reproduction steps

Change the Z-coordinate
Erase the Z-coordinate
Click somewhere else

### Actual results

The box has an empty value

### Expected results

I would expect it to automatically change the value to 0 if I leave the box (by clicking somewhere else).

![Namnlös](https://user-images.githubusercontent.com/32172100/112447116-3b330980-8d51-11eb-8b6a-51e4e38f61e5.png)

Sidenote about some differences:
If enter for example ,5 instead of 0,5, it uses 5 as the value.
If I instead write .5, it uses 0.5 (although it doesn't display the 0).
If I enter 0,5 it changes it to 0.5 as expected.

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your bug report.
I will discuss it with the team, also your side note.
Keep you posted!
