### ISSUE TITLE
Really difficult to get sections of print to be 100% infill. Also settings don't load.

### ISSUE THREAD

**Issue by Sensebellum** [Ultimaker/Cura#9454]
### Application Version

Really difficult to get sections of print to be 100% infill. Also settings don't load.

### Platform

Really difficult to get sections of print to be 100% infill. Also settings don't load.

### Printer

Really difficult to get sections of print to be 100% infill. Also settings don't load.

### Reproduction steps

Really difficult to get sections of print to be 100% infill. Also settings don't load.

### Actual results

Really difficult to get sections of print to be 100% infill. Also settings don't load.

### Expected results

Really difficult to get sections of print to be 100% infill. Also settings don't load.

Really difficult to get sections of print to be 100% infill. Also settings don't load.

**Comment by StuSerious** [comment]
gosh.. people are getting creative even with forms to not fill or provide any info whatsoever 🤣

**Comment by fvrmr** [comment]
Hi @Sensebellum please fill in the form correctly, otherwise we can't help you properly. 
Thank you in advance.

**Comment by Sensebellum** [comment]
Great work!
