### ISSUE TITLE
Cura Material Profile Duplicate/Remove Issue

### ISSUE THREAD

**Issue by PrintPlace** [Ultimaker/Cura#9495]
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

1. Open Preferences > Configure Cura...
2. Browse to Materials section
3. Duplicate Material Profile (e.g. Generic CPE) 

### Actual results

The Duplicated Material Profile can't be removed ("Remove" button is Greyed Out). When a subsequent Material Profile is Duplicated, the previous Material Profile can be removed again, but the newest Material Profile can't be removed ("Remove" button is Greyed Out).

### Expected results

Duplicated Material Profiles can be removed immediately after creating them.

![DuplicateIssue](https://user-images.githubusercontent.com/81819897/113428933-fc97f180-93d7-11eb-8963-fcd87b7d6e68.PNG)

**Comment by fvrmr** [comment]
Hi @WeslyJacobs thank you for your report.
If you activate an other material, then you can remove the duplicated material. 
The reason why is because the material is activated and then you can't delete it. 

Let me know if you activate an other material that you can delete the duplicate.

**Comment by 3DPKid** [comment]
> If you activate an other material, then you can remove the duplicated material.
> The reason why is because the material is activated and then you can't delete it.

=> Thanks for the clarification, this wasn't clear to me, but sounds logical. Meanwhile I tested this out and this is effectively the case.

**Comment by fvrmr** [comment]
Nice, then I will close this issue. Since this is solved!
