### ISSUE TITLE
Skirt/Brim Minimum Length has no effect for Brim

### ISSUE THREAD

**Issue by berberic2** [Ultimaker/Cura#9496]
### Application Version

4.8.0

### Platform

Linux

### Printer

FLSun QQS Pro

### Reproduction steps

· Set “Brim Width” to a small value
· No setting “Skirt/Brim Minimum Length” to large values has no effect.

### Actual results

Brim stays shortNr

### Expected results

Brim gets long

**Comment by rburema** [comment]
I've tried to reproduce this locally, but had no luck.
Could you please send us the project file?

(Info: Please: Save, not export, zip to get github to accept the file, attachments in email-reply are sadly ignored by the system, so please do so via the website.)
