### ISSUE TITLE
unable to start up cura 4.8 on windows 10

### ISSUE THREAD

**Issue by Callsignprofessor** [Ultimaker/Cura#9499]
### Application Version

4.8.0

### Platform

windows 10

### Printer

creality ender 3 pro

### Reproduction steps

I did a clean windows 10 install on a new SSD and when reinstalling cura it shuts down when selecting a printer. tried running it as administrator and a bunch of other stuff but eventually installed 4.6.2. But now I can't import my cura profile (originally made on 4.6.2) 

### Actual results

It shuts down

### Expected results

cura should load the offline printers and when you select your printer cura should be operationall

**Comment by jellespijker** [comment]
Please provide log files.
Goto help -> configuration  folder and the log files should be there

**Comment by Callsignprofessor** [comment]
@jellespijker sorry for my delayed reply, ive checked the config file but it gave the reason "the version is outdated, its 16 and should be 14"

[cura.log](https://github.com/Ultimaker/Cura/files/6272047/cura.log)

**Comment by jellespijker** [comment]
Those should be upgraded by the upgrader plugins. If you look in the marketplace are the upgrader plugins enabled?

**Comment by Callsignprofessor** [comment]
I've checked with the marketplace upgrader plugins. Haven't seen anything that has that exact name but everything in 'marketplace>installed' is checked appart from 4.6 to 4.7 version upgrader.

**Comment by Callsignprofessor** [comment]
So some miracle happend and 4.8 works on my pc! (checked everything but couldn't find the original issue) Profile is loading as well. Thanks @jellespijker for your help :)
