### ISSUE TITLE
unable to import cura profile

### ISSUE THREAD

**Issue by Callsignprofessor** [Ultimaker/Cura#9500]
### Application Version

4.6.2

### Platform

windows 10

### Printer

creality ender 3 pro

### Reproduction steps

Install cura and imported cura profile and it gave a message of successfully imported but it doesn't show on the list. I can make a new profile and export/import it without issues.

### Actual results

It gives a popup "profile successfully imported" but doesnt show in the list

### Expected results

my profile in the list

**Comment by MisterPrintf** [comment]
Not a bug; imported profiles will only show under the printer they have been designed for in most circumstances.

**Comment by Callsignprofessor** [comment]
Yes I know, but it still doesn't import.

Op zo 4 apr. 2021 20:26 schreef MisterPrintf ***@***.***>:

**Comment by jellespijker** [comment]
Can you provide log files and profile files that want to import

**Comment by Callsignprofessor** [comment]
Yes! sorry for my delayed reply.

[cura.log](https://github.com/Ultimaker/Cura/files/6272054/cura.log)

**Comment by Ghostkeeper** [comment]
The log file indicates that you're trying to import a profile created by Cura 4.8 into Cura 4.6.2. 4.6.2 is unable to read the more modern format of profiles (because that simply didn't exist yet when 4.6.2 was released).
