### ISSUE TITLE
SD not read when 128 files

### ISSUE THREAD

**Issue by web-eagle** [Ultimaker/Cura#951]
Hi,
if you have 128 files on the sd-card, it will not display the files on the card

**Comment by Ghostkeeper** [comment]
Cura never displays the files on an SD-card. Not unless you navigate a save-to-file or load-from-file dialogue there anyway.

I think you wanted to post this in the repository for the firmware of the Ultimaker 2? https://github.com/Ultimaker/Ultimaker2Marlin/issues

**Comment by daid** [comment]
The firmware indeed has a hard limit on the number of files, due to memory constrains.

**Comment by thopiekar** [comment]
@daid, has this been added to JIRA? In my opinion this should be added to our FAQ or even to our (future) manuals.
I expected the limit around 1000 or higher, so nobody would even hit that ever.

**Comment by web-eagle** [comment]
Hi, is it possible to show a message like “limit on files on SD is reached…”?
All the best
Axel

Von: Thomas Karl Pietrowski [mailto:notifications@github.com]
Gesendet: Sonntag, 28. August 2016 23:55
An: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Axel Schmidt <axel.schmidt@id2go.de>; Author <author@noreply.github.com>
Betreff: Re: [Ultimaker/Cura] SD not read when 128 files (#951)


@daid<https://github.com/daid>, has this been added to JIRA? In my opinion this should be added to our FAQ or even to our (future) manuals.
I expected the limit around 1000 or higher, so nobody would even hit that ever.

**Comment by web-eagle** [comment]
Hi,
you are right – it belongs to the Ultimaker.

Here is another problem:
This part is not sliced.[cid:image001.png@01D201CE.A679DA20]
This part is not sliced.
I attach also the rsdoc.
Best regards
Axel

Von: Ghostkeeper [mailto:notifications@github.com]
Gesendet: Samstag, 27. August 2016 13:15
An: Ultimaker/Cura <Cura@noreply.github.com>
Cc: Axel Schmidt <axel.schmidt@id2go.de>; Author <author@noreply.github.com>
Betreff: Re: [Ultimaker/Cura] SD not read when 128 files (#951)


Cura never displays the files on an SD-card. Not unless you navigate a save-to-file or load-from-file dialogue there anyway.

I think you wanted to post this in the repository for the firmware of the Ultimaker 2? https://github.com/Ultimaker/Ultimaker2Marlin/issues

**Comment by Ghostkeeper** [comment]
Hi web-eagle, your image seems to have failed to upload. A part is not being sliced? It's probably best to make a new issue out of that.
