### ISSUE TITLE
Adding comments to settings profiles

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9520]
### Is your feature request related to a problem?

I would like to be able to add a comments section to my custom settings profiles.

### Describe the solution you'd like

This would make it easier to remember what settings I want to investigate further and to maintain a change log. 
Or "this setting helped with that issue but I need to remember that it also affects this..."
If the comments also exports/imports with the profile, one could add instructions for others when sharing profiles.

### Describe alternatives you've considered

Keep a document on my computer, save new profiles every time I make a change. Include a readme document when sharing profiles. Memorize every setting and learn how they all interact, which is fun but not for everyone.

### Affected users and/or printers

Anyone

![Skärmklipp](https://user-images.githubusercontent.com/32172100/113857692-1b650200-97a3-11eb-9cf5-6d06c12c6de3.PNG)

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your feature request.
I will discuss this with the team. Keep you posted!

**Comment by Glodigit** [comment]
A possible workaround for now is using the Material Settings plugin. I've put a large majority of my changed settings in the material now as most of the settings are material related in one way or another. As well as being able to compare settings faster since there's no lag like when you change profiles, you could then put the comments in the material comment sections.

**Comment by printingotb** [comment]
That's clever but unfortunately I haven't found materials useful for me even with the plugin. I change a lot of settings to optimize for every print all the time including temp even for the same material. I instead use around 50 settings profiles, a few base profiles and one for every production part as they are all unique and the settings optimized. If I want to test a different value for a setting in a certain profile, I always save a new version so I can go back if it has a negative effect (I sometimes have more than one extra version). It would be simpler to write the change down in the profile instead.

**Comment by fvrmr** [comment]
This issue is related to https://github.com/Ultimaker/Cura/issues/7468 and that issue has been deferred because we won't expect to work on this anytime soon. 

I will close this issue as a duplicate. Hope you understand.
