### ISSUE TITLE
Colorblind Ass

### ISSUE THREAD

**Issue by mbourque** [Ultimaker/Cura#9521]
### Application Version

4.9.0 BETA

### Platform

OSX

### Printer

Creality CR-6 SE

### Reproduction steps

1. Preferences
2. General

### Actual results

You should not refer to color blind people as "Colorblind Ass"

Also no matter if I change theme, nothing happens and setting does not stick.

### Expected results

Change terms to not refer to people as "Ass"
Make these themes settings work

![image](https://user-images.githubusercontent.com/480604/113873226-9d90fe80-9782-11eb-9f77-76369e91dc25.png)

**Comment by mbourque** [comment]
I understand that for setting to take place, you must restart. If so, should notify user of this fact.

**Comment by mbourque** [comment]
Ah - I totally missed that. Thanks

**Comment by rburema** [comment]
Devs: See internal ticket CURA-8161

**Comment by nallath** [comment]
Fixed by https://github.com/Ultimaker/Cura/pull/9545
