### ISSUE TITLE
Setting language does not appear work

### ISSUE THREAD

**Issue by mbourque** [Ultimaker/Cura#9522]
### Application Version

4.9.0 BETA

### Platform

OSX

### Printer

Creality CR-6 SE

### Reproduction steps

1. Preferences
2. General
3. Interface > Language

### Actual results

I change to English, but it does not seem to set and is blank when revisiting the Preferences

### Expected results

It should set and be remembered 

![image](https://user-images.githubusercontent.com/480604/113873697-08dad080-9783-11eb-8d9d-2636e6c53d92.png)

**Comment by rburema** [comment]
Thanks for reporting this. We're aware of this ... it's part of a last minute fix to get the drop-down menu's to work at all on Mac  for the beta.

The language changing itself _should_ work however (that is, if you select say, Spanish in that box, after a restart, Cura should be in Spanish), it's just that the box now doesn't seem to listen to the currently active language. Which should definitely be fixed among the other things that are now wrong with the Preference Screen.

We should already have an internal ticket for this, I'll link it back here when I find it.

**Comment by rburema** [comment]
Devs: See internal ticket CURA-8161

**Comment by jonatanpolak** [comment]
When you click on select "language" something like this happens.
![screen](https://user-images.githubusercontent.com/329401/114560352-e78b5000-9c6c-11eb-8e32-f44624e881a4.jpg)
![screen2](https://user-images.githubusercontent.com/329401/114560360-e9edaa00-9c6c-11eb-8a58-ed89cf322a6f.jpg)
![Ten_Mac](https://user-images.githubusercontent.com/329401/114560401-f540d580-9c6c-11eb-85e5-71ebbf3ebd43.jpg)

**Comment by Ghostkeeper** [comment]
This has been fixed for the 4.9 stable release by https://github.com/Ultimaker/Cura/pull/9545:
![image](https://user-images.githubusercontent.com/2448634/114928985-8bbef380-9e33-11eb-87bd-adfbf022423d.png)
