### ISSUE TITLE
Arachne. Not slicing (possibly defects in the file itself).

### ISSUE THREAD

**Issue by IGO-rek** [Ultimaker/Cura#9527]
### Application Version

Arachne

### Platform

Windows 10

### Printer

DeltaBot

### Reproduction steps

1. Opened the file
2. sliced with custom settings

### Actual results

Nothing. it doesn't slice

### Expected results

There may be a problem with the file, but in theory it should have been sliced.

![Скриншот 07-04-2021 231918](https://user-images.githubusercontent.com/82113847/113910909-2d728f00-97fb-11eb-841b-7d8ebad2a6f9.jpg)
[Slising Arachne.zip](https://github.com/Ultimaker/Cura/files/6273607/Slising.Arachne.zip)

**Comment by GregValiant** [comment]
I don't have a problem slicing the files in 4.8 or 4.9b.  After repairing the STL with MS 3D Builder it still sliced.  Using my printer and my profile on the STL it sliced.

**Comment by konskarm** [comment]
Indeed it hangs in arachne while it slices without an issue in 4.9-beta. I'll raise this with the team.

**Comment by ksihota** [comment]
Check your infill type and see if it is zigzag or line (with Connect Infill Lines checked)
I have several items that begin to slice but then never finish with these settings but work fine with other infill settings.
![image](https://user-images.githubusercontent.com/29150649/114248867-c2859d00-994d-11eb-9154-415228ab3f2d.png)
![image](https://user-images.githubusercontent.com/29150649/114248931-ed6ff100-994d-11eb-8f21-8b9f288d57c4.png)

**Comment by IGO-rek** [comment]
> «Соединить линии заполнения»

Thank you! It really works. I realized that at low fill values and with the "Connect Infill Lines" enabled, it is impossible to cut.

**Comment by dtwolfen** [comment]
I was having this same problem wasn't until I saw this post that I realized how to get it to slice

**Comment by Ghostkeeper** [comment]
We've put this on our backlog, targetting it for when Arachne gets released in a stable build. Developers, see issue CURA-8174.

**Comment by ksihota** [comment]
I have found another time when arachne_engine_beta fails to complete a slice (progress bar disappears and slice does not complete.)
When the line width and number of walls hits a specific point where a new line will not fill a space this seems to happen. I can decrease the line width or decrease the number of walls and it will work, but a certain combinations the slice will fail.
![image](https://user-images.githubusercontent.com/29150649/116119813-aedb7580-a673-11eb-9838-93f297f1f87c.png)
![image](https://user-images.githubusercontent.com/29150649/116119997-eba76c80-a673-11eb-96b7-bc51eda4d349.png)
![image](https://user-images.githubusercontent.com/29150649/116120267-36c17f80-a674-11eb-9049-c9f616e11f93.png)

**Comment by Ghostkeeper** [comment]
@ksihota I can't reproduce your problem with my own testing models. It seems to complete the print fine every time, when I twiddle the line width around an integer number of walls. Do you have a project file to share that reproduces the issue?

**Comment by ksihota** [comment]
@Ghostkeeper  Sorry, I deleted that project. I just did a quick check and it works with my current setup so there must be at least one other setting that is influencing this behaviour. I will try and find the settings where it was happening. If I can reproduce it I will upload the file here.

**Comment by ksihota** [comment]
I went through all the wall settings and can't reproduce it. Maybe it was some other computer issue. Not sure why it was so specific to those 2 Cura settings though. If I discover the relationship I will post it here. Sorry for not investigating more before posting it.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
