### ISSUE TITLE
[4.9 Beta] Tab between Print Setting Fields Broken

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#9529]
### Application Version

4.9 Beta

### Platform

Windows 10 x64

### Printer

UMO

### Reproduction steps

Click into a print setting field, press tab.

### Actual results

Nothing happens.

### Expected results

Move to the next field.

**Comment by Vandresc** [comment]
Hi @CCS86, thank you for your feedback, I could easily reproduce it as well!
Will bring it up with the team.

**Comment by konskarm** [comment]
Thanks for your report @CCS86. This is now fixed for the 4.9 by https://github.com/Ultimaker/Cura/pull/9544/commits/20273098634f81fcf3f8d2ef37a888e357bcf9c3.

**Comment by CCS86** [comment]
Thanks guys!
