### ISSUE TITLE
Enable custom prime tower through Mesh Type

### ISSUE THREAD

**Issue by alonsorobots** [Ultimaker/Cura#9549]
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

I'm printing a very large print in my Ultimaker S5 and the prime tower is breaking when using dual extruders. 

Here being able to tag a mesh as a 'custom prime tower' under mesh type (per model settings) would be super useful.

In my individual case (other people could want to print other custom prime towers): I created a custom prime tower that had a flare at the bottom for more stability, but also 'beams' connecting the prime tower to the part (therefor preventing leverage on prime tower). One of the issues however is that there is no way to force the 'custom prime tower' part to print first before the other parts therefore defeating the point of a prime tower. 

### Actual results

Prime tower breaks and multi week print fails. 

### Expected results

Create a feature where user can label a mesh as a custom 'prime tower' using per model "mesh type".

**Comment by fvrmr** [comment]
Hi @alonsorobots thank you for your report.
Are you aware that you can add a brim to your prime tower and change the size? This might help to prevent breaking the prime tower. 
![Screenshot (153)](https://user-images.githubusercontent.com/77000924/114547127-5614e180-9c5e-11eb-9e90-1e6df60a6f7d.png)

Let me know if that works for you!
