### ISSUE TITLE
Arachne - User specified seam is not aligned

### ISSUE THREAD

**Issue by IGO-rek** [Ultimaker/Cura#9555]
### Application Version

Arachne

### Platform

Windows 10

### Printer

DeltaBot

### Reproduction steps

1. Opened the file
2. Turned the vase so that the seam was at the back
3. Set parameters: Layer High "0.2", Initial Layer High "0.2", Z Seam Alignment "User Specified", Z Seam Position "Back"
4. I set the value of the nozzle to 0.6 in order to print the vase in two walls
5. Sliced with my custom settings
Preview Mode

### Actual results

I saw that there is a retraction designation on layer 525. I printed a vase, and saw that I have a strange line almost along the entire length where there was a point showing a retraction.

### Expected results

I have been using Сura since 15.04.6 version. But most likely I still don't understand much, for me now it is important to make sure that the seam is aligned along the entire length and does not spoil the appearance of the vase.

**Comment by IGO-rek** [comment]
![IMG_20210410_214644](https://user-images.githubusercontent.com/82113847/114277925-20e67480-9a4f-11eb-97dc-7938f7fc1160.jpg)
![IMG_20210410_214605](https://user-images.githubusercontent.com/82113847/114277926-22b03800-9a4f-11eb-8c9c-8ce270901884.jpg)
![IMG_20210410_214549](https://user-images.githubusercontent.com/82113847/114277927-2348ce80-9a4f-11eb-9d99-e5830f8a3e63.jpg)
![IMG_20210410_214711](https://user-images.githubusercontent.com/82113847/114277928-23e16500-9a4f-11eb-87dd-44ae3bd37e83.jpg)
![IMG_20210410_214615](https://user-images.githubusercontent.com/82113847/114277930-25129200-9a4f-11eb-968c-12a5afbbd831.jpg)

**Comment by IGO-rek** [comment]
![Скриншот 10-04-2021 223553](https://user-images.githubusercontent.com/82113847/114277935-30fe5400-9a4f-11eb-99fb-8c17761b821c.jpg)
![Скриншот 10-04-2021 223532](https://user-images.githubusercontent.com/82113847/114277937-322f8100-9a4f-11eb-8482-9b0492ee5448.jpg)

https://user-images.githubusercontent.com/82113847/114277939-32c81780-9a4f-11eb-924f-d8ccc4b7e0c4.mp4

**Comment by IGO-rek** [comment]
[Strange seam behavior.zip](https://github.com/Ultimaker/Cura/files/6290314/Strange.seam.behavior.zip)

**Comment by IGO-rek** [comment]
[Strange seam behavior.zip](https://github.com/Ultimaker/Cura/files/6290324/Strange.seam.behavior.zip)

**Comment by fvrmr** [comment]
Hi @IGO-rek thank you for your bug report.
I can reproduce this issue in Arachne, I will discuss it with the team. 

But in 4.9 beta the seam looks better and is better aligned. 
![Screenshot (154)](https://user-images.githubusercontent.com/77000924/114548840-94130500-9c60-11eb-8808-10f7cdc66968.png)

Can you let me know if you can print better with 4.9 beta?

**Comment by IGO-rek** [comment]
> Hi @IGO-rek thank you for your bug report.
> I can reproduce this issue in Arachne, I will discuss it with the team.
> 
> But in 4.9 beta the seam looks better and is better aligned.
> ![Screenshot (154)](https://user-images.githubusercontent.com/77000924/114548840-94130500-9c60-11eb-8808-10f7cdc66968.png)
> 
> Can you let me know if you can print better with 4.9 beta?

Hi @fvrmr, yes this version is much more stable, I will use it for now. During printing, my flash drive on which there was a code was disconnected, so part of the vase was not printed. But I think that that part is enough to analyze. Those large gaps on the seam indicate too much retraction, I need to adjust it myself. Almost all new layers start from the same point, so I am happy with using cura 4.9, but not Arachne.
![Скриншот 20-04-2021 232936](https://user-images.githubusercontent.com/82113847/115440405-8269c880-a231-11eb-8378-1df46dba53b9.jpg)
![Скриншот 20-04-2021 232952](https://user-images.githubusercontent.com/82113847/115440409-839af580-a231-11eb-8f7d-33ddc23a6843.jpg)
![IMG_20210417_005741](https://user-images.githubusercontent.com/82113847/115440411-84338c00-a231-11eb-9ca6-f3b574de8f06.jpg)
![IMG_20210417_005737](https://user-images.githubusercontent.com/82113847/115440414-84cc2280-a231-11eb-9318-1e381882b531.jpg)
![IMG_20210417_005755](https://user-images.githubusercontent.com/82113847/115440421-8564b900-a231-11eb-9404-024ecee0824f.jpg)

**Comment by fvrmr** [comment]
Hi @IGO-rek thank you for letting me know that is works for you. 
We have a ticket on our backlog for the seam in Arachne.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?  (The Z-seam has undergone a lot of work recently.)
