### ISSUE TITLE
Nozzle Size Management

### ISSUE THREAD

**Issue by Grauenwolf** [Ultimaker/Cura#9559]
### Is your feature request related to a problem?

Nozzle size is probably the most frequently changed thing on a machine. Those of us who only own one machine often have to switch between a fine nozzle for miniatures, the standard 0.4 nozzle, and a large nozzle for bigger, less detailed prints.

Currently the nozzle size is buried in the machine settings. 

### Describe the solution you'd like

I would like a drop-down on the Prepare screen between the machine and filament type drop-downs. This drop-down would just have the nozzle size. 

In the Manage [Print] Profiles window, maybe add an option to specify which nozzle diameters a given print profile applies to. 

### Describe alternatives you've considered

One option I considered was just setting up multiple machine settings and naming them based on their nozzle size. This is somewhat tedious and error prone, as when I find mistakes in one machine setting I have to carefully update all the other machine settings to match.

Also, it's really easy to introduce a mismatch between machine setting and print profile. When I'm printing with a small nozzle, I don't want to see my large print profiles.

### Affected users and/or printers

I think this would be beneficial to anyone with a single printer. Those with multiple printers are less likely to need it, as they can dedicate their printers to specific nozzle sizes.

**Comment by fvrmr** [comment]
Hi @Grauenwolf thank you for your feature request.
You can change the nozzle size for some printers in the material menu. This is depended per printer definition. So if you want to add these for your printer you could add these in the `yourprinter.def.json` file. 
Here you can find more info about the definitions files: https://github.com/Ultimaker/Cura/wiki/Definition-Files-Explained

Let me know if you need help with that.
