### ISSUE TITLE
Enhancement: Relocate "Clear Build Platform" Option After Right Click

### ISSUE THREAD

**Issue by opensourcefan** [Ultimaker/Cura#956]
I right click to move around a lot and the odd time the dialog will come up and I accidentally hit the clear build platform button. Would it be possible to have the dialog box open a slight distance away from the mouse pointer or something else to prevent an accidental platform clear. 

![screenshot from 2016-08-29 16-09-59](https://cloud.githubusercontent.com/assets/10550038/18070593/bda3e62c-6e03-11e6-8f4a-8202b4fba44b.png)

**Comment by nallath** [comment]
The re-load all objects seems like a better choice. That shouldn't break anything if you accidently hit it.

**Comment by Ghostkeeper** [comment]
Made an issue in our internal tracker, so that it can get allocated to a sprint.

Note that it should be possible to undo the clear (Ctrl+Z) as a workaround.

**Comment by opensourcefan** [comment]
This can be closed, clear build platform has been swapped out of the way with reload on 2.3.0

Thank you,  not so scary to right click any more.
