### ISSUE TITLE
Missing section if stl is only printed once

### ISSUE THREAD

**Issue by M-Krieger** [Ultimaker/Cura#9562]
### Application Version

4.8.0

### Platform

MacOS 10.14.6

### Printer

HevoRS

### Project file
[CFFFP_Aufsatz v4 v2.3mf.zip](https://github.com/Ultimaker/Cura/files/6291862/CFFFP_Aufsatz.v4.v2.3mf.zip)

### Reproduction steps

I had a request to print a stl file and had issues with missing section until i realized they aren't missing if I multiply the stl. A simple slice with an up-to-date Prusaslic3er had no issues.

### Missing sections with default settings
* open the stl
* slice it with my default settings
* **Missing sections**
![Screenshot_2021-04-11_at_13_49_44](https://user-images.githubusercontent.com/3592094/114303400-3fd81b80-9ace-11eb-82c1-2aa43d9f4053.jpg)

### Missing sections with multiplied model but print one at a time
* multiply model on print area
* slice again
* set print sequence to "One at a time"
* *Missing sections*
![Screenshot_2021-04-11_at_13_56_05](https://user-images.githubusercontent.com/3592094/114303421-52eaeb80-9ace-11eb-8ad1-c1861b4279e3.jpg)

### No missing sections with multiplied model but print all at once
* multiply model on print area
* slice again
* set print sequence to "All at once"
* *No missing sections*
![Screenshot_2021-04-11_at_13_56_28](https://user-images.githubusercontent.com/3592094/114303426-57af9f80-9ace-11eb-9f4f-ac6efac740c4.jpg)

### Actual results

There are missing sections between walls in the upper part of the model

### Expected results

I expect the mentioned sections to be solid.

**Comment by fieldOfView** [comment]
Please include a link to a project file (File -> Save Project...) so we can have a look at the model and your settings.

**Comment by M-Krieger** [comment]
Thank you for your reply. I added it as a zip file because github won't let me upload .3mf files.

[CFFFP_Aufsatz v4 v2.3mf.zip](https://github.com/Ultimaker/Cura/files/6291861/CFFFP_Aufsatz.v4.v2.3mf.zip)

**Comment by fvrmr** [comment]
Hi @M-Krieger thank you for your bug report. You could try to enable the setting `union overlapping volumes`. 
Let me know if that solves your problem!

**Comment by Ghostkeeper** [comment]
These are indeed self-intersecting meshes. The purpose of Union Overlapping Volumes is to choose whether the overlap of two volumes should be considered outside of the model (convention in some geometry systems) or considered to be inside of the model (more robust for 3D printing, and for meshes that were produced for rendering). So this is expected behaviour.
