### ISSUE TITLE
UI addition

### ISSUE THREAD

**Issue by mikeoverbay** [Ultimaker/Cura#9564]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

It would be really handy to have the current Z displayed for the current slice you are previewing. Beside the slice number would be good. It is just (slice thickness * layer number) correct?

### Describe alternatives you've considered

Doing the math by hand

### Affected users and/or printers

any and all

**Comment by jellespijker** [comment]
Duplicate of #7576 closing this thread in favor of that one.
