### ISSUE TITLE
Will not slice any object

### ISSUE THREAD

**Issue by suckatprinting** [Ultimaker/Cura#9567]
### Application Version

4.8.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

No matter what i do, cura will not slice any object. the slice bar just stays white indefinitely and there is no process in the background. I have allowed the app all permissions possible and I can't find a fix on the internet anywhere.

### Actual results

I cant fix it

### Expected results

Hopefully someone smarter than I am will have a better idea

**Comment by nallath** [comment]
Please attach the Cura log files as indicated by the bug template.

**Comment by pierremilcent** [comment]
Did you try to move the z seam by it location X and Y.
I found that depending on z seam location sometimes the slicing process if blocked, changing value of X & Y solves this, then you have to find the right place.

**Comment by nallath** [comment]
> Did you try to move the z seam by it location X and Y.
> I found that depending on z seam location sometimes the slicing process if blocked, changing value of X & Y solves this, then you have to find the right place.

Could you share a project where it's blocked? It shouldn't be blocking based on the z-seam position.

**Comment by GregValiant** [comment]
On the one hand it sliced fine either way.  On the other hand...

"...is not watertight and consists of 4 sub-meshes".
![Untitled](https://user-images.githubusercontent.com/64202104/115036429-81d0db00-9e9b-11eb-9036-db0284d8e081.png)

I noted this in the sliced model.  I don't know if it's intended or not.  Structurally it doesn't look too good.

![Untitled1](https://user-images.githubusercontent.com/64202104/115038058-299ad880-9e9d-11eb-8159-886b7ba22e79.png)

**Comment by pierremilcent** [comment]
The part is designed for such purpose and print is going well at the end with very good quality?
The fact is that depending of seam position the slicing process may be "blocked", never finishing, or it does work.

I think it is true for objects with no default.
