### ISSUE TITLE
Version 4.9 removed the thin-walled horizontal fill

### ISSUE THREAD

**Issue by coolgua888** [Ultimaker/Cura#9570]
### Is your feature request related to a problem?

1.I used 4.8 slices, a shell just 1mm thick, which was divided into an outer wall of 0.4 and an inner wall of 0.4. The sawtooth or mesh filling in the middle could get the slices as shown in the figure, which could have good strength without delamination.
![2021-04-12 08_47_02-TXY2PRO__model3apple原 - Ultimaker Cura](https://user-images.githubusercontent.com/82374291/114421331-c92f4100-9be7-11eb-8421-64d99aa39dff.png)

![2021-04-12 08_48_23-TXY2PRO__model3apple原 - Ultimaker Cura](https://user-images.githubusercontent.com/82374291/114423215-8a01ef80-9be9-11eb-9adb-e681b7fb3ef8.png)

2.However, I used 4.9 cura slices, and the middle was directly transformed into a straight line. Without transverse filling, the strength would become very poor and the layer would rise.The Settings of the two softwares are the same, hoping to restore to the level of 4.8.
![2021-04-12 08_27_13-TXY2PRO__model3apple - Ultimaker Cura](https://user-images.githubusercontent.com/82374291/114425005-3b555500-9beb-11eb-8e04-31499a1a4237.png)
[walls.zip](https://github.com/Ultimaker/Cura/files/6298111/walls.zip)

### Describe the solution you'd like

4.9 Removed horizontal filling of thin wall, thin wall strength will be reduced, will be stratified

Thin wall with transverse filling, firm

### Describe alternatives you've considered

4.9 Removed horizontal filling of thin wall, thin wall strength will be reduced, will be stratified

Thin wall with transverse filling, firm

### Affected users and/or printers

all

**Comment by fvrmr** [comment]
Hi @coolgua888 thank you for your feature request.
Could you share a project file (file - save project) instead of a stl. In that way it is easier to see the difference and reproduce. 

Thank you in advance.

**Comment by Ghostkeeper** [comment]
It's not expected to overextrude the infill pattern on top of gap filling. The second picture was a bug.
