### ISSUE TITLE
Ошибки при разглаживании (пожалуйста помогите перевезти)

### ISSUE THREAD

**Issue by yankichat** [Ultimaker/Cura#9578]
### Application Version

cura arachne

### Platform

Windows 10

### Printer

flyingbear

### Reproduction steps

Я часто использую функцию разглаживание, вот пару багов которые я нашёл:

1- Разглаживание заходит за печатаемую деталь ориентируясь не на дорожки пластика, а на STL модель (при печати большими соплами это заметнее)
![image](https://user-images.githubusercontent.com/44008550/114707344-c4c36f00-9d32-11eb-8e77-d19ebf697f93.png)

2- Функция границы разглаживания не учитывается 
![image](https://user-images.githubusercontent.com/44008550/114707410-db69c600-9d32-11eb-9a76-9525b796f9b1.png)
![image](https://user-images.githubusercontent.com/44008550/114707493-f3d9e080-9d32-11eb-867a-0cebdb239f58.png)

### Actual results

1- Разглаживание загибает крышку или разглаживает в воздухе.
2- Разглаживание всегда происходит до краёв стенок из-за чего появляется волнообразная крышка.

### Expected results

1- Границы разглаживания должны ориентироваться на границы разглаживаемого слоя, а не на границы модели.
2- При увеличении параметра "Границы разглаживания" дорожки разглаживания должны отступать от границ стенок

**Comment by fvrmr** [comment]
Hi @yankichat thank you for your bug report.
Could you please fill in the form in English. Thank you in advance.

**Comment by yankichat** [comment]
> Привет, @yankichat, спасибо за сообщение об ошибке.
> Не могли бы вы заполнить анкету на английском языке. Заранее спасибо.

I know too little English to write this

**Comment by yankichat** [comment]
> Hi @yankichat thank you for your bug report.
> Could you please fill in the form in English. Thank you in advance.

I know too little English to write this
