### ISSUE TITLE
Import ini profile in 2.3.0

### ISSUE THREAD

**Issue by DarkSpoon** [Ultimaker/Cura#959]
Importing a profile created 15.04.6(.ini) results in an error "File is not a zip file".
![capture](https://cloud.githubusercontent.com/assets/4130330/18176534/9856088e-703b-11e6-8ec7-cd99dca2cbc4.PNG)

**Comment by nallath** [comment]
Nice catch. I've added it to our tracker.

**Comment by nallath** [comment]
Fixed it in d7d18043196734ae98da57ea24033b34cd485765
