### ISSUE TITLE
Cura 4.8.0 and x3g plugin export a blank file

### ISSUE THREAD

**Issue by brainforent** [Ultimaker/Cura#9591]
### Application Version

4.8.0

### Platform

MacOs 11.2.3

### Printer

FlashForge Creator Pro

### Reproduction steps

Activated the Marketplace plugin

### Actual results

The file is blank. Zero info.

### Expected results

A file that is not empty.

**Comment by fvrmr** [comment]
Hi @brainforent thank you for your bug report. 
Could you provide me more information, share your log file? You can find your log file here: `$USER/Library/Application Support/cura/<Cura version>/cura.log`
And does it happen with every file?

**Comment by Ghostkeeper** [comment]
This is better reported here: https://github.com/Ghostkeeper/X3GWriter/issues/30
