### ISSUE TITLE
Unsaved project warning

### ISSUE THREAD

**Issue by KenLucke** [Ultimaker/Cura#9599]
### Is your feature request related to a problem?

I frequently do some tweaks and then forget to save the project before moving on.

### Describe the solution you'd like

A warning dialog reminding the user that the project has not been saved if they try to 
a) close the program, or 
b) clear the build plate, while the "project is dirty" flag is flying.  

```
======================================================================
| Your project has changes that have not been saved. Do you wish to: |
|                              [Cancel] [Continue] [Save New] [Save] |
======================================================================
```

This could have an optional setting in Preferences to toggle this warning on or off.

### Describe alternatives you've considered

Use the system as is.

### Affected users and/or printers

Everyone

**Comment by fvrmr** [comment]
Hi @KenLucke thank you for your feature request.
We have already a ticket on our backlog for this issue, based on a feature request you did before: https://github.com/Ultimaker/Cura/issues/8830
I will add this to this ticket and close this one so we will keep everything in one place.
