### ISSUE TITLE
Failure to launch: 

### ISSUE THREAD

**Issue by tormenteddave** [Ultimaker/Cura#9600]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

none

### Reproduction steps

1. Install Cura 4.9.0 Beta
2. Launch Cura
3. Get error message.

### Actual results

cx_Freeze: Python error in main script (traceback unavailable)

error in sys.excepthook.
Exception: [WinError 43] The network path was not found: 'x:\\4.9-exe\\build\\inst\\bin\\cura_app.py'
Original exception: [WinError 53] The network path was not found: 'x:\\4.9=exe\\build\\inst\\bin\\cura_app.py'

![Capture](https://user-images.githubusercontent.com/64227140/115134077-79c38900-9fca-11eb-976d-c9986cc55009.PNG)

### Expected results

Click 'ok' and it ends the program.  It never launches the app.

**Comment by tormenteddave** [comment]
running it with Admin rights let me in to the program.

**Comment by fvrmr** [comment]
Hi @tormenteddave thank you for your bug report.
Could you share your log file? You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

**Comment by tormenteddave** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/6336415/cura.log)

**Comment by Cobra813** [comment]
> ### Application Version
> 4.9.0
> 
> ### Platform
> Windows 10
> 
> ### Printer
> none
> 
> ### Reproduction steps
> 1. Install Cura 4.9.0 Beta
> 2. Launch Cura
> 3. Get error message.
> 
> ### Actual results
> cx_Freeze: Python error in main script (traceback unavailable)
> 
> error in sys.excepthook.
> Exception: [WinError 43] The network path was not found: 'x:\4.9-exe\build\inst\bin\cura_app.py'
> Original exception: [WinError 53] The network path was not found: 'x:\4.9=exe\build\inst\bin\cura_app.py'
> 
> ![Capture](https://user-images.githubusercontent.com/64227140/115134077-79c38900-9fca-11eb-976d-c9986cc55009.PNG)
> 
> ### Expected results
> Click 'ok' and it ends the program. It never launches the app.

Got the Same issue.

**Comment by evanthomas** [comment]
Me too - identical.

**Comment by fieldOfView** [comment]
If you have a drive mapped to the driveletter X, please use a different drive letter as a workaround.

**Comment by Ghostkeeper** [comment]
This will be fixed with Cura 4.9.1, by moving our build folder on the Windows build server to the `C:` drive rather than the `X:` drive.
