### ISSUE TITLE
Can´t see a z seam

### ISSUE THREAD

**Issue by thestranger0078** [Ultimaker/Cura#9605]
### Application Version

4.9.0 beta

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

beta installed to test the new features... can´t see any z seam.... it´s not showed like on your website

### Actual results

tested diffferent parts.... alway the same. no z-seam

### Expected results

show z-seam

**Comment by thestranger0078** [comment]
https://user-images.githubusercontent.com/74991234/115151064-982d9100-a06b-11eb-9373-f45e03a270e7.MP4

![photo_2021-04-18_17-25-58](https://user-images.githubusercontent.com/74991234/115151069-9b288180-a06b-11eb-89e0-f7795913ffdf.jpg)

**Comment by fieldOfView** [comment]
Cura is running in "compatibelity mode", either because you told it to (in the general preferences), or because your GPU only supports that mode. The z seam is only shown in the "full" mode.

**Comment by GregValiant** [comment]
Those of us that must work in compatibility mode don't get the fancy stuff.  My old laptop doesn't support OpenGL 4.1 but I have a couple of workarounds.
This image is with the Outer Wall Wipe Distance set to 0.0 and the Shell option in the preview is turned on.  You can barely make out the Z seam and it's on a surface, not hidden in a corner.
![Untitled](https://user-images.githubusercontent.com/64202104/115152568-9fd74080-a03f-11eb-983c-f1a3b9979ee4.png)

This image shows the Outer Wall Wipe Distance set to 2.0 and the Shell option is turned off.  After viewing where the Z seam is, then I set things back to normal for printing.
![Untitled1](https://user-images.githubusercontent.com/64202104/115152649-e75dcc80-a03f-11eb-9a0e-1ad6a8b2d0cf.png)

**Comment by thestranger0078** [comment]
![Unbenannt](https://user-images.githubusercontent.com/74991234/115153503-93220f00-a076-11eb-91dc-82bbb438c5ae.JPG)

**Comment by thestranger0078** [comment]
i´m using this on my pc? it´s that not enought for cura??

**Comment by thestranger0078** [comment]
> Those of us that must work in compatibility mode don't get the fancy stuff. My old laptop doesn't support OpenGL 4.1 but I have a couple of workarounds.
> This image is with the Outer Wall Wipe Distance set to 0.0 and the Shell option in the preview is turned on. You can barely make out the Z seam and it's on a surface, not hidden in a corner.
> ![Untitled](https://user-images.githubusercontent.com/64202104/115152568-9fd74080-a03f-11eb-983c-f1a3b9979ee4.png)
> 
> This image shows the Outer Wall Wipe Distance set to 2.0 and the Shell option is turned off. After viewing where the Z seam is, then I set things back to normal for printing.
> ![Untitled1](https://user-images.githubusercontent.com/64202104/115152649-e75dcc80-a03f-11eb-9a0e-1ad6a8b2d0cf.png)

ahhh ok... nice trick..... but first i want to find out why cura 4.9 doesn´t show the seam.... maybe only an setting

**Comment by fieldOfView** [comment]
It looks like that GPU should suffice. It could be that the driver is lying to Cura that it cannot create an OpenGL 4.1 context, or you have inadvertently set the option to `Force layer view compatibility mode` in the general preferences.

**Comment by thestranger0078** [comment]
> It looks like that GPU should suffice. It could be that the driver is lying to Cura that it cannot create an OpenGL 4.1 context, or you have inadvertently set the option to `Force layer view compatibility mode` in the general preferences.

now i found it in general settings... sorry...... thx a lot. problem solved :)

**Comment by fvrmr** [comment]
Since it is solved I will close this issue.
