### ISSUE TITLE
Hi DPI screen bug, not nice startup screen on ubnuntu, splash screen

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#9606]
### Application Version

4.8.0

### Platform

ubunutu

### Printer

none

### Reproduction steps

start cura, see the splash screen

### Actual results

the splash screen is super tiny

### Expected results

it should take more space on screen. Size is in px not in % of screen size. should be fixed.

**Comment by avilab84** [comment]
![cura bug](https://user-images.githubusercontent.com/14994740/115152985-f199be00-a073-11eb-835e-2afd04098470.png)

**Comment by fvrmr** [comment]
Hi @avilab84 thank you for your report.
Could you try with the AppImage of Cura 4.9 beta? And see if it happens there?

**Comment by Ghostkeeper** [comment]
It is shown in the screenshots that the user was already using the AppImage.

**Comment by Ghostkeeper** [comment]
Ah, I misread, the question was to use 4.9.

Nevertheless, I can reproduce this issue on 4.9 as well, by setting my scale to 200% in Ubuntu, so it is a confirmed bug then.

**Comment by Ghostkeeper** [comment]
We've talked this over with the developers and consider this to be quite a minor bug. We'll keep it open in this tracker, but it won't get priority for now.
