### ISSUE TITLE
Combing doesn't work as expected

### ISSUE THREAD

**Issue by devydd** [Ultimaker/Cura#9608]
### Application Version

Arachne_engine_beta 99.9.1

### Platform

Windows

### Printer

Ender 3

### Reproduction steps

Combing: not in skin (or any other setting)

Box with 3 ribs - there are travels across the model (__box_3 stl file).
![2021-04-18_21-15-20_Cura](https://user-images.githubusercontent.com/68201914/115157754-409f1d80-a08b-11eb-8ddf-2d95a0bbe7b5.png)

Box with 2 or 1 rib - fine (__box_1 and __box_2 stl files).
![2021-04-18_21-15-50_Cura](https://user-images.githubusercontent.com/68201914/115157756-41d04a80-a08b-11eb-9af5-3af12dfd9323.png)

## Cura 4.9.0
fine in both cases no travels across the model.
![image](https://user-images.githubusercontent.com/68201914/115158023-7abcef00-a08c-11eb-8810-658c6feac6d6.png)

STL files: [boxes.zip](https://github.com/Ultimaker/Cura/files/6332025/boxes.zip)
Slicer config file: [creality_ender3_pla_hollow_fast_%234.inst.zip](https://github.com/Ultimaker/Cura/files/6332041/creality_ender3_pla_hollow_fast_.234.inst.zip)

### Actual results

see above

### Expected results

as in Cura 4.9.0 (no travels across the model)

**Comment by devydd** [comment]
New finding: with combing mode "Within Infill" setting the "Travel avoid Distance" to a rather large value (5 mm) "fixed" the issue in a rather unexpected way.
![image](https://user-images.githubusercontent.com/68201914/115158288-b73d1a80-a08d-11eb-972e-97bff36d604c.png)

**Comment by fvrmr** [comment]
Hi @devydd thank you for your bug report.
Could you share your project files (file - save project) instead of stl's. I want to see your fix and bug myself :)

**Comment by devydd** [comment]
Sure. I managed to produce even move curious travel paths:

###  Travel avoid Distance = 0 (travel as above)
3mf: [Travel avoid Distance = 0.zip](https://github.com/Ultimaker/Cura/files/6338816/Travel.avoid.Distance.0.zip)

![2021-04-19_22-16-18_Cura](https://user-images.githubusercontent.com/68201914/115297765-e078ac00-a15c-11eb-92d1-a36762693bcb.png)

---
### Travel avoid Distance = 4.503 (threshold value)

3mf: [Travel avoid Distance = 4.503.zip](https://github.com/Ultimaker/Cura/files/6338795/Travel.avoid.Distance.4.503.zip)
![image](https://user-images.githubusercontent.com/68201914/115297366-6b0cdb80-a15c-11eb-9fb3-4eebe3503ab2.png)

---
### Travel avoid Distance = 4.504 (above the threshold value)

3mf: [Travel avoid Distance = 4.504.zip](https://github.com/Ultimaker/Cura/files/6338827/Travel.avoid.Distance.4.504.zip)

![2021-04-19_22-18-00_Cura](https://user-images.githubusercontent.com/68201914/115297973-22a1ed80-a15d-11eb-9498-a0181e165382.png)

---
### Travel avoid Distance = 0 + checked: Outer Before Inner Walls

3mf: [Travel avoid Distance = 0 + OuterBeforeInnerWalls.zip](https://github.com/Ultimaker/Cura/files/6338851/Travel.avoid.Distance.0.%2B.OuterBeforeInnerWalls.zip)

![2021-04-19_22-21-40_Cura](https://user-images.githubusercontent.com/68201914/115298322-9f34cc00-a15d-11eb-92ed-0fe1950ed91b.png)

---
### Travel avoid Distance = 0 + checked: Outer Before Inner Walls + checked: Order Inner Walls By Inset
The strange travels are executing AFTER printing all the lines on a given layer.

3mf: [Travel avoid Distance = 0 +OuterBeforeInnerWalls +OrderInnerWallsByInset.zip](https://github.com/Ultimaker/Cura/files/6338868/Travel.avoid.Distance.0.%2BOuterBeforeInnerWalls.%2BOrderInnerWallsByInset.zip)

![image](https://user-images.githubusercontent.com/68201914/115298665-0b173480-a15e-11eb-9798-a6bf9f7a5a82.png)

**Comment by Ghostkeeper** [comment]
The Travel Avoid Distance >= 4.503mm is expected as that is about the spacing between your walls there. The avoid distance basically says that it's not allowed to come closer than 4.503mm to your model. Since the spacing between the walls is 9mm, anything over 4.5mm should prevent it from going between the walls.

It's also possible that it's different with Order Inner Walls By Inset and Outer Before Inner Walls checked, if that changes the order in which walls are printed.

The combing not working properly with odd numbers of walls was also reported in the discussion thread about the beta, here: https://github.com/Ultimaker/Cura/discussions/9388#discussioncomment-593924 . Developers, refer to CURA-8117.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
