### ISSUE TITLE
Toggle option for translucent helpers in layer view

### ISSUE THREAD

**Issue by nickbuhling** [Ultimaker/Cura#9612]
### Is your feature request related to a problem?

I am a fan of the translucent helper visualization, however there are times (for example when designing the support structures) that it would be useful to switch them to fully opaque again. 

### Describe the solution you'd like

It would be perfect when there was a simple toggle switch or something similar somewhere.

### Describe alternatives you've considered

No alternative. I have seen people using custom themes, but this is too permanent for my taste.

### Affected users and/or printers

Every supports fanatic will enjoy this feature ;)

**Comment by konskarm** [comment]
Hi @nickbuhling. We decided to defer this one, as there is always the option to view select the Color scheme "Material Color" and turn off the Shell and the Infill, which will effectively make your support structure opaque.
