### ISSUE TITLE
Cura 4.9 and Flashforge Creator Pro profile

### ISSUE THREAD

**Issue by brainforent** [Ultimaker/Cura#9619]
### Is your feature request related to a problem?

I'd like to have a native profile from you guys since you already have one for Dreamer NX. I'm having trouble with merge for dual extruding. It merges but does not respect the origin of the stl files. I use the profile made from YouTube [https://www.youtube.com/watch?v=aIy-3M29vcs&t=26s](url). 

### Describe the solution you'd like

The merged files work perfectly.

### Describe alternatives you've considered

I don't have one...

### Affected users and/or printers

Flashforge Creator Pro
2 files:
<img width="762" alt="Screen Shot 2021-04-20 at 14 53 52" src="https://user-images.githubusercontent.com/53477004/115442661-a523bf00-a1e8-11eb-806a-abdb2d633c4b.png">
What I expected:
<img width="762" alt="Screen Shot 2021-04-20 at 14 54 43" src="https://user-images.githubusercontent.com/53477004/115442743-bff63380-a1e8-11eb-9795-f6758b5ea64d.png">
What I get :
<img width="762" alt="Screen Shot 2021-04-20 at 14 55 17" src="https://user-images.githubusercontent.com/53477004/115442785-d00e1300-a1e8-11eb-949f-f5fd4f5d0c8d.png">
Tks a lot

**Comment by fvrmr** [comment]
Hi @brainforent thank you for your request.
I assume this has to with the model. Could you try with another dual color model and see if it works or not?

**Comment by brainforent** [comment]
Hi!
Thanks a lot for your response.
I tried another model, that I sliced differently and works, because all parts are in the same plane. Instead of the model I created that the parts were offset from each other in the Z axe.
The new one that is Ok.:



And the old one that does not merge well.


Should be:

**Comment by GregValiant** [comment]
Cura isn't much of an assembly modeler, but you can fool it.  In the CAD software, if the floating yellow model had another feature it would locate correctly.  Add a circle (concentric to the part) at Z=0 and extrude it -1mm.  When you bring the model into Cura move it into the build plate by setting the Z location to -1mm.  That will put the top of the new rectangle at Z=0, and your model will be located correctly.  You could then "group" it with the purple model sitting on the base.  You will have to turn off "Automatically drop models to the build plate" in Preferences.

**Comment by brainforent** [comment]
Thank you so much!!!
Best Regards
Renata
