### ISSUE TITLE
Gcode is not read by ender 3

### ISSUE THREAD

**Issue by Andersonmainetti** [Ultimaker/Cura#9620]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Installation of the new version without deleting the profiles used in the previous version;
2. stl slicing normally
3.  Saving to memory card
4. loaded in the printer
5. new gcode does not appear on the screen
6. Old Gcode are normal
7. Further attempts are thwarted

### Actual results

It is not possible to use the gcodes generated by Cura 4.9.0 on ender 3 Pro

### Expected results

That works well as in all previous versions of Cura.

**Comment by Ghostkeeper** [comment]
Is it possible to determine what is wrong with the g-code that Cura wrote then?
