### ISSUE TITLE
4.9.0 update, now pc can't find printer

### ISSUE THREAD

**Issue by Tireddadgamer** [Ultimaker/Cura#9623]
**Application version**
4.9.0

**Platform**
Win10

**Printer**
SV-01

**Reproduction steps**
1. Updated
2. Tried to connect printer
3. Got angry that it's not finding it.

******

It's been a day or so, been searching for really anything and everything that could help. Made a non-networked printer profile setting for my SV-01.  Checked again for network printer, found none available.  Loaded up a project and saw that "print via usb" was an option even though according to Cura, no network printer was available.

Started it up and low and behold, the bed started heating up. 

So I guess my PC and SV01 are communicating...they just don't know it.

**Comment by jellespijker** [comment]
Good to know it has been sorted. I skimmed through the manual of the SOV 1 printer and I don't see any network connectivity options that would explain why only USB and SD are options.
