### ISSUE TITLE
[4.9 beta to 4.9.0] Beta says no new version available

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9625]
**Application version**
4.9 beta to 4.9.0

**Platform**
win7

**Printer**
custom fff

**Reproduction steps**
Start cura 4.9 beta = no message to update
Check for updates = no new version available

**Screenshot(s)**
![Skärmklipp](https://user-images.githubusercontent.com/32172100/115510952-98eb4080-a280-11eb-972b-f61f66147f6b.PNG)

**Comment by jellespijker** [comment]
This is unfortunately expected behavior since the version is already defined as 4.9 in the beta version. We are considering broadcasting the new beta releases in the future. Imo this is something that would need to be addressed then as well.

**Comment by fvrmr** [comment]
We have a ticket on our backlog that is related to the updater. I will add this to the ticket.
Developers see CURA-7689

**Comment by nallath** [comment]
https://github.com/Ultimaker/Cura/pull/10189 && https://github.com/Ultimaker/Uranium/pull/715
