### ISSUE TITLE
New feature show "starts" in Linetype not available

### ISSUE THREAD

**Issue by spanzetta** [Ultimaker/Cura#9630]
I don't see this option.. but I am in "compatibility mode" because of "old" graphics card..
Is it that normal?
Thanks

![Clipboard01](https://user-images.githubusercontent.com/49818743/115542865-04450a80-a2a1-11eb-9b32-a586069c87e3.jpg)

**Comment by jellespijker** [comment]
Then you're out of luck unfortunately.
Due to the way in which the rendering is handled.
This isn't an easy fix unfortunately and it is unlikely that we will ever get the time to add this to the compatibility mode.

**Comment by spanzetta** [comment]
Update: after a Windows Update (which eventually fixed ATI/AMD graphics driver) and with Cura 4.9.1 I now can see "starts"
Don't which of the 2 fixed the problem.. but I am anyway happy to enjoy this new very nice feature! even with a very old graphics card (HP 4530s with Intel HD3000 + AMD HD7400M)
Thanks
