### ISSUE TITLE
Slicer adds little bumps to bottom layer of flat bottomed model

### ISSUE THREAD

**Issue by Monguce** [Ultimaker/Cura#9640]
### Application Version

4.9.0

### Platform

windows 10

### Printer

ender 3 v2

### Reproduction steps

Sliced model - should be flat bottomed but has little tiny bumps on the bottom that prevent proper adhesion.

Moved model down 0.1, 0.2, 0.3, 0.4, 0.5 mm - each time still has the bumps on the bottom so the first proper layer isn't on the build plate and adhesion is poor.

See picture.

<img width="1023" alt="Cura_6udULA3Xlb" src="https://user-images.githubusercontent.com/25795909/115588596-d377cc00-a2c6-11eb-88c9-be17dea64341.png">

### Actual results

The flat bottom of the print isn't printed ion the build plate. The 'first' layer is a few tiny blobs. Then what should be the first layer is printed where layer two should be.

It does this in every case - no matter what I set the Y distance to. 

### Expected results

First, the model is flat bottomed so it should print without dropping the model.
If there is a protrusion from the bottom of the model and the 'first' layer really is just a few blobs then dropping the model 0.2 mm (the height of the first layer) should make cura skip that layer and print the proper first layer. This doesn't happen - there are little blobs no matter where I drop the model to.

### Additional information

Please find attached an example of the problem as requested.
Screen shot of problem is included in 'reproduction steps'.

Thank you for your time - I really appreciate the amazing software but I can't work out how to solve this problem.

Cheers!

[jartop3.zip](https://github.com/Ultimaker/Cura/files/6352520/jartop3.zip)

**Comment by GregValiant** [comment]
Make your Initial Layer Horizontal Expansion = 0.
All that fine detail in the grid at the bottom is getting lost due to that setting = -1.0
