### ISSUE TITLE
Bad display of floating point numbers

### ISSUE THREAD

**Issue by Honi60** [Ultimaker/Cura#9643]
### Application Version

4.9.0

### Platform

Win 10

### Printer

mine build

### Reproduction steps

Just install the latest version 4.9.0

### Actual results

Bad visual of numbers see attach file

### Expected results

Normal numbers display

**Comment by jellespijker** [comment]
It seems the attachment that you mentioned wasn't added. Can you add it again?

**Comment by Honi60** [comment]
I send again the screen shot, see that numbers appears distorted

Hanina Golan

**Comment by jellespijker** [comment]
Unfortunately, GitHub doesn't allow attachments to be sent via email. Could you add it via the browser?

**Comment by jellespijker** [comment]
@Honi60 Could you take a look at issue #9667 There is a screenshot attached with that issue and I believe they are the same bug.
