### ISSUE TITLE
Cura 4.9 crash

### ISSUE THREAD

**Issue by snoopyduy** [Ultimaker/Cura#9645]
### Application Version

4.9

### Platform

Windows 7 64b

### Printer

Ultimaker S5

### Reproduction steps

App crashed at first start.

### Actual results

Can't run app

### Expected results

run app

![cura 4 9](https://user-images.githubusercontent.com/82992049/115652658-e090cb80-a357-11eb-88ef-697a9cf78306.png)

**Comment by fvrmr** [comment]
Hi @snoopyduy thank you for your bug report. 
Could you try to update described here: https://github.com/pyinstaller/pyinstaller/issues/4855#issuecomment-676851508

Please let me know if that will solve your issue.

**Comment by stolz55** [comment]
Installing Microsoft security upgrade KB3126587 worked for me. Win 7 64b.  I was getting the same error message when trying to start Cura 4.9.   Now it opens correctly.

**Comment by fvrmr** [comment]
Good to know that the upgrade worked for you @stolz55
