### ISSUE TITLE
Supports and Support Blockers

### ISSUE THREAD

**Issue by cwschwartz01** [Ultimaker/Cura#9651]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Tronxy SA PRO

### Reproduction steps

Used supports and it reduced the print volume so much it was unusable. The same this happened when I use a support blocker. I am using CURA 4.9.

### Actual results

The Print volume was reduced so small that I could not use support blockers or supports.

### Expected results

Small reduction in print volume. 

### Additional information

None

**Comment by fieldOfView** [comment]
We can't even begin to know what went wrong without a better description of what you did, one or more screenshots, or better yet a project (File -> Save project...).

**Comment by cwschwartz01** [comment]
Before 

![image](https://user-images.githubusercontent.com/16761678/115740740-1edcb980-a35d-11eb-9fe9-e296bb2b03d8.png)


After Supports added

![image](https://user-images.githubusercontent.com/16761678/115740972-521f4880-a35d-11eb-8a47-6acdaf9ed647.png)


Add Support Blocks

![image](https://user-images.githubusercontent.com/16761678/115741153-7d099c80-a35d-11eb-8b53-5310d7eb5ae1.png)

**Comment by GregValiant** [comment]
Special Modes | Print Sequence is set to "One at a Time" and so your MaxZ is determined by your gantry height.  Change the setting to "All at Once".

**Comment by cwschwartz01** [comment]
Thanks

**Comment by fvrmr** [comment]
I will close this issue since it is solved!

**Comment by Ghostkeeper** [comment]
Arguably, a support mesh should not be seen as a separate mesh in one-at-a-time mode. This is being tracked in https://github.com/Ultimaker/Cura/issues/4193.
