### ISSUE TITLE
Initial Print temps doesn't work

### ISSUE THREAD

**Issue by dmitche3** [Ultimaker/Cura#9655]
### Application Version

4.8-4.9

### Platform

windows 10

### Printer

Creality 3 V2

### Reproduction steps

When I set the initial print temp to 225 I expect that printing will start when the hotend reaches 220.  I print my first layer at 230 but I begin with printing a priming line.  This setting appears to be ignored regardless of its value.

### Actual results

as explained above

### Expected results

As explained above

**Comment by fvrmr** [comment]
Hi @dmitche3 thank you for your bug report.
Could you provide me a project file (file - save project), so I can try to reproduce this?
