### ISSUE TITLE
Cura filling in holes

### ISSUE THREAD

**Issue by jlpmedia** [Ultimaker/Cura#9661]
### Application Version

3.2.1

### Platform

Windows 10

### Printer

Creality Ender 5+

### Reproduction steps

Loaded File
Sliced

### Actual results

Cura filled in holes. Make Overhang Printable is Not checked.

### Expected results

what should have happened? it should have sliced it correctly. If i rotate the object x-degrees the hole doesnt get filled. geometry is good. no overlapping polys, no stray points, etc

**Comment by GregValiant** [comment]
In Cura, load the model and make your settings.  Go to File | Save Project and create a 3mf file, then post it here.

When the slicing changes due to part orientation on the build plate it is often a problem with the model.
