### ISSUE TITLE
Menus displaying at upper right in stead of under selected button (upper left).

### ISSUE THREAD

**Issue by MarcVer** [Ultimaker/Cura#9671]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

1. Download the newest update
2. use at least 2 monitors. And open cura on second monitor
3. click on a menu option such as "File"
4. the menu will appear upper right instead of left.

### Actual results
Menu opens okay at first monitor
Menu opens upper right on second monitor
Menu doesnt open on third monitor. (probably out of view)

(monitor positions: 1,2,3)
### Expected results

Menu should open under selected menu item.

**Comment by fvrmr** [comment]
Hi @MarcVer thank you for your bug report.
Unfortunately I can't reproduce this issue. So I will leave this open and wait till other users.
Hope you understand!

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
