### ISSUE TITLE
Cura 4.9 won't slice stl file

### ISSUE THREAD

**Issue by timothy1989** [Ultimaker/Cura#9679]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

1. Loaded an STL
2. Click on slice button.

### Actual results

Wait 20 minutes, and do nothing.

### Expected results

Finish slice.

**Comment by nallath** [comment]
It seems that the issue template has not been filled in entirely. Please check our guide on https://github.com/Ultimaker/Cura/wiki/Reporting-issues for more information on what information we need and why we need it.

**Comment by whitebravo** [comment]
same here
