### ISSUE TITLE
exits every time I try to load an object. I have to insert it dragging from a directory

### ISSUE THREAD

**Issue by Made3D-Italia** [Ultimaker/Cura#9680]
### Application Version

4.9.0

### Platform

windows 7/10

### Printer

ultimaker 3

### Reproduction steps

open cura
load an object

### Actual results

cura exits

### Expected results

cura load an object

**Comment by fvrmr** [comment]
Hi @Made3D-Italia thank you for your bug report.
Could you add your log file? You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
