### ISSUE TITLE
Profile Settings Don't Match

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#969]
Application Version: 2.3 beta
Platform: Windows 10

Within the manage profile window on each profile the settings don't match what's on the side settings panel even though there is a note saying "Your current settings match the selected profile."

![settings](https://cloud.githubusercontent.com/assets/2055566/18224792/76615efe-7220-11e6-8f3b-048698e028ae.PNG)

**Comment by fieldOfView** [comment]
Doh, I thought we had this fixed. Thanks for reporting it is still happening.

**Comment by shupack** [comment]
I have this issue as well, also, it's not changing profiles...stuck on low-quality.  I can't select normal or high..

**Comment by numanair** [comment]
@shupack Did you install 2.3 while you had 2.1 installed? My imported profiles are uneditable.

**Comment by shupack** [comment]
@numanair Yes, I had 2.1 for about 20 minutes (didn't look at the download page closely..)

this fixed my issues:

https://github.com/Ultimaker/Cura/issues/960

**Comment by ChrisRiddell** [comment]
@fieldOfView in the current beta what's used when the gcode is built the settings from the side panel or the ones from the profiles window?

**Comment by nallath** [comment]
@ChrisRiddell It uses "user_settings" -> Any settings not yet saved into a profile and "quality_changes" -> Any user changes made based off a "quality" and saved into a profile. Those two are merged and saved into a g-code. 
If you don't make any changes, the settings saved should be empty.

**Comment by fieldOfView** [comment]
Rely on the settings as shown in the sidebar.

**Comment by fieldOfView** [comment]
@ChrisRiddell, could you do us a favor and zip up your profile folder (C:/Users/[your username]/AppData/Local/Cura) so we can have a look?

**Comment by ChrisRiddell** [comment]
Okay this is interesting just checked the profiles window and its changed from when I took the screenshot when I opened this report. (but they still don't match)

![capture22](https://cloud.githubusercontent.com/assets/2055566/18267997/043173ee-7461-11e6-8568-ee3978dbf4bd.PNG)


@fieldOfView Here is my cura folder from appdata
https://dl.dropboxusercontent.com/u/91917089/cura.zip

**Comment by fieldOfView** [comment]
Thanks, that is very helpful, in the sense that it confirms that there is nothing wrong with the files in your archive. The good news is that we seem to have fixed this issue, after the build that went out as the 2.3 beta was made. 

For now, please don't pay attention to what that overview says, we hope to have a new beta build later this week.
