### ISSUE TITLE
Brim as Per Model Settings

### ISSUE THREAD

**Issue by RMFPV** [Ultimaker/Cura#9690]
### Is your feature request related to a problem?

It's currently impossible to remove Brim for some models. It's not needeв to print all models with Brim very often. Just some of them.

### Describe the solution you'd like

Please add Brim to be selected from the menu Per Model Settings.

### Describe alternatives you've considered

No

### Affected users and/or printers

Everyone who wants to print only some models with Brim.

**Comment by fvrmr** [comment]
Hi @RMFPV thank you for your feature request.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/6882 that's why I will close this issue.
Hope you understand!
