### ISSUE TITLE
Cura 4.9.0 crash

### ISSUE THREAD

**Issue by SirWinni** [Ultimaker/Cura#9693]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ultimaker 2+

### Reproduction steps

The error "cura crashed" is only existen if i use the icon to load a file If ei use menu it´s all o.k. Then it has not an error.

Sorry for my english.

### Actual results

--

### Expected results

--

### Additional information

The error "cura crashed" is only existen if i use the icon to load a file If ei use menu it´s all o.k. Then it has not an error.

**Comment by fvrmr** [comment]
Hi @SirWinni thank you for your bug report.
I will close this issue since it is related to #9668
Hope you understand!
