### ISSUE TITLE
4.9.0 Figer sur "découpe en cours..."

### ISSUE THREAD

**Issue by SCHOFFIT** [Ultimaker/Cura#9698]
### Application Version

4.9.0

### Platform

windows 10 entreprise

### Printer

ENDER 3 PRO

### Reproduction steps

Importer fichier .stl
Sélectionner "découpe"

### Actual results

Le message "Découpe en cours...." s'affiche, en dessous la barre grise d'avancement s'affiche mais ne se remplit pas et reste bloqué dans cet état.

### Expected results

Je dois pouvoir ensuite enregistré le fichier .GCODE sur mon ordinateur ou un lecteur extérieur.

**Comment by fvrmr** [comment]
Hi @SCHOFFIT thank you for your bug report.
Could you please fill in the report in English and add your log file?
You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
