### ISSUE TITLE
key in XYZ value no long accept ","

### ISSUE THREAD

**Issue by UM2EXTENDED** [Ultimaker/Cura#9703]
### Application Version

4.9.0

### Platform

macOS 11

### Printer

Ultimaker 2 Extended+

### Reproduction steps

Key in XYZ position values using "," is no longer possible, only . will be accepted.

Example:
Version 4.8 Z=-0,5mm = accepted
Version 4.9 Z=-0,5mm = set to 0
Version 4.9 Z=-0.5mm = accepted

Pls fix it as now really hard to use with (german) num pad.

### Actual results

Object position wrong.

### Expected results

Object position correct.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

na

**Comment by fvrmr** [comment]
Hi @UM2EXTENDED thank you for your bug report.
I can also reproduce this on Windows. I will discuss this with the team. 
Keep you posted!

**Comment by fvrmr** [comment]
We have discussed it with the team. And created a ticket for this on our backlog.
Developers see CURA-8191.

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by UM2EXTENDED** [comment]
It has been fixed already.
