### ISSUE TITLE
Progress Bars Reversed

### ISSUE THREAD

**Issue by SnowflakeSolutions** [Ultimaker/Cura#9711]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Open A Model
2. Slice It - The Progress Bar is moving backwards
3. Save It - The Progress Bar is sliding backwards

### Actual results

The progress bars are reversed.

### Expected results

The progress bars should move from Left-To-Right, might be an issue related to bug #9667 , maybe related to a system with RTL language support?

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6385982/cura.log) - Log File

**Comment by fvrmr** [comment]
Hi @SnowflakeSolutions thank you for your bug report.
I can reproduce this issue when changing the language of my computer to Arabic. So it is indeed related to the language support. It also shows the bug of #9667 so I will close this one as a duplicate. 
And I will discuss that issue with the team. Keep you posted in that thread!
