### ISSUE TITLE
preview doesn't work anymore

### ISSUE THREAD

**Issue by larsdesign** [Ultimaker/Cura#9715]
### Application Version

4.8.0

### Platform

MacBook pro

### Printer

a20t

### Reproduction steps

i sliced it and try open preview 

### Actual results

the preview doesn't work 

### Expected results

and normale it should work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

preview doesn't work on 4.8.0 anymore

**Comment by jellespijker** [comment]
We need the log files for this. Could you add them
