### ISSUE TITLE
Like to add a new printer profile

### ISSUE THREAD

**Issue by NilsRo** [Ultimaker/Cura#9720]
### Is your feature request related to a problem?

Yes, Anycubic Mega profile if not supporting materials

### Describe the solution you'd like

I created a completely new profile so everything is working for Mega S and Pro  I like to provide my new profile https://github.com/NilsRo/Cura_Anycubic_MegaS_Profile to the community but did not know what is the way I can add it to Cura itself. Do I have to fork the repo and do a pull request to the original one that it will be checked? 

### Describe alternatives you've considered

...

### Affected users and/or printers

Anycubic Mega S (and also Mega)

**Comment by fvrmr** [comment]
Hi @NilsRo thank you for your contribution and creating new profiles! 
You can add them by creating a pull request to the master branch of the Cura repo. Then we will check them indeed.
You can find here more info about adding machines: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura

Let me know if you have questions or need help!
