### ISSUE TITLE
Align to build plate not working on model

### ISSUE THREAD

**Issue by sckivitz** [Ultimaker/Cura#9721]
### Application Version

4.9.0

### Platform

Win10

### Printer

Creality Ender 3 (Pro?) 

### Reproduction steps

Trying to slice https://www.thingiverse.com/thing:767995
Click on the bottom of the foot with "align to build plate" tool
Model appears upside down from what I asked.
Instead, the head is aligned to build plate.

### Actual results

head is aligned while feet are sticking straight up

### Expected results

Expected foot to be aligned to build plate 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_jointed_dog_onepiece.zip](https://github.com/Ultimaker/Cura/files/6397211/CE3PRO_jointed_dog_onepiece.zip)
Attached.

**Comment by fvrmr** [comment]
Hi @sckivitz thank you for your report.
This has to do with the model. It seems like it is inverted, you can see on the top red and that shows normally overhang, but there is no overhang when you look at it. 
To fix this you could try the plugin mesh tools and then fix model normals. Let me know if that works for you!
