### ISSUE TITLE
Using Gradual Support Infill Steps Generates GCode which extrudes multiple times over the same spot

### ISSUE THREAD

**Issue by arjeousski** [Ultimaker/Cura#9723]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

CR-10 Mini

### Reproduction steps

I've trying to setup my support interface to be similar to raft as described in https://github.com/Ultimaker/Cura/issues/9192. 
I wanted my support surface to be on top of similar structure as raft, so that some of the material from support surface does down into it therefore making it easier to break away support surface from the model.

So I've setup relatively high support density, and tried to use gradual infill steps to only have that density near the support surface.

1. Set Support density to high number ~80%
2. Set Gradual Support Infill Steps to number 3
3. Slicing creates GCODE which goes over extruding the same place multiple times

### Actual results

Generated GCODE, extrudes over the same spot multiple times
![2021-04-29 09_27_22-CCR10_Support Test - Ultimaker Cura](https://user-images.githubusercontent.com/1074391/116558899-e8a7b880-a8cd-11eb-8c45-dafd37afb805.png)

The edge of the support has alot of material which also affects the bottom of the model
![image](https://user-images.githubusercontent.com/1074391/116558857-e0e81400-a8cd-11eb-97d7-d2e814c5b7e6.png)

![2021-04-29 09_32_19-Photo - Google Photos - Brave](https://user-images.githubusercontent.com/1074391/116558887-e6ddf500-a8cd-11eb-9d87-46dbb67cc4f0.png)

### Expected results

Ensure that there is no extrusion over the same spot multiple times such that support does not go into the model.

### Checklist of files to include

- [x] Log file
- [X] Project file

### Additional information & file uploads

[Support Test Project + STL.zip](https://github.com/Ultimaker/Cura/files/6398965/Support.Test.Project.%2B.STL.zip)

**Comment by fvrmr** [comment]
Hi @arjeousski thank you for your bug report. 
I will discuss this with the team. Keep you posted!

**Comment by jellespijker** [comment]
@fvrmr I think this a duplicate (couldn't find with a quick search) or it might be on our backlog in Jira already

**Comment by fvrmr** [comment]
Couldn't find the duplicate, but it we have a ticket on our backlog indeed. 
Developers see CURA-7848

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
