### ISSUE TITLE
cant connect magna 2 by wifi

### ISSUE THREAD

**Issue by momadac** [Ultimaker/Cura#9727]
### Application Version

4.9.0

### Platform

windows 10

### Printer

hellbot magna 2 230

### Reproduction steps

add a print, search in the local network, nothing.... add by ip, and couldnt connect, with the cura 4.8 and the mks wifi extension i have no problem

### Actual results

it wont connect to my print

### Expected results

the same as cura 4.8with the mks wifi extension

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

the printer that i want to connect by wifi is a hellbot magna 2-230 dual extruder

**Comment by fvrmr** [comment]
Hi @momadac thank you for your report.
We don't maintain wifi printing for other printers than Ultimaker and also not the mks wifi plugin. So you could report this to them.
I will close this issue for that reason.
