### ISSUE TITLE
Lost Low Quality Profile 4.9

### ISSUE THREAD

**Issue by jxer** [Ultimaker/Cura#9728]
### Application Version

4.9.0

### Platform

windows 10

### Printer

ender3 v2

### Reproduction steps

opened program tried to find low quality profile

### Actual results

low quality is no longer there

### Expected results

find low quality

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura_W6dXJScySu](https://user-images.githubusercontent.com/14966494/116646764-e5044800-a946-11eb-9811-dee16d06645f.jpg)

**Comment by Ghostkeeper** [comment]
The Low Quality profile is still there as far as I can see:
![image](https://user-images.githubusercontent.com/2448634/116677705-ce8ed880-a9a8-11eb-95a1-3e47da4eebf0.png)

The set of profiles that are available depends on the printer, the nozzles and the material types that you have active. Going by your list of custom profiles there, could it be that you are printing with TPU? Indeed, TPU only has a profile for Super, Dynamic and Standard. I'm guessing that the people who made that profile found that TPU couldn't extrude material fast enough to print realistically with 0.28mm layer height.

Is that your problem? I'm guessing that there are more reproduction steps than what you wrote down.

**Comment by jxer** [comment]
Thank you that was it. i was printing in TPU.

How does your .6  layer profile work? any issues?

**Comment by Ghostkeeper** [comment]
> How does your .6 layer profile work? any issues?

It's something that came along with project files I loaded in from other issues here on Github. People put those project files in their issue reports so that we can reproduce their slicing issues. I can't actually print them, so I can't tell you how well it works.
