### ISSUE TITLE
wrong de Translation 

### ISSUE THREAD

**Issue by deBugger-** [Ultimaker/Cura#9735]
### Application Version

4.9.0

### Platform

linux

### Printer

Anycubic I3 Mega 

### Reproduction steps

Dear all,

Switch to german i18n and have a look on the main menu bar,

You'll see

"Datei", "Bearbeiten", "Ansicht", "Einstellungen" (1st), "Erweiterungen", "Einstellungen" **(2nd)**, "Hilfe"

There are 2 times Einstellungen, where the second one leads to "Cura konfigurieren ...". This is confusing during in discussions, writing manuals and even help each other.

Please rename the second one to "Konfiguration".  Please note: My native language is German. In this context is the word   "Konfiguration" the best choice.

 
![cura-de-meuebar](https://user-images.githubusercontent.com/7442971/116754866-c024d900-aa09-11eb-9b81-902ee67fbc08.png)

Thank you
 

### Actual results

Main navigation bar which displays 2 equal navigation entry which are leading to different submenus.

### Expected results

A german main navigation instad 
"Datei", "Bearbeiten", "Ansicht", "Einstellungen", "Erweiterungen",  **_"<< Einstellungen >>"_**, "Hilfe"
this
"Datei", "Bearbeiten", "Ansicht", "Einstellungen", "Erweiterungen",  **_"<< Konfiguration >>"_** , "Hilfe"

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No logfile needed.

**Comment by fvrmr** [comment]
Hi @deBugger- thank you for your report. It is changed, see: https://github.com/Ultimaker/Cura/commit/7c954fdc2f85eb5caf0131739215b1872e3f69de

**Comment by deBugger-** [comment]
Dear fvrmr,
Thank you. Please note a update from 4.8.? to 4.9.1 is done. But it seems to be that your work is not included. On my machine (Archlinux) there are still 2 times "Einstellungen" in the main Navigation (de language). Your fix is missing.

Can you confirm this?

**Comment by fvrmr** [comment]
Thank you for reaching out and it is not in 4.9.1 but it will be included in the next release.
