### ISSUE TITLE
error offset anet a8

### ISSUE THREAD

**Issue by sastreae** [Ultimaker/Cura#9741]
### Application Version

4.9.0

### Platform

win 10

### Printer

anet a8

### Reproduction steps

preferencias-configurar cura-impresora-ajuste de maquina-extruder 1-desplasamiento de la tobera sobre eje x: puse -13 para ajustar el offset

### Actual results

cambio el offset del eje z

### Expected results

cambiar el offset del eje x 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no se que poner aca

**Comment by fvrmr** [comment]
Hi @sastreae thank you for your report.
Could you please fill in the form in English and add a project file or log file?
Thank you in advance.
