### ISSUE TITLE
Windows installer can't open files for writing

### ISSUE THREAD

**Issue by OdinochkA15** [Ultimaker/Cura#9744]
### Application Version

4.9.0

### Platform

Windows 7

### Printer

Creality Ender-5

### Reproduction steps

I downloaded the new version 4.9.0 and started installing it. But an error occurs: The file cannot be opened for writing. Now the program is not removed from the Program files and is not installed normally. Put back version 4.8

### Actual results

Does not work

### Expected results

not work

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![Error cura 4 9](https://user-images.githubusercontent.com/83505020/116785661-fa06e580-aac4-11eb-92a1-9fee644d0d76.jpg)
![Error cura 4 9_](https://user-images.githubusercontent.com/83505020/116785773-86b1a380-aac5-11eb-8d6d-5903115eeebe.jpg)

[cura_log.zip](https://github.com/Ultimaker/Cura/files/6409748/cura_log.zip)

**Comment by fvrmr** [comment]
Hi @OdinochkA15 thank you for your bug report. 
This might be related to this issue: https://github.com/Ultimaker/Cura/issues/9663
Can you check if that works for you?

**Comment by OdinochkA15** [comment]
oddly enough, this fixed the installation error.  But the program itself does not start after installation.  cura.exe error

**Comment by fvrmr** [comment]
What is the error you get when trying to open Cura?

**Comment by OdinochkA15** [comment]
the second screen that I attached in the first message.  cura.exe error

**Comment by OdinochkA15** [comment]
while version 4.8 works fine

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
