### ISSUE TITLE
Z-Seam Always at Outside Wall of Object

### ISSUE THREAD

**Issue by FPrefect20** [Ultimaker/Cura#9753]
### Application Version

4.9.0

### Platform

Win 10

### Printer

Anycubic Mega S

### Reproduction steps

Build a simple box with open top.
Slice with cure 4.9 using settings:
- z-seam alignmeng "user defined"
- coordinates representing the inside of the object

### Actual results

Z-Seam visible in CURA (white line) and at the outside of the printed object
(no matter what coordinates are entered)

### Expected results

Z-Seam at the inside (surface of the inner wall)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nothing

**Comment by fvrmr** [comment]
Hi @FPrefect20 thank you for your report. The white line also represents the starting point. 
But could you share your project file (file - save project) so I can take a look at your model and settings.

**Comment by FPrefect20** [comment]
If [-105mm] / [+105mm] is representing the [leftmost / rightmost] "corner" of the object, [0,0] should be the center, right?

![CURA01](https://user-images.githubusercontent.com/65475741/116909586-b1763600-ac44-11eb-9d02-6acd327e53ae.png)

**Comment by FPrefect20** [comment]
(pls. see project file attached)

[TEST_BOX.zip](https://github.com/Ultimaker/Cura/files/6416511/TEST_BOX.zip)

**Comment by fvrmr** [comment]
Hi @FPrefect20 thank you for your project file and screenshot. Now I understand want you would like to have.
You can't get the seam in the middle of the box because a seam will only start at a corner. 
You can find more information about the z seam here: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/shell/z_seam_type.md

Let me know if you have more question. But for now I will close this issue.

**Comment by FPrefect20** [comment]
Hi @fvrmr !
yes, i have more questions - thanks for the offer to ask.  :-) 
Why does it need a corner for a seam? why not place it on a flat wall for example? (there are other slicers doing so)
And if i slice a circle it doesn´t need a corner for the seam to be placed at.

**Comment by fvrmr** [comment]
The seam will always start at a corner, doesn't matter how big the corner is. So a circle has just tiny sides. And on the line where the sides connect the z seam can be added. 

See here: 
![Screenshot (164)](https://user-images.githubusercontent.com/77000924/117313349-1bc9e900-ae86-11eb-9d02-27ee4c6fbfd9.png)

And this is how the seam will look in Cura with that same model:
![Screenshot (165)](https://user-images.githubusercontent.com/77000924/117313848-8bd86f00-ae86-11eb-9b70-b500f1885fb1.png)

Hope this explains how the seam works.

**Comment by Ghostkeeper** [comment]
For more of an explanation on why seams in Cura always start in a corner, see https://github.com/Ultimaker/Cura/issues/8010 .

It's a minor limitation of the data structures in CuraEngine. It simply tracks an integer at which vertex it should start printing a loop, so the seam is then always on a vertex.
