### ISSUE TITLE
Cura auto closing

### ISSUE THREAD

**Issue by YSOng97** [Ultimaker/Cura#9762]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

custom printer

### Reproduction steps

1. Change to custom printer
2. Load stl file
3. Trying to move the object
4. Cura closed automatically

### Actual results

Cura closed automatically

### Expected results

Should remains opening

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fvrmr** [comment]
Hi @YSOng97 thank you for your report. 
Could you share your log file? Otherwise I can't really help you.
You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
