### ISSUE TITLE
Cura 4.9.0 not extruding with 2nd core

### ISSUE THREAD

**Issue by TheDesignerDan** [Ultimaker/Cura#9771]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ultimaker S5 Pro Bundle

### Reproduction steps

1. Printing a PLA part (Core 1) with Breakaway support (Core 2).
2. File is prepared and sent to the printer as normal, using established settings.

### Actual results

1. Whichever print core starts to print (either part or support), works fine, but the second core does not extrude at all.
2.  The printer still follows the full path as if it's printing, but the material is not extruding at all (sometimes still retracted in standby position).
3. Print cores are both clean and clear.
4. When reprinting the same exact .3mf file on Cura 4.8.0, it prints as normal.

### Expected results

Both materials should be extruding as normal, instead of just one or the other.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

N/A

**Comment by nallath** [comment]
It should be fixed for the 4.9.1 release.

See https://github.com/Ultimaker/CuraEngine/pull/1447 && https://github.com/Ultimaker/CuraEngine/pull/1445
