### ISSUE TITLE
Crash to Windows

### ISSUE THREAD

**Issue by DouglasJOlson** [Ultimaker/Cura#9783]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

CR-^SE

### Reproduction steps

1. Open folder button to select a new model to load.
2. Browse directory for model
3. Application closes without warning.

### Actual results

Application closes without warning

### Expected results

Allowed to select a file or files which load to the application to arrange and slice.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Not consistent, but often.
[cura.log](https://github.com/Ultimaker/Cura/files/6436774/cura.log)

**Comment by fvrmr** [comment]
Hi @DouglasJOlson thank you for bug report. 
This is a known issue. Here you can find the duplicate https://github.com/Ultimaker/Cura/issues/9668 and the work around to fix this.
Since it is a duplicate I will close this issue.
