### ISSUE TITLE
crash during a slice

### ISSUE THREAD

**Issue by petitpunch** [Ultimaker/Cura#9787]
### Application Version

4.9.0

### Platform

WIN 10

### Printer

Ender 3

### Reproduction steps

1. import .slt
2. create supports
3. slice

### Actual results

cura crash.

### Expected results

sliced stl

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

thank you
[CE3_helices charlotte 2.zip](https://github.com/Ultimaker/Cura/files/6437869/CE3_helices.charlotte.2.zip)

**Comment by fvrmr** [comment]
Hi @petitpunch thank you for your report.
I can't reproduce this unfortunately does it happen on every model?
Could you also share your log file? You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`
