### ISSUE TITLE
4.9 Cura Crashing on opening STL files

### ISSUE THREAD

**Issue by Dracaratos** [Ultimaker/Cura#9789]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3 v2

### Reproduction steps

I downloaded the file [here](https://www.thingiverse.com/thing:3709178) a 2D nightmare before christmas file, and it opens the file then has a bunch of crash reports as soon as it opens for a lot of different things. It seems from a rough glance that some extension is causing it maybe?

This also happened with a few other files, I got _some_ files to work but I'm unable to discern between what works and doesn't. Exported files from Blender did not open.

### Actual results

Blender opens, crash reports are generated

Crash Report: [cura.log](https://pastebin.com/vXgQaR6z)

### Expected results

Cura opens the file and let's me use it after

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://pastebin.com/vXgQaR6z)
[attempted 3d print](https://www.thingiverse.com/thing:3709178)

**Comment by nallath** [comment]
Something went wrong with the pastebin logfile. Could you re-upload it?

**Comment by Dracaratos** [comment]
Ah sorry it seems to have gone. I managed to reinstall it and update my extensions on the marketplace and that seemed to fix it. (My plugins https://i.imgur.com/7wFGCuU.png) it was Printjob Naming and ThingiBrowser that were not updated and it seems to have fixed the issue.

I still propose that cura doesn't crash from plugin related issues or rather disables them on an update to prevent these kinds of issues
