### ISSUE TITLE
Combing mode Problem

### ISSUE THREAD

**Issue by gottabigproblem** [Ultimaker/Cura#9797]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3 pro

### Reproduction steps

Changed combing mode to all
Then, put the max distance with no retract at 200mm
![Screenshot (2)](https://user-images.githubusercontent.com/83890536/117557113-bde00180-b03d-11eb-80e9-0113b439c507.png)

![Screenshot (3)](https://user-images.githubusercontent.com/83890536/117557126-dd772a00-b03d-11eb-8010-eb12028e49a4.png)
![Screenshot (4)](https://user-images.githubusercontent.com/83890536/117557127-e0721a80-b03d-11eb-9881-3f00a5773f90.png)

### Actual results

There was still stringing

### Expected results

There should have been no stringing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot (2)](https://user-images.githubusercontent.com/83890536/117557135-ebc54600-b03d-11eb-9de7-70597da62e23.png)
![Screenshot (3)](https://user-images.githubusercontent.com/83890536/117557136-ed8f0980-b03d-11eb-8156-0613952a52a6.png)
![Screenshot (4)](https://user-images.githubusercontent.com/83890536/117557137-ef58cd00-b03d-11eb-8c44-57b6e12dbe6e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/83890536/117557139-eff16380-b03d-11eb-9d43-c1634fa10de8.png)

**Comment by GregValiant** [comment]
I think you need to look at other settings.  When you have a part that splits into separate areas (islands) as it gets taller (like a table upside down with the legs sticking up, or a horizontal through hole), those separate areas require the print head to cross a gap.  Combing can't do anything about that.  Retraction distance and speed, travel speed, print temp, maybe Z-hop, Z seam location, layer start, point...those kinds of settings have an effect.  Combing is good when all of a part is contiguous, but has no effect when crossing a gap.  The printer _must_ cross the gap and if it is oozing there's gonna be a string.  Minimizing the oozing is the key.

**Comment by gottabigproblem** [comment]
im using tpu so i cant have retraction but i get what u mean

**Comment by fvrmr** [comment]
Hi @gottabigproblem 
Stringing can be caused by a lot of settings. 
In the settings guide you can read more about stringing: 
https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/troubleshooting/stringing.md

If you want you could share your project file and I can take a closer look and see what you could change.

**Comment by gottabigproblem** [comment]
how do i sahre my project file

**Comment by fvrmr** [comment]
You can share it as a .zip in a comment here on Github. Or share a Google drive link. 

To save a project file go to file - save project.

**Comment by gottabigproblem** [comment]
the

**Comment by GregValiant** [comment]
I think you need to put it in a zip file.  This website doesn't accept 3mf files.
