### ISSUE TITLE
cura filling in hole at bottom of model 

### ISSUE THREAD

**Issue by garyd9** [Ultimaker/Cura#9807]
### Application Version

4.9.0

### Platform

Windows 10 21H1

### Printer

custom/delta

### Reproduction steps

I imported a model with a 6x19x3(mm) rectangular "hole" in it.  I then rotated the model so that the "hole" is at the bottom.  When I'm on the "prepare" screen, the hole at the bottom is visible. 

### Actual results

When I sliced the model, cura acted as if the hole in the bottom didn't exist at all.  No support, no overhang... it just completely filled in the hole!

### Expected results

Cura should have respected the model (including the rectangular hole) and probably tried to support it.\

To see my results, please open the attached project file.  On the prepare screen, rotate to see the hole in the underside of the model.  Then slice it and check the preview screen to see that the hole is completely ignored by Cura.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[test-hole-in-bottom.zip](https://github.com/Ultimaker/Cura/files/6455605/test-hole-in-bottom.zip)
![prepare-screen](https://user-images.githubusercontent.com/1250182/117739533-8fdcf780-b1cc-11eb-9b87-b456f2901341.PNG)
![preview-screen (hole missing)](https://user-images.githubusercontent.com/1250182/117739592-a97e3f00-b1cc-11eb-938e-591bd30da49b.PNG)

**Comment by nallath** [comment]
You enabled the make overhang printable setting. So that is what Cura is doing; It changes the geometry so that the overhang is gone.

**Comment by garyd9** [comment]
duh!  Thank you for pointing out that I had left that option enabled (from another print.)
