### ISSUE TITLE
There are random tiny gaps between inner and outer walls on 2 walls, no infill print

### ISSUE THREAD

**Issue by d-schmidt** [Ultimaker/Cura#9811]
### Application Version

4.9.0

### Platform

windows 10

### Printer

Ender 3v2

### Reproduction steps
2 walls, 0 infill, 0 bottom:
![grafik](https://user-images.githubusercontent.com/3226483/117794558-a2e3dc00-b24d-11eb-8d4a-548a8b3f2a0e.png)

3mf
[moai-flat-fixed.zip](https://github.com/Ultimaker/Cura/files/6458114/moai-flat-fixed.zip)
see travel moves. i.e. layer 16

### Actual results

There are tiny gaps between the walls which cura tries to fill.

### Expected results

The inner wall has a constant offset relative to the outer wall and no gaps appear.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Is this a float rounding problem? I don't get how offset math can be so far off it produces gaps large enough for cura to try to fill them.

**Comment by d-schmidt** [comment]
@fvrmr what does "export" export? Saved as project: 
[moai-flat-fixed.zip](https://github.com/Ultimaker/Cura/files/6460411/moai-flat-fixed.zip)

**Comment by GregValiant** [comment]
When you "Export" then only the model is exported.  It can be as a 3mf model file, OBJ, STL, etc.  When you save "File | Save Project" (also a 3mf file extension) the file includes the printer, your settings, and the model.

**Comment by fvrmr** [comment]
Thank you for your project file. I can't reproduce it either with your file. Does it happen on other models with the same settings?

**Comment by d-schmidt** [comment]
seems this is a @smartavionics bugs. I can't reproduce this anymore

**Comment by smartavionics** [comment]
> seems this is a @smartavionics version bug. I can't reproduce this anymore on vanilla 4.9.0

Then open an issue at https://github.com/smartavionics/Cura
