### ISSUE TITLE
Ventilador de capa ne se activa

### ISSUE THREAD

**Issue by MikeMaker3D** [Ultimaker/Cura#9814]
### Application Version

4.9.1

### Platform

windows 10

### Printer

Ender 3 

### Reproduction steps

El ventilador de capa no se activa aunque este la pestaña de refrigeración de capa activada.

### Actual results

Modelos impresos deformados por exceso de temperatura

### Expected results

Modelos correctamente enfriados con 0 deformaciones.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![imagen_2021-05-12_124848](https://user-images.githubusercontent.com/84075672/117963269-6f25b680-b320-11eb-8a87-93771ac28dd5.png)

**Comment by GregValiant** [comment]
If you would put the gcode file in a zip file and use the File | Save Project command to make a 3mf file with your model and settings, and also put it into the zip file and then post it here that would be good.

**Comment by DjSteker** [comment]
Puedes probar M106 P0 S128 
M106 P(FanIndex)s S(speed)s   

y si no funciona quizás tenga algún fallo la impresora como un cable , a mi me dio un error cuando actualice a la versión 4.9.1 pero corregí el/los valor/es y funciona bien

**Comment by Ghostkeeper** [comment]
Could you communicate in English? We don't speak every language in the world, and English is the norm here.

We still need a project file to be able to debug this error. The Regular/Maximum Fan Speed Threshold seems to be working fine as far as I can tell, and so does the Minimum Layer Time setting.
