### ISSUE TITLE
Back Slash in saving Gcode

### ISSUE THREAD

**Issue by WForret** [Ultimaker/Cura#9822]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Crality Ender 3 Pro

### Reproduction steps

Installed the extensions : Gcode Filename Format
Wanted to save my program, but didn't worked because of the / tat the beginning

### Actual results

Didn't save my project

### Expected results

To delete the back slash befre saving the projects

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![2021-05-13 10_20_20-Save to File](https://user-images.githubusercontent.com/84139079/118138940-e452c380-b3d4-11eb-8d1a-7ead56d11556.png)

**Comment by fieldOfView** [comment]
Please log an issue with the creators of that plugin instead:
https://github.com/rgomezjnr/GcodeFilenameFormat/issues

**Comment by fvrmr** [comment]
I will close this issue since it is not relevant to Cura but to the plugin.
