### ISSUE TITLE
Better and faster variable layer height

### ISSUE THREAD

**Issue by ruredi87** [Ultimaker/Cura#9823]
### Is your feature request related to a problem?

Variable layer height is affecting all print and this causes longer print times

### Describe the solution you'd like

For example You want your print look better and yo do not want to see layer lines but lower layer height means longer print time, because inner walls, outer walls and infills will be exact same height. But if we do outer wall in lower layer height but inner walls and infill at higher layer height, print will be much more quick and quality will be better.  For example if we want to use 0.04 layer height cura will do all layers at 0.04. But with this feature outer walls will be at 0.04, inner walls and infills at 0.16(0.08, 0.12, 0,2 multiples of outer walls parameter, depends on which one you choose) so print look 0.04 layer height but its not fully 0.04. This means 4 times outer walls first at 0.04 layer height than 1 time 0.16 layer height in inner parameters.With this feature outer perimeters must print first because of nozzle height than it should print inner parameters.

### Describe alternatives you've considered

With this feature we should be able to choose also custom variable layer height. This is not depend this feature request but I think that problem is very negative thing if we compare to prusa slicer.

### Affected users and/or printers

It will affect all users if he care printed object's  outer look and if he care print time.

**Comment by fvrmr** [comment]
Hi @ruredi87 thank you for your feature request. 
You can change this for infill with the `infill layer thickness`. But not the for the walls.
Here you find more information why this wouldn't work: https://github.com/Ultimaker/Cura/issues/6322

Since it is a duplicate I will close this issue. Hope you understand.
