### ISSUE TITLE
Crash on pressing scale in Linux appimage

### ISSUE THREAD

**Issue by Ken-2018** [Ultimaker/Cura#9830]
### Application Version

4.9.1

### Platform

linux 4.9.1 appimage / Feren OS

### Printer

Creality CR-10

### Reproduction steps

Trying to resize a 3d file by scale causes Cura to crash hard. I tried it 20 times go to scale the 3mf formatted file and the application closes.

### Actual results

It closes dropping your window crashes hard.

### Expected results

Restart saying an error was detected?

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by smartavionics** [comment]
See #9709.

**Comment by fvrmr** [comment]
I am closing this issue because it is a duplicate of #9709
