### ISSUE TITLE
Build Plate initial layer temperature not set because no variable exists

### ISSUE THREAD

**Issue by BaileyMillerSSI** [Ultimaker/Cura#9832]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Snapmaker A350

### Reproduction steps

1. Changed initial build plate temperature to 10 degrees warmer
2. Changed start gcode variable to material_bed_temperature_initial_layer
3. Sliced and evaluated GCODE
4. Variable not replaced

### Actual results

The M140 command is set to the build plate temperature everywhere, no mention of the initial build plate temperature even once in the GCODE. Variable isn't replaced with initial build plate temperature.

### Expected results

M140 and M190 commands are set to the initial build plate temperature.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![5zAQiWpC5Q](https://user-images.githubusercontent.com/14271740/118308000-6d432b00-b4b9-11eb-89ef-cb1c7dbbbabe.png)
![Cura_SlNAHJc4qA](https://user-images.githubusercontent.com/14271740/118308003-6d432b00-b4b9-11eb-8861-1ebc13bd641f.png)

[Projectfile.zip](https://github.com/Ultimaker/Cura/files/6480364/Projectfile.zip)

**Comment by GregValiant** [comment]
{material_bed_temperature_layer_0} is the keyword you want.  The keyword list is [HERE](http://files.fieldofview.com/cura/Replacement_Patterns.html)

**Comment by fvrmr** [comment]
Hi @BaileyMillerSSI thank you for your report.
I will close this issue. Since @GregValiant suggestion would solve your problem.
But feel free to reach out if you have more questions.
