### ISSUE TITLE
Minimum Support Area not reflected in print but is in Cura display

### ISSUE THREAD

**Issue by csterlin** [Ultimaker/Cura#9838]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

1.  Set Minimum Support Area to 5 mm2
2.  Found small area of support not showing up anymore on Cura display
3.  Printed. 

### Actual results

Found the support still being printed, and actually fell over ruining the printout

### Expected results

The small support area should not have printed

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Additional project files are at dropbox
https://www.dropbox.com/s/a4qhjzxw3rgt00n/Cura_Project_Files.zip?dl=0

Cura generated project file is at dropbox
https://www.dropbox.com/s/n5l8hop2d4vafce/CE3_Knight_PartA.zip?dl=0

**Comment by fvrmr** [comment]
Hi @csterlin thank you for your bug report.
It looks like this is not support but your model.
![Screenshot (174)](https://user-images.githubusercontent.com/77000924/118491652-7f260780-b71f-11eb-9065-6a31e5a84a20.png)

**Comment by csterlin** [comment]
Hmmm... You are right. It should have displayed as light blue. I missed
that. I apologize for cluttering your inbox. I will study any further
issues with better attention to details.
Thanks for your quick analysis and response.
Chuck Sterling

**Comment by csterlin** [comment]
I meant to say that the red line would (not should) have displayed as light
blue had it been intended to be support.
Chuck Sterling

**Comment by fvrmr** [comment]
Hi @csterlin no problem!
