### ISSUE TITLE
scale and resize

### ISSUE THREAD

**Issue by Giovanni-lab782** [Ultimaker/Cura#9842]
### Application Version

4.9.1

### Platform

linux

### Printer

creality ender 3

### Reproduction steps

i open up cura then i load in my files then i click resize

### Actual results

after i click resize, cura closes itself

### Expected results

it should let me resize

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

this happens to every file i upload

**Comment by smartavionics** [comment]
See  #9709
