### ISSUE TITLE
Die Schrift in verschiedenen Menüpunkten nicht lesbar

### ISSUE THREAD

**Issue by Chaossurfer** [Ultimaker/Cura#9846]
### Application Version

4.9.0 / 4.9.1

### Platform

MacOs BigSur 11.3.1 mit Apple M1 Chip

### Printer

Prusa

### Reproduction steps

Also ich habe einen Mac mini mit M1 Chip und die Anzeigefehler die sie in den Bildern sehen. Aber nur in der Version 4.9.0 und 4.9.1. Mit der Version 4.8 habe ich keine Anzeigeprobleme. Habe die Software schon mehrfach komplett deinstalliert und wieder installiert - Ohne Erfolg. Auch bringt das umstellen von Deutsch auf Englisch keinerlei Verbesserung.

Now I translated the whole thing in English in case they do not understand German

So I have a Mac mini with M1 chip and the display errors you see in the pictures. But only in version 4.9.0 and 4.9.1. With version 4.8 I have no display problems. Have the software already several times completely uninstalled and reinstalled - Without success. Also the change from German to English does not bring any improvement.

### Actual results

Es passiert eigentlich nichts ausser das ich die Abschnitte nicht lesen kann

Nothing really happens except that I can not read the sections

### Expected results

Es soll entweder auf Deutsch oder Englisch zu lesen sein und nicht irgendwelche Hieroglyphen

It should be readable either in German or English and not any hieroglyphics

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

<img width="844" alt="Bildschirmfoto 2021-05-16 um 17 12 32" src="https://user-images.githubusercontent.com/71221455/118402681-49274b80-b66b-11eb-8c42-c5e589c1f5e5.png">
<img width="841" alt="Bildschirmfoto 2021-05-16 um 17 12 54" src="https://user-images.githubusercontent.com/71221455/118402683-4cbad280-b66b-11eb-8be0-d1cc9bf4a8e2.png">
<img width="590" alt="Bildschirmfoto 2021-05-16 um 17 12 18" src="https://user-images.githubusercontent.com/71221455/118402720-74aa3600-b66b-11eb-9299-b832685e2edd.png">
[cura.log](https://github.com/Ultimaker/Cura/files/6489458/cura.log)

**Comment by fvrmr** [comment]
Hi @Chaossurfer thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/8993 and it is related to BigSur that doesn't support the Qt library Cura is using.
I will close this because it is a duplicate. I hope you understand.
