### ISSUE TITLE
Failed to import profile: Could not find quality type high in current configuration

### ISSUE THREAD

**Issue by jd759** [Ultimaker/Cura#9848]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Artillery Genius

### Reproduction steps

I installed Cura an tried to import an existing profile.

### Actual results

I get the following error: Failed to import profile: Could not find quality type draft in current configuration

### Expected results

The profile should have been imported.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Cura error](https://user-images.githubusercontent.com/84285414/118406279-acb97500-b67b-11eb-9219-4b7a0b47ed84.PNG)

**Comment by fvrmr** [comment]
Hi @jd759 thank you for your report.
This has to do with that your printer doesn't have the draft quality profile. And the profile you want to import is based on that profile.
You can find here more information about importing profiles: https://github.com/Ultimaker/Cura/issues/8229

Also I am wondering if you had this profile in an other version of Cura?
