### ISSUE TITLE
4.9 and 4.9.1 can't click to select an item, 4.8 still works without issue.

### ISSUE THREAD

**Issue by missdup** [Ultimaker/Cura#9850]
### Application Version

4.9.0 and 4.9.1

### Platform

Mac

### Printer

Creality CR6-SE

### Reproduction steps

Open cura and open file, or open file directly in cura.
Left click to select item - nothing happens.
Can <CONTROL> A to select all which will select every item however if I then want to manipulate it (rotate, move etc) and click on the build plate the item/s are deselected.

### Actual results

Nothing happens when left clicking on an item or when left clicking a selected item to move, resize, rotate it becomes deselected.

### Expected results

Item should be selected when clicked. Equally if item is already selected left click should then enable it to be moved, scaled, rotated etc whereas it does now.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I've restarted Cura, reinstalled Cura, restarted Mac, tried all the solutions listed in this thread: https://community.ultimaker.com/topic/33478-cant-select-any-objects/ including to give cura 'full disk access' in privacy and security but the problem remains (in both 4.9 and 4.9.1).
If I don't need to select the item for any reason the new versions work fine, for anything else I have to use 4.8.

**Comment by fvrmr** [comment]
Hi @missdup thank you for your bug report.
Could you please add your log file? You can find your log file here: `$USER/Library/Application Support/cura/<Cura version>/cura.log`
