### ISSUE TITLE
Missing commits in 2.3

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#986]
I just wondered why CURA-2157 couldn't be verified on JIRA.
I compared 2.3 with master and saw that there are commits which should be in 2.3 but are just available on master.
See: https://github.com/Ultimaker/Cura/compare/2.3...master?expand=1

So on the one hand we can cherry-pick them or do a merge from master to 2.3, but don't know whether there is something new in master which doesn't belong to 2.3.

**Comment by nallath** [comment]
As far as I know there is nothing in master that cant be in 2.3

**Comment by Ghostkeeper** [comment]
Not yet anyway.
