### ISSUE TITLE
Cura 4.9 only makes Blobs on first extruder

### ISSUE THREAD

**Issue by aage-zz** [Ultimaker/Cura#9871]
### Application Version

4.9.0

### Platform

Mac OS Big Sur

### Printer

Ultimaker 3

### Reproduction steps

slice with dual extrus and blobs activated.
if extruder 2 starts first blobs are made for it and not extruder 1 and if extruder 1 starts blobs are made for it and not extruder 2.
it has not been a problem before the update

### Actual results

slice with dual extrus and blobs activated.
if extruder 2 starts first blobs are made for it and not extruder 1 and if extruder 1 starts blobs are made for it and not extruder 2.
it has not been a problem before the update

### Expected results

slice with dual extrus and blobs activated.
if extruder 2 starts first blobs are made for it and not extruder 1 and if extruder 1 starts blobs are made for it and not extruder 2.
it has not been a problem before the update

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

you ask too many questions

**Comment by nallath** [comment]
This has been fixed for 4.9.1.
