### ISSUE TITLE
Attempting to Scale model crashes Cura (Linux Mint)

### ISSUE THREAD

**Issue by photokinetic** [Ultimaker/Cura#9872]
### Application Version

4.9.1

### Platform

Linux Mint 20.1 Cinnamon (Cinnamon Version 4.8.6)

### Printer

Creality Ender 3 V2

### Reproduction steps

1. Imported an .stl into Cura
2. Attempted to click on the "Scale" option

### Actual results

When scale option is clicked, Cura unexpectedly exits

### Expected results

Cura shouldn't unexpectedly exit when you click on the scale option in order to scale your stl model

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6508796/cura.log)

**Comment by smartavionics** [comment]
See #9709
