### ISSUE TITLE
There are no file formats available to write with

### ISSUE THREAD

**Issue by purpleunicorn68** [Ultimaker/Cura#9876]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

AnyCubic

### Reproduction steps

Tried to save STL file to SD card then received error.
Downloaded meshmixer. Still not able to save file on SD card. 
Lost as to what to do next so here I am writing this bug report.

### Actual results

No change

### Expected results

Download file to SD card

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

All project files are failing to save to SD card
[Harley-Davidson_Poker_Chip_holder.zip](https://github.com/Ultimaker/Cura/files/6512578/Harley-Davidson_Poker_Chip_holder.zip)

I have no log file. Not sure how to fine one

**Comment by Ghostkeeper** [comment]
I think your reproduction steps aren't entirely clear to me. This is what I tried:

1. Load the Harley_Poker_chip_holder.stl file you provided from the zip archive into Cura.
2. Go to File -> Export...
3. Navigate to an SD card in the file dialogue.
4. Change the file format in the drop-down from 3MF to STL.
5. Save the file.

Cura then successfully saves and STL file in the SD card for me.

Are those your reproduction steps? Could you make a numbered list like that with individual steps?
