### ISSUE TITLE
Experimental Bridging not in Walls on Bridge Layer 2 and 3

### ISSUE THREAD

**Issue by AcJoker2** [Ultimaker/Cura#9890]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

I've configured the experimental bridge setting as shown here.
I sliced several "bridges" with it.
Before that I tested all bridge settings from min to max, but didn't see any influence on the problem.
Either it is a bug or there are other settings that require this, but which are not documented in the context. Or I couldn't find the info.
![4](https://user-images.githubusercontent.com/60291503/119225439-15817100-bb04-11eb-9619-129c6d6acd58.PNG)

### Actual results

The walls (inside and outside) of bridge layer 2 and 3 are not printed at reduced speed, but at normal wall speed.
In the code, the walls are also declared as normal walls and not as bridges.

In addition, the speed of the walls in the 1st bridge layer is displayed as a speed gradient.
According to the code, the speed is constant at the level of the bridge speed.
So it just seems to be a display bug.

But this could be related to the first error and trigger an incorrect bridge detection for layers 2 and 3.

I also don't understand why more material is extruded in the 1st layer for a short time at the end of the walls.

![1](https://user-images.githubusercontent.com/60291503/119225163-74de8180-bb02-11eb-9b11-1d00b407cb5c.PNG)
![2](https://user-images.githubusercontent.com/60291503/119225165-76a84500-bb02-11eb-86d4-c7cc81c8cb1c.PNG)
![3](https://user-images.githubusercontent.com/60291503/119225167-790a9f00-bb02-11eb-8d32-8f8251591c3e.PNG)

Layer 50 and 51 (Bridge Layer 1 and 2)

[Code.txt](https://github.com/Ultimaker/Cura/files/6526313/Code.txt)

### Expected results

I would expect that the walls will also have a reduced bridge speed, and that in all 3 bridge layers.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Project File
[Bridge 100mm.zip](https://github.com/Ultimaker/Cura/files/6526331/Bridge.100mm.zip)
Log
[cura.log](https://github.com/Ultimaker/Cura/files/6526339/cura.log)

**Comment by smartavionics** [comment]
The walls on bridge layers 2 and 3 use the normal wall settings. That is by design.

The change in speed/flow at the end of a bridge wall is to compensate for the underextrusion that occurs following the bridge wall. My Cura builds (see https://github.com/smartavionics/Cura/releases) feature an extra setting (Bridge Wall End Boost) that controls that feature but, unfortunately, it never became part of UM Cura.

**Comment by AcJoker2** [comment]
Thanks for the explanation. I just don't understand why the walls in layers 2 and 3 are not also declared as bridges.

Should the firmware not regulate the extrusion, at least with LA / PA.
From my point of view, it is very disadvantageous if the slicer intervenes in this way and this cannot be switched off.

So it's not a bug after all, sorry.
