### ISSUE TITLE
Backup from other PC not working

### ISSUE THREAD

**Issue by lukaskurz** [Ultimaker/Cura#9894]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 5

### Reproduction steps

I use Cura on my Desktop PC, which is dual booted with Windows 10 and Linux. Cura is installed on both OS, and I sync settings using the backup function. I wanted to install Cura on my Surface Pro and use the backup function to get all the settings and setup.

Steps:
1. Create Backup on Desktop PC (is already 4.9.1)
2. Start Cura on Surface
3. It asks me, which printer i want to setup (first install), I pick Creality Ender 5 and proceed.
4. Open the backups window and click restore on the latest backup.
5. Cura closes
6. I open cura again, and it asks me for the printer setup again, meaning the backup has not worked. ( even if i select printer, the settings from the backup are not there, so definitely not working)
7. I am sad :(

### Actual results

Cura basically is reset to fresh install mode, asking me which printer I want to set up. This happens after every backup. If I only restart (after printer setup) without backup, the changes are saved, so that should not be the issue.

### Expected results

I expected to have all the printer configs, extensions, print settings and co, like on my desktop PC.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6528072/cura.log)

**Comment by fvrmr** [comment]
Hi @lukaskurz thank you for your report.
I can reproduce this issue as well. I will close this issue, but updates about this issue can be found here: https://github.com/Ultimaker/Cura/issues/9905
