### ISSUE TITLE
When rotating object in Cura, object is resized automatically.

### ISSUE THREAD

**Issue by alexsolon74** [Ultimaker/Cura#9899]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

I added an object into Cura. I needed to rotate the object for better build plate orientation. When I rotated the object, the size of the object changed on its own. I was not in the sizing property only the rotation property.

### Actual results

The object was sized differently than the original size.

### Expected results

That the item maintain its original size.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Please see attached Project file.

[4_TRex_All.zip](https://github.com/Ultimaker/Cura/files/6529236/4_TRex_All.zip)

**Comment by fvrmr** [comment]
Hi @alexsolon74 thank you for your report.
I can't reproduce this issue. Can you share a video of this? 
Is this happening only with this file or does it happen more?
