### ISSUE TITLE
Enhancement: Toggle Part Visibility During Layer View

### ISSUE THREAD

**Issue by opensourcefan** [Ultimaker/Cura#990]
I'm having a tough time seeing the layers through the part ghost image that is created. Any chance that we can have an ability to toggle it on or off. Or maybe it's transparency can be increased or something. 

![screenshot from 2016-09-14 10-48-24](https://cloud.githubusercontent.com/assets/10550038/18523431/112076dc-7a69-11e6-9b79-a3c5dda4d37f.png)

**Comment by fieldOfView** [comment]
The ghosts are supposed to be rendered behind the layers, but that functionality did not quite make it in time for the beta. The should be fixed before the 2.3 final.
