### ISSUE TITLE
Infill Line Multiplier missing from print settings - macOS

### ISSUE THREAD

**Issue by davidewen** [Ultimaker/Cura#9925]
### Application Version

4.9.1

### Platform

macOS

### Printer

Prusa

### Reproduction steps

Looking for Infill Line Multiplier in Print Settings, it's not there.

Look in Preferences, it is there and checked.
![Screen Shot 2021-05-30 at 7 29 00 AM](https://user-images.githubusercontent.com/41236505/120108159-cc8b7700-c118-11eb-882b-f378790ea923.png)

### Actual results

Still not available

### Expected results

I expect to be able to use the option

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

no addition info

**Comment by yet-another-average-joe** [comment]
Maybe you uploaded the wrong screen capture ?
Infill Line Multiplier is under Infill, not Quality.
Type "multiplier" in the search field.

**Comment by davidewen** [comment]
> Maybe you uploaded the wrong screen capture ?
> Infill Line Multiplier is under Infill, not Quality.
> Type "multiplier" in the search field.

You are correct. I realized that after I uploaded the screen shot.

I also discovered that Infill Line Multiplier is only an option for a couple of the infill patterns. I had chosen a pattern that was not available. Once I selected a pattern that the option is available for, it showed up.
