### ISSUE TITLE
richer filament settings

### ISSUE THREAD

**Issue by leonhma** [Ultimaker/Cura#9929]
### Is your feature request related to a problem?

There are very little settings in the 'per-material-settings' tab.

### Describe the solution you'd like

Id like the material settings tab to have the ability to adjust the overhang angle, first layer temp, bridge properties and flow adjustment, please.

### Describe alternatives you've considered

i've tried prusaslicer but the slicing tolerances just dont seem rigth

### Affected users and/or printers

me, myself and i

**Comment by nallath** [comment]
There is a plugin for that: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MaterialSettingsPlugin
