### ISSUE TITLE
Failed print

### ISSUE THREAD

**Issue by epicyclic** [Ultimaker/Cura#9953]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

I sliced a couple of different Fusion 360 generated files and all appears well on the screen.  the files were loaded to printer via micro SD card.

### Actual results

The printer generates the purge line but no skirt and the printer then produces blobs prior to printing.  I checked for a clog but all ok.  
I then uninstalled 4.9.1 and reloaded it but the same happened. 

### Expected results

 Since then I've loaded 4.8.0 and sliced the same files and they have printed fine, exactly as expected, with skirt and no blobs.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

See above.

**Comment by fvrmr** [comment]
Hi @epicyclic thank you for your report.
Did you try to load the same project file from 4.8 in 4.9.1? Or did you create a new file?
Could you share both project files (file - save project) in a zip with me?

**Comment by fvrmr** [comment]
Hi @epicyclic could you post your stl (zipped) in a comment here on Github. It doesn't send the file when replying via email.

**Comment by epicyclic** [comment]
Zipped folder as requested...
[X axis adluster body v9.zip](https://github.com/Ultimaker/Cura/files/6637988/X.axis.adluster.body.v9.zip)

**Comment by fvrmr** [comment]
I can't see anything strange that is causing this. 
Did you print both files (in 4.9.1 and 4.8) with the same SD card?

**Comment by epicyclic** [comment]
Yes, indeed.  Everything was identical, I did try a second SD car and had the same result.
FYI, the file I copied was modified from a .step file from Thingiverse. 
I've just generated a new part to print and will try it with 4.9.1 and let you know what happens.
Thank for your help!

**Comment by epicyclic** [comment]
I'm pleased to say that the new design printed fine in 4.9.1 as did a resliced version of the part that was causing problems!
I'll keep monitoring the situation and report back if I get this error again.

**Comment by fvrmr** [comment]
For now I will close this issue as fixed, but feel free to reach out!
