### ISSUE TITLE
Cura 2.1 Support problem

### ISSUE THREAD

**Issue by Jay-watson** [Ultimaker/Cura#997]
The support material starts off from the bed where it should start from slope of the model. This leads to wasted plastic and the print time increases. I like a lot of the new features in cura 2.1 but this is a show stopper.

![cura 2 1 support issue](https://cloud.githubusercontent.com/assets/22235548/18583120/872fbbf6-7c00-11e6-8364-ec061637693c.JPG)

**Comment by thopiekar** [comment]
You can increase the angle to a higher value than the angle you use in your model.
The setting is available in the sidebar as "Overhang Angle".

**Comment by Jay-watson** [comment]
Hi, i tried increasing but no difference. if I go beyond 90 deg it has no support at all. See below

![cura 2 1 support issue 2](https://cloud.githubusercontent.com/assets/22235548/18587562/9c61522c-7c1a-11e6-896b-d974885265f5.JPG)

**Comment by thopiekar** [comment]
I see now more support? Probably I've got the wrong direction of the angle in mind..
You' already tried to decrease, isn't it?

**Comment by Jay-watson** [comment]
i just tried decrease and the problem doesnt go away. Thanks for your interest here, I am going to have to go back to 15.04 it seems.

**Comment by thopiekar** [comment]
Could you be so kind and upload the file?
Would like to reproduce it here 😉

**Comment by nallath** [comment]
Have you tried the same with 2.3?

**Comment by Jay-watson** [comment]
Here is the file that I have used to demonstrate the problem

[Support issue Cura.zip](https://github.com/Ultimaker/Cura/files/477397/Support.issue.Cura.zip)

**Comment by Jay-watson** [comment]
Well done, problem doesn't exist wih Cura 2,.3 Beta

![cura 2 1 support issue 3](https://cloud.githubusercontent.com/assets/22235548/18596202/e86d5b6e-7c3f-11e6-8ffa-fddeeef46349.JPG)

**Comment by thopiekar** [comment]
👍
