### ISSUE TITLE
Support blockers get grouped upon loading the project, ungrouping them sets Z to 0.

### ISSUE THREAD

**Issue by Hologos** [Ultimaker/Cura#9973]
### Application Version

4.9.1

### Platform

macOS Catalina 10.15.7

### Printer

Creality Ender 3 V2

### Reproduction steps

1. Load model
2. Add support blocker
3. Save the project
4. Close Cura
5. Open cure
6. Load the project
7. Ungroup the model and support blocker

### Actual results

Z position of all support blockers gets set to 0.

### Expected results

They should stay, where they were.

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

Here is [a video](https://user-images.githubusercontent.com/1620004/121787429-45cda400-cbc6-11eb-9dd0-8f684c37ff3d.mov).
Here is [the cura.log](https://github.com/Ultimaker/Cura/files/6642802/cura.log).

**Comment by GregValiant** [comment]
It appears to be OK in Windows 10.  To select a single item from a group in Windows it's CNTRL+LeftClick.  That works too.

**Comment by nallath** [comment]
I've tried this on Linux, it also doesn't load it back as a group. Perhaps it's a OSX only issue?

**Comment by fvrmr** [comment]
I've tried it on macOS Catalina 10.15.7 and couldn't reproduce this. Can you share your project file as a zip?

**Comment by Hologos** [comment]
Hi, I am sorry for not including the files. I had them ready and forgot to include them.
[2021-06-12.bug-report.support-blocker-z-pos-resets.zip](https://github.com/Ultimaker/Cura/files/6665580/2021-06-12.bug-report.support-blocker-z-pos-resets.zip)

**Comment by fvrmr** [comment]
Thank you I can now reproduce this on Windows. I will discuss this with the team. Keep you posted!

**Comment by Hologos** [comment]
Here is a list of 3rd party plugins I have installed.
![Snímek obrazovky 2021-06-17 v 13 29 56](https://user-images.githubusercontent.com/1620004/122388448-2e990880-cf70-11eb-8570-7eeede66cf0c.png)
