### ISSUE TITLE
Program freezing when print speed is set to 50mm/s

### ISSUE THREAD

**Issue by Vaakefjell** [Ultimaker/Cura#9974]
### Application Version

4.9.1

### Platform

macOS Catalina

### Printer

Creality Ender 3

### Reproduction steps

Default print speed for one of my PLA profiles was 70 mm/s. For printing this miniature I set layer height to 0.12, added tree supports, raft, and reduced the speed to 50 mm/s. When the speed was changed, the spinning beach ball of death appeared, and I had to force quit Cura. After repeated attempts, when reopening, I could slice without problem at 70, 60 and 40 mm/s, but at 50 mm/s it crashed again.

After using and tweking the profile on a different model, I am no longer able to reproduce the error.

### Actual results

Cura would freeze shortly after attempting to slice.

### Expected results

That Cura would slice as normal.
[cura.log](https://github.com/Ultimaker/Cura/files/6642797/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Not able to attach the project file.

**Comment by fvrmr** [comment]
Hi @Vaakefjell thank you for your report.
Can you share your project file that causes this error as a zip? Then I can try to reproduce this.
