### ISSUE TITLE
Multiply

### ISSUE THREAD

**Issue by trex246** [Ultimaker/Cura#9978]
### Application Version

4.9.1

### Platform

MAC

### Printer

Ender 3 V2

### Reproduction steps

load a model did a multiply 

### Actual results

screen froze for multiply

### Expected results

should have added more models to build plate

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![after](https://user-images.githubusercontent.com/58950134/121974402-e77aff80-cd44-11eb-88a9-4730e0bbb07e.jpg)
![before](https://user-images.githubusercontent.com/58950134/121974445-fd88c000-cd44-11eb-9cc1-3a9affa1b45f.jpg)

**Comment by fvrmr** [comment]
Hi @trex246 thank you for your report.
Could you share your log file?
You can find your log file here: `$USER/Library/Application Support/cura/<Cura version>/cura.log`
