### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by ribeirosk** [Ultimaker/Cura#9989]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

program hangs on startup "Starting print volume" 

### Actual results

program crashes and won't start 

### Expected results

open the program correctly 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6666693/cura.log)

**Comment by fvrmr** [comment]
Hi @ribeirosk thank you for your bug report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/9847
There you can find also a work around and this is fixed in the next release. 
I will close this issue as a duplicate.
