### ISSUE TITLE
Not print

### ISSUE THREAD

**Issue by defilippi82** [Ultimaker/Cura#9993]
### Application Version

4.9.1

### Platform

ubuntu

### Printer

delta ezt t1

### Reproduction steps

1 when send to print.
2 appears a box "sending data to Octoprint.." and not print

I have control to move with Cura, i can pre hot, extruder and bed with normal boton

### Actual results

nothing, 

### Expected results

resolved

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fieldOfView** [comment]
For problems with the OctoPrint Connection plugin, please use the issue queue at https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues
