### ISSUE TITLE
Support missing from first layer in holes if not printing brim

### ISSUE THREAD

**Issue by i-R0mka** [Ultimaker/Cura#9996]
### Application Version

4.9.1

### Platform

win 10

### Printer

custom

### Reproduction steps

when slicing a model, supports are printed from the second layer

### Actual results

when slicing a model, supports are printed from the second layer

### Expected results

supports should be printed from the first layer

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6675078/cura.log)
[CFFFP_Деталь.zip](https://github.com/Ultimaker/Cura/files/6675083/CFFFP_.zip)
![cura_problem_1](https://user-images.githubusercontent.com/86095717/122516964-7aa38600-d020-11eb-8cd1-25573f51c164.JPG)
![cura_problem_2](https://user-images.githubusercontent.com/86095717/122516979-7f683a00-d020-11eb-9385-ab8ce528527a.JPG)

**Comment by fvrmr** [comment]
Hi @i-R0mka thank you for your report.
Can you share a project file (file - save project). Your 3mf doesn't contain your settings so I can't reproduce your issue.

**Comment by i-R0mka** [comment]
[CFFFP_Деталь1.zip](https://github.com/Ultimaker/Cura/files/6675702/CFFFP_.1.zip)

**Comment by fvrmr** [comment]
If you disable the setting `brim replaces support` the support is printed from the first layer. 
Or you can disable `brim only on outside` and then the support is also printed on the first layer.

**Comment by i-R0mka** [comment]
"brim replaces support" completely disables the printing of support on the first layer, regardless of whether there is a border on this area or not.

**Comment by Ghostkeeper** [comment]
The supports are expected to be printed from the second layer if there is brim in its place on the first layer and Brim Replaces Support is enabled.

If Brim Replaces Support is disabled, the support is expected to be dropped all the way down, and the brim should then go around the support as well. This is what I'm seeing. It doesn't seem to disable printing support on the first layer. Here is a screenshot of the first layer of your project when Brim Replaces Support is disabled:

![image](https://user-images.githubusercontent.com/2448634/123434643-ff684400-d5cc-11eb-9754-7d05cc71cca0.png)

Are you seeing a different result, then?

**Comment by i-R0mka** [comment]
How to get around this bug is clear. This topic was raised precisely because of the illogicality of generating support with these settings. the button description says:
"Enforce brim to be printed around the model even if that space would otherwise be occupied by support. This replaces SOME regions of the first layer of support by brim regions."
In the area where there is no brim, for some reason there is no support. Well, if support is not printed on the first layer, why generate it from the second layer?

**Comment by Ghostkeeper** [comment]
Ah, sorry. Yes. The talk about brims led me away from the original bug report. The problem is actually precisely like you describe. The parts of support in the cavities in this print are omitted on the first layer.

The workarounds seem to be to either have brim inside the holes (which is harder to remove) or to make brim override support. Disabling both causes a bug, yes.

I can't reproduce the issue with different models, but with this model it does reproduce. It's expected to print support on the first layer there.

**Comment by Ghostkeeper** [comment]
We've discussed this issue with the team and added it to our backlog. Developers, please see issue CURA-8357.

**Comment by 3Duke3** [comment]
I can confirm I have struck this issue a number of times. To reproduce you need a model with two concentric footprints. It sort of goes hand in hand with models that have an inside brim generated when "Brim Only on Outside" is selected.

![image](https://user-images.githubusercontent.com/78054669/124854433-6d643080-dffb-11eb-851a-de83d8eb20d8.png)

![image](https://user-images.githubusercontent.com/78054669/124854444-7228e480-dffb-11eb-9aef-a9815c2b9971.png)

**Comment by GregValiant** [comment]
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
